### ISSUE TITLE
[GitHub Stars] error: something went wrong

### ISSUE THREAD

**Issue by gygys** [raycast/extensions#10008]
### Extension

https://www.raycast.com/mrmartineau/search-github-stars

### Description

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/62972588/98a918af-08b0-4c9f-aa33-5fa65ef6b9f8">
something went wrong
You can try reloading, or report the error to the extension developer, by copying the log from the Action Panel 8K

### Steps To Reproduce

macmini M2; Network is fine, tried uninstalling and reinstalling as well.

**Comment by Princeyadav05** [comment]
I was able to reproduce the issue. it is happening specifically for your username.
Will have a look into it.

**Comment by gygys** [comment]
> I was able to reproduce the issue. it is happening specifically for your username. Will have a look into it.

What a funny error, I tried what seems to be an error caused by the letters 'gy'. It worked fine for me until the most recent update though.
