### ISSUE TITLE
[Apple Notes] Extension Seems to have a Lag in Content

### ISSUE THREAD

**Issue by 1activegeek** [raycast/extensions#10009]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

When trying to use the extension, I'm finding that some notes are not showing up using the Search option. When I tried searching this morning for a Reading List file I created yesterday early in the day (sometime before 12PM, and it's now 9AM the next day) and it's not showing up. It appears at first glance every other note created BEFORE that note is present. As I searched for issues about this, I came back to it maybe 10 min later, and suddenly it now appeared.

### Steps To Reproduce

1. Create a new note in Apple Notes
2. Launch Raycast
3. Invoke the Apple Notes Search option
4. Look at the list of files shown in chronological order and notice the missing note
5. Alternatively search for the note, and notice it is not found

<img width="642" alt="image" src="https://github.com/raycast/extensions/assets/6810720/4ce99490-f458-473e-915d-3a1f1967ecf5">
<img width="766" alt="image" src="https://github.com/raycast/extensions/assets/6810720/c384c4f9-bc89-4708-a801-8c2689ca4afc">
<img width="761" alt="image" src="https://github.com/raycast/extensions/assets/6810720/56bb7fd3-0699-4dc4-b64d-bd2970ff03fb">

### Current Behaviour

All notes are not identified and searchable with the Search Apple Notes option.

### Expected Behaviour

All notes should be shown and searchable when using the Search Apple Notes option.

**Comment by 1activegeek** [comment]
This is still an issue. Any chance anyone will be able to help out with this issue? Looks like it's going to be marked Stale, but it doesn't seem to have been reviewed by anyone.

**Comment by thomaslombart** [comment]
Hey @1activegeek, I shipped some updates lately that might fix your issue. Do you still experience it?

**Comment by 1activegeek** [comment]
@thomaslombart It took me a moment, had to update Raycast first, then the new Notes updates came through I believe. It does appear at first glance to be doing better. Creating new notes has a slight delay, but that was me brute forcing it. Regular use I think would be perfectly fine if it doesn't immediately appear. I also noticed the Refresh option when searching so I assume that can grab updates in case I don't see them (used this when brute forcing it 😊 ). All in all, looks good to me! Nice work!! I'll come back if I see any issues arise.

**Comment by 1activegeek** [comment]
And PS - thanks for not letting this issue just die in stale state!! Much appreciated!!
