### ISSUE TITLE
[Bitwarden Vault] Add command to create new Items

### ISSUE THREAD

**Issue by anirudhganwal06** [raycast/extensions#10013]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

The extension serves well when I need to quickly access a password from my Bitwarden vault. But, whenever I need to add another secret in bitwarden, I have to open the vault manually in a browser.

### Who will benefit from this feature?

All users of this extension

**Comment by flokosiol** [comment]
Thanks for this extension! Searching the vault with this extension is much better than searching with the default app. 

Would be great if adding new secrets to the vault would be possible, too!

**Comment by flokosiol** [comment]
@anirudhganwal06 Awesome! Let me know if you need someone to test it. I now how to use the Raycast dev environment and how to run extensions locally. So this should be no problem.
