### ISSUE TITLE
[ColorSlurp] ...

### ISSUE THREAD

**Issue by edheltzel** [raycast/extensions#10010]
### Extension

https://www.raycast.com/Jordan-Ellis/colorslurp

#### Error:
```
Error: Could not open app
```
I get this MacOS popup:
![Screenshot 2024-01-05 at 9 49 13 AM](https://github.com/raycast/extensions/assets/402910/268c37aa-1afa-4146-850b-4513d3efa90c)

### Steps To Reproduce

1. launch raycast
2. search for `slurp`
3. see error

### Current Behaviour

not functioning 

### Expected Behaviour

launch slurp

**Comment by Jordan-Ellis** [comment]
Hi @edheltzel! Is ColorSlurp installed on your computer? If it is, could you tell me what version of ColorSlurp you have? Thanks!

**Comment by edheltzel** [comment]
@Jordan-Ellis I am on `v3.9.2`
