### ISSUE TITLE
[Remove Paywall] ...

### ISSUE THREAD

**Issue by edcet** [raycast/extensions#10035]
### Extension

https://www.raycast.com/tegola/remove-paywall

### Description

can’t download from store.  
![CleanShot 2024-01-07 at 04 37 00@2x](https://github.com/raycast/extensions/assets/94407827/ac7be5e3-d0d4-463d-8eb5-40cc6e633563)

### Steps To Reproduce

call rayast with shortcut
type storeinto command bar
enter store
down arrow until remove paywall addon
cmd + enter to download
encounter error

### Current Behaviour

fails to download

### Expected Behaviour

downloads successfully

**Comment by DannySeidel** [comment]
Hi @edcet,

This is a bug on Raycast's side. There is nothing an extension developer can do. 
Furthermore, I tried to reproduce your error, but everything worked fine for me.

I would recommend you to use the "feedback" command inside Raycast to report this error to the developers.
They usually respond pretty quickly.

**Comment by DannySeidel** [comment]
@raycastbot close this issue
