### ISSUE TITLE
[TickTick] Include priority when adding task

### ISSUE THREAD

**Issue by D-Pagey** [raycast/extensions#10048]
### Extension

https://www.raycast.com/appest/ticktick

### Description

The extension is great, however I wish I could set the priority when adding a task. I found the applescript code but when I tried to include the `priority` arguement, I kept getting AppleScript errors. 

On a side note - why use apple script as opposed to TickTicks REST API? Using the REST API wouldn't be reliant on having the actual TickTick Mac application installed. 

### Who will benefit from this feature?

I assume lots of TickTick users make use of the priority system of organising their todos. 

### Anything else?

```
const result = (await runAppleScript(`
    set result to ""
    tell application "TickTick"
      set result to add task to list "${projectId}" title "${title}" description "${description}"${
      dueDate ? ` due date "${dueDate}"` : ""
    } priority ${3} from "raycast" ${isAllDay ? "with" : "without"} allday
    end tell
  `))  
```
This didnt work for me, I saw from the types that priority is a number.

**Comment by viduycheung** [comment]
This Apple Script doesn't support priority syntax yet.

The REST API needs user authentication, and TickTick Open [API](https://developer.ticktick.com) has a limit on that and it also doesn't work when the user has no internet connection.

**Comment by D-Pagey** [comment]
A lot of the Raycast extensions involve the user logging in and proving their own API key.

Being able to set priority seems like a pretty fundamental feature to any To Do app imo. Enough so to warrant having a go with the REST API. 

Happy to have a look at integrating it if it'd be a welcome addition.
