### ISSUE TITLE
[Toothpick] Bluetooth LE/MIDI Device Support

### ISSUE THREAD

**Issue by jimhuds** [raycast/extensions#10044]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

Being able to connect to Bluetooth LE or MIDI Bluetooth devices would be really convenient. Currently using the app Conji for this (native mac alternative is using MIDI studio in Audio MIDI Setup).

**Comment by VladCuciureanu** [comment]
Hey! At the moment I do not have a lot of free time to work on this but I'll put it in the backlog. Thanks for opening the issue!
