### ISSUE TITLE
[Ollama AI] Configuration options for Translate command

### ISSUE THREAD

**Issue by geshido** [raycast/extensions#10055]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

It would be nice if there would be options for Target language for translate command. At the moment it uses Spanish as a target language.

**Comment by MassimilianoPasquini97** [comment]
Hi @geshido,
I have implemented this feature on #10098. Now Command 'Translate' require to chose the destination language.
