### ISSUE TITLE
[Arc] Missing history from some spaces / profiles when using "search history" command

### ISSUE THREAD

**Issue by marcmagn1** [raycast/extensions#10057]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

When using search history command, it looks like the extension doesn't consider the whole history in the case of a user with multiple profiles and multiple spaces. It only shows history from one profile or one set of space hard to converse.

### Steps To Reproduce

1. Set up multiple profiles on one arc browser. 
2. Set up multiple spaces for each profile. 
3. Visit a set of pages on each space
4. Check if anything is missing in the history via Raycast commands

### Current Behaviour

Search history only retrieves pages visited from one profile or one set of spaces.

### Expected Behaviour

Search history command should retrieve pages visited across all profiles and all spaces.

**Comment by aprice42** [comment]
I am seeing this issue as well.
