### ISSUE TITLE
[Apple Reminders] Add ability to copy the current context from currently active app into the reminder

### ISSUE THREAD

**Issue by abhishekmadhu** [raycast/extensions#10058]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Thank you for building such an amazing product. 

I would like to have the ability to generate and add a link to the currently open URL/EMail (in mac Mail) to a task that I add to the Reminders using the "reminder" extension. Something like [this](https://culturedcode.com/things/support/articles/2803569/#:~:text=Quick%20Entry%20(Mac%20only)). 

How I envision it to work:
1. User is in a specific application (say, Apple Mail)
2. User presses the shortcut/hotkey to open "Create New Reminder" window
3. The context will be automatically populated. 
4. For "Apple Mail", the "subject" of the reminder should be set to the "subject" line of the email. Also, a permalink to the email should be added to the "link" field of the reminder. (Clicking on this link in future should open up the specific email). 
5. For "Browsers", the "subject" of the reminder should be set to the "title" of the page (that is shown on hovering on the browser tab), and the "link" field of the reminder will contain the URL of the webpage. 
6. Similar smart context should be added for all relevant applications, but these two are the most important for daily users in my personal opinion. 
7. The "Subject" of the reminder should be "selected" when the "Create new Reminder" window opens, so that the user can just start typing to override the default subject. 

### Who will benefit from this feature?

Any user who uses native apple reminders to quickly capture information will benefit from this, especially followers of Thiago Forte, who demonstrated how one can easily handle their emails quickly.

**Comment by thomaslombart** [comment]
Thanks for the feature request. I'll discuss that with the team 🙂

**Comment by HairyOtter07** [comment]
+1, I was just about to try scripting this myself when I stumbled across this issue.
Though I am curious, is there any way to read/copy the user selected text from script commands or the extension API?

**Comment by thomaslombart** [comment]
We've taken a look at that, and we've decided it's something we'd like to explore further down the road, but not for now. I'll keep this issue alive in the meantime.

**Comment by weitzman** [comment]
This is now possible with https://developers.raycast.com/api-reference/browser-extension. Would love to see it.
