### ISSUE TITLE
[Pins] Command Terminated: Show Pins Code: 2 (Unhandled Extension Rejection)

### ISSUE THREAD

**Issue by MickyGH** [raycast/extensions#10065]
### Extension

https://www.raycast.com/HelloImSteven/pins

### Description

Hi,

I get a "Command Terminated: Pins: Show Pins - Code: 2 (Unhandled Extension Rejection)" error when opening command "Show Pins".

Fresh last Raycast version install on MacOS Sonoma 14.2.1, just this third party extension installed from Store.

### Steps To Reproduce

Open Show Pins command.

**Comment by SKaplanOfficial** [comment]
Looking into this.
