### ISSUE TITLE
[YouVersion Bible Suggest] Add Ukrainian language

### ISSUE THREAD

**Issue by JekRock** [raycast/extensions#10061]
### Extension

https://www.raycast.com/caleb531/youversion-suggest

### Description

I would love to see the Ukrainian language in the list of available Bible languages

### Who will benefit from this feature?

I will be able to use the extension to read the Bible in my native language

**Comment by caleb531** [comment]
@JekRock Sure, absolutely! Which version/translation should I use as the default version for the language setting? In other words, what is the most popular / common Ukrainian Bible translation? Here's the list of versions/translations that YouVersion supports for the Ukrainian language:

https://www.bible.com/languages/ukr

Of course, I'll add support for all these versions—it's just a matter of which one is the default.

**Comment by JekRock** [comment]
@caleb531 thank you for your quick response!
I would say [CUV](https://www.bible.com/versions/3786-CUV-) should be the default.

**Comment by caleb531** [comment]
@JekRock Excellent, I have noted that! I'll start work on implementing this, and should have something within the next few days. The Raycast extension review process will probably also add some time, but rest assured I'll be working on this!

**Comment by JekRock** [comment]
@caleb531 thank you so much!

**Comment by caleb531** [comment]
@JekRock Just wanted to make sure you saw that the new YouVersion Bible Suggest release (with Ukrainian support) has been approved and published! I believe the extension will automatically update within Raycast.

**Comment by JekRock** [comment]
@caleb531 I have already updated the extension to the latest version, and it's awesome!
Thank you so much for your work!

Blessings 🙏
