### ISSUE TITLE
[Hue] Error: self-signed certificate

### ISSUE THREAD

**Issue by GpL-inc** [raycast/extensions#10069]
### Extension

https://www.raycast.com/pindab0ter/hue

### Description

Error: self-signed certificate

TLSSocket.onConnectSecure:node:_tls_wrap:1659:34
TLSSocket.emit:node:events:514:28
TLSSocket.emit:node:domain:488:12
TLSSocket._finishInit:node:_tls_wrap:1070:8

### Steps To Reproduce

0.Updated Hue Bridge version

**AUTOMATIC**
1. Launch Raycast
2. Type Hue
3. Click on Control Lights
4. Press the Hud Bridge Button
**MANUAL**
1. Launch Raycast
2. Go to Raycast settings
3. Go to Hue extension
4. Find the ip address from my router & set it in the extension parameters
5. Set the username that I got by using the CLIP api (huebridgeapi/debug/clip.html)
[after testing a get action on the same interface with that exact user name > it did display all informations about the Hue lights in my house]

### Current Behaviour
**AUTOMATIC**
Shows nothing or specifies something went wrong
**MANUAL**
Returns "Failed to link with bridge : Error self-signed certificate"

### Expected Behaviour
It should work.. show my lights... shouldn't it?

_No response_

**Comment by pindab0ter** [comment]
@raycastbot rename this issue to "[Hue] Error: self-signed certificate"

**Comment by pindab0ter** [comment]
Unfortunately, this is a known issue. See #8743 for more information.

For anyone experiencing the same issue: This seems to be related to older models which use self-signed certificates. Even though I have written code that should deal with this, there are cases where this still won't be accepted.

Since I don't have a bridge that has this specific issue, I'm looking for someone that has to help me debug the problem.

**Comment by GpL-inc** [comment]
Ok !
Well, that’s a bummer… didn’t think my bridge was that old… has Philips helped in any way?

**Comment by pindab0ter** [comment]
From the [Philips Hue documentation on Using HTTPS](https://developers.meethue.com/develop/application-design-guidance/using-https/#Self-signed%20certificates):

> ## Self-signed certificates
> Older Hue Bridges currently still use self-signed certificates (instead of signed by Signify’s Hue Bridge CA). Handling those requires different logic, but we intend to update all bridges to receive Signify signed certificates so that no differentiation has to be made. To check if your bridge still has a self-signed certificate, you can run the following openssl command to inspect the certificate subject and issuer:
> 
> `openssl s_client -showcerts -connect <ipaddress>:443`
> 
> You should see that the Common Name (CN) of the Subject always matches the bridge id as expected, however in case of self-signed certificates you would see that the Common Name of the Issuer also equals the bridge id.
> 
> Until these bridges are updated, you need to handle the logic of trusting self-signed certificates at first connection. In other words you need to pin (with the bridge-id) the certificate on first connection with the bridge (“trust on first use”) and check upon later contacts with the same bridge. Note though that at some point these bridges will be updated to Signify signed certificates so that transition should be gracefully handled. For development/testing purposes, you can disable certificate validation (e.g. using the curl –insecure command line argument).

I have implemented the mentioned logic.

**Comment by joeynotjoe** [comment]
Hello! I have one of these older hue bridges and would love to be able to contribute debugging if at all possible.

**Comment by pindab0ter** [comment]
That sounds great. You can find me in the Raycast Slack which can be found https://www.raycast.com/.
