### ISSUE TITLE
[Wikipedia] Searching on Wikipedia no longer works 

### ISSUE THREAD

**Issue by Mauricevb** [raycast/extensions#10063]
### Extension

https://www.raycast.com/vimtor/wikipedia

### Description
The Wikipedia extension no longer works.

#### Error:
```
Error: Missing required property "title" for List.Item
```

### Steps To Reproduce

Search something on Wikipedia using the Wikipedia extension 

### Current Behaviour

Error on screen

**Comment by vimtor** [comment]
Hi @Mauricevb!

It appears to be working fine for me. I haven't received any complaints from other users. Can you please double-check it?

https://github.com/raycast/extensions/assets/36263538/235c732e-c8ee-46e3-bbf3-17d66bb44987

**Comment by menahishayan** [comment]
Works fine
<img width="1077" alt="image" src="https://github.com/raycast/extensions/assets/8170437/c98903c0-0328-473e-a9bc-f02a058a0117">

**Comment by Mauricevb** [comment]
I'm sorry! There must have been a network or an API issue when I tried it 4 days ago. I will close the issue.
