### ISSUE TITLE
[OpenAI Translator] The history items to be stored in a queue-like structure

### ISSUE THREAD

**Issue by birdmanmandbir** [raycast/extensions#10073]
### Extension

https://www.raycast.com/douo/openai-translator

### Description

I have a history size of 30, and I expect the history items to be stored in a queue-like structure. When it exceeds the size, I anticipate that the oldest item will be removed from the front of the queue and a new item will be added at the end. However, what actually happens is that the newest item replaces the oldest one at the end of the queue. As a result, I am unable to view the second-to-last record.

### Steps To Reproduce

1. Set the history size to 30 or smaller.
2. Translate more than 30 times.
3. Verify the contents of the history list.

### Current Behaviour

The newest item replaces the oldest one at the end of the queue

### Expected Behaviour

When it exceeds the size, I anticipate that the oldest item will be removed from the front of the queue and a new item will be added at the end.

**Comment by douo** [comment]
Thank you for your feedback. This bug has been fixed and will be released in the next version.

FYI: https://github.com/openai-translator/raycast-openai-translator/issues/18
