### ISSUE TITLE
[OpenAI Translator] Add a quick language switch button?

### ISSUE THREAD

**Issue by birdmanmandbir** [raycast/extensions#10074]
### Extension

https://www.raycast.com/douo/openai-translator

### Description

For the majority of extension users, I believe they typically only work with two languages. However, changing the target language is currently not a simple task as it requires searching through a long list of languages. There is a similar issue mentioned on https://github.com/raycast/extensions/issues/5738. To address this problem, I suggest adding a button that allows users to easily switch between Language A and Language B. This would greatly enhance the user experience. Alternatively, another solution could be implementing a setting that enables customization of the language list, allowing users to minimize unnecessary items.

### Who will benefit from this feature?

Any users work with a limited number of languages.

**Comment by douo** [comment]
Good point.

**Comment by douo** [comment]
WIP
