### ISSUE TITLE
Apple Reminders: Add location-based reminders

### ISSUE THREAD

**Issue by JacobAsker** [raycast/extensions#10080]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

I use the flag option and location option in reminders a lot. So I would love to be able to create those reminders directly from the recast extension!.

### Who will benefit from this feature?

Everybody who uses these features.

**Comment by thomaslombart** [comment]
Unfortunately, it's not possible to do so as it's not supported by Apple's API 😔
Therefore, I will close this as not planned.

**Comment by thomaslombart** [comment]
I've just seen it's possible to add location-based reminders so I'll reopen this issue.

**Comment by JacobAsker** [comment]
Alright, thanks for letting me know! And glad to hear that it’s possible :)Also I would like to thank you for making the extension! Used to use Things 3 but moved back to reminders, and being able to use your quick add extension is a life saver!Best regards from Sweden 😃Med vänlig hälsningar, Jacob Asker11 jan. 2024 kl. 14:25 skrev Thomas Lombart ***@***.***>:﻿
I've just seen it's possible to add location-based reminders so I'll reopen this issue.

**Comment by thomaslombart** [comment]
Thanks a lot for these kind words! 😊

**Comment by pankajpopli** [comment]
Is it possible to choose location preference that is "Arriving" or "Leaving" from the Create Reminder form when using saved locations ? 

Assuming one has already added locations in Manage Locations section.

Really thanks for the extension though, very helpful !!
