### ISSUE TITLE
[Remove Paywall] Add support for importing URL from clipboard

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#10088]
### Extension

https://www.raycast.com/tegola/remove-paywall

### Description

It would be convenient if this extension could import URLs from the clipboard, since it's not obvious how to paste into it.

### Who will benefit from this feature?

Everyone.

**Comment by DannySeidel** [comment]
Hi @chrismessina,

The extension either uses your selection as input or, if nothing is selected, it uses your clipboard. This is also described in the extension's description.

Cheers,
Danny

**Comment by tegola** [comment]
That's the reason why I had an input in the first version of the plugin: to allow the user to paste an URL and, if empty, to tell them (via the placeholder) that the URL would be taken from the selected text or from the clipboard.

The best solution would have been pre-filling the input with the selected text or clipboard, but Raycast didn't support filling fields in the search bar.

**Comment by DannySeidel** [comment]
For me, it was quite logical that the input comes from either the selection or the clipboard. But I totally understand the argument and why you added the placeholder in the first place.

My reasoning for the removal was that it would make no sense to either type the URL directly in the field or paste it from your clipboard when the clipboard content is already used automatically.

To make it clearer, my idea would be to change the name of the command. So instead of just "Remove Paywall," it would be "Remove Paywall from selection or clipboard", for example. What do you think about this?

**Comment by tegola** [comment]
I feel changing the command name wouldn't fix the issue, which I think are two issues:

1. the input URL is hidden: the selected text might be behind the search bar, and the clipboard text isn't visible at all
2. the interface isn't clear, and the user has to remember that the input is taken from a different context.

Maybe we could add a second input in the search bar, basically restoring the old input? It would always allow the user to paste a URL or tell them (via placeholder) that the value would be taken automatically.

Man, I really would like Raycast to support pre-filling the input field. @pernielsentikaer is this something we can fill as a feature request?

**Comment by chrismessina** [comment]
I appreciate the discussion. I kind of expect the Remove Paywall extension to work like a Quicklink, and I expect to paste in the target URL. I agree that it's suboptimal that Raycast doesn't make it obvious that the Clipboard contents (if it contains a URL) is already preloaded and ready to go — because it seems ambiguous to me. 

And to @tegola's point, I have to remember that this extension works differently than Quicklinks, which adds friction to what normally is a pretty mindless action.

The other reason why this is tricky is because it appears that the command's primary action is choosing a service from the dropdown, rather than opening a URL in the selected service:

![2024-01-17 (17 11 33) Pitch@2x](https://github.com/raycast/extensions/assets/22610/29c39e9a-13e4-411b-b387-381160614429)

**Comment by DannySeidel** [comment]
Just created a PR to add back the url argument
