### ISSUE TITLE
[Apple Reminders] Changing/Update due date from Raycast not reflected in Reminders app

### ISSUE THREAD

**Issue by kevinm6** [raycast/extensions#10085]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Changing update of reminders is a very useful feature of Raycast Apple Reminders extension, expecially for the support of **Natural Language** that gets the correct time!
However it seems it doesn’t work if the due date is passed and I want to change/update the **due date** for that reminder in the future.
**Raycast** seems to update and working (even without returning any error) but the due date is not reflected and updated in the Reminders app unlike how that happens for other changes.

### Steps To Reproduce

1. Set a reminder with a date
2. After that date is passed try to change it from Raycast
3. The change happens in Raycast but not in Apple Reminders (and for that, not synced with other devices)

**Comment by thomaslombart** [comment]
Thanks for reporting that issue. Could you send a recording to see more precisely what's happening?

**Comment by kevinm6** [comment]
Sure. Here it is!

https://github.com/raycast/extensions/assets/72861758/91c9b8ef-1f29-4284-8275-683282bc64d3

I was digging into the source code to maybe send a PR with a fix, but I had problem debugging the extension

**Comment by thomaslombart** [comment]
Thanks for the recording. I found a fix and will ship it soon.

**Comment by kevinm6** [comment]
> Thanks for the recording. I found a fix and will ship it soon.

Thanks for the fast response and fix!
I’ve just tested and it’s working as expected.
