### ISSUE TITLE
[Window Management] Next/Previous Desktop target loses focus after move 

### ISSUE THREAD

**Issue by IzakMaraisTAL** [raycast/extensions#10093]
### Extension

https://www.raycast.com/extensions/window-management

### Description

After using _Next Desktop_ on a window (e.g. window A on desktop 1), window A is moved to desktop 2 as expected. However, then it often loses focus . If _Next Desktop_ is invoked again, either nothing is moved (the destop just changes to desktop 3) or a different window (e.g. window B on desktop 2) is now moved to desktop 3. 

When I invoke _Next Desktop_ command in succession (using a hotkey) I want to move the same window (A) across multiple desktops (1 -> 2 -> 3 -> 4).

The same happens with the _Previous Desktop_ command. 

I have been using Raycast for about a year and I feel like this is a regression. 

### Steps To Reproduce

1. On MacOS Sonoma 14.1.2, with Raycast 1.65.0
2. Create a hotkey for Next Desktop. Create multiple desktops (5). Open different windows on each desktop. Now try to move a window from desktop 1 to desktop 5 by repeatedly invoking the Next Desktop hotkey. 

### Current Behaviour

The window cannot be reliably moved across multiple desktops. It will get stuck and sometimes a different window will be moved.

### Expected Behaviour

It should be possible to move the same window across multiple desktops by using Next/Previous Desktop repeatedly.

**Comment by IzakMaraisTAL** [comment]
I'm pretty sure https://www.raycast.com/extensions/window-management is the correct link to the issue, so @raycastbot seems confused.

**Comment by chrisgalvan** [comment]
same issue here, also I don't see the window management code in github

**Comment by MShahzaib** [comment]
Same issue

**Comment by IzakMaraisTAL** [comment]
Thanks for commenting that you can reproduce the problem. Hopefully that will help getting it fixed. 

Unfortunately since the window management is built in to raycast (not an opensource pluging) we cannot log bugs for it on github. The only way to report such bugs are on the raycast slack channel or via e-mail. 

However, I will re-post a link to this in the slack when people here mention that they have the same problem. Previously the devs from Raycast could not re-produce it.
