### ISSUE TITLE
[Reclaim] "Send to Up Next" tag

### ISSUE THREAD

**Issue by maximilianzuern** [raycast/extensions#10094]
### Extension

https://www.raycast.com/reclaim-ai/reclaim-ai

### Description

I noticed that each task displayed in the `Search Tasks` command has a "Send to Up Next" tag with an arrow icon, even the archived tasks. I was wondering if there is a specific reason for this, or if it is just a default setting. 

I tried clicking on the "Send to Up Next" tag, but it doesn't seem to do anything. Is this intended behavior, or is there a bug that needs to be fixed?

![reclaim-ai 2024-01-11 at 09 31 52](https://github.com/raycast/extensions/assets/85677120/876cb393-c611-4477-9860-d2d9120175ad)

**Comment by ajohnson1200** [comment]
Hmm... I could have sworn that worked at some point... the desired action is that clicking on that would send the task to Up Next (a new feature for priorities --> https://help.reclaim.ai/en/articles/4292868-prioritizing-your-tasks) but I agree that it's not doing that now... 😞

**Comment by maximilianzuern** [comment]
As far as I know, tags are not clickable. 
However, it would work via the Actionpanel.

**Comment by ajohnson1200** [comment]
yep, having "Send to Up Next" or "Remove from Up Next" as actions would be great, would definitely like that to happen.

**Comment by maximilianzuern** [comment]
> yep, having "Send to Up Next" or "Remove from Up Next" as actions would be great, would definitely like that to happen.

Is there a query link to trigger "Send to Up Next" such as `/planner/stop/task/${id}` or do I have to use the PUT request e.g `/tasks/${task.id}` (like [here](/tasks/${task.id}))?

**Comment by ajohnson1200** [comment]
PATCH to https://api.app.reclaim.ai/api/tasks/xxx

with payload = 

{"onDeck":true}

where xxx is the ID of the task should work.
