### ISSUE TITLE
[Reclaim] Add "At Risk" tag in Search Tasks command

### ISSUE THREAD

**Issue by maximilianzuern** [raycast/extensions#10095]
### Extension

https://www.raycast.com/reclaim-ai/reclaim-ai

### Description

I wanted to introduce a new tag to the `Search Tasks` command that indicates that a task is marked as "At Risk". 

However, I noticed that the API does not currently support this feature. 
Specifically, I found that every task has the value False for the key "atRisk", even though the task is marked as "At Risk" in the web application. This means that it is not possible to filter tasks based on this tag using the API. 

Could someone please clarify whether this is intended behavior, or if there is a bug that needs to be fixed? 
If it is intended behavior, is there any plan to add support for this feature in the future?

**Comment by ajohnson1200** [comment]
The backend implementation of "at risk" looks at the events scheduled for the task, find the one that's farthest in the future, and then if the end datetime of that event is after the due date for the task, we consider the task to be at risk... so the API doesn't return atRisk by default... you have to ask for the instances, something like

/api/tasks?instances=true

I think should then populate the the atRisk property.

**Comment by maximilianzuern** [comment]
Thank you! 
This API request works. 

What are your thoughts on implementing this in the `Search Tasks`command?

**Comment by ajohnson1200** [comment]
You're proposing an At Risk option here:

<img width="305" alt="Screenshot 2024-01-13 at 7 50 01 PM" src="https://github.com/raycast/extensions/assets/683294/632838f7-1308-4379-a6b8-1add6689c4ce">

If so, yeah, sounds like a great addition.

**Comment by maximilianzuern** [comment]
I would just add a tag (icon: 'ExclamationMark') if a task is at risk.

![raycast reclaim](https://github.com/raycast/extensions/assets/85677120/1116e582-dc3f-4a3d-9936-25cfb4781976)
