### ISSUE TITLE
[Jira Search (Self-Hosted)] API Token support

### ISSUE THREAD

**Issue by Tragio** [raycast/extensions#10117]
### Extension

https://www.raycast.com/emanguy/jira-search-self-hosted

### Description

Thank you for the amazing plugin. 🙂 

Unfortunately, my company doesn't allow the creation of Personal Access Tokens, but API Tokens they allow. I tried to use the API Token but it doesn't work.

I wonder if it would be possible to add API Token support. 🤔 

Thank you once again!

**Comment by emanguy** [comment]
It looks like the only real difference between PATs and API tokens is where the value gets placed... this should be doable, but I may need your help to verify the change works once I tweak the code as I don't have access to a JIRA instance supporting API tokens.

It'll involve side loading a prerelease version of the extension which makes use of the command line, are you comfortable with that?

**Comment by Tragio** [comment]
@emanguy for some reason I didn't receive the notification, just the one from the bot 😅 yes I'll be more than happy to contribute and test it 🙏

**Comment by hiyer-atl** [comment]
[This PR](https://github.com/raycast/extensions/pull/11534) addresses this issue.
