### ISSUE TITLE
[Apple Notes] is not displaying newly created notes. 

### ISSUE THREAD

**Issue by BlackJoker90** [raycast/extensions#10111]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

The Raycast Apple Notes Extension is not displaying newly created notes. Instead, only older notes are shown.

### Steps To Reproduce

1. Open Raycast.
2. Use the Apple Notes Extension.
3. Create a new note in Apple Notes.
4. Attempt to find the new note via the Raycast Extension.

### Current Behaviour

Only old notes are displayed, while new notes do not appear in the list.

### Expected Behaviour

The newly created note should be visible in the Raycast Apple Notes Extension.

**Comment by StevenRCE0** [comment]
Thanks, we've received serval relevant feedbacks. It seems that the Notes database has become less reliable and out of sync, while the Notes app itself maintains an internal persistent state. Anyone got clues?
