### ISSUE TITLE
getApplications(path) does not include Terminal for directory paths

### ISSUE THREAD

**Issue by SKaplanOfficial** [raycast/extensions#10115]
### Description

The `getApplications(path)` function from `@raycast/api` does not include Terminal.app in its output when the path provided is to a directory. Terminal is able to open directories via Raycast's own `open()` function as well as via the command line (e.g. `open -a "Terminal" ~/Desktop`), so I believe this is a bug.

For example, consider the following no-view command:
```typescript
import { getApplications, open } from "@raycast/api";
import path from "path";
import os from "os";

export default async function Command() {
  const dirPath = path.join(os.homedir(), "Downloads");
  const apps = await getApplications(dirPath);
  const terminal = apps.find((app) => app.name === "Terminal")
  // => undefined
  
  // this opens Finder
  open(dirPath, terminal)

  // this opens a Terminal at the Downloads dir
  open(dirPath, "Terminal")
}
```

Since `getApplications()` aims to reflect which apps can open the given path, the behavior seen above is inconsistent.

Also of note: iTerm, if installed, is properly recognized as being able to open directories.

### Steps To Reproduce

1. Use `getApplications(dirPath)` to get applications that can open a directory.
2. Attempt to find Terminal in the returned list of applications (fails).
3. Use `open(dirPath, "Terminal")` to open the directory in the Terminal (succeeds).

### Current Behaviour

Terminal is not included in list of apps that can open directories.

### Expected Behaviour

Terminal should be included in the list of apps that can open directories.

**Comment by mathieudutour** [comment]
That's a good point, will be fixed in the next release
