### ISSUE TITLE
[Apple Reminders] Unable to add reminder

### ISSUE THREAD

**Issue by blaineventurine** [raycast/extensions#10112]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

I am unable to use the "Quick Add Reminder" command. Adding a reminder using "Create Reminder" works just fine, but using Quick Add just pops an error up saying "Unable to add reminder" with no other info.

I am using the latest version of Raycast and the latest version of the extension (as far as I'm aware, both were reinstalled today as part of troubleshooting).

### Steps To Reproduce

1. Install Apple Reminders
2. Grant all required permissions for it to access reminders
3. Run the "Quick Add Reminder" command, with or without any notes

**Comment by thomaslombart** [comment]
Is it the case for all reminders you want to add? What's the exact text you used?

**Comment by blaineventurine** [comment]
To be clear, it's only for "Quick Add" - adding reminders with the pop-up window works just fine. I've tried variations of text on the reminder: `test reminder`, `do something`, etc. No matter what it just says "unable to add reminder" at the bottom of the screen.

**Comment by blaineventurine** [comment]
If there is any way to turn on debugging output, or anything else that would be helpful to you, let me know.

**Comment by thomaslombart** [comment]
Sure, you could fork the extension and run it locally to add some `console.log` statements, especially in the file `extensions/apple-reminders/src/quick-add-reminder.tsx`. Here's our guide about contributing to extensions: [Contribute to an extension](https://developers.raycast.com/basics/contribute-to-an-extension).

**Comment by blaineventurine** [comment]
Thanks! I'll give that a shot and see if I can figure out what's causing it.

**Comment by juanra** [comment]
@thomaslombart I checked the code and the extension imports the Raycast AI capability which is only available for Pro users. On free users it sends an error.

As @blaineventurine said, this only happens with the "Quick Add Reminder" option.

[Take a look](https://imgur.com/a/rukuK3V)

**Comment by thomaslombart** [comment]
@juanra This isn't a bug. Quick Add Reminder is using AI which is part of our Raycast Pro plan.

**Comment by thomaslombart** [comment]
@blaineventurine I shipped [bug fixes](https://github.com/raycast/extensions/pull/11046) that may have fixed your issue. Could you let me know if you still have the problem?

**Comment by dhruvkb** [comment]
"Create Reminder" is also raising an error. It worked fine before.

<img width="862" alt="Screenshot 2024-03-02 at 2 17 41 PM" src="https://github.com/raycast/extensions/assets/16580576/08d2e2c0-180a-4854-b00a-127341a055bd">

Is this related to this issue or it a new/separate?

**Comment by thomaslombart** [comment]
@dhruvkb I've shipped a fix, so the extension should work within a couple of hours. Please note that you can manually get updates by running `Check for Extension Updates`
