### ISSUE TITLE
[Coinbase Pro] ...

### ISSUE THREAD

**Issue by rabi3dadoudd** [raycast/extensions#1012]
# Extension – [Coinbase Pro](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/coinbase-pro/)
Author: @farisaziz12

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.29.1

**Comment by fe9lix** [comment]
Hey @rabi3dadoudd – closing this due to the missing description of the bug (you can open a new one any time...)
