### ISSUE TITLE
[SnapJot] Compatibility with obsidian daily notes

### ISSUE THREAD

**Issue by marcmagn1** [raycast/extensions#10130]
### Extension

https://www.raycast.com/k41531/snap-jot

### Description

I have already wired Snapjot to save memos into a folder in my obsidian vault. It will be great if it could append to my daily notes rather than separate files

### Who will benefit from this feature?

Raycast users who also use Obsidian

**Comment by k41531** [comment]
@marcmagn1 
Thank you for your interest in using the SnapJot extension with Obsidian. I had anticipated it would be used by Obsidian users as well!

To append memos to your daily notes in Obsidian, you can simply align the JotDown extension settings with your Obsidian daily note settings. This way, your memos will be added directly to your daily notes in Obsidian.

This is my settings.
**Obsidian**
![Screenshot 2024-01-13 at 19 26 41](https://github.com/raycast/extensions/assets/84236363/df502e2f-b990-4b2d-b25c-84a19dc3a875)
**SnapJot**
![Screenshot 2024-01-13 at 19 27 14](https://github.com/raycast/extensions/assets/84236363/3fcc1813-0b84-46a1-94d6-f5b930cfcdf9)


If I've misunderstood your issue, please feel free to provide a specific use case. I'd be happy to understand more about how you're using the extension and assist you further.
