### ISSUE TITLE
[Github] Template labels in Create Issue are incorrect

### ISSUE THREAD

**Issue by galligan** [raycast/extensions#1013]
# Extension – Github

Author: @RSO @grzegorzkrukowski 

## Description

When using Raycast to create a GitHub issue using an Issue Template, the templates are labeled with their `title` and not `name`.

## Steps To Reproduce

1. Open Raycast
2. Try to use `Github Create Issue`
3. Go to use an issue template
4. Recognize the template's label

## The current behavior

- The label given to the template is the `title`, which should be the pre-filled title of the issue

## The expected behavior

- The label given should be `name`, which is the name of the issue template

### Raycast version

Version: `1.29.1`

**Comment by galligan** [comment]
Hoping to see if @RSO @grzegorzkrukowski have any thoughts here before it's closed!

**Comment by RSO** [comment]
Just to double-check, is this report concerning the native GitHub extension in Raycast?

**Comment by galligan** [comment]
> Just to double-check, is this report concerning the native GitHub extension in Raycast?

@RSO yes that's correct

**Comment by RSO** [comment]
Hey @galligan so sorry for taking so long, something went wrong with the handoff here! Since this is concerning a native extension and not one that's maintained in this repository it's kinda fallen through the cracks. I'll make sure that someone looks into this though!
