### ISSUE TITLE
Apple Reminders: Does not go back to raycast root after adding a reminder

### ISSUE THREAD

**Issue by lucasnad27** [raycast/extensions#10141]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

While this is a small bug, it's quite annoying for my workflow. I've stopped using the "Create & Close Window" method because of it.

When I use the "Create & Close Window" method to create a reminder, the next time I open up Raycast, it's on the "create reminders" screen again. I inevitably start typing out of habit, then realize the create reminder screen is open and then hit ESC. Which then leads a draft reminder to be created 🤣 -- when you are adding reminders throughout the day, you quickly learn to never use that command again. At least in my experience.

### Steps To Reproduce

Steps to reproduce are quite simple.

1. Go to the "Create Reminder" screen
2. When completing your reminder, use the "Create Reminder and Close Window"

### Current Behaviour

After completing the steps above, when you launch Raycast, it goes immediately to the create reminder screen.

### Expected Behaviour

It should act like other extensions and actions in Raycast and open back to the "Root Search"

**Comment by thomaslombart** [comment]
Thanks for reporting the issue. I'll fix that soon. 😊
