### ISSUE TITLE
[Shortcuts Search] Support locally defined shortcuts

### ISSUE THREAD

**Issue by texastoland** [raycast/extensions#10143]
### Extension

https://www.raycast.com/solomkinmv/shortcuts-search

### Description

I'd like to be able to track my custom shortcuts like [ShortcutKeeper](https://shortcutkeeper.com). Ideally I could enter them in the extension and export them (or save/load from a version-able location). Automatically detecting Raycast hotkeys would be amazing if API allows it.

**Comment by solomkinmv** [comment]
Right now it's impossible to detect shortcuts and I doubt it will ever be.

I'll think about adding custom shortcuts, but right now you can create PR to add to global database: https://github.com/solomkinmv/shortcuts-disco

**Comment by texastoland** [comment]
That doesn't address my use case because my customized hotkeys would conflict with (and confuse) anyone else's.

**Comment by solomkinmv** [comment]
@texastoland what do you think about customization with json files that can be stored locally?

**Comment by texastoland** [comment]
> > export them (or save/load from a version-able location)
>
> customization with json files that can be stored locally?

That'd be cool! Shortcut Keeper already uses the following schema:

```json
{
  "Raycast": [
    {
      "keysLabel": "Shift-Command-/",
      "description": "Search Menu Items",
      "app": "Raycast",
      "tags": "system,global",
      "isPinned": 0,
      "id": 1705191431569
    },
    {
      "keysLabel": "Control-Command-Space",
      "description": "Search Emoji & Symbols",
      "app": "Raycast",
      "tags": "system,global",
      "isPinned": 0,
      "id": 1705191732883
    }
  ]
}
```


> Ideally I could enter them in the extension

Longer term it'd be nice to:

1. Enter the extension similar to a Raycast snippet
2. Record the keys pressed similar to VS Code
3. Show a menu bar item like Raycast timers

I love the concept 🤘🏼
