### ISSUE TITLE
The menu bar/ Timer don't work

### ISSUE THREAD

**Issue by joshlyra** [raycast/extensions#10154]
### Extension

https://www.raycast.com/ThatNerd/timers

### Description

Whenever i click on the both the timer & stopwatch menu bar extension on raycast, nothing pops up on my menu bar. But as you can see from the screenshot, both the battery & weather menu bar commands are working. 
<img width="837" alt="Screenshot 2024-01-15 at 11 36 00 AM" src="https://github.com/raycast/extensions/assets/148985315/4d454ca8-97ae-49f4-bf04-52a223533321">

### Steps To Reproduce

xxx

### Current Behaviour

Whenever i click on the both the timer & stopwatch menu bar extension on raycast, nothing pops up on my menu bar. 

### Expected Behaviour

I should experience functional timer / stopwatch menu bar widgets when I activate the extension.

**Comment by ThatNerdSquared** [comment]
Hi @joshlyra, thanks for the report. Could I double-check a few things with you?

- you've checked that the menubar icon isn't being hidden by any menu-bar-icon-hiding apps like Bartender, Hidden Bar, etc?
- the menubar icon doesn't show when a stopwatch/timer is running?
- you don't have the "Show Menu Bar Item When" preference set to "Never"?

**Comment by joshlyra** [comment]
Oof, I had the preference set to “only when running”…now it’s on always and it works!

Thanks!

**Comment by ThatNerdSquared** [comment]
Great to hear @joshlyra \:) Closing this issue now, feel free to reopen if needed or create another issue if you need to.

@raycastbot close this issue
