### ISSUE TITLE
[Soundboard] ...

### ISSUE THREAD

**Issue by mohamedfouadmd** [raycast/extensions#10166]
### Extension

https://www.raycast.com/pernielsentikaer/soundboard

### Description

hello, thanks for this great extension but, it has two major problem
and i don`t know if you can fix it
1- we are not able to play,pause,skip.....etc and this affect this extension
2- if you want to play another file you can`t because they will play at same time 
and if I press the same file 2 or three times it will play the audio again and again
and I can`t stop this even when quit from raycast
only if I restart the device  

i don`t know if that was a limitation because of the nature of mac os 

however

thank you for your work 🌺

### Steps To Reproduce

.

### Current Behaviour

.

### Expected Behaviour

.

**Comment by pernielsentikaer** [comment]
A soundboard is usually connected with ~3-second files. How long are the files you are using? We could maybe add a preference to determine if it should stop the previous sound. However, I think most people like the ability to play multiple sounds at the same time.

Just like a physical soundboard with buttons, you can also play multiple sounds at once if you want to.

**Comment by andreaselia** [comment]
Going to close this issue due to inactivity. I agree with @pernielsentikaer in that how it works at the moment is pretty great for a soundboard. Audio files should also be a few seconds for such an extension as it isn't a music player or anything like that.

@raycastbot close this issu

**Comment by andreaselia** [comment]
@raycastbot close this issue
