### ISSUE TITLE
[Semantic Scholar] Generate Bibtex for a reference

### ISSUE THREAD

**Issue by daniel-stoneuk** [raycast/extensions#1016]
# Extension – [Semantic Scholar](https://github.com/raycast/extensions/tree/a15fd2cbfec0021e1647522257d6b7002db7ab13/extensions/semantic-scholar/)
Author: @blainerothrock

Thanks for this awesome extension @blainerothrock. Would you be open to adding an action for generating and copying a Bibtex reference to the clipboard? 

If yes, I'd be happy to make a PR!

**Who will benefit with this feature?**
Citing a paper using Raycast.

**Any Other info.**
This could be implemented with the request:

```
curl --location --request GET 'https://doi.org/10.1007/b97644' \
--header 'Accept: application/x-bibtex'
```
```bibtex
@book{2004,
	doi = {10.1007/b97644},
	url = {https://doi.org/10.1007%2Fb97644},
	year = 2004,
	publisher = {Springer-Verlag},
	title = {Guide to Elliptic Curve Cryptography}
}
```

**Comment by blainerothrock** [comment]
Yes, that is a great addition! I honestly could use this today ha. Looking forward to the PR!

**Comment by daniel-stoneuk** [comment]
@blainerothrock Do you mind if I use the Raycast template to make a Raycast themed icon as well?

**Comment by blainerothrock** [comment]
Not at all! I have no ties to the current logo.

**Comment by daniel-stoneuk** [comment]
I've created a PR for this at #1022.

Unfortunately I realised that Semantic Scholar is missing DOIs for a number of papers that I have tried to cite, so I've also hidden the option if it's unavailable.

Let me know what you think!
