### ISSUE TITLE
[1Password] support multiple accounts

### ISSUE THREAD

**Issue by seanaye** [raycast/extensions#10163]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Currently the 1Password extension only supports a single account as far as I can tell. There is no option in the extension configuration to sign into a second account and I only see item from the account I initially authenticate with.

 It would be great if the extension supports authenticating with multiple accounts just like the 1Password desktop application.

### Who will benefit from this feature?

Any 1Password user with multiple accounts will benefit from this feature. E.g. me I have a personal 1Password account and a Work/Enterprise 1Password account.

**Comment by mortenscheel** [comment]
Yes please.
I don't think the `op` cli tool supports logging in to multiple accounts, but at least add a way to switch between accounts in the extension.

**Comment by dalposenrico** [comment]
Duplicate of #4744

**Comment by Luk4h** [comment]
> Duplicate of #4744

@raycastbot close this issue
