### ISSUE TITLE
Dynamically rendered Action(s) don't render in ActionPanel

### ISSUE THREAD

**Issue by knownasilya** [raycast/extensions#1017]
Raycast version: 1.29.1

## Description

When rendering an `<Action />` component dynamically, e.g. `{isShown && <Action title="abc" />}` does not show the Action, even if `isShown` is `true`.

## Steps To Reproduce

1. Conditionally render `<Action />` in an `<ActionPanel />` on a `List.Item`.
2. Change the condition so that another action is rendered instead

## The current behavior

Originally rendered action is always shown.

## The expected behavior

The conditional should rerender the action that is expected to be there based on the logic.

## Example Code

```js
import { List, ActionPanel, Action } from '@raycast/api';
import { useEffect, useState } from 'react';

export default function Command() {
  const [isLoading, setIsLoading] = useState(true);
  const items = [{ name: 'Test' }];

  useEffect(() => {
    setIsLoading(true);

    setTimeout(() => setIsLoading(false), 100);
  }, []);

  return (
    <List navigationTitle="My Items">
      {items.map((item, index) => (
        <List.Item
          key={index}
          title={item.name}
          actions={
            <ActionPanel>
              {isLoading ? (
                <Action title="UnLoad" onAction={() => setIsLoading(false)} />
              ) : (
                <Action title="Load" onAction={() => setIsLoading(true)} />
              )}
            </ActionPanel>
          }
        />
      ))}
    </List>
  );
}
```

**Comment by sxn** [comment]
hi @knownasilya, thanks for the report! This should be fixed in next release. 😉

**Comment by knownasilya** [comment]
Nice!
