### ISSUE TITLE
[Music] "Currently Playing Track" - extended information display

### ISSUE THREAD

**Issue by justinburrow** [raycast/extensions#10170]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

The "Currently playing track" command reveals the track name in a notification.

It would be much more useful if it displayed the [ track name ] by [ artist name ], and clicking on the notification performed the same action as "Reveal track".

### Who will benefit from this feature?

All users who use the Music extension.

**Comment by rawnly** [comment]
I'll see what i can do about this
