### ISSUE TITLE
[Vercel] No commit message

### ISSUE THREAD

**Issue by rseiffert** [raycast/extensions#10176]
### Extension

https://www.raycast.com/vercel/vercast

### Description

Search deployments shows the correct dates and the correct projects, but **no commit message(s)**
<img width="736" alt="2024-01-16_11-56-03" src="https://github.com/raycast/extensions/assets/1698356/a09462ee-f396-4482-964c-01631b43f095">

### Steps To Reproduce

Raycast "Search deployments"; Have a look at the returned list of deployments.

RayCast 1.65.0
macOS 14.2.1
All Vercel projects are on Bitbucket

**Comment by eserdinyo** [comment]
Hey @rseiffert , Are you still experiencing this issue?
I just installed this extension and everything seems to be working fine for me.

**Comment by rseiffert** [comment]
Hey @eserdinyo Unfortunately yes. The behaviour changed slightly. Now I am at least able to see the underlying projects
<img width="750" alt="2024-02-13_10-56-22" src="https://github.com/raycast/extensions/assets/1698356/985d14a8-7f89-4778-9200-0ec9cd0a87d4">

What I have done before my last screenshot:

I removed the Extension from raycast, created a brand new Token on Vercel, and installed the extension again.

My guess: Maybe this is bitbucket specific? Where do your Repos reside?

Raycast 1.67.1
All Vercel projects are still on Bitbucket and yes every commit has a commit message ;-)

**Comment by rseiffert** [comment]
Hey @eserdinyo Unfortunately yes. The behaviour changed slightly. Now I am at least able to see the underlying projects
<img width="750" alt="2024-02-13_10-56-22" src="https://github.com/raycast/extensions/assets/1698356/985d14a8-7f89-4778-9200-0ec9cd0a87d4">

What I have done before the screenshot above:

I removed the Extension from raycast, created a brand new Token on Vercel, and installed the extension again.

My guess: Maybe this is bitbucket specific? Where do your Repos reside?

Raycast 1.67.1
All Vercel projects are still on Bitbucket and yes every commit has a commit message ;-)
<img width="735" alt="2024-02-13_11-08-02" src="https://github.com/raycast/extensions/assets/1698356/f35a5097-0ad6-422b-8916-ab2b7db3ba18">

**Comment by eserdinyo** [comment]
My projects are in Github. Maybe you're right. It may be related Bitbucket.

**Comment by eserdinyo** [comment]
Checked the source code. Seems there is only Github for now :) 

```
const getCommitMessage = (deployment: Deployment) => {
  // TODO: determine others
  if (deployment.meta.githubCommitMessage) {
    return deployment.meta.githubCommitMessage;
  }
  return "No commit message";
};
```
