### ISSUE TITLE
Google Chrome Profiles not working correctly [Google Chrome Profiles] ...

### ISSUE THREAD

**Issue by dezerving** [raycast/extensions#1018]
# Extension – [Google Chrome Profiles](https://github.com/raycast/extensions/tree/022b60caf8144b5bf5007db8d0ee6f3b58e8da47/extensions/google-chrome-profiles/)
Author: @frouo

## Description

When using this extension and selecting my School profile and opening either a New Tab or Bookmark Chrome tries to open up a new instance of itself and closes the existing instance (losing all tabs), rather than continuing to use the Chrome instance I currently already have open.

Note: this seems like a Chrome issue and not an extension issue, but at the moment the extension is not working the way I thought it should.

## Steps To Reproduce

1. Open Raycast
2. Search 'show profiles'
3. Hit enter on any profile
4. Hit enter on a bookmark or new tab

## The current behavior

A new instance of Chrome attempts to open, hangs for a long time (minutes), and then eventually opens a new instance and closes my existing instance (I lose all existing tabs and everything).

## The expected behavior

A new windows of Chrome should open with the correct profile, in the existing instance of chrome (if already open).

### Raycast version
Version: 1.29.1

**Comment by dezerving** [comment]
I think the code needs to be updated, Bill on Slack pointed out that this works:
```open -na 'Google Chrome' --args --profile-directory='Profile 1' https://drive.google.com/```

**Comment by frouo** [comment]
Hello @dezerving does this command line works for you from your terminal?

You can find the name of the profile directory by open your profile (use google chrome if Raycast extension does not work) then open the link `chrome://version`.

The command line used in Google Chrome Profile Raycast extension is `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --profile-directory='Profile 1' https://drive.google.com/`. Could you try it too from your terminal?

Thanks

![image](https://user-images.githubusercontent.com/2499356/158331544-a852251c-90ac-4204-8938-0fd87e72c7e4.png)

**Comment by JSRossiter** [comment]
I believe Chrome 98 was the cause of this issue, and it's since been reverted in Chrome 99. It was also causing other issues with inactive profiles. The extension is working for me again now.

**Comment by frouo** [comment]
@dezerving just checking if there is anything new on your side regarding this issue? Which version of Chrome are you using?
