### ISSUE TITLE
[Logitech Litra] Command failed

### ISSUE THREAD

**Issue by Nenuial** [raycast/extensions#10197]
### Extension

https://www.raycast.com/timrogers/logitech-litra

#### Error:
```
Error: Command failed: /opt/homebrew/bin/litra-devices --version
env: node: No such file or directory


env: node: No such file or directory
ChildProcess.exithandler:node:child_process:422:12
ChildProcess.emit:node:events:514:28
```

### Steps To Reproduce

The litra extension stopped working for me.

The strange thing is that if I run `/opt/homebrew/bin/litra-devices --version` in a Terminal it works perfectly and I get:
`4.5.0`

I can still work my Litra with the command line using `litra-on` and `litra-off`.

Any hints as to what might go wrong would be hugely appreciated.

**Comment by Nenuial** [comment]
I didn't have the new `litra` command line! Sorry about that, I didn't realise that there had been a change.
Works like a charm again. Thanks for pointing me in the right direction!!

**Comment by timrogers** [comment]
@raycastbot close this issue
