### ISSUE TITLE
[OSINT Web Check] parsing security.txt

### ISSUE THREAD

**Issue by milo526** [raycast/extensions#10194]
### Extension

https://www.raycast.com/gksander/osint-web-check

### Description

https://securitytxt.org

The security.txt document (commonly found at https://{domain}/.well-known/security.txt) provides information on who to contact regarding security problems on a website.
It would be nice to view this information in the plugin.

Examples of such documents:

https://www.youtube.com/.well-known/security.txt
https://www.facebook.com/.well-known/security.txt
https://www.apple.com/.well-known/security.txt

### Who will benefit from this feature?

People interested in finding out more information about a website.

The information already provided in this plugin is very helpful to security researchers, adding this piece of information makes it a little more useful.

**Comment by gksander** [comment]
Yes! This should absolutely be added, I'll work on getting that added in once I get some bandwidth (should be a pretty light task)

**Comment by milo526** [comment]
Thanks for the quick implementation 😄 seems to work like a charm.
