### ISSUE TITLE
[GitHub] Ability to use a Fine-Grained Access Token

### ISSUE THREAD

**Issue by tanerilyazov** [raycast/extensions#10193]
### Extension

https://www.raycast.com/raycast/github

### Description

Currently the extension requires very broad authorization. There are companies, which are very strict about access and even more annoying(my case), outsorcing companies who have a single client with strict rules (insurance/bank sector). 
I think it will enable a bunch of other users to use this feature if we can use the new Fine-Grained access tokens to select projects which are a part of a organization, so we can request proper relevant access without touching the strict projects.
I'm well aware this means that some of the commands within the extension will have to be disabled based on the privileges (not having read:org). But a lot of devs probably don't need all of the commands, but really need only some of them. 

### Who will benefit from this feature?

I couldn't decouply it from the description. 😢

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then soon be able to exchange them in our swag store.

**Comment by tanerilyazov** [comment]
Hello, I dug a bit more into it and I think we can close this for now. After some testing seems like the Fine-grained tokens purpose is most likely to be used from an external system during CI/CD pipeline instead of the perspective of authenticating a user. 
For example there's no way to cover the user's notifications permission with it and it still in beta.
I think we can close this request and I'll look into it again in the future if their focus shifts a bit.

Thank you for the response, I'll gladly contribute with something else in the near future!

**Comment by thomaslombart** [comment]
All right, thanks for looking into it!
