### ISSUE TITLE
Jetbrains API exception

### ISSUE THREAD

**Issue by TomDeSmet** [raycast/extensions#1021]
# Extension – [Jetbrains](https://github.com/raycast/extensions/tree/e3bccd15a458040bff2f83dac63ce93c288fd3e0/extensions/jetbrains/)

Author: @gdsmith 

## Description
Installed the extension, set the scripts folder in Toolbox as well as in extension settings, but getting the following error and no projects: `ResponseError: Request cancelled API exception`

### Raycast version

Version: 1.29.1

**Comment by gdsmith** [comment]
@TomDeSmet sorry, I missed this, did you manage to get it sorted?

**Comment by TomDeSmet** [comment]
It solved itself but it pops up every once in a while. No idea when or why though...
