### ISSUE TITLE
[YouTrack] Add ability to create tasks 

### ISSUE THREAD

**Issue by snpefk** [raycast/extensions#10220]
### Extension

https://www.raycast.com/tiulpin/youtrack

### Description

Hi! Thanks for your effort.

It would be a cool addition to be able to create a task from Raycast.

### Who will benefit from this feature?

me :)

**Comment by snpefk** [comment]
@skoch13 hey king, you dropped this 👑

**Comment by skoch13** [comment]
@snpefk thanks. Have you tried it already? Any feedback?

**Comment by snpefk** [comment]
Yeah, it would be nice if I can change task status to "In progress" from creation page.
