### ISSUE TITLE
[WHOOP] ... Error loading Biometrics in Raycast

### ISSUE THREAD

**Issue by connerdrew** [raycast/extensions#10221]
### Extension

https://www.raycast.com/josha1len/whoop

#### Error:
```
RangeError: Invalid time value

yne:biometrics.tsx:19:2

---
16: import { WhoopColor } from "./helpers/constants"

### Steps To Reproduce

Open raycast
Launch Biometrics

### Current Behaviour

Error when loading biometrics

### Expected Behaviour

See biometrics

**Comment by Josha1len** [comment]
Hey @connerdrew, thanks for reporting. A potential fix has been approved [here](https://github.com/raycast/extensions/pull/10223). Please could you update the WHOOP extension and retry viewing your biometrics?

**Comment by Josha1len** [comment]
@raycastbot close this issue
