### ISSUE TITLE
My Schedule Open Zoom Meeting

### ISSUE THREAD

**Issue by RyonMB** [raycast/extensions#1023]
Raycast version: v1.29.1

## Description

Joining zoom meetings from My Schedule not working

## Steps To Reproduce

1. Create an event (through Calendly) with a Zoom meeting as location
2. Open the event in "My Schedule" 
3. Press cmd + enter or "Join Zoom Event" to join the event

![CleanShot 2022-03-03 at 21 29 26@2x](https://user-images.githubusercontent.com/43067960/156647678-c542ca47-7136-4995-96ee-2160b54723c6.jpg)

## The current behavior

Does not open the Zoom Meeting

## The expected behavior

Launches the zoom meeting

Note:

Google meetings do work

**Comment by daniel-karas** [comment]
I seem to be having the same issue - only for Chrome though. When I set the "browser to open Google related links with" to Firefox or Safari it works fine.

**Comment by fe9lix** [comment]
Hey @RyonMB, would you mind reporting this through Raycast's feedback command? (It's not API-related...)
