### ISSUE TITLE
[ChatGPT] Getting 401 error since a few days back

### ISSUE THREAD

**Issue by rochakagrawal** [raycast/extensions#10231]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Any messages being sent using the AI conversations is coming back with a 401 error "Error 401 status code (no body)"

I have double checked my API key and it is definitely working.  Please advise 

thanks

### Steps To Reproduce

1. Put in a query 
2. Receive an error in the Toast

**Comment by bxb100** [comment]
Can you share your configuration? (Remember to obscure sensitive data)

**Comment by rochakagrawal** [comment]
Hi - there has been no change to my configuration. It just stopped working
on its own. Here are some screenshots. My API key is definitely working as
I tested it thorough. python script

I have attached screenshots below of my config. I am using an Azure
endpoint

[image: image.png]

[image: image.png]

[image: image.png]

**Comment by bxb100** [comment]
The header was set wrong, but I don't have azure API to test.
so you can fork the extension

<img width="774" alt="image" src="https://github.com/raycast/extensions/assets/20685961/acb9d0b4-580f-4d4b-a231-8fb08e85d61a">

 modify the source code at `src/hooks/useChat.tsx` line 83

```diff
-  headers: { apiKey: getHeaders().apiKey },
+  headers: { 'api-key': getHeaders().apiKey },
```

run `npm i` `npm run dev` in terminal and see if it works

**Comment by rochakagrawal** [comment]
this works, thanks so much !

really appreciate your quick work.

May i ask if you have any plans of allowing us to send images / files
to chatgpt to query on that please?

many thanks

**Comment by bxb100** [comment]
It will be fixed after the PR merge.

> May i ask if you have any plans of allowing us to send images / files
to chatgpt to query on that please?

sry, no plan for me

**Comment by rochakagrawal** [comment]
Hi Lemon - i had to reinstall raycast, and when i am reinstalling your
extension (either from store) or from GitHub, i am only getting the below
command. Any idea why I can't get the AI chat option?

Many thanks


[image: CleanShot 2024-01-21 at ***@***.***

**Comment by bxb100** [comment]
I can't see your image, maybe the email replay erased the image

**Comment by rochakagrawal** [comment]
Hi - attached again

thanks

**Comment by bxb100** [comment]
@rochakagrawal It's not working, maybe you should directly upload the image to this issue page

**Comment by rochakagrawal** [comment]
Hi Lemon - i have put in the link to the image
https://i.imgur.com/4M7EuBi.png

thanks

**Comment by bxb100** [comment]
The commands remain unchanged.

> Any idea why I can't get the AI chat option?

Do you mean the `Models` setting?

<img width="774" alt="image" src="https://github.com/raycast/extensions/assets/20685961/eba0a36d-5f96-48d3-8090-2c8fd42a08dd">

**Comment by rochakagrawal** [comment]
No - what i mean is that I can't see the AI chat command any more. I can
only see the commands listed on the image https://i.imgur.com/4M7EuBi.png.
There used to be an option to enter into a conversation mode with AI

**Comment by bxb100** [comment]
> No - what i mean is that I can't see the AI chat command any more. I can only see the commands listed on the image ![i.imgur.com/4M7EuBi.png](https://i.imgur.com/4M7EuBi.png). There used to be an option to enter into a conversation mode with AI

sry, I don't know, can't help you
