### ISSUE TITLE
[Tyme 3 Time Tracker] Something went wrong

### ISSUE THREAD

**Issue by klickreflex** [raycast/extensions#10249]
### Extension

https://www.raycast.com/melkstam/tyme-3-time-tracker

### Description

The extension used to work for a couple of days after installing, but then stopped working. Reloading the extension, restarting Raycast and/or rebooting the MacBook didn't fix it. 

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'name')

t0:start-task-tracking.tsx:13:70

---
10: 
11: function StartTrackerForTask() {
12:   // Get all tasks
13:   const { data: tasks, isLoading: tasksIsLoading } = useCachedPromise(getTasks, [], {
14:     keepPreviousData: true,
15:   })

### Steps To Reproduce

1. MacOS 14.2.1 on M1 Max
2. Run the _Start Task_ command
3. Get the error

### Current Behaviour

 1. Run the _Start Task_ command
 2. Getting the error _Something went wrong_

### Expected Behaviour

 1. Run the _Start Task_ command
 2. Get a list of tasks to choose from

**Comment by melkstam** [comment]
Thanks for the report @klickreflex! 

I will look into it when I have time, but that resource is sadly a bit limited at the moment. Feel free to help investigate or even put up a PR if you want.

**Comment by klickreflex** [comment]
@melkstam Thanks, no pressure. I wouldn't know where to start working on Raycast extensions (and neither have time to get started with it), but fwiw I can test and share my observations: After reinstalling, the Tyme extension it started working again normally.
