### ISSUE TITLE
[Apple Reminders] Any way to get back the old reminder

### ISSUE THREAD

**Issue by rochakagrawal** [raycast/extensions#10245]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Is there any way to get back the old reminder extension repo? The new reminder extension is extremely buggy. I can't get it to show in the list dropdown all my macos reminders list. It only puts the reminder in the default list that I have.

I have tried reinstalling and adding this extension several times. Raycast, of course, has the permissions to access reminders in security and privacy; else it wouldn't have been able to add in the default list too.

Please see the screenshot.

### Steps To Reproduce

1. install extension on latest raycast
2. dropdown doesn't show the full list of reminders
![CleanShot 2024-01-20 at 13 01 08@2x](https://github.com/raycast/extensions/assets/3668160/98cf7d93-da1d-4958-ae73-fe213e7eed88)

**Comment by thomaslombart** [comment]
The `Could not get any data` error you had on the other issue (#10257) is probably the reason why you can't see the default list. I'll close only this issue to keep the backlog clean.
