### ISSUE TITLE
[Apple Reminders] Unabale to set priority

### ISSUE THREAD

**Issue by abcvav** [raycast/extensions#10259]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

When you open "My Reminders" and select a task, press cmd+k, choose "Set Priority," and then set a priority arbitrarily, a prompt will appear in the bottom left corner indicating "Unable to set priority."

### Steps To Reproduce

1. macOS 14.2.1,  Raycast 1.65.1
2. Open 'My Reminders', select a task, press cmd+k, choose "Set Priority", set any priority, a prompt will appear in the bottom left corner indicating "Unable to set priority."

### Current Behaviour

Unable to set priority

### Expected Behaviour

The priority should be set

**Comment by thomaslombart** [comment]
I can't reproduce that. Could you send a recording to see what happens in detail?

**Comment by abcvav** [comment]
Sure, this is it

https://github.com/raycast/extensions/assets/47599849/e74b83e4-1bb6-44b9-86c9-1a917c160d6d

**Comment by abcvav** [comment]
Alternatively, could you tell me where I can view the debug logs? I can upload them.

**Comment by thomaslombart** [comment]
Thanks for the recording. I'll take a look at that during the week.

**Comment by abcvav** [comment]
OK, thank you!
