### ISSUE TITLE
[Kagi FastGPT] All searches result in "Something went wrong"

### ISSUE THREAD

**Issue by andystevensname** [raycast/extensions#10266]
### Extension

https://www.raycast.com/http.james/kagi-fastgpt

### Description

I cannot successfully query FastGPT with this extension, any query results in a "something went wrong." Additionally, I use [Lulu](https://github.com/objective-see/LuLu). When that is turned on, I get a 502 Bad Gateway and I do not get as far as seeing the "something went wrong" screen. If that is unrelated, I'll figure that on my own, but thought I'd share just in case it's related.

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'output')

ask.tsx:30:39

---
27:       } finally {
28:         setLoading(false)

### Steps To Reproduce

1. Install extension
2. Configure extension with Kagi API key
3. Perform query with Kagi FastGPT, does not seem to change based on what the query is.

### Current Behaviour

Right now, the extension installs correctly and accepts a query, but it is not able to execute that query. I do have an active account and can verify that the API key works with the other Kagi Search extension that's available on the Raycast store.

### Expected Behaviour

The extension should query Kagi FastGPT.

**Comment by httpjamesm** [comment]
Did you add Api credits to your account?

**Comment by andystevensname** [comment]
@httpjamesm Aha I did not! My apologies! I just added credits and it works like a charm. Thank you, I'll close this now.
