### ISSUE TITLE
[PR Pipeline] New extension PR build stuck on 'eslint: not found' error

### ISSUE THREAD

**Issue by xeric** [raycast/extensions#1026]
PR: https://github.com/raycast/extensions/pull/1004
Could anyone provide some help why I always get 'eslint not found' error?
I tried to check eslint in local, compared the eslint files content with other repo, all of them are fine, but still get in build:

🕐 wait - validate extension icons
✅ ready - validate extension icons
🕐 wait - run ESLint
💥 error - run ESLint
sh: 1: eslint: not found
Error: sh: 1: eslint: not found
Error: Process completed with exit code 1.

I use 'npm run lint' in local, which has no issue.
from the few error info, looks like the environment run build has no global eslint? But I feel it should not happen.

**Comment by sxn** [comment]
hi @xeric - It seems like the `package-lock.json` file was missing the entire top-level `packages` key, which…it shouldn't 😅 regenerating the `package-lock.json` file _seems_ to have fixed the issue. What version of `node` and `npm` are you using?

**Comment by xeric** [comment]
@sxn thanks for your help, you figured out the root cause, due to some reason, my local env have to use a lower version node + npm (10.24.1 + 6.14.12), which generate totally legacy version of package-lock file, and after switched to node 16.2.0 + 7.13.0, the lock file generated has "packages" root property now, which can pass the build of PR pipe.
