### ISSUE TITLE
[PDFSearch] Cannot delete collection

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#10269]
### Extension

https://www.raycast.com/kevin-pek/pdfsearch

### Description

I'm getting the following error when trying to delete a collection:

Error: ENOENT: no such file or directory, unlink '/Users/****/Library/Application Support/com.raycast.macos/extensions/5bd5b1c6-6030-44b7-9446-55b52a1cac36/PJe.sqlite'

Object.unlink:sync:93:18
unlinkSync:node:fs:1853:17
Object.onAction:collections.js:43:4412
onAction:index.js:13:16332

### Steps To Reproduce

`⌘K` + `Delete Collection`

**Comment by kevin-pek** [comment]
Hi @xilopaint, I have made a new version of the extension that fixes this bug!

**Comment by xilopaint** [comment]
Thanks!
