### ISSUE TITLE
[Google Gemini] ability to rewrite selected text

### ISSUE THREAD

**Issue by chitwan-malhotra** [raycast/extensions#10260]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-gemini

### Description

As a user, I should have the ability to ask Google Gemini to rewrite my selected text. We do have Make Short, Make Long, Make Friendly, etc. But If i simply want to rewrite/reword the text keeping the same length, the option is not available.

For Example, asking the same to ChatGPT produces the following results.

![image](https://github.com/raycast/extensions/assets/18690075/3c6a809d-169f-43b1-9d34-e4addb767a22)

,

### Who will benefit from this feature?

If a selected text has to be written in differently.

**Comment by xilopaint** [comment]
@EvanZhouDev I was about to request this feature. This should be implemented by introducing an `Improve Writing` command. In Raycast AI we already have such a command:

<img width="886" alt="Screenshot 2024-01-22 at 11 51 45" src="https://github.com/raycast/extensions/assets/11052366/07713302-0fde-4a06-9617-2a3d51f85127">

This is the prompt:

```
Act as a spelling corrector and improver. Reply to each message with rewritten text using following instructions to rewrite it:
    - Fix spelling, grammar and punctuation
    - Improve clarity and conciseness
    - Break up overly long sentences
    - Reduce repetition
    - Prefer active voice
    - Prefer simple words
    - Keep the meaning same
    - Keep the tone of voice same
    Use english language
    

Text: {selection}

Improved Text:
```
