### ISSUE TITLE
[ScreenOCR] Add ability to recognize from clipboard?

### ISSUE THREAD

**Issue by zbuster05** [raycast/extensions#10270]
### Extension

https://www.raycast.com/huzef44/screenocr

### Description

Simply add a binding to recognize text from an image in the clipboard.

This would be particularly useful as:
1.  It would allow users to give access to the clipboard but not screen capture if they so desire.
2. It would also enable the use case where one wishes to use a pre-existing image and doesn't care to screenshot it.

**Comment by neo773** [comment]
Hi,

Yes, this would be a nice to have but unfortunately I don't have much time to look into this for now.
However I'd be happy to review a PR for this.
