### ISSUE TITLE
[PDFSearch] Add outline search

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#10279]
### Extension

https://www.raycast.com/kevin-pek/pdfsearch

### Description

Would it be possible to create a new command to search for outlines? I have a lot of PDF files with outlines, and it would be great to navigate them via Raycast. The list view (left side) would be populated with all the outlines of the PDF file and we could filter them and see their content in the detail view (right side).

### Who will benefit from this feature?

All extension users.

**Comment by kevin-pek** [comment]
Hey @xilopaint, I think that's a great idea for a feature! I wanted to ask more about how you would like this to work. Do you want it this feature to also work for collections of documents or just for a single document? Also, after selecting an outline from the list view, do you want to be able to view every page within the selected outline, or is searching the content within the outline of the document suffice (similar to what we have now)?

**Comment by xilopaint** [comment]
> Do you want it this feature to also work for collections of documents or just for a single document?

I think making it work with collections would only add unnecessary complexity. Making it work with single documents is enough for me.

> Also, after selecting an outline from the list view, do you want to be able to view every page within the selected outline

After selecting an outline, I would like to jump to the first page of that outline and be able to scroll through the document from there (up or down). Also, I would like to be able to open the document in my PDF reader at that page, as we can already do with the other command.

**Comment by xilopaint** [comment]
Any news here, @kevinpek? I'm looking forward to seeing this implemented.

**Comment by kevin-pek** [comment]
Hey @xilopaint, am currently still working on implementing this. It's taking longer than expected as I have been busy with the my current school semester, but I'll let you know once it is done!
