### ISSUE TITLE
[Notion] ... Menu bar support for Notion Updates

### ISSUE THREAD

**Issue by svranyes** [raycast/extensions#10280]
### Extension

https://www.raycast.com/notion/notion

### Description

In Notion there are "updates" that allow you to see Notion reminders and other changes. It would be super handy to see this list in the Notion Raycast extension and also see them as a menu bar drop down. There are other extensions that do this for Apple Reminders and for Todoist and its really helpful.

### Who will benefit from this feature?

Anyone using reminders in Notion - which I would think is a large majority of Notion users

**Comment by thomaslombart** [comment]
Unfortunately, we are limited here as we would need an API from Notion for that, which is not the case. I will mark this feature request as not planned then. Feel free to reopen it if they ever integrate that in the future.

**Comment by svranyes** [comment]
Thanks. I'll make the request to the Notion team to see if they'd be willing to add it.
