### ISSUE TITLE
[port-manager] Add a new button / option to open in browser

### ISSUE THREAD

**Issue by tahsinature** [raycast/extensions#10283]
### Extension

https://www.raycast.com/lucaschultz/port-manager

### Description

It's a handy extension to manage ports. It would be nicer if we also opened a port to the browser.
Sometimes we forget which port our app is running, especially when we have a few projects running simultaneously.
![SCR-20240122-lgii](https://github.com/raycast/extensions/assets/41298152/b99b2a56-84ff-42c1-931b-72b4441428b2)

### Who will benefit from this feature?

Developers. Especially front-end developers.

**Comment by Sheraff** [comment]
@tahsinature there was an update made to this extension a few days ago, but for some reason it didn't get released... https://github.com/raycast/extensions/pull/9966

This update would help make it easier to see which port matches what. (But I do like your idea too, we could think of implementing it once the PR i linked above actually gets released).

**Comment by lucaschultz** [comment]
> @tahsinature there was an update made to this extension a few days ago, but for some reason it didn't get released... https://github.com/raycast/extensions/pull/9966
> This update would help make it easier to see which port matches what. (But I do like your idea too, we could think of implementing it once the PR i linked above actually gets released).

Agreed! @pernielsentikaer is there anything that can be done to get #9966 released in the store? 🤔

**Comment by pernielsentikaer** [comment]
It should be in the store 🙂
