### ISSUE TITLE
ChatGPT Quick actions are not working.

### ISSUE THREAD

**Issue by hamzach330** [raycast/extensions#10295]
### Extension

https://www.raycast.com/alanzchen/chatgpt-quick-actions

### Description

<img width="742" alt="Screenshot 2024-01-23 at 12 29 16" src="https://github.com/raycast/extensions/assets/32511517/21fc6405-d71d-412b-a9fd-c69b80faf722">

I am facing this issue with my raycast command, I am using a paid version of ChatGPT and added the API Key secert as well. 

but whenever i ask a questio to the extension it gives me this error, i dont understand why ??

### Steps To Reproduce

<img width="742" alt="Screenshot 2024-01-23 at 12 29 16" src="https://github.com/raycast/extensions/assets/32511517/21fc6405-d71d-412b-a9fd-c69b80faf722">

I am facing this issue with my raycast command, I am using a paid version of ChatGPT and added the API Key secert as well. 

but whenever i ask a questio to the extension it gives me this error, i dont understand why ??

**Comment by alanzchen** [comment]
Looks like this is the built-in AI from Raycast, not my extension?

**Comment by alessiomaffeis** [comment]
That looks like the ChatGPT extension: https://github.com/raycast/extensions/blob/c596c09ce3ffa93548bd6f6852882e129f019b62/extensions/chatgpt/README.md

And from the error message in your screenshot, it looks you reached your API limits. You probably need to connect a credit card to your account or transfer some funds to it.

**Comment by hamzach330** [comment]
Thanks for you reply Alessio but the thing is that, my API limit is not over, I am using it other application as well, it’s just the Recast which is showing me this error.
