### ISSUE TITLE
MS Edge - search tab issue

### ISSUE THREAD

**Issue by hsetty** [raycast/extensions#1029]
I am hoping you can help with this weird configuration setup as I am not able to get it working correctly. I want to be able to search open tabs in MS Edge and go to that tab via raycast. My setup is like this

• I have MS Edge Beta on the Mac installed with multiple profiles (Work, Personal, Business)
• I typically have 1 window for each profile open and typically will have two profile windows open at any given point in time.
• Within each window, I have multiple tabs organized by tab groups.

I also have Windows 11 installed by Parallels which I use sparingly for my day job for certain windows only applications. Windows 11 also have MS Edge as the default browser.

The problem I am trying to solve is to go to one of the open tabs on my Mac from raycast. I installed the Edge extension, but when I try to search for the tabs it is trying to open up Edge from Parallels instead of looking up Edge on Mac. Not sure why it is doing that. Is there a way to fix that?

**Comment by fe9lix** [comment]
Hey @hsetty, could you use the official feature request template so that the author of the Edge extension gets mentioned? You can also use the "Request Feature" command when you open the details page for the extension in the Raycast store (it prefills some data for you).

**Comment by hsetty** [comment]
Done. 
https://github.com/raycast/extensions/issues/1164
Thanks!
