### ISSUE TITLE
[iterm] Support Python Scripts

### ISSUE THREAD

**Issue by FServais** [raycast/extensions#10300]
### Extension

https://www.raycast.com/ron-myers/iterm

### Description

Hi Team,

I currently have an iTerm Python script that opens some tabs and runs SSH -> tmux commands into them. It would be great to able to directly trigger it from Raycast.

I understand this is related to https://github.com/raycast/extensions/issues/9491, and comes with a challenge of using Python API instead of Applescript. However, iTerm comes with an environment that can be used to run the scripts: `$HOME/Library/Application Support/iTerm2/iterm2env/versions/<version>/bin/python3`.

I tried to implement it with `import exec from "node:child_process";` and seems to work but I don't know if there are any limitations or unwanted side effects. Also I'm restricting to Basic scripts, not "full environment" ones.

So what would be the pitfalls of using `child_process` to trigger the Python command?

iTerm 2 Python scripting documentation : https://iterm2.com/python-api/

Thanks!

### Who will benefit from this feature?

iTerm users who take advantage of Python Scripts for automation. 

### Anything else?

![Screenshot 2024-01-23 at 14 14 59](https://github.com/raycast/extensions/assets/5320536/42166aca-847c-408d-a656-33eb375b52b4)

**Comment by flops** [comment]
@FServais i'm currently working on it in free time, and i'll try to fix this issues with new update:
https://github.com/raycast/extensions/issues/9491
https://github.com/raycast/extensions/issues/10078
Maybe in a week or two.

**Comment by FServais** [comment]
Sounds great thanks! Should I close this one?

**Comment by flops** [comment]
No need, to be honest this issue is more appropriate for the future PR.
