### ISSUE TITLE
[Notion Page Search] Multiple workspaces

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [raycast/extensions#10318]
### Extension

https://www.raycast.com/reckoning-dev/search-notion

### Description

At the moment, only one pair of workspace-ID and headers is supported — ideally, it'd be easy to create searches for _multiple_ (or all?) Notion workspaces.

### Who will benefit from this feature?

People who use Notion both at work and at home

**Comment by Vesely** [comment]
It would be nice to have!

**Comment by kvenn** [comment]
I could see a good interface for this being:
Search Notion having a setting for "Default project" which lets you pick a specific one or "all" if you want to search all workspaces by default.

Then an additional command "Search Notion Workspace" which takes in an autocompleted workspace as the first argument and then the query as the second argument.

**Comment by kvenn** [comment]
I'd say this isn't stale.

**Comment by MaxLinWorm** [comment]
Plus one. Use notion for personal and work with separate workspaces
