### ISSUE TITLE
[Browser Bookmarks] always open bookmarks in default browser

### ISSUE THREAD

**Issue by shalgrim** [raycast/extensions#10317]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

I'm using this feature to switch to a new browser without transferring my old bookmarks. So I basically just want the bookmarks to be something I search from. I always want the link to open in my default browser

**Comment by thomaslombart** [comment]
You can do so by checking the checkbox "Open Bookmark's Browser"

![CleanShot 2024-01-25 at 09 37 11@2x](https://github.com/raycast/extensions/assets/16003285/39240b2e-98db-42fc-bc03-c138a94519f5)
