### ISSUE TITLE
[Convert Images] Can't convert to .webp

### ISSUE THREAD

**Issue by SergiuszR** [raycast/extensions#10313]
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

Using MacOS M1 on both machines. On both of them I have installed Raycast Pro. One machine doesn't have any issues when converting to webp, when the other one can't convert to this format only. (I didn't check all the others, cause Im interested mostly in webp)

### Steps To Reproduce

1. Click on the image
2. Run this extension
3. Pick webp

### Current Behaviour

Command failed: /Users/**user**/.config/raycast/extensions/7c158f0e-b70b-4922-8a1b-5c8a9ccb55d6/assets/webp/cwebp "/Users/**user**/Downloads/FAQ/image 3.png" -o "/Users/**user**/Downloads/FAQ/image 3.webp"
/bin/sh: /Users/**user**/.config/raycast/extensions/7c158f0e-b70b-4922-8a1b-5c8a9ccb55d6/assets/webp/cwebp: Bad CPU type in executable

### Expected Behaviour

Convert image to the given format.

**Comment by SKaplanOfficial** [comment]
Hi, I can look into this. Might just need to update the packaged executable. Odd that it works for one but not the other -- do you have Rosetta enabled on both?

**Comment by SergiuszR** [comment]
To be honest, I'm not sure. It used to work flawlessly. Just after I reinstalled the OS (clean install) it stopped working for webp format.
