### ISSUE TITLE
[Linear] Small layout shift in the menu bar window when there are no notifications every time you open the menu

### ISSUE THREAD

**Issue by gtsiolis** [raycast/extensions#10320]
### Extension

https://www.raycast.com/linear/linear

### Description

There's a small layout shift in the menu bar window when there are no notifications every time you open the menu.

### Steps To Reproduce

Install the extension and toggle the menu in the menu bar when there are no notifications.

https://github.com/raycast/extensions/assets/120486/7c15f94c-40bc-41cd-933c-bb6c6b3188b5

**Comment by thomaslombart** [comment]
It's a bug we need to fix within Raycast itself. I'll reclassify this one as an API bug instead of Linear.

**Comment by gtsiolis** [comment]
Thanks for taking a look, @thomaslombart.

**Comment by gtsiolis** [comment]
This is no longer reproducible. Thanks for anyone who fixed this. Cc @thomaslombart
