### ISSUE TITLE
[Apple Reminders] Ability to set hashtags

### ISSUE THREAD

**Issue by janss-en** [raycast/extensions#10324]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

it'd be useful to allow users to also set hashtags

### Who will benefit from this feature?

users who categorize their reminders with tags

**Comment by thomaslombart** [comment]
Thanks for the feature request! However, Apple doesn't provide that feature in their [APIs](https://developer.apple.com/documentation/eventkit/ekreminder) unfortunately, so I'll mark this issue as not planned.
