### ISSUE TITLE
[Music] add command to change output (ie. Macbook Speakers, Sonos Arc, Sony WH-1000xm3, ..)

### ISSUE THREAD

**Issue by joelgrimberg** [raycast/extensions#10328]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

with Apple Music you can 'bypass' the Sound Output of your MacOS. So your MacOS can be set to Macbook Speakers, while for example, the Apple Music output can stream to my Sonos Arc.

With Raycast I am currently able to set the output from MacOS, but this does not change the Apple Music (Itunes) output setting.

### Who will benefit from this feature?

Everyone ;) 

### Anything else?

![Screenshot 2024-01-25 at 08 38 51](https://github.com/raycast/extensions/assets/2995294/3c5b5774-fc9b-4937-a30f-133a4078f8f4)
![Screenshot 2024-01-25 at 08 39 40](https://github.com/raycast/extensions/assets/2995294/f16f2f5a-0e24-4916-accd-9f56d6c91e46)

**Comment by rawnly** [comment]
Hello thanks for opening the issue, unfortunately this goes above the possibility we have with the extension 😅

the extension uses apple script to automate some operations but it’s kind of limited. 

the current commands we support are most of the one exposed by the music app 🥲

**Comment by adisidev** [comment]
https://www.raycast.com/benvp/audio-device
This extension already does exactly what you asked for!

**Comment by rawnly** [comment]
@adisidev that extension changes the audio output of the computer, i think he wants to change the output only for the music app
