### ISSUE TITLE
[TidyRead - Streamline Your Daily Reading] Cannot fetch some RSS lists

### ISSUE THREAD

**Issue by alexandertsukanov** [raycast/extensions#10331]
### Extension

https://www.raycast.com/jaredliu233/tidyread---streamline-your-daily-reading

### Description

When I execute the "Daily Read" command, I encounter errors while fetching RSS feeds.

### Steps To Reproduce

When I execute the "Daily Read" command, I encounter errors while fetching RSS. Here are my sources:
https://in.relation.to/blog.atom
https://feeds.feedblitz.com/baeldung&x=1
<img width="745" alt="CleanShot 2024-01-25 at 11 40 53@2x" src="https://github.com/raycast/extensions/assets/17796771/0c4d7a6b-8829-4a89-bd07-4f2b5f75e7cc">

### Current Behaviour

Errors appear. 

### Expected Behaviour

Fetching RSS without any errors.

**Comment by DophinL** [comment]
@alexandertsukanov Hi Alex. First of all, thank you for using it and for the feedback!

I'm sorry for the trouble, this issue has been fixed inside this PR https://github.com/raycast/extensions/pull/10303 and is awaiting review.

When released, it will greatly reduce the likelihood of summary failures. Why do some articles failed to be summarized? You can refer to the documentation: https://www.tidyread.info/docs/why-some-articles-fail-to-be-summarized

**Comment by DophinL** [comment]
@raycastbot close this issue
