### ISSUE TITLE
[Carbon Screenshot for Raycast] Policy for removing broken extensions?

### ISSUE THREAD

**Issue by jpfeuffer** [raycast/extensions#10334]
### Extension

https://www.raycast.com/adelowo/carbon-code-screenshot-for-raycast

### Description

The mentioned extension is clearly broken with no response from the author.
#4673 
#9264 
#4140 

I was about to file another same bug report again until I saw all those closed issues.
If there is no intention or time to fix it (which I would understand), I suggest removing that extension to save people from wasting time.

### Who will benefit from this feature?

Everyone, including maintainers.

**Comment by adelowo** [comment]
Apologies @jpfeuffer , I am the author and I have been away for a while. Can you kindly help test https://github.com/adelowo/extensions/pull/1 ?

**Comment by adelowo** [comment]
Apologies @jpfeuffer , I am the author and I have been away for a while. Can you kindly help test https://github.com/raycast/extensions/pull/10402 ?
