### ISSUE TITLE
Make branch and drafts available in search

### ISSUE THREAD

**Issue by blv-Adrian-Lombera** [raycast/extensions#10346]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

Hi! At our team is extensively using branches to work. There is no Figma features to search and find branches easily. It would be very helpful if that was possible through raycast.

Drafts would also be a good add to the search.

**Comment by michaelwschultz** [comment]
Showing branches are a great idea. I'll look into this. As for drafts, Figma unfortunately doesn't make these available via the api.

**Comment by blv-Adrian-Lombera** [comment]
Awesome, thank you so much. Do you have any estimated releases in which you
think you could add this add?

**Comment by michaelwschultz** [comment]
I don't have time for it at the moment. Sorry, but I'll update you when it's available.
