### ISSUE TITLE
[Messages] Add command to open chat with a contact

### ISSUE THREAD

**Issue by third774** [raycast/extensions#10349]
### Extension

https://www.raycast.com/thomaslombart/messages

### Description

The "open message with this person" action is great — I wish this was available as a command!

### Who will benefit from this feature?

Everyone, I think? (I never know how to answer this question)

### Anything else?

🔥 extension! Love it!

**Comment by thomaslombart** [comment]
What do you mean with this action? It should already be possible to do so by creating a quick link.

**Comment by third774** [comment]
Doh! Sorry — what I meant was the ability to search my contacts list and pop open a text message to that person.
