### ISSUE TITLE
Custom Model names

### ISSUE THREAD

**Issue by turnercore** [raycast/extensions#10353]
### Description

We need to be able to type in our own string for 'model' which would allow you to use a lot more custom endpoints as well as fix the issue of different OpenAI models not being supported.

### Who will benefit from this feature?

Anyone that wants to use custom endpoints besides OpenAI, like Ollama, Perplexity, etc.

**Comment by mathieudutour** [comment]
Just inputting your own string doesn't really do anything. We would have to support all those different endpoints internally, each using different API formats with different API keys. So it's unlikely that we'll support arbitrary AI model with the extension API in the short term.
