### ISSUE TITLE
[Aspect Raytio] Calculate aspect ratio based on entered width and height

### ISSUE THREAD

**Issue by freinbichler** [raycast/extensions#10361]
### Extension

https://www.raycast.com/ickas/aspect-raytio

### Description

As a web developer, I am missing a few features in the current version of the extension:

Calculate aspect ratio: e.g. I see that an image is 1280x1000px in the design, so I want to define the aspect ratio of the image accordingly. I would want to enter the width and the height and get the aspect ratio as a result, like 32 : 25 in that case. Basically the functionality of this website: https://aspectratiocalculator.com

I would then want to quickly define this aspect ratio as a custom ratio and enter a few widths and get the corresponding heights as a result (for defining the responsive image sizes)

When I first tried your extension I entered both `width` and `height` values in the quick arguments. I was expecting to get the aspect ratio as a result to then do calculations with it.
I then understood that I should only enter width OR height to get the corresponding other value in the defined aspect ratios.

But maybe this could be the UX: if someone enters both width AND height in the arguments of the extension, a "temporary custom aspect ratio" is added, and I can then calculate different widths etc.

That would be very helpful for me. Because if I am coding one template, I would need to create one custom aspect ratio to calculate a few sizes and then never need it again...

**Comment by ickas** [comment]
@freinbichler the idea of getting the aspect ratio based on px dimensions is excellent.

The UX here is everything! So what you are suggesting is if the user enters the two values in the arguments when the extension opens, it can show (on the top of the list probably) the full dimensions (width + height) that the user entered a full resolution already and show the aspect ratio of that resolution, that's it?

Yes, it can be the best solution to add this (hidden) feature.

**Comment by freinbichler** [comment]
@ickas Basically yes, that is what I am suggesting. Ideally, the aspect ratio would show as the lowest possible integers, so e.g. if I enter 1920x1080 it should display 16:9 and if I enter 1280x1000 the result should be 32:25.

Also, these aspect ratios that are added by filling the width and height arguments simultaneously should ideally not persist forever. Maybe they persist until it is overridden (only 1 slot), or disappear at the end of the day, I am not sure. But I would be cumbersome to have to clean up the list every now and then. I think it should also not only persist for the current session, because I would switch between my code editor and raycast multiple times when I am implementing a template.
