### ISSUE TITLE
[GitHub Repository Search] Search only within your repositories

### ISSUE THREAD

**Issue by Antonio-Laguna** [raycast/extensions#10367]
### Extension

https://www.raycast.com/thomas/github-repository-search

### Description

I'll add some background here. I developed long time ago with a colleague a chrome extension. Code is here: https://github.com/firstandthird/github-repo-search

This extension is great since once you're in a couple of orgs, you get a ton of repositories and it's hard to comb through them. The downside is that is mainly for chrome, the UX on FF is subpar and doesn't work nicely on ARC as the omnibar doesn't seem to work either.

Right now this raycast extension extension (and the official one) searches through all of GH. My request is to add an option that just searches through your own repositories.

### Who will benefit from this feature?

I assume a lot of people? I don't think the GH search is useful by itself when it comes to combing through your repos

**Comment by mheidinger** [comment]
Just had a quick look at what the GitHub API offers and this seems to be fairly simple to provide by adding `user:@me` to the search text ([reference 1](https://docs.github.com/en/search-github/searching-on-github/searching-for-repositories#search-within-a-users-or-organizations-repositories), [reference 2](https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax#queries-with-usernames)).

But I could imagine that just searching your own users could be quite limiting for some, so potentially this could be extended to a configuration settings that accepts a lists of users/orgs to search in. In that settings, the value `@me` could then be provided by the user (would need to be mentioned in the description of that config setting).

One other thing I noticed while scrolling through the docs is that by default forks are excluded from search results. If someone only wants to search within their own repos, this could become a relevant option. Could be worth another preference to add `fork:true` to the search text.

Any opinions on such an approach?

**Comment by Antonio-Laguna** [comment]
@mheidinger I feel this makes sense. To be clear, I wasn't really requesting this to be the default or anything like that, I acknowledge it could be something useful to others. The way I use GH though is to go from repo to repo, create PRs, etc and if I search for PostCSS I don't want to see anything that's not on me (for example)

The fork seems like a good setting as well!

**Comment by mheidinger** [comment]
Created a PR for this: #10443
