### ISSUE TITLE
[ChatGPT] Custom models disappear and cannot be created

### ISSUE THREAD

**Issue by AeonWorks** [raycast/extensions#10384]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

As mentioned in the thread, my customized model suddenly became unavailable this month, a new default model appeared and could not be added.

I'm guessing that the 2024-01-11 update is the cause of this? Curious if other users haven't experienced this issue? 

This plugin is fantastic and I hope it can be restored. Thanks.

### Steps To Reproduce

1. MacOS 14.2.1 & Raycast v1.66.1 (including under the last update)
2. Called as usual (Hotkey or Alias)

**Comment by bxb100** [comment]
Could you share your config, or record a video?

**Comment by AeonWorks** [comment]
Problem solved, I removed the plugin and reinstalled it and was able to configure the new model. (However, the previously configured model is no longer available and needs to be reconfigured.)

Thanks again for developing such a great plugin.
