### ISSUE TITLE
[Bitwarden Vault] ...

### ISSUE THREAD

**Issue by julh18** [raycast/extensions#1038]
# Extension – [Bitwarden Vault](https://github.com/raycast/extensions/tree/484d200f15ecb8675c4cf2bcad55a1d6da615b8c/extensions/bitwarden/)
Author: @pomdtr

## Description
I was able to use the extension before and it worked great, but at some point I started having an error that does not let me use it. I tried to reinstall bitwarden cli, reinstall the extension, checking that the path is the correct one but nothing worked. 

## Error:
Error: Command failed with EACCES: /opt/homebrew/bin/bw status --session j854MRq7cB4rHguPq9Ldp1NodVtbSXHoGjg647yvLgW3LYOM4yHiIEGWt4lvS4BQaIvG7jvPCsSoK1P8InARDA==
spawn /opt/homebrew/bin/bw EACCES

spawn /opt/homebrew/bin/bw EACCES
__node_internal_captureLargerStackTrace:errors:464:5
__node_internal_errnoException:errors:594:12
Process.ChildProcess._handle.onexit:child_process:282:19
onErrorNT:child_process:477:16
processTicksAndRejections:task_queues:83:21

## Steps To Reproduce

1. Install bw cli 
2. Install bitwarden extension 
3. Unlock Vault 

## The current behavior
"Something went wrong, you can try reloading" 

## The expected behavior
Being able to use the extension. 

### Raycast version
Version: 1.29.1

![image](https://user-images.githubusercontent.com/96550689/156912113-a407e92e-8f21-42d0-94d2-4d132adca26a.png)

**Comment by pomdtr** [comment]
Thanks for reporting ! It looks like a permission issue. Can you try to run some bitwarden commands from the cli ?

**Comment by julh18** [comment]
You're right.  I installed it using homebrew, but when I try to run a command I get this message: "zsh: permission denied: bw" 
![image](https://user-images.githubusercontent.com/96550689/157496287-a464d332-148b-4247-9719-3a02a0edca2e.png)
