### ISSUE TITLE
Slack Status - Set yourself as active/away

### ISSUE THREAD

**Issue by MohamedISoliman** [raycast/extensions#1039]
# Extension – [Slack status](https://github.com/raycast/extensions/tree/56eada530324f6dc839f976d92ecc77d7b6e40a1/extensions/slack-status)

Author: @PitNikola

As a Raycast user, I want to have the ability to change the Slack status with an active/away toggle.

**Currently only the status changes without the active/away green dot**

**Who will benefit from this feature?**
Everyone using slack hopefully

**Comment by xswirelab** [comment]
For the implementer:

**API endpoint:** `https://slack.com/api/users.profile.set`
```bash
#!/bin/bash
# Api call to set the status(like it works now)
curl 'https://slack.com/api/users.profile.set' \
--header "Authorization: Bearer $SLACK_TOKEN" \
--header 'Content-Type: application/json; charset=utf-8' \
--data-raw "{
   \"profile\": {
        \"status_text\": \"404\",
        \"status_emoji\": \":coffee:\",
        \"status_expiration\": 0
    }
}"
```

**API endpoint:** `https://slack.com/api/users.setPresence`
```bash
#!/bin/bash
# Api call to set the presence
curl 'https://slack.com/api/users.setPresence' \
--header "Authorization: Bearer $SLACK_TOKEN" \
--header 'Content-Type: application/json; charset=utf-8' \
--data-raw "{
   \"presence\": \"away\"
}"
```

The `presence` parameter takes two options:
- `away` (string)
- `auto` (string)

The presence API also needs you to update the `OAUTH2 scope`. You will need to add an extra permission:
- `users.write`

Looking forward to the update.

**Comment by PitNikola** [comment]
Good suggestion, thank! I'll keep it in mind when I nave time to update the extension.

**Comment by MohamedISoliman** [comment]
@PitNikola any updates on this

**Comment by PitNikola** [comment]
Not yet. Unfortunately, haven't found time to look into it. The trickiest thing is to gracefully handle missing scopes and prompt users to update tokens without blocking them from using existing functionality. There is [another PR](https://github.com/raycast/extensions/pull/1330) for adding "pause notifications" checkbox which would require another scope update, it might be good to bundle it all together.
Not sure when I'll find time for it though. If anybody wants to contribute, it would be much appreciated.
