### ISSUE TITLE
[Raindrop.io] When you create a new collection while adding a new bookmark, if you subsequently add another new bookmark, the new collection is not available to select

### ISSUE THREAD

**Issue by atuttle** [raycast/extensions#10399]
### Extension

https://www.raycast.com/lardissone/raindrop-io

### Description

https://github.com/raycast/extensions/assets/46990/046af5f7-c4bb-446f-8621-85f4885a524b

### Steps To Reproduce

- Add a new bookmark and in the process, add a new collection
- Try to add another new bookmark to the collection you just created
- New collection is not available to select

**Comment by lardissone** [comment]
Good catch @atuttle!
Will fix asap
