### ISSUE TITLE
[Todoist] Most recent color change for menu bar task icon

### ISSUE THREAD

**Issue by bdielman** [raycast/extensions#10395]
### Extension

https://www.raycast.com/doist/todoist

### Description

After updating the extension I noticed the menu bar task icon for the Todoist extension is too dark when viewed in dark mode or using a darker wallpaper. I found it was recently changed in this PR: https://github.com/raycast/extensions/issues/9925

Attached is a screenshot of the current icon compared to others in the menu bar:
<img width="270" alt="Screenshot 2024-01-27 at 2 47 40 PM" src="https://github.com/raycast/extensions/assets/94547/cad34ccc-66ad-4f0a-861f-c931d69007b7">

### Steps To Reproduce

No real steps to reproduce, just a visual bug.

**Comment by Princeyadav05** [comment]
@thomaslombart sure, will have a look at it tonight.

**Comment by Princeyadav05** [comment]
@bdielman can you share you wallpaper or specific setting? because I tried with a dark wallpaper and the icon is fine.

<img width="533" alt="image" src="https://github.com/raycast/extensions/assets/22894003/2e186a93-4a14-46a5-a578-f712ad043515">

**Comment by bdielman** [comment]
It's any dark wallpaper that triggers the white/lighter icons. Toggling system appearance doesn't affect this either. I've tried both third party and Apple's own to see if it would make a difference

**Comment by thomaslombart** [comment]
@bdielman Could you share the wallpaper you're using? That way, @Princeyadav05 could probably reproduce it.

**Comment by bdielman** [comment]
Sure! These are the ones I've been using most the last few months, but the issue also happens with Apple's default wallpapers for me

https://basicappleguy.com/basicappleblog/autumn-gradients

**Comment by bdielman** [comment]
@thomaslombart @Princeyadav05 - Another possible solution is to duplicate the styles for the Apple Reminders extension's menu bar command. That displays correctly in any wallpaper and system appearance combination I've tried

**Comment by Princeyadav05** [comment]
@thomaslombart still not able to reproduce. Will you have a look at this?

![image](https://github.com/raycast/extensions/assets/22894003/e79e03c0-e1fd-4d55-a530-85f1dfcfc304)

**Comment by thomaslombart** [comment]
@Princeyadav05 It's unlikely I'll look at it soon as I'm focusing on other projects, sorry!

**Comment by bdielman** [comment]
So after removing the extension a number of times when this problem first occurred, it would appear darker like the example I posted. Just to test again today, reinstalling the extension worked this time and I'm seeing the menu bar icon in `#e5e5e5` as it's tinted in the code. 🤷 

I'm going to mark this is closed, but I'll create a new issue if it happens again. Thanks @thomaslombart and @Princeyadav05  for looking into this!
