### ISSUE TITLE
[Weather] Add preference to set 24h clock

### ISSUE THREAD

**Issue by teziovsky** [raycast/extensions#10397]
### Extension

https://www.raycast.com/tonka3000/weather

### Description

Hey! 👋 
I've got a cool idea. How about adding a preference option to set a 24-hour clock format? It's a small tweak that can make a big difference for users who prefer this time format for precision.

### Who will benefit from this feature?

Everyone who's used to the 24-hour clock mode

**Comment by tonka3000** [comment]
@teziovsky Check out #10407
