### ISSUE TITLE
[Messages] ... Send with message effect

### ISSUE THREAD

**Issue by Visual-Studio-Coder** [raycast/extensions#10394]
### Extension

https://www.raycast.com/thomaslombart/messages

### Description

I wish I could have a dropdown in the form that lets us choose what effect we want to send the message with (confetti, balloons etc)

### Who will benefit from this feature?

Adds some fun to the extension + its nice to have + its not going to inconvenience users if they just dont select anything in the dropdown

**Comment by thomaslombart** [comment]
Unfortunately, it's not possible to do that as Apple doesn't provide a complete API for it. Thanks for the feedback though!
