### ISSUE TITLE
[ChatGPT] Switching from "Ask Question" to "Full Text Input", the model change didn't work.

### ISSUE THREAD

**Issue by AeonWorks** [raycast/extensions#10391]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

After switching from "Ask Question" to "Full Text Input" and changing the model to Submit, the original model is still used to reply.

Because of this, every time a model needs to be switched, it needs to be interrupted that it is being generated using the wrong model (the previously selected model), and called again after the correct model is re-selected in order to do so.

The same result occurs when starting directly with full text input, typing in the content and selecting a model and then submitting it, the reply still uses the originally selected model.

I think this should be classified as a bug. although no error was reported after re-selecting the model.

### Steps To Reproduce

1. MacOS 14.2.1 & Raycast v1.66.1 (including under the last update)
2. Every time the model is switched, it will be like this
3. Regardless of whether "Enable full text input initially" is enabled or not, the problem persists

**Comment by bxb100** [comment]
hi, it should fixed on the latest version

**Comment by AeonWorks** [comment]
Very happy to hear that. Thank you for responding and handling this so quickly.

**Comment by AeonWorks** [comment]
Just tested and the latest version (January 28, 2024) already solves the problem.
