### ISSUE TITLE
[Change Case] Plugin not visible when using Stage Manager

### ISSUE THREAD

**Issue by jerzygangi** [raycast/extensions#10409]
### Extension

https://www.raycast.com/erics118/change-case

### Description

If Stage Manager is enabled, plugin is not visible.

### Steps To Reproduce

1. Install the plugin.
1. Disable Stage Manager.
1. Try to invoke the plugin.
1. Note that the plugin is visible and functions as expected.
1. Enable Stage Manager.
1. Try to invoke the plugin.
1. Note that the plugin is not visible. 

### Current Behaviour

Plugin is not visible.

### Expected Behaviour

Plugin is visible.

**Comment by erics118** [comment]
Not sure what you mean by "plugin"
