### ISSUE TITLE
[Obsidian] Numerical Year/Month/Date templates

### ISSUE THREAD

**Issue by j-peeters** [raycast/extensions#10426]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

Hi, I was trying to store tasks in my Daily note with the 'Append task' function. 
I have structured my Daily Note folder like this:
`Vault/Timestamped/2024/01/20240129` for a Daily note for the 29th of January in 2024
When I use the current placeholders it translates to this
`Vault/Timestamped/2024/Jan/2024JanMon`
It would be great if there was a setting to use numerical instead of textual templates for date formats.
Maybe I'm missing something, then I would be glad if someone could elaborate.

### Who will benefit from this feature?

To be more flexible in having tasks stored in a specific daily note.

**Comment by FServais** [comment]
I would suggest support of `{MM}` or `{DD}` could be added to templates?

I can take care of it if this approach seems fine.

**Comment by KevinBatdorf** [comment]
Sure thing @FServais 🙌

The code for that is here: https://github.com/raycast/extensions/blob/46b603905f374e904bb2612830569488a6fb0a9c/extensions/obsidian/src/utils/utils.tsx#L284

**Comment by j-peeters** [comment]
That addition would be really great. Thanks

**Comment by AdamAdamsMusic** [comment]
Just a thought - what do you guys think about potential Luxon/Moment.js integration for support for any kind of date/time templates? Maybe this could be the solution for date/time template parsing?

**Comment by KevinBatdorf** [comment]
Yeah that would probably work too. [date-fns](https://date-fns.org/docs/format) is another alternative

**Comment by FServais** [comment]
I was planning to use `luxon` *in addition* to the templates already supported today.

I have the diff but my workspace is in a messed up state seems like, build dist fails and publish fails as well, I'll try to troubleshoot this so we can have code review 👍

**Comment by FServais** [comment]
@raycastbot close this issue
