### ISSUE TITLE
[Arc] Unable to open links when Arc is running in the background and no windows are open

### ISSUE THREAD

**Issue by xhi-nico** [raycast/extensions#10455]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

I have noticed another issue trying to use the Arc extension in Raycast:

When Arc is completely closed/quit on MacOS, or when Arc has a window open, the extension works great opening links (except for when Arc is minimized, then it will open the link but not bring up the app).

When Arc has NO windows open but is still running in the background, the extension will fail opening up any link at all and give this error message:
![Screenshot 2024-01-30 at 13 19 00](https://github.com/raycast/extensions/assets/42051158/39ccb8b4-1827-47c0-9304-d9d418a3c10f)

Video of the issue:
https://github.com/raycast/extensions/assets/42051158/e10dc9e9-4bdd-44a6-9ad9-8dec646ba4c4

### Steps To Reproduce

1. close all windows of arc but leave it running in the background
2. attempt to open any link via "search arc" command in raycast

**Comment by tleo19** [comment]
@xhi-nico  Hey, Let me take a look i think I fixed this for another Arc command before.

**Comment by xhi-nico** [comment]
Thank you Léo!
