### ISSUE TITLE
[Toggl Track] Tags and Clients visible in the time entry window

### ISSUE THREAD

**Issue by InitPatch** [raycast/extensions#10456]
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Description

I'm working on a project, and I have a main task that I added as a description after having selected the project and the client. I need to use two different tags for it. However, when I try to start the timer using the Raycast extension, I can only see the main description and not the associated tags:
<img width="1470" alt="image" src="https://github.com/raycast/extensions/assets/15719066/5ab6ac7d-64f8-4ebd-8651-a8613b5ecd5e">

Ideally, I wish I could both the client and the tag that I selected when I first created the timer, in the time entry window

### Who will benefit from this feature?

I believe everyone who uses Toggl Track has different tags associated with the same tasks/descriptions, so they know which timer to start/stop whenever they do it through Raycast.

### Anything else?

Hit me at a.galand@gmail.com if you want more clarifications or screenshots to help with the context.

**Comment by bkeys818** [comment]
I'm currently working on major changes to this extension. I'll be adding several new commands and improving the existing ones.

If you'd like to create a PR, this is a fairly simple change. If not, I can add it to my list. I expect to be opening the PR with all my changes in the next two weeks.

**Comment by InitPatch** [comment]
Thanks @bkeys818 ! 
I'm not a developper, just a simple user, so I'm not even sure what a PR is ... Actually after asking Raycast AI, it seems to be Pull Request ... 
Aside from that, I wouldn't know what to do from here :)

**Comment by bkeys818** [comment]
@InitPatch, No worries! I'll add it to my list. You should see it along with a ton of other new features in the next few weeks.

**Comment by InitPatch** [comment]
Exiting news @bkeys818 ! I'm looking forward to try this new update soon! Thank you for what you're doing, since I discovered  Raycast a few weeks ago, I'm using your extension every single day! Keep up the good work!

**Comment by bkeys818** [comment]
I'm playing around with two different versions. @InitPatch and @franzwilhelm, which do you prefer?

<table>
  <tr>
    <td><img width="600" alt="Screenshot 2024-02-21 at 10 10 25 AM" src="https://github.com/raycast/extensions/assets/65252963/7c0502fa-c9ef-41f6-8b61-c252156467f0"></td>
    <td><img width="600" alt="Screenshot 2024-02-21 at 10 16 42 AM" src="https://github.com/raycast/extensions/assets/65252963/6ac67913-2fae-4472-a310-7f8c02993673"></td>
  </tr>
</table>

**Comment by InitPatch** [comment]
I think the 2nd one (on the right) makes more sense visually. Getting everything close to each other looks cleaner than on the opposite side of the Raycast window; easier/faster to read, IMO.
