### ISSUE TITLE
[OneNote] ... Doesn't allow you to open in app

### ISSUE THREAD

**Issue by TheA6** [raycast/extensions#10450]
### Extension

https://www.raycast.com/alewandowski/onenote

#### Error:
```
Error: missing expected parameter key: value


```
When I downloaded this extension, I was able to go through everything, and read everything, but as soon as I try to "open in onenote" the extension crashes. 

### Steps To Reproduce

1. Open extension
2. Hit the enter key to open a OneNote document
3. Hit the enter key to "open in OneNote"
4. Crashes

### Current Behaviour

Does not open in app

### Expected Behaviour

Opens the file in app

**Comment by vlcinsky** [comment]
The issue still holds true. Please, reopen.

**Comment by TheA6** [comment]
It seems it might be due to the organisational account - I haven't been able to make it work on organisational accounts

**Comment by TheA6** [comment]
How does one reopen the issue?
