### ISSUE TITLE
[Spotify Player] Menu bar player is not refreshing (hide icon when idle)

### ISSUE THREAD

**Issue by lengeradam** [raycast/extensions#10466]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Menu bar player from Spotify extension is not being automatically refreshed.
It's refreshed, if I do it manually via the command from Raycast. But not when songs change.

### Steps To Reproduce

1. Activate the menu bar player command for spotify.
2. Current song is displayed.
3. The displayed song stays the same even when the songs already changed.

### Expected Behaviour

Displayed song will change after it's changed.

**Comment by peduarte** [comment]
The change is not immediate and can take up to 30 seconds. Did it not change even after 30 seconds?

**Comment by lengeradam** [comment]
It actually works now 🤷‍♂️ I don't know what I did beside turning the command off and on (which I've also tried before raising the issue). I'm not able to reproduce it.
Before that it stayed the same until it was refreshed (e.g. 10 minutes or longer).

I will close this one, hopefully it will work now. Thanks for reaching out 🙂

**Comment by lengeradam** [comment]
Actually the issue is still there 😑
E.g. this morning there is nothing in my menu bar (I've chosen the hide option when the player is idle). After I start to play some music nothing has changed and nothing is displayed.
The refresh action from raycast doesn't work.
The only thing which works is to disable menu bar item and enable it again.

**Comment by peduarte** [comment]
Thanks for the report. Can you share any more details? Where did you initiate the play function from?

**Comment by lengeradam** [comment]
It doesn't matter how I initiate it. I've done it directly in Spotify app and by "Play" key on keyboard. For neither of those cases menu bar item appeared.
I'm on macOS 14.2.1 and I'm using the latest version of Raycast.
Let me know, if you need any specifics or other details.

**Comment by peduarte** [comment]
Ok, pinging @sxn for help 😄 Any clues what may be causing this or how could we debug?

**Comment by sxn** [comment]
would be useful to see what gets logged when the menu bar command is refreshed from the root search. This page describes how to view the logs: https://manual.raycast.com/troubleshooting/getting-logs-via-consoleapp

**Comment by lengeradam** [comment]
[extension-diagnostics.txt](https://github.com/raycast/extensions/files/14179761/extension-diagnostics.txt)
[ray.20240206_135029.log](https://github.com/raycast/extensions/files/14179763/ray.20240206_135029.log)

Here are both files.

**Comment by sxn** [comment]
hm, judging from the logs, it -seems- like the command is running normally… 🤔

A long shot, but would still be good to exclude: is there enough room in your menu bar for the item to show up? macOS will not show items if it decides they wouldn't fit, sometimes even if -theoretically- there's enough space there. You could try something like [Bartender](https://www.macbartender.com/Bartender5/) or [HiddenBar](https://github.com/dwarvesf/hidden)..

**Comment by lengeradam** [comment]
I think there is enough space. See screenshot.
![SCR-20240207-icjr](https://github.com/raycast/extensions/assets/53938139/844df8a4-b87e-4908-b24b-9825975f51bb)
When I disable the menu bar item and activate it again, it's displayed and it's updating again.
![SCR-20240207-idqy](https://github.com/raycast/extensions/assets/53938139/be242ff4-f89b-436b-91d1-cc69f2cb90d8)

**Comment by sxn** [comment]
ah yeah, there seems to be plenty of space there. Weird. I'll have a look if I can somehow reproduce the issue, it may be some bug in the extension / Raycast…

**Comment by lengeradam** [comment]
It seems that this setting is the culprit:
![image](https://github.com/raycast/extensions/assets/53938139/9c3e56b1-a1d3-48ad-8e73-be13f4434405)
When it's turned off, it works as expected.
When it's turned on, it works until it goes idle and then it doesn't appear again in the menu bar.

**Comment by xhi-nico** [comment]
Any update on this issue?

**Comment by xhi-nico** [comment]
still a valid issue.

**Comment by korak1111** [comment]
[xhi-nico](https://github.com/xhi-nico)
Try uninstalling the Spotify extension and reinstalling it. Worked for me.
