### ISSUE TITLE
[ChatGPT] Support page navigation keys in the search result, chat and conversations

### ISSUE THREAD

**Issue by danySam** [raycast/extensions#10467]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

When the search result is a bit long, you must rely on the mouse to scroll through the result.

It'd be helpful if we could focus on the right pane and scroll using the native navigation keys (Settings > Advanced > Page Navigation Keys) to scroll through the chat/message.

### Who will benefit from this feature?

Most users who prefer to use a keyboard over a mouse would find this very helpful

**Comment by bxb100** [comment]
It looks like no API can pull that off
