### ISSUE TITLE
[Apple Notes] Bug when trying to search notes

### ISSUE THREAD

**Issue by RihardsVeters** [raycast/extensions#10468]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

Hi! I’m experiencing problem with Apple Notes extension. I’m not able to search my notes anymore. Is it known bug or something I’ve done wrong?
![image](https://github.com/raycast/extensions/assets/41144957/76b86f13-2aa6-4bc6-a189-002dab0dd9a8)

### Steps To Reproduce

open search notes extension, see error.

**Comment by RihardsVeters** [comment]
Someone is going to fix this??

**Comment by pernielsentikaer** [comment]
@tumispro haven't we seen this before?

**Comment by mathieudutour** [comment]
yes: https://github.com/raycast/extensions/issues?q=is%3Aissue+is%3Aopen+database+disk

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/6916, so I'll mark it as such.
