### ISSUE TITLE
[Obsidian] Open in New Tab doesn't work

### ISSUE THREAD

**Issue by LaurenzUeckert** [raycast/extensions#10469]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

No matter if I open the searched note in a new tab or not, it opens the note in an already used tab

### Steps To Reproduce

1. have a tab open in obsidian
2. search note with obsidian raycast extension
3. open note in new tab
4. note gets opened in already used tab, instead of new tab

### Expected Behaviour

It should open a new tab

**Comment by KevinBatdorf** [comment]
I gave it a try just now and it seems fine to me. Can anyone else reproduce it?


https://github.com/raycast/extensions/assets/1478421/8dad4450-f016-4f1b-afb5-3a6716f35ef5

**Comment by FServais** [comment]
I've tried as well, it also works as expected.

**Comment by LaurenzUeckert** [comment]
Found the problem, the plugin: "close similar Tabs" seems to disable this
feature :(
thanks for your help!

Am Mi., 31. Jan. 2024 um 10:32 Uhr schrieb FServais <
***@***.***>:
