### ISSUE TITLE
[arc] Kagi search suggestions

### ISSUE THREAD

**Issue by bdsqqq** [raycast/extensions#10461]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

https://kagi.com/assets shows that `https://kagi.com/api/autosuggest?q= ` can be used for suggestions for Kagi.

This was recently suggested in a [PR comment](https://github.com/raycast/extensions/pull/10373#discussion_r1471976454)

### Who will benefit from this feature?

Users that have Kagi as a default search engine.

**Comment by omar-salama** [comment]
@raycastbot close this issue.
