### ISSUE TITLE
[GrammariX] ...

### ISSUE THREAD

**Issue by fpwex9** [raycast/extensions#10475]
### Extension

https://www.raycast.com/hakob_nersesian/grammari-x

### Description

It would be convenient if the selected text could be passed as an argument to the extension. This way, whenever I utilize the shortcut, the text would automatically be copied and sent for spell check. 

### Who will benefit from this feature?

everyone who uses it frequently

### Anything else?

Now I have to hit Cmd+C, Cmd+Shift+S (shortcut to launch GrammariX), then Cmd+V, Enter, then close the window and Cmd+V to paste the corrected text. It would be great to have a single shortcut to correct spellcheck and paste the result back

**Comment by hakob8956** [comment]
Done. PR is ready. Thanks for your feedback.
You can track it 
https://github.com/raycast/extensions/issues/10475.
