### ISSUE TITLE
Add the possibility to use another key other than Return

### ISSUE THREAD

**Issue by LeonardoGentile** [raycast/extensions#10476]
### Description

Hello,
this issue probably shouldn't belong here but I didn't know where I should have assigned.
Feel free to close it or move it somewhere else if it's Off-topic. 

There is a conflict when using tools like Karabiner that involves re-assigning the Return key on certain conditions. 
For example "Using Return as Open and Fn+Return to rename" when Finder is active.

That means that if Finder is active and I call Raycast then Return won't work as it is remapped by Karabiner.

The Karabiner issue is explained here [here](https://github.com/pqrs-org/Karabiner-Elements/issues/2942) but it probably won't be fixed.

My question is if it would be possible to assign another key instead of Return for confirming Raycast actions? 
If not it would be possible to add this feature or to solve this conflict somehow? 

### Who will benefit from this feature?

Users using Karabiner and Finder Keys remapping

**Comment by mathieudutour** [comment]
It's very unlikely that'll do that, `Return` is just too much of natural key to confirm stuff

**Comment by LeonardoGentile** [comment]
@mathieudutour sure thing, I don't want to change that. 
I need to make it work anyway, so for example let `shift-Return` work as if it was a simple `Return`.
This way I'll get Karabiner work and Raycast won't complain
