### ISSUE TITLE
[GitHub] Menu bar icon doesn't update until dropdown is open

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#10481]
### Extension

https://www.raycast.com/raycast/github

### Description

When I mark all the notifications as read on the menu bar item, the icon doesn't become white (from orange), I have to press on the dropdown again for it to update

### Steps To Reproduce

See above

### Current Behaviour

See above

### Expected Behaviour

See above

**Comment by thomaslombart** [comment]
I can't reproduce it. Could you share a recording? It'll make it easier to see what's happening.

**Comment by FezVrasta** [comment]
I did disable the menu bar after I opened this issue, I went to enable it again to record a clip and now everything seems to work properly 🤔

**Comment by FezVrasta** [comment]
AH! wait, it happened again, I need to find a way to record it...
