### ISSUE TITLE
[Ngrok] Couldn't find ngrok CLI

### ISSUE THREAD

**Issue by imkebe** [raycast/extensions#10498]
### Extension

https://www.raycast.com/ubinatus/ngrok

### Description
I can't create new tunnel. `Couldn't find ngrok CLI` error is risen.

The ngrok cli was installed using brew and it works.
Moreover the tunnel created via CLI can be managed via extension.

The valid apikeys are provided in extension configuration page.

### Steps To Reproduce

![image](https://github.com/raycast/extensions/assets/4148157/0a87f1ab-0a97-4a1f-b24c-239e04c22bc1)

### Current Behaviour

CLI not fount error

### Expected Behaviour

Tunell creation

**Comment by ubinatus** [comment]
Hi @imkebe, the extension checks if ngrok CLI is installed first using the `where ngrok` command internally. Mind running that in your terminal and telling me if a path is returned? If the CLI is found (which should be according to your description), have you installed ngrok CLI through brew AFTER installing the extension? If so, mind restarting Raycast?

**Comment by imkebe** [comment]
```❯ where ngrok
/opt/homebrew/bin/ngrok
❯ /opt/homebrew/bin/ngrok version
ngrok version 3.5.0```

I installed it long time ago, so i have restarted whole OS multiple times.

**Comment by imkebe** [comment]
#### Error:
```
Error: Command failed with exit code 1: which ngrok
    at /Users/kebe/.config/raycast/extensions/4297d17c-0394-458e-abf9-5befc9fd0660/index.js:12:1824
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by karocksjoeli** [comment]
Same error , I am install ngrok with HomeBrew , and mine terminal does can execute `ngrok`

**Comment by ubinatus** [comment]
Thought it was a permission issue that is preventing the Raycast ngrok extension script from executing or accessing the terminal (guess it requires full disk access). However, I'm seeing that it only happens when ngrok is installed through homebrew.

I'm aware that syncing between a Silicon and Intel based macOS. Homebrew installs to /opt/homebrew on Silicon and /usr/local/homebrew on Intel.

Currently debugging this. Keeping you posted for a possible solution.

**Comment by ubinatus** [comment]
Found the issue. Indeed just related to ngrok installed through homebrew. Creating a PR with the fix. Thanks for reporting this @imkebe and @karocksjoeli

**Comment by imkebe** [comment]
Thanks. That started to work.
However now would say i have another issue... There is a foreground terminal session invoked. Shouldn't it be a background taks? Should I rise another bug?

![Zrzut ekranu 2024-02-2 o 13 24 51](https://github.com/raycast/extensions/assets/4148157/f1938018-e016-462d-bedc-108760f4f452)

**Comment by ubinatus** [comment]
Sadly can't be a background task as Raycast would send a SIGTERM signal to any process hanging out after a period of time.

The first version of this extension had ngrok instance running in the background. However, received feedback that tunnels where stopped after 15 minutes. 😢
