### ISSUE TITLE
[GitHub] Requested Reviews in Menu Bar

### ISSUE THREAD

**Issue by Martin-Gonzalez90** [raycast/extensions#10501]
### Extension

https://www.raycast.com/raycast/github

### Description

It would be nice to add to the PR menu bar, the requested reviews so one can have active PRs and reviews in the same menu.
It can be another section in the same Menu, here an example.

![image](https://github.com/raycast/extensions/assets/89008098/30cf98e7-8f3b-4eea-8ef6-b2032bec63a5)

### Who will benefit from this feature?

Anyone using this extension :D

**Comment by MartinGonzalez** [comment]
PR in progress
https://github.com/raycast/extensions/pull/10507
