### ISSUE TITLE
[Apple Reminders] Crash repeatedly when creatingg reminder

### ISSUE THREAD

**Issue by metropol** [raycast/extensions#10505]
### Extension

https://www.raycast.com/raycast/apple-reminders

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

Looking at Memory in Activity Manager, all looks good. Memory pressure is green. Swap used: 442 MB.

### Steps To Reproduce

MacBook Pro M1 Pro 16GB
Command-Space to invoke RayCast
type create reminder
while typing title for reminder, the extension crashed.

**Comment by thomaslombart** [comment]
Thanks for flagging the issue. How many reminders and lists do you have?

**Comment by thomaslombart** [comment]
Hmmm… Could you share a recording? It'll make it easier to see what's happening.

**Comment by metropol** [comment]
Here it is. Invoke RayCast then tried three times in a row to create a
reminder. After it crashes, I just hit enter to reload and retry.
HTH

**Comment by thomaslombart** [comment]
I can't see the attached recording 😬

**Comment by metropol** [comment]
Can you try this?

**Comment by metropol** [comment]
Doesn't play from within GMail, but it works if I download it first.

**Comment by metropol** [comment]
Here's the clip.

https://github.com/raycast/extensions/assets/288290/ddf2b84a-3b94-4083-b731-951bfed95197

**Comment by thomaslombart** [comment]
Thanks for the recording. So, the command crashes _while_ you're typing the reminder's title, right? Not when submitting the reminder?

**Comment by metropol** [comment]
Yes, while I'm typing the title. Never got past the title.

**Comment by thomaslombart** [comment]
Oh, I think I know what's going on. We're loading upfront all reminders, whether they're still active or completed, so you must have a large number of completed reminders if it fails. Could you tell me how many completed reminders you have?

**Comment by metropol** [comment]
Indeed. I have 11784.

**Comment by thomaslombart** [comment]
So, that's the thing. We need to make some optimizations here. I'll work on it in the next few weeks.

**Comment by thomaslombart** [comment]
I shipped a fix for that, so you should be able to use it now.

**Comment by metropol** [comment]
It is working now (tested with version 1.68.1). Thanks!
