### ISSUE TITLE
[Linear] Images in descriptions failed to load

### ISSUE THREAD

**Issue by termosa** [raycast/extensions#10510]
### Extension

https://www.raycast.com/linear/linear

### Description

![CleanShot 2024-02-02 at 00 17 06@2x](https://github.com/raycast/extensions/assets/494013/382b63e6-246e-4ac4-9382-96d20cbda364)
All of the images in Linear ticket descriptions are failed to load.
Any chance it can be fixed?
Seems like Linear is blocking the access.

### Steps To Reproduce

1. Open "Search Issues" command from Linear extension
2. Find and open a ticket that contains image in the description
3. Ensure that images are not displayed

**Comment by OleksandrRakovets** [comment]
Linear requires [additional authentication for their assets](https://developers.linear.app/docs/oauth/file-storage-authentication).
