### ISSUE TITLE
[Clockify] Optional description

### ISSUE THREAD

**Issue by simonknittel** [raycast/extensions#10519]
### Extension

https://www.raycast.com/isma/clockify

### Description

When starting a new timer, the extension currently asks you to pick a project and a description. However, Clockify does not require you to have a description. 

The extension already correctly displays time entries with no description, you just can't start such one.

I would wish to start a new timer without a description.

**Comment by simonknittel** [comment]
I still wish for that feature

**Comment by shkm** [comment]
Still want this :-).

I'd love to have a stab myself but not sure I can find the time.
