### ISSUE TITLE
Support min/max date range

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#1051]
**Describe the feature and the current behavior/state.**

The date picker component should allow a way to limit the minimum and maximum selectable date.

**Will this change the current API? How?**

Two new properties to the component.

**Who will benefit from this feature?**

Users won't accidentally select invalid dates.

**Any Other info.**

**Comment by thomaslombart** [comment]
Done in [1.53.0](https://www.raycast.com/changelog/1-53-0).
