### ISSUE TITLE
[Get SSH Key] Error when executing the "Copy SSH Key" command if there are multiple keys

### ISSUE THREAD

**Issue by forketyfork** [raycast/extensions#10526]
### Extension

https://www.raycast.com/Theon/get-ssh-key

### Description

When I use the "Copy SSH Key" command, I get a "Something went wrong" error with the following error message:

```
Error: No enabled command 'list' found
```

I see that in case of multiple keys, the extension code just launches the "list" command. This command is present in the code and enabled in my settings. The command also works properly when executed directly via "List SSH Key".

### Steps To Reproduce

1. macOS Sonoma 14.3, Raycast v1.66.2, latest extension updates.
2. I have multiple SSH keys in the `~/.ssh/` directory.
3. Both "Copy SSH Key" and "List SSH Key" commands are enabled in the Raycast settings.
4. Use the `Copy SSH Key` command.

### Current Behaviour

"Something went wrong"

### Expected Behaviour

The SSH key list is opened.

**Comment by forketyfork** [comment]
The issue is still reproducible as of Raycast 1.70.2.

**Comment by forketyfork** [comment]
The issue is still reproducible as of Raycast 1.73.3.

**Comment by j3lte** [comment]
This should be fixed in the last update

@raycastbot close this issue
