### ISSUE TITLE
[CleanShot X] It stopped working

### ISSUE THREAD

**Issue by phuctm97** [raycast/extensions#10520]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

All Cleanshot commands in Raycast stopped working

### Steps To Reproduce

1. In macOS Sonoma
2. Install Cleanshot
3. Install Cleanshot Raycast extension
4. Try any Cleanshot command in Raycast, nothing happens

**Comment by Aayush9029** [comment]
@phuctm97 did you read the [docs](https://www.raycast.com/Aayush9029/cleanshotx)?

**Comment by phuctm97** [comment]
> @phuctm97 did you read the [docs](https://www.raycast.com/Aayush9029/cleanshotx)?
> 
> ![](https://github.com/raycast/extensions/raw/e24c69324167a7e932c63c20ffaca3e8ea33bddf/extensions/cleanshotx//media/EnableAPI.png) )

My bad, the docs indeed fixed it. I was confused because previously I didn't have to configure anything and it still works.
