### ISSUE TITLE
[Zoom] 400 Error After OAuth Changes

### ISSUE THREAD

**Issue by cbqrr** [raycast/extensions#10525]
### Extension

https://www.raycast.com/raycast/zoom

### Description

Error: Error while refreshing tokens: 400 (Bad Request)
{"error":"invalid_grant"}

    at withAccessToken(fie)
Dr:index.js:11:2490
    at ray-navigation-stack
Lo:index.js:11:2088

### Steps To Reproduce

In the latest version of the Zoom extension after the Jan 31 OAuth changes. 

### Current Behaviour

It isn't working. =) 

### Expected Behaviour

It should work =)

**Comment by mathieudutour** [comment]
It should be fixed in the latest release of the extension
