### ISSUE TITLE
[Google Bard] ...

### ISSUE THREAD

**Issue by ihtesham-chowdhury** [raycast/extensions#10529]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

Bard extension in raycast isn't working even after putting the right api key. Is it possible that google stopped this workaround of putting api keys from cookies? 

### Steps To Reproduce

1. inspect elements in bard page
2. find the application tab
3. click on cookies tab
4. now find __Secure-1PSID
5. now copy the value and paste it to the api page in bard extension
6. then the bard shows error and no command is working

**Comment by arisfavia** [comment]
I have the same problem

**Comment by NeoHuncho** [comment]
same problem
