### ISSUE TITLE
[Zoom] ...invalid grant error

### ISSUE THREAD

**Issue by keebo** [raycast/extensions#10533]
### Extension

https://www.raycast.com/raycast/zoom

### Description

Error: Error while refreshing tokens: 400 (Bad Request)
{"error":"invalid_grant"}

    at withAccessToken(fie)
Dr:index.js:11:2490
    at ray-navigation-stack
Lo:index.js:11:2088

### Steps To Reproduce

Macbook Pro M3 Max
OS: Sonoma 14.3
Error occurs while the extension is enabled. Rebooting and restarting Raycast does not solve the issue. None of the commands work in Raycast.

**Comment by imartinez921** [comment]
I am also having a similar situation, but with the extension **Google Workspace**.
Same steps to reproduce, but I am running Ventura 13.0 on a M2 Macbook Air.

```
Error: Error while fetching tokens: 400 (Bad Request)
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}

{
  "error": "invalid_grant",
  "error_description": "Bad Request"
```

**Comment by hugows** [comment]
Uninstalling and reinstalling made it work for me. I've seen this happen with a couple extensions btw. We need commands to re-run the initial config (something like "Reinstall" our Re-auth)

**Comment by mathieudutour** [comment]
It should be fixed in the latest release of the extension
