### ISSUE TITLE
Getting error "cannot search notes database disk image malformed"

### ISSUE THREAD

**Issue by Chiarandini** [raycast/extensions#10530]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

I have have started getting the following error message when using the "search note" command:

![image](https://github.com/raycast/extensions/assets/35749479/00c6b448-54c7-4e7e-9a0d-cf5f33044dcf)

The effect persists after uninstalling and reinstalling, as well as restarting my computer. I'm running macOS Sonoma v14.0 on a Macbook Air. The "New Note" command works as expected. When opening Apple Notes, I can search through my notes without issue. 

### Steps To Reproduce

1. Install Notes (I used the "Store" command provided by Raycast)
2. open "Search Notes" (I tried doing it by running the command and setting up a keyboard shortcut)
3. the error is at the bottom of the screen (as attached in the image)

### Current Behaviour

Shown in the screenshot

### Expected Behaviour

Fetches the notes and allows you to fuzzy search through them.

**Comment by Chiarandini** [comment]
UPDATE

So it started working again. I'm not sure if this is caused by an issue on my system or a concurrency issue?

**Comment by derrickshowers** [comment]
I'm also running into this issue. Seems to be new, as I use this extension a lot.

**Comment by chungweileong94** [comment]
It seems to be a common issue, and you can find more details at https://github.com/raycast/extensions/issues/6916.

One of the solutions is to rebuild the Apple note database as mentioned in the issue. Another much easier way to fix the issue is to sign-out and sign-in your Apple ID again in Apple Note, this will eventually rebuild the DB again.

**Comment by BlackJoker90** [comment]
Same problem here!

**Comment by RihardsVeters** [comment]
Problem is still out there :D

**Comment by mathieudutour** [comment]
Have you tried to sign-out and sign-in your Apple ID again in Apple Note?

**Comment by RihardsVeters** [comment]
> Have you tried to sign-out and sign-in your Apple ID again in Apple Note?

No, cause Apple notes it self works fine.. Extension isn't working.

**Comment by mathieudutour** [comment]
Can you try?

**Comment by RihardsVeters** [comment]
Opened system preferences, Internet accounts, icloud, Apps using icloud, turned off note syncing, then turned it back on an now it works fine..

**Comment by RihardsVeters** [comment]
Let's wait when all my notes will sync again.

**Comment by RihardsVeters** [comment]
Now that extension doesn't find all my notes..

**Comment by RihardsVeters** [comment]
Yeah so, it doesn't find locked notes.

**Comment by thomaslombart** [comment]
Hey there, the issue should be fixed as part of the [latest update](https://github.com/raycast/extensions/pull/11450). I also added some improvements here and there. Let me know if it works fine for you!

**Comment by BlackJoker90** [comment]
I no longer receive the error message, but the extension is unable to locate any notes now. I've already re-enabled note sync in iCloud Settings and restarted the Mac, but it hasn't resolved the issue.

**Comment by BlackJoker90** [comment]
Okay my bad I had first to resync the notes in the app itself now everything is working like charm thanks for the update :)
