### ISSUE TITLE
[Jira] Defaults for "create issue" command

### ISSUE THREAD

**Issue by christianbundy** [raycast/extensions#10531]
### Extension

https://www.raycast.com/raycast/jira

### Description

When I select "create issue", it defaults to the first alphabetical project. I have to change the project, change the issue type, set the assignee to myself, etc., on every ticket.

### Who will benefit from this feature?

Jira users who often create tasks for the same board, with the same issue type, assignee, etc.

**Comment by luizeboli** [comment]
This is beneficial not only when creating a new issue, but also when searching or using filters, you always have to select the project / filter. If we had something to save the last used value it would be a great improvement

**Comment by thomaslombart** [comment]
Thanks for the feature request!

**Comment by Samywamy10** [comment]
+100
