### ISSUE TITLE
[Splix] Support for logging in with email

### ISSUE THREAD

**Issue by joeyfigaro** [raycast/extensions#10532]
### Extension

https://www.raycast.com/splix.app/splix

### Description

Splix supports both Google and plain email signups/logins–it'd be nice if this extension offered signing in via email.

### Who will benefit from this feature?

People who didn't sign up via Google

**Comment by cwooldridge1** [comment]
> Splix

Hey! Thanks for using Splix! This is next on my queue after the mobile app is done.
