### ISSUE TITLE
Snippet cursor placement

### ISSUE THREAD

**Issue by MishaFrenkman** [raycast/extensions#1054]
**Describe the feature and the current behavior/state.**
Would be nice, when creating a snippet, one could choose where to place the cursor, after snippet has been expanded. 
Alfred 4 has this feature, which is the only reason I'm hesitating to switch.

Right now, cursor is always at the end of the expanded snippet.
**Will this change the current API? How?**
Snippet editor needs a way to tell where the cursor should go. Like in Alfred 4, one could write `{cursor}` inside the snippet so it nows exactly where to go. 
eg.
snippet keywoard: `;cl`
snippet: `console.log({cursor});`
-> places the cursor inside parentheses after expansion
**Who will benefit from this feature?**
Everyone ;)
**Any Other info.**

**Comment by fe9lix** [comment]
Hey @MishaFrenkman – could you report this through Raycast's feedback command? (It's unrelated to the API...)

**Comment by aurawindsurfing** [comment]
@MishaFrenkman I second that request, it should be part of snippets as well as {clipboard}

**Comment by MishaFrenkman** [comment]
@aurawindsurfing it's shipped in the latest updated

**Comment by aurawindsurfing** [comment]
nice one!
