### ISSUE TITLE
[Unsplash] ... The redirect uri included is not valid.

### ISSUE THREAD

**Issue by rutmehta** [raycast/extensions#10550]
### Extension

https://www.raycast.com/eggsy/unsplash

### Description

The redirect URL when signing into Unsplash through the Raycast extension is invalid. 
![CleanShot 2024-02-03 at 20 53 19@2x](https://github.com/raycast/extensions/assets/66664053/569e07bf-7d79-46aa-b535-f508a5bb13d5)

### Steps To Reproduce

Try to run unsplash for the first time without authorizing. It will take you to the authorization page, which is invalid.

### Expected Behaviour

Sign in normally, seamlessly.

**Comment by mv-stns** [comment]
After basically one year now, this issue still persists for me @eggsy and @kkange friendly reminder to look into this

**Comment by aindriu80** [comment]
please take a look.... tried the following but not accepted

`urn:ietf:wg:oauth:2.0:oob`

**Comment by eggsy** [comment]
This is a duplicate. Please read the extension's store page/readme. You have to manually add in a redirect uri which is specified in the readme file. That will fix this problem.

**Comment by mv-stns** [comment]
> This is a duplicate. Please read the extension's store page/readme. You have to manually add in a redirect uri which is specified in the readme file. That will fix this problem.

Sorry for the inconvenience. I had it running before, but I didn't think it could be something this simple. 😓
Thank you!
