### ISSUE TITLE
[Asana] ...

### ISSUE THREAD

**Issue by samuel-clara** [raycast/extensions#10582]
### Extension

https://www.raycast.com/raycast/asana

#### Error:
```
Error: Error while refreshing tokens: 400 (Bad Request)
{"error":"invalid_grant"}

    at withAccessToken(r3)
Dr:index.js:11:2490
    at ray-navigation-stack
Lo:index.js:11:2088
```

### Steps To Reproduce

Creating a task with the Asana Extension via Raycast

**Comment by mathieudutour** [comment]
It should be fixed in the latest release of the extension
