### ISSUE TITLE
[Change Case] Some transformations don't work

### ISSUE THREAD

**Issue by ErikAbele** [raycast/extensions#10594]
### Extension

https://www.raycast.com/erics118/change-case

### Description

When copying/selecting text in UPPERCASE and then selecting e.g. the Sentence or Title case transformation, the text stays all uppercase. I would expect that it gets transformed according to the selected case action.

### Steps To Reproduce

1. Select or copy uppercase text, e.g. THIS IS A TEXT
2. Call the extension via Raycast and select the Title Case or Sentence Case actions
3. Text stays all uppercase

See screenshot:

![CleanShot 2024-02-05 at 17 52 02@2x](https://github.com/raycast/extensions/assets/185813/65fb753a-c483-426f-ba40-43eb816a1161)

### Current Behaviour

Text stays uppercase, doesn't get transformed.

### Expected Behaviour

Text should be transformed to selected action.

**Comment by Princeyadav05** [comment]
@erics118 converting all the characters to lowercase and then using the underlying library to change to title case would work better i guess?

**Comment by erics118** [comment]
It seems that it could result in some unintended consequences. See https://github.com/blakeembrey/change-case/issues/308.

**Comment by Princeyadav05** [comment]
Okay.

**Comment by ErikAbele** [comment]
> This is the correct behavior. The underlying library keeps text that is capitalized as-is in this case.

Ok, so this is the behavior of the underlying library but it is certainly NOT the behavior the user expects.

I know it now but others won't so I'd like to suggest adding a very simple README.md with one or two sentences explaining the current behavior. Adding a README would display the "About this extension" button in Raycast as well as add the info to the store page; that would ensure that users of your extension don't have wrong expectations or even open a bug, as I did... ;-)

**Comment by erics118** [comment]
Feel free to PR some more clarification to add to the README.

**Comment by RihardsVeters** [comment]
Yeah.. so this is kinda weird..

**Comment by ErikAbele** [comment]
You are all fine with numerous bug reports because people don't understand the behaviour but still nobody is able to add a simple sentence to the README? OMG... I'm so happy that I left open-source software 15 years ago...

**Comment by erics118** [comment]
@raycastbot reopen this issue
