### ISSUE TITLE
[Search Next.js Documentation] extension not working.

### ISSUE THREAD

**Issue by tr1s** [raycast/extensions#10598]
### Extension

https://www.raycast.com/PrasadChinwal/nextjs-docs

### Description

Anything I click is just met with this image:

![CleanShot 2024-02-05 at 15 23 14@2x](https://github.com/raycast/extensions/assets/19172250/7897f858-01d0-43ba-bef1-a4331d91d461)

This isn't only happening to me either. Ref:
https://raycastcommunity.slack.com/archives/C028DTXTW3Y/p1706817867624609

### Steps To Reproduce

1. install search next.js documentation from raycast store
2. use the extension to search up anything in the docs, click enter
3. then you're met with the "something went wrong" message

### Current Behaviour

you're met with the "something went wrong" message

### Expected Behaviour

clicking an item should show the proper documentation

**Comment by hevey** [comment]
I am seeing the same issue here. a copy of the log 

```
HttpError: Not Found

index.js:30:321671
async b3:index.js:32:4632
async I0:index.js:32:5380
```
