### ISSUE TITLE
[Apple Reminders] Can't sort by descending priority

### ISSUE THREAD

**Issue by cm3cm** [raycast/extensions#10603]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

You currently can sort the reminders by Priority ascending, but not by descending

### Who will benefit from this feature?

Everyone who uses apple reminders priority

**Comment by thomaslombart** [comment]
You can with the `Order By` action.

![CleanShot 2024-02-12 at 10 09 22@2x](https://github.com/raycast/extensions/assets/16003285/9a635a7e-6660-4b70-b0cc-edabe858c5cf)
