### ISSUE TITLE
[Day One] Add timestamp to the entry

### ISSUE THREAD

**Issue by mittuled** [raycast/extensions#10604]
### Extension

https://www.raycast.com/AntonNiklasson/day-one

### Description

Currently, when creating an entry for Day One from Raycast, only the date is passed to Day One. Going through the Day One CLI documentation, looks like adding timestamp should be fairly straightforward.

### Who will benefit from this feature?

This will help remove the need to keep the menubar item for Day One active for quick entries. The point of using Day One from Raycast is to use it as a micro-journal with multiple short entries in a day. Without the timestamp the sequence of these entries is not maintained and makes it difficult to use the feature.

**Comment by AntonNiklasson** [comment]
Thank you reporting this! It should definitely be possible. I'll take a look tonight.
