### ISSUE TITLE
Support Retina Displays

### ISSUE THREAD

**Issue by oasaleh** [raycast/extensions#10624]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

The taskbar icons are blurry due to being low-res. I was wondering if you can swap the PNG files for SVG ones so macOS will take care of scaling? 

Here's what it looks like right now.
<img width="50" alt="Screenshot 2024-02-06 at 6 58 08 PM" src="https://github.com/raycast/extensions/assets/56449814/66db4a11-9841-4530-b13e-0ababa33bffc">

vs. icons that can scale.
<img width="44" alt="Screenshot 2024-02-06 at 6 58 22 PM" src="https://github.com/raycast/extensions/assets/56449814/a8ee4db2-2da5-4b7b-9be6-6761994273d0">
<img width="34" alt="Screenshot 2024-02-06 at 6 59 28 PM" src="https://github.com/raycast/extensions/assets/56449814/f85a3d05-ff26-4550-a267-9febb7783238">

I found a couple of alternatives if you would like to use them. I think they're more informative and are easier to distinguish in different modes vs. the current ones, where the hot steam is the only discerning factor. 
This one for when *decaffeinated* https://thenounproject.com/icon/coffee-pot-47716/
And this one for when *caffeinated* https://thenounproject.com/icon/coffee-pot-47772/
There's also this one https://thenounproject.com/icon/coffee-pot-47717/

### Who will benefit from this feature?

I hope every one who uses a high resolution monitor or simply uses a MacBook :)

### Anything else?

I tried to look in the code where the images are being used but couldn't find it.

**Comment by pernielsentikaer** [comment]
Closing as fixed 🔥 Thanks again @oasaleh
