### ISSUE TITLE
[google-translate] Language does not equal country flag

### ISSUE THREAD

**Issue by misterioss** [raycast/extensions#10631]
### Extension

https://www.raycast.com/gebeto/translate

### Description

Flags are commonly recognized as expressions of national pride; however, using them to signify languages can be highly deceptive. Despite multiple countries sharing identical flags, the linguistic diversity within each nation can be extensive. Depending solely on flags for language representation may result in oversimplifications and misunderstandings, overlooking the intricate nature of global communication.

**Comment by gebeto** [comment]
Yeah, it makes sense

**Comment by gebeto** [comment]
It makes sense, but without flags UI is harder to use, so need to think about some good solution for this one, because showing the country code will also looks not so good. So maybe will be good to show whole language name. But need to check how it will work
