### ISSUE TITLE
[System Monitor] ... Mac/Battery Temperature 

### ISSUE THREAD

**Issue by shihabsalah** [raycast/extensions#10639]
### Extension

https://www.raycast.com/hossammourad/raycast-system-monitor

### Description

System Monitor shows great information about the Mac, but it would certainly be much more valuable if we could monitor the temperature without installing another application.
Just showing the Mac temperature, Fan Speed, and Battery temperature

### Who will benefit from this feature?

Any mac user who needs to monitor the temperature (developers, editors, etc...)

**Comment by lucasmezencio** [comment]
That's an interesting feature! I'll be looking into that!
