### ISSUE TITLE
Universal search

### ISSUE THREAD

**Issue by zenopopovici** [raycast/extensions#1063]
**Describe the feature and the current behavior/state.**
Raycast lacks an universal search like Alfred has. An universal search would trigger all extensions that have a search capability (apps, extensions, files, folders, ...) and display the results in an unified way.

Here's an example from Alfred:
<img width="706" alt="Alfred Example" src="https://user-images.githubusercontent.com/767998/157647247-c4126a7c-2658-4086-8d07-f78d6416e5ee.png">

**Will this change the current API? How?**
You currently have to setup a shortcut or alias to perform a specific search. Search results are per extension only.

**Who will benefit from this feature?**
This would help enormously in getting things done. It would benefit users and developers in terms of discoverability and functionality.

**Comment by mathieudutour** [comment]
I'm going to close this as it's about a core feature of the app and not the API. I'll pass on the feedback to the team.

**Comment by ViGeng** [comment]
> I'm going to close this as it's about a core feature of the app and not the API. I'll pass on the feedback to the team.

How is the progress ? We users and developpers realy want this !
Thank you!

**Comment by Gregoor** [comment]
This is the number one reason why I default to Spotlight or my browser where I can search for things without jumping through the select-provider hoop

**Comment by youtextme** [comment]
You said choose-provider-first is why you default to Spotlight/browser. That's still Raycast's common friction vs Alfred universal search.

Mitigations: aliases/hotkeys that jump straight into a command's search, and Recents for files you already touched. If that still feels like a hoop, stay on Spotlight for search and only use free Raycast for windows/Store. Pro won't invent universal search.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
