### ISSUE TITLE
[ChatGPT] ...Extension keeps showing "Error: Connection error"

### ISSUE THREAD

**Issue by NuelEdeh** [raycast/extensions#10638]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

I keep getting "Error: connection error" when I try to use the Askchat gpt command. 

### Steps To Reproduce

1. On my mac, I've added an API key with a pay-as-you-go plan.
2. When I try to ask a question to chatgpt, I get "error:connection error"

### Current Behaviour

![image](https://github.com/raycast/extensions/assets/60858975/72c0c60b-fda7-4498-a46d-6204694901ad)

### Expected Behaviour

Responses to answer my question

**Comment by bxb100** [comment]
Could you share your configurations?

**Comment by NuelEdeh** [comment]
Here are my configurations.
1. 
![image](https://github.com/raycast/extensions/assets/60858975/6346231b-a089-4b55-8289-446d5bfa69a9)
2. ![image](https://github.com/raycast/extensions/assets/60858975/9c89927e-32ac-4372-a26d-213aad20d1de)
3. 
![image](https://github.com/raycast/extensions/assets/60858975/22d71f0d-ca25-4b78-896b-653dacd4a4a2)

**Comment by NuelEdeh** [comment]
![image](https://github.com/raycast/extensions/assets/60858975/8171b8b7-a096-40f7-a648-411a65eb0d4b)

**Comment by bxb100** [comment]
copy that, I'll dig that

**Comment by NuelEdeh** [comment]
@bxb100 I fixed the issue. I changed the certificate settings from "Default" to "Keychain" on my Raycast settings page and it worked. Thank you for responding to this.

![image](https://github.com/raycast/extensions/assets/60858975/e712aab5-b0e1-4431-8ee1-3976c6939654)
