### ISSUE TITLE
File Actions

### ISSUE THREAD

**Issue by zenopopovici** [raycast/extensions#1064]
**Describe the feature and the current behavior/state.**
What Raycast is missing to be complete are file actions. Afred aces this. Currently there is no extension or core functionality providing this capability. You need to be able to act on items and send them to another app, or action.

With Alfred you can move, copy files to recent locations or even search for a new location by triggering a shortcut:

<img width="700" alt="Alfred actions" src="https://user-images.githubusercontent.com/767998/157649097-4ef813b8-5156-4065-bc9f-9b17e9752bff.png">

<img width="700" alt="Alfred actions search" src="https://user-images.githubusercontent.com/767998/157648773-62120782-edfa-422d-8313-a27e168a302d.png">

**Will this change the current API? How?**
The current API has not such capabilities.

**Who will benefit from this feature?**
Power users and developers.

**Comment by helen** [comment]
Wanted to voice my support for this as an Alfred user testing out a switch 🙂  A very common scenario for me is moving items out of Downloads shortly after they get dumped in there, so I: search for a file by name, open the action palette, choose "Move to...", then search for the directory I want and action it.

**Comment by koinzhang** [comment]
Hi @zenopopovici @helen 

I have created a Common Directory extension that has been submitted to [PR](https://github.com/raycast/extensions/pull/1241) and is under review
The extension has two main features

1. Quick access to common folder directories.

1. Quickly Send files to the common directory, open directory or folder chosen manually

This is the best I could do with the existing API, although it's still inconvenient compared to Alfred's search mobile, but it's an effort.
Of course there are advantages to this extension (it can move or copy files/folders in bulk)

https://user-images.githubusercontent.com/36128970/162682823-8fa9bb32-4cd5-4f52-bf1a-827bb6fc1bb3.mp4

**Comment by zenopopovici** [comment]
@koinzhang Very very cool, I'll install it right away, this is actually a huge step forward into moving 100% on RayCast from Alfred.

**Comment by youtextme** [comment]
You filed that Raycast needs Alfred-class file actions to be complete. That gap is still the reason dual-setup is rational: Alfred for file move/copy/universal actions; free Raycast for Store and windows.

Pro does not close file actions. Don't pay hoping it will. Switch fully only when your file-action frequency drops — until then dual hotkeys are the product.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
