### ISSUE TITLE
[Browser Bookmarks] Wrong bookmark is selected on Chrome

### ISSUE THREAD

**Issue by Eldrick19** [raycast/extensions#10642]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

When using Google Chrome as the browser, the bookmarks extensions selects the wrong bookmark. This happens inconsistently, and it seems to select bookmarks that are close in search results. You have to try multiple times to get the desire bookmark.

Example below:
In this case I'm trying to open my "Calendly" bookmark, but it opens my "African Literature" bookmark instead (after a bit of delay..)

![Image](https://github.com/raycast/extensions/assets/26189114/931f9e06-b23b-4c62-bd2e-7a350e368983)

### Steps To Reproduce

1. Have 152 bookmarks or more in Google Chrome
2. Install the bookmark browser extension (latest version, updated January 31)
3. Search for bookmark that has related searches
4. Select a bookmark that is not top of the list

### Current Behaviour

When performing the steps above, the wrong bookmark is selected

### Expected Behaviour

The correct bookmark is selected

**Comment by thomaslombart** [comment]
Thanks for reporting this bug. I'll check with the team to see if there's something we can do about it.

**Comment by thomaslombart** [comment]
So, I was able to reproduce the bug by double-clicking *really fast* on another list item than the first one, but it needs to be done in like, half of a second for me. Did you notice a pattern for when it happens? Does it happen when your Mac happens to be slow?

**Comment by Eldrick19** [comment]
Hi @thomaslombart - I did notice a few patterns:
- It happens more often when it's not the first item
- It happens even if I wait a couple of seconds (~10-15 seconds)
- It seems to always select other bookmarks within the same search result
- When clicking, the opening of bookmarks are always slightly delayed

My Mac isn't particularly slow no. I've also tried uninstalling and reinstalling the extension.

**Comment by thomaslombart** [comment]
It's caused by an internal bug. The next Raycast release should fix it! 🙂

**Comment by Eldrick19** [comment]
Thanks @thomaslombart ! I'll keep an eye out and close this issue when released. Do you have details on when the next release will be?
