### ISSUE TITLE
[Google Tasks] ... Is there anyway to add a Command allowing Raycast to create a Google Task?

### ISSUE THREAD

**Issue by BritAngeles** [raycast/extensions#10650]
### Extension

https://www.raycast.com/elliotdes/google-tasks

### Description

Would tell my grand children tales of your gallantry, if you could add a Raycast Command to create a Google Task please.

### Who will benefit from this feature?

Everyone that uses Google Tasks and Raycast.

Presumably Google too, as they get more of our data, but IDK how the internet and economy works 🤷🏻

### Anything else?

Open to discussions of naming my first born child after you?

(Subject to approval from my as-yet-fictitious, future-mother of such child.)

Also, if anyone could make a Raycast extension for Google Keep, My second fictional child's name is up for grabs

**Comment by elliotdes** [comment]
Hi @BritAngeles, I am a bit unsure about what you want this feature to do? You can already make google tasks from raycast by using this extension.

Let me know, I will be happy to take a look. 😄

**Comment by ruaanvds** [comment]
@elliotdes, thanks for creating this. 

Came across this thread today looking for a similar answer. 

I think it would unlock of value in this extension if there was an option to "Copy Deeplink" on the both the List View and the Create Task view. 

![image](https://github.com/raycast/extensions/assets/6225983/8872de48-31c4-4850-aad3-2ad6e6f6f3dc)

![image](https://github.com/raycast/extensions/assets/6225983/3353fd06-2d4e-4a17-adb4-15ece1c5123b)

Happy to create a separate issue for this if this isn't what @BritAngeles meant by the issue.
