### ISSUE TITLE
[GIF Search] Copying Error

### ISSUE THREAD

**Issue by alsoknownaskaz** [raycast/extensions#10652]
### Extension

https://www.raycast.com/josephschmitt/gif-search

### Description

Receiving the below error message:
Failed to copy GIF: "Command failed with exit code 1: osascript
21:175: execution error: Not authorized to send Apple events to Finder. (-1743)"

### Steps To Reproduce

1. Call on the extension
2. Locate a gif
3. Activate to copy
4. Receive error

Attempted to uninstall and reinstall the extension, issue persists.

**Comment by j3lte** [comment]
@raycastbot rename this issue to "[GIF Search] Copying Error"

**Comment by j3lte** [comment]
@alsoknownaskaz I can't seem to reproduce the issue. It has to do with [this line of code](https://github.com/raycast/extensions/blob/0adffea14a7b17de24fc477672c51fc180b4e21d/extensions/gif-search/src/lib/copyFileToClipboard.ts#L33), which runs an Applescript to copy something to Finder.

In my opinion this has nothing to do with the extension, but has to do with permissions on your system.

Can you check if you have enable Automation access for Raycast? (System Preferences → Security & Privacy → Automation → Raycast should be checked)

**Comment by alsoknownaskaz** [comment]
@j3lte - so sorry, you are correct. I suspected it had to do with permissions access and the only one I didn't check was automation. Turned on and all works correctly. Thank you for the reply.
