### ISSUE TITLE
[Messages] No such file or directory error

### ISSUE THREAD

**Issue by jerudnik** [raycast/extensions#10651]
### Extension

https://raycast.com/thomaslombart/messages

#### Error:
```
Error: ENOENT: no such file or directory, chmod '/Users/jrudnik/.config/raycast/extensions/f872e5ef-af26-4086-8b11-261e5c6f6c93/assets/compiled_raycast_swift/contacts'
```

### Steps To Reproduce

1. Open raycast
2. Open send messages command
3. Receive error

### Current Behaviour

Not fetching contacts.

### Expected Behaviour

Expected to get contacts.

**Comment by thomaslombart** [comment]
Are you consistently getting the same error? What if you uninstall and reinstall the extension?

**Comment by jerudnik** [comment]
Ooops, reinstalled and it worked just fine.
