### ISSUE TITLE
[Unicode Symbols Search] Search by symbol code

### ISSUE THREAD

**Issue by asportnoy** [raycast/extensions#10654]
### Extension

https://www.raycast.com/mmazzarolo/unicode-symbols

### Description

Sometimes I have a unicode character code in my clipboard for something, for example `\u200B`. It would be great if I could use this extension to look up the character by that code, rather than having to google or look it up some other way. It seems like you already have the codes associated with each character so I'd imagine this wouldn't be too hard to implement.

### Who will benefit from this feature?

Mostly developers, but anyone who works with unicode codes.

### Anything else?

This should be able to handle various different formats of codes, such as, `200B`, `\u200B`, `U+200B`, `&#8203;`, etc.

**Comment by j3lte** [comment]
@raycastbot close this issue
