### ISSUE TITLE
[Night Light] ...

### ISSUE THREAD

**Issue by nukesean** [raycast/extensions#10669]
### Extension

https://www.raycast.com/devmoath/night-light

### Description

It'd be nice if the extension closed/dismissed Raycast after using one of the commands. It's very strange that Raycast stays open, forcing me to close it manually.

**Comment by erics118** [comment]
There is a setting to do this:

![CleanShot 2024-02-21 at 23 29 45](https://github.com/raycast/extensions/assets/52634785/bc37b755-1b37-457b-bf3f-dd5fc98ba670)
