### ISSUE TITLE
[Spotify] Starting playback sometimes opens the spotify app window

### ISSUE THREAD

**Issue by mikestopcontinues** [raycast/extensions#10670]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Sometimes—I don't know exactly why—when I start a new music source from "Your Library" or "Search", the Spotify window will open. This behavior only started recently. I wish I could say what changed.

### Steps To Reproduce

1. "Your Library"
2. Play anything.
3. Sometimes, the Spotify window will open.

### Current Behaviour

The Spotify window opens sometimes.

### Expected Behaviour

I would like it to never open the Spotify window.

**Comment by mikestopcontinues** [comment]
This still happens.

**Comment by mikestopcontinues** [comment]
Still a problem.

**Comment by thomaslombart** [comment]
Initially, every Spotify action was made through the API but for rate-limiting reasons, we had to switch to AppleScript for some of these actions. AppleScript requires Spotify to be opened, so if you're playing a song for example, and Spotify isn't opened, it'll open it. However, if Spotify is running in the background, it shouldn't bring the Spotify window to front. I'm not sure we can do much more here unfortunately 😕
