### ISSUE TITLE
[Apple Reminders] Entires in QuickAdd are behaving oddly

### ISSUE THREAD

**Issue by 1activegeek** [raycast/extensions#10677]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

I recently enabled the QuickAdd function for reminders. In doing so I was loving the ability to skip the need for picking a list, or requiring any other data to just get thoughts down into reminders into my Inbox list (set as the default). However after using this for a bit I started noticing extremely odd behaviors - sadly I don't have a perfect example to reproduce, but will attempt to try and create some that do the same thing.
Some of the unexpected behaviors:
- Confirmation dialog actually saying placed in the default list, but don't end up in the default (and no the name of list and special characters were NOT in use)
- Confirmation dialog actually indicating being placed in a different list (and no the name of list and special characters were NOT in use)
- Items receiving a priority setting that was not indicated in the creation of the reminder
- Items receiving due dates that were not indicated in the creation of the reminder
- Items having their content stripped off (i.e. a reminder that was 10 words long, appears with only 4 of those words on it)

### Steps To Reproduce

- Open QuickAdd prompt
- Use one of the examples below which results in something different:
```
- This is an example a really long remidner that I want to share with Raycast devs
  - Resulted in a reminder with a Medium priority
- Adjust light reminder to indicate which list is still on hass
  - Confirmation dialog said the task was added to my 'hass' list, there is no such list in reminders, it was added to a list named Traceable, and the reminder was trimmed down to "Adjust light reminder"
- Create new automation for recognizing the Bathroom Overhead has been in purple state
  - It created a new item in the inbox but has chopped the text down to "Create new automation"
- Create apple shortcuts for templates in Notes app
  - Created a reminder in the default list, but again set the priority to Medium
```
These are just the examples I could come up with for now. 

### Current Behaviour

I'm getting all sorts of variety of outputs that don't make sense and/or are not documented. Often times I'm losing takes that I want to show up in my inbox, but I randomly find them later somewhere they're not supposed to be. I may have to resort back to using the full input style for now until this is fixed.

### Expected Behaviour

Expect that inputs that are added this way, should be just the same as if added via the standard Create New Reminder option. If quick add is trying to process alternative language or something else to enable more advanced entry options - this needs more detail to understand how it works so that it doesn't have these odd behaviors. Alternatively, enforce the use of special characters like so many other systems to clearly indicate when dates, priorities, lists, etc are being added to the entry.

**Comment by 1activegeek** [comment]
I'd like to ask that this be re-opened and looked into further. Not sure there is a reason for GPT parsing, since I'm passing my own small reminders to the reminders app. Item 1 and 4 seem to have been resolved, but item 2 still goes to a list that doesn't exist and cuts off the end still. Item 3 also just got cutoff upon entry. AFAIK I am using the latest version of the plugin.

**Comment by thomaslombart** [comment]
I tried item 2 and 3 and they work on my end… Maybe the extension isn't updated. To make sure it is, please run `Check for Extension Updates`.

**Comment by 1activegeek** [comment]
Just tried again - validated Raycast is fully up to date, validated extensions are up to date, but still issue persists. I also noticed this time trying item 2, it had a different result than previous - instead of adding to the "hass" list ... it tried to add it to the "is still on hass" list 😆 

That said - is there some kind of log or something I can share to help identify what could be going wrong? 

Also I noticed it said this was using GPT4, but does that require me to subscribe to using the GPT4 model in Raycast? I do not pay for this upgrade.

**Comment by thomaslombart** [comment]
Oh that must be that! If you're not using GPT-4, it'll fallback to GPT-3.5, which is your case 😬

Unfortunately, I don't have any other workarounds for that. I've tried to improve the prompt and this affected some results. Only using a "smarter" model led to better results.

**Comment by 1activegeek** [comment]
So was the design of quick-add to be doing things like interpretation of priority, list, date, etc? I thought it was intended to be just a quick and easy option to enter a task hit enter, and go. At least that's how I was using it. Until I noticed these weird interpretations happening. If so, I'd suggest adding some detail to the feature in the store so people are aware. And to let them know that it's relying on a feature that may not be included if you're not paying for the AI upgrade. 

Even if using something like GPT4, isn't it possible it can still misinterpret information, resulting in broken workflows for folks? If an important task doesn't show up in the inbox like planned, that could be pretty detrimental to workflow. 

Perhaps for now my workaround will be use Apple shortcuts instead. Just disappointing to not keep it right in line with a keyboard shortcut in raycast.

**Comment by thomaslombart** [comment]
Yes, it was designed that way from the start. I see two improvements to that:

- If the user doesn't have AI enabled (so no Raycast Pro subscriptions), simply add a reminder in the default list with the raw text
- Or rename the `Quick Add Reminder` command to `Quick Add Reminder with AI`

> Even if using something like GPT4, isn't it possible it can still misinterpret information, resulting in broken workflows for folks? 

It is possible, and that's why the prompt is quite detailed with examples. However, the AI can make mistakes sometimes. That's also why we show a HUD with the task description in case the user quickly wants to verify that the AI got it right.

**Comment by 1activegeek** [comment]
@thomaslombart thanks for the updates. Makes sense. It seems like perhaps my need can just be achieved using the primary input - I can just ignore the extra stuff and use CMD+Shift+Enter to make the prompt disappear. 

My inputs on the adjustments - I would say at the minimum maybe just an expansion in the Raycast Store descriptions to highlight that the QuickAdd is using AI and/or what it should/n't understand when entering inputs. That would have deterred me 😄 

If it's not much work I think the first behavior you describe would be good - but should also include some indication that AI is in use if you DO have GPT4. If I had the upgrade, I might appreciate the added intelligence myself 😉

**Comment by thomaslombart** [comment]
https://github.com/raycast/extensions/pull/10916
