### ISSUE TITLE
[Spotify Player] Support for Spotify Web

### ISSUE THREAD

**Issue by kitkat-kitkat** [raycast/extensions#10683]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Currently, you can open songs/playlists/albums in the browser using Cmd+O, and that's about the extent of Spotify Web support. It'd be great if users could configure the extension to automatically open songs in the web instead of the Spotify app, and it'd be even better if media controls (shuffle, play, pause, skip) worked in the web too!

### Who will benefit from this feature?

Some people (including myself) prefer to use Spotify Web over the dedicated app for reasons such as easy ad-blocking, URL sharing, and just for the sake of staying lightweight. Supporting Spotify Web would make this extension much more useful for people like us!

### Anything else?

An alternative would be supporting the free-tier of the dedicated Spotify app (currently, the extension only works if you have premium), but I assume there are technical limitations stopping you from doing so.

**Comment by erics118** [comment]
Media controls should work, as it uses the Spotify API.
