### ISSUE TITLE
Respond error

### ISSUE THREAD

**Issue by Takami-Marsh** [raycast/extensions#10688]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

TypeError: Cannot read properties of undefined (reading 'messages')

mh:ChatView.tsx:43:80

---
40:  * @returns {JSX.Element} Raycast Chat View.
41:  */
42: export function ChatView(): JSX.Element {
43:   const { data: OllamaVersion, isLoading: IsLoadingOllamaVersion } = usePromise(OllamaApiVersion, [], {
44:     onError: HandleError,
45:   });
46:   const {
---

    at hh
Dr:index.js:11:2490
    at ray-navigation-stack

### Steps To Reproduce

General usage

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue
