### ISSUE TITLE
[Copy Path] ... Add exceptions

### ISSUE THREAD

**Issue by AISLVE** [raycast/extensions#10706]
### Extension

https://www.raycast.com/koinzhang/copy-path

### Description

I would love to be able to have set exception of forbidding copying from some apps I want

**Comment by koinzhang** [comment]
Hi @AISLVE. Currently this extension will only copy content from the Finder and Browser, when the foremost app is another app, it will just pop up a Toast alert and won't copy anything.
If you mean you want to disable the display of the Toast when the foremost app is another app, I'll provide a setting to do so.

**Comment by AISLVE** [comment]
so i use arc and when i try to copy the url of little arc it doesn't do so rather it copies other window's url

**Comment by koinzhang** [comment]
For Arc Browser, it is true that you can't get the current window URL if you are currently opening the window with Peek Links, this is because Peek Links is an Arc-exclusive capability.

**Comment by AISLVE** [comment]
yeah that's why i am asking for the feature to exclude certain apps since arc already has the ability to copy url with cmd + shift + c

**Comment by koinzhang** [comment]
Excluding certain apps may not solve your problem
I understand what you mean is to have the extension provide an ability to exclude Arc, then add a shortcut Shift+CMD+C for the command, and then use Shift+CMD+C in Arc to copy to the URL.
This cannot be achieved because if you set the shortcut key of Shift+CMD+C for the command, even if I provide the exclusion function, the shortcut key will be occupied in Arc and the ability to copy the URL that comes with Arc cannot be called.

**Comment by AISLVE** [comment]
no it can be achieved so i use paletro whose shortcut i have set as ⌘ + shift + C and have disabled it for vscode so i can use it's native command palette(⌘ + shift + P) and that works like a charm

**Comment by koinzhang** [comment]
The problem we are encountering now is that the URL of the Peek window of the Arc browser cannot be obtained through AppleScript, so Copy Path cannot obtain the URL of the Peek window, but it can be used normally for other types of Tab pages.

**Comment by AISLVE** [comment]
> Excluding certain apps may not solve your problem I understand what you mean is to have the extension provide an ability to exclude Arc, then add a shortcut Shift+CMD+C for the command, and then use Shift+CMD+C in Arc to copy to the URL. This cannot be achieved because if you set the shortcut key of Shift+CMD+C for the command, even if I provide the exclusion function, the shortcut key will be occupied in Arc and the ability to copy the URL that comes with Arc cannot be called.

yeah, but have you tried excluding, it doesn't harm to try it, maybe they will work

**Comment by AISLVE** [comment]
oh i see i will just have to change the shortcut then thanks for the help by the way. i am closing the issue now if it's ok with you

**Comment by koinzhang** [comment]
Sorry, I don't have a way to improve this at the moment. Copy Path is a command I use every day, and I'm constantly improving it. Today I just submitted a PR #10984, which is about some improvements in copying URLs: Now you can select which part of the URL to copy

**Comment by AISLVE** [comment]
yeah mate i understand and really love it that's why i am still using it it's awesome tbh that raycast has such a wide number of plugins to use and it's thanks to devs like you, i have changed the shortcut to ⌘ + ⌥ + SHIFT + C
