### ISSUE TITLE
GitLab My Open Issues gets error on details and images don't load

### ISSUE THREAD

**Issue by MikeSuiter** [raycast/extensions#1070]
# Extension – [gitlab](https://github.com/raycast/extensions/tree/main/extensions/gitlab)

Author: @tonka3000 

## Description

I do a My Open Issues and any of them I click on gets a Could not get details error for all of my issues. For any issues that have images, it shows Loading... but they never load. Both issues are shown in the screenshot below:

<img width="767" alt="Screen Shot 2022-03-10 at 10 10 21 AM" src="https://user-images.githubusercontent.com/5289509/157706509-73c7f45a-c7fd-4717-9fc3-42806fff7e95.png">

## Steps To Reproduce

1. My Open Issues
2. Show Details

## The current behavior
Gets error fetching details and images don't load

## The expected behavior
Able to get details and loads images

### Raycast version

Version: 1.30.1

**Comment by tonka3000** [comment]
Hi @MikeSuiter ,

Do you use gitlab.com or a private instance?
Is your project behind an authentication or is it public?
Can you try the same procedure on a public project on your instance.

**Comment by tonka3000** [comment]
Hi @MikeSuiter ,

I've found the problem. Please can you validate that your not loading urls starting with `/` like `/uploads`. The easiest way is be editing the description to see directly the markdown text.

If it starts with `/` it will be fixed with #949

**Comment by MikeSuiter** [comment]
Hi @tonka3000,

This is a private repo and I created an access token for Raycast.

Here is the markdown for images.

```
![Screen_Shot_2022-02-09_at_5.45.42_PM](/uploads/7676c9128229733f4096af1a1bcebf1a/Screen_Shot_2022-02-09_at_5.45.42_PM.png)
```

**Comment by tonka3000** [comment]
Great, #949 should fix that
