### ISSUE TITLE
[SF Symbols Search] Add AI capability to the search

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#10715]
### Extension

https://www.raycast.com/peteschaffner/sf-symbols-search

### Description

It would be great if Pro users could have the same improvement in this extension as we've had in Emoji search, which allows for the wider use of natural language:

![Screenshot 2024-02-12 at 03 55 50](https://github.com/raycast/extensions/assets/11052366/115ce2a5-b1b7-48b3-9f37-55cc931f9cce)

### Who will benefit from this feature?

All Raycast Pro users.

**Comment by peteschaffner** [comment]
Unfortunately I've pretty much abandoned this extension :( At the time there were some huge hurdles that made it difficult to keep up-to-date with SF Symbol changes, as well as deploy those changes (basically all the symbols had to be rasterized and bundled inside the extension, making it HUGE).

I too want this extension though, so I'll try to give it some thought and see if things have changed in a sense that I could represent the grid items with a unique font. If something like that is doable then improvements like you've described would be next on the list of things to do.

**Comment by xilopaint** [comment]
> I too want this extension though, so I'll try to give it some thought and see if things have changed in a sense that I could represent the grid items with a unique font. If something like that is doable then improvements like you've described would be next on the list of things to do.

Let me know if you update the extension, please!
