### ISSUE TITLE
[Todoist] Default due date for tasks

### ISSUE THREAD

**Issue by g9h** [raycast/extensions#10711]
### Extension

https://www.raycast.com/doist/todoist

### Description

Please consider adding a default due date to tasks created with this extension. Yes, I can and do add today to all of the tasks I create (and I largely ONLY use this extension to create tasks because it is so awesome) but having default vaules like due date and even priority might help many people's flows. Thank you for considering!!

### Who will benefit from this feature?

Anyone who forgets to check their "no due date" queues in Todoist.

**Comment by g9h** [comment]
i think i would like to try to work on it. any guidance you can provide is great, and any feedback on the code will be necessary and appreciated!!

**Comment by thomaslombart** [comment]
First, here's our guide about contributing to extensions: [Contribute to an extension](https://developers.raycast.com/basics/contribute-to-an-extension)

This could be done by using both quicklinks and deeplinks. You can find an example on the `Messages` extension: [send-message.tsx](https://github.com/raycast/extensions/blob/5566eaffa6211ab5d0d5f59daabab48c8dceb960/extensions/messages/src/send-message.tsx)
