### ISSUE TITLE
Caffeinate For isn't accepting partial inputs

### ISSUE THREAD

**Issue by lewiuberg** [raycast/extensions#10729]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

If minutes and seconds are left blank in `Caffeinate For` I think my Mac is getting decaf ;)

I have only experience with C# and python so I dare not a PR at this point :) 

### Steps To Reproduce

macOS Somona 14.0. no configs made.

### Current Behaviour

No caffeination is enabled  when entering 1h ""m ""s

### Expected Behaviour

caffeination for 1h

**Comment by pernielsentikaer** [comment]
I can't reproduce this scenario since everything is already calculated into seconds, so it shouldn't be happening.

Does it happen all the time for you?

**Comment by lewiuberg** [comment]
Hi!

Sorry! Im Working via Azure DevOps these days, so I didn't see this. 

I will test a bit to day and get back to you.
