### ISSUE TITLE
[Ratio Calculator] Calculate greatest common divisor based on width/height

### ISSUE THREAD

**Issue by houmark** [raycast/extensions#10730]
### Extension

https://www.raycast.com/justiniscoding/ratio-calculator

### Description

It would be great if you could input a width and a height and get the greatest common divider being the ratio.

For example, inputting something like: `1920px/1080px` (or maybe even just `1920/1080`) would output `16/9`.

### Who will benefit from this feature?

I may not be the only one trying to get a proper ratio based on some image size.

### Anything else?

Nope, hope you're interested in making it happen...

**Comment by Justiniscoding** [comment]
> ### Extension
> https://www.raycast.com/justiniscoding/ratio-calculator
> 
> ### Description
> It would be great if you could input a width and a height and get the greatest common divider being the ratio.
> 
> For example, inputting something like: `1920px/1080px` (or maybe even just `1920/1080`) would output `16/9`.
> 
> ### Who will benefit from this feature?
> I may not be the only one trying to get a proper ratio based on some image size.
> 
> ### Anything else?
> Nope, hope you're interested in making it happen...

Sure, I'll start working on it now!

**Comment by Justiniscoding** [comment]
Done, pull request here:
https://github.com/raycast/extensions/pull/10748
