### ISSUE TITLE
[iMessage 2FA] Any way to delete the 2FA message automatically as soon as it's been used?

### ISSUE THREAD

**Issue by xhi-nico** [raycast/extensions#10741]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

It would be ideal if the extension could also delete the 2FA message from Messages as soon as it's used. Not sure if this is even possible.

### Who will benefit from this feature?

Everyone that uses this extension

**Comment by alwinsamson** [comment]
I'm not sure if this works in macOS, but in iOS 17.3, Settings > Passwords > Password Options > Clean Up Automatically (VERIFICATION CODES). Automatically deletes 2FA codes.

**Comment by xhi-nico** [comment]
> I'm not sure if this works in macOS, but in iOS 17.3, Settings > Passwords > Password Options > Clean Up Automatically (VERIFICATION CODES). Automatically deletes 2FA codes.

this works when using Safari and the built-in feature, not when using this extension through RayCast.

**Comment by navtoj** [comment]
Duplicate of #9838

**Comment by navtoj** [comment]
@raycastbot close this issue
