### ISSUE TITLE
Google Chrome Extension is no longer detecting newer versions of Chrome

### ISSUE THREAD

**Issue by cliffordfajardo** [raycast/extensions#10744]
### Extension

https://www.raycast.com/Codely/google-chrome

## Details
Computer:  MacOS 14..3.1 (Sonoma)
Chrome version: Version 121.0.6167.139 

### Steps To Reproduce

Attempt to search for (1) history using the Google Chrome Extension

### Current Behaviour

Commands fails and tells user that Google Chrome is not on their system

<img width="1429" alt="image" src="https://github.com/raycast/extensions/assets/6743796/7b742ed5-b477-493d-bf98-fd1f7165ff62">

### Expected Behaviour

Command should work and not error by telling user that they dont have Google Chrome installed if it is installed on their system

**Comment by nagauta** [comment]
Hi!, it maight be same issue with #7900 i reported.
I'm trying to slove above.

**Comment by nagauta** [comment]
@cliffordfajardo 
if you try the steps below, can you search history?
* New Tab
* Search History

**Comment by pyxelr** [comment]
@cliffordfajardo: Was it resolved for you? I have the same problem.

**Comment by lessonli** [comment]
> Hi!, it might be same issue with [#7900](https://github.com/raycast/extensions/issues/7900) I reported. I'm trying to solve above.

same
