### ISSUE TITLE
[Perplexity API] Feature request to have an AI chat conversation

### ISSUE THREAD

**Issue by rochakagrawal** [raycast/extensions#10759]
### Extension

https://www.raycast.com/ilian/perplexity-api

### Description

Would love to have the feature to have a **full AI chat conversation** with follow up requests to responses. Similar to how this extension works with Chatgpt (https://www.raycast.com/abielzulio/chatgpt) Or gemini (https://www.raycast.com/EvanZhouDev/raycast-gemini)

### Who will benefit from this feature?

Users to be able to have back and forth chat conversation along with history

**Comment by maximilianzuern** [comment]
Chat conversation will definitely happen in the future.
However, I cannot provide a specific date.

**Comment by renehuber** [comment]
It would be great to merge Perplexity API with the ChatGPT extension, as the ChatGPT extension allready allows to define an alternative endpoint and the Perplexity API is OpenAI compatible.

**Comment by rochakagrawal** [comment]
Good point. How do you that ? How can we use perp API with chatgpt extensionSent from my  iphone On 5 Apr 2024, at 2:59 PM, renehuber ***@***.***> wrote:﻿
It would be great to merge Perplexity API with the ChatGPT extension, as the ChatGPT extension allready allows to define an alternative endpoint and the Perplexity API is OpenAI compatible.

**Comment by maximilianzuern** [comment]
@raycastbot reopen this issue

**Comment by maximilianzuern** [comment]
@raycastbot close this issue
