### ISSUE TITLE
[Auto Quit App] Quit App doesn't close the app if no more windows exist

### ISSUE THREAD

**Issue by alexandertsukanov** [raycast/extensions#10757]
### Extension

https://www.raycast.com/koinzhang/auto-quit-app

### Description

I've added the apps I want to close to the "Quit apps section." I've waited for the duration I set in the settings, but nothing has happened.

### Steps To Reproduce

I've added the apps I want to close to the "Quit apps section." I've waited for the duration I set in the settings, but nothing has happened.

### Current Behaviour

Apps to be quit.

### Expected Behaviour

Apps to don't quit.

**Comment by koinzhang** [comment]
Hi @alexandertsukanov. If you want to quit the app automatically, you have to get the Auto Quit APP menu bar command activated, you have to run it at least once, or activate it manually in the settings.
In the image below, the top is in the inactive state and the bottom is in the active state.
Please make sure it's active.

<img width="751" alt="image" src="https://github.com/raycast/extensions/assets/36128970/18ddbf68-f07e-4e4a-b49f-497a9d87d7ea">

<img width="741" alt="image" src="https://github.com/raycast/extensions/assets/36128970/07dda0ce-2bdb-4054-ac1d-4ab181968efd">

**Comment by polaris-han** [comment]
I got same question.
![CleanShot 2024-02-23 at 16 08 58@2x](https://github.com/raycast/extensions/assets/35481705/47e8c0fe-f587-4774-8537-949a6208eba5)
![CleanShot 2024-02-23 at 14 56 08@2x](https://github.com/raycast/extensions/assets/35481705/6e193d8e-737c-4633-a60e-12cff295e2ca)
After I upgraded the system, the extension didn't work.

**Comment by alexandertsukanov** [comment]
> Hi @alexandertsukanov. If you want to quit the app automatically, you have to get the Auto Quit APP menu bar command activated, you have to run it at least once, or activate it manually in the settings. In the image below, the top is in the inactive state and the bottom is in the active state. Please make sure it's active.
> 
> <img alt="image" width="751" src="https://private-user-images.githubusercontent.com/36128970/305690812-18ddbf68-f07e-4e4a-b49f-497a9d87d7ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzkyMDIsIm5iZiI6MTcwODY3ODkwMiwicGF0aCI6Ii8zNjEyODk3MC8zMDU2OTA4MTItMThkZGJmNjgtZjA3ZS00ZTRhLWI0OWYtNDk3YTlkODdkN2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA5MDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZWFmYWJhZTkyMjgwM2QzYzg5NWRkNjJjMWUyNjQ0OGY0ODBjZjkzNmJjOWFlMDQwNGM2MDYyNzE3NmM1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UlBQ6cznMddwoxAnhV7g4BbnvTGuNWLdghkx68y46Pk"> <img alt="image" width="741" src="https://private-user-images.githubusercontent.com/36128970/305690778-07dda0ce-2bdb-4054-ac1d-4ab181968efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzkyMDIsIm5iZiI6MTcwODY3ODkwMiwicGF0aCI6Ii8zNjEyODk3MC8zMDU2OTA3NzgtMDdkZGEwY2UtMmJkYi00MDU0LWFjMWQtNGFiMTgxOTY4ZWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA5MDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMzE5MDgzYjhjNWYzZDVhOTQzZDEyMmVhYzU5YTAwMzg0ZDE4NGI4ZTk0NzFlNWM0MzZiNGI3MjgwMjk5Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.StEDOYmmKO2U2rRLenrY5FkeLaQY542F5UlM6Ef4TkM">

This MinuBar item is enabled, so I think it's not the root cause.

**Comment by alexandertsukanov** [comment]
CC: @koinzhang
