### ISSUE TITLE
[Perplexity] Copilot setting/argument no longer affects the search

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#10752]
### Extension

https://www.raycast.com/third774/perplexity

### Description

Self-explanatory title. I believe this stopped working a few days ago.

### Steps To Reproduce

Run `Ask Perplexity` command with Copilot activated.

### Current Behaviour

The search is carried out without Copilot.

### Expected Behaviour

The search is carried out using Copilot.

**Comment by third774** [comment]
Yeah, I reported this to the Perplexity team the other day, so it's on their radar. Unfortunately we just have to wait for them to fix it.

![CleanShot 2024-02-14 at 01 04 38@2x](https://github.com/raycast/extensions/assets/8732191/bade7a4f-3cba-436f-af5d-b1350e6aadb3)

**Comment by xilopaint** [comment]
I'm closing this as the issue has been fixed on the Perplexity side.
