### ISSUE TITLE
[Oura] Once the API key is set, the placeholder "Oura" values should be replaced

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#10765]
### Extension

https://www.raycast.com/Rob/oura

### Description

After you install the extension and add your auth token, the commands seem to have placeholder values which are all `Oura`:

![2024-02-14 (12 07 05) CleanShot](https://github.com/raycast/extensions/assets/22610/7734537d-30f6-414f-916e-cbdb5789d9af)

It would be a nice touch if these values were automatically fetched once the auth token is added.

### Who will benefit from this feature?

Anyone who uses the Oura extension.

**Comment by RobErskine** [comment]
@chrismessina thanks for flagging this. I'm not totally sure how to trigger updates on the commands once a `preference` value has been changed. I don't see a callback or hook or anything onChange to trigger an update on the subtitle of the commands [in the docs](https://developers.raycast.com/information/manifest#preference-properties).

[I've asked in the official Raycast Slack #extensions channel](https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1708207814640509) what the best way to approach this would be if you want to follow along!

For now, triggering each of those commands should update the subtitle. If you don't see that happening lemme know.
