### ISSUE TITLE
[Bitwarden Vault] Delete item from vault

### ISSUE THREAD

**Issue by RihardsVeters** [raycast/extensions#10769]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Why there's missing action feature to delete item from the vault when I'm using search vault command?

### Who will benefit from this feature?

Everyone who uses this extension to browse all saved login items and want to delete items that are not used anymore.

**Comment by jomifepe** [comment]
Hey, thanks for the suggestion. Until now the extension was read-only (by choice), meaning there are no management operations (e.g. create, remove, etc). The first management operation was added recently, with the `Create Folder` command, so there might be some management functionalities coming in the future. As always, feel free to contribute 🙏
