### ISSUE TITLE
[Color Picker] Naming Colors

### ISSUE THREAD

**Issue by lennartuecker** [raycast/extensions#10774]
### Extension

https://www.raycast.com/thomas/color-picker

### Description

Hey Thomas,

I really like your extension and I use it everyday for my design work.
It would be really awesome if I could name colors in the "Organize Colors" space so I could search them quickly when I need them. I'm often working on many different projects with different pallettes. That would help with organising them a bit.

Thank you very much for the extension so far!
Lennart

### Who will benefit from this feature?

Probably many professional designers and devs who work on more than one project at a time.

**Comment by mathieudutour** [comment]
Fixed in https://github.com/raycast/extensions/pull/10960
