### ISSUE TITLE
Mute and unmute message is opposite from what's happening

### ISSUE THREAD

**Issue by ikkeleif** [raycast/extensions#10770]
### Extension

https://www.raycast.com/sven/microsoft-teams-calling

### Description

The message for mute and unmute displays when the opposite happens.

### Steps To Reproduce

Use the mute/unmute command

### Current Behaviour

The message says unmute when I mute, and mute when it unmutes

### Expected Behaviour

Should be the other way around

**Comment by svenwiegand** [comment]
Fixed.

@raycastbot close this issue
