### ISSUE TITLE
[Omnivore] support tagging in quick capture

### ISSUE THREAD

**Issue by geddski** [raycast/extensions#10780]
### Extension

https://www.raycast.com/karolusd/omnivore

### Description

When doing quick captures it would be amazing to be able to apply tags. e.g. quick capture [link] [tags]

The current workflow is tedious: 
1. quick tag w raycast extension
2. open omnivore
3. find the new link
4. tag it
5. close omnivore

### Who will benefit from this feature?

ME! :D And all omnivore power users.

**Comment by KarolusD** [comment]
@geddski thanks for reporting, I will have a look on it.

**Comment by geddski** [comment]
awesome thank you!

**Comment by KarolusD** [comment]
@raycastbot close this issue
