### ISSUE TITLE
VS Code Project Manager Extension opens the repo in Finder instead of VS Code

### ISSUE THREAD

**Issue by juanantona** [raycast/extensions#1078]
# Extension – [VS Code Project Manager](https://github.com/raycast/extensions/tree/main/extensions/visual-studio-code-project-manager*)

Author: @MarkusLanger 

## Description
The `Open in Code` action of the extension open the repo in Mac Finder instead of VS Code app. The extensions was working perfectly previously. I've noticed this change on the behavior a couple of days ago after upgrading Raycast (1.30.1) and VS Code (1.65.0) also.

## Steps To Reproduce
1. Launch Raycast
2. Go to VS Code Project Manager Extension
3. Find a repo
4. Hit `Open in Code` action

## The current behavior
The `Open in Code` action of the extension open the repo in Mac Finder

## The expected behavior
It should be open in the VS Code app directly

### Raycast version
Version: 1.30.1

**Comment by MarkusLanger** [comment]
@juanantona Is the name of the VSCode app "Visual Studio Code" on your maschine?

![image](https://user-images.githubusercontent.com/12131918/157852490-312cb357-d7e0-4cd9-aad6-076cb5254468.png)

**Comment by juanantona** [comment]
> @juanantona Is the name of the VSCode app "Visual Studio Code" on your maschine?
> 
Yes @MarkusLanger, the name is "Visual Studio Code".

As I updated within the description of the issue, the extension worked like a charm until some days ago. I think that Raycast was upgraded.

**Comment by MarkusLanger** [comment]
@juanantona That's strange. I use the Raycast command to open it in VSCode.
https://github.com/raycast/extensions/blob/main/extensions/visual-studio-code-project-manager/src/search-project-manager-projects.tsx#L145
Works on my maschine with Raycast 1.30.1 and VSCode 1.65.2 without any problems.

**Comment by juanantona** [comment]
I restarted Raycast and worked again 🤷‍♂️  
Sorry for this! I close the issue.

Thanks for your quick response and for your work!
