### ISSUE TITLE
[SF Symbols Search] ...

### ISSUE THREAD

**Issue by rmbults** [raycast/extensions#10786]
### Extension

https://www.raycast.com/peteschaffner/sf-symbols-search

### Description

Whatever symbol you choose, it just copies a square with a question mark to the clipboard.

### Steps To Reproduce

Mac OS Sanoma
MBA M2 2022
Raycast

### Current Behaviour

Whatever symbol you choose, it just copies a square with a question mark to the clipboard.

### Expected Behaviour

copie the right file to clipboard

**Comment by peteschaffner** [comment]
I'm sorry this is causing you issues. Unfortunately I'm no longer maintaining the extension, but the first thing that comes to mind is to ask if you have the SF Symbols.app installed on your computer?

**Comment by rmbults** [comment]
Hi,
Sorry to hear. Doing other Raycast stuff?

And: i feel silly. Installed the app and now it works ☺️.

Thanks!




Op vr 16 feb 2024 om 09:43 schreef Pete Schaffner ***@***.***

**Comment by peteschaffner** [comment]
Oh great, glad that fixed it!

Not really doing anything else Raycast-related at the moment. I do think I will return to this plugin one day though as I really need/want it! I hit a wall earlier on with this extension that made it difficult to do updates that could be distributed via the store. I plan on looking back into it though to see if there have been any changes that could resolve the issue I had.
