### ISSUE TITLE
[Library Genesis] ... I can't download any book in raycast

### ISSUE THREAD

**Issue by gu-eth** [raycast/extensions#10798]
### Extension

https://www.raycast.com/yz3440/library-genesis

### Description

I can't download any book. When I try it, I get error.

### Steps To Reproduce

I try to download any book but I keep receiving this message:

At: request to https://download.library.lol/main/3205000/3c229dbbc4b034896b91cd7e75537e22/Christopher%20Leonard%20-%20The%20Lords%20of%20Easy%20Money_%20How%20the%20Federal%20Reserve%20Broke%20the%20American%20Economy%20(2022).epub failed, reason: certificate has expired

I don't know how to solve it.

**Comment by j3lte** [comment]
I think it has nothing to do with the extension, but with the library.lol website. If the certificate is expired, it will give an error in the browser as well.

We might be able to fix it by ignoring certificate errors. I'll make a possible bugfix

**Comment by gu-eth** [comment]
Please, I love this extension but I can't use it, if you fix it just let me know ok? Thank you so much @j3lte

**Comment by j3lte** [comment]
@gu-eth I have created an option to ignore errors, BUT... There is also another way to fix this: 

> Open your extension preferences and select a different Gateway. If you choose `Cloudflare` for example, downloads work as well.

I will also add this instruction in the error handling.

**Comment by j3lte** [comment]
Problem solved with last update

**Comment by j3lte** [comment]
@raycastbot close this issue
