### ISSUE TITLE
[Spotify Controls] ...

### ISSUE THREAD

**Issue by Cygnusfear** [raycast/extensions#1079]
# Extension – [Spotify Controls](https://github.com/raycast/extensions/tree/9750b478df29f2630a0186d64dfacfd57ff7b7ea/extensions/spotify-controls/)
Author: @thomaspaulmann

## Description
Unable to reset spotify control extension permissions after accidentally selecting 'don't allow'

## Steps To Reproduce

1. Install plugin, use 'play' command, click 'don't allow'
2. ???
3. profit!

## The current behavior
'Something went wrong' message

## The expected behavior
A way to reset the permissions

### Raycast version
Version: 1.30.1

**Comment by thomaspaulmann** [comment]
Mmh... Unsure if I can catch this case in JS, maybe depending on the error that AppleScript throws. In the meantime you should be able to recover by going to the system preferences, security and then accessibility. 
![CleanShot 2022-03-15 at 12 03 14](https://user-images.githubusercontent.com/12066405/158274831-80f70f08-4d05-4b1c-8091-6f902f64a8ff.png)
