### ISSUE TITLE
[API Feature Request]  Fallback image source

### ISSUE THREAD

**Issue by Rawnly** [raycast/extensions#108]
**Describe the feature and the current behavior/state.**
It would be nice to have a fallback image when the `source` is not available.

**Will this change the current api? How?**
```ts
<ListItem
	title={item.title}
	icon={{
	  source: item.mediaContent ?? Icon.QuestionMark, // What if returns 404?
	  mask: ImageMask.RoundedRectangle,
	  fallbackSource: 'https://via.placeholder.com/50'
	}}
/>
```
---

#### Example
![img](https://user-images.githubusercontent.com/16429579/137566725-00cdf3d9-f0d6-43a2-ba7b-dd89025db43c.png)
> Example of list with some broken image urls

**Comment by fe9lix** [comment]
Shipped!
