### ISSUE TITLE
[OpenAI Translator] ...

### ISSUE THREAD

**Issue by ZaeXT** [raycast/extensions#10805]
### Extension

https://www.raycast.com/douo/openai-translator

### Description

Request to add support for Japanese OCR (or third-party OCR).

### Who will benefit from this feature?

People who want to translate Japanese screenshot.

**Comment by douo** [comment]
Hi @ZaeXT, thank you for your feedback. This extension uses macOS's built-in OCR API. After checking the [supportedRecognitionLanguages](https://developer.apple.com/documentation/vision/vnrecognizetextrequest/3751006-supportedrecognitionlanguages), I found that macOS 14 already supports Japanese. I will update it soon.
