### ISSUE TITLE
[Toothpick] Extension Feature Request

### ISSUE THREAD

**Issue by khlebobul** [raycast/extensions#10815]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

Hello, can you please tell me if it is realistic to somehow watch the charge percentage on the Keychron keyboard? It would be very cool to get such a feature in your extension.

### Who will benefit from this feature?

I found a similar [request](https://www.reddit.com/r/Keychron/comments/gvk7e5/check_keychron_battery_life/) on Reddit, I think a lot of users of these keyboards would like this feature

### Anything else?

Honestly, I'd like to help with development too, but I've never done anything like this before

**Comment by VladCuciureanu** [comment]
Hey! At the moment I don't have a lot of time for hobby projects but if you're in a tinkering mood, check out my branch of Toothpick (available on my Github profile), open a PR with your changes and I'll review them.

Regarding Keychron support, I'm not sure what Keychron's support for such a thing is like. Usually if the battery percentage is available in MacOS' bluetooth menu, then it shouldn't be that difficult to map but if not then most likely will require a device-specific implementation.

**Comment by khlebobul** [comment]
Good day, ok, I have read a lot of information about this. Apparently they really don't support displaying the percentage of charge unfortunately. 

I'll keep this thread open for now, maybe I'll be able to find something. Then I would love to work on it. Thanks!
