### ISSUE TITLE
[Switch Game Play History] ...

### ISSUE THREAD

**Issue by rmbults** [raycast/extensions#10814]
### Extension

https://www.raycast.com/kvdo2/switch-game-play-history

### Description

Fetching data returns an error
See image

### Steps To Reproduce

Mac OS Sanoma
MBA M2 2022
Raycast
<img width="747" alt="Scherm­afbeelding 2024-02-18 om 16 56 58" src="https://github.com/raycast/extensions/assets/158844923/1d8d6de1-64d5-49ba-ab5c-c0afbbbdd735">

### Current Behaviour

error

### Expected Behaviour

able to browse game history

**Comment by kvdo2** [comment]
Thanks for using it, but unfortunately the Nintendo API was no longer available a few months ago (some apps can still get game records, but I don't know how). I previously proposed to the raycast administrator to remove the extension, but so far there has been no progress.
