### ISSUE TITLE
[ChatGPT] Inability to answer according to prompt rules or even refusal to answer

### ISSUE THREAD

**Issue by AeonWorks** [raycast/extensions#10818]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

When using the extension, both GPT-4 Turbo and GPT-3.5 Turbo do not output the prompt in the agreed summary format, and even reply "I can't complete this request".

The same prompt is not a problem when using other third-party OpenAI applications that call the same API.

### Steps To Reproduce

1. Latest Raycast and ChatGPT plug-ins
2. e.g. summarize the content of this page (select all and call the ChatGPT plugin with a shortcut key): https://elektrogesetz.com
3. using GPT-3.5 turbo-1106, or GPT-4-1106-preview
4. prompt the format control section:
#### Summary
Summarize the main topics in one sentence
#### Key points
- [Point 1]
- [Point 2]
- ...
- [Point n]

**Comment by bxb100** [comment]
could  you share your config and ask questions with prompt screenshots

**Comment by AeonWorks** [comment]
> could you share your config and ask questions with prompt screenshots

Can you leave me an e-mail address? I'll provide you with the full prompt. I am summarizing directly by calling the model with this prompt configured. @bxb100

**Comment by bxb100** [comment]
> > could you share your config and ask questions with prompt screenshots
> 
> Can you leave me an e-mail address? I'll provide you with the full prompt. I am summarizing directly by calling the model with this prompt configured. @bxb100 

you  can send to john@tomcat.run
