### ISSUE TITLE
[Google Chrome Profiles] ...

### ISSUE THREAD

**Issue by diglobalaccount** [raycast/extensions#10821]
### Extension

https://www.raycast.com/frouo/google-chrome-profiles

### Description

It would be great to just be able to switch to that profile, opening the existing window and active tab without forcing either an about:blank or a Google Search to open.

### Who will benefit from this feature?

Everyone.

**Comment by diglobalaccount** [comment]
Also would be good to be able to search open tabs (like shift + command + A) for that profile, then open to the selected open tab.

**Comment by frouo** [comment]
Hello, thank you for your feature request. Unfortunately this not possible, or at least I did not find the way to achieve that..

Maybe there is a way by using a more complex Apple Script which would check active windows (?) but I haven't had the time to dig more. 

Feel free to contribute, I would **really** love that feature too! :)

**Comment by danparker-ide2e** [comment]
Not very a very helpful contribution from me but UPVOTE!! Absolutely love the extension, thanks!

**Comment by diglobalaccount** [comment]
Don't know if this is helpful but this extension appears to be getting closer: https://www.raycast.com/Codely/google-chrome
