### ISSUE TITLE
[coffee] 'Caffeinate for' doesn't work if status bar is disabled

### ISSUE THREAD

**Issue by efa2d19** [raycast/extensions#10823]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

Noticed mac not going to sleep when I use coffee on long builds.
Tried to find why and status bar seems like the culprit.
When disabled - problems appears from time to time. If enabled - can't reproduce.

### Steps To Reproduce

> caffeinate is disabled; status bar is disabled
* Open Raycast
* Select 'Caffeinate for'
* Select any time (e.g. 10 min)
* cmd + enter
* Check if caffeinate really started
	( manually refresh status item w/ enter or `ps aux | grep caffeinate` )

### Current Behaviour

Failed to start/no caffeinate process

### Expected Behaviour

Started w/ specified time

**Comment by Drugsosos** [comment]
probably related to or part of #10729 tho

**Comment by pernielsentikaer** [comment]
@oasaleh do you have this issue?

**Comment by Drugsosos** [comment]
> By the way, I have these checked

Also have the same settings\
Can you check what happens on repeatedly toggling on and off "caffeinate for"?

**Comment by efa2d19** [comment]
I'm not sure why, but it's gone after system wipe 🤷‍♂️
