### ISSUE TITLE
[AirPods Noise Control] Not Working

### ISSUE THREAD

**Issue by rawnly** [raycast/extensions#10837]
### Extension

https://www.raycast.com/chrahe/airpods-noise-control

#### Error:
```
Error: Command failed with exit code 1: osascript
3362:3369: execution error: The variable menuBar is not defined. (-2753)

a0:run-applescript.js:38:21

---
35:         timedOut,
36:         command: "osascript",
37:         options,
38:         parentError: new Error(),
39:     })

### Steps To Reproduce

1. Install the extension
2. Configure it with `3` as position value

<img width="354" alt="image" src="https://github.com/raycast/extensions/assets/16429579/a4991c9e-e275-43e8-a8cc-dc0dcfba8935">


### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by rawnly** [comment]
Configured with `3` as position in sound menu 

<img width="354" alt="image" src="https://github.com/raycast/extensions/assets/16429579/e22edcbf-e735-404b-a847-4e716d3e930a">

**Comment by Yohandah** [comment]
same.
Says `Coltrol center not found. Check Localization !` (there's a typo btw)

<img width="1266" alt="image" src="https://github.com/raycast/extensions/assets/15921402/ff007144-e9e2-40c1-a269-5b80df90c763">

My mac is in english.
<img width="485" alt="image" src="https://github.com/raycast/extensions/assets/15921402/81593f44-c321-4315-9c4d-94d7460d1b17">

**Comment by rawnly** [comment]
@Yohandah  used this instead

```applescript
#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Toggle Airpods Isolation
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🔇
# @raycast.packageName Toggle Isolation Mode

# Documentation:
# @raycast.description Toggle Airpods Isolation
# @raycast.author fedevitaledev
# @raycast.authorURL https://raycast.com/fedevitaledev

set soundMenu to ""
set ancToggle to ""
set transparencyToggle to ""

set OFF_MODE to 4
set TRANSPARENCY_MODE to 5
set ADAPTIVE_MODE to 6
set ISOLATION_MODE to 7

tell application "System Events"
	tell its application process "ControlCenter"
		set menuBarItems to menu bar items of menu bar 1
		repeat with mbi in menuBarItems
			if description of mbi contains "Sound" then
				set soundMenu to mbi
			end if
		end repeat
		
		if soundMenu is not equal to "" then
			click soundMenu
			
			try
				set transparencyToggle to checkbox ISOLATION_MODE of scroll area 1 of group 1 of window 1
				set ancToggle to checkbox TRANSPARENCY_MODE of scroll area 1 of group 1 of window 1
			on error errMsg
				click UI element 3 of scroll area 1 of group 1 of window 1
				delay 0.2
				set transparencyToggle to checkbox ISOLATION_MODE of scroll area 1 of group 1 of window 1
				set ancToggle to checkbox TRANSPARENCY_MODE of scroll area 1 of group 1 of window 1
			end try
			
			if value of transparencyToggle is 1 then
				click ancToggle
			else
				click transparencyToggle
			end if
			
			click soundMenu
		end if
	end tell
end tell
`
``

**Comment by iamyeizi** [comment]
Hi 👋🏽 @Yohandah @rawnly 
Try restarting the pc and hide/show the menu bar.
I have tried from position 2 to 9 and it works.
I have tried with English, Spanish and French languages.

Position 3 works correctly.
![CleanShot 2024-03-09 at 1  28 58](https://github.com/raycast/extensions/assets/37552350/72296efc-084e-4ef7-a3f5-0229a5788d5b)

Note that you need to have these permissions enabled in the System Settings in order to run this extension correctly in  Raycast, in case you have not previously enabled them or no extension has requested them.

![configs](https://github.com/raycast/extensions/assets/37552350/38bea7d3-dbec-4cdd-a1d6-8d24610817cf)
