### ISSUE TITLE
[YouTube Downloader] ...: Encorder failed spawn eacces

### ISSUE THREAD

**Issue by Mapa404** [raycast/extensions#10831]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

When i download the video
![2024-02-19 16 22 46](https://github.com/raycast/extensions/assets/84152121/c7920c97-a834-42ae-a1db-8d1870ed171b)

### Steps To Reproduce

no matter what link a send , always failed

**Comment by vimtor** [comment]
Hi @Mapa404!

I'm sorry you are facing this issue. Could you please share the output of running `which ffmpeg` and `which ffprobe` on the terminal? Also, make sure the output values match the ones that appear in the extension settings.
