### ISSUE TITLE
Format Json Doesn't Work

### ISSUE THREAD

**Issue by royhenengel** [raycast/extensions#10830]
### Extension

https://www.raycast.com/destiner/json-format

### Description

When copying a JSON file's content, even though the content is valid, I get an error "Please copy a valid JSON object."

### Steps To Reproduce

1. On MacOS Version 14.3.1
2. What configuration are you referring to? Happy to provide it.
3. Launch Raycast and run the command "Json",  choose "Format Clipboard JSON", and paste the contents of this file:
[config.json](https://github.com/raycast/extensions/files/14335942/config.json)
4. See error: Please copy a valid JSON 

![CleanShot 2024-02-19 at 13 51 14](https://github.com/raycast/extensions/assets/13081692/7cdfefd6-d8d0-4f5d-9530-b6e8c01c8f14)
![CleanShot 2024-02-19 at 13 50 27](https://github.com/raycast/extensions/assets/13081692/78279717-4e2a-4324-82a9-152e485b4d2b)

### Current Behaviour

When copying a JSON file's content, even though the content is valid, I get an error "Please copy a valid JSON object."

### Expected Behaviour

Display and format a JSON file's content

**Comment by AlexIsMaking** [comment]
@royhenengel would you mind pasting that JSON snippet as text, to make it easier to test?

**Comment by royhenengel** [comment]
Of course, NP:

{"paddingVertical":"56px","paddingHorizontal":"56px","backgroundImage":null,"backgroundImageSelection":null,"backgroundMode":"color","backgroundColor":"rgba(171, 184, 195, 1)","dropShadow":true,"dropShadowOffsetY":"20px","dropShadowBlurRadius":"68px","theme":"material","windowTheme":"none","language":"auto","fontFamily":"Hack","fontSize":"14px","lineHeight":"133%","windowControls":true,"widthAdjustment":true,"lineNumbers":false,"firstLineNumber":1,"exportSize":"2x","watermark":false,"squaredImage":false,"hiddenCharacters":false,"name":"","width":"1280"}

should be:

{
  "paddingVertical": "56px",
  "paddingHorizontal": "56px",
  "backgroundImage": null,
  "backgroundImageSelection": null,
  "backgroundMode": "color",
  "backgroundColor": "rgba(171, 184, 195, 1)",
  "dropShadow": true,
  "dropShadowOffsetY": "20px",
  "dropShadowBlurRadius": "68px",
  "theme": "material",
  "windowTheme": "none",
  "language": "auto",
  "fontFamily": "Hack",
  "fontSize": "14px",
  "lineHeight": "133%",
  "windowControls": true,
  "widthAdjustment": true,
  "lineNumbers": false,
  "firstLineNumber": 1,
  "exportSize": "2x",
  "watermark": false,
  "squaredImage": false,
  "hiddenCharacters": false,
  "name": "",
  "width": "1280"
}
