### ISSUE TITLE
[Perplexity API] Setting to use clipboard instead of selected text

### ISSUE THREAD

**Issue by jul-sh** [raycast/extensions#10832]
### Extension

https://www.raycast.com/ilian/perplexity-api

### Description

this would be very useful

**Comment by maximilianzuern** [comment]
The clipboard function and using selected text as input are essentially redundant. 
In other words, I can’t think of a situation where using the clipboard is necessary while selecting text is not possible.

So, adding a switch for clipboard content might just make things more complicated and results in unnecessary clutter.

**Comment by jul-sh** [comment]
I would push back saying that it makes sense, given that the default action for the returned text is also to copy back to the clipboard. 

Relying on the selected text feels flakey to me, since it relies on which window is currently selected, etc.

**Comment by jul-sh** [comment]
But feel free to close if you disagree.

**Comment by maximilianzuern** [comment]
I agree that when dealing with long texts (>5,000 tokens), it becomes inconvenient to select the text. However, there are other features, such as follow-up conversations, that have a higher priority at the moment.

By the way: using CMD + ENTER allows you to directly paste the output into the current window.

@raycastbot close this issue
