### ISSUE TITLE
[Perplexity] Add ability to choose the Focus

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#10834]
### Extension

https://www.raycast.com/third774/perplexity

### Description

Sometimes I want to use the `Writing` focus mode instead of the `All` focus mode. It would be great to have the ability to choose the focus if possible.

**Comment by third774** [comment]
Unless I'm not understanding correctly, this is already available!
![perplexity 2024-02-19 at 23 19 21](https://github.com/raycast/extensions/assets/8732191/f77ce0ff-c0a1-4f29-a92e-90365662e9b6)

**Comment by xilopaint** [comment]
Oh, I always use the fallback so I forgot to check there. As I understand it, fallback always uses the `All` mode, correct? If yes, is it possible to enable the fallback to work with other focuses?

**Comment by third774** [comment]
Ah, gotcha! Yeah, we can add that as a preference!

**Comment by xilopaint** [comment]
> EDIT: Hrm, or we could add extra commands (disabled by default) that have the focus hard-coded so you can have multiple fallbacks?

I think this alternative is better.

**Comment by xilopaint** [comment]
> EDIT: Hrm, or we could add extra commands (disabled by default) that have the focus hard-coded so you can have multiple fallbacks?

Any news here, @third774? I'm looking forward to seeing this implemented.

**Comment by third774** [comment]
No news yet — have had a pretty busy week. Still on my radar though!
