### ISSUE TITLE
[Android Debug Bridge (Adb) Commands] Add force-stop and kill commands

### ISSUE THREAD

**Issue by ubuntudroid** [raycast/extensions#10840]
### Extension

https://www.raycast.com/Quentin23Soleil/adb

### Description

`adb shell am kill` and `adb shell am force-stop` should be added to the list of commands. The commands need a mandatory parameter containing the application ID.

### Who will benefit from this feature?

`adb shell am kill` stops the given process, but keeps state saved via `SavedStateRegistry` and thus is super handy for testing state restoration. It only works though if the app is in background.

`adb shell am force-stop` hard kills the process even if it is in foreground and removes all saved state that's not persisted on disk.

Both commands are very handy for most Android developers.

**Comment by ubuntudroid** [comment]
You mean using `adb shell input keyevent 3`? Didn't think of that, but it certainly makes sense to do it for the user (and let them know about it), yes! 

Just need to make sure to wait 2 or 3 seconds between backgrounding and killing so that the lifecycle is stopped and data is written to saved state.

**Comment by ubuntudroid** [comment]
Lovely, thanks @quentin23soleil ! 🙏

**Comment by quentin23soleil** [comment]
@ubuntudroid it's available, but note it's not enabled by default, you'll have to check it :)

**Comment by ubuntudroid** [comment]
Works like a charm! 🙌
