### ISSUE TITLE
[Music] Playlists took way too long to load

### ISSUE THREAD

**Issue by adisidev** [raycast/extensions#10845]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

First of all, thank you very much for your lovely work! I use this extension nearly everyday, and it makes raycast that much better for me!

I've been having trouble with playlists. The "Start Playlist" command takes very long to load. Would it be possible to cache the playlist list and update in the background (such that new playlists aren't instantly visible, but at least the cached playlists come up much faster each time)? It's really slow to the point that I can't use this command.

### Steps To Reproduce

(I've faced this issue in all environments, and all previous versions)
Try the "Start Playlist" command.
The screen keeps loading for close to 30 seconds.

**Comment by dgmulf** [comment]
I'm seeing the same issue on Raycast 1.104.22, macOS 26.5.1.
