### ISSUE TITLE
[Linear] Only the last 50 teams are shown when creating an issue

### ISSUE THREAD

**Issue by vineus** [raycast/extensions#10856]
### Extension

https://www.raycast.com/linear/linear

### Description

The `teams` GraphQL API call is not paginated: https://github.com/raycast/extensions/blob/c286c7bf40e6263bfc9100513e92a11b3a568def/extensions/linear/src/api/getTeams.ts#L24-L53

resulting in only the latest 50 teams being fetched from linear

Linear doc: https://developers.linear.app/docs/graphql/working-with-the-graphql-api/pagination

> The first 50 results are returned by default without query arguments.

If there are more than 50 teams some will be missing from the dropdown when creating a linear issue 

![Screenshot 2024-02-21 at 12 12 26](https://github.com/raycast/extensions/assets/467126/be7e8eee-a6b1-4e4e-903b-887cb8b2a061)

### Steps To Reproduce

1. create more than 50 teams in linear
2. trigger the "Create issue" linear raycast action
3. list the teams in the "Team" dropdown

### Current Behaviour

only the last 50 teams created are shown

### Expected Behaviour

all available teams are shown

**Comment by thomaslombart** [comment]
Thanks for opening up an issue. It can be fixed by adding typeahead search support to this field.

**Comment by jfkisafk** [comment]
@raycastbot assign me

**Comment by jfkisafk** [comment]
@raycastbot assign me
