### ISSUE TITLE
error [Hide All Apps] ...

### ISSUE THREAD

**Issue by rmbults** [raycast/extensions#10854]
### Extension

https://www.raycast.com/peduarte/hide-all-apps

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
activate application "Finder"
tell application "System Events" to tell process "Finder"
    click menu item "Hide Others" of menu 1 of menu bar item "Finder" of menu bar 1
end tell
tell application "Finder" to set collapsed of windows to true
  
87:173: execution error: System Events kreeg een fout: menu item "Hide Others" of menu 1 of menu bar item "Finder" of menu bar 1 of process "Finder" kan niet worden opgevraagd.  (-1728)

activate application "Finder"
tell application "System Events" to tell process "Finder"
    click menu item "Hide Others" of menu 1 of menu bar item "Finder" of menu bar 1
end tell

```

### Steps To Reproduce

MBA M2 2022
MAC OS Sanoma 14.3

### Current Behaviour

all windows stay open
error

### Expected Behaviour

hide all windows

**Comment by andrewsardone** [comment]
Darn, I’m guessing the use of a specific menu command in [this change](https://github.com/raycast/extensions/commit/8c8d236f7053e0f441fa4d21f4cd7427f791f6c5) breaks hide-all in non-English locales. That’s a miss on my part; apologies!

The best course of action is to revert to mitigate customer pain. The original process-iteration methodology is just more reliable.

I’m not at my MacBook, but can revert tomorrow (2/22).

**Comment by peduarte** [comment]
@andrewsardone no worries, thanks for that! Would have been nice to make this faster, I use it all the time and have often felt it was a bit too slow. But oh well!

**Comment by rmbults** [comment]
It works again. Thanks!

Met vriendelijke groet,


R.M. Bults

Meander 36 9951 VE WINSUM | 0612858160 | ***@***.***


Op do 22 feb 2024 om 16:01 schreef Pedro Duarte ***@***.***>
