### ISSUE TITLE
[Google Translate] Show auto detected source language

### ISSUE THREAD

**Issue by termosa** [raycast/extensions#10857]
### Extension

https://www.raycast.com/gebeto/translate

### Description

It would be nice to show what language did translation extensions detected when "auto-detect" is enabled

### Who will benefit from this feature?

Users who are using auto-detection

**Comment by rasitayaz** [comment]
you can see the detected language by hovering over the flags for "quick translate" command.

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/45076094/38f4a1af-2bf0-488a-b2c8-2f3bfbc3df89">
