### ISSUE TITLE
Sync with pomodoro-tracker

### ISSUE THREAD

**Issue by tygas** [raycast/extensions#10855]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

Would be great to sync pomodoros with https://pomodoro-tracker.com/

Cause from it with Habitica extensions it goes to https://habitica.com

I know it's a long shot, but I can contribute to that feature if somebody could guide me a littlebit

### Who will benefit from this feature?

https://pomodoro-tracker.com/ users

### Anything else?

It would be a next level pomodoro as you can see your track record

**Comment by MartinGonzalez** [comment]
That sound very nice, but I think it would add more value if its another extension that is exclusively focused on this Pomodoro Tracker service.

Lets see others feedback.
