### ISSUE TITLE
[Figma File Search] Add OAuth support

### ISSUE THREAD

**Issue by thomaslombart** [raycast/extensions#10867]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

Right now, the Figma extension requires a personal access token and team IDs. It would be great to add OAuth support, so that you can get started on the extension with just a few clicks 🙂

We've recently released a set of [OAuth utils](https://developers.raycast.com/utilities/oauth) to make that task easier. The most complicated bit would be to create the Figma OAuth app and deploy a PKCE proxy to hide the client secret.

### Who will benefit from this feature?

All Figma users of the extension.

### Anything else?

I can help in that process, especially on the PKCE proxy deployment as we require them to be hosted on Raycast's end.

**Comment by GLaDO8** [comment]
This would certainly make the extension more accessible to folks. @michaelwschultz if you don't mind, can I take this up?

**Comment by michaelwschultz** [comment]
@GLaDO8 that would be awesome! I've branches and choosing your default app on my todo list. Should have them done soon.

**Comment by thomaslombart** [comment]
@GLaDO8 FYI, I went ahead and deployed a PKCE proxy for you that's required to add OAuth support for Figma. You can use the following code in the extension in a dedicated file (e.g `oauth.ts`) for that:

```tsx
import { OAuth, getPreferenceValues } from "@raycast/api";
import { OAuthService } from "@raycast/utils";

const client = new OAuth.PKCEClient({
  redirectMethod: OAuth.RedirectMethod.Web,
  providerName: "Figma",
  providerIcon: "command-icon.png",
  description: "Connect your Figma account",
});

const { PERSONAL_ACCESS_TOKEN } = getPreferenceValues<Preferences>();

export const figma = new OAuthService({
  client,
  clientId: "YOUR_CLIENT_ID",
  authorizeUrl: "https://figma.oauth.raycast.com/authorize",
  tokenUrl: "https://figma.oauth.raycast.com/token",
  refreshTokenUrl: "https://figma.oauth.raycast.com/refresh-token",
  scope: "files:read",
  personalAccessToken: PERSONAL_ACCESS_TOKEN,
});
```

Then, you can use `withAccessToken` for the two extension commands. Finally, you can use `getAccessToken` in the different API calls. 

@michaelwschultz since you're the author of the extension, I'd need a client ID and a client secret after [creating an app in Figma](https://www.figma.com/developers/api#register-oauth2). Please, send me the client secret in the Slack community and the client ID in this issue 🙂

@GLaDO8 to avoid existing users to be logged out, it'd be better to keep support for personal access tokens. There are different headers to send depending on the type of token so you'll need some logic related to that. I quickly tested it out and this should be enough:

```tsx
import { getPreferenceValues, showToast, Toast, LocalStorage, environment } from "@raycast/api";
import fetch from "node-fetch";
import { ProjectFiles, TeamFiles, TeamProjects } from "../types";
import { getAccessToken } from "@raycast/utils";

async function fetchTeamProjects(): Promise<TeamProjects[]> {
  const { PERSONAL_ACCESS_TOKEN, TEAM_ID } = getPreferenceValues();

  const { token, type } = getAccessToken();
  const teamID: string[] = TEAM_ID.split(",").map((team: string) => team.toString().trim());
  const teams = teamID.map(async (team) => {
    try {
      const response = await fetch(`https://api.figma.com/v1/teams/${team}/projects`, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          ...(type === "oauth" ? { Authorization: `Bearer ${token}` } : { "X-Figma-Token": PERSONAL_ACCESS_TOKEN }),
        },
      });
      ...
```

Let me know if you need any more help with this 😊

**Comment by michaelwschultz** [comment]
No problem. App has been created. Here's the client ID - `dkY6v4uzFHoH4RaK7mB7Uw`

**Comment by thomaslombart** [comment]
@GLaDO8 Any updates on this one? 🙂

**Comment by pernielsentikaer** [comment]
That's just awesome @GLaDO8 🔥

**Comment by GLaDO8** [comment]
Hey @thomaslombart, the authorisation URL doesn't seem to be working for some reason. Anything I might be doing wrong? I'm using Michael's client ID and the OAuth setup seems fine. 
![CleanShot yEy7IdgUon2024-03-14at13 17 11](https://github.com/raycast/extensions/assets/22849100/94508754-9365-4d51-a29b-42349620fd65)

**Comment by thomaslombart** [comment]
@GLaDO8 We changed our configuration lately. I'll soon get back to you with new URLs to use 🙂

**Comment by michaelwschultz** [comment]
Also, I've updated the auth url. @thomaslombart will still have to make a quick change I believe but that should be it on my end. cc @GLaDO8

**Comment by thomaslombart** [comment]
@GLaDO8 Here are the new URLs you can use:

- `authorizeURL`: https://oauth.raycast.com/v1/authorize/_ege2-Xu_rzO6XIRwPi7Mnne6GARpdRe1I1IAf6ralbKRJjaByWNHIEK4e5ESizgQ_Z2B526iMt1KdooGAMIrAjVvIHgnhTcQziAP_CgEkzYzAHUJRPw
- `tokenURL`: https://oauth.raycast.com/v1/token/qTlHR2nhUt2e07Ynlbw-T4ALSoDPrGnUZU4z1VsH-scRq-We8cI9RfPKJb9UfEau0bCVYIc0qtW5fOVJ0rtUwDN6KSg5d8XgR_wRofMYARLRzAWhTb5mFsXTdFZl3GPQfA
- `refreshTokenURL`: https://oauth.raycast.com/v1/refresh-token/HoH9ux_TZ_15D9D2btgNZHFDsQtYmSFRQKBCeI4XodDg6svGnR7l7hQaSAV9XY95lD9YzMTPcucjZyHCzoGOHRerqbWB1WAJjpjEDPpwkM5Jg2YCIF-fUcv7VFBepLxT5M9iv

**Comment by GLaDO8** [comment]
Thank you!
