### ISSUE TITLE
Availability to remove default shortcut for action

### ISSUE THREAD

**Issue by Tchoupinax** [raycast/extensions#1086]
Hello :)

**Describe the feature and the current behavior/state.**

Actually when I want to specify a shortcut for my action, the default action stays available. 

```jsx
<Action
    shortcut={{ modifiers: ["cmd"], key: "enter" }}
    title="Finished"
  />
```

<img width="195" alt="image" src="https://user-images.githubusercontent.com/9136206/158013375-fd818740-cc61-4083-b7ef-93ee99ef3da6.png">

**Will this change the current API? How?**

It is the same thing for form submitting. The probleme here is that for form submitting, the default shortcut is CMD + enter whereas the default shortcut for detail panel action is just enter. It breaks the UX because of having two default shortcut and I would like to force CMD press to prevent from making mistakes.

Thanks for your project, very useful <3

**Comment by mathieudutour** [comment]
> It breaks the UX because of having two default shortcut and I would like to force CMD press to prevent from making mistakes.

That's debatable: it's the same across all of Raycast. You changing it in your extension would break this affordance.

**Comment by Tchoupinax** [comment]
Yes is it debatable ^^ Why having two kind of shortcut for the same kind of action ? In my opinion, the submit of a form and the main action on detail should be the same... but it is understandable it is not the case.

What do you mean by `having a primary action that doesn't change the item` ? You mean adding the "finished" action on my detail not with "enter" to not alter the "default behaviour" ?

**Comment by mathieudutour** [comment]
I'm not sure what your extension is doing so it's hard to give proper recommendations :) 

But yes if you are concern that people might trigger this action that is hard to revert or something, you might want to add an action before your "Finished" action (which I'm not sure what it does so again, take it with a grain of salt 😄) so that the Finished action is triggered with `cmd + enter`

**Comment by thomaspaulmann** [comment]
I'm echo-ing @mathieudutour here. You should stick to the default shortcuts. If the action is destructive, you can show [an alert](https://developers.raycast.com/api-reference/feedback/alert).
