### ISSUE TITLE
[Ngrok] Allow Label to be Associated with Cloud Edge for Tunnel Group

### ISSUE THREAD

**Issue by csaper** [raycast/extensions#10875]
### Extension

https://www.raycast.com/ubinatus/ngrok

### Description

Currently the value of the user input to the `Label` field in the Add Tunnel interface appears to be sent to Ngrok's [Start Tunnel API endpoint](https://ngrok.com/docs/agent/api/#start-tunnel) as a **metadata** property. 
Per the [docs](https://ngrok.com/docs/agent/config/#common-tunnel-configuration-properties), the  **metadata** property is
> an arbitrary user-defined metadata that will appear in the ngrok service API when listing tunnel sessions

Alternately, the value in the `Label` field can be sent to the API endpoint as a **labels** property.
Per the [docs](https://ngrok.com/docs/agent/config/#labeled-tunnel-configuration), the **labels** property is
> A list of labels (name=value) that can be used to identify a tunnel to an ngrok Edge (specifically a tunnel group backend)

By implementing this, the user can input `edge={edge_hts_id}` as their label and the tunnel will be created on a [secure edge](https://ngrok.com/docs/network-edge/edges/) associated with their personal endpoint, of which they can add modules, security restrictions, load balancing, etc.

### Anything else?

Thanks!

**Comment by ubinatus** [comment]
Hey @csaper ! Thank you for your feedback 🙏. I believe the "label" was added as metadata solely for display purposes in the extension. The original intent was not to create a Labeled Tunnel Configuration but rather just to add a "tag".

However, this might be confusing for ngrok users who are meant to use a "label" for _ngrok Cloud Edges_ purposes.

We'll be addressing this issue later this week (busy with work). I feel that there should be a clear distinction between "tags" and "labels". I'll keep you updated on the progress. Thank you again for your input.
