### ISSUE TITLE
[URL Unshortener] Unable to Expand URL from https://is.gd

### ISSUE THREAD

**Issue by alwinsamson** [raycast/extensions#10886]
### Extension

https://www.raycast.com/SebDanielsson/url-unshortener

### Description

URL Unshortener is showing error when expanding URL from https://is.gd. 
System: Raycast 1.68.1 on macOS 14.3.1
Example URL: https://is.gd/putPEo
![image](https://github.com/raycast/extensions/assets/71998285/7674db23-b1d5-46e0-9a96-74b8c2df64c0)

### Steps To Reproduce

Tried different URL from https://is.gd same result

**Comment by sebdanielsson** [comment]
I just tried unshortening https://is.gd/putPEo with Raycast 1.68.1 running on macOS 14.3.1 and didn't get any error messages. Do you still have this issue?

**Comment by alwinsamson** [comment]
It works, wondering if it's also possible to expand/clean URL like this, I use www.expandurl.net to get the canonical URL. 

`https://redirect.viglink.com/?key=0ab71bd42c2ca312a536dac167978a13&u=https%3A%2F%2Fwww.amazon.com%2FApple-MU8F2AM-A-Pencil-Generation%2Fdp%2FB07K1WWBJK%2F%3Ftag%3Dtoysb-20&type=ap&loc=https%3A%2F%2F9to5toys.com%2F2024%2F02%2F17%2Fapple-pencil-2-drops-to-to-79-at-amazon-its-second-best-price-reg-129%2F&ref=https%3A%2F%2F9to5toys.com%2F`

![Screenshot 2024-02-22 at 13 19 19@2x](https://github.com/raycast/extensions/assets/71998285/308ed064-0c3d-48d6-9662-3d76352bbb8d)

**Comment by sebdanielsson** [comment]
Sorry for the late reply!

I'm not sure how to implement that functionality as sometimes the parameters are used to redirect the user to the final page. Preferably I would like to avoid depending on an online service. PRs are welcome of course😉
