### ISSUE TITLE
[Air Quality] Menu Bar Doesn't Automatically Refresh

### ISSUE THREAD

**Issue by zaksuhar** [raycast/extensions#10887]
### Extension

https://www.raycast.com/earthpyy/air-quality

### Description

The Menu Bar seems to not dynamically update in real-time. I clicked on the "dot and number" icon and it changed the AQI when I expected it to automatically refresh.

### Who will benefit from this feature?

All users.

**Comment by earthpyy** [comment]
Hi! Thanks for reporting this. I hope #10906 will fix the problem!
