### ISSUE TITLE
[Bitwarden Vault] ...

### ISSUE THREAD

**Issue by angelineflorajohn** [raycast/extensions#10885]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

It'd be helpful to have the "Send" feature of Bitwarden implemented within Raycast. The "Send" feature is useful in sending crendentials or any other sensitive information as text through a secure link. I use this functionality everyday at my place of work.

<img width="640" alt="image" src="https://github.com/raycast/extensions/assets/25217498/f28245eb-d2a0-45cb-8f55-fd7569a5d442">

### Who will benefit from this feature?

Anyone using Bitwarden to send important sensitive information over a secure link.

**Comment by jomifepe** [comment]
Hey, thanks for the suggestion. This will be implemented in the future for sure 🙂

**Comment by jomifepe** [comment]
3 new commands were released, give them a try @angelineflorajohn 🚀
