### ISSUE TITLE
[Air Quality] `Unknown station` is returned for an existing station

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#10893]
### Extension

https://raycast.com/earthpyy/air-quality

#### Error:
```
Error: Unknown station
    at yr (/Users/arthur/.config/raycast/extensions/34a75a54-9d4a-4fb8-986b-5ec5b79e7568/show-air-quality.js:43:5126)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

1. Define the station [@40576](https://aqicn.org/station/@40576/) in Raycast Settings
2. Run Show Air Quality command

### Current Behaviour

`Unknown station` error is returned.

### Expected Behaviour

Air Quality information returned.

**Comment by earthpyy** [comment]
Hi! Thanks for reporting. This should be fixed in #10906.
