### ISSUE TITLE
[(Basic) Bookmarks] Create bookmark without confirmation step

### ISSUE THREAD

**Issue by navtoj** [raycast/extensions#10892]
### Extension

https://www.raycast.com/rauno/bmrks

### Description

Currently, the confirmation view (screenshot below) shows up when I run the "Create Bookmark" command with a keyboard shortcut.

I want to have an option to create a bookmark without having to confirm the group or link title.

![bmrks](https://github.com/raycast/extensions/assets/20136585/3df19531-d6b1-4249-91e5-63b7950a354d)

### Who will benefit from this feature?

Anyone who wants to create bookmarks faster with a single keyboard shortcut.

### Anything else?

It can be implemented with a `no-view`[^1] command that runs in the background and shows a message to inform the user of completion (or error) with the `showHUD`[^2] api.

[^1]: https://developers.raycast.com/information/lifecycle#no-view-command
[^2]: https://developers.raycast.com/api-reference/feedback/hud

**Comment by peduarte** [comment]
But which group would it save to?

**Comment by navtoj** [comment]
> But which group would it save to?

The last group used by the user or an option in the command preferences to set a default group.

**Comment by peduarte** [comment]
Preferences can't have dynamic options unfortunately, and having it as a text field is too error prone

Defaulting to the last used group seems a bit random to me... I think this would only work if bmrks supported some sort of "inbox" approach, or an "all" category, where we could safely add bookmarks to, and then they can be moved

@raunofreiberg curious about your thoughts here

**Comment by navtoj** [comment]
> Preferences can't have dynamic options unfortunately, and having it as a text field is too error prone

The dynamic options could be exposed in a "preferences" page using a `Form.Dropdown`[^1] component and the user settings can be saved in local storage[^2].

[^1]: https://developers.raycast.com/api-reference/user-interface/form#form.dropdown
[^2]: https://developers.raycast.com/api-reference/storage

**Comment by raunofreiberg** [comment]
Yeah, I think what Pedro was saying is that we can't fetch data in the preferences view to populate a dropdown. So you'd have to just manually fill in a text field with your group name (e.g. `articles`) which feels awkward. Do I have that right?

**Comment by navtoj** [comment]
You're completely right, Raycast's Preferences API doesn't allow dynamic values and having a text field is just bad ui/ux.

I was talking about a Preferences page without using that api.

**Comment by peduarte** [comment]
@raunofreiberg yeah you got that right 

@navtoj yeah that would mean creating a new command. Some extensions do that, although it's just a workaround for the lack of dynamic preferences. This is on our list. I find that having these extra commands can be a bit overwhelming for people. 

Im leaning towards the optimal solution being that bmrks supports the creation of bookmarks outside of a group, especially because other people have requested the ability to browse all bookmarks ([pr here](https://github.com/raycast/extensions/pull/10900)). But obviously that's a slight change on the product side, not sure how Rauno feels about this

**Comment by raunofreiberg** [comment]
Mm yeah, I think a catch-all category like you made in #10900 would be useful on the web interface. 

Currently, you need to send a `group_id` when creating a bookmark but perhaps if we had an index view on the web, that's where we could send all bookmarks without a group ID.

**Comment by navtoj** [comment]
@peduarte 
> I find that having these extra commands can be a bit overwhelming for people.

Hmm, in that case, what about just an `ActionPanel.Submenu`[^1] to show the options instead of a whole separate command.

And, this could of course be deprecated when there is a change on the product side that allows for a non-group bookmark or a generic group.

[^1]: https://developers.raycast.com/api-reference/user-interface/action-panel#actionpanel.submenu

**Comment by peduarte** [comment]
If we can make this "all" category, then I guess we can just send all links there. If not, then we'd have to choose between a command or an action. I can see the benefit of assigning a hotkey and having your links automatically being saved!
