### ISSUE TITLE
[Messages] Couldn't send SMS (person without iMessage)

### ISSUE THREAD

**Issue by dariuszpaluch** [raycast/extensions#10899]
### Extension

https://www.raycast.com/thomaslombart/messages

### Description

Send message to person without Imessage cause error.

![Screenshot 2024-02-22 at 21 09 57](https://github.com/raycast/extensions/assets/15227876/9d20b614-305a-41a6-b743-b96c7b5f4ee1)
![Screenshot 2024-02-22 at 21 09 52](https://github.com/raycast/extensions/assets/15227876/8a4fa112-64e8-4c4d-ad7d-9e2adcabb0fe)

### Steps To Reproduce

1. Select person (who don't have iMessage -> SMS)
2. Write message
3. Send message

### Current Behaviour

- got error with: "Not Delivered"
- In details I saw option "Send as text message" -> then the message will send correctly

### Expected Behaviour

- send message correctly

**Comment by thomaslombart** [comment]
Thanks for reporting the issue. I'll take a look at it in the next few weeks. Feel free to give it a try if you'd like.

**Comment by thomaslombart** [comment]
Fixed with #14817.
