### ISSUE TITLE
[Color Picker] Add possibility to rename color

### ISSUE THREAD

**Issue by Jeromearsene** [raycast/extensions#10895]
### Extension

https://www.raycast.com/thomas/color-picker

### Description

Actually, colors have hexadecimal color like name. Ideally, I would like possibility to rename. It would be very practical in multiple project. By example:
- project 1 - primary
- project 1 - secondary
- project 2 - primary
- etc...

### Who will benefit from this feature?

Graphiste, marketing & frontend developers. Specially in multiple projects

**Comment by pernielsentikaer** [comment]
Opened #10960
