### ISSUE TITLE
[Zoom] "Start meeting" command is not working (400 error with invalid token reason)

### ISSUE THREAD

**Issue by Andry75** [raycast/extensions#10896]
### Extension

https://www.raycast.com/raycast/zoom

### Error
Error: Error while refreshing tokens: 400 (Bad Request)
{"reason":"Invalid Token!","error":"invalid_grant"}

Ue.refreshTokens:OAuthService.js:136:18

---
133:         if (!response.ok) {
134:             const responseText = await response.text();
135:             console.error("refresh tokens error:", responseText);
136:             throw new Error(`Error while refreshing tokens: ${response.status} (${response.statusText})\n${responseText}`);
137:         }
138:         const tokenResponse = (await response.json());
139:         tokenResponse.refresh_token = tokenResponse.refresh_token ?? token;
---

async Ue.authorize:start-meeting.js:41:14115

### Steps To Reproduce

1. Env:
  * Raycast version: 1.68.1
  * Zoom version: 5.16.10 (25689) 
2. Run `Start Meeting` command
3. Get the error like `Something Went Wrong`

### Current Behaviour

When attempting to launch a Zoom meeting, it is not working as on screenshot below:
<img width="862" alt="Screenshot 2024-02-22 в 18 14 47" src="https://github.com/raycast/extensions/assets/3405299/c4a251e1-8a9a-47bb-806a-1185949f3039">

### Expected Behaviour

Suppose to work :slightly_smiling_face:

**Comment by thomaslombart** [comment]
Did you notice when this happens? Have you revoked the access to Raycast in Zoom's settings?

**Comment by thomaslombart** [comment]
Can you point out or recall which update made it fail?

**Comment by thomaslombart** [comment]
Fixed as part of https://github.com/raycast/extensions/pull/13427.
