### ISSUE TITLE
Do Not Disturb Toggle command is invalid when disturb is on

### ISSUE THREAD

**Issue by quanru** [raycast/extensions#10905]
### Extension

https://www.raycast.com/yakitrak/do-not-disturb

### Description

Do Not Disturb Toggle command is invalid when disturb is on

### Steps To Reproduce

1. turn on
2. toggle

**Comment by Yakitrak** [comment]
@quanru could you please share some more information on what you mean by invalid? I just tried it and I am able to toggle between DND on and off without any issues.

**Comment by quanru** [comment]
When turned on, toggle has no reaction; the reverse is normal

**Comment by quanru** [comment]
I deleted the shortcut command and downloaded it again, but there is still a problem. It seems that the status is not correct

![image](https://github.com/raycast/extensions/assets/11739753/54ccb732-f458-4c4f-992a-4992dd46b39f)
![image](https://github.com/raycast/extensions/assets/11739753/23834621-e219-41eb-8e38-a57b01ffcaf2)

**Comment by Yakitrak** [comment]
Could you please remove the shortcut itself - delete this one in the Shortcuts app:
<img width="149" alt="image" src="https://github.com/raycast/extensions/assets/15147598/8f0fcd18-1e97-4965-b73a-87f3e7fd5298">

Then please delete and reinstall the Do Not Disturb extension from the store. I am not sure why this is happening as the extension makes use of the the shortcut which is native functionality. If the above steps do not work, then I think this might be something specific to your do not disturb settings.

**Comment by quanru** [comment]
I know why, locale Issue:
![image](https://github.com/raycast/extensions/assets/11739753/bb697f5a-7e00-4b93-b9e5-f6e1583942ea)

**Comment by quanru** [comment]
I think this change can work:
```js
export async function getDNDStatus() {
  const { stdout } = await executeCommand(`echo "status" | shortcuts run "${DNDshortcutName}" | cat`);
  return !stdout;
}
```

**Comment by Yakitrak** [comment]
Ah its local language issue, thank you for flagging this. I think your change will work but it would be good to test it a bit more. Do you want to make a PR for this?

**Comment by quanru** [comment]
> Ah its locale issue, thank you for flagging this. I think your change will work but it would be good to test it a bit more. Do you want to make a PR for this?

I'd love to!
