### ISSUE TITLE
Kimai HTTP-Request

### ISSUE THREAD

**Issue by ElMorito** [raycast/extensions#10902]
### Extension

https://www.raycast.com/marinsokol/kimai

### Description

The Raycast Kimai extension automatically makes an HTTPS request to the domain of the Kimai instance. This is problematic when the Kimai instance is running locally, as it typically does not use a SSL certificate.

The extension should provide the option to select the type of request (HTTP or HTTPS). This would allow the extension to be used with a locally running Kimai instance.

### Who will benefit from this feature?

All users who use a local Kimai instance or cannot use SSL for other reasons.

**Comment by marinsokol** [comment]
@ElMorito Update to extension has been published :-)

**Comment by ElMorito** [comment]
Thank you! Works fine 😁
