### ISSUE TITLE
[Music] ...

### ISSUE THREAD

**Issue by AnubisDeathGod01** [raycast/extensions#10903]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

Can you add the ability to browse within Apple Music? 
![Apply Music search option](https://github.com/raycast/extensions/assets/157870273/f4fe4deb-06d0-4b72-9e94-bbac0ef3a5f3)

**Comment by rawnly** [comment]
Hi @AnubisDeathGod01 unfortunately this is currently impossible due to api limitations
