### ISSUE TITLE
[Zed] Recent projects - add support for built-in Zed Recent Projects storage

### ISSUE THREAD

**Issue by sundevista** [raycast/extensions#10917]
### Extension

https://www.raycast.com/ewgenius/zed-recent-projects

### Description

When I activate the command "Search recent projects," I get an empty list whether I type something or not. I've opened Zed and checked if it captures my projects. Zed's "projects: open recent" works well and provides me with a list of my recent projects.

I have Zed Preview installed alongside with stable version, I checked if it's overriding settings, but it has recent projects as well.

<img width="764" alt="Screenshot 2024-02-23 at 17 23 41" src="https://github.com/raycast/extensions/assets/56955307/d95a4f3f-6abf-403f-bffb-abf4a9425505">
<img width="734" alt="Screenshot 2024-02-23 at 17 24 01" src="https://github.com/raycast/extensions/assets/56955307/1aace529-e0e2-467e-a0ef-c384cb17a073">

### Steps To Reproduce

1. Use "Search recent projects" command

### Current Behaviour

Empty list

### Expected Behaviour

List of actual projects

**Comment by ewgenius** [comment]
@sundevista thanks for reporting.

That is known issue, because this extension was created before zed had built-in recent projects supported, and has no connection to it.

I'm planning to fix that soon.

**Comment by ewgenius** [comment]
@raycastbot rename this issue to "[Zed] Recent projects - add support for built-in Zed Recent Projects storage"

**Comment by ewgenius** [comment]
@sundevista feel free to update extension, it should pull native zed projects now
