### ISSUE TITLE
[Random Data Generator] Empty result on Boolean random generator

### ISSUE THREAD

**Issue by lucastnr** [raycast/extensions#10919]
### Extension

https://www.raycast.com/loris/random

### Description

The boolean generator under `Generate Random Data` displays blank content instead of what I believe should be `false` (as opposed to `true`).

![Screenshot 2024-02-23 at 13 16 30](https://github.com/raycast/extensions/assets/59018759/602e0053-8a46-468f-83bd-5a79cd07d870)

### Steps To Reproduce

1. Run the _Generate Random Data_ command
2. Navigate to _Boolean_ option
3. Regenerate the result until you get an empty result on the right panel

### Current Behaviour

Shows blank text

### Expected Behaviour

Shows `false`

**Comment by stefanmatar** [comment]
@raycastbot close this issue
