### ISSUE TITLE
read-only and/or disabled form fields

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#1091]
**Describe the feature and the current behavior/state.**

It'd be very useful to provide a way to set text fields and other form elements as disabled or read-only so that users can't edit their content.

**Will this change the current API? How?**

the existing input components should accept a new `disabled` property.

**Who will benefit from this feature?**

Extensions that need to conditionally allow users to edit a specific field depending by some state.

**Any Other info.**

**Comment by bkeys818** [comment]
> @peduarte I think this has been accidentally closed by your commit

@peduarte, I second this... 😂
