### ISSUE TITLE
Add current color scheme to environment variables

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#1092]
**Describe the feature and the current behavior/state.**

Right now there's no way to know if Raycast is running in light or dark mode. This information should be available so that we can render extension's UIs properly, adapting colors to match the window background.

**Will this change the current API? How?**

**Who will benefit from this feature?**

Extensions that render colored icons, text, or images

**Any Other info.**

**Comment by thomaspaulmann** [comment]
As of [v1.31](https://developers.raycast.com/changelog#1.31.0-2022-03-23), you can use `environment.theme`.
