### ISSUE TITLE
[Bitwarden Vault] I don't need a password to access vault

### ISSUE THREAD

**Issue by andygjp** [raycast/extensions#10925]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

I can view all logons without entering a password.

### Steps To Reproduce

1. Open Raycast prompt
2. Type Bitwarden and press return -> Raycast prompt asks for password
3. Press escape
4. Type Bitwarden and press return -> Raycast lists all logons in vault

I have timeout configured to 4 hours. I don't know if using a timeout is significant.

### Expected Behaviour

I should have to enter a password to access vault.

**Comment by jomifepe** [comment]
Hey, thanks for reporting. Definitely not an expected behavior, fixing it right now.

**Comment by jomifepe** [comment]
The issue should be fixed, give it a try 🙂

**Comment by andygjp** [comment]
This is working as expected. Thank you!

**Comment by jomifepe** [comment]
@raycastbot close this issue
