### ISSUE TITLE
Services used? [URL Unshortener] ...

### ISSUE THREAD

**Issue by Visual-Studio-Coder** [raycast/extensions#10929]
### Extension

https://www.raycast.com/SebDanielsson/url-unshortener

### Description

You mention that security and privacy will be improved with this extension, except, it isn't mentioned anywhere what service you are using to expand the URLs. If we are just doing it with fetch, then thats useless and not very private. If it is using a dedicated service that expands it serverside, then that is private

If you DO find a service that does it free serverside, then please update this extension, and please add it to the readme. Thank you so much!

**Comment by Visual-Studio-Coder** [comment]
@sebdanielsson you should use unshorten.me api. recently discovered it

**Comment by sebdanielsson** [comment]
No. That wouldn't be good for privacy.
https://unshorten.me/privacy-policy
