### ISSUE TITLE
[Amazon AWS] service endpoint does not exist

### ISSUE THREAD

**Issue by bennnym** [raycast/extensions#10927]
### Extension

https://www.raycast.com/Falcon/aws

### Description

Multiple services do not work with this error:

for ssm, ecs etc.

S3 is the only one that is working.

```
Error: getaddrinfo ENOTFOUND ssm.ap-southeast-2.api.aws
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
 ```

### Steps To Reproduce

look for any details in the above services.

### Expected Behaviour

It works!!

**Comment by JonathanWbn** [comment]
@bennnym Do you by any chance have a `use_dualstack_endpoint=true` setting in your AWS config file? If so, could you try again after setting that value to `false`?

**Comment by bennnym** [comment]
That was it, thanks @JonathanWbn !!
