### ISSUE TITLE
[Copy Path] ... RootURL?

### ISSUE THREAD

**Issue by tadgill** [raycast/extensions#10937]
### Extension

https://www.raycast.com/koinzhang/copy-path

### Description

Is it possible to have an option to copy just the base or root url? Like copy then strip out all but the base: 

Example:  https://foo.net becomes foo or  https://sub.foo.net/lotsofstuff?blah=lots also becomes foo. (Or maybe adjustable to foo or foo.com or sub.foo.com ? 

### Who will benefit from this feature?

I WILL ! But many others might - I'm writing a tutorial on how to not ruin your inbox and fight spam, and add security by creating email aliases for every login you create.  So right now I copy "foo" into the clipboard, then run a snippet to use the clipboard to make: foo_myemail@myemaildomain.com so that way every site has a unique password AND email. If I could shortcut to just one command that would rock!

**Comment by koinzhang** [comment]
Hi @tadgill Your needs are very specific and too customized for a generic extension to fully satisfy.
But I optimized the ability to copy URLs in PR #10984. Now you can choose which part of the URL to copy.
<img width="299" alt="image" src="https://github.com/raycast/extensions/assets/36128970/13344d79-5467-4795-8682-3228bf06e2cd">

**Comment by koinzhang** [comment]
@raycastbot close this issue
