### ISSUE TITLE
[Air Quality] ...Error

### ISSUE THREAD

**Issue by rmbults** [raycast/extensions#10944]
### Extension

https://www.raycast.com/earthpyy/air-quality

### Description

error log:
TypeError: Cannot read properties of undefined (reading 'iso')

Er:show-air-quality.tsx:8:54

---
 5: import { getForecastRecords, getPollutionLevelAndImplication } from "./shared/utils";
 6: 
 7: export default function Command() {
 8:   const { data, error, isLoading } = useCachedPromise(fetchAirQuality);
 9: 
10:   if (error || !data) {
11:     return (
---

Dr:index.js:11:2490
    at ray-navigation-stack
Lo:index.js:11:2088

### Steps To Reproduce

MBA 2022 M2 OS Sanoma 14.3

### Current Behaviour

error

### Expected Behaviour

show airquality in pane

**Comment by rmbults** [comment]
Only when specifiing a location (https://aqicn.org/station/@86785/). When location empty then it works fine, but it does not use the nearest location.

**Comment by earthpyy** [comment]
@rmbults Hello! Thanks for opening the issue. I believe #10906 would also fix this issue!

By the way, the nearest location is determined by the IP's location which could be inaccurate. This is the default behavior of the AQICN API we've using.

**Comment by rmbults** [comment]
Okay, thanks, I will check when update has been processed in Raycast.
