### ISSUE TITLE
[ChatGPT] Unable to automatically synchronize OpenAI newest official models

### ISSUE THREAD

**Issue by AeonWorks** [raycast/extensions#10941]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

The OpenAI model has been updated to 0125, the extension only has 1106.

Can the user enter a Model ID?

Or is it possible to synchronize official updates?

### Steps To Reproduce

1. Latest Raycast and ChatGPT extension
2. Call Model by selecting the model in Edit Model
3. GPT-3.5 and GPT-4 only have 1106 version

**Comment by renehuber** [comment]
I would like to propose, that the model value can be freely overwritten with any value. Not only does it allow to change to new or less popular OpenAI models, it would also enable to use other LLMs which have a compatible API (for example, Perplexity).

**Comment by bxb100** [comment]
@renehuber @AeonWorks the latest version can customize the model's name

<img width="348" alt="image" src="https://github.com/raycast/extensions/assets/20685961/a2d70a20-92c1-4641-acce-fcb80823c8fb">
