### ISSUE TITLE
Assets are not reloaded until Raycast is restarted

### ISSUE THREAD

**Issue by Loskir** [raycast/extensions#1095]
Raycast version: 1.30.2

## Description
Assets (icons) are not reloaded on-the-fly when in dev mode or when building the extension. It is required to restart Raycast entirely to reload the icons

## Steps To Reproduce

1. Create an extension that uses local file (located in assets directory) as a list item icon or similar
2. Build the extension
3. Open the extension in Raycast, make it show that icon
4. Replace that file with another icon
5. Build the extension again
6. Open the extension in Raycast, see that the icon has not changed.
7. Reload the extension, it won't help
8. Restart Raycast using "Quit Raycast" command
9. Open the extension
10. Now the icon is reloaded

The same applies to dev mode.

## The expected behavior
Raycast shouldn't cache the icons so heavily, at least for dev mode and also maybe for locally installed extensions

**Comment by fe9lix** [comment]
There will be a new dev action to clear the assets cache in the next release.

**Comment by xilopaint** [comment]
I'm facing this issue and `Clear Assets Cache` doesn't work for me.

@raycastbot reopen this issue

**Comment by xilopaint** [comment]
@pernielsentikaer, please take a look at this.

**Comment by inducingchaos** [comment]
Bumping this - clearing the assets cache still does not work

@fe9lix

**Comment by Ernest0-Production** [comment]
+
