### ISSUE TITLE
[Snippet Surfer] ...Add a dedicated YAML field for tags

### ISSUE THREAD

**Issue by jasonshanks** [raycast/extensions#10953]
### Extension

https://www.raycast.com/astronight/snippetsurfer

### Description

Love this future-proof solution for referencing code snippets! I think using a ‘- tagname’ at the end of the title is simple (took my a while to realise that was how it was working). But even better might be using a YAML `tag:` field that you could comma-separate multiple tags.

### Who will benefit from this feature?

anyone using this to store their code snippets

**Comment by mkitane** [comment]
> But even better might be using a YAML tag: field that you could comma-separate multiple tags.

Good idea, we can add support for the `tags` field.
How would you see it being used in the app/UI?

**Comment by jasonshanks** [comment]
Hi thanks for considering!
For UI: obviously might be cumbersome to list them all on left, maybe just leave the first tag as you have there, then on the right, under the title list them all in the little pillbox outlined format?

For search: exactly [like this](https://raycastcommunity.slack.com/archives/C06HTSUL0E7/p1708987958115249): tuplets search query, eg. `tag:html` and the drop-down search filter already in place
