### ISSUE TITLE
[Easy Dictionary] DeepL Error 503, Youdao Error 400

### ISSUE THREAD

**Issue by sunrisewestern** [raycast/extensions#10968]
### Extension

https://www.raycast.com/isfeng/easydict

### Description

Get Error code 503 (Service Unavailable) for Deepl and Error code 400 (Bad request) for youdao. 

### Steps To Reproduce

Any

**Comment by tisfeng** [comment]
I have no problem testing here.

<img width="810" alt="image" src="https://github.com/raycast/extensions/assets/25194972/60d3382a-d0c5-4bad-8c40-a604ba97eb88">

**Comment by sunrisewestern** [comment]
我发现是raycast web proxy 的问题，打开系统代理 并且 raycast 勾选 web proxy 后就会报错，就算关闭代理也不行，必须禁用 raycast web proxy才行
