### ISSUE TITLE
[YouTube] Regular use of the extension makes the Action Panel inaccessible

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#10969]
### Extension

https://www.raycast.com/tonka3000/youtube

### Description

There's a severe issue related to the use of this extension. If one uses it for a little while, the Action Panel becomes inaccessible, either via mouse or keyboard, and the user has to quit Raycast and start it again.

I have the code ready for a PR with a couple of fixes and improvements (unrelated to this issue), but I think it's better to wait for this fix. I believe the issue lies on Raycast's side, as the Action Panel should not freeze under any circumstance.

### Steps To Reproduce

I cannot provide precise steps to reproduce the issue, but it is not difficult to replicate. Continuously using the Search Videos command for a couple of minutes renders the Action Panel inaccessible at some point.

**Comment by tonka3000** [comment]
Hey,

This sounds like a little bit like https://raycastcommunity.slack.com/archives/C01A0R0NXGQ/p1708941833991259?thread_ts=1708941833.991259&cid=C01A0R0NXGQ

@pernielsentikaer

**Comment by lcardito** [comment]
> Hey,
> 
> This sounds like a little bit like https://raycastcommunity.slack.com/archives/C01A0R0NXGQ/p1708941833991259?thread_ts=1708941833.991259&cid=C01A0R0NXGQ
> 
> @pernielsentikaer

In which case it probably isn't only for youtube.. I for instance don't use the youtube extension.. 🤔

**Comment by tonka3000** [comment]
Hey @xilopaint ,

I try to replicate your issue but get no issues. Do you be maybe on MacOS Sonoma?

**Comment by xilopaint** [comment]
Yes. macOS 14.2.1.

**Comment by lcardito** [comment]
> Hey @xilopaint ,
> 
> I try to replicate your issue but get no issues. Do you be maybe on MacOS Sonoma?

Same here :D if that helps!

**Comment by AISLVE** [comment]
hey @tonka3000 could you check out issue #10707 if possible

**Comment by pernielsentikaer** [comment]
We're looking into this issue at the moment 🙂

**Comment by xilopaint** [comment]
This issue seems to be fixed.
