### ISSUE TITLE
[Microsoft Teams Meeting] ...

### ISSUE THREAD

**Issue by chan-vince** [raycast/extensions#10961]
### Extension

https://www.raycast.com/sven/microsoft-teams-calling

### Description

Thanks @svenwiegand for your work on this extension!

I've been using the extension on the new v2 Teams app. However I have an issue where I need to do the approval step every time I use an action, not just the first time.

The 'approval step' is this, from the [docs](https://www.raycast.com/sven/microsoft-teams-calling):

> When executing one of the extension's actions for the first time, while in a meeting, Microsoft Teams will bring up a prompt New connection request for the extension. Allow the extension and you're ready to go!

I have tried restarting Teams and my Mac multiple times, and in my Teams settings, I see this which looks good:

<img width="819" alt="image" src="https://github.com/raycast/extensions/assets/15341873/96447ffd-57bb-4163-b220-1271117ff446">

But it seems like it's not applying - every time I use the extension, I need to approve (and the timestamp above is updated) but it still asks for approval every time. Every action gives me this pop up:

<img width="403" alt="image" src="https://github.com/raycast/extensions/assets/15341873/8c780ae8-c500-45cb-8fb0-23aafa157666">

Teams version: 24033.811.2716.7327 (24033.811.2716.7327)

### Steps To Reproduce

1. Use new Teams app
2. Ensure in the settings for this extension, 'Teams Version' is set to 'New Teams'
3. Start a call (e.g. the Teams test call service)
4. Execute an action; I used mute/unmute
5. Accept the pop up
6. Make another call
7. Observe pop up that I think shouldn't be there

### Current Behaviour

This popup appears on every action, not just the first time:
<img width="403" alt="image" src="https://github.com/raycast/extensions/assets/15341873/c7bd69df-a30c-4e8b-9ef0-ee3f0711c13a">

### Expected Behaviour

Once accepted, the 'New Connection Request' should not appear again.

**Comment by aksvenk** [comment]
Uninstalled and reinstalled the extension and this problem went away. Maybe moving from old to new teams leaves some residual configuration that causes this issue?

**Comment by svenwiegand** [comment]
Thanks for the hint @aksvenk. As far as I've heard, this didn't fix it for all people.

Unfortunately I cannot reproduce the problem and as the API we use of the Teams client isn't officially documented there's some guesswork involved anyway.

Sorry I currently don't have a clue how to help here @chan-vince

**Comment by p4sI** [comment]
Not sure if it helps, but for me reinstalling fixed it as well. 
I used first the classic teams and switched to the new one and had the same issue as described here before.

**Comment by chan-vince** [comment]
> Not sure if it helps, but for me reinstalling fixed it as well. I used first the classic teams and switched to the new one and had the same issue as described here before. Maybe it would be good to add this hint to the docs?

Ok good to hear it works for you - do you mean re-install this specific extension or re-install Raycast?
I've reinstalled this extension and it didn't work for me unfortunately.

@svenwiegand appreciate your input, I understand it's basically impossible to help if you can't reproduce. I'm looking into Raycast extension debugging to see if I can figure anything out..

**Comment by p4sI** [comment]
> Ok good to hear it works for you - do you mean re-install this specific extension or re-install Raycast? I've reinstalled this extension and it didn't work for me unfortunately.


I only reinstalled the extension, not Raycast.

**Comment by rgallo** [comment]
I was hitting this for a while, I reinstalled the extension and restarted both Teams and Raycast and it was still happening, then it suddenly stopped happening without restarting either application.  I'm not sure if that helps or if reinstalling fixed it, but it went away eventually.

**Comment by chan-vince** [comment]
Thanks all for your input. Yesterday suddenly it just started working for me too. I suspect those transparent Teams updates might have fixed something on their end.
And thanks @svenwiegand for your work on this extension, it's great!
