### ISSUE TITLE
[Apple Reminders] Date argument for quick add reminder without AI

### ISSUE THREAD

**Issue by guspimentel** [raycast/extensions#10966]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Since now is possible to quick add a reminder without AI, could it be possible to have a optional date argument only if the "Only use AI" option is unchecked?

### Who will benefit from this feature?

Everyone

**Comment by thomaslombart** [comment]
Unfortunately, it's not possible to do so since arguments are defined in a static way, so I'll mark this issue as not planned 🙂
