### ISSUE TITLE
[Bitwarden Vault] Continuously errors with server URL preference changed

### ISSUE THREAD

**Issue by lhjt** [raycast/extensions#10975]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

I recently updated this extension and noticed that it downloaded its own copy of the bitwarden CLI. I do have a custom URL for my instance. 

Since the update, it now always greets me with this error:

![20240227T171514](https://github.com/raycast/extensions/assets/48422312/aab2ab28-1a45-4a1c-b978-1788d97d2bab)

l have configured the CLI and extension to use my custom instance URL but the error persists. My guess is that the extension has not updated the config for its own internally downloaded bitwarden CLI with the new server URL address. 

I have reinstalled the extension and reconfigured everything, to no avail. I have also tried providing the path to my own bitwarden CLI binary, and the issue persists. 

### Steps To Reproduce

1. Install the extension
2. Configure a custom server URL
3. Try to run the "search vault" command

### Current Behaviour

Explodes with the screenshot in the description

### Expected Behaviour

Should not explode

**Comment by Geezus42** [comment]
Related: https://github.com/raycast/extensions/issues/10977

**Comment by Geezus42** [comment]
I know you already tried specifying the path, but I just pointed the extension to `/opt/homebrew/bin/bw`, and now it's working better than ever.

**Comment by lhjt** [comment]
![20240228T012400-Raycast-](https://github.com/raycast/extensions/assets/48422312/331bf57a-8903-4f30-ac6c-14ac10c72afd)

Unfortunately I am still experiencing the issue with that setting (I just restarted raycast as well):

![20240228T012459](https://github.com/raycast/extensions/assets/48422312/cf78ce75-c254-44cc-8eac-bccaf61dfa13)

**Comment by lhjt** [comment]
Hey @jomifepe thanks for the update - I see that you updated the extension in https://github.com/raycast/extensions/issues/10977#issuecomment-1966831894 and that seems to have solved the problem!

Things are working now. Shall I close this issue?

**Comment by jomifepe** [comment]
Great to hear, I gotta say that I wasn't expecting it to fix this issue, but it shouldn't have broken in the first place, so great 🙂

Thanks for the update!

@raycastbot close this issue
