### ISSUE TITLE
[Port Manager] ...

### ISSUE THREAD

**Issue by angelineflorajohn** [raycast/extensions#10989]
### Extension

https://www.raycast.com/lucaschultz/port-manager

### Description

Ports used by node.js are not being shown in the port manager. I am not sure if this is a bug or should be a feature request. 

<img width="776" alt="SCR-20240227-guad" src="https://github.com/raycast/extensions/assets/25217498/5fe60893-23a3-4501-89de-0d1403f0ecfb">

### Steps To Reproduce

1. Open "Open Ports" on raycast
2. Search for Node or scroll down the list of ports
3. Node is not visible/shown (possible feature request)

### Current Behaviour

not showing all the ports that are in use

### Expected Behaviour

show all the ports that are being used

**Comment by Sheraff** [comment]
@angelineflorajohn I haven't looked at the new code that was pushed as part of the last update to this extension, but before we delve into it: is it possible that in your example, the `node` processes are started by another process which itself does appear on the list? (sometimes it can even be a longer chain than that like "A starts B which starts C"...)

I'm not sure whether this extension is looking for named parent processes (to have something a little informative to show) or if it's just supposed to show *every* process, in which case it might indeed be a bug

**Comment by lucaschultz** [comment]
Hey @Sheraff, the recent update hasn't altered how the processes are viewed: by using `/usr/sbin/lsof +c0 -iTCP -w -sTCP:LISTEN -P -FpcRuLPn`.

Hi @angelineflorajohn! How are you displaying the processes? The extension should present all processes and ports obtained from executing `/usr/sbin/lsof +c0 -iTCP -w -sTCP:LISTEN -P` (the missing option is for formatting). Could you please verify that the port appears after a reboot when manually running the command in the terminal but not in the extension?
