### ISSUE TITLE
[NUMI] ... Querying Numi CLI doesn't work

### ISSUE THREAD

**Issue by alexbet** [raycast/extensions#10986]
### Extension

https://www.raycast.com/andresmorelos/numi

### Description

When I check the "Use numi-cli" checkbox, quering Numi doesn't work. It says that numi-cli is not installed, when in fact it is. It is installed with Homebrew as suggested on the Numi Github page, and the path to the numi file (a symbolic link) is correct. The symbolic link is at

/opt/homebrew/bin/numi-cli

Here are a couple of screenshots of the setting and the result.

<img width="1068" alt="307983515-071f882a-9fd5-403a-b5fe-561c5c59dc31" src="https://github.com/raycast/extensions/assets/3966760/6d0133e9-f2b8-4f05-a71d-6ddff0b6a09a">
<img width="862" alt="307983557-e3c81cc6-8b42-453d-b2cf-117f3c88aeb0" src="https://github.com/raycast/extensions/assets/3966760/64634669-a69d-4d2a-ba90-5baf37bc479e">

I tried uninstalling/installing the extension, the numi-cli, Numi itself, but nothing changed.

### Steps To Reproduce

1. Check the "use numi-cli" option in the extension
2. Try to query Numi

### Current Behaviour

It says that numi-cli is not installed, which is not correct. If I query the numi-cli directly in Terminal, it works fine.

### Expected Behaviour

It should work with the numi-cli.

**Comment by pernielsentikaer** [comment]
I just tested this and downloaded it from brew too, no errors. What does `which numi-cli` in the terminal gives you?

**Comment by alexbet** [comment]
> I just tested this and downloaded it from brew too, no errors. What does `which numi-cli` in the terminal gives you?

That is weird. Here you go:

<img width="1151" alt="Screenshot 2024-02-27 at 1 30 44 PM" src="https://github.com/raycast/extensions/assets/3966760/1f348f0b-1445-41c7-8d84-c886cb3f0f69">

**Comment by alexbet** [comment]
BTW, does it matter that Numi itself is installed? Could that somehow impact the numi-cli? I tried uninstalling Numi the application too, but still getting the error.

**Comment by pernielsentikaer** [comment]
No that should be more than fine, do you know how to debug an extension by forking it? If so I'd like to check it with you 🙂

**Comment by alexbet** [comment]
Unfortunately not. Are there instructions how to do that somewhere? Also, could it be a permissions problem of some kind maybe?

**Comment by pernielsentikaer** [comment]
If you know just a little bit of coding, then you can use the `Fork` action like this

![Raycast 2024-02-28 at 06 43 41](https://github.com/raycast/extensions/assets/38033107/7177c66b-8b8a-41a5-836c-79a445c62c6e)

That will guide you a bit, let me know if that files, then you can open the forked extension and add console.logs to the code and run the code with `npm run dev`

**Comment by alexbet** [comment]
OK, I figured it out. I ran the extension from Raycast, and it worked like that. It turns out there was an error in my .bashrc file which was causing the problem. After correcting that, it started working fine. 

Sorry to bother you and glad that we were able to work this out. Thanks!

**Comment by AndresMorelos** [comment]
@alexbet could you please share your .bashrc to replicate it? I also have Starship prompt but with ZSH, and, it works without issues.

Probably, it's related to https://github.com/starship/starship/issues/5816

**Comment by AndresMorelos** [comment]
BTW, I see here (https://github.com/raycast/extensions/issues/10986#issuecomment-1967358099) that you use ZSH too

Why not use a .zshrc file instead of .bashrc and add

```shell
eval "$(starship init zsh)"
```

**Comment by alexbet** [comment]
The code use is:

eval "$(starship init bash)"

I have no idea why this would be a problem. Anyway, switched to ZSH instead.

**Comment by AndresMorelos** [comment]
> The code use is:
> 
> eval "$(starship init bash)"
> 
> I have no idea why this would be a problem. Anyway, switched to ZSH instead.

I'm not sure why this happened, but it also with the VSCode integrated terminal when it tried to source the .bashrc file, probably something related to the starship prompt for the bash environment. 

Now that you switched to ZSH, is all working as expected? 

Let me know to close this issue.

**Comment by AndresMorelos** [comment]
@alexbet I'll close this issue, feel free to reopen if the issue persists 

@raycastbot close this issue

**Comment by kevinm6** [comment]
@AndresMorelos @pernielsentikaer I’ve encountered the same issue for some weird things in my `.bashrc` file.
Since I use `zsh` daily, could you consider use `--norc` arg to bash?

**Comment by kevinm6** [comment]
> @kevinm6 let me verify this option

Thanks! You should get it free using `/bin/sh`, but maybe in some machine/configuration it doesn't load the **PATH** and in that case can't find the `numi-cli` binary.
