### ISSUE TITLE
[Shortcuts Search] Support for more apps and shortcuts

### ISSUE THREAD

**Issue by AISLVE** [raycast/extensions#10988]
### Extension

https://www.raycast.com/solomkinmv/shortcuts-search

### Description

Hey there maybe add support for more apps and menu items from menubar like paletro or finbar that would be really awesome in my opinion since they both are paid and your app is partially same as them it would be a game changer to be honest

**Comment by solomkinmv** [comment]
@AISLVE The database is in the open source repository. Do you want to try to add it yourself? It should be pretty simple

**Comment by AISLVE** [comment]
oh ok, wait let me check it out also could you please link the repo

**Comment by solomkinmv** [comment]
@AISLVE 

Please see contribution guide for adding new shortcuts [here](https://github.com/solomkinmv/shortcuts-disco/blob/main/README.md#shortcuts-contribution).

Don't hesitate to create PR. There should be tests that validate config automatically.

**Comment by AISLVE** [comment]
thanks @solomkinmv but isn't that too much work or did i miss something in the guide, like can't we somehow get them from the menu bar directly

**Comment by solomkinmv** [comment]
So far I didn't find automatic solution. 
First of all, not all shortcuts are available from the menu bar.
But I think it's possible to extract ones that are in the menu bar. Will try to create some script for this.

**Comment by AISLVE** [comment]
hey, don't mean it in a bad way but how is it different from search menu items extension by raycast

**Comment by solomkinmv** [comment]
This extension supports all the configured shortcuts. If there's something that is not in the menu, the "search menu items extension" will fail to find this action
