### ISSUE TITLE
[Android Debug Bridge (Adb) Commands]

### ISSUE THREAD

**Issue by lidary-byte** [raycast/extensions#10997]
### Extension

https://www.raycast.com/Quentin23Soleil/adb

### Description

Add ability to get current activity

**Comment by quentin23soleil** [comment]
@lidary-byte Hello, could you describe more what you're expecting? 
Something like that `mResumedActivity: ActivityRecord{7f6df99 u0 com.sample.app/.feature.SampleActivity t92}` ?

**Comment by lidary-byte** [comment]
> @lidary-byte您好，您能详细描述一下您的期望吗？ 类似的东西`mResumedActivity: ActivityRecord{7f6df99 u0 com.sample.app/.feature.SampleActivity t92}`？

Yes

**Comment by pernielsentikaer** [comment]
This is now merged
