### ISSUE TITLE
[raindrop.io] Can't search my hashtags? (I.e. #content = no results)

### ISSUE THREAD

**Issue by m0rg5** [raycast/extensions#10996]
### Extension

https://www.raycast.com/lardissone/raindrop-io

### Description

Searching any hashtag returns no results.
I.e. #content

![image](https://github.com/raycast/extensions/assets/8669538/5c4bb7fc-ae21-4fbb-87cf-ee824b6965e7)

### Steps To Reproduce

As per pic

### Current Behaviour

no hashtag results

### Expected Behaviour

Hashtag results

**Comment by sh-cho** [comment]
Hi, you mean tag?

<img width="750" alt="image" src="https://github.com/raycast/extensions/assets/11611397/bcdfbbbb-01a4-4e7a-ae58-9f5d452c8976">

Looks like it's working for me

**Comment by lardissone** [comment]
@m0rg5 what are you expecting to see in the results when you enter the `#` only?

The extension is using Raindrop's API for search, so if it works in Raindrop's app/web, it should work in the extension.

In the app, if I enter just the `#` character, it doesn't returns any result, it only suggests the possible tags you can use for search, but results are not updated:
![20240304_103747@2x](https://github.com/raycast/extensions/assets/59826/3f000295-2ca4-429c-94e8-ddd1e2eae5aa)

We're not displaying autocomplete for search field in the extension.

**Comment by lardissone** [comment]
@m0rg5 maybe because there's an underscore in the tag? What happens if you search for `#_content` ?

![20240304_110349@2x](https://github.com/raycast/extensions/assets/59826/3bb56c13-d7e5-40dc-9965-89ffb94861fa)

Does it works for you in Raindrop's app/web?

**Comment by m0rg5** [comment]
> @m0rg5 maybe because there's an underscore in the tag? What happens if you search for `#_content` ?

Yr suggesting I don't know my own tags?
No, as I've clearly shown, nothing works with "#".

> Does it works for you in Raindrop's app/web?
Yes.

**Comment by m0rg5** [comment]
Ok, just realised tags do show if I search **without** "#", but not with.

**Comment by lardissone** [comment]
> Yr suggesting I don't know my own tags?

No, I'm just refering to your previous messages. In your screenshot you searched by `#content` and in your results I see a link tagged with `#_content`.

**Comment by lardissone** [comment]
Weird, it just works for me using the `#` at the beginning.
![20240304_122013@2x](https://github.com/raycast/extensions/assets/59826/729abb62-b230-44fe-85ed-9a71f25f8006)

It doesn't works for any tag for you using the `#`?

**Comment by m0rg5** [comment]
> It doesn't works for any tag for you using the `#`?

We're still asking? 😂 - again, any search with "#" gives 0 results.

Though, I can search tags without **#** (wouldn't have create this ticket if I realised this).
