### ISSUE TITLE
CDPATH breaks @raycast/api npm postinstall script

### ISSUE THREAD

**Issue by jeremybaumont** [raycast/extensions#10994]
### Description

[Discussed](https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1708990852297729) on the slack community #extensions channel.

Shell environment variable `CDPATH` [affects](https://man7.org/linux/man-pages/man1/cd.1p.html) the behavior of `cd` (change directory) command.

The `ray` shell script invoked by the @raycast/api npm postinstall step, has a logic that will break if the user sets CDPATH with a directory containing a `bin` directory. Especially how the `bin_dir` directory is computed in the `ray` shell script.

**Suggestion**

Use a local current directory reference.
```
bin_dir=$( cd -P ./"$( dirname "$source" )" >/dev/null 2>&1 && pwd )
```

### Steps To Reproduce

1. Create $HOME/bin directory `mkdir $HOME/bin`
2. Set CDPATH in your shell like the following `export CDPATH=$HOME`
3. Run `npm install` on a fresh create extension hello world repository

### Current Behaviour

`npm install` will fail on a fresh create extension hello world repository, if CDPATH is set to a directory containing a `bin` directory because the `npm postinstall` step of the @raycast/api package will fail to determine the `bin_dir` directory correctly.

```
...
npm info run @raycast/api@1.68.1 postinstall node_modules/@raycast/api bin/ray npm-post-install
npm info run @raycast/api@1.68.1 postinstall { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 582ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:i Completed in 16021ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/Users/jbaumont/.config/local/share/mise/installs/node/20.11.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
npm verb stack     at ChildProcess.emit (node:events:518:28)
npm verb stack     at maybeClose (node:internal/child_process:1105:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm verb pkgid @raycast/api@1.68.1
npm verb cwd /Users/jbaumont/code/raycast/hello-world
npm verb Darwin 23.3.0
npm verb node v20.11.1
npm verb npm  v8.19.4
npm ERR! code 1
npm ERR! path /Users/jbaumont/code/raycast/hello-world/node_modules/@raycast/api
npm ERR! command failed
npm ERR! command sh -c -- bin/ray npm-post-install
npm ERR! Fail parsing version
npm verb exit 1
npm timing npm Completed in 16065ms
npm verb unfinished npm timer reify 1708990249985
npm verb unfinished npm timer reify:build 1708990264565
npm verb unfinished npm timer build 1708990264565
npm verb unfinished npm timer build:deps 1708990264565
npm verb unfinished npm timer build:run:postinstall 1708990264568
npm verb unfinished npm timer build:run:postinstall:node_modules/@raycast/api 1708990264568
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jbaumont/.npm/_logs/2024-02-26T23_30_49_941Z-debug-0.log
```

### Expected Behaviour

`npm install` succeed.

**Comment by grzegorzkrukowski** [comment]
Thanks for reporting this problem, @jeremybaumont. We have updated the script, and the issue should be resolved in the next API version 1.69.1, which will be released today or tomorrow.
