### ISSUE TITLE
[Arc] ... Tab to search in [webapp]

### ISSUE THREAD

**Issue by davidevignozzi** [raycast/extensions#10990]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

"⌥⇧A" to open raycast shortcut to search for something in arc, i type YouTube "Tab" and nothing. I have to open arc and repeat the search there. Or open youtube and search.

<img width="862" alt="Screenshot 2024-02-27 alle 16 33 20" src="https://github.com/raycast/extensions/assets/73885963/0c258d2b-5d41-4eda-a41f-b42b3f63c639">

On arc you can press "Tab" to search for something on YouTube ChatGPT etc...  (I love this feature)

<img width="772" alt="Screenshot 2024-02-27 alle 16 23 33" src="https://github.com/raycast/extensions/assets/73885963/51d7de4b-ee17-4a42-840d-7c8472eadb3f">

### Who will benefit from this feature?

10x productivity, speed and focus with this feature even in raycast. Assured. I really hope it will come and I think like me many others.

**Comment by xilopaint** [comment]
You can't have an Arc's Command Bar behavior in Raycast without AppleScript support.

**Comment by omar-salama** [comment]
> Can't you use Quicklinks to do that?

a more annoying behavior is that opening a link from quicklinks that's a pinned/favorited tab opens it in a new tab.
