### ISSUE TITLE
[Google Translate] Can simultaneous multiple translations be added for quick translate? Possibly also with voice listen?

### ISSUE THREAD

**Issue by jewenso** [raycast/extensions#11008]
### Extension

https://www.raycast.com/gebeto/translate

### Description

Can multiple translations be added for quick translate? Possibly also with voice listen?

**Comment by rasitayaz** [comment]
what do you mean by multiple translations? quick translate can already translate the entered text to selected multiple languages.

**Comment by rasitayaz** [comment]
yeah, quick translate can do this already, you just need to adjust the languages you want to translate to using the top right dropdown.

**Comment by jewenso** [comment]
I see you can set multiple languages sets in the right dropdown, but I can't see any option to translate multiple languages simultaneously and view them all together.

**Comment by jewenso** [comment]
Sorry I finally found the way to add them, thanks. Regarding translations voice listen is there any chance you can add that feature?

**Comment by rasitayaz** [comment]
I'm not interested in implementing such feature, sorry

**Comment by gebeto** [comment]
@jewenso do you mean text to speech? or speech to text?

Few days ago text to speech was added by @strikerlulu , so I'll be able to add this feature to `quick translate` on this weekends

**Comment by jewenso** [comment]
Thanks for the reply. Yes, I meant text to speech feature for the translations. But are you talking about the extension Google Translate or another?
