### ISSUE TITLE
[Timers] timer not showing in menu bar

### ISSUE THREAD

**Issue by Oneechan69** [raycast/extensions#11014]
### Extension

https://www.raycast.com/ThatNerd/timers

### Description

I looked at this issue and I checked for the following:
- I have the setting to show the menu bar icon to always, and have the setting on to show raycast's icon in the menu bar
- When I start multiple timers I don't see any of them in the menu bar
- I don't have any apps to hide menu bar icons from running
<img width="658" alt="Screenshot 2024-02-28 at 3 20 03 PM" src="https://github.com/raycast/extensions/assets/42647030/d6a68696-7a65-497f-983c-d493c41bcfa3">

### Steps To Reproduce

None

**Comment by ThatNerdSquared** [comment]
Hi @Oneechan69, thanks for using Timers!

Hmm, that's weird. Thanks for providing the information about the common debugging paths - that's helpful. Couple more questions:
- When you run the "Timers Menu Bar" or "Stopwatch Menu Bar" command, does it show any errors?
- Do other menu bar commands for other Raycast extensions work for you?
- Do you remember any specific days/times when you faced this issue? (in case I can look back through extension error logs and find something useful)

**Comment by Oneechan69** [comment]
- Where would I see any errors?
- Which other extensions should I try?

**Comment by ThatNerdSquared** [comment]
@Oneechan69 

- There might be a red icon next to the words "Menu Bar Command" when you run the command
<img width="744" alt="Screenshot 2024-02-29 at 09 53 43" src="https://github.com/raycast/extensions/assets/72814106/20d7108c-2174-4665-8322-5db0c9b35fde">

- Weather or GitHub are easy ones that both have menu bar commands you can test

**Comment by Oneechan69** [comment]
@ThatNerdSquared I got the menu bar item now with "Timers Menu Bar", but now the timer only updates when I click on the icon and doesn't when I unclick it.

**Comment by ThatNerdSquared** [comment]
@Oneechan69 does it update every 10 seconds or so? It's set to update on a 10-second interval - I can't set it to update at a 1-second interval due to Raycast API limitations.

**Comment by ArtFlag** [comment]
I have the same issue and the timer **only** shows up in the menu bar of my external monitor, never in the menu bar of my laptop, regardless of whether my monitor is plugged in or not.

**Comment by Oneechan69** [comment]
You should make a separate issue for it.
