### ISSUE TITLE
[OpenAI GPT] GPT4Turbo

### ISSUE THREAD

**Issue by rowesk** [raycast/extensions#11025]
### Extension

https://www.raycast.com/simicvm/openai-gpt

### Description

Hey guys — would love the new 'gpt-4-turbo-preview' model to be added into the extension if that's possible? 🙏

### Who will benefit from this feature?

Everyone — more recent training data on a faster and cheaper model would benefit most of the people who currently use 'gpt4' or 'gpt-4-1106-preview'

**Comment by zaaahir** [comment]
Bump

**Comment by simicvm** [comment]
> Bump

I'll add it in the next 24h

**Comment by simicvm** [comment]
PR up here https://github.com/raycast/extensions/pull/11339
