### ISSUE TITLE
[Jira Search (Self-Hosted)] ...

### ISSUE THREAD

**Issue by arabshapt** [raycast/extensions#11026]
### Extension

https://www.raycast.com/emanguy/jira-search-self-hosted

### Description

Search of the story should be filtered down by project name. In settings I would also make it possible to set default project, because most people work on a single project(one could make it possible to switch between them easily(later)).
And search results are not shown in the expected order(or are not filtered the right way). Is the problem on jira side? How can we still have this problem in the world where fzf exists?!:) 
Thank you for this plugin!

**Comment by marinsokol** [comment]
@arabshapt Could you explain a bit, what is expected ordering for search results?
