### ISSUE TITLE
[Obsidian] Bookmark notes command doesn't show bookmarks inside folders in bookmarks tab

### ISSUE THREAD

**Issue by migui3230** [raycast/extensions#11020]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

when i use the bookmarked notes command, it only shows me the notes that are not inside folders in the bookmarks tab

<img width="1083" alt="image" src="https://github.com/raycast/extensions/assets/74937076/1dda39de-cd17-44b4-86d6-90d959d9dd19">

### Steps To Reproduce

1. open raycast
2. make sure to have bookmarked notes inside folders in the bookmarks tab in your obsidian vault
3. use the bookmarked notes command

### Current Behaviour

only shows notes not in folders in the bookmarked notes list

### Expected Behaviour

show all bookmarked notes whether they are in a folder or not in the bookmarks tab

**Comment by KevinBatdorf** [comment]
Thanks for reporting! PR is here: https://github.com/raycast/extensions/pull/11062
