### ISSUE TITLE
[GitHub -> Notifications] Distinct visually read and unread notifications

### ISSUE THREAD

**Issue by teziovsky** [raycast/extensions#11035]
### Extension

https://www.raycast.com/raycast/github

### Description

It would be great to visually distinguish the read and unread notifications. At the moment there is a list section with `read` and `unread`, but it could be more visible. You know, quick look and you know what is what right away.

Some examples:
- the colors of icons could be different, like `orange` for unread, and `green` for read,
- the text of the read notification could be `gray`, and the unread notification could be `white`

**Comment by thomaslombart** [comment]
Good idea! Do you want to actually look at it?

**Comment by teziovsky** [comment]
I'm confident in my ability to enhance it, but I'd like your input on which example you find more preferable 🤔 Alternatively if you have any other suggestions for resolving this, I'm open to hearing them 🤔

**Comment by thomaslombart** [comment]
I think I'll go for shades of gray here as `orange` and `green` may be too distracting.

**Comment by teziovsky** [comment]
I think it's not able to implement. I mean shades of gray in `List.Item` `title`. The `title` could only get `value` and `tooltip` props 🤔

**Comment by xilopaint** [comment]
I think this would create immense confusion. The colors of these icons on GitHub UI reflect the statuses of issues and PRs: issues can be open, closed, or not planned (green, purple, and gray), and PRs can be open, closed, or merged (green, red, and purple).

Anything different from this pattern would be counterintuitive and a big mistake.

Also, the Unread and Read sections already clearly communicate the status of the notifications.

The key question is whether we should color the icons according to the correct GitHub pattern. In my view, yes, we should. This way, if I have a purple PR icon in the Unread section, I know that I'm being notified about a merged PR. This adds real information to the UI.

**Comment by teziovsky** [comment]
> I think this would create immense confusion. The colors of these icons on GitHub UI reflect the statuses of issues and PRs: issues can be open, closed, or not planned (green, purple, and gray), and PRs can be open, closed, or merged (green, red, and purple).
> 
> Anything different from this pattern would be counterintuitive and a big mistake.
> 
> Also, the Unread and Read sections already clearly communicate the status of the notifications.
> 
> The key question is whether we should color the icons according to the correct GitHub pattern. In my view, yes, we should. This way, if I have a purple PR icon in the Unread section, I know that I'm being notified about a merged PR. This adds real information to the UI.

Agree with that.

**Comment by thomaslombart** [comment]
Yeah, I meant using `Color.SecondaryText` for the read section as the gray color is less visible.

![github 2024-03-04 at 12 34 14](https://github.com/raycast/extensions/assets/16003285/05ffb103-21c5-410f-b5ae-cbff5273ab01)

But applying the real colors as done on GitHub's UI is a great idea as well. I'm fine with both 🙂

**Comment by xilopaint** [comment]
@thomaslombart @pernielsentikaer I think this PR can be closed as #11653 has been merged and the OP agrees with the solution.
