### ISSUE TITLE
[Spotify Controls] - Returns Spotify not installed 

### ISSUE THREAD

**Issue by timcastillogill** [raycast/extensions#11032]
### Extension

https://www.raycast.com/thomas/spotify-controls

### Description

Spotify Controls are returning a `Spotify is not Installed` message. I have Spotify installed and it is Spotify Premium

I have tried:

1. Uninstalling Spotify App with Spotify Controls installed
2. Uninstalling Spotify Controls with Spotify App installed

### Steps To Reproduce

1. Install Spotify Controls
2. Install Spotify App
3. Login to premium account
4. Attempt to use a command e.g. Play
5. Receive message `Spotify is not installed`

**Comment by timcastillogill** [comment]
Update on this - once the computer was restarted it works as expected.

**Comment by ttiimmothy** [comment]
I have restarted the computer and it still mentions spotify is not installed.
