### ISSUE TITLE
`Form.Dropdown#onChange` not called if `value` set to an invalid value

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#1104]
Raycast version:

## Description

The following code results in `onChange` to never get called when an item is selected from the dropdown.

## Steps To Reproduce

```js
const [value, setValue] = useState('invalid value');

return (
	  <Form.Dropdown value={value} onChange={newValue => {
	    console.log('called!');
	    setValue(newValue);
	  }}>
	    <Form.Dropdown.Item value="bar" title="Bar" />
	    <Form.Dropdown.Item value="baz" title="Baz" />
	  </Form.Dropdown>
);
```

## The current behavior

`onChange` is never called.

## The expected behavior

`onChange` should get called or a runtime error should be thrown.

**Comment by mattisssa** [comment]
Thank you for creating the issue! We will take a look at the `onChange` behaviour issue and will think about how to warn developers about the case.
