### ISSUE TITLE
[Apple Mail] Message action "Move to Archive"

### ISSUE THREAD

**Issue by phajy** [raycast/extensions#11040]
### Extension

https://www.raycast.com/yug2005/mail

### Description

Could a "Move to Archive" option be added, like "Move to Trash" and "Move to Junk"?

### Who will benefit from this feature?

Anyone who frequently moves new mail to an Archive folder after a quick read.

### Anything else?

It looks like the code is there for detecting the Archive folder in `extensions/mail/src/utils/mailbox.ts` and `extensions/mail/src/scripts/messages.ts` could be updated to include a `moveMessageToArchive` command in a similar way.

Love this extension. Thanks to the developers!

**Comment by Luk4h** [comment]
Hello @pernielsentikaer, can you close this issue? It is solved from the pull request you merged. Thanks!
