### ISSUE TITLE
[Jira] It would be great if we can use the jira token instead of the wepApp login page.to avoid having to request admin access 

### ISSUE THREAD

**Issue by Pierre-Mike** [raycast/extensions#11047]
### Extension

https://www.raycast.com/raycast/jira

### Description

as of now to add jirta you need to login using web

### Who will benefit from this feature?

All contractors that are not part of the company and don't want to got though all the paper works. to request RAYCAST

**Comment by erlandsen-tech** [comment]
I second this feature. We have self hosted jira, so I would love to be able to select server and use token with this extension.

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/10185, so I'll mark it as such.
