### ISSUE TITLE
[SM.MS] ➕返回markdown格式链接🔗功能

### ISSUE THREAD

**Issue by hhr114** [raycast/extensions#11055]
### Extension

https://www.raycast.com/koinzhang/sm-ms

### Description

Hi，
Great work!
May you please add a function that one can get the format of markdown link back instead of url?
i.e., return `![](url)`
Thanks for your great work!

### Who will benefit from this feature?

someone who write blog with md and Raycast

**Comment by koinzhang** [comment]
Hi @hhr114. Thanks for the feedback, I've submitted a PR #11852 to add a setting to allow you to choose the form of the copied link!

**Comment by koinzhang** [comment]
@raycastbot close this issue
