### ISSUE TITLE
[Browser Bookmarks] Fails when using 2 different computeurs with Firefox profiles in diferent directories

### ISSUE THREAD

**Issue by czj** [raycast/extensions#11058]
### Extension

https://raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: ENOENT: no such file or directory, scandir '/Users/czj/Library/Application Support/Firefox/Profiles/1eflte2l.default'
    at readdirSync (node:fs:1513:3)
    at /Users/czj/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:39:53692
    at Array.filter (<anonymous>)
    at p5 (/Users/czj/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:39:53613)
    at async /Users/czj/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:58:231
```

### Steps To Reproduce

On MacOS 14.3.1 (23D60) with Firefox 123 and Raycast 1.68.1 the Browser Bookmark sync memorized the URL of the Firefox profile on one machine, but that directory differs on each machine.

On one machine `~/Library/Application Support/Firefox/Profiles/1eflte2l.default`

On the other one `~/Library/Application Support/Firefox/Profiles/5abefe5l.default`

### Current Behaviour

The same directory seems to be expected on each machine.

### Expected Behaviour

Each machine's profile storage directory needs to be different and remembered

**Comment by thomaslombart** [comment]
That's surprising as we don't cache that between Macs. Could you run the command below on both of your Macs and let me know the result?

```
cat ~/Library/Application\ Support/Firefox/profiles.ini
```

**Comment by czj** [comment]
Firefox Sync is used to sync profiles.
