### ISSUE TITLE
[Apple Reminders] Create reminder crashes with TypeError

### ISSUE THREAD

**Issue by Tatgat** [raycast/extensions#11057]
### Extension

https://www.raycast.com/raycast/apple-reminders

#### Error:
```
TypeError: t?.find is not a function

Nd:create-reminder.tsx:59:37

---
56:   mutate?: MutatePromise<{ reminders: Reminder[]

### Steps To Reproduce

1. Configure 'Create reminder' as crl+Q
2. Input shortcut to create a new reminder
3. Error "Something went wrong' occur

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by RayBB** [comment]
Also reported in [this comment](https://github.com/raycast/extensions/issues/10112#issuecomment-1974755497).

**Comment by thomaslombart** [comment]
I've shipped a fix, so the extension should work within a couple of hours. Please note that you can manually get updates by running `Check for Extension Updates`.
