### ISSUE TITLE
[Apple Reminders] Can't Create Reminder, Error Message Shown

### ISSUE THREAD

**Issue by aicayzer** [raycast/extensions#11071]
### Extension

https://www.raycast.com/raycast/apple-reminders

#### Error:
```
TypeError: t?.find is not a function

Nd:create-reminder.tsx:59:37

---
56:   mutate?: MutatePromise<{ reminders: Reminder[]

### Steps To Reproduce

Run "Create Reminder Command"

### Current Behaviour

"Something went wrong" shown

See GIF here:
![Arc (Screenshot 001638)](https://github.com/raycast/extensions/assets/22304629/027708e4-e59f-4140-a773-0602645e16ab)

### Expected Behaviour

UI for inputting command

**Comment by irangarcia** [comment]
Should be fixed in a couple of hours, as Thomas said [here](https://github.com/raycast/extensions/issues/11057#issuecomment-1975140959)

**Comment by irangarcia** [comment]
Should work in a couple of hours, as Thomas said [here](https://github.com/raycast/extensions/issues/11057#issuecomment-1975140959)

**Comment by irangarcia** [comment]
@raycastbot close this issue
