### ISSUE TITLE
[Prism Launcher] The extension is not recognising my Prism Launcher

### ISSUE THREAD

**Issue by Imzxhir** [raycast/extensions#11074]
### Extension

https://www.raycast.com/lockieluke3389/prism-launcher

### Description

This extension doesn't seem to recognise my Prism Launcher app or my prism launcher instance folder even though the path is created and there are instances in that folder.

Screenshot:
![image](https://github.com/raycast/extensions/assets/98621617/fe283540-5693-448a-8ddb-72ff61cb0475)

### Steps To Reproduce

1. Download the Prism Launcher Extension
2. Make sure you have some instances downloaded or created in Prism Launcher
3. Try to launch an instance from Raycast
4. You will see that Raycast cannot find your Prism Launcher app or it cannot find your instances

### Current Behaviour

It doesn't recognise you have Prism Launcher installed or that you do not have instances in the Prism Launcher instance folder.

### Expected Behaviour

The extension should recognise that you have Prism Launcher installed and that you have instances downloaded in the Prism Launcher instance folder.

**Comment by lockieluke** [comment]
Where do you have your Prism Launcher installed

**Comment by Imzxhir** [comment]
I have Prism Launcher installed at `/Users/zahir/Applications/Prism Launcher.app`.

**Comment by lockieluke** [comment]
The default Prism Launcher naming scheme is `PrismLauncher.app` as far as I know so just rename your instance to that

**Comment by lockieluke** [comment]
My fault, they did actually change it to `Prism Launcher.app` after `8.0`, working on a fix
