### ISSUE TITLE
[Image Host] Upload image from clipboard

### ISSUE THREAD

**Issue by hhr114** [raycast/extensions#11070]
### Extension

https://www.raycast.com/efeclk/image-host

### Description

Upload image from clipboard, plz.  like another extension `SM.MS`

### Who will benefit from this feature?

every one who use installed this extension

**Comment by clkefe** [comment]
Hey @hhr114! Thanks for your suggestion. I will definitely look into that and add it in a week or so. Do you have any other suggestions?

**Comment by pbocek** [comment]
hey @clkefe is it possible to add this feature? I could really benefit from that, thanks!
