### ISSUE TITLE
[Browser Bookmarks] sometimes opens random bookmarks

### ISSUE THREAD

**Issue by JhonnyAxe** [raycast/extensions#11088]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

I represented the issue in this video:

https://github.com/raycast/extensions/assets/84262172/624bf48f-6d64-46dc-85d9-49c41a94ac94

### Steps To Reproduce

1. Open th extension
2. Pick any bookmark
3. Press "enter"

It also happens while searching any bookmark

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue #10642, so I'll mark it as such.
