### ISSUE TITLE
The Gitlab extension errors when I search for an MR when selected `All` in the dropdown

### ISSUE THREAD

**Issue by aizaz-shahid** [raycast/extensions#11084]
### Extension

https://www.raycast.com/tonka3000/gitlab

### Description

When I select `All` in the dropdown, the extension errors without an informative error saying `Could not fetch Merge Requests: Error: [object Object]`. This might be because in case of `All` it needs to search a lot more MRs compared to the ones `created by me` for example.

### Steps To Reproduce

1. Open raycast and run search merge requests command from the gitlab extension
2. Select All from the dropdown
3. Type the search term in the search bar
4. You can copy the error after a while of loading. This will be the error: `Could not fetch Merge Requests: Error: [object Object]`

**Comment by macbookandrew** [comment]
@aizaz-shahid is this gitlab.com or a self-hosted instance
