### ISSUE TITLE
[Static Marks - Bookmark Search] Be able to adjust yml within raycast

### ISSUE THREAD

**Issue by BuruY** [raycast/extensions#11081]
### Extension

https://www.raycast.com/aerobless/static-marks

### Description

It would be great if we can add or remove bookmarks from within Raycast

**Comment by aerobless** [comment]
Yes that'd be neat, but I think it'll only work if you host the static marks file locally. Personally I use a remote file that I edit via GitHub.. so I won't be working on this. But if anyone else wants to build it I'd be happy to help review the code.
