### ISSUE TITLE
[Arc] Quickly using Alias to search sometimes misses keystrokes.

### ISSUE THREAD

**Issue by truongio** [raycast/extensions#11087]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

When typing an alias followed by space and then quickly type another key, the key is not registered in Raycast. This happens when you’re quick with your typing. For example, open Raycast => type alias (e g `a` to search Arc History) => hit space => type ``t. `t` is not registered. See video and the registered keystrokes using KeyCastr. I’ve also tried it with some other alias for searching Slack conversations and the same behavior happens there. I have a hard time reproducing it using the Search Files extension, though, so not all extensions might be affected.

https://github.com/raycast/extensions/assets/28986412/bbcc2934-deb4-446b-abad-f8285288a58b

### Steps To Reproduce

1. Hit hotkey to open Raycast, in my cast Cmd + Space
2. Type alias `a`
3. Hit space
4. Type another character, in my case `t`

The `t` won't register. Do these steps relatively quickly.

**Comment by trevoreyre** [comment]
I'm seeing this issue as well. I have the arc extension mapped to a global hotkey, and fairly regularly miss the first few keystrokes when I invoke it.
