### ISSUE TITLE
Memos - Re-direct to memo on latest version of Memos is failing

### ISSUE THREAD

**Issue by erauner12** [raycast/extensions#11098]
### Extension

https://www.raycast.com/JakeYu/memos

### Description

The latest (`stable`) image Memos is failing to properly open a memos after submitting it. I have an idea of why:

```bash
curl -X POST https://<memos host>/api/v1/memo \
-H "Content-Type: application/json" \
-H "Authorization: Bearer <api key>" \
-d '{"content": "hello world", "visibility": "PRIVATE"}'
```

```json
{
  "id": 1054,
  "name": "HKnjp6npoxW26WGrwSN3Ah",
  "rowStatus": "NORMAL",
  "creatorId": 1,
  "createdTs": 1709579295,
  "updatedTs": 1709579295,
  "displayTs": 1709579295,
  "content": "hello world",
  "visibility": "PRIVATE",
  "pinned": false,
  "creatorName": "erauner",
  "creatorUsername": "erauner",
  "resourceList": [],
  "relationList": []
}
```

The memo being opened is trying to open with `id` which is no longer how it works. Now the memo has a unique id which is the value of the `name` key.

ex:

https://host/m/HKnjp6npoxW26WGrwSN3Ah

### Steps To Reproduce

Command: `Send Memo Form`

Put some content in, `cmd+enter` to `Submit Form`

Opens link, does not exist. Get a 403 page:

https://host/403

### Current Behaviour

Opens url like:

https://host/m/id
ex:
https://<host>/m/1054

then re-directs to:

https://host/403

### Expected Behaviour

I'm taken to the newly created memo by the correct id:

ex:

https://host/m/name

https://host/m/HKnjp6npoxW26WGrwSN3Ah

**Comment by JakeLaoyu** [comment]
#11101
