### ISSUE TITLE
[Google Chrome] Combine search Tabs and History

### ISSUE THREAD

**Issue by testerez** [raycast/extensions#11090]
### Description

I guess I'm not the only one to open the same tab multiple times because it's faster to create a new one than checking if I already have it opened or not. This is why I was excited when I discovered the `Search Tabs` command.
Though, I realise it's pretty common for me to search for an open tab which is not actually open yet. When this happens, this is a bit frustrating and defeats the purpose of the command (for my use case at least).
The ideal solution for me would be to show an option to open a new tab if the one I'm looking for is not already opened.
I figured a way to do this would be to combine `Search Tabs` and `Search History` in the same command.
Basically this would just show the open tabs first then history. That way, I could seamlessly open a website regardless of it being already opened in a tab or not. A bit like it does when you open an app after all. 

If I missed a feature that would already cover this use case, please let me know!

### Who will benefit from this feature?

I believe this feature makes sense and would benefit many users because it unifies the behaviour between opening an app or a website.

**Comment by mathieudutour** [comment]
Seems like this issue is about a specific extension, not the API. Would you mind opening a new issue using the [correct template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the authors of the extension are properly aware of it?

**Comment by testerez** [comment]
Done: https://github.com/raycast/extensions/issues/11202
