### ISSUE TITLE
[KeePassXC] General security note

### ISSUE THREAD

**Issue by imkebe** [raycast/extensions#11107]
### Extension

https://www.raycast.com/zkytech/keepassxc

### Description

First of all, it's worth saying thank you for your contribution!
However I would raise an important issue in terms of security. The architecture of this extension is in my opinion, it negates the assumptions that Keepass* should have.

My main objective is that it's not using the HTTP server that is exposed by the open Keepass* app, which is should instead. That should works similar to the Browser extension that query the Keepass* to obtain the credentiials when the database is unlocked in Keepass*.

Instead the extension stores the:
1. Location of the database
2. Password

Keepass* database password shoudn't be saved anywhere other than the user's memory. If the Raycast has an vulnerability there will be an easy way of gaining access to the database. In fact i can image targeted attack on Raycast.

### Steps To Reproduce

1. Install the extension
2. Configure the extension

**Comment by zkytech** [comment]
1. Is there any http api to get account list ? or search by keyword ?
2. `If the Raycast has an vulnerability there will be an easy way of gaining access to the database. In fact i can image targeted attack on Raycast.` . Why http api can avoid this ?
3. In theory, there are indeed some methods that can give you a stronger sense of security, but I don't have time to implement them. Anyway, Pull requests welcome.

**Comment by Sulfyderz** [comment]
Hello @imkebe,

>> if the Raycast has an vulnerability there will be an easy way of gaining access to the database. In fact i can image targeted attack on Raycast. 

>Why http api can avoid this ?

I agree with @zkytech. However @imkebe, I understand your concern. Whenever I export my Raycast config file, I always erase the password saved in the extension before. If you can propose an alternative, feel free to do a PR. Unfortunately, I don't have time as well.

**Comment by imkebe** [comment]
The main difference is that the database is only accesible then user unlock the database while with the extension it's always accesible. I know that http api has also needs to be authenticated by exchanging some credentials - however this is not the master password.

I just wanted to point those security issues to the community.
