### ISSUE TITLE
[Memos] Newline in between each tag appended to Memo

### ISSUE THREAD

**Issue by erauner12** [raycast/extensions#11118]
### Extension

https://www.raycast.com/JakeYu/memos

### Description

Could you append a newline in between each tag appended to Memo?

ex:

current:
`content` #tag1 #tag2

desired:

`content`
#tag1
#tag2

### Who will benefit from this feature?

Anyone creating memos often. Especially with codeblocks as the primary content.

### Anything else?

lmk if any questions

**Comment by JakeLaoyu** [comment]
@erauner12 You can use Send Memo Form command to input text. Use shift+enter to add new line.

**Comment by JakeLaoyu** [comment]
@erauner12 This is too personalized. Some people like to add a line, while others do not. We are just following the format of usememo.
