### ISSUE TITLE
[ChatGPT Quick Actions] Error 429

### ISSUE THREAD

**Issue by lemonbottle** [raycast/extensions#11113]
### Extension

https://www.raycast.com/alanzchen/chatgpt-quick-actions

### Description

Getting this error since a few days ago:

![image](https://github.com/raycast/extensions/assets/29664408/55d74c3a-2153-4209-a243-50b3e5e95e01)

I made sure my API key is still active. 

### Steps To Reproduce

1. Select some text
2. Run any ChatGPT Quick Actions command

**Comment by alanzchen** [comment]
Is this a consistent error? If not, it's probably just some hiccups on the OpenAI side.
