### ISSUE TITLE
[Todoist] "Postpone" action in the Panel

### ISSUE THREAD

**Issue by brunocbreis** [raycast/extensions#11129]
### Extension

https://www.raycast.com/doist/todoist

### Description

The Todoist app has a "Postpone" feature for when you have a recurring task (say, weekly) and you want to skip this week's occurrence. This is different than just completing it, because then it doesn't count as done in your stats, and definitely different than deleting it, because it doesn't affect future repetitions.

I think this would be a nice action to have in the panel!
 

### Who will benefit from this feature?

Procrastinators 😄

**Comment by thomaslombart** [comment]
Todoist unfortunately doesn't have an API endpoint to do so. We could implement a custom solution, but this might be a bit complex and would likely differ from Todoist's functionality. Let's maybe ask them if they intend to ship support for that feature in their API.
