### ISSUE TITLE
[Obsidian] Cannot use any search function

### ISSUE THREAD

**Issue by clement-barbet** [raycast/extensions#11128]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

#### Error:
```
Error: Could not communicate with command worker


```

I'm left with this error, without any further notice.
Reinstalled Raycast and Obsidian to latest version.

### Steps To Reproduce

1. Use search function

**Comment by KevinBatdorf** [comment]
Just curious. About how many notes do you have? I wonder if it's a memory issue.

**Comment by clement-barbet** [comment]
521 notes
