### ISSUE TITLE
[Perplexity] ...

### ISSUE THREAD

**Issue by exezbcz** [raycast/extensions#11138]
### Extension

https://www.raycast.com/third774/perplexity

### Description

The "pro search" would be an optional setting in the Raycast Perplexity extension that automatically enables advanced search capabilities when using the Perplexity search engine through Raycast. By default, this mode would be turned on to provide a powerful search experience without requiring additional user input or configuration.

### Who will benefit from this feature?

power users that have perplexity pro

### Anything else?

<img width="525" alt="image" src="https://github.com/raycast/extensions/assets/90852205/9c2dd826-e443-49f2-883b-9455c3428ad1">

**Comment by yangwao** [comment]
I would like to vote for this as well, or at least would like to know where I can set copilot default on as parameter is `&copilot=true`

**Comment by xilopaint** [comment]
> or at least would like to know where I can set copilot default on as parameter is `&copilot=true`

There's a "Fallback with Copilot enabled" option in Settings.
