### ISSUE TITLE
[Swift Package Index] Extension doesn't show any results

### ISSUE THREAD

**Issue by maximkrouk** [raycast/extensions#11132]
### Extension

https://www.raycast.com/maximkrouk/swift-package-index

### Description

swiftpackageindex.com APIs have been updated, and the search endpoint now needs an API key.

I haven't found a way to obtain this key yet. Maybe @daveverwer can assist with this. I guess the update will require adding extension settings for users to input their keys. However, since it's unclear how to obtain one, users may give up on setting it up. So, it would be cool to find out if it is not necessary 🌚

> For the issue reviewer:
> _You may assign this issue to me and @japanese-goblinn_

### Steps To Reproduce

1. Install the extension from the store
2. Run "Search Packages" command
3. Enter any query (for example: "swift-composable-architecture")
4. See `"No results"` label
5. See `"<DOCTYPE HTML..."` error at the bottom

### Current Behaviour

Extension shows `"No results"` for any query
Extension fails with `"<DOCTYPE HTML..."` error

### Expected Behaviour

Extension shows corresponding results

**Comment by daveverwer** [comment]
Hi @maximkrouk! We'd love to chat about this, if that's OK.

If you use Discord, could we have a quick chat there about API keys? You can find the invite link in [our readme](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server). Once you're there, I'll invite you to a three way conversation with both of us and Sven.
