### ISSUE TITLE
[Ollama] Missing first two words of each response

### ISSUE THREAD

**Issue by DaniEnsi** [raycast/extensions#11141]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

<img width="820" alt="image" src="https://github.com/raycast/extensions/assets/74594229/743c05e9-57fc-403c-8580-5fff17cfb5ac">
<img width="837" alt="image" src="https://github.com/raycast/extensions/assets/74594229/95c2415c-31e3-45ba-a3f5-76bd8f254e23">

### Steps To Reproduce

1. Run any model, strart is missin

**Comment by validatedev** [comment]
I have tried with models gemma:2b and mistral:latest, same issue.

**Comment by MassimilianoPasquini97** [comment]
Fixed in https://github.com/raycast/extensions/pull/11223. Thanks @almoce for his help.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue
