### ISSUE TITLE
[Steam] Search games locally

### ISSUE THREAD

**Issue by canadaduane** [raycast/extensions#11143]
### Extension

https://www.raycast.com/KevinBatdorf/steam

### Description

While an API call out to the network is handy in a few cases, what I'd really like is a Steam game launcher--wouldn't it be nice to run a fav game that's already locally installed via Raycast? I want to be able to type "play qud" and instantly it shows me an icon of Caves of Qud in the search results (loaded locally from the list of games Steam.App has cached somewhere on my hard drive) and I press enter to play the game.

### Who will benefit from this feature?

Everyone who plays Steam games! :)

**Comment by KevinBatdorf** [comment]
I like this idea but I'm not sure if we can get a list of installed games. 

You could type in the game name and press %k to select the "Launch Game" action. And I could add a keyboard shortcut for that.

> from the list of games Steam.App has cached somewhere on my hard drive

Do you know where that is?

**Comment by canadaduane** [comment]
Here's what I see locally: <img width="200" alt="image" src="https://github.com/raycast/extensions/assets/129/58b1a4fa-260f-4c5e-8541-5d6c66951d44">

**Comment by KevinBatdorf** [comment]
Can you tell me what's in here for you? Run this command:

```sh
ls -la ~/Library/Application\ Support/Steam/SteamApps/common
```

I think Steam might put all the games in there, but your screenshot implies maybe not. Is Caves of Qud also in there?

**Comment by canadaduane** [comment]
<img width="515" alt="image" src="https://github.com/raycast/extensions/assets/129/d78fa9d5-ffff-4b77-8373-e875bd544606">
