### ISSUE TITLE
[Dropbox] fails to authenticate

### ISSUE THREAD

**Issue by sheatsb** [raycast/extensions#11140]
### Extension

https://www.raycast.com/chyroc/dropbox

### Description

Extension's auth app is pending review at Dropbox rendering it useless.

### Steps To Reproduce

1. Open Raycast
2. Trigger the Dropbox File Search command
3. Click "Sign In with Dropbox"
4. Browser opens to attempt to authenticate your Dropbox account

### Current Behaviour

Error: 

> "Error connecting app:
> This app is unable to link additional users because it has been frozen pending review."

### Expected Behaviour

Authentication of extension via Dropbox.com and use of file search.

**Comment by trevorgehman** [comment]
Any updates on this? When I install the extension and go through the authorization flow Dropbox shows this:

![CleanShot 2024-04-03 at 12 46 23@2x](https://github.com/raycast/extensions/assets/3209864/42dbf1dd-4f48-422a-8ede-f4869b086823)

**Comment by jcannon-majr** [comment]
Also wondering if there's any update from Dropbox on this? Great extension, still getting this "frozen pending review" error while installing.
