### ISSUE TITLE
[Change Case] No longer working properly

### ISSUE THREAD

**Issue by sorec574** [raycast/extensions#11150]
### Extension

https://www.raycast.com/erics118/change-case

### Description

Some of the cases are not correct (Eg. Sentence case, title case).

### Steps To Reproduce

---

- App Version: 1.68.1

- System Version: 14.3.1

### Current Behaviour

Case changes are no working as expected

### Expected Behaviour

Change case accurately without inaccuracies

**Comment by erics118** [comment]
Could you provide some more clarification on what exactly is not working correctly? Could you provide some example snippets where the cases aren't correct?

**Comment by albertograu** [comment]
Having the same issue. For example, sentence case is not converting the text properly:
![screenshot2024-04-01 at 13 21 48](https://github.com/raycast/extensions/assets/10909316/9e6fff9e-693d-4fd2-8c3b-4b89ea01f028)

In this example, we expect the string to be modified to: "Example case".

**Comment by erics118** [comment]
See https://github.com/raycast/extensions/issues/10594 Feel free to add docs clarifying the behavior, or a preference to lowercase the text before other transformations

**Comment by erics118** [comment]
@raycastbot close this issue
