### ISSUE TITLE
[Google Translate] Automatically translate selected text

### ISSUE THREAD

**Issue by RihardsVeters** [raycast/extensions#11153]
### Extension

https://www.raycast.com/gebeto/translate

### Description

Would be great if we could pass selected text right into translate when running any of available commands.

### Who will benefit from this feature?

Everyone who uses this extension for translation purposes.

### Anything else?

You could add this as option in extension settings.

**Comment by gebeto** [comment]
Here how it works for me

  - selecting text
  - pressing `Option + T`
  - Translate is opening with selected text

https://github.com/raycast/extensions/assets/13422799/ce365fc6-748a-4726-b66d-d3405d87b2d8

**Comment by RihardsVeters** [comment]
Oh my God!, why I never noticed this? I already have shortcut for Google translate, but I've been always copy/pasting the text I need to translate. Ok, great! Closing this! :)
