### ISSUE TITLE
[Google Translate] Disable voice translation

### ISSUE THREAD

**Issue by ftonato** [raycast/extensions#11155]
### Extension

https://www.raycast.com/gebeto/translate

### Description

Since the last update there is a new feature for `Play Text-To-Speech` but it is not always necessary or at least I don't use it and this functionality has changed a keyboard shortcut that previously did something else.

Before the update, once the text was translated, when pressing `cmd + enter` the `Toggle Full Text` was activated and we could see the text in full.
After the update, when pressing the same key combination, the text to speech translation takes place.

![CleanShot 2024-03-07 at 15 25 22@2x](https://github.com/raycast/extensions/assets/5417662/30848abc-173c-4cca-b9d1-375ae3c26013)

### Who will benefit from this feature?

If it is possible to disable this, or return the `cmd + enter` command to Toggle Full Text, or perhaps make it configurable for a key combination, perhaps it won't hinder the use of the tool so much for those who are used to something that worked until then.

**Comment by gebeto** [comment]
I think we can just move this command to 3rd place, it should fix this behavior

**Comment by gebeto** [comment]
I already made the PR with this fix, will be available soon, I think

**Comment by ftonato** [comment]
@gebeto Thank you 🚀
