### ISSUE TITLE
Notion - Customize form for CreateDatabaseForm deeplink command

### ISSUE THREAD

**Issue by dariuszpaluch** [raycast/extensions#11160]
### Extension

https://www.raycast.com/notion/notion

### Description

# Problems
- Notion API has a lot of limitations like database properties order, so we couldn't set specific order of properties in Notion and see the same in CreatePageForm form. 
- Users are using Raycast instead of Notion, to save something quickly. For that I propose make notion form clean and simple with hide optional fields (optional properties for database), hide fields with default values in quicklinks, change order of fields.

# Feature
Create deeplink for CreatePageForm command, but with adjustments like: 
- change order of fields
- show/hide fields (then we an hide fields with default values in deeplink)

I saw these code in CreatePageForm.tsx
```
  {databaseView && setDatabaseView ? (
    <ActionPanel.Section title="View options">
      <ActionSetVisibleProperties
        databaseProperties={databaseProperties?.filter((dp) => dp.id !== "title") || []}
        selectedPropertiesIds={databaseView?.create_properties || databaseProperties.map((x) => x.id)}
        onSelect={(propertyId) => {
          setDatabaseView({
            ...databaseView,
            create_properties: databaseView.create_properties
              ? [...databaseView.create_properties, propertyId]
              : [propertyId],
          });
        }}
        onUnselect={(propertyId) => {
          setDatabaseView({
            ...databaseView,
            create_properties: databaseView.create_properties?.filter((pid) => pid !== propertyId),
          });
        }}
      />
    </ActionPanel.Section>
  ) : null}
```
but I couldn't find where databaseView will be initialize first time. I think every time will be null or maybe I miss something?
I propose to fix this "View options" select and add something similar for change order of fields in the form.

### Who will benefit from this feature?

Users who use notion databases like:
- shopping list
- tasks
- reminders
...

### Anything else?

[src/forms/CreatePageForm.tsx](https://github.com/raycast/extensions/blob/10f52e699e74436ff38d55bc466ccd3b0030c753/extensions/notion/src/components/forms/CreatePageForm.tsx#L154)

**Comment by dariuszpaluch** [comment]
@erics118 I'd love to see it and maybe try to help

**Comment by erics118** [comment]
Yep, see #9212

**Comment by dariuszpaluch** [comment]
@erics118  I have a slightly different idea. I created PR here https://github.com/raycast/extensions/pull/11178

**Comment by dariuszpaluch** [comment]
@erics118 ^^ my PR has been merged 😆

**Comment by dariuszpaluch** [comment]
@erics118 My pr has been merged
