### ISSUE TITLE
[YouTube] Integrate with "watch later"

### ISSUE THREAD

**Issue by AntonNiklasson** [raycast/extensions#11167]
### Extension

https://www.raycast.com/tonka3000/youtube

### Description

I would love to be able to see my "watch later" list, and perhaps also remove items from it. I thought about creating a new extension for it, but perhaps we could integrate here instead?

If this sounds like a good idea, I'd be happy to put something together in a PR.

**Comment by raaghav03** [comment]
have forked the repository , would love to work on this.

**Comment by tonka3000** [comment]
@raaghav03 Great. Be aware that you need to impl. OAuth first to get to the data.

**Comment by raaghav03** [comment]
correct me if i am wrong @tonka3000 but you mean i need to enable OAuth in yt api to get the data ?

**Comment by tonka3000** [comment]
I'm pretty sure OAuth login is required. The current manual token does not allow to grab personal data because it requires OAuth login when I remember it correctly.

Watch Later AFAIK is personal data.

Back in the days when I started this extension there was no way for OAuth login in Raycast.

**Comment by raaghav03** [comment]
raycast has now added OAuth , will look at the docs and ping for help if needed

**Comment by tonka3000** [comment]
You can use my old PR as reference if you like

https://github.com/raycast/extensions/pull/1973

Checkout raycast/utils which gives you now a way easier way to impl that.

**Comment by tonka3000** [comment]
The biggest issue is getting a production key from Google. AFAIK no extension ever got one.

Maybe @pernielsentikaer now more about the key.

**Comment by AntonNiklasson** [comment]
As I said in the issue, I'd be happy to work on this. But if you're excited to do it go ahead of course! Let me now if I can help out somehow ☺️

**Comment by AntonNiklasson** [comment]
Any progress here? I'd be happy to work on this if no one else has started yet.

**Comment by raaghav03** [comment]
hey @AntonNiklasson , got swamped with examinations. would love to see how you solve this issue

**Comment by AntonNiklasson** [comment]
I'll take a look and see what I can do.
