### ISSUE TITLE
Custom date is not working

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#11168]
### Extension

https://www.raycast.com/ekafyi/twos

### Description

Custom date like "tomorrow" or "12 May" is not working.

### Steps To Reproduce

Mac M1, latest Raycast version.

### Current Behaviour

Custom date like "tomorrow" or "12 May" is not working.

### Expected Behaviour

Ability to type and select the date.

**Comment by ekafyi** [comment]
Hello! Unfortunately the natural language date feature runs on Twos client-side frontend (ie. when creating items from there) with no possible way to access it through their public API, so nothing can be done.
