### ISSUE TITLE
Cant install. Download URL is outdated.

### ISSUE THREAD

**Issue by scampb3ll** [raycast/extensions#11174]
### Extension

https://www.raycast.com/nhojb/brew

### Description

Hi folks, Im new to raycast so please forgive me if this is not a bug. I have repeatedly tried in a few different ways to install this extension and it fails with Failed To Install Extension - Download URL is outdated.
I at first thought it was my corp firewalls blocking things under the hood but other extensions seem to install fine.

### Steps To Reproduce

Open Raycast
hit + under Extensions tab
navigate to Brew
hit return to install

**Comment by timbitzen** [comment]
@scampb3ll I just tried uninstalling and reinstalling and was able to, but first had to update Raycast. Is it possible you have updates? New ones appear in an ad-looking message at the top of the Raycase spotlight box rather than as a pop-up, so you have have ignored them previously.
