### ISSUE TITLE
[Dig - DNS Lookup] - bug when checking .network domains

### ISSUE THREAD

**Issue by pictosun** [raycast/extensions#11195]
### Extension

https://www.raycast.com/danielbahl/dig

### Description

Hi,

when I try to check $.network domains the extension doesn't show any results. 

### Steps To Reproduce

1. type dig
2. enter some domain ending with .network
3. result is the question mark logo with the message 'Type hostname to search'
4. looks like the extension doesn'r recognize that I already entered a domain

### Current Behaviour

no result - not working

### Expected Behaviour

should give results of the entered domain

**Comment by pictosun** [comment]
Any update over here? Or is there maybe a change to solve the issue by myself?

**Comment by j3lte** [comment]
@raycastbot close this issue
