### ISSUE TITLE
[Bitwarden Vault] ...

### ISSUE THREAD

**Issue by Ammad-cloud** [raycast/extensions#11193]
### Extension

https://www.raycast.com/jomifepe/bitwarden

#### Error:
```
Error: Command failed with Unknown system error -86: /Users/donA/Library/Application Support/com.raycast.macos/extensions/5fdb86d3-dfcc-45a7-8969-8113b51434ab/bw-2024.2.0 lock
spawn Unknown system error -86

ChildProcess.spawn:child_process:421:11
Object.spawn:node:child_process:761:9
p0:search.js:46:4352
```

### Steps To Reproduce

1. Open Search Vault command.
2. Error pops up

**Comment by jomifepe** [comment]
Hello, is your mac arm64 or Intel, meaning you have an Apple M1/2/3 Pro/Max/Ultra chip? You can check this by going to the top left ` Apple menu > About This Mac`.

**Comment by jomifepe** [comment]
Sorry, but Bitwarden currently doesn't have an official arm64 CLI. If you update the extension, you should see a CLI not found error.

For now, arm64 users will have to install the CLI on their machine to use the extension.

This is described in the extension's description: https://www.raycast.com/jomifepe/bitwarden

**Comment by Ammad-cloud** [comment]
thank you - did not see that! It is working now after installing the CLI
