### ISSUE TITLE
[Paperless-ngx] Extension Crashes when searching for a document

### ISSUE THREAD

**Issue by Midbin** [raycast/extensions#11198]
### Extension

https://www.raycast.com/damdam/paperless-ngx

### Description

When trying to search for a document (after entering just one character) the extension crashes:

https://github.com/raycast/extensions/assets/5499764/c8bd3eed-27ba-4be2-b018-57669af2f14a

Crash:

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'length')

Ap:index.tsx:21:60

---
18: export default function DocumentList() {
19:   const { gridMode }: Preferences = getPreferenceValues();
20: 
21:   const [results, setResults] = useState<documentsResponse>();
22:   const [tags, setTags] = useState<tagsResponse>();
23:   const [types, setTypes] = useState<typesResponse>();
24:   const [correspondents, setCorrespondents] = useState<correspondentsResponse>();
---

Or:index.js:11:2490
    at ray-navigation-stack
Ro:index.js:11:2088
```

### Steps To Reproduce

Raycast is setup as a docker container on the local machine.
Paperless URL is set to `http://localhost:8000`, ~~the correct api token is set~~. _(see below)_
Grid mode is off, but does not make a difference if on.

### Current Behaviour

The extension crashes.

### Expected Behaviour

The extension does not crash (either display an error, or display the search results).

**Comment by Midbin** [comment]
After debugging it for a bit I found out the the api token was not correct. The server returned `{ detail: 'Invalid token.' }`which crashed the extension. I still think that this should not crash the extension but rather show an error.

**Comment by Padamdam** [comment]
Hi @Midbin, thanks for reporting back.

I'll look into implementing a more explicit user error
