### ISSUE TITLE
[ray.so] Seemingly sending URLs that I've visited to an endpoint

### ISSUE THREAD

**Issue by lockieluke** [raycast/extensions#11201]
### Extension

https://www.raycast.com/garrett/ray-so

### Description

I opened a proxyman trying to debug my own program and saw Raycast sending some my URLs to an endpoint like `api.ray.so/favicon?url=[url]`, url contained some of the urls I've recently visited.

I don't have the screenshot for proof right now (i was trying to double check by reopening proxyman but it didn't happen the second time, i can swear i saw those requests returning favicons of the websites I visited) but this is very suspicious.

All the requests either returned with `Not Found` or a favicon of the requested website.

You can check an endpoint like https://api.ray.so/favicon?url=https://www.google.com , it would redirect you to an image of google's favicon

### Steps To Reproduce

1. Open Proxyman
2. Observe HTTP requests from Raycast

**Comment by lockieluke** [comment]
Ok false alarm, it was crawling for favicons for the URLs I stored in my clipboard, but shouldn't this be done locally?

**Comment by mathieudutour** [comment]
This isn't related to the ray.so extension. 
We use the `api.ray.so/favicon` api to get the favicon of urls shown in the app (among others, the ones in the clipboard history). We used to use `https://www.google.com/s2/favicons` but found that it wasn't great for some domains (especially the ones behind authentication) so we built our own.
