### ISSUE TITLE
[Easy Dictionary] unable to use

### ISSUE THREAD

**Issue by cynicalight** [raycast/extensions#11205]
### Extension

https://www.raycast.com/isfeng/easydict

### Description

easy dictation -- search word is unable to work...

### Steps To Reproduce

easy dictation -- search word is unable to work...

**Comment by timbitzen** [comment]
+1

**Comment by tisfeng** [comment]
If you encounter a bug, please provide a detailed description of the issue and steps to reproduce it. 

Simply saying "unable to work" is not meaningful 🙄

**Comment by Vesely** [comment]
<img width="760" alt="Snímek obrazovky 2024-04-23 v 11 41 32" src="https://github.com/raycast/extensions/assets/2884297/36a1f726-b2e3-4141-8463-d000a1b84266">
There is an infinite loading. I installed the extension and didn't change any configuration.

**Comment by Vesely** [comment]
@tisfeng In my case there is an issue with `Czech` language. It's working well with `Spanish` or if I enable Google Translate in extension settings.

**Comment by tisfeng** [comment]
Sorry, I'm not familiar with the Czech language, so I'm not sure how these translation services support Czech.

But since you can use Spanish normally, it means Easydict runs fine on your computer. Please try using Google or Bing Translate, as they support most languages.

**Comment by Vesely** [comment]
@tisfeng It would be nice to throw an error instead of infinite loading if it's impossible to translate it
