### ISSUE TITLE
Doesn't recognize french characters i.e é, è, ç [File Manager] ...

### ISSUE THREAD

**Issue by riadhrebei** [raycast/extensions#11200]
### Extension

https://www.raycast.com/erics118/file-manager

### Description

This is an extension related issue rather than a Raycast issue. The file search feature recognizes words with accents like Crème & Braisé but this extension doesn't seem to. 

### Steps To Reproduce

Search for a word containing a latin accent like é, è, ç ô 
![Screenshot 2024-03-10 at 22 33 56](https://github.com/raycast/extensions/assets/35544458/b10aa390-5d07-4a1c-89c3-d656f81cec5a)

### Current Behaviour

Doesn't find the file

### Expected Behaviour

Finding the actual file.

**Comment by erics118** [comment]
I can't reproduce this. I made a few files containing these characters, and the search seemed to work just fine. Could you attach a video showing these files, and that searching for them directly doesn't work?

https://github.com/raycast/extensions/assets/52634785/333aee59-cf10-4127-bb75-0f58d2431608

**Comment by riadhrebei** [comment]
Here's a quick video of the issue. The file appears when writing a portion of it, once a query with characters of sorts is introduced, they vanish.

https://github.com/raycast/extensions/assets/35544458/92e6d9c4-770f-40ab-b0d0-b8ebf2ba7d1f
