### ISSUE TITLE
[Jira] 401 "scope does not match" error on some projects and commands

### ISSUE THREAD

**Issue by wodor** [raycast/extensions#11212]
### Extension

https://raycast.com/raycast/jira

#### Error:
```
Error: {"code":401,"message":"Unauthorized; scope does not match"}
    at Cs (/Users/artwielogorski/.config/raycast/extensions/9f656d62-a7b1-4bc6-bfa8-a67cbb427dcb/search-issues.js:95:2143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/artwielogorski/.config/raycast/extensions/9f656d62-a7b1-4bc6-bfa8-a67cbb427dcb/search-issues.js:99:4858
    at async Promise.all (index 3)
    at async /Users/artwielogorski/.config/raycast/extensions/9f656d62-a7b1-4bc6-bfa8-a67cbb427dcb/search-issues.js:99:4803
    at async Promise.all (index 0)
    at async $L (/Users/artwielogorski/.config/raycast/extensions/9f656d62-a7b1-4bc6-bfa8-a67cbb427dcb/search-issues.js:99:4754)
```

### Steps To Reproduce

login 
try to search anything 

### Current Behaviour

401 error

### Expected Behaviour

seeing results

**Comment by wodor** [comment]
probably it is missing a scope in here 
https://github.com/raycast/extensions/pull/10344/files#diff-f67c38789dfd4132afcdfc87d83ffe59183b28e44e1d7f318751f82213ac8b78R18 

but I don't know how to get to any logs to figure out which one is it 

// cc @esthor

**Comment by wodor** [comment]
to be more precise 
"search issues" also works (for a project that returns 401) when i search for a specific task in that project

**Comment by wodor** [comment]
@thomaslombart  responded directly with a link to recording via email

**Comment by thomaslombart** [comment]
@wodor Could you send it to thomas.lombart@raycast.com instead please? 🙂

**Comment by thomaslombart** [comment]
Thanks for sending the mail. Do you know if accessing Jira issues in other projects needs more scopes or not? I'd say not at first sight, but I'd like to confirm first.

**Comment by thomaslombart** [comment]
Hey @wodor, I'm cleaning up some of the issues in this repository. Are you still having the same issue?

**Comment by thomaslombart** [comment]
I'm closing this issue to maintain a clean backlog. Feel free to comment it if you still have the problem.

**Comment by renkosteenbeek** [comment]
It actually is still a problem. I'm a new Raycast user and I'm bumping into exactly this issue, unfortunately. 

I'm using the latest versions of everything, it's on my MacBook Pro M4 Pro which I received today :P. 

#### Error:
```
Error: {"code":401,"message":"Unauthorized; scope does not match"}
    at oo (/Users/renko/.config/raycast/extensions/9f656d62-a7b1-4bc6-bfa8-a67cbb427dcb/open-issues.js:94:2674)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/renko/.config/raycast/extensions/9f656d62-a7b1-4bc6-bfa8-a67cbb427dcb/open-issues.js:94:4210
    at async Promise.all (index 75)
    at async Fx (/Users/renko/.config/raycast/extensions/9f656d62-a7b1-4bc6-bfa8-a67cbb427dcb/open-issues.js:94:4142)
```
