### ISSUE TITLE
[Unicode Symbols Search] Character U+1E9E missing

### ISSUE THREAD

**Issue by renegeorgi** [raycast/extensions#11213]
### Extension

https://www.raycast.com/mmazzarolo/unicode-symbols

### Description

The character U+1E9E is missing in the database. As it is an important and widely used letter in German, it should be added to the database. Its part of the `Latin Extended Additional` Dataset.

### Steps To Reproduce

- Search for `ẞ`
- Search for `Capital Letter Sharp S`

### Current Behaviour

The letter is not found and not part of the dataset

### Expected Behaviour

`Latin Extended Additional` dataset is part of the database and letter `ẞ` can be found.

**Comment by pernielsentikaer** [comment]
This is now merged, you can run the command `Check For Extension Updates` - thanks for fixing @j3lte 🔥
