### ISSUE TITLE
[Ollama AI] ...

### ISSUE THREAD

**Issue by Noir-fluo** [raycast/extensions#11236]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

Hey i have a problem, I've installed Ollama as extention, and it's work only with text on clipboard, not on selected text.
I have set up like this :  But it's take information from my clipboard. 
![image](https://github.com/raycast/extensions/assets/44384173/856526e3-8862-43df-a3b0-6f1f25838cb5)

### Steps To Reproduce

1 Install Ollama (with Mistral as LMM 
2 Creat an extention 
3 try to tranlsalte, or turn text into professional or wathever you want (it's dosen't work) 
4 Set up the input texte from clipboard (it's work !)
5 try to set up text to selected text, it's dosen't work...

### Current Behaviour

It's take texte from clipboard, but i've set up the "selected text" 

### Expected Behaviour

it's will be take input from selected text

**Comment by MassimilianoPasquini97** [comment]
Hi @Noir-fluo, I'm using the latest release and 'Selected Text' does work. Are you trying to pass selected text from vim? In this case check this https://github.com/raycast/extensions/issues/11158#issuecomment-1984325341. The option below 'Imput Source' let you disable or enable 'clipboard' as a fallback if no text is selected.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue
