### ISSUE TITLE
[Notion] Template should be used when creating the database page

### ISSUE THREAD

**Issue by RedSlowpoke** [raycast/extensions#11233]
### Extension

https://www.raycast.com/notion/notion

### Description

Right now when I try to create a page in the database in Notion itself depending on the view it applies the template.
In Raycast the form is empty at the start, when you're creating a page.

The page should be prefilled as in Notion template when creating page through Raycast

### Who will benefit from this feature?

Everyone who uses the templates in Notion itself and uses the extension

**Comment by thomaslombart** [comment]
Unfortunately, there's no support for templates in the Notion API as of now. So, I'll mark the issue as "Not Planned" in the meantime. Feel free to reach out to Notion to ask them support for that!
