### ISSUE TITLE
[Music] ... Can not search a title by an Artist.

### ISSUE THREAD

**Issue by Danny-mtb** [raycast/extensions#11244]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

Hello,
when I open `Play Library Track` in Raycast and search for an Artist, I became an error -> `Could not get tracks` but the search says: `Search A Song by Title or Artist`. Is it even considered looking for an artist, or have I misunderstood something here?

Here are screenshots for the visual:
<img width="485" alt="Bildschirmfoto 2024-03-12 um 21 28 42" src="https://github.com/raycast/extensions/assets/43675603/a41c5cc3-89af-4e34-9d18-477cde92914e">
<img width="260" alt="Bildschirmfoto 2024-03-12 um 21 28 03" src="https://github.com/raycast/extensions/assets/43675603/e61420cc-8ae1-4bd9-b0fd-b8d7f45ea0fe">

### Steps To Reproduce

1. Open Raycast and search "Play Library Track"
2. There you can only search for song names and not for Artists

**Comment by that70schris** [comment]
would be really nice to combine the "Play Library ..." into one search call "Play From Library" and have the results show which "type" you're selecting, rather than have "Play Library Track", "Play Library Album", and the currently missing "Play Library Artist"
