### ISSUE TITLE
Search Note not working on raycast obsidian plugin [Obsidian] ...

### ISSUE THREAD

**Issue by sophiek123** [raycast/extensions#11241]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

1. Ran the search note command
2. Produced this error 

I have the AdvancedURI plugin installed on Obsidian and I know the extension is linked to my Obsidian Vault because the append daily note command works perfectly. 

### Current Behaviour

An error message is produced when I try to run the comand

### Expected Behaviour

Search Note pulls up relevants notes in the search bar.

**Comment by tylerwillis** [comment]
I also have this same issue / same error message.
