### ISSUE TITLE
[CleanShot X] New command: Open settings

### ISSUE THREAD

**Issue by fmerian** [raycast/extensions#11257]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

I'd like to open CleanShot preferences from Raycast

**Comment by lukaszmtw** [comment]
Right now it's not possible, but we will add this action to the URL scheme API in the upcoming CleanShot 4.7 update. Then it will be possible to add this to Raycast!

**Comment by fmerian** [comment]
> Right now it's not possible, but we will add this action to the URL scheme API in the upcoming CleanShot 4.7 update. Then it will be possible to add this to Raycast!

thanks, Lukas!

**Comment by erics118** [comment]
keep open; CleanShot version 4.7 hasn't been released yet

**Comment by lukaszmtw** [comment]
Hey! We've released the 4.7 update today, that includes the the new `/open-settings` API. Here are the docs: https://cleanshot.com/docs-api#open-settings

**Comment by fmerian** [comment]
> Hey! We've released the 4.7 update today, that includes the the new `/open-settings` API. Here are the docs: https://cleanshot.com/docs-api#open-settings

awesome!

also, what if we include the `View all uploads` command, too? could be as simple as a link to `https://cleanshot.cloud`.

happy to handle it!
