### ISSUE TITLE
[FileMaker Snippets] Create snippet doesn't work

### ISSUE THREAD

**Issue by stathisaska** [raycast/extensions#11253]
### Extension

https://www.raycast.com/eluce2/filemaker-snippets

### Description

* Go to raycast
* Select Create Snippet
* Enter snippet information
* Go to view snippets
* Use snippet

## Expected behaviour
Saved scripts steps to be pasted into the script

## Actual behaviour
Error -> Non-whitespace before first tag
<img width="743" alt="Screenshot 2024-03-13 at 12 14 50" src="https://github.com/raycast/extensions/assets/50539298/0815c027-6685-4298-a182-351078a2be35">

## Further steps
* Trying to modify the snippet deletes the snippet entirely
* All Privacy settings for Raycast have been checked in Settings
* Noticed that the snippet is not copied, but just a boolean `true` is saved instead
<img width="638" alt="Screenshot 2024-03-13 at 12 13 21" src="https://github.com/raycast/extensions/assets/50539298/ff5c718e-fa0c-41a8-a603-182405b04fd0">

### Steps To Reproduce

macOS Ventura with FileMaker 20.3.2

1. Go to raycast
2. Select Create Snippet
3. Enter snippet information
4. Go to view snippets
5. Use snippet

### Current Behaviour

Error -> Non-whitespace before first tag

### Expected Behaviour

Saved scripts steps to be pasted into the script

**Comment by eluce2** [comment]
I am able to replicate this and will attempt to submit a fix later today
