### ISSUE TITLE
[Send to Workflowy Inbox] ...

### ISSUE THREAD

**Issue by matthiasadler** [raycast/extensions#11254]
### Extension

https://www.raycast.com/cameron_pak/workflowy-inbox

### Description

Hi Cameron,

first of all thank you for the Workflowy extension! I was hoping someone would create it for Raycast.

It works very well, I just noticed that the creation of a bullet shows as "invalid date". The date "changed" looks ok, I have attached  a screenshot. It's a minor thing, but sometimes it helps me to see when I created a bullet.

Maybe you can fix it in a new release.

Thanks again,
all the best from Germany
Matthias

<img width="240" alt="Raycast Workflowy" src="https://github.com/raycast/extensions/assets/43719889/71e03e6f-6053-4211-8934-8e7bd656df77">

### Steps To Reproduce

1. Add bullet with Raycast extension
2. Open Workflowy inbox
3. Show menu of created bullet
4. "Created" at the bottom show "Invalid date"

**Comment by cameronapak** [comment]
Hey, I appreciate this. I will bring it up to the workflowy team. I think it's a bug on their API

**Comment by cameronapak** [comment]
https://github.com/cameronapak/workflowy-inbox

Also, I made the source code public and it's available for contributions, if interested!

**Comment by cameronapak** [comment]
"That's some weird sync issue unrelated to the API itself and which we haven't figured out yet. But it fixes itself if you refresh the page after a while." This is what I heard from the team

**Comment by cameronapak** [comment]
> I just tried it and can confirm the date shows up now. Thanks!

Thanks! I also heard that this issue may be fixed in beta. I will be closing this issue since it's out of my hands, but thanks for reporting it!
