### ISSUE TITLE
[Github] I can't create an issue for invited repos

### ISSUE THREAD

**Issue by kainbacher** [raycast/extensions#11260]
### Extension

https://www.raycast.com/raycast/github

### Description

When I want to create a new issue, I only see my repo. I also have other repos that I have access to and would like to create issues for these repos.

Working: (kainbacher: that's me)
https://github.com/kainbacher/irr

Not Working: (zemtu: i have access rights and 
https://github.com/zemtu/zemtu

Currently, https://github.com/zemtu is a GitHub user. What if https://github.com/zemtu is a GitHub organization? Could that possibly be the reason?

![CleanShot 2024-03-13 at 14 21 40](https://github.com/raycast/extensions/assets/593335/04ea68da-ae04-43c6-9cde-7bad0a804729)

![CleanShot 2024-03-13 at 14 21 51](https://github.com/raycast/extensions/assets/593335/995ae2cf-0bae-4f96-9620-2488e4c2837f)

![CleanShot 2024-03-13 at 14 22 05](https://github.com/raycast/extensions/assets/593335/ca2ad203-f57e-44c1-8fa0-d200675edef8)

### Steps To Reproduce

1. get an ivitation from a friend for a repo
2. try to create a new issue

**Comment by kainbacher** [comment]
@thomaslombart  I would love to help out with vuejs or python :)

React it not on my list.

**Comment by thomaslombart** [comment]
We only support React unfortunately 😕
