### ISSUE TITLE
[Iconify — Search Icons] Add SF Symbols

### ISSUE THREAD

**Issue by alanwill** [raycast/extensions#11268]
### Extension

https://www.raycast.com/destiner/iconify

### Description

Any plans to include support for Apple's SF Symbols?

### Who will benefit from this feature?

Designers and developers building for the Apple ecosystem (iOS, macOS, visionOS etc)

**Comment by xilopaint** [comment]
This is an Iconify extension. The provider is Iconify. I believe there's no sense in supporting SF Symbols in this extension. There's already a SF Symbols Search extension.
