### ISSUE TITLE
[Spotify Player] Alert for Duplicate Songs Before Adding to a Playlist

### ISSUE THREAD

**Issue by Brian-Konr** [raycast/extensions#11269]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

I would like to propose a new feature for the Spotify Player extension on Raycast that aims to enhance user experience and streamline playlist management. Specifically, I am suggesting the implementation of an alert mechanism that notifies the user if they are attempting to add a song to a playlist which already contains that song. This feature would help prevent the duplication of tracks in playlists, ensuring a cleaner and more organized music listening experience.

### Who will benefit from this feature?

those who frequently curate and manage their playlists. By preventing accidental duplication, users can maintain streamlined playlists without having to manually check for duplicates

### Anything else?

I am a student majoring in computer science and I am deeply interested in contributing to the development of this feature. Not only do I believe it will significantly benefit the community by improving the Spotify Player extension, but I also view this as a wonderful opportunity to contribute to society and further accumulate my experience in software development. I am eager to discuss potential implementation strategies and collaborate with the Raycast and Spotify Player extension teams to bring this feature to life.

If I am given the honor to contribute to the development of this feature, I can be reached via email at kobe2000101@gmail.com. I am fully prepared to collaborate closely with the team and bring my skills to the table to make this feature a reality. Thank you!

**Comment by thomaslombart** [comment]
Hey @Brian-Konr, thanks for the feature request. Feel free to open a PR for that one if you're interested in it. Here's our guide about contributing to extensions: [Contribute to an extension](https://developers.raycast.com/basics/contribute-to-an-extension)
