### ISSUE TITLE
extension Eject all disks

### ISSUE THREAD

**Issue by rmbults** [raycast/extensions#11263]
### Description

When using Eject All i get a message that a disk I don't have mounted, cannot be ejected. I thinks it is always the same ID. When unmounting the usual way through finder, all is fine.

### Steps To Reproduce

MBA 2022 M2 MacOS 14.4

### Current Behaviour

error
![system-command-eject-all-v0-psb68nf7qulc1](https://github.com/raycast/extensions/assets/158844923/5948f6a4-d2b1-4f9e-8cdc-33cfa03f3ee2)

### Expected Behaviour

no error

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
