### ISSUE TITLE
[Sourcegraph] Self-hosted sourcegraph search doesn't work

### ISSUE THREAD

**Issue by dleen** [raycast/extensions#1126]
# Extension – [Sourcegraph](https://github.com/raycast/extensions/tree/86b364651a4c2cdb95025f6951e998a4a1dcb3b1/extensions/sourcegraph/)
Author: @bobheadxi

## Description
Searching using self-hosted url doesn't work.

## Error:
```
Error: Protocol error

__node_internal_captureLargerStackTrace:errors:464:5
NghttpError:util:555:5
Http2Session.onSessionInternalError:core:784:26
```

## Steps To Reproduce

1. Configure self-hosted sourcegraph address e.g. `https://sourcegraph.mydomain.net`, enter API key
2. Do a search

## The current behavior
The search doesn't work...

<img width="753" alt="Screen Shot 2022-03-16 at 9 44 54 PM" src="https://user-images.githubusercontent.com/1297964/158738938-94dd6447-01eb-4268-805c-399248b9ae3c.png">

## The expected behavior
The search results are shown

### Raycast version
Version: 1.30.3

**Comment by bobheadxi** [comment]
@dleen What version of Sourcegraph is your self-hosted Sourcegraph instance?

**Comment by dleen** [comment]
Good question, sorry I should have included it: `3.37.0`

**Comment by bobheadxi** [comment]
No worries! Is your instance hosted behind networking restrictions of any kind?

**Comment by dleen** [comment]
Yes, my sourcegraph instance is only available via a VPN. But I made sure the VPN was connected, I can access the instance fine via browser, and via curl.

I think I'll check out the extension and run it locally with some debug statements to see what's happening...

**Comment by bobheadxi** [comment]
I did some brief searches regarding this. Threads like [this one](https://stackoverflow.com/a/32055112) indicate that we might need to introduce additional configuration to connect to VPNs, but I'm not terribly familiar with VPNs in general so I'm not too sure where to start.

If you could share a more complete error message, or some details about your VPN setup, that might be helpful!

**Comment by dleen** [comment]
I got around to looking at this.

> If you could share a more complete error message, or some details about your VPN setup, that might be helpful!

Unfortunately that error message is the entire message. Nothing else shows up. I don't think the VPN setup is the problem because I am able to reach the instance using all other clients just fine e.g. the sourcegraph curl instructions work.

I installed the extension locally but it didn't give any extra error details. The error said `Error: Protocol error` so when I took a look at the code I did notice that it was using `EventSource` and `http2`:
```
import EventSource from "@bobheadxi/node-eventsource-http2"
```

I took a look at the library and saw that it was a fork because the original didn't support `http2`. I swapped out the EventSource library for:
```
import EventSource from 'eventsource'
```

which actually worked and returned results from the server.

This ran into its own problem where it never stopped (requesting?) returning results until it hit a memory limit:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

__node_internal_captureLargerStackTrace:errors:464:5
NodeError:errors:371:5
Worker.[kOnExit]:worker:279:26
Worker.<computed>.onexit:worker:201:20
```

Maybe that's an issue with the library being different from the fork and some code needs updating to stop returning results?

But it was good to make some progress.

I'm not sure why the http2 library didn't work or what the `protocol error` actually means. When I visit my sourcegraph instance in the browser and inspect the network requests I see some `h2` requests (although just for JS assets, not the actual API queries).

**Comment by bobheadxi** [comment]
Interesting, I tried `eventsource` when first creating the extension and I couldn't get it to work. I see they cut a new release recently (https://github.com/EventSource/eventsource/releases/tag/v2.0.0), and I am indeed able to get it to work now! I'm not sure if something changed in the library or on our end, but I saw the memory limit issue as well and I think I've fixed it with https://github.com/bobheadxi/raycast-sourcegraph/commit/0b66d0a85c4be4f81a6193144c61ab614b8b8fcf

**Comment by bobheadxi** [comment]
The update will be included in https://github.com/raycast/extensions/pull/1228 !

**Comment by bobheadxi** [comment]
@dleen did the new update resolve your issue?

**Comment by dleen** [comment]
Yep! Works perfectly, thanks!!
