### ISSUE TITLE
[Ollama AI] - Answer in different language

### ISSUE THREAD

**Issue by mguyard** [raycast/extensions#11274]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

Today, in this extension, all prompt are in english.
Most of models are able to answer in different language.

An interesting feature can be to add in system prompt the answer language requested. Language can be a extension preference in a dropdown.
Fallback to english can be useful if model don't support language define in extension preferences.

For example, modifying prompt for extensions/raycast-ollama/src/ollama-explain.tsx who is :
```
const p =
    "Act as a writer. Explain the following text in simple and concise terms.\n\nOutput only with the modified text.\n";
```
by
```
const p =
    "Act as a writer. Explain the following text in simple and concise terms.\n\nOutput only with the modified text.\nYou only need to answer in French except if you don't support this language\n";
```

Will permit to answer in french. So if you replace French by the language preference, i think that's will be great.

### Who will benefit from this feature?

Every people where english isn't easy to use

**Comment by MassimilianoPasquini97** [comment]
Hi @mguyard, all provided commands are using prompt in english and are meant to be used as a base commands set. As described on README.md 'Create Custom Command' let you create as many commands you want with your own custom prompt.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue

**Comment by mguyard** [comment]
Yes I know and it like I use it. But it can be easily multi language without important modifications in extension.
And like this, it will not need to recreate all default commands to just have the right language
