### ISSUE TITLE
[Snippet Surfer] implement keyword

### ISSUE THREAD

**Issue by WladyX** [raycast/extensions#11272]
### Extension

https://www.raycast.com/astronight/snippetsurfer

### Description

It would be really useful to implement keywords, just like the native snippets:
"If you specify a keyword, you can simply type it in any application to have it auto-expand in-place. "

**Comment by mkitane** [comment]
As far as I know, the developer APIs don't allow this functionality for extensions

**Comment by WladyX** [comment]
That's a shame, i really use that, so for we it means using 2 extensions doing the same, thing, probably I'll use the native one just for this.
Thank you for sharing this cool extension.
