### ISSUE TITLE
[Apple Notes] how to grant permission manually

### ISSUE THREAD

**Issue by cofdam** [raycast/extensions#11278]
### Extension

https://raycast.com/tumtum/apple-notes

### Description

When searching and opening an apple note from raycast, I accidentally clicked "Not Allow", don't know how to fix it. 

### Steps To Reproduce

Failed to open the note with error:
Error: Command failed with exit code 1: osascript -e tell application “Notes” set theNote to note id “x-coredata://7A57C6D6-D5D2-4A55-9862-5A11D09D6C0D/ICNote/p1729” set theFolder to container of theNote show theFolder show theNote activate end tell 50:122: execution error: Not authorized to send Apple events to Notes. (-1743)

### Current Behaviour

doesn't open an apple note.

### Expected Behaviour

want it to open an apple note.

**Comment by thomaslombart** [comment]
`System Preferences > Privacy & Security > Automation > Raycast > Toggle notes checkbox`

![CleanShot 2024-03-22 at 16 02 32@2x](https://github.com/raycast/extensions/assets/16003285/b304a6d3-1e55-407e-b0ab-4ec1fcb529df)

**Comment by thomaslombart** [comment]
I'm closing this issue to maintain a clean backlog. Feel free to comment it if you still have the problem.
