### ISSUE TITLE
[One Thing] does not appear in the Menu Bar upon setting. Happens on Mac Sonoma 14.3.1 on M2 Pro

### ISSUE THREAD

**Issue by twilczek** [raycast/extensions#11282]
### Extension

https://www.raycast.com/pernielsentikaer/one-thing

### Description

It worked before I did the system update. Right now upon setting I only see a small popup in the bottom center of the screen (last screenshot) but it never appears in the Menu Bar
<img width="758" alt="Zrzut ekranu 2024-03-14 o 10 44 40" src="https://github.com/raycast/extensions/assets/15635607/388745b6-a2d0-48b1-8257-c8dafd1db98e">
<img width="489" alt="Zrzut ekranu 2024-03-14 o 10 44 59" src="https://github.com/raycast/extensions/assets/15635607/4c70281e-ef95-40a6-8d22-7e344fe55007">
<img width="371" alt="Zrzut ekranu 2024-03-14 o 10 46 42" src="https://github.com/raycast/extensions/assets/15635607/50b76fd0-860f-4bb0-afe3-c8e69781203b">

### Steps To Reproduce

1. Set One Thing using Raycast Command Bar

### Current Behaviour

It does not appear in the Menu Bar

### Expected Behaviour

It appears in the Menu Bar

**Comment by pernielsentikaer** [comment]
Do you have space in the menubar for the icon (Since it stops a bit before the notch if your machine has that)
