### ISSUE TITLE
[Coffee] Hide menu bar icon when not active

### ISSUE THREAD

**Issue by rogiervandenberg** [raycast/extensions#11283]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

First of all: Amazing Extension 🙏 Thanks for that! Furthermore, would it be an idea to have the menu bar only visible when active (the full coffee pot), but hidden when not active, to take up less space (in that small area right to the notch)? That way you can quickly Raycast enable it and have a visual clue it's running, but it's out of the way when not using it.

### Who will benefit from this feature?

All users that use Coffee once in a while.

**Comment by tannerkc** [comment]
@rogiervandenberg You could use the 'hidden bar' app from the App Store

**Comment by pernielsentikaer** [comment]
This is now possible as a preference under the menubar command 🙂
