### ISSUE TITLE
[Calculator] Timezone ignored for timestamp

### ISSUE THREAD

**Issue by na2hiro** [raycast/extensions#11302]
### Extension

core feature?

### Description

Timezone is ignored when timestamp is pasted.

<img width="759" alt="Screenshot 2024-03-15 at 9 05 07" src="https://github.com/raycast/extensions/assets/736244/555e471a-e584-4bc8-a6e0-c732a2df5b25">

### Steps To Reproduce

Paste `2024-03-09T00:57:19.000-06:00`

### Current Behaviour

`2024-03-09T09:57:19+09:00` if you're in JST timezone (increase the time by 9 hours. Input is considered 2024-03-09T00:57:19.000-**00**:00)

### Expected Behaviour

`2024-03-09T15:57:19.000+09:00` if you're in JST timezone (increase the time by +9 - (-6) = 15 hours)

**Comment by pernielsentikaer** [comment]
Hi 👋

Thank you for flagging this. It is indeed a bug that will be fixed in one of the upcoming releases 🙂
