### ISSUE TITLE
[Browser Bookmarks] Show the browser's icon for each bookmark in the search when connecting 2+ browsers

### ISSUE THREAD

**Issue by ziserman** [raycast/extensions#11301]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

Hello and thank you for such an awesome product 👍

Browser Bookmarks is my №1 feature in Raycast, I'm using it on a daily basis. Thank you so much!

Here's my feature request:
I found the information on the right side, along with the folders, to be useless. At the same time, I really miss the information about which browser will be open when I press some link. I'm using at least two browsers at the same time: Safari for personal usage and Chrome for my work.

I wish to understand what browser does the link refer to, right in the main search list.
<img width="751" alt="SCR-20240315-cmfp" src="https://github.com/raycast/extensions/assets/22889313/1d1ca8be-d352-4587-b8e0-944d084b549c">

I've never used the selector at the top right corner, because it slows down you a lot
<img width="257" alt="SCR-20240315-cnir" src="https://github.com/raycast/extensions/assets/22889313/959b17f3-4804-4e33-b148-437155a5c06d">

### Who will benefit from this feature?

Anyone who values the speed of navigation between bookmarks in Raycast. Well... Mostly anyone who uses 2+ browsers.

### Anything else?

I'm not a UX/UI designer, but I think it's possible to keep both folders and browser information together.

**Comment by thomaslombart** [comment]
This could be a nice improvement. We can add settings for these so that you can control what appears or not in the list accessories.
