### ISSUE TITLE
[Anybox] View folder location next to the link using the "Search links" command

### ISSUE THREAD

**Issue by branislavbudzak** [raycast/extensions#11305]
### Extension

https://www.raycast.com/anybox/anybox

### Description

My most used command in this Anybox extension is "Seach Links" command and it is great that I can browser all my links. I mostly organize my links using folders.  So I wish to see folder names next to or under link names, like in the Raindrop.io extension I used before Anybox. Maybe the tag can also be displayed there.

I know I can filter specific folders by enabling "Show Folders in Search Results" in the extension settings. However, I find it more useful to filter all links regardless of folders and then see the folders they are in.

I have over 650 links in Anybox, and some tools or websites I saved have similar names and descriptions. Therefore, I want to quickly recognize the category of each link.

Thank you for considering this feature.

### Who will benefit from this feature?

Those primarily using folders for organization want to quickly see the link category at a glance.

**Comment by francisfeng** [comment]
@raycastbot close this issue
