### ISSUE TITLE
[Cyberduck] Missing required property "title" for List.Item

### ISSUE THREAD

**Issue by CSM-800** [raycast/extensions#11310]
### Extension

https://www.raycast.com/scottaglia/cyberduck

### Description

Error: Missing required property "title" for List.Item
Cyberduck: 8.8.1 (41263)

### Steps To Reproduce

1. Open Raycast (Alt + Space)
2. Type FTP
3. Error appears

**Comment by scottaglia** [comment]
@raycastbot close this issue
