### ISSUE TITLE
[Brew] Run as different (admin) user

### ISSUE THREAD

**Issue by Zapfmeister** [raycast/extensions#11314]
### Extension

https://www.raycast.com/nhojb/brew

### Description

It would be great to have an option to run brew as a different user.
My main user doesnt have admin rights, so i would need to specificy the user and run the command accordingly.
For example:
`su - {user} -c {brew command}`

### Who will benefit from this feature?

Everyone that doesnt use admin permissions on his main user.

**Comment by MillerApps** [comment]
I don't see the use case here. 
- Allowing anyone to run admin commands undermines the purpose of admin roles. 
- Users without admin access may not understand homebrew. 
- Implementing this could lead to unintended consequences.

**Comment by Zapfmeister** [comment]
The idea was not to save the credentials, but to give and option to add a user under which brew is supposed to be executed and ask for the password when required.
