### ISSUE TITLE
[YouTube Music] Does not work in Safari when installed as PWA

### ISSUE THREAD

**Issue by khromov** [raycast/extensions#11323]
### Extension

https://www.raycast.com/danieldbird/youtube-music

### Description

When you have installed YouTube Music as a PWA via Share > Add to Dock, neither setting Safari nor the dedicated new YT Music "app" works. If choosing Safari it says "tab not found", if choosing the YT Music app it doesn't do anything.****

### Steps To Reproduce

1. Go to https://music.youtube.com/ in Safari on Mac
2. Share menu > Add to Dock
3. Now try to set either Safari or the new YT Music app, neither works.

![Screenshot 2024-03-16 at 03 01 21](https://github.com/raycast/extensions/assets/1207507/1c7697a6-3f89-4dee-ba79-32cea206828d)

### Current Behaviour

Commands don't work

### Expected Behaviour

Commands work

**Comment by burgerga** [comment]
Same for the Chrome PWA, setting the Youtube Music PWA or Google Chrome doesn't work
