### ISSUE TITLE
[GitLab] Time estimation, adding time spent on task, adding new issues

### ISSUE THREAD

**Issue by au-ganymede** [raycast/extensions#11338]
### Extension

https://www.raycast.com/tonka3000/gitlab

### Description

Enable, directly by command or using the available options (e.g. when previewing problems assigned to me), to estimate the time for a problem (/estimate) or add the time spent on a task (/spend 1h 2024-03-17).

GitLab documentation on this matter: https://docs.gitlab.com/ee/user/project/time_tracking.html

It would also be nice to be able to add a new issue from Raycast, complete it with subject, content, label and assign people to it.

Currently there is no such possibility, or at least I do not see it.

### Who will benefit from this feature?

This will benefit those who use GitLab for work on a daily basis. Especially if you work with other people in a team.

**Comment by tonka3000** [comment]
> It would also be nice to be able to add a new issue from Raycast, complete it with subject, content, label and assign people to it.

Did you tried the `Create Issue` command.
