### ISSUE TITLE
[MindNode] Allow to set the path to the Mindnode app in the extensions parameters

### ISSUE THREAD

**Issue by marcmagn1** [raycast/extensions#11348]
### Extension

https://www.raycast.com/thuggyduck/mindnode

### Description

Hello,

I'm currently using Mindnode through Setapp, but the extension fails to locate it due to a differing path from the standard version. 

I believe this issue could be resolved if the extension allowed users to manually direct it to their specific Mindnode application location.

### Who will benefit from this feature?

Setapp users

### Anything else?

Thanks in advance for entertaining the idea!

**Comment by natsustan** [comment]
Hi, thanks for using this extension!
Well, I just supported the mindnode on setapp and waiting for merge #11368 .
