### ISSUE TITLE
[QR Code Scanner] dosn't work with "Pop to root search" setting = immediately

### ISSUE THREAD

**Issue by JuliusJacobitz** [raycast/extensions#11358]
### Extension

https://www.raycast.com/StevenRCE0/qr-code-scanner

### Description

When setting the `Pop to Root Search` option in 'General Settings of Raycast' to `Immediately` the extension stops working: After selecting a QR-Code, nothing happens. When changing `Pop to Root Search` back, everything works fine.

### Steps To Reproduce

1. General Settings of Raycast -> Pop to Root search = Immediately
2. Try to capture a QR-Code

### Current Behaviour

above

### Expected Behaviour

above

**Comment by StevenRCE0** [comment]
Hello and thanks for reporting this issue. A fix is on its way.
