### ISSUE TITLE
[YouTube Downloader] Handle Youtube Playlist links

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#11365]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

It's not clear if the issue is because the video is from a recent livestream or that the link itself contains a reference to a playlist, but the YouTube Downloader can't seem to process it successfully.

This is the error I got:

```
TypeError: Expected a finite number, got number: NaN

GO:index.tsx:20:41

---
17: import fs from "fs";
18: 
19: export default function DownloadVideo() {
20:   const [loading, setLoading] = useState(false);
21:   const [title, setTitle] = useState("");
22:   const [formats, setFormats] = useState<videoFormat[]>([]);
23:   const [error, setError] = useState(0);
---

Or:index.js:11:2490
    at ray-navigation-stack
Ro:index.js:11:2088
```

### Steps To Reproduce

1. Activate YouTube Downloader in Raycast and attempt to download [this link](https://www.youtube.com/watch?v=Y2F8yisiS6E&list=TLGGFIbdOwQMZx4xODAzMjAyNA)
2. An error will be produced:

![2024-03-18 (15 27 10) Arc](https://github.com/raycast/extensions/assets/22610/34c6c9f9-8b17-4450-8db2-4e88df5b9b03)

The content of the error:

```
TypeError: Expected a finite number, got number: NaN

GO:index.tsx:20:41

---
17: import fs from "fs";
18: 
19: export default function DownloadVideo() {
20:   const [loading, setLoading] = useState(false);
21:   const [title, setTitle] = useState("");
22:   const [formats, setFormats] = useState<videoFormat[]>([]);
23:   const [error, setError] = useState(0);
---

Or:index.js:11:2490
    at ray-navigation-stack
Ro:index.js:11:2088
```

### Current Behaviour

YouTube Downloader is unable to download [this video](https://www.youtube.com/watch?v=Y2F8yisiS6E&list=TLGGFIbdOwQMZx4xODAzMjAyNA).

### Expected Behaviour

YouTube Downloader should be able to handle playlists; it could:

* offer a list of videos from the playlist to be downloaded individually
* download all of the videos in the playlist
* report an error that playlists aren't supported

**Comment by chrismessina** [comment]
Looking more deeply at this, it may be because:

1. The livestream was still happening. It seemed to also be available [here](https://www.youtube.com/live/Y2F8yisiS6E).
2. The file hadn't finished processing.

In any case — better error handling would be useful for live events and playlists!

**Comment by vimtor** [comment]
Hey @chrismessina!

You are 100% right we could add better error handling for these two cases.

I will implement it in the next batch of updates for the extension.
