### ISSUE TITLE
[swift-evolution] Adopt upcoming Swift Evolution metadata file changes

### ISSUE THREAD

**Issue by dempseyatgithub** [raycast/extensions#11375]
### Extension

https://www.raycast.com/BProg/swift-evolution

### Description

Hi, I'm James Dempsey, a member of the [Swift Website Workgroup](https://www.swift.org/website-workgroup/).

As part of the workgroup one area I’ve been focused on is the Swift Evolution Dashboard and the JSON file of evolution proposal metadata available at `https://download.swift.org/swift-evolution/proposals.json`.

I’m filing this issue because a GitHub search shows that this project references that URL.

I wanted to let you know that we are in the process of making some proposed changes to the schema and naming of the metadata file.

The proposed modifications are in the Swift Forums post at https://forums.swift.org/t/swift-evolution-metadata-proposed-changes/70779.

Please feel free to provide any feedback in that thread.

That post also describes the transition plan to migrate to the new metadata schema.

During the transition period, the `proposal.json` file will continue to be available at its current URL with its current schema.

A file with the new schema will also be available during the transition period.

For full details and to provide any feedback you may have, please review [the post in the Swift forums](https://forums.swift.org/t/swift-evolution-metadata-proposed-changes/70779).

### Who will benefit from this feature?

I imagine anyone using this extension.

**Comment by pernielsentikaer** [comment]
CC @BProg, could you check this

**Comment by BProg** [comment]
Will take a look and start working on it. thanks 🙏🏽

**Comment by dempseyatgithub** [comment]
An update that review period for the updated Swift Evolution metadata schema has ended.

The transition period to migrate to the new metadata schema and file has begun and will run through July 22, 2024.

Full details of the transition are available here:
https://forums.swift.org/t/swift-evolution-metadata-transition/71387

**Comment by dehesa** [comment]
Thank you for the heads up @dempseyatgithub 

@BProg any chance you can implement this 😬 🙏 Maybe it is also time to add that right-hand-side filter we talked about some time ago.

**Comment by BProg** [comment]
Starting the work

**Comment by BProg** [comment]
PR ready for review

**Comment by BProg** [comment]
I think the issue can be closed
