### ISSUE TITLE
[Swift Package Index] ...

### ISSUE THREAD

**Issue by atacan** [raycast/extensions#11399]
### Extension

https://www.raycast.com/maximkrouk/swift-package-index

### Description

```console
Could not perform search SyntaxError: Unexpected token '<, "‹!DOCTYPE " ... is not valid JSON
```

### Steps To Reproduce

- Type a search term.
- Get an error.

### Current Behaviour

Error

![ScrShot 2024-03-20 at 09 01 47@2x](https://github.com/raycast/extensions/assets/765873/56d1e0e8-3d0c-41c2-9973-9d926756b1c0)

### Expected Behaviour

Fetch and show search results

**Comment by japanese-goblinn** [comment]
Hey @atacan. It's a duplicate of https://github.com/raycast/extensions/issues/11132. The fix is in progress and will be done hopefully next week.

**Comment by maximkrouk** [comment]
Fixed in https://github.com/raycast/extensions/pull/11539 ✅
