### ISSUE TITLE
[Stock Tracker] 401 Unauthorized

### ISSUE THREAD

**Issue by iwex** [raycast/extensions#11393]
### Extension

https://www.raycast.com/hmarr/stock-tracker

### Description

![CleanShot 2024-03-19 at 23 49 03](https://github.com/raycast/extensions/assets/4510068/3f40f62d-1131-4a3a-938e-30b18b9aa06e)

### Steps To Reproduce

Search for some stock

**Comment by eduwass** [comment]
Looks like this is still happening
