### ISSUE TITLE
[SF Symbols Search] Two commands have the same keyboard shortcut

### ISSUE THREAD

**Issue by atacan** [raycast/extensions#11407]
### Extension

https://www.raycast.com/peteschaffner/sf-symbols-search

### Description

![ScrShot 2024-03-20 at 17 26 19@2x](https://github.com/raycast/extensions/assets/765873/98c48b48-aa0e-4500-a62d-a412962ba33d)

### Steps To Reproduce

Search for a symbol.
Open the commands for a symbol.

### Current Behaviour

the commands for copying the name and the symbol has the same Command+Shift+C keyboard shortcuts

### Expected Behaviour

I would prefer to use the Command+Shift+C to copy the name

**Comment by peteschaffner** [comment]
Hey @atacan! To be honest I haven't used or touched the code for this extension in a really long time—even those command titles in that screenshot seem different from what I remember implementing (IIRC there was a PR a while back, but it wasn't authored by me).

I'd like to dig back into this one day as I'd like to start using it again myself, but it was quite a gnarly extension to get working and maintain, so no promises :(
