### ISSUE TITLE
[ChatGPT] - Problem when "Use Full Text Input" is activated

### ISSUE THREAD

**Issue by Angelblot** [raycast/extensions#11420]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Hi, 

Better to show you a video :  Uploading Enregistrement de l’écran 2024-03-21 à 09.59.45.mov…

As you can see, the shortcut work well, but you can't see the result without returning back 2 times

Thank you for your help !

### Steps To Reproduce

I've both activated : Auto-load Text and Use Full Text Input
I've defined a shortcut to use the text I've selected to push it directly to Ask ChatGPT, I see that it's working background but can't see the result

### Current Behaviour

I need to go back 2 times to be able to see the result of ChatGPT

### Expected Behaviour

I think the result have to be shown when ready ?

**Comment by Angelblot** [comment]
https://we.tl/t-OsRpdx0WsC

**Comment by bxb100** [comment]
https://github.com/raycast/extensions/assets/20685961/6fa6aea0-c088-4f0f-aabd-21be3b2f55a5

**Comment by bxb100** [comment]
@pernielsentikaer Does there have a window's focus hook?

**Comment by pernielsentikaer** [comment]
No there is no such hook @bxb100
