### ISSUE TITLE
Doc screen/webpage to obtain Developer ID doesn't specify which API to request access to

### ISSUE THREAD

**Issue by tlwalton** [raycast/extensions#11428]
### Description

Wolfram offers six or seven APIs.  I've tried two of them, "Full Results API", and "Conversational API".  Neither seems to work.

**Comment by c0rinne** [comment]
I was only able to get it to work by signing up for Wolfram Alpha Pro. I signed up for 1 month and then was able to get the app using Full Results API.

**Comment by monofish** [comment]
> ### Description
> Wolfram offers six or seven APIs. I've tried two of them, "Full Results API", and "Conversational API". Neither seems to work.

If you look into the [source code](https://github.com/raycast/extensions/blob/7ca3463ee3617c017555ffea00228d1813c598f6/extensions/wolfram-alpha/src/index.tsx#L49), you can see the URL matches Wolfram Αlpha **[Simple API](https://products.wolframalpha.com/simple-api/documentation)**.
