### ISSUE TITLE
[Xcode] Add command to `Clear Swift Package Manager Cache` command.

### ISSUE THREAD

**Issue by kdaramz** [raycast/extensions#11426]
### Extension

https://www.raycast.com/SvenTiigi/xcode

### Description

Hello, developer.

If you look at the current **`Clear Swift Package Manager Cache`** command,
```bash
rm -rf ~/Library/Caches/org.swift.swiftpm/repositories
```
only above command is being executed.

However, this command is not perfect to clear SPM cache.
I think the following command needs to be additionally executed to completely clear the cache:
```bash
rm -rf ~/Library/org.swift.swiftpm
```
If this command is not executed, I have experienced cases where the old cache causes problems when importing packages.
[ref.](https://stackoverflow.com/questions/72788019/where-is-swift-package-manager-cache-located-swift-5-7)

p.s
I think it is better to delete the entire package rather than deleting the repositories within the package, even for existing commands:
```bash
rm -rf ~/Library/Caches/org.swift.swiftpm/repositories
```
to
```bash
rm -rf ~/Library/Caches/org.swift.swiftpm
```

### Who will benefit from this feature?

Anyone using this awesome extension! 👍🏽

### Anything else?

This extension has greatly improved my productivity. Thanks!

**Comment by SvenTiigi** [comment]
@kdaramz fixed with https://github.com/raycast/extensions/pull/11616

**Comment by SvenTiigi** [comment]
@raycastbot close this issue
