### ISSUE TITLE
[Acqua] Give Desktop Notifications

### ISSUE THREAD

**Issue by aizaz-shahid** [raycast/extensions#11427]
### Extension

https://www.raycast.com/FezVrasta/acqua

### Description

I am not sure where it sends the reminder, it is almost useless. It would be great if it could send a desktop notification

### Who will benefit from this feature?

Everyone

**Comment by FezVrasta** [comment]
Right now it only shows the status on the menu bar icon. Sending a push notification would be great but I don't know how to do it. Feel free to send a PR.
