### ISSUE TITLE
[Connect to VPN] Toggle last used VPN with seperate command

### ISSUE THREAD

**Issue by oligafner** [raycast/extensions#11424]
### Extension

https://www.raycast.com/rasmusbe/connect-to-vpn

### Description

I would like to have the ability to toggle the last used VPN or the first VPN in the VPN list instantly with a secondary raycast command.

### Who will benefit from this feature?

I need to toggle a single VPN a lot. The new command would save me one command in raycast. 

### Anything else?

Thanks for this great extension. ❤️

**Comment by rasmusbe** [comment]
Good idea, I'm not sure when I will have the time to try to implement it, but anyone else is welcome to try if they are faster than me.
