### ISSUE TITLE
[Ollama AI] 'Describe Content of Image' Problem with Image Size

### ISSUE THREAD

**Issue by wydrox** [raycast/extensions#11432]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

No mather how big resolution of an image i upload, the model mostly returns "too small image" or want even try to describe the image. I am using llava:34b.

I am wondering if heigh limit in this line is not an issue: https://github.com/raycast/extensions/blob/ce8c241a4cf3292c3ca317aab39c73f42446cc43/extensions/raycast-ollama/src/api/common.ts#L73

### Steps To Reproduce

1. Chose hires image with small text
2. load to raycast/ollama/describe content of the image
3. Poor results

### Current Behaviour

Model is not receiving full resolution of the image

### Expected Behaviour

Either model receives full res image or user can modify heigh limit

**Comment by MassimilianoPasquini97** [comment]
Hi @wydrox, can you explain better what type of problem do you encounter? Can you upload the image where you encounter this problem so I can try to reproduce the error on my own.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot rename this issue to "[Ollama] 'Describe Content of Image' Problem with Image Size"

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue
