### ISSUE TITLE
Permit applications to dynamically define new commands

### ISSUE THREAD

**Issue by jul-sh** [raycast/extensions#11431]
### Description

There's a set of AI extensions that define a common set of shortcuts: shorten text, expand text, summarize, etc. Eg Gemini, Perplexity, ChatGPT.

These prompts are useful, but as a user I'd want to define custom shortcuts for my own prompts/actions. To do this, extensions must be able to register new commands dynically, instead of statically in package.json.

**Comment by mathieudutour** [comment]
Duplicate of https://github.com/raycast/extensions/issues/939
