### ISSUE TITLE
[1Password] Better handle when 1Password CLI is updated via Homebrew

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#11434]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

I'm running the Beta of 1Password (1Password for Mac 8.10.30 (81030001)).

Recently the 1Password CLI updated from v2.24.0 to v2.26.0, including changing the location on disk from:

`/opt/homebrew/Caskroom/1password-cli/2.24.0/op`

to:

`/opt/homebrew/Caskroom/1password-cli/2.26.0/op`

I'm not sure if this happened when I ran `brew upgrade` or when I updated 1Password (I presume the latter) but it caused the 1Password Raycast Extension to silently fail.

Given that 1Password's [CLI docs](https://developer.1password.com/docs/cli/get-started/) recommend using Homebrew as the default installation method, it would probably be good for the 1Password Raycast extension to better handle this situation.

### Steps To Reproduce

1. Update the 1Password CLI binary via Homebrew (which will update the binary's path)
2. The Raycast extension, unless its configuration is updated manually, will fallback to showing the README, which tells the user how to install the CLI.

### Current Behaviour

1. Update the 1Password CLI binary via Homebrew (e.g. from v2.24.0 to v2.26.0)
2. Launch Raycast and activate the 1P extension
3. See Extension README

### Expected Behaviour

1. Update the 1Password CLI binary via Homebrew (e.g. from v2.24.0 to v2.26.0)
2. Launch Raycast and activate the 1P extension
3. Raycast 1Password Extension should automatically update the path for the CLI if it's been changed.

**Comment by Luk4h** [comment]
You have an interesting location for the program, when you run `where op` on your terminal it also points to `/opt/homebrew/Caskroom/1password-cli/2.26.0/op`? Mine even after updating keeps on `/opt/homebrew/bin`.

**Comment by chrismessina** [comment]
When I run `where op` I get:

```
/opt/homebrew/bin/op
```

**Comment by Luk4h** [comment]
You should write that text in the 1Password CLI property within the extension config.

In the latest release, it automatically checks that path to see if it is installed using Homebrew. The disk location is different from the command location.

@raycastbot close this issue
