### ISSUE TITLE
[1Password] Update documentation 1P Settings screenshot

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#11435]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

The [screenshot](https://github.com/raycast/extensions/blob/main/extensions/1password/assets/1password-settings.png) of 1Password Settings UI in the README file is out of date.

You can use this replacement:

![2024-03-21 (17 53 21) 1Password](https://github.com/raycast/extensions/assets/22610/fa8a7b47-01c0-4d93-bdb9-d932ac8e8701)

### Who will benefit from this feature?

Anyone that uses the 1Password extension.

**Comment by Luk4h** [comment]
Thanks, this should be now included with the pull request #11605 merged.

**Comment by Luk4h** [comment]
@raycastbot close this issue
