### ISSUE TITLE
[spotify-player] add DJ Command 🎶

### ISSUE THREAD

**Issue by randallwc** [raycast/extensions#11437]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Add an option called "DJ" to immediately jump into the DJ channel of spotify.

**Comment by YodaLightsabr** [comment]
It would be cool to see this functionality come to Raycast!

**Comment by thomaslombart** [comment]
That would be a great feature! But it's unfortunately not available in the Spotify API. They have a [community](https://community.spotify.com/) where you can add feature requests so it's probably worth it asking it there. I'll close it out in the meantime to keep the backlog clean 🙂
