### ISSUE TITLE
[Spotify Player] add warning for adding a duplicate song to a playlist 

### ISSUE THREAD

**Issue by randallwc** [raycast/extensions#11438]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

It would be nice to have a visual warning if I add the same song twice to one playlist.

### Who will benefit from this feature?

People who add one song to multiple playlists.

**Comment by RowMur** [comment]
I'll pick this one up

**Comment by RowMur** [comment]
So I've been looking into this one this evening and I'm not sure that it is worth implementing. TLDR there isn't a very good API query for this use case and so it would be super slow.

You can check whether a song is in a user's saved tracks by a using the `/me/tracks/contains` endpoint. However, there is no equivalent for a playlist. So, the next best option I can see is to get the list of tracks and check the IDs of the tracks against the ID of the track we are trying to add. There is a GraphQL esque input on the playlist tracks API calls which means we can save on the amount of data we are fetching. However, even when only fetch track IDs, it's capped to 50 tracks per call. 

This means that we would have to make two sequential API calls.

1. Fetch total tracks count
2. Fetch all tracks (in batches of 50 concurrently)

So, it's possible and I don't think it would be unusably slow, but I don't think it's worth giving up the snappy experience for. Plus, I'd imagine the use case for adding to a playlist via Raycast is primarily for new songs that wouldn't already be in their playlist. If they are managing their playlists I would've thought they'd more likely go the full app.

@mattisssa @peduarte Is it justifiable to close this issue?

**Comment by thomaslombart** [comment]
Thanks a lot for looking into it @RowMur, let's close this out then. It's better to have a snappy experience! ☺️
