### ISSUE TITLE
[Connect to VPN] Cannot connect to VPN

### ISSUE THREAD

**Issue by kjeldahl** [raycast/extensions#11442]
### Extension

https://www.raycast.com/rasmusbe/connect-to-vpn

### Description

It cannot connect to the VPN I have setup in System Preferences. If I have the VPN tab open I can see that the radio button if very briefly move to the right and then back, and an error message is shown:

<img width="260" alt="image" src="https://github.com/raycast/extensions/assets/19719/ae5479db-2929-4e81-9c9f-08d06cc5a3f9">

I looked in the source code for this extension and found the command which is used to connect and running it from the command line gives the same error. `/usr/sbin/networksetup -connectpppoeservice "Home"`

Connecting to the VPN by clicking the radio button in System Preferences | VPN works just fine.

I'll keep googling for a solution and update this issue if I find a solution.

### Steps To Reproduce

1. Add a L2TP over IPSec VPN profile
2. Connect to it using the extension
3. See the error

### Current Behaviour

It flicks the button on and off and shows and error

### Expected Behaviour

I connects to the VPN

**Comment by rasmusbe** [comment]
Not sure if it helps, but this is from the networksetup help command

> Any command that takes a password, will accept - to indicate the password should be read from stdin.
>  
>The networksetup tool requires at least admin privileges to change network settings. If the "Require an administrator password to access system-wide preferences" option is selected in System Preferences > Security & Privacy, then root privileges are required to change network settings.

Could it be either that the VPN requires password input or that you require admin password? The setting was hidden under the Advanced button in Security & Privacy in my system.

**Comment by rasmusbe** [comment]
If that doesn't help I would say that the bug is in the MacOS built in networksetup command and not in the extension, and probably not something we can solve 😞

**Comment by kjeldahl** [comment]
@rasmusbe Thanks you for the response. Admin password is not required and I cannot supply the password to the networksetup command, nor does it ask for one.

I guess I'll just have to use the System Preferences panel to connect. (I have also tried using `scutil` and `vpnutil` (https://github.com/Timac/VPNStatus))
