### ISSUE TITLE
[Obsidian] ...extension not working

### ISSUE THREAD

**Issue by Pierreml2021** [raycast/extensions#11445]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

Mac environnement, 

### Current Behaviour

not opening Obsidian

### Expected Behaviour

Obsidian should open on targettes note

**Comment by sammcj** [comment]
I think I may be having a similar issue https://github.com/raycast/extensions/issues/11741
