### ISSUE TITLE
[Apple Notes] cannot open note

### ISSUE THREAD

**Issue by RihardsVeters** [raycast/extensions#11447]
### Extension

https://raycast.com/tumtum/apple-notes

### Description

Tried to open note and it shows:

Failed to open the note with error:
Error: Command failed with exit code 1: osascript -e tell application “Notes” set theNote to note id “x-coredata://86FAB9A6-7948-42E5-9A71-96C66DB482BA/ICNote/p179” set theFolder to container of theNote show theFolder show theNote activate end tell 50:121: execution error: Notes got an error: Can’t get note id “x-coredata://86FAB9A6-7948-42E5-9A71-96C66DB482BA/ICNote/p179”. (-1728)

### Steps To Reproduce

No idea how to reproduce it, because other notes are opening for me..

**Comment by thomaslombart** [comment]
Have you granted the permission like described [over here](https://github.com/raycast/extensions/issues/11278#issuecomment-2015294842)?

**Comment by thomaslombart** [comment]
I'm closing this issue to maintain a clean backlog. Feel free to comment it if you still have the problem.

**Comment by mightyjoe781** [comment]
Hi, I am facing this issue, Notes got an error: Can’t get note id "64E36DA8-9468-4C87-AEEE-65924883D573". (-1728)
I read up the code -1728, but in my settings I am able to see that the raycast has full access.

<img width="467" alt="Image" src="https://github.com/user-attachments/assets/4e3cda83-0563-4d65-aa40-31de737389f3" />

<img width="466" alt="Image" src="https://github.com/user-attachments/assets/7e5ba782-bb58-4993-98df-c6f4a9e36f34" />

I have reinstalled raycast multiple times, removing completely & Restarting multiple times.
NOTE: all other extensions seems to work like apple-mail, apple-reminders. Even all commands related to apple-notes, seem to be working fine, except ask apple-notes.

**Comment by mightyjoe781** [comment]
I looked at your code and tried debugging, seems like something is going on my machine as this call is failing with above -1728 code
```applescript
tell application "Notes"
	set theNote to note id "64E36DA8-9468-4C87-AEEE-65924883D573"
	return body of theNote
end tell
```
