### ISSUE TITLE
[Ollama AI] Add Web Search Data on Context Window

### ISSUE THREAD

**Issue by sagarpalsapure** [raycast/extensions#11444]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

This feature would allow users to conduct web searches using embedding models like nomic-embed-text

### Who will benefit from this feature?

This feature would benefit individuals who use Raycast Ollama AI extension for web content research, valuable to have a search function with embedding support available.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot rename this issue to "[Ollama AI] Add Web Search Data on Context Window"

**Comment by MassimilianoPasquini97** [comment]
Hi @sagarpalsapure, as I have implemented querying text and pdf document with /file tag I was looking at doing the same but with web result maybe with a /web tag. At the time I was evaluating Google Search API or Bing API for the Search Engine part but neither of those offere a decent free personal use plan so implementing this feature with one of the major web search engine is out of the question.

[Brave Search API ](https://brave.com/search/api/) could be an alternative solution. It offer a decent free personal use plan with 1 query/second and 2000 query/month. Obviously the user will need to generate it's own token. An other advantage is that is Brave Search API is already implemented on langchain library (only on python for now) that I'm already using for the document query feature.

Nowadays I have very little time to spend for implementing new feature on this extension but when I will have it I will certainly looking for implementing this feature.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot assign me
