### ISSUE TITLE
[Mozilla Firefox] ...

### ISSUE THREAD

**Issue by andrewawilley** [raycast/extensions#11449]
### Extension

https://www.raycast.com/crisboarna/mozilla-firefox

### Description

Bookmarks added after adding the extension to Raycast are not showing in search results

### Steps To Reproduce

1. Install Firefox extension
2. Confirm Search Bookmarks shows current bookmark inventory
3. Add new bookmark to Firefox
4. Note that the new bookmark is not available

### Current Behaviour

Bookmarks added to Firefox after installing the Raycast extension are not available in subsequent bookmark searches

### Expected Behaviour

Bookmarks added to Firefox should be available in Raycast extension "Search Bookmarks" results

**Comment by theherk** [comment]
This is actually still an issue.
