### ISSUE TITLE
[Wi-Fi] not able to get Wifi status

### ISSUE THREAD

**Issue by that70schris** [raycast/extensions#11453]
### Extension

https://www.raycast.com/koinzhang/wi-fi

### Description

Scan Wifi and Wifi Signal not working at all

### Steps To Reproduce

1. install with macOS 14.3.1
2. observe everything working fine
3. update macOS to 14.4
4. only command working is now "Toggle Wifi"

### Current Behaviour

San Wifi says "No Wifi"

Wifi Signal has Wifi disconnected icon

**Comment by j3lte** [comment]
The issue here is that the package is using `node-wifi`, which hasn't been updated for a couple of years: https://www.npmjs.com/package/node-wifi

I experienced the same issue and investigated the package. It runs the following command to get the info: 

`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport --getinfo`

If you run this in your terminal, you will get the following message:

```
WARNING: The airport command line tool is deprecated and will be removed in a future release.
For diagnosing Wi-Fi related issues, use the Wireless Diagnostics app or wdutil command line tool.
```

So this is not an easy fix, we might have to replace the `node-wifi` package with some own solution

**Comment by that70schris** [comment]
hmm, not sure if this helps but I'm using this script for toggling Wifi instead:

```
interface=$(networksetup -listnetworkserviceorder | grep 'Wi-Fi' | grep 'en' | sed -E 's/.*(en[0-9]).*/\1/')

if [[ $(networksetup -getairportpower $interface) =~ 'On' ]]; then
	networksetup -setairportpower $interface off
else
	networksetup -setairportpower $interface on
fi
```

**Comment by koinzhang** [comment]
Currently almost all major wifi node libraries use the above command to get wifi, I haven't found a better wifinode library for the time being, if you guys have a good recommendation, feel free to let me know!

**Comment by guiltyvictim** [comment]
Still not working as of June.

**Comment by j3lte** [comment]
@guiltyvictim and still not possible to fix because Apple doesn't provide a way to get the status programmatically. This is not so much an issue with the extension, but with Apple

**Comment by VladislavGatsenko** [comment]
I was looking for a solution to a different problem, but maybe this will help with a solution. Just execute in the console:

system_profiler SPAirPortDataType

**Comment by koinzhang** [comment]
Since Apple no longer provides the Wifi tool, the Scan Wifi command is no longer available

**Comment by koinzhang** [comment]
Wifi Signal has been changed to the Menubar Wifi command, which now displays the following information
<img width="298" alt="image" src="https://github.com/user-attachments/assets/2cf9ff38-53fd-4c69-88a5-f8c4d58b3922">
