### ISSUE TITLE
[1Password] ... Extension not working

### ISSUE THREAD

**Issue by cslmn** [raycast/extensions#11461]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Extension is not working despite following all steps (downloaded the 1Password CLI tool and enabled Command-Line Interface in the app)

### Steps To Reproduce

downloaded the 1Password CLI tool and enabled Command-Line Interface in the app, then downloaded the 1password raycast extension but its not letting me access to passwords

**Comment by cslmn** [comment]
Appreciate it, it worked.

Thanks a lot

Charles

**Comment by Luk4h** [comment]
@raycastbot close this issue
