### ISSUE TITLE
[Coffee] ...

### ISSUE THREAD

**Issue by PawGangsta** [raycast/extensions#11463]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

Whenever i activate "caffeinate" the extension doesn't really inform whether the action has been taken or not, which can be easily fixed with some UX :)

### Steps To Reproduce

1. try to caffeinate anything

**Comment by pernielsentikaer** [comment]
There should be a HUD in the bottom middle of your screen showing this, doesn't that happen?

**Comment by PawGangsta** [comment]
Hello,

Thank you for getting back to me :) and no, there is no HUD in the bottom middle of my screen, no matter how many times i click Caffeinate nothing changes

Khaled Adel
Product Designer

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error, please notify the system manager. Please consider the environment before printing this email.

**Comment by pernielsentikaer** [comment]
You should see this 
![Raycast03042024-NzLvLTSo png@2x](https://github.com/raycast/extensions/assets/38033107/1b05a921-0293-470b-bb5e-86f4158cae18)

**Comment by xilopaint** [comment]
@raycastbot close this issue
