### ISSUE TITLE
Open Anybox while not running in the background.

### ISSUE THREAD

**Issue by eyalevy23** [raycast/extensions#11470]
### Extension

https://www.raycast.com/anybox/anybox

### Description

Hello, I use Anybox to store all my thoughts and things I am currently working on but don't have time to deal with now. I really like the idea of having everything in one place. The issue is that when Anybox is not open in the background and you press on one of the commands, it gives an error. Is there a way to open the Anybox app in the background? Thanks a lot for all your work.

### Who will benefit from this feature?

Anyone.

**Comment by francisfeng** [comment]
You can open the app by pressing ⌘ + T → Return when you saw the alert from Raycast.

@raycastbot close this issue
