### ISSUE TITLE
[One Thing] Adding marquee feature to text

### ISSUE THREAD

**Issue by sai-educ** [raycast/extensions#11475]
### Extension

https://www.raycast.com/pernielsentikaer/one-thing

### Description

Hello, is it possible to add marquee (scroll) feature to the text input? For example, if I input "physics simulations 101", the label will continuously scroll from right to left? 

### Who will benefit from this feature?

This is particularly beneficial for people who need to focus on just one item at a time, and to be reminded of to-do tasks constantly through out the day. Any text label in motion drives eye gaze towards it––as a reminder mechanism.

**Comment by thomaslombart** [comment]
@sai-educ This isn't possible with the Raycast API right now. I'll suggest that improvement to the team and see what we can come up with.

**Comment by thomaslombart** [comment]
So, it's something that makes sense, and we may implement that further down the road. We're not sure when yet as it's a relatively low-priority feature 🙂
