### ISSUE TITLE
[Gitlab] Assigned MRs in archived projects

### ISSUE THREAD

**Issue by eivasch** [raycast/extensions#11486]
### Extension

https://www.raycast.com/tonka3000/gitlab

### Description

Extension menu bar shows, that I have 4 assigned merge requests. But Gitlab shows only 2. It's because other 2 MRs are in archived  project

### Steps To Reproduce

1. In Gitlab create project
2. Create MR in it and assign it to oneself
3. Archive project
4.  This MR will be shown in menu bar in lists of MRs

### Current Behaviour

MRs from archived projects are shown

### Expected Behaviour

MRs from archived projects are not shown

**Comment by gav-fyi** [comment]
Hi,

I'd be interested in re-opening this issue, and potentially providing a fix for it. 

However, the GitLab API doesn't support filtering out archived projects. 😩 

The only solution, as far as I can see, is to make 2 API requests. One for the list of archived|active projects, and a second for the MRs, and cross reference them. 

Does this solution add too much of an overhead, or is it an acceptable solution? 

Thanks,
Gav
