### ISSUE TITLE
[Apple Reminders] Add support for smart lists

### ISSUE THREAD

**Issue by jenningsb2** [raycast/extensions#11482]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

I have a smart list dedicated to my work tasks that are due within the next three days. I would prefer to focus mainly on the tasks in that list rather than the default 'Today' or 'Scheduled' lists.

### Who will benefit from this feature?

Anyone who leverages Apple's smart lists.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Unfortunately, Apple doesn't return smart lists in their APIs. Smart lists are a complex feature to replicate given the number of rules involved, so I'll close this one as "Not Planned."
