### ISSUE TITLE
[Deepcast] Formality support

### ISSUE THREAD

**Issue by jimmyn** [raycast/extensions#11484]
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

DeepL allows specifying formality in the API request. It would be great to add support for this parameter

<img width="1146" alt="image" src="https://github.com/raycast/extensions/assets/5391775/ddaa6a63-347f-4c84-a5bd-448521890a8c">

### Who will benefit from this feature?

Users that use languages that have formal and informal translations, like Spanish for example

### Anything else?

https://www.deepl.com/docs-api/translate-text

**Comment by erics118** [comment]
keep open. I'll hopefully get to it at some point

**Comment by erics118** [comment]
@raycastbot keep this issue open

**Comment by erics118** [comment]
@raycastbot assign me

**Comment by erics118** [comment]
Forgot to tag, fixed in #15511

**Comment by erics118** [comment]
@raycastbot close this issue
