### ISSUE TITLE
[Things] "Show Today in Menu Bar" error

### ISSUE THREAD

**Issue by reidroman** [raycast/extensions#11494]
### Extension

https://www.raycast.com/loris/things

### Description

I'm quite excited about this feature but it hasn't worked in a while. Error below, I've tried reloading command, reinstalling extension, nothing's worked yet. Thanks for looking at it.

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

1. Install and configure extension
2. Run command "Show Today in Menu Bar"
3. Error

**Comment by thomaslombart** [comment]
Thanks for reporting the issue. How many lists and todos do you have in your today view?

**Comment by reidroman** [comment]
44 tasks, 6 are in an Area. My calendar is synced as well fwiw

**Comment by thomaslombart** [comment]
Yeah, doesn't seem to be a problem 😅

Could you share a recording?

**Comment by reidroman** [comment]
Worked when I started recording it after another reinstall 🤷

**Comment by thomaslombart** [comment]
All right, I'll mark this issue as closed but feel free to reopen the issue if you still face the error.
