### ISSUE TITLE
[System Monitor] add tab for GPU usage

### ISSUE THREAD

**Issue by uigywnkiub** [raycast/extensions#11506]
### Extension

https://www.raycast.com/hossammourad/raycast-system-monitor

### Description

Add GPU string

**Comment by lucasmezencio** [comment]
@uigywnkiub could you give us more context?

**Comment by uigywnkiub** [comment]
> @uigywnkiub could you give us more context?

<img width="836" alt="image" src="https://github.com/raycast/extensions/assets/29861553/b19e20d1-d46d-40c4-b346-36e3cd70031e">
Add GPU monitoring into this

**Comment by lucasmezencio** [comment]
@uigywnkiub I'm really sorry, but I'm afraid I still didn't get you. Do you have any example?

**Comment by uigywnkiub** [comment]
> @uigywnkiub I'm really sorry, but I'm afraid I still didn't get you. Do you have any example?

Add a GPU tab to show all the characteristics of the video card, as it is with the CPU. I don't know how else to explain it.

**Comment by ivribalko** [comment]
I'd like to have that too! A dedicated tab for GPU to see how much of it CrossOver / Ollama might be using.

**Comment by ivribalko** [comment]
@uigywnkiub could you update the title of the issue so that it says something like "[System Monitor] add tab for GPU usage" instead of "[System Monitor] ..."
