### ISSUE TITLE
[Figma File Search] Could not load pages

### ISSUE THREAD

**Issue by mustafakurt** [raycast/extensions#11501]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

Everything is setup correctly. All of a sudden it stopped working. I cannot search my Figma files anymore. I've tried to create a new token in Figma, in case the token would be expired (the setting is set to not expire at all), but that didn't work either. 

### Steps To Reproduce

The config is setup correctly. Personal Access Token and Team ID is correct. When I run the extension it says: could not load pages.
![image](https://github.com/raycast/extensions/assets/11297888/09d44e30-42c7-4145-929c-e11ef0ed2b6e)

**Comment by michaelwschultz** [comment]
@mustafakurt I haven't seen this issue before. I'll try to reproduce it. Can you maybe give me some more information on anything that may have changed before you received this error? Do you use multiple team IDs by any chance?
