### ISSUE TITLE
[Bitwarden Vault] Client ID and Client Secret are regularly deleted.

### ISSUE THREAD

**Issue by theherk** [raycast/extensions#11516]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Regularly when I open the extension, the Client ID and Client Secret are again required. I'm not sure how those preferences are being lost.

### Steps To Reproduce

1. Open Search Vault
2. ...

That's it.

It could be related to the fact that I synced Raycast on two machines, but that doesn't seem to have an impact on any of my other extension configurations. I have looked through the source code, but nothing jumped out at me as a potential cause.

### Current Behaviour

I have to reenter these parameters.

### Expected Behaviour

I don't have to reenter these parameters.

**Comment by jomifepe** [comment]
Hey, thanks for reporting. This doesn't seem like an extension bug, as we don't have any kind of control over the preferences, so that's most likely related to your setup or Raycast itself.

**Comment by jomifepe** [comment]
@raycastbot close this issue
