### ISSUE TITLE
[Figma File Search] Handle URL format change.

### ISSUE THREAD

**Issue by danhollick** [raycast/extensions#11514]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

On April 1st Figma is making some changes to their URL structure that I suspect will break this extension. I've attached the changes detailed in an email they sent out to developers.

 It's unclear if the current format will still be supported behind some versioning OR if the new format works already. 
 
<img width="704" alt="Screenshot 2024-03-27 at 06 56 32" src="https://github.com/raycast/extensions/assets/13898607/c9699eb8-c047-49a6-90ce-e895bc3b845c">

### Steps To Reproduce

There are no steps to reproduce.

**Comment by GLaDO8** [comment]
@danhollick the URLs for fetching projects inside a team and files inside a project remain unchanged. It also looks like we can keep using The `https://www.figma.com/file/:file_key` URL scheme to open a file URL in the desktop app or web according to the memo. So I don't think we need to make any changes. 
![CleanShot BPJIrjIKon2024-03-28at21 34 24](https://github.com/raycast/extensions/assets/22849100/57129426-31bc-4863-bf2d-939147997f39)

**Comment by danhollick** [comment]
@GLaDO8 okay cool, just thought I'd flag this in advance of the change. I'll close the issue.
