### ISSUE TITLE
[Visual Studio Code - Project Manager] Asks for "Visual Studio Extension Project Manager" extension even if already installed

### ISSUE THREAD

**Issue by marckohlbrugge** [raycast/extensions#11520]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

The recent update broke this Raycast extension for me. Before, it was working fine.

I'm using it with Cursor with the Visual Studio Extension Project Manager extension installed. However, when trying to use this Raycast extension, I get the error message:

> To use this extension, the Visual Studio Extension Project Manager is required and at least one project must be saved in the Project Manager.

I double checked the following:

- [x] Visual Studio Extension Project Manager is installed in Cursor
- [x] Raycast extension is configured to use Cursor
- [x] Restarted Raycast 

### Steps To Reproduce

1. Install Cursor
2. Install "Visual Studio Extension Project Manager" in Cursor
3. Set this Raycast's extension "VSCode" setting to Cursor
4. Open the command
5. Get the error message

**Comment by gadenbuie** [comment]
Apologies @marckohlbrugge, this must be the result of the changes I made in #11383. Can you open the extension settings and confirm that "Projects Location" is **unset**? In Cursor, can you confirm that the `projectManager.projectsLocation` setting is empty? Can you also confirm that there are `projects*.json` files in the expected extension storage location:

```bash
ls ~/Library/Application\ Support/Cursor/User/globalStorage/alefragnani.project-manager
```

**Comment by marckohlbrugge** [comment]
@gadenbuie Thank you for the super fast reply 🙌

Unsetting "Projects Location" fixed it!

I think what happened is something like this: the extension got auto-updated and stopped working. The reason it stopped working is because it forgot the setting to use Cursor, and instead pointed to the default VSCode which I have installed but doesn't have the Project Manager extension installed.

To try and fix this, I must have set both "Projects Location" and "VSCode" at the same time leading to this new issue.

All good now 👍

**Comment by eduwass** [comment]
I'm also using Cursor and the above comment solved it for me, thanks @marckohlbrugge and @gadenbuie
