### ISSUE TITLE
[Bitwarden Vault] Autofill action

### ISSUE THREAD

**Issue by RihardsVeters** [raycast/extensions#11530]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Wouldn't it be possible to add autofill action when I'm searching my vault? Raycast now have it's own browser extension, so Raycast could see those input fields in current page.

### Who will benefit from this feature?

Everyone who's using Raycast and Bitwarden cause Bitwarden extensions autofill is awfull.

**Comment by jomifepe** [comment]
Hey, thanks for the suggestion. The description of the new companion extensions is "Summarize and ask questions about your active browser tab. Bring the context of any webpage to Raycast AI", so it doesn't seem like it will be able to interact with the browser anytime soon 🙂

**Comment by RihardsVeters** [comment]
Lets hope, that Raycast team also helps this to happen make necessary changes to browser extension.

**Comment by jomifepe** [comment]
@raycastbot close this issue
