### ISSUE TITLE
[Linear] ...

### ISSUE THREAD

**Issue by edufletch** [raycast/extensions#11549]
### Extension

https://www.raycast.com/linear/linear

#### Error:
```
FetchError: request to https://linear.oauth.raycast.com/token failed, reason: unable to get local issuer certificate

    at withAccessToken(lM)
mI:create-issue.tsx:25:46

---
22:   )

### Steps To Reproduce

1. On 2021 14-inch Macbook Pro
2. Running Sonoma 14.4.1
3. Trying to use Linear extension to create an issue. It prompts me to connect, I click to do so, which opens a webpage saying I successfully connected to Linear, but on Raycast itself it says there was an error.


![Screenshot 2024-03-28 at 10 25 50 PM](https://github.com/raycast/extensions/assets/17969569/31bb44c0-a246-4616-9d1d-263bc609e691)
![Screenshot 2024-03-28 at 10 26 04 PM](https://github.com/raycast/extensions/assets/17969569/fdabfc48-376e-4abf-882a-40583abcc6d4)
![Screenshot 2024-03-28 at 10 28 52 PM](https://github.com/raycast/extensions/assets/17969569/e011707a-78b7-4d01-9be8-434e249db9e3)


### Current Behaviour

Unable to connect to Linear via Raycast extension.

### Expected Behaviour

To be able to connect to Linear when prompted by Raycast extension, and able to create Linear issues via Raycast extension.

**Comment by mathieudutour** [comment]
Are you using some kind of VPN/firewall/proxy?

**Comment by edufletch** [comment]
Probably - it's my work computer. We have zscaler installed (I don't know if that is a VPN, firewall, or proxy), which I know has caused issues for somethings in the past. But for Raycast, all other extensions have always worked fine - looks like this one is trying to pull a dependency that's blocked for some reason? 🤷‍♂️

**Comment by edufletch** [comment]
Unrelated, and I'll google this now, but I am subscribed, but didn't get a ping that I had a response. Anyone know why, or where I should expect that alert? I guess I had assumed email, but nothing ever showed up. Just want to make sure I see any responses so I can reply right away. Thanks!
