### ISSUE TITLE
Update Apple Music Extension

### ISSUE THREAD

**Issue by j10231** [raycast/extensions#11540]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

Design the extension to resemble the style of Spotify's extension.

### Who will benefit from this feature?

Every extension user

### Anything else?

<img width="1371" alt="84803425ead0227323000fb75c88955442434c62647caa8c24fe7bf9f4b78197" src="https://github.com/raycast/extensions/assets/133256674/f16eef01-18f9-4292-af59-a3b0a0965735">

**Comment by rawnly** [comment]
can't be done due to api limitations 😅

**Comment by rawnly** [comment]
@raycastbot close this issue
