### ISSUE TITLE
Recent list won’t sync with extension

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#11547]
### Extension

https://www.raycast.com/dch09/ableton-live

### Description

Yesterday I noticed that extension stopped syncing with Live's recent projects list.

Btw it seems that extension for Supernotes app doesn’t sync as well, could it be a global Raycast issue?

### Steps To Reproduce

1. Open a few projects in Live
2. Clear recents list
3. Close and re-open Live
4. Launch Raycast extension

### Current Behaviour

Shows completely different (old?) recents list

**Comment by dch09** [comment]
Recent projects list in this extension is not the same as the one in app menu bar, so clearing recent projects there won't affect extension results.

**Comment by dch09** [comment]
Results are built as can be seen in source code - search for **.als** file, sort them by edit date

**Comment by romanskorobagatko** [comment]
Thank you for the explanation!
