### ISSUE TITLE
[TidyRead - Streamline Your Daily Reading] "Source Link" is currently pointing to an incorrect article

### ISSUE THREAD

**Issue by alexandertsukanov** [raycast/extensions#11557]
### Extension

https://www.raycast.com/jaredliu233/tidyread---streamline-your-daily-reading

### Description

Dear Development Team,

I've observed that the "Source Link" is currently pointing to an incorrect article. It should ideally be positioned under the corresponding article, which is not the case at the moment.

Thanks.

### Steps To Reproduce

1. Install the extension
2. Wait until "Daily Read" command will fetch articles
3. Try to select the article an observe the behaviour 

### Current Behaviour

Dear Development Team,

I've observed that the "Source Link" is currently pointing to an incorrect article. It should ideally be positioned under the corresponding article, which is not the case at the moment.

Thanks.

### Expected Behaviour

The source link correctly points to the intended article.

**Comment by DophinL** [comment]
> ### Extension
> https://www.raycast.com/jaredliu233/tidyread---streamline-your-daily-reading
> 
> ### Description
> Dear Development Team,
> 
> I've observed that the "Source Link" is currently pointing to an incorrect article. It should ideally be positioned under the corresponding article, which is not the case at the moment.
> 
> Thanks.
> 
> ### Steps To Reproduce
> 1. Install the extension
> 2. Wait until "Daily Read" command will fetch articles
> 3. Try to select the article an observe the behaviour
> 
> ### Current Behaviour
> Dear Development Team,
> 
> I've observed that the "Source Link" is currently pointing to an incorrect article. It should ideally be positioned under the corresponding article, which is not the case at the moment.
> 
> Thanks.
> 
> ### Expected Behaviour
> The source link correctly points to the intended article.

Hi, Alex, I am very glad that you are still using tidyread. 😇  Could you please provide the error link you mentioned? And also the corresponding RSS link.

In addition, you can try to turn off this option.
<img width="1000" alt="image" src="https://github.com/raycast/extensions/assets/8707316/f43f1faa-0579-4672-bd5d-058bc19749a3">

By the way, I am developing a Chrome extension version. It is estimated to release the MVP by the end of April. I will invite you to use it then! If convenient, you can join the waitlist here https://tidyread.ai 🥰

**Comment by alexandertsukanov** [comment]
Hey, @DophinL !
It seems that in the last version, the issue does not appear here.

**Comment by alexandertsukanov** [comment]
I'm glad to use this extension for Raycast. It is a very nice RSS aggregator. Do not stop the development of this extension. Thank you.

**Comment by DophinL** [comment]
> I'm glad to use this extension for Raycast. It is a very nice RSS aggregator. Do not stop the development of this extension. Thank you.

Absolutely! The Chrome extension is also under development and will continue to iterate. Looking forward to your use and feedback! @alexandertsukanov 

In addition, we hope to invite you to join our Discord. You are one of the earliest users of Tidyread! Your voice is really important for the the product! 

https://discord.gg/SYzFtQAn

**Comment by alexandertsukanov** [comment]
If you don't mind, I will close this issue since it is not reproducible in the latest version.

**Comment by DophinL** [comment]
Now Discord has just been established, currently not active, but will soon start operating! @alexandertsukanov
