### ISSUE TITLE
[Apple Notes] - Cannot search notes database image is malformed

### ISSUE THREAD

**Issue by gewoonseba** [raycast/extensions#11550]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

When I invoke the "Search notes" extension, I can no longer search my notes. Error in the screenshot below. To my knowledge, nothing about my setup has changed.
![CleanShot 2024-03-29 at 07 00 19@2x](https://github.com/raycast/extensions/assets/7049958/311ffefb-3c23-4e5c-a01b-87b73ad77ad8)

### Steps To Reproduce

1. Open raycast
2. Invoke "Search notes"

**Comment by thomaslombart** [comment]
This was supposed to be fixed last week. Could you run both `Check for updates` and `Check for Extension Updates` commands?

**Comment by gewoonseba** [comment]
That fixed it @thomaslombart thanks.

It was working for a long while before that, so I didn't think to check for updates.

**Comment by thomaslombart** [comment]
No worries!
