### ISSUE TITLE
[Coffee] Formatting issue caffeinateFor validation

### ISSUE THREAD

**Issue by julienmunio** [raycast/extensions#11559]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

Formatting issue of validation of action Caffeinate For:
`Caffeinating your Mac for 30m2h` and not `Caffeinating your Mac for 2h30m`

### Steps To Reproduce

On action `Caffeinate For` fill Hours and Minutes

### Current Behaviour

`Caffeinating your Mac for 30m2h`

### Expected Behaviour

`Caffeinating your Mac for 2h30m`

**Comment by xilopaint** [comment]
The issue has been resolved.

@raycastbot close this issue
