### ISSUE TITLE
[Office2PDF] Multiple files selection

### ISSUE THREAD

**Issue by eyalevy23** [raycast/extensions#11558]
### Extension

https://www.raycast.com/ARui/office2pdf

### Description

Very awesome extension! I really like it a lot. Perhaps you could add an option to select multiple files at once. It would be much more convenient if you could choose the file you marked in Finder instead of searching for the file within the extension window. Thank you.

### Who will benefit from this feature?

everyone

**Comment by ARui-tw** [comment]
@raycastbot rename this issue to "Multiple files selection"
