### ISSUE TITLE
[Word Count] Add multi-language support

### ISSUE THREAD

**Issue by KevinNNNNNNNNNNNN** [raycast/extensions#11561]
### Extension

https://www.raycast.com/itsmingjie/word-count

### Description

if i drop both english and chinese, it won't count the chinese character. 

### Who will benefit from this feature?

every other languages.

**Comment by itsmingjie** [comment]
@raycastbot rename this issue to "Add multi-language support"

**Comment by itsmingjie** [comment]
Will consider working on this when free!
