### ISSUE TITLE
[Ollama AI] Explain Code Command: "No selected text found"

### ISSUE THREAD

**Issue by lucianthorr** [raycast/extensions#11568]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

I've installed the Ollama extension but besides the "Chat with Ollama" command, the others don't seem to work.  Probably user error on my part but an explanation would be great.

### Steps To Reproduce

1. On MacOS with Raycast and the Ollama extension
2. Using the codellama model (but others were tried also)
3. Go to Raycast > Ollama > Explain Code Step By Step
4. This goes to a blank Raycast window with "No selected text found" at the footer.

### Current Behaviour

"No selected text found" at the footer and no clear way to select text for it to explain.

### Expected Behaviour

I'd expect either a window that I can paste code into or that it would show whatever is in my clipboard and allow me to select what I'd like explained.

**Comment by MassimilianoPasquini97** [comment]
For use the other commands you need to select the text you want to pass on te context before launching the command as the error message suggest. On the extension properties you can also set to use the text on the clipboard and the other input method as a fallback if the primary input source is empty.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue

**Comment by lucianthorr** [comment]
Thanks.  Now that I understand the expected behavior, I can say that the "Selected Text" input does not seem to work for me.  I select a block of code in VSCode or in Zed editors, press Cmd+Space to launch Raycast, go to Ollama: Explain Code Step by Step and it says that "No selected text found"
Clipboard does work for me though.

**Comment by MassimilianoPasquini97** [comment]
Have you give raycast the permission to access you clipboard and selected text?

**Comment by lucianthorr** [comment]
Thanks again!  You are correct.  
For future me's, go to Settings > Privacy & Security > Accessibility and enable Raycast for "Allow the applications below to control your computer."
