### ISSUE TITLE
[Format JSON] Add command to minify and stringify with slashes

### ISSUE THREAD

**Issue by DevanFischer** [raycast/extensions#11560]
### Extension

https://www.raycast.com/destiner/json-format

## Command Summary

The new feature/command would allow the inverse formatting option. It would take the formatted json, minify it, and stringify it with backslashes. 

## Example

We often need to grab minified JSON objects from a parameter store and modify them. 

My process is:

1. Copy the minified json
	`"{\"advertisingPlatform\":\"google\",\"campaignType\":\"leadGen\",\"sourceReference\":\"freeConnectUs\",\"leadReference\":\"itmCombo\",\"targetedProvider\":\"optimum\"}"`
3. Use the format command to make it more easily readable
	```json
	{
		"advertisingPlatform": "google",
		"campaignType": "leadGen",
		"sourceReference": "freeConnectUs",
		"leadReference": "itmCombo",
		"targetedProvider": "optimum"
	}
	```
5. Modify the data
	```json
	{
		"advertisingPlatform": "google",
		"campaignType": "leadGen",
		"sourceReference": "freeConnectCa",
		"leadReference": "itmSingle",
		"targetedProvider": "xyz"
	}
	```
7. Put it back in its minified form
	`"{\"advertisingPlatform\":\"google\",\"campaignType\":\"leadGen\",\"sourceReference\":\"freeConnectCa\",\"leadReference\":\"itmSingle\",\"targetedProvider\":\"xyz\"}"`
9. Save the updated string to the parameter store

### Who will benefit from this feature?

My company would love this feature, but I assume others using the format command could find use to put the formatted json back in the format it was found. I have created an AI command to do this for now, but it requires a few extra steps since the AI can not update my clipboard.

### Anything else?

https://github.com/raycast/extensions/assets/25752779/4b6f8151-c293-49b3-be30-f3ff6a2f979b

**Comment by CarlosEthika** [comment]
Hey @DevanFischer thanks for using the extension. This is an interesting ask but sure I can take it.

**Comment by devloos** [comment]
Hey @DevanFischer thanks for using the extension. This is an interesting ask but sure I can handle that for you.

**Comment by DevanFischer** [comment]
I know it may seem a little weird. I actually went ahead and pulled down your extension and added the command myself. If you want I can submit a PR later on for them to pull it in :)

**Comment by devloos** [comment]
yea @DevanFischer feel free thank you!
