### ISSUE TITLE
Could not resolve "@raycast/utils"

### ISSUE THREAD

**Issue by iodrift** [raycast/extensions#11570]
### Description

I've been building my first Raycast extension (a companion to the Timing App, using its REST API), and have hit a wall: 
```
entry points [src/start-task-tracking.tsx src/stop-task-tracking.tsx src/list-projects.tsx]
build failed (src/list-projects.tsx:2:25 import { useFetch } from "@raycast/utils";): Could not resolve "@raycast/utils"
```

I then tried to fork existing extensions using raycast/utils to see if the problem was isolated to my extension, but it wasn't. Same exact problem with, e.g., the Mullvad and Porkbun extensions.

Reinstalling raycast/utils, and uninstalling NPM, rebooting, then reinstalling have not fixed it.

### Steps To Reproduce

On macOS 14.3.1 (23D60), brew install npm, npm install && npm run dev in any extension that relies on @raycast/utils

### Current Behaviour

build failed (src/list-projects.tsx:2:25 import { useFetch } from "@raycast/utils";): Could not resolve "@raycast/utils"

### Expected Behaviour

Functioning extension

**Comment by mathieudutour** [comment]
Can you try running `npm ls @raycast/utils`? What does it return?
