### ISSUE TITLE
Bitwarden: Unlocking the vault using the extension locks the vault for the script-commands

### ISSUE THREAD

**Issue by MarcelBochtler** [raycast/extensions#1157]
# Extension – [Bitwarden](https://github.com/raycast/extensions/tree/main/extensions/bitwarden)

Authors: @pomdtr, @jomifepe, @daniel-stoneuk

## Description
When unlocking the vault with the "search vault" functionality of this extension, the vault is being locked for all [bitwarden script commands](https://github.com/raycast/script-commands/tree/master/commands/password-managers/bitwarden).

## Steps To Reproduce

1. Unlock your vault using [the unlock script-command](https://github.com/raycast/script-commands/blob/master/commands/password-managers/bitwarden/unlock.sh).
2. Use the bitwarden extension. E.g. the "Search Vault" command.
3. Try to run any bitwarden script-command. --> This will not work, as the vault is now locked for the scripts.

## The expected behavior
The extension and the script-commands should work independent of each other.
Using the extension should not "block" the usage of the script-commands.

### Raycast version

Version: 1.30.3

**Comment by pomdtr** [comment]
This is probably linked with the extension persisting the SESSION_ID from bitwarden. As soon as it generates a new one, it invalidate the one from the script commands, and vice-versa.

I'm not sure there is any solution to this except adding the script commands as extension commands.

**Comment by PSalant726** [comment]
Yea @pomdtr you're exactly right. Both the script commands and the extension use the same Bitwarden CLI tools to manage user sessions.

@MarcelBochtler The script command package and the extension were never intended to be used together; the extension was released after the script commands existed, when Raycast exposed the public extensions API. For the best user experience, the extension is the recommended source of truth these days (although the script commands _should_ still work just fine on their own). If there are script command features that are missing from the extension, I'd recommend opening an issue and/or PR to have them added.

**Comment by MarcelBochtler** [comment]
Thanks for the explanation.
The issue is not only that the extension does not work well with the script command package, it also does not work well with the `bw` CLI itself.
Whenever the extension was used, the CLI will be locked, which breaks any usage of it in scripts outside of Raycast.

> The script command package and the extension were never intended to be used together

That is fine, I'd be happy to unlock the extension and the `bw` CLI separately.

Unfortunately, as of now, the extension basically blocks / interferes with the usage `bw`.

**Comment by daniel-stoneuk** [comment]
Bitwarden's CLI will look for a `BITWARDENCLI_APPDATA_DIR` environment variable to decide where to store it's own database. We could specify this in the extension code as the support path so that the `data.json` file used by the Raycast extension is different to the default. Unfortunately this would log everybody out of the extension, requiring re-entry of the master password.

@MarcelBochtler would you be happy with a workaround? One I've come up with (and tested) is as follows

1) Create an executable with the following contents

```bash
#!/bin/bash
export BITWARDENCLI_APPDATA_DIR="/Users/[username]/Library/Application Support/Bitwarden CLI Raycast/"
/usr/local/bin/bw $@
```

2) Create the directory above (Replace /usr... with `/opt/homebrew/bin/bw` if on M1)
3) Set the Bitwarden extension to use this executable in Raycast preferences

I can't confirm how secure this is, in particular if the bash script introduces any security issues. If you know a better way to run an executable with an environment variable please let me know!

If there's demand we could add a preference to the Bitwarden extension to set `BITWARDENCLI_APPDATA_DIR` - it would be a couple lines of changes, what do you think @pomdtr?

**Comment by pomdtr** [comment]
@daniel-stoneuk This is a smart idea, but it is not documented in the bitwarden API docs. So it could potentially break after updating the cli. 

I have another idea. We could allow the user to set it's own BW_SESSION variable in the raycast pref. The user would then be able to share both in the script commands, the extension and the bitwarden cli.

**Comment by PSalant726** [comment]
I feel strongly that changes should not be made to encourage simultaneous use of both the script commands and the extension, especially if it would require confusing users with additional extension preferences that would rarely apply. I would rather see the extension updated to add any features enabled by the script commands that are currently missing.

**Comment by pomdtr** [comment]
I feel like using the extension should not stop you from using the cli.

Using a custom BITWARDENCLI_APPDATA_DIR location would isolate the extension, allowing you to use both. It sounds like the right solution to me.

**Comment by PSalant726** [comment]
Yes, I agree that that change should be made; the extension should be isolated so as not to interfere with CLI commands. My comment was in reference to:

> I have another idea: we could allow the user to set it's own BW_SESSION variable in the raycast pref. The user would then be able to share it both in the script commands, the extension and the bitwarden cli.

I believe this change can and should be transparent to users.

**Comment by daniel-stoneuk** [comment]
>This is a smart idea! It is not documented in the bitwarden API docs, so it could potentially break after updating the cli, but this is unlikely.

I've found a mention elsewhere in the bitwarden docs, so we should be good to use it! https://bitwarden.com/help/data-storage/#cli

**Comment by pomdtr** [comment]
Perfect !
