### ISSUE TITLE
Window Management - Add Eighths

### ISSUE THREAD

**Issue by jason-simard-sagewright** [raycast/extensions#11588]
### Extension

https://www.raycast.com/extensions/window-management

### Description

The current implementation of Window Management provides an extensive list of features to move windows left, right, centre, bottom, top etc.  The current options can divide the monitor into halves, thirds, quarters or sixths.  

My request, because it's all about me, is to offer the exact same functionality as currently available with six frames but divide the monitor into eighths, 2 rows of 4 columns.  Then offer the ability to move/throw any window to any of the eight "frames".  Or a grouping of those eight "frames".  Like "Middle 4" to move the current app window to the middle 4 frames and have 4 more frames in each corner around the main window.

Like I said, I'm selfish and it's all about me.  Until I get the time to write an extension for "eighths", I thought I'd request a feature from the experts.

### Who will benefit from this feature?

Anyone with an ultra wide 5K monitor who doesn't need huge windows and prefers ultra control over window placement.

### Anything else?

![Screenshot 2024-04-01 at 15 26 20](https://github.com/raycast/extensions/assets/42213928/079f8e1b-05a7-4abc-a5b2-d2d68b8c66b3)

**Comment by wd** [comment]
My request is to add support for allowing people to customize the window size and position themselves. I need an action to center the window and resize it to leave some space at the top and bottom. 

something like below
<img width="850" alt="image" src="https://github.com/raycast/extensions/assets/58177/0f0fc0ad-b569-498c-b539-189d40f80359">

**Comment by wd** [comment]
oh it seems `almost max` with 60% could fulfill my requirement. 
<img width="293" alt="image" src="https://github.com/raycast/extensions/assets/58177/ec33132b-87f2-44d1-8f04-2de36a132875">

**Comment by 1activegeek** [comment]
I will also add that I'd love to see this added in. Right now I have to rely on using Moom to achieve this - but I'd love to consolidate and get rid of Moom. I have a Samsung Odyssey 57" widescreen ... it's kind of a requirement 😄
