### ISSUE TITLE
[Spotify Player] Make search show songs before artists

### ISSUE THREAD

**Issue by adisidev** [raycast/extensions#11583]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Whenever I use search, it is usually to queue a song. So I was thinking, is there any way to just show songs by default? I tried using Command + P, but that always resets to artists? Is there any way I can make it stay or have songs come up first?

**Comment by belyakov-am** [comment]
![image](https://github.com/raycast/extensions/assets/43389005/a681df9c-c440-4af2-9489-27cccc8a565d)

One workaround is to filter and show only songs.

However, I think it would be pretty convenient to be able to reorder sections in search and make it persistent.

**Comment by adisidev** [comment]
Thanks for your reply! I actually mentioned this already in my initial issue, you can use Command + P to search for songs only. However, this is not persistent either. If we could make this persistent (i.e. not having to press Command + P and select songs every time), that would already be plenty!

**Comment by belyakov-am** [comment]
Sorry, I missed your point a little. And I thought that this filter is persistent, but double checked now and in fact it isn't persistent, unfortunately.

In that case it would be very nice to have it persistent at least.

**Comment by belyakov-am** [comment]
I have never contributed to raycast extensions yet, but it seems that leveraging [`LocalStorage` API](https://developers.raycast.com/api-reference/storage) implementing persistent filtering should be pretty straightforward.

If the author/maintainers find this change suitable, I'm willing to contribute and implement it.

**Comment by adisidev** [comment]
Just wanted to mention, this issue has actually been fixed! Now, in the settings I can set it to default to songs first before Artists! Thank you!
