### ISSUE TITLE
[Checksum] get hash from selected file in finder

### ISSUE THREAD

**Issue by ViGeng** [raycast/extensions#11585]
### Extension

https://www.raycast.com/Ek217/checksum

### Description

Hi there! Thanks for the excellent work!

Currently, I need to specify the file path or paste the text into the interactive windows when we need to get a hash code from the file or text.

Hopefully, we can get the hash code from the selected file/text in finder/other apps directly.

### Who will benefit from this feature?

All users of this extension.

**Comment by ViGeng** [comment]
I guess Apple Script can do these things easily. ChatGPT told me something like this:
```AppleScript
tell application "Finder"
	set selectedFile to the first item of (get selection)
	set filePath to POSIX path of (selectedFile as alias)
	return filePath
end tell
```

**Comment by Ek2100** [comment]
This would be easy enough to do. I can try to add it.
