### ISSUE TITLE
[Ollama AI] text selected not found

### ISSUE THREAD

**Issue by D0gZys** [raycast/extensions#11581]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

I try to use ollama with raycast and make custom commands but when I select a text and execute the command, there is an message : text selected not found

### Steps To Reproduce

.

**Comment by MassimilianoPasquini97** [comment]
Hi @D0gZys. have you give access to clipboard anche select text to raycast? #11568. Do you encounter this problem only on custom commands or on predefined commands as well?

**Comment by clementvp** [comment]
I have the same issue.
Not working on predefined commands like translation.
I'm selecting text like I do normaly then i launch raycast and the predefined command: No selected Found text.
It works only if 'im in the Raycast Floating Note but anywhere else like a browser or a text editor :/
Clipboard option work.

**Comment by MassimilianoPasquini97** [comment]
Ensure you have given raycast "Accessibility" access, look at #11568.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue
