### ISSUE TITLE
[Microsoft Teams Meeting] Notification not correct

### ISSUE THREAD

**Issue by oberprah** [raycast/extensions#11599]
### Extension

https://www.raycast.com/sven/microsoft-teams-calling

### Description

When triggering `toggle microphone` or `toggle camera` the shown notification is the opposite of what the action was.

E.g. when I'm in the muted state and `toggle microphone` then `Muted` is displayed as a notification, however, I would expect `Unmuted`.

### Steps To Reproduce

1. Be _unmuted_ in a call
2. Trigger `toggle microphone`
3. `Unmuted` will be displayed, even when `Mute` should be displayed

The same is true for `toggle camera`.

**Comment by svenwiegand** [comment]
@raycastbot close this issue

**Comment by svenwiegand** [comment]
Fixed
