### ISSUE TITLE
[Keyboard Brightness] Add "Increase brightness" and "Decrease brightness" actions

### ISSUE THREAD

**Issue by karellm** [raycast/extensions#11592]
### Extension

https://www.raycast.com/huzef44/keyboard-brightness

### Description

I would like to assign a keyboard shortcut to increase or decrease the keyboard brightness since they were removed. 

I'm new to Raycast but my understanding is that we would need an action for each action. That would be a welcome addition versus the "Adjust brightness" which cannot be linked to keyboard shortcut directly.

### Who will benefit from this feature?

Any user of a keyboard that doesn't have the keys for keyboard brightness.

### Anything else?

Thank you for your work!

**Comment by belyakov-am** [comment]
Absolutely agree on this one, having 2 separate actions with their own shortcuts would be very convenient.

I'm willing to contribute and implement this one.

**Comment by neo773** [comment]
> Absolutely agree on this one, having 2 separate actions with their own shortcuts would be very convenient.
> 
> I'm willing to contribute and implement this one.

Happy to accept a PR

**Comment by belyakov-am** [comment]
Amazing! I'll have a look close to the weekend

**Comment by karellm** [comment]
Thank you!
