### ISSUE TITLE
GitHub: Can't see organisation repositories

### ISSUE THREAD

**Issue by DanSega1** [raycast/extensions#11607]
### Extension

https://www.raycast.com/raycast/github

### Description

I can see only my personal account repositories without my organization repositories

### Steps To Reproduce

install the extension
connect to my account
check repositories

### Current Behaviour

see only my account repositories

### Expected Behaviour

see and use all the repositories my account have access to like organization repositories

**Comment by antonengelhardt** [comment]
You can create a PAT in your [GitHub Settings](https://github.com/settings/tokens) with the following scopes:

![Screenshot-Arc-006466@2x](https://github.com/raycast/extensions/assets/106314688/e50de8ea-f4db-4317-9e23-457545a589ea)

Then in your extension settings, copy the code into the "Github Token" field.

**Comment by thomaslombart** [comment]
Is your organisation authorised in the GitHub settings?

![CleanShot 2024-04-04 at 10 23 52@2x](https://github.com/raycast/extensions/assets/16003285/c3adafef-27dc-43a0-b79b-e8e734bd5744)
