### ISSUE TITLE
[Notion] Search inside the page

### ISSUE THREAD

**Issue by itsjimmz** [raycast/extensions#11603]
### Extension

https://www.raycast.com/notion/notion

### Description

The searching feature is so useless if I want to search for something **inside** the page and don't get results.
I am not supposed to remember what I am searching for inside which page and search for the page name!

### Who will benefit from this feature?

next level

### Anything else?

thank you so much

**Comment by thomaslombart** [comment]
This is a limitation of Notion's API. There is nothing special we can do without having a significant impact on performance. I recommend asking Notion directly about this.
