### ISSUE TITLE
[Apple Reminders] No way to add back the reminder permission after removing it

### ISSUE THREAD

**Issue by realhackcraft** [raycast/extensions#11601]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

I needed to remove the reminder permission from an app, so I used `tccutils reset Reminders`, and now raycast won't ask me aboiut the reminder permission again and I can't add it back :(

### Steps To Reproduce

1. use Apple Reminders and accept reminder permission
2. run `tccutils reset Reminders`
3. Can't add reminder permission back again :(

### Current Behaviour

**Can't** add reminder permission back again :(

### Expected Behaviour

**Can** add reminder permission back again :)

**Comment by thomaslombart** [comment]
Don't you have a disabled toggle over here?

![CleanShot 2024-04-04 at 10 17 40@2x](https://github.com/raycast/extensions/assets/16003285/64fc5986-09a0-49e1-b64e-3d71ee3557d7)

**Comment by realhackcraft** [comment]
> Don't you have a disabled toggle over here?
> 
> 
> 
> ![CleanShot 2024-04-04 at 10 17 40@2x](https://github.com/raycast/extensions/assets/16003285/64fc5986-09a0-49e1-b64e-3d71ee3557d7)
> 
> 

I do not because of the command I ran. I think I found a temporary fix; only one of the buttons in the extension setting would ask for that permission, and it's not every time.

**Comment by realhackcraft** [comment]
I think an easier fix would be to have an ask permission toggle/button in raycast's ui itself, and not in the extension.

**Comment by thomaslombart** [comment]
> only one of the buttons in the extension setting would ask for that permission, and it's not every time.

Which one?

**Comment by realhackcraft** [comment]
Sorry for the late reply. The button that worked was the activate button in menu bar reminders.

**Comment by realhackcraft** [comment]
Although now the permission is gone again and doesn't work anymore

**Comment by realhackcraft** [comment]
OK I actually found the way to to add it back correctly.

https://github.com/DocSystem/tccutil/

using that tool, i run `sudo python3 ~/tccutil.py --reminders -e` and drag the raycast app back. This worked. Maybe you can add the repo url to the (that place on the left)
<img width="1112" alt="Screenshot 2024-04-18 at 11 36 56" src="https://github.com/raycast/extensions/assets/65378120/67ff50dd-c649-4e2c-af69-fc98bc669230">
