### ISSUE TITLE
[Apple Reminders] View completed reminders

### ISSUE THREAD

**Issue by jakeleventhal** [raycast/extensions#11610]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

There should be a setting to view completed reminders

**Comment by thomaslombart** [comment]
You should have a `Display Completed Reminders` action like so:

![CleanShot 2024-04-04 at 10 24 38@2x](https://github.com/raycast/extensions/assets/16003285/53fcbc3e-2ef1-469d-a8b8-b4318e900e84)
