### ISSUE TITLE
[iMessage 2FA] Codes with hypen not parsed correctly

### ISSUE THREAD

**Issue by eluce2** [raycast/extensions#11618]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

I often get a 2-factor code in the format of 123-456 but the extension only suggests "123" as my code instead of "123456" or "123-456"

### Who will benefit from this feature?

Everyone

**Comment by hitolaus** [comment]
That seems like a bug, since there is code for handling those codes. I think it is just an issue with matching order.

**Comment by eluce2** [comment]
Ah, yes I see. For better context, here is the a full example text:

```
Your Raise verification code is 299-074.
Raise will never contact you for this code. If you did not request this code, please contact Raise Member Services.
```

**Comment by hitolaus** [comment]
I have tested your example with my change and it works as expected - returning 299074. Now we just have to wait until the pull request has been reviewed :-)
