### ISSUE TITLE
[One Time Password] Quick insert

### ISSUE THREAD

**Issue by SoulEvans07** [raycast/extensions#11627]
### Extension

https://www.raycast.com/lachero/one-time-password

### Description

Add a shortcut (cmd+enter) which automatically inserts the value in the last focused input instead of adding it to the clipboard.

### Who will benefit from this feature?

* quicker and easier usage
* everybody who don't want to change their clipboard
* clipboard readers can't access it anymore
* there is no more accidentally pasted keys

**Comment by lacherogwu** [comment]
Can you elaborate? I'm not sure I got it

**Comment by SoulEvans07** [comment]
Sure. So the current behavior is something like this:
1. press cmd + space (Open Raycast)
2. press o + enter (my alias for the extension)
3. select the OTP you want to insert
7. press enter to copy
8. select the input where the OTP is needed
9. press ctr+v to insert

And the feature would work something like this:
**1. open a login form and put your cursor in the input where the OTP is needed**
2. press cmd + space (Open Raycast)
3. press o + enter (my alias for the extension)
4. select the OTP you want to insert
**5. press a shortcut (my suggestion is cmd+enter but that is used now for other stuff so shift+enter is probably better) to insert**
**6. the OTP is inserted into the previously focused input**

The idea came from the Authy OTP extension but their desktop app is discontinued and it had some network request when you open it in raycast which is now blocked by my company so I can't use it anymore.

I'm guessing that the way they implemented it is to simulate keyboard presses to avoid touching the clipboard.

The speed gain while marginal still felt easier and your clipboard is safe in 2 sense. Your OTP was never there so attackers can't access it that way and your workflow is not interrupted when let's say you had something on your clipboard but the page you wanted to insert it showed a login prompt.

**Comment by lacherogwu** [comment]
Got it, will take a look into it

**Comment by SoulEvans07** [comment]
I realised that raycast uses React so I can just implement these so I made a PR about it #13003
