### ISSUE TITLE
[One Time Password] Reorder menu items

### ISSUE THREAD

**Issue by SoulEvans07** [raycast/extensions#11628]
### Extension

https://www.raycast.com/lachero/one-time-password

### Description

Please change the order of items so that the "+ Create new" goes to the bottom instead of the top. 
Users use the OTPs way more than they are adding new ones so it's better to have those options at the top.
![image](https://github.com/raycast/extensions/assets/4013509/82af049f-68f8-4e50-b0b8-ff2515dc5fd1)

And if possible add a custom order or reorder by usage option in the settings. 
The ultimate goal would be to be able open Raycast, press the command alias, Enter, Enter (or CMD+Enter, #11627) and the last used OTP is already in your clipboard (or in the desired input)

### Who will benefit from this feature?

All users use the OTPs more than they are adding new ones so everybody should benefit from this. 
And if the custom order or reorder feature is done as well then you'll benefit from a significantly quicker and easier usage of the extension

**Comment by lacherogwu** [comment]
Thanks for your suggestion, I will take a look into it.

**Comment by SoulEvans07** [comment]
I realised that raycast uses React so I can just implement these so I made a PR about it #13003
