### ISSUE TITLE
GitHub - My Issues Menu Bar

### ISSUE THREAD

**Issue by vilavren** [raycast/extensions#11626]
### Extension

https://www.raycast.com/raycast/github/commands

### Description

Good afternoon, previously in the "My issues Menu Bar" only issues in which I was assigned were displayed, now all are displayed. It would be nice if I had a choice of what to display.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? There's a similar logic in the `My Pull Request Menu Bar` command that we can port to that.

**Comment by vilavren** [comment]
If I have time I would be happy to work on this. I'll try to find time, if I start work I'll let you know about it.

**Comment by ramsaysewell** [comment]
I've had a look and done some work on this locally. Could I please be assigned this issue?

**Comment by vilavren** [comment]
it would be great

**Comment by jfkisafk** [comment]
@raycastbot assign me
