### ISSUE TITLE
[Apple Notes] The search doesn't work

### ISSUE THREAD

**Issue by badta5te** [raycast/extensions#11633]
### Extension

https://raycast.com/raycast/apple-notes

#### Error:
```
Error: EPERM: operation not permitted, copyfile '/Users/badta5te/Library/Group Containers/group.com.apple.notes/NoteStore.sqlite' -> '/var/folders/l5/nprgsjgd3s73gzjbv59fdry40000gn/T/useSQL/3f03c856eb1512d05df0960eb06c942acd82fb5b/db.db'
```

### Steps To Reproduce

I'm trying to search notes, but I get the error:
![CleanShot 2024-04-04 at 16 11 19](https://github.com/raycast/extensions/assets/40657512/b54f78d7-58cb-4e91-bb94-710829033408)
I've checked the permissions according to https://github.com/raycast/extensions/issues/11278#issuecomment-2015294842, toggled it off and on, but it doesn't help.

### Current Behaviour

It doesn't search

### Expected Behaviour

It searches

**Comment by thomaslombart** [comment]
Does Raycast have full disk access in the settings? We can't get your notes otherwise because they're stored in a database in a library folder.

**Comment by badta5te** [comment]
> Does Raycast have full disk access in the settings? We can't get your notes otherwise because they're stored in a database in a library folder.

Got it. That's the setting I missed. Thank you.
