### ISSUE TITLE
[Pomodoro] ...

### ISSUE THREAD

**Issue by rmeireles04** [raycast/extensions#11634]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

User setting a default time

### Who will benefit from this feature?

All users

### Anything else?

All good very cool extension

**Comment by MartinGonzalez** [comment]
Hi @rmeireles04!

What do you mean with User setting a default time?
You can configure the time in the extension settings

<img width="311" alt="image" src="https://github.com/raycast/extensions/assets/4130008/0b406644-532e-42bf-8147-c9b88e694503">
