### ISSUE TITLE
[Bitwarden Vault] TOTP keys for my accounts

### ISSUE THREAD

**Issue by RihardsVeters** [raycast/extensions#11631]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Would it be possible to add new command for TOTP keys?
So it would display all my keys just like in mobile app.

### Who will benefit from this feature?

All Bitwarden premium users who use Bitwarden TOTP keys

**Comment by RihardsVeters** [comment]
Any comments on this request?

**Comment by jomifepe** [comment]
Thank you for the suggestion. Unfortunately, listing TOTP codes does not appear to be a feature available in the Bitwarden CLI. You can only retrieve a code for a single item, so implementing this is not possible.

**Comment by jomifepe** [comment]
@raycastbot close this issue
