### ISSUE TITLE
[Fork Repositories] Opening a specific repo only launches the app

### ISSUE THREAD

**Issue by pindab0ter** [raycast/extensions#11649]
### Extension

https://www.raycast.com/sxn/fork-repositories

### Description

If I open a specific repo from the command, it only opens the Fork app instead of opening the app with that specific repo opened.

### Steps To Reproduce

1. Open Fork with repo A
2. Use Search Repositories in Raycast
3. Navigate to repo B
4. Press ⏎ to Open in Fork
5. Fork opens with repo A, not B 

### Current Behaviour

It only launches the app with the most recent repository opened.

**Comment by sxn** [comment]
oh, thanks for reporting this. I can reproduce it if:

1. I open Fork in a particular repo
2. I close Fork
3. I use `Search Repositories`, select a different repo than on step 1
4. Choose `Open in Fork`

It works properly if Fork is running, but if it's not running when using `Open in Fork`, it seems to…forget the argument that it receives. I'll look at what's going on.

**Comment by sxn** [comment]
Not sure tbh. Opening a repository using `fork-cli` works as expected, regardless of whether Fork was open beforehand or not – so it may be a problem with the extension, or with how Raycast's `open` function works. Nevertheless, I opened a [PR](https://github.com/raycast/extensions/pull/11659) that works around the issue. 🤷

**Comment by pindab0ter** [comment]
Awesome! Thank you!
