### ISSUE TITLE
[Downloads Manager] Unable to execute Manage Downloads

### ISSUE THREAD

**Issue by juanmoliner** [raycast/extensions#11648]
### Extension

https://www.raycast.com/thomas/downloads-manager

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

1. Run Manage Downloads
2.<img width="746" alt="image" src="https://github.com/raycast/extensions/assets/23298251/2be63306-6a10-4e06-8d8d-3a96cad6d04d">

**Comment by DanielShuster** [comment]
Hey, I have the same problem. Is there a solution?
