### ISSUE TITLE
[Fantastical] `Something went wrong` when adding event

### ISSUE THREAD

**Issue by rmoff** [raycast/extensions#11640]
### Extension

https://www.raycast.com/devahschaefers/fantastical

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
        tell application "Fantastical" 
            
 parse sentence "Sunday 11-15 "Fred in London with Bob"" 

        end tell 
78:82: syntax error: Expected end of line, etc. but found identifier. (-2741)

        tell application "Fantastical" 
            
 parse sentence "Sunday 11-15 "Fred in London with Bob"" 

```

### Steps To Reproduce

on MacOS Add event (or add event quickly - same error)
Enter value `Sunday 11-15 "Fred in London with Bob"`
Throws an error. If you select Reload, fantastical opens with an `undefined` event for today

![CleanShot 2024-04-04 at 17 25 07](https://github.com/raycast/extensions/assets/3671582/87b65739-f5d0-47b7-9b6f-ade4ee270794)

### Current Behaviour

It doesn't work

### Expected Behaviour

It should work

**Comment by xilopaint** [comment]
@raycastbot assign me
