### ISSUE TITLE
[Apple Notes] allow to create a note template

### ISSUE THREAD

**Issue by lucasmpramos** [raycast/extensions#11656]
### Extension

https://www.raycast.com/raycast/apple-notes

### Description

ability to allow to set up a template for title and tag (or header and footer) for the New Note command

### Who will benefit from this feature?

everyone who likes to create notes in a more organized way

### Anything else?

thats it, love you guys

**Comment by thomaslombart** [comment]
Thanks for the feature request. We'd probably need to create a new command for that as `New Note` doesn't have any form views for now. Do you want to look into it?

**Comment by lucasmpramos** [comment]
Sure!
