### ISSUE TITLE
[Proxmox] [Not a bug] Documentation Enhancement

### ISSUE THREAD

**Issue by kmahyyg** [raycast/extensions#11652]
### Extension

https://www.raycast.com/CzBiX/proxmox

### Description

Already set corresponding CA in PVE and also imported CA into system keychain and set to "trusted by all", however, it's still not working. Error message said it's due to certificate chain issue.

Raycast Version: 1.69.0
Mac OS Version: 13.6

After troubleshooting, I found the problem is in Raycast settings. So I'd like to ask if it's convenient for you to add a statement about certificate chain issue.

For Example:
> When encountering HTTPS certificate issue during connection to Proxmox Node, If you choose to import the custom CA into your system keychain, you MUST select "Keychain" as external source of certificates instead of "Default". Check screenshot below.
> ![20240405-185809-Raycast-008657@2x](https://github.com/raycast/extensions/assets/16604643/178c0b0c-e7ec-40c1-a6a4-68c2ad2f6bea)

### Steps To Reproduce

Select "Default" as external source of certificates.

### Current Behaviour

Failed to connect to Proxmox server.

### Expected Behaviour

Working as usual.

**Comment by kmahyyg** [comment]
@CzBiX

**Comment by CzBiX** [comment]
Updated in #11661. 

@raycastbot close this issue.
