### ISSUE TITLE
[Pomodoro] Can not hide Pomodoro from Menu Bar

### ISSUE THREAD

**Issue by dboschm** [raycast/extensions#11672]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

The Command "Show Pomodoro in Menu Bar" does not toggle Pomodoro timer as expected.

### Steps To Reproduce

1. run command Show Pomodoro in Menu Bar
2. Pomodoro is now shown in menu bar
3. run command Show Pomodoro in Menu Bar a second time
4. Pomodoro is still shown in menu bar -> should be removed from menu bar again

### Current Behaviour

Show Pomodoro in Menu Bar can not be removed from the menu bar once it has been added.

### Expected Behaviour

Show Pomodoro in Menu Bar should work as a toggle making the Pomodoro timer visible/invisible.

**Comment by laugri** [comment]
> option + shift + command + D = 🚀

@dboschm hey, what do you mean by that ? Also trying to remove from menu bar but can't find how !

**Comment by dboschm** [comment]
Hi @laugri 

in the command + K menu there is an option to deactivate the menu bar Item. 
It's quite hidden but there is also the shortcut which also works without opening the command + K menu. 
<img width="781" alt="image" src="https://github.com/user-attachments/assets/607d970a-7252-4d29-9038-ed65c54026b5">

**Comment by laugri** [comment]
Thanks ! I hadn't scrolled so far down in the options and for some reason the shortcut wasn't working.
