### ISSUE TITLE
[Mail] "no archive mailbox found" error for all accounts when trying to archive emails

### ISSUE THREAD

**Issue by chadlavi** [raycast/extensions#11688]
### Extension

https://www.raycast.com/yug2005/mail

### Description

Whenever I try to archive an email from the Mail extension, I get a "no archive mailbox found" errror. I took at look at the code and it does seem like the lowercase version of the default archive mailbox that is being used for all of my gmail accounts in the Mail app is in the archive mailbox array, but for some reason it still isn't working.

### Steps To Reproduce

1. Use the Mail extension to view an email
2. try to "move to archive mailbox"
3. get "no archive mailbox found" error message

**Comment by Luk4h** [comment]
Which mail account are you using when trying to archive the mail?

**Comment by chadlavi** [comment]
4 different gmail accounts over IMAP. Same behavior is seen in all of them.

**Comment by Luk4h** [comment]
"Archive" should be a wildcard for the archive using Appscript.
Is you archive mailbox named like mine?
<img width="185" alt="image" src="https://github.com/raycast/extensions/assets/78048969/b7d43055-720d-4a1d-951e-82c1146b27ba">
