### ISSUE TITLE
[Single Focus] Closes Raycast as well!

### ISSUE THREAD

**Issue by Joshua-Wilcox** [raycast/extensions#11683]
### Extension

https://www.raycast.com/Mmehdi06/single-focus

### Description

Treating this as a Bug as I'm pretty sure its unintentional.
Running the "Quit Non-Focused" Command also quits Raycast which does not make much sense.

### Steps To Reproduce

Run Command.
Notice Raycast cannot be ran.

### Current Behaviour

Closes Raycast

### Expected Behaviour

Raycast Stays Open (Or at least have a configuration option to leave Raycast open)

**Comment by Mmehdi06** [comment]
Thank you for your feedback, it is true that this issue exist since the last version of raycast which implements real windows instead of floating ones. I have updated the app and submitted a pull request. I am waiting on the core team to validate this and it will be updated.
