### ISSUE TITLE
[Apple Notes] search in notes function does not work

### ISSUE THREAD

**Issue by jerry88599** [raycast/extensions#11694]
### Extension

https://raycast.com/raycast/apple-notes

#### Error:
```
Error: Error: no such table: zicinvitation

    at /Users/jerry88599/.config/raycast/extensions/8c7187e0-f64c-4dba-ba77-b1cb543256d6/index.js:11:3785
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

I install the latest Raycast and enabled the extension for apple notes

### Current Behaviour

I open the search notes and try to type something but it appears the error message

### Expected Behaviour

it can screen and pop up the key work which input to search in my notes

**Comment by thomaslombart** [comment]
This should have been fixed. Could you make sure the extension is updated by running `Check for Extension Updates`?

**Comment by thomaslombart** [comment]
I'm closing this issue to maintain a clean backlog. Feel free to comment it if you still have the problem.
