### ISSUE TITLE
[Heroicons] ...

### ISSUE THREAD

**Issue by finnbuster** [raycast/extensions#11709]
### Extension

https://www.raycast.com/johndoe123789/heroicons

### Description

When I open the heroicons extension in raycast, it closes immediately and reports that an error has occurred and to try again later. I've tried for a week and no change

### Steps To Reproduce

I've tried this on three machines and each fails.

**Comment by richdynamix** [comment]
This has also been happening for me for the past week. It happened not too long ago and wasn't working for weeks. It is probably my most used app.

**Comment by j3lte** [comment]
@raycastbot close this issue
