### ISSUE TITLE
[Harvest] Tasks do not appear on first load

### ISSUE THREAD

**Issue by tomgenoni** [raycast/extensions#11706]
### Extension

https://www.raycast.com/eluce2/harvest

### Description

When I first open the extension there are no Tasks listed. When I switch to a different client project and then back to the original one, the Tasks do appear. Tried uninstall/reinstall to no avail and resetting my account on the Harvest side.

This started happening maybe a month ago. Had worked fine until then.

![Screenshot 2024-04-08 at 1 23 09 PM](https://github.com/raycast/extensions/assets/1171072/f145b5d6-c581-4cb1-8b2e-9b13b1b9abd5)

### Steps To Reproduce

I'm not sure how to reproduce it.

### Current Behaviour

Client Tasks do not load when the extension first starts.

### Expected Behaviour

Tasks should load.

**Comment by eluce2** [comment]
Hi @tomgenoni! Thanks for reporting this. I've also noticed this behavior but haven't been sure about its cause. I think I found a fix to improve the caching of those lists which I believe should help

**Comment by tomgenoni** [comment]
Thanks for looking into it. I tried revoking/adding a new access token and archiving a project but am still seeing the issue.

**Comment by tomgenoni** [comment]
#11983 sounds like same issue
