### ISSUE TITLE
[Installed Extensions] Show the last usage date

### ISSUE THREAD

**Issue by danulqua** [raycast/extensions#11714]
### Extension

https://www.raycast.com/pernielsentikaer/installed-extensions

### Description

Usually, users may want to know which extensions they don't use in order to delete them and free up resources. It would be awesome view when the extension was last used.

It can be an accessory with a default color, and with red color if the extension was last used more than 30 days ago.

### Who will benefit from this feature?

Everyone.

**Comment by pernielsentikaer** [comment]
We currently don't have a way to track last usage of an extension, the only thing we might be able to get with the current data is when it was installed
