### ISSUE TITLE
Authy Extension - sort list by recent usage

### ISSUE THREAD

**Issue by LiranBri** [raycast/extensions#1171]
# Extension – Authy (https://github.com/raycast/extensions/tree/main/extensions/authy*)

Author: @guga4ka @lukekarrys @gdsmith @pernielsentikaer 

**Describe the feature and the current behavior/state.**
It would be amazing to have the list sorted by recent usage.
currently users need to manually press multiple keyboard buttons, while usually there are really 1-3 active 2FA people use on their day-to-day. it would eliminate all those and hence improve the usability significantly 

**Who will benefit from this feature?**
all users

**Any Other info.**

**Comment by guga4ka** [comment]
Thx for your feedback. 
As I know there isn't any built-in API to rank items based on usage. Will think about how I can implement it.

**Comment by LiranBri** [comment]
Can't the extension maintain last usage timestamp for each item in its own
memory and sort accordingly?

**Comment by guga4ka** [comment]
Not sure that recently used is the right way to sort the list. What about, let's say, "Favourite" mark, once u have added an item to favourite it will pop to the top. It will save the order of the list during each render and you can rely on hotkeys `cmd+1/0`

**Comment by LiranBri** [comment]
Favourites is also great. I just figured its more complex to implement.
how do you modify the order ?

regarding the "right way"- probably there are multiple right ways. sort by
recent usage, by alphabetical order, or with custom order. could the order
be configured by the user in the extension configuration?

**Comment by guga4ka** [comment]
> I just figured its more complex to implement. how do you modify the order ?
In my mind, it's something like a stack. Each next record will be first on the list. To add a record to favourite, add a new action or hotkey `cmd+f`. I expect that fav list won't be a long 3-5 records.

**Comment by LiranBri** [comment]
It feels to me a bit odd to not allow modification of existing order.
to be honest i think the sort by recent usage makes more sense as it serves
the same purpose, but the value is given automatically without any manual
action by the user.

having said that, anyhow both would be great improvement so just pick the
one you personally prefer :)

**Comment by guga4ka** [comment]
@pernielsentikaer @fe9lix i think we good to close it
