### ISSUE TITLE
can not publish extension

### ISSUE THREAD

**Issue by liangqingfengfeng** [raycast/extensions#11732]
### Description

I created a plug-in through Create Extension, and the plug-in is under a team. After development, 

run `npm run publish`

 it prompts that `npx: the command cannot be found: api`
<img width="873" alt="image" src="https://github.com/raycast/extensions/assets/52652101/a463bce2-a5ea-44b1-9765-35c5e8700a18">

### Steps To Reproduce

1. run `npm run publish`
2. then get the error

**Comment by mathieudutour** [comment]
what version of node/npm do you use?

**Comment by liangqingfengfeng** [comment]
> what version of node/npm do you use?你使用什么版本的node/npm？

node v20.12.1 (npm v10.5.0)

**Comment by mathieudutour** [comment]
Can you try without the `funy-translate` stuff?
