### ISSUE TITLE
[Notion] Integration Auth Not Working

### ISSUE THREAD

**Issue by shivangtripathii** [raycast/extensions#11730]
### Extension

https://www.raycast.com/notion/notion

#### Error:
```
FetchError: request to https://notion.oauth.raycast.com/token failed, reason: self-signed certificate in certificate chain

    at withAccessToken(Z3)
Or:index.js:11:2490
    at ray-navigation-stack
Ro:index.js:11:2088
```

### Steps To Reproduce

1. Install the extension
2. Authorize using the link 
<img width="750" alt="Screenshot 2024-04-10 at 10 12 36 AM" src="https://github.com/raycast/extensions/assets/53747240/4d231bc7-c44c-415a-bf41-de4133bb6dfa">

3. Grant accesses on notion.so page
4. Upon redirect, it shows error 
<img width="757" alt="Screenshot 2024-04-10 at 10 13 23 AM" src="https://github.com/raycast/extensions/assets/53747240/e6c0ccb1-d3c0-4d7f-8253-e300b45aefa6">

### Current Behaviour

Auth fails.

### Expected Behaviour

Auth should succeed.

**Comment by thomaslombart** [comment]
Are you using a proxy, a VPN, a firewall or anything like it?
