### ISSUE TITLE
[Spotify Player] Radio actions now trigger completely random song

### ISSUE THREAD

**Issue by mikestopcontinues** [raycast/extensions#11731]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

When you request `start radio` for either a "search" result or "now playing," instead a _single, random song_ plays. The song always seems like it could be a later member of the particular radio playlist. However, it's only one song, and playback ends immediately after.

### Steps To Reproduce

1. Search for a song, artist, or album
2. "Start radio"
3. Error

OR

1. Lookup "now playing"
2. "Start radio"
3. Error

**Comment by mikestopcontinues** [comment]
> So, under the hood, it's not really playing the artist's radio. What's actually happening is that we're fetching some recommendations similar to an artist or a song and then playing these recommendations. 

@thomaslombart But it's only playing a single song. That's got to be an error, right?

Does this strategy also explain why trying to play the generative "daylist" often will play the previous iteration of the playlist?

**Comment by thomaslombart** [comment]
> But it's only playing a single song. That's got to be an error, right?

It's playing different artists for me, the playback doesn't end 🤔

> Does this strategy also explain why trying to play the generative "daylist" often will play the previous iteration of the playlist?

Could you share a recording for this one? It'll make it easier to see what you mean.

**Comment by mikestopcontinues** [comment]
@thomaslombart On the radio point, I just tried to play Bonobo radio, and [this is what loaded](https://github.com/raycast/extensions/assets/150434/1e7a7020-8362-425c-885e-8eb2c04cd801).

And here's a video of the [daylist bug](https://drive.google.com/file/d/1boErhS3lUSlqnnAQ2fqycFOJ5jwTF6bd/view?usp=sharing).

**Comment by thomaslombart** [comment]
Here's what the [Spotify API](https://developer.spotify.com/documentation/web-api/reference/get-recommendations) says about that:

![CleanShot 2024-05-29 at 15 07 35@2x](https://github.com/raycast/extensions/assets/16003285/51a6570f-0c8e-4df0-bb6e-c3ccbc6990b5)

It doesn't seem Bonobo is an obscure or very new artist, but it may explain why you're getting only one result. Is it consistent across all songs/artists?

For the second bug, it seems you have the shuffle option on, which may explain why it's not playing the very first song. The song should, however, be part of the playlist you just played. Is it the case?

**Comment by mikestopcontinues** [comment]
Hey, the first issue is the same with every artist. Madonna gives me one song as well.

The second issue has to do with dynamic playlists. It plays the previous version of the playlist, rather than the current version. I think you can see in the screen capture that it queues a completely different list of songs.

**Comment by mikestopcontinues** [comment]
Still an issue.
