### ISSUE TITLE
[Linak Desk Controller] Server

### ISSUE THREAD

**Issue by Hydro8** [raycast/extensions#11733]
### Extension

https://www.raycast.com/samuelkraft/linak-desk-controller

### Description

Hi
Great work for your extension.
I would like to know if it's possible to use your extension as a server to speed up the command ?

### Steps To Reproduce

If not, is it possible to specify that we use a server and use the right commands ?
Thankss

**Comment by samuelkraft** [comment]
Hey @Hydro8, if you want to run the server, it would be best for you to start it separately outside of Raycast. Then, the extension could have an option to forward commands to the server. Would that help?

Cheers,
Samuel

**Comment by Hydro8** [comment]
Yes it would be helpful !
