### ISSUE TITLE
[Slack Status] ...

### ISSUE THREAD

**Issue by vizFlux** [raycast/extensions#1173]
# Extension – [Slack Status](https://github.com/raycast/extensions/tree/56eada530324f6dc839f976d92ecc77d7b6e40a1/extensions/slack-status/)
Author: @PitNikola

## Description
Configuration not successful by following the instruction provided.
<img width="739" alt="CleanShot 2022-03-23 at 09 43 46@2x" src="https://user-images.githubusercontent.com/13939164/159605252-65a406e5-a07f-4046-b0af-ebb88c7fe533.png">

## Steps To Reproduce

1. Follow instructions from https://github.com/raycast/extensions/tree/56eada530324f6dc839f976d92ecc77d7b6e40a1/extensions/slack-status/
2. Select "Set Status" from the search result
3. Current status displays as the screenshot

## The current behavior
1. Configuration not successful by following the instruction provided.
2. Not able to set status

## The expected behavior
1. Should be able to set status without error

### Raycast version
Version: 1.30.3

**Comment by PitNikola** [comment]
That's weird, this hasn't been a problem to anyone so far. Could you please confirm for me that you have these scopes set in your app?
```
"emoji:read",
"users.profile:write",
"users.profile:read"
```

You can find it in [My Slack Apps](https://api.slack.com/apps) -> <App Name> -> App Manifest

<img width="1098" alt="CleanShot 2022-03-23 at 12 07 17" src="https://user-images.githubusercontent.com/4332171/159695602-57261662-3b6b-4aa0-a49f-ba790e5f4a56.png">

(ignore other scopes on the screenshot, they are not required, I just reuse this token for other Slack integrations)

**Comment by vizFlux** [comment]
@PitNikola Yes, I have these scopes in the App Manifest:
<img width="719" alt="CleanShot 2022-03-24 at 08 10 43@2x" src="https://user-images.githubusercontent.com/13939164/159816869-874bc569-fa84-4f6f-adf0-756d5221a2f7.png">

**Comment by PitNikola** [comment]
Unfortunately I have no idea what is wrong with auth for you. The extension works for everyone else. I wonder if it has anything to do with extra security measures in your Slack channel. Could you maybe try it out with our [Slack Community](https://raycast.com/community)? I will approve the app so you can test it.
