### ISSUE TITLE
[Gif Search] Drag and drop "copy/paste"

### ISSUE THREAD

**Issue by sebastianvitterso** [raycast/extensions#11734]
### Extension

https://raycast.com/josephschmitt/gif-search

### Description

Since the drag-and-drop feature actually does something ("copy" the link), I'd like for it to be modifiable as well, just like the main action. So by dragging and dropping it e.g. in Slack, I'd love for it to actually copy the gif itself.

Current behaviour:

https://github.com/raycast/extensions/assets/37065184/3dc5513d-1842-4597-b07f-4a7329d6de97

### Who will benefit from this feature?

Users of any chat app where you want to add a gif, and possibly any other place you'd like to add a gif.

**Comment by j3lte** [comment]
Unfortunately that's impossible at the moment...
Allthough we're able to add `quicklook` (see [here](https://tsdocs.dev/docs/@raycast/api/1.71.1/interfaces/_internal_.ItemProps_2.html#quickLook)) to a `<Grid.Item />`, that wouldn't be feasible. Quicklook only supports locally downloaded files, not web urls...

If Raycast would implement some kind of drag handler to these items, we could potentially download the GIF when it starts dragging (or before) and thus implement the quicklook.
