### ISSUE TITLE
[Figma File Search] Add Multiple Figma Accounts

### ISSUE THREAD

**Issue by OpTicAyaaN** [raycast/extensions#11745]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

Allow users to add multiple Figma accounts to the extension

### Who will benefit from this feature?

People who use Figma in different accounts (school & work, multiple teams, personal, etc.)

**Comment by michaelwschultz** [comment]
@OpTicAyaaN hey, sorry for the late response. I like this idea, but I'm not sure how well it would work in practice. One thing you can do is download the extension yourself, rename it, and use it with another account giving you access to two accounts in Raycast. I know this isn't ideal but might work for your use case.

**Comment by GLaDO8** [comment]
I second this. Supporting multiple accounts is very complex, and a simpler solution would be running a local version of the extension, or maybe with Raycast supporting multiple extension variants sometime in the future :)

**Comment by erics118** [comment]
See https://github.com/raycast/extensions/issues/269
