### ISSUE TITLE
[Word Search] Fetch text from selection while using hotkey

### ISSUE THREAD

**Issue by jd-solanki** [raycast/extensions#11748]
### Extension

https://www.raycast.com/rishabswift/word-search

### Description

Hi 👋🏻 

Recently, I realized while writing I'm checking spellings and for this installed this extension to check the spelling mistake I made. I assigned hotkey that will open the "Spell a Word" command.

Now, When I write and not sure about the spelling I wrote is correct I hit hotkey I assigned but unfortunetly I've to retype the same spelling to check the result.

Hence, Can you improve it so it fetches the input from the selected text on system?

There's another benefit except spell checking someone can just select text and press the hotkey to get the spell result.

### Who will benefit from this feature?

- People who writes and wants to spell check
- People who want to get explanation via single hotkey

**Comment by jd-solanki** [comment]
@RishabSwift Are you upto it?

**Comment by bkeys818** [comment]
I can knock this out real quick if no one else is doing it.

**Comment by j3lte** [comment]
Added in last update

@raycastbot close this issue
