### ISSUE TITLE
[copy-path] Add Firefox as supported browser

### ISSUE THREAD

**Issue by alexandrelissowski** [raycast/extensions#11757]
### Extension

https://www.raycast.com/koinzhang/copy-path

### Description

Add Firefox as supported browser. 

Indeed, for the moment, only chromium based browsers are supported with this extension. 

### Who will benefit from this feature?

All users on Firefox and using Raycast

**Comment by koinzhang** [comment]
Hi @alexandrelissowski. I'm sorry, but currently Firefox doesn't support Apple Script, so it's not possible to implement this feature, if you find a better way to implement it, feel free to let me know!

**Comment by koinzhang** [comment]
Hi @alexandrelissowski. Hope it can help you. 
PR - [[Copy Path] Support Safari Web App and Firefox browser](https://github.com/raycast/extensions/pull/13061)
