### ISSUE TITLE
[iMessage 2FA] Incorrect 2FA code from USAA

### ISSUE THREAD

**Issue by GeoJunkie** [raycast/extensions#11758]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

When receiving a 2FA code from USAA, the extension gives a portion of the return phone number as the 2FA code instead of the 2FA code itself.

### Steps To Reproduce

1. Log onto USAA Bank (usaa.com)
2. Get the 2FA code text. Note the six-digit 2FA code and the phone number (800-531-8722)
3. Activate the extension
4. See the 2FA code that's indicated (800531)

### Current Behaviour

For the text message:
> USAA FRAUD PREVENTION ALERT: USAA will never contact you for this code, don't share it: 123456. Call 800-531-8722 if you gave it to anyone. Reply HELP for help.

It shows `800531` as the 2FA code instead of `123456`

![CleanShot 2024-04-11 at 10 16 27@2x](https://github.com/raycast/extensions/assets/7596032/a28fbb6f-6633-4144-823d-af9f33980996)

### Expected Behaviour

The actual 2FA code should be extracted instead of the phone number.

**Comment by ronaldheft** [comment]
This is related to the recent PR https://github.com/raycast/extensions/pull/11650. The phone number is being parsed as a code. I've seen this myself previously with other 2FA messages that include phone numbers (PNC Bank is one example).

@hitolaus I submitted a change a while back to address the parsing ordering that had the dashed parsing last to avoid situations like this. I'm wondering if there is an ordering that will allow the edge case you found to be parsed, while also avoiding this situation. If this can't be addressed by ordering, my next thought it to improve the dashed code parsing to filter out phone numbers.

@hitolaus What are your thoughts on how we can address this?

**Comment by yuercl** [comment]
I'm wondering if there is a lightweight neural network model that can run on Raycast that can extract verification codes more intelligently, rather than through regular expression rule patterns like now. Currently, large models can be extracted, but I think there are privacy issues. Is there any offline model that can achieve this kind of function?

**Comment by hitolaus** [comment]
@yuercl I agree, the current way of pattern matching will always end up being a bit of a mess in the long run :-) I have added unit tests in my latest PR (#11772), which will hopefully make it easier to refactor the matching logic at some point.
