### ISSUE TITLE
Encoding error: Output format mp3 is not available

### ISSUE THREAD

**Issue by jacqu3sk** [raycast/extensions#11754]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

I have check that the file paths to the ffmpeg and ffprobe are correct. I have also made sure to update everything. I Have no idea whats causing this issue.

### Steps To Reproduce

1. Download any video using 1080p 2. I get the error

**Comment by vimtor** [comment]
Hey @jacqu3sk, I'm sorry you're facing this issue.

Could you please share the video URL?

My guess is that the problem is with a specific video, similar to #11822.

**Comment by Joyouou** [comment]
Hi @vimtor , please check this video which is newly released. It throws an encoding error

https://www.youtube.com/watch?v=q7Qk1QDYZLw

I copied the error for you:

Error: Output format mp4 is not available

capabilities.js:589:20

---
586:           }, []);
587: 
588:         if (unavailable.length === 1) {
589:           return cb(new Error('Output format ' + unavailable[0] + ' is not available'));
590:         } else if (unavailable.length > 1) {
591:           return cb(new Error('Output formats ' + unavailable.join(', ') + ' are not available'));
592:         }
---

T:index.js:46:13445
I:index.js:46:13524
index.js:43:11429

**Comment by vimtor** [comment]
Thanks for sharing!

I've found this recent issue https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/1262 in the package the extension uses to interact with ﻿`ffmpeg`. From that issue, I'm guessing that you are using an `﻿ffmpeg` version different from ﻿`6.1`, which now gets installed automatically. Until the ﻿fluent-ffmpeg package gets updated to support that version, you will need to downgrade your local ﻿ffmpeg version to ﻿6.1. You can do this using Brew by running ﻿`brew install ffmpeg@6`.

**Comment by Joyouou** [comment]
Downgrading didn't help!

I uninstalled ffmpeg version 7 and also homebrew. Then i installed
homebrew and installed ***@***.*** The extension didn't recognize
version 6.

**Comment by vimtor** [comment]
@Joyouou could you see if any of these fix your issue?

- https://github.com/raycast/extensions/issues/11822#issuecomment-2064183311
- https://github.com/raycast/extensions/issues/11907
