### ISSUE TITLE
[Miro] Could we have a way of creating a new board without typing name and selecting the type each time?

### ISSUE THREAD

**Issue by preetmyob** [raycast/extensions#11767]
### Extension

https://www.raycast.com/felixhaeberle/miro

### Description

I really like your extension. However, when creating a board you have to go through a selection of the board type. Often I create a new miro board for some ad hoc meeting I'm having or just want to express some ideas visually. In those cases, I'd like to just open a blank board, without setting a name or description.  For other people, the blank board might not be what they start with in most cases, so perhaps the ability to save the type and use that for shortcuts would be brilliant.    

### Who will benefit from this feature?

This would be very useful in an enterprise environment where you often create boards of the same type over and over again.

**Comment by preetmyob** [comment]
Is this likely to ever be responded to?

**Comment by felixhaeberle** [comment]
Feel free to do a PR with the desired behavior and I will consider merging it!:)
