### ISSUE TITLE
[Miro] can you make it that I can find boards in my team, and not just my own owned ones please

### ISSUE THREAD

**Issue by preetmyob** [raycast/extensions#11766]
### Extension

https://www.raycast.com/felixhaeberle/miro

### Description

There isn't a way of searching for boards I don't own that I can find. 9/10 I'm opening a board used by my team that I didn't create and for this, the extension doesn't seem to help. 

### Who will benefit from this feature?

This would be brilliant in an enterprise setting where people create and share boards across teams.

**Comment by preetmyob** [comment]
Is this likely to ever be responded to?

**Comment by felixhaeberle** [comment]
Feel free to do a PR with the desired behavior and I will consider merging it!:)
