### ISSUE TITLE
[Bing Wallpaper] ...

### ISSUE THREAD

**Issue by TouhouGO** [raycast/extensions#11764]
### Extension

https://www.raycast.com/koinzhang/bing-wallpaper

### Description

Unable to set wallpaper, can only download

### Steps To Reproduce

![CleanShot 2024-04-12 at 10 29 56@2x](https://github.com/raycast/extensions/assets/93237754/b3332e48-ce8b-4242-8ab7-e66b57bb4989)

### Current Behaviour

Setting the wallpaper will automatically switch to Sonoma’s built-in dynamic wallpaper, and the downloaded wallpaper cannot be used.

**Comment by koinzhang** [comment]
Hi @TouhouGO Thanks for the feedback, fixed in PR #12452 !

@raycastbot close this issue
