### ISSUE TITLE
[GIF Search] ... Doesn't show any gif's sometimes when searching for stuff

### ISSUE THREAD

**Issue by JLee141** [raycast/extensions#11760]
### Extension

https://www.raycast.com/josephschmitt/gif-search

### Description

Hello! Having an issue where when searching for gifs the results don't populate.

EDIT *Extra Tidbits*
This may be because it's trying to find an incomplete sentence but stays in that state until it searches for word again. I have noticed a few times where I would search a complete sentence and even switching providers on search platform it would still hang onto showing no results. Noticed this recently.

### Steps To Reproduce

The way it's happening for me is I would..

1) Open gif search with Raycast
2) Search
3) Delete search and retype but it can be a few characters.
4) After around 2 characters it stops showing results sometimes.

### Current Behaviour

Shows results but then says no results after the edit, would need to delete search and reopen gif search again.

### Expected Behaviour

Should show the same gifs of topic searched.

**Comment by j3lte** [comment]
Most likely fixed after #11887 

@raycastbot close this issue
