### ISSUE TITLE
[Obsidian] Hide frontmatter properties and rendered code blocks

### ISSUE THREAD

**Issue by ChristinWhite** [raycast/extensions#11763]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

This plugin is fantastic and it's the one that's really driven me to start using Raycast instead of reaching for Alfred almost all of the time, thank you for your work!

With frontmatter properties becoming more and more important in Obsidian it's pretty easy to get notes where nothing but frontmatter is getting shown in the initial window and you have to scroll down to get to the actual note content. This issue is compounded if you use dataview or any other type of code blocks that are rendered rather than shown inline at the top of your notes.

![Obsidian](https://github.com/raycast/extensions/assets/1746405/4553017a-a91b-4aa2-92cc-629a58db9702)

If the notes can be easily parsed I'd love the following two options:

1. Hide frontmatter properties.
2. Hide rendered code blocks (as much as practical, at least `dataview, dataviewjs, 

Maybe in the future frontmatter could be extracted into the metadata section and frontmatter could be hidden by default.

Just rendering the frontmatter as YAML rather than note text would be an improvement but not negate the scrolling issue.

### Who will benefit from this feature?

Anyone who uses a lot of frontmatter-based properties (not dataview inline properties). Now that Obsidian has native support for easily creating and displaying properties this will likely be a growing use case beyond people just using things like Metadata Menu and Make.md. 

Admittedly, rendered code blocks are probably a bit more of an outlier issue.

### Anything else?

As a point of reference, here's what that note looks like in Obsidian, I only render the properties I want to see via Dataview while other properties have other functions. 
![CleanShot 2024-04-11 at 13 59 02@2x](https://github.com/raycast/extensions/assets/1746405/82a3547a-0550-49fc-9c79-18bb72d23b86)

I doubt rendering dataview outside of Obsidian would ever be practical but just getting to the note text when I use Raycast would be awesome!

**Comment by Perchycs** [comment]
Would also love this feature!

**Comment by KevinBatdorf** [comment]
Sorry for the late follow up. Does the setting to hide the frontmatter work? 

![CleanShot 2024-06-03 at 17 35 10@2x](https://github.com/raycast/extensions/assets/1478421/fed281f8-e580-46df-8136-da5c069238ca)


Can you share a typical note that I can use to test on? Maybe if I see it I can better understand the problem

**Comment by ChristinWhite** [comment]
I don't know how I missed that but it works perfectly! Sorry to raise a unnecessary issue.
