### ISSUE TITLE
[Open Graph] Add support to relative media URLs

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#11787]
### Extension

https://github.com/raycast/extensions/blob/3acb78602068f2cf2d286770ed9920ab7efca256/extensions/open-graph/README.md

### Description

In some instances, OG markup uses relative paths for their assets and in those cases, the extension craps out.

When relative paths are discovered, they should prepend the domain to the asset path.

### Steps To Reproduce

1. Launch extension and paste https://air.chat/
2. You'll see that the `og:image` value has a relative path, which means that the image preview doesn't load.
3. If you copy the value, you'll get `/images/airchat_icon.svg` which of course doesn't resolve.

![2024-04-12 (17 39 19) Arc](https://github.com/raycast/extensions/assets/22610/3196c4f1-a1da-47db-8e65-d4e034afce46)

### Current Behaviour

The extension doesn't treat relative paths correctly by prepending the domain.

### Expected Behaviour

1. Launch extension and paste https://air.chat/
2. The relative `og:image` path should be prepended with the domain.
3. Copying the value should result in `https://air.chat/images/airchat_icon.svg`

**Comment by chrismessina** [comment]
Done! 

https://github.com/raycast/extensions/blob/3acb78602068f2cf2d286770ed9920ab7efca256/extensions/open-graph/README.md

**Comment by chrismessina** [comment]
Can you help @1weiho?

**Comment by 1weiho** [comment]
Thanks @j3lte has fixed it💪🏼

**Comment by j3lte** [comment]
@raycastbot close this issue

**Comment by j3lte** [comment]
@chrismessina it seems that the bot doesn't want to close the issue (probably because it couldn't find it). Can you close the issue? This should be resolved now...

**Comment by chrismessina** [comment]
Looks like it's solved. Thanks @j3lte and @1weiho!
