### ISSUE TITLE
`getSelectedText()` doesn't select text from Raycast AI window

### ISSUE THREAD

**Issue by szymonrybczak** [raycast/extensions#11793]
### Description

Hey! I love the product and API, really good job! 

Recently I've started building extension which relies on `getSelectedText()` method - same as `Fix Spelling and Grammar` extension. And what I found is that when trying to call `getSelectedText()` inside Raycast AI separate window it doesn't select any text. 

https://github.com/raycast/extensions/assets/63900941/17e6894b-89e4-4811-942f-d087ba103fdd

### Steps To Reproduce

1. Open Raycast AI window,
2. Select text from the response,
3. Try calling `getSelectedText()` with selected text inside Raycast AI window.

### Current Behaviour

`getSelectedText()` doesn't return selected text from Raycast AI window. 

### Expected Behaviour

`getSelectedText()` return selected text from Raycast AI window.

**Comment by thomaslombart** [comment]
@szymonrybczak I can't reproduce it. Which version are you running? We may have fixed that in between?

**Comment by szymonrybczak** [comment]
hey @thomaslombart! I've checked now and it seems to work, thanks!


https://github.com/raycast/extensions/assets/63900941/db29b083-ff0c-4189-bbd8-9c0a10f834c2
