### ISSUE TITLE
[ChatGPT] Quicker access to model selection when asking a question

### ISSUE THREAD

**Issue by srbartlett** [raycast/extensions#11808]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

With "Ask Question" active, I would like the ability to choose a predefined model without using a mouse.

Currently, when I want to select a model, I need to open the Model dropdown, scroll to find the model I wish to use, select the model, return my hands to the keyword.  It is also not possible to <tab> to the dropdown to open it.  It would appear the dropdown can only be opened using the mouse.

Ideally, assigning a shortcut key to a model would be nice. Alternatively, having the ability to open the dropdown without the mouse would work.

### Who will benefit from this feature?

People who use ChatGPT with more then one model would benefit from this feature by allowing them to switch models faster.

**Comment by bxb100** [comment]
Command + P

**Comment by srbartlett** [comment]
Thanks @bxb100

**Comment by bxb100** [comment]
you are welcome 

@raycastbot close this issue
