### ISSUE TITLE
[Roam Research] Add Append API/Encrypted Graph Support

### ISSUE THREAD

**Issue by frankamedic** [raycast/extensions#11807]
### Extension

https://www.raycast.com/roamresearch/roam-research

### Description

Add support for encrypted graphs

### Who will benefit from this feature?

Everyone using encrypted graphs

**Comment by baibhavbista** [comment]
@frankamedic quick capture to encrypted graphs is in the works!
Due to the nature of encrypted graphs, we would not be able to support search or random blocks, but quick capture would work
