### ISSUE TITLE
[Linear] Hide done issues

### ISSUE THREAD

**Issue by dantnad** [raycast/extensions#11818]
### Extension

https://www.raycast.com/linear/linear

### Description

I work in a team that has several tickets, I, for example, am in 2 different teams (Support and Engineering) thing is that when I check my assigned issues I have LOTS of done issues:

![image](https://github.com/raycast/extensions/assets/39326187/5795e984-1141-4988-b3dd-43c006433b04)

And the Issues I'm currently working on do not appear (I believe because of the API limit) so I have to search them manually to update their status:

On assigned issues:
![image](https://github.com/raycast/extensions/assets/39326187/3791f47e-5327-46c1-ad8b-566781bc4594)

On current cycle:
![image](https://github.com/raycast/extensions/assets/39326187/ed5a22e6-c4a4-4093-87a9-b09549bc95e7)

### Who will benefit from this feature?

Developers and teams working on tickets with linear, maybe an option to Hide done on settings would be cool as some may want to check their done issues again but, in my case once it's done I don't really want to see them anymore.

### Anything else?

You guys rock 🩷 (Both Raycast team and extension Developer)

**Comment by jfkisafk** [comment]
@raycastbot assign me
