### ISSUE TITLE
[Apple Reminders] composed time recognition no working anymore

### ISSUE THREAD

**Issue by kevinm6** [raycast/extensions#11820]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

With the latest updates of the **Apple Reminders** some “composed time” strings (like `1 hour and 10 mins`) are not recognized as it used to be.
There are some weird strings that are recognized as in the screenshots below.
![Not working string](https://github.com/raycast/extensions/assets/72861758/05e2c4ee-e9b0-4ed9-8fd6-1982294f5a9b)
![Working string](https://github.com/raycast/extensions/assets/72861758/bd329867-5399-428a-9960-f2d46855d8cb)

### Steps To Reproduce

1. Open *Raycast* and an action from **Apple Reminders** extension (like My Reminders)
2. On a reminder item, change **Due Date** or press `cmd+d`
3. Enter one of the strings above and check the behaviour

### Expected Behaviour

It works as before

**Comment by thomaslombart** [comment]
Thanks for reporting this issue. It seems it's related to our native date picker. I'll check with the team what's up.

**Comment by thomaslombart** [comment]
This will be fixed in the next release.

**Comment by kevinm6** [comment]
I'm closing the issue since it appears to be fixed with latest update.
Thanks for the support and looking into this
