### ISSUE TITLE
Unexpected end of json input

### ISSUE THREAD

**Issue by m-j-45** [raycast/extensions#11826]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Every time I use the extension, even though it is working fine, I get the error message "Unexpected end of json input"

### Steps To Reproduce

I just use the extension as normal.

**Comment by Luk4h** [comment]
Hello @m-j-45, I am currently working on improving error handling and explanations for these errors. I will notify you as soon as possible when it is available. 🫡

**Comment by m-j-45** [comment]
OK thank you, and thanks for replying so quickly. From: Luiz Gustavo Marcondes ***@***.***>Date: Tuesday, 16 April 2024 at 12:42 PMTo: raycast/extensions ***@***.***>Cc: m-j-45 ***@***.***>, Mention ***@***.***>Subject: Re: [raycast/extensions] Unexpected end of json input (Issue #11826)Hello @m-j-45, I am currently working on improving error handling and explanations for these errors. I will notify you as soon as possible when it is available. 🫡—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Luk4h** [comment]
As for the latest update, there is now better error handling which should prevent these "Unexpected end of JSON input" errors and facilitate user reports and fixes.

@raycastbot close this issue
