### ISSUE TITLE
[Jira] not respecting refresh token when i reauth outside of raycast

### ISSUE THREAD

**Issue by sf8193** [raycast/extensions#11836]
### Extension

https://www.raycast.com/raycast/jira

### Description

I used it for two days and now none of the commands work, when i copy the error i get the below

Error: Error while refreshing tokens: 403 (Forbidden)
{"error":"unauthorized_client","error_description":"refresh_token is invalid"}

    at withAccessToken(iV)
Or:index.js:11:2490
    at ray-navigation-stack
Ro:index.js:11:2088

### Steps To Reproduce

1. Oauth into jira through okta
2. wait until that token expires

**Comment by thomaslombart** [comment]
Thanks for reporting the issue. What do you mean with "reauth outside of raycast"? 🙂

**Comment by sf8193** [comment]
@thomaslombart i use sso flow to auth into jira. It works the first time, and for as long as i have the refresh token. But when the refresh token, it doesn't let me go through the sso flow without force logging out inside of the raycast settings

**Comment by thomaslombart** [comment]
When you reauthorize, for how much time are you still logged in the extension?

**Comment by sf8193** [comment]
2-4 days i believe

**Comment by thomaslombart** [comment]
Fixed as part of https://github.com/raycast/extensions/pull/13427.
