### ISSUE TITLE
[Jira] Show target status when changing status

### ISSUE THREAD

**Issue by mikybars** [raycast/extensions#11847]
### Extension

https://www.raycast.com/raycast/jira

### Description

It'd be nice that when changing status to an issue the final status would be shown next to the _action_. This way undesired transitions would be avoided when you know beforehand the desired status but not the action.

![image](https://github.com/raycast/extensions/assets/43891734/3f28702f-17e0-4976-850e-7f6997cb3e70)
![image](https://github.com/raycast/extensions/assets/43891734/1574c02e-3199-4354-a91a-52ed4f4557ad)

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

**Comment by mikybars** [comment]
Sure. I'll send you a DM
