### ISSUE TITLE
[Toothpick] Configure input/output for bluetooth devices

### ISSUE THREAD

**Issue by NicodemPL** [raycast/extensions#11857]
### Extension

https://www.raycast.com/VladCuciureanu/Toothpick

### Description

I am not sure if this is even doable but here is my problem. I use bluetooth headphones (SONY WF-1000XM4) with my mac for eny meeting. They are great, small with perfect active nose cancelling. But their microphone is bad compared to built in my mac. So I tend to switch sound imput to microphone. Its easy doable from any meeting program. BUT.. there is another scenario that is not managable like this.
So I do also own great micrphone DJI MIC 2 - this is amazingly good and now I switched to use this instead of mac built in.
But its way more complicated as after connecting with Mac all my sound (input/output) is redirected to this microphone. Stupid thing as microphone does not have any speakers etc.
So before any meeting I have to:
- connect to SONY headphones
- connect to DJI MIC 2
- open AUDIO INPUT/OUTPUT settings in system, manualy choose for INPUT only my DJI MIC, for output SONY headphones

And it works great then. Super clear sound for me, noise cancelling and clear mic for anyone but also very, very annoying.

Any chance I could automate this???

### Who will benefit from this feature?

literally any nerd like me...

**Comment by VladCuciureanu** [comment]
Hey there! I completely get where you come from! That said, this is outside of the extension's scope. 

I suggest looking into Shortcuts though! From what I can tell, a well designed Shortcut could do your enumerated steps in one click

**Comment by VladCuciureanu** [comment]
@raycastbot close this issue

**Comment by weitzman** [comment]
I think you could combine this extension another: https://www.raycast.com/benvp/audio-device
