### ISSUE TITLE
[TickTick] Wrong dates for 'today' and 'tomorrow' keywords

### ISSUE THREAD

**Issue by Spaider** [raycast/extensions#11855]
### Extension

https://www.raycast.com/appest/ticktick

### Description

TickTick extension stopped setting correct dates for today and tomorrow keywords. See screenshots below. It was working some time ago but I'm not able to say exactly since when it's broken.

![image](https://github.com/raycast/extensions/assets/548604/a9718467-af16-4f1d-bf01-6d1e70134493)
![image](https://github.com/raycast/extensions/assets/548604/9f1e8a0b-f209-4daa-a2e1-f8af990b33ee)

### Steps To Reproduce

Invoke **Add task** command and start typing words **Today** or **Tomorrow** in **Due date** field.

### Current Behaviour

Suggested dates are one day off

### Expected Behaviour

It should set correct dates for today and tomorrow.

**Comment by viduycheung** [comment]
Currently, we don't support creating all-day tasks. The option today means at 00:00

**Comment by Spaider** [comment]
I'm confused. On my screenshot there is a clear discrepancy: on April 17 (see top right corner) if I enter **today** it shows April 16, which is effectively _yesterday_.

**Comment by viduycheung** [comment]
It seems to be the raycast issue. Please upgrade it to the latest version. If the issue persists, please contact the raycast team.
