### ISSUE TITLE
[One Time Password] QR detection failed when using Google Authenticator Migration QR code from iOS App.

### ISSUE THREAD

**Issue by OmkarK45** [raycast/extensions#11859]
### Extension

https://www.raycast.com/lachero/one-time-password

### Description

Steps followed 
- Google Authenticator iOS app
- Export the accounts > QR code > Transfer to macbook
- One Time Password extension > Actions > Select QR Code > Screengrab the QR code image > "QR detection failed error"

<img width="228" alt="image" src="https://github.com/raycast/extensions/assets/45557594/14c32387-8b6c-44fb-b78a-0917d1757eae">

### Steps To Reproduce

To replicate: be on latest version of google authenticator app
Try to add it in One Time Password Raycast extension

### Current Behaviour

QR detection fails despite choosing the correct QR as per Readme

### Expected Behaviour

Should detect the Google Authenticator Migration QR code

**Comment by muava12** [comment]
how to export to backup from this extension?
