### ISSUE TITLE
[spotify-player] add queue management commands

### ISSUE THREAD

**Issue by RowMur** [raycast/extensions#11856]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Building upon this [PR](https://github.com/raycast/extensions/pull/9862) and specifically this [comment](https://github.com/raycast/extensions/pull/9862#discussion_r1471904394), extend the features of the `Queue` command.

Additions in mind:
- Remove from queue
- Track movement
  - To top of queue
  - Up
  - Down

### Who will benefit from this feature?

All? Anyone who uses the queue command

**Comment by RowMur** [comment]
@bkeys818 you may be particularly interested in this as it's building on your feature.

I'll work on this myself, hope to have a PR out in the next couple of days once I've figured stuff out.

**Comment by RowMur** [comment]
Oh Spotify... https://community.spotify.com/t5/Spotify-for-Developers/API-Delete-Remove-songs-from-queue/td-p/4956378/page/3.

Thought this was an obvious feature to add - now I see why it wasn't...

**Comment by mattisssa** [comment]
Huh @RowMur, it seems like it hangs there from 2020-05-16 unmade 😬

**Comment by RowMur** [comment]
@mattisssa Yeah, it's a shame.

I was also going to create a bug issue in this area. Currently if you play a track from the queue you lose the rest of the queue and enter a new session effectively. Looking at the docs, the only solutions I can come up with would be extremely janky.

1. Hit `/next` endpoint until you make it to the selected track
2. Play the new track as we do now, but copy across the queue by repeatedly hitting the `/queue` endpoint
