### ISSUE TITLE
[Kill Process] Kill multiple processes at once

### ISSUE THREAD

**Issue by AntonShuvaev** [raycast/extensions#11853]
### Extension

https://www.raycast.com/rolandleth/kill-process

### Description

Currently, the "Kill Process" feature only allows killing one selected process at a time, closing the window immediately afterward. This requires repeating all steps to kill another process, which can be cumbersome. It would be beneficial to have the option to kill all searched processes at once. Alternatively, enabling the selection of multiple processes for simultaneous termination or keeping the window open after killing a process would improve usability. For example, in Alfred, pressing Enter kills the selected process, and Cmd + Enter kills all processes.

**Comment by erics118** [comment]
See https://github.com/raycast/extensions/pull/9185

**Comment by AntonShuvaev** [comment]
@erics118 Thanks for pointing that out. I missed it.
