### ISSUE TITLE
[Project Companion] Search directly project

### ISSUE THREAD

**Issue by Hydro8** [raycast/extensions#11868]
### Extension

https://www.raycast.com/maximedaraize/project-companion

### Description

Hi
Great extension, very useful !
It could be nice to be able to perform a search directly from raycast without launching the extension first.
Like "p tagada" to search for project "tagada".

With enter, we launch the default site and with cmd + enter with can launch alternative site.

What do you think ?

**Comment by maximedaraize** [comment]
> It could be cool to have a command to quickly create project.

Yes, I like those idea, will consider adding those. Thank you for your feedbacks @Hydro8

**Comment by Hydro8** [comment]
What about searching project directly on raycast ?

**Comment by maximedaraize** [comment]
> What about searching project directly on raycast ?

Sure, why not ✌🏻. I'll work on one after the other. But if you are interested i'll be happy if you want to contribute and open a pr for this.

**Comment by maximedaraize** [comment]
@raycastbot assign me
@raycastbot good first issue

**Comment by maximedaraize** [comment]
Testing new issue actions

@raycastbot Good first issue

**Comment by maximedaraize** [comment]
@raycastbot good first issue

**Comment by Hydro8** [comment]
Hi

Do you still consider adding these features ?
