### ISSUE TITLE
[Remove Background - Powered by Mac] inverts image

### ISSUE THREAD

**Issue by jsheffers** [raycast/extensions#11873]
### Extension

https://www.raycast.com/xmorse/remove-background-powered-by-mac

### Description

Tried it on my first image and it flipped the orientation upside down. It did a decent job of removing the background.

### Steps To Reproduce

Select image on desktop, run command.  Image was output was upside down.

**Comment by jsheffers** [comment]
This might be specific to the image (although it would still be good to track down).  I tried another and it works fine.

**Comment by remorses** [comment]
Can you try using the Mac built in remove background with right click and see what happens? It might be a bug in Mac OS

![Screenshot 2024-04-18 at 17 47 45](https://github.com/raycast/extensions/assets/31321188/d7a2dbc5-bcf4-4ff8-9b37-2a71c52bf3b2)

**Comment by jsheffers** [comment]
Yep, same issue.  Thanks for the follow up!
