### ISSUE TITLE
[Toothpick] Can't run deeplink of connections favourite device in background

### ISSUE THREAD

**Issue by sluzhynskyi** [raycast/extensions#11874]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

I'm trying to add shortcut to the Karabiner so it will connect to the favourite device. I added this shell command to the key binding:
`$open -g "raycast://extensions/VladCuciureanu/toothpick/connect-favorite-device-1?launchType=background"`
But error pops up
It doesn't happends with other extensions like spotify.

**NOTE:** that with command `$open -g "raycast://extensions/VladCuciureanu/toothpick/connect-favorite-device-1?launchType=userInitiated"` it runs fine and connects the device, but the Raycast pops up. 

### Steps To Reproduce

Write in the terminal
`$open -g "raycast://extensions/VladCuciureanu/toothpick/connect-favorite-device-1?launchType=background"`

### Current Behaviour

Error pops up:

<img width="436" alt="image" src="https://github.com/raycast/extensions/assets/44615981/3e554285-845a-4f62-bc74-2c755f678387">

Error log:
```
Reason: Could not load command
Domain: commands
Time: 15:15:46.086
Underlying: 
	Domain: RaycastNodeExtensions.APIError 1
	
```

### Expected Behaviour

PC connects to the favourite device in the background without showing Raycast popup

**Comment by VladCuciureanu** [comment]
Hey there! I'm sorry to hear that it's not working! At the moment I don't have the resources to work on Toothpick so it might be a while until I will be able to look into it, but I encourage you to maybe take a look yourself - all contributions are welcome! I'll gladly review your PR if you do so.

**Comment by sluzhynskyi** [comment]
Sure, there is knew [PR](https://github.com/raycast/extensions/pull/11939), you can review it. 
Btw thnx for your extension

**Comment by VladCuciureanu** [comment]
Reviewed - now we just need to wait for it to be merged. Glad you like the extension :^)

**Comment by VladCuciureanu** [comment]
@raycastbot close this issue.
