### ISSUE TITLE
[Remove Background - Powered by Mac] ...

### ISSUE THREAD

**Issue by Leizhenpeng** [raycast/extensions#11888]
### Extension

https://www.raycast.com/xmorse/remove-background-powered-by-mac

### Description

error.  Could not get the selected Finder items

<img width="850" alt="CleanShot 2024-04-19 at 20 51 10@2x" src="https://github.com/raycast/extensions/assets/50035229/16a2d76c-278b-4802-8ecc-369a097d9b49">

### Steps To Reproduce

1. select png in finder
2. active raycast
3. active extension

### Current Behaviour

error.  Could not get the selected Finder items

<img width="850" alt="CleanShot 2024-04-19 at 20 51 10@2x" src="https://github.com/raycast/extensions/assets/50035229/16a2d76c-278b-4802-8ecc-369a097d9b49">

**Comment by Leizhenpeng** [comment]
https://github.com/raycast/extensions/assets/50035229/22afb182-e33b-4fb0-9dfc-ac39ffd68a0e

**Comment by remorses** [comment]
Seems to be a problem with raycast itself, maybe not enough permissions to read the files
