### ISSUE TITLE
[Groq] Please Add Llama 3 8b

### ISSUE THREAD

**Issue by iamhenry** [raycast/extensions#11898]
### Extension

https://www.raycast.com/ilian/groq

### Description

Llama 3 8b was just released and Groq now supports it via api. Please add when you get a chance.
![image](https://github.com/raycast/extensions/assets/923439/19c9b9b0-f4fc-4c44-8b8d-d37b8abd6405)

### Who will benefit from this feature?

Devs and normal users

**Comment by maximilianzuern** [comment]
@iamhenry  I added both new Llama3 models.

**Comment by iamhenry** [comment]
@maximilianzuern awesome! i just downloaded the extention today but only have access to 3 models. see image

is there something else i need to do to enable the Llama 3 models? 
![image](https://github.com/raycast/extensions/assets/923439/9de5593e-1fdf-4bec-bc47-81ee749c2ed8)

**Comment by maximilianzuern** [comment]
Unfortunately, you have to wait until Raycast approves and merges the referenced pull request. 
Once it's merged, the extension should update automatically.

**Comment by iamhenry** [comment]
no worries! thx for the quick implementation!
