### ISSUE TITLE
[Plausible Analytics] ...

### ISSUE THREAD

**Issue by MarcelSchulz** [raycast/extensions#11890]
### Extension

https://www.raycast.com/thebrokenfinger/plausible-analytics

#### Error:
```
TypeError: Invalid URL

URL:url:775:36
Xe:index.js:37:16178
index.js:37:19422
    at new Promise (<anonymous>)
```

### Steps To Reproduce

Can’t add our website (an.jetzt) through the extension, potentially to the newish TLD .jetzt failing validation?

**Comment by medienbaecker** [comment]
I can reproduce this. Doesn't work with any TLD, not even `.com`.
