### ISSUE TITLE
[Timers] No sound when timer finishes

### ISSUE THREAD

**Issue by asgeirtj** [raycast/extensions#11897]
### Extension

https://www.raycast.com/ThatNerd/timers

### Description

Alarms don't work (give no sound)

### Steps To Reproduce

Start any timer and wait for it to finish.

**Comment by ThatNerdSquared** [comment]
Hi @asgeirtj, thanks for using Timers.

Are you getting a banner notification like the one below? Or does that not show up either?

![image](https://github.com/raycast/extensions/assets/72814106/e75dd9d7-9c70-45fe-9fad-9dd78e02cb36)

Note: may be linked to #11500, will be investigating this soon.

@raycastbot rename this issue to "[Timers] No sound when timer finishes"

**Comment by asgeirtj** [comment]
> Hi @asgeirtj, thanks for using Timers.
> 
> Are you getting a banner notification like the one below? Or does that not show up either?
> 
> ![image](https://private-user-images.githubusercontent.com/72814106/324088299-e75dd9d7-9c70-45fe-9fad-9dd78e02cb36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTE1MTAsIm5iZiI6MTcxNDMxMTIxMCwicGF0aCI6Ii83MjgxNDEwNi8zMjQwODgyOTktZTc1ZGQ5ZDctOWM3MC00NWZlLTlmYWQtOWRkNzhlMDJjYjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDEzMzMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MDhhNDM0YmVlZDViNDM4MGM1MTllZWIwYzFkYTE4N2UxZmI4ZGNhMjk0OTRkMmQzNDVlMzY5MjgxZDBjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2JLEIL0Rsf1reybZTZmSSFsDR9PmhQRtQsQ8yNKRz0I)
> 
> Note: may be linked to #11500, will be investigating this soon.
> 
> @raycastbot rename this issue to "[Timers] No sound when timer finishes"

No. No notification. No sound. This is enabled.

![image](https://github.com/raycast/extensions/assets/27446620/a19d5b56-87e3-4bd1-a975-23ee1260526b)

**Comment by ThatNerdSquared** [comment]
It looks like the current fix I have submitted will not be allowed into the store.

I am working on a different, more temporary one, but unfortunately while it will restore sound it is unlikely to permanently restore the notification functionality.

**Comment by ThatNerdSquared** [comment]
@raycastbot close this issue
