### ISSUE TITLE
[Spotify Player] ... Toggle Smart Shuffle

### ISSUE THREAD

**Issue by BastiBudde** [raycast/extensions#11909]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Add a command to toggle Spotify´s new smart shuffle feature.

### Who will benefit from this feature?

People who use the smart shuffle feature.

**Comment by thomaslombart** [comment]
That would be a great feature! But it's unfortunately not available in the Spotify API. They have a [community](https://community.spotify.com/) where you can add feature requests so it's probably worth it asking it there. I'll close it out in the meantime to keep the backlog clean 🙂
