### ISSUE TITLE
[Outline Page] Adding Brave support ?

### ISSUE THREAD

**Issue by Decryptu** [raycast/extensions#11948]
### Extension

https://www.raycast.com/praveenjuge/outline-page

### Description

Hello ! Do you plan on adding support for the Brave browser ? would be awesome, thank you !

### Who will benefit from this feature?

All Brave users

### Anything else?

https://github.com/brave/brave-browser

**Comment by praveenjuge** [comment]
Hey @Decryptu, 

Brave should be supported, can you try enabling `Allow Javascript from Apple Events` from the `View > Developer` menu bar item.

Added this as a error state in #11955

**Comment by Decryptu** [comment]
> Hey @Decryptu,
> 
> Brave should be supported, can you try enabling `Allow Javascript from Apple Events` from the `View > Developer` menu bar item.
> 
> Added this as a error state in #11955

Oh thank you ! This was the issue, I don't know if you planned to do it, but adding this to the error message could be useful, have a nice day 🙏🏻
