### ISSUE TITLE
Throws an error on third toggle

### ISSUE THREAD

**Issue by varslot** [raycast/extensions#11957]
### Extension

https://www.raycast.com/SebDanielsson/background-sounds

### Description

I works when I toggle on, then off, but it fails and throws an error on the third toggle:
```
Error: Command failed with exit code 1: osascript
Background sound is on
Background sounds turned off
757:788: execution error: No matching processes belonging to you were found (1)

Background sound is on
Background sounds turned off
O9:run-applescript.js:38:21

---
35:         timedOut,
36:         command: "osascript",
37:         options,
38:         parentError: new Error(),
39:     });
40: }
41: exports.runAppleScript = runAppleScript;
---
```

https://github.com/raycast/extensions/assets/56486004/002ccfa4-6fa0-489c-ba2b-01473bbd7719

### Steps To Reproduce

1. Toggle Background Sounds in Raycast
2. Do this 3 times
3. Receive error

### Current Behaviour

Not working after 3 toggles. Then have to manually turn Background Sounds on/off in System Settings for it to work again.

### Expected Behaviour

To be able to toggle on and off unlimited

**Comment by varslot** [comment]
Raycast 1.71.4
Sonoma 14.4.1
<img width="1112" alt="image" src="https://github.com/raycast/extensions/assets/56486004/847b7993-e2b5-4ac8-9cb2-acca16012429">
<img width="392" alt="image" src="https://github.com/raycast/extensions/assets/56486004/d8dd224b-39a7-4a8d-9d78-4000881c0d70">

**Comment by sebdanielsson** [comment]
@pernielsentikaer did you try to toggle the sound on and off three times or more during testing? I can't reproduce on my end.

**Comment by pernielsentikaer** [comment]
I can't reproduce it here, toggled 10+ times in a row without any issues

macOS 14.4.1 (23E224)
Raycast 1.72.0

**Comment by varslot** [comment]
Tried updating to Raycast 1.72.1, and uninstall then re-install the extension. No luck so far. 

One thing I noticed is that the extension is not able to (at least not visually) toggle the Bakcground Sounds switch. Whenever I flip the switch after the error, I'm able to use the extension for a few runs again.

**Comment by sebdanielsson** [comment]
I think it's a UI thing.

I tried the following:

1. Open settings and see the Background Sounds switch set to off
2. Run the toggle command (The switch will still show that it's off)
3. Close settings and reopen (The switch will indicate that the sound is on)

If you're aware of a better way of changing macOS System Settings I'd be glad to try it out and update the extension.
