### ISSUE TITLE
[Unsplash] Unable to connect to Unsplash account

### ISSUE THREAD

**Issue by Spratch** [raycast/extensions#11968]
### Extension

https://www.raycast.com/eggsy/unsplash

### Description

The link to connect to Unsplash send to an error page with this message: 

> The redirect uri included is not valid.

So I am unable to connect and to use Unsplash extension.

### Steps To Reproduce

1. MacOS 14.3.1 (23D60), MacBook Pro M3
2. I installed the extension from the raycast store, added my access key and my secret key
3. Tried to search an image
4. Opened the link to connect account
5. See error message

**Comment by Devoxer** [comment]
I have the same problem, please fix it, and thanks for the wonderful app

**Comment by AOMJ2PMP** [comment]
meh, I stumbled upon the same problem, still don't know why...

**Comment by eggsy** [comment]
Please read the README file of the extension, there's also an image showing the setting that'll fix this issue in the comments of this issue.
