### ISSUE TITLE
[Keyboard Brightness] Error toast appears even when toggle is successful

### ISSUE THREAD

**Issue by clasick** [raycast/extensions#11966]
### Extension

https://www.raycast.com/huzef44/keyboard-brightness

### Description

When using the "Toggle Keyboard Brightness" action, the error toast "Failed Toggling Keyboard Brightness" appears even when the toggle is successful, i.e., the keyboard lights turn on/off as desired.

<img width="318" alt="image" src="https://github.com/raycast/extensions/assets/13066221/8aa9a2eb-8a17-4628-9749-9ea595c37ba2">

### Steps To Reproduce

1. Install the Keyboard Brightness extension
2. Open Raycast
3. Find and run the Toggle Keyboard Brightness command
4. Observe the physical keyboard lights are toggled from on to off, or off to on
5. Observe error toast appear in the bottom middle of the screen: "Failed Toggling Keyboard Brightness"

### Current Behaviour

Error toast appears when toggle is successful

### Expected Behaviour

Error toast should only be shown during toggle failure

**Comment by pernielsentikaer** [comment]
I added a fix [here](https://github.com/raycast/extensions/pull/12011) for it @DannySeidel

**Comment by pernielsentikaer** [comment]
Should be fixed now, thanks for flagging
