### ISSUE TITLE
Clipboard.copy to copy a file will copy the filename in text too

### ISSUE THREAD

**Issue by Ricinix** [raycast/extensions#11964]
### Description

If I copy a file in mac finder, and paste it in mac terminal, it will show the file in absolute path: xxx/file.xxx.
If I use @raycast/api `Clipboard.copy` to copy a file in absolute path, and paste it in mac terminal, it will show the file's absolute path and its filename: xxx/file.xxx file.xxx.

Go a step further, If I use `Clipboard.copy` to copy a file and paste it in an App's rich text editor, some App will resolve it to be a file and a text of filename.

### Steps To Reproduce

1. latest raycast v1.71.4
2. @raycast/api: 1.71.3

**Comment by thomaslombart** [comment]
Could you share a recording? It'll make it easier to see what's happening.

**Comment by Ricinix** [comment]
> Could you share a recording? It'll make it easier to see what's happening.
I record a video.

https://github.com/raycast/extensions/assets/46063163/c7649d7d-55ba-43ac-92f2-4563b128d052

The extension code is in the video. The code only includes `Clipboard.clear` and `Clipboard.copy` api.
If I use `Clipboard.copy` to copy, the result will have a 'package.json' at the end. If I use `command + C` to copy it in Finder, the result only has the file's absolute path.

**Comment by thomaslombart** [comment]
Thanks, we'll have a look at it.

**Comment by mathieudutour** [comment]
Good catch, it'll be fixed in the next release
