### ISSUE TITLE
[Apple Notes] ... use applenotes://showNote?identifier in URL for links as it works on both Mac and iOS 

### ISSUE THREAD

**Issue by feedfornotes** [raycast/extensions#11979]
### Extension

https://www.raycast.com/raycast/apple-notes

### Description

use applenotes://showNote?identifier in URL for links as it works on both Mac and iOS. please replace current mac and mobile URL link to notes with use applenotes://showNote?identifier as it works on both so no need to choose. great for linking notes to other apps that work across apple platforms. see Alfred apple notes plugin as it works across platforms. https://github.com/sballin/alfred-search-notes-app

### Who will benefit from this feature?

every users of apple notes links

**Comment by thomaslombart** [comment]
Where do you mean to replace it? In the copy to clipboard actions?

**Comment by feedfornotes** [comment]
In the note actions menu. you could replace two items with one if the URL extensionwas applenotes:// as that works on both mac and mobile. 

￼

**Comment by thomaslombart** [comment]
Oh, indeed! Nice catch.

**Comment by feedfornotes** [comment]
Thanks! looking forward to seeing this added in the future
