### ISSUE TITLE
[Pomodoro] Timer not showing in Menu Bar

### ISSUE THREAD

**Issue by luizkc** [raycast/extensions#11974]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

The extension works and the timers get started, but I can't see the status of the timer in the menu bar, even when toggling the command. I've tried resetting the command, restarting my Mac, re-installing the extension, updating Raycast, and still no luck.

### Steps To Reproduce

1. install extension
2. use "show in menu bar" command
3. start a timer
4. see nothing show up in the menubar

**Comment by zhangyu921** [comment]
same here
