### ISSUE TITLE
[Session - Pomodoro Focus Timer] "Session is not installed"

### ISSUE THREAD

**Issue by earnjam** [raycast/extensions#11972]
### Extension

https://www.raycast.com/jameslyons/session

### Description

When trying any of the commands I get a "Session is not installed" error. But I'm sitting here staring at the Session app, open and active. So it is definitely installed. 

![image](https://github.com/raycast/extensions/assets/4267290/c956a78a-463c-471c-9bbb-5c88e1c7f416)

### Steps To Reproduce

Install Session
Install Session Raycast Extension
Try to start a new session

**Comment by earnjam** [comment]
I think it's related to Raycast being installed globally and Setapp being installed for my current user. 

![image](https://github.com/raycast/extensions/assets/4267290/c77ef4b2-6751-4f45-a611-42ae07840dc9)

![image](https://github.com/raycast/extensions/assets/4267290/23466c6b-7a8c-4f82-b62b-20598da90770)

**Comment by jamesjlyons** [comment]
@earnjam I think I have a fix I can push for this, I'll submit it soon so we can see if it works

**Comment by jamesjlyons** [comment]
Just [submitted a PR](https://github.com/raycast/extensions/pull/13254) to fix this issue!
