### ISSUE TITLE
[Copy Path] Command unhides all Finder Windows

### ISSUE THREAD

**Issue by brunocbreis** [raycast/extensions#11971]
### Extension

https://www.raycast.com/koinzhang/copy-path

### Description

When I launch the command with a hotkey and I have more than one Finder window open (but most are hidden / minimized / out of focus), it brings all of them to the front of the screen, which is quite distracting.

### Steps To Reproduce

1. Open multiple Finder windows
2. Open other applications, have some Finder windows be hidden or behind them
3. Focus on one Finder window
4. Perform the command with a hotkey
5. All other Finder windows are brought to the front

### Current Behaviour

 Windows are brought to the front

### Expected Behaviour

Windows are kept where they are

**Comment by koinzhang** [comment]
Hi @brunocbreis The extension uses AppleScript to get the Finder directory, and if there are multiple visible Finder windows, the following script will automatically bring all Finder windows to the forefront when you run it. There is no good workaround for this yet, so if you have any suggestions feel free to chime in!

```
export const scriptFinderPath = `
if application "Finder" is not running then
    return "Finder not running"
end if

tell application "Finder"
    return POSIX path of ((insertion location) as alias)
end tell
`;
```

**Comment by koinzhang** [comment]
Hi @pernielsentikaer 
Latest discovery, this issue occurs when calling getSelectedItem on the Raycast extension, so I hope the Raycast team can fix it.

**Comment by koinzhang** [comment]
Hi @brunocbreis The latest version of Raycast fixes this issue, I'll switch off this issue
@raycastbot close this issue
