### ISSUE TITLE
[Obsidian] Silent mode not working

### ISSUE THREAD

**Issue by homostellaris** [raycast/extensions#11989]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

The 'silent mode' option of the append commands are not working for me, it still focus Obsidian when executing one of those commands.

### Steps To Reproduce

1. Check silent mode is turned on in extension settings
2. Execute "append task" or "append to daily note" command
3. Obsidian window is focused

**Comment by KevinBatdorf** [comment]
The extension uses the Advanced URI extension which requires the focus, unfortunately. Silent mode just means it won't open the file in a new tab.

https://vinzent03.github.io/obsidian-advanced-uri/concepts/navigation_parameters

**Comment by homostellaris** [comment]
Oh I see, apologies I misunderstood the feature. Great extension nevertheless and thanks for the quick response 🙏
