### ISSUE TITLE
Retain text styles from Zotero in "Copy as reference" [Search Zotero] ...

### ISSUE THREAD

**Issue by lutefiasco** [raycast/extensions#1198]
# Extension – [Search Zotero](https://github.com/raycast/extensions/tree/676dcc09a80b7a46a31a9c527b5dab9cda1429b1/extensions/zotero/)
Author: @sadanand-singh

Copy as Reference currently seems to use the Zotero app's default citation style, but does not preserve italics in titles and other places, which is both confusing and limits the utility of the feature.

Zotero and Raycast users will benefit.

Even more amazing would be copying Zotero's full citation output.

**Comment by sadanand-singh** [comment]
PR #1772 closes this
