### ISSUE TITLE
[Summarize YouTube Videos with AI] It fails to retrieve the transcript from youtube video

### ISSUE THREAD

**Issue by joseph1125** [raycast/extensions#11984]
### Extension

https://www.raycast.com/iKasch/summarize-youtube-video-with-ai

### Description

This extension no longer works because it always fails to retrieve the transcript from youtube video.

### Steps To Reproduce

execute the only command with any youtube video

**Comment by iKasch** [comment]
Thanks for reporting! There seems to be an issue with receiving transcripts from youtube videos, which are used to generate the summary. 
I'm on it.

**Comment by iKasch** [comment]
@raycastbot close this issue

This is fixed with #12108. Make sure to update your extensions.
