### ISSUE TITLE
[Github] Add a Menu Bar option for Workflow Runs

### ISSUE THREAD

**Issue by jasonshanks** [raycast/extensions#11986]
### Extension

https://www.raycast.com/raycast/github

### Description

It would be a bonus to have a Menu Bar option connected to Workflow Runs that displays the status of currently running Workflow Runs (especially when completed).

### Who will benefit from this feature?

Any developer using the Github extension authorised to view status of Workflow Runs on any of their repos.
Quite often we are waiting for a run to complete before testing the functionality on the resulting website or application.

### Anything else?

As an addendum: Perhaps add an 'All repositories' option to display runs across all repos on the Workflow runs command window.

<img width="270" alt="Screenshot 2024-04-25 at 7 57 06 PM" src="https://github.com/raycast/extensions/assets/719396/161659fa-d063-4a87-a0f1-a10828bf041f">

**Comment by xilopaint** [comment]
Isn't the workflow status in My Pull Requests Menu Bar enough for you?
