### ISSUE TITLE
Current versions of litra CLI not supported due to new major version

### ISSUE THREAD

**Issue by Nenuial** [raycast/extensions#11981]
### Extension

https://www.raycast.com/timrogers/logitech-litra

#### Error:
```
You are running v1.1.2 of the `litra` CLI which is too new for this Raycast extension. Please downgrade to v0.2.0 or a later version within the same major version.: 
```

Is it normal that your litra-rs version "runs ahead" of the raycast extension? Do I need to downgrade litra-rs to continue using the raycast extension?

### Steps To Reproduce

Update litra-rs to latest version.
Use the raycast litra extension.

**Comment by timrogers** [comment]
@Nenuial Thanks for flagging this! This is a bug.

**Comment by timrogers** [comment]
@raycastbot rename this issue to "Current versions of litra CLI not supported due to new major version"

**Comment by timrogers** [comment]
Fix awaiting review now: https://github.com/raycast/extensions/pull/12054
