### ISSUE TITLE
[Zed] Error when opening the list of projects

### ISSUE THREAD

**Issue by olrtg** [raycast/extensions#11995]
### Extension

https://raycast.com/ewgenius/zed-recent-projects

#### Error:
```
Error: Error: in prepare, no such column: workspace_location
  SELECT workspace_location, timestamp FROM workspaces
         ^--- error here

    at /Users/olrtg/.config/raycast/extensions/715b336d-1cef-4f40-be8a-f740b3f1656a/search.js:11:3767
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I've tried reinstalling the plugin but the error still appears.

### Steps To Reproduce

1. I don't know if it happens with the stable version of zed. I'm using the zed preview version (latest version).
2. Open raycast menu
3. Open "Search recent projects"
4. The error should appear

### Current Behaviour

Shows error without showing results.

### Expected Behaviour

Should list the recent projects.

**Comment by JoltCode** [comment]
> ### Extension
> https://raycast.com/ewgenius/zed-recent-projects
> 
> ### Description
> #### Error:
> ```
> Error: Error: in prepare, no such column: workspace_location
>   SELECT workspace_location, timestamp FROM workspaces
>          ^--- error here
> 
>     at /Users/olrtg/.config/raycast/extensions/715b336d-1cef-4f40-be8a-f740b3f1656a/search.js:11:3767
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```
> 
> I've tried reinstalling the plugin but the error still appears.
> 
> ### Steps To Reproduce
> 1. I don't know if it happens with the stable version of zed. I'm using the zed preview version (latest version).
> 2. Open raycast menu
> 3. Open "Search recent projects"
> 4. The error should appear
> 
> ### Current Behaviour
> Shows error without
> 
> ### Expected Behaviour
> Should list the recent projects.

Seems to work fine for me on stable... Perhaps a Zed preview bug then?

**Comment by jylamont** [comment]
It does seem like it is a preview bug.

**Comment by jylamont** [comment]
Relevant commit: https://github.com/zed-industries/zed/commit/e0c83a1d32c013c404db39b9739a931c69a948d9#diff-6382f48d94a492f88801acbbe0305809e0f2a81f088fde4c969e0eb225d457d8R300

> ALTER TABLE workspaces RENAME COLUMN workspace_location TO local_paths;

Now that this commit is on Zed stable, I'll go ahead and make a patch.
