### ISSUE TITLE
[Confluence] Allow API Token authorization

### ISSUE THREAD

**Issue by huylenq** [raycast/extensions#11991]
### Extension

https://www.raycast.com/tbrown/confluence

### Description

Similar to https://www.raycast.com/raycast/jira, allowing two methods to login:
1. Through OAuth (which is already supported)
2. Through API Token (requested feature).

### Who will benefit from this feature?

Employee under organization that disallow normal users to authorize OAuth apps but allowing create an API Token.

### Anything else?

Thank you for this already great plugin.

**Comment by Brabalawuka** [comment]
This is needed please help take a look!
