### ISSUE TITLE
[Corcel AI] Download Failed

### ISSUE THREAD

**Issue by jmabeebiz** [raycast/extensions#12000]
### Extension

https://www.raycast.com/corcel.io/corcel

### Description

Able to generate images fine, and I'm able to save the images to Raycast, but I cannot download the images. It just says download failed.

### Steps To Reproduce

Download an image after generation.

### Current Behaviour

The download fails

### Expected Behaviour

The download should be added to my computer.

**Comment by jmabeebiz** [comment]
Thanks. I did select the Downloads folder (and another folder, for testing) and the download failed error came up.

I do have a Downloads folder, but when I type it into Terminal, I get a permission denied error. Which is odd, because I'm the only person who's ever used my computer. It's not a work computer or anything like that. Why would that be?

Attached a screenshot of the error happening when I hit download or hit the shortcut.

Thanks,
// Justin Mabee
*Squarespace Designer | Available for Hire*
justinmabee.com ( http://justinmabee.com )
(267) 632-4103

Sent via Superhuman ( ***@***.*** )

**Comment by AkinAguda** [comment]
I assume you are replying via email. Therefore, I cannot see the screenshot. I would appreciate if you could try sending it through github.

* One thing you should check is that raycast has download permission. To ensure this, go to `System Preferences` -> `Security & Privacy` -> `Files and Folders` -> `Raycast` and check that `Downloads Folder` is checked. Let me know how it goes!

**Comment by jmabeebiz** [comment]
Sorry about that, I was replying via email.
Attached the screenshot here.
And yes, I checked the permission, I've downloaded stuff before so I'm not sure what could be the issue.
![CleanShot 2024-04-25 at 12 03 55](https://github.com/raycast/extensions/assets/74937547/000c720c-f3e0-410c-92d2-fe01dfe3a9d7)
