### ISSUE TITLE
[Toothpick]:  Include display name of device in the command name

### ISSUE THREAD

**Issue by jsheffers** [raycast/extensions#12001]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

I've entered the display name for two of my devices (AirPods Pro, Bose QC35). I was wondering if it would be possible to make the commands for favorites include the display name instead of some generic number 1, 2 or 3.  Maybe only create the favorite commands if the user has filled out a favorite with the display being the name like

"Connect Shane's AirPods Pro" instead of "Connect Favorite Device 1"

### Who will benefit from this feature?

I think this provides a better experience for connecting to favorites, and anyone using them could benefit from this.

**Comment by VladCuciureanu** [comment]
Hey Shane! This is already kind of implemented - when connecting via a favorite device command, the command description should update and persist for following uses. Let me know if it's not working as intended (or jump in the code yourself - any help is lovely)

**Comment by VladCuciureanu** [comment]
@raycastbot close this issue.
