### ISSUE TITLE
[Things] ... Keyboard Shortcut to engage with menu bar item

### ISSUE THREAD

**Issue by cb1433** [raycast/extensions#12003]
### Extension

https://www.raycast.com/loris/things

### Description

Love your Raycast extension! For the "Show Today In Menu Bar" command, I know you can assign an alias or hotkey via Raycast to make it appear as an option in the menu bar... but is there any way currently to use a keyboard shortcut to actually engage with/open the "Show Today In Menu Bar" menu bar item? In other words, could I actually open the menu bar item's list with just a keyboard command and not having to click it with my mouse? Then move down it via arrow keys, more keyboard commands, etc. It's a small thing but it'd be nice to engage with the menu bar without having to leave the keyboard. Thanks!

### Who will benefit from this feature?

Me. Maybe others? Lol.

**Comment by thomaslombart** [comment]
It is unfortunately not possible at the moment. I will discuss with the team if it is possible to support that 🙂

**Comment by thomaslombart** [comment]
It is not possible to support that as of now, but it is something we may look into further down the road. We're not sure when we will tackle that though, as there are no Apple APIs for that 🙂
