### ISSUE TITLE
[GitHub] Token in settings gets cleared randomly

### ISSUE THREAD

**Issue by asportnoy** [raycast/extensions#12004]
### Extension

https://www.raycast.com/raycast/github

### Description

Every once in a while, the GitHub token in the extension settings gets wiped. Recently, it has been happening every few hours or so (I think in the past it might've been less frequent, but not sure).

As far as I can tell, I'm not doing anything that would cause it to be wiped. Any idea what's up?

### Steps To Reproduce

Don't have consistent steps, but just set a token in settings and see if it goes away after a while. I'd recommend also logging out of the OAuth when you're testing since it will be more apparent when it's wiped.

**Comment by thomaslombart** [comment]
Do you mean the token over as shown in the screenshot below?

![CleanShot 2024-04-29 at 10 30 19@2x](https://github.com/raycast/extensions/assets/16003285/1b54223e-acde-4b5f-8e91-dd8531031fb4)

**Comment by asportnoy** [comment]
Yes that's correct.

**Comment by thomaslombart** [comment]
It seems to be a bug within Raycast. The team is investigating it. I'll get back to you as soon as I know more 🙂
