### ISSUE TITLE
[GitHub Stars] authentication/token  support

### ISSUE THREAD

**Issue by macoswk** [raycast/extensions#12014]
### Extension

https://www.raycast.com/mrmartineau/search-github-stars

### Description

reference
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/setting-your-profile-to-private

### Who will benefit from this feature?

everyone

**Comment by mrmartineau** [comment]
@macoswk what exactly do you want to change here? Please can you provide more information
