### ISSUE TITLE
[Safari] Search Tab Groups

### ISSUE THREAD

**Issue by vlcinsky** [raycast/extensions#12016]
### Extension

https://www.raycast.com/loris/safari

### Description

Add command Search Tab Groups.

The command would search for a tab group  through all tab group names (not for tabs - yet).

Using search filter and Ctrl-N and Ctrl-P, one would focus on tab group of interest.

There would be only one action: using Enter, it would continue searching through tabs in given tab group.

It would be great to start with focus on the current tab group tab (as if you would open the tab group manually - the one which is active at given moment).

Default action would be open the tab group with given tab. Complete set of actions for this step would be identical with  current "Search Tabs". 

### Who will benefit from this feature?

When using Safari Tab Groups, tabs are nicely organized into smaller sets which are simpler to overview and which support more focused work.
I use tab groups such as:
- Monitoring: with Nagios and Grafana Cloud dashboard for quick check that all systems are up and running
- WI#147: for tabs related to my active work item #147 (I have more such tab groups)
- Work: Catch all tab group for ad hoc research.

With [Safari] Search Tab Groups, switching among tab groups and selecting proper tab would be much simpler.

### Anything else?

Note, that there are other issues similar to this one, but none approaches the search (of tabs) by picking up a tab group.

**Comment by marcjulianschwarz** [comment]
+1, That would be a really nice addition and extremely helpful. The current way of opening tab groups in Safari is quite slow and requires many clicks. Searching for it in Raycast would be way faster.

**Comment by samtsevich** [comment]
up

**Comment by giogt** [comment]
+1, this would be my perfect workflow.

I really like the Safari tab groups functionality and prefer it to how it is done in other browsers. But there isn't a straightforward way that I know of to easily search for tabs in tab groups and select the desired one by using only the keyboard.
