### ISSUE TITLE
[Linear] Add support for documents

### ISSUE THREAD

**Issue by dotlouis** [raycast/extensions#12029]
### Extension

https://www.raycast.com/linear/linear

### Description

Right now, the extension allows us to search for issues and projects.
I use project documents quite extensively (I sometimes have 10 project docs) and would love to be able to search them also.
Preferably globally, but I could also search for the project first and then use an action to search for its documents.

### Who will benefit from this feature?

Any Linear user that uses the [project documents feature](https://linear.app/docs/project-documents).

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the Slack community if you need further help.

**Comment by dotlouis** [comment]
Yes why not. I'll see what I can do and update here :)

**Comment by jfkisafk** [comment]
We can try to associate this with https://github.com/raycast/extensions/issues/13030. I think a command addition and an action for opening project docs can go hand in hand

**Comment by thomaslombart** [comment]
Good idea. I've closed the other issue and renamed this one accordingly.

**Comment by jfkisafk** [comment]
@raycastbot assign me
