### ISSUE TITLE
[Sonarr] ...

### ISSUE THREAD

**Issue by klept0** [raycast/extensions#12030]
### Extension

https://www.raycast.com/Aayush9029/sonarr

### Description

Receiving "Unexpected end of JSON input" error

### Steps To Reproduce

Set auth to HTTP or HTTPS (both give same error when testing)
Input API key (regenerated it multiple times for testing)
Verified port (changed for testing as well)
![image](https://github.com/raycast/extensions/assets/4031266/196067be-335e-4123-86ed-ec0e2036dc2f)

### Expected Behaviour

It *should* show the current shows based upon selection in extension

**Comment by Aayush9029** [comment]
@raycastbot assign @j3lte

**Comment by j3lte** [comment]
@raycastbot close this issue
