### ISSUE TITLE
1Password 8 / My Passwords error: The "file" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by filipvanreeth** [raycast/extensions#12039]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

I'm running the latest MacOS + 1Password 8 version. When I try to access the My Passwords command I get the following Javascript error: 'The "file" argument must be of type string. Received undefined'. Maybe interesting to mention, I installed 1Password via Homebrew.

![CleanShot 2024-04-27 at 10 09 40@2x](https://github.com/raycast/extensions/assets/155639/282ef87b-5e77-4a1d-b2ec-67a26c362b7d)

### Steps To Reproduce

1. Lastest MacOS version
2. Latest 1 Password 8 version
3. Latest Raycast version
4. Open My Passwords

### Current Behaviour

Gets the following Javascript error: 'The "file" argument must be of type string. Received undefined'.

### Expected Behaviour

Should open the 1Password items

**Comment by chvanikoff** [comment]
Same here

**Comment by Luk4h** [comment]
When you guys run "where op" on your terminal, what is the response?

**Comment by filipvanreeth** [comment]
@Luk4h I get 'op not found'.

**Comment by kRew94** [comment]
same here

**Comment by Luk4h** [comment]
That should mean that you don't have the 1Password CLI installed correctly guys. You probably should check on how to install that. It is on the 1Password app settings. You can also refer to the guide on the description of the extension

**Comment by filipvanreethio** [comment]
Installed 1Password CLI also and it works now. Thanks for the great support.

**Comment by PawGangsta** [comment]
Hello, I was facing the same problem, and I followed the steps. However, every time I authorize it gives me this error (• Unexpected end of JSON input). Can anyone help?

**Comment by Luk4h** [comment]
Could you open a new issue describing and giving a step by step? It will be easier for us to help you.
Also I recommend to try using the command in your terminal! For example if you are trying to retrieve the password for item named GitHub, run the following command on your terminal: ’op item get GitHub’. And see what it returns.
