### ISSUE TITLE
[Bitwarden] InstalledCLINotFoundError: Bitwarden CLI not found at /opt/homebrew/bin/bw

### ISSUE THREAD

**Issue by regnerisch** [raycast/extensions#12037]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

I'm using Nix as my package manager but the extention seem to search bw only at a specific path. 

The path of Nix package manager is `~/.nix-profile/bin/bw`(`which bw`)

### Steps To Reproduce

1. Install nix
2. Install bw-cli via nix (`nix-env -iA nixpkgs.bitwarden-cli`)
3. Log into Bitwarden

### Current Behaviour

After login getting: InstalledCLINotFoundError: Bitwarden CLI not found at /opt/homebrew/bin/bw

### Expected Behaviour

Searching for bw-cli and working without error.

**Comment by jomifepe** [comment]
Hello, the extension currently is not able to see if you have the CLI installed in some unpredictable place, only in `/opt/homebrew/bin/bw` and `/usr/local/bin/bw`, but you can always specify your path (`~/.nix-profile/bin/bw`) in the extension preferences. 

![Screenshot 2024-04-29 at 10 06 39](https://github.com/raycast/extensions/assets/7235666/6a72fbe0-5542-403f-9818-a567901c5665)

**Comment by regnerisch** [comment]
Thanks for your reply, but the error persists after adding the path manually: 

`InstalledCLINotFoundError: Bitwarden CLI not found at /Users/jonas/.nix-profile/bin/bw`

**Comment by jomifepe** [comment]
That is odd, the errors comes from checking if it exists and if raycast has permissions to execute it, everything should be working as expected. I will investigate it.

**Comment by regnerisch** [comment]
Yes.

<img width="697" alt="grafik" src="https://github.com/raycast/extensions/assets/9422737/caf4cd2c-4a5d-45b9-9c57-092294379cff">
