### ISSUE TITLE
[Obsidian] Append Task... to the Daily Note!

### ISSUE THREAD

**Issue by memee** [raycast/extensions#12038]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

Right now the note to which I can append to is fixed. I would like to be able to append to the current daily note which makes more sense to me. Meanwhile the possibility to have fixed "Inbox" note should be preserved.

### Who will benefit from this feature?

People who work mostly with their daily notes as a mean of organization.

**Comment by KevinBatdorf** [comment]
Hey, can you explain what you mean by fixed? Can you tell me more about your workflow and the command you use?

**Comment by memee** [comment]
@KevinBatdorf Here's "Append Task" command configuration panel:

<img width="317" alt="Zrzut ekranu 2024-05-30 o 14 49 32" src="https://github.com/raycast/extensions/assets/1036737/bd3fa0a8-48d1-43d9-ba96-ce90aea02e67">
"Path of the note you wish to append the task to" <-- this is what I understand as fixed.

I would like to have a checkbox/flag that says "Append to a periodic TODAY daily note" rather than specifying fixed note to append to.

**Comment by memee** [comment]
Great, that'll do.

**Comment by rs7911** [comment]
Just started using Raycast and have an issue with appending a task.

My Daily notes format is: YYYY-MM-DD-dddd
I tried putting {YYYY-MM-DD-dddd}, as well as {YYYY}-{MM}-{DD}-{dddd}, but I'm still not seeing my daily note update.
There seems to be no error message either.

Any suggestions?
