### ISSUE TITLE
[Tailscale] Add Custom Admi Console

### ISSUE THREAD

**Issue by LucasJanin** [raycast/extensions#12048]
### Extension

https://www.raycast.com/tailscale/tailscale

### Description

When you use Headscale, the open-source implementation of the Tailscale server, you have a different administration page. It would be nice to add the option to add a custom Admin Console URL in the plugin settings.

### Who will benefit from this feature?

People use the Headscale implementation (https://headscale.net) with a UI implementation like Headscale-admin (https://github.com/GoodiesHQ/headscale-admin). Other interfaces exist for Headscale: https://headscale.net/web-ui/

### Anything else?

Thanks for your nice plugin!

**Comment by LucasJanin** [comment]
This request is still valid

**Comment by erics118** [comment]
@raycastbot keep this issue open
