### ISSUE TITLE
[Ollama AI] - Possibility to define language

### ISSUE THREAD

**Issue by Angelblot** [raycast/extensions#12040]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

It would be interesting to be able to preset a language in order to be able to use all the pre-registered commands instead of having to create Custom Commands to do the same thing again.

### Who will benefit from this feature?

All non-Anglo-Saxon people

**Comment by MassimilianoPasquini97** [comment]
Duplicated #11274

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue
