### ISSUE TITLE
[Word Search] Can you please add Autofill Input functionality?

### ISSUE THREAD

**Issue by jewenso** [raycast/extensions#12045]
### Extension

https://www.raycast.com/rishabswift/word-search

### Description

Hi,

Thank you for creating the extension, I use it everyday.

I wonder if you could add a simple feature to automatically paste the currently selected word into the extension whenever you open word search (synonyms, antonyms etc). Without the need to select the word, copy the word, and then paste it to the extension.

Thank you

**Comment by bkeys818** [comment]
This may not be best for all users. It wouldn't exactly follow user expectations.

Checking when the text was copied would solve that problem, but that's not possible with the Raycast API at the moment.

**Comment by j3lte** [comment]
Added in last update

@raycastbot close this issue
