### ISSUE TITLE
[Alacritty] "Edit File in Alacritty" fails

### ISSUE THREAD

**Issue by kfernandez31** [raycast/extensions#12052]
### Extension

https://www.raycast.com/jose-elias-alvarez/alacritty

### Description

The command fails, doesn't open a file as intended. My `$EDITOR` is set to `nvim` by the way.

### Steps To Reproduce

Run "Edit File in Alacritty" 

### Current Behaviour

```
Error
2024-04-28 09:24:35.200
alacritty[35243:40346299] WARNING: Secure
coding is not enabled for restorable state!
Enable secure coding by implementing NSA...
```

### Expected Behaviour

The file should be opened in `$EDITOR` within an Alacritty window.

**Comment by kfernandez31** [comment]
Note: the same Error/Warning appears for the `Open Folder in Alacritty` command as well.

**Comment by kfernandez31** [comment]
Also, any reason the shell opened is not a login one?

**Comment by hoschi** [comment]
I have also problems with these actions. In my case it says it can't execute `fzf` in my `.zshrc` which works fine when not Alacritty isn't spawned by this extension.

**Comment by kfernandez31** [comment]
> I have also problems with these actions. In my case it says it can't execute `fzf` in my `.zshrc` which works fine when not Alacritty isn't spawned by this extension.

iirc this is due to the shell spawned being a [non-login interactive](https://www.freecodecamp.org/news/how-do-zsh-configuration-files-work/) one, so it doesn't source your `.zprofile` in which a setup for `fzf` and others is located. Try moving that setup (probably some `eval`s) to `.zshrc`.

**Comment by Jihillestad** [comment]
I am affected by the same bug. Both ~/.zshrc and ~/.zprofile are sourced anbd have this line:
```bash
export EDITOR="/opt/homebrew/bin/nvim"
```

**Comment by jose-elias-alvarez** [comment]
I mentioned this in another issue, but I'm afraid that I'm no longer using Alacritty and so will not be able to work on this myself but am happy to provide guidance if needed for anyone who wants to put in a fix.

I recall that there was some reason why I couldn't just use a login shell (Alacritty isn't a great macOS citizen) but it might be worth looking into, since that seems like it would solve this issue.
