### ISSUE TITLE
[Alacritty] "Edit File in Alacritty" - add support for terminal-based editors (TBEs)

### ISSUE THREAD

**Issue by kfernandez31** [raycast/extensions#12053]
### Extension

https://www.raycast.com/jose-elias-alvarez/alacritty

### Description

Currently, the "Edit File in Alacritty" does not support editing a file in a TBE. It instead assumes that `$EDITOR` can be ran standalone, such as is the case with the `code` command for Visual Studio Code. It would be nice for this not to be the case, consequently supporting NeoVim, Emacs, etc.

### Who will benefit from this feature?

TBE users.

### Anything else?

My personal workaround, since I do use a TBE:
```diff
+  const { shellPath } = getAlacrittyPreferences();
   const editor = getEditor();
   const paths = items.map((item) => `'${item.path}'`).join(" ");
-  const command = `${editor} ${paths}`;
+  const command = `${shellPath} -l -c '${editor} ${paths}'`;
   await runShellCommand(command);
 });
 ```

**Comment by jose-elias-alvarez** [comment]
Apologies, I’m no longer using Alacritty so I won’t be able to help out with this.
