### ISSUE TITLE
[Apple Reminders] ... Menu Bar request

### ISSUE THREAD

**Issue by MatchaWhisk** [raycast/extensions#12062]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

This extension is so amazing, I love it! Is there a way to simulate clicking on the menu bar reminders so I can see all my reminders from the menu bar without having to click on it? Currently, I have to transfer my hand from my keyboard to my mouse, then move my mouse to the Menu bar reminders icon, and click on it in order to expand the icon. I haven't found a way to do that with a shortcut or using raycast. I think if the "menu bar remindes" command can refresh, but also expand (by simulating clicking on the menu bar icon) and showing all the reminders would be useful.

### Who will benefit from this feature?

I think everyone would benefit. "My reminders" is great but it doesn't show all the reminders without having to scroll. The menu bar reminders shows all reminders without having to scroll. But this extension is already awesome!

### Anything else?

No, but I love this extension and hope it will get better and better with time! Thank you!

**Comment by MatchaWhisk** [comment]
Actually, I found a workaround by setting a hotkey with Bartender! Although it would still be nice to have the menu bar icon expand with the "menu bar reminders" command.

![image](https://github.com/raycast/extensions/assets/24281977/970e2ec2-8a62-435f-9db1-e41812958563)

**Comment by thomaslombart** [comment]
It is unfortunately not possible at the moment. I will discuss with the team if it is possible to support that 🙂

**Comment by thomaslombart** [comment]
It is not possible to support that as of now, but it is something we may look into further down the road. We're not sure when we will tackle that though, as there are no Apple APIs for that 🙂
