### ISSUE TITLE
[Ollama AI] Implementing `keep_alive` parameter

### ISSUE THREAD

**Issue by ibehnam** [raycast/extensions#12061]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

ollama doesn't keep the model in memory by default. If we don't use the extension for a few minutes, the model gets unloaded from memory. Which means the next time we use the extension, the model needs to be loaded into the memory again, which takes several seconds (sometimes a couple minutes).

ollama recently added `use_mlock` flag for the API requests, so it'd be nice to turn that on by default for this extension.

### Who will benefit from this feature?

Everyone.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot assign me

**Comment by MassimilianoPasquini97** [comment]
@raycastbot rename this issue to "[Ollama AI] Implementing `keep_alive` parameter"

**Comment by MassimilianoPasquini97** [comment]
Hi @ibehnam ,
This could be a valuable feature to implement, allowing for greater personalization for advanced users. By default, models remain in memory for five minutes. However, this behavior can be customized using the `keep_alive` parameter in a JSON request. This option enables setting the number of minutes the model should stay in memory or using a -1 value to keep it permanently active.

I'm currently refactoring the project to add new features. One of these allows configuring more Ollama Servers, so now I can implement the `keep_alive` on three different mode:
- Globally through extension preferences.
- For each Ollama Server.
- For every model.

 It's likely the best choice to implement it on Ollama Server. I welcome any alternative suggestions.

**Comment by ibehnam** [comment]
@MassimilianoPasquini97 Thank you! Yes, I think this will allow the users use ollama more often as it reduces model latency.

On a side note, it'd be great to include a "New Chat" feature in the extension. Currently, the user needs to manually archive the conversation (CMD-S), enter a name for the conversation, and then be able to start a new chat. It'd be nice to name the chats by their first few words, group them based on their dates, and just have a simple CMD-N shortcut to start a new chat.

**Comment by MassimilianoPasquini97** [comment]
Requested feature introduced on latest update #12734

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue
