### ISSUE TITLE
Obsidian: Opens Daily Note On Write, Ignores 'Silent Mode' 

### ISSUE THREAD

**Issue by janss-en** [raycast/extensions#12080]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

I have 'Silent Mode' ticked in the 'Append to Daily Note' Obsidian Raycast settings. And in my Obsidian Advanced URI plugin settings, I have 'Open file on Write' unticked. Despite this, Obsidian continues opening whenever I append text. I've tried reinstalling both the Raycast extension and Obsidian plugin. 

### Steps To Reproduce

1. Navigate to 'Append to Daily Note' Obsidian Raycast settings. 
2. Select 'Silent Mode'.
3. Navigate to Advanced URI plugin settings in Obsidian. 
4. Deselect 'Open file on write' options.
5. Execute 'Append to Daily Note' command.
6. Validate if text is appended in background (which is desired result), or if Obsidian opens when text is appended.

### Current Behaviour

The Obsidian app opens as text is appended, disrupting flow. 

### Expected Behaviour

Text is appended in the background without opening the Obsidian app.

**Comment by KevinBatdorf** [comment]
Sorry for the late reply. Advanced URI will still open Obsidian, but the option is just whether to open the file in question in a new tab within Obsidian. The focus is unfortunately required.

**Comment by AdamAdamsMusic** [comment]
Would a workaround with a direct access to the file within the file system be out of scope for this extension? Can't remember if Raycast requests Full Disk Access permission when setting up, but if so - we could do it this way.

**Comment by KevinBatdorf** [comment]
That would work, but would also require a large rewrite of the extension. It probably needs to be done though. Im just not sure when the best time for that is.
