### ISSUE TITLE
[Office Quotes] Failed to load quotes getaddrinfo ENOTFOUND officeapi.dev

### ISSUE THREAD

**Issue by podlesny-j** [raycast/extensions#12094]
### Extension

https://www.raycast.com/braydoncoyer/office-quotes

### Description

<img width="886" alt="image" src="https://github.com/raycast/extensions/assets/78863563/13dadc20-8d9f-4632-b317-ec5c85e06ca9">

### Steps To Reproduce

1. Install extension
2. Run extension's only command
3. See the error:
` Failed to load quotes getaddrinfo ENOTFOUND officeapi.dev`

**Comment by braydoncoyer** [comment]
Unfortunately, the API has been discontinued. I think that it makes sense to remove this extension from the store.

**Comment by xmok** [comment]
Fret not, my friends. PR #12930 is here to help 👀.
