### ISSUE TITLE
[Summarize YouTube Videos with AI] ...

### ISSUE THREAD

**Issue by alexsmedile** [raycast/extensions#12092]
### Extension

https://www.raycast.com/iKasch/summarize-youtube-video-with-ai

### Description

This app just gives error: Sorry, no YT transcript.

### Steps To Reproduce

Insert API. Select a Video. Paste Link.

### Current Behaviour

Error

### Expected Behaviour

Summary

**Comment by iKasch** [comment]
Hey @alexsmedile - Thanks for reporting. Youtube changed the location of the transcripts and they are currently not accessible for the extension. I'm working on a fix, which should be available soon. 🙏
