### ISSUE TITLE
[Grafana] API keys deprecated

### ISSUE THREAD

**Issue by lnlyssg** [raycast/extensions#12103]
### Description

As per https://grafana.com/docs/grafana/latest/administration/api-keys/ API keys do not work in newer versions of Grafana and have been replaced with Service Accounts

### Who will benefit from this feature?

Anyone using Grafana

**Comment by fabiosangregorio** [comment]
Any plan to support Service Accounts @Lp-Francois? 🙏🏻

**Comment by Lp-Francois** [comment]
Hey @fabiosangregorio, It's definitely something to add!
