### ISSUE TITLE
[1Password] Support for two logins (business and family account)

### ISSUE THREAD

**Issue by ashkrosh** [raycast/extensions#12102]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Currently if I login using my business account I have access to my business vaults but not my family account vaults. 

Is it possible to be logged in both? 

PS: all business plan users have access to free family accounts on 1Password.

**Comment by Luk4h** [comment]
With the latest update, the extension is able to use multiple vaults, filter items per vault, and switch accounts in extension. Right now there are no support for retrieving the passwords for multiple accounts at once. I will be leaving this issue open if someone is interested in trying the hard way to cycle between the user accounts and retrieving the passwords.

**Comment by cmpaul** [comment]
+1 to original issue. I just installed Raycast and this extension today. 

When I am signed into multiple 1Password accounts and open "My Vaults" via the extension, I see this error:
<img width="344" alt="image" src="https://github.com/raycast/extensions/assets/380070/de139274-df3d-489e-a8c6-e809ccb9737e">

**Comment by 2start** [comment]
Would be great to have this feature. Same use case businesss + private
