### ISSUE TITLE
[Background Sounds] Toggle command does not work

### ISSUE THREAD

**Issue by Swebi** [raycast/extensions#12112]
### Extension

https://www.raycast.com/SebDanielsson/background-sounds

### Description

Got this error error a few times, and other times it works, i get the popup the background sound toggled but doesn't actually toggle the sound

#### Error:
```
Error: Command failed with exit code 1: osascript
Background sound is off
Background sounds turned on
757:788: execution error: No matching processes belonging to you were found (1)

Background sound is off
Background sounds turned on
O9:run-applescript.js:38:21

---
35:         timedOut,
36:         command: "osascript",
37:         options,
38:         parentError: new Error(),
39:     })
```

### Steps To Reproduce

Open raycast and open the toggle background sound command

https://github.com/raycast/extensions/assets/82446436/0e8167bc-2fb6-4c6c-bcd1-5220bb76dde2

**Comment by sebdanielsson** [comment]
What version of macOS and Raycast are you running?
