### ISSUE TITLE
[Bitwarden Vault] `Add New Login` feature for Raycast extension

### ISSUE THREAD

**Issue by zeroaddresss** [raycast/extensions#12115]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Users should be able to add new logins (i.e., adding new email:pw credentials for a website) directly from Raycast without the need of opening Bitwarden App, logging in and go through all steps manually. This is a very frequent action, hence the benefit would be massive

### Who will benefit from this feature?

The extension currently offers the core functionalities, however I often find myself forced to open Bitwarden app, login and do all the manual steps to add a new login.
This happens pretty often and is generally annoying, since every time you sign up to a new website you have to add a new login to your vault.
With this feature being included in the extension commands, users would benefit with a smoother user experience since you can basically perform any frequent BW action directly from your Raycast.
Adding a new login credentials is an action that a common users performs pretty often, and it could really be useful if it could be done directly from Raycast.

**Comment by jomifepe** [comment]
Hello, this might come in the future. As always, I would also gladly review a PR that would implement it 😜
