### ISSUE TITLE
[Coffee] The caffeinate state does not show up in the status bar - impossible to disable

### ISSUE THREAD

**Issue by gregkoganvmm** [raycast/extensions#12120]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

The caffeinate state does not show up in the status bar - it is impossible to disable the "caffeinated" state from the status bar. The only way to do it is to find and kill the `caffeinate` process

### Steps To Reproduce

Environment: macOS Sonoma 14.4.1, Raycast 1.72.1
Click the "caffeinate" button

### Current Behaviour

The `caffeinate` process is launched, but the state is not reflected in the status bar and you cannot click the "decaffeinate" button. The decaffeinate command has no effect as well.

### Expected Behaviour

Should be able to disable the caffeinated state from the status bar

**Comment by xilopaint** [comment]
The issue has been resolved.

@raycastbot close this issue
