### ISSUE TITLE
[Bilibili] Functional Recommendations 

### ISSUE THREAD

**Issue by JordanQD** [raycast/extensions#12128]
### Extension

https://www.raycast.com/Fatpandac/bilibili

### Description

I hope it's possible to add a feature: add dynamic feed video to Watch Later
希望可以增加一个功能：将动态视频添加到稍候再看

**Comment by Fatpandac** [comment]
目前有一个功能可以添加视频观看提醒到 提醒事项 中，不知道能否满足你的需求。
<img width="391" alt="image" src="https://github.com/raycast/extensions/assets/30423976/38a7750a-a7ec-4adb-8b23-291d95c1e2bf">
