### ISSUE TITLE
[TinyPNG] ...

### ISSUE THREAD

**Issue by nuggbugg** [raycast/extensions#12126]
### Extension

https://www.raycast.com/kawamataryo/tinypng

### Description

Iam getting this error when trying to compress

### Steps To Reproduce

Opening raycast, searching tiny plugin, trying to compress
![CleanShot 2024-05-02 at 13 05 53](https://github.com/raycast/extensions/assets/168733556/2942c88d-cc76-454b-93f8-5cba1ac37efa)

**Comment by xilopaint** [comment]
Did you make sure that Finder is your frontmost application? The command works for me.
