### ISSUE TITLE
[Send to Workflowy Inbox] ...

### ISSUE THREAD

**Issue by bode-p** [raycast/extensions#12139]
### Extension

https://www.raycast.com/cameron_pak/workflowy-inbox

### Description

Thank you so much for this extension! I am immensely grateful for it and cannot emphasize enough how useful it has been.

Is it possible to add multiple fields via Extension Preferences so that the user can add numerous "Workflowy Save Location URLs"?  These multiple locations could be represented in the extension's UI as a dropdown menu. This update would allow Workflowy users to choose from multiple locations (depending on the context) instead of only being able to send the text to one exclusive location.

The extension's dropdown menu could remember the last location selected by the user, so they don't have to select it again each time they launch the extension. Alternatively, the user could select a default location. 

Thank you for your consideration!

### Who will benefit from this feature?

Anyone who would quickly like to capture bullet text to various locations.

**Comment by cameronapak** [comment]
@raycastbot good first issue

**Comment by cameronapak** [comment]
@bode-p, thanks for this idea! I no longer use Workflowy on my day to day, so I will not be the one creating this functionality. However, if you or someone you know is able to code this, the code is open-sourced and you please do feel free to contribute!
