### ISSUE TITLE
[gitlab] add option to filter out MRs you already approved from "My reviews"

### ISSUE THREAD

**Issue by chadlavi** [raycast/extensions#12136]
### Extension

https://www.raycast.com/tonka3000/gitlab

### Description

The "My reviews" command/menu bar item shows MRs that the user has already approved, making it difficult to use this functionality as a todo list.

GitLab's API seems to offer the ability to query approver IDs. It would be helpful to have a checkbox (unchecked by default) in the Extension settings to exclude MRs you already approved from the list of MRs in "My reviews".

### Who will benefit from this feature?

Users who want to use the "My reviews" command/menu bar item as a todo list of MRs that need their attention.

**Comment by macbookandrew** [comment]
https://github.com/raycast/extensions/issues/11190 would be one way to accomplish this
