### ISSUE TITLE
Fails, needs an *.EXE [Capture Fullpage of Website] ...

### ISSUE THREAD

**Issue by michaelwoodruff** [raycast/extensions#12149]
### Extension

https://www.raycast.com/Coun1er/capture-fullpage-of-website

### Description

Fails, needs an *.EXE 

### Steps To Reproduce

run ext
enter URL

### Current Behaviour

Fails, needs an *.EXE 

### Expected Behaviour

Not fail

**Comment by j3lte** [comment]
Should be fixed in #12814

@raycastbot close this issue
