### ISSUE TITLE
[Arc] Unable to fetch latest data

### ISSUE THREAD

**Issue by VatsalSy** [raycast/extensions#12142]
### Extension

https://raycast.com/the-browser-company/arc

#### Error:
```
Error: Command failed with exit code 1: osascript
659:669: execution error: Arc got an error: Can’t get window 1. Invalid index. (-1719)
    at A_ (/Users/vatsal/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search.js:31:3082)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async hs (/Users/vatsal/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search.js:65:1463)
```

### Steps To Reproduce

1. Raycast version: 1.72.1
2. Arc version 1.40.1
3. use search arc command 

### Current Behaviour

When using search arc command, it gives an error/warning: "Failed to fetch the latest data"

From what I can tell, there is no issues as the command still indexes all relevant window (including this one which I am using to write this bug report). 

<img width="487" alt="Screenshot 2024-05-03 at 07 26 12" src="https://github.com/raycast/extensions/assets/17101345/a61fc531-366a-4d46-8396-0689d9377964">

<img width="306" alt="Screenshot 2024-05-03 at 07 26 38" src="https://github.com/raycast/extensions/assets/17101345/eec0e319-92f8-44ce-8f88-322719d70b78">

### Expected Behaviour

Should simply show all latest search results without throwing the error/warning.

**Comment by VatsalSy** [comment]
Never mind. Issue solved by updating arc to v 1.41

**Comment by tomgenoni** [comment]
I can replicate this issue reliably if I don't have any Arc windows open. Using Arc Version 1.41.0 (49440)

**Comment by VatsalSy** [comment]
> I can replicate this issue reliably when using "Search Spaces" if Arc is running but I don't have any Arc windows/tabs open. Using Arc Version 1.41.0 (49440)

Yes, indeed, I could reproduce this issue reliably if

* Arc is closed. 
* Arc is running but there are no windows open.
