### ISSUE TITLE
[Jira] Error management can be improved

### ISSUE THREAD

**Issue by luarmr** [raycast/extensions#12154]
### Extension

https://www.raycast.com/raycast/jira

### Description

I'm unable to create an issue after fill of the form (I did before successfully ), likely due to something tied to my workflow in Jira. However, I'm unsure about the specific problem because the information I'm receiving is limited. `Failed creating issue`
It will be great to be able to see the response from the server.

### Who will benefit from this feature?

Every user?

### Anything else?

Observe that the app is functioning well. I can view my tasks and the entire sprints and filters. Actually, the app is very impressive.

**Comment by thomaslombart** [comment]
Could you share a recording? It'll make it easier to see what's happening.

**Comment by thomaslombart** [comment]
Indeed! Something is likely missing [here](https://github.com/raycast/extensions/blob/c70953d54e8cf09238e0b90d715f3b6a677c80eb/extensions/jira/src/helpers/issues.ts#L230). Do you want to take a look at it? 🙂
