### ISSUE TITLE
[Timers] Prevent autoclose on stopwatch start

### ISSUE THREAD

**Issue by Saidelocha** [raycast/extensions#12162]
### Extension

https://www.raycast.com/ThatNerd/timers

### Description

Hello,

Could you please make that raycast window stay open in the management menu after a stopwatch is start ? 

Thanks in advance.
Bests

### Who will benefit from this feature?

Everyone

**Comment by ThatNerdSquared** [comment]
Hi @Saidelocha, thanks for using Timers!

I'll add a setting for this in the next update.

**Comment by Saidelocha** [comment]
Hello @ThatNerdSquared,

Thank you very much!

**Comment by ThatNerdSquared** [comment]
@raycastbot rename this issue to "[Timers] Prevent autoclose on stopwatch start"

There's currently a preference for this already out on the store, but it is a little buggy. I've submitted a change to the store to fix this - it should be out shortly. Thanks for your patience.

**Comment by ThatNerdSquared** [comment]
This is now live on the store!
