### ISSUE TITLE
[Zed] search recent projects not working

### ISSUE THREAD

**Issue by auspy** [raycast/extensions#12163]
### Extension

https://raycast.com/ewgenius/zed-recent-projects

#### Error:
```
Error: Error: in prepare, no such column: local_paths
  SELECT local_paths, timestamp FROM workspaces
         ^--- error here

    at /Users/spark/.config/raycast/extensions/715b336d-1cef-4f40-be8a-f740b3f1656a/search.js:11:3767
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

idk started happening randomly

**Comment by ewgenius** [comment]
Hello @auspy, thanks for reporting. Most likely you have old version of Zed, could you please check? Workspaces schema was recently updated, see #11995 and #12137

**Comment by auspy** [comment]
> Hello @auspy, thanks for reporting. Most likely you have old version of Zed, could you please check? Workspaces schema was recently updated, see #11995 and #12137

I have the latest version. this issue got automatically resolved when I restarted my mac.

**Comment by ewgenius** [comment]
@raycastbot close this issue
