### ISSUE TITLE
[GitHub] Ability to see all Comments / full Conversation of a pull request

### ISSUE THREAD

**Issue by DimiM99** [raycast/extensions#12170]
### Extension

https://www.raycast.com/raycast/github

### Description

when opening the pull request I can't see comments on the pull request, I can add one but not see all of them, which doesn't make much sense.

### Who will benefit from this feature?

-> short from everyone

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](https://raycast.com/community) if you need further help.

**Comment by DimiM99** [comment]
> Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](https://raycast.com/community) if you need further help.

I don't have any side-projects atm. so why not, I'll dm you in slack once I have access.

**Comment by jfkisafk** [comment]
Hey @DimiM99 are you working on this? I wanted to implement the same feature for both Issues and PRs, so I can help here instead of creating a new issue!

**Comment by DimiM99** [comment]
> Hey @DimiM99 are you working on this? I wanted to implement the same feature for both Issues and PRs, so I can help here instead of creating a new issue!

Hallo, yes I am, wanna team up? I'll dm you in slack.

**Comment by ramsaysewell** [comment]
Is this still being worked on?

**Comment by LitoMore** [comment]
Guys, feel free to start your work if you want to contribute. Don't let other people's comments discourage you from picking this work up.

**Comment by jfkisafk** [comment]
No I am not working on it at the moment, I wanted a common component to be shared between PRs and issues. So I am still willing to team up and contribute if someone wants to handle one of them.
