### ISSUE TITLE
[1Password] Can't get "Open in 1Password" secondary action to work

### ISSUE THREAD

**Issue by joshuahhh** [raycast/extensions#12177]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

I have "Open in 1Password" set as my secondary action, as seen here:

![Screenshot 2024-05-04 at 4 07 47 PM](https://github.com/raycast/extensions/assets/643799/9868673b-e467-4384-88e0-46aab18d8c3a)

However, I can't seem to find any way to trigger this secondary action. The actions menu doesn't show it:

![Screenshot 2024-05-04 at 4 08 08 PM](https://github.com/raycast/extensions/assets/643799/00e7cafe-b71c-4252-af9d-f8c0a36b2cb7)

Pressing Cmd-Enter just opens the website in the browser.

I expected Cmd-Enter to trigger "open in 1Password", or for it to be otherwise available somewhere on the Cmd-K menu.

Thanks!

### Steps To Reproduce

See above.

**Comment by Luk4h** [comment]
I can't reproduce it, What type of Item are you trying to use this action on? I was able to open in 1Password via the secondary action (⌘+↩) and on the action panel (⌘+K).

**Comment by joshuahhh** [comment]
Does that mean your ⌘+K menu has an item for "Open in 1Password"? That's
interesting! I will poke around a bit to see why mine doesn't.

**Comment by Luk4h** [comment]
@joshuahhh yes, you should always have "Open in 1Password" Action on the ⌘ + K menu. They are related to Item types, that is why I asked. Were you able to fix it?
