### ISSUE TITLE
[Jira] Failure to use the application at all

### ISSUE THREAD

**Issue by amitz-jfrog** [raycast/extensions#12178]
### Extension

https://www.raycast.com/raycast/jira

### Description

FetchError: request to https://jira.oauth.raycast.com/token failed, reason: unable to get local issuer certificate

    at withAccessToken(eV)
Ir:index.js:11:2490
    at ray-navigation-stack
Eo:index.js:11:2088

### Steps To Reproduce

install extension
try to do any action
go through a successful authentication
![image](https://github.com/raycast/extensions/assets/160742797/ef8a436a-73ee-4dce-b392-21f53309856a)

Open raycast, the Jira extension then shows "something went wrong screen"

**Comment by amitz-jfrog** [comment]
Yes, I am using the ZScaler VPN

**Comment by thomaslombart** [comment]
Do you still have the issue if you disable it?

**Comment by amitz-jfrog** [comment]
I do not know
It is constantly on, without the ability to disable it.
I will leave it for now, thank you for the response
