### ISSUE TITLE
[Apple Reminders] Could not find extension's manifest file. You might need to reinstall the extension.

### ISSUE THREAD

**Issue by SamEdwardes** [raycast/extensions#12211]
### Extension

https://www.raycast.com/raycast/apple-reminders

#### Error:
```
Could not find extension's manifest file. You might need to reinstall the extension.


```

### Steps To Reproduce

On Sunday, all of my extensions stopped working. All extensions now result in the same error:

```
Could not find extension's manifest file. You might need to reinstall the extension.
```

I am reporting this under "Apple Reminders", but it also happened for brew, vscode, etc. I think the underlying issue is likely the same.

The following steps were attempted but did not resolve the issue:

- Reload extension
- Clear extension cache

The issues is resolved by uninstalling and then reinstalling the extension.

**Comment by thomaslombart** [comment]
Are you still facing the issue?

**Comment by SamEdwardes** [comment]
I resolve the issue by doing the following:

> The issue is resolved by uninstalling and then reinstalling the extension.

Since then, it has not happened again.

**Comment by thomaslombart** [comment]
This may have been a temporary issue. I'm closing this issue to maintain a clean backlog then. Feel free to comment or reopen it it if you still have the problem.
