### ISSUE TITLE
Unable to Auth - Possibly due to Zscaler

### ISSUE THREAD

**Issue by jesse-chelin** [raycast/extensions#12218]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

Trying to auth anything returns the following errors:

JIRA:

FetchError: request to https://jira.oauth.raycast.com/token failed, reason: unable to get local issuer certificate

    at withAccessToken(ac)
Ir:index.js:11:2490
    at ray-navigation-stack
Eo:index.js:11:2088

FIGMA:

FetchError: request to https://oauth.raycast.com/v1/token/qTlHR2nhUt2e07Ynlbw-T4ALSoDPrGnUZU4z1VsH-scRq-We8cI9RfPKJb9UfEau0bCVYIc0qtW5fOVJ0rtUwDN6KSg5d8XgR_wRofMYARLRzAWhTb5mFsXTdFZl3GPQfA failed, reason: unable to get local issuer certificate

    at withAccessToken(A5)
Ir:index.js:11:2490
    at ray-navigation-stack
Eo:index.js:11:2088

SPOTIFY:

je: request to https://accounts.spotify.com/api/token failed, reason: unable to get local issuer certificate

ClientRequest.<anonymous>:index.js:108:10

---
105: 		};
106: 
107: 		request_.on('error', error => {
108: 			reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error));
109: 			finalize();
110: 		});
111: 
---

ClientRequest.emit:node:events:526:35
ClientRequest.emit:node:domain:488:12
TLSSocket.socketErrorListener:node:_http_client:495:9

### Steps To Reproduce

1. Try to auth anything
2. Get Something Went Wrong

### Current Behaviour

I get a something went wrong error

### Expected Behaviour

App is authenticated

**Comment by michaelwschultz** [comment]
@pernielsentikaer any idea what's going on here? Has this already been solved?
