### ISSUE TITLE
[CleanShot X] raycast commands not working

### ISSUE THREAD

**Issue by lucasmpramos** [raycast/extensions#12228]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

none of my cleanshotX commands are working from raycast

### Steps To Reproduce

1. try any command
2. they don't respond

### Current Behaviour

raycast commands for cleanshotX not working

### Expected Behaviour

raycast commands should work

**Comment by Aayush9029** [comment]
@lucasmpramos read the readme. If the issue still persists. lmk
