### ISSUE TITLE
[CanvasCast] An option to select a default browser to open Canvas links.

### ISSUE THREAD

**Issue by VietTran-UTS** [raycast/extensions#1222]
# Extension – [CanvasCast](https://github.com/raycast/extensions/tree/7658ff51f0b81ffffb5038f60995f24e459670ce/extensions/canvascast/)
Author: @YodaLightsabr

An option to select a default browser to open Canvas links. 

**Describe the feature and the current behavior/state.**

Canvas links will open in the default browser in the mac settings

**Who will benefit with this feature?**

Users who have more than one canvas account or wish to open Canvas in a different browser than their default

**Comment by YodaLightsabr** [comment]
Maybe I could add a Copy Link option? I'm not sure.

**Comment by YodaLightsabr** [comment]
Do you have any ideas for the implementation?

**Comment by VietTran-UTS** [comment]
I was thinking an option in the settings.  "Default browser" with a dropdown list of browsers to select from

**Comment by YodaLightsabr** [comment]
bump; I might still add it
