### ISSUE TITLE
[Session - Pomodoro Focus Timer] Resume Session

### ISSUE THREAD

**Issue by ariccb** [raycast/extensions#12229]
### Extension

https://www.raycast.com/jameslyons/session

### Description

There's a pause command, but no resume. There's only start previous session, which doesn't work the same

### Who will benefit from this feature?

anyone who pauses a session, then wonders how to resume the session via raycast without opening the application

**Comment by jamesjlyons** [comment]
Hello! The "Pause" command also resumes sessions. I have [a PR open](https://github.com/raycast/extensions/pull/13254) to make that clearer in the copy.
