### ISSUE TITLE
[speedtest] update interface to include streaming quality 

### ISSUE THREAD

**Issue by gndclouds** [raycast/extensions#12232]
### Extension

https://www.raycast.com/tonka3000/speedtest

### Description

Would be nice to add two more results which tell me what type of call or streaming quality I could expect. See example in UI below. 

![image](https://github.com/raycast/extensions/assets/1757261/9a71f177-af23-414e-9235-4fa4c8eb4139)

### Who will benefit from this feature?

I personally use speed tests a lot for checking internet quality at a cafe before a call, I think it could help people in similar situations. be sure of if there call will work.

### Anything else?

If this get implemented here is some basic data on recommended speeds.

# Call info:
**Voice Calls:** For standard voice calls, the required internet speed is relatively low. Most services like Skype, Zoom, or VoIP (Voice over Internet Protocol) systems require about 100 Kbps (Kilobits per second) for a smooth experience.

**Video Calls:** Video calls demand significantly higher speeds due to the additional data transmission for video. For a standard-quality video call, you might need between 300 Kbps to 1 Mbps (Megabits per second). For HD (High Definition) video calls, the requirement can increase to 1.5 Mbps to 3 Mbps. For group video calls or calls in higher resolutions like 1080p or 4K, the speed requirement can be substantially higher, possibly ranging from 3 Mbps to over 20 Mbps depending on the number of participants and the specific service.

# Streaming Info:
**Standard Definition (SD):** For streaming video in standard definition (about 480p), you would typically need about 1-3 Mbps.

**High Definition (HD):** HD quality streaming (720p or 1080p) typically requires between 5-8 Mbps for a smooth experience.

**Full HD and Higher:** For 1080p with high framerate (like sports or action movies), you might need about 10 Mbps.

**4K Ultra HD:** Streaming in 4K Ultra HD requires a lot more bandwidth, typically around 25 Mbps or more to stream content without buffering.

**Live Streaming:** If you're broadcasting live, the requirements can vary significantly based on the quality of the video. For example, streaming at 720p might require between 3-6 Mbps upload speed, while 1080p streaming might need 6-13 Mbps upload speed. For 4K streaming, this can go much higher, around 30-50 Mbps upload speed.

**Comment by aliaksandrZh** [comment]
[https://github.com/raycast/extensions/pull/12284](https://github.com/raycast/extensions/pull/12284)

**Comment by pernielsentikaer** [comment]
This is now merged into the extension 🔥
