### ISSUE TITLE
[Notion] Multi account support

### ISSUE THREAD

**Issue by leblaze** [raycast/extensions#12240]
### Extension

https://www.raycast.com/notion/notion

### Description

search multiple accounts at once

### Who will benefit from this feature?

everyone with multiple accounts

**Comment by thomaslombart** [comment]
Multi-account support is a commonly required feature that's tricky to implement right now, so I'm afraid it won't be possible to do that for the Notion extension. You can follow the status of this feature request here: [#269](https://github.com/raycast/extensions/issues/269).
