### ISSUE TITLE
[Extension Bug] Home Assistant extension can't connect to web-socket

### ISSUE THREAD

**Issue by AuHau** [raycast/extensions#1225]
# Extension – [Home Assistant](https://github.com/raycast/extensions/tree/main/extensions/homeassistant)

Author: @tonka3000

## Description

Extension can't connect to Home Assistant Websocket API.

I have tried manually connecting to the Websocket API using [Websocket Extension](https://chrome.google.com/webstore/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo/) and I have managed successfully connect to it where this extension seems not to.

I wanted to see logs of what is going on, but thanks to https://github.com/raycast/extensions/issues/1224 I did not manage.

Maybe it is incompatible with the latest Home Assistant version? I have noticed that you are not running the latest `home-assistant-js-websocket` package.

### Raycast version

Version: 1.31.0

#### Home Assistant info

version | core-2022.3.6
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.9.2
os_name | Linux
os_version | 5.4.182
arch | armv7l
timezone | Europe/Prague

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

**Comment by tonka3000** [comment]
Hey @AuHau ,

I have also the latest version of HA (2022.3.7) and it works for me.

Do you have a trailing whitespace in your url e.g. `https://myhainstance.org/`. If yes: Remove it (`https://myhainstance.org`) and try again.

If this does not work maybe you need to upgrade to 2022.3.7.

**Comment by AuHau** [comment]
Hmmm, nothing traling. 

I have no idea what has changed but today it works as expected 😅 Most probably it is then problem on my Home Assistant deployment, so closing this. Thanks for the ideas!

**Comment by tonka3000** [comment]
@AuHau Great to hear that it works now. Let me know if you miss something from home assistant in the exension.
