### ISSUE TITLE
Things 3 - Add support for beta version

### ISSUE THREAD

**Issue by ondrejfuhrer** [raycast/extensions#1227]
# Extension – [Things](https://github.com/raycast/extensions/tree/main/extensions/things)

Author: @loris

**Describe the feature and the current behavior/state.**
Would it be possible to also add support for beta version of this wonderful task manager? I understand that there might be some issues with beta versions, but I guess that's expected 🙂  would be great.

**Who will benefit from this feature?**
All Thingsᵝ users 🙂 
**Any Other info.**

**Comment by ondrejfuhrer** [comment]
@loris Of course happy to help here, here is the output:

```
> plutil -p /Applications/Things3Beta.app/Contents/Info.plist | grep BundleName
  "CFBundleName" => "Things3Beta"
```

```
> plutil -p /Applications/Things3Beta.app/Contents/Info.plist | grep CFBundleIdentifier
  "CFBundleIdentifier" => "com.culturedcode.ThingsMac.beta"
```

**Comment by ondrejfuhrer** [comment]
@loris any update on this? 🙂

**Comment by ondrejfuhrer** [comment]
If I can help in any way to push this through the finish line, let me know 🙂

**Comment by loris** [comment]
Hi @ondrejfuhrer Sorry for the delay, i've been waiting for weeks to get listed in the Things beta now, but they won't let me in :-) So I just did a PR (https://github.com/raycast/extensions/pull/2226) to add a preference dropdown to switch the identifier  (`com.culturedcode.ThingsMac.beta` vs `com.culturedcode.ThingsMac`) used in AppleScript calls.
Can you try it?

Thanks

**Comment by ondrejfuhrer** [comment]
Hey @loris , checked it now and it seems to work fine, thank you!
