### ISSUE TITLE
[color-picker] Getting "Something went wrong" error every time using the pick color extension

### ISSUE THREAD

**Issue by binaryblitz10** [raycast/extensions#12278]
### Extension

https://www.raycast.com/thomas/color-picker

### Description

Using the pick color tool works fine to detect and copt the color code, however, it shows a "Something went wrong" toast message behind the color code toast.

https://github.com/raycast/extensions/assets/169087053/a483d0dc-e193-40e5-a1f3-00afe278c7bc

### Steps To Reproduce

1. Open Raycast
2. Search for Pick Color / Use shortcut
3. Click to detect the color

**Comment by wenf0** [comment]
@raycastbot reopen this issue
