### ISSUE TITLE
[Google Translate] ...

### ISSUE THREAD

**Issue by TuralAsgar** [raycast/extensions#12287]
### Extension

https://www.raycast.com/gebeto/translate

### Description

Would be great if we could use the "pronounce" button to hear how it is pronounced.

### Who will benefit from this feature?

Everybody.

**Comment by gebeto** [comment]
yep, sounds good, we already have text-to-speech, so it should be pretty easy to add it for pronounce, will check it today

**Comment by TuralAsgar** [comment]
@gebeto Thank you for all the efforts you put into it.

Is there any update?
