### ISSUE TITLE
[Visual Studio Code - Project Manager]  - option to open in VS Code AND external Terminal

### ISSUE THREAD

**Issue by guid-ooo** [raycast/extensions#12281]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

Hi, I would like to be able to open a project in both vs code and my terminal by hitting enter on a project. 

### Who will benefit from this feature?

Me, and probably some other people that want as little keystrokes as possible. :)

**Comment by eduwass** [comment]
@guid-ooo I suppose you mean an external Terminal app outside VSCode? Maybe you could create a task that runs on folderOpen and opens a Terminal?


https://stackoverflow.com/questions/51049955/start-app-when-opening-project-in-vs-code
