### ISSUE TITLE
[Notion] Add Text To a New Page

### ISSUE THREAD

**Issue by jewenso** [raycast/extensions#12295]
### Extension

https://www.raycast.com/notion/notion

### Description

In the Add Text to Page command, could you please add a feature to create a new page onto which to add that text directly from the panel? (Not just choosing from existing pages) Possibly where you can also choose in which page to create the page? Not just in databases?

Thank you

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](https://raycast.com/community) if you need further help.
