### ISSUE TITLE
[Folder Search] ...

### ISSUE THREAD

**Issue by Pixel-Panda** [raycast/extensions#12291]
### Extension

https://www.raycast.com/GastroGeek/folder-search

### Description

Doesnt search anything.

### Steps To Reproduce

Search for a folder, its self explanatory.

### Current Behaviour

Nothing

### Expected Behaviour

A folder

**Comment by omarshahine** [comment]
I would suggest rebuilding your spotlight index and rebooting.

There have been no code changes to this extension in a long while that could point to a regression. 

Also try changing scopes to see if that kicks the index to start working.

**Comment by Pixel-Panda** [comment]
@omarshahine okay I’m totally lost on that then! No wonder. I got Raycast specifically to disable Spotlight, which was actually their very early messaging in marketing. And works as mentioned perfectly. 

Spotlight kills my system, even on a 132GbDDR4 i9 iMac 5k. 

Turning that on to search folders for (almost) something Raycast does already is a hard swallow. 

But you’re pushing this stuff free and def not complaining so I’ll leave with saying I’d love if it worked the same way ‘Search Man Pages’ plugin works. 
1. To start, instant query time. Caches beautifully.
2. No spotlight mdutil needed at all.

May be worth a peek. 

Cheers
