### ISSUE TITLE
[Timezone Converter] Add UTC time convention option

### ISSUE THREAD

**Issue by koalazub** [raycast/extensions#12297]
### Extension

https://www.raycast.com/joao.mainka/raycast-timezone-converter

### Description

Provides GMT only

### Who will benefit from this feature?

Everyone

**Comment by ahmed2m** [comment]
What do you mean by that? how should this be "added"? the extension says "GMT+3" for example, just serves **exactly the same purpose** as "UTC+3".

> Greenwich Mean Time (GMT) is often interchanged with UTC.
> 
> Although GMT and UTC share the same current time in practice, there is a basic difference between the two:
> 
> [GMT is a time zone](https://www.timeanddate.com/time/zones/gmt) officially used in some European and African countries. The time can be displayed using both the 24-hour format (0 - 24) or the 12-hour format (1 - 12 am/pm).
> [UTC is not a time zone](https://www.timeanddate.com/time/aboututc.html), but a time standard that is the basis for civil time and time zones worldwide. This means that no country or territory officially uses UTC as a local time.
> 

Source: https://www.timeanddate.com/time/gmt-utc-time.html
