### ISSUE TITLE
[Git Repos] If Open With shortcut is a browser, use URL rather than path

### ISSUE THREAD

**Issue by bstncartwright** [raycast/extensions#1231]
# Extension – [Git Repos](https://github.com/raycast/extensions/tree/main/extensions/git-repos)

Author: @moored

## Description

I love how Git Repos allows me to open repositories easy in my terminal or editor, however it doesn't work when opening in Safari. I set Safari as my default shortcut: 
![Raycast-KhJjVUZQ](https://user-images.githubusercontent.com/2187109/160430029-28c2989b-c4fb-46d6-a31a-d1be8480024f.png)

When I use this, Safari opens with a new tab followed by Finder opening to the path of the repository.

I'd love that if it is a browser to use the remote URL rather than the full path. I did see that there is a workaround here (https://github.com/raycast/extensions/blob/main/extensions/git-repos/src/list.tsx#L128) but I would prefer to use the normal shortcut rather than a second one. 😄 

## Steps To Reproduce

1. Set Safari as an open with shortcut.
2. Attempt to use that shortcut for a GitHub repo.

## The current behavior

Safari opens with a new blank tab followed by Finder opening in the repository's directory.

## The expected behavior

Safari opens with the remote URL, the same as the [`Action.OpenInBrowser`](https://github.com/raycast/extensions/blob/main/extensions/git-repos/src/list.tsx#L148).

### Raycast version

Version: 1.31.0

**Comment by moored** [comment]
This extension was designed to work primarily with your local repos, so the Open with apps use the local path to the repos. If the repo has an origin defined, you can use ⇧⌘O to browse directly to the remote repo. You can use ⇧⌘U to go directly to the remote repo if it also has an upstream defined.

**Comment by bstncartwright** [comment]
@moored thanks so much for your reply!

In that case is it possible to have an option to OpenInBrowser as the shortcuts rather than those key binds you described? Or if we could change those key binds? I'd love to use a key bind to open the search of Git Repos using the extension hotkey, search the repo, press enter and then have it open in my browser. However if that is not possible or not as part of the design no worries and I can close this 😃

**Comment by bstncartwright** [comment]
Yes exactly, when I press return (default action) and my default is Safari, then it opens Finder in the directory of the repository, rather than open the remote URL in Safari.

**Comment by moored** [comment]
Got it. I will take a look and see what I can come up with and run it by you.

**Comment by bstncartwright** [comment]
That sounds great! Thanks so much for looking into this so quickly.
