### ISSUE TITLE
Hide Files extension broken...

### ISSUE THREAD

**Issue by Pixel-Panda** [raycast/extensions#12315]
### Description

totally dead extension: https://github.com/raycast/extensions/blob/d4d5371cf6e4ea3dc4c3da7c239470445919926e/extensions/hide-files/

### Steps To Reproduce

try to issuee it.does nothing,

### Current Behaviour

dust mites

### Expected Behaviour

work

**Comment by koinzhang** [comment]
Hi @Pixel-Panda. The extension works fine on my device, what problem are you experiencing? Any screenshot of the error and path to reproduce it?
