### ISSUE TITLE
[Text Replacements]...

### ISSUE THREAD

**Issue by vcbrewers** [raycast/extensions#12326]
### Extension

https://raycast.com/raycast/text-replacements

#### Error:
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at j9 (/Users/home/.config/raycast/extensions/5ca69272-fa01-43f2-912e-f6902c8b498b/import-text-replacements-to-snippets.js:32:4208)
    at async Object.U0 (/Users/home/.config/raycast/extensions/5ca69272-fa01-43f2-912e-f6902c8b498b/import-text-replacements-to-snippets.js:32:4322)
```

### Steps To Reproduce

1. Installed Extension from Raycast Store
2. Hit Enter to import macOS's text replacement
3. Received error notification w/in Raycast

**Comment by thomaslombart** [comment]
This error is likely coming from [this line](https://github.com/raycast/extensions/blob/d8a0c8518a097d1ea2a39d00145f275f627b5243/extensions/text-replacements/src/import-text-replacements-to-snippets.tsx#L24). Are there any special characters used in your text replacements? 

It would be super useful if you could fork the extension, add a `console.log` just before the [`JSON.parse` line](https://github.com/raycast/extensions/blob/d8a0c8518a097d1ea2a39d00145f275f627b5243/extensions/text-replacements/src/import-text-replacements-to-snippets.tsx#L24) and paste the result over here.
