### ISSUE TITLE
[Timers] ...menu bar option to deactivate delay

### ISSUE THREAD

**Issue by LK2408** [raycast/extensions#12323]
### Extension

https://www.raycast.com/ThatNerd/timers

### Description

It would be really great if the timer in the menu bar would not have a delay. This would really increase my productivity because actively seeing the timer slowly ticking down puts pressure on me

**Comment by ThatNerdSquared** [comment]
Hi @LK2408, thanks for using Timers!

Unfortunately, there's not much I can do about the delay in refreshing the menu bar command. The [minimum refresh interval allowed by the Raycast API is 10 seconds](https://developers.raycast.com/information/lifecycle/background-refresh#manifest). I realize this isn't ideal, but from an extension developer perspective there's not much i can do about it.

If you'd like a quicker refresh interval I would suggest putting a suggestion in the [Raycast Slack](https://raycastcommunity.slack.com/) about it - if the Raycast team changes their API to allow a shorter refresh interval I will update Timers accordingly.

**Comment by ThatNerdSquared** [comment]
@raycastbot close this issue
