### ISSUE TITLE
[Git Repos] Exclude Directories from searching

### ISSUE THREAD

**Issue by BrendanThompson** [raycast/extensions#12330]
### Extension

https://www.raycast.com/moored/git-repos

### Description

When searching for repositories it would be good to be able to exclude a directory from being search. As an example in my Development directory I have an Archive directory that contains old projects that I want to be able to reference but don't need to be able to open etc.

### Who will benefit from this feature?

Anyone who has an archive of older projects

**Comment by nitishpdmn** [comment]
Can the behavior you want be achieved by simply setting the "max scan depth" to a smaller number?

**Comment by BrendanThompson** [comment]
Unfortunately that wouldn't work. Doing so would render the extension useless. Archive sits at the root of Development.

**Comment by nitishpdmn** [comment]
Ok, since we're just using `find` on the backend, seems like it would be pretty straightforward to make this happen. Just going to leave this here for when I/someone gets around to it: https://stackoverflow.com/a/4210072
