### ISSUE TITLE
[Brew]...

### ISSUE THREAD

**Issue by kalebty** [raycast/extensions#12333]
### Extension

https://raycast.com/nhojb/brew

#### Error:
```
Error: Command failed: /usr/local/bin/brew info --json=v2 --installed
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 992: /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby: Bad CPU type in executable
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 992: /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby: Undefined error: 0

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at Pipe.<anonymous> (node:net:337:12)
```

### Steps To Reproduce

Command + Space
Type "Search Brew"
Type "alt-tab"
Enter, Enter
The I receive an error.

### Current Behaviour

Not really sure what's going on here. I just got a new M3 MacBook Air, was walking through a set up guide I found from Syntax.fm. 
At the point I installed Brew from the store and go to Brew search then try to install anything I get the error above. This also applies to Brew Upgrade and Brew Show Installed.

### Expected Behaviour

Search Brew would install alt-tab (or any other brew application)

**Comment by MillerApps** [comment]
Have you installed homebrew? 

You can run `brew -v` in your terminal to see what version of homebrew is installed. Or `which brew` to see the installation path. 


You can find the installation instructions [here](https://brew.sh/)

**Comment by kalebty** [comment]
@MillerApps I do have Brew installed `brew -v` returns 4.2.21 and which `brew returns` /opt/homebrew/bin/brew

I did make sure to install and set up brew before trying to use it with RayCast. But I'm not positive why it isn't working properly.

**Comment by MillerApps** [comment]
Looking at the output you provided again, it seems that the issue might be related to the Ruby version being used with Homebrew. Here are the steps to diagnose and resolve the issue:

1.	Verify Ruby Installation:
	▪	Check if you have Ruby installed by running:
`ruby -v`

2.	Ensure Ruby is Correctly Added to Your PATH:
	▪	Add Ruby to your PATH if it's not already included. You can do this by adding the following line to your shell configuration file (e.g., ﻿.bashrc, ﻿.zshrc):
`export PATH="/usr/local/opt/ruby/bin:$PATH"  # Adjust path if necessary`
	▪	Reload the shell configuration:
source ~/.bashrc  # or source ~/.zshrc

3.	Reinstall Homebrew's Portable Ruby (Optional):
	▪	Sometimes, reinstalling Homebrew's portable Ruby can resolve architecture compatibility issues:
`brew vendor-install ruby`

4.	Check Homebrew's Health:
	▪	Run the following command to check for any issues:
`brew doctor`

**Comment by kalebty** [comment]
I followed those instruction and am still unable to install anything with brew through RayCast. 
Here is my shell output if this is helpful.

ksoutherland@MacBook-Air ~ % ruby -v                  
ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]
ksoutherland@MacBook-Air ~ % echo $PATH               
/opt/homebrew/opt/ruby/bin:/Users/ksoutherland/.rubies/ruby-3.1.3/bin:/Users/ksoutherland/.gem///bin:/Users/ksoutherland/.rubies/ruby-3.1.3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin
ksoutherland@MacBook-Air ~ % brew vendor-install ruby 
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:d783cbeb6e6ef0d71c0b442317b54554370decd6fac66bf2d4938c07a63f67be
Already downloaded: /Users/ksoutherland/Library/Caches/Homebrew/portable-ruby-3.1.4.arm64_big_sur.bottle.tar.gz
==> Pouring portable-ruby-3.1.4.arm64_big_sur.bottle.tar.gz
ksoutherland@MacBook-Air ~ % brew doctor 
Your system is ready to brew.

**Comment by MillerApps** [comment]
I got nothing, I wasn't able to reproduce the problem on my machine. Sorry about that. Maybe @nhojb would be more help.

**Comment by nhojb** [comment]
`/usr/local/bin/brew info --json=v2 --installed`

@kalebty I'm guessing you have the x86-64 version of brew installed - which might explain the "Bad CPU type in executable" you are seeing in the ruby error output.

On ARM64 brew should is installed in `/opt/homebrew/bin/brew`. 

I would suggest completely uninstalling brew from your Mac, then re-install using the script provided at https://brew.sh/
