### ISSUE TITLE
[Alt-Text Generator] None of the methods product alt-text

### ISSUE THREAD

**Issue by jmabeebiz** [raycast/extensions#12346]
### Extension

https://www.raycast.com/jack_casica/alt-text-generator

### Raycast Version

1.73.3

### macOS Version

14.4.1

### Description

I just installed this today as this would be game changing for me and my website clients. Constantly having to write alt-text. But even after topping off my API account with OpenAI, I haven't been able to get any alt-text to come out. It just fails with each type. Tried multiple images as well, including unsplash ones from the example.

### Steps To Reproduce

Copy an image, put an image in the finder, or copy the URL.
Run extension.

### Current Behaviour

Fails every time.

### Expected Behaviour

Get image alt-text.

**Comment by JackCasica** [comment]
Hi @jmabeebiz ~ Thanks for helping me to make this extension better 😸. I'll publish the update today. 

I did find an issue with the `From URL` command, but I wasn't able to recreate any failures with the `From Selection` or `From URL` commands.

If you're still running into problems with any of the commands, I've also updated the Toast messages so they should provide more helpful error messages for debugging this further.

@raycastbot assign me

**Comment by jmabeebiz** [comment]
Thanks man! I just tried it again, and From Selection and From Finder are working now. URL is still broken. Fantastic extension!

Thanks,
// Justin Mabee
*Squarespace Designer | Available for Hire*
justinmabee.com ( http://justinmabee.com )
(267) 632-4103

Sent via Superhuman ( ***@***.*** )

**Comment by JackCasica** [comment]
I'll close this issue now as I've been using the commands without bugs for a few weeks now ~ Feel free to reopen this issue if you are still having these bugs. 

Cheers!

@raycastbot close this issue
