### ISSUE TITLE
[1Password] Doesn't show password data

### ISSUE THREAD

**Issue by laudaksg** [raycast/extensions#12340]
### Extension

https://www.raycast.com/khasbilegt/1password

### Raycast Version

1.73.3

### macOS Version

14.4.1 (23E224)

### Description

I have 1Password 8 installed and working on my mac, but Raycast doesn’t show the data.

https://github.com/raycast/extensions/assets/590064/8db7e039-f4cc-4c4a-9bf9-ad04698e9f33

### Steps To Reproduce

searching for passwords in raycast doesn't work.

**Comment by Luk4h** [comment]
Please, ensure that you have your 1Password CLI installed, and then Check if the path is set correctly on the extension preferences.

This issue has been fixed and waiting for merge on PR #12156. My Apoligies

**Comment by Luk4h** [comment]
PR has been merged.

@raycastbot close this issue
