### ISSUE TITLE
[Browser Bookmarks] doesn't find any Arc bookmarks

### ISSUE THREAD

**Issue by rvnash** [raycast/extensions#12344]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Raycast Version

1.73.3

### macOS Version

14.4.1

### Description

![CleanShot 2024-05-14 at 11 04 14](https://github.com/raycast/extensions/assets/182201/8a75b7e0-ddde-45fb-8085-cc6aef8ac446)

The extension says I don't have any bookmarks, but I have lots of bookmarks.

I have only Arc selected to search.

![CleanShot 2024-05-14 at 11 05 05](https://github.com/raycast/extensions/assets/182201/9557eb2d-3ede-499e-9e87-9770746c1b2c)

### Steps To Reproduce

1. Make Arc your primary browser
2. Set the extension to search bookmarks in Arc
3. It won't find any.

**Comment by thomaslombart** [comment]
@mskelton I remembered you added support for Arc bookmarks a while ago. Would you mind taking a look at this? 🙂

**Comment by mskelton** [comment]
@thomaslombart It's working fine for me with Arc, so not sure I know what's going on here.
