### ISSUE TITLE
[Quick Notes] Many Feature Requests

### ISSUE THREAD

**Issue by Ernest0-Production** [raycast/extensions#12354]
### Extension

https://www.raycast.com/biknandy/quick-notes

### Description

I want request:
- Display note title in Detail panel. Its useful when title is multiline text
- Display all note tags in Details panel.
- Display create and modify date in Details panel.
- Save all tags in directory with notes markdowns
- Tags Editor view for renaming 
- Sort DropDown in search bar, not only from Extension Settings
- Edit not from cmd+enter instead just Enter. 
- Switch to show/hide detail panel 
- Show all tags Subtitle when detail panel hidden

### Who will benefit from this feature?

Everyone

### Anything else?

I can do some of the tasks if you don't have time

**Comment by biknandy** [comment]
Thanks for submitting. I am working on adding a Details pane with the tags and can add a title/date as well.

For tag saving, I had that previously before introducing 2-way sync so not going to re-introduce as it complicates that. You can find the tags from your saved JSON for the extension.

I like the sort function from the main screen idea, will do in an action.

And then Edit should already be just Enter, that's set automatically.

Will do a tag editor interface soon, right now you can technically delete one and then add one but will improve that interface (will do this last).

**Comment by biknandy** [comment]
@raycastbot assign me

**Comment by Ernest0-Production** [comment]
Hi! Thank you very much for the detailed answer. 

As far as I know, you can change the hotline for the main action. The reason why just enter does not seem appropriate is that in the edit screen, confirmation of changes is done via cmd + enter.

**Comment by biknandy** [comment]
Update, some of these features will be released early next week.

**Comment by biknandy** [comment]
@Ernest0-Production Can you create a separate issue and assign to me for the tag manager edit improvements (unsure how to best do this)? Got a PR up for most everything else - Thanks!

**Comment by Ernest0-Production** [comment]
> @Ernest0-Production Can you create a separate issue and assign to me for the tag manager edit improvements (unsure how to best do this)? Got a PR up for most everything else - Thanks!

Done) https://github.com/raycast/extensions/issues/12556

**Comment by Ernest0-Production** [comment]
@biknandy Still missing the ability to hide Detail View :(

Note titles can be long, and sometimes it's quicker to navigate through the list when you see a slightly longer title line.

Can you please add a hotkey to hide this panel?

------


In the action panel for sorting, some icons are missing for some reason (is this a bug?)
There is also a “+New” button, which opens a view for creating a new tag (looks unexpected)

**Comment by biknandy** [comment]
@Ernest0-Production Good catch on the +Create I had copied that from the tag one. For the sort icon, it shows the currently selected sort. I'll also add the detail view hide later
