### ISSUE TITLE
[Shell] Settings to run command inside iTerm app not working

### ISSUE THREAD

**Issue by NBaLogn** [raycast/extensions#12350]
### Extension

https://www.raycast.com/asubbotin/shell

### Raycast Version

1.73.3

### macOS Version

14.4.1 (23E224)

### Description

As stated in title, the extension works fine to run commands inside Raycast, and it's running commands in the Terminal app too, but not in the iTerm app

### Steps To Reproduce

1. Fresh install of Shell extension
2. Checked the box to use Terminal/iTerm
3. Decided on iTerm as the Terminal application to use
4. Run simple commands in Raycast: shell [ls]

### Current Behaviour

Popup shows "Ran command in iTerm", but nothing happens

### Expected Behaviour

Popup shows "Ran command in iTerm", shows the iTerm window, runs command inside the open iTerm tab.

**Comment by kevinm6** [comment]
Hi @NBaLogn , I'll send a fix tomorrow.
After they'll merge it, I'll remind you here to test it.

**Comment by kevinm6** [comment]
@NBaLogn the fix should be available!
Be sure to update the extensions from Raycast and test it.
If it’s working, please close this issue

**Comment by NBaLogn** [comment]
It's fixed nicely. Thanks.
