### ISSUE TITLE
[Apple Notes] Error when trying to search notes

### ISSUE THREAD

**Issue by gewoonseba** [raycast/extensions#12369]
### Extension

https://www.raycast.com/raycast/apple-notes

### Raycast Version

1.74.0

### macOS Version

14.4.1 (23E224)

#### Error:
```
TypeError: Cannot read properties of null (reading 'includes')

c8:index.tsx:13:54

---
10: }
```

### Steps To Reproduce

1. Open raycast
2. Invoke "Search notes" (through ⌥+N shortcut)

### Current Behaviour

![CleanShot 2024-05-15 at 17 30 03](https://github.com/raycast/extensions/assets/7049958/1cb19d84-4b37-43e9-b927-85fb03730340)

### Expected Behaviour

Search notes

**Comment by thomaslombart** [comment]
I just pushed a fix for that. Could you run `Check For Extensions Update` and let me know if you still have the issue?

**Comment by gewoonseba** [comment]
Did so, but Raycast tell’s me I’m up to date. Still having the issue

**Comment by thomaslombart** [comment]
It should be good to go now. Something was wrong with the update.

**Comment by gewoonseba** [comment]
@thomaslombart still not working for me unfortunately. Just tried checking for updates, but still giving me the message everything's up-to-date and the search notes not working

**Comment by thomaslombart** [comment]
[The fix has been published though.](https://github.com/raycast/extensions/actions/runs/9098794468/job/25009831028) I'm not sure what's happening here 🤔

**Comment by thomaslombart** [comment]
Maybe uninstall it and reinstall it?

**Comment by gewoonseba** [comment]
Still no luck after uninstalling it and reinstalling.

```
TypeError: Cannot read properties of null (reading 'slice')

d2:NoteListItem.tsx:18:39

---
15:   isDeleted?: boolean;
16: };
17: 
18: export default function NoteListItem({ note, noteTitles, isDeleted, mutate }: NoteListItemProps) {
19:   const accessories = [];
20: 
21:   if (preferences.tags && note.tags.length > 0) {
---

    at ray-list-section
Ma:index.js:20:20287
Lr:index.js:11:6632
```

**Comment by thomaslombart** [comment]
Oh but that's a different error now. You don't have the `includes` error, but something related to `slice`. I'll take a look at it.

**Comment by thomaslombart** [comment]
All right, I just [shipped another fix](https://github.com/raycast/extensions/commit/23389680eda357f822c45a6ebad0df1f7969d869). Could you run `Check for Extension Updates` and try again? If it's not working, let's uninstall it and reinstall it again. If it still doesn't work, I'll provide you with a guide to debug this thing 🙂

**Comment by gewoonseba** [comment]
Works now after updating! Thanks 🎉
