### ISSUE TITLE
[bazinga-tools] Deprecate/delete the extention

### ISSUE THREAD

**Issue by aaabramov** [raycast/extensions#12376]
### Extension

https://www.raycast.com/luin/bazinga-tools

### Raycast Version

1.74.0

### macOS Version

14.3.1 (23D60)

### Description

Seems that the domain name that this extension uses (bazinga.tools) is not available anymore:
<img width="968" alt="image" src="https://github.com/raycast/extensions/assets/11317222/64917c36-f125-4eed-83d2-db373b5a57b7">

### Steps To Reproduce

I just was browsing and checking the source code and found this.

**Comment by luin** [comment]
Yeah sorry I forgot it here. Bazinga tools is not maintained anymore so should be removed.
