### ISSUE TITLE
[Google Chrome] Cannot search code-server tabs

### ISSUE THREAD

**Issue by zhuxinqimac** [raycast/extensions#12375]
### Extension

https://www.raycast.com/Codely/google-chrome

### Raycast Version

1.74.0

### macOS Version

14.1

#### Error:
```
Error: Issue with tab: 'Get Started — custom_tools — code-server~~~https://arnold-proxy-i18n.tiktok-row.org/p46cdf2b620da86aa4c8a39a5447298a9/?folder=/mnt/bn/tns-xinqi-arnold/repos/custom_tools~~~~~~1155867824~~~1'
Command failed with exit code 1: osascript -e 
    tell application "Google Chrome"
      activate
      set _wnd to first window where id is 1155867824
      set index of _wnd to 1
      set active tab index of _wnd to 1
    end tell
    return true
  
113:135: execution error: Google Chrome got an error: AppleEvent handler failed. (-10000)

Command failed with exit code 1: osascript -e 
    tell application "Google Chrome"
      activate
      set _wnd to first window where id is 1155867824

```

Install a vscode web code-server.
Using raycast to search code-server will trigger error.

### Steps To Reproduce

Open a vscode code server in chrome browser and install it as a standalone window (tab).
Using raycast to search for the code-server tab will trigger error.

### Current Behaviour

Using raycast to search code-server will trigger error.

### Expected Behaviour

Should be able to search code-server tabs as the web code-server is also a web tab.

**Comment by a-laughlin** [comment]
I lack experience with vscode code servers and installing them as tabs. Given that vscode is a code editor, you might be the best person to fix this @zhuxinqimac
