### ISSUE TITLE
[Gitmoji Search] Add option to paste emoji name like `:tada:`

### ISSUE THREAD

**Issue by garymazzeo** [raycast/extensions#1237]
# Extension – [Gitmoji Search](https://github.com/raycast/extensions/tree/192eb82fcccd2c7465f53c595b92ee2941aad2d3/extensions/gitmoji/)
Author: @ricoberger

Add option to paste name like `:tada:` instead of only pasting the emoji itself.

**Describe the feature and the current behavior/state.**
Current state: only option is to paste emoji character or copy emoji character to clipboard

**Who will benefit with this feature?**
Any who uses applications that don't support emoji natively. (Sourcetree is what I use.)

**Any Other info.**
Thank you so much for making this extension! It saves me time finding the gitmoji I need!

**Comment by ricoberger** [comment]
Hi @garymazzeo, in the preferences of the Gitmoji extension you can select if you want to paste/copy the gitmoji character or if you want to paste/copy the code of the gitmoji.

Does this already help or do you want another action where you can also paste/copy the code when the emoji option is selected in the preferences?

**Comment by garymazzeo** [comment]
Ahhhh, thanks @ricoberger! Yes, that's super helpful, and I think for me, that's perfect. I had thought there could be the option for either with cmd+K (with preference to switch the default). But I think for "gitmoji" use, only one is fine. The places that accept the character would also accept the `:code:` (my experience is mostly with github and gitlab). Thanks for the speedy reply, and thanks again for the extension!
