### ISSUE TITLE
[ChatGPT] Add voice selector for TTS

### ISSUE THREAD

**Issue by castletaste** [raycast/extensions#12389]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Currently, the system faces an issue where it cannot pronounce Cyrillic characters. This limitation affects users who communicate in languages that use the Cyrillic alphabet, causing an inconvenience and hindering effective communication.

### Who will benefit from this feature?

Implement a feature that allows users to choose a voice for text-to-speech responses in ChatGPT, including support for pronouncing Cyrillic characters accurately. This enhancement would greatly benefit users who rely on Cyrillic script, improving the overall usability and accessibility of the text-to-speech functionality

**Comment by bxb100** [comment]
hi, this project using https://www.npmjs.com/package/say depends on the Mac system command `say`

**Comment by bxb100** [comment]
Perhaps someone can add TTS to this extension in the future, but not today

@raycastbot close this issue
