### ISSUE TITLE
Can I display my existing workspace in Raycast?

### ISSUE THREAD

**Issue by owenjuni** [raycast/extensions#12381]
### Extension

https://www.raycast.com/limonkufu/aerospace

### Description

Can I display my existing workspace in Raycast?
I created a Raycast script that can quickly create a workspace, but I need a more portable way to switch workspaces.

### Who will benefit from this feature?

Here is the script

```
#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Aerospace 
# @raycast.mode compact
# @raycast.argument1 { "type": "text", "placeholder": "Workspace Name" }

# Optional parameters:
# @raycast.icon 🎬

echo "Running the aerospace CLI command..."
# aerospace workspace "$1"
aerospace move-node-to-workspace "$1"
```

**Comment by limonkufu** [comment]
@raycastbot assign me

Hi @owenjuni , it's not clear to me what you are asking. Could you elaborate a little bit further?

The extension (currently) only supports executing the keyboard shortcuts so in your case if you have a keyboard shortcut (binding) in your config to do what you like (i.e. `aerospace move-node-to-workspace`), when you click on this shortcut from menubar or list item in the extension, it will run it. I don't have a specific command for shortcuts.
