### ISSUE TITLE
[Tailwind CSS] Open docs inside of raycast instead of the browser

### ISSUE THREAD

**Issue by tom-sherman** [raycast/extensions#12393]
### Extension

https://www.raycast.com/vimtor/tailwindcss

### Description

As the title, I'd like to see a quick look at the docs inside of raycast instead of being pushed out to the browser.

### Who will benefit from this feature?

People who work in other programs eg. code editors and dont want to lose their context.

### Anything else?

The MDN extension works this way and it's great!

**Comment by vimtor** [comment]
Hey @tom-sherman!

Thanks for the suggestion, but I'm afraid this is not possible since their docs use MDX, and Raycast does not support this.

I'll close the issue and implement it if at some point adding support is easier. @raycastbot close this issue
