### ISSUE TITLE
[Simple Reminder] Reminder name length too long makes menu bar icon disappear

### ISSUE THREAD

**Issue by miguel-felix1** [raycast/extensions#12401]
### Extension

https://www.raycast.com/comoser/simple-reminder

### Raycast Version

1.73.3

### macOS Version

Sonoma 14.2.1

### Description

The menu bar is not being cut off if the topic length is too long, if the monitor screen size is smaller than retina, it's possible to crash the extensions resulting in no menu bar icon appearing at all, with an ellipsis cut off at 30 character, this issue should be fixed.

### Steps To Reproduce

1. Add a reminder with the menu bar icon active
2. Give the reminder an extra long name

### Current Behaviour

If topic name too long, no menu bar icon shows up

### Expected Behaviour

If topic name too long, it should be truncated with ellipsis at the end

**Comment by comoser** [comment]
@raycastbot assign @miguel-felix1

**Comment by miguel-felix1** [comment]
@raycastbot assign me
