### ISSUE TITLE
[ChatGPT] Cannot read properties of undefined...

### ISSUE THREAD

**Issue by PrimeMHD** [raycast/extensions#12414]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Raycast Version

1.74.0

### macOS Version

14.1.1

### Description

I use my own endpoint. It was working fine, but then it started throwing errors one day.
![image](https://github.com/raycast/extensions/assets/28723105/30a9b298-f31b-4b26-a940-9db04f294efb)
show error message:
```
cannot read properties of undefined (reading '0')
```
ps: it's not the fault of endpoint because other tools work fine with it.

### Steps To Reproduce

config: 
![image](https://github.com/raycast/extensions/assets/28723105/3786e8be-c3ad-450f-b3e5-890330513adf)
![image](https://github.com/raycast/extensions/assets/28723105/6e9309ca-ace3-49e3-b92d-299ae21a2efd)
![image](https://github.com/raycast/extensions/assets/28723105/d805e6d1-cf96-4841-b1e4-d0da4ba4ff14)

**Comment by bxb100** [comment]
Hi, I need the HTTP respond payload to figure out the reason, so could you share me this info through email?
