### ISSUE TITLE
[YouTube Downloader] "output format mp4 not available"

### ISSUE THREAD

**Issue by kudzuweb** [raycast/extensions#12412]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

1.69.2

### macOS Version

14.3

### Description

I installed ffmpeg with brew and checked the filepath with "which ffmpeg", then copied that filepath into the extension, same with probe. Am able to launch ffmpeg from the terminal, but when I try to use the raycast extension, it downloads to 100%, then says "Encoding failed: Output mp4 not available"

How do I fix this?

### Steps To Reproduce

Software versions above, base environment
Launch Raycast
Open YouTube downloader
paste in youtube URL
run
then the error appears

### Current Behaviour

Encoding failed

### Expected Behaviour

Download in specified folder

**Comment by kudzuweb** [comment]
Found the issue here, implemented the "temporary fix" of unlinking and then linking ffmpeg. Now instead of saying the format is not available, it just finishes, but no download in the folder.

**Comment by vimtor** [comment]
This was solved in https://github.com/raycast/extensions/pull/12583

@raycastbot close this issue
