### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by jasonsantony** [raycast/extensions#12424]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

1.74.0

### macOS Version

14.5

#### Error:
```
Error: Output format webm is not available

capabilities.js:589:20

---
586:           }, [])

### Steps To Reproduce

try to download any video

### Current Behaviour

errors

### Expected Behaviour

download the video

**Comment by lumap** [comment]
mp4 also doesn't work.

**Comment by vimtor** [comment]
Hi @jasonsantony and @lumap!

Sadly, this is a known issue. The problem is related to the new `ffmpeg` version and the library we are using to process the videos.

Check out the temporary solution here: https://github.com/raycast/extensions/issues/12110#issuecomment-2089490625
