### ISSUE TITLE
[YAFW] ffprobe failed to find a path to the file if the filename contains space

### ISSUE THREAD

**Issue by tonypinkevych** [raycast/extensions#12439]
### Extension

https://www.raycast.com/pablopunk/yafw

### Raycast Version

1.74.1

### macOS Version

Sonoma 14.1.1

### Description

If name contains space then any command failed to be executed. Probably because of ffprobe cannot find a file by provided path.

Could be related to this PR https://github.com/raycast/extensions/pull/12205.

https://github.com/raycast/extensions/assets/13913581/7838b6dd-2f67-499a-95d0-6f4abe3d7158

### Steps To Reproduce

1. rename any video to contains spaces;
2. try to run any fast command (`optimize`, `stabilize`, `convert to` or `resize`).

### Current Behaviour

It fails with an error.

### Expected Behaviour

It works.

**Comment by mlz11** [comment]
@raycastbot assign me
