### ISSUE TITLE
[YAFW] broken filename counter for fast commands

### ISSUE THREAD

**Issue by tonypinkevych** [raycast/extensions#12440]
### Extension

https://www.raycast.com/pablopunk/yafw

### Raycast Version

1.74.1

### macOS Version

Sonoma 14.1.1

### Description

After encoding the same file multiple times, the counter gets stuck on a constant number, such as `...1.mp4`.

https://github.com/raycast/extensions/assets/13913581/47adae19-5637-40ef-bead-935d47a21615

### Steps To Reproduce

1. encode any file multiple times with the same command;
2. for example `optimize`, `optimize`, `optimize`.

### Current Behaviour

If we have file named `hello.mp4`.
It creates 1 file named `hello\ 1.mp4`.

### Expected Behaviour

It should create multiple files
`hello 1.mp4`
`hello 2.mp4`
`hello 3.mp4`

or 

`hello (1).mp4`
`hello (2).mp4`
`hello (3).mp4`

to be consisted with macos file names.

**Comment by mlz11** [comment]
@raycastbot assign me

**Comment by mlz11** [comment]
Hey @tonypinkevych 👋🏻
I'm working on it, but chances are it's going to take me some time as the few first tries I had are unsuccessful 😅

**Comment by tonypinkevych** [comment]
@mlz11 It was working correctly before a few latest PRs, I was thinking of fixing it myself a bit later. But I'm glad you took it on yourself. Please let me know if you need any help, I would like to help 🙂

**Comment by mlz11** [comment]
@tonypinkevych https://github.com/raycast/extensions/pull/12478 seems to be a fitting fix to the issue

**Comment by tonypinkevych** [comment]
@mlz11 looks nice, thank you!
