### ISSUE TITLE
[Browser Bookmarks] Opens an empty tab in Firefox instead of bookmark URL

### ISSUE THREAD

**Issue by vsuharnikov** [raycast/extensions#12444]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Raycast Version

1.74.1

### macOS Version

14.5

### Description

"Open in Browser" opens a new window with empty tab instead of URL of bookmark.

## Compare to other extensions
I've tried to install [Hacker News](https://www.raycast.com/thomas/hacker-news) extension and it opens links as expected.

## Notes about opening URLs from Terminal
Have no idea, how this functionality works here, but this:
```bash
open -a Firefox --args 'http://www.youtube.com/'
```
opens a new tab in the last activated Firefox window (desired behavior), and this:
```bash
open -a Firefox 'http://www.youtube.com/'
```
opens a new window with an empty tab like in the issue.

### Steps To Reproduce

1. Open Raycast.
2. Write "Search Browser Bookmarks" and press Tab.
3. Select any bookmark and press Enter.

### Current Behaviour

"Open in Browser" opens a new window with an empty tab.

### Expected Behaviour

"Open in Browser":
1. Opens a bookmark url in Firefox.
2. Does this in the current active Firefox window.

**Comment by thomaslombart** [comment]
If this is happening in the terminal as well (so outside of Raycast), this is likely to be a macOS or a Firefox bug. Not sure we can do much here 😕

**Comment by vsuharnikov** [comment]
@thomaslombart it works totally fine if run with `--args` argument:
```bash
open -a Firefox --args 'http://www.youtube.com/'
```

**Comment by vsuharnikov** [comment]
Still doesn't work 🤷

**Comment by vsuharnikov** [comment]
I've just checked, now it works as expected.
