### ISSUE TITLE
[Bitwarden Vault] Autofill action

### ISSUE THREAD

**Issue by RihardsVeters** [raycast/extensions#12460]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Would love to see autofill as an action for vault items. This would really be just like 1password quick access menu but within Raycast.

**Comment by RihardsVeters** [comment]
I don't think that this would be too hard to implement and that would totally change the whole use of Bitwarden extension. 1password just simply asks for access to current website and that's it.. Any thoughts?

**Comment by jomifepe** [comment]
Hey, what do you mean with
> 1password just simply asks for access to current website and that's it

Does it do that in Raycast? Or the browser extension?

**Comment by RihardsVeters** [comment]
No, I meant 1password 8 macos app, asks for accessibility access when you install the app and then you can simply press ⇧⌘Space and open quick access menu, which works everywhere on mac. So I can press autofill to use it in browser or in any other opened app. I think that it would be great addition to Bitwarden extension, because currently I don't even see use of it if there's no autofill.
![IMG_4107](https://github.com/raycast/extensions/assets/41144957/88a34361-7ec8-43fe-b59c-330f0fec0253)

**Comment by jomifepe** [comment]
Are you using safari?

**Comment by RihardsVeters** [comment]
No, my default browser is Arc, but what's the difference here?

**Comment by jomifepe** [comment]
I'm trying to understand what's being used here, as I cannot gather a lot of information from a screenshot.

Is this coming from the 1password macos app? 

You must understand that Raycast provides us with a set of APIs and we are more or less restricted in what we can do. Spotlight probably has way more capabilities than Raycast, same goes for a native macOS app. 

Right now, it doesn't seem to be easy to do that. If possible, it would most likely have to be implemented using Swift.

**Comment by RihardsVeters** [comment]
So here's the information about quick access menu from 1Password 8 macos app https://support.1password.com/quick-access/
I understand that, but I'm sure that there must be an option to add simple autofill action to current Bitwarden extension.

**Comment by jomifepe** [comment]
How are you sure about that? Have you done any technical research?

**Comment by RihardsVeters** [comment]
Auto-fill basically is automatic copy/paste of two fields - username/email and password, so it shouldn't be too hard to check for relevant input fields in current window. I've no idea about back bone of this feature, but don't you agree that would be awesome if it could be done? As I understand you're one of Bitwarden developers or you just simply volunteer to create extension for open-source password manager?

**Comment by RihardsVeters** [comment]
Maybe this extension developers and Raycast team could work together on this if with current Raycast API it's impossible.

**Comment by RihardsVeters** [comment]
@erics118 @pernielsentikaer what do you thing guys? You've developed many extensions, so would this be possible?

**Comment by jomifepe** [comment]
1. I'm not a Bitwarden developer, I'm solely an open-source contributor, not affiliated in any way with Bitwarden.
2. I've told you before that I would like that feature to exist, which doesn't mean that it's feasible to implement
3. Are you aware of how open-source works? Most people here don't do this full-time. I will gladly implement features I see as valuable and maintainable.

If you so much desire this feature, please do some research or speak with the Bitwarden team and present a feasible way to implement this, saying that you're sure it's possible and that it's easy isn't enough.

**Comment by RihardsVeters** [comment]
I've suggested such quick access menu feature in Bitwarden Community Forum long time ago, but then came this extension which already replaces the need of it. Of course it. would be. great if Bitwarden developers implemented such feature in their macos app, but I think that won't happen any time soon.
