### ISSUE TITLE
[Visual Studio Code] - Add ability to re-order pinned items

### ISSUE THREAD

**Issue by hugomarfani** [raycast/extensions#12463]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

I think it would be great if you could re-order the pinned items in some way to make organisation easier!

### Who will benefit from this feature?

People who use the pin feature in the extension.

**Comment by tmwrnr** [comment]
Hi @hugomarfani

You can already reorder pinned items within the action panel (⌘ K) or using these shortcuts:

- move up: ⌥ ⌘ ↑
- move down: ⌥ ⌘ ↓

This should solve your problem.

**Comment by tmwrnr** [comment]
@raycastbot close this issue

**Comment by hugomarfani** [comment]
Thank you so much, I did not see that!!!!
