### ISSUE TITLE
[Spotify Player] Menubar "add to current playlist option"

### ISSUE THREAD

**Issue by OfficialCRUGG** [raycast/extensions#12475]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

The menubar item has a "Add to Playlist" option. However, when the user listens to a playlist but the current song is not in that playlist, an "Add to current Playlist" option would be nice. This is possible when the user uses smart shuffle, which occasionally plays songs that aren't in the playlist.

### Who will benefit from this feature?

People who use the Smart Shuffle feature as a means of expanding and growing their playlists. Whilst it may seem minimal, the amount of times I use this, clicking one "Add to current playlist" button would save tons of time compared to the dropdown, finding the right playlist, etc.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](https://raycast.com/community) if you need further help.

**Comment by OfficialCRUGG** [comment]
I have just looked into the code a bit, but if I'm being honest, I don't have the slightest idea how this would be implemented best.
Especially the part of conditionally showing the item only when the player is listening to a playlist, but the active song isn't part of that. I don't have the slightest clue how that would be done best.

**Comment by OfficialCRUGG** [comment]
Still relevant
