### ISSUE TITLE
[Jira Search (Self-Hosted)] Add command for create issue

### ISSUE THREAD

**Issue by Ernest0-Production** [raycast/extensions#12476]
### Extension

https://www.raycast.com/emanguy/jira-search-self-hosted

### Description

It would be very cool if you could port the issue creation command from jira extension. 

### Who will benefit from this feature?

Users who need the ability to quickly create a new task

**Comment by LunaticMuch** [comment]
I can look into that... but guess will take a bit

**Comment by Ernest0-Production** [comment]
> I can look into that... but guess will take a bit
Hi!  Thanks.

Is the jira cloud api so different from the self hosted api that we can't copy some of the source code from the jira cloud raycast extension?
