### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by ChristianTraxler** [raycast/extensions#12482]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

1.74.1

### macOS Version

14.4.1

### Description

"Output format mp4 is not available" is the error I keep getting.

### Steps To Reproduce

1. Clicking "Download video"
2. Get error "Output format mp4 is not available"

**Comment by JLee141** [comment]
Hey @ChristianTraxler 👋🏼

Had the same issue a few weeks back and I followed this and this solution helped me. Incase you haven't got this resolved. 👍🏼

https://github.com/raycast/extensions/issues/12110#issuecomment-2089490625
