### ISSUE TITLE
[Snippets] Dynamic placeholders in snippets

### ISSUE THREAD

**Issue by mattpatterson94** [raycast/extensions#1248]
**Describe the feature and the current behavior/state.**

A really great feature in Alfred is the ability to have dynamic placeholders in snippets

![Screen Shot 2022-03-31 at 5 48 20 pm](https://user-images.githubusercontent.com/4578986/161004672-e6776cd1-5505-4711-83e9-4a445e8c40e2.jpg)

So being able to reference things like a clipboard item in a snippet which is injected once the snippet is pasted.

**Will this change the current API? How?**

From a UX perspective, ideally a suggestion popup would show up if you typed a `{`, or alternatively a button directly below the snippet text field with placeholder options

![Screen Shot 2022-03-31 at 5 52 01 pm](https://user-images.githubusercontent.com/4578986/161005280-ad0ce3c9-a931-47dc-9be4-90655ba1ffc2.jpg)

**Who will benefit from this feature?**

The same people that would likely spend the time to set up a bunch of snippets to improve their productivity.

**Any Other info.**

Rather than referencing other extensions, an MVP could be using the OS apis, like the OS clipboard to build out some placeholder functions.

**Comment by sxn** [comment]
hi @mattpatterson94 - thanks for the suggestion. We're currently improving our Snippets extension, so your feedback is perfectly timed. ❤️ 
As this doesn't seem to be related to the extensions API, rather to the Snippets extension, I'll close the issue. If you have more feedback related to Raycast or its builtin extensions, don't hesitate to use the in-app `Send Feedback` command. 😺
