### ISSUE TITLE
[Zed] Duplicate entries when searching

### ISSUE THREAD

**Issue by tmwrnr** [raycast/extensions#12505]
### Extension

https://www.raycast.com/ewgenius/zed-recent-projects

### Raycast Version

1.74.1

### macOS Version

14.4.1

### Description

When you search for a project the same project is listed twice:

<img width="747" alt="image" src="https://github.com/raycast/extensions/assets/39673874/c5dc7ef2-5229-4629-a6d9-e25c3be1ff65">

Also when you search for a project which is pinned the project is listed in the pinned and recent section:

<img width="748" alt="image" src="https://github.com/raycast/extensions/assets/39673874/8d6e2d5f-0e91-4f8f-aa74-3dd557b65e68">

### Steps To Reproduce

1. Open a project with Zed
2. Open **Search Recent Project** command
3. Search the previous opened project

### Current Behaviour

The same project is listed twice.

### Expected Behaviour

The same project should only be listed once.

**Comment by ewgenius** [comment]
Thanks for the report @tmwrnr! I will check that.

**Comment by ewgenius** [comment]
@raycastbot assign me
