### ISSUE TITLE
Jira Enable to use self hosted instances

### ISSUE THREAD

**Issue by giolf** [raycast/extensions#12509]
### Extension

https://www.raycast.com/raycast/jira

### Description

Currently it seems not to be possibile to use this extension on self hosted jira instances.
It would be super handy to use it also on own jira instances.

### Who will benefit from this feature?

Each user which has to deal with self hosted jira instances

**Comment by thomaslombart** [comment]
It is possible by using an [API token](https://www.raycast.com/raycast/jira).

**Comment by giolf** [comment]
However if I use the extension called jira self hosted with the same api tokens it works. so I guess the issue is in ur extension.

**Comment by aghilas-xb** [comment]
Hello @thomaslombart and thank you for your work !
Could you please reopen this issue as it seems many of us can't make it work using api tokens.
As stated by someone else on another issue, the token/auth proved to be working using the [Raycast Jira Search (Self-Hosted Edition)](https://www.raycast.com/emanguy/jira-search-self-hosted) extension.

**Comment by giolf** [comment]
This is the main reason to stop me to be a paid user of raycsast: discordant core team

**Comment by thomaslombart** [comment]
Jira is included for free in Raycast fyi. I've reopened the issue, feel free to take a look at it.
