### ISSUE TITLE
[Brew] Cannot open details of installed package

### ISSUE THREAD

**Issue by TheHolyWaffle** [raycast/extensions#12507]
### Extension

https://www.raycast.com/nhojb/brew

### Raycast Version

1.74.1

### macOS Version

14.4.1

#### Error:
```
TypeError: Cannot read properties of null (reading 'value')

NC:index.js:13:25465
index.js:13:25312
    at Array.map (<anonymous>)
Ji:index.js:13:25305
```

### Steps To Reproduce

1. Open brew installed
2. Go open a package that is from a tap

**Comment by TheHolyWaffle** [comment]
@vpukhanov I still have the issue. Copied error log:
```
TypeError: Cannot read properties of null (reading 'value')

OC:index.js:13:24813
index.js:13:24660
    at Array.map (<anonymous>)
Ji:index.js:13:24653
```

**Comment by nhojb** [comment]
What's the package and tap that are causing the issue?

**Comment by TheHolyWaffle** [comment]
It seems to only happen for packages installed through taps: 

For instance: tap `sst/tap/sst` and package `sst`

https://github.com/user-attachments/assets/8b0ab2a9-0efe-4032-9418-dc36dfc39ba5

**Comment by j3lte** [comment]
#14596 Should fix this problem

**Comment by j3lte** [comment]
Fixed

@raycastbot close this issue
