### ISSUE TITLE
[Notion] ...

### ISSUE THREAD

**Issue by quintenverniers** [raycast/extensions#12514]
### Extension

https://www.raycast.com/notion/notion

### Raycast Version

1.75.1

### macOS Version

14.5

#### Error:
```
FetchError: request to https://notion.oauth.raycast.com/token failed, reason: unable to get local issuer certificate

    at withAccessToken(MA)
Fr:index.js:11:2490
    at ray-navigation-stack
Io:index.js:11:2088
```

### Steps To Reproduce

1. Macbook Pro M1 Pro 16 inch (16 gb ram)
2. Both on Hotel wifi and phone hotspot.
3. Same issue after rebooting

Browser (Arc - Chromium) shows a success message, after opening raycast I get an error.

### Current Behaviour

Login into notion is successful in the browser but fails.

**Comment by thomaslombart** [comment]
Are you using some kind of VPN/firewall/proxy?

**Comment by quintenverniers** [comment]
Hi @thomaslombart I was indeed...

I tried to connect notion on my company laptop, which uses zscaler.
I should've thought about that, I tried about 15 times, without any luck.

Now I disabled zscaler and it worked right away.
Sorry to have bothered you!
(Maybe I shouldn't have tried to set this up at 11 at night...)

Thanks for you comment!

**Comment by NikSrg** [comment]
Hi Raycast Team, 
I am having the same `unable to get local issuer certificate` error on my company mac (with zScaler). Even on dict.cc or google translate extension. Is there any workaround, because I can't turn off zScaler :(

**Comment by okinawaa** [comment]
same issue face with me

**Comment by okinawaa** [comment]
It works for me

<img width="1045" alt="image" src="https://github.com/user-attachments/assets/3b26c8e8-4992-417a-9fab-5bcc724f132d">
