### ISSUE TITLE
Issue with Extension 1password

### ISSUE THREAD

**Issue by prashantdwivedi** [raycast/extensions#12513]
### Extension

https://www.raycast.com/khasbilegt/1password

### Raycast Version

Version 1.75.1

### macOS Version

Ventura 13.6.7

### Description

I'm very new to Raycast. 
A few days ago, take Raycast Pro and switched from Alfred.

90% of shifting done; I'm stuck on 1Password auth. 
In the Image, you see

<img width="1048" alt="CleanShot 2024-05-22 at 23 36 09@2x" src="https://github.com/raycast/extensions/assets/6306052/efc11230-78b9-43cb-8906-06a61bde2a43">
<img width="366" alt="CleanShot 2024-05-22 at 23 36 03@2x" src="https://github.com/raycast/extensions/assets/6306052/bc13fc6f-7128-48a2-b327-a2c0788b0892">

### Steps To Reproduce

I have no idea what you are asking here. The problem I tell in the description.

**Comment by Luk4h** [comment]
Hello! Do you have the 1Password app and CLI installed?

**Comment by prashantdwivedi** [comment]
> Hello! Do you have the 1Password app and CLI installed?

1Password app 
Version: 1Password for Mac 8.10.32 (81032050)

**Comment by Luk4h** [comment]
Please check if you are on the latest extension upgrade

**Comment by cmpaul** [comment]
Also having this issue here!

**Comment by axap288** [comment]
> > Hello! Do you have the 1Password app and CLI installed?
> 
> 1Password app Version: 1Password for Mac 8.10.32 (81032050)

install 1Password Cli : brew install 1password-cli
