### ISSUE TITLE
[Bitly URL Shortener] Unable to get selected text from frontmost application 

### ISSUE THREAD

**Issue by alvaroybanez** [raycast/extensions#12529]
### Extension

https://www.raycast.com/blessanm86/bitly-url-shortener

### Raycast Version

1.75.1

### macOS Version

14.5

### Description

After pasting my API token in the extension config, I keep getting the error "Unable to get selected text from frontmost application".

This extension stopped working a while ago, but I can't recall when exactly. 

### Steps To Reproduce

1. When using Raycast on Macbook Pro M3
2. With Sonoma 14.5 using Arc Version 1.43.1 (50198)
3. I have my Bitly API token and I'm logged in with password per the extension instructions
4. I copy the URL with a Raycast shortcut (cmd+shift+C)
5. I run a Raycast shortcut (cmd+shift+B) to shorten the URL
6. I get the aforementioned error

### Current Behaviour

I get error "Unable to get selected text from frontmost application", and URL is not shortened.

### Expected Behaviour

The URL is shortened and copied onto my clipboard.

**Comment by blessanm86** [comment]
You might be facing this [issue](https://github.com/raycast/extensions/issues/6129#issuecomment-1530962812)

**Comment by alvaroybanez** [comment]
Thanks, but unfortunately not. 

Raycast already had access before checking, so this does not seem to be it. 

![Screenshot 2024-05-25 at 23 33 40](https://github.com/raycast/extensions/assets/28959458/7937095c-a1a1-4443-b04b-1ac8c3d09188)

**Comment by blessanm86** [comment]
@alvaroybanez Im not sure why this fails as this is a raycast API. 
These changes were introduced by @alex-cory in the last update.

I have wrapped the relevant code in a try catch so it properly fallback to the clipboard in case of failure.

**Comment by alvaroybanez** [comment]
@blessanm86 I'm closing this, as it magically went back to working 🤷 

Thanks for your help.
