### ISSUE TITLE
[Coffee] create specific command for Caffeinate for hours

### ISSUE THREAD

**Issue by carlesba** [raycast/extensions#12521]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

currently we got a different command to `caffeinate for...` which is great but requires extra `tab` key to be set.

I don't mean to remove this option but add a new one that is specifically for `Hours` so we can quickly set the caffeinate state.
The new command is powerful but harder to use.

### Who will benefit from this feature?

less actions to set caffeinate while keeping functionality while keeping current functionality.
We can enable/disable commands to customize our experience with the extension.

### Anything else?

new icons look neat. Thanks!

**Comment by xilopaint** [comment]
I can't understand you. Previously, you had to enter the command before filling out the form and submitting it. It wasn't a step less than now.

**Comment by carlesba** [comment]
Previously you could do:

1. open raycast
2. type caff  (selecting caffeinate for hours) 
3. press enter
4. type hours
5. press enter
 then you get caffeinated for H hours

Now:
1. open raycast
2. type caff (selecting caffeinate for time)
3. press enter
you get error: `no values set for caffeinate length`

I need to type `tab` and fill the numbers.

I know it's subtle, but makes a difference when using it. The issue is in how Raycast handle multiple inputs. With one input you can jump to the only field with enter.

Also, I don't understand who needs to caffeinate by seconds.

I'm suggesting to create a command to caffeinate by hours-only so we can still have this case.

**Comment by xilopaint** [comment]
You don't need to fill in the `Minutes` and `Seconds` arguments if you don't need them.

**Comment by carlesba** [comment]
I know. It's just the convenience of being able to press enter to fill the Hours. We can't after the last upgrade.

**Comment by xilopaint** [comment]
You described five steps in the previous implementation. The current implementation also depends on five steps but avoids the unnecessary form, making the command cleaner:

1) open raycast
2) type caff
3) press tab
4) fill in the `Hours` argument
5) press enter

**Comment by carlesba** [comment]
correct, my request is in the 3rd step. Before, it work with enter, which is more handy than tab. Now it doesn't.
