### ISSUE TITLE
[Aerospace Tiling Window Manager] Not handling mixed arrays properly

### ISSUE THREAD

**Issue by dmnkf** [raycast/extensions#12522]
### Extension

https://www.raycast.com/limonkufu/aerospace

### Raycast Version

1.75.1

### macOS Version

14.4.1

### Description

as I have multiple workspaces the whole logic behind my screen assignment is a bit complicated.

currently I got 

```
[workspace-to-monitor-force-assignment]
1 = ['built-in', 'secondary', 'LG.*', 1]
2 = ['secondary', 'zowie.*', 3]
3 = ['LG.*', 'main']
4 = ['secondary', 'zowie.*', 3]
5 = ['secondary', 'zowie.*', 3]
6 = ['secondary', 'zowie.*', 3]
```

the plugin however can't parse this and says this isn't allowed. Aerospace itself handles it properly.

### Steps To Reproduce

- add something like this to the .toml config

[workspace-to-monitor-force-assignment]
1 = ['built-in', 'secondary', 'LG.*', 1]
2 = ['secondary', 'zowie.*', 3]
3 = ['LG.*', 'main']
4 = ['secondary', 'zowie.*', 3]
5 = ['secondary', 'zowie.*', 3]
6 = ['secondary', 'zowie.*', 3]

- try to use the raycast plugin

### Current Behaviour

Some error about not being able to parse this mixed array.

### Expected Behaviour

Handle it like aerospace, where mixed arrays seem fine.

**Comment by limonkufu** [comment]
Thanks for the report.

Aerospace added a new functionality to expose the config directly which i will be switching very soon. That would take care of this bug as well. I will update here once i have the version ready

**Comment by limonkufu** [comment]
@raycastbot assign me
