### ISSUE TITLE
[Visual Studio Code] Cannot use 'Search Recent Projects' feature

### ISSUE THREAD

**Issue by viv96** [raycast/extensions#12525]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Raycast Version

1.75.1

### macOS Version

14.5

### Description

Error: 
```
Error: Command failed with exit code 1: osascript -e 
        tell application "System Events"
          tell process "Code"
            repeat while window 1 exists
              click button 1 of window 1
            end repeat
          end tell
        end tell
        
106:154: execution error: System Events got an error: Can’t get button 1 of window 1 of process "Code". Invalid index. (-1719)

        tell application "System Events"
          tell process "Code"
            repeat while window 1 exists
              click button 1 of window 1
```

The 'Search Recent Projects' feature of Visual Studio Code extension is not working. When the application is closed, the command works to open the selected project. But when the application is already open and when you are trying to switch projects then the command is glitching out.

### Steps To Reproduce

- make sure vscode application is closed
- open a recent project using 'Search Recent Projects' of the extension
- now try to search and open a different recent project using the same command

### Current Behaviour

Using Raycast to search recent project will trigger error

### Expected Behaviour

Should be able to open recent projects in vscode

**Comment by aliaksandrZh** [comment]
Hi, could you make a record? I just tried different scenario it seems like the extension works as expected.
