### ISSUE TITLE
[Zoom] ... Something went wrong on viewing my calendar 

### ISSUE THREAD

**Issue by brandonlipman** [raycast/extensions#12533]
### Extension

https://www.raycast.com/raycast/zoom

### Raycast Version

1.75.1

### macOS Version

14.5

#### Error:
```
Error: Error while refreshing tokens: 400 (Bad Request)
{"reason":"Invalid Token!","error":"invalid_grant"}

    at withAccessToken(Pie)
Fr:index.js:11:2490
    at ray-navigation-stack
Io:index.js:11:2088
```

### Steps To Reproduce

Go to upcoming meetings. Get the something went wrong. 

### Current Behaviour

Go to upcoming meetings. Get the something went wrong. 

### Expected Behaviour

Go to upcoming meetings. Get my meetings.

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/10896 (OAuth-related issue), so I'll mark it as such.

**Comment by brandonlipman** [comment]
Thanks @thomaslombart!
