### ISSUE TITLE
[1Password] Cannot read properties of undefined (reading 'account_uuid')

### ISSUE THREAD

**Issue by lmoloney** [raycast/extensions#12538]
### Extension

https://www.raycast.com/khasbilegt/1password

### Raycast Version

1.75.1

### macOS Version

14.5

### Description

Since latest upgrade

'My Passwords' provides the following
![Screenshot 2024-05-23 at 16 59 54](https://github.com/raycast/extensions/assets/20657870/c754d05c-bbb3-4a0f-8adf-d8f0bbe7124a)

Interestingly 'My Vault' command works
![Screenshot 2024-05-23 at 17 01 24](https://github.com/raycast/extensions/assets/20657870/af78ef5a-49d5-4578-ac2f-e9b6f3bed6a5)

Error dump shows the following

`TypeError: Cannot read properties of undefined (reading 'account_uuid')

Jp:Items.tsx:20:30

---
17: import { ItemActionPanel } from "./ItemActionPanel";
18: import { useMemo, useState } from "react";
19: 
20: export function Items({ flags }: { flags?: string[] }) {
21:   const [category, setCategory] = useCachedState<string>("selected_category", DEFAULT_CATEGORY);
22:   const [passwords, setPasswords] = useState<Item[]>([]);
23: 
---

_r:item-list.js:44:481
    at Vr
Fr:index.js:11:2490`

### Steps To Reproduce

1. Upgrade 1Password Raycast Extension
2. Use the My Password Command
3. Get error

### Current Behaviour

My Passwords command doesn't work

### Expected Behaviour

My Passwords works and lists the vault entries.

**Comment by Luk4h** [comment]
@raycastbot assign me
@raycastbot good first issue

@raycastbot rename this issue to "[1Password] 1Password CLI < v2.29.0 errors"

**Comment by Luk4h** [comment]
Hey @lmoloney, another user reported the same problem. It appears that somewhere between 1Password CLI v2.0.0 to v2.29.0. 1Password included a new property "account_uuid" in their "op account get" response. And the "My Password" command uses it.

Are you able to try update your 1Password CLI, and test if it solves this issue? Thanks

**Comment by Luk4h** [comment]
@raycastbot assign me

**Comment by Luk4h** [comment]
@raycastbot good first issue

**Comment by Luk4h** [comment]
Apparently this one didn't get spotted on testing of the latest update, because our accounts were on cache. You may ignore my last comment and wait for the merge of #12543 .

**Comment by Luk4h** [comment]
@raycastbot rename this issue to "[1Password] Cannot read properties of undefined (reading 'account_uuid')"
