### ISSUE TITLE
[Capacities] Not showing all Spaces and not adding to Daily Note

### ISSUE THREAD

**Issue by Cbro1212** [raycast/extensions#12539]
### Extension

https://www.raycast.com/steffenble/capacities

### Raycast Version

1.75.1

### macOS Version

14.5

### Description

When I use the Open Space it only shows one of my spaces.  When I use Add to Daily Note it does not show any spaces and it does not add the text to my daily note.

### Steps To Reproduce

Using Raycast as show above

### Current Behaviour

Not working

### Expected Behaviour

Want to see all my spaces and want to add to daily note

**Comment by sbleh** [comment]
@raycastbot  rename this issue to "Not showing all spaces"

There was a delay in processing messages to your daily note. They should all be there now. We'll look into the problem with your spaces.

**Comment by sbleh** [comment]
This should be fixed with the latest update.

@raycastbot close this issue
