### ISSUE TITLE
[Asana] Setting to hide Start Date from Create Task screen

### ISSUE THREAD

**Issue by parterburn** [raycast/extensions#12558]
### Extension

https://www.raycast.com/raycast/asana

### Description

Paid Asana accounts unlock the option for `Start Date`, but it's very optional inside Asana's UI and only used in more complex workflows. However, inside the Raycast extension, it has as much weight in the UI as `Due Date` and is often mistyped for this more important date in the flow of creating tasks quickly.

Is it possible to add a setting like `Show start dates` so that it wouldn't show in the Create Task screen at all?

### Who will benefit from this feature?

Users with Asana [Starter](https://asana.com/plan/starter), [Advanced](https://asana.com/plan/advanced), [Enterprise](https://asana.com/enterprise), and [Enterprise+](https://asana.com/enterprise) tiers, as well as [legacy tiers](https://asana.com/pricing-legacy) Premium, Business, and Legacy Enterprise.

### Anything else?

[Asana Start dates and start times](https://help.asana.com/hc/en-us/articles/23535997245339-Scheduling-tasks-using-start-dates-due-dates-and-times#h_01HBB2EJQT8TTQ9SBQ2MEZ3WEB)
> Start dates and start times enable teams with _complex_ workflows to effectively schedule tasks across multiple days or even down to the minute.

![CleanShot 2024-05-24 at 07 54 13@2x](https://github.com/raycast/extensions/assets/791889/625ae75c-ca69-40be-84dd-5411100965ce)

![CleanShot 2024-05-24 at 07 52 40@2x](https://github.com/raycast/extensions/assets/791889/8eb16c15-2dd1-4baf-8698-7660d1bfa51b)

![CleanShot 2024-05-24 at 07 56 41@2x](https://github.com/raycast/extensions/assets/791889/a36cbb8d-ed69-4eb2-b6b4-30e5423c6a30)

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](https://raycast.com/community) if you need further help.
