### ISSUE TITLE
[Arc] ... Open favourites without creating a new tab

### ISSUE THREAD

**Issue by MAB941009** [raycast/extensions#12565]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

Hello,

I'd like to be able to open a link from Raycast, that is favourited in Arc, without opening a new tab. I'd like the link to open the favourite tab, rather than a brand new one.

### Who will benefit from this feature?

Every Arc user.

**Comment by ariccb** [comment]
I am also hoping for this. Right now I have Slack favourited, and created a quicklink to it, but it opens in a new tab and doesn't load any content.

**Comment by snoolord** [comment]
being able to open favorites in the exact tab would be so clean!

**Comment by hugodutka** [comment]
I found a workaround - you can create an Apple Shortcut and use it instead of a quicklink. Here's a guide: https://joschua.io/posts/2023/05/24/automating-arc-applescript/
