### ISSUE TITLE
[TinyPNG] Add clipboard source

### ISSUE THREAD

**Issue by gitkeniwo** [raycast/extensions#12579]
### Extension

https://www.raycast.com/kawamataryo/tinypng

### Description

First off, a big thank you for this very nice extension you made.

I think it would be nice if we could compress the image in our current clipboard, and add the compressed image back to the clipboard because sometimes we don't want to save the pic first when it's copied from the internet.

**Comment by Alipacman** [comment]
I would love this, too!
