### ISSUE TITLE
[Open Folders] Folder in Folder Speed Dial show 'Value.substring' instead of Folder Name

### ISSUE THREAD

**Issue by j-peeters** [raycast/extensions#12596]
### Extension

https://www.raycast.com/timothy_boye/open-folders

### Raycast Version

1.75.1

### macOS Version

14.5

### Description

![20240527 Open Folder Settings](https://github.com/raycast/extensions/assets/4502360/a1e4d447-a14b-4ff9-b26d-f5620d6a64ac)

### Steps To Reproduce

Set a few folders for the Open Folder Speed Dial
Open the Speed Dial
See screenshot 

### Expected Behaviour

That the folder names are shown

**Comment by gfazioli** [comment]
yep, please 🙏 otherwise the extension becomes useless as the folders are not visible

**Comment by timothyBoye** [comment]
PR #13196 should have resolved this (thanks @gfazioli) let us know if not.

@raycastbot close this issue
