### ISSUE TITLE
[Phosphor Icons] Use the same search behavior as the Phosphor Website for aliases

### ISSUE THREAD

**Issue by OfficialCRUGG** [raycast/extensions#12606]
### Extension

https://www.raycast.com/marinsokol/phosphor-icons

### Description

The Website of Phosphor Icons seems to use tons of aliases, which makes searching their (often confusingly named) icons a lot easier, which is one of the main reasons people install this extension. For example on their website, I can find `arrow-clockwise` under the query "refresh", which isn't the case in this.

Also: See my correction below

### Who will benefit from this feature?

Everyone using this extension regularly

### Anything else?

Since all of phosphor is open-source, the list should be findable somewhere. Either in their website or elsewhere. Didn't have any luck in finding it so far though.

**Comment by OfficialCRUGG** [comment]
Correction: It seems the extension already respects these, but not perfectly. The actual alias for example icon I mentioned is `refreshing`. Searching that in Raycast finds the icon. It seems the website uses a fuzzy search here, which would be great for the extension too.

**Comment by marinsokol** [comment]
@raycastbot assign me
