### ISSUE TITLE
[YouTube Downloader] YouTube Live replays download

### ISSUE THREAD

**Issue by leofritsch** [raycast/extensions#12601]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

Hey Vimtor, I see the extension doesn't accept youtube.com/live/123456 type links yet.

Super easy fix, those can be directly converted to a "watch?v=" type link because the id is the same.

youtube.com/live/123456 -> youtube.com/watch?v=123456

And then from there be downloaded with the extension

### Who will benefit from this feature?

Everyone will benefit (:

**Comment by vimtor** [comment]
Thanks for the suggestion @leofritsch!

Let me check if the YouTube API that the extension uses supports downloading those kinds of videos.

**Comment by leofritsch** [comment]
@vimtor Ah I should have mentionned also, I tried converting the "/live" to "watch?v=" myself and it works every time this way so it probably should work if you convert the URLs?

Not sure about "live" lives.

**Comment by vimtor** [comment]
@leofritsch checking back on the extension, I remembered that it currently does not support downloading live videos. In fact, it shows an error message when you try to download a live video:

![CleanShot 2024-05-31 at 14 59 51@2x](https://github.com/raycast/extensions/assets/36263538/3146d450-cb02-4dc2-b2fc-4bb4ca216a92)

I don't understand how you were able to download them 😅

Perhaps you are downloading already finished livestreams?
