### ISSUE TITLE
[Quick Notes] Draft Changes in Edit View saved when go back

### ISSUE THREAD

**Issue by Ernest0-Production** [raycast/extensions#12623]
### Extension

https://www.raycast.com/biknandy/quick-notes

### Raycast Version

1.73.2

### macOS Version

15.2

### Description

When I want to edit a note and go back without clicking the Save Note button, my intermediate changes are already saved.

This doesn't seem entirely logical.

### Steps To Reproduce

1. Edit Note
2. Change title
3. Go back (esc)

### Current Behaviour

Changed title

### Expected Behaviour

Origin title

**Comment by biknandy** [comment]
@raycastbot assign me

This is by design as if you're editing a very large note and hit back by accident, it makes sense to save what you have (almost like autosave)

I can change it to not do this for just the title though

**Comment by Ernest0-Production** [comment]
@biknandy Hi! There is a suggestion to create a copy of the file and edit it until the note is saved)

You can also add support for Form Draft. I think, under the hood, raycast will save intermediate changes in some temporary files. In this case, you won't have to create your own draft logic.

**Comment by biknandy** [comment]
Ah yea I can maybe draft the current state as a new note. On save of that draft it can replace the current. Form draft won't work for this app (I tried it) due to the complexity of the file saving.
