### ISSUE TITLE
[Vim Bro - Search Vim Commands] Add Ctrl-a, Ctrl-x

### ISSUE THREAD

**Issue by d3chapma** [raycast/extensions#12630]
### Extension

https://www.raycast.com/ajaypremshankar/vim-bro

### Description

Add Ctrl-a and Ctrl-x to the list

Ctrl-a increments the number under the cursor
Ctrl-x decrements the number under the cursor

### Who will benefit from this feature?

Anyone that works with numbers in vim.

**Comment by pernielsentikaer** [comment]
This is now added @d3chapma, thanks for flagging 🙂
