### ISSUE TITLE
[App Keeper Manager] Allow running on always keep without making a selection

### ISSUE THREAD

**Issue by dudido** [raycast/extensions#12632]
### Extension

https://www.raycast.com/edith/app-keeper-manager

### Description

Currently, I have to open the extension and choose which apps to keep open.

Since I can set always keep open for some apps, I want to run it based on that, without making a selection 

### Who will benefit from this feature?

It's just faster so everyone probably

**Comment by onlysunjun** [comment]
Actually, it’s already configured. When you enter this plugin, you can use the up and down keys to select the app. Click on actions (shortcut key command+k) to see the set keep option (this configuration will remain unless you cancel it). To cancel: move to the set keep app and press ENTER (Clear always keep).
<img width="780" alt="iShot_2024-06-21_01 33 54" src="https://github.com/raycast/extensions/assets/74503143/4efb209f-854f-456b-ab61-9723c1c306d1">
<img width="781" alt="iShot_2024-06-21_01 35 40" src="https://github.com/raycast/extensions/assets/74503143/81d8411d-7751-49c2-859b-b01e163ada58">

**Comment by dudido** [comment]
Sorry maybe there was a misunderstanding: I want to run the command to close all apps (except for those already set to always keep) *without* seeing the submenu you made a screenshot of. Like a set and forget mode, based on what I had set previously as always keep.

I don't understand how your explanation demonstrates a way to do that.

**Comment by onlysunjun** [comment]
This demonstrates how to set ‘always keep’ and clear ‘always keep’ settings using Obsidian as an example. I hope this meets your requirements.

https://github.com/raycast/extensions/assets/74503143/60b823b3-c264-4201-ac72-00b2e59d3317

**Comment by onlysunjun** [comment]
This demonstrates how to set ‘always keep’ and clear ‘always keep’ settings using Obsidian as an example. I hope this meets your requirements.The app for setting needs to be selected using either the left mouse button or the up and down arrow keys.
https://github.com/raycast/extensions/assets/74503143/99676caa-9057-423c-86ee-ac26abbbe55a

**Comment by dudido** [comment]
Thank you for the video, but now I'm sure you haven't understood my request. I already know how to use and set ‘always keep’.

I'm looking for a way to close all apps without opening the extension's submenu. Currently the steps to close all apps are as follows:

**Comment by onlysunjun** [comment]
Got it. Adjust the close option to command+enter, and optimize the process as follows:
	1.	Open Raycast
	2.	Select ‘Close Unnecessary Apps’
	3.	(Optional) Activate or change ‘always keep’ for certain apps
	4.	Press command+enter
Does this approach suit your scenario?

**Comment by dudido** [comment]
I'm not sure…

Currently pressing the key Enter after your step two (2. Select ‘Close Unnecessary Apps’), opens a list of apps.

Why don't you allow to use a modifier key at that point such as command-enter to directly run the action 'close other apps' (and allow assigning a keyboard shortcut for that) without opening that list of apps?

So the workflow would be either:
1. Open Raycast
2. Select ‘Close Unnecessary Apps'
3. Press enter to see list of running apps

Vs.

1. Open Raycast
2. Select ‘Close Unnecessary Apps’
3. Press control+enter to close all apps not set to always keep.

**Comment by onlysunjun** [comment]
The update has been submitted, changing the shortcut to `close other apps` to Command + Enter.

**Comment by onlysunjun** [comment]
@raycastbot close this issue
