### ISSUE TITLE
[IPA Translator] Add support for SAMPA, X-SAMPA

### ISSUE THREAD

**Issue by dudido** [raycast/extensions#12631]
### Extension

https://www.raycast.com/BossElijah/ipa-translator

### Description

Great idea. This should also be able to transcribe to SAMPA or X-SAMPA

### Who will benefit from this feature?

Anyone using transcription for machines.

**Comment by BossElijah** [comment]
I think this is a good idea, so if anyone wants to create a PR for it, they're welcome. I don't have time to work on it at the moment though, but would appreciate the feature! 👍
