### ISSUE TITLE
Brew - Change command name!

### ISSUE THREAD

**Issue by DillonB07** [raycast/extensions#1263]
# Extension – [Brew](https://github.com/raycast/extensions/tree/main/extensions/brew)

Author: @nhojb 

**Describe the feature and the current behavior/state.**

On my computer, I don't use homebrew with the `brew` command. Instead, my command is `homebrew`. I suggest being able to modify the command in the extension settings.

Currently, we're stuck with `brew` and can't change it.

**Who will benefit from this feature?**

Anyone who has changed the name from `brew` to something else.

**Comment by daniel-stoneuk** [comment]
You can achieve something like this with the "alias" feature! For example, give each command an alias that begins with `homebrew`.

<img width="838" alt="image" src="https://user-images.githubusercontent.com/15860949/161386136-5ecd1e81-ed03-4538-bdd4-90e48a5e1a17.png">

**Comment by DillonB07** [comment]
Sorry, maybe I wasn't clear with what I meant in my original message.

If, for example, I want to install a new package in Terminal, I would run `homebrew install NAME` instead of `brew install NAME`.  What I want is to be able to specify that my homebrew installation uses `homebrew` instead of `brew` for when the extension runs commands.

**Comment by daniel-stoneuk** [comment]
Ahh sorry, I hadn't considered your configuration! 

That's a good feature request and can probably be implemented in a similar way as the Bitwarden extension.

**Comment by dufferzafar** [comment]
I want to change the homebrew path! I use an M1 Macbook but don't install homebrew in `/opt` but in my `$HOME` directory.

**Comment by nhojb** [comment]
> I want to change the homebrew path! I use an M1 Macbook but don't install homebrew in /opt but in my $HOME directory.

I'll add a preference for the brew binary path. That should work with your setup.

**Comment by DillonB07** [comment]
Awesome! Looking forward to being able to use it.

**Comment by nhojb** [comment]
Update has just been published. Let me know if you come across any issues 😄
