### ISSUE TITLE
[Apple Reminders] "Menu Bar Reminders" issues

### ISSUE THREAD

**Issue by Erimus-Koo** [raycast/extensions#12635]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Raycast Version

1.75.1

### macOS Version

14.5

### Description

1. The "Menu Bar Reminders" displays an icon on the secondary display, but no response while clicked.
2. Use the command "Menu Bar Reminders", no pop-up windows.

### Steps To Reproduce

1. Use 2 displays.
2. Activate the "Menu Bar Reminders"
3. Click the icon of "Menu Bar Reminders" on the secondary display.

**Comment by thomaslombart** [comment]
Could you share a recording? It'll make it easier to see what's happening.

**Comment by Erimus-Koo** [comment]
Okey, there're more details.

---
I want to show you the issue 2nd first,  "Use the command "Menu Bar Reminders", no pop-up windows."
<img width="1440" alt="image" src="https://github.com/raycast/extensions/assets/17139670/189a179f-627d-444d-bd4c-85d8e105b5b5">

If I press enter on this item, what should happen in the product design?
In my understanding, I wish it open the pop-up window from menu bar icon, like below:
<img width="1041" alt="image" src="https://github.com/raycast/extensions/assets/17139670/90961b15-0a72-4419-ad63-b5c5986d57de">

But now, only the icon flinks once, maybe restart or deactivate/activate.

---

And the other issue about the 2nd monitor, more details:

1. While the setting is opening, the icon on the 2nd display is not working.
<img width="1440" alt="image" src="https://github.com/raycast/extensions/assets/17139670/7da3b689-87ac-4488-ba2b-72bb56827558">
👆🏻While setting, the icon works on the major display. But doesn't work on the 2nd monitor.  


2. Sometimes while I click the major display's icon, the pop-up window will appear on the 2nd monitor.  
 Unfortunately, I can't record both monitors in one video.

**Comment by thomaslombart** [comment]
So, pressing `Menu Bar Reminders` is only activating a menu bar command, meaning an icon will appear in your menu bar. We can't toggle it because we're limited by Apple's APIs here.

For the 2nd issue, do you mean that the menu bar icon is never displayed?

**Comment by Erimus-Koo** [comment]
I see.

In the 2nd issue, the icon appeared, but nothing happened while chick, sometimes, on the 2nd monitor.

**Comment by thomaslombart** [comment]
So the issue is that clicking on the menu bar icon on the main display will get the pop-up to open on the 2nd display, right?
