### ISSUE TITLE
[App Keeper Manager] Support for Little Arc

### ISSUE THREAD

**Issue by dudido** [raycast/extensions#12633]
### Extension

https://www.raycast.com/edith/app-keeper-manager

### Description

Arc browser uses pop-up windows called little Arc. I want to be able to chose to close little Arc windows, but leave the main browser windows open.

### Who will benefit from this feature?

Anyone using Arc

**Comment by onlysunjun** [comment]
I haven't used ARC before. I recently downloaded it to check it out. Could you please provide a screenshot to show which part of the window "little arc" refers to?

**Comment by meikal** [comment]
You can find information about the feature at https://resources.arc.net/hc/en-us/articles/19235387524503-Little-Arc-Quick-Lookups-Instant-Triaging

Little Arc is the product name for a pop-up browser window to open external hyperlinks. These pop-ups can then be optionally integrated back into the main browser sessions by the user, left open, or closed. Similar to a session management in IDEs IMO.
