### ISSUE TITLE
[Raindrop.io] ...

### ISSUE THREAD

**Issue by ksandvik** [raycast/extensions#1264]
# Extension – [Raindrop.io](https://github.com/raycast/extensions/tree/7c19be06ffd759fb5d7fb9d713e3ea580ea1d193/extensions/raindrop/)
Author:

## Description

[Raindrop.io](http://raindrop.io/) command does not understand #hashtag entries with search. Should I file an issue over in github?
## Steps To Reproduce

1.Search #golang
2.

## The current behavior
No entries

## The expected behavior
All #golang tagged entries should show up. Same with other tags, or even better with multiple tag entries as a union of all those.

### Raycast version

1.31.0

**Comment by siriusnottin** [comment]
Hi @ksandvik, do you still have this issue? I just tested and it works fine on my side. (Raycast 1.33.2, Raindrop 5.5.1)

**Comment by ksandvik** [comment]
Yes, works now. Please close this one.

**Comment by siriusnottin** [comment]
Glad it works! I'm not part of the Raycast team so I can't close the issue myself ;)

**Comment by pernielsentikaer** [comment]
I can do it! 😄
