### ISSUE TITLE
[Quick Search] can custom searching site

### ISSUE THREAD

**Issue by bcometa** [raycast/extensions#12645]
### Extension

https://www.raycast.com/iwfan/quick-search

### Description

I would love to add some custom search locations. For example, searching a ticket number in Repairshopr. 

### Who will benefit from this feature?

Anyone that wants to search the clipboard with a hotkey using a different site than the four currently supported.

**Comment by iwfan** [comment]
Hi @bcometa! Thank you for your interest in this extension! I will look into adding the functionality as soon as possible.

@raycastbot rename this issue to "[Quick Search] can custom searching site"
@raycastbot assign me

**Comment by bcometa** [comment]
Thank you, @iwfan! After submitting this, I figured out how to do it in Raycast using Quick Links, but it would still be nice to have in the future if you ever get the free time and think it would be useful.

**Comment by iwfan** [comment]
I apologize for the slow response, I don't have enough time to complete this feature at the moment. It might be added in the future.

@raycastbot close this issue
