### ISSUE TITLE
[Things] ... search task

### ISSUE THREAD

**Issue by Skalt1** [raycast/extensions#12659]
### Extension

https://www.raycast.com/loris/things

### Description

Thank you for your work. I have a little request that it would be great to have. 
It would be possible to search a things task through the extension?
Thank you so much.

### Who will benefit from this feature?

Everyone who uses the extension.

**Comment by loris** [comment]
It's already possible somehow, if you type something in any lists (today, etc) and hit `⌘+⏎` it will open trigger that search into Things:
![Screenshot 2024-05-30 at 13 57 49@2x](https://github.com/raycast/extensions/assets/8362/3d3dea01-a5c8-4260-b0f3-70e38b58e77c)

However, what you probably meant was getting the search results _inside_ Raycast, but unfortunately this is not currently supported by Things AppleScript integration (https://culturedcode.com/things/support/articles/2803573/#search)
