### ISSUE TITLE
[Trello] ... 'Create a Todo' does not create anything in Trello

### ISSUE THREAD

**Issue by jessemdowd** [raycast/extensions#12654]
### Extension

https://www.raycast.com/ChrisChinchilla/trello

### Raycast Version

1.75.1

### macOS Version

14.5 (23F79)

### Description

It looks like it works but it doesn't actually create anything inside of trello. I can't seem to figure out why.

### Steps To Reproduce

1. Select Trello . `Create a Todo`
2. Fill out the form
3. Submit form
I've tried multiple times and multiple boards to test it.
![Screenshot by Dropbox Capture](https://github.com/raycast/extensions/assets/70118286/0c4982e6-a475-47c5-bea0-a4603f9e8ed1)

### Current Behaviour

Submitting the form, the behavior is just like anything else that is successful. There are no error messages. However, nothing submitted actually is created in Trello.

### Expected Behaviour

A new trello card would be created inside Trello

**Comment by ChrisChinchilla** [comment]
So @jessemdowd I suspect this is because you haven't gone through the steps here https://github.com/raycast/extensions/tree/a3b7797159feda1f48807e7a21287ce4dc6b2a23/extensions/trello/#trello-extension-for-raycast

I tried hard to make this clearer recently, but unfortunately the Trello API doesn't support some of Raycast's other options to make authentication easier.

**Comment by jessemdowd** [comment]
@ChrisChinchilla Thank you for the reply.
To clarify, I have followed those steps and the other commands work fine. Its just the Create that isn't working.
Am I missing something in the extension configuration?
![Screenshot by Dropbox Capture](https://github.com/raycast/extensions/assets/70118286/df753efe-4e32-45bc-9666-4f8b53c82f05)

**Comment by jessemdowd** [comment]
@ChrisChinchilla Started over and dug a little deeper, it looks like your extension is only granted `read` access. That would explain it... Not sure how to adjust that though.
![Screenshot by Dropbox Capture](https://github.com/raycast/extensions/assets/70118286/3c07a08b-5a8a-484c-846a-ed7db6d1afd2)

**Comment by ChrisChinchilla** [comment]
@jessemdowd Well this is odd, I fixed this in a previous PR 🤔

**Comment by jessemdowd** [comment]
Thank you @ChrisChinchilla 
The auth scope in the the PR worked for me. I can create items now. I'm stoked 👍
