### ISSUE TITLE
could not find extension's manifest file Domain

### ISSUE THREAD

**Issue by yazaldefilimone** [raycast/extensions#12658]
### Description

Reason: Could not find extension's manifest file
Domain: commands
Time: 11:36:30.299
Recovery: You might need to reinstall the extension.

**Comment by sxn** [comment]
Raycast throws that error when it tries to launch an extension but can't find its `package.json` file. Extensions get installed in `~/.config/raycast/extensions/`, so maybe something happened to that folder?

**Comment by yazaldefilimone** [comment]
> Raycast throws that error when it tries to launch an extension but can't find its `package.json` file. Extensions get installed in `~/.config/raycast/extensions/`, so maybe something happened to that folder?

![CleanShot 2024-05-31 at 11 00 51@2x](https://github.com/raycast/extensions/assets/78354432/ae64c132-7f93-4e3b-92e2-734a921a9387)

**Comment by yazaldefilimone** [comment]
Hi @vivgui, it worked after I deleted all the extensions and reinstalled them.
