### ISSUE TITLE
[GitHub] Api limits reached when viewing own PRs

### ISSUE THREAD

**Issue by DTchebotarev** [raycast/extensions#12664]
### Extension

https://raycast.com/raycast/github

### Raycast Version

1.75.2

### macOS Version

14.5

### Description

I get an error when viewing my PRs using the github extension. I suspect it's due to the sheer number of PRs I get subscribed to. The query below is one example but I've seen this error multiple times with multiple different queries (e.g. in different repositories, etc.). Pasting in several errors as examples.

![image](https://github.com/raycast/extensions/assets/6100882/47780370-932d-4fca-b715-e4fd41566900)

#### Error:
```
Error: Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `CFFD:3EF28A:4698D9:811EBA:66588DF3` when reporting this issue.: {"response":{"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `CFFD:3EF28A:4698D9:811EBA:66588DF3` when reporting this issue."}],"status":502,"headers":{}},"request":{"query":"query searchRepositories($query: String!, $numberOfItems: Int!) {\n  search(query: $query, first: $numberOfItems, type: REPOSITORY) {\n    nodes {\n      ...ExtendedRepositoryFields\n    }\n  }\n}\n\nfragment ExtendedRepositoryFields on Repository {\n  id\n  nameWithOwner\n  name\n  owner {\n    login\n    avatarUrl(size: 64)\n  }\n  url\n  mergeCommitAllowed\n  squashMergeAllowed\n  rebaseMergeAllowed\n  updatedAt\n  pushedAt\n  stargazerCount\n  isArchived\n  isFork\n  viewerHasStarred\n  primaryLanguage {\n    id\n    name\n    color\n  }\n  hasIssuesEnabled\n  hasWikiEnabled\n  hasProjectsEnabled\n  hasDiscussionsEnabled\n  releases {\n    totalCount\n  }\n}","variables":{"query":"user:@me org:REDACTED archived:false sort:updated-desc","numberOfItems":100}}}
    at /Users/dmitri/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:207:49846
    at p (/Users/dmitri/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:207:43252)
    at Object.next (/Users/dmitri/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:207:42556)
    at u (/Users/dmitri/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:207:42114)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

#### Another example error:
```
Error: GraphQL Error (Code: 403): {"response":{"documentation_url":"https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits","message":"You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID D0C8:59B46:476F62:826C19:66588F3F.","status":403,"headers":{}},"request":{"query":"query searchRepositories($query: String!, $numberOfItems: Int!) {\n  search(query: $query, first: $numberOfItems, type: REPOSITORY) {\n    nodes {\n      ...ExtendedRepositoryFields\n    }\n  }\n}\n\nfragment ExtendedRepositoryFields on Repository {\n  id\n  nameWithOwner\n  name\n  owner {\n    login\n    avatarUrl(size: 64)\n  }\n  url\n  mergeCommitAllowed\n  squashMergeAllowed\n  rebaseMergeAllowed\n  updatedAt\n  pushedAt\n  stargazerCount\n  isArchived\n  isFork\n  viewerHasStarred\n  primaryLanguage {\n    id\n    name\n    color\n  }\n  hasIssuesEnabled\n  hasWikiEnabled\n  hasProjectsEnabled\n  hasDiscussionsEnabled\n  releases {\n    totalCount\n  }\n}","variables":{"query":"user:@me org:instacart archived:false sort:updated-desc","numberOfItems":100}}}
    at /Users/dmitri/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:207:49846
    at p (/Users/dmitri/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:207:43252)
    at Object.next (/Users/dmitri/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:207:42556)
    at u (/Users/dmitri/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/my-pull-requests.js:207:42114)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

1/ Open raycast
2/ Use "my pull requests" command

**Comment by thomaslombart** [comment]
We're doing 10 concurrent calls under the hood to get your relevant PRs, it's looking like so:

```tsx
      const results = await Promise.all(
        [
          `is:pr author:@me archived:false is:open ${updatedFilter} ${repositoryFilter}`,
          `is:pr author:@me archived:false is:closed ${updatedFilter} ${repositoryFilter}`,
          `is:pr assignee:@me archived:false is:open ${updatedFilter} ${repositoryFilter}`,
          `is:pr assignee:@me archived:false is:closed ${updatedFilter} ${repositoryFilter}`,
          `is:pr mentions:@me archived:false is:open ${updatedFilter} ${repositoryFilter}`,
          `is:pr mentions:@me archived:false is:closed ${updatedFilter} ${repositoryFilter}`,
          `is:pr review-requested:@me archived:false is:open ${updatedFilter} ${repositoryFilter}`,
          `is:pr review-requested:@me archived:false is:closed ${updatedFilter} ${repositoryFilter}`,
          `is:pr reviewed-by:@me archived:false is:open ${updatedFilter} ${repositoryFilter}`,
          `is:pr reviewed-by:@me archived:false is:closed ${updatedFilter} ${repositoryFilter}`,
        ].map((query) => github.searchPullRequests({ query, numberOfItems: 20 })),
      );
```

Knowing we only take into accounts PRs that have been updated in the last two weeks. Could there be any one of these calls that's failing for you?

**Comment by antonengelhardt** [comment]
@thomaslombart @xilopaint 

https://github.com/raycast/extensions/pull/11653#issuecomment-2068884664

**Comment by j3lte** [comment]
@thomaslombart wouldn't it make more sense to reduce the calls by redefining the queries?

```
`is:pr author:@me archived:false is:open ${updatedFilter} ${repositoryFilter}`,
`is:pr author:@me archived:false is:closed ${updatedFilter} ${repositoryFilter}`,
```

could be rewritten as 

```
`is:pr author:@me archived:false is:open,closed ${updatedFilter} ${repositoryFilter}`,
```

We could then reduce this to 5 calls (maybe increase `numberOfItems`?)

**Comment by DTchebotarev** [comment]
Thanks for the attention folks. 

> Could there be any one of these calls that's failing for you?

Maybe? How can I test this? I do notice it's often a different api call that fails. Are there local logs I can access to see which queries are failing? 

> Knowing we only take into accounts PRs that have been updated in the last two weeks.

In my org the number of PRs that I get requested for review on is huge, on the order of 100 a day (because of very large teams being codeowners for very large areas of code). So two weeks is potentially 2k PRs. If it's really iterating over each PR like the comment @antonengelhardt linked suggests, then I am not surprised that it's exceeding some github rate limit.

Really I'm not interested in those PRs (it's 99% noise) so I think I could work around the rate limit if I could just disable certain queries, i.e.

```ts
          `is:pr review-requested:@me archived:false is:open ${updatedFilter} ${repositoryFilter}`,
          `is:pr review-requested:@me archived:false is:closed ${updatedFilter} ${repositoryFilter}`,
```

In an ideal world of course I could return the PRs where I have been requested as a reviewer personally and ignore where (one of) my (many) team(s) was requested, but I don't think that github supports such functionality.

**Comment by antonengelhardt** [comment]
The rate limit for the API is [5k request per hour.](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users)

My first ideas to solve this are:

- a setting to define a rate limit for raycast which controls how often the state is updated
- a setting to define an interval which controls how often the state is reloaded

Both could be done as well, but they would have to be mutually exclusive

**Comment by DTchebotarev** [comment]
According to [SO](https://stackoverflow.com/questions/75115326/github-view-prs-where-i-am-directly-requested-and-not-my-team), there's actually a different query we can use to only fetch review requests by name not by team. So 

```ts
          `is:pr review-requested:@me archived:false is:open ${updatedFilter} ${repositoryFilter}`,
          `is:pr review-requested:@me archived:false is:closed ${updatedFilter} ${repositoryFilter}`,
```

would become

```ts
          `is:pr user-review-requested:@me archived:false is:open,closed ${updatedFilter} ${repositoryFilter}`,
```

Thoughts about putting this behind an option? Something like "ignore team review requests". If this is relatively straightforward I can put up the PR.

**Comment by antonengelhardt** [comment]
Good idea! Options sounds great too. If you merge two queries into, you have to do the partition yourself, like [here](https://github.com/raycast/extensions/blob/main/extensions/github/src/notifications.tsx#L39)

**Comment by DTchebotarev** [comment]
I tried to take a stab (draft PR https://github.com/raycast/extensions/pull/12775) but I'm really confused by the behavior I'm seeing. I keep seeing this error:

```
[0] 17:53:25.665 ClientError2: Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `3401:3D9BEB:56D8F84:98B969A:665F8CCB` when reporting this issue.: {"response":{"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `3401:3D9BEB:56D8F84:98B969A:665F8CCB` when reporting this issue."}],"status":502,"headers":{}},"request":{"query":"query searchRepositories($query: String!, $numberOfItems: Int!) {\n  search(query: $query, first: $numberOfItems, type: REPOSITORY) {\n    nodes {\n      ...ExtendedRepositoryFields\n    }\n  }\n}\n\nfragment ExtendedRepositoryFields on Repository {\n  id\n  nameWithOwner\n  name\n  owner {\n    login\n    avatarUrl(size: 64)\n  }\n  url\n  mergeCommitAllowed\n  squashMergeAllowed\n  rebaseMergeAllowed\n  updatedAt\n  pushedAt\n  stargazerCount\n  isArchived\n  isFork\n  viewerHasStarred\n  primaryLanguage {\n    id\n    name\n    color\n  }\n  hasIssuesEnabled\n  hasWikiEnabled\n  hasProjectsEnabled\n  hasDiscussionsEnabled\n  releases {\n    totalCount\n  }\n}","variables":{"query":"user:@me org:instacart archived:false sort:updated-desc","numberOfItems":100}}}
[0]     at /Users/dmitri/.config/raycast/extensions/github/my-pull-requests.js:32939:23
[0]     at step (/Users/dmitri/.config/raycast/extensions/github/my-pull-requests.js:32611:23)
[0]     at Object.next (/Users/dmitri/.config/raycast/extensions/github/my-pull-requests.js:32558:18)
[0]     at fulfilled (/Users/dmitri/.config/raycast/extensions/github/my-pull-requests.js:32529:28)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[0]   response: {
[0]     data: null,
[0]     errors: [ [Object] ],
[0]     status: 502,
[0]     headers: Headers3 [Headers] { [Symbol(map)]: [Object: null prototype] }
[0]   },
[0]   request: {
[0]     query: 'query searchRepositories($query: St<...>
```

This is confusing to me because the query that seems to fail is `searchRepositories` but that's not related to the "my pull requests" command?

**Comment by antonengelhardt** [comment]
Just to be sure, you have used a PAT or logged in to the development version of the command?

**Comment by DTchebotarev** [comment]
I did log in to the dev version and the dev version does show the correct PRs - but for some reason I see the search repositories query.

**Comment by antonengelhardt** [comment]
sorry for the delay.

i checked out your branch and it works for me...

![Screenshot-Code-007465@2x](https://github.com/raycast/extensions/assets/106314688/d686c09f-a3e6-43dd-b014-3baaa1e77639)

and these are my settings

![Screenshot-Raycast-007467@2x](https://github.com/raycast/extensions/assets/106314688/a6bb8abf-9187-4a92-b049-650053adb074)

or am i doing something wrong?

**Comment by DTchebotarev** [comment]
I also get my PRs loading correctly, but then I get an additional error (https://github.com/raycast/extensions/issues/12664#issuecomment-2148482962) from the searchRepositories query. What's confusing to me is where the `searchRepositories` query comes from when viewing my PRs.

**Comment by antonengelhardt** [comment]
I don't get that error :(

**Comment by jfkisafk** [comment]
We've already merged the changes that @DTchebotarev was working on in an adjacent pr: https://github.com/raycast/extensions/pull/13043. Please re-open this issue in case the issue still persists.

**Comment by jfkisafk** [comment]
@raycastbot close this issue

**Comment by jfkisafk** [comment]
@raycastbot assign me
