### ISSUE TITLE
[Deepcast] 'View in Raycast' Option Fails When "Translate" Command is Disabled

### ISSUE THREAD

**Issue by kridijaw** [raycast/extensions#12662]
### Extension

https://www.raycast.com/mooxl/deepcast

### Raycast Version

1.75.2

### macOS Version

14.5

### Description

Disabling the "Translate" command causes any "Translate Into [Language]" command to return an error.

### Steps To Reproduce

1. Go to Raycast Settings > Extension > Deepcast.
2. Select "On Translation Action" and choose "View in Raycast".
3. Go to Raycast Settings > Extension > Deepcast > Translate.
4. Disable the "Translate" command.

### Current Behaviour

Using any "Translate into [Language]" command results in the error message: "Something went wrong. Unknown error."

### Expected Behaviour

Either display the translated input in Raycast or provide feedback indicating that the "Translate" command needs to be enabled.

**Comment by erics118** [comment]
The `Translate` has to be enabled in order for the` Translate into...` commands to work.

in depth explanation: This is because the `Translate into...` commands are `no-view`, so it has to call the `Translate` command which is a `view` command in order to show the view.
