### ISSUE TITLE
[YouTrack] Add feature to browse issues with saved searches 

### ISSUE THREAD

**Issue by snpefk** [raycast/extensions#12663]
### Extension

https://www.raycast.com/tiulpin/youtrack

### Description

Hi! Thanks for your effort.

Often, when working with YouTrack, you have different saved searches like “Reported by me,” “Assigned to me,” or the entire backlog of your project. It would be nice to switch between different saved search options, not just one in “Browse Issues.”

### Who will benefit from this feature?

me :) 

### Anything else?

no

**Comment by TyceHerrman** [comment]
This is still relevant afaik. Browse Issues still supports only one configured Query, so switching between assigned issues, reported issues, project backlogs, or other reusable views requires editing the command settings.

A query selector could expose multiple saved searches while retaining the configured Query as the default view.

@skoch13 @tiulpin I’m interested in working on implementing this - and if that's good by you can we reopen this?
