### ISSUE TITLE
[Guerrilla Mail] Raycash Refresh

### ISSUE THREAD

**Issue by anongecko** [raycast/extensions#12666]
### Refresh Option

https://www.raycast.com/krsntn/guerrilla-mail

### Description

It'd be really nice if one of the actions (on top of show mailbox) was a refresh option. I think it'd add a lot to the extension.

### Who will benefit from this feature?

Everyone.

**Comment by anongecko** [comment]
> We could not find the extension related to this issue. Please update the issue with the link to the extension.

Wdym it is labeled and has a link to the extension.

**Comment by krsntn** [comment]
Thank you for the suggestion! The extension already includes a refresh option in the actions menu, and you can also use the shortcut (cmd + r) to trigger the refresh function. Given these existing methods, adding a refresh action on top of showing the mailbox isn't necessary.
