### ISSUE TITLE
[Copy Path] Copy Path does not get URL from Little Arc

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#12677]
### Extension

https://www.raycast.com/koinzhang/copy-path

### Raycast Version

1.75.2

### macOS Version

14.5 (23F79)

### Description

I am unable to use Copy Path via keyboard shortcut to get the current URL of the frontmost Little Arc window. 

Ideally I would be able to set a global hotkey to grab the URL/Path of whatever I'm looking at, since I use Arc's `Copy URL` keyboard shortcut dozens of times a day.

Moving this function to Raycast would be incredibly convenient — but not without adding support for Little Arc windows.

--

**Feature suggestion:** It may make sense to reverse the logic of this extension to start w/ browsers and then fall back to Finder in terms of the copy path priority, or to offer the option to prioritize browsers over Finder.

### Steps To Reproduce

1. Enable Raycast Copy Path extension and set keyboard shortcut to ⇧⌘C
2. Open Arc and pull up a URL in the main window (e.g. raycast.com)
3. Open a Little Arc window and go to a URL (e.g. perplexity.com)
4. Hit ⇧⌘C
5. Inspect your clipboard to see which URL was copied.

### Current Behaviour

The URL from the main Arc window will have been copied (raycast.com), not the Little Arc URL (perplexity.com).

### Expected Behaviour

The URL from the Little Arc window should have been copied.

**Comment by koinzhang** [comment]
Hi @chrismessina The inability to copy Little Arc's URLs is not due to priority, but because Little Arc is a custom window view for Arc (not natively supported by Chromium), and Little Arc is not perceived through Raycast's Api or Applescript, so it is not possible to copy page URLs

**Comment by chrismessina** [comment]
Let me reach out to someone on the Arc team...

**Comment by chrismessina** [comment]
The Arc team is aware of it and may work on it soon.

**Comment by thomasmaherault** [comment]
@chrismessina Do you have any updates from the Arc team on this?

**Comment by chrismessina** [comment]
> @chrismessina Do you have any updates from the Arc team on this?

Lemme go ping @robotdestroy.
