### ISSUE TITLE
[Set Audio Device]... fails to fetch output device

### ISSUE THREAD

**Issue by ferd-az** [raycast/extensions#12672]
### Extension

https://raycast.com/benvp/audio-device

### Raycast Version

1.75.1

### macOS Version

14.4.1

### Description

The 'Set Output Device' simply isn't working. When you run the command the extension loads but fails to show the the output devices 

<img width="862" alt="Screenshot 2024-05-30 at 12 06 46 PM" src="https://github.com/raycast/extensions/assets/131395058/6c564891-a38c-4ae7-8be5-2e52c82fd561">

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    set devices to {}

    tell application "System Preferences"
      reveal pane id "com.apple.preference.sound"
    end tell
    tell application "System Events"
      tell application process "System Preferences"
        repeat until exists tab group 1 of window "Sound"
        end repeat
        tell tab group 1 of window "Sound"
          click radio button "Output"
          tell table 1 of scroll area 1
            set selected_row to (first UI element whose selected is true)
            set currentOutput to value of text field 1 of selected_row as text
            
            repeat with r in rows
              try
                set deviceName to value of text field 1 of r as text
                set deviceType to value of text field 2 of r as text
                set end of devices to { deviceName, deviceType }
              end try
            end repeat
          end tell
        end tell
      end tell
    end tell

    if application "System Preferences" is running then
      tell application "System Preferences" to quit
    end if
    
    return [ devices, "currentOutput", currentOutput ]
   
64:116: execution error: System Settings got an error: Can’t get pane id "com.apple.preference.sound". (-1728)
    at _t (/Users/ferdiaz/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:5:57)
    at /Users/ferdiaz/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:5:6400
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ca (/Users/ferdiaz/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:41:6806)
    at async b0 (/Users/ferdiaz/.config/raycast/extensions/2158713f-4712-4862-ba9a-3bce3cd07e3a/set-output-device.js:41:6981)
```

### Steps To Reproduce

1. Open Raycast ⌥+Space
2. Exec "Set Output Device" command

### Current Behaviour

you get no results when executing the command 

<img width="862" alt="Screenshot 2024-05-30 at 12 03 20 PM" src="https://github.com/raycast/extensions/assets/131395058/172253a0-2d42-4574-9e9d-29a13e1d17c8">

### Expected Behaviour

i would expect to see a list of devices just as you do when using "Set Input Device" 

<img width="862" alt="Screenshot 2024-05-30 at 12 04 36 PM" src="https://github.com/raycast/extensions/assets/131395058/46f55021-3759-4622-9442-67cab40dbc4a">

**Comment by antonengelhardt** [comment]
+1

**Comment by JoeRoddy** [comment]
For me, it's showing my MBP speakers, but not any Airplay devices:

![Screenshot 2024-06-21 at 9 50 13 AM](https://github.com/raycast/extensions/assets/16690442/696f36b9-3b56-41f8-b168-2a518f7f7018)

**Comment by antonengelhardt** [comment]
Keep it open
