### ISSUE TITLE
[Slack] ... is it possible to have this extension configurable to open on browser instead?

### ISSUE THREAD

**Issue by ariccb** [raycast/extensions#12676]
### Extension

https://www.raycast.com/mommertf/slack

### Raycast Version

1.75.1

### macOS Version

14.5 (23F79)

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    tell application "Slack"
      if not application "Slack" is running then
        activate
        set _maxOpenWaitTimeInSeconds to 5
        set _openCounter to 0
        repeat until application "Slack" is running
          delay 0.5
          set _openCounter to _openCounter   0.5
          if _openCounter > _maxOpenWaitTimeInSeconds then exit repeat
        end repeat

        delay 6

        # Exit 'Set yourself to active?' window
        activate
        tell application "System Events"
          key code 53
        end tell
      end if
      activate
      
      tell application "System Events" to tell process "Slack" to keystroke "A" using {command down, shift down}
    
    end tell
87:95: execution error: Can’t get application "Slack". (-1728)

    tell application "Slack"
      if not application "Slack" is running then
        activate
        set _maxOpenWaitTimeInSeconds to 5

```

I'm hoping to configure the Extension to be able to open the links in slack on the browser instead of needing the desktop application. 
It's sending a link `slack://channel?team=<team-id>/&id=<channel-id>` but i want it to open `https://app.slack.com/client/<team-id>/<channel-id>` instead

### Steps To Reproduce

works when I have slack desktop installed
doesn't work when i uninstall it

### Current Behaviour

sends me an error ```Can’t get application "Slack". (-1728)```

### Expected Behaviour

open in my default browser

**Comment by jfkisafk** [comment]
@raycastbot assign me
