### ISSUE TITLE
[Jira] ... If I search the ticket number without the project prefix, it shows no result found

### ISSUE THREAD

**Issue by jithendran-design** [raycast/extensions#12674]
### Extension

https://www.raycast.com/raycast/jira

### Raycast Version

1.75.2

### macOS Version

Sonoma 14.4.1 (23E224)

### Description

[Jira] ... If I search the ticket number without the project prefix, it shows no result found

### Steps To Reproduce

Go to Jira search issues
search with ticket id number alone without the prefix

### Current Behaviour

If I search the ticket number without the project prefix, it shows no result found

### Expected Behaviour

It should show the relevant tickets even if just the number is provided

**Comment by mikybars** [comment]
Can this be a bug in Raycast itself? I ran some queries against an issue's keywords and they only matched when the keyword  _started_ with the query, not even a substring. That doesn't seem to be what the API docs promise:

https://developers.raycast.com/api-reference/user-interface/list#search-bar

>The search bar allows users to interact quickly with list items. By default, [List.Items](https://developers.raycast.com/api-reference/user-interface/list#list.item) are displayed if the user's input can be (fuzzy) matched to the item's title or keywords.

**Comment by thomaslombart** [comment]
@jithendran-design Could you share a recording? It'll make it easier to see what's happening.

**Comment by mikybars** [comment]
<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/43891734/9fd417e1-ba72-4f66-bea2-8787e4490bac">
<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/43891734/372e3a28-8e9c-4e51-90f5-240e12e52e0a">
<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/43891734/f9801613-db6d-4077-8d9c-41b412f369d3">

**Comment by thomaslombart** [comment]
It's not a bug in Raycast because we're making a custom search using Jira's endpoints here. We probably need to do it the custom way like it's been done [here](https://github.com/raycast/extensions/blob/50b5fd0a93540e6365db07b49af5cdf4e3b7058f/extensions/jira/src/search-issues.tsx). Does one of you want to look at it? 🙂
