### ISSUE TITLE
[Taskwarrior] fails to parse task JSON after upgrading to Taskwarrior v3.0, if you leave the old .data files behind

### ISSUE THREAD

**Issue by sinewalker** [raycast/extensions#12680]
### Extension

https://www.raycast.com/yosy2010/raytaskwarrior

### Raycast Version

1.75.2

### macOS Version

14.5

### Description

After upgrading to Taskwarrior v 3.0.2 and exporting/importing tasks to the new database format, the Raycast integration can no longer list my tasks:

  
<img width="797" alt="image" src="https://github.com/raycast/extensions/assets/124139/6696a702-6327-4e9d-b193-2826cf9628bc">

- The error message is misleading:  the path to `task` is unchanged and set correctly:

```
~► which task 
/opt/homebrew/bin/task
```

Instead, I believe that the JSON is no longer parsing correctly with the new version of Taskwarrior.  The error appears to be coming from [line 23 in the api.ts file](https://github.com/raycast/extensions/blob/e9ae8d9bd61c2412e9432d35631f8d7284776f1d/extensions/raytaskwarrior/src/api.ts#L23) ([upstream](https://github.com/AltamimiYasser/raycast-extensions/blob/ext/raytaskwarrior/extensions/raytaskwarrior/src/api.ts#L23)).

```typescript
    const data = JSON.parse(stdout) as Task[];
    if (data) tasks = data.sort((a, b) => b.urgency - a.urgency);
  } catch (error) {
    throw new Error("Please make sure you have set the path to task in the settings");
```

Version 3.0 of Taskwarrior is a [breaking change](https://taskwarrior.org/docs/upgrade-3/). The format of the task database was changed, but this should be transparent to the extension.

I think what has happened is that the `task` command will display this warning, which is breaking the extension:

```text
~► task export rc.json.array:on > tasks.json
Found existing '.data' files in /Users/mjl/net/MEGA/task
  Taskwarrior's storage format changed in 3.0, requiring a manual migration.
  See https://github.com/GothenburgBitFactory/taskwarrior/releases.
Configuration override rc.json.array:on 
```

## Workaround

- Remove the `.data` files from your taskwarrior data directory

### Steps To Reproduce

1. In a system which has upgraded from Taskwarrior v2.x to v3.x, and has `.data` files left from the export/import
2. Run the command "List Active Tasks"
3. See error in Description
4. Run [the `task` command executed by the extension](https://github.com/AltamimiYasser/raycast-extensions/blob/ext/raytaskwarrior/extensions/raytaskwarrior/src/api.ts#L10) from a terminal
5. See the error message displayed by `task`
6. Remove the `.data` files as advised
7. Extension working as expected

### Current Behaviour

The extension errors with "Please make sure you have set the path to task in the settings" even when the path is correct

### Expected Behaviour

The extension should either explicitly state there was a problem parsing the JSON output by `task` (rather than assume all errors are because of a misconfiguration), or produce the error thrown by the command in some sort of pop-up display, for the user to diagnose and fix.

**Comment by uhkeller** [comment]
I have this problem with a fresh install of Taskwarrior (3.0.2). `task` does not display any errors, there is no `.data` file I could remove to work around this bug. The path is set correctly in the extension.

**Comment by sinewalker** [comment]
@uhkeller Could you try running the `task` command which the Taskwarrior Raycast extension is running, to see what error it produces? That could reveal what the problem actually is. I suspect that if you don't have a `.data` file, then you did not upgrade from an earlier Taskwarrior, so you might have a different problem.

```shell
task export rc.json.array:on > tasks.json
```

(disclaimer:  I am _not_ the extension's creator/maintainer)

**Comment by uhkeller** [comment]
Thanks for your response, @sinewalker. There is no error running this command, just the override message `Configuration override rc.json.array:on`. If i disable override messages in `.taskrc` the message is gone from terminal output put the extension still doesn't work.

**Comment by sinewalker** [comment]
How strange!

I wonder whether there is something causing a delay that the extension doesn't wait for? (I'm just guessing now).

Is your `data.location` on a network volume or something which might be intermittently slow? If so, try moving it locally and see if it helps. If not... I don't know

**Comment by uhkeller** [comment]
Strange indeed. No, the data are in the default location on my SSD. I'll try to find some time to properly debug this next week.

**Comment by uhkeller** [comment]
I've decided to downgrade to Taskwarrior 2 until taskwarrior-flutter and/or WingTask have caught up with TW 3. This also solves my Raycast problem for now.
