### ISSUE TITLE
[Toggle Audio Input (Microphone)]  Show/hide icon preference works vice versa.

### ISSUE THREAD

**Issue by aliaksandrZh** [raycast/extensions#12684]
### Extension

https://www.raycast.com/Quentin23Soleil/mute-microphone

### Raycast Version

1.75.2

### macOS Version

14.5

### Description

#
Bugs listed below were found after the last PR https://github.com/raycast/extensions/pull/12614
> when i toggle it with keyboard shortcut it is also triggered raycast (the search bar is showed up)

> it is quite annoying that the raycast window opens afterward.

> and the option I had added doesn't work as expecte
> ![image](https://github.com/raycast/extensions/assets/108681764/875a698a-cd7e-4444-b219-3d7444cf0598)

### Steps To Reproduce

Run Toggle command  with a keyboard shortcut. 

### Current Behaviour

Raycast is open

### Expected Behaviour

Raycast should not be open

**Comment by aliaksandrZh** [comment]
@raycastbot  assign me

**Comment by iamyeizi** [comment]
@raycastbot close this issue
