### ISSUE TITLE
[Change Case] Remove redundant transformations

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#12697]
### Extension

https://www.raycast.com/erics118/change-case

### Description

On the [Change Case Store listing](https://www.raycast.com/erics118/change-case), several transformations are listed as redundant:

<details>
<summary>Transformations</summary>

- camelCase
- Capital Case
- **CONSTANT_CASE (same as MACRO_CASE)**
- dot.case
- **Header-Case (same as Train-Case)**
- **kebab-case (same as param-case)**
- lower case
- lower First
- **MACRO_CASE (same as CONSTANT_CASE)**
- no case
- **param-case (same as kebab-case)**
- PascalCase
- Pascal_Snake_Case
- path/case
- **rAndOm cAsE (same as SPonGE CasE)**
- Sentence case
- snake_case
- sWAP cASE
- Title Case
- UPPER CASE
- Upper first
- **SPonGE CasE (same as rAndOm cAsE)**
- **Train-Case (same as Header-Case)**

</details>

In the extension settings, however, there is no indication of this redundancy:

![2024-05-31 (12 24 42) Raycast](https://github.com/raycast/extensions/assets/22610/1053a0d5-58dd-4439-a65d-21485bd4a3dd)

I understand that this extension is built around the underlying capabilities of the [change-case](https://github.com/blakeembrey/change-case) package, which targets technical users or developer cases, as @blakeembrey [says](https://github.com/blakeembrey/change-case/blob/main/packages/change-case/README.md) "Change case assumes you are switching between different programming cases".

While Raycast users are likely more technical, some of the nuances of these cases may be lost on everyday Raycast users, and so simplifying the extension to the most common cases may be preferable.

Therefore, by default, it seems that the Raycast Change Case Extension should offer these and only these transformations by default:

- camelCase
- Capital Case
- CONSTANT_CASE
- dot.case
- Header-Case
- lower case
- lower First
- no case
- param-case
- PascalCase
- Pascal_Snake_Case
- path/case
- rAndOm cAsE
- Sentence case
- snake_case
- sWAP cASE
- Title Case
- UPPER CASE
- Upper first

-- 

I will also propose making use of additional features offered by the [change-case](https://github.com/blakeembrey/change-case) package to handle some of the capitalization concerns that have been brought up elsewhere, as well as to increase the number of words used in the transformation examples.

### Who will benefit from this feature?

General users of the Change Case extension.

**Comment by erics118** [comment]
The lack of indication of redundancy in the preferences was a complete oversight on my side. The duplication of these transformations has been in the code since the very first version, but I never thought to explicitly clarify that there were duplicates. I just recently with the latest commit added the detailed store listing (which is just the README.md). 

I'll remove the redundancy as I doubt it would affect too many people.

**Comment by PWrzesinski** [comment]
@chrismessina @erics118 hello, as an example of a person who's used one of the removed cases recently, the kebab-case, could I ask if there is really anything wrong with having duplicates?

I mean what's the benefit of removing them? I don't think it affects readability of the options in a significantly negative way?

Personally I'd prefer just a simple clarification.

**Comment by chrismessina** [comment]
@PWrzesinski can you clarify? My understanding is that there are duplicate transformations with different names. That is, you can achieve the `kebab-case` transformation with `param-case`, so removing `kebab-case` doesn't result in a loss of functionality.

Reducing the number of options without losing functionality should streamline the UI, make it easier to maintain, and make it more approachable to new users.

One option could be to move these synonyms to the tooltip:

![2024-06-03 (12 27 59) Raycast](https://github.com/raycast/extensions/assets/22610/6ed8ae8f-874b-4240-8b0f-1b13a6b587dd)

So instead of: 

"Enable the "param-case" Transformation"

The tooltip would read:

"Enable the "param-case" Transformation, also known as kebab-case."

**Comment by PWrzesinski** [comment]
Yes, I understand that these are duplicates, however I remember this particular transformation as "kebab case", not "param case" and "kebab case" is what I'm looking for in the list of transformations when I want to apply it. That's why my personal preference would be to just disable it by default instead of removing it completely. Also I think parametrization instead of imposed decisions is a generally good approach with Raycast's diverse user base, but this is just my opinion.

We could also clarify everywhere that these are duplicates, if that improves UX.

**Comment by chrismessina** [comment]
One more proposal then: merge equivalent transformations on one line:

- camelCase
- Capital Case
- CONSTANT_CASE / MACRO_CASE
- dot.case
- Header-Case / Train-Case
- kebab-case / param-case
- lower case
- lower First
- no case
- PascalCase
- Pascal_Snake_Case
- path/case
- rAndOm cAsE / SPonGE CasE
- Sentence case
- snake_case
- sWAP cASE
- Title Case
- UPPER CASE
- Upper first

These could be formatted as: 

- `Name` (`Alternative Name`)
- `Name` / `Alternative Name`
- `Name` or `Alternative Name`

**Comment by erics118** [comment]
I've added support for some aliases of names, especially for the cases that were removed.

![CleanShot 2024-06-03 at 18 38 09](https://github.com/raycast/extensions/assets/52634785/c0fbde81-8dd1-4c44-aa45-8eab6aefee0a)

Also renamed the transformation from param case to kebab case bc mOst people I know also know it as kebab case, not param case.
