### ISSUE TITLE
[Change Case] Allow user to set a list of smallWords exceptions to transformation rules

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#12698]
### Extension

https://www.raycast.com/erics118/change-case

### Description

The [title-case](https://github.com/blakeembrey/change-case/blob/main/packages/title-case/README.md) package offers the ability to except a list of words from the title-case transformation:

`smallWords?: Set <string>` Set of words to keep lower-case when `sentenceCase === false` (default: `SMALL_WORDS`) 

Considering some of the [confusion in how the Change Case extension behaves by default](https://github.com/raycast/extensions/issues/11878#issuecomment-2142852910), the combination of lowercasing all text by default coupled with the ability to create a list (perhaps one per line) of `smallWords` or exceptions might lead to the best performance of this extension.

I'm not sure the best way to include a list of such words, but I can imagine that by default, a plain text dictionary could be provided with the extension for common or familiar words whose capitalization should be preserved (e.g. iPhone). This list should be user editable so that they can add their own capitalization word or phrase exceptions (e.g. "Whole Foods" vs "whole foods"). The list could be editable directly from the Change Case settings UI or by executing a command to edit the Change Case Dictionary.

### Who will benefit from this feature?

Anyone that uses the Change Case extension and is frustrated by its current behavior.

### Anything else?

That the underlying Change Case/Title Case package provides a way to tweak its behavior suggests that this kind of customization is common enough to be surfaced to Raycast users.

**Comment by erics118** [comment]
I definitely agree such an addition would be great to add. I can definitely add a preference. But, that would mean it would get difficult to configure a lot of these smallWords. I'm not sure how much this preference would be used, or if it is important enough to require a new command to be added.

**Comment by chrismessina** [comment]
I understand. I wonder if it would get much use... but I'm also looking at the other issues that people have submitted and it seems that changing the default to lowercase-by-default AND adding a way to except a list of words/phrases would make this extension supremely valuable!

To keep it simple, you could let a user import or export a basic .txt file with a list of words or phrases separated by new lines. You could model this after Raycast's "Import Settings & Data".

This way, users could collaborate on a list of "stop words" that would resist transformation... 

It seems somewhat straightforward since the Change Case package already supports this method?

**Comment by erics118** [comment]
I hesitate to add a whole new command to the extension, just for this relatively niche use case. I think for now, we can go with just have a text preference value, so users can input words separated by commas.

**Comment by erics118** [comment]
BTW, smallWords is only for title/sentence case
https://github.com/blakeembrey/change-case/blob/main/packages/title-case/README.md

**Comment by erics118** [comment]
I've added the preference in the latest commit. Not sure if we should really call it "small words" as even though that is how the library calls it, it's better used for things like iPhone, etc.

**Comment by PWrzesinski** [comment]
Will chime in as I'm getting notifications about this discussion. Sounds like "ignored words" would be better? Love that this extension is improving, I think I use this one most often! LMK if I can help in any way.

**Comment by chrismessina** [comment]
@erics118 just so you understand my style of contribution — I'm satisfied talking through things and getting pushback, especially on implementation considerations. I'm not writing the code, so will take what I can get! 

As for writing a new function — yep, a comma-separated list of words/phrases captured in a text input works just as well. I'm imagining that such lists _could_ get long, but I suppose we cross that bridge if we come to it.

"Small words" is not a clear label. Suggestions:

- Do Not Transform
- Exceptions
- Ignore
- Never transform
- Keep Original Case
- Preserve Case

**Comment by erics118** [comment]
I've decided to go with `Exceptions`. Here's an example of the UI for the new preference:

![CleanShot 2024-06-01 at 22 15 52](https://github.com/raycast/extensions/assets/52634785/7fd9f03c-f49c-4c1b-951c-b6e9f4fce4a0)

![CleanShot 2024-06-01 at 22 15 47](https://github.com/raycast/extensions/assets/52634785/7490a08a-591e-49ce-b57e-2c959bac55cf)

**Comment by chrismessina** [comment]
May I propose: 

Title: Title and Sentence Case Exceptions
Default values: macOS, iOS, iPadOS, iPhone, watchOS, tvOS

Or you could make that list the default values. That way people learn by seeing examples.

If people remove those values, the Placeholder text could be: "Comma-separated list of words or phrases"

**Comment by erics118** [comment]
I've implemented your ideas.

![CleanShot 2024-06-03 at 18 40 05](https://github.com/raycast/extensions/assets/52634785/16e3ccc6-edc7-45a3-8ee3-3b19aafbe6bf)
![CleanShot 2024-06-03 at 18 40 09](https://github.com/raycast/extensions/assets/52634785/6212488b-c450-44b1-b59e-b2cf2995bded)

**Comment by chrismessina** [comment]
Love this!
