### ISSUE TITLE
[Arc] "Search" command always opens suggestions on Little Arc

### ISSUE THREAD

**Issue by Luk4h** [raycast/extensions#12706]
### Extension

https://www.raycast.com/the-browser-company/arc

### Raycast Version

1.75.2

### macOS Version

14.4.1

### Description

When using the "Search" command, and typing a text, that is not found, you receive suggestions which you may google related to your input. Even when selecting "Open in Arc" it opens a Little Arc window with the search.

![image](https://github.com/raycast/extensions/assets/78048969/538127ff-36f3-4e31-8780-d023c7fbe271)

![image](https://github.com/raycast/extensions/assets/78048969/26eda155-958a-4325-b01c-8180f1a09c0c)

![image](https://github.com/raycast/extensions/assets/78048969/f08f9f8e-c1ec-4987-b44c-1886836bffcb)

Current "Search Arc" command settings:
![image](https://github.com/raycast/extensions/assets/78048969/be093fd6-3608-45cc-a22c-1970caec1b6d)

### Steps To Reproduce

1. Open "Search Arc" command
2. Type a text
3. Select a suggestion
4. Select "Open in Arc"
5. Watch it open in "Little Arc" 🙂

### Current Behaviour

Even when selecting "Open in Arc" it opens in a "Little Arc" window.

### Expected Behaviour

Open a tab in the current Arc window.

**Comment by loris** [comment]
Hi @Luk4h
From my understanding, the current behavior looks correct:

- `Open in Arc` uses the default opening method that **you** set in Arc using that setting:
![Screenshot 2024-06-03 at 10 14 42@2x](https://github.com/raycast/extensions/assets/8362/351d4c12-9f74-43db-8bc0-ff6541d545c2)
If you enable it, `Open in Arc` will open in Little Arc, if you disable it, it will open in your default Space

- `Open in Little Arc` always open in little arc
- Finally, you still have the `Open in Space` actions to force opening the suggestions in the space of your choice:
![Screenshot 2024-06-03 at 10 16 32@2x](https://github.com/raycast/extensions/assets/8362/6da0159c-96e2-4dff-a509-348983c448c8)

Does it make sense?

**Comment by Luk4h** [comment]
I guess it does make sense. Thanks very much for clarifying.
