### ISSUE TITLE
[Spotify Player] A command to play the AI DJ

### ISSUE THREAD

**Issue by kud** [raycast/extensions#12719]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

It could be great to be able to have a command to start the AI DJ.

![CleanShot 2024-06-02 at 01 53 32@2x](https://github.com/raycast/extensions/assets/655838/4c76e253-7d40-411d-8f1c-d49b74d19c17)

### Who will benefit from this feature?

Everyone

**Comment by erics118** [comment]
I tried to do this, but unfortunately it doesn't seem like the spotify app likes doing this.

The URI for the DJ is `spotify:playlist:37i9dQZF1EYkqdzj48dyYq `, but doing a curl request like so:

```sh
curl --request PUT \
  --url https://api.spotify.com/v1/me/player/play \
  --header 'Authorization: Bearer D74...a04' \
  --header 'Content-Type: application/json' \
  --data '{
    "context_uri": "spotify:playlist:37i9dQZF1EYkqdzj48dyYq"
}'
```

doesn't seem to work.

**Comment by kud** [comment]
Feel like this guy has the same issue https://community.spotify.com/t5/Spotify-for-Developers/What-Spotify-Web-API-does-the-DJ-button-use/td-p/5660189

**Comment by erics118** [comment]
Yup, I saw that post.
