### ISSUE TITLE
New detail view components in List.Detail

### ISSUE THREAD

**Issue by devinhalladay** [raycast/extensions#1273]
**Describe the feature and the current behavior/state.**
I'd like to use the new add-on components available in `Detail` within `List.Item.Detail` to build rich previews of list items.

**Will this change the current API? How?**
Would involve porting the new Detail API to List.Item.Detail. Ideally though I'd love to be able to also render JSX inside the detail pane rather than just plain markdown.

**Who will benefit from this feature?**
Anyone who creates lists for quick workflows like triaging an inbox.

**Comment by mathieudutour** [comment]
The metadata view is now also available on `List.Item.Detail`
