### ISSUE TITLE
[Brave Search with Results]...

### ISSUE THREAD

**Issue by ryanrichardson3** [raycast/extensions#12733]
### Extension

https://raycast.com/electerious/brave-search-with-results

### Raycast Version

1.75.2

#### Error:
```
Error: Bad Request
    at Object.H6 [as current] (/Users/ryan/.config/raycast/extensions/489317da-ed78-4789-b69b-6f32d4baa18e/index.js:8:315661)
    at /Users/ryan/.config/raycast/extensions/489317da-ed78-4789-b69b-6f32d4baa18e/index.js:8:316523
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

Run Brave Search Suggestion

**Comment by electerious** [comment]
Can you be more precise in the "Steps To Reproduce" section? What are you typing? When exactly do you see the error?

**Comment by electerious** [comment]
@raycastbot close this issue
