### ISSUE TITLE
[Todoist] Add the label "focus" on tasks set as focus from Raycast

### ISSUE THREAD

**Issue by kud** [raycast/extensions#12730]
### Extension

https://www.raycast.com/doist/todoist

### 🧑 Story
Implement a feature where tasks marked as focus in Raycast are automatically labeled with "focus" in Todoist, ensuring users can easily identify and manage their priority tasks across both platforms.

### 🕵️‍♂️ Background/Context
Users often use Raycast to quickly mark tasks as focus. Syncing this status with Todoist by adding a "focus" label helps maintain consistency and improves task management efficiency. This feature enhances the user experience by providing seamless integration between the two tools.

### 🔨 Acceptance Criteria
- Tasks set as focus in Raycast must be labeled with "focus" in Todoist.
- Label must be applied automatically without manual intervention.
- Existing tasks in Todoist should not be affected unless marked as focus in Raycast.

### 🧪 Testing Criteria
- Verify that tasks marked as focus in Raycast are labeled with "focus" in Todoist.
- Test edge cases where multiple tasks are marked as focus simultaneously.
- Ensure no duplicate labels are created.
- Validate performance and synchronization speed.

### Who will benefit from this feature?

Everyone using the feature "focus".

**Comment by jfkisafk** [comment]
@raycastbot assign me

**Comment by jfkisafk** [comment]
@raycastbot assign me

**Comment by kud** [comment]
Thanks!
