### ISSUE TITLE
[Pass] Add possibility to use pass-otp extension

### ISSUE THREAD

**Issue by camiloaromero23** [raycast/extensions#12752]
### Extension

https://www.raycast.com/capipo/pass

### Description

Password store has an extension for managing OTPs called [`pass-otp`](https://github.com/tadfisher/pass-otp) which I think can be added to this extension.

Here I give a sample comparison
``` console
pass <password-file> -c # Password
pass otp <password-file> -c # OTP
```

### Who will benefit from this feature?

Every password-store user who uses its OTP extension

**Comment by capipo** [comment]
Hi @camiloaromero23, I must say that I am not familiar with the OTP extension, I want to ask you a couple of things:
- When you insert an OTP key, is a gpg file created in the `~/.password-store` directory?
- How do you imagine the integration of OTP in this Raycast extension would be?

**Comment by camiloaromero23** [comment]
It is actually a line added to the gpg file that stores the password (in the same directory of the password store (`~/.password-store`)

Here is an example of it:

```
<<my-secure-password>>
otpauth:<<otp-url>>
```
In this case, the otp extension is under de `otpauth` value

What i think would be the best approach is that when you look for a value named `otpauth`, it copies the value of the otp using the command `pass otp <file> -c` instead of the url (which is the behavior it currently has)
<img width="886" alt="image" src="https://github.com/raycast/extensions/assets/64717266/581393ac-d5d7-46be-bdf6-a5cd14facede">

BTW, thanks for the time spent creating the extension, it is super useful! 🚀💪🏽

Let me know if I can help you by both giving advice or getting my hands dirty 🚀

**Comment by camiloaromero23** [comment]
@capipo ☝️

**Comment by capipo** [comment]
> @capipo ☝️

Hi, I've had my hands full with other stuff, I hope to get this sorted out over the next weekend.

Feel free to add a PR if you wish https://github.com/capipo/raycast-pass

**Comment by camiloaromero23** [comment]
Thanks for the good work 🤘🏽
