### ISSUE TITLE
Need a option to change to CAPITALIZE-KEBAB-CASE.

### ISSUE THREAD

**Issue by ongbt** [raycast/extensions#12762]
### Extension

https://www.raycast.com/erics118/change-case

### Description

I need to use CAPITALIZE-KEBAB-CASE for my commit statements.
Thanks!

**Comment by erics118** [comment]
I think it is best to copy a the method for CONSTANT_CASE. See the change-case GH repo file packages/change-case/index.ts L155

**Comment by PWrzesinski** [comment]
@erics118 I've opened a draft PR: https://github.com/raycast/extensions/pull/12773. I implemented the same basic logic as in the function you've mentioned, please let me know if this is what you had in mind.
