### ISSUE TITLE
[Apple Reminders] ...

### ISSUE THREAD

**Issue by rlw126** [raycast/extensions#12772]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Raycast Version

1.75.2

#### Error:
```
The extensions runtime appears to be missing. You may need to reinstall Raycast.


```

### Steps To Reproduce

1. Open menu bar reminders widget from menu bar
2. OR attempt to create a reminder from the raycast shortcut

both will result in the following error
<img width="739" alt="Screenshot 2024-06-04 at 12 52 27 PM" src="https://github.com/raycast/extensions/assets/171721461/1f75bca2-7b18-43bc-bf27-2c889e0abe40">

**Comment by thomaslombart** [comment]
Does it happen for all extensions or only for Apple Reminders?

**Comment by thomaslombart** [comment]
Have you tried uninstalling and reinstalling the extension?
