### ISSUE TITLE
[GitHub] Search Repository in Organization

### ISSUE THREAD

**Issue by guyk-bp** [raycast/extensions#12771]
### Extension

https://www.raycast.com/raycast/github

### Description

I want to have the ability to search for a repository in an organization - i.e. `github.com/my-org/[repo1, my-repo2, repo3]`).

### Who will benefit from this feature?

Mostly users in an organization (not GitHub enterprise) who need quick access to various repos

### Anything else?

Today's "_Search Repositories_" isn't enough since it's too broad.

**Comment by aeorge** [comment]
You can select an organization using the dropdown menu at the top right (`⌘ + P`). The list will then display repositories only from the selected organization.

**Comment by jfkisafk** [comment]
Plus you can always use the query `org:<org-name>` in the search bar if the organization is not listed in the top-right accessory dropdown.

**Comment by jfkisafk** [comment]
@raycastbot close this issue

**Comment by guyk-bp** [comment]
![image](https://github.com/raycast/extensions/assets/170321828/a9858e59-bbf8-4d54-a8c8-9200652bdf8c)
Perhaps I'm doing something wrong but this doesn't work (names have been changed for privacy issues)
