### ISSUE TITLE
[Apple Reminders] Grouping by Kanban column

### ISSUE THREAD

**Issue by assanali-uzakov** [raycast/extensions#12782]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Recently apple added a feature that allows to enable Kanban view in reminders app. So it would be great to be able to group tasks by the Kanban columns.

### Who will benefit from this feature?

I think everyone who is using Kanban view in reminders app.

**Comment by thomaslombart** [comment]
That's unfortunately not possible as Apple's Reminders API doesn't provide support for sections 😕

**Comment by thomaslombart** [comment]
No, unfortunately. I wouldn't expect EventKit updates to be released anytime soon from Apple to be honest 😔

The EventKit framework is definitely not on par with the features available in their native apps

**Comment by yougotwill** [comment]
Ah that is unfortunate. Thank you for your reply though 🙏
