### ISSUE TITLE
[Color Picker] Add color value to Color Picker

### ISSUE THREAD

**Issue by tomgenoni** [raycast/extensions#12783]
### Extension

https://www.raycast.com/thomas/color-picker

### Description

My most common use case is to confirm that a color is the correct value and often don't need to copy it. I currently use ColorSlurp's color picker for this (see screenshot) but would love to be able to use this extension.

![Screenshot 2024-06-05 at 1 36 19 PM](https://github.com/raycast/extensions/assets/1171072/a8d9e343-397e-46e7-9c26-67e2bad72cc6)

### Who will benefit from this feature?

Anyone who wants to confirm a color is correct without first having to copy it.

**Comment by aliaksandrZh** [comment]
I will look into it

**Comment by tmm** [comment]
Example repo that has live sampling (among other features) https://github.com/danielcapra/SCColorSampler

![example](https://github.com/user-attachments/assets/60c9642d-14da-49e6-af42-023c47354127)
