### ISSUE TITLE
[Ploi] Disable limit or enable pagination on servers/sites page

### ISSUE THREAD

**Issue by corentinbtmps** [raycast/extensions#12786]
### Extension

https://www.raycast.com/ploi/ploi

### Raycast Version

1.75.2

### macOS Version

14.5

### Description

Currently the display of sites and/or servers must be limited to a certain number and does not allow the complete display of sites and/or servers linked to my account.

### Steps To Reproduce

You need a Ploi account with a big amount of sites and/or servers.

**Comment by xmok** [comment]
Hi @corentinbtmps!

I've made a PR #13249 to paginate `Servers` (not `Sites` ...yet) but I had to mock the data. Could you check out the updated extension and confirm if Servers are now paginating for you?

Thanks.

**Comment by corentinbtmps** [comment]
@xmok - https://github.com/raycast/extensions/pull/13249#issuecomment-2199651489
