### ISSUE TITLE
[Color Picker] Misleading `oklch()` format

### ISSUE THREAD

**Issue by oskarkrawczyk** [raycast/extensions#12794]
### Extension

https://www.raycast.com/thomas/color-picker

### Raycast Version

1.75.2

### macOS Version

14.5

### Description

The extension format configuration for OKLCH implies one format:

![Screenshot 2024-06-06 at 16 37 04](https://github.com/raycast/extensions/assets/34213/3ae602f3-980a-42dd-9c3d-53dab08f542b)

Which is what I expect, the first argument (L) to be set in percentage, yet when I pick a color or convert, the first value is an integer (0-1).

Both are valid as per spec.

### Steps To Reproduce

Copying or generating a OKLCH color.

### Current Behaviour

Copying or generating a OKLCH color produces: `oklch(<number> < number> <number>)`

### Expected Behaviour

Should be `oklch(<percentage> <number> <number>)`

**Comment by pernielsentikaer** [comment]
CC @samuelkraft

**Comment by samuelkraft** [comment]
Reopening as the previous implementation didn't work reliably
