### ISSUE TITLE
[Ollama AI] ...

### ISSUE THREAD

**Issue by YanisBra** [raycast/extensions#12793]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Raycast Version

1.76.0

### macOS Version

Sonoma 14.5

### Description

When I create a custom command with the Raycast Ollama extension, the AI no longer considers text selection in its response since the latest update.

### Steps To Reproduce

1. Create a custom command that requires text selection for the AI to respond, for example: "Correct this text:"
2. Select a text from an application and execute the custom command to correct the text.
3. The AI responds without considering the selected text, so it does not correct the text.

**Comment by MassimilianoPasquini97** [comment]
![Screenshot 2024-06-06 alle 18 38 42](https://github.com/raycast/extensions/assets/62497822/9a82a0c3-6092-4811-9d12-e6fea0b4039c)

You need to use the tag {selection}, README.md for more info.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot assign me

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue
