### ISSUE TITLE
[Bitwarden Vault] unable to search vault

### ISSUE THREAD

**Issue by marek-liska** [raycast/extensions#12809]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Raycast Version

1.75.2

### macOS Version

14.5 (23F79)

#### Error:
```
Error: Unknown entry point type undefined specified

rN:index.js:20:36442
MessagePort.<anonymous>:index.js:10:696
[nodejs.internal.kHybridDispatch]:event_target:807:20
exports.emitMessage:messageport:23:28
```
![Screenshot 2024-06-07 at 14 10 12](https://github.com/raycast/extensions/assets/105655429/57ff6351-7b6a-44b2-8cf3-7503551a1fa6)

### Steps To Reproduce

custom server, M1 mac air, bitwarden-cli version 2024.4.1

**Comment by jomifepe** [comment]
Hey @marek-liska, I see that you closed the issue, did you manage to solve the error?

**Comment by marek-liska** [comment]
Hello, yes, it got fixed after an update of bitwarden-cli I assume. Currently on 2024.6.1 and everything seems to be working just fine
