### ISSUE TITLE
[GitHub Repository Search] Release Page Not work

### ISSUE THREAD

**Issue by Ernest0-Production** [raycast/extensions#12808]
### Extension

https://www.raycast.com/thomas/github-repository-search

### Raycast Version

1.76.0

### macOS Version

14.4.1

### Description

<img width="862" alt="Снимок экрана 2024-06-07 в 15 20 20" src="https://github.com/raycast/extensions/assets/19843524/04a70164-9789-48f9-ae50-8bc373293484">

### Steps To Reproduce

Run action "Browse Release" on any github repo with releases

**Comment by j3lte** [comment]
Unstall the issue, fix incoming: #13720

**Comment by j3lte** [comment]
Fixed in #13720

@raycastbot close this issue
