### ISSUE TITLE
[Todo List] shortcut to add item

### ISSUE THREAD

**Issue by ancepsinfans** [raycast/extensions#12824]
### Extension

https://www.raycast.com/maggie/todo-list

### Description

It would be nice to expose the ability to add an item to a todo list by shortcut. Could be used in combination with clipboard or more complex integrations (personally, I want to be able to write a script to check my Obsidian notes once a day and pull any lines with `#todo` into my Raycast todo list).

### Who will benefit from this feature?

everyone who needs todos

**Comment by romanskorobagatko** [comment]
@ancepsinfans this is a great idea, would be nice to have such feature.
