### ISSUE TITLE
[Music] Add "Generate Playlist" Command

### ISSUE THREAD

**Issue by neobarthold** [raycast/extensions#12821]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

I would love a "Generate Playlist" Command like in the [Spotify Extension](https://www.raycast.com/mattisssa/spotify-player).

**Comment by rawnly** [comment]
Hey this is not possible due to api limitations. I'm sorry.

**Comment by rawnly** [comment]
@raycastbot close this issue
