### ISSUE TITLE
[Raycast Wallpaper] Does not Respect "Show on all Spaces"

### ISSUE THREAD

**Issue by validatedev** [raycast/extensions#12825]
### Extension

https://www.raycast.com/koinzhang/raycast-wallpaper

### Raycast Version

1.76.0

### macOS Version

14.5

### Description

If I set a wallpaper using Raycast Wallpaper extension, it switches off the "Show on all Spaces" setting found in System Settings -> Wallpaper.

### Steps To Reproduce

1. Set any wallpaper with "Show on all Spaces" enabled.
2. Set any wallpaper with "Set Raycast Wallpaper".

### Current Behaviour

Preserve "Show on all Spaces" is disabled, and "Set Raycast Wallpaper" affects only one space.

### Expected Behaviour

The "Show on all Spaces" setting is respected whether it is enabled.

**Comment by validatedev** [comment]
I have solved it myself, but it was not ideal as it requires opening system settings via AppleScript. It seems not fixable via current AppleScript API because of the changes in Sonoma.

**Comment by pernielsentikaer** [comment]
Maybe @koinzhang knows another way?
