### ISSUE TITLE
[Bitwarden Vault] "Search Vault" doesn't show any entries

### ISSUE THREAD

**Issue by JoshiJoshiJoshi** [raycast/extensions#1285]
# Extension – [Bitwarden Vault](https://github.com/raycast/extensions/tree/9e0cbd6387e768a80a6a380b31664b0e9a04eafd/extensions/bitwarden/)
Author: @pomdtr

## Description
It's not showing any entries. "Refresh items" is showing an error. This started out of the sudden a few updates back.
Initial Screen when opening:
<img width="750" alt="Screenshot 2022-04-04 at 20 16 56@2x" src="https://user-images.githubusercontent.com/49132782/161606666-082bd6fb-a106-4f59-8285-8e4e889456e9.png">
Screen after refreshing:
<img width="750" alt="Screenshot 2022-04-04 at 20 17 41@2x" src="https://user-images.githubusercontent.com/49132782/161606695-05892dcd-fdb8-4b18-91ab-a8fa799b0590.png">

Reinstalled this extension and Bitwarden-cli. Both didn't work.

## Error:
```
Error: Command failed with exit code 1: /opt/homebrew/bin/bw sync --session XbHOb3IwwCz0mpsHpuAlewwUt5n3W/HtPEDCQWYB0uARXlINuusdQS+sJFn//9h7DaSCHHVIYIRRppqOyK9duQ==
/opt/homebrew/Cellar/bitwarden-cli/1.22.0/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:34644
                return Response.error("Syncing failed: " + e.toString());
                                                             ^

TypeError: Cannot read properties of null (reading 'toString')
    at SyncCommand.<anonymous> (/opt/homebrew/Cellar/bitwarden-cli/1.22.0/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:34644:62)
    at Generator.throw (<anonymous>)
    at rejected (/opt/homebrew/Cellar/bitwarden-cli/1.22.0/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:34619:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

/opt/homebrew/Cellar/bitwarden-cli/1.22.0/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:34644
                return Response.error("Syncing failed: " + e.toString());
                                                             ^

TypeError: Cannot read properties of null (reading 'toString')
SyncCommand.<anonymous>:bw.js:34644:62

---
34641:                 return Response.success(res);
34642:             }
34643:             catch (e) {
34644:                 return Response.error("Syncing failed: " + e.toString());
34645:             }
34646:         });
34647:     }
---

    at Generator.throw (<anonymous>)
rejected:bw.js:34619:65
processTicksAndRejections:task_queues:96:5
Nr:search.js:5:57
search.js:5:10353
processTicksAndRejections:task_queues:96:5
async ve.sync:search.js:5:13055
async c:search.js:10:2218
```

## Steps To Reproduce

1. Open Raycast via shortcut
2. Go to "Search Vault"
3. Enter Master password

## The current behavior
Doesn't show any entries.

## The expected behavior
Show me a list of entries.

### Raycast version
Version: 1.31.0

**Comment by daniel-stoneuk** [comment]
I ran into this issue the other day and found this issue in the bitwarden/cli repo https://github.com/bitwarden/cli/issues/234.

Running `bw logout` in a terminal window and then trying again solved it for me, so it's likely this is an issue with the bitwarden CLI.

**Comment by JoshiJoshiJoshi** [comment]
> I ran into this the other day and found this issue in the bitwarden/cli repo [bitwarden/cli#234](https://github.com/bitwarden/cli/issues/234).
> 
> Running `bw logout` in a terminal window and then trying again solved it for me, so it's likely this is an issue with the bitwarden CLI.

That actually solved my problem. Thank you very much!

**Comment by daniel-stoneuk** [comment]
I'm about to make a PR that adds some error handling around this - though I'm not able to reproduce to see if it is caught correctly.

**Comment by pomdtr** [comment]
Your "fix: looks good to me.

**Comment by daniel-stoneuk** [comment]
Thanks.

I guess not embedding the Bitwarden CLI means the user can update it and benefit from security fixes (before someone updates the Raycast repo). Plus it's easier to trust than an embedded binary.

**Comment by pomdtr** [comment]
Yeah at least right now we are forced to update the extension since we get a lot of bug report otherwise 😅
