### ISSUE TITLE
Authy extension doesn't work!

### ISSUE THREAD

**Issue by mdrahiem** [raycast/extensions#12859]
### Extension

https://www.raycast.com/guga4ka/authy

### Raycast Version

1.75.2

### macOS Version

14.5

#### Error:
```
Error: Unknown entry point type undefined specified

rN:index.js:20:36442
MessagePort.<anonymous>:index.js:10:696
[nodejs.internal.kHybridDispatch]:event_target:807:20
exports.emitMessage:messageport:23:28
```

<img width="755" alt="image" src="https://github.com/raycast/extensions/assets/12086760/5c7c698f-8b9c-4314-9bc0-75a32a6f576e">

### Steps To Reproduce

1. Open Raycast app
2. Type "Search token"
3. You will see the error page

### Current Behaviour

Shows the error screen

### Expected Behaviour

Show the otp list screen

**Comment by CampAsAChamp** [comment]
Experienced the same thing recently!

**Comment by mdrahiem** [comment]
Immediate next day it's fixed. Thanks team.
