### ISSUE TITLE
[Apple Reminders] - Quick Add Reminder fails randomly

### ISSUE THREAD

**Issue by MartinGNystrom** [raycast/extensions#12864]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Raycast Version

1.76.0

### macOS Version

14.5

### Description

When I use Quick Add Reminders it often fails with red text under the window and says something like "Failed to add reminder". I don't know where to look in logs for what went wrong

### Steps To Reproduce

1. Bring up Quick Add Reminder
2. Type comments in the Reminder box
3. Use a few words (5+)
4. It fails, but only sometimes!

### Current Behaviour

Fails upon adding reminder and renders error message

### Expected Behaviour

Always adds reminder, renders an actionable error message, or constrains input to ensure it always succeeds

**Comment by thomaslombart** [comment]
It's probably because the AI fails to give a correct answer (though we retry the call up to three times). Could you let me know which reminder text seems to fail?
