### ISSUE TITLE
[Stock Tracker] Receiving error for API authentication

### ISSUE THREAD

**Issue by ashygee** [raycast/extensions#12868]
### Extension

https://www.raycast.com/hmarr/stock-tracker

### Raycast Version

1.76.0

### Description

<img width="774" alt="Screenshot of View Stocks command not authenticating" src="https://github.com/raycast/extensions/assets/10384315/1b242343-d96c-46a9-918c-63bda8662a62">

### Steps To Reproduce

1. Open extension
2. Try to look up a stock

### Current Behaviour

No information populating

### Expected Behaviour

See stock information

**Comment by ramsaysewell** [comment]
Hi, 

There's a chance that this is an issue due to your location. From reading up on some Reddits, the Yahoo Finance API has been quite tricky to work with with anyone outside the US.

As this extension is not specific to Yahoo Finance, I would suggest that a different API should be used going forward.

**Comment by haydencbarnes** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSeyb7xMtZFjoNYI7XG1rjlhUopKAxdLAfSRcaPxg9p-9ii-_g/viewform?fbzx=-7189957683680596558%22}}} - Yahoo Finance API has been deprecated, this extension needs an API facelift

**Comment by eduwass** [comment]
Maybe https://www.alphavantage.co/ could be used? They offer free API key that looks rather easy to set up.

**Comment by haydencbarnes** [comment]
![CleanShot 2024-08-08 at 13 35 02@2x](https://github.com/user-attachments/assets/eb4b15c0-b5b3-48b8-9baf-25a2d4446b7e) Quicklink workaround for now

**Comment by haydencbarnes** [comment]
> Maybe https://www.alphavantage.co/ could be used? They offer free API key that looks rather easy to set up.

Limited to 15 requests per day... but let me see... could require users to add their own API key at first extension start up if you really want to use this extension

**Comment by haydencbarnes** [comment]
https://twelvedata.com/pricing - looks like its api requests limit is much higher for a single API

**Comment by haydencbarnes** [comment]
Or we could just redirect people to open the stocks app: for example https://stocks.apple.com/symbol/AAPL

**Comment by haydencbarnes** [comment]
> Or we could just redirect people to open the stocks app: for example https://stocks.apple.com/symbol/AAPL

Created this: https://github.com/raycast/extensions/pull/14925

**Comment by ericchernuka** [comment]
Just pushed a fix which should alleviate this issue. https://github.com/raycast/extensions/pull/16658
