### ISSUE TITLE
Is it possible to add the ability to select the download path?

### ISSUE THREAD

**Issue by arthurqiao** [raycast/extensions#12866]
### Extension

https://www.raycast.com/kaanrkaraman/twitter-video-downloader

### Description

This is a good extension, and I often use it. Since the video is downloaded to the download folder, it is not convenient to manage. Is it possible to add the ability to select the download path? 
I know that the following extension provides this function.
[https://www.raycast.com/vimtor/youtube-downloader](https://www.raycast.com/vimtor/youtube-downloader)

**Comment by kaanrkaraman** [comment]
I will look into it.
