### ISSUE TITLE
[Spotify Player] ... default playback device

### ISSUE THREAD

**Issue by samtfischer** [raycast/extensions#12863]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.76.0

### macOS Version

14.4

### Description

When I pick a song/album to play and spotify isn't currently running or open anywhere, it defaults to a device that I'm not always near. Can I set it to default to a specific playback device? Or just force it to launch a web player?

### Steps To Reproduce

Search for something and play it 

### Current Behaviour

Plays out of whatever the first available spotify connect device that's available

### Expected Behaviour

I'd like it to launch a web player and play locally on the device I'm launching from.

**Comment by thomaslombart** [comment]
Are you maybe playing Spotify from another active device (phone, TV, or else)? If there are no active devices, the action is supposed to [launch Spotify](https://github.com/raycast/extensions/blob/135d552faa8abf690ef6b0623f826741e1fe3440/extensions/spotify-player/src/api/play.ts#L37) and play the music.

**Comment by samtfischer** [comment]
If the desktop app isn’t installed, should it launch the web player?

Thanks, Sam Fischer

**Comment by thomaslombart** [comment]
It's not launching the web player as of now as we assume the desktop app is installed.
