### ISSUE TITLE
[Google Translate] ...

### ISSUE THREAD

**Issue by Freddiefdl** [raycast/extensions#12867]
### Extension

https://www.raycast.com/gebeto/translate

### Raycast Version

1.76.0

### macOS Version

14.5

### Description

All of my language sets are gone today suddenly.

<img width="756" alt="image" src="https://github.com/raycast/extensions/assets/48426088/789caf96-719e-45ce-add2-fa6679a669d9">

### Steps To Reproduce

1. Open raycast
2. Go to translate command
3. Select language sets

### Current Behaviour

Existing language sets are gone.

### Expected Behaviour

Existing language sets appear as expected.

**Comment by gebeto** [comment]
It looks like some bug related to Raycast itself, so local storage was cleared

**Comment by gebeto** [comment]
@patrikkernke do you have any insights here? maybe Raycast dev team know what can go wrong here?

Do the raycase even have any functionality to reset the extension storage?
