### ISSUE TITLE
I get a "something went wrong" every time I use the extension [Sonos] ... (But it still works though) 😄 

### ISSUE THREAD

**Issue by anderslorentsen** [raycast/extensions#12865]
### Extension

https://www.raycast.com/AntonNiklasson/sonos

### Raycast Version

1.76.0

### macOS Version

14.5

#### Error:
```
Error: listen EADDRINUSE: address already in use :::6329

Server.setupListenHandle:node:net:1872:16
listenInCluster:node:net:1920:12
Server.listen:node:net:2008:7
a.StartListener:decrease-volume.js:12:3517
```
The extension actually works fine, but every time I use it there´s a "Something went wrong promt" same place where the volume indicator is but in red saying there´s a problem. 
![CleanShot 2024-06-10 at 17 02 36](https://github.com/raycast/extensions/assets/166070165/3b26d2f9-d6bf-416e-a860-f5c69e9d7131)

And when I activate Raycast after using it, Ihave to esc out of it (see pic):

![CleanShot 2024-06-10 at 16 46 18](https://github.com/raycast/extensions/assets/166070165/3d9d0e8e-b59e-43d7-84cd-c874f1f089f1)

### Steps To Reproduce

I´m using e extension with hotkeys if that any help :)

![CleanShot 2024-06-10 at 17 00 46](https://github.com/raycast/extensions/assets/166070165/f09555b8-9574-4746-b6a9-88e8db65f34b)

### Current Behaviour

.

### Expected Behaviour

.

**Comment by AntonNiklasson** [comment]
Thank you reporting this. That sounds very annoying, I'll try to get to this soon. Does it happen every time? Or when you trigger via shortcut many times in quick succession?

**Comment by anderslorentsen** [comment]
Actually yes.. It only happens when I do it in quick sucsession. :)

Med venlig hilsen | Best Regards

Anders Lorentsen
+45 3131 4715
Skrædergyden 6
9000 Aalborg
Denmark
