### ISSUE TITLE
[Aerospace Tiling Window Management] Doesn't pick up configs in XDG directories

### ISSUE THREAD

**Issue by nerdyman** [raycast/extensions#12860]
### Extension

https://www.raycast.com/limonkufu/aerospace

### Raycast Version

1.76.0

### macOS Version

14.3

### Description

The Aerospace Tiling Window Management extension doesn't pick up configs when they're in `~/.config/aerospace/aerospace.toml`. It does kinda work if I symlink this config to `~/.aerospace.toml` but Aerospace supports both the home directory and XDG directory and will complain if there are configs in both locations so symlinking doesn't work properly. The plugin can find the config at least.

### Steps To Reproduce

1. Install Aerospace
2. Install Aerospace Tiling Window Management
3. Have config in `~/.config/aerospace/aerospace.toml`

### Current Behaviour

Extension errors, saying it can't find the config.

### Expected Behaviour

Extension finds the config as Aerospace supports this path for its config too.

**Comment by limonkufu** [comment]
The config is configurable in the plugin, you just need to point to the
actual file

**Comment by limonkufu** [comment]
@raycastbot assign me

**Comment by limonkufu** [comment]
@raycastbot close this issue
