### ISSUE TITLE
[Playback Duration Calculator] Support more speeds

### ISSUE THREAD

**Issue by bgiesing** [raycast/extensions#12873]
### Extension

https://www.raycast.com/nathanwijaya/playback-duration-calculator

### Description

I very often watch things on 3-5x speed or even more granular speeds like “2.35x”, would be nice to enter any number for the speed.

**Comment by nathanwijaya** [comment]
Hi @bgiesing, thanks for the feature request - I'll look into adding this.

@raycastbot assign me

**Comment by nathanwijaya** [comment]
Added in #12947

@raycastbot close this issue
