### ISSUE TITLE
[One Time Password] QR Code scan not working

### ISSUE THREAD

**Issue by noidwasavailable** [raycast/extensions#12877]
### Extension

https://www.raycast.com/lachero/one-time-password

### Raycast Version

1.76.0

### macOS Version

Sonoma 14.2

### Description

QR Code scan is not working as intended.

I checked if `screencapture` is working as intended with both `scan` and `select` modes by running `/usr/sbin/screencapture -xD 1 ~/Downloads/1.png` and `/usr/sbin/screencapture -xi ~/Downloads/1.png`, but the extension says `QR Code Detection Failed` every time.

### Steps To Reproduce

1. Export Google Authenticator
2. Move screenshots of the QR codes to the computer
3. Open it on Preview
4. Run "Scan a QR Code"

### Current Behaviour

`QR code detection failed`

### Expected Behaviour

Success!

**Comment by noidwasavailable** [comment]
I'll see if I have time to fork this repo and see what's internally the issue.

**Comment by noidwasavailable** [comment]
Looks like a `jsqr` issue, as the qr code cannot be read by the [demo site](https://cozmo.github.io/jsQR/) they have up.

**Comment by lacherogwu** [comment]
Perheps the QR code is incorrect?
are you able to share it here?

**Comment by noidwasavailable** [comment]
@lacherogwu Hi! Thanks for looking into it. I'm not sure how to, because I added codes that are 2fa codes for the accounts I actually use. 
I have tried 
1. doing it from cli using the script you linked in your extension description manually and that worked fine! 
2. scanning it with my iPhone camera to import the 2fa codes into Keychain and that worked fine as well!

So I don't think it's the QR code's issue.

**Comment by noidwasavailable** [comment]
For the meanwhile, I wrote a PR here: https://github.com/raycast/extensions/pull/12878 to allow for easier bulk importing from the cli output.

**Comment by lacherogwu** [comment]
Ok I understand you can't share your QR code, thanks for the contribution.
I will check the issue & go through your PR

**Comment by ChillarAnand** [comment]
Any plans to fix this?

**Comment by lacherogwu** [comment]
> Any plans to fix this?

Yes working on it right now.

**Comment by muava12** [comment]
can we export / import fro this extension?
