### ISSUE TITLE
[Cal.com] Extend Extension to see Bookings and act on them

### ISSUE THREAD

**Issue by neobarthold** [raycast/extensions#12889]
### Extension

https://www.raycast.com/cal/cal-com-share-meeting-links

### Description

Would love to see this Extension expanded so that I can see my Bookings and act on them, meaning to accept or decline them. Thats in 99% of the cases the reason I have to open the cal.com website.

**Comment by AlexIsMaking** [comment]
@neobarthold you can see your bookings now, in the new View Bookings command 👀

I like the status updates idea though, I'll add an action for that.

**Comment by neobarthold** [comment]
Awesome, thank you.

**Comment by neobarthold** [comment]
A small idea. Could the bookings be sorted by their date or perhaps make the sorting selectable? I could also imagine sorting by status would be useful.

**Comment by AlexIsMaking** [comment]
@neobarthold no worries! Just submitted the update ☝️

The bookings are sorted based on the date of the event at the moment. I haven't got the hang of adding sorting options to Raycast extensions yet so I'm probably not the man for that job I'm afraid.

**Comment by AlexIsMaking** [comment]
@pernielsentikaer I guess this issue can be closed now ☺️
