### ISSUE TITLE
[Jira Time Tracking] JS Heap out of Memory for large project

### ISSUE THREAD

**Issue by marcgemis** [raycast/extensions#12886]
### Extension

https://www.raycast.com/niallpaterson/jira-time-tracking

### Raycast Version

1.76.0

### macOS Version

14.4.1

### Description

The plugin works fine for a "smaller" project with ca 3000 entries
There are problems with a project with ca 23000 entries.

With the development version I got the other day, I get

`
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
`

In the Raycast window I see that around 11.000 of the 23.000 issues where loaded.

When this happens, one cannot log time for a issues within that project.
Even, when the issue is one of the more recent onces and was picked from the dropdown menu offered by the plugin

### Steps To Reproduce

1. open plugin
2. select the project with +23.000 issues
3. select the issue to which one wants to log time
4. fill in the time
submit
wait
... (forever)

### Expected Behaviour

I wouldn't mind if there was a limit to the number of issues in memory, as long as the most recent issues are loaded.

**Comment by LewisLebentz** [comment]
Have the same issue in Slack: https://github.com/raycast/extensions/issues/13067

**Comment by haydencbarnes** [comment]
> Have the same issue in Slack: #13067

Hi @LewisLebentz , this is a fairly large issue across extensions: https://github.com/raycast/extensions/issues/10127#issuecomment-2104485073

**Comment by haydencbarnes** [comment]
Keep open

**Comment by Xiang-Pan** [comment]
Stupid bot kill the community!

**Comment by haydencbarnes** [comment]
@Xiang-Pan @marcgemis You can now set custom JQLs, so this should no longer be an issue if you can narrow down the tickets you want to have available.
