### ISSUE TITLE
[SSH Connection Manager] Remove this buggy non maintained extension. Useless.

### ISSUE THREAD

**Issue by khurshid-alam** [raycast/extensions#12897]
### Extension

https://www.raycast.com/dimagrossman/ssh-manager

### Raycast Version

Latest

### macOS Version

13.4, 14.x

### Extension

https://www.raycast.com/dimagrossman/ssh-manager

### Description

If config has Jump host like this,

```ini
Host SecureConnect secure.myhost.com
	User admin
	HostName 168.169.34.54
	Port 22
	IdentityFile ~/.ssh/id_ed25519

Host Server-01
	User admin
	HostName 168.169.54.97
	Port 22
	ProxyCommand ssh -W %h:%p SecureConnect
```

Then instead of actual host name it shows ProxyCommand. 

**Note**:  HOST section can contain alias separated by space like both name and fqdn (host SecureConnect in above example)

![SCR-20231008-mkqe](https://github.com/raycast/extensions/assets/1333217/af182e35-9032-43d6-a3ad-dd1af8469c3e)

This extension can’t parse config file properly. Extension from other developers are much better. 

### Steps To Reproduce

1. macOS Ventura
2. Add above in ssh config file.
3. Go to ssh connection

### Current Behaviour

Same as above

### Expected Behaviour

It should show Proper name of the host. For multiple host aliases it can show both on the same line or separately as different ssh connection.

**Comment by emiara** [comment]
Hi! I completely agree with you, this extension is messy and very often does not work as expected. I am working on a rewrite of the whole thing. I would love the original contributors blessing but  either way, I am going to rewrite it. @EivindSul would you like to do it with me?

**Comment by scopsy** [comment]
@emiara feel free to give it a shot! I'm way over my head with work, so didn't really got time to review this :(

**Comment by emiara** [comment]
No problem! Its a great and necessary extension. I use it all the time so
it would be an honor to work on it. 😊

**Comment by TamasBarta** [comment]
@emiara, if you're taking on this endeavour, please make sure to support arbitrary terminal emulators by letting the user specify the terminal emulator command, or something (think `wezterm start -- %ssh_command%`), or just support every terminal emulator out there 😄

My issue with many Raycast extensions is when they don't support the apps I use (most notable example is list of supported calendar apps), but for terminal emulators it should be easy to allow whatever the user uses, if they can provide the command to launch it.

Thanks for your efforts! 🙏
