### ISSUE TITLE
[Fantastical] ... Could you add a notification to confirm when new reminder added?

### ISSUE THREAD

**Issue by bcometa** [raycast/extensions#12894]
### Extension

https://www.raycast.com/devahschaefers/fantastical

### Description

I can easily add a reminder or event (it seems to always work perfectly), but there is no notification to confirm it's been added. Therefore, I always end up going into Fantastical to confirm because I cannot risk an event or reminder not being added. If there was a notification to confirm event/reminder was successfully added, I could save the time and not confirm in Fantastical. 

### Who will benefit from this feature?

Everyone who wants to confirm their event or reminder was successfully added to Fantastical.

**Comment by xilopaint** [comment]
When running `Quickly Add Fantastical Event` and `Quickly Add Fantastical Reminder" commands you should see a toast message confirming an event or reminder has been added:

![Screenshot 2024-06-11 at 22 30 02](https://github.com/raycast/extensions/assets/11052366/38b286aa-5507-4f9e-8508-22c36d4a17a8)

**Comment by bcometa** [comment]
Ah! I think I was never patient enough to see it. Thank you! Your extension is definitely one of my most used Raycast extensions; I really appreciate you for making it!

**Comment by xilopaint** [comment]
> Ah! I think I was never patient enough to see it. Thank you! Your extension is definitely one of my most used Raycast extensions; I really appreciate you for making it!

I'm not the extension author, just a contributor. Maybe it's a good idea to use a HUD message as confirmation instead of a toast. This is the approach the Apple Reminders extension uses. I will think about it.

**Comment by bcometa** [comment]
Gotcha. Well, thanks for chiming in! I'd certainly welcome a HUD message.

**Comment by ramsaysewell** [comment]
I've worked on this and created a PR giving  user the choice to show a HUD message or a Toast.

#12928

**Comment by xilopaint** [comment]
@raycastbot close this issue
