### ISSUE TITLE
[Network Drive] Extension asks to install Samba, while macOS Samba is already installed

### ISSUE THREAD

**Issue by j-peeters** [raycast/extensions#12905]
### Extension

https://www.raycast.com/SuoweiHu/network-drive

### Raycast Version

1.76.0

### macOS Version

14.5

### Description

Thanks for developing this extension. AFAIK Apple is using Samba to mount network drives. So Samba is probably installed. The extensions doesn't recognize this and asks to install Samba via Homebrew. This feels superfluous and might cause conflicts by installing it again. Maybe there's a way to recognize the already installed Samba or just tap into it. Thanks

### Steps To Reproduce

1. install extension
2. configure extension
3. extension asks to install Samba

### Current Behaviour

Extension asks to install Samba

### Expected Behaviour

Extensions uses build in macOS Samba.

**Comment by SuoweiHu** [comment]
Hello @j-peeters, 

I have spent some time investigating the suggested **built-in samba**, I cannot find anything except for the `smbutils`, it is produce similar to what I am trying to do with `smbclient` (from `samba` installed via `brew`) but with no control over the format of the output it. 

And I recon it is a old version of smbutils as well. As it have no `logout` sub-command which  seems to appear on the man-page for smbutil https://man.freebsd.org/cgi/man.cgi?query=smbutil&format=html. 

Hence, for all the reasons, I feel like there's some proper reasons for us to use the `﻿smbclient` (from `samba` installed via `brew`) in this instance. Please let me know what you think on this matter :)

Kind Regards,
Simon Hu

**Comment by SuoweiHu** [comment]
Hello @j-peeters, I have address your suggestion on [pull-#12923](https://github.com/raycast/extensions/pull/12923). Appreciated your suggestion !

**Comment by j-peeters** [comment]
> Hello @j-peeters, I have address your suggestion on [pull-#12923](https://github.com/raycast/extensions/pull/12923). Appreciate your valuable comment !

Thank you so much for your research and considerations, Simon. I will try it out once the pull is merged by Raycast team.
