### ISSUE TITLE
1Password

### ISSUE THREAD

**Issue by tristanotto** [raycast/extensions#12910]
### Extension

https://www.raycast.com/khasbilegt/1password

### Raycast Version

1.76.0

### macOS Version

14.5

### Description

Can't log in to 1Password. Restarted Raycast but didn't help.

<img width="868" alt="image" src="https://github.com/raycast/extensions/assets/63663187/4bbaedc4-0110-426a-a617-9e68e12cbe32">

### Steps To Reproduce

1. Install 1Password extension
2. Try to log in

### Current Behaviour

Error message

### Expected Behaviour

log in

**Comment by abrantes01** [comment]
Got the same error. Fixed it by installing 1Password CLI and enabling it in 1Password app. See https://developer.1password.com/docs/cli/get-started/#install

**Comment by LitoMore** [comment]
Fixed in https://github.com/raycast/extensions/pull/13852. @raycastbot close this issue.
