### ISSUE TITLE
[System Monitor] ... RAM usage not correct (perhaps once >10GB?)

### ISSUE THREAD

**Issue by bcometa** [raycast/extensions#12917]
### Extension

https://www.raycast.com/hossammourad/raycast-system-monitor

### Raycast Version

1.76

### macOS Version

14.5

### Description

I noticed the RAM usage is incorrect for a runaway application. It's using ~12GB of RAM, but system monitor in raycast shows 12MB. 

### Steps To Reproduce

I suspect it may be hard to reproduce unless you have an app using a lot of RAM.

### Current Behaviour

Shows 12MB instead of 12GB

### Expected Behaviour

Shows 12GB

![Activity Monitor (Activity Monitor)  06-12-2024 @ 03 39 54 PM](https://github.com/raycast/extensions/assets/27237458/f90e870b-c356-4c93-bfa3-33e8c11585ba)

**Comment by lucasmezencio** [comment]
Hey @bcometa, could you please share what would be the output of the command below whenever this issue happen?

```bash
/usr/bin/top -l 1 -o mem -n 5 -stats command,mem
```

Thanks! :)

**Comment by bcometa** [comment]
Looks normal. But I don't have anything using a lot of RAM (>10GB) to confirm the error. 


Processes: 534 total, 7 running, 527 sleeping, 4648 threads 
2024/08/12 16:42:48
Load Avg: 4.30, 3.93, 3.78 
CPU usage: 11.63% user, 13.61% sys, 74.75% idle 
SharedLibs: 415M resident, 83M data, 22M linkedit.
MemRegions: 780722 total, 3197M resident, 168M private, 1897M shared.
PhysMem: 15G used (3099M wired, 6782M compressor), 111M unused.
VM: 266T vsize, 4921M framework vsize, 1337162(0) swapins, 2037647(0) swapouts.
Networks: packets: 33567443/37G in, 17800908/12G out.
Disks: 77258167/1172G read, 18009057/331G written.

COMMAND          MEM  
MailMate         3272M
plugin-container 1164M
WindowServer     1144M
Arc              1130M
Evernote Helper  842M
