### ISSUE TITLE
[Lucide Icons Search] Empty icons or without color

### ISSUE THREAD

**Issue by julianosill** [raycast/extensions#12914]
### Extension

https://www.raycast.com/Sn0wye/lucide-icons

### Raycast Version

1.76.0

### macOS Version

Ventura 13.6.1 (22G313)

### Description

All the icons displayed are empty or without color. When open them in browser, it opens just fine in black color.

![Screenshot 2024-06-12 at 17 46 33](https://github.com/raycast/extensions/assets/8575672/9fcf2864-8d44-4f99-bd3b-7f7ac5692291)

I've tried changing the color but nothing changes and happens both on light and dark system mode.

### Steps To Reproduce

Just open or search for any icon.

### Current Behaviour

Show icons empty or without color.

### Expected Behaviour

Show icons with selected color or in black/white.

**Comment by franky47** [comment]
I'm having the same issue (Raycast 1.84.3), on macOS 12.7.6:

![CleanShot 2024-10-18 at 15 36 47](https://github.com/user-attachments/assets/0b1e2a57-fa1f-4ad2-8e11-a19c3030ee9f)
