### ISSUE TITLE
[Google Cloud Platform Search] add option to choose "sub product"

### ISSUE THREAD

**Issue by yosefy** [raycast/extensions#12919]
### Extension

https://www.raycast.com/klaa97/gcp-search

### Description

add option to select "sub product"
for example choose `compute/instance groups` or `compute/instnace templates`

### Who will benefit from this feature?

usually one needs to go to specific part of product to manage it
so every google cloud user will benefit

**Comment by hisomura** [comment]
I agree with your suggestion, but I think it would be difficult to implement and maintain since there is no easy way to get a list of console URLs and names for the sub-products.
