### ISSUE TITLE
[Image Wallet]... Attempts to access Photos Library

### ISSUE THREAD

**Issue by DevanFischer** [raycast/extensions#12913]
### Extension

https://raycast.com/ibll/image-wallet

### Raycast Version

1.76.0

### macOS Version

v14.5 (23F79)

#### Error:
```
Error: EPERM: operation not permitted, scandir '/Users/devan/Pictures/Photos Library.photoslibrary'
    at readdirSync (node:fs:1513:3)
    at k9 (/Users/devan/.config/raycast/extensions/f7f2ccbe-e0a8-46af-9a43-256414627377/image-wallet.js:34:1109)
    at /Users/devan/.config/raycast/extensions/f7f2ccbe-e0a8-46af-9a43-256414627377/image-wallet.js:34:1001
    at Array.map (<anonymous>)
    at s2 (/Users/devan/.config/raycast/extensions/f7f2ccbe-e0a8-46af-9a43-256414627377/image-wallet.js:34:975)
    at async Object.l (/Users/devan/.config/raycast/extensions/f7f2ccbe-e0a8-46af-9a43-256414627377/image-wallet.js:88:661)
```

### Steps To Reproduce

1. Install the latest version of Raycast and Image Wallet extension
2. Configure the extension folder to point at `~/Pictures`
3. Attempt to run the Image Wallet command

### Current Behaviour

Raycast shows an error message about EPERM permission error on the Apple Photo Library directory.

<img width="1112" alt="image" src="https://github.com/raycast/extensions/assets/25752779/b1d18c28-9adb-4595-8c5a-47e0085d0d69">
the 

### Expected Behaviour

I would expect the extension to ignore the Photo Library directory if it is not accessible.

It would be great if the extension had an `exclude paths` configuration setting to allow specified paths to be ignored when reading and parsing files.

**Comment by ibll** [comment]
Put in #12918 for review, thanks for the issue! This only solves the actual error. I'll probably add a way to hide paths soon; I'm considering a few things to make the extension work with more setups than the narrow system I designed it for and would put it with that.
