### ISSUE TITLE
[Mite] Add comment field

### ISSUE THREAD

**Issue by bytepoets-cha** [raycast/extensions#12931]
### Extension

https://www.raycast.com/paolo_ricciuti/mite

### Description

Hi Paolo, I wanted to let you know that I really appreciate your extension! However, there's one feature that would be incredibly helpful: the display of the comment field. For my tasks, it's essential to include a ticket number with each entry, and without the ability to add comments, it's quite challenging to track my bookings accurately with Raycast.

Additionally, it would be amazing if it would be possible to start and stop time bookings in the same way that it’s done in the mite interface and not just by entering a certain amount of time. These features would streamline my process significantly.

Thank you for your great work, and I hope you consider these suggestions for future updates.

### Who will benefit from this feature?

Anyone booking on certain tickets or just going along with the task flow

**Comment by ramsaysewell** [comment]
Hey,

Thanks for the feature request. I'm not a user nor contributor to this extension but as it was simply adding an extra field, I thought I'd help out.

I've setup a PR that adds in a "note" field for when you're entering tasks.

As I'm not a user of Mite, I'm unaware of what the expected behaviour for stopping and starting the trackers. Perhaps the author of the extension is more familiar with that.

**Comment by paoloricciuti** [comment]
>Hi Paolo, I wanted to let you know that I really appreciate your extension! However, there's one feature that would be incredibly helpful: the display of the comment field. For my tasks, it's essential to include a ticket number with each entry, and without the ability to add comments, it's quite challenging to track my bookings accurately with Raycast.

I will take a look at @ramsaysewell PR as soon as i get back from my self imposed stop from OSS cause of burnout but it will likely be next week

>Additionally, it would be amazing if it would be possible to start and stop time bookings in the same way that it’s done in the mite interface and not just by entering a certain amount of time. These features would streamline my process significantly.

Sure...tbf i really dislike howì the mite interface start and stop a timer when you leave the hrs at 0 but i think we can have a command to start the timer. Would that fit well into your workflow?

**Comment by ramsaysewell** [comment]
Merged! 🎉 

This feature is now available so I'll close the issue. If you'd like to request anything else or find an issue with the extension then you'll need to create a new issue 😄

@raycastbot close this issue
