### ISSUE TITLE
[Window Management] Gaps between windows

### ISSUE THREAD

**Issue by akharrou** [raycast/extensions#12935]
### Extension

https://www.raycast.com/linear/linear

> PS: this is for the native "Window Management" extension, I just don't know how to properly link to something like that, so I put a random one.

### Description

Would it be possible to allow us to specify the number of pixels we would like between windows when managing them? A feature the [Rectangle](https://github.com/rxhanson/Rectangle) window manager supports.

![image](https://github.com/raycast/extensions/assets/36056254/09ffb515-2637-4a77-94cd-d93145a2bdbf)

### Who will benefit from this feature?

People with OCD, like myself. Lol, on a more serious note, it's a small aesthetic difference, but it feels more organized and spacious, it gives a breather. I along many others would appreciate it.

### Anything else?

It's actually the only thing holding me back from switching completely from Rectangle to Raycast window management. Although admittedly it would be also nice to support the "snap to window" they support as well.

![image](https://github.com/raycast/extensions/assets/36056254/4744ebae-5505-46bb-a54d-6b06a85a171b)

**Comment by ramsaysewell** [comment]
Hey, 

The Window Management already has options for specifying gaps in the windows. Is this not specific enough?

<img width="310" alt="image" src="https://github.com/raycast/extensions/assets/16674112/3b787d08-50e8-4edb-8e47-c0794ce0dfdd">

**Comment by akharrou** [comment]
> Hey,
> 
> The Window Management already has options for specifying gaps in the windows. Is this not specific enough?
> 
> <img alt="image" width="310" src="https://private-user-images.githubusercontent.com/16674112/339506194-3b787d08-50e8-4edb-8e47-c0794ce0dfdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMDM3NjksIm5iZiI6MTcxODMwMzQ2OSwicGF0aCI6Ii8xNjY3NDExMi8zMzk1MDYxOTQtM2I3ODdkMDgtNTBlOC00ZWRiLThlNDctYzA3OTRjZTBkZmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE4MzEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNWQxODYxMjJhYTA2ZjcxMmJkYzI3MTM5Njc0NzZhMGYyNTM1MDE3YTBkODFiN2E5ODc4NzhlZjRkNjMyYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.80aHo5m6LPfY6i6skas2GjlKPZ8SRwnFEOjKH8Evn5Q">

Oh wonderful, my apologies totally missed it, it was the first option, hiding in plain sight.

**Comment by akharrou** [comment]
> Hey,
> 
> The Window Management already has options for specifying gaps in the windows. Is this not specific enough?

Oh wonderful, my apologies totally missed it, it was the first option, hiding in plain sight.
