### ISSUE TITLE
[Espanso] Extension cannot find my match files for search

### ISSUE THREAD

**Issue by nbbaier** [raycast/extensions#12941]
### Extension

https://www.raycast.com/kud/espanso

### Raycast Version

1.76.0

### macOS Version

14.5

### Description

Since #12836 was merged, I cannot search my matches via the extension. I get the following message when running the command `Search Matches`

<img width="756" alt="Message showing how to add a match to Espanso" src="https://github.com/raycast/extensions/assets/12950157/12de2d04-ce14-44a8-b9f9-1355719ad49b">

Espanso itself works fine, and no other extension functionality has been affected. Reloading the Espanso app does not fix the problem.

### Steps To Reproduce

Update Espanso extension to latest version and run `Search Matches`

**Comment by kud** [comment]
Hey @nbbaier , please provide your files/folders tree. I will have a look really soon to fix that.
