### ISSUE TITLE
[Music] ...

### ISSUE THREAD

**Issue by naokiiida** [raycast/extensions#1294]
# Extension – [Music](https://github.com/raycast/extensions/tree/e656b46965d4367c43056d6a4f35e1bddcaf969a/extensions/music/)
Author: @Rawnly

## Description
"Search & Play Library Track" for songs with the same title defaults to the first result in the list, instead of the one selected.

## Steps To Reproduce

1. Add songs with the same name, case insensitive. 
Example: 
[STAY by The Kid LAROI & Justin Bieber](https://music.apple.com/album/stay/1574378620?i=1574378625)
[Stay by Zedd and Alessia Cara](https://music.apple.com/album/stay/1445043155?i=1445043157)
2. "Search & Play Library Track" for "stay"
3. Select the one on the bottom of the list

## The current behavior
Trying to play Stay by Zedd which is at the bottom of the list, but plays STAY by The Kid LAROI instead.

## The expected behavior
Play Stay by Zedd

### Raycast version
Version: 1.31.0

**Comment by Rawnly** [comment]
@dpnick can you check what's wrong? On #1295  too .. 

Sorry but I don't use Apple Music anymore, so I'm not able to test/reproduce this... 😅

**Comment by Rawnly** [comment]
@dpnick any feedback?

**Comment by Rawnly** [comment]
Ok I finally got some time to spend on this extension. I'm able to replicate the bug and is frustrating...
I think is a limitation of apple-script, since the command is `play track "${track}"`, but I'll try some tricks.

**Comment by Rawnly** [comment]
Got a solution! 😄 

```applescript
tell application "Music"
    play (every track whose id is "${id}")
end tell
```

i'll open a PR asap

**Comment by naokiiida** [comment]
Thanks!
