### ISSUE TITLE
[Linear] Cannot paste screenshot that has been copied to clipboard  in issue description when creating a new issue.

### ISSUE THREAD

**Issue by ljckn13** [raycast/extensions#12948]
### Extension

https://www.raycast.com/linear/linear

### Raycast Version

1.76.0

### macOS Version

15.0

### Description

Cannot paste screenshot that has been copied to clipboard in issue description when creating a new issue.

### Steps To Reproduce

1. Take screenshot and hold ctrl to save it to clipboard.
2. Open raycast and create new Linear issue
3. Add description and try to paste screenshot in issue description field - not working.

**Comment by thomaslombart** [comment]
Thank you for reporting the issue. It's expected, as the underlying component doesn't support any images, just text. I'll mark it as "Not Planned" since we don't plan on adding more features to that any time soon 🙂
