### ISSUE TITLE
[Music] ...

### ISSUE THREAD

**Issue by naokiiida** [raycast/extensions#1295]
# Extension – [Music](https://github.com/raycast/extensions/tree/e656b46965d4367c43056d6a4f35e1bddcaf969a/extensions/music/)
Author: @Rawnly

## Description
"Search & Play Library Album" for albums with the same title groups the albums together.

## Steps To Reproduce

1. Add albums with the same name, case insensitive. 
Example: 
[STAY - Single by The Kid LAROI & Justin Bieber](https://music.apple.com/album/stay/1574378620?i=1574378625)
[Stay - Single by Zedd and Alessia Cara](https://music.apple.com/album/stay/1445043155?i=1445043157)
2. "Search & Play Library Album" for "stay"

## The current behavior
Trying to play Stay by Zedd, but plays STAY by The Kid LAROI instead.
Stay by Zedd doesn't appear in the list. Instead, the album lists as having 🎧2 songs 
<img width="862" alt="Screen Shot 2022-04-06 at 7 52 20" src="https://user-images.githubusercontent.com/54788301/161863899-7317808f-0d54-486d-be2e-667991af24c2.png">

## The expected behavior
Show Stay by Zedd as well as STAY by the Kid LAROI

### Raycast version
Version: 1.31.0

**Comment by Rawnly** [comment]
same as #1294

**Comment by Rawnly** [comment]
Unfortunately this can't be fixed. There's no specific API from Apple Music to retrieve the Album ID and play it. Right now the extension uses a workaround which duplicates the songs filtered by album name and adds them to a temporary playlist.
