### ISSUE TITLE
[YouVersion Bible Suggest] Request to add the Filipino language

### ISSUE THREAD

**Issue by jasanmgl** [raycast/extensions#12963]
### Extension

https://www.raycast.com/caleb531/youversion-suggest

### Description

Please add the Filipino language to the list of languages in the extension options. The language is already supported in the YouVersion Bible 
![image](https://github.com/raycast/extensions/assets/150525436/0581a8c5-e6a1-4302-8296-b69a93fb02f5)

### Who will benefit from this feature?

Users in the Philippines who use this extension and prefer the Filipino version of the Bible.

**Comment by caleb531** [comment]
@jasanmgl Absolutely! What should the default Filipino version be? This isn't necessarily the version that you yourself prefer to use, but rather, when someone sets Filipino as their preferred language, what version/translation should be set by default?

Here is the list of versions that YouVersion supports for Filipino (`tgl`):
https://www.bible.com/languages/tgl

**Comment by caleb531** [comment]
@raycastbot assign me

**Comment by jasanmgl** [comment]
@caleb531 it should be the Magandang Balita Biblia (2005) (MBB05) version. As this is commonly referenced at least within our community. Thank you so much!
<img width="306" alt="image" src="https://github.com/raycast/extensions/assets/150525436/ddbb82bc-9001-4b74-8e74-f1cff99e9150">

**Comment by caleb531** [comment]
Okay, just submitted a pull request #13008 to add Filipino language support. Once that is merged, this will be available.
