### ISSUE TITLE
[Apple Notes] Feature request: Show notes that have linked to the current open notes (backlinks)

### ISSUE THREAD

**Issue by eatmoresushi** [raycast/extensions#12978]
### Extension

https://www.raycast.com/raycast/apple-notes

### Description

Thank you so much for building the extension. Apple notes have supported linking to other notes feature. We now can have a noteA mentions (links) noteB. However, when we open noteB, there is no way we could know noteA has linked it. I'm wondering if this raycast extension could add a command to show all the note titles that linked to the current note.

### Who will benefit from this feature?

Everyone using the extension

**Comment by thomaslombart** [comment]
We do have this feature:

![CleanShot 2024-06-17 at 11 16 47@2x](https://github.com/raycast/extensions/assets/16003285/306f79bb-283f-4386-920c-dcafb3261333)

Is that what you were looking for?

**Comment by eatmoresushi** [comment]
Hi @thomaslombart thanks for the reply. I didn't know you already implemented it under the _Search Notes_ command. That's awesome, this is the feature I'm looking for. However, I'm wondering if it could show the backlinks of current opened note? If I'm already got the Apple Notes app open and viewing one note, and I would like to know if there's any backlink to this note, currently, I would have to search it on Raycast and then check. Is it possible to add one command like _Show Backlinks of Current Note_?

**Comment by thomaslombart** [comment]
It's possible to get the current note with some AppleScript, so it's probably doable to do so.

However, a command like `Show Backlinks of Current Note` looks too specific. We aim to keep the Apple Notes extension powerful yet simple, meaning the commands have to easily be discoverable and generic. Maybe it could be better to name it `Current Note` which would then open the detail view of a note within Raycast, and so you'd be able to see the backlinks and links from there. What do you think?

**Comment by eatmoresushi** [comment]
Yeah that would be wonderful!!! Really appreciate. It would be interesting to see what other info you guys come up to shown in this detail view. Only thing I can think of it's creation date and latest modification date, maybe a word count?

**Comment by thomaslombart** [comment]
We actually already have this view actually 😄 

We show the following info on a note detail:
- Account (iCloud, Gmail, etc.)
- Folder name
- If the note is locked or not
- If the note has a checklist
- Tags
- Clickable links
- Clickable backlinks

A word count would be nice to have!

**Comment by eatmoresushi** [comment]
Wow that's nice. Yeah I just saw it from _Search Notes_. So instead of adding a new command, do you think we could just add a new section in _Search Notes_ at the top, called "current opened notes", so I could quickly check the note detail of my current note. (notes if multiple windows are opened). Or we could have a section just shows the details of current note on top of the lists. Which way do you think would be a better implementation?

**Comment by thomaslombart** [comment]
I think it's best to keep it as a separate command for various reasons:
- Some folks may expect the `Search Notes` command to always return the latest modified notes at the top. Showing the current note first may break their workflows.
- It'll be possible to assign a hotkey to the `Current Note` command which can be handy.
- It'll make the overall UX of the `Search Notes` complex if we want to keep on adding features afterwards. Doing it from another command will leave room for improvements

**Comment by eatmoresushi** [comment]
Yes, you are right. That makes total sense. That would mean just a hotkey away from showing the details(includes backlinks) of current note, which is great and exactly what I wanted. Thank you so much for considering and being willing to add this request. It's been fantastic discussing the details with you.

**Comment by thomaslombart** [comment]
Thanks for the kind words! It's been a pleasure as well 😊
