### ISSUE TITLE
[ChatGPT Quick Actions] Can you support the new ChatGPT application instead of OpenAI key using macOS shortcuts?

### ISSUE THREAD

**Issue by bigplayer-ai** [raycast/extensions#12980]
### Extension

https://www.raycast.com/alanzchen/chatgpt-quick-actions

### Description

Can you support the new ChatGPT application instead of OpenAI key using macOS shortcuts?

### Who will benefit from this feature?

everyone who wants to save penny.

### Anything else?

Can you support the new ChatGPT application instead of OpenAI key using macOS shortcuts? https://help.openai.com/en/articles/9275200-using-the-chatgpt-macos-app

**Comment by alanzchen** [comment]
Unless the official ChatGPT app has some sort of API (even Apple Script), we can't possibly implement this.

**Comment by bigplayer-ai** [comment]
> Unless the official ChatGPT app has some sort of API (even Apple Script), we can't possibly implement this.

it has using iOS shortcuts and [url scheme](https://support.apple.com/en-il/guide/shortcuts/apd624386f42/ios)?

<img width="1312" alt="Screenshot 2024-06-16 at 19 01 24" src="https://github.com/raycast/extensions/assets/119108387/251bc158-a78b-48b3-bd0d-360ea6176f4e">

**Comment by alanzchen** [comment]
In that case you could just use Shortcuts.app and assign a keyboard shortcut for it. 

![CleanShot 2024-06-17 at 22 15 10@2x](https://github.com/raycast/extensions/assets/2144783/097a7891-971e-4070-953a-4500d142574f)
