### ISSUE TITLE
[Messages] add option to close Raycast window after message sends

### ISSUE THREAD

**Issue by octokatherine** [raycast/extensions#12986]
### Extension

https://www.raycast.com/thomaslombart/messages

### Description

After sending a message, I have to escape out of the Raycast window. It would be nice if the window closed after sending, or if there was an option to have it behave like this.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? This feature shouldn't be too hard to implement.

**Comment by ramsaysewell** [comment]
I'd like to work on this as it could be quite fun to implement.

**Comment by thomaslombart** [comment]
I'm working on it at the moment.
