### ISSUE TITLE
[Espanso] ... Add match (using Raycast); Raycast unexpectedly disappears and my screenreader says "Raycast has no windows"

### ISSUE THREAD

**Issue by JaheerUCD** [raycast/extensions#12998]
### Extension

https://www.raycast.com/kud/espanso

### Raycast Version

1.76.0

### macOS Version

14.5

### Description

<img width="800" alt="Screenshot 2024-06-17 at 19 09 39" src="https://github.com/raycast/extensions/assets/44057391/ebb82240-26b0-4c89-b268-c4265107ccf3">
<img width="800" alt="Screenshot 2024-06-17 at 19 09 48" src="https://github.com/raycast/extensions/assets/44057391/3a0b5129-b2e1-4b0e-a64d-bd45347a9876">
<img width="800" alt="Screenshot 2024-06-17 at 19 09 23" src="https://github.com/raycast/extensions/assets/44057391/375876ed-17e1-4f4b-baba-e1c9d6fcd929">

Raycast problem report

I have two bugs with Raycast. The first bug is that my computer says that Raycast has no windows (I am using VoiceOver screenreader / Text-to-speech). When I navigate to the menu extras on the upper right part of the screen  (beside the Wi-Fi symbol and the input mode symbol), Normally I can open a menu in the menu extras which is called Raycast. I can use this menu to open the Raycast search, open the Raycast settings, the troubleshooting, the manual, and so on. However, often my computer just says that "Raycast has no windows". It is worth noting that I am using the voiceOver screen reader, that is, the text to speech assistive technology of Apple. I have a Mac studio with M1 Apple silicon processor and Mac OS Sonoma.
I also use a keyboard shortcut to bring up the Raycast search and this usually works, but often Raycast just disappears unexpectedly.
 
The second bug is related to the application called Espanso, which can create text shortcuts. I am using the same Espanso application together with Raycast on my MacBook (my other computer), and there I do not have any problems. I can open Ray cast search, ad to add a match For a text shortcut, and then I can type something anywhere on my computer and it will auto complete the text. For example, I can make the text shortcut :STH and this will auto complete to “something”. However, it has not worked yet on my Mac studio. I also get an arrow message, which is in one of the appended files.
I normally use Raycast and open the Espanso extension to add a match / snippet. Then this will bring up a window where I can define a match for a text shortcut. (see screenshots in the attached files)

### Steps To Reproduce

1. "Raycast has no windows" bug. With VoiceOver on, press Control + Option +  double-hit M to go to Menu Extras. Move left or right to find Raycast. Press Control + Option + Space to activate it. Move left or right again and VoiceOver will announce "Raycast has no windows".

2. Espanso bug: Open Raycast search. Type "Add" and select "Espanso - Add Match". Add a match and press Command + Return to finish it. Then the next window will be an error message. See the screenshots.

**Comment by kud** [comment]
@raycastbot assign me
