### ISSUE TITLE
[Harvest] Missing projects on customers

### ISSUE THREAD

**Issue by Vainyards** [raycast/extensions#1299]
# Extension – [Harvest](https://github.com/raycast/extensions/tree/868620af0a068059055d628e3be8bb0cc8c33e55/extensions/harvest/)
Author:

## Description
I am missing a lot of the customer projects in the trello plugin. 
I have some, but other not, We have a lot of projects on some customers due to different Projectnumbers etc. But I cannot seem to get how to set up projects so that I shows up in the raycast plugin. If I add them to harvest timesheet then I can start and stop in plugin. But I cannot search for them when I'm trying to add a new to clock time. 

Is there a limitation on objects in the dropdown? 
I would be great if the customer as well where searchable, an API limitation?!
I am project manager of all the projects. (even if I'm not mangageing it) 

## Steps To Reproduce

1. open raycast
2. start a new time
3. search for project to log time
4. cannot find correct project. 

## The current behavior
searches for some projects but others are not find able. 

## The expected behavior
Find correct project in dropdown, thru search or manual scroll
### Raycast version
1.31.0

![Skärmavbild 2022-04-06 kl  07 21 28](https://user-images.githubusercontent.com/81222124/161901333-e15b3fad-e541-470d-9980-34f45d02f678.png)

**Comment by tomgenoni** [comment]
I'm having the same problem. When I first bring up the extension there are no "Tasks" available. If I switch projects to a different client, then back to the original one, then the "Tasks" do show up. Tried uninstall/reinstall to no avail.

![Screenshot 2024-04-08 at 1 23 09 PM](https://github.com/raycast/extensions/assets/1171072/36adb1e7-2dca-47ea-89f3-e1d1c6b3358e)
