### ISSUE TITLE
All my otp tokens are corrupted. Tried uninstalling and resyncing but still showing as corrupted. 

### ISSUE THREAD

**Issue by trulytribal** [raycast/extensions#13009]
### Description

Hi I opened up my authy raycast extension and found that all the tokens were corrupted. 

I tried the following
- changing the backup password after finding them corrupted.
- Uninstalling and reinstalling with a new sync.

<img width="182" alt="Screenshot 2024-06-17 at 8 45 55 PM" src="https://github.com/raycast/extensions/assets/100387177/8d5b9d7f-a21e-4039-bef8-dc36cbe5044d">

### Steps To Reproduce

Not sure how to reproduce, it was just like this when i opened it.

### Current Behaviour

OTP tokens are corrupted.

### Expected Behaviour

The tokens should be available to paste into applications

**Comment by vinihvc** [comment]
Same issue here

**Comment by morfien101** [comment]
+1

**Comment by guga4ka** [comment]
@trulytribal should be fixed now, for additional context check #13092

@raycastbot close this issue
