### ISSUE TITLE
[Claude] Chats and models are no longer working after latest update

### ISSUE THREAD

**Issue by FelixLisczyk** [raycast/extensions#13017]
### Extension

https://www.raycast.com/florisdobber/claude

### Raycast Version

1.76.1

### macOS Version

14.5 (23F79)

### Description

I can no longer use the chat feature after the latest extension update. As soon as I submit my chat message, I receive the following error:

<img width="330" alt="Screenshot 2024-06-18 at 12 08 40" src="https://github.com/raycast/extensions/assets/5102728/21ccd0bf-f6a7-4043-b71d-e34bbb8d85c2">

In addition, I can also no longer access the "Models" command:

```
TypeError: Cannot read properties of undefined (reading 'toLocaleString')

Gi:list.tsx:44:10

---
41: };
42: 
43: const ModelDetailView = (props: { model: Model; markdown?: string | null | undefined }) => {
44:   const { model, markdown } = props;
45: 
46:   return (
47:     <List.Item.Detail
---

    at ray-list-item
on:index.js:20:22550
Jp:model.js:35:4581
```

### Steps To Reproduce

**First Issue**

1. Run the "Ask Question" command
2. Submit your query

**Second Issue**

1. Run the "Models" command

**Comment by florisdobber** [comment]
Hi @FelixLisczyk, I did a clean install of the latest version and am unable to reproduce your error. Could you try reinstalling to see if that will fix your issue? If you have any detailed system prompts, you might want to save those elsewhere before reinstalling.

**Comment by FelixLisczyk** [comment]
Hi @florisdobber, thank you for responding so quickly! Yes, a clean install works fine. It seems to be a migration issue from the old version. Could there be a new required property that doesn't exist in the old data model? I was able to reproduce the crash as follows:

1. Checkout the old version from your fork repository (`git checkout a8c5c4394e6c5bcbc5cae14dcd4081e726fea345`)
2. `npm install && npm run dev`
3. Enter your API key and create a custom model
4. Checkout the new version from your fork repository (`git checkout 9fe7b4067d4ba05ea051d6c5a01fc768d2b617c6`)
5. `npm install && npm run dev`
6. Run the "Models" command and try to edit the previously created model

I couldn't reproduce the 400 response in the "Chat" command yet. But it seems to refer to a missing `max_tokens` property. I'll keep my existing installation for now to validate any fixes.

**Comment by florisdobber** [comment]
Thanks @FelixLisczyk for the clear reproduction instructions! Using those it was easy to identify, and PR #13037 will address the issue. It was indeed due to the `max_tokens` property not being set in legacy models.

**Comment by FelixLisczyk** [comment]
Both commands are working again. Thank you very much for the quick fix! 👍
