### ISSUE TITLE
[Quit Applications] Don't reset selection/scroll position after quitting app

### ISSUE THREAD

**Issue by niklashigi** [raycast/extensions#13033]
### Extension

https://www.raycast.com/mackopes/quit-applications

### Description

Currently, the "Quit Applications" extension resets the selection and scroll position every time an application is quit. This makes it inconvenient to go through the list with arrow keys and quit multiple apps in a "I don't need this... not this either... let's also quit that" fashion.

https://github.com/raycast/extensions/assets/29176678/2c9bcede-e9a6-4cf7-adb9-32fd865491e4

A better behavior would be for the selection and scroll position to be retained so that the Enter key can be pressed multiple times to quit applications that are below/above each other in the list.

### Who will benefit from this feature?

Everyone using this extension to quit multiple applications in one go.

**Comment by codesjedi** [comment]
I'm not sure if this doable with the current api, what do you think @pernielsentikaer?

**Comment by shroudedcode** [comment]
@codesjedi I just found out that the built-in "Switch Windows" command has behavior very similar to what I was thinking about. It has a "Quit Application" action that makes the relevant app disappear (albeit with a delay) without the selection or the scroll position being reset.

**Comment by jrnxf** [comment]
I fixed this issue in my PR @codesjedi @mackopes if you want to take a look:
https://github.com/raycast/extensions/pull/13996
