### ISSUE TITLE
[Alice AI - Your ChatGPT Actions Companion] - LLM

### ISSUE THREAD

**Issue by baptistechretien** [raycast/extensions#13048]
### Extension

https://www.raycast.com/quiknull/alice-ai

### Description

Hello,

Would it be possible to configure LLMs language extensions such as Groq or Gemini?

Or the possibility to connect to the OpenRouter.ai platform.

Thank you in advance,

Bets regards,

**Comment by wojciechkrol** [comment]
Hello @baptistechretien,

As a developer of AliceAI, I do not plan to add support for providers other than OpenAI. If you have any ideas and time to implement other providers, feel free to contribute and open a PR with the changes.
