### ISSUE TITLE
[CleanShot X] Add option to send captured area to new AI chat

### ISSUE THREAD

**Issue by NormCopeland** [raycast/extensions#13046]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

The new `Send Captured Area to AI Chat` is great! Right now it sends it (understandably) to whatever AI chat is active. I would to have an option in the command's settings to either send to the active chat, or, start a new chat with the attached screenshot. 

### Who will benefit from this feature?

Anyone who would often be starting new chats based on a screenshot.

**Comment by erics118** [comment]
This would likely require changes from both the Raycast app and the CleanShot app. I suggest either emailing the CleanShot team, or posting in the Raycast slack to contact the respective dev teams.
