### ISSUE TITLE
[Ollama AI] When using a command (for example change tone to professional), with advanced settings/keep alive, error missing unit in duration

### ISSUE THREAD

**Issue by lstep** [raycast/extensions#13045]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Raycast Version

1.76.1

### macOS Version

14.5

### Description

in the advanced settings, parameter "keep alive". The information icon writed that, for keeping the model in memory indefinitely, one should input "-1". But when doing so, get error : `missing unit in duration`

### Steps To Reproduce

1. select ollama change tone to professional
2. click advanced parameters
3. set keep alive to -1
4. see error in red at bottom of window

**Comment by MassimilianoPasquini97** [comment]
@raycastbot assign me

**Comment by MassimilianoPasquini97** [comment]
I @lstep, thanks for opening this issue. Ollama now use golang Time.Duration format for keep_alive so unit are required even for negative or zero values. I have fixed this issue on #13047

**Comment by MassimilianoPasquini97** [comment]
Pull request #13047 merged

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue

**Comment by lstep** [comment]
Thanks, it has been corrected, except on the "Create Custom Command", still with the old invalid syntax. 

![Capture d’écran 2024-06-20 à 16 15 09](https://github.com/raycast/extensions/assets/2028/68f5ae86-3c81-4743-b411-dc5b7ef1676d)

**Comment by MassimilianoPasquini97** [comment]
> Thanks, it has been corrected, except on the "Create Custom Command", still with the old invalid syntax.
> 
> ![Capture d’écran 2024-06-20 à 16 15 09](https://private-user-images.githubusercontent.com/2028/341448237-68f5ae86-3c81-4743-b411-dc5b7ef1676d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4OTM4NDUsIm5iZiI6MTcxODg5MzU0NSwicGF0aCI6Ii8yMDI4LzM0MTQ0ODIzNy02OGY1YWU4Ni0zYzgxLTQ3NDMtYjQxMS1kYzViN2VmMTY3NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjBUMTQyNTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDUzMmUyNzk1M2VjZWQ5ZWM3YjQzYTI0ODFjNDUwYjMwZGZhMWQzNzJlY2U4MzY1MTdhM2ZjNTkwMGU0NmVmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OWj_Kt50aPZIFuspZlH30sbxUXrepI5IGtw32pnCP24)

I have missed that 😅, fixed on #13069 moving keep_alive info and validation function on a separate file.
