### ISSUE TITLE
[Spotify Player] ... Can we get "scrolling" option in menubar? 

### ISSUE THREAD

**Issue by bcometa** [raycast/extensions#13050]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

The Spotify Menu Bar Player is awesome. I just wish it would scroll to show entire song title/artist if the length exceeds max text length. 

### Who will benefit from this feature?

Everyone!

**Comment by erics118** [comment]
See https://github.com/raycast/extensions/issues/7450

**Comment by bcometa** [comment]
Didn't see that -- thanks Erics118!

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/11292, so I'll mark it as such.
