### ISSUE TITLE
[Menubar Calendar] Open reminder in the Reminders app

### ISSUE THREAD

**Issue by danulqua** [raycast/extensions#13055]
### Extension

https://www.raycast.com/koinzhang/menubar-calendar

### Description

Clicking the reminder while holding the ⌘ should open the reminder in the Reminders app.

### Who will benefit from this feature?

Everyone.

**Comment by koinzhang** [comment]
Thanks for your suggestion, I have submitted a PR #13058 : right click to open the reminder in Reminders.

FYI:
✨For Reminders, you can:
- Left-click on the reminder to complete it.
- Right-click on the reminder to open it in Reminder.
- Press **`⌥`** and click on the reminder to delete it.

**Comment by koinzhang** [comment]
Hi @danulqua The PR https://github.com/raycast/extensions/pull/13058 has been merged, can we close this issue?

**Comment by koinzhang** [comment]
@raycastbot close this issue
