### ISSUE TITLE
[Menubar Calendar] Add Calendar Events List

### ISSUE THREAD

**Issue by melwan** [raycast/extensions#13062]
### Extension

https://www.raycast.com/koinzhang/menubar-calendar

### Description

I love the added Reminders integration. Similarly, I would like to see events added such as a list of all-day and upcoming events.

The goal I'm hoping for is for this extension to combine the functionality of "Apple Reminders Menubar Extension" and "Calendar/My Schedule" extension with monthly calendar view as added bonus.
The only feature missing from the above goal is "Calendar/My Schedule" integration.

### Who will benefit from this feature?

Everyone.

**Comment by koinzhang** [comment]
Hi @melwan. I didn't choose to port over the full functionality of the Apple Reminders Menubar Extension for the aesthetics of the calendar view.
The calendar view would look very strange if Submenu was added. For this reason, I was also unable to add shortcuts to these items
<img width="298" alt="image" src="https://github.com/raycast/extensions/assets/36128970/bf0a31cd-9c00-4617-9dfa-5b30f0ef050f">

**Comment by koinzhang** [comment]
As for the inability to switch months, this is due to the limitations of the raycast API. There is no way to find an optimized way to implement this function yet.

**Comment by melwan** [comment]
Actually, what you did with this extension is perfect so far. No need for a full Apple Reminders functionality. What I was asking for is to show calendar events the same way we can see reminders :)

**Comment by koinzhang** [comment]
Hi @melwan. Calendar events has been added in #13160. Feel free to try and give me your feedback

**Comment by koinzhang** [comment]
@raycastbot close this issue
