### ISSUE TITLE
Feature Request for Sound

### ISSUE THREAD

**Issue by S-andres0694** [raycast/extensions#13068]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

Hello! I would like a feature that would allow me to play a sound whenever any of the breaks are over. 
Thank you!

### Who will benefit from this feature?

I think anyone could benefit from this feature as it makes really clear when the break is supposed to be over

**Comment by haydencbarnes** [comment]
@S-andres0694 There is already a sound option for whenever an interval is completed. Are you asking for a separate break sound option?

**Comment by S-andres0694** [comment]
No. I did not realise such feature already existed. I was able to notice by looking at the source code directly. Thanks for the support!

Also, just for curiosity. How did you build a feature for raycast? Is there a public API or an instructions webpage with some necessary details?

Cheers!
Sebas

**Comment by haydencbarnes** [comment]
@S-andres0694 Checkout https://developers.raycast.com/basics/contribute-to-an-extension

**Comment by haydencbarnes** [comment]
@raycastbot close this issue
