### ISSUE TITLE
[Slack] Worker terminated due to reaching memory limit

### ISSUE THREAD

**Issue by LewisLebentz** [raycast/extensions#13067]
### Extension

https://www.raycast.com/mommertf/slack

### Raycast Version

1.77.1

### macOS Version

14.6

### Description

I tried creating a Raycast app with a app manifest directly in Slack and also using the pre-made Slack app (believe that was newly added). With both no functionality works.

The error log shows this:

```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

I haven't done too much troubleshooting, but I've developed Slack integrations before and as I've been using Slack for a long time I wonder if i have too many messages/chats so it can't handle it?

Also using Enterprise Grid.

### Steps To Reproduce

1. Create Slack app with manifest
2. Install to workspace
3. Copy xoxp- key into the extension
4. Try to search or read unread messages - nothing works

**Comment by thomaslombart** [comment]
Could you share a recording? It'll make it easier to see what's happening.

**Comment by LewisLebentz** [comment]
@thomaslombart don't have my Mac with me at the moment, probably won't be able to send anything until tomorrow.

But literally nothing happens. I did a quick GitHub search and it seems like this memory issue is quite widespread across multiple extensions wherever it is processing a large amount of data.

**Comment by Elliot67** [comment]
Very likely an issue with large workspace : #4284 

When pulling data from the Slack API, the extension doesn't stop pulling until it gets **every** users, channels and messages.

**Comment by jfkisafk** [comment]
The optimal solution would be to replace pagination like these:

https://github.com/raycast/extensions/blob/5c077f5a72c66ae6caab0a5958f4d89fb30c86df/extensions/slack/src/shared/client/SlackClient.ts#L84-L94

with:

1. (recommended) just retrieve the first page and support typeahead search. We will need to explore if all the APIs support a search pattern to restrict the results. For example, can't find it for https://api.slack.com/methods/users.list
2. [raycast native pagination](https://developers.raycast.com/api-reference/user-interface/grid#pagination) and a typeahead search. But unless we figure out an API that supports typeahead search pattern, I think users of large workspaces will need to keep scrolling down to retrieve all items and search.
