### ISSUE TITLE
[Tailwind CSS] ...

### ISSUE THREAD

**Issue by davidwebca** [raycast/extensions#13072]
### Extension

https://www.raycast.com/vimtor/tailwindcss

### Raycast Version

1.77

### macOS Version

Sequoia beta 1

### Description

Searching for text decoration / underline offset results in a 404.

https://tailwindcss.com/docs/text-decoration-underline-offset

### Steps To Reproduce

1. Use the extension to search in docs
2. Search for "Underline offset"
3. Select the result
4. Falls onto a 404 

### Current Behaviour

Goes to https://tailwindcss.com/docs/text-decoration-underline-offset

### Expected Behaviour

Should be https://tailwindcss.com/docs/text-underline-offset#basic-usage

This should probably update automatically.

**Comment by vimtor** [comment]
Working now!

@raycastbot close this issue
