### ISSUE TITLE
[Plex] ...Failed to load library (does connect)

### ISSUE THREAD

**Issue by jasonshanks** [raycast/extensions#13070]
### Extension

https://www.raycast.com/mSarheed/plex

### Raycast Version

1.77.1

### macOS Version

15.0

### Description

Hello!

I was able to successfully connect my local Plex server (aside: might be good to give a bit more verbosity to the URL example: for instance I needed the Local network hostname (not 127.0.0.1) and also needed to include the port :32400)

However, after displaying the library sections (Movies, Series, Music, etc) It just says: "Something went wrong" for any of them. Error below...

```
TypeError: Cannot read properties of undefined (reading 'toString')

S3:sectionItems.tsx:28:35

---
25:   );
26: }
27: 
28: function SectionItem({ sectionItem }: { sectionItem: SectionItemsApiResponse["MediaContainer"]["Metadata"] }) {
29:   const markdown = `
30: |Title| ${sectionItem.title} |
31: |--|--|
---

Dr:index.js:8:6799
    at ray-list
dt:index.js:20:24299
```

### Steps To Reproduce

Initial server connection and first attempt to display index.
Only tried on local network, not remotely

**Comment by mSarheed** [comment]
@raycastbot assign me

**Comment by mSarheed** [comment]
Hi @jasonshanks. 
Thank you. I will look into it now and publish a new version of the extension that hopefully solves this issue.
