### ISSUE TITLE
[Authy Extension] Accounts corrupted after cmd + r sync

### ISSUE THREAD

**Issue by basal-luke** [raycast/extensions#13087]
### Extension

https://www.raycast.com/guga4ka/authy

### Raycast Version

1.77.1

### macOS Version

14.5

### Description

Around 90% of my entries are showing `corrupted`

Followed instructions in Q&A to try and resolve:

- Rerun `cmd + r`
- Deleted and re-installed extension

### Steps To Reproduce

1. add new account in Authy iOS app
2. open Authy Raycast extension on Macbook
3. `cmd + r` to sync new account to Macbook
4. new account from step 1 is shown correctly
5. existing accounts now show as `corrupted`

### Current Behaviour

![Screenshot 2024-06-21 at 15 14 15](https://github.com/raycast/extensions/assets/108523558/abae1102-f32a-412a-b881-5a98aeaa0fe7)

**Comment by guga4ka** [comment]
@basal-luke can you double check you password, sometime ago Authy did something with sync mechanism/backup password. Authy might force you to update your backup password once you will open backup password menu from app

**Comment by kolchurinvv** [comment]
i have the same issue. just uninstalled the extension and re-entered the pw; accepted the prompt on my phone - nothing 😭

**Comment by guga4ka** [comment]
@kolchurinvv could you pls submit an issue, at least at the moment seems like you have another problem.

**Comment by kolchurinvv** [comment]
@guga4ka from my end this looks exactly like my issue. if my comment about the extension uninstalling was unclear, i meant to say that i have followed this:
> Followed instructions in Q&A to try and resolve:
    Rerun cmd + r
    Deleted and re-installed extension
