### ISSUE TITLE
ADD a search for keyword

### ISSUE THREAD

**Issue by cyrusn** [raycast/extensions#13085]
### Description

Currently, in the Search Files extension, users can search in a specific folder by using `in` keyword. 

![image](https://github.com/raycast/extensions/assets/5738511/54dd9703-cdac-4247-b156-54363c3d67e8)

But it is not that convenient with this syntax, I suggest using `~/Desktop for name`, as we can search a specific folder, and use `tab` to go inside the folder, then type `for ...` for searching files in a specific folder.  

### Who will benefit from this feature?

Everyone

### Anything else?

Or any better way to search in a specific folder.

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
