### ISSUE TITLE
[Authy] Some records are showing `corrupted`

### ISSUE THREAD

**Issue by leopoldo920c00l** [raycast/extensions#13089]
### Extension

https://www.raycast.com/guga4ka/authy

### Raycast Version

1.77.1

### macOS Version

14.5 (23F79)

### Description

3 of my authy tokens (facebook, instagram and bitfinex) where showing "corrupted". I removed and reinstalled the extension and now all except 1 of my authy tokens show "corrupted".

### Steps To Reproduce

N/A

### Current Behaviour

Authy extension is showing corrupted for almost all tokens.

### Expected Behaviour

Tokens should work.

**Comment by LitoMore** [comment]
@raycastbot rename this issue to "[Authy] Some records are showing `corrupted`"

**Comment by LitoMore** [comment]
@leopoldo920c00l Did you try the `sync` action?

**Comment by leopoldo920c00l** [comment]
I dont see a sync action under the actions.

**Comment by gdsmith** [comment]
Check for the sync option on the non-corrupted token. If that doesn't work, maybe try changing your backup password.

**Comment by leopoldo920c00l** [comment]
Thanks it´s working after changing backup key.

**Comment by StirStudios** [comment]
We have reset the backup key but still no luck. We are on Mac. Also since the update there is no sync action.

**Comment by guga4ka** [comment]
since the @leopoldo920c00l's problem has been fixed i'm going to close this ticket @StirStudios we have a follow up ticket i will post update there #13092

@raycastbot close this issue
