### ISSUE TITLE
Option to turn off toast on success

### ISSUE THREAD

**Issue by jweinstein** [raycast/extensions#13081]
### Extension

https://www.raycast.com/koinzhang/paste-as-plain-text

### Description

Would love a toggle to turn off the toast on success. e.g. `# @raycast.mode silent`, since I use it so much.

**Comment by koinzhang** [comment]
@jweinstein Thanks for the suggestion, as you wish https://github.com/raycast/extensions/pull/13084

**Comment by jweinstein** [comment]
Woo!

**Comment by jweinstein** [comment]
I'm a newbie here, what's the process by which this update gets into the
latest version? I've updated my extensions and don't see this toggle yet.
(No rush, and super thankful!)

**Comment by koinzhang** [comment]
It needs this PR to be merged into the code repository before the extension will be updated, this process may last a week or two depending on the speed of the official Raycast review.
You can click the link https://github.com/raycast/extensions/pull/13084 to check the review progress
