### ISSUE TITLE
Authy - Twilio app

### ISSUE THREAD

**Issue by Priveng20** [raycast/extensions#13092]
### Extension

https://www.raycast.com/guga4ka/authy

### Raycast Version

1.77.1

### macOS Version

14.5

### Description

<img width="352" alt="No valid OTP" src="https://github.com/raycast/extensions/assets/100726173/4e15b720-d39c-4266-a082-588dbd4df79a">

I am getting the following error, I have changed my backup key, uninstalled the extension and reinstalled it and set it up from scratch again but still having the same issue 

### Steps To Reproduce

Just trying to access the extension

**Comment by gdsmith** [comment]
It really is worth double checking your backup password as that is almost 100% likely to be the issue here.

**Comment by exarus** [comment]
> It really is worth double checking your backup password as that is almost 100% likely to be the issue here.

Double checked everything.
1. Uninstalled Raycast extension
2. Changed Authy Backup password to a new one (on my Authy Mobile)
3. Removed Raycast extension from list of accepted devices (on my Authy Mobile)
4. Installed Raycast extension (on my Mac)
5. Filled Authy ID and new backup password (on my Mac)
6. Paired Authy Mobile with Authy Raycast extension
7. Found Twitch token in the list of Authy Raycast extension tokens (it's the only non-corrupted token, since it's non-standard TOTP) and pressed "Sync" button (Command+R on Mac).
8. Tokens remain corrupted. Nothing helps.

**Comment by Priveng20** [comment]
> > It really is worth double checking your backup password as that is almost 100% likely to be the issue here.
> 
> Double checked everything.
> 
> 1. Uninstalled Raycast extension
> 2. Changed Authy Backup password to a new one (on my Authy Mobile)
> 3. Removed Raycast extension from list of accepted devices (on my Authy Mobile)
> 4. Installed Raycast extension (on my Mac)
> 5. Filled Authy ID and new backup password (on my Mac)
> 6. Paired Authy Mobile with Authy Raycast extension
> 7. Found Twitch token in the list of Authy Raycast extension tokens (it's the only non-corrupted token, since it's non-standard TOTP) and pressed "Sync" button (Command+R on Mac).
> 8. Tokens remain corrupted. Nothing helps.

Yep same here.

It was working perfectly fine for me today and just stopped all of a sudden it stopped

**Comment by StirStudios** [comment]
> > It really is worth double checking your backup password as that is almost 100% likely to be the issue here.
> 
> Double checked everything.
> 
> 1. Uninstalled Raycast extension
> 2. Changed Authy Backup password to a new one (on my Authy Mobile)
> 3. Removed Raycast extension from list of accepted devices (on my Authy Mobile)
> 4. Installed Raycast extension (on my Mac)
> 5. Filled Authy ID and new backup password (on my Mac)
> 6. Paired Authy Mobile with Authy Raycast extension
> 7. Found Twitch token in the list of Authy Raycast extension tokens (it's the only non-corrupted token, since it's non-standard TOTP) and pressed "Sync" button (Command+R on Mac).
> 8. Tokens remain corrupted. Nothing helps.

Same here.

**Comment by Priveng20** [comment]
Hi @gdsmith any update on this?

I've gone through some of the other issues raised for this issue and tried some of the steps that worked for other users but I still have the same issue.

**Comment by AndyMznc** [comment]
Same problem as the previous users. All my items are corrupt, despite having tried to regenerate a new key several times and following the recommendations above

![raycast authy corrupted](https://github.com/raycast/extensions/assets/115222358/e7752f1b-7f85-443d-bf13-040694c50589)

**Comment by guga4ka** [comment]
@Priveng20 @AndyMznc Authy has changed the way how OTP token keys, since this is a private API, no one has been notified. I'm currently trying to investigate how to make extension back on track.

**Comment by Priveng20** [comment]
@guga4ka okay, thank you for the update

**Comment by guga4ka** [comment]
Authy added a new field `key_derivation_iterations` to the API response. We should use this for `pbkdf2Key` generation.

I'll push out a quick fix to unblock users, but heads up - it might slow down the extension a bit.

**Comment by kolchurinvv** [comment]
Using it is still a time saver vs using the app, especially now that the dedicated desktop has been shut down and the iPad optimized doesn't play well with auto tilers

**Comment by gdsmith** [comment]
@guga4ka I broke my OTP looking into this so have pushed a PR to fix along with a couple of tweaks #13152

**Comment by guga4ka** [comment]
@kolchurinvv I can't guarantee that Authy will not brake their API in future (after they drop desktop app it will really hard to explore their API). I guess i can add something like "export raw tokens" to be importing to the any other app. 

@gdsmith nice, i've have quickly checked PR, gr8 job, exactly the same i've done, will drop my changes.

**Comment by Priveng20** [comment]
@guga4ka and @gdsmith , just updated the extension and it is working 
Thank you for the feedback and assistance

**Comment by StirStudios** [comment]
@Priveng20 thanks so much for the work and quick fix. The plugin now works just as it did before!

**Comment by guga4ka** [comment]
I think we good to close this issue. @gdsmith one more time, thx for your contribution.

@raycastbot close this issue

**Comment by morfien101** [comment]
I was a bit confused by this so I will just comment here for the next person.

You need to updated to RayCast 1.7.1 (mine was out of date when I was trying to fix this), then remove the Authy as a plugin and reinstall it. Then re-setup your authy plugin.

@guga4ka Thank you 👍

**Comment by gdsmith** [comment]
You probably just needed to update Raycast and then the Authy plugin, the remove and reinstall should not be needed AFAIK.

**Comment by morfien101** [comment]
I did that and it didn't work. I updated raycast and tried to just resync but no luck. At this point most my otps showed corrupted. 

I guess milage may vary, but thats how I got mine to work again.

**Comment by gdsmith** [comment]
Did you check that the extension was on the latest version after you
updated Raycast?

**Comment by exarus** [comment]
The token loading time is way too long after the update. It's like more than 8s. It's faster to take the phone and check out the token from it

**Comment by guga4ka** [comment]
@exarus Yeah, this was a downside of the quick fix made by @gdsmith. I'll try to refactor the extension over the weekend. Initially, I didn't write it very optimally. The problem here is that the decryption of the OTP seed is calculated every time the extension runs, instead of doing it during onboarding 🤷‍♂️

**Comment by bduff9** [comment]
Just uninstalled and reinstalled this extension after getting the corrupted issue, however, it will not setup now.  Every time I enter my account Id and backup password, I get an error that says "Attestation token is missing". I have double-checked the account Id and backup password several times.

**Comment by guga4ka** [comment]
@bduff9 nothing i can help with, seems like Authy killed desktop App and might kill API that has been using to retrieve our OTPs, here is a [reddit post](https://www.reddit.com/r/Authy/comments/1dswnfa/authy_for_macos_install_attestation_token_is/) where users blame on the same problem. I will monitor the situation, but i din't find something useful at the moment.

**Comment by kolchurinvv** [comment]
Any suggestions for 2FA Authenticator apps alternatives that could also be worked into a Raycast extension?

**Comment by guga4ka** [comment]
@kolchurinvv my plan B is export all tokens from authy and import it to Bitwarden. Let's wait a bit for Authy statement, seems like not only 3rd party clients has this issue, but their own ipad app too. I will push the update to extension with export functionality so pls do not re-install extensions.
