### ISSUE TITLE
[Claude] Please add the new `claude-3-5-sonnet-20240620` model to the list

### ISSUE THREAD

**Issue by karnilaev** [raycast/extensions#13090]
### Extension

https://www.raycast.com/florisdobber/claude

### Description

Hello. Yesterday a new Claude model `claude-3-5-sonnet-20240620` has released. Please add it to the list.

**Comment by florisdobber** [comment]
#13080 is just waiting to be merged, after which it will be added to the list 🥳

**Comment by florisdobber** [comment]
PR #13080 got merged, so this can be closed.
@raycastbot close this issue
