### ISSUE TITLE
[Bitwarden Vault] Allow login with device

### ISSUE THREAD

**Issue by onjour** [raycast/extensions#13093]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Apparently there's no way to login to Bitwarden with a device from Raycast, I'd be great if we could.

**Comment by jomifepe** [comment]
Hey, I'm not sure I understood the issue, what do you mean by "device"?

**Comment by onjour** [comment]
> Hey, I'm not sure I understood the issue, what do you mean by "device"?

https://bitwarden.com/help/log-in-with-device/

**Comment by jomifepe** [comment]
Hey, sorry for the delay. I don't think that's supported by the CLI, and I'm limited to it's capabilities.
