### ISSUE TITLE
Snippet auto-expansion doesn't remove keyword in controlled Form.TextArea

### ISSUE THREAD

**Issue by thomaslombart** [raycast/extensions#1309]
Raycast version: 1.32.0

## Description

I tried using a snippet with auto expansion in a controlled `Form.TextArea` element and the keyword triggering the expansion is not removed.

## Steps To Reproduce

1. Use an extension with a controlled `Form.TextArea`
2. Auto-expand a snippet with a keyword

https://user-images.githubusercontent.com/16003285/162053602-bf782687-9deb-4c38-baba-0840c5a258f3.mp4

## The current behavior

The keyword is not removed when expanding a snippet.

## The expected behavior

The keyword should be removed when expanding a snippet.

**Comment by mathieudutour** [comment]
Should be fixed in 1.45!
