### ISSUE TITLE
[Ollama AI] Continue chat conversation with pre-defined commands

### ISSUE THREAD

**Issue by nirtamir2** [raycast/extensions#13103]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

Hi,
I’d like to see Ollama integration with Raycast enable chat conversations instead of providing a single answer for the pre-defined commands. I think it would be beneficial if this feature were configurable, allowing users to add more messages to pre-defined prompts and conversations.

### Who will benefit from this feature?

Everyone who wants to have a more effective conversation with Ollama and is not satisfied with the initial outcome may choose to refine their approach by engaging in further conversation.  Also, a common use case is to remove the useless explanation text that we may get in the response. 

### Anything else?

![image](https://github.com/raycast/extensions/assets/16452789/dc166c01-6636-4c6e-ba91-9b2a3a47f885)
I want to fine-tune the response here and guide it to make it shorter / show more examples. I would like to have a chat text input so I can write my response and continue the conversation

![image](https://github.com/raycast/extensions/assets/16452789/f5441ac1-e7ab-43ae-a3b0-e8a6d9756644)
Here is an example that I would like to ask the model to not include the starting line

I notice that Ollama extension can to handle chat messages (although I did not understand it at first because the UI is different compare to the common ai chat examples), but I want such ability with the pre-defined prompts

![image](https://github.com/raycast/extensions/assets/16452789/df57c8e9-6098-4232-851b-65c0795cf854)

**Comment by MassimilianoPasquini97** [comment]
I @nirtamir2, as you notice there is already a chat feature command called "Chat with Ollama" and you can create custom single shot command too with "Create Custom Command". But you get me thinking that can be useful to transfer response of a single shot command to a new chat where you can continue the conversation. Let me know what do you think and if you have more suggest to improve this extension.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot assign me

**Comment by nirtamir2** [comment]
> I @nirtamir2, as you notice there is already a chat feature command called "Chat with Ollama" and you can create custom single shot command too with "Create Custom Command". But you get me thinking that can be useful to transfer response of a single shot command to a new chat where you can continue the conversation. Let me know what do you think and if you have more suggest to improve this extension.

Exactly 💯 
I find myself asking the same questions but I want to continue the conversation and refine in the same context

**Comment by MassimilianoPasquini97** [comment]
I have added "Continue as Chat" with "CMD+N" shortcuts on actions menu. This action will save the response as a new chat and open "Chat with Ollama" for continue the conversation. Before publishing this feature, @nirtamir2 I will appreciate you opinion and if an other keyboard shortcut is more appropriated for the actions.

![Screenshot 2024-07-29 alle 07 37 55](https://github.com/user-attachments/assets/08febd23-f776-4cef-adbc-e43584295561)

**Comment by MassimilianoPasquini97** [comment]
Pull Request #13881 has been opened to introduce this new feature.

**Comment by MassimilianoPasquini97** [comment]
The pull request has been merged, so this issue can now be closed.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue
