### ISSUE TITLE
[U301 URL Shortener] ...Shorten URL From clipboard and not selected text

### ISSUE THREAD

**Issue by dags170291** [raycast/extensions#13113]
### Extension

https://www.raycast.com/shiny/u301-url-shortener

### Description

Can you please add ability to shorten url from clipboard instead of select text? The workflow with selected text only is a bit short handed. 

### Who will benefit from this feature?

Users who copy/share urls from applications like google drive and dropbox that goes directly to the clipboard.

**Comment by shiny** [comment]
I love this idea! 

My thought is to add a separated command called "Shorten URL Using Clipboard"

- It should copy the shortened result back to the clipboard.
- It should also support batch shortening, with each URL on a separate line.

I wonder if you have any suggestions on this.

**Comment by shiny** [comment]
Shorten URL From clipboard is available now 🎉

**Comment by MagnusHJensen** [comment]
> Shorten URL From clipboard is available now 🎉

You can close this issue using the ray commands listed.

`@raycastbot close this issue`

**Comment by shiny** [comment]
@raycastbot close this issue

**Comment by shiny** [comment]
> > Shorten URL From clipboard is available now 🎉
> 
> You can close this issue using the ray commands listed.
> 
> `@raycastbot close this issue`

Got it

**Comment by dags170291** [comment]
Thanks for adding, much appreciated
