### ISSUE TITLE
Gemini Extension API Key Problem

### ISSUE THREAD

**Issue by 77lez** [raycast/extensions#13117]
### Description

Hello, I am trying to set up my Gemini for Raycast extension, [click here to access it](https://www.raycast.com/EvanZhouDev/raycast-gemini). I got my API key and put it in the set up screen, everything goes well, until I get this error :
<img width="813" alt="Capture d’écran 2024-06-23 à 00 15 22" src="https://github.com/raycast/extensions/assets/91977318/d0c6c98b-2d73-4fe4-a7c6-d4bbbfcf9b65">

### Steps To Reproduce

1. [Get the extension.](https://www.raycast.com/EvanZhouDev/raycast-gemini)
2. Putting in your Gemini API key, by executing a command
3. Trying to send a request to Gemini.

> This extension lets you use both of Google AI's models, "Gemini 1.5 Flash", and "Gemini 1.5 Pro". 1.5 Pro requires a Gemini Advanced active subscription, which costs €21.99 ($23.51 according to Google). I chose 1.5 Pro from the extension's settings because I have an active subscription

> You can also put in your Gemini API key by going to the extension's settings, selecting it, and put in your key. It should look like this :

> By [subscribing](https://gemini.google.com/advanced?utm_source=google&utm_medium=cpc&utm_campaign=sem_lp&gad_source=1&gclid=CjwKCAjw7NmzBhBLEiwAxrHQ-QknXfXT43clSQsaG74LnmEbC1_juFa5GgXYN9-DVKsLsvIF2mSPUBoCDHYQAvD_BwE) to Gemini advanced, you also get all of Google One's perks, including 2TB of cloud storage.

<img width="329" alt="image" src="https://github.com/raycast/extensions/assets/91977318/841a58b9-5b67-4990-b243-60d8106c52d2">

### Current Behaviour

Error saying :

Could not access Gemini.
This may be because Gemini has decided that your prompt did not comply with its regulations. Please try another prompt, and if it still does not work, create an issue on GitHub.

### Expected Behaviour

I expect for this thing to work!!!

**Comment by 77lez** [comment]
I chose API bug, because it's related to an API key..

**Comment by mathieudutour** [comment]
It's related to an API key but it's not related to the Raycast API ;) 

Please reopen an issue choosing the extension bug so that the extension's authors are properly pinged

**Comment by 77lez** [comment]
oh, thanks for the information ! it's the first time i do this issue report thing.
