### ISSUE TITLE
[Arc] Performance is not good. There is a different implementation, please use it

### ISSUE THREAD

**Issue by arabshapt** [raycast/extensions#13126]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

It would be perfect if you could improve performance. There is alfred workflow that does the same but much faster. Both are using applescripts. It is written in JS, so you will understand it. Please make it faster. I wanted to extend it to switch to specific tabs using shortcuts and without raycast UI popping up, but the delay of the current script is a dealbreaker. I looked into it and I know that looping through all those windows, tabs and spaces takes time, but alfred(using the applescript manages to do it faster)(The speed has nothing to do with alfred, but only with applescript that is used hier that needs to change). 

From my investigation I can tell you where I think the difference lies:
Current implementation just passes Tab Object that doesn't contain coordinates of the tab in Art, so once the user chooses one of the options(tabs) you loop through everything again, which is unnecessary. Extend the Tab Object to also include not tab.id, but spaceIndex, windowIndex and tabIndex. Then you can just go there. 🙂

I hope arc implements this feature natively...

https://alfred.app/workflows/caicailiushui/arc-tabs-and-spaces/

**Comment by xilopaint** [comment]
Which extension command are you talking about, and how many tabs do you have open? The extension seems fast to me.
