### ISSUE TITLE
[Omnivore] Creates empty label when the label placeholder left empty

### ISSUE THREAD

**Issue by trijste** [raycast/extensions#13134]
### Extension

https://www.raycast.com/karolusd/omnivore

### Raycast Version

1.77.1

### macOS Version

14.5

### Description

When I save a link and add its URL to the URL argument, I leave the label argument empty. When I look in Omnivore, the saved article has a literal empty label.

### Steps To Reproduce

Copy the URL, launch Quick Capture in Raycast, paste the URL into the URL argument, and leave the labels argument empty. Capture.

### Current Behaviour

Creates empty label in Raycast

### Expected Behaviour

Article saved without a label of any kind

**Comment by KarolusD** [comment]
@trijste thank you for reporting! This should be fixed in this pull request: https://github.com/raycast/extensions/pull/13136

Also as Omnivore allows to have single label from few words i.e: "this is a label", I allowed only commas to be a label separators.
