### ISSUE TITLE
Adding Claude 3.5 Sonnet to Raycast AI Chat

### ISSUE THREAD

**Issue by yawen-d** [raycast/extensions#13143]
### Description

Adding Claude 3.5 Sonnet to Raycast AI Chat

### Who will benefit from this feature?

Everybody who subscribed to Raycast AI Pro.

**Comment by mathieudutour** [comment]
We released it yesterday.

But this issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) next time? 😊
