### ISSUE TITLE
[Bitly URL Shortener] TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by ejsing** [raycast/extensions#1315]
# Extension – [Bitly URL Shortener](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/bitly-url-shortener/)
Author:

## Description
I get an error when I open Bitly after pasting in the access token from Bitly.

## Steps To Reproduce

1. Install Bitly extension
2. Create free account on Bitly
3. Reset password and create new password
5. Go to https://app.bitly.com/settings/profile/
6. Click API
7. Enter password in the "Enter password" field
8. Click "Generate token"
9. Copy the shown token to the clipboard
10. Paste token in Bitly extension
11. Open Raycast
12. Type "Bitly" and hit enter
13. TypeError [ERR_INVALID_URL]: Invalid URL

**Comment by lkxed** [comment]
@ejsing It seems what this extension does is to shorten a URL from your **clipboard**. So if you haven't copy a valid url into your clipboard before using this extension, it will give your the error. So It is NOT a bug.

However, I do think the author should point this out. :)

**Comment by mathieudutour** [comment]
I'm not the author, but it's something that could be improved for sure!

**Comment by lkxed** [comment]
@mathieudutour Sorry I mistook you as the author. I'd love to. But I don't know where to add this hint, extension/command description or `README.md`?

I guess you are the real author @blessanm86, what do you think of this issue?

**Comment by blessanm86** [comment]
@lkxed isn't the command description good enough. I can also make it more explicit in the readme.

**Comment by lkxed** [comment]
@blessanm86 Oh I read the command description again…yeah it is good enough I think. Anyway, making it more explicit in the readme sounds good to me. Maybe something like "first copy a url to shorten, then run the command", since @ejsing is confused here :)

**Comment by ejsing** [comment]
The issue was indeed that I hadn't copied anything yet. I found out a few weeks later, when I set up Raycast on my work Mac and it just worked.

**Comment by mathieudutour** [comment]
handling errors more gracefully would probably be a good improvement

**Comment by blessanm86** [comment]
@mathieudutour @ejsing improved error handling.
