### ISSUE TITLE
Default for Sort List

### ISSUE THREAD

**Issue by njthebaud** [raycast/extensions#13156]
### Extension

https://www.raycast.com/jimluo/later

### Description

Hi,

I really like the extension so far but would like the option of changing the sorting it defaults to when opening the list. Right now it defaults to "Time" but would like the option of changing  it to "Read" so that whenever I open the list that's how it's sorted.

### Who will benefit from this feature?

Anyone who doesn't want Time to be the default sorting behavior.

**Comment by Ross249** [comment]
Thank you for advising. Appending a preference for sorting is a really good feature, I will bring it in the next version.
