### ISSUE TITLE
[Apple Notes] preview in search notes

### ISSUE THREAD

**Issue by omeruzvn** [raycast/extensions#13166]
### Extension

https://www.raycast.com/raycast/apple-notes

### Description

it would be nice to have preview (where you can quickly copy something without opening the app) when you search notes imo

### Who will benefit from this feature?

pretty much all users

### Anything else?

bear extension has this

![CleanShot 2024-06-25 at 22 34 23@2x](https://github.com/raycast/extensions/assets/173843465/f71cd332-32c4-4670-a43c-68319f27ea10)

**Comment by thomaslombart** [comment]
![CleanShot 2024-07-03 at 10 41 16@2x](https://github.com/raycast/extensions/assets/16003285/f369da57-8f27-43c6-976d-1028189b92b6)

We have this `View Note` action. Is it what you're searching for?

**Comment by omeruzvn** [comment]
oh yeah i didnt see that, it'll do the job just fine. thanks

**Comment by omeruzvn** [comment]
actually, i dont think there is a way to make it default but it would be a lot better, isnt it? we wouldnt have to leave raycast
