### ISSUE TITLE
[Connect to VPN] manually check active VPNs in list

### ISSUE THREAD

**Issue by zlobnic** [raycast/extensions#13163]
### Extension

https://www.raycast.com/rasmusbe/connect-to-vpn

### Description

I have 6+ vpns in list. Not all of them is vpn. And I usually use only one. Can you add settings to disable unnecessary in list?

Image below (it is not vpn):

![CleanShot 2024-06-25 at 18 41 27@2x](https://github.com/raycast/extensions/assets/39958947/e55d9068-7133-401d-9740-36261cfdb230)

and I'd like to disable them from the extension's settings

![CleanShot 2024-06-25 at 18 47 05@2x](https://github.com/raycast/extensions/assets/39958947/8ffe1d2d-47ad-4109-a537-39485c7fe53f)

**Comment by stonerl** [comment]
You can add the ones you are using the most to your favorites list.

**Comment by stonerl** [comment]
What kind of services are these?   Can you run `networksetup -listnetworkserviceorder` and give us the output

**Comment by zlobnic** [comment]
> What kind of services are these? Can you run `networksetup -listnetworkserviceorder` and give us the output

![CleanShot 2024-06-25 at 19 38 30@2x](https://github.com/raycast/extensions/assets/39958947/683f5338-dd4f-488b-83eb-33530f8bd526)

Attached. I'd like to see that list via extension setting and disable using checkbox, for example.

Thank you for your response!

**Comment by rasmusbe** [comment]
What do you get when you run
`networksetup -showpppoestatus "Handheld Barcode Scanner"` and `networksetup -showpppoestatus "LG Monitor Controls"`?

Right now we take the list from `networksetup -listnetworkserviceorder` and check the PPOoE Status.
If it returns "invalid" we mark it as a non VPN interface.

**Comment by zlobnic** [comment]
networksetup -showpppoestatus "Handheld Barcode Scanner" and networksetup -showpppoestatus "LG Monitor Controls"

`disconnected`

**Comment by stonerl** [comment]
Are both devices registered as usbmodem? You blurred them in your first output.

**Comment by zlobnic** [comment]
Yup!

I'd like to input "VPN" in Raycast and immidiately get connected to VPN, without choosing any (would be great option).

**Comment by stonerl** [comment]
@zlobnic what is the output for `networksetup -listallhardwareports`

We might compare the service list with the hardware ports and sort them out.
