### ISSUE TITLE
[Toggl Track] Show current task and timer on macOS menu bar

### ISSUE THREAD

**Issue by lukebars** [raycast/extensions#13165]
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Description

It would be nice to show the current task and timer on macOS menu bar. This would remind me to stop my task.

### Anything else?

I could help developing this if needed.

**Comment by bkeys818** [comment]
This is a feature I plan on implementing, that being said, it might be a while. I'm incredibly at the moment.

**Comment by lukebars** [comment]
Done. Enjoy guys!
