### ISSUE TITLE
[Amazon AWS] it became very buggy in comparison to earlier version

### ISSUE THREAD

**Issue by arabshapt** [raycast/extensions#13178]
### Extension

https://www.raycast.com/Falcon/aws

### Raycast Version

1.77.3

### Description

Not all pipeline are loaded immediately and it is not only about waiting. Waiting doesn't help. I had to remove and enter the same word multiple times. Very reproducible. It is not random. And what does rate exceeded mean? I never saw that before

ThrottlingException: Rate exceeded

### Steps To Reproduce

just search for pipelines

**Comment by jfkisafk** [comment]
@raycastbot assign me

**Comment by jfkisafk** [comment]
>  And what does rate exceeded mean? I never saw that before

Although I couldn't find the exact limits for the management API(s) transaction per second (TPS) for AWS code pipeline, AWS will always enforce certain TPS limits on the usage of the API(s) against your account in the region, to ensure your calls don't brown out their resources that might be serving multiple accounts (noisy neighbor). This [post](https://repost.aws/knowledge-center/elastic-beanstalk-api-throttling-errors) explains it for Beanstalk, but concept is similar for CodePipelines too. To support all actions we make 2 calls per pipeline now:

https://github.com/raycast/extensions/blob/f1c66279695c158fbf4d7484aadaf3336707224e/extensions/amazon-aws/src/hooks/use-codepipeline.ts#L21-L49

So I am guessing your constant retries to get the intended pipelines in the search results might have led to throttling against your account.

**Comment by jfkisafk** [comment]
I understand it can be non-intuitive - do you think a detailed instruction of how to use this command in the README will help? Otherwise, I can try to look into optimizing this command further in upcoming weeks to make it more intuitive.

**Comment by arabshapt** [comment]
Thank you for your explanation and your offer to help! It is not optimal for a tool that is meant for keyboard first usage to require scrolling... But I understand the problem... I found it really helpful to be able to check my pipelines and their status in this extension. I never had this kind of problem with it before this optimization. I think search through the whole list is necessary and caching for 5 or 10 seconds would also save some data, but we have lots of pipelines in our project. 15 to 20 Microservices with a pipeline for each feature branch, master and release. Please consider adjusting it:) I wish I could fork this branch, adjust it locally and at the same time get updates from your main branch(similar to standard forking on GitHub), bit last time I checked it just copies the latest state of the extension without any history(commits) or upstream. Similar to this pipeline command I wish you had one for code commit to search though repos, pull request, branches, tags. Aws website feels slow similar to Amazon, so this extension is extremely helpful when it works). Even if it is wasteful sending all these requests, it was very helpful. One could load all pipeline, but execution data only for visible(first 10 or 20). But generally I wouldn't optimize and loose functionality if these requests are free or cost little, because they are very useful. Thank you again:)

**Comment by jfkisafk** [comment]
@arabshapt Yeah I am considering adjusting it. The problem is unlike SQS/Secrets Manager list API(s), CodePipeline List API(s) do not offer typeahead support. Instead of raycast pagination, the intermediate solution I can think of is loading all pipelines and state, adding 500ms wait before each paginated call, a toast at the bottom showing how many pipelines have been loaded. And maybe a time-based caching (but not sure if it would help with memory constraints or make it worse)

>  Similar to this pipeline command I wish you had one for code commit to search though repos, pull request, branches, tags.

I see you already created this issue: https://github.com/raycast/extensions/issues/12299#issue-2291216365. Can you update the issue and re-prioritize the things you'd want in the first iteration. Like listing resources (repos, pull requests, branches etc.) might be quicker to implement than forms for creating pull requests, branches etc. So we can go the iterative approach here.

**Comment by arabshapt** [comment]
@jfkisafk, I updated my comment) I hope it is ok:)

**Comment by jfkisafk** [comment]
Also @arabshapt I was curious if you need other direct actions on CodePipeline command other than the ones present, "Toggling stage transitions", "Retry Failed Stage", "Stop Execution". Those were the ones I use the most for operations, but I am not a power user of CodePipelines.

**Comment by arabshapt** [comment]
@jfkisafk , I am also not a Poweruser:) I typically want to know whether my pipeline has failed(in progress, success). It would be nice to know at which stage it failed(build, deploy, test). Then I go there and analyze the problem. Sometimes in logs and sometimes in Cloudformation. The main thing I loved about this feature was searching and seeing  the status or opening the page of the correct pipeline. What searching/filtering are you using? Does it make sense to use fzf or similar here? The question is how forgiving should the search be. But I thing it was good
