### ISSUE TITLE
[Brew]...search 

### ISSUE THREAD

**Issue by amogh344** [raycast/extensions#13181]
### Extension

https://raycast.com/nhojb/brew

### Raycast Version

1.77.3

### macOS Version

14.5

#### Error:
```
Error: Command failed: /opt/homebrew/bin/brew info --json=v2 --installed
/bin/sh: /opt/homebrew/bin/brew: No such file or directory

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at Pipe.<anonymous> (node:net:337:12)
```

### Steps To Reproduce

1. brew 
2. search
3. failed to serach

**Comment by nhojb** [comment]
@amogh344 from the error it looks like you don't have homebrew installed. You can install by following the instructions found here: https://brew.sh

The other possibility is that you have an Intel Mac & the extension was searching for brew in the wrong location. If so you can set a custom path in Settings -> Extensions -> Brew (see screenshot)

<img width="1112" alt="Screenshot 2024-06-21 at 10 25 10" src="https://github.com/raycast/extensions/assets/312540/0831cd85-6406-4bbe-ab2b-5e1c163220e6">

**Comment by jfkisafk** [comment]
@amogh344 closing this issue! Please feel free to re-open in case the above instructions do not work.

**Comment by jfkisafk** [comment]
@raycastbot close this issue
