### ISSUE TITLE
[Jira] Epic drop down list is empty

### ISSUE THREAD

**Issue by TiboCiteo** [raycast/extensions#13187]
### Extension

https://www.raycast.com/raycast/jira

### Raycast Version

1.77.3

### Description

When I try to create a Jira issue, all drop-down lists and auto-complete features work except for the 'Epic' drop-down list.

### Steps To Reproduce

When I try to create a Jira issue, all drop-down lists and auto-complete features work except for the 'Epic' drop-down list.

### Expected Behaviour

'Epic' drop-down list display epics

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/12646, so I'll mark it as such.
