### ISSUE TITLE
[Ollama] Remove "local" server

### ISSUE THREAD

**Issue by nwithan8** [raycast/extensions#13183]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

Extension seems to always default to "local" server over other configured servers. When an Ollama server is not running locally on device, this makes the default behavior an error complaining about connection failure.

Could we add an option to delete "Local" the same way we can delete remote servers?

**Comment by MassimilianoPasquini97** [comment]
@raycastbot assign me

**Comment by nwithan8** [comment]
Reopen.
