### ISSUE TITLE
Favorite section for GIF's

### ISSUE THREAD

**Issue by jiserra** [raycast/extensions#1319]
# Extension – [GIF Search](https://github.com/raycast/extensions/tree/main/extensions/gif-search)

Author: @josephschmitt 

**Describe the feature and the current behavior/state.**
The idea is to have a Favorites section with bookmarked GIF's. I find myself sometimes looking over and over for the same gif and I don't always remember the exact keyword to find it. It would be great to have a Favorite section with all of these for quick access.

**Who will benefit from this feature?**
Everyone who uses a particular GIF more than once!

**Any Other info.**
Love this extension!

**Comment by josephschmitt** [comment]
This is out now!
