### ISSUE TITLE
"Open in Zotero" fails when Zotero app not launched

### ISSUE THREAD

**Issue by lutefiasco** [raycast/extensions#1320]
# Extension – [Zotero](https://github.com/raycast/extensions/tree/main/extensions/zotero/*)

Author: @sadanand-singh

## Description
If the Zotero app is not running when the extension runs, "Open in Zotero" opens the app to a blank window with no library loaded.

## Steps To Reproduce

1. Make sure Zotero app is not running
2. Invoke Zotero extension, search for an item, "return" for default action (Open in Zotero).3. 

## The current behavior
App launches, but does not load default library, item selected in extension is not opened

## The expected behavior
App launches, opens default library, opens item selection from extension
### Raycast version

Version: 1.32.0
Zotero version: 6.0.4

**Comment by sadanand-singh** [comment]
Yes this is an issue with zotero select links reported also on forums: https://forums.zotero.org/discussion/95789/zotero-select-links-dont-work-on-app-launch

**Comment by lutefiasco** [comment]
I'm running Zotero on a Mac, not windows, but I assume it's still an issue with Zotero. 

As a sidenote, I saw your local SQL version of the plugin is pending, and I'm _thrilled_. Many, many, many thanks for moving it from the slow web API to the speedy local version.
