### ISSUE TITLE
[Figma File Search] Add support for Enterprise & Orgs

### ISSUE THREAD

**Issue by jonohunt** [raycast/extensions#13202]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

You can only use this extension with Figma for Teams (maybe also individuals?), but not  organisations or enterprise. 

It would be really useful if this extension was also made to work with organisations and enterprise.

### Who will benefit from this feature?

Everyone who uses Figma for organisations and enterprise.

**Comment by GLaDO8** [comment]
@jonohunt the extension also works for organisations and enterprise accounts. After logging in with Figma, you need to provide team IDs for every team you want to search in. You can do this from extension settings. For multiple teams, you can provide a comma-separated list of team IDs. Below is an image for reference.

![image](https://github.com/raycast/extensions/assets/22849100/7a4318b3-fcaf-4670-aba7-2cb9ea204db1)

**Comment by jonohunt** [comment]
@GLaDO8 Thanks. The URL for our files doesn't contain "**team**", so instead of URLs like 
https://www.figma.com/files/team/12345678987654321/NameOfTeam...

we have URLs like
https://www.figma.com/files/12345678987654321/NameOfTeam...

I've tried entering the long long number, which the extension seems to accept (12345678987654321), but when I try to search for Figma file I get the following error

![CleanShot 2024-06-28 at 9  53 38@2x](https://github.com/raycast/extensions/assets/2163340/a71887cc-5209-4767-ac6f-93ba08c76e09)



Could it be that the extension has accepted the ID and PAT, but there's a bug causing my problem? 🤔

**Comment by GLaDO8** [comment]
@jonohunt if you go to Figma Home, you should be able to see a team page like the image below. You can copy the link to the team and find the ID there. If possible can you share a screenshot of your Figma home page?

![image](https://github.com/raycast/extensions/assets/22849100/017f45e8-33ad-4534-9477-467efa8188f6)

**Comment by jonohunt** [comment]
Ah, if I do that it's slightly different. Maybe it's a permission thing from my company? 🤔 

![CleanShot 2024-06-28 at 11  08 01@2xb](https://github.com/raycast/extensions/assets/2163340/20ebe29b-927e-4b3f-a7b1-f67a3824e1a0)

**Comment by jonohunt** [comment]
…I found out that I can get the IDs by clicking on "All Teams" in the sidebar, then right clicking on any of the teams under "Your Teams".
