### ISSUE TITLE
[Todoist] ...

### ISSUE THREAD

**Issue by lucymhdavies** [raycast/extensions#13209]
### Extension

https://www.raycast.com/doist/todoist

### Raycast Version

1.77.3

### macOS Version

14.5 (23F79)

### Description

Menu bar Filter Query does not appear to support the query: `due before: +1 hour`

I've tried a bunch of other filters, all of which seem to work fine, but this one in particular does not work. I'm wondering if somewhere the extension is parsing the filter wrong.

### Steps To Reproduce

* Have some tasks in Todoist, due within the next hour
* Set Menu Bar Tasks to Filter view, with filter: `due before: +1 hour`

### Current Behaviour

No tasks are shown in the menu bar

### Expected Behaviour

Menu bar should show tasks due within the next hour

**Comment by jfkisafk** [comment]
This is not a parsing issue and a problem with Todoist Api and how [filters](https://todoist.com/help/articles/introduction-to-filters-V98wIH) are being handled. I tried by creating a task due within next hour but when I put the filter `due before: +1 hour` or even `due before: +4 hours` (as suggested on their filter documentation), I did not get results, both in Raycast and Postman.

But when I switched to `due before: +9 hours` (based on my local time this would mean next day), I saw the task due in the next hours. There is some discrepancy in todoist api on how this filter is being handled.

**Comment by lucymhdavies** [comment]
ah. then yeah, not a Raycast issue.

I'll see if I can get support from Todoist :)

**Comment by lucymhdavies** [comment]
From Todoist support:

> Thank you for your patience. As promised, this is a follow-up on your question regarding the API not handling ''overdue'' or ''due before: +1 hours''.
> 
> Our developers explained to me that this is intentional. Extended, more complex filters like these are implemented by our clients, and not by backend.
> 
> This means that if you want to consume the API and filter by overdue, all you need to do is to filter in the code you are writing.

**Comment by jfkisafk** [comment]
Hey @lucymhdavies , is there a query that works if we substitute +x hours with iso timestamp client-side and then send the query to todoist api?

**Comment by lucymhdavies** [comment]
That is a very good question. If we can do something client-side to say "all tasks before TIMESTAMP", that could work. There's a bunch of UX considerations, but ignoring those for now...
it all depends on the API allowing "Before TIMESTAMP" type filters.



and it seems, no, it doesn't.


From experimentation, with a BUNCH of different filters...

```
#
# Things which the API accepts, but which return nothing
#

# due before: 8th july 4pm
filter="due%20before%3A%209th%20july%201am"

# due before: July 9th 2024, 1am
filter="due%20before%3A%20July%209th%202024%2C%201am"
# Response: []

# due before: July 9th 2024, 11am
filter="due%20before%3A%20July%209th%202024%2C%2011am"
# Response: []

# due before: July 9th 2024, 12pm
# (about 24h from now)
filter="due%20before%3A%20July%209th%202024%2C%2012pm"
# Response: []


#
# Things which do work, but aren't helpful
#

# due before: July 9th 2024, 1pm
# (about 25h from now)
filter="due%20before%3A%20July%209th%202024%2C%201pm"
# Response: (lots of tasks; all today)

# due before: July 9th 2024, 11pm
filter="due%20before%3A%20July%209th%202024%2C%2011pm"
# Response: (lots of tasks; all today)

# due before: tomorrow
filter="due%20before%3A%20tomorrow"
# Response: (lots of tasks)

# due before: July 12th 2024, 1pm
# 4 days from now
filter="due%20before%3A%20July%2012th%202024%2C%201pm"
# Response: (lots of tasks; all today)

# due before: friday
filter="due%20before%3A%20friday"
# Response: (lots of tasks, all due from today at soonest and thursday at latest)

# due before: next week
filter="due%20before%3A%20next%20week"
# Response: (lots of tasks, all due on various days this week)

# due before: 1am friday
filter="due%20before%3A%201am%20friday"
# Works as expected! - so the comma is likely a problem

# due before: July 12th 2024 1pm
filter="due%20before%3A%20July%2012th%202024%201pm"
# Response: (lots of tasks, up to and including 11th July) - so the comma definitely an issue

# due before: 3pm tomorrow
filter="due%20before%3A%203pm%20tomorrow"
# all tasks today 

# due before: 11pm tomorrow
filter="due%20before%3A%2011pm%20tomorrow"
# all tasks today

# due before: 1am wednesday
filter="due%20before%3A%201am%20wednesday"
# suddenly, a bunch of tasks

# due before 3pm tuesday
filter="due%20before%3A%203pm%20tuesday"
# all today

# due before: 11pm tuesday
filter="due%20before%3A%2011pm%20tuesday"
# all today


#
# Bunch of timestamp formats which do not work
#

# due before: 2024-08-09T12:00:00.000000Z
filter="due%20before%3A%202024-08-09T12%3A00%3A00.000000Z"
# Response: The search query is incorrect

# due before: 2024-08-09T12:00:00
filter="due%20before%3A%202024-08-09T12%3A00%3A00"
# Response: The search query is incorrect

# due before: July 9th 2024, 1am GMT
filter="due%20before%3A%20July%209th%202024%2C%201am%20GMT"
# Response: The search query is incorrect

# due before: 2024-07-08T16:00:00+0000
filter="due%20before%3A%202024-07-08T16%3A00%3A00%2B0000"
# The search query is incorrect

# due before: Mon, 08 Jul 2024 16:00:00 +0000
filter="due%20before%3A%20Mon%2C%2008%20Jul%202024%2016%3A00%3A00%20%2B0000"
# The search query is incorrect

# due before: 1720454400
filter="due%20before%3A%201720454400"
# The search query is incorrect




#curl -s -X GET   https://api.todoist.com/rest/v2/tasks?filter=${filter}   -H "Authorization: Bearer ${token}"
curl -s -X GET   https://api.todoist.com/rest/v2/tasks?filter=${filter}   -H "Authorization: Bearer ${token}" | jq -c .[].due

```


In Todoist, I have a bunch of tasks at various times throughout today. I also created a bunch due at various times tomorrow, and I have all sorts of tasks scheduled later this week

Lots of timestamp formats are just outright rejected by the API. Looks like it's only dates in the formats listed on https://todoist.com/help/articles/introduction-to-filters-V98wIH, and commas mess things up


But for our purposes... the closest I've been able to get it to do is all tasks today (which we can already do).



Seems their API is indeed written in a way to discourage attempts to do granular timestamp filtering server-side.


Unless I'm missing some test cases... seems the only way we could make this work would be to pull all tasks due today, and then do the filtering client-side. But I don't know if that's going to hit against https://github.com/raycast/extensions/issues/10127 or not

**Comment by jfkisafk** [comment]
Yeah my testing also concluded the same thing and even `due before: +x hours` only worked for showing the tasks due today (if `x` was adjusted properly). In my opinion, pulling all the tasks to perform filtering will conflict with https://github.com/raycast/extensions/issues/10127 and chances are we might not even get to the filtering part before seeing memory issues. 

For users with smaller number of tasks this might work, but we might need to design this with worst-case scenario in mind. Thinking from limiting this query standpoint, from Todoist API I couldn't see a way to get task count for user other than pulling all tasks, which will also cause issues. Plus, limiting the query for some users and not for others is a UX variance which might not be ok.

I think we can close this until we solve the memory issues. What do you think?

**Comment by lucymhdavies** [comment]
Agreed

**Comment by lucymhdavies** [comment]
Surprise update from Todoist today!

> I wanted to reach out to you and share an update about your feedback regarding the API not handling ''overdue'' or ''due before: 1+ hours''.
>
> As promised, I've shared your feeback with our Product team and later discussed this with our developers. I'm very happy to let you know that our Backend team is currently working on this so that the API supports complex filters. This should become available in the new version of Todoist. I can see from our internal discussions that our engineers are currently running the final tests before releasing these improvements! 🚀 
>
> I'd like to take this opportunity to thank you for helping us keep Todoist great, Lucy.

**Comment by lucymhdavies** [comment]
hopefully, once the API changes have been made, we won't need to re-open this.

but we'll see what happens 🤞

**Comment by lucymhdavies** [comment]
From my testing...

"overdue | due before: +1 hour"

Now works as expected

So I think they may have released the API changes
