### ISSUE TITLE
[Unsplash] ... Sign in (Unsplash) link is not valid

### ISSUE THREAD

**Issue by Rahmanism** [raycast/extensions#13200]
### Extension

https://www.raycast.com/eggsy/unsplash

### Raycast Version

1.77.3

### macOS Version

14.5

### Description

I added the secret key to the Unsplash extension and clicked the continue button. However, when I clicked the sign-in button, it opened a browser link to sign in to Unsplash, and I received an error message stating, “The redirect URI included is not valid.” I also tried copying the authorization link directly, but I encountered the same issue.

### Steps To Reproduce

1. Install the Unsplash extension in Raycast
2. Add the api and secret keys.
3. Click on the "sign in" button

### Current Behaviour

Gives me this error: "The redirect uri included is not valid."

### Expected Behaviour

Let me authorize the sign in.

**Comment by eggsy** [comment]
Check the extension Readme.
