### ISSUE TITLE
[Pins] Allow deactivating Pins (w/o deleting)

### ISSUE THREAD

**Issue by dudido** [raycast/extensions#13210]
### Extension

https://www.raycast.com/HelloImSteven/pins

### Description

I would like to be able to deactivate a pin, thereby hiding it from select menus (the menubar, the pins menu, or both). Ideally, I want to be able to run check for expirations, and mark all pins referencing dated items (apps uninstalled or folders moved e.g.) as deactivatd

### Who will benefit from this feature?

Anyone frequently changing Pins and setups

**Comment by SKaplanOfficial** [comment]
The first part of this (a visibility setting) is added in #13358. The second part (running actions upon pin expiration) will be ready soon.

**Comment by dudido** [comment]
This is great! Thank you @SKaplanOfficial !! Pins is the best app launcher ever!

I guess I should have mentioned that earlier, but would it be possible to have the same visibility settings for groups too, so that the setting is applied to all contained pins?

**Comment by SKaplanOfficial** [comment]
@dudido Adding that in an upcoming update, just trying not to overwhelm the Raycast team with huge PRs
