### ISSUE TITLE
[Ruler] option to not have the distance copied to clipboard

### ISSUE THREAD

**Issue by JasonBagley** [raycast/extensions#13228]
### Extension

https://www.raycast.com/anwarulislam/ruler

### Description

It would be great to have a toggle in the settings to not have the distance copied to clipboard. I find myself using the ruler numerous times and my clipboard history then becomes clogged up with lots of random numbers.

**Comment by anwarulislam** [comment]
@JasonBagley thanks for opening the issue. I am working on this
