### ISSUE TITLE
[YouTube Downloader] ...Set download location

### ISSUE THREAD

**Issue by Chamca** [raycast/extensions#13234]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

Ability to set specific and persistent download path different than the default "Downloads" folder

### Who will benefit from this feature?

Anyone with a mess of a download folder.

### Anything else?

I get tons of use out of this extension. Thanks for putting it out into the world.

**Comment by MagnusHJensen** [comment]
This is already possible, find the Download Video command and press `CMD+OPT+,` to access extension settings where on the right side you can set the download path, the video should be downloaded to.

**Comment by Chamca** [comment]
> e

Thanks, this was exactly what I was looking for.
