### ISSUE TITLE
[YouTube Downloader] ..."Copy Video" file output does not match video title

### ISSUE THREAD

**Issue by Chamca** [raycast/extensions#13236]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

1.77.3

### macOS Version

14.5

### Description

Using the "Copy Video"/⌘K function, its expected the file name to the downloaded file matches the title indicated in the Youtube Downloader dialogue box. However, it is a unrecognized string of characters instead. 

![image](https://github.com/raycast/extensions/assets/28811107/3474406f-055d-49ee-8ff5-d14da218c55d)

### Steps To Reproduce

1. Open "Download Video" via raycast 
2. Paste youtube URL
3. ⌘K for more actions
4. Select "Copy Video"
5. Wait for video to download
6. Paste into folder
7. Observe file name does not match title

### Current Behaviour

Using "Copy Video", file name output does not match video title indicated in "Download Video" dialogue box.

### Expected Behaviour

Using "Copy Video", file name output matches video title indicated in "Download Video" dialogue box. Should be identical behavior with default "Download Video" function

**Comment by ridemountainpig** [comment]
@raycastbot assign me

**Comment by ridemountainpig** [comment]
@raycastbot close this issue
