### ISSUE TITLE
enable fallback command for `List` components

### ISSUE THREAD

**Issue by chyroc** [raycast/extensions#1324]
add `enableFallback` props to `List` components, so we(developers) and users can add many command to fallback command.

usage example:

```react
function List<T>(props: {}) {
    useEffect(() => {
        const f = async () => {
            setDataList(await fetchData());
        };
        f();
    }, [query]);

    return (
        <List
            throttle={true}
            enableFallback={true}
            onSearchTextChange={setQuery}
        >
            {dataList && dataList.map((v, idx) => {
                return (
                    <List.Item
                        ...
                    />
                );
            })}
        </List>
    );
}
```

when we input some word( that not match any command , so fallback to fallback command), it will send to `List.onSearchTextChange` to render `List` 

`List` add `enableFallback` is example, we maybe add this props to any components, or create new component to use `enableFallback` props.

**Comment by mathieudutour** [comment]
Shipped in 1.46.0!
