### ISSUE TITLE
[Obsidian] Create a note throw an error 

### ISSUE THREAD

**Issue by stashev** [raycast/extensions#13245]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Raycast Version

1.77.3

### macOS Version

14.5 (23F79)

#### Error:
```
Error: EPERM: operation not permitted, scandir '/Users/xxxx/Library/Mobile Documents/iCloud~md~obsidian/'

Qo:NoteListObsidian.tsx:18:10

---
15:   bookmarked: boolean

### Steps To Reproduce

try to create a note

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by KevinBatdorf** [comment]
Is this just a Raycast permissions issue? Ifyou go to your privacy settings and find Raycast, do you have these toggled on?

![CleanShot 2024-07-01 at 14 30 36@2x](https://github.com/raycast/extensions/assets/1478421/4fae5dd9-405a-44a9-af40-da5dfa2fb38b)

**Comment by gvdp** [comment]
> Is this just a Raycast permissions issue? Ifyou go to your privacy settings and find Raycast, do you have these toggled on?
> 
> ![CleanShot 2024-07-01 at 14 30 36@2x](https://private-user-images.githubusercontent.com/1478421/344583064-4fae5dd9-405a-44a9-af40-da5dfa2fb38b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNTgyNjMsIm5iZiI6MTcyMTE1Nzk2MywicGF0aCI6Ii8xNDc4NDIxLzM0NDU4MzA2NC00ZmFlNWRkOS00MDVhLTQ0YTktYWY0MC1kYTVkZmEyZmIzOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMTkyNjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWJmYTNlMzQ5ZWVlOTU2OTU2MjlkOWU0NmY5YzkwYzc0MjE4ZGEzNjEyMDM5OTQ4NDE3OGMyZDhkMjFjZWM3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.axPKFhGWyAV0Lk4FC8aZlMljm4f3XNXouQ9mUWvY9nE)

This was the issue for me, setting the correct permission fixed the error, thanks!
