### ISSUE TITLE
[Yoink] Setapp Support

### ISSUE THREAD

**Issue by JhonnyAxe** [raycast/extensions#13241]
### Extension

https://www.raycast.com/koinzhang/yoink

### Raycast Version

1.77.3

### macOS Version

14.5

### Description

Hello, could you make the support of the application when Yoink is installed via Setapp?

### Steps To Reproduce

1. Open the app

### Current Behaviour

![CleanShot 30 06 2024 at 07 03 40@2x](https://github.com/raycast/extensions/assets/84262172/677158fd-e96b-4b6e-abde-1fcdc78f575e)

**Comment by koinzhang** [comment]
Hi @JhonnyAxe . Thanks for the feedback, I've submitted a PR https://github.com/raycast/extensions/pull/13393 to fix this issue.
But I don't have SetApp, so I haven't tested it (I'm relying on my previous experience fixing this issue), can you test it if it's convenient?
Here's the updated code, which you can run locally using the Import Extension command.
[yoink.zip](https://github.com/user-attachments/files/16154729/yoink.zip)

**Comment by JhonnyAxe** [comment]
![CleanShot 10 07 2024 at 08 32 11@2x](https://github.com/raycast/extensions/assets/84262172/5de3ea68-c69d-4f1a-8bcf-f2e9e4e65987)

**Comment by JhonnyAxe** [comment]
> Hi @JhonnyAxe . Thanks for the feedback, I've submitted a PR #13393 to fix this issue. But I don't have SetApp, so I haven't tested it (I'm relying on my previous experience fixing this issue), can you test it if it's convenient? Here's the updated code, which you can run locally using the Import Extension command. [yoink.zip](https://github.com/user-attachments/files/16154729/yoink.zip)

![CleanShot 10 07 2024 at 08 32 11@2x](https://github.com/raycast/extensions/assets/84262172/86c764c8-f433-48af-932a-3e79e1d847e2)

**Comment by koinzhang** [comment]
https://developers.raycast.com/basics/create-your-first-extension#build-the-extension
> Open your terminal, navigate to your extension directory and run npm install && npm run dev. 

Hi @JhonnyAxe, you should build the extension first

**Comment by JhonnyAxe** [comment]
> https://developers.raycast.com/basics/create-your-first-extension#build-the-extension
> 
> > Open your terminal, navigate to your extension directory and run npm install && npm run dev.
> 
> Hi @JhonnyAxe, you should build the extension first

As you can see it just opens the selected files:

![CleanShot 10 07 2024 at 09 33 00](https://github.com/raycast/extensions/assets/84262172/ba423bab-8cca-4ee4-83d4-7c9db90bf94d)

**Comment by koinzhang** [comment]
Let me explain the reason for this phenomenon.
Currently, when adding a file, it uses the bundleId to locate the Yoink app, but it seems that the SetApp version of Yoink has a different bundleId than the AppStore version, so it can't find the Yoink app and opens it using the default app!

The bundleId I'm currently using is `at.EternalStorms.Yoink`, can you take a look at the SetApp version of Yoink to see what the bundleId is?

The solution I've come up with so far is to locate the Yoink app based on the app path, which should solve the problem!

**Comment by koinzhang** [comment]
`mdls /Applications/Setapp/Yoink.app | grep kMDItemCFBundleIdentifier`
Enter this command in the terminal to see Yoink's bundleId

**Comment by JhonnyAxe** [comment]
> `mdls /Applications/Setapp/Yoink.app | grep kMDItemCFBundleIdentifier` Enter this command in the terminal to see Yoink's bundleId

kMDItemCFBundleIdentifier          = "at.EternalStorms.Yoink-setapp"

**Comment by koinzhang** [comment]
[yoink.zip](https://github.com/user-attachments/files/16156614/yoink.zip)
Yoink did change the bundleId.
I've now updated the code to locate Yoink apps directly by app name, no longer based on bundleId, please go ahead and test it.

**Comment by JhonnyAxe** [comment]
> [yoink.zip](https://github.com/user-attachments/files/16156614/yoink.zip) Yoink did change the bundleId. I've now updated the code to locate Yoink apps directly by app name, no longer based on bundleId, please go ahead and test it.

Yes, it works! Will you push the update now?

![CleanShot 10 07 2024 at 10 01 16](https://github.com/raycast/extensions/assets/84262172/f1525956-3d1f-46d1-a4bf-c20665545581)

**Comment by koinzhang** [comment]
I've submitted the PR #13393, but it takes about 5-10 business days for the PR to merge in, until then you can use the local extension
<img width="597" alt="image" src="https://github.com/raycast/extensions/assets/36128970/ea4ef8cb-f755-4c5c-afcc-1b3ac9e241b7">

**Comment by koinzhang** [comment]
Hi @JhonnyAxe The extension has been update, so I will close this issue. If you have any other issues, feel free to give me feedback.

@raycastbot close this issue
