### ISSUE TITLE
No such file or directory when running `ray develop and build`

### ISSUE THREAD

**Issue by lucasaugustsof** [raycast/extensions#13251]
### Description

I’m having a problem trying to run the ray development command for my Raycast extension on an ARM64 architecture. The error message indicates that the required binary file cannot be found. I’m using version 1.77.3 of the raycast/api. Follow the print below:

<img width="1018" alt="Screenshot 2024-06-30 at 19 08 45" src="https://github.com/raycast/extensions/assets/71651661/b3f1e613-7d1d-4591-ab31-eb59cc6cf287">

Could someone help me, please? I've already tried changing the directory directly in the script, but the error still persists.

### Steps To Reproduce

1. Create extension
2. npm install
3. npm run dev

### Current Behaviour

/Users/develcode106/Documents/CODES/develcode-time-tracker/node_modules/.bin/ray: line 71: /Users/develcode106/Documents/CODES/develcode-time-tracker/node_modules/@raycast/api/bin/arm64/ray: No such file or directory

### Expected Behaviour

Execute command correctly.

**Comment by rafaud** [comment]
I had the same problem, for some reason the script `node_modules/@raycast/api/bin/ray`, in the extension directory, couldn't properly download needed files. 

Culprit was line 36, for some reason URL `https://raycast.com/get-cli/` could not be resolved, but adding `www` at the beginning fixed the problem for me. (URL should look like this: `https://www.raycast.com/get-cli/`). 

Device: MacBook Pro, 14-inch, 2023
Chip: Apple M2 Pro
Memory: 32 GB
System: Sonoma 14.5

 Node version: v22.4.1
 NPM version: 8.19.4
Raycast version: 1.78.1

**Comment by li-qiang** [comment]
+1, I had this problem.

**Comment by mathieudutour** [comment]
That should be fixed now
