### ISSUE TITLE
[Pins] Setting for folders to open as new tab

### ISSUE THREAD

**Issue by dudido** [raycast/extensions#13268]
### Extension

https://www.raycast.com/HelloImSteven/pins

### Description

I would like to be able to set an option for folders to open them as new tabs rather than separate windows. I guess they should be added to the most recent finder window, if several are open.

### Who will benefit from this feature?

Anyone frequently opening sets of folders.

**Comment by SKaplanOfficial** [comment]
It respects Finder's "Open folders in new tabs instead of new windows" setting. If you have that enabled, it will do exactly as you've described. I'm not sure a separate setting for Pins is needed, but let me know if you think otherwise.

**Comment by dudido** [comment]
On my system, Finder's "Open folders in new tabs instead of new windows" setting is *not* respected. It is turned on, but each folder is opened as a separate windows (not tabs of a single window) and not even when a finder window with tabs is already open…

Notwithstanding this potential bug, I think it would be useful to set a default and be able to tune the setting per folder.

**Comment by SKaplanOfficial** [comment]
The bug would be with Raycast's [open()](https://developers.raycast.com/api-reference/utilities#open) function, as Pins just calls that with the path to the folder. I'll submit a bug report on Slack.

I can look into adding a per-folder setting that uses AppleScript or something to ensure opening in the same-window.
