### ISSUE TITLE
[Slack Status] Allow custom emojis

### ISSUE THREAD

**Issue by konsalex** [raycast/extensions#13262]
### Extension

https://www.raycast.com/petr/slack-status

### Description

Currently the emoji picker for the status allows only native emojis.

If there are custom emojis on the Slack workspace, it would be nice to allow usage of them by just typing them, even if they are not displayed.

For example for code pairing we have an emoji of the Zed icon, so in theory the emoji field could accept a value of `:zed:`

### Who will benefit from this feature?

People who want to use custom emoji statuses

**Comment by ramsaysewell** [comment]
Hey @konsalex, would you like to work on this yourself?

Slack gives us a method to list the available emojis in the workspace so this is definitely something possible. I'd be happy to help you out if you're up for the challenge.
