### ISSUE TITLE
[GitHub] Failed creating branch ... is not a valid ref name

### ISSUE THREAD

**Issue by timowenz** [raycast/extensions#13275]
### Extension

https://www.raycast.com/raycast/github

### Raycast Version

1.77.3

### macOS Version

14.5

### Description

I can't open a new branch because it says: `Failed to create branch. ... is not a valid ref name.` Don't know why this is coming up because the name of my branch should be correct.

![CleanShot 2024-07-01 at 16 11 28](https://github.com/raycast/extensions/assets/86304640/ea650a0b-d275-4423-86a8-ee11acfb8fc6)

### Steps To Reproduce

Create a branch with GitHub extension in Raycast.

### Current Behaviour

Error message and not creating a branch.

### Expected Behaviour

It should create a branch to my repo.

**Comment by jfkisafk** [comment]
@raycastbot assign me

**Comment by timowenz** [comment]
Alright thank you!
