### ISSUE TITLE
[SIPS] WEBP conversion makes files bigger that PNG or JPEG

### ISSUE THREAD

**Issue by humandman** [raycast/extensions#13273]
### Extension

https://www.raycast.com/HelloImSteven/sips

### Raycast Version

1.69.0

### Description

For about some time webp image conversion makes file way bigger from the original PNG or JPEG.
In the past months I've used the extension and worked like a charm in converting images, and usually the webp format became 1/10 of the original size, now from a 850kb jpeg image give a 1MB Webp image.

### Steps To Reproduce

1. Take a common jspeg file
2. Converto to WEBP format
3. Compare sizes, it's always bigger from the original

### Expected Behaviour

The Webp format weight way less than the original file.

**Comment by JUSTIVE** [comment]
The former PR #12957 might be related to this. I thought lossless as default would prevent users from unexpected image quality degradation, but I didn't consider file size. Adding a lossless option as Image-Modification's option would be great for all.

**Comment by humandman** [comment]
Hi @JUSTIVE, yeah option for lossless or quality option would be ideal!
