### ISSUE TITLE
[Font Awesome] ... Add default command option

### ISSUE THREAD

**Issue by stefandevo** [raycast/extensions#13287]
### Extension

https://www.raycast.com/dutzi/font-awesome

### Description

Would be great if you could add a default action to this extension.
Now these are hard coded Copy Icon Name of Copy Icon Classes.
But I would like to have for example the Copy as SVG to be the default command.

Check also the Iconify extension which has this option:

![CleanShot 2024-07-02 at 14 01 01@2x](https://github.com/raycast/extensions/assets/1656051/b6e38fe9-5952-4d24-981a-02dcfb0abbbf)

**Comment by GLaDO8** [comment]
This makes sense, planning to add this in an upcoming update.

**Comment by stefandevo** [comment]
@GLaDO8 any news on this?

**Comment by ridemountainpig** [comment]
@raycastbot assign me
