### ISSUE TITLE
[ScreenOCR] Korean OCR Not working

### ISSUE THREAD

**Issue by noidwasavailable** [raycast/extensions#13283]
### Extension

https://www.raycast.com/huzef44/screenocr

### Raycast Version

1.77.3

### macOS Version

14.2 (23C64)

### Description

Korean OCR is not working

### Steps To Reproduce

1. Select Korean in `Select Recognition Languages`
![image](https://github.com/raycast/extensions/assets/26755327/1f330a5f-39ba-4a56-9b59-b5e64aee5533)
2. Launch `Recognize Text` command
3. Get Error!

### Current Behaviour

Whenever I screenshot some Korean text, it says "No text detected"

### Expected Behaviour

It should correctly recognize Korean text

**Comment by noidwasavailable** [comment]
I'll try to fork it and see what the issue is when I have time~

**Comment by neo773** [comment]
What macOS version are you using? VisionKit is unfortunately bundled with macOS and there’s no way to update it individually.

**Comment by noidwasavailable** [comment]
@neo773 `Sonoma 14.2 (23C64)`
