### ISSUE TITLE
[Stock Tracker] No stocks loading

### ISSUE THREAD

**Issue by whitespacecode** [raycast/extensions#13286]
### Extension

https://www.raycast.com/hmarr/stock-tracker

### Raycast Version

1.77.3

### macOS Version

14.3.1

### Description

Not sure how to get this to work. You can't enter an api key either.
![image](https://github.com/raycast/extensions/assets/37139936/4e5491b9-8b54-438f-bf7d-ee1cf562c81f)

### Steps To Reproduce

I just installed the extension. 
Try to find any stock with no results

**Comment by haydencbarnes** [comment]
Already listed as an issue here: https://github.com/raycast/extensions/issues/12868

**Comment by haydencbarnes** [comment]
@raycastbot close this issue
