### ISSUE TITLE
[Text Replacements] Add command to export Raycast Snippets into Apple Text Replacements

### ISSUE THREAD

**Issue by kylemh** [raycast/extensions#13292]
### Extension

https://www.raycast.com/raycast/text-replacements

### Description

As @mxstbr pointed out in his YouTube video, Raycast is not on iOS and so it's necessary to use "Text Replacements" (TR) there. Unlike Max, I never had many TR. I only have loads of Raycast Snippets; however, I don't have a quick way to add them to TR to help my iOS experience!

### Who will benefit from this feature?

Anybody who wants to leverage their Raycast Snippet library on non MacOS devices.

**Comment by thomaslombart** [comment]
Thanks for the issue, but that's unfortunately not possible for the reasons explained [over here](https://github.com/raycast/extensions/pull/12031#issuecomment-2082182210) 😕
