### ISSUE TITLE
[Mozilla Firefox] Error: Worker terminated due to reaching memory limit: JS heap out of memory.

### ISSUE THREAD

**Issue by proactivematter** [raycast/extensions#13294]
### Extension

https://www.raycast.com/crisboarna/mozilla-firefox

### Raycast Version

1.77.3

### macOS Version

14.4.1 (23E224)

### Description

I have a lot of bookmarks. Upon trying to search bookmarks I get this error:

Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20

### Steps To Reproduce

Possibly related to me having a ton of bookmarks ( ~20-30K ). Other features work fine.

**Comment by egovelox** [comment]
Hi @proactivematter 

I'm just curious if the [Mozeidon extension](https://www.raycast.com/egovelox/mozeidon) I developed, would break the same way with your ~20-30K bookmarks.

I'm currently using it with ~6-7K bookmarks, and did not experienced any JS heap out of memory.

This extension relies on a firefox add-on and Go CLI, that output firefox tabs and bookmarks into Raycast.

If you don't mind going through the ( relatively complex ) [installation of the extension](https://github.com/egovelox/mozeidon?tab=readme-ov-file), 
I would be glad to have some feedback !



Cheers.
