### ISSUE TITLE
[Todoist] Raycast Extension error

### ISSUE THREAD

**Issue by danielngkt** [raycast/extensions#13301]
### Extension

https://www.raycast.com/doist/todoist

### Raycast Version

1.77.3

### macOS Version

Sonoma 14.5

#### Error:
```
Error: unable to get local issuer certificate

ap.from:AxiosError.js:89:13

---
86:     return prop !== 'isAxiosError'

### Steps To Reproduce

i was just trying to use the todoist extension and it has to setup, I agreed to the conditions, and it opened back Raycast and then the error:
Error: unable to get local issuer certificate

ap.from:AxiosError.js:89:13

---
86:     return prop !== 'isAxiosError';
87:   });
88: 
89:   AxiosError.call(axiosError, error.message, code, config, request, response);
90: 
91:   axiosError.cause = error;
92: 
---

ka.<anonymous>:create-task.js:59:8924
ka.emit:node:events:514:28
ka.emit:node:domain:488:12

### Current Behaviour

can't use the Todoist extension

### Expected Behaviour

Working todoist extension

**Comment by thomaslombart** [comment]
Are you using some kind of VPN/firewall/proxy?

**Comment by danielngkt** [comment]
yes, i am on my corporate laptop with zscaler.

**Comment by danielngkt** [comment]
i can’t fully disable ZScaler. I can turn of some functions like “Private Access” and “Digital Experience”. The “Internet Security” is admin controlled. Yes, I turn off both that I can turn off, and the issue still exists.

**Comment by thomaslombart** [comment]
You can add some settings in Raycast for SSL issues. Maybe you can ask one of your admins if they can do something about it?

**Comment by danielngkt** [comment]
Thanks,. short of asking the admin to Do something about it. You suggested some SSL settings? What would they be? thanks Regards,Daniel NgOn 11 Jul 2024, at 3:02 PM, Thomas Lombart ***@***.***> wrote:﻿
You can add some settings in Raycast for SSL issues. Maybe you can ask one of your admins if they can do something about it?

**Comment by thomaslombart** [comment]
Thinking more about it, adding SSL settings in Raycast may not be necessary now. Could you first check with your admin if the following domain is authorized on their end: `https://todoist.oauth-proxy.raycast.com`. We have had errors in the past where domains/URLs with the word `proxy` were not allowed for some users.
