### ISSUE TITLE
[Wi-Fi] Scan wifi not working

### ISSUE THREAD

**Issue by camiloaromero23** [raycast/extensions#13307]
### Extension

https://www.raycast.com/koinzhang/wi-fi

### Raycast Version

1.78.0

### macOS Version

14.5

### Description

Scan Wifi command is not working

### Steps To Reproduce

1. Open scan Wifi command

### Current Behaviour

No wifi network is shown
<img width="886" alt="image" src="https://github.com/raycast/extensions/assets/64717266/9b72ee29-9f17-433a-8f53-597e9bdd8585">

**Comment by iwex** [comment]
@koinzhang close?

**Comment by koinzhang** [comment]
Since Apple no longer provides the Wifi tool, the Scan Wifi command is no longer available and this issue can be closed
@raycastbot close this issue
