### ISSUE TITLE
Detail components render markdown error

### ISSUE THREAD

**Issue by chyroc** [raycast/extensions#1331]
command: `GitHub Gist`

star https://gist.github.com/todgru/4503682 and view it:

![image](https://user-images.githubusercontent.com/15604894/162440287-8cf88e5d-ad09-409d-b8dd-a86fe3bcbe39.png)

**Comment by koinzhang** [comment]
Hi @chyroc👋 
Thanks for the feedback. Here is the reason for not previewing correctly I neglected the formatting type of the MD(Currently all gist are displayed by default using the code box ```).
I will improve it.
