### ISSUE TITLE
[Messages]...Extension will not load in contacts from JSON

### ISSUE THREAD

**Issue by njbirk** [raycast/extensions#13314]
### Extension

https://raycast.com/thomaslombart/messages

### Raycast Version

1.78.0

### macOS Version

14.5

#### Error:
```
SwiftError: Failed to deserialize result from JSON: Unexpected token 'F', "Failed to "... is not valid JSON
    at ChildProcess.<anonymous> (/Users/nolanbirkeland/.config/raycast/extensions/f872e5ef-af26-4086-8b11-261e5c6f6c93/send-message.js:32:4540)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:488:12)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```
<img width="784" alt="image" src="https://github.com/raycast/extensions/assets/92126122/2b5f5f0a-c891-47a3-91ee-6e9e84bd4b54">

<img width="766" alt="image" src="https://github.com/raycast/extensions/assets/92126122/e9a52c88-fb42-494e-9b91-0bb89f008320">

### Steps To Reproduce

1. Open Raycast and choose "Send Message command". This will display the following: 
<img width="784" alt="image" src="https://github.com/raycast/extensions/assets/92126122/2b5f5f0a-c891-47a3-91ee-6e9e84bd4b54">
2. Opening the error message displays the full text: 
<img width="766" alt="image" src="https://github.com/raycast/extensions/assets/92126122/e9a52c88-fb42-494e-9b91-0bb89f008320">

### Current Behaviour

When send message command is entered, the provided error message is shown and no contacts can be entered

### Expected Behaviour

JSON data should be loaded correctly

**Comment by ramsaysewell** [comment]
Hey @njbirk,

Thanks for raising this issue. Can I check that Raycast has permission to access your contacts? This could help with determining what's going on here.

You can check the settings by going to:

System Settings -> Privacy & Security -> Contacts

and checking "Raycast".
