### ISSUE TITLE
[Linear] Showing sub-issues in a parent issue

### ISSUE THREAD

**Issue by inedyalkov** [raycast/extensions#13326]
### Extension

https://www.raycast.com/linear/linear

### Description

As of now, when there are sub-issues added to a parent issue, they only show up as issue IDs.

![Screenshot 2024-07-04 at 18 22 44](https://github.com/raycast/extensions/assets/110191050/da9167b8-14f9-4725-90c1-c5a281bb6b7f)

Seeing the sub-issue would be even better.

**Comment by jfkisafk** [comment]
Hey @inedyalkov, Raycast already has a feature to show sub-issues `Cmd + Shift + M` if you add sub-issues to the parent issue like [this](https://linear.app/docs/parent-and-sub-issues). Are you adding sub issues to the description?

**Comment by inedyalkov** [comment]
That was it, yes. Thank you @jfkisafk !
