### ISSUE TITLE
[Stock Tracker] Not Working

### ISSUE THREAD

**Issue by menjilx** [raycast/extensions#13325]
### Extension

https://www.raycast.com/hmarr/stock-tracker

### Raycast Version

1.78

### Description

<img width="432" alt="image" src="https://github.com/raycast/extensions/assets/14908836/2e3f3b07-357e-4aae-ac0c-40d0a27272c1">

### Steps To Reproduce

1. open stocks
2. enter "NVDA"
3. it will not work

**Comment by haydencbarnes** [comment]
Already mentioned here: https://github.com/raycast/extensions/issues/12868

**Comment by haydencbarnes** [comment]
@raycastbot close this issue
