### ISSUE TITLE
[Notion] Relation field only populates with a few options

### ISSUE THREAD

**Issue by jasonesiegel** [raycast/extensions#13324]
### Extension

https://www.raycast.com/notion/notion

### Raycast Version

1.77.3

### macOS Version

14.5

### Description

When attempting to create a new page, my Relation fields only populate with a few options, and I'm unable to search for the related values that I need to use. Is there an extension or API limitation?

### Steps To Reproduce

1. Open Create Database Page
2. Browser values of a relation field

**Comment by thomaslombart** [comment]
That's probably an extension limitation. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request.

**Comment by jasonesiegel** [comment]
I’m not a developer unfortunately!

**Comment by bkeys818** [comment]
I've wanted to fix this for a while, but time...
