### ISSUE TITLE
[Vivaldi] Add "Create New Window" command

### ISSUE THREAD

**Issue by purplespider** [raycast/extensions#13335]
### Extension

https://www.raycast.com/crisboarna/vivaldi

### Description

It would be great if a "Create New Window" command could be added. Like the one in the Google Chrome Extension.

### Who will benefit from this feature?

Those who work with multiple browser windows or multiple spaces. As you'd be able to switch to a new space, then open a new browser window in that space. If you use the "New Tab" command, it moves you back to a space that has an existing browser window in it.

**Comment by romanskorobagatko** [comment]
I support this, would be really nice to have.

**Comment by iwex** [comment]
@raycastbot close this issue
