### ISSUE TITLE
[Brew] Add ability to search from the main launcher

### ISSUE THREAD

**Issue by vpukhanov** [raycast/extensions#13337]
### Extension

https://www.raycast.com/nhojb/brew

### Description

Hi! I'm interested in adding an argument to the list commands of the extension (Search, Outdated, Installed).

I'd like to work on this myself, but I wanted to check with the contributors first to ensure there are no objections!

### Who will benefit from this feature?

Anyone who uses this extension a lot

### Anything else?

<img width="862" alt="Снимок экрана 2024-07-05 в 18 39 13" src="https://github.com/raycast/extensions/assets/1694616/caa753a5-45ea-4f92-806c-276221f48681">

**Comment by vpukhanov** [comment]
@raycastbot assign me

**Comment by nhojb** [comment]
Hey @vpukhanov, thanks for the suggestion.

Unfortunately I'm not very enthusiastic about adding arguments to the brew commands. It's not really consistent with Raycast's built-in search commands - none of which take arguments from root search. In my opinion adding arguments adds visual clutter to the UI. So it's a strong no from me 🫤

The usual approach to make it quicker to search with a command would be one or all of the following options:

- Add an alias or hotkey for the command(s). The hotkey allows users to launch directly into the command, by-passing root search.
- Enable the command as a "Fallback Command". Then you can enter the search term in root search and select the desired fallback command to directly search for the search term (see screenshots).


<img width="862" alt="Screenshot 2024-07-06 at 12 20 04" src="https://github.com/raycast/extensions/assets/312540/d5687b3d-2bdf-473d-b71f-00e3da2fc2cb">

<img width="862" alt="Screenshot 2024-07-06 at 12 19 36" src="https://github.com/raycast/extensions/assets/312540/b4ff467c-edde-40cc-a15c-2606af660baa">

**Comment by vpukhanov** [comment]
Cool, thanks for sharing your viewpoint, it makes a lot of sense! I'm glad I checked in with you first, it's interesting to hear the intentions behind this design decision. I'll close this issue then.
