### ISSUE TITLE
[ScreenOCR] macOS Sequoia Screen Recording Permission Issue

### ISSUE THREAD

**Issue by Asstiff** [raycast/extensions#13356]
### Extension

https://www.raycast.com/huzef44/screenocr

### Raycast Version

1.78.1

### macOS Version

15.0

### Description

On macOS 15, ScreenOCR cannot be used. Every time it try to get a screenshot, the permission alert appears.

### Steps To Reproduce

1. Upgrade to macOS Sequoia.
2. Use the ScreenOCR extension.
3. The permission prompt appears.

https://github.com/raycast/extensions/assets/46558763/606bb41f-30b4-432d-8d16-8dca87b5cef1

**Comment by anwarulislam** [comment]
@Asstiff can you please record in English?

**Comment by Asstiff** [comment]
<img width="262" alt="Screenshot 2024-08-01 at 14 08 36" src="https://github.com/user-attachments/assets/68204c4e-8b7c-45a7-8724-542ffea54aaf">
It looks like this.

[Deprecations](https://developer.apple.com/documentation/macos-release-notes/macos-15-release-notes#Deprecations)
Applications utilizing deprecated APIs for content capture such as CGDisplayStream & CGWindowListCreateImage can trigger system alerts indicating they might be able to collect detailed information about the user. Developers need to migrate to ScreenCaptureKit and SCContentSharingPicker. (120910350)

**Comment by erics118** [comment]
This is a new macos sequoia feature. See https://9to5mac.com/2024/08/06/macos-sequoia-screen-recording-privacy-prompt/

**Comment by neo773** [comment]
> This is a new macos sequoia feature. See https://9to5mac.com/2024/08/06/macos-sequoia-screen-recording-privacy-prompt/

This! there's unfortunately nothing I can do about that, it's just how Apple has decided on.
About the deprecation notice, I wasn't aware of that Thanks!
Although I don't have any plans at the moment to migrate.
