### ISSUE TITLE
[GitHub] Repository Search Sort By Most Stars⭐️

### ISSUE THREAD

**Issue by Rizkiacry** [raycast/extensions#13363]
### Extension

https://www.raycast.com/raycast/github

### Description

Toggle to search by most stars.

### Who will benefit from this feature?

Everyone who is looking for the most reliable repo.

### Anything else?

![CleanShot 2024-07-08 at 1  18 53@2x](https://github.com/raycast/extensions/assets/154677201/84b33e2e-39e0-452b-938e-cfb51409a50f)

**Comment by jfkisafk** [comment]
@raycastbot assign me

**Comment by jfkisafk** [comment]
This is being implemented and once merged you should have these options to sort repositories by:

https://github.com/raycast/extensions/blob/5f9d04c1f3bd512841193be45e9ab3f9dfe03c16/extensions/github/src/helpers/repository.ts#L136-L139
