### ISSUE TITLE
This appears to be reporting vastly different download speeds than the web-based products

### ISSUE THREAD

**Issue by MarketHubb** [raycast/extensions#13364]
### Extension

https://www.raycast.com/tonka3000/speedtest

### Raycast Version

1.78.1

### macOS Version

14.1

### Description

I'm seeing download speeds that are 1/3 to 1/2 of what I'm getting on the speedtest.net website (and verified by other third party speed test software)

### Steps To Reproduce

1. Run speed test
2. Compare results to web interface

**Comment by aliaksandrZh** [comment]
Just test it out. For me it works as expected. Could you provide any additional info?
Do you connected to VPN? Is the location of the server in the extension differ from the web site?
