### ISSUE TITLE
[pm2] extension add ability to change the pm2 home which at '~/.pm2/' by default[Extension Name] ...

### ISSUE THREAD

**Issue by yangws** [raycast/extensions#13384]
### Extension

https://www.raycast.com/litomore/pm2

### Description

In shell, cound set environment vairable 'PM2_HOME' to change the pm2 home from default '~/.pm2/' to another directory.
I hope the pm2 extension could support this feature, thus it makes raycast pm2 extension will works on my environment.

PM2_HOME specific Reference here: https://pm2.keymetrics.io/docs/usage/specifics/

**Comment by LitoMore** [comment]
Resolved in #13473

**Comment by LitoMore** [comment]
@raycastbot close this issue
