### ISSUE TITLE
[Yoink] ...Getting an error message that Yoink is not installed.

### ISSUE THREAD

**Issue by diwaniec** [raycast/extensions#13392]
### Extension

https://www.raycast.com/koinzhang/yoink

### Raycast Version

1.78.1

### macOS Version

14.5

### Description

I get the error message "Yoink is not installed." 

### Steps To Reproduce

Yoink is installed through Setapp (setapp.com).

**Comment by koinzhang** [comment]
Hi @diwaniec. Thanks for the feedback, I've submitted a PR #13393 to fix this issue.
But I don't have SetApp, so I haven't tested it (I'm relying on my previous experience fixing this issue), can you test it for me if it's convenient?
Here's the updated code, which you can run locally using the Import Extension command.
[yoink.zip](https://github.com/user-attachments/files/16146805/yoink.zip)

**Comment by diwaniec** [comment]
Thank you for your kind help!
Unfortunately, I'm still having the problem.
An idea: Setapp installs apps in a different location. Rather than being in "~/Applications/" they are in "~/Applications/Setapp/". Just a guess. Could that be the issue?

**Comment by koinzhang** [comment]
Yes. SetApp installs a different path to the app, can you tell me the installation path for Yoink on your computer?
I used /Applicatios/SetApp/Yoink.app but it doesn't seem right according to your debugging!

**Comment by koinzhang** [comment]
[yoink.zip](https://github.com/user-attachments/files/16154576/yoink.zip)
Here is the latest code, can you have a try?
