### ISSUE TITLE
Harvest Usability Improvements

### ISSUE THREAD

**Issue by rjhewitt3** [raycast/extensions#1339]
[Harvest](https://github.com/raycast/extensions/tree/main/extensions/harvest)
Author: @eluce2 

I’ve been using the Harvest extension and am loving it so far, but I have a couple of suggestions to make it even better:

1. Show the active timer in Raycast when initially opened like Calendar Events (see attached image)
2. Retain the last used project/task when creating new time entries

![image](https://user-images.githubusercontent.com/6742828/162479606-4cbbb029-10df-48db-af27-dbb23fd20c45.png)

**Comment by thomaspaulmann** [comment]
I'm gonna close this. @eluce2 improved what's possible.
