### ISSUE TITLE
[YouTube Downloader] Can't download video

### ISSUE THREAD

**Issue by mkjawadi** [raycast/extensions#13394]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

1.78.1

### Description

I can't use the extension to download YouTube videos. I've tried uninstalling the extension. I have tried installing/reinstalling ffmpeg (several versions including the recent one) but no luck. The downloading doesn't start at all!

<img width="738" alt="Screenshot 2024-07-09 at 1 22 59 PM" src="https://github.com/raycast/extensions/assets/32951993/9c5b62bd-6546-4201-ad4e-968c17738970">

### Steps To Reproduce

1. Open the extension
2. Paste the video URL
3. Hit "Download Video"

**Comment by codepil0t** [comment]
Yes I have an absolutely identical problem.
I have tried all video resolutions, all formats, but in the end I always get an error. 
In addition, I checked that Raycast has permissions to the folder where the video will be downloaded and that I have ffmpeg installed.

**Comment by ridemountainpig** [comment]
The error appears to be caused by the `ytdl-core` package. There is also an [issue](https://github.com/fent/node-ytdl-core/issues/1295) with 403 download failures.

The error message for the YouTube Downloader extension is:
```
10:20:51.716 MinigetError: Status code: 403
    at ClientRequest.<anonymous> (/Users/linyancheng/.config/raycast/extensions/youtube-downloader/index.js:1667:23)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:514:28)
    at ClientRequest.emit (node:domain:488:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:535:22)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:376:12) {
  statusCode: 403
}
```

**Comment by claudiuionus** [comment]
Hello guys,

also having the same issue.

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/175202690/c8a23151-5391-44d7-8103-6e7b0ea5e749">

Thanks!

**Comment by voloshinvlad** [comment]
I have the same problem. When I try to download a video from YouTube, the extension says "Download failed. Please try again later". I tried the old version of ffmpeg (6.1 stable), used many variations of path to ffmpeg and ffprobe, reinstalled/installed Raycast, extension, ffmpeg, but it didn't work at all. Please push fix.
![2024-07-10 15 14 42](https://github.com/raycast/extensions/assets/67964913/582e6c33-e1c8-440b-b9be-0ad48954660e)

**Comment by ultrahumanite** [comment]
Also experiencing the same issue.

**Comment by ridemountainpig** [comment]
@raycastbot close this issue

**Comment by polymerjones** [comment]
same issue, nothing works in raycast apparently
