### ISSUE TITLE
[Authy - Twilio App] ...

### ISSUE THREAD

**Issue by 0xgeorgemathew** [raycast/extensions#13407]
### Extension

https://www.raycast.com/guga4ka/authy

### Raycast Version

1.78.1

### macOS Version

14.5 

### Description

Unable to login. 

Unable to authenticate the extension using Authy ID and Backup Password.

Error: The device does not meet the minimum integrity requirements
Error: Login Request not Found

![Screenshot 2024-07-10 at 10 34 12 AM](https://github.com/raycast/extensions/assets/97821867/41668f5d-3d4d-46db-9d11-94f12adb7a42)
![Screenshot 2024-07-10 at 10 35 08 AM](https://github.com/raycast/extensions/assets/97821867/965d6696-d106-496a-8644-6bf8a56c7fa5)

### Steps To Reproduce

1. Install the extension. 
2. Start the extension. 
3. Provide Credentials Authy ID and Authy Backup Password.
4. Start the Extension
5. Press Enter
    

### Current Behaviour

![Screenshot 2024-07-10 at 10 33 30 AM](https://github.com/raycast/extensions/assets/97821867/2aba7335-8fcd-4449-a074-eed102c872ef)
![Screenshot 2024-07-10 at 10 34 12 AM](https://github.com/raycast/extensions/assets/97821867/1f89dacc-86b2-4a21-b742-d2da3c696bf3)
![Screenshot 2024-07-10 at 10 35 08 AM](https://github.com/raycast/extensions/assets/97821867/5c8c51a6-9578-47cc-a587-49283713f482)

Error: The device does not meet the minimum integrity requirements
Error: Login Request not Found

**Comment by guga4ka** [comment]
@0xgeorgemathew it's not possible to onboard new users to extension right now. I've made a note at readme and now a'm looking to way to disable new installation

**Comment by 0xgeorgemathew** [comment]
> @0xgeorgemathew it's not possible to onboard new users to extension right now. I've made a note at readme and now a'm looking to way to disable new installation

Thank you for the reply. 

Does old installations continue to work?

When new keys are added via android/iOS app do they sync with the raycast extension?

If you can think of any workarounds do suggest. 

I recently wiped my data on my device (have it backed up) and lost access to the extension

Thank you for building an incredible product. 

Good luck.

**Comment by guga4ka** [comment]
>Does old installations continue to work?

Yes 

>When new keys are added via android/iOS app do they sync with the raycast extension?

Should work as previously, Authy only changed API related to registration of new device

>If you can think of any workarounds do suggest.

Hard to say, i've also lose an access to extension and now thing about moving to something else. Regarding Raycast integration here is a nice extension https://www.raycast.com/lachero/one-time-password (you can export authy data to google auth format and import there) i might contribute to it to support 2FAS export format, or just write a private 2FAS extension to own use. The main problem is syncing of data, i didn't find a better way than manual export and manual import of data.

**Comment by LitoMore** [comment]
Be careful about storing your password data on Raycast, especially the One Time Password extension. When you remove the extension, your local data will be removed as well. You should store the OTP not only on Raycast.

**Comment by mathieutu** [comment]
Hello @guga4ka!
Thanks for your work on this extension. I think it was the one I used the most!
Unfortunately, I had to reset my mac, and now I've lost access to it.

I didn't find any equivalent app that can sync across devices, and be usable with Raycast like Authy was.
Did you find any proper alternative? Do you think the extension could be updated to handle the new Authy way to register devices? (I didn't find the discussion about it).

Thanks!

**Comment by siddharthalodha** [comment]
Is there a way to transfer this from my old device ?

**Comment by pernielsentikaer** [comment]
This extension is unfortunately deprecated

**Comment by siddharthalodha** [comment]
I got the extension restored via my backup but it isn't able to restore the data. Is there a way to restore the data for this app ? I still have access to the old device where it works fine.

**Comment by janstieler** [comment]
Hi,
Sorry for asking, but I don't understand why it's not possible to change the app to the new Authy API? Could someone clear me up? I miss this app really 😁 in authy!

**Comment by mathieutu** [comment]
For information I switched to Ente Auth on my side, and I'm pretty happy with it!

https://help.ente.io/auth/
