### ISSUE TITLE
[Jira] make possible to specify jira API version for legacy installations

### ISSUE THREAD

**Issue by theonewiththegun** [raycast/extensions#13409]
### Extension

https://www.raycast.com/raycast/jira

### Description

[Here](https://github.com/raycast/extensions/blob/7c37f9f8bacaa081449d992ba2a3afa794712b59/extensions/jira/src/api/request.ts#L33C58-L33C68) the API version is hardcoded, meanwhile in the wild values '2' and 'latest' and maybe some other may be found. This basically happened to me and prevented me from using the extension. 

### Who will benefit from this feature?

People with installations of JIRA that do not yet support latest API versions.

**Comment by theonewiththegun** [comment]
If it's OK i may be up to building a PR for this issue

**Comment by thomaslombart** [comment]
Sure, go ahead! 🙌
