### ISSUE TITLE
[Lorem Ipsum] Add more languages

### ISSUE THREAD

**Issue by iftachhh** [raycast/extensions#13411]
### Extension

https://www.raycast.com/AntonNiklasson/lorem-ipsum

### Description

Pretty self explanatory, suggest lorem ipsum text in other languages than English.

### Who will benefit from this feature?

Anyone speaking language other that English.

**Comment by AntonNiklasson** [comment]
Isn’t the content generated just not tied to any language? What would it look like in another language? Or are you referring to the AI command?

**Comment by enkia** [comment]
My guess, @iftachhh means utilizing additional ipsum packages such as chinese-lorem and aripsum which seems outside the scope since this extension generates its namesake, lorem-ipsum?

**Comment by iftachhh** [comment]
Hey, I mean suggesting Lorem Ipsum like texts in other alphabets that English, for example in Hebrew, Arabic, Chinese letters and etc. The text itself still won't have any meaning it will be used to illustrate how long text will look in different languages.

**Comment by AntonNiklasson** [comment]
Okay got it! It sounds like a great addition. I don’t have bandwidth right now, but could either review a PR or potentially get to it in a few weeks.
