### ISSUE TITLE
[Ollama AI] ollamaCertificateValidation error

### ISSUE THREAD

**Issue by nxtmlangin** [raycast/extensions#13412]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Raycast Version

1.78.1

### macOS Version

14.5

#### Error:
```
SyntaxError: Unexpected end of JSON input

S4:ollama-custom-command.tsx:9:27

---
 6: if (!p.ollamaCertificateValidation) process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = "0"

### Steps To Reproduce

When trying to use the custom command, I write an argument and execute, nothing happens ->  Value is missing in argument Model.
If I manually fill the Model field, I get the error from the description.
This issue has been happening to me for about a month, I tried to reinstall Raycast and the Ollama plugin, still the same.
The custom command seems to be the only  ollama command with the issue.

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by MassimilianoPasquini97** [comment]
@raycastbot assign me

**Comment by MassimilianoPasquini97** [comment]
@nxtmlangin "Custom Command" need to be used only with "Create Custom Command" where you can create you own custom commands

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue

**Comment by nxtmlangin** [comment]
I am pretty sure I was able to select a text and use this, writing a prompt on the fly :
<img width="751" alt="image" src="https://github.com/raycast/extensions/assets/137415506/9054de8f-154b-48d8-837e-f12193748a9a">
This was great, I will miss the feature if that's not possible anymore.

**Comment by MassimilianoPasquini97** [comment]
"Custom Command" wasn't design to be used like that. For your tipe of use I suggest to use "Chat with Ollama". 

> I am pretty sure I was able to select a text and use this, writing a prompt on the fly : <img alt="image" width="751" src="https://private-user-images.githubusercontent.com/137415506/347476900-9054de8f-154b-48d8-837e-f12193748a9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2Mjg4NjQsIm5iZiI6MTcyMDYyODU2NCwicGF0aCI6Ii8xMzc0MTU1MDYvMzQ3NDc2OTAwLTkwNTRkZThmLTE1NGItNDhkOC04MzdlLWYxMjE5Mzc0OGE5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxNjIyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzljYmY5MjYyYTZiNGVkZDgzN2QzMmUyNDg5OTUwYzFhYjljNzA2NjdmYmM2MmM4MzQ4Y2M2OGQzODY4OWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PSpQah5nqqqFzZa_TaQ_oR1_Ddo1pKIuWUF-uV8xub0"> This was great, I will miss the feature if that's not possible anymore.
