### ISSUE TITLE
more time options

### ISSUE THREAD

**Issue by qaboei** [raycast/extensions#13423]
### Extension

https://www.raycast.com/ike-gg/clean-keyboard

### Description

it would be nice to have an indefinite time option or the option to specify the time above 5 minutes

### Who will benefit from this feature?

me

**Comment by owain-williams** [comment]
Custom and indefinite times are a bit of a stretch due to the duration options, but I've added 1 hour and 24 hour options in the hope that this satisfies your use case. https://github.com/raycast/extensions/pull/13430
