### ISSUE TITLE
[YouTube Downloader] Downloads not working...

### ISSUE THREAD

**Issue by brunocbreis** [raycast/extensions#13434]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

 1.78.1

### macOS Version

Version 14.5 (23F79)

### Description

The extension seems to be broken. Is it that the service it uses to download from YouTube might be down?

### Steps To Reproduce

1. try to download a video, say https://youtu.be/QYquJ-USWOo
2. It fails

### Current Behaviour

Doesn't download. Displays this toast: 
![Arc-ss-001277@2x](https://github.com/raycast/extensions/assets/85531625/fd1094bc-0d88-4830-98ba-fa70ff0cdc05)

### Expected Behaviour

Downloads the video

**Comment by brunocbreis** [comment]
```
catch (err) {
    toast.title = "Download Failed";
    toast.style = Toast.Style.Failure;
    const error = err as Error;
    if (error.message.includes("private video")) {
      toast.message = "This video is private and cannot be downloaded.";
    } else if (error.message.includes("429")) {
      toast.message = "You have exceeded your download quota.";
    } else {
      toast.message = "Please try again later. " + error.message;
    }
    return;
```

i forked the extension and added this bit to learn more about the error and apparently we're getting a 403 status code from the request
![Arc-ss-001279@2x](https://github.com/raycast/extensions/assets/85531625/0fafa635-1c69-4e44-8b21-3c5f0d681c36)

**Comment by brunocbreis** [comment]
https://github.com/fent/node-ytdl-core/issues/1295

👆 seems to be a problem with the service

**Comment by ridemountainpig** [comment]
@raycastbot close this issue
