### ISSUE TITLE
[Messages] ...

### ISSUE THREAD

**Issue by ksandvik** [raycast/extensions#13443]
### Extension

https://www.raycast.com/thomaslombart/messages

### Description

Could messages remember the last contact used when sent a message in the popup so it's selected by default

### Who will benefit from this feature?

More common pattern than selecting 'looks like' an arbitrary value in the popup for the sender.

**Comment by shiyu-dev** [comment]
[messages](https://www.raycast.com/thomaslombart/messages) seems to be able to remember the most recent contact now, but cannot remember the number/email sent to that contact.

**Comment by thomaslombart** [comment]
Only the contact name is remembered as of now. Could you share a recording? It'll make it easier to see what's happening.

**Comment by ksandvik** [comment]
Close this, I got it working. I just use the latest one over and over to send to the same recipient. Maybe at some point it would be nice to add an alias or fuzzy search to find the entry in the Contact list and bypass the whole dialog. 

Feel free to close this.
