### ISSUE TITLE
[Image Modification] ...

### ISSUE THREAD

**Issue by meta-blog** [raycast/extensions#13453]
### Extension

https://www.raycast.com/HelloImSteven/sips

### Raycast Version

Version 1.78.1

### Description

![Microsoft Edge  - 03월 12일 15 03 28](https://github.com/user-attachments/assets/422caaa6-8b1a-4cc6-9d60-7a1d772edea6)

I was using the image transformation extension in Raycast without any issues. However, at some point, I started encountering errors when using the WebP image optimization feature.

It used to work fine before. I apologize for not being able to provide a detailed report on the error as I am not very familiar with the technical aspects of the program. However, I will attach an image to this message.

### Steps To Reproduce

1. Select WebP image
2. Execute Optimize function

**Comment by SKaplanOfficial** [comment]
@raycastbot close this issue
