### ISSUE TITLE
[YouTube Downloader] Download failed. Please try again later.

### ISSUE THREAD

**Issue by JCionx** [raycast/extensions#13451]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

1.78.1

### macOS Version

14, 15

### Description

 Can't download videos with this extension.

### Steps To Reproduce

1. Open the extension
2. Paste a URL for a youtube video
3. Click download

### Current Behaviour

I get the error: Download failed. Please try again later.

![Screenshot 2024-07-12 at 20 02 28](https://github.com/user-attachments/assets/32fbc7ec-b9f5-445d-8458-ce15f027a741)

### Expected Behaviour

I expected the video to download

**Comment by Merchify-io** [comment]
I have the same bug

**Comment by ridemountainpig** [comment]
@raycastbot close this issue
