### ISSUE TITLE
[Minecraft Color Codes] Add support for changing section sign to '&'

### ISSUE THREAD

**Issue by ChedRed** [raycast/extensions#13467]
### Extension

https://www.raycast.com/lafkpages/minecraft-color-codes

### Description

Since most servers use '&' as a replacement for the section sign, there could be a keybind to swap the '§'s in the copy menu for ampersand.

### Who will benefit from this feature?

Anyone who plays on servers and needs to quickly copy a color code.

**Comment by lafkpages** [comment]
@raycastbot assign me
