### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by ssmmuu** [raycast/extensions#13471]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

1.78.1

### macOS Version

14.5

### Description

Gwtting an error - cannot download video
https://github.com/user-attachments/assets/9a30766d-98f1-4441-8d87-03a0a86531ce
![CleanShot 2024-07-14 at 10 51 44](https://github.com/user-attachments/assets/f85921be-2c6d-4be4-8b97-4b4f332be480)

### Steps To Reproduce

open the command, paste a youtube link, download doesnt work

### Current Behaviour

Download doesnt work

### Expected Behaviour

Should download the video

**Comment by ridemountainpig** [comment]
@raycastbot close this issue
