### ISSUE TITLE
[Iconify — Search Icons] ...

### ISSUE THREAD

**Issue by chadami** [raycast/extensions#1347]
# Extension – [Iconify — Search Icons](https://github.com/raycast/extensions/tree/6c27faad5f848a8d8c2821ca0873d6db50f20ccb/extensions/iconify/)
Author: @Destiner

## Description
![](https://tva1.sinaimg.cn/large/e6c9d24egy1h13aaqrho5j20ny0gawex.jpg)

## Error:
```
Error: connect ECONNREFUSED 0.0.0.0:443

__node_internal_captureLargerStackTrace:errors:464:5
__node_internal_exceptionWithHostPort:errors:642:12
TCPConnectWrap.afterConnect:node:net:1146:16
```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.32.1

**Comment by Aayush9029** [comment]
![CleanShot 2022-04-10 at 14 35 38](https://user-images.githubusercontent.com/43297314/162634394-19a738a0-4a72-4d17-a082-bcb27d537220.png)

Can you confirm if this is still persistent @chadami ?
