### ISSUE TITLE
[Plex] ...

### ISSUE THREAD

**Issue by ssmmuu** [raycast/extensions#13485]
### Extension

https://www.raycast.com/mSarheed/plex

### Description

Would it be possible to **search** the media library? As far as I can tell, right now the extension lists the media in the library. 

### Who will benefit from this feature?

Everyone, I guess

**Comment by owain-williams** [comment]
If you update the extension (open Raycast -> "Check for extension updates"), the functionality for searching the library has been added in the last couple of days.

If you wouldn't mind checking back in if you have any comments, or just to confirm it works as expected, then we can action the ticket.

**Comment by ssmmuu** [comment]
Search works, thanks very much
