### ISSUE TITLE
[Coffee]  Modify the "caffeinate for" command in Raycast to quickly close the main window immediately after the user presses Enter. 

### ISSUE THREAD

**Issue by bigplayer-ai** [raycast/extensions#13486]
### Extension

https://www.raycast.com/mooxl/coffee

### Raycast Version

1.78.1

### macOS Version

14.5

### Description

To enhance the user experience, please modify the "caffeinate for" command in Raycast to automatically and quickly close the main window immediately after the user presses Enter. Currently, the delay in closing the window after triggering the command causes a noticeable lag. 

### Steps To Reproduce

1. Open Raycast action bar.
2. Enter the "caffeinate for" command with arguments.
3. Press Enter to execute the command.

### Current Behaviour

- The main window remains open for a noticeable period before closing, causing a delay and disrupting the user experience, it gets back to the action raycast bar then exits with taking a slight delay which feels unnatural and unresponsive.

### Expected Behaviour

- The main window should close immediately after pressing Enter, ensuring a seamless user experience without any noticeable lag.

**Comment by ridemountainpig** [comment]
@raycastbot close this issue
