### ISSUE TITLE
[I Don't Have Spotify] Spotify link not being validated properly

### ISSUE THREAD

**Issue by brunocbreis** [raycast/extensions#13488]
### Extension

https://www.raycast.com/sjdonado/idonthavespotify

### Raycast Version

1.80.0

### macOS Version

14.5

### Description

I pasted a Spotify link (specifically this one: https://open.spotify.com/album/3kjHLu1pL7tdY88GFwEkl6?si=oVIZ-ZbfQM2S1M7IM1f6RQ) and got an error that printed some json output saying it isn't valid. 
![idonthavespotify 2024-07-15 at 06 49 48](https://github.com/user-attachments/assets/ebd6c78b-78ed-4fb5-849a-df6934f63684)

### Steps To Reproduce

1. Have Spotify link in clipboard
2. Launch the extension

### Current Behaviour

throws error

### Expected Behaviour

validates link and shows other sources

**Comment by sjdonado** [comment]
Fixed already https://github.com/raycast/extensions/pull/13494
@raycastbot close this issue
