### ISSUE TITLE
[Shell] Add input method?

### ISSUE THREAD

**Issue by ChedRed** [raycast/extensions#13496]
### Extension

https://www.raycast.com/asubbotin/shell

### Description

I can type out commands or responses (eg. answering [Y/n] prompts) for the process running in the raycast terminal. Also an indicator for when the command finishes.

### Who will benefit from this feature?

Any developer who needs to quickly install an api, or a simple user installing stuff will benefit from the first. Anyone and every terminal user could benefit from the second.

**Comment by kevinm6** [comment]
@ChedRed I’m not the author of this extension, but just a small contributor.
I’m submitting a **PR** to add an indicator for the result, which should partially address your request.
Meanwhile, I don’t think handling *prompt replies* is part of the extension’s current scope, as supporting that would require changes to how the command is evaluated and might even necessitate changes to the **UI** based on which command is entered.

**Comment by ChedRed** [comment]
Ello kevin, thank you for submitting a PR and contributing to the project. For the prompt handling, I was wondering if there was some builtin system that enabled for following commands to be sent. That being said, I have not looked at the code for any raycast plugin nor have I developed one. However, I do have an example from the Raycast Arcade extension, where a guess can be submitted. Thank you for your help!
![Screenshot 2024-07-21 at 20 29 55](https://github.com/user-attachments/assets/1f8f6dfc-7116-44c5-9449-362e62c3ea39)

**Comment by jfkisafk** [comment]
Hello @ChedRed , after the execution has started and the `Detail` view is showing, it is incredibly hard to take user input based on prompts. We can parse each statement and use:

```
osascript -e 'display dialog ...
```

or a `Form`

to open a dialog for user input, but based on the variabilities, it is much easier to just pipe the command with a `yes`, so execute this: `yes | <your command...>`
