### ISSUE TITLE
[Coffee] Menu item only works when Raycast Settings is open

### ISSUE THREAD

**Issue by Fe2-O3** [raycast/extensions#13490]
### Extension

https://www.raycast.com/mooxl/coffee

### Raycast Version

1.78.1

### macOS Version

14.5

### Description

so I can click on the caffeinated menu bar, but I cant do anything with it unless Raycast Settings is open.  I think this video actually explains it.  

https://github.com/user-attachments/assets/fab33bd4-0376-40f0-913b-bae4375b9f71

### Steps To Reproduce

cant click on coffee menu unless Raycast settings is open

### Current Behaviour

menu doesnt work

### Expected Behaviour

menu button should work

**Comment by pernielsentikaer** [comment]
I was not able to reproduce this, does it happens all the time for you?
