### ISSUE TITLE
Claude

### ISSUE THREAD

**Issue by sorec574** [raycast/extensions#13517]
### Extension

https://github.com/raycast/extensions/tree/87f6dd8d99a38a61a4bc38b3a0014fffe5166c0b/extensions/claude

### Description

Anthropic has doubled the max output token limit for Claude 3.5 Sonnet from 4096 to 8192 in the Anthropic API ([Source](https://x.com/alexalbert__/status/1812921642143900036)).

### Who will benefit from this feature?

Anyone using the Claude extension.

**Comment by florisdobber** [comment]
Already addressed in #13527.

**Comment by florisdobber** [comment]
@raycastbot close this issue
