### ISSUE TITLE
[Raindrop.io] Add support for Vivaldi for "Save Browser Tab" feature

### ISSUE THREAD

**Issue by baslat** [raycast/extensions#13524]
### Extension

https://www.raycast.com/lardissone/raindrop-io

### Description

The function "Save Browser Tab" doesn't support Vivaldi browser. Please consider adding support for it. A quick test suggests adding this should work:

```ts
case "com.vivaldi.Vivaldi":
    return runAppleScript(`tell application "Vivaldi" to return URL of front document`);
```

### Who will benefit from this feature?

People who use Vivaldi, Raindrop and Raycast.

**Comment by j3lte** [comment]
Implemented #13735 

@raycastbot close this issues
