### ISSUE TITLE
[YouTube Music] ...

### ISSUE THREAD

**Issue by NilsLeo** [raycast/extensions#13535]
### Extension

https://www.raycast.com/danieldbird/youtube-music

### Raycast Version

1.79.0

### macOS Version

14.5 (23F79)

### Description

I have this configured with the arc Browser. Unfortunately it won't work with youtube music. However if i have a regular youtube video (not YT Music), it will skip to the next youtube video.

### Steps To Reproduce

1. Arc Browser, one tab with YT Music, another tab with regular Youtube and a Video playing
2. Default config
3. Run "Next track"
4. See as it skips the regular youtube video but not YT Music

**Comment by vmx2f** [comment]
any chance for this extension to work in windows? :D
