### ISSUE TITLE
[Google Meet] ...

### ISSUE THREAD

**Issue by luckyand7** [raycast/extensions#13531]
### Extension

https://www.raycast.com/vitoorgomes/google-meet

### Description

its copied this link https://meet.google.com/landing, instead the link with the meet code so i can easily paste it to coworker

### Who will benefit from this feature?

better flow using create gmeet in raycast

**Comment by iwex** [comment]
@luckyand7, it should open - https://meet.google.com/new, and this link will create a meeting.
I can't say why you are redirected to https://meet.google.com/landing.

**Comment by luckyand7** [comment]
yes its redirected correctly, but copied to my clipboard is this url: https://meet.google.com/landing

**Comment by iwex** [comment]
What is you browser?
Could you please record screen with this bug?

**Comment by luckyand7** [comment]
https://github.com/user-attachments/assets/06e98206-2713-4384-9f83-dc2cf7d744d9

im using chrome

**Comment by iwex** [comment]
Here is PR for your problem
https://github.com/raycast/extensions/pull/13532

**Comment by luckyand7** [comment]
Thank you🙏

**Comment by iwex** [comment]
@luckyand7 please check

**Comment by iwex** [comment]
@raycastbot close this issue
