### ISSUE TITLE
[Apple Reminders] Wrong Date

### ISSUE THREAD

**Issue by upviral** [raycast/extensions#13536]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Raycast Version

1.69.0

### macOS Version

14.5 (23F79)

### Description

When creating a new reminder, and I write "Monday" in the "Due Date" field, it picks August 1 2024.

Since it's currently July 18, the expected outcome would be July 22 2024.

See the attached video. 
https://github.com/user-attachments/assets/477aa62a-8795-40d8-84b9-223cf5f6769f

### Steps To Reproduce

Create a new reminder.
Enter "Monday" in the "Due Date" field.

(It's currently July 18)

### Current Behaviour

It will create the reminder on August 1.

### Expected Behaviour

It should create the reminder on July 22.

**Comment by iwex** [comment]
I guess you have old extension because I have other fields. Please reinstall and check again
![tBT1TsCn](https://github.com/user-attachments/assets/e9f8bc5b-13fa-441d-9ec5-144c126b421b)
