### ISSUE TITLE
[Coffee] Countdown

### ISSUE THREAD

**Issue by jsc0ded** [raycast/extensions#13539]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

Would love to see a countdown of the remaining time that ones device will be caffeinated for. 

I'll frequently caffeinate for the day (say 7.5 hours) but then leave my machine for one reason or another (finish early) and understanding how much time is left would be super useful. Yes, I could decaffeinate, but I _might_ come back so sometimes I don't want to... 😅

**Comment by pernielsentikaer** [comment]
So you want the number of time left in the menubar?

**Comment by jsc0ded** [comment]
Yes, that's correct, the amount of time left for caffeination.

**Comment by Metamba** [comment]
This is a great idea! I was just going to submit this.
