### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by E4P-prod** [raycast/extensions#13549]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

Unable to download any videos at all. Just updated my raycast today and all videos have started to fail

### Steps To Reproduce

Not a coder so have not gotten into teh code, i just use the shortcut to the extension and paste my video and hit enter and it fails after a few seconds

**Comment by ridemountainpig** [comment]
I have tried the extension, it worked successfully. Could you please reinstall the YouTube Downloader and try again?

**Comment by pr0d5h381** [comment]
I've tried the extension today, and got download failed error. Usually stops at 14% or don't even start at all. I've reinstalled it multiple times, as well as i've restarted my computer.

**Comment by pr0d5h381** [comment]
> I've tried the extension today, and got download failed error. Starts with "Downloading failed" and ramps up to 14% and fades away or don't even start at all and shows the error. I've reinstalled it multiple times, as well as i've restarted my computer. ![image](https://private-user-images.githubusercontent.com/69452857/356229432-ed2a3753-e259-48f7-a5fd-3bd54f0d8f4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTE0MTUsIm5iZiI6MTcyMzU1MTExNSwicGF0aCI6Ii82OTQ1Mjg1Ny8zNTYyMjk0MzItZWQyYTM3NTMtZTI1OS00OGY3LWE1ZmQtM2JkNTRmMGQ4ZjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEyMTE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYWM3NzI1NDdmMGQxZjE2N2M4YWRhODM4MmY2ZTYyYmNmNWFlZGQyODI5Mzg1MGVjOGZhNjhhODQxZjVhYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-8u5D9HrkcDXJdBTDKmXR-oGIhxbT03xSfj47fW996g)

Ok i guess it started working like nothing was wrong after few days.

**Comment by ridemountainpig** [comment]
Fixed in https://github.com/raycast/extensions/pull/13939.

**Comment by ridemountainpig** [comment]
@raycastbot close this issue
