### ISSUE TITLE
Bitwarden unable to log in into the vault

### ISSUE THREAD

**Issue by Monophonic1983** [raycast/extensions#13550]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Raycast Version

1.79.1

### macOS Version

14.4.1

### Description

After installing the CLI, and made sure the cliend id and secret are accurate, somehow I couldn't get logged in into my vault. It said that "Invalid master password". However, with the same password, I can log in in any other places like bitwarden official app and on the web. 

![CleanShot 2024-07-19 at 18 47 26@2x](https://github.com/user-attachments/assets/6ef42771-91f2-4005-9b14-f223863842ba)

### Steps To Reproduce

1. using homebrew to install cli as instructed
```brew install bitwarden-cli```
2. copy and paste the client id and secret into corresponding fields
3. type in the master password

**Comment by jomifepe** [comment]
Hey, please see https://github.com/raycast/extensions/issues/13329#issuecomment-2238743439

**Comment by Monophonic1983** [comment]
> Hey, please see [#13329 (comment)](https://github.com/raycast/extensions/issues/13329#issuecomment-2238743439)

Thanks! Problem solved!
