### ISSUE TITLE
[Hue] After several changes to mapping of lights to rooms, "Set Scene" crashes in Raycast. "Control Groups" still works.

### ISSUE THREAD

**Issue by myfineapps** [raycast/extensions#13568]
### Extension

https://www.raycast.com/pindab0ter/hue

### Raycast Version

1.79.1

### macOS Version

14.5

#### Error:
```
Error: unknown format: #NaNNaNNaN

S:chroma.js:186:18

---
183:             var rgb = _input.format[mode].apply(null, autodetect ? args : args.slice(0,-1))

### Steps To Reproduce

I suspect the bug is not easily reproducible, but hope the error message does help.

### Current Behaviour

After several changes to mapping of lights to rooms, "Set Scene" crashes in Raycast. "Control Groups" still works.

### Expected Behaviour

Set Scenes shouldn't crash

**Comment by pindab0ter** [comment]
Hey, thank you for reporting this. I'm afraid I'd need at least a stack trace to be able to debug this one. The error shows the line where the exception is thrown, but that's deep inside of the `chroma-js` dependency, which doesn't tell me enough.

Do you think you'd be able to provide a stack trace?
