### ISSUE TITLE
[SimpleTexOCR] "The maximum number of concurrent requests exceeded, please try again later"

### ISSUE THREAD

**Issue by Erik262** [raycast/extensions#13571]
### Extension

https://www.raycast.com/Arthals/simpletexocr

### Raycast Version

1.79.1

### Description

When taking a screenshot for OCR, the following error appears:
![image](https://github.com/user-attachments/assets/5cabd65e-9712-4753-a14b-885dceed45b5)

The maximum number of concurrent requests is not to be exceeded on my side.

### Steps To Reproduce

Just take a screenshot with this tool; it doesn't matter where you are doing

**Comment by zhuozhiyongde** [comment]
Please update to the latest version. This might be an issue with the API support region. You can try selecting the `global` server and see if this resolves the issue.

**Comment by Erik262** [comment]
> Please update to the latest version. This might be an issue with the API support region. You can try selecting the `global` server and see if this resolves the issue.

It does work now, but where I'm suppose to change the region?

**Comment by zhuozhiyongde** [comment]
> > Please update to the latest version. This might be an issue with the API support region. You can try selecting the `global` server and see if this resolves the issue.
> 
> 
> 
> It does work now, but where I'm suppose to change the region?

Raycast settings - Extensions

**Comment by Erik262** [comment]
> > > Please update to the latest version. This might be an issue with the API support region. You can try selecting the `global` server and see if this resolves the issue.
> > 
> > 
> > It does work now, but where I'm suppose to change the region?
> 
> Raycast settings - Extensions

![image](https://github.com/user-attachments/assets/80725497-9360-41a5-9ba9-1e69c7882576)

**Comment by zhuozhiyongde** [comment]
> Nothing in the config as well.

Please uninstall and reinstall. It currently appears that Raycast did not automatically update this extension.

**Comment by zhuozhiyongde** [comment]
@Erik262 I would like to ask if the issue has been resolved? If it has been resolved, please close this issue.
