### ISSUE TITLE
[Time-Traveling World Clock] Add country flag as icon

### ISSUE THREAD

**Issue by vbshubham** [raycast/extensions#13575]
### Extension

https://www.raycast.com/marky/world-clock

### Description

Please add a country flag as an icon next to the city names. This will make the cities more easily recognizable and add a colorful, fun element to the interface.

### Who will benefit from this feature?

Every one

**Comment by iwex** [comment]
Hello! Added here https://github.com/raycast/extensions/pull/13576

**Comment by iwex** [comment]
@raycastbot close this issue

**Comment by iwex** [comment]
@vbshubham merged

**Comment by ridemountainpig** [comment]
@raycastbot close this issue
