### ISSUE TITLE
[Time-Traveling World Clock] Add day of the week with Time.

### ISSUE THREAD

**Issue by vbshubham** [raycast/extensions#13574]
### Extension

https://www.raycast.com/marky/world-clock

### Description

Please also add day of the week with time. So that we know if it is tonight or tomorrow easily. 

### Who will benefit from this feature?

Every user

**Comment by ridemountainpig** [comment]
@raycastbot close this issue

**Comment by ridemountainpig** [comment]
@raycastbot close this issue
