### ISSUE TITLE
Figma File Search fails to provide access to raycast

### ISSUE THREAD

**Issue by Gareth71** [raycast/extensions#13577]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

I tried to link my Figma team to the Figma extension, I had to sign in via my browser and when I returned to raycast I had an error

#### Error:
```
FetchError: request to https://oauth.raycast.com/v1/token/qTlHR2nhUt2e07Ynlbw-T4ALSoDPrGnUZU4z1VsH-scRq-We8cI9RfPKJb9UfEau0bCVYIc0qtW5fOVJ0rtUwDN6KSg5d8XgR_wRofMYARLRzAWhTb5mFsXTdFZl3GPQfA failed, reason: unable to get local issuer certificate

    at withAccessToken(A5)
_r:index.js:8:2593
    at ray-navigation-stack
Eo:index.js:8:2094
```

### Steps To Reproduce

With above raycast and macOS
Select "Search Files" command from Figma extension
In Connect your Figma account screen click Sign in with Figma
In this screen 
<img width="440" alt="image" src="https://github.com/user-attachments/assets/1d83fe9b-38ff-4c58-9a37-73e24c347eb6">
Click allow access
In this screen
<img width="525" alt="image" src="https://github.com/user-attachments/assets/ae586a32-59af-47a9-91f1-a28e560a6ee5">
click open to raycast (I had to use button chrome provided rather the one in the webpage)
See this screen
<img width="552" alt="image" src="https://github.com/user-attachments/assets/1caf635c-4db0-4ad5-82a9-a61ea2398d7f">

### Current Behaviour

see error message

### Expected Behaviour

Figma account would be linked and would be able to search files

**Comment by michaelwschultz** [comment]
@Gareth71 thanks for reporting. Have you also added your team ID in the extension settings?

Appreciate the in-depth report btw. I think a few of the small bugs you ran into are Raycast issues and I'll pass them along.

**Comment by Gareth71** [comment]
Yes, I added my teams id following the instructions I found from a website I googled (see below). I checked and I can see it in the extensions settings.GarethOn 20 Jul 2024, at 5:56 PM, Michael Schultz ***@***.***> wrote:﻿
@Gareth71 thanks for reporting. Have you also added your team ID in the extension settings?
Appreciate the in-depth report btw. I think a few of the small bugs you ran into are Raycast issues and I'll pass them along.

**Comment by chrisd008** [comment]
I'm having the same issue. After entering the team ID, clicking "sign in with figma" button, and then allowing access, I just get the "something went wrong" message. If I had to guess there may be an issue with our Figma SSO / security settings that is preventing this from working. Even as a Figma admin in my org I don't see a way to add Raycast to the "connected apps" list within Figma's settings.

**Comment by michaelwschultz** [comment]
@thomaspaulmann mind weighing in here?
