### ISSUE TITLE
[GitHub] missing token permission error

### ISSUE THREAD

**Issue by glekner** [raycast/extensions#13588]
### Extension

https://raycast.com/raycast/github

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

getting this following error when using the Github Search pull requests command:
```
Your token has not been granted the required
scopes to execute this query. The 'id' field
requires one of the following scopes:
['read:project'], but your token has only bee...
```

the command successfully returns results but i'm getting an annoying error each time.
even though I injected my `gh` auth token which has all the needed permissions.

### Steps To Reproduce

1. Open Search pull requests
2. see error at bottom of raycast window

**Comment by thomaslombart** [comment]
Is it possible to post the full error log?

**Comment by glekner** [comment]
trying to report results in `request URL too long` error, so i'm posting the URL here
https://github.com/raycast/extensions/issues/new?&labels=extension%2Cbug&template=extension_bug_report.yml&title=%5BGitHub%5D...&extension-url=https://raycast.com/raycast/github&description=%23%23%23%23%20Error%3A%0A%60%60%60%0AError%3A%20Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27id%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%3A%20%7B%22response%22%3A%7B%22errors%22%3A%5B%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A29%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27id%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A30%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27title%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A31%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27public%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A32%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27number%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A33%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27readme%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A34%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27closed%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A35%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27shortDescription%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A36%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27url%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A37%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27createdAt%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A41%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27updatedAt%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A82%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27id%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A83%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27name%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A84%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27number%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A48%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27viewerCanClose%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A49%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27viewerCanUpdate%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%2C%7B%22type%22%3A%22INSUFFICIENT_SCOPES%22%2C%22locations%22%3A%5B%7B%22line%22%3A50%2C%22column%22%3A3%7D%5D%2C%22message%22%3A%22Your%20token%20has%20not%20been%20granted%20the%20required%20scopes%20to%20execute%20this%20query.%20The%20%27viewerCanReopen%27%20field%20requires%20one%20of%20the%20following%20scopes%3A%20%5B%27read%3Aproject%27%5D%2C%20but%20your%20token%20has%20only%20been%20granted%20the%3A%20%5B%27gist%27%2C%20%27read%3Aorg%27%2C%20%27repo%27%2C%20%27workflow%27%5D%20scopes.%20Please%20modify%20your%20token%27s%20scopes%20at%3A%20https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens.%22%7D%5D%2C%22status%22%3A200%2C%22headers%22%3A%7B%7D%7D%2C%22request%22%3A%7B%22query%22%3A%22query%20getViewer%20%7B%5Cn%20%20viewer%20%7B%5Cn%20%20%20%20...UserFields%5Cn%20%20%20%20organizations(first%3A%2050)%20%7B%5Cn%20%20%20%20%20%20totalCount%5Cn%20%20%20%20%20%20nodes%20%7B%5Cn%20%20%20%20%20%20%20%20avatarUrl%5Cn%20%20%20%20%20%20%20%20login%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%20%20projectsV2(first%3A%2050)%20%7B%5Cn%20%20%20%20%20%20totalCount%5Cn%20%20%20%20%20%20nodes%20%7B%5Cn%20%20%20%20%20%20%20%20...ProjectFields%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20UserFields%20on%20User%20%7B%5Cn%20%20id%5Cn%20%20avatarUrl%5Cn%20%20name%5Cn%20%20login%5Cn%20%20isViewer%5Cn%7D%5Cn%5Cnfragment%20ProjectFields%20on%20ProjectV2%20%7B%5Cn%20%20id%5Cn%20%20title%5Cn%20%20public%5Cn%20%20number%5Cn%20%20readme%5Cn%20%20closed%5Cn%20%20shortDescription%5Cn%20%20url%5Cn%20%20createdAt%5Cn%20%20creator%20%7B%5Cn%20%20%20%20...AuthorFields%5Cn%20%20%7D%5Cn%20%20updatedAt%5Cn%20%20views(first%3A%2050)%20%7B%5Cn%20%20%20%20totalCount%5Cn%20%20%20%20nodes%20%7B%5Cn%20%20%20%20%20%20...ProjectViewerFields%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%20%20viewerCanClose%5Cn%20%20viewerCanUpdate%5Cn%20%20viewerCanReopen%5Cn%7D%5Cn%5Cnfragment%20AuthorFields%20on%20Actor%20%7B%5Cn%20%20...%20on%20Bot%20%7B%5Cn%20%20%20%20id%5Cn%20%20%20%20login%5Cn%20%20%20%20avatarUrl(size%3A%2064)%5Cn%20%20%7D%5Cn%20%20...%20on%20User%20%7B%5Cn%20%20%20%20...UserFields%5Cn%20%20%7D%5Cn%20%20...%20on%20Mannequin%20%7B%5Cn%20%20%20%20id%5Cn%20%20%20%20login%5Cn%20%20%20%20avatarUrl(size%3A%2064)%5Cn%20%20%7D%5Cn%20%20...%20on%20Organization%20%7B%5Cn%20%20%20%20id%5Cn%20%20%20%20login%5Cn%20%20%20%20name%5Cn%20%20%20%20avatarUrl(size%3A%2064)%5Cn%20%20%7D%5Cn%20%20...%20on%20EnterpriseUserAccount%20%7B%5Cn%20%20%20%20id%5Cn%20%20%20%20login%5Cn%20%20%20%20name%5Cn%20%20%20%20avatarUrl(size%3A%2064)%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20ProjectViewerFields%20on%20ProjectV2View%20%7B%5Cn%20%20id%5Cn%20%20name%5Cn%20%20number%5Cn%7D%22%7D%7D%0A%20%20%20%20at%20m_%20(%2FUsers%2Fglekner%2F.config%2Fraycast%2Fextensions%2F89648e03-cceb-4205-9f40-75fcb039a4c6%2Fmy-pull-requests.js%3A239%3A19401)%0A%20%20%20%20at%20process.processTicksAndRejections%20(node%3Ainternal%2Fprocess%2Ftask_queues%3A95%3A5)%0A%20%20%20%20at%20async%20%2FUsers%2Fglekner%2F.config%2Fraycast%2Fextensions%2F89648e03-cceb-4205-9f40-75fcb039a4c6%2Fmy-pull-requests.js%3A1270%3A27968%0A%60%60%60%0A

not sure its helpufl @thomaslombart

**Comment by thomaslombart** [comment]
Are you sure you've granted the scopes? This doesn't seem to happen for other users… You can check out the required scopes over [here](https://www.raycast.com/raycast/github#readme). If it still doesn't work, could you log in through OAuth and see if it still fails?

**Comment by glekner** [comment]
@j3lte As I said the command successfully returns results, it's working but the error is very annoying. Also, this token is from the `gh` cli. Correct me if I'm wrong but this token should have all the needed permissions

<img width="886" alt="image" src="https://github.com/user-attachments/assets/48ff7617-677b-4460-b5fa-f72bb6a9266c">

**Comment by j3lte** [comment]
@glekner if I look at the Github Cli documentation, I'm going to go out on a limb and say you are probably wrong...

https://cli.github.com/manual/gh_auth_login

The documentation there states:

```
Alternatively, use --with-token to pass in a token on standard input. The minimum required scopes for the token are: repo, read:org, and gist.
```

That would suggest that the Github Cli will authenticate with the minimum amount of scopes. You should be able to find the scopes for this token in your Github profile...

I could be wrong here, but it would be worth checking out?

**Comment by glekner** [comment]
ok TIL, thanks for that @j3lte .
getting a token with `gh auth login -s read:project` fixes the issue, but I do see a bug here regardless with trying to report it and the URL being too long
