### ISSUE TITLE
[1Password] Do not require authentication as long as 1Password is unlocked

### ISSUE THREAD

**Issue by melikarslan** [raycast/extensions#13590]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Having to re-authorize every 10 min makes this workflow slower compared to using 1Password directly. Alfred's 1Password extension do not require authentication as long as 1P is unlocked. Can you please do the same?

**Comment by Luk4h** [comment]
Hello @melikarslan, There is an option on the extension properties, to make it not necessary to enter your password every 10  minutes, It will ask once, and you will be able to use it without needing to input your password every 10 minutes.
@raycastbot close this issue

**Comment by melikarslan** [comment]
> Hello @melikarslan, There is an option on the extension properties, to make it not necessary to enter your password every 10 minutes, It will ask once, and you will be able to use it without needing to input your password every 10 minutes. @raycastbot close this issue

I was aware of this feature and was using it. However, I find myself re-authenticating 1Password dozens of times a day. Please consider not requiring authentication while 1Password is unlocked or extending the 10-minute period to 1-2 hours.
