### ISSUE TITLE
[Figma File Search]

### ISSUE THREAD

**Issue by eshamh** [raycast/extensions#13597]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Raycast Version

1.79.1

### macOS Version

13.2 (22D49)

### Description

This keeps crashing after 3,4 days of use. It says could not load files when you try to search for any Figma file

<img width="762" alt="Screenshot 2024-07-22 at 12 45 00 PM" src="https://github.com/user-attachments/assets/afc3d9ac-b1a4-45c7-beb9-900cb6fa65cf">

### Steps To Reproduce

1.Install Figma search
2. Run it for a few days i.e search for files
3. You'll see the error after few days, you won't be able to search and find files

**Comment by GLaDO8** [comment]
@eshamh are you using personal access tokens or log in with figma to authenticate the extension?

**Comment by megaroeny** [comment]
I ran into this as well. I was using the PAT method, and was working prior.

**Comment by michaelwschultz** [comment]
@megaroeny nuts. Was hoping this was a one off. I'll take a look when I can. Sorry about that.

**Comment by megaroeny** [comment]
> @megaroeny nuts. Was hoping this was a one off. I'll take a look when I can. Sorry about that.

No problem! 👍 I'll try logging in later today to see if that method works. Didn't know that was an option.

**Comment by megaroeny** [comment]
Following up, sorry so late...

It worked after reinstalling the extension so that I use the new login method! Not sure if there's a way to notify users about this if they were using a PAT before, but at least it works. 😄
