### ISSUE TITLE
[HubSpot] the search on companies doesn't seem to filter on description

### ISSUE THREAD

**Issue by vincestus** [raycast/extensions#13602]
### Extension

https://www.raycast.com/harisvsulaiman/hubspot

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

I would like to search on companies based on vat number. Therefore, I added that specific information in the description of the company but it doesn't seem to filter on it even if the corresponding data retrieved via the API is displaying that vat number as description. 

### Steps To Reproduce

1. modify company in HS by setting a description: `test description`
2. search `test description` via the raycast HubSpot Search Companies command
3. 💥

### Current Behaviour

doesn't find any results
![Screenshot 2024-07-22 at 12 44 39](https://github.com/user-attachments/assets/46906079-d3a6-41fb-832b-2c612fdd51e6)

### Expected Behaviour

display that specific company with that specific description as displayed hereunder
![Screenshot 2024-07-22 at 12 44 16](https://github.com/user-attachments/assets/16f5de9e-28a7-4a8d-8ca7-15b4f56f071b)

**Comment by j3lte** [comment]
Unfortunately that's impossible with the current setup. Have a look at [this page](https://developers.hubspot.com/docs/api/crm/search#search-default-searchable-properties)

It states that for `/crm/v3/objects/companies/search` the default searchable properties are `website`, `phone`, `name`, `domain`. It might be possible to add this using some custom filter, but it also means you'd have to combine search results...

**Comment by j3lte** [comment]
Added in #13627

@raycastbot close this issue
