### ISSUE TITLE
[Browser Bookmarks] Select the browser where to open bookmarks

### ISSUE THREAD

**Issue by Cronos87** [raycast/extensions#1361]
# Extension – [Browser Bookmarks](https://github.com/raycast/native-extensions/tree/98807c71c6ec589775952a250d7225b403e995f5/extensions/browser-bookmarks/)
Author: Raycast

# Description

It would be awesome if we can select the browser where to open the bookmark. An option in the preference of the extension would be perfect.

## Why I want this feature?

My Mac is a professional one but I'm using it for personal purposes, for this, I'm using a different browser than the one I use to work and who is the default browser.

## Raycast Version

v1.32.1

**Comment by koinzhang** [comment]
Hi @Cronos87 
I made an extension [Quick Surf](https://www.raycast.com/koinzhang/quick-surf) that opens links between different browsers. It doesn't fit your needs very well, but you can try it out.
It's easy to use, select the link/copy the link and then run this extension to select a browser to open the link

<img width="300" alt="Metadata" src="https://user-images.githubusercontent.com/36128970/162677055-5c706b27-4521-40c3-8edb-a35b08e4eaf0.png">
