### ISSUE TITLE
[Steam] Add more info to the initial search

### ISSUE THREAD

**Issue by whitespacecode** [raycast/extensions#13620]
### Extension

https://www.raycast.com/KevinBatdorf/steam

### Description

I was playing around in the code to see if i could add more info to the initial search. 
Just the price alone would be enough for me..
It kinda works by changing line 25 in ListItems.tsx from 
```ts
const { data, isError: error } = useGameData({ appid: game.appid, execute: ready });
```
to 
```ts
const { data, isError: error } = useGameData({ appid: game.appid });
``` 
And adding the price data to the accessories
![steam-7](https://github.com/user-attachments/assets/c6a12a25-788d-4003-81b7-46c7031e9175)

But when you search and have a lot of data the application would just crash. I think the `useGameData` fetch is not ready for asynchronous loading data? 
![steam-6](https://github.com/user-attachments/assets/56356fc8-5d5d-4ca3-8213-02fd0680b823)

### Anything else?

When fetching the full gamedata the initial search could show even more at first glance like is_free or not in green color, or using list.metaData with a toggle.

**Comment by KevinBatdorf** [comment]
I just tried the extension out now without any changes and after using it a bit I got the memory error. The extension is a bit old and probably due for a rewrite with better local caching and some other features like checking whether a game is installed, and maybe a better "next game to play" recommendations system.

What other features would you like?

**Comment by whitespacecode** [comment]
I game on windows so for me personally installed or not wouldn't be needed. 
I did see you can provide your own api key to the extension? Not sure if all that could be improved with a simple login to steam button to provide credentials.
