### ISSUE TITLE
[Safari] Support fuzzy search

### ISSUE THREAD

**Issue by NESOY** [raycast/extensions#13621]
### Extension

https://www.raycast.com/loris/safari

### Description

Hi, I like to use the raycast safari extension. recently I had trouble.
When searching for a bookmark, it doesn't work.

Example
- bookmark name : raycast alpha safari
- search keyword : raycast safari
- search result : no results 😂

So I wish features like the fuzzy search function would be improved further.

### Who will benefit from this feature?

who using searching bookmark, tab, reading list

**Comment by iwex** [comment]
@raycastbot close this issue
