### ISSUE TITLE
[Ollama AI] Can't load llama3.1 

### ISSUE THREAD

**Issue by ksandvik** [raycast/extensions#13629]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

Installed llama 3.1 and set it as the default model. Model never loading, this is the 8B one and the previous 3.0 model loaded just fine with M1/MacBookPro with latest 14.5 MacOSX.

### Steps To Reproduce

1. start ollama via Raycast using any of the defined scripts

### Current Behaviour

Constant loading model.

### Expected Behaviour

Model could be used.

**Comment by MassimilianoPasquini97** [comment]
I have tried right now using llama3.1:8b model with the latest version of Ollama and it work using the raycast extension. Are your using the latest Ollama release? Have you tried using directly Ollama from terminal?

**Comment by MassimilianoPasquini97** [comment]
@raycastbot assign me

**Comment by ksandvik** [comment]
Ollama-2 is running, latest brew ollama is installed. 
ollama run llama3
runs from command line.
Are there logs, preference entries or something I could inspect to see if the Raycast plugin loads right models?

**Comment by ksandvik** [comment]
Correction
$ ollama run llama3.1

works fine.

**Comment by ksandvik** [comment]
Pilot error, this was with the 'fix spelling and grammar' that expects a text selection, without it the loading icon is displayed.
