### ISSUE TITLE
Node Application Showing in Dock with Sequoia macOS when running an Extension

### ISSUE THREAD

**Issue by ZuidVolt** [raycast/extensions#13636]
### Description

I know this isn't priority but for the upcoming macOS  release and right now with that latest sequoia macOS dev beta 4 when opening Raycast any extension using node.js causes it to pop up as an icon in the Dock and not just ran in the background like before, I think this has to do with macOS newest privacy feature?

### Steps To Reproduce

- Open Raycast
- Use any extension that uses node (for example: Vscode extension)

### Current Behaviour

Causes a node exec to appear in the Dock

### Expected Behaviour

The tasks should run in the background and should not show up in the Dock

**Comment by victor-ajayi** [comment]
Same issue here. I'm not sure what the fix it, you can't quit it or remove from dock.

<img width="429" alt="image" src="https://github.com/user-attachments/assets/6fa8dfeb-bb01-45c8-8147-a96a596f1452">

**Comment by j33ty** [comment]
Enabling full-disk access for Raycast from System Settings will fix it in MacOS Sequoia Beta 4. (Understandably, a lot of folks may not want to do that)

**Comment by ZuidVolt** [comment]
> Enabling full-disk access for Raycast from System Settings will fix it in MacOS Sequoia Beta 4. (Understandably, a lot of folks may not want to do that)

the Problem still occurs after Enabling full-disk access for Raycast, is there any other steps I could take, thank you

**Comment by LitoMore** [comment]
Raycast can do nothing since you're running Raycast on the macOS Beta. It's more like a macOS issue. You have no idea whether this bug will be fixed in the next beta version.

**Comment by ZuidVolt** [comment]
> Raycast can do nothing since you're running Raycast on the macOS Beta. It's more like a macOS issue. You have no idea whether this bug will be fixed in the next beta version.

That makes sense, thank you

**Comment by mathieudutour** [comment]
This should be in macOS 15 Developer Beta 5
