### ISSUE TITLE
CotEditor support

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#13635]
### Extension

https://www.raycast.com/asnimansari/scratchpad

### Description

Hello. Would be great to have CotEditor support.

### Who will benefit from this feature?

CotEditor users.

### Anything else?

Thanks for the useful extension.

**Comment by asnimansari** [comment]
@raycastbot good first issue

**Comment by iwex** [comment]
pr - https://github.com/raycast/extensions/pull/13645

**Comment by iwex** [comment]
@pernielsentikaer please close issue

**Comment by iwex** [comment]
@raycastbot close this issue
