### ISSUE TITLE
[Wikipedia] Open with external/other viewer

### ISSUE THREAD

**Issue by ndesgranges** [raycast/extensions#13648]
### Extension

https://www.raycast.com/vimtor/wikipedia

### Description

I often use [Wikiwand](https://www.wikiwand.com/) to open my wikipedia articles as I really don't like the UI of Wikipedia.

Is there a way to add an option to add a program to open the wikipedia link ?

Thank you

### Who will benefit from this feature?

Users who use external viewers for wikipedia.

**Comment by jfkisafk** [comment]
Hey @ndesgranges , you can always configure to open wikipedia links in browser (instead of raycast) through preferences.

<img width="1112" alt="Screenshot 2024-07-25 at 4 57 29 AM" src="https://github.com/user-attachments/assets/220f84bb-56c1-4312-9858-8c6ec7d22028">

**Comment by j3lte** [comment]
@ndesgranges I tried out the "Open in browser" like @jfkisafk said, this seems to automatically open it in Wikiwand if you have the extension installed.

**Comment by j3lte** [comment]
@raycastbot close this issue

**Comment by ndesgranges** [comment]
confirmed, thank you for the heads up !
