### ISSUE TITLE
Dashlane copies password after several time opening with biometrics

### ISSUE THREAD

**Issue by JDH247** [raycast/extensions#13654]
### Extension

https://www.raycast.com/tm.wrnr/dashlane-vault

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

https://github.com/user-attachments/assets/6f2eceae-a024-4770-822c-4410ed1cf293

When I open the Dashlane search passwords command, it requires biometry (I set up the client like this).
When I succeed with biometry, it closes raycast/Dashlane command. 
I have to do this process at least twice, until I can copy the password. 

### Steps To Reproduce

1. Open up "Search Password Command (I set up a hotkey)
2. Try to copy a password
3. Proceed with biometry
4. Open um Command again
5. Try to copy password
6. Proceed again with biometry

**Comment by tmwrnr** [comment]
Hi @JDH247,

you just need to wait a little longer. After the biometric auth is completed and the data is fetched the Raycast window will open by itself. Currently there is no other solution than just wait for the Dashlane CLI to  return the data after the biometric auth.

Let me know if this is working for you.
