### ISSUE TITLE
[File Manager] Allow hiding files per extension

### ISSUE THREAD

**Issue by ndesgranges** [raycast/extensions#13651]
### Extension

https://www.raycast.com/erics118/file-manager

### Description

I would like to be able to hide files per extensions so the item lists are not bloated with files I don't care about

### Who will benefit from this feature?

People who browse through folder containing files of interest and others files like `<name>.backup` or `<name>.log`

### Anything else?

could be as simple in settings as adding a field where user could add comma separated list of extensions like:

in extension settings:
> **Extensions to hide (separate each extension with a comma like "_.log,.dbg,.tmp_") :**
> ```
> .log,.backup
> ```

**Comment by erics118** [comment]
I've opted to support `.gitignore` completely. This allows for much more complicated setups, as well as super simple setups too. Please take a look at the linked PR.

**Comment by ndesgranges** [comment]
@erics118 

This is perfect, thank you ❤️
