### ISSUE TITLE
support remote projects

### ISSUE THREAD

**Issue by sunliang711** [raycast/extensions#13656]
### Extension

https://www.raycast.com/ewgenius/zed-recent-projects

### Description

could you please support remote recent projects since new version zed currently support remote development

**Comment by ewgenius** [comment]
@sunliang711 good idea, that should fit well

Need to check how zed stores remote projects

@raycastbot assign me

**Comment by ewgenius** [comment]
update: adding support to list remote project is simple, but still figuring out how to open it using zed cli
