### ISSUE TITLE
[ligue-1] Does not work anymore "Something went wrong"

### ISSUE THREAD

**Issue by ndesgranges** [raycast/extensions#13650]
### Extension

https://www.raycast.com/anhthang/ligue-1

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

Does not display anything for any date and any command, exept for the error "Something went wrong"

<img width="755" alt="Capture d’écran 2024-07-24 à 17 03 22" src="https://github.com/user-attachments/assets/ed1b070c-a5b7-4b18-87a0-478c1e9f3965">

### Steps To Reproduce

Launch any command

### Current Behaviour

"Something went wrong"

### Expected Behaviour

Show data

**Comment by loris** [comment]
It looks like Ligue1 website got a full redesign (https://ligue1.com/), thus the scraping code @anhthang implemented back then does not work anymore

**Comment by anhthang** [comment]
Thanks for your investigation. I will look into it and update later.
