### ISSUE TITLE
how to get item by onSelectionChange.id

### ISSUE THREAD

**Issue by chyroc** [raycast/extensions#1366]
`List` components has onSelectionChange props and onSelectionChange is `(id: string) => void`

but the id is a base64 data, i cannot get the item data by the id

**Comment by sxn** [comment]
hi @chyroc - you're receiving your `List.Item`'s autogenerated ID. If you don't want an ID to be autogenerated, you can use the the [id prop](https://developers.raycast.com/api-reference/user-interface/list#list.item):

```
export default function Command() {
  return <List onSelectionChange={id => console.log(id)}>
    <List.Item id="first" title="first item" />
    <List.Item id="second" title="first item" />
  </List>
}
```

in that case, navigating between the two items should print `first` and `second` respectively. :)

**Comment by chyroc** [comment]
thanks.
