### ISSUE TITLE
TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

### ISSUE THREAD

**Issue by dtomasch** [raycast/extensions#13669]
### Extension

https://www.raycast.com/asubbotin/shell

### Raycast Version

1.79.1

### macOS Version

14.5 (23F79)

#### Error:
```
TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

Bn:index.tsx:276:41

---
273: }

### Steps To Reproduce

Uninstalled extension and then reinstalled. Same error

### Current Behaviour

Get a "something went wrong" error when trying to run command.

### Expected Behaviour

Should run a command.

**Comment by kevinm6** [comment]
@dtomasch sorry, I've tried to reproduce but I'm not able to get the same error with the steps you said.
Could you provide more info?

**Comment by dtomasch** [comment]
I wish I could — the error was happening all day today and has now vanished so I can't provide any more details.

I guess I'll close this.

**Comment by Korel** [comment]
Hello @kevinm6, sorry for writing to a closed issue, but I have encountered the same issue today and I might have a reliable way to reproduce it:
* The error happened to me after I deleted .bash_history to get rid of bash history section (I use zsh normally).
* Then I created an empty .bash_history with touch, but error persisted. 
* Then I opened bashed and entered a couple commands to populate .bash_history and with that, error went away.

**Comment by kevinm6** [comment]
> Hello [@kevinm6](https://github.com/kevinm6), sorry for writing to a closed issue, but I have encountered the same issue today and I might have a reliable way to reproduce it:
> 
> * The error happened to me after I deleted .bash_history to get rid of bash history section (I use zsh normally).
> * Then I created an empty .bash_history with touch, but error persisted.
> * Then I opened bashed and entered a couple commands to populate .bash_history and with that, error went away.

Hi @Korel, I think I figured out what’s the issue: the state used to restore the extension can’t get anymore the original path you passed since is removed/changed.
If I found some time I’ll send a fix to it
