### ISSUE TITLE
[Groq] ...

### ISSUE THREAD

**Issue by LevyDeSales** [raycast/extensions#13665]
### Extension

https://www.raycast.com/ilian/groq

### Description

Llama 3.1 

### Who will benefit from this feature?

Llama 3.1 

### Anything else?

Llama 3.1

**Comment by maximilianzuern** [comment]
@raycastbot close this issue

**Comment by maximilianzuern** [comment]
@raycastbot rename this issue to "Add new Llama 3.1 models"
