### ISSUE TITLE
[Gif Search] Favorites not added from Recents

### ISSUE THREAD

**Issue by megaroeny** [raycast/extensions#13671]
### Extension

https://raycast.com/josephschmitt/gif-search

### Description

Today I noticed that my Favorite gifs are only displaying 1 file/gif. This specifically happens from the **Recents** view.

I tried removing/adding some back, but still only shows 1 file/gif. 😕 This happens across multiple sources, not just one source.

### Reproduction steps

1. Use a GIF
2. Then go to **Recents**
3. Use `Add to Favorites` on a recent GIF
4. Go to Favorites - GIF was not added as fav.

### Who will benefit from this feature?

Anyone using Favorite GIFs

### Anything else?

Some screenshots of one example:

A favorite:
![image](https://github.com/user-attachments/assets/224afbf4-7348-4184-803d-5ec9f2e5f194)

Not shown in Favorites list:
![image](https://github.com/user-attachments/assets/3d4bd9b5-131a-44af-803d-4b01b761cabb)

**Comment by megaroeny** [comment]
I just tried adding to Favorites today, and seems to have worked itself out (unless someone pushed a fix) 🤷🏼

**Comment by megaroeny** [comment]
_Ignore my last comment, updated/edited to clarify reproduction steps._

**Comment by thomaslombart** [comment]
Thanks for reporting this bug. Would you like to work on it? If yes, here's our [guide on extension contributions](https://developers.raycast.com/basics/contribute-to-an-extension) so that you can open up a pull request. Feel free to contact me here or in the [Slack community](https://raycast.com/community) if you need further help.

**Comment by megaroeny** [comment]
> Would you like to work on it? 

I would if I knew how to... I'm not an engineer. 😅 I don't have the bandwidth currently to learn the API, but I'll browse through the files a bit to get somewhat familiar. At least I narrowed it down to the "Recents" view actions.
