### ISSUE TITLE
[Spotify Player]  not working anymore

### ISSUE THREAD

**Issue by JDH247** [raycast/extensions#13675]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.79.1

#### Error:
```
FetchError: request to https://accounts.spotify.com/api/token failed, reason: getaddrinfo ENOTFOUND accounts.spotify.com

    at withAccessToken()
    at D0
_r:index.js:8:2593
    at ray-navigation-stack
```

### Steps To Reproduce

1. Opening up raycast
2. Trying to open up spotify extension

### Current Behaviour

Since 2 days I have this issue for the spotify extension.

**Comment by iwex** [comment]
@JDH247 probably you have some vpn. try to open accounts.spotify.com in your browser?
