### ISSUE TITLE
[Extension Feature Request] Disable "recently used" for Emoji search

### ISSUE THREAD

**Issue by timonbimon** [raycast/extensions#1368]
# Extension – [Emoji](https://github.com/raycast/extensions/tree/main/extensions/emoji)

Author: @FezVrasta 

**Describe the feature and the current behavior/state.**
<img width="767" alt="image" src="https://user-images.githubusercontent.com/14793026/162689510-9090c69a-d043-45db-9c55-cd32f3c127b5.png">
Would be great to have an option to disable the "recently used"-section when searching. :) 
To me it happens quite often that the result I'm looking for is not in that section and then I have to hit the down arrow quite a few times to move past the recently-used section and to get to the right result.

**Comment by bookercodes** [comment]
Hi, friends!

Came here originally to make my own issue but I see we've run into the same problem!

When I use the **:partying_face: [Search Emoji](https://www.raycast.com/FezVrasta/emoji)** extension, it always shows my most recent emojis first even if there’s a much better-suited candidate.
For example in this case I am looking for the “call me hand” emoji but I see some recent emojis at the top instead?

![image](https://user-images.githubusercontent.com/11927968/164694313-a996a11e-7bb5-40c7-a314-651c92282415.png)

**Comment by daniel-stoneuk** [comment]
I have also come across this issue, @FezVrasta would you mind if I created a PR to disable the recently used when searching?

**Comment by zepfietje** [comment]
@daniel-stoneuk go ahead! Just came here to say I also run into this frequently.
