### ISSUE TITLE
[Docker] Colima support

### ISSUE THREAD

**Issue by Xarakiri** [raycast/extensions#13689]
### Extension

https://www.raycast.com/priithaamer/docker

### Description

The Docker extension doesn't work with Colima. 
![image](https://github.com/user-attachments/assets/38d496fb-6f0e-4c89-929f-dcbe0edcf8bc)

### Who will benefit from this feature?

Anyone who uses colima as container runtime.

**Comment by GBHU753** [comment]
It already exists... Just change the socket path to /Users/myUser/.colima/default/docker.sock
