### ISSUE TITLE
[CleanShot X] Send captured area to AI Command

### ISSUE THREAD

**Issue by ovanbiervliet** [raycast/extensions#13690]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

The current feature `Send captured area to AI chat` is always opening the chat window, and then you do your thing. It would be handy to have a sibling command `Send captured area to AI command` that lets you pick an AI command to always execute instead of sending to chat.
Ideally there would be a more than one command to pick from, not sure what's the best ux in Raycast to deal with this.

### Who will benefit from this feature?

You could setup an AI command that describes the captured image and use that to fill alt text on sites and socials.

**Comment by BirkhoffLee** [comment]
I second this - it will be a lot more smooth to use it in AI commands instead of in AI Chat, for example:

`@screenshot a region and convert to text`
`@screenshot the screen and list all window titles and send to a new @notion page`
