### ISSUE TITLE
[Things] ... AI generate checklis for task generates in french and not english and I can't change it no matter what

### ISSUE THREAD

**Issue by feedfornotes** [raycast/extensions#13698]
### Extension

https://www.raycast.com/loris/things

### Raycast Version

current

### Description

AI generate checklis for task generates in french and not english and I can't change it no matter what

### Steps To Reproduce

  generate AI checklist and response is in french despite using english.

**Comment by jfkisafk** [comment]
I think AI is reading this section of prompt incorrectly:

https://github.com/raycast/extensions/blob/773355f3082158a0d384686b819945b94dd3a4a7/extensions/things/src/helpers.ts#L39

**Comment by jfkisafk** [comment]
@raycastbot assign me
