### ISSUE TITLE
[1Password] CLI won't connect to app

### ISSUE THREAD

**Issue by Djsquid2020** [raycast/extensions#13691]
### Extension

https://www.raycast.com/khasbilegt/1password

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

For some reason, I can't get the 1Password command to run, and it always shows an error. 

> "Connecting to desktop app: 1Password CLI couldn't connect to the 1Password Desktop App. To fix this, update the desktop app to the latest version. If you're still having trouble connecting, restart the app. If you're using version 8.10.12 or earlier of the app, the 1Password CLI binary must be located in /usr/local/bin/op."

Fresh installation of 1Password for Mac 8.10.36 (81036049)
Installed the latest 1Password CLI (2.29) via Homebrew 
**Integrate with 1Password CLI** is turned on in the app
1Password is turned on in 'Allow in the Background'
Restarted 1Password & Mac

Error still there.

![CleanShot 2024-07-26 at 10 18 00@2x](https://github.com/user-attachments/assets/e3c6ed3e-5036-42fb-991a-40776bbd445f)

### Steps To Reproduce

1. Run 1Password 'My Vaults' command 
2. Shows 'Authentication Required - Please authenticate using the requested method to proceed.
3. Shows Error - _"Connecting to desktop app: 1Password CLI couldn't connect to the 1Password Desktop App. To fix this, update the desktop app to the latest version. If you're still having trouble connecting, restart the app. If you're using version 8.10.12 or earlier of the app, the 1Password CLI binary must be located in /usr/local/bin/op."_

**Comment by Luk4h** [comment]
I am also on the same App version, but it works normally for me. Not sure what is going on.

**Comment by LitoMore** [comment]
@Djsquid2020 Does the bug still exist? Could you provide the result of the command below?

```shell
realpath $(which op)
```

**Comment by sammykumar** [comment]
Same bug exists for me. It started mid-to-late July which aligns to when this issue was opened. Here's the output of that command.


```shell
sammykumar@MacBookPro-SpaceBlack ~ % realpath $(which op)
/opt/homebrew/Caskroom/1password-cli/2.30.0/op
```

**Comment by bojanstef** [comment]
I had the same issue, enabling CLI in the developer settings on the Desktop app fixed it for me

![CleanShot 2024-10-12 at 13 43 14@2x](https://github.com/user-attachments/assets/dc496109-2d18-4419-96a8-0c8e0c8e0972)

**Comment by bojanstef** [comment]
Which documentation do I add this to so that future suffers find this solution

> I had the same issue, enabling CLI in the developer settings on the Desktop app fixed it for me
> 
> ![CleanShot 2024-10-12 at 13 43 14@2x](https://private-user-images.githubusercontent.com/5675392/375975767-dc496109-2d18-4419-96a8-0c8e0c8e0972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwODEzODUsIm5iZiI6MTczMzA4MTA4NSwicGF0aCI6Ii81Njc1MzkyLzM3NTk3NTc2Ny1kYzQ5NjEwOS0yZDE4LTQ0MTktOTZhOC0wYzhlMGM4ZTA5NzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDFUMTkyNDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzgzZTg0YjM4YTU0MjQzYWU4OGIyOTNmNmI3Yjk3YWZlZTVhMGIwZTU0OTEzZTRkMGNmM2M0YzdhYzY5OThiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Fw__1OKcw32YsO59vfzHt376c_QR6WFVSs73AoC2hlw)
