### ISSUE TITLE
[DevDocs]: allow configuring default behavior to open in PWA 

### ISSUE THREAD

**Issue by manishrc** [raycast/extensions#13694]
### Extension

https://www.raycast.com/djpowers/devdocs

### Description

The "Search Documentations" command in DevDocs allows you to search and open entries in both your web browser and the DevDocs Progressive Web App (PWA). It would be helpful to have the option to open entries in the PWA by default, or at least configure the default behavior.

![CleanShot 2024-07-26 at 12  29 50@2x](https://github.com/user-attachments/assets/bc1f28cd-5b43-4c13-be78-fcf1c1dbf0fa)

**Comment by djpowers** [comment]
Thanks for the suggestion @manishrc! I'll play around with this one. My initial inclination was to keep the behavior as is to avoid added complexity, but I'll see if I can do this in a clean way. I think this would be especially helpful for people who use the command + number shortcuts, or those switching from Dash looking for a similar experience.

In terms of the user side, my thought is to add a checkbox preference to enable defaulting to the DevDocs app.

Looking for implementation examples from other Raycast extensions, I did find the [Git Repos extension](https://www.raycast.com/moored/git-repos) which allows customizing actions, but that's more to set your preferred text editor(s) as opposed to switching the order of two static options.

**Comment by djpowers** [comment]
@raycastbot assign me

**Comment by manishrc** [comment]
![CleanShot 2024-08-20 at 11  23 30@2x](https://github.com/user-attachments/assets/196881a6-40c2-4ca1-bacc-5365e387dbf3)

This is perfect! Thanks you very much @djpowers 🙏
