### ISSUE TITLE
[Coffee] ... "Caffeinate Until"

### ISSUE THREAD

**Issue by jsc0ded** [raycast/extensions#13705]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

Allow the user to `Caffeinate Until <timeofday>`. (having a default would be awesome too)

Actually, a configurable setting that is `Turn on at` and `Turn off at` would be sweet. And having that setting be day specific would be even amazinger. This would allow me to turn on right before I start work, turn off right after I end work on MTWTF. 🌮 

### Who will benefit from this feature?

Literally everyone.

**Comment by AditiB-930** [comment]
If nobody has taken this up I can give this a try 😄

**Comment by xilopaint** [comment]
@AditiB-930 Go ahead. I don't see any open PRs for this extension.
