### ISSUE TITLE
Search bookmarks hangs

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#13709]
### Extension

https://www.raycast.com/dru89/obsidian-bookmarks

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

It saves bookmarks fine but I can’t search them, Ive  made a video - https://www.dropbox.com/scl/fi/ph7gbpzci4b1ce54h6ays/Screen-Recording-2024-07-26-14-55-43.mp4?rlkey=igbn5iu0f7cub7lzwbrsvjitb&dl=0

### Steps To Reproduce

1. Save bookmark
2. Launch Search Bookmarks command.

### Current Behaviour

Infinite loading

### Expected Behaviour

Showing the bookmarks

**Comment by iwex** [comment]
here is fix
https://github.com/raycast/extensions/pull/13751
