### ISSUE TITLE
[Anybox] ... when using Anybox via Raycast to find and then open a bookmark, the Kagi Search Safari Extension opens rather than my default web browser

### ISSUE THREAD

**Issue by scottharris1014** [raycast/extensions#13700]
### Extension

https://www.raycast.com/anybox/anybox

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

As noted in the title, when I have the Kagi Search for Safari extension (https://apps.apple.com/us/app/kagi-for-safari/id1622835804) installed (whether or not enabled), using Anybox via Raycast to open a bookmark URL opens the Kagi Search for Safari extension (just a window with instructions on how to make the extension work) and not my default browser (whether that deafult is Safari, Chrome, or Orion). When I uninstall the Kagi extension, Anybox Raycast extension works as expected.

### Steps To Reproduce

Kagi Search for Safari extension installed 
Trigger Search Links command within Anybox extension in Raycast
Find a link 
Hit Enter to Open in Browser
Browser does not open, instead Kagi Search for Safari extension window opens.

**Comment by francisfeng** [comment]
@raycastbot close this issue
