### ISSUE TITLE
[Toggle Menu Bar] Has no effect on fullscreen apps

### ISSUE THREAD

**Issue by fseda** [raycast/extensions#13706]
### Extension

https://www.raycast.com/iamyeizi/toggle-menu-bar

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

The extension has no effect on full screen app windows. It just keeps the last state that I set manually in system settings, if I use the extension it doesn't change the state for full screen windows. On other windows it works.

### Steps To Reproduce

<img width="318" alt="Screenshot 2024-07-26 at 14 20 19" src="https://github.com/user-attachments/assets/373e7c66-4764-4e7b-8944-4a261f834713">
<img width="318" alt="Screenshot 2024-07-26 at 14 20 11" src="https://github.com/user-attachments/assets/403b3a8d-bfba-410b-ab58-7dff9a2e774d">

When i toggle the "always" or "in full screen only" option it has no effect on full screen app windows

**Comment by Berkayert** [comment]
I have the exact same issue. I hope this gets fixed soon :) Is someone looking at this?

**Comment by rea1shane** [comment]
related #11632, still not working

**Comment by iamyeizi** [comment]
https://github.com/raycast/extensions/issues/16308#issuecomment-2698388079
