### ISSUE TITLE
[YouTube Downloader] Crashes when attempting to download a live premiere

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#13710]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

1.79.1

### macOS Version

14.5 (23F79)

### Description

This is the error I got:

```
TypeError: Expected a finite number, got number: NaN

DV:index.tsx:20:41

---
17: import fs from "fs";
18: 
19: export default function DownloadVideo() {
20:   const [loading, setLoading] = useState(false);
21:   const [title, setTitle] = useState("");
22:   const [formats, setFormats] = useState<videoFormat[]>([]);
23:   const [error, setError] = useState(0);
---

_r:index.js:8:2593
    at ray-navigation-stack
Eo:index.js:8:2094
```

### Steps To Reproduce

1. Attempt to download a video that is a live premiere.
2. Extension crashes

### Current Behaviour

On the YouTube video:

![2024-07-26 (15 33 01) Arc](https://github.com/user-attachments/assets/608cbd92-b7fb-4b38-bede-c05643d9e3c9)

The extension after pasting the video URL:

![2024-07-26 (15 31 50) Arc](https://github.com/user-attachments/assets/812a4c20-161f-40e2-b5ac-d94e59db2aa0)

### Expected Behaviour

If the video is a live premiere, the extension should report an error that the video is not available, is a live premiere, and/or can be downloaded later.

**Comment by ridemountainpig** [comment]
@raycastbot assign me
