### ISSUE TITLE
[Extension Name] ...

### ISSUE THREAD

**Issue by tsq456** [raycast/extensions#13729]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Raycast Version

1.79.1

### macOS Version

mac OS 13.6.7

### Description

After I configured the Bitwarden API, when I used the function, the vault status was locked. After I entered the master password, it feedback: Failed to unlock vault Invallid master password, but I can log in to the Bitwarden app with this master password, so I don't know what happened. Can anyone help me? Thanks.

![image](https://github.com/user-attachments/assets/0c7b55cf-51c2-4d27-9793-3ce744076325)

### Steps To Reproduce

After I configured the Bitwarden API, when I used the function, the vault status was locked. After I entered the master password, it feedback: Failed to unlock vault Invallid master password

**Comment by jomifepe** [comment]
Hey, please read this comment: https://github.com/raycast/extensions/issues/13329#issuecomment-2238743439

**Comment by tsq456** [comment]
> Hey, please read this comment: [#13329 (comment)](https://github.com/raycast/extensions/issues/13329#issuecomment-2238743439)

thanks, this method solved my problem!
