### ISSUE TITLE
[Wi-Fi] Toggle wifi shows error if MenuBar wifi is not activated

### ISSUE THREAD

**Issue by CharbelFarah** [raycast/extensions#13736]
### Extension

https://www.raycast.com/koinzhang/wi-fi

### Raycast Version

1.79.1

### macOS Version

Sonoma 14.2.1

#### Error:
```
Error: Command "Menubar Wi-Fi" must be activated before it can be run in the background


```

### Steps To Reproduce

1. Do not Activate (or Deactivate) MenuBar Wifi in extension settings
2. Run command "Toggle Wi-Fi" from Raycast menu
3. Wait a little, Wi-Fi will be turned on/off but you will get this error in the Raycast menu
![image](https://github.com/user-attachments/assets/97c702cc-fed2-4d85-8f3c-bd0e7c458451)

### Current Behaviour

Toggle "Wi-Fi" throws an error related to Wi-Fi MenuBar being inActive

### Expected Behaviour

Even if Wi-Fi was turned on/off, it should not throw an error related to Wi-Fi MenuBar being inActive

**Comment by koinzhang** [comment]
Fixed in https://github.com/raycast/extensions/pull/13738
@raycastbot close this issue Closes the issue.
