### ISSUE TITLE
[ChatGPT Quick Actions] GPT-4o mini: advancing cost-efficient intelligence

### ISSUE THREAD

**Issue by JhonnyAxe** [raycast/extensions#13731]
### Extension

https://www.raycast.com/alanzchen/chatgpt-quick-actions

### Description

Hello, OpenAI has recently released a new cost-efficient model called [GPT4o Mini](https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/). Are you planning to incorporate this into the extension?

### Who will benefit from this feature?

Everyone

**Comment by husniadil** [comment]
I think it's already available:

<img width="309" alt="Screenshot 2024-08-13 at 10 17 26" src="https://github.com/user-attachments/assets/0842f5aa-ce8c-4ad0-8398-0f73b3e4d3ca">

You may close the ticket if it has already been resolved on your end.
