### ISSUE TITLE
[Messages] Unable to send message

### ISSUE THREAD

**Issue by boje-velux-ext** [raycast/extensions#13747]
### Extension

https://www.raycast.com/thomaslombart/messages

### Raycast Version

1.79.2

### macOS Version

Sonoma 14.5

#### Error:
```
Error: Command timed out after undefined milliseconds: osascript
Timed out

Timeout._onTimeout:exec-utils.js:32:33

---
29:     const timeoutPromise = new Promise((_resolve, reject) => {
30:         timeoutId = setTimeout(() => {
31:             spawned.kill("SIGTERM")

### Steps To Reproduce

Write text and click "send message"

### Current Behaviour

It wait 10 sec and show the classic Raycast error page

### Expected Behaviour

Send SMS

**Comment by thomaslombart** [comment]
Are you consistently experiencing the same issue each time? If so, are you also getting the same error message? Thanks!

**Comment by boje-velux-ext** [comment]
I just did a shutdown of the Mac and now it is working. Before I close raycast couple of time and tried to send a SMS multiple time with same error. 
Hence error is gone for now.
