### ISSUE TITLE
[Transfer.sh Uploader] remove this extension because of deprecation

### ISSUE THREAD

**Issue by 0PandaDEV** [raycast/extensions#13750]
### Extension

https://www.raycast.com/PandaDEV/transfer-sh_upload

### Raycast Version

1.79.1

### Description

Please remove this extension because its deprecated and does not work anymore. Im the owner of this extension.

### Steps To Reproduce

-

**Comment by iwex** [comment]
As I see - it's alive
https://github.com/dutchcoders/transfer.sh

**Comment by 0PandaDEV** [comment]
yes but their main instance is not http://transfer.sh/

**Comment by iwex** [comment]
But you have an option to set the instance URL in preferences

**Comment by 0PandaDEV** [comment]
yes i know but not everyone can self host their own instance so the extension is useles to the average person

**Comment by 0PandaDEV** [comment]
Please remove this extension! I don't want to maintain it anymore and the project behind it looks dead apart from self-hosted instances. Just use the new https://www.raycast.com/PandaDEV/streamshare-uploader
