### ISSUE TITLE
[Apple Reminder] Custom Address, unableToSaveReminder

### ISSUE THREAD

**Issue by Euro3000** [raycast/extensions#13757]
### Extension

https://github.com/raycast/extensions/blob/693fbf8913ddf62436813c40b55e5dced773ae42/extensions/apple-reminders/

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

It seems my formatting of the custom location is wrong or I am having some issues.
If I try to create a reminder with a set location it creates an error:
"Unable to create reminder unableToSaveReminder"

Formats tried:
Heinigstraße 51 Frankfurt
Heinigstraße 51 60325 Frankfurt
Heinigstraße 51, 60325 Frankfurt
60325 Frankfurt Heinigstraße 51
Frankfurt Heinigstraße 51

### Steps To Reproduce

Create a reminder with a custom location. Presaved or custom.

**Comment by iwex** [comment]
https://github.com/user-atachments/assets/a2d8f674-d48f-4d65-860a-55481fcf528b

@Euro3000 I don't have this problem

**Comment by Euro3000** [comment]
> In94dZxg.mp4 
> @Euro3000 I don't have this problem

Hmmm ... idk what's wrong

https://github.com/user-attachments/assets/8be9b729-d7fd-4b85-962c-07e07d4c6f1c

**Comment by iwex** [comment]
@Euro3000 try to reinstall extension

**Comment by Euro3000** [comment]
> @Euro3000 try to reinstall extension

I did. Still the same issue :(

**Comment by iwex** [comment]
@thomaslombart @irangarcia @tmwrnr @jondelga

@pernielsentikaer please add correct tags

**Comment by thomaslombart** [comment]
I can't reproduce this problem as well. Are you at least able to create a reminder with just a title? Also, does Raycast have permissions to access your reminders?
