### ISSUE TITLE
[Notion] Focus on Name input instead of Database for faster workflow

### ISSUE THREAD

**Issue by baptisteArno** [raycast/extensions#13752]
### Extension

https://www.raycast.com/notion/notion

### Description

Would be nice to tell the extension to focus on the first text input to have a faster workflow.

**Comment by bkeys818** [comment]
For the Create Database Page command?

**Comment by baptisteArno** [comment]
> For the `Create Database Page` command?

Yes!

I have a "Inbox" database where I insert whatever goes through my mind. So I open up raycast Create Database Page and my goal is to go as fast as possible. But here I always need to hit "Tab" before writing down the page Name.

**Comment by bkeys818** [comment]
Try creating a QuickLink for creating a page on your "Inbox" database.

**Comment by bkeys818** [comment]
There's an action for it.
<img width="862" alt="Screenshot 2024-08-20 at 2 51 14 PM" src="https://github.com/user-attachments/assets/437c8e58-9328-47bf-8466-f593f9667653">
