### ISSUE TITLE
[Safari] Can't find bookmarks in specific folder

### ISSUE THREAD

**Issue by ksandvik** [raycast/extensions#13754]
### Extension

https://www.raycast.com/loris/safari

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

Safari bookmarks command no longer finds (accurately) all bookmarks in specific folder

### Steps To Reproduce

In my case I have a work folder with all the work related bookmarks, still available from the Safari bookmark folder.

Doing a Safari search bookmark does no longer return results from this folder.

### Current Behaviour

Missing entries that have been used during the week.

### Expected Behaviour

All entries from the folder should be found.

**Comment by ksandvik** [comment]
Is there a way to reindex in case there's a cache or something in the plugin (or possibly Safari) if this is used for the actual search?

**Comment by ksandvik** [comment]
BTW this is Safari Version 17.5 (19618.2.12.11.6).

**Comment by iwex** [comment]
Only from one folder?

**Comment by iwex** [comment]
@raycastbot reopen this issue

**Comment by ksandvik** [comment]
Export bookmarks from Safari via the export to HTML shows the bookmark links.

**Comment by ksandvik** [comment]
Looks like only one folder. Also the one I use the most.

**Comment by ksandvik** [comment]
Also, looking at the results from a search such as 'monitoring' no such word is in the bookmark result entries which is strange.

**Comment by ksandvik** [comment]
I suspect something got corrupt in case you have a trie or something, restarting Raycast didn't help.

**Comment by iwex** [comment]
@ksandvik please share more details - location of the dir, it's name, some bookmarks from that dir

**Comment by iwex** [comment]
![tEK9Vpos](https://github.com/user-attachments/assets/1e987d2b-a9d3-4e98-a398-63a6e0abae39)

**Comment by ksandvik** [comment]
It's a work dir with stuff inside VPN so I can't share that. As far as I know the directories for bookmarks are plist generated, not real directories. The dir name as no above ASCII-8 characters.

**Comment by ksandvik** [comment]
Remove/add back the plugin didn't work. See screenshot showing the oddity when looking for a bookmark with the string 'monitoring' in the bookmark name.

**Comment by ksandvik** [comment]
![monitoring-string](https://github.com/user-attachments/assets/f34b6ed0-fa2f-4f0b-91b8-91ea3704efaf)

**Comment by ksandvik** [comment]
Actually none of the hits from this bookmark search has the substring 'monitoring'

**Comment by ksandvik** [comment]
FYI Search Browser bookmarks plugin works with this search so I will switch to that for the time being.

**Comment by ksandvik** [comment]
![Safari-bookmark-search](https://github.com/user-attachments/assets/d5da54f9-ecc5-4cd8-b2bd-5ac9a1c4c268)
Here's an example from Safari what the expected search results from bookmarks should look like, 'monitoring' is found and no other entries are shown in the results. This is an issue with both the Raycast Search Bookmarks and gen across-browsers 'Search bookmarks'  commands.

**Comment by iwex** [comment]
I can change threshold for fuzzy search, make it as in Browser Bookmarks

**Comment by ksandvik** [comment]
Yes please, and make min fuzzy mode to be no fuzzy mode at all.

**Comment by iwex** [comment]
https://github.com/raycast/extensions/issues/13621 :)
Fuzzy is better most of the time, you can make a typo, but still will find your bookmark

**Comment by ksandvik** [comment]
Just now I don't get anything with either plugin compared with Safari Browser bookmark search and Spotlight that return the one and only bookmarks with the sub-string 'monitor' so I think the goal would be same with these two commands.

**Comment by niksite** [comment]
Same here. Recently, the bookmarks search has become unusable, returning totally irrelevant results at the top of the list. It seems to be trying to group results by the subfolder where it found the bookmarks, instead of sorting without grouping.

So, my first question is: Can we disable bookmarks grouping by folder when searching "All Bookmarks"?

My second question is: What's with the "Alcoholic Beverages" here?

<img width="288" alt="image" src="https://github.com/user-attachments/assets/10c1e9d1-582c-44a0-8753-0518a10d3d73">
