### ISSUE TITLE
[Bitwarden] Unable to log in using the master password

### ISSUE THREAD

**Issue by youvegotmoxie** [raycast/extensions#13767]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

Unable to log in using the master password and receiving an error stating "Invalid master password." This was working fine until I tried syncing the vault through the extension, which failed, and now I get that invalid password every time trying to unlock the vault

The same password works with both the web client and desktop app so this is clearly an issue on the Raycast side.

### Steps To Reproduce

1. Attempt to log into the Bitwarden vault with the Raycast extension
2. Watch it fail with an invalid password error

**Comment by jomifepe** [comment]
Hey, https://github.com/raycast/extensions/issues/13329#issuecomment-2238743439

**Comment by youvegotmoxie** [comment]
Thanks for the quick reply. That was indeed the issue
