### ISSUE TITLE
[Lark Documents]  Can not browse to document

### ISSUE THREAD

**Issue by Asura19** [raycast/extensions#1376]
# Extension – [Lark Documents](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/lark/)
Author: @tmk

## Description
Can not navigate to the doc

## Steps To Reproduce

1. Seach with query words, and the result appears
2. press enter for opening the document

## The current behavior
Raycast window disappeared, then noting happened.

## The expected behavior
Raycast window disappeared, browser opened the selected document.

### Raycast version

1.32.1

### Note
document's that its url has `wiki` word all failed, but which has `docs` or `docx` all succeeded.
https://bytedance.feishu.cn/wiki/wikcn*******

https://bytedance.feishu.cn/docs/doccn*******
https://bytedance.feishu.cn/docx/doxcn*******

My ByteDance email: yuyue.self@bytedance.com

**Comment by tmkx** [comment]
I've tested and it works, could you please provide an approach to reproduce this bug?

BTW, I did not receive the notification because my username is tmkx

**Comment by Asura19** [comment]
> 

@tmkx Sorry about the name, I found the bug has been fixed at recently version. Thank you for your replying.
