### ISSUE TITLE
Action for searching and opening pinned shelves

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#13776]
### Extension

https://www.raycast.com/jag-k/dropover

### Description

Please consider adding an action for searching and opening pinned shelves.

### Anything else?

Not sure if it's helpful but here is an example, "Search Bunches" action in this extension - https://www.raycast.com/koinzhang/bunch

**Comment by jag-k** [comment]
Thank you very much for the feature request!

Currently (as far as I know) such functionality is not available in Dropover itself, but I contacted the author (@tursunovic) of the application by email.

If @tursunovic says that this is possible, then I will definitely implement this functionality!

@raycastbot assign me
@raycastbot keep this issue open
