### ISSUE TITLE
[Markdown to Rich Text] preserve existing rich text in a selection of text that is transformed into rich text

### ISSUE THREAD

**Issue by DannyMatteson-at** [raycast/extensions#13778]
### Extension

https://www.raycast.com/ning_cao_cabeza/markdown-to-rich-text

### Description

When text is copied that is a mix of rich text and markdown, for example:

- bullet one
- bullet two1
hyperlink

pretend that hyperlink is actually a link. The bullets will be transformed to rich text bullets but the link formatting will be lost.

### Who will benefit from this feature?

anyone using a mix of rich text and markdown but who also needs the markdown to be converted.

**Comment by vegetablesB** [comment]
> ### Extension
> https://www.raycast.com/ning_cao_cabeza/markdown-to-rich-text
> 
> ### Description
> When text is copied that is a mix of rich text and markdown, for example:
> 
> * bullet one
> * bullet two1
>   hyperlink
> 
> pretend that hyperlink is actually a link. The bullets will be transformed to rich text bullets but the link formatting will be lost.
> 
> ### Who will benefit from this feature?
> anyone using a mix of rich text and markdown but who also needs the markdown to be converted.
> 
> ### Anything else?
> _No response_

I didn't find the error, here is the video. Please correct me if I was wrong.

https://github.com/user-attachments/assets/d56b6d04-b0bd-4572-8fbc-ac185d64abc3

**Comment by vegetablesB** [comment]
Hi @DannyMatteson-at , I have trouble to read rich text from clipboard using import { showHUD, Clipboard } from "@raycast/api";

```ts
const clipboardContent = await Clipboard.read();
console.log(clipboardContent);
const markdownText = clipboardContent.text;
const htmlContent = clipboardContent.html;
```

<img width="353" alt="image" src="https://github.com/user-attachments/assets/a5785511-4906-4cd5-87c3-767e320ff53a">

The output:
```text
  text: '[raycast](https://www.raycast.com/)\n' +
    '- first bullet\n' +
    '- second [raycast](https://www.raycast.com/)\n' +
    'Raycast\n' +
    '<p>hello<p>\n'
}
```
Output of Hyperlink is plain text, I am not able to tell if it is rich or not.

I am thinking read from clipboard and try to seperate the text based on plain text and rich text in document or html. But I can only get the plain text. Any thoughts?

**Comment by DannyMatteson-at** [comment]
Thank you very much for the reply @vegetablesB — I looked at the extension code and chatted this out with ChatGPT a little. It seems like if `Clipboard.read()` function isn't giving the required rich text directly, we might need to work with both HTML and plain text separately like you suggested.

Can we convert the Markdown to rich text and then merge it with the existing rich text (like the Raycast hyperlink in your screensot) to preserve the formatting?

I haven't tested the following yet but maybe I can fork and submit a PR:

```diff
import { richTextFromMarkdown } from "@contentful/rich-text-from-markdown";
import { documentToHtmlString } from "@contentful/rich-text-html-renderer";
import { documentToPlainTextString } from "@contentful/rich-text-plain-text-renderer";
import { showHUD, Clipboard } from "@raycast/api";

export default async function main() {
  try {
-    const markdownText = await Clipboard.readText();
+    // Read clipboard content
+    const clipboardContent = await Clipboard.read();
+    const markdownText = clipboardContent.text;
+    const existingHtmlContent = clipboardContent.html;

    const document = await richTextFromMarkdown(markdownText ?? "");
    const renderedHtml = documentToHtmlString(document);

+    // Merge existing HTML content with the new rich text
+    const combinedHtml = mergeHtml(existingHtmlContent, renderedHtml);

    const plainText = documentToPlainTextString(document);
-    const html = await renderedHtml;

-    await Clipboard.copy({
-      html: html,
+    // Copy combined rich text and plain text to clipboard
+    await Clipboard.copy({
+      html: combinedHtml,
       text: plainText,
     });
-    await Clipboard.paste({
-      html: html,
+    await Clipboard.paste({
+      html: combinedHtml,
       text: plainText,
     });
     await showHUD("Markdown converted and copied to clipboard! Also pasted.");
   } catch (error) {
     await showHUD("Failed to convert text");
   }
}

+// Helper function to merge existing HTML with new HTML
+function mergeHtml(existingHtml, newHtml) {
+  // Implement logic to intelligently merge existing HTML with new HTML
+  // For simplicity, here we concatenate the HTML strings
+  return (existingHtml || '') + newHtml;
+}
```

This seems like the tricky part:
```diff
+  // Implement logic to intelligently merge existing HTML with new HTML
+  // For simplicity, here we concatenate the HTML strings
```

**Comment by vegetablesB** [comment]
Hi @DannyMatteson-at , thank you for your reply. I have tried this const existingHtmlContent = clipboardContent.html;

This one is empty.

**Comment by yazanzaid00** [comment]
How about using Apple's Shortcuts app to accomplish this?

[Check out this shortcut](https://www.icloud.com/shortcuts/07079486be994db7b4c099036c3e5ed4).
