### ISSUE TITLE
[1Password] Undefined signature

### ISSUE THREAD

**Issue by jeremy-beasley** [raycast/extensions#13782]
### Extension

https://www.raycast.com/khasbilegt/1password

### Raycast Version

1.79.1

### macOS Version

14.5 (23F79)

### Description

- Trying to setup 1pw extension. 
- Selected 1pw8
- Couldn't make it past the auth screen. See the screenshot

<img width="862" alt="Screenshot 2024-07-30 at 21 59 55" src="https://github.com/user-attachments/assets/a983708f-6d22-4841-985a-5a5b4750959f">

I see an error message that says `Command failed: undefined sig`

### Steps To Reproduce

1. Selected 1pw8
2. Couldn't make it past the auth screen. See the screenshot

**Comment by LitoMore** [comment]
Fixed in #13852. @raycastbot close this issue.
