### ISSUE TITLE
[Reclaim] Crash

### ISSUE THREAD

**Issue by alexiej** [raycast/extensions#13785]
### Extension

https://www.raycast.com/reclaim-ai/reclaim-ai

### Raycast Version

1.79.1

### macOS Version

14.3

#### Error:
```
TypeError: Cannot set properties of undefined (setting 'stack')

Nr.componentDidCatch:index.js:7:2529
Ri.u.componentDidCatch.t.callback:react-reconciler.production.min.js:7:769
li:react-reconciler.production.min.js:5:17397
no:react-reconciler.production.min.js:7:27654
```

### Steps To Reproduce

Try open reclam ai

### Current Behaviour

Crash

### Expected Behaviour

not. crash

**Comment by ajohnson1200** [comment]
This is fixed.
