### ISSUE TITLE
[Reclaim] Menu Bar isn't working.

### ISSUE THREAD

**Issue by jesminewhee** [raycast/extensions#13790]
### Extension

https://www.raycast.com/reclaim-ai/reclaim-ai

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

The menu bar is not working even after re-enabling extensions and APIs. Tasks are also not starting and not showing stop / restart button - not sure if it's a bug or my own issue.
![image](https://github.com/user-attachments/assets/9d712810-932c-4587-b388-4fa05dee36e7)

Log of Error:

TypeError: Cannot set properties of undefined (setting 'stack')

Nr.componentDidCatch:index.js:7:2529
Ri.u.componentDidCatch.t.callback:react-reconciler.production.min.js:7:769
li:react-reconciler.production.min.js:5:17397
no:react-reconciler.production.min.js:7:27654

### Steps To Reproduce

1. Open 'Calendar Menu Bar' in Raycast.
2. 'Refresh Menu Bar Item'.

**Comment by pernielsentikaer** [comment]
Could this be related to the latest update @ajohnson1200

**Comment by pernielsentikaer** [comment]
CC @clayton-knapp

**Comment by derAndi** [comment]
I get the same error. I updated raycast to 1.80 and reloaded the extension but still the same error. MacOS is also 14.5.

Thanks for the extension by the way.

**Comment by clayton-knapp** [comment]
Revert PR ready to be approved and merged here:
https://github.com/raycast/extensions/pull/13799

**Comment by derAndi** [comment]
It works for me again. Thank you.

**Comment by pernielsentikaer** [comment]
It might just be a small thing that caused it 🙂

**Comment by ajohnson1200** [comment]
This is fixed now.

**Comment by pernielsentikaer** [comment]
Are you going to make a new PR or is it fixed in the backend so we can get the latest PR in again @ajohnson1200

**Comment by clayton-knapp** [comment]
@pernielsentikaer 
The broken menu bar has been fixed by the revert PR that was already merged. We have a new PR we will be opening soon with the new features.
