### ISSUE TITLE
[Notion] Can't add page to database

### ISSUE THREAD

**Issue by wyrwigruz** [raycast/extensions#13793]
### Extension

https://www.raycast.com/notion/notion

### Raycast Version

1.80.0

### macOS Version

14.5

### Description

From yesterday, Notion extension is not working. I can't add a page to the selected database. It seems that there is a bug with reading the name input.
![image](https://github.com/user-attachments/assets/879f2335-6dda-4f0f-8c89-623172a4d128)

### Steps To Reproduce

1. Try to add any page to any database

### Current Behaviour

Validation error is displayed next to the name input that the item is required.

### Expected Behaviour

I can add new page as usual.

**Comment by thomaslombart** [comment]
Could you share a recording? It'll make it easier to see what's happening.

**Comment by wyrwigruz** [comment]
https://github.com/user-attachments/assets/4806b016-e431-4408-bd7a-fec20daf1455

I created a fork an rollback changes from last commit and it works.
https://github.com/raycast/extensions/pull/13579 - this pull request contains breaking changes.

**Comment by atanych** [comment]
I have similar issues, it requires some item

![CleanShot 2024-07-31 at 20 50 07@2x](https://github.com/user-attachments/assets/17102fff-127a-43d0-89ed-44c416848154)

**Comment by RumTumTum** [comment]
Also have the same issue. It is not limited to any one database. This occurs for all of ~10 databases that I tested. In each case, I get the "The item is required" error on the first attribute (e.g., Name) even when data is populated.

This aligns with what has been shared above.
