### ISSUE TITLE
[Notion] ...

### ISSUE THREAD

**Issue by jlgzz** [raycast/extensions#13805]
### Extension

https://www.raycast.com/notion/notion

### Raycast Version

1.80.0

### macOS Version

14.5

### Description

When try to create a new entry for a database using the command, cant make the entry because it says "the item is required" even if the name is filled

### Steps To Reproduce

cmnd + space
create database page 
fill all the properties
cmnd + enter

**Comment by erics118** [comment]
See #13793

**Comment by erics118** [comment]
@raycastbot close this issue
