### ISSUE TITLE
[Reclaim] Calendar Menu Bar Extension error

### ISSUE THREAD

**Issue by beardly-beem** [raycast/extensions#13802]
### Extension

https://www.raycast.com/reclaim-ai/reclaim-ai

### Raycast Version

v1.69.0

### macOS Version

14.5

### Description

Reason: Code: 1 (Uncaught Extension Exception)
Domain: commands
Time: 18:34:36.078

### Steps To Reproduce

1. Open Raycast
2. Attempt to open Reclaim Calendar Menu Bar extension
3. Examine error
![raycast_error](https://github.com/user-attachments/assets/19dbec16-3dfb-4cae-b803-e5b192b01a0d)

### Current Behaviour

Calendar menu bar shows an error

### Expected Behaviour

Calendar menu bar shows time to next upcoming meeting.

**Comment by ajohnson1200** [comment]
yep, known issue, we're looking to revert a change made yesterday and waiting for Raycast folks to approve, thanks for filing!

**Comment by ajohnson1200** [comment]
This is fixed.

**Comment by beardly-beem** [comment]
> This is fixed.

Confirmed! Tysm
