### ISSUE TITLE
[YouTube Downloader] ... video not being found

### ISSUE THREAD

**Issue by dimitriacosta** [raycast/extensions#13807]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

1.80.0

### macOS Version

14.5

### Description

I am getting a "no video found" message every time i try to download a video from a fresh installation of the youtube downloader extension, I made sure both ffmpeg and ffprobe were properly installed but the issue persists
<img width="862" alt="Screenshot 2024-07-31 at 5 10 18 p m" src="https://github.com/user-attachments/assets/aeb543c5-6741-4397-9395-5377045dcb26">

### Steps To Reproduce

1. Open YouTube
2. Select any video
3. Click on the share button
4. Copy the URL
5. Open Raycast and select the download video extension
6. Paste the URL

**Comment by adomakins** [comment]
I'm using ytdl-core which is what this extension uses https://github.com/raycast/extensions/blob/98c102bdd8ac322b19f703bb9a759223cef2d288/extensions/youtube-downloader/src/utils.ts

But I'm running it on a Google Cloud Function and getting the same problem.

There may have been a breaking change on YouTube's site.

**Comment by adomakins** [comment]
By the way @dimitriacosta, I've used this extension on my computer and it worked like a charm so it's probably not your setup

**Comment by jkcharlie6679** [comment]
I have the same problem with the same version of macOS and Raycast.

**Comment by ridemountainpig** [comment]
@raycastbot assign me
