### ISSUE TITLE
Add Database Page Bug [Notion] ...

### ISSUE THREAD

**Issue by 4all101** [raycast/extensions#13810]
### Extension

https://www.raycast.com/notion/notion

### Raycast Version

v1.80.0

### macOS Version

14.5

### Description

the extension was working great with my notion to allow me to quickly add to my database in notion. but out of no where regardless of what i type in for the "name" of the entry, it gives me an error for "this item is required" even though its filled out. have tried everything but cant seem to make it work. tried uninstalling and reinstalling the extension and disconnecting the notion account. also redownload the raycast app itself. the other commands seem to work fine. any tips?
![Screenshot 2024-07-30 at 4 32 15 PM](https://github.com/user-attachments/assets/e8731953-4d2c-45cc-9a2f-678f87aef1e3)

### Steps To Reproduce

1. open raycast 2. initiate notion "add database page" command 3. select database and fill in entry 4. error occure saying "name" field is required

### Current Behaviour

error is remaining regardless of trouble shooting, not allowing me to submit my entry even though name field has text

### Expected Behaviour

command would read the text in the name field and create the database page entry

**Comment by erics118** [comment]
See #13793

@raycastbot close this issue
