### ISSUE TITLE
[Toggl Track] Toggle seconds in menubar

### ISSUE THREAD

**Issue by kikujiro-mms** [raycast/extensions#13816]
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Description

Option not to display seconds in Toggl Track menubar.

(Also, if possible: option to omit pipe symbol between data items; option not to use colour for icon / omit icon entirely.)

### Who will benefit from this feature?

People who find seconds unnecessary/distracting.
People who are bothered by the timer showing seconds but only updating every c10 seconds :)

### Anything else?

Thank you very much indeed for this extension, which has made a huge improvement to my workflow.

**Comment by lukebars** [comment]
Hi! Do you mean hiding seconds in the menubar extended state? The timer in Menubar is optional, you can toggle it in settings. 
<img width="766" alt="image" src="https://github.com/user-attachments/assets/66bc418d-b212-4426-9220-fc503e0573a9">
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/3c80af3f-a560-484a-b51e-070931b86d0f">

**Comment by kikujiro-mms** [comment]
Hi – thanks so much for the incredibly swift response.

I mean the menubar in the extended state. I'd love to see the time of the running timer, but seconds feels like overkill/distracting and weird as they don't update every second anyway :)

I realise this is nitpicky for the product of someone's generous free labour, but it's such a fantastic extension that I can't help myself.

**Comment by bkeys818** [comment]
@lukebars

It'd probably be best to hide the seconds by default.

**Comment by lukebars** [comment]
I agree @bkeys818. I'll try to raise a PR for that.
