### ISSUE TITLE
[LastPass Credentials Search] "stdout maxBuffer length exceeded" at +9500 entries

### ISSUE THREAD

**Issue by mcinicola** [raycast/extensions#13813]
### Extension

https://www.raycast.com/alex-popov-tech/lastpass

### Raycast Version

1.80.0

### macOS Version

Sonoma 14.5

### Description

We experience issues when we have +9500 entries in last pass. The extension gives the following error: stdout maxBuffer length exceeded

We tried removing access to some entries, which made it work.
We also tried adding entries for a different mac, which made it fail.

### Steps To Reproduce

Have access to +9500 entries
Watch as the extension gives an error.

### Current Behaviour

"stdout maxBuffer length exceeded" at +9500 entries

### Expected Behaviour

Expected to be able to search through all 9500 entries

**Comment by alex-popov-tech** [comment]
default buff size is 1024*1024 bytes i will increase it to 2048*2048, we will see if that would be enough

**Comment by alex-popov-tech** [comment]
pr created -> https://github.com/raycast/extensions/pull/13817

**Comment by alex-popov-tech** [comment]
@mcinicola please check, should be deployed now

**Comment by mcinicola** [comment]
@alex-popov-tech it works! 

Thank you very much :)

**Comment by alex-popov-tech** [comment]
@raycastbot close this issue
