### ISSUE TITLE
[Brand Icons] How to copy SVG to clipboard

### ISSUE THREAD

**Issue by pascalwhoop** [raycast/extensions#13825]
### Extension

https://www.raycast.com/litomore/simple-icons

### Description

simply copy the icon to clipboard feature

**Comment by LitoMore** [comment]
@pascalwhoop The feature is already in the action list. You can also change the default behavior from extension configuration.

**Comment by LitoMore** [comment]
@raycastbot rename this issue to "How to copy SVG to clipboard"

**Comment by LitoMore** [comment]
@raycastbot rename this issue to "[Brand Icons] How to copy SVG to clipboard"

**Comment by LitoMore** [comment]
@raycastbot close this issue

**Comment by pascalwhoop** [comment]
@LitoMore the copied SVG is a black only image though, not having the color icon that is displayed in the UI

**Comment by LitoMore** [comment]
@pascalwhoop We intently returned a pure SVG to users. The brand color value is just a reference color. The color of the logo is determined by the scene it sits in and the official guiding color scheme.

Also, for the SVG, you have multiple ways to specify the icon color, like:

1. SVG `fill` attribute
2. SVG `style` attribute
3. CSS styles
4. CSS masks
5. CSS filters
6. ...

We should let users decide which solution to use, rather than specifying it ourselves.

**Comment by pascalwhoop** [comment]
Okay so maybe I should articulate where I come from.
Thousands of people around the world are building architectural diagrams
and PowerPoint slides about companies and all sorts of stuff. Those
professionals often have to collect various brand logos. Those logos should
be “close to original but transparent background and svg or png”. Your
service is the closest to “instant lookup of logos” I could find. The only
thing that it’s missing is the one click copy of the svg in the color of
the brand as it is displayed by the raycast extension in the preview.
So the desired feature is that we can copy it exactly as it is previewed,
not in black.
Is that really not a possibility? You’re already previewing it in the
reference colour.

-- 

The contents of this email are confidential and intended only for the 
intended recipient. If you are not the intended recipient or responsible 
for delivery of the message to such person, you may not use, copy, 
distribute or deliver this message or any part of its contents to anyone, 
or take any action in reliance on it. If you have received this email in 
error, please immediately notify the sender and then permanently delete 
this message. The views, opinions, conclusions and other information 
provided herein are not intended to be and should not be interpreted as 
medical advice. Please consult your physician for all medical advice.

**Comment by LitoMore** [comment]
@pascalwhoop Good point. I think I can add a preference option to for copying the icon with color by default.

**Comment by pascalwhoop** [comment]
That would be appreciated!

-- 

The contents of this email are confidential and intended only for the 
intended recipient. If you are not the intended recipient or responsible 
for delivery of the message to such person, you may not use, copy, 
distribute or deliver this message or any part of its contents to anyone, 
or take any action in reliance on it. If you have received this email in 
error, please immediately notify the sender and then permanently delete 
this message. The views, opinions, conclusions and other information 
provided herein are not intended to be and should not be interpreted as 
medical advice. Please consult your physician for all medical advice.

**Comment by LitoMore** [comment]
I've created a PR to implement this feature:

- #13866
