### ISSUE TITLE
Support for Edge Beta, Dev, or Canary Builds

### ISSUE THREAD

**Issue by ahpatel** [raycast/extensions#1383]
# Extension – [Microsoft-Edge](https://github.com/raycast/extensions/tree/main/extensions/microsoft-edge)

Author: @mathieudutour 

Would you consider adding a install check against the Microsoft Edge [beta, dev or canary channels](https://www.microsoftedgeinsider.com/en-us/download/)?

When attempting to use this extension with the Microsoft [Edge Canary build](https://www.microsoftedgeinsider.com/en-us/download/canary) (which I run), I get the following error:

     > 🚨Error: Microsoft Edge browser is not installed

**Comment by rbreaves** [comment]
Would like to see this re-opened. A small thing, but many devs do use multiple versions of a given browser.

**Comment by KartikKumarSahoo** [comment]
Thanks @ahpatel for asking for this feature. This PR https://github.com/raycast/extensions/pull/7526 adds the capability to use any build of your choice.
