### ISSUE TITLE
[LastPass Credentials Search] Prioritize Favorites in Search results

### ISSUE THREAD

**Issue by mcinicola** [raycast/extensions#13838]
### Extension

https://www.raycast.com/alex-popov-tech/lastpass

### Description

Hi again

It would be nice, if Personal folders would have priority over shared folders if searching for the same - or at least favorites would be shown first. An option to decide what it should sort after would of course be the most user-friendly.

### Who will benefit from this feature?

Everyone - if implemented, it gives a bit more control over search results.

**Comment by mcinicola** [comment]
Currently it seems to favour what is in notes

**Comment by mcinicola** [comment]
I see it is alphabetical, so i

**Comment by mcinicola** [comment]
I see it is alphabetical - so i can manually change my personal passwords to get them at the top of search results.
Not pretty and a feature to toggle "Personal first" or "Favorites first" would of course be nice.

**Comment by alex-popov-tech** [comment]
hey,

can you provide example outputs for different folders and favorites? like example output from `lpass export` would be nice

**Comment by mcinicola** [comment]
```
➜ lpass export | grep "testentry"
http://,,,,testentryA-NotPersonal,Shared-Folder,1
http://,,,,testentryB-Personal,Personal,1
```

"testentryA-NotPersonal" is an entry in a Shared-Folder (Favorite is not set)
"testentryB-Personal" is an entry in my own Personal folder with Favorite set.

In my opinion, favorites should be shown first - as they would be the most used entries probably.
So something like this (ChatGPT made it for me 😆 )
```
lpass export | grep "testentry" | awk 'BEGIN { FS=OFS="," } { if ($1 ~ /favorite/) print $0; else non_fav[NR]=$0 } END { for (i in non_fav) print non_fav[i] }'

http://,,,,testentryB-Personal,Personal,1
http://,,,,testentryA-NotPersonal,Shared-Folder,0

```

**Comment by alex-popov-tech** [comment]
lgtm, i will try to do it in nearest days

**Comment by alex-popov-tech** [comment]
hey @mcinicola, getting back to your point, I just created lastpass account , and two entities, one with mentioning folder name, one without. And I can't see 'Personal' one, is it default one, or custom one?

```csv
url,username,password,extra,name,grouping,fav
http://nstr,nstr,nstr,,nstr,,0
http://someurl,username,password,note,somename,foldername,0
```

**Comment by mcinicola** [comment]
The personal one is custom.

The best thing would to have favorites listed first.
It appears difficult to remove from a folder, once it's already in one.

**Comment by alex-popov-tech** [comment]
okay, `fav` can be done. mind changing issue title / description then?

**Comment by alex-popov-tech** [comment]
@mcinicola after some additional research i've found that 'export' command that supports returning `fav` value do not support `format` arg, which means i cannot put there custom separator ( i believe `,` could be in some of the fields, like `url` ).

So TLDR - there are two commands, one supports `fav` but do not support formatting to avoid collisions, and second one support formatting but do not support `fav`

**Comment by mcinicola** [comment]
Ahh i see.. 

Then it might be an option to see a specific folder first.
I know everyone might not call whatever they want to see first "Personal" as i have.

Could that be a viable thing to do?

In the settings, having an option to write a name of a folder you want to have listed first in search results.

**Comment by alex-popov-tech** [comment]
That is possible, altho I'm not sure it will be easy to understand from settings screen, and idea itself is pretty bold ( sorting is such a big topic, like what if i want to toggle search ASC/DESC back and forth, sort items within folders first, sort by `name`, apply multiple sorts one on top of another ), and having just input field where you need to put specific single folder name looks kinda unfinished feature 🤔 

Does it cause too many problems to type few chars included in `name` or whatever it filters on and sort things this way more precise, rather than sorting them by folder?

**Comment by alex-popov-tech** [comment]
Okay, I won't have capacity on that feature soon, but you are most welcome to make this PR

As per update in Lastpass CLI - you can look how they respond to issues and their changelog - I would not hope they will do anything useful any time soon 🤷🏻‍♂️

**Comment by alex-popov-tech** [comment]
@raycastbot good first issue
