### ISSUE TITLE
[Safari] fails to run

### ISSUE THREAD

**Issue by nikitavoloboev** [raycast/extensions#13833]
### Extension

https://www.raycast.com/loris/safari

### Raycast Version

1.79.1

### macOS Version

15.0

#### Error:
```
Error: maxObjectCount exceeded

He.parseBuffer:bplistParser.js:92:10

---
89:   }
90: 
91:   if (numObjects > exports.maxObjectCount) {
92:     throw new Error("maxObjectCount exceeded")

### Steps To Reproduce

1. try run extension, break

**Comment by iwex** [comment]
@nikitavoloboev I see that you know JS, could you please debug by yourself
Problem is somewhere here https://github.com/joeferner/node-bplist-parser/blob/a76affe9caec05a3a47c5e02494de661b7204816/bplistParser.js#L90

**Comment by nikitavoloboev** [comment]
how can I add debug statements to this code, i.e. run this extension locally

I am new to raycast extension dev

**Comment by iwex** [comment]
It's easy as 1,2,3 :)

![HROdYItz](https://github.com/user-attachments/assets/fe11613d-6a79-442e-b8fe-e2d5f3b20468)
Choose dir and proceed.

1) Run `npm install` and `npm run dev`
2) Open extension with your code editor and feel free to change everything you want.

**Comment by nikitavoloboev** [comment]
Thank you.

After debugging, issue was that my `~/Library/Safari/Bookmarks.plist` was too large so it was breaking. I deleted some bookmarks and it worked again.
