### ISSUE TITLE
[Notion] Pass Default Values to Quick Capture command via LaunchContext

### ISSUE THREAD

**Issue by zsidnam** [raycast/extensions#13830]
### Extension

https://www.raycast.com/notion/notion

### Description

I would like to pass default values for `captureAs` and `notionPage` to the "Quick Capture" command via LaunchContext when creating a QuickLink. Similar functionality has been added to the "Create Database Page" command, but it does not look like this is supported in "Quick Capture".

### Who will benefit from this feature?

Anyone who frequently uses Quick Capture to save content to the same Page/Database in Notion and likes to automate Raycast workflows with QuickLinks. Capturing is supposed to be as frictionless as possible, so this functionality would save users one or two steps each time that use the command! 🙏

**Comment by zsidnam** [comment]
I'm happy to work on this if that would be helpful!

**Comment by thomaslombart** [comment]
Thanks for the PR! Here's our guide about contributing to extensions: [Contribute to an extension](https://developers.raycast.com/basics/contribute-to-an-extension)
