### ISSUE TITLE
[Base64] Inconsistent Encoding

### ISSUE THREAD

**Issue by martbock** [raycast/extensions#13842]
### Extension

https://www.raycast.com/DanielSinclair/base64

### Raycast Version

1.80.0

### macOS Version

14.6

### Description

This is a rather strange issue, but the Base64 extension seems to encode content inconsistently. I'll explain using an example:

When I have the base64-encoded value `YQpi`, no matter how I decode it (Raycast extension or shell command), I get `a\nb`. When using the bash `base64` command to re-encode, I get the initial value `YQpi`.

```sh
echo -n "a\nb" | base64
```

When I copy the same original content to my clipboard (`echo -n "a\nb" | pbcopy`) and use the extension's "Base64 Encode" command, I get the encoded value `YQ1i`, which differs from the original encoded value.

I tested the underlying `js-base64` library, but that does not seem to be the issue here:

```js
import { decode, encode } from "js-base64";

let decoded = decode("YQpi")
let encoded = encode(decoded)

console.log({decoded})
console.log({encoded})
```

```sh
$ node main.js       
{ decoded: 'a\nb' }
{ encoded: 'YQpi' }
```

I guess something is off here, but unfortunately I didn't have enough time to pinpoint the issue any further.

### Steps To Reproduce

1. Copy `YQpi` to clipboard
2. Run _Base64 Decode_
3. Run _Base64 Encode_
4. Look at the result

### Current Behaviour

The encoding command returns `YQ1i`.

### Expected Behaviour

The encoding command should return the orignal value `YQpi`.

**Comment by jfkisafk** [comment]
@raycastbot assign me

**Comment by jfkisafk** [comment]
The issue is not with the library but the way clipboard is being read here:

https://github.com/raycast/extensions/blob/8783a0522df8b595581ceae62dd5bf93621a097f/extensions/base64/src/encode.tsx#L6

which only yields `b` instead of `a\nb` from clipboard. Fixed it in the PR.
