### ISSUE TITLE
[Workspace] Please make this extention approved by Google Advanced Protection

### ISSUE THREAD

**Issue by jjmmfi** [raycast/extensions#13840]
### Extension

https://www.raycast.com/raycast/google-workspace

### Description

Please make this extension approved by Google Advanced Protection

### Who will benefit from this feature?

It is recommended that everyone caring about their online security should turn on Google Advanced Protection. Now most people can't use the extension including myself.

### Anything else?

Google Advanced Protection Program:
https://support.google.com/accounts/answer/7539956#zippy=%2Ccan-i-still-use-sign-in-with-google%2Ccan-i-use-non-google-apps-services-or-apps-script-with-advanced-protection

SIGN in error:

ERROR 400: policy_enforced

response_type=code redirect_uri=com.raycast:/oauth?package_name=Extension code_challenge_method=S256 state=eyJpZCI6IjZFMTY4RUFCLUE2ODctNEY3RC04RjBCLTg3OUE2OEYzRjRFOCIsInByb3ZpZGVyTmFtZSI6Ikdvb2dsZSIsImZsYXZvciI6InJlbGVhc2UifQ client_id=859594387706-uunbhp90efuesm18epbs0pakuft1m1kt.apps.googleusercontent.com code_challenge=VYPyEB2O7hvuAUlgMhF82UFIYBWJC-o6OebD1Ls4hbI access_type=offline scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.readonly openid flowName=GeneralOAuthFlow

**Comment by jjmmfi** [comment]
Sorry, I made a duplicate of this; did not see it the first time: https://github.com/raycast/extensions/issues/2220

**Comment by thomaslombart** [comment]
Thank you for reporting the issue. I'll mark yours as a duplicate and reopen the original one.
