### ISSUE TITLE
[Apple Notes] Create notes with Ai Notes

### ISSUE THREAD

**Issue by code-al** [raycast/extensions#13851]
### Extension

https://www.raycast.com/raycast/apple-notes

### Raycast Version

1.80.0

### macOS Version

14.5

### Description

I'm trying to create a note with a youtube video link using the ai note but it returns random topics unrelated to the video. I tried it on raycast ai running gpt 4o and it returns the correct topic but can't get it to work on ai notes. Here's the link: https://www.youtube.com/watch?v=3Nq3ye-QCyM

### Steps To Reproduce

1. In the text, I input "Youtube video summary"
2. In the instructions, I input "Create a summary using the title of this https://www.youtube.com/watch?v=3Nq3ye-QCyM youtube video."

### Current Behaviour

It creates a note using a random unrelated topic to the video.

### Expected Behaviour

Creates a note using the title of the video as summary.

**Comment by StevenRCE0** [comment]
Thank you for feedback. Could you record a clip demonstrating what's going on? I'm not really familiar with the workflows involving Raycast AI 🤔

**Comment by StevenRCE0** [comment]
My initial guess was that the AI API used in the extension (as well as other extensions) does not have multi-modal capabilities. Maybe perplexity would be a better option for this kind of need?

**Comment by code-al** [comment]
Ahh, i see. Not having the ability to access the web does explain why this happens. Such a shame. Thanks!
