### ISSUE TITLE
[Raindrop.io] Search by title only

### ISSUE THREAD

**Issue by tnaseem** [raycast/extensions#13867]
### Extension

https://www.raycast.com/lardissone/raindrop-io

### Description

I added a comment here:
https://github.com/raycast/extensions/issues/8939

But as the issue is marked as stale I'm not sure it will be seen! So, I thought I'd open a new issue.

It appears that you can search by title now, which wasn't possible before, according to that issue linked above.

As a test, in Raycast, I added `title:` before the search text and it did just that - searched just the title string. So, I'm assuming there must be a way of adding this feature now?

### Who will benefit from this feature?

Everyone who just wants to search the title of the bookmark and stops what looks like unrelated results from showing up, as the curent search searches through the url, description, etc too.

### Anything else?

Searching as normal (ie. no `title` operator):
![raindrop-io 2024-08-04 at 21 57 36](https://github.com/user-attachments/assets/9f62c5a9-b42f-4658-8cc4-f40db0714639)

The same search WITH the `title` operator:
![raindrop-io 2024-08-04 at 21 54 07](https://github.com/user-attachments/assets/05db611c-7fed-4bfd-bd0e-9c5a5b62f800)

As you can see, we get a much cleaner set of results that makes more sense, in the latter case.

So, it would be good to have the option in settings to allow user to search just the title, and not have to keep typing 'title:' each time!

**Comment by sh-cho** [comment]
@raycastbot keep this issue open

**Comment by sh-cho** [comment]
@raycastbot good first issue

**Comment by michaelwoodruff** [comment]
Wanted to bump this up. Can we add preference to search JUST TITLE ALWAYS. Without it search results are filled with a lot of garbage. Surprised this isn't the default. Thanks everyone for your time.

**Comment by lardissone** [comment]
Just pushed a PR with this feature: https://github.com/raycast/extensions/pull/15939
