### ISSUE TITLE
Node.js Bug

### ISSUE THREAD

**Issue by VedantGirkar** [raycast/extensions#13864]
### Extension

https://www.raycast.com/erics118/file-manager

### Raycast Version

1.79.1

### macOS Version

15.0

### Description

whenever I run this extension the terminal window opens up on my dock and keeps bouncing 
<img width="1728" alt="Screenshot 2024-08-05 at 1 26 06 AM" src="https://github.com/user-attachments/assets/fc4de5ae-cafc-491d-886a-4a309b43e431">
the "exec" file just shows up out of nowhere which was linked to the Node.js folder of raycast

### Steps To Reproduce

just starting the extension caused the exec file to pop up

**Comment by erics118** [comment]
This is an with either Raycast or macOS sequoia. See the thread in the Raycast slack for more info: https://raycastcommunity.slack.com/archives/C01A0R0NXGQ/p1721763938839879

**Comment by LitoMore** [comment]
It's not a bug from Raycast. Also, this issue has been fixed in macOS 15 Developer Beta 5.

@erics118 Feel free to use `@raycastbot close as not planned` to close this issue as not planned.

**Comment by VedantGirkar** [comment]
can you please tell me if this is resolved even for MacOS 15.1

**Comment by VedantGirkar** [comment]
thank you
