### ISSUE TITLE
[Linear] Add feature to create issues from templates or cached fields

### ISSUE THREAD

**Issue by mbssai** [raycast/extensions#13869]
### Extension

https://www.raycast.com/linear/linear

### Description

Either:
- Create issue from template
OR even better
- Create issue with certain fields already filled in (so you can quickly create issues that are always part of the same project/cycle/etc)

### Who will benefit from this feature?

Anyone who frequently makes tickets

**Comment by jfkisafk** [comment]
@raycastbot rename this issue to "Add feature to create issues from templates or cached fields"

**Comment by jfkisafk** [comment]
@raycastbot rename this issue to "[Linear] Add feature to create issues from templates or cached fields"

**Comment by jfkisafk** [comment]
@raycastbot assign me
