### ISSUE TITLE
[PDFSearch] Collection search not working

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#13876]
### Extension

https://www.raycast.com/kevin-pek/pdfsearch

### Raycast Version

1.80.0

### macOS Version

14.5

### Description

The collection search is not working.

### Steps To Reproduce

1. Create a collection
2. Try to search it

### Current Behaviour

Nothing is displayed in the search view.

### Expected Behaviour

Results should be displayed in the search view.

**Comment by kevin-pek** [comment]
Hi @xilopaint, thanks for reporting this! I was wondering if you have an example search query/document that is not working? My current suspicion is that changing the search logic to use Apple's SearchKit API may have caused how search results are retrieved to change.

**Comment by xilopaint** [comment]
It doesn't work for all the PDF files I have tested so far. Here's an example:

[apple-style-guide.pdf](https://github.com/user-attachments/files/16499805/apple-style-guide.pdf)

**Comment by kevin-pek** [comment]
Thanks! Could I also check if you enter very specific keyword queries eg. "march" or "june", you are able to get search results on the document? I am able to get 1 or 2 results with the queries on the PDF you provided.

**Comment by xilopaint** [comment]
Oh, now I see it works, but it's too slow. Searching for the term "follow" takes 6 seconds to show results. For a common word like "not", it takes 28 seconds. Is this extended time expected? How does the current performance compare to your previous implementation?

**Comment by kevin-pek** [comment]
Wow, that's an interesting problem, I was not expecting the new implementation to be slower. 

After looking deeper into this, I realised a few issues that have likely caused this:

1. The raycast swift extension does not automatically cancel previously triggered search processes unlike the previous implementation.
2. The new search implementation currently does not use multithreading which likely slowed things down.
3. For queries with many results (a few hundred), the function waits for all results to be collected before returning, which causes issues for larger files/collections.

Going to rectify this as soon as I can!
