### ISSUE TITLE
Issue with Git Search Repo since PR: Update github-repository-search extension #13720

### ISSUE THREAD

**Issue by MarcoLucke** [raycast/extensions#13872]
### Extension

https://www.raycast.com/raycast/github

### Raycast Version

1.80.0

### macOS Version

15.0

### Description

Since the newest Update of Git-Search Repos the behaviour of the included Repo Actions changed.
cmd + option + c to open / clone (if not existing already) a repo in vscode is gone.
only option now seems to cmd + shift + c which always clones into a new folder even tho the repo already got cloned before.
Option for default folder to clone into seems gone to since I always have to select my dev folder

### Steps To Reproduce

open raycast
open search repos
select a repo
try to open an existing repo in vscode without cloning it again

### Current Behaviour

I can only clone repos into a copy folder

### Expected Behaviour

I can clone a repo which doesn't exist local and can open an existing repo in vscode without cloning it again

**Comment by thomaslombart** [comment]
![CleanShot 2024-08-05 at 14 01 17@2x](https://github.com/user-attachments/assets/19fa4e4d-ceb7-4a35-9d9f-ade5d1e7e4e2)

I can still see it. Could you share a recording? It'll make it easier to see what's happening.

**Comment by MarcoLucke** [comment]
https://github.com/user-attachments/assets/378cc904-1e1a-4441-88af-af65e9f1cea8

As seen in the footage "clone in vscode" will always clone into a new folder.
This differs from the behaviour before where it would just open an existing repository in vscode instead of cloning it regardless.

**Comment by thomaslombart** [comment]
There's hasn't been any changes to the VS Code clone action in [the latest update](https://github.com/raycast/extensions/pull/13684) as shown in the screenshot, so I'm not sure what could cause the bug here. 

![CleanShot 2024-08-08 at 09 52 02@2x](https://github.com/user-attachments/assets/9adeabad-654f-47aa-820a-fea2a44e2f71)

> The default path where to clone to is gone as well so now I need to select the path every time I clone again

This wasn't used for the `Clone in VSCode` action. Are you sure you're referring to the right action? Could you send another recording where I can see the actions used instead of the keyboard shortcuts?

**Comment by MarcoLucke** [comment]
Isnt that change above ur marked one exactly what im referencing to? 

I stated:
<img width="818" alt="image" src="https://github.com/user-attachments/assets/728f7ff6-bd5d-44f8-9db2-22b987258044">
as stated there was a action cmd + opt + c that cloned / opened a repository in vscode if the repository already exists
which is now changed to cmd + opt + shift + c which allows to clone but not to open?
<img width="766" alt="image" src="https://github.com/user-attachments/assets/84bc10df-3128-4a15-bea9-4e4d399477ac">

**Comment by atrebels** [comment]
I think this is the missing option:
![image](https://github.com/user-attachments/assets/0201b0df-296d-471d-bb8a-dff3bd06e5e1)

In this action ist was possible to set a default target.  when cloning an repository with this action, it clones the repository to <defaultPath>/<Organization>/<reponame>. If it is already in there, it just open VS Code to Open the repository and didn't clone it again.

The mentioned "Clone in VSCode" Action clones the repository everytime (with a counting suffix) and you need to choose a target directory each time you clone.

So now Raycast doesn't acts  as a fast browser between repository anymore.

**Comment by MarcoLucke** [comment]
This action does not do the same as the old action "Clone and Open".
The Action "Clone in VSCode" only allows to Clone into a new Folder and open it in VSCode afterwards.
I don't want to clone it again if it's already cloned. The old action allowed to just open an already existing repository without needlessly cloning it again.
This was a very nice way to browse through and open existing work to continue working on.

The clone action was only needed for the first time I open a project, afterwards the "just open in vscode" component made it an everyday action I used to open the repositories in vscode.

As shown in the provided videos and screenshots the actions "clone in vscode" and "clone with options" do either always clone into a copyfolder or just block the complete action with the error text "repository already exists"

**Comment by jfkisafk** [comment]
@raycastbot assign me
