### ISSUE TITLE
[HowLongToBeat] 404 error when opening the extension

### ISSUE THREAD

**Issue by FelixLisczyk** [raycast/extensions#13873]
### Extension

https://www.raycast.com/Cronos87/howlongtobeat

### Raycast Version

1.80.0

### macOS Version

14.6

### Description

When opening the extension, the following error message appears in the status bar: `Could not perform search. Error: Request failed with status code 404`. The same error appears when searching for a game.

### Steps To Reproduce

1. Open the extension

### Current Behaviour

The error message described appears.

### Expected Behaviour

There should be no error message. The game search should work as expected.

**Comment by whitespacecode** [comment]
Not sure what happend but the raycast `npx @raycast/api@latest publish` added a pull request instead.. :/ https://github.com/raycast/extensions/pull/13888

**Comment by FelixLisczyk** [comment]
The issue is resolved now. Thank you!
