### ISSUE TITLE
Allow copy icon name instead of svg

### ISSUE THREAD

**Issue by joaovitoras** [raycast/extensions#1388]
# Extension – [Iconify](https://github.com/raycast/extensions/tree/main/extensions/iconify)

Author: @Destiner 

**Describe the feature and the current behavior/state.**

Today `Copy to clipboard` feature copy full svg
I would like to copy icon name instead of svg

**Who will benefit from this feature?**

People who only need the icon name

**Comment by Destiner** [comment]
Hey, thanks for feedback. Curious to learn a bit more about your workflow. Do you use the extension to preview icons, and then some library that renders the icon by specifying it’s name?

**Comment by joaovitoras** [comment]
Yes I use vuetify. An UI library for material design, in it there is a component called v-icon where it is possible to render icon only with the name

https://vuetifyjs.com/en/components/icons/
