### ISSUE TITLE
[Spotify Player] Generate Playlist not working

### ISSUE THREAD

**Issue by melissaep** [raycast/extensions#13899]
### Extension

https://raycast.com/mattisssa/spotify-player

### Raycast Version

1.80.0

### macOS Version

14.6

#### Error:
```
SyntaxError: Expected ',' or ']' after array element in JSON at position 1130
    at JSON.parse (<anonymous>)
    at failureToastOptions.title (/Users/mperry/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/generatePlaylist.js:76:184)
```

### Steps To Reproduce

1. Open generate spotify playlist command
2. Enter "jazz" as description
3. Get error "no results"
4. Repeat for a variety of searches

**Comment by thomaslombart** [comment]
Are you consistently experiencing the same issue each time? If so, are you also getting the same error message? Thanks!

**Comment by wohfab** [comment]
I think I had this once in the past but not anymore. Didn't really think about it. I'm on `Version 1.81.1` and the command works as expected. 

@melissaep, did you do the update to `>1.81.0` in the meantime and tested it again?

**Comment by psnewman** [comment]
It stopped working for me too. The "Generate playlist" command with any query no longer returns songs, while the "Add Playlist to Spotify" and "Add Songs to Queue" options are still available. I don't use this command frequently, so I'm uncertain when the issue began.

**Comment by thomaslombart** [comment]
Yeah, I had the error as well and updating the model to GPT-4o mini under the hood seemed to do the trick. You should have faster results as well, let me know if it still doesn't work!
