### ISSUE TITLE
[Remember the Date] - show a date in the root search

### ISSUE THREAD

**Issue by Matias-Sandoval** [raycast/extensions#13895]
### Extension

https://www.raycast.com/pernielsentikaer/remember-the-date

### Description

I would like for a date to be able to be pinned to "favorites" in the root search, this way it will remind us how many days are left until a date every time we open the root search

### Who will benefit from this feature?

They would benefit those who need to constantly remember how many days are left until that date. In my case, I want to remember how many days are left until an exam every time I open the root search.

![SCR-20240806-kywl-2](https://github.com/user-attachments/assets/3312a1c5-df39-4777-a984-2738da73c29a)

**Comment by samuelkraft** [comment]
@Matias-Sandoval As a workaround you can use the menubar command to do the same thing https://github.com/raycast/extensions/pull/11883

**Comment by pernielsentikaer** [comment]
By the way, bathing once a month sounds like an awesome thing 🔥

The menu bar is ideal; otherwise, we could maybe let you pin one of them in the subtitle of the command too. Can you use the menu bar as @samuelkraft mentions

**Comment by Matias-Sandoval** [comment]
Yes, I could use it, I have no problem with that. I made the request because my menu bar is full and I don't have space for more. That's why, as a solution, I thought some dates could be in the root search
