### ISSUE TITLE
[Ollama AI] Can't find "Add Server" Action

### ISSUE THREAD

**Issue by valaypatel** [raycast/extensions#13898]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Raycast Version

1.80.0

### macOS Version

14.5 (23F79)

### Description

Unable to find Add Server Action on Manage Model action
![Screenshot 2024-08-06 at 12 04 32 PM](https://github.com/user-attachments/assets/1dfc52a0-496f-4c99-b396-e633cc4dee2f)

### Steps To Reproduce

1. Install Ollama App
2. Search for Manage Model Action
3. Hit Command + K to see action available
    

### Current Behaviour

See that no Add Server action available

### Expected Behaviour

Add Server action should be available.

**Comment by MassimilianoPasquini97** [comment]
You need to run the command for view is Actions menu 😊.
![Screenshot 2024-08-06 alle 22 36 46](https://github.com/user-attachments/assets/79dd7adb-2b5f-49a5-9ff8-512ac7ffe984)

**Comment by MassimilianoPasquini97** [comment]
@raycastbot assign me

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue
