### ISSUE TITLE
[MultiForce] - Login URL Redirects user to the Lightning Pages setup page vs setup or home

### ISSUE THREAD

**Issue by onabavian** [raycast/extensions#13900]
### Extension

https://www.raycast.com/brian_j_decoder22/multi-force

### Raycast Version

1.80

### macOS Version

14.5

### Description

 Login URL Redirects user to the Lightning Pages setup page vs setup or home

### Steps To Reproduce

1. Click a Login
2. Salesforce opens into the Lightning App Builder Tab

### Expected Behaviour

Opens Setup home or Home

**Comment by Decoder22** [comment]
@raycastbot assign me

**Comment by Decoder22** [comment]
@raycastbot good first issue

**Comment by Decoder22** [comment]
@raycastbot keep this issue open

**Comment by Decoder22** [comment]
@raycastbot close this issue Closes the issue.

A fix for this issue was accepted into the Raycast store.

**Comment by Decoder22** [comment]
@raycastbot close this issue
