### ISSUE TITLE
[Apple Mail] Add menu bar command

### ISSUE THREAD

**Issue by catdevnull** [raycast/extensions#13902]
### Extension

https://www.raycast.com/yug2005/mail

### Description

Would love to have a menu bar item that says how many unread emails are available. The context menu should include all mails in the inbox, and a text that says when it was last checked.

**Comment by jfkisafk** [comment]
@raycastbot assign me

**Comment by jfkisafk** [comment]
Hey @catdevnull I think it'd be more consistent if we keep the UI elements for the menu bar context the same as you see in "See Recent Mail" command. I agree with other propositions regarding count etc. What do you think?

**Comment by catdevnull** [comment]
I personally don't use the "see recent mail" command as it seems to always be outdated for me.. I'm not sure why. At first I thought it only showed unread email, but I guess that's not the case. But it's not showing emails that are in my inbox for some reason.

If it were to work properly, that would work for me :)
Thanks for working on this!

**Comment by jfkisafk** [comment]
@raycastbot rename this issue to "[Apple Mail] Add menu bar command"

**Comment by catdevnull** [comment]
not stale
