### ISSUE TITLE
[Bitwarden Vault] Generate password utility works incorrectly

### ISSUE THREAD

**Issue by szarbartosz** [raycast/extensions#13906]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Raycast Version

1.80.0

### macOS Version

14.5

### Description

When trying to generate password using bitwarden extension, it adds the special characters to it, regardless of whether the option to include them is selected.
![image](https://github.com/user-attachments/assets/e2d564cb-a5aa-4958-8945-bb50997a9114)

### Steps To Reproduce

1. Open raycast and run `Generate Password` command from `Bitwarden` extension
2. Select type: `Password`
3. Enter the length of the desired password (eg. 20)
4. Make sure that the last checkbox (the one responsible for including special characters) is unchecked
5. Regenerate password multiple times and observe the outcome

### Current Behaviour

Generated password contains special characters

### Expected Behaviour

Generated password does not contain special characters

**Comment by szarbartosz** [comment]
The same happens for the numeric characters:
![image](https://github.com/user-attachments/assets/e30b85f6-188e-49bc-90e4-0e27579176af)

**Comment by jomifepe** [comment]
Hey, yeah there seems to be an issue. I'm able to get consistent results with special characters, but I see that numerical are being included when unchecked. Will investigate.

**Comment by szarbartosz** [comment]
@jomifepe any update on this one? I checked it recently and the bug still occurs 🐞

**Comment by jomifepe** [comment]
> @jomifepe any update on this one? I checked it recently and the bug still occurs 🐞

Hey, I'm planning to do some changes to the generate password command, which will include a fix for that, I just haven't found the time lately. Will probably open a PR for it soon. Sorry for the delay 🙂

**Comment by jomifepe** [comment]
Should be fixed, git it a try 🙂

**Comment by szarbartosz** [comment]
when tested locally I noticed that the password is still generated with special characters, even though the `Special characters` checkbox is not checked:
<img width="862" alt="image" src="https://github.com/user-attachments/assets/b6975269-29fa-4550-aa44-0102b05acc91">

**Comment by jomifepe** [comment]
😔 Will investigate further. There might be some issue with the data already store locally, as the code seems to run fine for me, so it's hard to track the issue down.

**Comment by jomifepe** [comment]
@raycastbot reopen this issue
