### ISSUE TITLE
[Drafts] Run action Create a Draft from selection in background with system notification

### ISSUE THREAD

**Issue by dudido** [raycast/extensions#13915]
### Extension

https://www.raycast.com/FlohGro/drafts

### Description

Currently, creating a Draft from a selection opens the window of Drafts showing the newly created draft. It would be nice if this would optionally happen in the background (optionally with a system notification), therefore not raising the window of Drafts everytime. Thanks!

### Who will benefit from this feature?

Aynone constantly clipping content to Drafts not wanting to be disturbed by the app raising and taking focus

**Comment by FlohGro-dev** [comment]
@dudido sorry for taken so long - working on it now and already got a prototype running 😊 
I will look into other commands that also would benefit from this approach and create a good package of new features! 

Thanks for your patience and suggestion!

**Comment by FlohGro-dev** [comment]
@dudido update is ready for review by the Raycast team: https://github.com/raycast/extensions/pull/14683

**Comment by dudido** [comment]
@FlohGro-dev Thanks I noticed the change the other day. It's beautiful, so much more efficient!
