### ISSUE TITLE
[Easydict] option to pop to root search immediately

### ISSUE THREAD

**Issue by sunrisewestern** [raycast/extensions#13916]
### Extension

https://www.raycast.com/isfeng/easydict

### Description

Currently, after searching for a word in Easydict, the user remains within the search results. It's not convenient to change the user's "Pop to Root Search" preference for all application.

This feature request proposes adding an option to automatically "pop" back to the root search bar immediately after a search is performed, especially beneficial when using keyboard shortcuts.

### Anything else?

Raycast provided [PopToRootType](https://developers.raycast.com/api-reference/window-and-search-bar) API

**Comment by tisfeng** [comment]
Sounds good, but the `PopToRootType` option is strange; it's impractical because it can only be actively used in the [closeMainWindow](https://developers.raycast.com/api-reference/window-and-search-bar#closemainwindow) method.

> This feature request proposes adding an option to automatically "pop" back to the root search bar immediately after a search is performed, especially beneficial when using keyboard shortcuts.

I think this is pointless. It's impossible to close the main window immediately after querying.

Theoretically, Raycast should provide a delegate method for closing the extension window, where we could set the `PopToRootType` option. I'm not sure if such an API exists now. I haven't found it.

**Comment by sunrisewestern** [comment]
I'm sorry the feature request description is misleading. I'm using the search word function(with "Query Selected Text Automatically" on) with a keyboard shortcut (e.g., ⌥⌥ ). When I press ⌥⌥, it will search the word I selected, and then I close the raycast window (by clicking outside the raycast window, not by Esc-Esc). And then I select another word and press ⌥⌥, what I expected is to search the new word, but it's still showing the previous word unless I set "Pop to Root Search" in raycast setting (which will affect all the extensions) or use Esc-Esc to close raycast window every time. 
 
The feature request should be: adding an option to automatically pop back to the root search bar immediately when closing the raycast window.

**Comment by tisfeng** [comment]
> adding an option to automatically pop back to the root search bar immediately when closing the raycast window.

Oh, I understand your idea, but I don't know how to implement it. Currently, Raycast doesn't seem to provide a convenient API to handle the option for automatically hiding the window when clicking outside of it. If there is one, please let me know.

I suggest you use Cmd + W to close the window, as this will ensure that every time you use the shortcut ⌥⌥, Easydict will query new words.

**Comment by sunrisewestern** [comment]
Ok, I thought PopToRootType API would do the trick. Thanks anyway!

**Comment by tisfeng** [comment]
🙂

@raycastbot close this issue
