### ISSUE TITLE
[Brew] Issue when importing raycast config from intel mac to silicon mac

### ISSUE THREAD

**Issue by msllrs** [raycast/extensions#13922]
### Extension

https://www.raycast.com/nhojb/brew

### Raycast Version

1.80.0

### macOS Version

13.4

### Description

after exporting my raycast config from an old intel machine and importing to a new silicon machine, i get the following error
<img width="338" alt="CleanShot 2024-08-08 at 10 16 23@2x" src="https://github.com/user-attachments/assets/7db73be0-57c1-4c61-971f-2fc944c05a5b">

also including the logs:
[ray.20240807_222021.log](https://github.com/user-attachments/files/16540716/ray.20240807_222021.log)

### Steps To Reproduce

export settings from intel mac
import settings to silicon mac
rub any brew command

**Comment by jfkisafk** [comment]
Did you install `brew` on your apple silicon Mac? You can verify it using `brew --version` in your terminal. Please use this command to install `brew` if it is not installed and then try the commands again:  

```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

**Comment by msllrs** [comment]
that did the trick! somehow i overlooked the fact that `brew` wasnt installed on the silicon mac 🙃
