### ISSUE TITLE
[ChatGPT3 Prompt] ...

### ISSUE THREAD

**Issue by luricaopensource** [raycast/extensions#13928]
### Extension

https://www.raycast.com/denizyoldas/chatgpt3-prompt

### Raycast Version

1.80.0

### macOS Version

14.6.1

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'map')

Et:index.tsx:16:43

---
13: }

### Steps To Reproduce

Just execute the extension after install

### Current Behaviour

Extension doesnt work, show a message "something went wrong"

### Expected Behaviour

Working

**Comment by husniadil** [comment]
I just checked this, and it appears that this extension has [the same issue as the ChatGPT extension](https://github.com/raycast/extensions/issues/13861). The problem is caused by an invalid CSV file from the prompt provider. Let me propose a PR to fix this.

@raycastbot assign me

**Comment by husniadil** [comment]
@raycastbot assign me

**Comment by husniadil** [comment]
@luricaopensource Hi, please check again. The fix should be there already. If it still persist, you can trigger the extension update manually from the Raycast menu.
