### ISSUE TITLE
[Whois] Add IP2Location.io API as a failover in case ipwho.is is not responding

### ISSUE THREAD

**Issue by ip2location** [raycast/extensions#13920]
### Extension

https://www.raycast.com/zavbala/whois

### Description

Currently, there is no failover API to call if ipwho.is is not responding. I think it would be good to have a failover to [IP2Location.io](https://www.ip2location.io/) where you can call the API endpoint like [https://api.ip2location.io](https://api.ip2location.io).

**Comment by j3lte** [comment]
Great idea, can you make a PR for this? As this is coming from @ip2location, I'm guessing this is more of an advertisement than an idea?

**Comment by j3lte** [comment]
I'm closing this issue. This account is spamming all over Github with their commercial service...

![Screenshot 2024-08-21 at 19 00 33](https://github.com/user-attachments/assets/260594e1-b11c-456a-a9c9-0defce042db2)

@raycastbot close this issue
