### ISSUE TITLE
[DevDocs]...

### ISSUE THREAD

**Issue by HenryGetz** [raycast/extensions#13932]
### Extension

https://raycast.com/djpowers/devdocs

### Raycast Version

1.80.0

### macOS Version

14.5

#### Error:
```
Error: Not Found
    at Object.q4 [as current] (/Users/henrygetz/.config/raycast/extensions/718783dc-e693-4a56-afe2-381f23a6f422/search-entries.js:8:315698)
    at /Users/henrygetz/.config/raycast/extensions/718783dc-e693-4a56-afe2-381f23a6f422/search-entries.js:8:316604
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

I just downloaded the most recent version of DevDocs and tried `Search Entries` with `psql` (or really anything), and it just says "No Results" and "Failed to fetch latest data, Not Found"

<img width="862" alt="image" src="https://github.com/user-attachments/assets/a0c0fe9e-f650-4358-8f17-bd694875ddb1">
<img width="862" alt="image" src="https://github.com/user-attachments/assets/d0e41730-e0ef-47f0-918a-2902bdfefd82">

### Current Behaviour

<img width="862" alt="image" src="https://github.com/user-attachments/assets/d0e41730-e0ef-47f0-918a-2902bdfefd82">

**Comment by HenryGetz** [comment]
Sorry— I did try to look in there, but that makes much more sense ahaha.. Thanks for your reply and work on this extension :)


> Oh, that's what the Copy command is for 🤦‍♂️😂
<img width="752" alt="image" src="https://github.com/user-attachments/assets/3c807ba0-3c1b-432e-86eb-9f0a042106ff">

**Comment by djpowers** [comment]
All good, @HenryGetz! I had added that "copy" command to try and make the slug more findable. Admittedly the "Search Entries" command is best used when set up as a Quicklink so you don't have to worry about passing in the slug each time.

I typically usually use the extension in one of two ways:
- invoking "Search Documentations" and typing to narrow down the documentation
- invoking a Quicklink to launch "Search Entries" via alias or hotkey to go directly to a specific documentation's entries (e.g., "psql" as a hotkey to launch PostgreSQL 16 entries from root search)
