### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by evgrashin** [raycast/extensions#13941]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

just updated

### macOS Version

14.5

### Description

Doesnt' download videos from YouTube.
<img width="314" alt="Снимок экрана 2024-08-09 в 11 55 02" src="https://github.com/user-attachments/assets/b62d3ecc-91fb-44ac-bac5-7f582cb24d43">

### Steps To Reproduce

Press the button Download video. See a mistake

**Comment by ridemountainpig** [comment]
Fixed in #13939.
