### ISSUE TITLE
[Visual Studio Code] "Open in code" just opens finder window

### ISSUE THREAD

**Issue by jacten** [raycast/extensions#13949]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Raycast Version

1.80.0

### macOS Version

14.4 (23E214)

### Description

When I select a project and click "Open in code" it just opens finder, instead of opening in vscode. 

https://github.com/user-attachments/assets/a590253b-0281-49d9-81fe-ba10d085cf48

### Steps To Reproduce

1. Install vscode extension
2. Choose "Search Recent Projects"
3. Press "enter"

### Current Behaviour

Opens in finder

### Expected Behaviour

Opens in vscode

**Comment by jacten** [comment]
Fixed! Issue was that Visual Studio Code was installed, but was not in my Applications directory 🤷

**Comment by jayjk13** [comment]
Facing the same.

Raycast Version
1.89.0

macOS Version
15.1.1 (24B91)
