### ISSUE TITLE
[Jira] Getting SSL errors

### ISSUE THREAD

**Issue by RabbitShare** [raycast/extensions#13946]
### Extension

https://www.raycast.com/raycast/jira

### Raycast Version

1.80.0

#### Error:
```
Qr: request to https://jira.adress.com/rest/api/3/myself failed, reason: self-signed certificate in certificate chain

    at withAccessToken(_W)
_r:index.js:8:2593
    at ray-navigation-stack
Eo:index.js:8:2094
```

Gitlab extension working with 
<img width="310" alt="image" src="https://github.com/user-attachments/assets/ceb9cd5f-b772-4832-b513-ac8e7afcd75f">

### Steps To Reproduce

Start any command

### Current Behaviour

Error with certificate

### Expected Behaviour

Working without have any errors

**Comment by thomaslombart** [comment]
Are you using some kind of VPN/firewall/proxy?

**Comment by RabbitShare** [comment]
> Are you using some kind of VPN/firewall/proxy?

Yes, company proxy for access to jira

**Comment by thomaslombart** [comment]
That's probably why it's not working. You may want to change your settings in `Advanced > Proxy and Certificate Settings` to fix it.

**Comment by thomaslombart** [comment]
I'm closing this issue to maintain a clean backlog. Feel free to comment it if you still have the problem.
