### ISSUE TITLE
[Raycast Notification] ...

### ISSUE THREAD

**Issue by njthebaud** [raycast/extensions#13956]
### Extension

https://www.raycast.com/maxnyby/raycast-notification

### Description

Really liking this extension since I've always wanted to use Raycast's notifications. However, it would be nice if there were options for colored text. Specifically green and red (yellow may be useful as well), although I suppose the option of any color would be ideal. Other extensions sometimes give their notifications in green if it was successful and red if it wasn't. The below shows an example in green from a GIF extension. This sometimes includes a circle (success) at the beginning or an X for failure, but not as necessary as the color in my opinion, but would be nice to have.

![SCR-20240809-pzqj](https://github.com/user-attachments/assets/ae92ad7c-d03c-4ed4-bd5d-0eb3dfb0916f)

### Who will benefit from this feature?

Anyone who wants to indicate success or failure of an action, or simply just wants to have the option of using colored text in their notifications for no other reason than to have color.

**Comment by erics118** [comment]
Seems like this actually isn't a feature. This extension internally uses the `showHUD` function which only supports a single text parameter. See https://developers.raycast.com/api-reference/feedback/hud#showhud

What you're seeing is likely from a toast after the main window has closed (which looks the exact same) but supports a success, failure, and loading state.

**Comment by jfkisafk** [comment]
@njthebaud I have implemented the feature but the toast API does not support background launchType. So there might be a flickering effect (opens raycast -> close main window -> show toast) to get success and failure notifications.

**Comment by erics118** [comment]
Yeah, I was concerned about the possible flickering. I was wondering if maybe the API could be updated to support this the success, failure, and loading states, so I asked in the slack: https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1723493267421789

**Comment by njthebaud** [comment]
hmm...a little bit of a deal breaker if it has to briefly open and close the raycast window before showing the notification. Hopefully the API can be updated since it sounds like you're just one step away. Thanks for keeping me in the loop...I'll definitely keep using the extension in the mean time though ;)
