### ISSUE TITLE
[Change Case] ...

### ISSUE THREAD

**Issue by SparkDevAdmin** [raycast/extensions#13954]
### Extension

https://www.raycast.com/erics118/change-case

### Raycast Version

1.80.0

### macOS Version

13.3.1 (a) (22E772610a)

### Description

When I add text with special characters, like "-" "+" etc, Change Case is removing those characters in the final string

This means I constantly have to add the special characters back...which basically negates the timesave by using Change Case in the first place 😅

Would love to see an update of this!

### Steps To Reproduce

Copy text with special characters
Select "Capital Case" within Change Case
Paste the string back (it won't have the special characters)

**Comment by erics118** [comment]
Few questions so I can help with this issue:
- Could you give an example that you are using?
- Which case are you transforming to?
- What is the expected result, and how does it differ from what the extension produces?

Generally for most cases, like pascal, snake, header, etc, these are used in programming or similar contexts, where there character set is usually limited to letters, numbers, `-` and `_`.

For cases like title and sentence, these are generally used in non-programming contexts, and symbols should be kept.

**Comment by husniadil** [comment]
Actually this extensions is cool, you can even preview this.

I tried this one, let's say I am working with Markdown:

> \## a titLe - with desC

and here is the preview from the Change Case`:

<img width="200" alt="Screenshot 2024-08-13 at 09 46 37" src="https://github.com/user-attachments/assets/bed9b843-2ec6-4638-861e-646ef6fb10ea">
<img width="200" alt="Screenshot 2024-08-13 at 09 46 49" src="https://github.com/user-attachments/assets/67b07000-7d72-4388-bfe7-5c225e8c06af">
<img width="200" alt="Screenshot 2024-08-13 at 10 04 10" src="https://github.com/user-attachments/assets/eacee4de-7a80-4cd1-8f14-c6e7fbc4770c">

Some of the formats removes special character, in this case `#` and `-`

Maybe you can add the rules or disclaimer in the README if needed?

**Comment by SparkDevAdmin** [comment]
Hey there,

I was using it to reformat the titles in a deck I was building. So it was to Capital Case 👍🏾

The expected result was not to have characters removed from the string I was holding in my clipboard!

Thanks,

-Adrian

**Comment by erics118** [comment]
I made a PR that includes preferences for setting prefix/suffix characters that won't be removed. Please take a look. You can view the linked google sheet to see the changes for various transformations.
