### ISSUE TITLE
[YouTube Downloader] ...its showing download failed

### ISSUE THREAD

**Issue by ShubhamPP04** [raycast/extensions#13966]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

1.73.2

### Description

Download failed

### Steps To Reproduce

.

**Comment by ridemountainpig** [comment]
Fixed in https://github.com/raycast/extensions/pull/13939.

**Comment by ridemountainpig** [comment]
@raycastbot close this issue
