### ISSUE TITLE
[YAFW] can you add speed up videos/gifs? 

### ISSUE THREAD

**Issue by bigplayer-ai** [raycast/extensions#13971]
### Extension

https://www.raycast.com/pablopunk/yafw

### Description

	•	-i: Specifies the input file.
	•	-filter:v "setpts=PTS/1.5": Speeds up the video by adjusting the presentation time stamps (PTS).
	•	-filter:a "atempo=1.5": Speeds up the audio by a factor of 1.5.
	•	The last part is the output file with a new name to indicate it has been sped up.

### Who will benefit from this feature?

everyone

**Comment by tonypinkevych** [comment]
@raycastbot assign me

**Comment by tonypinkevych** [comment]
@bigplayer-ai thanks for the idea. I'll start working on it.
