### ISSUE TITLE
[Rectangle] Add a cascade window arrangement option in Rectangle Actions

### ISSUE THREAD

**Issue by bigplayer-ai** [raycast/extensions#13981]
### Extension

https://www.raycast.com/crickford/rectangle

### Description

@crickford, adding a cascade window arrangement option to the Raycast extension would be incredibly useful, especially with the recent release of Cascade version 2, which brings significant enhancements for macOS users. You can read more about these improvements [here](https://github.com/rxhanson/RectanglePro-Community/issues/468#issuecomment-2252854372).

![Rectangle Actions](https://github.com/user-attachments/assets/408a0fe7-9b95-46e1-a374-2a7ab7d44c2d)

There’s a repository that implements this feature well: [Rectangle Pro for Raycast](https://github.com/bfmatei/rectangle-pro-raycast), though it’s not yet available on the Raycast store.

### Who will benefit from this feature?

This feature would be especially valuable for macOS users, given the improvements introduced with Cascade version 2. More details can be found in this [discussion](https://github.com/rxhanson/RectanglePro-Community/issues/468#issuecomment-2252854372).

### Anything else?

For additional context, you can explore the [Rectangle Pro Community](https://github.com/rxhanson/RectanglePro-Community).

@rxhanson Maybe could help?

**Comment by crickford** [comment]
Hey @bigplayer-ai! I finally had a chance to get around to this, support for cascade actions is incoming (see #16281)
