### ISSUE TITLE
The official expansion of ChatGPT, custom API queries have serious errors.

### ISSUE THREAD

**Issue by eachann1024** [raycast/extensions#13980]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Raycast Version

1.80.0

### macOS Version

15 bate4

### Description

There is a serious problem. When I choose a custom API and define the prompts, every time I ask a question, it only responds with my prompts and doesn't bring up my question. 

**I've tested the API in many places and it's not the problem.** 

Please see the gif. (Click to view the GIF)

![Image 2024-08-12 at 18 44 28](https://github.com/user-attachments/assets/1ca7e47f-0cee-4e95-a91c-3786936e7832)

### Steps To Reproduce

Refer to the gif animation above

**Comment by husniadil** [comment]
Here are some ways to reproduce the issue:

1. Open a PDF file and attempt to execute one of the commands from the extensions, such as "Ask Question" from ChatGPT, "Fix Spelling and Grammar" from Groq, or "Fix Spelling and Grammar" from Google Gemini.
2. Open the official ChatGPT app from OpenAI and try launching those commands.
3. Open other apps, ensuring they focus on non-text content, for example, the Apple Photos app, etc.

**Comment by husniadil** [comment]
@eachann1024 Although there is an error displayed in this extension (ChatGPT), it still provides accurate responses. I can obtain the answer using the same prompt, and the response appears above the question.

<img width="340" alt="Screenshot 2024-08-12 at 22 05 33" src="https://github.com/user-attachments/assets/23d6dc78-509f-49bf-ab31-986d2834965d">

Your question: hello your version
AI answer: Understood. How can I assist you today?

If that is what you mean by "the problem," I don't think it's related to either Raycast or the ChatGPT extension.

Please take a look on this official ChatGPT app:

<img width="1032" alt="Screenshot 2024-08-12 at 22 08 49" src="https://github.com/user-attachments/assets/c719a4ec-1f05-4e88-b912-bfa634f9ab66">

**Comment by eachann1024** [comment]
> @eachann1024 Although there is an error displayed in this extension (ChatGPT), it still provides accurate responses. I can obtain the answer using the same prompt, and the response appears above the question.
> 
> <img alt="Screenshot 2024-08-12 at 22 05 33" width="340" src="https://private-user-images.githubusercontent.com/10581130/357100368-23d6dc78-509f-49bf-ab31-986d2834965d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NzAwMTAsIm5iZiI6MTcyMzU2OTcxMCwicGF0aCI6Ii8xMDU4MTEzMC8zNTcxMDAzNjgtMjNkNmRjNzgtNTA5Zi00OWJmLWFiMzEtOTg2ZDI4MzQ5NjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE3MjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1Yjg5MDE4ZGU4YzJhMDM3NTkwZGJjYTUxMTQwM2I3YzNkNzdmZTkzZGE2ZjFiOTgyNzllNWFkMTJkZmY0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HTrwG-wNTJr3iVoNoIIDvaSIkrHoOa9E0xW_q7B2zNk">
> **Your question**: hello your version **AI answer**: Understood. How can I assist you today?
> 
> If that is what you mean by "the problem," I don't think it's related to either Raycast or the ChatGPT extension.
> 
> Please take a look on this official ChatGPT app:
> 
> <img alt="Screenshot 2024-08-12 at 22 08 49" width="1032" src="https://private-user-images.githubusercontent.com/10581130/357101724-c719a4ec-1f05-4e88-b912-bfa634f9ab66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NzAwMTAsIm5iZiI6MTcyMzU2OTcxMCwicGF0aCI6Ii8xMDU4MTEzMC8zNTcxMDE3MjQtYzcxOWE0ZWMtMWYwNS00ZTg4LWI5MTItYmZhNjM0ZjlhYjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE3MjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YTc2MTEyZTdmY2FmMWJlMmE1MTUwOWU4NTIzMWE2Yjc1MWE1Y2ZjOGQ2NzkwYjdmYjNkZGQyOWFjOWQ2ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UutFvkHKiPJgVD_qsaMjbboqYRYU4O4Y0yxhmLUaf-E">
> I requested the ChatGPT official app to respond in a shorter and less detailed manner, and that was the output. It answered with:
> 
> > "Hi! What do you need help with?"
> 
> Basically, the same pattern with yours:
> 
> > Understood. How can I assist you today?


https://github.com/user-attachments/assets/9852ab28-3dd1-4a40-9dfb-199cdb0380f8

Same answer if you ask a different question.
