### ISSUE TITLE
[WHOOP] issue connecting to whoop api

### ISSUE THREAD

**Issue by theurbandev** [raycast/extensions#13982]
### Extension

https://www.raycast.com/josha1len/whoop

### Raycast Version

1.69.0

#### Error:
```
Ue: request to https://whoop.oauth.raycast.com/token failed, reason: self-signed certificate in certificate chain

ClientRequest.<anonymous>:index.js:108:10

---
105:

### Steps To Reproduce

1. run a whoop cmd from Raycast (whoop account not connected)
2. auth with whoop api
3. open raycast and rerun whoop cmd
4. error

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by theurbandev** [comment]
has the maintainer abandoned this extension?  :(

**Comment by Josha1len** [comment]
Hi @theurbandev. Sorry for not getting back to you sooner.

I have just submitted an update to the WHOOP extension (in review):
- Authentication now uses OAuthService from Raycast utilities.
- Updated all dependencies to their latest compatible versions. 

I'm hoping these updates will resolve the authentication issue you reported.

Thanks!

**Comment by theurbandev** [comment]
Thanks for fixing the issue!
