### ISSUE TITLE
[Raycast Wallpaper] ...

### ISSUE THREAD

**Issue by jezkline** [raycast/extensions#13998]
### Extension

https://www.raycast.com/koinzhang/raycast-wallpaper

### Raycast Version

1.80.0

### macOS Version

15.1

### Description

I have Raycast set to auto-change my wallpaper and cycle through Raycast wallpapers every 5 minutes. However, every so often I get an "Error Setting Wallpaper" message. It says: Please make sure you have given Raycast the required permission. To make sure, click the button below and grant Raycast the 'System Events' permission. But I hae given Raycast the required permission and it still automatically changes the Wallpaper as expectd. So not really broken, just kinda annoying. Figured I'd report it anyway.

### Steps To Reproduce

Not sure. It just happens randomly during the course of the day. I've uploaded my log here, which was stopped right after I got the error: https://dropover.cloud/8c0e50

**Comment by koinzhang** [comment]
Thanks for the feedback, have submitted a PR #14711 to fix the issue!

**Comment by koinzhang** [comment]
@raycastbot close this issue
