### ISSUE TITLE
[Spotify Player] ...Your Library command shows only a very small portion of my library

### ISSUE THREAD

**Issue by Infrabass** [raycast/extensions#14000]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.80.0

### macOS Version

14.4.1

### Description

The Library command shows only a very small portion of my library.
While searching my library I can't find artists I'm following while the official Spotify app can.
Same with albums, songs, etc

### Steps To Reproduce

1. Run the Library command
2. Search artists you are following
3. Observe that the extension can't find them

### Current Behaviour

Can only find a small portion of our Spotify library

### Expected Behaviour

Can search through our whole Spotify library

**Comment by albertograu** [comment]
I confirm I experience the same behavior.

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/7222, so I'll mark it as such.
