### ISSUE TITLE
Bitwarden

### ISSUE THREAD

**Issue by voleursavage** [raycast/extensions#14015]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Raycast Version

1.80.0

### macOS Version

14.4

### Description

(node:5046) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Invalid master password.

### Steps To Reproduce

Fresh install on a new Mac

### Current Behaviour

Unable to unlock vault

**Comment by jluo98** [comment]
The bitwarden-cli hosted on homebrew is outdated (`2024.6.1`). The latest version (`2024.7.2`) does not have the error and the extension works again. 

You'll need to uninstall bitwarden-cli via homebrew. Then manually install the latest binary or use npm to install the latest version, and update the CLI path in Raycast settings. 

See [Password Manager CLI | Bitwarden Help Center](https://bitwarden.com/help/cli/#download-and-install)

**Comment by jomifepe** [comment]
Assuming the suggestion fixed the issue, feel free to reopen otherwise.

@raycastbot close this issue
