### ISSUE TITLE
[Auto Quit App] Refresh Interval

### ISSUE THREAD

**Issue by davewehr** [raycast/extensions#14023]
### Extension

https://www.raycast.com/koinzhang/auto-quit-app

### Description

I am coming from SwiftQuit which would quit the app almost immediately after the last window was closed. I see the most frequent refresh interval for Auto Quit is 5 minutes--is this a resource issue, to have it check more often? Would it be possible to shorten down to say, 30 seconds?

### Who will benefit from this feature?

This might attract more people that are currently using SwiftQuit

**Comment by Hydro8** [comment]
Yes indeed it will be super cool if the app can quit when we close the last window of the app.

**Comment by koinzhang** [comment]
Thanks for your feedback, currently reducing the minimum detection interval to 1m in #14689, not to seconds because of performance considerations.

**Comment by Hydro8** [comment]
Thanks. However, is it possible to have an option to close only if there’s no window open for the app ?

Sometime I open word in the background and check later something inside. But word is quit before 😕

thanks for your work.

**Comment by koinzhang** [comment]
If you are within the same desktop, it will automatically detect if the application individual has a window.
However, if you are on a different desktop, the application will not detect the presence of windows (the number of windows recognised is 0) and will therefore close by default. (I have not been able to find a better solution for this bug.)

Auto Quit App [README](https://www.raycast.com/koinzhang/auto-quit-app#readme)

<img width="886" alt="image" src="https://github.com/user-attachments/assets/aaa5cc48-33c6-482f-b17f-a9bc04071643">

**Comment by Hydro8** [comment]
Thanks I didn't see that. Indeed it work as expect.
I guess is not possible to check when you close a window of an app with a raycast extension.

**Comment by davewehr** [comment]
Thanks for the update!!Sent from my iPadOn Sep 27, 2024, at 5:37 AM, koin ***@***.***> wrote:﻿
If you are within the same desktop, it will automatically detect if the application individual has a window.
However, if you are on a different desktop, the application will not detect the presence of windows (the number of windows recognised is 0) and will therefore close by default. (I have not been able to find a better solution for this bug.)
Auto Quit App README
image.png (view on web)
