### ISSUE TITLE
[JetBrains Toolbox Recent Projects] CPU unusually high

### ISSUE THREAD

**Issue by aesadde** [raycast/extensions#14035]
### Extension

https://www.raycast.com/gdsmith/jetbrains

### Raycast Version

1.81.0

### macOS Version

14.5

### Description

Raycast is using a lot of CPU time. Logs indicate that the menu bar command is constantly 
![CleanShot 2024-08-15 at 10 10 11@2x](https://github.com/user-attachments/assets/490818bf-aca0-48da-87df-82faf01cbf28)

![CleanShot 2024-08-15 at 10 18 06@2x](https://github.com/user-attachments/assets/7cc20c40-9e8c-48b2-ac37-333ad41e27a2)

### Steps To Reproduce

1. Open Raycast
2. Activate the JetBrains "Open Recent Projects" Menu bar

**Comment by gdsmith** [comment]
Logs look like Raycast is switching between light and dark mode, not sure why that would be though

**Comment by aesadde** [comment]
@gdsmith weird indeed but turning off the extension menu bar fixed the issue. 

I'm using these tools
![CleanShot 2024-08-15 at 11 40 48@2x](https://github.com/user-attachments/assets/248e6271-9aad-4a2a-b4e8-5dd986f29043)
