### ISSUE TITLE
Add comma separation for numbers while typing in RayCast

### ISSUE THREAD

**Issue by mattcantstop** [raycast/extensions#14031]
### Description

In the included image you can see that I am typing a large number. In Alfred while the number is typed it would add commas to make parsing the number mentally a bit easier as you type. I miss this feature and would love to see it added to Raycast. Otherwise you need to be counting how many zeros you are typing while you type it, instead of just watching the number build in the preview screen a bit below. 

![image](https://github.com/user-attachments/assets/f7b4ef8c-1c10-4542-875e-df3056a5718b)

### Who will benefit from this feature?

Users generally who use numbers in Raycast.

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
