### ISSUE TITLE
[GitHub] Searching for Repositories is throwing an error

### ISSUE THREAD

**Issue by brentonmcs** [raycast/extensions#14032]
### Extension

https://www.raycast.com/raycast/github

### Raycast Version

1.18.0

### macOS Version

14.6.1

#### Error:
```
Error: Could not store Cache data for key "history": Error: Minified React error #185

### Steps To Reproduce

I'm getting this every 3-5 times when I'm searching for a private repository.

To reproduce:
1. open Raycast
2. type my alias for GitHub search 
3. error pops up.

### Current Behaviour

_No response_

### Expected Behaviour

A list of my repositories

**Comment by thomaslombart** [comment]
Could you share a recording? It'll make it easier to see what's happening.

**Comment by FelixLisczyk** [comment]
Here's a quick screen recording of the crash. It happens shortly after running the "Search Repositories" command (I'm using the `gh` alias). One difference I've noticed is the appearance of a "Visited Repositories" section at the top. This section does not appear when the extension runs normally (without crashing). I've posted the crashing line of code in issue #14344.

https://github.com/user-attachments/assets/ccfefe0a-bece-4043-91c5-09be70a4dd2d

**Comment by thomaslombart** [comment]
This is probably due to a caching issue occurring in the extension's storage. I'm not sure what went wrong here, but in the meantime, uninstalling and reinstalling the extension should be sufficient.

**Comment by ppawlowski** [comment]
> This is probably due to a caching issue occurring in the extension's storage. I'm not sure what went wrong here, but in the meantime, uninstalling and reinstalling the extension should be sufficient.

Reinstallation of the extension didn't solve the problem for me.

**Comment by FelixLisczyk** [comment]
After reinstalling the extension, it worked for a few days, but the crash still happens. The issue seems to occur when there are multiple entries in the "Visited" section. The order sometimes changes shortly after the repository list appears, and then the extension crashes.

**Comment by thomaslombart** [comment]
Thanks for your valuable input! It allowed me to reproduce the bug and fix it.

**Comment by FelixLisczyk** [comment]
Thank you, @thomaslombart! I've noticed that the order in the "Visited Repositories" section changes each time I open the extension. However, there haven't been any crashes so far. 👍
