### ISSUE TITLE
[Raycast Icons] AI Icon Search

### ISSUE THREAD

**Issue by not-first** [raycast/extensions#14043]
### Extension

https://www.raycast.com/petr/raycast-icons

### Description

The current behaviour only searched the icons by their name.

A beneficial feature would be to implement simply AI suggestions as well. This would operate the same to how AI emoji searching functions, where icons similar or related to the search queries concepts would be returned.

### Who will benefit from this feature?

This feature can make it easier to identify appropriate icons to use in certain scenarios. The AI suggestions can help to find emojis that fit in a scenario but may not be returned in the usual name search.

For example, in normal behaviour, searching for beach returns nothing.
In this new behaviour, the AI suggestions section could return the umbrella, the sun ...

It would also feel familiar to pro users due to the similarity it would have to the emoji picker's behaviour.

**Comment by xilopaint** [comment]
This was implemented by #14045. Please let me know if you face any problems.

<img width="886" alt="Screenshot 2024-08-18 at 06 24 58" src="https://github.com/user-attachments/assets/5b76baae-8ad5-4a50-bb1c-20ba4bf55e69">

@raycastbot close this issue
