### ISSUE TITLE
[Cobalt] Deprecated API

### ISSUE THREAD

**Issue by Apope1999** [raycast/extensions#14044]
### Extension

https://www.raycast.com/aelew/cobalt

### Raycast Version

1.81.0

### macOS Version

14.5 (23F79)

### Description

Error Message when trying to download any YouTube video:
```
An unexpected error occurred
this api domain is deprecated. use the https:// cobalt.tools/ web app, host your own api instance, or update the main cobalt api domain you use.
```

### Steps To Reproduce

1. Install the extension via the Raycast Store
2. Copy and paste any YouTube link (Optional: Set mode to Audio)
3. Start download

**Comment by senoe** [comment]
@raycastbot assign me

**Comment by aelew** [comment]
@raycastbot assign me
