### ISSUE TITLE
[Clean Keyboard] ...simply doesn't work. It could be my fault, but...

### ISSUE THREAD

**Issue by kynkos2** [raycast/extensions#14072]
### Extension

https://www.raycast.com/ike-gg/clean-keyboard

### Raycast Version

1.8.1.1

### macOS Version

14.6.1

### Description

It´s a great idea this extension... but doesn't work
I set it up in every option, but the keyboard still responses to inputs

### Steps To Reproduce

1. Open Raycast
2. toggle the extension
3. usually for a minute
4. I clean the keyboard, but both trackpad and keyboard run, not locked

### Current Behaviour

Keyboard unlocked

### Expected Behaviour

keyboard. locked for cleaning

**Comment by getdekoded** [comment]
So I had the same issue, had to give raycast accessibility access for the extension to work. Perhaps try that?

**Comment by kynkos2** [comment]
Thank you so much for your suggestion, IT WORKS!.

Álvaro
mailto: ***@***.***
Sent with Spark
