### ISSUE TITLE
[Google Translate] Add translate selected text command 

### ISSUE THREAD

**Issue by zd4r** [raycast/extensions#14076]
### Extension

https://www.raycast.com/gebeto/translate

### Description

Can you please add "translate selected text" command? Same as "Send selection to AI chat" but for translate

**Comment by LitoMore** [comment]
The `Quick Translate` command has already implemented this feature.

**Comment by gebeto** [comment]
This is already exists, all you need is just add hotkey to quickly open translate to run the translate, for me it is `CONTROL+T`

https://github.com/user-attachments/assets/08af8491-72f1-451b-83f1-914e74f6aca2

**Comment by LitoMore** [comment]
Closing due to this feature already exists.
