### ISSUE TITLE
[Color Picker] There's no way to remove the eye dropper icon from the macOS menu bar with a Raycast command

### ISSUE THREAD

**Issue by lord-reptilia** [raycast/extensions#14081]
### Extension

https://www.raycast.com/thomas/color-picker

### Raycast Version

1.81.1

### macOS Version

14.5

### Description

This raycast command should toggle on/off the extension's menu bar icon, not just activate it.

extensions/color-picker/src/menu-bar.tsx

Hi there! Love your great work and I'm very impressed about how complete this extension is. I just have this observation.

### Steps To Reproduce

When hitting enter to the **Menu Bar Color Picker** command from the Raycast command window, it only allows to add the eye dropper icon to the macOS menu bar over and over again.

### Expected Behaviour

To remove the eye dropper icon from the macOS menu bar when hitting enter to the same Raycast command that activated it. (with an option to add it back again with the same raycast command window)

**Comment by ridemountainpig** [comment]
@lord-reptilia The command `Deactivate Menu Bar Item` in the action can deactivate a menu bar command.

![CleanShot 2024-08-20 at 20 27 08@2x](https://github.com/user-attachments/assets/fa435c98-9824-4c59-8842-0164bbce25fd)

**Comment by lord-reptilia** [comment]
Hi!

Yeah, I know how to deactivate the Menu Bar Item,

However, the current design is quite inconvenient, and it would be greatly appreciated if this **deactivation could be as simple as hitting enter to the same command** that activated it.

Could a "Toggle Menu Bar Item **Command**" be considered to be offered?

Thank you for your review and consideration!

**Comment by LitoMore** [comment]
> Could a "Toggle Menu Bar Item Command" be considered to be offered?

No. It is better not add too many commands to the extension. There are enough commands now. I don't want the plugin to become a mess.

**Comment by lord-reptilia** [comment]
Hello Lito,

The current design is already inconvenient from my experience.

This is not a request for an additional command:

> **Expected Behaviour**
> To remove the eye dropper icon from the macOS menu bar when **_hitting enter to the same Raycast command that activated it._** 

For your consideration.
