### ISSUE TITLE
[Todoist] Focus workspace

### ISSUE THREAD

**Issue by rpuncel** [raycast/extensions#14091]
### Extension

https://www.raycast.com/doist/todoist

### Description

Add the ability to focus on one workspace globally within the Todoist extension. I'd like this to work like a toggle - perhaps a command that can be used to quickly set or unset the workspace. If a workspace filter is set, each Todoist command should automatically filter to only only projects and tasks within the workspace.

### Who will benefit from this feature?

Folks using Todoist for personal task management as well as work task management. E.g., during the work day folks may not want to see all the tasks they have to do in their personal life.  Conversely, I don't want to see work tasks when I am off the clock.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? If yes, here's our [guide on extension contributions](https://developers.raycast.com/basics/contribute-to-an-extension) so that you can open up a pull request. Feel free to contact me here or in the [Slack community](https://raycast.com/community) if you need further help.

**Comment by rpuncel** [comment]
> Thanks for the feature request. Would you like to work on it? If yes, here's our [guide on extension contributions](https://developers.raycast.com/basics/contribute-to-an-extension) so that you can open up a pull request. Feel free to contact me here or in the [Slack community](https://raycast.com/community) if you need further help.

I will give it a shot, but I will be very slow :D If this is hangs around for a long time and someone would like to pick it up, they should feel free.
