### ISSUE TITLE
[Apple Mail]...not pulling all  the inboxes in multiple accounts in mail app

### ISSUE THREAD

**Issue by passwordless-OTP** [raycast/extensions#14107]
### Extension

https://raycast.com/yug2005/mail

### Raycast Version

1.81.2

#### Error:
```
Error: Command timed out after undefined milliseconds: osascript
Timed out
    at Timeout._onTimeout (/Users/jarvis/.config/raycast/extensions/9abdb4fc-f5ee-4ee8-ade4-2296de586cef/see-recent-mail.js:8:322615)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

### Steps To Reproduce

<img width="774" alt="image" src="https://github.com/user-attachments/assets/3e9c18e9-a55c-44cf-868c-8cc10670d6be">

### Current Behaviour

got 4 accounts in my mail app of MacBook. I see it pulling some other folder such as "draft" "important". however when I do recent mails command it times out.

### Expected Behaviour

either pull the mails or give a recommendations how to fix that.

**Comment by jfkisafk** [comment]
@passwordless-OTP We made a few changes in [#](https://github.com/raycast/extensions/pull/13938) that can cause this:
1. Earlier any errors from `osascript` were being swallowed and now they are exposed. But if the commands were working for you earlier then I don't suspect this is an issue as you wouldn't have seen any messages in "Recent Mail" command (w/o any error)
2. The "Message Limit" preference was not being applied to "Recent Mail" command. Earlier the `osascript` was only retrieving first 10 messages per account and then slicing the first 5 of those 10 to render the List. Now, `osascript` will retrieve messages based on the "Message Limit" preference and if it is large (and your message sizes are also large), I suspect that can cause a timeout. Can you try setting the "Message Limit" preference to 10?

**Comment by uzairansaruzi** [comment]
ive set Message limit to 10 and 5 also but still keep getting the osascript error

**Comment by jfkisafk** [comment]
> ive set Message limit to 10 and 5 also but still keep getting the osascript error

Hmm I am not sure why it is saying `undefined timeout`, when the default value is 10 sec. Anyways, I am trying to increase the timeout to 30 sec to see if that helps.

**Comment by jfkisafk** [comment]
@raycastbot assign me
