### ISSUE TITLE
[DevDocs]: Support for syncing enabled or disabled document sets

### ISSUE THREAD

**Issue by manishrc** [raycast/extensions#14101]
### Extension

https://www.raycast.com/djpowers/devdocs

### Description

DevDocs supports over 600 documentation sets, which can be overwhelming when searching. To address this, DevDocs allows users to control which documentation sets are enabled or disabled.

![CleanShot 2024-08-20 at 11 39 57@2x](https://github.com/user-attachments/assets/c0317259-f898-42a4-a95c-3b60276b51f7)

However, because of this fabulous Raycast extension, search entry points often happen from the extension, rather than the DevDocs interface. Unfortunately, this means that disabled documentation sets are still displayed in the search results.
![CleanShot 2024-08-20 at 11  44 24@2x](https://github.com/user-attachments/assets/30c1674a-10c7-44dd-8cab-3f2e160950de)

It would be ideal if the Raycast extension could only show the enabled documentation sets, or at least sort them into two lexical groups: enabled and disabled.

### Who will benefit from this feature?

Almost everyone who uses DevDocs regularly would benefit from seeing less noise.

**Comment by djpowers** [comment]
Good suggestion @manishrc! Funny enough, I was just playing with some ideas related to this over the weekend. The separate sections can be accomplished using [`List.Section`](https://developers.raycast.com/api-reference/user-interface/list#list.section). 

My thought was to leverage the "export" feature available from the DevDocs settings page: https://devdocs.io/settings

This outputs a JSON file looking like so:
```json
{
  "docs": "css/html/http/javascript/ruby~3/dom"
}
```
Ideally this could be imported in the extension to mirror the documentations used on the web. I would probably default to what the web version of DevDocs enables (CSS, HTML, HTTP, JavaScript, Web APIs), possibly also including React and TypeScript to cater to the Raycast audience. This could likely be kept in local storage, and modified with add/remove actions.

The "enabled" documentations could be grouped in the top section. The remaining items could be placed in the lower section, similar to how the DevDocs sidebar displays them:
![CleanShot 2024-08-20 at 21 26 56@2x](https://github.com/user-attachments/assets/ca2b3273-2396-4346-aaef-de0ca8001958)

I envision that as more of a "preferred" or "favorites" section. If the extension evolves to support offline docs or searching multiple documentation sets at once, then it could make sense to officially support the notion of enabled/disabled states.

**Comment by djpowers** [comment]
@raycastbot assign me
