### ISSUE TITLE
[Timers] Menu Bar Item doesnt disappear

### ISSUE THREAD

**Issue by Euro3000** [raycast/extensions#14114]
### Extension

https://www.raycast.com/ThatNerd/timers

### Raycast Version

1.81.2

### Description

Running a timer, after it's finished, it wont dissappear from the menu bar.
<img width="85" alt="Bildschirmfoto 2024-08-21 um 08 54 29" src="https://github.com/user-attachments/assets/7fa9d7a0-6b8f-400a-923a-a808df1573fd">

### Steps To Reproduce

1. Run a timer
2. wait for it to end
3. for 2-3 secs it starts counting up
4. not disappearing from the menu bar

**Comment by ThatNerdSquared** [comment]
Hi @Euro3000, thanks for using Timers!

A couple questions to help with debugging:
- Do you have the "Ring Continuously" preference checked in the Raycast Settings for this extension? (should be checked by default)
- When this happens, does opening the menu bar item (clicking on it to show the full menu) make the timer disppear?
- When this happens, is the timer also present in the "Manage Timers" command?

Thanks again.

**Comment by ThatNerdSquared** [comment]
This was fixed in Raycast v1.82.1 — updating to the latest version of Raycast should solve your issue :)

@raycastbot close this issue
