### ISSUE TITLE
[Menubar Calendar] ... Join meetings

### ISSUE THREAD

**Issue by vinschi** [raycast/extensions#14112]
### Extension

https://www.raycast.com/koinzhang/menubar-calendar

### Description

The extension works pretty well, but it's missing a convenient feature that other similar has, if the meeting in the calendar has a link for a video call, you can't join the call from there. Any chance you can add it? Also, you can't configure which calendars can be accessed so the menu bar can become pretty long if you have many calendars. Thanks!

### Who will benefit from this feature?

All the users

**Comment by koinzhang** [comment]
Thanks for the feedback, I'm adding a new feature that allows you to click to open the URL (if there is one) in the calendar event after pressing the Opt key, hope this helps.

**Comment by koinzhang** [comment]
In addition, a new command is now available: 

**Configure Calendar List**:  configure calendar and reminders list displayed in the menu bar.

Hope this helps.

@raycastbot close this issue
