### ISSUE TITLE
[Bitwarden Vault] ...

### ISSUE THREAD

**Issue by zeitig** [raycast/extensions#14123]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Raycast Version

1.81.2

### macOS Version

14.6.1

#### Error:
```
Error: Command failed with exit code 1: /opt/homebrew/bin/bw status
(node:4164) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/homebrew/Cellar/bitwarden-cli/2024.6.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:36503
                state.accounts[userId].profile = diskAccount.profile

### Steps To Reproduce

1. **I installed Bitwarden CLI using Homebrew:**
   ```bash
   brew install bitwarden-cli
   ```

2. **I configured the Bitwarden Vault extension in Raycast:**
   - Opened Raycast.
   - Went to the `Extensions` section.
   - Installed the **Bitwarden Vault** extension.
   - In the extension settings, specified the path to the Bitwarden CLI using the output from the `which bw` command.

3. **I generated and configured API keys:**
   - Created API keys in my Bitwarden account (or confirmed existing ones).
   - Entered these API keys into the Bitwarden Vault extension in Raycast.

4. **I returned to Raycast and attempted to unlock the vault:**
   - When prompted, I entered the same master password into the Raycast extension.

### Current Behaviour

- After entering the master password, an `Invalid master password` error is displayed, despite the same password working in the CLI.
- Additionally, the console logs a warning:
  ```
  (node:1338) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.
  ```

### Expected Behaviour
- The Bitwarden Vault should unlock successfully in Raycast.

**Actual Result:**

**Comment by Inteleweb** [comment]
same issue. MAC pro M1

**Comment by jomifepe** [comment]
Hey, you're most likely on CLI version 2024.6.1, which has an issue, please try updating. Refer to this comment: https://github.com/raycast/extensions/issues/13329#issuecomment-2238743439

**Comment by defPhisy** [comment]
same error:
"client_id or client_secret is incorrect. Try again."
versions i tried: 2024.6.0, .6.1, .7.2, .8.1
without success
cli login works without any problems

**Comment by dereknex** [comment]
```shell
❯ bw -v
(node:7551) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2024.8.1
```
try login in with master password, then copy last error as below:
```shell
(node:7673) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Invalid master password.
```

**Comment by jomifepe** [comment]
@defPhisy When you say
> cli login works without any problems

Do you mean with client id and secret? Or with password?
Is the extension pointing to the correct CLI path?

**Comment by jomifepe** [comment]
@dereknex Same as above, do you have any other CLI version installed? The `Bitwarden CLI Path` preference should be pointing to the same path as the `bw` you're using in your terminal. You can run `which bw` to check that.

**Comment by dereknex** [comment]
> @dereknex Same as above, do you have any other CLI version installed? The `Bitwarden CLI Path` preference should be pointing to the same path as the `bw` you're using in your terminal. You can run `which bw` to check that.

Thanks for the reply, I tried logging out and trying again with no problem.

**Comment by defPhisy** [comment]
@jomifepe tried both:

1. cli with mail, password and otp works
2. cli with client_id and client_secret works
3. with `which bw` i took the cli path and pasted it into CLI Path field in your extension
4. your extension asks for master pw
5. typing my master pw throws error: `client_id or client_secret is incorrect. Try again.`

My setup:
- M2 Macbook Air with Sonoma `14.6.1`
- bw cli `2024.8.1`
- installed bw cli with npm, because bitwarden suggest to install it not via homebrew
- npm `10.7.0`

**Comment by jomifepe** [comment]
Hard to tell what the issue is, I'm not aware of a bug around incorrect client id or secret. 
That said, please check if those are correct (no leading or trailing spaces). As a last resort, try reinstalling the extension to force clean every possible value.

**Comment by defPhisy** [comment]
@jomifepe: After a fresh install of everything it works now. Still don't know what the issue was but thanks for your help.

**Comment by jomifepe** [comment]
Cool, I will investigate what might be getting cached that prevents logging in.

**Comment by blacroix** [comment]
Try to uninstall the extension (keeping the bw CLI installed) then install back the extension. It ends up working for me that way.

**Comment by alvaroybanez** [comment]
@jomifepe came to ask about the "invalid master password", after forcing the which bw in the extension path, everything is working appropriately. 

Thanks. 🙏
