### ISSUE TITLE
[Background Sounds] ...

### ISSUE THREAD

**Issue by ImWalterGZ** [raycast/extensions#14126]
### Extension

https://www.raycast.com/SebDanielsson/background-sounds

### Raycast Version

1.81.2

### macOS Version

14.3

### Description

Error: Command failed with exit code 1: osascript
Background sound is on
Background sounds turned off
757:788: execution error: No matching processes belonging to you were found (1)

Background sound is on
Background sounds turned off
O9:run-applescript.js:38:21

---
35:         timedOut,
36:         command: "osascript",
37:         options,
38:         parentError: new Error(),
39:     });
40: }
41: exports.runAppleScript = runAppleScript;
---

### Steps To Reproduce

Stop bg sounds and play them again

### Current Behaviour

<img width="796" alt="Screenshot 2024-08-21 at 14 04 52" src="https://github.com/user-attachments/assets/d51b18e6-9107-46ff-b22c-a58a6ce41818">

### Expected Behaviour

start bg souds

**Comment by sebdanielsson** [comment]
Hi!

If you try to enable the sounds through settings, just toggle on or off. Does the command work after that?

If not, would you mind trying updating macOS to 14.6.1?

**Comment by srindom** [comment]
Having the same issue. 

For me I cannot toggle sounds on. If I toggle them on through system settings, I can toggle them off with the extension, but I cannot toggle them back on. 

I am on macOS 15.1 btw.

**Comment by sebdanielsson** [comment]
> Having the same issue.
> 
> For me I cannot toggle sounds on. If I toggle them on through system settings, I can toggle them off with the extension, but I cannot toggle them back on.
> 
> I am on macOS 15.1 btw.

Just upgraded to 15.0 and it stopped working for me too. I'll investigate this weekend😎

**Comment by sebdanielsson** [comment]
I've hit a brick wall trying to find a workaround. The script is rewriting the plist to enable background sounds properly; however, the current method to restart the service doesn't work anymore under macOS 15.0.

If anyone manages to find a workaround, please let me know. This can be tested locally by running these commands:

Enable background sounds:
`defaults write com.apple.ComfortSounds "comfortSoundsEnabled" -bool "true"`
Disable background sounds:
`defaults write com.apple.ComfortSounds "comfortSoundsEnabled" -bool "false"`
Restart the service/must be done to apply the config changes (currently broken in macOS 15.0:
`killall heard`

**Comment by sebdanielsson** [comment]
@raycastbot keep this issue open

**Comment by DeadliestCache** [comment]
I'm experiencing this issue on both Ventura and Sonoma.

I can toggle background sounds on and off with the command once. Raycast notifies in both cases.

When I manually toggle the switch back on, the command will then turn background sounds off and Raycast will notify.

When I run the command again after successfully turning the sounds off with it, there is no notification, which seems accurate since the sounds did not turn back on, HOWEVER the sounds will turn on once I quit System Settings, reopen it, and reselect the Accessibility section.

In most cases the command doesn't toggle the switch position and the switch position doesn't reflect the actual state.

**Comment by awerks** [comment]
Fixed with #15513

**Comment by sebdanielsson** [comment]
> Fixed with #15513

Thank you!

@raycastbot close this issue
