### ISSUE TITLE
[Arc]... does not work for searching tabs still

### ISSUE THREAD

**Issue by agdfoster** [raycast/extensions#14122]
### Extension

https://raycast.com/the-browser-company/arc

### Raycast Version

1.81.2

### macOS Version

Sonoma 14.3

#### Error:
```
Error: Command timed out after undefined milliseconds: osascript
Timed out
    at Timeout._onTimeout (/Users/dev/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:8:319920)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

### Steps To Reproduce

There is no connection instructions so it should just work, but doesn't! It never has.

### Current Behaviour

Searching tabs etc does nothing

### Expected Behaviour

Searching tabs DOES something.

**Comment by agdfoster** [comment]
Thank you!

**Comment by agdfoster** [comment]
This still isn't working, why is it marked completed?

**Comment by xilopaint** [comment]
> This still isn't working, why is it marked completed?

Strange, it shouldn't happen.

@raycastbot reopen this issue

**Comment by agdfoster** [comment]
It times out after undefined milliseconds, can't take screenshot so
reported bug for the info
https://github.com/raycast/extensions/issues/14231
