### ISSUE TITLE
[ChatGPT] extension corrupted and all my custom models got deleted - help

### ISSUE THREAD

**Issue by turnipsforme** [raycast/extensions#14125]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Raycast Version

1.81.2

### Description

Is there a way to recover my custom models? I tried looking through the extension config using FindAnyFile and couldn't find where the models are stored. I had lots of models that I spent a while making, would be amazing to be able to find the text files for them!

### Steps To Reproduce

not sure what caused it to corrupt, it just stopped letting me interact with the extension (all options came up blank)

**Comment by mormubis** [comment]
I have the same issue. I cannot create new models.

**Comment by pernielsentikaer** [comment]
That does sound weird, and you're not getting any errors at all?

**Comment by mormubis** [comment]
Nope, for me, suddenly, it was using GPT 3.5 when I had two models with 4o and two different prompts. I needed to reinstall the extension to make it work.

I saw no models in the models view, and I couldn't create any, even though it says Cmd + T to create a model.

**Comment by jwhazy** [comment]
Finding this happens once I reach a certain amount of conversations. Has happened a couple times now.
