### ISSUE TITLE
[GitHub] Cache repositories for faster search

### ISSUE THREAD

**Issue by DonDebonair** [raycast/extensions#1412]
# Extension – [GitHub](https://github.com/raycast/native-extensions/tree/4727942f956f19fedb74e7a4ff7c6904bb960fd6/extensions/github/)
Author:

**Describe the feature and the current behavior/state.**

When I search repositories, the extension currently always seems to hit the Github API. The results never show up immediately, but it takes a couple of seconds, even for searches I have done before. I would be really nice if the extension would remember/cache my own repositories (also the private ones) so that it can show those immediately when searching.

After showing the cached/remembered repositories, it should still keep searching and refreshing the data to remove any stale repos

**Who will benefit with this feature?**

Any user that wants to access their own repos quickly

**Comment by koinzhang** [comment]
Hi @DandyDev 👋
This extension may meet your needs. [GitHub Repository Search](https://www.raycast.com/thomas/github-repository-search)

**Comment by DandyDev** [comment]
> Hi @DandyDev 👋 This extension may meet your needs. [GitHub Repository Search](https://www.raycast.com/thomas/github-repository-search)

I tried that one, but it will search through _all_ Github repositories. I only want to search through my own

**Comment by DonDebonair** [comment]
Is this something the Raycast developers can look into?

**Comment by DonDebonair** [comment]
@thomaspaulmann that would be great! Than I can switch to that extension

**Comment by thomaspaulmann** [comment]
It caches the repos that you visit. So if you visited a repo once (regardless if it's your own or another one), it will stay in recently visited repos. And it has actions to open the PR, issues, and other pages of a repo directly. Give it a try and let me know how you like it.

**Comment by jberglinds** [comment]
> We could add a dropdown to the GitHub Repository Search extension to either search all or only your repositories?!

Added in here: https://github.com/raycast/extensions/pull/2266
