### ISSUE TITLE
[Apple Notes] ...

### ISSUE THREAD

**Issue by weha-cai** [raycast/extensions#1414]
# Extension – [Apple Notes](https://github.com/raycast/extensions/tree/fb95bd1b49764c37de7cd9ffd1c8384f45877380/extensions/apple-notes/)
Author: @tumispro

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.32.1

**Comment by mathieudutour** [comment]
Please fill up the template and re-open
