### ISSUE TITLE
[YouTube Downloader] unable to complete downloads

### ISSUE THREAD

**Issue by alexpmarsh** [raycast/extensions#14159]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

1.81.2

### macOS Version

14.6.1 (23G93)

### Description

Download fails while downloading clip.

https://share.cleanshot.com/10xPctCs

https://github.com/user-attachments/assets/5a3f8183-03a4-4080-a86e-a0bdebce37bc

### Steps To Reproduce

1. initiate raycast launcher
2. choose YouTube Downloader extension
3. Enter Youtube URL
4. Select download clip

https://github.com/user-attachments/assets/49ef4cb7-c636-494f-985d-d1304da09699

### Current Behaviour

Download fails before it is complete

### Expected Behaviour

Download to complete and save to the predefined directory for downloads.

**Comment by vimtor** [comment]
We are using an unofficial YouTube API, and it can be flaky sometimes. Does it happen always?

**Comment by davidcodoe** [comment]
yes it happend to me today everytime i used it 
and today was the first time of trying it :(
