### ISSUE TITLE
[Anki] ...Error: Worker terminated due to reaching memory limit: JS heap out of memory  [kOnExit]:worker:313:26 Worker.<computed>.onexit:worker:229:20

### ISSUE THREAD

**Issue by fwends** [raycast/extensions#14150]
### Extension

https://www.raycast.com/anton-suprun/anki

### Raycast Version

1.81.2

### macOS Version

14.5 (23F79)

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

browse cards

### Current Behaviour

Error: Worker terminated due to reaching memory limit: JS heap out of memory

[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20

### Expected Behaviour

for it to work

**Comment by anton-suprun** [comment]
Hi 👋 

Thanks for raising the issue! 

I'm aware of the problem (someone else created this issue recently on my GitHub repo).

We have a fix in progress. 

Cause of issue:

When browsing cards ( Browse Cards command) for large collections we exceed the memory limit. In order to fix this I have a fix to add pagination to the cards browser!

Expect a resolve within the week :) 

Sorry for the delay

**Comment by anton-suprun** [comment]
@fwends to confirm my theory, could you share how many cards you have in total in your collection ?

**Comment by fwends** [comment]
I don't see anywhere that gives me that info, but i would say 1-2k

**Comment by anton-suprun** [comment]
> I don't see anywhere that gives me that info, but i would say 1-2k 

Thanks for checking!

I'll work on a fix in the next couple days! Thanks again for bringing this to my attention

**Comment by anton-suprun** [comment]
Hi,

Just wanted to provide an update; didn't have time to work on it last two weeks but have time tomorrow 👍 
Sorry for the delay

**Comment by anton-suprun** [comment]
Hi @fwends 👋 

Have a PR with a fix ready; thanks again for helping me debug this :)

**Comment by anton-suprun** [comment]
Hi 👋 

The fix was merged. 
It should resolve the issue you're having. 

Closing ticket 


(Feel free to re-open ticket if the issue persists after the change)

**Comment by fwends** [comment]
That is now working as it should it's really nice to use too.
