### ISSUE TITLE
[Jotoba — Japanese Dictionary] ...

### ISSUE THREAD

**Issue by mchen132** [raycast/extensions#14161]
### Extension

https://www.raycast.com/clnhs/jotoba

### Raycast Version

1.70.2

### Description

Search is not returning any result for any input language. 
The office website: jobota.de and jobota.com do not seem to load. 

### Steps To Reproduce

1. search anything in Jobota extension
2. No result returned.

**Comment by clnhs** [comment]
@mchen132 

Thank you for using this extension, and for the bug report!

The issue has been reported upstream already by someone else in Jotoba's repository (see WeDontPanic/Jotoba#49) and has been reported in their Discord as well.

**Comment by mchen132** [comment]
> @mchen132
> 
> Thank you for using this extension, and for the bug report!
> 
> The issue has been reported upstream already by someone else in Jotoba's repository (see [WeDontPanic/Jotoba#49](https://github.com/WeDontPanic/Jotoba/issues/49)) and has been reported in their Discord as well.

@clnhs 
Thank you for the prompt response!
The issue seems to be resolved already, based on your above [linked issue](https://github.com/WeDontPanic/Jotoba/issues/49). 
I will close this issue now 👍

**Comment by mchen132** [comment]
Issue resolved: https://github.com/WeDontPanic/Jotoba/issues/49
