### ISSUE TITLE
youtube-music : controlling normal youtube instead of youtube music in chrome

### ISSUE THREAD

**Issue by ashsuper18** [raycast/extensions#14183]
### Extension

https://www.raycast.com/danieldbird/youtube-music

### Raycast Version

1.81.2

### macOS Version

14.6.1

### Description

Hey,

When I have YouTube open in one tab and I’m playing music on YouTube Music in another, the extension doesn’t work properly. It controls YouTube instead of YouTube Music.

I tried creating a web app for YouTube Music and assigning the controls to that app, but it didn’t help. I also tested this in Safari and Edge, but the controls don’t work in the web app player for YouTube Music.

Could you please check into this?   I’d appreciate your help.

Thanks!

I am using Chrome: Version 127.0.6533.120 (Official Build) (arm64)

### Steps To Reproduce

No Comment

### Current Behaviour

Working for Normal Youtube (if youtube tab is open)

### Expected Behaviour

No Comment

**Comment by gnosticdev** [comment]
Try putting the one you want to control ahead of the other. It scans all tabs and plays the first it finds with a YouTube url of any kind. 

I suppose a check for music.youtube.com before youtube.com could be useful.
