### ISSUE TITLE
[Dub] Missing Tons of Links (Only Showing Most Recent 100 Links) Pagination Issue

### ISSUE THREAD

**Issue by abass** [raycast/extensions#14198]
### Extension

https://www.raycast.com/dubinc/dub

### Raycast Version

1.81.2

### Description

The extension takes the latest 100 links and doesn't handle pagination, so it does't actually show all links when searching which makes it less useful if you're actually using Dub quite heavily.

### Steps To Reproduce

Have more than 100 links and search for a link in Dub.

**Comment by jfkisafk** [comment]
I don't think dub API supports pagination at the moment.

**Comment by steven-tey** [comment]
@jfkisafk we [do support pagination](https://dub.co/docs/api-reference/endpoint/retrieve-a-list-of-links#:~:text=lastClicked-,page,default%3A%201,-The%20page%20number)! How would this work with Raycast's API though – e.g. is there any way we can run async filtering instead of Raycast's default local-first filtering?

**Comment by jfkisafk** [comment]
Oh sorry @steven-tey  I do not know how I missed that. But essentially we have to move with typeahead search option here, utilizing the `search` parameter. That way we will keep this command safe from memory heap issues  https://github.com/raycast/extensions/issues/10127#issuecomment-2104485073 (by not loading all the links in the memory).

We can dynamically trigger typeahead in case of large workspaces (i.e. when a page cursor is present for the next page page of results). But if the no. of links is < 100 then we can just supply `keywords` and use `filtering=true` instead (as we are now. This will save unnecessary calls to the API for smaller workspaces. Here is a recent example from "Search Documents" command in Linear extension that uses this architecture:

https://github.com/raycast/extensions/blob/c7857fd97dc54f8e2c4fe9dd7e9ad2749d15f288/extensions/linear/src/components/docs/DocumentList.tsx#L97-L99

https://github.com/raycast/extensions/blob/c7857fd97dc54f8e2c4fe9dd7e9ad2749d15f288/extensions/linear/src/hooks/useDocuments.ts#L5-L18

https://github.com/raycast/extensions/blob/c7857fd97dc54f8e2c4fe9dd7e9ad2749d15f288/extensions/linear/src/api/documents.ts#L83-L86

**Comment by steven-tey** [comment]
@jfkisafk that looks perfect, thanks for sharing! Feel free to make a PR for this – we can get to it on our end once as well we finish a few other integrations!

**Comment by jfkisafk** [comment]
Delegated it to @srikirank. He will be working on this one!

**Comment by steven-tey** [comment]
Thank you @srikirank 🙏

**Comment by steven-tey** [comment]
@srikirank were you able to figure out a solution for this? 👀

**Comment by jfkisafk** [comment]
@raycastbot assign me
