### ISSUE TITLE
[Timers] ...

### ISSUE THREAD

**Issue by im-abdullah** [raycast/extensions#14200]
### Extension

https://www.raycast.com/ThatNerd/timers

### Raycast Version

1.81.2

### macOS Version

14.6.1 (23G93)

### Description

once the timer ends, it's stuck at the top menu bar. if I start other timers, they become many ones stuck in top bar at like 0:04seconds all. 

### Steps To Reproduce

Start a timer, wait for it to end.

### Expected Behaviour

it should hide after.

**Comment by ThatNerdSquared** [comment]
Hi @im-abdullah, thanks for using Timers!

A couple questions to help with debugging:
- Do you have the "Ring Continuously" preference checked in the Raycast Settings for this extension? (should be checked by default)
- When this happens, does opening the menu bar item (clicking on it to show the full menu) make the timer disappear?
- When this happens, is the timer also present in the "Manage Timers" command?

Thanks again.

**Comment by ThatNerdSquared** [comment]
This was fixed in Raycast v1.82.1 — updating to the latest version of Raycast should solve your issue :)
