### ISSUE TITLE
[Spotify Player] "Dislike" does not dislike/hide song from Discover Weekly

### ISSUE THREAD

**Issue by kud** [raycast/extensions#14213]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.81.2

### macOS Version

14.6.1

### Description

When I want to dislike a song from Discover Weekly to help Spotify give me the right tracks, triggering "Dislike" does nothing.

https://github.com/user-attachments/assets/9c57defb-72e6-4a30-8ed6-52bc12d647fc

### Steps To Reproduce

1. Go to Discover Weekly playlist
2. Listen to a song
3. Run "Dislike" from this extension

### Current Behaviour

Just the toaster appears.

### Expected Behaviour

The toaster should appear and also especially dislike/hide this song.

**Comment by thomaslombart** [comment]
Could you share a recording? On my end, `Dislike` is removing the song from the "Liked Songs" playlist, so it's doing something.

**Comment by kud** [comment]
@thomaslombart Done 😌

**Comment by thomaslombart** [comment]
I see. That's actually another action in the Spotify extension. I'm not sure the Spotify API supports that, as I couldn't find anything after skimming the API. Feel free to take a deeper look; I may have missed something.

**Comment by kud** [comment]
Thanks. I can close this ticket then. 😊
