### ISSUE TITLE
[Git Buddy] Ability to work with multiple git repos in the extension

### ISSUE THREAD

**Issue by cyxn** [raycast/extensions#14212]
### Extension

https://www.raycast.com/gianfranco/git-buddy

### Description

I really like how it works. I wish it had the ability to select multiple Git repositories without requiring you to switch the extension configuration to specify a specific folder.

### Who will benefit from this feature?

Everyone who works with multiple git repos

**Comment by gianfrancopiana** [comment]
Hey @cyxn, thanks for trying out Git Buddy!

Totally get your point. This was the best solution I could think of that didn't hurt the user experience.

At one point I considered we could make users pick one folder and scan for repos inside - but that's not very flexible. Many people, including me, work on repos in different folders. And you'd still need a global setting to select which repo you're working on for the commands to work smoothly. 

So I thought this was the simplest solution overall. But having said all this, do you have any ideas for how this could work differently?

**Comment by cyxn** [comment]
@gianfrancopiana  I will think about this more deeply. I'm confident there is a solution; it’s just a matter of finding a good UX for it.

I agree that one folder is not flexible enough for everyone, but in my case, this is exactly how I have all my repos—they are all in the same folder.

I believe the configuration of the folder where the repository is located should be removed from global settings and integrated into the extension's functionality.

Maybe we can give separate command to user that can set multiple folders, or make this automated, aka `find ~ -type d -name ".git" -exec dirname {} \;` and set the result into some text where user can modify that.

Commands like "write PR description" can be modified to specify which repository to apply it to. Additionally, we can allow users to create quick links to such commands. For example, a user could have the command "write PR description for repo X," and it would function as it does now. Something like in extension that I've developed ("list custom commands" command) — https://www.raycast.com/cyxn/universal-commands

**Comment by gianfrancopiana** [comment]
That's a great point. I hadn't considered quicklinks. I'll keep this in mind and see if I can come up with a good solution. But please let me know if any other ideas come to mind.

And thanks for sharing the extension - just installed it!
