### ISSUE TITLE
[Snippet Surfer] Allow creation of snippets from within Raycast

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#14218]
### Extension

https://www.raycast.com/astronight/snippetsurfer

### Description

By default, the Snippet Surfer doesn't 1) come with any pre-installed snippets and 2) doesn't allow you to create a snippet from within Raycast:

![2024-08-27 (11 15 23) Arc](https://github.com/user-attachments/assets/9d87b442-9931-4011-beaf-f11d17394edf)

It would be great if you could quickly create new snippets from within this extension.

### Who will benefit from this feature?

Anyone who uses Snippet Surfer.

**Comment by mkitane** [comment]
Short answer: No. Snippet Surfer is geared a bit more towards developers.

There are some other features that raycast snippet doesn't have:
- Ability to show code blocks in the UI with some syntax highlighting (and more generally markdown syntax).
- Automatically copies only the content inside code snippets for code snippets.
- Stores snippets in a human-readable format and allows external editing (So you can bulk edit snippets with ease, auto generate them via code, etc...)
- Automatically apply edits without manual imports (You can bulk import new snippets to Raycast but that's a manual process now and it doesn't handle updates well).

**Comment by slhck** [comment]
I've created https://github.com/raycast/extensions/pull/14430/ to possibly help people onboard better, since I was also struggling with creating these snippets initially.
