### ISSUE TITLE
[Apple Reminders] Natural language does not set recurring & location

### ISSUE THREAD

**Issue by wyat-soule-waggoner** [raycast/extensions#14226]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Raycast Version

1.81.2

### Description

When i add a quick reminder, such as the one in the example "Send the weekly project status report Friday at 2 PM in the Work list", it creates the reminder of "Send weekly project status report in Work list" in the default task list.

Additionally, the "Remind me to buy milk when I'm leaving the office." will create a "Remind me to buy milk when I'm leaving the office." reminder with no time or location.

it also does not work for repeating tasks.

### Steps To Reproduce

1. raycast mac
2. nothing extra, just apple reminders extention
3. run "quick add reminder"
4. see that it creates the reminder without the natural language

### Current Behaviour

Creates a task without natural language based on location and repeating tasks in correct list

### Expected Behaviour

create a reminder with location set correctly, extra words scraped off (such as "remind me to get milk" modified to "get milk"), repeated tasks being repeated correctly, lists selected correctly.

**Comment by thomaslombart** [comment]
Are you a Raycast Pro user? These features work only if your reminder is parsed by Raycast AI, which is a feature limited to Pro users.
