### ISSUE TITLE
[Google Chrome] asks for full disk access, even though I have already set the permissions.

### ISSUE THREAD

**Issue by joest67** [raycast/extensions#14223]
### Extension

https://www.raycast.com/Codely/google-chrome

### Raycast Version

1.81.2

### macOS Version

Sonoma 14.6.1

### Description

when I use the Google Chrome extension, it asks for disk access again, even though I have already set the permissions. After restarting Raycast, it works, but sometimes later, it occurs again. 

![image](https://github.com/user-attachments/assets/8e496c49-03cf-4c81-81a6-5fbd4da0e8a8)
![image](https://github.com/user-attachments/assets/c267b7f0-3a92-4d3a-89bb-8be899351670)

### Steps To Reproduce

as description part describe~

**Comment by joest67** [comment]
@a-laughlin anyone can help me 😳

**Comment by a-laughlin** [comment]
Not sure why you're having that issue. Raycast doesn't have full disk access for me. The extension works fine. I never see that message. I don't think the issue you're experiencing is this extension.
