### ISSUE TITLE
[ChatGPT] use simple string content in completions api request perfer

### ISSUE THREAD

**Issue by MeetzhDing** [raycast/extensions#14230]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Raycast Version

1.81.2

### macOS Version

14.6.1

### Description

In the [openai document](https://platform.openai.com/docs/api-reference/making-requests), the server can accept simple string in the messagesContent.

```bash
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
     "model": "gpt-4o-mini",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }'
```

So there ara many AI platforms can accept the simple string format only.

### Steps To Reproduce

follow the instruction of [deepseek](https://platform.deepseek.com/api-docs/zh-cn/), 
use deepSeek API key.

### Current Behaviour

This will result in a 422 - Invalid Parameters error

<img width="750" alt="image" src="https://github.com/user-attachments/assets/8d1c2b88-4b0b-4c1c-a89d-3e6c5b3c3336">

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/5d1b98e0-b4e3-4a79-8f9f-7e28ea516685">

### Expected Behaviour

But the api code in the chatgpt plugin, array format will be used always.

https://github.com/raycast/extensions/blob/4e86383a7211b23eeda858e1da9b32a26a5c89a9/extensions/chatgpt/src/hooks/useChat.tsx#L71-L81
https://github.com/raycast/extensions/blob/4e86383a7211b23eeda858e1da9b32a26a5c89a9/extensions/chatgpt/src/utils/index.ts#L82-L100

---

Can we change the function of [buildUserMessage](https://github.com/raycast/extensions/blob/4e86383a7211b23eeda858e1da9b32a26a5c89a9/extensions/chatgpt/src/utils/index.ts#L82-L100), return single string when files parameter is empty?

This modification should be compatible.

**Comment by luckykong** [comment]
The `ChatGPT` extension has been updated, can you test it? 
I have checked in my mac and It's already usable.
