### ISSUE TITLE
[AirPods Noise Control] Switches to Adaptive while configured to switch to Noise Cancellation

### ISSUE THREAD

**Issue by shako** [raycast/extensions#14237]
### Extension

https://www.raycast.com/chrahe/airpods-noise-control

### Raycast Version

1.81.2

### macOS Version

14.1

### Description

With options `Transparancy` and `Noise Cancellation` configured, the extension switches between `Transparancy` and `Adaptive`

#### Extension configuration
1. Mac os language = `Nederlands (Nederlands)`
2. Airpods list position = `4`
3. Control center localization = `Bedieningspaneel`
4. Sound menu localization = `Geluid`

#### Steps
6. Activate the `Switch Noise Control Mode` action multiple times

#### Additional Context
Not sure if it's relevant, but the Noise Control options are as follows in dutch: 
- Uit
- Transparantie
- Adaptief
- Ruisonderdrukking

### Current Behaviour

The extension switches between `Transparancy` and `Adaptive`

### Expected Behaviour

The extension switches between `Transparancy` and `Noise Cancellation`

**Comment by bent101** [comment]
i have this issue too

**Comment by Hackerwithnotepad** [comment]
same here
