### ISSUE TITLE
[Coffee] ... Icon is stuck in the menu bar  and doesn't dissapear when turned off

### ISSUE THREAD

**Issue by lilvlad** [raycast/extensions#14248]
### Extension

https://www.raycast.com/mooxl/coffee

### Raycast Version

v1.18.2

### Description

When toggling the status the icon doesn't dissapear and if turned on multiple icons appear in the menu bar

### Steps To Reproduce

not sure

**Comment by pernielsentikaer** [comment]
This should be fixed in the next Raycast release
