### ISSUE TITLE
[Sesh] Not Loading

### ISSUE THREAD

**Issue by albertilagan** [raycast/extensions#14249]
### Extension

https://www.raycast.com/joshmedeski/sesh

### Raycast Version

1.81.2

### macOS Version

14.6.1

### Description

Unable to load session, I have not tested this on v1 so I'm not sure if this is because i'm on v2 of sesh now.

![Screenshot 2024-08-30 at 10 29 30@2x](https://github.com/user-attachments/assets/5fee049a-eefd-43a6-aa92-c84a50d8f74b)

Error
```
SyntaxError: Unexpected token 'd', "dotfiles _"... is not valid JSON

    at JSON.parse (<anonymous>)
sesh.ts:19:28

---
16:       if (error || stderr) {
17:         return reject(`Please upgrade to the latest version of the sesh CLI`);
18:       }
19:       const sessions = JSON.parse(stdout);
20:       return resolve(sessions ?? []);
21:     });
22:   });
---

ChildProcess.exithandler:node:child_process:414:7
ChildProcess.emit:node:events:519:28
```

### Steps To Reproduce

1. Open Raycast
2. Make sure there's active tmux session
3. Run `Connect to Session`

**Comment by albertilagan** [comment]
I tried to strip my config to 
```
[[session]]
name = "dotfiles 🏡"
path = "~/.dotfiles"
```
and here's the new error
```
#### Error:
```
SyntaxError: Unexpected token 's', "sesh confi"... is not valid JSON

    at JSON.parse (<anonymous>)
sesh.ts:19:28

---
16:       if (error || stderr) {
17:         return reject(`Please upgrade to the latest version of the sesh CLI`)
```

**Comment by joshmedeski** [comment]
JSON is currently broken in sesh v2, I will get it working in the next few days!

**Comment by joshmedeski** [comment]
Fixed with https://github.com/joshmedeski/sesh/pull/158
