### ISSUE TITLE
[Linear] Menu bar icon stuck

### ISSUE THREAD

**Issue by pritamrungta** [raycast/extensions#14251]
### Extension

https://www.raycast.com/linear/linear

### Raycast Version

v1.81.2

### macOS Version

14.6.1

### Description

The icon doesn't go away even after viewing the notification.

<img width="52" alt="image" src="https://github.com/user-attachments/assets/1e466a6d-b94f-429a-a037-d766dc983050">

The icons keep accumulating

<img width="155" alt="image" src="https://github.com/user-attachments/assets/e09dc65e-a472-4b77-a69d-7a297a23b348">

### Steps To Reproduce

1. Receive a notification
2. View it
3. The icon stays

**Comment by thomaslombart** [comment]
Thank you for reporting the issue. A recent Raycast release introduced a regression causing this bug in some menu bar commands. One of our engineers is working on it!

**Comment by jfkisafk** [comment]
With the fixes in menu bar with recent version [1.82.0](https://www.raycast.com/changelog/1-82-0), this issue is fixed. Please reopen if that is not the case.

**Comment by jfkisafk** [comment]
@raycastbot close this issue
