### ISSUE TITLE
[Apple Mail]...not pulling inbox if name contains comma

### ISSUE THREAD

**Issue by dfucci** [raycast/extensions#14261]
### Extension

https://www.raycast.com/yug2005/mail

### Raycast Version

1.81.2

### macOS Version

14.6.1

### Description

When running the "Refresh Mail" command an error occurs. The log show

```Error: Command failed with exit code 1: osascript
106:158: execution error: Mail got an error: Can’t get mailbox 1 of account id "XXX-YYY-ZZZ" whose name = "Tickets". Invalid index. (-1719)

hq:run-applescript.js:38:21

---
35:         timedOut,
36:         command: "osascript",
37:         options,
38:         parentError: new Error(),
39:     });
40: }
41: exports.runAppleScript = runAppleScript;
---

async BO:refresh-mail.js:244:8
```

I have a mailbox called "Tickets, receipts, contracts."
Renaming the mailbox fixes the issue.

### Steps To Reproduce

Run the `Refresh Mail` command

### Current Behaviour

An error occurs showing the "Something went wrong" message

### Expected Behaviour

All mailboxes are correctly fetched

**Comment by ridemountainpig** [comment]
@raycastbot close this issue
