### ISSUE TITLE
[YouTrack] ...not work

### ISSUE THREAD

**Issue by GRCmade** [raycast/extensions#14267]
### Extension

https://www.raycast.com/tiulpin/youtrack

### Raycast Version

1

### macOS Version

1

### Description

not work

### Steps To Reproduce

open youtrack

### Current Behaviour

1

### Expected Behaviour

1

**Comment by ruslan-korneev** [comment]
hello, @GRCmade, what exactly doesnt work for you?

**Comment by ruslan-korneev** [comment]
@raycastbot close this issue
