### ISSUE TITLE
Add pause

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#14265]
### Extension

https://www.raycast.com/HelloImSteven/keyboard-shortcut-sequences

### Description

Please add an option for input a pause value, to be able to specify a "wait" time before the next key press/shortcut.

**Comment by alexcamlo** [comment]
Is he even maintaining this extension? He is not answering any issue.

**Comment by SKaplanOfficial** [comment]
Will be resolved by #22181.

I haven't been able to make meaningful progress on extensions for a while for a number of reasons, despite wanting to. However, others are welcome to make contributions, which I'm happy to provide feedback on via email or PR reviews.
