### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by aarons3225** [raycast/extensions#14269]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

1.81.2

### macOS Version

14.16.1

#### Error:
```
Could not find extension's manifest file. You might need to reinstall the extension.


```

### Steps To Reproduce

1. have raycast open and running.
2. installed the extension
3. copied a YouTube link
4. ran the extension

### Current Behaviour

States Something went wrong

### Expected Behaviour

expected to download YouTube video

**Comment by ridemountainpig** [comment]
@aarons3225 I tried the extension, but it was successful on my end. Could you try reinstalling it again and let me know if the issue persists?

**Comment by aarons3225** [comment]
@ridemountainpig That worked. Sorry about that. Thank you for your reply.

**Comment by ridemountainpig** [comment]
@raycastbot close this issue
