### ISSUE TITLE
[Refresh WiFi] Refresh Bluetooth too?

### ISSUE THREAD

**Issue by aliafshany** [raycast/extensions#14271]
### Extension

https://www.raycast.com/natterstefan/refresh-wifi

### Description

Hello there,

Thank you for this wonderful extension. I would like to ask if it is possible to have an option for Bluetooth as well. I have not been able to find any extensions for this purpose.

Best

**Comment by merchako** [comment]
If wanted to request the same issue, is it better to bump it here or start a new issue?

A single refresh bluetooth command is especially important because if the user is on a bluetooth keyboard, they won't be able to turn it off AND turn it back on again because they won't be able to type.
