### ISSUE TITLE
Build extension failed

### ISSUE THREAD

**Issue by lchung0** [raycast/extensions#1427]
Raycast version: 1.32.1

## Description
hey guys，I got the following error when I try to build my extension, does anyone know why ?
It was strange because I'm using macbook with m1, but this script use x86/ray to build.

## Steps To Reproduce

1. create an extension
2. npm run build

## The current behavior
Here is the output.
![image](https://user-images.githubusercontent.com/16162468/163767654-0e106c5d-ae26-45d1-901f-a0a4b616da49.png)
And here is my system info.
![image](https://user-images.githubusercontent.com/16162468/163767695-d33653d9-df42-4ff7-80c7-e8e1c6fcbb2c.png)

## The expected behavior
`npm run build` goes well

**Comment by lchung0** [comment]
Ignore it, my mistake. I build it in remote machine.

**Comment by ParseDark** [comment]
> Ignore it, my mistake. I build it in remote machine.

Same issue. How can i fix it?
