### ISSUE TITLE
[nextdns] NextDNS Status Command

### ISSUE THREAD

**Issue by erics118** [raycast/extensions#14289]
### Extension

https://www.raycast.com/pernielsentikaer/nextdns

### Description

Add a command to view the status of nextdns locally, and display some info.

for example, display `{device name} is using NextDNS via {protocol}`

Basically, an extension command version of https://github.com/raycast/script-commands/blob/b38d4a7ade3ad0dcb28e762341399f73c68ebb4e/commands/dashboard/nextdns-status-check.py

### Who will benefit from this feature?

People who want to easily see if nextdns is enabled or not

### Anything else?

I can make the PR for feature. Not sure if this is better as a separate extension, or as part of this extension.

**Comment by pernielsentikaer** [comment]
Just added in #14302 @erics118 🙂
