### ISSUE TITLE
[Format JSON] incorrectly claims json string is invalid

### ISSUE THREAD

**Issue by noalbalint** [raycast/extensions#1430]
# Extension – [Format JSON](https://github.com/raycast/extensions/tree/34f3ee23919ce19a580797d1719d9768624c9f1f/extensions/json-format/)
Author: @Destiner 

## Description

this extension is incorrectly saying json strings are invalid.

## Steps To Reproduce

try pasting this string into the extension:

`{"_actionSubscribers": [], "_actions": {"createAssets/reset": [Array], "createAssets/setAssets": [Array], "createAssets/setGroupId": [Array], "createAssets/submit": [Array], "navigation/addAssetGroupListItem": [Array], "navigation/addNavigationItem": [Array], "navigation/clearCurrentGroup": [Array], "navigation/clearNavigationItems": [Array], "navigation/decrementAssetsLimit": [Array], "navigation/deleteAssetGroupListItem": [Array], "navigation/fetchAssetsLimit": [Array], "navigation/fetchCurrentGroup": [Array], "navigation/incrementAssetsLimit": [Array], "navigation/resetAssetsModal": [Array], "navigation/routeTo": [Array], "navigation/setAssetGroupsList": [Array], "navigation/setAssetsModal": [Array], "navigation/setCurrentGroup": [Array], "navigation/setMatchesSidebarState": [Array], "navigation/setTranslate": [Array], "navigation/updateAssetGroupListItem": [Array], "saveSearchModal/setOpen": [Array], "saveSearchModal/setSelectedGroup": [Array], "saveSearchModal/setStep": [Array]}, "_committing": false, "_makeLocalGettersCache": {"createAssets/": [Object], "navigation/": [Object], "saveSearchModal/": [Object]}, "_modules": {"root": [Module]}, "_modulesNamespaceMap": {"createAssets/": [Module], "navigation/": [Module], "saveSearchModal/": [Module]}, "_mutations": {"createAssets/RESET": [Array], "createAssets/SET_ASSETS": [Array], "createAssets/SET_ASSET_ERRORS": [Array], "createAssets/SET_GROUP_ID": [Array], "navigation/ADD_NAVIGATION_ITEM": [Array], "navigation/CLEAR_NAVIGATION_ITEMS": [Array], "navigation/SET_ASSETS_LIMIT": [Array], "navigation/SET_ASSET_GROUPS_LIST": [Array], "navigation/SET_ASSET_GROUPS_LIST_LOADING_STATE": [Array], "navigation/SET_ASSET_MATCHES_SIDEBAR_STATE": [Array], "navigation/SET_CURRENT_GROUP": [Array], "navigation/SET_MODAL_STATE": [Array], "navigation/SET_NAVIGATION_ITEM": [Array], "navigation/SET_TRANSLATE": [Array], "saveSearchModal/SET_OPEN": [Array], "saveSearchModal/SET_SELECTED_GROUP": [Array], "saveSearchModal/SET_STEP": [Array]}, "_subscribers": [], "_vm": {"$attrs": [Object], "$children": [Array], "$createElement": [Function anonymous], "$listeners": [Object], "$options": [Object], "$parent": undefined, "$refs": [Object], "$root": [Circular], "$scopedSlots": [Object], "$slots": [Object], "$vnode": undefined, "$vuetify": [Circular], "_c": [Function anonymous], "_computedWatchers": [Object], "_data": [Object], "_directInactive": false, "_events": [Object], "_hasHookEvent": false, "_inactive": null, "_isBeingDestroyed": false, "_isDestroyed": false, "_isMounted": false, "_isVue": true, "_renderProxy": [VueComponent], "_self": [Circular], "_staticTrees": null, "_uid": 1, "_vnode": null, "_watcher": null, "_watchers": [Array], "createAssets/canSave": false, "createAssets/getError": [Function anonymous], "createAssets/hasError": [Function anonymous], "createAssets/hasErrors": false, "navigation/assetGroupsList": [Array], "navigation/assetGroupsListLoadingState": true, "navigation/assetsLimit": [Object], "navigation/currentGroup": undefined, "navigation/isMatchesSidebarOpen": false, "navigation/modalState": [Object], "navigation/navigationItems": [Array], "saveSearchModal/currentStep": "CREATE_ASSET", "saveSearchModal/isOpen": false, "saveSearchModal/selectedGroup": null}, "_watcherVM": {"$attrs": [Object], "$children": [Array], "$createElement": [Function anonymous], "$listeners": [Object], "$options": [Object], "$parent": undefined, "$refs": [Object], "$root": [Circular], "$scopedSlots": [Object], "$slots": [Object], "$vnode": undefined, "$vuetify": [Circular], "_c": [Function anonymous], "_data": [Object], "_directInactive": false, "_events": [Object], "_hasHookEvent": false, "_inactive": null, "_isBeingDestroyed": false, "_isDestroyed": false, "_isMounted": false, "_isVue": true, "_renderProxy": [VueComponent], "_self": [Circular], "_staticTrees": null, "_uid": 0, "_vnode": null, "_watcher": null, "_watchers": [Array]}, "_wrappedGetters": {"createAssets/canSave": [Function wrappedGetter], "createAssets/getError": [Function wrappedGetter], "createAssets/hasError": [Function wrappedGetter], "createAssets/hasErrors": [Function wrappedGetter], "navigation/assetGroupsList": [Function wrappedGetter], "navigation/assetGroupsListLoadingState": [Function wrappedGetter], "navigation/assetsLimit": [Function wrappedGetter], "navigation/currentGroup": [Function wrappedGetter], "navigation/isMatchesSidebarOpen": [Function wrappedGetter], "navigation/modalState": [Function wrappedGetter], "navigation/navigationItems": [Function wrappedGetter], "saveSearchModal/currentStep": [Function wrappedGetter], "saveSearchModal/isOpen": [Function wrappedGetter], "saveSearchModal/selectedGroup": [Function wrappedGetter]}, "commit": [Function boundCommit], "dispatch": [Function boundDispatch], "getters": {"createAssets/canSave": false, "createAssets/getError": [Function anonymous], "createAssets/hasError": [Function anonymous], "createAssets/hasErrors": false, "navigation/assetGroupsList": [Array], "navigation/assetGroupsListLoadingState": true, "navigation/assetsLimit": [Object], "navigation/currentGroup": undefined, "navigation/isMatchesSidebarOpen": false, "navigation/modalState": [Object], "navigation/navigationItems": [Array], "saveSearchModal/currentStep": "CREATE_ASSET", "saveSearchModal/isOpen": false, "saveSearchModal/selectedGroup": null}, "strict": false}`

## The current behavior

extension says its invalid json

<img width="806" alt="Screen Shot 2022-04-18 at 1 36 06 PM" src="https://user-images.githubusercontent.com/45208632/163873882-d22792f4-9975-4a0e-a20c-2735381cc535.png">

## The expected behavior

Should process the json. When I use https://jsonformatter.curiousconcept.com/#, it works fine so its evidently not actually invalid.

<img width="1050" alt="Screen Shot 2022-04-18 at 1 36 13 PM" src="https://user-images.githubusercontent.com/45208632/163873894-2f07a575-5183-4bb2-9f48-864adec44879.png">

### Raycast version
1.32.1

**Comment by Destiner** [comment]
Hey @noalbalint, thanks for feedback. I would argue, however, that this JSON is invalid. At the start of your example, you have `"createAssets/reset": [Array]`, where  `[Array]` is not a valid part of JSON.

The tool that you’ve linked seems to transform your original json to make it valid (`[Array]` -> `[“Array”]`). I think modifying the original JSON is deceptive to the users.
