### ISSUE TITLE
[Todoist] Default sorting doesn't work

### ISSUE THREAD

**Issue by roizner** [raycast/extensions#14319]
### Extension

https://www.raycast.com/doist/todoist

### Raycast Version

1.81.2

### macOS Version

14.6.1

### Description

The order of the tasks (with Default sorting) in lists is incorrect, i.e. it's not the same as in Todoist app.

### Steps To Reproduce

1. Have some number of tasks in the Project / Filter / Sub-tasks.
2. Use manual sorting in Todoist app and reorder the tasks.
3. Open the list of tasks in the Raycast extension.

### Current Behaviour

The tasks are in some random order.

### Expected Behaviour

The tasks should be in the same order as in Todoist.

**Comment by thomaslombart** [comment]
Could you share some screenshots to see the difference between the tasks in Raycast and Todoist?

**Comment by roizner** [comment]
For Today tasks
in Todoist app (the desired order):
<img width="827" alt="image" src="https://github.com/user-attachments/assets/9e0a57ac-4d08-4ffe-bc35-4c4c0c9022b2">
in Raycast: 
<img width="740" alt="image" src="https://github.com/user-attachments/assets/5d2ccc20-5f27-4241-b793-54b0e944239e">

For sub-tasks
in Todoist app (the desired order):
<img width="850" alt="image" src="https://github.com/user-attachments/assets/d7416eb0-10c8-49b3-9049-f5d70252524a">
in Raycast:
<img width="750" alt="image" src="https://github.com/user-attachments/assets/615150e0-5d0b-410f-bc6b-ffa40de99466">

**Comment by thomaslombart** [comment]
Here's [the code](https://github.com/raycast/extensions/blob/b7a94dbf1cadfd61fc4f5d29ea010e704b9c00d4/extensions/todoist/src/helpers/tasks.ts) we have related to sorting today tasks in the extension:

```tsx
export function getTasksForTodayOrUpcomingView(tasks: Task[], userId: string) {
  const filteredTasks = tasks.filter((t) => {
    if (!t.due) {
      return false;
    }

    if (t.responsible_uid && t.responsible_uid !== userId) {
      return false;
    }

    return true;
  });

  // Sorts tasks based on the following criteria, in order:
  // 1. Due date type (datetime due dates appear first)
  // 2. Due date and time (earliest first)
  // 3. Priority (highest first)
  // 4. Day order (lowest first)
  return filteredTasks.sort((a, b) => {
    if (!a.due || !b.due) {
      return 0;
    }

    const aIsExactTime = isExactTimeTask(a);
    const bIsExactTime = isExactTimeTask(b);
    if (aIsExactTime !== bIsExactTime) {
      return bIsExactTime ? 1 : -1;
    }

    const bDue = new Date(b.due.date);
    const aDue = new Date(a.due.date);
    if (aDue.getTime() !== bDue.getTime()) {
      return aDue.getTime() - bDue.getTime();
    }

    if (a.priority !== b.priority) {
      return b.priority - a.priority;
    }

    return a.day_order - b.day_order;
  });
}
```

`day_order` being "the order of the task inside the Today or Next 7 days view (a number, where the smallest value would place the task at the top)." according to [Todoist's docs](https://developer.todoist.com/sync/v9/#items). I don't see how the code could go wrong in your case, so maybe there's a bug in Todoist's APIs 🤔

**Comment by roizner** [comment]
The problem I see in Today ordering seems to be about recurrent tasks. Todoist shows them on the top in my case, Raycast shows them on the bottom.

**Comment by thomaslombart** [comment]
Still, if a task is recurring, the `day_order` should probably be reflected in both Todoist's UI and API, so I don't think we can do much here apart from contacting their support.

**Comment by ColtonIdle** [comment]
@roizner i wonder if your issue is fixed now by 

https://github.com/raycast/extensions/issues/16646

my default ordering finally matches todoist web =)

**Comment by roizner** [comment]
No, I still see the list of sub-tasks ordered differently from what I see in the app.

**Comment by rickyribeiroo** [comment]
I am also experiencing the same issue.
