### ISSUE TITLE
[Dock Tinker] Add "Small Spacer" option to dock

### ISSUE THREAD

**Issue by namzo** [raycast/extensions#14311]
### Extension

https://www.raycast.com/koinzhang/dock-tinker

### Description

Love this extension. Please also add an option for adding smaller spacer to dock. The regular spacer is sometimes too wide.

Here's the script:
`defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="small-spacer-tile";}'`

Thanks!

### Who will benefit from this feature?

Everyone who uses the extension

**Comment by koinzhang** [comment]
Support in PR #14317

**Comment by koinzhang** [comment]
The PR has been merged.

@raycastbot close this issue
