### ISSUE TITLE
[Apple Reminders] ...Add field to attach reminder tags

### ISSUE THREAD

**Issue by sloraris** [raycast/extensions#14324]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Apple Reminders gains most of its automation and smart list capabilities through tags, this field is missing from the creation menu in Raycast though.

### Who will benefit from this feature?

Anyone using Apple Reminders

**Comment by thomaslombart** [comment]
Unfortunately, there's no support for reminder tags in Apple's APIs, so I'll close this issue as not planned 😕
