### ISSUE TITLE
[Google Cloud Platform Search] ... error

### ISSUE THREAD

**Issue by PhamQuang-512** [raycast/extensions#14337]
### Extension

https://www.raycast.com/klaa97/gcp-search

### Raycast Version

1.82.1

### macOS Version

14.2.1

#### Error:
```
RangeError: "length" is outside of buffer bounds

Buffer.utf8Write:buffer:1066:13
Sl.SD:searchProjects.js:5:28309
we.finish:searchProjects.js:5:27525
searchProjects.js:15:42847
```

### Steps To Reproduce

1. open extension gcp from raycast to seach
2. can not seach

### Current Behaviour

can not search for gcp project

### Expected Behaviour

search for gcp project

**Comment by klaa97** [comment]
@pernielsentikaer Which version of Node is Raycast using? It appears that version 22.7.0 suffers from a critical error: https://github.com/nodejs/node/issues/54518 tied to protobufs, and the problem seems similar here.

**Comment by gcar-bendingspoons** [comment]
Indeed the exception happens when initializing the `google-cloud` `ProjectsClient` here:
https://github.com/raycast/extensions/blob/3536d843f032492e720f0f618cd7ce44a9ce44ad/extensions/google-cloud-platform-search/src/projects.tsx#L5

I tried `console.log(process.versions.node)` and it is using `22.7.0`, so that's the issue.

**Comment by PhamQuang-512** [comment]
> @pernielsentikaer Which version of Node is Raycast using? It appears that version 22.7.0 suffers from a critical error: [nodejs/node#54518](https://github.com/nodejs/node/issues/54518) tied to protobufs, and the problem seems similar here.

how to check node version raycast using

**Comment by PhamQuang-512** [comment]
fork and change extension code like @m-gentil does work

**Comment by danielsequeira** [comment]
Unfortunately, this was done accidentally. We are going to publish a hotfix (1.82.3) that changes it back to 20.15.1.
