### ISSUE TITLE
Spotify Player Code: 2

### ISSUE THREAD

**Issue by marcoantonio123456** [raycast/extensions#14335]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.82.1

### macOS Version

14.6

### Description

On song change i am getting 

<img width="37" alt="Screenshot 2024-09-04 at 5 03 02 PM" src="https://github.com/user-attachments/assets/258f4329-46c6-47d6-ab73-b2e6cfe35014">

Where the album art would usually be. When i try to investigate i get 

Reason: Code: 2 (Unhandled Extension Rejection

Domain: commands
Time: 20:58:44.781

### Steps To Reproduce

nothing special in my configuration

### Current Behaviour

If i try to reload the error persists. I have tried to signout and sign back in to spotify. Only closing Raycast and restarting it fixes the issue for 1 song and then the cycle repeats

**Comment by clasick** [comment]
@marcoantonio123456 I got a similar error today and I was able to fix the issue by:
1. Uninstalling the Spotify Player extension from Raycast
2. Reinstalling and re-authenticating the latest extension version using my Spotify account

**Comment by thomaslombart** [comment]
@marcoantonio123456 Are you still having the issue?

**Comment by marcoantonio123456** [comment]
Hey, no it got resolved... the past comment solved the issue and it came back again but after some updates it went away. Plugin is running strong at the moment. Thank you
