### ISSUE TITLE
[Slack] Open Channel triggers "command + ." hotkey

### ISSUE THREAD

**Issue by nivzelber** [raycast/extensions#14340]
### Extension

https://www.raycast.com/mommertf/slack

### Raycast Version

1.82.2

### macOS Version

14.6.1

### Description

Whenever I open a channel using "Open Channel" command (can be a DM or an actual Channel), once the channel is opened The keyboard shortcut "command + ." is triggered.  
In my case this shortcuts is preconfigured to perform an action, which thus being performed every time I use the "Open Channel" command.

My specific action is opening the emoji menu if this information helps in any way.

### Steps To Reproduce

1. Trigger something (anything) using Raycast via the shortcut "command + ."
2. Activate the "Open Channel" command
3. Select a channel and open it
4. See the action configured in step 1 being triggerd

### Current Behaviour

Triggers "command + ." command

### Expected Behaviour

Should not trigger anything

**Comment by Elliot67** [comment]
Hi @nivzelber, I believe you can disable the "Close Slack sidebar" option to stop the shortcut. It is used to close the sidebar when navigating to a private chat.

**Comment by nivzelber** [comment]
Is this done via slack app or via extension settings in raycast?

**Comment by Elliot67** [comment]
@nivzelber Via extension settings inside Raycast.

**Comment by thomaslombart** [comment]
This code is indeed run by default, causing `Command + .` to be pressed:

```
await runAppleScript(
  buildScriptEnsuringSlackIsRunning(`
    tell application "System Events"
      tell process "Slack"
        key code 47 using {command down}
      end tell
    end tell
  `)
);
```

As @Elliot67 said, disabling "Close Slack right sidebar" will do the trick.

![CleanShot 2024-09-06 at 12 53 26@2x](https://github.com/user-attachments/assets/60d40b38-569f-434f-a47e-bcae0edab365)

**Comment by nivzelber** [comment]
You guys rock! I wish there was a way to change this shortcut (for slack, then in the extension) as the side panel opening is indeed weird, but those are problems for another day. I really appreciate the quick and detailed response.

We can close this thread.

**Comment by Elliot67** [comment]
@raycastbot close this issue
