### ISSUE TITLE
[Bitwarden Vault] Cannot successfully run the bw-cli

### ISSUE THREAD

**Issue by haabe** [raycast/extensions#14352]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Raycast Version

1.82.3

### macOS Version

14.6.1

#### Error:
```
Error: Command failed with exit code 1: /Users/<user>/Library/pnpm/global/5/node_modules/@bitwarden/cli/build/bw.js status
/Users/<user>/Library/pnpm/global/5/.pnpm/@bitwarden cli@2024.8.2/node_modules/@bitwarden/cli/build/bw.js:39426
                state.accounts[userId].profile = diskAccount.profile

```

This error might occur if I run bw from the terminal and the environment variable `BITWARDENCLI_APPDATA_DIR` is not set. I the environment variable is set, I can successfully run bw from the command line - but the extension still fails.

### Steps To Reproduce

1. Install latest version of bw cli using (p)npm
2. Set env param using export BITWARDENCLI_APPDATA_DIR=~/.bw
3. install and set up Raycast with the extension
4. Set up the API credentials for the extension
5. Try one of the Bitwarden endpoints (Search vault, ...)
6. See that you are prompted for the master password for a mere second or two before it crashes

### Current Behaviour

Crashes bw before logging in

### Expected Behaviour

Let bw make use of the defined env param

**Comment by jomifepe** [comment]
Hey, this is more of an issue related with how raycast works. Extensions run in an isolated environment, running something like `export BITWARDENCLI_APPDATA_DIR=~/.bw` won't be reflected in the extension's shell.

Can you explain what you're trying to achieve with setting the `BITWARDENCLI_APPDATA_DIR`? The extension is already setting it on launch.

**Comment by haabe** [comment]
> Can you explain what you're trying to achieve with setting the `BITWARDENCLI_APPDATA_DIR`? The extension is already setting it on launch.

There was a recent bug fix for the [diskAccount.profile bug for bw-cli](https://github.com/bitwarden/clients/issues/9646), but until it was released the proposed workaround was setting the [BITWARDENCLI_APPDATA_DIR](https://github.com/bitwarden/clients/issues/9646).

And, as I know the BITWARDEN_APPDATA_DIR was set in my terminal environment, I supposed the error be related to it not being set for the extension somehow.

**Comment by haabe** [comment]
Anyhow, my main problem is that the extension crashes before I manage to authenticate. All i get is this screen (and the provided error):
![image](https://github.com/user-attachments/assets/e46cacaf-1593-47ee-8a2a-92b90c1e4e59)

```
Error: Command failed with exit code 1: /Users/<user>/Library/pnpm/global/5/node_modules/@bitwarden/cli/build/bw.js status
/Users/<user>/Library/pnpm/global/5/.pnpm/@bitwarden+cli@2024.8.2/node_modules/@bitwarden/cli/build/bw.js:39426
                state.accounts[userId].profile = diskAccount.profile;
                                                             ^

TypeError: Cannot read properties of null (reading 'profile')
    at StateService.<anonymous> (/Users/<user>/Library/pnpm/global/5/.pnpm/@bitwarden+cli@2024.8.2/node_modules/@bitwarden/cli/build/bw.js:39426:62)
    at Generator.next (<anonymous>)
    at /Users/<user>/Library/pnpm/global/5/.pnpm/@bitwarden+cli@2024.8.2/node_modules/@bitwarden/cli/build/bw.js:39337:71
    at new Promise (<anonymous>)
    at state_service_awaiter (/Users/<user>/Library/pnpm/global/5/.pnpm/@bitwarden+cli@2024.8.2/node_modules/@bitwarden/cli/build/bw.js:39333:12)
    at /Users/<user>/Library/pnpm/global/5/.pnpm/@bitwarden+cli@2024.8.2/node_modules/@bitwarden/cli/build/bw.js:39421:61
    at StateService.<anonymous> (/Users/<user/Library/pnpm/global/5/.pnpm/@bitwarden+cli@2024.8.2/node_modules/@bitwarden/cli/build/bw.js:39898:44)
    at Generator.next (<anonymous>)
    at /Users/<user>/Library/pnpm/global/5/.pnpm/@bitwarden+cli@2024.8.2/node_modules/@bitwarden/cli/build/bw.js:39337:71
    at new Promise (<anonymous>)

Node.js v20.15.1

/Users/<user>/Library/pnpm/global/5/.pnpm/@bitwarden+cli@2024.8.2/node_modules/@bitwarden/cli/build/bw.js:39426
                state.accounts[userId].profile = diskAccount.profile;
                                                             ^
´´´

**Comment by blacroix** [comment]
Try to uninstall the extension (keeping the bw CLI installed) and install back the extension. It ends up working that way for me.

**Comment by haabe** [comment]
That fixed it, @blacroix. My guess is that BITWARDENCLI_APPDATA_DIR is set on extension install based on whatever value it has at that time. So if it isn't set, it will forever be faulty (unless you reinstall).

**Comment by jomifepe** [comment]
> That fixed it, @blacroix. My guess is that BITWARDENCLI_APPDATA_DIR is set on extension install based on whatever value it has at that time. So if it isn't set, it will forever be faulty (unless you reinstall).

I don't think that's the issue, the `BITWARDENCLI_APPDATA_DIR` is pointing to the extension support path, which won't change. As I said, the extension doesn't have access to your shell's `BITWARDENCLI_APPDATA_DIR`.
