### ISSUE TITLE
[Brew] Brave Browser or any cask install attempt

### ISSUE THREAD

**Issue by FlippityFloppityFloopy** [raycast/extensions#14350]
### Extension

https://raycast.com/nhojb/brew

### Raycast Version

1.82.3

### macOS Version

14.6.1

#### Error:
```
Error: Command failed: /opt/homebrew/bin/brew info --json=v2 --installed
/bin/sh: /opt/homebrew/bin/brew: No such file or directory

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at Pipe.<anonymous> (node:net:338:12)
```

### Steps To Reproduce

1) Type Brew / Search / Brave browser. 2) click install.

### Current Behaviour

stops at prompt

### Expected Behaviour

Install Brave Browser or any other app.

**Comment by ashokbaruaakas** [comment]
/opt/homebrew/bin/brew: No such file or directory

@FlippityFloppityFloopy 

It looks like Homebrew is either not installed on your system or it has been installed in a custom location.

- If Homebrew is not installed, you can install it by following the instructions [here](https://docs.brew.sh/Installation).
- If Homebrew is installed in a custom location, follow these steps:

1. Open the Raycast extension window.
![image](https://github.com/user-attachments/assets/827396da-0ae5-46c0-9859-b6a37993a5cc)

2. Set the custom Homebrew executable path.
![image](https://github.com/user-attachments/assets/e20503e3-3ba3-4273-8141-01e9d41d8ddf)

**Node: You can find the correct path by running the following command in your terminal:**
`which brew`

**Comment by ashokbaruaakas** [comment]
@raycastbot close this issue
