### ISSUE TITLE
[Easy Dictionary] Doesnt work any translation

### ISSUE THREAD

**Issue by artexhibit** [raycast/extensions#14357]
### Extension

https://www.raycast.com/isfeng/easydict

### Raycast Version

1.82.3

### macOS Version

14.6.1

### Description

Installed this extension. Enter any word, press enter - nothing works. Just infinite load

### Steps To Reproduce

In extension settings first language English, second is Russian, turned on only Google Translate and Detect Language Speed First. Everything else is unchecked

**Comment by tisfeng** [comment]
Sorry, tested on my computer and everything runs fine, I can't reproduce the problem you mentioned.

Please try to turn on the Baidu language detection option.

<img width="1098" alt="69694" src="https://github.com/user-attachments/assets/a44fe240-313b-4e02-96b8-990a4489168b">

**Comment by artexhibit** [comment]
> Sorry, tested on my computer and everything runs fine, I can't reproduce the problem you mentioned.
> 

I don't know how to reproduce it, it's just not working 🤔. Sometimes I write a word and it shows translation (1 try from 10-15). Tried with on and off VPN.

The thing is Translate extension is working with the same Google Translate seamlessly... Please take a look a video where I show your extension and iTranslate

https://github.com/user-attachments/assets/147b8f66-a7c0-42d6-8579-7e9b1df57694

**Comment by tisfeng** [comment]
It may be that the language detection API has encountered a malfunction. I will improve this part of the code later.

Please try enabling the `Use System Proxy` option, which may help.

<img width="1000" alt="16626" src="https://github.com/user-attachments/assets/f067ea35-fc5d-451c-9002-60d287db2483">

**Comment by artexhibit** [comment]
Thank you. I tried Use system proxy option. The same result 😩 I just like your extension more than iTranslate, hope you can fix it 🙏

**Comment by artexhibit** [comment]
Yeah, now it works good! Thank you! Wait for Raycast release!

**Comment by tisfeng** [comment]
Feel free to open an issue if you have any problems. I'll check it out when I have some time.

Later, I will release a version update for Raycast.

**Comment by tisfeng** [comment]
PR https://github.com/raycast/extensions/pull/14448
