### ISSUE TITLE
[Raindrop.io] ... Request for Raycast

### ISSUE THREAD

**Issue by egoldy** [raycast/extensions#14363]
### Extension

https://www.raycast.com/lardissone/raindrop-io

### Description

Two things:

1) I think I can only add tags that exist - can't create new tags.
2) Why can't I rename the title of the Raindrop bookmark - it only stores the URL name?

### Who will benefit from this feature?

Everyone who uses Raindorp and Raycast - surprised it doesn't exist

**Comment by rien7** [comment]
1. Can't create new tags is limit by raycast component.
2. Fixed in #14458 

@raycastbot close this issue
