### ISSUE TITLE
[GIF Search] Error when copying GIF

### ISSUE THREAD

**Issue by MalteVoelkner** [raycast/extensions#1436]
# Extension – [GIF Search](https://github.com/raycast/extensions/tree/1af80573d1fa71cc30fa3815aef708c8ece3ea54/extensions/gif-search/)
Author: @josephschmitt 

<img width="862" alt="CleanShot 2022-04-19 at 11 39 38@2x" src="https://user-images.githubusercontent.com/13710745/163975830-1ac20be2-7e6d-4ad2-940d-f4059c5fd270.png">

## Description
I’m unable to copy any GIF, even after adding a GIPHY developer link and allowing 'Apple Events' in the system settings.

<img width="875" alt="CleanShot 2022-04-19 at 11 38 25@2x" src="https://user-images.githubusercontent.com/13710745/163975683-6551df97-53eb-4369-8e11-70cae0fc0b5d.png">

## Steps To Reproduce
1. Get on my computer
2. Install the GIF Search Extension
3. Try to copy any gif

## The error message
`Failed to copy GIF: "Command failed with exit code 1: osascript -e tell app "Finder" to set the clipboard to ( POSIX file "/private/tmp/314a3b38e1ffce19b21de9e3e8517238/warnerbrosde-R6gvnAxj2ISzJdbA63.gif" )
21:140: execution error: Keine Berechtigung zum Senden von Apple-Events an Finder. (-1743)"`

### Raycast version
Version: 1.32.1

**Comment by josephschmitt** [comment]
Thanks for this. We're seeing it randomly and have been having trouble tracking it down. I'll let you know what we find

**Comment by thomaspaulmann** [comment]
> Keine Berechtigung zum Senden von Apple-Events an Finder.

Good to be German :-) Looks like permissions don't work.

**Comment by josephschmitt** [comment]
In the mean time you should be able to use the other actions, which let you copy the url to the gif among other things.

**Comment by thomaspaulmann** [comment]
![CleanShot 2022-04-20 at 4 56 07](https://user-images.githubusercontent.com/12066405/164272636-8ce55f30-9134-4163-8e4e-e6b94d8828ea.png)

Can you check if this permission is turned on as well?

**Comment by MalteVoelkner** [comment]
Thank you, that worked! Not these permissions exactly, but the 'Finder' permission under 'Raycast' did the trick for me. Thanks

![CleanShot 2022-04-21 at 09 54 47](https://user-images.githubusercontent.com/13710745/164407208-8c80ec99-2947-4554-a8a3-a0f7364d193b.png)
!

**Comment by thomaspaulmann** [comment]
@josephschmitt I think the Finder permission is necessary to copy the file. We should make it an API to avoid this. Noted on our end.

**Comment by josephschmitt** [comment]
> @josephschmitt I think the Finder permission is necessary to copy the file. We should make it an API to avoid this. Noted on our end.

Just curious why only some people run into this

**Comment by thomaspaulmann** [comment]
@josephschmitt This is because some users might have granted the permission already in Raycast for something else. We should add a way to check and grant permissions from within extensions in the long run.
