### ISSUE TITLE
[Home Assistant] Error status code 400 when trying to change fan speed

### ISSUE THREAD

**Issue by golflabel** [raycast/extensions#14362]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Raycast Version

1.81.3

### macOS Version

14.6.1

### Description

Whenever I navigate to any fans in my Home Assistant setup with Raycast and try to adjust their speed, I get an error code 400 and the speed doesn't change. I am able to toggle the fan on/off, however, just fine using the return key or turn the fans on or off using the ⌘+O and ⌘+F shortcuts.
![error status code 400 when trying to change fan speed](https://github.com/user-attachments/assets/4984451a-d8f2-4b78-81a0-23a8d141e93e)

### Steps To Reproduce

1. Running macOS 14.6.1 and Raycast 1.82.3
2. Running Home Assistant on an Intel NUC with the following versions: Core 2024.7.3, Supervisor 2024.08.0, Operating System 12.4, Frontend 20240710.0
3. Use Raycast to navigate to "Fans" entities/devices
4. Attempt to change speed of any individual fan (toggling and turning on/off works just fine, it's only speed changes that result in the error status code 400)

**Comment by tonka3000** [comment]
@golflabel Interesting. I have no fan myself. Can you try the service call command to adjust the speed of your fan?

**Comment by golflabel** [comment]
Sure, how do I do that?

**Comment by tonka3000** [comment]
There is a command call `Services`. Start it.
Then you can see basically the same as on  the developer tools page/actions from home assistant itself.

There are a couple of fan commands there which you can try out like `fan.turn_on` or `fan.percentahe`. Fill out the values and check if one of them works.

Currently the `fan.turn_on` command is used in the background of the raycast command, maybe we need to change it to a different one.

**Comment by golflabel** [comment]
Ah gotcha! I just tried that and it works great. I've got three-speed fans that I'm using it with and tried 33%, 66%, and 100% and all worked as expected when using the `Services` command in Raycast.

**Comment by tonka3000** [comment]
That is good to hear. You can create a Quicklink for now if you only use them with one fan.

What service call/action did you use exactly? `fan.turn_on`, `fan.percentage` or a different one.

Would be good to have the yaml verison of the call. I can put it behind the current action in the Raycast command to fix the issue.
