### ISSUE TITLE
[Window Management] Next / Previous Display broken (can be fixed by resetting keybindings)

### ISSUE THREAD

**Issue by janeklb** [raycast/extensions#14389]
### Description

There's a (now closed) ticket about something similar here: https://github.com/raycast/extensions/issues/12493 

The issue is basically the same as described above; however, this relates to the "Next _Display_" command, and it can be (temporarily) fixed by resetting the hotkey.

The fix (described below) gets reset eventually.. i'm not exactly sure when/how. I haven't restarted my laptop and I've had to apply it a handful of times. It does (temporarily) resolve the issue though.

### Steps To Reproduce

1. Try to use the Next Display command (Ctrl + Option + Command + Right Arrow)
2. Notice nothing happens
3. Change the hotkey to something else (eg. Shift + Ctrl + Option + Command + Right Arrow)
4. Use the command (✅ it works)
5. Change the hotkey back to the original (Ctrl + Option + Command + Right Arrow)
6. Use the command (✅ it works again!)

**Comment by fgeierst** [comment]
Probably fixed in 1.83.0 
> Window Management: Fixed Next/Previous Display shortcuts not working after attaching new displays while Raycast is running

**Comment by wilcoschoneveld** [comment]
I had this issue before and I can confirm this is fixed in 1.83.0

**Comment by vietdv277** [comment]
I had the same issue with MacOS 15.0.1 and Raycast 1.83.2. Next/Preview Display works, but Next/Preview Desktop does not.

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊

**Comment by hitzhangjie** [comment]
1.86.1 still not fixed.

**Comment by xxxzsgxxx** [comment]
I have the same issue. 
macos 13.7.8 , raycast 1.103.3

**Comment by mathieudutour** [comment]
Please see my message above
