### ISSUE TITLE
[Safari] Search Bookmarks command doesn't work

### ISSUE THREAD

**Issue by alexschcom** [raycast/extensions#14384]
### Extension

https://www.raycast.com/loris/safari

### Raycast Version

1.82.3

### macOS Version

14.6.1

### Description

Whenever I run the command, I get an error message saying "Something went wrong". Error log below:

#### Error:
```
Error: maxObjectCount exceeded

He.parseBuffer:bplistParser.js:92:10

---
89:   }
90: 
91:   if (numObjects > exports.maxObjectCount) {
92:     throw new Error("maxObjectCount exceeded")

### Steps To Reproduce

1. Open Raycast
2. Run command "Search Bookmarks"

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by iwex** [comment]
@alexschcom hello! you have more bookmarks than https://github.com/joeferner/node-bplist-parser can parse.

**Comment by alexschcom** [comment]
I see -- `maxObjectCount` is over 32K but I'm not familiar with plist files and didn't realize there's multiple objects/bookmark, decreasing the total number of "allowed" bookmarks significantly.

FYI for anyone else running into this issue in the future: I deleted some old bookmarks, getting my total down to ~2920 and it finally worked. It seems like the number of objects/bookmark can vary, but this should give you some idea...
