### ISSUE TITLE
[Visual Studio Code] change icon of extension and command depending on chosen build

### ISSUE THREAD

**Issue by jake-101** [raycast/extensions#14395]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

I started using Cursor instead of VS Code. I was happy to find that this extension is able to use Cursor. I went and added aliases so I can type "open with cursor" or "cursor projects" but wish that the icon for the extension would match the chosen build. It's not a big change but a nice quality of life improvement.

### Who will benefit from this feature?

picky people that want visual consistency

### Anything else?

![CleanShot 2024-09-09 at 17 22 19@2x](https://github.com/user-attachments/assets/3bfe12db-9d54-4ebc-a40c-e65a83898459)

**Comment by erics118** [comment]
This currently isn't possible with the current APIs.

**Comment by tmwrnr** [comment]
@raycastbot close this issue
