### ISSUE TITLE
[Spotify Controls] ...

### ISSUE THREAD

**Issue by methilal** [raycast/extensions#14396]
### Extension

https://www.raycast.com/thomas/spotify-controls

### Raycast Version

1.82.4

### macOS Version

14.6.1

### Description

I've been getting this error lately when I try to toggle private mode on. 

![CleanShot 2024-09-10 at 10 58 17](https://github.com/user-attachments/assets/69fb1a9a-c2d0-477b-83c3-21a714af2b3b)

![CleanShot 2024-09-10 at 10 59 44](https://github.com/user-attachments/assets/a78d1f6e-ec71-4bbc-919f-b3d6b6c8b01b)

### Steps To Reproduce

1. Open Raycast
2. Select "Toggle private session"

Not sure how to reproduce it exactly

### Current Behaviour

Gives an error. Its very likely permission error

### Expected Behaviour

It toggles private mode on and off.

**Comment by neehhaa06** [comment]
Hello!! @raycastbot, @methilal  :)

fix: #14396


Please, check macOS privacy settings to ensure Raycast has permission to control Spotify. Update or reinstall both Raycast and the Spotify Controls extension. Reauthorize Spotify access within Raycast if needed. If the problem persists, consult Raycast support or forums for additional help.
