### ISSUE TITLE
[Notion] Rename connection that is shown when creating a new database page 

### ISSUE THREAD

**Issue by timonbimon** [raycast/extensions#14392]
### Extension

https://www.raycast.com/notion/notion

### Description

<img width="432" alt="image" src="https://github.com/user-attachments/assets/ec2b46f1-7445-4c5a-9b1e-27e26d29fff4">
We have multiple people in our Notion workspace using the Raycast Notion extension. Would be great if we could still keep track of who added which page by being able to distinguish between the different Raycast Extensions 👀

### Who will benefit from this feature?

Anyone collaborating with multiple people on Notion.

**Comment by zsidnam** [comment]
This would be a great feature but unfortunately It looks like the Notion API does not support changing those properties: https://developers.notion.com/reference/post-page

![CleanShot 2024-09-09 at 08 08 48](https://github.com/user-attachments/assets/92953e51-058c-459b-82cc-032e56133c39)

**Comment by timonbimon** [comment]
<img width="958" alt="image" src="https://github.com/user-attachments/assets/8c52794b-b37b-4978-b614-097698b72872">
Would there be any way to change the name of the connection itself from "Raycast Extension" to something personalized I can configure in the extension? :) That would also solve the problem if I could call it "Timon's Raycast Extension"

**Comment by timonbimon** [comment]
Yea make sense! Thanks a lot for looking into this for me. 🤗
