### ISSUE TITLE
[Apple Reminders] Could not communicate with worker

### ISSUE THREAD

**Issue by yanjieee** [raycast/extensions#14390]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Raycast Version

1.82.3

### macOS Version

14.1.1 (23B81)

#### Error:
```
Error: Could not communicate with worker


```

![CleanShot 2024-09-09 at 15 52 53@2x](https://github.com/user-attachments/assets/7a66e2ba-825a-4e92-a7e3-f187839ab0ea)

### Steps To Reproduce

click any option in the status bar

**Comment by thomaslombart** [comment]
Can you copy the error log you're getting? You can do that by opening the action panel (⌘ + K) when you encounter the error screen.

**Comment by thomaslombart** [comment]
I'm closing this issue to maintain a clean backlog. Feel free to comment it if you still have the problem.
