### ISSUE TITLE
Cannot fetch google.com favicon or any website at all...

### ISSUE THREAD

**Issue by qbert392** [raycast/extensions#14407]
### Extension

https://www.raycast.com/vimtor/get-favicon

### Raycast Version

1.82.3

### macOS Version

14.6.1

#### Error:
```
Error: EACCES: permission denied, open '/Users/jayden/Downloads/npNFaYzWRZ5X_iG4o_VWs.png'


```

### Steps To Reproduce

1. CMD + SPACE
2. Write *favicon*
3. Hit `tab`
4. Write "google.com"

**Comment by neehhaa06** [comment]
Hello!! @raycastbot :)

fix: #14407


First, make sure Raycast has the required write access by checking the permissions for the {Downloads} folder before attempting to fix the issue. To make sure Raycast can access the file system correctly, you can give it Full Disk Access via System Settings. If the issue persists, consider using an alternative folder, like {Documents}, as Raycast is more likely to have write access there.
