### ISSUE TITLE
[Git Repos] Be able to run commands/scripts on a repository

### ISSUE THREAD

**Issue by SamuelGadiel** [raycast/extensions#14406]
### Extension

https://www.raycast.com/moored/git-repos

### Description

It would be great to execute a script or command in that repository.
For example, I could attach a shortcut (like Alt + Enter) to run a pre-defined script that cleans the repository and reinstalls the packages dependencies.
Or maybe a script that starts a node server, or run vite for react.

My particular usecase would be to hit a shortcut that would run a script that opens the repository in multiple programs, like VS Code, iTerm2 (terminal) and Github Desktop.

But the idea is to run any script the user creates, just selecting it instead of selecting an app in the configuration dropdown.

### Who will benefit from this feature?

Anyone who would like to have more customization when using the extension to manipulate the repository

**Comment by nitishpdmn** [comment]
You can already achieve this behavior by using Automator (builtin macOS app) to create an app that calls a script to do what you want.

![Screenshot 2024-09-10 at 1 11 27 PM](https://github.com/user-attachments/assets/41a009a1-7636-4a2c-9a94-156a1c25ce79)
