### ISSUE TITLE
[Gif Search] Obfuscate filename in clipboard so it doesn't kill the joke. 

### ISSUE THREAD

**Issue by seanparkross** [raycast/extensions#14413]
### Extension

https://raycast.com/josephschmitt/gif-search

### Description

When pasting a gif into an app like Slack (which is where 99.99999% of all the gifs I need go) It displays the long text filename above the image. This kind of kills the joke in most cases. 

EG: 
> User 1: 
> {{Obvious statement}}
> 
> User 2: 
> funny-reaction-gif-to-an-obvious-statement.gif
> {{actual-hilarious-gif}}

This is devastating to comedy. 

I'm thinking the solution would just be a preference to obfuscate the filename in the clipboard to `gif.gif` or something. 

Can we do this. Do you folks have time? Should I PR this?

### Who will benefit from this feature?

Humanity.

**Comment by thomaslombart** [comment]
Could you share a recording? It'll make it easier to see what's happening. Also, does it happen for all GIFs or just some of them?

**Comment by seanparkross** [comment]
PR here: https://github.com/raycast/extensions/pull/15178
🎉

**Comment by seanparkross** [comment]
Hey @thomaslombart 
The PR is updated. Could I get a merge over there 🙏 🙏 🙏 
Thanks!
