### ISSUE TITLE
Can't send message with marketplace shortcut

### ISSUE THREAD

**Issue by Mathisgdi** [raycast/extensions#14412]
### Extension

https://www.raycast.com/thomaslombart/messages

### Raycast Version

1.82.4

### macOS Version

15.0 Beta (24A5331b)

#### Error:
```
Error: Command failed with exit code 1: osascript
52:101: execution error: Not authorised to send Apple events to System Events. (-1743)

Q9:run-applescript.js:38:21

---
35:         timedOut,
36:         command: "osascript",
37:         options,
38:         parentError: new Error(),
39:     })

### Steps To Reproduce

1. open send message shortcut
2. choose contact and write message
3. send message 

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by thomaslombart** [comment]
Could you check if Raycast has the Automation permission enabled in `System Settings > Privacy & Security > Automation`?

**Comment by Mathisgdi** [comment]
Hello,

Here is the permission of raycast in system settings
***@***.***

From: Thomas Lombart ***@***.***>
Date: Sunday, 22 September 2024 at 09:48
To: raycast/extensions ***@***.***>
Cc: Mathis Ghidotti ***@***.***>, Author ***@***.***>
Subject: Re: [raycast/extensions] Can't send message with marketplace shortcut (Issue #14412)

Could you check if Raycast has the Automation permission enabled in System Settings > Privacy & Security > Automation?

**Comment by Mathisgdi** [comment]
Hello, here is the permission of raycast
<img width="449" alt="image" src="https://github.com/user-attachments/assets/38d41aa6-f471-44fd-b0ef-02a252847175">

**Comment by thomaslombart** [comment]
So that's why you need to give Raycast the `System Events` permission, because it's using AppleScript under the hood to send a message.

**Comment by Mathisgdi** [comment]
It's working now, thanks !
