### ISSUE TITLE
[Todoist] Feature to Schedule Tasks recurrently (Everyday, Every Week,  Every Month)

### ISSUE THREAD

**Issue by geraldaddey** [raycast/extensions#14423]
### Extension

https://www.raycast.com/doist/todoist

### Description

Allow to schedule tasks by detecting keywords like everyday, every week, every month, etc. 

This would be very useful for the following use cases: 
- [ ] Quick Add Task 
- [ ] Edit Task
- [ ] Add Time Reminder

### Who will benefit from this feature?

All Users!!!!

### Anything else?

Let me know what changes are required. I can make sometime to work on this during the weekends because I find it very useful and It's currently lacking!

**Comment by thomaslombart** [comment]
This should already be possible for the Quick Add Task command. It's not possible for the others as we're not using Todoist's NLP for them.

**Comment by geraldaddey** [comment]
Is it possible to include the Todoist NLP in scheduling tasks?

**Comment by thomaslombart** [comment]
It's unfortunately not possible as you can use Todoist's NLP just when you [quick add an item](https://developer.todoist.com/sync/v9/#quick-add-an-item) 😕

**Comment by thomaslombart** [comment]
I'm closing this issue to maintain a clean backlog. Feel free to comment it if you still have the problem.
