### ISSUE TITLE
[Home Assistant] New action: Reload configuration

### ISSUE THREAD

**Issue by robdejonge** [raycast/extensions#14428]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Description

Under 'Developer Tools → YAML' in Home Assistant, there are a number of options for reloading parts of the configuration, as well as checking the entire configuration and restarting Home Assistant. It would be super useful to have a 'Reload configuration' action, where I can then select which of these parts (or all of it) I would like to reload. 

### Who will benefit from this feature?

People who do a lot of configuration of their Home Assistant in YAML.

**Comment by tonka3000** [comment]
@robdejonge Try out the `Services` command and search for the specific reload action. You can make a quick link out of it for fast access.

**Comment by robdejonge** [comment]
The services command also lists all scripts, automation toggles, etc. That isn't really the kind of easy access I had in mind when I submitted the feature request :-) 

I'm trying to make it so that I don't need to keep a web browser open while I'm working on my configuration, and can quickly reload parts of or the whole configuration. That's kind of the point of Raycast in my opinion, to get things done quickly. 

But as I said in my other feature request ... it's your extension, so you get to decide what features get added!
