### ISSUE TITLE
[SnippetSurfer] Improve display for root level directory

### ISSUE THREAD

**Issue by slhck** [raycast/extensions#14431]
### Extension

https://www.raycast.com/astronight/snippetsurfer

### Raycast Version

current

### macOS Version

14

### Description

The default presentation of snippets in the root directory is a bit awkward:

### Steps To Reproduce

- Create a snippet YAML file in the root of the snippets directory

### Current Behaviour

<img width="862" alt="image" src="https://github.com/user-attachments/assets/fbce6045-8b05-4223-8c4b-727960633725">

### Expected Behaviour

It would be better to show the folder only when it's not ".", and just show it below the title, e.g.:

```typescript
import { List } from "@raycast/api";
import type { Snippet, SnippetContent } from "../types";

const SnippetContent = ({ snippet }: { snippet: Snippet }) => {
  const getMarkdown = () => {
    const title = snippet.content?.title ?? snippet.name ?? "";
    const description = snippet.content?.description ?? "";
    const content = snippet.content?.content ?? "";
    const folder = snippet.folder ?? "Inbox";
    const descriptionTxt = description
      .split("\n")
      .map((d) => `> ${d}`)
      .join("\n");

    const tags = snippet.content?.tags ?? [];
    const tagsStr = tags.map((tag) => `\`${tag}\``).join(" ");

    let markdown = `### ${title}\n`;
    if (folder !== ".") {
      // exclude root folder from display
      markdown += `**${folder}**\n`;
    }
    markdown += `\n${tagsStr}\n${descriptionTxt}\n\n${content}`;
    return markdown;
  };

  return <List.Item.Detail markdown={getMarkdown()} />;
};

export default SnippetContent;
```

**Comment by mkitane** [comment]
Agreed, we can simplify the view for the root folder, can you open a PR with the expected behavior?

**Comment by slhck** [comment]
Could you perhaps just copy my code suggestion to your local checkout if you agree with it? I haven't currently got the time to clone this several gigabytes repo and go through the release/PR process.
