### ISSUE TITLE
[Cron] ... Two months side by side

### ISSUE THREAD

**Issue by collinbell** [raycast/extensions#14437]
### Extension

https://www.raycast.com/astrit/cron

### Description

It would be nice if you could put months next to each other left to right as an option (see two months at once).

### Who will benefit from this feature?

People who want less clicking; faster information.

**Comment by ridemountainpig** [comment]
I think putting a two month calendar in one view will make it too compact.

**Comment by astrit** [comment]
@collinbell 

The way how the Calendar works is using the Grid and the prop `columns` which states 

```
Column count for the grid's sections. Minimum value is 1, maximum value is 8.
```

So we can't have more than that or horizontal scroll and you need for months side by side at least 14 columns which as of now is not possible using the Grid. 

✌️
