### ISSUE TITLE
[Bitwarden Vault] TypeError: Cannot read properties of null (reading 'profile')

### ISSUE THREAD

**Issue by blacroix** [raycast/extensions#14443]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Raycast Version

1.82.5

### macOS Version

14.6.1

#### Error:
```
Error: Command failed with exit code 1: /Users/x/.nvm/versions/node/v20.17.0/bin/bw status
/Users/x/.nvm/versions/node/v20.17.0/lib/node_modules/@bitwarden/cli/build/bw.js:39426
                state.accounts[userId].profile = diskAccount.profile;
                                                             ^

TypeError: Cannot read properties of null (reading 'profile')
    at StateService.<anonymous> (/Users/x/.nvm/versions/node/v20.17.0/lib/node_modules/@bitwarden/cli/build/bw.js:39426:62)
    at Generator.next (<anonymous>)
    at /Users/x/.nvm/versions/node/v20.17.0/lib/node_modules/@bitwarden/cli/build/bw.js:39337:71
    at new Promise (<anonymous>)
    at state_service_awaiter (/Users/x/.nvm/versions/node/v20.17.0/lib/node_modules/@bitwarden/cli/build/bw.js:39333:12)
    at /Users/x/.nvm/versions/node/v20.17.0/lib/node_modules/@bitwarden/cli/build/bw.js:39421:61
    at StateService.<anonymous> (/Users/x/.nvm/versions/node/v20.17.0/lib/node_modules/@bitwarden/cli/build/bw.js:39898:44)
    at Generator.next (<anonymous>)
    at /Users/x/.nvm/versions/node/v20.17.0/lib/node_modules/@bitwarden/cli/build/bw.js:39337:71
    at new Promise (<anonymous>)

Node.js v20.15.1

/Users/x/.nvm/versions/node/v20.17.0/lib/node_modules/@bitwarden/cli/build/bw.js:39426
                state.accounts[userId].profile = diskAccount.profile;
                                                             ^
```

### Steps To Reproduce

1. install the extension
2. install Bitwarden CLI: `npm install -g @bitwarden/cli`
3. define clientId, clientSecret and Bitwarden CLI Path
4. try Search Vault command

NB: I even connect using clientId and clientSecret on CLI: it works; I can search my vault using the CLI. It fails using Raycast + Bitwarden extension ;(

### Current Behaviour

I got an error 'Something went wrong' just after typing my master password.

### Expected Behaviour

Be able to search my vault ;)

**Comment by blacroix** [comment]
Sorry, I guess it's the same issue of https://github.com/raycast/extensions/issues/14352

**Comment by blacroix** [comment]
And https://github.com/raycast/extensions/issues/14123 ;(

**Comment by blacroix** [comment]
I found a way to make it work! The extension should be installed AFTER the CLI.

**Comment by jomifepe** [comment]
Hey, great that you got it working. I still have to investigate what is getting saved that is causing this issue (https://github.com/raycast/extensions/issues/14123#issuecomment-2337515018). Thanks for providing a solution here 🙂

**Comment by jomifepe** [comment]
@raycastbot close this issue
