### ISSUE TITLE
[Auto Quit App] Lower timer to quit

### ISSUE THREAD

**Issue by Hydro8** [raycast/extensions#14449]
### Extension

https://www.raycast.com/koinzhang/auto-quit-app

### Description

Hi
Is it possible to reduce the delay to quit an app like 1mn ?
Or is it possible to quit an app when we close the last window of this app ?
Thanks !

**Comment by koinzhang** [comment]
Thanks for your feedback, currently reducing the minimum detection interval to 1m in #14689, not to seconds because of performance considerations.

**Comment by koinzhang** [comment]
@raycastbot close this issue
