### ISSUE TITLE
[Battery Optimizer] Discharge Battery

### ISSUE THREAD

**Issue by cancel-cloud** [raycast/extensions#14445]
### Extension

https://www.raycast.com/Qetesh/battery-optimizer

### Description

It would be great to have a discharge option for the battery. That way, if you know you'll always be plugged in—for instance, during the weekend—the battery could discharge to, let's say, 20%, and the MacBook could run directly from the power supply.

### Who will benefit from this feature?

the battery would not be used for that time.

**Comment by Qetesh** [comment]
Thank you for the suggestion! As this project is based on [bclm](https://github.com/zackelia/bclm) with a focus on simplicity, a discharge feature isn’t feasible. Also, note that bclm doesn’t support macOS versions above 15.0.

**Comment by Qetesh** [comment]
@raycastbot close as not planned
