### ISSUE TITLE
[Coffee] Add Option to Start Screensaver

### ISSUE THREAD

**Issue by MrUltimate** [raycast/extensions#14452]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

Hi,

Loving this extension! It's the only way I can override my company's very aggressive sleep policy (which makes no sense since I work from home) but I'd love to request an additional feature!

Right now, the display stays awake no matter what, but I'd love an option to start the screensaver **but not put the display to sleep** (bonus if it doesn't lock the computer either). 

It would also be amazing if we can also get an option to control the time after which the screensaver is triggered (again this is useful for people who's enterprise policies don't let them control sleep/wake/screensaver times).

Thanks for the work on this!

### Who will benefit from this feature?

**This is extremely useful for OLED monitor owners looking to prevent burn in!**

**Comment by pernielsentikaer** [comment]
I don't think it's possible 🫠
