### ISSUE TITLE
[Logseq] Add current time to quick note

### ISSUE THREAD

**Issue by galligan** [raycast/extensions#1445]
# Extension – [Loseq](https://github.com/raycast/extensions/tree/main/extensions/logseq)

Author: @futantan @sxn

## Describe the feature and the current behavior/state.

I would like the extension to add the current time to the note that I create.

Two approaches possible for this:

- Pre-fill the current time as I start a new note
- or automatically prepend the time to the note

The outcome would create a note that looks like

``` md
- 09:13 Adding a note
```

## Who will benefit from this feature?

Anyone who does bullet journaling with Logseq

Thanks!

**Comment by galligan** [comment]
Will close for the time being!

**Comment by futantan** [comment]
@galligan Please refer to #2111

**Comment by futantan** [comment]
And let me know if this is the feature you want?
Since we have more people requesting this feature, it's time to ship it!

**Comment by galligan** [comment]
Looks great @futantan! Thanks for doing this!
