### ISSUE TITLE
[Obsidian] Tag Picker in 'Create Note' Action Not Working

### ISSUE THREAD

**Issue by bitbalancer** [raycast/extensions#14470]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Raycast Version

1.82.5

### macOS Version

14.6.1 (23G93)

### Description

The tag picker in the ‘Create Note’ action doesn’t recognize typed tags, resulting in no tags being added to the YAML header upon note creation.

![image](https://github.com/user-attachments/assets/be7cd9d6-0535-482e-9d36-efab79cbd593)

### Steps To Reproduce

	1.	Create a new vault without enabling community plugins.
	2.	Create several notes, including notes with nested tags.
	3.	In the “Create Note” action, type a tag in the tags field.
	4.	Complete the note creation process by clicking “Create”.
	5.	Open the newly created note and verify that the tag is absent in the YAML header.

### Current Behaviour

The tag typed in the tags field is absent from the YAML header of the newly created note.

### Expected Behaviour

The tag typed in is expected to be added to the tags property of the newly created note.

**Comment by bitbalancer** [comment]
Update: I realized that the issue I reported was not a bug but rather a misunderstanding on my part. It turns out that the date picker works well. I apologize for any confusion this may have caused.

The behavior is explained here: https://github.com/KevinBatdorf/obsidian-raycast/blob/main/README.md#create-note-1

**Comment by KevinBatdorf** [comment]
Thanks for the effort, regardless ☺️
