### ISSUE TITLE
Battery Menu Bar

### ISSUE THREAD

**Issue by robotflaqd** [raycast/extensions#14485]
### Extension

https://www.raycast.com/panrafal/battery-menubar

### Raycast Version

1.82.5

### macOS Version

12.7.6

### Description

Does not show the number for how much the battery is charged in the Menu bar, just a blank space for the default view. The percentage is an extremely high number for whatever reason. 

<img width="425" alt="Screen Shot 2024-09-16 at 6 01 55 PM" src="https://github.com/user-attachments/assets/deb5123d-3fdf-4e11-95b8-c7fa31dbfcd7">

Other battery app has no problems detecting and showing the correct amount
<img width="434" alt="Screen Shot 2024-09-16 at 6 02 04 PM" src="https://github.com/user-attachments/assets/326349cb-6830-478a-86f3-a0991491f56a">

More screenshots 
<img width="418" alt="Screen Shot 2024-09-16 at 6 02 50 PM" src="https://github.com/user-attachments/assets/c36ed041-a553-46ce-b378-4c66c7110717">
<img width="407" alt="Screen Shot 2024-09-16 at 6 03 01 PM" src="https://github.com/user-attachments/assets/ce71a513-15c4-4850-9012-6a995236c536">
<img width="388" alt="Screen Shot 2024-09-16 at 6 03 10 PM" src="https://github.com/user-attachments/assets/803823ed-ac9f-4441-8444-d279bbe1d434">

I have disabled/enabled many times, deactivated/activated, refreshed it, and done all sorts of toggling; nothing fixed it. 

### Steps To Reproduce

Literally installed the extension and activated it. I played around with all the settings, didn't fix it.

**Comment by robotflaqd** [comment]
I think this is a nice battery app, just that I can't seem to use it at this moment. Hopefully it gets addressed soon

**Comment by ridemountainpig** [comment]
I have installed this extension, and it works successfully. I suggest you try reinstalling the extension.

**Comment by robotflaqd** [comment]
Just uninstalled and reinstalled it. Same problem occurs. 

Hopefully the developers are able to look into this soon.

**Comment by j3lte** [comment]
@robotflaqd Might have to do with the fact you are running MacOS 12, which is pretty old (I'm on 15 now), so it can be that `ioreg` is reporting numbers that should be interpreted differently by the extension... Probably not something the developer can fix, unless someone is running on MacOS 12 and is willing to debug it.

**Comment by robotflaqd** [comment]
Perhaps so, but I honestly don't think MacOS 12 is _that_ old... 

If that's the case, then it's weird how other apps are able to pull battery information (along with other information that `ioreg` is used for) correctly, namely the Stats app getting my battery information (and every other information that app allows) as shown in the screenshot in the post running alongside the Battery Menubar Raycast extension.
