### ISSUE TITLE
[Todoist] Unable to create task

### ISSUE THREAD

**Issue by aadvikkkk** [raycast/extensions#14501]
### Extension

https://www.raycast.com/doist/todoist

### Raycast Version

1.81.2

### macOS Version

15.1 Beta

### Description

When trying to create a quick task on raycast, an error is displayed: 'Unable to create task Request failed with status code 400'
<img width="951" alt="Screenshot 2024-09-17 at 3 07 27 PM" src="https://github.com/user-attachments/assets/f4be034a-754a-48bf-9a1a-1d6af2c5f273">

### Steps To Reproduce

Try to create a quick task using raycast, it will display the error: Unable to create task Request failed with status code 400

### Current Behaviour

Displaying Error:  Unable to create task Request failed with status code 400

### Expected Behaviour

Should Create a task

**Comment by kud** [comment]
Please, use a proper title for this issue. 🙏

**Comment by jfkisafk** [comment]
@raycastbot rename this issue to "[Todoist] Unable to create task"

**Comment by jfkisafk** [comment]
@aadvikkkk 400 statusCode indicates there is a bad request which we may validation with forms. But if this issue is reproducible, can you please share a recording for the inputs that is leading to this error?
