### ISSUE TITLE
[Apple Notes]...

### ISSUE THREAD

**Issue by Astonchoi** [raycast/extensions#14508]
### Extension

https://raycast.com/raycast/apple-notes

### Raycast Version

1.82.5

### macOS Version

 Version 15.0 (24A335)

#### Error:
```
Error: Command failed with exit code 1: osascript
51:122: execution error: Not authorised to send Apple events to Notes. (-1743)
    at uA (/Users/macas/.config/raycast/extensions/8c7187e0-f64c-4dba-ba77-b1cb543256d6/index.js:32:3080)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/macas/.config/raycast/extensions/8c7187e0-f64c-4dba-ba77-b1cb543256d6/index.js:187:1422
```

### Steps To Reproduce

1. Run the "Search Notes" function in Raycast.
2. Select "View Note" from the "Actions" menu.
3. No preview appears, and an error message is displayed.

**Comment by thomaslombart** [comment]
Could you check if Raycast has the automation permission enabled in `System Settings > Privacy & Security > Automation`?

![CleanShot 2024-09-22 at 09 44 16@2x](https://github.com/user-attachments/assets/6447528b-ff38-4e05-a73c-5b5ea65076d6)

**Comment by Astonchoi** [comment]
@thomaslombart Thank you so much! I finally solved the problem!
