### ISSUE TITLE
[Bundlephobia Search] Add Tree Shakeable information

### ISSUE THREAD

**Issue by rushelex** [raycast/extensions#14502]
### Extension

https://www.raycast.com/vette/bundlephobia-search

### Description

The website https://bundlephobia.com has information about whether the package is Tree Shakeable. But the Raycast plugin does not have this information. It is very useful and only for this I have to switch to the website.

### Who will benefit from this feature?

Everyone

### Anything else?

<details>
<summary>Extension doesn't have it:</summary>

![CleanShot 2024-09-17 at 15 14 52](https://github.com/user-attachments/assets/9684b02f-8c6d-408c-bf1d-1f406874e1d1)
</details>

<details>
<summary>But the Bundlephobia website has it:</summary>

![CleanShot 2024-09-17 at 15 16 16](https://github.com/user-attachments/assets/b7ae8cd6-9399-4d4f-acf3-366b003ad2ee)
</details>

**Comment by dgrzedzielski** [comment]
@raycastbot close this issue
