### ISSUE TITLE
[Brew] ... Brew install cancels if no longer in foreground

### ISSUE THREAD

**Issue by anarqist** [raycast/extensions#14509]
### Extension

https://www.raycast.com/nhojb/brew

### Raycast Version

1.82.5

### macOS Version

15.0

### Description

When you try to install something with the brew extension it works just fine, as long as you keep the window `Raycast` in the foreground.  If you want to multitask something in the meantime and the window is no longer in the foreground it cancels the process. 

### Steps To Reproduce

1. Open raycast
2. type [Search] brew ...
3. Confirm installation with chosen object
4. Open another window -> Installation cancels
5. Keep Raycast in the foreground -> Installation successfully finishes. 

### Current Behaviour

As soon as the Raycast Window is no longer in the foreground the installation process stops/cancels. 

### Expected Behaviour

Continue running the command to install `Formulae` or `cask` in the background, even when Raycast is no longer in the foreground.

**Comment by nhojb** [comment]
Unfortunately this behaviour is inherent to Raycast itself and we can't work-around it. Extensions are unloaded by Raycast when the window is closed by the user or after a set timeout.
