### ISSUE TITLE
[AirPods Noise Control] ...

### ISSUE THREAD

**Issue by fwends** [raycast/extensions#14517]
### Extension

https://www.raycast.com/chrahe/airpods-noise-control

### Raycast Version

1.82.5

### macOS Version

14.5 (23F79)

### Description

Does not work just says control center not found, but that is what it's called.
!

### Steps To Reproduce

just run it and you can see it does not work 
it pops up the error ‹ Control Center not found. Check Localization!

### Current Behaviour

When you run it you get this 
‹ Control Center not found. Check Localization!
I did check it and it is called "Control Center" 

### Expected Behaviour

Not this

**Comment by cyxn** [comment]
same issue for me. It seems like someone has to fix it on his own and contribute the fix
