### ISSUE TITLE
[Tower Repositories] Open project in Cursor

### ISSUE THREAD

**Issue by lmartins** [raycast/extensions#14511]
### Extension

https://www.raycast.com/tdwesten/tower

### Description

The same way we can now quickly open a repo in VS Code, would be amazing if we could do the same for other editors, Cursor for example.

### Who will benefit from this feature?

Anyone who depends on an editor that is not listed by default in the app commands.

**Comment by tdwesten** [comment]
Hi @lmartins, 

I have updated the extension so you can select your default editor and terminal.

ref: https://github.com/raycast/extensions/pull/14538

**Comment by tdwesten** [comment]
@raycastbot assign me
