### ISSUE TITLE
[Browser Bookmarks] Doesnt open page on startup in firefox

### ISSUE THREAD

**Issue by fwhotto** [raycast/extensions#14524]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Raycast Version

1.82.5

### macOS Version

14.6.1

### Description

When firefox is not open the selected page is not loaded but it just opens the home page.

### Steps To Reproduce

1. Firefox is not active
2. open a bookmark through the extension

### Current Behaviour

The homepage is opened

### Expected Behaviour

The selected page is opened

**Comment by thomaslombart** [comment]
Could you share a recording? It'll make it easier to see what's happening.

**Comment by fwhotto** [comment]
sure 

https://github.com/user-attachments/assets/9975a6e7-a4ef-4166-9cba-8d3b0763b6e9

**Comment by thomaslombart** [comment]
I was not able to reproduce the bug. Does it happen only when Firefox is not launched yet? Is it the same for all URLs? Do you have the same issue for other browsers?

**Comment by fwhotto** [comment]
The problem was only with firefox. However, I updated to sequoia and the problem seems to no longer occur. It was for any url.
