### ISSUE TITLE
[Keyboard Shortcut Sequences] "Shift" key automatically engages with the first sequence when it is not added

### ISSUE THREAD

**Issue by Ololade121** [raycast/extensions#14528]
### Extension

https://www.raycast.com/HelloImSteven/keyboard-shortcut-sequences

### Raycast Version

1.82.5

### macOS Version

15.0

### Description

When I try to create a sequence, for example, in Notes, if I set the first sequence as ⌘+N to create a new note, it does ⌘+⇧+N to create a new Folder instead.

https://github.com/user-attachments/assets/e3398822-d750-45ac-9fe6-106db4891d0c

### Steps To Reproduce

When I try to create a sequence, for example, in Notes, if I set the first sequence as ⌘+N to create a new note, it does ⌘+⇧+N to create a new Folder instead

### Current Behaviour

Adding the “shift” key to the sequence

### Expected Behaviour

Sequence should be carried out with exactly the keys specified.

**Comment by SKaplanOfficial** [comment]
Hi, you need to use 'n' for the keystroke instead of 'N'. The keystroke simulates typing the exact value of that field, so 'N' is treated as Shift+N. I will clarify this in the field tooltip.
