### ISSUE TITLE
[Unicode Symbols Search] Superscript 1, 2, 3 are missing.

### ISSUE THREAD

**Issue by ATSiem** [raycast/extensions#14533]
### Extension

https://www.raycast.com/mmazzarolo/unicode-symbols

### Raycast Version

1.83.0

### macOS Version

14.6.1

### Description

Superscript 1, 2, 3 are missing.

<img width="763" alt="image" src="https://github.com/user-attachments/assets/3badc1f6-3958-4c96-8acc-f2524486240d">

### Steps To Reproduce

1. unicode search
2. filter by superscripts
3. 1, 2, and 3 are missing.

Related: filtering by a number, i.e. 5, does not display the number or super/subscript choices.

### Current Behaviour

Unable to select superscript 1, 2, 3 (able to select 0 and 4+)

### Expected Behaviour

Able to select superscript 1, 2, 3

**Comment by j3lte** [comment]
![Screenshot 2024-09-18 at 17 54 24](https://github.com/user-attachments/assets/86cbbb40-3a99-4eca-9724-448f6ef846e1)
@ATSiem Currently it seems to be part of a different character set, so it is **NOT** missing. That being said, I might see if we can merge these into "superscripts".

**Comment by j3lte** [comment]
Implemented a fix for this 'problem' (it's not really a problem, but it is confusing), waiting for #14567 to be accepted

**Comment by j3lte** [comment]
@raycastbot rename this issue to "[Unicode Symbols Search] Superscript 1, 2, 3 are missing."

**Comment by ATSiem** [comment]
A similar issue... subscript i does not appear.

If this is not a bug, the UX is very challenging to me.

Should I search for 'subscript i' or something else, in order to find: ᵢ

![image](https://github.com/user-attachments/assets/ea2bc273-f16a-41e8-b254-48025fd06774)

**Comment by j3lte** [comment]
@ATSiem it doesn't seem to be part of the included sets. This extension (in its current form, I am working on a better one) only includes [some character sets](https://github.com/raycast/extensions/blob/af4bff845229973b2bd8f86af0cfbdd26b570399/extensions/unicode-symbols/scripts/generate-dataset.ts#L14). It seems [subscript i](https://www.compart.com/en/unicode/U+1D62) is part of the Phonetic Extensions, which is currently not included.

**Comment by j3lte** [comment]
@ATSiem FYI, with the latest update (#14682) you can now set the dataset to `Full` (see Extension settings) and search for ALL unicode symbols. This only works in Grid mode
