### ISSUE TITLE
[Perplexity API] please add history and bookmark functionality similar to the chatGPT plugin to allow user to revisit a previous query

### ISSUE THREAD

**Issue by kagbodji** [raycast/extensions#14541]
### Extension

https://www.raycast.com/ilian/perplexity-api

### Description

When coding, my workflow consists of researching something by asking perplexity AI, then copying bits of the response to test, and revisit the response to copy / reread the response. However, the response disappears after some time. What would help is the ability to have history (and as a bonus, bookmark the response) to revisit later. This is how the chatGPT plugin currently implements it:

<img width="743" alt="image" src="https://github.com/user-attachments/assets/dcc6b07b-ab01-4a58-aead-a977d25affda">

<img width="743" alt="image" src="https://github.com/user-attachments/assets/40d820ae-1c90-4fbc-8d27-6389d4ef9325">

<img width="743" alt="image" src="https://github.com/user-attachments/assets/7cc786a1-60d9-405d-9342-b97550af2614">

### Who will benefit from this feature?

users who wish to persist responses retrieved from querying perplexity

**Comment by maximilianzuern** [comment]
The "AI Chat" command might be what you are looking for. 
By default, it saves the entire chat.

**Comment by maximilianzuern** [comment]
@raycastbot close this issue
