### ISSUE TITLE
[Apple Notes]search notes error

### ISSUE THREAD

**Issue by zzzli** [raycast/extensions#14544]
### Extension

https://raycast.com/raycast/apple-notes

### Raycast Version

1.82.5

### macOS Version

14.6.1 (23G93)

#### Error:
```
Error: EPERM: operation not permitted, copyfile '/Users/c0257/Library/Group Containers/group.com.apple.notes/NoteStore.sqlite' -> '/var/folders/8d/9_2fp95n29741bgw2nvf03gr0000gn/T/useSQL/aa865ccaf4e687b88d549df73fb673a3e9493d22/db.db'
    at async copyFile (node:internal/fs/promises:623:10)
    at async /Users/c0257/.config/raycast/extensions/8c7187e0-f64c-4dba-ba77-b1cb543256d6/index.js:12:24155
```

### Steps To Reproduce

1、open raycast
2、input search notes
3、error

### Current Behaviour

search notes

### Expected Behaviour

Normal search

**Comment by thomaslombart** [comment]
Could you check if Raycast has the Full Disk Access permission enabled in `System Settings > Privacy & Security > Full Disk Access`?

**Comment by thomaslombart** [comment]
I'm closing this issue to maintain a clean backlog. Feel free to comment it if you still have the problem.
