### ISSUE TITLE
[Unicode Symbols Search] Extension breaks when searching for some symbols

### ISSUE THREAD

**Issue by victor-ajayi** [raycast/extensions#14562]
### Extension

https://www.raycast.com/mmazzarolo/unicode-symbols

### Raycast Version

1.81.2

### macOS Version

macOS 15

#### Error:
```
Error: The operation couldn’t be completed. (Foundation.JSONError error 9.)


```
<img width="775" alt="image" src="https://github.com/user-attachments/assets/a700d7fa-1fe6-4fd7-82e4-546e55fd3921">

### Steps To Reproduce

Search "naira" 

### Current Behaviour

Usually if the symbol doesn't exist it shows a "No Results" empty page. But for some reason when I search the naira symbol, it breaks completely.

**Comment by j3lte** [comment]
![Screenshot 2024-09-19 at 19 56 10](https://github.com/user-attachments/assets/ffc3870f-3eaf-47c7-a710-c2965fcb593f)
I can't seem to reproduce this issue. Given your issue, you might want to update to the latest version of Raycast and see if it still persists... (I'm running `1.83.0`)

**Comment by victor-ajayi** [comment]
It seems the problem is in this setting for the extension. I have mine set to show as a list. I temporarily changed it to grid and it worked fine, doesn't work when it's set to list.

<img width="310" alt="image" src="https://github.com/user-attachments/assets/c39ed667-3f78-41e8-9b01-4516ba159d45">

**Comment by j3lte** [comment]
@victor-ajayi Confirmed it breaks on a list, let me look into it. Thanks for the clarification!

**Comment by j3lte** [comment]
Waiting for the bugfix #14567, it is confirmed it broke on `Ancient Symbols` in List Mode, I created a bugfix for it that should work

**Comment by victor-ajayi** [comment]
Thank you!

**Comment by j3lte** [comment]
This is hopefully now fixed with the latest update 😄 

@raycastbot close this issue
