### ISSUE TITLE
[Open Path] Use utils from `Open Path` in other extensions?

### ISSUE THREAD

**Issue by andrewmartin** [raycast/extensions#14564]
### Extension

https://www.raycast.com/koinzhang/open-path

### Description

This is an excellent extension. I was wondering (and this may be possible)––

Can I somehow use the functions in this extension _in my extension_? I have a custom extension where I'm working with the local filesystem and I'd love to take advantage of the open utils you've created. Just curious if a pattern exists for this that I might've missed.

### Who will benefit from this feature?

Other extension developers.

**Comment by koinzhang** [comment]
Currently the Raycast extension does not support the direct use of functions from another extension.
You can copy the function to your extension and use it.

**Comment by koinzhang** [comment]
@raycastbot close this issue
