### ISSUE TITLE
How do I import and use an ES6 module?

### ISSUE THREAD

**Issue by borkdude** [raycast/extensions#1457]
I am trying this code in my extension:

``` javascript
import { loadString } from 'nbb';

async function foo() {
  console.log(await loadString('(+ 1 2 3)'));
}

foo();
```

but I'm seeing errors about ES6 in `require`. How can I work with ES modules in extensions? I tried setting `"type": "module"` in the extension, but that didn't help. I don't know anything about TypeScript but I did try what they wrote here as well: https://www.typescriptlang.org/docs/handbook/esm-node.html.

<img width="1127" alt="Screenshot 2022-04-21 at 20 12 36" src="https://user-images.githubusercontent.com/284934/164527743-32c02d6b-7c39-4b2e-a6c6-738d00fd0962.png">

**Comment by sxn** [comment]
Hi @borkdude - it should "just work" 😅 

https://user-images.githubusercontent.com/1155589/164545743-df9f8275-acb2-4552-93e3-fbd7cf9cf9eb.mov


The `tsconfig.json` file I used in that example looks like this:
```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Node 16",
  "include": ["src/**/*"],
  "compilerOptions": {
    "lib": ["es2020"],
    "module": "commonjs",
    "target": "es2020",
    "strict": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react-jsx"
  }
}
```

**Comment by borkdude** [comment]
Excellent, I've got something working. Now I'm trying the next step: load an nbb script.

This is what I've got:

``` javascript
import { loadFile } from 'nbb';

async function run() {
  console.log(await loadFile(__dirname+'/script.cljs'));
}

export default run;
```

The file `script.cljs` is located as a sibling file to the `.tsx` file. How can I make sure that it gets copied to the `.config/raycast/extensions/nbb-ext-test` directory?

**Comment by borkdude** [comment]
Got it. When I move `script.cljs` to `assets` and then load it like this:

```
import { loadFile } from 'nbb';
import { environment } from '@raycast/api';

async function run() {
  console.log(await loadFile(environment.assetsPath+'/script.cljs'));
}

export default run;
```
it works!

**Comment by borkdude** [comment]
@sxn I hope you don't mind if I ask another question. Is it possible to return a `Command` component asynchronously? 

```
export default async function Command () {
  const res = await loadFile(environment.assetsPath+'/script.cljs');
  const cmd = res.Command;
  return <cmd/>;
}
```

So here the `script.cljs` returns a promise with an object `Command` which is a React component that I want to use.

**Comment by sxn** [comment]
hi @borkdude - nope, commands cannot be async. What you could do, however, is to use `useEffect` similarly to how I did in the example above to wait for the promise to resolve. Or alternatively you could use [react-use](https://www.npmjs.com/package/react-use)'s [useAsync](https://github.com/streamich/react-use/blob/master/docs/useAsync.md), which does the same thing but with slightly less boilerplate. 😺

**Comment by borkdude** [comment]
If top level await would be supported then the problem would also be solved. Is there a way to build a Raycast extension without outputting cjs (since that seems to be a problem)?

> build failed (src/nbb-ext-test.tsx:6:12 const res = await loadFile(environment.assetsPath+'/script.cljs');): Top-level await is currently not supported with the "cjs" output format

**Comment by borkdude** [comment]
Got it working with `useAsync`!

<img width="563" alt="Screenshot 2022-04-22 at 09 36 21" src="https://user-images.githubusercontent.com/284934/164629520-d63dce89-a842-46cd-b0d4-c2fb948f54c8.png">

<img width="240" alt="Screenshot 2022-04-22 at 09 36 52" src="https://user-images.githubusercontent.com/284934/164629819-e6d2895f-6436-4914-a92c-8fe01e8ca8bf.png">

**Comment by borkdude** [comment]
@sxn FYI, I documented how to create an extension with nbb here:

https://github.com/babashka/nbb/tree/main/doc/raycast
