### ISSUE TITLE
getSelectedText appears to return Clipboard.readText() sometimes

### ISSUE THREAD

**Issue by omonk** [raycast/extensions#14583]
### Description

I am wanting to create an extension which creates a markdown link using the URL from the clipboard and the currently selected text. 

The extension code I've put together works for the most part but getSelectedText and Clipboard.readText() often return the same results when they should 100% not.

### Steps To Reproduce

Checkout this repo - https://github.com/omonk/linkdown

1. `npm run dev` to start up the extension
2. Select and copy url (`https://google.com`)
3. Observe the url is in your clipboard history
4. Select a new portion of text from an application
5. Run `linky` command
6. See that the markdown created is either the URL twice [https://google.com](https://google.com) even when the selected text is not the link or JS throws with the error that the URL is invalid, as the URL that has been provided by Clipboard.history is in fact selected text. 

### Current Behaviour

- Clipboard.readText() returns selected text
- getSelectedText() returns the Clipboard.readText()

### Expected Behaviour

- Clipboard.readText() returns the the correct Clipboard.readText()
- getSelectedText() returns the correct selected text

**Comment by mathieudutour** [comment]
Yeah the heuristic of the getSelectedText is to try to use accessibilities APIs but if it can't, it'll try to send a copy command to get the selection. We found that some apps don't behave nicely and we have workaround that with the clipboard :/

Not much we can do here...
