### ISSUE TITLE
[Amazon AWS] Copy/Manage individual secrets

### ISSUE THREAD

**Issue by Falci** [raycast/extensions#14582]
### Extension

https://www.raycast.com/Falcon/aws

### Description

It would be useful if we could manage or copy individual secrets, not only the entire JSON object.

Currently, we can view the secret as a JSON. However, in the AWS webpage, we can view it as individual strings, as well as copy, update or delete them.

### Who will benefit from this feature?

I believe most users of this command could benefit from it.

### Anything else?

Great extension by the way!

**Comment by jfkisafk** [comment]
@raycastbot assign me

**Comment by jfkisafk** [comment]
@raycastbot reopen this issue

**Comment by jfkisafk** [comment]
To keep the scope narrow, we are adding the feature to copy individual secrets as part of the PR. Please create a different issue in case we need to manage secrets b/c the command currently does not offer that. 

Also, please consider that for security reasons, you might need to 2P the production secret values before modifying/deleting them and raycast command might make it a lot easier to bypass checks in your prod.

**Comment by b0lle** [comment]
Welcome back ;)
In my opinion its a bad idea to manage secrets with raycast, from security pov.

**Comment by Falci** [comment]
Yes, I see the problem. Just copy individual items would be great.
