### ISSUE TITLE
[Todoist] ... Just trying to connect Todois to Raycast so I can create a task from within raycast.   Won't connect

### ISSUE THREAD

**Issue by egoldy** [raycast/extensions#14584]
### Extension

https://www.raycast.com/doist/todoist

### Raycast Version

latest

### macOS Version

15.1

#### Error:
```
FetchError: request to https://todoist.oauth-proxy.raycast.com/token failed, reason: unable to verify the first certificate

    at withAccessToken(WC)
    at Ht
_r:index.js:8:2593
    at ray-navigation-stack
```

### Steps To Reproduce

I'm just tryint to add a new task and it's telling me to connect thee two of them which I'm doing -- then getting that error

### Current Behaviour

FetchError: request to https://todoist.oauth-proxy.raycast.com/token failed, reason: unable to verify the first certificate

    at withAccessToken(WC)
    at Ht
_r:index.js:8:2593
    at ray-navigation-stack

### Expected Behaviour

Trying to just to create a task

**Comment by thomaslombart** [comment]
Let's sync on issue #14585.
