### ISSUE TITLE
config quicklink from extension

### ISSUE THREAD

**Issue by chyroc** [raycast/extensions#1461]
**Describe the feature and the current behavior/state.**

1. update package.json

add command mode: `quicklink` to package.json

```json
  "commands": [
    {
      "name": "google-search",
      "title": "Search Google",
      "description": "Search Google",
      "mode": "quicklink"
    },
```

2. create src/google-search.tsx

```ts
export default async (query: string): Promise<string> =>{
	return `https://google.com/search?q=${query}`
}
```

3. render quicklink

![image](https://user-images.githubusercontent.com/15604894/164682589-46e5792a-49f8-4976-8654-bf433572138d.png)

**Will this change the current API? How?**

no

**Who will benefit from this feature?**

developers and users

**Any Other info.**

**Comment by pomdtr** [comment]
I think this is essentially the same as adding args to no-view commands:

```json
"commands": [
    {
      "name": "google-search",
      "title": "Search Google",
      "description": "Search Google",
      "mode": "no-view",
      "args": [
          {"type": "string", "placeholder": "query"}
       ]
 }
```

**Comment by peduarte** [comment]
Hey, what @pomdtr is correct. This can be achieved via a `no-view` Command, then set as Fallback Command. Thanks!
