### ISSUE TITLE
[OpenAI Translator] Missing languages

### ISSUE THREAD

**Issue by huyz** [raycast/extensions#14618]
### Extension

https://www.raycast.com/douo/openai-translator

### Raycast Version

1.83.1

### macOS Version

14.7

### Description

The list of languages is cut off after:
```
["kk", "Қазақ"],
```

That excludes many languages, including VIetnamese.

### Steps To Reproduce

Try to translate to Vietanmese.

### Current Behaviour

Vietnamese is not listed (along with many languages whose ISO code starts at or after the letter `k`)

### Expected Behaviour

All languages are listed, including Vietnamese

**Comment by douo** [comment]
This issue was already addressed in PR #14696
