### ISSUE TITLE
[OpenAI Translator] OpenAI models are outdated

### ISSUE THREAD

**Issue by huyz** [raycast/extensions#14619]
### Extension

https://www.raycast.com/douo/openai-translator

### Raycast Version

1.83.1

### macOS Version

14.7

### Description

The list of OpenAI models is in bad need of an update.

### Steps To Reproduce

Try to use OpenAI to translate.

### Current Behaviour

You will get an error message about "deprecated" models

### Expected Behaviour

![screenshot 2024-09-23T040639Z@2x](https://github.com/user-attachments/assets/c721575a-f867-459c-9b65-73153969858f)

**Comment by douo** [comment]
Thank you for your feedback. I have now changed the model list to load dynamically.
