### ISSUE TITLE
[Toggl Track] Menu bar item shows weird day total hours sometimes -479744:-27:-5

### ISSUE THREAD

**Issue by RaedGhazal** [raycast/extensions#14622]
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Raycast Version

1.83.1

### macOS Version

15.0

### Description

Sometimes the menu bar shows weird total day hours 
this is the chrome extension values:
<img width="457" alt="Screenshot 2024-09-23 at 1 27 45 PM" src="https://github.com/user-attachments/assets/9b995781-9096-4776-a734-6f2a4a95c787">

and this is the raycast menu bar
![Screenshot 2024-09-23 at 1 28 14 PM](https://github.com/user-attachments/assets/8c545863-5a01-4eb6-8492-e0351111117f)

### Steps To Reproduce

just open multiple time entries, doesn't always happen but a lot of times it does

### Current Behaviour

shows a weird total duration number

### Expected Behaviour

should show the sum of all the entries of the day

**Comment by lukebars** [comment]
@RaedGhazal 

Could you provide the following information?

Open up Raycast and enter "toggl"
<img width="886" alt="image" src="https://github.com/user-attachments/assets/85a97699-0eaf-4c84-9bc8-bc45c8a45c60">
 
 
Select Start/Stop time entry

At the bottom, there is Total time:
<img width="192" alt="image" src="https://github.com/user-attachments/assets/85c17f73-3e4f-4b72-996b-b95a76b4e09f">

Could you double check if it also shows incorrect values, as does the menu bar?

**Comment by RaedGhazal** [comment]
@lukebars yes

**Comment by lukebars** [comment]
Okay, so this seems like a global issue with the total time, not only the menu bar.

**Comment by RaedGhazal** [comment]
yeah sorry, a global issue in the raycast extension, just don't use it other than the menu bar so didn't really think of checking there

**Comment by lukebars** [comment]
@bkeys818 seems like a really busy week for me, so it would be great if someone would pick this up. Also - I haven't noticed this behavior even though I am using the extension every day.

**Comment by RaedGhazal** [comment]
oh I might now know how to reproduce, if you edit any time entry from the website/chrome extension, this happens instantly
