### ISSUE TITLE
[Google Chrome] ...

### ISSUE THREAD

**Issue by allanchiu** [raycast/extensions#14640]
### Extension

https://www.raycast.com/Codely/google-chrome

### Raycast Version

1.82.5

### macOS Version

15.0

### Description

can't use open tab and ask me to install the chrome. But i already installed it on my pc.

### Steps To Reproduce

![CleanShot 2024-09-24 at 16 21 05@2x](https://github.com/user-attachments/assets/5073617c-cc81-498e-bc70-d2c485c326a2)

**Comment by jaredmeakin** [comment]
Getting the same thing despite Chrome being installed. Anyway to configure this?
