### ISSUE TITLE
[Window Management] Not working with Xcode Simulator

### ISSUE THREAD

**Issue by philiplindberg** [raycast/extensions#14658]
### Description

When running any of the window management commands in an instance of Xcode Simulator, I'm getting a "Cannot move window" error:

![CleanShot 2024-09-25 at 09 17 20@2x](https://github.com/user-attachments/assets/f412fd5f-a46b-4e6a-bbbf-62c9db2629ce)

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
