### ISSUE TITLE
[TablePlus] Error when searching databases

### ISSUE THREAD

**Issue by chrcit** [raycast/extensions#14662]
### Extension

https://www.raycast.com/pernielsentikaer/tableplus

### Raycast Version

1.83.1

### macOS Version

14.6.1

#### Error:
```
Error: ENOENT: no such file or directory, open '/Applications/Setapp/TablePlus.app/Contents/Info.plist'

Object.readFileSync:node:fs:448:20
vd:database_list.js:37:5610
database_list.js:37:8739
database_list.js:37:8745
```

### Steps To Reproduce

1. I installed the extension
2. Clicked on the "Search Databases" command

**Comment by pernielsentikaer** [comment]
That's weird, do you know where TablePlus is installed and do you have it from SetApp?

**Comment by chrcit** [comment]
@pernielsentikaer I have it from Setapp and it's installed in my user's Applications folder

**Comment by pernielsentikaer** [comment]
Can you try to give me the path? Find it like this

![Raycast 2024-10-03 at 10 21 47](https://github.com/user-attachments/assets/7e9b71d3-c548-4168-9c84-a43f7abeed8b)

**Comment by chrcit** [comment]
@pernielsentikaer `/System/Volumes/Data/Users/ccito/Applications/Setapp/TablePlus.app`

**Comment by pernielsentikaer** [comment]
That's not the default location, weird 🫠

Can you try to add that path to preferences (Tabpleplus app path)

![Raycast03102024-4fPR3jnb png@2x](https://github.com/user-attachments/assets/b1acb28f-effc-4b08-92f9-6e2655a7a21c)
