### ISSUE TITLE
[Toggl Track] Create new task when creating a new entry

### ISSUE THREAD

**Issue by alex35mil** [raycast/extensions#14688]
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Description

It would be great to be able to create new tasks when creating a new entry. Otherwise, you have to go to the web ui to do that.

I think there is an API endpoint for it: https://engineering.toggl.com/docs/api/tasks/index.html#post-workspaceprojecttasks

**Comment by bkeys818** [comment]
I'd also like to do the same thing with tags. I'll try to get started on it this weekend.
