### ISSUE TITLE
[Snippets] Import Option

### ISSUE THREAD

**Issue by zaksuhar** [raycast/extensions#1469]
**Please add the option to import Snippets.**

It would be great to have the ability to easily import snippets from Google Sheets, Alfred (.alfredsnippets), or other file types (.csv, .xlsx). This is the only thing limiting me from switching entirely to Raycast at the moment :) 

I recently transferred from TextExpander to Alfred and now would like to migrate to Raycast. I've since created a Google Doc to manage all of my Snippets and use as a backup. If I want to delete or add a new snippet, I need to update it in 2 places. In a perfect world, Raycast could just pull from my Google Sheet.

Everyone will benefit from this feature!

**Comment by zaksuhar** [comment]
This would also save hours of the onboarding experience, for those Snippets superuser folks :)

**Comment by thomaspaulmann** [comment]
We released a feature to import snippets into Raycast via a JSON format. You can read more about docs [here](https://manual.raycast.com/snippets/how-to-import-snippets). You probably want to write a simple script to convert your CSV file to JSON that we can read. Let me know if that helps and we can close the issue.

**Comment by youtextme** [comment]
+1 — Snippet import (Alfred / CSV / Sheets) is a real migration blocker.

Until it lands: export Alfred snippets and recreate the top ~20 in Raycast Snippets (free). Dual-run Alfred for the long tail for a week so the switch does not stall on bulk import.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro. Snippets themselves are free-tier.
