### ISSUE TITLE
[Weather] ... Show weather in Fahrenheit

### ISSUE THREAD

**Issue by gdsingh** [raycast/extensions#14728]
### Extension

https://www.raycast.com/tonka3000/weather

### Description

Allow for showing weather in Fahrenheit in addition to Celsius as it does today.

### Who will benefit from this feature?

All users based in countries that use Fahrenheit

**Comment by ridemountainpig** [comment]
@gdsingh, you can change the unit system in the extension configuration to display the temperature in Celsius or Fahrenheit.

![CleanShot 2024-09-30 at 19 04 46@2x](https://github.com/user-attachments/assets/73f170e7-4993-489b-99cc-507f0e8ac539)

**Comment by gdsingh** [comment]
Thank you, I was not seeing this and needed to restart!
