### ISSUE TITLE
[iCloud+ Global Price Comparison] Let the user compare local prices in other currencies than CNY

### ISSUE THREAD

**Issue by wyan** [raycast/extensions#14731]
### Extension

https://www.raycast.com/elonwoo/icloud-global-pricing-comparison

### Description

The extension allows the user to compare prices of iCloud+ plans in different geographical regions, listing the price in the local currency and CNY. It would be desirable to be able to choose the comparison currency so that the user can see their local equivalent.

### Who will benefit from this feature?

All users outside of mainland China

**Comment by elonwoo** [comment]
@raycastbot assign me

**Comment by elonwoo** [comment]
@wyan thank you very much for your suggestion. I am currently on the National Day holiday in China. After the holiday, my partner and I will proceed with your new request.

**Comment by wyan** [comment]
Thank you so much for considering this issue :)
