### ISSUE TITLE
[Apple Reminders] Add tags to apple reminders from raycast, preferably in the quick add command

### ISSUE THREAD

**Issue by VatsalSy** [raycast/extensions#14760]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Objective:
Enable users to add tags to Apple Reminders directly from the Raycast Quick Add command. This feature will enhance the organization and categorization of reminders by incorporating tags during the creation process.

Current Behavior/State:
As of now, the Raycast Quick Add command allows users to create reminders in the Apple Reminders app. However, it does not support the addition of tags. Users must manually add tags to reminders after they have been created--by going to the apple reminders app, which can be time-consuming and disrupts workflow efficiency. It goes against the raycast motto of being in the flow!

Proposed Feature:
	1.	Tag Input Field: Introduce an optional input field in the Quick Add command interface where users can specify tags. Or, use AI to figure out what tag to use.. i often add: #followup with ABC... and hope that this goes to the followup list (all my reminders with this tag go to that list)
	2.	Tag Syntax: Allow users to input multiple tags by separating them with commas or spaces.
	3.	Integration with Apple Reminders: Ensure that the specified tags are correctly applied to the reminder in the 

Apple Reminders app upon creation.
User Workflow:
	1.	Open Raycast: Initiate the Quick Add command for Apple Reminders.
	2.	Enter Reminder Details: Type the reminder text as usual.
	3.	Add Tags: In the new tag input field, specify the desired tags (e.g., "work, urgent" or "personal finance").
	4.	Create Reminder: Submit the reminder, which will now include the specified tags.

By integrating this feature, Raycast will significantly improve its utility for users who rely on Apple Reminders for task management and categorization.

### Who will benefit from this feature?

Anyone using tags to categorize things in apple reminders... 
	•	Efficiency: Streamlines the process of tagging reminders, saving time and reducing the need for manual updates.
	•	Organization: Enhances the ability to categorize and filter reminders based on tags, improving task management.
	•	Consistency: Ensures that reminders are consistently tagged according to user-defined categories.

### Anything else?

The only bottleneck I can see is if Apple blocks manipulation of the tags field in their reminders.. that would be a pity...

**Comment by thomaslombart** [comment]
Thanks a lot for the feature request. Unfortunately, there's no support for reminder tags in Apple's APIs, so I'll close this issue as not planned 😕
