### ISSUE TITLE
[Notion] Search Notion is not refreshing results with newer pages

### ISSUE THREAD

**Issue by talkshowhost** [raycast/extensions#14767]
### Extension

https://www.raycast.com/notion/notion

### Raycast Version

1.83.2

### Description

When searching for a page in Notion, only created pages at the time of extension install are showing as results. 
Newer pages added after installing the extension do not show up in the results.

### Steps To Reproduce

1. Install Notion extension
2. Connect to an existing account
3. Use Search Notion command to search for a page, should show up in the results
4. Add a new page on Notion account
5. Use Search Notion command to search for new page. No pages found is shown

### Expected Behaviour

The page should show up on the results

**Comment by thomaslombart** [comment]
New root pages need to be granted access on Notion (see [extension's README](https://www.raycast.com/notion/notion)), there's unfortunately nothing we can do about that.

**Comment by talkshowhost** [comment]
Oh ok, I definitely missed that, it is unfortunate but at least there is a quick resolution for it.

Many thanks!
