### ISSUE TITLE
[WireGuard] Also start WireGuard tunnel manager when activating a tunnel

### ISSUE THREAD

**Issue by moehringn** [raycast/extensions#14763]
### Extension

https://www.raycast.com/sbugzhu/wireguard

### Description

**Current state**
When a tunnel is activated via command, no visualisation is available to indicate any active tunnel to the user.

**Feature**
It would be nice if the WireGuard tunnel manager would also start when activating a tunnel so the icon in the task bar at the top right appears as well. This way one can see that at least one tunnel is active.

**Comment by sbugzu** [comment]
Hi moehringn, thanks for the suggestion, I'm not considering supporting the feature at currently.

Personal considerations are:
1. the extension ensures that enabling/disabling services/viewing status can be done in raycast.
2. it's a bit weird when extensions call external apps and it's not necessary.

If you just want to check the status, my suggestion is to enable the VPN menu bar extra. Go to System Settings > Control Center > VPN and select "Show In Menu Bar".
