### ISSUE TITLE
[Slack] Cannot login

### ISSUE THREAD

**Issue by Pra3t0r5** [raycast/extensions#14787]
### Extension

https://www.raycast.com/mommertf/slack

### Raycast Version

1.83.2

#### Error:
```
FetchError: request to https://slack.oauth.raycast.com/token failed, reason: unable to get local issuer certificate

    at withAccessToken(H5)
_r:index.js:8:2593
    at ray-navigation-stack
Eo:index.js:8:2094
```

### Steps To Reproduce

1. Open raycast
2. Try to use slack related features
3. Login to slack
4. Confirm slack permission disclaimer
5. Return to raycast
6. Breaks

**Comment by thomaslombart** [comment]
Are you using some kind of VPN/firewall/proxy?

**Comment by 0xdhrv** [comment]
I am facing the same, with or without VPN

**Comment by thomaslombart** [comment]
Makes me think of this issue: https://github.com/raycast/extensions/issues/13301. Are you sure there's nothing else tampering with your network?

**Comment by 0xdhrv** [comment]
Yeah, nothing. I am getting this in the console error.

![IMG_5872](https://github.com/user-attachments/assets/2b49d10d-afdb-445c-8db6-6e0a84ddb385)

**Comment by 0xdhrv** [comment]
@thomaslombart 

The URL parameters show the `state` field is empty. If this information may help with debugging.

**Comment by thomaslombart** [comment]
That's weird. Does it also happen for the URL if you copy it from the OAuth screen?
![CleanShot 2024-10-18 at 10 44 52@2x](https://github.com/user-attachments/assets/2ea41d82-b822-499d-9427-53e09f1ca93f)
