### ISSUE TITLE
[GitHub Repository Search] ...

### ISSUE THREAD

**Issue by erauner12** [raycast/extensions#1478]
# Extension – [GitHub Repository Search](https://github.com/raycast/extensions/tree/34818c2e557126f85b29813edbd9b00e0cbe4ea5/extensions/github-repository-search/)
Author: @thomaspaulmann

## Description

Issue is that clone in vscode is not working

## Steps To Reproduce

1. Attempt to clone in vscode
2. it fails
3. 
<img width="423" alt="image" src="https://user-images.githubusercontent.com/59383957/164915432-a3313b1a-2079-45cf-b5b4-fc3a42979e8a.png">

## The current behavior

The repo fails to clone because the git command is pointing to a url that does not contain the repo name

## The expected behavior

the repo is cloned to the location specified

### Raycast version
Version: 1.33.2

**Comment by immint023** [comment]
Hi @erauner12 , I opened PR for this bug.
