### ISSUE TITLE
[Open Link in Specific Browser] Automatically recognize links in Raycast and suggest to open in specific browser

### ISSUE THREAD

**Issue by vbshubham** [raycast/extensions#14793]
### Extension

https://www.raycast.com/koinzhang/open-link-in-specific-browser

### Description

When I post a link in raycast, it should suggest open in a specific browser.
<img width="798" alt="image" src="https://github.com/user-attachments/assets/cc40502f-77e3-499d-9557-c42228a8cab8">

### Who will benefit from this feature?

It will make the use of the extension more natural.

**Comment by koinzhang** [comment]
Hi @vbshubham First of all I'm glad you're using the Open Link in Specific Browser extension.

The feature request you made is not currently available as an extension, it should be a built-in Raycast capability and you should make a feature request to Raycast officially.

Or @pernielsentikaer and @sxn can take a look at this issue.
