### ISSUE TITLE
[Spotify Player]...

### ISSUE THREAD

**Issue by maxwithbug** [raycast/extensions#14797]
### Extension

https://raycast.com/mattisssa/spotify-player

### Raycast Version

1.80.0

### macOS Version

seruoia 15.0

#### Error:
```
Error: Player command failed: Premium required
    at O4 (/Users/suman/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/yourLibrary.js:58:1232)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async o (/Users/suman/.config/raycast/extensions/320f40ef-a633-415a-ab0e-1e99515478f7/yourLibrary.js:60:469)
```

### Steps To Reproduce

1. Searched for my Spotify playlist 
2. Pressed enter to play a song 
3. Not playing, throws an error 

### Current Behaviour

not playing songs (I searched Spotify)

### Expected Behaviour

should play

**Comment by thomaslombart** [comment]
Some of Spotify's APIs require a premium account to use the extension. Unfortunately, there's nothing we can do about that, so I'll close this issue 😕

**Comment by jonasengelmann** [comment]
@thomaslombart I think it would be possible to fallback to applescript for play/toggle/pause. Is this a feature you would consider merging if I give it a try? I know this would make it platform-specific. Interestingly though, I get one premium-scoped api call for free every few minutes or so, which is probably also a reason this issue pops up all the time.
