### ISSUE TITLE
[Cal.com - Share Meeting Links] Add option to share personal account link

### ISSUE THREAD

**Issue by Apope1999** [raycast/extensions#14809]
### Extension

https://www.raycast.com/cal/cal-com-share-meeting-links

### Description

Instead of only having the options to share individual meeting links, it would be nice to have the option to copy the personal account link; ie. https://cal.com/[username]

### Who will benefit from this feature?

People who want to share all of their booking options instead of a specific event type. 

### Anything else?

Example concept of implementation from a similar booking app; Calendly

<img width="842" alt="Στιγμιότυπο οθόνης 2024-10-07, 12 20 07 πμ" src="https://github.com/user-attachments/assets/25d7286a-efa3-49fe-8542-eed19527edc3">

**Comment by xmok** [comment]
You can do this through the "Copy My Link" Action as shown in following screenshot:

<img width="1000" alt="cal-com-share-meeting-links 2024-10-14 at 23 22 25" src="https://github.com/user-attachments/assets/1dcc67d8-cde7-4f0a-aec3-50ef5c64d76d">

**Comment by jfkisafk** [comment]
Closing since this feature is already present

**Comment by jfkisafk** [comment]
@raycastbot close this issue
