### ISSUE TITLE
[Extension Name] ...Zed | Problem with opening a recent project, causes duplication of project in zed's recent projects window

### ISSUE THREAD

**Issue by TympanicLemon** [raycast/extensions#14803]
### Extension

https://www.raycast.com/ewgenius/zed-recent-projects

### Raycast Version

1.83.2

### macOS Version

15.0.1

### Description

When I use the `Search Recent Projects` command to open a recent project in zed, it works great and fine.
However, if I then use `cmd+option+o` to open the recent projects window in zed, it duplicates the project I just opened.

Opening the project normally, only one instance of the project shows up in zed's recent projects pop up, no matter how many times I open the project using the CLI tool or the open folder button in zed

### Steps To Reproduce

1. Open a folder to edit code using either zed, or the CLI tool
2. Close the editor, and then reopen zed again.
3. Open the recent projects window to check that the opened folder now shows up there
4. OPTIONAL: Feel free to check that the cli tool and zed's open folder button doesnt cause this duplication bug, i did but feel free
5. Close zed
6. Open said project using the zed raycast extension, through search recent projects command
7. After zed opens, close zed
8. Open zed
9. Open recent projects window popup, and boom the project is now duplicated and you see it twice and it will continue to duplicate, adding another and another entry if you continue the steps above

**Comment by ewgenius** [comment]
@raycastbot assign me

**Comment by ewgenius** [comment]
@TympanicLemon thanks for detailed report, I will check that

**Comment by TympanicLemon** [comment]
@ewgenius thanks for taking the time to even look at it, super appreciate it :)
