### ISSUE TITLE
[Bluesky] extension seems to crash when opening the timeline

### ISSUE THREAD

**Issue by xmok** [raycast/extensions#14814]
### Extension

https://www.raycast.com/dharamkapila/bluesky

### Raycast Version

1.83.2

### macOS Version

13.0.1

### Description

              @xmok extension seems to be crashing when I open the timeline now:

![CleanShot 2024-10-01 at 21 47 17@2x](https://github.com/user-attachments/assets/263bffa7-beeb-4e1b-bfe1-b37742e36e08)

![CleanShot 2024-10-01 at 21 46 53@2x](https://github.com/user-attachments/assets/017970a7-ce67-44c6-a1d8-8a9aac628992)

_Originally posted by @dkapila in https://github.com/raycast/extensions/issues/14719#issuecomment-2386902750_
            

### Steps To Reproduce

Open `Timeline`

### Current Behaviour

Crashes

### Expected Behaviour

No crash

**Comment by xmok** [comment]
@dkapila I created this new issue.
I am still unable to reproduce as all posts I come across seem to have proper markdown. I have added a null check and made some other changes (e.g. I added native pagination to the `Timeline` command). Is it possible for you to find a post that is causing this error so we can confirm the null check fixes the problem?

Here is where I am https://github.com/xmok/raycast-extensions/tree/ext/bluesky/extensions/bluesky though I can also create a proper PR once we have more info.

**Comment by xilopaint** [comment]
I got this when running the `Timeline` command:

```
Error: o.body?.cancel is not a function

t.from:types.ts:172:11

---
169:       ? Object.fromEntries(causeResponse.headers.entries())
170:       : undefined
171: 
172:     return new XRPCError(status, undefined, message, headers, { cause })
173:   }
174: }
175: 
---

t.call:timeline.js:16:338619
async Vx:timeline.js:98:1155
```

**Comment by xmok** [comment]
Hey @xilopaint 

I also get that error when the extension runs after a while but I'm pretty sure it's because of the latest package version of the protocol itself. It goes away when you run the command again.

But thank you for confirming you get the error as well I'll see if we can handle it more gracefully until we have an upstream fix. 👍

**Comment by dkapila** [comment]
@xmok , if I print the `post` object, I have quite a few posts in my timeline which don't have a `post.record`.  

![CleanShot 2024-10-07 at 16 30 00@2x](https://github.com/user-attachments/assets/6815e5f9-6757-44de-b282-3b78b17293d1)

And for these, my timeline fails to load with these logs: 
```
TypeError: Cannot read properties of undefined (reading 'text')
    at getPostMarkdownView (/Users/dk/.config/raycast/extensions/bluesky/home.js:51967:59)
    at /Users/dk/.config/raycast/extensions/bluesky/home.js:52071:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 11)
    at async parseFeed (/Users/dk/.config/raycast/extensions/bluesky/home.js:52035:17)
    at async /Users/dk/.config/raycast/extensions/bluesky/home.js:52964:29
```

Will try to refresh again later, and see if it persists.

**Comment by xmok** [comment]
Sounds good. I've followed loads of random accounts in an attempt to reproduce but somehow I still don't get the above error! In case it has something to do with the Bluesky instance, I'm on the default i.e. bsky.social.

Will standby until you can figure out which posts are causing the issue.

**Comment by xmok** [comment]
That's great news!
I'm opening the PR I worked on in the meantime:
- adds Native Raycast Pagination to the `Timeline` command
- adds a mini fix for post markdown missing
- updates deps 🚀
