### ISSUE TITLE
[Apple Reminders] Section Request

### ISSUE THREAD

**Issue by Juan-gonloz** [raycast/extensions#14835]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

It would be awesome to be able to choose the section and view by section the reminders:
<img width="862" alt="Screenshot 2024-10-08 at 12 34 34" src="https://github.com/user-attachments/assets/21a68b51-bc37-4ba6-aae5-872586934b3a">

Also, if the task appears in the menu bar would be great.
<img width="898" alt="Screenshot 2024-10-08 at 12 38 20" src="https://github.com/user-attachments/assets/62734f14-59f2-48e3-bce1-0939b79e9ebb">

### Who will benefit from this feature?

Everyone using the reminders extension, as they would be able to pick not only the list, but the section inside that list

### Anything else?

As you can see this view:
<img width="862" alt="Screenshot 2024-10-08 at 12 41 34" src="https://github.com/user-attachments/assets/324b2f19-c5f1-4d9b-a67b-c9492fbe2d6e">

Is different than this one:
<img width="1689" alt="Screenshot 2024-10-08 at 12 42 30" src="https://github.com/user-attachments/assets/016dd669-1e03-4cdc-aad1-1b081ad75713">

By the way, thanks for creating Raycast, love it

**Comment by thomaslombart** [comment]
Unfortunately, there's no support for sections in Apple's Reminders API, so I'll close this issue as not planned 😕
