### ISSUE TITLE
[Ollama AI] Add the full models list to the "Manade Models" command

### ISSUE THREAD

**Issue by Decryptu** [raycast/extensions#14833]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

Hello, could you please add the possibility to see the models list sorted by most popular like [here](https://ollama.com/library?sort=popular) ?

### Who will benefit from this feature?

Users will no longer need to go to the ollama website to verify the models tags, and see what are the latest models.

**Comment by MassimilianoPasquini97** [comment]
@raycastbot assign me
