### ISSUE TITLE
[Tyme 3 Time Tracker] ... Something went wrong - loading tasks

### ISSUE THREAD

**Issue by hazardawareness** [raycast/extensions#14842]
### Extension

https://www.raycast.com/melkstam/tyme-3-time-tracker

### Raycast Version

1.83.2

### macOS Version

15.0.1

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'name')

t0:start-task-tracking.tsx:13:70

---
10: 
11: function StartTrackerForTask() {
12:   // Get all tasks
13:   const { data: tasks, isLoading: tasksIsLoading } = useCachedPromise(getTasks, [], {
14:     keepPreviousData: true,
15:   })

### Steps To Reproduce

Open Raycast - Select Start Task - error

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by melkstam** [comment]
Hi and thanks for the report @hazardawareness!

I've sadly seen this before but I have a hard time reproducing this. This has also been reported in https://github.com/raycast/extensions/issues/10249.

Do you have any more any context about when this happened?

**Comment by hazardawareness** [comment]
@melkstam thanks. It happened directly after a tyme update so I assumed it was something to do with a change there but as you said it was isolated I tried to uninstall and then reinstall the extension and it fixed the issue.

Love the extension, use it every day. Next time this happens I'll see if I can debug exactly what might be causing it but uninstalling then reinstalling seemed to do the trick. Tried restarting, safe mode, quitting apps, etc before all that and nothing else helped.

**Comment by melkstam** [comment]
> @melkstam thanks. It happened directly after a tyme update so I assumed it was something to do with a change there but as you said it was isolated I tried to uninstall and then reinstall the extension and it fixed the issue.
> 
> Love the extension, use it every day. Next time this happens I'll see if I can debug exactly what might be causing it but uninstalling then reinstalling seemed to do the trick. Tried restarting, safe mode, quitting apps, etc before all that and nothing else helped.

Thanks! I will continue to try reproducing the issue. I'm glad you like the extension!
