### ISSUE TITLE
[Open Folders] crashes when selecting a folder using the numerical shortcuts

### ISSUE THREAD

**Issue by riadhrebei** [raycast/extensions#14844]
### Extension

https://www.raycast.com/timothy_boye/open-folders

### Raycast Version

1.83.2

### macOS Version

15.0

#### Error:
```
Error: missing expected parameter key: path


```

### Steps To Reproduce

Open speed dial 
Write 0 for first folder in speed dial

### Current Behaviour

Error

### Expected Behaviour

Opening the folder

**Comment by gfazioli** [comment]
@riadhrebei fixed - https://github.com/raycast/extensions/pull/14849

**Comment by gfazioli** [comment]
I think we can close this issue - it's fixed @riadhrebei
