### ISSUE TITLE
Appending notes to the active web page's Reflect note page

### ISSUE THREAD

**Issue by jaseemts** [raycast/extensions#14843]
### Extension

https://www.raycast.com/ryon/reflect

### Description

Whenever I watch a video or read an article, I can activate this command to add notes. If it's my first time doing this, it will create a Reflect page and add my notes. If I do it again, it will simply append the notes to that specific page.

Currently, I can only append notes to my daily notes. Adding this would make consuming and learning content much more seamless.

### Who will benefit from this feature?

Anyone who takes notes while watching a video, reading an article, or browsing a website will benefit. For quick, random ideas, the current Append Notes feature in Daily Notes is already helpful. However, for longer, detailed notes on a specific topic—especially when watching a video or reading a lengthy blog—I prefer to keep my notes on the page associated with that content. The Reflect Chrome extension allows us to bookmark and create a dedicated page for this purpose. However, to take notes, I still need to access the Reflect app itself.

### Anything else?

The UX could resemble the current "Append To Daily Note" command. In the background, whenever I add a note, it will check whether the respective page has been created.

Another idea is to include a drop-down with a search option for selecting the page to which notes should be added. But the experience would be seamless if page creation and verification were automated in the background.

**Comment by joshknowles** [comment]
Hey @jaseemts 👋🏽 

Unfortunately the [Reflect API](https://openpm.ai/packages/reflect#/graphs/%7BgraphId%7D/notes) has the following limitations making this request challenging
1. You can create a new note, but there is no way to append to the note in the same way that you can append to a daily note
2. There is no way to get a list of note titles (this is due to the end-to-end encryption)

Given the limitations of the API, what do you think the UX should be?

**Comment by jaseemts** [comment]
Hey @joshknowles, thank you for the quick response. I really appreciate it.

The limitation of the Reflect API is a shame. Hopefully, they will extend its capabilities soon.

The UX is quite straightforward.

-  I am on a webpage, a blog, or a YouTube video. While engaging with the content, I get an insight to note down.
-  I hit Command-Space, select "Add a quick Reflect note," and can add notes just like I do in the current "Append To Daily Note" command. In the background, it checks if a Reflect page for this note already exists. If not, it creates one and adds the note. If the page already exists, further notes will be appended to the existing ones.
-  I hit Command-Enter. The note is added, and I resume reading the blog or watching the YouTube video.

I believe this will create a seamless experience for consuming or learning from any web content, whether it's a video, a blog, or a tweet thread.

**Comment by joshknowles** [comment]
> The UX is quite straightforward. 
Sorry, to be more clear, I was asking if there is a difference user experience you thought made sense given what you are asking for can't currently be built.

I'd encourage you to open a feature request with the Reflect team to enchance their APIs to allow appending to links and notes.

**Comment by jaseemts** [comment]
@joshknowles Oops, my mistake. I can't think of any other UX that fits my workflow given the current limitations.

I will definitely submit a feature request to the Reflect team to improve their API. Thank you for your time.
