### ISSUE TITLE
[Summarize YouTube Videos with AI] ...

### ISSUE THREAD

**Issue by KenInLV** [raycast/extensions#14855]
### Extension

https://www.raycast.com/iKasch/summarize-youtube-video-with-ai

### Description

Please add Claude as an option in addition to ChatGPT and Raycast AI. Two reasons:

- Claude gives noticeably better summaries. OpenAI-based GPT goes through chronologically and shortens. Claude contemplates the transcript as a whole and intuits the key points. 
- Many of us are starting to have mixed feelings about OpenAI and prefer to financially support other developers.

### Who will benefit from this feature?

Everyone who prefers Claude over ChatGPT, and/or Anthropic over OpenAI.

### Anything else?

Love the tool, thanks for creating it and making it available.

**Comment by iKasch** [comment]
Thanks for reporting! I'll definitely check it out and make Claude available as well as some other new features.

**Comment by iKasch** [comment]
@raycastbot assign me

**Comment by iKasch** [comment]
@raycastbot reopen this issue

**Comment by iKasch** [comment]
@raycastbot keep this issue open

**Comment by iKasch** [comment]
@KenInLV Hey! Sorry for the long wait but Claude is now available. Hope you like it.
https://github.com/raycast/extensions/pull/15972

@raycastbot close this issue
