### ISSUE TITLE
[Claude] fail to access claude

### ISSUE THREAD

**Issue by mengliuveronica** [raycast/extensions#14858]
### Extension

https://www.raycast.com/florisdobber/claude

### Raycast Version

1.84.1

### macOS Version

macOS 14.6.1

### Description

I have claude api key and can confirm that it works fine when I access claude api using python locally. But the claude chat in raycast doesn't work. Why? is it because I am using a vpn? How to resolve this issue? Thanks!

### Steps To Reproduce

MacOS run ask calude

### Current Behaviour

nothing happens. 

### Expected Behaviour

respond

**Comment by florisdobber** [comment]
Hi @mengliuveronica, I just did a clean install and had no issues. Could you give me more information on what "doesn't work" means? What error message are you getting?

**Comment by mengliuveronica** [comment]
Hi, many thanks for getting back!  Below are some screenshots to help with the troubleshooting. I can confirm that my API key is input and that API key is working fine (I use other wrappers like Chatbox with it). The other screenshot shows the error message. The only thing I could think of that may cause the issue is because I am on a vpn but that is not an issue when I am directly accessing Claude API. I think it might have something with how the underlying package is treating vpn calls (or by default not being routed by the vpn). Hope this helps clarifies the situation and any help is appreciated!
***@***.******@***.***


From: Floris Dobber ***@***.***>
Date: Monday, October 14, 2024 at 16:59
To: raycast/extensions ***@***.***>
Cc: Meng Liu ***@***.***>, Mention ***@***.***>
Subject: Re: [raycast/extensions] [Claude] fail to access claude (Issue #14858)

Hi @mengliuveronica<https://github.com/mengliuveronica>, I just did a clean install and had no issues. Could you give me more information on what "doesn't work" means? What error message are you getting?

**Comment by florisdobber** [comment]
Hi @mengliuveronica, the screenshots didn't attach. I tested locally with my VPN turned on which worked fine, so without the screenshots it will be hard for me to provide any support.

**Comment by mengliuveronica** [comment]
Hi, this is the error message:

Error
Couldn't stream message: Error: 403 {"error": {"type": "forbidden", "message": "Request not allowed "}}

Any input is appreciated!

From: Floris Dobber ***@***.***>
Date: Tuesday, October 15, 2024 at 01:20
To: raycast/extensions ***@***.***>
Cc: Meng Liu ***@***.***>, Mention ***@***.***>
Subject: Re: [raycast/extensions] [Claude] fail to access claude (Issue #14858)

Hi @mengliuveronica<https://github.com/mengliuveronica>, the screenshots didn't attach. I tested locally with my VPN turned on which worked fine, so without the screenshots it will be hard for me to provide any support.

**Comment by florisdobber** [comment]
Hi @mengliuveronica, I think you were on to something with the VPN. Anthropic has a list of [supported regions](https://docs.anthropic.com/en/api/supported-regions) and I am guessing you are connecting from a region not on this list. If that is not the case, please let me know and I will investigate further.

**Comment by mengliuveronica** [comment]
Hi, yes that’s the case. I am not in a supported region which is why I am using VPN. So the VPN doesn’t work in this case?

From: Floris Dobber ***@***.***>
Date: Wednesday, October 16, 2024 at 15:36
To: raycast/extensions ***@***.***>
Cc: Meng Liu ***@***.***>, Mention ***@***.***>
Subject: Re: [raycast/extensions] [Claude] fail to access claude (Issue #14858)

Hi @mengliuveronica<https://github.com/mengliuveronica>, I think you were on to something with the VPN. Anthropic has a list of supported regions<https://docs.anthropic.com/en/api/supported-regions> and I am guessing you are connecting from a region not on this list. If that is not the case, please let me know and I will investigate further.
