### ISSUE TITLE
[File Manager] ...

### ISSUE THREAD

**Issue by theandylynch** [raycast/extensions#14854]
### Extension

https://www.raycast.com/erics118/file-manager

### Description

I'd like to be able to move files and directories to another location.

### Who will benefit from this feature?

People looking to have comprehensive file management.

**Comment by erics118** [comment]
This is going to be out of scope for this extension. It's a lot of effort for this feature. This extension is mainly just in maintenance, as the native file search in Raycast now provides traversing file directories, which was the original point of this extension.

**Comment by erics118** [comment]
@ raycastbot close as not planned

**Comment by erics118** [comment]
@raycastbot close as not planned
