### ISSUE TITLE
[Notion] Add new page to top of database

### ISSUE THREAD

**Issue by pimvanderheijden** [raycast/extensions#14861]
### Extension

https://www.raycast.com/notion/notion

### Description

Would it be possible to add the new page to the top of the database?

### Who will benefit from this feature?

anybody using databases, as I think this should have been the default

**Comment by zsidnam** [comment]
@pimvanderheijden can you clarify what you mean by adding "to the top of the database"? If you are talking about the sort order of the database view, that needs to be set directly on the view. (If your database view is sorted by Created Date DESC, new pages added to the database will appear at the top in that view).

Please let me know if I'm misunderstanding your question, though!

**Comment by pimvanderheijden** [comment]
I'm talking about the row number of the new page, in other words, the new
row in the database should have index 0. Notion creates database rows as
pages for some reason.

**Comment by pimvanderheijden** [comment]
It's unsorted I would say and that's why the newest item is on top. It looks like this for me. I created the item on top right now.

![image](https://github.com/user-attachments/assets/35046149-67ca-4696-9c5e-efdfb1ef3520)

When I perform the Notion "Create Database Page" command, the item ends up at the bottom
![image](https://github.com/user-attachments/assets/05d57acc-fb25-4c65-ac48-4213d0ef742d)

**Comment by pimvanderheijden** [comment]
To clarify, by "unsorted" I don't mean disordered but I mean the order in which it is stored under the hood, within the database.

**Comment by zsidnam** [comment]
@pimvanderheijden thank you for those screenshots; that was what I needed! I see what you are saying that Notion adds the row to the top of the table if you click the "New" button at the top of the database view and adds it to the bottom if you click the "New" button at the bottom of the view. That is really interesting that they do that, but I'm not seeing any way to control the insertion order from their API. It looks like there is a similar limitation if you create a Notion button that adds a page to a database; the new page always gets added at the bottom. Unfortunately, unless Notion updates the API to give us this ability, you will have to rely on sorting to make sure the newest row is always at the top.

**Comment by zsidnam** [comment]
I read about this a little further and it seems that Notion internally has access to an `order` property on the view itself, not on the database, which is also what enables manually dragging rows up and down the table views. You can see that this is specific to the view by adding another table view for that database  -> the rows will be laid out in order of "Created time" DESC even though they are ordered differently in your original database view.

Notion does not give access to creating/editing views in their API yet, so we won't have this ability.

**Comment by pimvanderheijden** [comment]
Thanks for diving into this. So there is no way currently to get the newly
inserted rows in top, correct? That's a pity.

I think we could say it's a UX issue with Notion itself. I noticed it also
occurs in the Notion app when you have a bad connection (or are offline).
Anyway, interesting topic. Thanks for spending some time on it with me!

**Comment by zsidnam** [comment]
@raycastbot close this issue
