### ISSUE TITLE
[Mattermost] ...Geting 401 error using lattermost search extension

### ISSUE THREAD

**Issue by rngjr3410** [raycast/extensions#14876]
### Extension

https://www.raycast.com/ernest0n/mattermost

### Raycast Version

newest version just downloaded it on 10-10-24

### macOS Version

15.1

### Description

Geting 401 error using Mattermost search extension. It does show that I logged in successfully.

### Steps To Reproduce

using the search feature, instantly responds with 401 error

### Current Behaviour

na

### Expected Behaviour

na

**Comment by xmok** [comment]
Hey @rngjr3410 I'm not the author but can you answer the following:
1. Which Authorization method are you using?
2. Are you able to see a List  like following screenshot or does the extension crash before?
![Screenshot 2024-10-13 at 12 43 55 AM](https://github.com/user-attachments/assets/5ec4666d-6b60-4e8d-ad9f-7415738addbf)
3. Do you have any DIRECT channels for the user you are logged in as?

If you can answer the above I might be able to push a fix.
