### ISSUE TITLE
[Visual Studio Code] Multiple commands not working with VSCode installed by nix-darwin

### ISSUE THREAD

**Issue by Fr4nk1inCs** [raycast/extensions#14871]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Raycast Version

1.82.5

### macOS Version

15.0.1

### Description

> I'm using [nix-darwin](https://github.com/LnL7/nix-darwin) ([nix](https://nixos.org) module for darwin) for my macOS environment management so it's a little different.
>
> Basically, VSCode is installed into `/Applications/Nix Apps/Visual Studio Code.app` with two levels of symlinking (`xxxxx` below stands for a unique hash for every package in the nix eco-system):
> - `/Applications/Nix Apps` -> `/nix/store/xxxxx-system-applications/`
> - `/Applications/Nix Apps/Visual Studio Code.app/` -> `/nix/store/xxxxx-vscode-1.93.1/Applications/Visual Studio Code.app`

Following commands on my machine failed to function:
- Open New Window: <img width="244" alt="image" src="https://github.com/user-attachments/assets/ad1a0d35-4e40-4836-9ce8-d261c7c9057b">
- Install Extension: <img width="862" alt="image" src="https://github.com/user-attachments/assets/05b3ec35-a188-4931-b83c-b409f33e7e3d">
- Commands: <img width="862" alt="image" src="https://github.com/user-attachments/assets/a5d51a11-bf27-4f5e-8ec9-7f7d392c9ba5">

I'm glad to provide extra info if needed.

### Steps To Reproduce

1. Environment: As described in description.
   - VSCode installed in `/Applications/Nix Apps/Visual Studio Code.app` which is a symlink (in a symlinked directory)
2. Extension Config: No extra modification except command `Commands` enabled.
3. Run commands mentioned in description. (Open New Window, Install Extension, Commands)

### Current Behaviour

As described in description.

### Expected Behaviour

All commands function perfectly.

**Comment by Fr4nk1inCs** [comment]
Currently the `Open New Window` command is done by executing some AppleScript:
https://github.com/raycast/extensions/blob/7a8c6d2e5f45991a456af97841e5b40c80376703/extensions/visual-studio-code-recent-projects/src/open-new-window.ts#L7-L19

The same script can't find `application "com.microsoft.VSCode"` on my machine, although `osascript` did find `application "Code"`:
```console
$ osascript -e 'id of application "Code"'
com.microsoft.VSCode
```

Another issue with this script is that if there's a language pack (Simplified Chinese for example) installed in VSCode, the menubar item is not displayed in English, making this script failed to `click` the `New Window` button.

A possible way to open a new window is to use the command line argument `-n` or `--new-window` provided by VSCode (and VSCodium/Cursor):
```console
$ code --new-window
```

But this would encounter the same problem (to find to executable `code`) which the `Install Extension` command has met. Maybe add a configuration item to let user set the executable path if  VSCode is not installed by a "standard" procedure?

**Comment by Fr4nk1inCs** [comment]
```console
$ osascript -e 'POSIX path of (path to application id "com.microsoft.VSCode")'
/nix/store/xxxxx-vscode-1.93.1/Applications/Visual Studio Code.app/
$ osascript -e 'POSIX path of (path to application "Code")'
/nix/store/xxxxx-vscode-1.93.1/Applications/Visual Studio Code.app/
```

**Comment by Fr4nk1inCs** [comment]
Anyway, I changed my main editor for remote servers to Zed and don't use VSCode anymore.

**Comment by foucist** [comment]
For anyone else that stumbles across this..  I had to restart Raycast for it to pick up the symlinks, specifically pick up symlinked apps in /Application/ (because of nix).  This might also apply to this extension issue as well.
