### ISSUE TITLE
[Spell] Details view enabled by default

### ISSUE THREAD

**Issue by cynicaljoy** [raycast/extensions#14903]
### Extension

https://www.raycast.com/Gorzog/spell

### Description

Add setting to enable Details View to be enabled by default. 

### Who will benefit from this feature?

Save some keystrokes for those that want to always have the details view available when reviewing spell results.

**Comment by Vincenzo160** [comment]
Hi, thank you for the issue, could you please be more specific on what you mean by "Details View", the extension only has a list view

**Comment by cynicaljoy** [comment]
![image](https://github.com/user-attachments/assets/aa1a8ce7-f2a3-4239-9c09-c08a336e1135)

![image](https://github.com/user-attachments/assets/dc58ad70-bc46-4b41-a576-0bce32731a97)

**Comment by Vincenzo160** [comment]
That's not my extension, i think the extension in the screenshot is [Word Search](https://www.raycast.com/rishabswift/word-search).

**Comment by Vincenzo160** [comment]
@raycastbot close this issue

**Comment by Vincenzo160** [comment]
No worries!
