### ISSUE TITLE
[Timers] Seconds are not updating on menu

### ISSUE THREAD

**Issue by sagarpatel288** [raycast/extensions#14902]
### Extension

https://www.raycast.com/ThatNerd/timers

### Raycast Version

1.84.2

### macOS Version

15.0.1

### Description

After starting a stopwatch, the seconds do not update on the menu item unless we click on it. The seconds freeze again as soon as we close the menu item details by clicking outside of it. I have added two more apps for comparison.

https://github.com/user-attachments/assets/b16531b7-f4ef-4366-a607-9652a9b82e92

### Steps To Reproduce

1. MacOS Sequoia 15.0.1 (M1 Max Pro, Apple Silicon)
2. Start a stopwatch using the timer
3. Check the timer menu item

### Current Behaviour

Seconds do not update on the menu item

### Expected Behaviour

Seconds should be updated on the menu item

**Comment by ThatNerdSquared** [comment]
Hi @sagarpatel288, thanks for using Timers!

Does it manage to update after around 10 seconds? If you deactivate the menu bar item ("Stopwatch Menu Bar" -> ⌘K menu) and reactivate it, does it manage to update after 10 seconds when a stopwatch is running?

**Comment by sagarpatel288** [comment]
Thank you for getting back to me so quickly, @ThatNerdSquared. I appreciate your help. To clarify, the updates occur every 10 seconds. Would it be possible to receive continuous updates instead? That would be helpful for a stopwatch! Thank you very much for considering this request.

**Comment by ThatNerdSquared** [comment]
Hi @sagarpatel288 — unfortunately, the 10-second refresh rate isn't something I added in, it's a limitation of Raycast itself. The [minimum refresh interval allowed by the Raycast API is 10 seconds](https://developers.raycast.com/information/lifecycle/background-refresh#manifest), so there's not much I can do to have continuous refresh, from an extension developer standpoint.

Sorry about that :( It might be worth putting a suggestion in the [Raycast Slack](https://raycastcommunity.slack.com/) if you'd like to see this limitation lifted.

**Comment by ThatNerdSquared** [comment]
@raycastbot close as not planned
