### ISSUE TITLE
[Zendesk — Search Support Center] Unauthorized

### ISSUE THREAD

**Issue by pkutaj** [raycast/extensions#14916]
### Extension

https://www.raycast.com/cpenned/zendesk

### Raycast Version

1.84.2

### Description

Calling https://snowplow.zendesk.com/api/v2/help_center/articles/search.json?query=hello from a browser gives me results. Calling it from Raycast returns unauthorized. I am an agent, logging in with Google SSO. Would it be hard to fix that? We are trying to use Knowledge Centered Support and this extension would greatly help in the workflow. Thanks!

### Steps To Reproduce

Quite simply, populating the URL with snowplow.zendesk.com
https://snowplow.zendesk.com/api/v2/help_center/articles/search.json?query=hello works for be in a browser session, but now via Raycast.

**Comment by cpenned** [comment]
Currently, the extension is for unauthenticated use. So you can only access public articles. I've got plans to open it up, but at least at this point, it would probably be through an API key. What other functionality would you like?

**Comment by pkutaj** [comment]
API key auth would be a great start. 

It is difficult for me to evaluate features as I have not used it yet.

However, getting as close to Jira extension with its Search Issues feature would be ideal - aside from fulltext search also showing where in a taxonomy a doc is + having a drop-down filter allowing a filter for a given category/section.

Thanks! Kind regards,
Pavol
