### ISSUE TITLE
[Bitwarden Vault] Generate Password command does not respect options

### ISSUE THREAD

**Issue by jose-elias-alvarez** [raycast/extensions#14910]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Raycast Version

1.84.2

### macOS Version

15.0.1

### Description

When running the Generate Password command from Bitwarden extension, the checked status of the "Numeric characters" and "Special characters" options are not respected, and the options always behave as if enabled.

Weirdly, I forked the extension and ran it locally to investigate, but my local copy doesn't have the same issue, and the options are indeed respected. (Even more weirdly, the generation step seems to take less time.)

I'm running the latest version of Bitwarden and the CLI (2024.9.0).

### Steps To Reproduce

1. Install and set up the extension
2. Run the `Generate Password` command

### Current Behaviour

Both numeric characters and special characters are always included in the generated password (the lowercase and uppercase options do seem to be respected).

### Expected Behaviour

The options are respected, and the relevant character types are included in or excluded from the generated password based on their values.

**Comment by jose-elias-alvarez** [comment]
A similar issue was raised in #13906, but it doesn't seem like the fix fully resolved it (the last comment there also indicates that at least one other person is still experiencing the same problem).

**Comment by jose-elias-alvarez** [comment]
For future reference: after further investigation I suspect this is actually an upstream issue and reported it at bitwarden/clients/issues/13657. Once that's fixed, I believe the generate command here will work as expected without any further changes.

**Comment by jomifepe** [comment]
> For future reference: after further investigation I suspect this is actually an upstream issue and reported it at [bitwarden/clients/issues/13657](https://github.com/bitwarden/clients/issues/13657). Once that's fixed, I believe the generate command here will work as expected without any further changes.

Interesting, thanks for investigating this, I'll keep an eye on the issue 🙌
