### ISSUE TITLE
[Word Search] Details view enabled by default

### ISSUE THREAD

**Issue by cynicaljoy** [raycast/extensions#14920]
### Extension

https://www.raycast.com/rishabswift/word-search

### Description

Add setting to enable Details View to be enabled by default.

![image](https://github.com/user-attachments/assets/fc56742b-2d2e-424d-82e0-b8244f820f9b)

![image](https://github.com/user-attachments/assets/9be24090-0bc5-4ce1-a2ee-d96fb74d2468)

### Who will benefit from this feature?

Save some keystrokes for those that want to always have the details view available when reviewing spell results.

**Comment by bkeys818** [comment]
@raycastbot close
