### ISSUE TITLE
[Brew] ...Download URL is outdated - please try again after successful store refresh

### ISSUE THREAD

**Issue by ar-hox** [raycast/extensions#14969]
### Extension

https://www.raycast.com/nhojb/brew

### Raycast Version

v.1.84.3

### macOS Version

Sonoma 14.7

### Description

![image](https://github.com/user-attachments/assets/3a96c3aa-7f10-4341-b07e-6a2e8a263d2a)

### Steps To Reproduce

1. Open Raycast store
2. Find brew extension 
3. Install

As an alternative same can be done from web: https://www.raycast.com/nhojb/brew

**Comment by nhojb** [comment]
@RSO any idea about this - just a temporary glitch in our store infra?

**Comment by RSO** [comment]
@ar-hox do you still see this issue? Are you running any proxies or firewalls that may block requests to our backend? Since this is the only report I've seen with this issue, I'm going to assume that the error stems from the client side and not the server.
