### ISSUE TITLE
[Hue] Support for multiple bridges

### ISSUE THREAD

**Issue by themattharris** [raycast/extensions#14973]
### Extension

https://www.raycast.com/pindab0ter/hue

### Description

Currently there seems to be no way to add additional bridges or multiple instances of the Hue extension meaning not all my devices can be controlled by the plugin.

### Who will benefit from this feature?

Any user with more than 50 devices and/or using multiple bridges

### Anything else?

https://www.philips-hue.com/en-us/products/smart-light-accessories/hue-bridge-buying-guide describes the upper limit of 50 devices (10 via bluetooth in a single room) of the Hue bridge.

**Comment by pindab0ter** [comment]
Hi @themattharris, thank you for opening this issue.

Unfortunately, because I do not have a multi bridge setup, I cannot develop for it.

**Comment by pindab0ter** [comment]
@raycastbot close as not planned
