### ISSUE TITLE
[YouTube Downloader] ... not recognizing ffmpeg is installed

### ISSUE THREAD

**Issue by RootRooster** [raycast/extensions#14986]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Raycast Version

v1.84.3

### macOS Version

15.0.1

### Description

When opening the YouTube Downloader it shows this error message (see image below). Even if I have ffmpeg and ffprobe installed (v 7.1).

![Screenshot 2024-10-20 at 00 55 59](https://github.com/user-attachments/assets/fc674eff-b66b-462e-84c3-2a75cf248568)

### Steps To Reproduce

1. Open raycast
2. Open YouTube Downloader
3. Error msg can be seen

### Current Behaviour

```sh
which ffmpeg
/opt/homebrew/bin/ffmpeg
```

```sh
ffmpeg          
ffmpeg version 7.1
```

```sh
which ffprobe
/opt/homebrew/bin/ffprobe
```

```sh
ffprobe
ffprobe version 7.1
```

**Comment by remorses** [comment]
Can you post a screenshot of your command preferences? You can go there with cmd k on the Raycast home view

there should be a setting to choose ffmpeg path

**Comment by RootRooster** [comment]
Hi!
I am terribly sorry for the inconvenience. I just noticed that I had command preferences set on another version of ffmpeg. 
Thank you so much for your help.
Best regards, 
Rooster
