### ISSUE TITLE
[Browser Bookmarks] ... can't detect bookmarks in Arc

### ISSUE THREAD

**Issue by Emir-1802** [raycast/extensions#14993]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Raycast Version

1.84.3

### macOS Version

Sonoma 14.7

### Description

I had been using this extension successfully until 3-4 days ago when the extension stopped showing suggestions for bookmarks in Arc. I've uninstalled it and reinstalled it, but I'm still getting the same output. Even if I unselect and then select Arc as a browser in the extension, nothing changes.

### Steps To Reproduce

1. I use the alias "bm" to open bookmarks in Raycast.
2. When I start typing the name of a bookmark, I receive a message saying that no bookmarks have been detected in Arc.
3. However, no results are displayed.
4. I have tried using other browsers that I have used in the past, and they worked without any issues.

![CleanShot 2024-10-20 at 15 43 01](https://github.com/user-attachments/assets/5bef3c1a-dabc-4274-8d74-f1d8cd06b42b)
![CleanShot 2024-10-20 at 15 43 18](https://github.com/user-attachments/assets/93ce01cd-abd8-4c06-abb4-ed21be047312)

### Current Behaviour

When I start typing the name of a bookmark, I receive a message saying that no bookmarks have been detected in Arc.

### Expected Behaviour

I'd get name suggestions for the bookmarks.

**Comment by thomaslombart** [comment]
This is weird, nothing changed in the browser bookmarks extension recently. 

Could you check if you have some data in these files:
- `~/Library/Application Support/Arc/StorableSidebar.json`
- `~/Library/Application Support/Arc/User Data/Local State`

Could you also share a recording to make it easier to see what's happening.

**Comment by Emir-1802** [comment]
Hi Thomas,

Update: It just started working without any intervention from my side. The data just abruptly appeared. I won't be tinkering with it to avoid breaking something. 😁

Regards,

On 21 Oct 2024, at 10:45, Thomas Lombart ***@***.***> wrote:

﻿

This is weird, nothing changed in the browser bookmarks extension recently.

Could you check if you have some data in these files:

  *   ~/Library/Application Support/Arc/StorableSidebar.json
  *   ~/Library/Application Support/Arc/User Data/Local State

Could you also share a recording to make it easier to see what's happening?
