### ISSUE TITLE
[API Feature Request] More Icons

### ISSUE THREAD

**Issue by es183923** [raycast/extensions#150]
**Describe the feature and the current behavior/state.**

Add more icons.
(the links go to an image of the existing icon that isn't in the API)
- Reset https://cln.sh/blwBTR
- Folder (along with Document)
- ArrowLeft, ArrowUp, ArrowDown (because there is ArrowRight)
- ArrowCounterclockwise (there is ArrowClockwise)
- StarSlash https://cln.sh/Tw40Uw
- StarUp https://cln.sh/zcnlXi
- StarDown https://cln.sh/DRfB7n
- Start, Pause, Stop (for start/pause/stopping commands)
- TerminalAlternative https://cln.sh/9hhqqa
- Unpin (there is a pin)
- LevelMeter0, LevelMeter1, LevelMeter2, LevelMeter3 (shading different levels)
- Minus (because there is a plus)
- SidebarRight, SidebarLeft(differentiate between left and right sidebar)
- Notch (for fun)
- Raycast (because this is Raycast)

**Will this change the current api? How?**

not really, just more enums to `Icon`

**Who will benefit with this feature?**

everyone who uses and/or creates extensions

**Any Other info.**

no

**Comment by mathieudutour** [comment]
we shipped a bunch of new icons in v1.38.0
