### ISSUE TITLE
[Apple Reminders] Enhance grouping based on the time of day

### ISSUE THREAD

**Issue by LearShachar** [raycast/extensions#15004]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

This extension is amazing i must say first of all. It makes using reminders much smoother.

I typically use the "today" view and i would really love to be able to separate my tasks based on time sections of the day (like the regular apple reminders does with morning, afternoon, night), and to also see / have visual separation of which list each task is from so i can organize it better in my head.

### Who will benefit from this feature?

Any users that use the today view often, especially with more than one task list.

**Comment by michalzuch** [comment]
@raycastbot rename this issue to "Enhance reminder grouping based on the time of day"

**Comment by michalzuch** [comment]
@raycastbot rename this issue to "[Apple Reminders] Enhance grouping based on the time of day"

**Comment by michalzuch** [comment]
To enable this feature, go to the extension's settings and toggle "Use Time of Day Grouping." We previously discussed that this option should be optional, as not all users may prefer it.

Hope you enjoy it! 🙌

<img width="1112" alt="Screenshot 2024-11-07 at 12 21 19 PM" src="https://github.com/user-attachments/assets/cc94dcbb-dc94-4a5a-a61e-2ec2b2463492">
