### ISSUE TITLE
[Markdown to Rich Text] ...Characters with umlauts (special characters) rendered incorrectly

### ISSUE THREAD

**Issue by Ololade121** [raycast/extensions#15006]
### Extension

https://www.raycast.com/ning_cao_cabeza/markdown-to-rich-text

### Raycast Version

1.84.3

### macOS Version

15.1

### Description

Special characters are rendered incorrectly.

![SCR-20241021-iqnp-5](https://github.com/user-attachments/assets/12a38752-a6cc-4854-b727-c1a522bf3fcb)

### Steps To Reproduce

1. Copy Markdown texts with special characters such as ü, ß, ä, ö.
2. Run the command
3. Command shows weird characters in place of the special characters

![SCR-20241021-iqnp-2](https://github.com/user-attachments/assets/2d6621d3-9c5f-424c-959d-44f52fa68fbd)

**Comment by vegetablesB** [comment]
Hi @Ololade121 , I couldn't reproduce.

https://github.com/user-attachments/assets/3bd4b179-12b6-4c24-a0f7-520d8fe24656
