### ISSUE TITLE
[Color Casket] Unable to install

### ISSUE THREAD

**Issue by slavarazum** [raycast/extensions#1501]
# Extension – [Color Casket](https://github.com/raycast/extensions/tree/8b2a6ecaf147a474c826077c0dd5d119e270cec7/extensions/color-casket/)
Author: @slavarazum

My first [recently published](https://github.com/raycast/extensions/pull/1266) extension unable to install from Store.

![CleanShot 2022-04-25 at 21 19 19@2x](https://user-images.githubusercontent.com/5820718/165149900-e439e346-9e71-45f1-8d86-d18111bf356d.png)

**Error Message**:

Failed to install extension.

```
Reason: Failed to decode response data
Domain: network
Time: 05:07:28.692
Service: Internal networking engine
Underlying: 
	Domain: RaycastData.StoreAPIResponse.Error 1
```

Extension details failed to load either...
![CleanShot 2022-04-25 at 21 00 42@2x](https://user-images.githubusercontent.com/5820718/165147516-c9bcbffe-4dc9-465b-ad04-c5b24e024a18.png)

Command logo is not displayed on extension page:
<img width="775" alt="CleanShot 2022-04-25 at 21 02 07@2x" src="https://user-images.githubusercontent.com/5820718/165147730-9801453d-8867-41ac-a74c-3b3dd843b247.png">

## Steps To Reproduce

1. Try to install extension from Strore
2. Open details

### Raycast version
Version: 1.33.2

**Comment by fe9lix** [comment]
Fixed!
