### ISSUE TITLE
[Quick Event]  More calendar hotkeys

### ISSUE THREAD

**Issue by vmoore12** [raycast/extensions#15024]
### Extension

https://www.raycast.com/mblode/quick-event

### Description

At the moment, you can only select from two calendars to add events. I have more than two calendars I would like to add events to, but there is no way to choose them.  I have only the default 'Enter' and 'CMD + Enter' hotkeys as options.  Nothing for the rest of the calenders and when I try to click on the rest of the calendars to add an event, I get a "Failed. Something went wrong." error message in red.

### Who will benefit from this feature?

People who have more than one calendar to add events to will benefite.

### Anything else?

![create_quick_event](https://github.com/user-attachments/assets/6b528d20-fdc0-42bf-ae8d-260329f3eb9c)

**Comment by whitespacecode** [comment]
@vmoore12 a pull request is made https://github.com/raycast/extensions/pull/15029
