### ISSUE TITLE
[YouTube Downloader] Is it possible to select higher kbps when downloading MP3 format?

### ISSUE THREAD

**Issue by sisyphusla** [raycast/extensions#15020]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

The download quality in mp4 format is very complete, while the mp3 format only has 128kbps and 48kbps. Is it possible to add a higher quality mp3 format?

### Who will benefit from this feature?

When I used Whisper to transcribe Chinese speech, I found that the mp3 quality would affect the transcription results. I would be very grateful if there is a higher quality mp3 format!

**Comment by vimtor** [comment]
The quality settings come from the unofficial YT API we are using, so I'm afraid no more audio options are available.

Sorry 🙏

@raycastbot close this issue
