### ISSUE TITLE
Calculator extension getting wrong results

### ISSUE THREAD

**Issue by oriolvinals** [raycast/extensions#15049]
### Description

Some calculations of `Calculator` are wrong

Only happens using `.`

Adding or removing decimal zeros make the calculations right (like `5/0.0001` => `50000`)

### Steps To Reproduce

* Open Raycast
* Type `5/0.001`
* Get result of `5` instead of `5000`

![](https://github.com/user-attachments/assets/b1a1ebce-19d8-477d-af53-21f1c8dd5738)

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
