### ISSUE TITLE
[Apple Reminders] ...quick add reminder can have an option to specify a date.

### ISSUE THREAD

**Issue by Sean-fn** [raycast/extensions#15045]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

`quick add reminder` can have an option to specify a date.

currently we need to use `create reminder` to go through all the options to add a date, it would be helpful to have that in a quick reminder.

### Who will benefit from this feature?

users who want to add a date

**Comment by michalzuch** [comment]
@raycastbot close this issue
