### ISSUE TITLE
[Apple Reminders] Add tags to reminders

### ISSUE THREAD

**Issue by Matias-Sandoval** [raycast/extensions#15043]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Apple's reminders app allows you to add tags, which I use frequently. When I want to add a tag using the Raycast extension, it's not possible because there's no option to add tags. It would be really helpful if you implemented "add tags" to a reminder.
The user should be able to add an existing tag to a reminder or create a new one.

**Comment by tmwrnr** [comment]
Hi @Matias-Sandoval, adding tags is currently not available by the API Apple provides. 

See #14760

**Comment by tmwrnr** [comment]
@raycastbot close this issue
