### ISSUE TITLE
[Shottr] Add option to open from clipboard

### ISSUE THREAD

**Issue by SamuelPinho** [raycast/extensions#15064]
### Extension

https://www.raycast.com/fernando_barrios/shottr

### Description

I use the `Open From Clipboard` option a lot, and it would be nice to have it as a raycast option too

### Who will benefit from this feature?

I would say that anyone that likes Shottr and uses the Open from Clipboard feature

**Comment by tmwrnr** [comment]
Hi @SamuelPinho, I think the command you are looking for is **Load Clipboard**. If the naming is not intuitive for you, you could use an alias in Raycast.

**Comment by SamuelPinho** [comment]
Ohh, thank you so much @tmwrnr 🙏
