### ISSUE TITLE
[LeetCode] Ability to copy problem to clipboard

### ISSUE THREAD

**Issue by vbshubham** [raycast/extensions#15067]
### Extension

https://www.raycast.com/justin0u0/leetcode

### Description

This is useful during interviews. It would be even better if there was an option to copy directly to markdown.

**Comment by xmok** [comment]
Can't believe we don't already have this feature 🤯.
Would you be interested in making a PR?

**Comment by justin0u0** [comment]
Hey @vbshubham, thanks for the suggestion! That sounds really useful.

If you don’t have the time to open a PR, feel free to let me know. I can add this feature.

**Comment by vbshubham** [comment]
Yeah. I am on vacation for a couple of weeks. If you could sdd the feature.
That would be great.

**Comment by justin0u0** [comment]
@raycastbot assign me

**Comment by justin0u0** [comment]
@raycastbot close this issue
