### ISSUE TITLE
[Google Maps Search] Extension

### ISSUE THREAD

**Issue by dingemann** [raycast/extensions#15062]
### Extension

https://www.raycast.com/ratoru/google-maps-search

### Raycast Version

1.84.3

### macOS Version

15.0.1 (24A348)

### Description

Wrong search term.

### Steps To Reproduce

1. open extension via keyword "map"
2. enter search term
3. pressing enter

### Current Behaviour

Either only part of the search term is send to google maps or the last search term I used.

### Expected Behaviour

Send the search term I provided.

**Comment by klaussner** [comment]
Hi @dingemann, are you referring to the input delay in the "Search Google Maps" command? If you press enter too soon, the rest of the input text will not be included in the first list element, which is used for searching:

https://github.com/user-attachments/assets/4960f581-4e0b-4cf3-b09a-8a0336f410e2

I think we could remove `throttle: true` here to avoid the delay:

https://github.com/raycast/extensions/blob/675b730bb18b220ca4d676b4a68e12cf9ed1ba7e/extensions/google-maps-search/src/find.tsx#L55

**Comment by dingemann** [comment]
@klaussner yes, thanks for pointing out. It seem to be related to the delay. When I wait for the suggested term to show up, there is no problem. When I type and then hit enter real quick, it uses the last search term.
