### ISSUE TITLE
[Spotify Player] Search playlists

### ISSUE THREAD

**Issue by morellodev** [raycast/extensions#1507]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/317b7f140dfc4a304317e5bde1408221e0777e30/extensions/spotify-player/)
Author: @mattisssa

It would be super nice if we could search for playlists too.

**Describe the feature and the current behavior/state.**

Currently this extension only lets us searching for songs. This request is for adding the ability to search for playlists too.

**Who will benefit with this feature?**

Everyone (common use case: directly search for the "Discover Weekly" playlist).

**Any Other info.**

**Comment by andreaselia** [comment]
I believe this can be closed due to #1512 being implemented?
