### ISSUE TITLE
[OpenAI Translator] Update the language switcher

### ISSUE THREAD

**Issue by demidchick** [raycast/extensions#15079]
### Extension

https://www.raycast.com/douo/openai-translator

### Description

I love the extension, but there's one tiny thing that complicates the use. Switching between my languages is a bit cumbersome. The languages I always use aren't on the top of the list, so I have to use the search bar. And since the language names are spelled in different writing systems, I have to switch the language on the keyboard → enter the language name → switch the language back → enter the phrase for translation.

This, of course, can be solved in different ways. Here's a few that I think could work without disrupting experience for other users:
1. Allow language pinning. This way, we could use ⌘ + P to open the language menu and then ⌘ + 1 / ⌘ + 2 / ⌘ + 3, etc. to switch between languages. Or maybe just introduce some universal shortcut for toggling between languages.
2. Add the English version of the language to the list, e.g. _Deutsch (German)_. This way, it'll be possible to search for any language without having to switch back and forth.

Any other work-around would also be amazing!

### Who will benefit from this feature?

Everyone who uses languages from different writing systems.

**Comment by douo** [comment]
Thank you for your feedback. Regarding the first point, do you think this PR https://github.com/raycast/extensions/pull/15123 could resolve your issue? As for the second point, it's also a very intuitive request, and I'll see how best to handle it.

**Comment by demidchick** [comment]
@douo yes, the "recent" languages will indeed solve my problem. Thank you, appreciate your help!
