### ISSUE TITLE
[Pomodoro] ...

### ISSUE THREAD

**Issue by codbro** [raycast/extensions#15086]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

Currently the app gives a total number of pomos since the beginning. And that is all.
It would be useful to see today's total number of pomos.
Maybe even weekly.

### Who will benefit from this feature?

Anyone who uses the pomo feature

**Comment by LitoMore** [comment]
The feature is already in `View Pomodoro Stats` command.
