### ISSUE TITLE
[Cloudflare WARP] ...

### ISSUE THREAD

**Issue by onuroenal** [raycast/extensions#15099]
### Extension

https://www.raycast.com/anandubajith/cloudflare-warp

### Raycast Version

1.84.3

### macOS Version

15.0.1 (24A348)

### Description

Cloudflare warp connect is working, but disconnect isn't working. (WARP version: 2024.9.346.0 (20241003.18))

### Steps To Reproduce

1. Run WARP Connect command
2. Connection is enabled
3. Run WARP Disconnect command
4. Connection is still enabled

### Current Behaviour

When I run the warp connect command, warp is working and status turn the enabled. But when I run the disconnect command, warp is still working and connection isn't disabled.

### Expected Behaviour

When I run the warp disconnected command the connection should be disconnected.

**Comment by anandubajith** [comment]
@raycastbot assign me
