### ISSUE TITLE
[Home Assistant] Assist command does not store send history

### ISSUE THREAD

**Issue by TKDKid1000** [raycast/extensions#15101]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Raycast Version

1.84.3

### macOS Version

15.1

### Description

When using the "Assist" command with any voice assistant that is _not_ the default "Home Assistant," which ignores chat history, the chat history is not sent to the Home Assistant server. For example, using both Ollama's and Gemini's integrations, the chat history would not be sent to the server, only displayed on the client, resulting in situations like these:
![homeassistant 2024-10-26 at 21 46 59](https://github.com/user-attachments/assets/1952a904-62fa-45b8-8f5e-457c485d958a)
These multi-turn conversations work fine within the standard Home Assistant UI, so I would imagine that they should function here, as well.

### Steps To Reproduce

1. Install and configure the Google-GenerativeAI extension in Home Assistant.
2. Add a new assistant using Gemini.
3. Run the Raycast "Assist" command and type any instruction, whether that be a query or a command. For example, "turn on the kitchen lights."
4. Ask the assistant to "turn off what you just turned on."

### Current Behaviour

The current chat history is not sent to the server, only the most recently sent message.

### Expected Behaviour

The entire chat history visible on the client should be sent to the server.

**Comment by ristomatti** [comment]
This still seems to be an issue.
