### ISSUE TITLE
[Joplin] Opening founded note in Joplin is not working 

### ISSUE THREAD

**Issue by m-pawelczyk** [raycast/extensions#15105]
### Extension

https://www.raycast.com/wisdom-plus/search-joplin-notes

### Raycast Version

1.70.3

### macOS Version

14.4.1

### Description

I ma using extensions to search note, but when I try to open note in Joplin app, it it not working. I am always getting last opened app in Joplin. It works different than Webclipper which is opening last created app by WebClipper

### Steps To Reproduce

1. Run Joplin Serach extensions in Raycast
2. Search for note
3. Click `ENTER` to get note preview
4. Click `ENTER` open note in Joplin

### Current Behaviour

It is just opening Joplin with last opened note. Not navigating to search note so basically it is needed to search again. 

### Expected Behaviour

It should open note in Joplin which I found than I can continue read or edit

**Comment by wisdom-plus** [comment]
@raycastbot assign me

**Comment by wisdom-plus** [comment]
@m-pawelczyk 
Thank you for the issue that I fixed with this [PR](https://github.com/raycast/extensions/pull/15592) in Open Note.

@raycastbot close this issue

**Comment by m-pawelczyk** [comment]
@wisdom-plus Very sorry for late reply. Thank you very much for fixing this. It works like a charm! 

P.S. I missed this update somehow :/
