### ISSUE TITLE
[Spiceblow - Sql Database Management]...

### ISSUE THREAD

**Issue by ramzimalhas** [raycast/extensions#15106]
### Extension

https://raycast.com/xmorse/spiceblow-database

### Raycast Version

Latest

#### Error:
```
TypeError: fetch failed
    at ue.exports.fetch (/Users/ramzimalhas/.config/raycast/extensions/422e9651-46b0-4a23-a4e3-531db71bea09/search-database.js:74:6145)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/ramzimalhas/.config/raycast/extensions/422e9651-46b0-4a23-a4e3-531db71bea09/search-database.js:3263:4908
    at async /Users/ramzimalhas/.config/raycast/extensions/422e9651-46b0-4a23-a4e3-531db71bea09/search-database.js:3289:3273
```

### Steps To Reproduce

It seems like the error is a ⁠TypeError indicating that a ⁠fetch operation failed in a JavaScript file located at ⁠/Users/ramzimalhas/.config/raycast/extensions/422e9651-46b0-4a23-a4e3-531db71bea09/search-database.js at line ⁠74:6145. The error is being caught in the ⁠processTicksAndRejections function.
To understand this error better and how to handle it, you can refer to the documentation on ⁠fetch in JavaScript:
	•	MDN Web Docs - Fetch API
This documentation will provide insights into how the ⁠fetch API works, possible reasons for the failure, and how to handle errors when using ⁠fetch in JavaScript.🐛 fix: fix typeerror caused by failed fetch operation in search-database.js

### Current Behaviour

🐛 fix: fix typeerror caused by failed fetch operation in search-database.js

### Expected Behaviour

not sure im a noob!

**Comment by remorses** [comment]
Does this error happens consistently? This error means that the extension could not reach the backed server, maybe you were disconnected from the internet?
