### ISSUE TITLE
[LookSee - A MAC, OUI, IAB Lookup] Notify User MAC Address is Randomized on Lookup

### ISSUE THREAD

**Issue by stephenjmcmahon** [raycast/extensions#15104]
### Extension

https://www.raycast.com/olavgjerde/looksee

### Description

Notify user if looking up a private MAC address if 2,6,A, or E is in the second spot that this is very likely a private MAC address. This also will cut down on unnecessary API calls.

    x2:xx:xx:xx:xx:xx
    x6:xx:xx:xx:xx:xx
    xA:xx:xx:xx:xx:xx
    xE:xx:xx:xx:xx:xx

https://www.rfc-editor.org/rfc/rfc7042.html#section-2.1
https://www.oasys.net/fragments/identify-private-macs/

### Who will benefit from this feature?

Anyone who is looking up a private MAC address and is not aware of this functionality from RFC

**Comment by stephenjmcmahon** [comment]
This snippet is working for me----

# Function to check if a MAC address is private
is_private_mac() {
    local mac_address=$1
    local first_byte_second_hex=${mac_address:1:1}

    # Check if the second hex digit is 2, 6, A, or E (indicating a randomized/private MAC)
    if [[ "$first_byte_second_hex" =~ [26AEae] ]]; then
        return 0  # Return 0 (true) if the MAC address is private
    else
        return 1  # Return 1 (false) if the MAC address is public
    fi
}


# Check if the MAC address is private
if is_private_mac "$mac_address"; then
    echo "This is a randomized MAC address and cannot be looked up."
    exit 0
fi

**Comment by olavgjerde** [comment]
Hey @stephenjmcmahon and thanks for the detailed feature request! I haven't had the time to look into this yet, but hopefully next week will be a bit calmer than this one 💡

From the top of my head I got this initial thought:
- We'll have to find an elegant way to detect "private/local"-ness across the various MAC address formats that are accepted as input today; semi-colons, hyphens, dot (cisco) and also no separator at all.

**Comment by stephenjmcmahon** [comment]
Hahah we are on similar wavelengths. Arubas AOS/CX vs their wireless controllers used different formatting so I have a script to format lowercase with colons every two characters. Now I work with Cisco and its different again 😂

https://github.com/stephenjmcmahon/Scripts/blob/main/Raycast/macformat.sh

And that is partially included in the maclookup script. I definitely used your idea and the print format emojis so please take anything you want for the big Raycast script🤘
https://github.com/stephenjmcmahon/Scripts/blob/main/Raycast/maclookup.sh

**Comment by olavgjerde** [comment]
Haha, the curveballs keep on coming 😂

Awesome work, I'll take a look at your scripts and see if I can draw some inspiration 😎

**Comment by olavgjerde** [comment]
@raycastbot keep this issue open

**Comment by olavgjerde** [comment]
Here's what I have locally now @stephenjmcmahon, maybe this approach could fit nicely within the existing extension 📸
I added an option to ignore this safe guard via the "Look up anyway" action if one strongly disagrees with it 😂

![looksee 2024-11-07 at 22 51 33](https://github.com/user-attachments/assets/1809004e-12cf-4d81-95a9-05d20c4de68e)
