### ISSUE TITLE
[Next.js Documentation] Examples directory

### ISSUE THREAD

**Issue by vimtor** [raycast/extensions#1511]
# Extension – [Next.js Documentation](https://github.com/raycast/extensions/tree/1cc635e4c5216e96b03242d942b2cb545bf29865/extensions/nextjs-docs/)
Author: @PrasadChinwal 

**Describe the feature and the current behavior/state.**

A new command for searching the [Next.js examples directory](https://github.com/vercel/next.js/tree/canary/examples)

**Who will benefit with this feature?**

Every user who like me searches for examples when integrating Next.js with new technologies

**Any Other info.**

I could develop this feature if needed :)

**Comment by PrasadChinwal** [comment]
@vimtor I think this will be a very good feature to have. Feel free to implement this and send a PR. Let me know if you need anything from me and I'll do my best to help out.
