### ISSUE TITLE
[NBA & WNBA Viewer] Standings are not updated to the 2024-25 season. They still show the 2023-24 season standings.

### ISSUE THREAD

**Issue by akhu27** [raycast/extensions#15114]
### Extension

https://www.raycast.com/AbhinavPalacharla/nba-viewer

### Raycast Version

1.84.3

### macOS Version

15.0.1

### Description

Standings are not updated to the 2024-25 season. They still show the 2023-24 season standings.

<img width="749" alt="Screenshot 2024-10-27 at 12 48 33 PM" src="https://github.com/user-attachments/assets/9c712789-c326-4a87-bac0-c134ce175677">
<img width="746" alt="Screenshot 2024-10-27 at 12 48 41 PM" src="https://github.com/user-attachments/assets/acb8f572-9b85-4d1e-aec2-bcc7e0fec9d8">

### Steps To Reproduce

1) Open Raycast
2) Search "View Standings"
3) Hit Enter
4) Eastern Conference and Western Conference Results are incorrect.

**Comment by jamtur01** [comment]
This is because we hardcode year to be:

```js
    year: new Date().getFullYear().toString(),
```

From https://site.web.api.espn.com/apis/v2/sports/basketball/nba/standings:

```json
{
  "uid": "s:40~l:46~g:7",
  "id": "7",
  "name": "National Basketball Association",
  "abbreviation": "NBA",
  "shortName": "NBA",
  "children": [
    {
      "uid": "s:40~l:46~g:5",
      "id": "5",
      "name": "Eastern Conference",
      "abbreviation": "East",
      "standings": {
        "id": "0",
        "name": "overall",
        "displayName": "Overall Standings",
        "links": [
          {
            "language": "en-US",
            "rel": [
              "standings",
              "desktop"
            ],
            "href": "https://www.espn.com/nba/standings/_/group/5",
            "text": "Table",
            "shortText": "Standings",
            "isExternal": false,
            "isPremium": false
          }
        ],
        "season": 2025,
        "seasonType": 2,
        "seasonDisplayName": "2024-25",
...
```

So we need a way other than pulling the current year to work out the season.
