### ISSUE TITLE
[Zen Browser] Bookmarks / Profile Selection Issue

### ISSUE THREAD

**Issue by theherk** [raycast/extensions#15129]
### Extension

https://www.raycast.com/Keyruu/zen-browser

### Raycast Version

1.84.3

### macOS Version

15.0.1

### Description

The only bookmarks shown to me in "Search Bookmarks" are the 5 default bookmarks. I'm not sure where they're coming from. I have one profile, and one profile directory. It has these default bookmarks deleted and several others created. The history in "Search History" and
"New Tab" are correct, though.

![Screenshot 2024-10-28 at 11 34 24](https://github.com/user-attachments/assets/b4468e43-0183-4a27-8991-db993367154e)

![Screenshot 2024-10-28 at 11 29 28](https://github.com/user-attachments/assets/88bb4481-220c-4b1d-9bca-c02f6870704b)

![Screenshot 2024-10-28 at 11 30 45](https://github.com/user-attachments/assets/fb51310e-3081-4995-a180-e4fd2a6143b6)

### Steps To Reproduce

I'm really not sure how to reproduce this one, but I've provided as much information as I have.

### Current Behaviour

I get the default bookmarks from a profile that doesn't exist. Maybe a cache thing.

### Expected Behaviour

I can search my bookmarks.

**Comment by Keyruu** [comment]
Oh sorry for the ping to the firefox extension maintainers. How can I remove you from that?

**Comment by Keyruu** [comment]
But about the issue: I'll have to check this, maybe it only shows me the bookmarks it synced from Firefox for me and not the new ones I added in Zen.

**Comment by theherk** [comment]
At some point, with no changes from me, it added the proper bookmarks. However, it still has the default bookmarks even though they're removed, and doesn't keep up-to-date. Since there is no cache for the plugin, I don't know how it is updated or even can get out-of-sync, but it does seem to lag behind actual updates to bookmarks. For instance, I've added a new bookmark and it doesn't show. Maybe in some days, it will.

**Comment by theherk** [comment]
Wait, just looking through the source code, it looks like this reads bookmarks from <profile>/bookmarkbackups rather than from the sqlite db, so they will only ever be up-to-date with the backup file. Maybe that should change?

In any case the workaround is to take a backup, which no matter where you set it, will also create a backup in the profile directory and update the plugins results. I'll leave it to you if this behavior should change.

**Comment by Keyruu** [comment]
Yup, this is how the current Firefox extension handles it, I have no idea why. Will create a PR with a fix that should display all bookmarks and be up to date with the ones in the browser :D
