### ISSUE TITLE
[Obsidian] Extension does not work for any actions

### ISSUE THREAD

**Issue by Pucekcom** [raycast/extensions#15147]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Raycast Version

1.84.6

### macOS Version

15.2

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

Search for anything.

### Current Behaviour

Extension does not work at all.

**Comment by vcavallo** [comment]
I'm having this issue. it looks like every instance of similar issues are closed as "inactive"...
