### ISSUE TITLE
[Color Picker] ...

### ISSUE THREAD

**Issue by FARLilian** [raycast/extensions#15149]
### Extension

https://www.raycast.com/thomas/color-picker

### Raycast Version

1.84.6

### macOS Version

Sequoia 15.0.1

### Description

Sometimes color picked from Figma or Storybook is not accurate to hex code. There's also no way to manually add colors or correct the hex code.
![Screenshot 2024-10-29 at 3 30 26 AM](https://github.com/user-attachments/assets/8ed03646-7c3d-4525-b9ef-7e733728bd47)
![Screenshot 2024-10-29 at 3 32 26 AM](https://github.com/user-attachments/assets/0ed65776-345c-4f97-8cbb-3c63a2c4e004)

### Steps To Reproduce

1. Make colored rectangle in Figma with HEX #003B5C
2. Use Raycast Color Picker to eyedrop color from rectangle

### Expected Behaviour

Correct hex# code being copied and way to manually add colors/correct hex code.

**Comment by LitoMore** [comment]
It's not a bug. It depends on your display profile.

![](https://github.com/user-attachments/assets/80b999d6-6f17-4bf6-b7d9-93cc287fce52)

Similar topic: https://stackoverflow.com/questions/30050879/color-picker-on-mac-os-x-selects-wrong-colors

**Comment by FARLilian** [comment]
> It's not a bug. It depends on your display profile.
> 
> ![](https://private-user-images.githubusercontent.com/8186898/381106650-80b999d6-6f17-4bf6-b7d9-93cc287fce52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDMwNDMsIm5iZiI6MTczMDIwMjc0MywicGF0aCI6Ii84MTg2ODk4LzM4MTEwNjY1MC04MGI5OTlkNi02ZjE3LTRiZjYtYjdkOS05M2NjMjg3ZmNlNTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjlUMTE1MjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGNlZjUyMWRmNDI3YTY0NTM5N2MzNjQ5MzM3Mzc1M2NkMzJjZDI5OTAxZGViZTU4OWQ2ZTgwYTZmYjE0NmQ2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bdBKkAm9nTmNcvLwR7tY5fQOwou8LDm79Gf1S0oFXXY)
> 
> Similar topic: https://stackoverflow.com/questions/30050879/color-picker-on-mac-os-x-selects-wrong-colors

Oh! That solved it! Thanks!

**Comment by LitoMore** [comment]
@raycastbot close as not planned

**Comment by LitoMore** [comment]
@raycastbot rename this issue to "[Color Picker] Picker selects wrong colors"
