### ISSUE TITLE
[Restart System Processes]: Improve UX

### ISSUE THREAD

**Issue by hrueger** [raycast/extensions#15148]
### Extension

https://www.raycast.com/muzhen_gaming/restart-system-processes

### Description

The extension is working fine and I really like it, however, there are some UX details that could be improved.

This is the current UI:
<img width="751" alt="grafik" src="https://github.com/user-attachments/assets/1c18c1fb-9a00-42f8-abb6-d4c447c4b953">

I suggest the following changes (open for discussion):
- Replace the select with a [list](https://developers.raycast.com/api-reference/user-interface/list)
- in that list, display the most recent command on top (I only need it for restarting audio, however, finder is always the first)
- The sudo option for each command can only be toggled by pressing Tab and Space. Also, that is not remembered. We could move that to [preferences](https://developers.raycast.com/api-reference/preferences)
- The advanced mode option has nothing to do per process like the sudo option, but rather switches the available options in the select dropdown. This should also be moved to the preferences.

### Who will benefit from this feature?

All users of that extension for a faster, more intuitive and raycast-like experience.

### Anything else?

I'd be happy to implement all those changes, but I wanted to discuss them first and get feedback 🙌
Thanks for reading and your input!

**Comment by XInTheDark** [comment]
Hey! Thank you so much for the extensive feedback!

I agree that the List would be a better alternative - although if it does replace the dropdown, it'll need to be intuitive and quick to use.

Regarding the 2 options - the rationale behind putting them in the command itself is so they can be toggled quickly. When I want to restart a process, it's usually a spontaneous thing, and I want to complete it in a few seconds; having to go into Raycast preferences and look for the extension is pretty slow and disruptive to the workflow. Especially the advanced mode checkbox, which is more like a toggle to switch between two very different modes - it's difficult for the user to confidently say "I will only need this mode and not the other". 

I imagine this would be a reasonable redesign: moving the Sudo mode option to the extension preferences, while the advanced mode toggle becomes an action within the command. Please let me know if there is a more suitable one!

The Sudo option not being remembered is definitely a bug  - thanks for pointing it out! Will quickly fix that in the next update, although it would probably be replaced in the redesign.

**Comment by XInTheDark** [comment]
@raycastbot keep this issue open

**Comment by hrueger** [comment]
Hi @XInTheDark,
thanks for the quick response! I totally agree with you, moving sudo to the preferences but keeping the advanced mode option sounds like a plan 👍
Would you like to work on this or should I try and open a PR?

**Comment by hrueger** [comment]
Perfect, I'll give it a shot this afternoon 👍
