### ISSUE TITLE
[Airtable] OAuth errors connecting to Raycast

### ISSUE THREAD

**Issue by Dru89** [raycast/extensions#15159]
### Extension

https://www.raycast.com/marks/raycast-airtable-extension

### Raycast Version

1.84.7

### macOS Version

14.5 (23F79)

### Description

When I try to connect Airtable to Raycast, I get the following error:
> Your OAuth application requested the scope "schema.bases:read data.records:read data.records:write" which your application does not have access to. You can edit this in your OAuth Application's settings 

Note that this error happens even though the Raycast web page says that I'm "Successfully connected to Airtable."

Also, the "Open Raycast" button on the Raycast website doesn't seem to work.

### Steps To Reproduce

1. Install the Airtable extensions
2. Run the "List Bases" command
3. Try to perform OAuth.

### Current Behaviour

An OAuth error is received:
> Your OAuth application requested the scope "schema.bases:read data.records:read data.records:write" which your application does not have access to. You can edit this in your OAuth Application's settings 

### Expected Behaviour

It should connect to OAuth correctly.

**Comment by xmok** [comment]
Hi @Dru89.
We are already aware of this Issue as discussed in PR #14864 specifically https://github.com/raycast/extensions/pull/14864#issuecomment-2419875303. Unfortunately, the OAuth scope still hasn't been updated from Airtable's side. In the meantime, you can follow instructions in the README to create your own OAuth app. I apologize for the inconvenience but it's out of our hands 😔.

@pernielsentikaer how about we change the OAuth ID then to the new one I created? That way we can be ready to roll ASAP.
