### ISSUE TITLE
[Jira Search] Please support multiple accounts/instances

### ISSUE THREAD

**Issue by chhabra496** [raycast/extensions#1517]
# Extension – [Jira Search](https://github.com/raycast/extensions/tree/a6d9ac115da2ebf4c1b41f710ea4b4b46a5b3f7c/extensions/jira-search/)
Author: @svenwiegand

Hi there - any chance you could support multiple accounts or Jira instances? Or if you can provide some tips on how to duplicate the extension so I could configure a second (and third...) jira. 

Thank you

**Comment by svenwiegand** [comment]
I‘m not planning to implement this, as it would be tricky and require quite some efforts. Sorry. But maybe there is another developer interested in implementing this.
