### ISSUE TITLE
[Color Picker] Convert color command has unclear functionality

### ISSUE THREAD

**Issue by sasha-rp** [raycast/extensions#15170]
### Extension

https://www.raycast.com/thomas/color-picker

### Raycast Version

1.84.7

### macOS Version

14.5

### Description

At first I thought the "Convert color" command wasn't working, but I think this may be more of a feature request. I would like to be able to choose the destination color format separately from the main color picker extension setting. Am I misunderstanding this command or does it not work as intended?

### Steps To Reproduce

1. Run "Convert color" command.
2. Paste in a hex color.
3. Press Enter
4. The result is copied to my clipboad, but it's still Hex. Perhaps because my chosen color format in extension settings is already Hex. 

### Current Behaviour

"Convert color" command converts from HEX to Color Format chosen in extension settings.

### Expected Behaviour

"Convert color" command allows user to choose destination color separately from the global color picker format setting. 

There are different potential ways I could see this working:
1. Set the color format in the command's settings (just like the global setting)
2. User gets a prompt for which format they'd like when running the command (perhaps an inline argument could work, or it could be a "step 2" for the command if possible)
3. User can choose their desired format in the Actions panel (CMD+K) when running the command
  a. Example: if I paste in a hex color, I could get rgba() by pressing CMD+K, then CMD+1.

**Comment by LitoMore** [comment]
@sasha-rp Thanks for reporting. I think we can change it to a command with view for users to select the target format.

I've noted your feedback and put the to my schedule.
