### ISSUE TITLE
[Pomodoro] Set 'Focus' mode when starting a Focus timer

### ISSUE THREAD

**Issue by alexandrelissowski** [raycast/extensions#15184]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

Would it be possible to trigger the 'Focus' or 'Do Not Disturb' mode on the mac when the Focus timer is started. 

### Who will benefit from this feature?

All user who don't want to be annoyed with notifications during a focus time.

**Comment by mikikiv** [comment]
@raycastbot assign me

**Comment by LitoMore** [comment]
Resolved in #15193.
