### ISSUE TITLE
Hello, we really like your application, it's very cool. Now I need to search for files on my computer, but with disk permissions enabled, I still cannot find any files. Please pay attention to this issue and look forward to your reply! thank you

### ISSUE THREAD

**Issue by MackDing** [raycast/extensions#15199]
### Description

Now I need to search for files on my computer, but with disk permissions enabled, I still cannot find any files. Please pay attention to this issue and look forward to your reply! thank you!

![image](https://github.com/user-attachments/assets/e72df112-8f3c-4e8d-b995-f4f49c0cbf4a)

<img width="280" alt="image" src="https://github.com/user-attachments/assets/40bd2153-3b12-4335-afac-02c2ea280837">

<img width="715" alt="image" src="https://github.com/user-attachments/assets/efd2fbfc-8c74-4c47-923d-18037bfdc402">

### Steps To Reproduce

Shortcuts open raycast
![image](https://github.com/user-attachments/assets/a57c91af-90df-4375-8c3b-6198302a561f)

select Search files ,click enter
![image](https://github.com/user-attachments/assets/ad72d11a-8976-4e8c-ade1-4a5c3513bcd6)

type file name 
![image](https://github.com/user-attachments/assets/bd92a4b5-0364-4a4f-9a1a-4054dc5eea20)

### Expected Behaviour

search any files correct

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
