### ISSUE TITLE
[Apple Reminders] ...Menubar - filter by smart list

### ISSUE THREAD

**Issue by pm3c** [raycast/extensions#15192]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

I have countless to do tasks in Reminders, and I've got it sorted out in 1 smart list for the day - the stuff that really needs to get done on that day (I filter by date, today or overdue, and if the task is flagged, and eventually by priority). It would be fantastic if the extension would allow to show just these filtered tasks, both on the menu bar part and the "normal" part.

### Who will benefit from this feature?

Everybody!

### Anything else?

Thanks! Really looking forward to it!

**Comment by thomaslombart** [comment]
Thanks for the feature request! It's unfortunately not feasible for the same reasons described https://github.com/raycast/extensions/issues/11482#issuecomment-2025428313, so I'll mark this issue as not planned.
