### ISSUE TITLE
[Quick Event] ... throws "something went wrong"

### ISSUE THREAD

**Issue by succulentpup** [raycast/extensions#15195]
### Extension

https://www.raycast.com/mblode/quick-event

### Raycast Version

1.84.8

### macOS Version

15.1

### Description

It throws "something went wrong" error every time I try to create an event.

### Steps To Reproduce

1. After selecting the Create quickevent, I typed "Focustime today from 10 am to 12:30 pm"

### Current Behaviour

It thows "Something went wrong"

### Expected Behaviour

I expect it to create an event in the calendar integrated to RayCast.

**Comment by joseparreiras** [comment]
Same thing here! Can't seem to find what the error is or get any troubleshooting. It shows the Calendar app but pops "Something went wrong"
