### ISSUE TITLE
[API Bug] Form Selection jumps around

### ISSUE THREAD

**Issue by tonka3000** [raycast/extensions#152]
I try to have dynamic FromTextArea's. The problem is that the dynamically spawn TextAreas have black text color in dark mode, which makes it unreadable. Also the selection jump back and forth (maybe related to #66)

Raycast version: 1.25.1

## Steps To Reproduce

```ts
export function TweetSendForm(props: { replyTweet?: TweetV1 | undefined }) {
  const [messages, setMessages] = useState<string[]>(["something"]);
  const rt = props.replyTweet;
  const submitText = rt ? "Send Reply" : "Send Tweet";
  console.log(messages);
  return (
    <Form
      onSubmit={submit}
      actions={
        <ActionPanel>
          <SubmitFormAction title={submitText} onSubmit={(values: TweetFormValues) => submit(values, rt)} />
          <ActionPanel.Item title="Add" onAction={() => setMessages([...messages, "test"])}/>
        </ActionPanel>
      }
    >
      <FormTextArea id="text" title="Text" placeholder="What's happening?" />
      {messages.map((m, i) => (
        <FormTextArea id={`t${i}`} title={`m ${i}`} placeholder="aaa" defaultValue={m} />
      ))}
    </Form>
  );
}
```

## The current behavior

https://user-images.githubusercontent.com/3163807/138165940-842ffe33-fcce-417c-9bc4-ab90b532925b.mp4

## The expected behavior

Text color like in the non dynamic version + stable selection.

**Comment by tonka3000** [comment]
@fe9lix @mattisssa 
This color behaviour is not only on extensions, the notes system of Raycast has the same problem on the same machine.

https://user-images.githubusercontent.com/3163807/140502832-be5ae384-d2cf-48bc-b2f5-958820c9a673.mp4

**Comment by fe9lix** [comment]
Just for completeness, as briefly discussed via Slack: The color issues probably is a Mojave-specific bug and since we have plans to deprecate support for Mojave at some point, the issue is unlikely to get fixed soon.
The selection/focus issue is a separate bug (updating the issue title to reflect that...)
