### ISSUE TITLE
[Emoji Search] Add aliases to emojis

### ISSUE THREAD

**Issue by grafst** [raycast/extensions#15217]
### Extension

https://www.raycast.com/FezVrasta/emoji

### Description

Some emojis I can never remember the name. With this feature I could add an alias which I can easily remember 😄 

### Who will benefit from this feature?

People who often use obscure emojis and or are bad at remembering.

**Comment by guspimentel** [comment]
You're already able to do that!

![image](https://github.com/user-attachments/assets/e4906975-6618-4faf-bd0f-1717e347e77e)

**Comment by grafst** [comment]
oh I was using a different extension for emojis but that is even better :)
thanks
