### ISSUE TITLE
[Pomodoro] Show Pomodoro Timer In Menu Bar, timer isn't updating

### ISSUE THREAD

**Issue by joacimeldre** [raycast/extensions#15244]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Raycast Version

1.85.0

### macOS Version

14.6.1

### Description

Pomodoro timer in the menu bar doesn't update the timer. It's static until I click the menu item. I've attached a GIF of how I experience this issue.

![Pomodoro Menu Bar](https://github.com/user-attachments/assets/4d0676f2-9769-4abe-8a6d-7fff270ac19a)

### Steps To Reproduce

1. Launch Raycast
2. Enter "Show Pomodoro in Menu Bar" 
3. In Menu Bar, click Pomodoro
4. In context menu, select a timer, for example Focus

### Current Behaviour

Timer displays. Displays max amount of time. Updates every 10 seconds.

### Expected Behaviour

Timer displays. Displays max amount of time. Updates every 1 second.

**Comment by haydencbarnes** [comment]
Hi @joacimeldre , I have had this behavior happen once before, believe restarting my MacOS and Raycast fixed it. Have you tried restarting your device?

**Comment by joacimeldre** [comment]
Hi Hayden. Thanks! I've restarted my MacBook (and Raycast). I experience
the same behaviour.

**Comment by joacimeldre** [comment]
Hi again. Raycast has updated to version 1.85.0. I'm still experiencing the
same behaviour.

**Comment by haydencbarnes** [comment]
@joacimeldre Have you also tried deactivating and reactivating the menu bar icon? 
![CleanShot 2024-11-07 at 10 12 37@2x](https://github.com/user-attachments/assets/0ed8759a-9aad-4090-a44e-6a3ff5ff4fd4)

**Comment by haydencbarnes** [comment]
Also curious to know if you are using an external display with your Mac?

**Comment by mikikiv** [comment]
I know that the package.json has the menu bar item at an interval for 10seconds. I dont know if that is how often the time updates but thats what i feel like i see generally on my system

```

commands": [
    {
      "name": "pomodoro-menu-bar",
      "title": "Show Pomodoro in Menu Bar",
      "subtitle": "Control timers from menu-bar",
      "description": "Start, pause, stop or continue pomodoro intervals",
      "mode": "menu-bar",
      "interval": "10s"
    },

```

I wonder if updating this to 1 or 2s will make this feel nicer?

Also, @joacimeldre do you definitely have background refresh enabled for Pomodoro in its settings?

**Comment by joacimeldre** [comment]
> @joacimeldre Have you also tried deactivating and reactivating the menu bar icon?

I just tried this. No change in behaviour.

> Also curious to know if you are using an external display with your Mac?

Yes, I'm using an external display. I tried detaching the display. Same behaviour with and without an external display. I'm also noticing that the Pomodoro menu bar only updates on the menu bar on the display that I'm currently active in.

> Also, @joacimeldre do you definitely have background refresh enabled for Pomodoro in its settings?

Yes. No changes have been done. This is default setting.
![CleanShot 2024-11-08 at 11 18 43@2x](https://github.com/user-attachments/assets/6c19c559-ef38-4516-8ee3-917f33145d71)

> I know that the package.json has the menu bar item at an interval for 10seconds. I dont know if that is how often the time updates but thats what i feel like i see generally on my system

Now that I understand more of how this plugin is expected to behave, this is what I'm experiencing. The clock updates every 10 seconds. Not every second as I expect from a clock that displays seconds.

So this isn't really a bug, it's a change request. Sorry, I'm dumb. 🥇

**Comment by joacimeldre** [comment]
I've updated the description to make it more clear what current and expected behaviour is.

**Comment by haydencbarnes** [comment]
https://developers.raycast.com/information/lifecycle/background-refresh#:~:text=The%20minimum%20value%20is%2010%20seconds -> This is a Raycast limitation for developers, thank you for your request but it is not possible at this time.

**Comment by haydencbarnes** [comment]
@raycastbot close this issue
