### ISSUE TITLE
TypeSnob: Add ª as an available character

### ISSUE THREAD

**Issue by victenheuser** [raycast/extensions#15252]
### Extension

https://www.raycast.com/sawyerh/type-snob

### Description

Could you add this little guy  ª  ?

### Who will benefit from this feature?

Brazillian and portuguese people.

**Comment by sawyerh** [comment]
@raycastbot keep this issue open

**Comment by sawyerh** [comment]
@raycastbot rename this issue to "TypeSnob: Add ª as an available character"
