### ISSUE TITLE
[Google Gemini] Extension Unable to Access Gemini API - All Queries Failing

### ISSUE THREAD

**Issue by maverickOG** [raycast/extensions#15251]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-gemini

### Raycast Version

1.85.0

### macOS Version

15.1 (Sequoia)

### Description

The Google Gemini extension is currently unable to access the Gemini API for any type of query. All attempts to use the extension result in an access error, regardless of the query content. This has been tested with various types of queries including technical questions ("What is overloading"), medical information ("What is the cause of multiple sclerosis"), and general knowledge questions ("What is trial").

### Steps To Reproduce

1. Open Raycast
2. Access the Google Gemini extension –> Ask AI
3. Enter any query (tested with multiple different topics)
4. Press Enter

### Current Behaviour

For all queries, the extension returns the following error:
"Could not access Gemini. This may be because Gemini has decided that your prompt did not comply with its regulations. Please try another prompt, and if it still does not work, create an issue on GitHub."

### Expected Behaviour

The extension should be able to successfully connect to the Gemini API and return relevant responses for standard queries across all topics. The current behavior suggests there might be an underlying authentication issue or API connection problem rather than a content policy violation since it affects all types of queries.

**Comment by EvanZhouDev** [comment]
I have tried the extension, and I cannot seem to replicate this on my end. Try to use Gemini's website, and see if it works there. Alternatively, also try getting a new API key.

**Comment by maverickOG** [comment]
Hey @EvanZhouDev, thank you. Creating a new API key worked. I don't know why the old API key was causing an issue, but creating a new one worked. If it happens again, I will keep this in mind.

**Comment by azenahlik** [comment]
Experiencing the same issue, changing keys / projects did not help.  
Extension worked for one day and stopped working suddenly.

The following works as expected: 

```bash
curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=api_key_here" \
-H 'Content-Type: application/json' -X POST -d '{"contents":[{"parts":[{"text": "Test"}]}]}'
```

but using streamGenerateContext instead of generateContext produces the following:

```json
{
  "error": {
    "code": 400,
    "message": "Invalid resource field value in the request.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "RESOURCE_PROJECT_INVALID",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.cloud.aiplatform.internal.PredictionService.StreamGenerateContent",
          "service": "aiplatform.googleapis.com"
        }
      }
    ]
  }
}
```

Using streamGenerateContext still works with gemini-pro, though, just not with gemini-1.5-flash.  
The only combination with issues is flash+stream.  
Changing to pro in the settings does not work either, though, so this might not be related.

Checking traffic with Proxyman, I cannot see any outgoing requests when submitting text in the extension.

**Comment by mlebkowski** [comment]
I’m having the same issue. @azenahlik, you need to manually check the proxy box in raycast advanced settings. Here’s the request/response the Gemini extension makes:

```json
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:streamGenerateContent?key=__redacted__&alt=sse
{
  "contents": [
    {
      "parts": [
        {
          "text": "test"
        }
      ],
      "role": "user"
    }
  ],
  "generationConfig": {
    "temperature": 1,
    "maxOutputTokens": 2048,
    "topP": 0.94,
    "topK": 32
  }
}
```

```
{
  "error": {
    "code": 400,
    "message": "Invalid resource field value in the request.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "RESOURCE_PROJECT_INVALID",
        "domain": "googleapis.com",
        "metadata": {
          "service": "aiplatform.googleapis.com",
          "method": "google.cloud.aiplatform.internal.PredictionService.StreamGenerateContent"
        }
      }
    ]
  }
}
```
