### ISSUE TITLE
Incorrect identification

### ISSUE THREAD

**Issue by RyuSeongbin** [raycast/extensions#15254]
### Description

If the main language is set to Simplified Chinese, ocr can recognize English but not Korean text, and if the main language is set to Korean, it can't recognize Chinese text. 
I don't know if it's a bug or it doesn't support multi-language recognition in the first place?

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
