### ISSUE TITLE
Clipboard History copies text from Illustrator as an image

### ISSUE THREAD

**Issue by riadhrebei** [raycast/extensions#15262]
### Description

Hello, as the title describes, my Raycast clipboard history shows copied text from Illustrator as an image instead of text like all other apps, the only thing that works is copying the text, pasting it in notes or text editor, copy it again and only then I can paste it in other apps/websites

Sorry for opening the issue here as I couldn't open it in the extensions bug report since it asks for an extension link and Clipboard History isn't on the Raycast Store

### Steps To Reproduce

1. Copy text from illustrator
2. Paste it in ChatGPT or other websites
3. It gets pasted as an image if the website allows it or doesn't paste it at all

### Current Behaviour

Pasting text as an image if copied from Illustrator
![Raycast 2024-11-07 at 14 31 31](https://github.com/user-attachments/assets/c3ac3a0f-0798-4c27-977e-6667f9dfc20b)

### Expected Behaviour

Pasting text like it should
![Raycast 2024-11-07 at 14 31 41](https://github.com/user-attachments/assets/3d0b3709-4b1e-4283-b804-630371734ee3)

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
