### ISSUE TITLE
[Open With App] Show recommended apps first

### ISSUE THREAD

**Issue by royhenengel** [raycast/extensions#15268]
### Extension

https://www.raycast.com/fturcheti/open-with-app

### Description

When triggering "Open With App," Raycast displays recommended apps for opening the file, which makes sense.
When trying to search Raycast for a specific app to open the file with, Raycast shows first other applications and then the recommended ones. When searching for an app, the result will usually come up first in the recommended apps section, which is again displayed at the end.

When searching for an app, it probably makes sense to show the recommended apps first.

### Anything else?

![CleanShot 2024-11-07 at 19 34 24](https://github.com/user-attachments/assets/32675362-e798-4632-8a24-a17cba3219d1)

**Comment by fturcheti** [comment]
@royhenengel Thanks for the report. I'll publish a fix soon.
