### ISSUE TITLE
Copy Image to Clipboard

### ISSUE THREAD

**Issue by davidchalifoux** [raycast/extensions#1527]
**Describe the feature and the current behavior/state.**
Currently, `CopyToClipboard` will only accept a string or a number. In the extension I am working on, I would love to be able to copy an image to the clipboard.

**Will this change the current API? How?**
I propose that  `CopyToClipboard` should accept the [ClipboardItem](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem) interface as well.

**Who will benefit from this feature?**
This will enable developers to write arbitrary data to the clipboard, allowing for more advanced functionality.

**Any Other info.**
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write

**Comment by cernard** [comment]
I Hope will implement this feature soon, need it too. 🙏🏻

**Comment by mathieudutour** [comment]
Available in v1.43
