### ISSUE TITLE
[Pomodoro] Check time left command

### ISSUE THREAD

**Issue by Jussinevavuori** [raycast/extensions#15274]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

I have hidden the pomodoro countdown from my menubar as (1) I have very little space left there and (2) I don't like seeing an active countdown, it distracts me from both focusing and relaxing.

Every now and then I would still like to be able to quickly check how much time my current timer has left. For that purpose, I would love a **View remaining time** command that simply tells me how much time I have left until the current timer ends.

Thank you!

### Who will benefit from this feature?

I believe users, who do not like having the Pomodoro timer in their Menubar.

**Comment by mikikiv** [comment]
@Jussinevavuori would clicking the menu bar item to see the time left satisfy this for you?

**Comment by Jussinevavuori** [comment]
> @Jussinevavuori would clicking the menu bar item to see the time left satisfy this for you?

Fastest Github reply ever, but yes, I think that would satisfy the need, if it is easier to developer than a new command! Thank you for the quick response.

**Comment by mikikiv** [comment]
@raycastbot good first issue
@raycastbot keep this issue open

**Comment by haydencbarnes** [comment]
@mikikiv Maybe I am a little confused, but is this currently working as expected? I do not see the time left when clicking the menu bar item.

**Comment by mikikiv** [comment]
> @mikikiv Maybe I am a little confused, but is this currently working as expected? I do not see the time left when clicking the menu bar item.

The ask here is to add a way to both hide the time on the menu bar and have quick access to the time left.
I imagine we can a menu item in the menu bar that shows the time left.
