### ISSUE TITLE
[GitHub] Failed to fetch latest data

### ISSUE THREAD

**Issue by shyakadavis** [raycast/extensions#15278]
### Extension

https://www.raycast.com/raycast/github

### Raycast Version

1.85.1

### macOS Version

13.6.9

### Description

When opening the menu bar to inspect your GitHub notifications, it just throws an error `Failed to fetch latest data`.

<img width="1680" alt="Screenshot 2024-11-08 at 12 01 03" src="https://github.com/user-attachments/assets/088886ef-f44a-48aa-8a43-90aa7cac03ed">

### Steps To Reproduce

Click on the GitHub menu bar.

### Current Behaviour

No data is shown, only an error.

### Expected Behaviour

A list of notifications from GitHub

**Comment by thomaslombart** [comment]
How many notifications do you have?

**Comment by shyakadavis** [comment]
@thomaslombart  At the time of writing, 2 are unread.

**Comment by thomaslombart** [comment]
Does all of the other commands fail with the same error?

**Comment by shyakadavis** [comment]
No. Only when relying to on the menubar for unread notifications. (TBH, this is my majority use case of the extension)

**Comment by shyakadavis** [comment]
![Screenshot 2024-11-08 at 13 06 42](https://github.com/user-attachments/assets/0bf0b7ea-d699-4cf1-b527-b9314853a029)

**Comment by thomaslombart** [comment]
Probably because we're trying to fetch the issue/PR associated with it (cf. [this line](https://github.com/raycast/extensions/blob/d2327f163a4c84b9dd57ef993f0d27474b8776ba/extensions/github/src/unread-notifications.tsx#L39)). A `try/catch` around this may do the trick. Would you like to work on this and open a PR?

**Comment by shyakadavis** [comment]
Sure, @thomaslombart I'll get to it.
