### ISSUE TITLE
[Ente Auth] Add user selectable default action choice

### ISSUE THREAD

**Issue by TechTronicLLC** [raycast/extensions#15297]
### Extension

https://www.raycast.com/chkpwd/ente-auth

### Description

Add option to allow choice of default behavior of either paste to active app (current default behavior) or copy to clipboard (currently an action choice, but cannot be selected as default action).

### Anything else?

Thanks so much to the creator of this extension, I like many others I'm sure needed a good alternative after the death of Authy.

**Comment by chkpwd** [comment]
This is a great suggestion, I'm currently on vacation. I can work on this once I'm back.

**Comment by chkpwd** [comment]
This was added in PR #15354

**Comment by TechTronicLLC** [comment]
Great job, much appreciated.
