### ISSUE TITLE
[API Feature Request] A method that return the selected Finder items

### ISSUE THREAD

**Issue by fturcheti** [raycast/extensions#153]
**Describe the feature and the current behavior/state.**

A method that return the selected items in Finder (files and folders). I've asked @thomaspaulmann about this on Slack and he suggested something like `getSelectedFile`, that would fit nicely with `getSelectedText`. I'm not completely convinced by the naming though because the method would ideally return an array of finder items, something like this:

```ts
interface FinderItem {
  path: string;
  isFile: boolean;
  isDirectory: boolean;
}
```

And that could be used like this:

```js
const selection = getSelectedFiles();
const files = selection.filter(item => item.isFile);
files.forEach(file => { console.log(file.path) });
```

**Will this change the current api? How?**

No.

**Who will benefit with this feature?**

Extensions that act on the selected files and/or folders, like #147 – Open Finder Selection With…. Some examples: 

- an extension with commands to open the selection with specific applications, so you could assign a keyboard shortcut to open files with your code editor for example;
- an extension to upload the selected file to an online file sharing service;
- an extension to display the summed size of the selected files;
- an extension to compress the selected files;
- an extension to convert the format of the selected image files.

**Any Other info.**

**Comment by dzg** [comment]
I would suggest making this behave like Launchbar's [Instant Send](https://www.obdev.at/resources/launchbar/help/InstantSend.html). If frontmost selection is Finder items, that is what gets passed. If it is text (in any app), then that gets sent.

**Comment by mathieudutour** [comment]
you can already access the selected text (in any app) with `getSelectedText`. This will add `getSelectedFinderItems` to get the finder items if it is the frontmost app
