### ISSUE TITLE
[Battery Optimizer] ...

### ISSUE THREAD

**Issue by DaddyF** [raycast/extensions#15313]
### Extension

https://www.raycast.com/Qetesh/battery-optimizer

### Raycast Version

Raycast 1.85.1 

### macOS Version

Sequoia 15.1

### Description

Battery Optimizer doesn't work. It returns error, Charging threshold : keyNotFound(code: "CHWA")%

### Steps To Reproduce

Any command regarding battery

**Comment by Qetesh** [comment]
Sorry, duplicate https://github.com/raycast/extensions/issues/14490

**Comment by Qetesh** [comment]
@raycastbot close this issue
