### ISSUE TITLE
[Bitly URL Shortener] Error when trying to shorten a URL

### ISSUE THREAD

**Issue by royhenengel** [raycast/extensions#15339]
### Extension

https://www.raycast.com/blessanm86/bitly-url-shortener

### Raycast Version

Version 1.85.2

### macOS Version

15.1

### Description

Error when shortening the URL: https://www.amazon.com/dp/B0BWHCWV4F?ref=ppx_yo2ov_dt_b_fed_asin_title&th=1

![CleanShot 2024-11-13 at 03 00 38](https://github.com/user-attachments/assets/8ce910b7-1e65-481d-840a-f397cc731e37)

### Steps To Reproduce

1. Copy a URL to the clipboard 
2. Open Raycast and navigate to the extension
3. Execute the extension and see the error

### Current Behaviour

Get a error when shorting the URL

### Expected Behaviour

Get a shortened URL

**Comment by royhenengel** [comment]
Changing the API key seems to have solved the issue.

**Comment by blessanm86** [comment]
@raycastbot close this issue
