### ISSUE TITLE
View Twitter details

### ISSUE THREAD

**Issue by jiserra** [raycast/extensions#1534]
# Extension – [Twitter](https://github.com/raycast/extensions/tree/main/extensions/twitter)

Author: @tonka3000 

**Describe the feature and the current behavior/state.**
Right now when you view the list of e.g. Recent Tweets, you need to press Return to access the tweet to view the entire content of the tweet. It would be awesome if this extension could be updated with the new list+detail view, so instead of "entering" the tweet, just by scrolling with the preview, the user get access to the whole content of the tweet.

**Who will benefit from this feature?**
Anyone who uses the Tweet extension!

**Any Other info.**
I don't know if there's any benefit of viewing the tweet not in the preview…? I guess the functionality can still be there, but having the preview will prevent unnecessary "entering", "escaping" to see the content of the tweets.

**Comment by tonka3000** [comment]
HI @jiserra ,

great idea. I will add this in the next update.

Greetings
Michael
