### ISSUE TITLE
[Obsidian] ...

### ISSUE THREAD

**Issue by billpetro** [raycast/extensions#1535]
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/abb13d130a7df62d2841605c095c3d44f2c795e7/extensions/obsidian/)
Author:

**Describe the feature and the current behavior/state.**

What is the correct way of entering into the extension the Vault location, if it is in an iCloud folder?

**Who will benefit with this feature?**

All iOS/iPadOS users

**Any Other info.**

proper path for iCloud vault access

**Comment by dallin** [comment]
@billpetro I ran into a similar issue and found the solution at marcjulianschwarz/obsidian-raycast#10. It was the escape characters (backslashes) that threw me off.

Just enter the path without any backslashes, like so:
```
/Users/dallin/Library/Mobile Documents/iCloud~md~obsidian/Documents/Notes/
```
Also be sure to add the trailing slash at the end. Doing it this way worked for me.

Hope that helps!

**Comment by marcjulianschwarz** [comment]
Hi @billpetro,

The easiest way to get the path to you vault is to right click on your vault folder, hold the `option` key and click on "copy folder as path". You can paste this path in the extension settings and everything should work. No need to add a `/` or anything.

Hope the screenshot helps even though it's in German:

<img width="357" alt="Bildschirmfoto 2022-05-05 um 22 22 12" src="https://user-images.githubusercontent.com/67844154/167019217-d234be9a-589c-4750-9543-8b810665f475.png">

Of course you can check out the link @dallin posted, maybe this will help too.

**Comment by pernielsentikaer** [comment]
Hi @raanym 👋 

This extension should now be update with this request
