### ISSUE TITLE
[Internet Radio] "Audio application not found" when using Music set as "Audio application"

### ISSUE THREAD

**Issue by tomgenoni** [raycast/extensions#15359]
### Extension

https://www.raycast.com/HelloImSteven/internet-radio

### Raycast Version

1.85.2

### macOS Version

15.1

### Description

When I try to play a station and Music is set as my Audio Application I get an error. The Music app does open but that's as far as it gets. I tested the other Audio Application sources and they all work fine. 

I have another computer and using Music as the selected Audio Application works fine, so it's something about my environment and this may not actually be a bug. But I wanted to report in case there was an easy fix.

I tried restarting and removing the Music preferences, but to no avail.

### Steps To Reproduce

1. Select "Music" as the "Audio Application" in the Internet Radio configuration
2. In Raycast, select "Browse Saved Stations" in Raycast
3. Select any station

![Screenshot 2024-11-13 at 11 26 21 AM](https://github.com/user-attachments/assets/c9b5fb66-600e-4edd-90e8-88ccdb710148)

**Comment by tomgenoni** [comment]
Fantastic extension, btw. Thank you for building this!

**Comment by SKaplanOfficial** [comment]
Hi, can you make sure Music automation is enabled in _System Settings > Privacy & Security > Automation > Raycast_?

**Comment by tomgenoni** [comment]
It was checked but System Events was not. Turning that on fixed it. Thank you!

![PixelSnap 2024-11-13 at 17 45 58](https://github.com/user-attachments/assets/fd9478b8-6a93-484f-abdc-458e3ab5f93e)
