### ISSUE TITLE
[Gif Search] Define Download location

### ISSUE THREAD

**Issue by Blendertom** [raycast/extensions#15372]
### Extension

https://raycast.com/josephschmitt/gif-search

### Description

Please add the option to define a custom download location instead of using the default download folder.

### Who will benefit from this feature?

This will ensure that the downloads folder remains uncluttered by GIFs. By having a single location to review already downloaded GIFs, everything stays organized.

**Comment by ridemountainpig** [comment]
@raycastbot assign me

**Comment by Blendertom** [comment]
Thank you for picking this up - @ridemountainpig 

I know it's a niche ask - but makes big QOL for me.
