### ISSUE TITLE
[ethereum-gas-tracker] Current gas prices are not being fetched

### ISSUE THREAD

**Issue by 0xF16** [raycast/extensions#15385]
### Extension

https://www.raycast.com/vinch/ethereum-gas-tracker

### Raycast Version

1.85.2

### macOS Version

15.1

### Description

Seems like the api endpoint used to provide gas prices is not working (https://api.0x3.studio/gas).

### Steps To Reproduce

1. Enable extension and activate menu item
2. When clicking on it this is the error i get on the screen. Anyway, gas prices seems to be fetched from few days ago (when it was working)
![CleanShot 2024-11-15 at 13 09 19@2x](https://github.com/user-attachments/assets/cc6682a2-c64e-478b-a0c6-1add78dab965)

**Comment by xmok** [comment]
Under the hood the current API was just making a call to Etherscan's Gas Tracker API endpoint. We can modify the extension to directly call the endpoint at https://docs.etherscan.io/etherscan-v2/api-endpoints/gas-tracker but it will mean a user needs to plug in their own API key. Is probably best for @vinch to weigh in first, though.

reference: https://github.com/0x3studio/0x3studio-api/blob/main/pages/api/gas.ts

**Comment by 0xF16** [comment]
I believe it's a good option to consider. The free rate limit is 5 requests per second or 100,000 requests per day (like 1.15 req/s if maxed out and distributed evenly throughout a day). This limit seems sufficient. If there's an option also to choose a frequency, that would be great! Like pulling every 6 seconds or at any other frequency.

**Comment by xmok** [comment]
We can definitely tweak the interval (see: https://developers.raycast.com/information/lifecycle/background-refresh#manifest).
Let's wait a couple of days until the author can chime in otherwise I'd be happy to modify the extension accordingly.
