### ISSUE TITLE
[Ollama AI] Connecting to an external server

### ISSUE THREAD

**Issue by alefeans** [raycast/extensions#15381]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

Hi, I really appreciate the quality of this extension! 

However, I've noticed that it requires the Ollama server to operate locally. As I have an external server running Ollama, it would be wonderful if there were an option to configure the extension to connect to a different host and port. 

Thank you for considering this suggestion!

**Comment by MassimilianoPasquini97** [comment]
@raycastbot assign me

**Comment by MassimilianoPasquini97** [comment]
Hi @alefeans,
this extension can be configure with multiple remote Ollama server. From `Manage Models` command access Actions pressing `cmd+k` and go to `Add Server`.

![image](https://github.com/user-attachments/assets/8fb05faa-244f-42a9-9185-886ac23d3467)

**Comment by MassimilianoPasquini97** [comment]
@raycastbot close this issue
