### ISSUE TITLE
[Visual Studio Code - Project Manager] Do not display untagged projects

### ISSUE THREAD

**Issue by fedeiglesias** [raycast/extensions#1539]
# Extension – [Visual Studio Code - Project Manager](https://github.com/raycast/extensions/tree/131d73bc5096bbb831940570d98f9bae935223dc/extensions/visual-studio-code-project-manager/)
Author: @MarkusLanger

Hello Markus, thank you for this great extension!!

**Describe the feature and the current behavior/state.**
Is there is any way to avoid showing non tagged projects ? 

**Who will benefit with this feature?**
Develops that organize our Projects in Favourites and no-tagged is not an option

**Comment by MarkusLanger** [comment]
Hi @fedeiglesias ,

Thanks for the hint. I created a PR for this feature => https://github.com/raycast/extensions/pull/1545

Best Regards,
Markus

**Comment by MarkusLanger** [comment]
PR merged

**Comment by MarkusLanger** [comment]
@fedeiglesias 

![image](https://user-images.githubusercontent.com/12131918/166133720-735999a3-c338-46d4-b6b2-a2b85a7ae5db.png)
