### ISSUE TITLE
[Cobalt] Cobalt v7 api has been shut down

### ISSUE THREAD

**Issue by Apope1999** [raycast/extensions#15429]
### Extension

https://www.raycast.com/aelew/cobalt

### Raycast Version

1.85.2

### macOS Version

15.0.1 (24A348)

### Description

This extension no longer works due to the following error when trying to download anything from YouTube.

`the cobalt v7 api has been shut down on nov 11th 2024. see https://github.com/imputnet/ cobalt/discussions/860 for more information.`

<img width="886" alt="Στιγμιότυπο οθόνης 2024-11-18, 9 59 45 μμ" src="https://github.com/user-attachments/assets/c6e9075b-3d5e-4f51-9f6d-eeb2b3701b2e">

### Steps To Reproduce

1. Using the latest Raycast and Cobalt version
2. Open extension and paste YouTube video link
3. Hit `Start Download`
4. Error!

**Comment by aelew** [comment]
@raycastbot assign me
