### ISSUE TITLE
[Pocket] Extension doesn't work

### ISSUE THREAD

**Issue by waleedaalhasan** [raycast/extensions#15434]
### Extension

https://www.raycast.com/vimtor/pocket

### Raycast Version

1.85.2

### macOS Version

15.1

### Description

When I try to use the extension after downloading it, using the "save current tab" command, I get this error:
<img width="771" alt="image" src="https://github.com/user-attachments/assets/680ebb6c-68dd-4392-879d-75672a9c21a0">

#### Error:
```
RequestError: self-signed certificate in certificate chain

ClientRequest.<anonymous>:index.js:792:106

---
789:             this._aborted = true

### Steps To Reproduce

1. Download the pcoket extension 
2. Run any command 

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by hrishabhn** [comment]
@raycastbot close this issue
