### ISSUE TITLE
Bitwarden: Multiple Accounts/Vaults

### ISSUE THREAD

**Issue by MatthiasGrandl** [raycast/extensions#1544]
[Bitwarden](https://github.com/raycast/extensions/tree/a7984a6186c92f8af790e6725609b8af9a530279/extensions/bitwarden/)

I have to use multiple bitwarden accounts. The official bitwarden GUI recently added support for that. I would love to be able to use multiple accounts with Raycast as well :)

**Comment by tonka3000** [comment]
Limitation of Raycast right now, see #269

**Comment by MatthiasGrandl** [comment]
Didn't see that issue. Yeah that would cover my request perfectly! Feel free to close this issue.

**Comment by tonka3000** [comment]
@pernielsentikaer
