### ISSUE TITLE
[Pocket] ... Cannot search bookmarks

### ISSUE THREAD

**Issue by miagg** [raycast/extensions#15475]
### Extension

https://www.raycast.com/vimtor/pocket

### Raycast Version

1.86.0

### macOS Version

15.11

#### Error:
```
Error: Missing required property "title" for List.Item


```

### Steps To Reproduce

1. Run `Search Bookmarks` command
2. Authenticate
3. Re-run command

### Current Behaviour

Something went wrong error

### Expected Behaviour

List of bookmarks

**Comment by hrishabhn** [comment]
@raycastbot close this issue
