### ISSUE TITLE
[Apple Reminders] Reminder headers

### ISSUE THREAD

**Issue by FRAGt4g** [raycast/extensions#15482]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Inside the reminders app. there are headers inside a task grouping but they don't show up in the list of tasks view on the raycast extension. If there was a way to add a header and separate tasks based on their heading that would be great for better readability.

### Who will benefit from this feature?

Anyone who really likes the extension and uses the reminders app heavily almost certainly uses sections within a task group and so having this feature would absolutely make the user experiences cleaner, clearer, and more similar to the real app.

These are the section headers that I am talking about and would like to have an equivalent inside the reminders raycast extension.
<img width="704" alt="image" src="https://github.com/user-attachments/assets/aebbcb55-54ed-4c0f-a623-c2910bb46ce5">

### Anything else?

Thanks for looking at this! Love the extension and just want to help make it even cooler if possible. :)

**Comment by thomaslombart** [comment]
Unfortunately, there's no support for sections in Apple's Reminders API, so I'll close this issue as not planned 😕

**Comment by FRAGt4g** [comment]
Well that sucks but thanks for the reply so quick! This might be a dumb work around, but maybe you could add a way to let people “copy” their own into the extension and just remake them specific to raycast?On Nov 22, 2024, at 2:55 AM, Thomas Lombart ***@***.***> wrote:﻿
Unfortunately, there's no support for sections in Apple's Reminders API, so I'll close this issue as not planned 😕

**Comment by thomaslombart** [comment]
That's a possibility, but it would add complexity to the extension since we'll have to fully manage them. It would also mean more manual work for users to keep their sections updated between Apple Reminders and Raycast. We usually try to keep app's extensions (Apple Reminders, Google Workspace, Linear, etc.) close to what the API provides to have the same UX as on their apps.

**Comment by FRAGt4g** [comment]
Yeah it was just a random thought and that all makes sense. Thanks for talking w me!
