### ISSUE TITLE
Include contacts or favorites [FaceTime] ...

### ISSUE THREAD

**Issue by jawy007** [raycast/extensions#1548]
# Extension – [FaceTime](https://github.com/raycast/extensions/tree/636fc1a117a3e071fce708acee546eea6f7992a8/extensions/facetime/)
Author: @ron-myers

<!--
  It would be very nice if the facetime feature could access the contacts app instead of typing the phone number directly. I'd love to be able to type "FaceTime Call", return, then start typing a name and have a dropdown list populate as I finish typing the name of my intended recipient.

**Who will benefit with this feature?**
All users

**Comment by ron-myers** [comment]
Agreed.  I have a start on this (and a Contacts extension) that I plan to finish up the first version of in the next ten days.

**Comment by bill-spilker** [comment]
@ron-myers What is the progress on this? I see your comment on May 1st
