### ISSUE TITLE
Issue publishing with npx

### ISSUE THREAD

**Issue by mikevalstar** [raycast/extensions#15554]
### Description

I am attempting to make a patch for an extension (nanoid) and following this guide: https://developers.raycast.com/basics/contribute-to-an-extension

However when I get to the step to run `npx @raycast/api@latest publish` I receive an error

```
ready  - validate package.json file
ready  - validate package-lock.json
ready  - validate other lock files
ready  - validate extension icons
ready  - run ESLint
ready  - run Prettier 2.8.8
ready  - getting fork
error  - preparing clone
    Error: failed running git Command failed: git reset --hard upstream/main
    fatal: ambiguous argument 'upstream/main': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'


    fatal: ambiguous argument 'upstream/main': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'
```

worth noting this is my first contribution, so my setup should be pretty basic

### Steps To Reproduce

- Run the "fork extension" command in Raycast
- Run `npm install && npm run dev`
- Modify extension
- Commit change 
- Run `npx @raycast/api@latest publish`
- Link github account
- Error is produced

**Comment by mathieudutour** [comment]
Duplicates of #15509
