### ISSUE TITLE
[Simple Reminder] Allow option to use self-hosted ntfy service

### ISSUE THREAD

**Issue by zeitchef** [raycast/extensions#15556]
### Extension

https://www.raycast.com/comoser/simple-reminder

### Description

Currently, the extension allows using `ntfy` to send mobile notifications, but does so only through the public server at `ntfy.sh` which means all notifications are publicly readable. I would like a configuration option to use my own, self-hosted `ntfy` server to keep my notification data private. By doing so, I can utilize the builtin access control mechanisms of `ntfy`.

### Who will benefit from this feature?

Anyone who cares about privacy.

### Anything else?

You can read more about ntfy access controls [here](https://docs.ntfy.sh/publish/#authentication).

**Comment by comoser** [comment]
@zeitchef that’s indeed something very beneficial to add. I’ll work on it as soon as possible 👍

**Comment by comoser** [comment]
@zeitchef in the oven! ☝️

**Comment by comoser** [comment]
@zeitchef enjoy 👐
