### ISSUE TITLE
[Google Drive] Infinite inital loading

### ISSUE THREAD

**Issue by aesign** [raycast/extensions#1558]
# Extension – [Google Drive](https://github.com/raycast/extensions/tree/ba25240e9e2d19f324b49d670e30bcd07f8cfb56/extensions/google-drive/)
Author: @vishaltelangre

## Description

![Screenshot 2022-05-02 at 11 13 18@2x](https://user-images.githubusercontent.com/35091482/166212239-ad068929-fba2-4627-9926-5934d70c261d.png)

## Steps To Reproduce

1. Set up the Google Drive path (/Volumes/GoogleDrive)
2. Run "Search Files" command

## The current behavior
List doesn't load

## The expected behavior
List should load

### Raycast version
Version: 1.33.2

**Comment by vishaltelangre** [comment]
@aesign Thanks for reporting it. 

Did it crash or did the files eventually start showing up (and after how much time)?

Also, how many files do you have in your Google Drive folder (try running the following commands)?

```sh
cd /Volumes/GoogleDrive
find . -type f | wc -l
```

**Comment by vishaltelangre** [comment]
BTW, it takes about 20 seconds for me to build an initial files cache index of about 6840 files. Once the cache index is built, it won't reindex again (until after 7 days or a manual reindexing). 

If there are some folders with a lot of files in them (that are of not much use to you) then you can exclude them using the comma-separated `Exclude Paths` preference (see screenshot) and rebuild the files cache index (using the actions menu).

![image](https://user-images.githubusercontent.com/876195/166235679-4a1f86d1-43bc-4e03-95be-c2947d266177.png)


Besides, I have added a helpful toast message in https://github.com/raycast/extensions/pull/1560 to reduce confusion around this.
