### ISSUE TITLE
[Quick Open Project] Conflicting keyboard shortcut

### ISSUE THREAD

**Issue by davidmondok** [raycast/extensions#15598]
### Extension

https://www.raycast.com/zerowidth/quick-open-project

### Description

The keyboard shortcut for opening the default editor + terminal is Shift + CMD + E. If an alternate editor is configured, the same shortcut is now used for opening the alternate editor basically removing the option to open the default editor + terminal via a shortcut. It would be great to make these shortcuts either configurable or at least make them all unique.

Otherwise awesome shortcut, definitely in my top 3 👍

**Comment by zerowidth** [comment]
Acknowledged, you can tell how little I use this. What do you think about:

- `cmd-E` for "open in editor", along with `enter` (current binding)
- `cmd-shift-E` for "open in alternative editor" (current, conflicted)
- `cmd-o` for "open with..." (current binding)
- `cmd-shift-o` for "open in both editor and terminal"

**Comment by zerowidth** [comment]
@raycastbot assign me

**Comment by davidmondok** [comment]
I agree that it's better to assign a new binding for "open in both editor and terminal" than "open in the alternate editor" as I'm sure more people use the latter.

I'd personally suggest `cmd-b` as b in both. But I would be absolute fine with `cmd-shift-o`. In the end it doesn't really matter as long is it works :)
