### ISSUE TITLE
[Todoist] ... Reader

### ISSUE THREAD

**Issue by VittelOG** [raycast/extensions#15606]
### Extension

https://www.raycast.com/doist/todoist

### Description

I have adhd, I need high pace input. I would like to have a copy paste text reader with a clear AI voice with up to 4x playback speed. Could you imagine implementing that?

### Who will benefit from this feature?

Everyone!!!!

### Anything else?

Thanks for your great work :))

**Comment by thomaslombart** [comment]
That's likely out of the scope of this extension. Feel free to send a feedback to the team instead via the `Send Feedback` command or in the #suggestions channel of the [Slack community](raycast.com/community).
