### ISSUE TITLE
Use entered text when hotkey is invoked 

### ISSUE THREAD

**Issue by gabriel-r** [raycast/extensions#15603]
### Description

When text is entered in the Raycast main input widget, using a command hotkey should pass that text as its input.

Example:

1. Assign the hotkey `Cmd` + `Shift` + `F` to _"Search DuckDuckGo"_
2. Open the main input box
3. Enter the text "loco"
4. Push `Cmd` + `Shift` + `F`

RESULT: The command _"Search DuckDuckGo"_ is launched with the text "loco" directly, do not pass Go, do not collect more input. 

### Who will benefit from this feature?

Everyone using heavily Recast, probably other people coming from Alfred.

### Anything else?

:heart:

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊

**Comment by gabriel-r** [comment]
Submitted via Feedback, thanks!
