### ISSUE TITLE
Accessiblity Tree (AXUIElement)

### ISSUE THREAD

**Issue by fgeierst** [raycast/extensions#15619]
### Description

As a thought experiment, would it be possible for a extension to access the MacOS accessibility tree?

### Who will benefit from this feature?

For example the result could be feed into an llm, paired with a user prompt like "explain the error on the screen" or "summuarize the website I currently opened in my browser". Having the structure output of the accessibility tree that might be more effective then having screenshots as an intermediary step.

### Anything else?

- https://developer.apple.com/documentation/applicationservices/axuielement_h
- https://www.hammerspoon.org/docs/hs.axuielement.html

**Comment by mathieudutour** [comment]
You could, but the accessibility tree is really big usually so might not fit in the context window.

That's not something we will expose in the API but you could use a swift file to get it
