### ISSUE TITLE
[Toggle Desktop Visibility] Doesn't work on macOS Sequoia 15.1.1

### ISSUE THREAD

**Issue by shrinidhi4u** [raycast/extensions#15623]
### Extension

https://www.raycast.com/Haojen/toggle-desktop-visibility

### Raycast Version

1.86.1

### macOS Version

Sequoia 15.1.1

### Description

Doesn't work on macOS Sequoia 15.1.1.

When I run the command Toggle Icon Visibility, the message says Desktop Icons Hidden, but the icons are not actually hidden. I tried relaunching Raycast app, but it still doesn't work.

### Steps To Reproduce

Install Toggle Desktop Visibility
Open Raycast, select Toggle Icon Visibility command, hit Enter
Expected: Desktop icons should be hidden
Actual : Desktop icons are still visible

### Current Behaviour

Desktop icons are not hidden

### Expected Behaviour

Desktop icons should be hidden

**Comment by VatsalSy** [comment]
Hi @shrinidhi4u 

thanks for opening this issue. However, I could not reproduce this error (see below). could you please send a screen recording of your desktop as you try to use this command?

![CleanShot 2024-12-01 at 16 16 59](https://github.com/user-attachments/assets/08c936e0-1de7-4093-92cc-154d52a9a12d)

I am at macOS Sequoia 15.1.1

**Comment by VatsalSy** [comment]
@raycastbot close this issue 

@shrinidhi4u please reopen the issue if you are still having issues with MacOS 15.2.

**Comment by nicolasdvlp** [comment]
@raycastbot reopen this issue

Hello everyone, I have the same problem on Sequoia. Here’s a video, thank you for your help.

![Image](https://github.com/user-attachments/assets/61d2728b-46f5-4e8e-b844-c2f8c0aa0df5)
