### ISSUE TITLE
[Tesla] View car Refreshing

### ISSUE THREAD

**Issue by skyefugate** [raycast/extensions#15624]
### Extension

https://www.raycast.com/williamwelsh/tesla

### Description

Hi! I love the extension, and it is wonderful but is it possible for the 'View Car' command to have it not constantly refreshing the entire page every few seconds? I think this would benefit more from static information or at least just the values themselves updating every few seconds. Currently it just results in the page flashing every few seconds. Love the rest of this extension!

### Who will benefit from this feature?

All users that use the Tesla extension

**Comment by WilliamWelsh** [comment]
Fixed in https://github.com/raycast/extensions/pull/15679
