### ISSUE TITLE
[Visual Studio Code] ...Feature Request: Display git Branch Name in Project List

### ISSUE THREAD

**Issue by YOEL311** [raycast/extensions#15626]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

It would be extremely helpful to have the current branch name displayed alongside each project in the Visual Studio Code - Project Manager extension within Raycast. This feature would provide at-a-glance information about the active branch for each project, saving time and reducing context switching.

### Who will benefit from this feature?

Proposed Implementation
Add a column or tag in the project list view to display the current branch name.
Alternatively, show the branch name as a subtitle or tooltip below the project name.
Provide a setting to enable or disable this feature for users who prefer a minimal view.

Benefits
Improves productivity by reducing the need to open each project to check the branch.
Enhances visibility and awareness of project states, helping developers avoid accidental commits to the wrong branch.
Simplifies the user experience for teams working on multiple branches across different repositories.

**Comment by VatsalSy** [comment]
https://github.com/raycast/extensions/pull/15647 solves this issue. 

@raycastbot close this issue

**Comment by YOEL311** [comment]
Thanks
