### ISSUE TITLE
multiple hotkeys for an app

### ISSUE THREAD

**Issue by fegyi001** [raycast/extensions#15639]
### Description

It would be nice if multiple hotkeys could be added for activating an app. I have a macbook, and Ctrl-Option-Command keys are a good combination for me, but I also have an external keyboard, where the Hyper (Shift-Ctrl-Option-Command) and Meh (Shift-Ctrl-Option) are available. Since I use both the built-in and the external keyboards frequently it would be nice if I could use hotkeys from both of them for opening an app. 

Until now I used Keyboard Maestro which enables this feature. I would like to switch completely to Raycast, because I already use it for everything else, and just running another app in the background for something that Raycast could do seems lame to me.

But since Raycast only allows one hotkey per app as of now, I still have to stick to Keyboard Maestro. 

### Who will benefit from this feature?

Everyone who is in the position of needing to have two or more hotkeys for the same app.

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
