### ISSUE TITLE
[Paste as Plain Text] ... remove trailing periods

### ISSUE THREAD

**Issue by acepelon** [raycast/extensions#15650]
### Extension

https://www.raycast.com/koinzhang/paste-as-plain-text

### Description

Hi there.  I really like your extension.  I have one request: can you allow for the option (or just make default, if multiple periods are present) to remove trailing periods?  Here's a piece of text from an SMS message where I was trying to extract the security code...

`PayPal: 000000 is your security code. Don't share your code.
`
Here is what was returned with paste as number:
`000000..
`

Thanks!
ACE

### Who will benefit from this feature?

Everyone trying to grep out a security code from texts

**Comment by koinzhang** [comment]
Hi @acepelon, thanks for your feedback, fix in #15656

**Comment by koinzhang** [comment]
@raycastbot close this issue
