### ISSUE TITLE
[Pomodoro] ... Daily and Weekly Stats

### ISSUE THREAD

**Issue by mertkaradayi** [raycast/extensions#15653]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

The current stats feature only provides all-time statistics, which are helpful but lack immediate relevance for daily or weekly productivity tracking. To make the stats more insightful, I propose the addition of daily and weekly stats.

For example:
	•	Daily Stats: Total pomodoros completed, total focus time, longest back-to-back pomodoro streak, etc.
	•	Weekly Stats: Weekly summary with totals and trends compared to previous weeks.

This will help users track and optimize their productivity on a shorter, more actionable timeframe, aligning better with the core philosophy of the Pomodoro technique.

### Who will benefit from this feature?

	•	Users looking to evaluate and improve their daily focus and productivity.
	•	Users interested in identifying short-term trends to adjust their schedules and goals dynamically.

### Anything else?

Attached are screenshots showcasing the current all-time stats view. The enhanced stats could follow a similar format but dynamically switch between daily, weekly, and all-time views. Adding a small calendar picker or quick toggle between timeframes could further improve usability.
<img width="372" alt="Screenshot 2024-12-02 at 11 04 43 PM" src="https://github.com/user-attachments/assets/ce533aba-d184-4302-82a7-f7df3ad3f95b">

**Comment by LitoMore** [comment]
Resolved in #15777.
