### ISSUE TITLE
[Open in Sublime Text] Give the possibility to open in an existing Sublime session instead of creating a new one.

### ISSUE THREAD

**Issue by mmemetea** [raycast/extensions#15664]
### Extension

https://www.raycast.com/anfalas/open-in-sublime-text

### Description

- Current behavior: each new open file opens a new Sublime session.
- Desired Behavior: A new tab would be opened if Sublime is already open.

### Who will benefit from this feature?

People would love tidy things: Fewer windows opened—less chaos.

### Anything else?

Thank you!

**Comment by anfalas** [comment]
I just submitted a pull request that fixes the problem.

**Comment by mmemetea** [comment]
Thank you for the fast reaction.
