### ISSUE TITLE
[Git Repos] Error when I set the app to open repos with as `Windsurf`

### ISSUE THREAD

**Issue by aabuhijleh** [raycast/extensions#15673]
### Extension

https://www.raycast.com/moored/git-repos

### Raycast Version

1.86.1

### macOS Version

15.1.1 (24B91)

### Description

Getting this error when I set "Open with" as Windsurf, then try to use the "List Repos" command from the git repos extension.

```
TypeError: Cannot read properties of undefined (reading 'name')

op:list.tsx:294:30

---
291: }): JSX.Element {
292:   return (
293:     <Action.Open
294:       title={`Open in ${props.openWith.name}`}
295:       icon={{ fileIcon: props.openWith.path }}
296:       target={`${getTarget(props.repo, props.openWith)}`}
297:       application={props.openWith.bundleId}
---

    at ray-menu-section
pa:index.js:20:9799
    at ray-action-panel
```

### Steps To Reproduce

1. In macOS
2. Use Git Repos extension
3. Have `Windsurf` app installed https://codeium.com/windsurf
4. Set it as the app to open repos with
5. Use `List repos` command

<img width="748" alt="image" src="https://github.com/user-attachments/assets/6a8e717e-4d55-4aec-bce2-5633c87e5f53">

### Current Behaviour

It's crashing and not letting me use Windsurf as my app to open repos with

<img width="785" alt="image" src="https://github.com/user-attachments/assets/6ffa0bac-5676-4f73-ba8a-925bd1069dad">

### Expected Behaviour

I should see the list of repos and be able to open them with Windsurf

**Comment by aabuhijleh** [comment]
It's working with VSCode and Cursor

**Comment by VatsalSy** [comment]
the Visual Studio Code extension (https://www.raycast.com/thomas/visual-studio-code) lists github repositories associated with recent projects and supports Windsurf.. See updates from Dec 2nd and Nov 17th (https://www.raycast.com/thomas/visual-studio-code)

**Comment by aabuhijleh** [comment]
@VatsalSy Thank you. Appreciate it.

**Comment by VatsalSy** [comment]
Hi @aabuhijleh 

I could not reproduce your error.. 

I attach my setup and the result I get.. All look reasonable.. Did I miss something?

![CleanShot 2024-12-04 at 15 11 42@2x](https://github.com/user-attachments/assets/a4829cc2-8db5-43c8-b453-913ac55bcce7)
![CleanShot 2024-12-04 at 15 11 55@2x](https://github.com/user-attachments/assets/e543783a-8b51-4c16-82a6-e3a8aad32021)


And then I was also able to open in Windsurf when I do ⏎

**Comment by aabuhijleh** [comment]
@VatsalSy Ok, I think this was an issue on my end. I restated my device and this issue disappeared.

Appreciate the help 🙏
