### ISSUE TITLE
[Pomodoro] Session end alerts not showing on macOS 15.2 beta

### ISSUE THREAD

**Issue by chungusmungus** [raycast/extensions#15675]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Raycast Version

1.86.1

### macOS Version

macOS Sequoia Beta 15.2 (24C5089c)

### Description

Hi, after installing the latest update, session end alerts aren’t showing while running the latest Sequoia beta. I tried restarting my Mac, uninstalling and reinstalling the extension and toggling settings off and on. Same deal.

### Steps To Reproduce

1. Run macOS 15.2 beta (24C5089c)
2. Set a timer
3. Wait for it to end

### Current Behaviour

No alert screen / sound showing (but 00:00 does still show in the menu bar)

### Expected Behaviour

Alert screen / sound shows as usual

**Comment by mikikiv** [comment]
Thanks for reporting. This is a duplicate report of issue #15672

**Comment by LitoMore** [comment]
Closing as duplicated.
