### ISSUE TITLE
[Pomodoro] Nothing happens at the end of the timer

### ISSUE THREAD

**Issue by fefzdev** [raycast/extensions#15672]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Raycast Version

1.86.1

### macOS Version

14.6.1

### Description

When the timer reaches 00:00 nothing happens and no gif is displayed. I also still can access the commands "pause" and "reset"

![image](https://github.com/user-attachments/assets/6247f7f2-6676-41dc-a429-b07e820e15f1)

### Steps To Reproduce

I'm using the extension as usual:
1. Start a timer (focus, short break or long break)
2. Wait for the timer to reach `00:00`
3. Raycast should open and display a gif (by default?) **but doesn't** 

### Current Behaviour

1. Start a timer (focus, short break or long break)
2. Wait for the timer to reach `00:00`
3. Nothing happens and timer stays to `00:00`

### Expected Behaviour

1. Start a timer (focus, short break or long break)
2. Wait for the timer to reach `00:00`
3. Raycast should open and display a gif + timer should be set back to `--:--` if no other step is selected

**Comment by haydencbarnes** [comment]
Also seeing this error

**Comment by haydencbarnes** [comment]
Correction: I only see this error when Pomodoro's preference for Do not Disturb (DnD) is turned off; it works when DnD it is turned on.

**Comment by LitoMore** [comment]
OK, let me check then

**Comment by fefzdev** [comment]
Wow! Thanks for the quick fix 🙏

**Comment by haydencbarnes** [comment]
@LitoMore Thank you again for the quick fix, but unfortunately, I am still seeing an error here when Pomodoro's preference for Do not Disturb (DnD) is turned on for a short break; it stops at 00:00.

**Comment by LitoMore** [comment]
Oh my... Let me check..
