### ISSUE TITLE
[Music] setting number of stars support

### ISSUE THREAD

**Issue by leeraymond78** [raycast/extensions#1568]
# Extension – [Music](https://github.com/raycast/extensions/tree/e656b46965d4367c43056d6a4f35e1bddcaf969a/extensions/music/)
Author: @Rawnly

Please help add feature to mark song ranking into 0-5 stars, it's really helpful for old itunes users.

**Comment by Rawnly** [comment]
@leeraymond78 can you add some details? ( I'm not an old music user 😅 )

**Comment by leeraymond78** [comment]
![Screenshot 2022-05-04 at 10 20 50](https://user-images.githubusercontent.com/5274536/166615249-014d7f3f-f671-4bf3-8d03-8fc197c7313b.png)
![Screenshot 2022-05-04 at 10 20 42](https://user-images.githubusercontent.com/5274536/166615252-1a664b93-e58a-4608-885b-3a218c519192.png)
![Screenshot 2022-05-04 at 10 20 32](https://user-images.githubusercontent.com/5274536/166615257-8613f5a4-0fc0-4bfc-855a-6973fd2f3bf7.png)

You can find "Star rankings" in the preference in Music.app, and then you can show the Rating in column, you can set the song 0 - 5 stars.

**Comment by Rawnly** [comment]
Ok I found the script, `tell application "Music" to set rating of current track to <value from 0 to 100 (20 * number of stars)>`
I'll start working on it today 👍

**Comment by pernielsentikaer** [comment]
Thanks @Rawnly 🔥
