### ISSUE TITLE
[Visual Studio Code] Make Git Branch color Gray

### ISSUE THREAD

**Issue by Ernest0-Production** [raycast/extensions#15693]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

The green color of the tag looks very contrasting and accentuating. It would be nice if it was gray

**Comment by VatsalSy** [comment]
@raycastbot assign me

**Comment by VatsalSy** [comment]
https://github.com/raycast/extensions/pull/15699 should fix this

**Comment by VatsalSy** [comment]
#15699 solves this. 

@raycastbot close this issue
