### ISSUE TITLE
[API Feature Request] Allow to register to URL protocol

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#157]
**Describe the feature and the current behavior/state.**

I'd like a way to register a specific URL protocol with my extension.

For example, clicking on a `magnet://` link my Transmission extension should be open and should then be able to do something with the URL

**Will this change the current api? How?**

I don't think so

**Who will benefit with this feature?**

Any extension than needs to register to some url  protocol

**Any Other info.**

**Comment by peduarte** [comment]
Related https://github.com/raycast/extensions/issues/3616
