### ISSUE TITLE
[CleanShot X] … Not capturing screenshot and showing a popup

### ISSUE THREAD

**Issue by mptapasdas** [raycast/extensions#15704]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Raycast Version

1.87.2

### macOS Version

15.1.1

### Description

[![Screen Shot](https://github.com/user-attachments/assets/a152d110-48ad-44d1-a038-cbbdfe081f08)

Gettng this popup whenever I am executing any command for cleanshot.

### Steps To Reproduce

In sequoia 15.1.1 and Raycast 1.82.7, 
Install the cleanshot extension
Execute any command

### Current Behaviour

It is showing a popup with the dialogue There is no application set to open the URL cleanshot://capture-fullscreen?action=copy.

### Expected Behaviour

It should capture the screenshot

**Comment by mptapasdas** [comment]
I have tried uninstalling and reinstalling cleanshotx extension.

**Comment by Aayush9029** [comment]
![CleanShot 2024-12-06 at 23 10 08@2x](https://github.com/user-attachments/assets/8c726819-2da5-4c53-a297-7d4e0607c9df)

@mptapasdas is this selected?

**Comment by mptapasdas** [comment]
@Aayush9029 I dont have any options like this in settings

**Comment by erics118** [comment]
Just to confirm, do you have the clean shot app installed? And what version of the app do you have?

**Comment by mptapasdas** [comment]
my bad i dont have the app installed. my apologies
