### ISSUE TITLE
[Music] Add option to shuffle music directly from library

### ISSUE THREAD

**Issue by jugaldb** [raycast/extensions#1570]
# Extension – [Music](https://github.com/raycast/extensions/tree/e656b46965d4367c43056d6a4f35e1bddcaf969a/extensions/music/)
Author:

Like there is a feature in the music app to shuffle entire library directly, add that too

**Comment by Rawnly** [comment]
@pernielsentikaer this can now be closed, I forgot to mention it in the Pr 👀

**Comment by pernielsentikaer** [comment]
Closed 🔥
