### ISSUE TITLE
[Pomodoro] Daily Focus time and Cycles

### ISSUE THREAD

**Issue by kimdaeyeub** [raycast/extensions#15732]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

I want to see daily focus time and daily cycles. Currently, we can only see the total focus time and cycles for the whole period. I think this is more efficient than seeing the total focus time and cycles for the whole period.

**Comment by kimdaeyeub** [comment]
Can I have a day to try creating this feature?

**Comment by kennguyen107** [comment]
I just came across this. Just wanted to say that I really want this feature implemented as well!
