### ISSUE TITLE
[GitHub] User should be able to select cloning ways when copying clone command

### ISSUE THREAD

**Issue by sushichan044** [raycast/extensions#15749]
### Extension

https://www.raycast.com/raycast/github

### Description

Currently, commands copied by the Copy Clone Command are always for the HTTPS protocol.
We could consider changing this so that users can set their preferences for https/ssh in the settings,
allowing them to choose how they want commands copied.

### Who will benefit from this feature?

Users prefers ssh protocol when execute `git clone`

### Anything else?

It might be nice to add an option to use the GitHub CLI as well as the UI on github.com
<img width="395" alt="スクリーンショット 2024-12-08 19 34 02" src="https://github.com/user-attachments/assets/e62ac4d4-b5a2-4143-95ed-bef41cb80520">

**Comment by sushichan044** [comment]
I am also trying to change the code to address the contents of this issue, but I need to update the schema PR first because I found many differences due to the GitHub schema change when I did the GraphQL codegen.

**Comment by jfkisafk** [comment]
> I am trying to change the code to address this issue. But, I need to create a PR to update gql schema first because I found many differences due to the GitHub schema change when I did the GraphQL codegen.

@sushichan044 I think this is expected. The graphql client is anyways generated so feel free to include your fix for this issue in the PR too.

**Comment by sushichan044** [comment]
@jfkisafk 
Indeed, submitting a PR only to regenerate and wait is a little bothersome.
Thanks for the advice!
