### ISSUE TITLE
[Obsidian] ...full text search of notes

### ISSUE THREAD

**Issue by raanym** [raycast/extensions#1575]
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/abb13d130a7df62d2841605c095c3d44f2c795e7/extensions/obsidian/)
Author: @marcjulianschwarz

**Describe the feature and the current behavior/state.**
Ability search within the notes, not just heading or title. Currently it just searches for file names.

**Who will benefit with this feature?**
Will really help to quickly retrieve information within notes..

**Any Other info.**

**Comment by pernielsentikaer** [comment]
Hi @raanym 👋 

This extension should now be update with this request
