### ISSUE TITLE
[Visual Studio Code] Setting to include only directories

### ISSUE THREAD

**Issue by vinkla** [raycast/extensions#15761]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

It would be helpful to filter out directories and exclude files. Sometimes, I open files in Code, but I don't want them to appear in my "search recent projects" list. This would be a great feature to have. Also, thank you for making the extension, keep up the good work.

**Comment by yug2005** [comment]
@vinkla You can already filter for folders using the dropdown on the top right: 

![image](https://github.com/user-attachments/assets/c1e5cebe-9a7e-4dc0-a78c-c7d1b11386b3)

This preference is also saved for the next time you use the extension.

**Comment by VatsalSy** [comment]
I am closing this issue as completed. @vinkla please reopen the issue if what @yug2005 described is not what you want.. 

@raycastbot close this issue.
