### ISSUE TITLE
[Pomodoro] Make the timer in the menu bar constant width

### ISSUE THREAD

**Issue by heiegg** [raycast/extensions#15779]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

Current font causes slight changes in width of the widget when the time changes. It is slightly annoying. It would be best to keep the widget in width constant, for example by using a monospaced font. 

### Who will benefit from this feature?

Users who don't like to see items in the menu bar shifting.

**Comment by mikikiv** [comment]
I would like to do this but I havent found any way we can use custom fonts or define a width like that in the menu bar. 
@KELiON @LitoMore Do either of you know more about that?

I am working on getting the menu bar text easily removed so you can both hide the countdown in the menubar and quickly see how much time is left which may be the next best way to resolve this for you
