### ISSUE TITLE
[Feature Request] Real-time Preview Support for Extension Commands

### ISSUE THREAD

**Issue by Alivers** [raycast/extensions#15784]
## Current Behavior
Currently, third-party extension commands require users to press Enter to execute and see results, even for simple conversions or calculations. This creates unnecessary friction in the user experience.

## Desired Behavior
Allow extension developers to implement real-time preview functionality similar to Raycast's built-in Calculator command, where results are shown instantly as users type, without requiring Enter to be pressed.

### Currency Conversion
User types: convert 100 USD
Instantly sees: conversions to different currencies
Updates as user modifies the amount

## Similar Features

Built-in Calculator command already implements this behavior.

**Comment by mathieudutour** [comment]
This would hurt the performances of the root search a lot. Unlikely that we'll do it

**Comment by Alivers** [comment]
> This would hurt the performances of the root search a lot. Unlikely that we'll do it

Yeah, understand the performance concern. IMO, it can be an option that user can enable it based their own situation.
