### ISSUE TITLE
[Slack] Search message - Scope error

### ISSUE THREAD

**Issue by boje-velux-ext** [raycast/extensions#15789]
### Extension

https://www.raycast.com/mommertf/slack

### Raycast Version

1.87.4

### macOS Version

15.1.1 (24B91)

### Description

I try to follow this [description](https://github.com/raycast/extensions/blob/49426271f3df025b39a34cf0a941ab80970b9df3/extensions/slack/README.md) but get a error on "Search Message":
The error is
_Missing Scopes
Please make sure your Slack app has all of the
required scopes._

"Open channel" and others is working fine. 

In general it seems like the README.md is not up to date with Slack's website.
![CleanShot 2024-12-10 at 14 48 26@2x](https://github.com/user-attachments/assets/b866663c-9259-4705-aabf-93d37283ca9c)

### Steps To Reproduce

1. Follow readme file
2. Go to "Search message"

### Current Behaviour

Error mention look at the scope setting for the Slack App.

### Expected Behaviour

Being able to search for Slack messages.

**Comment by jfkisafk** [comment]
@boje-velux-ext If you have recently started using the Slack extension for Raycast, would you mind authenticating through OAuth instead of access token? With OAuth, we manage the scopes in the code, so that the users won't need to maintain scopes.

**Comment by boje-velux-ext** [comment]
@jfkisafk the fix was to reinstall the Slack extension. Then I got prompted to OAuth and now the "search message" works
