### ISSUE TITLE
[Media Converter] ... Convert selected media in Finder

### ISSUE THREAD

**Issue by gabrieles02** [raycast/extensions#15786]
### Extension

https://www.raycast.com/leandro.maia/media-converter

### Description

I think a very natural way of using this extension would be to have an option in the settings to automatically have the media selected in finder show in the extension for quick conversion. Entirely avoiding the need for manually selecting the file in the extension. 

### Who will benefit from this feature?

Pretty much every user. I would guess, that if you want to convert a file, you have it open in Finder and it's not in the format you want, so being able to open the extension and convert immediately because the file is already preselected would be very useful.

**Comment by llfmaia** [comment]
Working on it!

**Comment by llfmaia** [comment]
Hello! Changes just got pushed into main. Update the extension and check it out!

**Comment by gabrieles02** [comment]
Works perfectly! Thank you so much!
