### ISSUE TITLE
[Date Format Converter] utcIsoFormat is not correct

### ISSUE THREAD

**Issue by appier-timliou** [raycast/extensions#15849]
### Extension

https://www.raycast.com/yangxy/date-format-converter

### Raycast Version

1.87.5

### macOS Version

13.6.3

### Description

utcIsoFormat is not correct. It should show UTC time.

https://github.com/user-attachments/assets/3a84f6fb-6c08-4cff-a667-aa346c443ad2

### Steps To Reproduce

Just launch the `Format Date` command, and type nothing or `now`.

**Comment by bestemic** [comment]
I’d like to work on this issue. Please assign it to me.
