### ISSUE TITLE
[Fetch YouTube Transcript] ... Can't fetch non-English transcripts?

### ISSUE THREAD

**Issue by eclectiv** [raycast/extensions#15850]
### Extension

https://www.raycast.com/apoorv_khandelwal/fetch-youtube-transcript

### Raycast Version

1.87.5

### macOS Version

15.1.1 (24B91)

### Description

When I try to fetch a video, I get an "Error fetching transcript" that says "Could not find en captions for..." Does the extension only allow for English transcripts? If so, is/would there be a way to let the user select which language the user would like the transcript it?

### Steps To Reproduce

Prompt extension. Paste YT Url.

**Comment by apoorv12** [comment]
@eclectiv It works with English Language Only. I will try If I can add other languages also.

**Comment by apoorv12** [comment]
@eclectiv I’m thrilled to announce that I’ve added support for all major 16 languages! 🎊🎊 I have submitted the PR.

**Comment by eclectiv** [comment]
Fantastic! Great job, @apoorv12 !
