### ISSUE TITLE
[WIP] ...

### ISSUE THREAD

**Issue by alvivanco** [raycast/extensions#15866]
### Extension

https://www.raycast.com/marckohlbrugge/wip

### Raycast Version

1.87.5

### macOS Version

15.1.1

### Description

when i try to submit a to-do with an image copied from my clipboard, it does not let me submit and reads "Unprocessable entity"

<img width="631" alt="image" src="https://github.com/user-attachments/assets/cfdea68a-ff55-441b-8a9e-e54da4eeb0a9" />

### Steps To Reproduce

1. take screenshot with mac native function (only portion of the screen)

2. option + space (to open Raycast)

3. search for WIP, and click "Add Completed To-do"

4. paste image (image gets added on files)

5. Type my to-do

6. Cmd + Enter (to submit To do)

7. get "Unprocessable entity" error

### Current Behaviour

I get the "unprocessable entity' error when trying to submit a todo with an image

### Expected Behaviour

to-do with image gets submitted to WIP

**Comment by marckohlbrugge** [comment]
Thank you for the report. I've fixed the issue. Once the Raycast team approves the fix, uploading copy/pasted images should work again.
