### ISSUE TITLE
Results not show all gists

### ISSUE THREAD

**Issue by 6ui11em** [raycast/extensions#1586]
# Extension Github Gist – [Title](https://github.com/raycast/extensions/tree/main/extensions/github-gist/)
Author: @koinzhang

When I search for a gist show results for the newer gists, older gist are not showed. Maybe there are a limit? 

If I do the same search with https://github.com/Gisto/Gisto I get all results.

**Comment by 6ui11em** [comment]
Hi @koinzhang,
Thank you for the replay.
The problem it is not about the limit of displayed results. The problem is that seems the search is not performed over all the gists. For exemple:

Search: laravel
Restult: 2 gists

But I know that I have older gists that are not shown in the results.

**Comment by koinzhang** [comment]
Hi @6ui11em. I understand what you mean.
The mechanism of how this command works is to show you 30 gist and then search through those 30 gist.
If it is not shown, it will not be searched.

Next version I'll add a new setting item that lets you choose the maximum number(30-100)  of gist you can show at a time.
And allow you to load the next page of Gist when the last Gitst is selected.

**Comment by 6ui11em** [comment]
Hi @koinzhang ,
This will be a great upgrade!
Thank you!

**Comment by koinzhang** [comment]
Hi @6ui11em 
[Github Gist](https://www.raycast.com/koinzhang/github-gist) update has been released with the following new features:

- Update Preference options: you can choose the number(30-100) of Gist loaded per page.
- Add “Load More”: When you select the last item in the list, the next page of Gist will be loaded automatically.
- Add “Open in Ray.so” action: Create beautiful images of your gist code using ray.so.
