### ISSUE TITLE
[Netlify] Increase Number of Sites Shown

### ISSUE THREAD

**Issue by alexschcom** [raycast/extensions#15860]
### Extension

https://www.raycast.com/netlify/netlify

### Description

Currently, the number of sites returned when using the **Search Sites** command is capped at 30.

I'd prefer to have a more exhaustive list -- the [official docs](https://docs.netlify.com/api/get-started/#pagination) say the upper limit per page is 100.

I assume the reason for the current limit is loading speed. However, most people probably don't have many sites anyway, so increasing the limit wouldn't cause a noticeable difference, while those of us who do have many sites would probably prefer being able to see as many sites as possible over having to wait just a little less. I think a setting might be a good solution here.

Cheers :)

**Comment by xmok** [comment]
Makes complete sense to me but for consistency, it's probably best to go with Raycast's own native pagination rather than set the limit to 100 as we might need to add it for more commands in the future.

@raycastbot assign me
