### ISSUE TITLE
[Weather] Extension no longer works if the API end point reaches the daily quota on views

### ISSUE THREAD

**Issue by andreaselia** [raycast/extensions#1587]
# Extension – [Weather](https://github.com/raycast/extensions/tree/main/extensions/weather)

Author: @tonka3000

## Description

Opening the extension in development mode shows that the API endpoint is returning a 503. Upon visiting the endpoint in my browser, I see text stating "Sorry, we are running out of queries to the weather service at the moment.".

## Steps To Reproduce

1. Open the extension
2. It doesn't work or show the weather

## The current behavior

The extension doesn't display the weather.

## The expected behavior

The extension displays the weather.

### Raycast version

Version: 1.34.0

**Comment by tonka3000** [comment]
Hi @andreaselia ,

The extension use the wttr.in API. So if they are down the extension is it as well. wttr.in is typically back in a couple of hours.

Greetings
Michael

**Comment by andreaselia** [comment]
Hey @tonka3000 👋 

I think it might be worth adding a message to the extension if the API fails to return a valid/expected response. Making use of the available [ListView.Empty](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) would do the job.

Another idea would be to have a secondary API that can be a fallback if the other fails, but I think the above might be a simpler solution.

**Comment by tonka3000** [comment]
@andreaselia #1592

**Comment by tonka3000** [comment]
@andreaselia #1614 adds a new weather extension based on OpenWeatherMap.
