### ISSUE TITLE
Spotify "no healthy upstream"

### ISSUE THREAD

**Issue by dingemann** [raycast/extensions#15886]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.87.5

### macOS Version

15.1.1

### Description

I am supposed to authenticate with spotify again. I get the error "no healthy upstream" though. 
I reinstalled the extension.

### Steps To Reproduce

1. use any function of spotify player extension
2. <img width="339" alt="Bildschirmfoto 2024-12-16 um 09 42 53" src="https://github.com/user-attachments/assets/b1cef6a7-073d-4781-8b0a-2d7963466afc" />
3. "no healthy upstream" error in browser

**Comment by thomaspaulmann** [comment]
Mmh... Not sure if this is something on our end. There is a veeeeery old post on reddit about a similar issue: https://www.reddit.com/r/spotify/comments/gz9zlm/no_healthy_upstream/

**Comment by dingemann** [comment]
Okay cheers. It seemed to have been something temporary. It's working again. Let's close this issue.
