### ISSUE TITLE
[Music] "Currently Playing Track" keeps Music open permanently

### ISSUE THREAD

**Issue by alexschcom** [raycast/extensions#15898]
### Extension

https://www.raycast.com/fedevitaledev/music

### Raycast Version

1.88.1

### Description

The latest commit to make the **Currently Playing Track** command inline (4b599bddf4c532f548dd88bb929761fc9a9b4581) auto-launches Apple Music continually in the background to get the track info. Since the command is useless without the "Background Refresh" setting enabled, this means if the user wants to use this command, they have to live with Apple Music always being open (even if they're not using it / want to quit it).

### Steps To Reproduce

1. Enable "Background Refresh" for the "Currently Playing Track" command
2. Observe Apple Music being opened in the background.

**Comment by michalzuch** [comment]
The fix has been merged. I hope you enjoy the update now! 🙌

@raycastbot close this issue
