### ISSUE TITLE
Timer freezes and doesn't get updated unless you click on it (video of the bug is attached)

### ISSUE THREAD

**Issue by andreisuslov** [raycast/extensions#15896]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Raycast Version

1.87.5

### macOS Version

14.7.1 (23 H 222)

### Description

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,3
  Model Number:	Z15G0021LLL/A
  Chip:	Apple M1 Pro
  Total Number of Cores:	8 (6 performance and 2 efficiency)
  Memory:	32 GB
  System Firmware Version:	11881.41.5
  OS Loader Version:	10151.140.19.700.2
  Serial Number (system):	PJ64RHH4XD
  Hardware UUID:	4044C659-7109-503F-8A33-93E2B752AEEB
  Provisioning UDID:	00006000-001438843ED8801E
  Activation Lock Status:	Disabled

https://github.com/user-attachments/assets/a5e11bea-b25e-4df7-8a1f-bb55250f9c5e

### Steps To Reproduce

Start the timer, observe the timer in the top menu bar.

### Current Behaviour

The timer doesn't get updated unless you click on it.

### Expected Behaviour

The timer's counting gets updated even if you don't click on it.

**Comment by mikikiv** [comment]
The timer in the menu bar updates about every 10 seconds by default; This is a limitation of Raycast. 
See https://github.com/raycast/extensions/issues/15244#issuecomment-2464654434 for more info

**Comment by LitoMore** [comment]
Closing as working expected.
