### ISSUE TITLE
[Unicode Symbols Search] Preference to make default action copy to clipboard

### ISSUE THREAD

**Issue by chriscalo** [raycast/extensions#15901]
### Extension

https://www.raycast.com/mmazzarolo/unicode-symbols

### Description

Today the Unicode Symbols Search offers two actions:
- paste to current application
- copy to clipboard

I'd love to have a **Primary action** preference that I can set to **Copy to Clipboard**.

A few reasons why:
- I've had issues with auto-paste not working everywhere
- This is also just not how my brain works: I tend to think of and search for the content I need to insert before my cursor is in the right place where I need to paste it
- I use a clipboard tool that keeps a history, which I can access even faster than Raycast the 2nd, 3rd, 4th time I need to copy and paste it

### Who will benefit from this feature?

Anyone who prefers copying content instead of having Raycast do the pasting.

### Anything else?

There's a precedent for this pattern in other extensions like Search Emoji & Symbols:

![Search Emoji & Symbols Preferences Screenshot](https://github.com/user-attachments/assets/0d02379e-3409-43da-b4e8-28e55dced974)

**Comment by j3lte** [comment]
@raycastbot assign me

**Comment by j3lte** [comment]
I have an update, unfortunately I am running into issues with pushing an update. I'll wait a little bit on #15909, if there isn't a solution soon I will make an old fashioned PR for this.

**Comment by j3lte** [comment]
Fix is here, waiting for it to be merged: #15915

**Comment by j3lte** [comment]
Fix is merged

@raycastbot close this issue

**Comment by chriscalo** [comment]
thank you! 🙏🏼
