### ISSUE TITLE
[HowLongToBeat] ...Could not perform search. Error: request failed with status code 404

### ISSUE THREAD

**Issue by turfandam** [raycast/extensions#15914]
### Extension

https://www.raycast.com/Cronos87/howlongtobeat

### Raycast Version

1.88.3

### macOS Version

15.2

### Description

When I try to use the howlongtobeat extension by searching, I directly receive this message. I saw that it is updated recently to correct this error, but now working still. I updated the extension, didn't work. Then I uninstalled the extension and reinstalled it, didn't work either.
![CleanShot 2024-12-17 at 18 50 36@2x](https://github.com/user-attachments/assets/363a70a9-52dc-4fd2-a051-e4afc8086e3c)

### Steps To Reproduce

1. Run Raycast.
2. Run Howlongtobeat extension.
3. Try to search anything.

### Current Behaviour

When searching, it does not work and gives the error message.

### Expected Behaviour

When I search, it should work normally.

**Comment by whitespacecode** [comment]
@turfandam 
I don't think the fix that @ridemountainpig provided is published yet.
When i fork the code i don't see his changes

**Comment by turfandam** [comment]
@whitespacecode thanks, I thought the issue #15415 was resolved and closed. In this case, we'll still wait right?
