### ISSUE TITLE
[Music] ... Opens Apple Music without commands in macOS 15.2

### ISSUE THREAD

**Issue by andrewmglaser** [raycast/extensions#15920]
### Extension

https://www.raycast.com/fedevitaledev/music

### Raycast Version

1.88.3

### macOS Version

15.2

### Description

I noticed Apple Music was consistently open after upgrading to macOS 15.2 and isolated to the Raycast Apple Music extension. 

### Steps To Reproduce

1. Enable Music extension in Raycast
2. Apple Music opens after some interval, even if there were no commands issued in Raycast.

### Current Behaviour

If this extension is enabled Apple Music will open if closed, even if there are no commands from Raycast. Seems like it's a prerequiste of the extension. 

### Expected Behaviour

If Apple Music must be active to use this extensions, it should be included in the Read Me or description.

**Comment by michalzuch** [comment]
Hey @andrewmglaser 🙌
This behavior was not planned, the fix is already waiting for review #15846

**Comment by andrewmglaser** [comment]
Apologies, should've read through open issues.

**Comment by michalzuch** [comment]
Don't worry, hope you will like it once the update is merged 😄

**Comment by michalzuch** [comment]
Don't worry, hope you will like it once the fix is merged 😄

**Comment by michalzuch** [comment]
The fix has been merged. I hope you like the update now 🙌

@raycastbot close this issue

**Comment by michalzuch** [comment]
The fix has been merged. I hope you enjoy the update now! 🙌

@raycastbot close this issue
