### ISSUE TITLE
[Summarize Youtube Video with AI]Summarize a specific chapter or time stamp range

### ISSUE THREAD

**Issue by sbroways** [raycast/extensions#15922]
### Extension

https://www.raycast.com/iKasch/summarize-youtube-video-with-ai

### Description

I have summarize a couple of videos, but i think because they're so long it's a little too high level. It would be nice to have a way to dig in on a specific area of the video and get more details. 

### Who will benefit from this feature?

Everyone using the plugin

**Comment by iKasch** [comment]
Thanks for the report! I'm currently working on a way to ask questions after the summary. I have not tried with very long and detailed videos but so far it works quite nice. Would this help already?

I attached a quick example.

https://github.com/user-attachments/assets/6c09e95b-8c34-483e-bb90-73a37f8a7243

**Comment by iKasch** [comment]
@raycastbot assign me

**Comment by sbroways** [comment]
I'll give this a try! Thanks!!

**Comment by iKasch** [comment]
@sbroways Update should be out now :) Hope you like it.
https://github.com/raycast/extensions/pull/15972

@raycastbot close this issue
