### ISSUE TITLE
[Change Case] ... hola

### ISSUE THREAD

**Issue by echuc** [raycast/extensions#1593]
# Extension – [Change Case](https://github.com/raycast/extensions/tree/a0c62af506694a97060f53530dd6291dbeb8244d/extensions/change-case/)
Author:

**Describe the feature and the current behavior/state.**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by pernielsentikaer** [comment]
Hi @echuc 👋 

What is this covering?
