### ISSUE TITLE
[Pomodoro] Add daily and weekly statistics views

### ISSUE THREAD

**Issue by luopeixiang** [raycast/extensions#15950]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

Currently, the Pomodoro extension only shows all-time statistics, which makes it difficult to track daily progress and recent productivity patterns. I would like to propose adding two new statistics views:

1. Today's Statistics:
   - Number of completed pomodoros today
   - Total focus time today
   - Back to back pomodoro cycles today

2. Last 7 Days Statistics:
   - Daily breakdown of completed pomodoros
   - Daily focus time  
   - Daily back to back cycles
   - Simple trend visualization

### Who will benefit from this feature?

1. Users who want to monitor their daily productivity and maintain consistent work patterns
2. Knowledge workers who need to track their daily focus time for reporting or self-improvement
3. Students who want to ensure they maintain regular study habits
4. Anyone using the Pomodoro technique who wants to optimize their daily and weekly productivity patterns

### Anything else?

Benefits of this enhancement:
- Helps users set and achieve daily focus goals
- Provides better motivation through shorter-term progress visibility 
- Enables users to identify patterns in their productivity (e.g., which days are most productive)

Similar implementations can be found in other popular Pomodoro apps.

**Comment by LitoMore** [comment]
We already have this feature:

<img width="1112" alt="image" src="https://github.com/user-attachments/assets/926461df-0516-4a30-b6d6-1415d9cf8b5d" />
