### ISSUE TITLE
[1Password] Password shortcut

### ISSUE THREAD

**Issue by haberdashPI** [raycast/extensions#15973]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

The copy password action uses one of the most akward shortcut combinations (⌥⌘C) but is one of the most common things one would like to do.

Can this extension add the option to either change shortcuts for actions or use a more ergonomic shortcut for this command (maybe just ⌘C).

### Who will benefit from this feature?

Those use the 1password extension

**Comment by Luk4h** [comment]
Hey @hasantezcan,
That shortcut combination is for in-menu actions. By default, you are able to copy a password using a simple return (⏎.) These are the ones we call "Primary action" `return`(⏎) and "Secondary action" `cmd + return`(⌘ + ⏎). They are both customizable in the extension settings. I will close this issue, even if these actions do not suit you, a.k.a. you have already set them to something more important than copying the password. You should create an issue asking for the options to customize the hotkeys.
 @raycastbot close this issue

**Comment by hasantezcan** [comment]
Thats not me 😅

**Comment by Luk4h** [comment]
My apologies!!!
