### ISSUE TITLE
Calculator query API access

### ISSUE THREAD

**Issue by sataset** [raycast/extensions#1599]
My idea is basically to implement a note taking in format of [numi.app](https://numi.app). In order to do so I wanted to use Calculator query API that is built-in to Raycast.

https://user-images.githubusercontent.com/28687456/166933607-007136df-2012-42fc-9557-a7f122da403b.mp4

**Describe the feature and the current behavior/state.**
As far as I understand from API doc it is not available.

**Will this change the current API? How?**
Yes.

**Who will benefit from this feature?**
Extension developers could benefit from integrating Calculator API.

**Comment by peduarte** [comment]
As of Raycast 1.45 any command can be set as Fallback Command. Hope this solves your issue, thanks!

**Comment by jerzygangi** [comment]
@peduarte I noticed you closed this issue. How can the calculator query API be used by extension authors, as @sataset was originally asking?
