### ISSUE TITLE
[Google Drive] Show selected file/folder in Finder.

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#1601]
# Extension – [Google Drive](https://github.com/raycast/extensions/tree/c16500d6b24f04f742bc38069c078d7bfec54378/extensions/google-drive/)
Author:

I'd love an option to show the file/folder searched in Finder. It would also be great to pick the default action to be performed in settings.

**Comment by influencebydesign** [comment]
I'd still like to see this feature added
