### ISSUE TITLE
[Google Chrome] search history  and search bookmarks failed

### ISSUE THREAD

**Issue by aqianchu** [raycast/extensions#16036]
### Extension

https://www.raycast.com/Codely/google-chrome

### Raycast Version

1.88.4

### macOS Version

15.2 24C101

### Description

![image](https://github.com/user-attachments/assets/205ca8d1-b403-42d3-8b22-470e7f394bcb)
![image](https://github.com/user-attachments/assets/8ea090af-7f27-4cd6-a601-62c94b6d437c)

I can't search history, I have given full disk access, but I still can't use search history and search bookmarks.
![image](https://github.com/user-attachments/assets/38ffe6cd-c2ab-4b86-8b67-4a2064492453)

### Steps To Reproduce

raycast 1.88.4, macOs: 15.2

### Expected Behaviour

I can use search bookmarks and search history.

**Comment by a-laughlin** [comment]
Are you using more than one profile?
Adam

Sent via mobile.
