### ISSUE TITLE
[Notion] – Include required integration capabilities in documentation

### ISSUE THREAD

**Issue by MystaMax** [raycast/extensions#1604]
# Extension – [Notion](https://github.com/raycast/extensions/tree/9553ddbaad4d6d4bcfd9bdb124b1574734a2c4ed/extensions/notion/)
Author: @mathieudutour

## Description

🙏🏾 Apologies. This isn't a bug, per se. It wasn't clear if the "Documentation Issue" type refers to just Raycast documentation or the entire Raycast ecosystem documentation, such as the README mentioned below.

While following the [README.md for the Notion extension](https://github.com/raycast/extensions/blob/main/extensions/notion/README.md), it does not mention what capabilities are required for the extension to work. The choices are:

**Content Capabilities**

- [ ] Read content
- [ ] Update content
- [ ] Insert Content

**User Capabilities**
- [ ] No user information
- [ ] Read user information without email addresses 
- [ ] Read user information including email addresses

It'd be nice if the README mentioned what was required, for clarity. 

Considering this extension can create database items, The read content and insert content capabilities are most likely required. Does this extension require any user capabilities?

I'm assuming the Integration type option provides some security around the extension, since it'll only be available within my workspace.

## Steps To Reproduce

1. Follow the [README](https://github.com/raycast/extensions/blob/main/extensions/notion/README.md)
2. After selecting the Notion workspace, there is a list of capabilities that are needed.
    ![screenshot-20220505T121542](https://user-images.githubusercontent.com/687718/166967327-ec58ce31-05d8-41bd-87e0-eb90f86759c2.png)

## The current behavior

The documentation doesn't recommend the required capabilities.

## The expected behavior

The documentation should recommend the required capabilities.

### Raycast version

Raycast 1.34.1

**Comment by mathieudutour** [comment]
The extension doesn't need any user capabilities but it does require all the content capabilities indeed. Feel free to open a PR with the info!

**Comment by mathieudutour** [comment]
now that it uses oauth, it's a lot simpler
