### ISSUE TITLE
[Brand Icons - simpleicons.org] Icons not loading

### ISSUE THREAD

**Issue by theSaviKing** [raycast/extensions#16048]
### Extension

https://www.raycast.com/litomore/simple-icons

### Raycast Version

1.88.4

### macOS Version

15.1.1

### Description

The Brand Icons extension no longer loads any icons when I access it. It shows a loading indicator, but after up to 5 minutes of waiting, nothing loads and I can't access any of the icons I could access before.

### Steps To Reproduce

1. Download "Brand Icons" extension from Simple Icons.
2. Activate extension
3. Loading indicator will show, but no icons will load.

### Current Behaviour

Icons do not load when extension is opened.

### Expected Behaviour

Extension should load icons when opened.

**Comment by LitoMore** [comment]
I already have a PR #15994 to fix it, but the Raycast team is on vocation.

I've tried contacting them directly on Slack, but no response.

Let's wait.
