### ISSUE TITLE
[Visual Studio Code Recent Projects] ...

### ISSUE THREAD

**Issue by Yug-Sahu** [raycast/extensions#1615]
# Extension – [Visual Studio Code Recent Projects](https://github.com/raycast/extensions/tree/5fad3eeb634eb9a5a3493fe9c0cebe036a5291a1/extensions/visual-studio-code-recent-projects/)
Author:

## Description
I cannot see my recent Visual Studio code projects. I get the following error but I cannot see the entire error : 
Failed to load recent projects
ENOENT: no such file or directory. Open 'Users/{User}/Library/Application Support...

![image](https://user-images.githubusercontent.com/104753308/167180171-fe883e05-5922-4e7e-9120-fef5e7763679.jpeg)

## Steps To Reproduce

1. The error shows when using the extension.

## The current behavior
Does not load and show the recent projects. 

## The expected behavior
Show the recent projects. 

### Raycast version
1.34.1

**Comment by KevinBatdorf** [comment]
I'm experiencing the same behavior starting yesterday morning (so about 30 hours ago)

**Comment by cy-98** [comment]
#1630

**Comment by cy-98** [comment]
resolved, and new version published.
