### ISSUE TITLE
[Jira] Would be nice to have a parent task link in the detail view of a task

### ISSUE THREAD

**Issue by pulchritude-laboratory** [raycast/extensions#1643]
# Extension – [Jira](https://github.com/raycast/native-extensions/tree/98807c71c6ec589775952a250d7225b403e995f5/extensions/jira/)

Would be nice to have a parent task link in the detail view of a task.

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/75523509/167595009-950486e2-5d9e-4cce-a96d-be53c3323040.png">

**Who will benefit with this feature?**
Most of the times we have a story with a large description block and subtasks without any descriptions.
The add-on would be more useful if we could jump from the subtask to the parent.

**Comment by trentwatt** [comment]
and also to be able to create a task with a parent task?
