### ISSUE TITLE
[Apple Notes] Duplicate items with smart folders

### ISSUE THREAD

**Issue by jimbytes** [raycast/extensions#1652]
# Extension – [Apple Notes](https://github.com/raycast/extensions/tree/main/extensions/apple-notes)

Author: @tumispro

## Description
The extension shows a number of duplicate items in the result pane. When using smart folders, the extension seems to search within folders and smart folders, generating many duplicates. 

## Steps To Reproduce

1. Create a "Linux" folder within Apple Notes. 
2. Inside, "Linux" folder, create a note "Installation" as title and add random text.
3. Assign tag "#ubuntu" and "#alpine" to the note.
4. Create a smart folder for ubuntu tag and another one for alpine tag.
5. Let time to update.
6. Search in raycast "installation", you should have three items for the same note.  

## The current behavior
The extension search within folders and smart folders that generate duplicate items in the result for the same physical note.

## The expected behavior
I think the extension should not index smart folders. They are already indexed whithin folders.

### Raycast version

Version: 1.34.1

**Comment by tumispro** [comment]
Thanks for the extensive report. I will look into is asap 👌

**Comment by tumispro** [comment]
I've quickly looked into the possibilities and it seems that the type of the folder isn't accessible by script. Notes do have a unique ID however, so I could check on that to prevent showing duplicates. The downside then is that when the folder field is shown it might in some cases show the (first) smart folder instead of the regular folder. What do you think?

**Comment by tumispro** [comment]
I have a PR ready for de-duplicating :) 

https://github.com/raycast/extensions/pull/1662

**Comment by tumispro** [comment]
Woah, already merged 🔥
