### ISSUE TITLE
[Visual Studio Code Recent Projects] could not open file/folder in vscode which contains a " " in directory path

### ISSUE THREAD

**Issue by githubmin** [raycast/extensions#1661]
# Extension – [Visual Studio Code Recent Projects](https://github.com/raycast/extensions/tree/3019509c5017168e4984dee77e678647b833a3c0/extensions/visual-studio-code-recent-projects/)

Author:

@cy-98 

## Description

File/folder which contains a space(" ") in directory path could not be opened with vscode

![image](https://user-images.githubusercontent.com/207617/167785947-1e6719b2-93ad-4dfd-8bcb-ed9e71b1ff3d.png)

## Steps To Reproduce

1. try to open a folder/file which under "~/Library/Application Support/" directory.
2. could not opened by vscode.

## The current behavior

not opened by vscode. nothing happened after Enter tapped.

I also tried "Open With..." action from Raycast menu, then select "VSCode", this is working correctly even under "~/Library/Application Support/" path.

## The expected behavior

should opened by vscode.

### Raycast version

Version:

1.34.1

**Comment by yug2005** [comment]
I also have this issue

**Comment by immint023** [comment]
Hi @githubmin @yug2005 , I tried and re-produced the error successfully. I am trying to fix it and create PR later.

**Comment by yug2005** [comment]
Would you need to add "" around the shell command?
