### ISSUE TITLE
How to get 2000 * 1250 size screenshoots for extension ?

### ISSUE THREAD

**Issue by cy-98** [raycast/extensions#1666]
I want publish a new extension, but i can't get the 2000 * 1250 screenshots exactly.

**Comment by maxfahl** [comment]
I followed their guide and used their Figma template: https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots

Also, make sure to have text size set to medium in Settings > Appearance.

**Comment by kudrykv** [comment]
Make sure you take the screenshot on the retina screen. If you take a screenshot on an external monitor, it will have a lower resolution.

Not sure what resolution iMac has.

**Comment by koinzhang** [comment]
Hi @cy-98 
You can try the [Capture Raycast Metadata](https://www.raycast.com/koinzhang/capture-raycast-metadata) extension.

**Comment by kudrykv** [comment]
@demartini I've tried running the command myself, and in my output, I'm seeing `Resolution: 3024 x 1964 Retina`. I'm not seeing `Retina` anywhere with your output. Do you have a retina screen?

I don't think Raycast developers implemented screenshotting from other screen types 😔

**Comment by demartini** [comment]
Hi @kudrykv, thanks for the quick reply.

My built-in display is not `Retina`, but I was able to generate the correct resolutions by changing my external monitor's resolution to `1920x1080`.

**Comment by maxfahl** [comment]
> I have the same problem, I already tried using both tools:
> 
> 
> 
> - Window Capture
> 
> - Capture Raycast Metadata
> 
> 
> 
> And the images are still at **1000x625** resolution.
> 
> 
> 
> Here is my output of `/usr/sbin/system_profiler SPDisplaysDataType`:
> 
> 
> 
> ```log
> 
> Graphics/Displays:
> 
> 
> 
>     Intel HD Graphics 6000:
> 
> 
> 
>       Chipset Model: Intel HD Graphics 6000
> 
>       Type: GPU
> 
>       Bus: Built-In
> 
>       VRAM (Dynamic, Max): 1536 MB
> 
>       Vendor: Intel
> 
>       Device ID: 0x1626
> 
>       Revision ID: 0x0009
> 
>       Metal Family: Supported, Metal GPUFamily macOS 1
> 
>       Displays:
> 
>         Color LCD:
> 
>           Display Type: LCD
> 
>           Resolution: 1440 x 900 (Widescreen eXtended Graphics Array Plus)
> 
>           UI Looks like: 1440 x 900
> 
>           Framebuffer Depth: 24-Bit Color (ARGB8888)
> 
>           Mirror: Off
> 
>           Online: Yes
> 
>           Automatically Adjust Brightness: Yes
> 
>           Connection Type: Internal
> 
>         U28E590:
> 
>           Resolution: 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition)
> 
>           UI Looks like: 3840 x 2160 @ 60.00Hz
> 
>           Framebuffer Depth: 24-Bit Color (ARGB8888)
> 
>           Display Serial Number: HXAJ400067
> 
>           Main Display: Yes
> 
>           Mirror: Off
> 
>           Online: Yes
> 
>           Rotation: Supported
> 
>           Connection Type: Thunderbolt/DisplayPort
> 
> ```

Did you take the screenshot on your Retina display? Seems you didn't.
