### ISSUE TITLE
[Google Drive] Make extension available as fallback command

### ISSUE THREAD

**Issue by robertvanhoesel** [raycast/extensions#1668]
# Extension – [Google Drive](https://github.com/raycast/extensions/tree/11e73c6d841aa409d5dd6c0342de63cde1dc1290/extensions/google-drive/)
Author: @vishaltelangre

**Describe the feature and the current behavior/state.**
Currently the extension is not available as to be configured as fallback command, even though supposedly with just one command it should be. https://raycastapp.notion.site/Fallback-Commands-11c8bb2bee484daabcdbdaeb14754d92

**Who will benefit with this feature?**
Anyone just typing a file name or query and then wanting to select 'Search Files' with the Google Drive extension

**Comment by vishaltelangre** [comment]
@pernielsentikaer Is there a configuration or an API to allow this? I couldn't find one.

**Comment by lukasoppermann** [comment]
I would also love this feature. Would be awesome for emoji finding as well.

**Comment by pernielsentikaer** [comment]
No that's unfortunately not possible at the moment but it's something that we have on our list 🙂
