### ISSUE TITLE
[Figma File Search] Crash when opening the search command

### ISSUE THREAD

**Issue by knandraina** [raycast/extensions#1670]
# Extension – [Figma File Search](https://github.com/raycast/extensions/tree/1da89c4626dd39b3c50a12208ee14c816f918ae8/extensions/figma-files/)
Author: @michaelwschultz

## Description

Occurring on my end and happening to #1732 as well.

Sometime within the last 3 days (for me), the Figma File Search extension stopped working. Opening the extension option yields an error. The logs (pasted below) seem to indicate an issue with the Team ID. My Team ID hasn't changed, but I cleared it and pasted it in again, which did not work. 

```
TypeError: Cannot read properties of undefined (reading 'filter')

os:index.js:17:1403

---
14: 
15:   Update the value for <TEAM_ID> in Raycast Preferences > Extensions > Figma...  
16:   then reopen the command.
17:   `})}var _e=require("@raycast/api");var un=require("react");function ns(){let[t,r]=(0,un.useState)({projectFiles:void 0,isLoading:!0,hasError:!1});return(0,un.useEffect)(()=>{async function o(){let a=await wu();a&&r(u=>yr(br({},u),{projectFiles:a}));try{let u=await Vd();r(l=>yr(br({},l),{projectFiles:u,isLoading:!1,hasError:!1})),await Su(u)}catch(u){console.error("error fetching files",u),u?.status>=400&&r(l=>yr(br({},l),{isLoading:!1,hasError:!0}))}}o()},[]),t}async function Ud(){let{PERSONAL_ACCESS_TOKEN:t,TEAM_ID:r}=(0,_e.getPreferenceValues)();try{let o=await Ye(`https://api.figma.com/v1/teams/${r}/projects`,{method:"GET",headers:{"Content-Type":"application/json","X-Figma-Token":t}});return o.ok?await o.json():Promise.reject(o)}catch(o){return console.error(o),(0,_e.showToast)(_e.ToastStyle.Failure,"Could not load team"),Promise.resolve({name:"No team found",projects:[]})}}async function Vd(){let{PERSONAL_ACCESS_TOKEN:t}=(0,_e.getPreferenceValues)(),o=(await Ud()).projects.map(async a=>{try{let l=await(await Ye(`https://api.figma.com/v1/projects/${a.id}/files`,{method:"GET",headers:{"Content-Type":"application/json","X-Figma-Token":t}})).json();return{name:a.name,files:l.files}}catch(u){return console.error(u),(0,_e.showToast)(_e.ToastStyle.Failure,"Could not load files"),Promise.resolve([])}});return Promise.all(o)}function os(){let{projectFiles:t,isLoading:r,hasError:o}=ns(),{files:a,visitFile:u,isLoading:l}=Cu(),m=r||l;return o?_jsx(rs,null):_jsx(sn.List,{isLoading:m,searchBarPlaceholder:"Filter files by name..."},_jsx(sn.List.Section,{key:"recent-files",title:"Recent Files"},a?.map(d=>_jsx(an,{key:d.key+"-recent-file",file:d,extraKey:d.key+"-recent-file-item",onVisit:u}))),!l&&t?.map(d=>_jsx(sn.List.Section,{key:d.name+"-project",title:d.name},d.files.filter(p=>a?.find(_=>p.key===_.key)===void 0).map(p=>_jsx(an,{key:p.key+"-file",file:p,onVisit:u})))))}module.exports=Ml(Hd);0&&(module.exports={});
18: 
---

Dr:index.js:24:2463
    at ray-navigation-stack
bo:index.js:24:2091
wo:index.js:23:619
    at ray-root
pa:index.js:24:2832
```

## Steps To Reproduce

1. Open Raycast
2. Open "Search Files (Figma)" Raycast option
3. See Error - "Something went wrong. You can try reloading, or report the error to the extension developer, by
copying the log from the Action Panel"

## The current behavior

<img width="774" alt="Capture d’écran 2022-05-11 à 21 32 33" src="https://user-images.githubusercontent.com/13239324/167930966-53d624b4-062f-4c5b-afc8-d8614ab660e1.png">

### Raycast version
Version: 1.34.1

**Comment by michaelwschultz** [comment]
@knandraina we need some more info on what exactly happened. Do you mind adding a description of what happened or instructions on how to reproduce this error? Is this your first time using the extension?

**Comment by michaelwschultz** [comment]
@kidpix thanks for reporting. I'm on it!

**Comment by remus-b** [comment]
I'm also having issues using this Extension. 
This is what Copy error gives me 👇 
`TypeError: Cannot read properties of undefined (reading 'filter')

os:index.js:17:1403

---
14: 
15:   Update the value for <TEAM_ID> in Raycast Preferences > Extensions > Figma...  
16:   then reopen the command.
17:   `})}var _e=require("@raycast/api");var un=require("react");function ns(){let[t,r]=(0,un.useState)({projectFiles:void 0,isLoading:!0,hasError:!1});return(0,un.useEffect)(()=>{async function o(){let a=await wu();a&&r(u=>yr(br({},u),{projectFiles:a}));try{let u=await Vd();r(l=>yr(br({},l),{projectFiles:u,isLoading:!1,hasError:!1})),await Su(u)}catch(u){console.error("error fetching files",u),u?.status>=400&&r(l=>yr(br({},l),{isLoading:!1,hasError:!0}))}}o()},[]),t}async function Ud(){let{PERSONAL_ACCESS_TOKEN:t,TEAM_ID:r}=(0,_e.getPreferenceValues)();try{let o=await Ye(`https://api.figma.com/v1/teams/${r}/projects`,{method:"GET",headers:{"Content-Type":"application/json","X-Figma-Token":t}});return o.ok?await o.json():Promise.reject(o)}catch(o){return console.error(o),(0,_e.showToast)(_e.ToastStyle.Failure,"Could not load team"),Promise.resolve({name:"No team found",projects:[]})}}async function Vd(){let{PERSONAL_ACCESS_TOKEN:t}=(0,_e.getPreferenceValues)(),o=(await Ud()).projects.map(async a=>{try{let l=await(await Ye(`https://api.figma.com/v1/projects/${a.id}/files`,{method:"GET",headers:{"Content-Type":"application/json","X-Figma-Token":t}})).json();return{name:a.name,files:l.files}}catch(u){return console.error(u),(0,_e.showToast)(_e.ToastStyle.Failure,"Could not load files"),Promise.resolve([])}});return Promise.all(o)}function os(){let{projectFiles:t,isLoading:r,hasError:o}=ns(),{files:a,visitFile:u,isLoading:l}=Cu(),m=r||l;return o?_jsx(rs,null):_jsx(sn.List,{isLoading:m,searchBarPlaceholder:"Filter files by name..."},_jsx(sn.List.Section,{key:"recent-files",title:"Recent Files"},a?.map(d=>_jsx(an,{key:d.key+"-recent-file",file:d,extraKey:d.key+"-recent-file-item",onVisit:u}))),!l&&t?.map(d=>_jsx(sn.List.Section,{key:d.name+"-project",title:d.name},d.files.filter(p=>a?.find(_=>p.key===_.key)===void 0).map(p=>_jsx(an,{key:p.key+"-file",file:p,onVisit:u})))))}module.exports=Ml(Hd);0&&(module.exports={});
18: 
---

Ut:index.js:5:2458
    at ray-navigation-stack
Cr:index.js:5:2088
    at Suspense
wr:index.js:4:714
    at ray-root
vi:index.js:5:2867`

**Comment by remus-b** [comment]
I uninstalled the extension and installed back and now looks like things work again.
