### ISSUE TITLE
JetBrains toolbox still not working to search projects 

### ISSUE THREAD

**Issue by aprice42** [raycast/extensions#1672]
# Extension – [JetBrains](https://github.com/raycast/extensions/tree/main/extensions/jetbrains/*)

Author: @gdsmith 

## Description
This is my last hold out for fully adopting Raycast into my personal workflow. I have tried following advice on all issues that I could find in the issue queue but I cannot get past the error: 

```
There was a problem finding the JetBrains shell scripts We were unable to find shell scripts, ensure you have the Generate Shell scripts option checked in JetBrains Toolbox under Settings. If you have set a custom path for your shell scripts, that can set that in the settings for this extension, this is currently set to  /usr/local/bin . You can also enable the extension preference to fallback to protocol url, though that is a less reliable method of opening projects.
```

- I use only PHPStorm and have it installed via JetBrains Toolbox 
- I have the shell scripts path set and it is correct
- I have the path for the tools install location correct (confirmed with method from another issue)

The only thing I can gather is that I installed PHPStorm outside of the toolbox at one point, and maybe there are leftover configs or something from that install that are getting in the way? Any ideas would be greatly appreciated. 

## Steps To Reproduce

1. Add the extension
2. Follow steps to configure
3. Turn off Generate Shell Scripts, and then back on to try to fix
4. Click on PHPStorm in finder and confirm location in the finder is the same as the tools install location

## The current behavior
Displays the message noted above

## The expected behavior
It should search my PHPStorm projects 🙏

### Raycast version

Version: 1.34.1

**Comment by afboteroz** [comment]
The same happen to me with intellij ultimate, i was checking it with @gdsmith, i had too installed previously intellij as standalone  ( not with toolbox ) maybe is like @aprice42 says, and there's some old config affecting the happy path?

**Comment by gdsmith** [comment]
I think this is fixed now if you can confirm @aprice42?

**Comment by aprice42** [comment]
@gdsmith still getting that same error, was there an update on either end that might have resolved this that I might have missed? I am running tool box app version: `JetBrains Toolbox 1.24.12080, macOS 12.2.1` and using Raycast v. 1.36.0

**Comment by gdsmith** [comment]
@aprice42 there's a brand new version out today will hopefully provide an error message if things are going wrong in the loading of the history files. Any change you can please check again?

**Comment by aprice42** [comment]
Thanks for the update! I upgraded to 1.36.1 and still no luck 


> There was a problem finding the JetBrains shell scripts We were unable to find shell scripts, ensure you have the Generate Shell scripts option checked in JetBrains Toolbox under Settings. If you have set a custom path for your shell scripts, that can set that in the settings for this extension, this is currently set to  /usr/local/bin . You can also enable the extension preference to fallback to protocol url, though that is a less reliable method of opening projects.


I tried toggling the `enable shell scripts` option of and then on in JetBrains toolbox and still no change. Any other troubleshooting steps you would suggest? 

FWIW using the `protocol URLs` option is working ok for me (just has issues finding a project if I change its name in PHPstorm).

**Comment by aprice42** [comment]
Thanks for getting back to me! I found the issue!

My PHPStorm shell script was renamed to `pstorm` not `phpstorm` changing it back to the default fixed the issue. 

Wonder if the plugin could be updated to check for an override like that?

**Comment by gdsmith** [comment]
@aprice42 do you know if shell_script_name the `.history.json` file was pointing to was correct? If it was pointing to `pstorm` then everything _should_ have worked and I'll have to do some more digging. If not, then I don't think I can check for overrides of individual scripts if they are not being reported correctly, but I _can_ add some extra troubleshooting tips in the error output. Would the addition here have helped you diagnose things?

> # There was a problem finding the JetBrains shell scripts
>
>  We were unable to find shell scripts, ensure you have the Generate Shell scripts option checked in JetBrains Toolbox under Settings.  If you have set a custom path for your shell scripts, that can set that in the settings for this extension, this is currently set to  `/usr/local/bin`. The script we were unable to find was `phpstorm`, please check to see if that is available using `which phpstorm` from a Terminal window.
>
>  You can also enable the extension preference to fallback to protocol url, though that is a less reliable method of opening projects.
```

**Comment by aprice42** [comment]
@gdsmith it looks like it was not set correctly. The file updated timestamp is dated prior to the date that I made the change I meantioned above (not sure how to trigger it to update?). But at the time that file was updated last, my shell command was set to `pstorm` and as you can see here `.history.json` had it as `phpstorm`. 

![2022-06-21 at 12 45 30](https://user-images.githubusercontent.com/675820/174884964-1364e604-9fe0-46f2-af04-e9ffe4255328.png)

An addition about this in the readme would have definitely helped me!

One other note, though maybe not important... 
This directory `~/Library/Application Support/JetBrains/Toolbox/apps/PhpStorm/ch-0` doesn't have `.history.json` it is in `~/Library/Application Support/JetBrains/Toolbox/apps/PhpStorm/ch-1`
