### ISSUE TITLE
Extension – List Repos: sort by least recently used

### ISSUE THREAD

**Issue by LiranBri** [raycast/extensions#1676]
# Extension – [List Repos](https://github.com/raycast/extensions/tree/main/extensions/git-repos)

Author: @moored 

**Describe the feature and the current behavior/state.**
I suggest having a default sort by recently used repos.
it would improve the user experience significantly, as today there is a long list where most items are not relevant for the user while usually there are only a few that are actually in usage at a given time.
on Authy extension there is the same feature, and it works fantastic.

**Who will benefit from this feature?**
everyone

**Comment by LiranBri** [comment]
🙀

**Comment by moored** [comment]
I can definitely see the benefit and will take a look at it.
