### ISSUE TITLE
 [google-translate] Translation can't work

### ISSUE THREAD

**Issue by tisfeng** [raycast/extensions#1682]
# Extension – [google-translate](https://github.com/raycast/extensions/tree/cfd70e9c69ae7cd9685d4a8973ae3ce1e21de2ac/extensions/google-translate/)

Author: @ospfranco 

## Description

Input words, do not display the translation results, but always query.

I'm not sure if this is because I'm in China, where Google and other foreign services are usually blocked for well-known reasons, which is sad.

If yes, is there any solution? Does Raycast support proxy? We usually use proxy services such as socks5 in these blocked countries to bypass GFW censorship.

## The current behavior

<img width="810" alt="image" src="https://user-images.githubusercontent.com/25194972/168197010-66de5bb5-7327-47be-9a87-6974ff768031.png">

## The expected behavior

Hope it works correctly

### Raycast version

Version: 1.34.1

**Comment by ospfranco** [comment]
yes, requests in China fail, there is the possibility to use a proxy with the underlaying library, but it was not implemented. Whomever is in charge of the extensions nowadays (I gave up the ownership) can decide to take care of it.
