### ISSUE TITLE
[parrot-translate] Support to open the word query interface of Eudic after querying words

### ISSUE THREAD

**Issue by tisfeng** [raycast/extensions#1685]
# Extension – [parrot-translate](https://github.com/raycast/extensions/tree/7a3cde0b56f0af284f12f8dee6426e8d66cb8e7b/extensions/parrot-translate/)

Author: @Haojen 

**Describe the feature and the current behavior/state.**

Hope to provide a function, after the query of a word, can directly open the word query interface of the Eudic Dictionary, and it would be better if it could be supported shortcut key !

Usually, after I have queried a word I don't know, I will add it to the new word list of Eudic dictionary, which is convenient for me to memorize the word and remember it in the future.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/25194972/168204643-b66ce408-5350-462a-9932-be246cddf9bd.png">

### Open in Eudic
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/25194972/168204694-19b75f91-425b-4423-8e45-d7ed7735c420.png">

**Who will benefit from this feature?**

[parrot translate] is great, but it would be better if it could be combined with other word search applications, so that more users who are currently using other word apps can benefit from it. Thank you very much.

**Comment by tisfeng** [comment]
Maybe can consider referring to [PopClip's Eudic plugin](https://pilotmoon.com/popclip/extensions/page/Eudic) , which can directly query the selected words in the Eudic after crossing word, which is very convenient.

https://github.com/pilotmoon/PopClip-Extensions/blob/master/source/Eudic.popclipext/eudic.applescript
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/25194972/168206524-2b049a5f-b319-4285-a9a0-fa7ebea00655.png">

**Comment by Haojen** [comment]
Here is my reply  https://github.com/raycast/extensions/pull/1708#issuecomment-1127902135
