### ISSUE TITLE
[API Feature Request] Toast Event Handler

### ISSUE THREAD

**Issue by froxcey** [raycast/extensions#169]
**Describe the feature and the current behavior/state.**
I love the toast API. It's extremely easy to use, and it has a great aesthetic. By using `const toast = new Toast()`, we get to control the toast. The toast has a x button that user can click on, and there's this loading animation. I wish there's an event handler (like `toast.on('close')`) that fires at least when `toast.style = ToastStyle.Animated`. Also, `toast.on('click')` might be less useful, but it can be used to display a error log file when something went wrong or to show a webpage containing some information.

**Will this change the current api? How?**
It's going to add an event handler to the toast API

**Who will benefit with this feature?**
A lot of people, really. The first one can be used to stop http requests, download, and pretty much anything that require loading. Second one can provide better error handling, especially for debugging when something went wrong on a distributed build.

**Comment by mathieudutour** [comment]
Instead of Toasts having different behaviour on click, we are going to allow for Toast Buttons instead so that the action is clear when the user click on something: https://github.com/raycast/extensions/issues/438
