### ISSUE TITLE
[Music] ...

### ISSUE THREAD

**Issue by Dragoid88** [raycast/extensions#1692]
# Extension – [Music](https://github.com/raycast/extensions/tree/e57abb84d6cc58f65bcf35282f0ddf5c4ce67804/extensions/music/)
Author: @Rawnly

## Description
When trying to use the Add to Library, and/or the love and add to library command there is a pop-up that says "An error has occurred"
## Steps To Reproduce

1. open Raycast 
2. search add to library
3. use the add to library command

## The current behavior
pop up error

## The expected behavior
currently playing song to be added to the users library and 
### Raycast version
Version: 1.34.1
![CleanShot 2022-05-14 at 01 03 38@2x](https://user-images.githubusercontent.com/75586509/168413091-ea864cd1-136b-441d-bdfe-225ee07b4fbf.png)

**Comment by Rawnly** [comment]
Hi! Thanks for reporting, the error seems to be in the "add to library" script, i'm working to fix it
