### ISSUE TITLE
[Documentation] can't receive confirm email

### ISSUE THREAD

**Issue by itshxu** [raycast/extensions#17]
Hi, Raycast team

I got a problem signing up with email, Google or Github. I filled the sign up form and go back to login and the website promoted that email confirm is required. But I checked my Gmail and didn't get any email from Raycast.

Please check it out and send me a confirm email to <REDACTED> if it's okey.

Thanks a lot

**Comment by RSO** [comment]
Hey @itshxu,

We hit an unfortunate bottleneck in our email delivery overnight, which should have recovered by now. Please let me know if the confirmation email still hasn't been delivered!

Sorry for the inconvenience!
