### ISSUE TITLE
brew: use the wrong brew binary when tow architectures installed in M1

### ISSUE THREAD

**Issue by sfwn** [raycast/extensions#1701]
# Extension – [brew](https://github.com/raycast/extensions/tree/main/extensions/brew)

Author: @nhojb 

## Description

brew commands failed to execute if you have installed of both two architectures:

- /usr/local/Homebrew/bin/brew
- /opt/homebrew/bin/brew

It works on terminal correctly,
<img width="225" alt="image" src="https://user-images.githubusercontent.com/13919034/168461785-ee2fb784-487c-4599-9cbe-008177a1d67a.png">

But broken on raycast,
<img width="442" alt="image" src="https://user-images.githubusercontent.com/13919034/168461807-9eb1d981-4d24-4e36-840d-19efbce55a06.png">

I have set PATH via `~/.profile`,
<img width="490" alt="image" src="https://user-images.githubusercontent.com/13919034/168461864-cd8c9f29-b0cb-4722-963c-f10414afd611.png">

## Steps To Reproduce

1. install two archs brew via https://docs.brew.sh/Installation#alternative-installs
2. set PATH correctly
3. tested in terminal and works fine
4. tested in raycast and failed

## The current behavior

use intel arch and work failed.

## The expected behavior

use arm arch.

### Raycast version

Version: 1.34.1
<img width="430" alt="image" src="https://user-images.githubusercontent.com/13919034/168462807-2d628e79-9a4d-4eb7-a154-5147b32cc8e2.png">

**Comment by PKizzle** [comment]
I have the exact same issue when trying to upgrade a formula. It would be additonally nice to be able to seamlessly switch between the x86 and arm version of brew.
