### ISSUE TITLE
[Visual Studio Code Recent Projects] Cannot find remote projects

### ISSUE THREAD

**Issue by Aiee** [raycast/extensions#1705]
# Extension – [Visual Studio Code Recent Projects](https://github.com/raycast/extensions/tree/3019509c5017168e4984dee77e678647b833a3c0/extensions/visual-studio-code-recent-projects/)
Author: @thomaspaulmann

## Description
Cannot open projects opened via SSH.
![image](https://user-images.githubusercontent.com/18348405/168532900-fc82e85e-b11a-4052-a473-322b3266192c.png)

It worked as expected weeks ago, not sure what broke this.

## Steps To Reproduce

1. Open the extension

## The current behavior
The extension only shows the local projects/files recently opened.

## The expected behavior
To show both local and remote projects.

### Raycast version
Version: 1.34.1

**Comment by yug2005** [comment]
I also have this issue.

**Comment by pernielsentikaer** [comment]
So it's only remote projects that are not working, right?

@macbookandrew do you have an idea about this one?

**Comment by pernielsentikaer** [comment]
Hi @Aiee and @yug2005 - could you try to see if it works for you in the latest version?

**Comment by yug2005** [comment]
For me, it is displaying an error screen. 

![image](https://user-images.githubusercontent.com/77864399/169871964-85994835-9264-466c-ad3a-1a747770291a.jpeg)

**Comment by pernielsentikaer** [comment]
@yug2005 could you please press ⌘+k and cope the error and paste it?

**Comment by yug2005** [comment]
TypeError: The "path" argument must be of type string. Received undefined

**Comment by pernielsentikaer** [comment]
@yug2005 what version of Visual Studio Code do you have?

**Comment by pernielsentikaer** [comment]
@yug2005 what version of Visual Studio Code do you have?

**Comment by yug2005** [comment]
1.67.2

**Comment by pernielsentikaer** [comment]
Can you help me debug it?

Can you catch me in [Slack](https://www.raycast.com/community) or in a DM on Twitter if you have that?

**Comment by pernielsentikaer** [comment]
@macbookandrew do you have time to help me out with bug or two? You can reach me in [Slack](https://www.raycast.com/community) or Twitter DM :)

**Comment by macbookandrew** [comment]
@pernielsentikaer are you able to reproduce this?

**Comment by pernielsentikaer** [comment]
Not yet since I didn't get any data, I found another missing thing that you maybe want to help with? Before changing to the new SQL format we filtered out deleted paths, this seems to be forgotten and will break the extension - do you think you could help with that @macbookandrew

**Comment by macbookandrew** [comment]
@pernielsentikaer I vaguely recall seeing something like that…do you recall roughly when that would have been working?

(I’m primarily a PHP/web backend developer and just hack on JS/React projects, so I’d prefer to find what was working and replace that vs. writing it from scratch)

**Comment by Aiee** [comment]
Hi @macbookandrew @pernielsentikaer,
Just an update for you guys, the extension now can load remote projects now. Seems the recent update fixed the problem.

Thanks!
