### ISSUE TITLE
[Calendar - My Schedule] - Hide spam events

### ISSUE THREAD

**Issue by depsimon** [raycast/extensions#1707]
# Extension – [Calendar](https://www.raycast.com/extensions/calendar)

## Description

The Calendar shows events created from spam email that I receive on my GMail address.
I remember I had to do something special on my Gmail calendar to not show those events. So on my GMail & Mac Calendar I don't see those events.

In the first screenshot you can see two spam events for today.

<img width="470" alt="screenshot 237" src="https://user-images.githubusercontent.com/1822289/168589160-d799f82d-1980-4b13-8ead-a6ddb1e14850.png">

In the next screenshot you can see the spam events don't appear when opening in RayCast.

<img width="862" alt="screenshot 238" src="https://user-images.githubusercontent.com/1822289/168589474-599df651-cbf2-4bd8-8a7b-044cfd4f696a.png">

## The expected behavior

Ignore events from spam mail in the MySchedule menubar.
It works fine when showing the events in Raycast, but the My Schedule feature displays all events even the spams.

### Raycast version

Version: 1.34.1

**Comment by sxn** [comment]
hi @depsimon 👋  thanks for the report, we'll look into what's going on 😱 
As this issue isn't related to the Extensions API, but to the native `My Calendar` extension, I'll close this issue.

Would you mind submitting it using Raycast's `Send Feedback` command? That way we can track progress & keep you updated when it's fixed. ❤️
