### ISSUE TITLE
Zotero: BibText key copying fails (and basic copy citation functionality sadly removed)

### ISSUE THREAD

**Issue by lutefiasco** [raycast/extensions#1710]
# Extension – [(https://github.com/raycast/extensions/tree/main/extensions/*)](https://github.com/raycast/extensions/tree/main/extensions/zotero)

Author: @sadanand-singh 

## Description

New, local-sql lite version of Zotero extension (hooray! Thank you! it's a terrific improvement!) no longer has functionality to copy static citations, rather than Bibtex, which is a major loss.

To remedy, I installed Bibtex, updated Zotero to export with Bibtext, verified the output format is now BibText, but receive a "something went wrong" error when attempting to "Copy BibText citation key".

## Steps To Reproduce

1. Invoke extension, search for item, choose "copy BibText citation key"
2.

### Raycast version

Version: 1.34.1
[RaycastZoteroErrorLog.txt](https://github.com/raycast/extensions/files/8703016/RaycastZoteroErrorLog.txt)

**Comment by sadanand-singh** [comment]
yes, I am still trying to figure out a good way to enable this. I have a solution locally, but is quite slow for the release.

Regarding your error, its an issue with changing extension settings. In your particular case, the cache was created before you have better beibtex enabled. so until the cache is updated, you will keep getting this error. I am working on a solution to handle this properly.

For the time being, either you can uninstall and re-install the extension, and then before launching a query enable bibtex in extension preferences, or just add a new entry to your zotero database.

**Comment by lutefiasco** [comment]
Uninstalling/reinstalling and enabling bibtex resolved the error. And thanks for letting me know that Zotero's shift-command-A and shift-command-C functions are possible on the roadmap. This is a great Raycast extension - I was using Alfred's zothero, so this is deeply appreciated. Do let me know if there's anything I can do to help with testing.

**Comment by sadanand-singh** [comment]
PR #1772 closes this.
