### ISSUE TITLE
[Figma File Search] ...

### ISSUE THREAD

**Issue by cjp585** [raycast/extensions#1732]
# Extension – [Figma File Search](https://github.com/raycast/extensions/tree/1da89c4626dd39b3c50a12208ee14c816f918ae8/extensions/figma-files/)
Author: @michaelwschultz

Trying to use the Figma file search extension shows a "Something went wrong" error. I was able to fix it before by generating a new token and replacing that in Preferences but that no longer works.

## Description

Cannot read properties of undefined (reading 'filter')
## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.35.1

**Comment by michaelwschultz** [comment]
@cjp585 sorry for the late response. I'll look into this and see if I can reproduce.

**Comment by cjp585** [comment]
Thank you! I uninstalled the extension and reinstalled using a fresh token and haven't had the issue for about a week if that helps.

**Comment by mathieudutour** [comment]
I'm going to close this one as it's duplicated https://github.com/raycast/extensions/issues/1670
