### ISSUE TITLE
[Music] ... Error with the playlist

### ISSUE THREAD

**Issue by sialaweb** [raycast/extensions#1734]
# Extension – [Music](https://github.com/raycast/extensions/tree/e6ee788e13d636649cdc9d653c920bef9ebc8858/extensions/music/)
Author: @Rawnly

## Error:
```

```

## Steps To Reproduce

1. command + space 
2. type music playlist

code:
TypeError: Cannot read properties of undefined (reading 'split')

start-playlist.js:42:425

---
39: 			${zu(t==="all"?"all":t)}
40:         end tell
41: 	return output
42: `);var Vu=X(nr());var qI=t=>{switch(t){case"subscription":return"Apple Music";case"user":return"Your Library";default:return t}};function Hu(){let[t,e]=(0,Ne.useState)("all"),[r,n]=(0,Ne.useState)(null),{pop:a}=(0,B.useNavigation)();return(0,Ne.useEffect)(()=>{(0,Ce.pipe)(t,Pe.getPlaylists,fe.mapLeft(p=>(0,B.showToast)(B.Toast.Style.Failure,"Could not get your playlists")),fe.map((0,Ce.flow)(Cu(),p=>Vu.groupBy(s=>s.kind.split(" ")[0])(p),n)))()},[t]),_jsx(B.List,{isLoading:r===null,searchBarPlaceholder:"Search A Playlist",searchBarAccessory:_jsx(B.List.Dropdown,{tooltip:"Playlist Kind",value:t,defaultValue:"all",onChange:p=>e(p)},_jsx(B.List.Dropdown.Item,{title:"All",value:"all"}),_jsx(B.List.Dropdown.Item,{title:"User",value:"user"}),_jsx(B.List.Dropdown.Item,{title:"Apple Music",value:"subscription"}))},Object.entries(r??{}).filter(([p])=>p!=="library").map(([p,s])=>_jsx(B.List.Section,{title:qI(p),key:p},s.map(m=>_jsx(B.List.Item,{key:m.id,title:m.name,accessoryTitle:`\u{1F3A7} ${m.count}  \u23F1 ${Math.floor(Number(m.duration)/60)} min`,icon:{source:"../assets/icon.png"},actions:_jsx(MI,{playlist:m,pop:a})})))))}function MI({playlist:{name:t,id:e},pop:r}){let n=`Start Playlist "${t}"`;return _jsx(B.ActionPanel,{title:n},_jsx(B.Action,{title:n,onAction:async()=>{await(0,Ce.pipe)(e,Pe.playById,fe.map(()=>(0,B.closeMainWindow)()),fe.mapLeft(()=>(0,B.showToast)(B.Toast.Style.Failure,"Could not play this playlist")))(),r()}}))}module.exports=nc(UI);0&&(module.exports={});
43: 
---

start-playlist.js:1:70255
start-playlist.js:42:439
start-playlist.js:1:3094
start-playlist.js:1:37655
Object.vc:start-playlist.js:1:4123
Object.Z:start-playlist.js:1:34630
start-playlist.js:1:7489
processTicksAndRejections:task_queues:96:5

### Raycast version
Version: 1.35.0

**Comment by Rawnly** [comment]
Hi! Thanks for reporting, I'm currently unable to reproduce the issue, can you give me some details? (playlist name etc..)

**Comment by Rawnly** [comment]
@sialaweb can you try (in a few mins)  if it has been fixed?

**Comment by sialaweb** [comment]
Yeahh!!! its fixed, now I can see the playlists, thanks!! great plugin and support!!
