### ISSUE TITLE
[Github] Inbox Notifications

### ISSUE THREAD

**Issue by ajdubovoy** [raycast/extensions#1737]
**Describe the feature and the current behavior/state.**

Currently, when running GitHub Notifications, all notifications are shown without filters.

I wish there were a filter box for "Inbox", "Saved", "Unread", and "Done". GitHub supports these filters in the web interface.

**Will this change the current API? How?**

Not really, it would just be a new filter box on the side.

**Who will benefit from this feature?**

Probably everyone who uses GitHub notifications.

**Any Other info.**

Love Raycast. Thanks so much for your work!

**Comment by unnamedd** [comment]
GitHub Notifications isn't a built-in extension, therefore source code is closed. For improvements in it, you need to use the `Send Feedback` form from inside of Raycast or use the [Slack Community](https://raycast.com/community).

**Comment by ajdubovoy** [comment]
Will do thanks!
