### ISSUE TITLE
Community Slack invitation not working

### ISSUE THREAD

**Issue by jones-sam** [raycast/extensions#1740]
When I try to join the community via the link in the readme:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/45644425/169292459-f00842af-8a33-4c63-8bff-3609778e738f.png">

I get this error from slack:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/45644425/169292647-93484b2d-a6e9-4693-9d55-7d2638277614.png">

**Comment by mathieudutour** [comment]
@thomaspaulmann anything we have to change here?

**Comment by pernielsentikaer** [comment]
It's now working again, thanks for flagging @jones-sam 😄

**Comment by thomaspaulmann** [comment]
> @thomaspaulmann anything we have to change here?

Slack sometimes expires the invitation link. I created a new one. It should be non-expiring now.
