### ISSUE TITLE
[Authy] Entered wrong authy ID, stuck in the process

### ISSUE THREAD

**Issue by bartkummel** [raycast/extensions#1744]
Hi,

I've installed the Authy extension. I made a mistake when I entered the Authy ID. However, I can't go back to that screen anymore. The option to "start the process from scratch" just tries with the same ID again. There's no way to go back to the input screen and enter the correct ID.

**Comment by andreaselia** [comment]
Hi @bartkummel, have you tried uninstalling the extension and then reinstalling it?

**Comment by bartkummel** [comment]
That worked. However, I consider that a work around rather than a proper fix.

**Comment by andreaselia** [comment]
I totally forgot about this, but you can also update your Authy ID in the "Configure Extension" screen which essentially takes you to Raycast Preferences where you'll be able to select the Authy extension, and update the Authy ID on the right hand side.

![CleanShot 2022-05-20 at 09 10 46@2x](https://user-images.githubusercontent.com/5033092/169484326-ba5a081e-662c-4394-b4c5-f52c08540198.png)
![CleanShot 2022-05-20 at 09 11 53@2x](https://user-images.githubusercontent.com/5033092/169484401-83dac563-39ae-4abb-a0bd-1b2de9bda02b.png)

**Comment by bartkummel** [comment]
Thanks. That feature is hidden well! ;-)
