### ISSUE TITLE
[Feature Request] - Local hotkeys

### ISSUE THREAD

**Issue by jezikk** [raycast/extensions#1751]
It would be nice to have local hotkeys which would be triggered only if Raycast search windows is opened. For example the following use case would be used to search in Google using Google search extension:

1. CMD + SPACE - Open Raycast search window. 
2. Still holding down CMD and press G - route to Google search extension.

**Describe the feature and the current behavior/state.**
Only global hotkeys all available. For example it is not possible to use CMD + F hotkey due to a possible collision with another application.

**Will this change the current API? How?**
Yes

**Who will benefit from this feature?**
All users. Increases usage performance.

**Comment by mathieudutour** [comment]
As this issue isn't related to the Extensions API, but to the native application, I'll close this issue.

Would you mind submitting it using Raycast's `Send Feedback` command? That way we can track progress & keep you updated when it's fixed. ❤️
