### ISSUE TITLE
[Change Case] ...

### ISSUE THREAD

**Issue by paulmarique** [raycast/extensions#1765]
# Extension – [Change Case](https://github.com/raycast/extensions/tree/a0c62af506694a97060f53530dd6291dbeb8244d/extensions/change-case/)
Author: @es183923

## Description
Latin special characters are not working on a few case change commands. (see screenshots)

Exemple with french: 
In Pasteboard : Déjà, j'aime beaucoup les établis
After Sentence Casing : D j j aime beaucoup les tablis 

## Steps To Reproduce
1. copy this : Déjà, j'aime beaucoup les établis
2. Open Change Case in Raycast 3. 

### Raycast version
Version: 1.35.1
![Screenshot 2022-05-21 at 22 57 00](https://user-images.githubusercontent.com/11415856/169668696-dd195817-3e54-4db4-a53a-ffe70b9e6884.jpg)
![Screenshot 2022-05-21 at 22 57 23](https://user-images.githubusercontent.com/11415856/169668730-022fd02d-4ac4-414f-968f-efff770a7409.jpg)
![Screenshot 2022-05-21 at 22 57 26](https://user-images.githubusercontent.com/11415856/169668731-9d847258-876b-401d-946b-eaf12f386456.jpg)

**Comment by es183923** [comment]
its not a feature. the package internally used by the extension doesn't support these types of characters. if youd like a fix, feel free to make a PR, but I dont have the time to do so
