### ISSUE TITLE
[Feature Request]: Can we support the customize the React Component?

### ISSUE THREAD

**Issue by ParseDark** [raycast/extensions#1767]
**Describe the feature and the current behavior/state.**
Ok. I think we can render react on the panel. So why not support the customize react component? For Example, we can add more and more extensions. Not only the List or a markdown or a form. If can support the React component. That means we can create everything on the Raycast. We have an entire frontend world resource. Why limit ours on the List/Detail/Form?
It will more and more frontend engineers join ours.

**Will this change the current API? How?**
I think not. We just provide a new feature to support the user customize the UI interface.

**Who will benefit from this feature?**
I think the feature will benefit all raycast developers.
**Any Other info.**
I like the raycast. And also I am Alfred 4 user. If raycast wants to be more powerful in the launch tool app, I think supporting the customized components is necessary.

Finally thanks for you work. Raycast Team.

**Comment by ParseDark** [comment]
By the way. I think the @raycast/api package should be split to two package. 
1. @raycast/api
2. @raycast/ui

**Comment by andreaselia** [comment]
I personally believe this would open up a can of worms, and make the Raycast experience inconsistent between extensions. Having a fixed set of components exposed via @raycast/api means that all extensions will have a consistent UI with each other.

**Comment by ParseDark** [comment]
> I personally believe this would open up a can of worms, and make the Raycast experience hugely inconsistent between extensions. Having a fixed set of components exposed via @raycast/api means that all extensions will have a consistent UI with each other.

You are right. But I think it's a choice. Just like you choose a closed or an opening system. Having a consistent UI is important I agree. But if not supported the customized feature will tie the extension developer. It will lose a lot of potential extension developers. If not have the extension developer join it. We can't build an ecological. 

For my side. I think in the initial phase I think more and more developers joining is more important thing.

**Comment by mathieudutour** [comment]
What kind of customizations are you thinking about? If it's a free-for-all generic View, it's very unlikely that it's going to happen. The reason why we have a limited set of components is because they are natively converted to native views.

**Comment by ParseDark** [comment]
> What kind of customizations are you thinking about? If it's a free-for-all generic View, it's very unlikely that it's going to happen. The reason why we have a limited set of components is because they are natively converted to native views.

Got it. I thought the raycast was just like the tauri... If not I got it. I will close the issue. And thanks again raycast developer team bring a powerful project.
https://github.com/tauri-apps/tauri
