### ISSUE TITLE
[API Feature Request] OAuth2 support

### ISSUE THREAD

**Issue by lardissone** [raycast/extensions#178]
I would like to be able to use OAuth2 in extensions.
Ideally for services that doesn't provides a test access token feature.

**Describe the feature and the current behavior/state.**
Something like the native extensions works (ie, Linear). A link opens in your browser, you log in and allow then it's redirected back to Raycast (and, somehow, to your extension) to continue the process.
Automated refresh token support would be amazing too. 

**Will this change the current api? How?**
Nope, it's just a new feature.

**Who will benefit with this feature?**
Anyone who wants to use third party services that uses OAuth2 as authentication.

**Comment by mathieudutour** [comment]
Shipped in v1.33.0
