### ISSUE TITLE
[Music] ...

### ISSUE THREAD

**Issue by shamimrahim** [raycast/extensions#1794]
# Extension – [Music](https://github.com/raycast/extensions/tree/e6ee788e13d636649cdc9d653c920bef9ebc8858/extensions/music/)
Author: @Rawnly

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.35.1

**Comment by Rawnly** [comment]
?

**Comment by pernielsentikaer** [comment]
Hi @shamimrahim, could you please edit your Issue so that we can see what's not working out 😄

**Comment by shamimrahim** [comment]
Sorry, I was trying to get the apple music extension working. I tried to submit a bug report but I clearly messed it up. I will try again when i get home from work. 
Sorry for the confusion
