### ISSUE TITLE
Zotero database search returns entries not containing the search term

### ISSUE THREAD

**Issue by robinhsi** [raycast/extensions#1799]
# Extension – [Zotero](https://github.com/raycast/extensions/tree/d356f51d3540c1fbeddad80d6806a6256eb1b4b8/extensions/zotero/)

Author: @sadanand-singh 

## Description
Zotero database search returns entries not containing the search term. When searching for any keyword in the database, it brings up almost all my database entries. At first I thought it searches everything, akin to Zotero search set to 'Everything' (which would make it near unusable). However, even when I search for a random string of characters, it still returns hundreds of entries which couldn't possibly be accurate.

![Screenshot 2022-05-24 at 19 28 34](https://user-images.githubusercontent.com/75787113/170106707-c0559aec-e87e-449c-b630-d05a83bf0ab6.png)

## Steps To Reproduce

1. Search for anything, such as a bogus search term (e.g. "shdufisaldhfsaildfuhaisd")
2. Get hundreds of results

## The current behavior
Returns almost all my entries

## The expected behavior
Return only entries that match either 'Title, Creator, Year'

### Raycast version

Version: 1.35.1

**Comment by sadanand-singh** [comment]
Thanks for the catch. There indeed was a bug in fuzzyness factor that I use in Fuse.js library. PR #1772 closes this.

Also note that search is slightly different than default Zotero.

Here matching is done with 10% fuzziness for title (40% weight), abstract (30% weight), tags (10% weight), creators (10% weight) and Year/Date (10% weight). You can also filter exact tags by prepending those terms with "." (without quotes) - please see README for details.

**Comment by pernielsentikaer** [comment]
This is now merged

**Comment by robinhsi** [comment]
> Thanks for the catch. There indeed was a bug in fuzzyness factor that I use in Fuse.js library. PR #1772 closes this.
> 
> Also note that search rules are slightly different than default Zotero.
> 
> Here matching is done with 10% fuzziness for title (40% weight), abstract (30% weight), tags (10% weight), creators (10% weight) and Year/Date (10% weight). You can also filter exact tags by prepending those terms with "." (without quotes) - please see README for details.

Thank you @sadanand-singh! I can see PR #1772 fixes the main bug, but I don't think it searches Creators or Year/Date (which coincidentally are what I search for the most). Not sure I should open a new issue for this? Thanks for your work!

**Comment by sadanand-singh** [comment]
Yes, I am in the middle of another PR for that. If you want you can create a new issue. Its just that current PR got merged before I could push my changes 😀
