### ISSUE TITLE
[API Feature Request] Select file

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#180]
**Describe the feature and the current behavior/state.**

I'd like a way to select a file from the user hard drive, ideally it should be part of the Form fields since I would like to use it on my [Transmission](#148) extension to let them add a torrent from a .torrent file.

**Will this change the current api? How?**

Nope.

**Who will benefit with this feature?**

Extension that require to select/load a file from the user hard drive.

**Any Other info.**

**Comment by michaelwschultz** [comment]
I think this would make so many more business workflows possible. Passing around files is just so necessary. Could be cool to be able to drag and drop into Raycast as well, and add multiple files. I can imagine a ton of extensions this would unlock.

**Comment by mathieudutour** [comment]
Available in 1.44
