### ISSUE TITLE
[Keyboard Maestro - List Macros] Add Edit Macro Option

### ISSUE THREAD

**Issue by jonathanlaniado** [raycast/extensions#1809]
# Extension – [Keyboard Maestro - List Macros](https://github.com/raycast/extensions/tree/cdaaf846198717c2b9cf058b60cc991c9c5aea8e/extensions/keyboard-maestro/)
Author: @eluce2

Can we add a new option in the list to edit the macro? In Keyboard Maestro's default `Trigger Macro by Name` action, holding Option+Enter will open the selected macro in the Keyboard Maestro Editor.

Any chance we can add similar functionality to this extension?

**Comment by jonathanlaniado** [comment]
@eluce2, love your work on the extension here. Any chance you could add the `Edit Macro` option?

**Comment by eluce2** [comment]
Sorry for the delay. At first I thought this was impossible and thought this was closed, but I looked again and was able to figure it out so I've submitted a PR with this feature

**Comment by eluce2** [comment]
I've added the keyboard shortcut ⌘+E to edit, but you can also use ⌘+Return (which is the standard Raycast shortcut for the secondary action)

**Comment by jonathanlaniado** [comment]
You made my day, thank you for getting this done so quickly. Love it! 😊
