### ISSUE TITLE
VS Code extension does not provide all recent items

### ISSUE THREAD

**Issue by mskelton** [raycast/extensions#1810]
# Extension – [Visual Studio Code Recent Projects](https://github.com/raycast/extensions/tree/main/extensions/visual-studio-code-recent-projects)

Author: @thomaspaulmann

## Description

The changes in https://github.com/raycast/extensions/pull/1630 changed to loading the recent VS Code projects from the storage.json path which is what is used to build the VS Code recent projects in the menu.  However, this is not the full list that you get when using the `File: Open recent` command via the command palette.

This is problematic since it only shows the most recent 10 projects rather than the full list.

I made a branch to revert to using the sqlite DB as the source of truth which fixes this issue. 
 https://github.com/raycast/extensions/compare/main...mskelton:fix-vscode-extension

## Steps To Reproduce

1. Open the recent projects command in Raycast

## The current behavior

Notice that only the last 10 projects are listed.

## The expected behavior

All recent projects are listed.

### Raycast version

Version: 1.35.1

**Comment by pernielsentikaer** [comment]
Hi @mskelton 👋 

It sounds like a good idea to make it stable again, and it seems like too many issues popped/pops up after changing the database type.

Could you make a PR so we can get it stable again?

**Comment by mskelton** [comment]
@pernielsentikaer Done!

https://github.com/raycast/extensions/pull/1811
