### ISSUE TITLE
[Search Zotero] ...Copy Bibtex and Copy Reference to Clipboard failing

### ISSUE THREAD

**Issue by lutefiasco** [raycast/extensions#1813]
# Extension – [Search Zotero](https://github.com/raycast/extensions/tree/00ba06582a2cff7fac1f59d531b0c97428ed062e/extensions/zotero/)
Author: @sadanand-singh

## Description
I have uninstalled and reinstalled the updated Zotero extension.

I have ticked/unticked the box fro BibTex with Zotero running and not running. 

All three copy options ("copy bibtex citation key", copy reference to clipboard, and copy bibtext to clipboard) display a "something went wrong" raycast screen.

The error is too long to paste in its entirety, but seems to be related to lib.json not being present.

## Error:
```

```

## Steps To Reproduce

1. Invoke any of the "copy to clipboard" commands.
2.

### Raycast version
Version: 1.35.1

**Comment by sadanand-singh** [comment]
See the Readme file on how to create the lib.json file

**Comment by lutefiasco** [comment]
I have created the lib.json file, and although Raycast no longer gives an error, the extension still fails. Invoking any of the copy commands  displays "copied to clipboard", but the clipboard remains empty.

**Comment by sadanand-singh** [comment]
Not sure what is happening. It is working on both of my machines

**Comment by sadanand-singh** [comment]
May be check manually if lib.json file indeed contains the particular reference that you are trying to copy.

**Comment by sadanand-singh** [comment]
There is no way to reproduce this. Either please provide details or close this.

**Comment by camayl** [comment]
Same issue here and the log is huge, any way to privately send it to you?

**Comment by michaelmior** [comment]
I believe I just posted a duplicate as #2549. I'm seeing the same issue.

**Comment by michaelmior** [comment]
In my case, I didn't see a message anywhere that I needed to install Better Bibtex and set up export. However, I did so and the lib.json file does indeed contain the document I am trying to cite.
