### ISSUE TITLE
Zotero: CSL Styles for Humanities Scholars, Note vs Bibliography Copying, Quick Search only Searches Title Field

### ISSUE THREAD

**Issue by lutefiasco** [raycast/extensions#1814]
# Extension – [Zotero](https://github.com/raycast/extensions/tree/main/extensions/zotero/*)

Author: @sadanand-singh

1 )The subset of citation styles offered by the extension via raycast omits any major citation styles used by scholars working in Humanities fields: Chicago and MLA.

2) The extension does not enable the copying of bibliography items in Full Note format and in Footnote Citation format (Cmd-Shift-C and Cmd-Shift-A in Zotero)

3) "Quick search" only searches title field, not author field, which does not replicate quick search functionality in Zotero app.

**Comment by lutefiasco** [comment]
Just to be clear, I remain incredibly grateful for this extension, and for the work you're putting into it. I am not in a position to contribute to development, but did want to set out different use-case scenarios.

**Comment by sadanand-singh** [comment]
PR #1840 closes this. Please note that point no. 2 will not be supported.

**Comment by sadanand-singh** [comment]
This can be closed.
