### ISSUE TITLE
How to edit/manage "library" ?

### ISSUE THREAD

**Issue by dzg** [raycast/extensions#1827]
Just discovered this; very cool!

But 
- how do I see/manage the "Shortcut Library" ?
- can I assign a keyboard shortcut to a particular shortcut?

Thanks!

**Comment by mattisssa** [comment]
Hey! Which shortcuts do you mean, the macOS app?

![CleanShot 2022-05-27 at 14 12 03@2x](https://user-images.githubusercontent.com/15333662/170706009-efdb9944-b24d-4b55-bedf-345e0cb52254.png)
