### ISSUE TITLE
[Search Zotero] Search by author name

### ISSUE THREAD

**Issue by eepperly** [raycast/extensions#1828]
# Extension – [Search Zotero](https://github.com/raycast/extensions/tree/00ba06582a2cff7fac1f59d531b0c97428ed062e/extensions/zotero/)
Author: @sadanand-singh

**Describe the feature and the current behavior/state.**

I think it would be very helpful if this extension could search the Zotero database by author name. Currently, if I search for "Kitaev", I get several articles which mention Kitaev's name in the abstract, but no papers by Kitaev himself.

**Who will benefit with this feature?**

Many researchers think of papers by their author and year, rather than the title and keywords which may appear in the abstract. By adding this feature, I think this would benefit many users who search for papers by author.

**Any Other info.**

**Comment by sadanand-singh** [comment]
Yes, I am working on a PR for this. Probably it will be up for review this weekend.

**Comment by eepperly** [comment]
> Yes, I am working on a PR for this. Probably it will be up for review this weekend.

This is delightful to hear. Thank you for your hard work on this!
