### ISSUE TITLE
Disable/Ignore copied text from extension in Clipboard history

### ISSUE THREAD

**Issue by georgesnow** [raycast/extensions#1832]
Currently, if extension is copying transient or concealed info and a user is using clipboard history. This text will be in pasteboard and the Clipboard History. 

Example KeePassXC extension copies an entries password.  The password will be stored in the Clipboard History extension requiring manually deletion. If the API allowed for the copied text to be marked the following (or alternatively if the Clipboard Extension could ignore not just specific apps, but extensions):

http://nspasteboard.org

And RayCast would honor these types (if doesn't already) to not be captured by the Clipboard History. 

Edit: Opened a ticket on React Native about the pasteboard types
https://github.com/react-native-clipboard/clipboard/issues/143#issue-1259973707

**Comment by peduarte** [comment]
Hey, excellent suggestion, thank you. We're tracking this internally now and it's under consideration!

**Comment by mathieudutour** [comment]
Available in 1.48.0!

**Comment by georgesnow** [comment]
So I downloaded 1.48.0. How do select which extensions for clipboard history to ignore?
