### ISSUE TITLE
Need help with the one password extension

### ISSUE THREAD

**Issue by kerim** [raycast/extensions#1841]
I'm stuck on step 5. 

1. Make sure you using 1Password 8 
2. Install the [1Password CLI](https://developer.1password.com/docs/cli) 
3. Open and unlock 1Password 
4. Choose 1Password > Preferences > Developers and enable CLI integration
5.   Use [opbookmarks](https://github.com/dteare/opbookmarks) to export your item metadata

I was able to download a release of opbookmarks from the github page, but I have no idea how to use it. It is just there in my downloads folder and clicking it gives an error message. I can't install from the commandline with brew either, as there is no formula for that. That about exhausts my CLI knowledge. Thanks.

**Comment by TwisterMc** [comment]
Were you able to install Rust? You need that to run `opbookmarks`

After you get Rust installed, clone [opbookmarks](https://github.com/dteare/opbookmarks) and follow their Build & install instructions. Then  CD to `target/release` and open that folder in the finder with `open .` Then double click on opbookmarks and it should run.

Yes, this is confusing as hell, but let me know where you get stuck and I can try and help.

**Comment by kerim** [comment]
I installed Rust, but I can't figure out the next step. Instructions say:

git clone
cd opbookmarks
cargo build --release

but I get 

fatal: You must specify a repository to clone.

How do I do that? I'm used to using home-brew but it says that there is no such formula.

Opbookarks says I can also find pre-built executables on the releases page, but I'm not sure how to "manually chmod u+x and remove the quarentine bit to make it work" Especially the second part...

**Comment by kerim** [comment]
OK. I seem to have gotten it working. Thanks!
