### ISSUE TITLE
Placeholder text with the same string value doesn't render

### ISSUE THREAD

**Issue by KevinBatdorf** [raycast/extensions#1843]
Raycast version: 1.35.2

## Description

When using the same placeholder text in two List views, navigating to the second view will render an empty string

https://user-images.githubusercontent.com/1478421/170882715-07eaa337-4ca6-4ba7-a5b6-2d8e74938c1b.mov

## Steps To Reproduce

```js
import { Action, ActionPanel, List } from "@raycast/api";

export default function Command() {
  return (
    <List searchBarPlaceholder="hi mom">
      <List.Item
        title="Press"
        actions={
          <ActionPanel>
            <Action.Push title="View more" target={<List searchBarPlaceholder="hi mom" />} />
          </ActionPanel>
        }
      />
    </List>
  );
}
```

## The current behavior

Renders empty string

## The expected behavior

Renders the placeholder text

**Comment by fe9lix** [comment]
Confirmed and fixed with the next release!
