### ISSUE TITLE
[Visual Studio Code - Project Manager] Add support for Remote SSH

### ISSUE THREAD

**Issue by chengjianhua** [raycast/extensions#1846]
# Extension – [Visual Studio Code - Project Manager](https://github.com/raycast/extensions/tree/01aca01489c2a293391f6ce92979d79ebe17e5a8/extensions/visual-studio-code-project-manager/)
Author: @MarkusLanger

I'm using VSCode with a remote host. So during the daily development, I'm using the Project Manager extension which is installed in the VSCode Remote Server of the remote server.

So, could this extension to support loading the project.json from the remote host by SSH?

**Describe the feature and the current behavior/state.**

So I propose to add another new command **"Search Remote Project"**, and add related settings in preferences like the path of `projects.json` in the remote machine and the SSH `host` of the remote machine.

**Who will benefit with this feature?**
People who're developing on remote machines using SSH and Visual Studio Code and [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager)

**Any Other info.**

## Reference

* [Developing on Remote Machines using SSH and Visual Studio Code](https://code.visualstudio.com/docs/remote/ssh)

**Comment by chengjianhua** [comment]
@MarkusLanger BTW, I already implemented this feature locally. Can I submit it and raise a pull request for you to review, if you don't mind?

**Comment by MarkusLanger** [comment]
@chengjianhua What about your PR?

**Comment by BinChenn** [comment]
> @MarkusLanger BTW, I already implemented this feature locally. Can I submit it and raise a pull request for you to review, if you don't mind?

Look forward to your PR, PLEASE!

**Comment by chengjianhua** [comment]
@BinChenn Sorry for the delay, I was busy with my work recently. I'll do this ASAP, but I can't have an exact plan.
