### ISSUE TITLE
Deepcast Translation API

### ISSUE THREAD

**Issue by MvBibs** [raycast/extensions#1850]
# Extension – [Deepcast Translation API](https://github.com/raycast/extensions/blob/7c4e3b223650e6dc56a56d0f5bc98ff87afd9e28/extensions/deepcast/README.md)

Author: @mooxl

## Description
The extension for translating a selected word into a determined language does not work and leads to an error indication. Even though, the clipboard history shows the selected word. In contrast, the "translate" extension works perfectly well.

## Steps To Reproduce

1. Copy a word
2. check if it's in the clipboard history
3. start the deepcast extension for a single language (e.g. "translate into German")

## The current behavior
error indication:
>please select the text to be translated
## The expected behavior
Translating the word into the chosen language
### Raycast version

Version: 1.35.2
![Bildschirmfoto 2022-05-30 um 09 32 25](https://user-images.githubusercontent.com/106513253/170942711-0fb7e966-5b89-4c26-afe5-349bf9e49813.png)

![Bildschirmfoto 2022-05-30 um 09 32 44](https://user-images.githubusercontent.com/106513253/170942765-db01cf1e-943b-4f38-a8f8-6cf591dee99c.png)

![Bildschirmfoto 2022-05-30 um 09 45 06](https://user-images.githubusercontent.com/106513253/170942964-99ff300d-9285-40af-9a77-39f0dbafe011.png)

**Comment by tell-y** [comment]
I faced the same issue.
I'm sure we should copy any sentence before using commands (e.g. Translate Into XXX)
https://github.com/raycast/extensions/pull/947

However, It's not working (Showed the error, "Please select the text to be translated"). My version is 1.43.2.
Any idea? @mooxl @pernielsentikaer @sxn

**Comment by pernielsentikaer** [comment]
Do you have the possibility to look into this @mooxl

**Comment by mooxl** [comment]
Will rework this in the coming weeks:) @pernielsentikaer
