### ISSUE TITLE
[Music] ...

### ISSUE THREAD

**Issue by lazarjov** [raycast/extensions#1861]
# Extension – [Music](https://github.com/raycast/extensions/tree/8acf2c2eec3ca5f4b7e1f1ae3fc067dc694d8ae3/extensions/music/)
Author: @Rawnly

## Error:
```

```

## Steps To Reproduce

1. Open Raycast
2. Run Start Playlist command

## The current behavior
'Something went wrong' message

## The expected behavior
See a list of available playlists

### Raycast version
Version: 1.35.2

**Comment by lazarjov** [comment]
There are only two steps, and the bug occurs.

**Comment by lazarjov** [comment]
I am running macOS Monterey v12.4.

I do have some playlists that start with # or '. I renamed them (or removed them) and nothing changed. Other Music commands work well.

**Comment by Rawnly** [comment]
The only problem I see there is that the querystring confuses the word R&B with a query param. But this is not causing the crash (i tried editing one of my playlists). 

I'll try adding all those playlists to my library and see what happen. (I hope I can do it via apple script and playlists ids lol)

**Comment by Rawnly** [comment]
@lazarjov does it have been fixed?

**Comment by lazarjov** [comment]
Hey @Rawnly! Yup, just tested it. It works great. Thanks a lot 🙌
