### ISSUE TITLE
[Window Management] Cycle through different window sizes with same shortcut

### ISSUE THREAD

**Issue by vanhoofmaarten** [raycast/extensions#1871]
# Extension – Window Management

Author: RayCast

**Describe the feature and the current behavior/state.**

https://user-images.githubusercontent.com/2543633/171578970-333d8e4c-47f0-4b05-b9e1-5f6c9f1e54cf.mov

Currently, each window size requires its own shortcut. 

It would be nice to quickly cycle through different window sizes in a certain direction with the same shortcuts. This frees up combinations for other extensions or commands.

Default cycle could be: Half screen, 2/3 of screen, 1/3 of screen.
Bonus: Configuring the cycle. What if the user could set the different steps and order of the steps of the cycle? Eg. 1/6, 1/4, 1/3, 1/2, 2/3, 3/4, 5/6

**Who will benefit from this feature?**

Everyone! Especially people who are meticulous about their screen real estate.

**Any Other info.**

Nope.

**Comment by vanhoofmaarten** [comment]
Well, in that case: bump.

**Comment by bweave** [comment]
Bump. I would really love to see this feature added. I've currently got a hand-rolled solution in Hammerspoon that does this, and I'd love to be able to drop Hammerspoon and go all-in on Raycast. Thanks!

**Comment by mikestopcontinues** [comment]
This feature keeps me from switching to Raycast for window management. Both `Spectacle` and `Rectangle` offer this. 

I believe the way it works is stateless. If the window is already "left half", then cycle to "left third". If already "left third", then "left 2/3rds". If "left 2/3rds", then "left half".

The same goes all "half" and "quarter" shortcuts.

**Comment by mikestopcontinues** [comment]
I can't seem to find the code for this extension, though I'd be very happy to submit a PR or fork it to add additional features. That said, I'm not an OSX dev, so I don't have the bandwidth to start from scratch. Any chance of this getting opened up?

**Comment by joelamajors** [comment]
I'd love to have the ability to create some different options and have them as shortcuts. I am also not an OSX dev, but I am a dev. I'll throw in if I can!

**Comment by vanhoofmaarten** [comment]
Oh no you don't.

**Comment by Erik262** [comment]
Yeah, This is a feature I requested three times via the Raycast App. Just having a Combo for the Windows size plus the Arrow key for switching the window to the left, right, down or up would be really nice instead of remembering all "Finger acrobatics" shortcuts.

**Comment by Erik262** [comment]
Nope, you do not close anything :)

**Comment by vanhoofmaarten** [comment]
Go back to the Shadow!

**Comment by Erik262** [comment]
> 

tztztzt... We only close when we have our feature! 😘

**Comment by Erik262** [comment]
Nah!... still waiting for the feature....

**Comment by vanhoofmaarten** [comment]
I'm going to follow @mathieudutour 's advice and post something on the Slack channel, as Window Management is not an open source extension.

https://github.com/raycast/extensions/issues/3545#issuecomment-1330402309

**Comment by Erik262** [comment]
@vanhoofmaarten I did write 2 or 3 feature requests from inside the raycast app. No response. I hope you will find some more success :)

**Comment by vanhoofmaarten** [comment]
@Erik262 Look at that, it's already there.

![Screenshot 2023-02-09 at 11 16 36](https://user-images.githubusercontent.com/2543633/217784545-e473b72f-a3ba-4630-8f31-2b6663e11fc0.png)

This scratches my itch.

**Comment by Erik262** [comment]
@vanhoofmaarten lol... Does it work on your side? Cycle adjacent displays doesn't work either.

**Comment by vanhoofmaarten** [comment]
@Erik262 It works, but cycle adjacent displays is not what I would expect.

**Comment by mathieudutour** [comment]
This option is to cycle between sizes, not "adjacent displays". We are planning some improvements to window management soon. In the meantime, I'm going to close this issue as it is not related to the API or extensions. You can use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) to send feedback about the app 😊

**Comment by mikestopcontinues** [comment]
Added some ideas to slack [#suggestions](https://raycastcommunity.slack.com/archives/C01AC2X0GMN/p1676629331770859).
