### ISSUE TITLE
Calculator - Does not accept underscores in number formats

### ISSUE THREAD

**Issue by psikoi** [raycast/extensions#1899]
I apologize for not following the suggested issue format, but I don't think this is an external extension. I couldn't find any other place to report bugs on the base application.

**Describe the feature and the current behavior/state.**

Currently, the base calculator in Raycast does not support underscores in number formats: (Ex: `5_000_000`). 

![Screenshot 2022-06-05 at 08 26 00](https://user-images.githubusercontent.com/3278148/172040409-7434229f-0fe1-4c51-b79e-8a6247cbe008.png)

**Who will benefit from this feature?**

Programmers - This format is very popular in programming languages and sometimes I find myself having to manually replace the underscores with commas when trying to copy/paste values from my code to Raycast.

**Any Other info.**

I believe this request is pretty self-explanatory, but I'd be happy to reply to any questions! I'm in love with Raycast

**Comment by mattisssa** [comment]
Hey @imthath-m! Could you please have a look at the issue? 😉

**Comment by imthath-m** [comment]
Hi @psikoi, Sorry for the late response. 

We do not have plans to support this now. We'll consider your request for the future.
