### ISSUE TITLE
[Color Casket] ...

### ISSUE THREAD

**Issue by BigBenITA** [raycast/extensions#1900]
# Extension – [Color Casket](https://github.com/raycast/extensions/tree/8b2a6ecaf147a474c826077c0dd5d119e270cec7/extensions/color-casket/)
Author:

anybody who is related with graphic/web designer since raycast don't have a color picker plugin**

**Comment by andreaselia** [comment]
Cc: @slava.razum as the extension creator.

**Comment by slavarazum** [comment]
@BigBenITA Could you please describe your idea in more detail. I'll try to do my best 🙂

**Comment by slavarazum** [comment]
@BigBenITA So, I have found a solution to add a color picker to the Color Casket. Release will be soon. Stay tuned 😉

**Comment by BigBenITA** [comment]
> @BigBenITA So, I have found a solution to add a color picker to the Color Casket. Release will be soon. Stay tuned 😉

Oh wow, amazing
