### ISSUE TITLE
[Spotify Player] Add to Queue Functionality

### ISSUE THREAD

**Issue by oddharsh** [raycast/extensions#1913]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/d56cf8925622a6b140aa49a89d94edb809b0c1ac/extensions/spotify-player/)
Author: @mattisssa

Not sure how feasible this is on the API side, but it'd be really cool to have queuing functionality when playing tracks, especially insofar as the play tracks function currently only grabs one song at a time and loops it on repeat until I select the next song.

**Comment by mattisssa** [comment]
no stalebot, keep calm 😄 
we will do that

**Comment by joseph1125** [comment]
This issue can be closed as the feature is finished and merged into main branch
