### ISSUE TITLE
[GIF Search] Can't paste in to Messages

### ISSUE THREAD

**Issue by JonLaliberte** [raycast/extensions#1914]
# Extension – [GIF Search](https://github.com/raycast/extensions/tree/b472207bd12ff855bd5dbec0f20308a5a452ed90/extensions/gif-search/)
Author: @josephschmitt

## Description
When pasting the gif in messages, it doesn't display properly.

## Steps To Reproduce

1. Search then copy gif
2. Paste in to messages.

## The current behavior
Shows this:
<img width="207" alt="Screen Shot 2022-06-07 at 10 55 21 AM" src="https://user-images.githubusercontent.com/5403662/172412365-715b5742-55c4-491c-8fb7-d2c1b8626d7c.png">

## The expected behavior
Should show this:
![IMG_6751](https://user-images.githubusercontent.com/5403662/172412463-e7b518bf-0cfa-4f4c-bec1-9b08c0ade538.gif)

### Raycast version
Version: 1.35.2

I thought it may be related to [1436](https://github.com/raycast/extensions/issues/1436), but I don't receive any errors.
I also tested by going in to Preview and creating a new document from the clipboard and that worked fine:
<img width="1041" alt="Screen Shot 2022-06-07 at 10 58 24 AM" src="https://user-images.githubusercontent.com/5403662/172413110-21f02ff8-f5fb-4e08-a012-aaa412a7b8b1.png">

**Comment by josephschmitt** [comment]
Hmm, that's a weird one. I'm just using AppleScript to copy the downloaded file to your clipboard. @thomaspaulmann any ideas?

**Comment by josephschmitt** [comment]
FWIW, I was just able to paste into Messages ok... 
![image](https://user-images.githubusercontent.com/136007/172462113-6255dee1-9f6a-42b3-aad0-86f99c36ee2b.png)

**Comment by JonLaliberte** [comment]
I just tried a few more gifs to see if it could be image dependent and had the same result still.

macOS 11.6.5 (20G527)

I confirmed with a few friends that they are being received the same way as I see them too.

<img width="867" alt="Screen Shot 2022-06-07 at 3 17 40 PM" src="https://user-images.githubusercontent.com/5403662/172464299-8cecadcf-22dc-41d2-8da1-bdd4bebbe40d.png">

If I instead open the URL, then copy the gif in Safari, it pastes in to Messages fine.

I use a clipboard manager (Pastebot) - I tried disabling that too, still same issue.
I closed/reopened Messages, no luck.

**Comment by josephschmitt** [comment]
Is the Raycast clipboard manager on? Maybe it's conflicting?

**Comment by JonLaliberte** [comment]
Raycast clipboard history is disabled.

Pasting in to Slack and this comment works fine.

![fallontonight-tonight-show-how-what-is-this-boqCITo4CpcRYJObHN](https://user-images.githubusercontent.com/5403662/172470315-76608132-f649-43a1-8b4d-640304fb7de0.gif)

**Comment by josephschmitt** [comment]
Weird. Wonder if it's a bug in Messages in macOS 11.

**Comment by JonLaliberte** [comment]
Seems to work fine on macOS 12 ... I tend to wait a few point releases before upgrading haha.
