### ISSUE TITLE
[YouTube] ...

### ISSUE THREAD

**Issue by Fritz7035** [raycast/extensions#1925]
# Extension – [YouTube](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/youtube/)
Author: @tonka3000

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.36.0

**Comment by mattisssa** [comment]
Please create a new Issue but don't forget to fill the template 😉
