### ISSUE TITLE
Snippets do not work in PHP Storm terminal window

### ISSUE THREAD

**Issue by aurawindsurfing** [raycast/extensions#1929]
# Extension – [Snippets](https://www.raycast.com/extensions/snippets/)

Author: Raycast

## Description

Snippet extension only works in the application main window. It does not apply if you open terminal within PHPStorm or probably any of the JestBrains apps.

## Steps To Reproduce

1. Open PHP Storm
2. Open Terminal with: Menu->Tool Windows->Terminal

## The current behavior

Not extending snippets

## The expected behavior

To extend snippets

### Raycast version

Version: 1.36.0

**Comment by aurawindsurfing** [comment]
bump - Snippets actually stopped working all together in PHPStorm... does anyone have the same issue?

**Comment by jaybhanushali3195** [comment]
Yes, it stopped working on all JetBrains products; I think. Not working in IntelliJ too!
