### ISSUE TITLE
[Zotero] Show author (and other information) in search result

### ISSUE THREAD

**Issue by robinhsi** [raycast/extensions#1933]
# Extension – [Zotero](https://github.com/raycast/extensions/tree/d356f51d3540c1fbeddad80d6806a6256eb1b4b8/extensions/zotero/)

Author: @sadanand-singh 

The Zotero extension now searches for author, but it would also be great if the search result screen could display the author name. This is the most relevant information missing, with other information such as Volume, Issue Number and Pages potentially also a nice addition.

Moreover, the publication date field often shows multiple dates (or rather the date in multiple formats), which could be fixed.

Finally, I was wondering if the shortcuts for the commands can be made customisable (e.g. make "Copy the Bibtex Citation Key" the default enter key option)?

These could be useful improvements to an already great extension!

**Comment by sadanand-singh** [comment]
Next PR will add authors in the main view. Other issues like Volume etc, are not that easily reliable and would need quite a lot of development time, hence personally I have not found adding them worth my time. 

Same goes for date format. Zotero really sucks at how it parses dates and it would really need a lot of coding to try to standardize it.

Shortcuts customization is a limitation of Raycast. Please file a feature request for the Raycast core feature separately.

**Comment by robinhsi** [comment]
> Next PR will add authors in the main view. Other issues like Volume etc, are not that easily reliable and would need quite a lot of development time, hence personally I have not found adding them worth my time.
> 
> Same goes for date format. Zotero really sucks at how it parses dates and it would really need a lot of coding to try to standardize it.
> 
> Shortcuts customization is a limitation of Raycast. Please file a feature request for the Raycast core feature separately.

Sounds great, thank you for your work

**Comment by realCrush** [comment]
> Next PR will add authors in the main view. Other issues like Volume etc, are not that easily reliable and would need quite a lot of development time, hence personally I have not found adding them worth my time. 
> 
> 
> 
> Same goes for date format. Zotero really sucks at how it parses dates and it would really need a lot of coding to try to standardize it.
> 
> 
> 
> Shortcuts customization is a limitation of Raycast. Please file a feature request for the Raycast core feature separately.

A small bug is that when I select "Open PDF", Raycast will always also open Zotero window and highlight that item, although it did open PDF at the same time. A little bit annoying, can you fix it if you have time? 😃

**Comment by robinhsi** [comment]
If I can add something, it would be useful to also have an option "Past Bibtex Citation Key to App" akin to Reference and Bibtex Entry.

**Comment by cyriltw** [comment]
> If I can add something, it would be useful to also have an option "Past Bibtex Citation Key to App" akin to Reference and Bibtex Entry.

old request, but any update on getting the citation key to show up?
