### ISSUE TITLE
[1Password] Extension showing items in search for empty vault

### ISSUE THREAD

**Issue by ShiftyMcCool** [raycast/extensions#1934]
# Extension – [1Password](https://github.com/raycast/extensions/tree/af49cfb0791337d66b1ab89b9f843554d02eb6da/extensions/1password/)
Author:

## Steps To Reproduce

1. Add multiple vaults to 1Password
2. Remove items from that vault
3. Items are still visible when searching via the extension

## The current behavior
Deleted items are still visible in search (sorry for all the blurring, this is a work account and client names are sometimes secret:
![image](https://user-images.githubusercontent.com/1320624/172632339-81b5e5a3-5740-456e-a52a-159874351388.png)
![image](https://user-images.githubusercontent.com/1320624/172634019-cfddaef9-d9b1-4554-87dd-773de318a595.png)

## The expected behavior
Deleted items should not appear in search

### Raycast version

v1.36.0

Let me know if you need more info.  The repro steps may not be exactly accurate as someone else on my team moved all items from the indicated vault to another so I'm not sure exactly how they did that.  All I know is that search is showing results for an empty vault (see screenshots)

EDIT: CLI is showing no results as well: 
![image](https://user-images.githubusercontent.com/1320624/172637617-132ae354-3ec1-4d57-b21a-e1dc2bd11178.png)

**Comment by ShiftyMcCool** [comment]
@pernielsentikaer any suggestions?  I'm still seeing old/removed entries and nothing I have tried will cause an update in the extension.  In fact, the entire vault has been renamed but still shows up as the old name.

**Comment by maarten00** [comment]
Same problem here. The items show up in the 'Recently deleted items' that can be found in the menu for the desktop app. Raycast should probably not be querying these items.

**Comment by pernielsentikaer** [comment]
That sounds like a bug to me, I can take a look within a few days if @dteare don't beat me 🙂

**Comment by pernielsentikaer** [comment]
I couldn't find a way to determine if the item was in the trash, is that possible @dteare

**Comment by khasbilegt** [comment]
Hello @pernielsentikaer. I am currently rewriting the extension utilizing the 1Password CLI 2 and this issue will be addressed in the new version. Thanks.

**Comment by pernielsentikaer** [comment]
Awesome 🎉

**Comment by ShiftyMcCool** [comment]
Just got a notification that this went stale.  This is just a comment to bump and ask about progress.  Thanks!
