### ISSUE TITLE
NPM extension keeps erroring: 'could not fetch packages'

### ISSUE THREAD

**Issue by waspeer** [raycast/extensions#1941]
# Extension – [NPM](https://github.com/raycast/extensions/tree/main/extensions/search-npm)

Author: Raycast

## Steps To Reproduce

1. Install NPM extension
2. Try to search for a package

My setup: Macbook pro m1 max, OS 12.4
(haven't been able to test it on other machines)

## The current behavior

An error shows: 'could not fetch packages'

## The expected behavior

Being able to search for packages

### Raycast version

Version: 1.36.0

**Comment by waspeer** [comment]
Same! It's a bit slow, but it's working again. Thanks for getting back!

**Comment by lafkpages** [comment]
Has been happening to me for the past month-ish now too

**Comment by lafkpages** [comment]
@MrMartineau bump 🙏
