### ISSUE TITLE
Bitwarden Send

### ISSUE THREAD

**Issue by gio8tisu** [raycast/extensions#1942]
# Extension – [Bitwarden](https://github.com/raycast/extensions/tree/main/extensions/bitwarden)

Authors: @PSalant726 , @pomdtr , @andreaselia 

It would be super nice to add a new command to manage [Bitwarden's Send feature](https://bitwarden.com/products/send/).
Send allows for securely sharing secrets to peers through a URL.

I have no experience developing raycast extensions, but if I have some guidance I would love to help.

Thanks!

**Comment by pomdtr** [comment]
Great idea!
You can take inspiration from this [example extension](https://developers.raycast.com/examples/doppler).

The bitwarden extension use the bitwarden cli behind the scene, the interaction between the cli and the extension is defined in the `api.ts`. Feel free to ping me on slack if you need help.

**Comment by PSalant726** [comment]
As a suggestion, if additional commands are going to be added to this extension then the extension's title should be changed to simply "Bitwarden", and the commands should be titled something like "Search Vault" and "Create Send" (or similar).

**Comment by pomdtr** [comment]
Sound's good.

We should have done it when we did merge the password generator.

**Comment by gio8tisu** [comment]
I've opened a PR with the Create Send functionality. It has room for improvement in terms of code structure and user input validation I guess. Let me know if you have some suggestions.
