### ISSUE TITLE
[Visual Studio Code - Project Manager] Fallback command

### ISSUE THREAD

**Issue by lforst** [raycast/extensions#1945]
# Extension – [Visual Studio Code - Project Manager](https://github.com/raycast/extensions/tree/01aca01489c2a293391f6ce92979d79ebe17e5a8/extensions/visual-studio-code-project-manager/)
Author: @MarkusLanger

Raycast has this concept of fallback commands - to search for stuff when it doesn't directly match a command. I think it would be awesome to have the raycast project manager extension work as a fallback command

**Describe the feature and the current behavior/state.**

Currently we cannot define the project manager search as a fallback command.

**Who will benefit with this feature?**

Everybody lol.

**Any Other info.**

I really like this extension!

**Comment by MarkusLanger** [comment]
Hi @lforst,
Thanks for the idea but at the moment it is not possible to support fallback commands from an extension. Only Quicklinks and Script Commands are supported. https://www.raycast.com/changelog/1-23-0

**Comment by lforst** [comment]
Ah sorry, I did not know that. thanks for taking a look and letting me know! Feel free to keep or close this as needed.
