### ISSUE TITLE
[Heroku] Adding logs view

### ISSUE THREAD

**Issue by frbuccoliero** [raycast/extensions#1949]
# Extension – [Heroku](https://github.com/raycast/extensions/tree/3170bc77e48cf72c5484acf218492f3405993b0d/extensions/heroku/)
Author: @Yukaii

I would like to suggest a little feature to add to the "Heroku" plugin: I would like to quickly check the logs for my apps directly from a Raycast view. 
Thanks a lot :)

**Comment by pernielsentikaer** [comment]
This should  now be included @frbuccoliero
