### ISSUE TITLE
[Toggl Track] ...text transformation to Japanese Bug

### ISSUE THREAD

**Issue by Akiyam-hub** [raycast/extensions#1959]
# Extension – [Toggl Track](https://github.com/raycast/extensions/tree/1891eb172e0bda146b4dc9dc95c3f3c0eb12ff15/extensions/toggl-track/)
Author:

## GIF 
![screencast 2022-06-11 15-52-59](https://user-images.githubusercontent.com/53425804/173177187-c9a95368-0f67-408b-9780-56a3d44d8799.gif)

## Description
I used  Input source **Japanese**  Extension **Toggl Track**  can time tracking **New Created a time entry** and
**Resume  Recent Time Entry** 
 I inputted text transformation to Japanese because of Search **Resume Recent Time Entry**
but Raycast's Interface did open **New Created a time entry** this instead of text transformation to Japanese.

## Steps To Reproduce

1. Changing the Input Source to  Japanese(Romaji)
2. Open Raycast Interface
3. Open command **Track Time**
4. I don't still **Created a new time entry**
5. I inputted  text and transformation to Japanese 
7. I didn't search "Recent Time Entry" because opened **New Created a time entry** Interface

## The current behavior

Can't Search **Resume Recent Time Entry**

### Raycast version
Raycast Version 1.36.0

**Comment by andreaselia** [comment]
Cc: @franzwilhelm as it didn't automatically add the extension author.

**Comment by Akiyam-hub** [comment]
P.S .
Show a notation of the key events.

If you go back to one of the new task creation screens, you will see that the converted characters have been entered.
![screencast 2022-06-12 07-17-27](https://user-images.githubusercontent.com/53425804/173206778-56009605-5255-481c-877e-c177ffd9bb1f.gif)

**Comment by aitaro** [comment]
It's happening on all extensions, not just Toggl Track.
It seems to be related to #1250.

**Comment by franzwilhelm** [comment]
Aha, so because of the enter keypress in the japanese transformer, toggl track detects it as enter to create new time entry? Unfortunately this is probably out of my control @aitaro ?
