### ISSUE TITLE
Code-Stash: Export Code Stash

### ISSUE THREAD

**Issue by timcastillogill** [raycast/extensions#1968]
# Extension – [Title](https://github.com/raycast/extensions/tree/main/extensions/*)

Author: [@ben-greenwood](https://github.com/raycast/extensions/commits?author=ben-greenwood)

**Describe the feature and the current behavior/state.**

Firstly, love the idea of having a code snippet library in Raycast 👍. 

The feature I would like to request is the ability to export all snippets from the extension for peace of mind (although I imagine they're being stored in a local .txt file?).

**Who will benefit from this feature?**

Anybody who wants to use this extension but know that it is simple to pull the data into another resource for whatever reason.

**Any Other info.**

**Comment by ben-greenwood** [comment]
Hey Tim,

Glad you are enjoying the extension!

I agree that an export function would be helpful, so i've built one into the next release - https://github.com/raycast/extensions/pull/2045

Thanks for the great suggestion!

**Comment by timcastillogill** [comment]
Hey Ben,

Amazing. Thanks for the great work!

Many thanks,

Tim
