### ISSUE TITLE
[Todoist] ...

### ISSUE THREAD

**Issue by PaulSwoogo** [raycast/extensions#1975]
# Extension – [Todoist](https://github.com/raycast/extensions/tree/d2cae3a2f1377968944ffbec9082c724541f70f9/extensions/todoist/)
Author: @thomaslombart

**Describe the feature and the current behavior/state.**
Option to mark todosist task as completed from Raycast

**Who will benefit with this feature?**
The whole reason of using shortcut is to ensure that I do not have to goto the app and adding this feature will allow me to not use Todoist app at all

**Any Other info.**

**Comment by thomaslombart** [comment]
Hi @PaulSwoogo, what do you mean by "Option to mark Todoist task as complete from Raycast"?

There's already this option with the shortcut `⌘` + `⇧` + `E`:

<img width="366" alt="CleanShot 2022-06-13 at 11 00 54@2x" src="https://user-images.githubusercontent.com/16003285/173318423-4854a6ed-7dbb-46c5-b510-847d576a5042.png">

**Comment by PaulSwoogo** [comment]
Sorry I meant - Asana

.

facebook ( https://www.facebook.com/TrySwoogo/ )

twitter ( https://twitter.com/swoogo )

linkedin ( https://www.linkedin.com/company/swoogo/ )

instagram ( https://www.instagram.com/swoogo/?hl=en )

( https://www.linkedin.com/company/swoogo/ ) We are hiring! ( https://swoogo.events/careers/ )

Thanks,
-------

Paul Singh [he/him]

-------------------

Team Lead, Account Management | PST Timezone

*Book a meeting* ( https://swoogo.chilipiper.com/book/me/paul-singh/all ) | +1.971.350.9990 ( tel:9713509990 ) | Linkedin ( http://www.linkedin.com/in/psinghpdx ) |

**Comment by thomaslombart** [comment]
It's also possible to mark a task as completed in Asana.

**Comment by PaulSwoogo** [comment]
I am a muppet - thank you so much

.

facebook ( https://www.facebook.com/TrySwoogo/ )

twitter ( https://twitter.com/swoogo )

linkedin ( https://www.linkedin.com/company/swoogo/ )

instagram ( https://www.instagram.com/swoogo/?hl=en )

( https://www.linkedin.com/company/swoogo/ ) We are hiring! ( https://swoogo.events/careers/ )

Thanks,
-------

Paul Singh [he/him]

-------------------

Team Lead, Account Management | PST Timezone

*Book a meeting* ( https://swoogo.chilipiper.com/book/me/paul-singh/all ) | +1.971.350.9990 ( tel:9713509990 ) | Linkedin ( http://www.linkedin.com/in/psinghpdx ) |
