### ISSUE TITLE
[Browser Bookmarks] ... Support search with Chinese keyword

### ISSUE THREAD

**Issue by ytqh** [raycast/extensions#1977]
# Extension – [Browser Bookmarks](https://github.com/raycast/native-extensions/tree/98807c71c6ec589775952a250d7225b403e995f5/extensions/browser-bookmarks/)
Author:

**Describe the feature and the current behavior/state.**
Support search with Chinese keyword

**Who will benefit with this feature?**
All Chinese Users

**Any Other info.**

**Comment by dehesa** [comment]
This has been fixed in release 1.43.0. For more information, check #3355.
