### ISSUE TITLE
[Slack] Support multiple workspaces

### ISSUE THREAD

**Issue by xiaogaozi** [raycast/extensions#2000]
# Extension – [Slack](https://github.com/raycast/extensions/tree/d3e045e1202b43a23bf38fddd89bf849135901b5/extensions/slack/)
Author:

**Describe the feature and the current behavior/state.**
Currently this extension only supports link with one Slack workspace, it will be very helpful if it could work with multiple workspaces.

**Who will benefit with this feature?**
Slack user who have joined multiple workspaces

**Any Other info.**

**Comment by joshmu** [comment]
Would love to see this too!
