### ISSUE TITLE
[Notion] Feature Req: Direct DB search

### ISSUE THREAD

**Issue by dimitrieh** [raycast/extensions#2017]
# Extension – [Notion](https://github.com/raycast/extensions/tree/065c88ef7d68d2c89467952cedf2ce527e50b0c2/extensions/notion/)
Author: @mathieudutour 

The notion Raycast extension is great! It allows me to search selected databases across my Notion. This is incredible! However, I would love to have the possibility to have my search command and scope be direct towards a specific database inside of my notion.

**Describe the feature and the current behavior/state.**

1. Open Raycast
2. Type name of specific Notion Database
3. See Raycast command with: [DB Icon] Search [DB Name]
4. Same functionality as default notion extension but results are scoped to the specific notion database.

<img width="522" alt="CleanShot 2022-06-16 at 19 39 04@2x" src="https://user-images.githubusercontent.com/429659/174132738-ab4289c5-93a4-439a-a6e6-e96e1ca478f7.png">

![CleanShot 2022-06-16 at 19 39 32@2x](https://user-images.githubusercontent.com/429659/174133150-5a692c52-2793-457a-b03a-cc63ec9dfcc4.png)

**Who will benefit with this feature?**

People who follow a second brain model inside of notion where they save things they often research new ideas with or have to recall themselves of something they have saved in a specific database. By being able to directly ask raycast to search in a specific database that mental connection becomes stronger.

**Any Other info.**

It would be great if the notion configured emoji that relates to the DB (if any) is used as an icon in Raycast!

**Comment by mathieudutour** [comment]
Unfortunately it's not yet possible to create "dynamic" commands.
You can search in a specific database when you select it in the "Search Notion" command tho. 
You could also fork the extension and hardcode the id with `queryDatabase` here: https://github.com/raycast/extensions/blob/main/extensions/notion/src/search-page.tsx#L20
