### ISSUE TITLE
[Easy Dictionary] ...

### ISSUE THREAD

**Issue by Kingmtu** [raycast/extensions#2026]
# Extension – [Easy Dictionary](https://github.com/raycast/extensions/tree/ceedc7844277cb42136dad4240687c5521dc7e0f/extensions/easydict/)
Author: @tisfeng

## Error: Error: read ECONNRESET

__node_internal_captureLargerStackTrace:errors:464:5
__node_internal_errnoException:errors:594:12
TLSWrap.onStreamRead:stream_base_commons:220:20
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.36.1

**Comment by tisfeng** [comment]
This error message looks like a node internal error,  Is there a more detailed error log? Or is there a recurrence condition?

**Comment by Kingmtu** [comment]
yes I reload the extension the problem is persistence,  I don't know how to take more detailed log
![Screen Shot 2022-06-18 at 12 55 51 PM](https://user-images.githubusercontent.com/55926032/174427621-06eb16c9-4ed3-4835-a4d2-0b06af97e794.png)
Error: read ECONNRESET

__node_internal_captureLargerStackTrace:errors:464:5
__node_internal_errnoException:errors:594:12
TLSWrap.onStreamRead:stream_base_commons:220:20

**Comment by tisfeng** [comment]
Is the above error information obtained through shortcut keys `cmd + K` ?

If you are a developer, you can try to download the extension repository locally, and then navigate to `Easydict` extension directory and `run npm install && npm run dev` in the terminal.  You can see more log information by debugging locally,  [refer here](https://developers.raycast.com/basics/create-your-first-extension#build-the-extension)

**Comment by tisfeng** [comment]
You can also try to uninstall the extension and reinstall it to see if the same problem still occurs. This may be a problem with the Raycast main program.

**Comment by tisfeng** [comment]
@pernielsentikaer  Could you please have a look at this question? I haven't seen this kind of error, and I don't know whether it is the internal error reported by the Raycast.

**Comment by Kingmtu** [comment]
Error: read ECONNRESET

__node_internal_captureLargerStackTrace:errors:464:5
__node_internal_errnoException:errors:594:12
TLSWrap.onStreamRead:stream_base_commons:220:20 
same error unfortunately
