### ISSUE TITLE
Grid Search Bar text is cleared when switching from List to Grid

### ISSUE THREAD

**Issue by yug2005** [raycast/extensions#2044]
Raycast version: 1.36.1

## Description

When the view switches from List to Grid, the search bar text is cleared. This is causing an issue for the YouTube extension as it goes from a list view for the recent searches to the grid view to show videos, channels...

This issue does not occur when the layout is set to list only. 

## Steps To Reproduce

1. Have a list view and search something
2. On search, change the view to a grid view. 

https://github.com/raycast/extensions/pull/2038#issuecomment-1160495628

## The current behavior

The search bar text clears when the view switches from list to grid. 

## The expected behavior

The search bar text should not clear.

**Comment by mathieudutour** [comment]
Hey @yug2005 

This behaviour is actually expected: you replace the component, there is no reason for it to keep the state from the previous component.

If you need to, you can listen to `onSearchTextChange` and pass the `searchText` yourself
