### ISSUE TITLE
[Notion] Not turning up pages

### ISSUE THREAD

**Issue by alper** [raycast/extensions#2049]
Hi,

The extension does not turn up pages in the workspace. I checked everything during authorisation.

Thanks,
Alper

**Comment by alper** [comment]
I reverted back to this because this one _is_ turning up all the pages that I regularly visit.

https://github.com/raycast/extensions/tree/main/extensions/search-notion

**Comment by mathieudutour** [comment]
Notion takes some time to give access to the pages as stated in their documentation: https://developers.notion.com/reference/post-search#limitations-of-search. It's a bit annoying but not much we can do on our side

**Comment by alper** [comment]
I mean that means it should display it now or? I reenabled the extension and it still does not turn up the page.

**Comment by alper** [comment]
Definitely some do show up but the ranking seems to be completely off or the pages I'm interested in don't. I'll try reinstalling and granting permissions, but I'm pretty sure that I checked everything.

The other Notion extension shows up exactly the pages I want properly ranked (say if I type the exact name, that page is the first in the list).
