### ISSUE TITLE
[Terminal Finder] Option to use other console app

### ISSUE THREAD

**Issue by mzamayias** [raycast/extensions#2059]
# Extension – [Terminal Finder](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/terminalfinder/)
Author: @yedongze

The idea and function behind the extension are great, albeit limited if the user doesn't prefer the Terminal or iTerm.

**Describe the feature and the current behavior/state.**

I am suggesting a third set of commands, `Finder -> Console` and `Console -> Finder`, where `Console` is a terminal application other than the (Apple's) Terminal or iTerm. The user should select their console app of preference in a Finder dialog, and the extension should remember their selection. Suggested interactions:

![TerminalFinderExtensionFeatureRequestDiagram](https://user-images.githubusercontent.com/29067825/174989070-5bfdb474-5e58-4e9d-bf40-09d13c3b817f.png)

The naming of the user-specified terminal app and the extension commands could change; it could be `Other Terminal App` instead of `Console`, for example. 

**Who will benefit with this feature?**

Users who don't use Terminal or iTerm, so let's say they are using Hyper. They won't use the extension unless they can utilise their favourite console application.

**Any Other info.**

**Comment by AaronDavidSchneider** [comment]
I didn't even know that people actually use different consoles other than terminal or iterm.

There is however an issue with your proposal: each console app (such as iterm or terminal) requires a different set of (AppleScript) commands for this extension to work. Looking at the source code of this extension, this also seems to be the case here.
