### ISSUE TITLE
[Text Decorator] ...

### ISSUE THREAD

**Issue by fturcheti** [raycast/extensions#2060]
# Extension – [Text Decorator](https://github.com/raycast/extensions/tree/f0f2a55293cca1ec5b3e29505f2bfcc1d813d96a/extensions/text-decorator/)
Author: @koinzhang 

## Description

The grid layout on "Decorate Text With Font" displays font previews in black. When using Raycast's dark theme, this results in low contrast and poor legibility.

<img width="750" alt="Screen Shot 2022-06-22 at 09 46 37" src="https://user-images.githubusercontent.com/365403/175032681-63fe2fde-667c-4bf5-9dd5-86b59547756d.png">

## Steps To Reproduce

1. Set Raycast to use the dark theme
2. Set "Decorate Text With Font" to use the grid layout
3. Invoke "Decorate Text With Font"

## The current behavior

Text on the grid layout is always black. 

## The expected behavior

When using Raycast's dark theme, text on the grid layout should be white. 

### Raycast version

1.36.1

**Comment by koinzhang** [comment]
Hi @fturcheti . Thank you for your feedback. I have reproduced the problem and fixed it in [PR#2063](https://github.com/raycast/extensions/pull/2063). The text in Grid layout is now displayed in white in dark mode.
<img width="1000" alt="Metadata" src="https://user-images.githubusercontent.com/36128970/175052504-3fc0c850-48b5-4ab7-852d-76c2d45d8f01.png">
