### ISSUE TITLE
[Formula 1] ...

### ISSUE THREAD

**Issue by gentlice** [raycast/extensions#2068]
# Extension – [Formula 1](https://github.com/raycast/extensions/tree/e7a90a65f0704fae074e64193cb9aff2828fca90/extensions/f1-standings/)
Author:

## Description
i'm getting errors for every Formula1 extension message "Error - Could not load seasons"
## Steps To Reproduce

1. Open Raycast
2. chouse Race Schedule (or any other command)3. 

## The current behavior
Under the Raycast i can see the Error only

## The expected behavior
See the schedule

### Raycast version

1.36.1

**Comment by pernielsentikaer** [comment]
Hi @gentlice 👋 

I was not possible to reproduce the issue here, are you on our [Slack](https://www.raycast.com/community) then I'd love to debug the issue with you 🙂
