### ISSUE TITLE
[Visual Studio Code Recent Projects] not working with vscode 1.68.1

### ISSUE THREAD

**Issue by zebapy** [raycast/extensions#2075]
# Extension – [Visual Studio Code Recent Projects](https://github.com/raycast/extensions/tree/6cf2be11613d7bdbfdd748d0a599e738edf99bd7/extensions/visual-studio-code-recent-projects/)
Author: @thomaspaulmann

## Steps To Reproduce

1. upgrade vscode to 1.68.1
2. try to use vscode recent projects raycast command

## The current behavior
nothing loads, raycast just shows loading indicator line

https://user-images.githubusercontent.com/2199845/175325716-92005212-3519-4369-9145-81c7505605d8.mov

## The expected behavior
should see list of my recently opened projects

### Raycast version
Version: 1.36.1

**Comment by zebapy** [comment]
my version says last updated 4 weeks ago. Opening the store doesn't visually do anything (maybe it tries update in background?)

I also just uninstalled it and reinstalled the ext and still seeing same result :(

**Comment by zebapy** [comment]
Not sure what changed but it's working now

**Comment by thomaspaulmann** [comment]
Oh okay... Weird indeed but happy that it get resolved. Let me know if something causes it again.
