### ISSUE TITLE
[Extension Feature Request] Todoist Create Task Menu Improvements

### ISSUE THREAD

**Issue by SmashMineGame** [raycast/extensions#208]
## Extension – [Todoist](https://github.com/raycast/extensions/tree/main/extensions/todoist)
**Author**: @thomaslombart 

## Describe the feature and the current behavior/state.
The Create Task menu stays as-is when a task is created. The form does clear, nor does it send you to a different page when it's submitted.

## Will this change the current api? How?
I suggest that once the task is created the project view for the task's selected project should open. There can also be a CMD-k menu option that doesn't open the project view and instead creates the task and clears the form.

## Who will benefit from this feature?
Anyone using the Todoist Raycast integration to add tasks.

**Comment by mattisssa** [comment]
Hey @thomaslombart! 
Here is the new feature request to your extension, take a look at that and subscribe to don't miss anything related 😉

**Comment by thomaslombart** [comment]
Thanks for letting me know. I'll take a look at it during the week! 🙂

**Comment by thomaslombart** [comment]
@SmashMineGame Just wanted to let you know that I'm updating the Todoist extension with your requested features. I expect to create a new pull request by the end of the week 🙂
