### ISSUE TITLE
[Music] Could not get your playlists.

### ISSUE THREAD

**Issue by jokerekv2** [raycast/extensions#2086]
# Extension – [Music](https://github.com/raycast/extensions/tree/87dd060b3b09fc49bed867b4b1e2a91232914ea3/extensions/music/)
Author:

## Description
There is no connect to apple music app. For example, an attempt to play a playlist causes the appearance of the message "Could not get your playlists."
## Steps To Reproduce

1. Launch raycast
2. Start Playlist

## The current behavior
Message: Could not get your playlists.

## The expected behavior
A playlist should play.

### Raycast version
1.36.1

**Comment by gstvds** [comment]
Did you have your Music app running when this happened? Or was it in quit mode?

I tried to run the command while the app was in quit mode and could reproduce this error. However, this didn't happen when the app was already running.

I think this happens because AppleScript can't load your playlists when the app is closed.

**Comment by jokerekv2** [comment]
In my case it happens even when the Music app is open..

**Comment by jokerekv2** [comment]
None of the commands in this extension work 😬

**Comment by gstvds** [comment]
Can you confirm Raycast has access to your Music app?
Under **System Preferences** > **Security & Privacy** > **Privacy** > **Automation**. You should have something like this:
![Captura de Tela 2022-06-26 às 12 59 01](https://user-images.githubusercontent.com/53450202/175822990-ffc1271a-d683-455b-be7d-7fe82d252424.png)

**Comment by jokerekv2** [comment]
Ok... that was the problem. Thanks a lot for solving it. I've been using mac os for a while now and honestly didn't get the idea that there could be such a setting there.
