### ISSUE TITLE
[Cleanshot X] ...

### ISSUE THREAD

**Issue by mageshyt** [raycast/extensions#2094]
# Extension – [Cleanshot X](https://github.com/raycast/extensions/tree/4e690dc9277a0b691b08aab147c97448167eb2ff/extensions/cleanshotx/)
Author:

**Describe the feature and the current behavior/state.**
the extension is not working please check it out. in order  to use cleanshort x , i have to buy its subscription ?  
**Who will benefit with this feature?**

**Any Other info.**

**Comment by andreaselia** [comment]
The Raycast extension essentially calls commands for the Cleanshot X application.

Just as you would need a Cleanshot X license to use the app, you will need one to use the extension.

You can purchase a license here: https://cleanshot.com/

Remember, it is only a subscription if you want app updates after 1 year, you can always avoid updating the app after 1 year and keep the app as it is.

**Comment by koinzhang** [comment]
If it is possible to add a pre-check for the extension is the best way @Aayush9029

**Comment by Aayush9029** [comment]
I personally think it's not that important for "app installed" check! If you feel like that'd be helpful to new users PRs are welcome 🤗 

*The name should be enough imo*, again PRs are welcome 🙏
