### ISSUE TITLE
[OBS Control] Start virtual camera

### ISSUE THREAD

**Issue by lukasoppermann** [raycast/extensions#2097]
# Extension – [OBS Control](https://github.com/raycast/extensions/tree/0a769bb418cc08249cac739a5d3199c289941d62/extensions/obs-control/)
Author:

It would be great if the plugin would have a command to toggle (start or stop) the virtual camera as well.

**Describe the feature and the current behavior/state.**
Currently the plugin only toggles the stream

However I always use the virtual camera so adding a command to toggle the virtual camera would be great.

**Who will benefit with this feature?**

People who use obs in other ways. e.g. for video conferences were an external camera input is fed through obs and then into ms teasm, slack, etc.

**Any Other info.**
The obs-cli supports this feature, so I think it should be available.

**Comment by lukasoppermann** [comment]
@pernielsentikaer any chance of this being added?

**Comment by pernielsentikaer** [comment]
I think we have to ask @Yukaii as the author if he could look into this 🙂 I'm not really into OBS myself 🫤

**Comment by lukasoppermann** [comment]
It should be pretty straight forward to do. So we need @Yukaii to react? I am happy to send a PR to add this feature.

**Comment by pernielsentikaer** [comment]
Well, @Yukaii is the author which needs to accept the incoming PRs but it seems like a good feature, I don't see a problem making it better 🙂
