### ISSUE TITLE
[Figma File Search] Treat hyphen in file name as space

### ISSUE THREAD

**Issue by sahilk** [raycast/extensions#2098]
# Extension – [Figma File Search](https://github.com/raycast/extensions/tree/1da89c4626dd39b3c50a12208ee14c816f918ae8/extensions/figma-files/)
Author: @michaelwschultz

## Description

Treat hyphens and other common file name separators as spaces. "abc-xyz" is not searchable against "abc xyz" currently.

## The current behavior
"abc xyz" shows no results when "abc-xyz" as a file exists

## The expected behavior
show "abc-xyz" as well in results

### Raycast version
Version: 1.36.1

**Comment by michaelwschultz** [comment]
Great suggestion @sahilk!
