### ISSUE TITLE
Add option to insert time before a quick note - [Logseq](https://github.com/raycast/extensions/tree/main/extensions/logseq)

### ISSUE THREAD

**Issue by hphoeksma** [raycast/extensions#2111]
# Extension – [Logseq](https://github.com/raycast/extensions/tree/main/extensions/logseq)

Author: @futantan 

**Describe the feature and the current behavior/state.**
Option to add a leading text before the insertion automatically. Like the current time stamp.

**Who will benefit from this feature?**
People who are using this to do interstitial journaling.

**Any Other info.**
For example my journals start with `**HH:mm** – [TEXT HERE]`

**Comment by futantan** [comment]
#1445 
I will work on this in the following days when available

**Comment by futantan** [comment]
Thanks for your feedback @hphoeksma :D

**Comment by futantan** [comment]
![CleanShot 2022-07-23 at 10 13 04](https://user-images.githubusercontent.com/6268441/180586712-16314005-cf04-4df8-9364-ebbb881e3f13.png)

https://user-images.githubusercontent.com/6268441/180586717-bb9495c0-fe67-450f-9834-33e5ee7e20a0.mp4

hi @hphoeksma Please review and let me know if this is what you want

**Comment by alphatroya** [comment]
Maybe an option to add a custom tag like #[[quick capture]] (like in mobile version of logseq) will be also appropriate?

**Comment by futantan** [comment]
Sounds great! Will add it!

**Comment by futantan** [comment]
Feature added! @alphatroya

**Comment by hphoeksma** [comment]
@futantan cool :-) Maybe it would be nice for people to be able to set up their own template as a prefix in which they can substitute a date variable. So they can make it bolded, at an emoji in front of it (as I have some people do). Many people - many different formats. So if it would be an input field where you could configure this - that would be more versatile.

`**{dd.mm}** -` becomes: **10.15** - Text here
`{dd:mm} -` becomes: **10:15** - Text here
`⏲️ {dd:mm}` becomes:  ⏲️ 10:15 Text here

Here I use `{` brackets as template tag - but whatever is possible would be fine.

I am happy as it is - but just an idea.

Thanks 👍

**Comment by galligan** [comment]
@hphoeksma would love to see this templatable too!

**Comment by feigaoxyz** [comment]
As Logseq has added [Logseq Protocol](https://docs.logseq.com/#/page/Logseq%20Protocol) for quick capture with customised format, will this ext consider following it?

**Comment by futantan** [comment]
hey @feigaoxyz great feedback, I will work on this soon!
