### ISSUE TITLE
Bitwarden password generator bug stuck in input

### ISSUE THREAD

**Issue by AaronDavidSchneider** [raycast/extensions#2113]
# Extension – [Bitwarden](https://github.com/raycast/extensions/tree/main/extensions/bitwarden)

Author: @pomdtr 

## Description

Since there is a limited range of possible values for the length of passwords in Bitwarden, I am not able to change the field (input will be disregarded) for certain inputs.

## Steps To Reproduce
<img width="1000" alt="Metadata" src="https://user-images.githubusercontent.com/7556347/176180822-213784a6-5c29-4fe4-a646-30e85cc78c40.png">

1. Open generate password
2. change length of password to e.g. 21
3. congrats: You are stuck there 

## The current behavior

Inputs are checked during typing

## The expected behavior

Inputs should be checked for validity after stuff is typed

### Raycast version

Version: 1.36.1

**Comment by pomdtr** [comment]
@jomifepe do you have time to take a look at this ?

**Comment by jomifepe** [comment]
> @jomifepe do you have time to take a look at this ?

Yeah sure, I'll take a look
