### ISSUE TITLE
Provide Form.IconList and Form.Icon to display image

### ISSUE THREAD

**Issue by koinzhang** [raycast/extensions#2115]
Provide `Form.IconList` and `Form.Icon` in `Form` to display image, as shown in the code below.

```   
<Form.IconList title={"Form.IconList"}>
        <Form.IconList.Icon source={icon1} />
        <Form.IconList.Icon source={icon2} />
        <Form.IconList.Icon source={icon3} />
</Form.IconList>
```

**Describe the feature and the current behavior/state.**

<img src="https://user-images.githubusercontent.com/36128970/176230614-03509d22-bad7-42bf-b2fb-2cbedb601ec1.png" height="150"/>

**Will this change the current API? How?**

Yes. A new component api will be added to the `Form`

**Who will benefit from this feature?**

People who show and browse pictures in Form

**Any Other info.**

**Comment by mattisssa** [comment]
It's not really clear to me what this item will be used for. 
Is it a file picker? Or is it a simple non-clickable item where you want to display an image? 
Do we have something like that somehwere else in Raycast?
