### ISSUE TITLE
Set Default Skin Tone for Emoji Extension

### ISSUE THREAD

**Issue by skeskali** [raycast/extensions#2120]
# Extension – [Emoji](https://www.raycast.com/FezVrasta/emoji)

Author: @FezVrasta 

**Describe the feature and the current behavior/state.**
The feature would make it possible for people to set a default skin tone for Emoji. This feature is available in LaunchBar, and I would love to see it in Raycast. 

**Who will benefit from this feature?**
Anyone who wants to/thinks its important to have emoji that represent their ethnic identity

**Any Other info.**
N/A

**Comment by koinzhang** [comment]
Hi @skeskali. Have you tried Raycast's built-in Search Emoji command, which allows you to set Emoji Skin Tone, just select Skin Tone in Preferences - Advanced - Emoji Skin Tone.
<img width="862" alt="截屏2022-06-29 10 08 57" src="https://user-images.githubusercontent.com/36128970/176335885-58a23ae5-a325-4799-887b-574fbae57174.png">
<img width="1112" alt="截屏2022-06-29 10 09 12" src="https://user-images.githubusercontent.com/36128970/176335895-e03b247a-5a5b-4494-ac18-2490bd358d80.png">

**Comment by skeskali** [comment]
I didn't know about this feature! Thank you so much!

**Comment by eatstorming** [comment]
Sorry to post here, I think it makes more sense than creating a new issue.

There seems to be a bug with the built-in emoji search: it correctly finds the emoji with the assigned skin tone when I search for it, but it is added to the Frequently Used list with the default (?) yellow skin tone, and clicking on the emoji there will paste it with that tone (yellow) instead the one selected in the Preferences.

![image](https://user-images.githubusercontent.com/20144145/188797548-b9ba190e-eed7-462a-b277-935390bf0639.png)
![image](https://user-images.githubusercontent.com/20144145/188797661-dbe81181-2d28-46e1-b6b4-d7db18250785.png)
![image](https://user-images.githubusercontent.com/20144145/188797742-b928f758-3b88-4278-80eb-efeebd909c7f.png)
![image](https://user-images.githubusercontent.com/20144145/188797795-1d499ab5-5cc0-4162-a646-8be39884a872.png)
![image](https://user-images.githubusercontent.com/20144145/188797925-2568777d-5878-4ae7-87cf-58b8fa25231a.png)
