### ISSUE TITLE
[Dribbble] Fine Tuning

### ISSUE THREAD

**Issue by felixludwig1** [raycast/extensions#2131]
# Extension – [Dribbble](https://github.com/raycast/extensions/tree/4bb67b62e76c2cfc600fe003b93677c8fefe0cbe/extensions/dribbble/)
Author: @gebeto

Hey, really appreciate that you took the time to create a Dribbble Extension! Really dig it and could see me using this on a daily base.

If you don't mind, I got some small ideas to make the extension even better:

- Having a way to fix the Filter, to always initially show a user specified category (maybe just somewhere under "configure extension". I know that you can use CMD+P but it's taking its time and some Filter are named the same ("all"). For me the recent shots are really not that interesting compared to
- Seeing the shots of people you follow. Could make the whole thing way more complicated I guess, but would be my top feature
- Each tile could have the dimension 4:3 instead of being squared to fit the Dribbble shot dimension and look better :) 

Thanks for the extension again! Hope this doesn't annoy.

**Comment by andreaselia** [comment]
Hey @gebeto,

You'd be able to achieve the authenticated state by using [OAuth](https://developers.raycast.com/api-reference/oauth), which will redirect the user to Dribbble and then back to Raycast once they authorize the application. This would allow you to list shots, projects, etc. in a lot more detail for the authenticated user, as well as their teams etc.
