### ISSUE TITLE
[Brew] Upgrade commands failing to execute

### ISSUE THREAD

**Issue by 1activegeek** [raycast/extensions#2138]
# Extension – [Brew](https://github.com/raycast/extensions/tree/c857437cb85229cc3e11177172ea408b8e03afa1/extensions/brew/)
Author: @nhojb 

## Description
Upgrades are failing for any installed app I try to update with Home-brew.
## Steps To Reproduce

1. Use the "brew" command in Raycast. 
2. Select the Show Outdated option. 
3. Choose to upgrade the outdated app
4. Error shown and action not taken

```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
Error: blockblock: Failure while executing; `/usr/bin/sudo -E -- /opt/homebrew/Caskroom/blockblock/2.0.5/BlockBlock\ Installer.app/Contents/MacOS/BlockBlock\ Installer -uninstall` exited with 1. Here's the output:
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```

## The current behavior
The actions that require Sudo, are failing.

## The expected behavior
The actions that require Sudo, would work successfully.

### Raycast version

1.36.1

**Comment by 1activegeek** [comment]
Checking in here - anything I can do @nhojb? Any other information needed. Or am I missing something obvious for enabling this?

**Comment by nhojb** [comment]
Thanks for reporting the issue. In most cases brew is designed not to require `sudo`. Do you know why it is required in this case? Looks like it's running an uninstall operation for some app?

It looks like we can force `sudo` to prompt the user for their password setting the `SUDO_ASKPASS` environment variable in the extension. I'll have a look into this.

**Comment by 1activegeek** [comment]
Updating with context from the Slack chat in case others are searching.

It seems that not ALL requests are requiring SUDO, but when they do, it's failing as there is no prompt. Specifically the issue I hit this with was with 1Password, I've since updated it already out of band so it was no longer a culprit. Here I have an example though of attempting to update the out of data LuLu package. Output from a standard Homebrew upgrade of the package at the command line for context:

```
user@machine % brew upgrade lulu
==> Upgrading 1 outdated package:
lulu 2.4.1 -> 2.4.2
==> Upgrading lulu
==> Downloading https://github.com/objective-see/LuLu/releases/download/v2.4.2/LuLu_2.4.2.dmg
Already downloaded: /Users/username/Library/Caches/Homebrew/downloads/bcc9111bf9e312f22d7221d864fd632b4610e7ff5c2579ea6674806ef89cb0b0--LuLu_2.4.2.dmg
==> Running uninstall script /Applications/LuLu.app/Contents/Resources/LuLu Uninstaller.app/Contents/MacOS/LuLu Uninstaller
Password:
```

In this case it is asking for the sudo password as it needs more permissions. I'd imagine there are quite a many packages like this that will require higher permissions for certain actions in the installation, removal, or update processes. 

Your mention of the variable sounds workable. Please let me know if I can test it out for you with an unofficial build at all. Happy to leave some outdated packages as is for right now to ensure I can validate it works. 

Appreciate the work you've done so far - this is going to be a really nice addition to my standard uses. Love it!!

**Comment by 1activegeek** [comment]
Awesome work!! Thank you so much - I'll check this out when I get back home and play around with it.
