### ISSUE TITLE
[Quicklink] Stopped working since updated chrome

### ISSUE THREAD

**Issue by obregonia1** [raycast/extensions#2140]
Raycast version:
1.36.1
## Description
Quicklink stopped working since updated chrome latest version
## Steps To Reproduce

1. Google Chrome update to `103.0.5060.53（Official Build） （arm64）`
2. Run quicklink

## The current behavior
Do nothing.
## The expected behavior
Open specified link.

**Comment by mattisssa** [comment]
Hey! Thanks for the report, we will take a look at that. 

One thing for the future – Quicklinks is part of the native land that doesn't related to the API. For the native land issues we have command **Send Feedback** that suits it better 😉

**Comment by obregonia1** [comment]
@mattisssa 
Thank you for comment. I noticed that this problem cause by chrome side.

**Comment by mattisssa** [comment]
> @mattisssa
> Thank you for comment. I noticed that this problem cause by chrome side.

Ah, alright. Thanks for the update 👍
