### ISSUE TITLE
JetBrains extension add more hotkey

### ISSUE THREAD

**Issue by HarryWang29** [raycast/extensions#2144]
# Extension - [JetBrains](https://github.com/raycast/extensions/blob/c614a2dfc24aad9174e55bacc6053238781d77a7/extensions/jetbrains/README.md)

Author: @gdsmith 

I'd like to set different hotkey for the tools of jetbrains.
for example option+cmd+g for goland, option+cmd+i for idea...

**Describe the feature and the current behavior/state.**
![image](https://user-images.githubusercontent.com/8288067/176641759-8ce67d51-8789-4e07-8b0d-464ae838062c.png)
I can just set one hotkey for JetBrains extension
**Who will benefit from this feature?**

**Any Other info.**

**Comment by gdsmith** [comment]
Hey Harry, I don't think there is a way to do this. The only thing I can think of is to add multiple commands for each of the JetBrains toolbox apps, but there is a lot and most people would then have commands they don't want/need. @pernielsentikaer do you have any thoughts on this? Is there a way to ship with commands available but disabled?

Can you give a bit more information as to why the list as is doesn't work well for you?

If it helps with your issue, here's what you can do:

* filter the tools using ⌘+P
* favourite projects using ⌘+F
* choose the sort order of the tools using ⌃+S
* jump between tools using ⌘+⬇️
