### ISSUE TITLE
Add more favorite / star icons

### ISSUE THREAD

**Issue by lukasoppermann** [raycast/extensions#2163]
Please add the "remove from favorite", "move favorite up" and "move favorite down" icons into the Icon component.

**Describe the feature and the current behavior/state.**
Currently only "Icon.star" is supported. 
3 icons would be added to the component.

**Will this change the current API? How?**
Not really, just add to it.

**Who will benefit from this feature?**
Anybody who uses favorites in their extension.

**Comment by mattisssa** [comment]
@mathieudutour Can you please clarify if we already introduced these icons to the API or it's still available internally only?

**Comment by mathieudutour** [comment]
All the new icons have been released with the redesign on 1.38.0.

We are not planning to add more icons for the time being, if you need a custom one, you can always use an SVG.
