### ISSUE TITLE
[Shell] Execute in iTerm: new session

### ISSUE THREAD

**Issue by robertvanhoesel** [raycast/extensions#2166]
# Extension – [Shell](https://github.com/raycast/extensions/tree/745611824d83b50ea87283344c63bf55ad1d169f/extensions/shell/)
Author:  @KELiON 

**Describe the feature and the current behavior/state.**
Execute in iTerm.app enters the command in the front-most/active session or tab. Without having the app open there is no way to know in which tab the command will be made, including maybe remote connections, containers or other sessions.

Ideally, it would open a blank tab or window.

**Who will benefit with this feature?**
Developers that have as many tabs open in iTerm as they have in Chrome.

**Comment by KELiON** [comment]
Good point, @robertvanhoesel! I've fixed it in #2848 and now if iTerm is already running, this command opens new tab.
