### ISSUE TITLE
[Shell] Allow running commands directly by prefixing them with `$ `

### ISSUE THREAD

**Issue by essenciary** [raycast/extensions#2183]
# Extension – [Shell](https://github.com/raycast/extensions/tree/745611824d83b50ea87283344c63bf55ad1d169f/extensions/shell/)
Author:

**Describe the feature and the current behavior/state.**
Right now you have to type "shell", select the "execute shell command" option, then type the actual shell command.

**Who will benefit with this feature?**
All the users

**Any Other info.**
Nope

**Comment by LeeBuckle** [comment]
Have you tried setting an alias?

When the search is an exact match for a user defined alias, hitting `space` will trigger that command. Quicklinks and some extensions trigger an additional input within the same search field. This behaviour is really nice for getting things done quick. E.g. `<cmd+space>g search input<enter>` is something I probably use 100 times per day to search google.

https://user-images.githubusercontent.com/80564456/178147028-be659359-a060-443a-b24e-f02179d17ae3.mp4

**Comment by essenciary** [comment]
Oh, that's cool, thanks for the tip!
