### ISSUE TITLE
[Linear] User cannot specify a project for an issue

### ISSUE THREAD

**Issue by huangsemao** [raycast/extensions#2201]
# Extension – [Linear](https://github.com/raycast/native-extensions/tree/0326feb025831e8c994758d8c54008bf62fa0807/extensions/linear/)
Author: @imthath-m

<img width="505" alt="Screenshot 2022-07-07 at 16 54 06" src="https://user-images.githubusercontent.com/3541426/177791842-dbff59fb-3c7f-4095-97b3-a026d55edf2e.png">

<img width="380" alt="Screenshot 2022-07-07 at 16 56 03" src="https://user-images.githubusercontent.com/3541426/177792901-5c8518cb-06aa-461a-a2cb-3d837ad221eb.png">

## Description
Impossible to specify a project at the time of issue creation or change it later

## Steps To Reproduce

1. Run **Create Issue** command 
2. Project field is disabled 
---

1. Run **Created Issue** command
2. Press Command+K and select **Set Project**
3. Extension shows error - Couldn't load data: HTTP response received with error

### Raycast version
1.37.1

**Comment by thomaslombart** [comment]
It seems this issue is related to the deprecated native extension. @pernielsentikaer should it be closed?

**Comment by pernielsentikaer** [comment]
Hi @huangsemao 👋 

It looks like you're using the deprecated version of the Linear extension, could you first try to check this in the preferences:
<img width="789" alt="CleanShot 2022-08-19 at 12 40 58@2x" src="https://user-images.githubusercontent.com/38033107/185601698-6eed6f0b-7083-4055-b38d-eb1eb480c66a.png">

If you're using that one, uninstall and install the right one:
![CleanShot 2022-08-19 at 12 41 44@2x](https://user-images.githubusercontent.com/38033107/185601787-6f311a8a-8d64-48ee-8fcb-d4ccb49d4f3f.png)

Could you make sure and get back if you're still facing the issue?

**Comment by huangsemao** [comment]
This issue was created for a deprecated extension when it was not deprecated. Everyting is fine with new extension. I think this issue can be closed
