### ISSUE TITLE
Full featured Raindrop.io extension (new extension suggestion)

### ISSUE THREAD

**Issue by aiotter** [raycast/extensions#2203]
# Extension – [Raindrop.io](https://github.com/raycast/extensions/tree/7c19be06ffd759fb5d7fb9d713e3ea580ea1d193/extensions/raindrop/)

Author: @lardissone

**Describe the feature and the current behavior/state.**
I want to add these new features:
- Use OAuth2 instead of the current Bearer token.
- Show detailed bookmark preview instead of only the title and the favicon.
- Add an access to the permanent copy of the bookmarked page (premium feature of raindrop.io)

**Who will benefit from this feature?**
Raindrop.io users

**Any Other info.**
The biggest problem is the huge number of changes. And the change in authentication method can break the other people's workflows. So I'm planning to create a new extension.

The fundamental objective of the extension is the same as the current extension. Will the new extension get accepted? How should I name it?

**Comment by mathieudutour** [comment]
> And the change in authentication method can break the other people's workflows. So I'm planning to create a new extension.

Not necessarily. For the Notion extension we support both: if the token is set (eg. old users), use that - otherwise use oauth

**Comment by lardissone** [comment]
Interesting suggestions!

I will work on OAuth support (didn't noticed Raycast added support for it).
And then I can work on detail view.

**Comment by lardissone** [comment]
@aiotter @mathieudutour I just noticed that Raindrop API only [supports](https://developer.raindrop.io/v1/authentication/token#step-3-the-token-exchange) authentication using `client_secret`. Not sure if there's a way already in Raycast to do requests to non-PKCE APIs or if there's another way to implement it.

**Comment by mathieudutour** [comment]
You can use a PKCE proxy: https://github.com/mathieudutour/pkce-proxy

**Comment by aiotter** [comment]
Wait, I didn't mean I want all those features to be implemented by @lardissone alone. If you're ready to check PR, I can add an detailed preview for my first step. Or do you already have a good idea about implementing it?

**Comment by lardissone** [comment]
@mathieudutour that would be great! I've been asking Raindrop support if they plans to add PKCE support anytime soon.

@aiotter I had been working on upgrade to Detail view, still requires some tuning but this is what I have:

https://user-images.githubusercontent.com/59826/178020288-462beda0-f4a7-438d-b0de-dfa355f82621.mp4

**Comment by aiotter** [comment]
Okay, I opened this issue for a purpose of my contribution, but if you want to do all the things by yourself keep going. I'll keep this issue open.
Please ask maintainers to close it when you don't need it anymore.

**Comment by lardissone** [comment]
@aiotter Sure. Feel free to contribute! I just had something already made on my computer but not yet released/finished and wanted to show you the status. 
Let me know if you like this way I can push this to my fork so you can review it before releasing it here.
