### ISSUE TITLE
[Cloudflare] Cache - Purge Everything

### ISSUE THREAD

**Issue by matt08** [raycast/extensions#2207]
# Extension – [Cloudflare](https://github.com/raycast/extensions/tree/main/extensions/cloudflare)

Author: @Destiner @niklaswa 

**Describe the feature and the current behavior/state.**
I request to add also "Purge Everything" option on every website instead only "Purge files from cache by URL". It's an often used option.

**Who will benefit from this feature?**
Any Cloudflare users :)

**Comment by adamcnaglich** [comment]
Shouldn't this made to be possible from the site details, not just the site selection screen? I had trouble finding it.
