### ISSUE TITLE
[Hypersonic] Using pre-exisiting databases with different field names.

### ISSUE THREAD

**Issue by mimansajaiswal** [raycast/extensions#2239]
# Extension – [Hypersonic](https://github.com/raycast/extensions/tree/54abe3c1e20f12a8a32709fc2276627478075cad/extensions/hypersonic/)
Author: @prrrcl

**Describe the feature and the current behavior/state.**
Map date, title and label to another property name for an already existing database in notion

**Who will benefit with this feature?**
Anyone who doesn't want to/cannot port over their complete todo setup to hypersonic template.

**Any Other info.**

**Comment by mimansajaiswal** [comment]
I don't know how to go about this, but I did modify the extension to have these preferences and be able to attach to custom databases. Is there anyway to have a pull request to submit possible modifications/upgrades to an extension made by someone else?

**Comment by danielsequeira** [comment]
yes there is @mimansajaiswal, all the extensions are part of this repo and open-source. you can go ahead and add these improvements yourself and create a PR for it.

**Comment by mimansajaiswal** [comment]
@prrrcl @igarcido95  I checked out your pull request branch and imported the extension. The filter option and changing property names works perfectly. Thank you.
