### ISSUE TITLE
[weather] Emojis for night weather.

### ISSUE THREAD

**Issue by brightonjack** [raycast/extensions#2241]
Currently, when the weather is "clear" in the evening, the extension shows it as "clear" in the evening however it has the "sun" emoji. It might make sense to have the extension show the moon emoji for clear weather in the evening.

It might be even better if the extension knew what the moon phase is for the given location, so it shows the right moon phase emoji, but I guess it's too much to ask :)
<img width="862" alt="Screenshot 2022-07-12 at 12 27 03" src="https://user-images.githubusercontent.com/937551/178469894-b39628e1-ee03-4f3f-8c4b-d48ad29c066c.png">

**Comment by danielsequeira** [comment]
@brightonjack you are referring to this extension: https://www.raycast.com/tonka3000/weather right?

**Comment by brightonjack** [comment]
Yes, correct.

**Comment by danielsequeira** [comment]
@tonka3000 fyi

**Comment by tonka3000** [comment]
Good idea.
