### ISSUE TITLE
[massCode] Ability to create new snippet from clipboard or selection with a shortcut key

### ISSUE THREAD

**Issue by AlNotAlbert** [raycast/extensions#2249]
# Extension – [massCode](https://github.com/raycast/extensions/tree/378d1ad3e97a863caa940b690f1f8e8bad85bb6d/extensions/masscode-assistant/)
Author:

ability to save a selection / clipboard into a new snippet form on masscode from using a shortcut on raycast. 

**Describe the feature and the current behavior/state.**
Right now, all you can do is search your snippets on masscode, but you cannot create any from raycast.

**Who will benefit with this feature?**

It will convenient for those who already use masscode, to be able save their snippets on masscode from raycast and have more portability with  their snippets, rather then relying on raycast to store code, since its only for mac.

**Any Other info.**

Ability to see code syntax highlighting from the ray-cast preview will be highly appreciated.

**Comment by pernielsentikaer** [comment]
CC: @antonreshetov

**Comment by pernielsentikaer** [comment]
Are you still around @antonreshetov

**Comment by AlNotAlbert** [comment]
is there an api on the masscode to create snippets?

**Comment by pernielsentikaer** [comment]
@antonreshetov are you around?
