### ISSUE TITLE
[Music] 'Play Library Album' shows list of song results, instead of album results?

### ISSUE THREAD

**Issue by jesseleite** [raycast/extensions#2258]
# Extension – [Music](https://github.com/raycast/extensions/tree/main/extensions/music)

Author: @fedevitalede @Rawnly

## Description

When selecting command "Play Library Album", there seems to be no way to search for album names, and the results show song titles rather than album names.

## Steps To Reproduce

1. Select "Play Library Album"
2. Try to search by album name

## The current behavior

Shows song titles as results, cannot search by album title.

## The expected behavior

I would expect to see a list of album titles, not song titles. When selecting an album, I would expect it to start playing at the start of the album.

### Raycast version

Version: 1.37.1

**Comment by Rawnly** [comment]
Thanks for reporting! i'll take a look asap!
