### ISSUE TITLE
[Extension Feature Request] Allow input of path to folder in file search

### ISSUE THREAD

**Issue by tgreen7** [raycast/extensions#226]
I am not sure if there is already a way to do this.

**Describe the feature and the current behavior/state.**
If I want to go to the folder `lims/e2e-tests/fixtures` I can't put in that path. I can put in fixtures directly but that gives me results from different folders I do not care about

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**
It would be awesome if i could narrow down those results by inputting a path. Even better would be allowing a fuzzy path so i could just do `lims/fixtures` directly.

**Comment by mattisssa** [comment]
Hey @tgreen7! The extension has been recently updated, could you please check if your feature is already there? 
Or shall we probably mention the author?

**Comment by tgreen7** [comment]
@mattisssa this still does not work.

**Comment by mattisssa** [comment]
@tgreen7 we've updated templates including Extension Feature requests, in the new one there are fields to mention the author. 
Could you please mention the author of the extension in your description or as a comment so he could take a look at the request?

**Comment by tgreen7** [comment]
@mattisssa I don't think this is an extension. The file search function is top level. Where should I be posting an issue for that?

**Comment by mattisssa** [comment]
ouch @tgreen7, sorry, forgot to respond to you here. Yes, seems like I confused an existing extension in the Store, having this issue is fine. 

The path to a folder in File Search works for me, but for fuzzy search, we don't have any plans for now. 
@nhojb can correct me if I'm wrong

**Comment by nhojb** [comment]
Paths are not yet supported in File Search in the public version of Raycast (we're still testing it internally). Should be available soon for public consumption.

Fuzzy search is not supported ATM.
