### ISSUE TITLE
[Elgato Key Light] ...

### ISSUE THREAD

**Issue by seanrose** [raycast/extensions#2268]
# Extension – [Elgato Key Light](https://github.com/raycast/extensions/tree/4479d612107d01bc93466c2ce7049e8b6fa79bfe/extensions/elgato-key-light/)
Author: @thomaspaulmann

## Description

I have two key light airs connected, but the extension only toggles one. The Elgato control center app turns both on and off. I know the software/firmware of these things leaves a bit to be desired, so it's possible there's something wrong with them.

## Steps To Reproduce

- If I have "link accessory controls" enabled in Elgato control center, only one left will be toggled by the extension
-  If I have "link accessory controls" disabled in Elgato control center, the extension will alternate which light it toggles

## The current behavior
Extension toggles one of two connected lights

## The expected behavior
Extension toggles both connected lights

### Raycast version
Version: 1.37.1

**Comment by empalms** [comment]
Affecting me as well, though the cycle is somewhat unpredictable AFAICT

**Comment by thomaspaulmann** [comment]
I'm having an issue with the command and might look into it.
