### ISSUE TITLE
[Library Genesis] error searching for books

### ISSUE THREAD

**Issue by lardissone** [raycast/extensions#2269]
# Extension – [Library Genesis](https://github.com/raycast/extensions/tree/61c4fdc9d91c3d12e3c86d3b3897133a45b32a0c/extensions/library-genesis/)

## Description
It returns a i.replace error when searching.

## Steps To Reproduce
See video:

https://user-images.githubusercontent.com/59826/179056667-13ac27f1-921e-4e5b-8b3e-77293f9a56fa.mp4

## The current behavior
Doesn't search anything.

## The expected behavior
Should return results.

### Raycast version
1.37.1

**Comment by moreluck-Yu** [comment]
I have the same problem as you, how did you solve it?
