### ISSUE TITLE
[Visual Studio Code - Project Manager] Not detecting new repos and repos that have moved

### ISSUE THREAD

**Issue by vongb** [raycast/extensions#2275]
# Extension – [Visual Studio Code - Project Manager](https://github.com/raycast/extensions/tree/01aca01489c2a293391f6ce92979d79ebe17e5a8/extensions/visual-studio-code-project-manager/)
Author: @MarkusLanger 

## Description
Project Manager is unable to find newly cloned and recently moved repositories.

## Steps To Reproduce

1. Clone a new repo or move an existing repo
2. Use Project Manager to search for the repo

## The current behavior

- Newly cloned repos won't show up in the search results.
- Old repos will have a white document icon instead of the blue folder icon with the path still showing the old path. Opening the old repo will open a new window of vscode without any projects open.

I've tried uninstalling and reinstalling the extension but the settings and the search results persist between reinstalls.

## The expected behavior
The repositories are shown when searched for.

### Raycast version
Raycast Version 1.3.7.1

**Comment by MarkusLanger** [comment]
@vongb You have to add or remove the repositories in the VSCode Extension "Project Manger". My Raycast extension reads the projects defined in the VSCode extension.

**Comment by vongb** [comment]
thanks! that worked!
