### ISSUE TITLE
[Browser Bookmarks] I hope Korean search is supported.

### ISSUE THREAD

**Issue by soo5717** [raycast/extensions#2277]
# Extension – [Browser Bookmarks](https://github.com/raycast/native-extensions/tree/98807c71c6ec589775952a250d7225b403e995f5/extensions/browser-bookmarks/)
Author:

**Describe the feature and the current behavior/state.**
- I hope **Korean search** is supported.
- Currently, it seems that only English searches are available.

![Screen Shot 2022-07-15 at 9 29 43 PM](https://user-images.githubusercontent.com/54765850/179223213-472d5fd6-acb7-4ee8-b084-aa9a645b95dc.png)

![Screen Shot 2022-07-15 at 9 30 37 PM](https://user-images.githubusercontent.com/54765850/179223476-92f14634-cc88-47df-a04c-bc6712c8ee46.png)

![Screen Shot 2022-07-15 at 9 30 53 PM](https://user-images.githubusercontent.com/54765850/179223421-1d6db450-191c-488f-820a-d546f8eb247c.png)

**Who will benefit with this feature?**
- This extension is more convenient for Korean users.

**Any Other info.**

**Comment by dehesa** [comment]
This has been fixed in release 1.43.0
