### ISSUE TITLE
[Music] Add to library command doesn't work

### ISSUE THREAD

**Issue by dcastil** [raycast/extensions#2280]
# Extension – [Music](https://github.com/raycast/extensions/tree/6c8077513b4ad4e59e64bef11c67d03ef23bfbea/extensions/music/)
Author: @Rawnly

When I open the command, the Raycast window gets closed and nothing happens. The currently playing track does not get added to my library.

## Steps To Reproduce

1. Install Music extension
2. Play track on Apple Music
3. Open Raycast and open "Add to library" command from Music extension
4. Raycast window closes but track was not added to library

## The current behavior

Raycast closes

## The expected behavior

Currently playing tracking gets added to Music library. Also would be nice to get confirmation from Raycast whether the command succeeded or not.

### Raycast version

Version: 1.37.1

**Comment by Rawnly** [comment]
I'll have a look asap! Thanks for reporting

**Comment by dcastil** [comment]
Ah just figured out that I actually get an "An error is occurred ❌" message, it was just hard to spot on my desktop background image.

Let me know if you need anything from me to debug this. 😊

**Comment by Rawnly** [comment]
Does it happens with all the songs? Can you mention some for debug? Thanks

**Comment by dcastil** [comment]
Yes, happens with every song. E.g. just tried this one: https://music.apple.com/de/album/drive-themes/661687170?i=661687178&l=en

**Comment by Rawnly** [comment]
Thanks!

**Comment by dcastil** [comment]
Also just made sure:
- The other music-related commands work fine
- System Preferences > Security & Privacy > Privacy > Automation > Raycast > Music is checked

**Comment by Rawnly** [comment]
Sorry for long delay on this, i've been very busy these days. Anyway, I think I got the "error". When I try to add to library the song you linked me I get this error: 

```
Music got an error: Can only duplicate subscription tracks to library source.
```

I  have no problems with other songs (eg: https://music.apple.com/it/album/reputation/1628227327?i=1628227344&l=en)

let me know if it persists.

**Comment by dcastil** [comment]
No worries. 😄

Adding to the library kinda works now (it adds to the library, but doesn't download it) but for some reason it adds a different version of the track to the library so that I can still add the same track via the Music app and then have it twice in the library.
