### ISSUE TITLE
[Dropbox] Download Files feature

### ISSUE THREAD

**Issue by jiserra** [raycast/extensions#2282]
# Extension – [Dropbox](https://github.com/raycast/extensions/tree/07bcbb1f6d6dde0f7aa1ba42c31d02b2c026dc55/extensions/dropbox/)
Author: @chyroc

It would be super useful if an action can be added to download the files/folders.

**Describe the feature and the current behavior/state.**
When you search or select a file/folder, the only action is "Open in Browser" with no other option.

**Who will benefit with this feature?**
Everyone who doesn't have the Dropbox client installed and doesn't want to open a tab in the browser just to download files.

**Any Other info.**
Awesome extension, but I would love for this to be implemented!

**Comment by chyroc** [comment]
great idea!
