### ISSUE TITLE
[Single Disk Eject] Exclude Disks from eject

### ISSUE THREAD

**Issue by Jashnok** [raycast/extensions#2283]
# Extension – [Single Disk Eject](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/single-disk-eject/)
Author: @johndturn

**Describe the feature and the current behavior/state.**

It'd be great to be able to exclude Disks from this feature from the extensions configuration menu.

**Who will benefit with this feature?**
 
Anyone who doesn't want to accidentally eject an important disk.

**Comment by johndturn** [comment]
vv cool idea. I'll see what I can do. My schedule's pretty slammed with work these days, but potentially in the coming weeks I can hack on it.

**Comment by johndturn** [comment]
@Jashnok This feature will be live once https://github.com/raycast/extensions/pull/2404 is merged. Feel free to follow there.

**Comment by johndturn** [comment]
@Jashnok Merged and delivered, please let me know if this feature isn't working for you or of any other recommendations.

**Comment by Jashnok** [comment]
@johndturn unfortunately it's not working for me at the moment.
![Screen Shot 2022-07-30 at 22 50 32](https://user-images.githubusercontent.com/42224338/181995755-f244a689-1053-42ca-971b-2253e924872a.png)

**Comment by johndturn** [comment]
Yep totally pushed a bug with the new feature. It assumes that people will always include a list of drives to ignore. Ill get a PR for that pushed up asap. 

In the meantime, as a workaround, if you add anything to the "List of Drives to Ignore" setting for the extension it will fix this. Doesn't have to be a real drive name.

**Comment by johndturn** [comment]
Bug fixed in this PR: https://github.com/raycast/extensions/pull/2446

**Comment by johndturn** [comment]
@Jashnok PR has been merged, can you confirm it's working for you now and that the new feature behaves as expected?
