### ISSUE TITLE
[Set Audio Device] no output devices on MacOS Ventura public beta

### ISSUE THREAD

**Issue by pdemidchick** [raycast/extensions#2291]
# Extension – [Set Audio Device](https://github.com/raycast/extensions/tree/9705ba94af72208cff790222ee3ce28e02231825/extensions/audio-device/)
Author: @benvp

## Description
The extension doesn't display any output sources if the _Include AirPlay devices_ option is turned on in the settings. 

## Steps To Reproduce
1. Go to the extension settings. 
2. Check the _Include AirPlay devices_ option. 
3. Run the command.

## The current behavior
There's no results in the output.

## The expected behavior
I can choose between the sources.

### Raycast version
1.37.1

**Comment by teziovsky** [comment]
I have this issue too 😥

**Comment by benvp** [comment]
I am still not using macOS Ventura, so I don't have any option to look into this right now. Maybe @FezVrasta has time to look into it as he implemented the Airplay part.

**Comment by FezVrasta** [comment]
That's most likely related to the new settings window. The Apple Script logic needs to be updated to work with it.
