### ISSUE TITLE
[Clockify] New time entries don't respect the "billable" flag of the project

### ISSUE THREAD

**Issue by dmastylo** [raycast/extensions#2296]
# Extension – [Clockify](https://github.com/raycast/extensions/tree/baa9c7891b5876e62d9af4453d73498f6655bf07/extensions/clockify/)

## Description
When doing "Start new timer" for a project that is marked as not billable by default, the time entries for that project are marked as billable.

## Steps To Reproduce

1. Add a project that has the default billing option turned on
2. Create a new time entry via "Start new timer" for that project
3. Check the time entry billable flag in the clockify site

## The current behavior
The time entry is marked as billable.

## The expected behavior
The time entry should not be marked as billable.

### Raycast version

1.37.1

**Comment by rogatty** [comment]
@dmastylo I noticed it too. Here is the fix: https://github.com/raycast/extensions/pull/4705
