### ISSUE TITLE
[Dev Tools Feature Request] Preference titles and labels

### ISSUE THREAD

**Issue by rolandleth** [raycast/extensions#230]
Since a checkbox can't have a `title` and nothing else can have a `label`, why have both and not use the `title` as the label for checkboxes?

I saw there's the edge case of grouping checkboxes together, but that's really just an edge case and maybe a dedicated way of grouping preferences would be better, so you can group other things as well. For example having a `sectionTitle`/`header` type.

Raycast version: 1.25.1

**Comment by thomaspaulmann** [comment]
Valid feedback. At some point we'll revisit the preferences and maybe introduce grouping. I'll close this issue for now given that it's been stale for a while.
