### ISSUE TITLE
[Slack] ... full list of users / channels are not available

### ISSUE THREAD

**Issue by netswift2905** [raycast/extensions#2300]
# Extension – [Slack](https://github.com/raycast/extensions/tree/d3e045e1202b43a23bf38fddd89bf849135901b5/extensions/slack/)
Author: @momme-rtf 

## Description
We have about 2000 people at my org in slack. Most of the people I search (Seems to be those that joined recently) do not show up in the raycast search command. 

## Steps To Reproduce

1. Select raycast search
2. Search for new slack user in the workspace
3. Many of them will not show up 

## The current behavior
Many users and channels are not findable with the search command

## The expected behavior
ALL users and channels should be findable with the search command

### Raycast version

1.37.1

**Comment by netswift2905** [comment]
On further inspection this seems to be due to the "limit" property in the API. Is there any way we can get slack API to bypass this limit and return all conversations?

**Comment by momme-rtf** [comment]
@netswift2905 Sry for the late reply. I finally found some time to push this fix. Would be nice if you could also test it since I'm not facing these issues.
[PR](https://github.com/raycast/extensions/pull/3381)
