### ISSUE TITLE
[Bitwarden] Avoid password exposure

### ISSUE THREAD

**Issue by CrisVM** [raycast/extensions#2302]
Hi,

First I'd like to say that this extension is amazing. Really useful and easy to use.

I'd like to just suggest an improvement to its usability, security, and privacy: it would be great if when we use the **Paste Password** command, the password could be sent directly to the active app, without using the system clipboard. This would avoid the password being exposed by the **Clipboard History** extension.

The idea is to make it behave just like the **Snippets** extension, i.e. when you use it to paste a snippet into the active app, the snippet content doesn't appear in **Clipboard History**, unless you open actions menu and choose **Copy to Clipboard** instead.

Just an idea to make this great extension even better.

Cheers.
Cristiano

**Comment by reanim8ed** [comment]
Also it would be nice to have autolock timer too
