### ISSUE TITLE
Node-Fetch doesn't play well with proxy configurations

### ISSUE THREAD

**Issue by whjvenyl** [raycast/extensions#2311]
**Describe the feature and the current behavior/state.**

The `node-fetch` module used to do requests doesn't support environment proxy configurations. Changing the agent used would allow, to properly use extensions behind a company firewall.

`const agent = new https.Agent({ rejectUnauthorized: !prefs.unsafeHTTPS });`

to something along the lines of

```
import { getProxyHttpAgent } from "proxy-http-agent";
...
const proxyUrl = process.env.HTTP_PROXY || process.env.http_proxy || `http://localhost:7070`;
const agent: http.Agent = getProxyHttpAgent({
  proxy: proxyUrl,
  rejectUnauthorized: !prefs.unsafeHTTPS,
});
```

**Comment by peduarte** [comment]
@whjvenyl Hey, is this still an issue for you in the latest version of Raycast 1.45.2? It has a new [Proxy setting](https://developers.raycast.com/changelog#1.45.0-2022-12-14) which is compatible with `node-fetch`
<img width="565" alt="image" src="https://user-images.githubusercontent.com/372831/210547732-e6eb8c8b-c729-4586-9e2d-83c65983afcd.png">
