### ISSUE TITLE
[Obsidian] ...

### ISSUE THREAD

**Issue by graubenh** [raycast/extensions#2312]
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/91660da681f661026bc33d06f2ca409045210eb1/extensions/obsidian/)
Author:

## Description
When I create a new note from Raycast, the body of my note is prepended with 'undefined'

## Steps To Reproduce

1. Create a new note with the New Note command.
2. View note in Obsidian.

## The current behavior
'undefined' is prepended to the text of the note.

## The expected behavior
Nothing is prepended to the text of the note.

### Raycast version

1.38

**Comment by marcjulianschwarz** [comment]
Hi @graubenh.

Could you please share a screenshot of your settings (Raycast -> Extensions -> Obsidian -> Create Note) and a screenshot of the create note form?

Do you use any templates?

**Comment by briansport13** [comment]
Hi I also had this problem when I first installed the extension. If you're looking for a quick fix you could try removing the Default Note Content & Unchecking the Fill Form With Defaults. For me when the default content is filled & fill form with defaults is checked I would get a prepended text with the default content.
<img width="298" alt="CleanShot 2022-08-07 at 22 01 30@2x" src="https://user-images.githubusercontent.com/110775063/183297691-4cf4976e-614b-4c91-b9c3-5afd62682418.png">
<img width="174" alt="CleanShot 2022-08-07 at 22 01 50@2x" src="https://user-images.githubusercontent.com/110775063/183297689-de0c5276-75d7-48ff-84bd-0a7a1cf3d0f7.png">
<img width="299" alt="CleanShot 2022-08-07 at 22 06 28@2x" src="https://user-images.githubusercontent.com/110775063/183297684-d7ba2b7f-ccb0-469c-b333-200f175f9c29.png">

**Comment by marcjulianschwarz** [comment]
Thanks for adding some clarifications. Found the issue and fixed it with [this commit](https://github.com/marcjulianschwarz/obsidian-raycast/commit/7eecaab5281d5d9d02afaed4aaefa6e559f97f70). Will be released with the upcoming update.
