### ISSUE TITLE
[Obsidian] Search Note support paths in the fuzzy search

### ISSUE THREAD

**Issue by dmastylo** [raycast/extensions#2316]
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/91660da681f661026bc33d06f2ca409045210eb1/extensions/obsidian/)
Author: @marcjulianschwarz

**Describe the feature and the current behavior/state.**
Sometimes adding the path helps add context to what exactly I'm looking for and would narrow the search results better / faster. Currently the search supports full text of the note itself and the filename, but not its path.

**Who will benefit with this feature?**
Anyone who is used to including the path in their fuzzy search in IDEs and text editors to quickly navigate to a file that may be named similarly or the same to other files.

**Any Other info.**

**Comment by marcjulianschwarz** [comment]
At the moment I am reworking the current fuzzy search by e.g. weighing the title and content of a note differently.
I think your suggestion makes a lot of sense, so I will add it to the search.

Do you know of any other parameters that might be useful when included in the search?

**Comment by dmastylo** [comment]
At the moment most of my typical searches would be full text, title, or path. But perhaps some people would find useful weighted matching on tags in the body or frontmatter YAML or even dataview inline fields if you want to extend search functionality to weight on plugin content. 

Regards,
Damian Mastylo

**Comment by marcjulianschwarz** [comment]
The under review standing [pull request](https://github.com/raycast/extensions/pull/2422) will add searching for paths.

However I wasn’t yet able to introduce a weighted fuzzy search. This will probably be part of a future update.
