### ISSUE TITLE
[Confluence Search] Could not perform search SyntaxError: Unexpected token B in JSON at position 0

### ISSUE THREAD

**Issue by altryne** [raycast/extensions#2333]
# Extension – [Confluence Search](https://github.com/raycast/extensions/tree/c5d7bc5776f040c7f4b42184e9f11ab42f155d88/extensions/confluence-search/)
Author:

## Description
Extension doesn't seem to work
## Steps To Reproduce

1. install and configure the extension
2. try searching

## The current behavior
error

## The expected behavior
results show up

### Raycast version
1.38.0

**Comment by altryne** [comment]
![CleanShot 2022-07-21 at 11 38 56](https://user-images.githubusercontent.com/463317/180278192-ade0b940-91d8-4abf-8481-932fdb9f7436.jpg)

**Comment by kholozyon** [comment]
any updates on this one? I'm getting the same error
