### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by SARRAF-5757** [raycast/extensions#2336]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/f32566f23a16c24f284981901d1c9757e798dd3b/extensions/spotify-player/)
Author: @mattisssa

## Description
When using any of the search functionalities (for example, search tracks or search artists, the search sometimes fails showing a "Something went wrong" page or saying "Search has failed" At the bottom of the window.
<img width="862" alt="Screenshot 2022-07-21 at 7 50 25 PM" src="https://user-images.githubusercontent.com/61262059/180333317-158c084e-5305-40ee-91e2-c45fd5467b81.png">
<img width="862" alt="Screenshot 2022-07-21 at 7 50 06 PM" src="https://user-images.githubusercontent.com/61262059/180333321-f7b48520-d025-452f-8a80-9a9534be8a17.png">

## Error:
```
Error: read ECONNRESET

__node_internal_captureLargerStackTrace:errors:464:5
__node_internal_errnoException:errors:594:12
TLSWrap.onStreamRead:stream_base_commons:220:20
```

## Steps To Reproduce
1. Search the name of multiple artists/tracks in a short amount of time

## The current behavior
Either shows "the search has failed at the bottom status bar or the "Something went wrong" page pops up.

## The expected behavior
Well, in a perfect world, it should find a list of search results pretty consistently.

### Raycast version
Version: 1.38.1

**Comment by mattisssa** [comment]
Hey! Thanks for the report.
Couldn't reproduce the issue anyhow.. Is it still happening to you?

**Comment by mattisssa** [comment]
Sorry, still cannot reproduce this. If you will catch this again, please reopen the issue.
