### ISSUE TITLE
[Spotify Player] Song does not update until you click on the Menu Bar App

### ISSUE THREAD

**Issue by ODB88** [raycast/extensions#2339]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/f32566f23a16c24f284981901d1c9757e798dd3b/extensions/spotify-player/)
Author: @mattisssa

## Description

Using this while listening to music, sometimes the song does not update until you go to the Menu Bar and click on it. 
Thanks!

### Raycast version
Version: 1.38.1

**Comment by mattisssa** [comment]
Hey, yes, unfortunately, it's a limitation of Raycast API. The minimal interval for background updates is 1 minute. 
More or less it shows information properly but sometimes you would need to do an additional click into the menu bar. We will probably reduce the interval later to make it work smoothly.
