### ISSUE TITLE
[Spotify Player] Menu Bar Now Playing Widget get stuck

### ISSUE THREAD

**Issue by oddharsh** [raycast/extensions#2340]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/f32566f23a16c24f284981901d1c9757e798dd3b/extensions/spotify-player/)
Author:

## Description
When changing full screen spaces, the menu bar extension becomes unclickable and unresponsive

## Steps To Reproduce
(doesn't consistently occur)
1. Open an app in full screen while spotify is playing
2. attempt to use the now playing widget.

### Raycast version
1.38.1

**Comment by sxn** [comment]
hi @oddharsh - thanks for reporting this issue!
What version of macOS are you using by the way? I've been trying to reproduce this on macOS Monterey (12.5) with no luck 🤔
Any hint towards the steps that lead to the item becoming unresponsive would be greatly appreciated! 😺

**Comment by oddharsh** [comment]
@sxn totally forgot, sorry! I'm on the Ventura beta, but I cross-tested with a friend on 12.5 and got the issue to come up sometimes. For me, initiating now playing while playing a track with my browser un-fullscreened, and then full-screening it and attempting to interact with the menu bar widget leads to unresponsiveness

**Comment by sxn** [comment]
Interesting - I'll see if I can reproduce the issue in Ventura. Meanwhile - do you think it'd be possible to record a video of the issue happening, or you reproducing the issue? Would be also interesting to know if other items in the menu bar can be interacted with, or if it's a general menu bar issue 🤔

**Comment by oddharsh** [comment]
Here you go:

https://user-images.githubusercontent.com/19518661/181294704-0265ec10-eea0-4e43-9d2b-612cd839efcd.mov

**Comment by mattisssa** [comment]
I guess this was fixed, right @sxn?

**Comment by sxn** [comment]
hey @oddharsh - latest release (1.41.0) attempts to fix some Ventura-related issues. Would you mind checking if this issue still occurs? 😺

**Comment by oddharsh** [comment]
looks to be working normally now!
