### ISSUE TITLE
[Emoji Search] ...

### ISSUE THREAD

**Issue by gdaq** [raycast/extensions#2344]
# Extension – [Emoji Search](https://github.com/raycast/extensions/tree/d9530cb3bf253d572d0675ecc0c51fc8ea60064b/extensions/emoji/)
Author: @FezVrasta

**Describe the feature and the current behavior/state.**

Can we update the list of emojis? There are a few new ones that have been added since the last release. 

The latest Emoji release https://emojipedia.org/emoji-14.0/ is not yet available from the extension.

**Who will benefit with this feature?**

Everyone 😉

**Any Other info.**

**Comment by kidonng** [comment]
Emojis from 14.0 are already there, it's just the preferences are broken (and options need to be updated). Done in #2375

Now that you mention it, I noticed the [built-in Emoji extension](https://www.raycast.com/changelog/1-34-0#:~:text=%F0%9F%99%80-,Emoji%20Search,-What%E2%80%99s%20using%20a) doesn't have Emojis from 14.0 either 😅
