### ISSUE TITLE
Extensions should be stored in $XDG_DATA_HOME

### ISSUE THREAD

**Issue by d12bb** [raycast/extensions#2355]
Raycast version: 1.38.2

## Description
Currently, extensions are stored in `$XDG_CONFIG_HOME` / `~/.config/raycast`. According to the [XDG basedir spec], this is “the base directory relative to which user-specific configuration files should be stored.” The correct directory to store "user-specific data files" like raycast extensions is `$XDG_DATA_HOME` / `~/.local/share`.

Reporting this here as I don't see any other, more correct way on the homepage.

## The current behavior
Extensions are stored in `~/.config/raycast`.

## The expected behavior
Extensions are stored in `~/.local/share/raycast`.

**Comment by thomaspaulmann** [comment]
Thanks for raising this issue. Right now we don't have the bandwidth to tackle this issue. It would require migration of the existing files. So far this hasn't popped up or caused any issues. We might pick it up in the future.
