### ISSUE TITLE
Add support for TagList in List.Item.Detail.Metadata

### ISSUE THREAD

**Issue by tonka3000** [raycast/extensions#2370]
Right now [List.Item.Detail.Metadata](https://developers.raycast.com/api-reference/user-interface/detail#detail.metadata.taglist.item) only support

- Label
- Separator

It would be helpful to have TagList support as well. This feature would help to add multiple labels on a single line (like GitHub, GitLab, ...). The `Detail` component already have support for this, so the the same look and feel would be great (API and UI).

An example use-case would be the meta-view from #2345 

**Describe the feature and the current behavior/state.**
Right now it is only possible to join a string array to a single string (or one label per entry, which easily make the list very long and scrolling is always needed). But this looks ugly and it is not possible to give them different color per item.

**Will this change the current API? How?**
Add 2 components `List.Item.Detail.Metadata.TagList` and `List.Item.Detail.Metadata.TagList.Item`, like [Detail](`List.Item.Detail.Metadata.TagList`)

**Who will benefit from this feature?**
Everybody who wants to display e.g. labels

**Any Other info.**

**Comment by mathieudutour** [comment]
shipped in v.1.39.0
