### ISSUE TITLE
[Linear] Can't select project in new Linear extension version 

### ISSUE THREAD

**Issue by dmastylo** [raycast/extensions#2383]
# Extension – [Linear](https://github.com/raycast/extensions/tree/27d569865d3949df410559c173f35b07bd7fb70a/extensions/linear/)
Author: @thomaslombart

## Description
New Linear version doesn't have a project option?

## Steps To Reproduce
<img width="862" alt="image" src="https://user-images.githubusercontent.com/2275125/180885374-a162ca3c-14b0-4c9c-b975-2878ef4c5aea.png">

## The current behavior
I should be able to select a project when creating an issue.

## The expected behavior
I used to be able to do this before the swap to the open source Linear extension.

### Raycast version
Version: 1.38.2

**Comment by thomaslombart** [comment]
The projects field isn't shown if there are not any projects for the selected team. Is it the case for you?

Note that the previous Linear extension showed the projects field but it was not possible to do anything than selecting no project.

**Comment by dmastylo** [comment]
Errr... are you sure about that? I have been doing nearly all of my linear management through RayCast for the last few weeks, assigning issues to the App or Backend projects I have on my team, and I was definitely able to do this before I swapped to using the new version of this extension. I definitely have projects for my team.

**Comment by thomaslombart** [comment]
I double-checked and you're right, there's a bug on the issue creation form when you have only one team. The issue creation form works fine only when you have multiple teams. I'm working on a a fix.

Thanks for bringing this out!

**Comment by dmastylo** [comment]
thanks for fixing this so quickly
