### ISSUE TITLE
API: `getNetworkProxy` of System Utilities

### ISSUE THREAD

**Issue by sxzz** [raycast/extensions#2386]
**Describe the feature and the current behavior/state.**

I want to get the system network proxy address, but there's no API. However, I found this library [node-macos-system-proxy-settings](https://github.com/jmshal/node-macos-system-proxy-settings). It 
 will run command `scutil --proxy` and parse the result.

I think Raycast should provide an Agent (like [ProxyAgent](https://undici.nodejs.org/#/docs/api/ProxyAgent)), or a function that returns system network proxy info just like `scutil --proxy`.

**Will this change the current API? How?**

No.

**Who will benefit from this feature?**

All extensions that sent network requests.

**Any Other info.**

None.

**Comment by tisfeng** [comment]
Agree, this feature is very useful, especially for Chinese users.

**Comment by shwangdev** [comment]
Indeed, can not agree more. We Chinese users do need such proxy feature. Otherwise we need to rewrite node-fetch part in each extensions.

**Comment by thomaspaulmann** [comment]
As part of [v1.45](https://www.raycast.com/changelog/1-45-0), we released support for proxies. The native setting also configures the extensions. Does this solve this issue?

**Comment by sxzz** [comment]
Yeah. We could use `process.env` to get proxy info via environment variables `NO_PROXY`, `HTTPS_PROXY`, `HTTP_PROXY`

Before that, users requires to enable the proxy option
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/6481596/210775626-e0a1e96d-febf-403d-8d0e-670d5013f600.png">
