### ISSUE TITLE
useFetch doesn't set isLoading: true in Reloading State

### ISSUE THREAD

**Issue by pindab0ter** [raycast/extensions#2392]
## Description

According to the [useFetch documentation](https://developers.raycast.com/utilities/react-hooks/usefetch#asyncstate) the Reloading State should have `isLoading: true`. However, this does not seem to be the case. When I run the [typeahead API example](https://github.com/raycast/extensions/tree/main/examples/api-examples) and add a `console.log()` you can see that `loading` is never true after the initial phase:

https://user-images.githubusercontent.com/5128166/181120258-39e4ee73-f3b8-4db1-bbfe-f1daa1cfc96b.mp4

Raycast version: 1.38.2

## Steps To Reproduce

1. Build and run the typeahead search example
2. Use the typeahead example and notice that the loading state is not shown after the first time it's been shown

## The current behavior

`isLoading` is not `true` in the Reloading State.

## The expected behavior

`isLoading` should be `true` in the Reloading State.

**Comment by mathieudutour** [comment]
Ah good catch! Not sure how I missed that...

Should be fixed in 1.0.7
