### ISSUE TITLE
[Linear] Change sort order of issues under "assigned issues"

### ISSUE THREAD

**Issue by dmastylo** [raycast/extensions#2405]
# Extension – [Linear](https://github.com/raycast/extensions/tree/27d569865d3949df410559c173f35b07bd7fb70a/extensions/linear/)
Author: @thomaslombart

**Describe the feature and the current behavior/state.**
Seems like issues are sorted by desc created atm. The actual linear app allows you to sort on whatever attribute you want. I have it sorted by priority, timestamp ordering doesn't do a whole lot for me. It would be nice to be able to select which sorting method you want from the extension settings at a minimum.

**Who will benefit with this feature?**
Anyone who wants to work on stories based on priority order.

**Any Other info.**

**Comment by thomaslombart** [comment]
Thanks for the feature request, it sounds like a useful addition! This seems like a good use-case for [dropdowns](https://developers.raycast.com/api-reference/user-interface/list#list.dropdown) in the issues views.
