### ISSUE TITLE
Inconsistent Action shortcut

### ISSUE THREAD

**Issue by roelvangils** [raycast/extensions#2408]
# Extension – [GIF Search](https://github.com/raycast/extensions/blob/348076b0517e3841338a9ebdca4b9f5f12f57d55/extensions/gif-search/)

Author: @josephschmitt 

Hm, there’s an inconsistency between the [Search for GIFs](https://github.com/raycast/extensions/blob/348076b0517e3841338a9ebdca4b9f5f12f57d55/extensions/gif-search/README.md) extension and the built-in Search Screenshots functionality. For screenshots, you can hit ⌘ ⏎  to paste it to the current app, but in the GIF extensions, the same shortcut copies the GIF link.

(See [Slack thread](https://raycastcommunity.slack.com/archives/C01AC2X0GMN/p1659037425509719)).

**Comment by roelvangils** [comment]
@josephschmitt What do you think?

**Comment by josephschmitt** [comment]
Hmm, I don't think "pasting into the current app" is functionality that is available to extensions. The screenshots stuff is built-in to Raycast itself and has more explicit system permissions.
