### ISSUE TITLE
[Notion] Could we have the support for Notion's newest status property?

### ISSUE THREAD

**Issue by ice-Yaya** [raycast/extensions#2412]
# Extension – [Notion](https://github.com/raycast/extensions/tree/8ea3c6f9563bf73663218d2ead8c32e683ef7b34/extensions/notion/)
Author: @ice-Yaya

### Describe the feature and the current behavior/state.
Loving 2 current functions to support Kanban view and customising visible properties for when searching for a database.
But the new status property is not an option in setting up the Kanban and choosing what to see.
Hope this could be supported.

### Who will benefit with this feature?
As Notion launched this new status property feature, I believe **more and more user will transform their initial single-selection into status**. This will more relevant to the Kanban view in this Raycast extension.

### Any Other info.
- [Notion help center on status property](https://www.notion.so/help/guides/status-property-gives-clarity-on-tasks)
- [Notion API info on status property](https://developers.notion.com/reference/property-value-object#status-property-values)

**Comment by ice-Yaya** [comment]
Notion has updated the API ([reference](https://developers.notion.com/changelog/changes-for-august-15-28-2022))

More supports for the `status` property.

**Comment by mathieudutour** [comment]
Now that it's possible, it would be nice yeah. Do you want to hack on it?
