### ISSUE TITLE
Add browser selector to the [Google Meet] ...

### ISSUE THREAD

**Issue by baronets-turk** [raycast/extensions#2419]
# Extension – [Google Meet](https://github.com/raycast/extensions/tree/55396a50505658d74d88ead2a18721ad42c2a09d/extensions/google-meet/)

My default browser is safari but I use chrome for google meet because it is better optimized for meetings and has only one google account.

**Comment by FlorianWendelborn** [comment]
@baronets-turk not a raycast solution, but typically people would use an app like https://sindresorhus.com/velja for this. I think it’d work well for your workflow
