### ISSUE TITLE
Spotify Player - shuffle play

### ISSUE THREAD

**Issue by grodzickir** [raycast/extensions#2421]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/main/extensions/spotify-player)

Author: @mattisssa

**Describe the feature and the current behavior/state.**
Shuffle play option for actions like playing a playlist would be really great. It could be controlled by a simple checkbox in configuration, either globally or for each 'play' action. For me, it would be most useful for playlists.

**Who will benefit from this feature?**
Everyone who has a favourite playlist for certain scenarios, but don't want to go always from the first song.

**Any Other info.**

**Comment by mattisssa** [comment]
Introduced separate actions for the `Search Albums` and `Search Playlist` commands. Let me know if it works wrong for you, the implementation is tricky since there is no proper API for such things...
