### ISSUE TITLE
[Linear] I would like more copy actions, including copy link, on the `CMD-T` actions after I create an issue

### ISSUE THREAD

**Issue by dmastylo** [raycast/extensions#2426]
# Extension – [Linear](https://github.com/raycast/extensions/tree/0aea27a6d2b3bf0f75d8ba2a972004e462c5400f/extensions/linear/)
Author: @thomaslombart

**Describe the feature and the current behavior/state.**
I frequently will want to copy a link after creating an issue in Linear to send to someone.

**Who will benefit with this feature?**
Anyone who shares links with co-workers on issues they've created through RayCast.

**Any Other info.**

**Comment by thomaslombart** [comment]
Thanks for the feedback! It's possible to include only two toast actions so it won't be possible to add a third option here after "Open Issue" and "Copy Issue Key".

What can be done, however, is to add a preference to the issue creation command with a dropdown to let the user choose what they want to copy after the issue creation. What do you think?

**Comment by thomaslombart** [comment]
Copy actions are not consistent across the different commands so having extension preferences per command makes more sense in my opinion.
