### ISSUE TITLE
[Obsidian] Open in new pane and/or open in new window action

### ISSUE THREAD

**Issue by dmastylo** [raycast/extensions#2428]
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/91660da681f661026bc33d06f2ca409045210eb1/extensions/obsidian/)
Author: @marcjulianschwarz

**Describe the feature and the current behavior/state.**
It would be nice to be able to open the note you are searching in a new pane or window instead of replacing the focused note.

**Who will benefit with this feature?**
Anyone who uses panes or windows in Obsidian.

**Any Other info.**

**Comment by marcjulianschwarz** [comment]
Hi @dmastylo,

sounds really useful.

This would only work when the user has the [Advanced URI](https://github.com/Vinzent03/obsidian-advanced-uri) plugin installed and enabled. The Daily Note command uses this plugin too. 

I will add a “Open in New Pane” action that will only show when the plugin is installed.

Thank you for the great feature requests.

**Comment by marcjulianschwarz** [comment]
Added the `Open in new Pane` action which will be released with the next update as you can see.

I don't thhink opening notes in a new window is possible.

**Comment by dmastylo** [comment]
Thanks for the update! Does advanced URI just not have new window support yet?

**Comment by marcjulianschwarz** [comment]
Not that I could see [here](https://vinzent03.github.io/obsidian-advanced-uri/concepts/navigation_parameters).
