### ISSUE TITLE
[API Feature Request] Auto-close extension view after running command

### ISSUE THREAD

**Issue by jaklan** [raycast/extensions#244]
**Describe the feature and the current behavior/state.**

I noticed quite frustrating behaviour of extensions - when I open a tab from the Chrome extension, or open a repo from the GitLab extension, or open a formula from the Brew extension etc. - the extension is not closed when I open Raycast again, I have to manually click `Escape` / `Backspace` to return to the main view. 

For example I **nonstop** start to search for some command in Raycast after switching tab using the Chrome extension and then I discover that I’m actually still searching within Chrome tabs… The behaviour I expect should be similar to the `silent` mode of script commands, but actually it's rather similar to the `fullOutput` mode.

Imho there should be different modes for extension commands (as they are for script commands), so extension developers can:
- decide then if it makes sense to close the extension view or not
- provide an option for their commands to allow users to select the preferred behaviour
(maybe it can even be a default option for all extension commands?)

PS `Pop to root search` setting doesn’t do the job, because it affects the behaviour of Raycast in all scenarios, and here we discuss only about the behaviour after executing the command.

**Comment by jaklan** [comment]
@bromanko any chance to update the Chrome extension? I still find it very frustrating, especially with that extension...

Btw, @thomaspaulmann - `GitHub Repository Search` is also affected exactly in the same way as above extensions

**Comment by bromanko** [comment]
See #284. I added it there but it has not yet been merged.

**Comment by jaklan** [comment]
@bromanko cool, thanks! However, it's implemented for `Search History`, but it doesn't work for the rest of the commands - `Search Tabs` and `New Tab` :/

**Comment by thomaspaulmann** [comment]
Hey, just picking this up. We have a setting in Raycast to pop to root after some interval. This is what developers should rely on when the window gets closed. Most of the time this results in the correct way. For other cases you can use the `popToRoot` function as highlighted here. I think this is the best way to keep the extensions consistent. 

Given that this issue has been stale for a while, I'll close it.
