### ISSUE TITLE
[Raindrop.io] Fallback for websites that don't have a favion.

### ISSUE THREAD

**Issue by roelvangils** [raycast/extensions#2443]
# Extension – [Raindrop.io](https://github.com/raycast/extensions/tree/306c57d1c53a81ca29168ba570f4a76241c589ce/extensions/raindrop/)
Author: @lardissone

**Describe the feature and the current behavior/state.**

Currently, bookmarks without favicon, have an empty space. It looks like they could not be loaded or something. Maybe consider adding a default icon (such as the Raindrop icon itself).

**Comment by lardissone** [comment]
@roelvangils good idea! will work on this!
