### ISSUE TITLE
Error listing disks [Single Disk Eject] ...

### ISSUE THREAD

**Issue by NormCopeland** [raycast/extensions#2444]
# Extension – [Single Disk Eject](https://github.com/raycast/extensions/tree/5b263d67bed83695221d4e0420ae58b600f6c318/extensions/single-disk-eject/)
Author: @johndturn

## Description

When activating this extension, it fails to list the available disks. Instead I get the following error:
`Error listing volumes Cannot read properties of undefined (reading 'split')`

![singlediskeject](https://user-images.githubusercontent.com/95777690/182028480-ba33bdc0-d5e4-4a4f-8909-61a993fe9b2c.gif)

## Steps To Reproduce

1. Activate extension
2. Error message appears

## The current behavior

The following error message appears: `Error listing volumes Cannot read properties of undefined (reading 'split')`

## The expected behavior

The extension should list available disks for selection.

### Raycast version
Version: 1.38.2

**Comment by johndturn** [comment]
Yes, look out for a PR fixing this today (MST timezone).

**Comment by johndturn** [comment]
PR fixing this issue: https://github.com/raycast/extensions/pull/2446

**Comment by johndturn** [comment]
@NormCopeland PR has been merged, can you confirm it's working for you now?

**Comment by NormCopeland** [comment]
@johndturn working! Thanks so much!
