### ISSUE TITLE
[Spotify Player] Add "dislike" command

### ISSUE THREAD

**Issue by kud** [raycast/extensions#2449]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/main/extensions/spotify-player)

Author: @mattisssa

**Describe the feature and the current behavior/state.**
Add a command to dislike a song (I often use it in the "Discover Weekly" playlist).

**Who will benefit from this feature?**
Everyone who loves to say to Spotify they don't like a song (better matching).

**Comment by kud** [comment]
Great! Thanks.

**Comment by kud** [comment]
Hey @pernielsentikaer @daikaiyu , could we re-open this issue because disliking here just dislikes the song but not removes it.

It should do that normally: ![screenshot-2022-10-11-22-45-41@2x](https://user-images.githubusercontent.com/655838/195204271-fd9ceb67-abed-4942-a9b1-0d952f6fe77b.png)

**Comment by daikaiyu** [comment]
> Hey @pernielsentikaer @daikaiyu , could we re-open this issue because disliking here just dislikes the song but not removes it.
> 
> It should do that normally: ![screenshot-2022-10-11-22-45-41@2x](https://user-images.githubusercontent.com/655838/195204271-fd9ceb67-abed-4942-a9b1-0d952f6fe77b.png)

I'll check it out.

**Comment by daikaiyu** [comment]
At present, `Like` to be equivalent to the operation of `Save to Your Library`. So, I think `Dislike` is more suitable to `Remove from Your Library`. 
Unfortunately, the official Spotify does not seem to provide API about `dislike the song`  which you mean.I didn't find it in AppleScript too.
If you find the relevant operation, please let me know! @kud
