### ISSUE TITLE
[Linear] Assigned Issues Are Empty

### ISSUE THREAD

**Issue by adrice727** [raycast/extensions#2461]
# Extension – [Linear]
(https://github.com/raycast/extensions/tree/fb357f0fcd02d9ff1244ef05d4c27011251dc154/extensions/linear/)

Author: @thomaslombart 

## Description

When I go to assigned issues, they are empty:

<img width="750" alt="Screen Shot 2022-08-02 at 10 29 17 AM" src="https://user-images.githubusercontent.com/5115751/182437255-44793e96-36a0-4014-8f28-aa82b1ff37e8.png">

Everything else seems to be working fine.  I can use search to find one of my issues and see that it is assigned to `me`:

<img width="353" alt="Screen Shot 2022-08-02 at 10 32 12 AM" src="https://user-images.githubusercontent.com/5115751/182437828-81c93374-bfe4-4e2f-ba0d-4000d024c4c1.png">

## Steps To Reproduce

1. Open Raycast and type `linear`
2. Select "Assigned Issues"

## The current behavior

Assigned issues are empty.

## The expected behavior

My assigned issues are displayed.

### Raycast version

`1.38.2`

**Comment by thomaslombart** [comment]
Thanks for creating the issue @adrice727. I wasn't able to reproduce the bug so I'll need more info to further investigate that one:
- Is the same thing happening for the "Active Cycle" and "Created Issues" commands?
- Do you have one or multiple teams in your Linear workspace?
- In the "Search Issues" command, are you able to see your avatar on the issue list item? (right-most accessory)
- What type of issues are assigned to you? What are their states?

**Comment by adrice727** [comment]
@thomaslombart 

- Is the same thing happening for the "Active Cycle" and "Created Issues" commands?
-- Yes

- Do you have one or multiple teams in your Linear workspace?
-- Yes, multiple teams

- In the "Search Issues" command, are you able to see your avatar on the issue list item? (right-most accessory)
-- Yes, I do see my avatar and when I select one of my issues, I have the option to `Un-assign from me` in the actions 
 
- What type of issues are assigned to you? What are their states?
-- Currently all bugs, with states: queued, in review, and engineering

I am able to create `Create Issue for Myself` which works fine, but the issue still does not show up in my assigned issues.

**Comment by thomaslombart** [comment]
Thanks for the answer @adrice727, it helps a lot in debugging. It seems like there's a bug that has to do with states not being retrieved. I'm working on a fix 🙂

**Comment by thomaslombart** [comment]
Small update: I didn't have much time to work on it lately. I'll get back to that tomorrow.

**Comment by thomaslombart** [comment]
@adrice727 are you still facing the issue? I made various fixes on the Linear extension: https://github.com/raycast/extensions/pull/2535.

**Comment by adrice727** [comment]
@thomaslombart No, everything is working as expected.  Thank you!

**Comment by thomaslombart** [comment]
Awesome. @pernielsentikaer can you close this issue? 🙂

**Comment by pernielsentikaer** [comment]
Sure, thanks for mentioning @thomaslombart
