### ISSUE TITLE
[Google Translate] Doesn't work at all

### ISSUE THREAD

**Issue by lainisourgod** [raycast/extensions#2468]
# Extension – [Google Translate](https://github.com/raycast/extensions/tree/507608b10c020d25aed0a1d744ff5b56f43249a5/extensions/google-translate/)
Author: @gebeto

## Description
Extension doesn't work: when I hit "Enter" to translate, error pops out. Error message provided

## Error:
```
Error: type mismatch at params.message : Expected to decode String but found a dictionary instead.
```

## Steps To Reproduce

1. Open Raycast
2. Configure Google Translate with `primary: russian; secondary: english`
3. Google Translate → opens text box `Enter text to translate`
4. write `sushi`
5. `Something went wrong`
![image](https://user-images.githubusercontent.com/24773652/182550379-d860c99f-344e-4069-877b-7122bcbf20ea.png)

### Raycast version
Version: 1.38.2

**Comment by gebeto** [comment]
Hm, interesting

Everything looks fine for me

<img width="769" alt="Screenshot 2022-08-03 at 10 34 45" src="https://user-images.githubusercontent.com/13422799/182550819-bcd03bc8-332b-4e47-b8b8-97cd2467aee3.png">

<img width="770" alt="Screenshot 2022-08-03 at 10 34 04" src="https://user-images.githubusercontent.com/13422799/182550725-9fe5ded3-9f0d-4e37-a78f-aadef3163f35.png">

**Comment by gebeto** [comment]
What's your location? Is google translate website works in your region?

https://translate.google.com/
