### ISSUE TITLE
[Music] Love Track not working

### ISSUE THREAD

**Issue by kubici** [raycast/extensions#2469]
# Extension – [Music](https://github.com/raycast/extensions/tree/e17b4a3c292e85ccd4933df860af435f487dc478/extensions/music/)

## Description
Using the commands from the music extensions do not work. For "Love Track" command, you get a "Something wrent wrong" error message.

## Steps To Reproduce

1. Open Raycast
2. Search for "Love Track" command
3. Push Enter
4. Error message appears

## The current behavior
Due to the errors in the commands, no music extension command is executable.

## The expected behavior
"Love Track" extension is setting the current playing track to favourite / liked / heart.

### Raycast version

1.38.2

**Comment by Rawnly** [comment]
I'll post updates in #2514
