### ISSUE TITLE
[Extension Bug]  Notion Page Search not supporting CJK character keywords

### ISSUE THREAD

**Issue by designedbyclu** [raycast/extensions#247]
## Extension – [Notion](https://github.com/raycast/extensions/tree/main/extensions/notion)
**Author**: @HenriChabrand 

![Screenshot -2021-10-27 at 15 43 42@2x](https://user-images.githubusercontent.com/26009982/139022125-3dcd498a-93b9-4549-88ce-6b840a081d05.png)

![Screenshot -2021-10-27 at 15 45 13@2x](https://user-images.githubusercontent.com/26009982/139022336-ca5837cd-8c92-4317-8152-c6f73bccf603.png)

Raycast version: 1.25.1

## Description:
The current extension doesn't support CJK for search, only able to search in English.

## The current behavior
Not Result for CJK words

**Comment by mattisssa** [comment]
Hey @HenriChabrand! 
Here is the new bug report to your extension, take a look at that and subscribe to don't miss anything related 😉
