### ISSUE TITLE
[Linear] Add ability to tag another user

### ISSUE THREAD

**Issue by rattrayalex** [raycast/extensions#2470]
# Extension – [Linear](https://github.com/raycast/extensions/tree/fb357f0fcd02d9ff1244ef05d4c27011251dc154/extensions/linear/)
Author: @thomaslombart 

**Describe the feature and the current behavior/state.**

Currently, when I type `@matt` for exampe, it doesn't autocomplete to suggest mentioning/tagging my teammate Matt. I would like it to do this, so that when I am quickly creating an issue (for example, during a conversation with a user), I can ask a teammate to quickly look into it.

**Who will benefit with this feature?**

Anyone working with teammates in Linear, especially those who frequently delegate (EM's, PM's, CTO's, CEO's, etc).

**Any Other info.**

This is the first thing I ran into when trying Raycast for the first time (I want a quick add-to-TODO app, and am hoping to use Linear for that since we use Linear for our eng tasks).

cc @gleich who maybe could take a look at banging this out 😉 (and thanks for turning me on to Raycast, I'm really excited to try it!)

**Comment by thomaslombart** [comment]
Thanks for the issue @rattrayalex! What do you mean by autocomplete? In which command(s) do you need it?

As of now, you can set assignees and benefit from Raycast's built-in autocomplete for this but not sure that's your use case. (cf screenshot below)

<img width="1000" alt="linear 2022-08-03 at 15 33 34" src="https://user-images.githubusercontent.com/16003285/182620937-925b50f4-f659-4e77-aa2d-b8096113ea39.png">

**Comment by thomaslombart** [comment]
Unfortunately, it's not possible to do that kind of thing in Raycast as of now 😕

**Comment by rattrayalex** [comment]
Got it, no problem! Thanks for taking a look!

**Comment by rattrayalex** [comment]
Wait actually, what if you added a `cc` field, like below `Assignee`, which uses the same dropdown but as a multiselect? And it just injects the contents into the description as `cc @alice @bob`?

**Comment by thomaslombart** [comment]
That could work. However, this would probably need to be configured via an extension preference to avoid bloating the UI for those not using the field.

**Comment by rattrayalex** [comment]
Weird, why does the @stale bot close things as _completed_?
