### ISSUE TITLE
[Spotify Player] Player command failed: No active device found

### ISSUE THREAD

**Issue by doloreslopezjoffre** [raycast/extensions#2474]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/0a85074ef89d716ba839091e83d6037892debab0/extensions/spotify-player/)
Author: @mattisssa

## Description
When trying to play a song, album or playlist for the first time, without Spotify open, the Spotify API throws an error (which is NOT handled in any "pretty" way by the extension neither).

<img width="388" alt="image" src="https://user-images.githubusercontent.com/61397555/182737106-84c2616d-53ee-4f58-bd16-af7a4b503c37.png">

**_My understanding of the problem is the following:_** 
Spotify plays a song, album or playlist on the `active` device. After certain inactivity period, devices are set to an `inactive` state and music cannot be played unless it becomes `active` again.

For what I found on a quick Google search, if you want to change the status of a device as active, according to [their documentation](https://developer.spotify.com/documentation/web-api/reference/player/get-a-users-available-devices/), you can first try to GET https://api.spotify.com/v1/me/player/devices in order to obtain the list of available devices:

```
// Example response
{
  "devices" : [ {
    "id" : "5fbb3ba6aa454b5534c4ba43a8c7e8e45a63ad0e",
    "is_active" : false,
    "is_private_session": true,
    "is_restricted" : false,
    "name" : "My fridge",
    "type" : "Computer",
    "volume_percent" : 100
  } ]
}
```

and then select one of the available devices by invoking the [player endpoint](https://developer.spotify.com/documentation/web-api/reference/player/transfer-a-users-playback/) `PUT https://api.spotify.com/v1/me/player`, including:

> - `device_ids` Required. 
> A JSON array containing the ID of the device on which playback should be started/transferred. For example: `{device_ids:["74ASZWbe4lXaubB36ztrGX"]}` Note: Although an array is accepted, only a single device_id is currently supported. Supplying more than one will return 400 Bad Request
> - `play` with value true if you want to start playing right away.

## Steps To Reproduce
1. Without having recently opened the Spotify app in any device, nor played a song or have been active on the app/desktop app/site, run any command of the extension regarding playing a song, album or playlist.

## The current behavior
Can't play a song (even if I've got Spotify open) and have to play a song before-hand before the extension can do its magic. 

## The expected behavior
Should be able to play a song, album or playlist without relying on the user's having to "prepare the stage" by marking the device (MacOs **active device** in which Raycast is currently running/the extension is being interacted with) as active.

### Raycast version
Version: 1.38.2

**Comment by mattisssa** [comment]
Hey! Thanks for the investigation, yes you're right about the source of the issue. Unfortunately, the scope I have for the current client doesn't have access to active devices, I'm still trying to reach Spotify support to get it right. 
The issue has been fixed in recent updates without getting it tho. So, let me know if this is still the issue for you 😉

**Comment by doloreslopezjoffre** [comment]
Cool! I just got to my macbook and it's working as expected! Thank youuuu
