### ISSUE TITLE
[Things] Ability to switch off 'Today' in Menu Bar (beta)

### ISSUE THREAD

**Issue by smutn** [raycast/extensions#2475]
# Extension – [Things](https://github.com/raycast/extensions/tree/5f42be97154e3920321c7001063fb0f5a1abd220/extensions/things/)
Author: @loris

It will be great to have ability to switch off `Show Today in Menu Bar` option in Actions pane, not only in Raycast Preferences / Extensions.

**Comment by loris** [comment]
Duplicates of https://github.com/raycast/extensions/issues/2811
