### ISSUE TITLE
[Brew] Unable to perform Brew Search

### ISSUE THREAD

**Issue by kanemontreuil** [raycast/extensions#2482]
# Extension – [Brew](https://github.com/raycast/extensions/tree/c857437cb85229cc3e11177172ea408b8e03afa1/extensions/brew/)
Author: @nhojb

## Description

Unable to perform `Brew Search` command.

https://user-images.githubusercontent.com/4593816/182888363-0c6b351c-2e24-4c0b-9916-c40de19ef95e.mov

## Steps To Reproduce

1. Launch Raycast
2. Type `Brew Search`, return
3. Observe `Brew search failed` error message

<img width="862" alt="Unable to capture error logs" src="https://user-images.githubusercontent.com/4593816/182890310-6385b6ff-94b2-469f-b2e7-0064d2dbf569.png">

> **Note**: It appears I'm unable to capture the error logs. `⌘ T` followed by `return` results in an empty clipboard.

## The current behavior

`Brew Search` fails, with no logs to capture.

## The expected behavior

`Brew Search` should allow searching formulae by name.

### Raycast version
Version: 1.38.3

### System information
OS: macOS Monterey
Version: 12.3.1
Model: MacBook Pro (16-inch, 2021)
Chip: Apple M1 Pro
Memory: 16 GB

**Comment by nhojb** [comment]
Hi @kanemontreuil thanks for the bug report.

Could you run `brew doctor` on your Mac and post the output? Thanks.

**Comment by kanemontreuil** [comment]
Sure thing @nhojb!

<img width="718" alt="Screen Shot 2022-08-04 at 11 36 52 AM" src="https://user-images.githubusercontent.com/4593816/182915191-38a33fe3-ef3c-4f7b-a956-992a6b54dc0d.png">

**Comment by kanemontreuil** [comment]
@nhojb it turns out my employer's proxy (Zscaler) was causing this issue. I realized after closing #2485 that they might be related. Works like charm now.

<img width="862" alt="working extension" src="https://user-images.githubusercontent.com/4593816/182970924-e4a257fd-2c67-4f80-a3fa-95e87f42f2f2.png">

**Comment by nhojb** [comment]
Great, thanks for the update. Glad you are good now.
