### ISSUE TITLE
[Hacker News] Unable to load stories due to local issuer certificate

### ISSUE THREAD

**Issue by kanemontreuil** [raycast/extensions#2485]
# Extension – [Hacker News](https://github.com/raycast/extensions/tree/4c6e4856f5a838f0bc74216eaa7e1def508d45e7/extensions/hacker-news/)
Author: @thomaspaulmann

## Description

Unable to load stories due to local issuer certificate

<img width="862" alt="hacker-news-8-4-22" src="https://user-images.githubusercontent.com/4593816/182915533-ae3ae27e-8388-44ae-9ff1-55ee1033d845.png">

> **Warning**: **Failed loading stories** unable to get local issuer certificate.

## Steps To Reproduce

1. Launch Raycast
2. Type `Hacker News`, hit `return`
3. Observe `Failed loading stories unable to get local issuer certificate` error message

## The current behavior

Extention failed loading stories.

## The expected behavior

Extention loads stories.

### Raycast version
Version: 1.38.3

### System information
OS: macOS Monterey
Version: 12.3.1
Model: MacBook Pro (16-inch, 2021)
Chip: Apple M1 Pro
Memory: 16 GB

**Comment by thomaspaulmann** [comment]
A quick Google search suggests that this is a SSL issue. Not sure if there is much to do on the extension side. Can you retry using it? Do you have any special networking setup?

**Comment by kanemontreuil** [comment]
@thomaspaulmann thanks for the quick response. Sure enough, it was my employer's proxy (Zscaler) causing issues. It works like a charm now.

<img width="862" alt="Working extension" src="https://user-images.githubusercontent.com/4593816/182970079-a88ca7fe-0f4c-47fc-9e31-5cb2641a305b.png">

**Comment by thomaspaulmann** [comment]
Glad you can stay on top of HN!

**Comment by waltyou** [comment]
hi @kanemontreuil, I face the same issue and I'm also working under Zscaler, how did you resolve it?

**Comment by kanemontreuil** [comment]
@waltyou I was able to work around Zscaler's proxy by using a VPN

**Comment by dufferzafar** [comment]
Does anyone know if there's a way to disable SSL verification in raycast? I'm unable to bypass the ZScaler proxy.

**Comment by axeII** [comment]
@dufferzafar thank you!!
