### ISSUE TITLE
[GIF Search] Favorites and/or recents sometimes get deleted

### ISSUE THREAD

**Issue by sxn** [raycast/extensions#2495]
# Extension – [GIF Search](https://github.com/raycast/extensions/tree/348076b0517e3841338a9ebdca4b9f5f12f57d55/extensions/gif-search/)
Author: @josephschmitt

## Description

I noticed that sometimes my favorites / recents were just…gone. After investigating, I noticed a few places where an exception is caught, and as a result, the extension calls clear, which… clears all recents or favorites. This makes it hard to use the `favorites` feature, as a failed API call could result in them being gone. 😅 

## Steps To Reproduce

1. Open `Search for GIFs`
2. Select Giphy in the dropdown (though I'm guessing it'll work with the other services, too)
3. Make sure you have some gifs in "recents" and "favorites"
4. Press esc to exit to the root search
5. Open `Search for GIFs`
6. You might see an error toast. If you don't, repeat steps 4-5 until you do. This can take a while - sometimes it happens on the first try, other times I had to repeat steps 4-5 for what felt like hundreds of times 😅 

I added a bunch of `console.log`s to all callsites of `await clear()` and, in my case, I was running into [this](https://github.com/raycast/extensions/blob/main/extensions/gif-search/src/hooks/useLocalGifs.ts#L37) every single time.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/1155589/183056728-c1fc9335-4bdb-427e-8f85-56b09f8823e1.png">

The output was:

```
11:46:08.322 clearing faves, because: /Users/sorin/Sandbox/raycast/extensions/extensions/gif-search/node_modules/@giphy/js-fetch-api/src/fetch-error.ts:5
        super(message)
        ^

Error: fetch failed
    at FetchError5 (/Users/sorin/Sandbox/raycast/extensions/extensions/gif-search/node_modules/@giphy/js-fetch-api/src/fetch-error.ts:5:9)
    at Object.<anonymous> (/Users/sorin/Sandbox/raycast/extensions/extensions/gif-search/node_modules/@giphy/js-fetch-api/src/request.ts:66:30)
    at step (/Users/sorin/Sandbox/raycast/extensions/extensions/gif-search/node_modules/@giphy/js-fetch-api/src/fetch-error.ts:11:16)
    at Object.throw (/Users/sorin/Sandbox/raycast/extensions/extensions/gif-search/node_modules/@giphy/js-fetch-api/src/fetch-error.ts:11:16)
    at rejected (/Users/sorin/Sandbox/raycast/extensions/extensions/gif-search/node_modules/@giphy/js-fetch-api/src/fetch-error.ts:11:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 0,
  statusText: ''
}
```

## The current behavior

When there's an error fetching the user's favorites and / or recents, their LocalStorage entries are deleted.

## The expected behavior

When there's an error fetching the user's favorites and / or recents, their LocalStorage entries are kept so next time the extension is loaded they can (hopefully) be displayed.

### Raycast version

Version: 1.38.3

**Comment by josephschmitt** [comment]
Hmm, I see your point. I think my original reasoning was I didn't want you to get into a state of corrupted fav's. But maybe that's too aggressive. I could maybe add a context menu option for clearing out favs if things go wrong? Wdyt?

**Comment by sxn** [comment]
> I think my original reasoning was I didn't want you to get into a state of corrupted fav's. But maybe that's too aggressive. I could maybe add a context menu option for clearing out favs if things go wrong? Wdyt?

Do we need to clear faves? 🤔 I would just not show them in that case; and if a user tries to add a new fave in this situation, pop a toast informing them why that can't be done, and offering to retry fetching them before. Or something to that effect. 😅
