### ISSUE TITLE
[Raycast Wallpaper] ...

### ISSUE THREAD

**Issue by ibehnam** [raycast/extensions#2502]
Gives an error:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/58621210/183296784-6bd693ef-5f6d-405b-a684-975e5228f382.png">

**Comment by koinzhang** [comment]
Hi @ibehnam. Can you use the Raycast Wallpaper extension now?
If it still doesn't work, can you copy the error log to me?

**Comment by ibehnam** [comment]
I tried again and got this error: `AxiosError: Request failed with status code 500` with the same image as above.

**Comment by reywright** [comment]
AxiosError: Request failed with status code 500

**Comment by haackt** [comment]
I found the error, which causes this bug.

The extension queries the URL `https://www.raycast.com/wallpapers.json`, which contains a faulty image link.
When the extension tries to access the URL, the server throws a 500 and causes the extension to crash.

I submitted a PR, which "fixes" the bug (see above).
(I simply just altered the data, after axios requests it from the server)

**Comment by koinzhang** [comment]
Hi @haackt Thank you very much for finding this error, I see you don't seem to have submitted a fix PR yet, so I submitted a fix [PR](https://github.com/raycast/extensions/pull/2791)
