### ISSUE TITLE
[CanvasCast] Not all courses are shown

### ISSUE THREAD

**Issue by cherryblossom000** [raycast/extensions#2504]
# Extension – [CanvasCast](https://github.com/raycast/extensions/tree/0e9e4eb56af9c3142bb0fadb062a9d63a1797113/extensions/canvascast/)
Author: @YodaLightsabr

## Description

Not all courses are shown. For me, only the first 8 of my 14 courses are shown.

## Steps To Reproduce

1. Have more than 10 courses
2. Use the command

## The current behavior

Not all courses are shown. For me, only the first 8 of my 14 courses are shown, which I think is because the other 2 courses returned in the first page of `/api/v1/courses` are old courses/don‘t appear on my dashboard (yet the `enrollment_state` is `active`… I’m not sure what’s going on here).

## The expected behavior

All courses are shown. [Pagination](https://canvas.instructure.com/doc/api/file.pagination.html) should be used and the `per_page` value should be set to a higher value (if unset like it is currently, it defaults to 10).

### Raycast version
Version: 1.38.3

**Comment by YodaLightsabr** [comment]
Is it pagination or unfavorited courses? If it's pagination I'd expect a different cutoff number. I'll take a look a bit later.

**Comment by cherryblossom000** [comment]
It’s pagination. The issue isn‘t with the unfavourited courses, of which there are 2 (which explains why only 8 courses are displayed). `/api/v1/courses` returns my first 10 courses, including 2 unfavourited ones (which I want to continue to not display), but I have 4 more unfavourited courses that I want to see.

**Comment by YodaLightsabr** [comment]
Oh ok. This sounds like an easy enough thing to fix.
