### ISSUE TITLE
[Spotify Player] Add option to limit the characters shown in menu bar

### ISSUE THREAD

**Issue by jahirfiquitiva** [raycast/extensions#2509]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/943671d313fd2d25437c0e705909d5ece1f6ca5e/extensions/spotify-player/)
Author: @mattisssa

**Describe the feature and the current behavior/state.**
Currently, when some songs have really long names, the menu bar item can take a lot of space

**Who will benefit with this feature?**
Anyone who like their menu bar to be as clean as possible

**Comment by mattisssa** [comment]
Hey! You can already do that, just go to the preferences of the command and you will find the option there:
![CleanShot 2022-08-09 at 00 06 37@2x](https://user-images.githubusercontent.com/15333662/183514688-5f3da008-f061-4035-8fa6-f593bfe5deb3.png)

**Comment by jahirfiquitiva** [comment]
oh, I didn't notice because I was looking at the extension settings instead of that command's ones 😅 

![Shot 2022-08-08 at 16 14 56@2x](https://user-images.githubusercontent.com/10360816/183516055-631c4399-09f1-4bcc-b34f-4845a81780b7.png)

Thanks for the quick response! 🙌

**Comment by mattisssa** [comment]
It's fine, since the pref is also not required it was easy to miss 😄 
I was thinking about specifying some default value since it popped up a few times already 🤔

**Comment by jahirfiquitiva** [comment]
> It's fine, since the pref is also not required it was easy to miss 😄 
> 
> I was thinking about specifying some default value since it popped up a few times already 🤔 

That might be good. Maybe also a disclaimer mentioning to change that one should change the command prefs instead of the extension's 🤔
