### ISSUE TITLE
[Open With App] extend to open with other Applications like PathFinder, Commander One, etc

### ISSUE THREAD

**Issue by freese** [raycast/extensions#2513]
# Extension – [Open With App](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/open-with-app/)

Author: Andres Freese

I love this extension and use it every day. 

**Describe the feature and the current behavior/state.**
Sadly, it doesn't support other file managers other than the default Finder Application. The current Apple Script only "tells" the Finder Application to do something with the selected items:

```
  const applescript = `
  tell application "Finder"
    set theItems to selection
  end tell
  set itemsPaths to ""
  repeat with itemRef in theItems
    set theItem to POSIX path of (itemRef as string)
    set itemsPaths to itemsPaths & theItem & return
  end repeat
  return itemsPaths
  `;
```

https://github.com/raycast/extensions/blob/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/open-with-app/src/index.tsx#L39-L41

The script could be extended to use other Finder alternatives, specially PathFinder but also Commander One and ForkLift

**Who will benefit with this feature?**
Users of alternative file managers, that offer more features than the Finder.

Thank you very much for this Extension  @fturcheti

**Comment by fturcheti** [comment]
Good suggestion @freese. As I don’t use PathFinder, would you like to contribute to the extension implementing this feature?

It would be necessary to add a preference for the user to select its file manager: Finder or PathFinder.

And the support for other file managers could be added later, depending on their AppleScript support.
