### ISSUE TITLE
[Music] Love track extension stopped working

### ISSUE THREAD

**Issue by slahard** [raycast/extensions#2514]
# Extension – [Music](https://github.com/raycast/extensions/tree/e17b4a3c292e85ccd4933df860af435f487dc478/extensions/music/)
Author: @Rawnly

## Steps To Reproduce

1. "Love track" either when streaming from the library or from the apple music catalog

## The current behavior
It seems like updating to macOS 12.5 broke the Love track extension. Even though I receive "Loved" system feedback it doesn't show as Loved in Apple Music. Moreover, when I'm streaming from Apple Music (not songs from my library) it shows the error message. 

## The expected behavior
Marking currently playing track as loved.

### Raycast version
Version: 1.38.3

**Comment by Rawnly** [comment]
Thanks for reporting, I'll have a look when I'm back from holidays ✌️

**Comment by Rawnly** [comment]
In the meantime can you post the error message?

**Comment by slahard** [comment]
No worries. Enjoy your holidays! 

<img width="1440" alt="Screenshot 2022-08-09 at 15 14 26" src="https://user-images.githubusercontent.com/83577071/183663858-030dc904-4566-4914-9bde-1c3f5e2f92d1.png">

Command failed with exit code 1: osascript -e tell application "Music" to duplicate current track to library playlist "Library"
28:81: execution error: Music got an error: Can only duplicate subscription tracks to library source. (-10006)

**Comment by flegfleg** [comment]
i have a similar issue, i get an error ("Whoops Something went wrong"), and the track is not loved.

**Comment by marcusmoore** [comment]
I'm not sure if it is best to post this here or in #2984 but I'm experiencing the same. When playing from my library I get the "Loved" feedback as well but the song is not loved in the library. When playing from Apple Music I get an error message.

I did a tiny bit of source diving and it seems like the "love and add to library" [command](https://github.com/raycast/extensions/blob/7fca49af04302358bc18b904bd72a1b27630d9cb/extensions/music/src/love-and-add-to-library.tsx#L10) actually calls `love` on the current track while the "love" [command](https://github.com/raycast/extensions/blob/7fca49af04302358bc18b904bd72a1b27630d9cb/extensions/music/src/love.tsx#L8) just calls `addToLibrary`. I'm not sure if that's helpful but it seems off.

Apple Music: 1.2.5.7
Raycast: 1.40.3

Thanks 😄

**Comment by Rawnly** [comment]
@marcusmoore thanks for the report, I'm working on a big PR fixing everything (this and other bugs) i hope to make ti mergeable asap! ✌️

**Comment by Rawnly** [comment]
Working on a fix this weekend! Sorry for delay!
