### ISSUE TITLE
[Google Workspace] Files in Shared Drives don't show up in search results

### ISSUE THREAD

**Issue by yangsu** [raycast/extensions#2517]
# Extension – [Google Workspace](https://github.com/raycast/extensions/tree/d7bf50a27c59d9eb276eb0fa1e528e8f81f3128e/extensions/google-workspace/)
Author: @thomaslombart

## Description
As of a few days ago, the Google Workspace commands no longer search over shared drives. Only files in my personal google drive show up in the search results.

## Steps To Reproduce

1. Raycast -> "Search Google Drive Files" or "Starred Google Drive Files"
2. Search for a file in a shared drive
3. See nothing

The workflow that works
1. Raycast -> type search query -> Search Google Drive Files
2. See correct results

## The current behavior
Result list is empty

## The expected behavior
Result list shows shared drive files

### Raycast version
Version: 1.38.3

**Comment by thomaslombart** [comment]
Thanks for the issue. We're currently discussing that in a PR: https://github.com/raycast/extensions/pull/2497 🙂

**Comment by thomaslombart** [comment]
This should be closed: cc @pernielsentikaer
