### ISSUE TITLE
[Linear] Not showing any issues in CreatedIssues or AssignedIssues

### ISSUE THREAD

**Issue by shaikegross** [raycast/extensions#2519]
# Extension – [Linear](https://github.com/raycast/extensions/tree/7bca0e21329cf1b13420ed396a4bcb02895b6579/extensions/linear/)
Author: @thomaslombart

[Linear] Not showing any issues in CreatedIssues or AssignedIssues even though such issues exists and are visible in the SearchIssues Command

## Description
Fails to show me issues that were assigned to me. in the last version of the extension this worked. I am logged in and can see tasks that really are assigned to me in the `Search Issues` Command, but not via the `Assigned Issues` Command.

![image](https://user-images.githubusercontent.com/61117512/183824184-d863c2d8-5d9c-42ed-ab81-bf3c8d0cefb1.png)

## Steps To Reproduce

1. Create an issue
2.  Assign it to yourself via 
3. Run the `Assigned Issues` Command and see if the list is empty

## The current behavior
Searches for issues and then writes "No Issues"

## The expected behavior
It should search for issues and return the issues that are assigned to me

### Raycast version
Version: 1.38.3

**Comment by thomaslombart** [comment]
It's been fixed. @pernielsentikaer can you close this issue?
