### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by emreerkin** [raycast/extensions#2520]
# Extension – [Spotify API Bug](https://github.com/raycast/extensions/tree/943671d313fd2d25437c0e705909d5ece1f6ca5e/extensions/spotify-player/)
Author: @mattisssa

## Steps To Reproduce

1. Use any command. In this case, I use Search Playlists. 
2. Search for any playlist name, it shows the playlists properly
3. make sure you have not played any music on Spotify or used these commands for while, about 45 mins or so.

## The current behavior
After hitting play command, extension fails and generates the warning in the attached screenshot. 

## The expected behavior
It should play the desired song-playlist-artist properly. 
(Note: Restarting Raycast or playing something manually on Spotify fixes the issue temporarily. After an hour of inactivity bug reproduces itself. Both Raycast and the extension are up to date)

### Raycast version
Version: 1.38.3
<img width="750" alt="d7bcc3930864948b6d215d41fd29a19e1f7561c3088024e88e481f800fba01a4" src="https://user-images.githubusercontent.com/65477917/183847850-90a9ac1d-96b7-475c-8a10-a1bf8d8b6a54.png">

**Comment by mattisssa** [comment]
Hey! The issue has been fixed recently, could you please check for updates and ensure it still happens for you?

<img width="767" alt="CleanShot 2022-08-10 at 11 09 13@2x" src="https://user-images.githubusercontent.com/15333662/183849727-7b18c412-4272-4adb-b9d8-f48a62489a25.png">

**Comment by emreerkin** [comment]
Thanks for the quick response. I did check for updates and everything seems to be updated. I also tried uninstalling and reinstalling the extension, however bug has remained consistent.

**Comment by mattisssa** [comment]
Should be fixed in the update, please let me know if it's not 😉

**Comment by michaelmior** [comment]
@mattisssa I don't see any update available to the extension.
