### ISSUE TITLE
[Vercel] show the github branch linked to a deployment

### ISSUE THREAD

**Issue by dgrcode** [raycast/extensions#2530]
# Extension – [Vercel](https://github.com/raycast/extensions/tree/2e6f0e021e7ad787369e9f120f536a9dd6ec5b61/extensions/vercast/)
Author: Max Leiter

**Describe the feature and the current behavior/state.**

Right now the information available is:
- coloured dot. I'm not sure if this shows status, since all I see is green points
- commit name
- project
- status
- time

I'd like to see a new column showing the branch or the domain (most of the time linked I guess) related to the deployment. In my case I'd like to see if the deployment is for my `main` branch, linked to my production domain, or the `staging` branch, linked to "staging.{domain}"

I'd add it just before the commit name, since commit and branch are closely related.

**Who will benefit with this feature?**
I think every user who has multiple branches deployed or multiple subdomains.

**Any Other info.**
I'm happy to work on this, but I'm unsure where to start. I know there's documentation both for vercel api and raycast extensions. From looking at them, it's not very clear to me if this is an easy task, since I haven't seen that info returned by vercel's api -at least in a single call–.

**Comment by MaxLeiter** [comment]
I'd really appreciate a PR with this feature!

The data is currently available, it's just not well documented. 

Each deployment made via git should have a `meta` object with one of `githubCommitRef`, `bitbucketCommitRef`, or `gitlabCommitRef`

**Comment by dgrcode** [comment]
Nice! I'll get started on it then :)

I need to read some docs and setup the dev environment for raycast extension development, but I should have something to share soon 🤞 

I'll keep you updated here.
