### ISSUE TITLE
[Linear] Todo status icon is very hard to see in light mode

### ISSUE THREAD

**Issue by nhojb** [raycast/extensions#2534]
# Extension – [Linear](https://github.com/raycast/extensions/tree/main/extensions/linear)

Author: @thomaslombart 

## Description

Todo status icon is very hard to see in light mode

<img width="767" alt="Screenshot 2022-08-11 at 11 51 35" src="https://user-images.githubusercontent.com/312540/184122383-43594604-b51f-4e84-bba0-8c0d21fa7f0b.png">

## Steps To Reproduce

1. Switch to light mode in Raycast
2. Open _Create Issue_ command
3. Select the _Status_ menu. The Todo icon is almost invisible.

### Raycast version

Version: 1.38.3

**Comment by thomaslombart** [comment]
The status icons show the same colors as these on Linear, so this could happen for any other status icons. Maybe it'd be worth it to provide a function under `@raycast/utils` or something else to automatically adjust the contrast between a color and the background if it's not accessible enough?
