### ISSUE TITLE
[Spotify Player] Just Play always errors

### ISSUE THREAD

**Issue by michaelmior** [raycast/extensions#2537]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/943671d313fd2d25437c0e705909d5ece1f6ca5e/extensions/spotify-player/)
Author: @mattisssa

## Description

When I try to use Just Play, I get an error message

## Error:
```
TypeError: Cannot read properties of undefined (reading 'items')

Object.s0:justPlay.js:112:1431

---
109:   else
110:     set shuffling to true
111:   end if
112: end tell`};async function JS(e){let t=await am();await im(rm.playTrack(t,e))}async function ZS(){let e=await am();return await im(rm.isRunning(e))==="true"}function e0(e){return`${e.artists[0].name} \u2013 ${e.name}`}async function am(){let t=(await(0,da.getApplications)()).find(i=>i.bundleId?.includes("spotify"));return t?t.name:(await(0,da.showToast)({style:da.Toast.Style.Failure,title:"Check if you have Spotify app is installed on your Mac"}),"Spotify")}var om=new n0.default;async function i0(){try{await f_()}catch(t){console.error("authorization error:",t),(0,hr.showToast)({style:hr.Toast.Style.Failure,title:String(t)});return}let e=(await mr.getTokens())?.accessToken;e?om.setAccessToken(e):(0,hr.showToast)({style:hr.Toast.Style.Failure,title:"Invalid accessToken"})}async function r0(e,t){try{await ZS()?(await i0(),await om.play({uris:e?[e]:void 0,context_uri:t})):JS(e??t??"")}catch(i){await(0,hr.showToast)({style:hr.Toast.Style.Failure,title:"Failed Start Playing",message:i.message})}}async function a0(e,t){await i0();try{return{result:await om.searchTracks(e,{limit:t}).then(a=>a.body).catch(a=>({error:a.message}))}}catch(i){return{error:i.message}}}async function s0(e){if(!await p_()){(0,ai.showToast)(ai.Toast.Style.Failure,"Unauthorized","\u26A0\uFE0F Please open any view-based command and authorize to perform the command.");return}let i=await a0(e.arguments.query,1),a=(0,o0.default)(i.result?.tracks.items).first();a?(await r0(a.uri),await(0,ai.showToast)(ai.Toast.Style.Success,`${ai.environment.theme=="light"?"\u{1F3B5}":"\u266B"}  ${e0(a)}`)):await(0,ai.showToast)(ai.Toast.Style.Failure,"Track is not found!")}module.exports=t1(KF);0&&(module.exports={});
113: /*!
114:  * methods
115:  * Copyright(c) 2013-2014 TJ Holowaychuk
---

async MessagePort.<anonymous>:index.js:1:2475
```

## Steps To Reproduce

1. Choose the Just Play command
2. Enter any text
3. Hit enter

## The current behavior

I get a "Something went wrong" display

## The expected behavior

Music would start playing

### Raycast version
Version: 1.38.3

**Comment by mattisssa** [comment]
Do you still have the issue? I couldn't reproduce it anyhow. 
If yes, please add more details what setup do you have. Do you have Spotify app open when it happens? Are you signed in?

**Comment by michaelmior** [comment]
Yes. I still have this issue regardless of whether or not the Spotify app is open. I am signed in.

**Comment by dancannon** [comment]
Hi, it might be useful to hear what query string you are providing. My best guess is that whatever you are providing is returning zero items which is causing this issue.

**Comment by michaelmior** [comment]
@dancannon It happens for any query string. But even if that were the case, shouldn't Raycast just show that there are no results rather than producing an error?

**Comment by dancannon** [comment]
Absolutely although if its happening for any query string then it suggests that there is another issue that also needs to be fixed. Internally the `Just Play` command searches for a track before playing it. Could you please try searching for a track using the  `Search Tracks` command and see what response you get there?

**Comment by michaelmior** [comment]
I get `Search has failed read ECONNRESET`
