### ISSUE TITLE
[HackerNews] Failed to load content 

### ISSUE THREAD

**Issue by guntiskarulis** [raycast/extensions#2539]
# Extension – [HackerNews](https://github.com/raycast/extensions/tree/main/extensions/hacker-news)

Author:@thomaspaulmann

## Description
Failed to load stories: 

<img width="770" alt="image" src="https://user-images.githubusercontent.com/85251380/184314250-b8a505fe-f0c1-4078-9e38-bc9d559206f7.png">

## Steps To Reproduce

1. Launch Raycast
2. Type `Hacker News` and hit `enter`
3. Observe error: `Failed loading stories / Error code 429`

## The current behavior
Extension is unable to load stories from Hacker News

### Raycast version

Version: 1.38.3

### System information

OS: macOS Monterey
Version: 12.5

**Comment by thomaspaulmann** [comment]
The issue was addressed, clsing for now.
