### ISSUE TITLE
[Extension Feature Request] Copy Password or fields in 1Password

### ISSUE THREAD

**Issue by jiserra** [raycast/extensions#254]
## Extension – [1Password](https://github.com/raycast/extensions/tree/main/extensions/1password7)
**Author**: @khasbilegt 

## Description
This is not a bug, this is a feature request, but I don't know how to post this. Feel free to remove it or tag it differently.

@khasbilegt It would be great if there was an action to `Copy password` instead of just `Open and Fill`. Most of the time I use the browser extension to fill passwords, but when the browser extension doesn't work or when I want to fill the password (or certainly another field in the 1Password record), I have to open 1Password and copy that. I would use this extension a ton for that use case.

Thanks!

**Comment by mattisssa** [comment]
Hey @khasbilegt! 
Here is the new feature request to your extension, take a look at that and subscribe to don't miss anything related 😉

**Comment by selfish** [comment]
Unfortunately, I'm afraid that isn't possible through the 1password CLI.
The encrypted data (password and secure fields) is just not exposed, so it won't be accessible. =\
I wish it was possible though

**Comment by argamanza** [comment]
@selfish @khasbilegt please take a look at [this bunch of scripts](https://github.com/argamanza/script-commands/tree/1password/commands/password-managers/1password) I made for personal use.

It's not the fastest and surely not optimized but it does what I need (I copy/paste passwords a lot in work).

**Comment by jiserra** [comment]
Thanks @argamanza! I'm trying to use your scripts, but I can't seem to log in, it tells me to check my credentials. I'm doing the raw commands on the Terminal and everything works (I obtain a token, etc) but whenever I run the "Status" command on Raycast, it always says "Sign Out". Any clues on what can be happening?

**Comment by argamanza** [comment]
> Thanks @argamanza! I'm trying to use your scripts, but I can't seem to log in, it tells me to check my credentials. I'm doing the raw commands on the Terminal and everything works (I obtain a token, etc) but whenever I run the "Status" command on Raycast, it always says "Sign Out". Any clues on what can be happening?

I have no clue... Could you try running all the steps (or at least sign in, status) with `# @raycast.mode inline` and paste the output here?

**Comment by jiserra** [comment]
The weirdest thing happen, now the status is working! Anyway, now when I try to use the "Copy Best Matching Password" command, it tells me that the 1Password CLI is not installed. I changed the line 29 and instead of checking for `bw` I'm checking for `op` and now is working. My questions for you is why you were checking for `bw`? What's that command?

**Comment by argamanza** [comment]
> The weirdest thing happen, now the status is working! Anyway, now when I try to use the "Copy Best Matching Password" command, it tells me that the 1Password CLI is not installed. I changed the line 29 and instead of checking for `bw` I'm checking for `op` and now is working. My questions for you is why you were checking for `bw`? What's that command?

I was using the script command for Bitwarden as inspiration so there's a chance I missed some usage of `bw` which is the Bitwarden CLI tool.

**Comment by mieubrisse** [comment]
Big +1 to this issue - I'd love to use Raycast+1Password extension to copy my password so I can use it for desktop apps like Slack, Todoist, and Google Calendar!
