### ISSUE TITLE
Make it possible to contribute to a single extension without having to download a big repo

### ISSUE THREAD

**Issue by dgrcode** [raycast/extensions#2541]
Raycast version: 1.38.3

**Describe the feature and the current behaviour/state.**
I want to contribute to one extension, so I have cloned this repo, which totals 3.5 GB. This might easily be the biggest folder in my computer at the moment.

Most of the weight comes from "/extensions" (1.56 GB) and "/.git" (1.88 GB). Those two folders grow proportionally with the amount of extensions, which is only going to keep growing. I don't think it's scalable to download all the extensions, especially as the number reach the thousands, which will happen quite soon 😄

I don't really have a suggestion, since I've never had to manage a repo like this. I'm opening this hoping someone has better ideas as this repo grows.

**Comment by alejgarciarodriguez** [comment]
I am facing the same issue. Maybe git submodules? Idk

**Comment by dgrcode** [comment]
I've never used git submodules before, but from what I'm reading in [the docs](https://git-scm.com/book/en/v2/Git-Tools-Submodules) it sounds like a nice solution for this use case.

One thing I don't know is how much complexity this adds on the git side. Like, could someone just download a submodule using the interface in github? (I mean the clone button on the top right of each repo)

The initial solution I thought about was having one repo per extension. The problem I see with that approach is that it'd make very hard to add new extensions, since you'd need someone in Raycast to open a repo for you. Contributing to existing extensions would be super easy.

The separate repos approach is also what I've seen in other projects that face this kind of "store" of open source packages situation. For example, webpack and their loaders. I've found [this list of loaders](https://github.com/webpack/docs/wiki/list-of-loaders), where each loader is a separate repo, and most of them are even owned by users different than webpack.

I don't think webpack has the concept of "store" where people browse what to add. It's more like someone who needs a loader will find their way to the loader, via google, stackoverflow, or something else. I don't think that part would work with Raycast, but there might be a solution for the store side that still allows for separate repos.

Just thinking out loud 🤷

**Comment by mathieudutour** [comment]
`ray publish` can now be used on public extensions. Simply run `npx ray publish` (after having updated the API) in your extension folder and it will automatically fork, clone, open a PR in a matter of seconds.

More info here: https://raycastapp.notion.site/ray-publish-c7209e1bd00a4858a68f13d9095910ea

_This is a beta feature and things might break (hopefully gracefully). We aren't updating the developer docs just yet but would love your feedback!_

**Comment by dgrcode** [comment]
I'm not sure I completely understood ray publish. After looking at the notion doc I've tried to "Fork Extension" but haven't found the way to do it. So I haven't been able to test if I could actually contribute without downloading all the other extensions.

Where can I find the "Fork Extension" action?

**Comment by mathieudutour** [comment]
it's an action on any commands in the root search

**Comment by dgrcode** [comment]
Awesome! I've just checked it's exactly what I wanted :)

I was trying to find it from the extension store, selecting one of the extensions and looking at the actions. Selecting the actions from the commands did work 👍
