### ISSUE TITLE
[Datetime Format Converter] default time format should be in 24-hour format, not ambiguous 12-hour

### ISSUE THREAD

**Issue by huyz** [raycast/extensions#2546]
# Extension – [Datetime Format Converter](https://github.com/raycast/extensions/tree/main/extensions/datetime-format-converter)

Author: @yangxyo 

## Steps To Reproduce

1. Submit `2022-08-12`
2. You will see:
    ```
    2022-08-12 12:00:00
    2022-08-12T00:00:00-07:00
    ```

## The current behavior

The first line is: `2022-08-12 12:00:00`

## The expected behavior

The first line should be `2022-08-12 00:00:00`

https://github.com/raycast/extensions/blob/492357ec729c62d8e78abfcf239cee640d8048fe/extensions/datetime-format-converter/src/index.tsx#L27
should say:
```js
      dTime.format("YYYY-MM-DD HH:mm:ss").toString(),
```
with `HH` instead of `hh`

### Raycast version

Version: 1.38.3

**Comment by huyz** [comment]
This should not be closed. It's a bad bug

**Comment by huyz** [comment]
Ok well the author doesn't want to fix his extension.  So clearly this extension should be removed from the gallery

**Comment by mathieudutour** [comment]
That's a bit harsh, feel free to open a PR to fix the bug, seems like you know where it is already!

**Comment by huyz** [comment]
I'm equally annoyed at this 2-week bot haha
