### ISSUE TITLE
[Projects] Support Gradle Kotlin DSL

### ISSUE THREAD

**Issue by beomjungil** [raycast/extensions#2548]
# Extension – [Projects](https://github.com/raycast/extensions/tree/main/extensions/projects)

Author: @ajaypremshankar @pernielsentikaer

**Describe the feature and the current behavior/state.**

Currently, `Projects` only support  `build.gradle` file for Gradle Project.
https://github.com/raycast/extensions/blob/2a70dd20b5d7320cac5e5ef38067cdbbeb7f7f3e/extensions/projects/src/application-config.json#L19-L26

It would be nice if `Projects` plugin  add support for [Gradle Kotlin DSL](https://docs.gradle.org/current/userguide/kotlin_dsl.html) with `build.gradle.kts` file. 

You can add like below.

```json
 { 
   "type": "gradle", 
   "finder": "build.gradle.kts", 
   "finderType": "file", 
   "icon": "gradle.png", 
   "spotlightQuery": ["kMDItemDisplayName == build.gradle.kts"], 
   "openWithKey": "openGradleWith" 
 }, 
```

**Who will benefit from this feature?**

Probably Android Developers who use raycast.

**Comment by pernielsentikaer** [comment]
Can you check this @ajaypremshankar
