### ISSUE TITLE
[Search Zotero] Can't copy BibTeX citation key

### ISSUE THREAD

**Issue by michaelmior** [raycast/extensions#2549]
# Extension – [Search Zotero](https://github.com/raycast/extensions/tree/ff2962d923ce14ec58885e84455de4905f063995/extensions/zotero/)
Author: @sadanand-singh

## Description

After searching for citation, I use the shortcut to copy the citation key and just get an error message.

## Error (truncated due to size limit):
```
TypeError: Cannot read properties of undefined (reading 'toString')

onAction:index.js:13:18501

---
10:             '${c}' is not a member of [${a.map(u=>`'${u.value}'`).join(", ")}].`)}}o.suggestionValues=a;break}}rm(o,e.id,"onBlur","blur",e.onBlur,e.name=="ray-form-datepicker"),rm(o,e.id,"onFocus","focus",e.onFocus,e.name=="ray-form-datepicker");let n=e.onChange;return!o.onChange&&n&&ie(o,"onChange",async a=>{B.batchedUpdates(n,a)}),o}function Qw(e,t,r){let o={nodeId:`${t.nodeId}_items_${r}`,path:`${t.path}/items/${r}`,title:e.title,value:e.value,icon:e.icon};Se(o);let n=e.value;return n&&!n.length&&console.warn(`You shouldn't use empty value for Tag Picker Item ${e.title}`),o}function rm(e,t,r,o,n,a=!1){!n||ie(e,r,async s=>{a&&(s=am(s));let c={target:{id:t,value:s},type:o};B.batchedUpdates(n,c)})}function am(e){let t=Date.parse(e);if(isNaN(t)==!1)return new Date(t)}var Vi=T(()=>{je();Yt();Ye();ot();$e()});function sm(e,t){switch(t.name){case"ray-action-panel":{pe(t,'A `Detail` does not accept any children. Ignoring "'+t.name+'".')&&
---

Object.v.batchedUpdates:react-reconciler.production.min.js:7:49891
index.js:6:13041
index.js:6:11057
    at new Promise (<anonymous>)
Io:index.js:6:10919
MessagePort.<anonymous>:index.js:1:2492
MessagePort.[nodejs.internal.kHybridDispatch]:event_target:559:20
MessagePort.exports.emitMessage:messageport:23:28
```

## Steps To Reproduce

1. Search for any reference
2. Press the shortcut for copying the citation key

## The current behavior

Using the "Copy Bibtex Citation Key" command produces an error

## The expected behavior

The citation key should be copied to the clipboard

### Raycast version
Version: 1.38.3

**Comment by splnkr** [comment]
Same problem here. Better bibtex json file does work with Alfred "supercharged citation picker" workflow. 

As for Raycast:
Searching for citations works. Also open pdf or in zotero. Other than those three commands do not work.

**Comment by splnkr** [comment]
I do not know what changed, but somehow everything works now. Just tried everything. Just a few minutes ago except copying and pasting references functions but now references do also work. That is really strange.

**Comment by augustebaum** [comment]
Testing to see if commenting will re-open the issue -- otherwise I'll open a duplicate.
