### ISSUE TITLE
[HowLongToBeat] Throws 404 upon opening or search for a game

### ISSUE THREAD

**Issue by RobErskine** [raycast/extensions#2551]
# Extension – [HowLongToBeat](https://github.com/raycast/extensions/tree/9811c1e1884f4577ef809dcd2ed62d85eaea84ff/extensions/how-long-to-beat/)
Author: @Cronos87 

## Description
Opening the How Long To Beat Raycast app immediately fires off a 404. Attempting to search for a game also returns a 404. I freshly installed the extension today.

![How Long to Beat is throwing a "Could not Perform Search"](https://p198.p4.n0.cdn.getcloudapp.com/items/z8umykle/041e7c01-f1d7-41af-8774-5fb4eeae6f74.jpg?source=viewer&v=0247552bbd41ecfa9a65d8e51fd9fd8f)

## Steps To Reproduce

1. Attempt to open How Long to Beat Raycast extension and see error
2. Attempt to search for a game and receive an error

## The current behavior
Attempting to use the extension always throws a 404

## The expected behavior
Games should load in and show how long it takes to beat them

### Raycast version

Raycast Version 1.38.3

**Comment by Cronos87** [comment]
Hello! Thank you for creating the issue.
I'm the develop of the extension. Yes indeed I noticed it too. I didn't have much time to fix, I am sorry about this.

I'll do my best to submit a PR this soon as I'm in holidays now.

In the meanwhile, thank you to download my extension. I hope you will enjoy it!

**Comment by Cronos87** [comment]
I fixed the issue with the PR #2557. I hope you will enjoy the extension :)

<img width="862" alt="CleanShot 2022-08-13 at 12 08 22@2x" src="https://user-images.githubusercontent.com/1923206/184479128-9ca6a87b-2601-47fd-b9f1-c048726eb44f.png">

**Comment by Cronos87** [comment]
Is it okay for you @RobErskine as the extension as been updated in the store?

**Comment by RobErskine** [comment]
@Cronos87 I can confirm I was able to use the Raycast `update` command and after that the extension works beautifully! Thank you for the timely fix.

---

![searching for pokemon in the howlongtobeat raycast extension](https://p198.p4.n0.cdn.getcloudapp.com/items/qGuO901m/ff1f95dd-ab31-4195-8f47-720743d67a7b.jpg?v=36dfafc083bd1d5630413d927b797b49)

**Comment by Cronos87** [comment]
Lovely! I hope you will enjoy it!
Don't hesitate if you have suggestions to enhance it 😉
