### ISSUE TITLE
[Google Fonts] An action to open fonts.google.com

### ISSUE THREAD

**Issue by rolandleth** [raycast/extensions#2554]
# Extension – [Google Fonts](https://github.com/raycast/extensions/tree/09e61ff210533eaaf4d9be5f9e35ce428a8d9be2/extensions/google-fonts/)
Author: @GastroGeek 

**Describe the feature and the current behavior/state.**
After searching a font (or after selecting variants), having an action to open the font on fonts.google.com would allow an easy way to download the font.

**Who will benefit with this feature?**
Everyone who needs to download a font.

**Comment by GastroGeek** [comment]
Good idea @rolandleth - I've just PR'd both _view_ and _download_ actions 🤞
