### ISSUE TITLE
Cannot detect Visual Studio Extension Project Manager is installed

### ISSUE THREAD

**Issue by Yu-Qi** [raycast/extensions#2556]
# Extension – [Visual Studio Code - Project Manager](https://www.raycast.com/MarkusLanger/vscode-project-manager)

## Description

I already install Raycast extention(Visual Studio Code - Project Manager) and Vscode extention (Project Manager)
But after selecting "Search project manager" in Raycast, it shows "To use this extension, the Visual Studio Extension [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) is required."

What I had tried:
- Restart vscode
- Restart Raycast
- Reinstall vscode extention
- Reinstall Raycast extention

Versions:
- Vscode: 1.67.2
-  Vscode extention (Project Manager): v12.6.1
- Raycast 1.38.3

Someone know how to make it work? Thx!!!

**Comment by strategyagents** [comment]
Same issue

**Comment by Yu-Qi** [comment]
I fix it :)
First you need to save a project with project manager on the vscode. And then it works~~~
