### ISSUE TITLE
hello,May I ask how to change the time zone? Because the time zone set by your template is different from mine, the daily log reminder time is incorrect Hypersonic] ...

### ISSUE THREAD

**Issue by bestsummer1988** [raycast/extensions#2574]
hello sir
May I ask how to change the time zone? Because the time zone set by your template is different from mine, the daily log reminder time is incorrect

**Comment by hdecoded** [comment]
Facing a similar issue. Tasks are not showing up in the todo view until I add a time to them

**Comment by ItsJamesMurray** [comment]
... this might explain why I've never gotten a reminder for any task.
