### ISSUE TITLE
[Bitwarden Vault] New secure note not found

### ISSUE THREAD

**Issue by conradolucas** [raycast/extensions#2580]
# Extension – [Bitwarden Vault](https://github.com/raycast/extensions/tree/ff516d809e0817bcf57138675627249a22d25889/extensions/bitwarden/)
Author:

## Description
After installed this extension, if you create a new secure note, this new note will not be found in the extension

## Steps To Reproduce

1. Add a new secure note 
2. Find the new secure note via raycast

## The current behavior
Secure note not found

## The expected behavior
Found and access new secure note 

### Raycast version
1.38.3

**Comment by join3r** [comment]
I couldn't replicate your issue. Did you sync your vault after you've added the note?
![CleanShot 2022-08-16 at 08 46 48](https://user-images.githubusercontent.com/20800445/184815540-088aa1c6-44f8-428a-b1a0-f268eafc5d02.png)
