### ISSUE TITLE
[Google Workspace] new plugin missing files upon search

### ISSUE THREAD

**Issue by kris-at-unity** [raycast/extensions#2582]
# Extension – [Google Workspace](https://github.com/raycast/extensions/tree/2e371837b4ea93b23bddec1d56729a689082be3b/extensions/google-workspace/)
Author:

## Description

The new search is missing files. There also seems to be files found and opened in "view" mode even though those are my files that should have been opened in edit mode.

I never encountered those issues with the old plugin, but the new one is missing tons of files from the search.

## Steps To Reproduce

I only have reliable ways to reproduce this in my workspace's files thus it's not helpful to list those here.

**Comment by pycckuu** [comment]
Same happens to me.

**Comment by kris-at-unity** [comment]
Found the same topic being discussed in [2497](https://github.com/raycast/extensions/pull/2497).
Closing this thread.
