### ISSUE TITLE
[Linear]  -stuck in sign in loop...

### ISSUE THREAD

**Issue by oba2311** [raycast/extensions#2585]
# Extension – [Linear](https://github.com/raycast/extensions/tree/2e371837b4ea93b23bddec1d56729a689082be3b/extensions/linear/)
Author: @thomaslombart

See:

https://user-images.githubusercontent.com/8249349/184864366-481ec24b-db65-427f-81f2-1d1d42fee831.mp4

### Raycast version
Version: 1.38.3

**Comment by thomaslombart** [comment]
Thanks for reporting! It seems something got broken when adding Raycast to Linear applications. I'll take a look.

**Comment by thomaslombart** [comment]
@oba2311 could you retry authenticating? To do so, please log out from Raycast (that will remove the stored tokens) and revoke access to the Raycast app in Linear's applications.

I was able to reproduce the error and I'm no longer stuck. It seems that something's happening on Linear's end and adding the application got extremely long.

**Comment by oba2311** [comment]
Works like a charm!

**Comment by thomaslombart** [comment]
@pernielsentikaer Could you close this issue, please? 🙂

**Comment by pernielsentikaer** [comment]
Yes of cause @thomaslombart 🙂
