### ISSUE TITLE
[GitHub Gist] ...

### ISSUE THREAD

**Issue by Aayush9029** [raycast/extensions#2607]
# Extension – [GitHub Gist](https://github.com/raycast/extensions/tree/c489b98079539b6d36831197794eec464532222f/extensions/github-gist/)
Author: @koinzhang

## Description
Completely BUGS out Raycast rendering it completely useless.
## Steps To Reproduce

1. Launch Raycast
2. Run Search Gists Command.

## The current behavior
Video: https://share.cleanshot.com/2Xp6d1
- Frozen Raycast window (CPU Spike), no way to quit it

## The expected behavior
- Show gists and details

### Raycast version
Version: 1.38.3

**Comment by koinzhang** [comment]
Hi @Aayush9029. I'm sorry you encounter this kind of problem, but I can't reproduce this problem now and can't provide a solution for the time being

**Comment by Aayush9029** [comment]
Apparent the extension was having trouble rendering large files!

I'm assuming it's a raycast limitation so I closed this issue!
