### ISSUE TITLE
[GitLab] How to find a MR list whose author is mine

### ISSUE THREAD

**Issue by 404J** [raycast/extensions#2612]
# Extension – [GitLab](https://github.com/raycast/extensions/tree/4185a959e2bf8574d1015467cf9a53196507191e/extensions/gitlab/)
Author: @tonka3000

**Describe the feature and the current behavior/state.**
I can't use My Merge Requests command to filter through author

**Comment by tonka3000** [comment]
Hi @404J ,

You can do the by type `author=<username>` in the search bar. Most of the GitLab filters are supported that way. You can also use `author!=<username>` to get the opposite result.

![CleanShot 2022-08-18 at 18 04 36@2x](https://user-images.githubusercontent.com/3163807/185442097-69671978-fc59-41d6-8b9f-63522e57a1b5.png)

Raycast has no native feature for that, so there is no auto-completion or something for now (see #88 or #87).

Greetings
Michael

**Comment by 404J** [comment]
Get it! @tonka3000
