### ISSUE TITLE
Getting this error while trying to add a task to Shortcut

### ISSUE THREAD

**Issue by exist2021** [raycast/extensions#2631]
ok, for some reason suddenly the shortcut stories are not getting created.

![Screenshot 2022-08-20 at 1 28 54 PM](https://user-images.githubusercontent.com/83490199/185735296-1828efc8-49ab-40d3-bab4-af6ef3225943.png)

![Screenshot 2022-08-20 at 9 32 42 AM](https://user-images.githubusercontent.com/83490199/185735248-b60f4b43-7d0f-4ce3-a04b-e36c1873034c.png)

**Comment by thomaspaulmann** [comment]
@Yukaii can you help with this?

**Comment by Yukaii** [comment]
OK I'll look into this

**Comment by Yukaii** [comment]
Hi @exist2021,

1. Could you help me check your workspace setting, and whether **projects** and **fields** are enabled?

These two are under avatar -> settings -> workspace features(side panel)

<img width="494" alt="スクリーンショット 2022-08-23 午後9 36 38" src="https://user-images.githubusercontent.com/4230968/186173566-7ab54e8b-c1dd-4b50-8487-609e2fc267e7.png">

<img width="849" alt="スクリーンショット 2022-08-23 午後9 39 52" src="https://user-images.githubusercontent.com/4230968/186173594-c841cfcb-e843-4541-9d72-1f5d0c225b4d.png">


2. Could you try to create a story with minimal fields, that only have `title`, `workflow`, `state`, and `type`?

**Comment by exist2021** [comment]
Hey, Project was on but 4/5 fields were disabled as I thought I won’t need
all of them, but now enabled all and created the story. This issue is
resolved.

Thank You
[image: Kind regards,]
[image: photo]
Manoj R Nayak
Wrting, Marketing & Building
A  Mumbai, India
M +91 9892334681
E ***@***.***
W http://manojnayak.com  <http://manojnayak.com/>
Whatsapp 9819392681
<http://fb.com/manoj.nayak> <http://linkedin.com/in/manojrnayak>
<http://twitter.com/manojnayak>

**Comment by Yukaii** [comment]
Hi @exist2021 thanks for the update, I think I still need to handle the case when fields are disabled.

**Comment by exist2021** [comment]
That would be nice, as I don’t need so many fields in my shortcut setup.
Have enabled currently, but if gets in the way might disable the same.
Thank you
