### ISSUE TITLE
Google Workspace search google drive files functionality

### ISSUE THREAD

**Issue by anthonyduynguyen** [raycast/extensions#2636]
# Extension – [Google Workspace](https://github.com/raycast/extensions/tree/2e371837b4ea93b23bddec1d56729a689082be3b/extensions/google-workspace/)
Author:

**Describe the feature and the current behavior/state.**
Allow search google drive files that search files that are in shared drives as well.

**Who will benefit with this feature?**
Google drive user who would like to search for files within different shared drives.

**Any Other info.**
That is all. Thank you for your time.

**Comment by setu4993** [comment]
+1, same request.
