### ISSUE TITLE
[API Bug] Last inserted Korean character gets ignored when submitting a form

### ISSUE THREAD

**Issue by jcha0713** [raycast/extensions#2647]
OS: MacOS Monterey 12.3
Raycast version: 1.39.1

## Description

Hi, I'm observing another issue with Korean character inputs and not entirely sure if this is an expected behavior. 

When submitting a form using the `Action.SubmitForm` component, if the cursor(underbar) is still on the last character I typed, that character does not get submitted. Here is a quick demonstration:

https://user-images.githubusercontent.com/29053796/185815396-58ed6164-85f7-44d4-9403-59ebf45704fb.mp4

I first type `안녕` but when I submit the form I only see the first letter, `안` in my console.
Then I type `안녕하세요`, and again, I see everything but the last letter. So `안녕하세` instead of `안녕하세요`.

This is problematic because in many programs the last character also gets inserted or submitted even if the cursor is on it. To avoid this as a user, one should either insert a new line character by pressing the return key(on Mac) or press any arrow keys to manually move the cursor.

## Steps To Reproduce

1. Create a new extension with the `Create Extension` command
2. Add the following to the main `.tsx` file

```jsx
import { Action, ActionPanel, Form } from "@raycast/api";

export default function Command() {
  return (
    <Form
      actions={
        <ActionPanel>
          <Action.SubmitForm title="Submit Description" onSubmit={(values) => console.log(values)} />
        </ActionPanel>
      }
    >
      <Form.TextArea id="description" />
    </Form>
  );
}
```

3. Run `npm install && npm run dev`, type any words in Korean, and submit the form

## The current behavior

If I type `안녕` and submit the form while the cursor is on the last character, that character gets ignored and not submitted.

`안녕` -> `안`

## The expected behavior

If I type `안녕` and submit the form,
the whole word must be submitted without losing the last character.

`안녕` -> `안녕`

**Comment by mathieudutour** [comment]
Should be fixed in the latest release
