### ISSUE TITLE
[GitHub Repository Search] Filter for my repositories 

### ISSUE THREAD

**Issue by Rawnly** [raycast/extensions#2648]
# Extension – [GitHub Repository Search](https://github.com/raycast/extensions/tree/efba3ec1978c17317a96bcdcaa914f9153839e04/extensions/github-repository-search/)
Author: @thomaspaulmann 

**Describe the feature and the current behavior/state.**
I'd like to be able to filter the search scope to my repos

**Who will benefit with this feature?**
Is useful to rapidly open repos you're working on, or search old ones without opening the browser.

**Comment by thomaspaulmann** [comment]
Can you explain this a bit further? There is a PR that adds a dropdown to filter organizations. Is that what you mean?

**Comment by Rawnly** [comment]
> There is a PR that adds a dropdown to filter organizations

Yeah exactly that but also with personal repos!

**Comment by pjlamb12** [comment]
I'd love to be able to see organizations that I'm a part of, but I don't. Is there something I need to do so they show up?

**Comment by thomaspaulmann** [comment]
Do you want to see the organizations or the repositories of the organizations that you are part of?

**Comment by thomaspaulmann** [comment]
Do you want to see the organizations or the repositories of the organizations that you are part of?

**Comment by pjlamb12** [comment]
Both I guess, but more importantly the repositories of the organizations.

**Comment by thomaspaulmann** [comment]
The new [GitHub Beta extension](https://www.raycast.com/raycast/github-beta) has this filter.
