### ISSUE TITLE
[Browser Bookmarks] Add "open in browser X" to actions panel

### ISSUE THREAD

**Issue by janek** [raycast/extensions#2661]
# Extension – [Browser Bookmarks](https://github.com/raycast/native-extensions/tree/98807c71c6ec589775952a250d7225b403e995f5/extensions/browser-bookmarks/)
Author:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/2146927/186129742-4e39785b-ed56-4161-89b3-baafe2c36109.png">

**Describe the feature and the current behavior/state.**
Currently, you open links in your default browser with `enter`. The suggestion is to add "Open in Chrome", "Open in Safari", etc. with shortcuts like `cmd+1`, `cmd+2` etc.

**Who will benefit with this feature?**
People that use something like [Browserosaurus](https://browserosaurus.com) or any of related solutions/hacks.

**Comment by aviagarwal1212** [comment]
+1 I would also like to decide where to open the bookmarks. Ideally, a setting to open it in the browser it originates from would be great!
