### ISSUE TITLE
[Google Search] FR: add a toggle for search history

### ISSUE THREAD

**Issue by StevenLi-DS** [raycast/extensions#2663]
# Extension – [Google Search](https://github.com/raycast/extensions/tree/60eb31ef24a707e9f658cbe02a2265e12c83b988/extensions/google-search/)
Author: @mblode 

**Describe the feature and the current behavior/state.**

Could you please consider adding a toggle to not remember search history? Right now, you have to manually clear it up every time. 
![CleanShot 2022-08-23 at 15 30 14](https://user-images.githubusercontent.com/33796896/186249498-c7cba671-c33b-4234-83db-8b6b0de6a5d9.png)

**Who will benefit with this feature?**
Those who don't want to keep a record of their search history

**Any Other info.**

**Comment by mblode** [comment]
Sorry, GitHub notifications are the worst and I didn't see this. I'm going to work on this now
