### ISSUE TITLE
[Google Search] FR: add an action for copy suggestion to clipboard

### ISSUE THREAD

**Issue by StevenLi-DS** [raycast/extensions#2664]
# Extension – [Google Search](https://github.com/raycast/extensions/tree/60eb31ef24a707e9f658cbe02a2265e12c83b988/extensions/google-search/)
Author: @mblode 

**Describe the feature and the current behavior/state.**
Could you please consider adding an action to copy suggestion to clipboard. Right now, only copy URL is available.

![CleanShot 2022-08-23 at 15 35 24](https://user-images.githubusercontent.com/33796896/186250567-6559450d-d777-46b4-8ba5-11325f3a4d2a.png)

**Who will benefit with this feature?**
I found google search suggestion is quite useful sometimes. Here, I'm using it as a spell checker. You can also use it to find a person's name, a song's name, etc. In such case, you may only need to copy the suggestion without open the url.

**Any Other info.**

**Comment by mblode** [comment]
Sorry, GitHub notifications are the worst and I didn't see this. I'm going to work on this now
