### ISSUE TITLE
[Word Count] Character Count Not Accurate

### ISSUE THREAD

**Issue by tjex** [raycast/extensions#2683]
# Extension – [Word Count](https://github.com/raycast/extensions/tree/961bfeab1d9818409c4beca1d70b4d9d87fba3b5/extensions/word-count/)
Author: @itsmingjie 

## Description
Character count is inaccurate when compared to other word counters. 
## Steps To Reproduce

1. Use the extension as intended

## The current behavior
Counts fewer characters compared to multiple other word counters.

### Raycast version 1.39.1

![image](https://user-images.githubusercontent.com/83029642/186854968-40c635d0-61b8-4b32-88a4-d3ed00406c4c.png)   
![image](https://user-images.githubusercontent.com/83029642/186854983-4d99be66-142d-45ce-8a15-0fe3a7ee47ff.png)   
![image](https://user-images.githubusercontent.com/83029642/186854998-5eff009a-00ef-4d16-bca4-4f7899aa1eed.png)

**Comment by itsmingjie** [comment]
Hey @tjex -- sorry for the delay! Somehow missed this notification. This is because you have the "Include whitespace in character count" option unchecked on the bottom. Simply check that and you should be seeing the intended result.
