### ISSUE TITLE
[TickTick] ...

### ISSUE THREAD

**Issue by yujianing** [raycast/extensions#2686]
# Extension – [TickTick](https://github.com/raycast/extensions/tree/052379c800e422af268068cc9d724c146d0983c4/extensions/ticktick/)
Author: @viduycheung

## Description
![image](https://user-images.githubusercontent.com/17079751/186886067-5b960125-594d-479a-8d6c-ef36e313ee50.png)
## Steps To Reproduce

1. install ticktick
2. into the tick, display：application not found

### Raycast version
Version: 1.39.1

**Comment by viduy** [comment]
You need install TickTick macOS version first.
