### ISSUE TITLE
[Text Shortcuts] Add support for Chicago Manual of Style title capitalization

### ISSUE THREAD

**Issue by mxstbr** [raycast/extensions#2687]
# Extension – [Text Shortcuts](https://github.com/raycast/extensions/tree/main/extensions/text-shortcuts)

Author: @koinzhang

**Describe the feature and the current behavior/state.**

Support for Chicago Manual of Style title capitalization like title.sh (see https://github.com/vercel/title)

**Who will benefit from this feature?**

**Any Other info.**

**Comment by koinzhang** [comment]
Hi @mxstbr Sorry for taking so long to reply.
Thank you very much for still using the Text shortcuts extension, I will submit a PR to update TitleCase (using this library you mentioned)

**Comment by mxstbr** [comment]
Not stale.

**Comment by koinzhang** [comment]
Hi @mxstbr. Text Shortcuts already supports Chicago Manual of Style title capitalization in [this PR](https://github.com/raycast/extensions/pull/3270), I think this issue can be closed.

**Comment by mxstbr** [comment]
Ah, thank you!
