### ISSUE TITLE
npm install failed on m1 mac book pro

### ISSUE THREAD

**Issue by elevensky** [raycast/extensions#2690]
my mac booke info, it's m1 chip.
![image](https://user-images.githubusercontent.com/6904834/186944942-a821b014-a06d-44f5-a963-d5d3d346c8b2.png)

## Description

![image](https://user-images.githubusercontent.com/6904834/186944736-5ef8b5fd-6be3-42a5-beeb-74fc163876ba.png)
![image](https://user-images.githubusercontent.com/6904834/186945112-f98f2e44-fb40-41b8-a0c1-3de45693d1a3.png)
![image](https://user-images.githubusercontent.com/6904834/186945188-60630b50-10b5-4ab6-8d86-cabd274c6295.png)

### Raycast version

Version: 1.39.1

**Comment by crazyair** [comment]
mark
