### ISSUE TITLE
Linear: Missing emojis for projects

### ISSUE THREAD

**Issue by thomaspaulmann** [raycast/extensions#2695]
# Extension – [Linear](https://www.raycast.com/raycast/linear)

Author: @thomaslombart 

## Description

Looks like Linear added support for emojis to projects. This isn't yet supported and an empty icon shows up in the list. Raycast render standard emojis, but Linear also has custom one from Slack, which should also be renderable (just images at the end). 

## Steps To Reproduce

1. Create a project and assign an emoji
2. Open the Search Projects command
3. See the emoji not rendered

## The current behavior

Emoji isn't rendered

## The expected behavior

Emoji is rendered (custom and standard ones)

### Raycast version

Version:

**Comment by thomaslombart** [comment]
Good idea, I'll tackle that in the next few days/weeks.
