### ISSUE TITLE
[iTranslate] Add possibility to translate in both language and the same time 

### ISSUE THREAD

**Issue by UtopiaEH** [raycast/extensions#2715]
# Extension – [iTranslate](https://github.com/raycast/extensions/tree/b27c99a25cb59504391deee2044f4e89f6fdd7eb/extensions/itranslate/)

**Describe the feature and the current behavior/state.**
Now it work properly just want new feature )

**Who will benefit with this feature?**
It will help user which not know perfect one language to study for example I know 2 lang but I'm not sure how to translate it in both I can write something in my native see the translate in eng which I know bad  :D and translate it in the second to be sure if it is properly and do not lost the meaning.

**Comment by 404J** [comment]
@UtopiaEH Hi👋~Thanks for your valuable advice, this is a good idea, I will consider adding this feature in future versions.

**Comment by 404J** [comment]
@UtopiaEH Good news!🎉 iTranslate already support translating into multiple languages at the same time!!
check it out here: [iTranslate](https://www.raycast.com/JinShi/itranslate)

**Comment by UtopiaEH** [comment]
Ya it is exactly what I wanted thx you 
![drag-queen-kiss-gif-by-paramount](https://user-images.githubusercontent.com/25262913/190385765-3831a321-82e6-4cc1-8a6e-83425c5789c5.gif)
