### ISSUE TITLE
[Timers] ...

### ISSUE THREAD

**Issue by ryneb** [raycast/extensions#2724]
# Extension – [Timers](https://github.com/raycast/extensions/tree/6ead481b289b6072171326c1e5a8917c1e6cda3c/extensions/timers/)
Author:

Current: the timer finishes and the alarm sounds once. This is often sufficient, except when I'm deeply focused. In that state, the sound doesn't even register and I might as well not have even set a timer. 

Desired: When a timer is started, I can optionally select for it to have an alarm that persists until I dismiss the alarm.

**Comment by ThatNerdSquared** [comment]
Hey @ryneb, thanks for using Timers! I'm the primary maintainer - sorry I didn't catch this feature request earlier.

What kind of persistence are you looking for? Playing the sound over and over again until dismissed, playing it a set number of times, playing it again every X minutes until dismissed, etc.

I'm easily accessible on the Raycast Slack as `@ThatNerd(Squared)`, so feel free to reach out there as well.

**Comment by ThatNerdSquared** [comment]
We had a discussion on Slack to clear up some details related to the proposed functionality - just created #2858 to address this along with some other fixes to Timers.
