### ISSUE TITLE
[Google Chrome] ...

### ISSUE THREAD

**Issue by gravicle** [raycast/extensions#2725]
# Extension – [Google Chrome](https://github.com/raycast/extensions/tree/efba3ec1978c17317a96bcdcaa914f9153839e04/extensions/google-chrome/)
Author: @rgomezcasas

## Description
Extension crashes when trying to search Chrome history
![ScreenCapture-2022-08-29-15 09 54-Google Chrome](https://user-images.githubusercontent.com/1091114/187307755-0eb64ddd-c330-40a7-9e61-36c059261b4d.png)

## Error:
```
Error: ENOENT: no such file or directory, open '/Users/amit/Library/Application Support/Google/Chrome/Default/History'

```
Looks like it breaks because I have multiple Chrome profiles, so it fails to find the `Default` profile.

### Raycast version
Version: 1.39.1

**Comment by shaderein** [comment]
Having the same issue today. The temporary workaround for me is forcing Google Chrome to launch with a profile pointed to the directory `/Users/.../Library/Application Support/Google/Chrome/Default/` with the command `open -na 'Google Chrome' --args --profile-directory='Default' https://drive.google.com/`. (Found this solution [here](https://github.com/raycast/extensions/issues/1018#issuecomment-1067245279).)Then, log in to your google account and enable syncing. Now the History file can be located by google-chrome extension. Make sure you make a backup of your original profile folder. (You can visit `chrome://version/` in your browser and check 'Profile Path' to find the current path in used.)

**Comment by satoshi-harashima** [comment]
https://github.com/raycast/extensions/blob/efba3ec1978c17317a96bcdcaa914f9153839e04/extensions/google-chrome/src/browserHistory.tsx#L33

Wishing that, instead of this line of code, we can select which profiles to be used. Mine is "Profile 1", not "Default".
