### ISSUE TITLE
[SLACK] Show unread thread messages in unread messages

### ISSUE THREAD

**Issue by mxstbr** [raycast/extensions#2732]
# Extension – [Slack](https://github.com/raycast/extensions/tree/d3e045e1202b43a23bf38fddd89bf849135901b5/extensions/slack/*)

Author: @momme-rtf 

**Describe the feature and the current behavior/state.**

I _love_ Slack's "Unread" view to quickly skim the messages that have been sent without losing them because they're immediately marked as read.

However, Slack's "Unread" view doesn't show me unread _thread_ messages, and when I click on "Threads" it immediately marks them as read — the exact opposite of what I want to get an overview.

Could the Raycast extension's "Unread messages" view also show unread _thread_ messages?

**Who will benefit from this feature?**

Anybody who gets lots of messages in Slack threads.

**Any Other info.**

**Comment by mxstbr** [comment]
Not stale.

**Comment by taylorjdawson** [comment]
@mxstbr your link to the slack extension is stale FYI :)

**Comment by momme-rtf** [comment]
Hey @mxstbr, sry for the late reply! Glad to hear you like the expansion and thanks for the great idea! Unfortunately, as far as I know, this is currently not supported by the Slack API. I'll add it to my list and monitor the API docs for changes.

**Comment by mxstbr** [comment]
Not stale
