### ISSUE TITLE
[Heroicons] Set main action

### ISSUE THREAD

**Issue by teziovsky** [raycast/extensions#2736]
# Extension – [Heroicons](https://github.com/raycast/extensions/tree/73f3ae276d07bc311d8b4c5282b38e4b45f3e7b1/extensions/heroicons/)
Author: @haackt

**Describe the feature and the current behavior/state.**
I think that it could be great if the user could set which action will be primary in settings. I mean, now the immediate action is `Paste JSX`, but I will usually use the `Copy name` action. I would love to set `Copy name` as the primary action on the `Enter` key.

**Who will benefit from this feature?**
I think everyone 😎

**Any Other info.**

**Comment by haackt** [comment]
Hey @teziovsky 👋🏻
I think this is a great idea! I'll get at it, as soon as possible 🚀

**Comment by haackt** [comment]
Just created a pull request for the implementation of this feature :)!

Once again, thank you for proposing it :)!

**Comment by teziovsky** [comment]
Thank you for fast implementation! Now just wait for merge 🔥

Best regards!

**Comment by haackt** [comment]
It just got merged 🚀
You can close this issue now :)

**Comment by teziovsky** [comment]
Great 🎉🎉
