### ISSUE TITLE
[API Bug] Conflicting keyboard shortcuts

### ISSUE THREAD

**Issue by mrmartineau** [raycast/extensions#274]
Raycast version: v1.25.0

## Description
I am working on some improvements to the [search-npm](https://www.raycast.com/mrmartineau/search-npm) extension that I created. I'd like to assign this keyboard shortcut (<kbd>⌘ + c</kbd>) to one of the actions. Whilst I can assign the shortcut and it shows in the action UI (see below), using the keyboard shortcut does not actually work.
**Are there any known issues using system-wide keyboard shortcuts within an extension action?** 

![image](https://user-images.githubusercontent.com/64883/139596788-5eeb5d21-4acc-4207-a83c-ec9bdffd643c.png)

I am using this code within an `Actions` block:

```tsx
<CopyToClipboardAction
  title="Copy Package Name"
  content={pkg.name}
  shortcut={{ modifiers: ['cmd'], key: 'c' }}
/>
```

## Steps To Reproduce

1. Add a `CopyToClipboardAction` to an existing extension with the <kbd>⌘ + c</kbd> modifiers
2. See check if the content is copied to the clipboard

## The current behavior
**No content** should be copied to the clipboard when the keyboard shortcut is used.

## The expected behavior
The content should be copied to the clipboard when the keyboard shortcut is used.

**Comment by PitNikola** [comment]
Thanks for bringing this up. This shortcut is occupied by regular "copy" action in the search field, so it's expected behavior that it doesn't work. We believe it can be confusing if extensions start overtaking common shortcuts like ⌘+C/V/Z. We might introduce some warning in the console when developer tries to assign it to an action to make it more clear.

**Comment by mrmartineau** [comment]
Thanks @PitNikola, I thought as much. 

I also notice that my search npm extension has a keyboard shortcut that is the same as another I use in Raycast itself (`cmd+opt+c`) which opens the clipboard history. Do you think it would be possible for keyboard shortcuts (in extensions) to be disabled by users if they conflict like mine do?
