### ISSUE TITLE
[Notion] ... Would love to connect to multiple Notion workspaces

### ISSUE THREAD

**Issue by seanspeaks** [raycast/extensions#2741]
# Extension – [Notion](https://github.com/raycast/extensions/tree/8ea3c6f9563bf73663218d2ead8c32e683ef7b34/extensions/notion/)
Author:

**Describe the feature and the current behavior/state.**
Currently only connect to one Workspace/org. I've got a personal and a business one, would love to connect to both

**Who will benefit with this feature?**
Anyone who has multiple workspaces

**Any Other info.**

**Comment by indaviande** [comment]
I personnaly have 3 accounts, would love to connect all of them as well.

**Comment by ELLIOTTCABLE** [comment]
This has come up multiple other times — see #2998, #4363. Could we get it re-opened? It's clearly a desirable feature. (=
