### ISSUE TITLE
[Cleanshot X] Add new command Capture History

### ISSUE THREAD

**Issue by albychok** [raycast/extensions#2743]
# Extension – [Cleanshot X](https://github.com/raycast/extensions/tree/4e690dc9277a0b691b08aab147c97448167eb2ff/extensions/cleanshotx/)
Author: @Aayush9029

Cleanshot team did a great job and [updated](https://twitter.com/CleanShot/status/1564642147718107139) the application. Would be awesome to use all that features with raycast.

**Comment by Aayush9029** [comment]
@albychok sure thing!
