### ISSUE TITLE
Pop multiple steps

### ISSUE THREAD

**Issue by cornedor** [raycast/extensions#2759]
**Describe the feature and the current behavior/state.**

Currently, the pop function can pop 1 view from the stack. It would be useful if we can pop multiple steps. 

**Will this change the current API? How?**

The `pop` function from `useNavigation` would receive an extra parameter.

**Who will benefit from this feature?**

Extensions that have an overview that could trigger a nested flow, but that flow needs to op back to the extension root.

**Any Other info.**

Another option would be a popToRoot alternative that pops back to the root of the extension.

**Comment by thomaspaulmann** [comment]
Couldn't you solve this via React and just render a completely different view? Also, do you have an exact use case? We try to keep the navigation consistent across commands/extensions and so far we haven't had a need for multiple pops.

**Comment by cornedor** [comment]
In my use case I have an overview of items. To add more items to the overview you can select an item from a new page, and after filling a form in another page, I would like to pop back to the overview page. This is currently not possible. I've not tried it by rendering a completely different view.

**Comment by peduarte** [comment]
@cornedor Curious if this is still an issue for you, or if Thomas/Mathieu's suggestions have done the trick? Thanks!

**Comment by cornedor** [comment]
Thanks for the reminder, calling pop multiple times seems to work. Thanks
