### ISSUE TITLE
Following the "create your first extension" docs doesn't work

### ISSUE THREAD

**Issue by markmiro** [raycast/extensions#2760]
Raycast version: 1.38.2

## Steps To Reproduce

1. I follow the instructions here: https://developers.raycast.com/basics/create-your-first-extension
2. I run `npm install`
3. I run `npm run dev`
4. The launcher opens automatically: <img width="862" alt="Screen Shot 2022-09-01 at 4 42 41 PM" src="https://user-images.githubusercontent.com/1214630/188031985-78ebf6a8-1f02-4bde-83a3-350fc9230522.png">
5. But when I launch it I get this: <img width="862" alt="Screen Shot 2022-09-01 at 4 42 49 PM" src="https://user-images.githubusercontent.com/1214630/188032011-1b7e6e13-7541-46e2-b598-b78c187502ca.png">

I tried this twice and I get the same bug. However, the hello world app did work before I ran the dev command. So it seems like it stopped working after I ran the dev command.

I would update the Raycast version, but I'm having trouble with that.

**Comment by SenpaiHunters** [comment]
Here are a few ideas you might be able to try:
1. Did you select the "Detail" template?
2. Is it under 'Raycast_extetions'
![SCR-20220905-p9i](https://user-images.githubusercontent.com/103985728/188401170-18003201-3d80-45e3-9073-57aafdc68258.png)
4. npm install && npm run dev requires another app i downloaded it from 'https://nodejs.org/en/download/'
After that it started to work. The idea is that the command should look like this:
![image](https://user-images.githubusercontent.com/103985728/188401820-8871b6e8-96bf-4f38-93ad-fd0a719a756a.png)

Here's a video on what i did - https://youtu.be/uYrY43JoqIg

**Comment by markmiro** [comment]
I'm very familiar with nodejs development. Maybe I'm doing something dumb and don't realize it, but I can't think of what it might be. Maybe there's something unique about my environment.

[Video](https://youtu.be/5DSG1n3x7Y4) of exactly what I'm doing.

What version of Raycast are you using?
I'm on 1.38.2

I'm really baffled that a basic template doesn't work.

After trying and failing to update the app, I'm less surprised that the template doesn't work ([video here](https://youtu.be/BisfNFSd__Y)). I submitted a bug report for this as well. One basic issue on its own isn't a big deal. You're a new company moving fast. But I can't even update to see if the problem I'm having was already fixed.

Another hypothesis. Maybe it's because I'm on an m1 mac? Maybe it's because I have a separate admin account that I login to when I make system changes?

**Comment by SenpaiHunters** [comment]
Instead of opening in code on the dropdown menu. Press, 'start development' (Command B). I had problems trying to use it via Visual Studio Code. 

I'm also on an M1 Mac, but am on a private profile instead of an admin one. 

If that doesn't help I'll try think of other options.

**Comment by markmiro** [comment]
The problem is solved in v1.39.2

I had to uninstall the app and install it again from the website because updating from within the app wasn't working for me. I didn't have to re-add any extensions.
