### ISSUE TITLE
npm extension showing outdated versions of packages

### ISSUE THREAD

**Issue by TimonVS** [raycast/extensions#2766]
# Extension – [Search npm](https://github.com/raycast/extensions/tree/main/extensions/search-npm)

Author: @reloadedhead 

## Description

This extension sometimes shows an outdated version of a package:

![CleanShot 2022-09-02 at 11 31 15@2x](https://user-images.githubusercontent.com/876666/188110143-214581f1-0ba4-4530-a4ae-06be15234455.png)

![CleanShot 2022-09-02 at 11 31 31@2x](https://user-images.githubusercontent.com/876666/188110205-870f4f4d-2751-476a-9ed8-111169a5e396.png)

Compared to the npm website:

<img width="520" alt="CleanShot 2022-09-02 at 11 32 10@2x" src="https://user-images.githubusercontent.com/876666/188110379-a84e264f-0ecb-4f24-a254-03029114b05e.png">

<img width="401" alt="CleanShot 2022-09-02 at 11 31 55@2x" src="https://user-images.githubusercontent.com/876666/188110399-f62a5c49-98b0-42c2-9fb0-45a4928f81d3.png">

Would it make sense to switch to the official npm registry API? (https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md). I've tried it and it does actually show the latest version of a package (e.g., https://registry.npmjs.org/-/v1/search?text=@types/react). I can contribute this change, I just want to verify if there's a specific reason npms.io was used over npm's REST API.

## Steps To Reproduce

1. Search for "typescript"
2. Version shown is 4.6.2 which is 6 months old, the latest version is 4.8.2 (also has the `latest` tag)

## The current behavior

Shows older versions of packages.

## The expected behavior

Shows the latest versions of packages.

### Raycast version

Version: 1.39.2

**Comment by mathieudutour** [comment]
Yeah I agree that we should switch. I'm guessing the reason for it was to get the "score" but IMO it's more important to get up-to-date results than this arbitrary metric.

Especially since `@raycast/utils` doesn't even show up in the results!

**Comment by TimonVS** [comment]
Funny running into you here 😄. I've put up an MR (#2786), it was a relatively small change, all features are still intact.
