### ISSUE TITLE
YouTube Extension doesn't work at all.

### ISSUE THREAD

**Issue by jadenquinn** [raycast/extensions#2777]
Raycast version:
1.39.2
## Description
I downloaded both Raycast and the YouTube extension, and input the API key, and it didn't work. It gave me an error about "quota". I looked back at the Google dev page to see if there was anything to do with that there, but I couldn't find anything.
## Steps To Reproduce

1. Get Raycast.
2. Get YouTube extension.
3. Input API key.
4. Try to use YouTube extension.

## The current behavior
I get an error.
## The expected behavior
I.... don't get an error.

**Comment by jadenquinn** [comment]
<img width="1398" alt="Screen Shot 2022-09-02 at 10 58 40 PM" src="https://user-images.githubusercontent.com/13245331/188258011-7f29baa8-7e79-432d-8886-0da8b594b8d9.png">

**Comment by georgeat8** [comment]
It might be related to your account quota. You get 10,000 units, which are calculated like this per YouTube's documentation: 

> Google calculates your quota usage by assigning a cost to each request. Different types of operations have different quota costs. For example:
> A read operation that retrieves a list of resources -- channels, videos, playlists -- usually costs 1 unit.
> A write operation that creates, updates, or deletes a resource usually has costs 50 units.
> A search request costs 100 units.
> A video upload costs 1600 units.

More details [here](https://developers.google.com/youtube/v3/getting-started#quota).

You could maybe try to create a new project and see if the issue persists.

**Comment by jadenquinn** [comment]
Not for lack of trying. I haven't been asked anything else.
