### ISSUE TITLE
[YouTube] ...

### ISSUE THREAD

**Issue by cynobar** [raycast/extensions#2785]
# Extension – [YouTube](https://github.com/raycast/extensions/tree/6533c5cf7342a838a0bcd056a5f0eb521144828d/extensions/youtube/)
Author: @tonka3000

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.39.2

**Comment by tranquanghuy0801** [comment]
What is the error? could not see the image you attached
