### ISSUE TITLE
[Search npm] extension takes ~2 seconds to load

### ISSUE THREAD

**Issue by TimonVS** [raycast/extensions#2787]
# Extension – [Search npm](https://github.com/raycast/extensions/tree/main/extensions/search-npm)

Author: @reloadedhead 

## Description

The Search npm extension takes ~2 seconds to load, which to me is quite disruptive. The Ruby Gems extension doesn't suffer from this issue.

https://user-images.githubusercontent.com/876666/188305924-f4215167-c5c9-4519-bbd7-e16522fa6876.mp4

## Steps To Reproduce

1. Open the Search npm extension
2. If it opens fast, first open another extension (e.g., the Ruby Gems extension), and then reopen the Search npm extension and it should load slowly.

## The current behavior

The extension loads slowly.

## The expected behavior

The extension should load instantly, like the Ruby Gems extension.

### Raycast version

Version: v1.39.2

**Comment by TimonVS** [comment]
Actually, the Ruby Gems extension also takes ~2 seconds to load sometimes, but it's more easily reproducible with the npm extension (?).

**Comment by mathieudutour** [comment]
Can you check the latest version? I added some caching so it should feel faster

**Comment by TimonVS** [comment]
Ooh, the `useFetch` hook is nice, that definitely makes search a lot faster! My problem is more about the startup time of the extension though. As you can see in the video, it takes ~2 seconds for the input placeholder and empty state of the npm Search extension to show up, in the meantime it feels like I cannot do anything. E.g., if I type some text while the extension is loading, it doesn't show up until after the extension is done loading. I don't know if it is related to this extension, or with Raycast in general, I don't use many extensions besides this one, but I did notice that the problem occurs less often with the Ruby Gems extension.

**Comment by mathieudutour** [comment]
Ah right, the empty state only shows up once it's finished loading - and we do a fetch even if there are no query. 

Maybe we should just skip the initial fetch 🤔 

In any case, you can start to interact with the extension right away, it will still work

**Comment by TimonVS** [comment]
> Ah right, the empty state only shows up once it's finished loading - and we do a fetch even if there are no query.

> Maybe we should just skip the initial fetch 🤔

Good call! I believe this wasn't a problem before `useFetch` was introduced, I tested this before because I had the same theory, but in both versions the extension loads slowly for me.

> In any case, you can start to interact with the extension right away, it will still work

Attached below is a video where I start typing before the extension has finished loading. While I can start typing, it's jarring that I don't see the input until the extension is done loading. I have to wait upwards of two seconds to actually use the extension, which makes me want to reach for the browser instead. The workflow in the browser might be slower (visit npmjs.com, do a search), but it reacts instantly to my commands, the difference in perception makes a huge difference I think.

https://user-images.githubusercontent.com/876666/188439600-726761bb-989b-44e4-a49e-5c4d2d6e788e.mp4
