### ISSUE TITLE
[Google Workspace] ...

### ISSUE THREAD

**Issue by aaronabl** [raycast/extensions#2793]
# Extension – [Google Workspace](https://github.com/raycast/extensions/tree/1e0173363c27f8bd624aed66d92576965ae4ce2d/extensions/google-workspace/)
Author: @thomaslombart

**Describe the feature and the current behavior/state.**
Currently, the extension requests for login into 1 Google account to grant access to the google drive files.

What I would like to request: For the extension to allow for multiple Google accounts (Like CMD+E) so that I can search across my various work files in different google accounts.

**Who will benefit with this feature?**

People with multiple accounts.

**Any Other info.**
Pretty please? :3

**Comment by thomaslombart** [comment]
Hey @aaronabl, it's not possible as of now to have multiple accounts for any extensions. I don't know when the Raycast team will tackle this but I guess you can follow this issue in the meantime: https://github.com/raycast/extensions/issues/269

**Comment by aaronabl** [comment]
Thanks for the quick response! I will keep an eye on this.

*Aaron M.*
*CEO*
*AB Logistics*

*m: *+65 8812 9369
*w:* ablogistics.co

Sent via Superhuman ***@***.***>
