### ISSUE TITLE
[Things] "Show Today in Menu Bar" won't toggle off

### ISSUE THREAD

**Issue by sylrs** [raycast/extensions#2798]
# Extension – [Things](https://github.com/raycast/extensions/tree/5f42be97154e3920321c7001063fb0f5a1abd220/extensions/things/)
Author: @loris

## Description
Disabling "Show Today in Menu Bar" doesn't seem to be working. When enabled, the menu bar icon cannot be disabled. It goes away for a split second, and then reappears again.

## Steps To Reproduce

1. Toggle "Show Today in Menu Bar"
2. Try to disable it. 
3. It doesn't go away

## The current behavior
The menu bar extension will not go away

## The expected behavior
The menu bar extension is able to be toggled on and off

### Raycast version
Version: 1.39.2

**Comment by sylrs** [comment]
On a second thought, I think this is the intended behaviour of the extension currently. It's still possible to disable the menu bar extension by going to Raycast preferences and disabling "Show Today in Menu Bar". 

However, I think that making the command something that toggles "Show Today in Menu Bar" on and off, would be a great improvement to the user experience.

**Comment by loris** [comment]
Duplicates of https://github.com/raycast/extensions/issues/2811
