### ISSUE TITLE
[API Feature Request] Add possibility to set the searchbar text from a function

### ISSUE THREAD

**Issue by tonka3000** [raycast/extensions#281]
Right now there is no way to set the searchbar text via a function. Clearing it is already possible via `clearSearchBar` function.

Would be great to have `setSearchBar(text:string )`

## Concrete Usecase

I have the situation where I have a search query history. So in the command (YouTube extension) I display the user the latest 20 search queries in a list. The queries will be set again if the user trigger the default action of the active item. This will set the searchText state and start the query (so the input happen via code and not via a widget). So it works fine, but the searchbar stay empty which can confuse a user. It would be great to have the proposed `setSearchBar` function to set the text via code. That way it would set the searchbar text for the user.

**Describe the feature and the current behavior/state.**

-

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Raycast extension developers.

**Any Other info.**

**Comment by jclem** [comment]
A workaround I've recently used in the meantime is to update `navigationTitle` while the saved search is in view (and clearing it again when the input changes):

https://user-images.githubusercontent.com/412282/142298243-d7839fca-7597-412d-8b16-6dabf708f32a.mp4
