### ISSUE TITLE
[Things] hide/toggle menu bar item

### ISSUE THREAD

**Issue by pvinis** [raycast/extensions#2811]
# Extension – [Things](https://www.raycast.com/loris/things)

Author: @loris, @KELiON

## Description

I can enable the today status bar item, but i can not remove it. maybe we can add a hide command too, or change the show command to a toggle command.

## Steps To Reproduce

1. open raycast
2. type "today"
3. click the "show today in menu bar"
4. item shows up
5. never goes away again

## The current behavior

after menu item shows up, it never goes away again

## The expected behavior

should be able to remove it from raycast, so a toggle or hide command would be great

### Raycast version

Version: 1.39.2

**Comment by KELiON** [comment]
@pvinis you can disable menu-bar command as any other command from extension settings: 

![CleanShot 2022-09-07 at 13 01 11@2x](https://user-images.githubusercontent.com/594298/188837444-a5d688a4-bdb2-45aa-9fcf-9744fcec1fa1.png)

**Comment by loris** [comment]
Indeed as @KELiON said, you can disable it directly through the Extensions setting.
I think this should remain the only consistent way to disable menu bar entries (and developper should not provide an additional way to do it in each extension). What do you think @thomaspaulmann ?

**Comment by pvinis** [comment]
this removes the command, but it does not remove the statusbar item if it's already there, right?

**Comment by sxn** [comment]
> this removes the command, but it does not remove the statusbar item if it's already there, right?

It should remove the item as well. If for some reason it doesn’t, please let me know, as it would be a bug. 😬

**Comment by loris** [comment]
> > this removes the command, but it does not remove the statusbar item if it's already there, right?
> 
> It should remove the item as well. If for some reason it doesn’t, please let me know, as it would be a bug. 😬

Just tried it, it does remove the item as expected

**Comment by sxn** [comment]
as of 1.40.0, Menu Bar Extras can be removed without disabling the command altogether:

> Menu Bar Extras can now be deactivated without disabling the menu bar command! To deactivate a menu bar command, run the Deactivate Command action from the command's Action Panel - or drag the menu bar extra out of the menu bar while holding down ⌘.
