### ISSUE TITLE
[Jira] Add action to track time

### ISSUE THREAD

**Issue by halfb00t** [raycast/extensions#2818]
# Extension – [Jira](https://github.com/raycast/native-extensions/tree/0326feb025831e8c994758d8c54008bf62fa0807/extensions/jira/)
Author: @imthath-m

First of all, thank you for this very useful extension. It helps a lot with Jira tickets without opening Jira.

**Describe the feature and the current behavior/state.**
Add new action to the extension which will allow us to add work logs to a selected issue.

**Who will benefit with this feature?**
Agile teams who track time

**Comment by Jarzebowsky** [comment]
There is a separate extension for it but the problem is as follows - it shows only 100 newer records.
