### ISSUE TITLE
[Password Generator] Default Password Length

### ISSUE THREAD

**Issue by exrl-py** [raycast/extensions#2819]
# Extension – [Password Generator](https://github.com/raycast/extensions/tree/e7fe049840dc16caa61931b8b1b8819af57d6007/extensions/password-generator/)
Author: Joshua Michaels

When opening the Password Generator extension, it would be efficient to have the password length default either to the number that was last used or a user-defined value to avoid having to specify a password length on each run.

At current, the extension requires you to specify a length each time you want to generate a password, which can be redundant, especially considering that users often pick the same value.

**Comment by purplespider** [comment]
Eager for this too. Commenting to have the feature request re-opened.
