### ISSUE TITLE
[Bitwarden Vault] Login failure?

### ISSUE THREAD

**Issue by ileonemil** [raycast/extensions#2821]
# Extension – [Bitwarden Vault](https://github.com/raycast/extensions/tree/ff516d809e0817bcf57138675627249a22d25889/extensions/bitwarden/)
Author: @pomdtr

## Description
I installed BW CLI, logged with api and unlocked the vault. I entered the directory of the CLI manually in the extension preferences but I'm not able to search anything with raycast.

## Error:
```
Error: Command failed with EACCES: /Users/leo/Library/Application Support/Bitwarden CLI status
spawn /Users/leo/Library/Application Support/Bitwarden CLI EACCES

__node_internal_captureLargerStackTrace:errors:464:5
__node_internal_errnoException:errors:594:12
Process.ChildProcess._handle.onexit:child_process:282:19
onErrorNT:child_process:477:16

```

## Steps To Reproduce

1. Open raycast
2. Search Vault 
3. "Something went wrong"

### Raycast version
Version: 1.39.2

**Comment by kirso** [comment]
Just struggled with this, the default path usually equals the wrong one when you install it on M1. Try adding /bin/bw in extension settings after you inserted your general path where the bitwarden-cli lives.

**Comment by pomdtr** [comment]
Thanks for the help @kirso. I'll had `/bin/bw` and `/usr/bin/bw` to the list of default cli paths.

**Comment by pomdtr** [comment]
Sorry for lack of response on this, I did not have a lot of free time last month.

**Comment by kirso** [comment]
@pomdtr no worries at all, thank for bringing this to life in a first place.

@ileonemil you should keep the path, but you need to direct the extension to where the `bw` is currently located. So its not enough to just put /usr/.../.../.../bin.

Here is an example of mine: /usr/local/opt/bitwarden-CLI/bin/bw (this worked for me)

Try:
`brew --prefix bitwarden-cli `
Then:
add /bin/bw to the path output

**Comment by pomdtr** [comment]
Another option is to just run `which bw` in your terminal and copy the output

**Comment by ileonemil** [comment]
Achille it worked!

Thank you all guys
Il 12 ott 2022, 09:27 +0200, Achille Lacoin ***@***.***>, ha scritto:
