### ISSUE TITLE
[Brew] Respect homebrew configuration

### ISSUE THREAD

**Issue by grzegor** [raycast/extensions#2822]
# Extension – [Brew](https://github.com/raycast/extensions/tree/dd6d1181a4d488063098d5561759026bafd36f6d/extensions/brew/)

Since homebrew doesn't have a user config file per se, it relies on environment variables and plugin should respect them. For example I have a custom AppDir in my HOMEBREW_CASK_OPTS that Raycast ignores. 

Ideally, brew should be run within user default shell which you can find querying dscl: `dscl . -read /Users/$(whoami) UserShell` (add -plist for XML output). This way user will have homebrew with its respecful configuration, as homebrew developers imagined. This will work in almost all use cases so it should be the default bahavior, maybe with opt-out in Raycast config for some edge cases.

**Comment by Loskir** [comment]
As far as I know, there is no good way to read user-defined env vars (especially if they are defined somewhere like `.zshrc`). Would be happy to be wrong, let me know if there is :D

**Comment by grzegor** [comment]
Due to how shells are historically configured there are many places they look for config files. In theory you could do some guesswork like iterating through all available initial config files that are known for all the shells, checking them for homebrew variables, then checking files they are sourcing, then checking what they're sourcing etc. but thats very, _very_ ugly, verging on pointless.

Whats a nice way to do it is to get all that automagically by just running brew commands wrapped with the user's default shell that knows best where it stores its variables and sources them itself.

I just made a quick test, things starting with % are commands, the rest is output or a comment:
```zsh
# CHECKING FOR CURRENT SESSION VARIABLE
% brew config | grep HOMEBREW_CASK_OPTS
HOMEBREW_CASK_OPTS: ["--appdir=/Users/grzegor/Applications"]

# CHECKING FOR NEW SESSION VARIABLE, SHOULD BE SAME AS ABOVE
% /bin/zsh -c 'brew config | grep HOMEBREW_CASK_OPTS'
HOMEBREW_CASK_OPTS: ["--appdir=/Users/grzegor/Applications"]

# CHANGING THE VARIABLE FOR NEW SESSIONS
% echo "export HOMEBREW_CASK_OPTS=/Applications/Homebrew" >> ~/.zshenv

# CHECKING THE CURRENT SESSION, SHOULD STILL HAVE OLD VARIABLE
% brew config | grep HOMEBREW_CASK_OPTS
HOMEBREW_CASK_OPTS: ["--appdir=/Users/grzegor/Applications"]

# CHECKING NEW SESSION, SHOULD READ THE UPDATED ONE
% /bin/zsh -c 'brew config | grep HOMEBREW_CASK_OPTS'
HOMEBREW_CASK_OPTS: ["/Applications/Homebrew"]
```

So the non-interactive `/bin/zsh -c` clearly initialises its variables properly from its config files on each spawn. I have no idea if it's the expected behaviour of all POSIX shells though (not even sure if fish is POSIX compliant), but worst case scenario it will work with OS default one that is very rarely changed (and if it is, then we can assume that user knows what they're doing anyway).

I also benchmarked it:
```
% time /bin/zsh -c "brew help" >/dev/null
/bin/zsh -c "brew help" > /dev/null  0.37s user 0.20s system 93% cpu 0.608 total

% time brew help >/dev/null
brew help > /dev/null  0.36s user 0.20s system 92% cpu 0.607 total
```

Wrapping brew command with shell adds 0.01 second to the execution time. I think the difference is insignificant.

I have no idea how node runs external executables, but if it doesn't care whether it's a path to a literal binary executable file or just a command string to execute then a trivial change to brewExecutable() function to return not something like `/opt/homebrew/bin/brew` but `/bin/zsh -c /opt/homebrew/bin/brew` instead (where /bin/zsh you get with the `dscl` query I posted in my previous comment, because some people may be running bash or fish or whatever) would result in `brew` command run in the expected environment with all variables (again, shell itself knows best where to look for them).
