### ISSUE TITLE
Add Actions for Poster/Backdrop to The Movie Database Extension

### ISSUE THREAD

**Issue by joeynotjoe** [raycast/extensions#2825]
# Extension – [The Movie Database](https://www.raycast.com/Aayush9029/tmdb)

Author: @Aayush9029

**Describe the feature and the current behavior/state.**
Right now, the only actions seems to be opening the actual TMDB page. It would be amazing if we had some additional actions added to the extension. Some that I think would be useful would be, "Copy Poster URL", "Copy Backdrop URL", "Copy Title Name". Maybe someone else has other good ideas for some that could be useful?

**Who will benefit from this feature?**
Myself, and anyone else who wants to look these things up quickly on TMDB using Raycast 😎 

**Any Other info.**
Is it possible to allow the user to configure what size backdrop/poster they could fetch? (i.e. '500', or 'original').

**Comment by Aayush9029** [comment]
Interesting idea! I'll let community *or you* to expand on this niche feature!

**Comment by joeynotjoe** [comment]
I wish I knew how to add actions, but unfortunately I can only figure out how to replace the existing OpenURL action's URL, haha. 

I'll try to dig into documentation somewhere. Thanks!

**Comment by Aayush9029** [comment]
OpenURL is the way to go! URL are here

https://github.com/raycast/extensions/blob/866137283104c186e27d9780a25f7b512838ddd8/extensions/tmdb/src/searchMovie.tsx#L47

https://github.com/raycast/extensions/blob/866137283104c186e27d9780a25f7b512838ddd8/extensions/tmdb/src/searchMovie.tsx#L51
