### ISSUE TITLE
[Spotify-Player] Should be able to toggle menu bar player

### ISSUE THREAD

**Issue by mikestopcontinues** [raycast/extensions#2826]
# Extension – [Spotify-Player](https://github.com/raycast/extensions/tree/main/extensions/spotify-player)
Author: @mattisssa

Similar to #2811, I'd like to be able to toggle Spotify menu bar on and off. Sometimes want to pay more attention to the names of songs, but sometimes I want to work. ;) Right now, you can't turn it off, though it seems more like a bug than the intended behavior...

## Steps To Reproduce

1. Run "Menu Bar Player" — turns on the menu bar player.
2. Run "Menu Bar Player" again — turns it off momentarily, then it's back.

## The current behavior

It won't turn off.

## The expected behavior

It should turn off.

### Raycast version

Version: 1.39.0

**Comment by sxn** [comment]
hi @mikestopcontinues - thanks for the report!
This isn’t really a bug with the extension, more a limitation of how menu bar commands in Raycast currently work -upcoming releases will address that!😺
In the mean time, the current way to remove a menu bar extra from the menu bar is to disable the command altogether in Preferences.

**Comment by mikestopcontinues** [comment]
Thanks! BTW I really dig the addition!

**Comment by sxn** [comment]
addressed in 1.40.0[1.40.0](https://developers.raycast.com/changelog#1.40.0-2022-09-28):
> Menu Bar Extras can now be deactivated without disabling the menu bar command! To deactivate a menu bar command, run the Deactivate Command action from the command's Action Panel - or drag the menu bar extra out of the menu bar while holding down ⌘.
