### ISSUE TITLE
[Fantastical] ... Not creating new event 

### ISSUE THREAD

**Issue by gdub99** [raycast/extensions#2827]
# Extension – [Fantastical](https://github.com/raycast/extensions/tree/337b063d5f4de90a1d21b3be253c74da8287aae6/extensions/fantastical/)
Author: @devahschaefers

## Description

Used the "Event" command in Raycast and put in an event, including event name, date, times, calendar, and received an error.  Fresh install of both Raycast and the Fantastical extension.

## Error:

Error: Command failed with exit code 1: osascript -e 
        tell application "Fantastical" 
            
 parse sentence "Test Event Friday 330p 5p /kids" 

        end tell
55:103: execution error: Not authorized to send Apple events to Fantastical. (-1743)

        tell application "Fantastical" 
            
 parse sentence "Test Event Friday 330p 5p /kids" 
        end tell
wr:fan-add-event.js:5:57

---
2: `:`
3: `.charCodeAt(),n=typeof e=="string"?"\r":"\r".charCodeAt();return e[e.length-1]===t&&(e=e.slice(0,e.length-1)),e[e.length-1]===n&&(e=e.slice(0,e.length-1)),e}});var wt=c((js,k)=>{"use strict";var $=require("path"),xt=ne(),bt=e=>{e=f({cwd:process.cwd(),path:process.env[xt()],execPath:process.execPath},e);let t,n=$.resolve(e.cwd),r=[];for(;t!==n;)r.push($.join(n,"node_modules/.bin")),t=n,n=$.resolve(n,"..");let s=$.resolve(e.cwd,e.execPath,"..");return r.push(s),r.concat(e.path).join($.delimiter)};k.exports=bt;k.exports.default=bt;k.exports.env=e=>{e=f({env:process.env},e);let t=f({},e.env),n=xt({env:t});return e.path=t[n],t[n]=k.exports(e),t}});var Et=c((Fs,le)=>{"use strict";var vt=(e,t)=>{for(let n of Reflect.ownKeys(t))Object.defineProperty(e,n,Object.getOwnPropertyDescriptor(t,n));return e};le.exports=vt;le.exports.default=vt});var Tt=c((Us,X)=>{"use strict";var tr=Et(),D=new WeakMap,It=(e,t={})=>{if(typeof e!="function")throw new TypeError("Expected a function");let n,r=0,s=e.displayName||e.name||"<anonymous>",o=function(...i){if(D.set(o,++r),r===1)n=e.apply(this,i),e=null;else if(t.throw===!0)throw new Error(`Function \`${s}\` can only be called once`);return n};return tr(o,e),D.set(o,r),o};X.exports=It;X.exports.default=It;X.exports.callCount=e=>{if(!D.has(e))throw new Error(`The given function \`${e.name}\` is not wrapped by the \`onetime\` package`);return D.get(e)}});var Pt=c(H=>{"use strict";Object.defineProperty(H,"__esModule",{value:!0});H.SIGNALS=void 0;var nr=[{name:"SIGHUP",number:1,action:"terminate",description:"Terminal closed",standard:"posix"},{name:"SIGINT",number:2,action:"terminate",description:"User interruption with CTRL-C",standard:"ansi"},{name:"SIGQUIT",number:3,action:"core",description:"User interruption with CTRL-\\",standard:"posix"},{name:"SIGILL",number:4,action:"core",description:"Invalid machine instruction",standard:"ansi"},{name:"SIGTRAP",number:5,action:"core",description:"Debugger breakpoint",standard:"posix"},{name:"SIGABRT",number:6,action:"core",description:"Aborted",standard:"ansi"},{name:"SIGIOT",number:6,action:"core",description:"Aborted",standard:"bsd"},{name:"SIGBUS",number:7,action:"core",description:"Bus error due to misaligned, non-existing address or paging error",standard:"bsd"},{name:"SIGEMT",number:7,action:"terminate",description:"Command should be emulated but is not implemented",standard:"other"},{name:"SIGFPE",number:8,action:"core",description:"Floating point arithmetic error",standard:"ansi"},{name:"SIGKILL",number:9,action:"terminate",description:"Forced termination",standard:"posix",forced:!0},{name:"SIGUSR1",number:10,action:"terminate",description:"Application-specific signal",standard:"posix"},{name:"SIGSEGV",number:11,action:"core",description:"Segmentation fault",standard:"ansi"},{name:"SIGUSR2",number:12,action:"terminate",description:"Application-specific signal",standard:"posix"},{name:"SIGPIPE",number:13,action:"terminate",description:"Broken pipe or socket",standard:"posix"},{name:"SIGALRM",number:14,action:"terminate",description:"Timeout or timer",standard:"posix"},{name:"SIGTERM",number:15,action:"terminate",description:"Termination",standard:"ansi"},{name:"SIGSTKFLT",number:16,action:"terminate",description:"Stack is empty or overflowed",standard:"other"},{name:"SIGCHLD",number:17,action:"ignore",description:"Child process terminated, paused or unpaused",standard:"posix"},{name:"SIGCLD",number:17,action:"ignore",description:"Child process terminated, paused or unpaused",standard:"other"},{name:"SIGCONT",number:18,action:"unpause",description:"Unpaused",standard:"posix",forced:!0},{name:"SIGSTOP",number:19,action:"pause",description:"Paused",standard:"posix",forced:!0},{name:"SIGTSTP",number:20,action:"pause",description:'Paused using CTRL-Z or "suspend"',standard:"posix"},{name:"SIGTTIN",number:21,action:"pause",description:"Background process cannot read terminal input",standard:"posix"},{name:"SIGBREAK",number:21,action:"terminate",description:"User interruption with CTRL-BREAK",standard:"other"},{name:"SIGTTOU",number:22,action:"pause",description:"Background process cannot write to terminal output",standard:"posix"},{name:"SIGURG",number:23,action:"ignore",description:"Socket received out-of-band data",standard:"bsd"},{name:"SIGXCPU",number:24,action:"core",description:"Process timed out",standard:"bsd"},{name:"SIGXFSZ",number:25,action:"core",description:"File too big",standard:"bsd"},{name:"SIGVTALRM",number:26,action:"terminate",description:"Timeout or timer",standard:"bsd"},{name:"SIGPROF",number:27,action:"terminate",description:"Timeout or timer",standard:"bsd"},{name:"SIGWINCH",number:28,action:"ignore",description:"Terminal window size changed",standard:"bsd"},{name:"SIGIO",number:29,action:"terminate",description:"I/O is available",standard:"other"},{name:"SIGPOLL",number:29,action:"terminate",description:"Watched event",standard:"other"},{name:"SIGINFO",number:29,action:"ignore",description:"Request for process information",standard:"other"},{name:"SIGPWR",number:30,action:"terminate",description:"Device running out of power",standard:"systemv"},{name:"SIGSYS",number:31,action:"core",description:"Invalid system call",standard:"other"},{name:"SIGUNUSED",number:31,action:"terminate",description:"Invalid system call",standard:"other"}];H.SIGNALS=nr});var de=c(G=>{"use strict";Object.defineProperty(G,"__esModule",{value:!0});G.SIGRTMAX=G.getRealtimeSignals=void 0;var rr=function(){let e=Ct-Gt+1;return Array.from({length:e},sr)};G.getRealtimeSignals=rr;var sr=function(e,t){return{name:`SIGRT${t+1}`,number:Gt+t,action:"terminate",description:"Application-specific signal (realtime)",standard:"posix"}},Gt=34,Ct=64;G.SIGRTMAX=Ct});var At=c(K=>{"use strict";Object.defineProperty(K,"__esModule",{value:!0});K.getSignals=void 0;var or=require("os"),ir=Pt(),ar=de(),cr=function(){let e=(0,ar.getRealtimeSignals)();return[...ir.SIGNALS,...e].map(ur)};K.getSignals=cr;var ur=function({name:e,number:t,description:n,action:r,forced:s=!1,standard:o}){let{signals:{[e]:i}}=or.constants,a=i!==void 0;return{name:e,number:a?i:t,description:n,supported:a,action:r,forced:s,standard:o}}});var Rt=c(C=>{"use strict";Object.defineProperty(C,"__esModule",{value:!0});C.signalsByNumber=C.signalsByName=void 0;var lr=require("os"),Ot=At(),dr=de(),fr=function(){return(0,Ot.getSignals)().reduce(pr,{})},pr=function(e,{name:t,number:n,description:r,supported:s,action:o,forced:i,standard:a}){return w(f({},e),{[t]:{name:t,number:n,description:r,supported:s,action:o,forced:i,standard:a}})},mr=fr();C.signalsByName=mr;var hr=function(){let e=(0,Ot.getSignals)(),t=dr.SIGRTMAX+1,n=Array.from({length:t},(r,s)=>Sr(s,e));return Object.assign({},...n)},Sr=function(e,t){let n=yr(e,t);if(n===void 0)return{};let{name:r,description:s,supported:o,action:i,forced:a,standard:u}=n;return{[e]:{name:r,number:e,description:s,supported:o,action:i,forced:a,standard:u}}},yr=function(e,t){let n=t.find(({name:r})=>lr.constants.signals[r]===e);return n!==void 0?n:t.find(r=>r.number===e)},gr=hr();C.signalsByNumber=gr});var Nt=c((Ws,qt)=>{"use strict";var{signalsByName:xr}=Rt(),br=({timedOut:e,timeout:t,errorCode:n,signal:r,signalDescription:s,exitCode:o,isCanceled:i})=>e?`timed out after ${t} milliseconds`:i?"was canceled":n!==void 0?`failed with ${n}`:r!==void 0?`was killed with ${r} (${s})`:o!==void 0?`failed with exit code ${o}`:"failed",wr=({stdout:e,stderr:t,all:n,error:r,signal:s,exitCode:o,command:i,escapedCommand:a,timedOut:u,isCanceled:l,killed:p,parsed:{options:{timeout:S}}})=>{o=o===null?void 0:o,s=s===null?void 0:s;let h=s===void 0?void 0:xr[s].description,y=r&&r.code,x=`Command ${br({timedOut:u,timeout:S,errorCode:y,signal:s,signalDescription:h,exitCode:o,isCanceled:l})}: ${i}`,I=Object.prototype.toString.call(r)==="[object Error]",j=I?`${x}
4: ${r.message}`:x,F=[j,t,e].filter(Boolean).join(`
5: `);return I?(r.originalMessage=r.message,r.message=F):r=new Error(F),r.shortMessage=j,r.command=i,r.escapedCommand=a,r.exitCode=o,r.signal=s,r.signalDescription=h,r.stdout=e,r.stderr=t,n!==void 0&&(r.all=n),"bufferedData"in r&&delete r.bufferedData,r.failed=!0,r.timedOut=Boolean(u),r.isCanceled=l,r.killed=p&&!u,r};qt.exports=wr});var $t=c((zs,fe)=>{"use strict";var W=["stdin","stdout","stderr"],vr=e=>W.some(t=>e[t]!==void 0),_t=e=>{if(!e)return;let{stdio:t}=e;if(t===void 0)return W.map(r=>e[r]);if(vr(e))throw new Error(`It's not possible to provide \`stdio\` in combination with one of ${W.map(r=>`\`${r}\``).join(", ")}`);if(typeof t=="string")return t;if(!Array.isArray(t))throw new TypeError(`Expected \`stdio\` to be of type \`string\` or \`Array\`, got \`${typeof t}\``);let n=Math.max(t.length,W.length);return Array.from({length:n},(r,s)=>t[s])};fe.exports=_t;fe.exports.node=e=>{let t=_t(e);return t==="ipc"?"ipc":t===void 0||typeof t=="string"?[t,t,t,"ipc"]:t.includes("ipc")?t:[...t,"ipc"]}});var kt=c((Vs,z)=>{z.exports=["SIGABRT","SIGALRM","SIGHUP","SIGINT","SIGTERM"];process.platform!=="win32"&&z.exports.push("SIGVTALRM","SIGXCPU","SIGXFSZ","SIGUSR2","SIGTRAP","SIGSYS","SIGQUIT","SIGIOT");process.platform==="linux"&&z.exports.push("SIGIO","SIGPOLL","SIGPWR","SIGSTKFLT","SIGUNUSED")});var Ft=c((Ys,R)=>{var d=global.process,v=function(e){return e&&typeof e=="object"&&typeof e.removeListener=="function"&&typeof e.emit=="function"&&typeof e.reallyExit=="function"&&typeof e.listeners=="function"&&typeof e.kill=="function"&&typeof e.pid=="number"&&typeof e.on=="function"};v(d)?(Bt=require("assert"),A=kt(),Lt=/^win/i.test(d.platform),B=require("events"),typeof B!="function"&&(B=B.EventEmitter),d.__signal_exit_emitter__?m=d.__signal_exit_emitter__:(m=d.__signal_exit_emitter__=new B,m.count=0,m.emitted={}),m.infinite||(m.setMaxListeners(1/0),m.infinite=!0),R.exports=function(e,t){if(!v(global.process))return function(){};Bt.equal(typeof e,"function","a callback must be provided for exit handler"),O===!1&&pe();var n="exit";t&&t.alwaysLast&&(n="afterexit");var r=function(){m.removeListener(n,e),m.listeners("exit").length===0&&m.listeners("afterexit").length===0&&V()};return m.on(n,e),r},V=function(){!O||!v(global.process)||(O=!1,A.forEach(function(t){try{d.removeListener(t,Y[t])}catch{}}),d.emit=Q,d.reallyExit=me,m.count-=1)},R.exports.unload=V,E=function(t,n,r){m.emitted[t]||(m.emitted[t]=!0,m.emit(t,n,r))},Y={},A.forEach(function(e){Y[e]=function(){if(!!v(global.process)){var n=d.listeners(e);n.length===m.count&&(V(),E("exit",null,e),E("afterexit",null,e),Lt&&e==="SIGHUP"&&(e="SIGINT"),d.kill(d.pid,e))}}}),R.exports.signals=function(){return A},O=!1,pe=function(){O||!v(global.process)||(O=!0,m.count+=1,A=A.filter(function(t){try{return d.on(t,Y[t]),!0}catch{return!1}}),d.emit=jt,d.reallyExit=Mt)},R.exports.load=pe,me=d.reallyExit,Mt=function(t){!v(global.process)||(d.exitCode=t||0,E("exit",d.exitCode,null),E("afterexit",d.exitCode,null),me.call(d,d.exitCode))},Q=d.emit,jt=function(t,n){if(t==="exit"&&v(global.process)){n!==void 0&&(d.exitCode=n);var r=Q.apply(this,arguments);return E("exit",d.exitCode,null),E("afterexit",d.exitCode,null),r}else return Q.apply(this,arguments)}):R.exports=function(){return function(){}};var Bt,A,Lt,B,m,V,E,Y,O,pe,me,Mt,Q,jt});var Dt=c((Qs,Ut)=>{"use strict";var Er=require("os"),Ir=Ft(),Tr=1e3*5,Pr=(e,t="SIGTERM",n={})=>{let r=e(t);return Gr(e,t,n,r),r},Gr=(e,t,n,r)=>{if(!Cr(t,n,r))return;let s=Or(n),o=setTimeout(()=>{e("SIGKILL")},s);o.unref&&o.unref()},Cr=(e,{forceKillAfterTimeout:t},n)=>Ar(e)&&t!==!1&&n,Ar=e=>e===Er.constants.signals.SIGTERM||typeof e=="string"&&e.toUpperCase()==="SIGTERM",Or=({forceKillAfterTimeout:e=!0})=>{if(e===!0)return Tr;if(!Number.isFinite(e)||e<0)throw new TypeError(`Expected the \`forceKillAfterTimeout\` option to be a non-negative integer, got \`${e}\` (${typeof e})`);return e},Rr=(e,t)=>{e.kill()&&(t.isCanceled=!0)},qr=(e,t,n)=>{e.kill(t),n(Object.assign(new Error("Timed out"),{timedOut:!0,signal:t}))},Nr=(e,{timeout:t,killSignal:n="SIGTERM"},r)=>{if(t===0||t===void 0)return r;let s,o=new Promise((a,u)=>{s=setTimeout(()=>{qr(e,n,u)},t)}),i=r.finally(()=>{clearTimeout(s)});return Promise.race([o,i])},_r=({timeout:e})=>{if(e!==void 0&&(!Number.isFinite(e)||e<0))throw new TypeError(`Expected the \`timeout\` option to be a non-negative integer, got \`${e}\` (${typeof e})`)},$r=async(e,{cleanup:t,detached:n},r)=>{if(!t||n)return r;let s=Ir(()=>{e.kill()});return r.finally(()=>{s()})};Ut.exports={spawnedKill:Pr,spawnedCancel:Rr,setupTimeout:Nr,validateTimeout:_r,setExitHandler:$r}});var Ht=c((Zs,Xt)=>{"use strict";var b=e=>e!==null&&typeof e=="object"&&typeof e.pipe=="function";b.writable=e=>b(e)&&e.writable!==!1&&typeof e._write=="function"&&typeof e._writableState=="object";b.readable=e=>b(e)&&e.readable!==!1&&typeof e._read=="function"&&typeof e._readableState=="object";b.duplex=e=>b.writable(e)&&b.readable(e);b.transform=e=>b.duplex(e)&&typeof e._transform=="function";Xt.exports=b});var Wt=c((Js,Kt)=>{"use strict";var{PassThrough:kr}=require("stream");Kt.exports=e=>{e=f({},e);let{array:t}=e,{encoding:n}=e,r=n==="buffer",s=!1;t?s=!(n||r):n=n||"utf8",r&&(n=null);let o=new kr({objectMode:s});n&&o.setEncoding(n);let i=0,a=[];return o.on("data",u=>{a.push(u),s?i=a.length:i+=u.length}),o.getBufferedValue=()=>t?a:r?Buffer.concat(a,i):a.join(""),o.getBufferedLength=()=>i,o}});var zt=c((eo,L)=>{"use strict";var{constants:Br}=require("buffer"),Lr=require("stream"),{promisify:Mr}=require("util"),jr=Wt(),Fr=Mr(Lr.pipeline),he=class extends Error{constructor(){super("maxBuffer exceeded");this.name="MaxBufferError"}};async function Se(e,t){if(!e)throw new Error("Expected a stream");t=f({maxBuffer:1/0},t);let{maxBuffer:n}=t,r=jr(t);return await new Promise((s,o)=>{let i=a=>{a&&r.getBufferedLength()<=Br.MAX_LENGTH&&(a.bufferedData=r.getBufferedValue()),o(a)};(async()=>{try{await Fr(e,r),s()}catch(a){i(a)}})(),r.on("data",()=>{r.getBufferedLength()>n&&i(new he)})}),r.getBufferedValue()}L.exports=Se;L.exports.buffer=(e,t)=>Se(e,w(f({},t),{encoding:"buffer"}));L.exports.array=(e,t)=>Se(e,w(f({},t),{array:!0}));L.exports.MaxBufferError=he});var Yt=c((to,Vt)=>{"use strict";var{PassThrough:Ur}=require("stream");Vt.exports=function(){var e=[],t=new Ur({objectMode:!0});return t.setMaxListeners(0),t.add=n,t.isEmpty=r,t.on("unpipe",s),Array.prototype.slice.call(arguments).forEach(n),t;function n(o){return Array.isArray(o)?(o.forEach(n),this):(e.push(o),o.once("end",s.bind(null,o)),o.once("error",t.emit.bind(t,"error")),o.pipe(t,{end:!1}),this)}function r(){return e.length==0}function s(o){e=e.filter(function(i){return i!==o}),!e.length&&t.readable&&t.end()}}});var en=c((no,Jt)=>{"use strict";var Zt=Ht(),Qt=zt(),Dr=Yt(),Xr=(e,t)=>{t===void 0||e.stdin===void 0||(Zt(t)?t.pipe(e.stdin):e.stdin.end(t))},Hr=(e,{all:t})=>{if(!t||!e.stdout&&!e.stderr)return;let n=Dr();return e.stdout&&n.add(e.stdout),e.stderr&&n.add(e.stderr),n},ye=async(e,t)=>{if(!!e){e.destroy();try{return await t}catch(n){return n.bufferedData}}},ge=(e,{encoding:t,buffer:n,maxBuffer:r})=>{if(!(!e||!n))return t?Qt(e,{encoding:t,maxBuffer:r}):Qt.buffer(e,{maxBuffer:r})},Kr=async({stdout:e,stderr:t,all:n},{encoding:r,buffer:s,maxBuffer:o},i)=>{let a=ge(e,{encoding:r,buffer:s,maxBuffer:o}),u=ge(t,{encoding:r,buffer:s,maxBuffer:o}),l=ge(n,{encoding:r,buffer:s,maxBuffer:o*2});try{return await Promise.all([i,a,u,l])}catch(p){return Promise.all([{error:p,signal:p.signal,timedOut:p.timedOut},ye(e,a),ye(t,u),ye(n,l)])}},Wr=({input:e})=>{if(Zt(e))throw new TypeError("The `input` option cannot be a stream in sync mode")};Jt.exports={handleInput:Xr,makeAllStream:Hr,getSpawnedResult:Kr,validateInputSync:Wr}});var nn=c((ro,tn)=>{"use strict";var zr=(async()=>{})().constructor.prototype,Vr=["then","catch","finally"].map(e=>[e,Reflect.getOwnPropertyDescriptor(zr,e)]),Yr=(e,t)=>{for(let[n,r]of Vr){let s=typeof t=="function"?(...o)=>Reflect.apply(r.value,t(),o):r.value.bind(t);Reflect.defineProperty(e,n,w(f({},r),{value:s}))}return e},Qr=e=>new Promise((t,n)=>{e.on("exit",(r,s)=>{t({exitCode:r,signal:s})}),e.on("error",r=>{n(r)}),e.stdin&&e.stdin.on("error",r=>{n(r)})});tn.exports={mergePromise:Yr,getSpawnedPromise:Qr}});var on=c((so,sn)=>{"use strict";var rn=(e,t=[])=>Array.isArray(t)?[e,...t]:[e],Zr=/^[\w.-]+$/,Jr=/"/g,es=e=>typeof e!="string"||Zr.test(e)?e:`"${e.replace(Jr,'\\"')}"`,ts=(e,t)=>rn(e,t).join(" "),ns=(e,t)=>rn(e,t).map(n=>es(n)).join(" "),rs=/ +/g,ss=e=>{let t=[];for(let n of e.trim().split(rs)){let r=t[t.length-1];r&&r.endsWith("\\")?t[t.length-1]=`${r.slice(0,-1)} ${n}`:t.push(n)}return t};sn.exports={joinCommand:ts,getEscapedCommand:ns,parseCommand:ss}});var pn=c((oo,q)=>{"use strict";var os=require("path"),xe=require("child_process"),is=St(),as=gt(),cs=wt(),us=Tt(),Z=Nt(),cn=$t(),{spawnedKill:ls,spawnedCancel:ds,setupTimeout:fs,validateTimeout:ps,setExitHandler:ms}=Dt(),{handleInput:hs,getSpawnedResult:Ss,makeAllStream:ys,validateInputSync:gs}=en(),{mergePromise:an,getSpawnedPromise:xs}=nn(),{joinCommand:un,parseCommand:ln,getEscapedCommand:dn}=on(),bs=1e3*1e3*100,ws=({env:e,extendEnv:t,preferLocal:n,localDir:r,execPath:s})=>{let o=t?f(f({},process.env),e):e;return n?cs.env({env:o,cwd:r,execPath:s}):o},fn=(e,t,n={})=>{let r=is._parse(e,t,n);return e=r.command,t=r.args,n=r.options,n=f({maxBuffer:bs,buffer:!0,stripFinalNewline:!0,extendEnv:!0,preferLocal:!1,localDir:n.cwd||process.cwd(),execPath:process.execPath,encoding:"utf8",reject:!0,cleanup:!0,all:!1,windowsHide:!0},n),n.env=ws(n),n.stdio=cn(n),process.platform==="win32"&&os.basename(e,".exe")==="cmd"&&t.unshift("/q"),{file:e,args:t,options:n,parsed:r}},M=(e,t,n)=>typeof t!="string"&&!Buffer.isBuffer(t)?n===void 0?void 0:"":e.stripFinalNewline?as(t):t,J=(e,t,n)=>{let r=fn(e,t,n),s=un(e,t),o=dn(e,t);ps(r.options);let i;try{i=xe.spawn(r.file,r.args,r.options)}catch(y){let g=new xe.ChildProcess,x=Promise.reject(Z({error:y,stdout:"",stderr:"",all:"",command:s,escapedCommand:o,parsed:r,timedOut:!1,isCanceled:!1,killed:!1}));return an(g,x)}let a=xs(i),u=fs(i,r.options,a),l=ms(i,r.options,u),p={isCanceled:!1};i.kill=ls.bind(null,i.kill.bind(i)),i.cancel=ds.bind(null,i,p);let h=us(async()=>{let[{error:y,exitCode:g,signal:x,timedOut:I},j,F,xn]=await Ss(i,r.options,l),be=M(r.options,j),we=M(r.options,F),ve=M(r.options,xn);if(y||g!==0||x!==null){let Ee=Z({error:y,exitCode:g,signal:x,stdout:be,stderr:we,all:ve,command:s,escapedCommand:o,parsed:r,timedOut:I,isCanceled:p.isCanceled,killed:i.killed});if(!r.options.reject)return Ee;throw Ee}return{command:s,escapedCommand:o,exitCode:0,stdout:be,stderr:we,all:ve,failed:!1,timedOut:!1,isCanceled:!1,killed:!1}});return hs(i,r.options.input),i.all=ys(i,r.options),an(i,h)};q.exports=J;q.exports.sync=(e,t,n)=>{let r=fn(e,t,n),s=un(e,t),o=dn(e,t);gs(r.options);let i;try{i=xe.spawnSync(r.file,r.args,r.options)}catch(l){throw Z({error:l,stdout:"",stderr:"",all:"",command:s,escapedCommand:o,parsed:r,timedOut:!1,isCanceled:!1,killed:!1})}let a=M(r.options,i.stdout,i.error),u=M(r.options,i.stderr,i.error);if(i.error||i.status!==0||i.signal!==null){let l=Z({stdout:a,stderr:u,error:i.error,signal:i.signal,exitCode:i.status,command:s,escapedCommand:o,parsed:r,timedOut:i.error&&i.error.code==="ETIMEDOUT",isCanceled:!1,killed:i.signal!==null});if(!r.options.reject)return l;throw l}return{command:s,escapedCommand:o,exitCode:0,stdout:a,stderr:u,failed:!1,timedOut:!1,isCanceled:!1,killed:!1}};q.exports.command=(e,t)=>{let[n,...r]=ln(e);return J(n,r,t)};q.exports.commandSync=(e,t)=>{let[n,...r]=ln(e);return J.sync(n,r,t)};q.exports.node=(e,t,n={})=>{t&&!Array.isArray(t)&&typeof t=="object"&&(n=t,t=[]);let r=cn.node(n),s=process.execArgv.filter(a=>!a.startsWith("--inspect")),{nodePath:o=process.execPath,nodeOptions:i=s}=n;return J(o,[...i,e,...Array.isArray(t)?t:[]],w(f({},n),{stdin:void 0,stdout:void 0,stderr:void 0,stdio:r,shell:!1}))}});var Es={};Gn(Es,{default:()=>vs});var N=require("@raycast/api");var mn=Ae(require("node:process"),1),hn=Ae(pn(),1);async function Sn(e){if(mn.default.platform!=="darwin")throw new Error("macOS only");let{stdout:t}=await(0,hn.default)("osascript",["-e",e]);return t}var yn=require("@raycast/api");async function gn(){return(await(0,yn.getApplications)()).find(e=>e.name==="Fantastical")!=null}var vs=async e=>{let t=e.arguments;if(await gn())await Sn(`
6:         tell application "Fantastical" 
7:             
8:  parse sentence "${t.add}" 
---

fan-add-event.js:5:10386
async Sn:fan-add-event.js:5:12141
async Object.vs:fan-add-event.js:5:12368
async MessagePort.<anonymous>:index.js:1:1842

## Steps To Reproduce

This occurs each time I attempt to add an event.

## The current behavior

Receive an error attempting to create an event.

## The expected behavior

Have not been successful with this command yet, but expect it to open a Fantastical window with my info populated.

### Raycast version
Version: 1.39.3

**Comment by devahschaefers** [comment]
Hey gdub99,

Try opening the terminal and running `tccutil reset AppleEvents`

**Comment by gdub99** [comment]
That, and restarting my computer, worked.  Thanks!
