### ISSUE TITLE
[Display Placer] Saving and retrieving preset does not seem to work

### ISSUE THREAD

**Issue by joepio** [raycast/extensions#2842]
# Extension – [Display Placer](https://github.com/raycast/extensions/tree/e962a25cf7a44568c74882b67227f322bf66137c/extensions/displayplacer/)
Author: @eluce2

## Description / steps to reproduce

1. install DisplayPlacer plugin and Homebrew app
2. check with terminal to verify displayplacer is installed
3. Open the `Switch Display Preset` action
4. Select `add new preset`. 
5. Give it some name
6. Save with `cmd+enter`
7. The new preset is nowhere to be found, even after restarting. 

### Raycast version

1.39.3

### Hardware

M1 Macbook pro 14

**Comment by sammykumar** [comment]
Having same issue

**Comment by mazamachi** [comment]
I'm facing the same issue on Raycast v1.43.2
