### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by sudhamjayanthi** [raycast/extensions#2854]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/ac512b4266776e08bc0ef679a47ff398e4449f04/extensions/spotify-player/)
Author: @mattisssa

**Describe the feature and the current behavior/state.**
Command should toggle the menu bar player instead of just turning it on.

i.e if the menu bar player is already showing, it should hide if the command is called again.

currently there is no way to turn it off and only way is to quit spotify.

**Who will benefit with this feature?**
everyone :)

**Comment by danielsequeira** [comment]
@sudhamjayanthi this is possible either in the command actions:
<img width="1000" alt="Raycast 2022-11-03 at 09 43 29" src="https://user-images.githubusercontent.com/12091319/199678559-0349a457-c7c3-4903-a461-c5908dbce46a.png">

Or in the command preferences:
<img width="1000" alt="Screenshot 2022-11-03 at 09 43 48" src="https://user-images.githubusercontent.com/12091319/199678590-b5081f1d-8f64-47d1-8f0a-0188ce1b1c6f.png">
