### ISSUE TITLE
Linear extension: `Create issue` flow doesn't load all labels

### ISSUE THREAD

**Issue by ubuntudroid** [raycast/extensions#2865]
# Extension – [Linear](https://github.com/raycast/extensions/tree/main/extensions/linear)

Author: @thomaslombart  

## Description

As discussed in [Slack](https://raycastcommunity.slack.com/archives/C01A0R0NXGQ/p1659945559816539) the Linear extension doesn't load all available labels in the `Create issue` flow. Filtering (by typing) also only works on the incomplete loaded list of labels, not on all labels.

We have a lot (read dozens) of labels, both for the workspace and for teams. Some of the team labels are missing for us.

## Steps To Reproduce

1. Create a Linear workspace with lots of team and workspace labels (not sure the count of labels plays a role here, but I have a feeling that it does).
2. Setup the Linear raycast extension to connect to the workspace
3. Launch the `Create issue` workflow in raycast and open the label dropdown or start typing.

## The current behavior

Not all labels are shown - for us some team labels were missing. Creation date doesn't seem to play a role here.

## The expected behavior

All labels (both team and workspace ones) should be listed and auto-completed.

### Raycast version

Version: 1.39.3

**Comment by thomaslombart** [comment]
Hey @ubuntudroid, thanks for the issue. I've tried it out on a test workspace and I couldn't reproduce the issue:

https://user-images.githubusercontent.com/16003285/191479219-68ac9ea3-ecf0-447f-80b2-2bda5b13c445.mp4

I have 20+ labels on the design team and they all load properly.

What labels are not shown in your case? Can you see something that could differ from the other labels (specific colors, different characters, etc.)? How many labels do you have?

**Comment by thomaslombart** [comment]
Not stale.

**Comment by thomaslombart** [comment]
@ubuntudroid After investigating, it seems the issue happens because Linear's API only returns the first 50 results by default. I shipped a temporary fix increasing the number of labels to 100. In the future, it'll be possible to search for any labels by their name no matter how big is the number.

**Comment by ubuntudroid** [comment]
Hi @thomaslombart, many thanks for fixing the issue ❤️  and sorry for not getting back to your earlier reply - I somehow missed it in my inbox. 🙈 That's amazing news!
