### ISSUE TITLE
[Asana] - Search All Tasks

### ISSUE THREAD

**Issue by joeynotjoe** [raycast/extensions#2874]
# Extension – [Asana](https://github.com/raycast/native-extensions/tree/98807c71c6ec589775952a250d7225b403e995f5/extensions/asana/)
Author: @PitNikola 

**The extension in its current form allows the user to see tasks assigned to themselves (My Tasks), but we can't search or filter for tasks beyond that.**

**Most Asana users who need to find tasks that are not assigned to themselves, or haven't been completed recently**

**[This Alfred Workflow](https://github.com/adriantoine/alfred-asana#readme) offers this functionality, and I need it in Raycast to convince my team to switch over 😄**

**Comment by PitNikola** [comment]
We are in a process of transitioning Asana extension from built-in to Typescript so that other can contribute. Once it's done, we can take a look at adding search tasks command there (or maybe someone from the community can add it).

cc @mathieudutour @thomaslombart
