### ISSUE TITLE
Emoji Search's Frequently Used list does not use the chosen skin tone

### ISSUE THREAD

**Issue by eatstorming** [raycast/extensions#2878]
Sorry to repost, my comment in a previous related issue seems to have gone unnoticed.

There seems to be a bug with the built-in emoji search: it correctly finds the emoji with the assigned skin tone when I search for it, but it is added to the Frequently Used list with the default (?) yellow skin tone, and clicking on the emoji there will paste it with that tone (yellow) instead the one selected in the Preferences.

![image](https://user-images.githubusercontent.com/20144145/188797548-b9ba190e-eed7-462a-b277-935390bf0639.png)
![image](https://user-images.githubusercontent.com/20144145/188797661-dbe81181-2d28-46e1-b6b4-d7db18250785.png)
![image](https://user-images.githubusercontent.com/20144145/188797742-b928f758-3b88-4278-80eb-efeebd909c7f.png)
![image](https://user-images.githubusercontent.com/20144145/188797795-1d499ab5-5cc0-4162-a646-8be39884a872.png)
![image](https://user-images.githubusercontent.com/20144145/188797925-2568777d-5878-4ae7-87cf-58b8fa25231a.png)

_Originally posted by @eatstorming in https://github.com/raycast/extensions/issues/2120#issuecomment-1238932672_

**Comment by eatstorming** [comment]
@nhojb is the wontfix confirmed?

**Comment by nhojb** [comment]
Not necessarily - it's just a low priority.

It's currently working as intended: the "Frequently Used" section stores the emoji with the skin tone. But I can understand that this behaviour doesn't suit some users, especially those who might switch skin tone frequently.

We have this issue in our internal bug tracker. I think we'd are ok to change the behaviour. It's just a matter of finding time to do the fix 🙂

**Comment by eatstorming** [comment]
Alright, thank you. 😁
