### ISSUE TITLE
[1Password] ...

### ISSUE THREAD

**Issue by matbrady** [raycast/extensions#2880]
# Extension – [1Password](https://github.com/raycast/extensions/tree/af49cfb0791337d66b1ab89b9f843554d02eb6da/extensions/1password/)
Author:

**Describe the feature and the current behavior/state.**

### Current Behavior
Result items are displayed using only the 1Password item name. This creates indistinguishable result that are named the same thing.

<img width="738" alt="Screen Shot 2022-09-13 at 9 01 56 AM" src="https://user-images.githubusercontent.com/1770862/189908668-191b118c-a93b-453e-b026-f38a4df2e28c.png">

### Feature Request

Include username field in result values similar to how 1P does. 
Years ago 1Password discouraged suffixing item names (ex: `Google - personal`, `Google - work`) because they would appear alphabetically in their browser extension results.  Prior to this, results were shown by how recently they were used. 

<img width="575" alt="Screen_Shot_2022-09-13_at_9_59_08_AM" src="https://user-images.githubusercontent.com/1770862/189922290-09da3fb0-2ef7-4e75-b393-8f9f7d1ddfd4.png">

**Who will benefit with this feature?**

Anyone not using suffixes for the 1Password item names. 

**Any Other info.**

**Comment by khasbilegt** [comment]
Hello @matbrady, Sorry for took too long to respond. I am currently rewriting the extension utilizing the 1Password CLI 2 and I will address this issue in the new version. Feel free to add any features you'd like to see as well. Thanks.

**Comment by GreyTeardrop** [comment]
I believe this is still relevant
