### ISSUE TITLE
[Timers] No sound played after the time finish

### ISSUE THREAD

**Issue by Jerry080801** [raycast/extensions#2893]
# Extension – [Timers](https://github.com/raycast/extensions/tree/6ead481b289b6072171326c1e5a8917c1e6cda3c/extensions/timers/)
Author:

**Describe the feature and the current behavior/state.**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by ThatNerdSquared** [comment]
Hi @Jerry080801, thanks for trying out Timers! Several audio options should be available with the extension. Is the "Selected Sound" option set in your extension preferences?
<img width="295" alt="Screen Shot 2022-10-03 at 20 57 14" src="https://user-images.githubusercontent.com/72814106/193731129-0c7baa62-72e1-4da2-b8d5-6e43cf30e003.png">

If so, this may be a bug - sorry about that. Can you try running `afplay /System/Library/Sounds/Hero.aiff` in Terminal, so we can see whether `afplay` works properly on your computer?
