### ISSUE TITLE
[Extension Bug] Dash: HTML special characters not being rendered correctly

### ISSUE THREAD

**Issue by rybertm** [raycast/extensions#291]
Raycast version: 1.25.2

## Description

The search results returned by Dash may contain characters that are html encoded, and since the `Item.title` and `Item.subtitle` are interpreted as normal strings it gets rendered incorrectly.

It may be related to #107.

## Steps To Reproduce

1. Search for any docset that has special character sush as `<`, ex: `Vec::new` in Rust, or `ArrayList` in Java

## The current behavior

<img width="862" alt="Screen Shot 2021-11-03 at 17 36 38" src="https://user-images.githubusercontent.com/60909556/140224662-a555950c-51b6-4836-a38d-0b4af4a18084.png">

## The expected behavior

<img width="862" alt="Screen Shot 2021-11-03 at 17 37 17" src="https://user-images.githubusercontent.com/60909556/140224901-5963bcf4-9ebe-4275-ade6-4e40df8c0ae9.png">

**Comment by rybertm** [comment]
I could open a PR with a fix if you guys think is a good idea

**Comment by RSO** [comment]
Thanks for reporting! Feel free to open a PR!

**Comment by rybertm** [comment]
Closed by #293
