### ISSUE TITLE
[How Long to Beat] 404 Not Found

### ISSUE THREAD

**Issue by FlorianWendelborn** [raycast/extensions#2913]
# Extension – [How Long to Beat](https://github.com/raycast/extensions/tree/main/extensions/how-long-to-beat)

Author: @Cronos87

404 Not Found (Apparently, again #2551 #2557)

![image](https://user-images.githubusercontent.com/1133858/190683125-90211929-6d5d-456b-afa4-aa0adb0a2c70.png)

## Steps To Reproduce

1. Attempt to use extension

## The current behavior

Throws 404 Not Found error

## The expected behavior

Properly searches for games to beat

### Raycast version

Version: v1.39.3

**Comment by yohan-descours-cabaud** [comment]
Hi! Thank you to open an issue about this. First, I need to apology for the late answer, I don't have a lot of time at disposition…
I will take a look at this issue, but it seems HLTB changed the API because of the integration inside the XBOX Game Pass.

Anyway, I'll keep you in touch soon.

**Comment by Cronos87** [comment]
Hi! Thank you to open an issue about this. First, I need to apology for the late answer, I don't have a lot of time at disposition…
I will take a look at this issue, but it seems HLTB changed the API because of the integration inside the XBOX Game Pass.

Anyway, I'll keep you in touch soon.

**Comment by FlorianWendelborn** [comment]
@Cronos87 no worries, I know that a random opensource extension isn't gonna get enterprise-level customer support. I just wanted to report the issue so someone can fix it eventually
