### ISSUE TITLE
[Shell] ...

### ISSUE THREAD

**Issue by jifengxuer** [raycast/extensions#2918]
# Extension – [Shell](https://github.com/raycast/extensions/tree/1f127d2aeff488922841f412ca82d63f68309e94/extensions/shell/)
Author: @KELiON

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.39.3

**Comment by pernielsentikaer** [comment]
Hi @jifengxuer 👋 

You added an empty report, can you please fill it out 🙂
