### ISSUE TITLE
[Toothpick] ...

### ISSUE THREAD

**Issue by norrichs** [raycast/extensions#2923]
# Extension – [Toothpick](https://github.com/raycast/extensions/tree/d228408bdb2e9155158cc8ff175d0c79d6188141/extensions/toothpick/)
Author: Ben Norrichs

**Describe the feature and the current behavior/state.**
- I'd like to be able to toggle connection to a specific preselected device, triggered by a hotkey binding.
- It would be great if the UI dismissed itself without any further clicks, with either success or failure.
- e.g.
1) hotkey
2) small window pops up - "Searching for <device name>"
3) if discovered
    a) if already connected - "Disconnecting"
    b) if not connected - "Connecting"
4) if successful - "Success, <device name> is connected. Window closes.
5) if not discovered "Sorry, <device name> not discovered
6) if connection / disconnection not successful, "Sorry, <device name> was not able to be <connected / disconnected>

**Who will benefit with this feature?**
Someone who uses a bluetooth device connected to multiple devices, and would like frictionless switching.
My specific use case is a headset that I use both for my phone and laptop.

**Any Other info.**

**Comment by VladCuciureanu** [comment]
Implemented these features in my fork [here](https://github.com/VladCuciureanu/Toothpick)

Currently at an airport so I'm unable to update the pull request but these changes will also be part of my proposed modifications here: #2641

**Comment by kvenn** [comment]
So excited for this (and the favoriting feature)!! Nice work.

I could see this playing really well with connecting bluetooth and setting audio output device (in the case of automatically connecting airpods). I have airpods set as my favorite for output device, now I just need it to connect.

**Comment by VladCuciureanu** [comment]
> So excited for this (and the favoriting feature)!! Nice work.
> 
> I could see this playing really well with connecting bluetooth and setting audio output device (in the case of automatically connecting airpods). I have airpods set as my favorite for output device, now I just need it to connect.

Really appreciate your comment! Glad to hear you find it useful too. As always, improvement suggestions are appreciated.

**Comment by VladCuciureanu** [comment]
Solved by #2641 (hopefully)
@norrichs Maybe close this issue?
