### ISSUE TITLE
Enable / Disable keyboard shortcut based on frontmost application

### ISSUE THREAD

**Issue by Sheraff** [raycast/extensions#2926]
**Describe the feature and the current behavior/state.**
I'd like to be able to configure a hotkey to only be active if a specific app is the frontmost app, or always be active unless a specific app is the frontmost app.
- for example, I might want to use <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>P</kbd> as a hotkey for "Search Menu Items", **unless** I'm on VSCode. This way I always know that my "main search function" is <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>P</kbd>.
- another example, I want to use <kbd>cmd</kbd>+<kbd>R</kbd> as a hotkey to a script that will "reload current tab on Chrome" so that whatever app I'm on while working on a website, I can refresh it. **Unless** the frontmost app is Safari or Firefox because I'm debugging those, in which case I need to be able to type <kbd>cmd</kbd>+<kbd>R</kbd> without being intercepted by Raycast

Here's such a setup done in Alfred (<kbd>cmd</kbd>+<kbd>R</kbd> refreshes Chrome, unless any of these is frontmost):
<img width="530" alt="Screen Shot 2022-09-17 at 22 49 25" src="https://user-images.githubusercontent.com/1325721/190875959-43ab8dfa-1060-457d-8e4f-61f3369939c2.png">

**Will this change the current API? How?**

**Who will benefit from this feature?**
Anyone who uses a lot of hotkeys. Anyone who likes to associate some semantics to muscle memory. Anyone on VSCode or Vim. Lots of people 😉

**Any Other info.**
I used to be one of the main workflow authors for Alfred (though I haven't done that in a long while) so I might be biased about my mental model of how such apps should work. I'm definitely open to hearing how one would go about achieving the kind of things I've described as examples above.

**Comment by mathieudutour** [comment]
Hey! Thanks for the feedback, noted. However I'm going to close the issue here since it's not related to the API

**Comment by Sheraff** [comment]
@mathieudutour is there somewhere else I should open this issue? Or is this another way of saying "won't implement"?

**Comment by mathieudutour** [comment]
I added your feedback to our feedback management system. I can't promise we will implement it soon but it's on our list now :)
