### ISSUE TITLE
Filtering list item titled based on search text causes flicker

### ISSUE THREAD

**Issue by prurph** [raycast/extensions#2929]
Raycast version: 1.39.3

## Description

When using a `List` with `onSearchTextChange` and `enableFiltering` explicitly on, if there is only one `List.Item` displayed, and its title depends on the search text, there is a "no results" flicker when the search text is updated.

This does not happen if `enableFiltering` is off, or if the item's props do not depend on the search text, so it seems likely the filter is being applied with the new search text before the component has been updated to match the new text.

Using `throttle` on the `List` does work around this issue at the cost of being slow to update the item title. 

Is there another workaround that doesn't involve managing custom filtering myself? The built-in Raycast matching works great and I'd really like to use it. The use case for this is to offer a list of options, filter them as the user types, and also offer an additional option based on their search text, sort of like "pick one of these, or make your own".

## Steps To Reproduce

Minimal example:

```javascript
import { List } from "@raycast/api";
import { useState } from "react";

export default function Command() {
  const [searchText, setSearchText] = useState("");

  return (
    <List enableFiltering={true} onSearchTextChange={setSearchText}>
      <List.Item
        icon="list-icon.png"
        title={`You searched for: ${searchText}`}
      />
    </List>
  );
}
```

Flickering (low framerate on gif doesn't capture it super well; it's present on each keypress):

![flicker.gif](https://user-images.githubusercontent.com/6109531/190882970-31377d9b-408b-44cb-8625-fb89c757514f.gif)

## The current behavior

When filtering is on, changing the search text causes "No results" to flicker.

## The expected behavior

Changing the search text updates the `List.Item` without flickering "No results". The filter function and component see a consistent state of the search text.

**Comment by mathieudutour** [comment]
That's the expected behaviour of `enabledFiltering`: it turns on the built-in filtering of Raycast. Since React renders are asynchronous, you will get some flickering. I'm not sure we can do much about it.

What are you trying to do exactly?

**Comment by prurph** [comment]
Thanks--I understand the expected behavior, but since the item has the `searchText` in it, ideally it should always appear. I get that this is happening because of the render cycle and the filter being applied to updated `searchText` before the item component has been updated and that this is managed by React.

My extension stores some files that represent screen window layouts, then gives users the option to restore that layout, or to overwrite it with the current screen window layout, so it will present an item for each file. Additionally, I'd like to allow users to save the current layout to a new file, with the name of whatever they've typed in.

Since the built-in filtering works great I was hoping to avoid writing a custom filter, but obviously a minor inconvenience and just adding throttle is a good workaround.

**Comment by mathieudutour** [comment]
Right, then maybe use an action instead of a list item? And an EmptyView? I don't think it's something that can be "fixed"

**Comment by prurph** [comment]
I modified this in line with your suggestion and moved all the functionality toward actions instead of creating a list item based on the search text and it works great. Thanks!
