### ISSUE TITLE
[OpenAI GPT3] Bug with form input info tooltips when updating values

### ISSUE THREAD

**Issue by lazarjov** [raycast/extensions#2930]
# Extension – [OpenAI GPT3](https://github.com/raycast/extensions/tree/6ed78afea5451ac8aff90905ecf2cc4ecffff578/extensions/openai-gpt3/)
Author: @simicvm

## Steps To Reproduce

1. Open 'Query OpenAI GPT3' command
2. Scroll to change _Frequency Penalty_ or _Presence Penalty_ parameter?
3. Hover over the info icon to the right to observe a tooltip
4. Remove the existing value in on the parameter
5. Observe the error message
6. Add a value as a number
7. Info icon that activates the tooltip is now gone
8. Do the steps 4-6 in the other parameter
9. Observe that the icon for parameter #1 is back, but icon for parameter #2 is now gone

See video: https://share.cleanshot.com/Mt7VLj

## The current behavior
Info icon disappears

## The expected behavior
Info icon should stay

### Raycast version
Version: 1.39.3

**Comment by simicvm** [comment]
Thanks for the report @lazarjov. I am aware of this behavior. It’s a bug in Raycast and the team is working on it.
