### ISSUE TITLE
[Unicode Symbols Search] Add commonly used names to search

### ISSUE THREAD

**Issue by Sheraff** [raycast/extensions#2931]
# Extension – [Unicode Symbols Search](https://github.com/raycast/extensions/tree/d18a6e43408d105a3ed7a17b6693fca19ea75ea3/extensions/unicode-symbols)

Author: @mmazzarolo 

**Describe the feature and the current behavior/state.**
It would be nice to add some "commonly used" names to some characters so they can be easier to find, even if such names aren't in the official char name. For example:
- <kbd>⇧</kbd> could be found with the string "shift" (currently, "UPWARDS WHITE ARROW")
- <kbd>⌘</kbd> could be found with the string "command" or "cmd" (currently, "PLACE OF INTEREST SIGN")
- <kbd>⌥</kbd> could be found with the string "alt" (currently, "OPTION KEY")
- <kbd>⌃</kbd> could be found with the string "ctrl" or "control" (currently not in dataset)
- <kbd>⌫</kbd> could be found with the string "delete" or "backspace" (currently "ERASE TO THE LEFT")

I'm sure there are other categories of characters that might also have some "common names" that people might report over time.

**Who will benefit from this feature?**

**Any Other info.**
As a side thing, would this extension still feel nice to use if it switched to the newer Grid layout? Some of the characters are quite small for the list view.

**Comment by mmazzarolo** [comment]
Hey @Sheraff ! Thanks for the feature request. I'm pretty sure [this is the solution you're looking for](https://github.com/raycast/extensions/issues/2240#issuecomment-1233997222) — Personally, I don't have enough free time to develop it now though, maybe in a month. 

> As a side thing, would this extension still feel nice to use if it switched to the newer Grid layout? Some of the characters are quite small for the list view.

Yeah, that's a great idea :)
