### ISSUE TITLE
[Dash] Use dash docset keywords as raycast command titles

### ISSUE THREAD

**Issue by Sheraff** [raycast/extensions#2935]
# Extension – [Dash](https://github.com/raycast/extensions/tree/9bb68f9ca1f2a52f52cb0ed9d04c43b85842fb0d/extensions/dash/)
Author: @sxn @RSO 

**Describe the feature and the current behavior/state.**
I would like the workflow for looking up docs to be:
- `⌥ + space` (open raycast)
- `"css"` (choose docset)
- `⇥` (launch command)
- `"margin"` (query docset)

Whereas right now there are 2 additional steps:
- `⌥ + space` (open raycast)
- `"dash"` (choose dash command)
- `⇥` (launch command)
- `"css"` (find docset)
- `⇥` (choose docset)
- `"margin"` (query docset)

Dash does offer the user the ability to set "docset keywords" in its interface, which it uses for its own search, as well as in its Alfred extension. It would be great to have the same ability in Raycast.

**Who will benefit with this feature?**
- every Dash user who has already too many keyboard shortcuts to remember and would like to not have to remember one for opening dash in raycast.

**Any Other info.**

**Comment by Sheraff** [comment]
> At this point, Raycast does not support dynamically defining commands in Extensions

To be fair, Alfred doesn't really support this either, but since its extensions are clear text (xml IIRC) this kinda is something that is doable. However I think this feature could be really neat for other "user defined" commands like for example a "translate" that allows the user to directly target "EN -> ES" by typing "ES".

**Comment by Cobular** [comment]
Bumping this as well - I see that it's not possible to do it dynamically, but would it be possible to register 5-10 commands that start out disabled and can be given aliases and mapped to searching a docset through the settings? It likely wouldn't be optimal but it work in the meantime!

**Comment by JasonBoy** [comment]
I am also trying to skip the first step, so I am making some changes to the extension, add two more commands to make it happen with the help of quicklink, here is the sneak peak of the change, when I am done, I will try to publish the code to this extension:

https://github.com/raycast/extensions/assets/2911620/4cdd24a8-50d4-44bc-bb78-e5909cd0713b

**Comment by Sheraff** [comment]
@JasonBoy that's dope! sorry i never saw this because i kinda went back to Alfred for a while to let raycast mature a bit, but I'm setting it up again and this was really one of the big missing pieces for me. Thanks!
