### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by MrMatt101** [raycast/extensions#2938]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/3553095541474d8e97fa564fa94279a1f5d5fb07/extensions/spotify-player/)
Author: @mattisssa

Giving the user the ability to choose what the menu bar player shows instead of just choosing the length of what is shown.

**Describe the feature and the current behavior/state.**
The feature will give the user the option to choose what is shown in the menu bar instead of just asking for how long it should be. This would be great for showing the song title by itself instead of showing the artist as well.

**Who will benefit with this feature?**
This feature will certainly benefit those who want to have information of the song they are listening to, since it is one of the best features I have seen in a Raycast extension, but it would help those who would like more space on their menu bar (like those with a mac that has a notch) without losing any important or wanted information.

**Comment by daikaiyu** [comment]
When I switched to MacBook with notch, I realized that menu bar was a very precious place.I think it is possible to configure the display content, position base on length limit.
