### ISSUE TITLE
[Music] General search function

### ISSUE THREAD

**Issue by TheGoodDude22** [raycast/extensions#2940]
# Extension – [Music](https://github.com/raycast/extensions/tree/e17b4a3c292e85ccd4933df860af435f487dc478/extensions/music/)
Author: @Rawnly

A broad Search command that could search songs, albums, and playlists all at once.

**Describe the feature and the current behavior/state.**
Currently, tracks, albums, and playlists need to be started from their own individual commands. I invoke the track command from a single keybind, but if I want to play an entire album I instead have to back out and go to the album specific search. A broad search that goes across categories would be nice to have.

**Who will benefit with this feature?**
People that like to control their music from the keyboard!

**Any Other info.**
I don't know if it's possible, but it would also be nice to be able to "Play Next"/"Play Later" a track instead of instantly overriding the current song. Thank you!

**Comment by Rawnly** [comment]
Hi! Thanks for asking! I'll try to look into this asap! I would like to merge #2844 first. Please be patient 😅 it could take a while

**Comment by Rawnly** [comment]
Given that, an idea could be to merge the 3 searches into one, it could be slower but maybe with some parallelism we could archive it!
