### ISSUE TITLE
[Google Meet] Create new meet for other than default users e.g. /u/1

### ISSUE THREAD

**Issue by TonyVlcek** [raycast/extensions#2948]
# Extension – [Google Meet](https://github.com/raycast/extensions/tree/main/extensions/google-meet/)

Author: @vitoorgomes

**Describe the feature and the current behavior/state.**
I'd want to be able to create a new meeting under a non-default google account. This can be done easily by adding, for example, `/u/1` as a suffix to the URL. I think a simple configuration field where a user can specify this suffix would be enough to start with.

This could be considered as an "advanced" feature to start with, and instead of having a special google account selector just add a simple text box where the URL suffix which determines the user can be added (e.g. `/u/1`).

At the moment there is no configuration possible.

**Who will benefit from this feature?**
Anyone who is using multiple google accounts. This will be perfect for people who have their personal google account set as the default one but want to open meeting under their work accounts. 

**Other info**
Thanks, I'm using this extension a lot and I love the fact that it copies the URL. Such a simple thing but it saves a couple of clicks. 🎉

**Comment by vitoorgomes** [comment]
Hi @TonyVlcek 

I loved your suggestion, it was in fact on my personal roadmap to add something like this in the future.

I'm busy this week, but I'll gladly look into this as soon as possible (probably this weekend or next week).

Cheers

**Comment by vitoorgomes** [comment]
hey @TonyVlcek 

I barely had time the last couple of weeks so I had to delay this, but now the PR is open and hope it will merge soon

cheers

**Comment by TonyVlcek** [comment]
@vitoorgomes Legend! Let me know if I can help with testing or anything else 👍

**Comment by vitoorgomes** [comment]
this issue can be closed now @pernielsentikaer

**Comment by pernielsentikaer** [comment]
Closing 😊
