### ISSUE TITLE
[Extension Bug] Brew extension produces errors with every command.

### ISSUE THREAD

**Issue by carpedavid** [raycast/extensions#295]
@nhojb 

Raycast version: 1.25.3

## Description

When running *any* available command, I get an error:

```
Error: Command failed: brew --prefix
/bin/sh: brew: command not found


/bin/sh: brew: command not found

checkExecSyncError:node:child_process:826:11
execSync:node:child_process:900:15
installed.js:1:308891
Object.<anonymous>:installed.js:1:308934
Module._compile:loader:1101:14
Object.Module._extensions..js:loader:1153:10
Module.load:loader:981:32
Function.Module._load:loader:822:12
Module.require:loader:1005:19
require:helpers:102:18
```

* I'm running Monterey 12.0.1 on an iMac (M1, 2021)
* Homebrew was installed using the standard install instructions available on https://brew.sh
* My copy of Homebrew lives in "/opt/homebrew/bin/brew" (via "which brew")
* It works without issue from the terminal (I use it every day)

## Steps To Reproduce

1. Run "Show Installed"
2. View the "Something went wrong" screen

## The current behavior

Any command blows up.

## The expected behavior

It works.

**Comment by nhojb** [comment]
@carpedavid are you using an M1 Mac? This is a known issue on this architecture.

I have a [PR](https://github.com/raycast/extensions/pull/259) pending which should address the issue.

**Comment by carpedavid** [comment]
Oh! Yes, that would be the issue. I didn't do an exhaustive enough search to see that you already have a PR out for it. Thanks!

**Comment by nhojb** [comment]
PR is merged now. Please let me know if you continue to have any issues on M1.

**Comment by carpedavid** [comment]
It works! Perfect!

——
David Garrett

***@***.***
https://aboutdave.info
