### ISSUE TITLE
Preselect ActionPanel.Submenu item

### ISSUE THREAD

**Issue by thomaslombart** [raycast/extensions#2959]
**Describe the feature and the current behavior/state.**

It would be great to preselect an `ActionPanel.Submenu` item so that users don't have to get started from the top of the submenu list like below:

![CleanShot 2022-09-20 at 12 12 02@2x](https://user-images.githubusercontent.com/16003285/191232222-abfe19e4-734a-4a55-bae7-a8630f508a3f.png)

**Will this change the current API? How?**

This would probably imply adding some props to `ActionPanel.Submenu` as well as `Action`

**Who will benefit from this feature?**

Any users making use of submenus.

**Comment by thomaspaulmann** [comment]
That would be a nice addition indeed and it's something we have on the native side already. Do you have any particular API in mind?

**Comment by thomaslombart** [comment]
I always felt like `ActionPanel.Submenu` was similar to a dropdown UX-wise so a similar API would make sense to me:
- A `value` prop on `ActionPanel.Submenu` along with a `onChange` handler (knowing that `value` will be passed as an argument to the handler)
- A `value` prop on `ActionPanel.Submenu`'s children

However, the `Action` component is not only used in `ActionPanel.Submenu`. So, maybe it would be worth creating a new component `ActionPanel.Submenu.Item` to avoid any confusion on what props `Action` accept depending on the use case.

**Comment by mathieudutour** [comment]
Available in v1.43
