### ISSUE TITLE
Unable to change Atlassian account in the Jira extension

### ISSUE THREAD

**Issue by GerardSetho** [raycast/extensions#2961]
Raycast version: 1.39.3

## Description

I'm unable to change to another Atlassian account when using the Jira Search extension. 

## Steps To Reproduce

1. I open Jira Search in Raycast's preferences
2. I login to my account 1 (say "gerard.setho@example.com")
3. I logout (also from Raycast's preferences)
4. When I try to login again, I'm unable to use a different account. The web login form does not allow me to enter a different user email.

## The current behavior

See steps to reproduce.

## The expected behavior

I expect Raycast to prompt me for an Atlassian email, before redirecting me to the web login page.

**Comment by thomaspaulmann** [comment]
Hey, I don't think this is an issue with Raycast. It's rather how youre browser handles the OAuth flow. If you can remove the logged in Atlassian session in your browser, you should be able to authenticate with another account. Alternatively, you should be able to copy the OAuth link in Raycast when authenticating and open it in a private browser window to authenticate with Atlassian.
