### ISSUE TITLE
[Window Management] Jump window between monitors

### ISSUE THREAD

**Issue by indaviande** [raycast/extensions#2963]
# Extension – Window Management

Author: RayCast

**Describe the feature and the current behavior/state.**
If you have two monitors side by side, it would be great to jump the window from one monitor to the other when you press hotkey to go from half left to half-right, twice. 
[Magnet app does that.](https://magnet.crowdcafe.com/)

**Who will benefit from this feature?**
All people with two or more screens.

**Comment by indaviande** [comment]
Hi, 
I think this could be implemented!

**Comment by reslear** [comment]
also need, like rectangle

**Comment by reslear** [comment]
> We could not find the extension related to this issue. Please update the issue with the link to the extension.

**Comment by reslear** [comment]
@raycastbot reopen
