### ISSUE TITLE
[GitHub] Show Draft PRs with a different Icon

### ISSUE THREAD

**Issue by ClayBenson94** [raycast/extensions#2974]
# Extension – [GitHub](https://github.com/raycast/native-extensions/tree/4727942f956f19fedb74e7a4ff7c6904bb960fd6/extensions/github/)
Author:

I would like to see different icons for PRs that are drafts.

**Describe the feature and the current behavior/state.**
Currently there are different icons for different PR statuses (open, closed, merged), but there isn't one for [Draft PRs](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

The screenshot below (with some censored titles) shows the current state. The blue-censored PR is currently in draft, and you can see that the icon is the same as the one right above it.

![Screen Shot 2022-09-21 at 8 39 46 AM](https://user-images.githubusercontent.com/15203744/191506282-b0bfd31b-c142-4f63-bdb3-6bde3c996448.png)

**Who will benefit with this feature?**
Anyone who uses this extension and has Draft PRs as part of their workflow

**Any Other info.**

**Comment by mathieudutour** [comment]
This is now the case in the new GitHub beta extension (which will be out of beta soon!)

**Comment by ClayBenson94** [comment]
@mathieudutour Will this show up as an update to the existing extension, or will it be a new extension when it's out of beta?

**Comment by mathieudutour** [comment]
once it's out of beta we will deprecate the native extension and point to the new one
