### ISSUE TITLE
[Spotify Player] Menu Bar Player text color unreadable on blur

### ISSUE THREAD

**Issue by SenseiMarv** [raycast/extensions#2975]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/3553095541474d8e97fa564fa94279a1f5d5fb07/extensions/spotify-player/)
Author: Marvin Stickel

## Description
When a screen is blurred (another screen is focused), the text color of the Menu Bar Player gets inverted. This makes the text unreadable in most situations.

![example](https://user-images.githubusercontent.com/41735601/191521739-f543e8de-e861-4f90-9f75-b8fc5d329b4c.png)

## Steps To Reproduce

1. Have a setup with more than one screen and the Menu Bar Player of the extension enabled in the extension preferences.
2. Focus on a application on one screen and look at the text color of the Menu Bar Player on another screen. Compare the color to other icons in the menu bar on the same screen.

## The current behaviour
The text color of the Menu Bar Player doesn't become transparent like other items in the menu bar but instead inverts.

## The expected behaviour
The text color of the Menu Bar Player should become slightly transparent but with the same color. (This is also the same behaviour that other apps like [Stats](https://github.com/exelban/stats) have)

### Raycast version

1.39.3

**Comment by mathieudutour** [comment]
Fixed in 1.45!
