### ISSUE TITLE
[Music] Love and/or add to library does not work

### ISSUE THREAD

**Issue by eproxus** [raycast/extensions#2984]
# Extension – [Music](https://github.com/raycast/extensions/tree/main/extensions/music)

Author: @Rawnly @fe9lix

## Description

The extension crashes when trying to perform the following shortcuts on tracks which are not in the library:

* _Add to Library_
* _Love Track_
* _Love and Add to Library_

**Note:** strangely enough, the _Dislike Track_ shortcut works just fine.

## Steps To Reproduce

1. Play music from an Apple Music subscription (_not_ from your library)
2. Run any of the above shortcuts

## The current behavior

The following error occurs:
```
Command failed with exit code 1: osascript -e tell application "Music" to duplicate current track to library playlist "Library"
28:81: execution error: Music got an error: Can only duplicate subscription tracks to library source. (-10006)
```

## The expected behavior

The shortcuts are successful, as if the same button was pressed in the Apple Music application itself.

### Raycast version

Version: v1.39.3

### macOS versions

macOS: 12.5.1
Apple Music: 1.2.5.7

**Comment by Rawnly** [comment]
> It seems that some AppleScript apis have changed, I'm working on an update asap. Thanks for reporting!
> 
> The current syntax should be
> 
> `duplicate current track to source "Library"`

Unfortunately it seems that this have some errors too I currently encounter the following:

`28:71: execution error: Music got an error: Can’t set source "Library" to current track. (-10006)`

I'll try to find a solution somehow.

**Comment by eproxus** [comment]
Thanks for looking into it, the whole Apple Music subscription vs library is a huge mess.

**Comment by Rawnly** [comment]
@eproxus with my latest PR #3358 it should've been fixed. Let me know!

**Comment by eproxus** [comment]
@Rawnly Thanks, it works! ❤️
