### ISSUE TITLE
[Extension Bug] Things extension doesn't work when Things is not in English

### ISSUE THREAD

**Issue by edjw** [raycast/extensions#299]
## Extension – [Things](https://github.com/raycast/extensions/tree/main/extensions/things)
**Author:** @loris 
Raycast version: 1.25.3

## Description

Using the Things Raycast extension gets an error that the Object (list) can't be found if Things is being used in a language other than English

## Steps To Reproduce

1. Install Things
2. Use Things in a non-English language
3. Install the Things Raycast extension
4. Get the error "Object can't be found -1728" 

## The current behavior

Accessing a Things list through the Raycast extension errors out. My Things is in German.

## The expected behavior

I can access my Things lists in Raycast using the extension even when my Things application is set up in a non-English language

**Comment by mattisssa** [comment]
Hey @loris ! 
🐞 Here is the bug report request to your extension, take a look at that and subscribe to don't miss anything related 😉

**Comment by loris** [comment]
Hi @mattisssa @edjw thanks for the report, this has been fixed as part of this PR: https://github.com/raycast/extensions/pull/418 (not yet live)

**Comment by edjw** [comment]
@loris thanks that's great. Really appreciate your work on this
