### ISSUE TITLE
Encountered two children with the same key

### ISSUE THREAD

**Issue by Jax0rz** [raycast/extensions#2992]
Raycast version:1.39.3

## Description
```
Warning: Encountered two children with the same key, `Startup Grind Kunming`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```
## Steps To Reproduce

I'm writing a chat contact search extension ,there're some people with the same name

## The current behavior

the extension works ok but there is a warning in console "Encountered two children with the same key"

## The expected behavior

Support the same key value in the.

**Comment by mathieudutour** [comment]
That's not possible, it's a necessary for react: https://reactjs.org/docs/lists-and-keys.html#keys
