### ISSUE TITLE
[Spotify Player] Where to paste Client ID and Client Secret?

### ISSUE THREAD

**Issue by 4eroflot** [raycast/extensions#2995]
Hi,
thank you for developing the Spotify player extension.
Where am I supposed to paste Client ID and Client Secret? Is it redundant after logging into Spotify?
Which functions are available only to Spotify premium users?
Does the raycast support web apps from brave or flotato?

Thanks!

**Comment by kasparlaurenz** [comment]
any updates on this?

**Comment by mathieudutour** [comment]
Can you open an extension issue instead? https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...
