### ISSUE TITLE
[cURL] ...

### ISSUE THREAD

**Issue by RazorII** [raycast/extensions#3003]
# Extension – [cURL](https://github.com/raycast/extensions/tree/733cf9d6a3fe3376cfeee56e0c8d8c291d1dd4b7/extensions/curl/)
Author: @jonathangiardino

**Describe the feature and the current behavior/state.**
Currently there is no way to sort the extensions in the built in store extension. Having recently added, alphabetical, most installed, ... as options would be helpful to explore the store.

**Who will benefit with this feature?**
Anyone who wants more store customizability.

**Any Other info.**

**Comment by jonathangiardino** [comment]
HI @RazorII, I am not quite sure how this is related to the cURL extension.

This seems more like a global Raycast store feature.

**Comment by RazorII** [comment]
Oh, it was intended for the whole Recast app … sorry, I thought the feedback from the Command + K options was for the store but it selected the top app I assume. Please ignore this & my apologies.

Kind regards,
Hans
