### ISSUE TITLE
[Shell] zsh support

### ISSUE THREAD

**Issue by franmontaldo** [raycast/extensions#3021]
# Extension – [Shell](https://github.com/raycast/extensions/tree/1f127d2aeff488922841f412ca82d63f68309e94/extensions/shell/)
Author: @KELiON

It would be nice to configure if you want zsh rather than bash

**Comment by stychu** [comment]
Exactly my need after finding about raycast and this extension. Please add zsh execution

**Comment by ryanmsnyder** [comment]
Would also love to see zsh support!
