### ISSUE TITLE
[Search StackOverflow] Sort by view count

### ISSUE THREAD

**Issue by Steellow** [raycast/extensions#3024]
# Extension – [Search StackOverflow](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/stackoverflow/)
Author: @sadanand-singh

**Describe the feature and the current behavior/state.**

Currently the search results are primarily sorted by answer count. I think it would make more sense to sort them by view count, since the amount of answers doesn't necessarily correlate with the question relevancy.

On the other hand, more views most likely means more relevant search result. I tried modifying the sort function, and at least for me, the results seem to be much better when primarily sorting by view count.

**Any Other info.**

I'd be more than happy to open PR about this myself if it's ok

**Comment by sadanand-singh** [comment]
Please feel free to open a PR. Thanks!
