### ISSUE TITLE
[cURL] ...

### ISSUE THREAD

**Issue by JonMoore46** [raycast/extensions#3025]
# Extension – [cURL](https://github.com/raycast/extensions/tree/733cf9d6a3fe3376cfeee56e0c8d8c291d1dd4b7/extensions/curl/)

### The ability to specify headers other than those suggested by the extension.

**Describe the feature and the current behavior/state.**
There are some custom headers/non standard headers for an internal API I would like to be able to set however I can only seem to select from the list of headers provided by the extension rather than being able to type in any manually. 

**Who will benefit with this feature?**
I would imagine most people would benefit from being able to specify headers other than those provided by the extension. 

**Any Other info.**

**Comment by josephtaylor-mn** [comment]
I would also really appreciate this feature
