### ISSUE TITLE
menu bar extention not showing up[Spotify Player] ...

### ISSUE THREAD

**Issue by M0N3Y3N0M** [raycast/extensions#3031]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/3553095541474d8e97fa564fa94279a1f5d5fb07/extensions/spotify-player/)
Author:

## Description
the mneu bar does not work
## Steps To Reproduce

1. install spotify extention

## The current behavior
no menu bar extention

## The expected behavior
menu bar extention

**Comment by danielsequeira** [comment]
@M0N3Y3N0M can you confirm that this is working now?
