### ISSUE TITLE
[Logseq] Date incorrect for journals setup with `EEEE` for day name - Extension: 'Logseq'

### ISSUE THREAD

**Issue by drawingthesun** [raycast/extensions#3033]
# Extension – [Logseq](https://github.com/raycast/extensions/tree/main/extensions/logseq)

Author: @futantan

## Description

For my journal date format `yyyy-MM-dd EEEE` the journal file being edited is `journals/2022-09-27 EEEE.md`.

The correct version should be `journals/2022-09-27 Tuesday.md

## Steps To Reproduce

1. Use the Logseq Quicknote
2. Notes are appended to the incorrect file for some users.

## The current behavior

Notes are appended to the file `journals/2022-09-27 EEEE.md`

## The expected behavior

Notes should be appended to the file `journals/2022-09-27 Tuesday.md`

### Raycast version

Version: Version 1.39.3

**Comment by futantan** [comment]
hi @drawingthesun 
This is fixed. Please help to close this issue if you test it ok
