### ISSUE TITLE
How to copy Client ID and Client Secret into the extension preferences

### ISSUE THREAD

**Issue by TheMightyMinski** [raycast/extensions#3037]
Hello,

Thank you for you development of the Spotify extension for Raycast. I have a very simple issue regarding the instruction how to set up the extension. I followed you description in "read me". I got the Copy Client ID and Client Secret but I simply do not see a way how to copy them into the extension. 

When in Raycast preferences, I find the Spotify extension. But there seems to be no way to get the ID and secret into the extension (no field, no command etc.). Could you help me please?

Thanks a lot!

All the best,
Andreas

**Comment by mattisssa** [comment]
Hey, the instruction has been outdated for quite a while now 🤪
It will be fixed with [this](https://github.com/raycast/extensions/pull/3767) PR.

Do you still have issues with auth? It uses simple OAuth to authenticate you with your Spotify account.
