### ISSUE TITLE
[Tailwind CSS] does not shows text classes

### ISSUE THREAD

**Issue by danielo515** [raycast/extensions#3040]
# Extension – [Tailwind CSS](https://github.com/raycast/extensions/tree/5493032894efca9ae862374623f66c86419d22d6/extensions/tailwindcss/)
Author: @vimtor

Hello, thanks for this extension, the idea is great, but for some reason it is not finding any text utility classes.

## Steps To Reproduce

1. Try to search any class related to text, for example text-xs or font-medium, etc
2. Don't find anything

## The current behavior
There are no results in the command to search for classes

## The expected behavior
To find the text related classes

### Raycast version
Version: 1.39.3

**Comment by danielo515** [comment]
It may be stalled, but it is unfixed

**Comment by vimtor** [comment]
Hi @danielo515 I think there are a lot of CSS classes missing. I didn't code that command myself so I would have to look into how does it work. For what I remember the clases were created manually so we will need a better way to generate them to the latest version.

**Comment by vimtor** [comment]
After some research I found this article: https://redpixelthemes.com/blog/tailwindcss-generate-all-classes/
Maybe I could do a little script to generate all the possible classes

**Comment by danielo515** [comment]
That will be lovely 😊 
Will be worth considering generating several sets for the different versions and allow the user pick the version. Happened to me several times that I tried to use a feature my version of tailwind does not have. Or, maybe it is just enoug to add a “From:version” annotation
