### ISSUE TITLE
[Todoist] Support for assignees

### ISSUE THREAD

**Issue by mikestopcontinues** [raycast/extensions#3049]
# Extension – [Todoist](https://github.com/raycast/extensions/tree/main/extensions/todoist)

Author: @thomaslombart 

My husband and I share Todoist lists to keep track of tasks. Others use it for teams. To make it easier to work with this extension, I think the following would be awesome:

1. Today's Tasks and Upcoming Tasks should only show (a) tasks assigned to me and (b) tasks assigned to no one. Other views should show all tasks. This is in line with how the Todoist app shows tasks.
2. I would similarly like to see who all tasks are assigned to in task lists. 
3. I would like to see who a task is assigned to on the task info screen.

Since not all Todoist users use the assignee feature, I think it's important to detect which users have any sharing settings enabled and only show assignee info for them. And maybe a global setting, "Show assignee info": `always`, `never`, `if sharing lists` (default).

**Who will benefit from this feature?**

Anyone who uses Todoist with other people.

**Any Other info.**

I'm open to contributing if we agree on the spec.

**Comment by thomaslombart** [comment]
Hey @mikestopcontinues! Thanks for bringing up the issue.

Under the hood, the extension uses the [Todoist REST API](https://developer.todoist.com/rest/v2/#overview) which doesn't support retrieving all users of a given Todoist project. A task only has an assignee ID and an assigner ID which makes it impossible to display the user's name and avatar.

There are two ways of implementing the feature:
1. Make use of [Todoist Sync API](https://developer.todoist.com/sync/v9/#overview) which supports retrieving user info. However, the useful [TypeScript client](https://github.com/Doist/todoist-api-typescript) used to perform Todoist API operations doesn't support any Sync API calls.
2. Ask the API team at Doist to allow retrieving user info.

Technically, the 2nd solution sounds better, but it's unlikely it'll be done in the upcoming weeks in my opinion.

In the meantime, feel free to look into it and suggest alternatives if you find them. The specs you describe in the ticket seem to be spot-on. The closest we are to Todoist's features, the better.

I have little time to dedicate to the extension in the upcoming month so I can't promise this will be done during that timeframe. But rest assured I have it in mind and will do it as soon as I have time 😊

**Comment by mikestopcontinues** [comment]
Moving countries at the moment, but I intend to work on this. It's still a valid request that I'd love to hear more feedback on.
