### ISSUE TITLE
[Obsidian] ... Menu Bar | Daily Notes Major Bug

### ISSUE THREAD

**Issue by Volconon** [raycast/extensions#3067]
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/e2c19dd992e84f89ce5ef011a7ed2b323b47bff0/extensions/obsidian/)
Author: @marcjulianschwarz

## Description
I have around 6/7 vaults in Obsidian.
Using the Beta menu bar item, I tried to create a daily note, but instead of opening the vault I'd selected, it opened the last one in the list.
As far as I can tell, it doesn't matter which one I try to create a daily note inside of. It'll open the last vault in the list every time...

No idea what exactly is happening here, but it might be reading some indexed variables incorrectly, or something along those lines.

The daily note command still functions correctly, so it's only from the menu bar that this bug is present.

## Steps To Reproduce

1. Activate Menu Bar Command.
2. Make sure to configure more than one vault for the Raycast command.
3. Open menu.
   - Select a vault above the bottom one.
5. Proceed to be wowed by the machines fore-knowledge of your needs, despite what you thought you needed.

## The Current Behavior
The last vault in the menu bar command will always be the one that gets opened by the Daily Notes option.

## The Expected Behavior
The vault selected will open when its Daily Note option is selected.

### Raycast version
Version: 1.40.1

**Comment by marcjulianschwarz** [comment]
Hi @Volconon,

I could reproduce this issue and it will be fixed with the next update which I will (hopefully) be able to release somewhere in the week of October 17th.
Added this bug report to the backlog of the [Roadmap](https://github.com/users/marcjulianschwarz/projects/1) as well.
