### ISSUE TITLE
[Obsidian] ... Menu Bar Command QOL suggestion

### ISSUE THREAD

**Issue by Volconon** [raycast/extensions#3068]
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/e2c19dd992e84f89ce5ef011a7ed2b323b47bff0/extensions/obsidian/)
Author: @marcjulianschwarz

**Describe the feature and the current behavior/state.**
In the menu bar command, all the vaults are currently displayed as a long list, which can become extremely long.
I think it'd be a good idea to merge all those menu's into sub-menus.

- **Have a menu for Daily Notes** that pops into a sub-menu where you select the desired vault.
- **Have a menu for Pinned Notes** that pops into a sub-menu that is separated by the names of each vault you've configured.
   - _This menu should only display vaults that contain a pinned note, and should state the lack of pinned notes otherwise._
- **Add a simple Open Vault Menu** that would function almost identically to the Daily Notes menu, but without the daily notes function.

---
**Who will benefit with this feature?**
I can't think of a single person that wouldn't benefit from this change; in fact, I think that this would only increase the usability of the menu when you start to accumulate vaults.

---
**Any Other info.**
I think that covers all the bases.

**Comment by marcjulianschwarz** [comment]
Hi @Volconon thank you for the suggestion. I agree that the menu bar needs an update.

I have added this issue to the backlog of the [Roadmap](https://github.com/users/marcjulianschwarz/projects/1).

**Comment by marcjulianschwarz** [comment]
Commenting to prevent automatic closing.

This issue is still being worked on.

**Comment by marcjulianschwarz** [comment]
Hi @Volconon, finally found some time to work on this. 

https://user-images.githubusercontent.com/67844154/205464716-45714bb8-d1af-453d-8566-9a7701cc6f9a.mov


---

> Have a menu for Pinned Notes that pops into a sub-menu that is separated by the names of each vault you've configured.
This menu should only display vaults that contain a pinned note, and should state the lack of pinned notes otherwise.

This would again lead to long list when a user has multiple vaults with lots of pinned notes in each of them, so I added another submenu for it.
