### ISSUE TITLE
[Extension Feature Request] TablePlus: show tag/env of the connection in the search results

### ISSUE THREAD

**Issue by eduardlleshi** [raycast/extensions#307]
Raycast version: 1.25.3

## Description
TablePlus "Search Databases" plugin returns the connection name only. This makes it very hard to distinguish connections based on their environment. I usually save the connections with the same name while the tag would be different on each (local/testing/development/staging/production).

TablePlus connections: 
![Image 2021-11-07 at 12 02 13](https://user-images.githubusercontent.com/6278258/140642367-32e8ada4-8a50-4000-bce6-7dd2ec874a2f.jpg)

TablePlus "Search Databases" plugin results for "Connection 1"
![Image 2021-11-07 at 12 03 49](https://user-images.githubusercontent.com/6278258/140642410-3a17fff0-37f2-4d20-8a6e-a0249d23799e.jpg)

## Steps To Reproduce

1. Create multiple connections with the same name but different tag (environments). Example Connection 1 [local], Connection 1 [testing], Connection 1 [production]
2. Search Connection 1 on the TablePlus Raycast extension.
3. The tag does not display. There will be three records of "Connection 1" with no info on which environment it is set up.

## The current behavior
TablePlus extension shows the connection name and a unique identifier.

## The expected behavior
TablePlus extension shows the connection name and tag. Bonus if the tag or name can be color coded based on the tag/env. 
I'm not sure if the unique identifier is useful, but I'm fine with it showing either way.

Tagging @pernielsentikaer for visibility.

**Comment by eduardlleshi** [comment]
The `bug` tag was auto-applied. I would not consider this a bug, but a feature request.

**Comment by pernielsentikaer** [comment]
Hi @eduardlleshi 👋 

I'm almost ready with the next version that will add groups/labels to, give me a day or two then it should be ready 👍 

As you can see was the first version was a bit messy, in the next version it should be a lot better :)

Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you want some previews.

**Comment by eduardlleshi** [comment]
Hi @pernielsentikaer. That's awesome! I'll be looking forward to the next update.

**Comment by pernielsentikaer** [comment]
Hi @eduardlleshi 👋 It's pushed, waiting for review #343

**Comment by pernielsentikaer** [comment]
Hi @eduardlleshi 👋 

You should now be able to use the update, let me know if everything is as expected

**Comment by eduardlleshi** [comment]
Looks great! Thanks @pernielsentikaer !
