### ISSUE TITLE
[Bear Notes] Opening note places cursor at end of note

### ISSUE THREAD

**Issue by apg-dev** [raycast/extensions#3072]
# Extension – [Bear Notes](https://github.com/raycast/extensions/tree/a8a11e9408170c13a2bf502d62bb38eeece15e77/extensions/bear/)
Author: @hmarr 

## Description
First let me say this is an incredibly helpful extension. Thank you for making it!

Bug: Searching for and then opening a Bear note (either in main or separate window) places the cursor at the end of the note (and scrolls the note to the end).

## Steps To Reproduce

1. Raycast: "Bear Search Notes" 
2. Select any note from list
3. Return or Cmd+Return
4. Bear note will open with cursor at end of note (and note scrolled to the end)

## The current behavior
Noted above.

## The expected behavior
Cursor is placed at the beginning of the first line after the h1 title. And note is not scrolled to the end.

### Raycast version
1.40.1

**Comment by hmarr** [comment]
I agree with this feedback – I also find this behaviour undesirable. However, it was added deliberately by a contributor, so it seems like some people want it. Additionally, there's no way of focusing the cursor at the top of the file, so we're stuck with a) open the note unfocused at the top of the file, or b) open the note focused but with the cursor placed at the end of the file.

As a compromise I made it configurable in https://github.com/raycast/extensions/pull/3085.

**Comment by apg-dev** [comment]
Thank you for the clarification. I think I’d still prefer the note at the top - even unfocused and presumably requiring a mouse-click to get focused - as many of my notes are quite long. So thank you for creating the option for that. How do I go about updating the extension on my end? And once again, much appreciation for this terrific plugin. It is superb! I have a couple feature suggestions that I’ll post in a separate ticket. Meantime, I'll go ahead and close this one with your patch.

**Comment by hmarr** [comment]
Yeah, I'd also prefer to open the note at the top even if it is unfocused - I'm going to leave the checkbox unchecked too.

To update, the easiest option is to wait for the Raycast team to merge the change, then you'll automatically get the update when it's published to the store!
