### ISSUE TITLE
[Extension Bug] JetBrains Toolbox: showing non-existing projects in the list, unable to open projects

### ISSUE THREAD

**Issue by eduardlleshi** [raycast/extensions#308]
## Extension – [JetBrains](https://github.com/raycast/extensions/tree/main/extensions/jetbrains)
**Author:** @gdsmith 

Raycast version: 1.25.3

## Description
The JetBrains Toolbox "Search Recent Projects" command is displaying results for directories that do not exist. I believe those directories were moved/renamed a few years ago. Searching the same project using JetBrains Toolbox generates expected results.

Another bug is whenever I try to open the project on the directory that exists it won't work. This is happening randomly. I can open a few projects, but can't open some. The PHPStorm window will bounce and not load the project. The selected result has the right directory. Can open them fine using PHPStorm or JetBrains Toolbox app.

JetBrains Toolbox results:
![Image 2021-11-07 at 12 11 43](https://user-images.githubusercontent.com/6278258/140642613-61150ba6-4197-4c78-b96a-84709cbf4a92.jpg)

JetBrains Toolbox Recent Projects Extension results:
![Image 2021-11-07 at 12 09 40](https://user-images.githubusercontent.com/6278258/140642642-8c78e588-d3b5-43aa-8e5d-4172068d7adc.jpg)

## Steps To Reproduce

1. Search for a project on Raycast using "JetBrains Toolbox Recent Projects".
2. Project is displayed multiple times.
3. Trying to open the right project on the existing directory will not do anything. PHPStorm will just bounce as if it can't find it.

## The current behavior
Shows project multiple times and sometimes projects cannot be opened.

## The expected behavior
Show only projects that exist on directories/JetBrains Toolbox and able to open projects everytime.

**Comment by mattisssa** [comment]
Hey @gdsmith ! 
🐞 Here is the bug report request to your extension, take a look at that and subscribe to don't miss anything related 😉

**Comment by gdsmith** [comment]
@eduardlleshi I'll split this into the two issues.

1) Not opening projects correctly

Can you check if you have the cli tools available, I added a fallback to try a protocol url (jetbrains://phpstorm/…) if the cli tools are not available, but those urls are not well implemented by JB and I have seen behaviour like you mentioned (the bouncing window). If you can supply the path to those projects it might shed some light on why that is failing.

2) Old projects showing up

JetBrains is pretty bad at clearing out config for old versions, it's likely that the extension is picking up config from an old PhpStorm project file. Can you check if they show up in the projects window of PhpStorm itself (File → Open Recent → Manage Projects…)? Can you check the output of:

```sh
/Users/george/Library/Application Support//JetBrains/PhpStorm2021.2/options/recentProjects.xml
```

If it's not in the projects window of PhpStorm then I think we will need to add a preference to only search the latest config.

@mattisssa thanks for the ping, I had missed this issue, I am subscribed, but only to participating and mentions as this repo is pretty noisy 😄.

**Comment by eduardlleshi** [comment]
@gdsmith thanks for getting back at this.

> 1. Not opening projects correctly
> 
> Can you check if you have the cli tools available, I added a fallback to try a protocol url (jetbrains://phpstorm/…) if the cli tools are not available, but those urls are not well implemented by JB and I have seen behaviour like you mentioned (the bouncing window). If you can supply the path to those projects it might shed some light on why that is failing.

I do have shell scripts enabled and the path being defined as `/usr/local/bin`



> 3\. Old projects showing up
> 
> JetBrains is pretty bad at clearing out config for old versions, it's likely that the extension is picking up config from an old PhpStorm project file. Can you check if they show up in the projects window of PhpStorm itself (File → Open Recent → Manage Projects…)? Can you check the output of:
> 
> ```shell
> find ~/Library/Application\ Support/JetBrains -name recentProjects.xml
> ```
> 
> If it's not in the projects window of PhpStorm then I think we will need to add a preference to only search the latest config.

File → Open Recent → Manage Projects… this shows the projects once.

I used the `Cleanup leftover tool directories...` option on JetBrains and deleted a lot of older versions of PHPStorm from JetBrains yesterday. I only kept the latest 2 versions (in case I want to roll back to a previous version). This probably removed old configs and now when I search for a project on Raycast it's only showing up once. I still cannot open the projects though (bouncy effect). Here's the output of that command: 

```
/Users/eduardlleshi/Library/Application Support/JetBrains/PhpStorm2021.2/options/recentProjects.xml
/Users/eduardlleshi/Library/Application Support/JetBrains/PhpStorm2021.1/options/recentProjects.xml
```

**Comment by gdsmith** [comment]
@eduardlleshi is it always the same project(s) that don't open? Can you give a full path to a project that fails? Does it work from the command line if you do e.g. `phpstorm /path/to/project`?

**Comment by eduardlleshi** [comment]
@gdsmith I found the problem. 

Somehow `/usr/local/bin/phpstorm` executable file was stored as `/usr/local/bin/phpstorm1` under the root user. I renamed it to `phpstorm` and gave permission to my user. I'm now able to open all projects from the Raycast JetBrains extension.

**Comment by gdsmith** [comment]
Great that this is working for you now. [I've made an update to the extension](https://github.com/raycast/extensions/pull/397) to hopefully make diagnosing these types of issues a little easier, added a readme to help troubleshooting and set it by default to not fall back on the protocol url. Hope that helps someone else with similar issues.
