### ISSUE TITLE
[Spotify Player] Menu Bar does not update correctly

### ISSUE THREAD

**Issue by Anhardty** [raycast/extensions#3083]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/3553095541474d8e97fa564fa94279a1f5d5fb07/extensions/spotify-player/)
Author: @mattisssa

## Description
When changing a track via the extension (or in Spotify), the menu bar status is not updated to the current track. Also, the menu bar status disappears after a minute, and even when restarting, it does not appear.  

## Steps To Reproduce

1. Start a track with "Just Play"
2. Start Menu Bar with "Menu Bar Player"
3. Change to another track with "Just Play" (or directly in Spotify)
4. Wait a few seconds (up to one minute) until the menu bar status disappears.

## The current behavior
The menu bar status does not show the current track status after the track changed, instead it disappears.

## The expected behavior
The menu bar status shows the current song correct after the track changed.

### Raycast version
Version: 1.40.1

### MacOS version
Version: Monterey 12.6

**Comment by daikaiyu** [comment]
Have you installed bartender 4?
I follow steps to reproduce ant reproduce successfully.But when I restarted bartender 4, it disappeared.
I still don't know why 😂.
