### ISSUE TITLE
[Bear Notes] Combine preview and backlinks into search pane

### ISSUE THREAD

**Issue by apg-dev** [raycast/extensions#3096]
# Extension – [Bear Notes](https://github.com/raycast/extensions/tree/a8a11e9408170c13a2bf502d62bb38eeece15e77/extensions/bear/)
Author: @hmarr 

For the preview note option, which is so helpful, is there any chance it could be moved up a level into the search note page, like this:

<img width="743" alt="raycast-preview" src="https://user-images.githubusercontent.com/55888411/193469953-cabdd0d2-a194-44a9-abb8-f101c7121adc.png">

Coupled with that, if there was a way to show the number of backlinks at the end of the note title, or even better would be if there was a backlinks panel below the preview in the image above - that would be incredible.

Use case: When searching for a Bear note, being able to see a mini preview and any backlinks would make navigating around connected notes so much easier. And given how slow the Bear 2.0 release seems to be taking, features like these would go a long way toward helping users.

Thank you for the consideration!

**Comment by hmarr** [comment]
This seems like a good improvement. I implemented it in https://github.com/raycast/extensions/pull/3651

**Comment by apg-dev** [comment]
> This seems like a good improvement. I implemented it in #3651

That is terrific - thank you!
