### ISSUE TITLE
[Microsoft Edge] unable to search bookmarks with Microsoft Edge extension 

### ISSUE THREAD

**Issue by 0xdeee** [raycast/extensions#3116]
# Extension – [Microsoft Edge](https://github.com/raycast/extensions/tree/efba3ec1978c17317a96bcdcaa914f9153839e04/extensions/microsoft-edge/)
Author:

## Description

unable to search for bookmarks in edge

## Steps To Reproduce

1. installed Microsoft Edge extension in raycast
2. tries searching for bookmarks in edge browser throught extension, but shows "An error occurred, Failed to show bookmarks"

## The current behavior

no bookmarks are showing up

### Raycast version
version 1.40.1

**Comment by KartikKumarSahoo** [comment]
Thanks @0xdeee for reporting the issue. And sorry for the delay in responding. This PR https://github.com/raycast/extensions/pull/7526 should fix the problem.
