### ISSUE TITLE
Spotify Track Search error

### ISSUE THREAD

**Issue by Sjmarf** [raycast/extensions#3118]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/3553095541474d8e97fa564fa94279a1f5d5fb07/extensions/spotify-player/*)

Author: @daikaiyu

## Description

When using the Search Track feature, I sometimes get the below error when trying to play a song.
```
Failed Start Playing
An error occurred while communicating with Spotify's Web API. 
Details: Restricted Device.
```

## Steps To Reproduce

1. Open the `Search Track` command.
2. Attempt to play a song. On my device, the error occurs more often than not.

### Raycast version

Version: 1.40.1

**Comment by daikaiyu** [comment]
Sorry, I am not a premium user. I can't reproduce this issue.
