### ISSUE TITLE
[Music] Add to library

### ISSUE THREAD

**Issue by lumargh** [raycast/extensions#3134]
# Extension – [Music](https://github.com/raycast/extensions/tree/a8a11e9408170c13a2bf502d62bb38eeece15e77/extensions/music/)
Author: @Rawnly

## Steps To Reproduce

1. Update Raycast and Extensions
2. Open command Add to Library, click Enter
3. Receive error (no effect in the Music app)

### Raycast version
Version: 1.40.2

**Comment by Rawnly** [comment]
Duplicate of  #2984

**Comment by lumargh** [comment]
My bad!
