### ISSUE TITLE
[YouTube] ...

### ISSUE THREAD

**Issue by Shochraos** [raycast/extensions#3135]
# Extension – [YouTube](https://github.com/raycast/extensions/tree/a8a11e9408170c13a2bf502d62bb38eeece15e77/extensions/youtube/)
Author: @tonka3000

## Description
Using the YouTube extension certain search queries can't be completed and an error message is displayed

## Error:
```
Error: Rendering failed:
The data couldn’t be read because it isn’t in the correct format.

    at runMicrotasks (<anonymous>)

```

## Steps To Reproduce

1. Use the "Search Videos" Command
2. Type "Enna Alouette"

## The current behavior
An error message is displayed

## The expected behavior
Search results are displayed
### Raycast version
Version: 1.40.3

**Comment by omarmiky2** [comment]
Can you give me apk youtube preimeam
