### ISSUE TITLE
Cannot find Client ID and Client Secret fields in Preferences > Extensions > Spotify :(

### ISSUE THREAD

**Issue by jakubsvec001** [raycast/extensions#3138]
# Extension – [Title](https://github.com/raycast/extensions/tree/main/extensions/*)

Author: @jakubsvec001

## Description
I cannot find the Spotify Extension 

## Steps To Reproduce

1. "Command" + "," > Spotify
2. Add Client ID and Client Secret

## The current behavior

I am expecting to add my Copy Client ID and Client Secret into the extension preferences

## The expected behavior

 The Client ID and Client Secret fields are not available under "command" + "," > Spotify :(

I am able to find such fields for other extensions under their respective app names in "Extensions"

### Raycast version

Version: 1.40.3

**Comment by ncastle** [comment]
This isn't a super helpful comment, but I just want to mention that I am also having this issue!

**Comment by ramirez** [comment]
I can't seem to find the preferences either.

**Comment by daikaiyu** [comment]
@jakubsvec001 @ncastle @ramirez 
Currently, Client ID and Client Secret cannot be added to preferences.The relevant content is hard encoded in the source code.
As a matter of fact, it is useless to add it.
