### ISSUE TITLE
Support Touch ID for Authy Extension

### ISSUE THREAD

**Issue by nicekiwi** [raycast/extensions#3139]
# Extension – [Authy](https://github.com/raycast/extensions/tree/ca17331bea29d1841de5738aae8b25b378ec0177/extensions/authy)

Author: @guga4ka 

**Describe the feature and the current behavior/state.**
Add a layer of security to accessing OTA codes, for instance the Authy iOS app supports touch ID, ideally add an option to required system login auth to show list of OTA codes after the command to open them is activated.

**Who will benefit from this feature?**
Anyone wanting to secure their OTA codes if workstation were breeched.

**Any Other info.**
https://www.electronjs.org/docs/latest/api/system-preferences#systempreferencesprompttouchidreason-macos

**Comment by guga4ka** [comment]
Raycast isn't an electron app, and currently doesn't support touchID. I thought several times about security aspects and the single option that I could imagine is _master password_ but it might be a bit rudimental to have a separate password for OTPS

**Comment by nicekiwi** [comment]
Yeah, I suspected as much, electron information was all I could find on V8 and Touch ID :( 

Authy app also supports a 4 number pin code, maybe that could work instead?

**Comment by dudido** [comment]
Whichever way you choose (TouchID, Pin Code, Master PW), I believe the extension needs some additional protection. Currently, the only option is to store the master pw permanently, which is quite insecure.

**Comment by nicekiwi** [comment]
> separate password. I will leave backup password as a preference of extension and user would be able to set up password he wants

Looking good, maybe easiest to restrict it to a 4 digit PIN code, as the iOS/Android apps do. 
Yes, do keep the backup password separate :)
