### ISSUE TITLE
[Wi-Fi] ...

### ISSUE THREAD

**Issue by Cerdix** [raycast/extensions#3164]
# Extension – [Wi-Fi](https://github.com/raycast/extensions/tree/a85a5f83e81211d31dac1d65f14362c40dfda4e3/extensions/wi-fi/)
Author: @koinzhang

**Using the computers existing knowledge of Wifi and Hotspot Passwords**

****Describe the feature and the current behavior/state.****

When ever I choose a Wi-Fi connection in the Raycast Scan Wi-Fi shortcut, it demands the password despite it being a Wi-Fi connection which the Computer already knows and has the password for. When I press connect through the control center on macOS Monterey, it connects without asking for the Password. 
      The Idea would be that when one presses enter or clicks on a already known Wi-Fi connection, it would grab the Password which is stored somewehre and enter it automatically. The process in the short cut window would look something like this:
      Select Wi-Fi, loading animation replaces or appears next to the wifi icon and animates. Once it connects, the loading icon disapears and the Wifi Icon turns green or animates from empty to full from bottom to top. 
      I know nothing of how computers connect to known networks, so you would implement this how you find it best work.

****Who will benefit with this feature?****

Well, people who want to use raycast instead of the control centre or other system windows? This is not important since the standar system process is really easy. 

Kindest Regards
Cedric Rhomberg

**Comment by koinzhang** [comment]
Hi @Cerdix Thank you for your advice.
But there are two problems at the moment, so there is no way to implement this feature for now.
1. I haven't found a good solution to get the Wifi password already stored in the local machine yet.
2. Although it is possible to get the wifi password via keychain, I haven't found a suitable node library to get the password yet.  And according to [Raycast official documentation](https://developers.raycast.com/basics/prepare-an-extension-for-store#keychain-access), access to the keychain extension will be denied
<img width="775" alt="image" src="https://user-images.githubusercontent.com/36128970/194755201-4643aa04-6b8f-4c45-9646-c546f191f2ed.png">

**Comment by HerrNiklasRaab** [comment]
@koinzhang have you reached out to the Raycast team, like describe in the documentation? This would be so helpful to have :)

**Comment by Cerdix** [comment]
HelloNo, sorry, I wasn't aware that I should contact them. Is this regarding the Wi-Fi extension? I can, but I have a very limited technical knowledge, and have no insight into any aspect of your application. It would be difficult for me to act as an intermediary due to attention needed as well as for the above stated reasons, and would recommend that somebody with insight and know-how would act in behalf of you, or ideally, you. If you still want me to ask on your behalf, despite despite what I have stated, what and how would I ask? Would I ask something along these lines?: (please do edit this to your liking)Dear Raycast teamI’m asking on the behalf of theThe developer ((insert name of developer)) for the extension ((insert name of extension)). It regards the access to Wi-Fi passwords stored inside the Mac Keychain app. The developer hasn’t found a workaround regarding this limitation, and would be interested in solving this problem, if possible.Kindest regardsCedric RhombergOn 14 Feb 2023, at 08:10, Niklas Raab ***@***.***> wrote:﻿
@koinzhang have you reached out to the Raycast team, like describe in the documentation? This would be so helpful to have :)

**Comment by HerrNiklasRaab** [comment]
The question was directed to @koinzhang :)

**Comment by Cerdix** [comment]
aaah i seeeeeeOn 14 Feb 2023, at 18:17, Niklas Raab ***@***.***> wrote:﻿
The question was directed to @koinzhang :)
