### ISSUE TITLE
[Search Browser Bookmarks] Add support to Arc Browser

### ISSUE THREAD

**Issue by matt08** [raycast/extensions#3166]
# Extension – Search Browser Bookmarks (not open source?)

Author: @pernielsentikaer

Add support for [Arc browser](https://thebrowser.company/) alongside Safari, Chrome, Firefox and Brave.

**Comment by matt08** [comment]
Any news? Plans?
Here is same feature request, but for another browser (Vivaldi): https://github.com/raycast/extensions/issues/2944

CC: @raycastbot @pernielsentikaer @mathieudutour @mathieudutour

**Comment by machielkreiken** [comment]
I too would really love an Arc integration!

**Comment by pernielsentikaer** [comment]
Hi 👋 

The current version is the `old Swift` version; as you may already know, we're porting all native Swift extensions to Open Source; when this happens it might be included in the initial version; if not, then it's easy to add it as a contributor 😊

**Comment by machielkreiken** [comment]
Hi @pernielsentikaer I already noticed Thomas's PR https://github.com/raycast/extensions/commit/6f6561eb4b60ab0d07495cacfb6ec5c63d3d299d

Glad to see support being added in the next release! Keep it up.

**Comment by machielkreiken** [comment]
:( No support to actually search your bookmarks yet?

**Comment by pernielsentikaer** [comment]
Not last time I checked 😊
