### ISSUE TITLE
feat req - library genesis - add option for default download location

### ISSUE THREAD

**Issue by erauner12** [raycast/extensions#3167]
# Extension –  [library genesis](https://github.com/raycast/extensions/tree/main/extensions/library-genesis/src)

Author: @yz3440 

add option for default download location:
- ex: `~/Downloads`

**Describe the feature and the current behavior/state.**

Currently, the plugin asks you where you want to download the file every time.

**Who will benefit from this feature?**

Users who do not need to put the file in a specific place each time

**Any Other info.**

**Comment by danielsequeira** [comment]
actually the author of this extension is: @yz3440 🙂

**Comment by pugson** [comment]
awesome, thank you @yz3440!
