### ISSUE TITLE
[SSH Connection Manager] ...

### ISSUE THREAD

**Issue by dannyneira** [raycast/extensions#3187]
# Extension – [SSH Connection Manager](https://github.com/raycast/extensions/tree/c6b6b827a9914aee69566380acddd541adb24780/extensions/ssh-manager/)
Author:

Please add the option to use the Warp terminal as the default for ssh connection. [warp.dev](https://www.warp.dev/)

**Describe the feature and the current behavior/state.**
Add the option in the extension settings dropdown.
![CleanShot 2022-10-10 at 17 12 14](https://user-images.githubusercontent.com/16809145/194965856-b8c6a7cf-8238-41ff-8393-32031bd31937.png)

**Who will benefit from this feature?**
The Warp Terminal user base.

**Any Other info.**

**Comment by AaronDavidSchneider** [comment]
Duplicate of #3165
