### ISSUE TITLE
[Asana] Failed to fetch latest data - status code 400

### ISSUE THREAD

**Issue by stanty522** [raycast/extensions#3188]
# Extension – [Asana](https://github.com/raycast/extensions/tree/a996484d2d3b4171bb7f5ef15356f6b0c13ca950/extensions/asana/)
Author: @thomaslombart

## Description
When creating a task an error is shown saying "Failed to fetch latest data". From a task creation POV the project field is not being auto populated. This does not prevent a task being created though, it just prevents the task created being put under a specific project.

## Steps To Reproduce

1. Create Task
2. See error

## The current behavior
When creating a task an error shows up that results in the Project field being blank even if a Project name is inputted manually, matching an existing project.

`20:48:34.221 The Form Item `assignee` is changing from an uncontrolled input to be controlled. This is likely caused by the value changing from `undefined` to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
20:48:35.595 [AxiosError: Request failed with status code 400] {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      Authorization: 'Bearer XXXXX',
      'User-Agent': 'axios/0.27.2'
    },
    baseURL: 'https://app.asana.com/api/1.0',
    url: '/projects',
    params: {
      workspace: '3829543799583',
      opt_fields: 'id,name,icon,color,custom_field_settings.custom_field'
    },
    method: 'get',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: <…>`

## The expected behavior
When creating a task the Project field should have auto complete letting the user categorise the task to be under a specific project.

### Raycast version
Version: 1.40.3

**Comment by thomaslombart** [comment]
Hey @stanty522, I wasn't able to reproduce the error you get. So, I shipped a small feature to improve the errors sent back by Asana in the following PR: https://github.com/raycast/extensions/pull/3217

While this does not fix your bug, it should allow to narrow down the scope of the bug.
