### ISSUE TITLE
[API Feature Request] Allow TextField types

### ISSUE THREAD

**Issue by lewisblackburn** [raycast/extensions#319]
**Describe the feature and the current behavior/state.**
I noticed when using the bitwarden extension, that the password is shown in plaintext. Would it be possible to allow for HTML input types in the TextFIeld component?

![Screenshot 2021-11-08 at 19 53 08](https://user-images.githubusercontent.com/51877955/140808635-b0ec8734-6d2c-46df-ab7b-1d23f8f0a397.png)

**Who will benefit with this feature?**

This will allow for:
![Screenshot 2021-11-08 at 19 56 39](https://user-images.githubusercontent.com/51877955/140809070-f99ae61a-7798-47b9-a184-55dd99e6544a.png)

**Comment by Yonben** [comment]
Agreed on that, in my case I'd love a number input :)

**Comment by fe9lix** [comment]
Shipped!
