### ISSUE TITLE
[Apple Notes] Full Text Search

### ISSUE THREAD

**Issue by hacdias** [raycast/extensions#3207]
# Extension – [Apple Notes](https://github.com/raycast/extensions/tree/ff2962d923ce14ec58885e84455de4905f063995/extensions/apple-notes/)
Author: @tumispro

It'd be nice to have full note search. This has been requested before: #1618

**Comment by hacdias** [comment]
Bump.

**Comment by AndreKucharzyk** [comment]
Hello! Anything happening with this one?

**Comment by tumispro** [comment]
@AndreKucharzyk @hacdias hey there! Do you have any suggestions on how that would work UI wise? Like should it search through the content of notes by default, or by using a specific action (an item in the bottom right corner menu)?

By default would be a little bit problematic, as I can imagine it would clutter current results. I am not sure if I can prioritise title in Raycast, I'd have to look into that.

**Comment by AndreKucharzyk** [comment]
@tumispro Hi friend, honestly I think the easiest answer would be to shamelessly copy the following solution - https://github.com/sballin/alfred-search-notes-app

**Comment by mcchang** [comment]
Interested in this one as well!
