### ISSUE TITLE
[Google Chrome] ...

### ISSUE THREAD

**Issue by imaloop** [raycast/extensions#3211]
# Extension – [Google Chrome](https://github.com/raycast/extensions/tree/efba3ec1978c17317a96bcdcaa914f9153839e04/extensions/google-chrome/)
Author: @rgomezcasas

## Error:
```
Error: ENOENT: no such file or directory, open '/Users/nick/Library/Application Support/Google/Chrome/Default/History'
```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.41.0

**Comment by satoshi-harashima** [comment]
Related
https://github.com/raycast/extensions/issues/2725
