### ISSUE TITLE
Menu status

### ISSUE THREAD

**Issue by rmbaad** [raycast/extensions#3212]
Hi there!
Thank you for the app and great developer experience!
I'm developing an extension for Raycast with menu bar functionality, and I wanted to add a feature, but I didn't find any event or state of a menu bar.

My case is to show some information from Gitlab, like how many merge requests you should review, and I wanted to add a "dismiss" feature not to highlight a menu icon until you get some changes (new merge request created), but I wanted to reset a "dismiss" status if a user opens a menu bar, and I don't know how to do it in a proper way. Maybe it would be nice to add something to get the menu bar status, maybe a hook like `const isMenuBarOpened = useMenuBarState()` or add an event for the `MenuBarExtra` component. Or maybe there is another way to check it.

Thank you!

**Comment by mathieudutour** [comment]
you can check the `environment.launchType` https://developers.raycast.com/api-reference/environment#launchtype to see when the user opens the menu bar
