### ISSUE TITLE
[Google Translate] ...

### ISSUE THREAD

**Issue by mvalezy** [raycast/extensions#3213]
# Extension – [Google Translate](https://github.com/raycast/extensions/tree/14eeb6aa236ead143b67da574df0187021aa730b/extensions/google-translate/)
Author: @gebeto

## Description
No translation output done.

## Steps To Reproduce

1. After installation, setup English > French as Languages
2. Ask to translate any work, like "house"
3. After typing starts, error messages replaces screen

![image](https://user-images.githubusercontent.com/2033647/195573758-8fecc0a1-8adf-49f2-a1bb-65f8fa59c7f7.png)

### Raycast version
Version: 1.40.3

**Comment by gebeto** [comment]
Looks good for me: <img width="769" alt="Screenshot 2022-10-13 at 16 13 39" src="https://user-images.githubusercontent.com/13422799/195606312-28195ae2-c728-4892-a049-60f88b45599c.png">

Maybe you have some internet connection issues? Can you open google translate in your browser?

**Comment by mvalezy** [comment]
Thanks for the quick response. Browser is fine.
I will try to check the certificate. This is the error I get so far.

Error: type mismatch at params.message : Expected to decode String but found a dictionary instead.
