### ISSUE TITLE
[Extension Bug]  Notion Database — no databases found by extension

### ISSUE THREAD

**Issue by aplssf** [raycast/extensions#322]
## Extension – [Notion](https://github.com/raycast/extensions/tree/main/extensions/notion)
**Author:** @HenriChabrand 
Raycast version: 1.25.3

## Description
@HenriChabrand this extension isn't seeing the databases that I've shared with it, via a personal integration.

When I open the extension, after sharing databases with the integration that I set up for this extension, the No Shared Content message is displayed.

## Steps To Reproduce

1. Create personal integration
2. Add access token and domain name for workspace to the extension's settings
3. Share databases with the integration
4. Open the extension via the 'Create Database Page' command
5. The 'No Shared Content' message is displayed

## The current behavior

See above

## The expected behavior

A list of databases that I can create pages in should be displayed.

**Comment by mattisssa** [comment]
Hey @HenriChabrand ! 
🐞 Here is the new bug report to your extension, take a look at that and subscribe to don't miss anything related 😉

**Comment by HenriChabrand** [comment]
Hello @mattisssa 👋 
We've discussed about it right after @aplssf had the issue – and managed to mitigate it.
It was because @aplssf had a lot of Database and Notion API can take a long time to respond in that case – but in the end does :)

**Comment by mattisssa** [comment]
@HenriChabrand @aplssf does it mean that we can close the issue? 🙃

**Comment by aplssf** [comment]
@mattisssa yes thanks
