### ISSUE TITLE
Support multiple installations/configurations of the same extension

### ISSUE THREAD

**Issue by EvansMatthew97** [raycast/extensions#3222]
# Extension – [All extensions](https://github.com/raycast/extensions/tree/main/extensions/*)

Author: @raycast

Support multiple installations/configurations of the same extension

Currently only allows a single installation or configuration per extension. Feature requested would allow the user to create multiple configurations for a single extension. The primary benefit is multi-account support out of the box for every extension.

Possible implementations:
1. Allow users to install the same extension twice, but must assign an alias for repeat installs
2. Allow multiple configurations for the same extension, request that the user choose a configuration each time they type the command (worse user experience than option 1)
3. Multiple Raycast "profiles" - largest change but possibly the largest benefit. The user can have profiles that are either isolated or inherit other profiles' configuration, and can switch between them using a command. This could affect the entire Raycast app config from colour scheme to which extensions are installed based and their configurations on the chosen profile.
Example use case is a "work" and "personal" profile, for BYOD and freelance developers.

This benefits all users who want to use multiple accounts with a single extension. Examples of users requesting multi-account support for different extensions:
- https://github.com/raycast/extensions/issues/305
- https://github.com/raycast/extensions/issues/1517
- https://github.com/raycast/extensions/issues/3057
- https://github.com/raycast/extensions/issues/2741

**Comment by weitzman** [comment]
This is a valid feature request. I dont much benefit in closing it as stale.
