### ISSUE TITLE
[Timers] ability to pause

### ISSUE THREAD

**Issue by wyrwigruz** [raycast/extensions#3226]
# Extension – [Timers](https://github.com/raycast/extensions/tree/d370a046747bdbac6385282a4c16b4b24dfb2b61/extensions/timers/)
Author: @ThatNerdSquared

It would be great if we could pause the timer :).

**Comment by ThatNerdSquared** [comment]
Hi @wyrwigruz, thanks for using Timers!

Great suggestion - I'll look into it 👍
