### ISSUE TITLE
New extensions PR naming convention

### ISSUE THREAD

**Issue by luknl** [raycast/extensions#3227]
I recently submitted an extension and wondered how I should name the PR. I took exemple on the other opened PRs for new extensions but I think there should be a template for naming them, that we can find in the docs or when creating the PR.
What do you think?

**Comment by luknl** [comment]
Any thoughts on that?

**Comment by mathieudutour** [comment]
We have a bot that will properly tag the PR if it's a new extension or a improvement to one (with its name) - that's what we use to quickly check them. I'm not sure we have to enforce a specific pattern, just write whatever is the most descriptive!
