### ISSUE TITLE
crash on query ip geolocation[IP Geolocation] ...

### ISSUE THREAD

**Issue by ParhamCreate** [raycast/extensions#3232]
# Extension – [IP Geolocation](https://github.com/raycast/extensions/tree/b4faed3d84d33cb66f90c0fa3d9d8c9e80c435e6/extensions/ip-geolocation/)
Author: @koinzhang

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.41.1

**Comment by koinzhang** [comment]
Hi @ParhamCreate This extension works fine for me now, may I ask what problems you are experiencing?
