### ISSUE TITLE
User can customize keybinding for actions

### ISSUE THREAD

**Issue by louishuyng** [raycast/extensions#3239]
**Describe the feature and the current behavior/state.**

**I used `cmd + K` as my legacy config for another mapping.** 

_I wonder do we support remapping the `cmd + K` action in raycast or if we should build a new feature to let users customize it._ 

It would be great if we can implement that feature or if you guys can give me some guidance so I can contribute to that.

**Will this change the current API? How?**

**Who will benefit from this feature?**
Mapping keys is quite essential and some user already has their old binding keys and don't want to change their old behavior. 

**Any Other info.**

**Comment by thomaspaulmann** [comment]
Thanks for raising this issue. This has popped up before. Right now, we don't have plans to allow re-mapping of the "standard shortcuts" for a few reasons:
- Complicates the keyboard handling logic in the app
- Hard to work with keyboard shortcuts that are defined by third party developers in their extensions
- Additional documentation efforts

We might pick this up at a later stage but I'm closing the issue for now.
