### ISSUE TITLE
[API Bug] arrowUp and arrowDown shortcuts do nothing

### ISSUE THREAD

**Issue by fuksman** [raycast/extensions#324]
Raycast version: 1.25.3

## Description
Using `arrowUp` or `arrowDown` as an only key in shortcut doesn't call linked action. Using any other key works fine. Checked only with `Detail` view.

## Steps To Reproduce

1. Use `shortcut={{ modifiers: [], key: "arrowUp" }}` in `ActionList.Item`
2. Run your extension
3. Click arrowUp on your keyboard

## The current behavior
Nothing happens

## The expected behavior
Clicking arrowUp calls the linked action

**Comment by fe9lix** [comment]
The up and down arrows in an action panel are used to navigate in the actions list up and down so they cannot be assigned as custom shortcut.
