### ISSUE TITLE
Figma File Search - Multiple Team Support

### ISSUE THREAD

**Issue by fyrebase** [raycast/extensions#3248]
# Extension – [Figma File Search](https://github.com/raycast/extensions/tree/4a5d8a3e4a789fbfafeadc9a538d9be62477ee1f/extensions/figma-files/)

Author: [@michaelwschultz](https://github.com/michaelwschultz)

**Describe the feature and the current behavior/state.**

The ability to search through multiple teams.

**Who will benefit with this feature?**

Figma users who work with multiple teams.

**Comment by Christopher-Hayes** [comment]
+1 this is a must for organization users.
