### ISSUE TITLE
[Salesforce Search] Option to exclude Reports & Dashboards

### ISSUE THREAD

**Issue by Mattyfaz** [raycast/extensions#3257]
# Extension – [Salesforce Search](https://github.com/raycast/extensions/tree/44bc89742780917741a181b3fc087c1a10ab4d70/extensions/salesforce-search/)
Store Link: https://www.raycast.com/sven/salesforce
Author: @svenwiegand 

 Firstly - I absolutely love this extension, it is much faster than searching within Salesforce itself.

**Describe the feature and the current behavior/state.**

Currently the extension will search Accounts, contacts, opportunities, **dashboards and reports** _(and custom object that are added)_.

Feature: In my case I don't need Dashboards & Reports, as such they clutter my search results. I would like an option to exclude searching for Reports & Dashboards. Perhaps add a checkbox toggle as part of the configuration where users can select/deselect which of the default objects they want searched?

**Who will benefit with this feature?**

Any users who don't need to search reports & dashboards _(or any other default object)_ but still want to search other Objects.

**Any Other info.**
N/A

Thank you for considering this :)

**Comment by svenwiegand** [comment]
Thanks for the suggestion @Mattyfaz. I now did what I should have done right from the beginning: I've split the one search command up into two: One for searching records (accounts, contacts, …) and one for searching dashboards and reports. This should fix your issue.

I've created pull request #3271 for this. As soon as it is merged, the new feature will be available.

**Comment by svenwiegand** [comment]
The pull request has been approved and the new version of the extension has been published.
