### ISSUE TITLE
[Obsidian] ...

### ISSUE THREAD

**Issue by JanPlr** [raycast/extensions#3261]
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/e2c19dd992e84f89ce5ef011a7ed2b323b47bff0/extensions/obsidian/)
Author: @marcjulianschwarz

## Description

The search note function of the obsidian extension does not work when I try to open it with a shortcut. It only allows me to search my notes when I TYPE "search ..." in the raycast window. But when I assign a shortcut to use this feature, it always gives me an error.

## Error:
```

```

## Steps To Reproduce

1. Assign shortcut to search function
2. Press shortcut
3. Get error

## The expected behavior

1. Assign shortcut
2. Press shortcut
3. Open search function in the correct behvaior, as what happens when I just type the "search" in the basic raycast window.

### Raycast version
Version: 1.41.1

**Comment by marcjulianschwarz** [comment]
Hi @JanPlr,

Thanks for bringing this problem to my attention. I however think that issue #3286 has some more details about it so I will continue the discussion there.
