### ISSUE TITLE
[Parallels Virtual Machines] Does not list all my VM's, nor launch them

### ISSUE THREAD

**Issue by aubreypwd** [raycast/extensions#3263]
# Extension – [Parallels Virtual Machines](https://github.com/raycast/extensions/tree/3437a6aab2ecbc7b50ea1ee5e7a81841bb74a241/extensions/parallels-virtual-machines/)
Author: @danpalmer

## Description

1. Does not list all VM's I have setup
2. Does not launch

## Steps To Reproduce

https://user-images.githubusercontent.com/1753298/196231524-2251d109-c7cf-4f6a-8b29-00c9fb843aae.mp4

## The current behavior

1. Does not list all VM's I have setup
2. Does not launch

## The expected behavior

1. Lists all my (2) VM's
2. Launches the one I select

### Raycast version
Version: 1.41.1

**Comment by danpalmer** [comment]
Hi @aubreypwd, thanks for raising this. Could you possibly confirm a few things to help me debug it?

- Are you definitely using Parallels Desktop Pro, and not the regular version? I've got Pro, and I know some things are scoped to just that, but I wasn't able to fully test so it's possible this is why it's partially working.
- Could you grab me the output from running: `/usr/local/bin/prlctl list --all --full --json --info` in your Terminal. Feel free to blank out anything that looks sensitive, but it should generally be safe to share. You can also email it to me directly if you'd rather not post it here. I suspect the reason for macOS missing is that I didn't test with a macOS VM, and some data isn't parsing correctly.

If you need any help doing any of this let me know. Thanks!

**Comment by aubreypwd** [comment]
> Are you definitely using Parallels Desktop Pro

<img width="800" alt="image" src="https://user-images.githubusercontent.com/1753298/196236459-8a44f7e2-ba21-462c-b83b-282490a84c41.png">

> Could you grab me the output from running

[3263.json.zip](https://github.com/raycast/extensions/files/9802860/3263.json.zip)

**Comment by aubreypwd** [comment]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/1753298/196729390-cd7d3be5-9363-49bb-be59-8e484f13da08.png">

```bash
❯ prlctl start "Windows 11"
The command is available only in Parallels Desktop for Mac Pro or Business Edition.
```

**Comment by danpalmer** [comment]
Thanks!

I'm going to improve the error messages for this case. 

Also thanks for the info for deciding the MacOS VM support. I'll get on that. 

Short this isn't a better answer. I'm going to have a quick look into using AppleScript instead of prlctl to get around this, but I'm not hopeful.

**Comment by danpalmer** [comment]
@aubreypwd I've finally had some time to look at the data you provided for me, and your macOS virtual machine is not listed in the output from `prlctl`. Did you definitely pass `--all` to the command when you ran it? If not some VMs are sometimes excluded.

If you did... can you think of anything else about your macOS VM that might cause it to not show up? Have you got any security settings enabled on the VM that could cause it to not show up?

Thanks for your continued help on this.

**Comment by aubreypwd** [comment]
```
❯ /usr/local/bin/prlctl list --all --full --json --info
[
	{
		"ID": "1d364a88-b70e-4b55-a2a0-507afe78c9ad",
		"Name": "Windows 11",
		"Description": "",
		"Type": "VM",
		"State": "suspended",
		"OS": "win-11",
		"Template": "no",
		"Uptime": "33841",
		"Home path": "\/Users\/aubreypwd\/Parallels\/Windows 11.pvm\/config.pvs",
		"Home": "\/Users\/aubreypwd\/Parallels\/Windows 11.pvm\/",
		"GuestTools": {
			"state": "possibly_installed",
			"version": "17.1.4-51567"
		},
		"Mouse and Keyboard": {
			"Smart mouse optimized for games": "auto",
			"Sticky mouse": "off",
			"Smooth scrolling": "on",
			"Keyboard optimization mode": "auto"
		},
		"Print Management": {
			"Synchronize with host printers": "on",
			"Synchronize default printer": "on",
			"Show host printer UI": "off"
		},
		"USB and Bluetooth": {
			"Automatic sharing cameras": "on",
			"Automatic sharing bluetooth": "off",
			"Automatic sharing smart cards": "off",
			"Support USB 3.0": "on"
		},
		"Startup and Shutdown": {
			"Autostart": "off",
			"Autostart delay": 0,
			"Autostop": "suspend",
			"Startup view": "same",
			"On shutdown": "close",
			"On window close": "suspend",
			"Pause idle": "on",
			"Undo disks": "off"
		},
		"Optimization": {
			"Faster virtual machine": "on",
			"Hypervisor type": "apple",
			"Adaptive hypervisor": "on",
			"Disabled Windows logo": "on",
			"Auto compress virtual disks": "off",
			"Nested virtualization": "off",
			"PMU virtualization": "off",
			"Longer battery life": "on",
			"Show battery status": "on",
			"Resource quota": "low"
		},
		"Travel mode": {
			"Enter condition": "battery-always",
			"Enter threshold": 30,
			"Quit condition": "power-connected"
		},
		"Security": {
			"Encrypted": "no",
			"TPM enabled": "yes",
			"TPM type": "crb",
			"Custom password protection": "off",
			"Configuration is locked": "off",
			"Protected": "no",
			"Archived": "no"
		},
		"Smart Guard": {
			"enabled": false
		},
		"Modality": {
			"Opacity (percentage)": 50,
			"Stay on top": "on",
			"Show on all spaces ": "on",
			"Capture mouse clicks": "on"
		},
		"Fullscreen": {
			"Use all displays": "off",
			"Activate spaces on click": "on",
			"Optimize for games": "off",
			"Gamma control": "on",
			"Scale view mode": "auto"
		},
		"Coherence": {
			"Show Windows systray in Mac menu": "off",
			"Auto-switch to full screen": "on",
			"Disable aero": "off",
			"Hide minimized windows": "off"
		},
		"Time Synchronization": {
			"enabled": true,
			"Smart mode": "off",
			"Interval (in seconds)": 60,
			"Timezone synchronization disabled": "off"
		},
		"Expiration": {
			"enabled": false
		},
		"Boot order": "hdd0 cdrom0 usb ",
		"BIOS type": "efi-arm64",
		"EFI Secure boot": "on",
		"Allow select boot device": "off",
		"External boot device": "",
		"SMBIOS settings": {
			"BIOS Version": "",
			"System serial number": "",
			"Board Manufacturer": ""
		},
		"Hardware": {
			"cpu": {
				"cpus": 4,
				"auto": "on",
				"VT-x": true,
				"hotplug": false,
				"accl": "high",
				"mode": "64",
				"type": "arm"
			},
			"memory": {
				"size": "6144Mb",
				"auto": "on",
				"hotplug": false
			},
			"video": {
				"adapter-type": "parallels",
				"size": "0Mb",
				"3d-acceleration": "highest",
				"vertical-sync": "on",
				"high-resolution": "on",
				"high-resolution-in-guest": "on",
				"native-scaling-in-guest": "off",
				"automatic-video-memory": "on"
			},
			"memory_quota": {
				"auto": "yes"
			},
			"hdd0": {
				"enabled": true,
				"port": "sata:0",
				"image": "\/Users\/aubreypwd\/Parallels\/Windows 11.pvm\/harddisk.hdd",
				"type": "expanded",
				"size": "262144Mb",
				"online-compact": "on"
			},
			"cdrom0": {
				"enabled": true,
				"port": "sata:1",
				"image": "\/Users\/aubreypwd\/Downloads\/22000.318.211104-1236.co_release_svc_refresh_CLIENTCONSUMER_RET_A64FRE_en-us.iso",
				"state": "disconnected"
			},
			"usb": {
				"enabled": true
			},
			"net0": {
				"enabled": true,
				"type": "shared",
				"mac": "001C424C4E54",
				"card": "virtio",
				"preventpromisc": "on",
				"mac_filter": "on",
				"ip_filter": "on",
				"nameservers": "",
				"searchdomains": ""
			},
			"sound0": {
				"enabled": true,
				"output": "Default",
				"mixer": "Default"
			}
		},
		"Host Shared Folders": {
			"enabled": true
		},
		"Host defined sharing": "All host disks",
		"Guest Shared Folders": {
			"enabled": false
		},
		"Shared Profile": {
			"enabled": true,
			"Use desktop": "off",
			"Use documents": "off",
			"Use pictures": "off",
			"Use music": "off",
			"Use movies": "off",
			"Use downloads": "off"
		},
		"Shared Applications": {
			"enabled": true,
			"Host-to-guest apps sharing": "off",
			"Guest-to-host apps sharing": "off",
			"Show guest apps folder in Dock": "off",
			"Show guest notifications": "on",
			"Bounce dock icon when app flashes": "on"
		},
		"SmartMount": {
			"enabled": true,
			"Removable drives": "on",
			"CD/DVD drives": "on",
			"Network shares": "on"
		},
		"Miscellaneous Sharing": {
			"Shared clipboard": "on",
			"Shared cloud": "on"
		},
		"Advanced": {
			"VM hostname synchronization": "off",
			"Public SSH keys synchronization": "off",
			"Show developer tools": "off",
			"Swipe from edges": "off",
			"Share host location": "on"
		}
	}
]
```

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/1753298/199034208-793e9802-2757-4454-81c5-596c6750fa11.png">

I'm sure I did. Here it is again.

As for settings, I'm not sure, but here are my settings to review:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/1753298/199034394-9d8e15bd-b527-4132-add9-32e9c89b476f.png">

<img width="748" alt="image" src="https://user-images.githubusercontent.com/1753298/199034442-6954120b-6b90-4db5-aa8e-0e54bf6fdded.png">

<img width="732" alt="image" src="https://user-images.githubusercontent.com/1753298/199034604-879a12cc-a740-42aa-8b55-7c2b6a569288.png">

I don't see anything that would restrict anything. I have disabled the whole Mac sharing/integration with Windows/etc.

**Comment by danpalmer** [comment]
Hm. That's a real pain. I can't see any reason why your VM wouldn't show up in the output there, but without it showing up there's not much the extension can do.
