### ISSUE TITLE
Shell: Failed to transferred command from Raycast to Terminal

### ISSUE THREAD

**Issue by wakaohhzeh** [raycast/extensions#3272]
# Extension – [Shell](https://www.raycast.com/asubbotin/shell)

Author: @KELiON 

## Description
When I type a command on Raycast and I wish Raycast will open a Terminal windows with that command I typed. Some times it works but some times it doesn't.
## Steps To Reproduce

1. Check open with Terminal/iTerm in the extension preference
2. Type a command, eg. cd ./Desktop
3. Type other command, eg. cd ./Downloads 

## The current behavior
Raycast open an empty Terminal window

## The expected behavior
Raycast has to open a Terminal windows it a command

### Raycast version

Version: 1.41.1

**Comment by KELiON** [comment]
@wakaohhzeh can you please attach a screenrecording?
