### ISSUE TITLE
[Gitmoji Search] Use API instead of dependency

### ISSUE THREAD

**Issue by carloscuesta** [raycast/extensions#3301]
# Extension – [Gitmoji Search](https://www.raycast.com/ricoberger/gitmoji)

## Author

@ricoberger 

### Describe the feature and the current behavior/state

Hey! 👋🏼 

Raycast user and fan here 😍 

I saw there was a `Gitmoji Search` extension on Raycast Store, but recently saw the extension is using the `gitmojis` package published on the registry.

https://github.com/raycast/extensions/blob/70da3c740f2751eb560c599fb44cd33bf3c464c1/extensions/gitmoji/src/gitmoji.tsx#L2

The downside of this approach is that a new version of the extension needs to be published every time a new gitmoji is added. In the gitmoji website we have a simple API endpoint that provides all the emojis! 🎉 

👉🏼 https://gitmoji.dev/api/gitmojis

### Who will benefit from this feature?

Everyone!

- Users: Will have the latest version of gitmoji available anytime
- Maintainers: Won't have to publish a new release of the extension anymore

**Comment by ricoberger** [comment]
HI @carloscuesta, I created a PR for this #3647, so that the extension tries to use the API and only falls back to the NPM package when the API call fails.

**Comment by carloscuesta** [comment]
Thank you for taking care of it! @ricoberger 🙏🏼
