### ISSUE TITLE
GitLab: Allow quick access to some predefined repository

### ISSUE THREAD

**Issue by CharlesB2** [raycast/extensions#3309]
# Extension – [GitLab](https://github.com/raycast/extensions/tree/main/extensions/gitlab)

Author: @tonka3000 

**Describe the feature and the current behavior/state.**

Currently to access a repo's section, I need to do "Search Project", type some letters, select. As I'm always interacting with the same repo, it would be much quicker to have a way to access this repo directly, and assign it a hotkey. 

**Who will benefit from this feature?**

Anyone who's always interacting with the same 1 or 2 repositories

**Comment by tonka3000** [comment]
Hi @CharlesB2 ,

Did you already tried the **Starred Projects** command? If the project is Starred on you GitLab account (via the star next to the project) it will be listed there. Then you can use CMD + 1 or CMD + 2 to access the repo.
This should work for your described use-case.

I'm not aware that it is possible now to have a top-level hotkey which is set dynamicly by an extension. Is there already a way @pernielsentikaer ?

Greetings
Michael

**Comment by CharlesB2** [comment]
Thanks @tonka3000, indeed, using starred projects is much quicker.

**Comment by pernielsentikaer** [comment]
No that's not possible @tonka3000 as far as I know 😊
