### ISSUE TITLE
[LINEAR]: Raycast Status stuck on "Installing extension" forever

### ISSUE THREAD

**Issue by EFF** [raycast/extensions#3311]
**Extension**: [Linear](https://github.com/raycast/extensions/tree/main/extensions/linear)
**Author** @thomaslombart

## Description
I just installed linear extension and even though the extension is properly installed (I can successfully create, list, update, delete issues). I don't recall having the same issue installing other extensions so far, I'll update this issue if I experience it with another extension.

This issue is **non-blocking** for me but it bugged me a little.

## Steps To Reproduce

1. Install linear ext
2. status stays _installing_ for ever

**ScreenCaps**:
![Screen Shot 2022-10-24 at 10 57 13 AM](https://user-images.githubusercontent.com/955524/197557993-88a375f3-ea10-4528-81de-dcfb86a9f247.png)
![Screen Shot 2022-10-24 at 10 51 47 AM](https://user-images.githubusercontent.com/955524/197558163-9a8242ce-3ef3-40b4-badf-358e64c3a575.png)

**Comment by thomaspaulmann** [comment]
Mmh... Were you able to reproduce this issue with other extensions as well?

**Comment by EFF** [comment]
I just installed 3 other extensions just to validate and I can confirm this issue **only** happened with Linear so far

**Comment by thomaspaulmann** [comment]
Mmh okay... So far we weren't able to reproduce it. There shouldn't be something specific to the Linear extension. I'll close it for now. If it reappears for other users, we'll investigate further.
