### ISSUE TITLE
[GIF Search] Add next page to gif search results.

### ISSUE THREAD

**Issue by khalido** [raycast/extensions#3314]
# Extension – [GIF Search](https://github.com/raycast/extensions/tree/cf8ba2cb37e703024a506584bc1f853a2de3c16c/extensions/gif-search/)
Author: @josephschmitt

Idea: Add a next page to the search results. Press next to return the next N search results.

**Describe the feature and the current behavior/state.**

Currently it displays the first N results (as configured in settings). If I don't like those, I have to do a new search. I'd like to be able to click next and it grabs the next N gif results.

**Who will benefit with this feature?**

Everyone! Sometimes you need to hunt down the right gif, and the first N isn't enough to choose from.

**Any Other info.**

**Comment by josephschmitt** [comment]
This is a great idea! I've asked the Raycast devs if they plan to support pagination natively in Raycast and I think they know about it. As soon as this feature is rolled out I'll definitely put it into the extension. Shouldn't be hard to add!
