### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by erngpawat** [raycast/extensions#3315]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/7d4e10b8f77c0617c32fb8483607329585e7365f/extensions/spotify-player/)
Author: @mattisssa

## Steps To Reproduce

1. Open Raycast
2. Search for Menu Bar Player
3. Hit enter.=

## The current behavior
Menu bar player not popping up.

## The expected behavior
Menu bar player should be popping up.

### Raycast version
Version: 1.41.1

**Comment by FlintMayers** [comment]
It was working until I updated to Ventura
