### ISSUE TITLE
[Recents] ...

### ISSUE THREAD

**Issue by tawassal** [raycast/extensions#3317]
# Extension – [Recents](https://github.com/raycast/extensions/tree/f55c8db8d61ec161cefd89d5aed3f9ad56bf1fa4/extensions/recents/)
Author: @GastroGeek

## Description
Recent documents not working, the other commands are e,g. recent apps, folders, etc

## Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

```

## Steps To Reproduce

1. type recent in raycast
2. select recent documents command, press enter

<img width="743" alt="Screenshot 2022-10-25 at 22 29 51" src="https://user-images.githubusercontent.com/115427635/197885810-df10d8e8-2b65-4c1c-a623-9b2617acb5ea.png">

## The current behavior
As image above

## The expected behavior
Assuming it shows a list of recent documents
### Raycast version
Version: 1.41.1

**Comment by GastroGeek** [comment]
@tawassal incoming fix. If you still see it, simply drop the new `limit` preference down to a more suitable level (defaults to 1000 which should be OK but just in case)...

**Comment by tawassal** [comment]
its working! Thank you!
________________________________
