### ISSUE TITLE
[API Bug] Detail tag isn't showing the loading indicator animation

### ISSUE THREAD

**Issue by unnamedd** [raycast/extensions#332]
Raycast version: 1.25.3

## Description

When we are using the tag `<Detail />` to present text content and make use of the prop `isLoading`, the view is not presenting the loading animator indicator like it is being presented when we are using the tag `<List />`.

## Steps To Reproduce

1. Create a screen which renders a `<Detail />` tag and add a prop `isLoading`, i.e:
```html
<Detail isLoading={ true } markdown="Small content" />
```

## The current behavior

![CleanShot 2021-11-10 at 19 14 33](https://user-images.githubusercontent.com/83694/141170631-50bc3a4c-955a-4984-9180-22c9dadb3df9.png)

## The expected behavior

![CleanShot 2021-11-10 at 19 13 44](https://user-images.githubusercontent.com/83694/141170663-14ee59a9-13f8-4660-821c-6ff5385b396a.png)

**Comment by fe9lix** [comment]
Hey @unnamedd, I can only reproduce this when I use the Detail component in a navigation stack, i.e. when the Detail view gets pushed, the isLoading property doesn't seem to be respected. When used standalone, outside of a navigation stack, it works as expected. Can you confirm this?

**Comment by unnamedd** [comment]
Yes @fe9lix, it is confirmed. In a navigation stack it is not working, but in a standalone mode it is showing the loading animation. Here a small gif to confirm that:
![CleanShot 2021-11-11 at 10 09 48](https://user-images.githubusercontent.com/83694/141270542-1d4a2c2d-2759-4532-9857-10a92fc41da3.gif)

**Comment by unnamedd** [comment]
The fix for this issue was released in the version 1.25.4, therefore I'm closing this issue.
