### ISSUE TITLE
[Asana] ...

### ISSUE THREAD

**Issue by tomasruta** [raycast/extensions#3321]
Every time I create a new task I have to change who it is assigned to. It always defaults to Unassigned. Before I was able to keep it assigned to Tomas Ruta

# Extension – [Asana](https://github.com/raycast/extensions/tree/77cc13418b6cbfcf2e848ab5293aa0b02293d1ae/extensions/asana/)
Author: @thomaslombart

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.41.1

**Comment by pernielsentikaer** [comment]
CC @thomaslombart - can you check this

**Comment by tomasruta** [comment]
Awesome!!

[image: image.png]

**Comment by tomasruta** [comment]
Hi, just checking in

**Comment by tomasruta** [comment]
Ah, okay, I've now manually updated the extension in Raycast and now it
does work..

But I didn't know that I should update it..

**Comment by pernielsentikaer** [comment]
Everybody with the extension gets the update within 4 hours, but you can force an update with the command `Check For Extensions Updates`
