### ISSUE TITLE
[Spotify Player] Menu bar not showing up 

### ISSUE THREAD

**Issue by itslexii** [raycast/extensions#3324]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/7d4e10b8f77c0617c32fb8483607329585e7365f/extensions/spotify-player/)
Author: @mattisssa

Menu bar isnt showing up 

1. Refresh menu bar

Menu bar not showing up

Expect it to show up
### Raycast version
Version: 1.42.0

**Comment by cm3cm** [comment]
Also having this issue!

**Comment by thomaspaulmann** [comment]
It only shows up if a song plays. Also do you have enough space in your menu bar? Apple hides some menu bar icons if it's getting too long.

**Comment by zhuang-jia-xu** [comment]
Same here. The menubar item seems to be rendering for like 0.5 second and then it disappears.

**Comment by theinterned** [comment]
I've been experiencing this as well for the past week or two. I tried to completely quit Raycast and even restart my machine. Other menu bar extensions are loading but the Spotify Now playing menu bar is not. 

I also noticed that the "Now Playing" item in the Raycast menu is not updating: even when I trigger it's "Refresh" command.

**Comment by zhuang-jia-xu** [comment]
I just tested out the code in development mode. The problem seems to be related to the AppleScript that should get current track from the Spotify app. Unfortunately I don’t know much about AppleScript so that’s all I can say for now.
