### ISSUE TITLE
[Elgato Key Light] ...

### ISSUE THREAD

**Issue by qor72** [raycast/extensions#3326]
# Extension – [Elgato Key Light](https://github.com/raycast/extensions/tree/4479d612107d01bc93466c2ce7049e8b6fa79bfe/extensions/elgato-key-light/)
Author: thomas

## Description
After the most recent Raycast update, the Elgato extension fails to toggle the key light. When you run the `Toggle On/Off` action the following error is reported: `Toggling Key Light Failed`. I have confirmed the light is on the network, available, and toggleable through the native control center. I have also rebooted the light and restarted raycast.

## Environment
- Elgato Control Center 1.3 (10415)
- Raycast 1.42.1

## Steps To Reproduce

1. Install Elgato Extension
2. Start Raycast, select the `Toggle On/Off` action for the Elgato key light

### Raycast version
- Raycast 1.42.1

**Comment by glortho** [comment]
+1 I have the same issue

**Comment by thewinger** [comment]
I also have this issue

**Comment by cmer** [comment]
Same here.

**Comment by then3rdman** [comment]
Yeh extention is currently broken

**Comment by qor72** [comment]
This is still a problem that needs fixing.
