### ISSUE TITLE
[Spotify Controls] ...

### ISSUE THREAD

**Issue by tawassal** [raycast/extensions#3328]
# Extension – [Spotify Controls](https://github.com/raycast/extensions/tree/b5dcca423f2322d1dddc6b75d6b516b0a32564d1/extensions/spotify-controls/)
Author: @thomaspaulmann

 Please could it be possible to add a play liked songs songs command

**Describe the feature and the current behavior/state.** 

Will play the first song from liked songs onwards e.g. from most recently added to oldest

**Who will benefit with this feature?**

Everyone who has liked songs on spotify, I do not make playlists and prefer to just like a song and have it in liked songs

**Any Other info.**

**Comment by thomaspaulmann** [comment]
This sounds more like something for the [Spotify Player extension](https://www.raycast.com/mattisssa/spotify-player). Could be a nice command to just play your liked songs.

**Comment by thomaspaulmann** [comment]
@mattisssa maybe you want to add this command?

**Comment by thomaspaulmann** [comment]
Looks like this issue is duplicated in #3329

**Comment by mattisssa** [comment]
> @mattisssa maybe you want to add this command?

Unfortunately don't have time for the extension development ATM, maybe someone will tackle the one before me 🙌

**Comment by egemenu** [comment]
For implementing this feature we need to extend the scope, but I couldn't find any way to extend it. I get error as `Insufficient client scope`. And when I extend the scope, I'm getting error as `Illegal scope` on authorisation step.

Would love to contribute but couldn't go to next step.
