### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by collinbell** [raycast/extensions#3340]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/7d4e10b8f77c0617c32fb8483607329585e7365f/extensions/spotify-player/)
Author: @mattisssa

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.42.1

**Comment by pernielsentikaer** [comment]
There is no content here?

The issue might be fixed with #3343
