### ISSUE TITLE
[Quit Applications] Add app icons

### ISSUE THREAD

**Issue by StevenLi-DS** [raycast/extensions#3346]
# Extension – [Quit Applications](https://github.com/raycast/extensions/tree/076a0f0871c330d098231107066efd49ada4add7/extensions/quit-applications/)
Author: @mackopes 

**Describe the feature and the current behavior/state.**

Could you please consider adding app icons so that it is easier for users to locate the app they want to quit.

**Who will benefit with this feature?**

**Any Other info.**

**Comment by mackopes** [comment]
Hi @StevenLi-DS,

Thanks a lot for the suggestion! I definitely plan to do this one day. I will try my best to prioritise it soon!
