### ISSUE TITLE
[Linear] Search project in all teams

### ISSUE THREAD

**Issue by CharlesB2** [raycast/extensions#3347]
# Extension – [Linear](https://github.com/raycast/extensions/tree/e4d119ad3b2e1aaf676341d4f99fb64d331a1147/extensions/linear/)
Author: @thomaslombart 

## Description

Projects are searched only in the team selected in the upper left dropdown, but that's not very handy (sometimes I don't remember which team I should mention)

## Steps To Reproduce

1. Hit the "Search projects" Linear command

## The current behavior

Must select the team

## The expected behavior

Provide a way to search in all teams

### Raycast version

1.42.1

**Comment by thomaslombart** [comment]
After taking a look at the issue, it seems we'd need an `All teams` option in the search bar dropdown:

![CleanShot 2022-11-17 at 16 59 42@2x](https://user-images.githubusercontent.com/16003285/202495921-73bffe10-641a-4fe7-81df-946e5b57744d.png)

This would be the default option.

**Comment by CharlesB2** [comment]
This is awesome, thank you guys!
