### ISSUE TITLE
[Set Audio Device] Set Output Device to Favorite stopped working in macOS Ventura

### ISSUE THREAD

**Issue by derick-bai** [raycast/extensions#3349]
# Extension – [Set Audio Device](https://github.com/raycast/extensions/tree/9705ba94af72208cff790222ee3ce28e02231825/extensions/audio-device/)
Author:

## Description
The "Set Output Device to Favorite" command stopped working after upgraded to macOS Ventura.

## Steps To Reproduce
1. Copy the device name (in this case, my AirPods pro) to clipboard via the "Set Output Device" command.
2. Configure the "Set Audio Device" extension. Paste the device name to the "Favorite Output Device" input box.
3. Run the "Set Output Device to Favorite" command.

## The current behavior
Got the error "Favorite output audio device could not be set".

## The expected behavior
The output audio device is set to the favorite I configured earlier.

### Raycast version
1.42.1

**Comment by avj73** [comment]
Same problem for me.
