### ISSUE TITLE
Add currently focused Chromium URL to drafts with optional title text

### ISSUE THREAD

**Issue by erauner12** [raycast/extensions#3351]
# Extension – [Drafts](https://github.com/raycast/extensions/tree/main/extensions/drafts)

Author: @FlohGro-dev 

**Describe the feature and the current behavior/state.**

Feature does not exist yet. Similar to: `Create Draft From Clipboard` command

I'm wondering has access to chromium. I wanted to see if it was possible to pull in the currently focused tab/window into the clipboard from raycast before sending the contents.

The feature I am requesting would do just that.

I think it would also be really nice to have an optional text box prompt to ask why you are saving this url. And if one is provided, it can become the title of the draft. Else, the url becomes the only text added to the draft.

**Who will benefit from this feature?**

People who want to store a specific url and why they wanted to revisit it.

**Any Other info.**

**Comment by FlohGro-dev** [comment]
Maybe you can accomplish what you want with Shortcuts? 
Seems to be easier then building that into a plug-in?

**Comment by erauner12** [comment]
I'll give it a shot! Will open this back up if I cannot find a reasonable solution. Thanks for checking
