### ISSUE TITLE
[Devdocs] Default language

### ISSUE THREAD

**Issue by erauner12** [raycast/extensions#3352]
# Extension – [Devdocs](https://github.com/raycast/extensions/tree/a791432e9373e6988af9afa5509a5d3aedead156/extensions/devdocs/)
Author: @pomdtr

**Describe the feature and the current behavior/state.**

Always starts on React. I'd like it to be able to always start on python 3.7 for example without having to select it everytime.

**Who will benefit with this feature?**

Anyone who uses a specific language in their job.

**Any Other info.**

**Comment by patrickfatrick** [comment]
I think an even better feature implementation would be the ability to create aliases to go straight to whatever documentation you want. eg ddr -> devdocs react, ddjs -> devdocs javascript, ddp -> devdocs python.

**Comment by pomdtr** [comment]
This is still relevant.
