### ISSUE TITLE
Clipboard Editor - Open in App Action

### ISSUE THREAD

**Issue by erauner12** [raycast/extensions#3353]
# Extension – [Clipboard Editor](https://github.com/raycast/extensions/tree/main/extensions/clipboard-editor)

Author: @pomdtr 

**Describe the feature and the current behavior/state.**

Take the current text in that has been edited in the clipboard editing buffer and paste it into an app such as sublime or vscode

**Who will benefit from this feature?**

People who a quick way to open a context to edit something that they need more space to see.

**Any Other info.**

Let me know if you have any questions!

**Comment by pomdtr** [comment]
This is a good suggestion, please keep it open.
