### ISSUE TITLE
[Search Browser Bookmarks] Add Support Japanese search

### ISSUE THREAD

**Issue by koheitakahashi** [raycast/extensions#3355]
# Extension – Search Browser Bookmarks

Author:

Search Browser Bookmars is not open source and I could not find the author.

I would like Search Browser Bookmarks to be able to search bookmarks in Japanese.

**Describe the feature and the current behavior/state.**

Currently, if a bookmark is registered in Japanese, a search in Japanese will not match.

For example, suppose that "アップル(日本)" and "楽天市場" is registered in my bookmarks as shown in the screenshot below.

![CleanShot 2022-10-29 at 13 19 10](https://user-images.githubusercontent.com/51867807/198822784-73b5d030-49ca-4b8f-a1d1-4b738f41c0f0.gif)

When I search for "アップル", I will not get any hits.
A search for "楽天" will not result in any hits.

Therefore, I would like to be able to search bookmarks in Japanese.

In this case, I expect "アップル(日本)" to appear in the search results when I search for "アップル" and "楽天市場" to appear in the search results when I search for "楽天".

**Who will benefit from this feature?**

Japanese who use this extension.

**Any Other info.**

I use chrome Version 106.0.5249.119 (Official Build) (arm64).

The URL of the bookmark in the screenshot is listed below.

- アップル(日本): https://www.apple.com/jp
- 楽天市場: https://www.rakuten.co.jp

**Comment by adhrinae** [comment]
+1 For this. Mainly searching in CJK languages doesn't work well.

I hope the Raycast team open-sources the extension so that other developers can look into this problem.

## Similar issues
- #1977
- #2277
- #2515 
- #2605

**Comment by dehesa** [comment]
Hi @koheitakahashi and @adhrinae,

We had indeed some issues searching in Browser Bookmarks in CJK languages. The release 1.43.0 now supports any language, please try them out. The fixes in that release have been minimal; we want to rewrite and open source the extension at some point in the beginning of next year, but I cannot give you an exact ETA.

**Comment by koheitakahashi** [comment]
@dehesa 

Thank you very much for the multi-language support. 🙌  I am looking forward to the release of the 1.43.0 version.

It is also very nice to see this extension will be open source. I would like to contribute when I can.
