### ISSUE TITLE
List item accessories randomly disappearing when filtering

### ISSUE THREAD

**Issue by fonimus** [raycast/extensions#3359]
Raycast version: 1.42.1

## Steps To Reproduce

1. Using map function in list item accessories construction with another accessories
  ````
  accessories={[
    ...item.labels.map((label) => ({ text: label.name })),
    { text: `#${item.number}` },
  ]}
  ````
2. Try to filter/unfilter with typing in search bar

Zip of test extension with bug : 
[bug.zip](https://github.com/raycast/extensions/files/9894027/bug.zip)

## The current behavior

![with-line](https://user-images.githubusercontent.com/26186612/198840791-60b81fc9-2305-417f-9e3e-e00763a93b39.gif)

Some accessories of some line are randomly disappearing 

## The expected behavior

![without-line](https://user-images.githubusercontent.com/26186612/198840803-ff738ec0-67ab-4382-9658-1c1c9a040521.gif)

The accessories should not disappear

**Comment by tonka3000** [comment]
I have the same problem with 1.42.x
