### ISSUE TITLE
[Bitwarden Vault] ...

### ISSUE THREAD

**Issue by cliffeyv** [raycast/extensions#3366]
# Extension – [Bitwarden Vault](https://github.com/raycast/extensions/tree/fdbea2522bf0176fdd7218f85a13c4d702a83a21/extensions/bitwarden/)
Author: @pomdtr

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.41.1

**Comment by pernielsentikaer** [comment]
Can you please describe the error you're facing, @cliffeyv, it's all empty 😊
