### ISSUE TITLE
Environment variables doesnt work

### ISSUE THREAD

**Issue by felixhaeberle** [raycast/extensions#3368]
Raycast version:
latest

## Description
I want to build my own plugin right now and I'm currently stuck with env variables. They simply return undefined no matter what I tried. I have set up several enviroment variable libraries such as dotenv to make it work but unfortunately, the self-defined env variables don't show up. Is this the intended behavior to limit env var's to a standard set?

Also I registered some strange bahvior with dotenv, one time it works and other times it don't, as something in raycast caches the vars. Do you have a working example how to deal with env in raycast extensions? Thanks!! 

## The current behavior
Env variables don't load 

## The expected behavior
Env variables should load

**Comment by fe9lix** [comment]
Hey Felix! It's expected that environment variables are not available – except for a couple of fix Node env vars that we set when launching the Node process. The vars that are available in your shell are usually set up via your shell configuration file, so they may be different for every user.

One way to set up custom configuration for extensions is using preferences: https://developers.raycast.com/api-reference/preferences

**Comment by felixhaeberle** [comment]
Thanks very much!! I have this case that I want to build a extension that needs a client id and a client secret for an API to work, and for a good user experience it can't be the case that every user has to create their own "App" inside the Platform from which the API is from right? how can one achieve this? 

I know there are other Raycast extensions like the one from gitlab where I only have to login and fetches to my data are possible then.

**Comment by fe9lix** [comment]
Currently most of the extensions either use password preferences for values such as API keys (end users enter their own keys) or OAuth if the service supports that. As for the latter, Raycast only supports [OAuth with PKCE](https://developers.raycast.com/api-reference/oauth) where you often only need a client id, which is fine to hardcode in the extension. If the provider does not support PKCE and/or requires a client secret, you could use an [OAuth proxy](https://github.com/mathieudutour/pkce-proxy) where only the proxy service knows the client secret. (We use that approach for our Linear and Asana extensions.) The OAuth credentials at the provider would be created under your user as the extension author, ideally through a separate account that you use for Raycast. End users of the extension then just authorize through their respective login credentials.

**Comment by felixhaeberle** [comment]
Interesting thank you very much, now things are getting clear!! Can you recommend an 0Auth proxy service?

**Comment by fe9lix** [comment]
As a start, you could deploy the linked project to a service such as Heroku or Vercel but probably best to ask in our Slack community.

**Comment by felixhaeberle** [comment]
Thank you, that was really helpful 🙏🙏
