### ISSUE TITLE
Enable extension developers to provide their own esbuild.config.mjs or to extend esbuild

### ISSUE THREAD

**Issue by jvican** [raycast/extensions#3382]
I was looking to write an extension, but I've seen that the build works with the ray CLI and it's hardcoded to Typescript.

I'm aware that you're using esbuild under the hood. Would it be possible to enable developers to configure esbuild so that we can write extensions in other languages that target js? For example, extension developers might want to develop extensions in Scala.js or Clojurescript —Purescript, or who knows what other language— which esbuild can integrate with through a custom plugin. Enabling developers to provide the esbuild plugin code or configuration for that would be nice as we can reuse those rich ecosystems to write React apps (that target Raycast's own backend).

I understand this is a bit of a power user feature, but I'm not a Typescript power user  so I'm asking to use something else because, at some point, I expect others will be in a similar position as myself.

Raycast version: v1.42.2

**Comment by thomaslombart** [comment]
Thanks for the feature request. We want to stick with only JavaScript and TypeScript and avoid any other supersets because it ensures that everyone is on the same page when it comes to reviewing and contributing to the extensions. Therefore, I'll close this issue as not planned 😊
