### ISSUE TITLE
[Weather] Location name shown incorrectly

### ISSUE THREAD

**Issue by juhamust** [raycast/extensions#3385]
# Extension – [Weather](https://github.com/raycast/extensions/tree/main/extensions/weather)

Author: @tonka3000 

## Description

The Weather extension has an issue showing location names correctly.

## Steps To Reproduce

1. Search weather for 'Jyväskylä'
2. See the output

## The current behavior

![image](https://user-images.githubusercontent.com/781002/199448762-0627985c-fab7-4ad4-a226-7737d37fe3ee.png)

## The expected behavior

For example, the console does not seem to have issues printing the letters

![image](https://user-images.githubusercontent.com/781002/199448957-26e0d516-0f8c-40a2-8d4e-fc46dbee411f.png)

### Raycast version

Version: 1.42.2

**Comment by tonka3000** [comment]
Hi @juhamust ,

please can you post the json content from https://wttr.in/?format=j1 here. I assume that you don't set a default query in the preferences (please comment if this is the case).

Not quite sure if the original json response is off or Raycast can not handle the string correct.

Thanks in advance
Michael

**Comment by juhamust** [comment]
Issue can be reproduced both with default query or query in Raycast window.

Seems that the issue is in wttr.in JSON data: [jyvaskyla.json.zip](https://github.com/raycast/extensions/files/9921102/jyvaskyla.json.zip)

![image](https://user-images.githubusercontent.com/781002/199511904-68a57c32-d88e-4167-a8c4-6605bf006652.png)

At the same time, the web view works as expected: https://wttr.in/Jyv%C3%A4skyl%C3%A4

**Comment by tonka3000** [comment]
> Perhaps this should be reported in Wttr unless there is no way to fix on query level?

I see the same data when calling https://wttr.in/Jyv%C3%A4skyl%C3%A4?format=j1 from my machine 🤔.
You should file an issue in the [wttr.in repo](https://github.com/chubin/wttr.in) because it looks like that this is an issue on the API v1.

**Comment by tonka3000** [comment]
@juhamust You can try my [OpenWeatherMap](https://www.raycast.com/tonka3000/openweathermap) as an alternative to the wttr.in

**Comment by juhamust** [comment]
Thanks for the suggestion, settling for OpenWeatherMap for now 👍 

But for the record: There is no alternative "international name" for Jyväskylä. Out of curiosity, I tested the language and it returns the forecast in Finnish:

![image](https://user-images.githubusercontent.com/781002/200557711-800c092c-614c-4eab-8ed5-e324285da4db.png)

So need for language support in the Weather extension for now. Will close this ticket.
