### ISSUE TITLE
[Authy] It's not possible to start from scratch

### ISSUE THREAD

**Issue by pernielsentikaer** [raycast/extensions#3394]
# Extension – [Authy](https://github.com/raycast/extensions/tree/ca17331bea29d1841de5738aae8b25b378ec0177/extensions/authy/)
Author: @guga4ka

## Description

It's not possible to `Start from Scratch`

## Steps To Reproduce

1. Type incorrect preference values on the first load
2. Use the action panel item `Start from Scratch`

## The current behavior

Show the toast with `Waiting for approval`

https://user-images.githubusercontent.com/38033107/199725662-c88bb029-932d-4cb3-949e-fa1aa2421c36.mp4

## The expected behavior

Pop extension preferences so the user can add the correct credentials.

I tried to fix it myself but I'm not sure what the logic should be, and how you think about it.

**Comment by guga4ka** [comment]
Not sure if it is possible to pop a preferences page once values are set. Option _Start from scrach_ was made to reset the onboarding flow with new values from preferences. Agree that message might confuse, but can't imagine another one.

**Comment by pernielsentikaer** [comment]
You can use [openExtensionPreferences](https://developers.raycast.com/api-reference/window-and-search-bar#openextensionpreferences) to pop to preferences from the action panel. could that work? 😊

**Comment by guga4ka** [comment]
Will play around it on weekends, sounds like a solution, wasn't aware about it.

**Comment by pernielsentikaer** [comment]
It wasn't there when you made the extension, that might be why 😊

**Comment by guga4ka** [comment]
I couldn't say that this option looks better 

https://user-images.githubusercontent.com/13866979/200295505-a5d594c4-0aa1-444b-886d-be13c4acca84.mov

@pernielsentikaer is there a way to clear extension/command preferences to show this screen? 
<img width="751" alt="image" src="https://user-images.githubusercontent.com/13866979/200296192-c826a919-40a1-495a-9e5d-126204d354af.png">

**Comment by pernielsentikaer** [comment]
No, not as it is right not @guga4ka
