### ISSUE TITLE
[Random Password Generator] Set default length

### ISSUE THREAD

**Issue by poxin13** [raycast/extensions#3398]
# Extension – [Random Password Generator](https://github.com/raycast/extensions/tree/a784ce773a32d0901ec9b34cd2b0167547128d04/extensions/random-password-generator/)
Author: [textnav](https://www.raycast.com/textnav)

Would love to see a setting to set the default length of the passwords so that when you open it each time it generates them based off this setting.

**Comment by purplespider** [comment]
Eager for this too. Commenting to have the feature request re-opened.

**Comment by axhamre** [comment]
+1 😊

It's an excellent extension and it would be so useful to be able to set default length 🙏
