### ISSUE TITLE
[Toothpick] Device support form

### ISSUE THREAD

**Issue by Emerson-Alexander** [raycast/extensions#3404]
# Extension – [Toothpick](https://github.com/raycast/extensions/tree/d228408bdb2e9155158cc8ff175d0c79d6188141/extensions/toothpick/)

**Device brand and model**

UGREEN HiTune X6

**Device data**

{"UGREEN HiTune X6":{"device_address":"C1:12:31:00:04:A5","device_batteryLevelMain":"100%","device_firmwareVersion":"1.0.0","device_minorType":"Headphones","device_productID":"0x223B","device_services":"0x800019 < HFP AVRCP A2DP ACL >","device_vendorID":"0x005D","device_connected":"true"}}

**Comment by VladCuciureanu** [comment]
Hello! Thanks for your submission. Your device is now mapped inside Toothpick. Whenever the next release comes up, you should see a custom icon accompanied by your device's battery level. ANC control is planned but yet to have an estimated release date.
