### ISSUE TITLE
[Slack] Extension doesn't find new people. 

### ISSUE THREAD

**Issue by gunniho** [raycast/extensions#3405]
# Extension – [Slack](https://github.com/raycast/extensions/tree/d3e045e1202b43a23bf38fddd89bf849135901b5/extensions/slack/)
Author: @momme-rtf

## Description
The Slack Search extension doesn't find everyone in our Slack. Surena is our latest addition to the team, and the extension doesn't find her. 

## Steps To Reproduce

1. Search for "Surena"
2. See that "Surena" isn't in the Raycast Slack Search Extension, even though she is in our Slack. 

<img width="769" alt="Screenshot 2022-11-04 at 10 08 59@2x" src="https://user-images.githubusercontent.com/1255418/199947503-0709106b-e186-41bb-bcb8-5c709038adc3.png">
<img width="173" alt="Screenshot 2022-11-04 at 10 09 25@2x" src="https://user-images.githubusercontent.com/1255418/199947572-a085235c-298f-4f72-b633-c77619b4c0e2.png">

## The current behavior
It appears that the extension can't find everyone. It might be that the extension can't find new people channels. 

## The expected behavior
I expect the extension to find everyone in my slack, not just some users. 

### Raycast version
Version: 1.42.2

**Comment by gunniho** [comment]
This might be related, but we only have 10 people on our Slack team: 
https://github.com/raycast/extensions/issues/2300

**Comment by momme-rtf** [comment]
@gunniho Thanks for reporting! Would you mind joining the raycast slack workspace so we can investigate further? Just search for my username and write me a dm:)
