### ISSUE TITLE
[DocSearch] Support for algolia search with different structure (e.g. gitbook)

### ISSUE THREAD

**Issue by AnishDe12020** [raycast/extensions#3406]
# Extension – [DocSearch](https://github.com/raycast/extensions/tree/a7bbeb339ab726e9a07842ac06b095913f5db96f/extensions/docsearch/)
Author: @Fatpandac 

**Describe the feature and the current behavior/state.**
Gitbook uses algolia for search and many developer docs live in gitbook (e.g. the raycast developer docs) and hence I think it would make sense to add support for gitbook. The problem with the gitbook indexes is that the `hierarchy` property (used for the title) and `url` property doesn't exist. Instead of the `url` property, there is a `path` property essentially indicating the path to the page so we can just add it after a preset `baseURL` which one can set in `apiData`. im not sure what to do about the hiearchy property yet so I think we have to discuss that (the only option in my mind right now is to simply show the `title` property which we get in gitbook indexes) 

EDIT: Seems like this is the behaviour of the Algolia API for many more search indexes (e.g. [Clerk Docs](https://clerk.dev/docs))

**Who will benefit with this feature?**
The users who use tools that have docs living in gitbook

**Comment by Fatpandac** [comment]
Thanks for your advice, I'll check it soon, but ***I cannot promise that it works out***.
