### ISSUE TITLE
[Set Audio Device] ...Select favorite does not work (Ventura OS).  

### ISSUE THREAD

**Issue by avj73** [raycast/extensions#3415]
# Extension – [Set Audio Device](https://github.com/raycast/extensions/tree/9705ba94af72208cff790222ee3ce28e02231825/extensions/audio-device/)
Author: @benvp

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.42.2

**Comment by lukepistrol** [comment]
Can confirm. Even the `Set Output Device` action itself does not list any devices when run.

**Comment by avj73** [comment]
Alas the favourite component still doesn’t work

**Comment by lukepistrol** [comment]
@tsugur Yes, when "Airplay Devices" are disabled, the action "Set Output Device" displays available devices but the Set "Output Device to Favourite" still does not work

![Screenshot 2022-11-15 at 15 42 35](https://user-images.githubusercontent.com/9460130/201947739-b9c4ac4a-2c44-4def-9b7e-9316679e660c.png)

**Comment by lukepistrol** [comment]
Not fixed yet
