### ISSUE TITLE
[Adhan Time] ...

### ISSUE THREAD

**Issue by shahnawaz323** [raycast/extensions#3417]
# Extension – [Adhan Time](https://github.com/raycast/extensions/tree/4bb301acf1ea251a4fcc32e03811017fd62eda93/extensions/adhan-time/)
Author: @mzaien

 Unless I switch to new app the menubar does not show the extension details. Instead of Menubar the prayer times should show in the raycast window.

Currently I have go to some app which leaves spaces for this extension notifications on menubar.

I am on MacOS venture

**Comment by mzaien** [comment]
Hi @shahnawaz323 

I have update the extension https://raycast.com/mzaien/adhan-time and added a search view please review it and tell me if it is good

**Comment by mzaien** [comment]
> Thanks for the update. Please include option to select hanfi time as well. Right Now we can only view shafi,maliki,hanbali prayer times

I'm depending on [aladhan api](https://aladhan.com) and they have this set of [methods](https://aladhan.com/calculation-methods) for calculating prayer times 

they have custom method but It is not clear for me how to make hanfi prayer method

**Comment by shahnawaz323** [comment]
I can get the hanfi time on their website under "Juristic School (only affects Asr calculation)". You can check where u can put it  in your api . Check screenshot 
![Screenshot_2022-11-09_11-40-06](https://user-images.githubusercontent.com/96956049/200809262-6d44df2b-e11f-4a0c-9a82-1d913d49da0e.png)

**Comment by mzaien** [comment]
> Juristic

Okay brother, found it I can use the `school` parameter, will work on it soon inshaAllah

**Comment by shahnawaz323** [comment]
thanks

**Comment by mzaien** [comment]
Salam @shahnawaz323 👋 , it was merged  [today](https://github.com/raycast/extensions/pull/3454#pullrequestreview-1175648123) please check it 

Thanks for your suggestions and help
