### ISSUE TITLE
[Yandex Music] ...

### ISSUE THREAD

**Issue by weeebdev** [raycast/extensions#3422]
# Extension – [Yandex Music](https://github.com/raycast/extensions/tree/13d29104d345dee8cbe7e1763b0b6edbd8d73ecb/extensions/yandex-music/)
Author: @AlexStrNik

## Steps To Reproduce

1. Open https://music.yandex.com/home in Brave browser on MacOs Monterey
2. Try to play music from raycast

## The current behavior
<img width="375" alt="image" src="https://user-images.githubusercontent.com/48881444/200177441-d2286a52-cfdf-47de-9b6e-129b87955456.png">

## The expected behavior
Work.

### Raycast version
Version: 1.42.2

**Comment by AlexStrNik** [comment]
Hi! I tried to reproduce and discovered that if Brave was installed after Raycast was launched whenever you try to select it in extension's preferences, Raycast resets it back to Safari. But if you relaunch Raycast everything works as expected. And yeah probably you should allow Raycast to control Brave in pop-up window. So can you please confirm that working, and probably we should report this bug to Raycast team

**Comment by weeebdev** [comment]
> Hi! I tried to reproduce and discovered that if Brave have been installed after Raycast was launched whenever you try to select it in extension's preferences, Raycast resets it back to Safari. But if you relaunch Raycast everything works as expected. And yeah probably you should allow Raycast to control Brave in pop-up window. So can you please confirm that working, and probably we should report this bug to Raycast team

It didn't work for me, however, I moved to https://github.com/juvirez/yandex-music-app . How about about creating something like https://www.raycast.com/mattisssa/spotify-player for this app?
