### ISSUE TITLE
Snippets not working in IntelliJ

### ISSUE THREAD

**Issue by jaybhanushali3195** [raycast/extensions#3427]
Extension – [Snippets](https://www.raycast.com/extensions/snippets/)
Author: Raycast

Description
Snippet does not work in IntelliJ. It does not apply if you open terminal or even any file within IntelliJ or probably any of the JetBrains apps.

Raycast version
Version: 1.42.2

Steps To Reproduce
Open IntelliJ
Open Terminal with: Menu->Tool Windows->Terminal or open any file in IntelliJ
Example:
![06 November at 05 PM 2](https://user-images.githubusercontent.com/36804441/200207714-87711891-7952-497c-a9fe-b6e4c8fcad89.gif)

The current behavior
Not extending snippets

The expected behavior
To extend snippets

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
