### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by daneeq** [raycast/extensions#3437]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/3de41c3231ca70545e679ffffa38ec03ed5519a8/extensions/spotify-player/)
Author: @mattisssa

## Steps To Reproduce

1. run Like Current Song or Dislike Current song

## The current behavior

Getting an API error: Bad Request

## The expected behavior

Executes successfully

### Raycast version
Version: 1.42.2

**Comment by jamborski-dev** [comment]
Same here. Tried re-login to Spotify to refresh authentication, but still same error. This is the main feature I got Raycast in first place. Could you please look into it? 

![Screenshot 2022-11-09 at 10 53 41](https://user-images.githubusercontent.com/46531778/200812233-1329c1ff-3d04-495f-91f8-90ac9fc9a972.png)

**Comment by Geezus42** [comment]
Also getting this.

**Comment by codepression** [comment]
Looks like they've updated the extension so that you have to create and use your own developer account on Spotify. But there's no place to even configure the extension with your API key and secret as far as I can tell. Will be taking a look
