### ISSUE TITLE
[Folder Search] ...

### ISSUE THREAD

**Issue by kaldray** [raycast/extensions#3440]
# Extension – [Folder Search](https://github.com/raycast/extensions/tree/16746d7925793ff02f67f2732a6d553b1bad2d6d/extensions/folder-search/)
Author: @GastroGeek

## Description

When i want to search for a folder the list does't show. The list still empty whatever i type and at any location :  This mac or my users path.

## Steps To Reproduce

1.Open folder Search
2. Search for a folder on any location on your mac.

## The current behavior

Folders doesn't appear when i type something.

<img width="862" alt="Capture d’écran 2022-11-08 à 16 48 01" src="https://user-images.githubusercontent.com/78658124/200611203-b546b0e2-063a-4688-8a14-4e31902d86f6.png">

## The expected behavior

Match what i type on search bar with name's folder on my mac and show them on the list

### Raycast version
Version: 1.42.2

**Comment by GastroGeek** [comment]
Did you check your permissions in macOS preferences (Privacy and Security I believe) @kaldray ? It will likely need `Files and Folders` and/or `Full Disk Access`.

Also, it depends on macOS' inbuilt Spotlight indexes so do ensure you have **enabled** spotlight indexing for your main drive/associated folders.

**Comment by kaldray** [comment]
Yes i just checked and raycast has full acces on my disc, files and folders too. Everything works great with Spotlight i can acces to my folders with it.  The sanity-check shows my path to my folder properly.

**Comment by mikowl** [comment]
@kaldray I had this same issue, uninstalling then reinstalling the extension seemed to fix it for me 🤷‍♂️

**Comment by karmelak** [comment]
I have the same issue. Unfortunately reinstaling the extension does not fix the problem. I gave full disk permissions to Raycast already. 

`mdfind` shows results but also outputs some logs on top. Do you think this could be the problem?

```
❯ mdfind Downloads
2023-02-14 13:57:07.658 mdfind[1618:26987] [UserQueryParser] Loading keywords and predicates for locale "pl_PL"
2023-02-14 13:57:07.659 mdfind[1618:26987] [UserQueryParser] Loading keywords and predicates for locale "pl"
/Users/karmelak/Downloads
/Users/karmelak/Library/Mobile Documents/com~apple~CloudDocs/Downloads
```
