### ISSUE TITLE
[TablePlus] ...

### ISSUE THREAD

**Issue by xiadongxiang** [raycast/extensions#3442]
# Extension – [TablePlus](https://github.com/raycast/extensions/tree/79827e3e08bb43bcf0e7950832da682a1c8d9c52/extensions/tableplus/)
Author:

## Description
<img width="270" alt="CleanShot 2022-11-09 at 09 17 04@2x" src="https://user-images.githubusercontent.com/15646003/200712457-563ce3fd-d65c-43d7-8ea3-043be10a6ca7.png">

## Steps To Reproduce

1.search database
2.open database

**Comment by mitchwd** [comment]
Can I please re-open this bug? It's still occurring for me.
Attempting to open any table via the Raycast extension gives an "Invalid URL" error.

Steps to reproduce:
1. Open Raycast
2. Search for 'tableplus'
3. Move to the Search Databases command
4. Open any connection

Expect: Database to open.
Actual: Error is presented (as in screenshot above): "Error Invalid URL"

Opening the same connection directly from TablePlus is working as expected.

Raycast v1.49.2
TablePlus Version 5.3.6 (496)
MacOS Ventura 13.3.1 (22E261)

@pernielsentikaer I think you were the original dev? Any ideas?

**Comment by mitchwd** [comment]
Ah, looks like it might be related to a custom data directory-
I've set a different directory in Tableplus > Preferences > Locations > Connections. 
Copying this directory to the Raycast TablePlus Extension Settings seems to work correctly. 👍🏻

**Comment by pernielsentikaer** [comment]
This was created before our new system where the author gets tagged so I didn't notice.

Did you have any items on the list when you opened the extension when the "wrong" path was added?

**Comment by mitchwd** [comment]
No worries. 
Yeah- the Raycast plugin was showing 2 connections that were in my _original_ data directory before I moved it. (ie. `~/Library/Application Support/com.tinyapp.TablePlus/Data/Connections.plist` No worries, I think this issue can be closed.

**Comment by pernielsentikaer** [comment]
Thanks for confirming 😊
