### ISSUE TITLE
[search-npm] incorrect yarn install script

### ISSUE THREAD

**Issue by net-tech** [raycast/extensions#3456]
# Extension – [search-npm](https://github.com/raycast/extensions/tree/a791432e9373e6988af9afa5509a5d3aedead156/extensions/search-npm)

Author: @mrmartineau @thomaspaulmann  

## Description

Copying the yarn install script of a package copies something like `yarn install common-tags`. `install` has been replaced in yarn for installing packages and `add` is now used. The correct package install script would be `yarn add common-tags`.

## Steps To Reproduce

1. Search any package using the extension.
2. Copy the yarn installation script.
3. Attempt to run the command on any of the more recent releases.

## The current behaviour

Yarn returns an error like \`install\` has been replaced with \`add\` to add new dependencies. Run "yarn add package-name" instead.`

## The expected behaviour

Yarn installs the package sucessfully.

### Raycast version

Version: 1.42.2

**Comment by mrmartineau** [comment]
@net-tech you are correct. Would you like to fix the issue?

**Comment by net-tech** [comment]
> @net-tech you are correct. Would you like to fix the issue?

@mrmartineau 
I'm pretty busy these days, so it would be very much appreciated if you quickly did it :)
