### ISSUE TITLE
Calculator result is wrong

### ISSUE THREAD

**Issue by nenad** [raycast/extensions#3458]
Raycast version: 1.43.1

## Description

Calculator result is wrong

## Steps To Reproduce

1. Open raycast
2. Type "20/0.05"
3. Expect result to be 400
4. Result is 4

## The current behavior

Result is 4

## The expected behavior

Result is 400

<img width="783" alt="image" src="https://user-images.githubusercontent.com/2515325/200965430-b8441549-61a4-4afa-990f-e65ab4187c76.png">

Similar issue reported in https://github.com/raycast/extensions/issues/1863.

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
