### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by mayssa2895** [raycast/extensions#3463]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/3de41c3231ca70545e679ffffa38ec03ed5519a8/extensions/spotify-player/)
Author: @mattisssa

## Steps To Reproduce

1. Install spotify extention
2. connect account
3. Try to like musique either from the menu bar player or from the control in raycast 

## The current behavior
There is an error "an error occured while communicating with spotify's web API, details : bad request"

## The expected behavior
The song should be liked on spotify

### Raycast version
Version: 1.43.1

**Comment by codepression** [comment]
Duplicate issue: #3437
