### ISSUE TITLE
Ignore .DS_Store when running `ray lint --fix`

### ISSUE THREAD

**Issue by felixhaeberle** [raycast/extensions#3464]
Raycast version:
Latest

## Description

When running `ray lint --fix`, `.DS_Store` files leads to an crash because of this error:

```
felixhaberle@MBP-von-Felix ~/D/g/miro (main)> npm run fix-lint

> fix-lint
> ray lint --fix

ready -  validate package.json file
ready -  validate package-lock.json file
ready -  validate extension icons
ready -  validate extension metadata
ready -  run ESLint
error -  run Prettier
[error] No parser could be inferred for file: src/.DS_Store
error -  linting issues found (tip: try re-running with '--fix')
```

## Steps To Reproduce

1. Insert `.DS_Store` file into subdirectory like src/
2. Run `npm run fix-lint`

## The current behavior

When running `ray lint --fix`, `.DS_Store` files leads to an crash.

## The expected behavior

`.DS_Store` should be ignored because it's ignored by .gitignore anyway,.

**Comment by raffeyang** [comment]
same problem

**Comment by mathieudutour** [comment]
Should work in 1.47.0!
