### ISSUE TITLE
[GitHub] Pull Request Templates

### ISSUE THREAD

**Issue by lucasnad27** [raycast/extensions#3469]
The [documentation](https://manual.raycast.com/github) mentions the following:

> 💡 Pro Tip: The Create Pull Request command also supports PR templates stored in the .github directory.

For the life of me, I can't figure out how to get the Create Pull Request function to respect my pull request template. Within my repo, I have a directory called `.github` with the following contents:

```
PULL_REQUEST_TEMPLATE.md
workflows
```

 The GitHub web interface picks up the template without a problem. Is there a bug? Or am I doing something wrong?

**Comment by mathieudutour** [comment]
Can you open an extension issue instead? https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...

**Comment by lucasnad27** [comment]
done - https://github.com/raycast/extensions/issues/4556
