### ISSUE TITLE
[Linear] Support for Switching Between Workspaces

### ISSUE THREAD

**Issue by dioncodes** [raycast/extensions#3485]
# Extension – [Linear](https://github.com/raycast/extensions/tree/90a20d15b0ae36a6cf6ea7900ef41101ef5f473d/extensions/linear/)
Author: @thomaslombart 

I am working with multiple workspaces and currently the extension is only working with a single one. For me it would be sufficient to have a command to switch workspaces - like "Switch Linear Workspace" -> select workspace and then it uses the selected workspace for all other commands until you switch again. Alternatively merge issues from multiple workspaces in e.g. "Assigned Issues" command would be awesome as well but this would probably be much more complicated.

**Who will benefit with this feature?**

Anyone who is a member of more than one Linear workspace.

**Comment by dioncodes** [comment]
@thomaslombart Wouldn't it be possible to store multiple (maybe limited to 3) workspace authorization tokens in the extension's configuration and add a command that can switch the selected one? Or config like this:

![CleanShot 2022-11-23 at 19 07 43@2x](https://user-images.githubusercontent.com/1241360/203618570-9df0949d-f143-4ad1-8a49-b747ec5950fa.png)

**Comment by thomaslombart** [comment]
Ah sorry, I missed your comment @dioncodes. It's not possible to do so as of now. Logging through `OAuth` is possible for only one account at a time.

**Comment by luizvergennes** [comment]
It has been more than 2 years; were there any significant improvements from different sources to possibly make this feasible?

**Comment by eduwass** [comment]
I'm working on a possible implementation for this here: https://github.com/raycast/extensions/pull/25646
