### ISSUE TITLE
[Word Count] "Include whitespace" keyboard shortcut conflicts with universal "close window" command

### ISSUE THREAD

**Issue by djpowers** [raycast/extensions#3488]
# Extension – [Word Count](https://github.com/raycast/extensions/tree/b4485b70806f879e4b683d53067fb2c3ca9d7014/extensions/word-count/)
Author: @itsmingjie

## Description
Raycast's [universal keyboard shortcuts](https://manual.raycast.com/keyboard-shortcuts) uses `⌘ W` to close the Raycast window. However, this extension uses the same shortcut to toggle the "include whitespace" option, which overrides the default Raycast behavior.

## Steps To Reproduce

1. Open Word Count's "Count" command
2. Press `⌘ W`

## The current behavior
The checkbox option for including whitespace is toggled.

## The expected behavior
The main Raycast window is closed.

My suggestion would be to change or remove the keyboard shortcut used toggle this. Since the actions menu only has two items, the `⌘ ⏎` command already works. Or as an alternative, perhaps `⌘ T` would work for "toggle," (or maybe "s" for "space"). If @itsmingjie is open to any of these options I'd be happy to create a pull request.

### Raycast version
Version: 1.43.2

**Comment by itsmingjie** [comment]
Got it! `⌘ T` sounds good as a secondary to `⌘ ⏎`. Would you mind making a pull request? Thanks!

**Comment by djpowers** [comment]
Thanks for being receptive! Just opened a PR.
