### ISSUE TITLE
[Brew] ...

### ISSUE THREAD

**Issue by scottdavisxx** [raycast/extensions#3489]
# Extension – [Brew](https://github.com/raycast/extensions/tree/b6892d67347d19c9b07f4116ec21b330e45258ad/extensions/brew/)
Author: @nhojb

I installed the extension. I tried to search and it crashed. I am on a 2022 16" MBP. 

## Error:
```

```

## Steps To Reproduce

1. Install homebrew extension in raycast.
2. Attempt to search.

### Raycast version
Version: 1.43.2

**Comment by nhojb** [comment]
Thanks for reporting. I had hoped that an earlier update had fixed this, but it didn't.

We're looking into possible fixes.

**Comment by nhojb** [comment]
It should be fixed now if you run `Check for Extensions Updates`

**Comment by scottdavisxx** [comment]
Confirmed. This is now working as expected.
