### ISSUE TITLE
[Brew] Failed to search on brew Extension

### ISSUE THREAD

**Issue by johnnyseubert** [raycast/extensions#3502]
# Extension – [Brew](https://github.com/raycast/extensions/tree/b6892d67347d19c9b07f4116ec21b330e45258ad/extensions/brew/)
Author: @nhojb

## The current behavior
I have an error sending me to try search again and again

## The expected behavior
list all the brew itens 

### Raycast version
Version: 1.43.2

**Comment by nhojb** [comment]
Just pushed an update that _should_ fix this issue.
