### ISSUE TITLE
For extentions, Default Action Performs when keypress Enter to confirm input of IME

### ISSUE THREAD

**Issue by jumpei-tsutsui** [raycast/extensions#3504]
Raycast version: 1.43.2
macOS 12.6
MacBook Air (M1, 2020)

## Description

The description is the same as #1250, but the same problem still occurs with extensions.
I don't think it is a specific extension issue, as the problem occurs with multiple extensions.
In the attached video, I confirmed that behavior with the Google Workspace extention; it also occurs with the Confluence Search extention.
I have confirmed that it does not occur when the Live Conversion feature is on. Also, once the candidate list is displayed and then converted, this issue does not occur.
The candidate list is what is shown in the attached image and is displayed when the conversion key (space key) is pressed multiple times.

## Steps To Reproduce

1. Open Raycast and Open an extention.
2. Enter some japanese words with IME.
3. Press Enter.

https://user-images.githubusercontent.com/6813186/201491987-0548e1ec-03c9-400e-8ad6-e5ac2752b136.mov

<img width="260" alt="candidate_list" src="https://user-images.githubusercontent.com/6813186/201492000-2d056c11-d3e5-4686-a99f-840ba9336ce7.png">

## The current behavior

Performing Default Action.

## The expected behavior

Just confirm input of IME.

**Comment by mathieudutour** [comment]
Out of curiosity, are you using the [google keyboard](https://www.google.co.jp/ime/) or the macOS keyboard?

**Comment by mathieudutour** [comment]
It should now be fixed in 1.62.0. Let me know if there still are some weird interactions!
