### ISSUE TITLE
[Asana] Textfield input lag

### ISSUE THREAD

**Issue by arnaudvalle** [raycast/extensions#3516]
# Extension – [Asana](https://github.com/raycast/extensions/tree/77cc13418b6cbfcf2e848ab5293aa0b02293d1ae/extensions/asana/)
Author: @thomaslombart 

## Description

When typing in input fields to create a new task, it lags and doesn't capture all key hits (see in the gif where I typed `hello`)

## Steps To Reproduce

1. Go to the create a task form
2. Add a name to the task (type it 'fairly' fast without interruption)
![input-field-lag](https://user-images.githubusercontent.com/1215056/201613065-2b24dcec-5f06-4242-99e6-ec1caf399dc3.gif)

## The current behavior
It seems to be doing some sort of throttling/debouncing on the text input and some characters disappear as you type the rest of the word. Typing each letter with a small pause between each character seems to be working ok.

## The expected behavior
We should be able to type as fast as we want in the input text and not lose any input

### Raycast version

1.43.2

**Comment by thomaslombart** [comment]
Hey @arnaudvalle, I can't reproduce that on my end. There isn't any additional logic (throttling/debouncing as you mentioned) on the task name field so I'm not sure where this comes from. Do you still have this issue as of today?

**Comment by arnaudvalle** [comment]
Hi @thomaslombart, thanks for looking into it. I've just tested again after a full reboot of my machine and I still get the issue. It is in fact not just limited to the task name field: the description field is also impacted. 
I've also double-checked the other fields and they all seem to behave as I would expect them to, with no noticeable lag on these.

I've also tried a few other raycast forms (snippets, reminders) and all the textfields in those seem to behave ok as well.

Is there any diagnostic / information I could provide you that would help you investigate it further? 

Thanks,

**Comment by thomaslombart** [comment]
I'm not sure what other info you could send on top of what you just said... I'll try to pass it on to a Raycast team member.
@mathieudutour Have you already had reports of extensions where the `Form.TextField` would lag as shown in the issue?

**Comment by mathieudutour** [comment]
I'm working on some changes that should fix that 🤞

**Comment by arnaudvalle** [comment]
For info, this is resolved for me now that I'm in v1.44.0 so I'll close it.
