### ISSUE TITLE
[YouTube] ...

### ISSUE THREAD

**Issue by rmn-pgt** [raycast/extensions#3518]
# Extension – [YouTube](https://github.com/raycast/extensions/tree/16761f22b3c6d1a9b3234fef364430da78c05805/extensions/youtube/)
Author: @tonka3000

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.43.2

**Comment by pernielsentikaer** [comment]
Closing due empty report, feel free to update it and I'll be happy to reopen 😊
