### ISSUE TITLE
[Documentation] Incorrect `List.accessoryTitle` description 

### ISSUE THREAD

**Issue by mmazzarolo** [raycast/extensions#352]
:wave: friends! 
Just wanted to report a tiny mistake/typo in the documentation of [`List.accessoryTitle`](https://developers.raycast.com/api-reference/user-interface/list), which is showing the `accessoryIcon` description instead of the `accessoryTitle` one. 
I wanted to submit a PR but I noticed that the docs are auto-generated from the type-definitions, so I assume I can only report it. :+1: 

![image](https://user-images.githubusercontent.com/9536354/141614173-5629a217-b571-4882-93cb-7611b618ced5.png)

**Comment by thomaspaulmann** [comment]
Good catch. Gonna update it.
