### ISSUE TITLE
[Brew] Issue on Macbook Air M1 - Unable to search and install via Raycast

### ISSUE THREAD

**Issue by bhanuvadlakonda** [raycast/extensions#3538]
# Extension – [Brew](https://github.com/raycast/extensions/tree/78ec4dfe8b316b05dade29da7bfe6cc2a807ab22/extensions/brew/)
Author: @nhojb

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.43.2

**Comment by nhojb** [comment]
It should be fixed now if you run `Check for Extensions Updates`
