### ISSUE TITLE
[Set Audio Device] ...

### ISSUE THREAD

**Issue by starshun** [raycast/extensions#3542]
# Extension – [Set Audio Device](https://github.com/raycast/extensions/tree/9705ba94af72208cff790222ee3ce28e02231825/extensions/audio-device/)
Author: @benvp

## Steps To Reproduce

1. Set a favourite device in Raycast Settings -> Extensions -> Set Audio Device
2. Use raycast to select Set output device to Favourite

## The current behavior
Fails with message "Favourite output audio device could not be set"

## The expected behavior
Audio output is set to the favourite device
![2022-11-16 12 18 45](https://user-images.githubusercontent.com/44442/202178997-bf5db674-2599-4a0f-a96e-bc88fc20d4e9.gif)

### Raycast version
Version: 1.43.2

**Comment by avj73** [comment]
Same problem.  Not sure if this has to do with how MacOS Ventura changed system preferences, but would love it if this could get fixed.
