### ISSUE TITLE
[Music] "Love Track" does not mark song with "Love" in Apple Music

### ISSUE THREAD

**Issue by hllvc** [raycast/extensions#3580]
# Extension – [Music](https://github.com/raycast/extensions/tree/17d8423f9e5ad4892254558fa227619413bad54f/extensions/music/)
Author: @peterdev22 

## Description
"Love Track" does not work anymore. I am not sure when it started happening, but recently I saw that my songs are not marked as "Love". I am currently on MacOS Ventura 13.0, if that info can help.

## Steps To Reproduce

1. Play song on Apple Music
2. Open Raycast bar
3. Search for "Love Track"
4. Execute "Love Track"

## The current behavior
It does nothing.

## The expected behavior
Mark song in Apple Music with "Love".

### Raycast version
1.43.2

**Comment by peterdev22** [comment]
The author for the music extension is actually @Rawnly but i've got a fix for this so no problem.

**Comment by peterdev22** [comment]
Fixed here #3595

**Comment by Rawnly** [comment]
@pernielsentikaer may this "wrong mention" be a `contributors` problem?

**Comment by hllvc** [comment]
@peterdev22 my bad. I did just quick glance at store. But probably this would be great to have labeled Author. Thanks for fix btw.

**Comment by pernielsentikaer** [comment]
We added a new template today, let me see if it's doing a better job @Rawnly 😊
