### ISSUE TITLE
[Toothpick] Device support form - Samsung Galaxy Buds Live

### ISSUE THREAD

**Issue by huseyint** [raycast/extensions#3584]
# Extension – [Toothpick](https://github.com/raycast/extensions/tree/d228408bdb2e9155158cc8ff175d0c79d6188141/extensions/toothpick/)

**Device brand and model**

[Samsung Galaxy Buds Live](https://www.samsung.com/us/mobile-audio/galaxy-buds-live/)

**Device data**

```json
{
    "Galaxy Buds Live (D701)": {
        "device_address": "E8:7F:6B:17:D7:01",
        "device_firmwareVersion": "0.0.1",
        "device_minorType": "Headset",
        "device_productID": "0xA013",
        "device_services": "0x800019 < HFP AVRCP A2DP ACL >",
        "device_vendorID": "0x0075",
        "device_connected": "true"
    }
}
```

**Comment by VladCuciureanu** [comment]
Hello! Thanks for your submission. Your device is now mapped inside Toothpick. Whenever the next release comes up, you should see a custom icon. ANC control is planned but yet to have an estimated release date. Same situation with battery level sadly.
