### ISSUE TITLE
[Toothpick] Device support form - Bose QuietComfort (QC) 35 wireless headphones II

### ISSUE THREAD

**Issue by huseyint** [raycast/extensions#3585]
# Extension – [Toothpick](https://github.com/raycast/extensions/tree/d228408bdb2e9155158cc8ff175d0c79d6188141/extensions/toothpick/)

**Device brand and model**

[Bose QC35 II](https://www.bose.com/en_us/support/products/bose_headphones_support/bose_around_ear_headphones_support/quietcomfort-35-wireless-ii.html)

**Device data**

```json
{
    "Bose QC35 II": {
        "device_address": "60:AB:D2:3B:0E:DA",
        "device_firmwareVersion": "4.8.1",
        "device_minorType": "Headphones",
        "device_productID": "0x4020",
        "device_rssi": "-51",
        "device_services": "0x800019 < HFP AVRCP A2DP ACL >",
        "device_vendorID": "0x009E",
        "device_connected": "true"
    }
}
```

**Comment by VladCuciureanu** [comment]
Hello! Thanks for your submission. Your device is now mapped inside Toothpick. Due to API limitations from Apple's and Raycast's side, ANC control and battery level indicators are not possible at the moment. This might change in the future.
