### ISSUE TITLE
[YouTube] Format error when searching for videos starting with numbers

### ISSUE THREAD

**Issue by rgutt** [raycast/extensions#3588]
# Extension – [YouTube](https://github.com/raycast/extensions/tree/16761f22b3c6d1a9b3234fef364430da78c05805/extensions/youtube/)
Author: @tonka3000

## Description
When searching for a video starting with a number a format error is thrown. In my case I was searching for the show "7 vs Wild". 

## Error:
```
Error: Rendering failed:
The data couldn’t be read because it isn’t in the correct format.

```

## Steps To Reproduce

1. Start Raycast
2. Type in Search YouTube  and select the command with enter
3. Search for any Video starting with a number such as "7 vs Wild".

## The current behavior
The error above is thrown.

## The expected behavior
The extension also accepts search queues starting with numbers.

### Raycast version
Version: 1.43.2

<img width="755" alt="Bildschirm­foto 2022-11-18 um 20 11 30" src="https://user-images.githubusercontent.com/16667984/202784082-af04f890-5569-4ecc-b2c6-c46e66dbb5b2.png">

**Comment by tonka3000** [comment]
@rgutt This should be fixed when #3592 get merged.

btw: It was not the starting character. Sometimes nodesjs string.slice crash when containing unusual characters, which seems to happen more often when Fritz Meinecke videos are searched 😉
