### ISSUE TITLE
[Extension Bug] cannot access Bitwarden if password contains "-"

### ISSUE THREAD

**Issue by Tsahao** [raycast/extensions#360]
## Extension – [Bitwarden](https://github.com/raycast/extensions/tree/main/extensions/bitwarden)
**Author:** @pomdtr 
**Raycast version:** 1.25.4

## Description
Cannot unlock vault if there is "-" in the password.
I can access the vault through terminal w/ no issues.
I can access the vault from Raycast extension if I changed my password to one without "-"

## Steps To Reproduce

1.Run Search Vault
2.Input correct Bitwarden master password (which contains - in the beginning)

## The current behavior
Failed to unlock vault

## The expected behavior
Unlock the vault

**Comment by fe9lix** [comment]
Update to "Extension Bug" (instead of API Bug)

**Comment by mattisssa** [comment]
Hey @pomdtr! 
🐞 Here is the new bug report to your extension, take a look at that and subscribe to don't miss anything related 😉

**Comment by pomdtr** [comment]
Thanks for the report! I'll look into it.

**Comment by pomdtr** [comment]
Thanks for the report, I think that this is related to raycast handling of input fields.

This message from the slack group is a good example of the problem: https://raycastcommunity.slack.com/archives/C01A0R0NXGQ/p1638304791155600

**Comment by pomdtr** [comment]
Hi @mattisssa, can we close this now that the issue is resolved in the API?
