### ISSUE TITLE
`searchText` property is abnormal when typing Chinese text

### ISSUE THREAD

**Issue by tisfeng** [raycast/extensions#3601]
As the title says, if you use the `searchText` property, it does not work properly when you type Chinese, for example, if you type "测试", the actual input text shows "ce' s".

### Test Extension:  [Easydict](https://www.raycast.com/isfeng/easydict)

This is an bug https://github.com/raycast/extensions/issues/3496  reported by an `Easydict` user, which I verified does exist. Another similar issue https://github.com/tisfeng/Raycast-Easydict/issues/27

![](https://user-images.githubusercontent.com/50407640/201456034-e56777d1-2f6d-4bc7-a043-f0fab6df7661.gif)

Raycast version: 1.43.2

## Description

After my investigation,  I found that it is caused by setting the `searchText` property,, if I remove it, the input display is normal. This should be the result of the recent Raycast api bug, I have seen the [Raycast fixes log](https://developers.raycast.com/changelog#1.43.0-2022-11-09) here, but do not know exactly what was fixed, apparently the problem still exists. Other extensions like [Todo List](https://www.raycast.com/maggie/todo-list) use this property and also have the same problem.

## Steps To Reproduce

1. use `Easydict` extension, type Chinese text, like 测试

## The current behavior

type "测试", the actual input text shows "ce' s"

## The expected behavior

type "测试", the actual input text shows "测试"

**Comment by mathieudutour** [comment]
Should be fixed in 1.45!
