### ISSUE TITLE
[One Thing] Being able to customise the font the same one that One Thing from Sindre

### ISSUE THREAD

**Issue by kud** [raycast/extensions#3606]
# Extension – [One Thing](https://github.com/raycast/extensions/tree/395c26cc7e211322861424b676ee450e11a81638/extensions/one-thing/)
Author: @pernielsentikaer

**Describe the feature and the current behavior/state.**

All is in the title

**Who will benefit with this feature?**

Everybody who uses One Thing

**Any Other info.**

The result, without customising One Sing from Sindre is also way better (right side):

![image](https://user-images.githubusercontent.com/655838/203050757-0bd6379a-40cd-469f-8a7b-77af36c14f0f.png)

**Comment by pernielsentikaer** [comment]
Just posting ref for visibility #3577

**Comment by mathieudutour** [comment]
That's not possible, Raycast doesn't allow you to customise the font used and is very unlikely to do so.

You are more than welcome to continue to use Sindre's app, it will remain a lot more powerful than the Raycast extension :)
