### ISSUE TITLE
[API Feature Request] Set hover text for list items 

### ISSUE THREAD

**Issue by es183923** [raycast/extensions#361]
Set a hover text for list items, like how the description works for preferences
![preferences example](https://user-images.githubusercontent.com/72744903/141856223-87138f2d-c8ac-40f0-989e-ce6ebb3bb987.png)

This is already implemented in the calendar extension. 
![calendar extension example](https://user-images.githubusercontent.com/72744903/141856079-b2998c41-203a-4ae0-a4f7-d34c2778723f.png)

**Describe the feature and the current behavior/state.**

Just like how the hover text shows for preferences, and in the calendar extension

**Will this change the current api? How?**

Yes. One idea is to add the `hoverText` prop. eg: 

```tsx
<List.Item title='Example Item' hoverText='hover text here'/>
```

**Who will benefit with this feature?**

Extension creators and users.

**Any Other info.**

no

**Comment by unnamedd** [comment]
The Tooltip was implemented in the version [1.32.0 (2022.04-06)](https://developers.raycast.com/changelog#1.32.0-2022-04-06).

It can be used in the `accessory` props in the `List.Item` component.

cc @fe9lix @mathieudutour
