### ISSUE TITLE
[Obsidian] Can append text to note

### ISSUE THREAD

**Issue by jzhang-brex** [raycast/extensions#3610]
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/9e427b6da0e2afbc24ec520d9c31c9bdb4da3e8e/extensions/obsidian/)
Author: @marcjulianschwarz

**Describe the feature and the current behavior/state.**

The plugin can create a new note. It'll be awesome so that it can append to certain note. As a configuration, the plugin can allow user to search among all the notes to append or specify a few options (e.g. daily note, scratchpad, draft)

**Who will benefit with this feature?**

**Any Other info.**

**Comment by marcjulianschwarz** [comment]
You can find more info on the available actions (and their preferences) [here](https://www.raycast.com/marcjulian/obsidian).
