### ISSUE TITLE
Custom URI handler raycast://

### ISSUE THREAD

**Issue by riccardodivirgilio** [raycast/extensions#3616]
It would be great if extensions could register custom uri handlers, or simply be able to respond to a custom one, such as raycast://my-extensions?foo=bar"

**Who will benefit from this feature?**

1. webapps can start Raycast with custom data
2. simple scripts can open Raycast using "open raycast://weather?aaa=22"

**Comment by peduarte** [comment]
Thanks for your suggestion! We'll consider it, and update the issue.

**Comment by mathieudutour** [comment]
Shipped in 1.47.0!

**Comment by riccardodivirgilio** [comment]
Great! Do you already have documentation for this? It should be linked here for future reference.

Thanks!

**Comment by peduarte** [comment]
@riccardodivirgilio Yep, good point. Here's the link to Deeplinks documentation → https://developers.raycast.com/information/lifecycle/deeplinks
