### ISSUE TITLE
[Linguee] Being able to translate from french to english

### ISSUE THREAD

**Issue by kud** [raycast/extensions#3619]
# Extension – [Linguee](https://github.com/raycast/extensions/tree/28f3b1846ce9e36d0afab62306ba0d840ba938eb/extensions/linguee/)
Author: @geekdada

**Describe the feature and the current behavior/state.**

Can't.

**Who will benefit with this feature?**

Me.

**Any Other info.**

Please?

**Comment by geekdada** [comment]
Sorry what is this about?

**Comment by kud** [comment]
Since I started to use this extension, only from english to french was possible. Not from french to english.

<img width="204" alt="image" src="https://user-images.githubusercontent.com/655838/204131309-0ab8a5b4-6dc6-4f40-819a-25673123e19f.png">

But since I've created this ticket, I can see that it's reversible so I'm fine now.

Thank you, I can close the ticket.
