### ISSUE TITLE
[API Feature Request] Embed Detail in a List

### ISSUE THREAD

**Issue by es183923** [raycast/extensions#362]
Show both a `Detail` component and a `List` component at the same time.
This is already implemented in the calendar extension.
Example:

![calendar extension example](https://user-images.githubusercontent.com/72744903/141856805-db641f45-88c9-48d1-ac9e-d4e8a3683ec5.png)

**Describe the feature and the current behavior/state.**

Embed a `Detail` component in a `List`, as shown in the previous image.

**Will this change the current api? How?**

Allow `Detail` to be in a `List`.
Example:
```tsx
<List>
    <Detail markdown='example detail' />; 
    <List.Item title="item1">
    <List.Item title="item2">
</List>
```

**Who will benefit with this feature?**

extension creators and users.

**Any Other info.**

no

**Comment by thomaspaulmann** [comment]
Hey, we thought about that one and paused it for now. It isn't just markdown but needs some more layouting to make it pretty. I'm closing this task for now. We might pick it up later.
