### ISSUE TITLE
[GitHub Beta] Install to organization without code access

### ISSUE THREAD

**Issue by underyx** [raycast/extensions#3623]
# Extension – [GitHub Beta](https://github.com/raycast/extensions/tree/90d9b021796bd5759097c9cbbc3d71b49f7d2a40/extensions/github/)

Author: @thomaslombart

**Describe the feature and the current behavior/state.**

I'd love to keep track of my open and assigned pull requests. But I wouldn't love to allow raycast to access the source code of my company's private repos.

**Who will benefit with this feature?**

Users from many companies.

**Any Other info.**

My team is struggling with similar problems in our own product which also has a github app. One of our ideas was to manage two github apps, one for code access and one for everything else, and require the code access one to be installed separately when a user wants to use code-related features.

**Comment by thomaslombart** [comment]
Thanks for your issue @underyx 😊
I'm not sure I get what you meant by "code access"? Organizations can prevent extensions from accessing their data (cf screenshot)

<img width="563" alt="CleanShot 2022-11-23 at 10 43 22@2x" src="https://user-images.githubusercontent.com/16003285/203515235-8aeea2cf-2170-4ef6-bd01-372443d71303.png">

**Comment by underyx** [comment]
Right, but if I don’t grant access to my company org, then I cannot see the
pull requests I have in the company repos. I’d like to grant that and it’s
easy to get approval for allowing access to pull equal data.

But if you expand “Repositories” you will see that access to source code is
included. That is sensitive access that I cannot just grant.

**Comment by thomaslombart** [comment]
Unfortunately, I don't see any [OAuth scopes](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps) allowing a user to manage PRs, issues, and all on private repos without granting code access 😕

**Comment by underyx** [comment]
Hmm, that's surprising to me! I've developed both kinds of apps before, and when I went to install the GitHub Beta extension yesterday, I'm 95% sure it showed me the GitHub App permissions screen instead of the OAuth one.

**Comment by underyx** [comment]
> I may be wrong since I didn't create directly the app. That being said, the `Raycast` app appears in the [Authorized OAuth Apps](https://github.com/settings/applications):

I think this is not the app I was prompted to install. The app I saw was called "Raycast Beta" or something similar. I can check in an hour and send screenshots! Note by the way that this issue is tagged [GitHub Beta] and not [GitHub], in case that's what's causing confusion.

**Comment by underyx** [comment]
And yep, I was wrong! Sorry for misleading you for so long. I think either GitHub updated the OAuth app auth design recently to match GitHub app auth, or I was thinking of a different flow which is specific to OAuth user auth. 

Sorry again about that. My feature request is still applicable but I guess it would be a much larger amount of work to switch to using GitHub apps.

**Comment by thomaslombart** [comment]
No worries 😊

Sure, the feature request is still applicable. I don't know what would be the amount of work to do, to be honest. This would need further investigation.
