### ISSUE TITLE
[Music] Just a test

### ISSUE THREAD

**Issue by pernielsentikaer** [raycast/extensions#3635]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

Testing

### Steps To Reproduce

Testing

### Current Behaviour

Testing

### Expected Behaviour

Testing

**Comment by pernielsentikaer** [comment]
It seems like it's correct now, right? We added a new form that takes care of doing the right tagging of people and extension name too

**Comment by Rawnly** [comment]
> It seems like it's correct now, right? We added a new form that takes care of doing the right tagging of people and extension name too

dope! thanks

**Comment by pernielsentikaer** [comment]
Now that part is always controlled by @raycastbot instead, closing 😊
