### ISSUE TITLE
[visual-studio-code-recent-projects] Allow reuse-window

### ISSUE THREAD

**Issue by vlaraort** [raycast/extensions#3645]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

Currently, when you open a new project from the extension, it opens in a new window. It could be really useful for people working with tabs, to allow to open it in a new tab, or even better, have an option somewhere to change the default open behaviour to new tab instead of new window.

The CLI command to open in tab instead of window is docummented here:
https://code.visualstudio.com/docs/editor/command-line

under the `--reuse-window` CLI flag

### Who will benefit from this feature?

All users that want more customization.

**Comment by thomaspaulmann** [comment]
Right now the extension doesn't use the CLI. We could consider bundling the CLI and add an option or secondary option for this behavior.

**Comment by thomaspaulmann** [comment]
@vlaraort do you want to contribute to the extension?
