### ISSUE TITLE
[Spotify Player] Does not allow app configuration

### ISSUE THREAD

**Issue by RichSimon** [raycast/extensions#3648]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Fresh install of both Raycast and extension. In the configuration panel, there does not appear to be a place to enter Spotify Client ID and Secret. (Different Raycast extensions show configuration options in the top of that panel.) 

<img width="984" alt="SCR-20221124-9vy" src="https://user-images.githubusercontent.com/2136539/203780992-1cbb72a4-1136-4e6a-8690-df6b4ed8fb3e.png">

### Steps To Reproduce

Ventura 13.0.1, fresh install of Raycast and Spotify Player. Generated new Spotify App on their site. Tried uninstalling extension and reinstalling.

Feel like I'm missing something, obviously there's a place to enter it.

### Expected Behaviour

Enter Spotify Client ID and Secret

**Comment by pernielsentikaer** [comment]
Hi @RichSimon 👋 

The first time you use one of the commands (like `Browse All`) you'll see this screen in order to make the connection

![Raycast-z5dUfs73@2x](https://user-images.githubusercontent.com/38033107/203799677-92eca0d7-71c5-4b47-87da-e9be9783b5dd.png)

**Comment by RichSimon** [comment]
That's what I thought too - but the window is blank and the progress line keeps animating endlessly (I let it run for a minute, but still).

<img width="711" alt="image" src="https://user-images.githubusercontent.com/2136539/203838308-9cce21f1-e931-4bf2-981e-b7cc4cdf6bd5.png">

**Comment by pernielsentikaer** [comment]
Did you try anything, like a restart?

**Comment by RichSimon** [comment]
OK **two** restarts somehow brought things back 🫣. Thank you Per!
