### ISSUE TITLE
[Toothpick] Device support form

### ISSUE THREAD

**Issue by Cheloneeh** [raycast/extensions#3653]
# Extension – [Toothpick](https://github.com/raycast/extensions/tree/d228408bdb2e9155158cc8ff175d0c79d6188141/extensions/toothpick/)

**Device brand and model**
Sony WH-1000XM4

**Device data**
{"WH-1000XM4":{"device_address":"14:3F:A6:09:E0:2C","device_firmwareVersion":"2.5.0","device_minorType":"Headset","device_productID":"0x0D58","device_services":"0x800019 < HFP AVRCP A2DP ACL >","device_vendorID":"0x054C","device_connected":"true"}}

**Comment by VladCuciureanu** [comment]
Hello! Thanks for your submission. Your device is now mapped inside Toothpick. Sadly, due to API limitations on Apple's and Raycast's side, ANC control and battery level indicators are not possible at the moment. This might change in the future.
