### ISSUE TITLE
[FIFA World Cup Qatar 2022™] ...

### ISSUE THREAD

**Issue by boetter** [raycast/extensions#3655]
### Extension

https://www.raycast.com/isma/world-cup

### Description

Show results in Menu Bar? 

Right now I can see my calendar showing which game is up, but it would be awesome to see live results via your extension?

<img width="355" alt="Screenshot 2022-11-25 at 11 16 32" src="https://user-images.githubusercontent.com/1336222/203960101-204bb689-f984-4cd1-a7eb-f65e1061124e.png">

**Comment by ismamz** [comment]
Hi @boetter! Is that screenshot a work in progress on the extension?
We can add live results (updated every minute).
You can see new coming features here: https://github.com/raycast/extensions/pull/3637

**Comment by boetter** [comment]
Unfortunately I don't have the skills to do it myself, this was just a screenshot of my calendar shown in the menu bar by a different Raycast extension.

**Comment by ismamz** [comment]
@boetter 👍 I'll work on that

**Comment by pernielsentikaer** [comment]
Let's have a look next time 😊
