### ISSUE TITLE
[Obsidian] Commands that search the vault do not work (Search Note)

### ISSUE THREAD

**Issue by Samsonite999** [raycast/extensions#3662]
### Extension

https://github.com/raycast/extensions/tree/9f3584132237295c2bbebc03e2de252eb5eb560c/extensions/obsidian/

### Description

```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20
```

### Steps To Reproduce

1. Obsidian vault path specified
2. Search Note function called
3. Raycast says "something went wrong"

**Comment by marcjulianschwarz** [comment]
Would you mind sharing how many notes there are in your vault?
