### ISSUE TITLE
[Apple Notes] ...

### ISSUE THREAD

**Issue by hinhkiet** [raycast/extensions#3665]
### Extension

https://github.com/raycast/extensions/tree/ff2962d923ce14ec58885e84455de4905f063995/extensions/apple-notes/

## Error:
```
doesn't work
```

**Comment by ron-myers** [comment]
Hi @hinhkiet - I am not sure I understand the issue you are having.  Can you elaborate?

**Comment by ron-myers** [comment]
Without more context - this can be closed.
