### ISSUE TITLE
[KeePassXC] Add Yubikey support

### ISSUE THREAD

**Issue by silas229** [raycast/extensions#3668]
### Extension

https://github.com/raycast/extensions/tree/9fb1ff46e2ce4185a0c7ff8d769e4fab0677065a/extensions/keepassxc/

### Description

Please add support for Yubikeys:
https://www.mankier.com/1/keepassxc-cli#Options-General_options

Example:
```
keepassxc-cli open -y 1 Documents/keepass.kdbx
```
The slot needs to be configurable (should be mostly 1 or 2).

### Who will benefit from this feature?

Every KeePaasXC user that has their database secured with a Yubikey.

**Comment by klassm** [comment]
Any update? Before the PR goes stale ...

**Comment by klassm** [comment]
Any news? It is again going stale.

**Comment by silas229** [comment]
The PR got closed due to inactivity, is there anyone who can work on it?

**Comment by klassm** [comment]
This issue is again going stale. Any updates?

**Comment by klassm** [comment]
Any news? Or is the extension just dead?

**Comment by klassm** [comment]
Ping

**Comment by silas229** [comment]
Ping

**Comment by SteffenAuer** [comment]
ping

**Comment by klassm** [comment]
Ping
