### ISSUE TITLE
[Search Project Manager] shows 1Password icon for vs-code remote projects

### ISSUE THREAD

**Issue by roelvangils** [raycast/extensions#3675]
### Extension

https://github.com/raycast/extensions/tree/main/extensions/visual-studio-code-project-manager

### Description

I noticed that the icon for my vs-code remote project is the 1Password file icon. Can I configure that? Even better: it would be nice if I could customise icons for my projects. Maybe even by supporting favicons.

### Who will benefit from this feature?

People managing multiple projects, of which some are Remote-SSH.

### Anything else?

![20221127_132754_Code@2x](https://user-images.githubusercontent.com/103744/204135334-5bd08fb5-eef4-4d8b-be79-dfd416066124.png)

**Comment by MarkusLanger** [comment]
Currently, no own data is stored in the extension. All information is loaded from the Visual Studio Extension.
Therefore, it is not possible to define your own icon for a project.
