### ISSUE TITLE
[Twitter] Handle multiple accounts?

### ISSUE THREAD

**Issue by kud** [raycast/extensions#3677]
### Extension

https://github.com/raycast/extensions/tree/34c65c7f190ad172e46c75384600aa938f932e98/extensions/twitter/

### Description

I'd like to be able to handle different accounts via this extension

### Who will benefit from this feature?

Everybody who uses more than one twitter account.

**Comment by kud** [comment]
😬

**Comment by tonka3000** [comment]
Related to #269

**Comment by kud** [comment]
ha that's great! Thanks!

**Comment by kud** [comment]
👋🏻
