### ISSUE TITLE
Wrong tooltips

### ISSUE THREAD

**Issue by tonka3000** [raycast/extensions#3680]
Raycast version: 1.44.0

## Description

The tooltip seems not to be in sync anymore 1.44.0. This is not the case for any node, but my GitLab extension has this problem.
The strange thing is that the data is set in the exact same line and only the tooltip is wrong. I tested the order by adding the project name to the tooltip and it was the wrong project name, so it seems that the order of the tooltips is not always the order of the list-items.

See https://github.com/tonka3000/extensions/blob/c76518e0c06762277d521d50fd4f484e5d1632e0/extensions/gitlab/src/components/project.tsx#L40

![CleanShot 2022-11-27 at 19 55 59](https://user-images.githubusercontent.com/3163807/204154418-7f0c1893-3486-4d45-a6af-5167403f240f.png)

![CleanShot 2022-11-27 at 19 56 47](https://user-images.githubusercontent.com/3163807/204154422-24b7eced-0f59-442b-942e-771bd979f927.png)

## Steps To Reproduce

1. Use the GitLab extension command `My Projects`

## The current behavior
Wrong tooltip is shown

## The expected behavior
The tooltip is shown from the given line

**Comment by mathieudutour** [comment]
Ah good catch, will be fixed in the next release

**Comment by mathieudutour** [comment]
Should be fixed in 1.45!
