### ISSUE TITLE
[Things] Extension cannot find the application 

### ISSUE THREAD

**Issue by pdrastil** [raycast/extensions#3681]
### Extension

https://www.raycast.com/loris/things

### Description

Hi,
it seems that current version of Things extension do not properly pick up installed Things 3 with following message

![things](https://user-images.githubusercontent.com/19188617/204155150-1d0eb2aa-e2bc-48b0-a609-d934aadd5f74.png)

### Steps To Reproduce

1. Installed Things 3 from App Store
2. Installed Things extension from Raycast store
3. Tried to invoke any command in Raycast
4. Extension is not picking up running Things application

### Current Behaviour

- Attempted to restart Raycast
- Attempted to restart Things 3

### Expected Behaviour

Extension can work properly with Things 3

**Comment by pdrastil** [comment]
After looking into System permissions I believe there should be some check / prompt to enable Security & Privacy > Automation > Raycast > Things. After enabling this the extension started to work.

**Comment by pdrastil** [comment]
Not stale

**Comment by peterdev22** [comment]
> After looking into System permissions I believe there should be some check / prompt to enable Security & Privacy > Automation > Raycast > Things. After enabling this the extension started to work.

Just did a tiny commit to make this clearer when there is an error.

**Comment by peterdev22** [comment]
@raycastbot close this issue
