### ISSUE TITLE
[Fantastical] Fantastical is not installed

### ISSUE THREAD

**Issue by akar0x** [raycast/extensions#3682]
Hello - 

### Extension

https://www.raycast.com/devahschaefers/fantastical

### Description

I have Fantastical running on my Mac. I have the Fantastical extension installed from Raycast.
When I add an event, I get an error message that Fantastical is not installed.
I have been unsuccessful in getting Raycast to work with Fantastical. Can anyone help me? Thanks

**Comment by nateritter** [comment]
This might have to do with the fact that Fantastical 2 is out, and named as such.

**Comment by nateritter** [comment]
Yes, this is in fact the issue. Easy workaround until the extension supports "Fantastical 2" is to just quit Fantastical completely and rename the app from "Fantastical 2" to "Fantastical".  You might have to disable and re-enable the extension, but doing this seems to resolves the issue.  I'm not sure of the impact of any updates from Fantastical's point of view.

**Comment by devahschaefers** [comment]
Hi thanks for pointing this out, I will work on an update
@nateritter
