### ISSUE TITLE
[Todoist] Unable to get labels, 502 error

### ISSUE THREAD

**Issue by lukigarazus** [raycast/extensions#3696]
### Extension

https://github.com/raycast/extensions/tree/ade8c11cbdc43d9f2e32eed95e55d0d56a0e0565/extensions/todoist/

### Description

I get this error all the time although task creation works
![Screenshot 2022-11-28 at 20 10 58](https://user-images.githubusercontent.com/32484818/204360978-83127e12-c5fb-4274-8333-fdd6a777ba61.png)

### Steps To Reproduce

1. Install Todoist extension
2. Input the API key
3. Create a task
4. Type in something in the title input
5. See the error at the bottom

### Current Behaviour

Error 502 appears in the extension

### Expected Behaviour

Error 502 does not appear in the extension

**Comment by thomaslombart** [comment]
I got this issue from time to time as well. The extension makes use of Todoist REST API v2 for more than a week now and I suspect the API to be a bit buggy for some API calls. I don't have any bandwidth on that for now, so I'd suggest to open an issue on the following repo: https://github.com/Doist/todoist-api-typescript/issues
