### ISSUE TITLE
[Spotify] No extension preferences are available to set and commands do not work

### ISSUE THREAD

**Issue by adetch** [raycast/extensions#3698]
### Extension

https://github.com/raycast/extensions/tree/c03b8fe91383caa14d69816a52a8674696de8827/extensions/spotify-player

### Description

I cannot see any preferences to set my client secret and token for spotify
<img width="1034" alt="Screenshot 2022-11-28 at 4 45 55 PM" src="https://user-images.githubusercontent.com/1463387/204410786-bde70bc3-5a41-444f-8ffe-c61b7e5fbfa0.png">

When I activate an option on the extension like 'like song' I get the followingnotice:
<img width="655" alt="Screenshot 2022-11-28 at 4 46 48 PM" src="https://user-images.githubusercontent.com/1463387/204410884-5fb40fda-9613-4fb8-b410-179946800de2.png">

### Steps To Reproduce

* Install extension
* Visit extension preferences
* Observe no such preferences are available

### Current Behaviour

I am unable to provide my spotify app's secret and token to control spotify

### Expected Behaviour

I can provide my spotify app's secret and token to control spotify

**Comment by adetch** [comment]
[extension-diagnostics.txt](https://github.com/raycast/extensions/files/10108744/extension-diagnostics.txt)

**Comment by jahirfiquitiva** [comment]
same issue here :c

**Comment by adetch** [comment]
@mattisssa any ideas?

**Comment by adetch** [comment]
The weird thing is there is no configuration even present in `package.json` to set the configs referenced in the help article here https://www.raycast.com/mattisssa/spotify-player... and furthermore `client_id` and `secret` are never pulled from any config but rather set once as per a typical Oath flow.

**Comment by adetch** [comment]
Looks like these preferences were removed in 099fc2f9885620fe64c2c0ed3d97838b94bf4f68, but docs weren't updated

**Comment by alez156** [comment]
lol I was going crazy trying to find the extension preferences

**Comment by adetch** [comment]
Please un-stale this, friendly stale-bot
