### ISSUE TITLE
[OpenAI GPT3] ...

### ISSUE THREAD

**Issue by marcmagn1** [raycast/extensions#3703]
### Extension

https://github.com/raycast/extensions/tree/90c4e7068117f8d0467a13bba113f2c21afef6b8/extensions/openai-gpt3/

### Description

The newest addition to the GPT-3 model family: `text-davinci-003` has been added, it would be great to add it to the list of models available in the extension.
Thanks in advance!

**Comment by simicvm** [comment]
Thanks for the comment @marcmagn1 . The PR #3699 with that feature has been merged few minutes ago. If you update the extension you should be able to use the new model.

**Comment by askep3** [comment]
Just did a fresh install of the extension, it doesn't look like text-davinci-003 is showing up.

**Comment by marcmagn1** [comment]
That was quick! All good on my side, its shows up! Thanks for the prompt
PR!

**Comment by simicvm** [comment]
> Just did a fresh install of the extension, it doesn't look like text-davinci-003 is showing up.

Interesting. I just re-installed the extension to test, and the model is there. It should be the default option.

<img width="1000" alt="openai-gpt3-1" src="https://user-images.githubusercontent.com/13484398/204526928-40c45a6b-4a00-4cc0-8070-3207e9188cb8.png">
<img width="1000" alt="openai-gpt3-2" src="https://user-images.githubusercontent.com/13484398/204527001-cee03a80-491a-416a-936e-fe7d1dec1944.png">

**Comment by askep3** [comment]
I tried re-installing a couple times as well as using a new API key, but it's just not showing up.

![image](https://user-images.githubusercontent.com/10843723/204533913-8b150ca8-d21b-44a6-8960-32213c7d0f22.jpeg)

**Comment by simicvm** [comment]
@askep3 you are actually using a different extension. The one we are talking about here is
https://www.raycast.com/simicvm/openai-gpt3

**Comment by askep3** [comment]
That would make sense. Thank you!

**Comment by deepbluesea** [comment]
can you add code-davinci-002

**Comment by simicvm** [comment]
> can you add code-davinci-002

it's in https://github.com/raycast/extensions/pull/4405 

should be merged soon.
