### ISSUE TITLE
[Dropbox] ... New Dropbox API no longer supports simple access_token

### ISSUE THREAD

**Issue by jcdietrich** [raycast/extensions#3713]
### Extension

https://www.raycast.com/chyroc/dropbox

### Description

Dropbox now uses scoped access and instead of an access_token you are given an
API key and API secret.

I would like it if this extension supported the current (and only available) api.

### Who will benefit from this feature?

Possibly everyone wanting to use this extension (don't know if existing ones still work)
but definitely any *new* user wanting to use this extension will not be able to unless 
this is addressed.

**Comment by Almadual** [comment]
I am having the same Issue and would like to be able to use this extension. As of now I cannot...
