### ISSUE TITLE
[Unicode Symbols Search] Accessing the "Miscellaneous Technical" symbol

### ISSUE THREAD

**Issue by JefCurtis** [raycast/extensions#3715]
### Extension

https://www.raycast.com/mmazzarolo/unicode-symbols

### Description

I see in the version changelist that some Apple-specific symbols (, ⌘, ⌥, ⏎, ⌫) were added, but I can't seem to access them. What is the magical incantation to get the right search results for these? 

### Steps To Reproduce

1. M1 MacBook Pro using the newest version of Raycast (1.44.0)
2. While using the extension, typing "command" or "cmd"

note: only the Apple logo worked for me typing "Apple"

### Current Behaviour

No results

### Expected Behaviour

⌘ command line

**Comment by pernielsentikaer** [comment]
⌘ is actually called `PLACE OF INTEREST SIGN`
⌥ should be searchable by `OPTION KEY`

We might be able to have something like `aliases` in the dataset where we can pass it to keywords - what do you think @mmazzarolo  / @FezVrasta

**Comment by JefCurtis** [comment]
Brilliant. Thanks for taking this on. Nice improvement!

**Comment by pernielsentikaer** [comment]
Thanks for the feedback; if you struggle to find anything, let me know 😊
