### ISSUE TITLE
[API Feature Request] 

### ISSUE THREAD

**Issue by l782993610** [raycast/extensions#372]
**Describe the feature and the current behavior/state.**
There should be proxy settings for foreign users.
**Will this change the current api? How?**
No, It can be a global setting in raycast.
**Who will benefit with this feature?**
It solve lots of network problems. For example, when I use the extension 'Google translate', It keep running with no result. I think it's cause by the proxy setting is not be used by this extension. However, we can't ask every developer to auto detect proxy setting. It should be  a global setting in raycast.
**Any Other info.**

**Comment by fe9lix** [comment]
Closing this since this seems to be something that should be handled via external apps and/or at the OS-level.
