### ISSUE TITLE
Can't connect to spotify [Spotify Player] ...

### ISSUE THREAD

**Issue by marvinoffers** [raycast/extensions#3724]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

I used Spotify-player for a couple of weeks ago and now since a week or so i is not possible to connect the raycast spotify player to my spotify account. 

### Steps To Reproduce

1. Connect Spotify
2. Try to search for a playlist
3. Asks to connect to spotify again
Repeat

### Current Behaviour

https://user-images.githubusercontent.com/21134921/204745683-10efd5b6-801f-4aaf-a332-b4ed4091ed01.mp4

After connecting to spotify it asks again to connect to spotify

**Comment by danielsequeira** [comment]
Hi @marvinoffers are you still experiencing this bug? Also are you able to consistently reproduce it?

**Comment by marvinoffers** [comment]
Working again! Thank you so much for looking into it @danielsequeira!
