### ISSUE TITLE
[Extension Feature Request] Enhancement of Figma File Search

### ISSUE THREAD

**Issue by arisacoba** [raycast/extensions#373]
# Extension – [Figma File Search](https://github.com/raycast/extensions/tree/main/extensions/figma-files)

**Author**: @michaelwschultz 
**Raycast Version:** 

## Describe the feature and the current behavior/state.
With the [Figma File Search](https://www.raycast.com/michaelschultz/figma-files-raycast-extension) currently, you can search files from one team. It would be so awesome if we can search from different teams as well 🙏

## Will this change the current api? How?
Not sure

## Who will benefit with this feature?
Anyone dealing with multiple teams in Figma

**Comment by mattisssa** [comment]
Hey @michaelwschultz ! 
💎 Here is the new feature request to your extension, take a look at that and subscribe to don't miss anything related 😉

**Comment by michaelwschultz** [comment]
@mattisssa thanks for the ping! @arisacoba appreciate the request. I've been planning to get this working soon. It's just been a busy time. Don't you worry though, it's coming! I'll post here again when I have an update. I'm working on a feature to allow drafts as well so people that aren't apart of any team can find this extension useful as well.

**Comment by arisacoba** [comment]
That sounds awesome! Thank you for this wonderful extension 🙇

**Comment by hannesjung** [comment]
@michaelwschultz thanks for the extension, was there any progress on supporting multiple teams or organisation users? thanks for an update

**Comment by msllrs** [comment]
i would certainly benefit from this feature!

**Comment by michaelwschultz** [comment]
Update: This was added by @GLaDO8 #6490 🎉
