### ISSUE TITLE
[Spotify] Option to hide menu bar player when nothing is playing, truncate text to length

### ISSUE THREAD

**Issue by Cobular** [raycast/extensions#3737]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

I'd like it if the Spotify menu bar feature would either minify itself down to just the spotify logo or somehow go away if I've been not playing anything for more than a few minutes (possibly configurable). Menu bar space is precious on a macbook air and I don't really need to know what's going on most of the time.

Also, if the song title is on the longer side, it can easily drive the menu bar into the annoying state where the date becomes only the day of the week and the menu bar item becomes cutoff. It would be preferable if the name would truncate to a certain length!

Example of a (actually pretty reasonable song name) causing overflow and being cutoff
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22972550/204988014-037a0c10-5518-41a8-8dd0-50a6283607e4.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22972550/204988111-63be3481-bb0e-4c86-8b0f-e1aada2468fa.png">

### Who will benefit from this feature?

All users of the menu bar extension, which I'd imagine many users have tried and then disabled because some of how it behaves is really frustrating and a bit of a non-starter.

### Anything else?

Just the images above showing the issue!

**Comment by mattisssa** [comment]
Hey! Thanks for the suggestion. Have you seen this feature in the command's preferences? 

![CleanShot 2022-12-02 at 16 16 21@2x](https://user-images.githubusercontent.com/15333662/205337197-a0b7c018-2c18-41ba-965a-f87f5e703a56.png)

Or would you like to have a separate action that allow you to expand/collapse it dynamically?

**Comment by Cobular** [comment]
🤦🏻‍♀️  totally missed that
A dynamic action would be nice though, although more useful would be a way to have it just show song title or band name (personally I'm always more interested in the name of the song because I can usually recognize the band even if it's a new song, plus song names seem to tend to be shorter). Also, the ability to tell it that the band name should be truncated before the song title would be great too!
