### ISSUE TITLE
[Extension Feature Request] 

### ISSUE THREAD

**Issue by l782993610** [raycast/extensions#375]
**Describe the feature and the current behavior/state.**
The extension google-translate doesn't provide a proxy option. However, the npm package google-translate-api obviously supports this feature, and here is the usage: [Google-translate-api-proxy](https://github.com/vitalets/google-translate-api#proxy)
**Who will benefit with this feature?**
Google Translate has request limits. If too many requests are made, you can either end up with a 429 or a 503 error.
And as for me, I can't get any result because I am a Chinese user, I can't connect google without proxy.

@ospfranco

**Comment by ospfranco** [comment]
this is a bit too advanced for the majority of users, that is why I didn't want to add it to the UI, however my work on the extension is done, if you want it you yourself or someone else will have to develop it
