### ISSUE TITLE
[Todoist] render markdown-style URLs

### ISSUE THREAD

**Issue by garymm** [raycast/extensions#3757]
### Extension

https://www.raycast.com/thomaslombart/todoist

### Description

Todoist accepts markdown syntax for URLs.
`[Help](https://www.todoist.com/help)` is rendered as [Help](https://www.todoist.com/help).
The todoist extension does not render these.

### Anything else?

https://todoist.com/help/articles/text-formatting

**Comment by thomaslombart** [comment]
Hey @garymm, as of now Markdown is not supported when rendered in `List.Item` components. If that's what you meant, we'll have to wait for a `@raycast/api` release.

**Comment by garymm** [comment]
Yeah I guess that's what I meant, but it's not a request for full markdown, just what the todoist app supports, and really just links.

**Comment by thomaslombart** [comment]
Yeah, you can see rendered links on the task's detail but not on list items due to Raycast's limitation, unfortunately. I've opened an issue on this a few months ago, so let's wait for status updates: https://github.com/raycast/extensions/issues/2957.
