### ISSUE TITLE
[Notion] ...

### ISSUE THREAD

**Issue by PhilMoore** [raycast/extensions#3759]
### Extension

https://www.raycast.com/HenriChabrand/notion

### Description

Hey, im having issues with the task addition element of this plugin. 

I've changed the database I use to add the tasks and it seems the extension is not refreshing. I added some additional linked database collums to it which are not displaying.

I've tried un-linking the app from notion, deleting the extention, deleleting the extension and connection in notion etc but no luck. 

Here's a screenshot of what all the collums look like on the list:
https://cln.sh/UtaXJt

Here's what I see:
https://cln.sh/jGDgxq
https://cln.sh/YYlLmo

Is there a way to force the extension to refresh the collums in notion?

### Steps To Reproduce

Add additional collums to a database and try adding it.

**Comment by metakirby5** [comment]
If you add non-relation properties, do they show up? I suspect that the plugin doesn't have read access to the linked databases, so it can't display the relations.

**Comment by PhilMoore** [comment]
Hey I added a status and that does not shop up. I don't think its that as all the linked databases are in my main folder which is shared and the app/ext does have access to these. 

So its not its also not adding any other new fields which have recently been added based on my test above.

**Comment by PhilMoore** [comment]
Hey, did you make any progress on this? Wondering if there's anything I can do as this is currently unusable for me. I see one related database field for my projects but missing the most important one which is for the clients to allocate the task to.

**Comment by metakirby5** [comment]
Actually, status was recently added to Notion, so it might not be supported by the extension yet. Can you try adding a basic text or checkbox field?

**Comment by PhilMoore** [comment]
Hey, basic text worked and shows up

All i need to see is the clients linked database, thats the field i need
to show up so this works. Its odd as the projects linked database is
showing up but not the clients one.

Thanks
Phil

On December 14, 2022, raycastbot ***@***.***> wrote:
> Actually, status was recently added to Notion, so it might not be
> supported by the extension yet. Can you try adding a basic text or
> checkbox field?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/raycast/extensions/issues/3759#issuecomment-
1351727040>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AHKXNYPCV5VOJGBFTQN5RT3WNHYJJANCNFSM6AAAAAASRVLPDI>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by metakirby5** [comment]
The only thing I can suggest is to re-install the extension 🤔

**Comment by PhilMoore** [comment]
Did that, still no change i dont see the clients related database list added, only the projects
