### ISSUE TITLE
[Extension Bug] Find in Dash always crash

### ISSUE THREAD

**Issue by linwanxiaoyehua** [raycast/extensions#376]
# Extension – [Find in Dash](https://github.com/raycast/extensions/tree/main/extensions/dash)

**Author**: @RSO 
**Raycast version**: v1.25.4

## Description

device: MacBook Pro with M1 Pro Chip
system version: macOS 12.0
dash version: latest in setapp

### when using dash downloaded from setapp

1. use find in dash 
2. crash

### Works fine on another Mac

device: MacBook Pro with intel Chip
system version: macOS 12.1
dash version: downloaded from official website

## The current behavior
<img width="862" alt="image" src="https://user-images.githubusercontent.com/35895571/142242753-5e88162a-1094-41ba-b227-8ffc463dbc63.png">

```
Error: Command failed: defaults read com.kapeli.dashdoc docsets | plutil -convert json -r -o /private/tmp/b2c5dddd0f84a034439a5eea55be298d.json -
2021-11-18 00:38:24.730 defaults[9884:105848] 
The domain/default pair of (com.kapeli.dashdoc, docsets) does not exist


2021-11-18 00:38:24.730 defaults[9884:105848] 
The domain/default pair of (com.kapeli.dashdoc, docsets) does not exist

ChildProcess.exithandler:node:child_process:397:12
ChildProcess.emit:node:events:390:28
maybeClose:child_process:1064:16
Socket.<anonymous>:child_process:450:11
Socket.emit:node:events:390:28
Pipe.<anonymous>:node:net:672:12
```

## The expected behavior

showing search result in dash

**Comment by mattisssa** [comment]
@linwanxiaoyehua Hey, thanks for the bug report! Let's report this to the extension's author. 
Provide a proper Raycast version in your ticket please.

**Comment by mattisssa** [comment]
I've also updated your report by mentioning author of the extension.
cc @RSO

**Comment by linwanxiaoyehua** [comment]
> @linwanxiaoyehua Hey, thanks for the bug report! Let's report this to the extension's author.
> Provide a proper Raycast version in your ticket please.

Hey, I've updated more details in description, if that helps.

**Comment by mattisssa** [comment]
> > @linwanxiaoyehua Hey, thanks for the bug report! Let's report this to the extension's author.
> > Provide a proper Raycast version in your ticket please.
> 
> Hey, I've updated more details in description, if that helps.

Thanks!

**Comment by linwanxiaoyehua** [comment]
I tested this extension on another intel Mac, it just works fine. Here's 2 thoughts I have:

1. This extension doesn't support M series chip
2. This extension doesn't support dash which is not from official website, maybe it's because the app path

Hope this will help. @RSO

**Comment by linwanxiaoyehua** [comment]
> I tested this extension on another intel Mac, it just works fine. Here's 2 thoughts I have:
> 
> 1. This extension doesn't support M series chip
> 2. This extension doesn't support dash which is not from official website, and I guess it's caused by the package name, dash from setapp has a different package name instead of com.kapeli.dashdoc
> 
> Hope this will help. @RSO

I checked this again, turns out it's caused by the package name, dash from setapp has a different one.

dash from official website: com.kapeli.dashdoc
dash from setapp: com.kapeli.dash-setapp

I guess now it's easier to enable a future to support dash from setapp? @RSO

**Comment by RSO** [comment]
Good find! I was wondering why my newly installed docsets didn't show up in the extension, but never got the time to look into this. I guess that the issue was that I have had both dashes installed at some point 😅 . I've attached a PR that fixes the issue by using a dynamic `bundleId`. Thanks for the thorough issue reporting!

**Comment by temannin** [comment]
Has there been an update for this? I am running version `1.26.2` with an M1 series chip and still receiving the error.

**Comment by RSO** [comment]
Hey @temannin, the original bug got fixed and deployed, and I've been using the extension on a daily basis on my M1 laptop, which leads me to think that your problem is a new one, so I'd suggest we move this into a new ticket.

In the new ticket, it'd be a great help If you could run `defaults domains` in your terminal, and look for `kapeli`, and let me know what the bundleId is for your Dash installation!
