### ISSUE TITLE
[OpenWeatherMap] API key not recognized

### ISSUE THREAD

**Issue by sasha42** [raycast/extensions#3761]
### Extension

https://github.com/raycast/extensions/tree/34c65c7f190ad172e46c75384600aa938f932e98/extensions/openweathermap/

### Description

I have added an API key to OpenWeatherMap inside of Raycast, however I keep getting a "_Could not fetch weather data from OpenWeatherMap_" error, stating an invalid API key.

<img width="757" alt="Capture d’écran 2022-12-02 à 11 10 55" src="https://user-images.githubusercontent.com/1775702/205269143-4f6a92e6-2bb5-4025-b42e-6ad623888864.png">

The API was tested in my browser, and is able to correctly return the weather, leading me to believe the error is within the extension implementation.

<img width="965" alt="Capture d’écran 2022-12-02 à 11 12 46" src="https://user-images.githubusercontent.com/1775702/205269365-b0648cb6-dcc1-4070-8b0f-3a30cf5d35d6.png">

### Steps To Reproduce

1. Install the OpenWeatherMap extension in Raycast
2. Obtain an API key from the OpenWeatherMap [API Keys](https://home.openweathermap.org/api_keys) dashboard
3. Paste the API key into the extension
4. Try to get the weather forecast using the extension

### Current Behaviour

The extension does not return the weather, giving a "_Could not fetch weather data from OpenWeatherMap_" error. The problem persists despite restarting Raycast.

### Expected Behaviour

The weather map is shown.

**Comment by sasha42** [comment]
Not to my knowledge! I copy and pasted several times. I even created a new API key just for this purpose.

**Comment by tonka3000** [comment]
Please try the onecall API in your browser if it also works

**Comment by sasha42** [comment]
I'm not familiar with the _onecall_ API - is it different from the API call that I made earlier in my test and added as a screenshot? If not, do you have a URL I could try?

**Comment by wra1w0** [comment]
I had the same issue with the extension. I think the reason is, that this extension uses One Call API from OpenWeatherMap. The fix is to use "One Call by Call" subscription plan (free for first 1000 calls per day) and not the standard free subscription. Then your API key works also with One Call API. The information about this subscription you can find here: https://openweathermap.org/price
