### ISSUE TITLE
[Set Audio Device] ... Airplay Devices aren't working

### ISSUE THREAD

**Issue by rjhewitt3** [raycast/extensions#3771]
### Extension

https://github.com/raycast/extensions/tree/653fa82fd1db7aa5ca74f1072acf3a628c486c1f/extensions/audio-device/

### Description

When Airplay Devices are enabled the output commands no longer work, in fact the list isn't populated at all. When disabled the list does populate, but of course Airplay Devices aren't listed. I use the the favorite output to quickly configure my desk homepods, and this extension has been a huge help. 

This stopped working when I upgraded to Ventura.

I also reinstalled the extension and that's how I discovered that when the airplay setting is off things work.

**Comment by rjhewitt3** [comment]
@benvp Perhaps no one else is experiencing this, but it's rendering the extension unusable for me (and I'm imagine others as well). Any plans to address this?

**Comment by ahoiemma** [comment]
@rjhewitt3 I just installed the extension and came here to search for an solution for this bug. I thought maybe I just didn't gave the right permissions to catch the list of airplay devices. Good to know im not the only one.

@benvp Would be great if you could take a look on this!

**Comment by id-clic** [comment]
Same here. I was searching a solution here but I was too optimistic. :-)

**Comment by rjhewitt3** [comment]
Seems like this extension isn't being maintained, that's unfortunate.

**Comment by rjhewitt3** [comment]
@gkoberger You PR'd this extension previously to add Ventura support, is this something you could consider? This is a bug, as far as I can tell, that relates to Ventura.
