### ISSUE TITLE
[Craft] Add Item To A Specific Note

### ISSUE THREAD

**Issue by IanAndrewR** [raycast/extensions#3786]
### Extension

https://www.raycast.com/bgnfu7re/craftdocs

### Description

I’d like to be able to add an item to the end of a note. Let’s say the note is called ‘Inbox’ and it’s in ‘My Space.’ You’d select the note/space in the extension setup so that in use you would simply be prompted for text which is added as the default action.

### Who will benefit from this feature?

Anyone using Craft as their dumping ground for ideas, notes, tasks etc

**Comment by kudrykv** [comment]
@IanAndrewR I will likely not be able to tackle it this year.

Still, please write up a bit more detailed workflow.
- How would you like to set up the note to which to append?
- Do you see it as appending to daily notes?
- Do you see yourself usually appending a few words (where input would do), or larger blocks of text (textarea)?

**Comment by IanAndrewR** [comment]
Hi @kudrykv as follows. Two options.

Easiest and perfectly fine for 80% of my use case.

- In the extension preferences you would select the default space and document. Let's say I have a recipes space and an Inbox where I want to jot down ideas, things I've seen and so on. 
- I would tell the extension first of all to use Space 'Recipes" (from a drop down returned by the extension) and then from a second drop down tell it to use the "Inbox" document. 

This would satisfy my requirement for selection of target document suitable as noted for 80% of my expected use case. 

Then

- You'd provide an 'Append Craft' command which would display a text area into which I'd type my notes. 
- Enter would append them to the "Inbox" document.

A slightly more complex and more complete/flexible.

- In the extension preferences you would select the default space only.
- The 'Append Craft' command would allow me to start typing the document name and as my target document appeared I'd be able to select that document. 
- I'd then enter my notes into a text area as before appending them in this case to the selected document in the space. Optionally I could skip selecting a document and have it default to the document (say Inbox) set up in preferences.

I suppose you could take this one step further an allow selection of space and document as part of the 'Append Craft' command but probably in this case, certainly for me, the extra keystrokes aren't worth it for the very few times I'd find myself outside my main Craft space.

HTH.

**Comment by kudrykv** [comment]
I would need to implement the second option anyway. AFAIK one cannot have dynamic values in the extension's preferences. As such, I can only have a predefined list of values. This makes no sense, so the second suggestion is the one that needs to be implemented.
