### ISSUE TITLE
[FaceTime] ...

### ISSUE THREAD

**Issue by ratkiff** [raycast/extensions#3788]
### Extension

https://github.com/raycast/extensions/tree/34c65c7f190ad172e46c75384600aa938f932e98/extensions/facetime/

### Description

Would love to make "ordinary" calls trough facetime. Used Alfred before and created an apple-script for it, however i do not know how to code in React etc. 

### Who will benefit from this feature?

Everyone who uses the app

### Anything else?

Dont know if this might help: 

`set isRunning to false
if application "Address Book" is running then
set isRunning to true
end if

set q to text ((offset of "Metadata" in q)+9) thru ((offset of "." in q)-1) of q

tell application "Address Book"
set phoneNum to value of phone of person id q

set phoneNum to item 1 of phoneNum

if isRunning is false
tell application "Address Book" to quit
end if

return phoneNum
end tell

end alfred_script</string>
				<key>cachescript</key>
				<true/>
			</dict>
			<key>type</key>
			<string>alfred.workflow.action.applescript</string>
			<key>uid</key>
			<string>93FE4836-7E73-48EE-BDB7-EAD342A28CD3</string>
			<key>version</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>applescript</key>
				<string>on alfred_script(q)

delay 1.5
tell application "System Events" to tell process "NotificationCenter"
	click button 1 of group 1 of UI element 1 of scroll area 1 of window 1
end tell

end alfred_script</string>
				<key>cachescript</key>
				<true/>
			</dict>
			<key>type</key>
			<string>alfred.workflow.action.applescript</string>
			<key>uid</key>
			<string>310D46E3-C087-4897-B3D5-24B6F6E59B0C</string>
			<key>version</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>concurrently</key>
				<false/>
				<key>escaping</key>
				<integer>127</integer>
				<key>script</key>
				<string>open 'tel://{query}'</string>
				<key>scriptargtype</key>
				<integer>0</integer>
				<key>scriptfile</key>
				<string></string>
				<key>type</key>
				<integer>0</integer>
			</dict>
			<key>type</key>
			<string>alfred.workflow.action.script</string>
			<key>uid</key>
			<string>337F7925-6BEA-46B8-838E-CE6205028551</string>
			<key>version</key>
			<integer>2</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>matchmode</key>
				<integer>1</integer>
				<key>matchstring</key>
				<string>( |-)</string>
				<key>regexcaseinsensitive</key>
				<false/>
				<key>regexmultiline</key>
				<false/>
				<key>replacestring</key>
				<string></string>
			</dict>
			<key>type</key>
			<string>alfred.workflow.utility.replace</string>
			<key>uid</key>
			<string>4BEF1D22-EE32-4A36-9CCB-19FD309BE197</string>
			<key>version</key>
			<integer>2</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>action</key>
				<integer>0</integer>
				<key>argument</key>
				<integer>0</integer>
				<key>focusedappvariable</key>
				<false/>
				<key>focusedappvariablename</key>
				<string></string>
				<key>hotkey</key>
				<integer>49</integer>
				<key>hotmod</key>
				<integer>3222274048</integer>
				<key>hotstring</key>
				<string>Space</string>
				<key>leftcursor</key>
				<false/>
				<key>modsmode</key>
				<integer>0</integer>
				<key>relatedAppsMode</key>
				<integer>0</integer>
			</dict>
			<key>type</key>
			<string>alfred.workflow.trigger.hotkey</string>
			<key>uid</key>
			<string>8EB82A14-42CD-4362-97B9-5DFFB896C21F</string>
			<key>version</key>
			<integer>2</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>argumenttype</key>
				<integer>0</integer>
				<key>keyword</key>
				<string>call</string>
				<key>subtext</key>
				<string>Ring {query}</string>
				<key>text</key>
				<string>Ring</string>
				<key>withspace</key>
				<true/>
			</dict>
			<key>type</key>
			<string>alfred.workflow.input.keyword</string>
			<key>uid</key>
			<string>99513CE2-87A3-46C9-B8E3-FDE46F4BD51A</string>
			<key>version</key>
			<integer>1</integer>
`

**Comment by ron-myers** [comment]
Thanks @thelastrife - I will add this to the backlog for this extension.   :)

**Comment by avj73** [comment]
Would also be good if there was a way to set up favorites, so you don't have to remember the phone #

**Comment by ratkiff** [comment]
@avj73 - I think a connection against “Contacts” Would suffice, so you can just search contact name, select and call :)
