### ISSUE TITLE
[Raindrop.io] ...

### ISSUE THREAD

**Issue by diminutivesloop** [raycast/extensions#3797]
### Extension

https://github.com/raycast/extensions/tree/efba3ec1978c17317a96bcdcaa914f9153839e04/extensions/raindrop/

### Description

Provide an option to view and search bookmarks from a specific user collection in addition to all bookmarks. This could be a dedicated command or a dropdown filter within the current commands.

### Who will benefit from this feature?

Any user who makes heavy use of the collections feature. As an example I have a "Read Later" collection and I would like to be able to easily look up and open those links via Raycast and not have the results cluttered with other links that I may have saved more recently.

**Comment by lardissone** [comment]
@diminutivesloop thanks for the suggestion! I'm already working on something like this! 
I'm facing a small problem that are the Groups. 

Collections are grouped within groups, so I have a few ways to do this:

1. ignore groups and put all the collections from all groups in the same list
2. display group name before collection name in dropdown
3. let the user set the group in settings (or by command) and always display collections from selected group

Also there's another drawback: nested collections.
To build the entire collections tree as it's displayed in their app, you need to do 3 different requests (documented [here](https://developer.raindrop.io/v1/collections/nested-structure)).
For this I was thinking on a new command to refresh the collection tree manually, to avoid long delays displaying collections.

What do you think?

Also, I'm thinking on change the display type based on the collection view option. So if you have a collection with `grid` or `masonry` view, I can display a grid of images in Raycast.

**Comment by lardissone** [comment]
Created a PR for this: https://github.com/raycast/extensions/pull/3920

**Comment by diminutivesloop** [comment]
@lardissone Looks good, although the filter selection isn't persisting between invocations of the command. If that's intentional it would be great to add an option to set the default collection filter or at least persist the most recently used one.

**Comment by lardissone** [comment]
@diminutivesloop ah, nice suggestion. I think it should be treated in settings. 

I'm not sure if you can do operations in settings (to fetch all collections and be able to choose), but maybe it could be a simple checkbox: "Use always the last selected collection".

WDYT?

**Comment by diminutivesloop** [comment]
The second option ("Use always the last selected collection") sounds perfectly fine for now.

**Comment by lardissone** [comment]
@diminutivesloop I've added that preference in #3995 will be released soon

**Comment by lardissone** [comment]
This has been released with #3995 .
We can close this ticket! /cc @pernielsentikaer
