### ISSUE TITLE
OAuth - Raycast button “Open Raycast” doesn’t work

### ISSUE THREAD

**Issue by mt40** [raycast/extensions#3799]
Hi team,

I’m following the guides at [1] and [2] to implement OAuth for Notion. Since I cannot store CLIENT_SECRET in Raycast, I also use a proxy server [3] for to keep it for me.

Problem
After Notion redirect to https://raycast.com/redirect?packageName=Extension with `code`, I see the web page below. The issue is clicking “Open Raycast” doesn’t do anything. Which prevent my extension to continue since promise is not fulfilled.
<img width="1666" alt="Screen Shot 2022-12-06 at 13 17 32" src="https://user-images.githubusercontent.com/8610576/206484345-06cf867b-4d0d-4b9c-8efd-37d84f7ca9a7.png">

My OAuth flow:
1. In Raycast extension, send an authorize request to Notion using PKCEClient
2. Notion redirects to Raycast with `code` <— I’m having problem after this step
3. In Raycast extension, after the promise is fulfilled, I make a request containging `code` to `myproxy.com/notion/access-token`
4. Notion returns `access_token` to proxy
5. Proxy returns `access_token` to my Raycast extension

Any suggestions on how to do this is welcome. Thank you so much in advance!

**Comment by fe9lix** [comment]
Hi! The link to the screenshot is not accessible.

Could you also share the full redirect URL from the Raycast page? (safe to share since only you have the code challenge.)

We already have an extension using OAuth with Notion in the store, maybe that helps to double check your implementation:
https://github.com/raycast/extensions/blob/main/extensions/notion/src/utils/notion.ts

**Comment by mt40** [comment]
hi @fe9lix I have updated the image. Yup I also consult the code from that extension and learn about the oauth-proxy approach. It’s very helpful haha.
However, back to the topic, I followed the oauth flow (like the extension) and got stuck at the step mentioned above.

**Comment by mt40** [comment]
I have a suspicion that only approved extension can be open from the web browser.
When testing with the other Notion extension, immediately after Notion redirect to raycast website with this url:
https://www.raycast.com/redirect?packageName=Extension&code=<…>&state=<…>
Browser shows a popup to ask me to allow opening Raycast.

My redirect url is similar, just different code and state, but the browser never shows that popup.

**Comment by mt40** [comment]
hi @fe9lix , thanks for your support, I have figured out what is the issue.
My redirect url is actually:
`https://www.raycast.com/redirect?packageName=Extension&?code=aaa&state=bbb`
Notice the 2 question marks 🥲
