### ISSUE TITLE
[API Bug] FileIcon not showing previews

### ISSUE THREAD

**Issue by es183923** [raycast/extensions#381]
Raycast version: 1.25.4

## Description

[FileIcons](https://developers.raycast.com/api-reference/user-interface/icons-and-images#fileicon) don't show the finder thumbnail, as it is supposed to

original link: https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1637224665196500

## Steps To Reproduce

1. Get an image.
2. Install the File Manager extension (just an easy way to repro it, can use any code that use FileIcons)
3. Navigate to that file

## The current behavior

It just shows a default image icon, not the image preview itself.

## The expected behavior

It should show a the Finder Thumbnail preview, as what is shown in finder.

**Comment by fe9lix** [comment]
Closing since this does not seem like a bug: the file icon for the type is correctly shown but full previews (e.g. for images) are not. This is the same behavior as in our built-in file search. We'll add a quicklook API at some point that should help with showing full file previews.
