### ISSUE TITLE
[Home Assistant] Failure authenticating with web socket

### ISSUE THREAD

**Issue by jweingardt12** [raycast/extensions#3811]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Description

API Token was created, but the extension cannot access the HA web socket. 

Running Raycast 1.44.0

<img width="789" alt="Screenshot 2022-12-07 at 09 03 07" src="https://user-images.githubusercontent.com/8882028/206199340-0dd47458-5dfa-4502-8df9-7293c376b4bd.png">

**Comment by jweingardt12** [comment]
Well...my attempts to resolve did it. Instead of the `.local` domain I entered the local IP, which worked. It does not, however, work on the reverse proxy I have configured via Cloudflare Tunnels. Not a huge deal, though!

**Comment by Shpigford** [comment]
I'm experiencing this same issue, however the local IP fix does not work for me.

**Comment by SikhNerd** [comment]
Local IP Fix worked for me, thanks
