### ISSUE TITLE
[Linear] Can't authorize extension while under VPN

### ISSUE THREAD

**Issue by lainisourgod** [raycast/extensions#3815]
### Extension

https://github.com/raycast/extensions/tree/8af9388f217e31487aecdf1284e8718a619766d3/extensions/linear/

## Error:
```
TypeError: fetch failed

Object.processResponse:undici:6406:34
undici:6727:42
AsyncResource.runInAsyncScope:node:async_hooks:203:9
```

### Steps To Reproduce

1. macos ventura macbook m1 max 16" 2021, raycast 1.44.0. cisco anyconnect corporate VPN
2. open `create issue` command. then click `sign in with Linear`. it opens browser, press `Authorize Raycast`.
3. error

### Current Behaviour

It opens Raycast, for a moment everything is ok, then it shows error message `something is wrong`, then it shows blank page 

<img width="757" alt="CleanShot 2022-12-08 at 00 16 58@2x" src="https://user-images.githubusercontent.com/24773652/206286700-ffdeb92b-b7ab-47f1-ad76-1caad6a52ea5.png">

### Expected Behaviour

Normal error message is shown saying I can't authorize. And better, I'm not required to disable VPN to authorize extension.

**Comment by lainisourgod** [comment]
also while trying to create issue while using VPN
```
TypeError: fetch failed
    at Object.processResponse (node:internal/deps/undici/undici:6406:34)
    at node:internal/deps/undici/undici:6727:42
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by thomaslombart** [comment]
Thanks for the issue. I'll take a look at that next week.

**Comment by thomaslombart** [comment]
I tried reproducing it with a VPN (NordVPN) without any success. All worked fine on my end. Are you able to log in to Linear without the VPN?

**Comment by lainisourgod** [comment]
@thomaslombart could you please provide me with request that Raycast is doing to login to Linear? I could ask if my VPN admins blocked domain or some parts of this request.

**Comment by thomaslombart** [comment]
You can get the authorization link on the OAuth login screen:

![CleanShot 2022-12-12 at 15 15 51@2x](https://user-images.githubusercontent.com/16003285/207067886-7a83c882-a2f9-4c79-8885-6cd9bc321523.png)

The authentication process goes through a proxy located at https://linear.oauth-proxy.raycast.com/. 

If you need more info on the API calls, you can check out the source code as well: https://github.com/raycast/extensions/blob/main/extensions/linear/src/api/oauth.ts

**Comment by thomaspaulmann** [comment]
@lainisourgod did you find anything?
