### ISSUE TITLE
Add possibility to get logging information from a user

### ISSUE THREAD

**Issue by tonka3000** [raycast/extensions#3817]
Raycast version: 1.44.0

**Describe the feature and the current behavior/state.**
Sometimes it is very hard to find a bug which happens on a users machine. Just having the stack trace not always help that much.
It would be great when there would be a possibility to record the console.log (can also be a raycast specific API) on a users machine (AFAIK console.log is deactivated) when a user activate the recording (opt-in). Afterwards this file could be shared with the extension developer to have a better inside what is going on on the users machine.
Because the log can have secrets in it, it would be good to inform the user about it so that it don't get shared on e.g. GitHub when it contains sensitive information.

**Comment by fe9lix** [comment]
We're currently working on a related project that would collect errors and make them accessible to developers. This would also include better source-mapped stack traces and including a concept of "breadcrumbs" (e.g. a trail of actions that the end user executed). Recording custom logs _*could*_ be a future addition to this but as you say, there is additional risk that sensitive data could be leaked.

**Comment by tonka3000** [comment]
@fe9lix This sound great

**Comment by mathieudutour** [comment]
Moving this discussion to #extension-issues-beta 👀
