### ISSUE TITLE
Mirror doesn't work

### ISSUE THREAD

**Issue by havhav31** [raycast/extensions#3819]
Raycast version:

## Steps To Reproduce

1.
2.

## The current behavior
gen.lib.rus.ec mirror doesn't work in my country. There should be a feature that allows us to specify the Libgen mirror.

**Comment by mathieudutour** [comment]
What extension are you talking about?

**Comment by danpalmer** [comment]
Looks like this is for https://www.raycast.com/yz3440/library-genesis.

It depends on `libgen` from NPM, which chooses from just 2 mirrors – https://www.npmjs.com/package/libgen#usage-choosing-a-mirror.

@havhav31 I'd suggest opening an issue on https://github.com/dunn/libgen.js about this. It looks like others have had [similar issues](https://github.com/dunn/libgen.js/issues/30). Also looks like it's out of maintenance, but a PR adding a new mirror to the list [here](https://github.com/dunn/libgen.js/blob/trunk/available_mirrors.js) might be accepted.

Then an upgrade to the libgen dependency on the extension should just work.
