### ISSUE TITLE
[Github] See the pull requests of others in the same repo

### ISSUE THREAD

**Issue by Ssionn** [raycast/extensions#3833]
### Extension

https://www.raycast.com/raycast/github

### Description

When in a repository with others, see their pull requests as well

**Comment by thomaslombart** [comment]
In which command would you like to see that? Note that it's already possible when searching for repositories (via the `Show Pull Requests` action, cf recording below)

https://user-images.githubusercontent.com/16003285/206703779-b84ae02d-d5df-4b48-9e98-f8ce49f86a52.mp4

**Comment by Ssionn** [comment]
If it's already available, than my issue can be closed. In my opinion it makes more sense to put it in the "Search Pull Requests" tab. For example you would be able to choose a repo in the Pull requests tab and then look at the pull requests that has been made for the repo.

In other words; I think the feature is way too hidden.

**Comment by Ssionn** [comment]
That's a fair point. I'm going to close this thread, since my question has been answered. Thank you!
