### ISSUE TITLE
Drafts - Optional Dropdown Tags List

### ISSUE THREAD

**Issue by erauner12** [raycast/extensions#3834]
### Extension

https://www.raycast.com/FlohGro/drafts

### Description

Giving us the ability to define static values to cycle through after using `Create Draft` action

ex:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/59383957/206707455-bb43b13b-4363-4f72-924a-d3f9b72766a0.png">

### Who will benefit from this feature?

will benefit by not having to remember specific tags that you want your drafts to fall into. Will not have to type them in manually.

### Anything else?

Let me know if you have any questions :) Thanks for all you do in the community

**Comment by erauner12** [comment]
bump, don't want this to be stalle

**Comment by FlohGro-dev** [comment]
I will definitely look into it 👍🏼

**Comment by FlohGro-dev** [comment]
Boost :)

**Comment by FlohGro-dev** [comment]
bump

**Comment by FlohGro-dev** [comment]
Closed in the newest update, please check it out @erauner12

**Comment by erauner12** [comment]
Awesome! This works great so far 🙂 Thank you

**Comment by FlohGro-dev** [comment]
Can you close the issue then @erauner12 ? Or is this up to the raycast team?

**Comment by erauner12** [comment]
all closed!
