### ISSUE TITLE
[1Password] ...

### ISSUE THREAD

**Issue by JonCrawford** [raycast/extensions#3836]
### Extension

https://github.com/raycast/extensions/tree/34c65c7f190ad172e46c75384600aa938f932e98/extensions/1password/

### Description

Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20

### Steps To Reproduce

1. Just tried to access a password with the `1p` command.

**Comment by pernielsentikaer** [comment]
Do you still have this issue @JonCrawford

**Comment by JonCrawford** [comment]
Looks ok today.
