### ISSUE TITLE
[Shell] Duplicated characters in section titles of man pages

### ISSUE THREAD

**Issue by AlbertBronsky** [raycast/extensions#3838]
### Extension

https://www.raycast.com/asubbotin/shell

### Description

Compare how this `man` page looks in Raycast Shell extension output and in the native Terminal.app:
<img width="862" alt="Screenshot 2022-12-09 at 10 45 58 AM" src="https://user-images.githubusercontent.com/44101337/206761994-e9f540b4-f618-41d4-8d25-a464f1747163.png">
<img width="682" alt="Screenshot 2022-12-09 at 10 45 42 AM" src="https://user-images.githubusercontent.com/44101337/206762006-bb7c14e0-c6d7-427b-9d39-7d9e6cd574e6.png">

### Steps To Reproduce

Execute Shell Command -> `man sysctl`

### Current Behaviour

Shows duplicated characters in section titles

### Expected Behaviour

Should show each character just once

**Comment by KELiON** [comment]
@albertbronsky thanks for reporting! As I see these duplicate characters appear for bold fonts in terminal. 

There is no purpose to implement in the extension all features that terminal-like applications include (different fonts/colors, user inputs), so I'll try to process output of shell commands to make it "plain text".
