### ISSUE TITLE
[Obsidian] Typing in the Search Note search field does not keep up with keyboard typing

### ISSUE THREAD

**Issue by apg-dev** [raycast/extensions#3840]
### Extension

https://github.com/raycast/extensions/tree/5e943fdf8aaf8b3dac1d082951f18a05f1ae162c/extensions/obsidian/

### Description

Typing in the Search Note search field doesn't seem able to keep up with entry. For instance, just typing a word like `signature` ... as soon as I type the fourth letter `n` the cursor auto-backspaces and removes what I typed. I don't have a particularly large vault (3000 files, total of 600MB). 

### Steps To Reproduce

1. Cmd-spacebar to open Raycast
2. Type `Obsidian Search Note` which pulls up the list of vaults (my vault and the Obsidian sandbox vault)
3. Select primary vault 
4. Start typing search text. Any words longer than three characters start auto-backspacing and removing search text.

I've seen this on Monterey and Ventura. Apple M1 Max with plenty of memory.

Thank you for considering a fix for this.

**Comment by marcjulianschwarz** [comment]
Can be closed, see #3622

**Comment by apg-dev** [comment]
Thank you for linking; I hadn't seen the other ticket.
