### ISSUE TITLE
[Apple Notes] ...

### ISSUE THREAD

**Issue by AndreKucharzyk** [raycast/extensions#3854]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

I beg you to add search throughout the whole note bodies instead of just title.
This is 1 of the 2 things in Raycast that are still implemented worse than in Alfred.

**Comment by ron-myers** [comment]
Sure. A few people have asked recently.  I will get this in place before the end of the year.

**Comment by ron-myers** [comment]
This is a duplicate of #3207 and can be closed.
