### ISSUE TITLE
[Bunch] "Search Bunches" command type-a-head noch longer working

### ISSUE THREAD

**Issue by flegfleg** [raycast/extensions#3855]
### Extension

https://github.com/raycast/extensions/tree/5230594fc0985a5739c11b643da9bf1b3cba80c7/extensions/bunch/

### Description

Hi, 
the type-a-head filter of the "Search Bunches" command stopped working a few weeks ago, i have to select the bunch manually. 

Thanks!

### Steps To Reproduce

macOS 12.6.1

1. Open RayCast
2. hit "Search bunches"
3. Type something

### Current Behaviour

 the list is not filtered

![CleanShot 2022-12-11 at 13 13 43@2x](https://user-images.githubusercontent.com/4009931/206903044-be9f090d-5a40-45ac-84b4-938079d1b6b5.jpg)

![CleanShot 2022-12-11 at 13 14 01@2x](https://user-images.githubusercontent.com/4009931/206903125-9da6764d-d2e3-4bed-9df6-b210f0fd3127.jpg)

### Expected Behaviour

the list should be filtered

**Comment by pernielsentikaer** [comment]
Can you upload a screencast of this? I was not able to reproduce it

**Comment by flegfleg** [comment]
I have no idea what changed, but now it is working again. 
Thanks for your time!
