### ISSUE TITLE
[HubSpot] Add companies search and global search

### ISSUE THREAD

**Issue by bbrandtom** [raycast/extensions#3857]
### Extension

https://github.com/raycast/extensions/tree/bfd0d3272ed685621fb0d22172650bbf7e0323c6/extensions/hubspot/

### Description

First of all, thank you very much for this extension!

I would like to request two things - 
 1. Being able to search for "companies".
 2. Being to have a global search to search over all data.

**Comment by harisvsulaiman** [comment]
@bbrandtom Search for companies is coming soon.
