### ISSUE TITLE
Cannot use space in search bar; typing input very slow [Bible] ...

### ISSUE THREAD

**Issue by aaronjz** [raycast/extensions#3866]
### Extension

https://github.com/raycast/extensions/tree/aae0455d73bf770ec0c78eed27186793208deded/extensions/bible/

### Description

Just recently noticed typing is very slow when "searching while typing" is enabled. That hasn't been the case for me in the past. Nothing on my macOS has changed. Also, when I use the space bar on the keyboard, the search box does not accept spaces. 

Using macOS Monterrey 12.6.1 with Raycast v1.44.0.

### Steps To Reproduce

1. Open Raycast extension with searching while typing enabled.
2. Type in the search bar.
3. Notice slow typing input.
4. Notice no spaces being accepted in the search bar.

### Current Behaviour

Slow input reception of characters. Search bar not accepting spaces. 

### Expected Behaviour

Search bar should be able to accept characters at a normal typing response; should accept spaces.

**Comment by josmithua** [comment]
@aaronjz thanks for reporting, I've noticed this too recently... Nothing has changed in my code, so some update to Raycast must be affecting it. I'll look it into it when I have some time, hopefully this weekend.

Cheers!
