### ISSUE TITLE
[Arc] Create new Arc window

### ISSUE THREAD

**Issue by kandros** [raycast/extensions#3869]
### Extension

https://www.raycast.com/thomas/arc

### Description

It would be nice to create a new Arc window from Raycast. (like in the video below)

Usecase? opening a new window does so in the current space. 

The current way is either
to select an Arc window, press CMD+N and move that to the desired window, or use the mouse. Both are not great.

https://user-images.githubusercontent.com/4562878/207278055-5a1e75c6-2d75-4679-9cb5-b2db189bec66.mp4

**Comment by thomaspaulmann** [comment]
This would be indeed nice. Unfortunately we rely on Arc's functionality for this. So we're blocked until they support it.

**Comment by kandros** [comment]
I wasn't aware Raycast script existed until today I was able to create one with a very simple applescript command

```
tell application "Arc"
	make new window
	activate
end tell
```
![CleanShot 2022-12-13 at 21 16 20](https://user-images.githubusercontent.com/4562878/207435198-6626c31e-469f-43ed-9a8d-4455c8a3c755.gif)

**Comment by thomaspaulmann** [comment]
Oh yeah it is. If you just want to open a new window, then that should be enough. Maybe you can add it as a separate command to the extension? You can use `runApplescript` to execute your logic. There are plenty of examples in the repository.

**Comment by thomaspaulmann** [comment]
Can you also set the window's URL via AppleScript? Might be handy to have an action in the Arc extension to open a URL in a separate new window.
