### ISSUE TITLE
[Extension Feature Request] Extend Gitlab MR request query with scope=all parameter

### ISSUE THREAD

**Issue by sattellite** [raycast/extensions#387]
# Extension – [Gitlab](https://github.com/raycast/extensions/tree/main/extensions/gitlab)

Authors: @tonka3000 @dai-shi 

**Describe the feature and the current behavior/state.**

I cannot get all merge requests with review assigned to me at all. This is feature of Gitlab API described at documentation. By default API request returns only merge request created by the current user.

Info from [Gitlab API documentation](https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests):

> Get all merge requests the authenticated user has access to. By default it returns only merge requests created by the current user. To get all merge requests, use parameter scope=all.

To fix this issue all you have to add one parameter to query in API request `scope=all`.

Place to add scope parameter in component `reviews.tsx`:

https://github.com/raycast/extensions/blob/1a043b68183d3afb94a3d987df1ed915262403a7/extensions/gitlab/src/components/reviews.tsx#L74-L79

**Who will benefit with this feature?**

This fix will allow get all merge request assigned to current user.

**Comment by mattisssa** [comment]
Hey @tonka3000! 
💎 Here is the new feature request to your extension, take a look at that and subscribe to don't miss anything related 😉

**Comment by tonka3000** [comment]
Thanks for the report and fix suggestion @sattellite
