### ISSUE TITLE
[GitLab] unable to pull data from gitlab.com

### ISSUE THREAD

**Issue by Tylopilus** [raycast/extensions#3872]
### Extension

https://github.com/raycast/extensions/tree/7cf0d190bc2c2aea72da0beaff72a23392dd844a/extensions/gitlab/

### Description

The gitlab extension does not pull any data from https://gitlab.com. Every command is stuck in a refresh state and nothing ever happens.

Things I have tried:
* Generate a new PAT with api access
* Generate a PAT with read only access
* Uninstall extension and reinstall extension

The PAT works fine when used in postman, either with ?private_token=... or as a Bearer.

### Steps To Reproduce

Install Extension
Define gitlab instance as https://gitlab.com
Enter PAT
Open any gitlab command

### Current Behaviour

Commands are stuck in a fetching state

### Expected Behaviour

Does whatever the command should do

**Comment by Tylopilus** [comment]
Additionally the PAT claims it was never used when I check the `last used` state on gitlab.com

**Comment by tonka3000** [comment]
@Tylopilus seems like network connection issue, maybe slow connection. gitlab.com works fine on my machine.

Try to copy the url into your browser https://gitlab.com/api/v4/projects?search=&min_access_level=30&per_page=100&page=1

Do you get some data?

**Comment by Tylopilus** [comment]
Yes the data is coming back fine from the url directly. It does not seem to be an issue with gitlab itself but with the extension. 

Now it does work but I am in a different network. So might be something on my home net that is having issues. Github is working fine tho in both networks.

**Comment by x10** [comment]
I'm having the exact same issue for about 3 weeks.

`Cannot search Merge Requests: Error: Unauthorized`

<img width="979" alt="Screenshot 2023-01-05 at 2 11 14 PM" src="https://user-images.githubusercontent.com/99417/210880812-94c453f7-dbad-41bc-ace7-77e687301d4b.png">

**Comment by tonka3000** [comment]
@x10 which scopes do you have assigned to your personal access token?

**Comment by z4f1r0v** [comment]
I have the same issue. I have `api` and `read_api` scopes in place.

**Comment by rafael-yure** [comment]
I'm having the exact same issue; however, an error is never shown. The extension just keeps loading and loading and nothing happens. I've tried to re-generate tokens, uninstall and install again... everything. Nothing seems to work.

**Comment by tonka3000** [comment]
@rafael-yure which command did you use?
