### ISSUE TITLE
[Hue] ...

### ISSUE THREAD

**Issue by ajsz** [raycast/extensions#3873]
### Extension

https://www.raycast.com/pindab0ter/hue

### Description

"Too many requests sent" error message wheny trying to control any lights with the extension.

**Comment by pindab0ter** [comment]
I have encountered, but never been able to reliably reproduce this bug.

I would like to move this extension to the [Hue API V2](https://developers.meethue.com/develop/hue-api-v2/). This might solve that problem. I don't know when I'll have the time to do that.

In the meantime, if you can manage to reliably reproduce the error, that'll help with finding a fix.

**Comment by ajsz** [comment]
Hi @pindab0ter is there any way I can provide some debug data to you that could help identifying this issue?

**Comment by pindab0ter** [comment]
Sure, you can (anonymize your data and) post it here!

**Comment by pindab0ter** [comment]
This has been solved in #4929 and further improved on in #5868.
