### ISSUE TITLE
[Recents] The new downloads are not being displayed in Recent Downloads

### ISSUE THREAD

**Issue by AndreKucharzyk** [raycast/extensions#3874]
### Extension

https://www.raycast.com/GastroGeek/recents

### Description

I'm not sure when and why it happens, but more often then not, the files that I'm downloading aren't visible in Raycast "Recent Downloads" even though they visible in the Download folder in Finder.

**Comment by AndreKucharzyk** [comment]
Im starting to wonder whether I should give up on this extension :(

**Comment by agileadam** [comment]
+1 on this. There isn't a clear cutoff on the last files that show up. I am seeing one file from yesterday, then a big gap, then a bunch of files from many days ago, etc.

**Comment by mickaelperrin** [comment]
Issue is still present. The "recent" downloads is just unusable
