### ISSUE TITLE
[Browser History] Add support for Arc Browser

### ISSUE THREAD

**Issue by jonathanlaniado** [raycast/extensions#3876]
### Extension

https://www.raycast.com/crisboarna/browser-history

### Description

Add support for [Arc Browser](https://arc.net/).

### Who will benefit from this feature?

All Arc users 😊

**Comment by crisboarna** [comment]
Hi @jonathanlaniado,

I am open to include Arc in this but I cannot implement/test it as I am only on the waitlist. Would need to wait for access to the close beta to be able to work on it.
