### ISSUE TITLE
[Hypersonic] Allow adding body to created todo

### ISSUE THREAD

**Issue by mxstbr** [raycast/extensions#3884]
### Extension

https://www.raycast.com/reboot.studio/hypersonic

### Description

I often link back to where the todo came from (e.g. Slack message) in the body of the Notion card:

<img width="570" alt="CleanShot 2022-12-14 at 06 22 31@2x" src="https://user-images.githubusercontent.com/7525670/207620853-ea7348af-45ef-4f31-975b-70772f895972.png">

I would appreciate if I could do that immediately when creating a todo from Hypersonic, rather than having to add it to the title.

### Who will benefit from this feature?

Everybody using Hypersonic this way

**Comment by mxstbr** [comment]
cc @igarcido95

**Comment by igarcido95** [comment]
I'm identified with this use case.

Probably we can detect URLs from the title and include them in body.

**Comment by mxstbr** [comment]
I wonder if there's an even more general solution, sometimes I also add text to the body 🤔 

Maybe something like `Create todo #personal body: This is the body slack.com/bla`?

**Comment by mxstbr** [comment]
FWIW, my previous self-made extension had a dedicated form field for the body:

![CleanShot 2022-12-14 at 10 48 37@2x](https://user-images.githubusercontent.com/7525670/207685784-a1426915-4b18-4ea5-a7e0-e6434ccb613a.png)

I know that that won't work with the central search bar creation UX, but just for reference. :)

**Comment by mxstbr** [comment]
Maybe there's a different separation that would work well (e.g. `Create todo #personal // This is the body slack.com/bla`), or maybe there's a diff solution that a separator that fulfills the same use case :)  Just throwing ideas around!

**Comment by igarcido95** [comment]
![CleanShot 2022-12-15 at 18 03 07](https://user-images.githubusercontent.com/42417619/207922679-8e9a63e5-b0db-4c7a-8ff4-3e18dbf8663a.png)

This is our suggested approach. Using an optional URL field in Notion database where we would save links. This way we can parse and open URLs directly from Hypersonic.

Thoughts?

**Comment by mxstbr** [comment]
Love that solution! I went through all my existing todos with bodies, and all of them have (mainly) a URL backlink as a body 👍

**Comment by igarcido95** [comment]
Hey @mxstbr, this is live in the last release ✌️

**Comment by mxstbr** [comment]
Doesn't seem to work for me? I just did "Update all extensions," so I must be on the latest published version 🤔 

![CleanShot 2023-01-05 at 13 40 21@2x](https://user-images.githubusercontent.com/7525670/210782420-42edc58d-2310-4246-b77b-57d5778fb7ec.png)

**Comment by igarcido95** [comment]
Hey @mxstbr,

If you are in the latest version, make sure to map URL field with a URL property in your Notion DB.

![CleanShot 2023-01-05 at 13 42 19@2x](https://user-images.githubusercontent.com/42417619/210783124-7de20a0d-77a6-4d3c-9c6c-4185a2f9cd66.png)

**Comment by mxstbr** [comment]
Ahhh! That worked, thank you 🙌
