### ISSUE TITLE
None of the Cleanshot extension actions work

### ISSUE THREAD

**Issue by danvpeterson** [raycast/extensions#3885]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

Trying to use any of the actions from the Cleanshot extension just does nothing (hit return, Raycast does not go away and nothing happens). I don't know if it makes a difference, but I have Cleanshot installed via Setapp.

**Comment by Aayush9029** [comment]
@danvpeterson 

`cleanshot://capture-area`

Paste that in safari! What happens?

**Comment by danfigmatokens** [comment]
Apologies, I've discovered that this is a wider issue, not just related to CleanShot but to Raycast extensions as a whole. I've filed a separate bug report for that, this one can be closed.
