### ISSUE TITLE
[plausible-analytics] Add a basic time filter

### ISSUE THREAD

**Issue by thebrokenfinger** [raycast/extensions#3886]
### Extension

https://www.raycast.com/thebrokenfinger/plausible-analytics

### Description

Hey! A user reached out to me with a feature request to add a basic time filter in the extension.

**Current Behavior:** The analytics data is shown for the past 30 days (and the user cannot change it).

**Expected Behavior:** The user should be able to add a basic time filter (ex. _Today_, _Last 7 days_, _Last 30 days_, _All time_).

I'm opening this issue for discussing what would be the best way to implement this. Should it be a new command, or be placed in `cmd+k` menu, or anything else? 
I'm also thinking that the user's preference would apply to all the websites she's tracking until she changes the time filter again.

### Who will benefit from this feature?

All the users :)

**Comment by thebrokenfinger** [comment]
@pernielsentikaer Any ideas on this? 🙂

**Comment by pernielsentikaer** [comment]
What about having a [List.Dropdown](https://developers.raycast.com/api-reference/user-interface/list?q=list#list.dropdown) where its possible to change the period?
