### ISSUE TITLE
[Spotify] Allow connecting to other players

### ISSUE THREAD

**Issue by robrecord** [raycast/extensions#3891]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Could the extension please allow you to choose which player to control?

Example: I would prefer to use [spotifyd](https://github.com/Spotifyd/spotifyd) than the official player. Other times I might want to control Spotify on my TV, or my Raspberry Pi with speakers.

### Who will benefit from this feature?

Everyone who uses an alternative player or another device (such as smart speaker).

### Anything else?

I believe this is possible - [spotify-tui](https://github.com/Rigellute/spotify-tui) for example allows connecting to any available player on the network.

**Comment by mattisssa** [comment]
@raycastbot reopen the issue since the feature (#4487) waits for the Spotify team approval on the required scope
