### ISSUE TITLE
Local cache of bookmarks for speed

### ISSUE THREAD

**Issue by HemalR** [raycast/extensions#3894]
### Extension

https://www.raycast.com/lardissone/raindrop-io

### Description

Thanks for the great extension. Really helps fill in the gap in Arc (great browser, but severely lacking in the bookmarking department).

One thing - Each 'search' is happening remotely, it would be super performant and useful to cache the data locally and show results based on local data, overwriting them with server data as the network request comes in.

Is that possible? Not sure what kind of data storage facilities the Raycast extension APIs allow.

### Who will benefit from this feature?

Everyone using Raindrop via Raycast

### Anything else?

Thanks regardless of whether this can be implemented 👍

**Comment by lardissone** [comment]
@HemalR I've been doing some tests and there are some drawbacks on having the bookmarks cached locally. Search can only work on title and tags (or any other [exposed property](https://developer.raindrop.io/v1/raindrops) in the bookmark) while the API does a [full-text search](https://help.raindrop.io/using-search/#full-text-search) within the links and PDFs content (if you have a PRO account).

**Comment by HemalR** [comment]
**_I would like to have this updating in the background instead of a dedicated command to update bookmarks._**

I was going to suggest this as a not so great option 😬. I think the manual option could still be a useful option but can be designed as something that isn't necessary unless a forced re-sync is required.

I imagine the extension is using the [search endpoint](https://help.raindrop.io/using-search/#operators) to generate results?

The non-manual workflow that I can think of:

1. Sync with local storage during initialisation (this would, by design, be slowish)
2. Any search after set up can default to a fuzzy search of the local db, adding in server results as they come in (if the user hasn't already made a selection from the local results at that point)
3. Resync server and local storage periodically- maybe defaulting to once an hour/once a day? Not sure how their rate-limits will allow this. This could possibly be made more performant by utilising the 'created' sort option from their API to sync only new bookmarks since the previous sync.

The challenge would be how to resync removed bookmarks... The forced manual full resync could come in handy for that. I don't imagine it is something that would be often used.

I might poke around your source code and see if I can get any ideas.

**Comment by HemalR** [comment]
> @HemalR I've been doing some tests and there are some drawbacks on having the bookmarks cached locally. Search can only work on title and tags (or any other [exposed property](https://developer.raindrop.io/v1/raindrops) in the bookmark) while the API does a [full-text search](https://help.raindrop.io/using-search/#full-text-search) within the links and PDFs content (if you have a PRO account).

Ah yeah, that makes sense. I guess the question would be whether the 'instant results' would be worthwhile. I.e. - What % of searches could be fulfilled with those limitations in place?

My feeling is that it would still be useful (90% plus of my searches would return the right result based on the title) but that is a single point of reference and might not apply to most Raindrop users. No idea.

**Comment by lardissone** [comment]
Thanks for your suggestions.

I just asked Raindrop developer if there's an API endpoint to get the add/delete/updates instead of re-sync all the bookmarks again. If that's possible, that will be easier to implement.

I like your suggestion of immediately display the local cached bookmarks based on title/tags search and hydrate results with the ones returned from the API as soon as they returns. Not sure how to implement that without a noticing glitch, because I would prefer API results first.

**Comment by HemalR** [comment]
Ah right, yes hydrating the results suddenly could cause a user to select the wrong bookmark. I can't think of a way off the top of my head to make that smooth. 

The closest workflow I can think of to make the workflow smooth:

1. User begins typing their search term. Local results show up as typing is in progress.
2. API results are NOT fetched straight away, instead fetched using a debounced function that resets on each keypress. That way, if the user begins arrowing down to a result, hydration will effectively be stopped and user won't end up hitting 'enter' right as hydration occurs.
3. Once X amount of time has passed without a keypress- maybe 600-800ms - then an assumption can be made that the user is not seeing the result from the local results they would like. At this point, make the network request and show this on the UI (a loader or a 'fetching more results' text) so that the user can see that more results are on the way.
4. Hydrate the results

**Comment by HemalR** [comment]
@lardissone 

I think you made some changes already?! It's fantastic thank you!

Having local results show as a list even prior to any typing is great 👍

**Comment by lardissone** [comment]
@HemalR it's not persisting all bookmarks but at least it caches the latest results.
