### ISSUE TITLE
[Dev Tools Bug] Command icon doesn't update until Raycast is quit and reopened

### ISSUE THREAD

**Issue by michaelwschultz** [raycast/extensions#39]
Raycast version: 1.25.0

## Description
Changing the command icon after first use requires the app to be restarted to see the new command icon.

## Steps To Reproduce

1. Run `nom run dev` on your extension with a command-icon.png in place. (used one of the example repos)
2. Replace command-icon.png with another image.
3. Run the extension again.
4. Shut down dev sever.
5. `npm run dev`
6. Still no luck.

## The current behavior
Command icon doesn't update when it's changed.

## The expected behavior
Shutting down the dev server and spinning it back up should update the icon. Or better yet, hot reload updates it as well.

**Comment by fe9lix** [comment]
Correcting the stale bot ;): Will be fixed with the next release.
