### ISSUE TITLE
[Figma File Search] Support for multiple teams

### ISSUE THREAD

**Issue by sofiasmnk** [raycast/extensions#3901]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

Currently the extension only supports searching files within one Figma team. As someone who is in multiple teams in one same Figma account, I would like to be able to search files from all my teams.

### Who will benefit from this feature?

Anyone with multiple Figma teams.

**Comment by Christopher-Hayes** [comment]
Duplicate of #373

**Comment by michaelwschultz** [comment]
Update: This was added by @GLaDO8 https://github.com/raycast/extensions/pull/6490 🎉
