### ISSUE TITLE
[Timers] can timer name show up in pop-up notification

### ISSUE THREAD

**Issue by clydebaron2000** [raycast/extensions#3906]
### Extension

https://www.raycast.com/ThatNerd/timers

### Description

Timer currently shows a pop-up notification and voices out the timer title's contents but does not show these contents in the notification.

### Who will benefit from this feature?

Anyone who used timers that does not necessarily has sound/headphones on.

**Comment by ThatNerdSquared** [comment]
Thanks for the feedback @clydebaron2000 - I'm not sure how I missed that, will be adding it shortly 👍

**Comment by ThatNerdSquared** [comment]
I've fixed this in #3999.

**Comment by pernielsentikaer** [comment]
Merged! 🧑‍🚒
