### ISSUE TITLE
[Arc] - Ability to switch to open tabs

### ISSUE THREAD

**Issue by altryne** [raycast/extensions#3909]
### Extension

https://www.raycast.com/thomas/arc

### Description

The description says 

"Search and quickly navigate Arc's history and open tabs." so this does search open tabs in Arc

But it doesn't switch to them, just opens them in Mini Arc?

Would be cool if this shows which tabs are open and then upon hit, switches to them

### Who will benefit from this feature?

All Arc users

**Comment by thomaspaulmann** [comment]
Would love that but unfortunately it isn't possible with AppleScript yet. Waiting for the Arc team to implement it.

**Comment by thomaspaulmann** [comment]
Actually it does switch to open tabs. Closing this issue.
