### ISSUE TITLE
GLOBAL_AGENT.HTTP_PROXY configuration value: URL protocol must be http:

### ISSUE THREAD

**Issue by Moeyua** [raycast/extensions#3910]
### Extension

https://www.raycast.com/krzysztofzuraw/search-mdn

### Description

![image](https://user-images.githubusercontent.com/45156493/208045141-785f7230-1e93-4498-a2fe-802848520ebf.png)

### Current Behaviour

Use proxy setting with system Petwork Preference.
![Uploading image.png…]()

### Expected Behaviour

It seems a duplicate of  https://github.com/electron/get/issues/215.

**Comment by mathieudutour** [comment]
What's the URL you are trying to set as the proxy? (the screenshot of the preferences didn't upload)

**Comment by Moeyua** [comment]
> What's the URL you are trying to set as the proxy? (the screenshot of the preferences didn't upload)

![image](https://user-images.githubusercontent.com/45156493/208047751-7198a554-bbc7-486e-b553-90cbf9116afe.png)

**Comment by mathieudutour** [comment]
can you check in v1.45.1 to see if it's fixed?

**Comment by Moeyua** [comment]
> can you check in v1.45.1 to see if it's fixed?

<img width="746" alt="image" src="https://user-images.githubusercontent.com/45156493/208282678-11360e32-8f63-4432-a775-08e8567923cd.png">
It's still have problem 😢

**Comment by fe9lix** [comment]
@Moeyua The proxy server URL must use the http protocol (in your screenshot there's https), but there's still currently a bug so you can try again with the next release end of the week.

What kind of local proxy are you using? Could you point us to the tool or source code in case it's an OSS project?

**Comment by Moeyua** [comment]
Thank you for your hard work.
I'm using [Surge](https://nssurge.com/) as my system proxy.

**Comment by fe9lix** [comment]
Thanks! I've just tested it with Surge and it's going to work with the next release. (No need to change any proxy settings.)

**Comment by mathieudutour** [comment]
Should be fixed now!
