### ISSUE TITLE
[Asana] ... Cannot create a task when "Project" field is populated

### ISSUE THREAD

**Issue by stanty522** [raycast/extensions#3915]
### Extension

https://www.raycast.com/raycast/asana

### Description

When trying to create a task where the "Project" field is populated, nothing happens. There is no error code. Pressing command+return does nothing. Clicking "Create task" does nothing.

Only when you keep "Project" field blank can a task be created.

### Steps To Reproduce

1. In Create Task environment
2. Populate the task fields
3. Add a project to the project field
4. Press "Create task"

**Comment by thomaslombart** [comment]
So after taking a look, it seems like it's not specific to Asana's source code. For some reason, adding `storeValue` to a `Form.TagPicker` item makes it impossible to submit the form. Maybe it's linked to the latest Raycast release (v1.45).

I'm asking that to the Raycast team and will let you know.

**Comment by thomaslombart** [comment]
The team will take a look at it next Monday. Sorry for the inconvenience 🙇‍♂️

**Comment by mathieudutour** [comment]
it should be fixed in v1.45.1
