### ISSUE TITLE
[Asana] Can't create a task for some projects

### ISSUE THREAD

**Issue by wyrwigruz** [raycast/extensions#3923]
### Extension

https://www.raycast.com/raycast/asana

### Description

I don't know why but for most of my projects adding task is not working. After pressing cmd+Enter nothing happens or Raycast crashes and quits. 

https://user-images.githubusercontent.com/22954960/208127203-5e77db07-96bb-42a0-af5a-562f66d810cd.mov

### Steps To Reproduce

1. Use Create Task Command
2. Select project
3. Set Task name
4. Press Command+Enter

### Current Behaviour

Nothing happens or Raycast crashes

### Expected Behaviour

Task is created

**Comment by mathieudutour** [comment]
it should be fixed in v1.45.1
