### ISSUE TITLE
Create Image From Code

### ISSUE THREAD

**Issue by craigz** [raycast/extensions#3926]
### Extension

https://www.raycast.com/garrett/ray-so

### Description

Running the `Create Image From Code` script results in a browser opening a generic page at dub.sh showing a rotating globe annotated with the text: "This map shows the locations of the last 50 clicks on [ray.so](https://ray.so/) in real time." rather than the expected code screenshot. The url seems to contain the expected content ex:
`https://ray.so/?theme=candy&background=true&darkMode=true&spacing=16&title=dailyNotes%20Stats&code=[redacted]&language=auto`.  

I've just reinstalled the script and running it again provided a dialog box where i filled in entries such as the title, theme, spacing, code, etc and all of those values are properly represented in the URL (above) however no image is ever created just the marketing page for dub.sh is displayed.

### Steps To Reproduce

- running the latest raycast with the `create image from code` extension reinstalled.
- invoke raycast.
- select `create image from code`.
- enter options in displayed dialog.
- submit request using `command` + `enter`

### Current Behaviour

- bathe in the light of a shiny 3rd party link aggregator's marketing page.

### Expected Behaviour

- an image of the pasted (or from clipboard) code.

**Comment by RSO** [comment]
There were some issues over the weekend with our DNS settings that caused ray.so to be pointed to a different service. We're investigating how this could've happened and have fixed the routing once again. Thank you for reaching out!
