### ISSUE TITLE
[API Feature Request] QuickLook

### ISSUE THREAD

**Issue by es183923** [raycast/extensions#393]
add a function to show the QuickLook preview of a file/folder

**Describe the feature and the current behavior/state.**

Currently, we can use `qlmanage` to show a different quicklook window, but it is very different from the one that Finder shows. Adding this function allows us to use the Finder QuickLook instead.

**Will this change the current api? How?**

adds a `showQuickLook(file: string)` function

**Who will benefit with this feature?**

developers and users

**Any Other info.**

**Comment by thomaspaulmann** [comment]
Seems like this is a duplicate of #367. Gonna close that one to keep the discussion in one place. Thanks for propsing an API 👏

**Comment by mathieudutour** [comment]
Duplicate of #367
