### ISSUE TITLE
Markdown Images Don't Render Correctly

### ISSUE THREAD

**Issue by saivan** [raycast/extensions#3933]
Raycast version: 1.45.1

## Description

I've made an extension that can render equations from latex or asciimath and it is ALMOST working 😂 I can actually render the equation as an "icon" (which you can see on the left) but when I place the image into the markdown, the image doesn't show up at all:

<img width="886" alt="Screenshot 2022-12-17 at 5 25 00 pm" src="https://user-images.githubusercontent.com/8543370/208228678-686c18b3-f973-4a2f-9661-82e8e94f83b4.png">

The produced markdown by my code is:

```
  # This is the image
  <img src="http://localhost:38245/typeset?string=&&asciimath=true&inline=true" />
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/800px-Image_created_with_a_mobile_phone.png" />
```

The extension itself runs a local express server to serve the svgs (which is necessary to show the markdown). When I try this produced code with any markdown renderer (like stack edit), the image of the equation shows up correctly:

<img width="1925" alt="image" src="https://user-images.githubusercontent.com/8543370/208228816-05e8efb3-7292-428b-b618-11ad661aa60b.png">

I've put this [repo up onto github](https://github.com/saivan/raycast-math-typeset) if you'd like to see the problem yourself. But it looks like I'm a little blocked here. I get no feedback as to why this image is not rendering. 

## Steps To Reproduce

1. Clone the github repo I've shared
2. Run `npm run dev` 
3. Run the extension and just type any equation (like e^x)
4. You should see the icon as shown above, but the image in the markdown won't render - I'm unsure about why

## The current behavior

The rendered image (svg) doesn't show up on the page

## The expected behavior

The image should show up on the page

**Comment by JonathanWbn** [comment]
I can imagine there is an issue with including non-SSL links in the markdown (`http` instead of `https`). I tried some other http-links in your example repo and they all didn't work while all https-links did work.

I would suggest trying to avoid hosting your own server altogether. I believe you could just do whatever you do behind the API directly from the extension component.

**Comment by saivan** [comment]
Well, the fact that its displaying in the icon field but not displaying in the markdown is a little bit curious isn't it? I'd argue that there isn't a huge problem with displaying http links unless I'm missing something, so I would consider this a bug, wouldn't you?

There's no real problem with hosting a server either is there? I tried doing this with the API directly, but there were quite a few issues with MathJax that I didn't want to debug. This approach works really well, and it also gives me a DOM environment that I can use to export images through the context menu later.

**Comment by JonathanWbn** [comment]
> Well, the fact that its displaying in the icon field but not displaying in the markdown is a little bit curious isn't it?

Sanitizing markdown for security risks is common while an icon URL is usually not sanitized. Seems normal to me.

> There's no real problem with hosting a server either is there?

Sure, it's fine if it works. But IMO this problem you are reporting is a downstream effect of this server-approach.

**Comment by saivan** [comment]
Okay, well perhaps I'm missing an approach that could work here, so I'd be very happy to look into an alternative approach. 

Do you see some other approach that I could take that wouldn't require me to host a full time server for something like this? I don't really want to maintain an online server, and it would lose the benefit of being useful offline.

**Comment by saivan** [comment]
@JonathanWbn I actually decided to put this to the test so I [provisioned an ssl cert for localhost and made the server a https server](https://github.com/saivan/raycast-math-typeset/commit/c83412a6ed8e3bc5b750ec00f2057cec5f87ee6e). I can confirm, that this did not fix the problem. I really do think there might be something going awry with the image rendering, because if you open the extension and just navigate to

```
https://localhost:38245/typeset?string=3x%2B4&&asciimath=true&inline=true
```

You'll see that it works fine. It also works fine on every other markdown renderer I've tried.

**Comment by saivan** [comment]
Yea [I just tried that too](https://github.com/saivan/raycast-math-typeset/commit/620fd3095a2fbd0983471445388848b17345d96b), no dice either. Really looks like it just doesn't want to render math 😂 It's a shame, this would be a very useful extension. I was hoping to make many more image generators (like svg generators etc)

**Comment by saivan** [comment]
My next question would be - could it somehow be related to the viewbox - or the default css that is being applied to the svg. Because it is pretty clear that "something" is showing up

<img width="886" alt="image" src="https://user-images.githubusercontent.com/8543370/209141039-f6eb700c-7b3a-4d84-9b39-195e695fc3d1.png">

I just can't debug this because I don't really have any dev tools

**Comment by saivan** [comment]
Okay, so it (looks like this approach works)[https://github.com/saivan/raycast-math-typeset/commit/25018adf3c39cb250b6e3102070abfff097b541a]. Thanks so much for your help:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/8543370/209143553-de8f1f1e-9612-4100-8ee3-b2671e174d23.png">

It's going to be a little trickier exporting this as a png and there are some other issues to debug. But this is great progress.

**Comment by JonathanWbn** [comment]
@saivan Awesome! 🎉 

So was this the case all along?

**Comment by saivan** [comment]
I do believe it was yes. I think the problem that occurred was that mathjax outputs the width and height in ems (you can see in the commit that I modified the svg attributes manually). So it likely wasn't playing nice with your default font size

**Comment by JonathanWbn** [comment]
Hah, that's interesting.
So then this issue can be closed, eh?

**Comment by saivan** [comment]
Yep, let's close it

**Comment by saivan** [comment]
Thanks so much for your help :)
