### ISSUE TITLE
[World Clock] Allow to change date format to dd/mm/yyyy

### ISSUE THREAD

**Issue by dpthegrey** [raycast/extensions#3934]
### Extension

https://www.raycast.com/koinzhang/world-clock

### Description

Currently this extension only has default date format as mm/dd/yyyy. We need to be able to set and change to dd/mm/yyyy

### Who will benefit from this feature?

Every other user who is not using mm/dd/yyyy format will benefit to get the dd/mm/yyyy.

**Comment by koinzhang** [comment]
Hi @dpthegrey. Thanks for your feedback, I submitted a [PR](https://github.com/raycast/extensions/pull/4086) to add more date formats and now there are three date formats to choose from: YYYY-MM-DD, MM/DD/YYYY, DD/MM/YYYY
