### ISSUE TITLE
[Linguee] It often happens that I've got this message

### ISSUE THREAD

**Issue by kud** [raycast/extensions#3935]
### Extension

https://www.raycast.com/geekdada/linguee

#### Error:
```
Error: getaddrinfo ENOTFOUND www.linguee.com

GetAddrInfoReqWrap.onlookup:node:dns:107:26
```

**Comment by geekdada** [comment]
Hey @kud,

Are you able to open https://www.linguee.com in any browser at the moment when it prompts you that error?

This error normally happens when your local network is having some issues, especially DNS issues.

**Comment by kud** [comment]
It does not happeny every time. Either we spam the API either I've gost some lost packets.

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/655838/208240135-c6668908-5304-4a7e-abd1-4777a9e7a549.png">

**Comment by geekdada** [comment]
It doesn't seem like spamming the API.

**Comment by kud** [comment]
Alright, let's close it then. :)
