### ISSUE TITLE
[One Thing] Clicking on the menu bar multiple times open a new raycast window

### ISSUE THREAD

**Issue by kud** [raycast/extensions#3937]
### Extension

https://www.raycast.com/pernielsentikaer/one-thing

### Description

When you click multiple times on the menu bar about One Thing, it'll open a new raycast window, which leads that you must quit as much the raycast window.

### Steps To Reproduce

1. Set a One Thing sentence
2. See it on the menu bar
3. Click 4-5-6 times on the menu bar on One Thing

### Current Behaviour

It will use multiple instances of One Thing

Video: https://share.cleanshot.com/5WYjWyYHkpg5zuqD3T5j

### Expected Behaviour

Having just one instance

**Comment by pernielsentikaer** [comment]
Hi @kud 

Thanks for the report.

This does indeed looks like a bug in the API; I created a bug report internally about this, and I'll update this issue when I have something new regarding this 😊

**Comment by kud** [comment]
Thank you @pernielsentikaer !

**Comment by pernielsentikaer** [comment]
This should be fixed some time ago, closing 😊
