### ISSUE TITLE
[Browser History] Add support for Orion

### ISSUE THREAD

**Issue by joeynotjoe** [raycast/extensions#3941]
### Extension

https://www.raycast.com/crisboarna/browser-history

### Description

Add support for [Orion](https://browser.kagi.com) browser.

### Who will benefit from this feature?

Anyone using Orion, of course!

**Comment by crisboarna** [comment]
Hi @joeynotjoe,

Support has been added.

**Comment by crisboarna** [comment]
@raycastbot close this issue
