### ISSUE TITLE
[Quit Applications] ...

### ISSUE THREAD

**Issue by mattie-g** [raycast/extensions#3948]
### Extension

https://www.raycast.com/mackopes/quit-applications

### Description

The Icon of the application, inline before the name.

### Who will benefit from this feature?

I imagine the majority, it would help with quicker ID of any apps to quit.

**Comment by mackopes** [comment]
Just for visibility: this is a duplicate of the [Issue 4007](https://github.com/raycast/extensions/issues/4007). 
I will look into this in the upcoming weeks when I'll have some spare time

**Comment by mackopes** [comment]
@mattie-g I merged a PR adding this functionality. feel free to check it out and close this task if you feel like this issue has been resolved :)
