### ISSUE TITLE
[Bitly URL Shortener] ...

### ISSUE THREAD

**Issue by pzelnip** [raycast/extensions#3949]
### Extension

https://www.raycast.com/blessanm86/bitly-url-shortener

### Description

Invalid URL on choosing action

### Current Behaviour

When I pick "Shorten URL" I get "Invalid URL": https://cdn.zappy.app/d890347001458b1ad3f3dda4282693e4.png

### Expected Behaviour

Should be able to shorten url successfully.

**Comment by blessanm86** [comment]
You have to have a valid URL in your clipboard before invoking shorten url.

If you are confident it is, u can try calling the api directly and see if it returns an error
https://github.com/raycast/extensions/blob/167496535be8649d4221bedcbaa2f9645611c4cd/extensions/bitly-url-shortener/src/index.tsx#LL25C5-L34C8

**Comment by pzelnip** [comment]
I had `https://www.facebook.com/` copied to my clipboard.  Upon picking "Shorten URL" I got the same "Invalid URL" error in Raycast.  

Upon trying hitting the API directly via Postman, I got 200 OK.

You can see both in this screen recording: https://cdn.zappy.app/v944c9d9440ad7d0bde92f26242b05703.mp4

Let me know if there's any other info I can provide, thanks!

**Comment by blessanm86** [comment]
@pzelnip Seems like ur using raycast clipboard history extension which works a bit differently.
I have updated the extension to use raycast latest API's.
It should start working once my PR gets merged
