### ISSUE TITLE
[Auto Quit App] ...

### ISSUE THREAD

**Issue by defragpro** [raycast/extensions#3954]
### Extension

https://www.raycast.com/koinzhang/auto-quit-app

### Description

I would like more applications, such as photoshop, figma, etc. I like the idea of the Swift Quit.

### Who will benefit from this feature?

I think to many people.

### Anything else?

https://swiftquit.com/

**Comment by koinzhang** [comment]
Hi @defragpro I've updated the extension and it now supports custom applications #6536
