### ISSUE TITLE
[Deepcast] instant replacement of selected text

### ISSUE THREAD

**Issue by philderfuchs** [raycast/extensions#3955]
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

I'd love a command that instantly replaces the selected text with the translated version and closes the raycast window. This would speed up the translation work flow.

**Comment by philderfuchs** [comment]
Is there any update on this? ☺️

**Comment by sebhewelt** [comment]
I'd love that too. I don't know how to use the extension now. It doesn't go inside the command view on click (being in root view)
