### ISSUE TITLE
[Unicode Symbols Search] Tab keys not displayed correctly, only display a question mark

### ISSUE THREAD

**Issue by multivac61** [raycast/extensions#3957]
### Extension

https://www.raycast.com/mmazzarolo/unicode-symbols

### Description

<img width="234" alt="image" src="https://user-images.githubusercontent.com/4436129/208431458-1f3512d2-256b-4a93-9754-a400dd13207d.png">

**Comment by pernielsentikaer** [comment]
I don't think we can do anything about this since I don't think macOS have those two.

We might be able to "remove" them instead so they are not listed since the list is generated automatically.
