### ISSUE TITLE
[Wikipedia] ...

### ISSUE THREAD

**Issue by laune-** [raycast/extensions#3958]
### Extension

https://www.raycast.com/vimtor/wikipedia

### Description

It would be super helpful if you have the option to define in which Wikipedia you want to search. So in most cases i want to search in the german wikipedia, but autosuggestion only works for the english wiki.

**Comment by JonathanWbn** [comment]
This is solved by #3976.

**Comment by JonathanWbn** [comment]
@raycastbot close

**Comment by JonathanWbn** [comment]
@raycastbot close this issue
