### ISSUE TITLE
[Formula 1] Error: Could not load seasons 

### ISSUE THREAD

**Issue by mattie-g** [raycast/extensions#3961]
### Extension

https://www.raycast.com/csigritz/f1-standings

### Description

On any command within the F1 extension the same error is thrown at the bottom of the raycast window "Error Could not load seasons"

### Steps To Reproduce

MacOS 13.0, Raycast 1.45.1

Click any command within the extension, it attempts to load, then displays the error. 

Installed the extension today, even with a restart of raycast and re-installing the extension same issue occurs.

**Comment by csigritz** [comment]
Currently the API (ergast.com) seems to be down

**Comment by mattie-g** [comment]
Closing as the API looks to be up and running now and the extension back to working!
