### ISSUE TITLE
[Figma File Search] keeps failing with "Something went wrong" error pop up

### ISSUE THREAD

**Issue by gunniho** [raycast/extensions#3965]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

I keep getting this error message
<img width="782" alt="Screenshot 2022-12-20 at 08 49 25@2x" src="https://user-images.githubusercontent.com/1255418/208623971-23d9e4af-143c-4f39-8732-21d005e193d0.png">

https://user-images.githubusercontent.com/1255418/208624368-2e683137-f5a3-4d14-a369-a39ce2051e83.mp4

I've tried uninstalling and reinstalling the extension but this keeps happening right at initial opening of the extension

### Steps To Reproduce

open extension
see error message

### Current Behaviour

"Something went wrong" error pop up appears. 

### Expected Behaviour

searching figma works

**Comment by pernielsentikaer** [comment]
We just released a patch that might fix this.

Could you run `Check For Extensions Updates` and try again 😊

**Comment by pernielsentikaer** [comment]
Closing in favor of #3902
