### ISSUE TITLE
[Safari] "Add to Reading List" command opens Safari unexpectedly

### ISSUE THREAD

**Issue by dcastil** [raycast/extensions#3968]
### Extension

https://www.raycast.com/loris/safari

### Description

When I execute the command "Add to Reading List" while the Safari app is closed, the command opens the Safari app but doesn't close it afterwards. I assume that the command needs to open Safari to be able to add an item to its reading list but I'd expect the command to close Safari in case it wasn't open already.

### Steps To Reproduce

1. Make sure Safari app is closed
2. Execute "Add to Reading List" with valid URL
3. Safari stays open after command finished

### Current Behaviour

Safari app stays open after command

### Expected Behaviour

Safari app stays open if it was open before but closes if it wasn't open before the command.

**Comment by dcastil** [comment]
By the way not sure whether this is a bug report or a feature request. 😅

**Comment by thomaspaulmann** [comment]
This is kind of expected because the extension relies on AppleScript to interact with Safari. Unfortunately, these interaction is only possible while the receiving app is open, in this case Safari. I'm clsoing the issue because there isn't an easy workaround for this.
