### ISSUE TITLE
[ BUG ] `Set Audio Device to Favorite` Stopped Working on Ventura

### ISSUE THREAD

**Issue by ibehnam** [raycast/extensions#3972]
### Extension

https://www.raycast.com/benvp/audio-device

### Description

`Set Output device to Favorite` stopped working when I upgraded macOS from Monterey to Ventura. The other command `Set Output Device` works though.

### Current Behaviour

Responds with "Favorite Output Audio Device Could not be Set."

**Comment by yigitkonur** [comment]
It would be fantastic if we could get this fixed - I used to be able to use it, but now it's not functioning properly.

**Comment by machielkreiken** [comment]
+1

**Comment by Aiee** [comment]
+1

Seems the apple script used below is incompatible with Ventura.
https://github.com/raycast/extensions/blob/653fa82fd1db7aa5ca74f1072acf3a628c486c1f/extensions/audio-device/src/utils.tsx#L60-L82

**Comment by ibehnam** [comment]
> +1
> 
> Seems the apple script used below is incompatible with Ventura.
> 
> https://github.com/raycast/extensions/blob/653fa82fd1db7aa5ca74f1072acf3a628c486c1f/extensions/audio-device/src/utils.tsx#L60-L82

Were you able to find a solution?

**Comment by andy2mrqz** [comment]
I also hit this today.  From a glance, seems like #5286 is the same issue

**Comment by aprice42** [comment]
This is still an issue, I am running up against it with Ventura 13.4.1. Any ideas about what can be done to fix it? I used to see all of my Audio devices and now see none when I use this plugin.

**Comment by sskaz** [comment]
My workaround was to install [switchaudio-osx](https://github.com/deweller/switchaudio-osx) and added some Shortcuts (run shell script actions) to toggle my different output sources.

Trying to debug AppleScript and Ventura’s System Settings is a nightmare, but if someone wants to go the AppleScript route, this [reddit post](https://www.reddit.com/r/applescript/comments/118ivys/updateguide_macos_ventura_system_settings_with/) might have some tips.

**Comment by aprice42** [comment]
Thanks for the suggestion @sskaz unfortunately, my intended use is to change my output to my sonos speaker, and [SwitchAudioSource doesn't appear to currently support Airplay devices](https://github.com/deweller/switchaudio-osx/issues/9). I did find someone talking about updating AppleScript to work with Ventura in that issue's comments, maybe it will be of use to an AppleScript developer out there to get this plugin fixed? 🙏 

https://github.com/deweller/switchaudio-osx/issues/9#issuecomment-1496674289
