### ISSUE TITLE
[Emoji Search] items not populating in list

### ISSUE THREAD

**Issue by barbados-clemens** [raycast/extensions#3975]
### Extension

https://www.raycast.com/FezVrasta/emoji

#### Error:
```
TypeError: fetch failed

Object.processResponse:undici:6406:34
undici:6727:42
AsyncResource.runInAsyncScope:node:async_hooks:203:9
```

### Steps To Reproduce

1. install emoji search
2. use emoji search
3. rm -rf .config/raycast (this happened on accident when I was updating my config files)
4. restart raycasy
5. reinstall emoji search
6. errors out.

Unsure what was in the .config/raycast that I accidently nuked, but I would assume reinstalling the extensions and restarting raycast would correctly repopulate the directory with maybe a lost of some customizations. 

also assuming the remove of the .config/raycast folder is what caused this as all my extensions where missing icons and wouldn't load. but after uninstalling and restarting raycast still experienced some issues with this plugin. (others seem to be fine)

### Current Behaviour

rm -rf .config/raycast seems to cause the plugin to break after retrying to setup from scratch

### Expected Behaviour

reinstalling after removing directory should correctly reset the plugin. (unsure if there is just a bad state it's in or something) at least a way to recover from this state would be ideal.

**Comment by sxn** [comment]
Thanks for the report! unicode.org is having some issues, unfortunately. There’s an open PR[PR](https://github.com/raycast/extensions/pull/3974)  to mitigate this.

**Comment by sxn** [comment]
I've merged the PR – once the extension updates it should work again. You can explicitly tell Raycast to search for extension updates by running the `Check For Extension Updates` command. 😸
