### ISSUE TITLE
[Hypersonic] Add support for subtasks

### ISSUE THREAD

**Issue by seanrose** [raycast/extensions#3977]
### Extension

https://www.raycast.com/reboot/hypersonic

### Description

Notion recently added support for subtasks: https://www.notion.so/releases/2022-12-15

It would be useful to have this in Hypersonic. Primarily, I am thinking of:
1. A view for all child tasks for a chosen task
2. Ability to specific child tasks for a chosen task (at creation and when modifying)
3. Ability to specific a parent task for a chosen task (at creation and when modifying)

### Who will benefit from this feature?

Since it's built in to Notion now, most who use it for tasks, I'd guess!

**Comment by igarcido95** [comment]
Hey @seanrose, thanks for the feedback.

Yeah, we are already working on how to integrate the new subtasks in Hypersonic.

We'll announce it soon.
