### ISSUE TITLE
[Google Translate] Add portuguese brazilian, code: pt-br

### ISSUE THREAD

**Issue by adrianoresende** [raycast/extensions#3982]
### Extension

https://www.raycast.com/gebeto/translate

### Description

Languages between `Portuguese` and `Portuguese Brazilian` are different and I fell missing the language with code pt-br

### Who will benefit from this feature?

All user Brazilian

**Comment by gebeto** [comment]
Here are more info:

https://github.com/raycast/extensions/pull/3160

Somebody tried to add pt-br but it looks like `pt` is enough
