### ISSUE TITLE
[Obsidian] ...

### ISSUE THREAD

**Issue by KruznickMeta** [raycast/extensions#3984]
### Extension

https://www.raycast.com/marcjulian/obsidian

#### Error:
```
Obsidian menu bar command doesn't work. Keeps askign me to reload.
```

### Steps To Reproduce

1. Standard 
2. search for obsidian extension
3. select menu bar command

### Current Behaviour

Error askign for reload

**Comment by marcjulianschwarz** [comment]
Can you share a screenshot of the problem that you are facing or a more detailed description?

**Comment by marcjulianschwarz** [comment]
Hi @KruznickMeta as I did not get an answer I will close this issue now. If you have anything to add please reopen this issue. Thanks.

**Comment by marcjulianschwarz** [comment]
@raycastbot close this issue
