### ISSUE TITLE
[Toothpick] Device support form

### ISSUE THREAD

**Issue by heyimjoshcarter** [raycast/extensions#3985]
# Extension – [Toothpick](https://github.com/raycast/extensions/tree/d228408bdb2e9155158cc8ff175d0c79d6188141/extensions/toothpick/)

**Device brand and model**
Beats Studio 3

**Device data**
1C:36:BB:36:9F:14

**Comment by VladCuciureanu** [comment]
Hey! Thanks for submitting this. Sadly this is not the info I need. Please follow these steps and then paste the data in your clipboard here.
- Connect your device
- Open this extension in Raycast
- Highlight your device
- Press 'Command + K'
- Run 'Copy Device Data' command

You should get something like this:
{"Beats Studio 3":{"device_address":"1C:36:BB:36:9F:14","device_firmwareVersion":"2.5.0","device_minorType":"Headset","device_productID":"0x0D58","device_services":"0x800019 < HFP AVRCP A2DP ACL >","device_vendorID":"0x054C","device_connected":"true"}}
