### ISSUE TITLE
[Sonarr] Support access via https

### ISSUE THREAD

**Issue by owine** [raycast/extensions#3993]
### Extension

https://www.raycast.com/Aayush9029/sonarr

### Description

Allow access via https, it looks like the extension is hardcoded for http and does not follow redirection.

### Who will benefit from this feature?

Those accessing Sonarr via a reverse proxy which only allows access via https on port 443.

**Comment by tdeverx** [comment]
@owine @Aayush9029 [#4209](https://github.com/raycast/extensions/pull/4209) should fix this 🎉
