### ISSUE TITLE
[Yandex Music] Just not working

### ISSUE THREAD

**Issue by medzhidov** [raycast/extensions#3994]
### Extension

https://www.raycast.com/alexstrnik/yandex-music

### Description

Not working on latest chrome MacOS Ventura 13.0

**Comment by AlexStrNik** [comment]
Hello can you provide a little bit more details? Which browser you use are you logged in etc

**Comment by medzhidov** [comment]
I logged in, have yandex plus, tried to use chrome, chrome canary and safari. It tried to work in safari, but requires permissions, but i want to use it for chrome. When i tried to use it with selected Chrome it do nothing, while yandex music tab is opened and selected and music plays. Chrome 108

**Comment by c01nd01r** [comment]
If someone is trying to set up an extension for Chrome, just make sure you've turned on the "Allow JavaScript from Apple Events" option under "View" -> "Developer".
