### ISSUE TITLE
GitHub Extension action fails

### ISSUE THREAD

**Issue by crisboarna** [raycast/extensions#3997]
GitHub action for extension checking fails on 'Run Ray CLI' 

https://github.com/raycast/extensions/actions/runs/3751666911/jobs/6372936257#step:5:1

Raycast version:

## Steps To Reproduce

1. Run the PR GitHub action on [this](https://github.com/raycast/extensions/pull/3996)

## The current behavior
GitHub action fails.
## The expected behavior
GitHub action to pass.

**Comment by pernielsentikaer** [comment]
We're taking a look; thanks for the report 🎄

**Comment by pernielsentikaer** [comment]
This is now fixed, there are a few errors for you to sort out now 😊
