### ISSUE TITLE
[Google Translate]  No Results

### ISSUE THREAD

**Issue by Peterpig** [raycast/extensions#3998]
### Extension

https://www.raycast.com/gebeto/translate

### Description

<img width="750" alt="image" src="https://user-images.githubusercontent.com/7956973/209041404-87253364-debd-4f6c-bfe7-275fc57cff2e.png">
<img width="750" alt="image" src="https://user-images.githubusercontent.com/7956973/209042247-c44df848-8370-4833-9793-6e6766daeba8.png">
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/7956973/209041887-6ba5be00-180b-46f6-b58d-0e5f090ca85e.png">
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/7956973/209041959-933efcef-e101-44ba-903b-2758604a6a83.png">

No matter what the translation is, it is invalid.
i can view googgle and google translate

### Steps To Reproduce

1. MacBook Pro (15-inch, 2017) 12.4 (21F79)
2. RayCast 1.45.1

### Current Behaviour

google translate has no result

when i input text word.  log write such as blew

![image](https://user-images.githubusercontent.com/7956973/209042605-4b5240e5-387e-45c0-a451-663173b70d69.png)

### Expected Behaviour

google translate work

**Comment by gebeto** [comment]
I think it is happened because you are using it a lot, and there are rate limiter raising by translate API, unfortunately I can't do anything with that

You need to wait some time (up to 1 hour) to get this translate back to work

**Comment by gebeto** [comment]
I'll also try to add some error handling, so there Toast will be showing if error will happen

**Comment by dcastil** [comment]
> I think it is happened because you are using it a lot, and there are rate limiter raising by translate API, unfortunately I can't do anything with that

I also run into this issue a lot. It's a bit frustrating when I'm waiting for the results and am not sure whether I hit the rate limit or the API is just taking longer.

Would it be possible to add an action to open Google Translate with the query in the browser while Raycast is loading? Or if it can be detected that I got rate limited, would be nice to show this action instead of the infinite loading screen.

**Comment by gebeto** [comment]
Yep, I'll try to do it today 🙌

Also if you are using `Translate Form`, you can use `⌥ + Enter` to open google translate, I'll also try to add it ti the `Translate` view

**Comment by gebeto** [comment]
https://github.com/raycast/extensions/pull/6666
