### ISSUE TITLE
[Quit Applications] Adding icon on each App

### ISSUE THREAD

**Issue by kud** [raycast/extensions#4007]
### Extension

https://www.raycast.com/mackopes/quit-applications

### Description

It could be great to have the icon of each app.

![screenshot-2022-12-22-19-11-36@2x](https://user-images.githubusercontent.com/655838/209199077-1b0bf40a-822a-4782-94ed-0ab0be1c21e9.png)

### Who will benefit from this feature?

Everybody using this app.

### Anything else?

Nope.

**Comment by mackopes** [comment]
I agree this feature would be amazing and I'd use it myself. I can take a look at it in the upcoming weeks. I am however, fairly busy these days, so no promises. Of course, any PRs are very welcome and I am happy to give them a review :)
