### ISSUE TITLE
[Todoist] The Menu Bar is sometimes broken

### ISSUE THREAD

**Issue by kud** [raycast/extensions#4008]
### Extension

https://www.raycast.com/thomaslombart/todoist

#### Error:
```
Error: Toast API is not available when command is launched in background
```

### Steps To Reproduce

1. Enable the menu bar
2. Wait (I don't know how many hours)

### Current Behaviour

The Menu Bar displays an error.

### Expected Behaviour

No issue.

**Comment by thomaslombart** [comment]
That's probably related to the latest updates to the commands (focus feature)?

**Comment by AnishDe12020** [comment]
If the Todoist SDK fails to fetch tasks (according to [Todoist Status](https://status.todoist.net/pages/history/5bc439e41a99c404bdfddd01) there was degraded performance on 21st), a function called `handleError` handles it by showing a toast saying it failed to fetch tasks but the Toast API is not available when it is a background refresh.

There are 2 solutions
1. Show a HUD showing failed to fetch tasks but if the API is down and it refreshes every 10 minutes and shows an error to the user, it may be kinda invasive
2. Do nothing, just show stale data until the API works

@thomaslombart what would you recommend as a solution to this?

**Comment by kud** [comment]
I think you're on the good track here @AnishDe12020 👍🏻

I've also observed some degraded performance on their API yeah.

**Comment by thomaslombart** [comment]
Todoist's API (as well as their app) has been pretty unstable lately, yeah. 

Ah, good catch, it's surely `handleError` that causes the problems. I'd say the second solution sounds better. The first one may be too intrusive. If Todoist's API is down at some point, the users will have the messages again and again until the API is fixed which is not something we want.

To fix it, we can leverage the `environment` object to check if we're in a menu bar command and do nothing if it happens. I haven't tested it out yet but this fix should do the trick:

```ts

export function handleError({ error, title }: HandleErrorArgs) {
  if (environment.commandMode === "menu-bar") {
    return;
  }

  if (error instanceof TodoistRequestError && error.isAuthenticationError()) {
    return showToast({
      style: Toast.Style.Failure,
      title: title,
      message: "Please, make sure your Todoist token is correct.",
    });
  }

  return showToast({
    style: Toast.Style.Failure,
    title: title,
    message: error instanceof Error ? error.message : "",
  });
}
```

If we want to improve the UX though, we can also decide to show the errors with `showHUD` when the user clicked on menu bar commands as well, but not for background refresh. That's probably doable through the [LaunchType](https://developers.raycast.com/api-reference/environment#launchtype) provided to top-level commands.

**Comment by AnishDe12020** [comment]
made a pr #4057 to fix this (sorry checked out from the wrong branch on #4056 so had to close it)
