### ISSUE TITLE
[JustWatch Search] ...

### ISSUE THREAD

**Issue by dcrumbine** [raycast/extensions#4009]
### Extension

https://www.raycast.com/rishabswift/search-justwatch

### Description

Hi Raycast Team: is it impossible to change the JustWatch extension so after the URL of "[justwatch.com/ca](http://justwatch.com/ca)" it can open as "[justwatch.com/us](http://justwatch.com/us)" because the "ca" in the Raycast extension I believe is Canada though I'm hoping to open the USA location? Thank you. - Dave

### Who will benefit from this feature?

Everyone who uses the popular JustWatch website in the USA.

### Anything else?

Thank you for that.

**Comment by RishabSwift** [comment]
Hey,

You can already switch the country, in which case it will open on whatever country you set.

![Screenshot 2022-12-22 at 16 02 33@2x](https://user-images.githubusercontent.com/15897093/209225486-3b2a1897-c6ff-4768-8637-67a623b9fc3b.png)

**Comment by dcrumbine** [comment]
I totally missed that. Gulp. Thank you for that.

On December 22, 2022, raycastbot ***@***.***> wrote:
> Hey,
>
> You can already switch the country, in which case it will open on
> whatever country you set.
>
>
>

>  
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/raycast/extensions/issues/4009#issuecomment-
> 1363337474>, or unsubscribe
> <https://github.com/notifications/unsubscribe-
> auth/A45FDKYTXCBILOXZIUJNM63WOS6ZRANCNFSM6AAAAAATHDUA5I>.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


--
Sent with HEY <https://hey.com/sent> — Email as it should be

**Comment by RishabSwift** [comment]
@raycastbot close this issue
