### ISSUE TITLE
[Extension Bug] Dash Command Failed

### ISSUE THREAD

**Issue by skinnyandbald** [raycast/extensions#401]
# Extension – [Dash](https://github.com/raycast/extensions/tree/ed7385e6a4acee12a1dbd384db1311be2cae792d/extensions/dash/)

Author: @RSO

## Description
<img width="782" alt="CleanShot 2021-11-20 at 12 09 42@2x" src="https://user-images.githubusercontent.com/151953/142735087-9dcf2c35-5578-4f4c-8bec-9b955e6a3cc9.png">

## Steps To Reproduce

1. Installed Dash extension
2. Access Dash within Raycast
3. Error

## The current behavior
Error: Command failed: defaults read com.kapeli.dashdoc docsets | plutil -convert json -r -o /private/tmp/b61cedd53b9dac38797f2184840e4742.json -
2021-11-20 12:07:14.300 defaults[40254:7519100] 
The domain/default pair of (com.kapeli.dashdoc, docsets) does not exist

2021-11-20 12:07:14.300 defaults[40254:7519100] 
The domain/default pair of (com.kapeli.dashdoc, docsets) does not exist

ChildProcess.exithandler:node:child_process:397:12
ChildProcess.emit:node:events:390:28
maybeClose:child_process:1064:16
Socket.<anonymous>:child_process:450:11
Socket.emit:node:events:390:28
Pipe.<anonymous>:node:net:672:12

## The expected behavior
To show Dash docs

### Raycast version
Version:

**Comment by RSO** [comment]
Thanks for reporting! Did the extension work before, or has it always been like this for you?

Also, can you maybe share how you have installed Dash on your machine? I'm currently aware of two different types of Dash installs that result in different locations, it could be that you're on a third 🤔 .
