### ISSUE TITLE
[Shell] Commands are not executed when "Use Terminal/iTerm" is enabled

### ISSUE THREAD

**Issue by tomacco81** [raycast/extensions#4019]
### Extension

https://www.raycast.com/asubbotin/shell

### Description

When I enable the "Use Terminal/iTerm" option in the settings and select "Terminal" as application, the terminal is opened but the command is not executed.

### Steps To Reproduce

1. Set ">" as alias and enable the option "Use Terminal/iTerm"
<img width="1112" alt="Bildschirm­foto 2022-12-23 um 08 02 02" src="https://user-images.githubusercontent.com/46278513/209288247-cb903de7-b263-4403-8537-97ada153cdbe.png">
2. Run '> echo hello world'
<img width="862" alt="Bildschirm­foto 2022-12-23 um 08 08 26" src="https://user-images.githubusercontent.com/46278513/209289152-95665a52-2b06-41e0-9d98-96a6c7344f08.png">
3. Terminal is opened but the command 'echo hello world' is not executed

### Current Behaviour

The terminal is opened but the command is not executed

### Expected Behaviour

The terminal is opened and the command is executed

**Comment by KELiON** [comment]
Probably #4063 should fix it
