### ISSUE TITLE
[Hypersonic] Menubar icon is too big

### ISSUE THREAD

**Issue by el** [raycast/extensions#4028]
### Extension

https://www.raycast.com/reboot/hypersonic

### Description

The menubar icon is too big, it should be slightly smaller.
Also, when there are no active tasks, there is no need to show a `0` count. Ideally, it can have a different icon for when there is a task and when there is none.

<img width="151" alt="Screenshot 2022-12-23 at 15 52 34" src="https://user-images.githubusercontent.com/1488164/209339352-b9dfef80-3b5f-48db-9290-0ff719e93545.png">

### Steps To Reproduce

Install the extension and enable the menubar icon

**Comment by igarcido95** [comment]
Hey @el, thanks for the feedback. Added to our backlog ;)
