### ISSUE TITLE
[Redmine] Allow to explicitly set "assignee"

### ISSUE THREAD

**Issue by cdhagmann** [raycast/extensions#4031]
### Extension

https://www.raycast.com/jwickers/redmine

### Description

Currently, the extension uses the `<<me>>` assignee value. However, some companies (mine included) assign people to groups that act as triage/backlog for available issues to work on next. In these situation, `<<me>>` also includes the issues in those groups. I would like to be able to specify the assignee value to be my name so that I only see the tickets I am actively assigned.

### Who will benefit from this feature?

Anyone whose companie abuses Redmine in this way (which is currently 100% of the companies that I have worked for that use Redmine)

### Anything else?

![Screen Shot 2022-12-23 at 10 40 52 AM](https://user-images.githubusercontent.com/4440901/209361819-7da58974-d555-48c9-ae80-e3a3c7b63af3.png)

**Comment by cdhagmann** [comment]
If I did the development and submitted it as a PR, would it be looked at for potential merging? I am willing to do it, but don't want to have it sit around.

**Comment by jwickers** [comment]
> If I did the development and submitted it as a PR, would it be looked at for potential merging? 

Sure, it shouldn't be too hard to do as well.
