### ISSUE TITLE
Give URL encoding option on quicklinks

### ISSUE THREAD

**Issue by pzelnip** [raycast/extensions#4038]
Often when I create a quicklink, the `query` parameter needs to be URL encoded.  As an example, I have a quicklink for `https://explainshell.com/` which is the link: `https://explainshell.com/explain?cmd={UrlEncodedCommand}`.  As an example, [here](https://explainshell.com/explain?cmd=ls+-Flah) is an explain shell link explaining the shell command `ls -Flah`.  Note that the URL requires the `cmd` be URL encoded or spaces escaped (ie. spaces converted to `+`).

As such if I want to use my ExplainShell quicklink, I have to find a command to query, replace spaces with `+` signs, then run the quicklink in Raycast.  This extra step is tedious (there's many Raycast extensions that can do this for me, but it's an additional unnecessary step).

It'd be great if on the configuration page for a quicklink there was an option to tick off a "URL encode query" or "replace spaces with +" to have Raycast URL encode any parameters to the quicklink before adding to the quicklink to open.

**Describe the feature and the current behavior/state.**

Currently if I have a quicklink, and the portion of the link that the `query` is in requires to be URL encoded I have to first manually url encode the text before triggering the quicklink

**Will this change the current API? How?**

There'd need to be an optional UI item to configure a quicklink to URL encode any query items

**Who will benefit from this feature?**

Anyone using quicklinks

**Any Other info.**

N/A

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
