### ISSUE TITLE
[Google Chrome] ...

### ISSUE THREAD

**Issue by kmizzi** [raycast/extensions#4049]
### Extension

https://www.raycast.com/Codely/google-chrome

#### Error:
Error: ENOENT: no such file or directory, open '/Users/kalvin/Library/Application Support/Google/Chrome/Default/History'

What's happening here is the default chrome profile folder seems to have changed from Default to Profile 1

### Steps To Reproduce

Search for history in Raycast

**Comment by kmizzi** [comment]
Note a workaround I just thought of is to create a Symlink.  I've done this and it fixed the problem locally but other users may be experiencing the same issue.

**Comment by bromanko** [comment]
Do you have any reference to the Default profile being changed? The [Chromium docs](https://chromium.googlesource.com/chromium/src/+/main/docs/user_data_dir.md#Introduction) still suggest it's `Default`. 

That said, the location should really be configurable. I'll see about adding a setting for it.

**Comment by kmizzi** [comment]
Unfortunately I couldn't find any docs either... but I did not change anything from default chrome install.  I think at some point my chrome tried to add a 2nd profile.  Perhaps if more than 1 profile exists, chrome changes the directory then?  The cause is a bit of a mystery to me.
