### ISSUE TITLE
[Github] Search PR lists only PR created by you

### ISSUE THREAD

**Issue by neeraj-ec** [raycast/extensions#4058]
### Extension

https://www.raycast.com/raycast/github

### Description

**Search Pull Request** command search only in pull requests created by you not all the pull requests.

### Current Behaviour

**Search Pull Request** command search only in pull requests created by you not all the pull requests.

### Expected Behaviour

It should search among all the pull requests regardless created by you or not.

**Comment by tonka3000** [comment]
Type `author:@me` in searchbar of raycast should work.

**Comment by neeraj-ec** [comment]
> Type `author:@me` in searchbar of raycast should work.

@tonka3000 this is to filter PRs created by me. The issue is opposite of it. Raycast lists PR only created by me. It should list/search all PRs not only mine.

**Comment by tonka3000** [comment]
Got you. You can use `-author:@me` for now.

**Comment by neeraj-ec** [comment]
> Got you. You can use `-author:@me` for now on a project case.
> 
> For search pull request this should be a filter option.

This randomly search any open source Github project's PR. I think what I specifically want is, search within my organisation. For that every time need to mention `org:abc` while searching PR and issues. There should be a setting to set org in the extension setting itself.

Isn't it a general use case where you usually work with repos under an org?

**Comment by ggnall** [comment]
Yes! This is what I'd like across basically all commands: create issue, search issues, search PRs, etc. They should be scoped to:
- A configurable org (optional)
- Created by anyone (not just me)

I need to see PRs and Issues that aren't mine or aren't in my personal repos to do my work. I think this extension used to work that way, but might be limited by API changes?

**Comment by thomaslombart** [comment]
Hey there, sorry for the late reply. After talking with the team, we can see how it's confusing. We'll see how we can change the GitHub commands to make the extension clearer. Stay tuned!

**Comment by jdk** [comment]
Can we open this back up?

**Comment by jdk** [comment]
I believe this is still an issue. Can we please open this back up?

**Comment by thomaslombart** [comment]
It is still opened.

**Comment by thomaslombart** [comment]
You can now search pull requests globally.

**Comment by ggnall** [comment]
Nice! Is the same behavior available on issue search?
>You can now search pull requests globally.

**Comment by thomaslombart** [comment]
Yes, it is!
