### ISSUE TITLE
[Wakatime] Show Today Summary Error

### ISSUE THREAD

**Issue by Fau818** [raycast/extensions#4060]
### Extension

https://www.raycast.com/iammola/wakatime

### Description

`Show Today Summary` and `Show Summary` do not work for me.

It will report a `Invalid API Key` error.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/75115028/209531322-6eb6e6f1-88ce-4805-848b-ac3a44359935.png">

But I had entered the correct API key.

**Comment by iammola** [comment]
Thanks, @Fau818. I've opened a PR that should fix the issue.

**Comment by NikosEfthias** [comment]
I still keep having this issue i updated extensions and uninstalled and installed back nothing changes.
Is it possible it is broken recently @pernielsentikaer

**Comment by pernielsentikaer** [comment]
It could indeed be the case, are you in our [Slack](https://www.raycast.com/community) community?

**Comment by NikosEfthias** [comment]
@pernielsentikaer no im not in the slack community

**Comment by iammola** [comment]
@NikosEfthias @pernielsentikaer 

Pardon the delay, I'll try to fix these issues over the weekend. Maybe it'll fix #4824 as well.

**Comment by NikosEfthias** [comment]
@iammola  great job:) thanks
