### ISSUE TITLE
[Hypersonic] Support for custom Complete status

### ISSUE THREAD

**Issue by allanjun** [raycast/extensions#4067]
### Extension

https://www.raycast.com/reboot/hypersonic

### Description

Hi, I've noticed that Hypersonic will only recognise the last status from status category `Complete`. 

On my example below I have three different Completed status: `Done`, `Wont do`, `Delegated`. 

As a result, some of my tasks still show up on the to-do list. On the example below, the task was actually "completed" but still shown up on the active tasks list:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/15525731/209553156-fbfaf350-0a36-4e68-958d-0f2c36584c41.png">

My suggestion would be to enhance the database setting view to allow users to choose the default status for categories "in progress" and "complete", and allow the filters to be more granular based on the status.

**Comment by igarcido95** [comment]
Hey @allanjun,

Yeah, we do not handle multiple status. Probably would make sense to have a default status for each but filter all completed ones.

**Comment by thedamon** [comment]
Just ran into this! I would be totally happy even if it defaulted to the built in status names, but being able to customize default for each status would also be wonderful.

Right now it is also showing my 'Done :: Archived' tasks as "incomplete" so I'm guessing it's matching on specific status label rather than group

**Comment by allanjun** [comment]
thank you @igarcido95  ! indeed @thedamon that is my struggle, I like to close my tasks with dedicated status: `done` vs `killed` vs `delegated` per screenshot. My experiments suggests it is matching the oldest status from the group, based on their creation date.

**Comment by allanjun** [comment]
actually allow me to reopen this to suggest two improvements:

- Suggest redesign the menu bar to incorporate the custom status:

    - This is how it is shown in hypersonic: ![image](https://user-images.githubusercontent.com/15525731/216943272-689fc097-2807-40bc-b325-36e445074753.png)
    - This is how it is shown on the status bar: ![image](https://user-images.githubusercontent.com/15525731/216943214-9576e571-0449-46b9-99b9-b376759c9763.png)


- be able to choose a default status when you create one new task from the command line:
    - ![image](https://user-images.githubusercontent.com/15525731/216943728-e1f04a73-85a2-4de9-b424-460a85eb91c8.png)
    - or respect the default choice from notion: ![image](https://user-images.githubusercontent.com/15525731/216943843-48486f00-32a9-4d7e-ad34-b8d5149a5365.png)

**Comment by simonmaris** [comment]
Just leaving this here, since it sort of fits. 

We have, for reasons, replaced the default Notion Status with a custom single select field to manage status. Currently this prevents us from using this, we can't even complete the setup.
