### ISSUE TITLE
[Extension Feature Request] Support more advanced 2FA options and add alphabetical sorting

### ISSUE THREAD

**Issue by bennetfabian** [raycast/extensions#407]
# Extension – [Two Factor Authentication Code Generator](https://github.com/raycast/extensions/tree/main/extensions/two-factor-authentication-code-generator)
Author: @cjdenio

**Describe the feature and the current behavior/state.**
1. Support more parameters of the 2FA URI scheme. Especially period as well as digits.
For example: Twilio, Twitch and Pinterest use 2FA via Authy and when exporting their 2FA URIs, you can see that all three services use URIs like `otpauth://totp/Twilio?secret=secret&digits=7&period=10`. 
So it would be nice to have optional advanced settings for these two parameters.
[URI Format Parameters](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#parameters)

2. Sort services alphabetically by their names
https://user-images.githubusercontent.com/41294690/142777407-994ac17e-f2bd-4e05-9a2c-349fcc3bfc5e.mov
Not even halfway through adding my 2FA tokens and it's getting reaaaally crowded and confusing.

**Who will benefit with this feature?**
1. All users of services that use 2FA with custom digits and periods.
2. All people who have dozens of services using 2FA

**Comment by bennetfabian** [comment]
https://user-images.githubusercontent.com/41294690/142777407-994ac17e-f2bd-4e05-9a2c-349fcc3bfc5e.mov

And alphabetical sorting would be nice 😅
Not even halfway through adding my 2FA tokens.

**Comment by guga4ka** [comment]
I did something similar (different period and token length) for my authy extensions, will see if i can adopt it to this extension.
