### ISSUE TITLE
[Home Assistant] Ignore certificates option doesn't work with actions

### ISSUE THREAD

**Issue by ofalvai** [raycast/extensions#4079]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Description

My Home Assistant instance is accessed through HTTPS, so I configured the extension with an `https://...` URL and checked the `Ignore Certificates` option in settings. This way the extension displays entities and states, but when I execute an action (such as toggling a light) it fails with this error message:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/1694986/209717201-fa71a72b-5a76-4f2c-9a06-05e6ce941f7f.png">

It seems that the `Ignore Certificates` option is not applied to API calls of the actions.

**Comment by tonka3000** [comment]
@ofalvai 👋

I will check it in the next couple of days what I can do but this looks solvable to me 

Thanks for the report

**Comment by MDXDave** [comment]
Any news about this issue? 😄

**Comment by pernielsentikaer** [comment]
This should now be available @MDXDave - could you please test it?

You might need to run `Check For Extensions Updates`

**Comment by MDXDave** [comment]
It works now! Thanks!
