### ISSUE TITLE
[Spotify Controls] Copy Track Details

### ISSUE THREAD

**Issue by KyleErhabor** [raycast/extensions#4088]
### Extension

https://www.raycast.com/thomas/spotify-controls

### Description

By default, Spotify does not make it easy to copy track details (e.g. name, album, etc.) I think adding a "Copy X" action to the Current Track or Now Playing commands would be useful.

### Who will benefit from this feature?

Anyone who wants to copy track details.

**Comment by thomaspaulmann** [comment]
There is already "Copy Current Track URL". Do you want to add similar commands to copy the track details in a formatted way? Could be "<Song> by <Artist>".

**Comment by KyleErhabor** [comment]
It doesn't necessarily have to be formatted (like one string with all the details), but yes, a command to copy details (so " by " would work, like "Copy Current Track [by] <Name/Artist/Album/etc.>)

**Comment by thomaspaulmann** [comment]
@KyleErhabor do you want to build it?

**Comment by KyleErhabor** [comment]
I'm not sure how to, but I can look into the API.

**Comment by thomaspaulmann** [comment]
You can check [this command](https://github.com/raycast/extensions/blob/4ae20432f083759fc86c93f1827a02988041df00/extensions/spotify-controls/src/copyUrl.ts#L7) for reference. It uses AppleScript to get the information and than construct a string to copy. I expect that this is gonna be similar.

**Comment by KyleErhabor** [comment]
Thank you. I was able to create a command that copies the name, artist, and album as a single string (in the following format: "<name> by <artist> (<album>)". Would this be fine for a pull request?
