### ISSUE TITLE
Jira Search (Self-Hosted Edition) Syntax Error: Unuxpected token < in JSON at position 4

### ISSUE THREAD

**Issue by theherk** [raycast/extensions#4090]
### Extension

https://www.raycast.com/emanguy/jira-search-self-hosted

### Description

After adding our servers custom domain and personal access token, attempting to use any of the commands returns this error. `Syntax Error: Unuxpected token < in JSON at position 4`. Perhaps I am using an unsupported version (v8.20.3#820003).

### Steps To Reproduce

1. Add custom domain.
2. Add personal access token.
3. Attempt to use any command.
4. Witness error as given.

**Comment by emanguy** [comment]
Hi @theherk! Thanks for opening an issue. The version of JIRA you're using should be okay, I tested the extension against JIRA v8.22.6 when forking the original JIRA extension. The error you're getting seems to indicate you're getting some form of HTML-based error when the extension is making a query against your instance.

I'd like to see if I can get some more information here to troubleshoot the issue, which will involve sending the HTTP request the extension makes to your JIRA instance, so pull out your favorite REST client! Here's what I'll need you to do:

1. Snag a personal access token from your JIRA instance. It can be the same one you're using in your raycast instance.
2. Find any JIRA issue key in your JIRA instance and have it ready
3. Set up a GET request in your REST client of choice to the path `/rest/api/2/search?fields=summary,issuetype,status&jql=key%3DYOUR_JIRA_ISSUE_KEY_HERE`, replacing **YOUR_JIRA_ISSUE_KEY_HERE** with the issue key you found in step 2. For example, if I had my base URL in the extension set up as `http://my.jira.com/baseurl` and had the JIRA key ABCD-123 I would set the URL to `http://my.jira.com/baseurl/rest/api/2/search?fields=summary,issuetype,status&jql=key%3DABCD-123`
4. In the request headers, you'll need to add your personal access token as a bearer token. The header should therefore be `Authorization: Bearer YOUR_PAT_HERE` where **YOUR_PAT_HERE** is the personal access token

Send that off to the server and shoot me the response you get back! Obviously omit any sensitive information in the response, but whatever you can get back to us should help!

**Comment by pedro-correia-tech** [comment]
Don't know if this helps. I've installed the extension for debug purposes and I'm getting this logs:

`15:57:27.703 FetchError: request to https://jira.pmidce.com/rest/api/latest/search?jql=%20order%20by%20lastViewed%20desc&fields=summary,issuetype,status failed, reason: write EPROTO 00F0C07801000000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:../deps/openssl/openssl/ssl/statem/extensions.c:908:

    at ClientRequest.<anonymous> (/Users/pcorreia1/.config/raycast/extensions/jira-search-self-hosted/issue.js:5373:14)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'EPROTO',
  code: 'EPROTO',
  erroredSysCall: 'write'
}
15:57:27.704 Error: Check your network connection
    at jiraFetch (/Users/pcorreia1/.config/raycast/extensions/jira-search-self-hosted/issue.js:5649:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async jiraFetchObject (/Users/pcorreia1/.config/raycast/extensions/jira-search-self-hosted/issue.js:5620:20)
    at async searchIssues (/Users/pcorreia1/.config/raycast/extensions/jira-search-self-hosted/issue.js:5873:18)
15:57:27.709 Error: write EPROTO 00F0C07801000000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:../deps/openssl/openssl/ssl/statem/extensions.c:908:`

**Comment by theherk** [comment]
I'm a bit embarrassed that I didn't realize this at the outset, but of course I can't reach my instance; it is behind a proxy. I have to use microsoft federated auth to reach the interface, so the api is not accessible to me locally. So if I call the api, I get redirected to federated auth, which just won't work until I have this route via vpn.

So, this is a _me_ issues. Sorry about that. But thank you for the excellent support.

@pedro-correia-tech: I'm going to close this, so you may want to open a separate issue.

**Comment by emanguy** [comment]
Glad you got everything sorted!

**Comment by pedro-correia-tech** [comment]
> @pedro-correia-tech yeah it sounds like you're having a slightly different issue involving SSL negotiation. If legacy renegotiation is disabled and that's what the server is saying it wants to do, you may just need to enable unsafe HTTPS in the extension settings. The original issue OP posted sounds like they're getting a response back but it contains HTML and not JSON.

@emanguy Even with Unsafe/Safe Https checked problem still appears.

I don't know exactly how can i check if the problem is the same on the official installation from the store.

Only way to me to debug this problem was clone the extension and run "npm run dev" and check console logs...
