### ISSUE TITLE
[YouTube Music] Doesn't seem to work with Firefox

### ISSUE THREAD

**Issue by theherk** [raycast/extensions#4093]
### Extension

https://www.raycast.com/danieldbird/youtube-music

### Description

This extensions commands work fine with Safari after allowing javascript apple events, but it doesn't work with Firefox and I can't find any further information on it.

### Steps To Reproduce

1. Use Macbook Pro M1 Max with Ventura 13.1.
2. Install Firefox 108.0.1.
3. Install this extension.
4. Set browser to Firefox.
5. Open and begin playback in Youtube Music.
6. Attempt to use any command.

### Current Behaviour

No commands work.

### Expected Behaviour

All commands work.

**Comment by AlexStrNik** [comment]
Reproduced, fix in progress

**Comment by AlexStrNik** [comment]
Oh, there is no way to fix since Firefox doesn't work with AppleScript(

https://bugzilla.mozilla.org/show_bug.cgi?id=125419
