### ISSUE TITLE
[Dropbox] ...

### ISSUE THREAD

**Issue by Thinkjarvis07** [raycast/extensions#4095]
### Extension

https://www.raycast.com/chyroc/dropbox

### Description

Dropbox File Share on Raycast is not operating.  Error code 400

### Steps To Reproduce

[Step 1.pdf](https://github.com/raycast/extensions/files/10323207/Step.1.pdf)
[Step 2.pdf](https://github.com/raycast/extensions/files/10323208/Step.2.pdf)
[Step 3.pdf](https://github.com/raycast/extensions/files/10323209/Step.3.pdf)
[Step 4.pdf](https://github.com/raycast/extensions/files/10323210/Step.4.pdf)
[Step 5.pdf](https://github.com/raycast/extensions/files/10323211/Step.5.pdf)
[Step 6.pdf](https://github.com/raycast/extensions/files/10323212/Step.6.pdf)
[Step 7.pdf](https://github.com/raycast/extensions/files/10323213/Step.7.pdf)

### Current Behaviour

 I generate an access key and publish dropbox app.  When I enter the access key and try to search my dropbox folders via Raycast.  I get error code 400

**Comment by Almadual** [comment]
I am having the same Issue. It would be cool if this would be resolved.
