### ISSUE TITLE
[API Feature Request] Inline mode

### ISSUE THREAD

**Issue by rolandleth** [raycast/extensions#41]
Inline mode for extension would open a lot of possibilities, for example:
- display current temperature, but open with more details, like a forecast; or
- display number of open PRs, then open a list to show them all and be able to open any of them.

Could work in the same way inline scripts work, where they refresh on a given timer and update their title and/or subtitle.

**Comment by PitNikola** [comment]
This is certainly something we are going to tackle at some point. Can't give any rough date on this. Unlikely to happen in 2021.

**Comment by thomaspaulmann** [comment]
Just picking this up. Is it not online inline mode but also specifying actions that could be performed from the root search? We don't have in scripts. There it's only displaying some dynamic subtitle for the comman.d

**Comment by mathieudutour** [comment]
Closing this as it's now possible to update the subtitle of a command
