### ISSUE TITLE
[YouTube Music] Play / Pause not working on Chrome

### ISSUE THREAD

**Issue by garymm** [raycast/extensions#4103]
### Extension

https://www.raycast.com/danieldbird/youtube-music

### Description

Toggle Play / Pause doesn't do anything for me.

### Steps To Reproduce

1. Open Google Chrome
2. Open `https://music.youtube.com/`
3. Play a song
4. Invoke RayCast
5. Invoke YouTube Music Toggle Play / Pause

### Current Behaviour

Nothing happens. In fact it seems like the command can't even be invoked, since RayCast window stays up.

### Expected Behaviour

Music pauses.

**Comment by LHARISMENDY** [comment]
Can reproduce also with Brave Browser.

**Comment by kaushikgopal** [comment]
there's a couple of these issues raised for "Youtube Music" and auto-closed cause noone's responded. i'm facing the same with Vivaldi, but not sure it's worth re-reporting if it's going to be closed cause this isn't the right channel.
