### ISSUE TITLE
Brave browser application Hotkey problem

### ISSUE THREAD

**Issue by shahnawaz323** [raycast/extensions#4105]
When I use the shortcut hot key to switch to brave browser (ctrl+shift+cmd+B) when the popup player is playing for a video it does not switch to the application rather it shifts the focus to the popout player. Remember popout player is the built in popout player in chrome/ Brave browser. 

Raycast version: 1.45.2

## Steps To Reproduce

1. Install brave browser or may any other browser. Use ctrl hotkey generated from karabiner elements for that browser (this step is not necessary. Any hotkey may work). Play the youtube video through popout player from the toolbar. Switch to some application and press the hotkey. 

## The expected behavior
Pressing the hotkey switches to the application rather shifting to the popout player.

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
