### ISSUE TITLE
[Bitwarden Vault] Auto lock vault when locking mac

### ISSUE THREAD

**Issue by CyrilNb** [raycast/extensions#4113]
### Extension

https://www.raycast.com/pomdtr/bitwarden

### Description

A preference to enable autolock the vault when the mac is locked

### Who will benefit from this feature?

Safety of users

**Comment by jomifepe** [comment]
This is a nice feature, I'm just not too sure about its feasibility. I don't think macOS has an easy way to check when the session was last locked. Also, bitwarden extensions are short-lived processes, meaning that they don't run in the background, which doesn't help with lock detection. 

Allowing the developer to access the last lock time would actually be a nice addition to the Raycast API.

**Comment by pernielsentikaer** [comment]
I don't think we have a way to retrieve this 🫤

**Comment by se-jaeger** [comment]
Hi, I'm also interested here.

Is it possible to implement time-base locking and unlock with fingerprint? Similarly to the Mac (GUI) App?

**Comment by jomifepe** [comment]
> Hi, I'm also interested here.
> 
> Is it possible to implement time-base locking and unlock with fingerprint? Similarly to the Mac (GUI) App?

Hey, the extension already has a time-based locking feature, but asks for the master password. 

Regarding the fingerprint, I wish, but that's not currently possible.

**Comment by se-jaeger** [comment]
You mean the "Skip Reprompt" setting? I guess it should lock bitwarden after say 5mins and then ask for the master password. Is this correct, @jomifepe?

**Comment by jomifepe** [comment]
> You mean the "Skip Reprompt" setting? I guess it should lock bitwarden after say 5mins and then ask for the master password. Is this correct, @jomifepe?

Yeah that's correct, is it not working for you?

**Comment by se-jaeger** [comment]
> > You mean the "Skip Reprompt" setting? I guess it should lock bitwarden after say 5mins and then ask for the master password. Is this correct, @jomifepe?
> 
> Yeah that's correct, is it not working for you?

Exactly, it doesn't work for me. I'll open a bug report.

**Comment by boehs** [comment]
> Regarding the fingerprint, I wish, but that's not currently possible.

Why not?

**Comment by jomifepe** [comment]
> > Regarding the fingerprint, I wish, but that's not currently possible.
> 
> Why not?

Raycast doesn't have a way to interact with those native macOS APIs. If it's possible, it would required some additional software that the users would have to install/configure, and that would be cumbersome, users already have to install the CLI for the extension to work.

**Comment by mathusanMe** [comment]
I was wondering whether using the Bitwarden Cli app itself for validating the touchID biometrics would be possible.
Bitwarden's chrome extension uses it to make touchID possible directly through chrome.

**Comment by jomifepe** [comment]
> I was wondering whether using the Bitwarden Cli app itself for validating the touchID biometrics would be possible. Bitwarden's chrome extension uses it to make touchID possible directly through chrome.

You mean the desktop app, that's something worth investigating, but it's most likely some kind of integration, since both clients are developed by the Bitwarden team.

**Comment by jomifepe** [comment]
Just released two experimental "On system lock" and "On system sleep" timeout options. Give it a try 🙂
