### ISSUE TITLE
[Hypersonic] Couldn't connect to Notion database

### ISSUE THREAD

**Issue by tson1111** [raycast/extensions#4119]
### Extension

https://www.raycast.com/reboot/hypersonic

### Description

I successfully connected hypersonic to my Notion account (see screenshot attached).
<img width="668" alt="image" src="https://user-images.githubusercontent.com/26613690/210207088-3888fb65-dffc-4ece-941c-d7ffd0950842.png">

But hypersonic still cannot access my Notion database:
<img width="618" alt="image" src="https://user-images.githubusercontent.com/26613690/210206983-fe41225e-5992-4a86-90f0-56e721978e53.png">

Error log attached:
`APIResponseError: Could not find database with ID: db18f25f-xxxxxxxxxxxxxxxxxxxx. Make sure the relevant pages and databases are shared with your integration.
    at sz (/Users/xxxxxx/.config/raycast/extensions/baa4a90b-xxxxxxxxxxxxxxxxxxxx/index.js:1:4348)
    at Yi.request (/Users/xxxxxx/.config/raycast/extensions/baa4a90b-xxxxxxxxxxxxxxxxxxxx/index.js:1:324073)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _P (/Users/xxxxxx/.config/raycast/extensions/baa4a90b-xxxxxxxxxxxxxxxxxxxx/index.js:39:77082)
    at async IT.initialData (/Users/xxxxxx/.config/raycast/extensions/baa4a90b-xxxxxxxxxxxxxxxxxxxx/index.js:39:77542)`

**Comment by tson1111** [comment]
> Hey @tson1111,
> 
> Do you have Full access permissions on the workspace?

Yes, I’m the owner of the workspace.

**Comment by DaltonThompson** [comment]
I have a similar issue, although Hypersonic does not present an error message. I gave Hypersonic access permissions to duplicate a template database to my Notion account, which it did successfully when I look inside Notion itself. However, in Raycast > My Tasks, I cannot find any database. This is what I see:
![Screen Shot 2023-01-05 at 3 31 18 PM](https://user-images.githubusercontent.com/20143971/210876363-831654bd-5a96-407a-a085-3bf13fc4ce26.png)

**Comment by igarcido95** [comment]
Hey @tson1111,

I would need more details to troubleshoot the issue. Could you DM me on Raycast Slack's at Ivan G.

Thanks!

**Comment by igarcido95** [comment]
Hey @DaltonThompson, same thing. I would need more details on your case. Could you DM me on Raycast Slack's at Ivan G.

Thanks!
