### ISSUE TITLE
[Jisho] History

### ISSUE THREAD

**Issue by mmtftr** [raycast/extensions#4120]
### Extension

https://www.raycast.com/dmacdermott/jisho

### Description

A command to show the recent history of searches/allow the possibility of exporting them would be really nice. I can also work on implementing this in my free time.

What I exactly want is a history of every typed up word. That means if I type "jisho" and see the result then delete my query, that should still be an entry in the history. This is a little vague but the application Shirabe Jisho does this really well.

From my observations, Shirabe Jisho does this:

On every search, it starts recording your input periodically (probably a _.throttle'd keystroke handler). If you clear the search bar, then the last recorded input is saved to the history. If you change the word before it's saved, only the last thing you wrote is saved. I think this makes sense.

I'm not at all familiar with the Raycast API but the save can probably happen upon the Raycast window going out of focus (save should happen only if the last entry is not the same in this case, since the window can come back and out of focus with the same entry without user input) or the extension being dismissed (i.e. user pressing ESC and going back to the general search bar).
 

### Who will benefit from this feature?

Japanese learners that want to export the words they looked up/access them later on.

### Anything else?

If this is a feature that the extension developer looks favorably upon, I can also attempt to implement it. Also tagging the extension developer for visibility @dmacdermott

**Comment by dmacdermott** [comment]
@mmtftr Thanks for the suggestion! Sorry for the late reply as I've been away for the holidays. I'm quite busy with work and other projects at the moment so it might be a while till I get around to implementing it. Please feel free to have a go yourself though if not I'll do it in a few weeks.

**Comment by mmtftr** [comment]
I'm also quite busy this week but I can take a look at this after the 16th. I've also seen that there is no rebounce on the Jisho API call. I might also add a (configurable) rebounce for that  to reduce load on the Jisho servers.

**Comment by dmacdermott** [comment]
@raycastbot close this issue
