### ISSUE TITLE
[Monzo] ...

### ISSUE THREAD

**Issue by mspych** [raycast/extensions#4121]
### Extension

https://www.raycast.com/danpalmer/monzo

### Description

After initially connecting the extension stopped working.
No transaction are showing.

### Steps To Reproduce

Launch the extension

### Current Behaviour

Failed to fetch latest data error is returned

### Expected Behaviour

Transactions should be pulled

**Comment by danpalmer** [comment]
Thanks will take another look. I've heard a similar report but not managed to reproduce in development and the stacktrace from prod builds didn't yield anything clear.

**Comment by danpalmer** [comment]
Thanks @raycastbot for the ping. I've done some more investigation here. I can reproduce this issue, it seems to be that refresh tokens stop working correctly after a while.

I noticed this code in the refresh function:

```typescript
const tokenResponse = (await response.json()) as OAuth.TokenResponse;
tokenResponse.refresh_token = tokenResponse.refresh_token ?? refreshToken;
return tokenResponse;
```

Line 2 defaults the refresh token to the _old_ refresh token. The Monzo docs aren't clear, but I suspect this is not allowed, and causes refresh tokens to get out of step, and therefore invalid.

I'm going to try removing this line and see if it works. I'll re-test over the next few days and submit a fix if it's all ok.

**Comment by danpalmer** [comment]
I actually fixed this in the end, should be all working.
