### ISSUE TITLE
[Elgato Key Light] ...Only controls one light

### ISSUE THREAD

**Issue by califa** [raycast/extensions#4125]
### Extension

https://www.raycast.com/thomas/elgato-key-light

### Description

The Raycast extension only controls one Key Light, even when 2 are connected.

### Steps To Reproduce

1. Install two key lights (work working via the Elgato control center)
2. Install Elgato Key Light Raycast extension.
3. Run any command, specifically Toggle On/Off might be the most obvious.
4. This is still the case even if you have "Link Accessory Controls" enabled in Elgato.

### Current Behaviour

Controls one light

### Expected Behaviour

Controls both lights

**Comment by thomaspaulmann** [comment]
Good point, I need to fix this. How would you expect this to work? I'm thinking about two different solutions:
1. Should `Toggle On/Off` toggle the individual lights or keep both in sync?
2. Should `Increase/Decrease Brightness` keep the lights in sync or change individually?

My first impression would be that it's kind of expected that both lights turn on or off simultaneously but the increase/decrease brightness should affect the lights separately. WDYT?

**Comment by lukasoppermann** [comment]
Hey, I am running into the same issue. I feel like `Toggle On/Off` should toggle all lights together. 

I guess `Increase/Decrease Brightness` would need to keep them in sync. Or how would you be able to control which light you are changing?

**Comment by califa** [comment]
Control Center has a `Link Accessory Controls` setting. I wonder if Raycast can honor that? Or surface each light individually + an "All lights" option?

**Comment by lukasoppermann** [comment]
I'd prefer an extra option. My lights are NOT linked because they have different brightness settings. ButI still want to turn them on and off at once. (Control center has this option at the top).
