### ISSUE TITLE
[GitHub] Clear inputs when submitting issue / Allow clearing of inputs manually with a `Reset` button

### ISSUE THREAD

**Issue by Foxhoundn** [raycast/extensions#4133]
### Extension

https://www.raycast.com/raycast/github

### Description

Right now there is no way to quickly clear all the entries & selections when creating an issue / issue was created. You have to go back to the main screen and to the issue creator again or manually clear all fields.

If the extension is open sourced I am happy to help.

### Who will benefit from this feature?

Everyone using Github issues in Raycast

### Anything else?

![CleanShot 2023-01-03 at 11 46 07](https://user-images.githubusercontent.com/8861481/210342642-cae2f372-7a37-4d60-9c89-ec6e92903d64.png)

**Comment by thomaslombart** [comment]
Good catch! Clearing the inputs haven't been done both on `Create Issue` command and `Create Pull Request`. I'm not sure I'll be able to fix that this week but rest assured it'll be done soon enough.
