### ISSUE TITLE
[Music] Failed to execute command "Add to Library"

### ISSUE THREAD

**Issue by Jaxx4Fun** [raycast/extensions#4145]
### Extension

https://github.com/raycast/extensions/tree/5c54bf190a516d206da7ea5cc87abcca4a1fff9a/extensions/music

### Description

it failed to add music to the library.
<img width="319" alt="image" src="https://user-images.githubusercontent.com/10000619/210556420-7c00b42b-f568-440e-97a9-fc09294ad8bc.png">

### Steps To Reproduce

1. Play a song
2. ⌥+space to call out raycast
3. search for the command "Add to Library" by typing the alias I pre-defined "ma"
4. ↩︎

### Current Behaviour

A prompt shows the command execution failed.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/10000619/210557104-5781f67c-2dd3-4f02-b8a9-8a542dc0a9b2.png">

### Expected Behaviour

The current playing song shall be added to Library.

**Comment by Jaxx4Fun** [comment]
https://github.com/raycast/extensions/tree/5c54bf190a516d206da7ea5cc87abcca4a1fff9a/extensions/music

**Comment by Rawnly** [comment]
Hello thanks for reporting, I have to investigate a bit further. Are you on a Radio? The "add to library" theme is quite weird with the Music app, I currently handle this in 2 different ways but seems that in your case neither is working.

https://github.com/raycast/extensions/blob/f8812e201b0d91270b839d11a57c024fc35ad4d0/extensions/music/src/util/scripts/current-track.ts#L13-L17

can you try the first script inside `Script Editor`? 

```osascript
tell application "Music" to duplicate current track to source "Library"
```

**Comment by LEUNGHOTIN** [comment]
I think this will help you : https://developer.apple.com/forums/thread/694200

**Comment by Rawnly** [comment]
Thanks, I’ll try this evening!

**Comment by Rawnly** [comment]
Hello everyone after a bit of investigation in the last few days, I haven't  come up with a solution. I already tried 2 different ways to add a track to the Library but it doesn't seem to be enough. The problem is that this kind of problem is inconsistent and I'm not always able to reproduce it. 

I also opened a new ticket directly to apple on "Feedback assistant" but as of now, no answers so far.

If anyone has any nice clean solution to try to fix this PRs are more than welcome!

**Comment by Rawnly** [comment]
Hello everyone, apple seems to be interested in this (maybe). In the ticket answer they asked for more details about the problem. Can you share some songs that you have problems with? I'm not able to reproduce this anymore somehow. 

Thanks for your help

**Comment by Jaxx4Fun** [comment]
Actually, for me, this issue is reproducible with every single song...
[夜海的秘密-昨夜派对](https://music.apple.com/cn/album/%E5%A4%9C%E6%B5%B7%E7%9A%84%E7%A7%98%E5%AF%86/1566500724?i=1566500725)

**Comment by LEUNGHOTIN** [comment]
[Smells Like Me](https://music.apple.com/cn/album/smells-like-me/1633318292?i=1633318575)
