### ISSUE TITLE
[Man Pages] "TypeError: ... received undefined" upon initial open

### ISSUE THREAD

**Issue by veloxo** [raycast/extensions#4156]
### Extension

https://www.raycast.com/HelloImSteven/man-pages

#### Error:
```
TypeError: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined

NodeError:errors:393:5
Function.byteLength:node:buffer:740:11
eo.set:index.js:15:16087
Wo:search-man-pages.js:9:130
```

### Steps To Reproduce

1. Activate the `Search Man Pages` extension

### Current Behaviour

Initial interaction immediately raises the "Something went wrong" panel

### Expected Behaviour

The extension loads

**Comment by SKaplanOfficial** [comment]
Fixed in #4328. @raycastbot close this issue
