### ISSUE TITLE
[Extension Feature Request] Window Management - Exempt Maximise command from Gap rule

### ISSUE THREAD

**Issue by LeeBuckle** [raycast/extensions#416]
# Extension – [Window Management] (Core extension)

Author: @raycastbot @thomaspaulmann (sorry, not sure who's responsible for the extension)

**Idea:**
An option to exempt the "Maximize" command from the gap rule.

**Describe the feature and the current behavior/state.**

At present, the window gap option affects all window management options, including maximize.

Having a gap is nice when you want a bit of space between windows that are side-by-side. For single, maximized windows however, it would be nice to have the option of not having a gap.

A toggle beneath the gap option, such as "Gap When Maximized" would be a nice addition.

**Who will benefit with this feature?**
Everybody who likes having a gap between windows but would also like maximized windows to make the most of the screen real estate that they have.

**Any Other info.**
Just a personal example of why this would be beneficial to me and people like me. I use a multiple monitor setup where one screen is a large ultra-wide and the other is a smaller, 16:9 24" monitor. The gap feature is great when arranging windows on my large screen, however, I generally use the smaller screen for single, maximized windows such as the web browser when I'm developing a website. Having a gap around the browser on the smaller screen means less screen real estate.

**Comment by thomaspaulmann** [comment]
Hey @LeeBuckle,

Thanks for raising this. The Window Management is a core extension and not part of this repository. So I'll close this issue. Nevertheless, I think it's a good feature request. I have a similar use case when I work on my big monitor and just on my laptop. On the monitor, I'd like to have a gap around my windows, on the laptop, I want to use every pixel. Though, I'm not sure if you would need another command or it should be rather that you can define different gaps per monitor. It should be possible to identify the monitor by ID (or maybe size?!) and then apply the gap. WDYT?

**Comment by LeeBuckle** [comment]
I can picture a simple simple implementation of your display specific idea. Since Mac OS already defines a name for each monitor, maybe take those names and add a separate gap option for each one, such as "Gap - Display Name" followed by the select box for that display. Ideally, gap options for only the currently connected displays would be displayed as some users might connect to many displays such as TV's, multiple monitors at home and at work etc.

In addition, I think a custom window size option would be great too, something that works in a similar way to Quicklinks where a keyword is combined with user input. For example, and just like CSS, typing "vw 50" would make the window take up 50% of the screen. Likewise "vh" would control the height. Adding "px" after a number would use pixels instead of percent. A combination keyword would be great too, for example "wh 60 750px" would make a window 60% wide and 750px tall. . Probably thinking a little to far ahead here but the idea is on the table.
