### ISSUE TITLE
[Code Stash] Ability to edit a code stash

### ISSUE THREAD

**Issue by ryanmsnyder** [raycast/extensions#4160]
### Extension

https://www.raycast.com/ben-greenwood/code-stash

### Description

Great extension. Please add the ability to edit a code block

**Comment by ben-greenwood** [comment]
Hey @ryanmsnyder

Thanks! I've submitted an PR for review with the new edit command #4163

**Comment by ben-greenwood** [comment]
@raycastbot close this issue
