### ISSUE TITLE
[Kagi Search] Ability to search entered phrase before search suggestions arrive

### ISSUE THREAD

**Issue by carlosefonseca** [raycast/extensions#4171]
### Extension

https://www.raycast.com/fearoffish/kagi-search

### Description

In Kagi Search, I should be able to type something and immediately press enter to search for what I typed.

Currently that is slightly broken because Enter will trigger the first action which comes from the Kagi API search suggestions which is usually a few milliseconds behind. So I end up with a search that lacks the last few characters. I end up opening Raycast again just to press enter again to open the search results for the full phrase.

My suggestion would be to make the first action always search for the currently typed text, and place the search suggestions bellow that action.

### Who will benefit from this feature?

All Kagi users.

### Anything else?

https://user-images.githubusercontent.com/14120/211041016-dc6500d1-ca0e-4c61-b1f3-8385d64925f8.mp4

**Comment by fearoffish** [comment]
That sounds like a good idea. I'll get on it...I'm a bit busy this week but I'll get to it.
