### ISSUE TITLE
Search in Devonthink database terminates with error

### ISSUE THREAD

**Issue by Bleistein** [raycast/extensions#4179]
### Extension

https://www.raycast.com/bgnfu7re/devonthink

#### Error:
```
see attached file
---
[Error.txt](https://github.com/raycast/extensions/files/10366816/Error.txt)


index.js:6:32483
    at Array.map (<anonymous>)
ci:index.js:6:32476
```

### Steps To Reproduce

New installation of raycast and the Devonthink extension today.

Just trying to search 3 letters... Every search results in this problem.

Apple macOS 13.1 on M1 14" MBP.

TypeError: Cannot read properties of null (reading 'value')

tk:index.js:6:32636

---
see attached file:

[Error.txt](https://github.com/raycast/extensions/files/10366822/Error.txt)
---

index.js:6:32483
    at Array.map (<anonymous>)
ci:index.js:6:32476

### Current Behaviour

Display: Something went wrong

### Expected Behaviour

Displaying some kind of search results...

**Comment by kudrykv** [comment]
Thank you for creating the issue!

Please try disabling Geolocation tick in extension preferences

**Comment by Bleistein** [comment]
Hi Vitaly,

thanks for the fast answer. That fixed the Problem!

With best regards
 
Michael Bleistein 

P.O. Box 1195 
VG1150 Valley, Virgin Gorda 
British Virgin Islands 

VG: +1   (302) 504-4321
DE: +49 (156) 78517337‬
SKYPE: bleistein
