### ISSUE TITLE
[Adhan Time] 12-hour Format

### ISSUE THREAD

**Issue by FaroukZeino** [raycast/extensions#4180]
### Extension

https://www.raycast.com/mzaien/adhan-time

### Description

Please add an option to show prayer times in 12 hour format also.

**Comment by mzaien** [comment]
Hello @FaroukZeino sorry for being late, an update having this feature was released just now 
https://github.com/raycast/extensions/pull/4320

**Comment by FaroukZeino** [comment]
No worries, thank you!
