### ISSUE TITLE
Coffee : can't caffeinate when Status menu bar is disabled

### ISSUE THREAD

**Issue by Padamdam** [raycast/extensions#4181]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

The **Cafeinate for** option (as well as **Toggle Caffeinate**, **Caffeinate for** and **Caffeinate while**) returns an error when using it and the **Caffeinate Status Menubar** command is disabled in Raycast's Extensions.

The error returned is : **Error: No enabled command 'index' found**

Extensions are all latest, Raycast is 1.45.2 on MacOS 13.1 and M1 Air.

### Steps To Reproduce

1. Install Coffee extension
2. Use any command to Caffeinate (...for, ...while)
3. Command is successfull
4. Go into Raycast's extensions settings and disable only Caffeinate Status Menubar
5. Exit Raycast's Settings
6. Use any command to Caffeinate (...for, ...while)
7. Error screen is presented with the following error (got from Copy Error secondary action) : **Error: No enabled command 'index' found**

Issue is present with either Status menu bar activated or not (present in menu bar or not).

**Comment by pernielsentikaer** [comment]
Thanks for flagging this, I'll make a fix today 😊

**Comment by Padamdam** [comment]
@pernielsentikaer Thanks for your fixing this.

I just tested and the extension works fine without the Caffeinate Status Menubar disabled in Raycast extension settings.

**Comment by pernielsentikaer** [comment]
Thanks for confirming it fixed the issue 😊
