### ISSUE TITLE
[Set Audio Device] to favourite output audio device not working for any of my devices

### ISSUE THREAD

**Issue by justinyan13** [raycast/extensions#4184]
### Extension

https://www.raycast.com/benvp/audio-device

### Description

Tried setting favorite device to the EXACT name of my airpods pro, external speaker. None would work

**Comment by DrPhilippBillion** [comment]
Same problem here with the indeed compliacted "Burr-Brown Japan PCM2702" Device ;-) Thanks for the great work you put into this Extension!
