### ISSUE TITLE
[Tailwind CSS] Filter by class name instead of selector name, or both

### ISSUE THREAD

**Issue by Solaris9** [raycast/extensions#4186]
### Extension

https://www.raycast.com/vimtor/tailwindcss

### Description

Currently the extension will filter by the selector name, where this might be an issue is when you want to find the tailwinds equivalent but it will yield no results. For example, if you search "width" it will return no results, but if you search "w-1" it will return that class. 

An update to either accept only the CSS class to return the tailwindcss selector equivalent, or search both the `selector` or `classes` to return the tailwind equivalent would be absolutely amazing for reasons listed in the next section.

You can view the problematic line here: https://github.com/raycast/extensions/blob/076c06daeba71dd1c2efd621e82923046b309a33/extensions/tailwindcss/src/search-classes.tsx#L8

### Who will benefit from this feature?

Anyone who might have issues with memorizing all the tailwindcss selectors, or are not able to have an extra browser tab open to search through the documentation, or someone who would like to view the tailwindcss selectors without having to navigate away from their code as it is very quick to open Raycast and start searching for what they need.

**Comment by vimtor** [comment]
Great idea I will try it. I don't promise anything since the list of class names is really huge and it may get a bit slow.
