### ISSUE TITLE
[Visual Studio Code - Project Manager] ...

### ISSUE THREAD

**Issue by oberonlai** [raycast/extensions#4193]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

Raycast can't load the second level view successfully.

### Steps To Reproduce

1.select the Search Project Manager
2.click enter

### Current Behaviour

No data loaded.

### Expected Behaviour

Load my VSCode project list

**Comment by MarkusLanger** [comment]
Hi @oberonlai ,

- What is your version of the VS Code Project Manager extension in VS Code?
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/12131918/211245951-818bb367-5af2-4e5e-80a2-1d5b19577449.png">

- Could you check the path and the structure of the project.json of the VS Code Project Manger Extension in VS Code?
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/12131918/211246068-920291b3-0206-46ba-a6da-e96dea6e201e.png">
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/12131918/211246093-54f2cfdf-d1c5-4ae1-a1f7-6059716d6860.png">

**Comment by oberonlai** [comment]
Hi

The version of my VS Code Project Manager extension is v12.7.0, too.
Actually, not only this extension doesn’t show the data, but also the other extensions:

Search Emoji:



Brew:



Alpine.js document



My raycast version is 1.45.2
MacOS version is 13.1

Please let me know if you need another info to debug.
Thanks for your help!

Oberon

感謝您的支持，有任何問題歡迎與我們聯絡!
服務時間：星期一～星期五 10:00～19:00
WP 網站架設 https://oberonlai.blog
WP 主機服務 https://hellowp.cc
—
賴俊吾 Oberon Lai
© 2022 ＷordPress 開發日常

**Comment by MarkusLanger** [comment]
@oberonlai Then it is not a problem of the extension. You should change the title and the labels so that someone can help with the general problem.
