### ISSUE TITLE
[Bitwarden Vault] Auto-generate password & paste into active app

### ISSUE THREAD

**Issue by sannidhyaroy** [raycast/extensions#4196]
### Extension

https://www.raycast.com/pomdtr/bitwarden

### Description

I've configured the `Generate Password` command shortcut as `Option + G`. Now, for sites that I'm newly signing up, I can just use `Option + G` and Raycast will generate a password. Then pressing `Cmd + Shift + Enter` will paste the password into the password field of the active app. Also, I've to tap on the password field to set the cursor there beforehand, or else it wouldn't paste it.

This is a three step process. The best way was to automate this just like how Chrome or Safari actually auto-generates and fills new passwords in sign-up forms automatically, but that's something only the Bitwarden team would be able to do and it doesn't look like they're implementing this soon.

### Who will benefit from this feature?

All Bitwarden Users. Auto-fills are extremely convenient.

**Comment by jomifepe** [comment]
Commenting to prevent the issue from being closed. Yeah, this can be implemented, I added it to my backlog.

**Comment by jomifepe** [comment]
Added a new "Generate Password (Quick)" command, try it out 🎉

**Comment by jomifepe** [comment]
@raycastbot close this issue
