### ISSUE TITLE
[iMessage 2FA] Possibility to change the default value (2FA/All mesages) for the search

### ISSUE THREAD

**Issue by stylishgadgets0p** [raycast/extensions#4199]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

Currently if I want to search for a message I have to switch from 2FA to All messages, it would be useful if I could choose that I want the default value All mesages/2FA. Thank you.

### Who will benefit from this feature?

everyone

**Comment by yuercl** [comment]
Sounds good, I think there could be a config that represents the default mode, but give me a little time to implement it.
