### ISSUE TITLE
[DEVONthink] ...

### ISSUE THREAD

**Issue by joshdoyle** [raycast/extensions#4202]
### Extension

https://www.raycast.com/bgnfu7re/devonthink

### Description

[raycast devonthink error.txt](https://github.com/raycast/extensions/files/10375847/raycast.devonthink.error.txt)

### Steps To Reproduce

Running 
- Raycast 1.45.2
- MacBook Air M2, 2022 MacOS Ventura 13.0. 
- Devonthink 3.8.7

I have two Devonthink databases and a global inbox. 

Attempt to search all, or single, database(s) from Raycast results in error. 

### Expected Behaviour

database search and results returned.

**Comment by kudrykv** [comment]
Please try disabling Geolocation tick in extension preferences at this time 

#4179
