### ISSUE TITLE
[Iconify — Search Icons] ...

### ISSUE THREAD

**Issue by lacherogwu** [raycast/extensions#4203]
### Extension

https://www.raycast.com/destiner/iconify

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20
```

### Steps To Reproduce

1. Lunch `View Icons` command
2. Start typing `waffle` and type it fast

### Current Behaviour

Showing error page

### Expected Behaviour

Show icons

**Comment by sxn** [comment]
This issue still persists. @Destiner any chance you can have a look? As it stands, the command seems to be unusable 😅 

https://user-images.githubusercontent.com/1155589/222105106-7469a460-7dd1-440b-a147-743a91b2964b.mov
