### ISSUE TITLE
[Shell] Add ability for input

### ISSUE THREAD

**Issue by zhengliw** [raycast/extensions#4205]
### Extension

https://www.raycast.com/asubbotin/shell

### Description

Currently, the extension runs the command and returns the output.

There are some programs though, that do require an input to do something useful. It would be awesome if you could make the interaction frames support inputs! Thanks!

### Who will benefit from this feature?

Well, as said, people who have to use commands/programs that require runtime input.

### Anything else?

-none-

**Comment by KELiON** [comment]
Hey, @zhengliw, thanks for reporting! Unfortunately, as I mentioned in [other issue](https://github.com/raycast/extensions/issues/3838#issuecomment-1346003516) this extension was designed only for simple use cases (input/output) and there is no purpose of supporting everything, that terminal apps support (like text formatting or user input).

Instead I can suggest to put commands in Raycast, but launch them in Terminal/iTerm/Warp. You can do it either by cmd+enter or by checking "Use Terminal/iTerm" checkbox in extension settings.
