### ISSUE TITLE
[Slack] ...

### ISSUE THREAD

**Issue by kimpa888** [raycast/extensions#4212]
### Extension

https://www.raycast.com/mommertf/slack

### Description

I'm trying to follow the instructions here: 

https://github.com/raycast/extensions/blob/34c65c7f190ad172e46c75384600aa938f932e98/extensions/slack/README.md

But at step 5 I get an error and can't proceed:

<img width="521" alt="CleanShot Safari 2023-01-10 at 12 25 47@2x" src="https://user-images.githubusercontent.com/116798295/211539673-97be875d-dec2-4cfa-adc6-e8c88c26798f.png">

### Steps To Reproduce

Follow steps in README and fail at step 5

**Comment by pernielsentikaer** [comment]
Hi 👋 

You need to switch to YAML, try that 😊

![Raycast-FPWi2mg2](https://user-images.githubusercontent.com/38033107/211540943-53b12457-7973-43c6-a227-784eaca9944d.png)

**Comment by kimpa888** [comment]
Thanks for the quick response, it did the trick!

Perhaps you should add this instruction in the README for dummies like me

🤪

//Henirk

**Comment by pernielsentikaer** [comment]
I updated the `README`, thanks for flagging 😊
