### ISSUE TITLE
[send to memo] it show "Check that API MEMO URL is correct", but in fact it's effected

### ISSUE THREAD

**Issue by stuchilde** [raycast/extensions#4215]
### Extension

https://www.raycast.com/ahonn/send-to-flomo

### Description

![image](https://user-images.githubusercontent.com/18589232/211581007-2e252353-bc56-41fb-961c-4ec2f1e3b470.png)
![image](https://user-images.githubusercontent.com/18589232/211581173-3a73a8bc-f237-4f64-92ae-1372afa3b033.png)

**Comment by pernielsentikaer** [comment]
@ahonn / @fankaidev does anyone of you have the possibility to check this? I don't have an API key

**Comment by ahonn** [comment]
@stuchilde
 I can't reproduce it here, please try if you can reproduce it again and provide more details (screen recording, etc.). 
From the code implementation, it looks like there may be a problem with flomo's API response.
