### ISSUE TITLE
[Obsidian] Automatically exclude files

### ISSUE THREAD

**Issue by diminutivesloop** [raycast/extensions#4216]
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

The "exclude following folders" option should automatically exclude any files or folders included in the Obsidian "Excluded files" option and should also exclude the `.trash` folder. In addition any user-defined excludes would be combined with these default excludes rather than overwriting them.

**Comment by marcjulianschwarz** [comment]
Hi @diminutivesloop, 
thank you for the suggestion.

I will add your idea to the [roadmap](https://github.com/users/marcjulianschwarz/projects/1).
