### ISSUE TITLE
[Obsidian] Support starred files

### ISSUE THREAD

**Issue by diminutivesloop** [raycast/extensions#4217]
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

There should be a command for viewing files and searches starred in Obsidian. Alternatively instead of creating a separate command the existing "Pinned Notes" command could be renamed and repurposed to work with starred files instead. This may reduce user confusion as the "Pinned Notes" feature could be confused with Obsidian's own "pinned tabs" functionality. In fact I originally assumed the "Pinned Notes" command was for viewing pinned tabs and thought it was broken until I realized how it was supposed to work.

**Comment by marcjulianschwarz** [comment]
Hi @diminutivesloop,
thank you for the suggestion. I will add this to the extensions roadmap.

Also, for more details on the current feature set of the extension you can have a look at this [README](https://github.com/marcjulianschwarz/obsidian-raycast#overview)

**Comment by marcjulianschwarz** [comment]
Just adding some information for my future self or anyone willing to contribute:

- starred files can be found in `.obsidian/starred.json`
- test whether modifying starred.json results in unexpected behavior in Obsidian or has other unwanted side effects

**Comment by diminutivesloop** [comment]
@marcjulianschwarz It would be a good idea to add a link to the roadmap to the README as it's currently not very discoverable;.
