### ISSUE TITLE
Custom colors for Item.Accessory tags

### ISSUE THREAD

**Issue by reflog** [raycast/extensions#4219]
### Description

Hi!
I'm creating an extension to search through documents on Paperless NGX.
Each document is tagged, and each tag has a color.
It would be great if I could use those colors for Item.Accessory .
Right now I can't because it accepts `Color` and not `ColorLike` so it discard custom colors and only accepts standard ones.

**Comment by mathieudutour** [comment]
Thanks for the feature request! At the moment we aren't really happy with how arbitrary colors work on tags so we first want to fix that before considering allowing custom colors

**Comment by mathieudutour** [comment]
Should work in 1.47.0!

**Comment by reflog** [comment]
awesome, thanks @mathieudutour !
