### ISSUE TITLE
[Formula 1] ... Date Format Prefs

### ISSUE THREAD

**Issue by mattie-g** [raycast/extensions#4222]
### Extension

https://www.raycast.com/csigritz/f1-standings

### Description

Ability to change the date format other than MM/DD/YYYY

### Who will benefit from this feature?

Users other than those in the US, being able to change it is a minor feature but would be a nice to have. Completely understand if its not worth it.

**Comment by sxn** [comment]
hi @mattie-g – thanks for bringing this up. The extension already uses `toLocaleDateString` to format dates, so it _should_ work as expected. Unfortunately since Node can't figure out users' locale, it seems to default to `en_US`. I'll look into what Raycast can do better here. :)

**Comment by mathieudutour** [comment]
It's now fixed in 1.46.0!
