### ISSUE TITLE
[Tailwind CSS] Option to copy class name without leading period

### ISSUE THREAD

**Issue by tomgenoni** [raycast/extensions#4224]
### Extension

https://www.raycast.com/vimtor/tailwindcss

### Description

In my workflow using Tailwind I'm nearly always populating `class` or `className` attributes and it would be great if I could copy just the class name without the period. 

### Who will benefit from this feature?

I assume this is the way most people use Tailwind so I imagine it would be widely used.

### Anything else?

Thank you for making this plugin! Super helpful.

**Comment by vimtor** [comment]
Great idea! I will implement this probably the next weekend

**Comment by tomgenoni** [comment]
Thank you! This is great.
