### ISSUE TITLE
[Spotify Controls] ...

### ISSUE THREAD

**Issue by nfdiop** [raycast/extensions#4226]
### Extension

https://www.raycast.com/thomas/spotify-controls

#### Error:
```

```

### Steps To Reproduce

1. Mac OS Ventura
2. Click on Play spotify
3. Raycast closes and nothing happes

**Comment by ron-myers** [comment]
Hey @nfdiop 👋  - I don't see anything under the error or behaviors sections.  When you have time please provide some more context on your issue.  😄

**Comment by nfdiop** [comment]
> Hey @nfdiop 👋 - I don't see anything under the error or behaviors sections. When you have time please provide some more context on your issue. 😄

Hello,
Thanks for looking into this. I didn’t see any issue myself. I just noticed that it didn’t ask authorisation to my spotify

**Comment by thomaspaulmann** [comment]
For the Spotify Controls extension, you need the Spotify desktop app installed. @nfdiop do you have it installed?
