### ISSUE TITLE
[Home Assistant] Don't show hidden entities

### ISSUE THREAD

**Issue by Mavamaarten** [raycast/extensions#4228]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Description

Entities in Home Assistant can be hidden in the UI. Once hidden they will not be shown in the UI, but they can still be targeted by services. Currently, the Raycast plugin still shows those hidden entities. This is annoying, because I have a template light which is a proxy for a different hidden light entity. Now this hidden light still pops up in the list of lights, even though I did hide it.

For example, this is the list of lights in Home Assistant:
<img width="389" alt="Screenshot 2023-01-11 at 11 54 12" src="https://user-images.githubusercontent.com/7346786/211788595-17b4ad01-1916-4118-af4d-66b9eaa54439.png">

This is that same list in Raycast Home Assistant:
<img width="749" alt="Screenshot 2023-01-11 at 11 55 42" src="https://user-images.githubusercontent.com/7346786/211788788-ffabafaf-bae9-46df-a7e6-e02600b6df49.png">

As you can see this "transformer light" should not appear in this list.

Showing or hiding hidden entities could be a setting in the plugin.

### Who will benefit from this feature?

Everyone with hidden entities

**Comment by tonka3000** [comment]
@Mavamaarten Like the request but it seems that the Home Assistant API don't provide information about the hidden state of an entity which would be required for that feature.
