### ISSUE TITLE
[Set Audio Device] Cannot use audio device as a favorite if it contains a special character

### ISSUE THREAD

**Issue by sebj54** [raycast/extensions#4229]
### Extension

https://www.raycast.com/benvp/audio-device

### Description

I would like to set my airpods as the audio device with the "Set Output Device to Favourite" command.

It does not work because my device name has a special character.
It is: `AirPods Pro de Sébastien`.

### Steps To Reproduce

1. Rename a Bluetooth device to include a special character like `é`
2. Set this device as the favorite
3. Try to use the "Set Output Device to Favourite" command
4. See error: "Favourite output audio device could not be set"

### Current Behaviour

"Set Output Device to Favourite" never set my favorite audio device. It works if I manually set output device from the "Set Output Device" command.

### Expected Behaviour

"Set Output Device to Favourite" should set my favorite audio device

**Comment by sebj54** [comment]
Issue is still there @raycastbot :)

**Comment by popbones** [comment]
I have the same problem too

**Comment by popbones** [comment]
Recently I noticed that although set to favorite doesn’t work for me, toggling between favorites works. Not sure if this provides any useful information.
