### ISSUE TITLE
[Tower Repositories] Open in Code now just shows repo in Finder

### ISSUE THREAD

**Issue by lmartins** [raycast/extensions#4232]
### Extension

https://www.raycast.com/tdwesten/tower

### Description

Up until today this would work as expected, opening the repo in a new VS Code editor. Today, for some reason, it just shows the repo folder in Finder.

### Steps To Reproduce

Running:

1. macOS Ventura 13.1
2. Raycast 1.45.3
3. VS Code 1.74.3

**Comment by tdwesten** [comment]
@lmartins Hi, thanks for reporting this issue. I tried to reproduce this bug but here with Raycast 1.46.1 on macOS Ventura 13.1 with VS code 1.74.3 it work without problems. Can you update Raycast and test it again?

**Comment by lmartins** [comment]
Hi @tdwesten a couple of days after noticing this the issue went away. I thought it followed an update to this extension, maybe I've got it wrong. Anyway, looks like is not an issue anymore. Sorry I get back here to close the issue.

**Comment by tdwesten** [comment]
Hi @lmartins NP!
