### ISSUE TITLE
[Google Chrome Profiles] ...

### ISSUE THREAD

**Issue by lionelfloriani** [raycast/extensions#4234]
### Extension

https://www.raycast.com/frouo/google-chrome-profiles

### Description

Hi there! Thanks for all the features. RayCast boosted my productivity so much.
I would like to ask if it will be possible to add a feature allowing the user to re-arrange the order of how the profiles are listed?
It would boost my productivity even higher hehe. 

Thanks for reading me!

Have a nice one

**Comment by frouo** [comment]
Hello @lionelfloriani ! Thank you for using the Google Chrome Profiles extension 🤩

I am not really sure on how we could setup this feature using the Raycast UI elements. Do you have any suggestion, like screenshots of another extension allowing user to re-order a list?

However, I thought of possibly 2 workarounds that may help:

1. use the Raycast shortcut (hold `⌘` key) to access an item quickly

<img width="788" alt="image" src="https://user-images.githubusercontent.com/2499356/212774563-831620e6-e94f-4c71-8e06-ef50f5b650bb.png">

2. or, edit your profile name and prefix it with 1, 2, 3, or a, b, c, etc.
 
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/2499356/212776381-7a453815-cd29-4f32-908a-fe31ed3e2158.png">

Does it make the thing for you?
