### ISSUE TITLE
[Music] Add current playing to playlist

### ISSUE THREAD

**Issue by gukj** [raycast/extensions#4245]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

When a song is playing, offer the ability to either:
- add that song to either a predefined playlist
- add the song to a playlist that the user picks from a list
- add the song to the currently playing playlist (very fitting for my specific use case, but likely not as common a need)

### Who will benefit from this feature?

My use case is that I often listen to an entire playlist and then let Apple Music "auto-play" recommended songs. Some of these really go well with the playlist in question so I'd like to add them to it. My current workflow for this is that I open Apple Music and manually add the song to the playlist. it would be awesome to be able to do this from Raycast.

**Comment by Rawnly** [comment]
Hi thanks for the request! I'm not sure that the third point is possible via AppleScript. But I'll try something in the next release!

Anyway I see your use case, pretty similar to mine with Spotify 😅

**Comment by Rawnly** [comment]
I'll might implement the first option and then with an update transform
It in the second one 🙂

**Comment by gukj** [comment]
Insane response time - thank you so much!

Yeah, the third might also be a bit weird for most users. It's pretty likely that the `currently playing song` is already in `currently playing playlist`. Could potentially be solved by first checking if `currently playing song` is in `currently playing playlist` and then offer the option, but I'm not a pro at Raycast scripting so not sure if it's even possible to have optional features in that way.

**Comment by Rawnly** [comment]
Unfortunately, the whole `Add to *` is not stable at all as you can read the following [from official apple forums][forum-link]:

> for tracks in AM's playlist, when the playlist is not added to library: duplicate current track to source "Library" or duplicate current track to first source works
---
> for tracks in AM's playlist, when the playlist is added to library (in the sidebar): cannot add track to library, we can only add it to an user playlist with duplicate current track to user playlist "name of user playlist"; running duplicate current track to first playlist of first source succeeds but Music hangs needing a force quit (and at the next start the track is not added)
---
> for tracks in AM's radio or with autoplay: cannot add track to library nor to user playlist; running duplicate current track to first playlist of first source succeeds but the track is not actually added, same if trying to add it to playlist: the command runs, but the track is immediately removed

I'll try something in the weekend and see if I can get something barely stable 👍 

> but I'm not a pro at Raycast scripting

You don't have to! Contributions are welcome! The Music extension is all `applescript` ;)

[forum-link]: https://developer.apple.com/forums/thread/694200?answerId=697573022#697573022

**Comment by gukj** [comment]
Great job! Thank you so much for this!
