### ISSUE TITLE
[Arc] "Search Tabs" and "Search Spaces" commands don't work

### ISSUE THREAD

**Issue by aesign** [raycast/extensions#4246]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

Thank you for the latest update, always wanted to browse arc tabs and spaces with Raycast. Unfortunately, both commands are not working for me as they throw an error.

When I run "Search Tabs":

`Error: Command failed with exit code 1: osascript -e 
    on escape_value(this_text)
      set AppleScript's text item delimiters to the "\""
      set the item_list to every text item of this_text
      set AppleScript's text item delimiters to the "\\\""
      set this_text to the item_list as string
      set AppleScript's text item delimiters to ""
      return this_text
    end replace_chars

    set _output to ""

    tell application "Arc"
      set _window_index to 1
      set _tab_index to 1
      
      repeat with _tab in tabs of first window
        set _title to my escape_value(get title of _tab)
        set _url to get URL of _tab
        set _location to get location of _tab
        
        set _output to (_output & "{ \"title\": \"" & _title & "\", \"url\": \"" & _url & "\", \"windowId\": " & _window_index & ", \"tabId\": " & _tab_index & " , \"location\": \"" & _location & "\" }")
        
        if _tab_index < (count tabs of first window) then
          set _output to (_output & ",\n")
        else
          set _output to (_output & "\n")
        end if
        
        set _tab_index to _tab_index + 1
      end repeat
    end tell
    
    return "[\n" & _output & "\n]"
   
629:637: execution error: Arc got an error: Can’t make location of item 1 of every tab of window 1 into type specifier. (-1700)
    at Lg (/Users/aesign/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:49:58)
    at /Users/aesign/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:49:8090
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async we (/Users/aesign/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:49:41572)
    at async Object.l5 [as current] (/Users/aesign/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:49:41651)`

When i run "Search Spaces":

`
Error: Command failed with exit code 1: osascript -e 
    set _output to ""

    tell application "Arc"    
      set _space_index to 1  
      
      repeat with _space in spaces of front window
        set _title to get title of _space
        
        set _output to (_output & "{ \"title\": \"" & _title & "\", \"id\": " & _space_index & " }")
        
        if _space_index < (count spaces of front window) then
          set _output to (_output & ",\n")
        else
          set _output to (_output & "\n")
        end if
        
        set _space_index to _space_index + 1
      end repeat
    end tell
    
    return "[\n" & _output & "\n]"
   
98:549: execution error: Arc got an error: Can’t make spaces of window 1 into type specifier. (-1700)
    at Z5 (/Users/aesign/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:30:57)
    at /Users/aesign/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:30:8086
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Re (/Users/aesign/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:30:41401)
    at async Object.Ia [as current] (/Users/aesign/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:38:32)
`

### Steps To Reproduce

When running both "search tabs" and "search spaces"

### Current Behaviour

They throws an error

### Expected Behaviour

They should list Arc's Tabs and Spaces

**Comment by thomaspaulmann** [comment]
Mmh... This is weird. Which version of Arc do you have installed?

**Comment by aesign** [comment]
> Mmh... This is weird. Which version of Arc do you have installed?

@thomaspaulmann  My bad, I was not on latest. Works after updating! Thank you.

By the way, do you plan to add actual tab names instead of page titles?

**Comment by thomaspaulmann** [comment]
Though, that also means that my version check doesn't work... The tab title popped up. I think it's an issue with Arc's AppleScript. Will mention it to them.

**Comment by hurshagrawal** [comment]
Thank you for the callout, @aesign! Just fixed and should be live on Thursday.

**Comment by tan-zx** [comment]
I experienced this issue, upgraded Arc to latest, but instead of showing the error message, it just kept loading for a while. But eventually, it finishes loading and works as expected!

Thank you so much for creating this, it really helps complement the way I use Arc — I'm still bookmarking a bunch of sites to come back to in the long term, but esp with huge/nested folders, sometimes searching through these bookmarks is not easy!
