### ISSUE TITLE
[API Feature Request] Dropdown - allow no default value

### ISSUE THREAD

**Issue by Padamdam** [raycast/extensions#4248]
### Description

At the moment (1.45.3) it is not possible to have a Dropdown with no value (or at least I didn't find a way).

The Dropdown automatically selects the first item in an array.

It would be great if we could allow empty value for Dropdowns as well as the ability to allow clearing selected value.

Thanks for all your work on this awesome app !

**Comment by Padamdam** [comment]
I'm working on an extension for Paperless-ngx.

When posting a document through the REST API, all fields are optional (except the file).

For example, the user can leave Document Type value empty and paperless will try to assign it automatically.

With current behavior, it is not possible to let paperless assign automatically the right metadata, user is forced to select from available options.

**Comment by mathieudutour** [comment]
then you can add another dropdown item "Automatic" or something

**Comment by Padamdam** [comment]
That's good way to bypass. But I'll need to remove this 'automatic' value from my model before POSTing.

I still believe this should be a useful feature to have going forward.

**Comment by mathieudutour** [comment]
It's unlikely that we will add that, we believe that it's better to have an explicit item with a proper label for the users.
