### ISSUE TITLE
[search-npm] Add a command to copy package version

### ISSUE THREAD

**Issue by sedghi** [raycast/extensions#4250]
### Extension

https://www.raycast.com/mrmartineau/search-npm

### Description

It would be great if we can have a command to copy the package version only.

### Who will benefit from this feature?

Everyone

**Comment by mrmartineau** [comment]
@sedghi do you mean the latest version number?

**Comment by sedghi** [comment]
Yes exactly.

**Comment by thomaspaulmann** [comment]
Want to contribute to it? Should be easy to add an action for it.
