### ISSUE TITLE
[Toothpick] Device support form

### ISSUE THREAD

**Issue by LiquidLemon** [raycast/extensions#4251]
### Extension

https://www.raycast.com/briankosw/toothpick

### Description

**Device brand and model**
Sony WF-1000XM4

**Device data**
{"WF-1000XM4":{"device_address":"14:3F:A6:F5:92:49","device_batteryLevelMain":"100%","device_firmwareVersion":"1.2.6","device_minorType":"Headset","device_productID":"0x0DE1","device_services":"0x800019 < HFP AVRCP A2DP ACL >","device_vendorID":"0x054C","device_connected":"true"}}

**Comment by LiquidLemon** [comment]
IDK what I can do here, the link is clearly there.

**Comment by VladCuciureanu** [comment]
Yeah, the template I used is outdated. You can ignore the warnings. I'll update them with the next update.
As for the device data... Thanks for your submission! In the next update I'll add a custom icon and a battery level indicator, but that's all I can do for now, as I don't have access to more functionalities.

**Comment by VladCuciureanu** [comment]
@raycastbot close this issue
