### ISSUE TITLE
[1Password] List not updating

### ISSUE THREAD

**Issue by GeoJunkie** [raycast/extensions#4252]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

The password list isn't updating. Everything on the list is exactly what it was when I first installed the extension and doesn't change as accounts are added, removed, renamed, etc.

I've gone as far as uninstalling and reinstalling the extension and it's still using that original list. Note that this has been months, so waiting for something to sync isn't working.

### Steps To Reproduce

1. Add a new account to 1Password
2. Access the extension
3. Search for the new account

### Current Behaviour

The new account doesn't appear

### Expected Behaviour

The new account should appear.

**Comment by khasbilegt** [comment]
What 1Password version are you using? If you're using 1Password with opbookmarks, you have to run opbookmarks to update the metadate.

**Comment by GeoJunkie** [comment]
> What 1Password version are you using? If you're using 1Password with opbookmarks, you have to run opbookmarks to update the metadate.

I'd forgotten the requirement to run `opbookmarks`. Ran that and it's synced. Thanks!

Side note: The only reference to `opbookmarks` I could find was in the [source code](https://github.com/raycast/extensions/blob/34c65c7f190ad172e46c75384600aa938f932e98/extensions/1password/src/onePassword/onePassword8.ts#L5-L15). I got this prompt when first setting it up, but couldn't find it again until just now. Could that be added to the extension docs or as a separate prompt? I can add a separate feature request if needed.

**Comment by thomaspaulmann** [comment]
Can we make this somehow easier? Maybe we can bundle the CLI? Then folks don't need to install it themselves and only need to enable it in 1Password 8.

**Comment by pernielsentikaer** [comment]
I remember @dteare said something about they're working on a new CLI to access all this data easier - is that correct @dteare

**Comment by GeoJunkie** [comment]
@pernielsentikaer I apologize for the delayed response. I'd missed that there was an update to this issue.

It still seems to be requiring a run of `opbookmarks` to get the update. At least if I try to access a newly-created login within a couple minutes. I'll test some more to see if there's a delay in syncing a new one or if it's still not picking it up.

**Comment by GeoJunkie** [comment]
Hi @pernielsentikaer , it actually seems to be working less well now. Running `opbookmarks` doesn't update the list in Raycast. The only way to get it to be updated is by running `op signin` from the CLI, then signing back in on Raycast.
