### ISSUE TITLE
Would love the Music extension to support volume for the Music app

### ISSUE THREAD

**Issue by danfigmatokens** [raycast/extensions#4256]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

It'd be great if I could control the Music app volume by 5% increments (simple Music volume up and Music volume down commands would be great). Since the Music app's volume is separate from the system volume (particularly when playing to HomePods) it's a pain to have to open the app every time I want to adjust the volume.

### Who will benefit from this feature?

Anyone that likes to adjust their music volume separate from system sounds.

**Comment by Rawnly** [comment]
This should be pretty straight forward! I'll add it to the next PR!

**Comment by danfigmatokens** [comment]
Super happy this is in! But man, really wish you had gone with 5% increments like in the original request. When connected to HomePods, 10% is just too big of a jump a lot of the time. For background music I am constantly wanting to set it to 5%.
