### ISSUE TITLE
[Arc] Unable to search spaces & tabs in new update

### ISSUE THREAD

**Issue by abass** [raycast/extensions#4258]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

<img width="739" alt="CleanShot 2023-01-14 at 00 21 40@2x" src="https://user-images.githubusercontent.com/5505994/212458989-59b2702c-42c3-43ef-936a-8e6e9eb9f1c9.png">

Error: Command failed with exit code 1: osascript -e 
    set _output to ""

    tell application "Arc"    
      set _space_index to 1  
      
      repeat with _space in spaces of front window
        set _title to get title of _space
        
        set _output to (_output & "{ \"title\": \"" & _title & "\", \"id\": " & _space_index & " }")
        
        if _space_index < (count spaces of front window) then
          set _output to (_output & ",\n")
        else
          set _output to (_output & "\n")
        end if
        
        set _space_index to _space_index + 1
      end repeat
    end tell
    
    return "[\n" & _output & "\n]"
   
98:549: execution error: Arc got an error: Can’t make spaces of window 1 into type specifier. (-1700)
    at Z5 (/Users/alex/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:30:57)
    at /Users/alex/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:30:8086
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Re (/Users/alex/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:30:41401)
    at async Object.Ia [as current] (/Users/alex/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-spaces.js:38:32)

### Steps To Reproduce

Search spaces, approve permissions, then try to search spaces

### Current Behaviour

Errors out

### Expected Behaviour

Not erroring out

**Comment by ankitchouhan1020** [comment]
Tried using latest Arc version?

**Comment by thomaspaulmann** [comment]
This should be fixed with a version check.
