### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by darioristic** [raycast/extensions#4265]
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```

```

**Comment by sxn** [comment]
hi @darioristic – could you update the top post & title with information on what problems you're experiencing? If you're not experiencing it anymore, feel free to close this issue or ping me or @pernielsentikaer and we'll close it. 😺

**Comment by sxn** [comment]
closing as there's nothing actionable sadly. @darioristic feel free to ping me if you can provide more details on what's happen, and I'll reopen the issue. 😉
