### ISSUE TITLE
[Google Workspace] Search and Reval Google Drive Files/Folders in Finder

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#4268]
### Extension

https://www.raycast.com/raycast/google-workspace

### Description

It would be awesome if there was a command that searched Google Drive and upon selection would reveal the file/folder in Finder.

Because of the way Google Drive mounts the drive locally, the files don't get indexed in MacOS. Additionally, the Google Drive application search only returns limited results.

The results of the Raycast Google Workspace extension are much better, but instead of opening in the browser, most often my workflow requires dealing with the files in Finder.

Opening the file locally in the associated application would be another great addition.

### Who will benefit from this feature?

Anyone that works with Google Drive files locally.

**Comment by thomaslombart** [comment]
Unfortunately, Google Drive's API provides info about the files on Google Drive and doesn't have access to their location on the macOS file system, so I'm not sure this feature would be easily feasible.

That being said, there are still things that can be done to enable this feature. Here are some ideas:
- Get the path of where Google Drive mounts locally (through a preference maybe?) and then construct the Finder path in the extension
- Open the `File Search` Raycast command from the extension (Google files were properly indexed on this one)

**Comment by christianmagill** [comment]
> That being said, things can still be done:

Using a preference to construct the path would work brilliantly!

The default `File Search` Raycast command doesn't return files on the local Google Drive for me. There's another Google Drive extension with a `File Search` command, but that seems to have problems with just the sheer amount of files on my Google Drive. It attempts to index and errors out. Also, by the nature of the indexing, it would mean whether a file/folder shows up depends on how long ago it was created and when the last index was built.
