### ISSUE TITLE
[Music] Add Songs and Albums to Favorites Playlist

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#4272]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

This request relates to: https://github.com/raycast/extensions/issues/1602

It would be great if there could be a setting for providing/enabling a "Favorites" playlist. 

If provided "Play Library Track" and "Play Library Album" would gain an option to save to the "Favorites" playlist.

Ultimately I'd like to then use a MacOs Shortcut to Queue those items to the Music Apps Up Next Playlist.

### Who will benefit from this feature?

Definitely me 😁

**Comment by Rawnly** [comment]
Unfortunately, the "add to playlist *" action can't be performed via AppleScript. And the current architecture of the extension is all AppleScript based.

**Comment by Rawnly** [comment]
@raycastbot close this issue

**Comment by christianmagill** [comment]
@Rawnly From what I understand, you can add to a playlist with the duplicate command. Unless things have changed...

Add a track to a playlist:

Here we are copying a track object into the playlist.

```
duplicate trk to the end of user playlist "tmpList"
duplicate track id 12693 to end of user playlist "tmpList"
```

Source: https://256stuff.com/gray/docs/misc/itunes_applescript_commands/

**Comment by Rawnly** [comment]
Itunes and Music api are not the same. 
Running the script you just sent me throws `Music got an error: Can’t set end of user playlist "<playlist_name>" to track id <track id>`

The script I was using before was: 
```osascript
tell application "Music"
	duplicate current track to playlist "<playlist_name>"
end tell
```

But then it throws : 
```osascript
error "Music got an error: Can only duplicate subscription tracks to library source."
```

**Comment by Rawnly** [comment]
Further reference: https://github.com/raycast/extensions/issues/4300

**Comment by christianmagill** [comment]
Weird,... I know an Alfred Workflow I was using previously uses a similar setup. Thanks for your attention on this anyways.

https://github.com/caleb531/play-song/blob/main/resources/config.applescript#L215

**Comment by Rawnly** [comment]
I'd like to figure out a solution too, I'll check the Alfred workflow to see if I'm missing something!

**Comment by SKaplanOfficial** [comment]
Hi @Rawnly, I know this is a bit late, but I just found that you can add tracks to playlists by using the move command, e.g.:
```
tell application "Music"
	move current track to playlist "Custom Playlist"
end tell
```
It adds the track to the playlist without actually "moving" it out of any others. Great wording on Apple's part...

**Comment by Rawnly** [comment]
I'll try tonight! Thanks!

**Comment by Rawnly** [comment]
@SKaplanOfficial this doesn't work for me :( 
![CleanShot 2023-02-02 at 13 40 39@2x](https://user-images.githubusercontent.com/16429579/216327665-d23e8907-d723-4fd6-bf97-c4289bbd751c.png)

**Comment by christianmagill** [comment]
@Rawnly, everything I've read points to duplicating the tracks. Did you have any success with that? By its nature, any tracks/albums added with this action would already be in the user's library since that's where the items are located via the commands.

**Comment by Rawnly** [comment]
@christianmagill 

> Did you have any success with that

If the song is not in the user library no.

Your point makes sense, but I can't see any other way to add songs to a playlist.
If you Google about adding a track to a playlist, these are the ways they are suggested in the forums/websites.

**Comment by christianmagill** [comment]
So what would be the difference between what we need to do, and the command to "Love and Add to Library"? Wouldn't that scripting get the track into the user's library where it could then be added to a playlist? Sorry for my rudimentary understanding here.

**Comment by Rawnly** [comment]
Let's suppose I'm listening to my "new music mix" and I find a song that fits with a playlist I'm creating, I might want to add it to this playlist but not to the Library. This behavior is currently impossible via `AppleScript` but is possible via the app.

---

So the thing is: I can't add a new command that works only in some situations (eg library songs) since I can't prevent it from running with other tracks. 

This is because the result will be a continuous error reporting here on GH with duplicate issues about "add to playlist doesn't work" etc...

**Comment by SKaplanOfficial** [comment]
@Rawnly I misunderstood the goal before, my bad! Nonetheless, I think this does what you want:

```
tell application "Music"
	set theName to name of current track
	set theArtist to artist of current track
	set theAlbum to album of the current track
	set existingTracks to get tracks of source "Library" whose name is theName and artist is theArtist and album is theAlbum
	
	if (count of existingTracks) = 0 then
		set theCount to count of tracks of source "Library"
		duplicate current track to source "Library"
		repeat while theCount = (count of tracks of source "Library")
			delay 1
		end repeat
	end if
	
	set theTrack to first track of source "Library" whose name is theName and artist is theArtist and album is theAlbum
	duplicate theTrack to playlist "Custom Playlist"
end tell
```
This works for streamed and non-streamed songs alike, on Ventura 13.2 at least.

**Comment by Rawnly** [comment]
@SKaplanOfficial this seem to work! Thank you!
