### ISSUE TITLE
[Web Converter] Tailwind Spacing Units

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#4274]
### Extension

https://www.raycast.com/nielsvanrijn/web-converter

### Description

It would be awesome to be able to convert to the closest Tailwind spacing unit on the default scale. 

Perhaps you could have two options if necessary, one that shows the closest default and another that has an arbitrary value.

The results for "117px" would look something like...

`28                                to Closest Tailwind Spacing (112px)`
`[117px]                                   to Tailwind Arbitrary Value`

Or if an exact match

`28                                         to Tailwind Spacing (112px)`

### Who will benefit from this feature?

People who find remembering the default Tailwind spacing scale difficult.

### Anything else?

Here's the spacing scale https://tailwindcss.com/docs/customizing-spacing#default-spacing-scale

**Comment by nielsvanrijn** [comment]
Fixed in https://github.com/raycast/extensions/pull/7092
