### ISSUE TITLE
[Currency Exchange] Historic exchange rate lookup for an earlier day

### ISSUE THREAD

**Issue by DavidJRas** [raycast/extensions#4281]
### Extension

https://www.raycast.com/xeric/currency-exchange

### Description

Can you add the ability to lookup the exchange rate on a particular historical date? 
This is needed for scenarios like tax time conversions looking at past transactions. Or after traveling looking at conversions for things on the day they happened in the past.

Could add it to the expressions you support like "1200 EUR to USD on 12/31/2022"

### Who will benefit from this feature?

I think many people who need currency conversion have these historic scenarios as well as current day scenarios.

**Comment by xeric** [comment]
@DavidJRas Ideally the quick answer is yes, I found there's a historical data API provided and I can leverage that one to get the exchange rate on particular date, I need some time to think about how to design a reasonable interactive UI or flow to enable this function, your proposal is quite ok, but it relies on end user manual input date time, I need a one more step further without manual input way.

**Comment by DavidJRas** [comment]
Sounds great. Thanks for considering.

**Comment by xeric** [comment]
@DavidJRas I've done this new requirement in latest version #4539, please notice that this function is depending on the https://www.exchangerate-api.com/docs/historical-data-requests. this API requires Pro, Business or Volume plans, it is not free.

**Comment by xeric** [comment]
Function provided. @raycastbot close this issue
