### ISSUE TITLE
[Slack] Out of memory in large slack workspace

### ISSUE THREAD

**Issue by yonatan-mitmit** [raycast/extensions#4284]
### Extension

https://www.raycast.com/mommertf/slack

### Description

Connecting to a large workspace (~1000 users, hundreds of channels)
Searching for users & channels crashes the extension quickly. 
The log contains the expected

Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20

### Steps To Reproduce

1. Set up integration as document
2. Configure access token
3. Search for users / channels
4. Extension crashes

### Current Behaviour

Extension crashes 

### Expected Behaviour

Extension doesn't crash

**Comment by everpeace** [comment]
I faced at this, too. I would be happy if this is resolved.
