### ISSUE TITLE
[Obsidian] It would be nice if the form inputs were tabable

### ISSUE THREAD

**Issue by steveperrycreative** [raycast/extensions#4286]
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

When using the Create Note command, it would be nice if the note's name input was initially selected ready for input. And then being able to tab to other inputs. At the moment, this is not possible.

### Who will benefit from this feature?

All users but especially those who don't want to or cannot use a mouse or trackpad.

**Comment by steveperrycreative** [comment]
Looking at this, it works with the Bear extension but not the Obsidian extension and I can see that it's using the same form component so it may be a bug rather than a feature request. Might be something to do with the default values being pulled in from prefs?

**Comment by marcjulianschwarz** [comment]
It is working fine for me (with the newest version from the store). The text is selected and one can use the Tab key to switch to the other fields.
Can you tell me how I could reproduce this issue?

**Comment by steveperrycreative** [comment]
I can confirm that this is now also working for me with the latest version.
