### ISSUE TITLE
[Music] missing HUD symbols

### ISSUE THREAD

**Issue by andrefgneves** [raycast/extensions#4290]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

Not sure if I didn't install the extension correctly, or if I'm maybe missing a font or something, but the icons shown in the confirmation HUD do not render correctly for me. Here's a screen shot:

<img width="299" alt="music" src="https://user-images.githubusercontent.com/3869532/212881825-117fcfd0-b99d-4eaa-bde7-d919bd98a9a9.png">

Any idea how to fix it?

**Comment by Rawnly** [comment]
Hi thanks for reporting, seems like you don't have sf symbols installed. 

installing it should fix this

**Comment by peterdev22** [comment]
Shouldn't SF symbols display on every Mac by default?

What MacOS version are you on currently @andrefgneves

**Comment by Rawnly** [comment]
@peterdev22 it should, but somehow happened the same to me when we introduced it in the extension (and I was on macOS 13.0)

**Comment by andrefgneves** [comment]
@peterdev22, I'm on `13.2 Beta (22D5038i)`.

Installing the SF Symbols app fixed it. Thank you!
