### ISSUE TITLE
[API Feature Request] JSON Schema for package.json keys specific to Raycast

### ISSUE THREAD

**Issue by rolandleth** [raycast/extensions#43]
Creating a schema for Raycast would make editing `package.json` with specific fields _so_ much easier (and safer) and adding it to https://www.schemastore.org/json/ would be even _awesomer_.

VSCode [supports](https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings) schemas and even schemastore.org out of the box and I suppose other editors do the same.

**Comment by dehesa** [comment]
Hey @rolandleth,

This is a good idea that @thomaspaulmann already brought forward. I will try to implement this by the next release.

**Comment by rolandleth** [comment]
Awesome! 💪🏻
