### ISSUE TITLE
[Music] 'Add to Playlist' command not working

### ISSUE THREAD

**Issue by MisreadPlebeian** [raycast/extensions#4300]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

Running the "Add to Playlist" command while the song is running results in an error and the song is not added to the requested playlist. This happens regardless of whether the command is manually initiated on Raycast or through keyboard shortcut. This error also happens regardless of which playlist is selected as the destination. 

### Steps To Reproduce

1. Have song playing in Apple Music

2. Run 'Add to Playlist' Command through Raycast (either through keyboard shortcut or command line)

3. Run into error

### Current Behaviour

Results in Error:

Error: Command failed with exit code 1: osascript -e tell application "Music" to duplicate current track to playlist "Music"
28:71: execution error: Music got an error: Can only duplicate subscription tracks to library source. (-10006)
    at O0 (/Users/Shrek/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:59)
    at /Users/Shrek/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:10477
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Mc (/Users/Shrek/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:38103)

### Expected Behaviour

Add song to playlist

**Comment by Rawnly** [comment]
Thanks for reporting! Can you please post the song you were trying to add?

**Comment by MisreadPlebeian** [comment]
It didn't work for any songs I tried to add. I've tried this command with ~ 10 different tracks from different artists over the past two days.

I've copied some songs that I tried this command with:
1. Snooze - Sza
2. LOVE. - Kendrick Lamar
3. Ballad of the Basement - WILLIS
4. Ruby Fields - Sarah and the Sundays

However, of note I can add songs to my library through the extension command.

**Comment by Rawnly** [comment]
I might have to remove this command. Unfortunately, Music doesn't allow adding a track to a playlist if the track is not present inside the user library. 

This has been my fault, while testing I only tried songs from my library.

https://www.macscripter.net/t/add-current-track-from-apple-music-to-playlist/72058/6

**Comment by andreaguida** [comment]
On my Mac the command "Add to playlist" have worked always good. Was one of the most used commands for me (for adding songs from a playlist to another). Can you restore the command, maybe adding in the readme file all the informations about the limitations with the songs that are not present in the user's library? Thanks! 🙏

**Comment by gukj** [comment]
@Rawnly Seems this feature was short-lived. Just wanted to add that I've been able to add songs that weren't in my library, so I think there's something else going on with this. Currently I can't add anything to playlists at all, doesn't matter if they're in my library or not.

**Comment by Rawnly** [comment]
```
25:29: syntax error: A end of line can’t go after this “to”. (-2740)
    at S0 (/Users/federicovitale/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:59)
    at /Users/federicovitale/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:10477
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async qc (/Users/federicovitale/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:38131)
```

I see, there's a typo at the end of the script! I'm sorry maybe prettier broke something just before pushing, @gukj can you  paste here the stack trace, so I can figure out if it's the same problem as mine.

**Comment by Rawnly** [comment]
@gukj I see, there's a typo in the script, thanks for reporting, something weird must be happened when merging

**Comment by Rawnly** [comment]
https://github.com/raycast/extensions/blob/6a5f1b00828ca7171b8c7e77efa78d951e7c37d5/extensions/music/src/util/scripts/current-track.ts#L36 here should be using `runScript` utility over the `tell`

**Comment by Rawnly** [comment]
Fixing here https://github.com/raycast/extensions/pull/4719

**Comment by Rawnly** [comment]
@gukj can you provide some feedback after the #4719 fixes? So I can close this issue

**Comment by gukj** [comment]
Works great 🎉
**Testing**
- Successfully added 5/5 song that we're already in my library
- Successfully added 5/5 songs that weren't in my library
**Issues**
- Doesn't respect the "Add song to Library when adding to playlist" setting. Instead adds song to library.
- Adding songs to playlist that aren't in the library takes a couple of seconds, but the Raycast UI doesn't show any indicator that something is going on, so I accidentally added a song three times by simple hitting return three times.

All-in-all I'm very happy with using it despite these issues. Thanks a ton for taking the time!
