### ISSUE TITLE
[Arc] Filter Tab Search by Pinned or Unpinned?

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#4304]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

It would be great if there was a way to search specifically for pinned or unpinned tabs. A lot of my pinned tabs end up acting more like bookmarks, so they can get in the way when I'm searching for more active tabs.

**Comment by thomaspaulmann** [comment]
Few ideas here:
- We could have a dropdown to filter different sections, e.g. "All Tabs", "Favorite Tabs", "Pinned Tabs", "Unpinned Tabs". Problem with that is that you can not have multiple sections enabled at the same time.
- We could add preferences to toggle each section. 
- We could have a setting for ordering the sections. This could work with both previous points.

WDYT?

**Comment by christianmagill** [comment]
Hm... When you say dropdown filter, do you mean within the cmd-k options or actual items in the results for selection? I often know which one of the sections I'm looking within. That being said I do searches within both categories. I think maybe the best option would be separate commands similar to option 1, but also with the setting to change the order of sections.

Thanks!
