### ISSUE TITLE
[Google Translate] ...

### ISSUE THREAD

**Issue by idhun90** [raycast/extensions#4311]
### Extension

https://www.raycast.com/gebeto/translate

### Description

Can you automatically recognize the language you entered?

I use English, Korean, and Chinese alternately. Is it possible to implement it so that you can automatically recognize the input language and translate it in a set language?

**Comment by gebeto** [comment]
Yesss, it is a good idea, I'll do it soon

**Comment by idhun90** [comment]
> Yesss, it is a good idea, thanks! I'll try to implement it soon

Thank you!
