### ISSUE TITLE
Cal.com - Share Meeting Links

### ISSUE THREAD

**Issue by Pucekcom** [raycast/extensions#4312]
### Extension

https://www.raycast.com/cal/cal-com-share-meeting-links

### Description

The current integration is supporting only individual links. I would love to have support for Team links.

### Who will benefit from this feature?

Everyone who is a cal.com users and books meetings with more than 1 person or within a company.

**Comment by pernielsentikaer** [comment]
This is not possible as it is right now; I contacted cal.com and it's not implemented yet

**Comment by GraphicOwls** [comment]
Yeah, I would really like this too!

**Comment by pernielsentikaer** [comment]
Still not possible, I had a chat with them and it's not a part of the API yet 😞

**Comment by MaxMusing** [comment]
I believe this is possible through the v2 API now: https://cal.com/docs/api-reference/v2/orgs-teams-event-types/get-all-team-event-types
