### ISSUE TITLE
Import Exported Code Stash

### ISSUE THREAD

**Issue by timcastillogill** [raycast/extensions#4313]
### Extension

https://www.raycast.com/ben-greenwood/code-stash

### Description

Having moved computer, I have exported my Code stash library, which worked perfectly. I'd now like to update my new computers 'code stash library' with the exported file. It's not clear where to drop the file and there doesn't seem to be the functionality built in.

### Who will benefit from this feature?

Anyone who wishes to move their stashes from machine to another

**Comment by ben-greenwood** [comment]
Hey @timcastillogill! Good shout, i've submitted a [PR](https://github.com/raycast/extensions/pull/4335) with a new import action 🙂

**Comment by ben-greenwood** [comment]
@timcastillogill #4335 has been merged in!

@raycastbot close this issue
