### ISSUE TITLE
[GitHub] Create Branch - load more issues

### ISSUE THREAD

**Issue by pernielsentikaer** [raycast/extensions#4317]
### Extension

https://www.raycast.com/raycast/github

### Description

Is it possible to load more items into `Linked Issue` dropdown? 

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/38033107/213230074-ca730bb3-f9d5-44b8-b9c6-1f4bc803c6e8.png">

### Who will benefit from this feature?

Everyone using this extension

**Comment by thomaslombart** [comment]
Sorry, didn't see that one! This would probably be feasible by adding a typeahead search to the dropdown fetching issues.
