### ISSUE TITLE
[Easy New File] Type in label

### ISSUE THREAD

**Issue by tomgenoni** [raycast/extensions#4323]
### Extension

https://github.com/raycast/extensions/tree/main/extensions/easy-new-file

### Description

<img width="305" alt="Screenshot 2023-01-18 at 7 51 21 PM" src="https://user-images.githubusercontent.com/1171072/213351594-789a18a0-607d-4646-8c28-8d417b91f026.png">

I assume you mean "Columns"
https://github.com/raycast/extensions/blob/5c120ad9aa4b177c783f401f6ad661ae58b202c8/extensions/easy-new-file/package.json#L45

Great plugin btw! I've wanted this for years. 

### Steps To Reproduce

Appears in the Raycast Extensions settings for this extension:

<img width="1000" alt="Screenshot 2023-01-18 at 7 57 20 PM" src="https://user-images.githubusercontent.com/1171072/213351767-d521055e-80b3-4cbd-a4ff-eac016fdc973.png">

### Current Behaviour

Says "File Item Coloums"

### Expected Behaviour

Should say "File Item Columns"

**Comment by koinzhang** [comment]
Hi @tomgenoni Thanks for the feedback, I have submitted a PR #4537 to fix text error.
