### ISSUE TITLE
[Code Stash] ENV and Properties languages

### ISSUE THREAD

**Issue by danulqua** [raycast/extensions#4339]
### Extension

https://www.raycast.com/ben-greenwood/code-stash

### Description

Add `env` and `Properties` to the languages list.

### Who will benefit from this feature?

Sometimes I save configs which are `environment` variables, so this absolutely won't be redundant.

**Comment by ben-greenwood** [comment]
Hi @danulqua, happy to add `env` but can you expand on the use of `Properties`?

**Comment by danulqua** [comment]
@ben-greenwood saw `Properties` in the VSCode languages list, and usually it's also being used for some kinds of configuration files. Thought it would be useful to share it along with `env`.
