### ISSUE TITLE
Change volume adjustment increments to 5%

### ISSUE THREAD

**Issue by danfigmatokens** [raycast/extensions#4341]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

Absolutely loved the quick turnaround and appreciate the feature addition with https://github.com/raycast/extensions/issues/4256 , thank you! Only complaint is that the original request was asking for 5% increments because when connected to external speakers (I'm using a pair of HomePods for example) a 10% jump is pretty huge. Ideal background volume with my setup is 5% and then jumping from 10 to 20% makes it too loud when I do want it a bit louder. Any external speakers with a loud maximum volume could use a finer grain of control.

### Who will benefit from this feature?

Anyone with external speakers capable of loud max volumes.

**Comment by Rawnly** [comment]
Uh ok! I can try adding an option in the extension preferences!

**Comment by danfigmatokens** [comment]
Nice! Obviously I understand this is probably a niche request, but would absolutely make a big difference for me with a super common annoyance in my daily life (and I'm sure there are others with loud external speakers connected). Thanks a lot! ❤️

**Comment by Rawnly** [comment]
Yes you might not  be the only one! Is a small change so no problem at all! I just opened the PR, now you can choose the volume size from a dropdown, `Low`, `Standard`, `Hight` wich are respectively: 5, 10 and 25
