### ISSUE TITLE
[Quick Event] Event only created for first calendar of calendar list

### ISSUE THREAD

**Issue by foss-** [raycast/extensions#4358]
### Extension

https://www.raycast.com/mblode/quick-event

### Description

Not possible to add event to calendars which are not the first calendar in list of calendars.

Btw - it would be nice improvement if calendar names could be read automatically. This would simplify setup and allow to get rid of the `Your calendars` field in extension settings.

This is Synology CalDAV calendars in case that is a factor and problem is not reproducible with Apple iCloud Calendars.

![cal](https://user-images.githubusercontent.com/5708172/213870323-7e34baf5-060b-4059-8e4f-b30565b016f0.png)

### Steps To Reproduce

1. manually entering calendar names in `Your calandars` in extension settings as `Calendar1, Calendar2, Calendar3, ...` (used the actual calendar names when testing)
2. try to add event to `Calendar2`

### Current Behaviour

Event is never created. What works is adding an event to `Calendar1`. Events added to any other calendar are not created.

### Expected Behaviour

Events should be created for all calendars.

**Comment by pernielsentikaer** [comment]
Hi @mblode 👋 

Do you have a clue what we could do?

**Comment by foss-** [comment]
This is persisting in v1.48.1.

**Comment by foss-** [comment]
Revisited this in version 1.51.3 and it works as expected. There is now a hint in the field when adding calendars to the extension to use the form `Calendar1,Calendar2,Calendar3`.
Tested this and it turns out, leaving out spaces indeed results in the extension working as intended. Closing.
