### ISSUE TITLE
[Todoist] Due Dates One Day Behind

### ISSUE THREAD

**Issue by alexlautin** [raycast/extensions#4359]
### Extension

https://www.raycast.com/thomaslombart/todoist

### Description

Due dates both in the menu bar and in the Raycast app are one day behind the actual set due date.

### Steps To Reproduce

1. Open Todoist Raycast app
2. Task is one day behind set due date

### Current Behaviour

One day behind set due date

### Expected Behaviour

Show actual due date

**Comment by thomaslombart** [comment]
Thanks for the feedback! Could you send some screenshots with the expected results? Would you mind sharing your timezone as well (there might be issues with it 😊)?

**Comment by hcrosse** [comment]
I've been having the same issue myself! Hope this helps.

**Timezone:** Eastern Standard Time (1:15pm at time of posting)

Menu bar:
<img width="363" alt="image" src="https://user-images.githubusercontent.com/12689177/214647928-2740ed47-f517-464c-8408-36544a73242c.png">

Todoist app:
<img width="848" alt="image" src="https://user-images.githubusercontent.com/12689177/214648099-da444b07-72cf-4de6-851a-2be5f9651de9.png">

**Comment by thomaslombart** [comment]
Thanks for the additional details. Unfortunately, I don't have any bandwidth for that at the moment. I'll eventually check it 😊

**Comment by gcoppeler** [comment]
Not sure what changed, or when, but my Raycast UI and menu bar are showing due dates 1 day (24 hours) after the actual due date on the task. However, this is only happening when there's a time on the due date. If the due date is just a day then it works as expected.

(Todoist app)
![Screenshot 2023-05-24 at 12 00 33 PM](https://github.com/raycast/extensions/assets/1764275/5fc81c59-689d-4000-8686-713ccac4fc25)
(Raycast AI)
![Screenshot 2023-05-24 at 12 00 58 PM](https://github.com/raycast/extensions/assets/1764275/72308862-03e0-454b-b6db-5fbc552ecec2)
(menu bar)
![Screenshot 2023-05-24 at 12 03 03 PM](https://github.com/raycast/extensions/assets/1764275/2b1bdaa4-51f5-4e1c-a2e6-f21275955405)
