### ISSUE TITLE
[Toothpick] Device Support Form

### ISSUE THREAD

**Issue by alex-berk** [raycast/extensions#4371]
### Extension

https://www.raycast.com/briankosw/toothpick

### Description

<b>Device brand and model</b>
Sony WH-1000XM3
<b>Device data</b>
{"WH-1000XM3":{"device_address":"XX:XX:XX:XX:XX:XX","device_firmwareVersion":"4.5.2","device_minorType":"Headset","device_productID":"0x0CD3","device_rssi":"-37","device_services":"0x800019 < HFP AVRCP A2DP ACL >","device_vendorID":"0x054C","device_connected":"true"}}

**Comment by VladCuciureanu** [comment]
Hey! While I do appreciate your submission, this device is mapped already.
Given the fact that there's no extra info added I'll close this ticket.
@raycastbot close this issue

**Comment by VladCuciureanu** [comment]
@raycastbot close this issue
