### ISSUE TITLE
[Music] ...

### ISSUE THREAD

**Issue by Lkmmaw** [raycast/extensions#4372]
### Extension

https://raycast.com/fedevitaledev/music

### Description

<img width="774" alt="image" src="https://user-images.githubusercontent.com/29972478/213921847-53d7df61-e2f7-4971-80dd-3eb55c16710c.png">

**Comment by Rawnly** [comment]
Hi, can you share which track you were playing? I have an open ticket with apple for this kind of issue and have to do some debugging.

Thanks

**Comment by LEUNGHOTIN** [comment]
You can try this song [Smells Like Me](https://music.apple.com/cn/album/smells-like-me/1633318292?i=1633318575)

**Comment by LEUNGHOTIN** [comment]
By the way, none of the songs from this album can be added to the library

**Comment by Lkmmaw** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Sorry to reply so late.I tried to add any Chinese song by “Add to Library", but I haven't succeeded yet. It also includes Smells Like Me.
                
                    
                            
                                
                            
                            
                                lkmmaw
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Federico ***@***.***>
            
        
      
      
        
         Date 
        
        
        01/25/2023 06:53
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [raycast/extensions] [Music] ... (Issue #4372)
        
      
    
  
  
Hi, can you share which track you were playing? I have an open ticket with apple for this kind of issue and have to do some debugging.
Thanks
