### ISSUE TITLE
[Wikipedia] ...

### ISSUE THREAD

**Issue by andreaguida** [raycast/extensions#4381]
### Extension

https://www.raycast.com/vimtor/wikipedia

### Description

Add Italian language, please! 🙏

### Who will benefit from this feature?

Italian users.

**Comment by NikosEfthias** [comment]
@andreaguida adding now

**Comment by andreaguida** [comment]
@NikosEfthias Great! Thanks!!! 😊

**Comment by NikosEfthias** [comment]
@raycastbot close this issue

**Comment by NikosEfthias** [comment]
the pr has been merged i think this issue can be closed now

**Comment by JonathanWbn** [comment]
@raycastbot close this issue
