### ISSUE TITLE
[Unicode Symbols Search] Command stuck in loading state

### ISSUE THREAD

**Issue by jonasmaaloe** [raycast/extensions#4382]
### Extension

https://www.raycast.com/mmazzarolo/unicode-symbols

### Description

![CleanShot 2023-01-23 at 00 48 53@2x](https://user-images.githubusercontent.com/2072298/213947237-02ccd966-da79-4db5-b4cb-be58bd7f0151.png)

When launching the command, the comman screen loads forever, and never resolves. I have tried:

- Uninstalling and reinstalling the command itself.
- Disabled and re-enabled the command in Raycast
- Quitting and relaunching the Raycast app

I'm running Raycast 1.46.0

**Comment by jonasmaaloe** [comment]
I solved it! Seemingly after running `Reload Script Directories` and `Refresh Apps and Settings` commands (I thought something like that happen on quite + reopen. Alas)

**Comment by pernielsentikaer** [comment]
Please let me know if it happens again, you can always catch me in [Slack](https://www.raycast.com/community)
