### ISSUE TITLE
[Google Translate] ...

### ISSUE THREAD

**Issue by stoicorley** [raycast/extensions#4389]
### Extension

https://www.raycast.com/gebeto/translate

### Description

 For specific languages for example Simplified Chinese, words like "庙会" are only translated but the difficult part of learning the language is the pronunciation "Miàohuì"

Is there any way to include the pronunciation in the translation?

### Who will benefit from this feature?

Non-native speakers of most Asian languages, as the phonemes and/or tones for Chinese, Japanese, Thai, etc., are not explicitly obvious based upon the example above. 

### Anything else?

I love the extension so far - thanks in advance!

**Comment by gebeto** [comment]
Oh, yes, I'll try to add pronunciation today. I was working on multilanguage yesterday and I saw that translate api is returning pronunciation, so now I just need to add it somewhere in UI 😄

**Comment by gebeto** [comment]
https://github.com/raycast/extensions/pull/6666
