### ISSUE TITLE
[Folder Search] Extension not working

### ISSUE THREAD

**Issue by andreaguida** [raycast/extensions#4391]
### Extension

https://www.raycast.com/GastroGeek/folder-search

### Description

Whetever I look for, there are no results.

https://user-images.githubusercontent.com/54178949/214118392-856eeff4-e6b9-4687-a1ec-6ba8c2666e12.mp4

**Comment by omarshahine** [comment]
I wonder if this is a spotlight issue. Does File search work for you?

**Comment by andreaguida** [comment]
@omarshahine yeah, Spotlight and the Raycast File Search feature are working perfectly fine. Thanks!
![CleanShot 2023-01-23 at 22 57 33@2x](https://user-images.githubusercontent.com/54178949/214159113-f7e5c2ae-ef85-4d9d-9531-69490fcc1c5e.png)

**Comment by omarshahine** [comment]
@GastroGeek might have ideas as he authored 99% of the extension including this piece.

**Comment by andreaguida** [comment]
FYI: extension started working after I've set macOS in English language (instead of Italian).

**Comment by MichaelHHeng** [comment]
I have the same Problem, German language, same as @flegfleg i don't want to change to english. Thanx @GastroGeek and @omarshahine 😊

**Comment by omarshahine** [comment]
Are any of willing to install https://github.com/derhuerst/node-spotlight and see if you have the same problem?

The extension is just a wrapper for node-spotlight.

**Comment by MichaelHHeng** [comment]
I have looked at this and honestly have no idea what it is, how to install it and what will happen after installation and/or how to test it. Even less do I know what a wrapper for node-spotlight is. Sorry, I am only a user and unfortunately completely lost 🤷‍♂️

**Comment by omarshahine** [comment]
I found the problem, now I have to fix it.

@raycastbot can you merge this issue with https://github.com/raycast/extensions/issues/6559

**Comment by omarshahine** [comment]
I have a fix and am now testing it out.

**Comment by pernielsentikaer** [comment]
Merged and closed, please give it a shot @andreaguida  - you can run `Check for extension Updates` to ensure you have the newest update
