### ISSUE TITLE
[Brew] Upgrade command can modify raycast itself if it is installed via brew

### ISSUE THREAD

**Issue by jalemann** [raycast/extensions#4392]
### Extension

https://www.raycast.com/nhojb/brew

### Description

If Raycast is installed via homebrew and the brew upgrade command is run via this extension, it can lead to raycast itself being uninstalled during upgrade. I guess, as raycast uninstalled itself it can not install the new version.

### Steps To Reproduce

1. Install raycast via homebrew
2. Install the brew extension for raycast
3. Configure the brew extension, setting a checkmark at 'Include auto-updating casks when upgrading'
4. Wait for a new raycast version to hit homebrew
5. Run brew upgrade via the raycast brew extension
6. Raycast uninstalls itself

### Current Behaviour

The brew extension can uninstall raycast.

### Expected Behaviour

The brew extension should probably ignore raycast when upgrading.

**Comment by Aayush9029** [comment]
That's kinda funny. 

1. I guess a work around would be using (run in terminal) or manually pasting the upgrade command in iTerm.

2. IIRC You can pin raycast to a specific version using 

`brew pin ...`

And then unpin using `brew unpin ...`

*raycast won't be updated using brew when pinned*


Potential dev fix: I guess we can modify this extension to automatically pin raycast, upgrade and then unpin raycast. Then run the upgrade command on raycast.


Potential user fix: Don't use brew to install raycast if you want to use brew upgrade extension on raycast.

**Comment by nhojb** [comment]
I wonder if it would be a good idea to exclude Raycast entirely from results in the extension. On the assumption that if user is running `brew` in Raycast:

1. They don't need to install it 😉 
2. They don't need to upgrade it via brew because Raycast includes it's own auto-updater.

But I'd never considered this before and it's a good catch.
