### ISSUE TITLE
[Bitwarden Vault] "Something went wrong"

### ISSUE THREAD

**Issue by vfonic** [raycast/extensions#4393]
### Extension

https://www.raycast.com/jomifepe/bitwarden

#### Error:

![Screenshot 2023-01-23 at 13 42 44](https://user-images.githubusercontent.com/67437/214122985-071ad47c-b9f9-41ee-8748-4ea62a89ebca.jpg)

### Steps To Reproduce

I don't know what happened, but since a few days ago, Bitwarden extension no longer works.

Things I tried:
1. Reload (action within Raycast)
2. Restart Raycast
3. Update Bitwarden via App Store

How can I generate crash log so that I can upload it here?

<details><summary>Here are my Bitwarden extension settings</summary>

![Screenshot 2023-01-23 at 13 46 45](https://user-images.githubusercontent.com/67437/214123791-de725f3a-9550-4a4d-a2a8-c142f50e53da.jpg)

</details>

I confirmed I have Bitwarden executable at `/usr/local/bin/bw`.

I figured how to get the diagnostics...I think:
[extension-diagnostics.txt](https://github.com/raycast/extensions/files/10482779/extension-diagnostics.txt)

Raycast: v1.46.0
macOS: Ventura 13.1
Bitwarden: 2023.1.1

**Comment by jomifepe** [comment]
Hello, thanks for providing a diagnostics file. 

I'm not sure what's causing the issue, but the file you provided states that you are not logged in when the extension tries to run bitwarden commands.

Have you tried reentering the Client ID & Secret? As a last resort, try to reinstall the extension.

**Comment by vfonic** [comment]
I rotated Client ID & Secret, upgraded bitwarden-cli and reinstalled Bitwarden Extension and now everything works again.

Thanks!

**Comment by davidyannick86** [comment]
> I rotated Client ID & Secret, upgraded bitwarden-cli and reinstalled Bitwarden Extension and now everything works again.

Thanks!

But I have always have the same problem
