### ISSUE TITLE
[Obsidian] Instant search

### ISSUE THREAD

**Issue by ggnall** [raycast/extensions#4400]
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

It would be great to run an instant search with live text. My current workflow is to invoke the search, hit enter, then do a live search where I can see the results instantly. This helps when I don't remember the exact text I'm looking. 

Of course one can bypass the search form screen with one-button press - it's just inconsistent with my other search app extension flows.

**Comment by marcjulianschwarz** [comment]
Hi @ggnall,

what exactly do you mean with this? Do you want to get to the search instantly without prior selection of a vault?
If yes, then you can add the path of your vault in the extensions preferences. 
Invoking the Search Note command will then directly open the search for that specific vault.

**Comment by ggnall** [comment]
I was comparing this to search behavior in other extensions, where I can do:

* Open raycast

* Type alias (e.g. `bs` for bear-search or `ts` for todoist search.

* Press space

* Raycast displays a list of results immediately and updates as I type in the search query.

For this extension it looks like:

* Open raycast

* Type alias `os` for obsidian search

* Press enter
* Raycast displays a list of results. I can type in characters to search within.

It's not a big type (a single button press), but it find myself repeatedly pressing space and waiting for something to happen.

A bigger improvement would be to set a better default (or manually configured) sort on the results. Sometimes my most recent file is at the way bottom.

**Comment by marcjulianschwarz** [comment]
Thank you for the clarification. This doesn't seem to work because of the search arguments. Would it solve your problem if I put the search arguments behind a preference checkbox? Then the search with spacebar should work.

Please open a new issue for the other improvement that you mentioned.

**Comment by ggnall** [comment]
>Would it solve your problem if I put the search arguments behind a preference checkbox?
Yes! 

>Please open a new issue for the other improvement that you mentioned.

Added this here https://github.com/raycast/extensions/issues/4635
