### ISSUE TITLE
[Floating Notes] Create multiple notes

### ISSUE THREAD

**Issue by yougotwill** [raycast/extensions#4403]
### Extension

https://raycast.com

### Description

It would be awesome if we could have multiple floating notes. Maybe adding a plus button to the note window which spawns a new note in the center of the screen.

### Who will benefit from this feature?

Anyone who wants multiple floating notes. Personally I would like it so that I can have one floating note for permanent things and another as a scratchpad for code, drafting a message, or other temporary thing etc.

### Anything else?

Love this app. Keep up the good work!

**Comment by yougotwill** [comment]
Still valid

**Comment by dirstart** [comment]
I need it.
Multiple floating notes
I want to develop it together.
I think everyone will like it.
