### ISSUE TITLE
[iMessage 2FA] After copying a code, mark the message as read.

### ISSUE THREAD

**Issue by zalmanlew** [raycast/extensions#4404]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

After copying a code, mark the message as read.

Currently it still leaves the notification. The assumption is that if I've copied the actual code it is safe to mark the message/chat as read.

**Comment by thomaspaulmann** [comment]
That would be indeed cool. Need to see if there is a way to do that in the SQL database. @zalmanlew do you want to help?

**Comment by zalmanlew** [comment]
@thomaspaulmann I looked at it a bit - from what I can we just need to `set is_read = 1` for the message ID.

I think it would also be a setting from the extension (like users can choose to enable/disable the option)

**Comment by thomaspaulmann** [comment]
I investigated it, but couldn't get it to work. I pushed my [work-in-progress branch](https://github.com/raycast/extensions/tree/2fa-mark-as-read). If you'd like, you can take it and try again.

**Comment by zalmanlew** [comment]
I tinkered with it as well but couldn't properly identify what updates iMessage is sending to the DB when marking a chat as read.

Maybe someone can check and compare to see all the records that were changed when a chat is marked as read.

**Comment by yuercl** [comment]
Those  fields  is_read ,  was_read ,  date_read ,  date_delivered , item_type ,  has_dd_results , and  group_action_type  can affect the read status of iMessage messages. Perhaps someone will have the opportunity to try again and see the results.
