### ISSUE TITLE
[Quit Applications] Add restart function

### ISSUE THREAD

**Issue by andreaguida** [raycast/extensions#4407]
### Extension

https://www.raycast.com/mackopes/quit-applications

### Description

Would be awesome if the extension can also restart selected process.

An example of Applescript that works:

```
on run
tell application "[name of application]"
	if its running then
		quit
		delay 0.5
	end if
	activate
end tell
end run 
```

**Comment by mackopes** [comment]
Interesting! Thanks for the snippet, too! I always struggle with the Applescript.

I think this could work. I'd rather check if the app is running in a loop as not all apps will quit in 0.5s, but that's a small modification. I will take a look at this

**Comment by andreaguida** [comment]
@mackopes Great! Thanks! 😃
