### ISSUE TITLE
Refreshing indicator won't show when setting in ActionPanel

### ISSUE THREAD

**Issue by RayZhao1998** [raycast/extensions#4411]
### Description

When I want to update `isLoading` in ActionPanel, the List's refreshing indicator won't show up again.

### Steps To Reproduce

- raycast 1.46.0
- @raycast/api@1.46.0

#### Example Code
```
import { List, ActionPanel, Action } from '@raycast/api';
import { useEffect, useState } from 'react';

export default function Command() {
  const [isLoading, setIsLoading] = useState(true);
  const items = [{ name: 'Test' }];

  useEffect(() => {
    setIsLoading(true);

    setTimeout(() => setIsLoading(false), 1000);
  }, []);

  return (
    <List navigationTitle="My Items">
      {items.map((item, index) => (
        <List.Item
          key={index}
          title={item.name}
          actions={
            <ActionPanel>
                <Action title="Refresh" onAction={() => {
                  setIsLoading(true)
                }}/>
            </ActionPanel>
          }
        />
      ))}
    </List>
  );
}
```

When click refresh action, the list's refreshing indicator won't show up.

### Current Behaviour

Refreshing indicator won't show up.

### Expected Behaviour

Refreshing indicator show up again.

**Comment by fe9lix** [comment]
@RayZhao1998 The isLoading property needs to be set on the list, e.g.: <List navigationTitle="My Items" isLoading={isLoading}>

**Comment by RayZhao1998** [comment]
Oh, thanks.
