### ISSUE TITLE
[Spotify Player] Not working because I can't authorize Spotify (Web Player on Arc Browser)

### ISSUE THREAD

**Issue by ozwxy** [raycast/extensions#4421]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Spotify Player is not working because I can't authorize Spotify on Web Player using Arc browser.
Arc is chromium browser. (https://arc.net/)

I run command 'Like a current song', but authorization window repeatedly showed.

**Comment by Legionof7** [comment]
I have this same issue with Arc!
