### ISSUE TITLE
[Associated Press] Paragraphs in Read view

### ISSUE THREAD

**Issue by jiserra** [raycast/extensions#4423]
### Extension

https://www.raycast.com/Dammmien/associated-press

### Description

I don't know if this is a limitation of Raycast or can be implemented, but is there any way to show the Read view with paragraphs? I'm sure the feed have paragraphs, but I don't know if it's possible to format them inside the preview of Raycast. Otherwise, it's pretty hard to read. 

Thanks!

### Who will benefit from this feature?

Everyone who wants to read news from this extension

**Comment by Dammmien** [comment]
Yes the Associated Press API returns content as an HTML string but Raycast uses markdown.
For simplicity I just sanitized the content by removing HTML tags, but we lost the layout indeed ...
The best solution could be to turn the html into markdown by using something like [turndown](https://github.com/mixmark-io/turndown).
I'll give it a shot.
