### ISSUE TITLE
[Toothpick] Device Support Form

### ISSUE THREAD

**Issue by jacopocolo** [raycast/extensions#4430]
### Extension

https://www.raycast.com/briankosw/toothpick

### Description

<b>Device name</b>
Sony WF-1000XM3

<b>Device data</b>
{"WF-1000XM3":{"device_address":"38:18:4C:4C:F0:BF","device_batteryLevelMain":"100 %","device_firmwareVersion":"3.1.2","device_minorType":"Headset","device_productID":"0x0CE0","device_services":"0x800019 < HFP AVRCP A2DP ACL >","device_vendorID":"0x054C","device_connected":"true"}}

### Anything else?

Happy to help!

**Comment by VladCuciureanu** [comment]
Hey! Your device is now mapped (changes awaiting review) and will have a custom icon and battery level shown in the extension, with possible added functionality in the future. Thanks for your submission.

**Comment by VladCuciureanu** [comment]
@raycastbot close this issue
