### ISSUE TITLE
[Visual Studio Code - Project Manager] Can I always open in current window instead of just when it empty

### ISSUE THREAD

**Issue by mefengl** [raycast/extensions#4433]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

when I use this command, it always opens in the current window if VSCode is already opened

### Who will benefit from this feature?

people who use laptop, don't have much space to put all their projects

### Anything else?

I guess there already has a way to do this, if so, just tell me
thankfully

**Comment by MarkusLanger** [comment]
@mefengl I don't see a parameter for the action to open the project in the current window.
https://developers.raycast.com/api-reference/user-interface/actions#action.open

**Comment by mefengl** [comment]
maybe can achieve this by close the previous window first
