### ISSUE TITLE
[Search npm Packages] Default action should open the package on npm

### ISSUE THREAD

**Issue by jasonbarry** [raycast/extensions#4436]
### Extension

https://www.raycast.com/mrmartineau/search-npm

### Description

The default action for each list item should be to open the package on npm. Not every item in the list has a repository or a homepage associated with it, which means the default action can change based on the metadata of the list item. If the `npm Package Page` action was first, then the result of pressing the return key would be consistent for every package. 

<img width="352" alt="CleanShot 2023-01-25 at 09 03 54@2x" src="https://user-images.githubusercontent.com/236451/214630916-8ca165c0-60b6-4931-810a-7137667257b7.png">

**Comment by mrmartineau** [comment]
@jasonbarry this is a configurable option actually, however, you are correct that the default option is set to open the repo. Source for this is [here](https://github.com/raycast/extensions/blob/cd4b874e3c18cb4afa68a91c05838143b77bd0f4/extensions/search-npm/package.json#L96-L97) if you're interested in changing it.

**Comment by luisFilipePT** [comment]
I have an open PR for this extension (https://github.com/raycast/extensions/pull/5290) if you think it helps I can do this small fix in that PR, however one question: In the links section should the `npm Package Page` move to the first position also?

@mrmartineau @jasonbarry

**Comment by jasonbarry** [comment]
@luisFilipePT yep makes sense to me, go for it
