### ISSUE TITLE
[Extension Feature Request] Add ProductHunt ranking list

### ISSUE THREAD

**Issue by moritzcodes** [raycast/extensions#444]
# Extension – [Product Hunt Extension](https://github.com/raycast/extensions/tree/main/extensions/producthunt)

Author: @ragnorc 

I just downloaded your Raycast Extension and as a Product Hunt User I would love to also see the real ranking list and not only the newest products!

Would be great, if could implement this feature!

**Comment by mattisssa** [comment]
Hey @ragnorc! 
Here is the new feature request to your extension, take a look at that and subscribe to don't miss anything related 😉
