### ISSUE TITLE
[Hacker News] add open with option

### ISSUE THREAD

**Issue by romanr** [raycast/extensions#4445]
### Extension

https://www.raycast.com/thomas/hacker-news

### Description

Add parameter to open link with an app. (HN reader app)

**Comment by thomaspaulmann** [comment]
@romanr Do you know the URL scheme to open links in the HN reader app? And do you have a specific one that I can try it out?

**Comment by romanr** [comment]
Yes, I tried few apps and [Octal](https://apps.apple.com/au/app/octal-for-hacker-news/id1308885491) is the best and top rated app for HN. works on iOS and macOS.  scheme `octal://item?id=`
Will be fantastic if you add support for it 😄

**Comment by thomaspaulmann** [comment]
Should be easy to add and can pave the way for other HN desktop apps. Do you want to give it a try to contribute? We have some similar code in the Linear and Figma extension to prefer opening links in desktop apps if they are installed. 

Ideally, we can show this option only for folks that have `Octal` installed.
