### ISSUE TITLE
[HubSpot] "Something went wrong" for all commands except "List communications"

### ISSUE THREAD

**Issue by scoop** [raycast/extensions#4446]
### Extension

https://www.raycast.com/harisvsulaiman/hubspot

#### Error:
```
TypeError: Cannot read properties of null (reading 'value')

lk:index.js:6:32649


index.js:6:32496
    at Array.map (<anonymous>)
pi:index.js:6:32489
```

Full back trace was too long. Gist here: https://gist.githubusercontent.com/scoop/2847b096d01f59aab66e8fd25c2cd238/raw/32f397322f135a2d00b54f4a14907211653bfee5/gistfile1.txt

### Steps To Reproduce

1. Created Private App
2. Configured Access Token in Extension
3. Ran any command (I don't even get to specify a search string for "Search contacts" for example)
4. The only command that works and lists content is the "List communications" command.
![CleanShot Arc Private Apps  HubSpot 2023-01-26 Hq1AGywz](https://user-images.githubusercontent.com/502/214787795-c1c3d7aa-5c82-4db9-bf72-620ad1210215.png)

We're on a CRM Hub Professional plan, the instance is set to German in case that changes anything. I have not seen any change in API behavior with our other integrations though.

### Current Behaviour

HubSpot results are shown

### Expected Behaviour

An error message is shown. Happy to help troubleshoot this with dev builds etc.

**Comment by pernielsentikaer** [comment]
@harisvsulaiman do you have a clue here?

**Comment by harisvsulaiman** [comment]
@pernielsentikaer I'm a bit busy right now. I'll take a look at it soon

**Comment by scoop** [comment]
I found the root cause. I had a call in my HubSpot instance originating from a Zoom meeting. This particular call didn't have a number associated with it. To safeguard against this situation you can use the following patch in your extension:

```diff
commit 703225a39c9d11e6d1979dc9b2b2de436fdcbf43
Author: Patrick Lenz <patrick@limited-overload.de>
Date:   Wed Sep 27 14:14:04 2023 +0200

    Safeguard calls without a phone number

diff --git a/src/calls.tsx b/src/calls.tsx
index 5934da7..506927e 100644
--- a/src/calls.tsx
+++ b/src/calls.tsx
@@ -29,7 +29,7 @@ export default function Command() {
                       <List.Item.Detail.Metadata.Label title="Title" text={hs_call_title} />
                       <List.Item.Detail.Metadata.Label title="Status" text={hs_call_status} />
                       <List.Item.Detail.Metadata.Label title="Created" text={new Date(createdate).toLocaleString()} />
-                      <List.Item.Detail.Metadata.Label title="To Number" text={hs_call_to_number} />
+                      <List.Item.Detail.Metadata.Label title="To Number" text={hs_call_to_number || ''} />
                     </List.Item.Detail.Metadata>
                   }
                 />

```

**Comment by harisvsulaiman** [comment]
@scoop  Can you submit a pr?

**Comment by scoop** [comment]
> @scoop Can you submit a pr?

Done. https://github.com/raycast/extensions/pull/8594
