### ISSUE TITLE
[Toggl Track] Migrate to API v9 before April 1 2023, when v8 will be disabled

### ISSUE THREAD

**Issue by rogatty** [raycast/extensions#4451]
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Description

API v8 which is being used by the extension is deprecated since Oct 1 2022: https://developers.track.toggl.com/changes/2022/10/01/api-v8-deprecation

During March 2023 there will be brownouts:
> During brownout periods, endpoints will be temporarily disabled and then re-enabled after a few hours. The goal is to help API clients to notice the scheduled unavailability and plan their migration accordingly.

On April 1 2023 the v8 will be disabled and the extension will stop working. I fill it as a feature request, but if we don't fix it before, then it'll become a major bug. 😉 

Here is the migration guide: https://developers.track.toggl.com/docs/additional/v8_migration_guide

### Anything else?

https://github.com/raycast/extensions/blob/2de651f199d9c46583b3510f72e24b1c42313a9b/extensions/toggl-track/src/toggl/index.ts#L6

**Comment by franzwilhelm** [comment]
Will try to look at this within march. Any PRs on the extension is welcom @rogatty
