### ISSUE TITLE
[Bitwarden] Use `bw unlock --check` to test vault status

### ISSUE THREAD

**Issue by pomdtr** [raycast/extensions#4452]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

See https://github.com/bitwarden/clients/issues/2729#issuecomment-1384715827

The check was broken in the past, but it looks like it is fixed now. We should probably use it to check the authentication status of the user.

It would also allow to add new commands relying on the authentication to the bitwarden extension.

**Comment by jomifepe** [comment]
@pomdtr Thanks! This is something I plan on implementing in some way in [this issue](https://github.com/raycast/extensions/issues/4351)
