### ISSUE TITLE
Adjust styling of Form.Dropdown.Item without Icon

### ISSUE THREAD

**Issue by Rincewind34** [raycast/extensions#4454]
### Description

At the moment, if a form contains items with as well as without icons, the dropdown becomes kind of hard to read.
<img width="532" alt="Screenshot 2023-01-26 at 14 32 44" src="https://user-images.githubusercontent.com/13020648/214863193-a5fcd588-2eaa-418a-97d6-5a2e466ff2c8.png">
In this case, the entry "None" doesn't have an icon associated with it. It is easy to imagine, that if items without an icon are scattered through the menu, the list becomes kind of hard to read, as there is no common start of text line.

If the styling is adjusted globally, the padding should only be applied if any items have an icon set. As an alternative to not change the global styling for all extensions, you could add an "Icon.NONE" so I can manually adjust the padding.

### Who will benefit from this feature?

I think this will be beneficial for everyone, not only developers, but also users since all extensions become more readable.

**Comment by thomaspaulmann** [comment]
For this reason, we recommend two things:
1. Split the `None` item into a separate `Dropdown.Section`
2. Use a default icon for `None` item, often times a circle works well

Have you tried those? In theory we could add a fallback item if other items have an icon. Though this feels a bit unexpected.
