### ISSUE TITLE
[API Feature Request] Windows and/or Linux support

### ISSUE THREAD

**Issue by AustinGil** [raycast/extensions#446]
It would be really awesome to get this app available in Windows and/or Linux.

**Comment by fe9lix** [comment]
Closing this here since it's not directly related to the API and extensions. (Windows/Linux support might be coming in the future but there's no timeline yet.)

**Comment by alerque** [comment]
Even if the code isn't open source you could at least open a project for the core app so there could be a public issue tracker...
