### ISSUE TITLE
[API Feature Request] Customize List 'No Results' text / screen

### ISSUE THREAD

**Issue by BoruiGu** [raycast/extensions#447]
**Describe the feature and the current behavior/state.**

ability to customize / provide additional message to the ‘No Results’ screen for List

**Will this change the current api? How?**

no, it will be a new API

**Who will benefit with this feature?**

extension developers will be able to provide instructions to users when List search returns no results

**Any Other info.**

context: 

i’m building an extension that displays a List, the items are fetched from remote sources (it could take a minute or two to fetch them, but these items do not change often)

the items are put into a cache once fetched, and the List renders items from cache if cache is available

the command provides a 'Refresh' action to fetch items from remote again and update the cache

it would be great if the API provides the ability to customize the No Result screen / text, so that it can display a message suggesting users to Refresh

**Comment by mattisssa** [comment]
Hey! Thanks for the suggestion, it's planned already 👍
