### ISSUE TITLE
[Stoic Quotes] ...

### ISSUE THREAD

**Issue by JhonnyAxe** [raycast/extensions#4473]
### Extension

https://www.raycast.com/rrajath/stoicquotes

### Description

Hi! Love your idea! But it would be grate if you make it in Telegram Bot where users could set the frequency of receiving such quotes. Will you?

### Who will benefit from this feature?

All stoic Telegram users 🙂

**Comment by rrajath** [comment]
Thank you @JhonnyAxe. Haven't really dealt with Telegram much, but I'd love to write a bot for it. Can you elaborate on the use cases you're most interested in?
