### ISSUE TITLE
[Extension Feature Request] Other apps for git repos

### ISSUE THREAD

**Issue by CarlAndersson** [raycast/extensions#448]
# Extension – [Git Repos](https://github.com/raycast/extensions/tree/main/extensions/git-repos)

Author: @moored 

**Describe the feature and the current behavior/state.**
I would like to select other apps to open my repos with.

**Who will benefit with this feature?**
Anyone who's not using vscode.

**Any Other info.**
It could be that I just don't get how to configure the extension properly...

**Comment by moored** [comment]
I want to add this however it is currently dependent on API Feature Request #98. If that gets implemented then I can add the ability to select your default editor, git client, etc. in the extension preferences.

**Comment by CarlAndersson** [comment]
Ah, that's fair. I'll watch that issue as well.

**Comment by mperezi** [comment]
It does not work for me. I can pick IntelliJ IDEA in the dropdown but when I open a project the effect is that the application opens up with the last project open, not the one I selected.

**Comment by moored** [comment]
Interesting, I am using the standard Raycast Action.Open API and has so far worked for me with Xcode, Visual Studio Code, Fork, BBEdit, iTerm, and Finder. It may have something to do with how IntelliJ IDEA receives/parses launch parameters. I don't use IntelliJ IDEA so am unable to test on my system.
