### ISSUE TITLE
[JetBrains Toolbox Recent Projects] ...

### ISSUE THREAD

**Issue by linpan** [raycast/extensions#4483]
### Extension

https://www.raycast.com/gdsmith/jetbrains

### Description

Reason: Code: 14 (Timeout)
Domain: commands
Time: 04:06:57.088

**Comment by linpan** [comment]
Reason: Code: 14 (Timeout)
Domain: commands
Time: 04:06:57.088

**Comment by DPN-XFN** [comment]
@linpan 
You can execute `find ~/Library/Application\ Support/JetBrains/Toolbox/apps -type f -name .history.json` ,If the output is {},
You can try installing from Toolbox or update  using toolbox?.

**Comment by rafael-yure** [comment]
I'm having the same issue, installed and copied the paths from toolbox but all I get is a timeout:

```
Reason: Code: 14 (Timeout)
Domain: commands
Time: 11:47:43.162
```
