### ISSUE TITLE
[Pinboard] ...search by title

### ISSUE THREAD

**Issue by cpresse** [raycast/extensions#4484]
### Extension

https://www.raycast.com/fe9lix/pinboard

### Description

Actually it is only possible to search by tags. Searching by title would be a great benefit. Searching by tag gives (at least for me) too many hits

### Who will benefit from this feature?

Everybody since it is easier to find specific entries

**Comment by fe9lix** [comment]
As far as I remember, this was a limitation of the Pinboard API. The newer Pinboard API version would support this but it hasn't been accessible yet at that time and its state still seems to be somewhat unclear :/.

**Comment by cpresse** [comment]
Yeah, the new api seems to be documented poorly. Is there anything I can do to support you here?
