### ISSUE TITLE
[Authy] Couldn't decrypt service tokens.

### ISSUE THREAD

**Issue by smeevil** [raycast/extensions#4485]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

Hi,

I am trying to use the Authy search token plugin. The setup went well, and I got the approval process from Authy, and the plugin continues after the approval. Though when trying to find a token, it shows the "Couldn't decrypt service token. Seems like Backup Password is wrong.".

I have changed the password to make sure it is correct in both Authy itself as well as in the plugin. The error messages remain. I have even tried to use a less complex password that only exists out of letters and numbers to rule out that it might be an unusual character that causes the problem. 

I've also tried uninstalling and reinstalling the plugin, only to the same effect.

My other devices picked up that the password changed and asked to verify the backup password. After inputting the new password they sync with no problems.

Before Raycast I used Alfred, which also has an Authy plugin, which is using a command line tool. This tool connects to Authy as well and has no problems after setting up the account and using the same backup password...

I'm not sure what might be wrong, or how I might assist in hunting down the problem.

Gerard.

### Current Behaviour

Starting Raycast and triggering the search token action from the Authy plugin returns an error "Couldn't decrypt service tokens. Seems like Backup Password is wrong."

### Expected Behaviour

It should be able to decrypt the service tokens as I am sure the password is correct.

**Comment by guga4ka** [comment]
hey @smeevil to be clear, I have no idea what's wrong with your setup, I've based my extension on chrome plugin and desktop app, and it sends the exact requests as these apps. The single suggestion is double check authy id and password, and start from scratch (cmd + enter) it will clean all caches.

**Comment by zonterone** [comment]
Have same problem

**Comment by smeevil** [comment]
@guga4ka I understand if you are quite busy and not coming around to this. I'd like to help out by making a pr to solve this. If you could tell me the direction you would like to handle the corrupted entry, I can see what I can do :)

**Comment by guga4ka** [comment]
I'm really sorry @smeevil, due to war in Ukraine. I will try to delivery fix at this week. Also, if the service isn't critical, could you share an otp url or service itself i will try to debug. @guga4ka  is my slack id, u can ping me directly.

**Comment by smeevil** [comment]
Hey @guga4ka , Thanks for the response, and no worries, I can still use the plugin with my workaround :) 

Since this authenticator has been disabled and deleted, I can share it with you.

The offending service that's iterated in the `const services: Otp[] = servicesResponse.authenticator_tokens.map((i) => {` process is 

```json
 {
  "account_type": "authenticator",
  "digits": 6,
  "encrypted_seed": "yqHuqDtY34+a3cUur0fqhGrLxLRKTCShOLYlhRZ5bn0=",
  "issuer": null,
  "key_derivation_iterations": 1000,
  "logo": null,
  "name": "ffxiv / square enix",
  "original_name": null,
  "password_timestamp": 1674995705,
  "salt": "0mff0NQDHfRsdr3x4wMH61MCXIaAlBy8",
  "unique_id": "1554320882"
}
```
