### ISSUE TITLE
[File Manager] Support an option to keep the last folder path.

### ISSUE THREAD

**Issue by tung-dang** [raycast/extensions#4489]
### Extension

https://www.raycast.com/es183923/file-manager

### Description

Hi, I would like to request a new feature. That is an option to allow File Manager remembers to keep the last folder path when opening.  Thank you! 

### Who will benefit from this feature?

I usually set my home folder `~` as a default folder and use a shortcut to trigger File Manager. 
I like to go to the desktop or download folder to find the files I need. 
I believe remembering the last folder will help to reduce some keystrokes to enter some texts to go to folders I need (Desktop or Download) because there is a high chance users will see that folder more often.

**Comment by es183923** [comment]
feel free to do implement this urself, I dont quite have the time to do it rn

**Comment by tung-dang** [comment]
Thanks @es183923 ! I will create a PR to implement this after my current PR in this repo is approved and merged. Now I will close this ticket.
