### ISSUE TITLE
[DEVONthink] search fails when a search word is entered

### ISSUE THREAD

**Issue by philp2** [raycast/extensions#4490]
### Extension

https://www.raycast.com/bgnfu7re/devonthink

### Description

Devonthing Database Search fails (Something Went Wrong box appears) when a search term is entered.  The error in the log is TypeError: Cannot read properties of null (reading 'value').  There is much more in the log but it exceeds the character limit permitted in this description box.  

### Steps To Reproduce

1. Macbook Pro with M1 chip running Ventura, latest version of Raycast and Devonthink extension for Raycast, and latest version of Devonthink 3.
2. I open the Raycast window and start to type devonthink and the first item listed is "Search in Databases Devonthink" (DT is in gray font).  I select that item and the "Search Devonthink Databases..." appears.  In the drop down list at the right, my two databases and inbox appear correctly.  
3. When I begin to enter any text as a search term, a "Something Went Wrong" box appears.  

### Current Behaviour

DT Database Search fails when entering a search term.

### Expected Behaviour

When a search term is entered, the DT note or folder that contains that term would be displayed in a list format.

**Comment by kudrykv** [comment]
@philp2 In the extension's properties, please disable the geolocation property. This should fix the issue locally for the time being

**Comment by philp2** [comment]
That fixed it.  Many thanks for your help, Vitaliy.

Phil
