### ISSUE TITLE
[Hypersonic] Unable to create a task

### ISSUE THREAD

**Issue by nator7** [raycast/extensions#4495]
### Extension

https://www.raycast.com/reboot/hypersonic

### Description

Whenever I try to create a task, I get the error "Done is expected to be a checkbox". The done field is in fact a checkbox and it doesn't hinder my ability to check off completed tasks. The item is not being created in the linked notion database.

### Steps To Reproduce

Connected my existing table with a checkbox field called "Done". I am able to check off completed tasks but not to create new one.
![CleanShot 2023-01-30 at 13 48 13](https://user-images.githubusercontent.com/97961853/215443493-d2d62369-dbbe-440d-bb43-4d64c94698e1.png)

### Current Behaviour

The line is created and then disappears with the Error "Done is expected to be checkbox"
![CleanShot 2023-01-30 at 13 46 32](https://user-images.githubusercontent.com/97961853/215443628-6d95e3cd-12c0-4f9c-992f-0c09a06faf50.png)

### Expected Behaviour

To create the task and add it into my related Notion database.

**Comment by pbernasconi** [comment]
Same issue here

**Comment by Bonapara** [comment]
Same issue 😔
