### ISSUE TITLE
Notion search within Raycast returning no results for any query

### ISSUE THREAD

**Issue by dev-communion** [raycast/extensions#4496]
### Extension

https://www.raycast.com/HenriChabrand/notion

### Description

Notion search within Raycast returning no results for any query. See screenshot for search UI for a page I know to exist.

<img width="763" alt="Screenshot 2023-01-30 at 10 35 42" src="https://user-images.githubusercontent.com/120494736/215453799-cd6b5ae6-1e3f-4727-9919-58872bdf7bda.png">

I'm not seeing any errors and I've added the internal app, secret key etc.

**Comment by christianmagill** [comment]
Can you create pages with the extension? If not this may match an existing issue

https://github.com/raycast/extensions/issues/4158
