### ISSUE TITLE
[CoinMarketCap Crypto Search] Action to copy the contract address

### ISSUE THREAD

**Issue by shawnkoh** [raycast/extensions#4499]
### Extension

https://www.raycast.com/SonicSpark/coinmarketcap-crypto-price-crawler

### Description

I believe it would be great if an action to copy the contract's address is added.
Personally, it's my main use case of CMC.

![CleanShot 2023-01-30 at 21 02 39](https://user-images.githubusercontent.com/2741783/215485106-093538d7-fe94-46fe-b833-a64fb69d80a0.png)

**Comment by moojing** [comment]
I think this function is difficult to add in the Action Panel because some token might exist across multiple chains.
But the idea you mention is cool, maybe I could try to add the option of copying address only on ETH?
