### ISSUE TITLE
[transmission] List Torrents shows error ECONNREFUSED

### ISSUE THREAD

**Issue by mikestopcontinues** [raycast/extensions#4504]
### Extension

https://www.raycast.com/FezVrasta/transmission

### Description

I configured Transmission Desktop to use localhost:9091 with no user/pass. I can access it fine via my browser. But when I try to list my torrents in raycast, I get `ECONNREFUSED`. 

My preference is to only allow IP `127.0.0.1`, but I tried it with/without this setting. It doesn't work in either case. 

Any ideas?

**Comment by FezVrasta** [comment]
have you tried setting a password?

**Comment by mikestopcontinues** [comment]
Yes, I did. I forgot to say so.

**Comment by FezVrasta** [comment]
It's a bit difficult to help you with so limited informations. I'm sorry.

**Comment by trankien386** [comment]
<img width="862" alt="Screen Shot 2023-03-06 at 16 26 19" src="https://user-images.githubusercontent.com/61229079/223070252-79ee7ef8-5311-4ea1-9c49-95da5507c51d.png">
I also have this exact same issue. Setting a password in Transmission makes no difference. I'm using the latest version of Transmission (4.0.1).
Are you using this extension with no issue?

**Comment by FezVrasta** [comment]
Could you create a `transmission.js` file like this, run it with node, and see what happens?

```js
new Transmission({
    host: '127.0.0.1',
    port: 9091,
    username: 'user',
    password: 'password',
    ssl: false,
  }).then(console.log);
```

**Comment by FezVrasta** [comment]
Ok so, I managed to reproduce it, the problem only happens if you set as host `localhost`. If you set `127.0.0.1` it works correctly.

It doesn't seem to be a problem with my extension though, because the code above works correctly with `localhost` too, I wonder if Raycast changed how networking works lately.

**Comment by trankien386** [comment]
I confirm that setting 127.0.0.1 makes it works.

One more issue is when i add new torrent, whatever path i type into Download Directory field, it always add a slash (/) before path. It prevents the torrent to be verified.

![SCR-20230308-keel](https://user-images.githubusercontent.com/61229079/223617757-d4e43a3c-47a3-4ee6-a3f2-7519fc83897c.png)
