### ISSUE TITLE
[Harvest] Option to select client first

### ISSUE THREAD

**Issue by tomgenoni** [raycast/extensions#4516]
### Extension

https://www.raycast.com/eluce2/harvest

### Description

I work with multiple clients and the project names can be the same across clients. For example, my project name is "Site design" for Client A and Client B. When I bring up the "New Time Entry" window I have to click into the Project dropdown to see which client is selected.

<img width="750" alt="Screenshot 2023-01-31 at 11 53 57 AM" src="https://user-images.githubusercontent.com/1171072/215868817-a5a49ce9-70af-4633-8611-a787fe613838.png">

I realize you don't have much room but a Client selector would be helpful. 

### Who will benefit from this feature?

Anyone who uses Harvest with multiple clients. 

### Anything else?

Thank you very much for making this extension. It's super helpful as is!

**Comment by eluce2** [comment]
@tomgenoni Can you use unique project codes to distinguish between your projects? This is how we handle this at my company and already has support in the extension

**Comment by tomgenoni** [comment]
Yes, I could. But then I'm adding info into the project just for the sake of this extension. Further I could have 7 different clients and remembering the codes becomes an issue. 

Could you have a user option to prepend the client name to the project? "Client A: Site design". This is effectively how Harvest handles this same issue.

<img width="592" alt="Screenshot 2023-01-31 at 12 42 26 PM" src="https://user-images.githubusercontent.com/1171072/215878349-a8b45f6c-bb9f-46b9-9a1f-b10deb6be955.png">
