### ISSUE TITLE
[Pomodoro] Remaining time should update automatically and not just on click at pomodoro icon on menu bar and should play a sound at the end

### ISSUE THREAD

**Issue by Calieston** [raycast/extensions#4524]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

1. Currently remaining time of pomodoro slot is not updating automatically means you have to click on it. 
2. An audio signal should occur once I reach end of a slot

### Who will benefit from this feature?

Users

**Comment by pernielsentikaer** [comment]
> Currently remaining time of the pomodoro slot is not updating automatically means you have to click on it.

It's updated every 10. seconds automatically, it's not possible in Raycast to update it faster than this at the moment

**Comment by foss-** [comment]
The problem, time is decreasing in 10 second increments is persisting in 1.52.1 on macOS 13.4.

**Comment by foss-** [comment]
Sorry @raycastbot  but you are doing a really bad job here.
