### ISSUE TITLE
[Hue] Allow manual configuration of IP for bridges on different subnet

### ISSUE THREAD

**Issue by luc-ass** [raycast/extensions#4525]
### Extension

https://www.raycast.com/pindab0ter/hue

### Description

I'd like to propose a manual option for the bridge configuration, as my bridge lives on a different (IOT-)Subnet. The bridge is thus not recognised by the extension. Doing this via a config file would be fine as well. Just need to know (and document) where that file lives. Thank you so much for your extension!

### Who will benefit from this feature?

Advanced users, who segregate their networks.

**Comment by pindab0ter** [comment]
Hey, I don't have the time to spend on this currently. I'm open to PR's!

**Comment by pindab0ter** [comment]
Could you tell me more about what would be in the configuration file and how you would see this work?

**Comment by pindab0ter** [comment]
I'm adding the ability to manually enter your Bridge IP Address and/or Bridge username in #6006.

**Comment by luc-ass** [comment]
Awesome!

**Comment by pindab0ter** [comment]
I'd like to reopen this as it will be implemented with the merging of #6006.
