### ISSUE TITLE
[Toothpick] Device Support Form

### ISSUE THREAD

**Issue by mtruem** [raycast/extensions#4527]
### Extension

https://www.raycast.com/briankosw/toothpick

### Description

<b>Device brand and model</b>
Google Pixel Buds Pro

<b>Device data</b>
{"Pixel Buds Pro":{"device_address":"74:74:46:1E:1C:81","device_firmwareVersion":"0.0.1","device_minorType":"Headset","device_productID":"0x3004","device_services":"0x800019 < HFP AVRCP A2DP ACL >","device_vendorID":"0x00E0","device_connected":"true"}}

**Comment by VladCuciureanu** [comment]
Hey! Your device will be mapped in the next release with a custom icon, with possible added functionality in the future. Thanks for your submission.
