### ISSUE TITLE
[Xcode] Links to SwiftPackageIndex aren't valid (https:/ instead of https://)

### ISSUE THREAD

**Issue by kiliankoe** [raycast/extensions#4530]
### Extension

https://www.raycast.com/SvenTiigi/xcode

### Description

When opening a link to a Swift package in the browser Raycast always opens an invalid URL, e.g. https:/github.com/apple/swift-argument-parser instead of https://github.com/apple/swift-argument-parser. 

### Steps To Reproduce

1. Search for a package
2. Open in browser

**Comment by SvenTiigi** [comment]
The bug should be fixed with https://github.com/raycast/extensions/pull/4531 ✌️ (https://github.com/SvenTiigi/extensions/commit/143388e18c2dddca71932e0d4f6777e8f57c247a)

**Comment by kiliankoe** [comment]
Thanks for the extremely fast fix @SvenTiigi!

I gotta ask though because I'm curious and know next to nothing about Typescript. In [SwiftPackageIndexService](https://github.com/raycast/extensions/blob/main/extensions/xcode/src/services/swift-package-index.service.ts#L18) I see the following line, which looks to be fine.

```ts
private static gitHubHostUrl = "https://github.com";
```

How is it that the change you made (using Array.join instead of Path.join) affects if the scheme has the right number of slashes if the host URL being joined already contained them? Was Path.join deduping the slashes to make it a valid path identifier?

**Comment by pernielsentikaer** [comment]
This should be resolved @kiliankoe - do you mind giving it a go and close the issue with `@raycastbot close this issue`

**Comment by SvenTiigi** [comment]
@kiliankoe correct the usage `Path.join` accidentally removed the last slash character of `https://` as `Path.join` seems to perform some kind of path normalization.
I was also unaware about this behavior until you reported this issue 😅

**Comment by kiliankoe** [comment]
Good to know, thanks! :D 

And it looks to be working just as intended now 👍 @raycastbot close this issue

**Comment by pernielsentikaer** [comment]
Could you try to write it as the only thing in the message (Just want to confirm it works @kiliankoe) 😊

**Comment by kiliankoe** [comment]
@raycastbot close this issue

**Comment by kiliankoe** [comment]
I don't think it does 😅 Does the bot do additional housekeeping or could I just close this manually?
