### ISSUE TITLE
[Google Translate] Multiple languages support

### ISSUE THREAD

**Issue by nickpnmrv** [raycast/extensions#4542]
### Extension

https://github.com/raycast/extensions/tree/ae80000d98666e9032b6cdd423b0ed6058fedbf9/extensions/google-translate/

### Description

It would be awesome to have an option to configure multiple languages. Especially for users in Europe.

### Who will benefit from this feature?

Users

**Comment by gebeto** [comment]
Hey 👋 Please check this PR, there are some examples how it works, I've tried to add multi-language support 🕺

https://github.com/raycast/extensions/pull/4704
