### ISSUE TITLE
[CanvasCast] ...

### ISSUE THREAD

**Issue by rab523** [raycast/extensions#4547]
### Extension

https://www.raycast.com/Yoda/canvascast

### Description

API token works, however data is missing when I initiate the plugin. For example, I the My Couses area, I only see two of my many Canvas courses listed.

### Steps To Reproduce

1. launch raycast
2. trigger keyboard shortcut
3. type keyword (in my case, "canvas" followed by a space
4. type course name
5. screen says "no results"

### Expected Behaviour

See all courses.

**Comment by YodaLightsabr** [comment]
Ah yes, I think this is a known issue. I have to fix the way it fetches courses from the API, because there are multiple factors that change how it's displayed on the web homepage.

**Comment by YodaLightsabr** [comment]
Would you mind sharing how you have these courses configured / the API output? I don't have any courses that are closed or in a weird state; they're all open and favorited for me, so it's hard to test.

**Comment by rab523** [comment]
Sure! I have always assumed Canvas only provides one API token for me for the entire courseload. Is there a place inside of the courses configuration or settings that I can find this information?

**Comment by YodaLightsabr** [comment]
Oop I guess I wasn't clear; I was mainly asking for what the courses were and what the settings were (enabled/disabled, published/unpublished, favorited, etc.) to try and debug why it's not showing up.

**Comment by rab523** [comment]
Got it! 

The two classes that appear in Raycast are enabled, favorited, and published, but none of my other 8 favorited (and enabled/published) courses show up. None of my unpublished or unfavorited courses show up.
