### ISSUE TITLE
[Mozilla Firefox] ...

### ISSUE THREAD

**Issue by dewinterjack** [raycast/extensions#4549]
### Extension

https://www.raycast.com/crisboarna/mozilla-firefox

### Description

The first option for the `New Tab` command - `Open Empty Tab` does not work. It does nothing.

### Steps To Reproduce

1. Run the New Tab command 
2. Open Empty Tab

![Screenshot 2023-02-02 at 14 50 21](https://user-images.githubusercontent.com/17269242/216357245-ce125d6b-67a0-45fd-bcfd-be861fe7b31e.png)

### Current Behaviour

 Raycast flickers and then exits as if the command has been run. Rest of the extension works as expected.

### Expected Behaviour

A new empty tab should be opened on Firefox.

**Comment by dhharris** [comment]
Was able to repro this issue, and also found another issue. When searching the history, it gives the option "Open in Firefox" which doesn't work, but opening in the default browser (which is Firefox) works.
