### ISSUE TITLE
[Unicode Symbols Search] ...

### ISSUE THREAD

**Issue by multivac61** [raycast/extensions#4554]
### Extension

https://www.raycast.com/mmazzarolo/unicode-symbols

### Description

Include ⌃ key in app. E.g., as used in https://support.apple.com/en-us/HT201236

**Comment by pernielsentikaer** [comment]
Hi @multivac61

This one?

![Raycast-xfPCkDru@2x](https://user-images.githubusercontent.com/38033107/216552413-b1e3ce53-e0e2-4f7e-8240-645b78c2b78b.png)

**Comment by multivac61** [comment]
^ is not the same as ⌃

I mainly use your tool to write up shortcuts, e.g., `⌘ A`, or `^⌥⌘⇧` which just looks off compared to `⌃⌥⌘⇧`

Raycast uses ⌃ and not ^ to display the control key:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/4436129/216606392-32bc4d05-6e6c-48a1-b875-c8843ae40a69.png">
