### ISSUE TITLE
[Music] "Add to library" actions fails when using different language in macOS 

### ISSUE THREAD

**Issue by andreaguida** [raycast/extensions#4555]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

"Add to Library" and "Music Love and Add to Library" actions fails when macOS is set in a different language than English. This happen because the "Library" playlist name is different. For example, my Mac is set in Italian language, so change "Library" in "Libreria" fixed the issue (I've tested the Apple Script in Script Editor). There is a solution for fix the problem in the extension? 

<img width="862" alt="CleanShot 2023-02-02 at 19 20 41@2x" src="https://user-images.githubusercontent.com/54178949/216412783-cc5aaf83-72cc-45e3-b49a-bb35d113db95.png">

**Comment by Rawnly** [comment]
Hi @andreaguida I understand the situation but I currently don't have another way to do this, I'm sorry but as you can imagine I can't add all languages variants (it's untestable too).

**Comment by Rawnly** [comment]
@raycastbot close this issue

**Comment by andreaguida** [comment]
Hi @Rawnly. Thanks for your response. There is no way to set a custom variable with the name of the Library?
