### ISSUE TITLE
[GitHub] Support root templates repository

### ISSUE THREAD

**Issue by lucasnad27** [raycast/extensions#4556]
### Extension

https://www.raycast.com/raycast/github

### Description

The documentation mentions the following:

> 💡 Pro Tip: The Create Pull Request command also supports PR templates stored in the .github directory.

For the life of me, I can't figure out how to get the Create Pull Request function to respect my pull request template. Within my repo, I have a directory called .github with the following contents:

PULL_REQUEST_TEMPLATE.md
workflows
The GitHub web interface picks up the template without a problem. Is there a bug? Or am I doing something wrong?

### Steps To Reproduce

1. Create a PULL_REQUEST_TEMPLATE.md file per [GH](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) instructions
2. Create a PR with the raycast extension

### Current Behaviour

The "templates" section is empty

### Expected Behaviour

The "templates" section should have an entry for the template created in the PULL_REQUEST_TEMPLATE.md file

**Comment by thomaslombart** [comment]
It's probably because it only checks the `.github` repository under the hood (cf screenshot)

<img width="847" alt="CleanShot 2023-02-03 at 09 23 47@2x" src="https://user-images.githubusercontent.com/16003285/216549202-2a5f8ffd-d409-49be-b2ab-951b57f9dd64.png">

That being said, it should support your use case. I've added this feature request to the team's backlog!

**Comment by lucasnad27** [comment]
Thanks @thomaslombart. I suspected the same so I created a .github repository for my ORGANIZATION (not my personal GitHub repos) -- because obviously I want everyone on my team to be using the same template :) That didn't work either, and given your screenshot, it now makes perfect sense why it didn't.

Can't wait for repo specific PR templates to be a reality. Once that's done, I can start getting my whole team to use Raycast. This is such a killer feature.

Should I close this issue out?

**Comment by thomaslombart** [comment]
That'd be a nice improvement indeed! Let's leave the issue open so that we can track it 😊

**Comment by thomaslombart** [comment]
You're welcome! We unfortunately didn't find the time to address this issue lately. Is this something you want to tackle? I could surely help you in the review and give you some pointers on what needs to be done 😊

**Comment by lucasnad27** [comment]
I can't commit anytime right now, but I'd love to put up a PR in the future. I'll set a reminder a few weeks from now and if I've got time, I'll drop something in this thread.

**Comment by lucasnad27** [comment]
@thomaslombart I've got some time cleared out in a couple of weeks away from my day job...would love to get this implemented depending on the LOE. I'm not familiar with the raycast dev ecosystem, but I'll read up on the docs in the interim. Any links or info you think will fast track my progress is greatly appreciated, but not necessary. Thanks!

**Comment by thomaslombart** [comment]
You'll probably have to look at the extension's `README.md` because you need a personal access token as well as this docs: https://developers.raycast.com/basics/contribute-to-an-extension.

**Comment by lucasnad27** [comment]
🙏🏻 -- thanks @thomaslombart
