### ISSUE TITLE
[Hypersonic] "Done is expected to be checkbox."

### ISSUE THREAD

**Issue by estheticdysfanktion** [raycast/extensions#4558]
### Extension

https://www.raycast.com/reboot/hypersonic

### Description

When trying to create a task from the Raycast Hypersonic Tab, it states "Done is expected to be checkbox." in the down left side of the window. Yet, my Notion property "Done" is a Checkbox property and no problems should arise, in theory.

**Comment by Bonapara** [comment]
Hi, just have the same issue when trying to use a "Done" Checkbox instead of the default "Status". It's working when I'm setting a task as done (The checkmark is getting checked on Notion) but it's impossible to create new task from Raycast/Hypersonic. It raises the error. Thanks!

**Comment by netswift2905** [comment]
having the same issue

**Comment by chebalski** [comment]
+1 same issue.
