### ISSUE TITLE
Pipedrive searches fail

### ISSUE THREAD

**Issue by dabeeeenster** [raycast/extensions#4564]
### Extension

https://www.raycast.com/stephendolan/pipedrive

### Description

Searching with the extension results in this:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/173290/216561265-70bc2b1a-7d79-4080-9e13-8f8e452dbbd0.png">

### Steps To Reproduce

1. Add an API key from Pipedrive
2. Search for anything
3. See Failure

### Current Behaviour

<img width="676" alt="image" src="https://user-images.githubusercontent.com/173290/216561342-8fe96005-6914-4cef-b9ad-6dcc3040611e.png">

### Expected Behaviour

Search results appear

**Comment by stephendolan** [comment]
@dabeeeenster That's a new one to me that I can't reproduce; the only places I'm using `name` are for the Deal Organization and Stage, which are required inputs for a Pipedrive Deal.

If you can find a way to grab a more specific error, I can spend a bit more time on it; otherwise, I'm not sure how to resolve what you're encountering.

**Comment by dabeeeenster** [comment]
Huh odd - it's working now. That's very strange - I didn't change anything. Maybe an issue in their API?

**Comment by dabeeeenster** [comment]
I'm seeing this error when I got no search results returned, but it works OK when there are results?

**Comment by wimsy** [comment]
I'm seeing this same error now. I just installed the extension and followed the same steps as the OP and seeing this error no matter what I type - even before I hit "enter."

**Comment by wimsy** [comment]
I figured out what's happening in my case. We don't use Organization on deals. According to the Pipedrive API docs, org_id is required unless a person_id is specified. I guess we rely on person_id (we tend to base everything off the deal title anyway and use it sort of like an organization name).
