### ISSUE TITLE
[ColorSlurp] Cannot use any commands even with colorSlurp installed and open

### ISSUE THREAD

**Issue by mk-ryan1988** [raycast/extensions#4568]
### Extension

https://www.raycast.com/Jordan-Ellis/colorslurp

### Description

None of the commands work due to the following error;

![image](https://user-images.githubusercontent.com/35534717/216582188-2edb9f88-1e96-4232-83c6-c4ec0c6e7da7.png)

### Steps To Reproduce

1. On Big Sur 11.6.3 (20G415)
2. With raycast version 1.47.2
3. Run any colorSlurp command. E.g "Pick Color"
4. Observe this error: "There is no application set to open the URL colorslurp://x-callback-url/show-magnifier."

### Current Behaviour

Extension does not execute commands 

### Expected Behaviour

Extension should execute commands

**Comment by Jordan-Ellis** [comment]
Hmm, could you tell me version of ColorSlurp you are using? The callback url scheme works with ColorSlurp 3.5 and up. 

ColorSlurp.com has some examples that use the url scheme, [found here](https://colorslurp.com/docs/url-scheme). I'd click on some of the example links and see if it works from there. That way we can narrow down if it's a problem with the Raycast extension, or your computer/ColorSlurp.

**Comment by mk-ryan1988** [comment]
@Jordan-Ellis - I've deleted and re-installed the latest version of colorSlurp and it works perfectly. Sorry I should of checked that first 👍

**Comment by Jordan-Ellis** [comment]
No worries! I'm glad you got it working!
