### ISSUE TITLE
[Lyrics] Add plex & plexamp Support

### ISSUE THREAD

**Issue by Squiddim** [raycast/extensions#4573]
### Extension

https://www.raycast.com/andrewjazbec/lyrics

### Description

Hey yall,

currently grabbing lyrics for both Plex & Plexamp isnt working( or not implemented most likely?)

### Who will benefit from this feature?

Plex Media Server Users

### Anything else?

Great Plugin Idea btw

**Comment by ajzbc** [comment]
Thanks for reporting!

Currently the extension uses Apple Scripts to get the current track info from the specified program.
From what I can tell Plex and Plexamp don't support this functionality and the info would need to be pulled through an API.

Something like this would probably be better suited for a "Plex" specific extension. Sort of like [this](https://www.raycast.com/fedevitaledev/music).

**Comment by ajzbc** [comment]
@raycastbot close this issue
