### ISSUE TITLE
[Arc] `Search Arc` command opens wrong pinned tab if URLs are the same

### ISSUE THREAD

**Issue by danulqua** [raycast/extensions#4576]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

If you have 2 pinned tabs which have the same URL, for example, in different spaces, and search one tab by using `Search Arc` command - the wrong tab opens. In my example, I have 2 different `127.0.0.1:5173` pinned tabs in 2 different spaces: https://share.cleanshot.com/PVVpLSYm

### Steps To Reproduce

1. Pin 2 tabs with the same URL, rename them so you can distinguish
2. Run `Search Arc` command, search for the tab
3. The wrong tab opens

### Current Behaviour

If I run `Search Arc` command and search for a pinned tab which has the same URL with the another pinned tab - the another one opens instead.

### Expected Behaviour

I expect that the pinned tab I was searching for will be opened.

**Comment by thomaspaulmann** [comment]
Indeed an issue and I need to dig into it. Right now the logic picks the first tab with the same URL. Instead it should reuse the indices for the tab to open it if it is still open and points to the same URL.

**Comment by danulqua** [comment]
any update?

**Comment by thomaspaulmann** [comment]
Not yet, need to look into it. Feel free to help with a contribution in the meantime.

**Comment by danulqua** [comment]
update comment

**Comment by danulqua** [comment]
ping
