### ISSUE TITLE
[Pomodoro] Add auto start feature

### ISSUE THREAD

**Issue by shahnawaz323** [raycast/extensions#4588]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

Please add a tick mark or something to auto-start the next mode.

For example breaks should start automatically when the focus mode ends and focus mode should start automatically when the break time ends. Give the user option to enable this feature.

Ofcourse the notification should be shown in raycast window that next mode has started.

### Who will benefit from this feature?

Anyone use this app.

**Comment by susonthapa** [comment]
@shahnawaz323 I was also thinking about this. Right now we have to start the break ourselves which is less than ideal. I think having an option to enable auto-start along with an option to set the cycle count would be awesome. The cycle count can be used to start the long break. 

Let me see if I can come up with something.
