### ISSUE TITLE
[Extension Feature Request]  Translate for DeepL Pro user

### ISSUE THREAD

**Issue by EryouHao** [raycast/extensions#459]
https://github.com/raycast/extensions/blob/81120ca8ddf5d8b44b160232047d5eb9b3f237b5/extensions/deepcast/src/index.tsx#L99

Hi, @ubuntudroid , thanks for your extension. maybe you can provide two switch for use api.deepl.com or api-free.deepl.com

**Comment by ubuntudroid** [comment]
I just extended the extension by additional languages, the original author is @mooxl - that being said, adding that switch shouldn't be that hard. However, right now I don't have time to work on this - maybe at the end of the year if no one else jumps onto this in the meantime.

**Comment by mooxl** [comment]
Thanks for summoning @ubuntudroid! I have some spare time this week, so I can implement this feature. Is it okay for you when the switch between pro and free appears in the welcome screen where u can input your api key @EryouHao?

**Comment by EryouHao** [comment]
@mooxl ok，it's fine.
