### ISSUE TITLE
[Orion] Orion RC support

### ISSUE THREAD

**Issue by thebitstick** [raycast/extensions#4590]
### Extension

https://www.raycast.com/plonq/orion

### Description

Extension only works with public builds of Orion.
Can a setting be added to switch between Orion and Orion RC?

**Comment by Plonq** [comment]
I'll have a look in the next few days

**Comment by Plonq** [comment]
@thebitstick I'm not sure where to download Orion RC. Can you confirm that if there was an option to specify the path to it, that that would be enough? For reference, the path the extension currently uses is `/Library/Application Support/Orion`.

**Comment by thebitstick** [comment]
The path for Orion RC profile is the same as Orion except with `RC` added:
`/Users/thebitstick/Library/Application Support/Orion RC/Defaults`

The **Search Browser History** extension has Orion support with the ability to enter a custom profile directory. It works with adding `RC`.

**Comment by Plonq** [comment]
@thebitstick If you are able, can you test the update: https://github.com/raycast/extensions/pull/4624 (I am unable to test as I don't currently have access to Orion RC).
