### ISSUE TITLE
[Todoist] Can't create a new task

### ISSUE THREAD

**Issue by ggnall** [raycast/extensions#4598]
### Extension

https://www.raycast.com/thomaslombart/todoist

### Description

It looks like the connection with the todoist api is broken for me. It hangs on creating a new task before finally giving an error message:

![CleanShot 2023-02-04 at 11 27 08](https://user-images.githubusercontent.com/4104582/216778547-4116017b-9eb7-4fbe-94ce-d4c5b8f312a3.gif)

### Steps To Reproduce

1. Configure todoist extension with api key
2. Create new task -> Success
3. Next day with no changes ->
4. Try to create new task -> error
5. Invoke "today" from raycast -> shows outdated tasks

**Comment by ggnall** [comment]
Not able to copy the error message but it contains:
`connect ENETUNREACH`

**Comment by ggnall** [comment]
I've also added a new token to todoist and updated the extension config to use that. Same results.

**Comment by thomaslombart** [comment]
Hmmm... that one is weird. These errors typically happen when you have no internet connection. Todoist had a maintenance and was down for an hour last Saturday so maybe that's the cause. Could you try again?

**Comment by kud** [comment]
Todoist API is a bit unstable and also does not accept so many requests.

It's not the first time I've got some "too many requests" issues. However yours seems different like it can't reach the server. Let's try today if you still have this issue and check also their status page.

**Comment by ggnall** [comment]
>Let's try today if you still have this issue and check also their status page.
Thanks y'all. I tried again today and I'm seeing the same results. I did a fresh install and turned off early access featurs in Todoist, but still unable to create tasks or see existing ones from raycast. The status page doesn't show any current issues.

**Comment by kud** [comment]
What version of node do you have? cf https://www.reddit.com/r/linuxquestions/comments/i2yr4i/comment/g0856od/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by ggnall** [comment]
I was on v14.16.1 and just upgraded to v19.6.0

**Comment by thomaslombart** [comment]
Do you still have the error @ggnall?

**Comment by ggnall** [comment]
I was for a few weeks. But right now it appears to be working properly

GG
973.906.6346
***@***.***
