### ISSUE TITLE
Can we have the year be counted down in percentage left in the year... [Year in Progress] ...

### ISSUE THREAD

**Issue by tino963** [raycast/extensions#4599]
### Extension

https://www.raycast.com/thomas/year-in-progress

### Description

A toggle to have the counting go from how much of the year has passed
to how much of the year is left for example we have 90.4% left of the year
vs 10.4% of the year has passed

### Who will benefit from this feature?

People whos mind works differently in terms of what drives them seeing a number go down is more motivational than going up, it feels more like what is actually happening we are losing time as time passes not gaining.

### Anything else?

Thank you for this great extension !

**Comment by thomaspaulmann** [comment]
@tino963 great idea, I like it! Would you be up for contributing it? You could add a preference to the command/extension as a dropdown. Then people can select the style they want and it's get shown properly.

**Comment by tino963** [comment]
@thomaspaulmann I would love to, but my programming knowledge goes only 4 chapters deep of a c++ textbook, Im definitely up for learning new skills and getting it done though
