### ISSUE TITLE
[Weather Extension Bug] Shows blank screen with 503

### ISSUE THREAD

**Issue by imthath-m** [raycast/extensions#46]
<img width="937" alt="image" src="https://user-images.githubusercontent.com/46041492/137520130-df2b0b95-5e4f-44b9-9fbb-db055427cd9f.png">

Always shows the blank screen. The toast shows "Error: http status 503". 

The issue could be location-specific or system-specific. Because some other users have told me that the command works as expected. But it never worked for me.

Raycast version: 1.25.0

## Description
Unable to view weather info

## Steps To Reproduce
1. Open Command
2. Shows blanks screen with error toast

## The current behavior
Blank Screen

## The expected behavior
Weather Info

**Comment by tonka3000** [comment]
#74 should give now the error message that it is a wttr.in server-side issue

**Comment by imthath-m** [comment]
![CleanShot 2021-10-18 at 09 46 24@2x](https://user-images.githubusercontent.com/46041492/137668498-4d8f934b-801f-45aa-ba40-d91a10c9fba9.png)

Thanks @tonka3000. It works now.
