### ISSUE TITLE
[Extension Feature Request] todo list

### ISSUE THREAD

**Issue by freeman14** [raycast/extensions#460]
# Extension – [todo list](https://github.com/raycast/extensions/tree/81120ca8ddf5d8b44b160232047d5eb9b3f237b5/extensions/todo-list/)

Author: @maggie-j-liu  

**Describe the feature and the current behavior/state.**
- Add ability to edit todo item
- Add ability to open URL from todo item by clicking enter

**Comment by mattisssa** [comment]
Hey @maggie-j-liu! 
Here is the new feature request to your extension, take a look at that and subscribe to don't miss anything related 😉
