### ISSUE TITLE
[Apple Maps Search] Remember last Origin

### ISSUE THREAD

**Issue by maroony** [raycast/extensions#4601]
### Extension

https://www.raycast.com/djpowers/apple-maps-search

### Description

At the moment, the default origin for maps directions to search is "Current Location". This has many disadvantages for me:

* it is slow (maps always tries to find out where I am)
* my mac is usually at home, so please use this origin as default or remember my choice

**Comment by djpowers** [comment]
Seems reasonable. The geolocation seems pretty quick for me, but it seems worth it to avoid relying on Maps to determine your location if possible.

I'll change the ordering for now since that's the easiest improvement.
