### ISSUE TITLE
[Extension Bug] Intellij IDEA Ultimate Projects have NODE_ENV=production

### ISSUE THREAD

**Issue by sbeugen** [raycast/extensions#461]
# Extension – [JetBrains](https://github.com/raycast/extensions/tree/1ab7287f4c9f2d15b5ed51a40a5511086c9751c3/extensions/jetbrains/)

Author: @gdsmith 

## Description
Intellij IDEA Ultimate Projects launched via Raycast have their `NODE_ENV` environment variable set to `production`. This means local builds or `yarn install` are not done as expected for the local development environment.

The issue maybe, that the extension itself runs in production mode. Maybe this env variable can be cleared when launching Intellij.

## Steps To Reproduce

1. Close all running instances of Intellij IDEA
2. Launch some project via the JetBrains Raycast Extension
3. run `echo $NODE_ENV` in the Terminal inside Intellij

## The current behavior
NODE_ENV=production

## The expected behavior
NODE_ENV= // blank

### Raycast version
Version: 1.26.1

**Comment by mattisssa** [comment]
Hey @gdsmith! 
Here is the new bug report to your extension, take a look at that and subscribe to don't miss anything related 😉

**Comment by mattisssa** [comment]
Thanks for the fix!

**Comment by gdsmith** [comment]
@sbeugen can you check if this fixes the issue for you?

**Comment by sbeugen** [comment]
Hi. Thx for the fix. Just checked it and it works now as expected 👍
