### ISSUE TITLE
can't publish using the `npx ray publish` tool

### ISSUE THREAD

**Issue by Saafo** [raycast/extensions#4612]
### Description

After commit in local repo, can't using the `npx ray publish` tool described in this [Notion Doc](https://raycastapp.notion.site/ray-publish-c7209e1bd00a4858a68f13d9095910ea)

### Steps To Reproduce

1. fork extension `ToolBox` to local using the new Fork Extension action in Raycast.
2. write new code and commit locally.
3. run `npx ray publish`
4. encountered an error `wait  - validate git repository.failed running git command 'git log origin/main..HEAD', exit status 128`

<img width="866" alt="image" src="https://user-images.githubusercontent.com/46736350/216812079-59772c62-85b7-4c43-877f-f434ae04c7d8.png">

### Current Behaviour

encountered an error

### Expected Behaviour

won't encounter any error and create PR automatically.

**Comment by mathieudutour** [comment]
can you try to run `git log origin/main..HEAD` in your repo? what's the error?

**Comment by Saafo** [comment]
It said: "fatal error: ambiguous parameter 'origin/main..HEAD'：unknown revision or path not exist in working space."

And when I run `git remote`, nothing print. Maybe no remote repo is set.

**Comment by mathieudutour** [comment]
hum we are checking for that, what does `git remote get-url origin && echo "ok"` print?

**Comment by Saafo** [comment]
"error：no such remote 'origin'"

**Comment by mathieudutour** [comment]
right so for some reason `git remote get-url origin` doesn't fail on your computer when we run it in the `ray` CLI, even tho it fails when you run it in your terminal 🤔

I'll have a look. In the meantime, you could push your repo to github repository so that there _is_ a remote...

**Comment by Saafo** [comment]
OK, but another problem I met is that when I ran `npx ray publish`, it seems that it will only download the current extension folder without any git history, and commit the whole folder using the global git config, it's not using the git submodule.

1. I don't want to commit using the global git config, but I never expected the auto commit behavior. More detailed documentation may help.
2. I noticed that in the package.json file, the order of the json of the downloaded version is different from the origin main branch.

**Comment by Saafo** [comment]
Well I'll configure a public version of git info for the repo before pushing to GitHub, instead using the global git config(which may contains my company info). It's okay to commit using the global git config, I can amend it although, but I wish the documentation can mention it. I was confused a lot when I see other files that I never changed contains my git name.

**Comment by mathieudutour** [comment]
> I'll configure a public version of git info for the repo before pushing to GitHub

Hum interesting, never done that before. Maybe I could re-using that info to commit 🤔 Could you point me somewhere it explains how you do it?

**Comment by Saafo** [comment]
> > I'll configure a public version of git info for the repo before pushing to GitHub
> 
> Hum interesting, never done that before. Maybe I could re-using that info to commit 🤔 Could you point me somewhere it explains how you do it?

Oh I usually clone one repo, and write codes, and before commit I'll configure git info using `git config --local`, so you can't using it 😂. I admit that maybe it's a little weird workflow.

I'm just wishing I can know the general process under the `fork extension` from the doc. It's totally nothing to do with `fork` actually.

**Comment by mathieudutour** [comment]
I added a few details to the [notion doc](https://raycastapp.notion.site/ray-publish-c7209e1bd00a4858a68f13d9095910ea) to explain what it does.

> I'll configure git info using git config --local, so you can't using it

I guess I could re-use that config to commit to the fork tho. At least the `user.name` and `user.email`

**Comment by Saafo** [comment]
> I added a few details to the [notion doc](https://raycastapp.notion.site/ray-publish-c7209e1bd00a4858a68f13d9095910ea) to explain what it does.

🎉🎉🎉

> I guess I could re-use that config to commit to the fork tho. At least the `user.name` and `user.email`

That maybe works! Maybe you can put a form after click `fork extension` to let user input name and email.

**Comment by mathieudutour** [comment]
I was more thinking about reading the local git config when you run `ray publish` to use the same in the fork

**Comment by Saafo** [comment]
I'm not sure whether monorepo and the new [sparse-checkout & partial clone](https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/) can help that.

**Comment by mathieudutour** [comment]
Sparse-checkout isn't particularly new and it is indeed what `ray publish` uses under the hood

**Comment by Saafo** [comment]
@mathieudutour well I think the git partial clone would remember git history. So it doesn't?

**Comment by mathieudutour** [comment]
Not sure what you mean. The history of the public extensions repo is always preserve. But with `ray publish` you aren't working with that repo directly.

**Comment by Saafo** [comment]
I'm just thinking about partial clone the git submodule with git history, so you won't need any git info. I'm not sure whether we can do this.

**Comment by mathieudutour** [comment]
Right, we don't want git submodules, they are a pain to deal with for every body involved 😄

**Comment by feyli** [comment]
I'm experiencing the same issue and still haven't found a fix. It does this for every extension I have tested it with. Is the origin of the problem known?

**Comment by mathieudutour** [comment]
the same `failed running git command 'git log origin/main..HEAD'` issue?

**Comment by feyli** [comment]
Same thing, every single command Saafo ran gave the same result when I ran executed it

**Comment by feyli** [comment]
Any clue? 🤔

**Comment by Aayush9029** [comment]
`rm -rf ~/.config/raycast/public-extensions-fork` fixed similar issue for me.

Here's my complete log.

![CleanShot 2023-04-28 at 21 40 23@2x](https://user-images.githubusercontent.com/43297314/235277675-4d4048d2-068d-4d33-8ecc-2e48514f9aa7.png)

**Comment by Saafo** [comment]
Any progress? I met this bug again after upgrading the @raycast/api to 1.53.4

**Comment by mathieudutour** [comment]
What's the error you are facing (there are a few in this thread)?

**Comment by Saafo** [comment]
@mathieudutour 
```bash
$ npx @raycast/api@latest publish
Need to install the following packages:
  @raycast/api@1.53.4
Ok to proceed? (y) y
error -  validate git repository
please first commit your changes
error -  failed validation extension

$ npx @raycast/api@latest publish
error -  validate git repository
please first commit your changes
error -  failed validation extension

$ npx @raycast/api@latest pull-contributions
error -  not in a git repo

# debug tests:

$ git log origin/main..HEAD
fatal: ambiguous argument 'origin/main..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

$ git remote get-url origin && echo "ok"
error: No such remote 'origin'
```

**Comment by Saafo** [comment]
> Can you run git status?

```bash
git status
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/index.tsx

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by mathieudutour** [comment]
right so you first have to commit your changes

**Comment by Saafo** [comment]
But I've already commited
<img width="560" alt="image" src="https://github.com/raycast/extensions/assets/46736350/ce2e8896-4931-43b6-b2a8-07bf7a4d8aa5">

**Comment by mathieudutour** [comment]
then discard the changes of src/index.tsx

**Comment by Saafo** [comment]
> then discard the changes of src/index.tsx

Seems working by stashing it. It's quite odd not allowing local changes. Maybe we can add some tips to remind this?

**Comment by mathieudutour** [comment]
Alright, I'll make the error messages more explicit and close this issue as the OP was fixed a while ago
