### ISSUE TITLE
[Pomodoro] add the command to hide the timer from menu bar

### ISSUE THREAD

**Issue by krutoy-chuvak** [raycast/extensions#4615]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

Hello! Please, add the command to hide the timer from menu bar

**Comment by KELiON** [comment]
Hey, @krutoy-chuvak! You can disable any Raycast menu-bar command, including Pomodoro from preferences: 

![CleanShot 2023-02-07 at 15 22 51@2x](https://user-images.githubusercontent.com/594298/217177231-31b823c8-37c3-4305-92fb-eb683181ed1f.png)

**Comment by alexcom** [comment]
@KELiON sure, but I believe that's not what @krutoy-chuvak  meant. I think that selecting "Show Pomodoro in Menu Bar" has to toggle timer visibility in menu bar on and off, not just turn it on and force user to go to extension settings and press "Deactivate" button.

**Comment by fattypiggy** [comment]
yes, really need this. I found that nearly all the extensions I installed have this issue: can ONLY show up in the menu bar, but CAN NOT hide.

**Comment by alexcom** [comment]
Perhapse it is something that has to be changed globally for all Raycast menubar extensions.

**Comment by callumgare** [comment]
It might still be nice to include a command to do this (or at least a note on how to remove in the README for the extension) but I found that macOS's built in method for removing a menu bar item seems to work. It's similar to removing an item from the dock except you have to hold down `ctrl` when dragging an item out of the menu bar. Once you've dragged it far enough you should see a little `X` icon appear and letting go will remove the item.
![Screenshot 2024-02-26 at 11 02 00](https://github.com/raycast/extensions/assets/346340/f240f0b4-0986-4f08-bb85-3646526635e5)
![IMG_7797 2](https://github.com/raycast/extensions/assets/346340/5fbff941-60f9-40e4-a55c-53f1c68f3891)
(sorry for the analogue screenshot, taking a digital screenshot doesn't seem to capture the `X` icon)
