### ISSUE TITLE
[Yubikey-Code] Newline character is appended to clipboard item 

### ISSUE THREAD

**Issue by bin101** [raycast/extensions#4623]
### Extension

https://www.raycast.com/yoyoyeti/yubikey-code

### Description

Newline character is appended to clipboard item. But I think this is more related to the Clipboard API the extension uses.

### Steps To Reproduce

1. Paste the OTP into a text field either manually or via the paste function of the extension

### Current Behaviour

See that there is a new line character

### Expected Behaviour

I only need the OTP value without the newline

**Comment by bin101** [comment]
@yoyoyeti Are you not active anymore?

**Comment by yoyoyeti** [comment]
@bin101 I'm Sorry I haven't got back to you about this. Covid took me out the other week, so I've been running behind on a few things. I'll try looking into this soon.

**Comment by bin101** [comment]
@yoyoyeti works great now, thank you very much 👍
