### ISSUE TITLE
[Pixabay] Search Music, Search Sound Effects, Search Photos[?], Search Vectors[?], Search Illustrations[?]

### ISSUE THREAD

**Issue by escoolioinglesias** [raycast/extensions#4639]
### Extension

https://www.raycast.com/tonka3000/pixabay

### Description

Expand the search categories:

Right now there is search Videos and search Images.

It would be great to be able to search Music and Sound Effects.

(Not as important) Maybe break down Images into:
-Photos
-Illustrations
-Vectors

### Who will benefit from this feature?

Anyone who might be looking to find and use copyright-free music and sound effects.
Likely a large number of the users who already use the extension.

**Comment by tonka3000** [comment]
Hi @escoolioinglesias ,

Searching for music is not possible via the API, only images and videos AFAIK.

Switching between photo, illustration and vector should be doable via the menu in the top right corner.

Greetings
