### ISSUE TITLE
[GitHub] Add more branches to the `into` field in `Create Pull Request` command

### ISSUE THREAD

**Issue by leechoohyoung** [raycast/extensions#4642]
### Extension

https://www.raycast.com/raycast/github

### Description

all repositories shown in 'Repository' drop down menu.
all local branch shown in 'from' drop down menu.
but origin develop branch not shown in 'into' drop down menu.
only origin master branch shown in 'into drop down menu.

### Steps To Reproduce

1. My company use enterprise GitHub account.
2. My personal GitHub account connected to my company enterprise account as teammate.
3. I logged in personal GitHub account via Raycast Github extension.
4. Raycast is registered in 'Organization account`s setting'.
5. execute 'Create Pull Request' command in Raycast.
6. Select repository.
7. Select from branch.

### Current Behaviour

origin develop branch now shown in 'into'

### Expected Behaviour

develop branch shown in 'into'

**Comment by thomaslombart** [comment]
Would you have different screenshots of what you have in GitHub compared to what you have in Raycast to better understand the issue?

**Comment by leechoohyoung** [comment]
@thomaslombart yes, I uploaded the screenshots. plz check.
<img width="572" alt="1" src="https://user-images.githubusercontent.com/4285647/221444398-70ba76f3-5f5f-448b-a222-93b625d4d3ad.png">
<img width="752" alt="3" src="https://user-images.githubusercontent.com/4285647/221444464-65443292-9284-4992-a738-f4046de35f2a.png">
<img width="748" alt="4" src="https://user-images.githubusercontent.com/4285647/221444478-4a87004a-6999-489b-a937-bbf31b30dabe.png">

**Comment by thomaslombart** [comment]
Ah, I see, thanks for uploading the screenshots. Under the hood, the `into` branch is just the repository's default branch. So we'd need to add support for other branches for the `into` field. I'll add that as a feature request!
