### ISSUE TITLE
[iMessage 2FA] ...

### ISSUE THREAD

**Issue by lacer2k** [raycast/extensions#4648]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

293578 cannot query the data on macos big sur 11.7.1

### Steps To Reproduce

with raycast on macos big sur 11.7.1 i use the app and can query the data

**Comment by thomaspaulmann** [comment]
Mmh... I don't have a way to reproduce this. Can you send some error?

**Comment by lacer2k** [comment]
hi sorry, it's my fault, on my other macbook is working, but on my old one gives me error. maybe is the os version big sur 11.7.4? could be a hint?

**Comment by lacer2k** [comment]
this is the error message:

Cannot query the data sqlite3: Error: unknown option: -]son
Use -help for a list of options.
