### ISSUE TITLE
[Extension Feature Request] Todoist Should Show Labels

### ISSUE THREAD

**Issue by SmashMineGame** [raycast/extensions#465]
# Extension – [Todoist](https://github.com/raycast/extensions/tree/main/extensions/todoist)
Author: @thomaslombart

**Describe the feature and the current behavior/state.**
There's no indicator as to what labels a task has, it would be great if it could show that somehow.

**Who will benefit with this feature?**
Anyone that uses labels in Todoist

**Comment by SmashMineGame** [comment]
I'm not exactly sure where the labels can be shown. In the Todoist apps, it's shown as greyed out text underneath the main task name however I don't know if raycast has the ability to do that. Alternatively the label can be shown with an icon and grey text on the right side of the task name like how the commands have the group name in raycast.

**Comment by thomaslombart** [comment]
Unfortunately, Raycast doesn't have the ability to do that for the moment. There are different ways to go about it:
1. Put the labels in the subtitle and move the description to a `<Detail />` component (markdown being supported). That would solve the issue but those who don't make use of labels would see the description is removed.
2. Put the labels in a more detailed view of a task. There wouldn't be any labels on the list view, though.
3. Put the labels in the accessory title (the info on the far-right), it's used to display the due date or the project, though. So we'd need to maybe split it up with a separator (a comma or by using`|`)

It's not ideal but there are lots of information to show on a task and the current API doesn't allow showing that many information 🙂

**Comment by SmashMineGame** [comment]
I agree, there currently isn't a way to show all the information about a task. Do you think there could be some sort of setting or toggle that switches between showing labels and descriptions in the subtitles. I also think that a more detailed view of a task would be nice, maybe that can be the new default action when pressing enter on a task. I don't see much of a use for opening the task in the browser.

**Comment by thomaslombart** [comment]
I think it would be feasible to show labels instead of descriptions via the [preferences](https://developers.raycast.com/api-reference/preferences#preferences) API, specifically with a dropdown or a checkbox. 

However, I find it to be confusing and I feel like this is "hacking" the UX.

**Comment by thomaslombart** [comment]
After some investigations, it appears that adding a detailed view of a task is not that easy. The [Detail](https://developers.raycast.com/api-reference/user-interface/detail) component only allows showing a markdown string. While it's a good use case to show the task's title and description, it's not the case for other metadata such as labels.

I'd suggest closing this issue or putting it in a frozen state waiting for an improvement from Raycast's team ✌️
