### ISSUE TITLE
[Linear] Status icons are not visible in light mode

### ISSUE THREAD

**Issue by imthath-m** [raycast/extensions#4657]
### Extension

https://www.raycast.com/linear/linear

### Description

Todo Status icon is not visible in light appearance

### Steps To Reproduce

1. Open Raycast in light appearance
2. Open Linear assigned issues
3. Look at issues with Todo status

### Current Behaviour

Status icon is not visible properly

<img width="935" alt="image" src="https://user-images.githubusercontent.com/46041492/217419730-c376678e-f437-4982-a46d-c4674c4193a5.png">

### Expected Behaviour

Probably, they should be in black or grey

**Comment by thomaspaulmann** [comment]
Thanks for flagging @imthath-m 👋
