### ISSUE TITLE
[Visual Studio Code Recent Projects] ... Use command to open any directory on local system

### ISSUE THREAD

**Issue by rollokd** [raycast/extensions#4659]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

The command should open a search bar similar to the file search functionality but when you action a certain file it opens in visual studio code

### Who will benefit from this feature?

The current functionality only allows you to open folders you have already opened in VSCode, there is no way to open a folder for the first time

### Anything else?

I am used to this functionality in Alfred, a similar system to raycast, trying to convert to raycast because there are some better features but I am missing this functionality

**Comment by thomaspaulmann** [comment]
Does this new command help #4650?
