### ISSUE TITLE
[Code Stash] ...

### ISSUE THREAD

**Issue by NeshaLe** [raycast/extensions#4663]
### Extension

https://www.raycast.com/ben-greenwood/code-stash

### Description

My somewhat extensive code stash has just gone this morning. It is completely empty. Is there a way to get those back??

### Current Behaviour

it's just empty now, and I'm reluctant to put anything there until issue is resolved.

**Comment by ben-greenwood** [comment]
Hey @NeshaLe, the code-stashes are just saved in your local storage, did you happen to clear that for any other reason?

@pernielsentikaer this is the second time I've heard this issue come up, does the local storage in Raycast get cleared after a certain amount of time or something?

**Comment by NeshaLe** [comment]
Hello @ben-greenwood, thank you for reply; as far as I know, I didn't do anything to clear local storage. Does this mean there is no way to get stashed code back?

**Comment by NeshaLe** [comment]
I am reading now about Storage API and that it is not meant to store large amounts of data. Not sure what error would too large amount of data have triggered, but nothing happened on my end, at least, not a visual feedback. Could that trigger local storage to clear somehow? Wouldn't be better to use Node's built-in APIs to write stash in the extension directory perhaps? Daily backups (time machine) I do probably couldn't be of help to recover my previous stash?

**Comment by ben-greenwood** [comment]
Hi @NeshaLe, Code Stash was never intended to work as a long-term repository for code so local storage felt like a reasonable choice. Unfortunately, unless Raycast natively backs up your local storage, there's nothing that can be done.
