### ISSUE TITLE
[Google Translate] For the given word i would like to see translation not only from First Language to Second Language but also from Second Language to First Language

### ISSUE THREAD

**Issue by DRAGONFLY360-CZ** [raycast/extensions#4664]
### Extension

https://www.raycast.com/gebeto/translate

### Description

For the given word i would like to see translation not only from First Language to Second Language but also from Second Language to First Language.

Some time ago i think it did work in that way.

**Comment by gebeto** [comment]
Yeah, it looks like it works differently now, I'm checking it

**Comment by gebeto** [comment]
Fix is ready, also improved autodetect in Translate Form

https://github.com/raycast/extensions/pull/4667

**Comment by gebeto** [comment]
Fix was merged, you can check the extension 🙌

**Comment by DRAGONFLY360-CZ** [comment]
wow, amaizing, now it is working ! 👏 thanks a lot
