### ISSUE TITLE
[Color Picker] Support lower cased hex color

### ISSUE THREAD

**Issue by otakustay** [raycast/extensions#4670]
### Extension

https://www.raycast.com/thomas/color-picker

### Description

Please support lower cased hex color format like `#ff16af`, some team requires color to be lower cased in their coding standard.

**Comment by thomaspaulmann** [comment]
That was fast :D Do you want to add another option to the preference? Should be relatively straight forward to contribute.

**Comment by otakustay** [comment]
I created #4712 to add `hex-lower-case` format, however I didn't successfully setup the whole environment, I don't have `swift` currently, so not 100% sure the code is correct
