### ISSUE TITLE
The utility would be amazing if after finding a contact or a company we can open the link to the contact / company from Raycast!

### ISSUE THREAD

**Issue by rocnoa** [raycast/extensions#4674]
### Description

The utility would be amazing if after finding a contact or a company we can open the link to the contact / company from Raycast!

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
