### ISSUE TITLE
[Logseq] Allowing Indenting in Quick Note

### ISSUE THREAD

**Issue by mharmel** [raycast/extensions#4677]
### Extension

https://www.raycast.com/futantan/logseq

### Description

When creating a Quick Note that contains linebreaks, multiple bullets in Logseq will be created. Hitting the tab-key does however not allow to create a nested bullet.

If a linebreak followed by tab would get interpreted as an indentation, one could already add another level of detail in a Quick Note, without having to go into Logseq. 

### Who will benefit from this feature?

Everyone who got familiar with adding details nested under a bullet and misses this, when creating quick notes on the fly.

**Comment by Holanda73** [comment]
would be very nice to have the feature request
