### ISSUE TITLE
[Todoist] Can't be used due to "write EPROTO error"

### ISSUE THREAD

**Issue by lxxjn0** [raycast/extensions#4679]
### Extension

https://www.raycast.com/thomaslombart/todoist

### Description

It looks like the connection with the todoist api is broken for me.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/48052622/217693695-75bf944f-48cc-4b6e-b354-6e8318bd3b3e.png">

### Steps To Reproduce

1. Configure todoist extension with api key
2. use any feature in todoist extension
3. not working with EPROTO error

**Comment by thomaslombart** [comment]
Todoist's API has been pretty unstable these past few months (mostly after upgrading to v2), could you try using the commands again to make sure it's not related to Todoist internals?

**Comment by LunaticMuch** [comment]
That error is because of a bad certificate from Todoist. Since Raycast uses node v18 which is built on openssl that has SECLEVEL=2 as default, old and bad certificates generate an issue. The SSL library simply refuses to negotiate them.

No solution is possible except having Todoist to use a decent certificate.

**Comment by lxxjn0** [comment]
It was a problem caused by using the extension while connecting my company's VPN. It was accessible normally without VPN.

Thank you for your confirmation :)

**Comment by LunaticMuch** [comment]
> It was a problem caused by using the extension while connecting my company's VPN. It was accessible normally without VPN.
> 
> Thank you for your confirmation :)

You should let your company know they have a certificate trouble 😄 
Whoever is dealing with the certificate passed to raycast on your local has an SSL trouble.
