### ISSUE TITLE
[Folder Search] Don't wait for spotlight when there are pinned folders

### ISSUE THREAD

**Issue by jrz** [raycast/extensions#4686]
### Extension

https://www.raycast.com/GastroGeek/folder-search

### Description

Situation is when you have a number of pinned folders and where spotlight is kind of slow (even a 1 sec delay). Probably because of the huge number of files / directories on the system.

When you start a search by typing, it will first waits for spotlight to finish / stream results before listing the results  (and prioritizing the pinned folders) . In the mean time, the pinned folders do not show up.

A better behavior would be to instantly show the pinned results while typing, and let spotlight do its work in the background. When it finished / streams results, the results should still be filtered / prioritized like it is right now.

### Who will benefit from this feature?

People with pinned folders

**Comment by omarshahine** [comment]
I have seen this, although I cannot reproduce it now. Interesting suggestion. I didn't write any of this code but I can take a look and see if this is easy or difficult.
