### ISSUE TITLE
[Color Picker] Organize Colors grouping and naming

### ISSUE THREAD

**Issue by guspimentel** [raycast/extensions#4694]
### Extension

https://www.raycast.com/thomas/color-picker

### Description

Lovely extension btw, @thomaspaulmann!

As a designer, I build a lot of style guides and design systems. It'd be awesome to be able to save and organize colors by clients, projects and themes. So my suggestion is to add the functionality of naming the colors and grouping them into folders. I imagine that it could be useful for teams to share colors.

### Who will benefit from this feature?

Individuals and teams that use recurring colors

### Anything else?

Structure-wise, it could follow how Figma organizes color styles. One thing to look out is how to handle duplicates. Should it merge all colors that share the same folder name?

**Comment by thomaspaulmann** [comment]
That could be cool and indeed I had the idea of some organizing, mostly around building color themes. The themes are just groups of colors. I can look into adding support for this soon.
