### ISSUE TITLE
[Open Link in Specific Browser] ...

### ISSUE THREAD

**Issue by petty** [raycast/extensions#4698]
### Extension

https://www.raycast.com/koinzhang/open-link-in-specific-browser

### Description

This doesn't recognize or use Safari on macOS ... not in Browsers (which does include Mail??) & not under Apps.

It would be awesome if I could customize the apps that do show up & add the ones that are missing.

**Comment by koinzhang** [comment]
Thank you for your feedback, I will investigate the reasons and then make improvements

**Comment by koinzhang** [comment]
Hi @petty. I've submitted a PR #5635 to fix the safari not showing issue.

There is a reason why email clients and other types of apps appear in the recommended apps:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/36128970/228459451-70072af1-29ed-4e59-a09b-2e18bd64062c.png">
You can read the extension's [introduction](https://www.raycast.com/koinzhang/open-link-in-specific-browser)

Tips: 
You can add Favorites from the Other section by selecting the apps you use (new shortcut is ⌘S, old shortcut is ⇧⌘P, You can find them in the ActionPanel).
