### ISSUE TITLE
[Extension Feature Request] Safari extension support for Safari Technology Preview

### ISSUE THREAD

**Issue by fortybillion** [raycast/extensions#470]
# Extension – [Safari](https://github.com/raycast/extensions/tree/main/extensions/safari)

Author: @loris @thomaspaulmann 

**Describe the feature and the current behavior/state.**

The "local tabs" query looks for an application named "Safari". It would be great to be able to switch that to look for "Safari Technology Preview".

**Who will benefit with this feature?**

Anyone who uses STP instead of stock Safari as their main browser.

**Any Other info.**

n/a

**Comment by loris** [comment]
@fortybillion Great suggestion, will install Safari Technology Preview on my device to test. Will probably make it an extension setting where you can switch between Safari or STP (seems better than trying to support both tabs list at the same time)
