### ISSUE TITLE
[Toggl Track] Certain Projects No Longer Available

### ISSUE THREAD

**Issue by johndturn** [raycast/extensions#4701]
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Description

Love the toggl track extension! I use[d] it multiple times a day! However, in what I assume might have been a recent release, it appears that some of my Toggl Projects are no longer available for selecting when starting a new time entry. 

This is even more unfortunate as the project that I bill to most these days is included in that list. 

I'm able to still select and bill to this project via the Toggl Track macOS, iOS and web apps. I also have a personal application that I built using the Toggl API and this personal application still recognizes the project as well. 

I noticed that this appeared to happen after recently I was forced to re-input my toggl track API key, if that's helpful at all. Probably about 2ish weeks ago? 

### Steps To Reproduce

1. Open the Toggl Track Extension
2. Attempt to create a new Time Entry
3. Search for a project
4. Some projects show while others don't

This also manifests itself when you open the extension and you can see recent time entries. The ones that are related to a project that it can't find all seem to indicate no project. 

### Current Behaviour

Cannot find certain projects. 

### Expected Behaviour

Should find all projects in your Toggl Workspace.

**Comment by rogatty** [comment]
There was only one major update recently which could affect this, but it was merged 2 days, not 2 weeks ago: https://github.com/raycast/extensions/pull/4476

If you built an app then you should be able to debug it yourself. 🙂 Can you check if those projects are returned from `https://api.track.toggl.com/api/v9/workspaces/${workspaceId}/projects`? Are they in the same workspace as the working ones?

**Comment by johndturn** [comment]
@rogatty Yes, the specific project that I'm referencing does get returned when hitting that endpoint. I have 1 workspace and all projects are all in the same workspace.

**Comment by rogatty** [comment]
@johndturn that's weird. I think there is only one place that could ignore a project returned from the API:
https://github.com/raycast/extensions/blob/ac3bf742ac48711035a9f3346f975169111accb2/extensions/toggl-track/src/context/ProjectGroup.ts#L13-L16

But it would mean that these projects belong to a different workspace, which isn't returned from `https://api.track.toggl.com/api/v9/workspaces`. You say all your projects are in the same workspace, but can you double check they all have the same `workspace_id` when returned from the API?

If IDs match then I don't know how to help without further details. Can you post the API responses after censoring them? Maybe there is some important detail not visible at first.

**Comment by johndturn** [comment]
@rogatty I believe that I understand what's happening here after digging in a bit more. I apologize about not getting better details till now. 

A couple of things that I think will be valuable: 

1. v8 of the API sent over, from what I can tell, an ACTUAL full list when querying `https://api.track.toggl.com/api/v8/workspaces/${workspaceId}/projects`. **_This is what I tested earlier without realizing that you were using v9 of the API._**
2. v9 of the that endpoint is actually paginating the projects for a given user without sending back any sort of indication. When I attempted to find my project (which starts with `Z`) using v9 of the endpoint, it didn't show up in the list. 
3. Investigating the docs for this endpoint (https://developers.track.toggl.com/docs/api/projects#get-workspaceprojects) I found that there is a `page` query param you can pass in. Using Postman I tested the endpoint passing in `page=2` and my project showed up. 

So, it appears that you're only fetching a single page of projects from that API, and people that happen to have a lot of active projects will end up with some projects missing. 

> Note that I couldn't find anything in their docs that gives a specific indication on the number of projects returned for a page by default, but my testing shows 151 elements returned for some reason. 

**Important Note**: They do have a `per_page` query param that you can pass in, specifying the number of records that you'd like to query for. I used 500 and all of my projects came through (I have about 200ish active projects... I know, I should clean those up). 

So, I believe that if you're ok with this, the easiest fix would be adding in the `per_page` query param on [this line](https://github.com/raycast/extensions/blob/ac3bf742ac48711035a9f3346f975169111accb2/extensions/toggl-track/src/toggl/index.ts#L17) then updating the extension documentation to point out that limitation. I can submit the PR for this change if you're open to it, or if you'd like to approach the problem another way, that's understandable too. 

Thoughts?

**Comment by rogatty** [comment]
@johndturn Ah, the migration guide didn't include information that a pagination limit has been introduced. 😞 Using `per_page` sounds good to me, but I believe @franzwilhelm has the final say as the extension creator. Can you try using `-1` or `0` to disable pagination, instead of using an arbitrary number? If not, then 500 sounds as good as any other large number.

**Comment by johndturn** [comment]
@rogatty Just tested it and neither `-1` nor `0` work to send all records.

**Comment by rogatty** [comment]
@johndturn I'd go with an arbitrary number, then. 🙂

**Comment by franzwilhelm** [comment]
Fetching all projects should not be a problem with servers nor internet connections among ppl using Raycast in 2023, so I think increasing per_page to maximum is the correct approach here @rogatty @johndturn 

Thanks for pointing this out! Feel free to open the PR, and I'll approve ASAP @rogatty

**Comment by johndturn** [comment]
@franzwilhelm @rogatty Just installed the updated version of the extension after the PR was merged and it's all working as expected. 

Thanks all!
