### ISSUE TITLE
[Set Audio Device] Changing audio device does not affect sound effects

### ISSUE THREAD

**Issue by BionicBison05** [raycast/extensions#4706]
### Extension

https://www.raycast.com/benvp/audio-device

### Description

Changing the audio device through the extension changes the "Play sound effects through" setting from "Selected Sound Output Device" (sound effects play through the active audio device) to whatever the previous audio output was before switching. This results in sound effects always playing through the first device that was in use before using the extension until the setting is changed back to "Selected Sound Output Device" in System Settings.

### Steps To Reproduce

1. Switch audio device using the extension
2. Observe that the "Play sound effects through" setting in System Settings has changed from "Selected Sound Output Device" to the previous audio device in use before switching

### Current Behaviour

"Play sound effects through" setting is affected by the extension

### Expected Behaviour

"Play sound effects through" setting remains untouched

**Comment by jcugat** [comment]
The issue is still relevant.
