### ISSUE TITLE
[Extension Bug] Things 3 - every command results in error (-1743) 

### ISSUE THREAD

**Issue by bbrandtom** [raycast/extensions#471]
# Extension – [Things 3](https://github.com/raycast/extensions/tree/main/extensions/things)

Author: @loris 

## Description

Every command I've tried results in an error (-1743).
The extension says I need to properly install and make sure I run things, but the app is running.
I've uninstalled and installed the latest version of the extension and problem persist.

## Steps To Reproduce

1. Open Raycast
2. Write "Add New To-Do"
3. Press Return
<img width="267" alt="image" src="https://user-images.githubusercontent.com/45038918/144660432-a3db4bb8-6d23-4079-b6e5-345e86e13b18.png">

### Raycast version
Version: 1.26.1
Things version: 3.15.8

**Comment by loris** [comment]
Hi @bbrandtom That's weird, probably some permission issues
Can you launch "Script Editor" (it comes with your macos install), choose "JavaScript" in the upper left dropdown and run the following script: `Application('Things').tags()`
It should show an array of results:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/8362/144662621-73eb5f22-69c4-45ba-bb89-e26383014d7a.png">

any error showing up?

**Comment by bbrandtom** [comment]
Thanks for the quick answer!
Yes you are right - 
<img width="688" alt="image" src="https://user-images.githubusercontent.com/45038918/144673772-07b1b623-8fdf-4153-8738-a77dab2c48be.png">

Any idea what can I do?

Originally `Things.app` was located under `Downloads`.
I've `cmd+drag` it to Applications lately (when I installed Raycast)

**Comment by loris** [comment]
@bbrandtom Can you try the following script `Application('Things3').tags()`?
(replaced `Things` with `Things3`, it should work both way, but let's try)

**Comment by bbrandtom** [comment]
Now it works :-)

<img width="712" alt="image" src="https://user-images.githubusercontent.com/45038918/144698157-71009689-89bf-4329-963e-d73eb927321c.png">

**Comment by bbrandtom** [comment]
Now the Raycast Things' extension also work for me 🤔 

I'm not sure what happened.

**Comment by loris** [comment]
Oh this is very strange. Glad it works but no idea either. Maybe your app was not properly registered because it was in the Downloads Folder?

**Comment by bbrandtom** [comment]
I don’t think that’s the case. Anyway, thanks for the help and for the extension!
