### ISSUE TITLE
获取翻译文本优生级问题。

### ISSUE THREAD

**Issue by kunpehx** [raycast/extensions#4710]
### Extension

https://www.raycast.com/isfeng/easydict

### Description

当在网页中选择需要翻译内容后，前在 Raycast 中输入另外的文本，选择 Search Word，会默认使用选择的文本进行翻译。

### Steps To Reproduce

> 前提：将 Search Word 设置为 Fallback command.
![](https://media.cleanshot.cloud/media/14858/IkM6XMhkpkik9ZVt5aGInjCAIaRFOtVeaMIIRGmB.jpeg?Expires=1676038249&Signature=S~gv92V2DEf4w~mlS8EaQ7-Y8F1~nKiluIiPAkJ2B1wm31zOpRhrVnukk6JGOC3~mjcuZqk7GNnf8j867G2QJmoUiF2VWo9iY5Y1Q0m9Gkzg~iv-nE18jd2jE82P6bxwbS1u~tAdryVvT7~r6AaWZEc~F82MtCaEGHoYFOr4zrV9GbEAed6VGuGIsk1vxlobpVoGByN008ZrhofZFAYREeddnkOuHJRJDZ2VkTvjpjSzHGM9altLrXTLjocE6rd7QO3eQVsSRbjI3AS2WVw5jF3c-86e97mMIuMxeV0D7OK-zm2sh-BActvNJQHfnocojR-NeZnJ-Yks4sjfTcvQJw__&Key-Pair-Id=K269JMAT9ZF4GZ)
1. 选择页面上出现的文本
2. 在`Raycast`输入要翻译的内容，选择 `Search Word`.
3. 翻译的文本是页面上选择的而不是输入的。
4. 是否可以优化一下，在用户有输入文本的下，优化取得输入文本。即调整一下获取翻译词汇的优生级。

具体可以参考以下视频：
URL: [演示视频](https://cln.sh/cgwjRTRC)

**Comment by tisfeng** [comment]
明白了，感谢反馈，稍后我优化一下。

**Comment by kunpeh** [comment]
这个插件很好用，谢谢你的付出。

**Comment by tisfeng** [comment]
问题原因已找到，目前正测试解决方法，稍后会发布新版本。

**Comment by tisfeng** [comment]
感谢反馈，我稍后排查一下。

**Comment by tisfeng** [comment]
@raycastbot close this issue
