### ISSUE TITLE
[Quick Search] Can't search input text in fallback command.

### ISSUE THREAD

**Issue by kunpehx** [raycast/extensions#4711]
### Extension

https://www.raycast.com/iwfan/quick-search

### Description

Can't search input text in fallback command.

### Steps To Reproduce

1. Setting `Quick Search` become to fallback command.
  ![](https://media.cleanshot.cloud/media/14858/iayVmt7HS69N0qzw6biIvuAZxOJdTMl3sQNOvxmP.jpeg?Expires=1676039494&Signature=LGdDyz~RTXxvKmN9eEYRx-IZ6hL39nJtzpKQxaM7T-QklG8NHBrupvY7LndinOwZTaLW9tJVcVd6nRTPfM3bOytncOX7mEfUhIuYhMj0EBqtaQcNTWnwx7Xs3Krrv2xZz7X386dD6W2svagwh13Ix9WgXRW8qLAXvPU0YYylZ0CyrFuVtfYB49RvmwfKp~iCWhqlxc5AuoDjG1mTI~BCqXJNSGztUaHqyD3AyMDxGGd9EOJ6QXbFJ7jkN1qooRRnGp9~HCR4k1z2QDkpFv505n0by0-3iiDy40VNZ6rxinrS1MYhDguuWpGpKmLub6J2IxmoUQf-fmrWneOVN9ysKA__&Key-Pair-Id=K269JMAT9ZF4GZ)
2. Add Quick Search to the default search. 
3. Enter keywords to search.
4. Quick Search does not use the entered keywords to search, but the clipboard or selected text to search.
5. Sample video:
https://cln.sh/4JKR7rdk

**Comment by iwfan** [comment]
@kunpehx Sorry for the slow response.

I've added support for fallback command, and will publish a new version soon.

**Comment by iwfan** [comment]
@kunpehx The new version has been published [here](https://www.raycast.com/iwfan/quick-search)

@raycastbot close this issue
