### ISSUE TITLE
[Typefully] ... Raycast Extension is no longer working :(

### ISSUE THREAD

**Issue by FrancescoFornaro** [raycast/extensions#4713]
### Extension

https://www.raycast.com/typefully/typefully

### Description

Since a couple of day ago, the extension stopped working for me.
When I save a draft via Raycast, I get this error:

- Failed Creating Draft fetch is not defined

I unistalled and installed the extension again with no results.

### Steps To Reproduce

Open Typefully extension
Write something as new draft
Try to save it
You get the error

**Comment by FrancescoFornaro** [comment]
<img width="297" alt="Screenshot 2023-02-10 alle 09 54 35" src="https://user-images.githubusercontent.com/125015366/218049986-81a96fa4-9ce4-4ff2-9f18-588a6b7cb3b7.png">

**Comment by mathieudutour** [comment]
Ah indeed! Should be fixed now

**Comment by FrancescoFornaro** [comment]
Thank you, after a new install it works as designed 🙂
BTW: Beautiful, usefull extension which changes a lot about my workflow and content creation. Thank you!
