### ISSUE TITLE
Error on open with visual studio code [Drupal Toolbox] ...

### ISSUE THREAD

**Issue by vervorm** [raycast/extensions#4714]
### Extension

https://www.raycast.com/emircanerkul/drupal-toolbox

### Description

Hi,

I get this error  when I tried the command "Open in Visual Studio Code"

`Error Occurred /bin/sh: code: command not found`

The other commands work perfectly.
I use DDEV as development tool.

And thanks for the tool, was looking for all kind of solutions to stop writing 'ddev drush cr' all the time

regards
S

![Screenshot 2023-02-10 at 11 00 33](https://user-images.githubusercontent.com/5492484/218062747-dabd42c2-7a25-4ea0-947f-257dbe66b3bc.png)

**Comment by emircanerkul** [comment]
@vervorm  Seems your OS cannot find the VS Code binary code on its path. Please refer to this https://code.visualstudio.com/docs/editor/command-line#_code-is-not-recognized-as-an-internal-or-external-command

**Comment by emircanerkul** [comment]
& your welcome

**Comment by vervorm** [comment]
thanks and sorry to think it was a bug 🫢
