### ISSUE TITLE
[Google drive]

### ISSUE THREAD

**Issue by idimitrijevic** [raycast/extensions#4721]
### Description

Hey guys,

Can you please add multiple volumes drives in Google Drive root path? We have one at the moment, but I would like to multliple account in order to index them.

Thank you
![218094569-5f991ad9-648a-4f07-934c-9b7333e133e0](https://user-images.githubusercontent.com/28489791/218128271-7df5e254-ac93-41a8-bc86-6d1bedf09403.png)

**Comment by mathieudutour** [comment]
Could you open an extension issue instead of an API issue? https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cfeature+request&template=extension_feature_request.yml&title=%5BExtension+Name%5D+...
