### ISSUE TITLE
Can't use ky to make REST requests

### ISSUE THREAD

**Issue by imprakharshukla** [raycast/extensions#4731]
### Description

Hey! I am trying to use ky(https://www.npmjs.com/package/ky) to make REST calls from my extension but anytime I even import ky, I receive the following error:

    TypeError: globalThis.Request is not a constructor
    constants.ts:10:19
    Object.<anonymous>:index.js:142:3
    Module._compile:loader:1149:14
    Module._extensions..js:loader:1203:10

This constants.ts file appears to be used by a package or maybe Raycast, not sure since it's the only output I get.

    import ky from "ky";
    import {BASE_URL, REFRESH_TOKEN} from "../const";
    
    export const getAccessToken = async (): Promise<{ access_token: string }> => {
        return ky.post(`${BASE_URL}/auth/token`, {
            json: {
                refresh_token: REFRESH_TOKEN
            }
        }).json();
    }

### Steps To Reproduce

1. Install ky and import it.

### Current Behaviour

Receiving the following error: 

    TypeError: globalThis.Request is not a constructor
    constants.ts:10:19
    Object.<anonymous>:index.js:142:3
    Module._compile:loader:1149:14
    Module._extensions..js:loader:1203:10

### Expected Behaviour

Should make the request free of error.

**Comment by mathieudutour** [comment]
From `ky`'s README: 
> Ky targets [modern browsers](https://github.com/raycast/extensions/issues/4731#browser-support) and [Deno](https://github.com/denoland/deno). For older browsers, you will need to transpile and use a [fetch polyfill](https://github.com/github/fetch) and [globalThis polyfill](https://github.com/es-shims/globalThis). For isomorphic needs (Node.js + browser, like SSR), check out [ky-universal](https://github.com/sindresorhus/ky-universal).

You need to use packages compatible with Node.js
