### ISSUE TITLE
[GitHub] Option to exclude archived repositories from "Search Repositories"

### ISSUE THREAD

**Issue by tomgenoni** [raycast/extensions#4732]
### Extension

https://www.raycast.com/raycast/github

### Description

Currently the list of repositories includes archived ones. It would be great if in additional to the "Include Forks" checkbox there was a "Include Archived" (probably set to `true` by default).

The GitHub API includes `"archived": true,` in the repo data so I assume they could be filtered out.

### Who will benefit from this feature?

Any GitHub user with a lot of old archived repos that they want to keep but do not need to see each time they start a search. It was a popular request of the GitHub UI results https://github.com/community/community/discussions/8591

### Anything else?

Thank you so much for this extension! Really great to use.

**Comment by thomaslombart** [comment]
Thanks for suggesting this improvement. I added it to our backlog 😊

In the meantime, don't hesitate to open a pull request for this if you feel like coding!

**Comment by Nirajn2311** [comment]
Hi, I'd like to take a jab at solving this.

**Comment by thomaslombart** [comment]
Sure, go ahead! Let me know if you need any help.
