### ISSUE TITLE
[Arc] Ability to manage boosts from the extension

### ISSUE THREAD

**Issue by pomdtr** [raycast/extensions#4733]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

I would like to be able to list my boost, toggle them, and open them in my prefered editor from raycast.

### Who will benefit from this feature?

All arc users

### Anything else?

Example boost directory:
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/17577332/218251736-8b5dec0a-54d4-4adf-a315-8fd89ba3eb30.png">

**Comment by thomaspaulmann** [comment]
That could be neat. AFAIK there isn't an official API to toggle them. Opening them in an editor could work. Do you want to contribute to the extension?

**Comment by pomdtr** [comment]
I'm a bit crowded in side projects right now, but I'll try to find some time.

Btw I need to demo sunbeam to you, it is almost ready for it's first beta :)
