### ISSUE TITLE
[Extension Feature Request] Improvements for the emoji search

### ISSUE THREAD

**Issue by timonbimon** [raycast/extensions#474]
# Extension – [Emoji](https://github.com/raycast/extensions/tree/main/extensions/emoji)

Author: @FezVrasta 

The Emoji search is one of the most used workflows on Alfred for me, so super happy to see this has been added to Raycast => on the path to one hurdle less for finally switching. 🤗

Three things (in order of importance) that make it really hard for me to use right now are
- lack of alternative names that one can use for searching for the emojis. An example: I tried searching `arm`, `strong`, `muscle` and didn't find the emoji (that here is called `Flexed Biceps`) that I wanted to use. It's near impossible to remember what all these emojis are called exactly, so being able to type in sensible description that match the right emojis is really important to me
- The Alfred workflow has an option to hit "command + enter" and the selected emoji will directly be copied AND pasted into the text you're currently in. Is it possible to add this to this extension as well?
- the emojis are quite small in the results... is there a way to make them bigger? I care less about the text description of the emoji and more really just want to see the actual emoji in the results when searching for one.

Thanks a lot for developing this in the first place! :)

**Comment by FezVrasta** [comment]
Hi 👋 regarding your first point, we have a ticket to track the feature https://github.com/raycast/extensions/issues/451

About 2. I'm not completely sure, I think available actions from the API are either Insert OR Copy, not both at the same time.

About 3, no luck for now, the extensions API doesn't allow larger icons.
