### ISSUE TITLE
[Toothpick] ...

### ISSUE THREAD

**Issue by InternetJohnny** [raycast/extensions#4742]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

When attempting to disconnect my Airpods Pro, Raycast will confirm they disconnected successfully, when in fact they are still connected.

### Steps To Reproduce

1. Connect Airpods Pro to Mac
2. Open Raycast > `Manage Bluetooth Connections`
3. Select Airpods Pro and press `Enter` to disconnect

### Current Behaviour

Headphones do not disconnect.

### Expected Behaviour

Headphones disconnect, otherwise an error message appears saying it was not possible to disconnect.

**Comment by HomemadeToast57** [comment]
Experiencing this as well using sony WF-1000XM4 bluetooth earbuds on MBP 2019 Ventura

**Comment by VladCuciureanu** [comment]
Hey! Known issue, not much I can do. See #3636 for a temp solution

**Comment by InternetJohnny** [comment]
Solution for anyone looking, worked for me:
[#3636 comment](https://github.com/raycast/extensions/issues/3636#issuecomment-1416710536)

**Comment by VladCuciureanu** [comment]
So, good news (kinda).
#8193
I implemented a compat-layer for 'blueutil' which improves this situation.

1. Install 'blueutil' via brew
2. Update Raycast
3. Update Toothpick
4. Open Toothpick preferences
5. Switch Bluetooth Backend to 'blueutil'

Connecting/disconnecting should be faster and less flaky. Testing was limited so I can't guarantee that it's perfect but, to me, it looks like an improvement :>
