### ISSUE TITLE
[1Password] Work with multiple vaults at the same time

### ISSUE THREAD

**Issue by mgonto** [raycast/extensions#4744]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

I'd love to be able to connect to multiple vaults at the same time

### Who will benefit from this feature?

anybody who has multiple vaults

**Comment by dhnaranjo** [comment]
I'd definitely like this feature.

**Comment by pprotas** [comment]
This would be awesome. I have a work account and a personal account. When installing the extension I chose my personal account, and as far as I can tell there is no way for me to switch to my work account.

I want to be able to see the passwords of both accounts in the same raycast window.

**Comment by vitorf7** [comment]
This definitely would be amazing, rather than having to use the 1Password Quick Access to search for a password which does allow to work with multiple accounts, I would prefer to use this with Raycast instead.

**Comment by dalposenrico** [comment]
I saw more issues have been opened about this, adding my comment just to say this would be really nice

**Comment by dagfinnhagen** [comment]
Same here, but would like the option to choose which vaults it should search. Right now I'm using 6 valuts, but when I'm at work I need it to search only my "work vaults".. It seems to me now that is searches all vaults so would be nice with an option to be able to disable/enable which vaults should be included in the search.

**Comment by kpeatt** [comment]
@Luk4h How do you tell Raycast which account you want to use? It seems to choose (what seems like) randomly for me.

**Comment by Luk4h** [comment]
Per the 1Password documentation, it auto sign-in on the lastest signed on account. If you reset the extension cache it should ask for the account.

On another note, I am working on an action that will allow to switch to another account, as well other vaults.

I am looking for input on the Vaults... Currently I think the approach should be a new command "My Vaults" where you are allowed to select the vault you want to search the passwords on.

**Comment by jntme** [comment]
I'd love that feature too. The Alfred App (https://alfred.app/workflows/alfredapp/1password/) searches all vaults per default, this is one of the features I miss most about my whole Raycast experience.

**Comment by James-DeLorenzo** [comment]
I just ran into this issue when adding my work account to my 1password. I am running v8. 

Raycast kept throwing an error until I ran the `op` cli command myself and it was asking for which vault to default to. Then this extension started working again. However I don't see in this extension's preferences to select which account to default.

 To fix this issue I think it would be handy to keep a list of the current accounts logged in to change what vaults to search. And on top of that which vault in said account to list as well.

**Comment by Luk4h** [comment]
With the lastest update, the extension is able to use multiple vaults, filter items per vault, and switch accounts in extension. Right now there are no support for retrieving the passwords for multiple accounts at once. I will be closing this issue, since it is named as "Work with multiple vaults at the same time". And as for now, it has been fixed.

@raycastbot close this issue

**Comment by mgonto** [comment]
Thanks for sharing! When is this shipping?

--gonto

**Comment by Luk4h** [comment]
It has been shipped! You should be able to use it right now, make sure to run "Check for extension updates" or
raycast://extensions/raycast/raycast/check-for-extension-updates

**Comment by mgonto** [comment]
I'm up to date but it's not working. When I go to My Passwords I get the following

Thanks!

--gonto

**Comment by Luk4h** [comment]
I belive this issue is related to #12492, waiting for the merge on that one yet. 😢
