### ISSUE TITLE
[Hypersonic] ...

### ISSUE THREAD

**Issue by pierrerognion** [raycast/extensions#4754]
### Extension

https://www.raycast.com/reboot/hypersonic

### Description

RangeError: Invalid time value

vS:onboarding.tsx:21:6
MK:index.js:64:16058
rR:index.js:58:73116
    at EK

### Steps To Reproduce

1. Try to complete the onboarding process on a French Mac.

### Current Behaviour

Impossible to launch the app.

**Comment by tonimasc** [comment]
Hey Pierre i'm smashing some bugs on Hypersonic, and tried to recreate yours changing my mac config to French keyboard and zone, all works fine on my machine i'm unable to replicate your error 😅. Do you have any other clues?
