### ISSUE TITLE
[Raycast Wallpaper] Only updates 1 desktop?

### ISSUE THREAD

**Issue by rocnoa** [raycast/extensions#4757]
### Extension

https://www.raycast.com/koinzhang/raycast-wallpaper

### Description

Raycast only updates the active desktop, is this deliberate? Is there a plan to update all desktops or should I put in a feature request?

**Comment by koinzhang** [comment]
Hi @rocnoa This extension updates wallpapers via Applescript, so only visible desktops are supported (if your current desktop is a full-screen application, the desktop wallpaper will not be updated). The extension is supported to update the desktop wallpaper of the extended monitor, but also to ensure that the desktop is visible.
I can't find a better solution for now, sorry; if you have a good idea, feel free to reopen this Issue.

@raycastbot close this issue

**Comment by Tazintosh** [comment]
Maybe something to inspire or use with https://github.com/georgesofianosgr/wally ?

**Comment by Tazintosh** [comment]
Not AppleScript but:
```
for screen in NSScreen.screens {
    try! NSWorkspace.shared.setDesktopImageURL(url, for: screen, options: [:])
}
```
in https://apple.stackexchange.com/questions/433794/seamlessly-change-all-desktop-spaces-wallpaper-on-mac-without-killall-dock
