### ISSUE TITLE
[GitHub] hide specific pull requests

### ISSUE THREAD

**Issue by kandros** [raycast/extensions#4759]
### Extension

https://www.raycast.com/raycast/github

### Description

I have some pull requests that required months to be merged (ongoing migrations or deprecation removal waiting for a LTS to expire) that I don't want to show
Some are part or repositories I don't control (OSS) so filtering by label etc is not gonna work.

A local blacklist would be enough (if it was on a file easily accessible would be even better, to sync across devices)

**Comment by thomaslombart** [comment]
On which commands would you want to hide specific PRs? Note that `My Pull Requests` only include PRs that have been updated in the last two weeks. If there hasn't been any activity on the PRs you mentioned, they shouldn't show up.

**Comment by kandros** [comment]
I'm not able to see the PR I had a problem with, but It hasn't changed from what I can see, maybe some integrations triggered a a check or something. WIll close for now
