### ISSUE TITLE
[Color Picker] ...

### ISSUE THREAD

**Issue by BigBenITA** [raycast/extensions#4765]
### Extension

https://www.raycast.com/thomas/color-picker

### Description

The extension is AMAZING.
Only one little thing, is it possible to add a flag to copy or not the # at the beginning of the HEX?
for example, Indesign already put the # so I have to manually delete it otherwise it didn't recognize the code.

### Who will benefit from this feature?

Every Adobe users.

**Comment by thomaspaulmann** [comment]
@BigBenITA that could be another color format. We have already a few in the preferences. Do you want to add it yourself? It's relatively straight forward to do.

**Comment by BigBenITA** [comment]
@thomaspaulmann ok yes of course tnx. Maybe another format without the # is the easiest way, since adobe ask the hex. I'm not a superexpert coding man, but i'd like to try.

**Comment by thomaspaulmann** [comment]
@BigBenITA did you make any progress on it?

**Comment by BigBenITA** [comment]
@thomaspaulmann nope, i'm not a coding expert at all so i dropped it.

**Comment by thomaspaulmann** [comment]
I'll take a look.
