### ISSUE TITLE
[Word Search] Add preference to make copying the correctly-spelled word to the default action (instead of pasting)

### ISSUE THREAD

**Issue by chriscalo** [raycast/extensions#4766]
### Extension

https://www.raycast.com/rishabswift/word-search

### Description

Today, the default action in the spelling command is to paste the correctly-spelled word into the active application. I almost always want to copy it instead, but that is a secondary action, so I have to remember to press **Cmd K**, **Down Arrow**, **Enter**. Unfortunately, there's seemingly no option or preference for changing this.

### Who will benefit from this feature?

Everyone who wants to copy the correctly-spelled word.

**Comment by RishabSwift** [comment]
@chriscalo You're able to quickly copy the word instead of pasting it by hitting `Command + Return`. So you don't have to do the steps you mentioned since this is just as fast as hitting "Return" 😉  

<img width="738" alt="SCR-20230213-gwi-2" src="https://user-images.githubusercontent.com/15897093/218525286-10a62335-a646-4ebf-bab6-da4f72dcb1ae.png">

**Comment by chriscalo** [comment]
Thanks for pointing this out. I was already aware of this option, and I know memorizing and using `Cmd Enter` is less physical effort, but I'm not sure it's going to stick in my brain. Because it's also the cognitive effort I'm trying to avoid, not just the physical. It would be better if I didn't have to remember for this one command to `Cmd Enter` where everywhere else I can just mash the `Enter` key. You obviously don't have to follow what I'm recommending, but being able to make Copy the default action feels like the ideal experience for those who would like to make Paste, the possibly destructive action, harder to do.

**Comment by RishabSwift** [comment]
Hey, 

Just to let you know that this feature is now live so you can change the default behaviour by going to the extension preferences.

**Comment by chriscalo** [comment]
Works perfectly, thank you so much, @RishabSwift 🙏🏼

![Screenshot 2023-03-01 at 20 50 51](https://user-images.githubusercontent.com/867717/222310155-04dd7536-eb6c-419b-96f2-9197edb826c3.png)
