### ISSUE TITLE
[Orion] Open tabs only search

### ISSUE THREAD

**Issue by heliostatic** [raycast/extensions#4770]
### Extension

https://www.raycast.com/plonq/orion

### Description

Today, the history search works very well, but there's no way to scope it to only open tabs. A way to quickly search and switch tabs would be amazing.

### Who will benefit from this feature?

Orion users with lots of tabs open

**Comment by heliostatic** [comment]
@Plonq I was curious how the Arc extension works, and it looks like they use AppleScript to get the list of tabs: https://github.com/raycast/extensions/blob/main/extensions/arc/src/arc.ts#L6-L44

**Comment by Plonq** [comment]
I'm working on this
