### ISSUE TITLE
[Elgato Key Light] Add support for multiple lights

### ISSUE THREAD

**Issue by omarshahine** [raycast/extensions#4771]
### Extension

https://www.raycast.com/thomas/elgato-key-light

### Description

I have two Elgato KeyLights, it would be awesome to have this control a "pair" as I have configured in the Elgato app.

### Who will benefit from this feature?

Anyone with a pair of lights

**Comment by thomaspaulmann** [comment]
This popped up before and would be indeed nice. Want to help by contributing? Happy to steer you in the right direction.

**Comment by omarshahine** [comment]
I actually spent a but of time and am kind of stuck.

bonjour.find can enumerate more than one light. 
bonjour.fineOne just gets one.

The issue is that I can't quite figure out how to store the resulting lights in an array and then return by resolving the promise without doing so too early.

also I found this other NPM package that might help but it doesn't seem to work with me:

https://github.com/NickParks/elgato-light-api

**Comment by omarshahine** [comment]
@thomaspaulmann I have a working version now. To make it work I added a pref asking the end user how many lights they have. That is needed to get this to work but I am sure that it could be improved to remove this need for a preference. I'll submit a PR.
