### ISSUE TITLE
[Asana] ...

### ISSUE THREAD

**Issue by rohitchouhan8** [raycast/extensions#4774]
### Extension

https://www.raycast.com/raycast/asana

### Description

Creating a task is great, but I wish I could see which task I just created so I can link it in a doc. The tasks I create aren't always assigned to me, so `My Tasks` aren't useful here.

**Comment by thomaslombart** [comment]
When you create a task, a success toast appears on Raycast's window's bottom-left edge. There you have two actions:
- `Open Task` which will open the Asana task in Raycast
- `Copy Task URL`, which will copy the URL of the newly created task.

Isn't `Copy Task URL` what you're looking for?
