### ISSUE TITLE
[iTranslate] Add action to paste the translation

### ISSUE THREAD

**Issue by HerrNiklasRaab** [raycast/extensions#4776]
### Extension

https://www.raycast.com/JinShi/itranslate

### Description

Very often you have a the workflow, that you are writing something in a foreign language, then you kind of need that one word, that you forgot. It would be so amazing if I could then
1.  just write the word in my native languag, 
2. select it 
3. translate it using your extension, 
4. but now instead of hitting ↩️  and copying it. Hit CMD + Enter to paste it into the application.

Would be so awesome to see this! I would also recommend to use the CMD + Enter shortcut for this and choose a different one for "Select target language....". Because the clipboard history uses the same shortcut for the exact same thing.

**Comment by 404J** [comment]
@HerrNiklasRaab Sorry for the long time no reply. I updated it so you can try it
