### ISSUE TITLE
[iTranslate] Open iTranslate Preferences opens translate command instead of the extension where the settings are

### ISSUE THREAD

**Issue by HerrNiklasRaab** [raycast/extensions#4778]
### Extension

https://www.raycast.com/JinShi/itranslate

### Description

When hitting this command:
<img width="778" alt="CleanShot 2023-02-13 at 21 45 05@2x" src="https://user-images.githubusercontent.com/28401593/218570731-4199f1c4-523f-429d-a5ff-8c9788af8caa.png">

I land here:
<img width="761" alt="CleanShot 2023-02-13 at 21 46 01@2x" src="https://user-images.githubusercontent.com/28401593/218571076-c143b841-9139-40c7-b81f-1f7a2f095f08.png">

But I would expect to land here:
<img width="1097" alt="CleanShot 2023-02-13 at 21 47 19@2x" src="https://user-images.githubusercontent.com/28401593/218571283-86d04124-2e72-499f-8661-62ac0612dd87.png">

**Comment by 404J** [comment]
@HerrNiklasRaab please update it.
