### ISSUE TITLE
[Host Switch] ...

### ISSUE THREAD

**Issue by jasonshanks** [raycast/extensions#4780]
### Extension

https://www.raycast.com/ewgenius/host-switch

### Description

This is simply amazing, thank you so much! I will use the heck out of this.

I wonder if there could be an option (say holding down COMMAND or OPTION when selecting host) to have it open in a new tab instead of replacing existing. for those side by side comparisons?

Bonus on Arc if it opened in Split Window. wow.

### Who will benefit from this feature?

Anyone comparing pages during development.

**Comment by ewgenius** [comment]
@jasonshanks thanks for suggestion sounds good to me! 👍 
Let me check if that is feasible

**Comment by ewgenius** [comment]
@jasonshanks I've added new action to open selected host in new tab

> Bonus on Arc if it opened in Split Window.

Unfortunately I didn't find documented Arc's AppleScript api for opening tab in split view (most likely there is no one yet)
