### ISSUE TITLE
[Open Path] Show error if path could not be found instead of opening google

### ISSUE THREAD

**Issue by HerrNiklasRaab** [raycast/extensions#4784]
### Extension

https://www.raycast.com/koinzhang/open-path

### Description

https://www.loom.com/share/cfab889f593e4faf9ee0b378256b37a3

**Comment by koinzhang** [comment]
Hi @HerrNiklasRaab. In fact, I don't think it's a mistake, Open Path is designed to be used not only to open file paths, but also for quick searches, which I often use (select a word, press Open Path and search the content in the browser).
I have no way to determine if the user wants to open the file path or search, so the internal logic of the extension is to first follow the file path and open the file if it exists, and then perform a search if the file does not exist. I hope you can understand this implementation scheme.

Another tip, Open Path also supports the following inputs, which you can check and try:

- Directory: /Users/Username/Desktop, `~/Desktop`
- URL: `https://www.raycast.com`, `www.raycast.com`, `raycast.com`
- URL Scheme: `raycast://confetti`
- IP address: `76.76.21.21`
- mailto: `mailto:hello@raycast.com`
- Email address: `hello@raycast.com`

**Comment by koinzhang** [comment]
Hi @HerrNiklasRaab. Maybe I can make improvements, but probably won't be updated recently (I've been busy lately)

**Comment by HerrNiklasRaab** [comment]
No worries, just giving feedback and loving it so far!

**Comment by koinzhang** [comment]
Hi @HerrNiklasRaab. I submitted a PR #5660 to update the extension with the following change points"

- Optimize the judgment logic of opening path (Now path strings starting with "file:///", "~/" and "Users/username" will no longer Perform search operations)
- **Show In Finder** and **Open File** items in the settings page now work properly

If you still have problems, feel free to reopen this Issue.

@raycastbot close this issue
