### ISSUE TITLE
Overwork Form.Checkbox

### ISSUE THREAD

**Issue by Rincewind34** [raycast/extensions#4791]
### Description

At the moment, I see two problems with this checkbox
A) The text is going to the right. I know your API provides the possibilities to add the text to the left (I think that would be the label) but that is very counter intuitive with the checkbox itself as in all other applications, the text next to a checkbox goes to the right. And it just doesn't make any sense to put the same text on both sides or a semantically same text. You also don't want to put anything wordy on the right, as that is what the "info" attribute is for.
B) The checkbox looks ridiculously small to fit to the font size.
<img width="608" alt="Screenshot 2023-02-10 at 17 14 20" src="https://user-images.githubusercontent.com/13020648/218793546-093d7a12-2f07-417e-957d-877e3e87936b.png">

I suggest adding the possibility to add a new full sized component as a toggle switch. It fixes both problems. Text normally goes to the left (look at any menu in the iOS settings) and you don't have to fit the size against the "label" font size but you can fit it against the font size of the Form.Label, Form.Dropdown or the placeholder text in Form.TextInput.
<img width="329" alt="Screenshot 2023-02-10 at 17 18 24" src="https://user-images.githubusercontent.com/13020648/218793516-db2463ba-6477-4edc-8a6e-ca3999269435.png">

### Who will benefit from this feature?

Everyone working with booleans in forms. I suggest marking the checkbox as deprecated instead of just straight replacing the underlying rendering as the new component wouldn't be a "checkbox" and it would lake the right aligned text (and at the moment everyone is probably using it and needs to move it to the left aligned text).

Marking it as deprecated ensures everyone stays inline with the global styling guidelines. Porting the code is very easy and probably won't introduce any bugs (provided no one makes a typo)

**Comment by mathieudutour** [comment]
As with every other Form item, the `title` goes on the left indeed.

We found that this format works well as part of our Forms. 

You could maybe have a look at some of our preference screens to find some inspiration:
<img width="457" alt="Screenshot 2023-02-15 at 09 15 09" src="https://user-images.githubusercontent.com/3254314/218970933-10f7e6c5-e274-479a-8772-950437ee859c.png">
<img width="439" alt="Screenshot 2023-02-15 at 09 15 16" src="https://user-images.githubusercontent.com/3254314/218970944-58ee94cc-b551-445d-91cd-8f3e27aef8b7.png">

It is very unlikely that we will deprecate it.
