### ISSUE TITLE
monday.com API time outs

### ISSUE THREAD

**Issue by cdmarshall** [raycast/extensions#4792]
### Extension

https://www.raycast.com/freak4pc/monday-com

### Description

The extension is currently inoperable and every request to the monday.com API is timing out. Regenerating API keys didn't solve the issue, I'm wondering if there was a change to Monday's APIs that has broken the integration.

I know this extension isn't widely used, but I hope that @freak4pc has some time to look into this because I find this extension quite useful.

![image](https://user-images.githubusercontent.com/30123530/218796212-ad8fe4cc-2693-42ad-93c3-1088d9156590.png)

### Steps To Reproduce

1. Configure extension with valid API token
2. Run "Recent Boards" command 

### Current Behaviour

Extension fails to load boards, teams, or groups.

### Expected Behaviour

Extension should be able to communicate with the monday.com API and fetch responses.

**Comment by freak4pc** [comment]
Hey @cdmarshall 
Can you share if this is still happening to you? Given this looks like a timeout it might've been an intermittent issue on our end or locally 

Thanks!

**Comment by cdmarshall** [comment]
@freak4pc I appreciate the response! I actually recently discovered the root cause. My company's VPN was causing the connection to timeout.
