### ISSUE TITLE
Moving Starred Notes to Top [Obsidian] ...

### ISSUE THREAD

**Issue by ReeceMMI** [raycast/extensions#4796]
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

It would be nice if starred notes were moved to the top of the list when using the "Search Note" command. Yes there is a command called "starred notes" which shows all of them at once but I personally don't really like this command because it is so limiting since you don't have access to the rest of the notes within it.

### Who will benefit from this feature?

Anyone who likes to star their most used notes. With that said, it would be more like pinning the notes rather than just starring them, which tends to prove quite useful when you want access to all your notes at once but want quick access to the ones you use a lot.

**Comment by marcjulianschwarz** [comment]
Sounds like a great idea, will add it to the roadmap.
