### ISSUE TITLE
[Linear] Spurious error related to missing milestone - Linear issue IS created despite error

### ISSUE THREAD

**Issue by coopr** [raycast/extensions#4799]
### Extension

https://www.raycast.com/linear/linear

### Description

When creating a new issue via the Linear extension, an error is shown - but the issue is created correctly in Linear, and the error appear spurious. 

### Steps To Reproduce

1. Invoke Raycast 
2. Type Linear
3. Select "create new issue"
4. Create the issue
5. Observe the error message at the bottom of Raycast window
6. Swich to Linear app - observe that the issue was created, despite the error message

### Current Behaviour

Error is shown - but there is no error. 

### Expected Behaviour

No error is shown in Raycast.

**Comment by coopr** [comment]
https://user-images.githubusercontent.com/94904/218863015-b9104303-9576-409d-abe0-037bf7fc7a6a.mp4

**Comment by thomaspaulmann** [comment]
Looks like there were some breaking API changes ([#267](https://github.com/linear/linear/issues/267)) which we need to fix.

**Comment by thomaslombart** [comment]
This should have been fixed with the upgrade of the SDK: https://github.com/raycast/extensions/pull/4843. @coopr are you still seeing the error?

**Comment by coopr** [comment]
No @thomaslombart, I'm not seeing the error anymore. Resolved! I'll close this issue - feel free to re-open if I did that wrong, and thanks very much!
