### ISSUE TITLE
[API Feature Request] DatePickerAction

### ISSUE THREAD

**Issue by HenriChabrand** [raycast/extensions#480]
**Describe the feature and the current behavior/state.**

Add the DatePickerAction that is available in the native `My Reminder` command.
Allowing the user to set a date (and time) directly from the action panel.

<img width="886" alt="Screenshot 2021-12-05 at 14 47 30" src="https://user-images.githubusercontent.com/18643714/144749246-51649a7b-d29d-4deb-a25a-c4edb6fa8a9b.png">

**Will this change the current api? How?**

Add a new action.

**Who will benefit with this feature?**

Any developers that want to create time-based action without having to use a Form > DatePicker for that.

In my case, for the Notion extension being able to quickly set/update a date property.

<img width="886" alt="Screenshot 2021-12-05 at 14 54 35" src="https://user-images.githubusercontent.com/18643714/144749390-f96f76bd-aa6e-4382-b104-43b313bc3f78.png">

**Any Other info.**

**Comment by thomaspaulmann** [comment]
That's a cool idea and something we thought about for a while. It can be handy for calendar or todo lists to pick some date in the future.

**Comment by mathieudutour** [comment]
It's now available in 1.46.0!
