### ISSUE TITLE
[Apple Notes] New note command causes crashing

### ISSUE THREAD

**Issue by wyniemko** [raycast/extensions#4801]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

Error: Command failed with exit code 1: osascript -e 
    tell application "Notes" to activate
    tell application "System Events" to keystroke "0" using command down
    tell application "System Events" to tell process "Notes" to ¬
    click menu item 1 of menu 1 of ¬
    menu bar item 3 of menu bar 1
  
82:114: execution error: System Events got an error: osascript is not allowed to send keystrokes. (1002)

    tell application "Notes" to activate
    tell application "System Events" to keystroke "0" using command down
    tell application "System Events" to tell process "Notes" to ¬
    click menu item 1 of menu 1 of ¬

### Steps To Reproduce

1. Search "New Note"
2. Notes opens, but no new note is created
3. Enter raycast to find: _Something went wrong_

<img width="741" alt="Screenshot 2023-02-14 at 8 33 49 PM" src="https://user-images.githubusercontent.com/77697805/218904669-65ba3a6e-51dd-45d0-bd4c-c64a387236f4.png">

### Current Behaviour

No new note is created, app crashes.

### Expected Behaviour

Opens a new note after prompt

**Comment by mathieudutour** [comment]
@StevenRCE0 can you have a look? Looks like [your recent PR](https://github.com/raycast/extensions/pull/4501) broke the command for some people

**Comment by StevenRCE0** [comment]
Please grant Raycast Accessibility permission beforehand, under "System Settings - Accessibility". I'm adding error handling to it.

**Comment by wyniemko** [comment]
> Please grant Raycast Accessibility permission beforehand, under "System Settings - Privacy & Security- Accessibility". I'm adding error handling to it.

Once I enabled accessibility access, I was able to create a new note through raycast.

Thanks!

**Comment by StevenRCE0** [comment]
The issue could be safely closed 😉
