### ISSUE TITLE
[Spotify Player] A song cannot be played

### ISSUE THREAD

**Issue by yauhen-info** [raycast/extensions#4807]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

When using a freshly installed Spotify, no song can be played

### Steps To Reproduce

1. MacOS
2. Default Config
3. Play a playlist or a song under the Search option, e.g. typing 'Moby'
4. "An identifier can't go after..."
<img width="763" alt="Screenshot 2023-02-15 at 11 37 16" src="https://user-images.githubusercontent.com/702415/219004332-57942187-e98d-4814-a97f-1d802a663f5b.png">

### Current Behaviour

No song can be played from Raycast.

### Expected Behaviour

A song can be played from Raycast directly.

**Comment by doichev-kostia** [comment]
Same with radio

<img width="357" alt="Screenshot 2023-02-19 at 15 40 28" src="https://user-images.githubusercontent.com/72884674/219955265-22fad8ab-5724-4a12-b718-115fc85f12dc.png">
