### ISSUE TITLE
[Linear] Views such as Active Cycle do not support paginated results

### ISSUE THREAD

**Issue by joel-u410** [raycast/extensions#4814]
### Extension

https://www.raycast.com/linear/linear

### Description

The Linear GraphQL API [paginates](https://developers.linear.app/docs/graphql/working-with-the-graphql-api/pagination) results by 50 issues at a time by default. As far as I can tell, the [API client in the Linear extension](https://github.com/raycast/extensions/blob/528e717591494b099704a434c0974d4a167f6583/extensions/linear/src/api/getIssues.ts) does not support fetching paginated results at all. This results in incomplete data, for example, in the "Current Cycle" view anytime there are more than 50 issues in the cycle. This is particularly a problem in a team context, where one cycle is used by a large team, resulting in more issues -- filtering by my name to view only _my_ issues in the active cycle results in a very incomplete list, because many of the issues were never loaded into Raycast in the first place.

### Steps To Reproduce

1. Have more than 50 issues in the active cycle in Linear
2. Open the Active Cycle view in the Linear Raycast extension
3. Count the issues

### Current Behaviour

Only 50 issues are displayed

### Expected Behaviour

All issues should be displayed

**Comment by thomaspaulmann** [comment]
Hey, that is indeed a limitation of the extension right now. Our extensions API doesn't provide an easy way to implement pagination yet. It's something that we had in mind to implement at some point. Could there be any "work-around" for now to help with your problem, f.e. showing some list item that there are more issues that would then fetch them or open Linear?

**Comment by joel-u410** [comment]
Maybe an easy (though imperfect) fix could be to just increase the requested items to be more than the default --

e.g. on this line: https://github.com/raycast/extensions/blob/main/extensions/linear/src/api/getIssues.ts#L211

changing

```
      query($cycleId: String!) {
```

to

```
      query(first: 500, $cycleId: String!) {
```

**Comment by joel-u410** [comment]
I went ahead and implemented pagination for this -- it doesn't change anything about the extensions API, but instead makes multiple requests to the Linear GraphQL API until all pages have been retrieved. I wrote it in a generic way so you could easily use it for any other Linear GraphQL queries too if you'd like.

The code is in https://github.com/raycast/extensions/pull/4856. Would be great to merge this into the official extension! (Otherwise, if you don't want to merge it, is there a way I can install my fork locally instead of the official one?)
