### ISSUE TITLE
Shortcut - Add support for "List Milestones"

### ISSUE THREAD

**Issue by jessekinzer** [raycast/extensions#4815]
### Extension

https://www.raycast.com/Yukai/shortcut

### Description

Like the show epics command. A show milestones command would be very helpful since Shortcut has a hierarchy starting with milestones. Just like how the "show epics" command allows you to enter an epic and view stories the "show milestone" feature should show all milestones and then allow you to enter a milestone and view epics inside it. 

Shortcut API - list milestones:
https://developer.shortcut.com/api/rest/v3#List-Milestones

**Comment by Yukaii** [comment]
Great idea, I'll take this when I have time 👍
