### ISSUE TITLE
[Google Chrome] Activates wrong tab or just errors out

### ISSUE THREAD

**Issue by michaelwexler** [raycast/extensions#4820]
### Extension

https://www.raycast.com/Codely/google-chrome

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    tell application "Google Chrome"
      activate
      set index of window (6 as number) to (6 as number)
      set active tab index of window (6 as number) to (14 as number)
    end tell
    return true
  
116:178: execution error: Google Chrome got an error: Invalid tab index entered. (9)

    tell application "Google Chrome"
      activate
      set index of window (6 as number) to (6 as number)
      set active tab index of window (6 as number) to (14 as number)

```

### Steps To Reproduce

In MacOS 12.6.1 on M1 macbook pro, using Raycast 1.47.3 and Chrome Version 109.0.5414.119 (Official Build) (arm64), added hotkey alias "t".  

So, t space to get to tab search, then either "Mail" for Yahoo Mail, or "Reachout" for a google doc with that name.  
The list does correctly show the tabs (2 mail tabs, 3 for the Reachout doc) but when I activate one, I either get some other tab, or the error as shown above.

### Current Behaviour

Either no tab is activated, the wrong tab is activated, or an error and request to "command K" to report bug from Raycast.

### Expected Behaviour

Expected correct tab to come forward and Chrome to take focus.

**Comment by michaelwexler** [comment]
See also https://github.com/raycast/extensions/issues/4225

**Comment by michaelwexler** [comment]
Can someone explain what the setActiveTab function actually does? Assume windowsIndex is a 3, and tabIndex is a 2,  it appears to just set index of window 3 to 3, and set active tab index of window 3 to tab 2.  The first line seems not necessary (perhaps it was meant to be "... to 1" which would have brought the window to the front, I think?).

**Comment by UncleBill** [comment]
> I still think we need to use the ID, not the Index.

Agree. I would try refactoring with using id.

**Comment by qmg-krewera** [comment]
I'm getting the same exception pretty often
`Error: Command failed with exit code 1: osascript -e 
    tell application "Google Chrome"
      activate
      set index of window (2 as number) to (2 as number)
      set active tab index of window (2 as number) to (4 as number)
    end tell
    return true
  
116:177: execution error: Google Chrome got an error: Invalid tab index entered. (9)

    tell application "Google Chrome"
      activate
      set index of window (2 as number) to (2 as number)
      set active tab index of window (2 as number) to (4 as number)`

That breaks potentially excellent feature. Do you guys have any update on ETA of the fix?
