### ISSUE TITLE
[Toothpick] Device Support Form

### ISSUE THREAD

**Issue by mindprint** [raycast/extensions#4827]
### Extension

https://www.raycast.com/briankosw/toothpick

### Description

<b>Device brand and model</b>
Replace this line with your device's brand name and model

<b>Device data</b>
{"Jabra Elite 85t":{"device_address":"30:50:75:C3:48:8E","device_batteryLevelMain":"100%","device_firmwareVersion":"2.0.0","device_minorType":"Headset","device_productID":"0x24CD","device_services":"0x800019 < HFP AVRCP A2DP ACL >","device_vendorID":"0x0067","device_connected":"true"}}

### Who will benefit from this feature?

All Jabra Elite 85t users :)

### Anything else?

There are a few more popular Jabra earbuds available. If you'd like help with icons I am happy to help.
Thank you.

**Comment by VladCuciureanu** [comment]
Hey! Your device will be mapped in the next release with a custom icon, with possible added functionality in the future. Thanks for your submission.
