### ISSUE TITLE
[Things] ...

### ISSUE THREAD

**Issue by acifre** [raycast/extensions#4839]
### Extension

https://www.raycast.com/loris/things

#### Error:
```

```

### Steps To Reproduce

Since updating to Ventura 13.3. Show today in menu bar is now broken.

**Comment by loris** [comment]
Hi @acifre. Thank you for reporting the issue. Can you confirme you still have the issue?
I have no issue with the menu bar, both running ventura 13.3 or 13.4

**Comment by acifre** [comment]
Issue is fixed, thank you!

Best,
Anthony

From: Loris Guignard ***@***.***>
Date: Friday, April 7, 2023 at 10:09 AM
To: raycast/extensions ***@***.***>
Cc: Anthony Cifre ***@***.***>, Mention ***@***.***>
Subject: Re: [raycast/extensions] [Things] ... (Issue #4839)

Hi @acifre<https://github.com/acifre>. Thank you for reporting the issue. Can you confirme you still have the issue?
I have no issue with the menu bar, both running ventura 13.3 or 13.4

**Comment by loris** [comment]
@raycastbot close this issue
