### ISSUE TITLE
[change-case] not working correctly with Latin characters

### ISSUE THREAD

**Issue by isaactopo** [raycast/extensions#4841]
### Extension

https://www.raycast.com/es183923/change-case

### Description

When you use the extension with Latin characters like `ó` or `'` they do not appear in the extension resulting in words with missing characters. I see that also commas`,` if they come after a Latin character, are not included.

**Comment by es183923** [comment]
Yes, that's because the lib that is used doesn't support these characters. Feel free to PR a fix using a different lib that supports accents and other characters.

**Comment by isaactopo** [comment]
I would love to, unfortunately, I am not a JS/TS developer.

**Comment by romansj** [comment]
Merged in https://github.com/blakeembrey/change-case/pull/296

Need to update change-case version once it comes out.

**Comment by erics118** [comment]
Related issues: #7420 #7452

**Comment by erics118** [comment]
@raycastbot reopen this issue
