### ISSUE TITLE
[Extension Name] ChatGPT3 Prompt

### ISSUE THREAD

**Issue by slavakurilyak** [raycast/extensions#4844]
### Extension

https://www.raycast.com/denizyoldas/chatgpt3-prompt

### Description

It would be great to use a more regularly updated prompt list, such as [awesome-chatgpt-prompts](https://github.com/f/awesome-chatgpt-prompts/blob/main/prompts.csv)

**Comment by pernielsentikaer** [comment]
This is not implemented - you might need to run the command `Check For Extensions Updates`
