### ISSUE TITLE
[Safari] Search Tabs: show dropdown with tab group list

### ISSUE THREAD

**Issue by eddyw** [raycast/extensions#4847]
### Extension

https://www.raycast.com/loris/safari

### Description

In "Search Tabs", it'd be great if there was a dropdown displaying the list of "Tab Groups"
Raw idea:

1. "Tab Groups" dropdown is displayed only if there are any besides the default
2. Dropdown displays the current "Tab Group" whose tabs are being shown

### Who will benefit from this feature?

Rather than having multiple Safari windows, some users use "Tab Groups" to organize tabs. The "Search Tabs" feature works well with it since it displays tabs of current active tab group.

However, if you have a big/moderate number of "Tab Groups", switching between them is tedious (and you can only go next/prev with Safari key-shortcuts). I think users could benefit from having the option to switch between "Tab Groups" in the same interface used for "Search Tabs" in Raycast to improve productivity. The usually workflow now looks like this:

1. Use mouse to open sidebar (or use key shortcut)
2. Look for the tab group name, click it (or use up/down keys + enter)
3. Closing the sidebar (or use key shortcut)
4. Trigger "Search Tabs" (key shortcut)

**Comment by scottaw66** [comment]
Supporting tab groups seems like a no-brainer, I'm surprised this was closed without comment.
