### ISSUE TITLE
[Safari] Adding Item to Reading List brings up Safari Window 

### ISSUE THREAD

**Issue by mharmel** [raycast/extensions#4849]
### Extension

https://www.raycast.com/loris/safari

### Description

When I add a URL to my Safari reading list, I expected that after hitting Cmd+Enter to add the new item, the Raycast window would just close – done. 
It does not close for me. And additionally Safari comes up when it was minimized or hidden before. It switches the sidebar on to display the reading list.
If this is intended behaviour, I'd like to suggest an option to turn this off :)

### Steps To Reproduce

- minimize or hide Safari window
- open some other application
- call Raycast and use the Safari Extension to add a new item to the reading list

### Current Behaviour

Safari window comes up, after adding the new item to the reading list through raycast.

### Expected Behaviour

The Raycast window closes and I get a little confirmation that the new item was added (like in the quick capture function of the Logseq Raycast extension). Safari does nothing.

**Comment by thomaspaulmann** [comment]
Unfortunately that's how Safari interprets the AppleScript. There isn't much we can do here.
