### ISSUE TITLE
[Extension Bug] Authy OTPs are too short

### ISSUE THREAD

**Issue by gdsmith** [raycast/extensions#485]
# Extension – [Authy/Search Token](https://github.com/raycast/extensions/tree/main/extensions/authy)

Author: @guga4ka

## Description

I sometimes get 4/5 character OTPs like this:

![image](https://user-images.githubusercontent.com/908695/144814288-3a7df766-8e7b-4284-a472-d081fc051543.png)
![image](https://user-images.githubusercontent.com/908695/144814986-a8ab0be8-2321-4331-9f3f-49774b2b1453.png)

## Steps To Reproduce

1. Open the extension

## The current behavior

OTP is 4/5 chars

## The expected behavior

OTP is 6 chars

### Raycast version
Version: 1.26.1

**Comment by guga4ka** [comment]
Doh, seems like I forgot to add padding, as a workaround just for now, add 0 for missing count of numbers in front of the token. I will fix it ASAP

**Comment by guga4ka** [comment]
@gdsmith I've fixed this issue, could you pls confirm that it works for you?

**Comment by gdsmith** [comment]
Works 100% – thanks for the fix 🙇
