### ISSUE TITLE
[Visual Studio Code Recent Projects] Does this support vscode insiders?

### ISSUE THREAD

**Issue by alok** [raycast/extensions#4858]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

I got an error when I tried to run this:

```
Error: ENOENT: no such file or directory, open '~/Library/Application Support/Code/User/globalStorage/state.vscdb'
```

**Comment by pernielsentikaer** [comment]
Hi @alok 

It should be possible from within preferences to set which build you're using.

![Raycast-J3jbDssQ@2x](https://user-images.githubusercontent.com/38033107/220090645-9cf64bdf-a1e9-4fed-b7f1-358374bd0766.png)

**Comment by thomaspaulmann** [comment]
We maybe can detect the error and show an hint for the preferences?

**Comment by alok** [comment]
thanks, fixed
