### ISSUE TITLE
[Brave] Add support for New Private Tab (aka New Incognito Tab)

### ISSUE THREAD

**Issue by rkayman** [raycast/extensions#4865]
### Extension

https://www.raycast.com/ron-myers/brave

### Description

Thanks for making this extension.  Already has support for 'New Tab'.  Please support 'New Private Tab' (also known as Incognito Tab).

### Who will benefit from this feature?

Developers and those using Brave for its better stance on Privacy over Chrome.

**Comment by ron-myers** [comment]
Sure, I agree this has value.

I will have a look to see if we have access to APIs to be able to add a private tab.
