### ISSUE TITLE
[Bitwarden Vault] launch url?

### ISSUE THREAD

**Issue by zeltak** [raycast/extensions#4873]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Hi and thank you for this epic extension

I previously was using 1passowrd and in the recast extension there is an option to launch the associated url in the browser. is that possible to add this to the Bitwarden extension?

best regards

Z

### Who will benefit from this feature?

everyone

**Comment by jomifepe** [comment]
Hey, thanks for the suggestion, yeah this is something that can be added. I will add this to my personal backlog for this extension, to implement when I have the time. In the meanwhile, anyone can feel free to pick this up, just comment on this issue to let others know you're working on it.

**Comment by jomifepe** [comment]
Added a new "Open in Browser" action to the vault items, try it out 🎉

**Comment by zeltak** [comment]
amazing!!

thx so much @jomifepe !!!

Z

**Comment by andreaselia** [comment]
@raycastbot close this issue
