### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by flawnn** [raycast/extensions#4878]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

If a song has been already liked, and you like it again, the extension removes the liked status and reapplies it. This causes already liked songs to come up again on the top list of your liked songs. It  obviously also as well resets the date at which you can see when you liked a song,

### Steps To Reproduce

1. Like an already liked song on Spotify and watch how it hops on the top of your liked songs (as well as that the added date gets resetted)

**Comment by codedbyjordan** [comment]
I could pick this up!

**Comment by andreaselia** [comment]
This has been fixed in v2 of this extension, see PR #5602 to follow along.
