### ISSUE TITLE
[Todoist] "Today" uses "Upcoming days" settings which should not

### ISSUE THREAD

**Issue by kud** [raycast/extensions#4882]
### Extension

https://www.raycast.com/thomaslombart/todoist

### Description

![screenshot-2023-02-20-09-30-13](https://user-images.githubusercontent.com/655838/220066745-6f21bcd1-0153-4c93-94f4-54d73a1358a8.png)

This week: I've got 4 tasks for the week but only 1 for today. Even if I use today, it shows me 4 tasks. It should not.

### Steps To Reproduce

- Create multiple tasks for all the week.
- Set 7 as "upcoming days"

### Current Behaviour

- You wil have all the 7-days tasks

### Expected Behaviour

- You should only have today tasks.

**Comment by thomaslombart** [comment]
Do you intend to work on this one?

**Comment by pdussart** [comment]
for completeness: the workaround is to set the "number of upcoming days" to 1
