### ISSUE TITLE
[Spotify Controls] Commands stop working 

### ISSUE THREAD

**Issue by natashaw** [raycast/extensions#4884]
### Extension

https://www.raycast.com/thomas/spotify-controls

### Description

The usual commands simply stop controlling Spotify completely.

#### Platform:
OS: macOS Monterey 12.5.1 (21G83)
Chip: M1

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    tell application "Spotify"
      if not application "Spotify" is running then
        activate

        set _maxOpenWaitTimeInSeconds to 5
        set _openCounter to 1
        repeat until application "Spotify" is running
          delay 1
          set _openCounter to _openCounter + 1
          if _openCounter > _maxOpenWaitTimeInSeconds then exit repeat
        end repeat
      end if
      previous track
    end tell
402:416: execution error: Not authorized to send Apple events to Spotify. (-1743)

    tell application "Spotify"
      if not application "Spotify" is running then
        activate

```

**Comment by thomaspaulmann** [comment]
@natashaw looks like Raycast lost permission to run AppleScript. Could you restart the app and check your system security settings? Closing for now as this isn't an extension issue but a system issue. Feel free to re-open if the issue persists.
