### ISSUE TITLE
[Extension Bug] Can the gitlab plugin add v3 compatibility and allow switching api versions

### ISSUE THREAD

**Issue by HuangJunjia** [raycast/extensions#489]
# Extension – [Gitlab](https://github.com/raycast/extensions/tree/main/extensions/gitlab)

Author: @tonka3000 

## Description

My company is using v8 version of gitlab instance and api is using v3 version, is it possible to consider compatibility?

## Steps To Reproduce

1. Set instance url and token
2. Search project

## The current behavior

Prompt error 404

## The expected behavior

Is it possible to add v3 compatibility while allowing switching api versions

### Raycast version
Version: 

- Raycast: 1.26.1
- Extension: 1.1.0

**Comment by tonka3000** [comment]
Hi @HuangJunjia ,

I have no access to a GitLab 8.0 version. So testing it would be really hard. Since GitLab 8.0 is from 2015(!) I would not add support for v8.0 myself.

Maybe you wanna add the support for that yourself via a PR?

Greetings
Michael

**Comment by HuangJunjia** [comment]
> Hi @HuangJunjia ,
> 
> I have no access to a GitLab 8.0 version. So testing it would be really hard. Since GitLab 8.0 is from 2015(!) I would not add support for v8.0 myself.
> 
> Maybe you wanna add the support for that yourself via a PR?
> 
> Greetings Michael

I am very sorry that my English is not very good, there is no clear expression of my thoughts.

If you don't mind, can I add support to the V8.0 version API?
