### ISSUE TITLE
[Music] Menubar component for current playing song

### ISSUE THREAD

**Issue by baaaaaapy** [raycast/extensions#4895]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

Displays the current song in the menubar like the spotify extension

### Who will benefit from this feature?

Anyone who wants to see what the current song is

### Anything else?

![Screenshot 2023-02-20 at 21 58 58](https://user-images.githubusercontent.com/82696125/220236454-aa7e2d37-ddde-49db-a46c-08930cd32b64.png)

**Comment by Rawnly** [comment]
Yep! as said in #4453 is something I'd like to introduce once I have more time to work on this :)
