### ISSUE TITLE
[Asana] Shortcut for creating Asana ticket is not loading

### ISSUE THREAD

**Issue by andreasspiegler** [raycast/extensions#4897]
### Extension

https://www.raycast.com/raycast/asana

#### Error:
<img width="862" alt="image" src="https://user-images.githubusercontent.com/7158992/220295719-57267253-f05a-4594-9c1b-24dd82b804aa.png">

```
SyntaxError: Unexpected end of JSON input

F4:CreateTaskForm.tsx:32:33
rS:create-task.js:63:3931
wr:index.js:5:2490
    at ray-navigation-stack
```

**Comment by thomaslombart** [comment]
Thanks for reporting this bug. I added it to our backlog 😊

In the meantime, don't hesitate to open a pull request for this if you feel like coding!
