### ISSUE TITLE
[Change Case] ...

### ISSUE THREAD

**Issue by lemikeone** [raycast/extensions#4905]
### Extension

https://www.raycast.com/es183923/change-case

### Description

It beaks special characters, like ":" or "ê". 

### Steps To Reproduce

Try to change the case of : "prêtes"

### Current Behaviour

Will change it to : PR TES

### Expected Behaviour

Should change it to : PRÊTES

**Comment by es183923** [comment]
see #4841

**Comment by pernielsentikaer** [comment]
Closing as duplicate of #4841
