### ISSUE TITLE
[Timezone Converter] ...

### ISSUE THREAD

**Issue by jasonshanks** [raycast/extensions#4909]
### Extension

https://www.raycast.com/joao.mainka/raycast-timezone-converter

### Description

Awesome addition to the extension library! Just a quick and easy suggestion: could the list of timezones be auto-sorted into chronological order? Maybe as a preference option since some may want a custom order but as it is you would have to pre-think that ahead of time anyway before adding them one by one.

**Comment by joaom182** [comment]
@jasonshanks that's a great idea! I'll implement it.
