### ISSUE TITLE
[API Bug] Text Form input return transformed text

### ISSUE THREAD

**Issue by pomdtr** [raycast/extensions#491]
Raycast version: 1.26.1

## Description

User-provided text from the text form input is automatically transformed. This is not always the desired behavior.

## Steps To Reproduce

![image](https://user-images.githubusercontent.com/17577332/145003282-4b60175a-a249-4e95-91a3-9d4e67ebe848.png)

## The current behavior

`->` is transformed to ➡️

## The expected behavior

`->` should not be transformed by default.

**Comment by mattisssa** [comment]
Hey, thanks for creating the issue, actually it already popped up in the issues twice 😁
We will take a look at that.

**Comment by pomdtr** [comment]
Yep, I created this issue to label it has an api bug instead of an extension bug :)
