### ISSUE TITLE
Search Apple Music

### ISSUE THREAD

**Issue by chrisensor** [raycast/extensions#4913]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

Would it be possible to add a command to search Apple Music (if Apple expose it?)

### Who will benefit from this feature?

All users

**Comment by Rawnly** [comment]
Unfortunately, there's no way to achieve that view AppleScript :/

**Comment by chrisensor** [comment]
@raycastbot close this issue

**Comment by Rawnly** [comment]
@raycastbot close this issue
