### ISSUE TITLE
[GitLab] My Reviews fails or hangs

### ISSUE THREAD

**Issue by z4f1r0v** [raycast/extensions#4916]
### Extension

https://www.raycast.com/tonka3000/gitlab

### Description

After a clean installation of the extension, I try running `My Reviews` and get either `Cannot search Reviews: FetchError: request to https://gitlab.com/api/v4/user?per_page=50&page=1 failed, reason: socket hang up` or a hanging window. In the case of the former, I am capable of successfully issuing the query and get the results as expected.

https://user-images.githubusercontent.com/8957630/220628717-edc0d402-e0eb-48c4-a8ce-c1f999770ae3.mov

### Steps To Reproduce

Execute the `My Reviews` action

### Current Behaviour

Received either `Cannot search Reviews: FetchError: request to https://gitlab.com/api/v4/user?per_page=50&page=1 failed, reason: socket hang up` or a hanging window.

### Expected Behaviour

MRs that I'm assigned as a reviewer are retrieved.

**Comment by z4f1r0v** [comment]
My gitlab url is `https://gitlab.com`. My token scope is `api` and `read_api`. I've tried all possible combinations between the two.

**Comment by tonka3000** [comment]
@pernielsentikaer raycast issue?

**Comment by pernielsentikaer** [comment]
Hi @z4f1r0v 👋 

Are you still experiencing this issue?

**Comment by z4f1r0v** [comment]
Not anymore. Closing.
