### ISSUE TITLE
[Arc] Add command for New Little Arc Window

### ISSUE THREAD

**Issue by sdalmonte** [raycast/extensions#4921]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

Adding the New Little Arc Window command to Raycast would let users open a page in Little Arc without having to switch to their main Arc window.

### Who will benefit from this feature?

all users of the Arc extension

**Comment by thomaspaulmann** [comment]
Need to see if that's possible. Want to give it a try yourself?
