### ISSUE TITLE
[Notion] Can't create page

### ISSUE THREAD

**Issue by svenmalvik** [raycast/extensions#4923]
### Extension

https://www.raycast.com/HenriChabrand/notion

### Description

When creating a page, I get the following error msg.
`Could not find database with ID: xxxxx` It's a subpage I deleted and there is no other "database" to choose from.

**Comment by christianmagill** [comment]
@svenmalvik, If you also can't search successfully, this may match an existing issue https://github.com/raycast/extensions/issues/4158

**Comment by svenmalvik** [comment]
The search works fine. I recorded a 45sec video to show the error https://www.youtube.com/watch?v=bNvpg61KVWg

**Comment by svenmalvik** [comment]
@christianmagill The search works fine. I recorded a 45sec video to show the error https://www.youtube.com/watch?v=bNvpg61KVWg
