### ISSUE TITLE
[OSS Browser] Option to change home directory

### ISSUE THREAD

**Issue by yzlnew** [raycast/extensions#4926]
### Extension

https://www.raycast.com/JinShi/oss-browser

### Description

Currently it is `$ROOT/` every time log into a bucket. But if it is a shared bucket with many users creating nested folders, it is inconvenient to navigate to my folders frequently.

### Who will benefit from this feature?

Anyone with complex folder structure.

**Comment by 404J** [comment]
@yzlnew Maybe you can add any folder to "Bookmarks", This way it will always stick on the top

<img width="739" alt="image" src="https://user-images.githubusercontent.com/35960860/234779280-db6e7425-ca05-4195-a08e-97c520cac962.png">

<img width="743" alt="image" src="https://user-images.githubusercontent.com/35960860/234779214-9f4a8d0c-10b7-4966-8059-776918f8e98a.png">
