### ISSUE TITLE
[Clipboard History] Ignore passwords copied from browser extension: Bitwarden (password manager)

### ISSUE THREAD

**Issue by amunrarara** [raycast/extensions#4927]
### Extension

https://www.raycast.com/extensions/clipboard-history

### Description

[Clipboard History's description page](https://www.raycast.com/extensions/clipboard-history) states: 

"Passwords copied from any password managers and other [transient data](http://nspasteboard.org/) are ignored by default."

However, passwords copied from Bitwarden are, in fact, showing up within Clipboard History. 

Tested with MacOS desktop app, as well as Vivaldi (Chromium) browser extension. 

### Who will benefit from this feature?

Bitwarden users

**Comment by amunrarara** [comment]
@raycastbot seems to be incorrect in this case

**Comment by amunrarara** [comment]
> > @raycastbot seems to be incorrect in this case
> 
> this is because the clipboard history is not an extension, it is a built-in feature in Raycast.

Where _should_ I post the issue, then?

**Comment by zalewskigrzegorz** [comment]
Hi @amunrarara 
I think you can set up it by yourself.
![image](https://user-images.githubusercontent.com/12560152/222574201-a927a2ec-c668-42bd-bf36-9ab636328455.png)

**Comment by amunrarara** [comment]
@zalewskigrzegorz Thanks for that, I didn't know about that feature. 

Unfortunately, it still does not cover the Bitwarden Chrome Extension, which I use 99% of the time. **Is there a way to prevent Clipboard History from reading specific Chrome Extensions?**

**Comment by amunrarara** [comment]
I'm still hoping this issue can be resolved!

**Comment by thomaspaulmann** [comment]
Mmh interesting... I dug into the source code of the browser extension of Bitwarden. [Here](https://github.com/bitwarden/clients/blob/0d85bdc9314f6a3365aae328079d1e4806492b17/apps/browser/src/autofill/content/misc-utils.ts#L4) is the code where they copy the text/password. It gets copied as a plain text, which means that Raycast doesn't have a way to distinguish it from other items. 

Other macOS apps mark the pasteboard content as transient (more [here](http://nspasteboard.org/)). This allows Raycast to identify if content was transient and ignores it saving it in the Clipboard History.

Few questions:
- Could we add something similar to the open source extension? This would improve the extension in general. AFAIK you can copy custom `ClipboardItem` but unsure about the type of the data.
- Could you test if the password gets removed from your clipboard? So simply copy a password from the extension, then wait a few minutes and see if you can still paste it into other applications with "⌘ + V" (not from the clipboard history).

**Comment by amunrarara** [comment]
That's some excellent code-sleuthing, @thomaspaulmann. 

Is question #1 directed toward me? I'm unsure how to respond to that particular question; I'm not intending to open a PR for Raycast currently, I'm a bit work-swamped at the moment unfortunately. Could change in the future though; this tool rocks. 

As for #2, I confirmed that passwords copied from the Bitwarden browser extension are _not_ being removed from my clipboard. I've attached a screenshot of what the info block from the password itself looks like; I'm using the Bitwarden extension within the Vivaldi browser.

Although macOS apps marks the pasteboard content as _transient_, and the extension copies as plain text, is there a way to view that the _source_ of the copy is a Vivaldi extension, and lift particular information from it? Or, some sort of event listener that Bitwarden emits on-copy that can be listened to? 

Interesting to note, there is a setting in Bitwarden that **auto-clears copied passwords from my standard clipboard based on a selected time in the Settings menu**. That might be a clue to wiring it up to Raycast.

<img width="464" alt="Screen Shot 2023-03-15 at 12 35 12 PM" src="https://user-images.githubusercontent.com/21048358/225283640-b48fffaa-0cba-4db6-848c-16e9e6e53d8a.png">

**Comment by amunrarara** [comment]
(Also, this issue was marked as **Closed** by the robot, can it be re-opened?)

**Comment by guspimentel** [comment]
Could we disable the clipboard history for Raycast's extensions as well? I use the Bitwarden extension a lot and it would be helpful to not have the clipboard history saving my passwords from this source.

**Comment by thomaspaulmann** [comment]
> Could we disable the clipboard history for Raycast's extensions as well? I use the Bitwarden extension a lot and it would be helpful to not have the clipboard history saving my passwords from this source.

We released a new API to mark copied content as transient. Looks like the Bitwarden extension wasn't updated. @guspimentel want to go ahead making the change?

> is there a way to view that the source of the copy is a Vivaldi extension, and lift particular information from it? Or, some sort of event listener that Bitwarden emits on-copy that can be listened to?

@amunrarara unfortunately that isn't possible.

> Interesting to note, there is a setting in Bitwarden that auto-clears copied passwords from my standard clipboard based on a selected time in the Settings menu. That might be a clue to wiring it up to Raycast.

@amunrarara did you enable this setting and notice if Raycast removes the item? I believe we have/had logic for this in place. So maybe that's a bug after-all?!

**Comment by guspimentel** [comment]
> We released a new API to mark copied content as transient. Looks like the Bitwarden extension wasn't updated. @guspimentel want to go ahead making the change?

@thomaspaulmann I have no idea how to do this 😂

**Comment by jomifepe** [comment]
> Could we disable the clipboard history for Raycast's extensions as well? I use the Bitwarden extension a lot and it would be helpful to not have the clipboard history saving my passwords from this source.

> We released a new API to mark copied content as transient. Looks like the Bitwarden extension wasn't updated. @guspimentel want to go ahead making the change?

Hey, I created a [PR](https://github.com/raycast/extensions/pull/5394) to fix this, should be available soon

**Comment by amunrarara** [comment]
> @amunrarara did you enable this setting and notice if Raycast removes the item? I believe we have/had logic for this in place. So maybe that's a bug after-all?! 

I have this enabled, yes, but Raycast does not adhere to it!
