### ISSUE TITLE
[API Bug] Tag Image Display Issue

### ISSUE THREAD

**Issue by HenriChabrand** [raycast/extensions#493]
Raycast version: 1.26.1

## Description

When selecting a tag that as for image source a large external image – the tag don't handle properly the size of the image.

Here's the tag before selecting:

<img width="899" alt="Screenshot 2021-12-07 at 16 31 07" src="https://user-images.githubusercontent.com/18643714/145059084-0ec14dfc-810f-4c52-843f-c50c2fe2f0e0.png">

And once selected:

<img width="899" alt="Screenshot 2021-12-07 at 16 30 53" src="https://user-images.githubusercontent.com/18643714/145059122-fe5e1311-e0d6-4751-a337-71f21f8daf0a.png">

## Steps To Reproduce

1. Create a `TagPicker` with as for icon `{source: SOME_LARGE_IMAGE_URL}`
2. Open the form and select the tag

## The current behavior

<img width="899" alt="Screenshot 2021-12-07 at 16 30 53" src="https://user-images.githubusercontent.com/18643714/145059122-fe5e1311-e0d6-4751-a337-71f21f8daf0a.png">

## The expected behavior

The image should stay small as it is in the list.

**Comment by mattisssa** [comment]
Hey @HenriChabrand! Thanks for the report. Could you please share an URL with this large image, please? Cannot reproduce the bug.

**Comment by mattisssa** [comment]
omg, the longest open issue, but I finally had a chance to catch this bug and resolve the issue. @HenriChabrand It's finally will be gone on the next release 😉
