### ISSUE TITLE
[WhatsApp] Invalid phone format error

### ISSUE THREAD

**Issue by Carl-ki** [raycast/extensions#4936]
### Extension

https://github.com/raycast/extensions/tree/679f72650ed725cad06e6a4524d3be2588595879/extensions/whatsapp/

### Description

Trying to add Chat gives "Invalid phone format" on a number that is perfectly correct.

Is this extension maybe locked to only accept USA phone numbers?

### Steps To Reproduce

Using **macOS 10.15.7 Catalina**
Using **Raycast 1.44.0**

1. Use the "Add chat" option in the Raycast extension
2. Enter a name and a phone number with the +XX country code in front
3. Trying to "Save Chat"

### Current Behaviour

Get error "Invalid phone format"

### Expected Behaviour

I expect the phone number to be added.

**Comment by vimtor** [comment]
Hi there!

I've just tried inputting phone numbers with country codes and it work perfectly. If you @Carl-ki can provide the phone number (changing some digits) for me to test it out would be great.

I am using https://www.npmjs.com/package/phone for the validation. I will try upgrading the library to see if it fixes the issue.

**Comment by Carl-ki** [comment]
Hi vimtor and thank you for your reply. I've managed to narrow down the issue in that the error is only for Brazilian country code (+55)

I looked at your validation library.

Maybe changing this code:  **phone_number_lengths: [10, 11]**
To this:  **phone_number_lengths: [9,10, 11,12]**

...could resolve the issue?

**Comment by Carl-ki** [comment]
Here is a demo Brazilian phone number with numbers changed. The first (489) are for the region.
+55 48 9919-1804

**Comment by vimtor** [comment]
Hi @Carl-ki can you try if is working now with the new version?
