### ISSUE TITLE
[NotePlan 3] Commands not working

### ISSUE THREAD

**Issue by marceldarvas** [raycast/extensions#4937]
### Extension

https://www.raycast.com/shakedlokits/noteplan-3

### Description

I tried searching my notes via the extension and got no results, I tried the daily plan, it doesn't seems to be woking.

I found the File Extension option, which I changed to md, but it was still broken.

I have my notes store in CloudKit via NotePlan, may have to do with the issue.

**Comment by marceldarvas** [comment]
@shakedlokits I've located what the issue is. The Container path for the SetApp version of NotePlan is different
https://github.com/raycast/extensions/blob/69248d62bf7fb7774000ef59446fd564f6ee1819/extensions/noteplan-3/src/lib/note-utilities.ts#L10

I've tried creating a forked version and changing it to
``const NOTE_PLAN_URI = `${homedir()}/Library/Containers/co.noteplan.NotePlan-setapp/Data/Library/Application Support/co.noteplan.NotePlan-setapp`;``

Which didn't help as I ran into new problems:
```
RangeError: Invalid time value

search_default:search.tsx:7:2

---
4: import { NoteDetail, OpenNoteAction } from "./lib/components";
5: 
6: export default () => {
7:   const [notes] = useNoteList();
8:   const { push } = useNavigation();
9: 
0:   return (
---

wr:index.js:5:2490
    at ray-navigation-stack
Ro:index.js:5:2088

```

This is beyond my skills. Let me know what you think!

**Comment by lukerandall** [comment]
@marceldarvas can you confirm if this is now fixed with the latest version?

**Comment by marceldarvas** [comment]
@lukerandall I was almost going to reply that it doesn't work, but then I caught my mistake.

In the file extension field I had "md " with the space. Once I removed that I started working. 

Thanks for adding SetApp option!
