### ISSUE TITLE
Sip

### ISSUE THREAD

**Issue by rocketdonut** [raycast/extensions#4944]
### Extension

https://www.raycast.com/jameslyons/sip

### Description

When trying to use the extension, it launches Webex.

### Steps To Reproduce

1. Choose any command from the extension
2. Webex launches

**Comment by rocketdonut** [comment]
![Screenshot](https://user-images.githubusercontent.com/60496281/221044348-4bed025e-85bd-4a56-a177-93a80ecf7a75.png)

**Comment by jamesjlyons** [comment]
Interesting, looks like Webex is picking up the url scheme and assuming it's the last part of its own: `webexteams://meet?sip=[[VALUE]]`. Seems like Webex shouldn't even pick it up, but let me see if there's any way around it.

**Comment by rocketdonut** [comment]
There's a setting in Webex that allows the user to choose which application to start a call with.

![Application Picker](https://user-images.githubusercontent.com/60496281/229292729-8667310b-28f5-46e5-a942-ee6b23d8383f.png)

Depending on which application is selected, it will open that app when you use this extension. I changed it to Sip and the extension works as expected. This is what I'm going to use as a workaround.
