### ISSUE TITLE
Feedback on Raycast's user experience and suggestion for direct result display

### ISSUE THREAD

**Issue by Hongbusi** [raycast/extensions#4949]
### Description

Hello, I am a user of Raycast and would like to give feedback on an issue with the user experience. 

As a tool that values simplicity, I really enjoy Raycast's design. However, when using plugins, I found one aspect that is not as straightforward: after entering a keyword, I need to perform a jump operation to display the results, which I find a bit cumbersome. 

Raycast VS Alfred:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/53554371/221114991-7ef07c1d-8d5c-4b2b-8b6a-602f15628c45.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/53554371/221115027-c084e498-9762-4251-8df7-b174725b5680.png">

Therefore, I would like to ask if Raycast supports directly displaying results upon invocation? If not, are there any plans to add this feature in future updates? 

Thank you for your time and patience in reading this, and I look forward to your reply.

**Comment by mathieudutour** [comment]
You can add an alias to the `translate` command to achieve the same result
