### ISSUE TITLE
Did not support on old Mac, for example MacBook 2015 [Toothpick] ...

### ISSUE THREAD

**Issue by peaceyourself** [raycast/extensions#4950]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

When tap Manage Blue Connections，there is nothing found on my MacBook 2015pro

**Comment by VladCuciureanu** [comment]
Hey! Could you please share the output of the following command?
`system_profiler SPBluetoothDataType -json`
Thanks

**Comment by peaceyourself** [comment]
> Hey! Could you please share the output of the following command? `system_profiler SPBluetoothDataType -json` Thanks

```
{
  "SPBluetoothDataType" : [
    {
      "controller_properties" : {
        "controller_address" : "AC:BC:32:94:DF:34",
        "controller_chipset" : "BCM_20703A1",
        "controller_discoverable" : "attrib_off",
        "controller_firmwareVersion" : "v169 c4825",
        "controller_productID" : "0x0001",
        "controller_state" : "attrib_on",
        "controller_supportedServices" : "0x382039 < HFP AVRCP A2DP HID Braille AACP GATT Serial >",
        "controller_transport" : "USB",
        "controller_vendorID" : "0x004C (Apple)"
      },
      "devices_list" : [
        {
          "Jabra Elite 65t" : {
            "device_address" : "70:BF:92:24:6A:C0",
            "device_firmwareVersion" : "2.2.2",
            "device_minorType" : "Headset",
            "device_productID" : "0x247E",
            "device_vendorID" : "0x0067"
          }
        },
        {
          "JBL T280TWS" : {
            "device_address" : "F0:A9:68:10:5B:71",
            "device_minorType" : "Headset"
          }
        },
        {
          "shin" : {
            "device_address" : "08:C7:29:2B:BB:15"
          }
        },
        {
          "Beats Solo³-shin" : {
            "device_address" : "DC:D3:A2:BB:E6:A6",
            "device_minorType" : "Headphones",
            "device_productID" : "0x2006",
            "device_vendorID" : "0x004C"
          }
        }
      ]
    }
  ]
}
```

**Comment by sarneeh** [comment]
I'm experiencing the same issue on a 2015 MacBook. Interesting that it used to work a while ago, but after some update it stopped. It just doesn't show any device, even tho there are multiple bluetooth connections.

**Comment by VladCuciureanu** [comment]
Thanks for the additional data! I've been experiencing a very tight schedule for the last few weeks so I didn't have the time to look into it but I wrote this bug down and will be in the next update for sure.

**Comment by sarneeh** [comment]
@VladCuciureanu @peaceyourself The problem has been fixed after updating to MacOS Ventura 🎉

**Comment by VladCuciureanu** [comment]
Glad to hear that! I will investigate the bug when I have some time on my hands though. Wouldn't want older versions to be incompatible.
