### ISSUE TITLE
[Amazon AWS] Not getting AWS credentials

### ISSUE THREAD

**Issue by andreacavagna01** [raycast/extensions#4953]
### Extension

https://www.raycast.com/Falcon/aws

### Description

The Amazon AWS Extension of Raycast does not work with aws credentials in the credentials file

### Steps To Reproduce

1 - start Leapp to generate a set of short-lived AWS credentials inside `~/aws/credentials` folder
2 - searching for s3 bucked fo any other command
3 - no result found always

**Comment by JonathanWbn** [comment]
relates to #4941

I will check this over the weekend.

**Comment by boringContributor** [comment]
Hi @JonathanWbn,

I created your mentioned issue and already found the root problem. 

https://github.com/raycast/extensions/pull/4984

I created a PR here which fixes the problem. Feel free to collaborate with me on this issue :)

**Comment by JonathanWbn** [comment]
I opened https://github.com/raycast/extensions/pull/5141 which I expect fixes this. @andreacavagna01 could you check this?

**Comment by andreacavagna01** [comment]
Sorry for being late, by checking the repo, I see that the extension only checks for ENV variables, which is not the default method of credentials generation of AWS. This is why the app is not working with Leapp. Can we re-open this?
