### ISSUE TITLE
316429[Flight Tracker] ...

### ISSUE THREAD

**Issue by sebasckushki** [raycast/extensions#4966]
### Extension

https://www.raycast.com/cojmeister/trackflight

### Description

I'm using Raycast to access Flight tracker. I set up my API Key; it works properly when I test the code snippet inside RapidAPI, but for the same query from Raycast, I get 'Internal Server error' when I attempt to find data on a flight

I saw in the release notes that there were updates to Flight Tracker, perhaps some of these are causing an issue and need to be rolled back?

**Comment by sebasckushki** [comment]
@raycastbot close this issue

**Comment by cojmeister** [comment]
I'm guessing you managed?

**Comment by sebasckushki** [comment]
Yes! It was an issue with having copied the ' at the beginning of the API
key, accidentally! [image: 🤦‍♂️]

Sebastián Castro
Cofundador + Presidente
***@***.***

Chapultepec Uno Piso 16, Av. Paseo de la Reforma 509, CDMX
<https://kushkipagos.com/> <https://www.linkedin.com/company/kushki/>
<https://www.facebook.com/KushkiOficial/>
