### ISSUE TITLE
[Tailwind CSS] Find the nearest color based on the given color code.

### ISSUE THREAD

**Issue by yogiw** [raycast/extensions#4968]
### Extension

https://www.raycast.com/vimtor/tailwindcss

### Description

Users can find Tailwind colors by inputting the color code. For example, if a user inputs #EFF0F7, the matching color will be returned. If there is no match, the nearest color, which is slate-100 (#F1F5F9), will be returned. Euclidean distance may work well for this purpose.

### Who will benefit from this feature?

Tailwind user

**Comment by vimtor** [comment]
This is a great idea but I feel this could complicate things a bit too much. For example you could mistake yourself into believing that the input you wrote is the actual color or I will need to set a threshold for when colors disappear, which seems really tricky to nail down. Also, I don't have any way to explain this in the extension so this could be confusing for some people.

For now I prefer keeping things simple and just provide a way to search the default colors.
Thank you for your suggestion ❤️

@raycastbot close this issue
