### ISSUE TITLE
[Google Workspace] Multiple google accounts

### ISSUE THREAD

**Issue by natedog2424** [raycast/extensions#4972]
### Extension

https://www.raycast.com/raycast/google-workspace

### Description

I have personal and school google accounts and i would love to be able to search the drive of both accounts. I often forget what account a file is in so it's a huge pain to find where they are.

### Who will benefit from this feature?

Anyone who has multiple google accounts which I think is like everyone :)

**Comment by thomaslombart** [comment]
Thanks for reporting but there's always [an issue](https://github.com/raycast/extensions/issues/4039) for this use-case 😊
