### ISSUE TITLE
Error: Timeout

### ISSUE THREAD

**Issue by naveen-bharathi** [raycast/extensions#4978]
### Extension

https://www.raycast.com/gdsmith/jetbrains

### Description

Reason: Code: 14 (Timeout) Domain: commands Time: 01:38:55.374

### Steps To Reproduce

Run the **Search recent projects** command in the [Jetbrains Toolbox](https://www.raycast.com/gdsmith/jetbrains) extension

### Current Behaviour

Loads indefinitely

### Expected Behaviour

List the projects

**Comment by gdsmith** [comment]
@naveen-bharathi any more context? What app are you trying to launch? Is this only for a specific project or for all projects? What is giving the error there?

**Comment by naveen-bharathi** [comment]
When I'm trying to run the **Search recent projects** command in the [Jetbrains Toolbox](https://www.raycast.com/gdsmith/jetbrains) extension, It loads indefinitely, and sometimes throws an error `Reason: Code: 14 (Timeout) Domain: commands Time: 01:38:55.374`. I was using this extension without any issues until I reset my MacBook. After that reinstalled Raycast and this extension, and this extension now doesn't work.

**Comment by gdsmith** [comment]
Okay, what version of JB Toolbox do you have? What tool are you trying to open? Does it work from the Toolbox project launcher

**Comment by naveen-bharathi** [comment]
JB Toolbox version: 1.27.2.13801

Trying to open projects used in webstorm with this extension.

Note: not sure if it has anything to do with this issue, webstorm was manually installed but is detected by JB Toolbox and shows the recent projects from webstorm

**Comment by gdsmith** [comment]
Okay, yes, it relies on the apps being installed via toolbox. Maybe just try installing it that way and see if that fixes it.

**Comment by naveen-bharathi** [comment]
@gdsmith reinstalling webstorm via toolbox fixed the issue. Thanks for you support.

**Comment by naveen-bharathi** [comment]
@raycastbot close this issue
