### ISSUE TITLE
[GitHub] ... Open issues are not showing

### ISSUE THREAD

**Issue by jSagvold28** [raycast/extensions#4980]
### Extension

https://www.raycast.com/raycast/github

### Description

I have a total of 4 issues open and they arent showing up in Raycast

### Steps To Reproduce

1. Open raycast
2. go to github issues
3. look

### Current Behaviour

No issues fount

### Expected Behaviour

Display open issues

**Comment by thomaslombart** [comment]
Could you give more details about your open issues? I can't reproduce it so it's a bit hard to debug it.

**Comment by jSagvold28** [comment]
Weird, it happened a few times I just restarted my mac and it seemed work well. Thank you for your time!

**Comment by thomaslombart** [comment]
That's weird. I'll close this issue, but don't hesitate to reopen it or reach out in case it happens again.
