### ISSUE TITLE
[Obsidian] Append specific note / file

### ISSUE THREAD

**Issue by patrikzudel** [raycast/extensions#4981]
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

The "Append daily note" feature is nice but in practice it creates a lot of files which just end up messy for me. I much prefer to have a dump file / "Short term tasks" file and keep track of all things needed there. 

It would be amazing to have a quick way to append a specific file. Basically what I want is just the ability to chose which file I can append new text to, not just the Daily note.

Thanks!

### Who will benefit from this feature?

Anyone who uses Obsidian for task management and/or quick notes but prefers not to use Daily notes.

### Anything else?

Figured out a way to accomplish this using Quick Links in raycast using this URL.
If anyone needs this just change the (Vault Name) and (File Name)

obsidian://advanced-uri?vault=**(Vault Name)**&filepath=**(File Name)**&data={Query}&mode=append

Still having this in the extension would be great because of the **Silent mode.**

**Comment by marcjulianschwarz** [comment]
Hi @patrikzudel,

Thank you, this will be an upcoming feature, see https://github.com/marcjulianschwarz/obsidian-raycast/issues/36
