### ISSUE TITLE
[Heroicons] Copy name as PascalCase

### ISSUE THREAD

**Issue by henrikruscon** [raycast/extensions#4985]
### Extension

https://www.raycast.com/haack/heroicons

### Description

Would be very neat to add ability to copy the name as PascalCase, right now it copies only in kebab-case.

### Who will benefit from this feature?

People who use the [heroicons npm dependency](https://www.npmjs.com/package/heroicons) need to manually convert the name right now to PascalCase.

**Comment by haackt** [comment]
> ### Extension
> 
> https://www.raycast.com/haack/heroicons
> 
> ### Description
> 
> Would be very neat to add ability to copy the name as PascalCase, right now it copies only in kebab-case.
> 
> ### Who will benefit from this feature?
>
> People who use the [heroicons npm dependency](https://www.npmjs.com/package/heroicons) need to manually convert the name right now to PascalCase.
> 
> ### Anything else?
> 
> _No response_

That's a neat addition to the extension, I haven't even thought of. I will implement it ASAP.

Thank you very much, for bringing it to my attention!

**Comment by henrikruscon** [comment]
Keep this detail in mind if you're intention is to support the specific use-case I mentioned above:

> Icons use an upper camel case naming convention and are always suffixed with the word Icon.

For a more general approach simply doing the PascalCase is enough.

Thanks for a great extension!
