### ISSUE TITLE
[Spotify Controls] Toggle play pause does not work

### ISSUE THREAD

**Issue by MattAgn** [raycast/extensions#4989]
### Extension

https://www.raycast.com/thomas/spotify-controls

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    tell application "Spotify"
      if not application "Spotify" is running then
        activate

        set _maxOpenWaitTimeInSeconds to 5
        set _openCounter to 1
        repeat until application "Spotify" is running
          delay 1
          set _openCounter to _openCounter + 1
          if _openCounter > _maxOpenWaitTimeInSeconds then exit repeat
        end repeat
      end if
      playpause
    end tell
402:411: execution error: Non autorisé à envoyer des évènements Apple à Spotify. (-1743)

    tell application "Spotify"
      if not application "Spotify" is running then
        activate

```

### Steps To Reproduce

1. Spotify is opened
2. I press the hotkey to toggle play-pause
3. Nothing happens
4. When I open raycast, I see the error message

### Current Behaviour

When spotify is not playing and when I press the hotkey to toggle play/pause, nothing happens 

### Expected Behaviour

When I press the hotkey to toggle play/pause, Spotify plays (when it was not playing before)

### Side note

I found out that when I directly use the raycast command "Toggle play/pause" (without the hotkey, it does not work either). The play and pause commands don't work either.

**Comment by thomaspaulmann** [comment]
Looks like Raycast isn't authorized to run AppleScript. Could you restart Raycast and try again?

**Comment by thomaspaulmann** [comment]
Ah great it got resolved!
