### ISSUE TITLE
[OpenAI GPT3] Request new ai model

### ISSUE THREAD

**Issue by glkrenx** [raycast/extensions#4992]
### Extension

https://www.raycast.com/simicvm/openai-gpt3

### Description

Please consider to add code-cushman-001 to list of AI Model. As refer to Models OpenAI page it says this model slightly faster. This could show the result even faster

### Who will benefit from this feature?

Developer who need faster result generated code

### Anything else?

Here is the source

https://platform.openai.com/docs/models/codex

**Comment by simicvm** [comment]
Sure, I'll add soon.

**Comment by simicvm** [comment]
PR is here https://github.com/raycast/extensions/pull/5041

**Comment by simicvm** [comment]
@raycastbot close this issue
