### ISSUE TITLE
[Music] ... add to playlist error

### ISSUE THREAD

**Issue by wiwiluo** [raycast/extensions#4994]
### Extension

https://raycast.com/fedevitaledev/music

### Description

Error: Command failed with exit code 1: osascript -e 
tell application "Music"
	set theName to name of current track
	set theArtist to artist of current track
	set theAlbum to album of the current track
	set existingTracks to get tracks of source "Library" whose name is theName and artist is theArtist and album is theAlbum
	
	if (count of existingTracks) = 0 then
		set theCount to count of tracks of source "Library"
		duplicate current track to source "Library"
		repeat while theCount = (count of tracks of source "Library")
			delay 1
		end repeat
	end if
	
	set theTrack to first track of source "Library" whose name is theName and artist is theArtist and album is theAlbum
	duplicate theTrack to playlist "jp"
end tell
 
177:271: execution error: “Music”遇到一个错误：不能获得“every track of source "Library" whose name = "Boy" and artist = "Reol" and album = "Boy - Single"”。 (-1728)
    at S0 (/Users/saeba/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:59)
    at /Users/saeba/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:10477
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async qc (/Users/saeba/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:38131)

**Comment by Rawnly** [comment]
Hi is your system lang English? Unfortunately seems that the "Library" playlist is language sensitive, I'm still figuring out how to support multiple languages
