### ISSUE TITLE
[Roam Research] ...

### ISSUE THREAD

**Issue by wecanseeformiles** [raycast/extensions#4997]
### Extension

https://www.raycast.com/dive2Pro/roam-research

### Description

![image](https://user-images.githubusercontent.com/126406936/221421428-903892c2-e671-4d89-bb1f-88a3c6840bd6.png)

It's not obvious what token is being required for the graph.  Filling in my password for Roam Research doesn't work.  Presumably it's some graph specific password but I have no idea where to find it.  Is it assuming that user's have encrypted their graph with a password.  More explanation is needed within the form to make it clearer to the user.

**Comment by dive2Pro** [comment]
@wecanseeformiles hey, you can take the token by following these steps
https://roamresearch.com/#/app/developer-documentation/page/bmYYKQ4vf
