### ISSUE TITLE
Form.Dropdown types should be able to specified as union types

### ISSUE THREAD

**Issue by BasixKOR** [raycast/extensions#4998]
### Description

Currently, the value of `<Form.Dropdown />` can only be specified as a string, making it clunky when used with union types.

Making it generic (specifically make it extend `FormItemProps_2<T>` instead of `FormItemProps_2<string>`) would be beneficial for type safety.,

### Who will benefit from this feature?

TypeScript enthusiasts, mostly.

**Comment by mathieudutour** [comment]
It wouldn't really be possible to ensure type safety for the children of the Dropdown (eg. ensuring that you are only adding value from the union type). So I'd say that it'd be _detrimental_ for type safety. Or maybe I'm understanding what you are proposing?
