### ISSUE TITLE
[OneNote] ...

### ISSUE THREAD

**Issue by MeboGit** [raycast/extensions#5000]
### Extension

https://www.raycast.com/alewandowski/onenote

### Description

It would be great if there would be a global search over all sections. If you don't know the section you have to go to OneNote and execute the search in there :-(

**Comment by alewandows** [comment]
Hello, 
Actually, the extension already searches over all sections globally. You just have to type some keywords in the search bar and corresponding notes (or sections, or notebooks) will appear, wherever they are located.

**Comment by alewandows** [comment]
@raycastbot close this issue

**Comment by MeboGit** [comment]
Thanks for your reply. 
If I enter some search phrase I get the following error:

Error: Command failed with exit code 1: osascript -e 
        tell application "System Events"
            keystroke "a" using command down
            keystroke "c" using command down
        end tell
        tell application "Microsoft OneNote" to activate
     
54:86: execution error: System Events got an error: osascript is not allowed to send keystrokes. (1002)

        tell application "System Events"
            keystroke "a" using command down
            keystroke "c" using command down
        end tell
--------
How could I activate OneNote or what Do I have to activate?

**Comment by alewandows** [comment]
When the search gives no result, the extension creates a new note with the search string as title. 
To do so, it needs some access rights. 
Go to System Settings > Privacy & Security > Accessibility,   and add Raycast to the list.

**Comment by MeboGit** [comment]
Ok, Raycast added to Security Settings, thanks.
But how do I make a global search (equivalent to OneNote|Find|Search All Notebooks)? Looks like I only can search in titles?! A global search in "All Notebooks" would really be great!

**Comment by alewandows** [comment]
Not implemented for now. 
But it could be interesting, you're right. I put it on the feature request list 👍

**Comment by MeboGit** [comment]
Ok, that would be very nice, for me this would be a key feature within Raycast itself.
Also the Mac|OneNote|Find|Search All Notebooks search is a little poor, you only get the page-names where the search string occurs. A perfect search would be to list all lines (clickable to go into the position of that orrurance in that note) in all notebooks with that search phrase. 

Not even Microsoft is able to implement such a search :-(
