### ISSUE TITLE
[Amazon AWS] ... Add Support for MFA profiles 

### ISSUE THREAD

**Issue by zachcp** [raycast/extensions#5004]
### Extension

https://www.raycast.com/Falcon/aws

### Description

Accessing AWS resources via the Raycast API is fantastic. However, for multi-user or role-based accounts, it is often the case that an MFA step is required. Would it be possible to add MFA validation to this extension?

### Who will benefit from this feature?

Anyone using this extension who needs to use MFA to access their account.

**Comment by JonathanWbn** [comment]
@zachcp I have been trying to do this for a while (and spent many hours on it). I **do** think it's possible, but it isn't trivial. I haven't given up on it, though.

relates to #3022
