### ISSUE TITLE
[Asana] Create task and Close or Create another one

### ISSUE THREAD

**Issue by alper** [raycast/extensions#5009]
### Extension

https://www.raycast.com/raycast/asana

### Description

There should be different usages of Return and Command-Return.

One of them should be the current feature:
- Create task and leave the window open to create another one

The other should be:
- Create task and close the window immediately

### Who will benefit from this feature?

People who need speed.

**Comment by thomaslombart** [comment]
That could be done via a preference in the `Create Task` form. This is actually a setting we have for other extensions that need a quick-add like feature 😊
