### ISSUE TITLE
[Deepcast] Add a revert selected languages

### ISSUE THREAD

**Issue by bryanvrgsc** [raycast/extensions#5017]
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

A button that shift the selected languages, for example from English to Spanish. Then you click shift and change from Spanish to English

### Who will benefit from this feature?

Everybody, because it is normal if you don't know the language to verify.

### Anything else?

<img width="858" alt="Screenshot 2023-02-27 at 9 34 10 a m" src="https://user-images.githubusercontent.com/35511824/221607868-340ac973-ae11-43e5-a6fa-b1331159eb4e.png">

**Comment by MonsterDeveloper** [comment]
There's already such a feature: just press `Cmd+K` in Translate view and select Switch languages. Or just do it in one click by pressing `^X`.
