### ISSUE TITLE
search tags which are written not in english

### ISSUE THREAD

**Issue by GreenRuslan** [raycast/extensions#5020]
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

For now, when I'm trying to search for a note via a tag written in Ukrainian - it doesn't perform any search and shows me only the list of all notes.

### Who will benefit from this feature?

I believe that it will help all people who are using not english for their obsidian notes and tags in it

**Comment by marcjulianschwarz** [comment]
Could you please share an example note that I can try?

**Comment by GreenRuslan** [comment]
Yes, of course.

For example, I have a note with such tag `#психологія`. When I use the
"search note" command and use a tag for searching then I receive the list
of all notes without any filtering via tag and also, in the dropdown of all
tags I don't see any tag in Ukrainian.

Here how does it looks like.

This is the original note
[image: image.png]

Here is how I'm trying to find it (I tried both variants with # and without)
[image: image.png]

And this flows gives wrong results in all cases which are connected with
ukrainian language. When I'm searching via english - everything is all
right. Searching via name of the notes in ukrainian works correctly.

пн, 27 лют. 2023 р. о 18:57 Marc Julian Schwarz ***@***.***>
пише:

**Comment by marcjulianschwarz** [comment]
Thank you for providing an example, will have a look at this in the next few days.

**Comment by GreenRuslan** [comment]
Any updates about this problem?
