### ISSUE TITLE
[Cal.com] Share Meeting Link does not work. It's always empty despite me having public meeting links. 

### ISSUE THREAD

**Issue by harrisrobin** [raycast/extensions#5024]
### Extension

https://github.com/raycast/extensions/tree/main/extensions/cal-com-share-meeting-links

### Description

“share meeting link” for cal.com's raycast extension has never ever worked for me.

I have made sure i pasted in the API key, tried different keys days later and im on the latest version. It always shows up empty despite me having two public meetings (15m & 30m).
Anyone else experiences this?
<img width="766" alt="image" src="https://user-images.githubusercontent.com/3880008/221670532-a3286729-a18d-4e87-919d-0035faa45029.png">

### Steps To Reproduce

1. Make sure you have public event types in your cal.com profile
2. grab your API key from cal.com
3. paste in into the Raycast extension
4. See that there are no meeting links shown at all.

<img width="761" alt="CleanShot 2023-02-27 at 12 02 16@2x" src="https://user-images.githubusercontent.com/3880008/221670755-9e6f737c-d514-4112-9643-62de166332db.png">

I'm not sure if there's something about my meetings that make it not go through.

### Current Behaviour

The meeting links are not shown.

### Expected Behaviour

The meeting links should be shown.

**Comment by eluce2** [comment]
Hi @harrisrobin. I'm unable to replicate this. Are you using the hosted or self-hosted version of cal.com? The extension only works with the hosted version, but that is the only thing off the top of my head why it wouldn't work for you.

**Comment by harrisrobin** [comment]
@eluce2 thanks for the reply!

I'm using the hosted version, not the self hosted. I definitely pasted the API key that I copied directly to my clipboard on cal.com. I don't really know why it's not working for me, will keep trying stuff.

Here's a video


https://user-images.githubusercontent.com/3880008/221679224-a88894a4-3e4f-4b3f-88e3-61a9efd5e981.mp4
