### ISSUE TITLE
[Music] Search apple music by name, artist, album, etc

### ISSUE THREAD

**Issue by 55Cancri** [raycast/extensions#5026]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

Search music by name, artist, etc.

### Who will benefit from this feature?

Everyone using apple music and raycast

**Comment by Rawnly** [comment]
as seen in https://github.com/raycast/extensions/issues/4913

**Comment by Rawnly** [comment]
@raycastbot close this issue
