### ISSUE TITLE
[NixPkgs Search] CAN NOT perform search

### ISSUE THREAD

**Issue by HawickMason** [raycast/extensions#5034]
### Extension

https://www.raycast.com/aiotter/nixpkgs-search

### Description

CAN NOT perform search with error below
![image](https://user-images.githubusercontent.com/15688994/221759386-90023435-0504-44e1-844d-c9c27f35ad05.png)

### Steps To Reproduce

just search any package in NixPkgsSearch

### Current Behaviour

prompt with errror 

### Expected Behaviour

return search result

**Comment by aiotter** [comment]
This seems the revival of #3500.
It must be easy to fix, however, I am extremely busy nowadays. My patch will come after 14th Mar.
I can review it if you make a PR.

**Comment by Teruya-Himaki** [comment]
Hi, I experienced this issue and tried working on it. Glad if you can review that :bow:
