### ISSUE TITLE
[Hypersonic] Be able to rank tasks according to the `Select` property's rank

### ISSUE THREAD

**Issue by gregoirenovel** [raycast/extensions#5038]
### Extension

https://www.raycast.com/reboot/hypersonic

### Description

I defined Hypersonic's `Select` to be the "Priority" column defined in my Notion DB.
This Priority column as a given order (High > Medium > Low).
Could it be possible to ask Hypersonic to rank tasks according to this columns' ranking?

**Comment by mv-stns** [comment]
Instead of that, additionally setting priorities would be awesome. Like !, !! or !!! (Low, Mid, High) or something similar. Tried tinkering that myself but I'm no Typescript Dev and in Raycast the priority tag is always vanishing after a database fetch.
