### ISSUE TITLE
[CleanShot X] ...

### ISSUE THREAD

**Issue by gheIIer** [raycast/extensions#5047]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

#### Error:
```
Error: Could not open URL

process.processImmediate:timers:471:21

```

**Comment by Aayush9029** [comment]
Do you have cleanshot installed? 



if so try


cleanshot:// 

And lmk what happens.

**Comment by gheIIer** [comment]
fixed it, I just had to link the extension to the relative app.

**Comment by Aayush9029** [comment]
@gheIIer Great 👍 , sorry for future reference. What does "link to app" mean?

**Comment by gheIIer** [comment]
After trying to start up cleanshot on raycast for a few times (always resulting in an error), a notification popped up automatically asking me to connect manually cleanshotX to the extension on raycast!
