### ISSUE TITLE
[LastPass Credentials Search] Don't sync every time the extension gets used

### ISSUE THREAD

**Issue by neticmfr** [raycast/extensions#5069]
### Extension

https://www.raycast.com/alex-popov-tech/lastpass

### Description

As it's configured right now, it looks like everytime you use the LP extenstion, it does a "lpass sync".

It would be nice that you can add a manual sync and you remove the automatically sync. You can make it a optional function or set it to sync once a day.

### Who will benefit from this feature?

At our company we have a lot of password in LP, and it takes a long time every time it syncs. It takes about 10 seconds.

It's way faster to use LP's own app as for now.

### Anything else?

It's a very good plugin and I would like to use it, if the automatically sync gets removed or only set to sync once a day.

**Comment by alex-popov-tech** [comment]
Hey @neticmfr , thanks for bringing this.
I will look into this, and see if i can help with your problem.

**Comment by neticmfr** [comment]
Hi @alex-popov-tech, very nice. Thank you.

**Comment by alex-popov-tech** [comment]
@neticmfr seems that pr is merged, please take a look if that fixes your issue

**Comment by neticmfr** [comment]
@alex-popov-tech apparently it didn't fix the issue with slow load time.

I really don't know what it could be :-(

**Comment by neticmfr** [comment]
@alex-popov-tech It's the lpass export command that takes a long time.

**Comment by alex-popov-tech** [comment]
@neticmfr is calling `lpass export --sync=no` takes lot of time too? is there much difference between `--sync=yes` and `--sync=no` ?

**Comment by neticmfr** [comment]
@alex-popov-tech, nope it pretty much takes the same amount of time.

It has to load everything before you can search in the LP extension. And when you have a lot of passwords, then it takes a long time to export everything, every time you use the extension.

**Comment by alex-popov-tech** [comment]
@neticmfr im curious how many passwords do you have so see such?

Im sorry to hear that it is not working well for you, but i don't think there is any pagination mechanism built in `lpass export` :(

Maybe we could cache id's of entities ourselves, and use only `lpass show`, but im not sure that is okay from security point of view, and it sounds rather complicated...do you think its okay to store such things locally?

**Comment by neticmfr** [comment]
@alex-popov-tech We have 5000+ passwords.

I thought about creating a list/or-something-else from the "lpass ls" command and then afterwards use the "lpass show" command to grab details like passwords, username etc.

But a search function in Raycast I have now idea on how to create.

**Comment by neticmfr** [comment]
`lpass ls --format="%ai %au %ap %al %am %aU %as %ag" --sync=now  0.58s user 0.04s system 52% cpu 1.165 total`

time lpass ls --format="%ai %au %ap %al %am %aU %as %ag" --sync=no:
`lpass ls --format="%ai %au %ap %al %am %aU %as %ag" --sync=no  0.56s user 0.03s system 94% cpu 0.618 total`

time echo '$password' | LPASS_DISABLE_PINENTRY=1 lpass export --sync=no --fields=id,name,username,password,url
`LPASS_DISABLE_PINENTRY=1 lpass export --sync=no   4.85s user 15.06s system 93% cpu 21.399 total`

Apparently the time command bugs a little bit out when a one-liner includes a pipe, but I did include the fields "id,name,username,password,url" to the lpass export command.

The lpass login with sync takes a bit longer that 0.58 seconds, I think about 2 seconds more. So total with sync will be about 2.58 seconds.

**Comment by alex-popov-tech** [comment]
@neticmfr ok i see

So roughly speaking its `0.5s` vs `5s`, right?

**Comment by neticmfr** [comment]
@alex-popov-tech 

There's different times for both user time and system time. They need to be counted together.

lpass ls with sync = 2.62 sec.
lpass ls without sync = 0.58 sec.
lpass export without sync = 19.91 sec.

There's a massive 19.33 sec difference, between "lpass ls" without sync and "lpass export" without sync.

**Comment by neticmfr** [comment]
@alex-popov-tech 

I'll wait. Just write, if there's any more information you'll need.

**Comment by alex-popov-tech** [comment]
@neticmfr i've tested it locally, and even for my ~180 entities it few times faster ( 0.2s vs 0.6s-1.2s ), so here is new PR https://github.com/raycast/extensions/issues/5069

Hope this one will help more than previous :)

**Comment by neticmfr** [comment]
@alex-popov-tech 

Nice, I can't wait to try it out :-)

**Comment by neticmfr** [comment]
@alex-popov-tech 

You did it. It's very fast now. I'll be using this and I'll recommend this extension to my colleagues.

Very good job and thank you so much :-)

**Comment by neticmfr** [comment]
@alex-popov-tech 

There's actually one more thing, that would be nice to add.

When you search for an entry you can see the ID of the entry, but you can't copy the ID nor can you search for entries using the ID.

Being able to search for entries using the ID, would make this extension even better :-)

**Comment by alex-popov-tech** [comment]
@neticmfr copy for ID could be added, mind sharing use case for this? :) 

about search by ID - i just went through the docs and found [this](https://developers.raycast.com/api-reference/user-interface/list#search-bar) page, i will give it a try

**Comment by neticmfr** [comment]
@alex-popov-tech 

When entries sometimes have similar names it's better to identify them by ID.

**Comment by neticmfr** [comment]
@alex-popov-tech 

I would like to be able to filter by ID (Which is in your picture) or by name.

![image](https://user-images.githubusercontent.com/107932924/224715283-1e0adc6a-d4c0-4ea3-9be2-15a5a950ff92.png)

The "lpass ls" command also shows both name (filtered out by red boxes) and ID.

**Comment by alex-popov-tech** [comment]
@neticmfr added PR for this https://github.com/raycast/extensions/pull/5359

**Comment by neticmfr** [comment]
@alex-popov-tech 

It works. Thank you a lot.

**Comment by alex-popov-tech** [comment]
@neticmfr glad that I could help, please don't forget to close the ticket :)
