### ISSUE TITLE
[1Password] Possibility to copy username, password and OTP from Raycast

### ISSUE THREAD

**Issue by janpeeters70** [raycast/extensions#5071]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

It would be great is we could copy username, password and OTP for a specific 1P entry directly from Raycast instead of Raycast opening 1P to that entry. Would something like this be possible?

### Who will benefit from this feature?

Everyone that uses 1P ;-) It will provide much more flow and speed!

**Comment by khasbilegt** [comment]
Duplicate of #4626
