### ISSUE TITLE
[OpenAI GPT3] include gpt-3.5-turbo 

### ISSUE THREAD

**Issue by tungnh91** [raycast/extensions#5080]
### Extension

https://www.raycast.com/simicvm/openai-gpt3

### Description

OpenAI has released gpt-3.5-turbo 
https://platform.openai.com/docs/guides/chat

### Who will benefit from this feature?

everyone

**Comment by simicvm** [comment]
sure, will do it soon.

**Comment by mjherich** [comment]
Thanks, @simicvm. I hacked something together [here](https://github.com/mjherich/extensions/commit/736d6fe6ed483a2c1a54ae2d57989a850e09a2cb) to get it working supafast. Would be 🤌 if we could get a true conversational interface within raycast, not sure if that's possible with the api yet though.

**Comment by simicvm** [comment]
@mjherich another contributor already got his PR merged into the app. https://github.com/raycast/extensions/pull/5090

**Comment by zach-fuller** [comment]
@raycastbot close

**Comment by zach-fuller** [comment]
@raycastbot close this issue
