### ISSUE TITLE
[Visual Studio Code - Project Manager] Even after installing Project Manager the extension doesn't work

### ISSUE THREAD

**Issue by sambowenhughes** [raycast/extensions#5087]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

Hey 👋 

Maybe some weird caching going on. After installing `Project Manager` into VS Code I still get the following warning: 

> To use this extension, the Visual Studio Extension [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) is required.

### Steps To Reproduce

1. Ensure you don't have `Project Manager` installed in VS Code
2. Install `Visual Studio Code` to Raycast
3. Search `code` into Raycast
4. You get this warning `To use this extension, the Visual Studio Extension [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) is required.`
5. Install Project Manager in VS Code
6. Search `code` into Raycast
7. Same warning 🤔 

I have reset my PR and reset VS Code.

### Expected Behaviour

Id expect it to have picked up the VS Code changes?

**Comment by MarkusLanger** [comment]
Hello @sambowenhughes,

do you have any projects saved in the "Project Manger" of VSCode?

Could you check the path and the structure of the project.json of the VS Code Project Manger Extension in VS Code?
<img width="1082" alt="211246068-920291b3-0206-46ba-a6da-e96dea6e201e" src="https://user-images.githubusercontent.com/12131918/222344936-8d65780c-73ab-4713-ab56-9d50aec6c2d6.png">

<img width="1117" alt="211246093-54f2cfdf-d1c5-4ae1-a1f7-6059716d6860" src="https://user-images.githubusercontent.com/12131918/222345015-833b8d3f-e7a8-42f5-a759-81a9ee39e56b.png">

**Comment by sambowenhughes** [comment]
Hey @MarkusLanger 

So I've just checked my `projects.json` file. I hadn't configured any projects which is why ray cast wasn't picking them up. 

My bad, first time using Project Manager so hadn't realized I needed to manually configure them. After setting up Project Manager correctly Raycast is working perfectly. Closing this issue 🙏
