### ISSUE TITLE
[NotePlan 3] ...

### ISSUE THREAD

**Issue by roamnovice** [raycast/extensions#5088]
### Extension

https://www.raycast.com/shakedlokits/noteplan-3

#### Error:
```

```

### Steps To Reproduce

loaded the extension and it doesn't work

### Expected Behaviour

should allow me to search my notes

**Comment by pr1mal** [comment]
@roamnovice could you please provide a bit more details? 
- Did it work before or was this the first time you tried it?
- what version of Raycast and Noteplan extension are you using?
- what is installation source of Noteplan - AppStore or SetApp?

**Comment by roamnovice** [comment]
I had just downloaded the latest version of ray cast and then the extension. It is the App Store version of Noteplan Noting happens. I just get the something went wrong. I’d be happy to set up a time and trouble shoot Colin Gold305-785-6511On Mar 2, 2023, at 2:57 AM, Evgeny Sokolov ***@***.***> wrote:﻿
@roamnovice could you please provide a bit more details?

Did it work before or was this the first time you tried it?
what version of Raycast and Noteplan extension are you using?
what is installation source of Noteplan - AppStore or SetApp?

**Comment by roamnovice** [comment]
I had just downloaded the latest version of raycast 1.48 and then the extension. 

I am using the App Store version of Noteplan 

Noting happens. I just get the something went wrong. i reload and nothing.

I am using md notes. 

I’d be happy to set up a time and troubleshoot. I feel like it cannot find the directory?

I switched to setapp version to test, and I didn't get the error, just got no results. Then back to app store, and got the error.

**Comment by pr1mal** [comment]
I guess you were not requested to configure Noteplan extension. If yes, go to Raycast settings and:
1. Go to "extensions" section
2. Find "Noteplan" extension
3. Change default "txt" file extension to "md"
4. Select appropriate installation source of Noteplan - AppStore or SetApp
<img width="1112" alt="Screenshot 2023-03-06 at 10 28 00" src="https://user-images.githubusercontent.com/95601/223070656-ffc20ff2-10d1-41a9-9c56-dc132b7acb1c.png">

This should help

**Comment by roamnovice** [comment]
Thank you for all of your help:

I did all of the things you said: Please see attached pictures:

Here is a copy of the error:

RangeError: Invalid time value

tse:search.tsx:7:18
wr:index.js:5:2490
    at ray-navigation-stack
Ro:index.js:5:2088


Please let me know if you have any questions. 



Colin Gold
305-785-6511



￼￼

**Comment by pr1mal** [comment]
@shakedlokits do you have ideas why this may happen?

**Comment by lukerandall** [comment]
@roamnovice the short answer is that it's likely this is happening because you're using monthly, quarterly or yearly notes. I've opened a PR that will hopefully fix this; if you're able to test it (PR is #5176) that would be great.

**Comment by roamnovice** [comment]
I would be more than happy to help but you will need to walk me through how to load.

I read everything on that page, but I am an end user, most of that doesn’t make sense. Sorry. 

But I promise, I will provide feedback.  


Colin Gold
305-785-6511

**Comment by pernielsentikaer** [comment]
This is now merged, could you give it a go?
