### ISSUE TITLE
[ARC] Support for arguments in ARC search command

### ISSUE THREAD

**Issue by kush-daga** [raycast/extensions#5094]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

Would love to have a feature, where we can add arguments in the Search Command for Arc extension.

Argument Reference - https://developers.raycast.com/information/lifecycle/arguments

This would allow for us to be able to search directly using deeplink, something like this

<img width="784" alt="image" src="https://user-images.githubusercontent.com/40840079/222427196-473e1ad1-006a-45d8-a466-483c65aa76c8.png">

### Who will benefit from this feature?

Anyone using deeplinks, or this extension. This also might solve an issue where Search Arc is a fallback command

Example - 
<img width="700" alt="image" src="https://user-images.githubusercontent.com/40840079/222427367-e5a86840-1348-47bd-907d-1f01b8b3f3ab.png">

After we click on search with arc, this does not actually search

<img width="799" alt="image" src="https://user-images.githubusercontent.com/40840079/222427567-a4bd8a01-073b-486d-b6d3-b3a02719f31f.png">

Have to press space or some character for it to search.
<img width="750" alt="image" src="https://user-images.githubusercontent.com/40840079/222428498-cb8f0015-9367-4a61-9908-7b1741cfd8ae.png">

**Comment by thomaspaulmann** [comment]
Cool idea, I added support for it in #5168. Thanks for the suggestion!
