### ISSUE TITLE
[Gitlab] endless loading of Images in issue 

### ISSUE THREAD

**Issue by janstieler** [raycast/extensions#5096]
### Extension

https://github.com/raycast/extensions/tree/e98c4ee82dff7213d357a6b1c5b129ccc5682e17/extensions/gitlab

### Description

If I show an Isseue in Raycast and the issue have an image it never end the loading.

### Steps To Reproduce

Open a Gitlab issue in raycast with an image.

### Current Behaviour

It shows only a grey badge with the loading text.
![Bildschirmfoto 2023-03-02 um 13 07 24](https://user-images.githubusercontent.com/754880/222439089-9023d60b-4f9f-4720-b02d-5baeb6c36e54.jpg)

### Expected Behaviour

The image inside the issue should be displayed.

**Comment by macbookandrew** [comment]
@janstieler by chance is this a private GitLab instance? If so, then that’s the cause.

**Comment by tonka3000** [comment]
@janstieler Hi,

As @macbookandrew already mentioned: do you use a private GitLab instance? Is it possible to share the link how it is written in markdown in the referenced issue?

**Comment by macbookandrew** [comment]
In theory it’s feasible to replace that with a full URL based on the instance URL and issue/project URL, but I suspect it’ll still be broken because Raycast doesn’t have the auth session cookies that your browser does.

**Comment by macbookandrew** [comment]
Based on my test just now:

- Uploaded an image to an issue in our private GitLab instance
- Copied the full URL
- Opened the URL in my normal browser and it displayed correctly
- Opened the URL in a different browser, and it redirected me to the gitlab login screen

**Comment by janstieler** [comment]
Hi,
okay if it can't solve than I have to live with it :) .

**Comment by tonka3000** [comment]
@janstieler Make a public test repo and add an issue with an uploaded. I would guess this one is working.

The actual implemention already should replace the relative path with an absolute one. I'm pretty sure that is an permission issue. I think this is also the case for other images as well (when I remember correctly).

**Comment by pangliang** [comment]
same issue

```javascript
return (<Detail markdown={`![img](https://avatars.githubusercontent.com/u/3114995?s=80&v=4)`} />);
```

![image](https://user-images.githubusercontent.com/3114995/230564437-3d20c08d-9e09-4b45-a48b-78170de39ecb.png)

**Comment by tonka3000** [comment]
@pangliang make a public repo and try it with that

**Comment by tonka3000** [comment]
This is a current limitation of the extension. Image are not shown when the user don't have permission for `private` or `internal` projects because the requests needs to be authorized (see #5976). Raycast `Detail` don't have the ability to add extra headers to the request and so request fail and is stuck in the `Loading` state.

For public repositories this works normally.

When something like #5976 would be in the Raycast API it would be fixable.

**Comment by tonka3000** [comment]
This is a limitation from the GitLab API (see [#25498](https://gitlab.com/gitlab-org/gitlab/-/issues/25498)). It is not possible now to download artifacts like images from a private/internal project even the access token is provided.
