### ISSUE TITLE
[1Password] Unable to make it work

### ISSUE THREAD

**Issue by zalewskigrzegorz** [raycast/extensions#5099]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

I got an error when I tried to use it. With 1password8 and CLI

`Command failed: /usr/local/bin/op signin --account xxx
Enter the password for xxxxxx at my.1password.com: [ERROR] 2023/03/02 16:00:35 operation not supported on socket
`
There is no information how to setup extension.

### Steps To Reproduce

1. Install extension
2. try to use it.

### Current Behaviour

returns error
`Command failed: /usr/local/bin/op signin --account xxx
Enter the password for xxxxxx at my.1password.com: [ERROR] 2023/03/02 16:00:35 operation not supported on socket
`

### Expected Behaviour

Should display paswords

**Comment by thomaspaulmann** [comment]
@khasbilegt or @pernielsentikaer could you assist with the setup here?

**Comment by mvcaaa** [comment]
Same here

```
Command failed: /usr/local/bin/op signin --account nnnnnnnnnnnnn
Enter the password for xxx.xxx@gmail.com at my.1password.com: [ERROR] 2023/03/14 15:37:15 operation not supported on socket
```

**Comment by mvcaaa** [comment]
I think something is changed in op cli

if i try to run in manually there is an error:

```

mvc@MacBook-Pro-2 ~ % /usr/local/bin/op signin --account nnnnnnnnnnnn

[ERROR] 2023/03/14 15:39:12 Output of 'op signin' is meant to be executed by your terminal. Please run 'eval $(op signin)'. You can use the '-f' flag to override this warning.
````

**Comment by mvcaaa** [comment]
Looks like i figure it out

You have to Connect 1Password CLI with the 1Password 8 desktop app: https://developer.1password.com/docs/cli/get-started#step-1-connect-1password-cli-with-the-1password-8-desktop-app

**Comment by pernielsentikaer** [comment]
Does anyone still have issues here?

**Comment by zalewskigrzegorz** [comment]
Quite works but i'm stuck on 
![image](https://user-images.githubusercontent.com/12560152/225049867-03f374bd-5ba0-4fb2-97ed-89b1e827b663.png)

but this same in console, so I believe it's my internal problem not related to extension
![image](https://user-images.githubusercontent.com/12560152/225050357-636c0599-6495-4a13-a3a4-19b804a7755d.png)

**Comment by khasbilegt** [comment]
> Quite works but i'm stuck on ![image](https://user-images.githubusercontent.com/12560152/225049867-03f374bd-5ba0-4fb2-97ed-89b1e827b663.png)
> 
> but this same in console, so I believe it's my internal problem not related to extension ![image](https://user-images.githubusercontent.com/12560152/225050357-636c0599-6495-4a13-a3a4-19b804a7755d.png)

I was told by the 1Password team that they recently had [availability issues]([1Password.com service availability issues.](https://1password.statuspage.io/incidents/jfd09216tf1l)) on their servers, so please try again and see if the same issue still occurs.
