### ISSUE TITLE
[Timers] Dismiss Timer Alert don't work.

### ISSUE THREAD

**Issue by bokamix** [raycast/extensions#5100]
### Extension

https://www.raycast.com/ThatNerd/timers

### Description

When Dissmiss Timer Alert is selected from the menu, the alerts are not interrupted.
![image](https://user-images.githubusercontent.com/29372724/222468285-ecdaeea9-3244-432a-b8f0-267143b74f17.png)

**Comment by ThatNerdSquared** [comment]
Hi @bokamix, thanks for using Timers - can you copy the log using ⌘K so we can get a better sense of what the error is?
