### ISSUE TITLE
[Logitech Litra] ... More commands

### ISSUE THREAD

**Issue by zalewskigrzegorz** [raycast/extensions#5101]
### Extension

https://www.raycast.com/timrogers/logitech-litra

### Description

First! 
Awesome work.

It will be great to have more commands available to use
litra-brightness-lm
or 
litra-temperature-k

### Who will benefit from this feature?

Everyone. :D

**Comment by timrogers** [comment]
@zalewskigrzegorz Thanks for reaching out! Do you have any thoughts on how you'd like the interface to work?

**Comment by zalewskigrzegorz** [comment]
Personally, I will prefer command to increase or decrease bright by 10% and similar for a color changes. But maybe it will be quicker to use some presets what user can configure in a menu.
