### ISSUE TITLE
[Jira Beta] Create Issue fails

### ISSUE THREAD

**Issue by daghoidahl** [raycast/extensions#5115]
### Extension

https://www.raycast.com/raycast/jira-beta

### Description

Trying to create a Jira issue, I get this error:

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'issuetypes')

Vy:CreateIssueForm.tsx:57:42
kU:create-issue.js:103:3853
wr:index.js:5:2490
    at ray-navigation-stack
```

 It started after I opened the Create Issue command and selected a specific project, and since then the command has stopped working entirely. I was able to work around it by reinstalling the extension.

### Steps To Reproduce

The error now happens every time I try to open the Create Issue command.

**Comment by thomaslombart** [comment]
I'll look into that this week!

**Comment by thomaslombart** [comment]
@daghoidahl Do you have any issue types associated with your project?
