### ISSUE TITLE
[Bitwarden Vault] Show full information for a bank card

### ISSUE THREAD

**Issue by zmactep** [raycast/extensions#5117]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

For now I can copy just one field of the bank card at the time. So, if I want to copy card info into the payform I have to:
Search for a card -> Copy number
Search for a card -> Copy month
Search for a card -> Copy year
Search for a card -> Copy CVV

This is a lot of actions. **It would be great if I could see the card full info in some view.**

### Who will benefit from this feature?

One look instead of 4-5 searches.

**Comment by jomifepe** [comment]
Hey, yeah, that makes sense, I will add it to my personal backlog for this extension, to implement when I have the time.

**Comment by zmactep** [comment]
@jomifepe, sounds great, thank you!

**Comment by jomifepe** [comment]
Added a new `Show Card Details` action to the vault items, try it out 🚀

**Comment by pernielsentikaer** [comment]
Added
