### ISSUE TITLE
[Authy] Couldn't decrypt service tokens

### ISSUE THREAD

**Issue by francistogram** [raycast/extensions#5123]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

I get the error "Couldn't decrypt service tokens. Seems like Backup Password is wrong"

At this point I've approved the connection on my phone and have tried changing my password 3 times so I'm sure that it actually does match

I've also tried uninstally Authy extension and reinstalling

<img width="764" alt="image" src="https://user-images.githubusercontent.com/3721449/222772905-18d6c896-b8bf-470d-8593-c260240477ad.png">

**Comment by guga4ka** [comment]
@raycastbot close this ticket

i'm working on fix, but i really limited im time, will try to release fix during next week
