### ISSUE TITLE
[github] ... shows integration error icon while it's working fine

### ISSUE THREAD

**Issue by mibrahimdev** [raycast/extensions#5125]
### Extension

https://www.raycast.com/raycast/github

### Description

shows an integration error icon while it's working fine.

<img width="768" alt="Screenshot 2023-03-03 at 7 53 16 PM" src="https://user-images.githubusercontent.com/12463348/222794744-f10f63f1-ecee-44dd-a516-6feb4fe49603.png">

<img width="777" alt="Screenshot 2023-03-03 at 7 53 24 PM" src="https://user-images.githubusercontent.com/12463348/222794718-9c1221db-9285-4810-a417-66aef73e035f.png">

### Current Behaviour

shows an integration error icon

### Expected Behaviour

should hide the error icon

**Comment by thomaslombart** [comment]
What do you mean by integration error icon? What's the error message?

**Comment by mibrahimdev** [comment]
@thomaslombart this little red warning, it appears all over the extension commands

<img width="119" alt="Screenshot 2023-03-07 at 3 42 07 PM" src="https://user-images.githubusercontent.com/12463348/223439787-422d52b5-a1fb-442d-9cd7-095b1f8313f2.png">

**Comment by thomaslombart** [comment]
You're probably using the deprecated GitHub version. You can use the new one from the store instead: https://www.raycast.com/raycast/github.

**Comment by mibrahimdev** [comment]
yeah it's working fine now, will close the issue
