### ISSUE TITLE
[Obsidian] Add Selected File to Vault

### ISSUE THREAD

**Issue by heliostatic** [raycast/extensions#5130]
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

I'd like to select a PDF and add it to my vault (ideally with a note). My specific use case is adding papers I find in my research to my vault for later reference.

### Who will benefit from this feature?

Obsidian users who frequently add files to their vaults.

### Anything else?

I'd also be excited to have a "web clipper" that takes a URL from the clipboard and creates a note with it :)

**Comment by marcjulianschwarz** [comment]
Hi @heliostatic. Thank you for the feature request. Where would you want the file to be added in your vault?
- The default media folder
- Selected folder from a list of folders
- root folder of vault

**Comment by weitzman** [comment]
I love the web clipper proposal.
