### ISSUE TITLE
[Change Case] Paste by default, Snake case/Title case blend

### ISSUE THREAD

**Issue by trijste** [raycast/extensions#5131]
### Extension

https://www.raycast.com/es183923/change-case

### Description

I wish this extension offered an option to paste on enter rather than copy to clipboard on enter. I wish this extension had an option for a combined snake/title case

### Who will benefit from this feature?

All users!

**Comment by rochakagrawal** [comment]
For me it pastes by default. I want the reverse. I want copy to clipboard by default. How do I change it?
@es183923 @pernielsentikaer
