### ISSUE TITLE
[Emoji Picker] Duplicate Norway Flag

### ISSUE THREAD

**Issue by JonathanWbn** [raycast/extensions#5140]
### Extension

https://www.raycast.com/changelog/1-29-0

### Description

The Norway flag appears twice when searching for it.

![Raycast 2023-03-04 at 14 42 44](https://user-images.githubusercontent.com/19997520/222905724-07893724-6e13-4f52-9f10-3ca8d6d01a95.png)

### Steps To Reproduce

Open built-in Emoji Picker.

### Current Behaviour

The Norway flag appears twice in search results.

### Expected Behaviour

The Norway flag appears once in search results.

**Comment by pernielsentikaer** [comment]
Thanks a bunch for flagging and tagging, I'll have a look with the team 😊
