### ISSUE TITLE
[Google Search] Using as a fallback command doesn't respect input

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#5166]
### Extension

https://www.raycast.com/mblode/google-search

### Description

If you set Google Search as a fallback command, the input is not respected. Instead, the previously queried search is used.

### Steps To Reproduce

Set the command as a fallback command and select it as the fallback for a query

### Current Behaviour

It shows results for the previous queried search

### Expected Behaviour

It should show results for the new query.

**Comment by vburlion** [comment]
Thanks for opening this issue. Same behaviour here with the latest version of Raycast (1.48.5).
Also, if you disable "Remember search history" in the extension settings, it shows no result unless you input a new character.

<img width="862" alt="Screenshot 2023-03-05 at 22 20 09" src="https://user-images.githubusercontent.com/5800483/223012113-ac2d7bc4-f2f0-4fea-b8a4-43cd0a4c9acb.png">
