### ISSUE TITLE
[Toothpick] Show Battery Percentage of non-apple devices

### ISSUE THREAD

**Issue by felixludwig1** [raycast/extensions#5173]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

Hey,
would be super nice to have the ability to see the current battery percentage of all my connected devices. In this case it's not showing the battery of my mouse (mx master 3) in toothpick, while it does in the mac control center. 

It would be very helpful to see this here and would finally make the bluetooth-menu in the control center obsolete, being fully replaced by this extension! 

![Screenshot 2023-03-06 at 16 13 52](https://user-images.githubusercontent.com/97047348/223151202-a0055941-b81f-42fe-a924-8053a4477797.png)
![Screenshot 2023-03-06 at 16 14 31](https://user-images.githubusercontent.com/97047348/223151208-28f5abdc-f312-4a4b-8b8e-c562aedcd7c1.png)

**Comment by VladCuciureanu** [comment]
Hey Felix! Sorry for the late reply and thanks for your suggestion! In theory this is what I'm trying to do with Toothpick but in this instance I'm not sure how the MX Master is sending battery data. Could you help me out?

This is what I need:

1. Connect your device
2. Open this extension in Raycast
3. Highlight your device
4. Press 'Command + K'
5. Run 'Copy Device Data' command
6. Paste your data in an issue using [this template](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cfeature+request&template=extension_feature_request.yml&title=%5BToothpick%5D+Device+Support+Form&extension-url=https://www.raycast.com/briankosw/toothpick&description=%3Cb%3EDevice%20brand%20and%20model%3C%2Fb%3E%0AReplace%20this%20line%20with%20your%20device%27s%20brand%20name%20and%20model%0A%0A%3Cb%3EDevice%20data%3C%2Fb%3E%0AReplace%20this%20line%20with%20the%20copied%20data).
7. ???
8. Profit
