### ISSUE TITLE
[Hue] Brightness shortcuts don't work

### ISSUE THREAD

**Issue by jornetsimon** [raycast/extensions#5178]
### Extension

https://www.raycast.com/pindab0ter/hue

### Description

Using the `CMD-Shift-Up/Down` shortcut to increase/decrease the brightness does not do anything. It used to work, though.

<img width="886" alt="CleanShot 2023-03-07 at 19 12 33@2x" src="https://user-images.githubusercontent.com/936101/223512418-03e1da53-3a84-46bc-a6f0-1a8f8c9fa581.png">

### Steps To Reproduce

- Go to Control Groups or Control Lights
- Press the shortcut 

### Current Behaviour

The brightness doesn't decrease or increase

### Expected Behaviour

- The brightness should change when pressing the shortcut

**Comment by pindab0ter** [comment]
It seems the command still works, but the shortcut doesn't.

@thomaspaulmann do you know of any changes to the availability of the <kbd>⌘⇧↑</kbd> and <kbd>⌘⇧↓</kbd> shortcuts? For the records, <kbd>⌘⇧←</kbd> and <kbd>⌘⇧→</kbd> do still work, and it happening to both me and @jornetsimon decreases the likelihood of it being a user configuration issue.

**Comment by pindab0ter** [comment]
I'm working on a big update that uses the new V2 version of the Hue API. In developing that, I've noticed that issue is gone. So hold out for that!

**Comment by pindab0ter** [comment]
The issue I described hasn't been resolved.

**Comment by jornetsimon** [comment]
You're right, there is still an issue on raycast-hue@2.0 for groups.
Sorry for closing too early.

**Comment by pindab0ter** [comment]
I've had talks with the devs. This is a bug with the Grid view.

**Comment by pindab0ter** [comment]
@thomaspaulmann can you confirm that this is related to a bug with the specific shortcuts? Off the top off my head it's <key>Cmd</key>+<key>Shift</key>+Arrow keys

**Comment by pindab0ter** [comment]
It seems like this issue has been resolved.

@raycastbot please close this issue.
