### ISSUE TITLE
[Extension Bug] – Days until Christmas

### ISSUE THREAD

**Issue by fivestones** [raycast/extensions#518]
# Extension – [Days until Christmas](https://github.com/raycast/extensions/tree/40c9568745d66423e25473f7d20bfdba73f5f890/extensions/days-until-christmas)

Author: @MEGApixel23 

## Description 
I am in Kathmandu time zone (which is GMT+5:45), and the extension currently says it's 12 days and 13 hours till Christmas, when it's actually only 12 days and 11 hours and 52 minutes till Christmas here.

## Steps To Reproduce

1. Set computer to Kathmandu time zone (I'm assuming this is part of the problem)
2. Install extension.
3. Run extension. Time is a little over an hour off. 

## The current behavior
Reads a little over an hour extra in the time until Christmas

## The expected behavior
Should give the exact correct time until Christmas--either hours, minutes, seconds, or else round to the closest hour, correct for a given current time zone.

### Raycast version
Version: 1.26.1

**Comment by MEGApixel23** [comment]
Thanks for the report! I'll review it and will update you once fixed.

**Comment by fivestones** [comment]
Just trying to not let this be closed by the bot

**Comment by fivestones** [comment]
> Thanks for the report! I'll review it and will update you once fixed.

Any chance this will get fixed eventually?

Thanks!
