### ISSUE TITLE
[GitHub] Add typeahead search for repository

### ISSUE THREAD

**Issue by simonkotwicz** [raycast/extensions#5181]
### Extension

https://www.raycast.com/raycast/github

### Description

When trying to create a GitHub issue the dropdown list is populated with a limited list of repositories and trying to create an issue in any other repository doesn't seem possible. My own repositories don't even show up. All I see in the dropdown list are repositories in orgs that I belong to that I have never even touched (most of which return an error anyways saying access to repo collaborators is denied).

### Steps To Reproduce

Use `Create Issue` command (this probably only happens if you are part of multiple orgs that have a lot of repositories).

### Current Behaviour

Your own repositories don't even show up in the list of repos you can create issues for.

### Expected Behaviour

Your own repositories should appear and probably appear first in the list.

**Comment by thomaslombart** [comment]
Could you add a screenshot or screencast of the result you're getting? There are a maximum of 100 repositories in the `Create Issue` command so it's surprising you're not seeing at least one of your repositories. Otherwise, we should probably add typeahead search to the repository field to be able to search through your repos.

**Comment by thomaslombart** [comment]
Exactly, the search query should be used for searching the repositories.

**Comment by thomaslombart** [comment]
Hey @simonkotwicz, I'm busy with other projects at the moment, so I'm afraid I won't be able to fix that soon. Are you willing to take on that PR? I can surely provide you with some pointers on how to achieve the feature.

**Comment by simonkotwicz** [comment]
Unfortunately I'm a bit overloaded right now as well, but maybe if you leave some pointers the next person that sees the issue can make a PR.
