### ISSUE TITLE
[OpenAI GPT3] ...

### ISSUE THREAD

**Issue by chibincode** [raycast/extensions#5182]
### Extension

https://www.raycast.com/simicvm/openai-gpt3

### Description

Help! Why does the prompt result in the feedback "Something went wrong but I am not sure what" every time I send it?

**Comment by DorukAkinci** [comment]
Hey @chibincode, If you could explain the `steps to reproduce`, we might answer the question better. Did you set your OpenAI API token? Are you sure that the token is correct and there is no whitespace in the string? Also, how did you fill out the form inputs before you send the message? Once you give this information, we can check again 🙌
