### ISSUE TITLE
[1Password] Modify shortcuts and few new features!

### ISSUE THREAD

**Issue by teziovsky** [raycast/extensions#5186]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

I would like to start using the 1Password extension, however, I would prefer to be able to modify keyboard shortcuts for the "Copy Username" and "Copy Password" actions. Additionally, I have some ideas for features that could be added to the extension:

The ability to paste the username and password in addition to copying them.
Copying and pasting 2FA codes.
Closing the Raycast window after copying the username or password so that the copied phrase can be immediately pasted.

### Who will benefit from this feature?

Anyone who wants to customize shortcuts

**Comment by thomaspaulmann** [comment]
Why customizing keyboard shortcuts? We usually try to pick the best. Do you want to add the new actions yourself?

**Comment by teziovsky** [comment]
I create this issue because I prefer to use ⇧ it as a modifier as often as possible.
It's easier to click ⇧ + ⌘ + C or ⇧ + ⌥ + C rather than ⌘ + ⌥ + C. That's why I would love to change it in settings 🤔
