### ISSUE TITLE
[Jira Beta] Assign To not listing my user

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#5188]
### Extension

https://www.raycast.com/raycast/jira-beta

### Description

When I try to assign an issue to myself (search for Federico) my user doesn't come up in the dropdown. It works on the non-beta version.

**Comment by thomaslombart** [comment]
Are you able to see at least some users in the dropdown?

**Comment by thomaslombart** [comment]
Are you able to find yourself if you search your name?

**Comment by FezVrasta** [comment]
no, as soon I type "fe" it stops returning results

**Comment by thomaslombart** [comment]
Do you have this action in your extension? 

<img width="374" alt="CleanShot 2023-03-09 at 14 25 36@2x" src="https://user-images.githubusercontent.com/16003285/224036709-d8b11675-ac24-4e4c-b9ae-e370fc7cf91d.png">

**Comment by FezVrasta** [comment]
<img width="373" alt="CleanShot 2023-03-09 at 2 59 17@2x" src="https://user-images.githubusercontent.com/5382443/224047907-ef3cb383-e426-4793-b989-b2f3f9832cc2.png">

**Comment by thomaslombart** [comment]
So the requests are the same between the two extensions so it's hard to debug it here (like for the sprint results). Could you share a recording of the action you're performing in the native extension and in the beta extension?

**Comment by FezVrasta** [comment]
I'm showing up now 🤔 

<img width="509" alt="CleanShot 2023-03-21 at 12 48 44@2x" src="https://user-images.githubusercontent.com/5382443/226597437-00f9222f-6ddb-4bf1-a13d-55810d109e73.png">
