### ISSUE TITLE
[Jira Beta] Default priority level not respected

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#5189]
### Extension

https://www.raycast.com/raycast/jira-beta

### Description

I have configured some custom priority levels, and set one of them as default. When I go create a new issue, the wrong priority level is selected by default.

**Comment by thomaslombart** [comment]
Ah, interesting. The issue form selects the first value by default in the dropdown. It makes sense to choose the default.

**Comment by thomaslombart** [comment]
After checking out Jira's API, it seems they don't send back the default priority. The priority object does have a `isDefault` property, but I can't see it in my instance. Knowing that this is relatively [new](https://community.developer.atlassian.com/t/new-batch-of-rest-apis-for-jira-priorities-released-in-jira-cloud/62774) and that their APIs are marked as experimental, I'm not sure that's possible as of now.

In the meantime, I'll make it so the form automatically remembers the last priority value.
