### ISSUE TITLE
[Jira Beta] Support for teams?

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#5190]
### Extension

https://www.raycast.com/raycast/jira-beta

### Description

It would be great if you could add support for teams, they are part of the Jira Software Premium subscription so they are not super common.

<img width="442" alt="CleanShot 2023-03-07 at 11 53 08@2x" src="https://user-images.githubusercontent.com/5382443/223402176-da8a5f23-8c5b-44ed-bfce-88c61295f1e6.png">

**Comment by thomaslombart** [comment]
This should be doable by adding support for a new custom field in the extension. I'll look into it 😊

**Comment by thomaslombart** [comment]
After looking at it, I won't be able to add that improvement since I need Jira Premium on my account. So, I encourage you to tackle it. Feel free to contact me here or in the [Slack community](https://www.raycast.com/community) if you have any questions 😊
