### ISSUE TITLE
[Fantastical] "Fantastical is not installed"

### ISSUE THREAD

**Issue by fabriciojm** [raycast/extensions#5192]
### Extension

https://www.raycast.com/devahschaefers/fantastical

### Description

Not possible to use the extension; when adding a new event I get:
"Fantastical is not installed. Please first install fantastical to use this extension"
Was once reported in [Reddit](https://www.reddit.com/r/raycastapp/comments/z1bxha/raycast_app_and_fantastical_help_please/).

App Version: 1.48.5
System Version: 12.1.0
<img width="461" alt="image" src="https://user-images.githubusercontent.com/4597553/223411525-9ead67ff-4529-448c-956e-0913270a0877.png">

**Comment by msageryd** [comment]
@fabriciojm Did you solve this?
I'm getting the same error.

**Comment by devahschaefers** [comment]
Go to Finder > Applications and check what the name of Fantastical is. If it’s not Fantastical please change it to Fantastical and please report what it is.

**Comment by msageryd** [comment]
Oh, my bad 🤦
I have been running Fantastical from the Downloads folder all the time without noticing. Moved it to Applications and everything works nicely.

Thanks!
