### ISSUE TITLE
[Google Chrome] Search Bookmarks Error - "no bookmarks"

### ISSUE THREAD

**Issue by alxwlfe** [raycast/extensions#5208]
### Extension

https://www.raycast.com/Codely/google-chrome

### Description

I've installed the latest Raycast and Chrome Extension, but continue to run into this error when attempting to search my bookmarks in Chrome. It's unclear if there are permissions I need to setup, etc.

`🚨Error: Google Chrome browser has no bookmarks. Please add some bookmarks to continue using this command. `

I do have bookmarks lol

I've tried:
- restarting Raycast
- uninstalling/reinstalling the Chrome Extension

Any help appreciated!

### Steps To Reproduce

1. Install latest Raycast + Chrome Extension **(note: install this using Raycast, no via browser)**
2. Open Raycast
3. type 'Chrome'
4. Select 'Search Bookmarks' option
5. Press ENTER

### Current Behaviour

I receive the following error:

`🚨Error: Google Chrome browser has no bookmarks. Please add some bookmarks to continue using this command. `

### Expected Behaviour

Bookmarks are searched

**Comment by alxwlfe** [comment]
Update, installing this via the browser store (as opposed to within Raycast itself) resolved this, leaving the issue in case it's worth investigating

**Comment by HiNeal** [comment]
The same problem, through the web download still can't solve

**Comment by wu-yifan** [comment]
Some problem here.

**Comment by neversmiler** [comment]
me  too
