### ISSUE TITLE
[GitHub] Can't load repositories because of permission issues

### ISSUE THREAD

**Issue by wtiann** [raycast/extensions#5209]
### Extension

https://www.raycast.com/raycast/github

### Description

After entering `Create pull request`, it shows an error `Failed to fetch latest data`.   Error message: `You do not have permission to view repository collaborators`. I think some of the repos has some permission issues. But it seems to prevent loading other repos. I tried to create PR for other repos, but those repos can't be found in the dropdown. However, those are available in search repo or search PR commands.

### Steps To Reproduce

1. Enter Create Pull Request by command. if it loads some repos that has permission issue  it'll show the error.

**Comment by thomaslombart** [comment]
Could you send a screencast of what you're getting? It'll make it easier to debug this 😊

**Comment by wtiann** [comment]
This is when the `Create Pull Request` panel opened, it got an error. Not sure if that prevents loading rest of the repo lists. From this repo dropdown some repo are missing, but the missing ones can be found through search repo function.
 
<img width="862" alt="Pasted Graphic 2 copy" src="https://user-images.githubusercontent.com/87437339/224180186-f98f067b-0e0f-4472-88c8-ec2bdf2ef804.png">

**Comment by thomaslombart** [comment]
Thanks for including the screenshot! I'll take a deeper look at that in the next few days or weeks.

**Comment by mxstbr** [comment]
Still an issue.
