### ISSUE TITLE
[Jira Search (Self-Hosted)] Entering a JIRA key scenario

### ISSUE THREAD

**Issue by na2hiro** [raycast/extensions#5216]
### Extension

https://www.raycast.com/emanguy/jira-search-self-hosted

### Description

For the search ticket feature, it would be nice to support a quick access to JIRA when JIRA key is provided. Specifically, there's a bit of friction today:

1. Type ABC
2. Depending on how fast I type, it can start searching tickets which contains ABC and show the result
3. Continue typing -123 and enter
4. Enter chooses the first result which contains "ABC", instead of opening ABC-123

What would be ideal

1. Type ABC
2. Depending on how fast I type, it can start searching tickets which contains ABC and show the result
3. (new) Continue typing -123. As soon as It looks like JIRA ticket (when it's "ABC-1"), stop showing search result, but show "Open ABC-1" option, without waiting for JIRA API to return ticket name. Once API returns ticket name, it can show the ticket name
4. (new) Enter will send user to open the ticket which I typed

### Who will benefit from this feature?

Those who communicate or document JIRA keys but it happened it was not linked

**Comment by svenwiegand** [comment]
Fixed with PR #5507 for the jira cloud version of the extension. Thanks to @na2hiro for the well-thought idea.

**Comment by na2hiro** [comment]
@svenwiegand Thanks for the quick resolution! I don't know what's the differences in processes between cloud version and self hosted; Would self hosted version be soon updated, or needs fixes separately by separate set of maintainers?

**Comment by svenwiegand** [comment]
@na2hiro The original Jira extension is the cloud version which has been created by me. Someone then made a fork (a copy) of it to address Jira for servers. So this is a completely separate project maintained by other people. Thus it requires manual effort to implement this feature there. It is totally up to the maintainers of this extension whether they will implement this feature at all.

Sorry …
