### ISSUE TITLE
[Jira Search (Self-Hosted)] Race condition in ticket search result 

### ISSUE THREAD

**Issue by na2hiro** [raycast/extensions#5217]
### Extension

https://www.raycast.com/emanguy/jira-search-self-hosted

### Description

When it searches JIRA tickets while I'm typing, a result for what I typed before can override what I typed after.

It should instead cancel ongoing requests once the result for later changes arrives.

### Steps To Reproduce

1. Type "Hide"
2. It starts searching for "Hide"
3. Quickly continue typing to be "Hide button"
4. It starts searching for "Hide button"
5. It shows result for "Hide button" (it can be faster because there are fewer results)
6. It shows result for "Hide"

You might need to choose some nice query and/or a JIRA instance with a lot of tickets

### Current Behaviour

It shows result for "Hide", which is not intended

### Expected Behaviour

It shouldn't do step 6: it should keep showing a result for "Hide button"

**Comment by svenwiegand** [comment]
Fixed with PR #5507 for the Jira cloud version.
