### ISSUE TITLE
[Things] Inspection is enabled by default for process or parent application with deprecated 'com.apple.webinspector.allow' entitlement

### ISSUE THREAD

**Issue by misterkrueger** [raycast/extensions#5219]
### Extension

https://www.raycast.com/loris/things

### Description

I’m running out of ideas why the Things 3 extension isn’t working. Things is running and has URL scheme activated, Raycast has the automation rights in system settings. I tried enabling/disabling settings, reinstalling everything in every possible combination I could think of. 

### Steps To Reproduce

1. Environment: 
MacOS 13.3 Beta 3
Raycast 1.48.7
Things: 3.17.3
Latest extension update

Things: Running & URL Scheme activated
MacOS: Automation rights for Raycast on Things is activated

2. Whatever action from the extension I pick, I get the "Things not running" warning and the error message below.

4. Error message: 

Inspection is enabled by default for process or
parent application with deprecated
'com.apple.webinspector.allow' entitlement.
Use 'inspectable' API to enable inspection i...

### Current Behaviour

No interaction between Raycast and Things possible

### Expected Behaviour

interaction between Raycast and Thing

**Comment by loris** [comment]
Hi @misterkrueger, thank you for reporting this. Can you confirm you still have the issue or do you have additional detail?
I am running the exact same version of macOS and Things as you and everything is running fine.

**Comment by misterkrueger** [comment]
Hi @loris, it was one of these once in a while penalties for using beta software. Later in the beta cycle of MacOS 13.3 everything started working again (a few other raycast extensions where also affected). Forgot to close this one. Thanks for your reply.
