### ISSUE TITLE
[API Feature Request] No support for Gifs

### ISSUE THREAD

**Issue by himynameisjonas** [raycast/extensions#522]
Raycast version: 1.26.2

## Description

Gif images shows as still images when rendered with markdown in a `Detail` view

## Steps To Reproduce

1. Render a image tag with a gif url in the markdown prop on a Detail component

## The current behavior
The image shows just the first frame

## The expected behavior
Show all the frames, i.e show the animated gif as a gif and not a still image-

**Comment by unnamedd** [comment]
The support for animated gif was implemented in the version [1.32.0 (2022.04-06)](https://developers.raycast.com/changelog#1.32.0-2022-04-06).

cc @fe9lix @mathieudutour
