### ISSUE TITLE
not sure how to find path logseq

### ISSUE THREAD

**Issue by Holanda73** [raycast/extensions#5222]
### Description

How can I find the path to logseq that needs to be entered in the Raycast extension. I cannot find it in the readme.

**Comment by thomaslombart** [comment]
cc @futantan

**Comment by futantan** [comment]
![CleanShot 2023-04-11 at 19 44 27@2x](https://user-images.githubusercontent.com/6268441/231152982-e7c305c1-efa8-4557-a50d-b15fe66cf7f4.png)

click All graph, you will find the path there
