### ISSUE TITLE
[Brew] Custom brew Executable Path not working

### ISSUE THREAD

**Issue by chrislemke** [raycast/extensions#5225]
### Extension

https://www.raycast.com/nhojb/brew

### Description

Since I am using an M1 Mac I had to change the executable brew path to `/opt/homebrew/bin/brew`. This custom path gets ignored and always falls back to `/usr/local/bin/brew`. Since I also have a brew installation for the old architecture the `Show installed` always shows the brews installed in `/usr/local/bin/brew`.

Please check out
<img width="1728" alt="Screenshot 2023-03-08 at 12 21 01" src="https://user-images.githubusercontent.com/11752694/223702417-2a9daea4-d6f7-42c9-b267-ebf252c1a40b.png">
<img width="1728" alt="Screenshot 2023-03-08 at 12 21 52" src="https://user-images.githubusercontent.com/11752694/223702448-1da87fff-b24c-426c-b99c-4f0b0ae4602c.png">

Maybe I am doing something terribly wrong. Looking forward to your help. 🙂

### Steps To Reproduce

1. Install brew to `/opt/homebrew/bin/brew` - default Apple M1 brew installation
2. Change the _Custom brew Executable Path_ to `/opt/homebrew/bin/brew`
3. Run `Show installed`
4. Should show the brews installed for brew installation

### Current Behaviour
Show installed always shows the brews for the brew installation at: `/usr/local/bin/brew`

### Expected Behaviour
Should show the brews installed for the selected installation.

**Comment by chrislemke** [comment]
Hey!
Any progress concerning this issue?

**Comment by nhojb** [comment]
Hi Chris, yes it should be fixed in the latest version of the extension. Run `Check for Extension Updates`, but you probably have it already.
