### ISSUE TITLE
[Google Workspace] ...allow multiple Google accounts

### ISSUE THREAD

**Issue by Holanda73** [raycast/extensions#5229]
### Extension

https://www.raycast.com/raycast/google-workspace

### Description

The extension can only manage one google account, but it would be good to be able to login to  several google accounts at the same time.

### Who will benefit from this feature?

all Google Workspace users

**Comment by thomaslombart** [comment]
Thanks for reporting but there's arleady an [issue](https://github.com/raycast/extensions/issues/4039) for this use-case 😊
