### ISSUE TITLE
[API Feature Request] add "keywords" attribute to Dropdown Item

### ISSUE THREAD

**Issue by eluce2** [raycast/extensions#523]
I would like to be able to add `keywords` for a form dropdown item so that I can search against other terms without having to put them in the title of the dropdown item.

**Describe the feature and the current behavior/state.**
This would work similarly to the keywords attribute on List Items, but in this case for searching values in a dropdown field.

**Will this change the current api? How?**
No, this could be added as a non-breaking change.

**Who will benefit with this feature?**
In my particular case, I would like to be able to search for a section title and see all the items for that section, but since that may not be the desired use case every time, adding a `keywords` attribute would allow for greater flexibility in dropdown fields for all extension developers

**Any Other info.**

**Comment by mattisssa** [comment]
Hey! Sorry for the late response. This is a really good idea, we don't have this even natively but I'll put it in our feature list!

**Comment by eluce2** [comment]
Could I raise this feature request again? I actually run into this issue quite often. My company adds new harvest projects frequently using codes that never match my search and I can never find them. If this were added, I would be able to search for a company name and have the correct project pull up in the list

**Comment by mattisssa** [comment]
ouch, seems like it has hang out here for quite long. Let me change the feature prior. If it's not tricky to implement, we will introduce it in a one of next releases 👌

**Comment by mathieudutour** [comment]
Added support in v1.40.0
