### ISSUE TITLE
[Things] Add command to copy link to list item to clipboard

### ISSUE THREAD

**Issue by gtg922r** [raycast/extensions#5232]
### Extension

https://www.raycast.com/loris/things

### Description

In addition to "Open in Things..." it would be helpful to have a command to "Copy Link to Clipboard" which would copy the URI to the item to the clipboard, rather than opening the URI to open Things. 

### Who will benefit from this feature?

Anyone who uses links to Things items in their notes, calendar invites, etc

**Comment by andreaselia** [comment]
I'll take a look at this in the morning 😁
