### ISSUE TITLE
[ChatGPT3 Prompt] ...

### ISSUE THREAD

**Issue by therosbif** [raycast/extensions#5236]
### Extension

https://www.raycast.com/denizyoldas/chatgpt3-prompt

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'map')

Et:index.tsx:16:43
Nr:index.js:5:2490
    at ray-navigation-stack
ko:index.js:5:2088
```

### Steps To Reproduce

1. launch the extention

### Current Behaviour

Craches on launch

### Expected Behaviour

doesn't crash

**Comment by denizyoldas** [comment]
I have examined the issue and it is not caused by the code. There seems to be an issue with the source from which we have obtained the prompts list. Therefore, we are unable to retrieve the data. I am awaiting for the problem to be resolved when my opened pull request is approved.

@therosbif
