### ISSUE TITLE
[CleanShot X] ... I don't know how to use this extension as a newbie

### ISSUE THREAD

**Issue by aaron2wh** [raycast/extensions#5240]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

everytime when I launch any cleanshot x command, it prompt below:
未设定用来打开URL cleanshot://capture-window的应用程序。
<img width="260" alt="image" src="https://user-images.githubusercontent.com/43267693/223906669-aca84e57-138e-445d-80ec-c1e3d23ba51b.png">

**Comment by Aayush9029** [comment]
@aaron2wh You can buy license from https://cleanshot.com

or you can use https://www.raycast.com/Aayush9029/screenshot, this uses native screenshot app. 


@raycastbot  close this issue

**Comment by Aayush9029** [comment]
@raycastbot close this issue
