### ISSUE TITLE
[Chinese Character] Update quotes “ ”, ' ' -> 「」『 』or vice versa

### ISSUE THREAD

**Issue by Thud-Concrete** [raycast/extensions#5242]
### Extension

https://www.raycast.com/koinzhang/chinese-character

### Description

As a user, I would like to request an update for quotes during Chinese conversion. Currently, Simplified Chinese uses " " and ' ' for quotes, but I would like to have the option to use the traditional Chinese quotes 「」and 『 』instead. This feature would be particularly useful when converting context that contains a lot of conversation dialog.

It would also improve the readability and clarity of the converted text, making it easier to understand and engage with.

Therefore, I request the development team to consider adding this feature to the system's Chinese conversion process, and provide an option for users to choose between the different types of quotes. Thank you for considering this feature request.

**Comment by koinzhang** [comment]
Hi @Thud-Concrete. Thanks for your feedback, I've submitted a PR #6341 to add the ability to convert simple and traditional quotes.
If you have any other questions, feel free to give me feedback
