### ISSUE TITLE
[ChatGPT3 Prompt] ...

### ISSUE THREAD

**Issue by Konasensei** [raycast/extensions#5245]
### Extension

https://www.raycast.com/denizyoldas/chatgpt3-prompt

#### Error:
TypeError: Cannot read properties of undefined (reading 'map')

Et:index.tsx:16:43
Nr:index.js:5:2490
    at ray-navigation-stack
ko:index.js:5:2088

**Comment by pernielsentikaer** [comment]
There is no content here @Konasensei - could you update the issue?

**Comment by Konasensei** [comment]
@pernielsentikaer omg yes I'm sorry! Updated the description



TypeError: Cannot read properties of undefined (reading 'map')

Et:index.tsx:16:43
Nr:index.js:5:2490
    at ray-navigation-stack
ko:index.js:5:2088

**Comment by denizyoldas** [comment]
@raycastbot close this issue

**Comment by Konasensei** [comment]
Thanks @denizyoldas, works like a charm now.
