### ISSUE TITLE
[Downloads Manager] ...

### ISSUE THREAD

**Issue by Marcfelske** [raycast/extensions#5248]
### Extension

https://www.raycast.com/thomas/downloads-manager

### Description

Cut latest download.
Copy latest download already exists. However, the copy feature requires returning to the downloads folder to delete the file once it's moved to the correct location.

### Who will benefit from this feature?

People who use their downloads folder responsibly (i.e. empty) and move files from the downloads folder to a new destination.

**Comment by thomaspaulmann** [comment]
Do you want to make a PR with this new command?

**Comment by thomaspaulmann** [comment]
Alternatively we could add a `Move...` action in the list, similar to how we have it in the File Search. WDYT?

**Comment by thomaspaulmann** [comment]
Yeah probably best to just have another command. Do you want to add it yourself?

**Comment by thomaspaulmann** [comment]
And servus :-P

**Comment by Marcfelske** [comment]
Hi Thomas,
Good to meet! Wish I was able to add the comment myself. I'm a mech-eng and
substack python, self-taught guy.
