### ISSUE TITLE
[Extension Feature Request] Add configuration to exclude tabs from specific devices

### ISSUE THREAD

**Issue by axsuul** [raycast/extensions#525]
# Extension – [Safari](https://github.com/raycast/extensions/tree/main/extensions/safari)

Author: @loris 

**Describe the feature and the current behavior/state.**

Select which devices tabs are included from (i.e. exclude tabs from other devices). I have an old laptop that is stuck with thousands of iCloud tabs that I don't want included and slows down the rendering of tabs.

**Who will benefit with this feature?**

Anyone with multiple devices.

**Any Other info.**

![CleanShot 2021-12-13 at 17 59 19@2x](https://user-images.githubusercontent.com/187961/145919098-2cc8108d-d670-47d7-a9ec-a791f26451fa.png)

**Comment by loris** [comment]
Hi @axsuul, I might have a look, but honestly the correct way to fix this is on your end: you should remove that old device from your iCloud account (right now, this is not only slowing down your raycast extension, but also your Mac Safari and iPhone Safari which are also listing those tabs)
