### ISSUE TITLE
[Music] Error while adding a track to a playlist

### ISSUE THREAD

**Issue by kevinpardo** [raycast/extensions#5250]
### Extension

https://raycast.com/fedevitaledev/music

### Description

I suspect this is due to the fact that my system language is french, and so "Library" is called "Bibliothèque" on my computer.

Here is the stack trace :

Error: Command failed with exit code 1: osascript -e 
tell application "Music"
	set theName to name of current track
	set theArtist to artist of current track
	set theAlbum to album of the current track
	set existingTracks to get tracks of source "Library" whose name is theName and artist is theArtist and album is theAlbum
	
	if (count of existingTracks) = 0 then
		set theCount to count of tracks of source "Library"
		duplicate current track to source "Library"
		repeat while theCount = (count of tracks of source "Library")
			delay 1
		end repeat
	end if
	
	set theTrack to first track of source "Library" whose name is theName and artist is theArtist and album is theAlbum
	duplicate theTrack to playlist "Rock or Die"
end tell
 
177:271: execution error: Erreur dans Music : Il est impossible d’obtenir every track of source "Library" whose name = "Make This Easy" and artist = "The Blue Stones" and album = "Hidden Gems". (-1728)
    at S0 (/Users/kevin/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:59)
    at /Users/kevin/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:10477
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async qc (/Users/kevin/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:38131)

### Steps To Reproduce

When typing the "Add to playlist" command while a track is playing in the "Music" app on mac.

### Current Behaviour

Throws the error above

### Expected Behaviour

Adds the music to the playlist

**Comment by Rawnly** [comment]
Hi Kevin, you're right, that's the reason why it throws an error. Unfortunately seems like Music library is language sensitive. I'm still figuring out how to get around it

**Comment by kevinpardo** [comment]
Thanks for the reply!

I'm sure you've considered that option, but if not : the word "Library" could be replaced with a variable that detects the system languages and replaces it with the appropriate word. The word could be picked from a dictionary (like a json file maybe?) that stores the "Library" translation for all languages (or at least the most used?).

Not sure how practical or feasible it is, but hope it helps!

**Comment by Rawnly** [comment]
> Not sure how practical or feasible it is,
At the current state of the code I think it can result in a big refactor, I'll try later today to see if I can do something 👍

**Comment by Rawnly** [comment]
> At the current state of the code I think it can result in a big refactor

Smaller than I thought! Fixed in the latest PR 😅

**Comment by kevinpardo** [comment]
Awesome!
Thanks a lot, it's pretty cool of you to have fixed that so fast!
