### ISSUE TITLE
[Google Workspace] Search Gmail

### ISSUE THREAD

**Issue by trankien386** [raycast/extensions#5251]
### Extension

https://www.raycast.com/raycast/google-workspace

### Description

Since this extension already allows me to search Google Drive, it would be perfect if it also allows me to search Gmail. Besides, i haven't seen any email searching extensions on extension store. I think that kind of extension will benefits everyone.

**Comment by thomaslombart** [comment]
Searching Gmail sounds like a neat addition indeed. I'll discuss this with the team to explore the feasibility and implications of implementing this feature. I'll keep you updated and will get back to you on what we'll decide.

**Comment by thomaslombart** [comment]
Hey @trankien386, just wanted to let you know that after talking with the team, we think integrating Gmail into the Google Workspace extension might not be the best idea. We're worried about the Gmail scope and don't want users to feel like the extension has access to too much data.

 Plus, we've got limited resources for extensions. Adding Gmail features like creating/sending/searching mails, drafts, attachments, labels, and threads would be a pretty big task.

On the bright side, someone in the community started building an extension that seems like what you're looking for: https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1679232205848529. Maybe you could sync up with him? 😊
