### ISSUE TITLE
[Trello] Search Todos doesn't work

### ISSUE THREAD

**Issue by trankien386** [raycast/extensions#5255]
### Extension

https://www.raycast.com/ChrisChinchilla/trello

### Description

While Search Boards and Fetch Todos work perfectly, i can't search any cards using Search Todos. Nothing shows up when i typed keywords.

Additionally, Setting Due Date in Create a Todo makes no difference. After i choose a due date and create a card, i check on trello and i see that the card is created but there isn't a due date.

I wonder if the extension works normal for other people.

**Comment by Zhuoli** [comment]
I have the same problem, I'm new to raycast and just installed this extension yesterday, with no luck this google translate extention seems frozen there when I pressed enter and expection a translation.

**Comment by ChrisChinchilla** [comment]
Something got reverted it seems. @trankien386 could you create a separate issue for the date problem? Thanks :)

**Comment by trankien386** [comment]
No problem. Thanks for looking into it.
