### ISSUE TITLE
[Github Enterprise] Create issue doesn't allow searching repo beyond initial list returned

### ISSUE THREAD

**Issue by simonkotwicz** [raycast/extensions#5256]
### Extension

https://www.raycast.com/Kinbaum/github-for-enterprise

### Description

Creating an issue returns a predefined list of repositories to choose from and doesn't always contain the repo that you want to make an issue for.

### Steps To Reproduce

1. Use the create issues command
2. Try and search for a repo that is not in the dropdown list

### Current Behaviour

No results show up.

### Expected Behaviour

The extension should take your query and fetch a new list of repos from Github.

**Comment by simonkotwicz** [comment]
is this extension still being maintained?

**Comment by Kinbaum** [comment]
@simonkotwicz I haven’t had any time to keep up with this as of late, but will still happily take and review contributions

**Comment by LunaticMuch** [comment]
@simonkotwicz I can have a look. How many repos do you have there? Gut feeling is that if you say 1000, the list might not contain all of them.

**Comment by simonkotwicz** [comment]
@LunaticMuch I don't own 1000 repositories but I'm part of multiple orgs with 1000s of repos. I think the search query should be used for searching repositories when there are no matches in the cached list (or something to that effect).
