### ISSUE TITLE
[Extension Feature Request] Show domain name instead of author in HN Frontpage Extension

### ISSUE THREAD

**Issue by plibither8** [raycast/extensions#526]
# Extension – [Hacker News](https://github.com/raycast/extensions/tree/main/extensions/hacker-news)

Author: @thomaspaulmann

**Describe the feature and the current behavior/state.**

Currently, each story entry shows the story submitter's HN username. This by itself is not informative at all to the submitted story. Moreover, highlighting the submitter might introduce a bias in clicks/upvotes if the submitter is someone popular (which I believe you'd agree goes against the HN philosophy).

Instead, we can show the domain name of the submitted story. I would love to know which website I am going to be directed to before pressing enter - is it GitHub, a news website, Wikipedia? HN does this too, and would be a bit consistent then with how they present their entries.

![CleanShot 2021-12-14 at 14 55 47@2x](https://user-images.githubusercontent.com/31861755/145970738-ee5cb81b-97ec-49aa-913d-dc6d3d122a38.png)

**Who will benefit with this feature?**

Everyone, I guess! 😄 

**Any Other info.**

I'd love to take this if possible, or engage in more discussion. :)

**Comment by thomaspaulmann** [comment]
@plibither8 could be neat. Do you want to submit a PR?

**Comment by plibither8** [comment]
Thanks for the reply @thomaspaulmann! Sure thing, would love to take it up. Will probably get some time this weekend, hope to complete it then 😄
