### ISSUE TITLE
[Visual Studio Code - Project Manager] Open in Terminal overrides environment variables such as NODE_ENV

### ISSUE THREAD

**Issue by regohiro** [raycast/extensions#5260]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

When I open the terminal using Visual Studio Code - Project Manager extension, it overrides the default environment variables. However, this only happens when I open it on a fresh terminal. If I open it on an existing terminal, it won't override. 
<img width="816" alt="221386036-fe32876a-9637-486b-affb-942f8163f6f6" src="https://user-images.githubusercontent.com/62818999/224198501-f9dc667a-7af9-4cf1-a842-392f996d8c0e.png">

Related to https://github.com/raycast/extensions/issues/229

### Steps To Reproduce

1. Make sure the Terminal app (or iTerm) is not running
2. Open raycast and use the extension to open terminal
3. On the terminal, run `printenv` and check the environment variable 

### Current Behaviour

The extension overrides the environment variables (see description).

### Expected Behaviour

It shouldn't override.

**Comment by MarkusLanger** [comment]
Hello @regohiro,

Thanks for the information. I created a branch with a fix https://github.com/MarkusLanger/extensions/tree/5260
Could you check if it works for you?

**Comment by regohiro** [comment]
Tested locally and works! Thanks for the fix!

**Comment by pernielsentikaer** [comment]
This is now merged
