### ISSUE TITLE
[Timezone Converter] ...

### ISSUE THREAD

**Issue by adrianmldn** [raycast/extensions#5263]
### Extension

https://www.raycast.com/joao.mainka/raycast-timezone-converter

### Description

America - Utah time zone

**Comment by joaom182** [comment]
Hi @adrianmldn what is the issue? Could you describe it better?

**Comment by adrianmldn** [comment]
Hi! Sorry. I should have explained better. The issue is that is no America - Utah time zone in the list.

**Comment by DannySeidel** [comment]
Hi @adrianmldn there is no America/Utah timezone. The extension uses the official IANA timezone database. Just use a city within the same time and a existing timezone like America/Denver. If you want look for yourself, here is a list with all available timezones: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by DannySeidel** [comment]
@raycastbot close this issue
