### ISSUE TITLE
[Visual Studio Code - Project Manager] Add project from Raycast

### ISSUE THREAD

**Issue by Martin-Gonzalez90** [raycast/extensions#5270]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

Hi!
Would be nice to be able to add projects from raycast.

Action could "Add Project"
Receives a path
It saves it in the json file project manager uses.

Would be possible to do it?

**Comment by MarkusLanger** [comment]
Hi @Martin-Gonzalez90 ,

It should be possible to implement this. Besides the path, it should also be possible to define a name and the tags.
The tags should be selectable from those stored so far.
So there is a lot to do. I don't know if this is used by many. I'll keep it in mind as soon as I find the time.

**Comment by MartinGonzalez** [comment]
Also I can try to make it, so I can practice extensions :D
I was doing something similar until I met this one
