### ISSUE TITLE
[Linear] Support for multiple workspaces / Switching workspaces

### ISSUE THREAD

**Issue by AlbinUllerstam** [raycast/extensions#5272]
### Extension

https://www.raycast.com/linear/linear

### Description

**Current behaviour**

- When I connect my linear account to raycast I can only access one of the two workspaces on my account.<img width="251" alt="CleanShot 2023-03-10 at 12 09 40@2x" src="https://user-images.githubusercontent.com/100718031/224301740-1634b789-be4d-4b95-8f9a-d35a49df5fc2.png">

**Proposed behaviour**

- The ability to quickly switch between workspaces

### Who will benefit from this feature?

- People who use multiple workspaces

**Comment by thomaslombart** [comment]
Unfortunately, Linear's API is bound to a single workspace so it's not possible to switch between workspaces without logging out from Raycast. This would be feasible if multiple instances of a single extension would be supported in Raycast (cf https://github.com/raycast/extensions/issues/269) but it's not the case yet.

**Comment by thomaslombart** [comment]
Closing in favor of https://github.com/raycast/extensions/issues/4299
