### ISSUE TITLE
Open In Visual Studio Code

### ISSUE THREAD

**Issue by hrbrmstr** [raycast/extensions#5277]
### Extension

https://github.com/raycast/extensions/tree/3746067740d57d122aa62bd2dc7f8345369b957d/extensions/open-in-visual-studio-code

### Description

In this array:

https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cfeature+request&template=extension_feature_request.yml&title=%5BExtension+Name%5D+...

it would be helpful for those who use Visual Studio Code - Insiders edition to be able to launch that. Doing so only requires adding that app to the array on those lines.

### Who will benefit from this feature?

Everyone who uses Visual Studio Code - Insiders

### Anything else?

This is the change:

```
      "default": "Visual Studio Code",
      "data": [
        {
          "title": "Visual Studio Code",
          "value": "com.microsoft.VSCode"
        },
        {
          "title": "Visual Studio Code - Insiders Edition",
          "value": "com.microsoft.VSCodeInsiders"
        },
        {
          "title": "VSCodium",
          "value": "com.vscodium"
        }
      ]
    }
  ],
```

**Comment by thomaspaulmann** [comment]
Can you make a PR?
