### ISSUE TITLE
[iTerm] open iTerm2 profile

### ISSUE THREAD

**Issue by sunrisewestern** [raycast/extensions#5283]
### Extension

https://www.raycast.com/ron-myers/iterm

### Description

open iTerm2 profile from raycast

### Who will benefit from this feature?

iTerm2 users

**Comment by ron-myers** [comment]
@sunrisewestern  do you mean that you would like to open a non-default profile via Raycast?

**Comment by sunrisewestern** [comment]
Yes. Currently I have to open iTerm and then open a profile. It would be much easier if I can directly open a profile from raycast.

**Comment by sunrisewestern** [comment]
Here's a work-around using raycast command.
https://github.com/sunrisewestern/raycast-script-command/blob/a1510cfeaffb60aba34f81e2e5d407ff449e579e/open-iterm2-profile.applescript
