### ISSUE TITLE
[System Monitor] ...

### ISSUE THREAD

**Issue by crisneda** [raycast/extensions#5287]
### Extension

https://www.raycast.com/hossammourad/raycast-system-monitor

### Description

It indicates everything in real time, except RAM usage.

![image](https://user-images.githubusercontent.com/16434211/224426238-4f1de23e-861e-4137-be1d-5ab52d54a48d.png)

**Comment by pernielsentikaer** [comment]
Can you check if this is better now @crisneda

**Comment by crisneda** [comment]
Yep, it's seems solved.

**Comment by crisneda** [comment]
Yep, it's seems solved.
