### ISSUE TITLE
[Coda Bookmarks Search] ...

### ISSUE THREAD

**Issue by joesteinkamp** [raycast/extensions#5296]
### Extension

https://www.raycast.com/allienx/coda-bookmarks-search

### Description

It would be great to be able to search across all documents, pages, and workspaces. To start, if only a single workspace would still be very powerful. 

### Who will benefit from this feature?

All Coda users

**Comment by allienx** [comment]
@joesteinkamp I will have to take a look at the coda api to see what's possible.

Just for clarification, I built this extension to only search for URLs stored in a table. It's not a global search.

So you'd like to be able to search for URLs in tables across all your documents/pages/workspaces? Right now the extension is pretty simple, you have to tell it what table you want to search. I will have to see if it's possible to be smarter and automatically find tables that have URLs.

**Comment by joesteinkamp** [comment]
Yeah to clarify I previously used a tool called Slapdash to search across all my Coda docs and pages and quickly navigate to the right doc and page. It's definitely a lot more featureful then what you have so far but Raycast told me to reach out to you since you already are using Coda's API.
________________________________
