### ISSUE TITLE
[Visual Studio Code Recent Projects] ...

### ISSUE THREAD

**Issue by rollokd** [raycast/extensions#5299]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

I would like the ability to open files I have no opened before in vscode, I use PathFinder instead of Finder so the open from finder command doesnt work for me. Either way it would nice if it was possible to have a command that searches all the files and folders on your system like the File Search UI within Raycast that when you action a folder/file it opens in VSCode. The current system only allows you to open a folder I have already opened in VSCode and the option to open through finder defeats the point of raycast as it requires about as many steps as it would take to actually open the file manually in vscode through finder. Raycast should be able to do it all through the command line.

### Who will benefit from this feature?

Everyone who is using this extension already will at some point need to open a new file/folder and the current implementation is cumbersome and doesn't work for other file management applications like PathFinder

**Comment by macbookandrew** [comment]
@rollokd agreed, it would be nice, but that also seems out of scope for the original purpose of this extension.

For what it’s worth, the File Search command does have an “Open With” command (<kbd>⌘</kbd> + <kbd>O</kbd>) that I frequently use to accomplish this.

**Comment by thomaspaulmann** [comment]
The extension already includes the ["Open With Visual Studio Code" command](raycastinternal://extensions/thomas/visual-studio-code/open-with-vscode). With the command, you can select a folder or file in the Finder and then run the command to open it in VS Code. 

I hope that helps. Alternatively there is also the ["Open With App" extension](https://www.raycast.com/fturcheti/open-with-app) which can come in handy to open files/folders.
