### ISSUE TITLE
[Extension Feature Request] Toggle "Low Power Mode" of Battery Preferences

### ISSUE THREAD

**Issue by chrisma** [raycast/extensions#530]
# Extension – [System](https://raycast.com/extensions/system/)
Author: Raycast authors

**Describe the feature and the current behavior/state.**
The **System** extension already provides actions to e.g. restart or set the volume. It would be nice to be able to set/toggle the "Low Power Mode" of MacOS using Raycast. It is part of the Battery preference pane. 
Currently, no "toggle MacOS Low Power Mode" command is available in Raycast.

<img width="600" src="https://user-images.githubusercontent.com/1652117/146204442-6eb6f80e-61fc-49e9-b2eb-9fb9a58abb54.png">
<img width="600" src="https://user-images.githubusercontent.com/1652117/146204784-02f08689-f890-4976-9d05-54864bbe01d9.png">

**Who will benefit with this feature?**
Users who want to extend battery life of their laptops, but don't want to dig deep in the preferences.

**Comment by chrisma** [comment]
Seems that there are already some ideas on how to trigger LPM programmatically: https://www.reddit.com/r/shortcuts/comments/qi3nz1/turn_low_power_mode_onoff_on_mac/

In particular the following returns the current LPM state (requires `sudo, unfortunately): 

```bash
pmset -g | grep lowpowermode | awk -F' ' '{ print$2 }'
```

**Comment by mattisssa** [comment]
Hey @chrisma! I think this can be done better by creating a separate extension for this, like "Battery Controls" where it would be possible to do.
Probably now is the perfect time to [build one](https://www.raycast.com/developers) 😉

**Comment by chrisma** [comment]
> I think this can be done better by creating a separate extension for this, like "Battery Controls"

Thanks for the reply! Important to know whether additional "system commands" should be integrated into the built-in Raycast System extension, or be supplemented by additional separate extensions by the community.

The scope of extensions could be the individual screens of the MacOS System Preferences, i.e. `Battery`, `Bluetooth`, `Displays`.

<img width="663" alt="image" src="https://user-images.githubusercontent.com/1652117/146351291-73ed45df-4075-4bca-a05c-a1e5fa012f23.png">
