### ISSUE TITLE
[Single Disk Eject] Eject all disk or a group of disk

### ISSUE THREAD

**Issue by StevenLi-DS** [raycast/extensions#5300]
### Extension

https://www.raycast.com/johndturn/single-disk-eject

### Description

Eject all disks at once, or let users define a group of disks they want to eject one by one.

### Who will benefit from this feature?

It would be very useful if you connect your MacBook to a dock with many external hard drives. If I can define a group of hard drives that I want to eject at once when I disconnect my MacBook from the dock, it would be very convenient.

**Comment by johndturn** [comment]
@StevenLi-DS interesting proposal. Any thoughts on what you'd like the user experience to look like in configuring these options? I'm inclined to think that this might be better suited as a separate extension or a combination of existing commands and this extension. 

Raycast comes with a pre-built system command for ejecting all disks, which you could use. Then you could use this extension for single ejects. Would that satisfy your use case?

**Comment by StevenLi-DS** [comment]
@johndturn thanks. I didn't realize that there is a ejecting all disks command 😅.
