### ISSUE TITLE
[Zoom] Zoom improvement ideas

### ISSUE THREAD

**Issue by StevenLi-DS** [raycast/extensions#5302]
### Extension

https://www.raycast.com/raycast/zoom

### Description

1. Toggle for auto-copying the invitation info (link) to my clipboard right after scheduling a meeting. Right now, you have to act very fast before CMD + T disappears at the bottom so that you can copy the link.

2. I always find Zoom generates way too many texts, and I always have to delete some before sending the invitation to someone, but right now you can only copy a link via the extension. If you need to send a Zoom invitation to someone, I believe it would be essential for that person to know the time and duration. It would be great if you can auto-copy the following info after scheduling. 
```
Date: Mar 11, 2023
Time: 09:00 PM Eastern Time (US and Canada)
Topic: Zoom meeting
Duration: 60 mins
Link: https://your-zoom-link
```

3. The default time starts from 6 am .... a bit early for a Zoom meeting. It would be nice if you can pin a regular time in the dropdown menu, or maybe add more options in the dropdown.
<img width="750" alt="cs-cjgoron2_2x" src="https://user-images.githubusercontent.com/33796896/224520314-b745f3de-c1ee-4199-b147-c3c1225ae5dd.png">

4. The `Start Time` field supports natural language input, but `Duration` does not.... so maybe the following UI is more clear?  
![cs-mb9d1y7h_2x](https://user-images.githubusercontent.com/33796896/224519948-b2688be6-a4a8-490b-ad53-8f90d15550e6.png)

**Comment by thomaslombart** [comment]
I'll discuss these use cases with the team and I'll get back to you on these 😊

**Comment by StevenLi-DS** [comment]
Thanks, @thomaslombart, I'm just too lazy to type `tomorrow 3pm`😅

**Comment by thomaslombart** [comment]
Hey there! I had a chat with our team about the first two improvements you suggested (auto-copying the invitation link and adding more meeting info) and we won't be working on them since they're a bit too specific. However, feel free (or other community members) to give it a try and submit a pull request. We'll happily review it. Thanks for your understanding! 🙌

**Comment by StevenLi-DS** [comment]
@thomaslombart Thanks for getting back on this. Could you guys at least consider delaying the disappearance CMD + T? or not just make it stay at the bottom of the ui?

**Comment by thomaslombart** [comment]
Well, changing this would have an impact on all extensions and it's something most users are fine with. If you need to have the scheduling link automatically copied, note that you could achieve this with the extensions preferences. Here are some pointers on how to do it:

1. Add a new checkbox preference in `Schedule Meeting` command via `package.json` (let's call-it `autoCopyMeetingLink` )
2. In `extensions/zoom/src/components/CreateMeetingForm.tsx`, after the meeting is scheduled, you can add an `if` statement to check if the preference is enabled and if yes, copy the link, thanks to the `Clipboard` API.

Let me know if you need further help with that.
