### ISSUE TITLE
[Trello] Can't set Due Date in Create a Todo

### ISSUE THREAD

**Issue by trankien386** [raycast/extensions#5313]
### Extension

https://www.raycast.com/ChrisChinchilla/trello

### Description

I set a due date when i create a card. Then I check on Trello to see that the card is created but there isn't a due date associated with it.

**Comment by andreaselia** [comment]
It looks like @ChrisChinchilla isn't passing through the description or due date to the creation of tasks API endpoint from what I can tell having a quick look through the code.

**Comment by ChrisChinchilla** [comment]
@andreaselia Sheesh, sure I tested thank, will look now, thanks!
