### ISSUE TITLE
[Google Workspace] Wrong account is used for Google Spreadsheets

### ISSUE THREAD

**Issue by joesteinkamp** [raycast/extensions#5315]
### Extension

https://www.raycast.com/raycast/google-workspace

### Description

When using the Create Google Spreadsheet it's the only Google Workspace file that's missing "?authuser=" when the URL loads causing the wrong account to be used for folks that don't want to create a sheet on their default Google Account.

Doc, Slides, and Forms all work correctly. 

For example, I'm logged into my personal Google account as my default account in Chrome but I like to use work Google account for Raycast. When I create a sheet with that Raycast command, it creates the sheet for my default (personal) account instead of my work account that I'm logged into on Raycast. 

### Steps To Reproduce

1. Log into two Google accounts
2. Log into your No. 2 Google account in Raycast
3. Use "Create Google Spreadsheet" command

### Current Behaviour

Creates spreadsheet under No. 1 Google account

### Expected Behaviour

Creates spreadsheet under No. 2 Google account that's logged into Raycast

**Comment by thomaslombart** [comment]
Oh, nice catch. This one has been forgotten!

**Comment by thomaslombart** [comment]
Thanks for reporting that up. Would you like to work on it? As far as it seems, it's a matter of adding the `authuser` parameter to [this line ](https://github.com/raycast/extensions/blob/d5e8413792d71457f9132a12fa5ba8357c1bf629/extensions/google-workspace/src/components/FileListItem.tsx#L164) like it's been done [here](https://github.com/raycast/extensions/blob/738d76ef6f7bc275ac34bf7540f0fcc9ac94f606/extensions/google-workspace/src/components/FileListItem.tsx#L40).

**Comment by jbjanot** [comment]
Thanks for your feedback.
[I just contributed to the extension](https://github.com/raycast/extensions/pull/12944).
BTW the process is very clear, and the workflow is working like a charm, congrats to the team.
