### ISSUE TITLE
[Deepcast] Support more languages

### ISSUE THREAD

**Issue by 9bow** [raycast/extensions#5323]
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

Recently [DeepL announced that they're supporting some more languages like Korean and Norwegian](https://www.deepl.com/en/blog/welcome-korean-and-norwegian).

Actually, DeepL is now supporting 29 languages, but only Deepcast only supports 25 languages.

* [Languages currently DeepL supports](https://www.deepl.com/docs-api/translate-text/translate-text/) (from `source_lang` param)
```
BG - Bulgarian
CS - Czech
DA - Danish
DE - German
EL - Greek
EN - English
ES - Spanish
ET - Estonian
FI - Finnish
FR - French
HU - Hungarian
ID - Indonesian
IT - Italian
JA - Japanese
KO - Korean
LT - Lithuanian
LV - Latvian
NB - Norwegian (Bokmål)
NL - Dutch
PL - Polish
PT - Portuguese (all Portuguese varieties mixed)
RO - Romanian
RU - Russian
SK - Slovak
SL - Slovenian
SV - Swedish
TR - Turkish
UK - Ukrainian
ZH - Chinese
```

* [Languages currently Deepcast supports](https://github.com/raycast/extensions/blob/7025e822b8e0bda761c2af13b2e2b4ce6e00bb53/extensions/deepcast/src/utils.ts#L35-L59)
```
  BG: "Bulgarian",
  ZH: "Chinese",
  CS: "Czech",
  DA: "Danish",
  NL: "Dutch",
  EN: "English",
  ET: "Estonian",
  FI: "Finnish",
  FR: "French",
  DE: "German",
  EL: "Greek",
  HU: "Hungarian",
  IT: "Italian",
  JA: "Japanese",
  LV: "Latvian",
  LT: "Lithuanian",
  PL: "Polish",
  PT: "Portuguese",
  RO: "Romanian",
  RU: "Russian",
  SK: "Slovak",
  SL: "Slovenian",
  ES: "Spanish",
  SV: "Swedish",
  UK: "Ukrainian",
```

If you have a reason for excluding these languages, please let me know.
```
ID - Indonesian
KO - Korean
NB - Norwegian (Bokmål)
TR - Turkish
```

If not, I suggest adding them. :)

### Who will benefit from this feature?

Those who use unsupported languages - Indonesian, Korean, Norwegian, Turkish.

(FYI, as a native Korean user, I would take benefit from this feature, too. 😄)

### Anything else?

Please review adding more languages first to make sure it makes sense.
If you're short on time, please let me know. Then I’ll try to create a pull request about it.

**Comment by MonsterDeveloper** [comment]
Hey! Thanks for noticing that! I've updated the extension to include these 4 languages (see PR #5717).

So I guess the issue can be marked as resolved.

**Comment by 9bow** [comment]
Thanks :)
