### ISSUE TITLE
[My Daily Log] Cloud Notes API like Noition

### ISSUE THREAD

**Issue by ViGeng** [raycast/extensions#5326]
### Extension

https://www.raycast.com/frugoman/my-daily-log

### Description

It would be a huge improvement if the extension replaces the local log file with cloud notes api like notion.

### Who will benefit from this feature?

My Daily Log users,
Cloud Notes users.

**Comment by frugoman** [comment]
Yeah I think it'd be beneficial to share logs across macbooks sharing maybe the same raycast account.

I don't know if raycast have such APIs to fetch the user id or something like that, but can look into it

It's not necessary a Notes app, it's intended as a log more than anything.

**Comment by frugoman** [comment]
@ViGeng This functionality is kind of already supported, as you can modify the folder in where the logs are stored. You can change the location to be under, for example, your iCloud folder (or Dropbox, Google Drive, etc).
I'll close this issue for now

**Comment by frugoman** [comment]
@raycastbot close this issue
