### ISSUE TITLE
[Spotify Controls]  Option to connect to different device

### ISSUE THREAD

**Issue by wtiann** [raycast/extensions#5328]
### Extension

https://www.raycast.com/thomas/spotify-controls

### Description

Can you add a feature to play on a different device?  It'll list all available devices and the user can select which one to play on.

**Comment by thomaspaulmann** [comment]
@peduarte works on some updates to the Spotify extension and might tackle that one as well.

**Comment by peduarte** [comment]
It's happening, but as part of Spotify Player. We're potentially going to merge them. Still TBD.

<img width="395" alt="(ಠ ›ಠ) — @peduarte — q951BQPD001337@2x" src="https://user-images.githubusercontent.com/372831/227023794-8f448a53-d14b-43a8-896e-452833eba546.png">
<img width="750" alt="(ಠ ›ಠ) — @peduarte — okrXWIst001338@2x" src="https://user-images.githubusercontent.com/372831/227023840-b3d3dbc0-b3e5-43a6-858e-ecbd5d2d9e4c.png">
