### ISSUE TITLE
[Postman] ...

### ISSUE THREAD

**Issue by Moha-Mahdhour** [raycast/extensions#5340]
### Extension

https://www.raycast.com/tarikyildizci/postman

#### Error:
```
ue: request to http://127.0.0.1/blog failed, reason: connect ECONNREFUSED 127.0.0.1:80

ClientRequest.<anonymous>:index.js:108:10
ClientRequest.emit:node:events:513:28
ClientRequest.emit:node:domain:489:12
Socket.socketErrorListener:node:_http_client:494:9


```

### Steps To Reproduce

use raycast and then try to send a request

### Current Behaviour

doesn't send a request and shows that there is a bug and an error

### Expected Behaviour

Send a request to the api

**Comment by tarikyildizci** [comment]
hey @Moha-Mahdhour , hope ypou're doing well. Could this be a problem about your port? it seems you are trying to send a request to :80, if that is correct you can send me the details and I can have a look. Have a good day 🙂
