### ISSUE TITLE
[Jira Beta] Error shows up after ticket creation

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#5349]
### Extension

https://www.raycast.com/raycast/jira-beta

### Description

This error shows up after I create a ticket. The ticket is correctly generated.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/5382443/225000505-9a3798ec-bd63-415e-85bf-feaf7204bfab.png">

**Comment by thomaslombart** [comment]
Could you share a recording? I can't reproduce it. The error normally shows when the field is empty, required an you focus on another field.

**Comment by FezVrasta** [comment]
I can't consistently reproduce it, it looks like after I create the ticket, it attempts to submit the form again, resulting in the error above. It may be some kind of race condition or network related issue.

**Comment by FezVrasta** [comment]
Ah, I figured it out. It happens if you click to open the menu that shows up after an issue is created so that you can copy the ticket ID.

**Comment by thomaslombart** [comment]
Coming back to that problem, that's actually something expected. When you click on the success message, you lose the focus on the summary field which is a required one, so the error message shows up.
