### ISSUE TITLE
[Extension Bug] Buildkite

### ISSUE THREAD

**Issue by gtramontina** [raycast/extensions#535]
# Extension – [Buildkite](https://github.com/raycast/extensions/tree/main/extensions/buildkite)

Author: @mskelton

## Description

"Search Pipelines" fails to load. Here's a copy of the error:
```
TypeError: Cannot read properties of null (reading 'pipelines')

xo:search-pipelines.js:50:78

---
47:     }
48:   }
49: }
50: `;function xo(){let{org:a}=(0,or.getPreferenceValues)(),[n,i]=(0,No.useState)(""),l=nr([a,n],{query:Li,errorMessage:"Could not load pipelines",variables:{org:a,search:n}})?.organization.pipelines.edges??[];return _jsx(or.List,{isLoading:l.length===0,searchBarPlaceholder:"Filter pipelines by name...",onSearchTextChange:h=>i(h),throttle:!0},_jsx(Qr,{title:"Favorites",pipelines:l.filter(({node:h})=>h.favorite)}),_jsx(Qr,{title:"All pipelines",pipelines:l.filter(({node:h})=>!h.favorite)}))}0&&(module.exports={});
51: 
---

    at ray-navigation-stack
nm:index.js:24:10558
al:index.js:24:10663
Is:index.js:24:9779
QO:index.js:24:8740
    at ray-root
Ef:index.js:24:10083
```

## Steps To Reproduce

1. Setup API Token
2. Run "Search Pipelines" command

**Note**: this could be very well related to the permissions attached to the token, which I failed to find the required permissions documented. Perhaps improving the initial setup and/or add a readme note listing the required permissions could help.

## The current behavior

"Something went wrong" screen.

## The expected behavior

I could search/browser my existing pipelines.

### Raycast version
Version: `1.26.2`

**Comment by mskelton** [comment]
@gtramontina Did you enable GraphQL API Access for the token?

**Comment by gtramontina** [comment]
I did… I even gave (all?) rest read permissions as per image below.

<img width="646" alt="Screen Shot 2021-12-16 at 1 26 43 pm" src="https://user-images.githubusercontent.com/374635/146296769-80db5064-4702-40a5-a14d-8abf219186d0.png">

**Comment by mskelton** [comment]
Could you double check that the org name you added to your settings is correct?

**Comment by gtramontina** [comment]
Ah! I had used the "display name", which contains uppercase characters. Using the org name from the URL worked fine. Thanks!

So is GraphQL access enough for this plugin?
Cheers!

**Comment by mskelton** [comment]
Yep, GraphQL access is all you need.  Glad you got it fixed!
