### ISSUE TITLE
[My Daily Log] Fix timestamp for entries to zero-padded minutes/seconds

### ISSUE THREAD

**Issue by urbansheep** [raycast/extensions#5355]
### Extension

https://www.raycast.com/frugoman/my-daily-log

### Description

Current version of the extensions inserts timestamps without extra formatting, which leads to strange looking strings like `9:1:5` (instead of `9:01:05` or `09:01:05`).

I fixed it at my local fork by adding `.toString().padStart(2, '0')` to minutes and seconds in the getHourAndMinute(), but maybe there's a better way.

It would be ideal if the string formatting was customizable (time/date separators, seconds or no seconds, markdown decorations like italic/bold, separator between the timestamp and the entry text itself). But having correct minutes/seconds formatting is the major fix for the daily use.

**Comment by frugoman** [comment]
@urbansheep Hi! thanks for raising this! could you attach a screenshot? I do not see that behaviour on my end

**Comment by urbansheep** [comment]
Well, switching over to json definitely makes it more flexible (and solves the issue with formatting), but now daily log became raycast-bound.

Previous approach (appending a line to markdown file) allowed me to use it as way to update my daily log in the Obsidian vault. It seems I will have to find another way to manage this if I don't want to edit daily log json file by hand (and I don't).
