### ISSUE TITLE
[Home Assistant] Error: Protocol "http:" not supported. Expected "https:"

### ISSUE THREAD

**Issue by chrisdrackett** [raycast/extensions#5358]
### Extension

https://github.com/raycast/extensions/blob/ea0de2a3c9ac5822f89e358d1d1d93cb704637b9/extensions/homeassistant/README.md

### Description

Recently (not sure when) I found that I could not interact with my Home Assistant entities anymore without getting the error:

> Error: Protocol "http:" not supported. Expected "https:"

I assume this is because I was using the local IP of my HASS server, which by default is only `http`. I currently have a reverse proxy setup, so it was a pretty easy fix for me, but for less technical users this might be difficult to setup I would assume. My gut would be to allow `http` as that is all home assistant support (as far as I can tell) in its default configuration.

### Steps To Reproduce

1. setup home assistant with a http url.
2. attempt to change an entity via raycast
3. error!

### Current Behaviour

nothing happens, get an error.

### Expected Behaviour

command goes through.

**Comment by rspeicher** [comment]
Seeing this on my instance as well.

**Comment by rspeicher** [comment]
Confirmed reverting ea0de2a3 from https://github.com/raycast/extensions/pull/4906 resolves the error.

@ofalvai Do you have some time to see if you can update your fix to still support non-HTTPS installs?

**Comment by tonka3000** [comment]
Hey @rspeicher ,

I will fix that.

**Comment by tonka3000** [comment]
@rspeicher @chrisdrackett #5385 should fix the issue. You can try it out.

**Comment by ofalvai** [comment]
Hey @tonka3000, thank you for the quick fix and sorry about the issue. I can confirm the latest version still works on my HTTPS setup too!

**Comment by tonka3000** [comment]
Hey @ofalvai . No big deal, bugs happen. Thanks for making the PR for my extension.
