### ISSUE TITLE
[Linear] Search Issue search results recently worse

### ISSUE THREAD

**Issue by lightbody** [raycast/extensions#5371]
### Extension

https://www.raycast.com/linear/linear

### Description

I'm a *diehard* Raycast + Linear extension user. My use case is: I'm the co-founder of a small startup[1] and I handle ~100 support tickets every day. Often I spend time linking support chats in Intercom to Linear issues, and I've bound ctrl-shift-s to the Linear Search action.

Recently I've noticed the quality of the search results has gone way down when searching through the Linear extension.

Here are the results for the search for "things 3".

<img width="573" alt="image" src="https://user-images.githubusercontent.com/50803/225316872-433127d3-c2bf-40f7-a966-f8bac9e02852.png">

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/50803/225317235-7106663a-a387-40bf-b18f-6bd98677c134.png">

I can't quite explain what is wrong, but it has definitely become a lot less useful and I'm having to change my workflow to bypass Raycast :(

[1] https://reclaim.ai/ - try it :) We're hoping to launch our own Raycast extension soon!

### Current Behaviour

Search results that don't seem to be very helpful at all.

### Expected Behaviour

Search results that match what I get when searching natively in Linear.

**Comment by thomaslombart** [comment]
I was thinking the same thing lately. Unfortunately, we're directly calling Linear's API when searching for an issue so I'm afraid we won't have any fixes for that now. I've asked Linear's team to validate if it's on their end.

**Comment by lightbody** [comment]
Well, that explains it. Hopefully they fix up the search API at some point! I'll maybe drop a note directly in their Slack community as well.

**Comment by lightbody** [comment]
I'll close this out for now since there isn't much you can do. Thanks for chasing it down. I'll drop a comment in here if/when I see improvements in the search results.
