### ISSUE TITLE
[Linear] Custom Search Issues logic

### ISSUE THREAD

**Issue by lightbody** [raycast/extensions#5372]
### Extension

https://www.raycast.com/linear/linear

### Description

Assuming #5371 gets resolved, I would *love* to be able to customize some of the filters for searching for issues. Specifically, I would like to bind a keyboard shortcut to a Search Issues action that was fine-tuned to only search for issues in a certain project, with certain status values. This would let me rapidly search the backlog of my main project and not get other stuff (other projects, completed/in-flight work, etc) polluted in the results.

Thanks!

**Comment by thomaspaulmann** [comment]
This would be very cool indeed. Do you have some searches that you do regularly? Trying to understand if a GitHub-like syntax would work here. F.e. `assignee:thomas project:ai fix bug` would work for all issues that are assigned to me, part of the ai project and contain "fix bug".

**Comment by lightbody** [comment]
The main search I do *all* the time is for stuff in a specific project that has status in either Triage, Backlog, or Todo. Basically, I'm looking for stuff we aren't working on so that I can link it up with inbound support requests / feature requests.
