### ISSUE TITLE
Add MR template for GitLab

### ISSUE THREAD

**Issue by n14s** [raycast/extensions#5376]
### Extension

https://www.raycast.com/tonka3000/gitlab

### Description

This extension is awesome!
Many people have to use Merge Request Templates, especially at work, to structure the MR description and link JIRA tickets.
Unfortunately, without the ability to use templates in the extension, it loses most of its value.
It would be awesome if MR templates could be added to the create MR function.

### Who will benefit from this feature?

Most users, especially professional developers.

**Comment by tonka3000** [comment]
PRs are welcome for that feature

**Comment by charl3j** [comment]
@raycastbot close this issue
