### ISSUE TITLE
[Extension Bug] Harvest - @eluce2 

### ISSUE THREAD

**Issue by astrit** [raycast/extensions#538]
# Extension – [Harvest](https://github.com/raycast/extensions/tree/main/extensions/harvest)

Author: @eluce2 

## Description
I think this is a bug because it is not showing the project name but empty brackets 

## Steps To Reproduce

1. Add Access Token
2. Account ID 
3. New Time Entry

![image](https://user-images.githubusercontent.com/2398447/146455378-1c2fe185-7940-4db8-bb20-bd46f6e6689b.png)

## The current behavior
No Project Name 

## The expected behavior
Show project name

### Raycast version
Version: 1.26.3

**Comment by eluce2** [comment]
Thanks for letting me know about this! The brackets are to show the project code, the name is what's showing there. I'll add some logic for the next update so that the brackets do not show if there is no project code.

**Comment by astrit** [comment]
@eluce2 thanks for the feedback. 

I understand now. 
This is how the projects are organised on my account if it helps 

![image](https://user-images.githubusercontent.com/2398447/146511619-a0e65716-8f52-4d1a-b9b8-a7a93e6936c7.png)

**Comment by eluce2** [comment]
Yes, perfect! Grouping projects by client is coming in the next version also!
