### ISSUE TITLE
[Figma File Search] ...

### ISSUE THREAD

**Issue by joesteinkamp** [raycast/extensions#5383]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

It would be great to search an entire Figma org or be able to configure multiple team (I've seen Slapdash do that).

### Who will benefit from this feature?

Anyone that uses multiple teams

**Comment by michaelwschultz** [comment]
@joesteinkamp working on it. Hope to have an update out soon. 👍

**Comment by GLaDO8** [comment]
Extension is now updated to support multiple teams :)

https://github.com/raycast/extensions/pull/6490

**Comment by GLaDO8** [comment]
@raycastbot close this issue
