### ISSUE TITLE
[Obsidian] Append to Daily Note Silent Mode is not working

### ISSUE THREAD

**Issue by sumonsinha209** [raycast/extensions#5386]
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

I tried the append to daily note and it appends the content and open the app which is something I don't want. I just need it to append and that's it.

**Comment by marcjulianschwarz** [comment]
This is not possible. The extension is relying on the advanced URI plugin of Obsidian. For the silent mode to work Obsidian has to be running. It will still focus on Obsidian but it wont open the note. This means you can continue your work on the currently open note.

This is a limitation of the advanced URI plugin.

From the extensions README:
> Silent mode, if enabled, will not open the note if it is currently not opened in an Obsidian tab or pane (Obsidian has to be running)

@raycastbot close this issue

**Comment by sumonsinha209** [comment]
Ok. I don't close Obsidian. What I wanted was when I'm on a different app, I don't want it to switch to Obsidian.

**Comment by marcjulianschwarz** [comment]
This is currently not possible due to the limitation of the advanced uri plug-in.
