### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by AbianTang** [raycast/extensions#5388]
### Description

<img width="328" alt="截屏2023-03-16 04 48 18" src="https://user-images.githubusercontent.com/60424384/225438996-ac46cf5c-4fe9-43aa-96f9-b2cdb06d58d0.png">

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊

**Comment by AbianTang** [comment]
ok，it's a proxy problem
