### ISSUE TITLE
[Asana] 400 error creating task with due date

### ISSUE THREAD

**Issue by devinhalladay** [raycast/extensions#5393]
### Extension

https://www.raycast.com/raycast/asana

### Description

When creating an Asana task with a start date, I get a 400 error.

https://user-images.githubusercontent.com/1934813/225479422-d89fac06-51c3-459a-a27f-7814755d5346.mp4

### Steps To Reproduce

1. Run `Create task`
2. Add a start date or end date
3. Create the task

### Current Behaviour

400 error

### Expected Behaviour

Successful task creation

**Comment by thomaslombart** [comment]
Do you have anything else besides the 400 error? Could you share a recording, please? 😊

**Comment by thomaslombart** [comment]
Sorry, didn't see that one, it didn't load at first 😅 
@stanty522 any ideas where this may come from? It's probably due to this PR: https://github.com/raycast/extensions/pull/4276

**Comment by stanty522** [comment]
Judging from the video it seems like the 400 error happens because no due date is set. Asana requires tasks have a due date if you have a start date. If both are left unspecified then it should be okay. If you only put due date and no start date it should be okay too.

**Comment by thomaslombart** [comment]
Ah, interesting one. @devinhalladay could you let me know if you still have the issue if you set a due date? @stanty522 as I don't have Asana Premium, could you let me know what's the UX on Asana when you set a start date but not a due date? Are there any errors displayed?

**Comment by foss-** [comment]
Also can't create a new task with start + due date. The error message differs, when using both start + due date:
`Request failed with status code 402`

Removing both dates allowed for task creation.

**Comment by devinhalladay** [comment]
@thomaslombart sorry for the delay. Task creation works when only the _due_ date is selected. So the problem only occurs when a _start_ date is set without a _due_ date.
