### ISSUE TITLE
Unable to add music to library, love function works fine[Music]: 

### ISSUE THREAD

**Issue by LeoLee53** [raycast/extensions#5395]
### Extension

https://raycast.com/fedevitaledev/music

### Description

Command failed with exit code 1: osascript -e tell application "Music" to duplicate current track to source 1 
28:63: execution error: Music got an error: Can’t set source 1 to current track. (-10006)

**Comment by Rawnly** [comment]
Duplicate of #5344, in already working on this, ho to fix this soon

**Comment by Rawnly** [comment]
@raycastbot close this issue
