### ISSUE TITLE
[Visual Studio Code - Project Manager] Open projects on the remote server

### ISSUE THREAD

**Issue by xc-gs** [raycast/extensions#5406]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

Currently, this extension only allows the opening of local projects. Need support for projects on remote-ssh or docker.

**Comment by xc-gs** [comment]
> There should be a remote support already ...
> 
> https://github.com/raycast/extensions/blob/6072b8dc9dbabf33de28277e6f2c3bf8d34086fc/extensions/visual-studio-code-project-manager/src/search-project-manager-projects.tsx#L29
> 
> Maybe @TobiasYin could help?

I can see the remote projects but was not able to directly open them.

**Comment by MarkusLanger** [comment]
What happens when you try to open a project? Maybe you can attach a short GIF.

**Comment by xc-gs** [comment]
@MarkusLanger  Nothing happens when I click on it.

**Comment by xc-gs** [comment]
@MarkusLanger  Thanks. I figured it out. I didn't install "code" in the path.
