### ISSUE TITLE
[Bear Notes] Raycast no longer working with updated Bear (Bear 2 - released today)

### ISSUE THREAD

**Issue by apg-dev** [raycast/extensions#5407]
### Extension

https://www.raycast.com/hmarr/bear

### Description

<img width="738" alt="Raycast-Bear" src="https://user-images.githubusercontent.com/55888411/225668832-27b24439-26a0-46c1-b9f3-fdd9997a955f.png">

### Steps To Reproduce

Update Bear with today's update from Shiny Frog. Try using Raycast to find notes.

### Expected Behaviour

I'm not sure how much work it will be to allow Raycast to work with the updated Bear, but unfortunately the upgrade to Bear 2 is one-way (can't go back). So we're stuck without Raycast access to Bear notes until compatibility can be achieved :-(.

**Comment by apg-dev** [comment]
It's in Testflight for both macOS and iOS.

And sadly, I didn't realize it would break Raycast.

>>
Hey there! The time you knew was coming is now here: the Bear 2 beta is
ready for you *with sync* on Mac and iOS! The next section is really
important, so please read it:

[image: :warning:] *Once you go Bear 2 beta, you can’t go back*. This new
beta will migrate and upgrade your old Bear 1 database and use it from now
on. The /Application Data v2/ folder is no longer used. Be sure to *export
all new and edited notes since Bear 1*, then import them into this new beta.

**Comment by lucaschultz** [comment]
I've got everything up and running locally. I'll submit a pull request tomorrow.

**Comment by gacharles23** [comment]
Hello. Is there an estimate on when this plugin might be able to support Bear 2? Thank you.

**Comment by lucaschultz** [comment]
Currently we're just waiting for the MR beeing merged 🙂

**Comment by program247365** [comment]
Was fixed in the #5536 PR. @raycastbot close this issue
