### ISSUE TITLE
[Multilinks] Use any browser

### ISSUE THREAD

**Issue by megaroeny** [raycast/extensions#5412]
### Extension

https://www.raycast.com/abhisheksatre/multilinks

### Description

I wanted to use this, but noticed you only provide Safari and Chrome in your browser dropdown menu. Why's that?

Can you update it to support any browser or add more to the list, specifically Edge? Thanks!

![Kapture 2023-03-16 at 15 27 00](https://user-images.githubusercontent.com/1559447/225732076-feac5bc6-276a-499b-bb74-05b30312565d.gif)

### Who will benefit from this feature?

Anyone with a browser that's not Safari or Chrome

### Anything else?

@mathieudutour tagging you since it's your extension 😉

**Comment by abhisheksatre** [comment]
@megaroeny Added firefox, edge, and chromium browser support.

@raycastbot close this issue
