### ISSUE TITLE
[logseq] ...logseq search found Failed to open link. Missing graph identifier after `logseq://graph/`.

### ISSUE THREAD

**Issue by absir1949** [raycast/extensions#5415]
### Extension

https://www.raycast.com/futantan/logseq

### Description

when i use logseq searh, it found some pages，but i open the results, then i will found a error about 'Failed to open link. Missing graph identifier after `logseq://graph/`.
<img width="410" alt="image" src="https://user-images.githubusercontent.com/14873265/225792481-ee11c890-3610-4bf9-a363-1bd39f76e68a.png">

my logseq path is in cloud, and i set path is '/Users/myusername/Library/Mobile Documents/iCloud~com~logseq~logseq/Documents/'

what can i do?

i use mac m1pro,and logseq is the last version,raycast is the last version.

**Comment by kerim** [comment]
Still having this issue. Who is maintaining this extension?
