### ISSUE TITLE
GPT-4 Support

### ISSUE THREAD

**Issue by Maclean-D** [raycast/extensions#5418]
### Extension

https://www.raycast.com/simicvm/openai-gpt3

### Description

Adding support for the GPT-4 API for people that already have access to it.

### Who will benefit from this feature?

Anyone who already has access to GPT-4

**Comment by simicvm** [comment]
> GPT-4 support would be nice, as it [doesn't seem to be working in the other extension](https://github.com/raycast/extensions/pull/5253#issuecomment-1489235807).

PR is up and should be merged shortly https://github.com/raycast/extensions/pull/5661
