### ISSUE TITLE
[Wi-Fi] support personal hotspots

### ISSUE THREAD

**Issue by polderleo** [raycast/extensions#5421]
### Extension

https://www.raycast.com/koinzhang/wi-fi

### Description

It would be great to have a separate section for hotspots, or personal hotspots that you can connect to.

**Comment by pernielsentikaer** [comment]
Hi @koinzhang 👋 

Is this even possible?

**Comment by koinzhang** [comment]
Hi @polderleo @pernielsentikaer As of now, this feature is not available for now. Mobile hotspot will be displayed together with other Wifi
