### ISSUE TITLE
[OpenAI GPT3] ...

### ISSUE THREAD

**Issue by jwptrs77** [raycast/extensions#5428]
### Extension

https://www.raycast.com/simicvm/openai-gpt3

### Description

<img width="988" alt="image" src="https://user-images.githubusercontent.com/127485678/225916818-1e457a9e-944e-4806-b426-33635f112261.png">
upon entering a prompt I get an error
 message. i have entered an API key of a GPT plus account to access.
<img width="766" alt="image" src="https://user-images.githubusercontent.com/127485678/225917009-40758cb3-a1fd-46e9-a034-6d7f5780fcab.png">

### Steps To Reproduce

op a macbook running latest versions.
see screenprints.

**Comment by jaredliu233** [comment]
i have the same promblem, can you support proxy?maybe the api is banned from the country.

I solve it like this:

import { ChatGPTAPI } from "chatgpt";
import dedent from "ts-dedent";
import puppeteer from "puppeteer";

const chatgptApi = new ChatGPTAPI({
    apiKey: process.env.OPENAI_API_KEY as string,
    fetch: (url, options = {}) => {
        const defaultOptions = {
            agent: require("https-proxy-agent")("http://127.0.0.1:33210"),
        };

        const mergedOptions = {
            ...defaultOptions,
            ...options,
        };

        return require("node-fetch").default(url, mergedOptions);
    },
});

**Comment by simicvm** [comment]
enabling API usage from the unsupported country goes against the OpenAI Policy. Therefore I will not be able to support this unfortunately.

**Comment by simicvm** [comment]
@raycastbot close this issue
