### ISSUE TITLE
[1Password] ...

### ISSUE THREAD

**Issue by aluminumfalkon** [raycast/extensions#5441]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Logging into business account gives the error "spawnSync /usr/local/bin/op ENOBUFS".

![Screenshot 2023-03-18 at 11 34 48](https://user-images.githubusercontent.com/117615180/226115536-63112944-08df-4a81-a901-6c6fd7f0637c.jpg)

Signing into my personal account works fine.

### Steps To Reproduce

1. Open My  Passwords
2. Choose a team account from the list

### Current Behaviour

Receive an error and account is not opened.

### Expected Behaviour

Should see passwords in team account

**Comment by khasbilegt** [comment]
@pernielsentikaer could this be related to the buffer size?

**Comment by pernielsentikaer** [comment]
Could be 😊 

@aluminumfalkon what does `op item list | wc -l` in a terminal give you?

**Comment by khasbilegt** [comment]
@aluminumfalkon what happens when you try to manually sign in using the cli directly?
