### ISSUE TITLE
[readwise-reader] ...

### ISSUE THREAD

**Issue by gndclouds** [raycast/extensions#5445]
### Extension

https://www.raycast.com/zach/readwise-reader

### Description

I would love to see a few more options other than only opening different reader tabs.
- new links (similar to ⌘ A in the reader app)
- add new feeds
- upload file

### Who will benefit from this feature?

It would allow any reader user to save items more quickly. The current functionality is mainly based on viewing existing content.

**Comment by zach-fuller** [comment]
Hey @gndclouds 👋  I plan on pushing an update that adds support for adding links later tonight. Currently there isn't an API for creating feeds or uploading files but I plan to add additional functionality as the Reader API progresses. I'll link the pull request here once it's up.
