### ISSUE TITLE
[Create T3 App] ... Can have the ability to select the terminal we want?

### ISSUE THREAD

**Issue by ThePromiseBenard** [raycast/extensions#5446]
### Extension

https://www.raycast.com/mozzius/create-t3-app

### Description

Currently, it just  opens the default mac os terminal to run the installs. Can we have a way to select our preferred terminal app?

### Who will benefit from this feature?

Everybody i guess

**Comment by mozzius** [comment]
That'd be great! I don't like the way it works at the moment anyway. Ideally, it'd just work via child_process in the background, but I couldn't get that working. Do you (or anyone) know if there's any other extension that has that functionality?
