### ISSUE TITLE
[Menubar Weather] Wind speed does not indicate direction

### ISSUE THREAD

**Issue by cybercode** [raycast/extensions#5451]
### Extension

https://www.raycast.com/koinzhang/menubar-weather

### Description

The entry for wind should also display the wind direction (either as an arrow (↗) or string (NE, NNW). Wind speed without direction is not particularly useful info. 

### Who will benefit from this feature?

everyone

**Comment by koinzhang** [comment]
Hi @cybercode I've submitted a PR #5640  to add the ability to show wind direction.
If you have any other questions, feel free to reopen this Issue.

@raycastbot close this issue

**Comment by cybercode** [comment]
thank you, looks great!
