### ISSUE TITLE
[Timers] UNREASONABLY Loud Timer. The "Volume" setting magnifies the system volume.

### ISSUE THREAD

**Issue by rpalaguachi** [raycast/extensions#5455]
### Extension

https://www.raycast.com/ThatNerd/timers

### Description

I nearly lost my hearing.

This is largely my own fault, but I'm hoping the devs can prevent this from happening to someone else.

When I set up my first timer, there was a field to configure the "Volume". I set it to `90`, assuming that meant 90% of my relative system volume. 

No, 90 must be 900% of it because what I got was an ungodly loud Piano Chime through my speakers that woke up my entire household and the neighbors. Worst part? I couldn't figure out how to turn it off either!

The system notification was useless in turning off the timer. How was I supposed to know clicking my menu bar dropdown would stop the timer? I had to go into the terminal and kill the AppScript process by force.

I'm sorry, I normally don't write bug reports in a frustrated tone, but I was (and still am) in genuine shock. 

I can't even go back to adjust the volume (lost the setting), but please check if there's an additional zero when setting the timer volume so people don't lose their hearing. <3

### Steps To Reproduce

1. Set up your first timer, and put the Volume setting to 90
2. Wait...
3. Destroy your ears

### Current Behaviour

Setting the timer volume **multiplies** the system volume (or so I believe)

### Expected Behaviour

Volume should be relative of system volume, not absolute (or worse, multiplicative of system volume).

**Comment by ThatNerdSquared** [comment]
Hi @rpalaguachi - I'm sorry for what happened!

First, I'll offer a quick explanation of how the volume works. It should be a decimal between 0 and 1, 0 being silent and 1 being the system volume. In your case, `0.9` gives you the intended 90% of system volume. I went back and checked that [there's a tooltip explaining this](https://github.com/ThatNerdSquared/timers-for-raycast/blob/1131956f926c794f78e5af231bdb6dca3d825dc4/package.json#L225), although I realize it may not have showed in your case. Under the hood, the system I use to play the sounds accepts values up to 255, increasing on a logarithmic scale - why it's structured for such mindbendingly loud sounds, I'm don't know either, but it's not something I have control over.

For stopping the timer, did you have the "Ring Continuously" setting enabled? If so, the "Dismiss Timer Alert" command should have stopped the alert sound from playing again. If not, the sound should only have played once.

Moving on to solutions - as far as I know, there's no way for me to validate the actual input for the volume preference. I'll push a quick fix today that auto-caps the volume at 4 or 5 and shows an error message to prevent the situation you encountered from happening again, as well as do some further investigation to see if a better UX is possible. As for stopping timer alerts, it seems like [it's possible to add buttons to notifications from AppleScript](https://stackoverflow.com/questions/33808062/action-buttons-applescript-functions), so I'll add that functionality soon. Please let me know whether you had the "Ring Continuously" setting enabled and whether you tried the "Dismiss Timer Alert" command so I can identify other bugs/usability issues!

Again, sorry for the bad experience you had with Timers \:( I'll do my best to make sure things are fixed as soon as possible.

**Comment by ThatNerdSquared** [comment]
@pernielsentikaer do you know of any good approaches to validating input from extension preferences? Can I add a validator to the `package.json` somehow?

**Comment by rpalaguachi** [comment]
Thanks for the quick reply!

Your explanation cleared everything up for me (I'm still new to Raycast, so thank you!)

Yes, I definitely agree that the max volume should be 4 or 5. That would save a lot of headaches.

I'll take your suggestions and see if I can safely use Timers again. I really appreciate the timely response :)

**Comment by pernielsentikaer** [comment]
Is there any reason to go above 100? You could also let the user select 1-100(%) and strip the percentage and do the calculate yourself and just set it to 100 if the entered number is above 100?

**Comment by rpalaguachi** [comment]
I could imagine a scenario where the user might play music on low volume, but wants to make sure the timer comes through louder. Perhaps 200%.

**Comment by lokot0k** [comment]
As far as I can see it's impossible to specify absolute volume with `afplay`. Docs clarify that volume is configurable in relative to the system
 >The scale is logarithmic and in addition to (not a replacement for) other volume control(s)

So it may be hard/impossible(without additional deps) to make absolute volume scale for user. Because of that I think the problem is to explain to users that the input value is relative, not absolute

**Comment by ThatNerdSquared** [comment]
Right, what @lokot0k mentioned has been my main problem with this, given that not only is `afplay`'s volume setting relative and a decimal but also very weird (logarithmic scale that goes up to 255 for sound far louder than the system?!). It's not really possible to specify percentages outside of 0-100% (which are decimals between 0 and 1 as previously mentioned).

Maybe sticking "relative" and/or "decimal between 0 and ${upperLimit}" in the name of the setting would be useful?

> You could also let the user select 1-100(%) and strip the percentage and do the calculation yourself
The logarithmic scale makes it a bit tricky but I'll investigate this a little bit if nothing else works well.
