### ISSUE TITLE
[OpenAI GPT3] ...

### ISSUE THREAD

**Issue by AllenAlex-1014** [raycast/extensions#5462]
### Extension

https://www.raycast.com/simicvm/openai-gpt3

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'message')

Pe:ai.tsx:160:106
async onAction:index.js:22:2371
```

**Comment by simicvm** [comment]
seems like the API is using inappropriate form. Basic GPT3 and and GPT3.5 have different APIs, one is taking `prompt` other `message` .

Can you tell me with what model does this happen?

**Comment by AllenAlex-1014** [comment]
> seems like the API is using inappropriate form. Basic GPT3 and and GPT3.5 have different APIs, one is taking `prompt` other `message` .
> 
> Can you tell me with what model does this happen?

GPT 3.5 turbo  and  text-davinci-003  both happened this problem

**Comment by simicvm** [comment]
> > seems like the API is using inappropriate form. Basic GPT3 and and GPT3.5 have different APIs, one is taking `prompt` other `message` .
> > Can you tell me with what model does this happen?
> 
> GPT 3.5 turbo and text-davinci-003 both happened this problem

Strange, I can't reproduce the error. Does it happen with any prompt or only with a specific prompt?
