### ISSUE TITLE
[Extension Bug] BitWarden extension should not show master password in plain text

### ISSUE THREAD

**Issue by tonyxiao** [raycast/extensions#547]
![image](https://user-images.githubusercontent.com/696842/146647964-ec373ee2-3865-4d1e-a041-5c826b5c8611.png)

Having extension in plain text was very freaky. Here's the code that needs to change.

https://github.com/raycast/extensions/blob/2aa3585cce4514447adddc15ac01f8cb0a6467d1/extensions/bitwarden/src/components.tsx#L53

**Comment by pomdtr** [comment]
Duplicate of https://github.com/raycast/extensions/issues/44

**Comment by mattisssa** [comment]
@pomdtr thanks for linking the duplicate 👍 
Closing this one then.
