### ISSUE TITLE
[Focus - Website Blocker For Mac] ...

### ISSUE THREAD

**Issue by QIanGua** [raycast/extensions#5470]
### Extension

https://www.raycast.com/ernest/focus

### Description

It does't recognize my Focus.app installed from Setapp.

### Steps To Reproduce

1. Option + space to envoke Raycast
2. Input Focus and select Focus command

### Current Behaviour

Focus is not installed
Install Focus app from: https://heyfocus.com

### Expected Behaviour

I wish it can support Focus.app from Setapp, whose bundle ID is `com.bradjasper.focus-setapp`.
I guess the `getInstallStatus` in `utils.tsx` can be rewrote as
```
export async function getInstallStatus() {
  const applications = await getApplications();
  return applications.some(({ bundleId }) => bundleId === "BradJasper.focus" || bundleId === "com.bradjasper.focus-setapp");
}
```

**Comment by namzo** [comment]
@QIanGua Thanks for sharing! I'll push a fix for it.

**Comment by namzo** [comment]
@QIanGua I've pushed it https://github.com/raycast/extensions/pull/5472. It should work once it's merged.

@raycastbot close this issue
