### ISSUE TITLE
[Tana] ...

### ISSUE THREAD

**Issue by gila2000** [raycast/extensions#5471]
### Extension

https://www.raycast.com/cheslip/tana

### Description

Every time I try to send something to Tana I get a 403 error.
I am on a Mac OS Ventura.

**Comment by shurtador** [comment]
I was getting the same error when I first set it up. 
I understand that error 403 is the API saying the request is forbidden. On my end, it was because the API token I was using was wrong.

Can you double-check your token? Maybe that solves the issue.
