### ISSUE TITLE
[Bitly URL Shortener] ...

### ISSUE THREAD

**Issue by mlatilik** [raycast/extensions#5473]
### Extension

https://www.raycast.com/blessanm86/bitly-url-shortener

### Description

Hello,
I constantly get an error message "Error. Invalid URL". I tried to generate multiple API keys. 
Thanks,
Ales

**Comment by blessanm86** [comment]
Are u just using cmd+c and then selecting the extension or using raycast clipboard history extension?

**Comment by mlatilik** [comment]
just cmd+c. Actually just upgraded to 1.49.0, and it seems working fine now. 
@raycastbot close this issue
