### ISSUE TITLE
Logitech Litra not running

### ISSUE THREAD

**Issue by Lvkz** [raycast/extensions#5476]
### Extension

https://www.raycast.com/timrogers/logitech-litra

### Description

Cannot use the Manage Devices option on the Litra extension:

The output of `dirname $(which litra-on)` is: `/opt/homebrew/bin`

```
/Error: Command failed: /opt/homebrew/bin/litra-devices --json
env: node: No such file or directory


env: node: No such file or directory
ChildProcess.exithandler:node:child_process:412:12
ChildProcess.emit:node:events:513:28
```

One note: if I run the command is trying to run manually I get a correct response: 

```
/opt/homebrew/bin/litra-devices --json
[{"name":"Logitech Litra Glow","serial_number":"XXXXXXXXXXXXX"}]
```

### Steps To Reproduce

1. Download the Litra extension.
2. Install Node.
3. Install the Litra package.
4. Run extension.

### Current Behaviour

 
![CleanShot 2023-03-20 at 15 04 09](https://user-images.githubusercontent.com/2721391/226440638-1ea018cf-d18a-4857-b8fa-56d66ee7dac5.png)

### Expected Behaviour

Manage the connected Litra devices.

**Comment by timrogers** [comment]
Thanks for reaching out! This looks very weird. I can't think of an obvious reason why this would happen. 

A couple of questions:

1) How did you install the litra module? I'm surprised to see it in the Homebrew bin directory?
2) Can you run `ls -l /opt/homebrew/bin | grep litra` and share the output?

**Comment by Lvkz** [comment]
Thank you for looking at this!

1. Just as indicated in the documentation:  `❯ npm install -g litra`
2. Sure thing here's the output:

```
❯ ls -l /opt/homebrew/bin | grep litra
lrwxr-xr-x@ 1 lukasgomez  admin    63 Mar 20 14:16 litra-brightness -> ../lib/node_modules/litra/dist/commonjs/cli/litra-brightness.js
lrwxr-xr-x@ 1 lukasgomez  admin    66 Mar 20 14:16 litra-brightness-lm -> ../lib/node_modules/litra/dist/commonjs/cli/litra-brightness-lm.js
lrwxr-xr-x@ 1 lukasgomez  admin    60 Mar 20 14:16 litra-devices -> ../lib/node_modules/litra/dist/commonjs/cli/litra-devices.js
lrwxr-xr-x@ 1 lukasgomez  admin    61 Mar 20 14:16 litra-identify -> ../lib/node_modules/litra/dist/commonjs/cli/litra-identify.js
lrwxr-xr-x@ 1 lukasgomez  admin    56 Mar 20 14:16 litra-off -> ../lib/node_modules/litra/dist/commonjs/cli/litra-off.js
lrwxr-xr-x@ 1 lukasgomez  admin    55 Mar 20 14:16 litra-on -> ../lib/node_modules/litra/dist/commonjs/cli/litra-on.js
lrwxr-xr-x@ 1 lukasgomez  admin    62 Mar 20 14:16 litra-oversight -> ../lib/node_modules/litra/dist/commonjs/cli/litra-oversight.js
lrwxr-xr-x@ 1 lukasgomez  admin    66 Mar 20 14:16 litra-temperature-k -> ../lib/node_modules/litra/dist/commonjs/cli/litra-temperature-k.js
```

**Comment by timrogers** [comment]
Ah, I just spotted this part in your original output:

> env: node: No such file or directory

The problem is that it can't find `node`, not that it can't find the `litra-devices` module.

I wonder if the solution suggested [here](https://stackoverflow.com/a/48736639) might help - could you try it?

**Comment by Lvkz** [comment]
@timrogers this dual node installation is proven to be a little tricky... I will update you when I can sort it out. Following the steps on different answers on the post you suggested has not worked so far.

**Comment by pixelcab** [comment]
FWIW, I'm encountering the same issue using NVM on Mac (v13.3.1)

### Raycast error output

``` 
Error: Command failed: /Users/USERNAME/.nvm/versions/node/v16.19.0/bin/litra-devices --version
env: node: No such file or directory


env: node: No such file or directory
ChildProcess.exithandler:node:child_process:412:12
ChildProcess.emit:node:events:513:28
```

### Node version and Litra installation

```
❯ which node
/Users/user.name/.nvm/versions/node/v16.19.0/bin/node

❯ node -v
v16.19.0

❯ /Users/user.name/.nvm/versions/node/v16.19.0/bin/litra-devices --version
4.4.1

❯ ls -l /Users/user.name/.nvm/versions/node/v16.19.0/bin | grep litra
lrwxr-xr-x  1 user.name  staff        63 Apr 19 08:53 litra-brightness -> ../lib/node_modules/litra/dist/commonjs/cli/litra-brightness.js
lrwxr-xr-x  1 user.name  staff        66 Apr 19 08:53 litra-brightness-lm -> ../lib/node_modules/litra/dist/commonjs/cli/litra-brightness-lm.js
lrwxr-xr-x  1 user.name  staff        60 Apr 19 08:53 litra-devices -> ../lib/node_modules/litra/dist/commonjs/cli/litra-devices.js
lrwxr-xr-x  1 user.name  staff        61 Apr 19 08:53 litra-identify -> ../lib/node_modules/litra/dist/commonjs/cli/litra-identify.js
lrwxr-xr-x  1 user.name  staff        56 Apr 19 08:53 litra-off -> ../lib/node_modules/litra/dist/commonjs/cli/litra-off.js
lrwxr-xr-x  1 user.name  staff        55 Apr 19 08:53 litra-on -> ../lib/node_modules/litra/dist/commonjs/cli/litra-on.js
lrwxr-xr-x  1 user.name  staff        62 Apr 19 08:53 litra-oversight -> ../lib/node_modules/litra/dist/commonjs/cli/litra-oversight.js
lrwxr-xr-x  1 user.name  staff        66 Apr 19 08:53 litra-temperature-k -> ../lib/node_modules/litra/dist/commonjs/cli/litra-temperature-k.js
lrwxr-xr-x  1 user.name  staff        59 Apr 19 08:53 litra-toggle -> ../lib/node_modules/litra/dist/commonjs/cli/litra-toggle.js

**Comment by timrogers** [comment]
@pixelcab Very weird :( It's odd that `node` isn't available in `/usr/bin/env`. I wonder if this would be worth creating an nvm issue?

**Comment by timrogers** [comment]
https://github.com/nvm-sh/nvm/issues/786 says that this is by design for NVM. Sounds like you can create a symlink yourself.

**Comment by arough007** [comment]
I'm having the same issue with nvm.

```
Error: Command failed: /Users/max/.local/share/nvm/v18.7.0/bin/litra-devices --version
env: node: No such file or directory


env: node: No such file or directory
ChildProcess.exithandler:node:child_process:412:12
ChildProcess.emit:node:events:513:28
``` 

```
which node                                                                                                                                                             
/Users/max/.local/share/nvm/v18.7.0/bin/node

node -v                                                                                                                                                           
v18.7.0

/users/max/.local/share/nvm/v18.7.0/bin/litra-devices --version                                                                                                        
4.4.1

ls -l /Users/max/.local//share/nvm/v18.7.0/bin | grep litra                                                                                                            
lrwxr-xr-x  1 max  staff        63 Apr 27 13:10 litra-brightness -> ../lib/node_modules/litra/dist/commonjs/cli/litra-brightness.js
lrwxr-xr-x  1 max  staff        66 Apr 27 13:10 litra-brightness-lm -> ../lib/node_modules/litra/dist/commonjs/cli/litra-brightness-lm.js
lrwxr-xr-x  1 max  staff        60 Apr 27 13:10 litra-devices -> ../lib/node_modules/litra/dist/commonjs/cli/litra-devices.js
lrwxr-xr-x  1 max  staff        61 Apr 27 13:10 litra-identify -> ../lib/node_modules/litra/dist/commonjs/cli/litra-identify.js
lrwxr-xr-x  1 max  staff        56 Apr 27 13:10 litra-off -> ../lib/node_modules/litra/dist/commonjs/cli/litra-off.js
lrwxr-xr-x  1 max  staff        55 Apr 27 13:10 litra-on -> ../lib/node_modules/litra/dist/commonjs/cli/litra-on.js
lrwxr-xr-x  1 max  staff        62 Apr 27 13:10 litra-oversight -> ../lib/node_modules/litra/dist/commonjs/cli/litra-oversight.js
lrwxr-xr-x  1 max  staff        66 Apr 27 13:10 litra-temperature-k -> ../lib/node_modules/litra/dist/commonjs/cli/litra-temperature-k.js
lrwxr-xr-x  1 max  staff        59 Apr 27 13:10 litra-toggle -> ../lib/node_modules/litra/dist/commonjs/cli/litra-toggle.js
```

**Comment by TannerH** [comment]
I was facing the same nvm issues as others posted. I always use the same brightness and temperature so I really just needed the ability to toggle the light on and off. My workaround was to create a simple Script Command that just runs `{full-path-to-litra-nvm-install}/litra-toggle`

**Comment by timrogers** [comment]
It's very interesting that that works, but it doesn't work when the extension runs the same script. 

Are you able to share the script command?

I have an idea of how we might be able to fix this - I'll make a PR and might get some of you to test it in the next day or two :)

**Comment by pixelcab** [comment]
> I was facing the same nvm issues as others posted. I always use the same brightness and temperature so I really just needed the ability to toggle the light on and off. My workaround was to create a simple Script Command that just runs `{full-path-to-litra-nvm-install}/litra-toggle`

Funny, I ended up going to same route with the simple script. Only difference was I created it using 'Shortcuts'. This allowed me to use the built in Raycast Shortcuts functionality, allowing for quicker on/off either via Raycast or a hot key combo. I'd prefer to use this extension though, since it provides more functionality. Regardless it's a quick work around. 

FWIW, it seems to the reason it works using your own script is because my I'm able to source/load the shell variables that NVM relies on. Or to just call the path to the NVM node bin node path.

**Comment by timrogers** [comment]
That's super helpful! Thanks ❤️

My thinking is that I could add an (optional) setting where you specify the path to the Node executable rather than relying on `/usr/bin/env node`. I think that'll do the trick! I'll try to do it in the next couple of days and will share a link so you can test it.

**Comment by timrogers** [comment]
Would y'all be able to try the fix I've proposed in [this PR](https://github.com/timrogers/raycast-logitech-litra/pull/54)?

You can download and run the extension by running:

```bash
git clone https://github.com/timrogers/raycast-logitech-litra.git && cd raycast-logitech-litra && git checkout timrogers/nvm && npm i && npm run dev
```

Once it's installed, can you try setting the `Node.js binary path` option to the output of `which node` in your terminal?

**Comment by timrogers** [comment]
I've confirmed with some users that the change in https://github.com/timrogers/raycast-logitech-litra/pull/54 works. I'm going to get it pushed for review, and we should be able to get the fix into the Raycast Store very soon.

**Comment by pixelcab** [comment]
@timrogers Thank you for your efforts. I downloaded the latest update and added the NVM node path; everything is working smoothly so far!

**Comment by pernielsentikaer** [comment]
Can you confirm too @Lvkz 🙂

**Comment by Lvkz** [comment]
@timrogers @pernielsentikaer, this works!! Thank you so much for looking into this and providing a working solution.
