### ISSUE TITLE
[OpenAI GPT3] ...

### ISSUE THREAD

**Issue by LeoLee53** [raycast/extensions#5482]
### Extension

https://www.raycast.com/simicvm/openai-gpt3

### Description

The extension won't pop back to root search even if I set it to 5 seconds in the settings. Other extensions work just fine, I think it's specific to this plugin.

**Comment by simicvm** [comment]
Unfortunately I am unable to reproduce this issue, and without additional details I am not able to help.

**Comment by LeoLee53** [comment]
Here’s a recording of the issue. I’ve set my raycast ‘popping back to root search’ time to immediately.

From: Marko Simic ***@***.***>
Date: Thursday, March 30, 2023 at 10:53 AM
To: raycast/extensions ***@***.***>
Cc: LeoLee53 ***@***.***>, Author ***@***.***>
Subject: Re: [raycast/extensions] [OpenAI GPT3] ... (Issue #5482)

Unfortunately I am unable to reproduce this issue, and without additional details I am not able to help.

**Comment by LeoLee53** [comment]
By the way, what further detail do you need? I’ll see if I can provide to help you solve the issue
________________________________
发件人: Marko Simic ***@***.***>
发送时间: Thursday, March 30, 2023 10:53:22 AM
收件人: raycast/extensions ***@***.***>
抄送: LeoLee53 ***@***.***>; Author ***@***.***>
主题: Re: [raycast/extensions] [OpenAI GPT3] ... (Issue #5482)


Unfortunately I am unable to reproduce this issue, and without additional details I am not able to help.

―
