### ISSUE TITLE
[Obsidian] Can't create new note

### ISSUE THREAD

**Issue by kslstn** [raycast/extensions#5483]
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

Creating a new note via the extension results in an error message.

I can however use the 'Daily Note' and use the 'Append to Daily Note' command. The commands involving searching and opening notes and my vault also work without error.

### Steps To Reproduce

On my macBook with an Obsidian vault in my iCloud, I've set the 'Path to vault' by copying the vault's path through the finder (Option + Right click).

1. Invoke Raycast
2. Find the 'Create note' command
3. Press enter
4. Fill out a file name
5. CMD + Enter

### Current Behaviour

An error message is shown:
>Unable to find a vault for the URL obsidian://open?path=%2FUsers%2F[my first name]%2FLibrary%2FMobile%20Documents%2FiCloud~md~obsidian%2FDocuments%2F[My vault name]%2F[My note name].md

Again, note that this doesn't happen with the other commands, suggesting that the vault's path is set correctly.

_Edit: it turns out that, despite the error message, the note file and its content are correctly created._

### Expected Behaviour

I'd expect a new note to be created, as it used to be.

**Comment by marcjulianschwarz** [comment]
Are there any special tokens in your vaults or notes names?

**Comment by marcjulianschwarz** [comment]
Oh I see the issue now. Your vault is located in an iCloud folder which has the ~ symbol in it. This might be the problem here. Will try to fix it. 

But did I understand it right that the notes are in fact created at the correct location?

**Comment by kslstn** [comment]
Exactly!
