### ISSUE TITLE
[Wireguard] Fails for configurations with " " space in the name

### ISSUE THREAD

**Issue by hannesjung** [raycast/extensions#5484]
### Extension

https://www.raycast.com/sbugzhu/wireguard

### Description

The extension shows an error if one of your wireguard connections contains a " " space character
`Command failed: /usr/sbin/scutil --nc status CONFIG_NAME | head -n 1 | grep -i "connected"`

This can easily be fixed by adding quotes to the configuration name
`Command failed: /usr/sbin/scutil --nc status "CONFIG_NAME" | head -n 1 | grep -i "connected"`

### Steps To Reproduce

1. Have one of your Wireguard connection names contain a " " space character

### Current Behaviour

Error message - see above

### Expected Behaviour

Should show list of connections & the status

**Comment by sbugzu** [comment]
Thanks for your feedback, has been submitted to fix: https://github.com/raycast/extensions/pull/5501

**Comment by pernielsentikaer** [comment]
Should be fixed in the latest release
