### ISSUE TITLE
[Spotify Player] Menu Bar Player and Now Playing doesn't work as expected

### ISSUE THREAD

**Issue by vishwasnavadak** [raycast/extensions#5505]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

<img width="763" alt="image" src="https://user-images.githubusercontent.com/13111030/226869212-574cccda-5f97-4b0e-9070-193e3d0a85f3.png">
<img width="768" alt="image" src="https://user-images.githubusercontent.com/13111030/226869344-5547413e-85b8-41af-8d5a-6b86276ec191.png">

#### Error:
```
Run Error: Command terminated, code: 14 (Timeout)
```

### Steps To Reproduce

Open Raycast and Type `Now Playing` or `Menu Bar Player` while Spotify App is playing the music in the background. 

### Current Behaviour

They show a loading screen or Error and doesn't load the song that is currently playing. 

### Expected Behaviour

Now playing is expected to show the currently playing song and Menu Bar Player is supposed to load the song name on the menu bar.

**Comment by kyranjamie** [comment]
same 
<img width="575" alt="image" src="https://user-images.githubusercontent.com/1618764/226980211-59ce931f-1c3e-48da-9ce1-429a3df9130c.png">
