### ISSUE TITLE
[Reminders] Natural language for creating new reminders

### ISSUE THREAD

**Issue by stephan281094** [raycast/extensions#5509]
### Extension

https://raycastapp.notion.site/Reminders-cd04642052864c5b82c4c5891e1ddbe2

### Description

Raycast natively comes with the Reminders extension installed. This extension allows for creating a new reminder. Right now this is a form with a couple of fields, and it works great. It would be nice, however, to be able to use natural language for creating reminders, e.g. `remind me to take the garbage out tomorrow at 9 am`.

I realize this might be a rather complex feature to implement and it might be out of scope, so feel free to close. I think it would, however, improve people's productivity. And that's what Raycast is all about 😉.

### Who will benefit from this feature?

Anyone using the Reminders extension regularly. Although, I imagine that having support for natural language processing could also benefit other extensions, such as the calendar app for creating or updating events. Perhaps this is something that should be part of the Raycast AI, where the difference is that you'd let AI perform actions.

### Anything else?

There's a couple of things I can think about that could be supported:
- Understand dates, such as `tomorrow`, `the last day of March`, `next week`, `this weekend`
- Understand times, such as `at noon`, `7 pm`, `tonight`, `this afternoon`
- Understand repeated events, such as `daily at 9 am`, `every week`, `Mondays until May 1st` (this might actually be a new feature altogether)
- Understand typos, such as `tomororw`, `tday` (nice to have)

**Comment by LunarRed** [comment]
I too would greatly value this.

**Comment by stephan281094** [comment]
Found out today that this has been implemented using the "Quick Add Reminder" command, see https://youtu.be/g5PBtcrm7Aw?t=168.
