### ISSUE TITLE
[Google Maps Search] "Find Place" starts with latest clipboard value

### ISSUE THREAD

**Issue by alexschilpp** [raycast/extensions#5511]
### Extension

https://www.raycast.com/ratoru/google-maps-search

### Description

When triggering the Google Maps "Find Place" action via Raycast it auto-populates the input field with your latest clipboard value. Most of the time your last copied value is not what you want to search Google Maps for, so you first need to clear the input before you can start your actual search.

I'd love to see this action starting with an empty input field instead so you can immediately type away. If you still want to search your last copied value you can always do a quick cmd+v.

Thanks!

### Who will benefit from this feature?

I believe that the user flow of the extension would be much smoother as you won't be surprised by automatically pasted irrelevant values

**Comment by ratoru** [comment]
Hi @alexschilpp! Thank you for raising this issue. I will try and fix it by the end of next week.

This wasn’t the intended behavior. One of the recent updates must have broken the functionality.

**Comment by chrismessina** [comment]
Just to confirm, autofill is off by default.
