### ISSUE TITLE
[Warp Launch Configuration] Warp config is not opened if there isn't any other warp screen opened at the time

### ISSUE THREAD

**Issue by brightestintegrations** [raycast/extensions#5514]
### Extension

https://www.raycast.com/joetannenbaum/warp-launch-configuration

### Description

When trying to launch a warp configuration the warp application does not open if all warp screens are closed

### Steps To Reproduce

1. Make sure warp is running but close all screens
2. Open raycast and try to launch the warp config

### Current Behaviour

Nothing happens

### Expected Behaviour

Expected: Warp opens en new screen with the expected configuration

**Comment by joetannenbaum** [comment]
@raycastbot close this issue
