### ISSUE TITLE
[Extension Bug] Lark mindnote search issue

### ISSUE THREAD

**Issue by zhangqifan** [raycast/extensions#552]
Extension – [Lark](https://github.com/raycast/extensions/tree/main/extensions/lark)

Author: @tmkx 

## Description

Mindnote searching is not working because of the wrong path appending.

Current link: xxx.feishu.cn/**mindnote**/xxx
Should be:  xxx.feishu.cn/**mindnotes**/xxx

## Steps To Reproduce

1. Create a mindnote document
2. Use Lark/Feishu 'Search Documents' function
3. Enter doc name
4. Open link in a web browser and it shows a blank page

## The current behavior

Showing a blank web page

## The expected behavior

Showing the document page

### Raycast version
Version: 1.26.3

**Comment by tmkx** [comment]
Okay, I'm going to fix it.
