### ISSUE TITLE
[iMessage 2FA] support code format 123-456

### ISSUE THREAD

**Issue by zalmanlew** [raycast/extensions#5523]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

CashApp codes are sent like `123-456` 

It only seems to read the `123` part here.

![image](https://user-images.githubusercontent.com/35234925/227232134-547bc944-c70e-42a9-b9fa-f697e4245351.png)

**Comment by arronhunt** [comment]
https://github.com/raycast/extensions/blob/6ffb6095b4b7dffb1975d40b3f96c9237555e593/extensions/imessage-2fa/src/utils.ts#L51

Looks like the regex is case sensitive. Cash app texts look like this: 

> Cash App: This code is for you and only you. Code: 000-000. To prevent fraud, never share it anywhere or with anyone, including people posing as Cash App.

An easy fix is to make it case insensitive. 

```
(?i)(^|code:|is:|\b)\s*(\d{3})-(\d{3})($|\s|\\R|\t|\b|\.|,)
```

cc @thomaspaulmann
