### ISSUE TITLE
[Visual Studio Code - Project Manager] ...

### ISSUE THREAD

**Issue by epan-dd** [raycast/extensions#5525]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

I added a new repo to the projects directory several hours ago and it still hasn't shown up as  a possible search result

### Steps To Reproduce

1. Set up the extension
2. provide a project directory with existing projects
3. git clone a new repo into the project directory
4. search for the new repo with the extension

### Current Behaviour

new repo does not show up in results

### Expected Behaviour

new repo does show up in results

**Comment by MarkusLanger** [comment]
@epan-dd Do you use the Project Manager Extension in VSCode and added the new project there?

**Comment by epan-dd** [comment]
@MarkusLanger thank you this worked great. appreciate the support!
