### ISSUE TITLE
[Wireguard] Disconnect all command

### ISSUE THREAD

**Issue by Spaider** [raycast/extensions#5535]
### Extension

https://www.raycast.com/sbugzhu/wireguard

### Description

It would be nice to have `Disconnect all` command. This will save some clicks daily. Usually it works like this: you turn some VPN connection on, do something and disconnect. Now if you want to disconnect, you have to select connection and only then select it to disconnect. 

### Who will benefit from this feature?

Having dedicated `Disconnect all` command will allow short cut assignment for it, thus it will not be even necessary to open Raycast window.

**Comment by sbugzu** [comment]
@raycastbot close this issue
