### ISSUE TITLE
Chinese support[Dev Tools Feature Request] 

### ISSUE THREAD

**Issue by kola-web** [raycast/extensions#554]
Raycast version:

**Describe the feature and the current behavior/state.**

**Comment by fe9lix** [comment]
@kola-web Could you be more specific what this feature request means?

**Comment by kola-web** [comment]
Only English interface, no Chinese interface

**Comment by kola-web** [comment]
> @kola-web Could you be more specific what this feature request means?

Only English interface, no Chinese interface

**Comment by fe9lix** [comment]
Sorry, I'm closing this issue since it's unclear what the actual feature request is. We do support EN as main locale for Raycast itself and the dev tooling.
