### ISSUE TITLE
[Terminal Finder] ...Warp -> Finder Command  cannot be executed.

### ISSUE THREAD

**Issue by mqlsq** [raycast/extensions#5547]
### Extension

https://www.raycast.com/yedongze/terminalfinder

### Description

When I try to use "Warp -> Finder" in Terminal Finder, it doesn't work and displays garbled characters.

### Current Behaviour

![Mar-24-2023 15-15-33](https://user-images.githubusercontent.com/1697933/227458160-a0d16dda-c550-4bdf-8f73-726a06bc59d1.gif)

**Comment by ESMP** [comment]
Unfortunately this extension doesn't work in my system... I try opening Warp from a selected finder folder and all it does is open Warp and change my input method. Same happens when trying the opposite... this extension would be best for my purposes, but I ended up installing the Copy Path one.
