### ISSUE TITLE
[Compress PDF] Error 422 

### ISSUE THREAD

**Issue by Vainyards** [raycast/extensions#5552]
### Extension

https://www.raycast.com/felixhaeberle/compress-pdf

### Description

When I try to compress pdf I get Error 422. 

### Steps To Reproduce

Add plugin
Register cloudconvert
create API key
Add to Raycast
Add file to compress
Error 422

### Current Behaviour

When I try to compress pdf I get Error 422. 

### Expected Behaviour

Compressed PDF in folder. 

Wishful was more explenation about the API key.

**Comment by Harosatchi** [comment]
Same error
