### ISSUE TITLE
[Things] Add a shortcut for Completing a to-do

### ISSUE THREAD

**Issue by mattlemmone** [raycast/extensions#5554]
### Description

It used to be possible to use the `Mark as Completed` action with a keyboard shortcut - I believe it was `CMD` + `return` on MacOS.

Within the past week or so, it is no longer possible - it instead copies a URI to the clipboard. I use Things and Raycast as daily drivers, so I was a bit confused.

Poking around for a bit, I noticed this PR was merged recently: https://github.com/raycast/extensions/pull/5436, where we have inserted `Copy URI` above `Mark as Completed`. I think an unintentional side-effect here was swapped the default keyboard shortcut over to `Copy URI`.

 `Copy URI` is not a feature I personally use, but I'm sure many of us use this to complete tasks in our various to-do lists 😄

### Who will benefit from this feature?

With 11.2k installs for this extension, I'm thinking we'll hear a few more voices chime in soon since the default keyboard shortcut was remapped.

### Anything else?

I couldn't find much on the default keyboard mapping (aside from [this](https://manual.raycast.com/action-panel)), so apologies if I'm misinformed here, but it doesn't look like there's any way for users to remap this manually back to how it was.

**Comment by mathieudutour** [comment]
Could you open an extension issue instead of an api issue? https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cfeature+request&template=extension_feature_request.yml&title=%5BExtension+Name%5D+...
