### ISSUE TITLE
[Microsoft Edge] Support for Edge Canary

### ISSUE THREAD

**Issue by macjabeth** [raycast/extensions#5564]
### Extension

https://www.raycast.com/KartikKumarSahoo/microsoft-edge

### Description

Currently the extension only seems to support the Microsoft Edge Stable and Dev builds. It would be nice if it also supported Microsoft Edge Canary.

### Who will benefit from this feature?

Myself and any others who use the Canary build.

**Comment by KartikKumarSahoo** [comment]
Support added in this PR https://github.com/raycast/extensions/pull/7526
