### ISSUE TITLE
[TickTick] Add smart parse tasks

### ISSUE THREAD

**Issue by petruut** [raycast/extensions#5569]
### Extension

https://www.raycast.com/appest/ticktick

### Description

I would like to be able to quickly add a task with the smart syntax that ticktick uses (e.g. raycast string: "t today #chores #home ~personal do laundry")

**Comment by viduycheung** [comment]
@petruut Hi, thanks for the suggestion. Smart parse is currently limited by technical solutions, but the action of adding tasks we are already under development.

**Comment by viduycheung** [comment]
@raycastbot close this issue
