### ISSUE TITLE
[Window Management] send window to next desktop

### ISSUE THREAD

**Issue by kennyma-eplus** [raycast/extensions#5578]
### Extension

https://www.raycast.com/extensions/window-management

### Description

[re-open] (#5548)[https://github.com/raycast/extensions/issues/5548]

i mean send the window to `Next Virtual Desktop` within the same  monitor
but not sending the window to next monitor

**Comment by qortex** [comment]
Would love that too. Sad it's been closed.

**Comment by scarecode** [comment]
This would be really useful!
