### ISSUE TITLE
[Trello] Search todos (across boards) not working

### ISSUE THREAD

**Issue by zenminimalist** [raycast/extensions#5586]
### Extension

https://www.raycast.com/ChrisChinchilla/trello

### Description

When I trying the "Search todos" it's not listing anything and give a "no results". I tried various todos, where I'm sure they exist - same issue.

Is this a know issue? Or what am I missing?

**Comment by ChrisChinchilla** [comment]
I'll take a look as soon as I can but I am travelling and checking out the extensions repo take a lot of data :(

**Comment by zenminimalist** [comment]
I'm still seeing the same behavior. Anything I can try to see why this problem is occurring?

**Comment by ChrisChinchilla** [comment]
@zenminimalist Do you have the most up to date version? It is working for me now…

**Comment by zenminimalist** [comment]
> @zenminimalist Do you have the most up to date version? It is working for me now…

Yes, it was and is still the most current version. Have no clue why I had this issue. But the re-installation (no other chanes were made) solved it for some reason.

Thanks for the quick reply though!
