### ISSUE TITLE
[Image Modification] Can you add support for Path Finder

### ISSUE THREAD

**Issue by tianwg** [raycast/extensions#5587]
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

When I use with an image in path finder it says image not found. Can you add an option to select or set an alternative file manager like path finder

### Who will benefit from this feature?

Anyone who use different file manager

**Comment by SKaplanOfficial** [comment]
I'll look into this -- should definitely be possible for Path Finder, not sure about other file managers though.
