### ISSUE TITLE
[GitLab] Search all issues, not just the ones created by me

### ISSUE THREAD

**Issue by href** [raycast/extensions#5588]
### Extension

https://www.raycast.com/tonka3000/gitlab

### Description

The GitLab extension is really great, but something confused me for a while. The action "Search GitLab Issues" does not search all issues, it just searches issues created by myself:

https://github.com/raycast/extensions/blob/a7db609f05058b76a27ca18e709402d5ccac2292/extensions/gitlab/src/components/issues_search.tsx#L12

Would it be possible to make it an option to search all issues?

If not, might it make sense to rename the action to "Search GitLab Issues Created by Me"?

As it stands, I find it confusing, and I thought at first, that the search might not work right.

**Comment by tonka3000** [comment]
Hi @href,

> The action "Search GitLab Issues" does not search all issues, it just searches issues created by myself:

This has multiple reasons.

1. It works similar to the GitHub extension `Search Issue`
2. This is also the default on GitLab webpage

> Would it be possible to make it an option to search all issues?

That could be tricky or in extreme cases problematic. The GitLab webpage `Search Issue` page e.g. does set the requirement that you need at least one filter.
The API itself does not have this, but you mostly get a 500 status back when you have no filter.

So GitLab has a problem with a lot of hits in the search, especially on gitlab.com, not quite sure why.

> If not, might it make sense to rename the action to "Search GitLab Issues Created by Me"?
 
I would go with `Search My Created Issues`

> As it stands, I find it confusing, and I thought at first, that the search might not work right.

Yeah, this can be confusing in the beginning.

## Possible Solutions

### Via Projects
In general you have always the option to search for issues in the project. Just select a project e.g. with `My Starred Projects` and it will set the project a filter. 

### Rename the Command

Rename the command would make the actual impl. more obvious but I wanna have the option for the future to switch between created, assigned and mentioned directly in one command.

In general I would love to have a Search All Issues (where you have a least developer permissions) Command. But I think I need to wait until all GitLab instances can handle that.

**Comment by href** [comment]
Thank you for your thorough response. I see how this makes sense in the case of GitLab.com. I didn't think of that, since we use our own instance, where the search defaults to all projects in my tests.

Since the API does not have this limit, maybe it would be an option to make that configurable, for managed instances (i.e., anything not pointing at gitlab.com)?

I could go via projects, but that would require a bunch of steps, instead of a single one. That is, for now it's easiest for me to just use a quick link to the site search of our instance, though it lacks the auto-completion fidelity of your extension of course.

Thanks in any case, I derive a lot of value from your extension as is already!

**Comment by tonka3000** [comment]
I checked the endpoint on a private instance and the endpoint works as excepted so adding the feature should be doable.

I will try to integrate that with the dropbox in the right upper corner in the existing command (if it does not work well I will make another root command). This will take some time because many things to do right now.

**Comment by href** [comment]
Thank you. No problem if it takes time!

**Comment by tonka3000** [comment]
> Is there any way for me to configure this as the default?

Not for now. Maybe a preference for that command to set? Or there would be the option to remember the last option which was set.

**Comment by href** [comment]
Maybe this is actually something that Raycast should do on its own (remember the last selected option). For now, I noticed that I can quickly switch using Command+P, so no need to put any more energy into this.

**Comment by tonka3000** [comment]
There is an option in raycast to remember the last action.

**Comment by href** [comment]
That seems like something I would activate, but I leave it up to you. Thanks again.
