### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by brandoncarl** [raycast/extensions#5595]
### Extension

https://www.raycast.com/ernest/focus

### Description

The Focus (Custom Duration) is not treated as a Timed Session. As such, the user can still trigger Unfocus.

This should instead be treated as a Timed Session and work in the same way that Focus (25 Minutes) works.

### Steps To Reproduce

Run the Raycast command Focus (Custom Duration) and use 0 hours and 10 minutes.

### Current Behaviour

The command does not treat this as a Timed Session.

### Expected Behaviour

The command treats this as a Timed Session.

**Comment by namzo** [comment]
@brandoncarl Thanks for sharing. I just tried it and you're right, only the "hours" field works for some reason.

I'll take a look and push a fix.

**Comment by brandoncarl** [comment]
Thanks for your great work, much appreciated.

**Comment by namzo** [comment]
I just pushed a fix for this https://github.com/raycast/extensions/pull/5603

@raycastbot close this issue
