### ISSUE TITLE
[System Settings] extension only search for one level

### ISSUE THREAD

**Issue by couillonnade** [raycast/extensions#5596]
### Extension

 System Settings Extension

### Description

The System Settings extension only search for one level. For instance, if you search for "hot corner" it does not find anything. Spotlight is able to find any elements in settings. 

System Settings extension is not in the store but part of the extension in Raycast.

### Steps To Reproduce

1. Open Raycast
2. Search for "hot corner"
3. no results

### Current Behaviour

Only finds elements in the first level of System Settings

### Expected Behaviour

Should find any element at any level

**Comment by couillonnade** [comment]
Extension is not visible in the store

**Comment by unnamedd** [comment]
> Has this been evaluated?

Hi @couillonnade 👋 , 
what you are trying to report here there is no relation to any extension, to report something you believe is not working properly, you must use the _**Send Feedback**_ form from inside of Raycast or use the channel #bugs in the Raycast Community on Slack (https://raycast.com/community).

**Comment by couillonnade** [comment]
Gotcha. Will do!
