### ISSUE TITLE
[Bitwarden Vault] Raycast extension not allowing access to the vault even with the client id and client secret. Tried rotating the api keys to no effect. Started after a reinstall to try and get touch id access to the raycast extension instead of having to fill master password all the time

### ISSUE THREAD

**Issue by kdjalexander** [raycast/extensions#5607]
### Extension

https://www.raycast.com/jomifepe/bitwarden

#### Error:
```
Error: Command failed with exit code 1: /opt/homebrew/bin/bw lock
You are not logged in.

at:error.js:59:10
search.js:18:4889
```

### Current Behaviour

Error when trying to set up raycast extension to give access to vault.

Started after a reinstall due to another error, not being able to access the vault using touch id.

### Expected Behaviour

Gain access to vault,
Touch id to unlock vault

**Comment by jomifepe** [comment]
Sorry for the issue, just opened a [PR](https://github.com/raycast/extensions/pull/5609) to fix this

**Comment by jomifepe** [comment]
Should be fixed now, take a look
