### ISSUE TITLE
[Easy Dictionary] ...x2: The operation was aborted.  c:index.js:70:17 AbortSignal.m:easydict.js:162:17318 [nodejs.internal.kHybridDispatch]:event_target:731:20 AbortSignal.dispatchEvent:event_target:673:26

### ISSUE THREAD

**Issue by mobowp** [raycast/extensions#5612]
### Extension

https://www.raycast.com/isfeng/easydict

#### Error:
```

```

**Comment by mobowp** [comment]
x2: The operation was aborted.

c:index.js:70:17
AbortSignal.m:easydict.js:162:17318
[nodejs.internal.kHybridDispatch]:event_target:731:20
AbortSignal.dispatchEvent:event_target:673:26

**Comment by tisfeng** [comment]
Thank you for the feedback, I am aware of this issue https://github.com/tisfeng/Raycast-Easydict/issues/35 and will submit a PR to fix it soon.

If you can't wait, you can try using the latest code from the repository https://github.com/tisfeng/Raycast-Easydict

**Comment by tisfeng** [comment]
@raycastbot close this issue
