### ISSUE TITLE
[Brew] Managing services

### ISSUE THREAD

**Issue by Sulfyderz** [raycast/extensions#5616]
### Extension

https://www.raycast.com/nhojb/brew

### Description

Hello,

Could you integrate the features of the other Brew Raycast extension aiming at managing the services (https://www.raycast.com/es183923/brew-services)? Currently we have to install two Raycast extensions for Brew. It's kind of annoying. It would be great if we can turn on or turn off services.

Best,

### Who will benefit from this feature?

Anyone using services from brew.

**Comment by nhojb** [comment]
Yeah, I think this is a good idea. We could integrate the services functionality and potentially deprecate the brew services extension.
