### ISSUE TITLE
[Apple Notes] ... "Cannot search notes. Database disk image is malformed"

### ISSUE THREAD

**Issue by pankajkaram** [raycast/extensions#5619]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

On searching for notes within raycast, can see this error at the bottom "Cannot search notes. Database disk image is malformed"

It is able to search notes titles but not within notes (body, description)

**Comment by andrewcincotta** [comment]
I'd like to bump this issue. Any solutions?

**Comment by rfscouto** [comment]
I also face this issue. Uninstalling and reinstalling the extension does not work.

**Comment by rfscouto** [comment]
I've exported my Raycast settings, uninstalled Raycast and reimported the settings. Now I don't get the issue anymore. Hope this helps figure out the root cause.

**Comment by StevenRCE0** [comment]
Yup, I also encountered the issue for a few times. Typically, the error disappears after a while. But none of us contributors have figured it out. 😣

**Comment by melwan** [comment]
Simply restarting my MacBook fixed it for me. Running MacBook Air (M2).
