### ISSUE TITLE
[Easy Dictionary] Show me the "something went wrong"

### ISSUE THREAD

**Issue by dxkrs** [raycast/extensions#5627]
### Extension

https://www.raycast.com/isfeng/easydict

#### Error:
```
x2: The operation was aborted.

c:index.js:70:17
AbortSignal.m:easydict.js:162:17318
[nodejs.internal.kHybridDispatch]:event_target:731:20
AbortSignal.dispatchEvent:event_target:673:26
```

### Steps To Reproduce

Show me the "something went wrong" after show the translation content.

**Comment by tisfeng** [comment]
I don't know what your error message is. 

But I did find some issues with my code before, and I have already submitted a PR https://github.com/raycast/extensions/pull/5615  to fix it.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/25194972/228419547-6391615c-1f09-41e8-b2c1-60ef09a2d952.png">

**Comment by tisfeng** [comment]
A new version has been released, please give it a try.

**Comment by dxkrs** [comment]
Yes,it is fixed!
