### ISSUE TITLE
[Extension Bug] Speedtest failed - unknown system

### ISSUE THREAD

**Issue by tmarsik42** [raycast/extensions#563]
# Extension – [Speedtest](https://github.com/raycast/extensions/tree/c33ee380a4b1c3a3beb0fa2eee075aea9f5c1514/extensions/speedtest/)
Author: @tonka3000 

## Description
launching Speedtest command throws error -86
<img width="797" alt="Snímek obrazovky 2021-12-22 v 0 19 18" src="https://user-images.githubusercontent.com/95856146/147010025-7d364249-8c33-4e18-8eba-5b5cacfabe98.png">

I have M1 macbook if that changes anything

## Steps To Reproduce

1. open raycast
2. run 'Speedtest'

### Raycast version
Version: 1.26.3

**Comment by tonka3000** [comment]
@tmarsik42 Use the "Clear CLI Cache" action and restart the whole command. Maybe this can fix it.

In general the Speedtest run on M1 with Rosetta2.

**Comment by tmarsik42** [comment]
Trying to run Raycast with Rosetta did it for me. Thank you, that was a new piece of information for me.
