### ISSUE TITLE
[1Password] Copying password appears to add a newline character at the end of it

### ISSUE THREAD

**Issue by igniscyan** [raycast/extensions#5630]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Was driving me crazy why copying from this extension would have all my logins fail. It is appending a newline at the end of every password.

### Steps To Reproduce

Copy password, get newline.

### Current Behaviour

New line is added at the end of my password

### Expected Behaviour

No new line at the end of my password

**Comment by pernielsentikaer** [comment]
I tried to reproduce this but I'm not able to, it seems like it never adds newline for me 😞
