### ISSUE TITLE
[Visual Studio Code - Project Manager] Add support for VSCode cached projects

### ISSUE THREAD

**Issue by HenryTSZ** [raycast/extensions#5632]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

Add support for VSCode cached projects

now, has Git cached and any cached, but don't has VSCode cached

I hope add VSCode cached

**Comment by MarkusLanger** [comment]
@HenryTSZ This Raycast extension is only for VSCode Project Manager projects.

**Comment by MarkusLanger** [comment]
Thanks for the screenshot. I will have a look.

**Comment by MarkusLanger** [comment]
@HenryTSZ PR created #5665

**Comment by HenryTSZ** [comment]
@MarkusLanger thank you very much!

**Comment by MarkusLanger** [comment]
@raycastbot close this issue
