### ISSUE TITLE
[Brew] I don't know what error is this, please check

### ISSUE THREAD

**Issue by chumido98** [raycast/extensions#5634]
### Extension

https://www.raycast.com/nhojb/brew

### Description

i runed command "Show Installed" and get this error. Please check

Error: Command failed: /usr/local/bin/brew info --json=v2 --installed
Error: no implicit conversion of nil into Hash
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:260:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `refresh'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:86:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:76:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:387:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:125:in `block in os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:299:in `to_h'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `map'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `print_json'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:110:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

    at ChildProcess.exithandler (node:child_process:412:12)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:313:12)

**Comment by chumido98** [comment]
> Could you attach the output of running `/usr/local/bin/brew info --json=v2 --installed`. Thanks.

Yes of course. Here:

Error: no implicit conversion of nil into Hash
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:260:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `refresh'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:86:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:76:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:251:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:387:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:125:in `block in os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:123:in `os_versions'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:299:in `to_h'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `map'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:232:in `print_json'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:110:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

**Comment by nhojb** [comment]
Right, looks like there's something wrong with your brew installation. Could you try reinstalling brew? Then try again.

**Comment by chumido98** [comment]
> Right, looks like there's something wrong with your brew installation. Could you try reinstalling brew? Then try again.

Will all packages be deleted when i reinstall brew? Is there any change i can keep them

**Comment by nhojb** [comment]
> Will all packages be deleted when i reinstall brew? Is there any way i can keep them

I don't think so. You could try running `brew doctor` first and see if that suggests a fix.

If `brew leaves` works then you can also backup your installed formulae like this:

```
brew leaves > my_brews.txt
```

Then after re-installing brew you can install the formulae like this:

```
brew install $(cat my_brews.txt)
```

**Comment by chumido98** [comment]
It worked. Thank you very much.
