### ISSUE TITLE
[Extension Bug] 

### ISSUE THREAD

**Issue by saforem2** [raycast/extensions#564]
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/main/extensions/*)

Author: @marcjulianschwarz 

## Description
The description reads

> Search, open, view, copy, paste and edit any note in Obsidian

but the extension only provides the search command 
![img1](https://user-images.githubusercontent.com/5234251/147151487-67349b9a-13cc-4c1e-85fc-7173104788b2.png)
![img2](https://user-images.githubusercontent.com/5234251/147151552-ea1bed94-fa4b-4fad-a34b-ade27a0de1bd.png)

## Steps To Reproduce

1. None
2.

### Raycast version
Version: 1.26.3

**Comment by marcjulianschwarz** [comment]
This is expected behavior.
You can open, view, copy, paste and edit a specific note if you search for it in the search command and use actions which can be executed with keyboard shortcuts. You can view them with `cmd+k`.

**Comment by saforem2** [comment]
ahhhhh, I see now. sorry for the confusion!

closing

**Comment by marcjulianschwarz** [comment]
No problem.
