### ISSUE TITLE
[GitHub] I cannot see PRs from private repos

### ISSUE THREAD

**Issue by the21st** [raycast/extensions#5644]
### Extension

https://www.raycast.com/raycast/github

### Description

I signed in with Github but I cannot see my pull requests from private repos. I tried signing out and back in again, but never do I get prompted about granting access to private repos.

**Comment by thomaslombart** [comment]
Could you share a recording to see what's the problem in particular? It'd be useful to know:
- Which commands you use
- If you got some results
- Which PRs you couldn't see

**Comment by the21st** [comment]
@thomaslombart 

- I use the "My Pull Requests" command
- I am getting results only for PRs from public repos
- I cannot see PRs from private repos of https://github.com/deepnote/

**Comment by the21st** [comment]
@thomaslombart I don't know how to do that. Could you point me to the documentation? I tried looking for it but I only found this: https://github.com/raycast/extensions/blob/24d1c59f3bdc540d672d78d986f7b63e4c117057/extensions/github/README.md

**Comment by unnamedd** [comment]
@the21st you can generate a Personal Access Token for you in this link: https://github.com/settings/tokens

**Comment by the21st** [comment]
Raycast unfortunately doesn't display the full error message:

![image](https://user-images.githubusercontent.com/4610874/231461296-877dec2b-79d4-42c7-a9aa-77f8a2ad3970.png)

**Comment by the21st** [comment]
Update, even after I added the personal access token and received no error in the "My pull requests" view, I cannot see my PRs from private repos:

![image](https://user-images.githubusercontent.com/4610874/231461699-89bd7dcf-ce09-4a7c-8e9c-6554d867f1a7.png)

**Comment by unnamedd** [comment]
> @unnamedd Thanks! What scopes does the extension need?

Inside of Raycast Preferences > Commands > GitHub, you should see, but here it goes: 
```
notifications repo read:org read:user read:project
```

**Comment by thomaslombart** [comment]
Indeed, you can see the scopes in the preferences as @unnamedd said. That's a good point, though, I'll add some notes to the `README.md` file.

**Comment by the21st** [comment]
> Inside of Raycast Preferences > Commands > GitHub, you should see, but here it goes:
> 
> ```
> notifications repo read:org read:user read:project
> ```

Thanks for the list! 

FYI, I cannot see in the raycast app:

![image](https://user-images.githubusercontent.com/4610874/231476343-ae1dca52-0bb0-4250-ae9e-8ae7f7a726f9.png)

**Comment by unnamedd** [comment]
@the21st do you still need any help to solve this issue? If not, would be very kind of you if you to close this issue.

**Comment by the21st** [comment]
My issue is resolved, thanks!
