### ISSUE TITLE
select spaces with command P , show only active open tabs first, show other tabs after [Arc] ...

### ISSUE THREAD

**Issue by tino963** [raycast/extensions#5654]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

I think this extension can be much improved, first by letting us select the workspace with command p, and showing only tabs belonging to the activated workspace we select and only the active most recent listed, and the rest should go after and also also allow going into folders if we choose,

**Comment by cyxn** [comment]
Not sure if the initial topic is about that, but I'd benefit from searching tabs in the current space. 
Let's say I just close the arc's sidebar and can switch my tabs of current space using the raycast exclusively. It could be a separate command for searching tabs within current space

**Comment by cyxn** [comment]
@thomaspaulmann @pomdtr @zach-fuller @ankitchouhan1020 @pernielsentikaer 
is that even possible using AppleScript. I'm not really familiar with it? I can consider contributing to this extension if there is a way to identify the following:
- current workspace (and tabs within current workspace)
- folder items
- toggle (open/close) these folders
