### ISSUE TITLE
[Google Chrome Profiles] ...

### ISSUE THREAD

**Issue by daverad** [raycast/extensions#5656]
### Extension

https://www.raycast.com/frouo/google-chrome-profiles

### Description

I'd like to be able to switch chrome profile via the extension, without it loading a new tab. (If that is already possible apologies, just couldnt figure it out >.<)

thanks!

### Who will benefit from this feature?

anyone who uses this extension to frequently switch profiles without the need to create a new tab or new search

**Comment by frouo** [comment]
Hello, unfortunately it is not possible :( At least I didn't find a way to for the moment and time available.
