### ISSUE TITLE
[Apple Notes] Action to create a deep link to open a specific note in Notes

### ISSUE THREAD

**Issue by dreasan** [raycast/extensions#5658]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

I really appreciate this extension, and use it quite a bit to get to my notes. One thing that would make it even better would be an action to be able to create a deep link ~~similar to the one that can already be created to search for notes:~~

~~raycast://extensions/tumtum/apple-notes/index?fallbackText=Recipe~~

~~The link searches for all notes containing recipes. Nice!~~

~~Additionally, I would now want to be able to link to notes directly and open them. Therefore, an idea:~~

Could we create a new action in the note search results to immediately create a deep link to open the note in Notes?

~~raycast://extensions/tumtum/apple-notes/open?fallbackText=Best%20Chocolate%20Chip%20Cookie%20Recipe~~

notes://showNote?identifier=UUID

EDIT: Changed to Apple notes URL scheme. See comments below, for an explanation, why the Raycast URL scheme was suggested at first.

### Who will benefit from this feature?

All users who would want to link to notes from other applications (writing tools, task managers etc.).

**Comment by StevenRCE0** [comment]
I think it's beyond Raycast Deeplink's purpose and seems like a detour. 
You may have a look at [a discussion about Apple Notes URL schemes](https://developer.apple.com/forums/thread/701574) which is likely a better way to jump into some specific note.

**Comment by dreasan** [comment]
Yup, I agree with @SKaplanOfficial.

My initial request/idea was based on the _false_ assumption that the Apple Notes URL scheme is not working (anymore), based on another discussion and a failed self-test.

However, the link you provided to the Apple forum discussion made clear that I used a wrong scheme, and it actually works. I could now successfully open a note by using:

`notes://showNote?identifier=UUID`

Therefore, I would amend the initial request toward the use of the Apple Notes URL scheme.
Meaning, the notes search result list (Search Notes command) should offer an Action to get the note UUID (Copy Note ID). Or, even better: The URL to open the note (Copy Note Link). The ID is probably already known to Raycast at that point.

I believe it would be useful, especially since it opens the door to easy internal linking in notes without first sharing these via iCloud, and as @SKaplanOfficial mentioned, these IDs are not directly accessible anywhere else in Notes.

**Comment by StevenRCE0** [comment]
It makes sense and also quite easy to implement. I'm working on it!

**Comment by StevenRCE0** [comment]
Here I would begin a discussion:
- Only iCloud notes are shown in sqlite database(for example, "On My Mac" notes are absent in my tests), and we could get promising URLs for those ones. 
- With `mobilenotes://` instead of `notes://`, we can make the URL work on iOS! I think that's also quite helpful. 
- I see the other contributors tried to exclude those Recently Deleted notes from SQL query, but they're later reloaded from AppleScript calls. AppleScript can't really tell if a note is Recently Deleted, if we take in i18n considerations. 
- I prefer to add an option to disable AppleScript fetching, but make it turned off(use AppleScript) by default.

**Comment by SKaplanOfficial** [comment]
The script [here](https://discourse.hookproductivity.com/t/using-the-built-in-notes-url-scheme/6071) uses AppleScript and sqlite3 to get the selected note URL with AppleScript -- shouldn't be too difficult to modify this to get the deeplink of any particular note. Still doesn't work for "On This Mac" notes, but it seems like those just don't support deeplinks at all.

I think an Action to copy the deeplink for the current note in the Search Notes list is the most reasonable thing, compared to a script command, etc. 

As for what to do with deleted notes, I'll leave this to others as I have the questionable habit of never deleting notes.

**Comment by StevenRCE0** [comment]
> The script [here](https://discourse.hookproductivity.com/t/using-the-built-in-notes-url-scheme/6071) uses AppleScript and sqlite3 to get the selected note URL with AppleScript -- shouldn't be too difficult to modify this to get the deeplink of any particular note. Still doesn't work for "On This Mac" notes, but it seems like those just don't support deeplinks at all.

Yep, I've seen the post. However, isn't it a subset of what we've got in the database?

**Comment by SKaplanOfficial** [comment]
Yes, I believe so, however it provides a way to get the UUIDs for the deleted notes currently obtained via AppleScript. That's for if you want to support deeplinks for deleted notes too without changing the AppleScript fetching approach.

**Comment by StevenRCE0** [comment]
> Yes, I believe so, however it provides a way to get the UUIDs for the deleted notes currently obtained via AppleScript. That's for if you want to support deeplinks for deleted notes too without changing the AppleScript fetching approach.

https://github.com/raycast/extensions/blob/9064cbca84b1cca1295b6efc566bec9f71efe98c/extensions/apple-notes/src/useSql.ts#L110

This query excludes the deleted on purpose.

**Comment by dreasan** [comment]
> * Only iCloud notes are shown in sqlite database(for example, "On My Mac" notes are absent in my tests), and we could get promising URLs for those ones.

I could find the local notes in the tests in the SQL lite database, specifically the ZICCLOUDSYNCINGOBJECT table.

My method:
1. Created a new local note titled New local note.
2. Used [this](https://www.icloud.com/shortcuts/e370c4eacc7441a18e7ec95667b2e32f) Shortcut to search for the local note.
3. Used the graph viewer to navigate and view the _note_ object.
4. Copied the UUID from the URL inside the object: `notes://showNote?identifier=UUID`
5. Queried with `SELECT * FROM ZICCLOUDSYNCINGOBJECT WHERE ZIDENTIFIER = '<UUID>';`

For me, this returned the note data for the _On my Mac_ note. I am uncertain if it had to do with the fact that I created a fresh note. I normally do not use the local note account.

**Comment by dreasan** [comment]
> I think an Action to copy the deeplink for the current note in the Search Notes list is the most reasonable thing, compared to a script command, etc.

I would prefer an action too.

**Comment by dreasan** [comment]
> * With `mobilenotes://` instead of `notes://`, we can make the URL work on iOS! I think that's also quite helpful.

Yes, I think both make sense. If I had to choose, though, I would go for `notes://`. Considering Raycast has a macOS focus.

**Comment by StevenRCE0** [comment]
It rocks! The best approach is to fetch everything through db and ditch AppleScript fetching entirely. It'll not only solve this URL problem but also increase performance significantly.

 I'm busy recently so no tests were done. Feel free to contribute!

**Comment by SKaplanOfficial** [comment]
@dreasan Yep, seeing that on my end too. I thought it was working before, but I'm probably remembering wrong. In any case, I'll fix that soon when I work on #5968 and #5619.
