### ISSUE TITLE
[Color Casket] Names for favourite colors

### ISSUE THREAD

**Issue by juhamust** [raycast/extensions#5666]
### Extension

https://www.raycast.com/slava.razum/color-casket

### Description

Color Casket -extension provides a nice list of features to render colors, including color favorites. However, identifying the favorite colors would be easier if one could give a custom name for them.

![image](https://user-images.githubusercontent.com/781002/228796806-e42ccab0-24f1-49e8-959c-dd27a674fa89.png)

### Who will benefit from this feature?

Corporate users, designers, and developers alike.

**Comment by slavarazum** [comment]
Nice suggestion 👍 Took it into todo list.

**Comment by texastoland** [comment]
Please reopen 🙏🏼 @slavarazum

**Comment by slavarazum** [comment]
@texastoland Took it into a near plan.
