### ISSUE TITLE
[One Thing] ...

### ISSUE THREAD

**Issue by ratinevo** [raycast/extensions#5668]
### Extension

https://www.raycast.com/pernielsentikaer/one-thing

### Description

Error: Cannot find module './react-reconciler.production.min'
Require stack:
- /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/index.js
- /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js

Require stack:
- /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/index.js
Module._resolveFilename:loader:985:15

**Comment by pernielsentikaer** [comment]
Hi @ratinevo 👋 

I'm not able to reproduce this, can you add some steps to reproduce this?
