### ISSUE TITLE
[Jira] Unable to authorize

### ISSUE THREAD

**Issue by Reiner0** [raycast/extensions#5670]
### Extension

https://www.raycast.com/raycast/jira

### Description

I switched to this new version of the Jira extension, when attempting to authorize/login, I am receiving this error message from Jira:

This app requires access to a Jira & Jira site which you don’t have or don’t have the permission to access.

With the previous extension I was able to sign into my Jira account with no issues.  My org uses Jira Cloud.

### Steps To Reproduce

1. Installed the extension
2. Found one of the commands, i.e. Create Issue
3. Click the Sign in With Jira button
4. Browser opens to Jira Authorize App page
5. See the error

**Comment by thomaslombart** [comment]
Thanks for bringing up this issue, I'll investigate that in the next few days or weeks.
