### ISSUE TITLE
[Jira] ... only shows the first 50 projects, cannot create an issue in project with identifier starting with `U`

### ISSUE THREAD

**Issue by qbunt** [raycast/extensions#5676]
### Extension

https://www.raycast.com/raycast/jira

### Description

Currently cannot `Create Issue` on the Jira project I'm on because I cannot access the project in the search list when creating an issue.

Moving to the new Jira extension and authorizing it, I only see the first 50 projects in my Jira account. We work with many clients, so we have many projects inside our Jira account, but the projects with identifiers (for example starting with the letter `U`) I cannot search for in the `Create Issue` action, but I can see inside `Search Issues` with the same project ID. 

### Steps To Reproduce

1. Authorize Jira
2. Attempt to `Create Issue`
3. Try searching for the correct project (in this case starting with `U`)
4. Cannot find project in the list at all, list is truncated to 50 items

### Current Behaviour

Cannot create issue with project identifier starting with `U`

### Expected Behaviour

Should be able to create an issue with any project in my jira account

**Comment by thomaslombart** [comment]
Thanks for bringing up this issue, I've added it to our backlog and will work on it in the next few weeks.

**Comment by qbunt** [comment]
@thomaslombart I see the hard limit of 100, but for whatever reason, we're getting truncated at 50, honestly this could be the Jira API limiting you too, but the outgoing extension didn't do this, so 🤷 let me know if it needs another look, thanks!

**Comment by qbunt** [comment]
@thomaslombart thanks for handling this quickly, went to try the same thing today and it worked, product is absolutely killer, keep it up
