### ISSUE TITLE
[Search npm Packages] faster access to packages when you know the name

### ISSUE THREAD

**Issue by mattfysh** [raycast/extensions#5679]
### Extension

https://www.raycast.com/mrmartineau/search-npm

### Description

When you know the name of the library but want to quickly open the github repo or npm page (e.g. to see the code or readme), it would be great to skip the searching and open the predictable URL asap

I had a similar setup with Alfred where I'd hit cmd+space and then type "n lodash" and press enter, and it would automatically open to the npm page, in this example https://npmjs.org/package/lodash

### Who will benefit from this feature?

Developers in a panic

**Comment by mrmartineau** [comment]
I think a Raycast quicklink would work best for what you need here, have you tried it? You could use this: 
```
https://www.npmjs.com/package/{Query}
```
which would get you to the npm package page, or event [njt](https://njt.vercel.app/) as a script command, which I have. See the one I created ages ago: https://github.com/raycast/script-commands/blob/master/commands/web-searches/njt.sh
