### ISSUE TITLE
[GitHub]  Background refresh for PRs

### ISSUE THREAD

**Issue by MrBerkalp** [raycast/extensions#5684]
### Extension

https://www.raycast.com/raycast/github

### Description

Usually it takes the Github extension up to 7-8 seconds to refresh Pull Requests. Background refresh would greatly improve usability since the user would have the latest info without waiting.

### Who will benefit from this feature?

All users who have PRs being constantly assigned to them.

**Comment by thomaslombart** [comment]
Thanks for your input! This is something a bit tricky to implement as of now. But that's something we want to look into in the future 😊
