### ISSUE TITLE
[ChatGPT] ...

### ISSUE THREAD

**Issue by PeterJohannsenCMT** [raycast/extensions#5686]
### Extension

https://www.raycast.com/abielzulio/chatgpt

#### Error:
```
Error: Request failed with status code 401

hs.exports:createError.js:16:14
bs.exports:ask.js:2:7730
IncomingMessage.<anonymous>:ask.js:7:11807
IncomingMessage.emit:node:events:525:35
```

### Steps To Reproduce

I just installed it, and I entered my API key, which I obtained on the openai page. When I (for instance) select Ask Question in Raycast after about half a second it just says "Something went wrong" with the error above. So I cannot use the extension at all, unfortunately

**Comment by abielzulio** [comment]
Hi, I'm sorry for what's happening to you.

Have you double-checked your API key to ensure that it is not misspelled or mistyped? If so, have you tried reinstalling the extension? @PeterJohannsenCMT

**Comment by abielzulio** [comment]
@raycastbot close this issue

Closing due inactivity
