### ISSUE TITLE
[Google Maps Search] ...

### ISSUE THREAD

**Issue by marclar** [raycast/extensions#5690]
### Extension

https://www.raycast.com/ratoru/google-maps-search

### Description

It seems the plugin automatically pastes the content of my clipboard into the textbox where I intend to type my destination. This is always confusing and not at all how I'd expect it to work. I arrive on the screen with some jumble of text, I think it's an API key or something, and have to remember that no, I just need to enter a rough address.

Please change the behavior or at least make it optional.

Thanks!

### Who will benefit from this feature?

Everyone?

### Anything else?

![image](https://user-images.githubusercontent.com/482690/229149583-e585e551-2149-4bb2-b11a-a2e1a65a4ba2.png)

**Comment by ratoru** [comment]
Hi @marclar! You’re absolutely right, this shouldn’t happen. One of the recent updates must have changed the behavior. I will try and fix it by the end of next week! 

Also see #5511

**Comment by ratoru** [comment]
Ok turns out the last contributor changed the behavior. I originally intended the extension to work the way you described. It's probably okay to change it back? Thoughts @marclar? Maybe I'll change the instant copy from clipboard to an opt-in option in the extension's preferences.

**Comment by chrismessina** [comment]
Autofill is now off by default.
