### ISSUE TITLE
[Simple Youdao Translate] ...

### ISSUE THREAD

**Issue by impeiran** [raycast/extensions#5692]
### Extension

https://www.raycast.com/xeric/simple-youdao

#### Error:
```
Error: Command failed: afplay "/tmp/tmp_raycast_simpleyd.mp3" -v 1
Error: AudioFileOpen failed ('dta?')


Error: AudioFileOpen failed ('dta?')
ChildProcess.exithandler:node:child_process:412:12
ChildProcess.emit:node:events:513:28
```

### Steps To Reproduce

1. try 'shift + enter' to prononce a word

### Current Behaviour

throw error

**Comment by xeric** [comment]
@impeiran I think you faced the same issue with this: https://github.com/raycast/extensions/issues/5366#event-8817609863, please check you have enabled the TTS function in your youdao account.

**Comment by impeiran** [comment]
Thanks for your help, it works!
