### ISSUE TITLE
[Bear Notes] 2.0/2.0 beta support. 

### ISSUE THREAD

**Issue by danmurpas** [raycast/extensions#5694]
### Extension

https://www.raycast.com/hmarr/bear

### Description

I currently can't get this to work in the 2.0 beta. Which I totally understand. Just sending this to let you know there are people out there that love this extension and would love an update! :) 

### Who will benefit from this feature?

everyone that uses bear and raycast.

**Comment by lucaschultz** [comment]
I opened pull request #5706 adding Bear 2 support to the extension 🙂

@raycastbot close this issue
