### ISSUE TITLE
Safe web page to the Wayback Machine

### ISSUE THREAD

**Issue by navratilkarel** [raycast/extensions#5699]
### Extension

https://www.raycast.com/pernielsentikaer/wayback-machine

### Description

Capture a web page as it appears now for use as a trusted citation in the future.

https://web.archive.org/save

### Who will benefit from this feature?

Everyone!

**Comment by andreaselia** [comment]
I don't think they allow this via a public API endpoint as they do the availability one unfortunately. I guess it may be possible to implement for those who wanted to use the extension with their own account setup with credentials to enter or something though 🤔

**Comment by SKaplanOfficial** [comment]
You can save a page with just a URL — `https://web.archive.org/save/theURL`

**Comment by andreaselia** [comment]
Ah nice, I didn't know that was a valid public endpoint, thanks @SKaplanOfficial 👍
