### ISSUE TITLE
[API Bug] useNavigation pop issue

### ISSUE THREAD

**Issue by ciiiii** [raycast/extensions#571]
Raycast version: 1.26.3

## Description

- First Menu: a List contains List.Item with PushAction to push Second Menu
- Second Menu: a List contains List.Item with PushAction to push Data Form
- Data Form: a form with SubmitFormAction will trigger `useNavigation.pop()` when submit

## Steps To Reproduce
[code example](https://github.com/ciiiii/raycast-navigation-bug)
1. trigger the PushAction of First Menu, you will go to Second Menu
2. trigger the PushAction of Second Menu, you will go to Data Form
3. submit the Data Form, you will back to Second Menu
4. back, you will back to First Menu
5. **trigeer the PushAction of First Menu, you will directly go to Data Form**

## The current behavior
STEP5: trigeer the PushAction of First Menu, you will go to Data Form

## The expected behavior
STEP5: trigeer the PushAction of First Menu, you will go to Second Menu

## Screenshots
<img width="791" alt="image" src="https://user-images.githubusercontent.com/28784251/147464573-1624273c-ab7f-4c03-ac03-2ad3853b507c.png">
STEP1
<img width="792" alt="image" src="https://user-images.githubusercontent.com/28784251/147464593-c67572f0-8fc9-4f8b-8204-485013ad369d.png">
STEP2
<img width="787" alt="image" src="https://user-images.githubusercontent.com/28784251/147464617-ed684d2a-a8ea-41ef-813e-9c8ce0ccaae4.png">
STEP3
<img width="785" alt="image" src="https://user-images.githubusercontent.com/28784251/147464638-cfaa63ff-1320-4287-b8dc-9b447206ce07.png">
STEP4
<img width="796" alt="image" src="https://user-images.githubusercontent.com/28784251/147464658-3d6f3e11-02ec-4f41-9f12-19c9e99df3b1.png">
STEP5
<img width="790" alt="image" src="https://user-images.githubusercontent.com/28784251/147464674-0bd5f176-4512-4359-b370-930669419a11.png">

**Comment by mattisssa** [comment]
Wow, this is the good catch! Thanks for describing it, we will investigate!
