### ISSUE TITLE
[Dropbox] ...

### ISSUE THREAD

**Issue by matthewjameslord** [raycast/extensions#5719]
### Extension

https://www.raycast.com/chyroc/dropbox

### Description

When trying to authorize app, get an error from dropbox saying that "This app is unable to link additional users because it has been frozen pending review.".

**Comment by chyroc** [comment]
dropbox oauth app need to production request.
i start this request.

**Comment by chyroc** [comment]
Help Needed: Need a new logo to pass dropbox's app review
