### ISSUE TITLE
[Jira] Can't find any issues

### ISSUE THREAD

**Issue by sebkolind** [raycast/extensions#5726]
### Extension

https://www.raycast.com/raycast/jira

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'name')

Xy:IssueListItem.tsx:15:40
    at ray-list-section
cs:index.js:23:15636
Or:index.js:5:5486
```

### Steps To Reproduce

1. Open Raycast
2. Install Jira extension
3. Authorise
4. Search for an issue

**Comment by thomaslombart** [comment]
They are three objects that can have the `name` property in `IssueListItem`: `status`, `issuetype`, and `priority`. I assumed these fields would always be defined since a Jira issue should always have a status, a type, or a priority 🤔
