### ISSUE TITLE
[Warp Launch Configuration] Forwards exported environment variables to Warp

### ISSUE THREAD

**Issue by dextermb** [raycast/extensions#5728]
### Extension

https://www.raycast.com/joetannenbaum/warp-launch-configuration

### Description

When launching via Raycast using the extension I've noticed that it's forwarding:
* `NODE_ENV`
* `NODE_PATH`

which are then causing issues when trying to develop for work/projects.

[Slack discussion](https://raycastcommunity.slack.com/archives/C028DTXTW3Y/p1680509569647559)

### Expected Behaviour

Environment variables from the plugin should not be passed onto the application

**Comment by thomaspaulmann** [comment]
You should be able to fix this by using the [`runAppleScript` util](https://developers.raycast.com/utilities/functions/runapplescript).

**Comment by joetannenbaum** [comment]
Thanks for the heads up, @thomaspaulmann. In the updated extension we're not using AppleScript at all anymore, but I'll grab that util in the future if we need to add it back in for some reason!

**Comment by thomaspaulmann** [comment]
Ah okay...
