### ISSUE TITLE
[GitHub] Multiple accounts

### ISSUE THREAD

**Issue by DominicVonk** [raycast/extensions#5731]
### Extension

https://www.raycast.com/raycast/github

### Description

Please enable multiple accounts

### Who will benefit from this feature?

Everyone with multiple github accounts

**Comment by thomaslombart** [comment]
Multi-account support is a commonly required feature that's tricky to implement right now, so I'm afraid it won't be possible to do that for the GitHub extension. You can follow the status of this feature request here: [#269](https://github.com/raycast/extensions/issues/269).
