### ISSUE TITLE
[OpenAI GPT3] Support GPT4

### ISSUE THREAD

**Issue by AdamPetroff** [raycast/extensions#5733]
### Extension

https://www.raycast.com/simicvm/openai-gpt3

### Description

Please support GPT4, love the extension

### Who will benefit from this feature?

me

**Comment by dylanjrae** [comment]
@simicvm maybe I am missing something but I don't see how to select any model other than these two:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/55325297/233698902-b4bd2f25-0e46-4dc7-85b5-717bd42d6d1e.png">

How do you actually use GPT4 when creating a new model?

**Comment by simicvm** [comment]
@dylanjrae  Can you please try to reinstall the extension? This is how it should look like. I can't reproduce the bug.

<img width="1000" alt="openai-gpt 2023-04-22 at 02 47 49" src="https://user-images.githubusercontent.com/13484398/233702203-2ac41a73-f21a-417e-a4ab-a429b63902f4.png">

**Comment by dylanjrae** [comment]
Reinstalled from store, no luck. I am not sure how the store works, maybe an out of date version is still up there? Is there a way I can stall directly?

**Comment by simicvm** [comment]
@dylanjrae   Actually you might be using a different extension. Your screenshot has a field “Pinned”, while mine doesn’t.

**Comment by dylanjrae** [comment]
@simicvm Fairly sure it is the same as this repo - when I click "About this extension" from my installed extensions, [this](https://github.com/raycast/extensions/blob/7f263e3d8fd926775eb223a5a18f177435db6839/extensions/chatgpt/README.md) is the link I get.

Perhaps this is an out of date version? Here is the full new model screen:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/55325297/233718799-3e52ec6c-90be-46e6-9c82-4b667ab45176.png">

**Comment by dylanjrae** [comment]
Never mind, I am looking at the wrong extension 🤦‍♂️

Thanks for the help.

**Comment by AbhishekTripathi** [comment]
@simicvm I see that the old extension was updated to the new one. The problem however is that the new extension doesn't support Azure AI like the old one. Request you to consider adding the support for it. Until then I am forced to use the old extension :(

**Comment by simicvm** [comment]
> @simicvm I see that the old extension was updated to the new one. The problem however is that the new extension doesn't support Azure AI like the old one. Request you to consider adding the support for it. Until then I am forced to use the old extension :(

hm, I am not sure that the old version supported Azure AI. You might be using another extension 🤔
