### ISSUE TITLE
[ChatGPT] Error message by using without selected text

### ISSUE THREAD

**Issue by wra1w0** [raycast/extensions#5734]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

I get an error message when I open the “Ask Question” command without selected text. But it doesn't impact command functionality in any way. I have the setting for autoload text on, and it works correctly when I select text in an application.

<img width="431" alt="Screenshot 2023-04-03 at 13 55 33" src="https://user-images.githubusercontent.com/47259322/229502683-73710a23-46ba-4f7c-aa66-3583e74e5fd4.png">

### Steps To Reproduce

1. Open Raycast.
2. Search for "Ask Question".
3. Open command.
4. You see the error massage.

**Comment by abielzulio** [comment]
Are you still facing this issue on a daily basis? @wra1w0

**Comment by wra1w0** [comment]
> Are you still facing this issue on a daily basis? @wra1w0

Don't use the extension anymore, because of Raycast AI. But I just reinstalled it and tested again, and I still got an error.

I think this is the function you use. 
```ts
 useEffect(() => {
    (async () => {
      if (isAutoLoad && !disableAutoLoad) {
        setLoading(true);
        try {
          const selectedText = await getSelectedText();
          if (selectedText.length > 1) {
            setData(selectedText.trim());
            await showToast({
              style: Toast.Style.Success,
              title: "Selected text loaded!",
            });
          }
        } catch (error) {
          await showToast({
            style: Toast.Style.Failure,
            title: "Selected text couldn't load",
            message: String(error),
          });
        }
        setLoading(false);
      }
    })();
  }, []);
```
When no text is selected, you throw the error message. But from a UX perspective, it's not so nice. Because if someone intentionally doesn't select some text, it shouldn't be an error. 

In my opinion, the better way may be to throw a success toast with text like "No text selected" etc. or an error toast without "Error"-word in the description.
