### ISSUE TITLE
[Bitwarden] Fill multiple parts at once

### ISSUE THREAD

**Issue by boehs** [raycast/extensions#5736]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Currently, if I am logging onto a website, I copy the username, paste it in, renter, hit enter to fill the password, renter, copy totp.

A much better flow would be something similar to the password paste where, with one keybinding, it does

`Username <Tab> Password <Enter???>` and copies the TOTP, like the bitwarden mobile app

**Comment by jomifepe** [comment]
Hey, thanks for the suggestion. That would be great, but I don't think it's currently possible to implement. As far as I'm aware, Raycast doesn't provide a way to perform multiple keystrokes, only paste something to the active app. 

One thing that will eventually be added is an option to choose whether to close the window when copying usernames/passwords. That way you can copy the username and password, paste the password, and then use the clipboard history to paste the username.

**Comment by jomifepe** [comment]
@raycastbot close this issue
