### ISSUE TITLE
[OpenAI Translator]  It would be great to add a two-way translation feature.

### ISSUE THREAD

**Issue by dylan237** [raycast/extensions#5738]
### Extension

https://www.raycast.com/douo/openai-translator

### Description

For example, as a native Chinese speaker, I can set my primary language to be Chinese and also set a target language. For instance, if I want my input to be translated into English, then I can set the target language as English. When I type in a non-Chinese language, the system will automatically recognize the language and translate it into the target language which is English in this case. If I type in my native language which is Chinese, then the system will default to translating it into my chosen target language which is English.

### Who will benefit from this feature?

I think the majority of users use translation tools mainly to translate unfamiliar languages. With this feature, users can input in their familiar language and get the another translation result. This issue was translated from Chinese to English through ChatGPT. If this feature can be added, it will allow users like me to achieve this goal more efficiently.

**Comment by douo** [comment]
Thank you, @dylan237.  Very helpful advice. However, the accuracy of language detection is only 55% now.(ref:https://github.com/yetone/openai-translator/pull/306)

After I implement a better replacement solution, I should be able to implement the auto invert function you mentioned.
