### ISSUE TITLE
[Jira] Cannot Create an Issue

### ISSUE THREAD

**Issue by karl00schmidt** [raycast/extensions#5740]
### Extension

https://www.raycast.com/raycast/jira

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'autoCompleteUrl')

Hy:CreateIssueForm.tsx:51:42
zU:create-issue.js:103:3897
Er:index.js:5:2490
    at ray-navigation-stack
```

### Steps To Reproduce

1. Open create an issue
2. A few seconds later, the app crashes with the above error.

**Comment by thomaslombart** [comment]
I pushed a change that should hopefully fix the issue. Could you let me know if you still have the problem?

**Comment by FezVrasta** [comment]
It fixed the issue for me

**Comment by thomaslombart** [comment]
Then, I'll close this issue. @karl00schmidt, feel free to reopen the issue if you're still getting the error 😊
