### ISSUE TITLE
[Dropbox] Error connecting app: This app is unable to link additional users because it has been frozen pending review.

### ISSUE THREAD

**Issue by silfves** [raycast/extensions#5741]
### Extension

https://www.raycast.com/chyroc/dropbox

### Description

Can't sign in to Dropbox due to this error

**Comment by chyroc** [comment]
same as https://github.com/raycast/extensions/issues/5719

**Comment by romanskorobagatko** [comment]
I have the same issue on latest Ventura 13.3.1

**Comment by chyroc** [comment]
Help Needed: Need a new logo to pass dropbox's app review

**Comment by apas** [comment]
[Here you go](https://i.postimg.cc/m2Sn2fJD/icon.png).

**Comment by bangroot** [comment]
This is still an issue - can we re-open it?

**Comment by lenart** [comment]
This is still an ongoing issue. With the latest changes to Mac file indexing, I really need this to start working :(
