### ISSUE TITLE
[Extension Bug] Can't get all history tab from multiple accounts in Chrome (google-chrome extension)

### ISSUE THREAD

**Issue by Crayon-ShinChan** [raycast/extensions#575]
# Extension – [google-chrome](https://github.com/raycast/extensions/tree/ca49a3c09c4d87814253f36599a14c1eb28be9a7/extensions/google-chrome/)

Author: Codely

## Description

I have two accounts in my Chrome browser but I can just get the chrome history from one of the accounts. The account that I can't get history by google-chrome extension is my primary account actually.

## Steps To Reproduce

1. login two google accounts in Chrome
2. try "search history" function from google-chrome extension

## The current behavior

just get the history of one account

## The expected behavior

get the history of all accounts

### Raycast version
Version: 1.26.3

**Comment by Crayon-ShinChan** [comment]
After I deleted the default account in my Chrome, which google-chrome extension can get the history correctly. I got the error.
![image](https://user-images.githubusercontent.com/38809606/147640020-6084f8a6-fc76-466e-b370-84b852cbe054.png)
```
Error: ENOENT: no such file or directory, open '/Users/bytedance/Library/Application Support/Google/Chrome/Default/History'
```

It seems that google-chrome can just get the history from the default account

**Comment by ryee-dev** [comment]
I'm having this issue right now actually.
