### ISSUE TITLE
[Toggl Track] Only show active projects

### ISSUE THREAD

**Issue by TweedBeetle** [raycast/extensions#5757]
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Description

Currently, all projects are listed, even archived ones. 
It would be nice if only active (not archived) projects where listed.

### Who will benefit from this feature?

People who have archived projects

**Comment by rogatty** [comment]
It should be enough to add `&active=true` or `&active=1` to https://github.com/raycast/extensions/blob/b62a4cac452b0fabe1e137ff3c5907886b45be0d/extensions/toggl-track/src/toggl/index.ts#L17 based on https://developers.track.toggl.com/docs/api/projects#get-workspaceprojects.
