### ISSUE TITLE
Open Browsers Profiles to add shortcuts for every profiles.

### ISSUE THREAD

**Issue by joescon** [raycast/extensions#5758]
### Extension

https://www.raycast.com/skydiver/browsers-profiles

### Description

Hello, thank you for this extension, it helps a lot. Could you add a function that it can set individual shortcuts for each profile, so that it can switch between profiles more convienient? Thank you.

### Who will benefit from this feature?

Everyone who has many browser profiles and needs to switch frequently.

**Comment by kytta** [comment]
See https://github.com/raycast/extensions/issues/17160#issuecomment-2667541303
