### ISSUE TITLE
[ChatGPT] Continuous mode of conversation

### ISSUE THREAD

**Issue by Monophonic1983** [raycast/extensions#5759]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

It would be great if the model supports continuous mode of conversation, which enables the gpt to remember the context. 

### Who will benefit from this feature?

Everyone

**Comment by abielzulio** [comment]
Hi! It's should be fixed on the 4/4/23 update.

@raycastbot close this issue
