### ISSUE TITLE
[Figma File Search] ...

### ISSUE THREAD

**Issue by ftinsel** [raycast/extensions#5761]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

I would like to disable the menubar helper

### Who will benefit from this feature?

Everyone on a laptop, we need to manage the numbers of applications in the menubar

### Anything else?

Thanks

**Comment by thomaspaulmann** [comment]
You can do that in our settings. Open `Raycast Settings -> Extensions -> Figma -> Quicklook` and then deactivate or disable the command.
