### ISSUE TITLE
[`@raycast/api`] Support yarn and pnp

### ISSUE THREAD

**Issue by CreatiCoding** [raycast/extensions#5762]
### Description

Hi, I have a suggestion of `@raycast/api` cli bin file.

I'm trying to use `@raycast/api` in yarn v3 + pnp environment, but `@raycast/api/bin/arm64/ray` was not support that environment. I think that cli bin file was not support yarn pnp environment.

I wanna make it to support but I can't find cli code. Where is it..? Is it private tool?

If I can have authority about read/write of `bin/ray`, can you make it support?

**Comment by mathieudutour** [comment]
unlikely to happen, the CI assumes that npm is used and there aren't too many advantages to use yarn or pnp now
