### ISSUE TITLE
[Jira] Filters selected through typeahead search are not persisted

### ISSUE THREAD

**Issue by tzookb** [raycast/extensions#5768]
### Extension

https://www.raycast.com/raycast/jira

### Description

when selecting "my filters", it loads all the filters, then loads the issues from the first filter.
It would be great if it can either remember the last used filter, or it would be able to set a default filter

### Who will benefit from this feature?

basically anyone that has filters

**Comment by thomaslombart** [comment]
It's supposed to be the current behavior. Here's what I have for example:

https://user-images.githubusercontent.com/16003285/230018255-f9fb16d2-f98f-4bba-ba20-20f9724264ea.mp4

What are you getting?

**Comment by tzookb** [comment]
that's weird...
for some filters it works as you shared, and for others it keeps resetting to the first one 🤷🏾‍♂️

**Comment by thomaslombart** [comment]
Could you share a recording? Or if not, do you recognize a pattern in what filters don't get saved?

**Comment by tzookb** [comment]
just tried forking and see how this works.
seems like:
`List.Dropdown`
keeps resetting to the the first filter.

But this happens only for my owned filters 🤷

**Comment by tzookb** [comment]
I was able to replicate on a different account. An seems like this happens only on filters I "own"

**Comment by thomaslombart** [comment]
I've shipped a fix that may close the issue @tzookb. Could you try it again and let me know if it works for you?

**Comment by tzookb** [comment]
thanks @thomaslombart 🙏 
just tried to pull latest and saw the changes, but this thing is still not behaving... super weird

https://www.loom.com/share/825ed8c2126b46299a7ada80f0cc084c

**Comment by thomaslombart** [comment]
Thanks for the recording, I get what's happening now. The filter is not in the list initially so the dropdown won't be able to restore the value since it doesn't see any corresponding in the list. I'll investigate potential solutions.

**Comment by svsool** [comment]
hey, encountered the same problem, would be great if last used filter will stay selected on re-issuing the command, thanks

**Comment by antoinerey** [comment]
Genuine question, would there be a way to re-install the "legacy" Jira extension in the meantime? I've removed it from my local Raycast install, and it's not showing up in the store anymore.

**Comment by tzookb** [comment]
Not sure what you mean by legacy. But if it's same extension bit older code.

Just pull this repository, checkout to the commit in the past that meets your requirement.

Run the app and you will get it

**Comment by thomaslombart** [comment]
Thanks for the kind feedback and your patience! 😊 

I know this has been opened for a long time but the fix isn't trivial. I'd like to get that done in the next few weeks.

**Comment by edosrecki** [comment]
@thomaslombart any news on this? 🙏

**Comment by thomaslombart** [comment]
Unfortunately, I didn't prioritize this during these last few months as I was focused on something else. I would like to tackle that at some point, but if it's urgent, you can also take a look at it. Here's our guide on contributing to extensions: [Contribute to an extension](https://developers.raycast.com/basics/contribute-to-an-extension).

**Comment by thomaslombart** [comment]
This has been fixed in https://github.com/raycast/extensions/pull/14459. Feel free to re-open this issue if you still can't persist filters.
