### ISSUE TITLE
[Image Modification] ...

### ISSUE THREAD

**Issue by jchap** [raycast/extensions#5778]
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

When I try to convert a .heic file it says no image selected.
Other file formats work fine
Not sure what version of the extension I have installed. Just installed it today (April 4th, 2023) from Raycast.com

MacOS 13.2.1
M1 MacBook Pro
<img width="568" alt="Screenshot 2023-04-04 at 9 30 24 PM" src="https://user-images.githubusercontent.com/3805932/229981377-26ee66c3-1064-4f70-96d6-7eaa9b162274.png">

### Steps To Reproduce

1. select .heic image on Desktop
2. hit hotkey to bring up Raycast
3. type convert  and hit enter
4. select png
5. hit enter
6. it gives an error at the bottom that says no image selected.

### Current Behaviour

can't convert .heic file to any format

### Expected Behaviour

convert .heic file to png or other file format

**Comment by SKaplanOfficial** [comment]
Hm, I'm not able to recreate this. What is the image kind reported in the "Get Info" panel for that file?

**Comment by jchap** [comment]
Thanks for taking a look.

In the get info panel the Kind is: HEIC Image.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SKaplanOfficial** [comment]
Interesting, all of my HEIC files show the kind as "HEIF Image". I can add the HEIC kind to the list of supported types, but I wonder why your heics are diferent from mine.

**Comment by jchap** [comment]
That is interesting. I tried exporting the HEIC file in Preview to HEIC and
it still shows up as HEIC Image in the get info pane. I tried to get info
on a bunch of other HEIC images and the same result - HEIC Image.
Bizarre. :)
