### ISSUE TITLE
[Flaticon — Search Icons] TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by wardweistra** [raycast/extensions#5786]
### Extension

https://www.raycast.com/bgnfu7re/flaticon

### Description

Searching for any icon gives the following error:
```
TypeError: Cannot read properties of undefined (reading 'map')
    at Object.Ua [as current] (/Users/ward/.config/raycast/extensions/a9fc4983-0104-49e7-9085-96532c312a46/commandSearch.js:30:11191)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

1. In MacOS, open RayCast
2. Type Icon and select Seach Icons (Flaticon)
3. Type `lavalier`
4. See the above error

### Current Behaviour

Error

### Expected Behaviour

Shows icons

**Comment by kudrykv** [comment]
Can you please reinstall and see if that works?
Also, can you please provide which Mac (intel, m1) you are on?
Can you validate that API key is correct?


https://user-images.githubusercontent.com/12697803/230125161-8f9eaf2a-756b-498e-bc61-f1096f03b3a5.mp4

**Comment by wardweistra** [comment]
Hi @kudrykv, thank you for checking. I reinstalled and all is working fine again for now. I'll let you know if it may ever break again.

I'm on a M1 mac.

**Comment by wardweistra** [comment]
@kudrykv It's back now though:
```
TypeError: Cannot read properties of undefined (reading 'map')
    at Object.Ua [as current] (/Users/ward/.config/raycast/extensions/a9fc4983-0104-49e7-9085-96532c312a46/commandSearch.js:30:11191)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by kudrykv** [comment]
That's embarrassing. I'll try to look into it later today.

**Comment by wardweistra** [comment]
@kudrykv The `map` error is now gone, but instead it will just show "no results found":
<img width="862" alt="CleanShot 2023-04-21 at 13 48 21@2x" src="https://user-images.githubusercontent.com/779157/233628562-2ca8e8e1-8b79-42bc-9d8a-01e39e8bc7e0.png">

Removing the extension and installing again + filling API key will resolve it for a while, but it keeps coming back in about a day or so like the `map` error.

**Comment by kudrykv** [comment]
One issue resolves, and another appears!
I have a suspicion what could that be. I'll check it out.

**Comment by kudrykv** [comment]
#6103

**Comment by wardweistra** [comment]
Thanks for the hard work @kudrykv 🙏

**Comment by kudrykv** [comment]
@wardweistra Hello, I wanted to ask if the change made any difference?
