### ISSUE TITLE
[ChatGPT] ...

### ISSUE THREAD

**Issue by caydgreen** [raycast/extensions#5790]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Any time I ask a question I get an error code 429.  Rolled my API key and the problem persists.

### Steps To Reproduce

1. Open raycast and type "ask question"
2. Type in question
3. Hit enter
4. Error 429 in bottom left

### Expected Behaviour

No error, and Chat GPT reponse.

**Comment by Spiteless** [comment]
I am also having this issue. 


<details>
<summary>Screenshot</summary>

<img width="751" alt="image" src="https://user-images.githubusercontent.com/5898009/230275064-aca2ba2c-43ae-410b-b6a4-54cb49b1d60e.png">

</details>

**Comment by homoky** [comment]
Me as well.

**Comment by abielzulio** [comment]
Have you tried to change your account plan to `pay-as-you-go`? This mostly happens due to using a free tier account.

**Comment by homoky** [comment]
Yeah, it was it. Sorry. My bad. It would be good to show alert that will translate that error code to user message.

**Comment by Spiteless** [comment]
Changing to a pay-as-you-go plan resolved  the issue for me

**Comment by abielzulio** [comment]
@raycastbot close this issue
