### ISSUE TITLE
[ChatGPT] Custom model is not used at all

### ISSUE THREAD

**Issue by thestacks** [raycast/extensions#5791]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

I have configured custom model using 'Models'. When I use the 'ask question' path, and select this newly created model, it seems that its not being used, and the 'Default' one is used - based on received answers

Model: gpt-3.5-turbo

### Steps To Reproduce

1. Open Raycast
2. Use Models command
3. Use CMD + N shortcut to create new Model
4. Set name: 'Slackbot'
5. Set prompt: {craft a concise, human-like, and friendly message based on the given text. If the given text is a full sentence, focus on fixing grammar while still considering ellipses, brackets, and parentheses. The message should typically be one or two sentences in length, unless the context requires more. Use the message in informal settings like Slack or Telegram, but adjust the tone as needed based on instructions in brackets (e.g., "[!pro and confident and !friendly]"). If the given text includes parentheses, fill in the sentence with a creative touch. If the given text ends with ellipses, extend the message by at least one more sentence, but no more than two sentences.}
6. Use CMD + Enter to submit creation of the new model
7. Use 'Ask Question' Command, provide text like: 'deadline, approaching, soon' and select the 'Slackbot' model.
8. ChatGPT should provide answer that mentions something about deadline, and has not more than 2 sentences long as in the prompt defined in the model, but seems to be responding as you would use Default model.

### Current Behaviour

Default model is used and the custom model prompt is ignored.

### Expected Behaviour

Use selected custom model prompt.

**Comment by abielzulio** [comment]
Are you still facing this issue on a daily basis? @thestacks

**Comment by thestacks** [comment]
Sorry to say, but I have dropped using this extension in favor of Raycast AI.

**Comment by abielzulio** [comment]
@raycastbot close this issue
