### ISSUE TITLE
[World Clock] Some times are an hour earlier than they should be

### ISSUE THREAD

**Issue by aprice42** [raycast/extensions#5798]
### Extension

https://www.raycast.com/koinzhang/world-clock

### Description

I just noticed today that some times in my saved timezone list are displaying with incorrect times, it looks like the incorrect times are all +1 hour off...

![2023-04-05 at 16 59 53](https://user-images.githubusercontent.com/675820/230239527-27406393-fa54-4254-b8cf-a1db226fa549.png)

### Steps To Reproduce

Install the extension, add America/New_York timezone and America/Los_Angeles timezone. Note that they are not 3 hours apart as they should be.

### Current Behaviour

They are only displaying as 2 hours apart.

### Expected Behaviour

They should be displayed as 3 hours apart.

**Comment by aprice42** [comment]
so, after writing this up, I thought to try reinstalling the extension. That seems to have fixed the issue. The UX seems slightly different, so it seems like I must have been using an old version. I was under the impression that extensions would automatically be updated as Raycast is updated. Is that not the case? Or is there a reason that extension would not have been automatically updated?

**Comment by koinzhang** [comment]
Hi @aprice42 According to Raycast's official statement, the extension will be updated automatically when you enter the extension store, if not, you can update it manually using the **Check For Extensions Updates** command.

It seems that the problem has been solved, so I closed the issue @raycastbot close this issue
