### ISSUE TITLE
[ChatGPT] ... I've been getting a bunch of errors using GPT-4 model:

### ISSUE THREAD

**Issue by connorwforsyth** [raycast/extensions#5801]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20

### Steps To Reproduce

Make a query via GPT-4.. often I am getting this.

**Comment by abielzulio** [comment]
@raycastbot close this issue.

Closing this issue due to a future fix that will be available on [the next update](https://github.com/raycast/extensions/pull/6528).
