### ISSUE TITLE
[ChatGPT3 Prompt] Cannot open prompt

### ISSUE THREAD

**Issue by aeckardtvbu** [raycast/extensions#5803]
### Extension

https://www.raycast.com/denizyoldas/chatgpt3-prompt

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'map')

Et:index.tsx:16:43
Nr:index.js:5:2490
    at ray-navigation-stack
ko:index.js:5:2088
```

### Steps To Reproduce

1. Open the ChatGPT prompt
2. The error occurs

### Current Behaviour

An error occurs

### Expected Behaviour

The prompt should open

**Comment by denizyoldas** [comment]
It will be fixed when a pr act is accepted to solve the problem 
https://github.com/f/awesome-chatgpt-prompts/pull/581

**Comment by denizyoldas** [comment]
@raycastbot close this issue
