### ISSUE TITLE
[Bitly URL Shortener] ...

### ISSUE THREAD

**Issue by hindfelt** [raycast/extensions#5804]
### Extension

https://www.raycast.com/blessanm86/bitly-url-shortener

### Description

Can't execute command - error message Invalid URL string.

### Steps To Reproduce

open raycast.
start writing "sho" and when the command is highlighted press enter.
Nothing happens. Error message Invalid URL string showing.

**Comment by hindfelt** [comment]
screenshot-gif
[image: CleanShot 2023-04-06 at 17.18.28.gif]

**Comment by blessanm86** [comment]
It seems like the gif didn't upload properly

**Comment by hindfelt** [comment]
Opening it in Gmail works for me.  Here's a Dropbox link
https://www.dropbox.com/s/z243dwv2z08dh7r/mail.gif?dl=0

**Comment by blessanm86** [comment]
An update that displays more error information has been merged. Try again. Should tell u if it's an API error or something wrong with what's in the clipboard

**Comment by blessanm86** [comment]
@hindfelt any updates?
