### ISSUE TITLE
[Brew] Could you add a command to uninstall or clean outdated application ?

### ISSUE THREAD

**Issue by Langeeker** [raycast/extensions#5816]
### Extension

https://www.raycast.com/nhojb/brew

### Description

Could you add a command to uninstall or clean outdated application ?

**Comment by gleich** [comment]
I was thinking it would just list all of the things you can have installed and you can uninstall them with enter. You could also press cmd + enter to zap uninstall. I am willing to put up a PR for this if this is something that would get merged by the maintainers.
