### ISSUE TITLE
[Claris Snippets] Copying a snippet causes to error

### ISSUE THREAD

**Issue by onefile** [raycast/extensions#5817]
### Extension

https://www.raycast.com/eluce2/claris-snippets

### Description

Adding a new snippet in the current version of Claris Snippet, saving it and then copying it will result in the following error message:
"_Error
Could not identify the type of FileMaker data
stored in database to send to the clipboard.
Clipboard starts with: <?xml version="1.0" .._."
However, old snippets (created before update the extension) can be copied. (Unfortunately, I deleted my old, working snippet...).

### Steps To Reproduce

MacBook Air (M1), macOS Ventura (13.3), FileMaker (19.6.3.302), Raycast (1.49.2)

### Current Behaviour

Copying a snippet causes an error

### Expected Behaviour

Copy snippet (works without error message) and paste into FileMaker with Command V.

**Comment by eluce2** [comment]
Hi there, Just wanted to let you know that I'm able to replicate this issue but still working on a fix

**Comment by onefile** [comment]
Hi, maybe the error is here?!
_2023-03-12 update: for anyone who has been using FmClipTools, there was a change to the script that converts objects to XML. In the past, it also made the XML "pretty" (indentation, basically) by default. However, that made it slower and also could introduce slight differences that can cause problems for FileMaker when pasting back. So, the default is now to leave the XML "ugly", with a separate script to "Prettify XML in Clipboard", which should operate on any XML in the clipboard. Technical note: it is using tidy for that formatting, with tidy's options set to do as little extra modification as possible._
https://github.com/DanShockley/FmClipTools
