### ISSUE TITLE
 My IP Geolocation - preference to swap returned coordinates?

### ISSUE THREAD

**Issue by gns-jdaniel** [raycast/extensions#5829]
### Description

Google Maps wants coordinates N/S,E/W, but this extension provides them E/W,N/S.

Would it be possible to supply the coordinates with the option to copy them in either format? (an option to immediately search those coordinates would be awesome too!)

### Who will benefit from this feature?

Anyone who wants to search coordinates on Google Maps

**Comment by ratoru** [comment]
Hi @gns-jdaniel! Could you elaborate a bit? I'm not quite sure I understand what you mean. I'll see what I can do.

**Comment by gns-jdaniel** [comment]
When I press return on My IP Geolocation, I get the coordinates as -123W,48N (for example):
<img width="740" alt="Screenshot_2023-04-10_at_9_54_54_AM" src="https://user-images.githubusercontent.com/57409410/230952434-d82ccb47-e20a-48d8-9036-894b4cfadfa1.png">

However, if I then try to use those coordinates in Google Maps in the order that they're given in My IP Geolocation (-123,48...east/west coordinate before north/south coordinate), I get an error:
<img width="361" alt="Screenshot 2023-04-10 at 9 58 12 AM" src="https://user-images.githubusercontent.com/57409410/230951996-c9ab2b28-1d54-45f2-92bb-9fbbebdcc5fd.png">

I have to swap them so that the coordinates are 48,-123 (ie north/south coordinate before east/west coordinate):
<img width="360" alt="Screenshot 2023-04-10 at 9 58 35 AM" src="https://user-images.githubusercontent.com/57409410/230952318-f771548a-e173-4a09-8cfb-0cf334b90416.png">

Is it possible to either permanently switch the coordinates returned to be NS,EW rather than the current EW,NS? Or add an option to select that preference?
