### ISSUE TITLE
[ChatGPT]  adding a customizable Chat GPT API server setting

### ISSUE THREAD

**Issue by WingCH** [raycast/extensions#5841]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

I suggest the author to consider adding a customizable Chat GPT API server setting.

### Who will benefit from this feature?

Customization: Different users have different requirements for their chatbot, and customizable API server enables users to configure their chatbot according to their needs.
Efficiency: A customizable API server can be optimized based on the user's requirements, thereby improving the server's efficiency.

**Comment by abielzulio** [comment]
> ### Extension
> 
> https://www.raycast.com/abielzulio/chatgpt
> ### Description
> 
> I suggest the author to consider adding a customizable Chat GPT API server setting.
> ### Who will benefit from this feature?
> 
> Customization: Different users have different requirements for their chatbot, and customizable API server enables users to configure their chatbot according to their needs. Efficiency: A customizable API server can be optimized based on the user's requirements, thereby improving the server's efficiency.
> ### Anything else?
> 
> _No response_

Could you elaborate more for your feature request?

**Comment by WingCH** [comment]
> > ### Extension
> > 
> > https://www.raycast.com/abielzulio/chatgpt
> > ### Description
> > 
> > I suggest the author to consider adding a customizable Chat GPT API server setting.
> > ### Who will benefit from this feature?
> > 
> > Customization: Different users have different requirements for their chatbot, and customizable API server enables users to configure their chatbot according to their needs. Efficiency: A customizable API server can be optimized based on the user's requirements, thereby improving the server's efficiency.
> > ### Anything else?
> > 
> > _No response_
> 
> Could you elaborate more for your feature request?

One potential scenario is that obtaining access to the ChatGPT 4 API service can be challenging due to factors like country or usage restrictions. Nevertheless, certain third-party providers offer ChatGPT 4 API without connecting to OpenAI servers. As a result, users only need to modify the base URL.

for example:
https://chat-ai.logcg.com

**Comment by kaiyo655** [comment]
Additional, add support for Azure OpenAI API please.

**Comment by intitni** [comment]
Recently, I gained access to Azure OpenAI, and I noticed that it's much faster than OpenAI's API. 

In some other ChatGPT clients, there is a feature that allows users to swap the base URL from `https://api.openai.com` to others such as `https://someopenaiproxy.com`. This enables users to build a proxy and direct the request to other services.

You can take this project as an example: https://github.com/haibbo/cf-openai-azure-proxy/blob/main/README_en.md

It would be brilliant if this plugin could support customization of the server to allow this kind of feature. Thank you!

**Comment by abielzulio** [comment]
> Recently, I gained access to Azure OpenAI, and I noticed that it's much faster than OpenAI's API.
> 
> In some other ChatGPT clients, there is a feature that allows users to swap the base URL from `https://api.openai.com` to others such as `https://someopenaiproxy.com`. This enables users to build a proxy and direct the request to other services.
> 
> You can take this project as an example: https://github.com/haibbo/cf-openai-azure-proxy/blob/main/README_en.md
> 
> It would be brilliant if this plugin could support customization of the server to allow this kind of feature. Thank you!

Hi! We're already working on it through this [PR](https://github.com/abielzulio/chatgpt-raycast/pull/36). You could look there to see our progress and do let me know if there's any suggestion :)
