### ISSUE TITLE
chatgpt

### ISSUE THREAD

**Issue by Anandsure** [raycast/extensions#5852]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Ask a Question results in a 429 Error. 

<img width="768" alt="image" src="https://user-images.githubusercontent.com/43916800/230848110-d71e1220-7a77-424b-a09f-d56340543b23.png">

Note:
429 according to openAI is a rate-limit exceeded issue. None of my other personal applications make an API call to that particular account. So it's unlikely the issue is from that end. Hence the confusion here. 

Pre requisites:
1. API Secret key has been added from my person openAI account. 

### Steps To Reproduce

1. Open the Ask Question command under the chatgpt extension
2. Follow through the prompt of adding an API key. 
3. once added, extension loaded up and I've typed in a query
4. Observed the above result (reference screenshot)

### Current Behaviour

ERROR code 429

### Expected Behaviour

Likely a SUCCESS CODE 200 along with response to the query from the model

**Comment by Anandsure** [comment]
@abielzulio any updates?

**Comment by abielzulio** [comment]
> @abielzulio any updates?
> 
> 

It won't work due you're using a `pay-as-you-go` account. You need to have a paid account as I've mentioned in the docs.

**Comment by abielzulio** [comment]
@raycastbot close this issue

**Comment by abielzulio** [comment]
@raycastbot close this issue
