### ISSUE TITLE
[Tailscale] Exit Node Support

### ISSUE THREAD

**Issue by danpalmer** [raycast/extensions#5859]
### Extension

https://www.raycast.com/samlinville/tailscale

### Description

Command requests:

**Toggle exit node**
- If on, disables selected exit node.
- If off, presents a list of available exit nodes, with selection enabling that exit node.

**Toggle allow LAN access with exit node**
- Toggles value
- Persists state so that, e.g. toggling when no exit node will ensure correct configuration on next exit node connection.

### Who will benefit from this feature?

All Tailscale users. This seems to be a relatively common use-case, and one that might be done regularly.

### Anything else?

Happy to help with further requirements or testing!

**Comment by samlinville** [comment]
@danpalmer I apologize, I didn't see this PR earlier; I actually just submitted a larger PR to add this and a few other features!

**Comment by samlinville** [comment]
@raycastbot close this issue
