### ISSUE TITLE
[1Password] Expose secret references

### ISSUE THREAD

**Issue by eluce2** [raycast/extensions#5863]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

I haven't dived too deep into this extensions code yet, but I understand you're using the 1Password CLI to get items. I would like to be able to quickly access a [secret reference](https://developer.1password.com/docs/cli/secret-references#generate-a-secret-reference) from this extension so I don't have to remember the command each time I need to copy this value.

I am willing to help contribute this to your extension if you'd be open to that

### Who will benefit from this feature?

Software Teams using secret references to safely share environment variables within their codebase

**Comment by khasbilegt** [comment]
Hello @eluce2, just to make sure if I understood your idea, you would like to view (and maybe copy to clipboard) the secret references of item fields in the extension, is that right? 

I use the `op run` command often to replace env variables by its secret reference. I was planning to add detail view for each items and where we could present the references. What do you think?

**Comment by eluce2** [comment]
Yes, this is exactly what I'm looking for. If by a "detail view" you actually mean a list view in the Raycast API that would be perfect. The advantage to this is that you more easily go down each item in the 1Password entry to perform an action on the individual field. I would see this as a great way to get at what I'm looking for

**Comment by khasbilegt** [comment]
I am not sure what would be the ideal implement but currently all the items are "listed" and there should be another way to present the each fields of an item. It might be easier to create additional action item for each field's secret reference.

**Comment by eluce2** [comment]
In my opinion, actions should be as static as possible so they can be assigned reliable keyboard shortcuts. This is another reason I would strongly suggest you use the list implementation. This way, the list of fields can be filtered to find the one you need and then you can press the keyboard shortcut for the action you want, whether that's to copy the secret, field name, UUID, or reference, etc.
