### ISSUE TITLE
[ChatGPT] ...

### ISSUE THREAD

**Issue by SunKaedes** [raycast/extensions#5872]
### Extension

https://www.raycast.com/abielzulio/chatgpt

#### Error:
```
Error: read ECONNRESET

TLSWrap.onStreamRead:stream_base_commons:217:20

```

### Steps To Reproduce

错误同#5837

**Comment by pernielsentikaer** [comment]
How do you reproduce this? Could you record a screencast of the issue?

**Comment by SunKaedes** [comment]
https://user-images.githubusercontent.com/24784217/232237237-f478eca5-9b02-4f57-b002-2ae65a9b84ae.mp4

**Comment by ijilwevsd41** [comment]
+1

**Comment by abielzulio** [comment]
@ijilwevsd41 @SunKaedes Could you all access to the chat.openai.com through browser?

**Comment by SunKaedes** [comment]
可以的

**Comment by abielzulio** [comment]
This would be related to OpenAI restrictions in China. We're proposing a fix that hopefully makes it work by offering Azure OpenAI as an alternative. It's on [review](https://github.com/raycast/extensions/pull/6528) now!

**Comment by NeroAsmarr** [comment]
I faced the same issue, and it is indeed a network problem in China when using a proxy. I tried to use the enhanced mode in clash pro to solve this problem, but it didn't work the next day.

**BUT I FOUND ANOTHER SOLUTION: just using the API Endpoint instead of Proxy.**
you can look for it online.
