### ISSUE TITLE
[GitLab] Allow setting the "Delete source branch" flag when creating a new MR via Raycast

### ISSUE THREAD

**Issue by dhharris** [raycast/extensions#5877]
### Extension

https://www.raycast.com/tonka3000/gitlab

### Description

Currently there's no option to set this flag via the Raycast extension. In the UI it is found in the "Merge options" section

![Screen Shot 2023-04-11 at 15 06 39](https://user-images.githubusercontent.com/9009622/231171949-bee9294d-2612-486c-b07c-9aa02ada5c77.png)

It also doesn't respect the default behavior for new issues in the gitlab repo (which may be a bug?)

### Who will benefit from this feature?

Deleting the source branch is a pretty common practice so that old feature branches don't stay around in gitlab when they have already been merged.

**Comment by tonka3000** [comment]
Make sense. Need to check how to impl that.

Would you prefer to have it the same way like on the website, so that the default is turned on and you can change it?
