### ISSUE TITLE
[Unsplash] Add Quick Look Actions

### ISSUE THREAD

**Issue by ajtruex** [raycast/extensions#5878]
### Extension

https://www.raycast.com/eggsy/unsplash

### Description

This extension is great especially the new updates waiting to be published. The only suggestion I have is to add a Quick Look option. The functionality can be found in the clipboard history extension.

### Who will benefit from this feature?

Anyone who would like to see the images in question natively on their computer.

**Comment by eggsy** [comment]
Great idea! But I think we'd have to download to preview the actual image, I don't think it's that necessary when you can just see the image inside the Raycast window. Do you think downloading _somewhat_ large images to get a preview looking? Implementing this would cause extra files + unnecessary network usage. Could that be considered fine?

**Comment by CheinTian** [comment]
The extension indicates me to sign in with Unsplash. But the redirect url is wrong.  How can i solve this?

![image](https://user-images.githubusercontent.com/87127203/233784546-77a9a17a-31d8-4aa1-8030-069a21e139bc.png)

![image](https://user-images.githubusercontent.com/87127203/233784562-2836e61a-0220-4c41-944d-dab790468806.png)

**Comment by eggsy** [comment]
Follow the instructions in the readme/store page of the extension. You have to set the redirect uri yourself.
