### ISSUE TITLE
[Obsidian] ...

### ISSUE THREAD

**Issue by aledomyy** [raycast/extensions#5885]
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

When i append something to my daily note, after writing the text it opens obsidian, which kind of defeats the purpose (as it is practically the same as simply opening the daily note). It would be great if this did not happen. Thank you so much for such a great extension!!

**Comment by conatus** [comment]
> @aledomyy please enable check-box `Silent Mode` in command `Append to Daily Note`.

Sorry to say it, but this doesn't have the desired effect. Obsidian will always be foregrounded due to how this Extension works.

https://github.com/raycast/extensions/issues/10802#issuecomment-1950985013
