### ISSUE TITLE
[Visual Studio Code - Project Manager] ...

### ISSUE THREAD

**Issue by AirOne-dev** [raycast/extensions#5890]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

When I open a remote ssh project with this extension (only using raycas). The "search" feature of vscode is broken.

### Steps To Reproduce

1. Open raycast and type "Project Manager"
2. Hit [enter] to show the listing of saved projects
3. Open a remote ssh project
4. Start a global search (cmd + shift + f)
5. Search for something : it loads, and then show no results

**Comment by MarkusLanger** [comment]
@AirOne-dev The extension uses this call => https://github.com/raycast/extensions/blob/a91fe01778cd1f1c32d38637ac9855a0c11fed21/extensions/visual-studio-code-project-manager/src/search-project-manager-projects.tsx#L207
Could you check if your problem also occurs if you call it from your terminal?
`code --remote [URL to the project]`

I don't have any remote project so I cannot check it.

**Comment by AirOne-dev** [comment]
Seem's to be a vscode bug, i does the same when i execute : 
`code --remote /ssh-remote+myserver.com/home/me/work/...`

**Comment by AirOne-dev** [comment]
something like this seems to work :

code --remote remote_url_here --locale $(osascript -e 'user locale of (get system info)')

(I use osascript because it work for all versions of macos) 
(LC_ALL, or others environment variables are not set in my case)

**Comment by wangpy1489** [comment]
I have same issue.
