### ISSUE TITLE
[Authy] ...

### ISSUE THREAD

**Issue by PMiraLopes** [raycast/extensions#5896]
### Extension

https://www.raycast.com/guga4ka/authy

#### Error:
```
Error: Invalid base32 characters

uu:OtpListItem.tsx:72:38
fu:search-otp.js:42:4668
Or:index.js:5:5486
    at ray-list
```

I just reinstalled the extension, and after setting it up I cannot get any OTP tokens, always get the error screen

I tried already check for updates and reinstall the extension

### Current Behaviour

An error screen appear every time that i try to access the extension

### Expected Behaviour

when I open the extension, it shows me the OTP tokens

**Comment by guga4ka** [comment]
@raycastbot close this issue
duplicate #5880
