### ISSUE TITLE
[Emoji Search] Add a setting for skin tone

### ISSUE THREAD

**Issue by kud** [raycast/extensions#5898]
### Extension

https://www.raycast.com/FezVrasta/emoji

### Description

Could be great to have a skin ton setting.

### Who will benefit from this feature?

Anyone.

**Comment by arronhunt** [comment]
Interesting. Looks like the built-in emoji picker supports skin tone selection. 

<img width="862" alt="image" src="https://user-images.githubusercontent.com/298336/231896914-69e00e89-bda9-4e66-819e-740ef3f9b6e2.png">
