### ISSUE TITLE
[Spotify Beta] Doesn't tell user when premium is required, just crashed the menu bar player

### ISSUE THREAD

**Issue by Gabibag** [raycast/extensions#5904]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

#### Error:
```
Error: Player command failed: Premium required

Ms:pause.ts:19:10
async onAction:nowPlayingMenuBar.js:99:2780
index.js:7:35293
```

### Steps To Reproduce

1. Have a non-premium spotify account
2. Use the menubar player to skip

### Current Behaviour

Crashes and tells the user theres an error.

### Expected Behaviour

Tell user they need premium.

**Comment by peduarte** [comment]
Thanks for that! Will look into it

**Comment by peduarte** [comment]
Should be better now, let me know!
