### ISSUE TITLE
[Spotify Player] Show which songs are explicit

### ISSUE THREAD

**Issue by ajtruex** [raycast/extensions#5909]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Add an explicit indicator in the song search or a preference to only search for the explicit version. I get clean versions every once in a while when searching for a track. 

### Who will benefit from this feature?

People who prefer the songs how they were intended by the artist!

I guess it could also benefit those who want the clean version 🙄.

**Comment by runmaxde** [comment]
I want that as well, got the feat ready, waiting for #5975
