### ISSUE TITLE
[OpenAI GPT] ...

### ISSUE THREAD

**Issue by Arneshpal** [raycast/extensions#5911]
### Extension

https://www.raycast.com/simicvm/openai-gpt

### Description

Reason: Extension and command preferences hasn't been found
Domain: database
Time: 06:44:18.332
Database: raycast-enc.sqlite
Table: commands

**Comment by simicvm** [comment]
I can't reproduce the issue. But it might due to extension name change. Try removing the currently installed extension and installing again from https://www.raycast.com/simicvm/openai-gpt
