### ISSUE TITLE
[Spotify Beta] Crash while in background

### ISSUE THREAD

**Issue by Mr-Alirezaa** [raycast/extensions#5922]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

#### Error:
```
Error: Bad Request

a3:oauth.ts:88:10
async Ns:nowPlayingMenuBar.js:61:1169
nowPlayingMenuBar.js:61:18021
```

**Comment by peduarte** [comment]
Hey, thanks for raising this issue. Can you elaborate on how this happened? Are you able to consistently reproduce this? Did it eventually "come back to life"?

**Comment by Mr-Alirezaa** [comment]
Hey @peduarte,
Yes it keeps crashing when I tap the reload button. It is reproducing itself :)

Since I'm using Spotify from Iran, and due to sanctions I have to use VPN. As far as I can remember, when my VPN went offline and came back online, it crashed. but I'm not sure if thats the reason.

**Comment by peduarte** [comment]
Oh, interesting. Looks like it's related to auth. Would you mind trying to logout and log back in?
- "Extensions"
- Search for "Spotify Beta"
- Click Logout

Then try to open one of the commands, such as "Your Library", and you'll be asked to authenticate again.

Let me know how that goes please, and we can figure out whats the next stop

**Comment by Mr-Alirezaa** [comment]
I re-authorized "Spotify Beta". The problem seems to be fixed for now. I'll let you know if it happens again and tell me if there's anything I can do to help further.
