### ISSUE TITLE
[Color Picker] Adding accessibility feature

### ISSUE THREAD

**Issue by kud** [raycast/extensions#5924]
### Extension

https://www.raycast.com/thomas/color-picker

### Description

It could be great to have accessibility feature like Pika does

![screenshot-2023-04-13-13-40-18@2x](https://user-images.githubusercontent.com/655838/231761340-3b318031-3737-4849-b3ae-b9077fdf8c16.png)

### Who will benefit from this feature?

Anyone

**Comment by diegohaz** [comment]
I'd love to have this feature.
