### ISSUE TITLE
[GitLab] can not use “My Merge Request” command 

### ISSUE THREAD

**Issue by Jimmy-Chung** [raycast/extensions#5926]
### Extension

https://www.raycast.com/tonka3000/gitlab

### Description

After configuring gitlab url and API Token in the right way， I can use some commands of the extension，such as "My Recent Commit”, "Search Project", and so on. 
But, i can  not use “My Merge Request”， when I open it ， after a few seconds， it always shows an error message：Cannot search Merge Requests: Cannot read properties of undefined (reading 'map') 
<img width="774" alt="image" src="https://user-images.githubusercontent.com/8760085/231775854-109f3b81-42b7-4363-8071-5b98371825e1.png">

### Steps To Reproduce

use  “My Merge Request” command

### Current Behaviour

nothing display , just show a error message: Cannot search Merge Requests: Cannot read properties of undefined (reading 'map') showsan

### Expected Behaviour

should show some merge request item

**Comment by tonka3000** [comment]
Which version of GitLab do you use? Self hosted or GitLab.com?

**Comment by Jimmy-Chung** [comment]
Self hosted v13.6.1

**Comment by tonka3000** [comment]
> Self hosted v13.6.1

Very outdated version. I just support 15.x versions (16.x is already around the corner) but you can make a PR if you can fix the issue.
