### ISSUE TITLE
[Downloads Manager] ...

### ISSUE THREAD

**Issue by itsbrex** [raycast/extensions#5930]
### Extension

https://www.raycast.com/thomas/downloads-manager

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20
```

### Steps To Reproduce

1. Try running `Manage Downloads` action

### Current Behaviour

![Screenshot 2023-04-13 at 13 18 25](https://user-images.githubusercontent.com/9772694/231873757-1acf8d36-93d1-428e-a30b-5cf7a38009e6.gif)

**Comment by ron-myers** [comment]
@itsbrex - how large is your downloads folder in terms of the number of files?

**Comment by thomaslombart** [comment]
Hey @itsbrex, we've fixed a performance issue in the 1.54.0 release that should make this type of bugs less likely to appear. Do you still have the error?

**Comment by itsbrex** [comment]
@ron-myers @thomaslombart Sorry for the delay here. Glad it got sorted even with my less than helpful non-responsiveness 10 points to you both. 🪄😁 🙌

**Comment by itsbrex** [comment]
@ron-myers @thomaslombart just tried re-running it and got the same error after a fresh uninstall / re-install.

```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

```
echo "Number of files: $(ls -1 ~/Downloads | wc -l)"
Number of files:     3917
```
