### ISSUE TITLE
[Spotify Beta] How to dismiss Raycast on return key

### ISSUE THREAD

**Issue by nikitavoloboev** [raycast/extensions#5931]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

### Description

When I do a search for song/artist like so:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/6391776/231885598-f93ab7c2-97f8-4109-ad82-663c6a666d14.png">

I would like to on return to dismiss Raycast. So it starts playing the song/artist and I don't have to activate Raycast via hotkey again or `esc` 2+ times which is annoying.

Can I do this or this should be programmed into the extension? 

Thank you.

### Expected Behaviour

I want to quickly search for the song I want to play and quickly play it without having to manually dismissing Raycast. ♥️

**Comment by nikitavoloboev** [comment]
![CleanShot 2023-04-13 at 23 27 15@2x](https://user-images.githubusercontent.com/6391776/231886770-6be87fb1-0746-4607-b3d2-14f57cc11f88.png)

Okay apparently I can do this.

**Comment by peduarte** [comment]
Glad you found it!
