### ISSUE TITLE
[ChatGPT] ...No response 429 error

### ISSUE THREAD

**Issue by lehaoduong123** [raycast/extensions#5933]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

There is no response from the ChatGPT extension after keying the API

**Comment by duke2048** [comment]
Same issue here: Request failed with status code 429, any hints to fix it?

**Comment by sejal27** [comment]
How was this resolved? I have the same problem. 429 is the error code for rate limits, but I just made my first query so that shouldn't be an issue.

**Comment by abielzulio** [comment]
@raycastbot close
