### ISSUE TITLE
sportify-beta search issue

### ISSUE THREAD

**Issue by davidvidmar** [raycast/extensions#5939]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

### Description

Searching the library doesn't work as expected. If I search playlist with a scope of "all", it doesn't show my "Discovered Weekly", but if I explicitly select "Playlists" it does.

This could be related to the unfinished task of paginating, but I'm reporting it just in case.

### Steps To Reproduce

Run "My Library Command.
Started searching for a playlist name.

### Current Behaviour

Nothing is shown until I select "Playlists" on the right.

### Expected Behaviour

It should find my playlists when searching "All".

**Comment by peduarte** [comment]
Thank you! Looking into it

**Comment by davidvidmar** [comment]
The problem is fixed as far as I tested! Thank you for quick fix.
