### ISSUE TITLE
[OpenAI] Support setting the default model and reuse the last one as the starting model

### ISSUE THREAD

**Issue by hugows** [raycast/extensions#5942]
### Extension

[openai](https://www.raycast.com/simicvm/openai-gpt)

### Description

Support changing the default model to a specific one and/or at least reuse the last one.
This is simply to avoid the gpt4 cost if turbo is almost as good!

**Comment by zhfeng1** [comment]
> We could not find the extension related to this issue. Please update the issue with the link to the extension.

Hello, The link to the extension is :https://github.com/raycast/extensions/tree/main/extensions/openai-gpt

**Comment by spazbg** [comment]
I want to ask for the same. Please set the default model in the OpenAI GPT extension to gpt-3,5-turbo. Most of us need access to GPT 4, or it's too expensive, and now we have to change the mode in every query, which is very frustrating.
