### ISSUE TITLE
Arc

### ISSUE THREAD

**Issue by fearoffish** [raycast/extensions#5943]
### Extension

https://github.com/raycast/extensions/tree/main/extensions/arc

### Description

The "Search Arc" extension has google hard coded. This should use whatever search I have configured in Arc.

### Who will benefit from this feature?

Anyone who doesn't use google as their search.

**Comment by danpalmer** [comment]
@fearoffish can you clarify which bit has a hard-coded Google search?

As far as I can tell all the search commands just search Arc metadata, and wouldn't use Google. There was a default to open new Little Arc windows on Google, but I removed this a few days ago (defaulting to your configured Arc search engine) in https://github.com/raycast/extensions/pull/5866.

**Comment by fearoffish** [comment]
@danpalmer All I know is that when I use the "Search Arc" action, it opens Google. Maybe it's this bit?

https://github.com/raycast/extensions/blob/94a85235fc605b1ad5eb75ff13bb3fad742b4b07/extensions/arc/src/actions.tsx#L183

**Comment by danpalmer** [comment]
Oh yeah, missed that bit. That looks like it. Good find!

I'm unfortunately busy for the next month and a bit so unlikely to have another session working on Raycast extensions for a while. Hopefully someone else can fix this sooner!
