### ISSUE TITLE
[Spotify Beta] Server error while searching library

### ISSUE THREAD

**Issue by jahirfiquitiva** [raycast/extensions#5947]
### Extension

https://raycast.com/mattisssa/spotify-beta

#### Error:
```
Error: Server error.
    at Mo (/Users/jahir/.config/raycast/extensions/56a2815e-83a0-44c6-8f3c-04ef778f3298/yourLibrary.js:47:20456)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 5)
```

**Comment by peduarte** [comment]
Can you elaborate please? Which steps did you take exactly?

**Comment by jahirfiquitiva** [comment]
> Can you elaborate please? Which steps did you take exactly? 

I just went to search in "Your Library" and the error appeared, without any results

**Comment by peduarte** [comment]
Does it happen all the time, or just once?

**Comment by peduarte** [comment]
Ok, thanks for reporting this. I'll keep an eye on it 👀

**Comment by jahirfiquitiva** [comment]
@peduarte no problem, thank you! the extension works great otherwise 😀

**Comment by peduarte** [comment]
Thanks!

**Comment by jahirfiquitiva** [comment]
@peduarte  I ran into another issue... The menu bar command/player stopped working. I tried using the reload button, but it just says 

```
Command Terminated
Reason: Code: 2 (Unhandled Extension Rejection)
Domain: commands
Time: 02:19:31.465
```

```
Error: Bad Request

a3:oauth.ts:88:10
async Ns:nowPlayingMenuBar.js:61:1169
nowPlayingMenuBar.js:61:18021
```

![Shot 2023-04-17 at 09 21 22@2x](https://user-images.githubusercontent.com/10360816/232514878-2716642b-0175-4352-8871-caa6c66aba3e.png)

**Comment by peduarte** [comment]
@jahirfiquitiva Thanks for reporting back! 

Did it just randomly stop working, or was it after a specific action? Can you reproduce this consistently? What are the steps taken?

Was the Spotify App running on your machine when this happened?

Thanks!

**Comment by jahirfiquitiva** [comment]
@peduarte 

> Did it just randomly stop working, or was it after a specific action?
Randomly ... like yesterday I turned my laptop on and it errored, even after a restart it still failed

> Can you reproduce this consistently? What are the steps taken?
Not sure how to reproduce it, but it still fails even after a restart. And every time I try to `reload` it shows the error: `Command Terminated - Reason: Code: 2 (Unhandled Extension Rejection)`

> Was the Spotify App running on your machine when this happened?
It wasn't. I tried opening it and then reloading the command, but still errors

**Comment by peduarte** [comment]
Ok. Thanks! Are you on our [Slack](https://raycast.com/community)? Will be easier to debug 🤓

**Comment by jahirfiquitiva** [comment]
I haven't had this issue in some days, so I'll close this and reach out if it ever happens again.

Thanks for all the help! @peduarte
