### ISSUE TITLE
[Spotify Beta] Quicker access to Album grid

### ISSUE THREAD

**Issue by ghosteen** [raycast/extensions#5949]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

### Description

It would be nice if the default option in the search results for an artist was 'Show Albums' rather than 'Play'. 

It's fine in the results for albums or songs, but for artists I always hit enter thinking it will show me the album grid.

Quick access to a grid of recently played albums would also be great.

Thanks! I love the extension

**Comment by peduarte** [comment]
That's a very subjective thing. I will keep an eye on it though, happy to change if majority agrees. 

But for what's worth, the secondary action is "Show Albums", and secondary actions can be triggered with ⌘ ⏎

**Comment by ghosteen** [comment]
OK, I understand

But if the action with ⏎ is Play.

Couldn't the first option after ⌘ ⏎ be 'Show Albums'? Because it's still Play ⏎ and you have to do two more steps to get to "Show Albums".

On the other hand. When I start listening to new artists, I can't remember the name of the band or album.
Isn't it possible to add a shortcut to a "Recently listened" grid?

This and other Spotify options like 'Back to your music' or 'Suggestions for today' would be nice to have more handy.
I end up having to go into the app to search for what I've been listening to recently.

**Comment by peduarte** [comment]
@ghosteen Are you referring to swapping "Show Popular Songs" with "Show Albums"?

![(ಠ ›ಠ) — @peduarte — AQPR29jl001617@2x](https://user-images.githubusercontent.com/372831/232425450-d743a712-55b9-4b96-b024-4a0e20480025.png)

**Comment by ghosteen** [comment]
Yes. For me, if the secondary option with ⌘ ⏎ would be 'Show Albums' instead of 'Show Popular Songs' it would be great.

I don't know if you can change that keyboard shortcut somehow.

And like I said, if there was a shortcut to 'Recently Listened' that would be perfect.

**Comment by peduarte** [comment]
Ok, noted. Will have a think and let you know!
