### ISSUE TITLE
[Extension Feature Request] - Add copy URL action to Obsidian plugin

### ISSUE THREAD

**Issue by marcromeyn** [raycast/extensions#597]
Author: @marcjulianschwarz 

First of all, big thanks for creating this extension. I am using it every day.

**Describe the feature and the current behavior/state.**
I would love to have an option to copy the URL to the page I select in the plugin. This way I can use this in other applications, like Todoist.

**Who will benefit with this feature?**
Everyone that’s using Obsidian together with other applications.

**Comment by marcjulianschwarz** [comment]
Hi @marcromeyn,
thanks for the feedback.

This sounds like a good idea. So the action should copy the `obsidian://` URL which opens the note, did I understand this correctly?

**Comment by marcromeyn** [comment]
Exactly! An other potential action could be to create a markdown link, something like `[PAGE_NAME](OBSIDIAN_URL)`.

**Comment by marcjulianschwarz** [comment]
Perfect, will implement both features and let you know when the new version is available.

**Comment by marcjulianschwarz** [comment]
@marcromeyn if you haven't seen it yet, your requested feature is now available with the newest version of the extension.
Check it out:
https://www.raycast.com/marcjulian/obsidian

**Comment by marcromeyn** [comment]
Awesome, big thanks for this!
