### ISSUE TITLE
[Google Chrome] Does not switch to tab

### ISSUE THREAD

**Issue by varp** [raycast/extensions#5998]
### Extension

https://www.raycast.com/Codely/google-chrome

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    tell application "Google Chrome"
      activate
      set _wnd to first window where id is NaN
      set index of _wnd to 1
      set active tab index of _wnd to 21
    end tell
    return true
  
96:99: execution error: The variable NaN is not defined. (-2753)

    tell application "Google Chrome"
      activate
      set _wnd to first window where id is NaN
      set index of _wnd to 1

```

### Steps To Reproduce

I think it's caused by multi-profile/window usage of Chrome or by using of Tag groups

### Current Behaviour

Got an error

### Expected Behaviour

Switch to tab

**Comment by karolre** [comment]
Because I cannot reproduce the issue, I have prepared the pull request which should provide more info allowing to help understand the root cause: https://github.com/raycast/extensions/pull/6068

**Comment by karolre** [comment]
I was able to find a root cause thanks to more extensive error logging. The issue is related to the fact that in some cases MacOS generates windows identifiers which are represented in exponential form: `1,304973562E+9`. Full exception below.

```
Error: Issue with tab: '[tab name]~~~[tab url]~~~~~~1,304973562E+9~~~4'
Command failed with exit code 1: osascript -e 
    tell application "Google Chrome"
      activate
      set _wnd to first window where id is NaN
      set index of _wnd to 1
      set active tab index of _wnd to 4
    end tell
    return true
  
96:99: execution error: The variable NaN is not defined. (-2753)

Command failed with exit code 1: osascript -e 
    tell application "Google Chrome"
      activate
      set _wnd to first window where id is NaN
```

Now I need to find a way to resolve it.

**Comment by karolre** [comment]
Raised PR to fix the issue: https://github.com/raycast/extensions/pull/6172

**Comment by varp** [comment]
@karolre Thanks a lot!
