### ISSUE TITLE
[Unsplash] Unable to sign in

### ISSUE THREAD

**Issue by fabioatcorreia** [raycast/extensions#6005]
### Extension

https://www.raycast.com/eggsy/unsplash

### Description

When clicking on the "Sign in with Unsplash" button, after setting the Access and Secret Keys, the Unsplash site opens with a failure message:  

<img width="708" alt="Screenshot 2023-04-18 at 07 55 13" src="https://user-images.githubusercontent.com/22024644/232696878-2dde0e34-24c6-4c86-a717-6ed8d3e7d716.png">

**Comment by eggsy** [comment]
Please make sure you follow each step carefully in the README file.

**Comment by fabioatcorreia** [comment]
Thanks, that fixed it 🤦 
Sorry for the bother!  
I had this working previously but, somehow, it stopped working...
