### ISSUE TITLE
[My Daily Log] ...

### ISSUE THREAD

**Issue by Alireza29675** [raycast/extensions#6007]
### Extension

https://www.raycast.com/frugoman/my-daily-log

### Description

It seems that it doesn't throw any proper errors:

#### Error:
```

```

### Steps To Reproduce

1. 
![Screenshot 2023-04-18 at 11 23 04](https://user-images.githubusercontent.com/2771377/232717468-c89065dd-e065-4a09-b008-3e99d02085a8.png)

2.
![Screenshot 2023-04-18 at 11 22 51](https://user-images.githubusercontent.com/2771377/232717392-de149957-a752-4979-8a4b-10b5e4d9520e.png)

**Comment by frugoman** [comment]
Hi @Alireza29675, thanks for reporting this! A few questions to understand the issue:

Is this the very first log you try doing? 
Have you logged something before?
Do you have a folder configured for the logs to be stored in? (Check this in the extension configuration)

**Comment by Alireza29675** [comment]
Hi Nicolas! Sure!

_Is this the very first log you try doing?_ **Yes**
_Have you logged something before?_ **No, always faced the same error**
_Do you have a folder configured for the logs to be stored in?_ **It's `~/Documents/DailyLog`**

**Comment by Alireza29675** [comment]
I fixed it by manually creating `~/Documents/DailyLog` folder. I guess that's the problem:)
