### ISSUE TITLE
[ChatGPT] ...

### ISSUE THREAD

**Issue by slenderongithub** [raycast/extensions#6015]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

<img width="741" alt="SCR-20230418-qxov" src="https://user-images.githubusercontent.com/100205231/232799730-6737938a-16fa-4274-8ded-2d53bfe1048b.png">

### Steps To Reproduce

1. search ChatGPT in raycast
2. use command "ask a question"
3. error comes up

**Comment by abielzulio** [comment]
Could you provide the full error logs here?
