### ISSUE TITLE
[Extension Feature Request] Play Spotify albums

### ISSUE THREAD

**Issue by jiserra** [raycast/extensions#602]
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/main/extensions/spotify-player)

Author: @mattisssa 

**Describe the feature and the current behavior/state.**
Currently, the Spotify Player extension is great to search for individual tracks, but that's not the way a lot of people consume music: we play whole albums as well! I would like the search to work for albums. Currently when you select a track you can `Cmd-K` and it has the _Show Album_ option, but that just opens Spotify in the web. It would be great to have a _Play Album_ option.

**Who will benefit with this feature?**
Everyone who likes to listen to music through albums!

**Any Other info.**
Thanks for the extension!

**Comment by djpowers** [comment]
Any chance of this being revisited/reopened? I think this would be a great feature. Additionally, is it possible for the "Show Album" option to open in the Spotify desktop application if installed?

**Comment by mattisssa** [comment]
Hey! Oh yeah, I missed that the stale bot closed it. 
Actually, it was impossible with the current authorisation flow, but a spoiler alert: I have done it in the beta version and internal version of Raycast where it’s possible and many more. So, set the reminder to around 20-22 of April to get that 😉
