### ISSUE TITLE
[Github Enterprise] Support notifications and discussions

### ISSUE THREAD

**Issue by bobspryn** [raycast/extensions#6020]
### Extension

https://www.raycast.com/Kinbaum/github-for-enterprise

### Description

I would love to see the enterprise extension get close to feature parity with the regular version. Specifically I would love to be able to open my notifications and discussions.

### Who will benefit from this feature?

Anyone who uses Github Enterprise

### Anything else?

Thanks for the hard work!

**Comment by perat** [comment]
Hi, I need this feature. Especially notifications in system tray for Github Enterprise.
