### ISSUE TITLE
[Unsplash] Cannot sign in - The redirect uri included is not valid.

### ISSUE THREAD

**Issue by patrickmccallum** [raycast/extensions#6023]
### Extension

https://www.raycast.com/eggsy/unsplash

### Description

While setting up the extension the user is asked for two things:
* The API/Secret key for a custom dev app
* To sign in with unsplash

During sign in with unsplash the process fails the auth screen displays with the error:
"The redirect uri included is not valid."

Screenshot attached
<img width="752" alt="image" src="https://user-images.githubusercontent.com/11825795/232934923-6953277d-43fa-468d-8321-3bcdefc314f9.png">

**Comment by eggsy** [comment]
Hi, please refer to extension's readme for new installation steps. You are missing the `redirect_uri` field in your Unsplash application settings. It won't take more than 2 minutes to setup so don't worry.

**Comment by patrickmccallum** [comment]
Ah got it. Cheers.

**Comment by patrickmccallum** [comment]
@raycastbot close this issue
