### ISSUE TITLE
[Mozilla-Firefox] Extension says Firefox Not Installed

### ISSUE THREAD

**Issue by asala6675467** [raycast/extensions#6024]
### Extension

https://www.raycast.com/crisboarna/mozilla-firefox

### Description

Raycast says that Firefox is not installed, even though it is (and I reinstalled).  Raycast recognizes the application, and another extension that use Firefox (Search Browser Bookmarks) are working OK.  However, when I try to use the Firefox extension, get an error saying "Error: Mozilla Firefox browser is not installed".  Having the same problem with Search Browser History Extension.  

![Screenshot 2023-04-18 at 8 33 31 PM](https://user-images.githubusercontent.com/71223258/232935987-ec52f4c4-1343-4cb9-b159-c323acc0524c.jpg)

### Steps To Reproduce

Running Any action using Firefox Extension for Raycast

### Current Behaviour

Says that Firefox is not installed

### Expected Behaviour

Actions should execute in Firefox

**Comment by i-vrnv** [comment]
@asala6675467 Hi! Have you solved the problem?

**Comment by asala6675467** [comment]
No, the problem is still there: Firefox is still installed and I still get the same dialog.

**Comment by i-vrnv** [comment]
@asala6675467 I've found a solution.

1. Check your Firefox profiles folder `$HOME/Library/Application Support/Firefox/Profiles`
2. If there are multiple folders with `.default-release` (or `.default-nightly` for FF Nightly) find folder for your profile. I found it by `Last changed` column. In my case my profile had some postfix with random numbers. <img width="315" alt="image" src="https://github.com/raycast/extensions/assets/22278399/cbb0677c-7dc9-435f-a6de-8b87dd2c7257">
3. Make a backup of Profiles folder
4. Remove stale folders and remove postfix if you have it.
5. Open `installs.ini` in `Firefox` folder and edit folder name.
6. Save the file and run Firefox.

After this manipulation the extension start working. Hope this help! 

PS: Judging by the code, people with more than one profile will receive the history and bookmarks of the profile that was selected under the index 0. You can check it [here](https://github.com/raycast/extensions/blob/c7beafd52945cff0c162323e3c8560152f2900fc/extensions/mozilla-firefox/src/util/index.ts#L15)
