### ISSUE TITLE
[Google Translate] "something went wrong"

### ISSUE THREAD

**Issue by jaranflaath** [raycast/extensions#6029]
### Extension

https://www.raycast.com/gebeto/translate

#### Error:
```
TypeError: Cannot read properties of null (reading '1')
Url: https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=7575687618933437031&bl=boq_translate-webserver_20230417.08_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=5710&rt=c

index.js:90:21
async b0:translate-form.js:28:11660
```

### Steps To Reproduce

1. type "translate" into Raycast to open the extension. 
2. Start typing anything, and Raycast says "Something went wrong". 

### Current Behaviour

Extension fails with "Soemthing went wrong"

### Expected Behaviour

Working translation

**Comment by gebeto** [comment]
https://github.com/raycast/extensions/pull/6666

**Comment by gebeto** [comment]
Everything is okay now, this issue can be closed
