### ISSUE TITLE
[Spotify Beta] Bring "Just Play" feature over from the original extension

### ISSUE THREAD

**Issue by carsuki** [raycast/extensions#6032]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

### Description

Not sure if this is a common use case, but the main thing I use the current non-beta Spotify extension for is the "Just Play" function—being able to instantly play a song I want to hear is a really useful little feature. It saves the trouble of pulling up the Spotify window and searching for the song manually, waiting for Spotify's search to find something, and then hopefully having what I want be the top (easiest to click and play) result.

The only current option in this Beta version is to use the search. At least in this situation, it isn't significantly faster than just doing it through the regular Spotify app, and is a lot more navigation for the same result compared to one quick text input.

### Who will benefit from this feature?

Anyone who likes being able to quick play a song they want to hear in that moment without any additional searching or menus; when they already know the title/artist they're looking for and want to just punch it in and listen.

**Comment by peduarte** [comment]
Thank you. Noted and we'll consider this 👍

**Comment by sudhamjayanthi** [comment]
Huge +1 for this. It was one of the main features I used in the old extension.

**Comment by peduarte** [comment]
It's back, check out https://github.com/raycast/extensions/pull/6204
