### ISSUE TITLE
[Google Translate] ...

### ISSUE THREAD

**Issue by w0rng** [raycast/extensions#6037]
### Extension

https://www.raycast.com/gebeto/translate

### Description

Error: type mismatch at params.message : Expected to decode String but found a dictionary instead.

process.processImmediate:timers:471:21

**Comment by tangerine1202** [comment]
Can you provide the command, language set, and text you used?

**Comment by w0rng** [comment]
> Can you provide the command, language set, and text you used?

language set: Russian ->  english
I used different text in Russian, but now everything has been repaired
