### ISSUE TITLE
Crashes whenever you arrow down too quickly

### ISSUE THREAD

**Issue by frankreporting** [raycast/extensions#6042]
### Extension

https://www.raycast.com/thomas/downloads-manager

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20
```

### Steps To Reproduce

On MacOS 13.3.1, starting download manager with an alias, then hitting the down arrow key several times quickly.

### Current Behaviour

Hitting the down arrow key 2-3 times rapidly causes the extension to crash and I have to start over. If I key down more slowly, with a half second or so pause between each key press, it works fine. 

### Expected Behaviour

Hitting the arrow keys faster should simply make the selection change faster. Should not cause it to crash.

**Comment by ron-myers** [comment]
@frankreporting  - I can't replicate this.

How many files are in your downloads folder?  Is anything of massive scale or unique?
