### ISSUE TITLE
[Hypersonic] Extension is unresponsive after a single action every time

### ISSUE THREAD

**Issue by jakobbringman** [raycast/extensions#6045]
### Extension

https://www.raycast.com/reboot/hypersonic

#### Error:
```
Error: Could not launch command

process.processImmediate:timers:471:21

```

### Steps To Reproduce

1. Create a new task or mark existing task complete (My Tasks)
2. Create a second task or mark existing task complete (this step will not execute properly)
3. extension crashes

### Current Behaviour

Extension unresponsive after performing an action (endless loading of the top gray bar or crash)

### Expected Behaviour

Possible to perform any number of actions without crash

**Comment by martindisley** [comment]
Keeping this active as my ticket for the same issue got closed due to inactivity.
