### ISSUE TITLE
[Spotify Beta] ...

### ISSUE THREAD

**Issue by sudhamjayanthi** [raycast/extensions#6056]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

#### Error:
```
Error: Player command failed: Premium required

Ms:pause.ts:19:10
async onAction:nowPlayingMenuBar.js:99:2818
index.js:7:35293
```

### Steps To Reproduce

1. Play a song on spotify
2. Click on menu bar player
3. Click on pause

### Current Behaviour

It errors out and fails to pause the song. Apparently, I need a premium account for that. 

Old extension worked well without the need of a premium account too. Not sure, if it's a API change from Spotify side or a bug with this extension.

### Expected Behaviour

It successfully pauses the song.

**Comment by peduarte** [comment]
Closing in favour of https://github.com/raycast/extensions/issues/5904
