### ISSUE TITLE
[DuckDuckGo Search] Send the search result to other search engine

### ISSUE THREAD

**Issue by guspimentel** [raycast/extensions#6065]
### Extension

https://www.raycast.com/tegola/duck-duck-go-search

### Description

Hey, thanks a lot for this extension!

I was wondering if its possible to send the query result to another search engine. I'm using Neeva right now and it'd be awesome to be able to get search suggestions from DuckDuckGo and open the the Neevas's search page.

Is it possible to add custom search engines to open the search result page?

### Who will benefit from this feature?

People that seek for search engine that respects your privacy, wants to have the convenience of the Raycast provides and also wants flexibility to user another search engine.

**Comment by tegola** [comment]
I have never used Neeva, but if it’s a supported bang on DDG, there is an upcoming contribution to the plug-in that adds support for a few bangs. Or you could just use the bang already, since DDG does the redirect automatically when you use one.

The alternative would be developing a similar plugin just for Neeva.

**Comment by guspimentel** [comment]
> I have never used Neeva, but if it’s a supported bang on DDG, there is an upcoming contribution to the plug-in that adds support for a few bangs. Or you could just use the bang already, since DDG does the redirect automatically when you use one.
> 
> The alternative would be developing a similar plugin just for Neeva.

I've take a look on Neeva's docs and there is not current support for url params, like DDG does. The idea is to add something similar to the Quicklink feature, where you could add an url and a query parameter.

**Comment by tegola** [comment]
I don't get why you would use DuckDuckGo's suggestions while Neeva has their own. Aren't they just as good? This, assuming there are no licensing issues about using them outside Neeva's website/apps.
