### ISSUE TITLE
[ChatGPT] Ask Question report 'Something went wrong!'

### ISSUE THREAD

**Issue by RayKr** [raycast/extensions#6066]
### Extension

https://www.raycast.com/abielzulio/chatgpt

#### Error:
```
Error: read ECONNRESET

TLSWrap.onStreamRead:stream_base_commons:217:20

```

**Comment by abielzulio** [comment]
Do you still face this particular issue on a daily basis? From my understanding, that error would be something related to your connection. Have you checked your internet connectivity?

**Comment by RayKr** [comment]
> 

Yes, I am still facing this problem now. I have set up the proxy config, but it still doesn't work.
