### ISSUE TITLE
[ChatGPT] How to use existing paid ChatGPT account?

### ISSUE THREAD

**Issue by anjit6** [raycast/extensions#6071]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

The current implementation for this extension expects to input the OpenAI secret key. But what if you already have a paid account for the standalone ChatGPT? Is there any way to log in with an account and start using ChatGPT inside Raycast?

**Comment by abielzulio** [comment]
@raycastbot close this issue

It's a different account. You need to have a `pay-as-you-go` plan API key in order to use the extension.
