### ISSUE TITLE
[ChatGPT] Something went wrong

### ISSUE THREAD

**Issue by 0xlane** [raycast/extensions#6074]
### Extension

https://www.raycast.com/abielzulio/chatgpt

#### Error:
```
Error: Request failed with status code 400

hs.exports:createError.js:16:14
bs.exports:ask.js:2:7730
IncomingMessage.<anonymous>:ask.js:7:11807
IncomingMessage.emit:node:events:525:35
```

**Comment by abielzulio** [comment]
Are you still facing this issue on a daily basis?

**Comment by 0xlane** [comment]
Yes, I suspect that raycast does not support my HTTP proxy service. It works fine when I use someone else's HTTP proxy service, but my proxy service uses the vless protocol. However, when using the same proxy, the chathub plugin in Chrome works fine after configuring the proxy and API. But for the chatgpt plugin in Raycast, it cannot be used after configuring the proxy and API.
