### ISSUE TITLE
[Spotify Beta] Use Apple Script to control playback

### ISSUE THREAD

**Issue by kvdo2** [raycast/extensions#6079]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

### Description

Now the way to control music is to call Spotify Web API, which requires Premium to control, otherwise an error will be throw. 

`Spotify Player` supports controlling playback through Apple Script. Does Spotify Beta have such a plan in the future?

<img width="862" alt="image" src="https://user-images.githubusercontent.com/78251524/233574718-29319f7f-2019-4cea-875d-e6e09724f3e9.png">

### Who will benefit from this feature?

Playback can be controlled without Premium

**Comment by peduarte** [comment]
Thanks! Closing in favour of https://github.com/raycast/extensions/issues/5904
