### ISSUE TITLE
[Deepcast] first use unsuccessful

### ISSUE THREAD

**Issue by tobias-schnabel** [raycast/extensions#6105]
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

installed raycast and extension, signed up for deepl API (free tier), copied and pasted API key, wanted to try out the extension, but got this error message: 
<img width="446" alt="Screenshot 2023-04-22 at 21 45 58" src="https://user-images.githubusercontent.com/70516553/233803626-399bb4d8-2837-4258-9675-5e37ad4d12ca.png">

tried generating new deepl API key and updating it in extension settings, same issue. DeepL account shows 0 characters used.

**Comment by MonsterDeveloper** [comment]
Hi!

I tried to replicate the issue, but on my machine everything works fine. Perhaps, @mooxl could provide us with another test.

Also, could you please run a `curl` command in the terminal to see whether an API is reachable from your machine? Replace `{{you_api_token}}` with your access token received from DeepL.
```bash
curl --request POST \
  --url https://api-free.deepl.com/v2/translate \
  --header 'Authorization: DeepL-Auth-Key {{you_api_token}}' \
  --header 'Content-Type: application/json' \
  --data '{
	"text": ["Hi! This is a sample text."],
	"target_lang": "de"
}'
```

Meanwhile, I'll try to improve error handling in Deepcast. This is a weak point right now.

**Comment by tobias-schnabel** [comment]
Hi, thanks for the quick response!
Ran the curl request, worked fine (I removed my API key):
`~$ curl --request POST \
  --url https://api-free.deepl.com/v2/translate \
  --header 'Authorization: DeepL-Auth-Key *' \    
  --header 'Content-Type: application/json' \
  --data '{
        "text": ["Hi! This is a sample text."],
        "target_lang": "de"
}'
{"translations":[{"detected_source_language":"EN","text":"Hallo! Dies ist ein Beispieltext."}]}% `

**Comment by MonsterDeveloper** [comment]
Hi once again!

My PR #6118 has just been merged, which includes improved error handling. Could you please update the extension and make a screenshot of the error?

**Comment by tobias-schnabel** [comment]
Hi! Extension now works perfectly fine, I have tried several translations, LGTM
