### ISSUE TITLE
Error Request failed with status code 429

### ISSUE THREAD

**Issue by micwaab** [raycast/extensions#6108]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Whenever I attempt to use the Raycast chatGPT extension, I always get the error: Error Request failed with status code 429.

My Raycast is current as of today, 2023-04-22—extension has been downloaded today as well.

### Steps To Reproduce

1. Open Raycast
2. Run chatGPR extension
3. Ask a question
4. Receive error: Error Request failed with status code 429

### Current Behaviour

Unable to get any info from chatGPT through Raycast. However, I can open a browser window and use chatGPT with the same account with no issues.

### Expected Behaviour

I expect to be able to interact with chatGPT via the Raycast extension.

**Comment by abielzulio** [comment]
You need to upgrade your developer account to a `pay-as-you-go` plan.

**Comment by micwaab** [comment]
@raycastbot close this issue
