### ISSUE TITLE
[Apple Notes] ...

### ISSUE THREAD

**Issue by rjqueen** [raycast/extensions#6112]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

With your Search Notes extension I am able to determine the URL of a note which can then be used as a link in a different note to link back to that note. Which is kind of cumbersome. It would be awsome to have a way to just copy a note's URL by selecting it to run a command to retrieve the URL and then paste it as a link in a subsequent note. It would really be super to maybe even have an index or history of copied Note URLs to search and then use a selection from that list as a link anywhere in Notes.

### Who will benefit from this feature?

Anyone who uses Notes and wants a way to refer or pull up additional notes efficiently - esp as it's difficult to always remember the title of a note or which folder it might be located in.

**Comment by StevenRCE0** [comment]
That's cool, we are making Obsidian/Notion-like app based on Apple Notes! 😮

**Comment by SKaplanOfficial** [comment]
Not sure if this is within the scope of this extension. I personally think that the copy URL action as it exists now is sufficient, considering that the copied URL will appear in your clipboard history and can be pinned there. What do others think?

**Comment by tylerwince** [comment]
I would agree with @SKaplanOfficial. I’ve created a PR to make the Copy Note URL also copy a Rich Text version with the note name as to make this even easier with the current functionality. #6646
