### ISSUE TITLE
[ChatGPT] ...

### ISSUE THREAD

**Issue by Koeter** [raycast/extensions#6115]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Hi, I have a ChatGPT plus account from OpenAI. I have entered my API key but still get the 429 error. Is as pay-as-you-go account different from ChatGPT plus?

**Comment by abielzulio** [comment]
> ### Extension
> 
> https://www.raycast.com/abielzulio/chatgpt
> ### Description
> 
> Hi, I have a ChatGPT plus account from OpenAI. I have entered my API key but still get the 429 error. Is as pay-as-you-go account different from ChatGPT plus?
> ### Steps To Reproduce
> 
> _No response_
> ### Current Behaviour
> 
> _No response_
> ### Expected Behaviour
> 
> _No response_

Yes

**Comment by abielzulio** [comment]
@raycastbot close this issue
