### ISSUE TITLE
[Extension Feature Request] Target Daily Note in Obsidian

### ISSUE THREAD

**Issue by leah-ferguson** [raycast/extensions#612]
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/obsidian/)
Author: @marcjulianschwarz 

**Describe the feature and the current behaviour/state.**
I'd love to create a hotkey in Raycast to append to my current daily note specifically. Right now, I can append by searching the note title, but it would reduce the friction if I could have daily notes as a separate command.

**Who will benefit from this feature?**
Anyone who uses the core plugin Daily Note (which, from experience in the Obsidian community, will be a good percentage of Obsidian users).

**Any Other info.**
This could be achievable *if* the user has the community plugin [Advanced URI](https://github.com/Vinzent03/obsidian-advanced-uri) installed and activated.
The daily note URI is `obsidian://advanced-uri?vault=VAULTNAMEHERE&daily=true`

**Comment by marcjulianschwarz** [comment]
Do I understand it correctly that you have to have the Advanced URI plugin installed to make this work?

**Comment by marcjulianschwarz** [comment]
Hi @leah-ferguson, I just got another [feature request at my own repo](https://github.com/marcjulianschwarz/obsidian-raycast/issues/11) about daily notes.

Do you think the proposed solution (custom commands for obsidian URIs) would address your feature request too?

**Comment by marcjulianschwarz** [comment]
This issue is not stale as it has been addressed in a new pull request #1196.

**Comment by marcjulianschwarz** [comment]
Hi @leah-ferguson,

the requested feature has been added to the store.
