### ISSUE TITLE
[Spotify Beta] Menu Bar Player not showing

### ISSUE THREAD

**Issue by erngpawat** [raycast/extensions#6128]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

### Description

Menu Bar Player not showing

### Steps To Reproduce

1. Type in menu bar player in raycast and hit enter

### Current Behaviour

Only the white Spotify logo is showing

### Expected Behaviour

Menu Bar Player is supposed to be showing

**Comment by peduarte** [comment]
If you see the white spotify logo in your menu bar, then it has been activated. once you start playing something through Spotify, the name of the playing track will appear next to the logo. are you saying that is not happening?

**Comment by erngpawat** [comment]
I've disabled to original spotify extension, restarted raycast, and now got
it to work.

Thank for the reply. Loving this new update so far. And also appreciate
your transparency with the dev process on Twitter!

**Comment by peduarte** [comment]
Thank you 🙌
