### ISSUE TITLE
GetSelectedText fails with error "Cannot copy selected text from frontmost application"

### ISSUE THREAD

**Issue by Nevon** [raycast/extensions#6129]
### Description

Calling `await getSelectedText()` throws the following error:

```
Error: Cannot copy selected text from frontmost application.
    at gc (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:6:228)
    at pc (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:5:6799)
    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:5:6649)
    at process.processImmediate (node:internal/timers:471:21)
```

I reproduced this with the ChatGPT extension, but I don't see that it's doing anything unusual as far as I can tell: https://github.com/raycast/extensions/blob/main/extensions/chatgpt/src/hooks/useQuestion.tsx#L15-L38

### Steps To Reproduce

1. Using the latest version of the ChatGPT extension
2. Enabling the option to automatically load the selected text into a new conversation
3. When starting a new conversation there is a toast with the above error

**Comment by mathieudutour** [comment]
What application are you trying to get the selected text from?

**Comment by Nevon** [comment]
Pretty sure it was VS Code. It never worked with any application, so i didn't take note of which ones i tried, but vscode was definitely one of them.

**Comment by mathieudutour** [comment]
I just tried 
```js
import { getSelectedText, showHUD } from "@raycast/api";

export default async function command() {
  showHUD(await getSelectedText());
}
```
and it seems to work fine. Make sure that you granted Raycast access to "Accessibility" in System Settings > Privacy & Security > Accessibility.

**Comment by Nevon** [comment]
Thank you, that did indeed work. Maybe there's an opportunity for Raycast to listen for this kind of error (if possible) and prompt the user to grant the needed permissions? I've seen a lot of applications request permissions at startup for things like window managers and such.

**Comment by mathieudutour** [comment]
You should have been prompted for the permissions. If you deny it, I don't believe it's possible to prompt again
