### ISSUE TITLE
[Home Assistant] Filter shown entities 

### ISSUE THREAD

**Issue by MDXDave** [raycast/extensions#6130]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Description

As it is not possible to hide hidden entities (see #4228), it would be helpful to choose from a list of entities that should be shown within Raycast.

This would made it possible to get rid of entries that are not needed to be controlled from Raycast.

For example when i want to switch on a entity with the name WLED, there are many other entries that are shown that are related to the searched entity, but not useful to display within Raycast.

![image](https://user-images.githubusercontent.com/6099976/234014425-76995271-409a-46cc-8a93-8e67161e9c0f.png)

### Who will benefit from this feature?

Everyone uses the Raycast HA extension.

**Comment by tonka3000** [comment]
@raycastbot close this issue
