### ISSUE TITLE
[Todoist] "Today" and "Upcoming" commands show tasks not assigned to me 

### ISSUE THREAD

**Issue by enricenrich** [raycast/extensions#6133]
### Extension

https://www.raycast.com/thomaslombart/todoist

### Description

The "Today" and "Upcoming" commands show tasks not assigned to me. To solve that issue, the filter that fetches the tasks should be updated to include tasks that aren't assigned OR that are assigned to the logged in user (`me`).

**Example (not tested):**

* [`today.tsx`](https://github.com/raycast/extensions/blob/d065abad2aaeb89078db3453335533e7a90040e9/extensions/todoist/src/today.tsx#L22) → `(overdue | today) & (!assigned | assigned to: me)`
* [`upcoming.tsx`](https://github.com/raycast/extensions/blob/d065abad2aaeb89078db3453335533e7a90040e9/extensions/todoist/src/upcoming.tsx#L14) → `all & (!assigned | assigned to: me)`

### Steps To Reproduce

1. Create a shared project.
2. Create a task due today and assigned to a different user.
3. Run the "Today" or "Upcoming" commands.

### Current Behaviour

That new task is shown.

### Expected Behaviour

The new tasks should not be shown.

**Comment by thomaslombart** [comment]
Hey @enricenrich, I'm working on an overhaul of the extension that should solve your issue (and provide many other [useful features](https://twitter.com/thomas_lombart/status/1650417086940827651)). Stay tuned 📻

**Comment by enricenrich** [comment]
Thanks for the update, @thomaslombart! I'm looking forward to test it. 🚀

**Comment by thomaslombart** [comment]
Fixed: #6498
