### ISSUE TITLE
[ENS Name Lookup] Not working at all

### ISSUE THREAD

**Issue by BrennerSpear** [raycast/extensions#6137]
### Extension

https://www.raycast.com/Yukai/ens-name-lookup

### Description

No matter what I do I get `"cannot perform search. Forbidden"`

**Comment by Yukaii** [comment]
Thanks for reporting this!

The current version was based on an HTML crawler to Etherscan.io. It seems that ENS lookup on Etherscan has recently added Cloudflare protection. Maybe it's time to find a more stable way to fix this.

**Comment by BrennerSpear** [comment]
Hmm I wonder if their API has something. Or just a small lambda that uses
Ethers
