### ISSUE TITLE
[Microsoft Teams Meeting] ...

### ISSUE THREAD

**Issue by Gitupah** [raycast/extensions#6138]
### Extension

https://www.raycast.com/sven/microsoft-teams-calling

### Description

I installed the Raycast extension and copied the API token from Teams into the extension config, but it is not working for me.

![CleanShot 2023-04-24 at 13 56 19](https://user-images.githubusercontent.com/2104185/234115786-f5cb00fe-d434-45dc-ba5d-810b227552b0.png)

Teams version is 1.6.00.7354. (Mac)

**Comment by svenwiegand** [comment]
@Gitupah As the screenshot states: The extension will only do something if a Teams call is in progress.

If it still does not work, ensure that you copied the token von teams without any whitespaces at the beginning or end. At least one other user had this issue.

**Comment by Gitupah** [comment]
Thank you. It was the whitespace issue. It's working now.

**Comment by svenwiegand** [comment]
Happy to hear, it worked.

@raycastbot close this issue
