### ISSUE TITLE
[Hue] Set scene directly with top level command

### ISSUE THREAD

**Issue by sasha42** [raycast/extensions#6139]
### Extension

https://www.raycast.com/pindab0ter/hue

### Description

Today, in order to set a scene, you have to run the 'Control Groups' command, then tap on a control group, and then tap on a scene. It would be great if you could program a scene to trigger directly with a keyboard shortcut or a alias - for example, set the _bedroom_ to _nightlight_ with _ctr + cmd + l_.

For example, by implementing an 'Add to favorites' action, users will then be able to trigger the scene with their keyboard using an easy to use shortcut.

<img width="784" alt="Capture d’écran 2023-04-24 à 23 58 49" src="https://user-images.githubusercontent.com/1775702/234125807-ffabd458-46f0-42b9-b09a-464f446b2ccc.png">

### Who will benefit from this feature?

Philips Hue and Raycast users who have a small number of scenes that are frequently used.

**Comment by robertvanhoesel** [comment]
This is a good idea and should be possible using the [`Action.CreateQuickLink`](https://developers.raycast.com/api-reference/user-interface/actions#action.createquicklink) component in combination with the deeplink scheme.on with the [deeplink](https://developers.raycast.com/information/lifecycle/deeplinks) scheme. Would be something like raycast://extensions/pindab0ter/hue/setScene?launchContext=%7B%22sceneId%22%3A%22abc-234%22%7D

The recent Spotify Beta Extension has a good example:
https://github.com/raycast/extensions/blob/c7e094ac950b7294675419734f401a404d9e9e31/extensions/spotify-beta/src/quickActions.tsx#L56-L65

As a bonus this would allow controlling lights from other non-raycast apps by using those deeplinks.

Happy to play with this over the course of this weekend @pindab0ter

**Comment by pindab0ter** [comment]
Love the idea! Great suggestion!

@robertvanhoesel would that allow for setting a keyboard shortcut?

You can work off of my draft PR #6006 if you feel like giving it a go!

**Comment by robertvanhoesel** [comment]
@pindab0ter yes, the create quicklink action prefils the form for the Create Quick Link command that has been there for a while. You can then assign shortcuts, aliases, custom names etc.

**Comment by pindab0ter** [comment]
I see, awesome! I look forward to what you come up with! Feel free to message me on Slack, too.
