### ISSUE TITLE
[JetBrains Toolbox Recent Projects] Env wrong set

### ISSUE THREAD

**Issue by imshenshen** [raycast/extensions#6143]
### Extension

https://www.raycast.com/gdsmith/jetbrains

### Description

使用raycast登录webstorm，会带上Raycast的Env。。。
<img width="1243" alt="截屏2023-04-25 15 46 59" src="https://user-images.githubusercontent.com/19701958/234211168-8c05f3c0-4ff5-45f6-a04d-e8b49afcdb09.png">

### Current Behaviour

NODE_ENV is production

### Expected Behaviour

node NODE_ENV from raycast

**Comment by gdsmith** [comment]
@imshenshen I thought we'd fixed that issue. Is this happening all the time, or only when opening a project with JB app closed?

**Comment by imshenshen** [comment]
我没办法复现这个问题，我重启了电脑后没有这个问题了。目前我只能凭借印象提供一些信息：
1. 我同时打开了三个项目
1. 我当时运行了一个Webstorm的Node Debug，它突然断开了
2. 当我再次执行时Debug时，Webstorm提示我找不到可执行的Node程序
3. 然后我在Webstorm中手动配置了Node Interpreter，开始Debug我的npm script，我突然发现是production模式了
4. 我新打开了一个Webstorm的Terminal，执行 `env | grep NODE`，发现是Production模式并且NODE_PATH指向了Raycast的目录
5. 我用 `iTerm2`新开窗口执行 `env | grep NODE` 没有任何输出
6. 我在Githut上提交了issue，重新启动了电脑。

## translate by ai

   I am unable to reproduce the issue at the moment as restarting my computer has resolved it. However, based on my recollection, here are some details:
   1. I had three projects open simultaneously.
   2. I was running a Node Debug in Webstorm that suddenly disconnected.
   3. When I attempted to run the debug again, Webstorm could not find an executable Node program.
   4. I manually configured the Node Interpreter in Webstorm and began debugging my npm script, only to realize that it was in production mode.
   5. I opened a new Terminal in Webstorm and ran `env | grep NODE`, which showed that it was in Production mode and pointing to the directory of Raycast.
   6. I opened a new window in iTerm2 and ran `env | grep NODE`, but there was no output.
   7. I submitted an issue on GitHub and restarted my computer.

**Comment by gdsmith** [comment]
What makes you think it was the extension that caused the node env issue?
