### ISSUE TITLE
[Google Translate] usually gives me different and worse results than google translate web

### ISSUE THREAD

**Issue by danielo515** [raycast/extensions#6145]
### Extension

https://www.raycast.com/gebeto/translate

### Description

This is not properly a bug, just something I wanted to raise, because it defeats a bit the purpose of the extension. Many times the extension gives me results that I'm not happy with, so I go and test the same query in the web version and then I get much better results there.

**Comment by gebeto** [comment]
This one is in progress, hope will merge it soon

**Comment by gebeto** [comment]
https://github.com/raycast/extensions/pull/6666

**Comment by gebeto** [comment]
This issue can be closed, it was fixed in #6666
