### ISSUE TITLE
[YouVersion Bible Bug] does not work after change language setting to Chinese...

### ISSUE THREAD

**Issue by phoenixwu** [raycast/extensions#6146]
### Extension

https://www.raycast.com/caleb531/youversion-suggest

### Description

does not work after change language setting to Chinese or Japanese.
It may be encoding issue or unicode issue?

**Comment by caleb531** [comment]
@phoenixwu Thanks for the report! I am aware of this issue, and actually already have a fix in my new [YVS Node package](https://github.com/caleb531/youversion-suggest-node). I already have plans to integrate that package into YVS Raycast, and once I do, this issue will be fixed. Now that you've let me know there's a critical bug, I will be sure to prioritize this work.

In other words, please hang tight—I'm working on it!

-Caleb
