### ISSUE TITLE
[Spotify Beta] Browse playlist folders using "Your Library"

### ISSUE THREAD

**Issue by lodybo** [raycast/extensions#6153]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

### Description

I have a lot of playlists and organized them using [playlist folders](https://support.spotify.com/us/article/playlist-folders/). When I switch into "Your Library", I can see the playlists I have/follow that I haven't put into a folder, but I cannot see the ones that are moved into a playlist folder.

It would be nice if I could select playlists that are inside a playlist folder, because it would make the action of selecting a playlist from Spotify inside Raycast more usable.

### Who will benefit from this feature?

Anyone who has playlist folders.

**Comment by peduarte** [comment]
Hey, thanks, unfortunately that's a limitation of the Spotify API. People have been asking for this since [2015](https://github.com/spotify/web-api/issues/38#issue-71794037) :/

**Comment by lodybo** [comment]
Okay, I see.. Well that's too bad unfortunately. Thanks anyway for making a great extension!
