### ISSUE TITLE
Downie 4 Causes the plugin to not work

### ISSUE THREAD

**Issue by macOSWk** [raycast/extensions#6157]
### Extension

https://www.raycast.com/mackopes/quit-applications

### Description

Error: Command failed: plutil -convert json "/Applications/Downie 4.app/Contents/Info.plist" -o - checkExecSyncError:node:child_process:871:11 execSync:node:child_process:943:15 Ss:index.js:5:12411 index.js:21:646

**Comment by mackopes** [comment]
hey! thanks for raising this issue, this seems to be related to https://github.com/raycast/extensions/issues/5356. I will try to push the fix soon.

**Comment by mackopes** [comment]
@macOSWk This issue should be fixed now. Could you please check it out and close the issue if it has been resolved for you? :)

**Comment by mackopes** [comment]
@raycastbot close this issue
