### ISSUE TITLE
[Brew] Untar Anywhere installation not supported

### ISSUE THREAD

**Issue by FullofQuarks** [raycast/extensions#6165]
### Extension

https://www.raycast.com/nhojb/brew

### Description

Homebrew installed via the untar anywhere method (https://docs.brew.sh/Installation#untar-anywhere-unsupported) is not supported by this extension, because it is looking in the default executable path.

In my specific example, brew prefix is `/Users/home/.brew`, which means that the brew executable is `/Users/home/.brew/bin/brew`.

### Steps To Reproduce

1. Install homebrew via untar anywhere instructions (https://docs.brew.sh/Installation#untar-anywhere-unsupported)
2. Try to use this extension

### Current Behaviour

This error is received with all brew actions in Raycast:

```Error: Command failed: /opt/homebrew/bin/brew update
/bin/sh: /opt/homebrew/bin/brew: No such file or directory

    at ChildProcess.exithandler (node:child_process:412:12)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:313:12)
```

### Expected Behaviour

The extension knows where brew is (`which brew`), and uses that to execute commands

**Comment by nhojb** [comment]
@FullofQuarks did you try setting a custom brew path in Settings -> Extensions -> Brew?

<img width="1112" alt="Screenshot 2023-04-25 at 19 33 02" src="https://user-images.githubusercontent.com/312540/234370072-c847fe1d-a0e2-4066-b449-922df9f54891.png">

**Comment by FullofQuarks** [comment]
Outrageous. I totally missed that. Thanks! Closing due to user error
