### ISSUE TITLE
[Jira] "Open Issues" fails

### ISSUE THREAD

**Issue by chrismetcalf** [raycast/extensions#6171]
### Extension

https://www.raycast.com/raycast/jira

#### Error:
```
Error: Rendering failed:
Missing required component property "title"
```

### Steps To Reproduce

1. Launch the JIRA "Open Issues" command
2. Command fails

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue #6011, so I'll mark it as such.
