### ISSUE TITLE
Append/Pretend to Draft won't add a prefix"- " if triggered via quick link

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#6181]
### Extension

https://www.raycast.com/FlohGro/drafts

### Description

Append/Pretend to Draft won't add "- " if triggered via quick link

here is a video - https://capture.dropbox.com/7CgH48ss21q5R32b

### Steps To Reproduce

1. Create "Append/Pretend to Draft" action
2. Add "- " prefix
3. Create a quick link to this action
4. Trigger quick link

### Current Behaviour

Won't add a prefix

### Expected Behaviour

Will add a prefix

**Comment by FlohGro-dev** [comment]
Thanks for the report @romanskorobagatko 
I will look into it in the 2nd week of may (I'm currently on vacation).
I didn't make any changes to this so if you're sure that it was setup correctly as a quicklink that's a bug which is there since the initial release and it should be an easy fix.

**Comment by FlohGro-dev** [comment]
Hi @romanskorobagatko I was able to reproduce this bug, thanks for your report. I'll fix it and release a new version of the extension. Thanks for your report!

**Comment by FlohGro-dev** [comment]
@romanskorobagatko its not updated yet. I'll do some minor updates to screenshots, too. The update then needs to be reviewed by the Raycast team before it will get published. 
I'll let you know here when it is fixed and published. The extension should auto update, but you can also force that via Raycast then.

**Comment by romanskorobagatko** [comment]
Thank you very much.

**Comment by FlohGro-dev** [comment]
@romanskorobagatko issue is fixed in new version in the Raycast store - you can force the update and test it 👍

**Comment by romanskorobagatko** [comment]
Seems to work as expected, thank you!

**Comment by FlohGro-dev** [comment]
Great to hear @romanskorobagatko 
Let me know when you have further requests 👌🏼
