### ISSUE TITLE
[Easy Dictionary] ...

### ISSUE THREAD

**Issue by monocyclergithub** [raycast/extensions#6186]
### Extension

https://www.raycast.com/isfeng/easydict

### Description

希望增加音量调整，现在是以100%音量播放单词发音的，而系统音量经常开不到100%，就会突然一播放单词吓一跳
Hoping to increase the volume adjustment, now the pronunciation of words is played at 100% volume, and the system volume is often turned on less than 100%, and suddenly the word is startled

**Comment by tisfeng** [comment]
@raycastbot close this issue
