### ISSUE TITLE
[Things] Add task bug: brackets in name make "something go wrong"

### ISSUE THREAD

**Issue by b-d-m-p** [raycast/extensions#6197]
### Extension

https://www.raycast.com/loris/things

### Description

When using the "Add New To-Do" command, if you have brackets, `()` in the name and press `cmd + return`, you will get a "Something went wrong" view.

### Steps To Reproduce

1. Open the Raycast command pallet
2. Type "Things"
3. Arrow down to "Add New To-Do" and press return
4. Enter a name with brackets like 'Test (test)`
5. Press `cmd + return`
6. A "Something went wrong" view will be displayed and the to-do will not be added.

Removing the brackets and doing the same process will allow the to-do to be added.

### Current Behaviour

On adding the task a "Something went wrong" view is displayed and the to-do is not added. 

### Expected Behaviour

The to-do with brackets can be added.

**Comment by loris** [comment]
Hi @b-d-m-p, just opened a PR to fix the issue.
Things URI Schema requires URL encoded string, but they actually have issue with some special characters that should not be encoded (like brackets or quotes), so I replaced the usual encodeURIComponent with escape (which is supposedly deprecated) which encode every special characters.

This should be more robust:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/8362/234800114-9851a1fe-4511-4636-95d7-e6ad85fc37f1.png">


Let me know if you have issue
