### ISSUE TITLE
[brew] Add capability to change brew path (Apple Silicone)

### ISSUE THREAD

**Issue by lewiuberg** [raycast/extensions#6198]
### Extension

https://www.raycast.com/nhojb/brew

### Description

On Macs with Apple Silicone/arm64 the default brew path commonly used is `/opt/homebrew/bin/brew`.

Note that many have a second brew installed for rosetta that uses the old `/usr/local/bin/brew`, however, not as the main brew.

### Who will benefit from this feature?

Ever brew user with Apple Silicone

**Comment by urwrstkn8mare** [comment]
> second brew installed for rosetta that uses the old /usr/local/bin/brew

@lewiuberg so do you want to be able to switch it while using the command? Because you can already change the executable used by putting the path in this preference:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/42769125/234789803-d3010c04-5262-4af8-97d5-f7caadcbef51.png">

**Comment by urwrstkn8mare** [comment]
@lewiuberg please see if [this PR](https://github.com/raycast/extensions/pull/6201#issue-1686473365) fixes your issue with the `Show Installed`.

> Maybe there could be a `brew switch` command that switched between the two different paths?

That could be done but it would add a lot of complication that most may not need. I could be wrong tho. Maybe the others may have suggestions for this?

**Comment by lewiuberg** [comment]
@urwrstkn8mare It works great now!

Thanks :)

**Comment by urwrstkn8mare** [comment]
Nw! I'm guessing you're running my version as a developer locally. In that case you'd probably have 2 instances of the extensions (1 with a hard drive icon) which you could use for each of your Homebrews. That could be a hacky solution to make it easy to switch between the 2. Just remember to keep the local copy up to date with this repo in case of any new features fixes etc.

**Comment by lewiuberg** [comment]
Not yet! But I'll have a look at the developer stuff tonight. Think I just got an idea for an extension myself. 

Thanks fort the swift replies and good support 💪🏻
