### ISSUE TITLE
[JetBrains Toolbox Recent Projects] Opens two instances of the app

### ISSUE THREAD

**Issue by keironlowe-edriving** [raycast/extensions#6203]
### Extension

https://www.raycast.com/gdsmith/jetbrains

### Description

When opening a recent project through Raycast, it opens up two instances of the app. One which only shows the "Welcome to {app}" window, and another with the actual project.
![image](https://user-images.githubusercontent.com/73830244/234849682-d58685c9-3406-465a-9486-3d4907c6e23d.png)
![image](https://user-images.githubusercontent.com/73830244/234849771-46aa3326-9cf8-4937-bfe4-325a7bcc727e.png)

### Steps To Reproduce

1. Use Raycast to open a recent project
2. Notice two applications open

### Current Behaviour

Two application instances are opened

### Expected Behaviour

A single application instance is opened

**Comment by DieterHolvoet** [comment]
I'm having the same issue!

**Comment by gdsmith** [comment]
Did you recently download a new version of your IDE? Does it only happen from Raycast or does the same thing happen if you use the cli to open a project?

**Comment by gdsmith** [comment]
Also, does it happen when IDE is open or only when it's closed?

**Comment by keironlowe-edriving** [comment]
> Did you recently download a new version of your IDE? Does it only happen from Raycast or does the same thing happen if you use the cli to open a project?

Toolbox auto updates so not sure, I do have the option to roll back to 2022.3.3 (PhpStorm).

Doesn't happen when I use the CLI. Seems to do it the first time you use Raycast, so if I open PHPStorm, then open a recent project using Raycast it does the two app thing, then any future use doesn't, until I quit then it will do it again.
