### ISSUE TITLE
[Deepcast] Cannot translate

### ISSUE THREAD

**Issue by pascalscr** [raycast/extensions#6210]
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

I've created an account for DeepL and registered for the free API, got the Key and pasted it into the extensions settings.

Now, when I wan't to translate something via the extension, I just cannot because "something went wrong."

I checked the API and used 0/500,000 characters. The key is correct, i copied it multiple times, typed it manually in, created a new key, nothing worked.

### Steps To Reproduce

1. Use the "translate" command of Deepcast via Raycast
2. Enter some text and let it translate

### Current Behaviour

When trying to translate it just says "something went wrong. Check your internet connection, API key, or you've maxed out the API."

### Expected Behaviour

To get the translated text.

**Comment by MonsterDeveloper** [comment]
Hi!

Seems to be a duplicate of #6105 and #5882.

I'd have to get some more details on the error and on how to reproduce it. No matter what I do, Deepcast works on my machine. I don't have another one to test it out, unfortunately.

For now I can suggest you doing [this test](https://github.com/raycast/extensions/issues/6105#issuecomment-1519084640) to see whether the API is accessible from your Mac.

Error reporting system in Deepcast is currently not informative at all, but I already have an open PR #6118 which aims to drastically improve error handling.

**Comment by pascalscr** [comment]
Hi @MonsterDeveloper 

yes, seems to be duplicate, sorry for that!

I did the test and received the expected return of:
{"translations":[{"detected_source_language":"EN","text":"Hallo, Welt!"}]}

**Comment by MonsterDeveloper** [comment]
Hi once again!

My PR #6118 has just been merged, which includes improved error handling. Could you please update the extension and make a screenshot of the error?

**Comment by pascalscr** [comment]
Thanks for the info! I just tried and got a translation, so no error so far!
