### ISSUE TITLE
[Unsplash] Unclear Random Wallpaper way of operating.

### ISSUE THREAD

**Issue by Tazintosh** [raycast/extensions#6214]
### Extension

https://www.raycast.com/eggsy/unsplash

### Description

I'm using an M1 mini running Ventura 13.1 and Raycast + Unsplash last version (as for this date).
My system, mainly always run two Spaces and multiple other full screen apps.
I've set the Unsplash Preference "Update Random Image" to "10 minute" and "Background Refresh" is checked on the "Set Random Wallpaper" command.
But my Desktop images never updates. I've to constantly trigger it manually and only the active Space is refreshed.
I'm starting to wonder if "Update Random Image" is at all related to the "wallpaper".
Am I missing something?

### Steps To Reproduce

1. Set the Unsplash Preference "Update Random Image" to "10 minute"
2. Check "Background Refresh" on the "Set Random Wallpaper" command.
3. Wait for it.
4. It won't change, so trigger it manually
5. Only the currently active Space will update.

### Current Behaviour

None of my spaces Wallpapers update automatically based on a given time.

### Expected Behaviour

All my spaces Wallpapers update automatically based on a given time.

**Comment by kkange** [comment]
Fixed background updates not working.

However, in my test environment, all displays updated the image just fine, so I'm not sure about this issue. 🤔
