### ISSUE TITLE
[Quick Event] add more help text to beginning screen

### ISSUE THREAD

**Issue by robrecord** [raycast/extensions#6221]
### Extension

https://www.raycast.com/mblode/quick-event

### Description

Please add the following to the help text for the initial input box:

> The calendar names can be found in the sidebar of Calendar.app

Otherwise everybody is confused.

### Who will benefit from this feature?

Everybody who installs via the Raycast Store

**Comment by bascomb** [comment]
Hey so your feature request is to change the instructions, right? I'm honored but you can create a PR to change :)
