### ISSUE TITLE
[Music] Emoji Icons are not rendering properly for playlist

### ISSUE THREAD

**Issue by GUOliver** [raycast/extensions#6226]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

It appears that two icons (before Total number of songs and Total duration of the playlist) are missing.
<img width="886" alt="Screenshot 2023-04-28 at 10 12 50 pm" src="https://user-images.githubusercontent.com/47715205/235144526-c659a86c-7c03-46dd-b4dd-8ac9d57c4178.png">

### Steps To Reproduce

1. Open Raycast from keyboard.
2. Input `Start Playlist` command from Apple music Extension.

### Expected Behaviour

Icons should be rendered properly as expected.

<img width="609" alt="Screenshot 2023-04-28 at 10 20 30 pm" src="https://user-images.githubusercontent.com/47715205/235145780-5898f80b-72df-4496-a49d-69e2c0495ffe.png">

**Comment by Rawnly** [comment]
Please double check to have sf symbols installed

**Comment by GUOliver** [comment]
It worked after i installed the sf symbol installed. Thanks !
@raycastbot close this issue
