### ISSUE TITLE
[Spotify Beta] Only the top 50 things in my library are being detected

### ISSUE THREAD

**Issue by FuriousNutSlaps** [raycast/extensions#6236]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

### Description

Not sure if it's a bug or this is how it's supposed to be coz of API limitations but:

1. The extension shows only 50 of my artists in Spotify on the artists page of Your Library. 
2. The extension only detects the most recent 50 playlists (or whatever custom order the top 50 are in) in my Spotify library, so whenever I search for playlists using the Your Library command, only these top 50 show up.
3. Even inside playlists that the extension does detect, only the top 50 songs in the playlist are detected.
4. Similarly, the extension only detects the top 50 songs in my Likes.

### Steps To Reproduce

Have more than 50 playlists, artists, songs in playlists in your Spotify Library.

### Current Behaviour

Only 50 things in your Spotify Library at a time will get detected by the Your Library feature of the extension, whether it be playlists, artists, or songs inside the playlist.

### Expected Behaviour

Everything should be detected?

**Comment by peduarte** [comment]
Pagination hasnt been done yet, will get to it though!

**Comment by FuriousNutSlaps** [comment]
Ahhh, TIL what pagination is. Should I close the issue?

**Comment by peduarte** [comment]
@FuriousNutSlaps Yeah, once we introduce the pagination API, I will implement it.
