### ISSUE TITLE
[Music]: 

### ISSUE THREAD

**Issue by wagninger** [raycast/extensions#6237]
### Extension

https://raycast.com/fedevitaledev/music

### Description

Command failed with exit code 1: osascript -e tell application "Music" to play 
28:32: execution error: Keine Berechtigung zum Senden von Apple-Events an Music. (-1743)

### Steps To Reproduce

in macOS 13.3.1 on an M1 Macbook Air, I did twice:

A fresh install of Raycast V 1.50.0 and the music plugin.

Gave it full disk access and access to "media & apple music".

tried to execute any of the plugins commands, but it either said it can't send Apple-Events to Music or "could not get Tracks" when trying to play anything from the library.

### Current Behaviour

Failing to execute any of the plugins commands and throwing an error message

### Expected Behaviour

either executing the commands or telling me what to do to fix it.

**Comment by Rawnly** [comment]
Hey thanks for reporting! This is quite weird 🫤

Can you try to change your system language to English? I have a suspect but i giorni I'm wrong.

**Comment by wagninger** [comment]
Hi,

Thanks for replying!
I changed it to „English - English“ and had to reboot, but I’m still getting „could not get Tracks“ :/

Mit freundlichen Grüßen/Best regards,

Andreas Wagner



Sandgasse 23/15
8010 Graz
Österreich
M: +43 676 3015907

**Comment by wagninger** [comment]
I have a suspicion… could it be that there are supposed to be some dialogues, asking for permission?
I haven’t seen any, but when I saw that it didn’t work, giving full disk access was my reflex.

Should I give any more permissions?

Mit freundlichen Grüßen/Best regards,

Andreas Wagner



Sandgasse 23/15
8010 Graz
Österreich
M: +43 676 3015907
Am 29. Apr. 2023, 12:18 +0200 schrieb Federico ***@***.***>:

**Comment by wagninger** [comment]
Hi!

Is there any new insight on what could cause this not-functioning? I could also test this on an Intel Mac (that is not mine) to see if it’s an issue there.

Mit freundlichen Grüßen/Best regards,

Andreas Wagner



Sandgasse 23/15
8010 Graz
Österreich
M: +43 676 3015907
Am 29. Apr. 2023, 12:18 +0200 schrieb Federico ***@***.***>:
