### ISSUE TITLE
[ChatGPT] ...

### ISSUE THREAD

**Issue by artyaz** [raycast/extensions#6238]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

The plugin crashes or just stops(while the loading bar is still animated) after writing some text. 

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20
```

### Steps To Reproduce

Open the plugin again. But it writes for about 4-6 seconds after that and crashes

**Comment by abielzulio** [comment]
@raycastbot close this issue.

Closing this issue due to a future fix that will be available on [the next update](https://github.com/raycast/extensions/pull/6528).
