### ISSUE TITLE
[Unsplash] ...An error has occurred The redirect uri included is not valid.

### ISSUE THREAD

**Issue by evanxia1213** [raycast/extensions#6245]
### Extension

https://www.raycast.com/eggsy/unsplash

### Description

After entering both keys, i will still need to open the link and authorize the access. However, there seems to be an issue with the Unsplash pages as they display an error message stating that the redirect URI provided is invalid.

### Steps To Reproduce

1. Enter both keys.
2. Follow the link provided.
3. Grant access authorization.
4. However, the Unsplash pages are currently displaying an error message indicating that the redirect URI is invalid.

**Comment by eggsy** [comment]
Please read the Installation part:

https://www.raycast.com/eggsy/unsplash

**Comment by rorybowcott** [comment]
@evanxia1213 Did you manage to resolve this issue? I am getting the same issue
