### ISSUE TITLE
[Bitbucket Search] Search repositories command does not give any result

### ISSUE THREAD

**Issue by shaunwen** [raycast/extensions#6248]
### Extension

https://www.raycast.com/Francois/bitbucket

### Description

Search repositories command does not give any result.

I got all the permissions ticket including: Account, projects, repositories, Pull Requests, Pipelines. Noticed when creating the app password, the repositories read permission got automatically ticked and greyed out if the projects read permission got ticket though. It works for search the PRs, but it does not work for repositories.

My Raycast version is 1.50.0. I installed the Bitbucket Search extension by today.

### Steps To Reproduce

open Search Repositories command, it shows the following:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/4570313/235340752-d808dfe8-35ae-4530-b1a2-7528525ab2c6.png">

### Current Behaviour

Search repositories command does not give any result.

### Expected Behaviour

The search repositories command show list available repositories before typing any keyword, and should be able to clicked into a repo to show related pipelines.

**Comment by Lp-Francois** [comment]
Hey! ☀️ 

I've just tried a fresh bitbucket extension install on latest raycast, and I don't get any errors, I can see a list of my repositories.

Can you confirm/send the following:
- screenshot of the new token permissions you are using
- make sure you use the new token
- you can see some repositories when going to: https://bitbucket.org/<organization_or_user>/workspace/repositories
- restart raycast (we never know haha)

Thanks

**Comment by shaunwen** [comment]
Hi @Lp-Francois, Sorry for the delay of providing the screenshot, the permission I used are the following:
![image](https://github.com/raycast/extensions/assets/4570313/d8deff2d-9159-4296-a945-2100955f1e33)
I am wondering if it has to be an item to allow the access of raycast explicitly in the Application authorizations section?

**Comment by shaunwen** [comment]
In addition, I retrieved some logs following [the instruction](https://manual.raycast.com/troubleshooting/getting-logs-via-consoleapp), please see the following attachement:
 
[ray.20230620_140725.log](https://github.com/raycast/extensions/files/11795723/ray.20230620_140725.log)

**Comment by Lp-Francois** [comment]
Hum, can you maybe try to create a token with full access, test if the extension is working? 
It would be to check if one permissions is the issue

There was another issue that seemed similar, be sure to have the latest updates on the extension & raycast

**Comment by shaunwen** [comment]
I have the latest version of raycast and extension, I am not sure if it has something to do with permission setting of our company. So it is hard to debug. Closing it as don't seem to be resolved.
