### ISSUE TITLE
[GitHub] Don't ask for write permissions

### ISSUE THREAD

**Issue by srid** [raycast/extensions#6253]
### Extension

https://www.raycast.com/raycast/github

### Description

This extension shouldn't need write access to my repos at all.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/3998/235358526-bd835bae-d243-4243-97ea-a2669adf5499.png">

### Steps To Reproduce

1. Install the extension
2. Use it

### Current Behaviour

Requests Write access

### Expected Behaviour

Requests only Read access

**Comment by thomaslombart** [comment]
Hey @srid, there's no OAuth scope allowing to only read repositories in [GitHub's Scopes for OAuth Apps](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps), only `repo` is available which grants access to both read and write access in both public and private repositories. I'm afraid we don't have any other choices as of now, so I'll close this issue.

![CleanShot 2023-05-02 at 12 17 12@2x](https://user-images.githubusercontent.com/16003285/235640966-4295107a-9505-437f-8a56-a4c8b28c1b7e.png)

**Comment by jdoconnor** [comment]
can the tool request `public_repo`instead of `repo`?

**Comment by thomaslombart** [comment]
@jdoconnor Many users are using the extension to also browse their private repositories, so while it's technically feasible, it wouldn't be worth it from a maintenance point of view.
