### ISSUE TITLE
[debank] ...

### ISSUE THREAD

**Issue by sheniatskii** [raycast/extensions#6256]
### Extension

https://www.raycast.com/Yukai/debank

#### Error: it dopesnt work
```

```

### Steps To Reproduce

1. Set wallet in search
2. Pay attention to the result

### Current Behaviour

Error: Request failed with status code 429

St.exports:index.js:1:5068

---
1: var nn=Object.create;var le=Object.defineProperty;var sn=Object.getOwnPropertyDescriptor;var on=Object.getOwnPropertyNames;var an=Object.getPrototypeOf,un=Object.prototype.hasOwnProperty;var pt=t=>le(t,"__esModule",{value:!0});var m=(t,e)=>()=>(e||t((e={exports:{}}).exports,e),e.exports),cn=(t,e)=>{for(var r in e)le(t,r,{get:e[r],enumerable:!0})},mt=(t,e,r,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let s of on(e))!un.call(t,s)&&(r||s!=="default")&&le(t,s,{get:()=>e[s],enumerable:!(n=sn(e,s))||n.enumerable});return t},ln=(t,e)=>mt(pt(le(t!=null?nn(an(t)):{},"default",!e&&t&&t.__esModule?{get:()=>t.default,enumerable:!0}:{value:t,enumerable:!0})),t),fn=(t=>(e,r)=>t&&t.get(e)||(r=mt(pt({}),e,1),t&&t.set(e,r),r))(typeof WeakMap!="undefined"?new WeakMap:0);var Oe=m((Ys,vt)=>{"use strict";vt.exports=function(e,r){return function(){for(var s=new Array(arguments.length),o=0;o<s.length;o++)s[o]=arguments[o];return e.apply(r,s)}}});var R=m((Xs,gt)=>{"use strict";var dn=Oe(),M=Object.prototype.toString;function Le(t){return M.call(t)==="[object Array]"}function Be(t){return typeof t=="undefined"}function hn(t){return t!==null&&!Be(t)&&t.constructor!==null&&!Be(t.constructor)&&typeof t.constructor.isBuffer=="function"&&t.constructor.isBuffer(t)}function pn(t){return M.call(t)==="[object ArrayBuffer]"}function mn(t){return typeof FormData!="undefined"&&t instanceof FormData}function vn(t){var e;return typeof ArrayBuffer!="undefined"&&ArrayBuffer.isView?e=ArrayBuffer.isView(t):e=t&&t.buffer&&t.buffer instanceof ArrayBuffer,e}function Cn(t){return typeof t=="string"}function yn(t){return typeof t=="number"}function Ct(t){return t!==null&&typeof t=="object"}function fe(t){if(M.call(t)!=="[object Object]")return!1;var e=Object.getPrototypeOf(t);return e===null||e===Object.prototype}function gn(t){return M.call(t)==="[object Date]"}function bn(t){return M.call(t)==="[object File]"}function wn(t){return M.call(t)==="[object Blob]"}function yt(t){return M.call(t)==="[object Function]"}function _n(t){return Ct(t)&&yt(t.pipe)}function En(t){return typeof URLSearchParams!="undefined"&&t instanceof URLSearchParams}function Rn(t){return t.trim?t.trim():t.replace(/^\s+|\s+$/g,"")}function xn(){return typeof navigator!="undefined"&&(navigator.product==="ReactNative"||navigator.product==="NativeScript"||navigator.product==="NS")?!1:typeof window!="undefined"&&typeof document!="undefined"}function Pe(t,e){if(!(t===null||typeof t=="undefined"))if(typeof t!="object"&&(t=[t]),Le(t))for(var r=0,n=t.length;r<n;r++)e.call(null,t[r],r,t);else for(var s in t)Object.prototype.hasOwnProperty.call(t,s)&&e.call(null,t[s],s,t)}function Ne(){var t={};function e(s,o){fe(t[o])&&fe(s)?t[o]=Ne(t[o],s):fe(s)?t[o]=Ne({},s):Le(s)?t[o]=s.slice():t[o]=s}for(var r=0,n=arguments.length;r<n;r++)Pe(arguments[r],e);return t}function qn(t,e,r){return Pe(e,function(s,o){r&&typeof s=="function"?t[o]=dn(s,r):t[o]=s}),t}function Sn(t){return t.charCodeAt(0)===65279&&(t=t.slice(1)),t}gt.exports={isArray:Le,isArrayBuffer:pn,isBuffer:hn,isFormData:mn,isArrayBufferView:vn,isString:Cn,isNumber:yn,isObject:Ct,isPlainObject:fe,isUndefined:Be,isDate:gn,isFile:bn,isBlob:wn,isFunction:yt,isStream:_n,isURLSearchParams:En,isStandardBrowserEnv:xn,forEach:Pe,merge:Ne,extend:qn,trim:Rn,stripBOM:Sn}});var de=m((Ks,wt)=>{"use strict";var z=R();function bt(t){return encodeURIComponent(t).replace(/%3A/gi,":").replace(/%24/g,"$").replace(/%2C/gi,",").replace(/%20/g,"+").replace(/%5B/gi,"[").replace(/%5D/gi,"]")}wt.exports=function(e,r,n){if(!r)return e;var s;if(n)s=n(r);else if(z.isURLSearchParams(r))s=r.toString();else{var o=[];z.forEach(r,function(c,f){c===null||typeof c=="undefined"||(z.isArray(c)?f=f+"[]":c=[c],z.forEach(c,function(u){z.isDate(u)?u=u.toISOString():z.isObject(u)&&(u=JSON.stringify(u)),o.push(bt(f)+"="+bt(u))}))}),s=o.join("&")}if(s){var a=e.indexOf("#");a!==-1&&(e=e.slice(0,a)),e+=(e.indexOf("?")===-1?"?":"&")+s}return e}});var Et=m((Zs,_t)=>{"use strict";var An=R();function he(){this.handlers=[]}he.prototype.use=function(e,r,n){return this.handlers.push({fulfilled:e,rejected:r,synchronous:n?n.synchronous:!1,runWhen:n?n.runWhen:null}),this.handlers.length-1};he.prototype.eject=function(e){this.handlers[e]&&(this.handlers[e]=null)};he.prototype.forEach=function(e){An.forEach(this.handlers,function(n){n!==null&&e(n)})};_t.exports=he});var xt=m((Qs,Rt)=>{"use strict";var Fn=R();Rt.exports=function(e,r){Fn.forEach(e,function(s,o){o!==r&&o.toUpperCase()===r.toUpperCase()&&(e[r]=s,delete e[o])})}});var pe=m((ei,qt)=>{"use strict";qt.exports=function(e,r,n,s,o){return e.config=r,n&&(e.code=n),e.request=s,e.response=o,e.isAxiosError=!0,e.toJSON=function(){return{message:this.message,name:this.name,description:this.description,number:this.number,fileName:this.fileName,lineNumber:this.lineNumber,columnNumber:this.columnNumber,stack:this.stack,config:this.config,code:this.code,status:this.response&&this.response.status?this.response.status:null}},e}});var me=m((ti,St)=>{"use strict";var Tn=pe();St.exports=function(e,r,n,s,o){var a=new Error(e);return Tn(a,r,n,s,o)}});var Ie=m((ri,At)=>{"use strict";var On=me();At.exports=function(e,r,n){var s=n.config.validateStatus;!n.status||!s||s(n.status)?e(n):r(On("Request failed with status code "+n.status,n.config,null,n.request,n))}});var Tt=m((ni,Ft)=>{"use strict";var ve=R();Ft.exports=ve.isStandardBrowserEnv()?function(){return{write:function(r,n,s,o,a,l){var c=[];c.push(r+"="+encodeURIComponent(n)),ve.isNumber(s)&&c.push("expires="+new Date(s).toGMTString()),ve.isString(o)&&c.push("path="+o),ve.isString(a)&&c.push("domain="+a),l===!0&&c.push("secure"),document.cookie=c.join("; ")},read:function(r){var n=document.cookie.match(new RegExp("(^|;\\s*)("+r+")=([^;]*)"));return n?decodeURIComponent(n[3]):null},remove:function(r){this.write(r,"",Date.now()-864e5)}}}():function(){return{write:function(){},read:function(){return null},remove:function(){}}}()});var Lt=m((si,Ot)=>{"use strict";Ot.exports=function(e){return/^([a-z][a-z\d\+\-\.]*:)?\/\//i.test(e)}});var Pt=m((ii,Bt)=>{"use strict";Bt.exports=function(e,r){return r?e.replace(/\/+$/,"")+"/"+r.replace(/^\/+/,""):e}});var De=m((oi,Nt)=>{"use strict";var Ln=Lt(),Bn=Pt();Nt.exports=function(e,r){return e&&!Ln(r)?Bn(e,r):r}});var Dt=m((ai,It)=>{"use strict";var Ue=R(),Pn=["age","authorization","content-length","content-type","etag","expires","from","host","if-modified-since","if-unmodified-since","last-modified","location","max-forwards","proxy-authorization","referer","retry-after","user-agent"];It.exports=function(e){var r={},n,s,o;return e&&Ue.forEach(e.split(`
2: `),function(l){if(o=l.indexOf(":"),n=Ue.trim(l.substr(0,o)).toLowerCase(),s=Ue.trim(l.substr(o+1)),n){if(r[n]&&Pn.indexOf(n)>=0)return;n==="set-cookie"?r[n]=(r[n]?r[n]:[]).concat([s]):r[n]=r[n]?r[n]+", "+s:s}}),r}});var Mt=m((ui,kt)=>{"use strict";var Ut=R();kt.exports=Ut.isStandardBrowserEnv()?function(){var e=/(msie|trident)/i.test(navigator.userAgent),r=document.createElement("a"),n;function s(o){var a=o;return e&&(r.setAttribute("href",a),a=r.href),r.setAttribute("href",a),{href:r.href,protocol:r.protocol?r.protocol.replace(/:$/,""):"",host:r.host,search:r.search?r.search.replace(/^\?/,""):"",hash:r.hash?r.hash.replace(/^#/,""):"",hostname:r.hostname,port:r.port,pathname:r.pathname.charAt(0)==="/"?r.pathname:"/"+r.pathname}}return n=s(window.location.href),function(a){var l=Ut.isString(a)?s(a):a;return l.protocol===n.protocol&&l.host===n.host}}():function(){return function(){return!0}}()});var V=m((ci,jt)=>{"use strict";function ke(t){this.message=t}ke.prototype.toString=function(){return"Cancel"+(this.message?": "+this.message:"")};ke.prototype.__CANCEL__=!0;jt.exports=ke});var Ht=m((li,$t)=>{"use strict";var Ce=R(),Nn=Ie(),In=Tt(),Dn=de(),Un=De(),kn=Dt(),Mn=Mt(),Me=me(),jn=J(),$n=V();$t.exports=function(e){return new Promise(function(n,s){var o=e.data,a=e.headers,l=e.responseType,c;function f(){e.cancelToken&&e.cancelToken.unsubscribe(c),e.signal&&e.signal.removeEventListener("abort",c)}Ce.isFormData(o)&&delete a["Content-Type"];var i=new XMLHttpRequest;if(e.auth){var u=e.auth.username||"",h=e.auth.password?unescape(encodeURIComponent(e.auth.password)):"";a.Authorization="Basic "+btoa(u+":"+h)}var x=Un(e.baseURL,e.url);i.open(e.method.toUpperCase(),Dn(x,e.params,e.paramsSerializer),!0),i.timeout=e.timeout;function U(){if(!!i){var p="getAllResponseHeaders"in i?kn(i.getAllResponseHeaders()):null,C=!l||l==="text"||l==="json"?i.responseText:i.response,_={data:C,status:i.status,statusText:i.statusText,headers:p,config:e,request:i};Nn(function(P){n(P),f()},function(P){s(P),f()},_),i=null}}if("onloadend"in i?i.onloadend=U:i.onreadystatechange=function(){!i||i.readyState!==4||i.status===0&&!(i.responseURL&&i.responseURL.indexOf("file:")===0)||setTimeout(U)},i.onabort=function(){!i||(s(Me("Request aborted",e,"ECONNABORTED",i)),i=null)},i.onerror=function(){s(Me("Network Error",e,null,i)),i=null},i.ontimeout=function(){var C=e.timeout?"timeout of "+e.timeout+"ms exceeded":"timeout exceeded",_=e.transitional||jn.transitional;e.timeoutErrorMessage&&(C=e.timeoutErrorMessage),s(Me(C,e,_.clarifyTimeoutError?"ETIMEDOUT":"ECONNABORTED",i)),i=null},Ce.isStandardBrowserEnv()){var w=(e.withCredentials||Mn(x))&&e.xsrfCookieName?In.read(e.xsrfCookieName):void 0;w&&(a[e.xsrfHeaderName]=w)}"setRequestHeader"in i&&Ce.forEach(a,function(C,_){typeof o=="undefined"&&_.toLowerCase()==="content-type"?delete a[_]:i.setRequestHeader(_,C)}),Ce.isUndefined(e.withCredentials)||(i.withCredentials=!!e.withCredentials),l&&l!=="json"&&(i.responseType=e.responseType),typeof e.onDownloadProgress=="function"&&i.addEventListener("progress",e.onDownloadProgress),typeof e.onUploadProgress=="function"&&i.upload&&i.upload.addEventListener("progress",e.onUploadProgress),(e.cancelToken||e.signal)&&(c=function(p){!i||(s(!p||p&&p.type?new $n("canceled"):p),i.abort(),i=null)},e.cancelToken&&e.cancelToken.subscribe(c),e.signal&&(e.signal.aborted?c():e.signal.addEventListener("abort",c))),o||(o=null),i.send(o)})}});var Vt=m((fi,zt)=>{var W=1e3,G=W*60,Y=G*60,j=Y*24,Hn=j*7,zn=j*365.25;zt.exports=function(t,e){e=e||{};var r=typeof t;if(r==="string"&&t.length>0)return Vn(t);if(r==="number"&&isFinite(t))return e.long?Wn(t):Jn(t);throw new Error("val is not a non-empty string or a valid number. val="+JSON.stringify(t))};function Vn(t){if(t=String(t),!(t.length>100)){var e=/^(-?(?:\d+)?\.?\d+) *(milliseconds?|msecs?|ms|seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|weeks?|w|years?|yrs?|y)?$/i.exec(t);if(!!e){var r=parseFloat(e[1]),n=(e[2]||"ms").toLowerCase();switch(n){case"years":case"year":case"yrs":case"yr":case"y":return r*zn;case"weeks":case"week":case"w":return r*Hn;case"days":case"day":case"d":return r*j;case"hours":case"hour":case"hrs":case"hr":case"h":return r*Y;case"minutes":case"minute":case"mins":case"min":case"m":return r*G;case"seconds":case"second":case"secs":case"sec":case"s":return r*W;case"milliseconds":case"millisecond":case"msecs":case"msec":case"ms":return r;default:return}}}}function Jn(t){var e=Math.abs(t);return e>=j?Math.round(t/j)+"d":e>=Y?Math.round(t/Y)+"h":e>=G?Math.round(t/G)+"m":e>=W?Math.round(t/W)+"s":t+"ms"}function Wn(t){var e=Math.abs(t);return e>=j?ye(t,e,j,"day"):e>=Y?ye(t,e,Y,"hour"):e>=G?ye(t,e,G,"minute"):e>=W?ye(t,e,W,"second"):t+" ms"}function ye(t,e,r,n){var s=e>=r*1.5;return Math.round(t/r)+" "+n+(s?"s":"")}});var je=m((di,Jt)=>{function Gn(t){r.debug=r,r.default=r,r.coerce=c,r.disable=o,r.enable=s,r.enabled=a,r.humanize=Vt(),r.destroy=f,Object.keys(t).forEach(i=>{r[i]=t[i]}),r.names=[],r.skips=[],r.formatters={};function e(i){let u=0;for(let h=0;h<i.length;h++)u=(u<<5)-u+i.charCodeAt(h),u|=0;return r.colors[Math.abs(u)%r.colors.length]}r.selectColor=e;function r(i){let u,h=null,x,U;function w(...p){if(!w.enabled)return;let C=w,_=Number(new Date),Z=_-(u||_);C.diff=Z,C.prev=u,C.curr=_,u=_,p[0]=r.coerce(p[0]),typeof p[0]!="string"&&p.unshift("%O");let P=0;p[0]=p[0].replace(/%([a-zA-Z%])/g,(Q,T)=>{if(Q==="%%")return"%";P++;let B=r.formatters[T];if(typeof B=="function"){let oe=p[P];Q=B.call(C,oe),p.splice(P,1),P--}return Q}),r.formatArgs.call(C,p),(C.log||r.log).apply(C,p)}return w.namespace=i,w.useColors=r.useColors(),w.color=r.selectColor(i),w.extend=n,w.destroy=r.destroy,Object.defineProperty(w,"enabled",{enumerable:!0,configurable:!1,get:()=>h!==null?h:(x!==r.namespaces&&(x=r.namespaces,U=r.enabled(i)),U),set:p=>{h=p}}),typeof r.init=="function"&&r.init(w),w}function n(i,u){let h=r(this.namespace+(typeof u=="undefined"?":":u)+i);return h.log=this.log,h}function s(i){r.save(i),r.namespaces=i,r.names=[],r.skips=[];let u,h=(typeof i=="string"?i:"").split(/[\s,]+/),x=h.length;for(u=0;u<x;u++)!h[u]||(i=h[u].replace(/\*/g,".*?"),i[0]==="-"?r.skips.push(new RegExp("^"+i.substr(1)+"$")):r.names.push(new RegExp("^"+i+"$")))}function o(){let i=[...r.names.map(l),...r.skips.map(l).map(u=>"-"+u)].join(",");return r.enable(""),i}function a(i){if(i[i.length-1]==="*")return!0;let u,h;for(u=0,h=r.skips.length;u<h;u++)if(r.skips[u].test(i))return!1;for(u=0,h=r.names.length;u<h;u++)if(r.names[u].test(i))return!0;return!1}function l(i){return i.toString().substring(2,i.toString().length-2).replace(/\.\*\?$/,"*")}function c(i){return i instanceof Error?i.stack||i.message:i}function f(){console.warn("Instance method `debug.destroy()` is deprecated and no longer does anything. It will be removed in the next major version of `debug`.")}return r.enable(r.load()),r}Jt.exports=Gn});var Wt=m((S,ge)=>{S.formatArgs=Xn;S.save=Kn;S.load=Zn;S.useColors=Yn;S.storage=Qn();S.destroy=(()=>{let t=!1;return()=>{t||(t=!0,console.warn("Instance method `debug.destroy()` is deprecated and no longer does anything. It will be removed in the next major version of `debug`."))}})();S.colors=["#0000CC","#0000FF","#0033CC","#0033FF","#0066CC","#0066FF","#0099CC","#0099FF","#00CC00","#00CC33","#00CC66","#00CC99","#00CCCC","#00CCFF","#3300CC","#3300FF","#3333CC","#3333FF","#3366CC","#3366FF","#3399CC","#3399FF","#33CC00","#33CC33","#33CC66","#33CC99","#33CCCC","#33CCFF","#6600CC","#6600FF","#6633CC","#6633FF","#66CC00","#66CC33","#9900CC","#9900FF","#9933CC","#9933FF","#99CC00","#99CC33","#CC0000","#CC0033","#CC0066","#CC0099","#CC00CC","#CC00FF","#CC3300","#CC3333","#CC3366","#CC3399","#CC33CC","#CC33FF","#CC6600","#CC6633","#CC9900","#CC9933","#CCCC00","#CCCC33","#FF0000","#FF0033","#FF0066","#FF0099","#FF00CC","#FF00FF","#FF3300","#FF3333","#FF3366","#FF3399","#FF33CC","#FF33FF","#FF6600","#FF6633","#FF9900","#FF9933","#FFCC00","#FFCC33"];function Yn(){return typeof window!="undefined"&&window.process&&(window.process.type==="renderer"||window.process.__nwjs)?!0:typeof navigator!="undefined"&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/(edge|trident)\/(\d+)/)?!1:typeof document!="undefined"&&document.documentElement&&document.documentElement.style&&document.documentElement.style.WebkitAppearance||typeof window!="undefined"&&window.console&&(window.console.firebug||window.console.exception&&window.console.table)||typeof navigator!="undefined"&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/firefox\/(\d+)/)&&parseInt(RegExp.$1,10)>=31||typeof navigator!="undefined"&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/applewebkit\/(\d+)/)}function Xn(t){if(t[0]=(this.useColors?"%c":"")+this.namespace+(this.useColors?" %c":" ")+t[0]+(this.useColors?"%c ":" ")+"+"+ge.exports.humanize(this.diff),!this.useColors)return;let e="color: "+this.color;t.splice(1,0,e,"color: inherit");let r=0,n=0;t[0].replace(/%[a-zA-Z%]/g,s=>{s!=="%%"&&(r++,s==="%c"&&(n=r))}),t.splice(n,0,e)}S.log=console.debug||console.log||(()=>{});function Kn(t){try{t?S.storage.setItem("debug",t):S.storage.removeItem("debug")}catch{}}function Zn(){let t;try{t=S.storage.getItem("debug")}catch{}return!t&&typeof process!="undefined"&&"env"in process&&(t=process.env.DEBUG),t}function Qn(){try{return localStorage}catch{}}ge.exports=je()(S);var{formatters:es}=ge.exports;es.j=function(t){try{return JSON.stringify(t)}catch(e){return"[UnexpectedJSONParseError]: "+e.message}}});var Yt=m((hi,Gt)=>{"use strict";Gt.exports=(t,e=process.argv)=>{let r=t.startsWith("-")?"":t.length===1?"-":"--",n=e.indexOf(r+t),s=e.indexOf("--");return n!==-1&&(s===-1||n<s)}});var Zt=m((pi,Kt)=>{"use strict";var ts=require("os"),Xt=require("tty"),O=Yt(),{env:y}=process,D;O("no-color")||O("no-colors")||O("color=false")||O("color=never")?D=0:(O("color")||O("colors")||O("color=true")||O("color=always"))&&(D=1);"FORCE_COLOR"in y&&(y.FORCE_COLOR==="true"?D=1:y.FORCE_COLOR==="false"?D=0:D=y.FORCE_COLOR.length===0?1:Math.min(parseInt(y.FORCE_COLOR,10),3));function $e(t){return t===0?!1:{level:t,hasBasic:!0,has256:t>=2,has16m:t>=3}}function He(t,e){if(D===0)return 0;if(O("color=16m")||O("color=full")||O("color=truecolor"))return 3;if(O("color=256"))return 2;if(t&&!e&&D===void 0)return 0;let r=D||0;if(y.TERM==="dumb")return r;if(process.platform==="win32"){let n=ts.release().split(".");return Number(n[0])>=10&&Number(n[2])>=10586?Number(n[2])>=14931?3:2:1}if("CI"in y)return["TRAVIS","CIRCLECI","APPVEYOR","GITLAB_CI","GITHUB_ACTIONS","BUILDKITE"].some(n=>n in y)||y.CI_NAME==="codeship"?1:r;if("TEAMCITY_VERSION"in y)return/^(9\.(0*[1-9]\d*)\.|\d{2,}\.)/.test(y.TEAMCITY_VERSION)?1:0;if(y.COLORTERM==="truecolor")return 3;if("TERM_PROGRAM"in y){let n=parseInt((y.TERM_PROGRAM_VERSION||"").split(".")[0],10);switch(y.TERM_PROGRAM){case"iTerm.app":return n>=3?3:2;case"Apple_Terminal":return 2}}return/-256(color)?$/i.test(y.TERM)?2:/^screen|^xterm|^vt100|^vt220|^rxvt|color|ansi|cygwin|linux/i.test(y.TERM)||"COLORTERM"in y?1:r}function rs(t){let e=He(t,t&&t.isTTY);return $e(e)}Kt.exports={supportsColor:rs,stdout:$e(He(!0,Xt.isatty(1))),stderr:$e(He(!0,Xt.isatty(2)))}});var er=m((g,we)=>{var ns=require("tty"),be=require("util");g.init=ls;g.log=as;g.formatArgs=is;g.save=us;g.load=cs;g.useColors=ss;g.destroy=be.deprecate(()=>{},"Instance method `debug.destroy()` is deprecated and no longer does anything. It will be removed in the next major version of `debug`.");g.colors=[6,2,3,4,5,1];try{let t=Zt();t&&(t.stderr||t).level>=2&&(g.colors=[20,21,26,27,32,33,38,39,40,41,42,43,44,45,56,57,62,63,68,69,74,75,76,77,78,79,80,81,92,93,98,99,112,113,128,129,134,135,148,149,160,161,162,163,164,165,166,167,168,169,170,171,172,173,178,179,184,185,196,197,198,199,200,201,202,203,204,205,206,207,208,209,214,215,220,221])}catch{}g.inspectOpts=Object.keys(process.env).filter(t=>/^debug_/i.test(t)).reduce((t,e)=>{let r=e.substring(6).toLowerCase().replace(/_([a-z])/g,(s,o)=>o.toUpperCase()),n=process.env[e];return/^(yes|on|true|enabled)$/i.test(n)?n=!0:/^(no|off|false|disabled)$/i.test(n)?n=!1:n==="null"?n=null:n=Number(n),t[r]=n,t},{});function ss(){return"colors"in g.inspectOpts?Boolean(g.inspectOpts.colors):ns.isatty(process.stderr.fd)}function is(t){let{namespace:e,useColors:r}=this;if(r){let n=this.color,s="[3"+(n<8?n:"8;5;"+n),o=`  ${s};1m${e} [0m`;t[0]=o+t[0].split(`
3: `).join(`
4: `+o),t.push(s+"m+"+we.exports.humanize(this.diff)+"[0m")}else t[0]=os()+e+" "+t[0]}function os(){return g.inspectOpts.hideDate?"":new Date().toISOString()+" "}function as(...t){return process.stderr.write(be.format(...t)+`
---

At.exports:index.js:1:5240
IncomingMessage.<anonymous>:index.js:6:10928
IncomingMessage.emit:node:events:525:35

**Comment by Yukaii** [comment]
It seems that Debank has blocked their old version of the API.
