### ISSUE TITLE
[Hue] Add option to toggle all the lights (on/off)

### ISSUE THREAD

**Issue by PiotrekPKP** [raycast/extensions#6257]
### Extension

https://www.raycast.com/pindab0ter/hue

### Description

I love your extension! There is only one thing that bothers me and it's a missing feature - currently you can only turn off all the lights. It would be nice to have a function that would toggle on/off all the lights.

I think it would be easy to do, just something like `light => // set state to !light.on.on` would be required.

### Who will benefit from this feature?

All Philips Hue lights users.

**Comment by pindab0ter** [comment]
That sounds like a great improvement!

With Hue, if there are any lights on in a group, it will turn them all off first. Then if all lights are off, it will turn them all on.

I can just rename the Turn Off All Lights command to Toggle All Lights. No functionality will be lost.

**Comment by PiotrekPKP** [comment]
> That sounds like a great improvement!
> 
> With Hue, if there are any lights on in a group, it will turn them all off first. Then if all lights are off, it will turn them all on.
> 
> I can just rename the Turn Off All Lights command to Toggle All Lights. No functionality will be lost.

That would be perfect!

**Comment by pindab0ter** [comment]
I wrote the feature in the new update branch (#6006). I'll test it when I get home in a few weeks.

**Comment by pindab0ter** [comment]
#6006 is now up for review.

**Comment by pindab0ter** [comment]
This was implemented in #6006.

**Comment by PiotrekPKP** [comment]
Thanks A LOT 🙏

**Comment by pindab0ter** [comment]
@raycastbot close this issue
