### ISSUE TITLE
[WhoSampled] Check if spotify is installed + Ability to pass spotify URL

### ISSUE THREAD

**Issue by Aayush9029** [raycast/extensions#6259]
### Extension

https://www.raycast.com/andrewtruex/whosampled

### Description

If Spotify is not running in the background, the application will crash entirely.

<img width="1000" alt="whosampled 2023-05-01 at 02 28 29" src="https://user-images.githubusercontent.com/43297314/235416828-4b490ce8-6d5a-4619-83b2-07cfe5c10ca7.png">

### Steps To Reproduce

On fresh installation.

1. Install extension
2. Run

### Current Behaviour

Extension Crashes

### Expected Behaviour

An error or suggestion to install / open spotify.
Ability to paste spotify URL instead.

**Comment by pernielsentikaer** [comment]
I can't reproduce this, I just see this 
<img width="278" alt="Raycast-dhVw8Pzr@2x" src="https://user-images.githubusercontent.com/38033107/235421808-1ce24e0f-52c1-43fe-a170-3ce17b3b4c9c.png">

Could you fork it and see if you can spot what's wrong @Aayush9029
