### ISSUE TITLE
[Taskplane] This service no longer exists

### ISSUE THREAD

**Issue by rvanbaalen** [raycast/extensions#6264]
### Extension

https://www.raycast.com/albingroen/taskplane

### Description

See their blog post:

https://abgn.me/blog/goodbye-taskplane

### Steps To Reproduce

1. Read the blog post
2. Conclude Taskplane no longer exists
3. ...
4. Done

**Comment by rvanbaalen** [comment]
This issue is still active. How to report broken/stale plugins?

**Comment by peduarte** [comment]
Hey, thanks for creating this issue.

So Taskplane no longer exists, meaning the extension no longer works. Right? 

There are a couple of options
- You can uninstall the extension
- The author can reach our if they want it to be deleted from the store
- I'll reach out to the author and see if we can update it with a note for users

Did you have something else in mind?

**Comment by rvanbaalen** [comment]
Hi Pedro

It was more of a heads up to you guys. I came across this addon as a Raycast user, tried it and was bummed that this wasn't working anymore. 

Obviously uninstalled. Created this issue as a note to the Raycast team. Might want to contact the maintainer and/or remove it from the store. 

Deal with it as you see fit ✌️ the goal of this issue was to notify you/the team of this "bug" and as such, it can be closed now. 

@raycastbot close this issue

**Comment by peduarte** [comment]
@rvanbaalen Awesome, thanks!
