### ISSUE TITLE
[Jira] open issues fails to load

### ISSUE THREAD

**Issue by jordwil** [raycast/extensions#6266]
### Extension

https://www.raycast.com/raycast/jira

### Description
Jira] open issues fails to load after updating to Raycast V. 1.50.0 

#### Error:
```
Error: Rendering failed:
Missing required component property "title"
```

### Steps To Reproduce

1. Raycast Version 1.50.0 
2. Open `Open Issues`

### Current Behaviour

`Something Went Wrong Message`

### Expected Behaviour

Lists open jira issues.

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue #6011, so I'll mark it as such.
