### ISSUE TITLE
Harvest: Can't access all projects

### ISSUE THREAD

**Issue by Vainyards** [raycast/extensions#627]
## Extension - [Harvest](https://github.com/raycast/extensions/tree/374cddf4b660c71e872d7754372788fa72164afb/extensions/harvest)
**Author**: @eluce2 

I installed the new raycast Harvest plugin. 
But I do not understand why im not seeing all projects? 

Is this some setting on the project or more of my harvest account?! 

On some customers I only see "non-billable" projects for example? 
Is this a restriction of the API of some sort?!

**Comment by mattisssa** [comment]
Hey Eric @eluce2, it seems like someone has a few questions about your extension 😉

p.s. @Vainyards please follow the issue templates next time while creating an issue, it makes us easier to review them and reach out to the author of the extension in the report/.

**Comment by eluce2** [comment]
@Vainyards How many projects do you have? Do you think it's more than 100 that would be visible to you when creating a new time entry?

There are no limits that I've imposed for this list on my side, so I'm wondering if you're running into the pagination limit on the API.

**Comment by Vainyards** [comment]
@mattisssa Thanks for update! Im new about posting issues at github! Will do better next time! 

@eluce2 yes there could very well be 100 projects within my company up and running at any given time. Since most of our customers have several each. 

I dont know, since Im seeing some projects and not others. Just asking to see if there maybe is something in this exension, but it could very well be limitation in the API. Is there some way of getting around this?!
