### ISSUE TITLE
[Browser Bookmarks] No option to configure the extension when user only has one browser

### ISSUE THREAD

**Issue by ozgurirmak** [raycast/extensions#6271]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

There is option to configure the extension - `Select Browsers` does not appear
![072DC6A0-8052-45BA-96E9-75C87003FCCC](https://user-images.githubusercontent.com/58088054/235603756-b50b84af-dd50-4dec-960f-25455592bc00.png)

### Steps To Reproduce

1. run command
2. no option to `Select Browsers`

**Comment by thomaslombart** [comment]
Which browsers are you using on your Mac and which one is the default one?

**Comment by thomaslombart** [comment]
Thanks for the additional details. I'll look into that.
