### ISSUE TITLE
[Google Chrome] - Please make this work on other chromium browsers

### ISSUE THREAD

**Issue by thtliife** [raycast/extensions#6285]
### Extension

https://github.com/raycast/extensions/tree/main/extensions/google-chrome

### Description

I use Chromium rather than Chrome, because I'm not a fan of all the added advertising in the Chrome edition.
It would be fantastic if this extension could be made to work on the Chromium browser, and potentially other Chromium based browsers.

I imagine this would be something along the lines of adding configuration to allow setting things like:

* the AppName (replacing `Google Chrome` with `Chromium` or `Brave`
* defaultChromeProfilePath (replacing `["Application Support", "Google", "Chrome"];` with something like: `getPreferenceValues<Preferences>().defaultChromeProfilePath.split('/');`
* defaultChromeStatePath (replacing `["Application Support", "Google", "Chrome", "Local State"];` with something like: `getPreferenceValues<Preferences>().defaultChromeStatePath('/');`

### Who will benefit from this feature?

Users of chromium based browsers other than Google Chrome.

**Comment by thtliife** [comment]
no hopes of this then?

**Comment by aldopareja** [comment]
please!

**Comment by tifandotme** [comment]
ungoogled chromium please
