### ISSUE TITLE
[Capture Fullpage of Website] ...

### ISSUE THREAD

**Issue by liuyunfan1997** [raycast/extensions#6287]
### Extension

https://www.raycast.com/Coun1er/capture-fullpage-of-website

### Description

![image](https://user-images.githubusercontent.com/131890770/235837578-3930cb09-f838-47a6-be5d-07fb071557fa.png)
I pasted the URL into the input box and executed the command, it reported an error to me.

### Steps To Reproduce

I pasted the URL into the input box and executed the command, it reported an error to me.

**Comment by madza91** [comment]
@pernielsentikaer @Coun1er It can be easily reproduced by installing it from the store, but when is forked and installed as development env, it works. It looks like the issue is because `@playwright/test` package is in dev dependencies.

**Comment by pernielsentikaer** [comment]
I just tried to install it from the store and didn't have any issues at all, do you have Chrome installed?
