### ISSUE TITLE
[ChatGPT] ...

### ISSUE THREAD

**Issue by stefankc** [raycast/extensions#6288]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Selected Text couldn't load.

### Steps To Reproduce

1. Just installed
2. Enable auto-load selected text
3. And tried in browse, notion etc.

### Current Behaviour

Selected Text couldn't load.
![image](https://user-images.githubusercontent.com/94632796/235844128-f73d430c-72fe-4308-9e49-59202a6f2bb8.png)

### Expected Behaviour

Selected Text in prompt

**Comment by abielzulio** [comment]
Are you still facing this issue on a daily basis? @stefankc
