### ISSUE TITLE
[Github] Support "queued" PR status

### ISSUE THREAD

**Issue by AntonNiklasson** [raycast/extensions#6289]
### Extension

https://www.raycast.com/raycast/github

### Description

We're using [Githubs new merge queue feature](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue). It would be nice to have the "queued" status be reported in the list of pull request. Currently it just shows all checks passed on the PR with a green check.

Here's the info you get currently:

<img width="159" alt="Screenshot 2023-05-03 at 10 54 13" src="https://user-images.githubusercontent.com/785676/235872468-46891d07-80cb-4ff6-9b09-156099f29f60.png">

### Who will benefit from this feature?

Everyone using the extension, that are also using merge queues on github.

**Comment by thomaslombart** [comment]
Thanks for the feature request. It sounds like a nice addition. Would you like to work on it? I can provide you some guidance on how to contribute to this extension so that you can open a pull request.

**Comment by AntonNiklasson** [comment]
Sure, I'll give it a go!

**Comment by thomaslombart** [comment]
Awesome! Here's the feature outline from what I've seen:

1. Update the `PullRequestFields` fragment in `api/pullRequest.graphql` to include the `mergeQueueEntry` property (cf screenshot) 
2. Update `PullRequestListItem.tsx` to read that property and add a new accessory to the list item if it's defined
3. Add a new entry in `CHANGELOG.md` 
4. Open the PR 🚀

<img width="340" alt="CleanShot 2023-05-09 at 15 42 14@2x" src="https://github.com/raycast/extensions/assets/16003285/73503006-c8bf-49dc-9386-56f8fbba22ca">
