### ISSUE TITLE
[Notion Extension Bug] 

### ISSUE THREAD

**Issue by Ua01** [raycast/extensions#629]
# Extension – [Notion](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/notion/)

Author: @HenriChabrand 

## Description
The "create database" feature isn't working as intended, while the search function is. It keeps reporting an error

<img width="862" alt="Screen Shot 2022-01-07 at 10 15 23 PM" src="https://user-images.githubusercontent.com/25459320/148595289-5d6d6120-9824-4409-9be8-8476da9c1da8.png">

This
[Raycast Error code.txt](https://github.com/raycast/extensions/files/7830871/Raycast.Error.code.txt)
 👆

## Steps To Reproduce

1. Setup the extension by following the provided extension instructions
2. Attempt to use the "Create Database Page" Command

## The current behavior

It shows the attached error

## The expected behavior

It should open a menu to create a database pg in notion, as advertised

### Raycast version
Version: latest - 1.26.3

**Comment by HenriChabrand** [comment]
Hello @Ua01 👋 
This issue has been identified and the fix is currently pending for review 🙌 
https://github.com/raycast/extensions/pull/617

**Comment by HenriChabrand** [comment]
Thank you for reporting this issue 💪

**Comment by Ua01** [comment]
That's great, looking forward to word on a fix ☺️

**Comment by HenriChabrand** [comment]
It should have been fix – could you confirm? @Ua01

**Comment by Ua01** [comment]
> It should have been fix – could you confirm? @Ua01

There's no change on my end, it's still showing the same error unfortunately.

**Comment by HenriChabrand** [comment]
Hello @Ua01 
Could you send over the error again? 
Because in the detail of the error normally something has changed

**Comment by Ua01** [comment]
[Raycast error code 2.txt](https://github.com/raycast/extensions/files/7860246/Raycast.error.code.2.txt)

Hi @HenriChabrand 
No worries, here is the new error code. Hope it helps.

**Comment by Ua01** [comment]
Hi @HenriChabrand 

The issue seems to have been fixed, Thanks for all your help. ☺️
