### ISSUE TITLE
[Jira] ...

### ISSUE THREAD

**Issue by colinfitzp** [raycast/extensions#6290]
### Extension

https://www.raycast.com/raycast/jira

#### Error:
```
Error: Rendering failed:
Missing required component property "title"
```

### Steps To Reproduce

Go jira Open Issues
The error "something went wrong" appears on screen.

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue #6011, so I'll mark it as such.
