### ISSUE TITLE
[UUID Generator] Option to paste/copy can't be found in the settings

### ISSUE THREAD

**Issue by neominik** [raycast/extensions#6294]
### Extension

https://www.raycast.com/jmaeso/uuid-generator

### Description

Since the uuid generator has been updated yesterday, instead of copying uuids, it will only paste them. Looking through the settings, there is only a toggle for uppercase and a namespace for v5 uuids, but no dropdown to choose copy/paste, so it will always "paste" them (it doesn't actually paste into any application that I tried, but that is a separate issue).

### Steps To Reproduce

1. install extension
2. go to extension settings
3. click on anything related to uuids, not find the setting

**Comment by LunaticMuch** [comment]
I will look at it shorly!

**Comment by pernielsentikaer** [comment]
I added that in #5876, strange if your PR removed it
