### ISSUE TITLE
[Bitwarden Vault] ...

### ISSUE THREAD

**Issue by Tigeredgar** [raycast/extensions#6302]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Keeps logging me out right after logging in.

### Steps To Reproduce

Login with master password. 
Wait 2 seconds
Logs me out and prompts for master password again

**Comment by jomifepe** [comment]
Hello, thanks for reporting, I'm taking a look into the issue. In the meantime, please try to reinstall the extension.

**Comment by trm217** [comment]
Experiencing the same issue currently.

**Comment by jomifepe** [comment]
Can you confirm that the issue still persists are the last update?

**Comment by GumbyXGames** [comment]
Upgraded to Raycast v1.50.4 and issue persits.

**Comment by trm217** [comment]
Can confirm, issue persists.

**Comment by jomifepe** [comment]
Please verify if the issue still persists with the latest update

**Comment by trm217** [comment]
@jomifepe It's working for me now. Thank you for your effort 🙌🏻

**Comment by jomifepe** [comment]
@Tigeredgar can you confirm that it's working correctly?

**Comment by GumbyXGames** [comment]
Bitwarden extension seems to be working fine after installing the update. Thanks for the quick fix!

**Comment by jomifepe** [comment]
I will assume that this issue is resolved, given that two people already confirmed that it's working. 

If not, be sure to comment, thanks 🙂

@raycastbot close this issue
