### ISSUE TITLE
[Tana] Clarify in docs from where you should call "Get API token"

### ISSUE THREAD

**Issue by lainisourgod** [raycast/extensions#6307]
### Extension

https://www.raycast.com/cheslip/tana

### Description

hi! first, thanks for the extension, I really needed it!

I spent 15 minutes debugging the strange behaviour I was getting that "Quick Add" added my notes under some random node in Tana. Only understood what happened, when I deleted this node, and "Quick Add" failed to work at all.

I think we could it make it clearer in README that node

Current version:
"""
The note that you write will be added to a node that you configure.

... To generate this token, open the command line (Cmd/Ctrl-K) and select Get API Token. ...
"""

I propose:
"""
All the notes you write will be added **under a node that you configure**. The good place is Inbox. You can find it in Sidebar on the top." ( with formatting ). 

... To generate this token, focus on the node you want to store content in (e.g. create a "Raycast Capture" node in your Inbox), open the command line (Cmd/Ctrl-K) and select Get API Token. ...
'""

<img width="866" alt="CleanShot 2023-05-03 at 23 38 34@2x" src="https://user-images.githubusercontent.com/24773652/236027438-98b4f68e-9ba4-429c-a5b7-1abeb2900705.png">

**Comment by pentekostos** [comment]
I was bitten by this as well. If you haven't selected a node, the "Get API Token" command doesn't show up in the palette, so I assumed the behavior changed and I needed to generate a token from the settings menu. When I tried using that I got 400 responses. Not until I read your post did I realize that I needed to select a node first and run the Get API Token command.
