### ISSUE TITLE
[ChatGPT Quick Actions] ...

### ISSUE THREAD

**Issue by Arneshpal** [raycast/extensions#6308]
### Extension

https://www.raycast.com/alanzchen/chatgpt-quick-actions

#### Error:
```
⚠️ Raycast was unable to get the selected text. You may try copying the text to a text editor and try again.
```

### Steps To Reproduce

Just open the extension and do anything same result comes

### Current Behaviour

The extension is not usable at all right now.

**Comment by alanzchen** [comment]
Hi @Arneshpal,

This is a known bug for Raycast, see #6129 and #4352

Sometimes Raycast is just not able to grab the selected text on your screen for some reason (typically in complicated scenarios, such as in MS Word). As the message suggested, you may want to try to copy the text over to a plain text editor and try again.

Sorry that there is nothing I can do from my end. Thanks for using the extension.
