### ISSUE TITLE
[Extension Feature Request] A new vercel raycast extension 

### ISSUE THREAD

**Issue by MaxLeiter** [raycast/extensions#631]
# Extension – [Vercast](https://github.com/raycast/extensions/tree/main/extensions/vercast)
Author: Unknown (@gleich?)

I've been working on a new Vercel extension modified from Vercast. It provides a single `vc` command for completing multiple tasks, which differs from Vercast's `Search Vercel Deployments` command. I was wondering if I should request to merge my extension as a new one, or should I replace vercast? The source code (with some screenshots) is available here: https://github.com/MaxLeiter/vercel-raycast

The new features include adding and editing environment variables, searching projects by team, and searching deployments by project.

**Comment by gleich** [comment]
Hey Max! Awesome extension. From what I've experienced in the past they seem to prefer having people help maintain existing extensions than adding duplicate ones. They will probably get back to you on Monday about what they would like you to do.

On a more personal note, I would love to merge the extensions. I am very active on GitHub and can just add you as a collaborator to the vercast project.  Lemme know if you might even wanna do a quick call to discuss it.

**Comment by PitNikola** [comment]
Hey folks! We have a [paragraph about this topic in our guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store#contributing-to-existing-extensions-vs-creating-a-new-one). It's not always straightforward what's the best solution. From user point of view, it's better when there are fewer extensions doing similar thing on the store. However if functionality differs significantly, it's okay to have duplicates.

In this case, if Max's extension is a spin-off from Vercast and @gleich would be happy to merge those, it would probably be more reasonable way to move forward. We recently added support for collaborators to bring visibility to folks who contribute to existing extensions.

Let me know if you have any questions.

**Comment by MaxLeiter** [comment]
I'm happy to merge the extensions and to hop on a call, @gleich. Send me an email at maxwell.leiter@gmail.com and we can figure it out. 
 
Thanks for the input, @PitNikola
