### ISSUE TITLE
[Airtable] Add new row to base

### ISSUE THREAD

**Issue by LukaHarambasic** [raycast/extensions#6311]
### Extension

https://www.raycast.com/marks/raycast-airtable-extension

### Description

I would love to be able to create new tables from Raycast to a table. I, therefore, imagine two ways:
1. You can define a default base & table, e.g., Bookmarks or Notes. If you then call the action, an input based on the fields in the table will be presented. If it's impossible to do this automatically, it would be nice to map the inputted text to a field manually.
2. Besides the default base, this feature should be available for every base & table as an option in the existing flow. Creating a new row could be the default behavior when pressing enter or life in the Action menu.

What do you think @pernielsentikaer?

Mange tak,
Luka

**Comment by marks** [comment]
Hi @LukaHarambasic - I agree this is a great idea, but I wanted to chime in to say I don't think I'll be able to take it on in the foreseeable future, so please go ahead and submit a PR if you get a chance. I'd be happy to help test/review it.

**Comment by LukaHarambasic** [comment]
Fair point! I solved my use case with a custom script. Therefore I'll close this issue, maybe I'll implement it one day :)
