### ISSUE TITLE
[Browser Bookmarks] Safari bookmarks do not show root folders

### ISSUE THREAD

**Issue by chuxubank** [raycast/extensions#6313]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

The new Browser Bookmarks plugin do not show bookmark folders and bookmarks inside a folder from Safari, the previous one (which is deprecated now) works well.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/17001575/236106559-ee1c968a-e206-4ada-91e5-8baac701f203.png">

Here are my bookmarks folders
<img width="317" alt="image" src="https://user-images.githubusercontent.com/17001575/236106545-d9c19dac-e12c-4993-9c88-d2afa5b91494.png">

### Steps To Reproduce

1. Open raycast://extensions/raycast/browser-bookmarks/index
2. Press Cmd+P
3. No folders show up

### Current Behaviour

Only `Favourites` and `Reading List`

### Expected Behaviour

All the folders show up like 
```
Org
Work
Blog
Book
Design
Tools
Music
Software
Life
Language
Study
OJ
Game
Develop
```

**Comment by thomaslombart** [comment]
It seems root folders are not supported in the extension! I'll take a look at it in the next few days or weeks.
