### ISSUE TITLE
[下罗普] ...

### ISSUE THREAD

**Issue by owenjuni** [raycast/extensions#6315]
### Extension

https://www.raycast.com/jag-k/dropover

### Description

Unable to operate on pdf and ePub files

### Steps To Reproduce

Select pdf, epub file, shortcut key operations such as option + command + a, prompt failed add files to Dropover!

**Comment by jag-k** [comment]
@owenjuni are these files you select in Finder? Cause' this extension use `getSelectedFinderItems` Raycast API.

**Comment by owenjuni** [comment]
Yes, I'll record a screen to show you.
![](https://owenjuni-cos-1256992750.cos.ap-guangzhou.myqcloud.com/uPic/7ejiNH.mp4)

**Comment by jag-k** [comment]
I think it happened 'cause you use Chinese characters in the filename. I'm fixed this here #6413, and after this PR will be released, you can try to add files to Dropover again.

**Comment by owenjuni** [comment]
Yes, I changed the name of the file to English so that I didn't make another mistake.
https://owenjuni-cos-1256992750.cos.ap-guangzhou.myqcloud.com/uPic/k1u7uj.mp4
