### ISSUE TITLE
[Visual Studio Code - Project Manager] the default open application be changed

### ISSUE THREAD

**Issue by KurumiRin** [raycast/extensions#6318]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

I am using the VS Code Insiders version. Can I change the default open application?

**Comment by theherk** [comment]
You can. If you go to the extension's configuration, you can select from:

- Visual Studio Code
- Visual Studio Code - Insiders
- VSCodium
- VSCodium < 1.71

**Comment by theherk** [comment]
Bottom right in this image.
<img width="1112" alt="Screenshot 2023-05-04 at 10 58 06" src="https://user-images.githubusercontent.com/3605078/236158039-67a8c377-101c-4d51-9aaf-97a45060630f.png">

**Comment by KurumiRin** [comment]
> 

oh thanks, i see

**Comment by KurumiRin** [comment]
> Bottom right in this image. 这张图片的右下角。这张图片的右下角。  这张图片的右下角。  <img alt="Screenshot 2023-05-04 at 10 58 06" width="1112" src="https://user-images.githubusercontent.com/3605078/236158039-67a8c377-101c-4d51-9aaf-97a450

> Bottom right in this image. <img alt="Screenshot 2023-05-04 at 10 58 06" width="1112" src="https://user-images.githubusercontent.com/3605078/236158039-67a8c377-101c-4d51-9aaf-97a45060630f.png">

oh thanks, i see
