### ISSUE TITLE
DEVONthink

### ISSUE THREAD

**Issue by glfruit** [raycast/extensions#6325]
### Extension

https://www.raycast.com/bgnfu7re/devonthink

### Description

When I search something through this extension, I'd like to copy the item links of search results to clipboard. I've checked through the source code, I think maybe two more actions can be added to actionpanel in SearchResultItem.tsx:
 <Action.CopyToClipboard title="Copy Item Link" target={`x-devonthink-item://${result.uuid}`} />
 <Action.CopyToClipboard title="Copy Markdown Link" target={`[${result.name}]x-devonthink-item://${result.uuid})`} />

**Comment by kudrykv** [comment]
@glfruit check it out
