### ISSUE TITLE
`useCachedPromise` code example does not match its text description

### ISSUE THREAD

**Issue by kgrhartlage** [raycast/extensions#6330]
### Description

The example code for [Promise Argument dependent on List search text](https://developers.raycast.com/utilities/react-hooks/usecachedpromise#promise-argument-dependent-on-list-search-text) has no argument dependent on search text. The argument to the hook is a static string:

```js
const [searchText, setSearchText] = useState("");
const { isLoading, data } = useCachedPromise(
  async (url: string) => {
    // function body
  },
  ["https://api.example"]
);
```

<details>
<summary>screenshot</summary>

![CleanShot 2023-05-04 at 21 21 00@2x](https://user-images.githubusercontent.com/42832087/236307898-44e11f54-79ee-4c19-b816-f4f34e1e8000.png)

</details>

IIUC this should be an interpolated string, something like this:

```js
const [searchText, setSearchText] = useState("");
const { isLoading, data } = useCachedPromise(
  async (url: string) => {
    // function body
  },
  [`https://api.example?q=${searchText}`]
);
```

Not related, but IIUC either the returned data type or its handing in the list is also incorrect. The example uses the `text()` method of the `Response` interface, which returns a string:

```js
const result = await response.text();
``` 

The `List` then tries to iterate over that data of type `string`:

```js
(data || []).map((item) => (
  <List.Item key={item.id} title={item.title} />
))
```

<details>
<summary>screenshot</summary>

![CleanShot 2023-05-04 at 21 22 36@2x](https://user-images.githubusercontent.com/42832087/236308291-3cfc57ce-ca5c-4c58-9c22-3ab1d1e1f289.png)

</details>

**Comment by mathieudutour** [comment]
Good catch, fixed here: https://github.com/raycast/utils/commit/c156a7a0ff1196ea65f71deee5d9ef6ddfbe2e80

Feel free to send a PR if you think it can be improved further
