### ISSUE TITLE
[Spotify Beta] Quick Actions Data Needs to Be Revalidated

### ISSUE THREAD

**Issue by spikenilan** [raycast/extensions#6335]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

### Description

I have a keyboard shortcut to like a song. With the new Spotify Beta Raycast extension, this behavior is broken. It's using the cached song so it is basically always out of date. I believe it is also broken for the other Quick Actions although I have not tested it although I have notcied some funny behavior with Play/Pause. Also, the code is using `revalidate` from `useCachedPromise` which does not return a Promise. I believe it should be awaiting `mutate` instead

### Steps To Reproduce

1. Create a QuickLink for the Quick Action `Like`
2. Assign a keyboard shortcut to this QuickLink
3. Change the currently playing song through the actual spotify player
4. Execute the keyboard shortcut

### Current Behaviour

Likes an old song

### Expected Behaviour

Likes the currently playing song

**Comment by peduarte** [comment]
Thanks. Quick Actions has been removed in favour of Disabled Commands. https://github.com/raycast/extensions/pull/6204
