### ISSUE TITLE
[Timers] Ability to see the stopwatch in a small box or the menubar...

### ISSUE THREAD

**Issue by someinternetguy** [raycast/extensions#6339]
### Extension

https://www.raycast.com/ThatNerd/timers

### Description

It would be nice to be able to see my running stopwatch(es) under the timer dropdown in the menubar, or maybe in a little box somewhere on screen.

### Who will benefit from this feature?

everyone :)

**Comment by ThatNerdSquared** [comment]
Hey @someinternetguy, thanks for using Timers \:)

I'm currently working on a stopwatch menu bar command, similar to the one for timers! Haven't had much time to work on it lately as I've been quite busy, but hoping to have it released soon. Thanks for the suggestion.

**Comment by someinternetguy** [comment]
Thank you for the response and your hard work! looking forward to the feature whenever it may happen :)

**Comment by rjhewitt3** [comment]
@ThatNerdSquared Came to Github to report this same suggestion—can't wait to have my timers in the menubar. 👏🏻

**Comment by ThatNerdSquared** [comment]
Hey @rjhewitt3, just to clarify, this WIP feature is for the *stopwatches* menu bar. If you want to see the countdown timers in your menu bar, there's already a "Timers Menu Bar" command that can be used to enable that. If that doesn't work for some reason, feel free to open another issue as well!

**Comment by rjhewitt3** [comment]
@ThatNerdSquared Ah, forgot about that. I had it disabled because I didn't want it always visible. Opened another issue to request a modification/setting for it (#6963).
