### ISSUE TITLE
[Amazon AWS] extension fails to run any command

### ISSUE THREAD

**Issue by allen-n** [raycast/extensions#6340]
### Extension

https://www.raycast.com/Falcon/aws

#### Error:
```
Error: Command failed: /bin/zsh -l -c "assume -c default"
zsh:1: command not found: assume


zsh:1: command not found: assume
ChildProcess.exithandler:node:child_process:412:12
ChildProcess.emit:node:events:513:28
```

actions other than `run profile script` no longer work in any capacity. Meaning when I enter the command (for instance, search dynamodb tables) and type a table name, no search results are shown on any profile.

### Steps To Reproduce

1. Select the `run profile script` command
2. Select a profile
3. Error occurs

**Comment by allen-n** [comment]
Also confirmed that my aws cli is properly authed and working as intended, is there a way to reset the path to the creds? It looks like its reading them correctly since it's finding the right two profiles, it just can't actually display any results for any of the actions.

**Comment by frese** [comment]
The "run profile script" is a flexible command where you can setup a script to run for a certain profile. The provided default example using https://granted.dev "assume" command, requires you to install granted first and configure it correctly. 
In any case, it's up to you to make sure the script/command you provide for "run profile script" is working as intended.

**Comment by sbl3** [comment]
I've got the same issue -- it's more than just the "run profile script" that's failing.  All the AWS actions are not working. If I select "EC2 Instances" I get a blank screen and I've got a bunch of EC2 instances

![image](https://user-images.githubusercontent.com/50999519/236503847-03ccf912-2d89-4285-ab45-58b594a28c7b.png)

I've verified my cli permissions are working.  "aws ec2 describe-instances" works.

**Comment by allen-n** [comment]
Yes sorry I did a bad job explaining but @sbl3 explained it perfectly. Happy to record a loom to demo the behavior but *all* commands are silently failing in the way captured by his screenshot. This started maybe 2-3 days ago so I assume there was a breaking change in a recent release.

**Comment by allen-n** [comment]
Here is a loom demoing the issue:
[https://www.loom.com/share/af4880f3564441df9ad0af5a90a16af1](https://www.loom.com/share/af4880f3564441df9ad0af5a90a16af1)

**Comment by JonathanWbn** [comment]
I prepared the fix: https://github.com/raycast/extensions/pull/6358
