### ISSUE TITLE
[ClickUp - Tasks Explorer] Quick direct access to list

### ISSUE THREAD

**Issue by elieteyssedou** [raycast/extensions#6348]
### Extension

https://www.raycast.com/aparandeh/manage-clickup-tasks

### Description

Hi,

Thanks for the clickup task explorer in Raycast.

Everytime I want to navigate to the board I'm looking for, I have to make it through the entire tree of space/folders/boards/list until I arrive to the board I want to explore.
I've set the "Default list ID", thinking it would bring me directly to the list I need when exploring the tasks, but the list does not show up directly.
May be the Tasks Explorer could open directly on the "Default list ID", having the possibility to escape or go back? But it would be awesome if the Tasks Explorer could arrive directly where I want it to.

Thank you!

**Comment by Ali-Parandeh** [comment]
Great suggestion, I believe there is a search endpoint that we can hook into with a search command. Would that solve your issue? Or still prefer a default list to be set?

**Comment by elieteyssedou** [comment]
Thank you @Ali-Parandeh for your answer!

A search would be great sure, but if I could arrive on the board I want in one command, it would be perfect. (isn't it the philosophy of raycast ? :) accessing things the quickest way possible)
> may be we could save the search, and coming back to Tasks Explorer could bring back the search? Idk, but less click and typing would be the better, once configured.
