### ISSUE TITLE
[Todoist] Add support for showing "All tasks"

### ISSUE THREAD

**Issue by charlesdurham** [raycast/extensions#6349]
### Extension

https://www.raycast.com/thomaslombart/todoist

### Description

It would be nice to have a command for "All tasks" or even if the "Search Tasks" command defaulted to showing all.

### Who will benefit from this feature?

Pretty much anyone ... I think :)

**Comment by charlesdurham** [comment]
Hm. After a little more fiddling around I think "Search Tasks" may just be broken but would behave this way (if the command worked). I am not able to search at all, my tasks appear for ~0.5s and then disappear and searching does not show anything.

**Comment by thomaslombart** [comment]
Hey @charlesdurham, I'm working on a big update that should suit your needs. Stay tuned! 📻

**Comment by thomaslombart** [comment]
Should be fixed by #6498
