### ISSUE TITLE
[GitHub] Allow marking all as read from menu bar

### ISSUE THREAD

**Issue by ritave** [raycast/extensions#6350]
### Extension

https://www.raycast.com/raycast/github

### Description

I'm getting around 20 notifications a day from GitHub, and while I don't need to read the contents of them, I need to keep up to date with the titles.

I would very much appreciate if I could mark all notifications as read, straight from the menu bar command. Currently I have to either open GitHub website or open list of all notifications in Raycast.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by ritave** [comment]
Hey @thomaslombart I did take a quick peak at the source, but the earliest I'd have some time to even play with it would be month/month and a half from today.

**Comment by thomaslombart** [comment]
No worries. Here's a general outline of what you can do to add the feature:

1. Add a new `MenuBarExtra.Item` in `unread-notifications.tsx`
2. Bind the `onAction` prop to a function marking notification as read. You can see how it's been done in `NotificationActions.tsx` L.58
3. Update the `CHANGELOG.md` file
4. Open the Pull Request

Hope it's helpful 😊
