### ISSUE TITLE
Missing script: "publish" when run `npm run publish`

### ISSUE THREAD

**Issue by Saafo** [raycast/extensions#6357]
### Description

When I finished developing an extension(contributing to an existing extension)(already ran `npm install` `npm run build`), and try to run `npm run publish` as the [guide](https://developers.raycast.com/basics/publish-an-extension#publish-your-extension) says, I ran into an error:

```
npm run publish
npm ERR! Missing script: "publish"
npm ERR!
npm ERR! Did you mean this?
npm ERR!     npm unpublish # Remove a package from the registry
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

I checked the package.json:

```json
  "scripts": {
    "build": "ray build -e dist",
    "dev": "ray develop",
    "fix-lint": "ray lint --fix",
    "lint": "ray lint"
  }
```

no `publish` script is available.

However, I found `and then run npx @raycast/api@latest publish` in this [article](https://developers.raycast.com/basics/contribute-to-an-extension#develop-the-extension), I try to run `npx @raycast/api@latest publish`, and it's ok.

Should we add `publish` scripts to the auto-generated package.json? I'm newbie to js, so I'm not sure how can we directly run `npm run publish` successfully as the [`Publish an Extension`](https://developers.raycast.com/basics/publish-an-extension) guide says.

### Steps To Reproduce

1. fork an existing extension
2. `npm install` && `npm run build`
3. `npm run publish`

### Current Behaviour

Missing script: "publish"

### Expected Behaviour

successfully to publish my extension

**Comment by mathieudutour** [comment]
the `publish` script is added to the package.json of new extensions, but older ones don't have it. Feel free to add it when you fork an extension that doesn't have it
