### ISSUE TITLE
[API Bug] 

### ISSUE THREAD

**Issue by rixtrayker** [raycast/extensions#636]
Raycast version: 1.26.3 - latest

## Description
When I try to paste something from clippy ( clipboard manager ) I should press cmd+shift+V so Raycast disappears.
## Steps To Reproduce

1.  Install clippy
2. press cmd+shift+V  make sure this shortcut is the default one

**Comment by fe9lix** [comment]
Could you describe this in more detail and how it's related to the API / extensions?

**Comment by rixtrayker** [comment]
<img width="423" alt="Screen Shot 2022-01-11 at 9 41 32 PM" src="https://user-images.githubusercontent.com/7710590/149010246-42d23e4b-264c-469b-82f4-a5642269bc8e.png">
I don't think it's related to the API, I can't find an appropriate category, When this tool pops Raycast disappears, so I have to press CMD + space again ( I use this as main clipboard history, I can't depend on yours at least for now).
I appreciate adding this feature if it matters.

**Comment by fe9lix** [comment]
Closing since it looks like that would be the expected Raycast behavior and it doesn't have anything to do with the API. (You can use the feedback command in Raycast to send us app-related suggestions.)
