### ISSUE TITLE
[Search npm Packages] does not work at all since apprx 2 weeks

### ISSUE THREAD

**Issue by a-x-** [raycast/extensions#6365]
### Extension

https://www.raycast.com/mrmartineau/search-npm

### Description

Shows error "Could not fetch packages" when I try to search any package

### Steps To Reproduce

1. install and select npm search packages
2. search any package (e.g. express)

**Comment by a-x-** [comment]
I use corporate's laptop with zscaler vpn&firewall. Usually I have problems with ssl certificates.
But this npm extension had worked previously

**Comment by LunaticMuch** [comment]
Can you confirm the version you're currently using?

**Comment by LunaticMuch** [comment]
Ok, I can reproduce it. It's actually interesting as I have the same trouble. Even enabling the proxy in raycast does not work. It happens with any extension.
#6379 may relate to this


@pernielsentikaer has anything change recently in Raycast or Raycast API?
