### ISSUE TITLE
[ChatGPT] ..Can not do anything. Constantly getting a message Something went wrong 

### ISSUE THREAD

**Issue by CptEugeneSparrow** [raycast/extensions#6366]
### Extension

https://www.raycast.com/abielzulio/chatgpt

#### Error:
```
Can not do anything. Constantly getting a message Something went wrong 
```

### Steps To Reproduce

Can not do anything. Constantly getting a message Something went wrong 

### Current Behaviour

Something went wrong 

### Expected Behaviour

Something went wrong

**Comment by abielzulio** [comment]
Could you provide the full error logs here? Have you made sure that you're already copied the right API key?
