### ISSUE TITLE
[Extension Feature Request] Add the ability to exclude certain paths from the "Search Recent Projects" action in the Xcode extension

### ISSUE THREAD

**Issue by sindresorhus** [raycast/extensions#638]
# Extension – [Xcode](https://github.com/raycast/extensions/tree/main/extensions/xcode)

Author: @SvenTiigi

**Describe the feature and the current behavior/state.**

I would like to see a preference where I could add paths to ignore from the "Search Recent Projects" action.

I'm aware I could ignore them in Spotlight, but I actually want those paths searchable, I just don't want them to include their Xcode projects in the "Search Recent Projects" action.

**Who will benefit with this feature?**

People that have Xcode projects they don't usually open. For example, forked projects, backups, archived projects, etc.

**Any Other info.**

Thanks for making this awesome extension. This was the last thing I needed to fully switch from Alfred to Raycast.

**Comment by SvenTiigi** [comment]
Hi @sindresorhus,

Great idea! 👍 
I will let you know when the corresponding PR has been created.

**Comment by SvenTiigi** [comment]
@sindresorhus a new version of the Xcode Raycast Extension has just been published which contains an option to exclude 
directory paths when searching for recent Xcode projects.

https://www.raycast.com/SvenTiigi/xcode

![https://user-images.githubusercontent.com/11733014/149989294-0e7f7587-f5a8-4722-8b99-1ba45b79acdc.png](https://user-images.githubusercontent.com/11733014/149989294-0e7f7587-f5a8-4722-8b99-1ba45b79acdc.png)

**Comment by sindresorhus** [comment]
Works perfectly. Thanks for implementing this 🙌
