### ISSUE TITLE
[Bundlephobia Search] ...

### ISSUE THREAD

**Issue by regalstreak** [raycast/extensions#6382]
### Extension

https://www.raycast.com/vette/bundlephobia-search

### Description

not working

### Steps To Reproduce

use it

**Comment by dgrzedzielski** [comment]
Everything is working for me. Could you please provide some more information? Just a reminder, this is only an extension to Raycast, and I'm not responsible for https://bundlephobia.com/, which may sometimes have issues that can affect the extension.

**Comment by regalstreak** [comment]
Okay I don't know how this got created, it works now! Probably was not working for before and I might've clicked on some report bug extension.
