### ISSUE TITLE
[Linear] Support Milestones in Create and View issues

### ISSUE THREAD

**Issue by guppy57** [raycast/extensions#6388]
### Extension

https://www.raycast.com/linear/linear

### Description

Linear recently added support for Milestones to further organize and group issues. I use this feature in a few projects. However, today I realized that you can't assign an issue a milestone in the Raycast Linear extension, nor view what milestone an issue belongs to when viewing an issue.

### Who will benefit from this feature?

All Linear users will benefit that have milestones enabled and setup for a Linear project.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.
