### ISSUE TITLE
[Extension Bug] Pair of key lights from elgato are not turning on/off together

### ISSUE THREAD

**Issue by d-ivashchuk** [raycast/extensions#639]
[Elgato key light](https://www.raycast.com/thomas/elgato-key-light)
Author: @thomaspaulmann 

## Description
Whenever I try to toggle the key light(I have a pair) only one will turn on and then off, on second iteration the second will turn on and then off - it never happens that both actually turn on/off on command.

## Steps To Reproduce

1. Have two key lights
2. Turn them on from extension
3. See that only one turns on/off

## The current behavior
Only one out of two elgato key lights turn on when I trigger the command

## The expected behavior
Both elgato key lights turn on when I trigger the command

### Raycast version
Version: 1.26.3

**Comment by thomaspaulmann** [comment]
Good point. I only have one KeyLight to test and this is why I ended up setting only the first light. Do you want to submit a PR to change it?

**Comment by d-ivashchuk** [comment]
sure thing! if you could only point me to the docs on how to run the extension locally and permalink the extension code! It would be a great start - I guess I can figure out everything else myself!

**Comment by thomaspaulmann** [comment]
You find our docs [here](https://developer.raycast.com) and the source code for the extension is [here](https://www.raycast.com/thomas/elgato-key-light). You can find the source code of any extension via the store:
![CleanShot 2022-01-31 at 9 21 51@2x](https://user-images.githubusercontent.com/12066405/151875208-ac85137b-bd6c-455b-b01b-30020986646d.png)

Thanks a lot for helping with this 🙇
