### ISSUE TITLE
[API Feature Request] List filtering: Extend fuzzy search over keywords

### ISSUE THREAD

**Issue by loris** [raycast/extensions#64]
**Describe the feature and the current behavior/state.**

It appears the built-in list filtering provided when using the Raycast List UI component is not doing fuzzy search over the terms set in the `keywords` prop.
For instance with the following values: `["foo bar"]`, the entry will be included if I type "foo" but not "bar".
Please note, the search is properly doing a fuzzy search over the `title` property
Let me know if this is intended, or a bug, or I am missing something.

**Will this change the current api? How?**

No

**Who will benefit with this feature?**

Every extension using the List component

**Comment by mrmartineau** [comment]
FWIW I hacked an improved filter on [my extension](https://github.com/mrmartineau/raycast-extensions/commit/678bd0b2f9e24f95d63879365f50086043234208) (not in the Raycast store yet) by splitting (`''.split(' ')`) a string of words and adding the resulting array to the `keywords` prop. Fuzzy find would be even better though..

**Comment by mrmartineau** [comment]
Unless I'm mistaken, fuzzy find has been added to list items now so I think this issue can be closed. See the changelog here: https://github.com/raycast/extensions/blob/c726a8200e05737a0643cc298d58196ada204f45/docs/changelog.md#1255---2021-11-18

**Comment by loris** [comment]
@mattisssa @mrmartineau Sorry, but this is not fixed. I think the change you are referring to is about doing fuzzy search over the terms which are in the `List.Item` `title` prop. My issue is about doing the same over the terms in the `keywords` prop as stated in the documentation:  `An optional property used for providing additional indexable strings for search. When filtering the list in Raycast through the search bar, the keywords will be searched in addition to the title.` (https://developers.raycast.com/api-reference/user-interface/list)

Right now, you can reproduce the issue with the latest Raycast version this way:
Have a List.item with the following `keywords` value: `keywords={['foo bar']}`. Search for `bar` and the list item will be filtered out instead of being included in the results (note that it will work fine when searching for `foo`).

**Comment by mrmartineau** [comment]
Yes @loris, you are correct. Fuzzy find in the `title` is working but not for `keywords`.

**Comment by fe9lix** [comment]
Just to clarify: full fuzzy search currently works with the title attribute of list items. Everything else that should be filterable such as categories in subtitles, usernames in accessory titles, etc. can be configured via keywords, which currently use prefix search only (both for performance reasons and to avoid too many false positives). Also not that there's always the possibility to opt out of built-in filtering. 

In future versions, we might make more visible fields available via fuzzy search by default, so that there shouldn't be a need to work around it via keywords.

**Comment by loris** [comment]
@fe9lix No problem! I had to switch to custom filtering in my extensions anyway because I needed more control over the filtering. Thanks.
