### ISSUE TITLE
[Authy] ...

### ISSUE THREAD

**Issue by elliotslab** [raycast/extensions#6405]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

Error: Invalid base32 characters

uu:OtpListItem.tsx:72:38
fu:search-otp.js:42:4668
Ir:index.js:5:5486
    at ray-list

### Steps To Reproduce

Hit the command to refresh the keys after adding a new one with the phone and the extension breaks and no longer show any code

**Comment by guga4ka** [comment]
@raycastbot close this issue #5880 duplicate
