### ISSUE TITLE
[API Bug] Can't find / install Core extensions

### ISSUE THREAD

**Issue by tumispro** [raycast/extensions#641]
Raycast version: 1.26.3

## Description

I didn't select the 'Calculator' extension during installation and I am unable to do so afterwards. The manual says to find it under prefs -> Extensions -> Core, but the Core entry isn't present there. See screens below for details.

## Steps To Reproduce

1. Install Raycast without Calculator extension
2. Go to prefs -> Extensions

## The current behavior

Core (and Calculator itself) are missing from the Extensions panel

## The expected behavior

Core and Calculator can be installed from the Extensions pane

![Screenshot 2022-01-10 at 16 48 49](https://user-images.githubusercontent.com/1461426/148796312-0458f67a-274b-48cc-8292-0aee20c06552.png)

![Screenshot 2022-01-10 at 16 48 13](https://user-images.githubusercontent.com/1461426/148796305-572468be-488b-4050-ba72-27c20eef7254.png)

**Comment by fe9lix** [comment]
Closing this issue since it's not related to the API: there is no separate Core or Calculator extension, it's all built-in by default. Looks like outdated docs, which we will update. Other extensions can be installed via the built-in Store command.
