### ISSUE TITLE
[GitHub] Add support for GitHub Enterprise

### ISSUE THREAD

**Issue by niksite** [raycast/extensions#6410]
### Extension

https://www.raycast.com/raycast/github

### Description

Please add support for GitHub Enterprise. 

This is essentially the same as GitHub, but with a custom GraphQL endpoint and the ability to use custom self-signed certificates.

### Who will benefit from this feature?

All Raycast users employed by companies that use GitHub Enterprise instead of the common GitHub.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide you some guidance on how to contribute to this extension so that you can open a pull request.

In the meantime, you can also use this extension which seems to suit your needs: [GitHub Enterprise
](https://www.raycast.com/Kinbaum/github-for-enterprise)

**Comment by DanielVolchek** [comment]
Hi, this is still open right? I'd like to take a crack at it if I can. It might take me some time but if no one else is working on it and it isn't a priority I could do it

**Comment by thomaslombart** [comment]
Hey @DanielVolchek, sure, feel free to tackle it 😊

**Comment by yuha0** [comment]
> This is essentially the same as GitHub, but with a custom GraphQL endpoint and the ability to use custom self-signed certificates.

fwiw, I can confirm that a simple `sed 's/github.com/my-enterprise-instance-url/g'` and it worked for me. However, besides trusting a self signed cert, one may also need to gracefully handle features that are not available in your installed version (e.g. I was trying to hit a legacy github enterprise instance on version 3.5, which does not have GitHub Discussion, and the extension crashed when it could not find a `hasDiscussionsEnabled` field in the API).

**Comment by joshgoebel** [comment]
> I can confirm that a simple sed 's/github.com/my-enterprise-instance-url/g' and it worked for me.

Wasn't quite that simple here... IIRC I had to change some token auth to bearer... and a few of the generated URLs (for notifications at least) didn't work... Our enterprise version adds an extra `/api/v3/blah` to the URL that needs to be stripped that the existing code isn't accounting for.  And I was only testing notification stuff.

That said, I'm interested in at least getting the "happy paths" working here for people using modern Enterprise GitHub... if there are perhaps a few people who'd be happy to do some testing...?
