### ISSUE TITLE
[System Monitor] Battery Menu Shown on Mac Without Battery

### ISSUE THREAD

**Issue by beschoenen** [raycast/extensions#6412]
### Extension

https://www.raycast.com/hossammourad/raycast-system-monitor

### Description

I'm on an 2019 iMac and raycast shows a battery menu for my mac.

<img width="862" alt="Captura de pantalla 2023-05-08 a las 19 52 23" src="https://user-images.githubusercontent.com/1887585/236895162-5305b159-1574-4ff6-96fa-f3d1d7bb087a.png">

### Steps To Reproduce

1. open system-monitor

### Current Behaviour

Battery tab is shown

### Expected Behaviour

Battery tab should not be shown for Macs without a battery.

**Comment by pernielsentikaer** [comment]
How does this look for you now? I just update the code 🙂 You you run `Check for extension Updates` to ensure you have the newest update and update here?

**Comment by lucasmezencio** [comment]
Hey @pernielsentikaer! Thanks for this! But I think that's not what I thought.

After you published the "Time on battery" feature, I realised that the calculation for "Time on AC" seems a bit different from what's being shown on the Activity Monitor, so I think it will require a bit more work.

What do you think?

**Comment by pernielsentikaer** [comment]
I guess so, but not sure what you exactly want, if you can draw I might be able to make it 🙂

**Comment by beschoenen** [comment]
> How does this look for you now? I just update the code 🙂 You you run `Check for extension Updates` to ensure you have the newest update and update here?

I've updated, but see no difference. Still have the battery menu available like in the initial post. I does include a "time on battery" now, which obviously doesn't work either.

**Comment by lucasmezencio** [comment]
@pernielsentikaer the log shows every entry from battery and AC, I think I'm only checking the AC entries, but when the laptop is on battery, we should consider the battery entries.

Then, when talking about this very issue, maybe the logs can show different entries, since the computer doesn't have a battery, so it could be helpful.

**Comment by pernielsentikaer** [comment]
I can't remember how it works for older models, do you? We can for sure change data so it's fits if we know the data

**Comment by beschoenen** [comment]
@lucasmezencio Assuming you meant `pmset -g`

```
System-wide power settings:
Currently in use:
 standby              1
 Sleep On Power Button 1
 womp                 1
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 proximitywake        1
 powernap             1
 gpuswitch            2
 networkoversleep     0
 autorestart          1
 standbydelayhigh     86400
 sleep                1 (sleep prevented by bluetoothd, sharingd)
 hibernatemode        3
 disksleep            10
 ttyskeepawake        1
 displaysleep         20
 tcpkeepalive         1
 highstandbythreshold 50
 standbydelaylow      86400
 ```
