### ISSUE TITLE
[Browser Bookmarks] Missing favicons

### ISSUE THREAD

**Issue by daniellacoste** [raycast/extensions#6418]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

I'm unable to see many of the favicons from the Raycast browser extension. I have a lot of "untitled" bookmarks, so it makes the extension hard to use. Some of the bookmarks include `calendar.google.com`, `docs.google.com`, etc

I have tried refreshing the bookmark using the refresh command, but it has not updated the favicon.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/11893695/236951590-6e0e6706-f1a4-47b4-b642-77087f3c4145.png">

### Steps To Reproduce

1. Chrome account
2. Create a bookmark for `calendar.google.com`
3. Open Raycast, navigate to the bookmark
4. Observe the missing favicon

**Comment by thomaslombart** [comment]
Thanks for flagging this issue. I’ve added it to our team’s backlog, but it may take some time before we can implement it. 

In the meantime, feel free to submit a pull request if you’d like to tackle this issue. I’d be happy to review it! You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by thomaslombart** [comment]
Closing this issue in favor of #6590 which has a bit more details.
