### ISSUE TITLE
[1Password] No passwords showing up when linking 1Password 7

### ISSUE THREAD

**Issue by rvanbaalen** [raycast/extensions#6419]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

The extension does not seem to work with 1Password 7 unless I'm missing installation steps somewhere?

### Steps To Reproduce

1. Choose 1Password 7 during setup
2. No passwords show up when searching for anything

### Current Behaviour

No passwords show up

### Expected Behaviour

Passwords showing up 😅

**Comment by khasbilegt** [comment]
Hello @rvanbaalen, 

Have you enabled third party integrations in the 1Password Preferences?

![image](https://user-images.githubusercontent.com/9023312/236984375-0abdf49d-9013-4e7f-b02b-93eb4cfad121.png)

**Comment by rvanbaalen** [comment]
Ah. That makes sense. 

Is it just me or is there absolutely 0 documentation about this?
