### ISSUE TITLE
[Wayback Machine] Save multiple URLs

### ISSUE THREAD

**Issue by crstauf** [raycast/extensions#6420]
### Extension

https://www.raycast.com/pernielsentikaer/wayback-machine

### Description

Interface to provide a list of URLs to save would be helpful for sites where there isn't an index of pages, but you want to save multiple pages without waiting for each one to finish.

**Comment by crstauf** [comment]
@pernielsentikaer Please review?

**Comment by andreaselia** [comment]
@crstauf I think he's currently on vacation, so not sure when he'll see this.

This sounds quite easy to implement on the surface, I guess a form input with comma separated URLs or something like that would work, then it's just if the form will continue processing if you close Raycast or not.

**Comment by crstauf** [comment]
@pernielsentikaer Still on vacation?

**Comment by andreaselia** [comment]
Hey @crstauf, I've not had time to work on this but I'll try and whip something up this week if someone doesn't beat me to it.

**Comment by crstauf** [comment]
Thanks, @andreaselia. 

What happened to @pernielsentikaer?

**Comment by andreaselia** [comment]
@crstauf I believe he has been abducted by aliens and is currently being interrogated to see what future features @thomaspaulmann has planned for Raycast.

**Comment by andreaselia** [comment]
I started work on this in PR #8730, just need @pernielsentikaer to let me know his thoughts now.

**Comment by crstauf** [comment]
Thanks! Excited to check it out!

**Comment by pernielsentikaer** [comment]
Thanks for your concern, @crstauf, I'm all good and alive 🙂

Somehow, I didn't get notifications in this thread 🫠

**Comment by crstauf** [comment]
@pernielsentikaer Is this available now? I've run "Check for extension updates" but I'm told I'm up-to-date.

**Comment by andreaselia** [comment]
@crstauf it should be available now as a new command "Save Multiple to Wayback Machine" - it is on my end at least.

**Comment by crstauf** [comment]
Oh it's a new command: did not know that.

**Comment by crstauf** [comment]
![2023-10-17T194935](https://github.com/raycast/extensions/assets/4573033/b00e9a1e-eb9c-4109-83fe-6b02a776c670)

**Comment by andreaselia** [comment]
Try restarting Raycast, and check for extension updates again.

cc @pernielsentikaer

**Comment by crstauf** [comment]
Ahh, updated Raycast, then checked for extension updates again, and there it pulled.

Didn't Raycast used to auto-inform when there were updates?
