### ISSUE TITLE
[Safari] ...

### ISSUE THREAD

**Issue by sshemirani** [raycast/extensions#6427]
### Extension

https://www.raycast.com/loris/safari

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'normalize')

l_:search-bookmarks.tsx:11:55
kr:index.js:5:2490
    at ray-navigation-stack
Lo:index.js:5:2088
```

### Steps To Reproduce

Search for a bookmark and the above error appears.

**Comment by loris** [comment]
Will be fixed with https://github.com/raycast/extensions/pull/6391

**Comment by loris** [comment]
@raycastbot close this issue
