### ISSUE TITLE
[JetBrains Toolbox Recent Projects] ...

### ISSUE THREAD

**Issue by sshemirani** [raycast/extensions#6428]
### Extension

https://www.raycast.com/gdsmith/jetbrains

### Description

The extension does not open the projects anymore. It launches Idea but the actual project does not open.

### Steps To Reproduce

1. Open Search Recent Project
2. Select the project name from the list
3. The selected project does not open

**Comment by gdsmith** [comment]
@sshemirani sorry, something broke for single versions with the changes for handling multiple versions, should be fixed in #6521
