### ISSUE TITLE
[Github] Could not create Github issue through Raycast extension

### ISSUE THREAD

**Issue by yangwao** [raycast/extensions#6432]
### Extension

https://www.raycast.com/raycast/github

### Description

I can't select repositories where to create issue. 

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/5887929/6dfcf1d2-cb17-4b3f-bbe0-ef5f19183e35">

My bet it's maybe permissions? Because other issues I can see even from our private repositories.

### Steps To Reproduce

1. write `github create`
2. press `enter`
3. try select repository 
4. I see no results to select repository

### Current Behaviour

Don't see repositories

### Expected Behaviour

Select repositories from my organization to create issue within.

**Comment by yangwao** [comment]
> Do the extension has the rights to read your org's repositories?

Yes, I've granted through oauth. Is there way to double check it through some screen?

Yes, confirming, it got access 

![image](https://github.com/raycast/extensions/assets/5887929/974736b6-a5c1-4590-85f8-003961b4899a)

**Comment by thomaslombart** [comment]
Does it happen if you use a [personal access token](https://github.com/raycast/extensions/blob/main/extensions/github/README.md#L5) instead?

**Comment by yangwao** [comment]
> Does it happen if you use a [personal access token](https://github.com/raycast/extensions/blob/main/extensions/github/README.md?rgh-link-date=2023-05-15T09%3A15%3A27Z#L5) instead?

How I'll do that?

**Comment by thomaslombart** [comment]
No ideas so far. I'd need to take some time to debug it but I have already a lot on my plate right now 😕
I encourage you to take a look at it locally if you feel like it.

**Comment by thomaslombart** [comment]
What do you mean? 🙂

**Comment by yangwao** [comment]
Hey @thomaslombart @unnamedd @tonka3000 @khasbilegt @pernielsentikaer @loxygenK @oilbeater, I've managed to get error log when I'm on **Create Issue dialog** and opened drop-down menu, maybe this is the case why I don't see anything on UI? 

It tried fetch even those I did not grant permission? 

```
Error: Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `F31F:DA31:797FC6A:7A930EC:64AEAA5F` when reporting this issue.: {"response":{"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `F31F:DA31:797FC6A:7A930EC:64AEAA5F` when reporting this issue."}],"status":502,"headers":{}},"request":{"query":"query searchRepositories($query: String!, $numberOfItems: Int!) {\n  search(query: $query, first: $numberOfItems, type: REPOSITORY) {\n    nodes {\n      ...ExtendedRepositoryFields\n    }\n  }\n}\n\nfragment ExtendedRepositoryFields on Repository {\n  id\n  nameWithOwner\n  name\n  owner {\n    login\n    avatarUrl(size: 64)\n  }\n  url\n  mergeCommitAllowed\n  squashMergeAllowed\n  rebaseMergeAllowed\n  updatedAt\n  stargazerCount\n  viewerHasStarred\n  primaryLanguage {\n    id\n    name\n    color\n  }\n  hasIssuesEnabled\n  hasWikiEnabled\n  hasProjectsEnabled\n  hasDiscussionsEnabled\n  releases {\n    totalCount\n  }\n}","variables":{"query":"user:@me org:Progressbar org:polyhack org:nko4 org:nodeschool org:geefu org:LXJS org:nodejsbratislava org:ipfs org:dysonring org:vue-polkadot org:FryTheDefi org:starmesh org:kodadot org:antfu-sponsors org:metaprimenetwork","numberOfItems":100}}}
    at /Users/yangwao/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:220:23442
    at p (/Users/yangwao/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:220:16848)
    at Object.next (/Users/yangwao/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:220:16152)
    at l (/Users/yangwao/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:220:15710)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by thomaslombart** [comment]
This error may happen because GitHub isn't able to load too much data at once. It's quite hard to debug it since it's a generic error. The best you could do would be to report this issue to GitHub with the ID you got (`F31F:DA31:797FC6A:7A930EC:64AEAA5F`)

**Comment by thomaslombart** [comment]
Closing because another issue is similar (https://github.com/raycast/extensions/issues/6519)

**Comment by yangwao** [comment]
> The best you could do would be to report this issue to GitHub with the ID you got

How to report this and where if you can help?

**Comment by yangwao** [comment]
Submitted GH ticket

**Comment by yangwao** [comment]
> From reading the referenced issues it appears that what is occurring here is that the extension is not properly dealing with paginating the list of your repositories when retrieving them [using the GitHub API](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-a-user). The GitHub API will return a maximum of 100 results when searching for a users repositories, and I see that you have 465 repositories. I see that they have already created [a pull request](https://github.com/raycast/extensions/pull/7846) to fix that issue, so I would recommend watching that to be merged and released in a new version of the extension.

Probably fixed in 
- #7846
