### ISSUE TITLE
[Safari] Not able to search bookmark

### ISSUE THREAD

**Issue by ltsai323** [raycast/extensions#6433]
### Extension

https://www.raycast.com/loris/safari

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'normalize')

l_:search-bookmarks.tsx:11:55
kr:index.js:5:2490
    at ray-navigation-stack
Lo:index.js:5:2088
```

### Steps To Reproduce

open "Search bookmark in Safari".
Type one key to get this error

### Current Behaviour

Something went wrong. Use cmd+k to report bug

### Expected Behaviour

Search bookmark

**Comment by loris** [comment]
Will be fixed in https://github.com/raycast/extensions/pull/6391

**Comment by loris** [comment]
@raycastbot close this issue
