### ISSUE TITLE
[Jira2Git] Crashes without further notices

### ISSUE THREAD

**Issue by Tylopilus** [raycast/extensions#6434]
### Extension

https://www.raycast.com/ipiranhaa/jira2git

#### Error:
```
Could not load command

```

### Steps To Reproduce

Download extension
Provide PAT and email
copy url (https://company.atlassian.net/browse/XXX-266)

### Current Behaviour

Displays `Something went wrong` with the error mentioned above

### Expected Behaviour

Creates a branch name and is copyable

**Comment by ipiranhaa** [comment]
@Tylopilus Could you please provide some images or videos for reproduction?
