### ISSUE TITLE
[Orion] Search Orion Reading List command doesn't work (seemingly because the list is too lengthy)

### ISSUE THREAD

**Issue by PaawanSharma** [raycast/extensions#6435]
### Extension

https://www.raycast.com/plonq/orion

### Description

This extension provides 4 commands. 3 of them work for me. `Search Orion Reading List` does not work. The error suggests to me that it is because my Reading List is too long. I would be curious to know if there is a way to resolve this or at least find out what the size of the list is.

### Steps To Reproduce

Orion 0.99.124-beta (WebKit 616.1.10)
MacOS 13.3.1
Raycast 1.50.4

### Current Behaviour

```
Error: maxObjectCount exceeded

bA.parseBuffer:bplistParser.js:92:10
bA.parseFileSync:reading-list.js:1:22826
reading-list.js:71:1921
reading-list.js:71:1975
```

### Expected Behaviour

I should be able to search the Reading List.

**Comment by Plonq** [comment]
Hi @PaawanSharma, I'll look into this when I can (some time in the next few days)

**Comment by Plonq** [comment]
@PaawanSharma How many items do you have in your reading list?
