### ISSUE TITLE
[The Office Quotes] ... Failed to load quotes getaddrinfo ENOTFOUND www.officeapi.dev

### ISSUE THREAD

**Issue by bcometa** [raycast/extensions#6439]
### Extension

https://www.raycast.com/braydoncoyer/office-quotes

### Description

First time install... can't use it. Says: Failed to load quotes getaddrinfo ENOTFOUND www.officeapi.dev

### Steps To Reproduce

Just install and open in raycast. 

### Current Behaviour

Says: Failed to load quotes getaddrinfo ENOTFOUND www.officeapi.dev

### Expected Behaviour

See office quotes

**Comment by firesofmay** [comment]
Plus one, still failing
