### ISSUE TITLE
[Extension Bug] Outdated Authy dependency

### ISSUE THREAD

**Issue by fe9lix** [raycast/extensions#645]
# Extension – [Authy](https://github.com/raycast/extensions/tree/main/extensions/authy)
Author:  @guga4ka  

## Description
Authy uses the node-forge dependency, which has some vulnerabilities according to Dependabot in versions < 1.0.0.

## Steps To Reproduce
Run Dependabot on the extension.

## The current behavior
Vulnerabilities are detected.

## The expected behavior
No vulnerabilities are detected.

**Comment by guga4ka** [comment]
#646 add it manually, is it possible to add dependabot to this repository?
