### ISSUE TITLE
[Browser Bookmarks] ...

### ISSUE THREAD

**Issue by metalhaze** [raycast/extensions#6450]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20
```

### Steps To Reproduce

1. Install the new "Search Browser Bookmarks"
2. Launch the extension
3. Hit Enter to choose browsers to search
4. Choose Safari and Chrome
5. Exit the extension and open it again to reload it
6. The extension instantly crashes

I have over 4000 bookmarks in Chrome. Combine that with Safari and I prob have like 6000

### Current Behaviour

Instantly crashing on launch

### Expected Behaviour

To not crash on launch

**Comment by thomaslombart** [comment]
Thanks for bringing up this issue. I'll work on it.
