### ISSUE TITLE
[My Daily Log] Logging at midnight counts as "Yesterday"

### ISSUE THREAD

**Issue by patrickmccallum** [raycast/extensions#6451]
### Extension

https://www.raycast.com/frugoman/my-daily-log

### Description

When logging an entry in a file as the first item at 00XX hours (e.g. 12:35am) it will create the file under yesterday's date.

So a log created at the 11th of May at 12:35am creates a file as the 10th of may at "24:35".

Attached image is an example I made while creating this ticket.

<img width="415" alt="image" src="https://github.com/raycast/extensions/assets/11825795/c22d7139-84a1-4906-b0f3-33feb0da0fb7">

### Steps To Reproduce

1. Have no data (Likely not needed but useful for illustrating the problem)
2. Have clock to midnight
3. Create new log
4. Observe the log creates it under yesterday

**Comment by frugoman** [comment]
Thanks for reporting! I'll take a look this week!

**Comment by patrickmccallum** [comment]
@frugoman Update: I think this is actually related to timezones? I'm in +10:00 and it was logging items created at 9am under "Yesterday" as well, but the next items made at 11:30 worked fine.

Thanks for looking into this.
