### ISSUE TITLE
[Holodex] TypeError: (intermerdiate value).map is not a function

### ISSUE THREAD

**Issue by DaniruKun** [raycast/extensions#6452]
### Extension

https://www.raycast.com/uetchy/holodex

### Description

When using any of the commands, they all fail with a TypeError.

### Steps To Reproduce

1. Launch the `Holodex` extension
2. Call any command (e.g. Livestreams)
3. Observe the error

### Current Behaviour

`TypeError: (intermerdiate value).map is not a function`
And no results

### Expected Behaviour

Should provide an interactive list of results.

**Comment by hcy1251** [comment]
Hi! I cloned the repo down and change the API header from `X-API-KEY` into `X-APIKEY`, and I'm able to do the actions without TypeError, but unfortunately I'm not sure about how to publish the debug process, which I'm having a branch modified the API header, and not able to push it and do the pull request process.

**Comment by DaniruKun** [comment]
@raycastbot close this issue
