### ISSUE TITLE
[My Daily Log] Copy notes to clipboard from logged days of the month view

### ISSUE THREAD

**Issue by patrickmccallum** [raycast/extensions#6454]
### Extension

https://www.raycast.com/frugoman/my-daily-log

### Description

Ability to copy the selected days notes to the clipboard, or alternately open them for line by line inspection/edit/copy/delete from Raycast would be amazing

### Who will benefit from this feature?

I'm using it to log my tasks which I'm required to paste into slack daily as part of "What did you do yesterday" program. This would speed the process as currently I have to go and open the file manually or just retype what in the extension view.

**Comment by frugoman** [comment]
Ah this is a good one!

I'm not sure if you will have the Raycast Pro sub to get raycast AI, I've added an extension for that that generates a stand-up speech ready to copy paste or read.

Apart from this, I think I can add something as well to see the status of the day as text that's easy to copy!

Probably no editable, but at least to copy!

**Comment by frugoman** [comment]
In #6540 I've added an option to 'Copy all to clipboard', to get the list copied!
