### ISSUE TITLE
[Extension Feature Request] Allow searching "provider" field as well

### ISSUE THREAD

**Issue by aeons** [raycast/extensions#646]
## Extension – [Authy](https://github.com/raycast/extensions/tree/02ce9ff8953b3fad9b963405145801ff95b59600/extensions/authy/)

Author:  @guga4ka 

Many of my Authy apps are named the same, since they use the username as their name by default. It would be nice to be able to also search in the "provider" field when searching.

IE. to get my github token, I currently need to search for `aeons`, my username, and then arrrow-down to the github entry. If I could search for `github` instead, there would be far fewer entries.

**Comment by guga4ka** [comment]
#648 add subtitle to search, it's either issuer or account type
