### ISSUE TITLE
[Notion] ...

### ISSUE THREAD

**Issue by jasonesiegel** [raycast/extensions#6460]
### Extension

https://www.raycast.com/HenriChabrand/notion

### Description

There's a database that does not appear in Notion search results. I'm not sure what the unique attribute of the database would be to cause this. It's my most-used database.

### Steps To Reproduce

1. Search for database name.
2. Database is not in results.

**Comment by mathieudutour** [comment]
Did you check https://github.com/raycast/extensions/tree/814dd02e872eb88bc1ee2556d319d9c7e1d71430/extensions/notion/#i-cannot-find-the-notion-page-or-database-from-raycast?

**Comment by jasonesiegel** [comment]
Yes, everything's connected.
