### ISSUE TITLE
[deepcast] .. setTargetLanguage to last selection

### ISSUE THREAD

**Issue by FL0R1AN84** [raycast/extensions#6463]
### Extension

https://github.com/raycast/extensions/tree/a66477346699916635254ff66b88e76b338514c8/extensions/deepcast

### Description

Why is the target language set to EN-US? I want to select another target language. It would be best to activate the last selection again. A super feature would be, if I could set the target language in the settings.

` const [targetLanguage, setTargetLanguage] = useState<TargetLanguage>("EN-US");`

### Steps To Reproduce

https://github.com/raycast/extensions/blob/a66477346699916635254ff66b88e76b338514c8/extensions/deepcast/src/index.tsx

**Comment by MonsterDeveloper** [comment]
Good morning!

> Why is the target language set to EN-US

I guess as it's default in Raycast.

> A super feature would be, if I could set the target language in the settings.

This doesn't sound very complicated — just another preference.

However, we should choose between default target language in settings or the language from last translation. I don't currently see a way of combining these two approaches.

**Comment by FL0R1AN84** [comment]
But the target language is defined in the code and not in Raycast?

`const [targetLanguage, setTargetLanguage] = useState<TargetLanguage>("EN-US");`

at line 29: https://github.com/raycast/extensions/blob/a66477346699916635254ff66b88e76b338514c8/extensions/deepcast/src/index.tsx

**Comment by MonsterDeveloper** [comment]
That’s true, yep.

Are you thinking about selecting default target language in settings?

Or using the previously selected language?

Maybe there’s a way of combining these two approaches, but I don’t see it now.

**Comment by FL0R1AN84** [comment]
I wouldn't really care. Both options are good. I was only surprised that since the extension update the target language is now always fixed and then also in US English. Before, at least the last selection was always used and the behaviour was wonderful for me.
