### ISSUE TITLE
[Music] HUD message missing icons

### ISSUE THREAD

**Issue by fengtianze** [raycast/extensions#6474]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

[SFSymbols](https://github.com/raycast/extensions/blob/f9d8b9ead48d00233977deee9bc46e816b5b8606/extensions/music/src/util/models.ts#L7) still missing definition, may be just remove it?

![CleanShot 2023-05-11 at 16 31 38@2x](https://github.com/raycast/extensions/assets/16134228/f5605543-69ea-494a-805b-ad72cd3f2ac7)

### Steps To Reproduce

1. Execute commands such as play, pause, etc.
2. See HUD information

**Comment by Rawnly** [comment]
Do you have SFSymbols Installed?

**Comment by fengtianze** [comment]
> Do you have SFSymbols Installed?

Thanks，I thought the system was installed by default😅
