### ISSUE TITLE
[NBA Viewer] ...

### ISSUE THREAD

**Issue by andreev-danila** [raycast/extensions#6482]
### Extension

https://www.raycast.com/AbhinavPalacharla/nba-viewer

### Description

When game time is TBD your render 8:00(maybe it is only my timezone). Maybe we can just render TBD for this case, it is more predictable about game like that

### Who will benefit from this feature?

All who interesting in actual data about NBA Playoff games, yo!
Thanks for this extension, it is very useful ✨

### Anything else?

`I can help with code as well, if you have no time for this task`

**Comment by djpowers** [comment]
I'd say give it a try @andreev-danila if you're up for it!
