### ISSUE TITLE
[ChatGPT] failed to load after copying API key, returned a message saying something went wrong...

### ISSUE THREAD

**Issue by dougcasement** [raycast/extensions#6486]
### Extension

https://www.raycast.com/abielzulio/chatgpt

#### Error:
```

```

### Steps To Reproduce

Mac M1 system running MacOS 13.2.1
Just upgraded Raycast to Pro
Created, copied and pasted Open AI API key into the required Raycast input field
Returned an error message saying "Something went wrong"

**Comment by abielzulio** [comment]
Could you provide the full error logs here? Have you made sure that you're already copied the right API key?

**Comment by dougcasement** [comment]
Hi Abiel,I can't recreate the error – in fact, I can't even re-locate the field where the API goes. However, it now seems to be working, in that all of the Open.ai commands/extensions behave properly.In answer to your other question: it was a new API key specifically created for Raycast and I copied and pasted it, rather than re-key it.Cheers
DougAt 4:18 am on 14 May 2023, Abiel Zulio M ***@***.***> wrote:Could you provide the full error logs here? Have you made sure that you're already copied the right API key?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by abielzulio** [comment]
> Hi Abiel,I can't recreate the error – in fact, I can't even re-locate the field where the API goes. However, it now seems to be working, in that all of the Open.ai commands/extensions behave properly.In answer to your other question: it was a new API key specifically created for Raycast and I copied and pasted it, rather than re-key it.Cheers
> DougAt 4:18 am on 14 May 2023, Abiel Zulio M ***@***.***> wrote:Could you provide the full error logs here? Have you made sure that you're already copied the right API key?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
 
I'm able to reproduce it and turned out your API key was wrong so it wouldn't load initially.

@raycastbot close this issue
