### ISSUE TITLE
[GitHub] Menubar notification should link using notification referer

### ISSUE THREAD

**Issue by kiliankoe** [raycast/extensions#6495]
### Extension

https://www.raycast.com/raycast/github

### Description

When opening a notification from the notification center on GitHub directly, the URL has a notitication referer ID appended to it, e.g. `https://github.com/<org>/<repo>/<whatever>?notification_referrer_id=<ID>`. I think this is what powers the banner to be displayed at the top where the notification can be marked as done aside from other actions. I assume this ID is accessible from the notification API endpoint (or at least I hope so).

This is currently not shown when going to the notification directly through the GitHub extension menubar item, but it would be great if it were!

### Who will benefit from this feature?

Every user of the fantastic new GitHub notification menubar extension.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by kiliankoe** [comment]
Hi @thomaslombart, after looking at it again, it seems that the extension already links to the correct URL, I unfortunately don't know what it could be doing differently to get the top bar to show :/
