### ISSUE TITLE
[Extension Feature Request] Show brew formula / cask name in addition to display name

### ISSUE THREAD

**Issue by tonyxiao** [raycast/extensions#650]
I use `Brewfile` and really enjoy using Raycast extension to search. However it is not possible for me the figure out the right formula / cask name because the extension only displays the "display name" which cannot be used on the command line. 

<img width="832" alt="image" src="https://user-images.githubusercontent.com/696842/149005343-74e7f1a1-dbeb-4873-a281-a8d7a25a0e5b.png">

**Comment by thomaspaulmann** [comment]
Maybe adding an action to copy the formula/cask name would work?

**Comment by nhojb** [comment]
@tonyxiao thanks for the feedback!

I've added the ability to copy the formula or cask name in the next (pending) [update](https://github.com/raycast/extensions/pull/701):

<img width="862" alt="Screenshot 2022-01-17 at 22 22 41" src="https://user-images.githubusercontent.com/312540/149911946-2462fcd0-5b1d-4c07-8406-6df804f90099.png">
<img width="862" alt="Screenshot 2022-01-17 at 22 22 46" src="https://user-images.githubusercontent.com/312540/149911956-9d8adbff-6be0-4606-9956-511082978ab9.png">
