### ISSUE TITLE
[RSS Reader] ...

### ISSUE THREAD

**Issue by Arnav12S** [raycast/extensions#6505]
### Extension

https://www.raycast.com/fuksman/rss-reader

### Description

To load the article with in the raycast app? Like Associated Press Extension.

**Comment by SKaplanOfficial** [comment]
You can view articles using the action menu or by pressing `command+return`, which will give something like this view:

<img width="1000" alt="rss-reader-1" src="https://github.com/raycast/extensions/assets/7865925/c0f34d28-8c0d-48ae-85c2-b411d7cf66a7">
