### ISSUE TITLE
[ChatGPT Quick Actions] ...

### ISSUE THREAD

**Issue by jwlben11** [raycast/extensions#6509]
### Extension

https://www.raycast.com/alanzchen/chatgpt-quick-actions

### Description

I want to be able to add and store my own custom commands and prompts, and be able to edit the prompts of the current commands

**Comment by alanzchen** [comment]
Adding a custom command is not possible as Raycast does not allow extensions to dynamically register commands. Instead, all the commands are pre-registered in the source code. I do provide a custom command slot for you to use your own prompt, but you can't rename it to something else at the moment.
