### ISSUE TITLE
[Extension Bug] Search Vercel Deployments Fails to Install

### ISSUE THREAD

**Issue by mulholo** [raycast/extensions#651]
# Extension – [Vercast](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/vercast)

Author: @gleich

## Steps To Reproduce

1. Install extension from https://www.raycast.com/matt/vercast
2. Grab new token from https://vercel.com/account/tokens
3. Put in Raycast after running vercast command. Also tried in extensions menu. 
4. See error below ins creenshot

## The current behaviour

Failed to fetch deployments

<img width="767" alt="CleanShot 2022-01-11 at 22 01 37@2x" src="https://user-images.githubusercontent.com/20966690/149028337-95c030a5-fdfe-4967-8324-7430ede78fe4.png">

## The expected behavior

Can search my deployments

### Raycast version
Version: 1.26.3

**Comment by gleich** [comment]
Hey @mulholo! Sorry to hear you're having issues. Would you mind sending the log error? Make sure you don't have your PAT in the error before sending.
