### ISSUE TITLE
[github] can't create issues based on repository

### ISSUE THREAD

**Issue by noghartt** [raycast/extensions#6519]
### Extension

https://github.com/raycast/extensions/tree/main/extensions/github0b1/extensions/github/

### Description

After doing the initial setup to run the extension, trying to `Create Issue` is showing an error: `"Failed to fetch data"`. 

### Steps To Reproduce

1. Install GitHub extension
2. Setup it (create the right token, with the right permissions)
3. Try to `Create Issue`
4. Search for a repository from another org, like my case
5. Wait some seconds while searching
6. See the error message

### Current Behaviour

Display an error message `"Failed to fetch data"`.

### Expected Behaviour

Should display the right searched repository to allow me to go for the rest of the form to create the issue.

**Comment by thomaslombart** [comment]
Do you have more details on the error? You should be able to copy the error logs with the `Failed to fetch latest data` error toast.

**Comment by noghartt** [comment]
> Do you have more details on the error? You should be able to copy the error logs with the `Failed to fetch latest data` error toast.

Oh, I'm sorry, I forgot to add the error log, adding it below:

#### Error:
```
Error: Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `CE4E:4ACB:19B30582:19F10D77:64620A89` when reporting this issue.: {"response":{"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `CE4E:4ACB:19B30582:19F10D77:64620A89` when reporting this issue."}],"status":502,"headers":{}},"request":{"query":"query searchRepositories($query: String!, $numberOfItems: Int!) {\n  search(query: $query, first: $numberOfItems, type: REPOSITORY) {\n    nodes {\n      ...ExtendedRepositoryFields\n    }\n  }\n}\n\nfragment ExtendedRepositoryFields on Repository {\n  id\n  nameWithOwner\n  name\n  owner {\n    login\n    avatarUrl(size: 64)\n  }\n  url\n  mergeCommitAllowed\n  squashMergeAllowed\n  rebaseMergeAllowed\n  updatedAt\n  stargazerCount\n  viewerHasStarred\n  primaryLanguage {\n    id\n    name\n    color\n  }\n  hasIssuesEnabled\n  hasWikiEnabled\n  hasProjectsEnabled\n  hasDiscussionsEnabled\n  releases {\n    totalCount\n  }\n}","variables":{"query":"user:@me org:entria org:Open-Pix org:FantomRPG org:PepefyApp org:compsci-labs org:doskya-labs org:ccsseraphini org:learning-in-public org:Jeffaneios org:woovibr org:doskya","numberOfItems":100}}}
    at /Users/noghartt/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:220:23443
    at p (/Users/noghartt/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:220:16849)
    at Object.next (/Users/noghartt/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:220:16153)
    at l (/Users/noghartt/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:220:15711)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by noghartt** [comment]
> Does it always fail or does it succeed sometimes?

Every time that I tried it, it fail. I tried some combinations of permissions on my token too, even putting all permissions together, didn't work.

**Comment by thomaslombart** [comment]
Does your account or different orgs have lots of repositories?

**Comment by noghartt** [comment]
> Does your account or different orgs have lots of repositories?

Yes, more than 200 repositories summing all orgs + my account.

**Comment by ahmetrehaseker** [comment]
I am facing the same issue, I forked the extension to test it, and I found out that extension getting 100 repositories with the `useMyRepositories` function. When I changed that number to 10 it works fine ( but it retrieves 10 repository). Basically main issue is timeout. I also run the graphql with the same query and get the similar error. Maybe a pagination can fix this problem or the shrinking the retrieved data might help.

**Comment by thomaslombart** [comment]
Unfortunately, pagination is a bit tricky to implement right now, but it's something we want to look into. The best thing to do now, as you said, would be to shrink the data and support typeahead search for repositories and other relevant fields.

**Comment by yangwao** [comment]
Hey I have a similar issue 

@noghartt 

https://github.com/raycast/extensions/issues/6432

**Comment by yangwao** [comment]
I think it's meanwhile working, can close.

Thanks for effort
