### ISSUE TITLE
[Browser Bookmarks] for Arc Browser

### ISSUE THREAD

**Issue by 100rab-S** [raycast/extensions#6520]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

The easy access to browser bookmarks and also can access to specific folders is great. Love this feature and use it every day on Chrome and Brave browsers. But this feature isn't available on Arc browser. It would be great if there is a feature to access the pinned tabs and folders through such a extension.

### Who will benefit from this feature?

All the Arc browser users.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.
