### ISSUE TITLE
[ChatGPT] ...

### ISSUE THREAD

**Issue by Simonedb235** [raycast/extensions#6523]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

It doesn't work
<img width="758" alt="Screenshot 2023-05-13 at 10 15 47 AM" src="https://github.com/raycast/extensions/assets/66254053/394bea04-598a-462d-9254-be6ddf6c4cbd">

### Steps To Reproduce

1. open Raycast
2. goes to ask question 
3. write something to chat gpt
4. the error is displayed

**Comment by abielzulio** [comment]
Closing this issue due to a future fix that will be available on [the next update](https://github.com/raycast/extensions/pull/6528).

**Comment by abielzulio** [comment]
@raycastbot close this issue
