### ISSUE TITLE
[Music] Missing Icons

### ISSUE THREAD

**Issue by leonlazic** [raycast/extensions#6526]
### Extension

https://github.com/raycast/extensions/tree/8e05d3724b6fb41b767d3d67b25394c269d5daa5/extensions/music

### Description

Icons are missing and replaced by a square box and ? for every command.
![Missing Icons](https://github.com/raycast/extensions/assets/26551422/fdd1df1d-d93c-405c-b78c-12370fd59505)

### Steps To Reproduce

Execute any command. Missing Icons next to command name

**Comment by Rawnly** [comment]
Please make sure to have sfsymbols installed

**Comment by leonlazic** [comment]
> Please make sure to have sfsymbols installed

Thank you very much. This should be probably added to the top of the readme.

**Comment by leonlazic** [comment]
@raycastbot close this issue
