### ISSUE TITLE
[ChatGPT] Can't add new model if all are deleted

### ISSUE THREAD

**Issue by fgeierst** [raycast/extensions#6538]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

I deleted all models. The screenshot suggests Cmd T would bring up a dialog to add a new model, but it doesn't.

<img width="739" alt="Bildschirmfoto 2023-05-14 um 12 07 25" src="https://github.com/raycast/extensions/assets/22551442/e6f8705f-3ab9-4099-8f70-9a77900506cc">

### Steps To Reproduce

1. Install ChatGPT extension, bring up the model view and delete the default model.
2. Hit Cmd+T to create a new model

### Current Behaviour

Cmd T does trigger any response.

### Expected Behaviour

Cmd T brings up a form to add a new model.

**Comment by abielzulio** [comment]
> ### Extension
> 
> https://www.raycast.com/abielzulio/chatgpt
> 
> ### Description
> 
> I deleted all models. The screenshot suggests Cmd T would bring up a dialog to add a new model, but it doesn't.
> 
> 
> 
> <img width="739" alt="Bildschirmfoto 2023-05-14 um 12 07 25" src="https://github.com/raycast/extensions/assets/22551442/e6f8705f-3ab9-4099-8f70-9a77900506cc">
> 
> 
> 
> ### Steps To Reproduce
> 
> 1. Install ChatGPT extension, bring up the model view and delete the default model.
> 
> 2. Hit Cmd+T to create a new model
> 
> ### Current Behaviour
> 
> Cmd T does trigger any response.
> 
> ### Expected Behaviour
> 
> Cmd T brings up a form to add a new model.

Could you elaborate on how did you delete all the models? Seems I didn't allow the user to delete all the models including the default one.

**Comment by fgeierst** [comment]
Not sure how I deleted the default model, it was by accident and some time ago. Maybe I renamed it and then deleted it?

Is there a way to reset the extension?

**Comment by fgeierst** [comment]
I uninstalled the extension and installed it again. That way, I got the default model back. Now the actions are visible and I can add new models, too.

**Comment by edobry** [comment]
I also have this issue, the models just disappeared by themselves. I don't want to uninstall as I don't want to lose my Conversations history. is there any way to fix this or to preserve my data?

**Comment by zakelfassi** [comment]
> I also have this issue, the models just disappeared by themselves. I don't want to uninstall as I don't want to lose my Conversations history. is there any way to fix this or to preserve my data?

Same here, and just randomly happened. No more models, and can't create new ones without destroying all data/reinstalling ...
