### ISSUE TITLE
[Visual Studio Code - Project Manager] Make it work when VSCode is closed

### ISSUE THREAD

**Issue by wottpal** [raycast/extensions#6539]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

This extension would be way more useful if it would be somehow made available when VSCode is closed. Right now, it only shows this:

<img width="862" alt="Screenshot 2023-05-14 at 14 43 20" src="https://github.com/raycast/extensions/assets/3930150/e221340e-57f4-4b9c-bf55-12ac47494b6b">

### Who will benefit from this feature?

Developers using VSCode starting to work on their project (w/o having VSCode opened already)

**Comment by theherk** [comment]
It does work when closed, and will open it for you. Do you have that extension installed? If so, maybe provide some more information about your system and how you have the extension configured.

**Comment by theherk** [comment]
To be clear, you need a plugin in VS Code in addition to the Raycast plugin. You can get it [here](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) or in [Open VSX](https://open-vsx.org/extension/alefragnani/project-manager).

**Comment by wottpal** [comment]
Hey @theherk, thanks for following up. I have the extension installed (for years, actually). The Raycast extension works as expected when VSCode is running; it doesn't otherwise.

I tried a bit with my extension settings and found that this check mark (that i've had unset somewhen in the past) was causing the issue. After re-enabling caching, everything works as expected 🤦‍♂️

```
"projectManager.cacheProjectsBetweenSessions": false
```

**Comment by theherk** [comment]
Oh sweet. I wouldn't have guessed. Glad you got it sorted, and explained here for others that come looking.
