### ISSUE TITLE
Compatibility with Bear 2

### ISSUE THREAD

**Issue by sccardais** [raycast/extensions#6549]
### Extension

https://www.raycast.com/hmarr/bear

### Description

Is the Bear extension for Raycast compatible with Bear 2? I realize that Bear 2 isn't the official release but I noticed something about updating the extension for Bear 2 in the GitHub documentation.

Thank You
ScottC

### Steps To Reproduce

Running MAC OS 13.4 and Bear Version 2.0 (10209)

The Search action works but the Create note does not.

**Comment by juanbanchero** [comment]
Yes it is! I've been using it since the beta of bear 2 and it works like charm 😄 

@raycastbot close this issue
