### ISSUE TITLE
Allow to move the cursor to next item on a list

### ISSUE THREAD

**Issue by danielo515** [raycast/extensions#655]
**Describe the feature and the current behavior/state.**
I want to be able to programatically move the selected item on a list, so user can take quick action on an entire list.

**Will this change the current api? How?**
No, this is an additional api that should be opt-in

**Who will benefit with this feature?**
Doing quick actions on a list. For example, imagine you have a todo-list that is not binary, that has different intermediary states. You could implement a quick action on the item to move it from not done to "in-progress" and move the cursor to the next item on the list

**Any Other info.**
Currently the only thing I think can be done is to keep several sections within the list and move the current item to the second part of the list, but this is a misuse of the current API IMO.

**Comment by fe9lix** [comment]
If I understand correctly, wouldn't the `selectedItemId` property on the list allow you to do that? https://developers.raycast.com/api-reference/user-interface/list
