### ISSUE TITLE
[UUID Generator] ULID support

### ISSUE THREAD

**Issue by jerome-wego** [raycast/extensions#6555]
### Extension

https://www.raycast.com/jmaeso/uuid-generator

## What
Add an action to generate a ULID string.#6522 

### Who will benefit from this feature?

Developer who use ULID for time-sortable unique keys

**Comment by Jqnxyz** [comment]
> Hey, did you tag issue `6522` on purpose? Thanks!

Not at all. Weird! Sorry about that.

**Comment by LunaticMuch** [comment]
Let's make this less stale now :)

**Comment by jmaeso** [comment]
Hi all 👋 
Sorry for the radio silence here, I've been busy lately. As the creator of this extension I'm good with any feature for it while it keeps it's main purpose, which is to have a `UUID` in the clipboard by just: 
1. Raycast shortcut
2. Typing `uuid`
3. <enter>
Any feature on top of that as a param, argument, extra window, etc. is good if it can help more people, but please, don't change the main usecase 🙏
