### ISSUE TITLE
[Bitwarden Vault] When "Copy and Paste to Active App" selected, password not copied ("Generate Password (Quick)" command)

### ISSUE THREAD

**Issue by davidmickelsen** [raycast/extensions#6569]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

It seems that when using the "**Generate Password (Quick)**" command, when the selected **Action to perform after generating** is "Copy and Past to Active App", the command is failing to copy the generated password to the clipboard. It successfully pastes the password into the active app, but the password is not copied to the clipboard.

The **Action** "Copy to Clipboard" works as expected; the generated password is successfully copied to the clipboard.

The **Action** "Paste to Active App" also works as expected; the generated password is pasted into the active app, but not copied to the clipboard.

### Steps To Reproduce

1. In Raycast Preferences, for the command "**Generate Password (Quick)**", set the **Action to perform after generating** to "Copy and Paste to Active App".
2. Run the "**Generate Password (Quick)**" command.

### Current Behaviour

The generated password is pasted into the active app, but it is not copied to the clipboard.

### Expected Behaviour

The generated password is pasted into the active app, and it is copied to the clipboard.

**Comment by jomifepe** [comment]
Thanks for reporting, should be fixed now

**Comment by pernielsentikaer** [comment]
Closing as fixed
