### ISSUE TITLE
Twitter Extension gives the 403 

### ISSUE THREAD

**Issue by MassivDash** [raycast/extensions#657]
# Extension – [Twitter](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/twitter/README.md)

Author: @tonka3000

## Description
The new twitter access levels have disrupted the work of this extension. This is not bug report per say, this extension uses Oauth 1.0, which is now behind elevated twitter plan, only v2 endpoint are free for developers right now.

If I try to use the app I get 403 error: "You currently have Essential access which includes access to Twitter API v2 endpoints only"
Any chance for v2 endpoint rewrite ? 

## Steps To Reproduce

1. install extension 
2. follow the installation instructions

### Raycast version
Version: 1.26.3

**Comment by zepfietje** [comment]
This is still a relevant issue.

**Comment by zepfietje** [comment]
Still an issue.

**Comment by andypiper** [comment]
You can apply for Elevated access on the Twitter API to access the v1.1 API for free, there is no cost (but there may be a wait to get approval). Alternatively, this extension would need to be rewritten using a more up-to-date API library that calls the v2 API.

**Comment by tonka3000** [comment]
Hi @andypiper ,

the extension can not really use v2, because most endpoints simply not exist in v2 which are required for the extension (see update in README from https://github.com/raycast/extensions/pull/1561). Using v1 is the only option, because v2 is unfinished.

**Comment by ArtemisFowl-san** [comment]
Hey, I still get the same error message after going through the OAuth link. Is this supposed to be working by simply signing in or do you still need an API key
