### ISSUE TITLE
`code` styling on `Form.TextArea` continues for one character after closing backtick

### ISSUE THREAD

**Issue by davej** [raycast/extensions#6573]
### Extension

https://www.raycast.com/linear/linear

### Description

The Markdown formatter seems to continue the `code` styling for one character after the backtick is closed. This is purely visual because the created issue is formatted correctly.

### Steps To Reproduce

1. Choose "Create Issue"
2. Type some text surrounded by backticks into the description field

### Current Behaviour

The `code` styling continues for one character after the backtick is closed. See vid below.

https://github.com/raycast/extensions/assets/26971/24d86e32-584e-4020-ba08-abc6746502c5

### Expected Behaviour

The `code` styling should terminate immediately after the backtick character.

**Comment by mathieudutour** [comment]
This should be fixed in 1.51.2
