### ISSUE TITLE
[Authy...] I don't get approval request

### ISSUE THREAD

**Issue by alexkubica** [raycast/extensions#6578]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

I followed instructions on https://github.com/raycast/extensions/blob/dd81b21f6b2b3265d57a15ae4aa14d53766d3feb/extensions/authy/README.md however I'm not getting the approval request
I checked both on Mac app and on iPhone app
The credentials are correct as I was able to login on Mac app
I tried reinstalling but it didn't help

### Steps To Reproduce

1. Install Authy extension
2. Run and configure it as instructed
3. No approval request

### Current Behaviour

No approval request

### Expected Behaviour

To get approval request

**Comment by alexkubica** [comment]
Hey any update on this one?

**Comment by guga4ka** [comment]
hey, could you pls twice check this option  and authy id 
<img width="621" alt="image" src="https://github.com/raycast/extensions/assets/13866979/eb63ad48-3675-4f3b-a805-d53ed1588256">
<img width="621" alt="image" src="https://github.com/raycast/extensions/assets/13866979/29fe22a8-2a84-429a-856d-0141fded53d0">

**Comment by guga4ka** [comment]
@raycastbot close this issue

fill free to reopen in case issue hasn't been resolved
