### ISSUE TITLE
[GitHub] Add ability to merge pull requests

### ISSUE THREAD

**Issue by kud** [raycast/extensions#6582]
### Extension

https://www.raycast.com/raycast/github

### Description

As a user of the Raycast extension, I would love to be able to merge pull requests directly from the Raycast interface. This would save me time and allow me to streamline my workflow by avoiding the need to switch between multiple tools. Adding this functionality would be a great enhancement to the Raycast extension and would greatly improve the user experience for those who frequently work with pull requests on GitHub.

**Comment by thomaslombart** [comment]
It is possible to merge pull requests with the extension provided you have the rights (cf [this file](https://github.com/raycast/extensions/blob/main/extensions/github/src/components/PullRequestActions.tsx#L169))
