### ISSUE TITLE
[Spotify Beta] ...

### ISSUE THREAD

**Issue by toalg** [raycast/extensions#6588]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

#### Error:
```
Error: Bad Request

Q9:oauth.ts:88:10
async As:nowPlayingMenuBar.js:61:1169
nowPlayingMenuBar.js:61:18023
```

### Steps To Reproduce

Mac OS 13.3.1 (a)

**Comment by peduarte** [comment]
Missing Description and Steps to reproduce. Feel free to re-open with the required info!
