### ISSUE TITLE
[Image Modification] Create a new image

### ISSUE THREAD

**Issue by mbackermann** [raycast/extensions#6593]
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

Can we have an option to create a new image instead of changing the original one?

**Comment by SKaplanOfficial** [comment]
Adding this to the next version, with some additional options. Thanks for the suggestion!

<img width="303" alt="Screenshot 2023-06-18 at 21 18 55" src="https://github.com/raycast/extensions/assets/7865925/d3f300f3-ef3a-47db-9c63-806cbb356ac9">

**Comment by mbackermann** [comment]
Thank you very much!
