### ISSUE TITLE
[API Feature Request] Focus specific element in a Form

### ISSUE THREAD

**Issue by mooxl** [raycast/extensions#66]
During the development of Deepcast I noticed that there is no possibility to set a focus on a specific element within a form after the render. This would simplify the input of texts to be translated, since the respective field does not have to be selected separately. 

This could be made possible by specifying the element to be focused on in the Form component, or by setting the focus to true using a boolean in a Form.x child component.

**Comment by PitNikola** [comment]
Good idea, we'll consider adding it soon.

**Comment by sxn** [comment]
available as of **v1.33.0** 😸
