### ISSUE TITLE
inline layout for Form inputs 

### ISSUE THREAD

**Issue by danielo515** [raycast/extensions#660]
**Describe the feature and the current behavior/state.**
Current layout options in forms are quite limiting. Having each input on a separate line is not always the best. 
Allowing to put some form inputs inline could make the form more attractive and make more clear that some fields may be binded. For example, a list were you have to provide a name with an input text and select and icon with a dorpdown. 

**Will this change the current api? How?**
This could be a new layout component or extra option to existing components 

**Who will benefit with this feature?**

Those who want to create a bit more complex forma without making them too long 

**Any Other info.**

**Comment by mattisssa** [comment]
Hey! Thank you for the suggestion. We currently don't support this kind of layout anywhere in the app, since we have a title label aligned on the left from text inputs it feels like such a layout won't work properly. 

What would you try to achieve using this horizontal layout?

**Comment by danielo515** [comment]
Hello @mattisssa 
I took for granted that a different input size would be used, or that the label could be re-positioned to a different place, for example, over the input.

My objective is to build forms that resemble more the kind of data you're entering.
For example, on a list of elements where you have to assign both a name and an icon it is more intuitive if both input fields are on the same line, giving you a visual clue that they belong to the same item.

So for example, instead of this per each item:

![image](https://user-images.githubusercontent.com/2270425/149339099-b26886ca-166d-414d-92ce-3f72385b285d.png)


Do this:

![image](https://user-images.githubusercontent.com/2270425/149339376-aeaea019-6121-4414-a87c-54319c25a97a.png)

**Comment by thomaspaulmann** [comment]
For now, we don't allow multi-column layouts in forms. This is to make sure that our UI stays consistent and users get the same UX across extensions. Having different layouts make it also harder to add new UI capabilities such as help buttons or error states for form items. We might pick this topic up later.
