### ISSUE TITLE
[Todoist] Getting an error when completing a task through Raycast

### ISSUE THREAD

**Issue by bdielman** [raycast/extensions#6614]
### Extension

https://www.raycast.com/doist/todoist

### Description

When either using `cmd` + `k` to bring up the menu to complete or using the keyboard shortcut `cmd` + `shift` + `e` I get the error "Unable to complete task Could not launch command". The task is still marked as completed and it's removed from view in both the extension and Todoist.

<img width="397" alt="Screenshot 2023-05-17 at 10 34 17 AM" src="https://github.com/raycast/extensions/assets/94547/9118b03d-ccaa-464d-beb9-d4da003531b4">

### Steps To Reproduce

1. MacOS Ventura (13.3.1 (a))
2. Run the Todist extension 'Home' to bring up a list today's tasks
3. Complete the task either through `cmd` + `k` to bring up the menu or the keyboard shortcut `cmd` + `shift` + `e`
4. This error appears: `Unable to complete task Could not launch command`

### Current Behaviour

Getting an error when completing a task

### Expected Behaviour

Completes the task without issue

**Comment by bdielman** [comment]
Yep! I did. I didn't realize that needed to be enabled. Enabled it and everything's working now. Thanks!

**Comment by thomaslombart** [comment]
You shouldn't have the error if the menu bar command is disabled though. I'll make some future updates on that. Thanks!
