### ISSUE TITLE
[Bear Notes] Images no longer being displayed in note preview 

### ISSUE THREAD

**Issue by apg-dev** [raycast/extensions#6616]
### Extension

https://www.raycast.com/hmarr/bear

### Description

Raycast search for any Bear note that contains images: the images do not appear in Raycast preview, just a placeholder "Loading ..." which never resolves to an image. I tried restarting both Raycast and Bear to no avail.

Raycast: 1.51.1
Bear: Version 2.0 (11208)

Let me know if any additional information is needed.

Thank you.

### Steps To Reproduce

Raycast search for Bear note with images.

**Comment by apg-dev** [comment]
Any chance this can be investigated?

**Comment by gacharles23** [comment]
I see this same issue: all notes containing images show a "Failed to load image" gray block where the image should be in the preview pane. Did anyone find out the cause of this? I'm on Raycast 1.77.1 and Bear 2.2.1

Thank you,
Grace
