### ISSUE TITLE
[ScreenOCR] Support More Languages.

### ISSUE THREAD

**Issue by Asstiff** [raycast/extensions#6617]
### Extension

https://www.raycast.com/huzef44/screenocr

### Description

It would be so much better if more languages could be supported, or at least could be chosen as primary. It only recognizes English and numbers currently sadly.

### Who will benefit from this feature?

Everyone that uses other than English.

**Comment by Vesely** [comment]
+1 for Czech language 🙏🏻

**Comment by neo773** [comment]
@Asstiff 
Update the Extension I have added support for all the supported languages by Apple's Vision Kit

@Vesely 
> +1 for Czech language 🙏🏻

The author here, unfortunately it's not up to me to support Czech language it's a limitation of Apple's Vision Kit until they update it to support Czech there's nothing I can do.
