### ISSUE TITLE
[Google Chrome] Search History and Search Bookmarks trigger "Google Chrome Not Found" Error

### ISSUE THREAD

**Issue by jaymody** [raycast/extensions#6619]
### Extension

https://www.raycast.com/Codely/google-chrome

### Description

With the Google Chrome extension, when I try the `Search history` command I get the following error:
```
🚨Error: Google Chrome browser is not installed
This extension depends on Google Chrome browser. You must install it to continue.
```

Google chrome is most definitely installed on my machine (via homebrew), in fact the `Search tabs` command works just fine.

The `Search bookmarks` command gives a slightly different error:
```
🚨Error: Google Chrome browser has no bookmarks. Please add some bookmarks to continue using this command.
```

### Steps To Reproduce

Run the `Search history` command. My specific setup is:

- M1 Macbook Pro
- MacOS Version: `13.2.1 (22D68)`
- Chrome Version: `113.0.5672.126 (Official Build) (arm64)`
- Chrome is set to my default browser (installed via homebrew)
- I use a chrome profile that is logged into my google account

Things I've tried:

- reinstalling the chrome extension
- as per [this comment](https://github.com/raycast/extensions/issues/5208#issuecomment-1458957250), also tried uninstalling the extension and reinstalling via the browser store
- restarting my computer
- uninstalling and re-installing chrome
- uninstalling and re-installing raycast
- tried switching to a different chrome profile

**Comment by neversmiler** [comment]
me  too

**Comment by jaymody** [comment]
I also tried installing a different version of Chrome (version 112) however I still had the same issue.

**Comment by neversmiler** [comment]
https://www.raycast.com/raycast/browser-bookmarks

I just found an alternative and hope that can help you.

**Comment by neversmiler** [comment]
和之前设置同样的快捷键，可以完美替代。

**Comment by neversmiler** [comment]
The same shortcut keys as before can be perfectly replaced.

**Comment by neversmiler** [comment]
And this plugin can also choose other browsers, very nice

**Comment by jaymody** [comment]
That plugin only supports bookmarks, the main functionality I'm looking for here is the ability to search through my Chrome History.

**Comment by jaymody** [comment]
Just bumping this as this issue is still not resolved.
