### ISSUE TITLE
Option to disable the search input on the List component 

### ISSUE THREAD

**Issue by danielo515** [raycast/extensions#662]
**Describe the feature and the current behavior/state.**

The list is very powerful, but it seems to be heavily focused on just a single use case. 
Filtering the list is not always required and having not needed  UI elements can be distracting. 
Adding a boolean to disable the search bar will solve this situations. 

**Will this change the current api? How?**

Should be a new addition to the List component 

**Who will benefit with this feature?**
Flows that are not that usual and don't need the search bar 

**Any Other info.**

**Comment by mattisssa** [comment]
Hey @danielo515! Actually, we don't have such a list anywhere in the Raycast since if you are using a list it's much easier to navigate there using the search bar instead of pressing keys down/up. In the case, you have a list with some amount of static items it probably could be worth using the Detail screen with an action panel for it. But I'm not sure about the case.

How would you use such a component without a search bar, do you have exact examples of extensions where it would be useful?

**Comment by danielo515** [comment]
Hello @mattisssa 

I am building a plugin that has a different interaction mechanism that does not require using arrow keys, but it doesn't require to filter either.
It is a list that allows you to change the status on the items on the list to build a new one, it doesn't require filtering because you are supposed to update all the items on the list.

It is on an early stage, but here is a video of the first prototype:

![Kapture 2022-01-14 at 14 05 11](https://user-images.githubusercontent.com/2270425/149520601-ff25db73-e308-4445-84e6-39d35ee30e99.gif)

**Comment by mattisssa** [comment]
It looks a bit confusing to me but... Doesn't it more convenient to type "U..." and then change the state of the item with UK-58? I think Search bars don't really interfere here and hiding it won't help a lot, because you will have that top space anyway because of back button.

**Comment by thomaspaulmann** [comment]
For now we don't have plans to disable the searchbar in our list components. As outlined, this is a fundamental part of Raycast's UX and users are used to search through lists. Later we might add ways to solve use cases that don't have many list items.

**Comment by danielo515** [comment]
So this is now possible using the `enableFiltering` option, which looking at the git commits was added [just 4 months after this issue was closed](https://github.com/raycast/extensions/commit/339a2773e374e1f45a9835d19dbab50ee70c4292).
What I nice way to discourage people to ask for API improvements, by saying that their suggestions doesn't make sense, that are confusing and that they don't fit in the plans, and then implement it 4 months later just because one of your extension ideas needs it, and then it makes all the sense.

**Comment by thomaspaulmann** [comment]
To clarify, `enableFiltering` keeps the search bar, it just disabled the automatic filtering.

**Comment by danielo515** [comment]
And that is exactly what I wanted 👍 
Because I want to use it as an input to add to the list, not to filter it. Perfect fit
