### ISSUE TITLE
Add support for rich-text editor UI components

### ISSUE THREAD

**Issue by StevenRudenko** [raycast/extensions#6624]
### Description

Could you please add support for any rich-text editor UI components like:
    * CKEditor 5
    * Quill 1.3
    * Slate
    * TinyMCE 5 & 6

### Who will benefit from this feature?

It may open the ability to create extensions to work with texts, like saving notes and styling text in a clipboard.

I have already a couple of ideas for it:
* Adding Grammarly API to help with grammar issues: https://developer.grammarly.com/docs/#supported-text-editors
* Highlighting information with custom patterns (like card numbers, emails, etc.)

**Comment by thomaslombart** [comment]
Hey there, it's unlikely we'll ship that as we want to have control over our components, and it'll probably be complex and overkill to integrate that into our API. Thanks for the feature request though! 😊
