### ISSUE TITLE
[NeteaseMusic] Doesn't Work in English Environment

### ISSUE THREAD

**Issue by Coffee-Water** [raycast/extensions#6630]
### Extension

https://www.raycast.com/chyroc/netease-music

### Description

Seems like the extension won't work when system languages is set to any other languages other than Chinese.
![SCR-20230518-josz](https://github.com/raycast/extensions/assets/73344728/b4a7f17f-8645-48bd-b5d7-69ee91eb262b)

### Steps To Reproduce

1. System language is configured as English;
2. Run any of the commands in the extension;
3. The command won't be performed and an error message pops up as 
> execution error: System Events got an error: Can't get menu bar item "控制" of menu bar 1 of process "Nete...

**Comment by Xiang-Pan** [comment]
There is no solution currently, the automatic close is stupid.

**Comment by yuercl** [comment]
Just found a workaround solution. You can customize the language settings for specific apps on your Mac without changing the system language. Go to "System Preferences" > "Language & Region." At the very bottom, add Netease Music to the customization list and set its language to Chinese. Now the plugin should work as intended.

刚刚找到了一个解决方法。您可以在 Mac 上自定特定 App 的语言设置，而无需更改系统语言。转到“系统偏好设置”>“语言和地区”。在最底部，将网易音乐添加到自定义列表中，并将其语言设置为中文。现在插件应该按预期工作。

**Comment by Xiang-Pan** [comment]
谢谢!

**Comment by sillyguodong** [comment]
> Just found a workaround solution. You can customize the language settings for specific apps on your Mac without changing the system language. Go to "System Preferences" > "Language & Region." At the very bottom, add Netease Music to the customization list and set its language to Chinese. Now the plugin should work as intended.
> 
> 刚刚找到了一个解决方法。您可以在 Mac 上自定特定 App 的语言设置，而无需更改系统语言。转到“系统偏好设置”>“语言和地区”。在最底部，将网易音乐添加到自定义列表中，并将其语言设置为中文。现在插件应该按预期工作。
> 
> [chyroc/netease-music-controller#1](https://github.com/chyroc/netease-music-controller/issues/1)

thank you! that works!
