### ISSUE TITLE
[Lark Documents] ...

### ISSUE THREAD

**Issue by Taoaozw** [raycast/extensions#6632]
### Extension

https://www.raycast.com/tmk/lark

### Description

I am using both lark and Flybook, one as an individual and one as a business, can you add a function to switch accounts, or is there any way to log in to both accounts

### Who will benefit from this feature?

who both use lark and flybook

**Comment by tmkx** [comment]
what's flybook

**Comment by Taoaozw** [comment]
> 

飞书😂

**Comment by Taoaozw** [comment]
> what's flybook

飞书😂

**Comment by tmkx** [comment]
sorry, there is currently no way to log in with two accounts. <img width="20" alt="glance" src="https://github.com/raycast/extensions/assets/13805071/8270678e-e794-445b-a66a-964f64ebd295">

**Comment by tmkx** [comment]
Just like the official Raycast GitHub extension

**Comment by Taoaozw** [comment]
> sorry, there is currently no way to log in with two accounts. <img alt="glance" width="20" src="https://user-images.githubusercontent.com/13805071/239152538-8270678e-e794-445b-a66a-964f64ebd295.png">

well, it's too sad

**Comment by Taoaozw** [comment]
> Just like the official Raycast GitHub extension

thanks for your reply

**Comment by Taoaozw** [comment]
@raycastbot close this issu

**Comment by Taoaozw** [comment]
@raycastbot close this issue

**Comment by Taoaozw** [comment]
> Just like the official Raycast GitHub extension

Is it possible to release a separate Flybook extension

**Comment by tmkx** [comment]
You can clone the repo and run extension in local env, it can coexist with the published one.

**Comment by Taoaozw** [comment]
> 

Ok, thanks again
