### ISSUE TITLE
[Jira] My filter command is stopped working

### ISSUE THREAD

**Issue by jijo-nl** [raycast/extensions#6634]
### Extension

https://www.raycast.com/raycast/jira

### Description

Error: Rendering failed:
Missing required component property "title"

It was working fine till yesterday, today morning onwards started failing.

### Steps To Reproduce

1. Run command MyFilter

### Current Behaviour

It's shows something went wrong

### Expected Behaviour

List out the default selected filter stories, defects, epics.

**Comment by thomaslombart** [comment]
Can you uninstall and install back the extension and let me know if you still run into the issue?

**Comment by jijo-nl** [comment]
Thanks, it's working.


Thanks & Regards,
Jijo Alexander


On Thu, May 18, 2023 at 12:19:48, Thomas Lombart ***@***.******@***.***>> wrote:

Can you uninstall and install back the extension and let me know if you still run into the issue?

**Comment by boaz-wiesner** [comment]
Hi,

I uninstalled and reinstalled and still getting this same error when accessing "My Filters". It's worth noting that other commands seem to be functioning, but my workflow is completely based around filters 😞

**Comment by Dirdmaster** [comment]
I am facing the same issue. 
I have attempted to uninstall and reinstall the extension, but now I am unable to log in to Jira through the extension. 

The website "https://jira.oauth-proxy.raycast.com" keeps loading indefinitely. 

After several attempts, I managed to log in, but I instantly receive a forbidden error whenever I try to execute any Jira command.

**Comment by thomaslombart** [comment]
@Dirdmaster Does `Open Issues` also fail for you?

**Comment by thomaslombart** [comment]
Maybe there are network restrictions for you? The extension has to go through the jira.oauth-proxy.raycast.com website to authenticate the user.

**Comment by Dirdmaster** [comment]
I don't think it's related to my network. It actually works from time to time. Most of the time, jira.oauth-proxy.raycast.com is unaccessible for me

I have tried to use the extension with a couple internet connections and different devices, but the instability persists. Is it possible that jira.oauth-proxy.raycast.com itself is unstable?

**Comment by thomaslombart** [comment]
It doesn't seem unstable, I've tried logging in and logging from the extension out several times and it works fine 🤔

**Comment by Dirdmaster** [comment]
For now I've decided to roll back to the legacy jira extension which works perfectly fine for me

Could my issue be linked to the new authorization flow? How do the two how do they differ from each other?

**Comment by thomaslombart** [comment]
Probably. The legacy Jira extension is native (so using Swift) and doesn't have to make use of a proxy like the new one. I'll try to investigate that, but I'm not sure I can find something since the authorization flow doesn't differ much from all of the other flows in our extensions (GitHub, Linear, Zoom, etc.) that don't fail...

**Comment by boaz-wiesner** [comment]
@thomaslombart Is there some kind of more verbose logging that I can enable to help debug this? It's very repeatable and super strange. All other things work, just My Filters does not.

**Comment by Dirdmaster** [comment]
Interesting, I did some testing and I'm facing the same issue with linear
![image](https://github.com/raycast/extensions/assets/48012615/f8866132-57ce-436d-8091-2d0f1041d1ef)

What would be the required steps to further debug this issue?

**Comment by thomaslombart** [comment]
@boaz-wiesner There's no option to enable more verbose logging. It's probably a matter of Jira returning corrupted date or empty titles for some reasons. I'll try to take a stab at it this week but not sure I'll have enough bandwidth for that. If you want, you can fork the extension and try to fix it locally, it might just be a matter of providing a default title to the dropdown's filter if it's empty.

**Comment by thomaslombart** [comment]
@Dirdmaster Strange indeed... Are you also having the issue with other other proxies such as on our other extensions: Asana, GitHub, Google Workspace, Zoom, etc.?

**Comment by mjvdw** [comment]
I had a go at forking the extension and running locally. Works perfectly locally (good work around in the meantime I guess), but the issue is still there with the production version.

**Comment by thomaslombart** [comment]
@Dirdmaster Are you in the [Slack community](http://raycastcommunity.slack.com/)? It'd be better to debug things out there to keep the issue relatively clean.

**Comment by thomaslombart** [comment]
@mjvdw Is the local version still working out for you? It seems the error occurs after some uses, so maybe installing the local version worked initially but not anymore.

**Comment by thomaslombart** [comment]
FYI, I've shipped a fix that may solve this issue but not sure since I'm basically debugging it blindly 😅 
Could one of you test it out and let me know if you still have the issue (cc @boaz-wiesner @jijo-nl) @mjvdw)?

**Comment by boaz-wiesner** [comment]
@thomaslombart Works! Got the update automatically, didn't need to install/uninstall.
Thanks so much!
