### ISSUE TITLE
[TempMail] ...

### ISSUE THREAD

**Issue by Arnav12S** [raycast/extensions#6639]
### Extension

https://www.raycast.com/Joshlucpoll/tempmail

#### Error:
```

```

### Steps To Reproduce

1. On raycast on macbook pro with macOS 13.4
2. View Email is not working.

**Comment by Joshlucpoll** [comment]
Hey @Arnav12S, is this with all emails you try to open or just one?

**Comment by Joshlucpoll** [comment]
Hmm, do you have the specific error message @Arnav12S ? Also have you tried to reset TempMail using the 'Reset TempMail' command? That might solve the problem

**Comment by Joshlucpoll** [comment]
@Arnav12S I've pushed a new release for TempMail, can you update the extension and let me know if your problem is fixed? Thanks
