### ISSUE TITLE
[Google Translate] Error while using transator 

### ISSUE THREAD

**Issue by anisim101** [raycast/extensions#6647]
### Extension

https://www.raycast.com/gebeto/translate

### Description

TypeError: Cannot read properties of null (reading '1')
Url: https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=-7579761867446382414&bl=boq_translate-webserver_20230516.06_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=8129&rt=c

index.js:90:21
async b0:translate-form.js:28:11660

### Steps To Reproduce

1. Open extension 
2. paste / write input request text
3. // error

**Comment by gebeto** [comment]
https://github.com/raycast/extensions/pull/6666
