### ISSUE TITLE
[Get SSH Key] Can't select my ssh key

### ISSUE THREAD

**Issue by iwex** [raycast/extensions#6651]
### Extension

https://www.raycast.com/Theon/get-ssh-key

### Description

Hello!
When I select "Copy SSH Key" it shows me an error:
![CleanShot 2023-05-19 at 02 26 03](https://github.com/raycast/extensions/assets/4510068/f5897ce7-5a53-427c-b7b0-6349cff329cd)

Error is "Could not load command"

I tried to fix it, so I cloned the repo and imported this as a new extension. In this case, I don't have an error.

Also, you should remove this line https://github.com/raycast/extensions/blob/4b9653c437b484ee63541e6cbb33ef6167f787db/extensions/get-ssh-key/src/index.tsx#L18 as it hides raycast window.

### Steps To Reproduce

1. Open raycast
2. Select `Copy SSH Key`

### Current Behaviour

Error

### Expected Behaviour

Show list of ssh keys

**Comment by iwex** [comment]
offtopic: how can I clone only a particular extension and not all 3GB repo?

**Comment by pernielsentikaer** [comment]
You can use the command `Fork Extension` when you have an extension from the store installed

![Raycast-Kmixq7jn@2x](https://github.com/raycast/extensions/assets/38033107/0853b0f6-efc2-4b4e-b82d-db609367d7dd)
