### ISSUE TITLE
[Spotify Beta] cannot connect to spotify anymore

### ISSUE THREAD

**Issue by mettin** [raycast/extensions#6659]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

#### Error:
```
Error: Bad Request

e5:oauth.ts:88:10
async Ro:search.js:47:1169
search.js:47:18021
```
<img width="886" alt="Screenshot 2023-05-19 at 08 57 03" src="https://github.com/raycast/extensions/assets/1436111/37113ac7-9369-4db4-90dc-0cf437beb5c1">

### Steps To Reproduce

🤷‍♂️

### Current Behaviour

see screenshot

### Expected Behaviour

I can use the app

**Comment by peduarte** [comment]
Oh weird, would you mind trying Logging out and logging back in? You can do that in Preferences > Extensions. 

Meanwhile I'll look into this

**Comment by kcaashish** [comment]
I faced the same thing but with Your Library, while other commands worked.

**Comment by mettin** [comment]
@peduarte Logging out/in works, thanks! Let me know if I can do anything else to help with debugging
