### ISSUE TITLE
[Extension Bug] CoinMarketCap "Refresh Crypto List" command doesn't seem to work (anymore)

### ISSUE THREAD

**Issue by tumispro** [raycast/extensions#666]
# Extension – [CoinMarketCap Crypto Search](https://github.com/raycast/extensions/tree/main/extensions/coinmarketcap-crypto-crawler*)

Author: SonicSpark

## Description

Adding some coins to favorites and then using the command "Refresh Crypto List" results in an error: 

> Error: Request failed with status code 403

## Steps To Reproduce

1. Add some coins to favorites using "Search Crypto" and then "Add To Favorites"
2. Run the "Refresh Crypto List" command

## The current behavior

403 error

## The expected behavior

List of favorites with current price

### Raycast version
Version: 1.27.0

**Comment by mattisssa** [comment]
Thank you for creating a separate issue! 👏 
cc @moojing @Yukaii

**Comment by tumispro** [comment]
Might I suggest to perhaps remove the command entirely and add it as a command to the Search Crypto command? Imo way more clean and useful.

**Comment by mattisssa** [comment]
@tumispro sure, feel free to open a PR with that. I think you can do this right in [existing extension](https://github.com/raycast/extensions/tree/main/extensions/coinmarketcap-crypto-crawler*), we can mention the author of the extension if it's fine with him. Seems like he has been inactive for a while so I think it's good to give the extension a fresh update

**Comment by moojing** [comment]
@tumispro Do you mean make the "refreshing" function into an `action` instead of a command?

**Comment by moojing** [comment]
thank you for the response @tumispro, if you found other problems or got some new idea about the extension you could let me know! I'll keep improving it in my free time 😆

**Comment by moojing** [comment]
@tumispro I've updated the refresh command and [made it into an action now](https://github.com/raycast/extensions/pull/883).

**Comment by tumispro** [comment]
Awesome!
