### ISSUE TITLE
[Kill Process] Command to relaunch a process

### ISSUE THREAD

**Issue by delorfin** [raycast/extensions#6660]
### Extension

https://www.raycast.com/rolandleth/kill-process

### Description

I often use this extension when I need to use an app, but it's not responding (e.g. Spotify hangs frequently after the computer wakes up). So I kill the process and then launch the app again.

To make this easier and faster, maybe the Kill Process extension could feature a separate command for this? With exactly the same interface, but after a process is killed, it gets launched again automatically.

### Anything else?

The challenge could be in identifying which app the process belongs to.

One option could be to use something similar to [this script](https://github.com/sjitech/mac_list_windows_pids), which identifies the window name for each process. Then we use the window name to find the app.

Not all apps have windows, or for some apps, windows could be closed at the moment. This needs more investigation, but even without this at first, the relaunch command would still be useful.

**Comment by rolandleth** [comment]
@delorfin I don't want to use accessibility features for this extension, and reading window titles most likely requires. If you find another way to do it, I am open to suggestions.
