### ISSUE TITLE
[Tuya Smartlife] -  Add Scenses  

### ISSUE THREAD

**Issue by avs-sin** [raycast/extensions#6675]
### Extension

https://www.raycast.com/andresmorelos/tuya-smart

### Description

We're requesting to add the feature to activate Scenes from Ratcast! This will be a great addition and make our lives easier. 

### Who will benefit from this feature?

everyone.

**Comment by AndresMorelos** [comment]
Looking on tuya smart documentation.

**Comment by AndresMorelos** [comment]
@avs-sin I read the documentation and know how to implement it. I'm looking for a way to add an SQLite database here to save all information needed.

This change will take a while to be implemented.
