### ISSUE TITLE
[JetBrains Toolbox Recent Projects] Continuous loading when using "Search Recent Projects"

### ISSUE THREAD

**Issue by irozum** [raycast/extensions#6680]
### Extension

https://www.raycast.com/gdsmith/jetbrains

### Description

When using the "Search Recent Projects" command, it just loads forever and doesn't show any result or errors. I've already tried changing tools and shell scripts director path but it still didn't help.

### Steps To Reproduce

1. Install JetBrains Toolbox.
2. Install this extension
3. Try the command above

**Comment by gdsmith** [comment]
@irozum can you try the debugging steps in #4483 and let me know the outputs?

**Comment by irozum** [comment]
Hi George,

Igor is no longer with SPC. What is the below regarding – is there an issue with the Google Chrome Extension?

Thanks,

Monish Bhambhani | Senior Product Manager
SPC Card | spccard.ca | 999 Edgeley Blvd Unit 1 | Vaughan, Ontario L4K 5Z4

From: George ***@***.***>
Date: Saturday, May 20, 2023 at 3:41 AM
To: raycast/extensions ***@***.***>
Cc: Igor Rozum ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [raycast/extensions] [JetBrains Toolbox Recent Projects] Continuous loading when using "Search Recent Projects" (Issue #6680)

@irozum<https://github.com/irozum> can you try the debugging steps in #4483<https://github.com/raycast/extensions/issues/4483> and let me know the outputs?

**Comment by gdsmith** [comment]
@irozum this is a comment in a github issue. Igor raised an issue about a JetBrains plugin I wrote for Raycast. Is this still Igor's GitHub account and it's  just linked to the wrong email address or can we close this issue down?

**Comment by irozum** [comment]
Hi @gdsmith, yeah, the notifications were linked to a different email account. 

The problem was that my PyCharm app was manually installed not through the Toolbox. But after I installed it through there, the extension started to work.

Thanks for the help.

**Comment by irozum** [comment]
@raycastbot close this issue
