### ISSUE TITLE
[Vault Manager] Unable to list kv v2 secrets 

### ISSUE THREAD

**Issue by shaoye** [raycast/extensions#6682]
### Extension

https://raycast.com/fonimus/vault-manager

#### Error:
```
Error: no handler for route "secret/metadata/". route entry not found.
    at p (/Users/sy/.config/raycast/extensions/ae0b3588-18b8-45b8-801a-e236beebbd5e/vault.js:78:26447)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E0 (/Users/sy/.config/raycast/extensions/ae0b3588-18b8-45b8-801a-e236beebbd5e/vault.js:117:222)
    at async Object.<anonymous> (/Users/sy/.config/raycast/extensions/ae0b3588-18b8-45b8-801a-e236beebbd5e/vault.js:125:8582)
```

### Steps To Reproduce

We only have one kv Secret engine called `my-secrets` in our vault. Vault Manager is unable to list the secrets under it.

It would be great if we can support it and specify the secret path to like `/my-secrets`

**Comment by fonimus** [comment]
Hello @shaoye, if I understand well, your request is to be able to specify a different "root" path than / ?

Can you give me steps to reproduce it and especially test it in development mode ? 
(docker image or something)

Thanks

**Comment by shaoye** [comment]
Yes, it's very easy to reproduce, just start the vault docker in development mode and create a new kv engine

```
 docker run --cap-add=IPC_LOCK -p 8200:8200  --name=dev-vault hashicorp/vault
 ```

<img width="720" alt="Screenshot 2023-05-23 at 2 10 38 PM" src="https://github.com/raycast/extensions/assets/15662193/f8199d45-ba27-454b-86c0-aa25831b3214">

<img width="651" alt="Screenshot 2023-05-23 at 2 13 22 PM" src="https://github.com/raycast/extensions/assets/15662193/b5c31dbc-2a43-45f7-96f5-fc398602ff69">

**Comment by pernielsentikaer** [comment]
Closing as merged, feel free to comment if it's not working out 🙂
