### ISSUE TITLE
[Bitwarden Vault] Error upon launching because Raycast can't fetch the frontmost application.

### ISSUE THREAD

**Issue by ibll** [raycast/extensions#6695]
### Extension

https://www.raycast.com/jomifepe/bitwarden

#### Error:
```
Error: Could not retrieve frontmost application

process.processImmediate:timers:471:21
```

<img width="881" alt="image" src="https://github.com/raycast/extensions/assets/61601241/7e157852-bda2-4dc7-8247-004d7ca44709">

Works just fine when switching to another app.

### Steps To Reproduce

1. Open a program in Wine, mine was in Porting Kit. It doesn't really register as a normal macOS window.
2. Open `Search Vault` command.
3. Error pops up.

### Current Behaviour

I try to use the Search Vault command and it has an error upon loading because I have a strange program focused.

### Expected Behaviour

I try to use the Search Vault command and it takes the error in stride, because I don't imagine the extension really needs to know what app I have focused to copy a password.

**Comment by jomifepe** [comment]
Thanks for reporting, [fix is on the way](https://github.com/raycast/extensions/pull/6671).

**Comment by jomifepe** [comment]
Should be fixed now, give it a try @ibll
