### ISSUE TITLE
[Spotify Beta] ... menubar player (error code 2) not working

### ISSUE THREAD

**Issue by agrarico** [raycast/extensions#6696]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

### Description

Enabling menu bar player doesn't work:

Error:

Reason: Code: 2 (Unhandled Extension Rejection)
Domain: commands
Time: 09:27:52.913

![image](https://github.com/raycast/extensions/assets/56153618/a1d20fd4-d31e-4d32-89ea-b3966fa5f2ea)

### Steps To Reproduce

On my other macbook pro it does work.

I have two macbooks. It works on this one:
Macbook 16 2.6Hz 6-core I7 (16gb)

And I get the error on my M1 13" Macbook (8gb)

Both running the latest MacOS Ventura 13.3.1 (a).

**Comment by peduarte** [comment]
Related: https://github.com/raycast/extensions/issues/6522

**Comment by peduarte** [comment]
Will look into it!

**Comment by peduarte** [comment]
It looks like this can happen when tokens are not refreshed properly.

Could you please check that Raycast is still an authorized Spotify App in your [account settings](https://www.spotify.com/uk/account/apps/)? 

Then, could you open Spotify Preferences in Raycast and click "logout" (see screenshot below)

![(ಠ ›ಠ) — @peduarte — 4O1uwbG3002016@2x](https://github.com/raycast/extensions/assets/372831/32cd73f4-db70-4b70-a0c6-6fd4aa957f48)

Then finally, can you try and authorize again, and let me know if that works?

Meanwhile, Im gonna do some work to automatically prompt a re-auth if this happens

**Comment by peduarte** [comment]
I pushed a fix, but we also need to push an app wide fix. it should be much better now (hopefully), and if you do seen the red triangle, click on it to open raycast, then hit "reload".

**Comment by agrarico** [comment]
Seems to work again. Thanks!
