### ISSUE TITLE
[TempMail] ...

### ISSUE THREAD

**Issue by MKReyesH** [raycast/extensions#6697]
### Extension

https://www.raycast.com/Joshlucpoll/tempmail

### Description

When you try to open an email, you get "Something went wrong message".

<img width="862" alt="Captura de Pantalla 2023-05-21 a las 11 40 43" src="https://github.com/raycast/extensions/assets/33583170/9857ea43-2e86-46c3-8359-5d68673e180e">

<img width="862" alt="Captura de Pantalla 2023-05-21 a las 11 40 49" src="https://github.com/raycast/extensions/assets/33583170/dff21ff9-aac3-46f8-a61e-363b291ddb32">

```
TypeError: Right-hand side of 'instanceof' is not an object

Y6:message.tsx:135:37
Nr:index.js:6:2490
    at ray-navigation-stack
_o:index.js:6:2088
```

### Steps To Reproduce

1. Open "Open Mailbox" in Raycast
2. Select an email
3. Hit ↵

**Comment by Joshlucpoll** [comment]
@MKReyesH I've pushed a new release for TempMail, can you update the extension and let me know if your problem is fixed? Thanks

**Comment by MKReyesH** [comment]
Hello, thanks for the update. I do not get the "Something went wrong" error anymore, but I still cannot read the emails inside Raycast (I have to open them using the browser).

<img width="774" alt="Captura de Pantalla 2023-06-08 a las 21 55 50" src="https://github.com/raycast/extensions/assets/33583170/75f6e80d-1a39-42b1-bbe9-b83e704baff7">

Do you have any idea why the email can be read from a local .html file in browser, but cannot be read from inside Raycast? Are you able to reproduce this behaviour? Thanks.
