### ISSUE TITLE
Add the possibility to directly open the URL of a Bitwarden item

### ISSUE THREAD

**Issue by afanjul** [raycast/extensions#670]
# Extension – [Bitwarden](https://github.com/raycast/extensions/tree/main/extensions/bitwarden)

Author: @pomdtr

  Add the possibility (maybe using Command+Enter) to -not only copy the item URI- but open the URL of the item directly in the browser (as Bitwarden does from its extension).

For users of Bitwarden

**Comment by pomdtr** [comment]
Hey @afanjul, I have added this to my personal backlog
