### ISSUE TITLE
[Quick Search] 可否加入谷歌学术快捷搜索指令

### ISSUE THREAD

**Issue by FLIER001** [raycast/extensions#6701]
### Extension

https://www.raycast.com/iwfan/quick-search

### Description

可否加入谷歌学术快捷搜索指令？

进一步的，是否可以开放自定义设置，通过用户填写`url`+`{queary}`的方式实现

感谢作者！

**Comment by iwfan** [comment]
Hi @FLIER001 Sorry for the slow response.

You can use the [Quick Links](https://manual.raycast.com/quicklinks) feature to customize search URL.

<img width="1000" alt="Raycast 2023-07-03 at 11 44 12" src="https://github.com/raycast/extensions/assets/28853200/5eb5cf3c-4ecf-4651-a618-767694abf016">


@raycastbot close this issue
