### ISSUE TITLE
[1Password] - Can only login and use passwords from 1 account

### ISSUE THREAD

**Issue by oliver-platt** [raycast/extensions#6713]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Many of us will have 2 accounts -  if you use 1password for work, 1password actually give everyone a free account to use for their personal passwords. It would obviously be much more useful if I could access passwords from both my personal and work account via Raycast.

### Who will benefit from this feature?

Everyone with 1password for work and home

**Comment by jedelson-pagerduty** [comment]
commenting to reopen since I've submitted a PR for this
