### ISSUE TITLE
[Spotify Beta] TypeError in Your Library: Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by kcaashish** [raycast/extensions#6725]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'url')

Ka:TrackListItem.tsx:15:2
    at ray-list-section
os:index.js:20:18779
Li:yourLibrary.js:67:6016
```
<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/31175326/8ea5ed51-e65b-4985-9414-fc3d2847f2cd">

### Steps To Reproduce

1. Open raycast.
2. Login to Spotify Beta.
3. Open `Your Library` command.

### Current Behaviour

Giving error. `Something went wrong`

### Expected Behaviour

Should list the contents of my library.

**Comment by peduarte** [comment]
Thanks, looking into it!
