### ISSUE TITLE
[Spotify Beta] Don't pop Spotify window open when something is played

### ISSUE THREAD

**Issue by kcaashish** [raycast/extensions#6726]
### Extension

https://www.raycast.com/mattisssa/spotify-beta

### Description

In the earlier extension, `Just Play` would start playing a song with Spotify in the background, it would not pop the Spotify window open, which it does right now either you `Just Play` or `Search` and play. It would be great to just start playing the song with Spotify open in the background without the window pop up.

### Who will benefit from this feature?

I am sure everyone!

**Comment by peduarte** [comment]
We're looking into this, to see if its possible with AppleScript. FWIW it should only happen when it uses AppleScript fallback, not when using the API
