### ISSUE TITLE
[Harvest] Error: Could not launch command  process.processImmediate:timers:471:21

### ISSUE THREAD

**Issue by edmundcwm** [raycast/extensions#6730]
### Extension

https://www.raycast.com/eluce2/harvest

#### Error:
```
Error: Could not launch command

process.processImmediate:timers:471:21
```

Tried reinstalling the extension but the problem still persists.

### Steps To Reproduce

1. Open "Today's Timesheet"
2. The "Something Went Wrong" error message appears

![GIF Recording 2023-05-23 at 7 19 37 AM](https://github.com/raycast/extensions/assets/13222067/4da74f2b-ef5e-4ca3-b338-19f9bc13acd8)

### Current Behaviour

On MacOS 13.3.1, when opening 'Today's Timesheet' I'm getting the "Something Went Wrong" error message.

### Expected Behaviour

On MacOS 13.3.1, when opening 'Today's Timesheet' I should be presented with the list of timesheet entries.

**Comment by eluce2** [comment]
Thanks for reporting this. Are you able to share the debug information from the cmd+K menu when the error shows up?

**Comment by eluce2** [comment]
I'm sorry, I must have missed it while reading on my phone. I will look into this right away

**Comment by edmundcwm** [comment]
Appreciate the quick fix @eluce2! It's working for me now! 🎉  And a huge thanks for this awesome extension!
