### ISSUE TITLE
[ChatGPT] Error: read ECONNRESET  TLSWrap.onStreamRead:stream_base_commons:217:20

### ISSUE THREAD

**Issue by Mixologist1337** [raycast/extensions#6731]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Error: read ECONNRESET

TLSWrap.onStreamRead:stream_base_commons:217:20

### Steps To Reproduce

Error: read ECONNRESET

TLSWrap.onStreamRead:stream_base_commons:217:20

### Current Behaviour

can't use

**Comment by Nauxscript** [comment]
refer to #6688 , maybe the same problems;
if not, we need more infomation about it, your environment network, version, proxy, etc.

**Comment by Nauxscript** [comment]
@raycastbot close this issue

**Comment by shichongrui** [comment]
Can anyone tell me how I can have @raycastbot stop pinging me on these issues?
