### ISSUE TITLE
[ray.so] R language support

### ISSUE THREAD

**Issue by jimjam-slam** [raycast/extensions#6735]
### Description

Hi there! I'm really enjoying using [ray.so](https://ray.so) (both through the website and the RayCast extension). I was hoping you'd consider adding R as a supported language for syntax highlighting.

### Who will benefit from this feature?

R is still a fairly popular language (presently [16th on TIOBE](https://www.tiobe.com/tiobe-index/), for example) with a strong culture of education, so there are plenty of folks who'd benefit from being able to share code snippets in this language.

### Anything else?

I'm not super familiar with syntax highlighting standards and am not familiar enough with ray.so to say whether its ability to support R is constrained upstream, but in case it's useful, here are the syntax highlighting definitions for R in its widely-used VSCode extension:

https://github.com/REditorSupport/vscode-R/blob/master/syntax/r.json

Thanks very much!

**Comment by mathieudutour** [comment]
Could you send this feedback feedback+rayso@raycast.com instead? This repo isn't about ray.so
