### ISSUE TITLE
[World Clock] Sort timezones

### ISSUE THREAD

**Issue by icatalina** [raycast/extensions#6738]
### Extension

https://www.raycast.com/koinzhang/world-clock

### Description

I'd like to be able to sort the timezones

### Who will benefit from this feature?

All users of the World Clock extension

**Comment by koinzhang** [comment]
Hi @icatalina I have submitted a PR to update this extension #6842
- Starred time zones support sorting

Now I'm going to close this Issue, if you have other questions, feel free to give feedback
@raycastbot close this issue
