### ISSUE TITLE
Jira Search with numbered keys only

### ISSUE THREAD

**Issue by jiserra** [raycast/extensions#674]
# Extension – [Raycast JIRA Search](https://github.com/raycast/extensions/tree/a6d9ac115da2ebf4c1b41f710ea4b4b46a5b3f7c/extensions/jira-search)

Author: @svenwiegand 

**Describe the feature and the current behavior/state.**
Currently, the `Search Issue` command works well for searching a complete key, but I would like it to work without the need to enter the letters. Instead of forcing me to search for `ABC-1234` I would like to search for just `1234` and that can find both `ABC-1234` and `XYZ-12345`.

**Who will benefit with this feature?**
Everyone that doesn't want to write the letters of the key first!

**Any Other info.**
I currently have a script command to replace this, but I would love it in an extension with results. Thanks a lot!

**Comment by nesl247** [comment]
https://jira.atlassian.com/browse/JRACLOUD-74476 - seems to be the upstream ticket to track this possibility.

**Comment by nesl247** [comment]
While this requires something upstream, can we keep this open though?
