### ISSUE TITLE
[Browser Bookmarks] Most of the bookmarks don't show favicons

### ISSUE THREAD

**Issue by irozum** [raycast/extensions#6742]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

Favicons aren't displayed for some of the bookmarks while they are shown in the browser. It was working before but something happened and it broke.

### Steps To Reproduce

1. Install the extension
2. See that not all bookmarks have favicons attached to them.

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue #6590, so I'll mark it as such.
