### ISSUE TITLE
[Steam] ...

### ISSUE THREAD

**Issue by nukesean** [raycast/extensions#6744]
### Extension

https://www.raycast.com/KevinBatdorf/steam

### Description

It would be nice to be able to display prices in the desired currency, as all prices seem to be shown in CDN$ currently.

### Who will benefit from this feature?

Everyone outside of Canada.

**Comment by KevinBatdorf** [comment]
That's unfortunately just how the Steam API works. It just arbitrarily sends back the wrong data. Wrong language too.

In my experience it just randomly does it though but if I try again in a minute it's back to normal.
