### ISSUE TITLE
[Figma File Search] ...

### ISSUE THREAD

**Issue by nevertoday** [raycast/extensions#6746]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

#### Error:
```

```

### Steps To Reproduce

Reason: Code: 2 (Unhandled Extension Rejection)
Domain: commands
Time: 01:11:44.055

**Comment by GLaDO8** [comment]
@nevertoday can you provide more context on what triggered the error?

**Comment by michaelwschultz** [comment]
Seems like this issue was mistakenly posted. Either way there isn't enough information. This should be closed.

**Comment by michaelwschultz** [comment]
@raycastbot close this issue
