### ISSUE TITLE
[Beeminder] Making goals list appear faster

### ISSUE THREAD

**Issue by clouedoc** [raycast/extensions#6754]
### Extension

https://www.raycast.com/vivgui/beeminder

### Description

**Currently**, it takes a long time to load the goal list.
I do not really use the extension to know more about the status of my goal, but more to quickly add data.

E.g.: I just added an Anki card... Let me pull up the Beeminder Raycast command and add +1!

https://github.com/raycast/extensions/assets/13921610/804335e6-eb0f-4509-9a5b-d3e83de916bb

**Desired behavior:**

The goal list appears instantly.
Some data is missing at first, the user can wait for the data to appear asynchronously.
Even while the data is fetching, the user can enter on a goal and add data.

### Who will benefit from this feature?

- People who want to quickly add Beeminder data, without regards for the current status of their goals.

### Anything else?

An alternative solution would be to add a "add data to beeminder goal" action, that would take into input the goal name, datapoint number, and datapoint comment.

The goal names list would be cached to make it fast.

AND! also, an idea could be to add a way to create quicklinks to add data to Beeminder? Like an action that says "I just did 10 pushups and I want this to be sent to beeminder". I could write this in my raycast bar, and tada, it would add the data to beeminder!

(thanks for making my life easier already! I use your extension everyday)
(I can create a PR this weekend if you like one of these solutions)

**Comment by vivgui** [comment]
@clouedoc I truly apologize, I didn't see the notification when this was first created and now seeing it. Yes, feel free to create a PR with whatever solution and I'll make sure to preview it as soon as possible.

**Comment by vivgui** [comment]
@raycastbot close this issue
