### ISSUE TITLE
 [Todoist] ...

### ISSUE THREAD

**Issue by BrOrlandi** [raycast/extensions#6759]
### Extension

https://www.raycast.com/doist/todoist

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20
```

### Steps To Reproduce

Open Raycast
Select "Home" command for todoist.

### Current Behaviour

Shows error

### Expected Behaviour

Show the home of todoist.

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue #6562, so I'll mark it as such.
