### ISSUE TITLE
[TempMail] Can't open any mail inside Raycast

### ISSUE THREAD

**Issue by JhonnyAxe** [raycast/extensions#6762]
### Extension

https://www.raycast.com/Joshlucpoll/tempmail

#### Error:
```
TypeError: Right-hand side of 'instanceof' is not an object

Y6:message.tsx:135:37
Nr:index.js:6:2490
    at ray-navigation-stack
_o:index.js:6:2088
```

### Steps To Reproduce

1. Open Mailbox
2. Choose a mail
3. Press **Enter**

### Current Behaviour

![CleanShot 25 05 2023 at 10 56 18](https://github.com/raycast/extensions/assets/84262172/f1d15cce-7263-43f0-a30d-3049dc1cd0b0)

**Comment by Joshlucpoll** [comment]
Thanks for reporting the bug, I'm currently looking into it

**Comment by Joshlucpoll** [comment]
@JhonnyAxe I've pushed a new release for TempMail, can you update the extension and let me know if your problem is fixed? Thanks

**Comment by JhonnyAxe** [comment]
Thank you!

Now it responds but almost every mail shows that:

<img width="886" alt="CleanShot 05 06 2023 at 14 14 47@2x" src="https://github.com/raycast/extensions/assets/84262172/1bce0517-5033-47c1-a0ad-09bf9ed5adc5">

**Comment by Erik262** [comment]
I am facing the same problem as well.
