### ISSUE TITLE
Google Search: Improve searching of history

### ISSUE THREAD

**Issue by thomaspaulmann** [raycast/extensions#677]
# Extension – [Google Search](https://www.raycast.com/mblode/google-search)

Author: @mblode 

**Describe the feature and the current behavior/state.**

Right now the history disappears when I type a new query. I think it would be a better behavior if you keep the history section and just filter it locally. 

https://user-images.githubusercontent.com/12066405/149572645-0f4aa77a-1523-475e-9b61-fdf1240cd040.mp4

**Comment by mblode** [comment]
That makes sense 👍 Good suggestion
