### ISSUE TITLE
[Jira] set default team

### ISSUE THREAD

**Issue by mettin** [raycast/extensions#6772]
### Extension

https://www.raycast.com/raycast/jira

### Description

When selecting 'Active sprints' i always will select the same team. Would be great if I can set a default team or if the plugin remembers the last team I selected

### Who will benefit from this feature?

Everyone that uses multiple teams in Jira

**Comment by thomaslombart** [comment]
When you say teams, do you mean projects?

**Comment by IzakMaraisTAL** [comment]
An alternative is to let the extension remember which project I had selected last I had the active sprints view open. 

I have just switched from the deprecated JIRA extention to the new one. With the previous one I did not need to re-select the project again each time I opened Active sprints.

**Comment by thomaslombart** [comment]
Got it! This is actually a duplicate of issue #5988, so I'll mark it as such. Thanks for bringing up the issue anyway 😊
