### ISSUE TITLE
[Simple Youdao Translate] ...

### ISSUE THREAD

**Issue by Wu-XiaoLin** [raycast/extensions#6773]
### Extension

https://www.raycast.com/xeric/simple-youdao

#### Error:
```
Error: Command failed: afplay "/tmp/tmp_raycast_simpleyd.mp3" -v 1
Error: AudioFileOpen failed ('dta?')


Error: AudioFileOpen failed ('dta?')
ChildProcess.exithandler:node:child_process:412:12
ChildProcess.emit:node:events:513:28
```

### Steps To Reproduce

1. mac os 
2.
3. youdao ...
4. Error: Command failed: afplay "/tmp/tmp_raycast_simpleyd.mp3" -v 1
Error: AudioFileOpen failed ('dta?')

Error: AudioFileOpen failed ('dta?')
ChildProcess.exithandler:node:child_process:412:12
ChildProcess.emit:node:events:513:28

**Comment by xeric** [comment]
Could you check if your Youdao account turn on TTS function?
https://github.com/raycast/extensions/issues/5366#event-8817609863
