### ISSUE TITLE
[My Daily Log] ...

### ISSUE THREAD

**Issue by nukesean** [raycast/extensions#6777]
### Extension

https://www.raycast.com/frugoman/my-daily-log

### Description

The dates displayed in "Logged Days of Month" are off by 1. For example, logs from May 24 are labeled May 23 in the command. I'm not sure if this is relevant, but just in case: I store the logs in Dropbox to sync between machines.

### Steps To Reproduce

1. Make a new log
2. Use the "Logged Days of Month" command
3. Observe incorrect dates

### Current Behaviour

Dates are displayed as (Date - 1). See image below:

<img width="454" alt="DailyLog" src="https://github.com/raycast/extensions/assets/69487134/c14cb468-191f-4163-8284-0d5ad02df5b8">

### Expected Behaviour

Display correct dates.

**Comment by frugoman** [comment]
I'll take a look at this!

**Comment by bakari45** [comment]
I recently started using Daily Log, and the date is still off one day. Logs for today are stamped 11/25, but today's date is 11/25.
