### ISSUE TITLE
Bug getting markdown values from Form.TextArea 

### ISSUE THREAD

**Issue by joshknowles** [raycast/extensions#6782]
### Description

When using the `enableMarkdown` property of `Form.TextArea`, the markdown generated from the keyboard shorts (i.e. cmd-b) is only saved to the form value if you make an additional change to the form after using the markdown keyboard shortcut.

### Steps To Reproduce

1. Create a simple form with a Form.TextArea with `enableMarkdown` set to true
2. Input some text into your text area
3. Select some of the text and hit cmd-b to surround it with ** ** 
4. Submit the form
5. Values of the TextArea do not contain the ** **
6. Make a change to the TextArea after using the Markdown keyboard shortcut (i.e., add another character, newline, etc.)
7. Submit the form
8. Validate the value contains the markdown as expected

![image](https://github.com/raycast/extensions/assets/48/4d70c383-c311-454d-83ac-19d7a4b68737)

### Current Behaviour

Generated markdown only persisted to the form value after an additional change occurs

### Expected Behaviour

Generated markdown should persist to form value after using keyboard shortcut with no additional changes to form

**Comment by mathieudutour** [comment]
You're correct, it's indeed a bug - I'll fix it

**Comment by mathieudutour** [comment]
Should be fixed in 1.53.0!
