### ISSUE TITLE
[Weather] ...

### ISSUE THREAD

**Issue by brandyblacktea** [raycast/extensions#6784]
### Extension

https://www.raycast.com/tonka3000/weather

### Description

Could not fetch data from wttr.in

FetchError: request to https://wttr.in/%E4%B8%8A%E6%B5%B7?format=j1
failed, reason: certificate has expired

### Steps To Reproduce

Unable to obtain weather information.

**Comment by paulovpereira** [comment]
Still broken the extension for me. Any news on the fix? @tonka3000

**Comment by tonka3000** [comment]
@paulovpereira wttr.in seems to be down for now.

I would recommend https://www.raycast.com/tonka3000/openweathermap . Way more reliable, free and very precise.

**Comment by tonka3000** [comment]
btw: wttr.in is running again as well
