### ISSUE TITLE
[Todoist] Show the number of tasks besides project name

### ISSUE THREAD

**Issue by kissint8** [raycast/extensions#6785]
### Extension

https://www.raycast.com/doist/todoist

### Description

New feature REQUEST:
If it contains the **num of tasks for every project** in `Show projects`, I would apprecite much.

**Comment by thomaslombart** [comment]
I'm not sure I understand the feature request. Could you detail it?

**Comment by kissint8** [comment]
I think the iamge will show  more clearly.  

<img width="750" alt="image" src="https://github.com/raycast/extensions/assets/36233728/5320b270-f2fa-4994-9f4e-07525702d127">

Just add the count of tasks for every project to the right of each project name.  (when press `Show Projects` command)

**Comment by thomaslombart** [comment]
Good idea. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request.

**Comment by kissint8** [comment]
It's my  great pleasure.To be honest, I'm very interested in todoist!

**Comment by kissint8** [comment]
Well, I have implemented it in a less elegant way, which result as shown below:
- add a new item in `accessories`:
<img width="750" alt="image" src="https://github.com/raycast/extensions/assets/36233728/fc9d1074-d5bb-4db7-a263-c2cf12527a50">

 <br/><br/>
- just set `subtitle`:
<img width="750" alt="image" src="https://github.com/raycast/extensions/assets/36233728/3809b06e-bd26-460b-ab03-066714998fa0">
<br/>
However, I did the extension fork via raycast, so I wonder know how to open a pull request just like on github.

**Comment by thomaslombart** [comment]
You should find all info [here](https://developers.raycast.com/basics/contribute-to-an-extension).

**Comment by kissint8** [comment]
yeah, I following the guide what you mentioned, and open a pull request #6869.
