### ISSUE TITLE
[Google Bard] ...

### ISSUE THREAD

**Issue by jmabeebiz** [raycast/extensions#6794]
### Extension

https://www.raycast.com/EZDev/raycast-bard-ai

### Description

Even with putting in the cookie key, I'm unable to add content to use the commands. I tried putting it in three times --
__Secure-1PSIDCC=AP8dLtwpZLdw9QZFxqFoRXjjF4oXC_ugBrLK1mi6xdXo1oPzk3T2OBdurE2zGoXxk99l4oJReHE.google.com
AP8dLtwpZLdw9QZFxqFoRXjjF4oXC_ugBrLK1mi6xdXo1oPzk3T2OBdurE2zGoXxk99l4oJReHE.google.com
AP8dLtwpZLdw9QZFxqFoRXjjF4oXC_ugBrLK1mi6xdXo1oPzk3T2OBdurE2zGoXxk99l4oJReHE

Also, there's nowhere to put in actual text to give it a prompt. 

### Steps To Reproduce

I tried to use the extension as normal, and it did not work in any capacity.

**Comment by metya** [comment]
Can confirm! Doesn't work with error `can't reach Bard now`

**Comment by EvanZhouDev** [comment]
Okay, these are two different issues.
First of all, fixing the "Can't reach Bard now:"
1. You need the cookie labeled "__Secure-1PSID," not "__Secure-1PSIDCC." They are different!
2. You need to put in the key as it is. Do not put "__Secure-1PSID=" prefixed!

Please read the instructions on the README carefully.

Second: As for the prompt, Ask AI is currently only to be used as a fallback command. This means you set it as a fallback command (docs on Raycast's website) and then you type something in the command bar itself, scroll down to "Ask AI" and click enter on it. Then, it will submit *that* as the query.

I will make sure to improve the README in the next update.
Also know that I am currently working on a more powerful and re-engineered version of `raycast-bard-ai` that will give it chat history, better integration, and more!

If you have any other questions, let me know.

**Comment by metya** [comment]
In my case - I carefully copied exactly `__Sercure-1PSID` with the period at the end.
I used `Ask AI` command as a fallback command. 
Doesn't work.

**Comment by EvanZhouDev** [comment]
Do you have access to Google Bard normally? It should work if you do... alternatively, try running [bard-ai](https://www.npmjs.com/package/bard-ai) on your system and see if *that* works. Let me know, and I will definitely look into it.

**Comment by metya** [comment]
Yes, of course. 
Ok, I'll try. 
Will write here in one hour, approximately.

**Comment by metya** [comment]
Ok, I've tried it with the code example in the README.md.

i.e.

```js
import Bard, { askAI } from "bard-ai";

await Bard.init("COOKIE_KEY");

console.log(await askAI("Hello world!"));
```
with my cookie of course
and it threw this error:


```js
Process exited with code 1
Uncaught Error Error: Could not get Google Bard.
    at init (/Users/metya/Projects/bard-ai/node_modules/.pnpm/bard-ai@1.2.0/node_modules/bard-ai/index.js:29:16)
    at processTicksAndRejections (internal/process/task_queues:95:5)
    --- await ---
    at runMainESM (internal/modules/run_main:53:21)
    at executeUserEntryPoint (internal/modules/run_main:79:5)
    at <anonymous> (internal/main/run_main_module:23:47)
```

I little bit debugged it, and it doesn't get a proper response on line 24, so the next line 26 match does get null.

**Comment by hutgrabber** [comment]
I am trying to use the 'Ask AI' feature of this Raycast Extension, however, there is no way I am able to provide input to the extension. Basically, there is no place where I can type my question. Can you please help me on this?

**Comment by EvanZhouDev** [comment]
Use it as a fallback command. Look at Raycast docs for more information.

**Comment by yzlnew** [comment]
What is a `period` at the end of the value? I don't see my `__Secure-1PSID` value ends with meaningful character.

**Comment by EvanZhouDev** [comment]
It doesn’t have to end in a period. Copy whatever value you have. I was simply saying that if you *do* have a period or any other character, make sure to include it.

**Comment by jfmadridc** [comment]
same here, to clarify my __Secure-1PSID looks like this `YAh....mGPIQ.` much longer I just redacted the middle
I have tried several times making sure there is no trailing or ending space but ends in the same `⚠️ Unable to reach Bard at this time.`

**Comment by EvanZhouDev** [comment]
Yes, this is an issue with the Bard API. They have changed their interface, and the changes have been PRed. I'm waiting for it to be accepted.

**Comment by aaSchcolnik** [comment]
> Yes, this is an issue with the Bard API. They have changed their interface, and the changes have been PRed. I'm waiting for it to be accepted.

Hi! I've tried using your extension moments ago and I'm getting the same error: "⚠️ Unable to reach Bard at this time."

Has your PR been accepted? If it's the case then I guess this issue is persistant

**Comment by EvanZhouDev** [comment]
Huh... works for me? In both production and dev. Try updating your extensions.

**Comment by aaSchcolnik** [comment]
> Huh... works for me? In both production and dev. Try updating your extensions.

Interesting. I followed all of the instructions and I still got that error, there were no updates for the extension, i did try to do that. I'll give it a try once im using the computer again. Thank you for the answer, if you have any idea of what I may have done wrong feel free to leave me a comment on it, thanks!

**Comment by daniloogoncalves** [comment]
Same here. Getting error "Unable to reach Bard at this time".
Cookie OK
Fallback OK
But it's not working

**Comment by natesilva** [comment]
I am getting "Failure to fetch Bard" on every request.

I ran the above Node.js code using the `bard-ai` module and the cookie key -- and it worked, with Bard replying "Hello world! It's nice to meet you. How can I help you today?"

But in the Raycast extension I get an error.

**Comment by CharlieLeee** [comment]
> Edit: This happens when using the AI Chat action. If I copy some text to the clipboard and use "Ask AI" then it works.

I can confirm that I have the same behavior here.

**Comment by nickwild-999** [comment]
Sorry yes me too

**Comment by EvanZhouDev** [comment]
Please try clearing cookies, then logging in again, and getting a new PSID.

**Comment by nickwild-999** [comment]
I can get it to work with commands like Summarize and Shorten, but not Chat

**Comment by EvanZhouDev** [comment]
Hmm... That's strange. I'll have to look into it. I am using a slightly new implementation for Chat, but I think I'll do a major rewrite of this extension after the API that I am using (bard-ai) gets to version 2 (which should be soon)

**Comment by nickwild-999** [comment]
Thanks Evan, much appreciated
