### ISSUE TITLE
[iTranslate] a lot of times the translate doesn't work from first time

### ISSUE THREAD

**Issue by UtopiaEH** [raycast/extensions#6796]
### Extension

https://www.raycast.com/JinShi/itranslate

### Description

A lot of times the translation doesn't work for first time on gif attached below can find my current settings
![shoot_26_05_4_49](https://github.com/raycast/extensions/assets/25262913/2c16dd0d-5a66-4bc3-9b62-4a45fd72d605)

### Steps To Reproduce

1. Open translate
2. write some words
3. got error 
4. try agayn ones or twise and start to work

![shoot_26_05_4_48](https://github.com/raycast/extensions/assets/25262913/a2bcbd76-d6d0-4617-81dd-17ca5ac645c0)

**Comment by 404J** [comment]
@UtopiaEH sorry about that🥲,I will fix it immediately

**Comment by 404J** [comment]
@UtopiaEH Please update this extension~

**Comment by UtopiaEH** [comment]
No problem  but it look like is up to date
