### ISSUE TITLE
[Brave] searching tabs and opening new tabs does not work

### ISSUE THREAD

**Issue by dkarter** [raycast/extensions#6803]
### Extension

https://www.raycast.com/ron-myers/brave

### Description

Brave search tabs and new tab features does not work. I've tried these on multiple computers (Intel and Apple Silicon).

I have pressed 'OK' when asked if I want to allow Raycast to control Brave

![CleanShot 2023-05-26 at 14 07 22@2x](https://github.com/raycast/extensions/assets/551858/e1a2cc5a-e05e-4f38-b34a-690baa914633)

https://github.com/raycast/extensions/assets/551858/74671418-29b4-49c6-b1c9-068d3d4192a8

https://github.com/raycast/extensions/assets/551858/1686a2a2-127f-4825-a446-4ee75133dfd0

### Steps To Reproduce

1. Open the search tabs/create new tab feature of this extension

### Current Behaviour

Crashes with an error: "Something happened while trying to run your command"

### Expected Behaviour

Should work without an error? :)

Seems similar to #4159 - but could be a different underlying error since I know there were some changes merged to this extension since

**Comment by dkarter** [comment]
It is still not working

**Comment by sdaza** [comment]
Same here, not working!
