### ISSUE TITLE
[System Monitor] ...

### ISSUE THREAD

**Issue by W00dyBuzz** [raycast/extensions#6804]
### Extension

https://www.raycast.com/hossammourad/raycast-system-monitor

### Description

There should be another option at the bottom to open Activity Monitor in case people want to get more info.

### Who will benefit from this feature?

People who see the basic info inside this app but want to see more info (a list of running processes, etc).

**Comment by pernielsentikaer** [comment]
Opened #6871

**Comment by lucasmezencio** [comment]
@pernielsentikaer this issue should be closed, no?

**Comment by pernielsentikaer** [comment]
Correct 😊
