### ISSUE TITLE
[ChatGPT] Persist last conversation on "Ask Question" command.

### ISSUE THREAD

**Issue by luisbc92** [raycast/extensions#6805]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Currently, when focus is lost from Raycast after using the "Ask Question", the state is lost and a new conversation is created. The conversation is then stored in "Conversations", however it might be helpful for "Ask Question" to preserve state until explicitly reset (much like Raycast AI).

### Who will benefit from this feature?

This will be useful for the use case where multiple questions need to be asked on the same topic.

**Comment by Nauxscript** [comment]
I need it too 😂 It may be necessary to redesign the interaction in order to implement this feature.
Do you have any idea?
