### ISSUE TITLE
[Imgur] ...

### ISSUE THREAD

**Issue by kyellareddy** [raycast/extensions#6807]
### Extension

https://www.raycast.com/BalliAsghar/imgur

### Description

It should be possible to upload to Imgur using an account.

### Who will benefit from this feature?

People who have an Imgur account and want their media to stay together under that account.

**Comment by ShakataGaNai** [comment]
Seconding this to unclose/unstale. It's not clear in the documentation how this plugin works, where it uploads, what a new clientID does (and has no place for a client secret).
