### ISSUE TITLE
[Parcel Tracker - 17track] API paid feature

### ISSUE THREAD

**Issue by geonzee** [raycast/extensions#6808]
### Extension

https://www.raycast.com/cojmeister/package-tracker

### Description

In the approval process, it looked to me that the API shouldn't interact with the business API service of 17Track. They used to allow it some time ago, but now it seems to me that the URL on the README doesn't even exist anymore.

### Steps To Reproduce

cannot find 17track security Key.

**Comment by cojmeister** [comment]
Hey @geonzee , I don't understand your problem. 
In order for the link in step 2 to work, you need to be logged into your 17track account, which you created in step 1. 
Seems to work for me

**Comment by geonzee** [comment]
Thank you for the prompt response.

Are you using a buyer or seller 17track account? What are the steps to find the security key?
The only page related to the API I can find recently is this: https://api.17track.net/en.

This link https://api.17track.net/en/admin/settings sends me to the login page, even if I'm already logged in, and neither my personal account (buyer) nor the business account (seller) leads me to a settings page where I can find the key.


From: cojmeister ***@***.***>
Date: Sunday, May 28, 2023 at 08:53
To: raycast/extensions ***@***.***>
Cc: geonzee ***@***.***>, Mention ***@***.***>
Subject: Re: [raycast/extensions] [Parcel Tracker - 17track] API paid feature (Issue #6808)

Hey @geonzee<https://github.com/geonzee> , I don't understand your problem.
In order for the link in step 2 to work, you need to be logged into your 17track account, which you created in step 1.
Seems to work for me
