### ISSUE TITLE
`fetch()` does not work

### ISSUE THREAD

**Issue by EvanZhouDev** [raycast/extensions#6814]
### Description

Raycast version 1.52.1
@raycast/api 1.52.1

Fetch is not supported in Raycast extensions, even though it is even supported in the LTS version of Node.js (18.16.0).

I am currently using my own NPM library, which I recently migrated to `fetch()`, [bard-ai](https://github.com/EvanZhouDev/bard-ai). Because of this, I cannot simply install a fetch polyfill on the Raycast side.

### Steps To Reproduce

1. Create any form of a Raycast extension
2. Simply use `fetch()` anywhere inside the main component of a command
3. Run the extension
4. It complains that "ReferenceError: fetch is not defined"

### Current Behaviour

Fetch is not defined.

### Expected Behaviour

Fetch should be defined for any version of Node.js that is at least LTS.

**Comment by jairaume** [comment]
Raycast's API provides the [`useFetch` hook ](https://developers.raycast.com/utilities/react-hooks/usefetch)if you import [`@raycast/utils`](https://developers.raycast.com/utilities/getting-started) !

**Comment by EvanZhouDev** [comment]
Hello! Thanks for the quick response. The problem that I am having is that the _dependency_ (which I also made) uses `fetch()`, so I can't directly use the Raycast hook. If there's no other workaround, I guess I can just keep on updating an older version of `bard-ai` which uses `axios`.

**Comment by mathieudutour** [comment]
`fetch` support is still experimental in NodeJS. There are some issues regarding proxies for example. That's why we have disabled it for now.

> Because of this, I cannot simply install a fetch polyfill on the Raycast side.

Why not? Import any node-fetch library and set it as a global variable if you want

**Comment by EvanZhouDev** [comment]
> Why not? Import any node-fetch library and set it as a global variable if you want

Oh my, oh my, how embarrassing 🤦‍♂️. Been doing this for too long to not realize that. Thank you for your time!

**Comment by inducingchaos** [comment]
@mathieudutour any plans to support this soon?

Mostly just curious. The [`useFetch`](https://developers.raycast.com/utilities/react-hooks/usefetch) hook is cool and all. Only gripe I have with it really is the need to create another state variable if you don't want it to run on mount:

```typescript
const [runCreateThought, setRunCreateThought] = useState(false)

const { isLoading: createThoughtIsLoading } = useFetch(`https://random.app/api/thoughts`, {
    ...createThoughtInit(thought),
    execute: runCreateThought,
    onData: appendCreatedThought
})
```

As opposed to just calling fetch in a function.

--

Seems like fetch was introduced in Node *years* ago. Seeing this error initially made me think Raycast was running some kind of legacy Node version or weird environment where Node doesn't exist... seems like a no-brainer to include it to me.
