### ISSUE TITLE
[ChatGPT] Error when setting custom api endpoint

### ISSUE THREAD

**Issue by HatsuneMK00** [raycast/extensions#6825]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

@Nauxscript Hi! I'm trying to set custom api but get this error. The same url works fine in another app that using openAI api. Could you please help me locate where is wrong? I have "https://my-url.top/" in the apiEndpoint and have the useApiEndpoint checked.

Error: Request failed with status code 404

gt.exports:createError.js:16:14
yt.exports:ask.js:2:7730
IncomingMessage.:ask.js:7:11799
IncomingMessage.emit:node:events:525:35

### Steps To Reproduce

1. Check the "change API Endpoint"
2. Set API Endpoint to "https://my-url.top"
3. Use "Ask Question" command.

### Current Behaviour

Getting an error says:
Error: Request failed with status code 404

gt.exports:createError.js:16:14
yt.exports:ask.js:2:7730
IncomingMessage.:ask.js:7:11799
IncomingMessage.emit:node:events:525:35

### Expected Behaviour

Being able to chat with ChatGPT

**Comment by HatsuneMK00** [comment]
#6658 This may be related to this pull request.

**Comment by Nauxscript** [comment]
The link cannot be accessed. Have you configured the HTTPS certificate?
when I run `curl https://my-url.top` in my terminal, It comes this error:

```
curl: (60) SSL: no alternative certificate subject name matches target host name 'my-url.top'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

and what's app you mentioned that the url is working fine?

**Comment by HatsuneMK00** [comment]
Thanks for your reply! So sorry about the ambiguousness of the url. It is just a dummy one, the url I use in "Opencat"(A gpt app using OpenAI API) and "Bob"(A translation app) is "makise-amadeus.top" and they both work fine.

**Comment by Nauxscript** [comment]
> Thanks for your reply! So sorry about the ambiguousness of the url. It is just a dummy one, the url I use in "Opencat"(A gpt app using OpenAI API) and "Bob"(A translation app) is "makise-amadeus.top" and they both work fine.

oh I see. If you are using `Bob` and  setting `makise-amadeus.top` in the `OpenAI 翻译` service, maybe I know how was this problem caused?

In the third-party applications, when we set the OpenAI api `https://api.openai.com`,  it actually calls `https://api.openai.com/v1`. So if your custom service has the same interface specifications as OpenAI, you could try `makise-amadeus.top/v1`.

refer to [chatanywhere/GPT_API_free](https://github.com/chatanywhere/GPT_API_free#raycast-%E6%8F%92%E4%BB%B6-chatgpt%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8);

I am using this custom service so my apiEndpoint is set as `https://api.chatanywhere.com.cn/v1`

**Comment by HatsuneMK00** [comment]
This fix works! Everything is fine after I add a `/v1` at the end. Thanks a lot!

**Comment by Nauxscript** [comment]
@raycastbot close this issue

**Comment by Jackiexiao** [comment]
in my case, I don't need to add `/v1`

**Comment by Nauxscript** [comment]
> in my case, I don't need to add `/v1`
> 
> 
> 
> <img width="320" alt="image" src="https://github.com/raycast/extensions/assets/18050469/daa001d8-25b5-4848-a59c-0436efb11efc">
> 
> 

Because you are using azure api👀
