### ISSUE TITLE
[ChatGPT] Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by pys1992** [raycast/extensions#6834]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

1. setup api key
2. open the plugin

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/44765369/e01f30e1-eb34-4cf2-97f8-3d0c3ba32114">

Error: Client network socket disconnected before secure TLS connection was established

connResetException:errors:711:14
TLSSocket.onConnectEnd:node:_tls_wrap:1593:19
TLSSocket.emit:node:events:525:35
TLSSocket.emit:node:domain:489:12

### Steps To Reproduce

1. setup api key
2. open the plugin

**Comment by Nauxscript** [comment]
This could be due to the local proxy, check out your proxy setting and relaunch raycast to retry.

**Comment by pys1992** [comment]
> This could be due to the local proxy, check out your proxy setting and relaunch raycast to retry.

@Nauxscript  Yes, it is a issue about local proxy. Thanks.

It works after I close this option.

<img width="1068" alt="image" src="https://github.com/raycast/extensions/assets/44765369/e7175f3d-b64a-43cd-a00d-bf399d5f2a21">
