### ISSUE TITLE
[Linkding] Misleading Error Toast On Successful Results

### ISSUE THREAD

**Issue by vkhitrin** [raycast/extensions#6839]
### Extension

https://www.raycast.com/InteractiveNinja/linkding

### Description

Hey @InteractiveNinja,

I've encountered a "false" toast error when executing the command:

https://github.com/raycast/extensions/assets/32794653/6fb7a6bf-65ae-4a71-9dc5-19964dc37162

When launching the command, a toast `Something went wrong` almost immediately pops up until results are returned. 
It has occurred for the last two weeks over several linkding releases (I am currently at `1.19.0`).
I have also tried using your repo https://github.com/InteractiveNinja/raycast-linkding-ext, with the same result.

### Steps To Reproduce

1. Execute the `Search Linkding` command.
2. Error toast appears until results are shown.

### Current Behaviour

Error toast appears early and is misleading.

### Expected Behaviour

Error toast appears only when it exhausts all attempts to fetch results.

**Comment by InteractiveNinja** [comment]
Hello @vkhitrin

Thanks for your bug ticket, I was able to reproduce the error and correct it in my repo. The error toast was displayed when actually no error occurred, the behavior was adjusted. I am currently working on a multi-linking instance feature for this extension. The fix will be implemented as part of this update and will be available in the store. I am not certain how long it will take me, so please be patient. You could also use the current version from my repository, which already has the fix implemented. 

I greatly appreciate your help and wish you a wonderful day.

**Comment by vkhitrin** [comment]
Thanks a lot, @InteractiveNinja!

Would you like to keep this issue open until you push your PR?

**Comment by InteractiveNinja** [comment]
Yes, it would be cool if the ticket stays open, I'll close it when I'm done with the PR.
