### ISSUE TITLE
[TickTick] Command to show all tasks in Inbox, not just the one with date stamp

### ISSUE THREAD

**Issue by truongio** [raycast/extensions#6843]
### Extension

https://www.raycast.com/appest/ticktick

### Description

Hi, right now there are two commands, one to show today's task and another to show tasks for the upcoming 7 days but I can't in anyway see all my tasks in Inbox.

### Who will benefit from this feature?

All users

**Comment by viduycheung** [comment]
https://github.com/raycast/extensions/pull/7367

**Comment by viduycheung** [comment]
https://github.com/raycast/extensions/pull/7367
@raycastbot close this issue
