### ISSUE TITLE
[1Password] ...

### ISSUE THREAD

**Issue by skybird-dev** [raycast/extensions#6846]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

newly created passwords not showing up in Raycast even after 30 minutes

### Steps To Reproduce

macOS Monterey 12.6.6 
Raycast 1.52.1
1Password for Mac 8.10.6 (81006027)

### Current Behaviour

Does not show up

![Screen Shot 2023-05-29 at 10 59 56 AM](https://github.com/raycast/extensions/assets/117532029/f1c0b52c-45af-49f2-8288-66f20ad8b411)

### Expected Behaviour

Should show up within minutes at least

**Comment by TyypKUbt** [comment]
Just commenting that I'm still experiencing this issue - it seems like 1password on raycast does not get updated, and in order to see the latest saved passwords you need to clear the cache and basically sign in again
