### ISSUE TITLE
[Google Translate] Add action to paste text from clipboard

### ISSUE THREAD

**Issue by Ernest0-Production** [raycast/extensions#6848]
### Extension

https://www.raycast.com/gebeto/translate

### Description

When open translate window, add action using option+V for example, that will be automatically past text from clipboard to source text, and translate it

**Comment by gebeto** [comment]
Thanks for the suggestion! I'll implement it soon 🙌

**Comment by gebeto** [comment]
Hm, but also, why you can't just use CMD+V to paste the text? Why do we need to add custom action for it?

**Comment by Ernest0-Production** [comment]
I think this is a bit more convenient as it reduces the number of actions to translate the text. 

P. S. I didn't expect to meet you here :) (jailgeek admin)

**Comment by pernielsentikaer** [comment]
This should now be live 🙂 Could you test it out @Ernest0-Production 🙂

**Comment by Ernest0-Production** [comment]
@pernielsentikaer Yeah, it's even better than I wanted. Thanks to the author and the raycast team!)
