### ISSUE TITLE
[Todoist] New Task with a due_datetime

### ISSUE THREAD

**Issue by sgnilreutr** [raycast/extensions#6855]
### Extension

https://www.raycast.com/doist/todoist

### Description

Personally I like to be reminded of a task on a certain time, currently the Raycast extension does not provide a way to specify a time.

https://developer.todoist.com/rest/v2/#create-a-new-task

### Who will benefit from this feature?

Everyone that uses Todoist tasks with due times.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by sgnilreutr** [comment]
> Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

More than happy to do so.

We could connect/confer via Discord? sgnilreutr#5882

**Comment by sgnilreutr** [comment]
I will finish this.

**Comment by thomaslombart** [comment]
Fixed as part of #8474.
