### ISSUE TITLE
[Arc] Search history is missing a ton of entries

### ISSUE THREAD

**Issue by neilio** [raycast/extensions#6860]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

I just did some tests with Arc history search in Raycast, and I'm not quite sure where it's getting its results, as they don't match up with my Arc browser history at all. See below for an example.

<img width="969" alt="CleanShot 2023-05-30 at 12 32 37@2x" src="https://github.com/raycast/extensions/assets/1400/a5683347-eff8-42ad-aa3b-ee5473d69b62">

### Steps To Reproduce

The only step to reproduce is to try some searches and compare the results to what's in Arc's history list.

### Current Behaviour

Returns back a seemingly random mix of items, with the biggest gaps in the recent past (the last week).

### Expected Behaviour

Anything I see in Arc's history window should be part of the Arc extension's history results.

**Comment by joshmedeski** [comment]
I'm having the same issue. It appears that only some of the spaces are showing history. I have multiple profiles in my Arc setup and would like the history of all profiles to be shown in the history search.

**Comment by joshmedeski** [comment]
I discovered the the plugin is only pointing at the default profile's history: https://github.com/raycast/extensions/blob/main/extensions/arc/src/sql.ts#L4

Can we adjust the plugin to support multiple profiles and point at all profile histories?

**Comment by joshmedeski** [comment]
I've crated https://github.com/raycast/extensions/issues/7665 to specifically add multi-profile support to the Arc extension.
