### ISSUE TITLE
Field label isn't updated when dropdown changes

### ISSUE THREAD

**Issue by NeoVier** [raycast/extensions#687]
Raycast version: 1.27.0

## Description

In the form API, when the value of a form element is updated, the other form elements aren't re-rendered. This could be important in cases where, for instance, the label of an element depends on the value of another.

Concrete example: building an extension to search [Elm](https://elm-lang.org) packages by type, we can search either by type signature, package author, module name or package name (only one of these at a time). So a sensible UI would be to have one text field and one dropdown, where the text field is the query to search for, and the dropdown represents one of those possibilities. However, when the dropdown value changes, the textfield label isn't updated.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/39280468/149636826-40b2aadd-bda3-4c9c-9bdc-0bd97c5c6b4e.png">

## Steps To Reproduce

Sample code:

```ts
  const [state, setState] = useState<State>({ query: "", searchType: "signature" });

  return (
    <Form
      actions={
        <ActionPanel>
          <OpenInBrowserAction title="Search" url={searchUrl(state)} />
        </ActionPanel>
      }
    >
      <Form.TextField
        id="query"
        title={searchTypeTitle(state.searchType)}
        placeholder="String -> Maybe Int"
        value={state.query}
        onChange={(newQuery) => setState((prevState) => ({ ...prevState, query: newQuery }))}
      />
      <Form.Dropdown
        id="searchType"
        defaultValue="signature"
        title="Search by"
        value={state.searchType}
        onChange={(newSearchType) =>
          setState((prevState) => ({ ...prevState, searchType: newSearchType as SearchType }))
        }
      >
        {searchTypes.map((searchType) => (
          <Form.Dropdown.Item key={searchType} title={searchTypeTitle(searchType)} value={searchType} />
        ))}
      </Form.Dropdown>
    </Form>
```

1. Create a controlled textfield and a controlled dropdown
2. Make the label of the textfield dependent on the dropdown value
3. Change the dropdown value. Notice how the label on the textfield doesn't update
4. If you now input something into the textfield, it's label will be updated

## The current behavior

After changing the value of the dropdown, the label of the input is only updated after the user inputs something into the textfield

## The expected behavior

The label on the textfield should be updated as soon as the dropdown value is updated

**Comment by NeoVier** [comment]
I was just testing it with other values, and apparently it only happens if the `placeholder` attribute on the text field is a static text (if there is no placeholder, or if the placeholder is also dependent on the state, the label and the placeholder both update)

**Comment by mattisssa** [comment]
Hey @NeoVier! Thank you for the report. Can I ask you to share the `State` interface and `searchTypes` so I could test the code? :)

**Comment by mattisssa** [comment]
Ok, I'm using this test code, I think it should help repro the bug.

```import { Form, ActionPanel, OpenInBrowserAction } from "@raycast/api";
import { useState } from "react";

type SearchType = "signature" | "test";

interface State {
  query: string;
  searchType: SearchType;
}

const searchTypes: SearchType[] = ["signature", "test"];

export default function Main() {
  const [state, setState] = useState<State>({ query: "", searchType: "signature" });

  return (
    <Form
      actions={
        <ActionPanel>
          <OpenInBrowserAction title="Search" url={""} />
        </ActionPanel>
      }
    >
      <Form.TextField
        id="query"
        title={state.searchType}
        placeholder="String -> Maybe Int"
        value={state.query}
        onChange={(newQuery) => setState((prevState) => ({ ...prevState, query: newQuery }))}
      />
      <Form.Dropdown
        id="searchType"
        defaultValue="signature"
        title="Search by"
        value={state.searchType}
        onChange={(newSearchType) =>
          setState((prevState) => ({ ...prevState, searchType: newSearchType as SearchType }))
        }
      >
        {searchTypes.map((searchType) => (
          <Form.Dropdown.Item key={searchType} title={searchType} value={searchType} />
        ))}
      </Form.Dropdown>
    </Form>
  );
}

**Comment by NeoVier** [comment]
Oh sorry, I should've included them on the issue description. Anyway, here they are:

```ts
type SearchType = "signature" | "author" | "packageName" | "moduleName";

const searchTypes: SearchType[] = ["signature", "author", "packageName", "moduleName"];

interface State {
  query: string;
  searchType: SearchType;
}

function searchTypeTitle(searchType: SearchType): string {
  switch (searchType) {
    case "signature":
      return "Type Signature";
    case "author":
      return "Author";
    case "packageName":
      return "Package Name";
    case "moduleName":
      return "Module Name";
  }
}
```

**Comment by mattisssa** [comment]
Got the case, thanks a lot for catching this, will be fixed on next release 😉 👏

**Comment by NeoVier** [comment]
Nice! Thanks for the quick reply! 🔥
