### ISSUE TITLE
[Home Assistant] Allow Internal & External URL

### ISSUE THREAD

**Issue by davocarli** [raycast/extensions#6879]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Description

Hi! It would be great to be able to configure both an internal & external url for the Home Assistant extension. The internal (local) url works incredibly fast, but will only work when connected to the same Wi-Fi network as your HA instance. This means that if you configure with this url and leave your home, you will not be able to connect.

It would be great to be able to configure a "backup" (external) url as well, so that when the local one is not accessible it will attempt to connect to the external one. This can give you the benefit of super-fast speeds when at home, without making the extension useless when out of the house.

### Who will benefit from this feature?

Any Home Assistant user who has HA exposed to the internet would benefit from this feature.

**Comment by tonka3000** [comment]
@davocarli

You talking about the same mechanism as the HA-smartphone app is using right?

**Comment by davocarli** [comment]
Pretty much, yeah. I believe the smartphone app checks your WiFi SSID and uses the local vs internet url based on that. As an alternative you could also just try one link, then try another if it fails.

**Comment by tonka3000** [comment]
SSID works. Detecting a wired connection would be a problem.
The websocket connection don't give an exception fast, this would lead to slow command startup times.

Would the SSID approach be enough in your case?

**Comment by tonka3000** [comment]
I've implemented a ping based version too. Not finished, but I assume I will push it in the next couple of days.

**Comment by davocarli** [comment]
Yeah an SSID based version would be perfect in my case, since I use a wireless connection. I'm sure there's someone who would benefit from the ping based version but it isn't something I necessarily need.

Thanks for working on this.
