### ISSUE TITLE
[Stock Tracker] Does not function whatsoever

### ISSUE THREAD

**Issue by jonfriedman** [raycast/extensions#6883]
### Extension

https://www.raycast.com/hmarr/stock-tracker

### Description

All functions completely broken. Cannot search or display any stock information.

### Steps To Reproduce

1. Open the extension.
2. Search for a stock.

### Current Behaviour

Output reads "No results"

### Expected Behaviour

Search lists stock information for searched for item. Home screen of extension shows favorite stocks and related info.

**Comment by hmarr** [comment]
The Yahoo Finance API just changed, and unfortunately that has broken this integration. I think I know how we can work around the issue, so I'll have a go at fixing it whenever I get some time.

**Comment by hmarr** [comment]
@jonfriedman https://github.com/raycast/extensions/pull/6928/files should fix this
