### ISSUE TITLE
[Formula 1] ...

### ISSUE THREAD

**Issue by mkandan** [raycast/extensions#6886]
### Extension

https://www.raycast.com/csigritz/f1-standings

### Description

@csigritz
exact same as this issue is happening again https://github.com/raycast/extensions/issues/2068

### Steps To Reproduce

1. Install Formula 1 extension from store
2. Try running any of the 3 commands (constructor standings, driver, standings, race schedule)
3. 
<img width="778" alt="image" src="https://github.com/raycast/extensions/assets/40218068/1ebf0cdc-cb6f-499a-b814-14f6f9ccfca0">

### Current Behaviour

Says `error could not load sessions`

### Expected Behaviour

show the relevant information

**Comment by csigritz** [comment]
I am currently looking into this issue. Looks like there is some kind of SSL issue when connecting to the API.

**Comment by csigritz** [comment]
Just contacted the API vendor if he can check the new certificate issued on 2023-05-31.

**Comment by csigritz** [comment]
The certificate has been corrected on the API side. The extensions now works again. No update to the code required.

**Comment by mkandan** [comment]
Thank you @csigritz !!!
