### ISSUE TITLE
[Home Assistant] Connection to websocket failed

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#6890]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Description

After setting the Home Assistant URL and API token I get this with any command:

<img width="886" alt="Screenshot 2023-05-31 at 22 40 11" src="https://github.com/raycast/extensions/assets/11052366/a4959010-4329-4f91-9696-83b16c4302f6">

### Steps To Reproduce

The same as above.

**Comment by tonka3000** [comment]
@xilopaint 

Try it via IP for testing. Could be that .local addresses are not possible in that scenario.

**Comment by xilopaint** [comment]
@tonka3000 it works via IP.

**Comment by xilopaint** [comment]
It works in the browser.

**Comment by tonka3000** [comment]
AFAIK browser handle mDNS themself. I assume that nodejs doesn't do that out of the box.

**Comment by xilopaint** [comment]
Should I close the issue then?

**Comment by tonka3000** [comment]
No. I need to check how to handle mDNS in nodejs.

**Comment by xilopaint** [comment]
@tonka3000 I'm facing this issue again.

**Comment by tonka3000** [comment]
@xilopaint Does this happen with the .local address or the IP?

**Comment by xilopaint** [comment]
> @xilopaint Does this happen with the .local address or the IP?

@tonka3000 The `.local` address, I just edited my comment. It works with the IP.

**Comment by tonka3000** [comment]
@tonka3000 But it work the last couple of weeks?

**Comment by xilopaint** [comment]
> What exact error message do you get?

<img width="886" alt="Screenshot 2023-08-24 at 02 19 31" src="https://github.com/raycast/extensions/assets/11052366/f1c697af-734e-4d22-bdbf-cbae129123e6">

I noticed the issue a few days ago.

**Comment by tonka3000** [comment]
This is the error I assumed based on your first error report. The timeout is 5 seconds, which irritating that the system does not responded in that timeframe 🤔.

Did you opened multiple commands in a short period of time (5-30 seconds)? Maybe that is of rate limiting.
I don't cache it longer than one command run and maybe it would be good to think about caching, but local devices often answer the mDNS very quickly.

Maybe it would be a good test if you clone the extension on your machine, change the timeout to 10-15 seconds [here](https://github.com/raycast/extensions/blob/2830eb8352702af95409af8901e06d4fcc56fa93/extensions/homeassistant/src/lib/mdns.ts#L3). Would but interesting to know if the mDNS answer will arrive later or if it never will reach your machine.

**Comment by xilopaint** [comment]
@tonka3000 

> Did you opened multiple commands in a short period of time (5-30 seconds)?

No.

> Maybe it would be a good test if you clone the extension on your machine, change the timeout to 10-15 seconds [here](https://github.com/raycast/extensions/blob/2830eb8352702af95409af8901e06d4fcc56fa93/extensions/homeassistant/src/lib/mdns.ts#L3). Would but interesting to know if the mDNS answer will arrive later or if it never will reach your machine.

I've raised the timeout to 15s and no luck.

**Comment by tonka3000** [comment]
@xilopaint  That is strange. It seems that your Home Assistant don't send a response or for whatever reason the nodejs lib I used don't see it.

Questions:
- Do you have access points which are in mesh-mode? 
- Do you use ESP Home?

**Comment by xilopaint** [comment]
@tonka3000 

> Questions:
> 
> * Do you have access points which are in mesh-mode?
> * Do you use ESP Home?

No and no.

**Comment by xilopaint** [comment]
@tonka3000 Hey, the `.local` address is working again.

**Comment by xilopaint** [comment]
> @tonka3000 Hey, the extension is working with the `.local` address again.

@tonka3000 Maybe it worked for a while because of the cache, but now it has stopped working again. 😓

**Comment by tonka3000** [comment]
Switch to the IP for now. Right now I'm very busy but I will add a long-term cache in one of the next versions.
