### ISSUE TITLE
[Keyboard Maestro - List Macros] ...

### ISSUE THREAD

**Issue by skilletaudio** [raycast/extensions#6891]
### Extension

https://www.raycast.com/eluce2/list-keyboard-maestro-macros

#### Error:
```

```

### Steps To Reproduce

Run the shortcut and then triggerd Keyboard Maestro Raycast "List Macros" for Keyboard Maestro

### Current Behaviour

Doesn't seem to work. Always posts something went wrong. 

### Expected Behaviour

To show macros but I am not totally sure what it is suppose to do.

**Comment by eluce2** [comment]
Sorry you're having trouble with this. The error message didn't come through. This script is pretty simple, but does require AppleScript. Perhaps there was a security permissions prompt that is not allowing Raycast to control Keyboard Maestro?

This is the script running behind the scenes if you'd like to try running it directly on your machine to see if you get the same error:
```
tell application "Keyboard Maestro Engine"
          set macroList to getmacros with asstring
end tell
```
It should return some XML

**Comment by eluce2** [comment]
@raycastbot close this issue
