### ISSUE TITLE
[Bing Search] Error text on VIetnamese text

### ISSUE THREAD

**Issue by trdbau** [raycast/extensions#6897]
### Extension

https://www.raycast.com/maver1ck/bing-search

### Description

When I typed something in Vietnamese, the text went wrong.

### Steps To Reproduce

1. Inside Bing Search, type some Vietnamese words, then the UI went wrong

### Current Behaviour

<img width="798" alt="Screen Shot 2023-06-01 at 15 25 53" src="https://github.com/raycast/extensions/assets/33424891/808ebfd8-91c5-4897-a81a-6680d438b5cc">

### Expected Behaviour

Show the correct one

**Comment by maver1ck** [comment]
Hi @trdbau 
I think this will be fixed in https://github.com/raycast/extensions/pull/6764

**Comment by trdbau** [comment]
@maver1ck thank you for the information. I will close it and open a new one when if the PR #6764 doesn't fix this issue

**Comment by trdbau** [comment]
@maver1ck and, do you know when will the PR been merged?
