### ISSUE TITLE
kill all processes listening to a specific port (lsof -n -i :8000)

### ISSUE THREAD

**Issue by Matlor** [raycast/extensions#6900]
### Extension

https://www.raycast.com/rolandleth/kill-process

### Description

kill all processes listening to a specific port (lsof -n -i :8000)

**Comment by rolandleth** [comment]
The idea is nice, but the purpose of the extension is to 1. list all processes, sorted by some kind of usage and 2. kill one of them, filtering by name/process. It also makes use of `ps`, which doesn't offer port information. I don't see how this could be implemented.
