### ISSUE TITLE
[Hue] "Failed to link with the Hue Bridge"

### ISSUE THREAD

**Issue by eta-orionis** [raycast/extensions#6904]
### Extension

https://www.raycast.com/pindab0ter/hue

### Description

The extension used to work perfectly. Since about 1-2 months it requests to link with the Hue Bridge. The linking however does not work, with the message "Failed to link with the Hue Bridge". There is nothing in the Raycast logs.

### Steps To Reproduce

In MacOS Monterey 12.6.6, latest Raycast, latest Hue extension. Give any command from the extension and try to connect to the Bridge when asked.

Bridge firmware: latest (1.57.1957200040, set to automatically update). 
Raycast 1.52.1
All extensions are updated to latest version.

The Hue extension's "i" icon links to 
https://github.com/raycast/extensions/blob/66c73a9e96efecfa13b22337e22cd7c5c6af0701/extensions/hue/README.md

### Current Behaviour

"Failed to link with the Hue Bridge"

Philips Hue App works without a problem and never asked to relink to the Bridge
iOS Home works without a problem and also never asked to relink
Other 3rd party apps using the Bridge work without any problem

### Expected Behaviour

The extension links successfully and works.

**Comment by RishabSwift** [comment]
Having this same issue, except in my case it just doesn't seem to connect after installing the extension

**Comment by pindab0ter** [comment]
A new update (#6006) has just been pushed. Please let me know if this changes your situation.

If it doesn't, at least you will be able to manually enter the IP address and/or API key for your Hue Bridge.

**Comment by eta-orionis** [comment]
Thanks! 
It still did not connect, but I could enter IP and username manually. 

However, now it cannot connect to the Bridge for a different reason. Error message: "Failed to link with bridge: Self-signed cert".

The Hue bridge uses a self-signed cert  by design from Philips and I cannot change it anywhere. Note that the certificate is also re-generated with each reboot of the Hue bridge.

The extension seems to use https and I don't see a way to force a http connection  or to tell it to accept self-signed certs.
