### ISSUE TITLE
[OneNote] ...

### ISSUE THREAD

**Issue by EdFenner** [raycast/extensions#6913]
### Extension

https://www.raycast.com/alewandowski/onenote

### Description

When Search Notes is activated, returns an error "Microsoft OneNote is not installed"
OneNote is installed and can be launched from raycast, so it is available.

### Steps To Reproduce

1. Active Search Notes
2.  No configuration available
3. Error "Microsoft OneNote is not installed"
![2023-06-02_08-09-19](https://github.com/raycast/extensions/assets/3855021/2a9ae4ea-136e-46e0-a386-9129ee0a38b8)

### Expected Behaviour

Find OneNote

**Comment by majoma7** [comment]
Issue still persists - any other people with the same issue?

**Comment by EdFenner** [comment]
I gave up
