### ISSUE TITLE
[Apple Notes] Error Encountered - "Cannot search notes: database disk image is malformed"

### ISSUE THREAD

**Issue by shutuprishi** [raycast/extensions#6916]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

Hi, 

Whenever I attempt to search for notes within the application, the aforementioned error message is displayed on the screen.
"Cannot search notes database disk image is malformed"

I have tried reinstalling the application and even my computer, but the problem persists.

### Steps To Reproduce

1. Launch Raycast
2. Type "search notes" to access the command to search Apple Notes
3. Press Enter
4. The error message "Cannot search notes database disk image is malformed" appears instead of displaying the search results.

**Comment by axsuul** [comment]
Also seeing this issue – tried re-installing the extension but still getting the error.

**Comment by aydinmustafacan** [comment]
Also seeing this issue, reinstalling does not help

**Comment by KendrickMcD** [comment]
Also having this issue, reinstalling did not fix for me either.

**Comment by michalAI** [comment]
Same problem.

**Comment by Han-Ya-Jun** [comment]
Same problem.

**Comment by adoolaard** [comment]
Same problem. I tried resetting all the Privacy & Security permissions on my Mac, hoping that this issue would be solved with fresh permissions. Unfortunately, it didn't work.

**Comment by adrianclark1** [comment]
Also having this issue. Alfred is able to search my Apple Notes, but the Raycast extension returns this error.

**Comment by neilpatel121** [comment]
I've identified the bug in the Notes extension. It seems to stem from a particular type of note. Specifically, any Apple note that is accompanied by a file attachment (not an image) appears to trigger the issue. Once I removed the file attachment from the problematic note, I was able to successfully operate the extension. This issue occurred while utilizing image effects.

**Comment by BlackJoker90** [comment]
Any procress?

**Comment by 1activegeek** [comment]
Would love to hear any progress? Disappointing to see such key plugins like this not receiving the attention. Based on a plethora of other opened and then closed issues - this is a major problem, but not solution in sight at the moment outside of some complicated SQLite instructions or the dreaded sign out of and sign into your AppleID. That is a bigger task these days with the amount of things centered around it unfortunately.

**Comment by thomaslombart** [comment]
Hey there, the issue should be fixed as part of the [latest update](https://github.com/raycast/extensions/pull/11450). I also added some improvements here and there. Let me know if it works fine for you!
