### ISSUE TITLE
[Raindrop.io] ...

### ISSUE THREAD

**Issue by nukesean** [raycast/extensions#6920]
### Extension

https://www.raycast.com/lardissone/raindrop-io

### Description

It works for a while and then always fails eventually. I suspect it may have to do with Raycast Pro's cloud sync feature? I even created separate test tokens for each machine hoping that would fix the problem, but it doesn't; and since it appears the token can only be entered into the extension immediately after it's installed (it disappears from settings afterwards), there's no way for me to tell if this extension is syncing the token across machines.

### Steps To Reproduce

1. Install extension
2. Enter token
3. Use without issue
4. Repeat steps above on another machine
5. Return to original machine later and find the extension no longer works

### Current Behaviour

Extension eventually fails to retrieve user details:

![image](https://github.com/raycast/extensions/assets/69487134/554a3a9b-bc92-4479-b1bc-8fa6c0853155)

### Expected Behaviour

It should continue working properly across all machines even when Raycast Pro Cloud Sync is enabled.

**Comment by lardissone** [comment]
@nukesean it's weird, but I'm not using Cloud Sync (I use it only in one computer). Not sure if anyone else is experiencing the same.
If that's the problem, I assume it has not much to do with the extension, but how Raycast handles extensions' settings.

/cc @pernielsentikaer

**Comment by nhojb** [comment]
Should be fixed in the *1.57* release coming this week.

**Comment by nukesean** [comment]
Awesome! But out of curiosity, where did you see them say this would be fixed in the next update? Thanks!

**Comment by nhojb** [comment]
I'm an engineer at Raycast 😉

**Comment by nukesean** [comment]
That’s cheating! 😜
