### ISSUE TITLE
[Google Bard] ...

### ISSUE THREAD

**Issue by nukesean** [raycast/extensions#6921]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

The extension always returns the error: "Unable to reach Bard at this time." This has occurred over the last couple days on every machine I've tested. The cookie I entered is `__Secure-1PSID`, as specified in the instructions, and I also made sure to include the period at the end.

### Steps To Reproduce

1. Follow the instructions provided
2. Attempt to use the extension

### Current Behaviour

Fails to reach Bard.

### Expected Behaviour

Work as intended.

**Comment by EvanZhouDev** [comment]
I am sorry this doesn't work for you. I just installed it from the store right now and put in my own key. It works completely fine. Please refer to #6794 for more information, as I try to work this out for everyone.

**Comment by EvanZhouDev** [comment]
Will be closing. Again, follow #6794.

@raycastbot close this issue
