### ISSUE TITLE
[Unsplash] ...

### ISSUE THREAD

**Issue by nanduldas** [raycast/extensions#6935]
### Extension

https://www.raycast.com/eggsy/unsplash

### Description

Getting error "The redirect uri included is not valid"

### Steps To Reproduce

1.Search Images
2.Click Authorise

**Comment by eggsy** [comment]
Please check the extension's store page. You have to manually configure the redirect uri.

**Comment by eggsy** [comment]
@raycastbot close this issue as it is inactive for a while.

**Comment by eggsy** [comment]
@raycastbot close this issue
