### ISSUE TITLE
[bitwarden vault] ... cannot reach the custom url option in settings

### ISSUE THREAD

**Issue by yieldhog** [raycast/extensions#6937]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Hi --

In the settings, I am unable to tab or scroll down to the option to input my self hosted custom url. I am unable to resize the Raycast settings box in order to do so. See screenshot

<img width="1005" alt="Screenshot 2023-06-04 at 8 48 52 AM" src="https://github.com/raycast/extensions/assets/3329021/8140ec49-3d1e-47f0-a567-ece34c1ab066">

### Steps To Reproduce

Raycast settings

**Comment by jomifepe** [comment]
Hello, I'm sorry, but it's unlikely that this issue is related to the Bitwarden extension.

**Comment by yieldhog** [comment]
Apologies, you're right -- thanks for responding. It actually happens for all menus. My resolution/etc is standard, can't seem to figure out how to increase the size of Raycast settings menus.
