### ISSUE TITLE
[Summarize YouTube Videos with AI] Expand on item

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#6938]
### Extension

https://www.raycast.com/iKasch/summarize-youtube-video-with-ai

### Description

Love this extension. Would be great if I could ask the extension to expand upon a certain part of the summary, based on the content of the video. Or possibly take me to the related part of the video.

**Comment by iKasch** [comment]
@christianmagill Jumping to the part of the video is a great idea, I will look into this! I do have the timestamps of the things being said but connecting them to the summarized part you are looking at will be very tricky.

What exactly do you mean by "expand"? Do you want to get more info about this section or talk to AI about the context you "expand on"?

Thanks for the kind words ✌️

**Comment by iKasch** [comment]
Got it, thanks. Right now the summarisation process is pretty "dumb" and not context aware. It's a nice idea though, I will try to come up with a way to get more out of the context. Thanks for the ideas!

**Comment by iKasch** [comment]
@christianmagill it's been some time, but there was a bigger update to the extension now which should do pretty much what you asked for. https://github.com/raycast/extensions/pull/15972
Hope you like it!
