### ISSUE TITLE
[Toothpick] Update the command name with the device name

### ISSUE THREAD

**Issue by svallory** [raycast/extensions#6939]
### Extension

https://www.raycast.com/briankosw/toothpick

### Description

After picking a device, instead of showing "Connect Favorite Device #x"

### Who will benefit from this feature?

Anyone that forgets what is the order of their 3 favorite BT devices

### Anything else?

Maybe this could be promoted to a Raycast feature called "dynamic commands". where command names can contain variables pointing to settings

**Comment by VladCuciureanu** [comment]
AFAIK, this is not possible in Raycast. It's a good idea, but there's no way to implement such a thing.

**Comment by VladCuciureanu** [comment]
@raycastbot close this issue

**Comment by VladCuciureanu** [comment]
> @VladCuciureanu this would be an ugly hack... but when does Raycast read information about installed extensions or scripts? Is there a way to trigger it? What if the extension managed script files and updated them when settings changed?

Raycast extension commands are defined before publishing the extension, inside package.json, which is not modifiable in any way, as far as I know. You are welcome to test this out by forking the extension, though.

**Comment by svallory** [comment]
Sure there is! It's not pretty though :) The script below should work for an installed extension. It doesn't work for extensions in development because they are constantly recompiled and the deployed package.json gets overwritten.

```
import { getPreferenceValues } from "@raycast/api";
import { writeFile } from 'fs';
import { join } from 'path';

// note that after compilation, package.json will be in the same folder as this code
const pkgPath = join(__dirname, 'package.json');

export default async () => {
  const pkg = require(pkgPath);
  logEnvironment();
  const { favoriteDevice1, favoriteDevice2, favoriteDevice3 } = getPreferenceValues();

  const commands = [];

  for (const command of pkg.commands) {
    console.log('checking', command.name);
    if (favoriteDevice1 && command.name == 'connect-favorite-device-1') {
      command.title = `Connect Device: ${favoriteDevice1}`;
    }
    else if (favoriteDevice2 && command.name == 'connect-favorite-device-2') {
      command.title = `Connect Device: ${favoriteDevice2}`;
    }
    else if (favoriteDevice3 && command.name == 'connect-favorite-device-3') {
      command.title = `Connect Device: ${favoriteDevice3}`;      
    }

    commands.push(command);
  }

  pkg.commands = commands;
  
  const json = JSON.stringify(pkg, null, 2);
  const data = new Uint8Array(Buffer.from(json));
  
  console.log(`writing pkg to ${pkgPath}`);
  console.log(json);
  return writeFile(pkgPath, data, (err) => {
    if (err) {
      console.error(err);
    }
  });
};
```

**Comment by VladCuciureanu** [comment]
Thanks for the example! I will check with the Raycast team if this is a good approach or if this is going to be patched later on.

**Comment by VladCuciureanu** [comment]
Update from Raycast Team:

> This isn't going to work for published extensions, we don't read the package.json after it's installed. However, you could update the subtitle of the command using updateCommandMetadata which I just realise that we haven't documented except here: https://developers.raycast.com/information/lifecycle/background-refresh#running-in-the-background

So runtime package.json modifications aren't possible but I'll look into the dynamic command names 👍🏻

**Comment by svallory** [comment]
Awesome, @VladCuciureanu! I actually found out about  `updateCommandMetadata`. There were 2 problems with using that though:

1. It updates the subtitle for all commands
2. The only way to trigger the update would be to use background refresh. This would be a waste of resources in this case since I would have to set an interval for the refresh, but the subtitle only changes once the preferences change. 

If I may... my suggestion would be to:

1. Implement an onPreferencesUpdated event to the [command lifecycle](https://developers.raycast.com/information/lifecycle). This lifecycle event hook architecture is a good foundation and could later be expanded to include `onInstalled`, `onEnabled`, `onDisabled`, etc
2. Extend the `updateCommandMetadata` to take in the `name` of the command to be updated and allow it to modify other properties

Another solution that can also be powerful would be to allow extensions to install and remove `script commands` in Raycast managed, per extension, scripts folder.

Script commands have the command documentation in the file itself and could be generated using a template.

Let me know if I can help with anything. I'm liking this tool so much that I almost went checking for open positions with guys hahahaha

Seriously, my productivity with Raycast is insane!

**Comment by VladCuciureanu** [comment]
I know this is not really what you requested but I hooked the command's subtitle to the device name set in preferences to make it easier to distinguish between the favorite device commands. The command's subtitle should update on running the command, so run the command and then the subtitle should update.

**Comment by svallory** [comment]
Hey @VladCuciureanu, that's awesome! The goal was to tell the user which device was connected to the favorite device slot and you hit it. Thank you so much! :)
