### ISSUE TITLE
[Tmux Sessioner] ...

### ISSUE THREAD

**Issue by chrihart** [raycast/extensions#6940]
### Extension

https://www.raycast.com/loishy/tmux-sessioner

### Description

I've installed the extension and it seems as if tmux can not be found in my path.   I used macports to install it.  Tmux clearly works when I use it in the terminal directly regardless as to if I use kitty or terminal.  But there seems to be an error with the tmux sessioner extension.   None of the commands work with exception of setting the default terminal.  Which have done. 

_$which tmux_
/opt/local/bin/tmux

### Steps To Reproduce

1. using macports
2. install tmux
3. install raycast
4. install tmux sessioner extension
5. try to run

### Current Behaviour

Nothing works.  Error "Failed to create session" is presented in lower left corner.

### Expected Behaviour

A new session would be created.

**Comment by louishuyng** [comment]
Hi @chrihart thanks for your raising

It seems like the tmux binary can not execute inside Raycast environment. 

From my guess, we can have two ways to solve that 

### First Solution
Install `tmux` using a **homebrew package manage**r and the path of the `tmux` should be like this

```bash
$ which tmux
$ /opt/homebrew/bin/tmux

```
### Second Solution
Moving tmux binary from `/opt/local/bin/tmux` to `/opt/homebrew/bin/tmux` and make sure `$PATH` environment variable include this path `/opt/homebrew/bin/tmux`
