### ISSUE TITLE
[1Password] extension fails with `i?.filter is not a function` error

### ISSUE THREAD

**Issue by digitalbase** [raycast/extensions#6944]
### Extension

https://www.raycast.com/khasbilegt/1password

#### Error:
```
TypeError: i?.filter is not a function

Ji:Items.tsx:11:57
a9:item-list.js:63:3030
    at d9
Nr:index.js:6:2490
```

### Steps To Reproduce

install latest 1password8
install latest raycast 1password extension
install 1password OP

<img width="230" alt="Screenshot at June  05 - 000581@2x" src="https://github.com/raycast/extensions/assets/849282/080e7bca-5004-4452-9332-dd478517a96e">

When i try to load 1password bookmarks:

<img width="765" alt="Screenshot at June  05 - 000582@2x" src="https://github.com/raycast/extensions/assets/849282/bc46a783-717e-4258-9f0e-681a0546e76f">

### Current Behaviour

passwords don't get listed. 

### Expected Behaviour

see an overview of password so i can complete or edit

**Comment by pernielsentikaer** [comment]
Do you know how to debug it yourself? You can  Fork the extension to your local environment and that way when running `npm run dev` you should get a better error and can debug it locally

![Raycast-SfRc4UFW@2x](https://github.com/raycast/extensions/assets/38033107/cf343ce5-11a2-467c-ab11-d0e41a9e275c)
