### ISSUE TITLE
[Jira Search (Self-Hosted)] Pin Entity on the top

### ISSUE THREAD

**Issue by Ernest0-Production** [raycast/extensions#6945]
### Extension

https://www.raycast.com/emanguy/jira-search-self-hosted

### Description

Please add action to pin tasks, boards, projects on the top of search result by default.

Here is example of Xcode project search plugin:
<img width="749" alt="Снимок экрана 2023-06-05 в 13 18 06" src="https://github.com/raycast/extensions/assets/19843524/73ac30cd-9d91-4998-9b97-c77d3066ce63">

**Comment by svenwiegand** [comment]
Nice idea, though I’m currently lacking Time to implement this.
