### ISSUE TITLE
[Authy] ...

### ISSUE THREAD

**Issue by dlandes77** [raycast/extensions#6949]
### Extension

https://www.raycast.com/guga4ka/authy

#### Error:
```

```

### Steps To Reproduce

Every time I try to access Authy through Recast

### Current Behaviour

it took a while to get the account to work (would get stuck waiting for a response after approving from my phone). Once it did I was always directed to the "something went wrong" screen, when looking for an account I need an OTP for. Sorry I am unable to give more detail.

### Expected Behaviour

It should give me an OTP

**Comment by guga4ka** [comment]
@raycastbot close this issue
seems like #5880
