### ISSUE TITLE
[Hookmark Search] ...

### ISSUE THREAD

**Issue by andrewmglaser** [raycast/extensions#6951]
### Extension

https://www.raycast.com/QIanGua/search-hookmark

### Description

I'm using the SetApp version of Hookmark. I've also used the regular download version Hookmark (beta). I think Raycast may be confused about which version to use. I'm not able to use the extension's features  although it does launch the Setapp version of Hookmark after being prompted in the action bar.

### Steps To Reproduce

- Install Hookmark Search extension
- Try any Hookmark Search extension command

**Comment by QIanGua** [comment]
Hi @andrewmglaser. After the Setapp's Hookmark is launched, what's the response of Raycast if you run "Search Hookmark"?

**Comment by andrewmglaser** [comment]
@QIanGua it fails in a loop, e.g., it just says 'Hookmark is not running' and prompts be to launch it again

**Comment by realCrush** [comment]
Same issue here, Hookmark app from SetApp would never run `Search Hookmark` command successfully.

**Comment by realCrush** [comment]
BTW, for Craft.app, almost all commands from this extension would fail.

**Comment by QIanGua** [comment]
@realCrush  There are a few minor bugs preventing the stable launch of Hookmark. I may require additional time to ensure its robustness.

**Comment by realCrush** [comment]
> @realCrush There are a few minor bugs preventing the stable launch of Hookmark. I may require additional time to ensure its robustness.

Yes, in fact, I have already reported this bug on the Hookmark forum. They haven't replied yet: [Hookmark Shortcut and AppleScript for Craft fail - Bug Reports - Hookmark Forum](https://discourse.hookproductivity.com/t/hookmark-shortcut-and-applescript-for-craft-fail/7220)
