### ISSUE TITLE
Spotifu menu bar not working

### ISSUE THREAD

**Issue by Gubscruz** [raycast/extensions#6953]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

The songs are not appearing on the menu bar. I have space for it

### Steps To Reproduce

Probably if you enable the spotify menu bar when there's no room for it and then make room

**Comment by peduarte** [comment]
There's been a bunch of improvements recently. Can you check if this is still an issue for you please? Thanks

**Comment by peduarte** [comment]
Assuming it's fine now, please re-open if you encounter any issues :)
