### ISSUE TITLE
[GitLab Docs] Documentation search no longer working

### ISSUE THREAD

**Issue by pedropombeiro** [raycast/extensions#6959]
### Extension

https://www.raycast.com/saschaeggi/gitlab-docs

### Description

The documentation search has stopped working recently, and no search results come up, ever.

### Steps To Reproduce

In the GitLab Docs extension, type `GitLab` or any other word.

### Current Behaviour

<img width="734" alt="image" src="https://github.com/raycast/extensions/assets/138074/22821fb6-5ba7-414b-99f0-2d5fea83484f">

### Expected Behaviour

A list of the occurrences in the GitLab documentation.

**Comment by saschaeggi** [comment]
We're working on integrating our new search service.

**Comment by saschaeggi** [comment]
PR created: https://github.com/raycast/extensions/pull/7881
