### ISSUE TITLE
[Jira] Filter input should be available while loading

### ISSUE THREAD

**Issue by glekner** [raycast/extensions#6960]
### Extension

https://www.raycast.com/raycast/jira

### Description

I want to be able to type a query while initial loading, this behavior was supported in the deprecated extension.

![image](https://github.com/raycast/extensions/assets/24938324/173e74a4-41f1-48ba-b37d-bd57ccc2571e)

### Steps To Reproduce

1. Open Jira "Open Issues"
2. Start to type
3. Nothing happens while loading

### Current Behaviour

Typing while loading does not register

### Expected Behaviour

The filter input should be visible while loading and the typing should register while loading

**Comment by glekner** [comment]
cc @bengry

**Comment by igor9silva** [comment]
I have sent a PR #7382.
