### ISSUE TITLE
[Timers] Option to make timer menubar hidden unless there is an active timer

### ISSUE THREAD

**Issue by rjhewitt3** [raycast/extensions#6963]
### Extension

https://www.raycast.com/ThatNerd/timers

### Description

I like to keep my menubar as clean as possible, and having a permanent icon there for timers (which I only use on occasion) doesn't work for me. I'd much rather only see a representation there when I have a timer actively running. As a reference, the "My Schedule" menubar command has a similar setting so that events only show up when they're a defined amount of time away.

**Comment by lokot0k** [comment]
@rjhewitt3 I can totally understand you, I also like my menubar tidy. Did you try some organizing utils? For example: https://github.com/dwarvesf/hidden If not, then you will find this useful

**Comment by pernielsentikaer** [comment]
Closing this since its now merged 🙂
