### ISSUE TITLE
[Jira] "Show Details" Action is present on details view

### ISSUE THREAD

**Issue by kgrhartlage** [raycast/extensions#6971]
### Extension

https://www.raycast.com/raycast/jira

### Description

When viewing the details of a specific ticket, the default action for me is "Show Details", which obviously does not work in this scenario.

<details>
<summary>screenshot</summary>

<img width="862" alt="CleanShot 2023-06-07 at 09 21 15@2x" src="https://github.com/raycast/extensions/assets/42832087/dfad45da-0fc5-4649-ae6a-71b0a6e65629">

</details>

I looked at the code and I don't see how that action could possibly show up, since the `showDetailsAction` [is not being passed down ](https://github.com/raycast/extensions/blob/1b28f23f10a584b6ac1f09f3641761ef4a10d207/extensions/jira/src/components/IssueDetail.tsx#L147). Moreover, when I run the extension in development mode this behaves as expected and the "Show Details" action does **not** show up on the details view. But when I do the same thing with the extension installed from the store, the  "Show Details" action is always present. And it's driving me nuts. I tried re-installing the extension. Any idea why this is happening for me?

### Steps To Reproduce

One of several user paths:

1. Trigger "Active Sprints" command
2. Trigger "Show Details" actions
3. Observe "Show Details" being the default action on the details page

### Current Behaviour

"Show Details" action is the default action on both the list view and the details view

### Expected Behaviour

"Show Details" action should not be present on the details view

**Comment by thomaslombart** [comment]
Thanks for bringing up the issue. I can reproduce both in production and locally. I'm confused on `showDetailsAction` though. Where have you seen that in the codebase? I can't find it.

Anyway, from what I can see, this bug has been there for quite some time. I'll fix it this week 😊

**Comment by kgrhartlage** [comment]
> I can reproduce both in production and locally. I'm confused on `showDetailsAction` though. Where have you seen that in the codebase? I can't find it.
> 

It's a prop of `IssueActions`, no? It's used on the list view, see [here](https://github.com/raycast/extensions/blob/1b28f23f10a584b6ac1f09f3641761ef4a10d207/extensions/jira/src/components/IssueListItem.tsx#L57). I'm starting to wonder if I'm looking at the right extension code... 😕 

Thanks for looking into it, much appreciated 🙏

**Comment by thomaslombart** [comment]
Not on the [main](https://github.com/raycast/extensions/blob/main/extensions/jira/src/components/IssueListItem.tsx) branch. Something got probably changed in between.
