### ISSUE TITLE
[Google Bard] ...

### ISSUE THREAD

**Issue by tashawnjones** [raycast/extensions#6975]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

Followed instructions, but the extension does not work for me at all. I get an error for every command.

### Steps To Reproduce

1. Open Raycast
2. Initiate a Bard extension command
3. Error immediately shown (this happens for all Bard commands)is immediately shown

### Current Behaviour

Error shown for all Bard commands

### Expected Behaviour

Bard response after command entered

**Comment by iamhenry** [comment]
same here. i copied the required ID from Bard into the extension but none of the commands work

**Comment by nickwild-999** [comment]
Yes me too I get "Failure to fetch Bard"

**Comment by EvanZhouDev** [comment]
Please try clearing your cookies, logging in, and getting a new PSID

**Comment by asamofal** [comment]
> Please try clearing your cookies, logging in, and getting a new PSID

Thanks, it helped.
