### ISSUE TITLE
clickup

### ISSUE THREAD

**Issue by tfraley** [raycast/extensions#6978]
### Extension

https://github.com/raycast/extensions/blob/6e8861cfcd2b3ca94ae9b79dafdc507cda91dc75/extensions/clickup

### Description

Would be nice to include a description of how to get the ID's for the extension. 

I've tried a number of times but am unable to get this extension to work.
If there was an explanation of the IDs I could rule out human error and call it a bug. 
But at this point all I can say is it doesn't work. 

### Steps To Reproduce

install plugin, 
add, Default list ID 
Add Default Space ID
Add Default Team ID 

Then open up tasks explorer and get error 
Open up and make a quick, quick capture and get error 

### Current Behaviour

Error "Something went worng"

### Expected Behaviour

It working

**Comment by Ali-Parandeh** [comment]
Thanks for opening the bug report. It may be that the click up API is updated. I'll put in a fix tonight :)
