### ISSUE TITLE
Use of environment variables in configuration fields

### ISSUE THREAD

**Issue by bhean** [raycast/extensions#6979]
### Description

I was trying to use the Obsidian extension, but I need to configure the path to the Obsidian Vault, which in MacOS is normally stored in: `/Users/USERNAME/Library/Mobile Documents/iCloud~md~obsidian/Documents/`

I use Raycast Pro in 2 devices (work and personal) and my username is not the same in these both, so if I configure the path in one device, only works there but not in the other device (because the path is not the same due the username)

It would be great if this `PATH` field in the configuration allows the use of environment variables. In this case, I could use `${USER}` to define the path, and it'll be valid everywhere

### Who will benefit from this feature?

Everyone that use more than one device (for example a laptop for work and a different laptop for personal use) with different usernames in each one

### Anything else?

![CleanShot 2023-06-07 at 19 22 58](https://github.com/raycast/extensions/assets/6599289/d0a58ec2-01ab-450c-94ac-04a9a4fe60b2)

**Comment by mathieudutour** [comment]
That's something that can already be handled in the extension (either by handling `${USER}` or more commonly `~`), no need for an API for that. If it doesn't work already, I'd encourage you to open an extension issue instead of an API one.

**Comment by bhean** [comment]
Thanks for the reply...
I didn't know that this feature already exists (is not documented). 

Anyway, I tried it... and is not working, so I'll open an issue about that,

Thanks!

**Comment by mathieudutour** [comment]
It's up to the extension to support it :) Raycast has no idea that this text field is a file path
