### ISSUE TITLE
Harvest

### ISSUE THREAD

**Issue by bchopson** [raycast/extensions#6980]
### Extension

https://www.raycast.com/eluce2/harvest

### Description

Currently, timers show time in fractions of an hour (i.e. 1.75). It would be nice to have an option to view timers in HH:MM, like 1:45 instead of 1.75, as in the Harvest web and desktop UIs.

**Comment by eluce2** [comment]
This setting should be controlled by whichever time format you have set in your harvest account settings, although these are typically controlled by the company admin and not per user. Is this consistent with what you're seeing? I do agree that it would be nice to specify your own preference in the Raycast extension
