### ISSUE TITLE
[Lorem Ipsum] ... but with English words instead 😀

### ISSUE THREAD

**Issue by thomarto** [raycast/extensions#6992]
### Extension

https://www.raycast.com/AntonNiklasson/lorem-ipsum

### Description

I appreciate that this extension is called 'Lorem Ipsum' so I understand the irony of this request...

...but might there be a way for this extension (or is there potential for a new one) to generate sentences and paragraphs of text using English words instead of Lorem Ipsum?

Even though it's the standard placeholder text, I've always found blocks of Lorem Ipsum difficult to look at and distracting because it's, essentially, nonsense. It's also not fun to use it any documents or layouts because almost every word gets picked up and underlined by the spell checker, giving my ageing eyes a hard time.

The sentences wouldn't even have to make sense – just having the words in English would be enough for my brain to stop bugging me about wonky placeholder text.

Many thanks.

### Who will benefit from this feature?

Everyone, I hope :-)

### Anything else?

**My eyes!!** 😵 👀

<img width="875" alt="My eyes!" src="https://github.com/raycast/extensions/assets/26119379/40691c16-dcbe-4eb1-8150-66be5c54d40a">

**Comment by AntonNiklasson** [comment]
Interesting! I like this type of "gibberish" since it's very clear that it is indeed just placeholder data. I don't have a strong opinion though
