### ISSUE TITLE
[Music] ...

### ISSUE THREAD

**Issue by wty20060888** [raycast/extensions#6993]
### Extension

https://www.raycast.com/fedevitaledev/music

#### Error:
```

```

### Steps To Reproduce

1. In Raycast Version 1.53.0
2.  Run `Play` command, same satuation with command `Toggle Play/Pause` `Next Track` `Previous Track` etc
3.  show something like "Something went wrong", but the command functions fine.

**Comment by wty20060888** [comment]
<img width="862" alt="截屏2023-06-10 07 59 27" src="https://github.com/raycast/extensions/assets/49235401/8582156b-43bc-4097-a0e1-fadabae4583f">

**Comment by danpalmer** [comment]
Hi, are you able to copy any log from the action panel as the screen says?

Is this reproducible every time you run the Pause command? How about other commands? Are your Mac and Raycast up to date?

**Comment by wty20060888** [comment]
Error log：”Could not load command”

Is this reproducible every time you run the Pause command?  ------Yes

How about other commands? -----`Toggle Play/Pause` `Next Track` `Previous Track` these commands also show the error

MacOS version: Ventura 13.4
Raycast version :1.53.0

**Comment by Rawnly** [comment]
I don’t think that’s a bug from the extension itself. The pause / play commands are just bare AppleScript. 

Can you try running the following in the Scripts app? 

> tell application “Music” to pause

Maybe this could help to understand what is happening

**Comment by wty20060888** [comment]
I think you're right, it's not a plugin issue, I'm closing it and trying to write a script to run it myself.
@raycastbot  close this issue

**Comment by kastov** [comment]
> I don’t think that’s a bug from the extension itself. The pause / play commands are just bare AppleScript.
> 
> Can you try running the following in the Scripts app?
> 
> > tell application “Music” to pause
> 
> Maybe this could help to understand what is happening

I had the same  #6985 , I tried to create Script and it works fine. Are you sure that this is not related to Raycast and extension?
'Add to library' don't work at all. 
```
Could not load command
```

**Comment by wty20060888** [comment]
@kastov  The script works, thanks.Hope the developers will fix this.

**Comment by Rawnly** [comment]
@wty20060888 @kastov sorry for the inconvenience, something must have changed in the last updates. I'm delivering a fix right now.

**Comment by wty20060888** [comment]
@Rawnly Great!

**Comment by wty20060888** [comment]
Hello：
I recently encountered a problem where I can't access the Raycast website, and my IP is currently in China. What is the cause of this and how can it be solved?
