### ISSUE TITLE
[Elgato Key Light] Command fails in latest raycast

### ISSUE THREAD

**Issue by qor72** [raycast/extensions#6995]
### Extension

https://www.raycast.com/thomas/elgato-key-light

#### Error:
```
Could not load command
```

Raycast v1.53.1
Elgato Plugin, latest -- tried uninstalling and reinstalling.

### Steps To Reproduce

1. Install Extension
2. Try to turn on/off the light using the "toggle On/Off" command
3. Error will be reported by Raycast

### Current Behaviour

Raycast throws an error

### Expected Behaviour

The Elgato light targeted is toggled.

**Comment by omarshahine** [comment]
This issue is caused by the issue I detailed in this bug:
https://github.com/raycast/extensions/issues/7010#issuecomment-1587703279 
and there is another bug here
https://github.com/raycast/extensions/issues/6986#issuecomment-1582142246

**Comment by qor72** [comment]
Appreciate the update. Where's the "close as duplicate" option?
