### ISSUE TITLE
[Timers] ...

### ISSUE THREAD

**Issue by amjad1233** [raycast/extensions#6999]
### Extension

https://www.raycast.com/ThatNerd/timers

#### Error:
```
Can't load the time 
```

### Steps To Reproduce

1. MacBook Pro M2
2. Add the extension
3. Add a shortcut `time60`
4. Try a shortcut on Raycast
5. It will go to the timer window 
6. But fail

### Current Behaviour

Error

### Expected Behaviour

Timer to be started

**Comment by ThatNerdSquared** [comment]
Hi @amjad1233, thanks for the report - looks like this bug has been here for a while 🤦‍♂️ I've just pushed a commit to fix it in my latest PR, so it'll be patched in a few days.
