### ISSUE TITLE
[Switch Game Play History] English name of games

### ISSUE THREAD

**Issue by jag-k** [raycast/extensions#7001]
### Extension

https://www.raycast.com/kvdo2/switch-game-play-history

### Description

Please, give an English name of games in grid (if it's possible)

<img width="1000" alt="switch-game-play-history 2023-06-09 at 12 48 04" src="https://github.com/raycast/extensions/assets/30597878/b662c800-aa61-40e0-9ce5-62d508b3cb79">

### Who will benefit from this feature?

All people, who can't read Japanese

**Comment by kvdo2** [comment]
The title language of the game depends on the area of your account. I will try to provide english title support.
