### ISSUE TITLE
[Google Workspace] Open files with the wrong Google account

### ISSUE THREAD

**Issue by MarcBickel** [raycast/extensions#7003]
### Extension

https://www.raycast.com/raycast/google-workspace

### Description

Whenever I open a Google Drive file through this extension, it opens with the wrong Google account. 
I am logged in the extension with my professional account, and this same account is the default one in my browser (Arc). 

However when I open a file, it opens with my personal account selected. 

### Steps To Reproduce

1. Log in the extension with a google account
2. Set this same account as default in google drive in the browser (Arc)
3. Open google file through the extension
4. in the little Arc window that opens, check the account used in the top right. It's the wrong one. 

### Expected Behaviour

The professional account is the one selected.

**Comment by thomaslombart** [comment]
On which command does this happen?

**Comment by thomaslombart** [comment]
Could you test it out on other browsers such as Safari, Firefox, or Google Chrome? I'm not able to reproduce it.

**Comment by MarcBickel** [comment]
I get the same problems on safari. I do not use the other two, so cannot test, apologies. 

￼￼

**Comment by MarcBickel** [comment]
I see now that my screenshots sent by mail do not come up here. Apologies. Here they are:
![Screenshot 2023-06-15 at 14 46 00](https://github.com/raycast/extensions/assets/13186695/6bb72a23-c185-44e3-a83a-67baf54625bc)
![Screenshot 2023-06-15 at 14 45 54](https://github.com/raycast/extensions/assets/13186695/d440d221-8a39-4583-94ef-18c6f1dd18e6)
