### ISSUE TITLE
I have no idea what is wrong it not working suddenly [Authy] ...

### ISSUE THREAD

**Issue by AboodeDaBOSS** [raycast/extensions#7006]
### Extension

https://www.raycast.com/guga4ka/authy

#### Error:
```
Error: Invalid base32 characters

uu:OtpListItem.tsx:72:38
fu:search-otp.js:42:4668
Ir:index.js:6:5510
    at ray-list
```
<img width="747" alt="image" src="https://github.com/raycast/extensions/assets/68856095/32ccb6b9-4000-4195-82d3-d7612de9b461">

### Steps To Reproduce

a

### Current Behaviour

a

### Expected Behaviour

a

**Comment by guga4ka** [comment]
have you recently changed backup password?

**Comment by guga4ka** [comment]
@raycastbot close this issue 
duplicate #5880
