### ISSUE TITLE
Apple Mail Features for Improvement - Move mail and viewing

### ISSUE THREAD

**Issue by joshebv** [raycast/extensions#7009]
### Extension

https://www.raycast.com/yug2005/mail

### Description

Thank you for building this extension. I would like to see the ability to view mail in the main inbox as opposed to recent mail or all mail which appears to include sent mail. Also, I would love the ability to move mail to a specific folder with typed input from the user.

### Who will benefit from this feature?

I believe anyone who follows a foldered/inbox zero approach would benefit from this feature.

**Comment by ikupenov** [comment]
It's difficult to figure out the name of the "main" mailbox as that varies between different mail providers, and AFAIK can be renamed. However, you can manually select the mailbox you'd like to view from the dropdown: 

![CleanShot 2023-06-12 at 15 31 27@2x](https://github.com/raycast/extensions/assets/13287035/878c7a36-8fd9-4c31-92ab-2e470811a928)

Right now mailboxes are being sorted based on the unread count. It's not ideal but not sure what would be a better alternative 😕.
