### ISSUE TITLE
[Image Modification] Allow enable/disable of image formats

### ISSUE THREAD

**Issue by tomgenoni** [raycast/extensions#7023]
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

This is a super handy extension but for my purposes I only ever need to convert to a few formats: svg, png, jpg. Would be nice if we could toggle the formats in the extension settings to hide the ones not needed. 

### Who will benefit from this feature?

Anyone who is converting images regularly but only needs a few formats. 

### Anything else?

Great extension! Thank you for making this.

**Comment by SKaplanOfficial** [comment]
I'll include it in the next release. Thanks for the suggestion!

<img width="407" alt="Screenshot 2023-06-18 at 20 02 25" src="https://github.com/raycast/extensions/assets/7865925/2b183604-8027-4043-81b1-5e7ec21399fa">
