### ISSUE TITLE
[Toothpick] Device Support MX Master 3

### ISSUE THREAD

**Issue by designedbyclu** [raycast/extensions#7024]
### Extension

https://www.raycast.com/briankosw/toothpick

### Description

<b>Device brand and model</b>
Logi MX Master 3 Mice

<b>Device data</b>
`{"device_address":"FB:71:EE:14:DB:9B","device_firmwareVersion":"MPM19.01_0015","device_minorType":"Mouse","device_productID":"0xB023","device_services":"0x400000 < BLE >","device_vendorID":"0x046D","device_connected":"true"}`

### Anything else?

Show battery level would be nice

**Comment by VladCuciureanu** [comment]
@raycastbot close this issue
