### ISSUE TITLE
Would you mind adding more action for LastPass

### ISSUE THREAD

**Issue by weijiany** [raycast/extensions#7033]
### Description

Now, lastpass extension could only search vaults from lastpass based on lastpass-cli, but for me, I want to only use this extension to manage all vaults, so that I could not install lastpass application and don't need to login it in web or others. vaults

### Who will benefit from this feature?

Supporting manage vaults actions for lastpass extension. For example:
- [ ] Adding vault
- [ ] Remove vault
- [ ] Edit vault

**Comment by mathieudutour** [comment]
Please open an extension feature request instead of an API one :)
https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cfeature+request&projects=&template=extension_feature_request.yml&title=%5BExtension+Name%5D+...
