### ISSUE TITLE
[Notion Page Search] Failed to query: invalid input

### ISSUE THREAD

**Issue by michomitu** [raycast/extensions#7044]
### Extension

https://www.raycast.com/reckoning-dev/search-notion

### Description

The extension was working properly, but now I'm only getting 'Failed to query: invalid input'.
I can't figure out what caused this error.
![Mimini Arc 11-06-2023 at 09 PM@2x](https://github.com/raycast/extensions/assets/97712653/11913c63-9e15-4f04-9bb9-31c73d53125f)

### Steps To Reproduce

1. install and configure the extension
2. search anything
Mac mini M1, macOS 13.4

**Comment by aaron2wh** [comment]
same issue

**Comment by jsonMartin** [comment]
Same here

**Comment by sadanand-singh** [comment]
there was some change in underlying notion search API. I am looking into it. However, I am traveling so it might take a little time. Any contributions would be welcome.

**Comment by geraldaddey** [comment]
There's broken change from notion. It has to do with a query type which now accepts an object as a value rather than a string. Patiently waiting for a fix 🤞🏾
