### ISSUE TITLE
[Visual Studio Code] Hide folders under Search Recent Projects

### ISSUE THREAD

**Issue by stevenlis** [raycast/extensions#7045]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

Add an option to hide folders under Search Recent Projects cmd.

The Search Recent Projects command currently returns all folders and workspaces ever opened in Visual Studio Code. It would be beneficial if I could limit the results to only the workspaces I have recently been using.

**Comment by macbookandrew** [comment]
@StevenLi-DS have you tried the filter menu to filter to just workspaces?

<img width="273" alt="Screen Shot 2023-06-11 at 5 05 20 PM" src="https://github.com/raycast/extensions/assets/784333/9daf501f-9bf6-4856-9387-f74c530c4df3">

**Comment by StevenLi-DS** [comment]
@macbookandrew I don't actually have anything displayed under that...

**Comment by Christopher-Hayes** [comment]
@macbookandrew I don't see that either, that would be nice to have. I couldn't find it in extension settings.

**Comment by macbookandrew** [comment]
@Christopher-Hayes @stevenlis you would have to create a workspace for it to show up here. To do that, open a project and go to File > Save Workspace As…

More info about workspaces:

> A Visual Studio Code "workspace" is the collection of one or more folders that are opened in a VS Code window (instance). In most cases, you will have a single folder opened as the workspace but, depending on your development workflow, you can include more than one folder, using an advanced configuration called [Multi-root workspaces](https://code.visualstudio.com/docs/editor/workspaces#_multiroot-workspaces).
>
> The concept of a workspace enables VS Code to:
>
> - Configure settings that only apply to a specific folder or folders but not others.
> - Persist [task](https://code.visualstudio.com/docs/editor/tasks) and [debugger launch](https://code.visualstudio.com/docs/editor/debugging) configurations that are only valid in the context of that workspace.
> - Store and restore UI state associated with that workspace (for example, the files that are opened).
> - Selectively enable or disable extensions only for that workspace.
>
> You may see the terms "folder" and "workspace" used interchangeably in VS Code documentation, issues, and community discussions. Think of a workspace as the root of a project that has extra VS Code knowledge and capabilities.
>
>> Note: It is also possible to open VS Code without a workspace. For example, when you open a new VS Code window by selecting a file from your platform's File menu, you will not be inside a workspace. In this mode, some of VS Code's capabilities are reduced but you can still open text files and edit them.

Source: https://code.visualstudio.com/docs/editor/workspaces

**Comment by Christopher-Hayes** [comment]
@macbookandrew I'm actually here because I only want to show folders, "Open Recent Project" shows mostly files for me which I never need to open, so I always have to tab through the files to open a project. But, I'll try toying with workspaces if it shows up better in Raycast.
