### ISSUE TITLE
Authy

### ISSUE THREAD

**Issue by rohitji1113** [raycast/extensions#7047]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

I can see all of my accounts linked to Authy and all of the individual apps that have tokens. But every single one shows corrupted. 

### Steps To Reproduce

Download extension, sign in. 
<img width="826" alt="Screenshot 2023-06-11 at 7 43 40 PM" src="https://github.com/raycast/extensions/assets/135932493/4b3a8449-066f-4de1-ac6e-6bc4ba5c699f">

### Current Behaviour

Can't use the authy extension.

### Expected Behaviour

Able to get the authy tokens.

**Comment by guga4ka** [comment]
i guess your backup password isn't correct.

**Comment by rohitji1113** [comment]
Got it - how did it get partial information of all of the individual accounts if the password was wrong? Also didn't get notified the password was wrong when I signed in. Or is this a different backup password?

*Rohit Aggarwal
* Chief Operating Officer

*m:* *+1 480.567.6744*

Sent via Superhuman ( ***@***.*** )

**Comment by ulken** [comment]
Seeing the same problem. This has worked before. Stopped working without making any changes.

**Comment by guga4ka** [comment]
@raycastbot close this issue 

i'm collecting this type of problem in this issue #5880
