### ISSUE TITLE
[Jira] ...

### ISSUE THREAD

**Issue by daghoidahl** [raycast/extensions#7048]
### Extension

https://www.raycast.com/raycast/jira

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

### Steps To Reproduce

Environment: MacBook Pro 16-Inch 2021 16 GB, MacOS Ventura 13.4

1. Click "Search Issues"

### Current Behaviour

Something went wrong

### Expected Behaviour

Display a list of Jira issues

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue #7013, so I'll mark it as such.
