### ISSUE TITLE
[Vivaldi] ...

### ISSUE THREAD

**Issue by manishie** [raycast/extensions#7054]
### Extension

https://www.raycast.com/crisboarna/vivaldi

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

### Steps To Reproduce

macos ventura 13.4 (22F66)
I can search history and tabs, but not bookmarks.

**Comment by thomaslombart** [comment]
Hey @manishie, we've fixed a performance issue in the 1.54.0 release that should make this type of bugs less likely to appear. Do you still have the error?
