### ISSUE TITLE
[SSH Connection Manager] ...

### ISSUE THREAD

**Issue by cui086** [raycast/extensions#7055]
### Extension

https://www.raycast.com/dimagrossman/ssh-manager

#### Error:
```

Error: Command failed with exit code 1: osascript -e 
    tell application "Terminal"
      do script ""  
      activate
      set position of front window to {1, 1}
      set shell to do script "ssh -i /Users/mykey.pub  user@domain.com " in window 1
    end tell
    
    tell application "System Events" to tell process "Terminal"
        set frontmost to true
        windows where title contains "bash"
        if result is not {} then perform action "AXRaise" of item 1 of result
    end tell
  
355:390: execution error: System Events got an error: osascript is not allowed assistive access. (-25211)

    tell application "Terminal"
      do script ""  
      activate
      set position of front window to {1, 1}


```

### Steps To Reproduce

1. Mac Version 12.5
2. Try to connect do ssh connection with a pub key.
3. Error appears after redirect to terminal
4. Reload the extension panel solves the problem.

**Comment by LenoxFro** [comment]
Hello @cui086,

did you check your System Preferences's Security and Privacy settings?
https://discussions.apple.com/thread/254078469

(First result when searching for your error message btw)

**Comment by cui086** [comment]
yeah problem solved after enabling accessibility. Close the issue.
