### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by peternagy96** [raycast/extensions#7056]
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```
Could not load command
```

### Steps To Reproduce

I just downloaded the extension on an M1 MacBook Pro running Macos 13.4, and none of the search commands seem to work, I get the above error for the Just Play command, and I get "Search has failed: could not communicate with the Spotify's Web API - Details: not found". The menu bar command, liking/unliking and featured playlist commands seem to work

### Current Behaviour

All search commands do not work.

### Expected Behaviour

They should display results to my query.

**Comment by peduarte** [comment]
Hey, is this still an issue for you? Im guessing that maybe Spotify API was down when you encountered this issue.

**Comment by peternagy96** [comment]
Hey, thanks for following up! I uninstalled the extension when I created the ticket. Now after re-installing it seems like the commands got updated and it is working now. Thanks!

**Comment by peduarte** [comment]
Ok, thanks!
