### ISSUE TITLE
[Todoist] Extension crashes after clicking 'Home' command

### ISSUE THREAD

**Issue by sebiq96** [raycast/extensions#7057]
### Extension

https://www.raycast.com/doist/todoist

### Description

After installing extension and logging into TODOist, I'm unable to view any of my task. The reason seems to be pretty obvious. 

#### Error:
```
TypeError: Cannot read properties of null (reading 'due')

l7:TodayTasks.tsx:16:51
Ir:index.js:6:5510
    at ray-list
ut:index.js:20:23404
```

### Steps To Reproduce

1. Install extension
2. Log into Todoist via browser
3. Get back to Raycast
4. Open Raycast -> Home (Todoist extension command)
5. Error

**Comment by thomaslombart** [comment]
Thanks for bringing up the issue. I couldn't reproduce it, and I'm a bit surprised by this bug, as it would mean that a task could be `null`. If possible, could you fork the extension, add a log in `TodayTasks` (something like `console.log(JSON.stringify(data?.items));`), and let me know what you get?

**Comment by sebiq96** [comment]
I found a way how to break an extension
1. Create new task
2. Give it a name e.g. "test" and "save"
3. Open "Search" command, find task by name, hit "Command + K" and select "Edit"
4. Don't change anything and hit "Command + Enter"
5. Go back to Raycast main view and open extension "Home" command
6. Error should appear

ofc I've forked repository and logged `data.items`, example below:
`[{
  added_at: '2021-10-13T21:38:57.683380Z',
  added_by_uid: '12345678',
  assigned_by_uid: null,
  checked: false,
  child_order: 2,
  collapsed: false,
  completed_at: null,
  content: 'Background ideas',
  day_order: -1,
  description: 'My task description',
  due: null,
  duration: null,
  id: '1234567890',
  is_deleted: false,
  labels: [],
  parent_id: null,
  priority: 1,
  project_id: '1234567890',
  responsible_uid: null,
  section_id: null,
  sync_id: '1234567890',
  user_id: '12345678'
}]`

**Comment by casassg** [comment]
Was able to repro, I think the issue is EditTask. If you don't edit the task in any way, todoist does not return an item which leads to an item in `data.items` set to null. Added a potential fix to the issue in the above PR. 

Btw, need to find a way to clean cached state as now my local dev environment is completly broken (trying to find a way to invalidate it if it fails)

**Comment by sebiq96** [comment]
@casassg I think you're right, moreover `EditTask` was recently edited (around month ago).
If you want to make local env working again assign empty array to tasks in TodaysTasks.tsx line 19, reload Home and then revert code 😅 

Anyways when extension is running properly user is able to perform action: "Clear Local Storage & Cache". I think this option should be available especially when extension crashed (but I'm not sure if it's even possible).
