### ISSUE TITLE
[Hookmark Search] ...

### ISSUE THREAD

**Issue by Gogeta1217** [raycast/extensions#7062]
### Extension

https://www.raycast.com/QIanGua/search-hookmark

### Description

I haven't managed to get the Search command to work yet. The other ones all work as intended, but the Search command keeps saying "Hookmark isn't running".

### Steps To Reproduce

All attempts to use the command fail. I tried using a global hotkey, alias, and just running it by clicking on it

**Comment by QIanGua** [comment]
@Gogeta1217  To launch Hookmark, there are some issues that need to be addressed. Before the extension is updated, I suggest manually launching Hookmark to use the search command.

**Comment by Gogeta1217** [comment]
Sorry, my explanation wasn't clear. Hookmark is running and the other three commands are working properly. However, the Search Hookmark command isn't recognizing that the app is already running. It states "Hookmark isn't running" and the only option it provides is to "Launch Hookmark".

**Comment by QIanGua** [comment]
@Gogeta1217 Thanks for your explanation. I know where is the problem.  In `search-hookmark.tsx`, `const { data, isLoading, error } = useCachedPromise(getBookmarks);`  This takes too much time to getBookmarks and it throws an error, resulting in a warning. I'll try to find some robust method to get bookmarks from Hookmark.

**Comment by dnlfrst** [comment]
For me, this is still an issue. Is there anything that I can help with in resolving the issue, @QIanGua?
