### ISSUE TITLE
[Google Tasks] ...

### ISSUE THREAD

**Issue by BramMusters** [raycast/extensions#7063]
### Extension

https://www.raycast.com/elliotdes/google-tasks

### Description

Raycast version: 1.53.2

Google Tasks API is enabled, and I  set up an OAuth Client ID for iOS with bundle ID: com.raycast

I can't sign in to my account due to missing extension verification:
![image](https://github.com/raycast/extensions/assets/7532595/9a60480b-13d1-4763-a5f8-658ca05b9ec6)

### Steps To Reproduce

1. Install the extension
2. Open the extension
3. "Sign in with Google"
4. A browser opens, select your account.
5. The error shows up

**Comment by elliotdes** [comment]
Hey, have you previously had the extension working? And then it broke after a few days?

Or has it not been working from the start?

**Comment by BramMusters** [comment]
> Hey, have you previously had the extension working? And then it broke after a few days?
> 
> Or has it not been working from the start?
I'm not sure to be honest. I do recall installing the extension some time ago and deleting it again (perhaps due to it not working).

Ok, after digging deeper I found the issue:
My OAuth Consent Screen is still in the "Testing" phase and I didn't add my own account as a Test user. Adding it solved my issue.

Apologies for creating the issue
