### ISSUE TITLE
[GitHub] Show Issue/PR number in Notifications action

### ISSUE THREAD

**Issue by loxygenK** [raycast/extensions#7068]
### Extension

https://www.raycast.com/raycast/github

### Description

Currently in `Notifications` action, Issue/PR numbers are not shown unlike `Search Pull Requests` or `Search Issues`. I believe it would be useful if the Issue/PR numbers are shown in `Notifications` too!

##### In `Search Pull Request`
<img width="284" alt="image" src="https://github.com/raycast/extensions/assets/55672846/0553831f-bd18-4395-bf91-0c070285dd37">

##### In `Notification`
<img width="768" alt="image" src="https://github.com/raycast/extensions/assets/55672846/aa90dc90-2cea-44f2-aaf8-23a7a4dbf561">

### Who will benefit from this feature?

Users who want to work with the Issue/PR numbers. Specifically (in my case), `gh pr checkout` uses the number of the PR the user want to work with. Although the link can be used as an argument, it would be really nice if I could start working just by quickly glancing at the title and number of the PR!

### Anything else?

- [Documentation of `gh pr checkout`](https://cli.github.com/manual/gh_pr_checkout)

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by loxygenK** [comment]
Sorry for my late reply...! Yes! I'd like to work on this.

And thanks for the support! FYI, I'm planning to make a function to extract the Issue/PR number from URL in [`helpers/notification.ts`](https://github.com/raycast/extensions/blob/main/extensions/github/src/helpers/notifications.ts), and call it and add to the `accessories` props of `List.Item` in [`components/NotificationListItem.tsx`](https://github.com/raycast/extensions/blob/main/extensions/github/src/components/NotificationListItem.tsx#L36).
