### ISSUE TITLE
[Microsoft Edge] Opening the browser fails when using the shortcut key to bind the page

### ISSUE THREAD

**Issue by cloudhao1999** [raycast/extensions#7069]
### Extension

https://www.raycast.com/KartikKumarSahoo/microsoft-edge

### Description

I want to use a keyboard shortcut to bind the `Search Bookmarks` page. The search works fine when I use the shortcut to bring up this page, but when I press enter to open the tab, it doesn't activate `Microsoft Edge` browser. So I downloaded the official `Microsoft Edge` plugin and debugged it, and found that on line 56 of the `index.ts` file in the `action` folder
```typescript
await Promise.all([closeMainWindow({ clearRootSearch:true }), checkAppInstalled()]);
```
I made modifications to this line of code, added the attribute `popToRootType`
```typescript
- await Promise.all([closeMainWindow({ clearRootSearch:true }), checkAppInstalled()]);
+ await Promise.all([closeMainWindow({ clearRootSearch:true, popToRootType: PopToRootType.Suspended }), checkAppInstalled()]);
```
And assigned it the value of `PopToRootType.Suspended`.  After compilation, the plugin can be opened normally.

### Steps To Reproduce

1. In MacOS Ventura 13.4
2. Bind a shortcut key for `Search Bookmarks` page in `Microsoft Edge` Plugin
<img width="672" alt="image" src="https://github.com/raycast/extensions/assets/32376445/9d4cc384-d845-4580-8633-42b2225b2ae7"> 

3. Use the shortcut keys to evoke the page
4. Use Enter Key to open a bookmark
5. It doesn't activate `Microsoft Edge` browser. 

### Current Behaviour

It doesn't activate `Microsoft Edge` browser. 

### Expected Behaviour

canactivate `Microsoft Edge` browser.

**Comment by KartikKumarSahoo** [comment]
Should be fixed by this PR https://github.com/raycast/extensions/pull/7526
