### ISSUE TITLE
[Append Clipboard] Feature request to include a space after separator, remove trailing whitespace

### ISSUE THREAD

**Issue by trijste** [raycast/extensions#7075]
### Extension

https://www.raycast.com/koinzhang/append-clipboard

### Description

I use this for reports and am missing key features that I struggle to work around. I would like to be able to include a space after the separator character, like "text1, text2."

I also have an issue where copying from some applications introduces a trailing whitespace when I double click the value I want to copy, e.g. "text1\n,text2." It would be great if the extension trimmed the whitespace off the clipboard value while appending.

### Who will benefit from this feature?

I believe it's a valuable feature that will expand this tool's utility.

**Comment by koinzhang** [comment]
Hi @trijste. I've submitted a PR #7488 to update the extension, hopefully it will meet your needs.

Now I will close this issue, if you still have any questions, welcome to reopen the issue and report back.

@raycastbot close this issue
