### ISSUE TITLE
[Notion] The extension does not bring results

### ISSUE THREAD

**Issue by juanra** [raycast/extensions#7080]
### Extension

https://www.raycast.com/HenriChabrand/notion

### Description

Hello everyone,

I installed the "Notion" extension and followed the setup steps. However, when I do a page search it doesn't bring me any results.

Please watch this screen recording: [https://imgur.com/a/ydPhe9H](https://imgur.com/a/ydPhe9H)

### Steps To Reproduce

1. Create a new integration as a developer in "Settings & Members -> My connections -> Develop or manage integrations"
2. Copy the Internal Integration Secret and paste it in the extension configuration window
3. Activate Raycast and type "Search Notion"
4. Type a keyword
5. No results

### Current Behaviour

No page results

### Expected Behaviour

It should bring results according to the keywords posted

**Comment by juanra** [comment]
Hi guys,

I understand that you must be super complicated, however I wanted to confirm if you had been able to take a look at this issue. 

Thanks in advance.

**Comment by thomaslombart** [comment]
Do you still have the issue @juanra?

**Comment by juanra** [comment]
Thanks for the followup @thomaslombart.

The reference that @iamyeizi recommended worked for me. Unfortunately it was not so clear in the extension README.

Thanks again to both.
