### ISSUE TITLE
[Google Tasks] Add Task Command

### ISSUE THREAD

**Issue by BramMusters** [raycast/extensions#7093]
### Extension

https://www.raycast.com/elliotdes/google-tasks

### Description

Currently, it's only possible to create tasks by 
1. using the "View Lists" command
2. Selecting a List
3. Typing a title of the Task, pressing Enter
4. A "Create Task" form pops up. (see screenshot))
![image](https://github.com/raycast/extensions/assets/7532595/39369153-f830-4363-9832-9c0070912535)

I think it shouldn't be too hard to have step 4 as a separate command? This would allow for very quick task creation.

### Who will benefit from this feature?
Anyone who wants to quickly create tasks.

### Anything else?
- Perhaps there should be a setting for the default task list, or an option to remember the last task list used.

**Comment by azindel13** [comment]
> ### Extension
> https://www.raycast.com/elliotdes/google-tasks
> 
> ### Description
> Currently, it's only possible to create tasks by
> 
> 1. using the "View Lists" command
> 2. Selecting a List
> 3. Typing a title of the Task, pressing Enter
> 4. A "Create Task" form pops up. (see screenshot))
>    ![image](https://private-user-images.githubusercontent.com/7532595/245756662-39369153-f830-4363-9832-9c0070912535.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODIxMDAsIm5iZiI6MTcwNDQ4MTgwMCwicGF0aCI6Ii83NTMyNTk1LzI0NTc1NjY2Mi0zOTM2OTE1My1mODMwLTQzNjMtOTgzMi05YzAwNzA5MTI1MzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMTkxMDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTEyNGQ5NTk4MmJlYzcwM2QxODM4YmNkMzZlYWU1ZDE2MDc4NTRhMzQ2NDM4NTA3MmZhNzdlNWIyZjkxNDhhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tZgfS91-uEw4OoV5PZatgZwkVGKlOSjmQQ8cCXVaRAc)
> 
> I think it shouldn't be too hard to have step 4 as a separate command? This would allow for very quick task creation.
> 
> ### Who will benefit from this feature?
> Anyone who wants to quickly create tasks.
> 
> ### Anything else?
> * Perhaps there should be a setting for the default task list, or an option to remember the last task list used.

This would be great
