### ISSUE TITLE
[Converter] Work with large numbers

### ISSUE THREAD

**Issue by jswalens** [raycast/extensions#7100]
### Extension

https://www.raycast.com/koinzhang/converter

### Description

The converter extension seems to be limited in the size of the numbers that are input. It would be great if it would accept arbitrary-sized numbers.

For example, start the base converter extension, and in the decimal field, start typing "12345678901234...". Once you reach 12345678901234567, this turns into 12345678901234568. If you then enter more digits (up to 20?), the field gets reset.

Similarly, if you enter "0102030405060708" in the base-16 field, it gets turned into "5ccbce0cc85c" once you enter the last digit.

### Who will benefit from this feature?

Anyone converting large numbers between bases. E.g. 64-bit numbers (or larger) in hex form.

**Comment by jswalens** [comment]
I can confirm this issue still exists.

It is caused by using `parseInt` which generates JavaScript numbers (= actually floating point numbers). It could be solved by using `BigInt`s, as the data is always integers anyway.

```
> parseInt("12345678901234567")
12345678901234568    // last digit 7 in input becomes 8 in output
> BigInt("12345678901234567")
12345678901234567n   // this is correct
> parseInt("0102030405060708", 16)
72623859790382850    // this is incorrect
> BigInt("0x0102030405060708")
72623859790382856n   // this is correct
```

**Comment by jswalens** [comment]
This issue still exists.

**Comment by jswalens** [comment]
I can confirm this issue still persists. I may look into fixing this in the future, if I have some spare time.

**Comment by jswalens** [comment]
Still relevant for me.

**Comment by jswalens** [comment]
Bug still persists.

**Comment by jswalens** [comment]
Still there.

**Comment by jswalens** [comment]
.

**Comment by Saafo** [comment]
Possibly current the owners of this extension have no time dealing with this issue. But if you provide a pr, we're glad to review it.

**Comment by koinzhang** [comment]
@jswalens Fixed in #13862

**Comment by jswalens** [comment]
Great news, thanks!

**Comment by koinzhang** [comment]
Hi @jswalens The [Converter](https://www.raycast.com/koinzhang/converter) extension has been updated to fix this issue so I'll close this issue, if you have any other issues feel free to keep the feedback coming!
@raycastbot close this issue
