### ISSUE TITLE
Getting an error - Bad Request

### ISSUE THREAD

**Issue by ideallivingmanagement** [raycast/extensions#7105]
### Extension

https://www.raycast.com/tonka3000/twitter

### Description

It has been working for quite some time but now I'm getting abad request error. I wonder if it has to do with the API changes that Twitter made recently.

### Steps To Reproduce

MACOS
Selecting any of the Twitter commands in Raycast

**Comment by mil3na** [comment]
The extension is giving a 403 every time. Maybe is worth investigating it?

**Comment by tonka3000** [comment]
Hey @mil3na ,

I have no API key since it is not free anymore. If you can send me a key in slack I can check it.

**Comment by eduwass** [comment]
Looks like this is still the case.
