### ISSUE TITLE
[Arc] ..."Search Arc" not working

### ISSUE THREAD

**Issue by neffepito** [raycast/extensions#7111]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20

### Steps To Reproduce

The function "Search Arc" not working and shows "Something went wrong"

**Comment by thomaslombart** [comment]
Hey @neffepito, we've fixed a performance issue in the 1.54.0 release that should make this type of bugs less likely to appear. Do you still have the error?
