### ISSUE TITLE
[Bitwarden Vault] Add concept of favorites

### ISSUE THREAD

**Issue by verheyenkoen** [raycast/extensions#7112]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Would be nice if you could mark certain Bitwarden entries as favorites and have them displayed above the full list in a separate "Favorites" section group (preferably in a list that you can self-order). I have hundreds of passwords in Bitwarden but there's around 3 I use very often (ten's of times a day). Currently I can only grab them by searching (or if I hack a special char in the name so it comes on top of the list alphabetically). Would be cool if I could just `arrow down` + `enter` and have the password copied.

Alternatively you could also develop this as a "Most used" feature, but that would require keeping a count for every entry, every time its' password is copied.

### Who will benefit from this feature?

Me and many others 🤪

**Comment by jomifepe** [comment]
Hello, yeah this is something I would like to implement, added my [personal backlog](https://github.com/users/jomifepe/projects/1/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C%22Labels%22%5D).

**Comment by jomifepe** [comment]
Feature implemented, take it for a spin 🚀 

Here's a demonstration:

https://github.com/raycast/extensions/assets/7235666/f9f4c16c-977d-4fc4-87c4-e15329db2fbc
