### ISSUE TITLE
[KeePassXC] ...

### ISSUE THREAD

**Issue by YuriyUdod** [raycast/extensions#7115]
### Extension

https://www.raycast.com/zkytech/keepassxc

### Description

If the password contains the sequence ....{.....}.....   (where "." means any symbol), I think, that extension is trying to interpret this and receives an error and cannot paste the password.

### Steps To Reproduce

1. Create a record with password, for example: 33{fg}555
2. Try to use it in console

### Current Behaviour

Error: Maximum depths of replacement has been reached. Entry uuid: {some uuid here}

### Expected Behaviour

Paste stored password

**Comment by YuriyUdod** [comment]
And maybe it can be a security problem.

**Comment by YuriyUdod** [comment]
Hello,
Sorry, but this problem returns.

**Comment by YuriyUdod** [comment]
Any news?

**Comment by zkytech** [comment]
> Any news?

already fixed 1 month ago
