### ISSUE TITLE
[Liba.ro - URL Shortener] Auto-close window

### ISSUE THREAD

**Issue by rjhewitt3** [raycast/extensions#7123]
### Extension

https://www.raycast.com/libaro/liba-ro_shortener

### Description

The Raycast window/form should close when the url is successfully converted and copied to clipboard. Manually closing is hindering my workflow significantly.

**Comment by rjhewitt3** [comment]
@thomaslombart Just realized that there is no success notification of any kind now, the window closes and the link is copied to the clipboard. Can you add a Raycast toast to confirm visually?

**Comment by thomaslombart** [comment]
Was your message a mistake @rjhewitt3? I'm not sure what I should do here.

**Comment by rjhewitt3** [comment]
@thomaslombart You're the one that closed the issue according to activity log, so I thought you'd be the person to tag. Perhaps I should've mentioned @RosiersRobin?

**Comment by thomaslombart** [comment]
Oh, it's because I approved and merged the PR. @RosiersRobin is the person mention, yes!
