### ISSUE TITLE
[Search Zotero] Chinese word segmentation problem

### ISSUE THREAD

**Issue by Yubuxin** [raycast/extensions#7126]
### Extension

https://www.raycast.com/reckoning-dev/zotero

### Description

Chinese word segmentation seems to have some problems, some words can not be matched with the proper result, such as a search for "鲁迅" (Lu Xun) yielded no results - even if there **is** an entry in database titled "鲁迅的青年时代" (Lu Xun's youth) - only by changing the search term to "鲁迅的" (Lu Xun's) will get the correct results.

### Steps To Reproduce

1. open raycast & "search Zotero" command
2. type a single Chinese word like "鲁迅"
3. search

**Comment by sadanand-singh** [comment]
Sorry, I have no way to test other languages issues. Any contributions would be welcome!
