### ISSUE TITLE
[Heroicons] Configure Heroicons Version

### ISSUE THREAD

**Issue by grafst** [raycast/extensions#7128]
### Extension

https://www.raycast.com/haack/heroicons

### Description

I can only use Heroicons v1 in my project. So I would like a setting to filter the heroicons by version.

**Comment by haackt** [comment]
I'm currently working on a solution to select Heroicons versions dynamically. It may take a while to complete, as I'll be away for the next few weeks.

**Comment by haackt** [comment]
Until it's implemented I'd suggest you to use [Iconify](https://www.raycast.com/destiner/iconify) by @Destiner

It already has the functionality to only display Heroicons v1 icons

**Comment by grafst** [comment]
oh cool, thanks
