### ISSUE TITLE
[Bitbucket Search] - Something went wrong

### ISSUE THREAD

**Issue by gm90** [raycast/extensions#7137]
### Extension

https://www.raycast.com/Francois/bitbucket

#### Error:
```

```

### Steps To Reproduce

1. On mac os Ventura 13.4
2. Using latest Raycast Pro (v1.53.4) + the bitbucket extension
3. As soon as I attempt to open the search box I used to get
4. I get:

<img width="762" alt="image" src="https://github.com/raycast/extensions/assets/285740/018d7659-1e1e-4990-beee-7cd5e383fdfe">

with the attached error.

### Expected Behaviour

Previously was able to search for repositories via the extension

**Comment by Lp-Francois** [comment]
It can happen if your wifi disconnected briefly, or if you didn't set a token.

Otherwise I don't have any idea what could have happened, especially the error doesn't seem useful :/ Not sure I can do anything here sadly

**Comment by gm90** [comment]
A token is definitely specified + no issues with the internet connection. Appears I'm not the only one:

**Comment by sxn** [comment]
fixed in https://github.com/raycast/extensions/pull/7176
