### ISSUE TITLE
[Authy] ...

### ISSUE THREAD

**Issue by sandrofsousa** [raycast/extensions#7138]
### Extension

https://www.raycast.com/guga4ka/authy

#### Error:
```
Error: Invalid base32 characters

uu:OtpListItem.tsx:72:38
fu:search-otp.js:42:4668
Ir:index.js:6:5510
    at ray-list
```

### Steps To Reproduce

Initial installation from the Raycast store. The error occurred while trying to use the extension for the first time.

**Comment by devCharles** [comment]
i have the same problem but happened when syncing the extension today

```
Error: Invalid base32 characters

uu:OtpListItem.tsx:72:38
fu:search-otp.js:42:4668
Ir:index.js:6:5510
    at ray-list
``` 
System:
Mac OS Ventura 13.3.1
i7

**Comment by sandrofsousa** [comment]
It seems to be related to #5880. Despite that issue suggesting that the problem was sorted, it remains even on a fresh install.

**Comment by guga4ka** [comment]
lets track it in one place #5880

@raycastbot close this issue
