### ISSUE TITLE
[Google Chrome] Search Tabs - Search within URL name and title of webpages

### ISSUE THREAD

**Issue by nivcoder** [raycast/extensions#7149]
### Extension

https://www.raycast.com/Codely/google-chrome

### Description

"Search tabs" searches the title of the page but not within the URL. Sometimes the name of the service isn't in the title, but it's usually in the URL. For example, it's difficult to find the tab that's open for HubSpot since the title of the page doesn't contain that word.
<img width="1093" alt="SCR-20230616-rdyj" src="https://github.com/raycast/extensions/assets/131817722/1c9088d0-a097-4ecd-84ee-d407f6ea28ce">

### Who will benefit from this feature?

I imagine many/most users of this very useful extension will appreciate being able to find their pages more easily. Without this feature, people still need to default to searching within tabs within Chrome instead of using this nice extension.

**Comment by muescha** [comment]
(is there a way to reopen the issue or should I create a new one?)
