### ISSUE TITLE
[Reflect] Ability to append to daily note as bullet or task (checkbox)

### ISSUE THREAD

**Issue by dujaje** [raycast/extensions#7160]
### Extension

https://www.raycast.com/ryon/reflect

### Description

Right now when you append to daily note, the appended text is always added as a bullet. 

What would be great is if you could append and append instead as a checkbox. My suggestion would be just if you started your text with [] it would become a checkbox, but I am sure there are also other options.

### Who will benefit from this feature?

Anyone who uses reflect for task tracking as well as notes!

**Comment by joshknowles** [comment]
@dujaje I agree this would be a good addition, but unfortunately, the Reflect API does not correctly parse `[]`.

I sent this request and a handful of other API-related bugs (like parsing `[[ ]]`) to Alex a few weeks ago, I'll ping him and see when these might get fixed.
