### ISSUE TITLE
[Hue] Extension lost link to my Hue bridge and reconnecting to it also fails

### ISSUE THREAD

**Issue by felixkaiser** [raycast/extensions#7161]
### Extension

https://www.raycast.com/pindab0ter/hue

### Description

I could previously correctly control my lights after initially connecting to my Hue bridge. Since maybe 6-8w I can no longer do that, since "there's no bridge connected". It seems the connection got lost.

When I try to reconnect, after pushing the physical button on the bridge and connecting the extension, I get the error message "Failed to link with the Hue Bridge".

I'm afraid I have to no other information available, but happy to debug more if pointed in the direction.

### Steps To Reproduce

I could previously correctly control my lights after initially connecting to my Hue bridge. Since maybe 6-8w I can no longer do that, since "there's no bridge connected". It seems the connection got lost.

When I try to reconnect, after pushing the physical button on the bridge and connecting the extension, I get the error message "Failed to link with the Hue Bridge".

I'm afraid I have to no other information available, but happy to debug more if pointed in the direction.

**Comment by felixkaiser** [comment]
Uninstalling end re-installing the extension produces the same result.

**Comment by pindab0ter** [comment]
An update (#6006) has just been pushed. Please try again and let me know if that changes your situation.

The update will allow you to manually set your Bridge's IP Address and/or API key if it still doesn't work.

**Comment by felixkaiser** [comment]
Thanks for investing your time into this. I've un-installed and re-installed the extension and am now getting a new error:

**Comment by felixkaiser** [comment]
I'm getting the same error after I've manually added the IP to the extensions settings and try to connect using "Control lights" again.

I do see a field called "Bridge Username (manual)". Is this meant to be asking for the APKI key? How do I obtain one?

**Comment by pindab0ter** [comment]
I've coded in provisions for older Hue Bridge models that only serve the self-signed certificate. Unfortunately I don't have one, I so I'm not able to debug this myself.

I'm afraid I can't do more than offer my help and guidance in where to start debugging. Feel free to message me in the Raycast Slack if you are (or anyone else is) up for that.

**Comment by felixkaiser** [comment]
Thanks for that. I currently can't prioritise that, sorry.
My model is at least a v2, my understanding is that there's only a newer v2.1 after that. Not sure when the self-signed cert was abandoned.
