### ISSUE TITLE
[Tmux Sessioner] add wezterm to terminal list

### ISSUE THREAD

**Issue by hnspn** [raycast/extensions#7166]
### Extension

https://www.raycast.com/louishuyng/tmux-sessioner

### Description

Add wezterm to terminal list
https://wezfurlong.org/wezterm/

**Comment by louishuyng** [comment]
Hi @hnspn I am on my way to fixing that. However, got some problem with publishing to the store

https://raycastcommunity.slack.com/archives/C028DTXTW3Y/p1687215084075049?thread_ts=1687003752.117709&cid=C028DTXTW3Y

**Comment by louishuyng** [comment]
Hi The issue has been solved in the new release version
<img width="950" alt="image" src="https://github.com/raycast/extensions/assets/40130936/cb31c04c-b324-4425-8f98-aeed4c658466">

@raycastbot close this issue
