### ISSUE TITLE
[Authy] Invalid base32 characters

### ISSUE THREAD

**Issue by SarcevicAntonio** [raycast/extensions#7175]
### Extension

https://www.raycast.com/guga4ka/authy

#### Error:
```
Error: Invalid base32 characters

uu:OtpListItem.tsx:72:38
fu:search-otp.js:42:4668
Ir:index.js:6:5510
    at ray-list
```

### Steps To Reproduce

1. use raycast sync to import authy settings on new device
2. use authy show token command
3. accept this device on another device
4. this error appears

**Comment by SarcevicAntonio** [comment]
sorry, looks like dupe of #7138 and/or #5880

**Comment by guga4ka** [comment]
check latest comment at #5880
@raycastbot close this issue
