### ISSUE TITLE
[Authy] "Error: Invalid base32 characters" using Search Token command

### ISSUE THREAD

**Issue by malpkakefirek** [raycast/extensions#7182]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

Using an incorrect backup key (one that is impossible to set, for example "hello"), when going to the "Search Token" command, the below error occurs. Sometimes also happens when you have a possible to set backup key that is incorrect, however that is inconsistent.

#### Error:
```
Error: Invalid base32 characters

uu:OtpListItem.tsx:72:38
fu:search-otp.js:42:4668
Ir:index.js:6:5510
    at ray-list
```

### Steps To Reproduce

1. Install extension
2. Connect authy account, but with incorrect backup key (something that is too short to be possible always does that)
3. Search Token command gives this error

**Comment by guga4ka** [comment]
duplicate #5880 
@raycastbot close this issue
