### ISSUE TITLE
[Todoist] ...

### ISSUE THREAD

**Issue by giap9416** [raycast/extensions#7188]
### Extension

https://www.raycast.com/doist/todoist

#### Error:
```
TypeError: Cannot read properties of null (reading 'due')

v7:TodayTasks.tsx:16:51
Ir:index.js:6:5510
    at ray-list
ut:index.js:20:23404
```

### Steps To Reproduce

Todist

**Comment by casassg** [comment]
@giap9416 ty for filling, mind adding steps to reproduce the error?
