### ISSUE TITLE
[Hypersonic]... Doesn't seem to work with new Tasks and Projects rework.

### ISSUE THREAD

**Issue by ambitendencies** [raycast/extensions#7191]
### Extension

https://raycast.com/reboot/hypersonic

#### Error:
```
TypeError: Cannot read properties of undefined (reading '0')
    at D2 (/Users/ben/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:62:89956)
    at /Users/ben/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:62:90671
    at Array.map (<anonymous>)
    at KC (/Users/ben/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:62:90664)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ZC.initialData (/Users/ben/.config/raycast/extensions/baa4a90b-4452-4213-b1c0-315edd746652/index.js:62:90770)
```

### Steps To Reproduce

Try to load Hypersonic, get greeted with the error.

**Comment by edu-pazmino** [comment]
I have the same error, please could you double check this error?

**Comment by abehr** [comment]
Same for me

**Comment by allanjun** [comment]
I found one workaround but will require access to automation features:
- add a new status propriety for your tasks, mirroring the original one (i.e. all the status you have, see on my example below)
- link the database using this new custom status
- build automations like on the last screenshot: when `new status` set to `Done`, set `old status` to `Done`
    - you will have to make one automation per status, you will need to do it twice if you want it to be synced bi-directionally 

<img width="361" alt="image" src="https://github.com/raycast/extensions/assets/15525731/b9dcead1-19a7-40e2-b704-58396febc9be">

<img width="547" alt="image" src="https://github.com/raycast/extensions/assets/15525731/805c7d60-53e7-4991-99e5-7467d637e52f">

<img width="325" alt="image" src="https://github.com/raycast/extensions/assets/15525731/3d018d95-df88-4352-8d25-af2f4eac5bbb">
