### ISSUE TITLE
[Browser Bookmarks] Search functionality only searched for exact match 

### ISSUE THREAD

**Issue by jaybhanushali3195** [raycast/extensions#7195]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

The new browser bookmark search extension does not have fuzzy search, Is it possible to improve the search of bookmarks ?
Ex.
I have a bookmark named “Jay is software developer”
When I search “Jay software” , it gives me no results back, is there a workaround for that ?
This basically restricts the user to search when they have a lot of bookmarks

### Steps To Reproduce

1. Make a chrome bookmark with the name “Jay is software developer”
2. Search for "Jay software"
3. It shows no results.

### Current Behaviour

No results

### Expected Behaviour

It should show “Jay is software developer” bookmark
Current chrome bookmark manager can do this
![19 June Monday at 05 PM](https://github.com/raycast/extensions/assets/36804441/a26973d3-bd83-4bff-a36a-708877369cee)

**Comment by thomaslombart** [comment]
Indeed, the browser bookmarks extension doesn't support fuzzy search as it uses custom filtering. It'll need to be supported. Is this something you'd like to work on? At the very least, I guess, you could split the search query in different words and individually check if these words are part of the bookmark's title.

**Comment by jaybhanushali3195** [comment]
Currently,I won't have any bandwidth to work on this. 
But is there a guide on how to set up and contribute to raycast extension? 

Also, all the extensions are in typescript right ?

**Comment by jaybhanushali3195** [comment]
Okay, I will get onboarded to this. But this might take time.
Also, fuzzy search would require some optimized algorithm to be implemented, which would already be available on internet.
