### ISSUE TITLE
[GitHub] Support re-run failed jobs in workflow

### ISSUE THREAD

**Issue by oilbeater** [raycast/extensions#7197]
### Extension

https://www.raycast.com/raycast/github

### Description

For a large github workflow with multiple jobs, it may take hours to rerun the whole workflow. It would be helpful if raycast github plugin can only re-run failed jobs for a workflow.

I find that octokit already support  re-run-workflow-failed-jobs  https://octokit.github.io/rest.js/v19#actions-re-run-workflow-failed-jobs

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by oilbeater** [comment]
@thomaslombart Yeah I'd like to have a try. However, I am not familiar with development of the raycast extension, I will need some time to figure it out.
