### ISSUE TITLE
[System Monitor] ...

### ISSUE THREAD

**Issue by victorbertels** [raycast/extensions#7198]
### Extension

https://www.raycast.com/hossammourad/raycast-system-monitor

### Description

Everytime you open the extension the task PMSET spikes multiple times to 100%

the moment you close the extension through raycast it falls to within normal boundaries.

### Steps To Reproduce

open the extensions
See PMSET jump to 100% multipletimes
<img width="744" alt="CleanShot 2023-06-20 at 14 46 26@2x" src="https://github.com/raycast/extensions/assets/42408871/7013f083-4206-4782-a66a-be1988c74ea8">

**Comment by lucasmezencio** [comment]
@victorbertels I'm not sure if this can be considered as a bug. PMSET is used to gather information about power/battery.

Would it be enough to simply hide `pmset` from the processes list?

**Comment by noahstreller** [comment]
> @victorbertels I'm not sure if this can be considered as a bug. PMSET is used to gather information about power/battery.
> 
> Would it be enough to simply hide `pmset` from the processes list?

I seem to have the exact same issue. Before opening System Monitor, PMSET isn't on the process list at all (in the Activity Monitor), and my total CPU load lies at around 25%. Once I open the System Monitor, my CPU quickly spikes very high towards the maximum load.



<img width="934" alt="image" src="https://github.com/raycast/extensions/assets/65013011/da046ddc-7a64-4878-9412-c3b6f17e9a99">

**Comment by otakukz17** [comment]
I have the same problem, but when I open an extension, it immediately uses 100% of the CPU and hangs my laptop
