### ISSUE TITLE
[GitHub] Breaking auth flow renders extension unusable

### ISSUE THREAD

**Issue by rjdellecese** [raycast/extensions#7202]
### Extension

https://www.raycast.com/raycast/github

### Description

Breaking the auth flow by closing the Raycast auth page for the GitHub extension renders the extension unusable.

### Steps To Reproduce

1. Install GitHub extension from the store
2. Being authentication process
3. Close GitHub authentication "page" in Raycast
4. Authenticate to GitHub through the browser, granting permission to the Raycast GitHub extension
5. Attempt to re-run a GitHub extension command and see Raycast authentication "page" again
6. Try clicking "Sign in with GitHub" in Raycast and, be taken to a web page (at `https://github.oauth-proxy.raycast.com/authorize`) which displays an `ERR_SSL_PROTOCOL_ERROR`

**Comment by arkuhn** [comment]
Same issue with me but for the Jira plugin.

**Comment by mathieudutour** [comment]
It should be fixed now
