### ISSUE TITLE
[GitHub] Add views for assigned and requested reviews PRs/Issues

### ISSUE THREAD

**Issue by asportnoy** [raycast/extensions#7209]
### Extension

https://www.raycast.com/raycast/github

### Description

Add commands for the following:
- [Review Requested PRs](https://github.com/pulls?q=is%3Apr+is%3Aopen+review-requested%3A%40me+)
- [Assigned Issues](https://github.com/issues?q=is%3Aissue+is%3Aopen+assignee%3A%40me+)
- [Assigned PRs](https://github.com/pulls?q=is%3Apr+is%3Aopen+assignee%3A%40me+)

Could possibly be combined into the "My Issues"/"My PRs" commands, maybe with some kind of option to choose what you see.

### Who will benefit from this feature?

Makes it much easier to get to relevant issues/PRs, so it would benefit many developers who use GitHub and want to use Raycast to make it easier to manage their PRs/issues.

### Anything else?

See links above for relevant filters on GH. I think only including open items would make sense for these, though that could also be configurable. Maybe also an option to hide drafts (filter: `draft:false`).

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by asportnoy** [comment]
Not stale

**Comment by thomaslombart** [comment]
Hey, I've taken a second look at that. It's already possible to see these views in `My Pull Requests` and `Open Issues`, so not sure if dedicated commands would be useful.
