### ISSUE TITLE
[Zoom] Start meeting reports an error

### ISSUE THREAD

**Issue by tayloramurphy** [raycast/extensions#7210]
### Extension

https://www.raycast.com/raycast/zoom

### Description

I'm on a mac m1, with raycast version 1.53.4

#### Error:
```
Could not load command
```

### Steps To Reproduce

Try to launch a zoom meeting, either with the zoom app open or closed.

### Current Behaviour

I get an error with minimal info.

<img width="753" alt="Screenshot 2023-06-20 at 3 23 10 PM" src="https://github.com/raycast/extensions/assets/5394188/cce97e99-a507-4339-bd69-089361f3ede1">

### Expected Behaviour

Zoom starts a meeting 😄

**Comment by thomaslombart** [comment]
Are you consistently getting the same result when launching this command?

**Comment by tayloramurphy** [comment]
@thomaslombart yep - it's for any of the commands from the extension. 

I just tried the "This Week's Meetings" command and got this error:

```
Reason: Code: 2 (Unhandled Extension Rejection)
Domain: commands
Time: 22:48:51.354
```

but everything else gives me the "something went wrong" screen.

**Comment by thomaslombart** [comment]
@TaylorAMurphy We've improved error messages with version 1.54.0. Could you try it out one more time and let me know the error? Unfortunately, the error messages are generic and it's not actionable as it is 😕

**Comment by tayloramurphy** [comment]
@thomaslombart Updated and got the following OAuth error. I also went through the zoom app marketplace to see if there was anything I can do on my end to fix, but I didn't find anything. (Screenshot showing it's installed on my account appropriately.)

<img width="1069" alt="Screenshot 2023-07-03 at 11 30 09 AM" src="https://github.com/raycast/extensions/assets/5394188/18622dcf-ba6c-46de-bb57-f00d9ba489a6">



Error: Bad Request

ss:oauth.ts:71:10

---
68: 
69:   if (!response.ok) {
70:     console.error("refresh tokens error:", await response.text());
71:     throw new Error(response.statusText);
72:   }
73: 
74:   const tokenResponse = (await response.json()) as OAuth.TokenResponse;
---

async on:start-meeting.js:14:902
async Object.ia:start-meeting.js:14:2375

**Comment by tayloramurphy** [comment]
Just wanted to report I'm still getting this exact same error on 1.55.2

**Comment by tayloramurphy** [comment]
booo @raycastbot. I'm still experiencing this. Same error with a slightly different `start-meeting.js` line

```
Error: Bad Request

ss:oauth.ts:71:10

---
68: 
69:   if (!response.ok) {
70:     console.error("refresh tokens error:", await response.text());
71:     throw new Error(response.statusText);
72:   }
73: 
74:   const tokenResponse = (await response.json()) as OAuth.TokenResponse;
---

async on:start-meeting.js:14:902
async Object.ia:start-meeting.js:14:2357
```

**Comment by tayloramurphy** [comment]
@thomaslombart I logged out of Zoom from Raycast and then reauthenticated. It now works as expected. I'm guessing you can close unless you want to throw a more meaningful user action error in the event of this error.

**Comment by thomaslombart** [comment]
All right, feel free to reopen the issue if you see something weird happening again.
