### ISSUE TITLE
[Google Bard] ...

### ISSUE THREAD

**Issue by davidnyuwin** [raycast/extensions#7211]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

when I use the ask ai command, how do I provide an input? it doesn't give me a promopt? 

### Steps To Reproduce

invoke ask ai 

### Expected Behaviour

look for prompt then run command

**Comment by EvanZhouDev** [comment]
For now, use it as a fallback command. Enter your text in the search bar, then use the Ask AI fallback. Will be optimizing this experience in the future.

@raycastbot close this issue
