### ISSUE TITLE
[Authy] Error after authentication

### ISSUE THREAD

**Issue by DBZFYAM** [raycast/extensions#7214]
### Extension

https://www.raycast.com/guga4ka/authy

#### Error:
```
Error: Invalid base32 characters

uu:OtpListItem.tsx:72:38
fu:search-otp.js:42:4668
Ir:index.js:6:5510
    at ray-list
```

### Steps To Reproduce

I just installed the extension (never used before). After specifying the ID and backup password, Authy asked to confirm. After confirming and pressing Enter in the Authy extension, it seems to log in, but then shows a "Something went wrong" screen and can't proceed anymore.

I don't have any special characters in the names of my accounts (except from spaces)

### Current Behaviour

After authenticating/logging in, shows an error

### Expected Behaviour

(I assume) show a list of accounts to choose from

**Comment by guga4ka** [comment]
duplicate #5880

@raycastbot close this issue
