### ISSUE TITLE
[Quit Applications] ...

### ISSUE THREAD

**Issue by qlery49** [raycast/extensions#7216]
### Extension

https://www.raycast.com/mackopes/quit-applications

### Description

Can you implement a feature to close all apps except for the selected one? Additionally, it would be great to have a toggle in the settings that enables the option to hide Raycast and Finder from the list.

### Who will benefit from this feature?

Everyone

### Anything else?

Love your extension, hope you could implement those features

**Comment by mackopes** [comment]
Hi @qlery49,

Thanks for reaching out with the feature request! I also appreciate your enthusiasm and and effort in writing all the code necessary.

I considered this feature carefully, but I am not 100% convinced this is a good user experience.

Could you please elaborate further on your intended use case? Maybe we can come up with a solution that is both user-friendly as well as useful for you. Right now, while I understand the potential usefulness in some specific scenarios, I don't see how a general user would intentionally use this.

My biggest issue is with the "exceptions". I don't think it is a good UX to "quit all except the selected one, and finder, and raycast, and ...". It kind of hides what the command does from the user. I also do not want the users to go into the settings just to find out what a command does, and I do not want users configure quit-applications in any way. The whole philosophy of quit-applications is to be simple to use straight out of the box and without any configs. Basically do one thing (quit applications) and do it well.

I wonder if raycast's script command would be more useful for this purpose. Maybe even a separate extension could be considered for this.
