### ISSUE TITLE
[Google Translate] ...

### ISSUE THREAD

**Issue by fariasmateuss** [raycast/extensions#7221]
### Extension

https://www.raycast.com/gebeto/translate

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'flag')

h3:translate.tsx:10:32
_r:index.js:6:2490
    at ray-navigation-stack
Do:index.js:6:2088
```

### Steps To Reproduce

Type "Miror" and see the error.

![Screenshot 2023-06-21 at 13 24 24](https://github.com/raycast/extensions/assets/55674918/a0a00fd5-f1ba-4ba8-9f4f-d547798d5639)

### Current Behaviour

Error "Something went wrong".

### Expected Behaviour

The translation from English to Portuguese.

**Comment by gebeto** [comment]
Which language you use?

**Comment by fariasmateuss** [comment]
> Which language do you use?

English

**Comment by nirtamir2** [comment]
Did you try to uninstall and install it again?

**Comment by or-agami** [comment]
Can confirm on "Miror", "Irrelevant" also cause this issue for some reason (auto detect > English)

**Comment by gebeto** [comment]
This was fixed in latest release yesterday, there was a problem with autodetect

Related to: https://github.com/raycast/extensions/pull/7864

@pernielsentikaer can you please close this issue?
