### ISSUE TITLE
[YouTube Downloader] Command is not installed even if it is

### ISSUE THREAD

**Issue by teziovsky** [raycast/extensions#7230]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

The problem is with the `Homebrew install path` (you can check it with `brew --prefix`). In ARM and Intel there are different paths:
```
macOS Intel: /usr/local
macOS ARM: /opt/homebrew
```
The extension is checking only for `/opt/homebrew`, meaning users with Intel chips cannot use this extension.

### Steps To Reproduce

1. macOS Ventura 13.4 with an intel chip
2. Extension installed from the store
3. Execute extension the first time
4. See the error

### Current Behaviour

It shows an error page informing you that you don't have installed `ffmpeg` even if it is installed.

### Expected Behaviour

Working correctly 🤔

**Comment by teziovsky** [comment]
### Screenshots
<img width="943" alt="Screenshot 2023-06-22 at 13 33 43" src="https://github.com/raycast/extensions/assets/36273653/507e746a-c30e-4fe7-986c-4db9d462c894">
<img width="1000" alt="youtube-downloader 2023-06-22 at 13 28 35" src="https://github.com/raycast/extensions/assets/36273653/3fa3c803-f1ec-4f85-aa72-9f78ef93e318">

**Comment by vimtor** [comment]
Hi @teziovsky! Sorry for the error, I did not know that Homebrew changed the path for Intel. I will try to fix it this weekend.

**Comment by teziovsky** [comment]
@vimtor no problem 😎
Is it possible to download audio from youtube video in mp3 format? 🤔

**Comment by vimtor** [comment]
> @vimtor no problem 😎 Is it possible to download audio from youtube video in mp3 format? 🤔

Yes! It is possible to download the video as an mp3 audio

**Comment by BionicBison05** [comment]
Could it be possible in the future to specify where ffmpeg is installed? I installed it without homebrew entirely.

**Comment by vimtor** [comment]
> Could it be possible in the future to specify where ffmpeg is installed? I installed it without homebrew entirely.

Yes I think I am going to do that. I tried to be clever searching for common installation locations in the PR but I am going to adapt it so the user can specify their desired path.

**Comment by Airhaed** [comment]
same here, i’m on macbook pro m2 and i installed ffmpeg and everything but i still get this message:

🚨 Error: ﻿ffmpeg is not installed

**Comment by teziovsky** [comment]
You can pass path to ffmpeg in extension settings.
Get path from
which ffmpeg
