### ISSUE TITLE
[Asana] Not able to login to the extension

### ISSUE THREAD

**Issue by JonSAdams** [raycast/extensions#7231]
### Extension

https://www.raycast.com/raycast/asana

### Description

It is not letting me authorize my account. I have my computer off and on and the application. 

### Steps To Reproduce

Running: MacOS 13.4 (22F66)
Connected to Ethernet with a work VPN
Failing from copying the link and clicking the link from the Reycast App

### Expected Behaviour

I expected it to authorize my account

**Comment by thomaslombart** [comment]
Do you have the same result if you try to login multiple times?

**Comment by JonSAdams** [comment]
Yes! I’m happy to reproduce in a screen recording as well if you would like. Jonathan AdamsOn Jun 23, 2023, at 3:40 AM, Thomas Lombart ***@***.***> wrote:﻿
Do you have the same result if you try to login multiple times?

**Comment by thomaslombart** [comment]
Yes, please send it over 🙂
