### ISSUE TITLE
[Kagi FastGPT] Error while performing a lookup

### ISSUE THREAD

**Issue by heliostatic** [raycast/extensions#7233]
### Extension

https://www.raycast.com/http.james/kagi-fastgpt

#### Error:
```
TypeError: Cannot read properties of null (reading 'output')

ask.tsx:30:39

```

### Steps To Reproduce

1. Add api key
2. Perform lookup
3. Error and no text displayed
4. Repeat with additional lookup to confirm

### Current Behaviour

Error and no text displayed

### Expected Behaviour

Result from FastGPT displayed

**Comment by httpjamesm** [comment]
Hi, can you confirm that you've added credits to your developer account?

**Comment by heliostatic** [comment]
Well, I can now 😅 -- I had not added any before. Error is resolved now. I guess this is now less of a bug than a feature request: display a friendly error suggesting adding credits in case the user is me?

**Comment by httpjamesm** [comment]
Yup. Will do. Thanks for pointing it out
