### ISSUE TITLE
[Pins] ...

### ISSUE THREAD

**Issue by philippnutiu** [raycast/extensions#7236]
### Extension

https://www.raycast.com/HelloImSteven/pins

#### Error:
```

```

### Steps To Reproduce

1. Try to show the pins in the menu bar

**Comment by pernielsentikaer** [comment]
You didn't add any content in your report @philippnutiu - could you update it 🙂

**Comment by philippnutiu** [comment]
Hello @pernielsentikaer after some restarts the extension is working. I had the error that the menu was not displayed now it is working :D
