### ISSUE TITLE
[Aleph] Permission dialog not being prompted

### ISSUE THREAD

**Issue by mordechaim** [raycast/extensions#7240]
### Extension

https://www.raycast.com/d7mtg/aleph

### Description

Using commands that need clipboard access without the required system permissions will fail with 
_**Encode failed** no text selected._

The proper solution is to prompt the user to grant accessibility access to Raycast.

### Steps To Reproduce

1. Disable accessibility permission: System Settings > Privacy & Security > Accessibility > Raycast
2. Try using any command

**Comment by d7mtg** [comment]
@peduarte Do you know how to solve something like this?

**Comment by peduarte** [comment]
Not sure. Upon initial installation, users are prompted to grant permissions. But if they reject there's not much we can do. Not sure we can keep prompt'ing... will need to run it past the team.

**Comment by mordechaim** [comment]
@peduarte I do recall being prompted again when trying to use Raycast Window Management commands when the permission is disabled.

**Comment by d7mtg** [comment]
@peduarte I'm thinking, a possible solution might be to at least tell the user why it's not working. A HUD message "Extention action failed: Permission denied" would suffice.

**Comment by mil3na** [comment]
This is how I've seen other extensions dealing with permission errors: https://github.com/raycast/extensions/blob/main/extensions/iterm/src/core/permission-error-screen.tsx

Maybe this can help/inspire you?
