### ISSUE TITLE
[Visual Studio Code] ...

### ISSUE THREAD

**Issue by StevenLi-DS** [raycast/extensions#7244]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

`Open With Visual Studio Code` does not work if you already open a folder. You must go back one level up and select the folder to use this cmd. It would be great if it can open the front finder folder in vscode directly, like the [Open in Visual Studio Code](https://www.raycast.com/shubzkothekar/open-in-visual-studio-code)

**Comment by aka-rabbi-inv** [comment]
i've attempted a fix for the above in a pr. please review the changes.
