### ISSUE TITLE
Reason: Extension and command preferences hasn't been found Domain: database 

### ISSUE THREAD

**Issue by iamgraeme** [raycast/extensions#7249]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Reason: Extension and command preferences hasn't been found
Domain: database
Time: 09:16:11.012
Database: raycast-enc.sqlite
Table: commands

### Steps To Reproduce

Launch Raycast
Type Spotify
select Search Artists

https://www.loom.com/share/be6a5bf72706436e9888feebf421b5a1?sid=be84900d-a654-49c6-99a7-c0a662e3540b

### Current Behaviour

Errors out

### Expected Behaviour

I would expect to be able to search by Artist?

**Comment by peduarte** [comment]
@iamgraeme Thanks for raising this, we're investigating. Meanwhile, would you mind uninstalling the Spotify Player extension, and installing it again? So sorry about the inconvenience!

**Comment by iamgraeme** [comment]
I haven't that I know of, I will reinstall tonight, thanks 🙏

**Comment by sxn** [comment]
fixed in v1.55.2
