### ISSUE TITLE
[GitHub] No longer showing icon in menu bar

### ISSUE THREAD

**Issue by CircuitSacul** [raycast/extensions#7252]
### Extension

https://www.raycast.com/raycast/github

### Description

Before the last release, the github extension would show in the menu bar, listing github notifications. Now, it simply isn't there. There's plenty of room on my menu bar and I've tried reinstalling the extension.

It looks like https://github.com/raycast/extensions/issues/7236 is the same issue.

### Steps To Reproduce

Install the GitHub extension

### Current Behaviour

No icon in menu bar

### Expected Behaviour

Icon in menu bar

**Comment by thomaslombart** [comment]
I'm unable to reproduce this bug. Are you able to see other menu bar icons for other Raycast extensions?

**Comment by CircuitSacul** [comment]
> I'm unable to reproduce this bug. Are you able to see other menu bar icons for other Raycast extensions?

Never mind, it looks like I just had to run the "Unread Notifications" command to make it appear. My bad.
