### ISSUE TITLE
[Logseq] Unable to specify path to graph

### ISSUE THREAD

**Issue by shaunrfox** [raycast/extensions#7254]
### Extension

https://www.raycast.com/futantan/logseq

### Description

I've been struggling to get the correct path to my graph. I keep getting similar errors while trying every variation I can think to try. 

This is the path I've been working with:
`/Users/USER/Library/Mobile Documents/ iCloud~com~loqseg~logseq/Documents/logseq/logseq/config.edn`

Here are some of the errors I'm getting:

- "Error: ENOENT: no such file or directory, open '/Users/USER/Library/Mobile Documents/iCloud~com~loqseg~logseq/Documents/logseq/logseq/config.edn'"

- "Folder does not exist: /Users/USER/Library/Mobile Documents/iCloud~com~loqseg~logseq/Documents/logseq/logseq/config.edn"

---

I'm not sure what's happening here, but if there's a chance that the formatting of the path is incorrect, perhaps the configuration field could be replaced with a folder picker?

### Steps To Reproduce

I'm on a Mac, running 13.4
1. Navigate to Logseq graph in Finder
2. Right-click, hold 'option', select 'Copy "logseq" as Pathname'
3. Paste into Raycast Logseq extension configuration, it auto-saves
4. Launch Raycast, select 'Quick Note' action
5. Enter text, hit 'command + return'
6. Error pops up

**Comment by hadret** [comment]
Hey @shaunrfox, from what I can see above, you are providing Logseq with path to the config.edn file instead of path to the graph (which needs to be the folder with your notes, essentially). Try to loose these two last bits `logseq/config.edn` (i.e. `/Users/USER/Library/Mobile Documents/iCloudcomloqseg~logseq/Documents/logseq`) and it should work then.

**Comment by pdomineaux** [comment]
The path `/Users/USER/Library/Mobile Documents/iCloudcomloqseg~logseq/Documents/`  refers to an graph located on iCloud Drive which does not seems to work.
I've tried to use a symlink as a workaround but in my case, it still does not work.
The iCloud Drive is used here to be able to sync the graph with the iPhone Logseq app.
Anyone with a workaround to get both tools to work (raycast and iCloud sync) ?

**Comment by pdomineaux** [comment]
The path /Users/USER/Library/Mobile Documents/iCloudcomloqseg~logseq/Documents/ refers to an graph located on iCloud Drive which does not seems to work.
I've tried to use a symlink as a workaround but in my case, it still does not work.
The iCloud Drive is used here to be able to sync the graph with the iPhone Logseq app.
Anyone with a workaround to get both tools to work (raycast and iCloud sync) ?

**Comment by pdomineaux** [comment]
Ok I've found the solution : In the Finder, Click the Cloud icon with the arrow down to download the folder locally.
Now the path is recognized in Raycast Logseq extension
