### ISSUE TITLE
[Script Commands Store – Find and manage your Raycast Script Commands] ...

### ISSUE THREAD

**Issue by jag-k** [raycast/extensions#7259]
### Extension

https://www.raycast.com/tholanda/script-commands

#### Error:
```
Error: EACCES: permission denied, mkdir '/Users/jag-k/.local/share/raycast/scripts/commands'

mkdirSync:node:fs:1396:3
list.js:21:1064
    at Array.forEach (<anonymous>)
eu.setupFolders:list.js:21:1036
```

### Steps To Reproduce

Idk how to reproduce, but I hope you know what to do

### Current Behaviour

Raycast Exception `Something went wrong`

### Expected Behaviour

Working extension)

**Comment by unnamedd** [comment]
Hello @jag-k,
thanks for opening this issue to report the error. 
Yes, I do have an idea what could've been wrong in the code, but I am wondering if you've given enough permission to Raycast access your full hard drive on System Settings (or System Preferences).

Basically what the extension is trying to do is to create a folder in this path `/Users/jag-k/.local/share/raycast/scripts/commands` but it was not possible to done. 

Check the permissions you have given to Raycast and tell me afterwards if it such configuration fixes it or not.
Looking for your return.

**Comment by unnamedd** [comment]
Hi,

as there's no further iteration in this issue, I will assume the error isn't happening for the user any more, therefore I will ask for the bot to close this ticket.

Please comment in here in case of any clarification needed.

@raycastbot close this issue
