### ISSUE TITLE
[gerrit-code-review] Allow unsafe HTTP requests options do not work

### ISSUE THREAD

**Issue by ttuygun** [raycast/extensions#7261]
### Extension

https://github.com/raycast/extensions/tree/main/extensions/gerrit-code-review

### Description

I setup a gerrit instance using a docker [image](https://hub.docker.com/r/gerritcodereview/gerrit) on my Mac without using any SSL certificate with the address of `http://localhost:8080`. Unfortunately, I cannot add gerrit instance because of the error. I think this option does not work at all.

<img width="774" alt="CleanShot 2023-06-24 at 14 11 26@2x" src="https://github.com/raycast/extensions/assets/10091984/8ada5688-9830-4b73-9a85-fc930d874d59">
<img width="769" alt="CleanShot 2023-06-24 at 14 11 40@2x" src="https://github.com/raycast/extensions/assets/10091984/32bf7bbc-8f7e-41dc-afcc-1fb2dd4f4968">

### Steps To Reproduce

1. Browse Projects (gerrit code review)
2. Add Gerrit
3. Set URL as: http://localhost:8080 (this is where gerrit instance in my local)
4. Set username, display name and password.
5. Enable Unsafe HTTPS

### Current Behaviour

Gerrit instance cannot added because TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:".

### Expected Behaviour

Gerrit instance should be added even if I use HTTP protocol

**Comment by vkhitrin** [comment]
Hi @ttuygun,

It is hard coded in the extension to use `https` requests which cause this issue when attempting to use `http` request.
https://github.com/raycast/extensions/blob/3978da85eea51ed583b554f41d897f26f1d62f2e/extensions/gerrit-code-review/src/utils/api/gerrit.ts#L2
https://github.com/raycast/extensions/blob/3978da85eea51ed583b554f41d897f26f1d62f2e/extensions/gerrit-code-review/src/utils/api/gerrit.ts#L164

I will look into this.

**Comment by ttuygun** [comment]
After new version, I encountered this error https://github.com/raycast/extensions/issues/7291
