### ISSUE TITLE
[Google Chrome Profiles] ... Allow config Local State location

### ISSUE THREAD

**Issue by hientt53** [raycast/extensions#7265]
### Extension

https://www.raycast.com/frouo/google-chrome-profiles

### Description

At the moment, the extension can only be used with Google Chrome. However, I'm eager to utilize it on other Chrome variants like Brave or Chromium. Is it possible for you to add settings that allow me to modify the path to the Local State file? 
The default path is Library/Application Support/Google/Chrome/Local State, but I would like to have the option to point it to the Local State file of Chromium, which can be found at Library/Application Support/Chromium/Local State.

### Who will benefit from this feature?

Who are the users of alternative Chrome variants like Brave, Chromium, etc.?

**Comment by frouo** [comment]
Hello @hientt53 ,

Thank you for your feedback!

This is interesting, but I see an edge case. What about people who use both Chrome and Brave as browsers (do they exist?)? With your suggestion, they would have to choose between using the extension for Chrome or for Brave, which could be a bit frustrating.

What do you think?

Thanks

**Comment by hientt53** [comment]
Thank you for your feedback. 

Regarding the matter you raised, the plugin should continue to operate as it currently does. The configuration I mentioned is merely an additional option for those with specific needs (if users don't set it, it behaves as it currently does). 

I would greatly appreciate it if you would consider adding setting  to this plugin.
