### ISSUE TITLE
[Quit Applications] ...

### ISSUE THREAD

**Issue by jakob-haywood** [raycast/extensions#7267]
### Extension

https://www.raycast.com/mackopes/quit-applications

#### Error:
```
Command id unknown


```
Command id unknown

### Steps To Reproduce

i killed the app 'pulltube' and it said api error occured, twice

**Comment by mackopes** [comment]
Hi @jakob-haywood,

Thanks a lot for reporting this. I'll investigate and get back to you when I get some time. :)
Apologies for the inconvenience though!
