### ISSUE TITLE
[Date Converter] Convert from UTC to PDT 

### ISSUE THREAD

**Issue by jaybhanushali3195** [raycast/extensions#7273]
### Extension

https://www.raycast.com/asportnoy/date-converter

### Description

Have an option to convert between time zones

### Who will benefit from this feature?

I work as a SWE and there are various places where time is in UTC but I am in PDT so its always a hassle to convert

**Comment by asportnoy** [comment]
Can you give some examples of desired inputs and outputs?

**Comment by jaybhanushali3195** [comment]
Thanks for getting back.
So, **input** can be any format time string.
For example 

1. 2023-06-23T08:37:38 ( This is in UTC ) 
2. 2023-06-23T15:37:38.306-07:00 ( This is already in PST )

Output should be the same time human-readable format in 12 hours format in PDT
June 23, 8:37 AM PST

**Comment by asportnoy** [comment]
The output should already be in your local time. For the first one, append a `Z` (`2023-06-23T08:37:38Z`) to signify that it is in UTC (most ISO dates should already have that). The second one already works for me.

**Comment by asportnoy** [comment]
Hi @jaybhanushali3195 all set on this?

**Comment by jaybhanushali3195** [comment]
Yes, sounds good.Thanns.
