### ISSUE TITLE
[Spotify Player] Play from URL

### ISSUE THREAD

**Issue by edrf12** [raycast/extensions#7276]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Add the ability to play a song/playlist from url so you can use deeplinks to control what is playing on Spotify.

### Who will benefit from this feature?

Anyone who wants an easy way to automate what is playing on Spotify somehow.

### Anything else?

The URL being like https://open.spotify.com/playlist/[id]

**Comment by peduarte** [comment]
Hey, Im not sure I understand the use case. Can you explain a bit further please?

**Comment by edrf12** [comment]
Spotify links by default do not play the song they just open it. This command would simply play songs and playlists by link. Which would also make possible binding a specific key combination to play a specific playlist on your keyboard.
