### ISSUE TITLE
[Browser Bookmarks] Expose frequently used pages to the top

### ISSUE THREAD

**Issue by elgar328** [raycast/extensions#7278]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

According to my memory, it seems that frequently used pages were exposed at the top in the previous version of the update.
Although this feature seems simple, it can save a lot of keyboard strokes when using Browser Bookmarks.
When I search for pages I frequently visit in Browser bookmarks, they are always located in the 2nd and 3rd places, so I have to press the down arrow every time. And pages that are rarely visited always appear first.

**Comment by thomaslombart** [comment]
Seems like we have a regression here. Thanks for reporting!

**Comment by thomaslombart** [comment]
@elgar328 I shipped an update that may have fixed the issue. Are frequently visited items ranked higher if you try to open a few of them?

**Comment by elgar328** [comment]
I just checked, and it's working fine!
Thank you so much for the quick update!!

**Comment by thomaslombart** [comment]
Awesome!
