### ISSUE TITLE
Enable the Jira extension to work with on-demand / managed version

### ISSUE THREAD

**Issue by icougil** [raycast/extensions#728]
# Extension – [Jira search](https://github.com/raycast/extensions/blob/a6d9ac115da2ebf4c1b41f710ea4b4b46a5b3f7c/extensions/jira-search/README.md)

Author: @svenwiegand 

**Describe the feature and the current behavior/state.**
Hi! It will be amazing to be able to use this feature not just only with the Cloud version of the Jira managed / on-demand version.

**Who will benefit with this feature?**
All the users have their own Jira installation in their companies 😉

**Any Other info.**
N/A

Thank you in advance!

**Comment by svenwiegand** [comment]
Thanks for the request @icougil. As Jira Server will be sunset in two years, this looks like a niche solution ;-) But hey, this a still two years …

Unfortunately, I do not have a Jira Server system to test with. If you could provide a test account, I could take a look into it.

**Comment by icougil** [comment]
Oh really Jira Server is going to be "deprecated"? Didn't knew that 😮.

I am working with a Jira Server, but it is a corporate one, as you can imagine, I can't give you access to the server... so I can't see how we can work with this, apart from following the API and trying to implement the requests/endpoints required...

**Comment by svenwiegand** [comment]
Sorry for the late reply @icougil. I‘ve decided to not implement this due to the deprecation of Jira Server and the problems with the testing. 

Maybe there is another developer who is interested in this, has access to a Jira server system and wants to implement this.
