### ISSUE TITLE
[Raindrop.io] Separate highlights are not displayed correctly

### ISSUE THREAD

**Issue by wyatt** [raycast/extensions#7281]
### Extension

https://www.raycast.com/lardissone/raindrop-io

### Description

![image](https://github.com/raycast/extensions/assets/40368472/7977befa-5d0b-4983-9b59-ba2ed2bc88a9)
When searching for a bookmark and opening the "Show details" panel, the highlights section does not separate the individual highlights into separate quotes

### Steps To Reproduce

1. Add an article to raindrop and add several separate highlights
2. Search for it, and view its details within the Raycast extension

### Current Behaviour

All highlights are in a single block quote, separated by ">" characters

### Expected Behaviour

Highlights are separated into individual block quotes, with spacing between each one

**Comment by lardissone** [comment]
@wyatt thank you for reporting it! Will fix it asap!

**Comment by lardissone** [comment]
@wyatt created a PR with the fix: #7282
