### ISSUE TITLE
[gerrit-code-review] 401 Unauthorized after a instance added successfully 

### ISSUE THREAD

**Issue by ttuygun** [raycast/extensions#7291]
### Extension

https://github.com/raycast/extensions/tree/main/extensions/gerrit-code-review

### Description

Any action (Browser Projects, Query Changes, etc.) returns `Fetch failed 401 Unauthorized` after a instance added successfully without any error.

### Steps To Reproduce

1. Add a instance without getting any error.
2. Browse Projects
3. Select added (showed as Logged In) instance

### Current Behaviour

After 3, you will get `Fetch failed 401 Unauthorized` error left bottom corner of Raycast.

**Comment by vkhitrin** [comment]
Hey @ttuygun,

Are your HTTP credentials correct? There should be an authorization check that will not allow users to add the instance if they fail to authenticate. I am unsure why it didn't work in your case (unless it is a bug with some API call).
Could you please provide some info:
1. What is the version of Gerrit's instance?
    You can check it on the bottom left corner of the web UI
	<img width="377" alt="Screenshot 2023-06-28 at 12 16 48" 	src="https://github.com/raycast/extensions/assets/32794653/f7c3d75a-aeb6-4883-9b24-af18cf39ddfe">
	Or hovering on the instance favicon in Raycast
	<img width="823" alt="Screenshot 2023-06-28 at 12 21 14" src="https://github.com/raycast/extensions/assets/32794653/e594fb8d-001d-49fa-87d7-737282a4ba8f">

2. Can you try and access your instance without credentials to see if it works (if your instance supports public access)?

**Comment by vkhitrin** [comment]
@ttuygun, I can reproduce this across many versions of Gerrit.

I think I broke the credentials check, which is not working correctly.

https://github.com/raycast/extensions/blob/ea04f893e95e94a27e9f82af57a6c4b11c18ebc2/extensions/gerrit-code-review/src/utils/api/gerrit.ts#L188-L190

**Comment by ttuygun** [comment]
@vkhitrin I setup your last PR as locally. Unfortunately, I still getting 401 unauthorized error.

I debug your last commit. You request `SERVER_URL/a/config/server/preferences`
I tried access with in a private window of a browser with requested URL. Sadly, I still cannot authenticate even in the browser. When I delete the following path `/a/config/server/preferences`, I can access without any authentication error. I think there is a trick or a problem when we try to authenticate gerrit instance with preferences path

**Comment by vkhitrin** [comment]
Hey @ttuygun,
I'm sorry for the long delay.

I can access `/a/config/server/preferences` when I am authenticated with the browser.
Can you please share the Gerrit instance version you are attempting to use?
