### ISSUE TITLE
[1Password] ...

### ISSUE THREAD

**Issue by craigharman** [raycast/extensions#7298]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Allow multiple 1Password accounts.

Currently when you login for the first time you are asked to select a 1Password account. I'd like to be able to search all my passwords across all my accounts.

### Who will benefit from this feature?

Anyone with multiple 1Password accounts - given you get a free personal account with business accounts this would be a lot of users.

**Comment by gwenwindflower** [comment]
cosign, i need this as well!

**Comment by craigharman** [comment]
No takers? It's a shame as I can't use the 1Password extension without it.

**Comment by pernielsentikaer** [comment]
We might be able to give this a test more: https://github.com/raycast/extensions/pull/7571 - but it was actually implemented @craigharman
