### ISSUE TITLE
[GitHub] Show repository in Notification list

### ISSUE THREAD

**Issue by jmatsushita** [raycast/extensions#7301]
### Extension

https://www.raycast.com/raycast/github

### Description

Really appreciate the recent work on Github notifications by @loxygenK  to [show PR/issue numbers](https://github.com/raycast/extensions/pull/7181)) and I find myself missing a way to see which repository the notification  originated from.

~~Right now, all my notifications have a `Watching` label which also feels like it's redundant (but maybe it's used for something I don't know of).~~ [nvm](https://github.com/raycast/extensions/issues/7301#issuecomment-1611005149) 

<img width="530" alt="image" src="https://github.com/raycast/extensions/assets/356097/a73e0f7c-bb09-417e-9e22-1033b19a2a00">

### Who will benefit from this feature?

Anyone receiving notifications from more than one github repository.

**Comment by jmatsushita** [comment]
Ha ha, well submitting this issue answered my question about the `Watching` label immediately 🤣 

<img width="536" alt="image" src="https://github.com/raycast/extensions/assets/356097/9b6d3b54-2f0c-4180-874f-52797c939e7c">

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by tonka3000** [comment]
@xilopaint I already found the issue. I will make a PR later.

**Comment by tonka3000** [comment]
@xilopaint Can you maybe check if the PR #7788 works for you?

**Comment by xilopaint** [comment]
@tonka3000 Sorry, I've never developed for Raycast. I don't know how to install the extension from your PR. Can you guide me?

**Comment by tonka3000** [comment]
@xilopaint Sure.

1. First you need to get the source code of my PR.

     You can do this via a zip file which could be faster/easier (git version also possible, see below). Goto https://github.com/tonka3000/extensions/tree/github-fix-menu-repo-missing ,click on the green button `<> Code` (upper right corner) and use `Download ZIP`. After the download you can extract it to a place of your choice on the disk.

    The git way: Clone my fork https://github.com/tonka3000/extensions with `git clone https://github.com/tonka3000/extensions.git` in a terminal. And switch to the branch `tonka3000:github-fix-menu-repo-missing` with `git checkout -b tonka3000:github-fix-menu-repo-missing origin/tonka3000:github-fix-menu-repo-missing`


2. Now goto the source folder (the git clone version or the unzipped content)
3. Goto the folder `extensions/github`
4. Call `npm ci` on the terminal (if you got an error here you need to install nodejs 18 first)
5. Call `npm run dev`
6. Raycast should now popup and you should see all GitHub Commands (your store installed version is not touch at all, this is a second copy of the extension with different settings)
7. Now start the GitHub Menu command (the one with the green icon on the right)
8. Authenticate if required
9. Now you should see a second menu command

Let me know if you need more support

**Comment by xilopaint** [comment]
@tonka3000 I just tested and the PR works. Thanks!

Btw, wouldn't it be better to place the repository name and the issue/PR numbers above the title with a smaller font like we have in the GitHub website?

<img width="635" alt="Screenshot 2023-08-03 at 19 12 55" src="https://github.com/raycast/extensions/assets/11052366/812da471-0ca8-43c7-9061-0e0401b165c7">

It would save space and improve readability, especially when the title is long.

**Comment by tonka3000** [comment]
@xilopaint The Raycast API just have the ability to set a title and a subtitle (light-gray text) and there is can not be modeled with Raycast for now. Maybe @thomaslombart has some ideas here.

**Comment by thomaslombart** [comment]
Unfortunately, it is not possible as we have constraints with the menu bar.

**Comment by xilopaint** [comment]
@thomaslombart Do you mean constraints in the Raycast API or in the Apple API?

**Comment by thomaslombart** [comment]
I meant the Raycast API. We can only set a title and a subtitle as @tonka3000 said.

**Comment by xilopaint** [comment]
@tonka3000 Could you take a look into #7727?
