### ISSUE TITLE
[GitHub] False `Review Requested` flag

### ISSUE THREAD

**Issue by konsalex** [raycast/extensions#7305]
### Description

False `Review Requested` tag

You can see in the image 

<img width="740" alt="CleanShot 2023-06-28 at 16 20 02@2x" src="https://github.com/raycast/extensions/assets/12672541/745083e5-59a4-429f-95d3-8f2ce17e3a8b">

for `Table Navigation experiments #575`  that there is `Review Requested`.

In this case, this is wrong, as review is required, but not yet requested 

<img width="379" alt="CleanShot 2023-06-28 at 16 22 26@2x" src="https://github.com/raycast/extensions/assets/12672541/cf020f9b-b204-42ad-bc52-402262cc9256">

### Current Behaviour

Label is `Review Requested` with 0 reviewers

### Expected Behaviour

To have `Review Required` as label, and not `Requested`

**Comment by thomaslombart** [comment]
Thanks for reporting out this typo. I've fixed it: https://github.com/raycast/extensions/commit/98d03125c875f1e2a194bb99e019ab17146f0e0e.
