### ISSUE TITLE
[Logseq] Can't search for pages

### ISSUE THREAD

**Issue by ituri** [raycast/extensions#7309]
### Extension

https://www.raycast.com/futantan/logseq

### Description

I can't find any pages using the plugin. My pages are stored in my root folder as well as in some subfolders inside the root folder. I'm not using the default setup though where pages are stored in the /pages folder inside the root folder. 

Is there any chance to make the plugin search the root- and other subfolders as well?

### Steps To Reproduce

c.f. above.

**Comment by hadret** [comment]
Hi @ituri, I don't think it's possible right now with the current version, the `/pages` part is hardcoded: https://github.com/raycast/extensions/blob/635c928ffc59351ca66067543dc81f9424ff85f1/extensions/logseq/src/logsearch.tsx#L107C2-L107C82

What you may experiment with is to go through these steps: https://developers.raycast.com/basics/contribute-to-an-extension and then just drop the ` + "/pages"` part or replace it with whatever you have in there instead. I'm not sure this is going to yield expected results or any results whatsoever for that matter.
