### ISSUE TITLE
[Toggl Track] also shows archived projects, which is not what you would expect

### ISSUE THREAD

**Issue by adkoen** [raycast/extensions#7316]
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Description

When searching for a project to track time, the results also contains projects that are archived within toggl. Which gives errors like pulling up a report and the tracked time isn't there (because it has been tracked against an archived project.
Solution: by default the extension should only return active projects. Maybe you could add an option to include archived projects as well (but I would not be using that :-) )

### Who will benefit from this feature?

Everyone, now you can make serious mistakes and end up not charging for multiple tracked hours.

### Anything else?

ONo

**Comment by rogatty** [comment]
@adkoen see https://github.com/raycast/extensions/issues/5757#issuecomment-1495789595, and feel free to open PR.

**Comment by adkoen** [comment]
@rogatty I would add this as a PR (Pull Request), if I knew what to do. Never did a pull request before.

**Comment by rogatty** [comment]
@adkoen see https://github.com/raycast/extensions/blob/main/CONTRIBUTING.md 🙂
