### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by Chengiss** [raycast/extensions#7319]
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```
Error: Command failed with exit code 1: osascript
436:441: syntax error: Expected end of line, etc. but found identifier. (-2741)

Z5:run-applescript.js:38:21

---
35:         timedOut,
36:         command: "osascript",
37:         options,
38:         parentError: new Error(),
39:     })

### Steps To Reproduce

install spotify extension
choose your library

### Current Behaviour

not playing song. showing "something went wrong"

### Expected Behaviour

play song

**Comment by peduarte** [comment]
Hey, just so I understand this correctly. Your steps were:
1. Open "Your Library" Command
2. Find a Song (or was it an Artist, Album, etc?)
3. Press Play
4. Error

Can you please be specific as you can in the order of events, then I can try and reproduce. 

Thanks!

**Comment by Chengiss** [comment]
Hi,

Let me add some screenshots:

1. Look for spotify extension
[image: image.png]
2. Go into "Search"
[image: image.png]
3. Choose Something
[image: image.png]
4. Press Return
[image: image.png]

This is today's behaviour. Yesterday it said "something went wrong" but
today I didn't get that message.

Thanks in advance.

**Comment by peduarte** [comment]
Thanks for that 🙏 So are saying that today it worked, but yesterday you got a "something went wrong" error?
