### ISSUE TITLE
[ChatGPT] ... API Limit / ChatGPT Plus API

### ISSUE THREAD

**Issue by royaloakks** [raycast/extensions#7321]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Forgive the newbie question but i have a ChatGPT Plus subscription. I have added the API to the Raycast Extension but it says i've reached my limit. Do i also need an Azure API 'pay as you go' to also to make it work? If i sign up for Azure do I still new a ChaGPT Plus account?

### Steps To Reproduce

<img width="862" alt="Screenshot 2023-06-29 at 14 52 56" src="https://github.com/raycast/extensions/assets/138127186/3adc83e5-401b-4b59-8d1c-63f9c7f42cb9">

**Comment by Nauxscript** [comment]
This is the answer from Chat-GPT 😂:

> If you have a ChatGPT Plus subscription, you do not need an additional Azure API subscription to use the ChatGPT API. The ChatGPT API is separate from the Azure API, and your ChatGPT Plus subscription covers the usage of the ChatGPT API.
> 
> However, it's important to note that as of my knowledge cutoff in September 2021, the ChatGPT API is not included in the ChatGPT Plus subscription. It is billed separately and has its own pricing. To use the ChatGPT API, you would need to sign up for it and pay for the API usage based on the pricing provided by OpenAI.
> 
> It's possible that the Raycast Extension you mentioned has its own limitations or requirements, so you may want to consult the documentation or support resources specific to that extension to understand why you're seeing the limit message.
> 
> In summary, if you sign up for the ChatGPT API, you would not need an Azure API 'pay as you go' subscription. However, you would still need a ChatGPT API subscription (separate from ChatGPT Plus) to make use of the ChatGPT API.

![image](https://github.com/raycast/extensions/assets/13010589/de6a0317-093c-45e0-a1b0-84fa3771e893)

@raycastbot close this issue

**Comment by royaloakks** [comment]
HA, not sure this actually answers my question as i still don't know what i need.

So there's a Chat GPT subscription and API and a Chat GPT Plus subscription API. There's also a Azure API which you do or don't need?

**Comment by Nauxscript** [comment]
As I know, Azure is a service provided by Microsoft, so it has no direct relationship with GPT. On the other hand, Chat-GPT Plus allows users to access the GPT service on the official OpenAI website and also offers the use of the GPT-4 model. However, Chat-GPT API is used for integration of Chat-GPT functionality in third-party applications or services, and it requires a separate subscription. It is different from the Chat-GPT Plus service.

**Comment by royaloakks** [comment]
So in short i don't need a ChatGPT plus account... instead i should get an Open API paid for account which will supply the API i need to integrate ChaGPT with applications such as Raycast?
