### ISSUE TITLE
[Microsoft Edge] ...

### ISSUE THREAD

**Issue by fenqiang4952** [raycast/extensions#7324]
### Extension

https://www.raycast.com/KartikKumarSahoo/microsoft-edge

### Description

After using the shortcut key to open "bookmarks" or "history", the selected URL cannot be opened in the browser, and there is no response after pressing "enter".
But it can work normally after opening with the command.

### Steps To Reproduce

env:
Apple M1 Pro  Mac OS 13.4.1 
Edge: 114.0.1823.58
raycast: 1.54.1

### Current Behaviour

Use the shortcut to open "bookmarks",
press "enter"
Can't open webpage in browser

**Comment by KartikKumarSahoo** [comment]
This should be fixed by this PR https://github.com/raycast/extensions/pull/7526
