### ISSUE TITLE
[Kagi FastGPT] ...

### ISSUE THREAD

**Issue by Ek2100** [raycast/extensions#7325]
### Extension

https://www.raycast.com/http.james/kagi-fastgpt

### Description

When entering anything in the Kagi FastGpt extension, it just shows the "Something went wrong screen". My API key is correct and its still not working.

<img width="767" alt="image" src="https://github.com/raycast/extensions/assets/113011003/a2969582-4151-4a57-a28c-621acd5e7bd3">

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'output')

ask.tsx:30:39

---
27:       } finally {
28:         setLoading(false)

### Steps To Reproduce

1. Run Extension with any input
2. Look at the error.

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by httpjamesm** [comment]
Hmm. Can you confirm the extension is up to date? Have you added credits to your account? The credits error should show up, but just checking.

**Comment by Ek2100** [comment]
Yep, I did all this and the extension is up to date. It seems to be working now so not sure what happened.

**Comment by Ek2100** [comment]
@raycastbot close this issue
