### ISSUE TITLE
[browser-bookmarks] make the Fuzzy Search configurable

### ISSUE THREAD

**Issue by wklken** [raycast/extensions#7326]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

in the lastest version, add feature fuzzy search https://github.com/raycast/extensions/blob/7a90d69858a14b5dc91c7b9018003434fb3e18c3/extensions/browser-bookmarks/CHANGELOG.md

before that version, I always get what i want after typing. but now, I always need to find the item after scrolling pages.

even i type the same word as the bookmark, it's not on the top!

the result not sorted by the correlation? 

### Who will benefit from this feature?

make the fuzzy search configuable?

**Comment by thomaslombart** [comment]
Hey @wklken, could you send a recording to see what's happening for you?

**Comment by wklken** [comment]
<img width="836" alt="image" src="https://github.com/raycast/extensions/assets/2002216/e5b0a61e-f831-4794-aded-0271508d49a5">

- the previous version, the target is on the top(top 1)
- the current version, position is about page 2/3

**Comment by thomaslombart** [comment]
Maybe the fuzzy search is too sensitive. Would you mind testing it out locally by modifying the configuration here: [`index.tsx` L168](https://github.com/raycast/extensions/blob/effb58b9558c2a5ced68e896942ed16f8f6b7e06/extensions/browser-bookmarks/src/index.tsx#L168) with the [fuzzy search `threshold` parameter](https://fusejs.io/api/options.html#threshold)?

**Comment by wklken** [comment]
> Maybe the fuzzy search is too sensitive. Would you mind testing it out locally by modifying the configuration here: [`index.tsx` L168](https://github.com/raycast/extensions/blob/effb58b9558c2a5ced68e896942ed16f8f6b7e06/extensions/browser-bookmarks/src/index.tsx#L168) with the [fuzzy search `threshold` parameter](https://fusejs.io/api/options.html#threshold)?

Is there any documentation that can guide me on how to locate and make changes to that file on my computer?

**Comment by thomaslombart** [comment]
Sure: https://developers.raycast.com/basics/contribute-to-an-extension.

**Comment by wklken** [comment]
It turns out not the `threshold` make the result order wrong, it the `domain` of `keys: ["title", "domain", "folder"]`!

the keywords both hit `domain` and `title`.

the `title` should have the greater weight than `domain` and `folder`? 

when we save a bookmark, like `https://github.com/raycast/extensions`, the title is auto be `raycast/extensions: Everything you need to extend Raycast.`, and when we want to search in hundreds bookmarks, it's reasonable the title be much more import than `domain`.

<img width="775" alt="image" src="https://github.com/raycast/extensions/assets/2002216/63ecc4e7-20b1-4919-9e55-1b2c826ee633">

(can't figure out why they hit!)

**Comment by thomaslombart** [comment]
What if you remove the `domain` and the `folder` keys and turn down the `threshold` a bit (to `0.4` for example)?

**Comment by wklken** [comment]
> 

Much better, but still not as good as the previous version. It doesn't work the same way as `fzf`, and I'm still unsure about why some results are being included.

<img width="835" alt="image" src="https://github.com/raycast/extensions/assets/2002216/5af2147f-ccd4-4b20-b116-27bb7d61dd7b">

**Comment by thomaslombart** [comment]
I don't know much about the internals of the [fuzzy search package](https://fusejs.io) that's used, to be honest.

**Comment by muchzill4** [comment]
@wklken thanks for looking into this. I find the new version not match what I'd expect either. I did play with `threshold`, as suggested by @thomaslombart, but that didn't help much.

So far, I'm getting the accuracy I'm used to by using:

```ts
    return new Fuse(folderBookmarks, {
      keys: ["title", "domain", "folder"],
      ignoreLocation: true,
      ignoreFieldNorm: true,
    });
```

@wklken could you give this a shot and share your experience?

**Comment by thomaslombart** [comment]
I've shipped a fix @muchzill4 and @wklken. Does this give you more accurate results?

**Comment by wklken** [comment]
much better than previous version!
thanks @thomaslombart

**Comment by muchzill4** [comment]
It does indeed. Thank you @thomaslombart.
