### ISSUE TITLE
[Authy] ...

### ISSUE THREAD

**Issue by rbnj0904** [raycast/extensions#7327]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

All the tokens appear as corrupted instead of numbers. Except one token

### Steps To Reproduce

In raycase, when i search for token. All tokens except one shows as corrupted

**Comment by guga4ka** [comment]
seems like you have provide incorrect backup password

**Comment by rbnj0904** [comment]
You are right, thank you.

Would make it easier to point out that the backup password is 12 characters
minimum :)

**Comment by guga4ka** [comment]
@raycastbot close this issue 

@rbnj0904 probably this is configured at authy backend that i have not access to
