### ISSUE TITLE
Typos, unclear documentation.

### ISSUE THREAD

**Issue by fluidstu** [raycast/extensions#7329]
### Description

YouTube API key setup documentation page.
For someone who has no experience of API keys and who wants to get started with RayCast, this documentation page is very difficult to follow.

1. There are numerous typos and incorrect grammar.
2. "Enable the API via the dashboard. Click on the to activate APIs on the top of the website and search for youtube data api v3".
What is a 'dashboard'? "Click on the "… click on the WHAT?

I gave up here and went back to Alfred.

**Comment by mathieudutour** [comment]
@tonka3000 @SKaplanOfficial @madza91 maybe something to improve in the readme?
