### ISSUE TITLE
[Visual Studio Code] VSCodium support

### ISSUE THREAD

**Issue by boldandbrad** [raycast/extensions#7340]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

[VSCodium](https://vscodium.com/) support would be great!

VSCodium is exactly the same as VSCode but without the telemetry and bloat. It just happens to store its data in differently named directories/files. 

### Who will benefit from this feature?

All users to prefer VSCodium to VSCode.

**Comment by tonka3000** [comment]
@boldandbrad switch to VSCodium in the preferences. This should be already supported.

**Comment by boldandbrad** [comment]
🤦‍♂️ you are correct. I knew I missed a step between install and ask. Thank you.
