### ISSUE TITLE
Append task [Obsidian] ...

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#7344]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

![Screenshot by Dropbox Capture](https://github.com/raycast/extensions/assets/64922803/204cc09b-fe81-42c5-8c52-6389fb6ab077)
Append task command creates a separate folders (see the screenshot) though I pointed to my vault and particular note.
Could it be because the vault is in iCloud?

Other actions like "Append to daily note" work as expected.

Advance URI is installed.

### Steps To Reproduce

1. Add a vault path to Obsidian extension
2. Add a note path to "Append Task" action
3. Execute "Append Task" action
4. A new folder tree was created (see the screenshot) instead of appending the text to a predefined note.

### Current Behaviour

A new folder tree was created (see the screenshot)

### Expected Behaviour

Should append the text to a predefined note.

**Comment by KevinBatdorf** [comment]
I couldn't reproduce it. What does your task note path look like?

If I have a vault named `brain` and a note `Test note` set then the URL that's being used behind the scenes looks like this:
```
obsidian://advanced-uri?mode=append&filepath=Test%20note&data=-%20%5B%20%5D%20%23task%20my%20task&vault=brain&openmode=silent
```

If you update the URL to your vault/note is the result the same? 
(you can copy/paste the URL into your browser in case you didn't know)

**Comment by romanskorobagatko** [comment]
When I right click the note and hit copy advanced uri I’m getting this - obsidian://advanced-uri?vault=Obsidian%20Vault&filepath=todolistlink.md
