### ISSUE TITLE
Extensions management menu in the preferences does sort randomly when having the production and dev version next to each other

### ISSUE THREAD

**Issue by tonka3000** [raycast/extensions#7354]
### Description

The Extension Preferences list get sorted randomly (between same extension) when having both, the development version and the production (store) version next to each other.

https://github.com/raycast/extensions/assets/3163807/95050c00-964e-4d2a-b7ea-7f2b61dbffd7

I often disable the development commands after developing to keep the settings when needed again.

This effect also happen when enable/disable a single command in it as well.

### Steps To Reproduce

1. Go to preferences
2. Go to extension tab
3. Scroll to the extension which has dev and prod version
4. Disable/Enable all commands of the dev version

### Current Behaviour

The position of the 2 extension jumps which leads to the effect that I sometimes check/uncheck the wrong extension.

### Expected Behaviour

The sorted should respect the dev flag as well when both version are installed. The order (dev or prod first) is not that important, more that it stay consistent.

**Comment by mathieudutour** [comment]
Ah good catch, will be fixed in the next release
