### ISSUE TITLE
[Ruler] Night Shift + Red Outline 

### ISSUE THREAD

**Issue by Ek2100** [raycast/extensions#7361]
### Extension

https://www.raycast.com/anwarulislam/ruler

### Description

- When you have night shift enabled, it will temporarily disable it while the command is enabled.
- It displays some weird red border around your screen

### Steps To Reproduce

1. Turn On Nightshift
2. Run the extension

### Current Behaviour

Temporarily disables nightshift and shows a red border

https://github.com/raycast/extensions/assets/113011003/d75d1c07-a103-4162-8338-76433784604e

**Comment by anwarulislam** [comment]
Hi, @Ek2100! 

I kept that red line intentionally. 
- Night shift doesn't get disabled
- Red line is an indicator

It indicates that the ruler is open now.

If you think we can/should change the behavior please let me know how we should do it. I'll try to add features.
