### ISSUE TITLE
[Asana] When activating a command I an error prevents use of the feature.

### ISSUE THREAD

**Issue by BennEntterprise** [raycast/extensions#7363]
### Extension

https://www.raycast.com/raycast/asana

### Description

#

#### Error Copied to the clipboard:
```
Error: Authentication error: unable to refresh tokens

gX:oauth.ts:64:10

---
61: 
62:     return tokenResponse

### Steps To Reproduce

1. Trigger a command like "Create Task" for the extension. 
2. You will see there is an error screen.
3. When following the prompts There is an option to Sign In to Asana.
4. The link opened for login is broken 

### Current Behaviour

The link opening asana for login is broken so I don't know how to fix it.

### Expected Behaviour

That I be permitted to login to Asana and that raycast-asana extension will be able to create and manage asana tasks on my behalf.

**Comment by BennEntterprise** [comment]
Here is a recording. 

I will also note that I may be having the same bug as [this issue](https://github.com/raycast/extensions/issues/7231) but I opened a new issue since I don't have any vpns or anything like that. 
https://github.com/raycast/extensions/assets/29560043/1d84b4e7-4423-4b2a-be08-ead1024e3a53

**Comment by thomaslombart** [comment]
Same as https://github.com/raycast/extensions/issues/8139.
