### ISSUE TITLE
[MOCO] Find projects by client name

### ISSUE THREAD

**Issue by flokosiol** [raycast/extensions#7369]
### Extension

https://www.raycast.com/eviscares/moco

### Description

**Current behavior**  
When you use the "Todays Activities" or "Manage Time Bookings" command you can filter all entries by searching a name of project. 

**Feature request**  
It would be amazing if you could also filter by the name of the client.

### Who will benefit from this feature?

Everyone who has to handle different projects with similar names across multiple clients will benefit from this feature.

### Anything else?

Thanks a lot for your work and this MOCO extension!

**Comment by eviscares** [comment]
Hey, thanks for the feature request. I'll take a look if I can implement something like that. :)

**Comment by flokosiol** [comment]
@eviscares Today I found the time to have a look on how to develop Raycast extensions. I forked your MOCO extension and found a solution for this issue by adding keywords to the corresponding ListItem. Are you interested in a pull request? It's just a single additional line. I could go ahead like described here: https://developers.raycast.com/basics/contribute-to-an-extension
