### ISSUE TITLE
[Authy] Unable to refresh token list

### ISSUE THREAD

**Issue by vladfrangu** [raycast/extensions#7378]
### Extension

https://www.raycast.com/guga4ka/authy

#### Error:
```
Error: Invalid base32 characters

uu:OtpListItem.tsx:72:38

---
69:   setOtpList: (value: (prev: Otp[]) => Otp[]) => void
```

I also noticed, but unfortunately wasn't able to catch in a screenshot, that there was a message where the loading indicator was that says `Command id unknown`. Not sure what that is about 😅 

I'm also unsure if its a full duplicate of #5880 (I did try the steps of uninstall->reinstall but that didn't change anything)

### Steps To Reproduce

1. Refresh Authy

### Current Behaviour

It doesn't seem to load, and is giving the error in the description

### Expected Behaviour

It should load the list just fine!

**Comment by gdsmith** [comment]
Hoping that #7381 helps avoid the error.
