### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by Peterb999** [raycast/extensions#7383]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

I've installed ffmpeg and still get the message "ffmpeg is not installed." Help! Thanks. 

### Steps To Reproduce

I'm running Raycast 1.54.1 in MacOS 13.4.1

**Comment by vimtor** [comment]
I think this is a duplicate of #7230. I will add an option for the user to specify where `ffmpeg` is installed 😀

**Comment by vimtor** [comment]
This has been fixed in #7350

**Comment by vimtor** [comment]
This has been fixed in #7350

@raycastbot close this issue
