### ISSUE TITLE
Something went wrong on "Search matches"[Espanso] ...

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#7384]
### Extension

https://www.raycast.com/kud/espanso

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

### Steps To Reproduce

1. Launch Espanso
2. Execute "Search matches" command from Raycast

### Current Behaviour

Getting "Something went wrong" message

### Expected Behaviour

Ability to search matches

**Comment by kud** [comment]
Hey @romanskorobagatko , could you provide me your espanso file? Also does it work when you start the espanso search bar?

**Comment by kud** [comment]
I cannot reproduce the error at the moment. Feel free to add any comment to help on this otherwise it'll be closed.
