### ISSUE TITLE
[Harvest] ...

### ISSUE THREAD

**Issue by ovanbiervliet** [raycast/extensions#7386]
### Extension

https://www.raycast.com/eluce2/harvest

### Description

When setting the time format to hours:minutes, the menu bar item doesn't reflect these changes. 

### Steps To Reproduce

1. Set time format to hours:minutes
2. Check the running timer in the menu bar

### Current Behaviour

Keeps displaying decimal time in menu bar

### Expected Behaviour

Adapts to the selected time format

**Comment by stephenmatthews** [comment]
I'm having the exact same issue

**Comment by eluce2** [comment]
Thanks everyone, oversight on my end. A fix is in the works!
