### ISSUE TITLE
[Ecosia Search] Searches should be URL encoded 

### ISSUE THREAD

**Issue by BramMusters** [raycast/extensions#7388]
### Extension

https://www.raycast.com/mcocirio/ecosia-search

### Description

Whenever I try to search something that contains a special character like a Space, A "Could not open the App" error shows.

### Steps To Reproduce

1. Use the Ecosia Search command
2. Type "foo bar"
3. Press enter

Wat does work:
"foobar"

Also, entering the URL encoded versio `foo%20bar` directly does work.

**Comment by MFCo** [comment]
Thanks for reporting @BramMusters! Just opened https://github.com/raycast/extensions/pull/7391 with the fix
