### ISSUE TITLE
[API Bug] Form.TextArea component cannot input Chinese

### ISSUE THREAD

**Issue by ahonn** [raycast/extensions#739]
Raycast version: 1.27.0

## Description

https://user-images.githubusercontent.com/9718515/150907654-068b313a-dc94-4afd-916d-e75fe2201c5e.mp4

Send to flomo plugin can't input Chinese, it was working when I PR'd this plugin to this repository, but now it doesn't work

* Form.TextArea can't input Chinese, but Form.TextField can.
* Form.TextField has a weird behavior.

I didn't find Form's code, I guess the composition event of the input method is not handled correctly

## Steps To Reproduce

1. Install [Send to flomo](https://www.raycast.com/ahonn/send-to-flomo) extension
2. Switch input method to Pinyin
3. Enter Chinese into the MEMO or tags

## The current behavior
Chinese input does not go in

**Comment by mathieudutour** [comment]
It does seem that there is an issue when using the `value` prop with a `Form.TextArea`. Are you certain it used to work before?

**Comment by ahonn** [comment]
I'm not sure it used to work before.  And `TextField` also has problems with Chinese display.
So how do I fix this, avoid using the `value` prop with `Form.TextArea`/`Form.TextField`?

**Comment by yuewei-c** [comment]
I'm having the same problem, is there a solution yet?

**Comment by mattisssa** [comment]
> I'm having the same problem, is there a solution yet?

Hey, unfortunately we haven't fixed the issue yet. Sorry for inconvenience

**Comment by mattisssa** [comment]
Should be fixed in v1.37.0
