### ISSUE TITLE
[Summarize YouTube Videos with AI] ...

### ISSUE THREAD

**Issue by Vibaek96** [raycast/extensions#7393]
### Extension

https://www.raycast.com/iKasch/summarize-youtube-video-with-ai

### Description

When I try to use this extension with the ChatGPT as AI I get the following error: "Request failed with status code 429".

My OpenAI API Token has been applied and is marked as "used" on their website. Is it possible to fix this?

**Comment by iKasch** [comment]
@Vibaek96 thabks for reporting! Error 429 means there were too many requests to openai in a short amount of time. 

Can you confirm that your API Key works on other apps like https://chatbotui.com ?

You can also check this thread for additional help: https://github.com/raycast/extensions/issues/7311

**Comment by Vibaek96** [comment]
Thanks for the response. I found the issue was on my end: my 3 month free API trail had expired.
