### ISSUE TITLE
[Harvest] Project value disappears on new entry

### ISSUE THREAD

**Issue by ovanbiervliet** [raycast/extensions#7397]
### Extension

https://www.raycast.com/eluce2/harvest

### Description

When creating a new timer, sometimes the selected Project disappears and the list of projects is empty. I have to abandon the ticket creation at that point and start over.

So far I have not been able to pinpoint when exactly it happens, it is sporadic.

Note: my current project list has only 1 entry. This may/may not be relevant.

### Steps To Reproduce

1. Harvest -> New Time Entry
2. Select [Project]
3. Select [Task]
4. Start typing in [Notes]
5. Notice that sometimes the [Project] field is reset to '-'.
6. Additionally, the dropdown doesn't contain any projects at that point.

![Ø2307-012853@2x
](https://github.com/raycast/extensions/assets/3488544/ea6ce04e-788a-4dd1-8c06-11bbd8114e28)

![Ø2307-012854@2x](https://github.com/raycast/extensions/assets/3488544/02d546b2-c5ea-4174-a27a-bd98c000f73b)

### Current Behaviour

When editing the Notes field, the Project field is sometimes reset.

### Expected Behaviour

Project field should not change when editing other fields.

**Comment by eluce2** [comment]
Thanks for reporting this. I have also noticed this behavior occasionally but have not yet pinned down the cause. Are you by chance using the menu bar portion also ("Running Timer" command)? If so, do you have anything set in the Callback URL fields for that command?
![CleanShot 2023-07-15 at 12 47 16@2x](https://github.com/raycast/extensions/assets/37158449/78026571-dc98-417b-b9f0-cf3ec6faf01b)

**Comment by ovanbiervliet** [comment]
Yes, that was active and the callback urls were empty. Should I disable for now, or enter some urls (which)?

**Comment by eluce2** [comment]
I'm wondering if this is tied to the background refresh, but I can't say for sure. I haven't been able to replicate this issue for the past week or so and my background refresh is toggled off. I'll try turning it back on and keep testing on my end

The background refresh is only needed to keep the shown time in the menu bar accurate as a timer is running, but if you hide the time and always start/stop timers using Raycast it isn't needed.

**Comment by ovanbiervliet** [comment]
I had disabled the menu item and background refresh but it still acted this way when editing an time entry. For now I have stopped using it due to this. Thanks anyway.

**Comment by eluce2** [comment]
Hey @ovanbiervliet. An update to the Harvest extension was released today. One of the changes included catching Harvest's rate limiting error which I believe may have been causing this behavior. So far I have not run into this bug anymore, so you may be able to give it another shot on your end!
