### ISSUE TITLE
[Spotify Beta] API rate limit exceeded

### ISSUE THREAD

**Issue by vimtor** [raycast/extensions#7399]
### Extension

https://raycast.com/mattisssa/spotify-beta

#### Error:
```
Error: API rate limit exceeded
    at qp (/Users/vimtor/.config/raycast/extensions/56a2815e-83a0-44c6-8f3c-04ef778f3298/search.js:63:2695)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

This error is being shown constantly when I use any of the Spotify commands.
I have a premium Spotify account and I did not use the Spotify API for anything else.

**Comment by peduarte** [comment]
Thanks, will look into this. Do you have the Menu Bar Player activated by any chance?

**Comment by jonas-w** [comment]
Got the same issue today multiple times, and I have the menu bar player activated. Will deactivate it.

**Comment by peduarte** [comment]
Should have a fix soon 👍

**Comment by jonas-w** [comment]
Thanks, @peduarte! Would it be possible to have a config option that lets you use your own Spotify client ID?

**Comment by peduarte** [comment]
@jonas-w that's something we can consider for "power users"
