### ISSUE TITLE
[Hue] Can't control lights after last update

### ISSUE THREAD

**Issue by luishmcmoreno** [raycast/extensions#7400]
### Extension

https://www.raycast.com/pindab0ter/hue

#### Error:
```
Error: unknown hex color: #NaNNaNNaN

Hn:chroma.js:804:14

---
801:         // if _input.css? and rgb = _input.css hex
802:         //     return rgb
803: 
804:         throw new Error(("unknown hex color: "   hex))
```

### Steps To Reproduce

I don't know exactly the steps to reproduce but I suppose it's because I have smart plugs which is considered as lights by Hue but don't have any hex color control. I also have a smart switches inside walls connected to Hue. I'm not sure if it's related.

### Current Behaviour

When enter "Control Lights" command, we see this error:
![image](https://github.com/raycast/extensions/assets/775795/3cb57d50-a8a3-4553-87b2-0630ff85b1bf)

### Expected Behaviour

Access "Control Lights" command normally

**Comment by pindab0ter** [comment]
Could you fix the formatting and finish your sentence? I'll start looking into it in the meantime.

**Comment by pindab0ter** [comment]
Could you tell me more about when exactly this happens? Are you adjusting individual lights or groups? Are you changing the colour/brightness, or are you setting a scene? Please tell what steps you take to reach the error.
