### ISSUE TITLE
[Google Translate] Not working behind a proxy

### ISSUE THREAD

**Issue by reekystive** [raycast/extensions#7406]
### Extension

https://www.raycast.com/gebeto/translate

### Description

Google Translate Extension is not using system proxy, even "Use System Network Preferences" is enabled in Raycast Settings.

### Steps To Reproduce

1. Connect to a network that requires a proxy to connect to Google
2. Enable System Proxy in macOS System Settings
3. Enable "Use System Network Preferences" in Raycast Settings
4. Use Google Translate Extension

### Current Behaviour

Google Translate Extension is not using system proxy.

This extension is using `iamtraction/google-translate`, which is using `undici` as HTTP client to send requests. Maybe that library is not inspecting system proxy settings.

### Expected Behaviour

Google Translate Extension is using system proxy to communicate with Google.

**Comment by Auk513** [comment]
same problem
