### ISSUE TITLE
[Summarize YouTube Videos with AI] Would be great if we could ask questions

### ISSUE THREAD

**Issue by willhoag** [raycast/extensions#7417]
### Extension

https://www.raycast.com/iKasch/summarize-youtube-video-with-ai

### Description

It would be nice to subsequently prompt for more details after the summary. Sometimes the details received from the summary aren't exactly what you need. I was hoping to get the list that was presented in a video, but instead the summary gave me other details.

**Comment by iKasch** [comment]
@willhoag hey, sorry for the late updates to the extension, but there is a bigger one out just now. It should do exactly what you asked for. https://github.com/raycast/extensions/pull/15972
Hope you like it!
