### ISSUE TITLE
[Bear Notes] Ability to set defaults for `bn` (New Note) command

### ISSUE THREAD

**Issue by ohong** [raycast/extensions#7419]
### Extension

https://www.raycast.com/hmarr/bear

### Description

When I create a new Bear note with the `bn` Raycast command, I almost always want "Open Note" to be "In New Window" so I can work on it right away. However, the default is "Don't Open Note" so I need to spend the extra second (& mouse clicks) to adjust that option.

For the sake of quick capture, it would be amazing if we could set our own defaults here. Thx!

### Who will benefit from this feature?

People who want to quickly capture new notes in Bear in their preferred ways.

**Comment by juanbanchero** [comment]
Hi @ohong. Thanks for the ideas! 💡 I coded it and you can follow this feature in here > https://github.com/raycast/extensions/pull/7449

**Comment by juanbanchero** [comment]
This is already done, you can run `check for extensions update` command to update 😄

**Comment by juanbanchero** [comment]
@raycastbot close this issue
