### ISSUE TITLE
No translation into the selected language. [Summarize YouTube Videos with AI]

### ISSUE THREAD

**Issue by minisiowo** [raycast/extensions#7422]
### Extension

https://www.raycast.com/iKasch/summarize-youtube-video-with-ai

### Description

The extension does not take into account the selected language (in this case, Polish). Below, I provide a link to a video that is causing issues. I don't know if it's the fault of the extension or Raycast AI because OpenAI's ChatGPT performs very well on the website. 

Video link:
[https://www.youtube.com/watch?v=ax7f3JZJHSw](https://www.youtube.com/watch?v=ax7f3JZJHSw)

### Steps To Reproduce

1. Provide a link to the movie.
2. Wait for a response.

### Current Behaviour

Summary is in a completely different language than the one chosen.

### Expected Behaviour

Summary written in the chosen Polish language.

**Comment by iKasch** [comment]
@minisiowo hey, sorry for the late answer. There has been a bigger update to the extension which should make language detection more reliable. Hope it works for you.
