### ISSUE TITLE
access today page with keyboard shortcut[Craft] ...

### ISSUE THREAD

**Issue by kimtrinh** [raycast/extensions#7429]
### Extension

https://www.raycast.com/bgnfu7re/craftdocs

### Description

currently can only access today view by daily note then clicking today.  would like to go directly to today page on craft with keyboard

**Comment by kudrykv** [comment]
Hi @kimtrinh!

Are you talking about a separate command to set a Raycast shortcut?

**Comment by kimtrinh** [comment]
Yes I would like to have a shortcut directly to the craft today page

Is that possible?
________________________________

**Comment by kudrykv** [comment]
I need to make it a separate command first. As the closest remedy here and now, I suggest creating a shortcut for "Daily notes." Then, navigating to today's note would be a <your shortcut>, <enter> key combination.

**Comment by kudrykv** [comment]
Actually, at this time, I can't make the time to look into it. I'm sorry.
You can make a "longer" shortcut as I suggested before at the time.
