### ISSUE TITLE
[Kagi FastGPT] Request option to disable web_request

### ISSUE THREAD

**Issue by jcs-lambda** [raycast/extensions#7439]
### Extension

https://www.raycast.com/http.james/kagi-fastgpt

### Description

Kagi's FastGPT API has a boolean parameter `web_request`. When true, the FastGPT performs a web search, then analyzes the results to formulate its answer. When false, FastGPT generates an answer based on its training data.

The web_search request costs 10x as much as the non-web_search request. I am consistently getting better results with web_search disabled - with web_search I mostly get "there is not enough context to answer your question" responses. While running the same query without web_search gives reasonable, useful answers.

Please add a preference to control the web_search value.  
EDIT: Currently, web_search is hardcoded to `true` (line 19, ask.tsx). Adding a preference item and using that value in the call to `query` from ask.tsx works great in local testing for me.

### Who will benefit from this feature?

All users will benefit from this feature because it will make this extension useful and less expensive. If I continue paying for FastGPT queries that only return "need more context" answers, I will stop using the service or switch to another tool.

**Comment by httpjamesm** [comment]
Kagi has deprecated web_search and forces it to the enabled state due to financial unsustainability of the option.

**Comment by jcs-lambda** [comment]
Understood. Thanks for the quick response.

@raycastbot close this issue
