### ISSUE TITLE
[Pocket] ...

### ISSUE THREAD

**Issue by TransRapid** [raycast/extensions#7441]
### Extension

https://www.raycast.com/vimtor/pocket

### Description

Running this code does not work. Error 403 is received upon submitting the last snippet to get the access token.

### Steps To Reproduce

1. OS X Ventura
2. Terminal
3. Vivaldi or Safari
4. Terminal
5. 

### Current Behaviour

Fails to authorize.

### Expected Behaviour

Authorizes and generates access token.

**Comment by nivcoder** [comment]
I can confirm the same issue.

**Comment by TransRapid** [comment]
It seems the issue comes down to the format of the strings generated. No matter how you try to post it says it is wrong


It will submit but not send any access key back, then submitting it again I get error 403 which seems to indicate one of the original 2 strings is invalid, perhaps because it was already used once.

Maybe I need to wait longer.

**Comment by TransRapid** [comment]
> I can confirm the same issue.

What Terminal are you using? I also tried bash and had the same result.

**Comment by TransRapid** [comment]
> I can confirm the same issue.

What Terminal are you using? I also tried bash and had the same result.

**Comment by TransRapid** [comment]
Solved, the issue is as suspected, the Mac Terminal. I used a free tier of GCS to run the commands and it works perfectly fine. Not super happy with Ventura or ZSH shell especially. Run it from a different terminal or cloud shell and you will be fine, might even work downloading a mobile terminal app.

**Comment by TransRapid** [comment]
Solved, the issue is as suspected, the Mac Terminal. I used a free tier of GCS to run the commands and it works perfectly fine. Not super happy with Ventura or ZSH shell especially. Run these same commands from a different terminal or cloud shell and you will be fine, it might even work downloading a mobile terminal app.

Additionally you might try adjusting settings on Apple Terminal. If I have more time I can try the same later, and put a followup linked to this, but the issue with the extension itself is not really an issue.

@vimtor Closing this ticket, but maybe you have some feedback on what might be causing this issue in the built in Mac Terminal.

**Comment by nivcoder** [comment]
I was using iTerm / zsh. I'll try a different one, thanks!

**Comment by vimtor** [comment]
To be honest, I am a bit frustrated with Pocket. It started working, but then it suddenly stopped. They have a custom OAuth flow, so I can't use the built-in Raycast method. I'm a bit out of ideas for the extension :(

**Comment by TransRapid** [comment]
> To be honest, I am a bit frustrated with Pocket. It started working, but then it suddenly stopped. They have a custom OAuth flow, so I can't use the built-in Raycast method. I'm a bit out of ideas for the extension 😢 

Do you mean as far as an inline extension without having to use any external program? The extension works, but something weird happens when using zsh vs bash. It seems that one of the initial inputs is misinterpreted by Pocket API-and then produces a bad output and doesn't even know it's bad until you put in the access key generated from that and it doesn't add up properly.

**Comment by vimtor** [comment]
> 

I had a lot of improvements ready to be shipped, but since this wasn't working they didn't see the light.

https://github.com/raycast/extensions/pull/2991

Any ideas @pernielsentikaer?

**Comment by vimtor** [comment]
> > To be honest, I am a bit frustrated with Pocket. It started working, but then it suddenly stopped. They have a custom OAuth flow, so I can't use the built-in Raycast method. I'm a bit out of ideas for the extension 😢
> 
> Do you mean as far as an inline extension without having to use any external program? The extension works, but something weird happens when using zsh or bash on Ventura specifically. I imagine something more related to some Terminal settings. It seems that one of the initial inputs is misinterpreted by Pocket API-and then produces a bad output and doesn't even know it's bad until you put in the access key generated from that and it doesn't add up properly.
> 
> Working extension is super useful btw.

I had a lot of improvements ready to be shipped, but since this wasn't working they didn't see the light.

https://github.com/raycast/extensions/pull/2991

Any ideas @pernielsentikaer?

**Comment by xilopaint** [comment]
@TransRapid @vimtor I faced the same the same issue and managed to complete the auth flow by following [Pocket documentation](https://getpocket.com/developer/docs/authentication):

```shell
curl -X POST https://getpocket.com/v3/oauth/request \
-H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" \
-H "X-Accept: application/x-www-form-urlencoded" \
-d "consumer_key=YOUR_APP_CONSUMER_KEY&redirect_uri=pocketapp1234:authorizationFinished"
```

```shell
curl -X POST https://getpocket.com/v3/oauth/authorize \
-H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" \
-H "X-Accept: application/x-www-form-urlencoded" \
-d "consumer_key=YOUR_APP_CONSUMER_KEY&code= YOUR_REQUEST_TOKEN"
```

If this works for you guys the documentation should be changed.
