### ISSUE TITLE
[Bear Notes] Create note from search

### ISSUE THREAD

**Issue by rhazsolomon** [raycast/extensions#7448]
### Extension

https://www.raycast.com/hmarr/bear

### Description

If I search for a note, say "Tony Hawk", but that note does not exist, I'd like to have to option to create a note with the title, "Tony Hawk."

### Who will benefit from this feature?

Everyone.

**Comment by juanbanchero** [comment]
Hi @rhazsolomon. Thanks for the ideas! 💡  I coded it and you can follow this feature in here > https://github.com/raycast/extensions/pull/7449

**Comment by juanbanchero** [comment]
This is already done, you can run `check for extensions update` command to update 😄

**Comment by juanbanchero** [comment]
@raycastbot close this issue
