### ISSUE TITLE
[Spotify Player] Make song title scroll

### ISSUE THREAD

**Issue by nKumar2015** [raycast/extensions#7450]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Make song titles scroll across the menu bar if the title is longer than the set maximum chars to display.

### Who will benefit from this feature?

Anyone who wishes to have the name to be fully displayed while conserving menu bar space.

**Comment by peduarte** [comment]
Good idea. We currently don't have an API for this. I'd be hesitant to implement it using something such as `setInterval` since the menu bar commands are always running.
