### ISSUE TITLE
[YouTube Downloader] Audio format is downloading in mp4, not mp3

### ISSUE THREAD

**Issue by teziovsky** [raycast/extensions#7464]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

The `mp4` format in fact is Video format. When I choose the `Audio 128kbps` option I expect that the result file will have `mp3` extension rather than `mp4`, but without music video 🤔
What is interesting, when I choose the `Video 144-1080p` it will download the file with `mp4` extension too, but with the music video included 🤔

### Steps To Reproduce

1. Open extension
2. Copy music video like this https://www.youtube.com/watch?v=nHtX5Kh8sis
3. Paste into an extension
4. Choose a format - `Audio 128kps` (there should be `kbps` I think)
5. Download and look at the result

### Current Behaviour

Downloaded file has `mp4` extension instead of `mp3` 🤔

### Expected Behaviour

The downloaded file should have `mp3` extension 🥳

**Comment by teziovsky** [comment]
## Screencast 
1. Settings in the extension
<img width="1000" alt="youtube-downloader 2023-07-11 at 09 41 27" src="https://github.com/raycast/extensions/assets/36273653/18ecc96a-2808-49fb-b50a-91ee757eefaa">

2. The result file after the download
<img width="348" alt="Screenshot 2023-07-11 at 09 41 47" src="https://github.com/raycast/extensions/assets/36273653/2b57c5c1-9436-43d0-be2d-c1804a9fee8d">

I expected `.mp3` instead of `.mp4`. Eventually, it could be nice to give an opportunity to choose between `.mp4` and `.mp3`. Or maybe more types of extensions like `.aac` or something like that. I don't know if it's possible 🤔

**Comment by vimtor** [comment]
@teziovsky fix incoming!

Thanks for testing the extension so much, I hope you find it valuable :)
