### ISSUE TITLE
[TickTick] ...

### ISSUE THREAD

**Issue by sky02x** [raycast/extensions#7467]
### Extension

https://www.raycast.com/appest/ticktick

### Description

Inbox command not working

### Steps To Reproduce

Run 'Inbox' command

### Current Behaviour

<img width="805" alt="Screenshot 2023-07-11 at 10 46 55 PM" src="https://github.com/raycast/extensions/assets/108785851/8e3c2d97-40e6-4a4b-9c31-9d893765967a">

### Expected Behaviour

Shows ticktick inbox

**Comment by viduycheung** [comment]
Please ensure your TickTick macOS app is updated to the latest version and has incomplete tasks in your Inbox. @sy02x

**Comment by sky02x** [comment]
ah yes that fixed it, thanks!

**Comment by viduycheung** [comment]
@raycastbot close this issue
