### ISSUE TITLE
[TickTick] ...

### ISSUE THREAD

**Issue by sky02x** [raycast/extensions#7472]
### Extension

https://www.raycast.com/appest/ticktick

### Description

Allow marking tasks as 'done' in raycast itself instead of having to open the app

**Comment by viduycheung** [comment]
@sky02x Thanks for your feedback, we are consider to develop this feature and we will notify you when it is launched.

**Comment by viduycheung** [comment]
@sky02x  Hi, the complete task feature has been published to the store. (Require TickTick macOS app version 5.4.61 and the latest TickTick Raycast extension)

**Comment by viduycheung** [comment]
@raycastbot close this issue
