### ISSUE TITLE
[Spotify Player] Play liked songs with option to shuffle

### ISSUE THREAD

**Issue by homostellaris** [raycast/extensions#7473]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Currently I can't find a way to play my liked songs. I can search for individual liked songs but that will play the song in isolation rather than playing through all of them. Additionally I'd like the option to shuffle play whatever I'm about to choose.

### Who will benefit from this feature?

Anyone who regularly listens to their liked songs.

**Comment by bkeys818** [comment]
Here's my comment on a similar issue (#5996).

> Unforchantly, it's the Spotify API that doesn't allow for this.
> 
> See this [community post](https://community.spotify.com/t5/Spotify-for-Developers/Enable-play-back-of-the-quot-Liked-Songs-quot-playlist-through/m-p/4967889).

**Comment by homostellaris** [comment]
Thanks for the input @bkeys818 👋

The answer community suggests the [get user's saved tracks endpoint](https://developer.spotify.com/documentation/web-api/reference/get-users-saved-tracks) which looks like it would do what we want but would just have to deal with the pagination.

**Comment by homostellaris** [comment]
Ah yes you are right, I hadn't looked deeply at how it works but seems we'd need a liked songs 'context' to play otherwise we'd just have to add all songs to the queue which would be a pain as you say.

Probably better to just create playlists for what I would commonly like to play. Thanks for your help to understand, gonna close this.

**Comment by bkeys818** [comment]
@homostellaris
I made a tool that might help with this. It's still in beta, but I'd love another tester. Check out my [spotify-tools repo](https://github.com/bkeys818/spotify-tools).

**Comment by bkeys818** [comment]
@nightgolfer, You might just be onto something...
