### ISSUE TITLE
[WARP] Open directory command browsing doesn't work

### ISSUE THREAD

**Issue by fascox** [raycast/extensions#7474]
### Extension

https://www.raycast.com/warpdotdev/warp

### Description

Unable to find any directory with the open directory command, browse is always empty.

![Schermata 2023-07-12 alle 12 33 57](https://github.com/raycast/extensions/assets/700221/876485c9-9cfe-4602-880f-7b3df6ed46e2)

### Steps To Reproduce

1. select command
2. type few key to search folder

### Current Behaviour

browser list is empty

### Expected Behaviour

should populate the list with matching folders name

**Comment by joetannenbaum** [comment]
Internally, this command uses Spotlight's index to search for directories. Is Spotlight indexing the directory you're searching for?

**Comment by fascox** [comment]
yes and I also tried other directories too, including my home directory. same result. I also have Raycast full access to disk and file and folders in security and privacy tab in the settings.

![Schermata 2023-07-12 alle 17 22 26](https://github.com/raycast/extensions/assets/700221/70277bbf-1760-4576-b29a-558370ecd7a5)

**Comment by joetannenbaum** [comment]
Ok, thank you. And just to confirm, if you search within the Spotlight app itself, you get results?

![CleanShot 2023-07-12 at 12 32 21@2x](https://github.com/raycast/extensions/assets/2702148/d7abbda0-0ff1-4ef4-930a-b0d6c5be94b6)

**Comment by fascox** [comment]
Yes i confirm that from spotlight and Raycast built in search files command get results

![Schermata 2023-07-12 alle 19 41 48](https://github.com/raycast/extensions/assets/700221/49306b60-6bf4-4570-9318-6a225742777f)

**Comment by joetannenbaum** [comment]
@fascox ok, I'm going to try and improve the error messaging around this to see if we can get to the bottom of it.

**Comment by fascox** [comment]
> @fascox OK, I'm going to try and improve the error messaging around this to see if we can get to the bottom of it.

Any news regarding improvements to error messaging for detecting this issue?

**Comment by fcarboneras** [comment]
I have the same issue with this problem, it would be great if there is some news to this issue ? :)

**Comment by Goodosky** [comment]
I also have the same problem.

**Comment by bobvbright** [comment]
Same here
