### ISSUE TITLE
[Pomodoro] ... menu bar timer does not update

### ISSUE THREAD

**Issue by theomjones** [raycast/extensions#7475]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

Menu bar timer does not update unless it is interacted with (clicked on)

### Steps To Reproduce

1. Enable menu bar item
2. Start a timer
3. See that it does not update

**Comment by pernielsentikaer** [comment]
It's only possible to update the menubar every 10th seconds as it is right now, 1 second won't work
