### ISSUE TITLE
[Menubar Weather] Unfocused Monitor Display Glitch

### ISSUE THREAD

**Issue by rjhewitt3** [raycast/extensions#7481]
### Extension

https://www.raycast.com/koinzhang/menubar-weather

### Description

On unfocused monitors the text within the menu bar widget appears white, rather than dimmed like all other menu bar icons/text.
<img width="229" alt="Screenshot 2023-07-12 at 12 20 14@2x" src="https://github.com/raycast/extensions/assets/6742828/70de4593-d8cf-4aeb-8c00-fdb4031d117d">

### Steps To Reproduce

Use multiple monitors, look at menubar on unfocused monitor.

**Comment by rjhewitt3** [comment]
@sxn Any update on this issue?

**Comment by rjhewitt3** [comment]
@sxn, interestingly I've had SF Symbols selected for quite some time and the icons never changed for me—and the problem has persisted. 🤔

**Comment by sxn** [comment]
should be fixed in today's release (**v1.65.0**), so I'll close this ticket 🎉

**Comment by rjhewitt3** [comment]
Thanks @sxn! 👏🏻
