### ISSUE TITLE
[Pomodoro] ... Add ability to hide menu-bar icon while not in use.

### ISSUE THREAD

**Issue by andrewtimosca** [raycast/extensions#7482]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

I like having the menu-bar icon/time active while I'm using the timer, but I'd like to be able to have it hidden while I'm not using it.

**Comment by callumgare** [comment]
I've found a way to do this: https://github.com/raycast/extensions/issues/4615#issuecomment-1963122626
