### ISSUE TITLE
[Obsidian] All the commands when trying to fetch my notes do not work

### ISSUE THREAD

**Issue by aureusx** [raycast/extensions#7485]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

The commands listed in "steps to reproduce" (so all commands interacting with my list of notes) do simply not run. I get "Something went wrong". Other commands, like appending to the daily notes, work.

#### Error:
```
TypeError: t.tags.split is not a function

yi:NoteListObsidian.tsx:18:10

---
15:   bookmarked: boolean
```

### Steps To Reproduce

Whenever searching for notes (if it is the whole vault, bookmarked notes or when I'm trying to open a random note), I get the error.

Must have something to do with the tags in my vault...? I'm mostly using tags inside YAML, both in list and in array notation.

I'm using Obsidian v1.3.5 and I also tried un- and reinstalling the plugin, so I should be up to date.

It doesn't matter if I enter anything for the "Note" or "Tag" fields.

**Comment by KevinBatdorf** [comment]
I'll see if I can reproduce it to find the underlining cause, but if not I can address the crashing at least. Thanks for reporting it.

**Comment by KevinBatdorf** [comment]
I can't reproduce it but here are some notes on what I found (note I'm not the original author of this plugin so I'm debugging it):

It parses the yaml and looks for `tags`. It checks whether the tags property is an array, and if not, it treats it as a string and converts it into an array. Based on the error message you reported, it's assuming the tags are a string, but they are not. So it's some other primitive or object. 

Do you have any idea what tags of yours might be the issue? I can squash the error by failing gracefully, but if you can show me how you're using it then I can add support too.

**Comment by aureusx** [comment]
Thanks! That already helped. I just logged all my pages' tags and found out that one of my templates renders the tag as an object. It's a QuickAdd template that gets the tag from a script of mine with {{VALUE:tag}}.

I excluded my templates folder from the plugin's index and now everything works as expected.

I'd still say that a fix in the plugin so it doesn't simply crash would be helpful, but this has solved it for me!

**Comment by marcjulianschwarz** [comment]
@KevinBatdorf this could be related with https://github.com/KevinBatdorf/obsidian-raycast/issues/32 

I think the current YAML parsing only works with strings.

**Comment by KevinBatdorf** [comment]
@marcjulianschwarz Seems you added support for arrays about a year ago here https://github.com/KevinBatdorf/obsidian-raycast/blob/main/src/utils/yaml.tsx#L110

@aureusx thanks for the confirmation! I'll open a PR to prevent it from crashing.

**Comment by marcjulianschwarz** [comment]
Oh yeah, I meant strings and arrays of strings but not arrays of objects. But I saw you already fixed it :)
