### ISSUE TITLE
Create a new note if no results

### ISSUE THREAD

**Issue by nadavmoreno** [raycast/extensions#7492]
### Extension

https://www.raycast.com/hmarr/bear

### Description

If searching for a note is getting no results, add the abilty to create this new note without leaving the "Search Notes" screen

### Who will benefit from this feature?

everyone

**Comment by juanbanchero** [comment]
This is already done in the last update, you can run `check for extensions update` 😄

**Comment by juanbanchero** [comment]
@raycastbot close this issue
