### ISSUE TITLE
[Extension Bug] Clash rule edit fail

### ISSUE THREAD

**Issue by l782993610** [raycast/extensions#750]
# Extension – [Title](https://github.com/raycast/extensions/tree/main/extensions/*)

Author:  Amasdeus

## Steps To Reproduce

1. Start app clash
2. turn to rules

## The current behavior
it collapsed
![image](https://user-images.githubusercontent.com/59809602/151441514-3d6aed1a-3a1e-44f3-b4a4-cd5c288b9121.png)
and error is:

> Error: Worker terminated due to reaching memory limit: JS heap out of memory
> 
> __node_internal_captureLargerStackTrace:errors:464:5
> NodeError:errors:371:5
> Worker.[kOnExit]:worker:279:26
> Worker.<computed>.onexit:worker:201:20

## The expected behavior
Show the proxie rules
### Raycast version
Version: 1.27.0

**Comment by l782993610** [comment]
It seems that I have too much rules, is it possible to filter rules?

**Comment by ciiiii** [comment]
@l782993610 how many rules you have?

**Comment by ciiiii** [comment]
My Clash has almost 10000 rules, you can count yours by this command.
```
➜ curl localhost:9191/rules -s | jq '.rules | length'
9353
```
