### ISSUE TITLE
[Authy] 1password

### ISSUE THREAD

**Issue by nicoandmee** [raycast/extensions#7502]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

Hi, thanks for making this. It works! But for most accounts I use TOTP / 2FA in addition to password. Therefore, it would be convenient to add an option to do this in the context menu.

### Who will benefit from this feature?

Anyone who uses 2FA!

**Comment by gdsmith** [comment]
There is already a 1password extension. Can you just explain a bit more about what changes you are suggesting here?

**Comment by guga4ka** [comment]
As i understed @nicoandmee is wan't addition view with password, i've worked on in previously but because of the lack of time i drop it. Will look on code and see what i can do.
