### ISSUE TITLE
[Obsidian] Menu Bar stopped working

### ISSUE THREAD

**Issue by GeoJunkie** [raycast/extensions#7504]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

#### Error:
```
SyntaxError: Unexpected end of JSON input

Ef:obsidianMenuBar.tsx:8:33

---
 5: import { getObsidianTarget, ObsidianTargetType, useObsidianVaults, vaultPluginCheck } from "./utils/utils"

### Steps To Reproduce

1. Activate the Obsidian Menu Bar in settings
2. See the exclamation point on the menu bar
3. Click it and see the error

### Current Behaviour

This was working until this morning. Now it won't work at all.

This is what it looks like:
![CleanShot 2023-07-14 at 10 56 06@2x](https://github.com/raycast/extensions/assets/7596032/4c61fccf-ac71-471f-b00d-f2747870f7dc)
<img width="772" alt="CleanShot 2023-07-14 at 10 57 08@2x" src="https://github.com/raycast/extensions/assets/7596032/c6c5d2ba-f2c0-41b8-8a29-3dbe2ab2cbce">

Tried reloading, restarting Raycast, deactivating and reactivating the extension. It still won't work.

### Expected Behaviour

It should continue working as before

**Comment by KevinBatdorf** [comment]
The error is suggesting that data is malformed somehow. It might be hard for me to debug it without more information. 

> 5: import { getObsidianTarget, ObsidianTargetType, useObsidianVaults, vaultPluginCheck } from "./utils/utils"

Could there be a copy/paste issue sharing the stack trace? This seems incomplete.

Maybe just clear the extension cache completely from the Raycast action panel? It won't delete anything in your vault.

If that doesn't work, share the stack trace or more of the error. I can walk you through debugging it too (clone, install, build etc) if you're interested.

**Comment by GeoJunkie** [comment]
> The error is suggesting that data is malformed somehow. It might be hard for me to debug it without more information.
> 
> > 5: import { getObsidianTarget, ObsidianTargetType, useObsidianVaults, vaultPluginCheck } from "./utils/utils"
> 
> Could there be a copy/paste issue sharing the stack trace? This seems incomplete.
> 
> Maybe just clear the extension cache completely from the Raycast action panel? It won't delete anything in your vault.
> 
> If that doesn't work, share the stack trace or more of the error. I can walk you through debugging it too (clone, install, build etc) if you're interested.

It does look like there was an issue. I used the "Report Bug" option which I thought prefilled the full error, but apparently it doesn't. Here's the output from choocing "Copy Error"

```
SyntaxError: Unexpected end of JSON input

Ef:obsidianMenuBar.tsx:8:33

---
 5: import { getObsidianTarget, ObsidianTargetType, useObsidianVaults, vaultPluginCheck } from "./utils/utils";
 6: 
 7: function BookmarkedNotesList(props: { vault: Vault }) {
 8:   const [notes] = useNotes(props.vault, true);
 9:   return (
10:     <MenuBarExtra.Submenu title={props.vault.name} key={props.vault.path + "Bookmarked Notes"}>
11:       {notes.map((note) => (
---

    at ray-menu-bar-extra-submenu
gs:index.js:20:27030
Tf:obsidianMenuBar.js:134:10573
```

I'm happy to help with debugging, too. I haven't worked directly with extension coding, but it's something I've been interested in learning :)

**Comment by GeoJunkie** [comment]
Given the updated stack trace, I tested using the Bookmarked Notes command and it worked OK. I don't have any notes bookmarked, though, so it only went through the create a new note path.

**Comment by GeoJunkie** [comment]
@KevinBatdorf I was able to stop the error by filling in the "Path to Vault" setting in the main extension settings. Interestingly, every other command seems to be working properly and pulling the vault info from Obsidian itself. This one was working until a couple days ago, too.

**Comment by KevinBatdorf** [comment]
Thanks for that extra info. If the "Path to Vault" field is empty it will attempt to load the obsidian.json file from `${homedir()}/Library/Application Support/obsidian/obsidian.json` and use the vault info from there.

For example
```json
{"vaults":{"fc7a372760a58ff2":{"path":"/Users/kevin/code/brain","ts":1683469744872,"open":true}}}
```

Can you check if that file is corrupt or has something different?

**Comment by GeoJunkie** [comment]
That looks correct:
```json
{
    "vaults": {
        "fa9d2a628d52e39b": {
            "path": "/Users/taco/Second Brain",
            "ts": 1689346725328
        },
        "df499aacf486501b": {
            "path": "/Users/taco/Digital Garden",
            "ts": 1689346814260,
            "open": true
        },
        "14c92d8a4debe957": {
            "path": "/Users/taco/Dropbox/Obsidian/Developer Apprenticeship",
            "ts": 1688128480640
        },
        "fd8b033ab8b71e8e": {
            "path": "/Users/taco/Dropbox/Second Brain v0.1",
            "ts": 1688128544861
        }
    }
}
```

**Comment by KevinBatdorf** [comment]
Sorry for not following up sooner. I think I may have identified the issue. If the cache is undefined or null, the extension [falls back to](https://github.com/KevinBatdorf/obsidian-raycast/blob/main/src/utils/data/cache.tsx#L80) an empty string which would give that error. 

I'll update that code, but since it works for you this way then you can leave things be anyway.
