### ISSUE TITLE
[ChatGPT] An error occurred after using the API Endpoint.

### ISSUE THREAD

**Issue by cbingb666** [raycast/extensions#7506]
### Extension

https://www.raycast.com/abielzulio/chatgpt

#### Error:
```
Error: Request failed with status code 401

gt.exports:createError.js:16:14

---
13:  * @returns {Error} The created error.
14:  */
15: module.exports = function createError(message, config, code, request, response) {
16:   var error = new Error(message)

### Steps To Reproduce

1. Set API KEY
2. Enabled API Endpoint and filled in
3. Enter "ask" and press Enter.
4. An error message appears: "Something went wrong You can try reloading, or report the error to the extension developer, by copying the log from the Action Panel #f K”

I suspect that the API Endpoint supplier is unable to provide the models list API, or other interfaces are not supported.

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by shichongrui** [comment]
Can anyone tell me how to stop being pinged on these issues?

**Comment by Nauxscript** [comment]
> Can anyone tell me how to stop being pinged on these issues?

Maybe you need to open a new issue to ask the official maintainers😂

btw I have the same question😅

**Comment by cbingb666** [comment]
It has been solved, because after adding API Endpoint, some API Endpoint addresses need to add v1 after the link, e.g. https://xxx.xxx.com/api replaced by https://xxx.xxx.com/api/v1

**Comment by cbingb666** [comment]
It has been solved, because after adding API Endpoint, some API Endpoint addresses need to add v1 after the link, e.g. https://xxx.xxx.com/api replaced by https://xxx.xxx.com/api/v1.
这个问题已经解决了，因为在添加 API 端点后，一些 API 端点地址需要在链接后添加 v1，例如 https://xxx.xxx.com/api 替换为 https://xxx.xxx.com/api/v1。

**Comment by cbingb666** [comment]
It has been solved, because after adding API Endpoint, some API Endpoint addresses need to add v1 after the link, e.g. https://xxx.xxx.com/api replaced by https://xxx.xxx.com/api/v1.
