### ISSUE TITLE
[Keyboard Shortcut Sequences] ...

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#7509]
### Extension

https://www.raycast.com/HelloImSteven/keyboard-shortcut-sequences

### Description

It triggers command modifier instead of control

### Steps To Reproduce

Switching from Arc browser to Obsidian
Then apply control+c shortcut

### Current Behaviour

in triggers command+c

### Expected Behaviour

to trigger control+c

**Comment by SKaplanOfficial** [comment]
Hi, I'm not able to recreate this. It correctly triggers control+c. Can you share the JSON of the sequence? (command+j from the 'Run Shortcut Sequence' command)

**Comment by romanskorobagatko** [comment]
{"name":"Obsidian ReadItLater","description":"","icon":"add-person-16","shortcuts":[{"keystrokes":"l","modifiers":["command down"]},{"keystrokes":"c","modifiers":["command down"]},{"keystrokes":"o","modifiers":["command down","control down","option down","shift down"]},{"keystrokes":"c","modifiers":["control down"]}]}
