### ISSUE TITLE
[Bear Notes] Fuzzy search doesn't work

### ISSUE THREAD

**Issue by nadavmoreno** [raycast/extensions#7510]
### Extension

https://www.raycast.com/hmarr/bear

### Description

It looks like the extension is not implementing the fuzzy search feature on the native Mac app

### Steps To Reproduce

1. Macos 
2. Raycast v1.55.2
3. Bear v2.0.1
4. Bear notes extension
5. Create a note with the title -  "testing fuzzy search" 
6. Use Bear command "Note List Search..." and search for "testing search". you will get the note created on step 5
7. Use Raycast "Search Notes" command and search for "testing search". you will get no results

### Current Behaviour

No results 

### Expected Behaviour

Show relevant results

**Comment by hmarr** [comment]
See https://github.com/raycast/extensions/issues/2710
