### ISSUE TITLE
[Spotify Player] error

### ISSUE THREAD

**Issue by abcdefghijklmnopqrsteve** [raycast/extensions#7511]
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```
Run Error: Command terminated, code: 2 (Unhandled Extension Rejection)


```

### Steps To Reproduce

I have no idea

### Current Behaviour

The menu bar displaces the error sign, and keep asking to connect with Spotify even tho I already did multiple time.

**Comment by peduarte** [comment]
Hey, thanks for reporting this. Could be an auth issue post-update. I need to investigate. Meanwhile, could you please try uninstalling the extension and re-installing it? Sorry about that!

**Comment by oleksii-ivanov** [comment]
happened to me too, restarting raycast and deactivating spotify menu bar didn't help but uninstalling helped . thanks

**Comment by tryit05** [comment]
i have the problem. it required me to sign in but after signing in it still could not connect and required to sign in again
