### ISSUE TITLE
[Microsoft Edge] ...

### ISSUE THREAD

**Issue by vae999** [raycast/extensions#7525]
### Extension

https://www.raycast.com/KartikKumarSahoo/microsoft-edge

### Description

I After binding the shortcut key, it is often difficult to open the links when using the shortcut key to run “search Bookmarks” for searching bookmarks, pressing enter.

### Steps To Reproduce

exec "command + shift + e" (my config)

enter "ttt" after select one bookmark ,enter

Unable to open edge and jump link

**Comment by KartikKumarSahoo** [comment]
Thanks for reporting the issue. This should be fixed by https://github.com/raycast/extensions/pull/7526 PR.

**Comment by vae999** [comment]
This issue has been fixed

Thank you very much😊
