### ISSUE TITLE
Authy: Adding new account doesn't add it to "Search token" command

### ISSUE THREAD

**Issue by vfonic** [raycast/extensions#753]
# Extension – [Authy](https://github.com/raycast/extensions/tree/main/extensions/authy)
Author: @guga4ka 

## Description

I've successfully installed and set up the Authy extension for Raycast.
I've since added two new accounts to my Authy account.
I've added the accounts through Authy app on my phone.
The added accounts appeared immediately on my desktop app (they got synced/backed up successfully).

However, Authy Raycast extension doesn't see them when I search for them using "Search Token" Command.
I tried restarting the computer and also restarted Raycast several times. I don't know how to instruct Authy extension to "refetch" the list of available OTP passwords.

## Steps To Reproduce

1. Install Authy extension
2. Add new OTP password to Authy account
3. Use "Search Token" Command to search for the newly added OTP account in Authy

## The current behavior

The extension cannot find a new token.

## The expected behavior

The extension finds a new token.

### Raycast version
Version: 1.27.0

**Comment by guga4ka** [comment]
Have you tried sync action `cmd + r`?
<img width="862" alt="image" src="https://user-images.githubusercontent.com/13866979/151510549-8ae963c5-b6a7-45b3-9456-2ea4b7159095.png">

**Comment by vfonic** [comment]
That worked like a charm! Thanks! :)

Do you think there's some way we could make this more visible for the end users such as myself who might have missed this action in more actions? (I'm a new Raycast user so, even though I knew about the actions, I didn't think that this functionality might be there). Would it make sense to add a "Sync" button (or checkbox) in preferences?

**Comment by guga4ka** [comment]
The single reason why I didn't so synchronization automatically is a chance to be banned/rate limited by authy api. I guess I can describe it somewhere in the readme, but not sure if someone is reading it. Regarding separate command to refresh the list, i guess it might be overengineering. Basically, `cmd+r` is a common pattern to refresh/pull again a data f.e. Bitwarden extension implements it's in the same way

**Comment by vfonic** [comment]
Hmmmm, is Authy API rate-limiting based for the whole extension, across all Raycast users or it's per-user (per-installation)? If it's per-installation, you could issue a request when user "enters the Command". I'm not sure what's the correct lingo here, but basically when user selects "Select Token" command and starts typing the search term.

How often/how fast would user be able to keep selecting this command so that you get rate-limited by the API? I'd assume that user would, in worst case scenario, select the command at most once per second, probably once every half an hour or so (when user is about to login to some site).

Maybe I'm just not very familiar with Raycast and how its extensions work or where I should search for a certain functionality.
But, to me, if I'm asked:
> How would you re-sync your Authy list of sites?

I'd never say: I'd first go to Search Token and then...

I looked at all the other places I could think of:
1. Raycast preferences 
  a. I tried changing any of the preferences for the extension
2. I tried to see if there's some other Authy extension command I could use

That's my $0.02. Take care. :)

**Comment by guga4ka** [comment]
>Hmmmm, is Authy API rate-limiting based for the whole extension, across all Raycast users or it's per-user (per-installation)? If it's per-installation, you could issue a request when user "enters the Command". I'm not sure what's the correct lingo here, but basically when user selects "Select Token" command and starts typing the search term.
A single user would be rate-limited.

It isn't so quick to extract data from authy api and do it each time when a user enters to command -- bad idea. Also adding a new 2fa token isn't so frequent event. I guess it better do it on-demand. I will ask a community, what's the best way to do it. Thanks for your ticket, cheers.
