### ISSUE TITLE
[Unsplash] No option to choose desktop 

### ISSUE THREAD

**Issue by lemomar** [raycast/extensions#7531]
### Extension

https://www.raycast.com/eggsy/unsplash

### Description

Hi there!
I just noticed that there is no option to choose the affected Desktop in the settings anymore.

### Steps To Reproduce

1. Open Extension settings
2. Go to Unsplash settings

### Current Behaviour

There is no option to choose a desktop, commands target all desktops by default instead

**Comment by lemomar** [comment]
Hey @jackmsvaughan,

Thank you for the issue, I'd like to point out that the feature you requested already exists under extension settings which you can find by simply pressing `Cmd` + `Option` + `,` while hovering any of the commands from Unsplash; then you'll simply scroll down through the list on the right and find the option "Apply Wallpaper To"... Changing that setting to "Every Desktop" should help you get what you want!

<img width="303" alt="image" src="https://user-images.githubusercontent.com/13917975/222698030-6b0a50cf-f59f-467f-aa24-86f685087193.png">

Let me know if there's anything else, and please react/respond so I can close the issue! I'm not sure if the setting works since I don't have a second monitor installed, this will help me fix it if it wasn't working! Thanks.

_Originally posted by @eggsy in https://github.com/raycast/extensions/issues/5116#issuecomment-1453314107_

**Comment by lemomar** [comment]
I've found [this comment](https://github.com/raycast/extensions/issues/5116#issuecomment-1453314107), referencing the setting

**Comment by lemomar** [comment]
Tu @eggsy, thanks for the quick answer!
Is the setting saved for the scheduled wallpaper change too?

**Comment by eggsy** [comment]
Just checked the code and didn't see any related changes to that setting. Seems like that setting wasn't utilized in the background wallpaper change. I think that way it defaulted to use the current monitor but I changed it to apply to all monitors. Changing only one monitor's background didn't seem like a use case at that moment but seems like you prefer it that way. I will add the setting back when I have time 🙏
