### ISSUE TITLE
[cURL] Add custom headers

### ISSUE THREAD

**Issue by adisidev** [raycast/extensions#7539]
### Extension

https://www.raycast.com/jonathangiardino/curl

### Description

Currently, we can only choose headers from the pre-determined list that CURL gives us. However, often custom web applications have custom headers. Thus, we should allow the `key` and `value` of each header to be customisable.

Thank you for your work @jonathangiardino  

If permitted, I'd be happy to help implement this feature.

### Who will benefit from this feature?

Those using cURL for web development!

**Comment by jonathangiardino** [comment]
@adisidev 

Sure, go ahead! 
Please feel free to contribute!😊
