### ISSUE TITLE
[LastPass Credentials Search] Hide/show password while searching

### ISSUE THREAD

**Issue by jjmss** [raycast/extensions#7541]
### Extension

https://www.raycast.com/alex-popov-tech/lastpass

### Description

At this time, if you search for a account all the account details are shown. And yes, its nice to see the details in order to see what the login details is and compare them if there is multiple. However, siting in a public area and searching for a specific account and displaying all the details is abit risky and uncomfortable for some.

Having a option when you install the extension (example below the "Refresh Rate" option) to always hide/show the password would be nice. Alternatively having a option to press down a key to display the password before pasting it, like holding down "control + shift" or "control + command" changes the password from ********* to "the actual password".

### Who will benefit from this feature?

I would assume users using this extension in public places or in a open area with other people around them may benefit with this feature. As this would improve the privacy of the user using the extension when not sitting alone.

**Comment by alex-popov-tech** [comment]
hello @jjmss 
thanks for posting this, i will try to implement new option tomorrow

**Comment by alex-popov-tech** [comment]
hey again @jjmss 

sorry for delay, pr is there.

I've added new preference to make passwords be hidden/shown everywhere by default, as well as action to toggle this setting while searching ( like if you want them always be hidden, but before pasting you want to quickly make sure its the right one ).

Please confirm it covers your needs, thank you for patience <3

**Comment by jjmss** [comment]
Yes this sounds good :) as long as I'm able to use the extension without leaking / showing the password by accident I'm happy ;)

**Comment by jjmss** [comment]
Looks an works as expected! Thanks :)

**Comment by alex-popov-tech** [comment]
@raycastbot close this issue
