### ISSUE TITLE
[Jira] Add shortcut to invoke command Create Issue

### ISSUE THREAD

**Issue by teziovsky** [raycast/extensions#7542]
### Extension

https://www.raycast.com/raycast/jira

### Description

Add shortcut to invoke command Create Issue from list of issues for example with `⌘ + N`. There will be a faster way to create new issues 🤔

### Who will benefit from this feature?

I hope all of users 😎

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by thomaslombart** [comment]
Here's our guide about contributing to extensions: [Contribute to an extension](https://developers.raycast.com/basics/contribute-to-an-extension)
