### ISSUE TITLE
[Jira] Ability to filter issues by Project

### ISSUE THREAD

**Issue by teziovsky** [raycast/extensions#7543]
### Extension

https://www.raycast.com/raycast/jira

### Description

It may be a good improvement when users select from which projects want to see tasks. The all projects will be one of the options for sure!

### Who will benefit from this feature?

I hope all of users 😎

**Comment by thomaslombart** [comment]
Thank you for the feature request. In which command would this be added? `Search Issues`?

**Comment by teziovsky** [comment]
I think it could be in every command that has a list of issues 🤔 It would be great to filter the list by all projects or by the specific project. Then you have a quick preview of what is to be done in a given project. What do you think?

**Comment by thomaslombart** [comment]
It could be something yes, apart from `My Filters` who filters the list by Jira filters.
