### ISSUE TITLE
[Library Genesis] Add download keyboard shorcut (CMD+D)

### ISSUE THREAD

**Issue by matijaoe** [raycast/extensions#7551]
### Extension

https://www.raycast.com/yz3440/library-genesis

### Description

Add download keyboard shortcut, perhaps CMD+D

### Who will benefit from this feature?

Everyone who wants a one-click download

**Comment by yz3440** [comment]
@matijaoe Currently `return` is the shortcut for "Download Book". Can you clarify the context where a user might want to use an additional shortcut?

![CleanShot 2023-07-18 at 11 58 47](https://github.com/raycast/extensions/assets/24559576/42533324-630b-4739-bcab-3855abe3c273)

**Comment by matijaoe** [comment]
My bad, only after your comment I decided to check the extension settings, and sure enough there is an option to pick the primary action. Switched to Download book, all good now!

Sorry for inconvenience, and thank you for your awesome extension 🙏🏻
