### ISSUE TITLE
git clone https://github.com/raycast/extensions takes too long

### ISSUE THREAD

**Issue by schwa** [raycast/extensions#7556]
### Description

I've got a pull request I want to contribute back to Raycast andI've been cloning a fork of https://github.com/raycast/extensions for the last 25 minutes and it's only 26% done.

Equally; creating a Codespace is a massive time sink and grinds to a halt.

Having such a huge repo is really massive barrier to contributing back to the project

**Comment by skoch13** [comment]
As far as I understand it the current approach would be the following: instead of cloning the whole repo, one should execute the 'Fork Extension' command towards an application in question and contribute as described [here](https://developers.raycast.com/basics/contribute-to-an-extension).

**Comment by mathieudutour** [comment]
Exactly, we have tools to work around that
