### ISSUE TITLE
So many hardcoded paths to /Applications/<appname>

### ISSUE THREAD

**Issue by schwa** [raycast/extensions#7557]
### Description

A quick search of the source code via https://github.com/search?q=repo%3Araycast%2Fextensions%20%22%2FApplications%2F%22&type=code shows that there are many many hard coded paths to apps within /Applications. On macOS users are free to move apps anywhere and there are good APIs to find a user's apps without assuming they're in that directory.

All these Raycast extensions are broken for users who do not store all their 3rd apps in /Applications

**Comment by mathieudutour** [comment]
You're right, what would be your recommendations? Everybody is free to write extensions however they want

**Comment by schwa** [comment]
Raycast devs should provide functionality that uses launch services and/or other apis to allow authors to find apps by more robust and reliable methods (i.e. bundle identifiers). Even the humble `open` command line tool has a `-b` option to open an app by bundle id.

Raycast should also discourage the use of hard coded paths to apps in their documentation and/or sample code.

This issue severely limits the functionality of Raycast for users.

Many tools that allow users to install apps (e.g. homebrew) allow the user to customise install locations.

**Comment by schwa** [comment]
Oh and raycast could also go through existing extensions and fix them up once new apis are in place. Raycast is a for-profit company and benefiting from these extensions working well for everyone.

**Comment by mathieudutour** [comment]
We already provide some utilities to get applications: https://developers.raycast.com/api-reference/utilities#getapplications

While Raycast benefits from the extensions, we don't have the capacity to fix all the bugs. The whole point of the extensions being open source is that the community can improve them as they see fit.

**Comment by mathieudutour** [comment]
I added an example about getting an application by its bundle id: https://github.com/raycast/extensions/commit/29fbbb5311527b82861cdddb00fcac96090889a3

Feel free to open a PR if you have a suggestion on how to improve the docs.

> Raycast at the end of the day, is profiting from this more than any individual random open source committers are

Raycast isn't profitable at the moment so I hope you can understand that we have to keep our efforts focused.

> relying on the open source community to do all the work is equally unviable

I don't think anybody in the community would think that.
