### ISSUE TITLE
[Country Lookup] ...

### ISSUE THREAD

**Issue by mattouzalem** [raycast/extensions#7574]
### Extension

https://www.raycast.com/pernielsentikaer/country-lookup

### Description

Hey,

How about adding the following information to the country lookup extension:
- Country alpha3 code?
- Country VAT rate (super helpful in the EU)?

Thanks for your feedback!

**Comment by mattouzalem** [comment]
Hey Per,


Thanks for coming back to me on that!
I believe that the feed that you're using does have this data, it's just that it's labelled as "cca3".


Do you think you could update the extension, please?


Thanks a lot!


Kind regards,
Matthieu

--- original message ---
On July 25, 2023 at 11:21 AM GMT+2 ***@***.*** wrote:



Country alpha3 code should be doable to add, but the feed I'm using (see example country) does not have this data 😞

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you authored the thread.Message ID: ***@***.***>
--- end of original message ---

**Comment by pernielsentikaer** [comment]
cca3 is easy, VAT rate is not possible

**Comment by mattouzalem** [comment]
Amazing, thanks Per!


And no worries about VAT.


Have a nice day!
Matthieu

--- original message ---
On July 26, 2023 at 7:42 AM GMT+2 ***@***.*** wrote:



Closed #7574 as completed via #7653.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you authored the thread.Message ID: ***@***.***>
--- end of original message ---

**Comment by pernielsentikaer** [comment]
You're welome 🙂
