### ISSUE TITLE
Ability to reschedule task from Raycast [Reclaim] ...

### ISSUE THREAD

**Issue by kwadge** [raycast/extensions#7584]
### Extension

https://www.raycast.com/reclaim-ai/reclaim-ai

### Description

I spend a lot of time rescheduling tasks I cannot get to at the time and it would be amazing to be able to do that from the Raycast Menu bar. Click a Task, and alongside Start/Complete, Reschedule would be great. Thanks!

### Who will benefit from this feature?

All users!

**Comment by webergnr** [comment]
@kwadge Thanks for your feedback! This in now in our raycast backlog, and we will work on that soon.

**Comment by maximilianzuern** [comment]
I have made a pull request #8203 few weeks ago that allows you to reschedule your tasks via the `My Calendar` command. This way, you can easily view your events in a calendar format and reschedule events from the same command.

This feature is not exactly what you requested, but I hope it will still be helpful for you.

**Comment by kwadge** [comment]
Thanks for implementing that feature!! I really appreciate you listening to
your users and making useful changes!!

**Comment by maximilianzuern** [comment]
@raycastbot close this issue
