### ISSUE TITLE
[GitHub] Saved searches/advanced search

### ISSUE THREAD

**Issue by sebdanielsson** [raycast/extensions#7601]
### Extension

https://www.raycast.com/raycast/github

### Description

I would like to get a list of all open issues in all of my own repositories.

### Who will benefit from this feature?

People with lots of repositories that is rarely checked on.

### Anything else?

Currently I'm getting the results with advanced search. Should be possible to to the same with the GitHub API?

https://github.com/search?q=user%3Asebdanielsson+-label%3Adashboard+state%3Aopen&type=issues&ref=advsearch

Or you could just enter this into the search field:
user:sebdanielsson -label:dashboard state:open

Where "user" is the owner of all repositories to be searched, "-label" will exclude issues with the tag chosen tag, "state" will let you choose if you only want issues that is open, closed or both.

**Comment by thomaslombart** [comment]
I'm not sure I got your feature request. Did you mean you want to have a way to access your favorite search from the `Search Issues` command?

**Comment by sebdanielsson** [comment]
Yes. Support for all advanced searches would be the most flexible but my use case but for me it would primarily be to get a list of all open issues on my own repositories.

**Comment by sebdanielsson** [comment]
That only shows issues that's either assigned to me or mentioning me. I guess it could work if I added a bot to all of my repos that automatically assign me to every issue on creation but that seems like much work for this one feature.

**Comment by thomaslombart** [comment]
What if you were able to create a quick link from the `Search Issues` command which would allow you to open it with the search text pre-filled?

**Comment by sebdanielsson** [comment]
Yeah that would be perfect!😃

**Comment by thomaslombart** [comment]
Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by sebdanielsson** [comment]
I'm a pretty novice developer but I would happily give it a try!😃
