### ISSUE TITLE
[Warp] WarpPreview commands not working with Raycast v1.55.2

### ISSUE THREAD

**Issue by ryan6416** [raycast/extensions#7603]
### Extension

https://www.raycast.com/warpdotdev/warp

### Description

I’m using the WarpPreview version instead of the stable version of Warp, and it seems that the commands (Open Warp tabs and windows, Open Launch Configurations) are only for the stable version of Warp. I’m currently on Raycast v1.55.2.

### Steps To Reproduce

1. Install the Warp extension.
2. Run any command, such as “Open in Warp” or “Open Launch Configuration”.
3. An error message appears: “Cannot open selected item Error: Could not get the selected Finder items”.

### Current Behaviour

When I run any command, such as “Open in Warp” or “Open Launch Configuration”, an error message appears: “Cannot open selected item Error: Could not get the selected Finder items”.

### Expected Behaviour

I expect the commands to work as intended and open the selected items in Warp without any error messages.

**Comment by joetannenbaum** [comment]
So, the custom URI for the preview version is warppreview:// and for Warp it's warp://. I'll chat with the Warp team to see if they want to support both versions for the Raycast extension.
