### ISSUE TITLE
[Google Chrome] Google Chrome Beta commands not working with Raycast

### ISSUE THREAD

**Issue by ryan-efendy** [raycast/extensions#7604]
### Extension

https://www.raycast.com/Codely/google-chrome

### Description

I’m using Google Chrome Beta instead of the stable version, and none of the commands (search tabs, search history, search bookmarks) are working.

I'm using Raycast v1.55.2

### Steps To Reproduce

1. Install the Google Chrome extension.
2. Run any command, such as “search bookmarks”.
3. An error message appears: “🚨Error: Google Chrome browser has no bookmarks. Please add some bookmarks to continue using this command.” or when selecting the “new tab” command, this error appears: “🚨Error: Google Chrome browser is not installed. This extension depends on Google Chrome browser. You must install it to continue. If you have Homebrew installed then press ⏎ (Enter Key) to install Google Chrome browser. Click here if you want to download manually.”

### Current Behaviour

When I run any command, such as “search bookmarks”, I get an error message: “🚨Error: Google Chrome browser has no bookmarks. Please add some bookmarks to continue using this command.” When I select the “new tab” command, I get this error: “🚨Error: Google Chrome browser is not installed. This extension depends on Google Chrome browser. You must install it to continue. If you have Homebrew installed then press ⏎ (Enter Key) to install Google Chrome browser. Click here if you want to download manually.”

### Expected Behaviour

I expect the commands to work as intended and interact with my Google Chrome Beta browser without any error messages.

**Comment by andrewgoldsky** [comment]
Also having this issue

**Comment by xiaooojun** [comment]
不处理？？？
