### ISSUE TITLE
[Tana] ...

### ISSUE THREAD

**Issue by 3workingcats** [raycast/extensions#7606]
### Extension

https://www.raycast.com/cheslip/tana

### Description

When I tried to write a note and send it to Tana, an error message "Request failed with status code 400" appeared.

### Steps To Reproduce

1. In Raycast, activate the plug-in and type something.
2. Send.
<img width="886" alt="SCR-20230722-muqx" src="https://github.com/raycast/extensions/assets/87949333/2fccce94-079a-4171-882b-20a297d7b66a">

**Comment by hayley** [comment]
I installed this today and it's still having the issue reported above, but looks like the extension has been abandoned. :(

**Comment by cheslip** [comment]
@hayley can you try updating the API token? I just tried this on a new node and it's working.

**Comment by hayley** [comment]
That worked! I did "get API token" through the Tana command palette, then re-configured the extension with whatever tana put on the clipboard and that worked.
Thanks for the quick response!
