### ISSUE TITLE
[Toothpick] ...

### ISSUE THREAD

**Issue by kyellareddy** [raycast/extensions#7607]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

Would it be possible to let users set a keyboard shortcut to toggle a specific device?

### Who will benefit from this feature?

People who repeatedly connect to a specific device.
eg. keyboard, earbuds, etc.

**Comment by VladCuciureanu** [comment]
Hey! Check out the extension's settings. There you can enable one of the favorite device commands. In the command's setting you have to write the device name and then you can bind a key combination to the command

**Comment by kyellareddy** [comment]
I tried using that command but it doesn't seem to be working for me. I wrote in the name exactly as it shows up in my Bluetooth settings.

When I trigger that command, it says "Connecting" for a split second then stops.

**Comment by VladCuciureanu** [comment]
> I tried using that command but it doesn't seem to be working for me. I wrote in the name exactly as it shows up in my Bluetooth settings.
> 
> 
> 
> When I trigger that command, it says "Connecting" for a split second then stops.

Must be a bug. Will look into it

**Comment by VladCuciureanu** [comment]
Hey! I implemented recently an option to switch out the bluetooth backend. If you go to the extension's preferences, you can choose "blueutil (experimental)" as a bluetooth backend. This might solve your issue. Just be sure to install 'blueutil' via brew beforehand.
