### ISSUE TITLE
[Timers] ...Stopwatch won't showing in Menu Bar.

### ISSUE THREAD

**Issue by phosluo** [raycast/extensions#7612]
### Extension

https://www.raycast.com/ThatNerd/timers

### Description

I actived the Stopwatch Menu Bar command. But the stopwatch won't showing in Menu Bar.

### Steps To Reproduce

Maybe I used to set the Menu Bar in somewhere, but I can't remember it.

### Current Behaviour

The stopwatch shows in Menu Bar.

**Comment by ThatNerdSquared** [comment]
Hi @phosluo - just wanted to confirm a couple small things:

- you've checked that the stopwatch menubar icon isn't being hidden by any menu-bar-icon-hiding apps like Bartender, Hidden Bar, etc?
- the menu bar icon doesn't show when a stopwatch is running?
- you don't have the "Show Menu Bar Item When" preference set to "Never"?

**Comment by phosluo** [comment]
Yes, yes, and yes.

**Comment by ThatNerdSquared** [comment]
Hm. Does this only happen for the Stopwatch menu bar item? Or does the Timers menu bar item also not show up?

@pernielsentikaer there shouldn't be a case where a menu bar item just doesn't show up when activated, right? Worst case, if there's an error, it should just show a red ⚠️ warning symbol in the menu bar?

I may do a little more poking around to see if I can find a cause, but the menu bar still works on my side, both in prod and dev, so I'm not entirely sure what's happening at the moment.

**Comment by phosluo** [comment]
I tried the Caffeinate extension and it didn't show in menu bar, either.
In fact, every icon from extension can't show in the menu bar. (The Raycast icon itself can show.)
I remember I once used the Caffeinate extension, and it did show. But I didn't know how to turn it off, so I pressed command and drag its icon out of menu bar. That all I did.
Thanks for help.

**Comment by ThatNerdSquared** [comment]
Oh, so menu bar items for other extensions also don't work for you? Might want to ask about that in the Raycast Slack if it's not specific to any one extension.

**Comment by pernielsentikaer** [comment]
If you drag it outside the menubar  ⌘ it should be enough just to rerun the menubar command and it should get back.

Are you sure there is space for it (if you have the notch MacBook)

- Do you see any errors if you search for the menubar command?
- Do you see any errors in the command `Extension Diagnostics`

**Comment by phosluo** [comment]
[extension-diagnostics.txt](https://github.com/raycast/extensions/files/12188930/extension-diagnostics.txt)
[extension-diagnostics1.txt](https://github.com/raycast/extensions/files/12188931/extension-diagnostics1.txt)
<img width="736" alt="Screenshot 2023-07-28 at 08 09 56" src="https://github.com/raycast/extensions/assets/6356720/b1df7d05-1d5c-4771-b873-6b884657fec4">
@pernielsentikaer I found many Events in Extension Diagnostics. There are some runErrors.

I didn't see any errors when I search for the menubar command. And there is space for icons.
Thanks for help.

**Comment by pernielsentikaer** [comment]
How much space do you have in the menubar and did you have the notch version?

**Comment by phosluo** [comment]
Yes, I have the notch version. (MacBook Air M2, 2022)
<img width="1280" alt="Screenshot 2023-07-29 at 10 24 19" src="https://github.com/raycast/extensions/assets/6356720/7fdedddd-3229-4399-a681-17837a2c80aa">

I tried the Coffee extension and it still won't show. Just for your information.

**Comment by ThatNerdSquared** [comment]
Do we have any more new data on this issue?

If not, @phosluo I would suggest following up with the Raycast team on the Raycast Slack? It seems like this issue isn't limited to just the Timers extension, so unfortunately there's likely nothing I can do as an extension developer.

**Comment by pernielsentikaer** [comment]
Could you take a fullscreen image of your screen?

**Comment by TrySound** [comment]
Aaaahhhh, how to stop this stupid timer? Is there a process to kill? Raycast does not see any active timers.

**Comment by ThatNerdSquared** [comment]
@TrySound I'd recommend opening another issue if you're facing a problem, but in general, have you tried checking for "Ring Continuously" in the extension settings and the "Dismiss Ringing Timer" command?

If the alert sound is ringing but no timers are shown as finished in the "Manage Timers" command, that may be a serious bug.

**Comment by ThatNerdSquared** [comment]
@TrySound sorry about that, a new release has been shipped to fix this bug. The "Dismiss Ringing Timer" command or stopping the timer should stop the alert sound as well now.
