### ISSUE TITLE
[JetBrains Toolbox Recent Projects] ...

### ISSUE THREAD

**Issue by ghost** [raycast/extensions#7617]
### Extension

https://www.raycast.com/gdsmith/jetbrains

### Description

I have followed the install instructions ,but it doesn't work. In raycast, the extension doesn't show anything, and haven't any error message
idea version:2021.3.3
raycast version:1.55.2

<img width="750" alt="image" src="https://github.com/raycast/extensions/assets/137248730/18591260-f1df-4254-af86-6c8e501443d2">

<img width="315" alt="image" src="https://github.com/raycast/extensions/assets/137248730/c09728cc-87ae-41df-8a88-95a0cdefda41">

### Steps To Reproduce

no other steps, just follow the install instructions

**Comment by gdsmith** [comment]
@jinbaizhe-util did you install IDEA via JetBrains Toolbox?

*If you did:*

 - What version of Toolbox you are using?
 - Can you give the output of:

```sh
find ~/Library/Application\ Support/JetBrains -type f -name .history.json
```

I also see that's an older version of IDEA, any chance you can upgrade? JetBrains makes updates to the format of the history file this extension uses over time.

*If you didn't:*

This extension was made for Toolbox based installations and doesn't work well with manual installations. You can try re-installing via Toolbox or we can try and figure something out. As a first step it would be very helpful if you can let me know if you have any `.history.json` files anywhere in your `~/Library` directory somewhere.

**Comment by Jiinwoo** [comment]
<img width="642" alt="image" src="https://github.com/raycast/extensions/assets/46522752/1188666b-7271-4fa9-9446-81b1b84f28bf">



I have the same symptoms.

**Comment by gdsmith** [comment]
Okay, it's not finding any history files other than for Toolbox itself. Did you install the IDE(s) via Toolbox? What version of Toolbox are you using? What version of the IDE(s)?

**Comment by Jiinwoo** [comment]
I installed intelij through toolbox.

toolbox version: JetBrains Toolbox 2.0.0.16404, macOS 14.0
intellij version: 2023.2

**Comment by gdsmith** [comment]
There is no support for Toolbox 2.0 – it is not actually released yet.

**Comment by Jiinwoo** [comment]
JetBrains Toolbox 1.28.1.15219 and macOS 14.0 version are the same.
<img width="295" alt="image" src="https://github.com/raycast/extensions/assets/46522752/0c540beb-2939-4a02-9662-c486ed314dcd">


<img width="426" alt="image" src="https://github.com/raycast/extensions/assets/46522752/646693d2-9e15-4f0f-9502-48e1dcd106f8">

**Comment by gdsmith** [comment]
Okay, but if you already installed Toolbox 2.0 then it will have re-arranged all your tools (as the notice clearly states) so I don't think re-installing the previous version is going to work. Perhaps if you uninstall and re-install the tools there? I also don't know if there are any breaking changes in MacOS 14.0.

**Comment by gdsmith** [comment]
For anyone willing to test it out, please try the following PR #7799 which adds support for Toolbox 2.0
