### ISSUE TITLE
[Capture Fullpage of Website] ...

### ISSUE THREAD

**Issue by terryupton** [raycast/extensions#7619]
### Extension

https://www.raycast.com/Coun1er/capture-fullpage-of-website

### Description

When I run this I get the following error:
`Executable doesn't exist at /Users/ terryupton/Library/Caches/ms-playwright/ chromium-1005/chrome-mac/Chromium.app/ Contents/MacOS/Chromium...`

### Steps To Reproduce

1. Install extension
2. Run the extension
3. enter the url and hit enter
4. Error

<img width="886" alt="Screenshot 2023-07-23 at 19 42 02" src="https://github.com/raycast/extensions/assets/5698596/8470caab-2d6e-4fcc-821e-af1d49618b79">

**Comment by ironicmoka** [comment]
Same here.
Chrome installed (but not used in over a year), Brave and Vivaldi opened while testing the extension with same outcome
