### ISSUE TITLE
[GitHub] ERROR with "View all Notification" in Menu Bar

### ISSUE THREAD

**Issue by NicolasVaillant** [raycast/extensions#7625]
### Extension

https://www.raycast.com/raycast/github

#### Error:

```
Error: Could not launch command

process.processImmediate:timers:476:21
```

<img width="316" alt="image" src="https://github.com/raycast/extensions/assets/77850354/8682187e-e453-422b-aa6a-53e7dacb1345">

![SCR-20230724-egc](https://github.com/raycast/extensions/assets/77850354/a9cf372c-a6f8-4015-8b6c-8f21e1bb2f30)

### Steps To Reproduce

1. Enable `Unread Notifications` Menu Bar  with Background Refresh on Raycast
2. Click on `View all Notifications`(I do not have any notification)

### Current Behaviour

Clicking on `View All Notifications` with no notifications set the icon to an error state. Clicking on it opens the Raycast window with the message `Something went wrong`.

### Expected Behaviour

I do not know to be honest. I guess a GitHub app redirect ? a Raycast list with all notifications ?

**Comment by thomaslombart** [comment]
I'm not able to reproduce that bug. Are you logged in to the extension? Do you have any notifications when launching the `Notifications` command from the GitHub extension?

**Comment by NicolasVaillant** [comment]
Yes, it works. And now, `View All Notifications` from Menu Bar works well too... nvm.

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/77850354/73a3aadb-4ed8-4f76-b573-12cac063469f">

**Comment by NicolasVaillant** [comment]
Okay, I get it! I had the `Notifications` command disabled in Raycast, so the menu bar was unable to run it...
Sorry about that
