### ISSUE TITLE
[Todoist] Show filters command

### ISSUE THREAD

**Issue by dudido** [raycast/extensions#7627]
### Extension

https://www.raycast.com/doist/todoist

### Description

I would like to be able to access my tasks via filters. So Show Filters command in the Raycast extension (similar to Show Labels/Projects) would be great.

### Who will benefit from this feature?

Anyone using filters in Todoist

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by dudido** [comment]
I'm not a developer and wouldn't no where to begin. I just wanted to get the suggestion out there. Thanks

**Comment by geraldaddey** [comment]
Hi @thomaslombart, I am open to make the contribution to use this feature. I would appreciate some guidance.

**Comment by thomaslombart** [comment]
Hey @geraldaddey, here's the changes you'd probably have to make:

- Add support for filters in `syncRequest` along with types in `api.ts`
- Add a new command called `Show Filters` in `package.json` plus a file called `show-filters.tsx`
- Add support for filters in the `home.tsx` by adding a dropdown section in the search bar accessory

UX wise, I think displaying a list of filters that would lead you to a list of tasks by pressing enter is sufficient. Of course, you could add additional features like marking a filter as favorite, deleting one, etc.

Here's the [Todoist API used under the hood](https://developer.todoist.com/sync/v9/#overview).

If you have more questions, feel free to reach out in the [Slack community](http://raycastcommunity.slack.com/).

**Comment by kud** [comment]
I am also available to answer any questions regarding this. 😌

**Comment by geraldaddey** [comment]
@thomaslombart  thank you. I'll get right on with it

**Comment by geraldaddey** [comment]
@kud hi there. currently working on getting the tasks based on the filters. Can you help? Already worked on the view and could show if  you would like to see

**Comment by geraldaddey** [comment]
Hi @thomaslombart,
I've implemented the filter and filter tasks functionality in the Todoist extension. I'm planning to create a pull request for these changes. If you have any feedback or if there are any enhancements needed, please let me know. I'm open to working on them in the future.

**Comment by thomaslombart** [comment]
Awesome @geraldaddey, thanks for letting me know.

**Comment by geraldaddey** [comment]
@raycastbot this issue was resolved and PR approved. With @thomaslombart 's approval, you can close this issue. Thanks

**Comment by erauner12** [comment]
is this working for everyone? Seems to be broken for me and I am signed in and have my API key plugged into the raycast extension.
