### ISSUE TITLE
[1Password] Cannot log into onepassword

### ISSUE THREAD

**Issue by navxio** [raycast/extensions#7628]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

op signin command fails, log below

### Steps To Reproduce

on macos latest
Install the raycast onepassword extension

Try to sign in
login with 1password and allow access
enable 1password cli

<img width="892" alt="image" src="https://github.com/raycast/extensions/assets/9297865/c1b59035-5a77-4786-9f8d-e4004c995a47">

### Current Behaviour

Command failed: /usr/local/bin/op signin --account <myaccount name>
[ERROR] 2023/07/24 16:40:27 read: context deadline exceeded

### Expected Behaviour

signin successful and ability to copy passwords

**Comment by pernielsentikaer** [comment]
Just to be sure, can you run everything related to 1Password in the terminal, like `/usr/local/bin/op whoami`

**Comment by navxio** [comment]
@pernielsentikaer Hey, manually signing in with `op signin` fixed this for me.
