### ISSUE TITLE
[Spotify Player] "Set Volume to 75%" Message Typo

### ISSUE THREAD

**Issue by ethnzhng** [raycast/extensions#7637]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

The HUD confirmation message for the command "Set Volume to 75%" has a typo, displaying '25%' when it should say '75%'.

The typo can be seen [at the following line.](https://github.com/raycast/extensions/blob/7182e0c52d57e28273f75a9a65f70457c3ebe81d/extensions/spotify-player/src/volume75.ts#L10C9-L10C9)

### Steps To Reproduce

Run "Set Volume to 75%" command

### Current Behaviour

Message says 25%

### Expected Behaviour

Message says 75%

**Comment by peduarte** [comment]
Good catch, thanks!

**Comment by pernielsentikaer** [comment]
This is now fixed @ethnzhng - thanks for the hint 🔥
