### ISSUE TITLE
[Colorify - Generate Themes From Images] ...

### ISSUE THREAD

**Issue by d7mtg** [raycast/extensions#7648]
### Extension

https://www.raycast.com/EvanZhouDev/colorify

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

### Steps To Reproduce

Just tried to create a theme

**Comment by EvanZhouDev** [comment]
Please ensure you are using an image smaller than 4k. If you must, compress the image with an online compressor.
