### ISSUE TITLE
[Zoom] ...

### ISSUE THREAD

**Issue by willc121** [raycast/extensions#7650]
### Extension

https://www.raycast.com/raycast/zoom

### Description

When I use a raycast to start an immediate zoom meeting, zoom opens and then it says "waiting for host to start the meeting." 

I am the host... so it ends up being an useless meeting that I have to cancel and then open the app and then click "new meeting."

### Steps To Reproduce

1. run raycast
2. utilize "start meeting" command
3. Zoom will load and then say "waiting for host"
![Screenshot 2023-07-25 at 11 58 00](https://github.com/raycast/extensions/assets/125075541/9106cdfb-5de1-4d6d-aaa9-6de3f76dce3e)
<img width="634" alt="Screenshot 2023-07-25 at 11 58 23" src="https://github.com/raycast/extensions/assets/125075541/3fd31a97-d057-4762-8a08-ddf361cbd4a3">

**Comment by thomaslombart** [comment]
Are you sure you're authenticated with the same account on the Zoom app and the Raycast extension?

**Comment by thomaslombart** [comment]
I took a second look at this issue, and I was able to reproduce it only if I was signed in with another account. Therefore, I'm closing it. Please feel free to reopen it and paste a recording if it's not working out for you.
