### ISSUE TITLE
[Carbon Screenshot for Raycast] Unable to create a screenshot with default settings

### ISSUE THREAD

**Issue by VGontier-cmd** [raycast/extensions#7654]
### Extension

https://www.raycast.com/adelowo/carbon-code-screenshot-for-raycast

#### Error:
```
Error: Could not find Chromium (rev. 1069273). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /Users/vgontiercmd/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.

 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /Users/vgontiercmd/.cache/puppeteer).
m2.resolveExecutablePath:index.js:591:2210

```

### Steps To Reproduce

1. Launch the extension
2. Create a screenshot with the params: Automatic, 3024 Night, Dank Mono

### Current Behaviour

```Something went wrong```

### Expected Behaviour

A screenshot generated / copy image to clipboard

**Comment by adelowo** [comment]
Apologies @VGontier-cmd . I’d take a look after work hours today

**Comment by VGontier-cmd** [comment]
> Apologies @VGontier-cmd . I’d take a look after work hours today

No worries, thanks for looking at it

**Comment by VGontier-cmd** [comment]
Hey ! Any news regarding the issue? @adelowo
