### ISSUE TITLE
[Spotify Player] toggle pause error

### ISSUE THREAD

**Issue by haikeyidesu** [raycast/extensions#7658]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Unknown error occurred when I tried to toggle/pause my music

### Steps To Reproduce

just open spotify

### Current Behaviour

Says unknown error

### Expected Behaviour

pause/play music

**Comment by peduarte** [comment]
Hey, this is odd 🤔 Are you a Spotify Premium subscriber?
