### ISSUE TITLE
List API throttle can provider a custom delay time API?

### ISSUE THREAD

**Issue by Haojen** [raycast/extensions#766]
**Will this change the current api? How?**
My Backend API server request limit is strict, so this List API default throttle delay time always too short, so I need to set a custom throttle delay duration time, hope can be add this feature.

**Any Other info.**
I love Raycast, hope doing well!

**Comment by thomaspaulmann** [comment]
We try to keep the behavior the same across extensions. Therefore we won't change the built-in `throttle`. That said, if it's too slow for your use case, you can also use the `onSearchTextChange` callback and implement your own logic. Though, it should obviously make sense for your extension. If in doubts, use the built-in one ;-)

**Comment by Haojen** [comment]
@thomaspaulmann  Thank you reply, I understand and that's exactly what I've done.
