### ISSUE TITLE
[ChatGPT] Remove me from getting pinged every time an issue is created

### ISSUE THREAD

**Issue by shichongrui** [raycast/extensions#7660]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Every time an issue is created for the ChatGPT extension I get mentioned by the Raycast bot. I don't want to be mentioned every time an issue is created for the ChatGPT extension. I submitted one bug fix when I was testing the extension, and now for all time Raycast will believe I can help. But my time is finite, and so is my knowledge, and it's just noise.

### Steps To Reproduce

1. Create a bug report for an extension
2. Wait momentarily
3. See @shichongrui get mentioned by the Raycast bot

### Current Behaviour

I get mentioned.

### Expected Behaviour

I don't get mentioned.

**Comment by pernielsentikaer** [comment]
It's because you're one of the contributors, for now, the only way not to get pinged is to remove you as a contributor 🙂

**Comment by Nauxscript** [comment]
![image](https://github.com/raycast/extensions/assets/13010589/a644fa76-463e-470d-a918-a335a720d3c4)

Maybe this will be helpful for you.

**Comment by shichongrui** [comment]
Oh duh 🤦 thanks.

**Comment by josephlou5** [comment]
You can also add yourself to the `"pastContributors"` field in the `package.json`. See #18222 as an example.
