### ISSUE TITLE
[Claris Snippets] ...

### ISSUE THREAD

**Issue by glenavontechnology** [raycast/extensions#7662]
### Extension

https://www.raycast.com/eluce2/claris-snippets

### Description

Started to get an error whereby any new snippets saved can no longer be used, as an error message appears:

This has always worked fine in the past, I have no idea what's changed. Old snippets still work, it's just any new ones don't seem to work.

Tried copying from FM19 and FM20, no plugins, nothing else changed?!

![FileMaker Pro - Script Workspace (Untitled) 2023-07-26 at 3 38 38 PM](https://github.com/raycast/extensions/assets/105449924/ba05fe16-b233-4f73-b993-9edc0dc44162)

### Steps To Reproduce

1. In filemaker, copy script steps
2. in Raycast, add Claris Snippet
3. In Raycast, select added snippet
4. Error message appears in Raycast

**Comment by eluce2** [comment]
see also https://github.com/raycast/extensions/issues/5888
