### ISSUE TITLE
[NixPkgs Search] Error when searching 

### ISSUE THREAD

**Issue by bromanko** [raycast/extensions#7664]
### Extension

https://www.raycast.com/aiotter/nixpkgs-search

### Description

I am getting an error when attempting any search:

`Could not perform search. Error: No such index [latest-40-nixos-unstable]`

Reinstalling and installing the extension does not resolve the issue.

### Steps To Reproduce

1. Type anything in the search box
2. See error message

### Current Behaviour

Search returns an error.

### Expected Behaviour

Search should not return an error.

**Comment by j-jeurissen** [comment]
duplicate of #7623

**Comment by bromanko** [comment]
Closing as duplicate.
