### ISSUE TITLE
[Arc] Multi Profile Support

### ISSUE THREAD

**Issue by joshmedeski** [raycast/extensions#7665]
For the [arc extension](https://github.com/raycast/extensions/tree/6245dc92e1945c7c95c3eb50a59eb8b108ebcac9/extensions/arc)

### Description

As a user, I want my Arc commands to work across multiple profiles, so I can access data across all my browser activity.

### Who will benefit from this feature?

Anyone who leverages multiple profiles in Arc.

### Anything else?

"Search Arc" is currently only looking up the [Default profile's history](https://github.com/raycast/extensions/blob/6245dc92e1945c7c95c3eb50a59eb8b108ebcac9/extensions/arc/src/sql.ts#L10). We need to come up with a way to work with multiple profiles.

There are some ideas on how this could be done.

1. Create a useSQL hook variation that can query multiple databases and return all of the results together (less performant but an easier experience).
2. Create separate "Search arc" commands for each profile (isolated but more performant and easier to use).

**Comment by kevinjfoley** [comment]
I'd love to see support for this as well.  Or failing support for multiple profiles, it'd be nice to have the ability to select which profile is searched.
