### ISSUE TITLE
[Currency Exchange] ...

### ISSUE THREAD

**Issue by edmondnow** [raycast/extensions#7670]
### Extension

https://www.raycast.com/xeric/currency-exchange

### Description

The extension doesn't seem to work 

### Steps To Reproduce

input: 10
currency selected: usd
error: Unexpected token < at JSON at Position 0:

**Comment by xeric** [comment]
@edmondnow it works fine in my side, could you please check if you have right API Key set in your configuration? you also can use some API client (e.g. Postman) to test the currency APIs with your key to confirm it works well or not. APIs are here: https://www.exchangerate-api.com/docs/overview

<img width="1000" alt="currency-exchange 2023-07-27 at 12 26 42" src="https://github.com/raycast/extensions/assets/190927/ced62bab-c58a-4aa3-84e2-3ab239ab3497">
