### ISSUE TITLE
[Calendar - My Schedule] Open Google Meet events with default browser (instead of chrome)

### ISSUE THREAD

**Issue by MattisBrizard** [raycast/extensions#7671]
### Description

When I have a Google Meet event in my calendar, it appears in Raycast My Schedule, when I press enter, it automatically opens Google Chrome.
I would prefer that command to open the meeting in my Default Browser.

### Current Behaviour

Calendar - My Schedule opens Google Meet event with Google Chrome.

### Expected Behaviour

Calendar - My Schedule opens Google Meet event with the default browser.

**Comment by mathieudutour** [comment]
This issue is not related to the API or 2rd party extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
