### ISSUE TITLE
Authy

### ISSUE THREAD

**Issue by pratham-emedgene** [raycast/extensions#7674]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

Most of the accounts/tokens are marked as "corrupted". Only a few display the OTP.
I had been using the extension for a while and it was working fine. I added a new account and did "Sync" in Authy commands and since then accounts/tokens showing corrupted. 

Also tried uninstalling/installing the extension and the issue persists.

Raycast version: 1.56.0
![image](https://github.com/raycast/extensions/assets/72385252/12e9ed5c-25a6-41f4-a529-9bf2462d8a6f)

### Steps To Reproduce

1. Open raycast
2. Search for Authy extension/command
3. Press enter

### Current Behaviour

Many tokens are "corrupted"

### Expected Behaviour

Display OTP

**Comment by pernielsentikaer** [comment]
Have you seen that before @guga4ka

**Comment by gdsmith** [comment]
Sounds almost identical to this ticket #7659

**Comment by guga4ka** [comment]
that basically shows that Authy backup password is wrong. @pratham-emedgene could you pls double check it?

**Comment by pratham-emedgene** [comment]
Backup password was correct because it worked in another device also the extension was working prior with the same password. However I did reset it and then re-installed extension and used new password and it worked. Authy changed their password requirements and may be it has got to do with it somehow.
