### ISSUE TITLE
[Reminders] Improve due date change logic

### ISSUE THREAD

**Issue by coffenbacher** [raycast/extensions#7682]
### Extension

https://www.raycast.com/extensions/reminders

### Description

Currently, in "My Reminders", Cmd+D opens a cool due date change prompt where you can type e.g. "Tomorrow" or "Next week".

This feature request is to change the behavior of typing days like "Thursday" to assign them to the next future Thursday, rather than Thursday in the current week (which could be in the past). So on a Friday, if you change the due date to Thursday, it should change it the Thursday 6 days in the future instead of 1 day in the past. (As far as I know, changing due dates to be a new date in the past is not part of any normal workflow.)

### Who will benefit from this feature?

Anyone using Cmd+D in Raycast Reminders extension.

**Comment by coffenbacher** [comment]
> We could not find the extension related to this issue. Please update the issue with the correct link to the extension.

I am unclear what the bot means. https://www.raycast.com/extensions/reminders seems to be the correct link to the extension.

**Comment by coffenbacher** [comment]
I disagree with the bot, this would be a good improvement 🤷

**Comment by verheyenkoen** [comment]
Looks like this is a baked-in extension of some kind that is not in this code base, even though it works the same as an extension.
