### ISSUE TITLE
[Google Chrome Profiles] Add quick link for each profile

### ISSUE THREAD

**Issue by mibrahimdev** [raycast/extensions#7683]
### Extension

https://github.com/raycast/extensions/tree/main/extensions/google-chrome-profiles

### Description

As a Raycast user I want to get quick access of each Chrome profile such as [work - personal ....]

### Who will benefit from this feature?

Any one using multi profiles

**Comment by mibrahimdev** [comment]
@frouo what do you think?

**Comment by frouo** [comment]
Hello @mibrahimdev, I am not sure to understand your request.

You can already quick access your Chrome Profiles by adding a shortcut for the "Google Chrome Profile" (I recommend Cmd+Shift+M) and then hit Cmd+Enter.

**Comment by mibrahimdev** [comment]
@erics118 Thanks 👏🏼

**Comment by frouo** [comment]
Sorry @mibrahimdev I didn't know about this Quicklinks feature! Thank you @erics118 for your contribution.
