### ISSUE TITLE
[Browser Bookmarks] Add Vivaldi support

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#7685]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

Please add Vivaldi browser support

### Who will benefit from this feature?

All Vivaldi users

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.
