### ISSUE TITLE
[PromptLab] "Open Advanced Settings" -- can we control which editor?

### ISSUE THREAD

**Issue by oferhalevi** [raycast/extensions#7690]
### Extension

https://www.raycast.com/HelloImSteven/promptlab

### Description

"Open Advanced Settings" launches Xcode. Can this be controlled/configured to launch a different editor (VS Code, etc.)?

**Comment by SKaplanOfficial** [comment]
It opens in your default JSON editor. You can look [here](https://stackoverflow.com/a/43665710) for instructions on how to change the default editor for all files with the .json extension.
