### ISSUE TITLE
[Hue] Turning on groups sets brightness to 0

### ISSUE THREAD

**Issue by namzo** [raycast/extensions#7696]
### Extension

https://www.raycast.com/pindab0ter/hue

### Description

When you turn on a group (Control Groups  > Click on room or zone), the brightness of all lights in that group is set to 0.

It works correctly when you go through "Control Lights", but you have to turn on each light individually.

### Steps To Reproduce

1. With hue lights off, Open Raycast
2. Search and click "Control Groups"
3. Click on a Room or Zone

### Current Behaviour

The Room or Zone is turned on but brightness is set to 0.

### Expected Behaviour

Brightness should be set to the previous set value.

**Comment by pindab0ter** [comment]
@raycastbot close this issue
