### ISSUE TITLE
[Bug] `ctrl`+`[` doesn't work in lieu of `esc`

### ISSUE THREAD

**Issue by starptr** [raycast/extensions#772]
## Description
Pressing `ctrl`+`[` should have the same behavior as pressing `esc`.

## Steps to Reproduce
1. Bring up raycast with `alt`+`space`
2. Try to close it by pressing `ctrl`+`[`

## The Current Behavior
Nothing happens

## The Expected Behavior
Raycast should close

### Raycast version
v1.27.0

**Comment by sxn** [comment]
thanks for the bug report @starptr. However, this doesn't seem to be related to the extension API, so would you mind reporting through the in-app `Send Feedback` feature? 😺

**Comment by starptr** [comment]
oops, sorry about that!
