### ISSUE TITLE
[Jira] Priority icons are too large and misaligned

### ISSUE THREAD

**Issue by jrmajor** [raycast/extensions#7726]
### Extension

https://www.raycast.com/raycast/jira

### Description

Some priority icons on the right are twice the size they should be, some of them have different size than other:

![Screenshot of “Open Issues” view with too large and misaligned icons](https://github.com/raycast/extensions/assets/26096713/f3e554fc-265a-4c82-835d-b0e97e765012)

### Steps To Reproduce

Just open the “Open Issues” command.

### Current Behaviour

Too large and misaligned icons :c

### Expected Behaviour

Small, cute icons that perfectly fit Raycast design!

**Comment by thomaslombart** [comment]
Thanks for bringing this issue to our attention. We'll work on it and will keep you updated on our progress!

**Comment by jrmajor** [comment]
That's great, thank you!
