### ISSUE TITLE
[GitHub] `Mark All as Read` not working as expected on Unread Notifications menu bar command

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#7727]
### Extension

https://www.raycast.com/raycast/github

### Description

When clicking on `Mark All as Read` the menu bar command icon color doesn't change immediately and we need to click on it again for the command to visually take effect.

P.S.: Not related to this issue, but I would also suggest changing the icon color from orange to a color more in line with the colors used in the GitHub brand. I believe the purple used in the GitHub Desktop app icon would be a better match.

![desktop-icon](https://github.com/raycast/extensions/assets/11052366/ad8eb744-8aeb-4546-9b99-3f96ffbb0230)

### Steps To Reproduce

1. Click on Unread Notifications menu bar icon.
2. Click on `Mark All as Read`.

### Current Behaviour

The icon color will not change immediately, as if the command had not visually taken effect.

### Expected Behaviour

The icon color should change immediately, as if we had no more unread notifications.

**Comment by thomaslombart** [comment]
I wasn't able to reproduce it. Are you getting this bug consistently?

**Comment by xilopaint** [comment]
Yes. The notifications are read but the icon doesn't change its color unless I click on it again or wait for the next refresh.

**Comment by thomaslombart** [comment]
Could you share a recording, please?

**Comment by xilopaint** [comment]
> Could you share a recording, please?

@thomaslombart As you can see, I first click on `Mark All as Read`, but the menu bar icon doesn't update right away. So, I need to click a second time for the icon to change its color.

https://github.com/raycast/extensions/assets/11052366/76359104-d092-435d-b345-57f05b27194c

**Comment by xilopaint** [comment]
@thomaslombart I still have the same issue with the latest version of the extension.

**Comment by thomaslombart** [comment]
Have you run the `Check For Extension Updates` command?

**Comment by xilopaint** [comment]
Yes.

**Comment by thomaslombart** [comment]
I had the issue before and I'm confident the issue is fixed since clearing the notifications is now [done optimistically](https://github.com/raycast/extensions/blob/62375e12bcee5c3cbd7a04903e28f2f359c8acbb/extensions/github/src/unread-notifications.tsx#L42) so it should be cleared immediately (like below):

https://github.com/raycast/extensions/assets/16003285/8f958f4f-a724-41c6-80fc-812285a9ca40

Sometimes extension updates land a bit later, so I'd recommend waiting for a bit less than an hour, checking for extension updates again, and letting me know if you still have the issue.

**Comment by thomaslombart** [comment]
I'd say that the orange color pops more in the menu bar than the purple one. Also, won't it be confusing to have the same color than GitHub Desktop?

**Comment by xilopaint** [comment]
> I'd say that the orange color pops more in the menu bar than the purple one. Also, won't it be confusing to have the same color than GitHub Desktop?

I don't it confusing once you know ahead of time that the item is intended to show notifications and is not part of the Desktop app. I simply think it's a natural choice to use the brand color scheme.

As for what color pops more, if this is the criteria you chose, I would stick with the green color. It's the color used by the [Gitify](https://www.gitify.io/) menu bar app that has the same functionality.

I just find the current orange color ugly and somewhat sad.
