### ISSUE TITLE
[PromptLab] Error when clicking on the menu bar command

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#7728]
### Extension

https://www.raycast.com/HelloImSteven/promptlab

### Description

When clicking on the menu bar icon, I see this error pop up after a few seconds:

<img width="737" alt="Screenshot 2023-07-30 at 19 59 00" src="https://github.com/raycast/extensions/assets/11052366/dccd6754-e545-4c09-ac94-7b06e6b80752">

### Steps To Reproduce

1. Click on the menu bar icon and wait a few seconds.

### Current Behaviour

Error pops up.

### Expected Behaviour

No errors being displayed.

**Comment by SKaplanOfficial** [comment]
This is a limitation in Raycast, as far as I can tell. It's been reported as a bug in the official slack channel.

**Comment by xilopaint** [comment]
What's causing this?

**Comment by SKaplanOfficial** [comment]
There's a timeout for menu bar commands that happens regardless of whether the menu is actively opened or not, and extension developers have no control over it. It happens with all of the menubar commands I've got set up (Pomodoro, Text Shortcuts, Color Picker).

**Comment by xilopaint** [comment]
I don't get the same error when click on the Unread Notifications menu bar command of the GitHub extension.

**Comment by SKaplanOfficial** [comment]
Hm that one uses a 15 minute interval, while PromptLab (and presumably the others I listed) don't have any update interval. That might be a workaround for now. I'd assume that the error still appears after 15 minutes, but I can't test that right now.

**Comment by SKaplanOfficial** [comment]
This should be fixed with the latest Raycast update.

**Comment by xilopaint** [comment]
Yes, it's fixed. Thanks!
