### ISSUE TITLE
AppWindowGrid2x2 and AppWindowGrid3x3 are blank squares

### ISSUE THREAD

**Issue by octoxan** [raycast/extensions#7729]
### Description

Trying to use the icons on this page https://developers.raycast.com/api-reference/user-interface/icons-and-images and all of them I've tried seem to work just fine except for AppWindowGrid2x2 and AppWindowGrid3x3 which are just squares without the smaller icon grids.

VS Code auto completes for these 2, so it seems to be the recommended name for them, not sure what's up with them.

### Steps To Reproduce

1. Be building an extension
2. Do `<List.Item title="Icon" icon={Icon.AppWindowGrid2x2} />

### Current Behaviour

Blank square icon

### Expected Behaviour

The icons in the documentation.

**Comment by mathieudutour** [comment]
Fixed
