### ISSUE TITLE
[Memos] This extension should be upgrade for new release version of memos

### ISSUE THREAD

**Issue by qkxie** [raycast/extensions#7731]
### Extension

https://www.raycast.com/JakeYu/memos

### Description

From version 0.14.0, memos upgrade its API format. And this extension is still use old API.

### Steps To Reproduce

1. Upgrade memos to latest version.
2. The extension is broken.

### Current Behaviour

Can not send memos. It raise error.

### Expected Behaviour

Work.

**Comment by qkxie** [comment]
https://github.com/raycast/extensions/pull/7686

**Comment by qkxie** [comment]
For memos 0.15.1, it has changed the auth method again.

The plugin should be updated again.

**Comment by JakeLaoyu** [comment]
#8518 8518
