### ISSUE TITLE
[Spotify Controls] ... Search track and add to queue 

### ISSUE THREAD

**Issue by mollekensl** [raycast/extensions#7734]
### Extension

https://www.raycast.com/thomas/spotify-controls

### Description

This used to be a feature, as I could've sworn I used this. We were able to search a track, any track and add it to the queue, as i don't always want to instantly play the song and have it throw off my entire ongoing playlist. 

### Who will benefit from this feature?

Everyone? I feel like it's a common thing to have a song pop up into your head and you want to play it without having to open up spotify, go click that search bar and add that song to the queue, while we can just open raycast, type a command look for the song and add it to the queue with a command. i swear this was a feature before, i'd love it back as i used it all the time and find myself missing it every time. 

### Anything else?

![Track Search](https://github.com/raycast/extensions/assets/94297901/432a8a67-03ed-47d2-bb43-88d9fef2e51c)
much like this but then in the command+K the option of adding it to a playlist, to play it straight away, and most importantly to add it to the queue.

**Comment by yansq** [comment]
Firstly, I guess the plugin you are using is "[Spotify Player](https://www.raycast.com/mattisssa/spotify-player)," not "Spotify Controls". And the reason for the lack of "add to queue" function might be that you selected an artist instead of a specific song. In my testing, I found that option is available.
<img width="740" alt="image" src="https://github.com/raycast/extensions/assets/26108404/59329deb-8f21-4dee-8a98-de4855586c1f">

**Comment by mollekensl** [comment]
I'm fully aware that it's another extension, it was to show what I meant; "spotify controls" used to have this function, but doesn't anymore. My bad for not noticing that I selected an artist and there is in fact an "add to queue"; regardless of that, I'd prefer to not have to use a mix of extensions as I use "spotify controls" more often and this would be an addition. 

Within the other extension there also is no shortcut/keybinding to quickly add to the queue, which again, used to be an option on "spotify controls" and is not configurable in their commands.
