### ISSUE TITLE
[Google Tasks] When creating events with a Time, the time appears to get dropped

### ISSUE THREAD

**Issue by dep** [raycast/extensions#7739]
### Extension

https://github.com/raycast/extensions/blob/ef8d03a61d44c57f8046beea5fc348a71312bff4/extensions/google-tasks/

### Description

I've noticed that when I create an event using Raycast, and give it a time like "August 12 at 2pm" the event gets created, but as an all-day event on August 12th (the time gets dropped).

### Steps To Reproduce

1. In Raycast create a new task ("Lunch with Bob")
2. Give it a date and time (August 12 at 2pm)
3. Create the task

### Current Behaviour

Notice the task is created on August 12, but has no time

### Expected Behaviour

Task should be scheduled for 2pm

**Comment by elliotdes** [comment]
Hey, extension author here.

Nothing can be done about this one as the Google task API doesn't let you set a time!

**Comment by dep** [comment]
Oh bummer! Well thanks for reporting back @elliotdes!
