### ISSUE TITLE
[Toggl Track] ... Invalid API Key Detected

### ISSUE THREAD

**Issue by shrop** [raycast/extensions#7749]
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Description

Over the past month, I have noted the API key does not work and I get the message "Invalid API Key Detected". 

I have to uninstall and install the extension to place the API key back in place. This seems to happen once per month, but can be every few days. I haven't found a trigger for this. Thought maybe it was around extension updates, but that doesn't seem to be the case based on the last commits in Github.

Good news is the work around is to reinstall.

![API Key Issue](https://github.com/raycast/extensions/assets/14832/69d9c010-f323-4702-8955-b0a802d7e61c)

### Steps To Reproduce

1. Install the extension
2. Set the API key
3. Use extension
4. Note the API key will fail to work with the message "Invalid API Key Detected" at some point later

### Current Behaviour

API key stops working at least once per week

### Expected Behaviour

API key continues to work

**Comment by bkeys818** [comment]
Wow, that's an odd one. I haven't heard of anyone experiencing this issue.

I've got a few questions too establish context.
- Do you pay for premium?
- Are you of an organization? (not owned by you)
- Are you a Toggl Track beta tester?

**Comment by franzwilhelm** [comment]
In fact I also experienced this, but also resolved it by reinstalling 🤔 I'll have a look

**Comment by shrop** [comment]
I am a Raycast premium user @bkeys818. It happened for a couple of weeks there and after 3-4 uninstalls and reinstalls on two Macs, It has been more stable the past week or so. 

My Toggl account is a free personal one, not tied to an organization. Also, I am not a Toggl Track beta tester as far as I know. I once beta tested their recruiting tools.
