### ISSUE TITLE
[Asana] cannot assign nor self-assign

### ISSUE THREAD

**Issue by Piste** [raycast/extensions#7753]
### Extension

https://www.raycast.com/raycast/asana

### Description

My assignee box remains empty, whether I type something or don't.

### Steps To Reproduce

1. Create task
2. Try to assign it

**Comment by thomaslombart** [comment]
Could you share a recording, please?

**Comment by Piste** [comment]
I can. I'm not sure when I'll get to it though as I'll need to obfuscate/anonymize some of the information. Is there a log file I can look at to troubleshoot further on my own?

**Comment by thomaslombart** [comment]
You could always run the extension locally by forking the extension ([Contribute to an extension](https://developers.raycast.com/basics/contribute-to-an-extension))

**Comment by alper** [comment]
Here, I have one:

![CleanShot 2023-09-11 at 00 52 00](https://github.com/raycast/extensions/assets/72429/44bb19df-6bdd-4f47-9b69-cc863debe86f)

**Comment by thomaslombart** [comment]
Could you expand the error you have in the toast? It looks like there's a helpful message there.

**Comment by alper** [comment]
Ah, I hadn't even noticed that. Here you go.

![CleanShot 2023-09-11 at 11 12 33@2x](https://github.com/raycast/extensions/assets/72429/c9c414af-e30a-451d-8264-2362f35809d1)

**Comment by thomaslombart** [comment]
Interesting. Could you give me more details about your workspace? Do you have any clue why fetching users in this workspace wouldn't be allowed there?

**Comment by alper** [comment]
I think my workspace is relatively legacy. Not sure how to give the exact details. I can't find anything in Asana itself.
