### ISSUE TITLE
[Extension Bug] CoinMarketCap Crypto Search

### ISSUE THREAD

**Issue by zweizeiler** [raycast/extensions#776]
# Extension – [CoinMarketCap](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/coinmarketcap-crypto-crawler/)

Author:  @moojing 

## Description

When searching crypto, the something went wrong screen pops up.

## Steps To Reproduce

1. Search Crypto List

## The current behavior

![image](https://user-images.githubusercontent.com/71968447/151927079-c952826a-a2df-4dd2-ab31-2af2e72eb4b7.png)

## The expected behavior

Load Crypto List

### Raycast version
Version: 1.27.1

**Comment by sxn** [comment]
thanks for the bug report! None of the commands added by the extension work for me, either. @moojing any idea what's wrong? 🤔

**Comment by moojing** [comment]
@sxn  Thanks for the improvement! It looks well. 
After checking I found that use `params` when sending request can solve the problem (instead of `data`). 
I've made the PR [here](https://github.com/raycast/extensions/pull/797) !
