### ISSUE TITLE
[JetBrains Toolbox Recent Projects] ...

### ISSUE THREAD

**Issue by Lzzzs** [raycast/extensions#7763]
### Extension

https://www.raycast.com/gdsmith/jetbrains

## It's still loading. I've been waiting a long time
![image](https://github.com/raycast/extensions/assets/74575471/988cfd89-ff57-4a68-bd5e-5733a118cfea)

### Steps To Reproduce

1. open store
2. install JetBrains Toolbox

**Comment by gdsmith** [comment]
Have you updated to Toolbox 2.0? If so the extension is not currently compatible.

**Comment by Lzzzs** [comment]
I don't know what version I have, but I just installed it from the store

**Comment by gdsmith** [comment]
The version of JetBrains Toolbox I mean

![image](https://github.com/raycast/extensions/assets/908695/4cde5bfb-630f-4f68-a620-3d4b2fee6272)

**Comment by Lzzzs** [comment]
Thank you very much. The problem has been solved. I didn't have JetBrains Toolbox on my computer, but the problem was fixed after downloading it
