### ISSUE TITLE
[Google Bard] ...

### ISSUE THREAD

**Issue by isuruhg** [raycast/extensions#7764]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

Hi

Doesnt seem to work. I've copied the cookie details correct (and on Safari).

### Steps To Reproduce

1. Enter cookie details upon installation.
2. Activate bard (e.g explain)
3. Unable to reach Bard.

**Comment by EvanZhouDev** [comment]
Have you tried going to bard.google.com, clearing cookies, and getting a new PSID?
Also, if its still not working, use the extension for the official Bard API: https://www.raycast.com/EvanZhouDev/raycast-google-palm
