### ISSUE TITLE
[Bitwarden Vault] Customize password generation 

### ISSUE THREAD

**Issue by bmwilly** [raycast/extensions#7767]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Ability to customize how "Generate Password" behaves — e.g., the number of characters and whether special characters are included. 

AFAICT, the current behavior is to produce a 14-charactuer alphanumeric password, and that this can't be customized. 

### Who will benefit from this feature?

Everyone who uses the extension

**Comment by bmwilly** [comment]
Similar issue that didn't get a response: https://github.com/raycast/extensions/issues/2303

**Comment by jomifepe** [comment]
Hey, thanks for the suggestion. Yeah, for sure, if other clients have that option, I'm happy to include it in the extension. Added to my [personal backlog](https://github.com/jomifepe/extensions/issues/18).

**Comment by jomifepe** [comment]
I submitted a [PR](https://github.com/bitwarden/clients/pull/5974) add those to the CLI, let's see what they say :)

**Comment by bmwilly** [comment]
@jomifepe thanks for the response and the CLI PR! 

However, the CLI currently supports password length and whether special characters are included (as shown in your screenshot), but these are not options in the Raycast extension as far as I can tell.

**Comment by jomifepe** [comment]
They are, in the `Generate Password` command, does it not look like this for you?

![Screenshot 2023-08-12 at 10 41 02](https://github.com/raycast/extensions/assets/7235666/daf01544-296d-485d-8714-bbb4edca1e18)

**Comment by bmwilly** [comment]
ah, I had only been using `Generate Password (Quick)` with a hotkey, so hadn't seen that menu before. Sorry for the noise (still learning Raycast)! 

Please feel free to close this out or use it to track the changes related to https://github.com/bitwarden/clients/pull/5974 

Thanks!

**Comment by jomifepe** [comment]
No worries, I'm glad it's working 🙂 
I can try to make it more clear that `Generate Password` defines the options for the Quick version of the command.
