### ISSUE TITLE
[Google Bard] - Nothing Working

### ISSUE THREAD

**Issue by AbdulrahmanNahhas** [raycast/extensions#7769]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

# "AI Chat" Command Problem:

When I try to use AI Chat command it will return "Failure to Fetch Bard" always.

<img width="923" alt="Screenshot 2023-08-02 at 4 59 44 PM" src="https://github.com/raycast/extensions/assets/91866837/ffa05db4-6e78-4d0c-879a-4a9fc75b493c">

And when I tried to use any command in AI Chat always it returns errors.

<img width="371" alt="Screenshot 2023-08-02 at 5 02 36 PM" src="https://github.com/raycast/extensions/assets/91866837/5f70db9d-af0a-4e7c-94ce-29ef98e4eb06">

# Other Commands Problems:
All other commands only use the selected text, so I can't enter texts in there. and I think that is a really big problem 

<img width="864" alt="Screenshot 2023-08-02 at 4 59 57 PM" src="https://github.com/raycast/extensions/assets/91866837/03c7d450-1321-452c-96a0-06101a8f5f4f">
<img width="843" alt="Screenshot 2023-08-02 at 5 00 04 PM" src="https://github.com/raycast/extensions/assets/91866837/afd0fbe3-f056-47c8-83a4-6289c52c75dd">
<img width="834" alt="Screenshot 2023-08-02 at 5 00 10 PM" src="https://github.com/raycast/extensions/assets/91866837/2ce74921-a675-4719-86d8-23fc4489b7a6">
<img width="829" alt="Screenshot 2023-08-02 at 5 00 17 PM" src="https://github.com/raycast/extensions/assets/91866837/a9ad5053-2594-4183-a041-d2803bab22fb">
<img width="820" alt="Screenshot 2023-08-02 at 5 00 25 PM" src="https://github.com/raycast/extensions/assets/91866837/5c51e4fb-6137-4061-bf63-f3c089d330d1">

### Steps To Reproduce

1. Log in to your Google account, and visit [Google Bard](https://bard.google.com/)
2. Open the Web Inspector, and go to the "Application" tab.
3. Click open the Cookies dropdown on the sidebar, under storage, and click on the option that says https://bard.google.com.
4. Look for and copy the Cookie labeled __Secure-1PSID. Make sure you copy the periods at the end as well.

### Current Behaviour

**Nothing Working.**

### Expected Behaviour

**Everything should work**

🔔 @EvanZhouDev you might want to have a look.

**Comment by EvanZhouDev** [comment]
Have you tried going to bard.google.com, clearing cookies, and getting a new PSID?
Also, if its still not working, use the extension for the official Bard API: https://www.raycast.com/EvanZhouDev/raycast-google-palm

**Comment by AbdulrahmanNahhas** [comment]
Thank you for your quick and informative answer 😊.
