### ISSUE TITLE
[Extension Feature Request] Switch both Input and Output to same device in one command

### ISSUE THREAD

**Issue by mrvkino** [raycast/extensions#777]
# Extension – [Audio-Device](https://github.com/raycast/extensions/tree/main/extensions/audio-device)

Author: @benvp

**Describe the feature and the current behavior/state.**
It would be great to have a command to switch both input and output. This would allow to switch all sound to one device without doing two command.

**Who will benefit with this feature?**
Everyone with a video-conference headset and a laptop. We can do video call on both device and its a hassle to change both input and output separately.

**Any Other info.**
This command would list only devices that can support both Input and Output such as a headset and the laptop. It would skip speakers, dedicated podcasting mic, etc...

**Comment by benvp** [comment]
Sounds like a nice extension. I think we could probably implement this as either

* a separate command which switches both
* or an action which you open with Cmd + K

The latter would then just say 'Switch input and output device'. This one would then also switch the oder device, if possible.

What do you think @mrvkino ?

**Comment by mrvkino** [comment]
Usually, I want to switch both when I want to get on a call with my headset, so it feels more natural to me to request the action and be presented with the list of valid option that support both. (negative: it does add another command)

The sub-action to move both brings questions on what to expect if we select a dedicated input/output. If we select a speaker and move both input and output, where does the input goes to (or does it stays to the current input being used) and vice-versa. 
If there is a way to signal the user the input/output is available for both that could help, but at the cost of visual clutter and cognitive load.

The dedicated command fits more with the intent of moving everything for a purpose in my opinion and is my preferred way with what I mentioned above.

Did that make sense?

**Comment by mrvkino** [comment]
adding a comment to keep this feature request alive
