### ISSUE TITLE
[Bilibili] Show all dynamic video feed

### ISSUE THREAD

**Issue by realCrush** [raycast/extensions#7776]
### Extension

https://www.raycast.com/Fatpandac/bilibili

### Description

The current "show all dynamic feed" feature includes a lot of **text-based feeds**, and some content creators post multiple **repetitive feeds** to increase their exposure. Can we add a feature to only display dynamic **videos** and reduce the distractions?

### Who will benefit from this feature?

All Raycast Bilibili user who want to efficiently get videos posted by the creators they follow.

### Anything else?

Nope.

**Comment by Fatpandac** [comment]
This will be a great addition. I have pushed this feature to my repository. Merging the new feature into the official repository will require some time. If you require the feature immediately, feel free to download and utilize it from my [repository](https://github.com/Fatpandac/Raycast-Bilibili).

**Comment by realCrush** [comment]
Thank you for such a quick fix!
