### ISSUE TITLE
[Notion] Pages not loading

### ISSUE THREAD

**Issue by reflash** [raycast/extensions#7778]
### Extension

https://www.raycast.com/HenriChabrand/notion

### Description

Pages are not loading even though the extension connection has full access
<img width="737" alt="image" src="https://github.com/raycast/extensions/assets/2879985/ae8e648b-4d4d-4582-803e-3414f00b9cd8">

### Steps To Reproduce

There're no specific steps, I just installed the extension and it's not searching for anything

**Comment by thomaslombart** [comment]
Hi @reflash, do you still have the issue?

**Comment by iamyeizi** [comment]
@reflash try to do this https://github.com/raycast/extensions/issues/4158#issuecomment-1507639762

**Comment by reflash** [comment]
> @reflash try to do this [#4158 (comment)](https://github.com/raycast/extensions/issues/4158#issuecomment-1507639762)

that worked! thanks!

**Comment by iamyeizi** [comment]
this comment is now part of the doc 😁
