### ISSUE TITLE
Extension Preferences: Dropdown List with automatic indication of default values

### ISSUE THREAD

**Issue by unnamedd** [raycast/extensions#7779]
### Description

As a developer, I would like to have the option to specify the default value in the dropdown list within the Extension Preferences.

This can be achieved automatically through Raycast without the developer needing to indicate or use an additional property. The type `dropdown`from Preferences properties already has a `default` attribute. Here's an example:

```json
{
  "name": "dropdownListPreferenceName",
  "type": "dropdown",
  "required": false,
  "title": "A Title",
  "data": [
    { "title": "First Option", "value": "first-option" },
    { "title": "Second Option", "value": "second-option" }
  ],
  "default": "second-option" // <---------
}
```

The result would resemble the screenshot below, taken from the built-in extension `Search Emoji & Symbols`:

![CleanShot 2023-08-03 at 11 53 26](https://github.com/raycast/extensions/assets/83694/ab774fbe-e746-4bc2-b10e-73692ed4c1de)

This approach eliminates the need for developers to manually set the default value inside of the text in the option, as shown in the following screenshot:

![CleanShot 2023-08-03 at 12 24 51](https://github.com/raycast/extensions/assets/83694/ab204e21-61e4-4fc4-ab8c-a8ee8bfbb17b)

Alternatively, if the team decides to enhance customization, they can consider the approach used by the `Clipboard History` extension, which offers more flexibility:

![CleanShot 2023-08-03 at 12 31 08](https://github.com/raycast/extensions/assets/83694/68b571e0-2f5a-4c42-aea9-7eb080a7f3d6)

### Who will benefit from this feature?

Extension developers, in general, are increasing the amount of information available for extension customization. Furthermore, users will have more information at hand to decide which option better fits their needs.

**Comment by mathieudutour** [comment]
Good idea, we just shipped it :)
