### ISSUE TITLE
[Google Bard] Unable to connect with servers

### ISSUE THREAD

**Issue by soejrd** [raycast/extensions#7781]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

The current method of using the cookie from visiting bard doesn't work. 

### Steps To Reproduce

Using MacOS 13.4 and Google Chrome I visited bard.google.com.
I then had a quick conversation, opened the required cookie. 
Copied this cookie into the input field.
It'd never be able to connect to the server.

**Comment by thefirebanks** [comment]
Found this now too! Still happening unfortunately :/

**Comment by mickeyeng** [comment]
Still happening. Can't connect.

Steps: 

1. Open Raycast
2. Enter Google session cookie key
3. Test command with Bard Ask AI
4. Bard failed to connect

**Comment by anilakdereli** [comment]
> ### Extension
> https://www.raycast.com/EvanZhouDev/raycast-bard-ai
> 
> ### Description
> The current method of using the cookie from visiting bard doesn't work.
> 
> ### Steps To Reproduce
> Using MacOS 13.4 and Google Chrome I visited bard.google.com. I then had a quick conversation, opened the required cookie. Copied this cookie into the input field. It'd never be able to connect to the server.
> 
> ### Current Behaviour
> _No response_
> 
> ### Expected Behaviour
> _No response_

I encountered the same issue as well. I resolved it by re-completing the necessary steps in Google Chrome without extensions, and it worked.

**Comment by dnet5** [comment]
Same here.

**Comment by EvanZhouDev** [comment]
Please migrate to the PaLM API extension, if you are able to. The Bard extension is no longer stable, and the library powering it, `bard-ai`, is only working now for some people.
