### ISSUE TITLE
Copy notes to clipboard

### ISSUE THREAD

**Issue by eurunuela** [raycast/extensions#7786]
### Extension

https://www.raycast.com/reckoning-dev/zotero

### Description

It would be great if the extension could copy notes to the clipboard in Markdown format to paste into any note-taking app.

**Comment by sadanand-singh** [comment]
Thanks for your comment. I am working on a feature that allows you to edit/add a markdown note to en entry, as well as view the note directly in raycast. Of course you can also copy those to Clipboard.
