### ISSUE TITLE
[System] - Toggle System Appearance not working

### ISSUE THREAD

**Issue by matsechterhoff** [raycast/extensions#7790]
### Extension

https://www.raycast.com/extensions/system

### Description

Using the command Toggle System Appearance seems like it is not working. I checked the extensions tab and made sure the extension is activated. Using the system settings and changing the appearance manually is working. Other commands from the systems extension like eject all disks or lock screen etc. are working.

### Steps To Reproduce

Using the command.

### Current Behaviour

Nothing

### Expected Behaviour

Switch from light to dark mode and vice versa.

**Comment by sergiivelykodnyi** [comment]
I have the same issue when the 'Toggle System Appearance' command does not work, but other system commands work correctly.

**Comment by sergiivelykodnyi** [comment]
Turning System Events on for the Raycast fixed this problem.

Privacy & Security -> Automation -> Raycast

<img width="462" alt="image" src="https://github.com/raycast/extensions/assets/7940800/7a311099-6d7f-4324-bb78-31315668c6ef">

**Comment by korac** [comment]
Thanks @sergiivelykodnyi, this one helped me!

**Comment by ruridge** [comment]
If anyone comes to this in the future, these settings need to be enabled in the **MacOS System Settings**.

"System Events" needs to be enabled for the "Toggle System Appearance" command to work:

<img width="731" height="260" alt="Image" src="https://github.com/user-attachments/assets/177d8854-cb06-4d71-8590-3f57f46f638d" />
