### ISSUE TITLE
[Amazon AWS] No commands are working

### ISSUE THREAD

**Issue by reflash** [raycast/extensions#7792]
### Extension

https://www.raycast.com/Falcon/aws

### Description

This is the error I get - just installed the extension
Error: getaddrinfo ENOTFOUND s3.asd.amazonaws.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)

### Steps To Reproduce

No specific steps, it's just not working
I have a default profile stored in credentials and aws cli is working properly

**Comment by JonathanWbn** [comment]
Hey @reflash, thank you for reporting. I will take a look over the weekend.

**Comment by JonathanWbn** [comment]
Hey @reflash, could you share your **redacted** `.aws/config` and/or `.aws/credentials` file? This would help me reproduce and fix the problem.

**Comment by reflash** [comment]
@JonathanWbn I think the issue could be closed - it was a misconfigured .aws/config. I set a correct region there and it began working
Thanks!

**Comment by JonathanWbn** [comment]
@reflash Cool, thanks for reporting.

@raycastbot close this issue
