### ISSUE TITLE
[Linear] Open in browser failed

### ISSUE THREAD

**Issue by Repomn** [raycast/extensions#7794]
### Extension

https://www.raycast.com/linear/linear

### Description

`Cloudn't open app' pops after I search issues and press enter.

### Steps To Reproduce

1. search isssues
2. select issue
3. press enter
4. pop `Cloudn't open app'

**Comment by thomaslombart** [comment]
Have you uninstalled Linear as a desktop app recently?

**Comment by Repomn** [comment]
@thomaslombart No, I didn't.

**Comment by thomaslombart** [comment]
Do you consistently have this error? Could you share a recording?

**Comment by thomaslombart** [comment]
Since I cannot reproduce it and the issue is becoming stale, I am closing it to maintain a clean backlog. Please feel free to reopen it if you still experience the bug.
