### ISSUE TITLE
[Apple Music] SFSymbols displaying as broken Unicode box character on macOS Ventura

### ISSUE THREAD

**Issue by h3h** [raycast/extensions#7800]
### Extension

https://github.com/raycast/extensions/tree/main/extensions/music

### Description

The quick lozenge notifications from Raycast after an Apple Music function is performed (e.g. Volume Up via keyboard shortcut) show a broken Unicode character box symbol instead of the intended icon, noted in the code as `SFSymbols.SPEAKER_FILL_MINUS`.

This is true for all Apple Music commands (Volume Down, Play/Pause, etc.).

### Steps To Reproduce

1. In macOS Ventura 13.4.1 (c) 
2. Install Raycast latest stable (1.56.0)
3. Install Apple Music extension
4. Record a Hotkey for Apple Music’s _Volume Up_ command
5. Press the hotkey and observe Raycast’s notification content

### Current Behaviour

![music-volume-up](https://github.com/raycast/extensions/assets/1401/c066c135-f247-4f04-adad-9712fc008165)

### Expected Behaviour

It should render a nice speaker icon for _Volume Up_ and the appropriate icons for the various other commands.

**Comment by peterdev22** [comment]
Thanks - this has been a reoccurring issue as I don't think SFSymbols are intended to be used outside of xcode.

A fix for now is to download and install SFSymbols from the [Apple Developer](https://developer.apple.com/sf-symbols/) website. 

I'll submit a pr to remove these symbols very soon.

**Comment by pernielsentikaer** [comment]
This is now resolved
