### ISSUE TITLE
[Script Commands Store] Scripts Break when Folder Moved

### ISSUE THREAD

**Issue by alexclst** [raycast/extensions#7802]
### Extension

https://www.raycast.com/tholanda/script-commands

### Description

When configuring the extension you give it a path for the scripts to live. But if you later move or rename that folder, then all the scripts break, since this store makes aliases to them that will have been broken by the move/rename. How do we re-sync the scripts directory so-to-speak so the extension regenerates all the aliases?

### Steps To Reproduce

1. Set up extension
2. Install a few scripts
3. Move and/or rename the folder you configured scripts to go in
4. Change both the setting for this extension and the main Raycast Script Commands extension
5. Observe that none of the scripts appear
6. Observe that this is due to aliases breaking

### Current Behaviour

After moving and/or renaming the folder all script commands installed by this extension cannot be found.

### Expected Behaviour

That the scripts would still be found. This extension should have a way to regenerate the aliases on-demand.

**Comment by unnamedd** [comment]
Hi @alexclst,

Thank you for reporting this issue! I'm aware of it and I have added it to my list of improvements. Unfortunately, I haven't had much time recently to work on the next version, which will include a fix for this problem.

Currently, I am saving the absolute path in the storage, which is causing the issue you reported. It will be resolved in the next version.

In the meantime, I apologize for the inconvenience, but I have to suggest two possible workarounds:
1. Move it back to the original folder you defined.
or
2. Redo the process using the folder you have in mind.

Once again, sorry for the inconvenience.

**Comment by alexclst** [comment]
@unnamedd Say I wanted to "redo the process" (I assume you mean start fresh with an empty folder at the new location). I can't seem to install scripts I had previously. Even with the files gone the store thinks the script is installed, and the uninstall script then may seem like it works (of course, the script was already gone), but the store doesn't seem to give me the option of downloading the script again. What file would I need to delete to have the store forget all installed scripts?

**Comment by alexclst** [comment]
@unnamedd Ok, so uninstalling and reinstalling the extension erased whatever settings were keeping track of installed scripts so that I could re-install ones I still need in their new home.
