### ISSUE TITLE
Option to set default, favourite devices to run by default.

### ISSUE THREAD

**Issue by krishnaar21** [raycast/extensions#7805]
### Extension

https://www.raycast.com/zcfan/scrcpy

### Description

Right now whenever I run an extension I need to select the device always, is there any way I can set the default device to run to skip device selection each time?

**Comment by zcfan** [comment]
Implemented default selection by moving the dropdown item to the top of the devices list. 😉

**Comment by zcfan** [comment]
@krishnaar21 I didn't provide a "default device" setting, instead I'll always select previous device automatically. I believe this is a better solution than manually specify a default devcie.
