### ISSUE TITLE
[spotify-player] `getUserPlaylists` hard-coded 50 limit

### ISSUE THREAD

**Issue by ad2969** [raycast/extensions#7807]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Is there a reason that this is limited to 50? Is that the Spotify API cap of some sort?
https://github.com/raycast/extensions/blob/e842e281b9a57148f8a824ef757bcda0cceecb87/extensions/spotify-player/src/api/getUserPlaylists.ts#L6C1-L7C1

If it is a limit from the spotify API, I could be interested in contributing to this, maybe having it re-query the libraries during search.

### Who will benefit from this feature?

Anyone (other than me) who has way over 50+ playlists in the Spotify library

**Comment by djpowers** [comment]
I came here via search while checking if this had been reported. I confirmed by cross-referencing the "Liked Songs" playlist in my library that only the most recent 50 tracks are available via the "Your Library" Raycast command.

My thought was also to re-query as the search is made, but it appears both the [Get User's Playlists](https://developer.spotify.com/documentation/web-api/reference/get-list-users-playlists) and [Get Playlist Items](https://developer.spotify.com/documentation/web-api/reference/get-playlists-tracks) API endpoints have the maximum number of items to return limited at 50, and does not provide a way to filter by field.
