### ISSUE TITLE
[Toothpick] Device not disconnecting through the "Disconnect" action

### ISSUE THREAD

**Issue by aichi-t** [raycast/extensions#7811]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

When a bluetooth device is connected and the "Disconnect" action is executed via the return key or selecting "Disconnect" from the list of actions under cmd + k menu, the extension displays "Device disconnected successfully" but the device remains connected.

Bluetooth device: AirPods Pro (first generation)
Raycast version: 1.56.3

<img width="744" alt="image" src="https://github.com/raycast/extensions/assets/49226803/b9b9f2e8-c9c7-48b2-a3c7-d4deeec905e8">

https://github.com/raycast/extensions/assets/49226803/284b8424-828e-484a-9d49-49c5252632ab

### Steps To Reproduce

1. Connect a bluetooth device via menu or toothpick
2. Open "Manage Bluetooth Connections" from Raycast
3. Execute the "Disconnect" action by pressing the return key (or via the action menu in cmd + k)

### Current Behaviour

The bluetooth device remains connected after "Disconnect" action executed

### Expected Behaviour

The bluetooth device should disconnect after "Disconnect" action executed

**Comment by VladCuciureanu** [comment]
So... This issue is known. For some reason, on some devices, disconnecting doesn't work. I tried adding blueutil-compatibility but apparently blueutil doesn't work either. For now I don't know how to fix this issue. Sorry.

You are welcome to looking more in depth into the issue and contribute a fix if you want.

**Comment by VladCuciureanu** [comment]
Otherwise, this is a temporary solution found by another user of this extension:
https://github.com/raycast/extensions/issues/3636

**Comment by VladCuciureanu** [comment]
@raycastbot close this issue

**Comment by VladCuciureanu** [comment]
So, good news (kinda).
#8193
I implemented a compat-layer for 'blueutil' which improves this situation.

1. Install 'blueutil' via brew
2. Update Raycast
3. Update Toothpick
4. Open Toothpick preferences
5. Switch Bluetooth Backend to 'blueutil'

Connecting/disconnecting should be faster and less flaky. Testing was limited so I can't guarantee that it's perfect but, to me, it looks like an improvement :>
