### ISSUE TITLE
[Goodreads] Open in Browser does not work due to Malformed URL

### ISSUE THREAD

**Issue by timelessthee** [raycast/extensions#7813]
### Extension

https://www.raycast.com/puneeth/goodreads

### Description

The URL is malformed when opening a book result in browser, with CMD+Enter or the Actions menu.
An extra 'https://www.goodreads.com' is prepended to the URL, breaking the link and resulting in a page not found.

For example, a search for the book "The Name of the Rose" and selecting the top result, outputs a URL of 
`https://www.goodreads.comhttps//www.goodreads.com/book/show/119073.The_Name_of_the_Rose?from_search=true&from_srp=true&rank=1
`

### Steps To Reproduce

1. Open Raycast 
2. Use the extension by typing Goodreads and typing the name of the book <img width="862" alt="Screenshot 2023-08-06 at 17 41 43" src="https://github.com/raycast/extensions/assets/6428311/b885fd53-e305-4a7a-942e-999198295127">
3. Press CMD+Enter (or use the Actions menu to open in browser)
<img width="862" alt="Screenshot 2023-08-06 at 17 41 51" src="https://github.com/raycast/extensions/assets/6428311/34bd7015-741c-42a6-acf1-905b3e777516">
4. Note the Page Not Found and the malformed URL has an extra "https://www.goodreads.com" prepended to it, breaking the link.

<img width="893" alt="Screenshot 2023-08-06 at 17 41 56" src="https://github.com/raycast/extensions/assets/6428311/03f9b7fe-e6b6-4dbc-83d8-554bd4ea221c">

### Current Behaviour

See 'Steps to Reproduce' above

### Expected Behaviour

For book result to open correctly in Browser

**Comment by shettypuneeth** [comment]
Thanks for reporting @timelessthee. I'll have a fix out soon.

**Comment by pernielsentikaer** [comment]
This is now merged, you can run `Check for Extension Updates` now to see it, otherwise, you'll have it within a few hours 🙂
