### ISSUE TITLE
[LastPass Credentials Search] Error message showing full credentials (security issue bug?)

### ISSUE THREAD

**Issue by jjmss** [raycast/extensions#7818]
### Extension

https://www.raycast.com/alex-popov-tech/lastpass

### Description

I belive I've been signed out or something in the lastpass cli, and when I now tried to do a search I was able to see my master password and email, everything was shown.

### Steps To Reproduce

I'm not quite sure how it happend, but it looked like this:
<img width="716" alt="Skjermbilde 2023-08-06 kl  21 29 00" src="https://github.com/raycast/extensions/assets/59848779/37b79e40-675f-480c-aab6-ef2ff74abb12">

I'm not sure if this is a error message by the lastpass cli or not, but if it is i would assume a possible fix could be to have a regex to remove the password. The place where the password is mentioned looked like this:
&& echo "......" | LPASS_DISABLE_PINENTRY=1
so a regeg looking for echo " and " | LPASS_DISABLE_PINENTRY could maybe work?

### Current Behaviour

The master password and email is being showed. (guess the email is ok)

### Expected Behaviour

Expected the masterpassword atleast to not be shown.

**Comment by alex-popov-tech** [comment]
Hello, @jjmss !

Password is there for debugging purposes, so if you put incorrect password, you will be able to see it there, in error message.

As for your error, can you please check is there email confirmation of usage your credentials from LastPass ? If so, please approve it and try load extension again

**Comment by jjmss** [comment]
I logged in again using lpass login and it worked again.. even if the password is there for debugging, it would be nice to either toggle debugging or something so "again" for people sitting in public or doing live meetings screensharing (as the search worked fine yesterday, so it came as a suprise for me)

**Comment by alex-popov-tech** [comment]
okay, makes sense, i will take into it

**Comment by alex-popov-tech** [comment]
@jjmss Hello! I've created pr addressing your issue #7841
