### ISSUE TITLE
[YouTube Downloader] File Type options not displaying

### ISSUE THREAD

**Issue by Shayanmz** [raycast/extensions#7819]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

Not sure what I'm doing wrong or if I'm missing an install, but the export "File Type" isn't displaying any options.
![CleanShot 2023-08-06 at 16 45 33@2x](https://github.com/raycast/extensions/assets/50340583/be2fb866-5a01-4e7e-8105-fde20182e24e)

### Steps To Reproduce

1. Download the extension
2. Do the default Homebrew install
3. try using it 🤔

**Comment by darmiel** [comment]
I think it has to do with the fact that the video has not yet been fully processed by YouTube. Can you try any other video?

**Comment by Shayanmz** [comment]
@darmiel, ah yea another video worked. You called it - I just pulled the most recent video on my subscriptions, it didn't work with the first few. But it works with any others!

Cheers :)
