### ISSUE TITLE
[Extension Feature Request] Confluence server-side search

### ISSUE THREAD

**Issue by pcatterall7** [raycast/extensions#782]
# Extension – [Confluence Search](https://github.com/raycast/extensions/tree/main/extensions/confluence-search)

Author: @daviddkkim 

#### Describe the feature and the current behavior/state.
Currently, the Confluence API method used returns only the first 25 pages in the Confluence site. Those 25 pages are returned when the the extension loads. Then, entering text in the search field filters those 25 pages client-side and renders the results. As currently implemented, if your Confluence site has more than 25 pages, the majority of the pages will never be searchable.

Instead, entering text in the search field should make an API call that searches for page titles that contain the search string. Then, render the results of that query. Consider using the `GET /wiki/rest/api/search` endpoint ([reference](https://developer.atlassian.com/cloud/confluence/rest/api-group-search/#api-wiki-rest-api-search-get)).

#### Who will benefit with this feature?
Anyone who uses a Confluence space with more than 25 pages.

**Comment by daviddkkim** [comment]
I can tackle this this weekend or if someone else would like, feel free to

**Comment by batmac** [comment]
It would be great! I can help you to test it as much as you want, feel free to tell me!

**Comment by daviddkkim** [comment]
sorry! I dropped the ball on this; should be able to get around to it this weekend!

**Comment by daviddkkim** [comment]
got the PR up !

**Comment by batmac** [comment]
your pr is working fine on my laptop, thank you very much!
