### ISSUE TITLE
[GitLab] Extension doesn't work on multiple computers with Cloud Sync enabled

### ISSUE THREAD

**Issue by emlez** [raycast/extensions#7821]
### Extension

https://www.raycast.com/tonka3000/gitlab

### Description

I installed the GitLab extension on my computer. However, when I tried to install the same extension on my second computer using Cloud Sync, all the data was transferred, but the extension doesn't work on the second computer. I receive the `Error: Error: Unauthorized` error message whenever I try to execute any command.
I'm just not sure how to re-authorize my access for the GitLab extension without re-installing.

### Steps To Reproduce

1. Set up the GitLab extension in first computer as intended.
2. Access a second computer with Cloud Sync and attempt to utilize any GitLab extension commands.
3. Encounter the following error on the second computer: "Error: Error: Unauthorized."

### Current Behaviour

Here's a screenshot from the _Merge Requests Menu Bar_ command:

![Screenshot 2023-08-06 at 9 37 40](https://github.com/raycast/extensions/assets/64607766/f660e356-107f-4160-adc8-75f95368ba82)

And a screenshot from the error prompt in the Projects command:

![Screenshot 2023-08-06 at 9 38 59](https://github.com/raycast/extensions/assets/64607766/efe092a0-371d-4d04-8bb2-87f9a3bce8f8)

### Expected Behaviour

I'd expect it would work without an issue on any of the computers, and Cloud Sync already does a great job sharing the commands I do use and the shortcuts for them.

**Comment by tonka3000** [comment]
@emlez I'm not using cloud sync but AFAIK credentials and passwords are not synced with cloud sync.

You need to set your personal access token in the preferences of the extension again (on the new machine of course) because I assume it is empty on the new machine.

You have 2 options

- Use the original access token (as mentioned in the readme that that token should be stored I a secret box)
- Create a new personal access token by following the section in the readme.

**Comment by emlez** [comment]
@tonka3000, I think there might be a problem with API Tokens when Cloud Sync is enabled. 

On the new machine, I can't find the API Token secret box_(see screenshot)_, but it's visible on the first machine. 
Therefore, I'm not prompted to add a new personal access token on the new machine unless I disable Cloud Sync and reinstall the extension.

However, this would disable Cloud Sync for all my other extensions. So when I turn Cloud Sync back on, the original computer starts receiving the `Error: Error: Unauthorized` message, which causes that machine's extension to stop working.

![Screen Shot 2023-08-07 at 12 57 43](https://github.com/raycast/extensions/assets/64607766/7c61c661-712a-4acd-be3f-1a11948225de)

**Comment by tonka3000** [comment]
Hm strange. As extension developer we do not implement anything to support cloud sync, it works without any work on our side.
The sync is entirely done by Raycast.

@pernielsentikaer @mil3na can you help here?

**Comment by mil3na** [comment]
Hey folks!
This is an error on our side. A fix for cloud sync on extensions will be included in our next release.

**Comment by emlez** [comment]
Closing the issue following the [v1.57.0 update](https://www.raycast.com/changelog/1-57-0). Thanks to everyone for resolving this matter!
