### ISSUE TITLE
[GitHub] Hide Archived repos

### ISSUE THREAD

**Issue by tobbbe** [raycast/extensions#7827]
### Extension

https://www.raycast.com/raycast/github

### Description

Would be nice to exclude archived repos. I cant think of any reason you would want to see them with this extension?
I could make a PR for it 😊

**Comment by thomaslombart** [comment]
Are you talking about the `Search Repositories` command? If so, there's already a preference to remove archived repos from the list called `Include Archived`.

**Comment by tobbbe** [comment]
Oh didnt know that. nice. Unfortunately archived repos still shows up under "Visited Repositories".
What I initially meant was when in `Create Issue` when selecting repo:
![image](https://github.com/raycast/extensions/assets/2511610/cf09a095-6741-429e-b40f-e1b881e1bfea)

**Comment by thomaslombart** [comment]
Ah, I see. Indeed, in this case, the dropdown shows all repositories. I'm wondering if the preference in `Search Repositories` could be moved as a global setting.

**Comment by tobbbe** [comment]
yea that would be nice!
