### ISSUE TITLE
[Arc] SyntaxError: Unexpected token on Search Tabs

### ISSUE THREAD

**Issue by loekbosman** [raycast/extensions#7829]
### Extension

https://raycast.com/the-browser-company/arc

#### Error:
```
SyntaxError: Unexpected token u in JSON at position 6404
    at JSON.parse (<anonymous>)
    at Object.E5 [as current] (/Users/loekbosman/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:87:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

search within tabs

**Comment by pernielsentikaer** [comment]
Hi @loekbosman 👋 

Is there any `weird` characters in your tab names at the moment?

**Comment by loekbosman** [comment]
Are emoji's weird?

**Comment by hugivar** [comment]
@loekbosman  - I wasn't able to reproduce this bug, even with emoji's in the title. Do you have some of your tab titles that I can use to reproduce the error?

**Comment by loekbosman** [comment]
Hi,

I just reinstalled the extension, I instantly get this error.

Some of the tabs open:

**Comment by maurelian** [comment]
I have the same issue: 

#### Error:

```
SyntaxError: Unexpected token  in JSON at position 7650
    at JSON.parse (<anonymous>)
    at Object.E5 [as current] (/Users/maurelian/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:89:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I have a ton of tabs (that's what Arc is for after all), but I looked for weird characters, and closed a lot of tabs and cannot get it to work. 

I did notice the the position number given seems to _always_ decrease when I close a tab, which suggests to me that the unexpected token is at the end.

How would one go about getting this JSON string out?

**Comment by maurelian** [comment]
Maybe someone could update the title of this issue to make it more descriptive? Would help me to find and check-in on it occasionally.

**Comment by pernielsentikaer** [comment]
Do you know how to Fork an extension @maurelian? If so you should be able to `npm run dev` and find the location in the code
