### ISSUE TITLE
[Extension Feature Request] Unlocking a locked vault

### ISSUE THREAD

**Issue by antony-frolov** [raycast/extensions#783]
# Extension – [1Password7](https://github.com/raycast/extensions/tree/main/extensions/1password7)

Author: @khasbilegt

The idea is to prompt the user to unlock the vault if it is locked.
Currently 'View in 1Password' doesn't work for a locked vault.
It is the default behaviour of Alfred 1Password extension, so this feature should be possible.

**Comment by tdwesten** [comment]
Hi @antony-frolov any idea how this works for alfred?

**Comment by tdwesten** [comment]
@antony-frolov I took a look... but found nothing...
