### ISSUE TITLE
Quicklinks user input transform?

### ISSUE THREAD

**Issue by isaaclem90** [raycast/extensions#7840]
### Description

Hi thanks for this awesome tools!

I am wondering if currently it's possible to apply any form of transform to quicklinks?

For instance I would setup my quicklink to be `https://foo.com/{version}.json`

sample value for `version` would be `v1.1` but the final url should be `https://foo.com/v1-1.json`

It would be nice if we can also set some transform rules when we are defining the url, something like `https://foo.com/{url: \. -> -}.json`

### Who will benefit from this feature?

It will increase flexibility and open rooms for more users

**Comment by mathieudutour** [comment]
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
