### ISSUE TITLE
[Obsidian] keeps saying "Advanced URI plugin not installed" but it is

### ISSUE THREAD

**Issue by benvenker** [raycast/extensions#7844]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

I get the below message every time I try to use the Append to Daily Note action
![CleanShot 2023-08-08 at 05 09 10](https://github.com/raycast/extensions/assets/4605817/353543b8-54d1-4ce4-ae2a-76079e33e423)

## System and Raycast Version
- MacBook Air M2, MacOS 13.5
- Raycast v1.56.3

## Steps
- Open Raycast
- Trigger Obsidian append to daily notes action
- See message in screenshot above

### Current Behaviour

I get the message that Advanced URI plugin is not installed

### Expected Behaviour

Since I have the Advanced URI plugin installed, I expect not to see this message and for the task to append to the daily note under the specified heading.

**Comment by KevinBatdorf** [comment]
Can you check what is in the community-plugins.json? Check where your `Personal` vault is.

For me, mine is `/Users/kevin/code/brain`, so
```
cat /Users/kevin/code/brain/.obsidian/community-plugins.json`
```

![Screen Shot 2023-08-08 at 12 48 35 PM](https://github.com/raycast/extensions/assets/1478421/1b953903-b895-4592-be9c-e1b9abfd196c)

The extension checks that file to determine whether the plugin is installed or not. 

If it is there, then it might be harder to debug, but lets see.

**Comment by benvenker** [comment]
Here you go. It's second on the list:
![2023-08-09 - 06 47 48 - screenshot](https://github.com/raycast/extensions/assets/4605817/cd85627d-f3f5-4916-b635-2f25cdff159a)

**Comment by KevinBatdorf** [comment]
The code that does the check will look for the directly, then check the contents. One of those two are failing here for some reason. Here's the function (truncated - full version [here](https://github.com/KevinBatdorf/obsidian-raycast/blob/main/src/utils/utils.tsx#L69))

```js
const communityPluginsPath = vault.path + "/.obsidian/community-plugins.json";

if (!fs.existsSync(communityPluginsPath)) {
  // show error message
} else {
  const plugins: string[] = JSON.parse(fs.readFileSync(communityPluginsPath, "utf-8"));
  if (plugins.includes(plugin)) {
    // success
  } else {
    // show error
  }
}
```

Your output and file name look correct. Maybe the permissions on that file prevent the read? Or something is wrong with the vault name. 

If you're willing, could you build the extension ([from here is easiest](https://github.com/KevinBatdorf/obsidian-raycast)) then just sprinkle some console logs and see what is going on? You might even have an error in the console already.

If you're new to Raycast development, you just clone the repo, run `npm ci`, then `npm run dev` and it will start the server and pop open the extension. It's really simple.

**Comment by marcjulianschwarz** [comment]
Looks like the vault name was detected as “/Personal” which doesn’t seem right (see the prepended slash). 

@benvenker is your vault automatically detected by the extension or did you add a path in the settings?

**Comment by benvenker** [comment]
@marcjulianschwarz looks like that did the trick, thanks! @KevinBatdorf thanks for your suggestions as well, appreciate the tip on where to build the plugin from source.

One thing I ran into after getting this working was it not being able to find the heading, which I figured out, but it wasn't obvious that I should only put in the heading name and not the level. Let me know if I could help out by submitting a docs PR. Thanks!

**Comment by KevinBatdorf** [comment]
> Let me know if I could help out by submitting a docs PR. Thanks!

Absolutely! Can do it on the repo here: https://github.com/KevinBatdorf/obsidian-raycast

Or otherwise on the extensions repo directly. 

Also, can open an issue first if unsure about anything too (or chat about it in the PR)
