### ISSUE TITLE
[1Password] Support for retrieving the primary one-time password for an item

### ISSUE THREAD

**Issue by davidski** [raycast/extensions#7847]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Thank you very much for this handy extension! I'd very much like a command to get the primary one-time password (when configured) for an item. In the 1password CLI (`op`), this can be retrieved via syntax like: `op item get REDACTED --otp`.

### Who will benefit from this feature?

When using the extension for filling in popups, OTP codes can be coped and pasted (my primary use case for the extension).

**Comment by CyberDuck79** [comment]
same request, the extension is useless without this feature, I use the 1password quick access instead of raycast.

**Comment by davidski** [comment]
Trying one more ping on this before giving up on this extension. Is there a maintainer available to help resolve this very useful feature?

**Comment by nesl247** [comment]
This is still needed.
