### ISSUE TITLE
[GitHub] Custom color for menu bar icon color

### ISSUE THREAD

**Issue by asportnoy** [raycast/extensions#7851]
### Extension

https://www.raycast.com/raycast/github

### Description

The orange color in my theme (Dracula) does not look very good in my menu bar:
![Screenshot 2023-08-08 at 15 39 27](https://github.com/raycast/extensions/assets/14863373/16008b42-5e56-4f81-9772-2d5b7dbc2863)

Could you add an option to have a custom tint color? Either a pick of one of the other theme colors, or just a regular color picker field.

### Who will benefit from this feature?

Users of Raycast themes

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by megaroeny** [comment]
@thomaslombart @asportnoy I think a simpler approach would be to have it toggle between a light/dark icon depending on the OS appearance theme. Right now I am using a dark menu bar, and it's hardly visible:

![image](https://github.com/raycast/extensions/assets/1559447/f41fd929-aa00-44bb-bf56-74b4b01bb016)

**Comment by thomaslombart** [comment]
@megaroeny It's actually another command we're talking about. Your issue should have been fixed now with this change: https://github.com/raycast/extensions/commit/cb646dc6e83d330a45e8a245e3c2e26c0956cf0d.

**Comment by asportnoy** [comment]
Don't close
