### ISSUE TITLE
[Music]: 

### ISSUE THREAD

**Issue by augustofretes** [raycast/extensions#7852]
### Extension

https://raycast.com/fedevitaledev/music

### Description

Command failed with exit code 1: osascript -e tell application "Music" to set loved of current track to true 
28:62: execution error: Music got an error: A descriptor type mismatch occurred. (-10001)

### Steps To Reproduce

1. Create or a play a song in a station
2. Try to set the song to loved 

### Current Behaviour

Also, adding a song to your library takes a while after hitting enter.

**Comment by octoxan** [comment]
Can replicate this as well, started my normal station and tried to love a song. I am on Sonoma Beta though. 

@augustofretes what version of macOS are you on?

Attached full stack trace:
```
Error: Command failed with exit code 1: osascript -e tell application "Music" to set loved of current track to true 
28:62: execution error: Music got an error: A descriptor type mismatch occurred. (-10001)
    at makeError (/Users/xan/.config/raycast/extensions/music/love.js:5425:17)
    at handlePromise (/Users/xan/.config/raycast/extensions/music/love.js:6192:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runAppleScript (/Users/xan/.config/raycast/extensions/music/love.js:7649:22)
```

**Comment by augustofretes** [comment]
I'm on Sonoma Beta as well.

**Comment by rawnly** [comment]
if you're curious have a look at #6988

**Comment by rawnly** [comment]
@augustofretes or @pernielsentikaer can we please update the issue title in order to avoid duplicates?

**Comment by rawnly** [comment]
@raycastbot close this issue
