### ISSUE TITLE
[Menubar Weather] ...

### ISSUE THREAD

**Issue by Antinino** [raycast/extensions#7853]
### Extension

https://www.raycast.com/koinzhang/menubar-weather

### Description

![SCR-20230809-fu7](https://github.com/raycast/extensions/assets/12130807/b07b396d-13e0-4b24-a5de-be7273a30c30)
![SCR-20230809-g27](https://github.com/raycast/extensions/assets/12130807/4e41da02-8ded-4551-b0c1-b250a9b3128e)
It seems normal in the setting. I can see the last refresh time, but it just shows "no weather info, try again later" on the menubar.
I've tried restarting raycast, the extension, network and even my mac, yet nothing changed.

macOS 12.6 (21G115) 

### Steps To Reproduce

macOS 12.6 (21G115) 
Raycast 1.56.3
menubar weather is the latest version

**Comment by koinzhang** [comment]
Hi @Antinino. Have you tried uninstalling and reinstalling this extension? Maybe it's due to some internal cached key changes that need to be cleared from the extension cache.

**Comment by Antinino** [comment]
> Hi @Antinino. Have you tried uninstalling and reinstalling this extension? Maybe it's due to some internal cached key changes that need to be cleared from the extension cache.

It works after reinstalling! THX for the reply.
