### ISSUE TITLE
[Set Audio Device] Shows no results when Include AirPlay devices is on in settings

### ISSUE THREAD

**Issue by RvRoo** [raycast/extensions#7868]
### Extension

https://www.raycast.com/benvp/audio-device

### Description

When I toggle on `Include AirPlay devices` the "Set Output Device" command shows no results.

### Steps To Reproduce

1. Go to "Set Audio Device" extension settings
2. Check the `Include AirPlay devices` box
3. Run "Set Output Device" command

**Comment by roelvangils** [comment]
I hope this gets updated! 🤞🏼

**Comment by jkp** [comment]
Same issue here on my M1 MBP.
