### ISSUE TITLE
Unable to install any extensions - Failed to Download Dependencies, reinstalling doesn't work

### ISSUE THREAD

**Issue by C0deZLee** [raycast/extensions#7869]
### Extension

https://www.raycast.com/GastroGeek/folder-search

### Description

<img width="651" alt="image" src="https://github.com/raycast/extensions/assets/7098849/e9ecc28e-1b5e-4ca5-a8d4-ea92b941f6bd">

- 

### Steps To Reproduce

1. Install raycast
2. Try to install extensions

**Comment by omarshahine** [comment]
Just this extension or all extensions?
