### ISSUE TITLE
[Speedtest] ...

### ISSUE THREAD

**Issue by kyellareddy** [raycast/extensions#7872]
### Extension

https://www.raycast.com/tonka3000/speedtest

### Description

There should be an option to open the result link directly.

**Comment by pernielsentikaer** [comment]
Hi @kyellareddy 👋 

This is already possible when the test is done, hit  ⌥+enter

![speedtest 2023-08-10 at 09 01 53](https://github.com/raycast/extensions/assets/38033107/4f5ca8f6-a396-40b1-b216-c75870795880)
