### ISSUE TITLE
[GitHub] More Configuration Options for Menu Bar Commands

### ISSUE THREAD

**Issue by p0fi** [raycast/extensions#7883]
### Extension

https://www.raycast.com/raycast/github

#### Current Situation
The menu bar commands (My Pull Requests, Open Issues, Unread Notifications) have very limited configuration options. Basically the only thing you can configure right now is the maximum number of items (see picture)
<img width="307" alt="CleanShot 2023-08-10 at 11 05 51@2x" src="https://github.com/raycast/extensions/assets/6141293/d8cc3486-84b6-436c-8511-a08d6ac83fee">

#### Proposal
Add more configuration options like **which repositories to include** in the menu bar items for issues/PRs/Notifications

### Who will benefit from this feature?

Everyone who is using GitHub and Raycast on different machines like work and private. 

It would be very useful to only see work related issues/PRs/notifications when on a work machine and only private ones when on a private machine.

**Comment by thomaslombart** [comment]
Unfortunately, including the repositories isn't feasible as a configuration option because they are only static choices.

**Comment by p0fi** [comment]
Is there any other way to limit the menu bar commands to specific repositories?

**Comment by thomaslombart** [comment]
I don't see any other way unfortunately.
