### ISSUE TITLE
[Amazon AWS] Secrets Manager (incorrect region when opening in browser)

### ISSUE THREAD

**Issue by reflash** [raycast/extensions#7885]
### Extension

https://www.raycast.com/Falcon/aws

### Description

I'm opening Secrets Manager command to list all my secrets - that's working fine and all of them are listed properly
When I try to open a secret in a browser to edit it I get navigated to the following link
https://eu-north-1.console.aws.amazon.com/secretsmanager/secret?name=<secret-name>&region=eu-west-1#

As you can see region is eu-west-1 in params, but somehow it queries eu-north-1 instead - so the page says secret not found

### Steps To Reproduce

1. Open Secrets Manager command
2. Select a secret
3. Open Secret

### Current Behaviour

Opens https://eu-north-1.console.aws.amazon.com/secretsmanager/secret?name=<secret-name>&region=eu-west-1#

### Expected Behaviour

Should open https://eu-west-1.console.aws.amazon.com/secretsmanager/secret?name=<secret-name>&region=eu-west-1#

**Comment by JonathanWbn** [comment]
@reflash I prepared a PR (https://github.com/raycast/extensions/pull/7936). Would you mind checking if this works?

**Comment by reflash** [comment]
> @reflash I prepared a PR (#7936). Would you mind checking if this works?

yep, tried it out on my local machine - works perfectly 😄 
Thanks!
