### ISSUE TITLE
[Bitwarden Vault] "Something went wrong" – ERR_DLOPEN_FAILED

### ISSUE THREAD

**Issue by BlueBlindBoy** [raycast/extensions#7893]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

I'm getting the "Something went wrong" screen when I try and search my vault. I recently switched from an intel mac to apple silicon, and reading the error leads me to believe I made a mistake while transferring data. Any help would be appreciated.

**Error:**
```
Error: Command failed with exit code 1: /usr/local/Cellar/bitwarden-cli/2023.7.0/bin/bw lock
node:internal/modules/cjs/loader:1338
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/usr/local/Cellar/bitwarden-cli/2023.7.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/argon2/lib/binding/napi-v3/argon2.node, 0x0001): tried: '/usr/local/Cellar/bitwarden-cli/2023.7.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/argon2/lib/binding/napi-v3/argon2.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/bitwarden-cli/2023.7.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/argon2/lib/binding/napi-v3/argon2.node' (no such file), '/usr/local/Cellar/bitwarden-cli/2023.7.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/argon2/lib/binding/napi-v3/argon2.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/local/Cellar/bitwarden-cli/2023.7.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/argon2/argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.16.0

node:internal/modules/cjs/loader:1338
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
```

### Steps To Reproduce

1. Install extension
2. Install bitwarden-cli via homebrew
3. Enter client ID, client secret, and CLI path
4. Run "Search Vault" Command

### Current Behaviour

"Search Vault" command produces "Something went wrong" screen, meanwhile the other commands fail to run.

### Expected Behaviour

Commands should run.

**Comment by jomifepe** [comment]
Hello, did you by any chance use the macOS migration tool or something to transfer existing software (like NodeJS) from the Intel to the M1 Mac?

**Comment by BlueBlindBoy** [comment]
Yes, I used Migration Assistant to transfer the "documents and data" category, which likely also migrated an incompatible version of NodeJS.

`node -p "process.arch"` outputs `x64`

**Comment by jomifepe** [comment]
> Yes, I used Migration Assistant to transfer the "documents and data" category, which likely also migrated an incompatible version of NodeJS.
> 
> `node -p "process.arch"` outputs `x64`

Yeah, that is likely the culprit, try to reinstall Node version that supports ARM64 architectures and (maybe) the Bitwarden CLI again.

**Comment by BlueBlindBoy** [comment]
Homebrew was also transferred, and existed as if it were on an intel machine. Consequently, every time I attempted to  reinstall node, Homebrew installed the x86 version. After removing Homebrew and reinstalling properly, it fixed the issue. 

Thank you for helping me fix my user error.

**Comment by jomifepe** [comment]
No worries, happy it's working now 🚀
