### ISSUE TITLE
[Authy] Waiting without a specific deadline in the search state.

### ISSUE THREAD

**Issue by 2SANGIN** [raycast/extensions#7895]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

![image](https://github.com/raycast/extensions/assets/11793706/486949e0-c426-4bb1-86ec-efcc613dafe6)

In the above state, even if I wait indefinitely, the list does not appear.

I am using two MacBooks, and Raycast settings are being synchronized.
When I reset on one device and enter the backup password, then try, the OTP list appears. However, it seems that it does not function properly on the other device as shown in the screenshot above.

Thanks

### Steps To Reproduce

1. Set up on the first PC -> Verify normal operation when using the auth extension.
3. Attempt to use the authy extension on the second PC -> The list is not visible.

**Comment by guga4ka** [comment]
Hey @2SANGIN thx for report issue. Unfortunately i do not use cloud sync and do not have a second mac to reproduce the issue. Root-cause might be a time of sync, i use a local storage to cache some data needed to authorisation and OTPs itself. @pernielsentikaer do you know what exactly cloud sync is syncing? Does it sync extensions's local storage?
