### ISSUE TITLE
Cannot search for tabs

### ISSUE THREAD

**Issue by maxiim3** [raycast/extensions#7902]
### Extension

https://raycast.com/the-browser-company/arc

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    on escape_value(this_text)
      set AppleScript's text item delimiters to the "\""
      set the item_list to every text item of this_text
      set AppleScript's text item delimiters to the "\\\""
      set this_text to the item_list as string
      set AppleScript's text item delimiters to ""
      return this_text
    end replace_chars

    set _output to ""

    tell application "Arc"
      set _window_index to 1
      set _tab_index to 1
      
      repeat with _tab in tabs of first window
        set _title to my escape_value(get title of _tab)
        set _url to get URL of _tab
        set _location to get location of _tab
        
        set _output to (_output & "{ \"title\": \"" & _title & "\", \"url\": \"" & _url & "\", \"windowId\": " & _window_index & ", \"tabId\": " & _tab_index & " , \"location\": \"" & _location & "\" }")
        
        if _tab_index < (count tabs of first window) then
          set _output to (_output & ",\n")
        else
          set _output to (_output & "\n")
        end if
        
        set _tab_index to _tab_index + 1
      end repeat
    end tell
    
    return "[\n" & _output & "\n]"
   
466:1105: execution error: Not authorised to send Apple events to Arc. (-1743)
    at r_ (/Users/maxi/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:53:57)
    at /Users/maxi/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:53:8079
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D1 (/Users/maxi/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:53:41514)
    at async Object.E5 [as current] (/Users/maxi/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:53:41593)
```

### Steps To Reproduce

1. In MacOS 13 on MBP m1
2. Open raycast and launch the 'search tabs' action
3. An error occures with the message in the description

**Comment by danulqua** [comment]
@maxiim3 Hi Maxiim,

Can't reproduce the issue. On my end everything works fine.

Make sure you are using the latest Arc Browser and Arc extension versions (Raycast → Check For Extension Updates).

Also, try reinstalling Arc extension.

**Comment by maxiim3** [comment]
I am using the latest Arc version. Alright, i'll try again.

**Comment by maxiim3** [comment]
Hi and sorry for answering only now...

So i installed Arc extension again.
I am up to date on my MacOS, Raycast and Raycast' extensions.
I only have the ability to use the action `Search History` and `Search Arc`, which are working fine :
- I can browse the history and it will open the selected tab in a new little arc window.

When using `Open New Window` or `Open New Tab`, I got an error message (See the video bellow)
When using `Access Spaces and Favorite` or `Search Tabs` I got a `Failed to fetch latest data` error. (See also the video)

https://github.com/raycast/extensions/assets/93276593/f66efb09-78a1-47cb-8a9c-55652c6a95b7

Best regards

**Comment by gavin-burns-US** [comment]
✅  **Resolved on my machine after a few weeks of frustration** 

**First and Foremost**: Enable Accessibility: Open "System Settings" > "Privacy & Security" > "Accessibility". Ensure Raycast is toggled.

**Solution**: 
- Automation Permissions: Similarly, go to "System Settings" > "Privacy & Security" > "Automation". Ensure Raycast  has permission to control Arc (which it does not).

<img width="487" alt="image" src="https://github.com/raycast/extensions/assets/118209746/54509e7f-87e1-45c7-a90a-77a1370f98bf">


> Issue needs to be resolved by a config of sorts, requesting permissions from user upon first command run


🔔 @thomaspaulmann @pomdtr @zach-fuller @ankitchouhan1020 @pernielsentikaer @danpalmer @hugivar @danulqua

**Comment by maxiim3** [comment]
Hi !
Thank you for the answer.
- _First and Foremost: Enable Accessibility: Open "System Settings" > "Privacy & Security" > "Accessibility". Ensure Raycast is toggled._ 👉 It was already checked. Raycast suggests it when loading for the first time.
- _Automation Permissions: Similarly, go to "System Settings" > "Privacy & Security" > "Automation". Ensure Raycast has permission to control Arc (which it does not)._ 👉 I didn't knowthis one !
So i toggled Arc in "System Settings" > "Privacy & Security" > "Automation", and it actually fixed a part of the problem.
- I am now able to `Access Spaces and Favorite`,` Open New Window`,  `Open New Tab`.
- But **I still cannot use** `Search Tabs`.


<img width="613" alt="CleanShot 2023-09-18 at 09 49 23@2x" src="https://github.com/raycast/extensions/assets/93276593/a4b82857-d6f0-443d-bc08-111888c3c3ae">

Here is the new Error i get :

#### Error:
```
SyntaxError: Unexpected token   in JSON at position 23031
    at JSON.parse (<anonymous>)
    at Object.E5 [as current] (/Users/maxi/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:87:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
