### ISSUE TITLE
[Library Genesis] ...

### ISSUE THREAD

**Issue by Macinate** [raycast/extensions#7908]
### Extension

https://www.raycast.com/yz3440/library-genesis

### Description

Getting error with: TypeError: p.replace is not a function
<img width="862" alt="New Issue · raycastextensions" src="https://github.com/raycast/extensions/assets/115506918/15e859de-3d07-4261-89f6-298815cc80b4">

### Steps To Reproduce

1. search for a book
2. receive error: TypeError: p.replace is not a function

### Current Behaviour

TypeError: p.replace is not a function

### Expected Behaviour

Seeing book results based on search

**Comment by yz3440** [comment]
@Macinate I just looked into it. I couldn't reproduce it so it's probably dependent on the user's access to the mirrors. It seems to me like the built-in mirror urls is probably no accessible on your end. The built-in ones are: http://gen.lib.rus.ec and http://libgen.is . Can you let me know if you can access either of both?

**Comment by Macinate** [comment]
Seems to be resolved.. Thank you. Cheers!

—
Raymond Massey
(703) 408-1500
