### ISSUE TITLE
Pinned items in clipboard manager

### ISSUE THREAD

**Issue by JosephTLyons** [raycast/extensions#791]
I've been using [Maccy](https://maccy.app) as my clipboard manager for some time now - one of its best features is the ability to pin items in your clipboard that you want to have around indefinitely.  I think this would be an excellent feature for Raycast's clipboard manager.

**Comment by es183923** [comment]
First, feature requests not specific to extensions should be posted in the [Slack community](https://raycast.com/community). Second, this feature already exists.

<img width="862" alt="Screen Shot 2022-02-02 at 10 15 26 PM" src="https://user-images.githubusercontent.com/72744903/152275717-46edede9-ec94-4fa1-a6fd-2a78aff6c5be.png">

**Comment by JosephTLyons** [comment]
Thanks for the info!  I'll close and use Slack going forward.
