### ISSUE TITLE
Volume control with Spotify Controls

### ISSUE THREAD

**Issue by sidbena** [raycast/extensions#792]
### Extension – [Spotify Controls](https://github.com/raycast/extensions/tree/main/extensions/spotify-controls)
**Author:**
@thomaspaulmann

**Describe the feature and the current behavior/state.**
I would like to be able to control Spotify's internal volume from the keyboard too.
This can be done with AppleScript too, for example:
```
tell application "Spotify"
	set sound volume to 50
end tell
```
or
```
tell application "Spotify"
	set sound volume to (sound volume - 10)
end tell
```
I would love five built-in presets available (the value goes from 0 to 100):
- 0 (mute)
- 50
- 100 (full)
- volume up (in 10 increments)
- volume down (in 10 decrements)

**Who will benefit with this feature?**
Any user wanting to control more of Spotify's feature set through the keyboard.

**Any Other info.**
Thanks in advance!

**Comment by thomaspaulmann** [comment]
@sidbena how about adding it yourself? The source code is [here](https://github.com/raycast/extensions/tree/f7ebc9bfac2fa17a41f356c5cdf823019ea234e4/extensions/spotify-controls/).

**Comment by sidbena** [comment]
@thomaspaulmann: I'm sorry, I but I'm not sure how. I've done some scripting before, but I've never coded anything for an already existing extension, let alone done much git stuff to ”real” repos. Is there a guide to this or a similar scenario?
