### ISSUE TITLE
[Man Pages] Search inside the result. 

### ISSUE THREAD

**Issue by interfan7** [raycast/extensions#7927]
### Extension

https://www.raycast.com/HelloImSteven/man-pages

### Description

Ideally - allows searching in a similar manner to Linux vim style (i.e. pressing "/" starts search promt), but a generic way such as a hotkey or simple character in Raycast typing box would be about as good.

Frankly, without that, I don't really find a value in this extension because a terminal window is always open anyway, so I switch to it with CMD+tab (or Raycast) and just type
`man {entry}`.
Maybe there are benefits I'm not aware of though.

### Who will benefit from this feature?

People who are not too experienced with man in Linux-style terminals.
Developers and IT who are used to Raycast so much that they prefer Linux commands lookup in Raycasr rather than a terminal. 

### Anything else?

If you decide to create a man from Linux system rather than Mac, that can also benefit technical users who don't have instant connection to a Linux system or don't have a complete man resource over there.

**Comment by SKaplanOfficial** [comment]
There isn't really a good way to do this with the API that Raycast provides (can't scroll to a position within Detail view, no built-in search dialog component, etc.).

Would being able to do a full-text search from the initial list view be sufficient for your needs?

In general, the extension is mostly for quick lookup when the terminal isn't open. I myself still use `man` from the terminal when it's more convenient, and I use the Raycast extension when answering questions, when I'm in an interactive program and don't want to waste time opening another tab, etc.

**Comment by interfan7** [comment]
Thanks for elaborating @SKaplanOfficial.

Elaborating the Raycast API limitation and the intended usage of this extension, I'm satisfied. 

I may find it useful for reading the 1st lines of a command (e.g. usage) etc...
