### ISSUE TITLE
[ChatGPT] UI glitch when asking a question in a conversation in Full-text mode

### ISSUE THREAD

**Issue by romatou** [raycast/extensions#7928]
### Extension

https://www.raycast.com/abielzulio/chatgpt/changelog

### Description

I have been using RayCast because of ChatGPT extension mostly and have encountered a glitch from the very beginning. I tried reinstalling the app 3 times but each time I get the same problem and it gets hard to communicate with ChatGPT in a conversation specifically (becuase the first question works fine, so does it work okay when not expanding the text input). I have posted screen recording with the glitch on [Reddit](https://www.reddit.com/r/macapps/comments/15lc1u9/has_anyone_encountered_such_glitch_in_raycast/). 

### Steps To Reproduce

1. On macOS Ventura 13.5 install RayCast
2. Install ChatGPT extension
3. Open the extension and insert OpenAI API key
4. Ask the first question
5. Open full-text input and ask another question and press enter

### Current Behaviour

View is jumping between latest and previous question indefinitely. If to click on the latest question twice it will stop jumping, but sometimes the RayCast window just closes.

### Expected Behaviour

Should not jump

**Comment by Nov19** [comment]
I know hot to fix this... just double-click the tab of the last question at the left of the Raycast window.

**Comment by romatou** [comment]
> I know hot to fix this... just double-click the tab of the last question at the left of the Raycast window.

That is what I do when need to see the answer to my question. Preferably not to have this glitch at all. So, @Nov19, I believe I'm not the only one who has this glitch?

**Comment by Nov19** [comment]
> > I know hot to fix this... just double-click the tab of the last question at the left of the Raycast window.
> 
> That is what I do when need to see the answer to my question. Preferably not to have this glitch at all. So, @Nov19, I believe I'm not the only one who has this glitch?

Of course, you're not the only one XD. The glitch randomly occurs once in a while...
