### ISSUE TITLE
[PostHog] Issues with handling multiple Projects

### ISSUE THREAD

**Issue by Biszu** [raycast/extensions#7929]
### Extension

https://www.raycast.com/david_newell/posthog

### Description

I have separate projects for managing Dev/Prod environments (as described on https://posthog.com/tutorials/multiple-environments).
After quickly trying out the extension, I found issues with Search Persons and Feature Flags.

@daibhin 

### Steps To Reproduce

1. Create >=2 projects in Posthog
2. Add some users and feature flags with the same names to all projects
3. Set up Raycast extension
4. Search for a Feature Flag
5. Search for a Person

### Current Behaviour

4. Feature flags from only one project are shown (in my case, it's the first Project on the list).
If on posthog.com another project is active, opening any result targets the other project, leading to error "Feature flag not found"

5. Only Persons from the first project are shown in the results. Searching for a person from other projects yields no results.

### Expected Behaviour

Search works across all Projects.
Feature Flags and Persons displayed in Raycast have information about the Project they belong to.
Opening them switches the active Project on posthog.com, and the selected flag/person is correctly displayed.

**Comment by daibhin** [comment]
Thanks for reporting your issue @Biszu! Let me take a look and try to find the root cause

**Comment by Biszu** [comment]
Bump

**Comment by Biszu** [comment]
@daibhin This extension is abandoned, isn't it?
