### ISSUE TITLE
[Ollama AI] I'd like a chat like interface

### ISSUE THREAD

**Issue by sebastiennoir** [raycast/extensions#7930]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

The current online "ask Ollama" is great for a short sentence request. I'd like a bigger UI (like to one from chat-gpt) offering a list of interactions (request / response). 

### Who will benefit from this feature?

All users. As soon as you'd like to tweak your prompt, copy/paste parts of it.

**Comment by MassimilianoPasquini97** [comment]
Hi @sebastiennoir,

I'm currently working on a major update with those features:

- New command **Chat with Ollama**: an interactive chat (request / response) with possibility to save multiple conversation and resume them.
- New command **Create Custom Command**: an easy way for create custom commands with quicklinks.
- New command **Manage Models**: where you can view installed models, delete them and install new ones.

I'm just finished to develop this new features, soon will be available throw store. You can track progression on repository [raycast_ollama](https://github.com/MassimilianoPasquini97/raycast_ollama)

**Comment by sebastiennoir** [comment]
Excellent news! 
I'll be very happy to try it as soon as it's released!!

**Comment by MassimilianoPasquini97** [comment]
Hi @sebastiennoir, all requested features will be available after this #7940 merge request.

**Comment by MchLrnX** [comment]
It looks like this is live but I'm running into an issue where after four or five messages history is all but lost and the models (regardless of model) typically starts responding with the same thing again and again.  Can anyone help?

**Comment by MassimilianoPasquini97** [comment]
@MchLrnX This is a limitation of the context length of all models, they default to 2048, you can increase this value to 4096 with a custom [model file](https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md).
