### ISSUE TITLE
[OpenWeatherMap] Could not fetch data from OpenWeatherMap

### ISSUE THREAD

**Issue by foss-** [raycast/extensions#7932]
### Extension

https://www.raycast.com/tonka3000/openweathermap

### Description

Data is not fetched despite using an API key

### Steps To Reproduce

1. add default location and API key to OpenWeatherApp extension.
2. open weather

### Current Behaviour

request to https://api.openweathermap.org/geo/1.0/direct? appid=APIKEY_HERE&g=DEFAULT_LOCATION_HERE
failed, reason: connect EBADF 82.196.7.246:443

### Expected Behaviour

Query should return result.

**Comment by tonka3000** [comment]
@foss- which version of Raycast do you use? Which MacOS version do you use?

**Comment by foss-** [comment]
Should have put that in the initial report, sorry.
macOS 13.5
Raycast 1.57.1

**Comment by tonka3000** [comment]
@foss- Solved?
