### ISSUE TITLE
[Toggl Track] Time tracking for tasks

### ISSUE THREAD

**Issue by renehlavova** [raycast/extensions#7933]
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Description

It is not possible to track time per task on projects. It would be helpful to have to possibility to select project and then pick a task from a list of tasks (could be optional). 

It should be possible: https://developers.track.toggl.com/docs/api/tasks

### Who will benefit from this feature?

Anyone tracking time per multiple clients / projects which can have different tasks. It is sometimes needed to hand to clients or to connect these entries with a kanban board.

### Anything else?

I can help create a PR.

**Comment by franzwilhelm** [comment]
Cool @renehlavova pls do open a PR and I'll review it :)
