### ISSUE TITLE
[Jira] Search Issues setting for default project key 

### ISSUE THREAD

**Issue by iltimasd** [raycast/extensions#7951]
### Extension

https://www.raycast.com/raycast/jira

### Description

Currently the Search Issues requires the project key to search by issue key. Often I'm working in only one project for an extended period of time, and it would be helpful to input just numbers that follow the project key.

**Comment by iltimasd** [comment]
related #7543

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by iltimasd** [comment]
Sure!
