### ISSUE TITLE
[Easy Dictionary] ...

### ISSUE THREAD

**Issue by geekerzhou** [raycast/extensions#7957]
### Extension

https://www.raycast.com/isfeng/easydict

### Description

"search word" lose optional argument. it's not working on mac pro 14 m2

### Steps To Reproduce

1. type "Search world + tab + ${query}"
2. enter command, ${query} word lose, you have to type word again

**Comment by tisfeng** [comment]
Hi, I've tested this many times and I can't reproduce the problem you're talking about at my computer.

I don't have the energy to troubleshoot this issue at the moment https://github.com/tisfeng/Raycast-Easydict/issues/44 , if you can provide PR, or have PR from other peeps, I'd be happy to take it.

**Comment by jwhalee** [comment]
yo someone please help me help him, thanks haha

**Comment by tisfeng** [comment]
@raycastbot close this issue
