### ISSUE TITLE
[ChatGPT] ...

### ISSUE THREAD

**Issue by Nov19** [raycast/extensions#7958]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Occasionally, the extension clears all my models. I was unable to restore the models.
<img width="762" alt="image" src="https://github.com/raycast/extensions/assets/89353728/1344bf68-eb1d-4b02-b339-3b11602412e5">
<img width="762" alt="image" src="https://github.com/raycast/extensions/assets/89353728/4af3b3f0-4e43-4edb-b372-7474c3c2dfa6">

And as you can see... the dropdown menu disappears...

### Steps To Reproduce

1. MacOS 13.5 (22G74)
2. With about 6 or 7 models saved in the extension.
3. Run 'Ask Question'
4. Once in a while... it says "Something went wrong". I restart the extension, and all my models are gone.

**Comment by cwkone** [comment]
Also encountered this issue last week. Strange. Still unable to restore, create, change, or even view any models. Nothing changed with my API key either.

**Comment by Nov19** [comment]
> Also encountered this issue last week. Strange. Still unable to restore, create, change, or even view any models. Nothing changed with my API key either.

Yep... I had to reinstall the extension to be able to use Models. And I lost all my models

**Comment by mickm3n** [comment]
+1

**Comment by zakelfassi** [comment]
Same issue here – @abielzulio happy to help debug/track this down if you have any prior context, but it seems to have happened (at least in my case) out of the blue. Appreciate your work on this!
