### ISSUE TITLE
[Easy Dictionary] Lost focus when startup

### ISSUE THREAD

**Issue by Saafo** [raycast/extensions#7959]
### Extension

https://www.raycast.com/isfeng/easydict

### Description

Each time Easy Dictionary startup, it will lost focus and regain focus for a while, during the period it will lost the keyboard input.

If you cannot reproduce, I'll provide screenshot later.

### Steps To Reproduce

1. open Raycast
2. open easy dict

**Comment by tisfeng** [comment]
Hi, this is most likely a small probability issue related to the user's computer environment, Easy Dictionary hasn't had the issue you mentioned in over a year on my computer.

I don't have the energy to troubleshoot this issue at the moment https://github.com/tisfeng/Raycast-Easydict/issues/44 , if you can provide PR, or have PR from other peeps, I'd be happy to take it.

**Comment by Saafo** [comment]
It's related to the `Query Selected Text Automatically` feature

**Comment by Saafo** [comment]
It's the bug of `getSelectedText` API from Raycast, I'll report it.

**Comment by tisfeng** [comment]
That's great.

@raycastbot close this issue
