### ISSUE TITLE
[Music]: 

### ISSUE THREAD

**Issue by hugomingoia** [raycast/extensions#7973]
### Extension

https://raycast.com/fedevitaledev/music

### Description

Command failed with exit code 1: osascript -e tell application "Music" to set loved of current track to true 
28:62: execution error: Music got an error: A descriptor type mismatch occurred. (-10001)

### Steps To Reproduce

Use "love track" command

**Comment by rawnly** [comment]
Are you on Sonoma? if so this is a duplicate of #7852.

**Comment by rawnly** [comment]
#8648

**Comment by rawnly** [comment]
@raycastbot close this issue
