### ISSUE TITLE
[Deepcast] Translate command - setting default "TO" language

### ISSUE THREAD

**Issue by arekmastalerczuk** [raycast/extensions#7974]
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

I often use the default translation box (Deepcast -> Translate), where I type a phrase and in the "From" field there is a "Detect" option, but in the "TO" field there is a default "English (US)" option selected. Is it possible to add functionality so that I can indicate the default language into which the phrase should be translated? I often translate from English to Polish and have to click on the "TO" option each time and select the native language.

I know that there is an option "Translate into Polish", although it may seem that it works similarly it is not so - there the result is not displayed, but copied to the clipboard and I have to paste it to another place later, and often I do not need this, because I just want to glance at the translation.

If it would be possible to add such functionality I would be very grateful because it would make my work much easier.

### Who will benefit from this feature?

The beneficiaries of this solution would be all those who often translate text into their native language, which is not always English. I myself translate 99% of the text from English to Polish, but I am sure that a very large group of people translate precisely from English (here the "Detect" option is ideal in the "FROM" field) to their native language. The English-speaking community is certainly very large, but if it were possible to set the "TO" option to any language, this extension would be ideal

**Comment by arekmastalerczuk** [comment]
The solution to my problem was to change the settings in the extension - there is an option that allows you to display the content in the window instead of copying to the clipboard. After changing the settings, I thought it was not working because it was still copying to the clipboard, but after several seconds the extension started working properly and now using the "Translate into Polish" option I am able to solve my earlier problem.

**Comment by rea1shane** [comment]
Need this feature.
