### ISSUE TITLE
[iMessage 2FA] ...

### ISSUE THREAD

**Issue by loekbosman** [raycast/extensions#7975]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

Does not work, does not load any messages

### Steps To Reproduce

Open de extension
... 
does nothing

### Current Behaviour

Does nothing

### Expected Behaviour

Show messages (with or without 2FA)

**Comment by ronaldheft** [comment]
Have you received any two-factor codes recently? By default, only codes from the last 24 hours are displayed. You can adjust that timeframe in the settings.

**Comment by ronaldheft** [comment]
Can you provide examples of the messages that aren't recognized?

**Comment by loekbosman** [comment]
The ones in the image I added?

**Comment by ronaldheft** [comment]
@loekbosman There are no images on this issue. Looks like you're replying via email. Perhaps GitHub isn't including the images you're attaching in your replies? Could you add the images from GitHub's website? Thanks!

**Comment by loekbosman** [comment]
Hi,

I tried it with another type of 2FA and it seems the one I reported on is just not recognised.

So - apologies - it does work, but not for all kind of 2FA codes. 

<img width="1132" alt="SCR-20230818-ioji" src="https://github.com/raycast/extensions/assets/77696663/ee1a93a5-6770-4732-ad04-9999de4ddc55">

**Comment by ronaldheft** [comment]
@loekbosman Thanks for providing an example. Currently only numeric codes are detected, but I just proposed a change that would support alphanumeric codes that are uppercase as well. Follow #7997 to see when the extension is updated.
