### ISSUE TITLE
[Amazon AWS] Extension doesn't work with Amazon SSO 

### ISSUE THREAD

**Issue by dmitrym0** [raycast/extensions#7988]
### Extension

https://www.raycast.com/Falcon/aws

### Description

I have aws-vault working locally with my various SSO profiles, below returns successfully:

```
❯ aws-vault exec myrole -- aws sts get-caller-identity
```

However when I try to use list S3 buckets (or any other resources), nothing comes back.

### Steps To Reproduce

1. Setup an SSO profile:
```
[profile Sandbox.PowerUserAccess]
sso_start_url = https://---.awsapps.com/start
sso_region = us-west-2
sso_account_name = Sandbox
sso_account_id = --
sso_role_name = PowerUserAccess
region = us-west-2
credential_process = aws-sso-util credential-process --profile Sandbox.PowerUserAccess
sso_auto_populated = true
```
2. Setup and verify `aws-vault`.
3. Install Amazon AWS
4. Invoke Raycast, type `s3`
5. Select `Sandbox.PowerUserAccess`
6. Start typing a known bucket name

### Current Behaviour

Nothing happens, s3 listing is empty.

### Expected Behaviour

Listing known buckets.

**Comment by JonathanWbn** [comment]
@dmitrym0 I can see that your credential process uses `aws-sso-util` instead of `aws-vault`. This might be the issue here.

This AWS extension currently has only limited support for SSO use cases... I might take another step at improving this at some point, but I currently have no such plans.
I would be happy to review/contribute to any improvements you might have.

**Comment by dmitrym0** [comment]
@JonathanWbn Do you have a plan in mind -- how would you add SSO support? Is it possible to do so without major rework?

**Comment by JonathanWbn** [comment]
@dmitrym0 I think it's a rather difficult thing because you naturally require some re-routing behavior. I could not suggest a plan on how to do it without digging in again.

**Comment by frese** [comment]
FWIW I can get most to work with SSO, if I run "aws sso login" in a terminal first - but it's admittedly not super stable :-(

**Comment by dmitrym0** [comment]
I was able to get the bulk of the functionality working by adding a single line here: https://github.com/dmitrym0/extensions/commit/e1f5f70793545f1ec47fbfab1c5455d69ae5b956

and setting this as my profile script:

```
/bin/zsh -l -c "echo q | aws-vault exec --no-stdout  <profile> -- aws sts get-caller-identity"
```

Launching the "main" console from various profiles requires a logout first, otherwise everything seems to work fine.

This was a quick patch without the full understanding of how this extension functions. If it makes sense, happy to create a PR.

👍

**Comment by andreacavagna01** [comment]
I could help in that I think! maybe you can link the line of codes where the extension is retrieving credentials? I can add other source method to retrieve credentials, as documented in the AWS documentation

**Comment by dmitrym0** [comment]
@andreacavagna01 I added support for SSO here https://github.com/dmitrym0/extensions/commit/e1f5f70793545f1ec47fbfab1c5455d69ae5b956
