### ISSUE TITLE
[Safari] Search for tabs within all tab groups 

### ISSUE THREAD

**Issue by Momixxxxxxx** [raycast/extensions#7992]
### Extension

https://www.raycast.com/loris/safari

### Description

Currently, when you use the "search tabs" command, it can only search the currently open tab group and the iCloud tabs. It would be very useful to search also the other, currently closed, tab groups.

### Who will benefit from this feature?

Everyone who uses tab groups to organize their Safari workflow.

**Comment by csteinlehner** [comment]
Oh yes, that would be a great feature!
