### ISSUE TITLE
[Sequel Ace] Use configurable preferences for environment colors

### ISSUE THREAD

**Issue by macbookandrew** [raycast/extensions#7999]
### Extension

https://www.raycast.com/nagauta/sequel-ace

### Description

Currently the colors are hard-coded to indicate environments.

This is great and I love the appearance of the colors, but Sequel Ace doesn’t actually define or label those colors anywhere, so it seems they are arbitrarily chosen (perhaps they match TablePlus?).

I have a different personal scheme for matching colors to environments that I’ve been using for 15 years and would like to remap the colors to match the environments I’m used to using.

@nagauta what do you think? 

@pernielsentikaer do you know of any other extensions that have color pickers or a mapping interface in the preferences UI that I could look at to start a PR?

### Who will benefit from this feature?

Anybody who doesn’t use this hardcoded color/environment mapping:

- local: green
- development: blue
- testing: purple
- staging: orange
- production: red

**Comment by nagauta** [comment]
@macbookandrew 
thanks you for feedback!!
I have recognized it is problem that the colors are hard-coded to indicate environments.
so it should be changed as you propose.

thanks for PR. I am so happy you contributing.

**Comment by nagauta** [comment]
> @pernielsentikaer do you know of any other extensions that have color pickers or a mapping interface in the preferences UI that I could look at to start a PR?
@pernielsentikaer do you have any ideas about this?
