### ISSUE TITLE
[Extension Bug] CoinMarketCap Crypto Crawler: Memory limit exceeded

### ISSUE THREAD

**Issue by sxn** [raycast/extensions#800]
# Extension – [CoinMarketCap Crypto Crawler](https://github.com/raycast/extensions/tree/main/extensions/coinmarketcap-crypto-crawler)

Author: @moojing 

## Description

Some queries return _a lot_ of results, which lead to the extension running out of memory and crashing

<img width="862" alt="image" src="https://user-images.githubusercontent.com/1155589/152399105-8947daba-f573-402e-93b2-b1b4625b8ee7.png">

## Steps To Reproduce

1. Run `Refresh Crypto List`
2. Run `Search Crypto` command
3. Type `a`

## The current behavior

Extension crashes.

## The expected behavior

Extension doesn't crash. 😅 We could either limit the amount of results to e.g. 1000, or only perform searches when e.g. at least 3+ characters are provided.

### Raycast version
Version: v1.27.1

**Comment by moojing** [comment]
Ohhhh, I didn't expect this situation. And I think limit the search result to a certain number is a good solution. Maybe a user don't need so many options when searching a token! 

I can create another PR , maybe let's make the limit to be 1000 first?

**Comment by moojing** [comment]
@sxn  I updated the limit [here](https://github.com/raycast/extensions/pull/883) (using 500 as the limit)
