### ISSUE TITLE
[Obsidian] ...

### ISSUE THREAD

**Issue by offbrands-studio** [raycast/extensions#8003]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

Menu Bar Item produces error warning and won't load. 

### Steps To Reproduce

Open Raycast
Open 'Obsidian Menu Bar' 
Error ensues 

### Current Behaviour

Not working - produces red error ! icon

### Expected Behaviour

To show obsidian logo

### Error Copied 

```Error: ENOENT: no such file or directory, scandir 'Digital Garden'

Ef:obsidianMenuBar.tsx:8:33

---
 5: import { getObsidianTarget, ObsidianTargetType, useObsidianVaults, vaultPluginCheck } from "./utils/utils";
 6: 
 7: function BookmarkedNotesList(props: { vault: Vault }) {
 8:   const [notes] = useNotes(props.vault, true);
 9:   return (
10:     <MenuBarExtra.Submenu title={props.vault.name} key={props.vault.path + "Bookmarked Notes"}>
11:       {notes.map((note) => (
---

    at ray-menu-bar-extra-submenu
vs:index.js:23:27383
Tf:obsidianMenuBar.js:134:10628```

**Comment by offbrands-studio** [comment]
Any update on this issue?

**Comment by KevinBatdorf** [comment]
I couldn't reproduce it at the time but I'll try to reproduce it again later and check the crash reports to see if there's more details there.

**Comment by offbrands-studio** [comment]
Thank you @KevinBatdorf - Let me know if there’s anything more I can share to help.

**Comment by KevinBatdorf** [comment]
I couldn't reproduce it. it's loading fine for me. Can you tell me more about your usage? Do you have a lot of notes? Multiple bases? I can try reproducing it again but probably need more details.
