### ISSUE TITLE
[Apple Notes] Unable to run 'Search Notes'

### ISSUE THREAD

**Issue by Shota-Abe** [raycast/extensions#8004]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

When I try to run 'Search Notes', I get an error message 'Cannot search notes database disk image is malformed'.

### Steps To Reproduce

1. Run "Search Notes".
2. See error.

**Comment by mchmarny** [comment]
+1

**Comment by paul-s-prk** [comment]
+1
