### ISSUE TITLE
[Spotify Player] Add options for adding and removing albums into your library

### ISSUE THREAD

**Issue by badta5te** [raycast/extensions#8019]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Hi, I've been using the Spotify extension extensively. While exploring new artists, I often come across albums that I would like to add to my library for later listening. Unfortunately, this option is not currently available in the extension. 
I have developed a solution to add this feature to the extension and I would like to discuss it before submitting a pull request (PR). I want to ensure that this feature will be useful not only for me but also for other users.

### Who will benefit from this feature?

Everyone who wants to add and remove albums to the library.

### Anything else?

![CleanShot 2023-08-20 at 22 48 24@2x](https://github.com/raycast/extensions/assets/40657512/4974d7b8-1328-49eb-b9d6-8b93d339fcb9)

**Comment by AntonYartsev** [comment]
I find this useful.
In this case, a small suggestion: it would be very convenient to also add labels for albums already in the library (perhaps an icon or an emoji)
