### ISSUE TITLE
[Extension Bug] Connection stucked with Figma File Search

### ISSUE THREAD

**Issue by AntoinePlu** [raycast/extensions#802]
# Extension – [Figma File Search](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/figma-files/)
Author: Micheal Schultz @michaelwschultz

## Description
I tried to connect my Figma account via the extension. After entering the secret API and Team ID, I got an error "Something went wrong". I may have retried once or twice, then the app crashed.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/2418708/152427778-364d29f3-80eb-4246-8dfc-ecfacee2fd28.png">

## Steps To Reproduce

1. Enter your secret API key then your Figma Team ID
2. Validate, then force retry

## The current behavior
The extension doesn't seem to be able to connect Figma to Raycast (without more info).

## The expected behavior
We are expecting a sync between Figma and Raycast to be able to search files inside a specific team.

### Raycast version
Version: 1.27.1

**Comment by fe9lix** [comment]
The reason could be a wrong team id. Have you checked whether the access token and team id are correctly entered? 

## Access Token
You can find the Figma access token in your Account Settings > Personal Access Token section

## Team ID
You can extract the team ID by navigating to your team page in Figma and then looking at the URL in the browser, for example:
https://www.figma.com/files/team/<TEAM_ID>/

Update the value for <TEAM_ID> in Raycast Preferences > Extensions > Figma...  
then reopen the command.

@michaelwschultz I've created a [PR](https://github.com/raycast/extensions/pull/805) that adds error handling.

**Comment by michaelwschultz** [comment]
@AntoinePlu did this fix your issue or are you still having problems?

**Comment by fe9lix** [comment]
I'm closing this for now since improved error handling has now landed with the latest extension update. Feel free to reopen if fixing the team ID does not fix the error.

**Comment by AntoinePlu** [comment]
Sorry for the late reply folks.

The short answer is yes, I'm still stuck behind that screen.
I'm sure I have the right TeamID and personal unique token from Figma.

Out of topic, if I can suggest something on the error management part, I had to go through your documentation and all to find back the link to this extension settings. I didn't have the reflex at the moment to find it behind extensions/<appname>.

It could be great to have a direct link behind CMD+K from the "Something went wrong" screen.

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/2418708/154587828-e2f28fb8-0893-49dc-94f2-b16d893c5ff3.png">

**Comment by fe9lix** [comment]
@michaelwschultz Is that something that you could help debug...?

**Comment by michaelwschultz** [comment]
I see someone else had a similar issue. I'll look into it @fe9lix.

**Comment by michaelwschultz** [comment]
@AntoinePlu do you mind uninstalling and reinstalling the extension again from the store?

**Comment by AntoinePlu** [comment]
FYI, I'm running a MBP on BigSur 11.5.

- I've uninstalled then reinstalled the extension.
- Created a new personal token
- Copied that one + the team ID
- And sadly I still have the same error


Here is the full error code if that can help:

```
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

W:react.production.min.js:20:384

---
17: function R(a){a.result=null;a.keyPrefix=null;a.func=null;a.context=null;a.count=0;10>P.length&&P.push(a)}
18: function S(a,b,c,e){var d=typeof a;if("undefined"===d||"boolean"===d)a=null;var g=!1;if(null===a)g=!0;else switch(d){case "string":case "number":g=!0;break;case "object":switch(a.$$typeof){case p:case q:g=!0}}if(g)return c(e,a,""===b?"."+T(a,0):b),1;g=0;b=""===b?".":b+":";if(Array.isArray(a))for(var l=0;l<a.length;l++){d=a[l];var f=b+T(d,l);g+=S(d,f,c,e)}else if(null===a||"object"!==typeof a?f=null:(f=A&&a[A]||a["@@iterator"],f="function"===typeof f?f:null),"function"===typeof f)for(a=f.call(a),l=
19: 0;!(d=a.next()).done;)d=d.value,f=b+T(d,l++),g+=S(d,f,c,e);else if("object"===d)throw c=""+a,Error(B(31,"[object Object]"===c?"object with keys {"+Object.keys(a).join(", ")+"}":c,""));return g}function U(a,b,c){return null==a?0:S(a,"",b,c)}function T(a,b){return"object"===typeof a&&null!==a&&null!=a.key?escape(a.key):b.toString(36)}function ca(a,b){a.func.call(a.context,b,a.count++)}
20: function da(a,b,c){var e=a.result,d=a.keyPrefix;a=a.func.call(a.context,b,a.count++);Array.isArray(a)?V(a,e,c,function(a){return a}):null!=a&&(N(a)&&(a=ba(a,d+(!a.key||b&&b.key===a.key?"":(""+a.key).replace(O,"$&/")+"/")+c)),e.push(a))}function V(a,b,c,e,d){var g="";null!=c&&(g=(""+c).replace(O,"$&/")+"/");b=Q(b,g,e,d);U(a,da,b);R(b)}function W(){var a=I.current;if(null===a)throw Error(B(321));return a}
21: var X={Children:{map:function(a,b,c){if(null==a)return a;var e=[];V(a,e,null,b,c);return e},forEach:function(a,b,c){if(null==a)return a;b=Q(null,null,b,c);U(a,ca,b);R(b)},count:function(a){return U(a,function(){return null},null)},toArray:function(a){var b=[];V(a,b,null,function(a){return a});return b},only:function(a){if(!N(a))throw Error(B(143));return a}},createRef:function(){return{current:null}},Component:E,PureComponent:G,createContext:function(a,b){void 0===b&&(b=null);a={$$typeof:w,_calculateChangedBits:b,
22: _currentValue:a,_currentValue2:a,_threadCount:0,Provider:null,Consumer:null};a.Provider={$$typeof:v,_context:a};return a.Consumer=a},forwardRef:function(a){return{$$typeof:x,render:a}},lazy:function(a){return{$$typeof:aa,_ctor:a,_status:-1,_result:null}},memo:function(a,b){return{$$typeof:z,type:a,compare:void 0===b?null:b}},useCallback:function(a,b){return W().useCallback(a,b)},useContext:function(a,b){return W().useContext(a,b)},useEffect:function(a,b){return W().useEffect(a,b)},useImperativeHandle:function(a,
23: b,c){return W().useImperativeHandle(a,b,c)},useDebugValue:function(){},useLayoutEffect:function(a,b){return W().useLayoutEffect(a,b)},useMemo:function(a,b){return W().useMemo(a,b)},useReducer:function(a,b,c){return W().useReducer(a,b,c)},useRef:function(a){return W().useRef(a)},useState:function(a){return W().useState(a)},Fragment:r,Profiler:u,StrictMode:t,Suspense:y,createElement:M,cloneElement:function(a,b,c){if(null===a||void 0===a)throw Error(B(267,a));var e=h({},a.props),d=a.key,g=a.ref,l=a._owner;
---

useState:react.production.min.js:23:308
as:index.js:17:100
is:index.js:17:1385
wl:react-reconciler.production.min.js:5:19061
Wi:react-reconciler.production.min.js:9:6962
ji:react-reconciler.production.min.js:9:940
Jo:react-reconciler.production.min.js:9:871
Ut:react-reconciler.production.min.js:9:728
Jl:react-reconciler.production.min.js:7:12492
```

**Comment by fe9lix** [comment]
Hey @AntoinePlu – do other (non-Raycast) extensions installed from the store work for you?

**Comment by michaelwschultz** [comment]
Doesn't seem like this is local to the Figma extension from the error message. @fe9lix if you find out that it is, just let me know.
