### ISSUE TITLE
[Notion] Timezone and @remind support

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#8020]
### Extension

https://www.raycast.com/HenriChabrand/notion

### Description

When I create new items with date/time fields, the time is always three hours off even though the timezone is set on the field. Additionally, it would be great to support adding @remind.

### Steps To Reproduce

1. Using a Notion Database with timezone set on the field
2. Adding a new entry with Create a Page
3. Setting a specific time for the entry.

### Current Behaviour

The time is set to 3 hours ahead of the time entered.

### Expected Behaviour

The time should be set to the correct time.

**Comment by bkeys818** [comment]
As of now, Notion's API doesn't support `@remind`.

**Comment by christianmagill** [comment]
Thanks, hopefully sometime in the future.

**Comment by christianmagill** [comment]
@bkeys818 Any idea what might be causing the time differentiation?

**Comment by bkeys818** [comment]
@christianmagill, I haven't tried to recreate it yet. Working with time zones gets stupid complicated. What time zone are you in?

**Comment by christianmagill** [comment]
I’m EST. Yeah date math is always a struggle. Only thing worse is combining
it with calendar invites.

**Comment by thomaslombart** [comment]
Could you post a recording to get a better understanding of what happens for the timezone issue?

**Comment by christianmagill** [comment]
@thomaslombart Sure, here's a video...

https://drive.google.com/file/d/1fgTX_ePcWn2MN7sMd2ySunCgv4FJouKG/view?usp=sharing

**Comment by christianmagill** [comment]
I've checked and the timezone for the field is set to EDT as is my system.

**Comment by erics118** [comment]
I have a fix for the issue that causes the time to be off, which I will make after #8218 is merged.

**Comment by bkeys818** [comment]
This issue was fixed and can be closed.

**Comment by erics118** [comment]
Timezone stuff was fixed but `@remind` support isn't possible yet.
