### ISSUE TITLE
[Home Assistant] Fuzzy matching entities

### ISSUE THREAD

**Issue by graelo** [raycast/extensions#8030]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Description

Thanks for this great extension. I'd love it even more if it could perform fuzzing matching of entity names.

For example, with an existing entity named "Garage Light Switch", I'd like to find it by simply typing "garligsw", or "glisw". For another entity named "kitchen-vent", typing "kvent" should also match.

Currently, users have to type the correct substring with separators. In the above example, it means users have to type "Garage " and "kitchen-" respectively.

Would you consider adding this?

Thanks a lot!

### Who will benefit from this feature?

I think any user searching for entities will enjoy this feature, but in particular users who have lots of entities.

### Anything else?

You can get an example of fuzzy maching with the command line tool `fzf`.

```shell
echo "Garage Light Switch" | fzf
```

<img width="131" alt="image" src="https://github.com/raycast/extensions/assets/84066822/e0250b93-7dbd-44f0-9aa1-6dd51a1bffb4">

**Comment by tonka3000** [comment]
Hi @graelo,

Thanks for using the extension. I totally get the point.

Do you like the fuzzy search from the Raycast root search? I'm think about using it. I implemented fuzzy-search in my GitLab Extension, but I'm not that happy with the library I used.

Do you use `fzf `for your fuzzy search?

**Comment by graelo** [comment]
Thanks for being so prompt!

I'm a recent Raycast user but I found their fuzzy matching very natural (like Spotlight or fzf), so I think it would be a great fit, indeed! Good catch

Cheers

**Comment by tonka3000** [comment]
@graelo I will tray to use Raycast first, if it is not good enough a fallback would be zfz Algo.

**Comment by graelo** [comment]
@tonka3000 Very cool, thanks!

Just fyi, I spotted this: https://www.npmjs.com/package/fzf (I don't know if it's any good but the number of weekly downloads is high). Sorry I'm not a js/ts dev, so I don't know if this helps.

**Comment by graelo** [comment]
Hello, I'm still super interested in this feature (no pressure @tonka3000, it's just to avoid auto-closing).

**Comment by tonka3000** [comment]
@graelo I still want to implement it but right now not much time to do so. I already tested the variants especially the native Raycast search and I need to find ways around the downsides (internal technical detail) of using the approach.
