### ISSUE TITLE
[Menubar Weather] Contrast issue on not-focused screen

### ISSUE THREAD

**Issue by kud** [raycast/extensions#8032]
### Extension

https://www.raycast.com/koinzhang/menubar-weather

### Description

On the screen which is not the current one, the icon is like "active" compared to other ones. And when it's the current one, the contrast is less important

![screenshot-2023-08-21-16-02-46](https://github.com/raycast/extensions/assets/655838/5753ee80-f151-450e-a336-162c47b81054)
![screenshot-2023-08-21-16-07-14@2x](https://github.com/raycast/extensions/assets/655838/1072cf4a-2dac-4702-bb44-e62cac29d6e7)

https://github.com/raycast/extensions/assets/655838/dfc3327e-7195-435c-8b40-7dba75227b4e

### Steps To Reproduce

Switching the focus between different screens and check the contrast.

**Comment by koinzhang** [comment]
Hi @kud This problem already has a related issue #7481, which belongs to the official API problem, and we look forward to their resolution.
So I will close this issue, if you have other questions, welcome to issue
@raycastbot close this issue

**Comment by kud** [comment]
Sure thing, thanks!
