### ISSUE TITLE
[Jetbrains Toolbox] "Search Recent Projects" does not work for rider since 2.0 support

### ISSUE THREAD

**Issue by peppy** [raycast/extensions#8040]
### Extension

https://www.raycast.com/gdsmith/jetbrains

### Description

After upgrading Jetbrains Toolbox to 2.0 I found the extension stop working. I then found https://github.com/raycast/extensions/issues/7617 (note that this issue should probably be closed as the related PR https://github.com/raycast/extensions/pull/7799 is merged and deployed) and realised all I needed to do was update raycast to pull down the new version.

It's working very well for DataGrip and PhpStorm, on two different PCs. But on both PCs, my rider projects do not show.

In the apps list, a broken icon shows next to rider, even though the extension does list all my rider installs:

![2023-08-22 22 43 52@2x](https://github.com/raycast/extensions/assets/191335/763f26f1-3d7a-4227-829e-6b5d60e7806c)

In the case of my other PC it correctly shows both EAP and normal, but no projects:

![](https://user-images.githubusercontent.com/191335/261190704-724c3a48-c09b-4a7c-8073-b3402491676f.png)

### Steps To Reproduce

1. Open "search recent projects"
2. Note that rider projects don't show

**Comment by gdsmith** [comment]
Fixed in #8045
