### ISSUE TITLE
[Menubar Weather] Forecast > Weather does not have day number

### ISSUE THREAD

**Issue by kud** [raycast/extensions#8047]
### Extension

https://www.raycast.com/koinzhang/menubar-weather

### Description

When I want to watch the forecast, it's quite hard to understand what day we're talking about as it's got no number, compared to other types of forecast, even if I really like those weather icons.

https://github.com/raycast/extensions/assets/655838/0169947d-db31-4d0d-bc70-01ef487e209d

### Steps To Reproduce

1. Click on the menu bar icon
2. Hover on Forecast > Weather

### Current Behaviour

No day number

### Expected Behaviour

Should have day number

**Comment by koinzhang** [comment]
@raycastbot Keep Issue open

**Comment by kud** [comment]
Thanks

**Comment by kud** [comment]
Grrrrrrrrrrrrrrrrrr!
