### ISSUE TITLE
[Reclaim.ai] Change "Add time" to "Set Time"

### ISSUE THREAD

**Issue by ariccb** [raycast/extensions#8048]
### Extension

https://www.raycast.com/reclaim-ai/reclaim-ai

### Description

I find sometimes I over-estimate how long a task will take, or my default (30min) is slightly too long and is taking up room in my calendar when other tasks could get fit into there. Right now the only option is to "add time" to the selected task, where it would be more useful to just "set time", whether it's adding or subtracting from what was there before.

### Who will benefit from this feature?

everyone!

### Anything else?
I also find it a little confusing what the yellow time is for, because it's missing an icon/ description.

![Untitled](https://github.com/raycast/extensions/assets/48956351/81059cc5-d950-4249-bb04-8ecbbee746f2)

**Comment by maximilianzuern** [comment]
> I also find it a little confusing what the yellow time is for, because it's missing an icon/ description.

You can just hover each tag to obtain more details.
 <img width="862" alt="Screenshot 2023-08-23 at 14 50 04" src="https://github.com/raycast/extensions/assets/85677120/d99ff355-680c-4039-87c4-f73abe14fbf8">

> Right now the only option is to "add time" to the selected task, where it would be more useful to just "set time", whether it's adding or subtracting from what was there before.

Would it fix the issue if we added the option “Add 15 min” to the menu?

Giving input via the [Action Panel](https://developers.raycast.com/api-reference/user-interface/action-panel) is not supported by Raycast. 
Also, subtracting time is AFAIK not suported by the reclaim API. 

If you overestimated the time of your task and finished earlier, I suggest you use the “Mark as done” Action."
<img width="862" alt="Screenshot 2023-08-23 at 14 51 03" src="https://github.com/raycast/extensions/assets/85677120/7298d56d-8d3d-4d10-a0cf-3a8556b34b28">

**Comment by ariccb** [comment]
Oh I see, maybe what needs to be added is an option to snooze a task by a certain amount.


---
On August 23, 2023 at 7:50 AM, Maximilian ***@***.******@***.***>) wrote:
I also find it a little confusing what the yellow time is for, because it's missing an icon/ description.
You can just hover each tag to obtain more details.
[Screenshot 2023-08-23 at 14 50 04]<https://user-images.githubusercontent.com/85677120/262678988-d99ff355-680c-4039-87c4-f73abe14fbf8.png>
Right now the only option is to "add time" to the selected task, where it would be more useful to just "set time", whether it's adding or subtracting from what was there before.
Would it fix the issue if we added the option “Add 15 min” to the menu?
Giving input via the Action Panel<https://developers.raycast.com/api-reference/user-interface/action-panel> is not supported by Raycast.
Also, subtracting time is AFAIK not suported by the reclaim API.
If you overestimated the time of your task and finished earlier, I suggest you use the “Mark as done” Action."
[Screenshot 2023-08-23 at 14 51 03]<https://user-images.githubusercontent.com/85677120/262683078-7298d56d-8d3d-4d10-a0cf-3a8556b34b28.png>

**Comment by maximilianzuern** [comment]
Are you referring to the Reschedule feature?
This could be implemented quite easily.

<img width="824" alt="Screenshot 2023-08-29 at 17 15 20" src="https://github.com/raycast/extensions/assets/85677120/176229c6-5e8a-4d41-b718-ceb37cfe0abc">

**Comment by ariccb** [comment]
Yes! That would help quite a lot.

Aric Crosson Bouwers
[icon] 403.909.5049 | [icon]  www.ariccb.dev<https://www.ariccb.dev/> | [icon]  ***@***.******@***.***>



On August 29, 2023 at 9:18 AM, Maximilian ***@***.******@***.***>) wrote:
Are you referring to the Reschedule feature?
This could be implemented quite easily.
[Screenshot 2023-08-29 at 17 15 20]<https://user-images.githubusercontent.com/85677120/264068782-176229c6-5e8a-4d41-b718-ceb37cfe0abc.png>

**Comment by maximilianzuern** [comment]
https://github.com/raycast/extensions/pull/8203

- Added `Reschedule` feature.
- Added 'Add 15min' option to `Add Time`.
- Added 'Mark incomplete' feature to archived tasks.
