### ISSUE TITLE
[GitHub] Search Issues implies it searches globally but actually only searches own

### ISSUE THREAD

**Issue by peppy** [raycast/extensions#8052]
### Extension

https://github.com/raycast/extensions/blob/f86274b3b7464b4159a1a3cbad7020c1c3e1464b/extensions/github/README.md

### Description

As per

https://github.com/raycast/extensions/blob/f86274b3b7464b4159a1a3cbad7020c1c3e1464b/extensions/github/src/search-issues.tsx#L27

issue search is less useful than it should be because it's including the `author:@me` search filter. This means that when searching for issues you rarely find what you're looking for.

This is not implied in the command description, nor the placeholder text when searching:

![Safari 2023-08-23 at 06 13 34](https://github.com/raycast/extensions/assets/191335/f0c0a255-71bd-422b-b463-943e6762ff13)

I believe this should be removed, especially since there's already another command for "Created Issues".

### Steps To Reproduce

As above

**Comment by peppy** [comment]
I would hope that the author filter is just removed for these commands, personally (I've tested this locally and it works as I'd hope it to).

If there's a requirement for filtering to own PR/issues, two new commands "Search own issues" and "Search own pull requests" may read better.

**Comment by peppy** [comment]
I've started to experiment with a flexible solution for this. I know we could add a filter dropdown with options like "All <Issues|Pull Requests" and "Opened by me", but what works well for me is allowing customisation of the `author:@me` spec across search commands:

https://github.com/raycast/extensions/assets/191335/db2df27f-9281-40b8-9ef9-2a5f61657003

Would this be an acceptable change? If so I will tidy things up and shoot off a pull request.

**Comment by thomaslombart** [comment]
I still find the filter dropdown to be better in terms of user experience, but I haven't had a chance to revisit it yet. So, let's use your solution in the meantime.

**Comment by peppy** [comment]
The problem with the filter dropdown is that as per my video, I always want to search in my organisation. To my knowledge there's not a way to add a custom item to the filter dropdown? Unless there's some hidden github search term that we could add a standardised item for like `org:@mine`...

**Comment by thomaslombart** [comment]
> To my knowledge there's not a way to add a custom item to the filter dropdown?

What do you mean? I don't see any limitations in doing that.

**Comment by peppy** [comment]
Sorry I was a bit unclear. Checking existing extensions I can't see a predefined UX for adding custom items to that menu. It might be a bit high effort.

**Comment by peppy** [comment]
@thomaslombart it turns out the already implemented `SearchRepositoryDropdown` does a pretty great job, and also covers my use case of wanting to query across my repos / org. Does this seem like a better direction? Would be quite simple, just hooking it up to the PR/issue/discussion searches (ignore the placeholder text, which will need an update):

![iTerm2 2023-10-10 at 03 58 42](https://github.com/raycast/extensions/assets/191335/d66006f6-9beb-4efe-85a5-0464134efa7f)

**Comment by thomaslombart** [comment]
Let's do that, yeah. It sounds like a good solution on which we can improve further down the road.

**Comment by peppy** [comment]
@thomaslombart I've submitted my changes over at #8766, please take a look and see if you agree with them 🙏.
