### ISSUE TITLE
[Authy] OTPs are not fetching 

### ISSUE THREAD

**Issue by kirso** [raycast/extensions#8053]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

After providing permissions to the extension with the id and password it doesn't load the OTPs:
![CleanShot 2023-08-23 at 14 36 33](https://github.com/raycast/extensions/assets/2138870/b0e071b9-293c-480b-b15c-fb9f7c1c00f6)

### Steps To Reproduce

1. Install Authy extension
2. Search Tokens in raycast

### Current Behaviour

Doesn't show or fetch OTPs 

### Expected Behaviour

Copy and see OTPs in Raycast

**Comment by krishgokulk** [comment]
same issue, how can I resolve this issue

**Comment by kirso** [comment]
> If all the OTP are "corrupted" then it's likely you have an incorrect backup password. Please try resetting it and redownloading your OTP if you are sure the password is correct.

I've checked the password and changed it a few times. Reinstalled the extension on Raycast but still getting the same result. The password is correct.
