### ISSUE TITLE
[Google Bard] `Bard couldn't connect` Error

### ISSUE THREAD

**Issue by jag-k** [raycast/extensions#8060]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

I have a trouble with this extension. I can't use it, 'cause I have `Bard couldn't connect.` error.

### Steps To Reproduce

Create new account/cookies

**Comment by nedzen** [comment]
For some reason the API won't connect anymore

**Comment by TonyVlcek** [comment]
I'm having the same issue. Is this an issue on Raycast's or Google's side?

**Comment by robinsrk** [comment]
Same here, can't connect. Please make another way to connect api

**Comment by rickycm** [comment]
got the same error here

**Comment by dnet5** [comment]
Same thing.

**Comment by devgocri** [comment]
Same thing

**Comment by EvanZhouDev** [comment]
Please migrate to the PaLM API extension, if you are able to. The Bard extension is no longer stable, and the library powering it, `bard-ai`, is only working now for some people.

**Comment by Ssiswent** [comment]
> Please migrate to the PaLM API extension, if you are able to. The Bard extension is no longer stable, and the library powering it, `bard-ai`, is only working now for some people.

Hi, I have a similar problem with palm, do you know the reason? Thanks.
I use the same `__Secure-1PSID`.
![image](https://github.com/raycast/extensions/assets/37449310/327bf403-ab3a-4ecb-8289-30e54bb8fcac)
