### ISSUE TITLE
[Weather] Add "feels-like" data

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#8062]
### Extension

https://www.raycast.com/tonka3000/weather

### Description

Please, consider adding "feels-like" data to the extension.

**Comment by tonka3000** [comment]
@xilopaint Will be added in the next version

**Comment by xilopaint** [comment]
> @xilopaint can your share a screenshot

Weird, now it's showing the data. Does the extension has a cache?

**Comment by tonka3000** [comment]
The new version is cached.

Did you see all the other new values but not `feels like` or was it always the old version? It could be that the extension update took longer on your machine.

**Comment by tonka3000** [comment]
Ok, than I would assume that your automatic extension update took longer .

Btw: there is a command where you can trigger the update (check extension updates or something like that) to get such things faster if you already know that there is an update.
