### ISSUE TITLE
[WeChat] 一直报错: Wechat is not running

### ISSUE THREAD

**Issue by fox-ghost** [raycast/extensions#8064]
### Extension

https://www.raycast.com/raffeyang/wechat

### Description

已经正确安装微信客户端, 使用命令时,一直提示 Wechat is not running

### Steps To Reproduce

系统信息:
![CleanShot 2023-08-24 at 12 50 39@2x](https://github.com/raycast/extensions/assets/59099193/564ae915-e689-4abd-918b-fe8a9ea1ccdb)
Raycast 信息:
<img width="370" alt="CleanShot 2023-08-24 at 12 51 29@2x" src="https://github.com/raycast/extensions/assets/59099193/0fde5474-ea2f-4452-9950-3fc1cf5e8267">
微信版本:
![image](https://github.com/raycast/extensions/assets/59099193/bee36b87-9566-49fb-ae5c-c6e0420a0ecb)

**Comment by raffeyang** [comment]
请仔细阅读README，需要安装微信插件[WeChatExtension-ForMac](https://github.com/raffeyang/WeChatExtension-ForMac)，详细安装方式查看对应repo

**Comment by fox-ghost** [comment]
@raycastbot close

**Comment by minghaoguo20** [comment]
Same issue.
I've installed WeChatTweak-macOS and WeChat and keep them up-to-date. And I have rebooted my mac.
However, I still face such problem. 
<img width="774" alt="image" src="https://github.com/raycast/extensions/assets/69155059/a246b76d-e398-4e80-a377-307c70060f1f">
