### ISSUE TITLE
[Filament] Filament 3.0 support

### ISSUE THREAD

**Issue by gwlortscher** [raycast/extensions#8065]
### Extension

https://www.raycast.com/aurawindsurfing/filament

### Description

A new major version of Filament has been released (3.0), but this extension only searches the 2.0 docs.

**Comment by aurawindsurfing** [comment]
Hey will work on it this weekend. Intially there was no algolia available on the new docs.

**Comment by aurawindsurfing** [comment]
Pull request made

**Comment by aurawindsurfing** [comment]
@raycastbot close this issue
