### ISSUE TITLE
[JIRA] Can't select an epic while creating a ticket

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#8071]
### Extension

https://www.raycast.com/raycast/jira

### Description

Could we have a way to add an epic to a ticket when one is being created?

**Comment by thomaslombart** [comment]
Isn't this already possible? There is an Epic field in the `Create Issue` command if the selected task type is not a subtask.

**Comment by FezVrasta** [comment]
![CleanShot 2023-09-06 at 4 03 13@2x](https://github.com/raycast/extensions/assets/5382443/81aa5c8a-c3a3-40d6-abf9-2d187710a347)

I don't see an Epic field on any of my issue types, but it's there on the JIRA web ui

**Comment by thomaslombart** [comment]
Is it the case for each Jira project?

**Comment by FezVrasta** [comment]
Now that I look it only happens with the EN project
