### ISSUE TITLE
[Flow Timer] Start Next Focus and Start Timer

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#8077]
### Extension

https://www.raycast.com/vimtor/flow

### Description

I'd like to see a command to both start the next focus session and start the timer at the same time. It seems you currently need to execute both to get a session going.

**Comment by vimtor** [comment]
Hey @christianmagill!

Thanks for reporting the issue. This seems to be a bug. I no longer use this extension but it worked. Perhaps the Flow developers changed how the Applescript works. I will try to fix it soon.

**Comment by christianmagill** [comment]
@vimtor Much thanks! I appreciate that.
