### ISSUE TITLE
[Domainr] ... Invalid API key

### ISSUE THREAD

**Issue by seanbperiod** [raycast/extensions#8080]
### Extension

https://www.raycast.com/fedevitaledev/domainr

### Description

Hello, I'm having trouble getting the Search Domains / Domainr extension set up with RapidApi and I can't find any instructions on what to do..
I'm guessing I have to sign up for a RapidApi account - So I did that, then subscribed to the Domainr API, and found an API there.
Then I followed the instruction here: To get an API Key: https://rapidapi.com/blog/api-glossary/api-key/
Found the API key as mentioned, and put that in the extension, but I keep getting the error: invalid API key.
I also searched the raycast github for instruction on setup, but couldn't find anything.
Any help would be appreciated.

### Steps To Reproduce

1. Insert API key
2. Try using Search Domain
3. ?????
4. Profit

**Comment by rawnly** [comment]
hi thanks for reporting, i saw your email but i'm currently out. i'll have a look into it asap

**Comment by seanbperiod** [comment]
Hoping this is still being considered for an update!

**Comment by rawnly** [comment]
Hi @seanbperiod I'm sorry but I cannot reproduce the issue, if i create a new api-key from rapidapi seems to be valid for me. 

Steps: 
1. Sign In to rapodapi.com
2. Create a new app or use an existing one
3. Register to the domainr api on rapidapi
4. Go to https://rapidapi.com/developer/dashboard and copy your api-key
5. Configure the extension

**Comment by rawnly** [comment]
Here's the api: https://rapidapi.com/domainr/api/domainr
