### ISSUE TITLE
[Onenote] could not search anything

### ISSUE THREAD

**Issue by yoghurtdewdew** [raycast/extensions#8082]
### Extension

https://www.raycast.com/alewandowski/onenote

### Description

Related to #4853 
According to https://github.com/raycast/extensions/issues/4853#issuecomment-1512116382

I have closed some notebooks to make the number below 10 but it still could not make it.

<img width="1076" alt="image" src="https://github.com/raycast/extensions/assets/63794438/27fa359c-9ca2-41af-86a6-00d8ce4a1180">
<img width="1036" alt="image" src="https://github.com/raycast/extensions/assets/63794438/d10144d3-0ab7-402b-8fe6-f33637c63b5e">
<img width="406" alt="image" src="https://github.com/raycast/extensions/assets/63794438/6a496482-b9c4-44a2-a964-cde70f5efa18">

And is there any possibility to remove the restrictions of the notebooks numbers? Thank you!

### Steps To Reproduce

<img width="786" alt="image" src="https://github.com/raycast/extensions/assets/63794438/7ecca4f3-0065-4332-b519-ca62d8f7fcdf">

**Comment by yoghurtdewdew** [comment]
As #4853 described the related files:

<img width="769" alt="image" src="https://github.com/raycast/extensions/assets/63794438/f80fe629-0f44-42ff-8b32-913e0a5a78a3">

How to fix this?

**Comment by yoghurtdewdew** [comment]
Any progress?

**Comment by yoghurtdewdew** [comment]
Any progress?

**Comment by yoghurtdewdew** [comment]
Any progress?

**Comment by alewandows** [comment]
Hi,
Thank you very much for your feedback. 
Unfortunately, I currently have no free time to spend on this project... Hope one day I will !
