### ISSUE TITLE
[Jira] Cannot search for the sprint

### ISSUE THREAD

**Issue by adam-tkaczyk-mck** [raycast/extensions#8084]
### Extension

https://raycast.com/raycast/jira

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'localeCompare')
    at /Users/XXX/.config/raycast/extensions/9f656d62-a7b1-4bc6-bfa8-a67cbb427dcb/create-issue.js:98:2900
    at Array.sort (<anonymous>)
    at jU (/Users/XXX/.config/raycast/extensions/9f656d62-a7b1-4bc6-bfa8-a67cbb427dcb/create-issue.js:98:2761)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

Search for the sprint

### Current Behaviour

Error during search

### Expected Behaviour

Visible results

**Comment by thomaslombart** [comment]
Thanks for flagging this issue. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by adam-tkaczyk-mck** [comment]
Sorry, I probably won't have time for that in this month 😞
