### ISSUE TITLE
[YouTube] ...

### ISSUE THREAD

**Issue by jjr284** [raycast/extensions#8091]
### Extension

https://www.raycast.com/tonka3000/youtube

### Description

When recent videos are enabled, after searching a video once, there isn't a way to clear it. It will only let me click on the recent video, not search for more.

### Steps To Reproduce

 For example, I made Search Videos a hot key... now when I jump straight to search videos, it shows the most recent one, and when I press enter, it doesn't accept my search that I typed in, it clicks on the old recent video. The temporary workaround was disabling showing recent videos.

**Comment by tonka3000** [comment]
@jjr284 👋,

Interesting. I'm not able to reproduce that. Can you create a screen-recording and post it here?

btw: Which Raycast version do you use?
