### ISSUE TITLE
[Arc] Blurry Menu Bar icon

### ISSUE THREAD

**Issue by NicolasVaillant** [raycast/extensions#8097]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

The menu bar icon is really blurry. It's really remarkable compare to other icon.

<img width="368" alt="image" src="https://github.com/raycast/extensions/assets/77850354/1efa12aa-f018-402e-ab3a-d4d83749f470">

### Steps To Reproduce

Run extension

**Comment by danulqua** [comment]
Hi @NicolasVaillant,

Unfortunately, I am unable to reproduce it. I have a 13" MacBook Pro, but it could be an issue on modern MacBooks with a notch.

@thomaspaulmann @pomdtr @zach-fuller @ankitchouhan1020 @pernielsentikaer @danpalmer @hugivar, if anyone has it - take a look.

**Comment by NicolasVaillant** [comment]
Hum... ok. I have the same problem with GitHub extension icon...
Thank you.

Here's my system report :
•	Model Name: MacBook Air
	•	Model ID: Mac14.2
	•	Chip: Apple M2
	•	Total number of cores: 8 (4 performance and 4 efficiency)
	•	Memory: 8 GB
	•	System firmware version: 8422.141.2
	•	OS loader version: 8422.141.2

**Comment by NicolasVaillant** [comment]
OK, that's really interesting because right now the icon has no blur problem. 
The GitHub icon follows the same behavior.

<img width="404" alt="image" src="https://github.com/raycast/extensions/assets/77850354/2e2746e9-8d05-4ecd-bb4d-e5f85d7b54c7">

**Comment by hugivar** [comment]
I am unable to reproduce this either with the notch

Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,2
  Chip:	Apple M1 Max
