### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by HardIsEasy** [raycast/extensions#8102]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

Ability to select start and end time for the video to be downloaded. To speed up the download process.

**Comment by vimtor** [comment]
Hi, @HardIsEasy! (cool name btw)

I will try to implement this soon. I've tried in the past by attempting to cut the video using `ffmpeg`. However, I've realized that the `ytdl-core` library has built-in trimming, so I will give it a try and see what happens.
