### ISSUE TITLE
[Todoist] Add option to sort tasks by date added

### ISSUE THREAD

**Issue by ryan-efendy** [raycast/extensions#8105]
### Extension

https://www.raycast.com/doist/todoist

### Description

The current Todoist Raycast extension allows sorting tasks by due date, name, and priority. However, it does not provide the option to sort tasks by date added, which is available in the standard Todoist app and web UI. This feature request is to add sorting tasks in Raycast by date added, in both ascending and descending order. This would match the full functionality in the main Todoist interfaces and provide more flexibility in viewing and managing tasks.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.
