### ISSUE TITLE
[Summarize YouTube Videos with AI] ...

### ISSUE THREAD

**Issue by nukesean** [raycast/extensions#8108]
### Extension

https://www.raycast.com/iKasch/summarize-youtube-video-with-ai

### Description

Add an option to query the video transcript in AI Chat after receiving the summary and/or a separate command to enter AI Chat directly without first using the default summarization command. If a separate command, the initial prompt could tell ChatGPT to provide a summary of the video in chat first and then to be ready for follow-up questions.

### Who will benefit from this feature?

Everyone who wants to know more about the video than is included in the default summary.

**Comment by iKasch** [comment]
Hey @nukesean - There is a bigger update to the extension out now. https://github.com/raycast/extensions/pull/15972
It might not be exactly as you described but maybe it is enough for you usecases. Hope you like it.
