### ISSUE TITLE
[Weather] ...

### ISSUE THREAD

**Issue by jjr284** [raycast/extensions#8109]
### Extension

https://www.raycast.com/tonka3000/weather

### Description

Ability to switch to farenheit please :)

### Who will benefit from this feature?

Those within the United States

**Comment by tonka3000** [comment]
@jjr284 Go to the extension preferences and switch to `Imperial Units`

![CleanShot 2023-08-28 at 06 32 48@2x](https://github.com/raycast/extensions/assets/3163807/6cbc1277-4776-417d-8010-f3b7e38b4761)
