### ISSUE TITLE
Jira:  Select status when creating new issue

### ISSUE THREAD

**Issue by porcherie** [raycast/extensions#8116]
### Extension

https://www.raycast.com/raycast/jira

### Description

Add possibility to select status when creating new issue
<img width="1487" alt="SCR-20230828-luro" src="https://github.com/raycast/extensions/assets/50797800/ba7848f3-131c-43cf-b5db-55f3bf496e1e">

### Who will benefit from this feature?

everybody using intensively jira, especially when reporting urgent bugs to fix
this will remove the need to go to the backlog on Mira webpage and change status to open

**Comment by richardfontein** [comment]
I'd like to pick this feature request up

**Comment by smeevil** [comment]
We are also missing this field, @rifont are you still interested in picking this up?
