### ISSUE TITLE
YouTube Downloader: Add 192kbps MP3 download option

### ISSUE THREAD

**Issue by soguy** [raycast/extensions#8123]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

Add 192kbps MP3 download option as 128kbps is lower quality.

### Who will benefit from this feature?

All users who download audio from YouTube videos and Youtube Music using this extension

**Comment by vimtor** [comment]
Hi @soguy!

Thanks for the suggestion. @darmiel do you remember if this was an option?

**Comment by pernielsentikaer** [comment]
Did you see the answer @vimtor

**Comment by vimtor** [comment]
@pernielsentikaer yes!

If I understood @darmiel correctly, it is not possible to do this with the API by just downloading the audio.

A possible workaround would be to download the audio as a video and then remove the video part to leave the audio at 192 kbps. However, this approach would be extremely hacky and a bit misleading. I would prefer to close this issue and reconsider it if more people are interested.
