### ISSUE TITLE
[whois] IP Addresses are returning blank

### ISSUE THREAD

**Issue by alessandro-newzoo** [raycast/extensions#8125]
### Extension

https://www.raycast.com/zavbala/whois

### Description

Hello, thank you for this awesome extension!
Unfortunately, it doesn't seem to return anything when you enter an IP address, though who.is works fine with IPs.
Is this something that you think could be fixed, please? 🙏 

### Steps To Reproduce

Enter an IP in the field

### Current Behaviour

<img width="780" alt="image" src="https://github.com/raycast/extensions/assets/47320294/d7ce049e-6fc6-47bd-9c39-2c498ee7bc35">

**Comment by solid-pixel** [comment]
closing as I have implemented it myself in #8853

@raycastbot close this issue

**Comment by solid-pixel** [comment]
@raycastbot close this issue
