### ISSUE TITLE
[Spotify Player] Spotify extension not working

### ISSUE THREAD

**Issue by jp-liu** [raycast/extensions#8129]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Extending all operation commands did not work.
View gif image:

![Kapture 2023-08-29 at 18 12 20](https://github.com/raycast/extensions/assets/79979500/2bb4cba7-d69e-4bcd-82fe-b4fe2b3c08b5)

### Steps To Reproduce

1. There are no special steps, you can view the gif above

**Comment by peduarte** [comment]
Oh wow that is weird... some thoughts
- are you logged in to the same account in the app and raycast?
- can you try quitting the app and running again?
- can you try restarting raycast?

need to iron out the above first :D

**Comment by jp-liu** [comment]
Yes, I've re-downloaded the extension several times, the spotify authorization account is correct, raycast and the computer have been restarted, yet he doesn't take effect!

**Comment by jp-liu** [comment]
> Oh wow that is weird... some thoughts
> 
> * are you logged in to the same account in the app and raycast?
> * can you try quitting the app and running again?
> * can you try restarting raycast?
> 
> need to iron out the above first :D

Yes, I've re-downloaded the extension several times, the spotify authorization account is correct, raycast and the computer have been restarted, yet he doesn't take effect!

**Comment by geonzee** [comment]
same here
