### ISSUE TITLE
[Google Translate] ...Could you make the result be in english script instead of native script?

### ISSUE THREAD

**Issue by prasadbandodkar** [raycast/extensions#8132]
### Extension

https://www.raycast.com/gebeto/translate

### Description

The result is impossible to read if the script is different. It would be helpful if the translate result could be in the english script.

**Comment by gebeto** [comment]
I do not really understand the issue, can you please provide more details? and maybe some screenshots or screencasts

**Comment by prasadbandodkar** [comment]
Could the command display the Latin script version of the translation instead of the native script version? For example, in the screenshot below, could the response to “How are you?" be “Mīru elā unnāru” in the Telugu language instead of the native script that is currently displayed (attached)?

Thanks,
Prasad

-
Prasad Bandodkar

**Comment by gebeto** [comment]
I can do it like that:

show pronounce under translation for Translate Form:
<img width="862" alt="Screenshot 2023-08-31 at 20 00 45" src="https://github.com/raycast/extensions/assets/13422799/9d949229-a2eb-4575-83fb-c30010f41be3">

or for `Translate` I can just add one more row for pronounciation:
<img width="788" alt="Screenshot 2023-08-31 at 20 06 29" src="https://github.com/raycast/extensions/assets/13422799/a2f2f95d-a196-4dbd-8549-9142fb1bfd2d">

Is it works for you?

**Comment by gebeto** [comment]
PR is ready, I hope it will be reviewed soon, you will be available to use it when it will be merged

https://github.com/raycast/extensions/pull/8174

**Comment by prasadbandodkar** [comment]
Great, thanks! Looking forward to it :)

-
Prasad Bandodkar
