### ISSUE TITLE
[KeePassXC] Password security enhancements

### ISSUE THREAD

**Issue by yaronuliel** [raycast/extensions#8150]
### Extension

https://www.raycast.com/zkytech/keepassxc

### Description

It would be great if, like KeePassXC app - the extension would ask for the database password every time you lock the computer (don't know if it is possible to track screen lock via raycast... but worth trying) 

### Who will benefit from this feature?

Every user that uses the app and want extra security, and minimize the chances of unauthorized users of the machine getting access to the password database

### Anything else?

Support for TouchID unlock would also be great

**Comment by boggleboggle** [comment]
I am also concerned about this. Anyone with access to the computer (or any software for that matter) could access all the passwords. 

A possibly simple solution (not a programmer) would be to add a PIN number to the extension (perhaps easier than TouchID). Everytime you access the Keypass database, you enter the pin. No need to track the lock screen lock). Not sure if this is possible.

**Comment by artk42** [comment]
TouchID should be implemented
