### ISSUE TITLE
Backup Data Stored in Localstorage for Two-Factor Authentication Code Generator

### ISSUE THREAD

**Issue by Innei** [raycast/extensions#8159]
### Description

I've been using [Two-Factor Authentication Code Generator Plugin](https://www.raycast.com/cjdenio/two-factor-authentication-code-generator) and find it extremely useful. However, the current export configuration options do not support backing up data stored in `localStorage`, where 2FA codes are kept.

Given the critical nature of 2FA codes, having a backup is essential for account recovery and security.

Would it be possible to add a feature to backup and restore `localStorage` data related to the 2FA codes generated by this extension?

Thank you for your time and consideration.

**Comment by mathieudutour** [comment]
Could you open an feature request for the extension: https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cfeature+request&projects=&template=extension_feature_request.yml&title=%5BExtension+Name%5D+...? Otherwise the authors won't know about it
