### ISSUE TITLE
[Youdao Translate] ...Error code 222

### ISSUE THREAD

**Issue by shenyeah** [raycast/extensions#8160]
### Extension

https://www.raycast.com/tiancheng92/youdao-translate

### Description

<img width="770" alt="image" src="https://github.com/raycast/extensions/assets/44078613/37b36380-84a8-407e-9bcf-362512382c6a">

### Steps To Reproduce

type any text, return errors

**Comment by tiancheng92** [comment]
<img width="797" alt="image" src="https://github.com/raycast/extensions/assets/42594679/591f9beb-3f7c-412c-833f-a1fb005d74f0">
API Key error
