### ISSUE TITLE
[iMessage 2FA] ... After the update, substitutes '2FA' in place of the code

### ISSUE THREAD

**Issue by otakukz17** [raycast/extensions#8162]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

После последнего обновления, расширение начало брать слово 2FA, которое содержится в сообщении в качестве кода.
Мне приходят сообщения типа: "In House 2FA one-time code 892075" и расширение думает что код это 2FA, можно ли добавить его в исключение?

### Steps To Reproduce

1. Request SMS with a code 
2. Open the extension 
3. SMS with the code arrives 
4. The extension highlights "2FA" as the code 
5. No success :(

**Comment by otakukz17** [comment]
Description:
After the last update, the extension started taking the word 2FA which is contained in the message as a code.
I get messages like: "In House 2FA one-time code 892075" and the extension thinks the code is 2FA, can I add it to the exception?

**Comment by ronaldheft** [comment]
Thanks for reporting. I have a fix for this in #8177

**Comment by otakukz17** [comment]
> Thanks for reporting. I have a fix for this in #8177

Thanks for the work. I have another question, in the Raycast Store, there is no update for the extension yet. How can I update the extension?

**Comment by yuercl** [comment]
> > Thanks for reporting. I have a fix for this in #8177
> 
> Thanks for the work. I have another question, in the Raycast Store, there is no update for the extension yet. How can I update the extension?感谢您的工作。我还有一个问题，在 Raycast 商店中，扩展还没有更新。如何更新扩展？

@thomaspaulmann @arronhunt code has approved, please check the fix #8177
