### ISSUE TITLE
[SSH Connection Manager] Read connection list from ~/.ssh/config

### ISSUE THREAD

**Issue by yaronuliel** [raycast/extensions#8164]
### Extension

https://www.raycast.com/dimagrossman/ssh-manager

### Description

It would be great to have the app (at least optionally) - read ssh hosts lists from `~/.ssh/config` which is the standard place for defining remote sever, identity keys, etc. with openssh

This feature will make the extension 10x faster to getting start with, and will remove a lot of hassle from managing the connection list

### Who will benefit from this feature?

Users that already have a list of ssh server defined for openssh

### Anything else?

To fully support the `Host` definition in openssh - the `user` property of the connection should also be considered optional.
It is very common to set the connection username in the openssh config, so that connecting to a server doesn't require reentering the information on any connection

Today when the username field is left blank - the extension tries to connect to `@ssh.example.com` - which lead to an error

**Comment by pernielsentikaer** [comment]
Did you see this @scopsy

**Comment by silas229** [comment]
The extension does not recognise the Hostname.
I think it would be easier if it would just insert the alias (`ssh <alias>`)

In sshconfig:
<img width="253" alt="SCR-20231205-nbab" src="https://github.com/raycast/extensions/assets/23215125/f14853d1-7575-43af-ac85-16055e0bdb13">

In Raycast:
<img width="284" alt="SCR-20231205-nati" src="https://github.com/raycast/extensions/assets/23215125/f3d43064-f767-4f8a-bb8b-8a1e22066a41">

In iTerm:
<img width="188" alt="SCR-20231205-nbib" src="https://github.com/raycast/extensions/assets/23215125/17d5e5ba-753e-43f3-8f30-66317e81e93b">

**Comment by silas229** [comment]
unstall

**Comment by pernielsentikaer** [comment]
Can you look into that @solid-pixel

**Comment by solid-pixel** [comment]
> Can you look into that @solid-pixel

Sorry I can't, I don't have the time nor the energy to contribute at the moment.
Doesn't the extension already do what OP is asking though?

**Comment by silas229** [comment]
@solid-pixel no, it has bugs:
https://github.com/raycast/extensions/issues/8164#issuecomment-1840823197

**Comment by silas229** [comment]
.

**Comment by silas229** [comment]
.

**Comment by silas229** [comment]
.

**Comment by dongnak** [comment]
please fix https://github.com/raycast/extensions/issues/8164#issuecomment-1840823197

**Comment by pernielsentikaer** [comment]
@scopsy are you still around?
