### ISSUE TITLE
[Toggle Audio Input (microphone)] fail to mute audio input

### ISSUE THREAD

**Issue by sakaman** [raycast/extensions#8180]
### Extension

https://www.raycast.com/Quentin23Soleil/mute-microphone

#### Error:
```
Error: spawnSync /Users/foo/.config/raycast/extensions/c9ece8c4-784f-48e9-8a7a-7b67ffae12e8/assets/scripts/input-volume Unknown system error -86

Object.spawnSync:child_process:1110:20
spawnSync:node:child_process:871:24
execFileSync:node:child_process:914:15
l:toggle-mute.js:1:1098
```

### Steps To Reproduce

1.  macOS 13.4.1 22F82 x86_64 on MacBookPro16,1
2. open raycast and call command 'Toggle mute audio input'
3. report something went error

### Current Behaviour

Fail to mute input audio with the extension

### Expected Behaviour

Mute input audio successfully

**Comment by danulqua** [comment]
Hi @sakaman,

Could you DM me on [Slack](https://www.raycast.com/community) so we can test some things together?

**Comment by danulqua** [comment]
@sakaman update has been released, extension should work as expected.
