### ISSUE TITLE
[Google Bard] ...

### ISSUE THREAD

**Issue by immortalsantee** [raycast/extensions#8181]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

#### Error:

<img width="263" alt="image" src="https://github.com/raycast/extensions/assets/6284566/db9f4071-aca3-4c2a-beca-44d5f1cd54d1">
<img width="206" alt="image" src="https://github.com/raycast/extensions/assets/6284566/ce772c56-7ae3-4173-abe7-a05500adea10">
<img width="208" alt="image" src="https://github.com/raycast/extensions/assets/6284566/7a481fe5-c1cb-4f39-9fe6-0c5d5b4f1c60">

### Steps To Reproduce

1. Open bard
2. Type something
And you get the error.

**Comment by Visual-Studio-Coder** [comment]
@immortalsantee I think the Google Bard extension, which uses cookies, won't work effectively anymore. Luckily, you can now install the Google PaLM extension, which has the same functionality as Google Bard, but is more reliable and faster.

You can check it out [here](<https://www.raycast.com/EvanZhouDev/raycast-google-palm>)
