### ISSUE TITLE
[Arc] Searching Tabs doesn't open always open the correct tab

### ISSUE THREAD

**Issue by jzhang-brex** [raycast/extensions#8189]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

For example, Arc opens tab 1, tab 2 and tab 3. This plugin properly display them in the Raycast. 

However, when I select tab 1, it may open tab 2. The behavior is consistent for a certain selection. If I select tab 1 again, it will always open tab 2.

I also observe certain cases where it will open the correct tab.

### Steps To Reproduce

Mentioned in the description. Not sure how easy it is to reproduce. I don't know whether this depends on my space and tabs I have.

**Comment by davidkingham** [comment]
I have the same issue, I can reinstall the extension and it works great for about a day, then it consistently opens incorrect tabs.

**Comment by pendolino** [comment]
Same issue here has been bothering me for a while after I really loved this extension. Keeps opening the wrong tabs!

**Comment by davidkingham** [comment]
This issue still exists

**Comment by loris** [comment]
@davidkingham @pendolino @jzhang-brex just created a PR which fix the issue (but add a small delay when opening the tab), feel free to test the PR before it goes live https://github.com/raycast/extensions/pull/10017

**Comment by megaroeny** [comment]
I just tried this command (using Arc for the first time), and for me there's no results at all when using the command:

![image](https://github.com/raycast/extensions/assets/1559447/4341f21d-1136-447f-96c6-578c8f9ef598)
