### ISSUE TITLE
[BitWarden] Lock Vault crashes with `Key Connector`

### ISSUE THREAD

**Issue by sxn** [raycast/extensions#821]
# Extension – [BitWarden](https://github.com/raycast/extensions/tree/71dc0903b48af29aa0595ad456899ba7679312e0/extensions/bitwarden/)

Author: @pomdtr 

## Description

Trying to use `Lock Vault` command locks the vault, then crashes.

## Steps To Reproduce

1. Use `Search Vault`, unlock vault
2. Use `Lock Vault`

## The current behavior

Prod mode:

<img width="818" alt="image" src="https://user-images.githubusercontent.com/1155589/152741086-e428b67f-ce67-47ed-b1b1-2a1ab3d4fe02.png">

Development mode:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/1155589/152514744-89755746-8e51-4c96-a7f0-a21de516a899.png">

## The expected behavior

Vault locks, no error displayed.

### Raycast version
Version: 1.27.1

**Comment by daniel-stoneuk** [comment]
This looks like it could be an issue in the Bitwarden CLI https://github.com/bitwarden/cli/issues/439.

Should be resolved in the latest release, but I haven't tested yet since the Homebrew code hasn't been updated yet.

**Comment by pomdtr** [comment]
@mattisssa I think we can close this
