### ISSUE TITLE
VS Code Open Projects Extensions is not working[Extension Bug] 

### ISSUE THREAD

**Issue by Ansub** [raycast/extensions#822]
## Extension - [visual-studio-code-recent-projects](https://github.com/raycast/extensions/tree/b3ff5f4678170aa6225daf7bcb03922d34e40466/extensions/visual-studio-code-recent-projects/)

Author: @mathieudutour

## Description
VS Code extension to see the recent projects is not working on my MBA, I reinstalled it but still, there is no response from the extension. it just says "Something Went Wrong!"

### Raycast version
Version:  1.27.1

**Comment by Ansub** [comment]
duplicate of #808

**Comment by mattisssa** [comment]
Got the same
![CleanShot 2022-02-07 at 12 14 45@2x](https://user-images.githubusercontent.com/15333662/152759216-fdf195dd-ac8a-4c5a-8ca7-efb22da93a68.png)

**Comment by mattisssa** [comment]
Hey @thomaspaulmann! Seems like a wrong author has been mentioned here. I've checked that [the PR](https://github.com/raycast/extensions/pull/807) fixes the bug

**Comment by Ansub** [comment]
> Got the same ![CleanShot 2022-02-07 at 12 14 45@2x](https://user-images.githubusercontent.com/15333662/152759216-fdf195dd-ac8a-4c5a-8ca7-efb22da93a68.png)

getting the same error

**Comment by Ansub** [comment]
Working on my end now
