### ISSUE TITLE
[Todoist] Implement Colour-Coding for Focus Task

### ISSUE THREAD

**Issue by kud** [raycast/extensions#8232]
### Extension

https://www.raycast.com/doist/todoist

## 🌐 Current Situation
Currently, tasks that are marked as "focus" do not have any distinctive visual indicators, making them blend in with other tasks. It becomes challenging for users to quickly identify which tasks they've set their primary attention on, reducing the effectiveness of the "focus" feature.

## 🎯 Proposed Solution
Introduce a color-coding system where focus tasks are highlighted in green. This will allow users to quickly spot and prioritize their main tasks amidst other items on their list.

## 📈 Benefits
By color-coding the focus tasks, we enhance user experience by:
1. Making task management more intuitive.
2. Reducing the time users spend searching for their main tasks.
3. Potentially increasing user engagement and satisfaction with the product as tasks are more visually organized.

## 📚 Resources
User feedback has frequently mentioned the desire for visual differentiation of focus tasks. Additionally, visual cues have been proven effective in task management tools as per industry best practices.

## ⚠️ Potential Challenges
1. We need to ensure that the chosen shade of green is accessible and distinguishable by all users, including those with color vision deficiencies.
2. Consideration should be given to how the color-coding will fit with the overall design aesthetic and whether it might clash with any other existing color-coded features.
3. Users might have preferences for other colors or the ability to customize the color for their focus tasks.

## 📝 Conclusion
Introducing a color-coding feature for the focus tasks will greatly enhance the user experience by providing a clear and quick visual indicator of primary tasks. I believe that this improvement will be welcomed by our user base, making our product more efficient and user-friendly. Thank you for considering this feature request, and I'm here to answer any questions or concerns the team might have.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it?

**Comment by kud** [comment]
It's planned, as I will do it.
