### ISSUE TITLE
[Todoist] Enhanced Category Search Functionality

### ISSUE THREAD

**Issue by kud** [raycast/extensions#8233]
### Extension

https://www.raycast.com/doist/todoist

## 🌐 Current Situation
Currently, users are limited in their ability to search across different categories. This limitation results in inefficient navigation and potentially missing out on relevant content.

## 🎯 Proposed Solution
Introduce a search feature that allows users to search across any category. 

## 📈 Benefits
1. **Improved User Experience**: Users will find it easier to discover content relevant to them.
2. **Efficiency**: Reduces the time taken for users to navigate and find the content they are looking for.
3. **Increased Engagement**: With easier search options, users might spend more time on the platform exploring various categories.

**Comment by thomaslombart** [comment]
What do you mean by category?

**Comment by kud** [comment]
Project. My bad.

**Comment by thomaslombart** [comment]
But is it possible to search across all projects using the "Search" command, right? I don't think I understand what the feature request is here.
