### ISSUE TITLE
[Todoist] Menu Bar Memory/Cache Inconsistency

### ISSUE THREAD

**Issue by kud** [raycast/extensions#8234]
### Extension

https://www.raycast.com/doist/todoist

## 🥡 TL;DR
Todoist extension's menu bar shows intermittent memory/cache issues leading to display inconsistencies.

## 🐛 Issue
In the Todoist extension, the menu bar's task count fluctuates. At times it displays the correct number of tasks, and at other moments, it indicates no tasks.

## 📚 Context
This issue has been observed intermittently. When the task count drops to zero, manually clicking the icon seems to temporarily rectify the issue. However, during such fluctuations, the "focus task" is also affected. There's a suspicion that this could be related to local storage or a similar caching mechanism.

## 👎 Actual result
Intermittent display of zero tasks in the menu bar, even when tasks are present. The "focus task" is also affected during these inconsistencies.

## 👍 Expected result
The Todoist extension should consistently display the correct number of tasks without any fluctuations. The "focus task" should remain unaffected.

## 🚀 Possible Solution
Investigate the local storage or caching mechanism used by the extension. Ensure that the data fetch and cache refresh operations are working as expected without any conflicts.

## 🗺  Steps To Reproduce

- Use Todoist extension normally with tasks added.
- Notice the task count showing correctly on the menu bar.
- After some time, observe the task count dropping to zero.
- Clicking the Todoist icon restores the task count but affects the "focus task".

**Comment by kud** [comment]
Here we go @thomaslombart 


https://github.com/raycast/extensions/assets/655838/778355bb-582c-4431-9b21-af486968c8b5

**Comment by thomaslombart** [comment]
Have you noticed a pattern on when it happens? The extension is supposed to refresh the data every 10 minutes so this should (theoretically) rarely happen.

**Comment by kud** [comment]
It happens every time. Since we've discussed and now, the issue came back.

I will try to find the pattern why it happens.

**Comment by kud** [comment]
It's every 10min apparently yeah.

With those options: 
![screenshot-2023-09-04-15-32-57](https://github.com/raycast/extensions/assets/655838/b67bfd05-80ee-450e-a2b7-ffb657c53da0)

**Comment by kud** [comment]
It's still a big issue (to me). I will check what's going on there.

**Comment by kud** [comment]
Still here.

**Comment by kud** [comment]
https://github.com/raycast/extensions/assets/655838/344537f4-b651-41ea-b3c3-5a6efbe69583
