### ISSUE TITLE
[Espanso] Copies "Label" field instead of "Replace" field.

### ISSUE THREAD

**Issue by AbhishekTripathi** [raycast/extensions#8235]
### Extension

https://www.raycast.com/kud/espanso

### Description

First of all thanks for this extension. The idea is very neat. I hope when the issue is fixed, it will be part of my workflow and will boost my productivity.

The expectation is that when I am searching for a snippet, the search should be both on the trigger, and on the label field. The output of the search should ideally show the trigger, and the replace parameter but copy the replace parameter by default. Currently, it is copying the label field which is useless as it is a description of the snippet.

A sample snippet:

```
    - label: Bug emoji
      replace: 🐛
      trigger: "!ebug"
```

### Steps To Reproduce

Make a new snippet in your espanso config file as provided in description of this bug. 

Case 1: Try to search for espanso config with text "emoji". 
Case 2: Try to search for espanso config with text "bug".

### Current Behaviour

Case 1: There is no match found.
Case 2: The match is found. However, the right window shows the snippet label text "Bug Emoji" instead of replace value. Pressing "Enter" copies the label text.

### Expected Behaviour

Case 1: The match should correctly filter the snippets based either on label or on the trigger field.
Case 2: The matched entity should copy the trigger by default. The right window can be enhanced to show full snippet details but pressing enter should copy the replace value.

@kud please have a look.

**Comment by kud** [comment]
I was not aware of the field `label`. I've just tried it, it's a great one! It will make the list way cleaner!

Thanks for suggesting.

**Comment by nbbaier** [comment]
Yeah this is really cool!

**Comment by kud** [comment]
Got an issue with espresso for now. Need to wait an answer before being able to do something.

https://github.com/espanso/espanso/issues/1702

**Comment by kud** [comment]
I'm sorry, but for now, this issue is blocked. I can't do anything other than wait for the issue on Espanso. I hope it will be resolved soon or a workaround will be available.

**Comment by kud** [comment]
I did my best https://github.com/espanso/espanso/pull/1720 but espanso seems not to be so active those days.
