### ISSUE TITLE
[YouTube] Create a compact view in order to emphasize the video titles

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#8243]
### Extension

https://www.raycast.com/tonka3000/youtube

### Description

I'm the author of the YouTube workflow for Alfred:

<img width="745" alt="Screenshot 2023-09-04 at 23 27 32" src="https://github.com/raycast/extensions/assets/11052366/b39311a4-d911-424e-865b-8e3bfb0b814c">

After switching to Raycast from Alfred, this is one of the few Alfred workflows that I couldn't stop using. The problem is that the YouTube Raycast extension barely shows the video titles:

<img width="886" alt="Screenshot 2023-09-04 at 23 25 40" src="https://github.com/raycast/extensions/assets/11052366/f7911d1a-1388-423e-b57a-e940987bb632">

I acknowledge the visual appeal of thumbnails, but in this situation, they compromised the selection of a video based on its content, which is best represented by the title.

To address this, I suggest providing a compact view that prioritizes the video titles, even if displaying thumbnails is not feasible.

**Comment by tonka3000** [comment]
Switch the view layout in the extension preferences to list instead of grid.

**Comment by xilopaint** [comment]
> Switch the view layout in the extension preferences to list instead of grid.

Oh, sorry! I can't believe I didn't notice that setting 🫠

**Comment by tonka3000** [comment]
No big deal, glad I could help.
