### ISSUE TITLE
[Hue] General "Something went wrong" Error when accessing "Control Lamps" Command

### ISSUE THREAD

**Issue by bjesuiter** [raycast/extensions#8247]
### Extension

https://www.raycast.com/pindab0ter/hue

#### Error:
```
Error: ENOENT: no such file or directory, open '/Users/bjesuiter/.config/raycast/extensions/1437e84a-8af7-4574-aca7-296de9ac06ea/assets/icons/plug.png'


```

### Steps To Reproduce

Simply try to run the "Control Lights" Command with a working hue bridge setup. 

### Current Behaviour

I get this error screen: 

<img width="862" alt="Bildschirmfoto 2023-09-05 um 10 57 26" src="https://github.com/raycast/extensions/assets/2365676/0932fc3d-dcd0-4edc-83ac-f2c90db9eea7">

BUT: When using "set Scene" it works flawlessly!

I also added the Hue Bridge IP manually to make sure it is found. 

### Expected Behaviour

The command works (i've never seen it working, i suspect, it shows a list of your light devices?)

**Comment by pindab0ter** [comment]
@raycastbot close this isssue

**Comment by pindab0ter** [comment]
@raycastbot close this isssue
