### ISSUE TITLE
[Search Zotero] Add Item by Identifier

### ISSUE THREAD

**Issue by 3e9b** [raycast/extensions#8250]
### Extension

https://www.raycast.com/reckoning-dev/zotero

### Description

Zotero has the feature to add item by identifier (ISBN, DOI). It would be helpful to make a command inside of this extension that can directly do that.

https://www.zotero.org/support/adding_items_to_zotero#add_item_by_identifier

### Who will benefit from this feature?

Anyone who uses Zotero or opens Zotero mostly to add items.

### Anything else?

Thanks!

**Comment by sadanand-singh** [comment]
Adding items to zotero database is whole another beast under the hood. I do not have time to develop a whole another app/extension. If you look at the code currently, to avoid file race conditions, I currently maintain a raycast copy of the sqlite db file. For doing anykind of write operation, this whole part has to be rewritten and redesigned.

**Comment by sadanand-singh** [comment]
Thats why command is called “search zotero” not another zotero app!

**Comment by sadanand-singh** [comment]
@raycastbot close this issue
