### ISSUE TITLE
[CleanShot X] Commands are too quick

### ISSUE THREAD

**Issue by WilliamWelsh** [raycast/extensions#8256]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

When using any screenshot command, like capture area or OCR, sometimes Cleanshot loads too fast and Raycast is still visible. This is an issue if you want to screenshot, or OCR, something behind the Raycast window and it doesn't dismiss. I think there needs to be a small quarter second sleep or something.

### Steps To Reproduce

1. Run "Capture Area" or "OCR" from Raycast

### Current Behaviour

Raycast window is still visible after running the command

### Expected Behaviour

Raycast window is not visible after running the command

**Comment by erics118** [comment]
I will fix this after #8254 is done.

**Comment by Aayush9029** [comment]
@erics118 were you able to replicate this issue? I have been unsuccessful at reproducing it.

We can always add a "custom delay" preference if the issue is persistent among others.

**Comment by WilliamWelsh** [comment]
Maybe if closeMainWindow is called before running open?

**Comment by erics118** [comment]
> @erics118, were you able to replicate this issue? I have been unsuccessful in reproducing it.
> 
> 
> 
> We can always add a "custom delay" preference if the issue is still persistent among others.

no
