### ISSUE TITLE
[TickTick] Support 'Quick Add Task' like Raycast Todoist extension

### ISSUE THREAD

**Issue by dudido** [raycast/extensions#8264]
### Extension

https://www.raycast.com/appest/ticktick

### Description

I would like to be able to quick add tasks in a similar way to the Todoist extension straight from the input line, rather than opening a separate dialog box.

### Who will benefit from this feature?

Everyone, who wants to create tasks using TickTick

**Comment by viduycheung** [comment]
Wait for raycast to review and publish it. https://github.com/raycast/extensions/pull/8275

**Comment by viduycheung** [comment]
@raycastbot close this issue

**Comment by dudido** [comment]
Thank you!

**Comment by nhamlani101** [comment]
Hi, when creating the quick task it doesn't follow the default due date of any todo items, as in there is no due date assigned, when my TickTick level preferences show that default is "today". Can this be fixed?
