### ISSUE TITLE
[TickTick] Set defaults for list/due date for 'Add Task' in Raycast extension settings

### ISSUE THREAD

**Issue by dudido** [raycast/extensions#8265]
### Extension

https://www.raycast.com/appest/ticktick

### Description

I would like to be able to set defaults for the list and the due date in the extension settings for the 'Add Task' command.

### Who will benefit from this feature?

Everyone, who wants to create new tasks more quickly. Usually the targets are the same, and sometimes you want every new task to default to today or tomorrow for example. Choosing them from drop-down lists is tedious.

**Comment by viduycheung** [comment]
Wait for raycast to review and publish it.

**Comment by viduycheung** [comment]
The `Add Task` command will remember your last selection, it can almost do the default list thing.

**Comment by viduycheung** [comment]
@raycastbot close this issue

**Comment by dudido** [comment]
Is it possible to add a List field to the new Quick Add Task command, too?

**Comment by viduycheung** [comment]
> Is it possible to add a List field to the new Quick Add Task command, too?

The “no view” command in Raycast only supports text or password arguments. As such, there isn’t an optimal solution for selecting list in the command.
