### ISSUE TITLE
[Todoist] Set default for due date, priority, projects labels for Quick Add Task & Create Task commands of Raycast Todoist extension

### ISSUE THREAD

**Issue by dudido** [raycast/extensions#8266]
### Extension

https://www.raycast.com/doist/todoist

### Description

I would like to be able to set default for the options due date, priority, projects labels for the ‘Quick Add Task‘ & ‘Create Task‘ commands in the settings of the Raycast Todoist extension.

### Who will benefit from this feature?

Everyone, who wants to quickly change the defaults when creating new tasks. Choosing these from drop-down lists in dialog boxes is tedious.

**Comment by thomaslombart** [comment]
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

**Comment by dudido** [comment]
I'm not a developer. Sorry @thomaslombart
