### ISSUE TITLE
[Confluence] Unable to authenticate using Personal Access Token

### ISSUE THREAD

**Issue by andrewip** [raycast/extensions#8269]
### Extension

https://www.raycast.com/tbrown/confluence

### Description

My company uses an internally hosted instance of Confluence.  Previously, I was able to authenticate and access Confluence using my Personal Access Token; however, I'm now being asked to log into my Atlassian account, which I do not have.

### Steps To Reproduce

Assuming you are unauthenticated, invoke the Confluence extension.  The user is then presented with a dialog to log into their Atlassian account.

<img width="746" alt="Screenshot 2023-09-06 at 10 03 00 AM" src="https://github.com/raycast/extensions/assets/634450/e32f9f04-9118-4536-9109-5bbad5e6ff44">

### Current Behaviour

The extension asks me to log into my Atlassian account.

<img width="746" alt="Screenshot 2023-09-06 at 10 03 00 AM" src="https://github.com/raycast/extensions/assets/634450/f1222f55-0d80-46ef-b93f-901c97005eea">

### Expected Behaviour

In the extension configuration, I should be able to specify where my company's internal instance of Confluence is and be given the means to provide a personal access token.

**Comment by TreZc0** [comment]
Can we maybe restore the old confluence extension as confluence (data-center) for now, until this is resolved? Similar strategy to jira i guess.

**Comment by andrewip** [comment]
@TreZc0 That would be awesome if you can.

**Comment by andrewip** [comment]
Are there any timelines for when the old extension can be restored?

**Comment by TreZc0** [comment]
Would like to bump this again.

**Comment by andrewip** [comment]
@daviddkkim Can you take a look to see if the old Confluence extension can be restored?

**Comment by zopfli** [comment]
Hi! Would it not be better to allow the user to _either_ use a PAT and URL _or_ use the cloud authentication?

**Comment by LorenzKahl** [comment]
This is still relevant for people locked in to corporate on-premise solutions.

**Comment by andrewip** [comment]
Seems like Tyler Brown is the current maintainer.  Does anyone know how to contact him?  His profile says "@tbrown", but I can't find it in GitHub.

**Comment by LorenzKahl** [comment]
This is still relevant and yet to be solved
