### ISSUE TITLE
[Open in Visual Studio Code] fails to detect VS Code installation

### ISSUE THREAD

**Issue by chambliss** [raycast/extensions#8271]
### Extension

https://www.raycast.com/shubzkothekar/open-in-visual-studio-code

### Description

Hi! My VS Code installation isn't being detected by the extension for some reason. I have used this extension successfully in the past, so I'm not sure exactly when this behavior changed. 

I thought at first that it was because I recently replaced my VS Code installation with the arm64-specific build instead of the darwin-universal build, but when I tested this again with the darwin-universal build, the installation is still not detected. 

Here's my output from About for my VS Code installation:
```
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:40:25.698Z (3 wks ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0
```

Screenshot of the issue:

![Google Chrome-2023-09-06 at 09 08 05AM](https://github.com/raycast/extensions/assets/43484165/e2d0a8cf-f206-4f67-9f04-1ac3d09711c9)

### Steps To Reproduce

1. Select folder in Finder to open in VS Code
2. Open Raycast and run "Open in Visual Studio Code"
3. Observe message "Visual Studio Code is not installed" 

### Current Behaviour

The folder/project fails to open in VS Code / VS code installation is not detected

### Expected Behaviour

Installation is detected and folder opens

**Comment by shubzkothekar** [comment]
@chambliss Go to extension settings and make sure that the `Visual Studio Code` is selected. If that doesn't fix this issue then can you tell me what is the bundle id of VS Code that you installed.
