### ISSUE TITLE
[My Daily Log] ...

### ISSUE THREAD

**Issue by bakari45** [raycast/extensions#8272]
### Extension

https://www.raycast.com/frugoman/my-daily-log

#### Error:
```
Error: ENOENT: no such file or directory, open '/Users/bakari/Documents/DailyLog/2023-09-07.json'

Object.openSync:node:fs:601:3
Object.writeFileSync:node:fs:2249:35
Re.saveLogs:createLogCommand.js:30:2617
Re.create:createLogCommand.js:30:2824
```

### Steps To Reproduce

Opened the log window and wrote a log. 

### Current Behaviour

I'm trying Daily Log for the first time, but I get an error message when I try to submit a log. 

### Expected Behaviour

Expect it to save the log.

**Comment by frugoman** [comment]
@bakari45 I've fixed this issue! Please give it a try!!

Thanks for reporting it! Feel free to close it if it's resolved for you!

**Comment by bakari45** [comment]
Yes, thanks, it works now. 
Do you think you will ever enlarge the input text window to make it easier to edit text or write longer logs?
