### ISSUE TITLE
Change sorting in Apple Notes extension

### ISSUE THREAD

**Issue by mattisssa** [raycast/extensions#829]
# Extension – [Apple Notes](https://github.com/raycast/extensions/tree/1c453d15151d48909a4e4f0bc0afe1d863511bd1/extensions/apple-notes/)
Author: @tumispro

## Description
As I can see now the notes are randomly sorted in the `Search Notes` command. I think it would be nice to have a portion option by **last updated** or something like that.

**Comment by tumispro** [comment]
It should be sorted by last modified date. Can you confirm that this is not the case for you?

**Comment by tumispro** [comment]
The order might be different for different users. Currently investigating in https://github.com/raycast/extensions/pull/891.

**Comment by axhamre** [comment]
@tumispro I don't know if this was ever fixed or if there's been a regression, but when searching it's not sorted chronologically for me:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/1907343/177013114-71f8dda2-34d5-4d56-8ac5-34a848a2b18e.png">

**Versions**
Raycast: 1.37.1
macOS: 12.4
Notes: 4.9

**Comment by tumispro** [comment]
@axhamre Weird, I can indeed reproduce. I'll look into a fix asap, thanks for reporting!

**Comment by tumispro** [comment]
@axhamre I have quickly checked, but it seems this is just Raycast's algorithm picking the order of the results and I can't really influence that.

**Comment by axhamre** [comment]
Interesting. It kind of have made sense if the algo was great, but currently it appears to be broken.

And you're sure about your assumption? Invoking "Search Notes" with no filtering is sorting correctly, as well as filtering the clipboard history and snippets.

**Comment by tumispro** [comment]
I'm pretty sure I can't influence search results, only the items to search through. Perhaps @ron-myers could confirm.
