### ISSUE TITLE
[Amazon AWS] Add support for credentials from credentials file 

### ISSUE THREAD

**Issue by andreacavagna01** [raycast/extensions#8291]
### Extension

https://www.raycast.com/Falcon/aws

### Description

I want to read short-lived credentials directly from the credentials file, including AWS Session Token

### Who will benefit from this feature?

I can start using Leapp and switch profile from them

**Comment by JonathanWbn** [comment]
@andreacavagna01 This extension is already supposed to support reading from the credentials file. Can you share how this is not working for you? It might also be useful to share your `config` and `credentials` file (redacted, of course), so that I can reproduce the issue.
