### ISSUE TITLE
[API Feature Request] List + Detail (side-by-side) view

### ISSUE THREAD

**Issue by Talor-A** [raycast/extensions#83]
I would love to see this view present in the "file search" feature to be exposed to the extensions API.

<img width="862" alt="Screen Shot 2021-10-15 at 9 04 57 PM" src="https://user-images.githubusercontent.com/11509865/137641845-e7fb443f-7bdf-4a8d-aeed-76afc13ba553.png">

**Will this change the current api? How?**
add a way to render this view to the List or ListItem component. 

**Who will benefit with this feature?**
anyone who is interested in viewing list items inline quickly, e.g. details on a github issue in the github extension, a preview of comments in the hacker news extension, file previews in the google drive extension.

**Comment by sinewave** [comment]
+10 Agreed. Would love to see support for this as well!

**Comment by kevinwhoffman** [comment]
Agreed. This view would be especially valuable for previewing images and their meta data returned by a remote API.

**Comment by alexheyd** [comment]
Similarly, if the List+Details could be stacked as well that'd be great, like the way it is in the "My Schedule" command

**Comment by Innei** [comment]
+1

**Comment by FezVrasta** [comment]
I would like to be able to switch between the list view and this one, so that pressing enter on a row opens the side panel
