### ISSUE TITLE
[Gmail] Search Email

### ISSUE THREAD

**Issue by dtmunir** [raycast/extensions#8306]
### Extension

https://www.raycast.com/tonka3000/gmail

### Description

I would like to be able to search my Gmail from anywhere on my computer. Eg. I'm looking at my calendar in VimCal, and want to be able to see all the past emails associated with a person, to remind me of the context. I should be able to see the subjects of my most recent emails involving this person, and then be able to launch into any of those emails.

### Who will benefit from this feature?

Anyone who uses Gmail and needs to recall the history and context around an  individual

**Comment by tonka3000** [comment]
@dtmunir Hi,

The feature is partially already in the extension. You can show mails from a specific sender via the `Filter Mails from Sender` action (this just set the `from:<address>` in the search). The thing which is missing is that you get the address from another app.

The only way which would make sense to me would using the selected text. Can you select the address in VimCal?

You can already create custom quicklinks for specific queries and I'm think to add some marker to support selected text e.g.
`from:%SELECTED_TEXT%`. That would make it very easy to customize it for your needs.

If you can not mark the address maybe some applescript can help to extract the info.
