### ISSUE TITLE
[gopass] could not load or copy passwords

### ISSUE THREAD

**Issue by tjex** [raycast/extensions#8319]
### Extension

https://www.raycast.com/bake/gopass

### Description

gopass extension finds, displays and navigates my password-store filetree fine, but shows the error "could not load passwords" and "could not copy passwords".

I'm using an existing password store from `pass`. 

`gopass mounts` returns "No mounts", despite a path being generated and present in `.config/gopass/config`

### Steps To Reproduce

1. MacOS 13.5, raycast 1.58
2. password store generated with `pass` but with `gopass` generated files as well.
3. config: 
```text
core.autopush = true
core.autosync = true
core.cliptimeout = 45
core.exportkeys = true
core.notifications = true
mounts.path = /Users/tjex/.local/share/password-store
```
could not load:
![Screenshot 2023-09-10 at 19 48 55](https://github.com/raycast/extensions/assets/83029642/bdaf2ae6-8e1e-4d70-9331-8cdd9086eb9a)

could not copy:
![Screenshot 2023-09-10 at 19 49 09](https://github.com/raycast/extensions/assets/83029642/d20e9813-b8a1-4e87-a7b0-14eec4687acb)

### Current Behaviour

displays password store, but does not copy passwords.

### Expected Behaviour

copying passwords to clipboard.

**Comment by miagg** [comment]
Same case here! Only copies password if I unlock using cli tool. After 15 minutes it stops working since it needs to be unlocked again using master password.

**Comment by tjex** [comment]
@miagg Hmm. That makes sense to a degree, as the timeout has to do with gpg-agent timing out (and needing a password again). But I have my gpg-agent timeout set to a day, and even if I try straight after using gopass successfully via the CLI, I cannot copy my passwords.

Could you give me some more steps as to how you're able to copy your passwords from Raycast? Maybe I can figure out why it's not working for me. 

In your case, you could also consider setting your gpg-agent timeout longer. It sounds like that may be the only thing stopping you.

**Comment by miagg** [comment]
> @miagg Hmm. That makes sense to a degree, as the timeout has to do with gpg-agent timing out (and needing a password again). But I have my gpg-agent timeout set to a day, and even if I try straight after using gopass successfully via the CLI, I cannot copy my passwords.
> 
> Could you give me some more steps as to how you're able to copy your passwords from Raycast? Maybe I can figure out why it's not working for me.
> 
> In your case, you could also consider setting your gpg-agent timeout longer. It sounds like that may be the only thing stopping you.

I did nothing other than installing the gopass extension from the Raycast store and gopass from homebrew. Like you, I was using pass. Everything worked out of the box. It mounted my password store automatically, though I too get `No mounts` when I run `gopass mounts`.

I also did increase the cache ttl and now I have no issues. I only have to unlock the first time from terminal.
