### ISSUE TITLE
[Todoist] Make focus task extendable (e.g. automatically start a toggl timer)

### ISSUE THREAD

**Issue by tonyxiao** [raycast/extensions#8323]
### Extension

https://github.com/raycast/extensions/blob/779372ddbeca3eafa477a1bb73e6093fc4117b99/extensions/todoist/README.md

### Description

Focus task is awesome, but it is totally redundant to then separately go to toggl to start a time entry for it. I wish I could combine those two actions in one. This should ideally be extendable so other users can define their own custom actions that happen when a task is focused on. 

### Who will benefit from this feature?

Anyone using a time tracker together with their Todoist

**Comment by thomaslombart** [comment]
Thanks for the feature request. What do you have in mind for that?
