### ISSUE TITLE
[Anybox] ...Could not communicate with command worker [API Exception]

### ISSUE THREAD

**Issue by yuemingming** [raycast/extensions#8328]
### Extension

https://www.raycast.com/anybox/anybox

### Description

I encountered the error in the title when I executed the extenstion of AnyBox.

### Steps To Reproduce

*

**Comment by ImNag** [comment]
I'm facing this issue after updating v2 of Anybox app. Not sure, if it relates to the communication problem of Anybox extension in Raycast. But, yeah - it stopped working.

**Comment by francisfeng** [comment]
@yuemingming @ImNag 

Yeah, the extension also needs to be updated to 2.0.

I’ve opened a PR at https://github.com/raycast/extensions/pull/8318

Hopefully it can get merged soon.

**Comment by francisfeng** [comment]
The PR was merged. Should be fine by now.

@ImNag @yuemingming
