### ISSUE TITLE
[GrammariX] ...

### ISSUE THREAD

**Issue by Visual-Studio-Coder** [raycast/extensions#8348]
### Extension

https://www.raycast.com/hakob_nersesian/grammari-x

### Description

Just use the Raycast AI api, so pro users can just use it without the necessity for an API Key

### Who will benefit from this feature?

Pro users

### Anything else?

Maybe if the person DOESN'T have pro, then allow them to input an api key instead

**Comment by hakob8956** [comment]
@raycastbot close this issue
