### ISSUE TITLE
[ChatGPT] Would like to add inline functionality

### ISSUE THREAD

**Issue by 0x0-00** [raycast/extensions#8352]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Enter a keyword (e.g. /gpt) + ask a question + trigger a keystroke within an app 
->
Let ChatGPT generate the result as a stream within the current app

### Who will benefit from this feature?

everyone

### Anything else?

![inline2](https://github.com/raycast/extensions/assets/49114841/5475a2c4-c582-4b34-b838-017069e6f6ea)

**Comment by hyuri** [comment]
Yes, please. Essential. So we can also have, for example:
`timer 30s`
