### ISSUE TITLE
[Toothpick] Disconnecting device

### ISSUE THREAD

**Issue by kvzivn** [raycast/extensions#8353]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

Disconnecting my bluetooth speaker doesn't work.

### Steps To Reproduce

Using the Toothpick disconnect device function from either the device management screen or the disconnect command.

### Current Behaviour

Says it's disconnnect sucessfully but it's not.

### Expected Behaviour

Should properly disconnect the device.

**Comment by VladCuciureanu** [comment]
Please try installing blueutil via brew and changing the bluetooth backend to blueutil from the extension's settings. This is a feature recently added to bypass exactly this issue.

**Comment by kvzivn** [comment]
@VladCuciureanu When i'm using `blueutil` I'm getting the following error when trying to run either "Manage Bluetooth Connections" or "Disconnect Device"

```
TypeError: Cannot read properties of undefined (reading 'getDevices')

Kn:manage-bluetooth-connections.tsx:7:41

---
4: import { Device } from "./core/devices/devices.model";
5: 
6: export default function ManageBluetoothConnectionsView() {
7:   const [loading, setLoading] = useState(true);
8:   const [devices, setDevices] = useState<Device[]>([]);
9: 
0:   const { bluetoothBackend } = getPreferenceValues();
---

Ir:index.js:9:2490
    at ray-navigation-stack
$o:index.js:9:2088
```

**Comment by VladCuciureanu** [comment]
Can you give me the result of running 'which blueutil' in terminal?

**Comment by kvzivn** [comment]
Ah sorry, hadn't installed `blueutil`. Works now. Thanks for quick replies! Great extension!

**Comment by VladCuciureanu** [comment]
Thanks! Glad you like it. I'll look into that 'disconnect favorite device' command. Maybe it will pop up in the next update

**Comment by VladCuciureanu** [comment]
@raycastbot close this issue
