### ISSUE TITLE
[Todoist] Can't add a date to task

### ISSUE THREAD

**Issue by brunocbreis** [raycast/extensions#8354]
### Extension

https://www.raycast.com/doist/todoist

### Description

When I try to use the Create Task command, all fields work except the Date one, which allows me to select a date but doesn't register the input

https://github.com/raycast/extensions/assets/85531625/e335aaf9-c9a7-45c8-a2fe-aa50aa948f66

### Steps To Reproduce

1. Open Create Task
2. Try to add date to a task

### Current Behaviour

Creates task without selected date

### Expected Behaviour

Should add the date

**Comment by thomaslombart** [comment]
Fixed as part of v1.58.1.
