### ISSUE TITLE
[Library Genesis] Searching does not work

### ISSUE THREAD

**Issue by Mdejonge** [raycast/extensions#8355]
### Extension

https://www.raycast.com/yz3440/library-genesis

### Description

When searching for books an exception is thrown: `p.replace is not a function`

### Steps To Reproduce

1. Install the app for ray
2. Search for a book
3. Get's error `p.replace is not a function`

**Comment by Mdejonge** [comment]
The problem is caused because i am unable to connect to http://gen.lib.rus.ec/. Maybe skip the url if an exception is received?

**Comment by nununo** [comment]
I'm getting the same error.

**Comment by Mdejonge** [comment]
@nununo A temporary solution is in the settings of the extension to add `https://libgen.is/` to the Preferred Libgen Mirror.

**Comment by yz3440** [comment]
Hi folks! Thank you so much for reporting these bug. The truth is the mirror picking mechanism was not well thought out and pretty hacky. I'm working on a fix now, but I can't promise an quick updates given my recent schedule.

### Some Background

I was using a [npm package for fetching libgen url](https://www.npmjs.com/package/libgen) which doesn't really work. I'm planning to encode a few well-known libgen mirrors and ping them to choose the best mirror manually. While picking out the mirrors, I realized there is [this type of mirror](https://libgen.is/) and [that type of mirror](http://libgen.gs/), having different UIs. I want to include them both to maximize the chances of hitting a usable mirror, but my old html parser doesn't work on the latter one. I'll be tackling these problem one by one.

@Mdejonge Thank you for saying the what I was going to say! I should probably encode the instruction if none of the candidate mirrors are reachable.

Anyways, thank you all so much for using my extension! I hope you find it useful as I do. Happy reading!
