### ISSUE TITLE
[Bitwarden Vault] Extension encountered an error

### ISSUE THREAD

**Issue by raphtlw** [raycast/extensions#8360]
### Extension

https://www.raycast.com/jomifepe/bitwarden

#### Error:
```
Error: Command failed with Unknown system error -86: /Users/raphael/Library/Application Support/com.raycast.macos/extensions/5fdb86d3-dfcc-45a7-8969-8113b51434ab/bw-2023.8.2 lock
spawn Unknown system error -86

ChildProcess.spawn:child_process:413:11
Object.spawn:node:child_process:757:9
je:search.js:47:4352
```

### Steps To Reproduce

1. in any macOS version running the latest version of raycast
2. run any bitwarden command

**Comment by jomifepe** [comment]
Hello @raphtlw, sorry for the inconvenience, the extension recently stopped requiring the installation of the CLI and that may be the cause of the issue.

Can you tell me if you see any message saying "Initializing Bitwarden CLI" once you launch a command, before the error?

**Comment by raphtlw** [comment]
> Hello @raphtlw, sorry for the inconvenience, the extension recently stopped requiring the installation of the CLI and that may be the cause of the issue.
> 
> Can you tell me if you see any message saying "Initializing Bitwarden CLI" once you launch a command, before the error?

Hi, the issue was caused because I hadn't installed rosetta on my m1 mac. While I no longer need the support, I did not see any message coming up in the raycast window when I tried to run Bitwarden. Is the node rpc interface just not aarch64?

Thanks for the help,

Raphael
