### ISSUE TITLE
[Music]: Error when using "love and add track to library"

### ISSUE THREAD

**Issue by Aparikk** [raycast/extensions#8365]
### Extension

https://raycast.com/fedevitaledev/music

### Description

Command failed with exit code 1: osascript -e tell application "Music" to set loved of current track to true 
28:62: execution error: „Music“ hat einen Fehler erhalten: Die Typen der Deskriptoren passen nicht. (-10001)

### Steps To Reproduce

1. Apple Music playing
2. Open Raycast and type in love
3. use the "love and add to library" command

**Comment by rawnly** [comment]
#8648 fixes this

**Comment by rawnly** [comment]
@raycastbot close this issue
