### ISSUE TITLE
[Todoist] Please make a command for opening the focused task

### ISSUE THREAD

**Issue by smut-ny** [raycast/extensions#8382]
### Extension

https://www.raycast.com/doist/todoist

### Description

Focus task is really awesome feature and it extends the Todoist usability in a new way. Right now I am able to mark any task to be focused -> as far as I know it means that task is displayed in menu bar. But I would love to just open raycast and hit a shortcut to quickly display description of that focused task.

### Who will benefit from this feature?

I think it's really great for productivity because you can focus on the task you are working at the moment and you can preview the description without any additional searching. Also there is a community of ADHD people who use todoist. I asked on reddit and there is no similar feature in todoist. I think this command would be hugely beneficial!

**Comment by kud** [comment]
Hey @smut-ny , hope you're going well.

I'm not sure I understand the feature exactly. Would you like to have a window that shows the task that is currently in focus, in addition to the menu bar?

**Comment by smut-ny** [comment]
Hey @kud, thank you for reply!

Use case would be something like this.

This is current functionality:
1. You go into "Home" in raycast.
2. Find a task. Cmd + F to focus on the task.

This will show the title in menu bar, but as far as I know this is where the focus feature ends.

New feature I am suggesting:
In Raycast todoist extension add new command "Open focused task":
<img width="755" alt="Screenshot 2023-09-14 at 13 27 05" src="https://github.com/raycast/extensions/assets/34166011/5632c200-1987-4529-98f1-37a235d89507">


 By using the command it opens the focused task in Raycast this way:

<img width="758" alt="Screenshot 2023-09-14 at 13 19 10" src="https://github.com/raycast/extensions/assets/34166011/46cc8cb4-0357-4bec-972b-543b893f6ae9">

So imagine you are working on some issue you have saved in todoist. You just mark the task in raycast as focused. And anytime you want to check the description or change something inside the task, you don't have to open todoist app or find the task in search. You just hit raycast command "Open focused task" and it will show you all the informations in raycast window. 
By making it a raycast command you can map an alias or record hotkey to it, this way you'll quickly preview/open the task you decided to focus on.

I hope this explanation is clear and someone else might find it useful.

**Comment by kud** [comment]
Okay, simple as it is. It's just a shortcut to open the detailed page of the currently focused task.

Makes sense, should be easy to do. I'll see what I can do. 😌

**Comment by smut-ny** [comment]
@kud Thank you for looking into it! This feature would be fire 🔥

**Comment by kud** [comment]
Still working on it.

**Comment by smut-ny** [comment]
@kud Hi Kud, any news on this request? I am reminding, so it won't get forgotten. 😊

**Comment by kud** [comment]
Oh it's not :D struggling a bit with Raycast and time at the moment. 😌

**Comment by smut-ny** [comment]
Thanks for update! :)

**Comment by kud** [comment]
https://github.com/raycast/extensions/pull/8969

**Comment by kud** [comment]
Enjoy @smut-ny

**Comment by smut-ny** [comment]
You are best thank you so much! :)
