### ISSUE TITLE
[Time-Traveling World Clock] Custom naming

### ISSUE THREAD

**Issue by chrisrowe** [raycast/extensions#8383]
### Extension

https://www.raycast.com/marky/world-clock

### Description

Hey! I would love to be able to add custom labels/titles to the timezones I add. For a distributed team just seeing the names of people and their times is a lot easier to digest than cities and times.

**Comment by koinzhang** [comment]
@chrisrowe If you add a time zone to your favorites (⌘+S), you can set aliases, icons, and notes for it (⌘+E)
<img width="400" alt="image" src="https://github.com/raycast/extensions/assets/36128970/5d7f27fa-b7c0-4462-a223-9f0aaff2c37a">

<img width="400" alt="image" src="https://github.com/raycast/extensions/assets/36128970/55ad58fa-1326-4256-9dd5-0db3ce76c1c2">

**Comment by chrisrowe** [comment]
![](http://up.chri.sr/Screen-Shot-2023-09-14-10-17-34.54-1694683055.png)
I don't see an option for that, I checked for updates too

**Comment by chrisrowe** [comment]
Ah you're using a different extention https://www.raycast.com/koinzhang/world-clock

**Comment by koinzhang** [comment]
@himarky Hi, can you improve the extension's profile so that the extension's name and title correspond? Try to avoid using the same name as the World Clock extension!
<img width="454" alt="image" src="https://github.com/raycast/extensions/assets/36128970/70040bc2-664f-4aab-b58b-a33fec3adace">

**Comment by mathieudutour** [comment]
> What do you think about this issue?

Ah yep sorry about that, I just fixed the script so it won't happen again
