### ISSUE TITLE
[Bitwarden] is slow loading vault items and copying passwords

### ISSUE THREAD

**Issue by IvoVermeer** [raycast/extensions#8387]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Since a couple days, whenever I do s a search in my vault, it's very slow to load vault items. Sometimes it's also slow when copying a password.
<img width="618" alt="image" src="https://github.com/raycast/extensions/assets/5347891/8d33b90f-e81b-46c2-b0e7-7f52f6ff80b4">

### Steps To Reproduce

1. Hit the raycast shortcut (⌘ + Space for me)
2. Search for the bitwarden vault command
3. Do a search (for me there's now a delay of 7 seconds before items show)
4. Copy password (also a delay of 7 seconds before the password is copied and the dialog closes)

Currently I have an issue with #3, #4 seems to have solved itself. But two days ago, #4 was the issue.

I have tried quitting and restarting Raycast, installing my own version of bw (bitwarden-cli) via Brew and also re-installing bitwarden from the Raycast store and re-configuring my credentials. The issue still persists

### Current Behaviour

Delay when searching for vault items

### Expected Behaviour

no delay in searching items or copying passwords
(this was the case until a couple of days ago)

**Comment by IvoVermeer** [comment]
I have some extra info, I got logs from the terminal:
`2023-09-14 23:12:49.569 I  Raycast[39071:1600e2] [com.raycast.macos:commands] Command loaded
		Command ID: bitwarden.search__f5cd1829-474a-4572-86c3-f4d0bbce46b9
		Session ID: A3EC5C71-E019-41C5-9FA4-42E704C5A1FF
		Launch type: userInitiated
2023-09-14 23:12:49.569 Db Raycast[39071:8da31] [com.raycast.macos:node] View command loaded
		Command key: extension_bitwarden.search__5fdb86d3-dfcc-45a7-8969-8113b51434ab
		Session ID: A3EC5C71-E019-41C5-9FA4-42E704C5A1FF
2023-09-14 23:12:49.574 Db Raycast[39071:8da31] [com.raycast.macos:node] Render called
2023-09-14 23:12:49.574 I  Raycast[39071:8da31] [com.raycast.macos:app] Init CommandListViewController
2023-09-14 23:12:49.576 Db Raycast[39071:8da31] [com.raycast.macos:node] List Update: Sections
2023-09-14 23:12:49.576 Db Raycast[39071:8da31] [com.raycast.macos:node] List Update: Keep Section Order
2023-09-14 23:12:49.576 Db Raycast[39071:8da31] [com.raycast.macos:node] List AutoCompletion updated: 0
2023-09-14 23:12:49.577 Db Raycast[39071:8da31] [com.raycast.macos:node] List selection changed: ''
2023-09-14 23:12:49.577 Db Raycast[39071:8da31] [com.raycast.macos:node] List Update: Selection
2023-09-14 23:12:49.577 Db Raycast[39071:8da31] [com.raycast.macos:node] List Update: SearchBar Placeholder
2023-09-14 23:12:49.577 Db Raycast[39071:8da31] [com.raycast.macos:node] List Update: Detail
2023-09-14 23:12:49.578 Db Raycast[39071:8da31] [com.raycast.macos:node] Reloaded UI: Navigation Bar
2023-09-14 23:12:49.578 Db Raycast[39071:8da31] [com.raycast.macos:node] Navigation Update: Root replaced
2023-09-14 23:12:49.582 Db Raycast[39071:8da31] [com.raycast.macos:node] Render called
2023-09-14 23:12:49.582 Db Raycast[39071:8da31] [com.raycast.macos:app] SearchBarViewController did appear. Making search bar text field first responder
2023-09-14 23:12:49.590 Db Raycast[39071:8da31] [com.raycast.macos:node] Render called
2023-09-14 23:12:49.592 Db Raycast[39071:8da31] [com.raycast.macos:node] Render called with empty patches
2023-09-14 23:12:49.593 Db Raycast[39071:8da31] [com.raycast.macos:node] Render called
2023-09-14 23:12:58.624 Db Raycast[39071:8da31] [com.raycast.macos:node] Render called
2023-09-14 23:12:58.625 Db Raycast[39071:8da31] [com.raycast.macos:node] List Update: Sections
2023-09-14 23:12:58.629 Db Raycast[39071:8da31] [com.raycast.macos:node] List AutoCompletion updated: 615
2023-09-14 23:12:58.636 Db Raycast[39071:8da31] [com.raycast.macos:node] List selection changed: 0f19b67a-e089-4c5b-a5ff-ad5a00b7c740
2023-09-14 23:12:58.638 Db Raycast[39071:8da31] [com.raycast.macos:node] Reloaded UI: Navigation Bar Accessories
2023-09-14 23:12:58.638 Db Raycast[39071:8da31] [com.raycast.macos:node] Reloaded UI: Loader
2023-09-14 23:12:58.639 Db Raycast[39071:8da31] [com.raycast.macos:node] Reloaded UI: Global Action Panel
2023-09-14 23:12:58.676 Db Raycast[39071:8da31] [com.raycast.macos:node] Render called
2023-09-14 23:12:58.678 Db Raycast[39071:8da31] [com.raycast.macos:node] Reloaded UI: Global Action Panel
2023-09-14 23:12:58.678 Db Raycast[39071:8da31] [com.raycast.macos:node] Render called with empty patches
2023-09-14 23:13:09.317 I  Raycast[39071:8da31] [com.raycast.macos:app] Clear to root scheduled after 90.0s`

You can see the 7s delay between two 'Render called' messages at 2023-09-14 23:**12:49**.593 and 2023-09-14 23:**12:58**.624

**Comment by IvoVermeer** [comment]
I also tried using bw from the command line and then the search is instant, so it doesn't seem to be an issue with bw itself

**Comment by pernielsentikaer** [comment]
How many items do you have in the vault, do you know that?

**Comment by IvoVermeer** [comment]
I started the REST api from the terminal and did a request to /list/object/items. I count 616 items.
I also have an organisation setup, that has 69 items which are included in the total of 616.

**Comment by IvoVermeer** [comment]
I have since done a clean install of my Mac and currently it's the copying of the password that is taking a long time. Searching items now feels normal

**Comment by jomifepe** [comment]
Hey, that's definitely a weird behavior, are you still experiencing it? I can only associate this issue with a slow execution of CLI commands, but am not sure what could be causing it.

**Comment by IvoVermeer** [comment]
Hi @jomifepe ,

Sorry for the late response. Yes, I 'm still facing the issue. That is, it's still taking to to copy passwords.

I have also tested the CLI itself by starting the REST api and there is no delay there. So it seems to be in the extension itself.

So far, I've failed to setup a dev environment myself, I will try that again so I can try to debug and find the exact line that's causing the delay.

**Comment by IvoVermeer** [comment]
OK, I got the dev environment setup and I've been able to track it to this line:
<img width="913" alt="image" src="https://github.com/raycast/extensions/assets/5347891/921946e9-31a6-4630-a082-d320ca6b845b">
That it what is taking long, the two console.logs are seconds apart:
<img width="226" alt="image" src="https://github.com/raycast/extensions/assets/5347891/5d6b19cf-c33a-4ba6-9fad-6ff425feba09">
Hoever, when I navigate to its source, I hit my knowledge-limit and don't know what to look for further

**Comment by jomifepe** [comment]
Hey @IvoVermeer, thank you for that, good job debugging the issue, will take a closer look into it.

**Comment by IvoVermeer** [comment]
@jomifepe You're welcome👍 Let me know if I can test some more 😄

**Comment by IvoVermeer** [comment]
I just notices something today. When I'm still in the vault-search screen (what's the term?), The loading-bar keeps moving. If I wait until that bas stops moving and then copy the password, the copy is instant. So it seems it's not the copying of the password that's taking a long time, but a running process that's started as soon as I bring up the bitwarden extension

**Comment by jomifepe** [comment]
> I just notices something today. When I'm still in the vault-search screen (what's the term?), The loading-bar keeps moving. If I wait until that bar stops moving and then copy the password, the copy is instant. So it seems it's not the copying of the password that's taking a long time, but a running process that's started as soon as I bring up the bitwarden extension
> 
> EDIT: I think I found the culprit. Loading the items and loading the folders is what's taking a long time. I found this in bitwarden.ts: <img alt="image" width="774" src="https://private-user-images.githubusercontent.com/5347891/286750574-b8891580-5089-4b00-938b-5781f6a49da1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NzEwOTYsIm5iZiI6MTcwMzg3MDc5NiwicGF0aCI6Ii81MzQ3ODkxLzI4Njc1MDU3NC1iODg5MTU4MC01MDg5LTRiMDAtOTM4Yi01NzgxZjZhNDlkYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMTcyNjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjRiZjNjOGEwNDRjM2Q0YmFhMjY4MWY4NGVmNzMzMzNjN2FmOTI4OTBhYTQwNWUzNTg4ZDE2YzhiNzJjMDZiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HFnc8d9InMt6caxPqpIHbSwr9KUIyRfU5unrUPi7J60">
> 
> And this is what's logged: <img alt="image" width="263" src="https://private-user-images.githubusercontent.com/5347891/286750909-ab197358-9e27-44d1-998e-1fd603cd46eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NzEwOTYsIm5iZiI6MTcwMzg3MDc5NiwicGF0aCI6Ii81MzQ3ODkxLzI4Njc1MDkwOS1hYjE5NzM1OC05ZTI3LTQ0ZDEtOTk4ZS0xZmQ2MDNjZDQ2ZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMTcyNjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODg3ODI3MGQ0ODMxMDYxNmU5ZDY4ZGFhMThhMmYzMjlkM2EyMzVlYjlmNjQ4ZDA0ZTZiZWM1ZDM1ZmY4ZTQ2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LNlN_bEKS2z1rTHDMIOFUcn3lcZre6jqpWXrEiWQqR0"> So loading the items takes 1.1s, but loading the folders takes 6.8s. When I take out the folders: <img alt="image" width="794" src="https://private-user-images.githubusercontent.com/5347891/286751076-d1d80029-411e-4286-9a2f-a60d9601123b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NzEwOTYsIm5iZiI6MTcwMzg3MDc5NiwicGF0aCI6Ii81MzQ3ODkxLzI4Njc1MTA3Ni1kMWQ4MDAyOS00MTFlLTQyODYtOWEyZi1hNjBkOTYwMTEyM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMTcyNjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODRjYTdiOTg5OWJlYjQ1M2JmMjc5MTRhOGFlMmEyMTVhNWNhY2I5MDFkMjUyNDA0YTZmYmQyNWNhNGYzZDZhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7oRVtyX_dgMKm-wD3RDH2co1uYKaPw3fikw-94Kzxmc">
> 
> Loading is much faster: <img alt="image" width="259" src="https://private-user-images.githubusercontent.com/5347891/286751171-a6ceaf57-9fd5-41ae-a477-431d3118d418.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NzEwOTYsIm5iZiI6MTcwMzg3MDc5NiwicGF0aCI6Ii81MzQ3ODkxLzI4Njc1MTE3MS1hNmNlYWY1Ny05ZmQ1LTQxYWUtYTQ3Ny00MzFkMzExOGQ0MTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjlUMTcyNjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTcxMTczNTE3ZWE0MTJmNGFhZjMwNjk3ZjdlNTJjNmNlNjBhZDI1YWJkOTlkMTY5YzE2Mjg0ZTMxMzQ4MWVlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7FJfCrnc0rNr1ESQsPY-KKeIou-85JAmjIdIGL_dccs">
> 
> I personally don't use folders (anymore), I'll see if clearing them out has an effect. I will also try to see if I'm able to add a setting to switch off the folder functionality (no drop-down, no folder-icon in the list)

Hey, sorry for the delay. Thanks again for debugging the issue. Yeah, that was built with a publish-subscribe method, which means that if you copy a password before they are _really_ loaded, that action will subscribe to that item, and it will conclude once the items finish loading. 

Why is it possible to copy before they load? Because, for faster loading times, some of the vault data is cached locally (the non-sensitive values).

That said, the delay should not be that long, about 1 to 2 seconds on my machine, which is not the best, but I cannot greatly improve that, it's the CLI call that's slow, hence the caching mechanism.

**Comment by ivaarsson** [comment]
I've created a PR that should solve this issue by fetching the password directly with the get password command. If the get password command finishes before the load of the vault is finished, then that result is used instead.

https://github.com/raycast/extensions/pull/11049

**Comment by pascalinger** [comment]
Thanks @ivaarsson for your PR. I'm curious to see if this solves my issue with the extended fetching times. Subscribed to your PR and hoping for a quick merge and push to the extension.

Thanks!

**Comment by ivaarsson** [comment]
@pascalinger The PR is now merged

**Comment by pascalinger** [comment]
Thanks @ivaarsson ! I reinstalled the extension and it's considerably faster now. Close to the 3 seconds you reported on your end. Strangely, I feel like it used to take a mere second or less some time back. Might be my imagination, though.

**Comment by ivaarsson** [comment]
I don't think it's your imagination, I feel like it used to be faster too. I believe my loading times have gotten slower and slower the more my organisation's vault has grown, but I also want to remember the command `bw get password <id>` being faster on it's own. My guess would be a bug in the bitwarden-cli, but it's hard to say.

**Comment by pascalinger** [comment]
@ivaarsson At least I'm not alone with my feeling. I don't use organization vaults and I've not been amassing logins unreasonably fast so I'd venture a guess that you are right about your assumption regarding the cli. Maybe they've made a performance-breaking change that was necessary under security consideration. I might just go ahead and ask in their repo.

Thanks for your work, anyhow!

**Comment by jomifepe** [comment]
The CLI calls are definitely slower when done by raycast extensions, can't figure out why. 

At least with @ivaarsson's code, it should be faster than before for larger vaults, I hope it solves this issue 🙂 Thanks!

**Comment by jomifepe** [comment]
@raycastbot close this issue

**Comment by rbhanot4739** [comment]
I have a similar issue where the password fetching and copying with raycast takes ~1-2 seconds for and i have a fairly small sized vault with probably >100 entries.

**Comment by jomifepe** [comment]
Hey, ~1-2 seconds is not a long time. CLI calls are not the fastest, and that's something we don't have control over. The extension already has a bit of caching, so you can search and hit copy before the secrets are loaded.
