### ISSUE TITLE
[QR Code Scanner] ...

### ISSUE THREAD

**Issue by vanwoods** [raycast/extensions#8393]
### Extension

https://www.raycast.com/StevenRCE0/qr-code-scanner

### Description

Hi, 

Thanks for making this plugin, very handy!!

When assigning a hotkey this will not work just as the alias does, it opens the panel with the scanned url.  Could this be a bug?

### Steps To Reproduce

Raycast 1.58.0
OSX Ventura 13.5.2

1. trigger hotkey
2. scan qr
3. nothing happens

### Current Behaviour

Nothing

### Expected Behaviour

Open the panel with scanned url en button to open url

**Comment by StevenRCE0** [comment]
Sorry for the very late reply. I look into it ASAP, thanks!

**Comment by vanwoods** [comment]
Hi, thanks for getting back on this!

It seems to be working now with the latest OS and Raycast version.
