### ISSUE TITLE
[Arc]...

### ISSUE THREAD

**Issue by tino963** [raycast/extensions#8395]
### Extension

https://raycast.com/the-browser-company/arc

#### Error:
```
SyntaxError: Unexpected token   in JSON at position 114521
    at JSON.parse (<anonymous>)
    at Object.e7 [as current] (/Users/tino/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search.js:102:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

use search tab function, does not work produces the error JSON at position 114521

**Comment by Visual-Studio-Coder** [comment]
It seems to work for me . . .

At this point, just try restarting mac, uninstalling & reinstalling arc, uninstalling and reinstalling raycast, or those kinds of things

**Comment by pernielsentikaer** [comment]
Do you have some special chars in your tabs title?

**Comment by tino963** [comment]
Yes some of them have emoji
