### ISSUE TITLE
[Google Bard] Unable to reach Bard at this time.

### ISSUE THREAD

**Issue by rseiffert** [raycast/extensions#8401]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

Hi, I am unable to reach Bard.

I have a suspicion that it is related to the fact that I use Bard from _Germany_ and that my Google-Account also is German.

Do you have any other ideas?

<img width="582" alt="2023-09-15_09-31-09" src="https://github.com/raycast/extensions/assets/1698356/3457a48f-2269-45ef-a643-4baeb9b28883">

### Steps To Reproduce

0. I copied the Cookie-Value as described in your README.md and no, I did not forget the period in the end. And yes, I am a developer myself ;-)
1. I highlighted Text in the foremost Application (Chrome)
2. I open raycast and try to start "Find Synonym"
3. After a brief period of time raycast answers "⚠️ Unable to reach Bard at this time."
4. this is the same for all Bard-Commands from within raycast, although Bard is reachable via the Webinterface
5. MacOS 13.5.2; raycast 1.58.1

### Current Behaviour

see above

**Comment by pernielsentikaer** [comment]
@EvanZhouDev are you still around?

**Comment by Visual-Studio-Coder** [comment]
Just use the new Google palm extension. It's free and faster

**Comment by iamhenry** [comment]
> Just use the new Google palm extension. It's free and faster

do you need an api and get invited from google to get one?

**Comment by dnet5** [comment]
Same here. I can't use it, even following the instructions.
Also, @Visual-Studio-Coder the Google PaLM extension you mention... It depends on the PaLM API (via MakerSuite), and that ain't available for everyone yet.
How did you managed to install it?

**Comment by asfaltboy** [comment]
Also, Google Bard's extensions are also useful for me (ability to summarise an email or Google Drive document is cool)...

@pernielsentikaer is there an easy way to run the extension locally (pointing to a source dir) if we wanted to debug the issue?

**Comment by EvanZhouDev** [comment]
If you want to try to fix it, please join this Slack channel for `bard-ai`, the library underneath this extension: https://join.slack.com/t/bard-aiworkspace/shared_invite/zt-1y1g3570m-Hx_N3IShMYBMkR6jpRyRjw

I can let you know what we have so far :)

**Comment by pernielsentikaer** [comment]
You can simply after installation of an extension run `Fork Extension` - this will clone it locally 🙂
