### ISSUE TITLE
[Gmail] Copy Direct Link to Email

### ISSUE THREAD

**Issue by NormCopeland** [raycast/extensions#8403]
### Extension

https://www.raycast.com/tonka3000/gmail

### Description

Currently you can click to open an email and then copy the direct link to the email from the browser address bar, but it would be amazing to be able to have an action in raycast when viewing an email that will copy the message's direct link to my clipboard.

### Who will benefit from this feature?

Anyone who adds emails to their project/manager and want a link back to the original email.

### Anything else?

Thank you!!

**Comment by NormCopeland** [comment]
@tonka3000 Thanks for an excellent extension. I just wanted to make sure that you saw this. Thank you!

**Comment by tonka3000** [comment]
@NormCopeland hi 👋,

So you wanna select a mail in Raycast and want to get the url from gmail.com (same that is used to open the mail) via an action, correct?

**Comment by NormCopeland** [comment]
That's right! Get the direct URL of the message without needing to open it. It's not a big deal to open the message and copy the URL, but this would be smoother.

**Comment by tonka3000** [comment]
I've added the change to #8432

**Comment by NormCopeland** [comment]
Thank you!
