### ISSUE TITLE
[Things] Menu Bar Settings: Hide Text, Show Count, Monochrome Icon

### ISSUE THREAD

**Issue by boettges** [raycast/extensions#8417]
### Extension

https://www.raycast.com/loris/things

### Description

I'd like to suggest adding some _optional_ settings to enhance the Menu Bar entry offered by the extension. These settings would offer users more flexibility and customization:

1. Hide Text: Allow to hide the Today list's topmost to-do title being shown in the Menu Bar to avoid cluttering it.
2. Show Count: Display a number of remaining to-dos.
3. Monochrome Icon: Uses a monochrome Things icon to blend in better with other native Menu Bar icons.

Thanks a bunch 👍 

### Who will benefit from this feature?

Anybody already suffering from the scarce space in the Menu Bar.

**Comment by leodbrs** [comment]
We could maybe reopen this issue ?
