### ISSUE TITLE
Google bard api not working on raycast

### ISSUE THREAD

**Issue by AlexLee1992** [raycast/extensions#8424]
### Description

<img width="750" alt="image" src="https://github.com/raycast/extensions/assets/38725845/7c7d8b56-1770-4392-8ebd-0f46273780f1">
According to the readme document, copy the cookie value to the api location and always display please wait for bard to initialize. How to solve it?

**Comment by tryit05** [comment]
same here

**Comment by mathieudutour** [comment]
This isn't related to the API. Can you open an [extension issue](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...) so that the author are correctly pinged?
