### ISSUE TITLE
Method to get root search query

### ISSUE THREAD

**Issue by imthath-m** [raycast/extensions#843]
> Can I get search query from root search in my extension? I want dynamically show list items based on user search query.

User request via Email. 

**Describe the feature and the current behavior/state.**
There is no existing API.

**Will this change the current api? How?**
No. It will be an addition.

**Who will benefit with this feature?**
Developers who want the list of items in their extensions to be based on the user's input.

**Any Other info.**

**Comment by mathieudutour** [comment]
Closing this as we have support for arguments now. It's not clear what's the use case for accessing the root search query otherwise (especially since it's not always there)
