### ISSUE TITLE
[Notion] End Date Support

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#8438]
### Extension

https://www.raycast.com/notion/notion

### Description

It would be great if dates could be optionally split into separate inputs for start / end date support.

I often have schedule fields that use a both start and end options to define the range, for instance, project duration, phases, etc.

### Who will benefit from this feature?

Anyone who uses end date functionality of Notion.

**Comment by erics118** [comment]
> optionally split into separate inputs for start / end date support

This is a good idea, but it would make the page form have an extra line that sometimes is unnecessary. I do have a possible solution in mind though

**Comment by erics118** [comment]
@raycastbot reopen this issue

**Comment by christianmagill** [comment]
@erics118 , Any chance of resurrecting this now that the related issues have been solved.
