### ISSUE TITLE
Password not recognised [LastPass Credentials Search] ...

### ISSUE THREAD

**Issue by Jackydu92** [raycast/extensions#8442]
### Extension

https://www.raycast.com/alex-popov-tech/lastpass

### Description

The extension is unable to log me into LastPass because of an erroneous password, despite double checking it is correct at least 3 times.
<img width="779" alt="Screenshot 2023-09-18 at 12 51 52" src="https://github.com/raycast/extensions/assets/145344010/6bdb5995-d629-48d5-9c22-957ee5d9758d">

### Steps To Reproduce

1. Set up LastPass extension with RayCast
2. Launching the "Search Vault" function

### Expected Behaviour

This should allow me to search the credentials stored in LastPass.

**Comment by BaQQer** [comment]
Experiencing the same issue. I am sometimes, not always, able to circumvent the issue by executing `lpass login` followed by `lpass ls` at which searches are again available through the Raycast extension. When the error occurs, a failed login attempt is logged in the LastPass login history.

**Comment by floristweb** [comment]
Same issue here. Whenever the error occurs in the Raycast Extension, I open a terminal and login via lpass login. Login always works great. Immediately after this, I can use the Raycast Extension.
BUT after some time, the error happens again. This way, I have to login at least once a day in the terminal - which sucks.
