### ISSUE TITLE
[Coffee] Add option to only show coffee icon in menu bar when caffeinated

### ISSUE THREAD

**Issue by Justiniscoding** [raycast/extensions#8447]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

My menu bar is pretty cluttered from all my raycast extensions, and since I don't use the coffee extension daily (I use it about once a week) I don't think that I need the icon constantly in the menu bar. I don't want to completely disable the menu bar icon, because I do still want the coffee icon in the menu bar when my mac is caffeinated. TL;DR, An option to hide the coffee menu bar icon would be really useful for people with cluttered menu bars

### Who will benefit from this feature?

People who do not use the extension often and do not want the icon in their menu bar constantly. People with cluttered menu bars would also benefit.

**Comment by Justiniscoding** [comment]
@mooxl

**Comment by bobmoff** [comment]
I cant get the icon out of my status bar any more now that I once activated it. Please fix. Would be nice with a toggle for this at least, but I agree that it would be even better if the icon only showed when caffeinated.

**Comment by Justiniscoding** [comment]
> I cant get the icon out of my status bar any more now that I once activated it. Please fix. Would be nice with a toggle for this at least, but I agree that it would be even better if the icon only showed when caffeinated.

To get the icon out of the menu bar, find the coffee status menu bar command, press ⌘ + K, and then the second last option will be "Deactivate Command". Press that and it will disappear. Since the devs aren't replying, I might do this myself and make a pull request
