### ISSUE TITLE
[Year in Progress] Not updating menu bar percentage

### ISSUE THREAD

**Issue by angeloschl** [raycast/extensions#8458]
### Extension

https://www.raycast.com/thomas/year-in-progress

### Description

The percentage value of the day in the menu bar is not updating. When I click on the symbol in the menu bar, the correct value is displayed. I have enabled "Background refresh" in the "Show X in Menu Bar" setting.
Thanks for your help, and please correct me if I have done something wrong by reporting this "bug."

<img width="270" alt="CleanShot 2023-09-19 at 12 07 25@2x" src="https://github.com/raycast/extensions/assets/56880843/c1259ab0-f4be-4537-9520-1baa392fab37">

### Steps To Reproduce

I have to be honest. I don't know how to reproduce this behavior.

### Current Behaviour

There is no automatic updating of the percentage display in the "menu bar".

### Expected Behaviour

The percentage display in the "menu bar" should update automatically.

**Comment by cunyiles** [comment]
Same for me. It only updates the value if I do **click menu bar** > **select percentage** > **click menu bar again**.

**Comment by anothertempore** [comment]
OK I can reproduce it, fixing~

**Comment by angeloschl** [comment]
It works for me know. Thank you very much!
