### ISSUE TITLE
[Oh My Zsh Git Alias] Find the alias by command

### ISSUE THREAD

**Issue by filipszczepanski** [raycast/extensions#8478]
### Extension

https://www.raycast.com/yufeikang/oh-my-zsh-git-alias

### Description

Searching for an alias using a command

You type: `check`
You get: `gco git checkout`

### Who will benefit from this feature?

Everyone who want to find the alias by command.

### Anything else?
Current:
<img width="618" alt="Screenshot 2023-09-20 at 16 19 00" src="https://github.com/raycast/extensions/assets/3180140/112cdf69-720c-42b2-a404-dfe8eb7f4cb9">

**Comment by yufeikang** [comment]
Hi, Thank you for feedback.

https://github.com/raycast/extensions/pull/8493

**Comment by yufeikang** [comment]
@raycastbot close this issue
