### ISSUE TITLE
[Jira] epic dropdown doesn't function

### ISSUE THREAD

**Issue by qbunt** [raycast/extensions#8482]
### Extension

https://www.raycast.com/raycast/jira

### Description

When you're writing a new ticket in Jira in the 'Create Issue' command, I have about a dozen active epics that are in this specific project. No matter what I search for, or type into the epics field, I see no epics available to my project. 

I really would like the ability to file a ticket into a specific epic, but it does not appear possible either in this version of the extension. If it's not possible, maybe the dropdown should either be disabled or removed. I've reinstalled the extension as well, and that appears to have no effect	

### Steps To Reproduce

1. Run the 'Create Issue' command in Raycast
2. Select the project and start filling in the issue
3. Tab to the 'Epic' dropdown and search for an epic
4. Witness there is nothing in the dropdown

### Current Behaviour

No epics appear

<img width="476" alt="image" src="https://github.com/raycast/extensions/assets/187095/8fea4975-7f4f-46b2-a903-76bc9fc84da2">

### Expected Behaviour

I should be able to create an issue with an epic attached.

**Comment by qbunt** [comment]
Any update on this one? Would really like the ability to use an epic when making a ticket

**Comment by thomaslombart** [comment]
Hey @qbunt, we have many extensions to maintain at Raycast so we unfortunately can't be on top of everything. The best would be to open a PR for it 😊

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!

**Comment by qbunt** [comment]
@thomaslombart no worries at all, just wanted to check in on it, raycast is massive. If I can get some spare cycles together for dev on it, I will certainly keep it on my radar. Thanks for getting back to me and keep up the great work 🥂

**Comment by thomaslombart** [comment]
Thanks for the kind words! Let me know if I can provide you with some pointers to get started on it.

**Comment by qbunt** [comment]
@thomaslombart the way they do this in the Jira API is not consistent and changes by version and deployed location, it's possible to handle but would be absolutely silly complicated. If you use 'server' or 'data center' editions, you can update epic links but it's considered a "custom field", but that also varies by version, etc. 

I think the most straightforward way to fix this is to get the heck off of Jira 🤣 Thanks anyway

**Comment by thomaslombart** [comment]
Jira being Jira I guess! 😄

**Comment by yamhirotoCS** [comment]
Hey, 

I've had the same issue.  Fiddling on JIRA by unassigning, assigning, re-unassigning myself from an Epic, and refreshing Raycast allowed me to see the EPICs I needed in "create issue". One painful step on JIRA and then you can skip theie UI forever ! 🥳
