### ISSUE TITLE
Todoist: Add option to sort tasks by sections

### ISSUE THREAD

**Issue by geraldaddey** [raycast/extensions#8485]
### Extension

https://www.raycast.com/doist/todoist

### Description

The current Todoist Raycast extension allows sorting tasks by due date, name, labels and priority. However, it does not provide the option to sort tasks by sections. This feature request is to add sorting tasks in Raycast by section, to be able view different tasks related to the same project. This would provide more flexibility in viewing and managing tasks. 

### Who will benefit from this feature?

Anyone who has a lot of tasks in one project and has apportioned tasks to different sections.

### Anything else?

<img width="360" alt="screenshot  2023-09-20 at 5 32 01 PM" src="https://github.com/raycast/extensions/assets/42818198/4c311081-4f4b-46b4-a12e-a3fe0d6066a8">

**Comment by geraldaddey** [comment]
Thank you for clarifying that for me. I will close this issue. But can you please inform me if adding tasks with natural language flags is currently possible in the extension.

**Comment by thomaslombart** [comment]
Yes, with the Quick Add command.

**Comment by geraldaddey** [comment]
Hello @thomaslombart, I know this issue is closed. But can you provide me with a way of viewing tasks belonging to only one section in the Home page(just like viewing by inbox, today, upcoming, labels, projects etc). My actual use case is viewing only tasks in a particular section of project. I have a load of tasks in each project and viewing them can be overwhelming sometimes.

**Comment by thomaslombart** [comment]
You can do that with the `Home` command, you should have a dropdown with the different views and projects.

**Comment by geraldaddey** [comment]
Sections is currently not included in the category. It currently has only Projects and Labels. I would like to include sections to that list to quickly access specific sections of my large projects. My intention is to create quicklinks to directly access sections just as i can access other labels. I am willing to contribute and make a pr to implement it but would appreciate some guidance.

**Comment by thomaslombart** [comment]
That should probably be done in the `Show Projects` command as the dropdown in the `Home` commands needs to stay relatively clean and out of clutter.
