### ISSUE TITLE
[Home Assistant] Toggle Groups

### ISSUE THREAD

**Issue by eIiot** [raycast/extensions#849]
# Extension – [Home Assistant](https://github.com/raycast/extensions/tree/ecfa4418abe83b9ff1698a8b6da5ffff60f53428/extensions/homeassistant/)
Author: @tonka3000

I would love it if It would be possible to toggle a group as the default, instead of viewing the entity information!

**Describe the feature and the current behavior/state.**
Currently, when you click `enter` when selecting a group, it opens the entity information. I would love if it would toggle the group. At a minimum, it would be nice to have it as an option in the commands.

**Who will benefit with this feature?**
People who would like to toggle their groups.

**Any Other info.**

**Comment by tonka3000** [comment]
Hi @eIiot ,

Which kind of group you are talking about? Lights group are already supported.

Please provided an example for your groups you are having. Yaml examples of your group would also help.

Greetings
Michael

**Comment by eIiot** [comment]
I'm talking about a .group entity created in groups.yaml. They should be able to be toggled with homeassistant.toggle

For example
<img width="935" alt="image" src="https://user-images.githubusercontent.com/39346975/153735183-b24e94ea-0441-405a-96e6-93784411d711.png">

**Comment by tonka3000** [comment]
@eIiot Please can also send a screenshot from the entity view itself. I would be interesting which state the group show too you (on the right side. I guess it is `off`). There is no toggle service for groups, so I need to make sure that `on/off` state is always there.

Please can you also check if `homeassistant.turn_on` will turn on the group on as you expect. Same for `homeassistant.turn_off` but for the off state. Just use the Home Assistant developer tools to check it.

If this all works on your side I can impl. that.
