### ISSUE TITLE
[AWS] Request ability to modify AWS_CONFIG_FILE path

### ISSUE THREAD

**Issue by marcus-crane** [raycast/extensions#850]
# Extension – [Amazon AWS](https://github.com/raycast/extensions/tree/main/extensions/amazon-aws)

Author: @victor-falcon

**Describe the feature and the current behavior/state.**

I would like to request that instead of directly hardcoding `~/.aws/credentials`, you support the `AWS_CONFIG_FILE` environment variable.

In the case of where I work, we use [saml2aws](https://github.com/Versent/saml2aws) and in order to have the AWS invoke it every time (using the `credential_process` block supported by AWS config), my credentials file lives at `~/.saml2aws_credentials`.

Seemingly this could be done by adding an extra preferences field that the user can specify and then feeding that into the SDK used under the hood of the extension

**Who will benefit with this feature?**

Myself and any other engineers who use this somewhat niche variable

**Any Other info.**

**Comment by marcus-crane** [comment]
It looks like for the Javascript SDK, setting `AWS_SHARED_CREDENTIALS_FILE` as an environment variable should do the trick:

https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/shared_ini_file_credentials.js#L10

**Comment by adnanrahic** [comment]
I can second @marcus-crane that this feature is needed for any production use case.
Using different AWS Profiles is normal in day-to-day work. 
I'd suggest implementing [this](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html), as it would enable setting the particular profile when enabling the extension.

Thanks @marcus-crane for opening this issue. 👏

**Comment by speed0ne** [comment]
Please integrate it. 
I also use AWS with different SSO Profile and the actual state doesn't work for me.

**Comment by paro-paro** [comment]
Any update on this? Is it possible to use the extension while having the .aws/credentials file outside the $HOME directory?
