### ISSUE TITLE
[Obsidian] Show search results ordered by last modified

### ISSUE THREAD

**Issue by gacharles23** [raycast/extensions#8503]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

When pulling up the Raycast Obsidian search, it seems to list notes alphabetically. It would be super nice if there was a way to instead see the notes ordered descending by last modified. That way, when pulling up the search option, all recently edited notes will be right at the top, making for a quick method for jumping to a note from outside of Obsidian.

Thanks for the consideration.

**Comment by KevinBatdorf** [comment]
I agree that makes more sense and how Obsidian displays notes in the quick switcher

**Comment by KevinBatdorf** [comment]
PR here: https://github.com/raycast/extensions/pull/8735
