### ISSUE TITLE
[Obsidian] Installing this plugin causes Raycast to hang

### ISSUE THREAD

**Issue by gacharles23** [raycast/extensions#8504]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

I recently installed this plugin and periodically when I perform certain functions like searching for a note, Raycast will hang. Activity Monitor shows "Raycast (Not Responding)". This requires me to do a Force Quit and then restart Raycast. If I disable this plugin, I no longer get the hangs. 

Could this be related to the fact that (1) I have a large vault (about 1500 notes) and (2) the vault is in an iCloud drive? Perhaps something related to this plugin indexing my vault??

Thanks for building this plugin. I hope to be able to consistently use it.

Configuration
- Raycast 1.59.0
- Ventura 13.5.2
- Mac Studio, M1 Max, 32GB memory

### Steps To Reproduce

1. Install plugin
2. Point to a vault on iCloud drive with many files (~1500)
3. Enable search to look at note contents
4. Try to search for a file

Most times it will work, and about 10-20% of the time it will cause Raycast to hang.

**Comment by KevinBatdorf** [comment]
Yeah sounds like overloading Raycast's list. I'll see if there's a way to optimize this. (might be a week or so as im out of town starting tomorrow and time will be limited)

**Comment by KevinBatdorf** [comment]
So looking at the code, we have some custom filtering here that at first glance doesn't seem required. However, it might take some time to refactor it and it could actually be doing more than I notice right away. I'll take a look into refactoring it but just wanted to leave an update here.
