### ISSUE TITLE
[Linear] In the issue creation action, the team dropdown should include the ID in addition to the name

### ISSUE THREAD

**Issue by seanrose** [raycast/extensions#8507]
### Extension

https://www.raycast.com/linear/linear

### Description

- In the issue creation action, the team dropdown should include the ID in addition to the name
- Currently it only has the team name (eg for Product Management with the ID PM, it will only show Product Management)
- It should show both for each team

This will make it easier to select teams.
<img width="490" alt="image" src="https://github.com/raycast/extensions/assets/449454/c3a9d098-96ee-4e6c-a63e-8cbb0639bce2">

### Who will benefit from this feature?

Anyone creating issues who changes teams of issues

### Anything else?

Linear's own UI matches teams and IDs in this same way

**Comment by thomaslombart** [comment]
Done: https://github.com/raycast/extensions/commit/05810db44f49908fb807b22ee6505d66720e62c9
