### ISSUE TITLE
[Browser Bookmarks] Search results not longer as relevant

### ISSUE THREAD

**Issue by dariodjuric** [raycast/extensions#8514]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

It seems that as of the latest update, the search results are no longer very relevant. For example, searching for "SSO" gives me 5 results that don't even have SSO in the name, and the result that used to be the first (which has "SSO" in the name), is now 6th in the list.

### Steps To Reproduce

1. Add a Chrome bookmark like: "Discord": https://discord.com/channels/841573134531821608/842637025524842496
2. Add a bookmark that has SSO in the title
3. Search by "SSO"

### Current Behaviour

The "SSO" link is not first in the list.

### Expected Behaviour

The "SSO" link should be the most preferred link.

**Comment by thomaslombart** [comment]
Could you send a recording to see what are your matches? When did you see that happen?

**Comment by dariodjuric** [comment]
> Could you send a recording to see what are your matches? When did you see that happen?

Sure, here it is: https://share.cleanshot.com/81nlMKBX

It started happening today or yesterday. I _think_ I saw the bookmarks extension got updated, and then it started happening.

**Comment by thomaslombart** [comment]
Thanks, I'll have a look into that.

**Comment by AndreKucharzyk** [comment]
Sorry, is there any ETA on that one? Raycast bookmark searching has been my daily driver since day one and now is pretty unusable.
