### ISSUE TITLE
[Notion] Save Quicklink to Navigate to Database

### ISSUE THREAD

**Issue by christianmagill** [raycast/extensions#8522]
### Extension

https://www.raycast.com/notion/notion

### Description

Currently you can save a Quicklinks to the database page in Notion, but I'd like to see the ability to create a Quicklink that would take me to the Raycast prompt to search items within the selected database.

**Comment by thomaslombart** [comment]
Nice idea. Feel free to open up a PR 🙂

**Comment by erics118** [comment]
Keep open for now
