### ISSUE TITLE
[iMessage 2FA] Does not detect 2FA codes that are 8 digits

### ISSUE THREAD

**Issue by Coder84619** [raycast/extensions#8536]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

Chase Bank, and other companies, send 2FA codes that are more than six digits. Chase sends 8 digit 2FA codes and this extension does NOT recognize them. 

### Steps To Reproduce

1. Go to a website that sends 8 digit 2FA codes (e.g. chase.com).
2. Wait for the 2FA code to be sent
3. Launch the Raycast 2FA extension, and observe in the list of codes that the 8 digit 2FA is NOT listed

### Current Behaviour

8 digit 2FA codes are not parsed.

### Expected Behaviour

It should recognize 2FA codes up to and including at least 8 digits.

**Comment by ronaldheft** [comment]
Oddly, I noticed the exact same issue with Chase this morning, haha. I'll submit a fix later today.

**Comment by Coder84619** [comment]
Will Raycast automatically get the updated extension?
