### ISSUE TITLE
[JetBrains Toolbox Recent Projects] ...

### ISSUE THREAD

**Issue by JanBajec1999** [raycast/extensions#8545]
### Extension

https://www.raycast.com/gdsmith/jetbrains

### Description

I updated the jetbrains toolbox and now im getting this

There was a problem finding the JetBrains shell scripts
We were unable to find shell scripts, ensure you have the Generate Shell scripts option checked in JetBrains Toolbox under Settings.
If you have set a custom path for your shell scripts, that can set that in the settings for this extension, this is currently set to ﻿/usr/local/bin.
You can also enable the extension preference to fallback to protocol url, though that is a less reliable method of opening projects.

### Steps To Reproduce

1. Update the jetbrains toolbox
2. run the raycast jetbrains plugin

**Comment by gdsmith** [comment]
@JanBajec1999 please let me know what IDEs you have installed, what version of IDE(s)/Toolbox/Raycast you are on and where you have your shell scripts installed (from Toolbox Settings).
