### ISSUE TITLE
[Quick Phone Call] allow calling a contact

### ISSUE THREAD

**Issue by rluvaton** [raycast/extensions#8546]
### Extension

https://www.raycast.com/karbassi/quick-call

### Description

currently you can only call a specific phone number. I don't remember my contacts phone number so I would like to call a contact instead

### Who will benefit from this feature?

everyone with normal memory that uses quick call

**Comment by karbassi** [comment]
The "Search Contacts" raycast feature allows you to call someone via your contact.

![Screenshot 2023-09-27 at 6 21 51 PM](https://github.com/raycast/extensions/assets/17738/83dfa555-2ed5-49a2-9717-0a083c5aef72)
