### ISSUE TITLE
[ScreenOCR] ... Can you add the ability to cancel newlines?

### ISSUE THREAD

**Issue by Zou9805** [raycast/extensions#8558]
### Extension

https://www.raycast.com/huzef44/screenocr

### Description

当我通过截图来识别长段文本时，在屏幕中的的换行会导致识别的文本会分成好多段，需要手动删除来让文本重新变成一整段。可否添加自动变成一段的功能呀？谢谢开发者Huzef      ——来自有道翻译
When I took a screenshot to identify a long piece of text, line breaks on the screen caused the identified text to break into several segments, which had to be manually removed to make the text into a single segment again. Can I add the function of automatically becoming a segment? Thanks to developer Huzef      -- from Youdao Translation

### Anything else?

![CleanShot 2023-09-25 at 12 23 47@2x](https://github.com/raycast/extensions/assets/39221981/e172506f-88f1-4fd3-80f8-d99a81191e01)

**Comment by baptistechretien** [comment]
I would also be very interested in this feature, already present in the "TextSniper" application.
