### ISSUE TITLE
[GitHub Gist] Render mathematical expressions inside Markdown

### ISSUE THREAD

**Issue by jhelgert** [raycast/extensions#8562]
### Extension

https://www.raycast.com/koinzhang/github-gist

### Description

Currently, mathematical expressions inside markdown documents aren't displayed correctly, i.e. the LaTeX expressions aren't rendered at all. Since Github [supports mathematical expressions by means of MathJax](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions), being able to see the rendered expression inside the extension too would be really nice.

### Who will benefit from this feature?

Everyone who uses markdown containing mathematical expressions.

### Anything else?

[Here's a sample](https://gist.github.com/jhelgert/d95eefac231cd2d7e32918443953971b) which illustrates how Github renders the markdown:

<img width="551" alt="CleanShot 2023-09-25 at 12 46 43@2x" src="https://github.com/raycast/extensions/assets/8471326/09e4c3b6-1e0b-45ec-92d0-ce029f3e42ef">

vs how the gist extension renders it:

<img width="862" alt="CleanShot 2023-09-25 at 12 32 59@2x" src="https://github.com/raycast/extensions/assets/8471326/f5f9573b-5c6c-4d62-99c9-f2b24837c1da">

**Comment by Aayush9029** [comment]
AFAIK, Raycast doesn’t support rendering mathematical expressions inside the Markdown renderer. This is not a gist issue. Granted, we could send the mathematical expression to some server that renders and returns an image. 

I'd recommend sending a feedback through slack! 

@koinzhang what do you think?
