### ISSUE TITLE
[Waktu Solat] Add Option to Enable Ping Sound for Notification

### ISSUE THREAD

**Issue by ezzylan** [raycast/extensions#8563]
### Extension

https://www.raycast.com/msms/waktu-solat

### Description

- Current behavior: Have to manually check if it's already prayer time
- Feature request: Add option to enable simple sound (ping, etc.) to notify when it's prayer time

### Anything else?

I can help adding this feature into the extension if you want. Just contact me through GitHub 😁

**Comment by sayuthisobri** [comment]
@ezzylan I'm thinking of adding a reminder to the menu bar that shows messages like "Zohor in 5 minutes." Can't promise when exactly, but it's on my to-do list. By the way, feel free to work on the notification you mentioned earlier.
