### ISSUE TITLE
[GitHub] Black pull requests icon on dark background

### ISSUE THREAD

**Issue by busybox11** [raycast/extensions#8573]
### Extension

https://www.raycast.com/raycast/github

### Description

The "My Pull Requests Menu Bar" item has an always dark color. It doesn't work well with an already dark background (see attached screenshot, on the left: 21 pull requests)

![image](https://github.com/raycast/extensions/assets/29630035/1f007f67-1e50-4807-a2c6-a7a31a5db76d)

### Steps To Reproduce

1. Activate "My Pull Requests Menu Bar" item in Raycast's GitHub extension settings.

### Current Behaviour

The icon is dark.

### Expected Behaviour

The icon should adapt to the theme.

**Comment by thomaslombart** [comment]
Fixed: cb646dc6e.
