### ISSUE TITLE
[Notion] Insufficient permissions for this endpoint

### ISSUE THREAD

**Issue by danhughes** [raycast/extensions#8579]
### Extension

https://www.raycast.com/notion/notion

### Description

Getting the error captured below when using two of the built in actions in the Notion extension. Both 'Create Database Page' and 'Search Notion' say "Insufficient permissions for this endpoint." Despite the message, I can create a new page and searching works. 

https://share.cleanshot.com/cK3W1GZp

### Steps To Reproduce

1. Install Notion extension
2. Create new Notion integration
3. Select pages to share with Raycast
4. Run Create Database Page or Search Notion command

### Current Behaviour

Raycast window display permissions issue

### Expected Behaviour

No permissions error

**Comment by thomaslombart** [comment]
Does you still get it? Or was it a one-time thing?

**Comment by Whyya** [comment]
the same problem .
