### ISSUE TITLE
[AirPods Noise Control] Broken with addition of Adaptive mode in Sonoma

### ISSUE THREAD

**Issue by BionicBison05** [raycast/extensions#8581]
### Extension

https://www.raycast.com/chrahe/airpods-noise-control

### Description

With the addition of the Adaptive noise control mode in Sonoma, the extension now switches to Transparency for what it thinks is noise cancellation and Adaptive for what it thinks is transparency.

### Steps To Reproduce

1. Be using macOS Sonoma
2. Connect AirPods
3. Use extension

### Current Behaviour

Does not switch between noise control and transparency as it should, instead switching between transparency and adaptive

### Expected Behaviour

Switches between noise control and transparency as before, or better yet, cycles through/includes separate commands to support the new Adaptive mode.

**Comment by BionicBison05** [comment]
Definitely still an issue.

**Comment by iamyeizi** [comment]
Ready! @BionicBison05

**Comment by BionicBison05** [comment]
@iamyeizi works great, thanks!

**Comment by shigella520** [comment]
When will the new version be released to the raycast store

**Comment by iamyeizi** [comment]
@shigella520 it was shipped one month ago 🤠

**Comment by shigella520** [comment]
However, I set the configuration of the Switch to Noise Cancellation and Transparency,it does not work as expected. I found that the Noise Cancellation option is always executed as Adaptive Mode.

**Comment by shigella520** [comment]
<img width="300" alt="image" src="https://github.com/raycast/extensions/assets/34263598/cc3285ca-4ad4-4ff4-8cce-8ba0c6f91000">
Toggle Conversation Awareness also not work
