### ISSUE TITLE
[Things] When trying to use the 'Quick Add To-Do' action I get an error saying I need to have Raycast Pro

### ISSUE THREAD

**Issue by wtigert** [raycast/extensions#8585]
### Extension

https://www.raycast.com/loris/things

### Description

If I try to use the 'Quick Add To-Do' action that's a part of the Things extension, upon pressing return or 'Open Command' the raycast window will flash and then display a message saying that 'Quick Add To-Do' requires a Raycast Pro subscription.

The 'Add New To-Do' action works fine and does not seem to have this issue.

Quick video of the interaction:
https://github.com/raycast/extensions/assets/453304/5c6fcc71-4c28-4407-80f0-28a276b9209d

Screenshot of the message that is displayed:
![screenshot 2023-09-26 at 23 22 56](https://github.com/raycast/extensions/assets/453304/33e74226-aa8e-4a4a-ad77-04b017d3281e)

### Steps To Reproduce

1. In macos Ventura w/ Raycast 1.59.0 and the Things extension installed, open the raycast window
2. Make sure the 'Quick Add To-Do' Command is enabled in the raycast extension settings
3. Type 'Quick Add To-Do' in the Raycast Command Prompt
4. With the 'Quick Add To-Do' command selected tab over to the To-do field
5. Type in 'Test Todo' and press Return

### Current Behaviour

Upon pressing return after entering a todo in the todo input the raycast window will flash and go to a screen saying that the extension command requires raycast pro. No todo will be added to the Things app.

### Expected Behaviour

A notification saying 'Added Todo' will flash successfully an a new todo will be added to Things without interacting with any Raycast Pro functionality.

**Comment by thomaslombart** [comment]
It is expected. Quick Add Todo uses Raycast AI (which is part of the Pro plan) under the hood to provide NLP support. I'm closing the issue then. :)

**Comment by wtigert** [comment]
@thomaslombart ahhhh apologies. I didn't realize it was making use of AI.
