### ISSUE TITLE
[Brew] "Updating ..." still processing on Raycast event though it's already done

### ISSUE THREAD

**Issue by Sulfyderz** [raycast/extensions#8588]
### Extension

https://www.raycast.com/nhojb/brew

### Description

Hello,

Thank you for your great extension.

However, there is an annoying bug when you update all your formulae and casks inside your "Show outdated" command. When you update all with the shortcut, you have a message in the left bottom corner saying "Updating ...". If you go to Raycast root, you can still see it. However, it is in a kind of infinite loop. It doesn't go away even though every update is done. The trick to solve it/kick it is to call the Raycast command : "Refresh Apps and Settings".

Do you have any idea of what's happening ?

Best,
Sulfyderz.

### Steps To Reproduce

1. Go the the "Show outdated" command;
2. Update all formulae and casks with the shortcut;
3. Go to the Raycast root and wait. Here you'll see in the left bottom corner the message "Updating ..." in a kind of infinite loop.

### Current Behaviour

The message "Updating ..." is in a kind of infinite loop. It doesn't go on its own.

### Expected Behaviour

The message "Updating ..." should go away on its own when every formula/cask is updated.

**Comment by shawnyeager** [comment]
I can confirm the same behavior in Raycast 1.59.0 on macOS 14.0.

**Comment by nhojb** [comment]
Thanks for the report. Possibly we're not clearing the `Updating...` message when the update completes. The other thing that can happen is that the extension is unloaded before it can clear the message. I'll take a look.

**Comment by sxn** [comment]
thanks for the report! I've been trying to reproduce it in order to see what's up, but I've not had any success so far 🥺

any chance you can provide a step-by-step with what you're doing to reproduce the issue? A video would be even better 😺

**Comment by Sulfyderz** [comment]
Hello @sxn,

Here is a step-by-step:
1. Call Raycast;
2. Launch the Brew command `Upgrade`;
3. While it's still processing, click outside of Raycast (i.e. closing the Raycast window);
4. Call Raycast again an you'll see the message is still there in a kind of loop.

How to clean it ?
Call the Raycast command `Refresh Apps and Settings`.

If you still need a video, I'll do that. Feel free to share your feedback.

**Comment by sxn** [comment]
right, I was able to reproduce it, too, in the mean time 😺 I've fixed internally, and it should be fixed in the next Release 👌
