### ISSUE TITLE
[Brew] When using brew with both x86_64 and arm64 installed, the plugin only accesses x86_64

### ISSUE THREAD

**Issue by joonhyuk** [raycast/extensions#8592]
### Extension

https://www.raycast.com/nhojb/brew

### Description

I'm using brew on both arch from today because of game-porting-toolkit.
There was no problem before that, but when I installed the x86_64 brew, the plugin is only dealing with the x86_64 brew.

It would be nice if you could make it optional, or let me set it in settings.

**Comment by nhojb** [comment]
You can set a custom brew path in Settings -> Extensions -> Brew

<img width="1112" alt="Screenshot 2023-04-25 at 19 33 02" src="https://github.com/raycast/extensions/assets/312540/abd340cf-7bcf-4ca4-9725-febfd98f8e13">
