### ISSUE TITLE
[Notion] Doesn't connect to Notion after following setup instructions and Troubleshooting tips

### ISSUE THREAD

**Issue by aprice42** [raycast/extensions#8596]
### Extension

https://www.raycast.com/notion/notion

### Description

I am not able to use any of the features of this extension after following the setup steps and troubleshooting.

### Steps To Reproduce

- I followed the setup instructions and created a custom connection in Notion. 
- It has full access (see screen cap below)
- I added the token to the Notion Raycast Extension configuration

Trying to Create a database page
- I get the error "No Databases Found"

Trying to Search 
- I get the error: "Something went wrong"

Trying Quick Capture
- I am not able to see any pages to add the capture to. 

In reviewing the readme it says that I should see my connection under "My Connections" in Notion, but it isn't there. It is listed under Workspace > Connections and there is not a setting to "Access selected pages" that should be available as mentioned in the readme either.

![2023-09-27 at 10 22 25](https://github.com/raycast/extensions/assets/675820/e4c466f3-4a2c-4bab-8699-a0dac3de4fb1)

My custom connection settings
![image](https://github.com/raycast/extensions/assets/675820/b76a3c38-fa62-4ad0-9cb1-451302913d14)

Did the Notion app get an upgrade and these options no longer apply, or am I missing something else. Any thoughts would be appreciated. 

### Current Behaviour

Not able to connect to notion databases.

### Expected Behaviour

Should see and have access to all notion databases.

**Comment by thomaslombart** [comment]
I think you need to check the "My Connections" tab in your account, not "Connections" in the "Workspace" section.

![CleanShot 2023-09-29 at 13 35 19@2x](https://github.com/raycast/extensions/assets/16003285/cfb98c4e-f700-42b5-a710-b1d54f933e80)

**Comment by aprice42** [comment]
For some reason it doesn't show up under "My Connections"? Other things do, but not the custom Raycast Connection that I created, that only shows under the more general "Connections" section for the workspace. I am not sure how I can do things differently to make it show up correctly? Any ideas would be appreciated.

![2023-09-29 at 13 10 36](https://github.com/raycast/extensions/assets/675820/b8f59efc-f2b8-457a-81d9-52f84b62f19b)

I am using the latest Notion Desktop App 2.2.1 and I have a Pro account in case that makes a difference?

**Comment by thomaslombart** [comment]
Could you remove the Raycast extension from Notion and then send a recording of what happens when you login into the Notion extension?
