### ISSUE TITLE
[Google Tasks] Impossible to use with non-workspace Google account

### ISSUE THREAD

**Issue by proton1k** [raycast/extensions#8597]
### Description

Probably should be mentioned that this extension works with Google Workspace only and it's not possible to pass through the configuration in a private Google Cloud account to use this extension. If I am not wrong, only external testing mode is available for private accounts and a lot of additional irrelevant information to pass the app verification process (like link to youtube video with demo of the app is required). Unlikely to succeed. Or am I wrong?

**Comment by thomaslombart** [comment]
@elliotdes fyi

**Comment by elliotdes** [comment]
Hi! I looked into getting Google Tasks Raycast verified with GCP. I contacted the author of the Google Photos extension, who tried to get [verified](https://github.com/raycast/extensions/pull/4297).

Would need to provide links for the Application home page and privacy policy. I think Raycast team would need to do this.
