### ISSUE TITLE
Add Multi-select Functionality for Tasks in Todoist Extension

### ISSUE THREAD

**Issue by geraldaddey** [raycast/extensions#8598]
### Extension

https://www.raycast.com/doist/todoist

### Description

Problem:
Currently, the Todoist Raycast extension lacks the ability to select multiple tasks simultaneously. This feature would greatly enhance the usability and efficiency of the extension, particularly for users who frequently work with multiple tasks at once. (labelling, completing, moving, scheduling, deleting, changing task priority ) 

Feature Request:
I propose implementing multi-select functionality, which allows users to select multiple tasks by holding down the "Shift" key and pressing the "Arrow Up" or "Arrow Down" keys.

Expected Behavior:
When the user holds down the "Shift" key and presses the "Arrow Up" key, the following should happen:

The currently selected task, if any, remains selected.
The task immediately above the currently selected task becomes selected.
If the user presses "Arrow Up" again while holding "Shift," the task above the currently selected task is also selected.
This selection behavior continues until the user releases the "Shift" key or reaches the top of the task list.
When the user holds down the "Shift" key and presses the "Arrow Down" key, the following should happen:

The currently selected task, if any, remains selected.
The task immediately below the currently selected task becomes selected.
If the user presses "Arrow Down" again while holding "Shift," the task below the currently selected task is also selected.
This selection behavior continues until the user releases the "Shift" key or reaches the bottom of the task list.

### Who will benefit from this feature?

This feature would be a valuable addition for users who frequently need to perform batch actions on tasks, such as marking them as complete, moving them to a different project, applying labels etc.

**Comment by thomaslombart** [comment]
Raycast doesn't have support for multi-selection right now, so there's not much I can do here without overcomplicating or over-engineering the extension at the moment. I'm closing the issue as "won't fix" for now, but rest assured I'll discuss the multi-select functionality with the team.

**Comment by thomaslombart** [comment]
@geraldaddey Hey, I've discussed the multi-select functionality with the team, and while we see its value, it requires a complete rethinking of how the list and grid items would work... or we would need to consider an entirely different functionality to address this use case. We will address it at some point, but we are not prioritizing it in the near future. I hope you'll understand 😊

**Comment by geraldaddey** [comment]
Hi there @thomaslombart,

Thanks for considering the multi-select functionality. I just wanted to highlight that this feature is already available on the Todoist mobile app, and integrating it into the Raycast extension would indeed supercharge its usability. It could potentially attract a larger user base looking for this added convenience. I'm excited about the possibilities and hope to see it in the future.
