### ISSUE TITLE
[Browser Bookmarks] Permission error for Safari bookmarks

### ISSUE THREAD

**Issue by a835785342** [raycast/extensions#8603]
### Extension

https://raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: EPERM: operation not permitted, open '/Users/xxxx/Library/Safari/Bookmarks.plist'
```

### Steps To Reproduce

macos13.0

**Comment by thomaslombart** [comment]
Could you check out the system preferences to see if Raycast has full disk access? If not, please enable it and let me know if you still have the error.


![CleanShot 2023-09-28 at 10 10 20@2x](https://github.com/raycast/extensions/assets/16003285/0a3b296a-bbc1-4e29-984e-34529efd07df)

**Comment by a835785342** [comment]
> Could you check out the system preferences to see if Raycast has full disk access? If not, please enable it and let me know if you still have the error.
> 
> ![CleanShot 2023-09-28 at 10 10 20@2x](https://user-images.githubusercontent.com/16003285/271216689-0a3b296a-bbc1-4e29-984e-34529efd07df.png)

its ok,thank
