### ISSUE TITLE
[Google Workspace] Can't open Google Colab files

### ISSUE THREAD

**Issue by Bold-maverick** [raycast/extensions#8610]
### Extension

https://www.raycast.com/raycast/google-workspace

### Description

The "Starred Google Drive Files" command is pointing the the wrong url.
Command url: https://drive.google.com/file/u/0/d/1wfytOXWIw86Y&authuser=user/edit
file url: https://colab.research.google.com/drive/1wfytOXWIw86Y

The command url points to the error:
"Sorry, the file you have requested does not exist.

Make sure that you have the correct URL and the file exists."

### Steps To Reproduce

1. MacBook M2, Os Ventura, Browser Brave [Version 1.58.131 Chromium: 117.0.5938.92 (Official Build) (arm64)]
4. "Sorry, the file you have requested does not exist.

Make sure that you have the correct URL and the file exists."

**Comment by thomaslombart** [comment]
Could you please send some screenshots? The extension basically opens the URL that the Google API sends back, and we don't transform it. So, I'm not sure if there's anything we can do in this case.

**Comment by Bold-maverick** [comment]
> Could you please send some screenshots? The extension basically opens the URL that the Google API sends back, and we don't transform it. So, I'm not sure if there's anything we can do in this case.

An "authuser" param is always added to the url, when removed GDrive is able to locate the file, but the default urls from the extension show to the below page
<img width="919" alt="Screenshot" src="https://github.com/raycast/extensions/assets/89585848/62aeec88-d4fa-4777-a441-4aa28a39fc62">

**Comment by thomaslombart** [comment]
If I got it well, `https://drive.google.com/file/u/0/d/1wfytOXWIw86Y` does open the file like you expected, right? But appending the `authuser` parameter does not? Also why is the `authuser` value equals to `user/edit`? It should be the mail associated to the Raycast extension instead.

**Comment by Bold-maverick** [comment]
Yes the `authuser` velue is `user/edit` as you mentioned, and it's returning the right email. I uninstalled the extension, refreshed the connection, and allowed ad blockers and trackers but nothing seems to work.

**Comment by thomaslombart** [comment]
No, my question was why it's `user/edit` instead of your Google account?

**Comment by Bold-maverick** [comment]
The auth/user value is `authuser=myemail/edit` 
Also, I've installed the Menu Bar Command for "Starred Google Drive Files" and it's pointing to the right url without the `authuser` param.

**Comment by thomaslombart** [comment]
Does this happen for all files, or only a certain type of files?

**Comment by Bold-maverick** [comment]
So seems like the issue only occurs when trying to open a Google Colab file

**Comment by thomaslombart** [comment]
Interesting. To provide more context, the `authuser` value is used to ensure that when you open Google Drive files, it opens with the account you logged in with in Raycast. Therefore, it is likely that Google Colab does not handle this `authuser` parameter correctly. The reason it works with the menu bar command is simply because the parameter has been forgotten.

Do you know how to specify the account for Google Colab to use when opening a file via the URL? If that's not possible, we can consider making an exception for it, but it might open the file with the wrong account (which is still better than not opening it at all).
