### ISSUE TITLE
[Wolfram Alpha] Readme should specify API type

### ISSUE THREAD

**Issue by msiemens** [raycast/extensions#8613]
### Extension

https://www.raycast.com/mathieudutour/wolfram-alpha

### Description

When creating an App ID, Wolfram Alpha requires to select the API type. Users need to select "Simple API" for the extension to work, but this is not documented at the moment.

![Screenshot 2023-09-29 at 15 41 33](https://github.com/raycast/extensions/assets/1873922/cb1c14fb-9392-4b6f-a5c3-f96925701832)

### Steps To Reproduce

1. Create an App ID with the API type other than "Simple API"
2. Execute any query

### Current Behaviour

Error: Invalid App ID

### Expected Behaviour

Extension's readme states the API type

**Comment by mathieudutour** [comment]
Good idea, do you want to open a PR to fix it?
