### ISSUE TITLE
[RegEx REPL] Include Regex Cheatsheet on the regex builder screen

### ISSUE THREAD

**Issue by esperpanorama** [raycast/extensions#8614]
### Extension

https://www.raycast.com/hongkiulam/regex-repl

### Description

This awesome extension helps me to quickly write and test regular expressions. However, I do not know the entire regex syntax out of my head and the volatility of Raycast windows causes my expression to get lost if I have to look something about expressions up while I am editing.

It would be very helpful if the first screen of this extension would include some kind of regex cheatsheet, so that I can quickly lookup infos I am not sure about. For example I normally use the cheatsheet included at https://rubular.com/ because it is very short and precise.

### Who will benefit from this feature?

Everyone who want to write a regular expression and does not know the entire syntax out of their head.

### Anything else?

I ❤️ this extension!

**Comment by hongkiulam** [comment]
I can have a look at this, but not sure how best to place the 'cheatsheet' as I only have the UI elements provided by raycast to work with 🤔

**Comment by esperpanorama** [comment]
Thank you, I really appreciate your effort :)

**Comment by hongkiulam** [comment]
@raycastbot close this issue

**Comment by esperpanorama** [comment]
Awesome, thank you for your update, works like a charm! 🚀
