### ISSUE TITLE
[System Monitor] ... The extension again uses all CPU resources

### ISSUE THREAD

**Issue by otakukz17** [raycast/extensions#8617]
### Extension

https://www.raycast.com/hossammourad/raycast-system-monitor

### Description

I have previously created such a bug report. When I run the extension, it instantly creates a lot of pm processes and fully utilizes the CPU.
![image](https://github.com/raycast/extensions/assets/53805854/5f4983a0-b08b-4c65-9ae9-78762000baed)
I use MacBook Pro M1 8/512

### Steps To Reproduce

1. Install the extension from the Store
2. Run it
3. In the extension itself and in MacOS monitoring you can see that the CPU is 100% utilized

### Current Behaviour

Utilization of all CPU resources

### Expected Behaviour

Running a single process to monitor system status

**Comment by shawnyeager** [comment]
Can confirm this. Just sent the feedback via Raycast. This only happens using this extension. By comparison, running `top`, `htop`, `glances`, etc. via CLI does not cause the same behavior.

**Comment by pernielsentikaer** [comment]
It might be something that we can improve a bit, but it looks like the extension is collecting a lot of data, which is resource-intensive due to multiple calls.

I just tried opening the extension for a minute, and this was my result:

![raycast-system-monitor 2023-10-17 at 09 09 40](https://github.com/raycast/extensions/assets/38033107/282f804a-bc18-4054-a9f8-546aee14c227)

**Comment by shawnyeager** [comment]
Pay particular attention to @otakukz17's screenshots. The extension is causing multiple threads of `pmset` (macOS' power management daemon) to spawn, which in turn consume max CPU. My guess is that this is an Apple Silicon thing. Suggest testing.

As a result, the extension is unusable for me.

**Comment by shawnyeager** [comment]
Be that as it may, it's accurate. As I noted, it pegs my CPU by causing multiple instances/threads of `pmset`. Using a system monitor to measure performance when the system monitor, itself fully consumes the CPU is unusable.
