### ISSUE TITLE
[Jira] Error creating Jira Issue

### ISSUE THREAD

**Issue by literallyjustroy** [raycast/extensions#8620]
### Extension

https://www.raycast.com/raycast/jira

### Description

The Create Issue command always errors out for me, usually shortly after opening. I'm on an M1 Mac updated to Sonoma.
<img width="252" alt="image" src="https://github.com/raycast/extensions/assets/56088145/61609124-dca5-41fe-8d85-9b064b98e7df">

This GIF is in real time:
![Screen Recording 2023-09-30 at 6 12 07 AM](https://github.com/raycast/extensions/assets/56088145/b6454186-3ee1-4578-bc0d-c047c9309daa)

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

### Steps To Reproduce

1. Select the Create Issue command.
2. The extension errors out shortly after.

### Current Behaviour

An error when creating a Jira Issue

### Expected Behaviour

Successfully able to create a Jira Issue

**Comment by thomaslombart** [comment]
Thanks for flagging this issue. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!

**Comment by literallyjustroy** [comment]
Thanks, I'll look into it this week. If anybody else happens to pick this up in parallel don't worry about stepping on my toes.

**Comment by literallyjustroy** [comment]
I am now unable to recreate this issue.. Might've been caused by high memory usage via Crowdstrike Falcon. If it happens again I'll take a crack at it but since I can't recreate the issue right now I'm not looking into this anymore.

**Comment by thomaslombart** [comment]
All right, I'll close the issue then. Thanks for letting me now!

**Comment by literallyjustroy** [comment]
@thomaslombart I'm able to recreate this today. I'm not a member of the Slack workspace so I'm unable to join that at the moment; I shot you an email. 

Where would be a good starting place? The error messages don't seem to provide a stack trace, just some references to workers.

**Comment by thomaslombart** [comment]
@literallyjustroy can't you join at raycast.com/community? You should be able to. Then, if you have any extensions-related questions, the right channel would be #extensions.

**Comment by literallyjustroy** [comment]
I was able to join the community by the way - Not sure what my problem was originally. Probably something to do with attempting to join on a work machine.
