### ISSUE TITLE
[Gmail] Support for Multiple Accounts

### ISSUE THREAD

**Issue by pgvanhoven** [raycast/extensions#8628]
### Extension

https://www.raycast.com/tonka3000/gmail

### Description

Right now, the Gmail extension for Raycast only has support for _one_ Gmail account. **It would be _amazing_ if multiple accounts could be viewed and managed through the extension.**

### Who will benefit from this feature?

Students that have both a private and a school email.

**Comment by tonka3000** [comment]
Very tricky to make with the current API of Raycast. I have multiple accounts myself and would love to add all to my extension.

Details see #269
