### ISSUE TITLE
[Music]: 

### ISSUE THREAD

**Issue by hexiaojie123** [raycast/extensions#8630]
### Extension

https://raycast.com/fedevitaledev/music

### Description

Command failed with exit code 1: osascript -e tell application "Music" to set loved of current track to true 
28:62: execution error: “Music”遇到一个错误：描述符类型不匹配。 (-10001)

### Steps To Reproduce

1. play track in apple music
2. tap love track in raycast with the help of apple music extension

### Current Behaviour

error

### Expected Behaviour

tag love to current track

**Comment by rawnly** [comment]
#8648 fixes this

**Comment by rawnly** [comment]
@raycastbot close this issue
