### ISSUE TITLE
[Heroicons] ...

### ISSUE THREAD

**Issue by gwlortscher** [raycast/extensions#8631]
### Extension

https://www.raycast.com/johndoe123789/heroicons

### Description

Crashes immediately upon use. Just says "an error occurred, try again later."

### Steps To Reproduce

1. Launch Heroicons Search

**Comment by devajmeireles** [comment]
> We could not find the extension related to this issue. Please update the issue with the correct link to the extension.

Isn't https://www.raycast.com/johndoe123789/heroicons?

**Comment by MKlblangenois** [comment]
I got the same issue on my side with extension linked by @devajmeireles

**Comment by JonasPardon** [comment]
Same here

**Comment by rspeicher** [comment]
The extension is attempting to fetch `https://raw.githubusercontent.com/tailwindlabs/heroicons.com/master/src/data/tags.js` from [here](https://github.com/raycast/extensions/blob/f30ca36f8da62ca7682ec516c8ab6d1d84d08d12/extensions/heroicons/src/heroicons.ts#L11-L13). It seems that repository was removed/made private.

So either this extension needs to store this information locally (which as a bonus might remove the need to be online) or mirror that information elsewhere.

**Comment by shreyshah33** [comment]
Facing the same issue!

**Comment by JonasPardon** [comment]
This looks like it's resolved now. The icons load again without any issue for me.
