### ISSUE TITLE
[GitHub] Menu bar icon looks out of place in when dark background and light text

### ISSUE THREAD

**Issue by dhruvkb** [raycast/extensions#8632]
### Extension

https://www.raycast.com/raycast/github

### Description

The icon is permanently dark and looks out of place when the status bar is white-icon/dark-background.

<img width="703" alt="Screenshot 2023-10-01 at 4 49 11 PM" src="https://github.com/raycast/extensions/assets/16580576/ed360590-5a73-4e75-93aa-91d049acb8be">

### Steps To Reproduce

0. Change wallpapers till the status bar has white icons.
1. PR menu bar remains in the black icon.

### Current Behaviour

Menu bar icon color does not keep up with the default icons.

### Expected Behaviour

Menu bar icon color should match the other menu bar items.

**Comment by tonka3000** [comment]
See #8624
