### ISSUE TITLE
[Obsidian] ...

### ISSUE THREAD

**Issue by AMGMNPLK** [raycast/extensions#8634]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

### Steps To Reproduce

Search for a note

**Comment by KevinBatdorf** [comment]
Hey, sorry for not replying before. About how many notes do you have?

**Comment by AMGMNPLK** [comment]
7000+

**Comment by AMGMNPLK** [comment]
News?

**Comment by KevinBatdorf** [comment]
The extension loads all the notes into memory, and in the case where you have a lot of notes (or a lot of content in the notes), it's crashing. Unfortunately, it will require essentially rewriting the entire extension to index locally and search outside of Raycast's native search mechanism. 

It's a situation where making the changes can result in breaking something seemingly unrelated without realizing it. If someone can figure out a good strategy for adding integration tests with Raycast I'd feel more confident making such a change to the extension.

Unless someone else has a better idea here, I don't know when or if a fix will happen. Obviously, someone else is also welcome to take the risk updating the extension too, and I'd be happy to audit the changes to the best of my ability of course.
