### ISSUE TITLE
[Notion]Template Selection for New Database Items

### ISSUE THREAD

**Issue by geraldaddey** [raycast/extensions#8638]
### Extension

https://www.raycast.com/notion/notion

### Description

I'd like to propose the implementation of a template selection feature in the Raycast extension for Notion when creating new database items. Presently, users have to start with a blank slate, entering data manually, which can be time-consuming and prone to errors. By introducing template options, users would be able to choose from pre-defined templates tailored to their specific use cases, such as project management, task tracking, content creation, etc

### Who will benefit from this feature?

This will benefit all Notion users who rely on templates within their databases. This feature would save users hours of time by eliminating the need to manually recreate structured data from scratch, ensuring efficiency and accuracy. It would also guarantee data consistency, a crucial aspect of database management, by enabling users to start with standardized templates tailored to their specific use cases.

**Comment by thomaslombart** [comment]
Unfortunately, the [Notion API](https://developers.notion.com/reference/intro) doesn't provide support for database templates at the moment. Therefore, I will close this issue as "not planned" to maintain a clean backlog. Please feel free to reopen it in the future if they add support for it.
