### ISSUE TITLE
[Single Disk Eject] Fails to eject SD Card

### ISSUE THREAD

**Issue by brunocbreis** [raycast/extensions#8642]
### Extension

https://www.raycast.com/johndturn/single-disk-eject

### Description

Whenever I try to eject an SD card, it fails to do so, but says it did. It works fine with external ssds.

https://github.com/raycast/extensions/assets/85531625/6edf4626-525c-4e4f-b4f9-13eaa6ab06b2

### Steps To Reproduce

Try to eject an SD card.

### Current Behaviour

Doesn't eject, says it did.

### Expected Behaviour

Eject and confirm or not eject and report error.

**Comment by johndturn** [comment]
@brunocbreis Thanks for surfacing this! I'm doing a bit of travel over the next 2 weeks, but I'll dive in and take a look at it once I'm back and things are settled.

**Comment by brunocbreis** [comment]
Have you managed to get around to this yet?

**Comment by johndturn** [comment]
@brunocbreis thank you for your patience. Im back from traveling now and I'll have time this week to review this and give you an update.

**Comment by johndturn** [comment]
@brunocbreis Looking into this a bit more, I have a qq for you: What sort of SD card is this that you're trying to eject (specific hardware)? Also, how is the SD card formatted (FAT32, exFAT, NTFS, or something else)?

**Comment by brunocbreis** [comment]
I've just tried to reproduce it now and it successfully ejected all of my SD cards. 🙃 I was on another computer, with another SD card when the error happened though. Which I don't have access to anymore 😅

**Comment by brunocbreis** [comment]
It was named Untitled, yes. If I'm not mistaken, it seemed like the card wasn't ejected for a reason (might've been being used by another app), and the problem wasn't that the extension failed to eject it, it was that it failed to warn about the error

**Comment by johndturn** [comment]
@brunocbreis Great call on that. I'll dig into the code a bit more tonight and see if I can replicate the issue / layer in some additional error handling.

**Comment by johndturn** [comment]
@brunocbreis FYI: https://github.com/raycast/extensions/pull/9189
