### ISSUE TITLE
Clipboard history not working anymore via Raycast [CleanShot X] ...

### ISSUE THREAD

**Issue by DC0423** [raycast/extensions#8646]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

After the Cleanshot X update "Open clipboard history" do not work anymore via Raycast command

### Steps To Reproduce

1. Everything was working fine 
2. Update to clean shot 4.6
3. open clipboard history command in Raycast do nothing now

**Comment by Aayush9029** [comment]
"Open clipboard history"

My apologies, I'm not entirely sure which command you're referring to. Could you please clarify?

![Raycast 2023-10-02 at 20 16 38](https://github.com/raycast/extensions/assets/43297314/169766e4-f7eb-408e-832f-a9dbeb78ed49)

**Comment by erics118** [comment]
Do you mean "Open History"?

![CleanShot 2023-10-04 at 13 44 51](https://github.com/raycast/extensions/assets/52634785/3ed87ebe-2d18-4e33-a7aa-dba865efd0d8)

**Comment by Aayush9029** [comment]
@DC0423 

Please provide a video of the problem or step-by-step instructions to reproduce it. I can’t replicate it and found no error logs on the cloud.

Thank you!

**Comment by NiiyaDaiki** [comment]
@DC0423 @Aayush9029 
Hi there!
I had the same problem, but I solved it with the following method!

Make sure that "Allow applications to control CleanShot" is checked in the advanced settings of Clean Shot X.
[This seems to have been added in Clean Shot 4.6.](https://cleanshot.com/changelog)
If it is not checked, check it. You should then be able to start Clean Shot X from Raycast.

![CleanShot 2023-11-08 at 19 40 23@2x](https://github.com/raycast/extensions/assets/56012694/d6462566-900f-48a0-bd23-99fba5d3d7f0)


If you have already solved this problem, please ignore my answer.
