### ISSUE TITLE
[Jira Time Tracking] ...

### ISSUE THREAD

**Issue by peterreibel** [raycast/extensions#8657]
### Extension

https://www.raycast.com/niallpaterson/jira-time-tracking

### Description

The extension is only showing the first 50 projects. It would be nice to have it show _all_ projects. My company develops solutions and products alike which is why we are exceeding the extension's 50 projects limit in Jira.

### Who will benefit from this feature?

All users of companies with more than 50 project entries in Jira.

**Comment by niallpaterson** [comment]
Hey @peterreibel!

Apologies for the delay. Good point, happy to look into this.

**Comment by peterreibel** [comment]
Thanks @niallpaterson, that would be awesome!
