### ISSUE TITLE
[Color Picker] ...

### ISSUE THREAD

**Issue by kyellareddy** [raycast/extensions#8662]
### Extension

https://www.raycast.com/thomas/color-picker

### Description

Would it be possible for Color Picker to also show matching colors/color palettes?

For example, after I pick a color, it would have an option to show a color that has a good contrast with the color I picked.
Sort of like https://coolors.co/contrast-checker.

### Who will benefit from this feature?

People who are looking for an easy way to find a good colors for design work.

**Comment by thomaspaulmann** [comment]
@kyellareddy that should be possible. It should probably be a new command. For a color, it could push a new screen to suggest colors. I even had the idea for a contrast checker.
