### ISSUE TITLE
[iMessage 2FA] ... doesnt return anything

### ISSUE THREAD

**Issue by Pixel-Panda** [raycast/extensions#8666]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

 no errors, no log, just empty

### Steps To Reproduce

run it

### Current Behaviour

 no errors, no log, just empty

### Expected Behaviour

something at all

**Comment by ronaldheft** [comment]
Have you received a recent two factor code via text? Could you provide an example of a text message you're expecting to find a two factor code in?
