### ISSUE TITLE
Raycast Bitwarden extension not loading bug

### ISSUE THREAD

**Issue by SARRAF-5757** [raycast/extensions#867]
# Extension – [Bitwarden Vault](https://github.com/raycast/extensions/tree/71dc0903b48af29aa0595ad456899ba7679312e0/extensions/bitwarden/)
Author: @pomdtr

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.28.0

**Comment by pomdtr** [comment]
@mattisssa can we close this ? The issue is not useful without details
