### ISSUE TITLE
[Spotify Player] a message "unknown error" pop up when using 'Toggle Play/Pause' after installed 'Spotify Player'

### ISSUE THREAD

**Issue by hmk-frankie** [raycast/extensions#8672]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

[Spotify Player] a message "unknown error" pop up when using 'Toggle Play/Pause' after installed 'Spotify Player'

### Steps To Reproduce

1. Macbook M1, 2020 / 8GB / MacOS Sonoma 14.0
2. Raycast v.1.59.0 + Latest downloaded Spotify App + authenticated Raycast access at https://accounts.spotify.com/authorize/ (both Spotify App and authenticated the same Spotify account)
3. Run 'Toggle Play/Pause'
4. See error 'Unknown error'
![image](https://github.com/raycast/extensions/assets/90236543/43352013-f48e-4273-82c1-e9540a996ace)
![image](https://github.com/raycast/extensions/assets/90236543/135e5051-7a67-431e-b592-45b495a3d788)
![image](https://github.com/raycast/extensions/assets/90236543/04f16cbe-e614-4630-a12d-933876950197)

### Expected Behaviour

I can use the function 'Toggle Play/Pause' in Spotify Player within Raycast by selected it or Raycast hotkey.

**Comment by peduarte** [comment]
Is this still happening?

**Comment by shsitaram** [comment]
I receive the same error when attempting to run the **toggle play/pause** command. When I click the **play** button from the menu bar, I receive a different error: *Player command failed: Premium required*. 

On the [docs for start/resume playback](https://developer.spotify.com/documentation/web-api/reference/start-a-users-playback), I see the following passage:
> This API only works for users who have Spotify Premium.

**Comment by thomaslombart** [comment]
I'm closing this issue to maintain a clean backlog. Feel free to comment if you still have the problem.
