### ISSUE TITLE
[LastPass Credentials Search] Failing to use extension since last update

### ISSUE THREAD

**Issue by mbrcic-avy** [raycast/extensions#8674]
### Extension

https://www.raycast.com/alex-popov-tech/lastpass

#### Error:
```
SyntaxError: Invalid regular expression: /Nz![:ax.Pxp!y2?2WHb</: Unterminated character class

wa:index.tsx:19:51

---
16: 
17: export default function Command() {
18:   const { email, password, syncRate, hidePassword } = getPreferenceValues<Preferences>()

### Steps To Reproduce

As soon as I trigger/open extension it fails
1. I can login via lpass-cli
2. Extension worked after last issue I opened, where the resolution was to change password
3. I didn't change anything, so most probably latest update has something that changed which causes this

Ping me if more details are needed.

### Current Behaviour

Extension doesn't work when summoned via raycast

### Expected Behaviour

Extension to work

**Comment by mbrcic-avy** [comment]
SyntaxError: Invalid regular expression: /Nz![:ax.Pxp!y2?2WHb</: Unterminated character class

wa:index.tsx:19:51

---
16: 
17: export default function Command() {
18:   const { email, password, syncRate, hidePassword } = getPreferenceValues<Preferences>();
19:   const [showPassword, setShowPassword] = useState(!hidePassword);
20: 
21:   const api = lastPass(email, password);
22:   const [isLoading, setIsLoading] = useState(true);
---

Ir:index.js:9:2490
    at ray-navigation-stack
$o:index.js:9:2088

**Comment by alex-popov-tech** [comment]
hey @mbrcic-avy , thank you for opening this issue!

the error is super weird, can you try restart your mac, or reinstall/update raycast itself?

**Comment by mbrcic-avy** [comment]
Will try in few hours, and get back to you.

Currently it says I am on v1.59.0 of Raycast.

**Comment by mbrcic-avy** [comment]
Didn't go to re-install Raycast, but tried some other things:
- reinstalled the extension, didn't help
- all the other extensions work correctly

Will maybe try some other options in next days, but can not promise.

**Comment by alex-popov-tech** [comment]
@mbrcic-avy sorry for your issue, but i did not change code in weeks i think, and the error message is not helping to understand whats wrong :( it works on my raycast of the same version as yours :( maybe try to re-install extension? it should be fairly easy

**Comment by mbrcic-avy** [comment]
All good. Again special characters in password. Can be closed.
