### ISSUE TITLE
[unicode-symbols] Add Unicode Block “Greek and Coptic”

### ISSUE THREAD

**Issue by allen-liaoo** [raycast/extensions#8678]
### Extension

https://github.com/raycast/extensions/blob/main/extensions/unicode-symbols/

### Description

Add symbols in the Unicode block "Greek and Coptic" (see [here](https://www.compart.com/en/unicode/block/U+0370)) as it has Greek symbols that are commonly used in mathematical notation. The index (HTML entity number) of the block is from `880` to `1023`. 

Take theta θ as an example. Currently there are 20 variations provided in the [assets.json](https://github.com/raycast/extensions/blob/main/extensions/unicode-symbols/assets/dataset.json), but none of which is not either bold or italics.
<img width="758" alt="image" src="https://github.com/raycast/extensions/assets/16383622/3f9d7441-0b00-42ad-bb97-fb0812c5b917">

**Comment by TonyVlcek** [comment]
Hi, just bumped into this as well. The Greek symbols currently insert a multi-byte version even though single-byte alternatives exist.

<img width="294" alt="image" src="https://github.com/raycast/extensions/assets/4984658/e2e4e993-1c4e-490c-9250-66c719aa11d4">

It'd be nice to default to the single-byte variants and have the option to sue the multi bytes if need be.

**Comment by allen-liaoo** [comment]
@TonyVlcek thank you so much!
