### ISSUE TITLE
[UniFi] … Can't connect to console

### ISSUE THREAD

**Issue by bgiovand** [raycast/extensions#8679]
### Extension

https://www.raycast.com/tonka3000/unifi

### Description

Can't connect to my local console, using a local account.

UDM Pro
UniFi OS v3.1.16
Network v7.5.176

If i use https for the console i get error: self signed certificate

If i use http for the console i get error: unknown.

<img width="298" alt="image" src="https://github.com/raycast/extensions/assets/179564/c8adce10-c870-4b25-aa0f-8468ea73017d">

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/179564/507e8e51-432c-4a2a-a85c-9dd6d5728d93">

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/179564/6d321821-b92d-4513-b418-e012f41e7026">

I tried creating a separate local account just for raycast to no avail.

Attempted to use .local mDNS domain but no luck as well.

### Steps To Reproduce

1. Install extension
2. Enter console URL, username and password (all local)

### Current Behaviour

Can't connect to my UDM pro console. Errors out using either http or https.

### Expected Behaviour

I'm assuming i should be able to see my and select my unifi udm pro, and then use the commands to list connect devices etc.

**Comment by tonka3000** [comment]
Hm strange 🤔. Do you use a self signed certificate? What address do you usually use when go to the UDM Pro Dashboard in the browser?

**Comment by bgiovand** [comment]
It's a self signed cert. Either 192.168.1.1 or unifi.local (mDNS) for the addresses. I'm away for a few days so will be a bit before i can trouble shoot again.

**Comment by bgiovand** [comment]
Odd, I removed and re-added the self signed cert into keychain and that seemed to fix it.
