### ISSUE TITLE
[DevUtils] There is no application set to open the URL `devutils://`

### ISSUE THREAD

**Issue by aimsecond** [raycast/extensions#8681]
### Extension

https://www.raycast.com/devutils/devutils

### Description

The Devutils commands don't work for my environment. 
Take the `Base64 string encode/decode` command as an example. When I click on that command, I see error:

> There is no application set to open the URL devutils://base64encode?clipboard.

I tried to click the `Choose application` button and select `Raycast`, but all of the apps grayed out and none was selectable. 

![image](https://github.com/raycast/extensions/assets/16809491/47ff6109-a98a-445c-831d-9efde374b7ee)

System Info:
- MacOS Ventura 13.6 (22G120)
- Raycast v1.59.0

### Steps To Reproduce

1. Install Devutils from Raycast store
2. Copy some string into the clipboard
3. Trigger raycast, search with keyword 'base64'. The command `Base64 string encode/decode` is the first result.
4. Select the above command by mouse click or press enter key
5. The error "There is no application set to open the URL devutils://base64encode?clipboard." will pop up.

### Expected Behaviour

The base64 encoded string will be inserted at the top of the clipboard history.

**Comment by aimsecond** [comment]
Hi, are there any updates on this issue? Thanks!

**Comment by vietanhlehuu** [comment]
Hi @aimsecond , it requires the DevUtils app installed to use this extension. Have you installed it?

**Comment by astanciu** [comment]
I am seeing the same error after a fresh install of Raycast. DevUtils is the first and only extension installed:
![image](https://github.com/raycast/extensions/assets/1675025/d17fc18e-0ec3-4425-82d3-3e84178dfb12)
![image](https://github.com/raycast/extensions/assets/1675025/87465181-aeb6-4480-a693-e4d61e010250)

**Comment by Joren-Thijs-KasparSolutions** [comment]
This extension is an integration for the [devutils](https://devutils.com/) app. You have to install it seperatly.
