### ISSUE TITLE
[Arc] Search Tabs feature opens a random, unrelated tab if you hit Enter before refresh is complete

### ISSUE THREAD

**Issue by jrochell** [raycast/extensions#8684]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

Expected results: Selecting the tab shown in Raycast will take you to that tab in Arc. 

Actual: If you select a tab and hit enter before the loading indicator animation completes, selecting the result will take you to a random, unrelated open tab. 

### Steps To Reproduce

Steps to reproduce: 
1. Open Raycast
2. Invoke the Search Tabs function (note the loading bar animation that shows below the text field) 
3. Search for a tab and press enter while the loading bar animation is still going.

**Comment by pendolino** [comment]
Any update for this bug? It's been ongoing still.

**Comment by pendolino** [comment]
Still waiting for a fix on this please

**Comment by loris** [comment]
duplicate of https://github.com/raycast/extensions/issues/8189

**Comment by thomaslombart** [comment]
This should have been fixed with the following fix: https://github.com/raycast/extensions/pull/10017.

**Comment by jrochell** [comment]
Seems to be fixed for me! Thank you 🙌
