### ISSUE TITLE
[Linear] Create Task command fails with time out

### ISSUE THREAD

**Issue by connor-gg** [raycast/extensions#8689]
### Extension

https://raycast.com/linear/linear

#### Error:
```
FetchError: request to https://api.linear.app/graphql failed, reason: connect ETIMEDOUT 2606:4700::6812:1ce7:443
    at ClientRequest.<anonymous> (/Users/connordodge/.config/raycast/extensions/a9696c4c-a4e8-4ff1-bf49-c9015f796200/create-issue.js:23:308424)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Steps To Reproduce

1. Newly installed Linear extension in Raycast
2. New Linear instance with the default tasks
3. Open create task command for Linear in Raycast
4. The extension tries to load some data from Linear
5. The request in the description fails

I've tried a couple of different raycast commands and none of them seem to able to load any data from Linear at all. However, I can navigate to the linear app in my browser and everything there seems to work fine. In Raycast I just see the loading shimmer at the top of the window until the request times out.

### Current Behaviour

Raycast extension is unable to load data from linear api

### Expected Behaviour

Raycast extension should be able to load data from linear api

**Comment by thomaslombart** [comment]
Do you consistently have the error? It looks like something on Linear's end.

**Comment by connor-gg** [comment]
Yes, I do consistently have the error. I'm just trying out Raycast and Linear both for the first time, and I haven't been able to use them together at all. It spins like it is searching and then times out on every command I try.

It's possible it is something on Linear's end, this is just where the report error functionality took me.

**Comment by thomaslombart** [comment]
Could you send a recording?

**Comment by connor-gg** [comment]
Of course. The error that shows at the end is the same one I referenced in the initial report.

https://github.com/raycast/extensions/assets/117552786/792bfde2-3e76-4b61-8cf8-b89fa190fb50

**Comment by thomaslombart** [comment]
That's weird. Are you able to perform a network call using [Insomnia](https://insomnia.rest)  or [Postman](https://www.postman.com) with your [personal Linear API key](https://linear.app/raycast/settings/api)?

**Comment by connor-gg** [comment]
Yes, I was able to do a request via Postman and it worked. I did a POST request to `https://api.linear.app/graphql` with the query 

```
{
    "query": "{ issues { nodes { id title } } }"
}
```

and I got back all of my linear tickets.

**Comment by connor-gg** [comment]
I also ttried looking at network traffic using a proxy (proxyman on mac), but I wasn't able to find any for this extension when it was trying to make requests. I was able to see requests from raycast to the raycast store through the proxy, but I couldn't see requests made from other raycast extensions, like the Todoist extension (which did show my tasks, so it made some kind of request that worked) 

So I'm not sure if that tells me anything meaningful or not. I'm not sure where, or even if, the network traffic from extensions would show up.

**Comment by thomaslombart** [comment]
Do you have this issue only on the Linear extension or also on others (e.g GitHub, Notion, etc.)?

**Comment by connor-gg** [comment]
I had that thought when I first logged the bug, and I tried Todoist and it worked fine then, and it still works fine. 

I tried github and notion as well since you brought them up. Github is working fine, but curiously Notion is timing out as well. It doesn't surface the error the same way the Linear extension does though, so I can't get the exact error.

**Comment by thomaslombart** [comment]
What error are you getting on Notion?

**Comment by connor-gg** [comment]
It just says "Request to Notion api has timed out"
![Screenshot 2023-10-26 at 5 11 44 AM](https://github.com/raycast/extensions/assets/117552786/12028c0e-756d-4c51-ac3c-fde0e83b974b)

**Comment by connor-gg** [comment]
I just updated my mac os this morning, and the Raycast / Linear and Raycast / Notion integrations seem to be working now. I am able to search and get results, and I am able to create tasks.

**Comment by thomaslombart** [comment]
Thanks for letting us know. Glad it works out now!
