### ISSUE TITLE
[GitHub] I only see my own repos, not external ones to which I was invited

### ISSUE THREAD

**Issue by kainbacher** [raycast/extensions#8691]
### Extension

https://www.raycast.com/raycast/github

### Description

![CleanShot 2023-10-05 at 16 42 43@2x](https://github.com/raycast/extensions/assets/593335/4c55b644-b498-47da-8813-8b4eb0e1de3e)
![CleanShot 2023-10-05 at 16 43 09@2x](https://github.com/raycast/extensions/assets/593335/d83edc05-279e-4971-a332-9dffba123aad)
![CleanShot 2023-10-05 at 16 43 16@2x](https://github.com/raycast/extensions/assets/593335/ae62a10f-7554-4f97-9c67-8460b44f06c0)

### Steps To Reproduce

1. add your github account
2. you need acces to a repo from another user
3. try to create a new issue for this repo

### Current Behaviour

I can't select this repo

**Comment by thomaslombart** [comment]
Have you granted access to other repos?

![CleanShot 2023-10-12 at 11 42 53@2x](https://github.com/raycast/extensions/assets/16003285/e2fdd6bd-b806-4362-aa9a-42d1373dedba)

**Comment by kainbacher** [comment]
<img width="994" alt="CleanShot 2023-10-12 at 15 49 42@2x" src="https://github.com/raycast/extensions/assets/593335/039d84c8-8279-482d-bbd1-ee3cc2c97731">

@thomaslombart yes

Maybe a difference is, that it's repos from another user not an organization. But I have access to this repos, so it should also work.

**Comment by thomaslombart** [comment]
When you say, "I have access" do you mean that you are a collaborator in these repositories?
