### ISSUE TITLE
[Pomodoro] Menu Bar countdown buffer

### ISSUE THREAD

**Issue by aaronjz** [raycast/extensions#8699]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

When using the menu bar Pomodoro command, the countdown timer animation seems to buffer/stutter frequently. You occasionally see the seconds change, but not continuously, though it seems like the countdown timer is still happening in the background. If I click on the menu bar icon, it will show the countdown animation for a couple of seconds before freezing again for about 10 seconds.

### Steps To Reproduce

1. Run Pomodoro menu bar command
2. See the menu bar countdown timer animation freeze frequently

### Current Behaviour

Freezing countdown timer animation

### Expected Behaviour

A continuous second-by-second animation of the countdown timer in the menu bar.

**Comment by pernielsentikaer** [comment]
This is currently a limitation in Raycast. You cannot go below 10 seconds from the menubar at the moment, but it's something that we want to improve in the future.
