### ISSUE TITLE
[Deepcast] Unknown error when translate.

### ISSUE THREAD

**Issue by rea1shane** [raycast/extensions#8710]
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

Unknown error when translate:

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/93363751/4f419441-a985-4651-955c-5a59d4994e42">

Api key is available, Translate to Chinese is work:

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/93363751/35f298d0-d235-4beb-8f14-e073c84c64a9">

How to debug it?

### Steps To Reproduce

Translate anything use "Deepcast > Translate".

**Comment by erics118** [comment]
See #8917

**Comment by erics118** [comment]
@raycastbot close this issue
