### ISSUE TITLE
[Coffee] Menu bar icon doesn't work normal.

### ISSUE THREAD

**Issue by rea1shane** [raycast/extensions#8716]
### Extension

https://www.raycast.com/mooxl/coffee

### Description

Like title.

Bug 1:

Cannot be enabled from the menu bar:

https://github.com/raycast/extensions/assets/93363751/a2b7398b-9553-4c67-be62-9264dd9b2c8f

Bug 2:

Icon can't click after enable or disable:

https://github.com/raycast/extensions/assets/93363751/3a28ebc0-a915-4573-80d9-053f50f3566a

**Env:**

MacBook Pro:
Apple M1 Pro
14.0 (23A344)

Raycast:
1.59.0

### Steps To Reproduce

See videos.

**Comment by rea1shane** [comment]
fix by https://github.com/raycast/extensions/pull/9210

**Comment by pernielsentikaer** [comment]
🔥
