### ISSUE TITLE
[Color Picker] Custom color format

### ISSUE THREAD

**Issue by tobiasht** [raycast/extensions#8729]
### Extension

https://www.raycast.com/thomas/color-picker

### Description

In the programs I use, the HEX colors do not start with #. When pasting colors multiple times a day, it gets tedious to remove them every time. I would love it if you could add alternative writings for some of the different color formats. 

There will undoubtedly be many similar requests to this one, so I suggest adding more default color formats. Here are some examples:

![Screenshot 2023-10-08 at 16 28 38](https://github.com/raycast/extensions/assets/20655261/856eff1f-c104-4a5d-8540-08cce6680b1a)

 If you want to take it one step further, I suggest taking inspiration from the [PowerToys' Color Picker](https://learn.microsoft.com/en-us/windows/powertoys/color-picker), where you can make completely custom color formats. 

![image](https://github.com/raycast/extensions/assets/20655261/9e175528-54cd-4c81-819d-a9127b2f6d82)

### Who will benefit from this feature?

Everyone that works with colors every day. The format of the colors really depends on the program or the programming language that you are using. 

### Anything else?

By implementing the Custom color format. Programmers could potentially paste in the entire "color string" (eks: `Color(0xFF000000)` ) in their program. 

Instead of:
1. Writing `Color(0xFF)`
2. Copying the color
3. Pasting the color value. 
4. (Removing the #)

**Comment by TyceHerrman** [comment]
This is still relevant afaik. Color Picker now has more fixed formats and a conversion-target selector, but it still doesn't support bounded custom output templates such as `Color(0x{AARRGGBB})`.

A token-based template system for color components and common encodings would cover application- and language-specific wrappers without allowing arbitrary code execution.

@thomaspaulmann @pernielsentikaer I’m interested in working on implementing - and if that's good by you can we reopen this?
