### ISSUE TITLE
[Music]: Love And Add to Library error

### ISSUE THREAD

**Issue by shadowfish07** [raycast/extensions#8736]
### Extension

https://raycast.com/fedevitaledev/music

### Description

Command failed with exit code 1: osascript -e tell application "Music" to set loved of current track to true 
28:62: execution error: “Music”遇到一个错误：描述符类型不匹配。 (-10001)

### Steps To Reproduce

1. listen Apple Music
2. execute Love And Add to Library

**Comment by rawnly** [comment]
follow #8648

**Comment by rawnly** [comment]
@raycastbot close this issue
