### ISSUE TITLE
[Dropbox] ...

### ISSUE THREAD

**Issue by diwaniec** [raycast/extensions#8741]
### Extension

https://www.raycast.com/chyroc/dropbox

### Description

I get the message "This app is unable to link additional users because it has been frozen pending review" when I attempt to sign in with my Dropbox account.

### Steps To Reproduce

Using the Raycast plug-in, I attempt to sign in to Dropbox as prompted I get the following error message: This app is unable to link additional users because it has been frozen pending review

**Comment by SolidRhino** [comment]
I still getting this bug.
