### ISSUE TITLE
[Obsidian] Allow "Open in default app"

### ISSUE THREAD

**Issue by gacharles23** [raycast/extensions#8746]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

Using this extension to find a particular note, it would be super helpful if the note could be opened in the default app (rather than first needing to open the note in Obsidian and then selecting "Open in default app").

### Who will benefit from this feature?

Anyone who uses a separate editor for working with markdown files in an Obsidian vault. In my case I use Panda for long-form note writing.

Thank you for your consideration.

**Comment by gacharles23** [comment]
Hi @KevinBatdorf, I'm wondering if this is something that might be implemented. Thank you so much!

-Grace

**Comment by KevinBatdorf** [comment]
Yeah let me look into this. I believe Raycast has a way to detect the default app based on the file extension. I have a queue with a few items to work on this weekend and I should be able to get to this one as well. Thanks for the reminder

**Comment by gacharles23** [comment]
Thank you Kevin, that would be wonderful! Is there any chance the "open in default app" could be triggered by Cmd-Enter? I realize that shortcut is currently for "Quick Look" - but I’m not sure I understand the need for Quick Look since we get a preview by default. Plus Cmd-Enter to open in default app works like some of the other Raycast shortcuts I use. Regardless, I really appreciate your plugin and am very thankful for your work to support it! You’ll likely make me a convert from outliner-based note tools to Obsidian. -Grace

**Comment by KevinBatdorf** [comment]
Best I can do without changing functionality for others is to add an option so you can set it as the primary option, with open in obsidian as the secondary one. See here: https://github.com/KevinBatdorf/obsidian-raycast/pull/74

I'll work on a few more issues and set up a PR here on Raycast this weekend

**Comment by gacharles23** [comment]
Amazing!!
