### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by Manyis2023** [raycast/extensions#8751]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

#### Error:
```
Error: Status code: 410

ClientRequest.<anonymous>:index.ts:255:18

---
1: 
---

Object.onceWrapper:node:events:628:26
ClientRequest.emit:node:events:525:35
ClientRequest.emit:node:domain:489:12
```

### Steps To Reproduce

1. copy website 
2. open YouTube-downloader
3. paste
4. Has been running, but the final feedback bugs

**Comment by vimtor** [comment]
Since we are using an unofficial YouTube API, some random errors are to be expected. I would implement better error handling so that you have more context about these errors.
