### ISSUE TITLE
[Authy] After removing the Authy token directly in Authy app, extension cannot reauthenticate again

### ISSUE THREAD

**Issue by vfonic** [raycast/extensions#8754]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

I was cleaning up the various "Devices" in the Authy app (not the Authy Raycast extension, but the actual app). I removed "one too many" device. I mistakenly removed the Authy Raycast extension "device" and now I cannot add it back.

The error that I see when I press Refresh (CMD+R) is Device not found.

### Steps To Reproduce

1. Install the extension and authenticate
2. Remove the device from Authy app
3. Try to re-authenticate from the extension

**Comment by guga4ka** [comment]
@raycastbot close this issue

**Comment by vfonic** [comment]
@guga4ka why did you close the issue? I don't think the proper solution is to reinstall the extension. The extension should have the option to reset its settings to initial values so that you can start from scratch.

**Comment by guga4ka** [comment]
@vfonic This is basically the simplest way to reset a extension. Deleting the access to the account leads to reinstalling of the extension. There is another way, change the authy id at preferences to whatever digits you want, it will clear the cache of the extension, and then start an onboarding from scratch

**Comment by vfonic** [comment]
> Deleting the access to the account leads to reinstalling of the extension.

What do you mean? I deleted the access in Authy app and the extension didn't reinstall. I had to manually remove the extension, go to Raycast store, and install it again. This seems like an overkill to me.

> There is another way, change the authy id at preferences to whatever digits you want, it will clear the cache of the extension, and then start an onboarding from scratch

This, to me, also doesn't sound like the solution. It doesn't sound like something me as an end user should be aware of. Nowhere in the preferences does the "authy id" field say: changing Authy Id will clear the cache, nor there is a button saying "Clear cache". It's a "side effect".

Either way, just wanted to report this. I think it's terrible UX that end users need to reinstall the extension when their auth token expires/is deleted.

![1600179090360](https://github.com/raycast/extensions/assets/67437/18d111ac-f2c3-4a32-b886-afcd68c771fd)

**Comment by gdsmith** [comment]
> What do you mean? I deleted the access in Authy app and the extension didn't reinstall. I had to manually remove the extension, go to Raycast store, and install it again. This seems like an overkill to me.

I think @guga4ka is merely saying that if you delete the access in the Authy app there is no simple recovery step and the easiest way forward for the user is to remove and reinstall the extension.

An extension reset sounds like something that should be implemented system wide by the Raycast team rather than expecting each extension to roll their own version, I'll add a suggestion for that on the Raycast slack.

**Comment by vfonic** [comment]
I agree, Raycast could implement extension reset API of sorts.

Thanks! 🙏
