### ISSUE TITLE
[Toothpick] Device Support - Samsung Galaxy Buds+ (SM-R175)

### ISSUE THREAD

**Issue by oranja** [raycast/extensions#8764]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

**Device brand and model**
Brand: Samsung
Model: Galaxy Buds+ (SM-R175)

**Device data**
```
{
  "device_address": "C4:5D:83:34:23:8C",
  "device_batteryLevelMain": "100%",
  "device_firmwareVersion": "0.0.1",
  "device_minorType": "Headset",
  "device_productID": "0xA012",
  "device_services": "0x800019 < HFP AVRCP A2DP ACL >",
  "device_vendorID": "0x0075",
  "device_connected": "true"
}
```

**Notes:**
The device is displayed as "Galaxy Buds+ (<_ADDR_L4>)", where <_ADDR_L4_> are the last 4 hexadecimal digits of the device address.
In my case it is "Galaxy Buds+ (**238C**)", but will be different for every pair.

### Who will benefit from this feature?

Owners of Samsung Galaxy Buds+ earphones.

**Comment by VladCuciureanu** [comment]
Hey! Right now it's late but I wanted to tell you that I'll look into both topics tomorrow. Thanks for your issues and contributions. All help is appreciated!

**Comment by VladCuciureanu** [comment]
@oranja Please create a Raycast developer account with the username 'oranja' if you want to be added to the contributors list.

**Comment by oranja** [comment]
@VladCuciureanu I've updated the alias on my developer account. Should be okay now I hope.
