### ISSUE TITLE
[Obsidian] Folder Management for Daily Note

### ISSUE THREAD

**Issue by macjabeth** [raycast/extensions#8768]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

It would be awesome if we had the option to designate a particular folder for our daily notes, like an "Activity" folder. Currently, we have to move the notes manually after creating them, but having this feature would be a great quality-of-life improvement, saving us extra steps.

### Who will benefit from this feature?

Obsidian users.

### Anything else?

Thank you for creating this extension!

**Comment by Mattyy94** [comment]
But at the settings of daily notes (in Obsidian) you can setup the folder structure for new daily notes?

**Comment by macjabeth** [comment]
> @macjabeth  But at the settings of daily notes (in Obsidian) you can setup the folder structure for new daily notes? 

Oops, I didn't see that section. It gets added to the correct folder now. Thank you!
