### ISSUE TITLE
Authy: Deleting account from Authy doesn't remove it in extension even after sync

### ISSUE THREAD

**Issue by vfonic** [raycast/extensions#879]
# Extension – [Authy](https://github.com/raycast/extensions/tree/main/extensions/authy)

Author: @guga4ka  (would be good to have author username in the readme: https://github.com/raycast/extensions/tree/main/extensions/authy)

## Description

I removed account from Authy and added it back again. In the Authy app, there's only one account, but in the Raycast Authy extension I see two accounts now and they are called the same so I don't know which is which.

## Steps To Reproduce

1. Add account to Authy
2. Raycast Authy Sync
3. Remove account from Authy
4. Raycast Authy Sync
5. Raycast Authy search token

## The current behavior

Token is still in the extension

## The expected behavior

Token is no longer in the extension as it has been removed.

### Raycast version

Version:
1.28.0

**Comment by guga4ka** [comment]
Accounts that has been deleted from authy app doesn't delete instantly, it exists for 48 hours. If u sync apps after 48 hours, it should delete. You can rename new one and sync again.

**Comment by vfonic** [comment]
It's been just slightly over 48 hours (about 50 hours) now, and I still see both accounts.

> from authy app

Neither Authy app on my desktop and Authy app on my phone have the two logins. The only place where I see two logins is in the Authy Raycast extension.

I'll check again tomorrow and let you know if this problem persists.

Where do these "logins" exist? In the response returned by Authy API? Because I immediately got the changes propagated from my phone app to my desktop app. So it's definitely not in "authy app". Did you mean Authy API?

**Comment by vfonic** [comment]
I forgot to check before, but today when I checked, the account that I deleted before wasn't showing up anymore. I'm closing this issue. Thanks!
