### ISSUE TITLE
[1Password] is not synchronized with the client.

### ISSUE THREAD

**Issue by superwhys** [raycast/extensions#8790]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

when i add a new entry in client or web page, the entry I added cannot be queried using this extension.

### Steps To Reproduce

1. add a new entry in client or web page(add a password with title "testPwd").
2. open Raycast window and select the 1password extension
3. query title "testPwd" in extension
4. can not query the entry i just added

### Current Behaviour

can not query the entry i just added

### Expected Behaviour

query the entry i just added

**Comment by superwhys** [comment]
At first I thought the time was too short and it didn't sync up, but after I tried to wait for a few days, it still couldn't query

**Comment by Davidwalser** [comment]
@superwhys could you resolve the issue?

**Comment by radualexe32** [comment]
+1

I have the same issue. To get all my passwords synced I would need to restart the integration process from scratch

**Comment by solid-pixel** [comment]
same here, acknowledgment from the maintainer would be very appreciated.
