### ISSUE TITLE
[Tim] Start specific task

### ISSUE THREAD

**Issue by adamalfredsson** [raycast/extensions#8792]
### Extension

https://www.raycast.com/tm.wrnr/tim

### Description

It would be such an amazing feature if I could start a specific task from Raycast by searching for it! For example, I could find a "Start timer for 'My website'"

### Who will benefit from this feature?

Multitasking Tim users

### Anything else?

I might be happy to create a PR for this, if the feature request is approved!

**Comment by tmwrnr** [comment]
Hi @adamalfredsson, thanks for using the extension!

Do you mean a new command "Start timer" where a list of all Tasks is shown and you can search and start a task from there?

If yes then you could use the **Tasks** command. The list can be filtered and the selected task can also be startet using ⌘ + ↵.

If you mean something else, can you provide a different extension which has this feature? 

Apart from that, is there anything the extension could do differently/better?

**Comment by adamalfredsson** [comment]
Oh, I hadn't discovered this – that's amazing, exactly what I was looking for! Thanks for an amazing product and sorry for bothering!

**Comment by tmwrnr** [comment]
No problem, I'm glad you like the extension. (I didn't develop Tim itself 😅)

If you have other ideas for improvements, I look forward to the suggestions.
