### ISSUE TITLE
how to use this components in search bar

### ISSUE THREAD

**Issue by chyroc** [raycast/extensions#880]
![image](https://user-images.githubusercontent.com/15604894/153700350-8c0d4baf-d53b-4e60-9d58-aab12c6cbbea.png)

i cannot found this components in docs.

**Comment by unnamedd** [comment]
You can’t. It is not available in the API yet.

**Comment by thomaspaulmann** [comment]
The good news is that we’re working on exposing the component. Stay tuned a little bit longer.

**Comment by thomaspaulmann** [comment]
@chyroc we've just added the component to the API. Find out more [here](https://developers.raycast.com/api-reference/user-interface/list#dropdown).

**Comment by chyroc** [comment]
thanks
