### ISSUE TITLE
[Library Genesis] Book search not working 

### ISSUE THREAD

**Issue by BitLegion** [raycast/extensions#8803]
### Extension

https://www.raycast.com/yz3440/library-genesis

### Description

It does not render a search for books on Library Genesis. Instead, I get the error "TypeError: p.replace is not a function"

### Steps To Reproduce

1. Open up Raycast
2. Navigate to the Library Genesis plugin 
3. Select the "Search with Books" option
4. Attempt to search with a book

**Comment by jphastings** [comment]
This is a duplicate of #8355, there's a [quick-fix](https://github.com/raycast/extensions/issues/8355#issuecomment-1720927792) and an explanation in the (short!) thread.

**Comment by j3lte** [comment]
Fixed in #9549, issue can be closed

**Comment by j3lte** [comment]
@raycastbot close this issue
