### ISSUE TITLE
[Notion] Unable to add page with "No Selection" Select

### ISSUE THREAD

**Issue by wyrwigruz** [raycast/extensions#8805]
### Extension

https://www.raycast.com/notion/notion

### Description

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/22954960/b98ed263-25c6-4028-8457-488f5623a55e">

### Steps To Reproduce

1. Create a page in the database.
2. The page should have an empty selection field selected, labeled "No Selection."
3. Attempt to add the page.

### Current Behaviour

An error occurs.

### Expected Behaviour

I'm able to add page to database

**Comment by erics118** [comment]
Fixed in #8340
