### ISSUE TITLE
[I Don't Have Spotify] error: unable to verify the first certificate

### ISSUE THREAD

**Issue by hossammourad** [raycast/extensions#8806]
### Extension

https://www.raycast.com/sjdonado/idonthavespotify

### Description

The extension command is failing to work and throws the following error message:

![CleanShot 2023-10-15 at 01 25 25](https://github.com/raycast/extensions/assets/4350401/71f0fd04-d5ab-4253-a523-3be2c86fac95)

### Steps To Reproduce

1. Copy link for any Spotify song
2. Paste it in the extension command

### Current Behaviour

error: unable to verify the first certificate

### Expected Behaviour

to find the song on other platforms

**Comment by sjdonado** [comment]
@hossammourad I'm not able to replicate it 
<img width="844" alt="image" src="https://github.com/raycast/extensions/assets/27580836/22e956a7-b632-43d4-b0b2-69892255e8df">

Seems to be that it was a temporary server issue, it is back to normal
<img width="1447" alt="image" src="https://github.com/raycast/extensions/assets/27580836/6d9e2ff2-3070-4c55-87e1-7ff564662aff">

**Comment by hossammourad** [comment]
It's working fine now. It could have been a network glitch or something. Thanks for verifying.
