### ISSUE TITLE
[Music]: 

### ISSUE THREAD

**Issue by Sheldontao** [raycast/extensions#8810]
### Extension

https://raycast.com/fedevitaledev/music

### Description

Command failed with exit code 1: osascript -e tell application "Music" to set favorited of current track to true 
28:66: execution error: Music got an error: A descriptor type mismatch occurred. (-10001)

### Steps To Reproduce

1.mac monterey 12.7
2. command "favorite track" occur error

**Comment by rawnly** [comment]
#8872

**Comment by LEUNGHOTIN** [comment]
> #8872

#8782 It doesn’t seem to take effect. My macOS version is 12.7 and Raycast version is 1.59.0. When executing ‘Favorite and Add to Library’, the following error will still be reported.
```
Error: Command failed with exit code 1: osascript -e tell application "Music" to set favorited of current track to true 
28:66: execution error: “Music”遇到一个错误：描述符类型不匹配。 (-10001)
    at Lm (/Users/leung/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/favorite-and-add-to-library.js:5:59)
    at /Users/leung/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/favorite-and-add-to-library.js:5:10465
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async lu (/Users/leung/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/favorite-and-add-to-library.js:5:40097)
```

**Comment by rawnly** [comment]
yes because the favore command has been introduced in 14.0, the PR provides a fallback for older macos versions 😃

i'm looking to fix the pr checks by the end of the day

**Comment by rawnly** [comment]
@raycastbot close this issue
