### ISSUE TITLE
[Anybox] Provide Grid view of Search Links

### ISSUE THREAD

**Issue by realCrush** [raycast/extensions#8813]
### Extension

https://www.raycast.com/anybox/anybox

### Description

Thanks to Anybox's excellent screenshot capture and web cover acquisition capabilities, using the [Grid view](https://developers.raycast.com/api-reference/user-interface/grid) provided by Raycast is a more intuitive choice that allows users to quickly find the desired content.

### Who will benefit from this feature?

Most Anybox users, since humans are more sensitive to images than text.

**Comment by francisfeng** [comment]
@raycastbot close this issue

Will be supported in the latest Raycast extension. The latest Mac version (2.1.2) is required.
