### ISSUE TITLE
Drafts: Create Drafts from selection & option to empty clipboard after action

### ISSUE THREAD

**Issue by dudido** [raycast/extensions#8815]
### Extension

https://www.raycast.com/FlohGro/drafts

### Description

The action 'Create Drafts from Clipboard' action should create a draft based on the current selection by default, if the clipboard is empty. Alternatively, this could become a separate action 'Create Drafts from Selection' or similar. Also, there should be an option to automatically empty the clipboard after running the action.

### Who will benefit from this feature?

It will save any user time by omitting the keystroke to copy, if the text is not already on the clipboard but needs to be selected first.

### Anything else?

Thanks!

**Comment by FlohGro-dev** [comment]
I'm not sure about emptying the clipboard - I don't want to delete something a user might also need somewhere else.

For the rest of it I'll have a look ;)

**Comment by FlohGro-dev** [comment]
didn't had time to look at this, sorry.

**Comment by FlohGro-dev** [comment]
Bump

**Comment by FlohGro-dev** [comment]
sorry you had to wait that long @dudido - I finally managed to work on this again and it was far easier than I thought. Sorry for the delay..

I added a new command `Create Draft From Selection` to create a new draft from the selected text which I really enjoy using. Thanks for the suggestion! I decided against emptying the clipboard in the other command.

Hope it gets reviewed and published soon! #11217

**Comment by FlohGro-dev** [comment]
@raycastbot close this issue

**Comment by dudido** [comment]
Sorry I missed this. It's beautiful, thank you!

**Comment by FlohGro-dev** [comment]
@dudido youre very Welcome!

**Comment by FlohGro-dev** [comment]
Hi @dudido please open a new feature request since this issue is closed.

I understand your idea, but I'll have to look into this a bit deeper since right now I'm just using url schemes which require the app to launch in the foreground. It might be possible with other solutions though
