### ISSUE TITLE
[ClickUp - Tasks Explorer] ...

### ISSUE THREAD

**Issue by Ricardo-Abude** [raycast/extensions#8826]
### Extension

https://www.raycast.com/aparandeh/manage-clickup-tasks

### Description

Hello. I am trying to use the Clickup extension. Got the API from Clickup and the task explorer is working fine. However, the quick capture command is not working, and I keep getting an error message stating "Something went wrong, please try later. Any thoughts how to solve this? thanks
---

App Version: 1.59.0

System Version: 13.4.1

### Steps To Reproduce

1. open quick capture
2. fill in a task
3. submit

### Current Behaviour

error - Something went wrong, please try later.

### Expected Behaviour

create a new task at clickup

**Comment by Ali-Parandeh** [comment]
It might be that the extension API has changed slightly. Let me fix some bugs this weekend.

**Comment by Ricardo-Abude** [comment]
Hi Ali,

Thanks for the reply. I managed to get all the correct ID's - Team, Space
and list - and now it's working properly.

As a suggestion it would be nice if the assignee also was part of the
extension dialog.

Thanks again
Ricardo

Sent via Superhuman ***@***.***>
