### ISSUE TITLE
[Tana] ...

### ISSUE THREAD

**Issue by palseb** [raycast/extensions#8831]
### Extension

https://www.raycast.com/cheslip/tana

### Description

I installed the API key for Raycast
When I trigger the 'Tana Quickadd' I receive this  error message **_Requet failed with status code 400_**

### Steps To Reproduce

Request failed with status code 400

**Comment by birdmanmandbir** [comment]
The extension is outdated, tana API has a addNodeV2 endpoint
I'm working on fix it currently, @cheslip  do u have a opensource project, or maybe i should create a new repo for this?

**Comment by birdmanmandbir** [comment]
Duplicate Issue: https://github.com/raycast/extensions/issues/8580

**Comment by birdmanmandbir** [comment]
I think the result of this quick add command should add to `Today` node, but it add to `Library` by default.

**Comment by jesper-bylund** [comment]
Same issue.

Quick add should add to `Today` node or `Inbox` like the capture app.
