### ISSUE TITLE
[Toggle Audio Input (microphone)] Show menubar icon only if muted

### ISSUE THREAD

**Issue by guspimentel** [raycast/extensions#8832]
### Extension

https://www.raycast.com/Quentin23Soleil/mute-microphone

### Description

Would it be nice if we could set the menu icon to be visible only if the mic is muted, otherwise it'd not be shown

### Who will benefit from this feature?

User with clustered menu bar or want a clean asthetic

**Comment by iamyeizi** [comment]
@raycastbot reopen this issue

**Comment by iamyeizi** [comment]
@guspimentel Done!
@raycastbot close this issue
