### ISSUE TITLE
[Unsplash] Invalid redirect for signin

### ISSUE THREAD

**Issue by shawnyeager** [raycast/extensions#8837]
### Extension

https://www.raycast.com/eggsy/unsplash

### Description

I've added my API keys, then was prompted to sign in. Repeated attempts produce the following error from Unsplash:

![CleanShot 2023-10-17 at 12 14 06@2x](https://github.com/raycast/extensions/assets/980297/bbbe487e-08e8-41b5-b99b-92ae35449080)

### Steps To Reproduce

1. Install extension
2. Execute any extension command
3. Populate Unsplash API keys
4. Execute any extension command
5. Click through sign-in button/link

### Current Behaviour

Produces an error as seen in the above screenshot.

### Expected Behaviour

Successful launch of Unsplash for sign-in.

**Comment by eggsy** [comment]
Have you done this step?

![image](https://github.com/raycast/extensions/assets/13917975/d6b9fcfd-4ac2-4570-b809-1e2d5d4db94b)

**Comment by shawnyeager** [comment]
I hadn't. Thanks. I wouldn't have gone looking in the readme, so maybe this could be presented as an alert in the Raycast extension UI?

**Comment by eggsy** [comment]
> I hadn't. Thanks. I wouldn't have gone looking in the readme, so maybe this could be presented as an alert in the Raycast extension UI?

I don't think Raycast API allows us to edit the OAuth pages/steps, so you must read the information first.

**Comment by shawnyeager** [comment]
Thanks. Feedback for @snykraycast would be to enable these special instructions somehow. 🙏🏼
