### ISSUE TITLE
[LastPass Credentials Search] Shift Enter copies to clipboard instead of pasting

### ISSUE THREAD

**Issue by brunocbreis** [raycast/extensions#8841]
### Extension

https://www.raycast.com/alex-popov-tech/lastpass

### Description

In the action panel, it says pressing shift enter should paste the username to the current app. It actually copies it to the clipboard.

### Steps To Reproduce

Open Search Vault Command
Select an item
Press shift enter or select Paste username from the action panel

### Current Behaviour

Copies to clipboard

### Expected Behaviour

Paste to app

**Comment by alex-popov-tech** [comment]
hey @brunocbreis , thanks for opening issue.
You are right, i will fix this now.

**Comment by alex-popov-tech** [comment]
@brunocbreis sorry for delay, here is PR ^

**Comment by alex-popov-tech** [comment]
@brunocbreis merged, mind re-checking and closing if everything looks good?

**Comment by brunocbreis** [comment]
Looks good to me! Just submitted another issue I've been dealing with, though 😅
