### ISSUE TITLE
[Google Translate] Translate to multiple languages at the same time

### ISSUE THREAD

**Issue by rasitayaz** [raycast/extensions#8844]
### Extension

https://www.raycast.com/gebeto/translate

### Description

Currently, using the 'Translate' command, we can add multiple language sets and switch between them. But even when we want to translate interchangeably between two languages (like A to B, and then B to A), we need to change the language set.

With this new feature, user will not need to constantly change language sets. Let me explain what I have in my mind with some example images I made:
<img width="862" alt="example" src="https://github.com/raycast/extensions/assets/45076094/04a264f7-6299-4f25-bd59-c972017a25b6">
<img width="862" alt="example2" src="https://github.com/raycast/extensions/assets/45076094/d9e79278-d524-4063-9be4-d9a0f1e6f019">

### How this feature should work in my opinion;

- Command should ask the user for two main languages for the first run (like the current 'Translate' command)
- User should be able to add and delete languages in the list (min two languages should be mandatory)
- Command should automatically hide the detected language in the result list (since it will display the input text as is)

We can either change the existing command with this, or maybe add another command for this feature like "Translate Multiple Languages". What do you think?

### Who will benefit from this feature?

Users who are regularly making translations between multiple languages, or making translations interchangeably between two languages.

**Comment by gaojunran** [comment]
if you strongly need the feature, you can try [antfu's raycast extension](https://github.com/antfu/raycast-multi-translate), which meets your requirement. However, as he does not like the management way of extensions of raycast, you need to follow the steps in his README and install it locally.

**Comment by gebeto** [comment]
I'm going to add ability to add multiple target languages to the translation sets

**Comment by gebeto** [comment]
Hey @rasitayaz , I've just added this ability here, now you will be able to create language set with as much target languages as you want:

https://github.com/raycast/extensions/pull/16240
