### ISSUE TITLE
[Music] Show lyrics in the menu bar (or a floating window)

### ISSUE THREAD

**Issue by GP2P** [raycast/extensions#8850]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

A Raycast menu bar item for showing Apple Music lyrics would be perfect. There already exists a lot of extensions with menu bar display, especially the calendar functionality.

### Who will benefit from this feature?

People wanting to have a easy way of showing the currently playing lyrics where they can see it without needing to download and give access to paid/shady-looking 3rd party apps.

### Anything else?

Look up the app `Looking Glass`

**Comment by rawnly** [comment]
Nice idea, unfortunately I don't think this is possible with the current state of the raycast api :/

**Comment by GP2P** [comment]
As I see here, the API supports changing title of menu bar items in real-time:
https://developers.raycast.com/api-reference/menu-bar-commands

Additionally, you can add [background refresh](https://developers.raycast.com/information/lifecycle/background-refresh) to it!

Could you please investigate how the official calendar integration behaves? This would be a killer feature! Thanks!

**Comment by GP2P** [comment]
I am looking at the API and my initial thought is that this is doable with some workarounds. Could we discuss why you think it'd be impossible? @rawnly 

As I see here, the API supports changing title of menu bar items:
https://developers.raycast.com/api-reference/menu-bar-commands

Additionally, you can add [background refresh](https://developers.raycast.com/information/lifecycle/background-refresh) to it - maybe we'd need to dynamically set the refresh time to real fast (at runtime when a song was detected using slow refresh times), or, just refresh real fast when a user opens this command to read the current lyrics, and turn off self when detected that no song is playing.

Anyways, glad to talk, think this would be a killer feature! If you're okay with it, I can try to implement this with your help. Thanks Federico!

**Comment by GP2P** [comment]
After building a demo myself I realized background refresh only allows 10s as min refresh value, which means we can't "abuse" this. Any way for the function to self-update its title while active?

**Comment by GP2P** [comment]
Using these I was able to get it to self-update (only) DURING being clicked on (in focus), guess that's not too useful, hoping to see any guidance - this is my first time with modern frontend stuff like react or .tsx, I usually write systems software.

```tsx
import { MenuBarExtra } from "@raycast/api";
import { useState, useEffect } from "react";

export default function Command() {
    const [title, setTitle] = useState(getCurrentLyrics());

    useEffect(() => {
        const intervalId = setInterval(() => {
            setTitle(getCurrentLyrics());
        }, 100);

        return () => clearInterval(intervalId);
    }, []);

    return (
        <MenuBarExtra title={title}>
            <MenuBarExtra.Item title="This has to exist" />
        </MenuBarExtra>
    );
}

function getCurrentLyrics() {
    return Math.floor(Date.now() / 100).toString();
}
```

**Comment by rawnly** [comment]
i said it was impossibile because the background refresh is too limited, and there's now way (at least for what i know) to refresh it manually.. 🥲

btw i have some time this weekend, i can try something too! 

where are you getting the lyrics?

**Comment by rawnly** [comment]
anyway, i love the idea, feel free to implement it in the actual extension or just experiment with it, i'm happy to help if needed!
