### ISSUE TITLE
[Pomodoro] Pomodoro Menu bar doesn't update in realtime

### ISSUE THREAD

**Issue by oluwatbi** [raycast/extensions#8852]
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

The menu bar icon doesn't update in real time

### Steps To Reproduce

1. opening raycast (⌘ + Space)
2. Search for the Pomodoro extension
3. Activate the command with Menu Bar

### Current Behaviour

Shows static Icon

### Expected Behaviour

Time(sec) count shouldn't be static

**Comment by oluwatbi** [comment]
I don't know if this is supposed to have the Request Feature label or the bug label

**Comment by bekicot** [comment]
Looks related to #8699

**Comment by pernielsentikaer** [comment]
That's not possible at the moment, 10 seconds is the lowest it can update at the moment
