### ISSUE TITLE
[Vivaldi] `Search Tabs` stuck in perpetual loading state.

### ISSUE THREAD

**Issue by crisneda** [raycast/extensions#8854]
### Extension

https://www.raycast.com/crisboarna/vivaldi

### Description

The extension does not display the list of tabs. The rest of the commands seem to work normally.

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/16434211/e2161638-7a22-4b84-a338-4916ac3cee52">

### Steps To Reproduce

1. Run command 'Search Tabs'

**Comment by crisneda** [comment]
Unfortunately, the problem still persists.

**Comment by sxn** [comment]
oops, I closed this issue along with a few other issues that _were_ opened as a result of an issue with Raycast. This seems like an extension issue, though. Sorry about that. 😅
