### ISSUE TITLE
[Google Chrome Profiles] API file appears to be corrupted

### ISSUE THREAD

**Issue by frouo** [raycast/extensions#8859]
### Extension

https://www.raycast.com/frouo/google-chrome-profiles

#### Error:
```
The API file appears to be corrupted. You may need to reinstall Raycast.


```

Raycast version : 1.60

### Steps To Reproduce

1. Download the `Google Chrome Profiles` extension
2. Open `Google Chrome Profiles` command

### Current Behaviour

![image](https://github.com/raycast/extensions/assets/2499356/203d7391-069c-4394-8da7-16f32c0143f4)

### Expected Behaviour

The extension should list my Google Chrome profiles.

**Comment by sxn** [comment]
hey, thanks for the report. This is an issue with Raycast, not the extension. We're currently addressing it and will deploy a hotfix shortly. Sorry for the hassle 🙏
