### ISSUE TITLE
[Google Search] ...

### ISSUE THREAD

**Issue by Gusaracha** [raycast/extensions#8864]
### Extension

https://www.raycast.com/mblode/google-search

#### Error:
```
The API file appears to be corrupted. You may need to reinstall Raycast.


```

### Steps To Reproduce

1. It can not be ruined the extension

**Comment by erics118** [comment]
This is a Raycast issue. Update Raycast to version `1.60.1` with the `Check For Updates` command. [Slack link](https://raycastcommunity.slack.com/archives/C01A0R0NXGQ/p1697650082289099?thread_ts=1697638624.400889&cid=C01A0R0NXGQ) for reference.
