### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by Gusaracha** [raycast/extensions#8865]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Reason: The API file appears to be corrupted. You may need to reinstall Raycast.
Domain: commands
Time: 18:40:33.369

### Steps To Reproduce

Reason: The API file appears to be corrupted. You may need to reinstall Raycast.
Domain: commands
Time: 18:40:33.369

**Comment by erics118** [comment]
This is a Raycast issue. Update Raycast to version `1.60.1` with the `Check For Updates` command. [Slack link](https://raycastcommunity.slack.com/archives/C01A0R0NXGQ/p1697650082289099?thread_ts=1697638624.400889&cid=C01A0R0NXGQ) for reference.
