### ISSUE TITLE
Remove the blank page opening on launching profile[Google Chrome Profiles] ...

### ISSUE THREAD

**Issue by lucifermickelson** [raycast/extensions#8869]
### Extension

https://www.raycast.com/frouo/google-chrome-profiles

### Description

On

**Comment by frouo** [comment]
Hello @lucifermickelson , you can set the URL for any new tabs in the extension configuration, see:

<img width="1000" alt="image" src="https://github.com/raycast/extensions/assets/2499356/8da2cd21-da30-4e9b-9a4e-8f786df3efa3">

Unfortunately I didn't find the way to open google chrome on a new tab (as if you've clicked ➕ on chrome).
