### ISSUE TITLE
[Google Search] Always have current search at top

### ISSUE THREAD

**Issue by eIiot** [raycast/extensions#887]
# Extension – [Google Search](https://github.com/raycast/extensions/tree/60eb31ef24a707e9f658cbe02a2265e12c83b988/extensions/google-search/)
Author: @mblode

**Describe the feature and the current behavior/state.**
Currently, if I want to search for something, I have to wait 1-2 seconds for the autofill to populate my query. It would be great if hitting enter without any navigation always brought me to that exact search page, with suggestions as options.

**Who will benefit with this feature?**
Users who like to search for stuff quickly using the Google Search extension.

**Comment by mblode** [comment]
Great idea 👍 So the first result is always an exact match search. Are you experienced with coding and would you be able to work on the feature?

**Comment by eIiot** [comment]
I could probably figure something out, It wouldn't be that hard to just return the current text.

I'll try something out when I have the time, and submit a PR
