### ISSUE TITLE
[Microsoft Teams Meeting] The new Microsoft teams app is not supported

### ISSUE THREAD

**Issue by Richigeht** [raycast/extensions#8870]
### Extension

https://www.raycast.com/sven/microsoft-teams-calling

### Description

Hello,
I updated to the "new" Microsoft teams 2.0 app and the shortcts don't work no more. 

It's not only you - also OBS doesn'T work with it anymore or Teams doesn't with both of you. But it would be great to get back my beloved shortcuts :-) thanks!

### Steps To Reproduce

1. Update to the NEW teams 2.0 app.
2. Be happy about the quicker loading times.
3. Notice in your meetings, you cannot control the mute button anymore....
4. Wonder about less successful meetings :( 
5. Make a bug at github.... oh wait! ;) 

### Current Behaviour

Error message within Teams that it cannot control the app. 

### Expected Behaviour

Mute/unmute to work

**Comment by svenwiegand** [comment]
Hi @Richigeht, I can confirm that the new Teams 2.0 client currently doesn't provide the API used by my extension. 

I'm using an undocumented API here, which is the same as used by the Microsoft Teams plugin for the Streamdeck (see [Microsoft's blog post](https://techcommunity.microsoft.com/t5/microsoft-teams-blog/delivering-new-webinar-experiences-with-microsoft-teams/ba-p/3725145)). On the [plug-in's page](https://marketplace.elgato.com/product/microsoft-teams-da5e2bbc-197c-4afe-8a85-a9941bf52697) they say, the latest version of the plugin is working with the new Microsoft Teams, but for me, it does not. 

As this API isn't documented anywhere, at the moment I don't see a chance to get this fixed. Any hints are welcome.

**Comment by raffiloch** [comment]
@svenwiegand - First, thank you for the excellent extension! It is incredibly useful and greatly simplifies things.

I have come across various Reddit posts mentioning that the Streamdeck plugin for Teams now works with the New Teams. However, the API key registration flow has changed slightly. The New Teams now supports third-party app APIs, but there is no longer an option to generate a new API key. According to the Microsoft support page, once the feature is enabled, you simply need to activate the plugin on the third party device. A confirmation window will then appear to connect the plugin with Teams. I'm really curious if something similar can be achieved with the Raycast extension. :-)

In any case, thank you for your outstanding work!

Links:
- https://support.microsoft.com/en-us/office/connect-to-third-party-devices-in-microsoft-teams-aabca9f2-47bb-407f-9f9b-81a104a883d6?storagetype=live
- https://www.reddit.com/r/elgato/comments/11yohh1/teams_plugin_not_working/

**Comment by svenwiegand** [comment]
@raffiloch Thanks for the links. That looks promising, though MS still doesn‘t seem to provide an API documentation and I will have guess again and reengineer the Stream Deck plugin like back in spring. I hope I‘ll find some time in December to fix this.

**Comment by Richigeht** [comment]
HiI am using in the mean time "micdrop" which isn't limited to Teams and can be used as well with shortcuts. I prefer the raycast method but for the time being microp works as drop in replacement quite well. Mit elektrischen GrüßenRicardo KissingerSent from my iPhoneAm 19.11.2023 um 07:50 schrieb Sven Wiegand ***@***.***>:﻿
@raffiloch Thanks for the links. That looks promising, though MS still doesn‘t seem to provide an API documentation and I will have guess again and reengineer the Stream Deck plugin like back in spring. I hope I‘ll find some time in December to fix this.

**Comment by mguilherme** [comment]
in the new MS Teams version there's no token to copy:
<img width="1139" alt="image" src="https://github.com/raycast/extensions/assets/699510/0e309dda-9c7c-4289-ae31-04745a7f983f">

**Comment by raffiloch** [comment]
@svenwiegand you are the best! Just stumbled upon that there is now an API registration option for the New Teams client. Your extension works flawlessly and is really great. Thanks a lot for this! 🙏 💪 🎉

**Comment by svenwiegand** [comment]
Thanks @raffiloch, but it was @philippreissing who has implemented the support for the new Teams. I‘ve just did the review. Nevertheless we now have it 🎉

**Comment by svenwiegand** [comment]
@raycastbot close this issue

**Comment by flokosiol** [comment]
Thanks a lot @philippreissing for this contribution! I really missed this extension after switching to the new Teams app. And of course thanks @svenwiegand for the great work, too!

**Comment by tbsmn** [comment]
Just wan't to say thank you too.
This is so helpfull for me every single day!
You guys rock @philippreissing and @svenwiegand!

**Comment by raffiloch** [comment]
> Thanks @raffiloch, but it was @philippreissing who has implemented the support for the new Teams. I‘ve just did the review. Nevertheless we now have it 🎉

Kudos to @philippreissing as well! 💪

**Comment by juanra** [comment]
Hi guys!

Thanks @svenwiegand and @philippreissing for all the work done with this.
I don't want to overshadow the celebration in the thread, but in my case I am having an issue: every time I activate the "mute mic", the popup that says "New connection request" is shown in MS Teams, every time I execute the command...

Has it happened to you?
Any idea how to solve it and not have it ask me every time I run the command?

**Comment by Nenuial** [comment]
I have had the same issue at first. After a restart of Teams everything was fine.

I have however an issue with the indication "Muted" and "Unmuted" which is often the exact opposite of the microphone status in Teams… Not a big issue, but slightly annoying.

**Comment by svenwiegand** [comment]
@juanra: Did a restart of Teams solve the issue for you, like stated by @Nenuial ? I definitely haven't seen this issue on my own.

@Nenuial: Thanks for the report. You are right: I can also see the wrong notification overlays. When showing the meeting control view, the state of the microphone is shown correctly. I'm quite busy currently, but might look into this issue someday.

**Comment by juanra** [comment]
Thanks for asking @svenwiegand 

This is what I have tried so far, unfortunately without success:

- I restarted the app
- I restarted the machine
- I uninstalled the app with AppCleaner and installed again

**Comment by svenwiegand** [comment]
Hm, that's really strange @juanra. You've said you already reinstalled teams; otherwise I would suggest removing the consent for Raycast in Microsoft Teams (you first have to block it and then in the block list you can remove it).

Unfortunately, Raycast doesn't support any logging for extensions outside a development system, so that I currently don't really have an idea how to track down this issue.

**Comment by Nenuial** [comment]
> @Nenuial: Thanks for the report. You are right: I can also see the wrong notification overlays. When showing the meeting control view, the state of the microphone is shown correctly. I'm quite busy currently, but might look into this issue someday.

Thanks!
