### ISSUE TITLE
The API file appears to be corrupted. You may need to reinstall Raycast.

### ISSUE THREAD

**Issue by eliUtopia** [raycast/extensions#8876]
### Extension

https://www.raycast.com/thomas/visual-studio-code

#### Error:
```
The API file appears to be corrupted. You may need to reinstall Raycast.


```

### Steps To Reproduce

The API file appears to be corrupted. You may need to reinstall Raycast.

### Current Behaviour

The API file appears to be corrupted. You may need to reinstall Raycast.

### Expected Behaviour

The API file appears to be corrupted. You may need to reinstall Raycast.

**Comment by pernielsentikaer** [comment]
What version of Raycast and macOS are you using?

**Comment by macbookandrew** [comment]
@eliUtopia looks like a problem with Raycast itself: https://github.com/raycast/extensions/issues/8856#issuecomment-1768976612

1.60.1 [should resolve it](https://github.com/raycast/extensions/issues/8856#issuecomment-1769027472)
