### ISSUE TITLE
i wish the fading of the window wouldnt appear with cleanshot extension [CleanShot X] ...

### ISSUE THREAD

**Issue by paranjay245** [raycast/extensions#8877]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

i wish the fading of the window wouldnt appear with cleanshot extension[CleanShot X] ...
when i take screenshot with the extension it fades the background which is annoying :( 

### Steps To Reproduce

when you take screenshot with any cleanshot x tool it just fades the background : (

**Comment by erics118** [comment]
can you provide some screenshots or recordings? I'm not quite sure what you mean by "fading"

**Comment by paranjay245** [comment]
this is cleanshot screenshot & it fades the active window while screenshoting with raycast command or shortcut and also after screenshot i need to press the window to reactivate the same 
![CleanShot 2023-10-20 at 08 40 50@2x](https://github.com/raycast/extensions/assets/120307516/e94c92a0-e743-436e-84f5-20af62341705)


<img width="1680" alt="Screenshot 2023-10-20 at 08 40 23" src="https://github.com/raycast/extensions/assets/120307516/3f198d98-307b-4bd9-8413-0d7931f7c928">

![CleanShot 2023-10-20 at 08 51 53](https://github.com/raycast/extensions/assets/120307516/9dd9a42f-9dca-4d70-93e1-bb4374a7f8c9)


sorry for lack of clarity and thank you soo much for the extension!

**Comment by erics118** [comment]
I think this is either a bug with CleanShot X, or a inherent unfixable feature with how the URL scheme API works.

If you were to run:
```sh
sleep 3; open 'cleanshot://capture-area'
```
in Terminal, then quickly switch the frontmost app to something else, the frontmost app also gets "faded", or unfocused.

So, I don't think this is an issue that the Raycast extension can easily resolve

**Comment by Aayush9029** [comment]
@raycastbot close this issue
