### ISSUE TITLE
[ChatGPT] App screen flickers upon getting long answers - noticeable more in Full-text input

### ISSUE THREAD

**Issue by senguttuvang** [raycast/extensions#8879]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Flashing Screen Issue

[Flashing Screen Issue](https://www.loom.com/share/24b3903a05444a96aa308e365345b176)

### Steps To Reproduce

Try to get the response when the response is already being loaded

### Current Behaviour

Flashes the screen - attempts to switch between conversations

### Expected Behaviour

Should focus and stay on the currently focused conversation without flashing

**Comment by wincent** [comment]
I also see this even after the first response has been received. As soon as I ask a follow-up question, I get a flickering. One thing that seems to help to repro: asking longer questions (ie. with `⌘T`) with longer answers.

I can also see the flickering if I open up the history view and then press and hold the up or down cursor keys for about one second.
