### ISSUE TITLE
[LastPass Credentials Search] Command fails to login

### ISSUE THREAD

**Issue by brunocbreis** [raycast/extensions#8882]
### Extension

https://www.raycast.com/alex-popov-tech/lastpass

### Description

![Arc-ss-000103@2x](https://github.com/raycast/extensions/assets/85531625/13973176-f3b2-402d-bf89-73db4daa2a5c)
Command always fails when trying to open it before manually logging in in the Terminal. I believe it's passing a string of asterisks instead of the actual password to the CLI command? But I might be interpreting the message wrong.

Point is, I have to always open the Terminal, manually login to lpass-cli, and only then I can use the command. Password is set correctly in settings.

Might this be a problem with the actual CLI tool logging me out too often? If that's the case, maybe the error message could suggest a setting that overrides that or warn me about how often I should login manually again.

### Steps To Reproduce

1. Open command without having logged in manually.

### Current Behaviour

Fails to login, displays error message as if the password is wrong.

### Expected Behaviour

Login successfully and load passwords.

**Comment by brunocbreis** [comment]
thanks for clarifying, i imagined the asterisks might be a privacy thing. i'll do what you suggested and report back

**Comment by brunocbreis** [comment]
![Terminal-ss-000105@2x](https://github.com/raycast/extensions/assets/85531625/094666ef-6437-43b7-8349-f7864979921f)
Tried uninstalling both the extension and the cli app, and still getting the same error. Now I think it might have to do with the authenticator setting that I have. When I login manually on the terminal, extension still ends up working afterwards.

But before setting up this authenticator thing in my lastpass account, I would still have that issue and had to login manually basically every day to use the extension

**Comment by alex-popov-tech** [comment]
@brunocbreis this extension does not support 2fa, only single password :( can you please check will it work with password only? because for me after re-installation it works fine 🤷🏻‍♂️

**Comment by Ethanwang17** [comment]
I am also having the same exact issue, where I can login manually through terminal but it only lasts so long before it give me the error again and I have to re-login on terminal. I have tried uninstalling the extension and lpass cli and it did not fix my problem.

**Comment by alex-popov-tech** [comment]
@Ethanwang17 can you please run command from error manually in terminal? `zsh -c -l ...` <- this one

tbo i have little idea on how to debug that :(

**Comment by Ethanwang17** [comment]
@alex-popov-tech 
When I type the command in it says
zsh:1: command not found: ...
So still not working but if you don't know how to fix it, it's all good.

**Comment by alex-popov-tech** [comment]
@Ethanwang17 which version of OS do you have? and can you please put all output, the one in `...` ? you kinda missed most interesting part :)

**Comment by Ethanwang17** [comment]
@alex-popov-tech 
I am on version MacOS Sonoma 14.0 (23A344)

<img width="682" alt="SCR-20231030-jrkg" src="https://github.com/raycast/extensions/assets/91906326/a0c3c33b-7b9e-435b-b3e0-609befc62a01">

**Comment by alex-popov-tech** [comment]
@Ethanwang17 ah i see. could you please paste that whole command into terminal from screenshot in first message?
like put this whole line with password and others ```zsh -c -l 'echo 'YOUR_PASSWORD_HERE' | LPASS_DISABLE_PINENTRY=1 lpass login'```

**Comment by Ethanwang17** [comment]
<img width="697" alt="SCR-20231030-tnlh" src="https://github.com/raycast/extensions/assets/91906326/35dfc0e8-658e-4b85-9a1e-52f50892f820">

it works when I run the command but when I go to use the extension a few hours later it will get signed out and I have to re-sign in with the command

**Comment by alex-popov-tech** [comment]
@Ethanwang17 so after you run this command extension works, but then at some point it stops working again? 🤯

**Comment by Ethanwang17** [comment]
yes, that is correct

**Comment by brunocbreis** [comment]
can confirm that the command works for me as well, and makes the extension work. but right now it seems like the same behavior as before when i would login manually. my expectation is that tomorrow (probably earlier), i will be automatically logged out.

i have disabled 2FA as well, as you mentioned it's not compatible with the extension

**Comment by alex-popov-tech** [comment]
can you guys please try `which lpass`  in terminal? maybe there are multiple installations...

**Comment by brunocbreis** [comment]
```
which -a lpass
/opt/homebrew/bin/lpass
```

i only get the one

**Comment by brunocbreis** [comment]
however, i just tested the extension and, 2 days after my last comment, it seems to be working 😄
so maybe that manual command did work better than the one i was trying before

**Comment by alex-popov-tech** [comment]
🤯
