### ISSUE TITLE
[Browser Bookmarks] Failed to browse book marks

### ISSUE THREAD

**Issue by ArickNan** [raycast/extensions#8885]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:405:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

### Steps To Reproduce

1. type bm to get bookmark list

**Comment by thomaslombart** [comment]
Thanks for bringing this up. It appears that this is a duplicate of issue #6810, so I'll mark it as such.
