### ISSUE TITLE
[1Password] Match shortcuts with 1Password app

### ISSUE THREAD

**Issue by juhamust** [raycast/extensions#8886]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

My Password uses different shortcuts to copy the username and the password, compared to the official app. This is a bit confusing and unnecessary.

![image](https://github.com/raycast/extensions/assets/781002/709e030b-e663-4f2b-b845-31db3743b9da)

![image](https://github.com/raycast/extensions/assets/781002/23d049d5-2e1b-44a4-80af-ffa1372a69d3)

### Who will benefit from this feature?

Everyone using both 1Password app and My Passwords extension. Easier to migrate from one to another 👍

**Comment by pernielsentikaer** [comment]
What do you think here @khasbilegt
