### ISSUE TITLE
[Git Repos] Search does not work anymore since last update

### ISSUE THREAD

**Issue by gufertum** [raycast/extensions#8887]
### Extension

https://raycast.com/moored/git-repos

#### Error:
```
Error: Invalid binary plist. Expected 'bplist' at offset 0.
    at a1.parseBuffer (/Users/tms/.config/raycast/extensions/e0a4c081-81fa-44ca-a689-08e4920ee819/list.js:30:23308)
    at qa (/Users/tms/.config/raycast/extensions/e0a4c081-81fa-44ca-a689-08e4920ee819/list.js:39:2630)
    at async _2 (/Users/tms/.config/raycast/extensions/e0a4c081-81fa-44ca-a689-08e4920ee819/list.js:46:3981)
    at async u8 (/Users/tms/.config/raycast/extensions/e0a4c081-81fa-44ca-a689-08e4920ee819/list.js:49:396)
    at async Object.gitRepos [as current] (/Users/tms/.config/raycast/extensions/e0a4c081-81fa-44ca-a689-08e4920ee819/list.js:46:4648)
```

### Steps To Reproduce

1. select 'list git repos'
2. start search ... error appears

does not matter if i search for names or paths (new config item)

**Comment by nitishpdmn** [comment]
What version of Raycast and macOS are you on?

I added the new option for searching by path, so I guess something about the plist/preference file didn't like having its format/contents changed? This doesn't happen on my machine though, and I've tried deleting and reinstalling the extension. I only started using Raycast about a week ago though, so it's possible I don't have any historical preferences to break. Fwiw I'm on Raycast 1.60.1 and macOS Sonoma 14.0.

@moored did my update break your install? Fwiw I'm on Raycast 1.60.1 and macOS Sonoma 14.0. A plist error seems like it should be way lower level than anything in the extension itself though.

**Comment by nitishpdmn** [comment]
It seems like the error is coming from the `default-browser` package when it tries to load the `defaultBrowserId`.

A workaround I'm seeing online is to convert the plist file in question to binary format with 
`plutil -convert binary1 Info.plist`. The plist in question here is `~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist`. Unclear why it would suddenly break.

A potential fix would be to change the way the browser check is being done to check if the app is a browser instead of checking against the default browser bundleId. Maybe using https://www.npmjs.com/package/get-installed-browsers ?

**Comment by nitishpdmn** [comment]
@gufertum I converted my plist to xml and reproduced the exact error you had down to the line/character number, so I think I have a fix for the issue.

Steps to reproduce:
```console
$ cd ~/Library/Preferences/com.apple.LaunchServices
$ head -c 6 com.apple.launchservices.secure.plist
bplist%
$ plutil -convert xml1 com.apple.launchservices.secure.plist
$ head -c 6 com.apple.launchservices.secure.plist
<?xml %
```

Until the change in the PR above is merged, you should be able to get the error to go away by either:
1. Running `plutil -convert binary1 ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist`
2. Going to System Preferences and changing your default browser, then changing it back. That seems to reset it to a binary plist for me

**Comment by gufertum** [comment]
@nitishpdmn Thank you for your effort. Changing the default browser worked. Looking forward for the change.
Keep it up 👍
