### ISSUE TITLE
[Apple Reminders Beta] Group by Due Date don't work

### ISSUE THREAD

**Issue by teziovsky** [raycast/extensions#8889]
### Extension

https://www.raycast.com/raycast/reminders

### Description

The `My Reminders` extension has a feature that can group the reminders by date. When the group by is set to `Due Date` it doesn't group reminders properly. Any other option of `Group By` works properly.

### Steps To Reproduce

- Some information:
  - MacOS Sonoma 14.0
  - Raycast v1.60.1
  - Poland (PL)
- Steps:
  - Open `My Reminders` extension
  - Set `Group By` to `Due Date`

### Current Behaviour

`Group By` set on `Due Date` groups all the reminders in the `Other` group and that's all.

### Expected Behaviour

`Group By` set on `Due Date` should group all the reminders properly to `Overdue`, `Today`, `Tomorrow`, `Upcoming`, and `Other`.

**Comment by teziovsky** [comment]
I tried to find an issue by myself, but have that error in the terminal, when `npm run dev`:
```bash
error -  compiling swift package
build failed (src/api.ts:1:22 import reminders from "swift:../swift/reminders";): failed to parse the swift package: exit status 1
```

**Comment by thomaslombart** [comment]
Could you post some screenshots of what you're getting and what you're expecting?

**Comment by teziovsky** [comment]
Lol, sorry! I had reminders whose due date was later than the current week, that's why all reminders are in group `Other` 😅
Everything is working as expected, when I tested it with different dates like `yesterday`, `today`, `tomorrow` etc 😅
Sorry for the misunderstanding!

**Comment by thomaslombart** [comment]
Maybe you'd expect them to be grouped by the actual due date instead of in `Others`? I was wondering if I shouldn't do that. The `Others` behavior is consistent with the native behavior but it may be confusing.

**Comment by thomaslombart** [comment]
Done: https://github.com/raycast/extensions/commit/542ea680c19009820ef9e3cb4615949126a5a5aa
