### ISSUE TITLE
[CleanShot X] ...

### ISSUE THREAD

**Issue by ChukieWu** [raycast/extensions#8893]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

it says the extension lacks some application to start the function. Does it mean that I have to download clean shot x and pay to start it function?

### Steps To Reproduce

1.open command
2. select one particular function
3.the extension lacks some application to start the functi
<img width="1280" alt="截屏2023-10-21 15 38 31" src="https://github.com/raycast/extensions/assets/116949863/995d1898-4a7d-4d90-9998-81de51c856e1">
on

**Comment by Aayush9029** [comment]
That's correct.

You can try the screenshot extension for free though in on raycast store.

 @ChukieWu

**Comment by Aayush9029** [comment]
@raycastbot close this issue
