### ISSUE TITLE
No longer works... "An error occurred, Try again later"

### ISSUE THREAD

**Issue by avern87** [raycast/extensions#8897]
### Extension

https://www.raycast.com/johndoe123789/heroicons

### Description

This previously worked perfectly and I used it often. Unfortunately, the extension now just crashes immediately and shows the "An error occurred. Try again later" error message anytime I attempt to open it. 

### Steps To Reproduce

1. Install HeroIcons extension
2. Attempt to access it

### Current Behaviour

It immediatelly crashes, when I attempt to access it. 

### Expected Behaviour

It previously worked flawlessly.

**Comment by connorwforsyth** [comment]
I am also facing this issue and have been for a number of weeks. It's nearly a daily-use extension for me, so I would love to see it working again. ✌️
