### ISSUE TITLE
[mailboxlayer] ...

### ISSUE THREAD

**Issue by bhupesh-sf** [raycast/extensions#8899]
### Extension

https://www.raycast.com/xmok/mailboxlayer

### Description

always getting below error:

![CleanShot 2023-10-21 at 21 07 25@2x](https://github.com/raycast/extensions/assets/6471510/d88ca48d-4e49-4de4-b111-7f1a1ef7b160)

### Steps To Reproduce

1. Install the extension
2. register on https://mailboxlayer.com/dashboard for free account
3. copy the access id from dashboard
4. enter the same in raycast
5. now run the command, enter an email address (valid or invalid)
6. Observe the error

### Current Behaviour

![CleanShot 2023-10-21 at 21 07 25@2x](https://github.com/raycast/extensions/assets/6471510/d88ca48d-4e49-4de4-b111-7f1a1ef7b160)

### Expected Behaviour

should get a successful response

**Comment by xmok** [comment]
Hi bhupesh-sf!

I am unable to reproduce this error 🤔 .

- Can you confirm that you are entering the correct API Access Key? It's possible there's a rogue character like an extra space causing the issue.

- Can you confirm that you are able to call the API directly using the browser or an API tool such as [HTTPie for Web](https://httpie.io/app) ? i.e http://apilayer.net/api/check?access_key={ACCESS_KEY}&email={EMAIL_ADDRESS} ?

Standing by for an update.
