### ISSUE TITLE
Failed to get current track

### ISSUE THREAD

**Issue by anirudhganwal06** [raycast/extensions#8901]
### Extension

https://www.raycast.com/andrewjazbec/lyrics

### Description

I'm watching a song video on youtube but the Lyrics extension says `Failed to get current track` when I search for lyrics.
Basically, not just this, I've tried Youtube Music, Youtube, Youtube Music brave app and many songs. This extension hasn't worked for me at all, not once.
I've configured the extension to use Brave Browser.

### Steps To Reproduce

1. Open youtube or youtube music
2. Search "If the world was ending"
3. Play the video.
4. Open raycast and run `Search Lyrics` command.
5. You should see a `Error • Failed to get current track`

### Current Behaviour
<img width="1151" alt="Screenshot 2023-10-21 at 10 15 16 PM" src="https://github.com/raycast/extensions/assets/46159714/d8536550-f051-4a91-88c8-2f11698c3cc7">

_No response_

**Comment by ajzbc** [comment]
@anirudhganwal06 feel free to open a PR

It is likely either an issue with retrieving the track info with the apple script or the way it is parsed

**Comment by anirudhganwal06** [comment]
There's an issue with getting the player state from the browser applications.
Most probably it works for just a specific app like Spotify as Brave Browser or Safari doesn't seem to provide a `player` state.

Also, I just found out that it opens up a tab in browser that shows the lyrics. I am not interested in that and wanted something that shows lyrics as the song plays.
