### ISSUE TITLE
[Home Assistant] Open Home Assistant application instead the web version

### ISSUE THREAD

**Issue by LucasJanin** [raycast/extensions#8908]
### Extension

https://www.raycast.com/tonka3000/homeassistant

### Description

For now each time, each time the extension opens a new tab in the browser.
It will be beneficial to have the ability to open the Home Assistant application instead of the web version.

### Who will benefit from this feature?

All users have the Home Assistant application installed

**Comment by tonka3000** [comment]
@LucasJanin I've build a first draft to support this via #9832

**Comment by tonka3000** [comment]
@raycastbot reopen this issue
