### ISSUE TITLE
[Apple Notes] ...

### ISSUE THREAD

**Issue by dalynguy** [raycast/extensions#8910]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

<img width="748" alt="image" src="https://github.com/raycast/extensions/assets/138276492/58f79555-875b-4664-a7f3-2bd82dda4f4e">

### Steps To Reproduce

<img width="738" alt="image" src="https://github.com/raycast/extensions/assets/138276492/e8a13c3e-da9e-42a8-8895-e7519cc71322">

### Current Behaviour

When i use it says: Cannot search notes database disk iimage is malformed

**Comment by ashrithps** [comment]
Is there any solution? im facing same issue
