### ISSUE TITLE
[Pie for Pi-hole] Supporte multiple instances

### ISSUE THREAD

**Issue by LucasJanin** [raycast/extensions#8914]
### Extension

https://www.raycast.com/GLaDO8/pie-for-pi-hole

### Description

It will be nice to be able to add multiple Pi-Hole instances.

### Who will benefit from this feature?

Every user with multiple Pi-Hole instances

**Comment by GLaDO8** [comment]
Hey @LucasJanin, quick question, what are some use cases for which you have multiple pi-hole instances? Just curious.

**Comment by LucasJanin** [comment]
Hi Glado8,

I'm using 2 PiHole instances for redundancy: In case one Pi-hole server goes down or experiences issues, others can continue to provide DNS filtering, ensuring uninterrupted internet access.

https://www.reddit.com/r/pihole/comments/cwloxv/why_and_how_im_running_two_instances_of_pihole_on/

**Comment by GLaDO8** [comment]
Got it! With Pi-Hole 6.0 coming out soon, I was waiting for the the REST API to be released for making further improvements. If the release horizon takes too long, I'll start working on this :)

**Comment by LucasJanin** [comment]
Sounds good, thanks for your reply!
