### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by rus1ru** [raycast/extensions#8916]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

#### Error:
```
Error: aborted

connResetException:errors:720:14
TLSSocket.socketCloseListener:node:_http_client:461:19
TLSSocket.emit:node:events:529:35
TLSSocket.emit:node:domain:489:12
```

### Steps To Reproduce

Run the youtube downloader

**Comment by pernielsentikaer** [comment]
Hi @rus1ru 👋 

Could you please provide some reproduction steps?
