### ISSUE TITLE
Deepcast - Translation error

### ISSUE THREAD

**Issue by baptistechretien** [raycast/extensions#8917]
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

Translation error, regardless of the language, only for the "Translation" command.

### Steps To Reproduce

Extension
https://www.raycast.com/mooxl/deepcast

Description
Translation error, regardless of the language, only for the "Translation" command.

[Image](https://dropover.cloud/7eb4e9)

Steps To Reproduce
Translate anything use "Deepcast > Translate".

**Comment by erics118** [comment]
Should be fixed with #8807

**Comment by baptistechretien** [comment]
Thank you, how soon will the fix be published?

**Comment by erics118** [comment]
Probably in the next few weeks. I have to wait for a response from the other developers.

**Comment by erics118** [comment]
That PR was merged.
@raycastbot close this issue
