### ISSUE TITLE
[Browser Bookmarks] 

### ISSUE THREAD

**Issue by teziovsky** [raycast/extensions#8922]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

I opened this issue in relation to https://github.com/raycast/extensions/commit/3dca7873bc565613d252a87dea196ec52f193bc5.
It's a nice feature, but I have that case when I have all bookmarks in Safari (to have it synced via iCloud with iPhone). I'm using `Arc` as the default web browser and now I need to copy the bookmark link from Safari (because the bookmarks are stored in Safari, so the extension is opening Safari) and paste it into `Arc`. That isn't very pleasant, when I'm using this extension a lot 🤔

Maybe it will be a good idea to let the user choose which web browser should open the bookmark via extension preferences. What do you think?

### Steps To Reproduce

1. Open extension
2. Open any bookmark

### Current Behaviour

The bookmark opens in the browser where the bookmark comes from.

### Expected Behaviour

The bookmark opens in the browser which is selected in extension preferences:
1. Where the bookmarks come from
2. In default web browser
3. In the specific web browser

**Comment by teziovsky** [comment]
@iloveitaly maybe you want to look at this Issue 🤔

**Comment by thomaslombart** [comment]
Interesting one. Let's make that a preference, yes. @iloveitaly, do you mind taking care of that? 😊

**Comment by thomaslombart** [comment]
@teziovsky You can now uncheck the preference called `Open Browser's Bookmark`.
