### ISSUE TITLE
[Raindrop.io] Add Bookmarks

### ISSUE THREAD

**Issue by JefCurtis** [raycast/extensions#8928]
### Extension

https://www.raycast.com/lardissone/raindrop-io

### Description

When addding new bookmarks, I would like the ability to add a title/description

### Who will benefit from this feature?

Anyone who creates new bookmarks. I'm surprised it's not already available. 

### Anything else?

Thanks for the wonderful extension. I use it daily!

**Comment by lardissone** [comment]
Interesting, that may be an optional field.

**Comment by JefCurtis** [comment]
I am also curious about why [the use of the multiple raindrop endpoint](https://github.com/raycast/extensions/blob/28756322c9426d9f925011f8b78634d76c168957/extensions/raindrop-io/src/add.tsx#L57C22-L57C22) over the single. It would certainly add to the complexity if you were to add optional fields, as each URL would benefit from its own title input?

**Comment by lardissone** [comment]
Good observation, will update and fix in the next update. 
Do you think of any other field we could include in the Add Bookmark command?

**Comment by JefCurtis** [comment]
> Do you think of any other field we could include in the Add Bookmark command?

Hmm, the description field (from the API docs, I get the impression that it might be the "excerpt" property?) would be useful. I don't use it often, but I imagine some would use it regularly.

**Comment by bmwilly** [comment]
I'm still interested in this. Commenting in hopes that the issue is re-opened.
