### ISSUE TITLE
[Apple Reminders Beta] Menu Bar Reminders fails to fetch latest data

### ISSUE THREAD

**Issue by lucymhdavies** [raycast/extensions#8930]
### Extension

https://raycast.com/raycast/reminders

#### Error:
```
Error: ENOENT: no such file or directory, chmod '/Users/strawb/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/assets/compiled_raycast_swift/reminders'
```

### Steps To Reproduce

I configured access to reminders, and ran the "Menu Bar Reminders" command

### Current Behaviour

The menu part part does not work, instead showing the error seen above.

In my case, the directory above does exist:
```
$ ls -lah /Users/strawb/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/assets/compiled_raycast_swift
total 0
drwxr-xr-x@ 2 strawb  staff    64B 20 Oct 12:53 .
drwxr-xr-x@ 5 strawb  staff   160B 20 Oct 12:53 ..
```

If I create the file it's complaining about...

```
$ touch /Users/strawb/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/assets/compiled_raycast_swift/reminders
```

then I get a different error

```
Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:414:11)
    at spawn (node:child_process:761:9)
    at /Users/strawb/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/menu-bar.js:31:2719
    at new Promise (<anonymous>)
    at Object.FX (/Users/strawb/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/menu-bar.js:31:2561)
    at async sw (/Users/strawb/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/menu-bar.js:31:3443)
```

### Expected Behaviour

I have Reminders configured, and things like "My Reminders" works fine.

**Comment by thomaslombart** [comment]
That's a curious one. This looks like a bug that should fail for all commands. Are you sure you didn't confuse the `My Reminders` command with the native extension? 

Otherwise, do you have any kind of antivirus on your Mac? That could explain what's happening here.

**Comment by lucymhdavies** [comment]
Oh, fun times. This is one of those bugs which... after a bunch of restarts since I first noticed the issue, it's working fine now. Love those kind of bugs 😂 

It was definitely the `My Reminders` command and the `Menu Bar Reminders` command.

If it happens again next time I reboot the laptop... is there a good place for me to gather some more error logs?

And if it doesn't happen again next time I reboot... I'm fine to just close this off for now.

**Comment by thomaslombart** [comment]
Ah, that's frustrating 😅 

But it's good to know that it's working out. If it happens again, feel free to reopen the issue and provide some more logs here.
