### ISSUE TITLE
[Punto Switcher] Switch input locale after text conversion

### ISSUE THREAD

**Issue by AlDemion** [raycast/extensions#8932]
### Extension

https://www.raycast.com/red.avtovo/punto

### Description

It would be fine if there were an option to switch the input locale to the conversion language after conversion.

**Comment by red-avtovo** [comment]
Hi @AlDemion! That is actually what is already happening. The quite unfortunate thing is that it is not ideal and sometimes doesn't switch the layout. 
But otherwise it is already implemented

**Comment by red-avtovo** [comment]
@AlDemion I haven't heard you for a while. Since everything is working (not ideal, but still working), I'm closing this issue.
Feel free to reopen it if you think otherwise

@raycastbot close this issue
