### ISSUE TITLE
[Apple Reminders Beta] ...

### ISSUE THREAD

**Issue by Visual-Studio-Coder** [raycast/extensions#8935]
### Extension

https://www.raycast.com/raycast/reminders

### Description

The reminders don't update in menubar.

### Steps To Reproduce

Quick Add a random reminder. Wait for it to show up in `My Reminders` and then check if its in the menubar

**Comment by thomaslombart** [comment]
The menu bar updates every 10 minutes so it may be expected.

**Comment by thomaslombart** [comment]
Closing it in order to keep the backlog clean. Feel free to reopen the issue.
