### ISSUE TITLE
[Raindrop.io] ... Ability to Search ONLY Title

### ISSUE THREAD

**Issue by michaelwoodruff** [raycast/extensions#8939]
### Extension

https://www.raycast.com/lardissone/raindrop-io

### Description

There is a lot garbage in descriptions of bookmarks that automatically gets added when you save a bookmark to Raindrop. I rarely won't that info, and I don't think you have a choice in the Chrome extension. The problem is by default when searching for a bookmark in Raycast it finds stuff unrelated because it finds these keywords in the description, and I never even knew it was there. Searching would be much easier (probably faster) if it only looked at the TITLES. Can we add the ability to ignore descriptions when searching as a toggle?

### Who will benefit from this feature?

Everyone who uses search

**Comment by michaelwoodruff** [comment]
Not sure if this can be fixed at the Extension, or would need to be added by Raindrop service/APOI itself?

**Comment by lardissone** [comment]
Hi @michaelwoodruff thanks for reporting.

Look, search is open to use any of the default operators by Raindrop, you can check the docs [here](https://help.raindrop.io/using-search/#operators).

**Comment by tnaseem** [comment]
> Hi @michaelwoodruff thanks for reporting.
> 
> Look, search is open to use any of the default operators by Raindrop, you can check the docs [here](https://help.raindrop.io/using-search/#operators).
> 
> And it seems you cannot search for title only. Maybe we should suggest to Raindrop author to include a `title:"something"` operator or similar to make this happen.

Sorry for bring this up again...

I had a look at the documentation for Raindrop and it appears that you can search by title now. As a test, in Raycast, I added `title:` before the search text and it did just that - searched just the title string. So, I'm assuming there must be a way?

**Comment by lardissone** [comment]
It was added in #15955
