### ISSUE TITLE
Twillo's Autjy

### ISSUE THREAD

**Issue by adigold** [raycast/extensions#8947]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

I'm experiencing corrupted code on all of my keys:
https://cloud.agsoundtrax.com/5zubnkXR

### Steps To Reproduce

1. Unauthorized device.
2. Authorized again.
3. Experiencing errors.

**Comment by guga4ka** [comment]
seems like a backup password is wrong

**Comment by adigold** [comment]
You're right. Thank you! It would be helpful to have the error reason in the extension window. Thanks again for your assistance!

**Comment by guga4ka** [comment]
@adigold it should show an alert like it 
<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/13866979/3f2c8241-17c6-4301-9b9d-52e3415c5dc6">

could you pls say, do you have 7 digit OTPs like twitch, twilio, pinterest etc?

@raycastbot close this issue

**Comment by adigold** [comment]
I haven't seen this pop-up alert, and you're right. I only received a single Twitch OTP code.

**Comment by guga4ka** [comment]
yeah, this is a source why this alert wasn't shown. Will fix in next release

**Comment by adigold** [comment]
Perfect!
Thanks
