### ISSUE TITLE
[Apple Reminders Beta] Something went wrong "My Reminders"

### ISSUE THREAD

**Issue by teziovsky** [raycast/extensions#8955]
### Extension

https://www.raycast.com/raycast/reminders

#### Error:
```
RangeError: Invalid time value

nM:my-reminders.tsx:11:53

---
 8: 
 9: export default function Command() {
10:   const { displayCompletionDate } = getPreferenceValues<Preferences.MyReminders>();
11:   const [listId, setListId] = useCachedState<string>("all");
12: 
13:   const { data, isLoading, mutate } = useData();
14: 
---

Fr:index.js:9:2490
    at ray-navigation-stack
Vo:index.js:9:2088
```

### Steps To Reproduce

1. Update extension
2. Open "My Reminders"

### Current Behaviour

Reminders are not showing

![reminders 2023-10-25 at 12 55 26](https://github.com/raycast/extensions/assets/36273653/d92e6609-1218-443b-89df-2a9ea5e23cb2)

**Comment by thomaslombart** [comment]
Would you mind sharing the date time of your reminders?

**Comment by teziovsky** [comment]
<img width="591" alt="Screenshot 2023-10-25 at 12 57 18" src="https://github.com/raycast/extensions/assets/36273653/0f984cc4-7781-4eb1-8939-623cab8705c1">

<img width="407" alt="Screenshot 2023-10-25 at 12 57 37" src="https://github.com/raycast/extensions/assets/36273653/1172f4e4-f34e-4e36-b735-841716b2f6ca">

**Comment by thomaslombart** [comment]
I shipped [a fix](https://github.com/raycast/extensions/commit/bcfcfad4f1883a7051e6556d0d800b4d0302eef7). Do you still have the issue?

**Comment by teziovsky** [comment]
```
RangeError: Invalid time value

nM:my-reminders.tsx:11:53

---
 8: 
 9: export default function Command() {
10:   const { displayCompletionDate } = getPreferenceValues<Preferences.MyReminders>();
11:   const [listId, setListId] = useCachedState<string>("all");
12: 
13:   const { data, isLoading, mutate } = useData();
14: 
---

Fr:index.js:9:2490
    at ray-navigation-stack
Vo:index.js:9:2088
```
Hmmm nothing changed. When I cleared `Clear Local Storage & Cache`. The extension opened properly, but when I changed `Group By` to `Due Date` it crashed again with that error 🤔

**Comment by thomaslombart** [comment]
Ah, so it may be related to how the due dates are parsed and organized into sections. I tried replicating your reminders due dates but couldn't make it crash. Let's try one more time.

**Comment by thomaslombart** [comment]
Are you able to launch the extension locally? If so, could you add a `console.log` [here](https://github.com/raycast/extensions/blob/1ac6ae88e3086c8a308e332736a2a69f7ac71281/extensions/apple-reminders/src/hooks/useViewReminders.ts#L101) and let me know if you get any value?

**Comment by teziovsky** [comment]
Yes of course, let me check 😎

**Comment by teziovsky** [comment]
I have that error during `npm run dev`
```
build failed (src/api.ts:1:22 import reminders from "swift:../swift/reminders";): failed to parse the swift package: exit status 1
```

Do you know how to solve it? 🤔

**Comment by thomaslombart** [comment]
Which version of macOS and Swift are you using?

**Comment by teziovsky** [comment]
# MacOS
```bash
sw_vers
ProductName:		macOS
ProductVersion:		14.1
BuildVersion:		23B74
```

# Swift 
```bash
swift -version
Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: x86_64-apple-darwin23.1.0
```

**Comment by teziovsky** [comment]
All I need to do in the project dir is `npm run dev`, right?

**Comment by thomaslombart** [comment]
Assuming you run `npm install` beforehand, yes `npm run dev` is the only command you need to run.

**Comment by teziovsky** [comment]
```
npm install && npm run dev

up to date, audited 254 packages in 1s

98 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> dev
> ray develop

info  -  entry points [src/my-reminders.tsx src/create-reminder.tsx src/menu-bar.tsx src/quick-add-reminder.tsx]
error -  compiling swift package
build failed (src/api.ts:1:22 import reminders from "swift:../swift/reminders";): failed to parse the swift package: exit status 1
```

![Raycast 2023-10-30 at 10 15 28](https://github.com/raycast/extensions/assets/36273653/11914b51-3190-4046-ab4a-81ae1d1ea259)

**Comment by thomaslombart** [comment]
I assume you're using the latest Raycast version as well? What version do you also have when running `ray version`?

**Comment by teziovsky** [comment]
```
bunx ray version
1.60.1
```

**Comment by thomaslombart** [comment]
And using Xcode 15+? 😅

**Comment by teziovsky** [comment]
Ok, there is a problem I guess 🙈

**Comment by teziovsky** [comment]
```
xcodebuild -version
Xcode 15.0.1
Build version 15A507
```

```
npm run dev

> dev
> ray develop

info  -  entry points [src/my-reminders.tsx src/create-reminder.tsx src/menu-bar.tsx src/quick-add-reminder.tsx]
error -  compiling swift package
build failed (src/api.ts:1:22 import reminders from "swift:../swift/reminders";): failed to parse the swift package: exit status 69
```

It's not a problem 🤔 🤷

**Comment by thomaslombart** [comment]
I'll check in with the team and see what's happening here. Are you still getting the bug as of today even after clearing the cache in case the extension didn't update after the fix?

**Comment by teziovsky** [comment]
Hmm, all extensions are up to date, raycast is up to date, `My Reminders` cache is deleted, and still there is an error:

![apple-reminders 2023-10-30 at 15 09 35](https://github.com/raycast/extensions/assets/36273653/8db0f826-b074-47fa-8f01-f416fde4d2f4)

**Comment by thomaslombart** [comment]
I shipped another fix that will hopefully solve your problem: https://github.com/raycast/extensions/commit/19c58d2dd265a8352eeeff270cf4057368d9d50e. Could you try out once again when it's published (in ~30 minutes) and after checking the extension updates?

**Comment by teziovsky** [comment]
Now works as expected 🚀🎊
Thank you for this fix!

**Comment by thomaslombart** [comment]
Glad it works! 🙌
