### ISSUE TITLE
[Twilio’s Authy] All OTP corrupted after updating backup password

### ISSUE THREAD

**Issue by justaddcl** [raycast/extensions#8957]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

I was prompted by Authy to update my backup password. However, once I did that through the Authy app and then updated my Authy Backup Password on the Twilio's Authy extension, all my OTP now appear as `corrupted`. However, any new OTPs added to Authy since updating my backup password works as expected. If I use my previous backup password, I can see all my older OTPs, but the new OTPs then appear as `corrupted`. Essentially, I have to choose which set of OTPs I want working since not all will work at once.

### Steps To Reproduce

1. In the Authy Desktop, go to **Settings** > **Accounts** > **Change Backup Key** and create a new backup key
2. In Raycast, go to **Raycast Settings** > **Extensions** > **Twilio's Authy** and then change the `Authy Backup Password` to the password updated in step 1.
3. Use the **Twilio's Authy** Raycast extension to view Authy OTP and see the OTPs are now all `corrupted`
4. Add a new OTP to your Authy account
5. Sync the **Twilio's Authy** Raycast extension to make sure the new OTP added in step 4 is visible and is not `corrupted`. 

### Current Behaviour

After updating my Authy backup key in Authy Desktop as well as the **Twilio's Authy** Raycast extension, all OTPs added before updating the key shows as `corrupt` while all OTPs added after updating the key shows as expected.

### Expected Behaviour

All OTPs should work as expected once the Authy Backup Password for **Twilio's Authy** Raycast extension matches the backup key set on the Authy account.

**Comment by guga4ka** [comment]
Kinda strange behaviour, after sync it should replace old tokens encrypted by old password with new. Could you pls try to re-install extension. Will try to reproduce it at free time

**Comment by justaddcl** [comment]
Hi @guga4ka, have you had a chance to look into this issue? Is there anything else I can do in the meantime?

**Comment by vassyz** [comment]
Same issue here, changed my backup password and the newly added tokens show up as corrupted.

**Comment by justaddcl** [comment]
Since there have been no updates from @guga4ka, I tried forking the extension to see if I might be able to help fix this issue in the meantime. 

While in development mode, I happened to run the `Clear Local Store & Cache` action (from the `Actions` menu when the `Search Token` command is hovered/selected in Raycast) while trying to debug the issue. I ultimately couldn't identify or fix the issue with my local forked version, but when I retried un-installing and re-installing the extension, my OTPs were all working again on my non-local version.

@vassyz, perhaps try clearing your local store and cache then try un-installing and re-installing the extension to see if that fixes your issue too?

@guga4ka, any chance the extension is not properly clearing the cached values when the backup password is updated in the extension's settings? 🤔

**Comment by vassyz** [comment]
@justaddcl I don't see the `Clear Local Store & Cache` option.

**Comment by justaddcl** [comment]
@vassyz, have you [forked the extension](https://developers.raycast.com/basics/contribute-to-an-extension) and run it locally?

**Comment by vassyz** [comment]
> @vassyz, have you [forked the extension](https://developers.raycast.com/basics/contribute-to-an-extension) and run it locally?

So sorry, I missed that bit.

**Comment by mallowigi** [comment]
Hi, I'm currently having this issue. It was working fine until I decided for some reason to reinstall the app. And now some passwords are corrupted. Clearing the cache didn't work.

**Comment by guga4ka** [comment]
@justaddcl can you contribute your changes to upstream extension, i've tried a several times to change a password and each time it works just fine.
