### ISSUE TITLE
Action.Push need onPop props to trigger some state change

### ISSUE THREAD

**Issue by chyroc** [raycast/extensions#896]
current, Action.Push props:

![image](https://user-images.githubusercontent.com/15604894/153803526-1da77054-9c26-4f88-b738-224b5520214a.png)

i need `onPop` props to trigger outter components some action done, and some state chagne.

**Comment by thomaspaulmann** [comment]
Not sure if the push action is the right place to add such functionality. Maybe it should be rather something of the `useNavigation` hook. The hook could provide some callback that is triggered as soon as the the component is rendered again. 

Not exactly sure about your use case, but you could add some callback to the component that you push. The callback can then update the previous screen. As far as I understand, this should solve your problem.

**Comment by thomaspaulmann** [comment]
I'm closing this issue given that there is a workaround for it.

**Comment by MarlBurroW** [comment]
This workaround doesn't work.
I've a Websocket on the main command screen updating a state passed on a pushed screen (data are stored with a useState hook).
The state is passed to the second screen via a prop.

Example
```jsx
<Action.Push title="Monitor detail"   monitor={monitor}/>} />
```

When the websocket update data on the main screen, this update doesn't trigger re-rendering on the pushed screen.
