### ISSUE TITLE
Split/Keep formatted text as individual tasks.

### ISSUE THREAD

**Issue by krishnaar21** [raycast/extensions#8961]
### Extension

https://www.raycast.com/maggie/todo-list

### Description

sometimes my team members send some tasks in single block of text or formatted in slack/teams etc but i wanted to copy whole thing and make it as individual tasks (respect markup format)

### Who will benefit from this feature?

Users of todo extension.

**Comment by bkeys818** [comment]
@krishnaar21, I want to make sure I understand what you're asking for. Can you provide an example?
