### ISSUE TITLE
[Browser Bookmarks] ...

### ISSUE THREAD

**Issue by jdenormandie** [raycast/extensions#8963]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

Not sure when it started, but fairly recently.  

I use Arc browser as my default browser (if I click on a webloc file, the link opens in Arc, also I've set the preference in System Settings > Desktop & Dock > Default web browser = Arc.) but since Arc doesn't do bookmarks, and I have years of bookmarks saved in Safari, I have enabled both Safari and Arc in the Browser Bookmarks extension.  

Now when I use Browser Bookmarks to select a bookmark from my Safari bookmarks, the link opens in Safari.  Until recently the link would open in Arc.

### Steps To Reproduce

Running Raycast v1.6.0.1, on macOS Sonoma 14.0.  When I click the (i) on the Browser Bookmark extension it takes me to a Github page for "Browser Bookmarks: Add support for Arc (#8497)".  I have run the Raycast extension "Check For Extension Updates" to make sure I am running the current version.

Steps:
Invoke Raycast.
Type "bm" which is the alias I have given Browser Bookmarks, then tab.
Select any link.
Link opens in Safari instead of my default browser, Arc.

### Current Behaviour

Links open in Safari.

### Expected Behaviour

Links should open in Arc.

**Comment by thomaslombart** [comment]
We've added a preference that is enabled by default so that bookmarks are opened on the browser they're associated with, to disable that, go to the command preferences and uncheck `Open Bookmark's Browser`.

**Comment by jdenormandie** [comment]
That fixed it, thanks!
