### ISSUE TITLE
Add an event argument to `onAction`

### ISSUE THREAD

**Issue by Haojen** [raycast/extensions#897]
My Raycast Version: latest version (1.28.0)

## 1. if I bind custom keyboard , The first and second keyboard modifiers in ActionPanel always is **enter** and **cmd** + **enter**,they never change, this is bug ? or that's it ?

<img width="793" alt="Screen Shot 2022-02-14 at 3 13 44 PM" src="https://user-images.githubusercontent.com/6928850/153816927-5f263171-a3d0-4a91-8264-7972d0d5b05d.png">

 I don' find from https://developers.raycast.com/api-reference/keyboard any details can tell me why it is that.

## 2.  I want when onAction event handler triggered to know user  pressed which key,  because I want to have different logic for different keys 

Here is example
 ```javascript
  <ActionPanel.Item
      title="Down"
      shortcut={{ modifiers: ["opt"], key: "arrowDown" }}
      onAction={ keyboardEvent => console.log("Your event triggered by", keyboardEvent.keys, keyboardEvent.modifiers )}
  />

```

**Comment by mathieudutour** [comment]
> if I bind custom keyboard , The first and second keyboard modifiers in ActionPanel always is enter and cmd + enter,they never change, this is bug ? or that's it ?

That's a feature ;) 
The first and second action are always going to have those 2 shortcuts, that's what users are used to. The behaviour is documented here: https://developers.raycast.com/api-reference/user-interface/action-panel#actionpanel 

The shortcut that you define will still work tho

> I want when onAction event handler triggered to know user pressed which key, because I want to have different logic for different keys

I'm not too sure that would lead to a good UX. What would be the use case for it?

**Comment by mathieudutour** [comment]
Going to close this as it's unlikely that we are going to do this without details about the use cases
