### ISSUE TITLE
[ChatGPT] Can't create new model with ⌘ + T.

### ISSUE THREAD

**Issue by nandastone** [raycast/extensions#8977]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Listing models shows "No custom models, create a new model with ⌘ + T shortcut."

The shortcut doesn't work.

### Steps To Reproduce

Open the ChatGTP Models command.
Press ⌘ + T.

### Current Behaviour

Pressing ⌘ + T plays the Mac invalid input sound, and nothing happens.

### Expected Behaviour

Pressing ⌘ + T allows adding a new model.

**Comment by nandastone** [comment]
Suggestion - all the "Create Model" action to be triggered with regular Raycast actions like pressing enter.

**Comment by jchuder** [comment]
@nandastone I also had the same issue, but I found that it was resolved after reinstalling the extension.

**Comment by jblogs** [comment]
it appears again in version 1.73.2.
I do customized models than the default one, but the model page now shows no model
the cmd T keystroke does not work
i know if i reinstall the extension might resolve the problem, but it would lead to lose all my conversation data
