### ISSUE TITLE
[Apple Reminders Beta] Natural Language

### ISSUE THREAD

**Issue by guspimentel** [raycast/extensions#8979]
### Extension

https://www.raycast.com/raycast/reminders

### Description

What if we could add reminders using natural language. Similar of what's done on the Hypersonic extension.

### Who will benefit from this feature?

Everyone

**Comment by thomaslombart** [comment]
You can with the `Quick Add Reminder` command: https://x.com/thomas_lombart/status/1717084599170257352?s=20

**Comment by davetorbeck** [comment]
Is there a reason this is paywalled behind AI?  Seems there are plenty of non-AI NLP libraries to implement something like this.

**Comment by davetorbeck** [comment]
@thomaslombart Looks like the alfred-reminders plugin uses Chrono.js to parse dates from natural language.  I haven't looked too in-depth into it but it works well in alfred from my own usage.

https://github.com/wanasit/chrono

**Comment by thomaslombart** [comment]
I have actually seen that one, and it would probably work fine for dates. However, this doesn't take into account recurring dates and all the other fields like priority or list names. You also get internationalization without having to configure anything with AI.
