### ISSUE TITLE
[Trello] ...

### ISSUE THREAD

**Issue by davewehr** [raycast/extensions#8981]
### Extension

https://www.raycast.com/ChrisChinchilla/trello

### Description

I am trying to use the Trello RayCast plugin and am having trouble authenticating. 

I entered into the settings my Trello username (email address)
I generated an "person access token" from my Atlassian account settings.
The field for API token was already filled out when I installed the extension.

Every time I try to use the plugin, it says it cannot authenticate.

Please advise. 

### Steps To Reproduce

I entered into the settings my Trello username (email address)
I generated an "person access token" from my Atlassian account settings.
The field for API token was already filled out when I installed the extension.

**Comment by ChrisChinchilla** [comment]
Hmm @davewehr The only think I can think of is that your email address isn't actually your user name? Check what value people "@" you, that might be the user name instead?

**Comment by davewehr** [comment]
Good Afternoon,

Thanks for your response. I did go and see that my username is actually ‘davewehr3’ but when I try that it still doesn’t work…

Can you confirm that the API token that was pre-populated when I installed the add-on, should in fact be pre-populated?

What else can I try?

**Comment by ChrisChinchilla** [comment]
@davewehr yes, that’s my token, which is needed to work with the Trello API that the extension calls, and as far as I know, it works for everyone else. Hmm, I’ll try and dig further with a fresh account p.

**Comment by davewehr** [comment]
Thanks, I appreciate your time troubleshooting this issue.

**Comment by ChrisChinchilla** [comment]
@davewehr Sorry for the delay, but I am stuck on this, however, I have received a few others reporting it, but never created on GitHub unfortunately, but a small minority of users.

Did you change the API key at all?

You can also try visiting the following URl yourself (ideally with curl if you know how, but a browser is also fine)

https://api.trello.com/1/members/me/boards?key=${apitoken}&token=${token}

Replace apitoken with the default token and token with yours. Let me know if you get any ore detailed errors…

**Comment by davewehr** [comment]
Good Afternoon,

Sorry I let this die on the vine, it was a low priority for me.

I just uninstalled and reinstalled the extension, so I am 100% sure the default token has not changed.
I also revoked my Trello API token and created a new one, and used that to configure the plugin.
For my username, it shows in Trello as @davewehr3 so I tried that, as well as davewehr3.

I attempted to follow the troubleshooting steps provided, using the URL provided and replacing the default token as well as my own token, but I am getting a 404 error, saying “invalid key”.

I wasn’t sure if I was supposed to remove the {} or input the tokens within, so I tried both but the result was the same both times. 

One thing of note, I that I am also using the Confluence and Jira extensions, which work as expected. 

Please advise, and thank you in advance. Have a great day!

**Comment by ChrisChinchilla** [comment]
@davewehr Clutching at straws here, but did you follow the setup steps? Specifically following this URL and giving access to the appropriate boards etc?

https://trello.com/1/authorize?expiration=never&name=RayCastTrelloExtension&scope=read&response_type=token&key=13f8c59607ba6d82531d3db5f46999c1

**Comment by davewehr** [comment]
Chris, 

Thanks for getting back to me. I’m not sure how I missed that, I thought I looked at all the instructions but never saw the page you sent. I tried it, was able to log in, and get a token from the link after I logged in and granted access to the boards.

I’m assuming the code I got from that process is what goes into the ‘Personal Access Token’ field, so I dumped it into there. VOILA, it worked!!!

Thank you!

BTW: Where did that link come from? I just went through the motions of installing the Raycast extension and didn’t see a reference to it anywhere…

**Comment by ChrisChinchilla** [comment]
@davewehr Ahh, this might explain the occasional error then, as it's mentioned in the read-me file, but I can't imagine everyone would look at it, so clearly, there needs to be better onboarding. I'll work on it!

**Comment by ChrisChinchilla** [comment]
Unfortunately, Raycast supports PKCE, and the Trello API doesn't, so I was hoping to change the auth flow to OAuth, but I can't. So instead, I am just going to clear the fields people need to fill in, and at least then trying to use any command will take people to the preferences showing they have to add something… 🤷‍♂️
