### ISSUE TITLE
[Set Audio Device] ... Doesn't set favorite audio device M1 and intel Mac

### ISSUE THREAD

**Issue by arturas-sisakovas-ibm** [raycast/extensions#8982]
### Extension

https://www.raycast.com/benvp/audio-device

### Description

Hello,

Appreciate the Reycast as well rich library of extension it brings to the table. Really impressed by productivity boost and ease of use.

Would like to clarify one particular problem. Currently experiencing the problem trying to set audio input/output device as favorite with [Set Audio Device](https://www.raycast.com/benvp/audio-device) extention.

Maybe I am just not understanding a concept of "setting favorite device in Preference" - is it meant to be MacOS preferences or Reycast Preferences?

The problem is the following: In macOS (14.1 Sonoma) on both - Macbook Pro Intel (2019) and M1 MAX (2021) - I select an audio input/output device in **Mac -> Sound** preferences -> Open Reycast -> Trigger "Set Output Device to Favorites" and get this error:
![image](https://github.com/raycast/extensions/assets/123038201/68d1afc8-8631-4fd1-ab23-74ffe2592be2)

Could someone take a look at this issue?

P.S: It might be just my missunderstand.

Thanks!

### Steps To Reproduce

1. Open Mac Sound settings output tab
2. Select output device
3. Open Reycast and execute "Set Output Device To Favorites"
4. Get error: "No favorite output audio device specified"

**Comment by tomgenoni** [comment]
I've set my "Favourite Output Device" in the extensions settings...

![Screenshot 2023-12-08 at 6 28 48 PM](https://github.com/raycast/extensions/assets/1171072/2e4be92d-0068-42b2-936f-eb9c6768c2ea)

but I get an error running "Set Output Device to Favourite"

![Screenshot 2023-12-08 at 6 30 34 PM](https://github.com/raycast/extensions/assets/1171072/3c5e6a13-230e-4dc8-9fd2-9caf7d278185)

**Comment by ferd-az** [comment]
we need a new set audio device extension 👀
