### ISSUE TITLE
[Ollama AI] ...

### ISSUE THREAD

**Issue by this-josh** [raycast/extensions#8983]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

#### Error:
```
SyntaxError: Unexpected end of JSON input

    at JSON.parse (<anonymous>)
PassThrough.<anonymous>:ollama.ts:206:63

---
203:         body?.on("data", (chunk) => {
204:           if (chunk !== undefined) {
205:             const buffer = Buffer.from(chunk)

### Steps To Reproduce

Not sure, but I have had this error twice today.

Today it came from `pytorch lightning 80 epochs`

Model `openhermes2-mistral:latest:`


If this doesn't have enough description feel free to remove 

### Current Behaviour

Crashes after writing ~200 words

### Expected Behaviour

not to crash

**Comment by MassimilianoPasquini97** [comment]
Hi @this-josh,

it seems Ollama [generate](https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-completion) api is responding with a malformed json response causing this issue. For better understand what is causing this issue and try to reproduce it I need the following information;

* This problem appear only using openhermes2-mistral:latest model?
* Have you tried to use this model with ollama cli? If true, have you experience any issue?

**Comment by this-josh** [comment]
I have only been using this model recently, have now switch to zephyr, I'll let you know if I see the error again.

I've only used it via the cli a few times, no issues. I have experienced it a few times in raycast.  It would be good if this extension could print more verbose error messages at the very least

**Comment by MassimilianoPasquini97** [comment]
When I have created this extention I have followed Ollama API documentation end viewing at [generate](https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-completion) API it use two differente json response. One used during text generation and one when text generation is ended. Viewing TS error probably Ollama API is responding using a different json format non documented.

I will view deep on Ollama Code trying to find if there is an undocumented json format used during generate api response.

**Comment by MassimilianoPasquini97** [comment]
They deleted `sample_count` and `sample_duration` without updating docs. I have created a separated branch on [raycast_ollama](https://github.com/MassimilianoPasquini97/raycast_ollama/tree/OllamaResponseApiFix) where I have applied the fix. I will ask you @this-josh if you can clone this branch and test on you machine if the problem is fixed. Let me know if you can do this for me and if it solved the issue. Thank you for your help and for report this bug 🙏🏻.

**Comment by this-josh** [comment]
Sorry @MassimilianoPasquini97 I managed to miss this. I cannot see the branch now, perhaps you've closed it? I haven't experienced this issue for a little while now.

**Comment by MassimilianoPasquini97** [comment]
Hi @this-josh, I suppose it was an Ollama or os related issue and seems to be resolved. At this time I'm receiving a similar problem (`SyntaxError: Expected ',' or ']' after array element in JSON at position 9882`) only on extensions installed on macOS 13.6.0. For those one is better to update the os at least on the latest 13.6 release, currently 13.6.2.

If you are no longer facing this problem I think that this issue can be closed.
