### ISSUE TITLE
Documentation on clipboard topics should be updated

### ISSUE THREAD

**Issue by Haojen** [raycast/extensions#899]
In Raycast latest version(1.28.0) , the Clipboard API is removed and split. If follow the steps in the documentation to import Clipboard API, they will be throw A error  info say can't find this module.

The doc say
```javascript
import { Clipboard } from "@raycast/api";

export default async () => {
  await Clipboard.copy("https://raycast.com");
};
```

But actually is
```javascript
import { copyTextToClipboard,  pasteText } from  "@raycast/api";
```

**Comment by mathieudutour** [comment]
It's the other way around, in `1.28.0`, `copyTextToClipboard` and `pasteText` are deprecated in favour of `Clipboard`

**Comment by Haojen** [comment]
@mathieudutour  True, I checked my package.json depend, is 1.27 NOT 1.28,  so I update to 1.28. then I seen discarded and replace a lot APIs. I'm so tired look like my Raycast extension never can't  publish. always on the road. 😂

By the way, the old APIs on new Raycast version (1.28+) can work is fine?

**Comment by mathieudutour** [comment]
yes, it's all backward compatible, the old APIs will work fine, but they will be shown as deprecated and should show a helpful message regarding how to migrate.

Sorry about the confusion!

**Comment by Haojen** [comment]
@mathieudutour Yeah, I agree with that. Hope can show a deprecated API info to attention developers. anyway hope you guys doing well
