### ISSUE TITLE
[Simple Reminder] Punctuation marks and umlauts are removed from the reminder title

### ISSUE THREAD

**Issue by FelixLisczyk** [raycast/extensions#8990]
### Extension

https://www.raycast.com/comoser/simple-reminder

### Description

Special characters like punctuation marks (?!.) and umlauts (äöü) are stripped from the reminder title.

### Steps To Reproduce

Create a reminder "Go to the supermarket? in 1 hour"

### Current Behaviour

The new reminder is called "Go the supermarket" (without the question mark)

### Expected Behaviour

A reminder "Go to the supermarket?" is created.

**Comment by comoser** [comment]
@FelixLisczyk with this change, the extension should be more faithful to what you actually input. Regarding the special characters (like the ones you mentioned that are common in northern european languages), the extension (much like raycast itself) only officially supports english. For any other language a large revision is needed to support them.

**Comment by FelixLisczyk** [comment]
This works now even with umlauts. Thank you very much for the quick fix! 👍
