### ISSUE TITLE
[Toothpick] Disconnect doesn't work on Intel mac

### ISSUE THREAD

**Issue by powersagitar** [raycast/extensions#8997]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

Toothpick doesn't disconnect the mac from bluetooth devices. Each time clicking on the *disconnect* button or hit *enter*, a message shows up saying *Device disconnected successfully* despite nothing is really disconnected.

### Steps To Reproduce

Environment: 
MacBook Pro 2017 running macOS 14.0 (23A344) with the help of OpenCore Legacy Patcher 1.1.0.
Note: The disconnect feature also didn't work in the past year before the machine was upgraded to Sonoma (it was running Ventura a year ago).

Steps to reproduce:
1. Open Raycast and type `toothpick`, then select *Manage Bluetooth Connections*.
2. Find a random connected bluetooth device and either click the *Disconnect* button or hit *enter*.
3. Device isn't disconnected.

### Current Behaviour

Toothpick doesn't disconnect the mac from the bluetooth device.

### Expected Behaviour

Toothpick closes the connection between the mac and the bluetooth device.

**Comment by VladCuciureanu** [comment]
This is part of the flakiness introduced by using MacOS's private AppleScript API. I can only suggest to switch over to the experimental blueutils BlueTooth backend as shown [here](https://github.com/VladCuciureanu/Toothpick#enabling-blueutil-backend).

**Comment by powersagitar** [comment]
Thanks for response. Solution works perfectly, and no problem is observed for now.
