### ISSUE TITLE
[CricketCast] error

### ISSUE THREAD

**Issue by mtancock** [raycast/extensions#900]
# Extension – [Cricketcast](https://github.com/raycast/extensions/tree/main/extensions/cricketcast/)

Author: @sampoder 

## Steps To Reproduce

1. Install extension
2. Attempt to load / refresh extension

## The current behavior

![CleanShot 2022-02-14 at 10 28 32@2x](https://user-images.githubusercontent.com/1439570/153847574-03112933-3b57-4ba4-ac46-c6fc8f6acb5c.png)

Get an error: "Cannot read properties of undefined (reading 'split')"

## The expected behavior

Extension would load

### Raycast version

Version: 1.28.0

**Comment by sampoder** [comment]
Hmm, it's working for me? The Cricinfo API might have been down

**Comment by sampoder** [comment]
(sorry for the late response!)
