### ISSUE TITLE
[ChatGPT] error in typing a English word with Chinese input method

### ISSUE THREAD

**Issue by thchuan2001** [raycast/extensions#9001]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

https://github.com/raycast/extensions/assets/26373468/e7ab6c13-ff91-4d5c-8c49-dec164c0eea0

I encountered an issue while using the popular Chinese input method, "Sogou". Typically, after typing the letters for an English word, I can press "Enter" to input the word. This functionality works seamlessly in other applications, including the main Raycast input bar. However, in the ChatGPT extension, pressing "Enter" prematurely sends the API request instead of inputting the intended English word. I genuinely appreciate your work on this extension—it's been immensely helpful. I kindly request that this issue be addressed for the expansion of your Chinese user base.

### Steps To Reproduce

1. open the chatgpt extension
2. change to "sogou" input method
3. write a english word and type enter
4. you'll find the request is sent without the english word typed

**Comment by mathieudutour** [comment]
This should be fixed in 1.62.0. Let me know if there still are some weird interactions
