### ISSUE TITLE
[Spotify Player] Menu Bar Player

### ISSUE THREAD

**Issue by Arsen302** [raycast/extensions#9003]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Menu Bar Player required the auth to spotify account, but this feature is crushed every time when I'm trying to accept the rights for raycast extension.

### Steps To Reproduce

macOS 14 Sonoma, MacBook Pro 14. latest Chrome, Raycast, Spotify.

### Current Behaviour

Raycast spotify extension can't auth the after successfully approved Spotify API usage. 
![CleanShot 2023-10-28 at 16 52 35](https://github.com/raycast/extensions/assets/62101882/d55e97ce-50cd-417d-9a30-18d6bb85f0a3)

### Expected Behaviour

After 5 times dumb actions of authenticate to Spotify, it work, but why I don't get it, and still have the same error which you can check in the gif. 
![CleanShot 2023-10-28 at 16 52 35](https://github.com/raycast/extensions/assets/62101882/0383cc8c-6237-4e20-9d23-4f3724c3a48b)

**Comment by thezapalsky** [comment]
Hey, I've had the same issue for the past 2 weeks, 

when I tried to authenticate through "Menu Bar Player" I was in never ending loop.

I've tried to authenticate through different options from the extension ("Now Playing" I think) and it worked at the 1st time and now the Menu Bar Player also syncs.

Not sure if that's the fix or the devs fixed something in the meantime but it worked for me, please give it a try and lmk.

**Comment by peduarte** [comment]
We're going to look into this! 👀

**Comment by usnmustanger** [comment]
> Hey, I've had the same issue for the past 2 weeks,
> 
> when I tried to authenticate through "Menu Bar Player" I was in never ending loop.
> 
> I've tried to authenticate through different options from the extension ("Now Playing" I think) and it worked at the 1st time and now the Menu Bar Player also syncs.
> 
> Not sure if that's the fix or the devs fixed something in the meantime but it worked for me, please give it a try and lmk.

I've had the exact same experience.

**Comment by danielraffel** [comment]
Same issue. Raycast asks me to auth spotify over and over again. Once approved it sticks for a day max then expires and I go through this never ending cycle. Just doesn't work.

**Comment by theharryszn** [comment]
same issue, i always have to reauthenticate every single day
