### ISSUE TITLE
[Notion] Search doesn't work if type more than one word from the page name

### ISSUE THREAD

**Issue by Harosatchi** [raycast/extensions#9006]
### Extension

https://www.raycast.com/notion/notion

### Description

Search doesn't work if type more than one word from the page name.

Example in English:

Two words from the name
<img width="747" alt="Снимок экрана 2023-10-28 в 20 50 44" src="https://github.com/raycast/extensions/assets/51264528/9ebad3d9-d7db-4095-850c-6e9679b547b8">

One word from the name
<img width="752" alt="Снимок экрана 2023-10-28 в 20 50 58" src="https://github.com/raycast/extensions/assets/51264528/eb6887bb-49fe-4c6a-a852-5f59cf5c7cf0">

Example in non-English:

Two words from the name
<img width="747" alt="Снимок экрана 2023-10-28 в 20 21 20" src="https://github.com/raycast/extensions/assets/51264528/7a39db57-8875-462f-827a-72c7af2aeb32">

One word from the name
<img width="750" alt="Снимок экрана 2023-10-28 в 20 20 32" src="https://github.com/raycast/extensions/assets/51264528/36abef2d-ab56-43f5-8f2b-1a060abcbeda">

### Steps To Reproduce

Just type more than one word from the page name.

### Current Behaviour

Page won't be found.

### Expected Behaviour

Page must be found.

**Comment by thomaslombart** [comment]
Unfortunately, we can't do much about it as the search results are provided by Notion's API. I'll close this issue as "won't fix" then. Maybe it's worth it reporting that to the Notion team?

**Comment by Harosatchi** [comment]
@thomaslombart
> Unfortunately, we can't do much about it as the search results are provided by Notion's API. I'll close this issue as "won't fix" then. Maybe it's worth it reporting that to the Notion team?

Here's what Notion support responded:

> Our [Search by title](https://developers.notion.com/reference/post-search) API supports searching all parent or child pages and databases that have been shared with an integration even if query contains more than one word from the page title.
> 
> If this is not working for you, could you please give us more information on the API call you are using and the pages/databases that you are expecting in the API response?

Can you tell me what to answer them?

**Comment by Harosatchi** [comment]
@thomaslombart
> You can tell them they'll find the code over here: https://github.com/raycast/extensions/tree/main/extensions/notion/src. Especially here: https://github.com/raycast/extensions/blob/main/extensions/notion/src/utils/notion/page.ts

Wrote. Answered:
> Unfortunately, reviewing custom scripts are out of the scope of support. Could you please share the exact API and its payload, that you will use with any REST client such as Postman or cURL command so that we can review it?

**Comment by thomaslombart** [comment]
Well, we're using their Notion client so I can't give an exact API. It's looking like that:

```
await notion.search({
  sort: {
    direction: "descending",
    timestamp: "last_edited_time",
  },
  page_size: 20,
  query: "The",
});
```

Then, I guess the call under the hood made is:

```
curl -X POST 'https://api.notion.com/v1/search' \
  -H 'Authorization: Bearer '"$NOTION_API_KEY"'' \
  -H 'Content-Type: application/json' \
  --data '{
    "query":"The",
    "page_size":20,
    "sort":{
      "direction":"descending",
      "timestamp":"last_edited_time"
    }
  }'
```

**Comment by Harosatchi** [comment]
@thomaslombart

Their answer:
> Can you please confirm if you have ran the same API call in using cURL or any REST client such as Postman to confirm if search API call is not working as expected? If yes and you are not getting the expected results, could you please share the API call and its payload you used for search API call, pages that were expected in the search results, etc.

**Comment by AlexIsMaking** [comment]
Not sure if I've misunderstood the issue here but I can type more than one word to search for a specific page name -

![CleanShot 2023-11-16 at 13 49 34@2x](https://github.com/raycast/extensions/assets/10284831/8e8bc232-a435-4db0-adc8-ee1d66e3a08d)

![CleanShot 2023-11-16 at 13 49 49@2x](https://github.com/raycast/extensions/assets/10284831/7c2e553e-48fa-4430-8146-a7f1eb175947)
