### ISSUE TITLE
[Notion] Option to only allow inputs for certain properties on "Create Database Page" command

### ISSUE THREAD

**Issue by andrewgoldsky** [raycast/extensions#9010]
### Extension

https://github.com/raycast/extensions/blob/1def14244b6316e7986ce89daa4267ea480c3527/extensions/notion/

### Description

I'm using the Notion extension to write pages to a task database that has a large number of properties. Realistically I only want to use 3-4 of these properties when creating a new task. Is there a way for the "Create Database Page" command to only ask for inputs on a select set of properties?

@erich2s @bkeys818 @thomaslombart 

### Who will benefit from this feature?

Notion power users

**Comment by erics118** [comment]
See #8479 and #5016
