### ISSUE TITLE
[1Password] Password not copied if biometric step is required

### ISSUE THREAD

**Issue by gshpychka** [raycast/extensions#9012]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

The "copy password" action does not copy the password if the 1P app prompts for Biometric authentication. It should copy the password after successful authentication.

### Steps To Reproduce

1. Enable TouchID protection in 1Password settings.
2. Use this extension's "copy password" feature
3. You will be prompted by 1Password to authenticate with TouchID, complete the authentication
4. Confirm that the password was not copied

### Current Behaviour

Password not copied after completing biometric auth, you have to perform the action again to actually get the password.

### Expected Behaviour

Password copied after completing biometric auth

**Comment by andreiborisov** [comment]
@khasbilegt, will you be able to look into this? 🥺

**Comment by gshpychka** [comment]
This is still an issue.

**Comment by gshpychka** [comment]
@khasbilegt this is still an issue

**Comment by Luk4h** [comment]
Hello, I am working on some updates of the app, right now focused only on v8. Which version of 1Password are you using?

**Comment by gshpychka** [comment]
> Hello, I am working on some updates of the app, right now focused only on v8. Which version of 1Password are you using?

Using latest v8

**Comment by Luk4h** [comment]
With the latest release, you can enable the "Auto Renew Authorization" background refresh, resulting in fewer biometric prompts. Additionally, now users are always prompted when retrieving items, not during copying any fields. Which should remove your frustration. Let me know how you feel.

**Comment by gshpychka** [comment]
> With the latest release, you can enable the "Auto Renew Authorization" background refresh, resulting in fewer biometric prompts. Additionally, now users are always prompted when retrieving items, not during copying any fields. Which should remove your frustration. Let me know how you feel.

With that setting enabled, I now get a biometrics prompt every ten minutes.

I don't mind getting a prompt when copying a password - the issue is that the password is not copied after I confirm my biometrics - I have to launch raycast again afterwards. Same with the new behavior - I now get prompet when the extension loads (instead of when the password is copied), but this closes raycast and I have to launch it again.

**Comment by Luk4h** [comment]
> With that setting enabled, I now get a biometrics prompt every ~ten minutes (maybe more?).

It should be at each 9 minutes. If for these 9 minutes the computer stays awake, it should not ask for a password. Can you confirm if on your 1Password config, it is set to lock after 10 or more minutes? Right now my auto lock is set to 4 hours. And lock on sleep enabled as well.

**Comment by gshpychka** [comment]
> > With that setting enabled, I now get a biometrics prompt every ~ten minutes (maybe more?).
> 
> It should be at each 9 minutes. If for these 9 minutes the computer stays awake, it should not ask for a password. Can you confirm if on your 1Password config, it is set to lock after 10 or more minutes? Right now my auto lock is set to 4 hours. And lock on sleep enabled as well.

Yeah I don't want random prompts out of nowhere. I am fine with getting a prompt when opening the extension or copying a password - I just don't want the extension to close after I confirm the prompt, so that I have to open it again.

**Comment by Luk4h** [comment]
I see, I recommend then you disabling the auto-renew command on the Raycast settings to stop these random prompts. I think have a fix in progress for this. But I will need you to wait a bit more, since it will include another commands I am working on.

**Comment by gshpychka** [comment]
> I see, I recommend then you disabling the auto-renew command on the Raycast settings to stop these random prompts. I think have a fix in progress for this. But I will need you to wait a bit more, since it will include another commands I am working on.

Of course, thank you

**Comment by jmabeebiz** [comment]
Hi, I wanted to jump in on this as I've been seeing the same issue for a while now, but it is a bit different.
In my set up, I have the auto-renew turned off, and I get two TouchID prompts every time I try to see a password, and then Raycast closes without the password copied. I then have to go back and get the password again.

**Comment by gshpychka** [comment]
> Hi, I wanted to jump in on this as I've been seeing the same issue for a while now, but it is a bit different. In my set up, I have the auto-renew turned off, and I get two TouchID prompts every time I try to see a password, and then Raycast closes without the password copied. I then have to go back and get the password again.

Yeah, that's the same issue.

**Comment by Luk4h** [comment]
I have a PR waiting on merge, for some improvements and fixes. Sadly I don't think it will have any impact on this issue, will wait on your feedback. If you can provide me what is your workflow I can maybe simulate it?

**Comment by jmabeebiz** [comment]
All good. I changed my workflow and added the extension back in Arc, no need for passwords as much in Raycast now.

Thanks,
// Justin Mabee
*Squarespace Designer | Available for Hire*
justinmabee.com ( http://justinmabee.com )
(267) 632-4103

Sent via Superhuman iOS ( ***@***.*** )

**Comment by gshpychka** [comment]
> I have a PR waiting on merge, for some improvements and fixes. Sadly I don't think it will have any impact on this issue, will wait on your feedback. If you can provide me what is your workflow I can maybe simulate it?

Sure! Just basically set the primary action to "Copy password" and try to use the plugin 10 minutes after last auth. Expected behavior: Auth prompt -> Password is copied. Actual beavior: Auth prompt -> Nothing happens. Have to launch the plugin again and repeat the process to actually copy the password.

**Comment by Luk4h** [comment]
With the latest update for the extension now, the biometric steps are invoked on extension start. Which solves this issue.

@raycastbot close this issue
