### ISSUE TITLE
[Zoom] Close a call

### ISSUE THREAD

**Issue by LucasJanin** [raycast/extensions#9016]
### Extension

https://www.raycast.com/raycast/zoom

### Description

It will be nice to close a call with Raycast

### Who will benefit from this feature?

When the user initiates a call and the people leave the room, the call doesn't close automatically.

**Comment by thomaslombart** [comment]
There's a separate extension to control your Zoom meeting. @prashantv you'll probably want to look at that.

**Comment by prashantv** [comment]
The zoom-control extension interacts with the Zoom client via menu items. Are you looking for a way to exit a meeting window? If there's a menu item option to do that, it'll be pretty easy to integrate
