### ISSUE TITLE
[Search Token] 

### ISSUE THREAD

**Issue by fajibfaaz7** [raycast/extensions#9020]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

The screenshot is attached below. Which shows the codes are corrupted. The tried to reinstall the extension, but it shows the same issue.
<img width="721" alt="image" src="https://github.com/raycast/extensions/assets/49675506/0a121642-f9da-49cc-bf54-fee93b91b1d8">

### Steps To Reproduce

1. Initially it's working fine
2. Try refreshing to get newly added codes
3. Then all codes become corrupted

### Current Behaviour

<img width="721" alt="image" src="https://github.com/raycast/extensions/assets/49675506/bffcc8c6-aac6-4848-895e-6063ad9b9c1b">

### Expected Behaviour

Needs to show the codes

**Comment by guga4ka** [comment]
@fajibfaaz7 check backup password, seems like it wrong

**Comment by leikoilja** [comment]
@guga4ka, i have been experiencing the same issue, it just says 'corrupted' and i cant do anything 
<img width="240" alt="image" src="https://github.com/raycast/extensions/assets/10655107/e868cfc4-27da-4de2-974f-5b81c8091722">

**Comment by guga4ka** [comment]
@raycastbot close this issue
