### ISSUE TITLE
[Calendar] Calendar misses zoom events at new zoom domain zoom-x

### ISSUE THREAD

**Issue by birnstiel** [raycast/extensions#9023]
### Extension

https://manual.raycast.com/calendar

### Description

Calendar / MySchedule no longer shows any Zoom meetings because most meetings now use a different URL that ends in zoom-x.de. This is a collaboration between Zoom and German Telecom to host servers in Germany and is now the default URL of most Companies/Universities/... in Germany. I think that the parser needs to include those URLs in addition to all other patterns (e.g. `*zoom.us`, `*zoom.gov`, `*zoom.com`, and so on).

### Steps To Reproduce

1. Add a valid Zoom Meeting link that uses the URL `https://zoom-x.de/j/[MEETINGID]`
2. Calendar / MySchedule will not show Zoom options to join the meeting.

### Current Behaviour

Zoom Meetings with the usual domain (e.g. `https://zoom.com/j/[MEETINGID]`) are shown, but the new domain is not showing up.

### Expected Behaviour

All valid Zoom Meeting URLs should be showing up in `Calendar` or `MySchedule`.

**Comment by sxn** [comment]
oh, I didn't know! Thanks for bringing this up, I'll make sure it's fixed in this week's release 🙏

**Comment by sxn** [comment]
should be fixed in 1.61.0, released yesterday 😺

**Comment by sxn** [comment]
should be fixed in the latest release (1.61.0) 🎉
