### ISSUE TITLE
Stack traceback may not correct

### ISSUE THREAD

**Issue by Gnosnay** [raycast/extensions#9030]
### Description

recently i receive the extension issue notification. it is as follows:
<img width="914" alt="image" src="https://github.com/raycast/extensions/assets/20450379/7564c62e-e2bf-4cd0-9bea-364cf2065a5d">

as you can see, the stack complains that `TypeError: Cannot read properties of undefined (reading 'length')`, but the related code is `const { cidrStr } = props.arguments;`

May i know the actual stacktrace?. Thank you

### Steps To Reproduce

Don't know how to reproduce

**Comment by mathieudutour** [comment]
cc @sxn

**Comment by sxn** [comment]
thanks for the report!

Yeah that stack trace isn't great, so we're looking into how we can improve it. I've created a ticket internally, and will close this one since this isn't an issue related to any one extension. 😺

**Comment by Gnosnay** [comment]
> thanks for the report!
> 
> Yeah that stack trace isn't great, so we're looking into how we can improve it. I've created a ticket internally, and will close this one since this isn't an issue related to any one extension. 😺

@sxn hi master, thank you so much for your efforts.
recently I met related issues again
<img width="889" alt="image" src="https://github.com/raycast/extensions/assets/20450379/38aa3c61-471d-40f2-86c0-1842ef355197">

May i know what the root cause of it actually?
