### ISSUE TITLE
Google Bard extension showing "Bard failed to connect"

### ISSUE THREAD

**Issue by estech321** [raycast/extensions#9038]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

I installed the Bard extension and carefully followed the steps to copy the key from Bard's cookies, double-checking I got the entire thing including the period. I even uninstalled the extension and tried starting from scratch again. However, I always receive the same error message, worded differently depending on my command. When opening "AI Chat," the window has the message "Bard Failed to Connect". When I enter a question anyway, I receive the message "Bard is still initializing". When I use any other command, it says "Unable to reach Bard at this time". 

Check the **Current Behavior** section for screenshots. Any help would be greatly appreciated.

### Steps To Reproduce

Follow the setup directions, and open any command. It may work for you, it may not. It's possible Google added some more security to Bard or something and that's why it doesn't work.

### Current Behaviour

<img width="300" alt="Bard_failed_to_Connect" src="https://github.com/raycast/extensions/assets/131488942/b2359c0f-df48-41b6-9cba-fc6552e41dd5">\
 AI Chat ↑
<img width="300" alt="Unable_to_reach_Bard" src="https://github.com/raycast/extensions/assets/131488942/bf23b4c5-5fc4-41ae-8737-fcdcbca443be">\
Anything Else ↑

### Expected Behaviour

I expect the "AI Chat" tab to let me chat with Bard and the others to do as their title describes.

**Comment by Mattyy94** [comment]
I have the same issue, just added this extension and followed the steps to. setup the connection. But isn't possible anymore?

**Comment by awcm0n** [comment]
Same here. Not working.

**Comment by cwill-dev** [comment]
It is not working for me either.

**Comment by InitPatch** [comment]
Sorry for spamming, but same problem here. I followed the instructions regarding the key, but then I got the same message "Bard failed to connect". I even restarted Raycast to see if it would make a difference, but no.

**Comment by Fenc3s** [comment]
I'm experiencing the same issue.

**Comment by xsbchen** [comment]
#9798 I created a PR for fix this, plz help to try
