### ISSUE TITLE
Rename Devices + Reorder

### ISSUE THREAD

**Issue by stuvrt** [raycast/extensions#904]
# Extension – [Set Audio Device](https://github.com/raycast/extensions/tree/52f3b0b58307a470ef49197f963773814e085b44/extensions/audio-device/)
Author: @benvp

**Describe the feature and the current behavior/state.**
> ⚠️  Both requests apply to both commands in the extension.

Currently, you can just select the device. Some of those devices have unclear names. 

It would be great to customise the device name, so it's bespoke to the user. In my case, `External Headphones` are in fact my speakers plugged in to the headphone jack. I'd like to rename it something like `Speakers`.

I would also like to move the devices around to order in a way that is to my preference. I don't ever use the LG monitor for either speakers or microphone, but for some unclear reason, they comes first.

![CleanShot - CleanShot - 14022022 - 05 58 06 PM](https://user-images.githubusercontent.com/17166544/153920223-51abe7af-271c-4995-a2cf-9adeb766cee2.png)

**Who will benefit with this feature?**
Everyone.

**Any Other info.**
No.

**Comment by benvp** [comment]
Interesting addition. Do you have an idea how we could persist the user data? Is there any way in the Raycast api build in for such use cases?
