### ISSUE TITLE
[Obsidian] ...

### ISSUE THREAD

**Issue by AMGMNPLK** [raycast/extensions#9043]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:405:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

### Steps To Reproduce

Searching notes

### Current Behaviour

Doesn't return results

**Comment by AMGMNPLK** [comment]
Is this issue solved? Thank you

**Comment by KevinBatdorf** [comment]
Do you still see the error? The extension needs to rewrites to manage memory a bit better, but I'm looking into ways to add some tests first so I can safely make larger updates like this. 
I suspect you have a lot of notes right?

**Comment by AMGMNPLK** [comment]
Hi Kevin,

Yes, I still get it. I have around 5000 notes.
