### ISSUE TITLE
[ChatGPT] ...

### ISSUE THREAD

**Issue by panosfrantzis** [raycast/extensions#9050]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

error 401

### Steps To Reproduce

mac os Sonoma

**Comment by micwaab** [comment]
Having the same issue.

**Comment by micwaab** [comment]
UPDATE: I created a new API in my OpenAI account and used it to update my Raycast ChatGPT ext. Now it is working as expected.

**Comment by panosfrantzis** [comment]
> UPDATE: I created a new API in my OpenAI account and used it to update my Raycast ChatGPT ext. Now it is working as expected.

i am using also new API

**Comment by panosfrantzis** [comment]
UPDATE: Today i get a new message that "you have reached your APi limit: please upgrade to pay as you go"
