### ISSUE TITLE
[Wikipedia] unable to get local issuer certificate

### ISSUE THREAD

**Issue by Maplerxyz** [raycast/extensions#9054]
### Extension

https://www.raycast.com/vimtor/wikipedia

#### Error:
```
Error: unable to get local issuer certificate

ClientRequest.<anonymous>:index.js:789:106

---
786:             this._aborted = true

### Steps To Reproduce

1. Open raycast
2. Press enter on featured page wikipedia

### Current Behaviour

_No response_

### Expected Behaviour

N/A

**Comment by menahishayan** [comment]
This is a network error. Reconnect to a more stable network and it should fix itself

**Comment by Ek2100** [comment]
@raycastbot rename this issue to "[Wikipedia] unable to get local issuer certificate"

**Comment by Ek2100** [comment]
Yep. As menahishayan stated, this is a network issue. I have seen this error before and it seems to be an issue with restrictive networks.

**Comment by menahishayan** [comment]
@raycastbot close this
