### ISSUE TITLE
[WhatsApp] WhatsApp deletes all recorded contacts and groups data

### ISSUE THREAD

**Issue by izabelacborges** [raycast/extensions#9059]
### Extension

https://www.raycast.com/vimtor/whatsapp

### Description

WhatsApp extension keeps losing or deleting the recorded Contacts and Group-chats data every few days, making me have to input it all over again. It does not necessarily have a specific behaviour or something that happens before it that makes all Contacts/Groups vanish from the list, I can be using it intermittently through the day and from one use to another I'll lose all the records I've had put there before.

### Steps To Reproduce

MacBook Pro M1, 16GB Memory, macOS Sonoma 14.0, Raycast 1.60.1

1. Add all contacts and groups to the extension
2. Configure shortcut control+W to open chats
3. Use the shortcut to open chats throughout the day
4. Every couple of days the list of contacts is empty and I need to add it all again

That self-deletion of the inputted data happened 3 times over the last week.
There were no new extensions or apps downloaded to the computer and I couldn't find anything that might be interfering with the extension's behaviour.

**Comment by vimtor** [comment]
I suspect this might be related to Raycast clearing the local storage to free up memory. I don't know if that is how it works, though. I don't use the extension a lot, but checking it now, it retained the contact data properly, so I'm a little confused about the reason.

Perhaps you can shed some light on this, @pernielsentikaer?
