### ISSUE TITLE
Can't run the `Create extension`command

### ISSUE THREAD

**Issue by jeroenvanrensen** [raycast/extensions#9063]
### Description

When I type "Create extension", I can't run the command:
![Scherm­afbeelding 2023-11-01 om 17 41 33](https://github.com/raycast/extensions/assets/46967616/33bad4cd-7edd-4193-91a1-aa4a94213476)

### Steps To Reproduce

1. Sign in to an account
2. Type "Create extension"

### Current Behaviour

The "Create extension" command doesn't show up.

### Expected Behaviour

The "Create extension" command should show up.

**Comment by erics118** [comment]
I think you may have these commands disabled. Can you go to settings and take a look?
It should look something like this:
![CleanShot 2023-11-08 at 20 33 42](https://github.com/raycast/extensions/assets/52634785/87e81195-d5c8-44af-8eb9-83754346b262)

**Comment by jeroenvanrensen** [comment]
That was the problem indeed! Thank you!
