### ISSUE TITLE
[Browser Bookmarks] bookmarks without names are no longer returned

### ISSUE THREAD

**Issue by daniellacoste** [raycast/extensions#9079]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

Chrome has support for bookmarks without Names:
<img width="191" alt="image" src="https://github.com/raycast/extensions/assets/11893695/4fb9373f-a1ba-4308-893a-0bda984d266c">
<img width="434" alt="image" src="https://github.com/raycast/extensions/assets/11893695/1fa44a08-34b9-4378-adae-8c5087bcd249">

Previously, this Raycast extension used to be able to return results for bookmarks without names (e.g. `calendar.google.com` above). Now, it does not return any results:
<img width="794" alt="image" src="https://github.com/raycast/extensions/assets/11893695/83b30142-f18d-45ac-ada4-c8fbba8fa06d">

### Steps To Reproduce

[in Chrome,]
1. Create a bookmark w/o a name
2. Open Browser Bookmarks extension
3. Search for an element of the URL from (1) (in my example, `calendar` which is part of `calendar.google.com`)
4. Observe the empty results (expected to return `calendar.google.com`)

### Current Behaviour

See (4) above

### Expected Behaviour

At step (4), expected behavior is to see the results for the `calendar.google.com` (nameless) bookmark

**Comment by thomaslombart** [comment]
Caused by #8936. @third774 could you take a look?

**Comment by third774** [comment]
PR is up! Sorry for the bug! 🫣

**Comment by daniellacoste** [comment]
no apologies necessary, thanks @third774 for the original fix and this quick second one!
