### ISSUE TITLE
[Search Zotero] Copy link to PDF

### ISSUE THREAD

**Issue by Erlendms** [raycast/extensions#9089]
### Extension

https://www.raycast.com/reckoning-dev/zotero

### Description

I like how the default behaviour (↩️ Return) in this extension is to open the PDF - **but I'd like to be able to copy that link as well. So something similar to _Copy Zotero URL to Clipboard_ (Shift+Cmd+C), but for the PDF link**.

Another neat thing would then be to be able to choose the default behaviour (as I would pick _Copy Link to PDF_ if I could. ☺️) - but that might be more complicated!

Thanks. 🙂

-Erlend 

### Who will benefit from this feature?

In Zotero 7, as the extension support is poor at the moment, it's very hard to actually get the links to the PDFs for some reason. So this would be useful for those of us who jumps between different apps, but likes to keep the canonical PDFs and annotations in Zotero.

**Comment by sadanand-singh** [comment]
which PDF link you want to copy? currently, "open PDF" command uses `zotero://` url schema provided by zotero. Not sure how that will be useful to someone.

If you could explain with some example, I can try to find a solution.

**Comment by Erlendms** [comment]
Yeah, that's precisely the URL I'd like! ☺️

Here's my use case:
I'm working in my Outline app, and then I have a list of "important sources for this topic". There I'd like to paste the links to the PDFs, so that if I click it, I'll go straight to the PDF in Zotero.

So everything is locally on my Mac.

Makes sense? 🙂

**Comment by Erlendms** [comment]
Hurray! 🙌🏻
Yeah, I assumed it was possible, since you already had it available "under the Return key". ☺️

Speaking of: What do you think of the idea of being able to choose a default action in the extension settings?

I'm thinking you can present the list of actions that's not under Cmd+K, and the user can choose which of them to happen when they hit Return.

**Comment by sadanand-singh** [comment]
Sure such a way of doing default action is doable. ButI feel its little hacky. I have been awaiting for some update in API itself to provide such an option.

**Comment by sadanand-singh** [comment]
can be closed now
