### ISSUE TITLE
Github Menubar Command always error with alert icon

### ISSUE THREAD

**Issue by sor4chi** [raycast/extensions#9097]
### Extension

https://www.raycast.com/raycast/github

#### Error:
```
TypeError: Cannot read properties of null (reading 'number')

Bue:open-pull-request-menu.tsx:53:4

---
50:   const { github } = getGitHubClient()

### Steps To Reproduce

It happened as soon as I rebooted, so there was no particular step, just an error displayed in the menu bar command.

### Current Behaviour

Error mark appears in the menu bar.

### Expected Behaviour

The number of Pull Requests should display properly.

**Comment by sor4chi** [comment]
@raycastbot rename this issue to "Github Menubar Command always error with alert icon"

**Comment by aeorge** [comment]
Could this be related to the GitHub [incident](https://www.githubstatus.com/incidents/xb30mby9fs5x) from yesterday? Are you still experiencing this issue?

**Comment by sor4chi** [comment]
Hi, @aeorge 
I don't think it matters, it keeps happening again now.

**Comment by thomaslombart** [comment]
We've started seeing a spike of errors which is correlated to the GitHub incident @aeorge is talking about. GitHub sent corrupted data during that time (looking at the error, something like `[null, null, …]`) which has been stored into cache since then. I'll fix it soon.
