### ISSUE TITLE
[Apple Reminders]  no notifications from the native Reminder app

### ISSUE THREAD

**Issue by makkish** [raycast/extensions#9105]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Hi,

Just installed this extensions when I saw that the old one no longer was supported.

I noticed one issue with this one, no notifications appears. I've only used the "Create Reminder". I can see the reminder in the native Reminders app, on all my Apple devices, but no notification appear. The permission seems to be correct since the reminder is added, I also verified in settings.

I've tried with restarting the Mac and reinstalling the extension without any success. I've tried on both Mac Mini and a Macbook.

Thanks!

### Steps To Reproduce

1. Add a reminder in Raycast with _Create Reminder_
2. Confirm it's added in the native Reminder app
3. When the reminder supposed to show with a notification, nothing shows. It's just red in the Reminder app

### Current Behaviour

No notifications are showing, e.g on Mac nor iPhone, when the reminder is due. The reminder is added though.

### Expected Behaviour

Show notifications when reminder is due, like the native Reminder app.

**Comment by thomaslombart** [comment]
Did you get any notifications at all with the old extension? I don't remember getting any notifications with it 🤔

**Comment by makkish** [comment]
Yes I did, just like it was added through the native app 😊

**Comment by thomaslombart** [comment]
Could you send a screenshot of the notification you're getting?

**Comment by makkish** [comment]
Can I install the old extension somehow? I uninstalled it on both my Macs unfortunately.

**Comment by thomaslombart** [comment]
You can't unfortunately 😬
I'll investigate that anyway. Thanks for the feedback!

**Comment by makkish** [comment]
Thank you very much

**Comment by dchmurec** [comment]
I can confirm the same behavior on my side as well. The reminder appears in Reminders, but when the time comes to 'remind,' it doesn't send any notifications to my Mac, phone, or Apple Watch. The reminder itself remains in red color, just as makkish described.
