### ISSUE TITLE
markdown links inside List.Item.Detail are not rendered correctly

### ISSUE THREAD

**Issue by gobear6212** [raycast/extensions#9110]
### Description

After the latest update, links passed into the markdown property of `List.Item.Detail` aren't rendered correctly. They are rendered as text instead of links in the item view.

### Steps To Reproduce

1. Follow the example from [List - Raycast API](https://developers.raycast.com/api-reference/user-interface/list#list.item.detail) to create a list item
2. Follow the example to pass `<List.Item.Detail markdown="![Illustration](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png)" />` as the detail
3. The image is rendered properly when viewed inside Raycast
4. Modify the last line and pass `<List.Item.Detail markdown="[Illustration](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png)" />` as link instead (without `!`)
5. The link is not rendered correctly when viewed inside Raycast

### Current Behaviour

Markdown links are rendered as normal text

### Expected Behaviour

Markdown links should be rendered as clickable links which is opened in the browser when a user clicks on it

**Comment by mathieudutour** [comment]
Ah yep, I'll fix it
