### ISSUE TITLE
[Timers] Dismiss timer throws an error

### ISSUE THREAD

**Issue by raulfdm** [raycast/extensions#9111]
### Extension

https://www.raycast.com/ThatNerd/timers

#### Error:
```
Error: ENOENT: no such file or directory, unlink '/Users/raulmelo/Library/Application Support/com.raycast.macos/extensions/be268af3-1b74-491e-ba09-da66a11e5d5c/2023-11-05T11__13__42.362Z---1500.dismiss'

unlinkSync:node:fs:1883:3
Object.$:dismissTimerAlert.js:1:1775
```

### Steps To Reproduce

1. set a timer;
2. opens raycast;
3. search for. "Dismiss tiem alert"
![CleanShot 2023-11-05 at 10 53 57@2x](https://github.com/raycast/extensions/assets/12464600/750e41b3-7ecd-4c28-b35b-c879074fe1e3)

### Current Behaviour

timer keeps running

### Expected Behaviour

dismiss the timer

**Comment by ThatNerdSquared** [comment]
Hi @raulfdm, thanks so much for opening this issue - I've seen this error come up in logs and have been trying to fix it for months now.

"Dismiss Timer Alert" is actually meant to be used with the "Ring Continuously" preference - if that preference is enabled, once a timer is finished, the alert sound plays repeatedly until the timer is deleted or this "Dismiss Timer Alert" command is run. It's not actually meant to stop a running timer, although I can see now why that might have been confusing 😅 

I can reproduce this on my end, so I'll be adding error handling for this (and adding a command to stop the currently running timer) shortly.

Once again, thanks so much for this issue, I wasn't able to repro this before but I guess I never thought about this use case 😅
