### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by crbon** [raycast/extensions#9115]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

Occasionally Raycast becomes non-responsive, when using the YouTube Downloader extension to download YouTube videos.

### Steps To Reproduce

1. Get YouTube video link - [https://www.youtube.com/watch?v=rTgj1HxmUbg](https://www.youtube.com/watch?v=rTgj1HxmUbg)
2. Let plugin auto input link from clipboard or paste into URL field
3. Select Format - Audio 128kps
4. Start - 'Download Audio'

### Current Behaviour

Occasionally crashes Raycast.
Noticed it happens more with longer videos 

### Expected Behaviour

Don't crash Raycast

**Comment by vimtor** [comment]
Hi @crbon!

When you say "crashes Raycast," do you mean it displays an error toast or it actually crashes and requires you to reopen it? If it's the latter, I'm unsure about the possible cause. I would need assistance from a member of the Raycast team.

**Comment by crbon** [comment]
No error message from the extension or Raycast. They both become unresponsive, unable to open Raycast, and when hovering over the little notification pebble it just shows the spinning beachball. Have to force quit Raycast to get this back to normal usually.

**Comment by vimtor** [comment]
In that case, I don't know what I could do, to be honest. Maybe @pernielsentikaer can shed some light on the issue?
