### ISSUE TITLE
[Password Generator] Improve UI and add options

### ISSUE THREAD

**Issue by rafaell-lycan** [raycast/extensions#9121]
### Extension

https://www.raycast.com/joshuaiz/password-generator

### Description

First of all thanks @joshuaiz for this lifesaver extension.

I'd like to suggest 2 small enhancements that might be handy for everyone and the overall XP when using this extension.

#### 1. Changing the options:

- Uppercase
- Lowercase
- Numbers
- Symbols

#### 2. Improve the password length:

Also, I don't know how to improve the size input, but it would be nice to use something like an input `range` as well from a minimum of 4-6 up to 50-100 characters.

#### References

- https://1password.com/password-generator/
- https://www.lastpass.com/features/password-generator
- https://www.dashlane.com/features/password-generator
- https://bitwarden.com/password-generator/

### Who will benefit from this feature?

Everyone interested in generating passwords.

### Anything else?

Again, thanks for making this extension happen.

**Comment by joshuaiz** [comment]
@rafaell-lycan These are great suggestions. I'd like to add memorable passwords as well. 

I'll try to add these when I can although no ETA as of now.
