### ISSUE TITLE
[Apple Notes] Not working since Sonoma

### ISSUE THREAD

**Issue by jiserra** [raycast/extensions#9122]
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

Since updating to Sonoma, the extension hasn't been working. If I try the "Search Notes" command, it comes back with an error of "database disk image is malformed".

### Steps To Reproduce

1. With Mac OS Sonoma 14.0
2. Run the command "Search Notes"

### Current Behaviour

An error is returned with "database disk image is malformed"

### Expected Behaviour

A list of notes to search

**Comment by simonemargio** [comment]
Same for me. 

Searching through the issues it seems to be a common problem:
#8910 
#8734 
#8004 
#8363 
#6631 
#6916 
#5619

**Comment by adidoes** [comment]
I ran into this issue as well, not sure how to help fix it

**Comment by israelg99** [comment]
I have the same issue with some extensions. Likely originating from sqlite.

**Comment by ashrithps** [comment]
Has there been any solution to this?

**Comment by eleventhaus** [comment]
also facing the same issue
