### ISSUE TITLE
API: Date picker's NLP doesn't understand a month followed by a day (e.g Jan 10)

### ISSUE THREAD

**Issue by upviral** [raycast/extensions#9131]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Let's say I want to create a reminder on January 10, so I write "Jan 10". This used to work. However, it now picks a completely random date.

See the following GIF: 

![From Wilco 2023-11-07 at 14 22 12](https://github.com/raycast/extensions/assets/12424149/6642f01f-f7e3-41e4-95ff-8fb4c5c7b380)

Even when I write "January 10", it still doesn't work, see :
![From Wilco 2023-11-07 at 14 24 26](https://github.com/raycast/extensions/assets/12424149/41342fba-9a4b-4dd5-b1e8-1d0d147edaa6)

### Steps To Reproduce

1. Start creating a new reminder
2. In the Due Date, enter "Jan 10" (alternatively, I've tested "January 10" - which also doesn't work).
3. You'll see it recommends "tomorrow" instead of January 10. 

### Current Behaviour

Currently, it'll create the reminder with "tomorrow" as the due date.

### Expected Behaviour

The expected behavior is that it creates a reminder on January 10.

**Comment by thomaslombart** [comment]
Thanks for reporting the issue. It's actually not an Apple Reminders bug, but a date picker bug. What's happening under the hood is that when the date picker doesn't have any results to return, it defaults to the very next date you could use. If you try "10 Jan", the date picker should return January 10th. So, it seems we need to make some improvements to the date picker's NLP.

I'm updating the issue's title.

**Comment by mathieudutour** [comment]
That's fixed now
