### ISSUE TITLE
[Tapo Smart Devices] ...

### ISSUE THREAD

**Issue by baptistechretien** [raycast/extensions#9132]
### Extension

https://www.raycast.com/timrogers/raycast-tapo-smart-devices

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:405:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

### Steps To Reproduce

Unable to get the extension to work. The authentication is successful, but an error message appears when searching for devices.

**Comment by timrogers** [comment]
@baptistechretien Thanks for reaching out! How many Tapo devices do you have, out of interest?

**Comment by timrogers** [comment]
@baptistechretien Just a reminder about the above question 🆙
