### ISSUE TITLE
[TickTick] unable to connect to TickTick to Fetch or Add tasks

### ISSUE THREAD

**Issue by YashashGaurav** [raycast/extensions#9134]
### Extension

https://www.raycast.com/appest/ticktick

### Description

Whenever I try and add a task or look at today's tasks the Raycast extension shows an error banner as below.

I reinstalled ticktick to make sure I have the latest version of the app too. 

![image](https://github.com/raycast/extensions/assets/7768011/359b2f90-2daf-4666-8060-05530ea553c7)

### Steps To Reproduce

1. Open Raycast with this extension installed and enabled. 
2. Try fetching tasks for Today 

### Current Behaviour

Shows and error banner and I cannot view or add tasks

### Expected Behaviour

To allow to add and view tasks.

**Comment by viduycheung** [comment]
Are you install TickTick macOS App? The function is based on the native App.

**Comment by YashashGaurav** [comment]
Yup tried with the TickTick app installed from the Apple App store and from your website too! Didn't work in both cases.

Here are the app's About dialog: 

<img width="330" alt="image" src="https://github.com/raycast/extensions/assets/7768011/928598dc-cc54-44a6-a994-d99ce3d90d07">

**Comment by viduycheung** [comment]
Could you please record a video of your operation? This function seems to be working correctly on my end.
