### ISSUE TITLE
[ChatGPT Quick Actions] Support More Custom Action

### ISSUE THREAD

**Issue by Crayon-ShinChan** [raycast/extensions#9135]
### Extension

https://www.raycast.com/alanzchen/chatgpt-quick-actions

### Description

<img width="1112" alt="image" src="https://github.com/raycast/extensions/assets/38809606/4ed968c9-5e5a-40c2-b10b-3f3589e7a3af">
Now, [ChatGPT Quick Actions](https://github.com/raycast/extensions/tree/631a9a01a2e596eb77deb7e737959520253ba258/extensions/chatgpt-quick-actions/) supports one custom action. But what if I want to set multiple custom actions simultaneously?

### Who will benefit from this feature?

This would unlock the extension's large potential. People can do lots of quick action with unlimited customized prompts

**Comment by Crayon-ShinChan** [comment]
https://zenan.ch/blog/gpt-on-mac

I checked this, seems need to change the source code to add more custom action for now

**Comment by alanzchen** [comment]
Thanks for bringing this up. This is currently impossible with the Raycast API.

@raycastbot close this issue
