### ISSUE TITLE
[Deepcast] ...Transliterated translation for special characters 

### ISSUE THREAD

**Issue by RihardsVeters** [raycast/extensions#9136]
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

I'm adding reminder for @erics118 about transliterated text for translation. As we spoke I would love to be able to copy Russian transliterated text, for example 
English: My name is Rihards
Russian: Меня зовут Рихардс
Transliterated Russian: Menya zovut rihards

### Who will benefit from this feature?

Everyone who is translating something to Russian language and using transliterated version for something, e.g. for URLs

**Comment by erics118** [comment]
@RihardsVeters I've added an option in the extension settings to completely switch over to using transliterated text. What do you think?

![CleanShot 2023-11-15 at 22 41 36](https://github.com/raycast/extensions/assets/52634785/576509c9-37cb-424d-8285-8a34cdb8d661)

**Comment by RihardsVeters** [comment]
@erics118 Not best case scenario, because I also need not transliterated text for page Title, h1 etc. Maybe it's better to just add another shortcut for ability to copy transliterated text? Just as another developer did for Google translate extension?
https://github.com/raycast/extensions/issues/9260

**Comment by erics118** [comment]
Ok, I changed it to be like google-translate. Is this what you're looking for? It only shows the transliteration if it differs from the original translation.

![CleanShot 2023-11-16 at 18 38 49](https://github.com/raycast/extensions/assets/52634785/0c1f7f8f-d438-4a5d-8c1d-d83463876117)

**Comment by RihardsVeters** [comment]
Yeah that is what I'm looking for ;) Thanks. Waiting for it to be pushed on live.
