### ISSUE TITLE
[Obsidian] Searching the content of notes in Obsidian

### ISSUE THREAD

**Issue by WheheoHu** [raycast/extensions#9140]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

Just like [OminiSearch](https://github.com/scambier/obsidian-omnisearch) plugin inside obsidian .

### Who will benefit from this feature?

Every Obsidian and Raycast user

**Comment by KevinBatdorf** [comment]
Sorry for the late reply. Do you have this checked?

![CleanShot 2023-11-19 at 13 04 35](https://github.com/raycast/extensions/assets/1478421/017ca286-47bd-4082-b4af-f01cfffe213b)

In this case it will search the content as well as the title

**Comment by WheheoHu** [comment]
> Sorry for the late reply. Do you have this checked?
> 
> ![CleanShot 2023-11-19 at 13 04 35](https://private-user-images.githubusercontent.com/1478421/284080422-017ca286-47bd-4082-b4af-f01cfffe213b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTE0MDAsIm5iZiI6MTcwMzE1MTEwMCwicGF0aCI6Ii8xNDc4NDIxLzI4NDA4MDQyMi0wMTdjYTI4Ni00N2JkLTQwODItYjRhZi1mMDFjZmZmZTIxM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMDkzMTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZiOTZlZDZjMTdiZTEyOGQxOWViMTU1YmQ3MzUyYWMzNzUxOGU1ZDI2ZTAyNDJiNmJmODkyMmM2MzQ1NDQ5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-AdzeUkO8_5G3nDugGIu0bwXdgkqN_tF4fMD0yzMLPE)
> 
> In this case it will search the content as well as the title

Thank u for reply, it works!

**Comment by WheheoHu** [comment]
> Sorry for the late reply. Do you have this checked?
> 
> ![CleanShot 2023-11-19 at 13 04 35](https://private-user-images.githubusercontent.com/1478421/284080422-017ca286-47bd-4082-b4af-f01cfffe213b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTE0MDAsIm5iZiI6MTcwMzE1MTEwMCwicGF0aCI6Ii8xNDc4NDIxLzI4NDA4MDQyMi0wMTdjYTI4Ni00N2JkLTQwODItYjRhZi1mMDFjZmZmZTIxM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMDkzMTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZiOTZlZDZjMTdiZTEyOGQxOWViMTU1YmQ3MzUyYWMzNzUxOGU1ZDI2ZTAyNDJiNmJmODkyMmM2MzQ1NDQ5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-AdzeUkO8_5G3nDugGIu0bwXdgkqN_tF4fMD0yzMLPE)
> 
> In this case it will search the content as well as the title

Thank u for reply,it works
