### ISSUE TITLE
[GitHub] Cannot open Notification in browser 

### ISSUE THREAD

**Issue by AvishkaUmesh** [raycast/extensions#9142]
### Extension

https://www.raycast.com/raycast/github

### Description

This is about Notification command. 

When I select a notification from the list and select open in browser command. I get below response in the browser

{
  "message": "Requires authentication",
  "documentation_url": "https://docs.github.com/rest/activity/notifications#get-a-thread"
}

### Steps To Reproduce

1. I have create a token from given link in the readme. 
2. Select Notification command
3. Select a notification to open in browser 
4.  getting this response {
  "message": "Requires authentication",
  "documentation_url": "https://docs.github.com/rest/activity/notifications#get-a-thread"
}
And other command works fine no issues with them. Tried using Oauth also but the same bug occurred.

**Comment by thomaslombart** [comment]
Could you share a recording? It'll be easier to see what's happening.

**Comment by AvishkaUmesh** [comment]
https://github.com/raycast/extensions/assets/76151266/f862e65c-4be2-4620-946e-a1542c8548bf
