### ISSUE TITLE
Screenshot not showing up on the site mentioned below. 

### ISSUE THREAD

**Issue by trace2798** [raycast/extensions#9145]
### Description

Hey. The screenshot is not showing up on this route: https://www.raycast.com/thomas/spotify-controls

What I see: ![image](https://github.com/raycast/extensions/assets/113078518/f43aa559-3958-445d-b0a5-5e66f516f23d)

Expected: For the screenshot to show.

@thomaspaulmann

**Comment by codrkoaz** [comment]
did you figure out the problem?
