### ISSUE TITLE
Access the latest GPT4.0-Turbo API

### ISSUE THREAD

**Issue by Holeuang** [raycast/extensions#9146]
### Description

has an updated knowledge cutoff of April 2023 and introduces a 128k context window (the equivalent of 300 pages of text in a single prompt). 

### Who will benefit from this feature?

I would be happy to subscribe to pro for a year if I could use GPT4.0Turbo

**Comment by gandalfsaxe** [comment]
I thought they were missing as well at first, but the GPT-4 Turbo models are actually there just under these names :)


<img width="1647" alt="image" src="https://github.com/raycast/extensions/assets/12127864/39c00d91-5b47-4bd5-a38f-f479d683c1f1">

**Comment by Holeuang** [comment]
hey,I have a question, how do I open gpt-4-turto?[image: image.png]

Gandalf Saxe ***@***.***> 于2023年11月23日周四 20:51写道：

**Comment by Holeuang** [comment]
> @Holeuang 您需要在扩展程序的首选项中粘贴 OpenAI API 密钥，并且需要向帐户添加资金 - 目前这不是免费的，而且它甚至不包含在 ChatGPT Plus 订阅中。要使用 GPT-4 Turbo，请`gpt-4-1106-preview`从列表中进行选择。

open ai is not serving China, so there is no way to be funds added to the account

**Comment by logancyang** [comment]
> I thought they were missing as well at first, but the GPT-4 Turbo models are actually there just under these names :)
> 
> <img alt="image" width="1647" src="https://private-user-images.githubusercontent.com/12127864/285211348-39c00d91-5b47-4bd5-a38f-f479d683c1f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTM0NDcsIm5iZiI6MTcwNTQ1MzE0NywicGF0aCI6Ii8xMjEyNzg2NC8yODUyMTEzNDgtMzljMDBkOTEtNWI0Ny00YmQ1LWEzOGYtZjQ3OWQ2ODNjMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAwNTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZTJhODE5ZTU4MDBmZjQ3OGVhYTdhMDFmMDAzNTg2YmMwOGNiOWU3MmQ3OGZjNjRiMTdmZDU5MmQ0NDZkMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TlYGJheZ5eehZTDEqnwot9VKhcl4vuBz8jYTml9SL-c">

I do have GPT-4-TURBO API access and am able to use it with other clients, but I do not see all the options as in your screenshot. I only see 2 gpt-3.5 options. Why?

**Comment by bxb100** [comment]
> I do have GPT-4-TURBO API access and am able to use it with other clients, but I do not see all the options as in your screenshot. I only see 2 gpt-3.5 options. Why?

Can you access the OpenAI API and check if there is a GPT-4 related model available?[^1]

```shell
curl https://api.openai.com/v1/models \
  -H "Authorization: Bearer $OPENAI_API_KEY"
```


[^1]: https://platform.openai.com/docs/api-reference/models/list

**Comment by logancyang** [comment]
@bxb100 yes

```
{
  "object": "list",
  "data": [
    {
      "id": "curie-search-query",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "gpt-4",
      "object": "model",
      "created": 1687882411,
      "owned_by": "openai"
    },
    {
      "id": "babbage-search-query",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "dall-e-3",
      "object": "model",
      "created": 1698785189,
      "owned_by": "system"
    },
    {
      "id": "babbage-search-document",
      "object": "model",
      "created": 1651172510,
      "owned_by": "openai-dev"
    },
    {
      "id": "dall-e-2",
      "object": "model",
      "created": 1698798177,
      "owned_by": "system"
    },
    {
      "id": "gpt-3.5-turbo-0301",
      "object": "model",
      "created": 1677649963,
      "owned_by": "openai"
    },
    {
      "id": "text-embedding-ada-002",
      "object": "model",
      "created": 1671217299,
      "owned_by": "openai-internal"
    },
    {
      "id": "gpt-4-0613",
      "object": "model",
      "created": 1686588896,
      "owned_by": "openai"
    },
    {
      "id": "davinci-search-query",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "gpt-4-1106-preview",
      "object": "model",
      "created": 1698957206,
      "owned_by": "system"
    },
    {
      "id": "tts-1-hd-1106",
      "object": "model",
      "created": 1699053533,
      "owned_by": "system"
    },
    {
      "id": "tts-1-hd",
      "object": "model",
      "created": 1699046015,
      "owned_by": "system"
    },
    {
      "id": "ada-search-document",
      "object": "model",
      "created": 1651172507,
      "owned_by": "openai-dev"
    },
    {
      "id": "ada-code-search-code",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "davinci-002",
      "object": "model",
      "created": 1692634301,
      "owned_by": "system"
    },
    {
      "id": "babbage-002",
      "object": "model",
      "created": 1692634615,
      "owned_by": "system"
    },
    {
      "id": "gpt-4-vision-preview",
      "object": "model",
      "created": 1698894917,
      "owned_by": "system"
    },
    {
      "id": "davinci-search-document",
      "object": "model",
      "created": 1651172509,
      "owned_by": "openai-dev"
    },
    {
      "id": "curie-search-document",
      "object": "model",
      "created": 1651172508,
      "owned_by": "openai-dev"
    },
    {
      "id": "ada-search-query",
      "object": "model",
      "created": 1651172505,
      "owned_by": "openai-dev"
    },
    {
      "id": "ada-code-search-text",
      "object": "model",
      "created": 1651172510,
      "owned_by": "openai-dev"
    },
    {
      "id": "gpt-3.5-turbo-16k-0613",
      "object": "model",
      "created": 1685474247,
      "owned_by": "openai"
    },
    {
      "id": "whisper-1",
      "object": "model",
      "created": 1677532384,
      "owned_by": "openai-internal"
    },
    {
      "id": "gpt-3.5-turbo-16k",
      "object": "model",
      "created": 1683758102,
      "owned_by": "openai-internal"
    },
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo-0613",
      "object": "model",
      "created": 1686587434,
      "owned_by": "openai"
    },
    {
      "id": "gpt-3.5-turbo-1106",
      "object": "model",
      "created": 1698959748,
      "owned_by": "system"
    },
    {
      "id": "gpt-3.5-turbo-instruct",
      "object": "model",
      "created": 1692901427,
      "owned_by": "system"
    },
    {
      "id": "gpt-3.5-turbo-instruct-0914",
      "object": "model",
      "created": 1694122472,
      "owned_by": "system"
    },
    {
      "id": "tts-1-1106",
      "object": "model",
      "created": 1699053241,
      "owned_by": "system"
    },
    {
      "id": "tts-1",
      "object": "model",
      "created": 1681940951,
      "owned_by": "openai-internal"
    }
  ]
}
```

**Comment by bxb100** [comment]
@logancyang Which plugin do you use? [chatgpt](https://www.raycast.com/abielzulio/chatgpt)?

**Comment by logancyang** [comment]
@bxb100 yes. I just reinstalled it and somehow I can see all the models now. Not sure why there was an issue before but anyways. Thanks for looking!

**Comment by bxb100** [comment]
@logancyang The problem happened while fetching model data lag entered the form view

https://github.com/raycast/extensions/assets/20685961/51f52ac3-cd2e-4022-80aa-74f1b614e9be

as the video shows, I will add a loading view to reduce this problem
