### ISSUE TITLE
[OneNote] Claims Onenote not installed when it is 

### ISSUE THREAD

**Issue by akivajackson** [raycast/extensions#9150]
### Extension

https://www.raycast.com/alewandowski/onenote

### Description

Claims Onenote not installed when it is 

### Steps To Reproduce

Installed extension, tried to run it, got error 
On latest version of the extension and raycast

Mac Sonoma 14.1.1
Apple M1 2020

**Comment by akivajackson** [comment]
This still doesn't work :(

**Comment by vlcinsky** [comment]
Still does not work. Please, reopen.

My attempts to resolve:
- restarted notebook (did not help)
- reinstalled the OneNote extension (with restarting RayCast) (did not help)
- reinstalled OneNote itself and reauthenticated - problem resolved (but it seems like it takes few seconds to catch with list of open notebooks)
