### ISSUE TITLE
[Installed Extensions] Uninstall action

### ISSUE THREAD

**Issue by third774** [raycast/extensions#9161]
### Extension

https://www.raycast.com/pernielsentikaer/installed-extensions

### Description

Would love if I could use `⌃X` to uninstall extensions from within the `List Installed Extensions` command list view! 🙏🏻

### Who will benefit from this feature?

Anyone who uses the extension and realizes they have certain ones they never use and want to uninstall?

**Comment by erics118** [comment]
I don't think there's an API for one extension to uninstall another extension, so I believe this isn't officially possible. There may be some hacky way to do it though

**Comment by third774** [comment]
Yeah, that makes sense. Maybe the built-in `Manage Extensions` command should also be able to list extensions installed from the store instead of just development extensions.

**Comment by pernielsentikaer** [comment]
Correct, that's not possible - I can see why it would be handy and we might add it in the revamped version of Raycast preferences 🙂
