### ISSUE TITLE
[JWT Decoder] Just shows a blank raycast screen. 

### ISSUE THREAD

**Issue by ggoforth** [raycast/extensions#9162]
### Extension

https://www.raycast.com/gdsmith/jwt-decoder

### Description

I copy a JWT, open raycast, select JWT Decoder and then nothing happens.  Just an empty screen.  Sometimes the right hand column shows, but not always. 

### Steps To Reproduce

1. Copy a JWT token 
2. open raycast
3. select jwt decode
4. assert nothing is shown.  

![2023-11-08 16 55 39](https://github.com/raycast/extensions/assets/1167712/ee43721e-a6a9-422e-8e1a-13a914bea3e0)

**Comment by zhhanging** [comment]
Hello, I have a pr to solve this issue, please check. https://github.com/raycast/extensions/pull/9442

**Comment by gdsmith** [comment]
@raycastbot close this issue
