### ISSUE TITLE
[Twilio's Authy] Some of my records are shown as corrupted

### ISSUE THREAD

**Issue by taehwakang** [raycast/extensions#9166]
### Extension

https://www.raycast.com/guga4ka/authy

### Description

![SCR-20231109-lyv](https://github.com/raycast/extensions/assets/66982381/5c58b8b3-0b02-4fac-a769-40cde62705b3)

Like above, some of my records are shown as corrupted.

I searched Q&As from https://www.raycast.com/guga4ka/authy this page and the Q&A says
```
Q: I got corrupted OTP for some of my records
A: That means the extension couldn't decrypt your OTP, pls submit a [GitHub issue]
```

### Steps To Reproduce

1. Mac OS Ventura 13.5, MacBook Pro M1 14-inch, 2021
2. Authy ID and password are set
3. Run Search Token action of Twilio's Authy extension
4. some of records are shown as corrupted

### Current Behaviour

some of records are shown as corrupted

### Expected Behaviour

all records should be shown normally

**Comment by guga4ka** [comment]
I would say that a backup password isn't correct. OTP that you see is a Authy native, like a twitch, pinterest etc. They all a 7 diggits. Check your password.

**Comment by taehwakang** [comment]
@guga4ka changed backup password and set it again fixed the issue. Thanks!
