### ISSUE TITLE
push and Action.Push add navigationTitle to change navigation title

### ISSUE THREAD

**Issue by chyroc** [raycast/extensions#917]
when use `push` or `Action.Push` to push new component to current page, the navigation title not change.

maybe can add `navigationTitle` props to change this

**Comment by anhthang** [comment]
@chyroc you can add `navigationTitle` in the target component. All the high-level components (List, Detail, Form) has it

https://developers.raycast.com/api-reference/user-interface

**Comment by mattisssa** [comment]
As written in the comment below it's possible by assigning a value into the `navigationTitle` prop for the screen,
