### ISSUE TITLE
Raycast Extension: Download Video Youtube : 🚨 Error: ﻿ffmpeg is not installed

### ISSUE THREAD

**Issue by DenQuizon** [raycast/extensions#9174]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

found installation instruction about homebrew but after copy and pasting the code in terminal no fix happened

### Steps To Reproduce

<img width="765" alt="Screenshot 2023-11-09 at 1 42 26 PM" src="https://github.com/raycast/extensions/assets/128210481/1268a79e-fdbd-4bd4-880d-904867f0826f">

**Comment by darmiel** [comment]
Can you re-open the terminal and type `which ffmpeg`?
If ffmpeg was installed, you should see a path (e. g. `/opt/homebrew/bin/ffmpeg`) - copy & paste this path into the extension settings under **ffmpeg Path**

**Comment by vimtor** [comment]
> Can you re-open the terminal and type `which ffmpeg`? If ffmpeg was installed, you should see a path (e. g. `/opt/homebrew/bin/ffmpeg`) - copy & paste this path into the extension settings under **ffmpeg Path**

Exactly! Also, please do the same with `ffprobe`. (Thanks, @darmiel ❤️)

**Comment by sjimmylin** [comment]
Have a intel version, so my path is under /usr/local/bin/ffmpeg. Even after updating the path in the extension setting, ffmpeg can not be found...

**Comment by vimtor** [comment]
> Have a intel version, so my path is under /usr/local/bin/ffmpeg. Even after updating the path in the extension setting, ffmpeg can not be found...

Can you check if your issue is similar to #9051?

**Comment by sjimmylin** [comment]
The solutions you wrote in the other thread did not work for me either. I haven tried manually installing ffmpeg though.

**Comment by vimtor** [comment]
If I understand correctly @sjimmylin, you are also getting an error when running `ffmpeg -version`?

**Comment by sjimmylin** [comment]
@vimtor It doesn't look like it. Here is the output:
<img width="567" alt="Screenshot 2023-11-27 at 17 11 46" src="https://github.com/raycast/extensions/assets/44523644/aaf89249-7a28-42cb-b0c0-ed8dca33bbd1">
