### ISSUE TITLE
[Apple Reminders] Support relative time in Quick Add Reminder command

### ISSUE THREAD

**Issue by jrddp** [raycast/extensions#9181]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Quick Add Reminder is an excellent feature and I'm glad to see it. However, the main use case I would have for it doesn't seem to work. I would typically want to add a reminder like the following examples:
- "Leave for class in 3 hours" or "leave for class in 3h" 
- "Check on the oven in 15 minutes" or "check on oven in 15m"

None of these seem to have the intended effect. If I set something like "check on the oven in 30 minutes", it does seem to set but at the wrong time. Specifically, it seems to always set for 12:30 AM in that case.

### Who will benefit from this feature?

Everyone that wants to use the quick add reminder to add reminders QUICKLY without needing to waste cognitive effort choosing a specific time.

**Comment by thomaslombart** [comment]
Indeed, adding reminders this way is broken. Thanks for reporting the issue.
