### ISSUE TITLE
[Music] ...we need 'search'

### ISSUE THREAD

**Issue by ssl13194222802** [raycast/extensions#9188]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

It would be better if I could use Raycast to search songs in apple music.Apple Music

**Comment by rawnly** [comment]
Unfortunately due to the current state of the implementation that's not possible at the moment. Search is available only via MusicKit API, I created a PR a while ago but i still have to implement the authentication server.

**Comment by rawnly** [comment]
See #6988
