### ISSUE TITLE
Matter error

### ISSUE THREAD

**Issue by amoyag** [raycast/extensions#9198]
### Description

Hi.
I got this error after setting up the extension:

TypeError: Cannot read properties of undefined (reading 'map')

pa:index.tsx:15:60

---
12: }
13: 
14: export default function Command() {
15:   const [isTokenValid, setIsTokenValid] = useState<boolean>(false);
16:   const [state, setState] = useState<State>({});
17:   // 1 = queue, 2 = favorites
18:   const [filter, setFilter] = useState<any>(1);
---

Fr:index.js:9:2490
    at ray-navigation-stack
Vo:index.js:9:2088

I really don't know if I got the right token, the instructions are not clear enough.

**Comment by mathieudutour** [comment]
This doesn't seem to be a API error. Can you open an extension issue instead: https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+...
