### ISSUE TITLE
[Downloads Manager] wanna select multiple items at once

### ISSUE THREAD

**Issue by nagauta** [raycast/extensions#9201]
### Extension

https://www.raycast.com/thomas/downloads-manager

### Description

I want to select multiple items at once because It will help when I copy & past items to another apps.

### Who will benefit from this feature?

anyone who use this extension

### Anything else?

I can contribute for this but I need investigate whether It can be selected multiply

**Comment by ron-myers** [comment]
@nagauta  - what would you see the Raycast command and UI interaction for this being?
