### ISSUE TITLE
[JetBrains Toolbox Recent Projects] shell script location problem

### ISSUE THREAD

**Issue by Lindsay0214** [raycast/extensions#9202]
### Description

Extension – [JetBrains Projects](https://github.com/raycast/extensions/tree/main/extensions/jetbrains)
Author: @gdsmith 

Hi, I faced the script path problem.

![截圖 2023-11-11 下午11 18 44](https://github.com/raycast/extensions/assets/56778568/53fca4c0-00ff-4db6-b39d-5aad3f2273ae)

![截圖 2023-11-11 下午11 18 29](https://github.com/raycast/extensions/assets/56778568/fb66a798-6de2-41ac-957f-3a84792f3ebe)

and I checked my permission, looks like I have the permission
I have no idea what's wrong, if need any context just tell me, thanks help

![截圖 2023-11-11 下午11 35 54](https://github.com/raycast/extensions/assets/56778568/00a50321-cd88-459b-b8f3-acd45e01ae2f)

### Steps To Reproduce

Computer: Mac Pro / M1 / MacOS Ventura 13.5
1. install raycast and [JetBrains Toolbox Recent Projects](https://www.raycast.com/gdsmith/jetbrains) extension
2. open raycast, use JetBrains command, and click Search Recent Projects

### Current Behaviour

![截圖 2023-11-11 下午11 18 44](https://github.com/raycast/extensions/assets/56778568/360e154a-a264-42ab-8910-160cf93f7098)

### Expected Behaviour

https://timdeschryver.dev/blog/enable-shell-scripts-for-the-jetbrains-toolbox-app

**Comment by mathieudutour** [comment]
This doesn't seem to be a API error. Can you open an extension issue instead: https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2Cbug&projects=&template=extension_bug_report.yml&title=%5BExtension+Name%5D+... so that the authors are properly aware of this?
