### ISSUE TITLE
[Notion] cannot find Raycast extension

### ISSUE THREAD

**Issue by stedmanblake** [raycast/extensions#9204]
### Extension

https://www.raycast.com/notion/notion

### Steps To Reproduce

Follow steps here:
https://github.com/raycast/extensions/blob/1def14244b6316e7986ce89daa4267ea480c3527/extensions/notion/README.md

### Current Behaviour

Actual: cannot find Raycast integration in Notion extensions

Video reproduction:
https://share.cleanshot.com/K6xwQbYL

### Expected Behaviour

Expected: see Raycast integration in the Notion extensions

**Comment by thomaslombart** [comment]
Are you actually logged to Notion in the Raycast extension? Are you also able to search or create pages? I can't see that in the recording.

**Comment by alexanderstoehr** [comment]
As I understood, you have to create your own integration within Notion to get the Notion Token:
<img width="530" alt="Screenshot 2023-12-02 at 00 49 06" src="https://github.com/raycast/extensions/assets/25031364/4b2f690c-47eb-48a2-b50e-d5814e0078dc">


Did not get it running yet, but might be another problem on my side.

**Comment by ollyde** [comment]
There's a step missing on the instructions where you need to "Sign in with Notion" Via Raycast

**Comment by domioanna** [comment]
Nevermind, found it after uninstalling and reinstalling the extension
