### ISSUE TITLE
[Text Shortcuts] ...

### ISSUE THREAD

**Issue by gygys** [raycast/extensions#9213]
### Extension

https://www.raycast.com/koinzhang/text-shortcuts

### Description

I need a function of text reverse order, I can't find how to implement it

**Comment by koinzhang** [comment]
This feature is not available at the moment.
What does text reverse order mean?
Is it reverse order by line or by letter?

**Comment by gygys** [comment]
For example, a string of characters "string," converted to "gnirts."

Hope you can add this function in the future, thank you.


> 在 2023年11月13日，10:24，koin ***@***.***> 写道：
> 
> This feature is not available at the moment.
> What does text reverse order mean?
> Is it reverse order by line or by letter?
>
