### ISSUE TITLE
[Bitwarden Vault] Biometric

### ISSUE THREAD

**Issue by marcomiche00** [raycast/extensions#9214]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Is it possible to add biometric login?

### Who will benefit from this feature?

Everyone

**Comment by jomifepe** [comment]
Hello, thanks for the suggestion. Multiple people have asked for this, and here's why it's not implemented yet: https://github.com/raycast/extensions/issues/8075#issuecomment-1694508921

**Comment by jomifepe** [comment]
Duplicate of #8075

**Comment by jomifepe** [comment]
@raycastbot close this issue
