### ISSUE TITLE
[Apple Reminders] I hope this plug-in can support adding tasks to today

### ISSUE THREAD

**Issue by silentiris** [raycast/extensions#9217]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

I hope this plugin can support adding tasks to today，now it can only add to a certain list which created by uslef.thanks

### Who will benefit from this feature?

everyone use this plugin

### Anything else?

i dont know why quick adding is also advanced feature and need a pro membership...

**Comment by thomaslombart** [comment]
It's already possible to add a reminder to today:

![CleanShot 2023-11-13 at 09 40 25@2x](https://github.com/raycast/extensions/assets/16003285/ecf7efa3-efde-4c7d-8869-2adf9804e8cd)

> i dont know why quick adding is also advanced feature and need a pro membership...

The command is using the AI, which is part of Raycast Pro, under the hood to provide NLP support.

**Comment by silentiris** [comment]
thank u dor u reply, my question has solved.
