### ISSUE TITLE
[Browser Bookmarks]...Tries accessing profile that doesn't exist

### ISSUE THREAD

**Issue by baswolting** [raycast/extensions#9220]
### Extension

https://raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: ENOENT: no such file or directory, scandir '/Users/Bas/Library/Application Support/Firefox/Profiles/xavewwd0.default'
    at readdirSync (node:fs:1527:3)
    at /Users/Bas/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:40:37319
    at Array.filter (<anonymous>)
    at D5 (/Users/Bas/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:40:37240)
    at async /Users/Bas/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:59:231
```

### Steps To Reproduce

1. Installed Browser Bookmarks while I had the original extension\
2. Only enable Firefox as a browser (not enabling Safari nor Google Chrome)
3. It produced this error from the start, never working correctly
4. After being forced to delete the deprecated Browser Bookmarks, I haven't been able to use the extension yet (a few weeks ago)

### Current Behaviour

When I open the browser bookmarks, it gives an error stating that the profile can not be found. If go to the directory where the profile(s) are located, there are four profiles. Three of them for the Firefox Developer edition, and one for the default release. None match the name of `xavewwd0.default` which is the profile somehow linked to the extension. If this profile existed, then it must have been months ago, because I installed this extension months ago and it has always produced this error.

The existing profile names, and whether they have any data, are as follows:

- 03dfvchh.dev-edition-default: empty
- 32x8eokh.default-release: populated with data
- 98yfj1b9.dev-edition-default-1678439485223: empty
- lglnqddq.dev-edition-default-1697551338297: populated with data

Things I've tried so far are:
- Uninstalling and re-installing the extension
- Disabling the Firefox browser in the bookmarks settings, then re-enabling it
- Disabling and re-enabling other browsers (the issue does not exist with Chrome)
- Re-creating the folder (`xavewwd0.default` in the Firefox/Profiles directory) that is trying to be accessed, which partially resolved this issue. For some reason, even though it's empty, this gets all of my **previous** bookmarks. The problem is that it does not fetch any new ones. 

### Expected Behaviour

1. Gets all existing bookmarks from the currently used browser profile
2. Uses the correct browser profile for all browsers
3. Fetches newly created bookmarks

**Comment by thomaslombart** [comment]
Thanks for reporting the issue thoroughly! Would you mind sharing the content of the following file: `~/Library/Application Support/Firefox/profiles.ini`? We're reading this file under the hood to get the user's profiles.

**Comment by baswolting** [comment]
Below are the file contents of `profiles.ini` located in the `~/Library/Application Support/Firefox` directory. Here's what I've tried, but none have solved the sync issue:

1. Commenting out the `name` and `path` of Profile1 using `; ` at the start of each line, replacing it with the ones of Profile0
2. Removing the `name` and `path` of Profile1 and replacing it with the ones of Profile0
3. Fully removing Profile1 and adding `default=1` to Profile0, as well as `default=0`

Here's some additional noteworthy behavior:
1. After removing the manually-created, empty directory of `Profiles/xavewwd0.default`, the issue persists (as it's the starting state)
2. After removing the `Profile1` section, which uses the directory, the error does not display anymore

In all the instances described above, the issue remains that new bookmarks are not synced. I created a bookmark in Chrome and it was added instantaneously after refreshing using the command+r command. I added a new bookmark yesterday, and another just now, but they still are not updated for Firefox even though I refreshed several times.

```
[Profile2]
Name=dev-edition-default
IsRelative=1
Path=Profiles/lglnqddq.dev-edition-default-1697551338297

[Profile1]
Name=default
IsRelative=1
Path=Profiles/xavewwd0.default
Default=1

[Profile0]
Name=default-release
IsRelative=1
Path=Profiles/32x8eokh.default-release

[General]
StartWithLastProfile=1
Version=2

[Install1F42C145FFDD4120]
Default=Profiles/lglnqddq.dev-edition-default-1697551338297
Locked=1

[Install2656FF1E876E9973]
Default=Profiles/32x8eokh.default-release
Locked=1
```

**Comment by baswolting** [comment]
Hi @thomaslombart, hope you can help me to figure this out. Tried quite a few things but haven't found a solution yet. If you need any additional info let me know and I'll try to send it asap. It's probably one of the most helpful extensions I have so I hope it can be fixed and working again soon.

**Comment by thomaslombart** [comment]
There may be something wrong with your Firefox configuration but it's hard to debug it since I can't reproduce it. Here's the file we use to get your Firefox bookmarks: https://github.com/raycast/extensions/blob/main/extensions/browser-bookmarks/src/hooks/useFirefoxBookmarks.ts. Do you see something wrong in there related to your configuration?

**Comment by baswolting** [comment]
Hi @thomaslombart, it appears that after modifying the file, new bookmarks are not syncing immediately as they do in Google Chrome. However, when I restart my computer, the new bookmarks do appear. I'm unsure if this sync delay is expected or not, but it currently meets my needs.

For those facing the same problem, the solution would be to edit the `profiles.ini` file by either removing inaccessible profiles or changing their order.

Thanks for the suggestion! I'll close this issue now.
