### ISSUE TITLE
[Easy Dictionary] OCR translating not working

### ISSUE THREAD

**Issue by wybert** [raycast/extensions#9226]
### Extension

https://www.raycast.com/isfeng/easydict

### Description

OCR translation function can extract the text but will not translate the extracted text sometimes. See below,
<img width="742" alt="image" src="https://github.com/raycast/extensions/assets/5254627/fbe71197-60e0-4e1a-8027-dafc4980fe0f">

### Steps To Reproduce

1. Install eazy dict
2. search OCR
3. select some text and translate Eazy

**Comment by tisfeng** [comment]
Hi, it's possible that the language recognition has failed, causing it to get stuck. The extension uses some online language recognition services, such as Bing, Baidu, etc., and you need to turn on the corresponding translation service option before it will be enabled. It is recommended to enable at least two or more language recognition services.

I will update a version later to optimize the language recognition function.

**Comment by tisfeng** [comment]
It's going to take a little while before I'm free to deal with this, sorry.

**Comment by wybert** [comment]
After checked serval translation service options, I could use it.

**Comment by tisfeng** [comment]
A new version [v2.9.1](https://github.com/tisfeng/Raycast-Easydict/releases/tag/2.9.1) has been released.

### 💎 Optimization

- Support customized OpenAI API URL, thanks to [liyaodong](https://github.com/liyaodong) for the PR.
- Optimized the language recognition function, added Baidu language recognition as default option.

**Comment by tisfeng** [comment]
@raycastbot close this issue
