### ISSUE TITLE
[Apple Reminders] ...

### ISSUE THREAD

**Issue by Visual-Studio-Coder** [raycast/extensions#9233]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

I wish the quick add AI command allowed you to put the date you'd like to be reminded on in the `notes` argument instead of the `reminder` arg.

### Who will benefit from this feature?

Anybody who is trying to use it intuitively

**Comment by thomaslombart** [comment]
I don't understand what you mean here. Could you give some examples?
