### ISSUE TITLE
[Dashlane Vault] Dashlane CLI is not installed

### ISSUE THREAD

**Issue by javier-kovacs** [raycast/extensions#9236]
### Extension

https://www.raycast.com/tm.wrnr/dashlane-vault

### Description

The extension is not working even after installing Dashlane CLI.

### Steps To Reproduce

1. Install the Raycast extension
2. Install Dashlane CLI using Homebrew
3. Sync Dashlane CLI data
4. Try the sync command in Dashlane Vault Raycast extension

### Current Behaviour

Error messsage showed: "Dashlane CLI is not installed"

### Expected Behaviour

Sync Dashlane vault.

**Comment by tmwrnr** [comment]
Hi @javier-kovacs ,

Did you [log in](https://dashlane.github.io/dashlane-cli/personal/authentication) to the Dashlane CLI after installing it? If so, are you able to use the CLI without any issues?

Is it only the "Sync" command that is not working, or are the "Password" and "Notes" commands also not functioning properly?

**Comment by tmwrnr** [comment]
@raycastbot rename this issue to "[Dashlane Vault] Dashlane CLI is not installed"

**Comment by javier-kovacs** [comment]
Hi @tmwrnr ,

Thank you for your reply.

Yes, I logged in to the Dashlane CLI after installing it. I can use the CLI without any issue (I can copy password to the clipboard, sync, etc., with store-password option set to true).

The "Sync" command is showing the error that I mentioned. The "Password" and "Notes" commands are showing an "Empty Vault" message with a "Sync" default action if I hit "Enter". When I hit "Enter" I get an error message "Dashlane sync failed".

**Comment by tmwrnr** [comment]
Thanks @javier-kovacs for the detailed answer!

Unfortunately, I currently have no idea what the problem could be.

I guess we have the same version, but what is the version of your CLI? My version is 1.14.2. And which macOS version are you using?

I will completely reinstall the CLI again and hope that I can recreate the problem. If not, would you perhaps have time to look at the problem together?

**Comment by tmwrnr** [comment]
Hi @javier-kovacs,

Thank you very much for the further information! I'm still trying to recreate the problem. Even if I set my macOS to Spanish, the extension works. The version of macOS and the CLI are exactly the same for me. I currently have no idea why the extension doesn't work for you.

I also asked the [Raycast Community](https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1700289649856309) to further narrow down the problem. I will continue to keep you updated.

**Comment by javier-kovacs** [comment]
Hi @tmwrnr 

The following screenshots show the error we are talking about:

![Error01](https://github.com/raycast/extensions/assets/40871825/8ddcb91e-7119-42d5-94ae-b539f1c6e9f4)
![Error02](https://github.com/raycast/extensions/assets/40871825/78064090-33db-4f75-afbe-008466856e64)
![Error03](https://github.com/raycast/extensions/assets/40871825/cb726410-86b4-45b1-9de4-99197d977333)
![Error04](https://github.com/raycast/extensions/assets/40871825/ed03e3d9-b8c9-4558-9726-128d660c7af3)

Hope this helps to better understand.

**Comment by tmwrnr** [comment]
Hi @javier-kovacs,

I have released a new version that allows you to set the path for the Dashlane CLI. The [extension page](https://www.raycast.com/tm.wrnr/dashlane-vault) now includes a troubleshooting section on how to obtain the path. Please try this and let me know if it works for you.
