### ISSUE TITLE
[Obsidian] search nog working. after entering search criteria and pressing enter, this error occurs

### ISSUE THREAD

**Issue by alexanderrkok** [raycast/extensions#9242]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

#### Error:
```
Error: Cannot get default application for file at /Users/alex/Library/Mobile Documents/iCloud~md~obsidian/Documents/Alex vault/Projects/Teamcoach opleiding/Reflectieverslagen/Opleidingsdagen/Reflectieverslag TC06 - Coachen bij stagnerende en regressieve teams.md


```

### Steps To Reproduce

Lastest version van Mac OS and Obsidian version 1.4.16 of raycast  version 1.61.2 
I will get an error when I search in raycast for search note. 
I enter search criteria in the search box and press enter
'something went wrong' is all I see.

### Current Behaviour

<img width="788" alt="image" src="https://github.com/raycast/extensions/assets/39742244/6c983a15-df9d-40b5-9b21-cdfb5dcf624c">
<img width="802" alt="image" src="https://github.com/raycast/extensions/assets/39742244/4628e9d1-508a-48c5-8b3f-a436a7c111e4">

### Expected Behaviour

search results.

**Comment by KevinBatdorf** [comment]
Opening a PR with a fix now. Thanks for reporting it.

**Comment by alexanderrkok** [comment]
Thnx, works like a charm now :-D
