### ISSUE TITLE
[Obsidian] Search Note failure

### ISSUE THREAD

**Issue by placer14** [raycast/extensions#9244]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

#### Error:
```
Error: Cannot get default application for file at /Users/<path_to_file>/2023-11-13.md


```

### Steps To Reproduce

0. Somehow disassociate markdown files with Obsidian
1. Attempt to Search Notes for a specific file (any)
2. Observe Raycast error view

### Current Behaviour

Shows Raycast error view

### Expected Behaviour

Shows search results from vault

**Comment by placer14** [comment]
Seems to be a duplicate of https://github.com/raycast/extensions/issues/9242. Closing.

**Comment by KevinBatdorf** [comment]
Opening a PR with a fix now. Thanks for reporting it.
