### ISSUE TITLE
[Apple Reminders] Set today as due date without setting a time

### ISSUE THREAD

**Issue by fturcheti** [raycast/extensions#9245]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Using the "Create Reminder" command, I'd like to be able to set reminders for today without setting a specific time. I can set reminders for tomorrow, as an example, without setting a time, but not for today.

**Comment by thomaslombart** [comment]
Hey @fturcheti, I tried it out and I can create one. The displayed date is wrong, which seems like a bug on our end but it should still be possible to create a reminder for today.  Could you send a recording to see what happens?

![CleanShot 2023-11-15 at 09 04 57](https://github.com/raycast/extensions/assets/16003285/d970cdcd-bd9a-4936-aecf-73eb907723eb)

**Comment by fturcheti** [comment]
Hey @thomaslombart, thanks for your attention. I recorded the video below some minutes after 17:00.

https://github.com/raycast/extensions/assets/365403/b7a2b3d9-0982-4fdf-a4d3-3db5643808ab

**Comment by fturcheti** [comment]
There's another strange thing that I point in the video above. When I select "Tomorrow" from the list, the field incorrectly display the date for tomorrow with a time associated—12:00. But the reminder is created without a time associated, as it was supposed to.

**Comment by thomaslombart** [comment]
Thanks for the additional details. I'll look into it.
