### ISSUE TITLE
[CleanShot X] extension commands don't open CleanShot

### ISSUE THREAD

**Issue by gabrielecirulli** [raycast/extensions#9258]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

Hello,
I used to run this extension on a M1 MacBook Pro with no issue. I recently switched to a M2 MacBook Air and haven't been able to get the extension to work.

I've not been able to diagnose the cause of the issue. I tried reinstalling the Raycast extension, and checked under Settings > Privacy & Security that all relevant permissions are granted to Raycast.

Is there something I might be missing?

### Steps To Reproduce

I am unable to provide detailed STR as I'm unsure what's causing the issue. The basic STR would be: 

1. Install CleanShot
2. Install Raycast
3. Install the extension
4. Grant Raycast all Privacy permissions

**Comment by gabrielecirulli** [comment]
It looks like the solution was to turn on this setting under "Advanced". As far as I can tell, this requirement wasn't documented.

![CleanShot 2023-11-15 at 14 12 28@2x](https://github.com/raycast/extensions/assets/886011/83f1facb-1e39-477c-952a-29ffe0d4d9cc)

**Comment by erics118** [comment]
Yep, its a new-ish change in CleanShot X that hasn't been documented in the extension docs. https://github.com/raycast/extensions/issues/8646 was about the same thing. Feel free to PR some doc changes
