### ISSUE TITLE
[Google Translate] Option to copy pronunciation

### ISSUE THREAD

**Issue by RihardsVeters** [raycast/extensions#9260]
### Extension

https://www.raycast.com/gebeto/translate

### Description

There’s no option to copy pronunciation/transliteration. Someone could add this. I'm using translate every day and I'm SEO specialist. I want to create URLs and I'm using pronunciation/transliteration for that purpose in Russian or Farsi.

### Who will benefit from this feature?

Everyone who uses translations for URLs

### Anything else?

![image](https://github.com/raycast/extensions/assets/41144957/65154959-4340-444f-82f3-0402cf5749ba)

**Comment by gebeto** [comment]
You can try to use this extension for slugging: https://www.raycast.com/unreadablename/slugify

While there are not implemented copy in google translate

<img width="862" alt="Screenshot 2023-11-15 at 19 15 33" src="https://github.com/raycast/extensions/assets/13422799/855b39ec-f623-485d-bbb6-ea673f9d495d">

**Comment by gebeto** [comment]
We already have ability to copy Translated text to the clipboard by pressing `CMD+ENTER`
<img width="862" alt="Screenshot 2023-11-15 at 19 23 03" src="https://github.com/raycast/extensions/assets/13422799/22f5dd5c-3161-483f-974b-d5513a1afb60">

**Comment by gebeto** [comment]
Added ability to copy pronunciation in this PR: https://github.com/raycast/extensions/pull/9262

**Comment by RihardsVeters** [comment]
Great news! ;) Waiting for it to be pushed live :)

**Comment by gebeto** [comment]
It is live now 🚀

**Comment by RihardsVeters** [comment]
Just tested, great work! Thank you!
