### ISSUE TITLE
[Odesli] Use it with Tidal song/album links

### ISSUE THREAD

**Issue by j-peeters** [raycast/extensions#9261]
### Extension

https://www.raycast.com/annedouwe/odesli

### Description

I tried using this on a Tidal song link but it didn't work. 
For what kind of music links is this extension intended? 
Not clear from description on extension page. 
Thanks!

### Who will benefit from this feature?

All Tidal users ;-)

**Comment by anned20** [comment]
Thanks for your feedback @j-peeters.

It should work out of the box with Tidal links. The raw list of supported platforms is:

- spotify
- itunes
- appleMusic
- youtube
- youtubeMusic
- google
- googleStore
- pandora
- deezer
- tidal
- amazonStore
- amazonMusic
- soundcloud
- napster
- yandex
- spinrilla
- audius
- anghami
- boomplay
- audiomack

However, I do agree with you that it would be good to include this in the description of the extension.

In case the link does not work with the extension, do you mind sharing it so I can debug this?

**Comment by anned20** [comment]
Added to README.md in #9279.

**Comment by j-peeters** [comment]
Hi @anned20 Thanks for confirming that it should also work with Tidal. The first times I used it after having copied a Tidal link I just heard raycast make a 'ploink' sound, as if it wasn't able to do anything. After a restart everything worked. Not sure how this would be related. 
Thanks for developing this, it's really useful since most of my friends are on Spotify (still, with the crappy sound) while I'm on Tidal. So it makes sharing suggestions a lot easier.
