### ISSUE TITLE
[CleanShot X] Does not work anymore with CleanShot 4.6

### ISSUE THREAD

**Issue by svenwiegand** [raycast/extensions#9277]
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

Since I've updated CleanShot X to version 4.6 (currently using 4.6.1 9a0ecd4) the extension doesn't do anything anymore.

### Steps To Reproduce

1. Select for example the "Capture Screen" command.

### Current Behaviour

Nothing happens.

### Expected Behaviour

The screen is captured and appears as a CleanShot mini window on the desktop.

**Comment by Aayush9029** [comment]
@svenwiegand 
![CleanShot 11-16 at 11 20 40@2x](https://github.com/raycast/extensions/assets/43297314/b182aa29-0bb3-4960-b3bb-b7948fe93f9e)

**Comment by Aayush9029** [comment]
@raycastbot close this issue

**Comment by erics118** [comment]
@Aayush9029 are you willing to PR some docs to the extension README? this seems like a pretty common issue now

**Comment by Aayush9029** [comment]
@erics118  Done. Will push new changes.
