### ISSUE TITLE
SyntaxError: Invalid or unexpected token koa=function(a,b,c,d){var e=null;switch(b)https://youtube.com/watch?v=2_vJ54m_agc

### ISSUE THREAD

**Issue by MishaIvasyutyn** [raycast/extensions#9284]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

When attempting to download a video from YouTube using the Raycast extension, a SyntaxError: Invalid or unexpected token is encountered
Additional Bug Description:
After encountering the ﻿SyntaxError: Invalid or unexpected token while attempting to download a video from YouTube using the Raycast extension, another issue arises. When pasting a different video, an error message is displayed indicating that the video cannot be found. However, the extension was previously able to find and process the video within a promised time.

### Steps To Reproduce

	1.	Install and enable the Raycast extension.
	2.	Open a web browser and go to a YouTube video.
	3.	Attempt to download the video using the Raycast extension's download feature.
	4.	While the video is being processed, an error message appears: "SyntaxError: Invalid or unexpected token koa=function(a,b,c,d){var e=null;switch(b)https://youtube.com/watch?v=2_vJ54m_agc".
	5.	Copy a different YouTube video URL.
	6.	Paste the new video URL into the Raycast extension to initiate the download.
	7.	Instead of successfully processing the new video, an error message is displayed, indicating that the video cannot be found.

### Current Behaviour

	1.	When attempting to download a video, a ﻿SyntaxError: Invalid or unexpected token is encountered, specifically in the ﻿koa function with the provided parameters (﻿a, ﻿b, ﻿c, ﻿d).
	2.	After encountering the syntax error, when pasting a different video URL, the extension displays an error message indicating that the video cannot be found. This occurs even though the extension was able to process a video successfully within the promised time frame before encountering the error.

### Expected Behaviour

	1.	The extension should process the video URL without encountering any syntax errors or unexpected token issues.
	2.	Upon successfully processing the video URL, the extension should initiate the download process and save the video to the designated location.
	3.	If a different video URL is pasted after encountering an error, the extension should be able to handle it correctly and initiate the download process for the new video without reporting that it cannot be found.

**Comment by vimtor** [comment]
Is this happening to you every time you try to download a video? We are using the unofficial YouTube API, and it's not super reliable, so some flakiness is to be expected.

**Comment by MishaIvasyutyn** [comment]
I'm sorry for the long response, but everything seems to be working perfectly fine since the last time I've been using this extension
