### ISSUE TITLE
[Pins] Option to show grouped pins in the root menu

### ISSUE THREAD

**Issue by targumanu** [raycast/extensions#9286]
### Extension

https://www.raycast.com/HelloImSteven/pins

### Description

It would be nice to have an option to display all pins in the root menu, including those assigned to a group.
In this case, grouped pins could be separated by group titles

### Who will benefit from this feature?

Anyone having not too many pins and wanting to quickly see and access them from the menu bar without having to navigate submenus

**Comment by SKaplanOfficial** [comment]
I honestly thought I already had this option, but I guess not. Will add it in the next update. Thanks!
