### ISSUE TITLE
Keeps on signing out every day[Gmail] ...

### ISSUE THREAD

**Issue by pearsed13** [raycast/extensions#9287]
### Extension

https://www.raycast.com/tonka3000/gmail

#### Error:
```
Error: Toast API is not available when command is launched in background


```

### Steps To Reproduce

It is in my top bar on latest Sonoma. I have just the "display unread" option and it signed out

### Current Behaviour

Signes out every so often. Recently it started happening every day

### Expected Behaviour

To stay signed in

**Comment by tonka3000** [comment]
Hi @pearsed13 ,

Try to set your oauth key to production in the Google console.
