### ISSUE TITLE
[Google Translate] not working properly

### ISSUE THREAD

**Issue by jiechen257** [raycast/extensions#9292]
### Extension

https://www.raycast.com/gebeto/translate

### Description

When I evoke the extension that expands and enters the translation, the problem appears
![image](https://github.com/raycast/extensions/assets/73946940/cbf53e1e-31e8-4985-a147-fdaea4f68f9e)

### Steps To Reproduce

1. evoke the extension
2. enter the translation
3. the problem appears

**Comment by erics118** [comment]
This seems like the unofficial API that is being used malfunctioned. Just try running the command again, and it should fix itself.

I believe the issue is that the server is returning HTML (hence the `<`) rather than JSON.

**Comment by jiechen257** [comment]
> This seems like the unofficial API that is being used malfunctioned. Just try running the command again, and it should fix itself.
> 
> I believe the issue is that the server is returning HTML (hence the `<`) rather than JSON.

yeah, when I subsequently launch the plugin again, it works fine. It does seem like an api problem
