### ISSUE TITLE
[Slack] Support multiple workspaces

### ISSUE THREAD

**Issue by theherk** [raycast/extensions#9295]
### Extension

https://www.raycast.com/mommertf/slack

### Description

Currently, the extension's configuration accepts one Slack Access Token. It seems like it would be good to support multiple workspaces. I realize that isn't as simple as accepting more tokens because the workflow has to change significantly, but many of us use several Slack workspaces at a time. Or perhaps I'm completely overlooking how this already works with multiple workspaces.

### Who will benefit from this feature?

All Slack users that have several workspaces open at once.

**Comment by rowanoulton** [comment]
Adding a plus-one to this :+1:

**Comment by gabriel-r** [comment]
Duplicate of #4802
