### ISSUE TITLE
[Tesla] Add a setting to get kilometers and Celsius degrees

### ISSUE THREAD

**Issue by cerivan** [raycast/extensions#9300]
### Extension

https://www.raycast.com/williamwelsh/tesla

### Description

Add a setting to switch between miles and kilometers, and °F to °C

### Who will benefit from this feature?

All non-US users

**Comment by WilliamWelsh** [comment]
@cerivan This was merged :D

**Comment by WilliamWelsh** [comment]
@raycastbot close this issue
