### ISSUE TITLE
[Bitwarden] Unlock via Touch ID when native Vault App is unlocked

### ISSUE THREAD

**Issue by sewqawsdewq332** [raycast/extensions#9306]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Request to enable unlock via Touch ID when native Vault App is unlocked, similar to how the browser extensions work.

### Who will benefit from this feature?

Mac based users with Touch ID enabled.

### Anything else?

[](https://bitwarden.com/help/biometrics/)

**Comment by jomifepe** [comment]
Hello, thanks for the suggestion. Multiple people have asked for this, and here's why it's not implemented yet: https://github.com/raycast/extensions/issues/8075#issuecomment-1694508921

**Comment by jomifepe** [comment]
Duplicate of #8075 

@raycastbot close this issue
