### ISSUE TITLE
[Easy Dictionary] ...

### ISSUE THREAD

**Issue by liusd-cn** [raycast/extensions#9310]
### Extension

https://www.raycast.com/isfeng/easydict

#### Error:
```
Error: Unexpected scutil proxy output format

Object.zR:parse-scutil.ts:52:12

---
49:         return data
Error: Unexpected scutil proxy output format

Object.zR:parse-scutil.ts:52:12

---
49:         return data;
50:     } catch (e) {
51:         throw Object.assign(
52:             new Error("Unexpected scutil proxy output format"),
53:             { scutilOutput: output } // Attach output for debugging elsewhere
54:         );
55:     }
---

ChildProcess.<anonymous>:easydict.js:8:816
ChildProcess.emit:node:events:514:28
ChildProcess.emit:node:domain:488:12

### Steps To Reproduce

1. OS: macOS 14.1.1 23B81 arm64
        Host: Mac14,9
      Kernel: 23.1.0
     Packages: 84 (brew)
     Shell: zsh 5.9
2. 


### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by liusd-cn** [comment]
<img width="317" alt="image" src="https://github.com/raycast/extensions/assets/106422496/fcfdf767-f29a-4441-8e16-67ea277fded9">

**Comment by tisfeng** [comment]
It looks like getting the system agent failed, please execute the following command in the terminal to see if the result is as follows

```bash
scutil --proxy
```

<img width="1006" alt="image" src="https://github.com/raycast/extensions/assets/25194972/8ef07986-e03b-4240-bd78-c6739de6b429">

**Comment by tisfeng** [comment]
It is also recommended to turn on the Web Proxy option in the Raycast settings page so that you can get the proxy directly through the Raycast API instead of using scutil --proxy.

<img width="1036" alt="image" src="https://github.com/raycast/extensions/assets/25194972/2510a627-3241-4a5b-bde5-9a52fd2c2926">

**Comment by liusd-cn** [comment]
This problem has been solved, and thank you for your answer





---- Replied Message ----
| From | ***@***.***> |
| Date | 11/18/2023 17:58 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [raycast/extensions] [Easy Dictionary] ... (Issue #9310) |

It is also recommended to turn on the Web Proxy option in the Raycast settings page so that you can get the proxy directly through the Raycast API instead of using scutil --proxy.

**Comment by tisfeng** [comment]
@raycastbot close this issue

**Comment by maxchang3** [comment]
@raycastbot rename this issue to "[Easy Dictionary] Unexpected scutil proxy output error"
