### ISSUE TITLE
Spotify Player

### ISSUE THREAD

**Issue by orvpagadua** [raycast/extensions#9313]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

can't play Spotify songs
```
Error: Player command failed: Premium required

pi:play.ts:68:10

---
65:     }
66: 
67:     console.log("play.ts Error: ", error);
68:     throw new Error(error);
69:   }
70: }
71: 
---

async onAction:search.js:59:768
```

### Steps To Reproduce

search any songs on the raycast Spotify player extension then play.

### Current Behaviour

Gives the 'Something went wrong message'

### Expected Behaviour

should be able to play any song

**Comment by erics118** [comment]
Premium is required to use the extension.


@raycastbot close this issue
