### ISSUE TITLE
[Empty Screenshot Folder] When Clearing

### ISSUE THREAD

**Issue by Eveeifyeve** [raycast/extensions#9323]
### Extension

https://www.raycast.com/chanceaclark/empty-screenshots

#### Error:
```
Error: EPERM: operation not permitted, scandir '/Users/eveeify/Documents/Screenshots'


```

### Steps To Reproduce

1. set to ~/Documents/Screenshots

### Current Behaviour

Failing

### Expected Behaviour

It should be clearing

**Comment by chanceaclark** [comment]
I think this could be one of two issues:
1. Might need to give Raycast permission for the Desktop folder. `Privacy & Security > Files and Folders > Raycast`
<img width="827" alt="Screenshot 2023-11-27 at 11 12 08" src="https://github.com/raycast/extensions/assets/10539418/bfcaf17e-9ef9-4b7f-9eb2-26624c563ec7">

2. I did a quick grep around npm's archived GitHub repo and found that older versions of node my cause this. I would be curious to know what your default node version is to see if that might an issue.

**Comment by Eveeifyeve** [comment]
It was an issue in privacy and security I had documents off. Next time to prevent this issue can you make a notification or something to notify the person?

**Comment by chanceaclark** [comment]
I'll throw up PR to address that @Eveeifyeve!
