### ISSUE TITLE
[Apple Reminders] ...

### ISSUE THREAD

**Issue by sysophost** [raycast/extensions#9328]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

The `edit` action only lets you edit the title and description in existing reminders, not due date/priority etc. Given you can set these via the `create` action it would be nice if there was the same functionality when editing existing reminders.

## Create

![image](https://github.com/raycast/extensions/assets/4862442/b908b0f1-0215-469d-898d-f430ca42b86c)

## Edit

![image](https://github.com/raycast/extensions/assets/4862442/ba252ed8-5fd7-4801-a0fe-aaec87bdc217)

### Anything else?

Further to this, it would also be nice if there was a visual indicator that distinguished the pro from the non-pro features within the extension, e.g. `quick add` is a pro only feature but isn't visually distinguishable from other features until you try to use it.

**Comment by thomaslombart** [comment]
Why not using the dedicated actions for that?

![CleanShot 2023-11-20 at 11 42 37@2x](https://github.com/raycast/extensions/assets/16003285/b2d39db1-fff3-44ca-b91a-c5a65452eea8)

**Comment by thomaslombart** [comment]
I'm closing the issue as there's already a solution to that and to keep a backlog clean.
