### ISSUE TITLE
Ability to delete assets from Raycast extension window

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#9329]
### Extension

https://www.raycast.com/colbyfayock/cloudinary

### Description

Add an action to be able to delete images (ctrl + x)

**Comment by colbyfayock** [comment]
thanks @romanskorobagatko - good idea!

do you have any Raycast flows you've really liked with that regard? considering things like confirming you want to delete, before you delete the asset?

given i'm somewhat new still to creating these, would love to see what a good UX looks like

**Comment by romanskorobagatko** [comment]
@colbyfayock here is an example with [Jump](https://www.raycast.com/HelloImSteven/jump) extension - https://capture.dropbox.com/B1rNjMmHe5nACErl

**Comment by colbyfayock** [comment]
opened a ticket over on the actual repository for this as well https://github.com/colbyfayock/raycast-cloudinary/issues/10
