### ISSUE TITLE
Feature Request: Task Search and Add Functionality in Time Entry Creation for  [Toggl Track] ...

### ISSUE THREAD

**Issue by kuvahaku** [raycast/extensions#9332]
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Description

The Toggl Track Raycast extension currently lacks an option to search and link tasks during time entry creation. Users must navigate to Toggl Track separately to do so. Additionally, some situations require task association as a mandatory step.
The proposed feature is an integrated task search function during time entry creation, enabling users to select and link tasks directly within the same interface.

### Who will benefit from this feature?

Regular users, especially project managers, freelancers, and team leads, will benefit from this feature. It streamlines workflow, reduces platform switching, and assists in scenarios where task association is mandatory.

### Anything else?

![CleanShot- toggl-task](https://github.com/raycast/extensions/assets/22451853/9235c6cd-2b2a-49e9-940a-f0ce8147a630)

**Comment by bkeys818** [comment]
The hope was that #8018 would add this feature, but no one had premium, so we couldn't test it.
