### ISSUE TITLE
Display Error in Spotify Player on Raycast 1.62.1 with Menu Bar on MacBook Air M1

### ISSUE THREAD

**Issue by bickpenna** [raycast/extensions#9334]
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```
Error: OAuth request creation is not available when command is launched in background


```

### Steps To Reproduce

Device: MacBook Air M1
Operating System: 14.1.1 (23B81)
Raycast Version: 1.62.1

**Comment by samschooler** [comment]
Having the same issue

**Comment by sxn** [comment]
hi there – it looks like the menu bar command is activated, but for some reason you're not authenticated via OAuth. This results in the command running in the background attempting to initiate OAuth, which must be user-initiated to work properly. To resolve this, please try the following:

1. Go to Raycast's root search.
2. Run the Spotify extension's `Menu Bar Player` command.
3. Follow the prompts on the OAuth screen to authenticate.

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/1155589/7e6ef215-77a0-4b2f-bb4b-118be8865ccf">

After successful authentication, you should see a confirmation screen, and the menu bar command should function correctly. If you encounter any issues during the process, please let me know, and I’ll be happy to assist further.

**Comment by samschooler** [comment]
> hi there – it looks like the menu bar command is activated, but for some reason you're not authenticated via OAuth. This results in the command running in the background attempting to initiate OAuth, which must be user-initiated to work properly. To resolve this, please try the following:
> 
>     1. Go to Raycast's root search.
> 
>     2. Run the Spotify extension's `Menu Bar Player` command.
> 
>     3. Follow the prompts on the OAuth screen to authenticate.
> 
> 
> <img alt="image" width="862" src="https://private-user-images.githubusercontent.com/1155589/297687796-7e6ef215-77a0-4b2f-bb4b-118be8865ccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDc2NjEsIm5iZiI6MTcwNTk0NzM2MSwicGF0aCI6Ii8xMTU1NTg5LzI5NzY4Nzc5Ni03ZTZlZjIxNS03N2EwLTRiMmYtYmI0Yi0xMThiZTg4NjVjY2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMTgxNjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIxNTRmMDRkY2NhYzYwOTgxZTAzMzkyYzBiMjAxZDM0MmY3ZTc3MGVkZDFmOWIyYWE0OGE1OWU0YmZkNmFmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HYcjGzoUFf2fi1Wa1mXfkmjTULAEqSzsZVA-tki4Zcc">
> 
> After successful authentication, you should see a confirmation screen, and the menu bar command should function correctly. Hope this helps!

I will say, this was not the case when I initially ran into this error. However it seems to be working now, thx :)
