### ISSUE TITLE
[Safari] ... Save safari search history for all profiles, not just default profile

### ISSUE THREAD

**Issue by scottaw66** [raycast/extensions#9339]
### Extension

https://www.raycast.com/loris/safari

### Description

Safari extension saves history for default personal safari profile but does not save history for second, work-related safari profile. This may be a limitation of Safari profiles and information to the extension but just in case it IS possible to save history for all Safari profiles, I am requesting the ability to do so.

### Who will benefit from this feature?

Anyone who uses Safari profiles

**Comment by scottaw66** [comment]
This is another example of a need for multiple extensions that do the same thing. The authors go awol. I don't understand it.

**Comment by SKaplanOfficial** [comment]
There isn't really a need for multiple extensions that do the same thing as anyone can make a PR adding features to the extension. This is a fairly large feature that will take some time and effort.

I will look into adding profile support, but last I checked there wasn't a straightforward way to do it.

**Comment by loris** [comment]
> This is another example of a need for multiple extensions that do the same thing. The authors go awol. I don't understand it.

@scottaw66 Please be respectful of open source contributors, they don't owe you nothing and are not going "awol"

**Comment by scottaw66** [comment]
I have zero issues with them, and I understand they owe me nothing. The issue comes in because Raycast encourages using existing extensions rather than creating ones that duplicate the features of another. This means if for some reason the one extension that doesn't do something never gets updated, now we're stuck.

**Comment by scottaw66** [comment]
> There isn't really a need for multiple extensions that do the same thing as anyone can make a PR adding features to the extension. As for why this is stalled: this is a fairly large feature that will take some time and effort.
> 
> I will look into adding profile support again, but last I checked there wasn't a straightforward way to do it.

That's all I needed, was some kind of response. I 100% get it may not be possible or not worth the effort.

**Comment by SKaplanOfficial** [comment]
I get that stance, but I also think there are advantages to having one extension for things. For example, if someone on Reddit/Slack/elsewhere needs help with a particular extension, others can efficiently provide specific information for that extension, whereas having multiple extensions for the same thing can cause confusion & fragmentation.

Like I said before, as long as anyone can contribute to an extension, extensions _should_ be able to keep updating even without the original author's involvement (in practice, Raycast's approach to this does need some work). 

Personally, I like the current system as it encourages me to contribute to others' extensions and see how they approach different tasks. It also encourages me to think more about how to make my extensions customizable to meet others' needs. But I can see how it's not the same for everyone. Not sure what the best path forward is.

---

As for this issue: I'm honestly not sure where Apple is storing the history for non-default profiles, or where they're storing profiles at all for that matter. The history DB doesn't contain entries for other profiles, but you can view the history in Safari, so it must be somewhere.

I'll keep poking around when I have time. If/when I find a way, or if Apple provides an API for it in the future, I'd be happy to add profile support throughout the extension.
