### ISSUE TITLE
Can't seem to add my figma or change my inputs

### ISSUE THREAD

**Issue by a842322** [raycast/extensions#935]
# Extension – [Figma File Search](https://github.com/raycast/extensions/tree/3d465f6258eb61fa862a0bb8f813c7f781c0dab9/extensions/figma-files/)
Author: @michaelwschultz

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.28.0

**Comment by michaelwschultz** [comment]
@a842322 not sure exactly what you mean here. I'm assuming you had some trouble adding your Figma credentials. 

You can update your credentials in the Extensions section of the settings panel.

Most likely you need to verify that you've added your Team ID correctly. The easiest way to do that is to click on your team in Figma.

Then grab the ID that comes after `figma.com/files/team/**YOUR ID HERE***` in the URL.

Hopefully these screenshots help.

![CleanShot 2022-02-18 at 11 01 52](https://user-images.githubusercontent.com/57668/154745807-c124955d-6c2c-45b6-a562-6f056d2c9f17.png)

![CleanShot 2022-02-18 at 11 02 47](https://user-images.githubusercontent.com/57668/154745989-52c870c3-d772-4f55-aea0-32eb4484254d.png)

**Comment by mathieudutour** [comment]
I'm going to close this issue as the issue template hasn't been filled and it's impossible to investigate.
