### ISSUE TITLE
[JetBrains Toolbox Recent Projects] blank menu icon

### ISSUE THREAD

**Issue by MustCodeAl** [raycast/extensions#9357]
### Extension

https://www.raycast.com/gdsmith/jetbrains

### Description

Blank icon in menu bar

### Steps To Reproduce

Install the extension and hook up your ides

### Current Behaviour

the icon is completely blank in the menu bar

https://github.com/raycast/extensions/assets/87888006/31de694d-98a8-49ed-b3f1-59b52e6ae8e8

### Expected Behaviour

should display an image to similar to the actual jetbrain toolbox in the menubar when you have it activated

**Comment by gdsmith** [comment]
@MustCodeAl sorry missed this issue, can you confirm if it's still happening, and if so, what version of JetBrians Toolbox you are using?

**Comment by MustCodeAl** [comment]
I Just reset my MacBook and now the icon is appearing normally

**Comment by gdsmith** [comment]
@raycastbot close this issue
