### ISSUE TITLE
[Screen Sharing Recents] New Locations do not get added since Sonoma

### ISSUE THREAD

**Issue by m-wack** [raycast/extensions#9359]
### Extension

https://www.raycast.com/bix/screen-sharing-recents

### Description

Since updating to Sonoma, all old Screen Sharing Locations from pre-Sonoma still show up in the search of the extension.
However every target Location I accessed since updating to Sonoma, does not get found in search. It is found in Apple's new Screen Sharing App though.

### Steps To Reproduce

1. in macOS Sonoma
2. access a new, never pre-Sonoma opened Screen Sharing Target
3. Search for it in the extension
4. Do not find it

### Current Behaviour

Targets newly accessed since Sonoma don't show up.

### Expected Behaviour

Newly access Locations get added to the search like before.

**Comment by wlonkly** [comment]
Yeah, looks like this all changed in Sonoma -- hosts are now stored in plist files in `$HOME/Library/Containers/com.apple.ScreenSharing/Data/Library/Application Support/Screen Sharing Hosts`, where the contents of the plist look like 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>vnc://user@hostname:5900</key>
	<data>
	[some kind of public key I think?]
	</data>
</dict>
</plist>
```

Thankfully it looks like they're stored as XML, not as binary plists.

Although.. I have plist files in there dating back to 2021, so maybe it's always had both?  But the `.../Application Support/Screen Sharing` directory referenced by the extension is now empty. 

No idea how to open this ticket back up (it's still broken...) but figured I'd record what I found.

**Comment by m-wack** [comment]
Ah, I'm not the only one with the issue atleast. 
I reopened a new issue here:

https://github.com/raycast/extensions/issues/10420

Maybe add your comment there too so we can get this issue resolved together with a Dev.
