### ISSUE TITLE
setState not triggering Form rerender

### ISSUE THREAD

**Issue by guo40020** [raycast/extensions#936]
Raycast version: 1.28.0

## Description
When using controlled textField, setState does not update the actual value of the textField, or TextArea. I found out that setState does not update the ui even if I put my state to the title of the textField

## Steps To Reproduce

[Sample code](https://github.com/guo40020/kellys-raycast-workflow/blob/master/src/pages/pref.tsx)

## The current behavior
setState does not trigger ui rerender.

## The expected behavior
setState should trigger ui rerendering.

**Comment by mattisssa** [comment]
Hey @guo40020! Thanks for the report. For some reason, your code works fine for me. Probably I'm doing something wrong to reproduce it, could you please share more details? probably a screencast of the issue will help.

**Comment by guo40020** [comment]
Thanks for reply! Actually the problem that I was running in was that I was trying to limit the Clash port `TextField` to accept only numbers but I found that the actual state behind it was correct but the value of the `TextField` was not controlled by the state.

Screenshot:
![image](https://user-images.githubusercontent.com/19303341/154799632-46ba5e84-f123-4ba9-a26e-be5746dd20a3.png)
