### ISSUE TITLE
[Change Case] ...Need to exit extension for it to update to newly selected text after using it once already 

### ISSUE THREAD

**Issue by Kikangh** [raycast/extensions#9364]
### Extension

https://www.raycast.com/erics118/change-case

### Description

Hi, I have an issue with the Change Case extension. More often that not, I need to change the case several times in a row for different words. I'll select the first one, invoke Raycast, type "change case", hit enter, type "upper" to get "upper case", hit enter, then select another word, invoke raycast again. Then Raycast will still be  « inside » the "change case" extension, with the "upper case" selected, yet the displayed word will be the previous one. It did not update. I'll have to go back twice and enter the "Change case" extension again for it to take the new selection into account. For my use case, I'd like it to update to my latest text selection every time I invoke raycast while "in the extension".
I hope I was able to explain this situation clearly enough.

### Steps To Reproduce

1- select some text in a text editor,
2- invoke Raycast, type "change case", hit enter,
3- type "upper" to get "upper case", hit enter, (or any other case type I guess), and it'll replace text case accordingly,
4- select another word, while still in the delay where Raycast will "stay" in the active extension,
5-  invoke raycast again. Raycast will still be  « inside » the "change case" extension, with the "upper case" selected, yet the displayed word will be the previous one.
6- hit enter and it'll paste the previous text. It won't update to the newly selected text.

### Current Behaviour

1- select some text in a text editor,
2- invoke Raycast, type "change case", hit enter,
3- type "upper" to get "upper case", hit enter, (or any other case type I guess), and it'll replace text case accordingly,
4- select another word, while still in the delay where Raycast will "stay" in the active extension,
5-  invoke raycast again. Raycast will still be  « inside » the "change case" extension, with the "upper case" selected, yet the displayed word will be the previous one.
6- hit enter and it'll paste the previous text. It won't update to the newly selected text.

### Expected Behaviour

1- select some text in a text editor,
2- invoke Raycast, type "change case", hit enter,
3- type "upper" to get "upper case", hit enter, (or any other case type I guess), and it'll replace text case accordingly,
4- select another word, while still in the delay where Raycast will "stay" in the active extension,
5-  invoke raycast again. Raycast will still be  « inside » the "change case" extension, with the "upper case" selected, the text displayed will be the newly selected one, with the case changed.
6- hit enter and voilà.

**Comment by erics118** [comment]
I've personally wanted to do this, but I haven't found a really nice way to do this yet.

**Comment by Kikangh** [comment]
Understood, thanks for the reply.
I have no clue how this works or what are the requirements for Raycast extensions, so sorry if my thinking is irrelevant :

If the "Change Case" extension would "quit" after pasting the modified text, it would still simplify things for me, as it would mean less steps to get to the result, since I’d be at Raycast’s root when I invoke it the second time.
Maybe a setting toggle for this behavior would be useful if other use cases don’t need this ?

Anyhow, thanks for making this extension and making it available to us.

But maybe a user setting 

Le 22 nov. 2023 à 19:51, Eric ***@***.***> a écrit :


I've personally wanted to do this, but I haven't found a really nice way to do this yet.

**Comment by erics118** [comment]
I hesitate to do that because it's generally recommended to respect the user's preference of `Pop to Root Search` under Advanced preferences. 
![CleanShot 2023-11-25 at 17 19 34](https://github.com/raycast/extensions/assets/52634785/c80fe092-cda4-4ec0-bc1c-aa4ea88141f1)

How about a manual refresh action? eg, `cmd-r` to refresh the clipboard?

**Comment by Kikangh** [comment]
Manual refresh action sounds good to me  Cordialement,Gilles HemardEnvoyé de mon iPhoneLe 25 nov. 2023 à 23:20, Eric ***@***.***> a écrit :﻿
I hesitate to do that because it's generally recommended to respect the user's preference of Pop to Root Search under Advanced preferences.
CleanShot.2023-11-25.at.17.19.34.png (view on web)
How about a manual refresh action? eg, cmd-r to refresh the clipboard?
