### ISSUE TITLE
[Confluence] Support Self-Hosted Confluence

### ISSUE THREAD

**Issue by kojunho7** [raycast/extensions#9366]
### Extension

https://www.raycast.com/tbrown/confluence

### Description

Hello, I would like to use a self hosted instance of Confluence, using a custom domain and access token. 
This setup would be similar to the functionality provided by a self-hosted Jira Search.

https://www.raycast.com/emanguy/jira-search-self-hosted

### Who will benefit from this feature?

Large enterprises and organizations that use self-hosted Confluence.

**Comment by Mekacher-Anis** [comment]
bringing it back to life!!
