### ISSUE TITLE
[Visual Studio Code] New installation > 'Open With' and 'Commands' don't work

### ISSUE THREAD

**Issue by DerZyklop** [raycast/extensions#9367]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

Installed the extension. Some commands don't work. Installation of Visual Studio Code seems fine.

### Steps To Reproduce

Install Visual Studio Code
Install Raycast
Install Raycast extension 'Visual Studio Code'
Open Raycast
Type 'vscode commands'
Hit 'enter'

### Current Behaviour

Commands that work:
- Search recent projects
- Show / Install / Uninstall extensions

Commands that do not work:
- Open With Visual Studio Code while no file is selected in Finder (Error: `Failed opening selected Finder or Path Finder item - Not a valid directory`)
- Open With Visual Studio Code while a file is selected in Finder (Error: `Failed opening selected Finder or Path Finder item - Could not get the selected Finder items`)
- Commands (No response from Reycast for VSCode extension / Error: `Could not get VSCode commands`)

### Expected Behaviour

All commands work without Errors.

**Comment by erics118** [comment]
open with vscode - this command requires something to be selected with Finder.
commands - this command requires the Raycast extension for VSCode to be installed.

**Comment by DerZyklop** [comment]
Thanks @erics118! 
The requirements are fulfilled on my machine.
I just figured that the error’s description is different depending on whether I have a file selected in Finder (`Could not get the selected Finder items `) or not (`Not a valid directory`). 
FTR: I added that info to the 'Current Behaviour' section above.

**Comment by DerZyklop** [comment]
The bug is still happening. 
FYI @erics118 ✌

**Comment by erics118** [comment]
I don't know what's broken, as they all work for me.
