### ISSUE TITLE
[Mozilla Firefox] ...Can not search for tabs

### ISSUE THREAD

**Issue by psi-mon** [raycast/extensions#9373]
### Extension

https://www.raycast.com/crisboarna/mozilla-firefox

### Description

When I try to search for a tab nothing is shown and there is the following error:
```
Error: Error: in prepare, no such column: k
   moz_places           WHERE moz_places.title LIKE k           ORDER BY last_vi
                                      error here ---^

    at Object.current (/Users/kaputtzimon/.config/raycast/extensions/4f2f1045-8725-4c82-a486-6e6b587dd101/new-tab.js:8:3284)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

When I try the search history command the same error appears as soon as I start typing. 

### Steps To Reproduce

OS: macOS Sonoma 14.0
Firefox: 120.0
Raycast: 1.62.1

**Comment by grandkrav** [comment]
Looks like the tab search feature is disabled.
There is code for searching and selecting a tab (by moving open tabs to the desired tab).

I tested [Brotab](https://github.com/balta2ar/brotab) (with the Brotab Firefox extension) to select an open tab. It seems that everything works quite stably. Is this a suitable solution for extension?

**Comment by renchap** [comment]
This is still an issue, there is no way to search in open tabs with this extension (like what is possible with Safari)

**Comment by sergey-kravchenk0** [comment]
@renchap there is an option to use [brotab](https://github.com/balta2ar/brotab) to search in open tabs

**Comment by grandkrav** [comment]
@renchap there is an option with Brotab:

> Looks like the tab search feature is disabled. There is code for searching and selecting a tab (by moving open tabs to the desired tab).
> 
> I tested [Brotab](https://github.com/balta2ar/brotab) (with the Brotab Firefox extension) to select an open tab. It seems that everything works quite stably. Is this a suitable solution for extension?
