### ISSUE TITLE
Quick Option to Remove EXIF Metadata

### ISSUE THREAD

**Issue by mrbonky** [raycast/extensions#9399]
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

Quickly remove EXIF data from images. Often I convert images to post to public websites and have to go through an image editor to remove the data when I just need to quickly convert and post an image online.

### Who will benefit from this feature?

People looking to post images anonymously on public websites quickly. Removing the metadata that often contains things like device type and location data would be extremely beneficial.

**Comment by 3e9b** [comment]
This function is no longer working. I fixed it in a pull request but it was never merged. #11093

**Comment by SKaplanOfficial** [comment]
@3e9b Apologies for the late reply. The Strip EXIF Data command works for me currently. The change you made in #11093 consistently throws a file not found error for me, since instead of outputting to the new path it tries to operate on a nonexistent file. I can't see how it would work without the `-o` flag. I'd be happy to look into it more if you can provide more information about the error you're getting.

**Comment by 3e9b** [comment]
@SKaplanOfficial Here's what I'm getting
```
Command failed: "/Users/name/Library/Application Support/com.raycast.macos/extensions/7c158f0e-b70b-4922-8a1b-5c8a9ccb55d6/Image-ExifTool-12.74/exiftool" -all= -o "/Users/name/Desktop/Screenshot 2024-06-24 at 3.38.43 PM.png" "/Users/name/Desktop/Screenshot 2024-06-24 at 3.38.43 PM.png"
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LC_ALL = "en_US-u-hc-h12-u-ca-gregory-u-nu-latn",
	LANG = (unset)
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Error: '/Users/name/Desktop/Screenshot 2024-06-24 at 3.38.43 PM.png' already exists - /Users/name/Desktop/Screenshot 2024-06-24 at 3.38.43 PM.png
```

However when I run my version without the `-o` flag, no issues.

**Comment by SKaplanOfficial** [comment]
Ah, thanks! I don't see the error when using "Save in Containing Folder", but I see it with "Replace Original". Will have to handle those cases separately as ExifTool doesn't seem to allow using `-o` to overwrite a file (instead requiring `-overwrite_original`, which doesn't work for the other case).

Fix for this and some other bugs will be pushed soon (today or tomorrow).
