### ISSUE TITLE
[Hue] Extension can't find Bridge

### ISSUE THREAD

**Issue by pharwood** [raycast/extensions#9404]
### Extension

https://www.raycast.com/pindab0ter/hue

### Description

I installed the Hue extension a few weeks ago and it worked perfectly. Then about a week ago it stopped communicating with my Bridge. I tried the following:

Restart Mac
Uninstall and reinstall extension
Using IP address instead of pressing Bridge button

None of which worked. The Bridge works fine with my other Hue lights and accessories.

### Steps To Reproduce

Install extension and launch.
Choose command.
Prompt to press Bridge button.
Do this.
Failed to link with Bridge.
Tried entering IP address with same result.

**Comment by pindab0ter** [comment]
Please let me know if there is more information you can provide. I can't do anything unless we know what exactly is going wrong.

**Comment by pharwood** [comment]
Has been working as expected for a few weeks now. I didn't do anything. It just seemed to start working again.

**Comment by pindab0ter** [comment]
That's very good to hear!

**Comment by pindab0ter** [comment]
@raycastbot close this issue
