### ISSUE TITLE
[Bible] Add BSB and LSB Translations

### ISSUE THREAD

**Issue by knpwrs** [raycast/extensions#9424]
### Extension

https://www.raycast.com/josmithua/bible

### Description

The [BSB](https://berean.bible/) is a modern public domain Bible translation.

The [LSB](https://lsbible.org/) is an update of the NASB 1995 (which is already included with the extension).

**Comment by knpwrs** [comment]
The LSB is available through Bible Gateway, which this extension uses.

The BSB is easily accessible through https://fetch.bible, e.g., https://collection.fetch.bible/bibles/eng_bsb/html/gen.json

**Comment by josmithua** [comment]
Hi @knpwrs, I've submitted a PR to update the available bible versions from Bible Gateway,  which adds the LSB. 

A lot more work would have to be done to support a new source like fetch.bible, so unfortunately the BSB is not an option right now.
