### ISSUE TITLE
[Visual Studio Code] ...

### ISSUE THREAD

**Issue by rh01** [raycast/extensions#9446]
### Extension

https://www.raycast.com/thomas/visual-studio-code

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'name')

E2:index.tsx:134:49

---
131: }
132: 
133: function LocalItem(props: { entry: EntryLike

### Steps To Reproduce

Open "Search Recent Projects", Panic occurs

```
Something went wrong
You can try reloading, or report the error to the extension developer, by
copying the log from the Action Panel K
```



### Current Behaviour

I cannot use "Search Recent Projects" command and function

### Expected Behaviour

fix

**Comment by Han-Ya-Jun** [comment]
I'm having this problem too.

**Comment by zhuozhiyongde** [comment]
Same.

**Comment by Yuki-Sakaguchi** [comment]
The same error occurred, but when I checked, nothing was set.
I fixed it by setting up the terminal!

**Comment by zhuozhiyongde** [comment]
@tmwrnr 
Fixed, thx!

**Comment by CaptainVincent** [comment]
I'm experiencing the same issue. Checking the terminal settings with my terminal could fix my problem (opening recent files without anything).
I think perhaps the language of the host could affect the matching of the terminal app's name, causing it to default to none.

**Comment by pernielsentikaer** [comment]
A fix has been deployed now, you can either wait for it or run `Check For Extension Updates` 🙂
