### ISSUE TITLE
Google bard not working

### ISSUE THREAD

**Issue by AISLVE** [raycast/extensions#9447]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

I follow all the steps written and put in my session cookie ID but still it say bard couldn't connect
<img width="886" alt="image" src="https://github.com/raycast/extensions/assets/121119257/63986cb0-f06c-4e28-bdc6-f4bd9dc9cd4f">

### Steps To Reproduce

Put in your session cookie ID
It will not work

### Current Behaviour

Bard couldn't connect

### Expected Behaviour

Bard should just answer every single time

**Comment by tfraley** [comment]
I'm seeing the exact same error. 
Went through the readme and adding bard Key from cookies not dice. 
Did they change something ?

**Comment by xsbchen** [comment]
#9798 I created a PR for fix this, plz help to try

**Comment by AISLVE** [comment]
yes i will @xsbchen
