### ISSUE TITLE
[salesforce-search] Stay logged in

### ISSUE THREAD

**Issue by lukas1994** [raycast/extensions#9455]
### Extension

https://www.raycast.com/sven/salesforce

### Description

I have to login to salesforce multiple times per day. I've tried all kinds of salesforce settings and couldn't figure out a way to stop it. A co-worker is using https://www.scratchpad.com/ which never gets logged out. Would be great if someone can reproduce this behaviour here.

cc @joshknowles @pernielsentikaer

### Who will benefit from this feature?

Every Salesforce user!

**Comment by svenwiegand** [comment]
Hm, for me, the login is working for multiple days, but I'm not sure which Salesforce settings are influencing this. I get an access and a refresh token from Salesforce. If the access token expires, I get a new one using the refresh token. If the refresh token also expired, a relogin is necessary. Normal OAuth flow. Not much I can do about it.
