### ISSUE TITLE
Gitlab: More intuitive navigation

### ISSUE THREAD

**Issue by Loskir** [raycast/extensions#946]
# Extension – [GitLab](https://github.com/raycast/extensions/tree/0bf78cfe5a77b433271a3fce24438767eb7f4d85/extensions/gitlab/)
Author: @tonka3000

**Describe the feature and the current behavior/state.**
Currently the default action for many items is "Open in browser". I would like to see more consistent navigation, that allows me to navigate to the desired screen with a few enter clicks rather than with non-obvious shortcuts.

**So first of all: I suggest adding Project screen**

<img width="800" alt="изображение" src="https://user-images.githubusercontent.com/21295738/154802897-bf2760db-7906-4aee-a8fb-7ddf36b73692.png">

Right now it's only possible to jump directly from the projects list to issues/pipelines/etc using context actions or shortcuts.

<img width="400" alt="изображение" src="https://user-images.githubusercontent.com/21295738/154802928-ec7c9608-0b57-4302-92d1-85f2371b9383.png">

Adding Project screen will make navigation more intuitive.

### Next: Navigation to Project screen from "My Recent Activities" and "My Projects"
<img width="400" alt="изображение" src="https://user-images.githubusercontent.com/21295738/154803055-7b17ac73-e79c-4848-91ae-3ceda6234969.png">

There are no actions at all in "My Recent Activities" right now. In "My Projects" the default action is "Open in browser". I suggest changing that to "Open Project" which opens the project screen.

I might have already spent a few hours on this, so what do you all think? 😅

**Comment by Loskir** [comment]
Also would be nice to replace these
https://github.com/raycast/extensions/blob/0bf78cfe5a77b433271a3fce24438767eb7f4d85/extensions/gitlab/src/components/event.tsx#L135
https://github.com/raycast/extensions/blob/0bf78cfe5a77b433271a3fce24438767eb7f4d85/extensions/gitlab/src/components/event.tsx#L162
https://github.com/raycast/extensions/blob/0bf78cfe5a77b433271a3fce24438767eb7f4d85/extensions/gitlab/src/components/event.tsx#L179

with PushActions which navigate to the corresponding sections

**Comment by tonka3000** [comment]
Hi @Loskir ,

thanks for your feedback.

>There are no actions at all in "My Recent Activities" right now. In "My Projects" the default action is "Open in browser". I suggest changing that to "Open Project" which opens the project screen.

This kind of navigation was already in the extension (was a command called Project explorer, checkout the video in the first [PR](https://github.com/raycast/extensions/pull/2)) but I removed it for now because most users don't use the extension that way. I already prepared a different version, where a user can choose if the primary action should be open the project in raycast or in the browser. The default will be still `Open in Browser` because this is what most users use. That way you can choose between staying in raycast to explorer the project or open the project in the browser.

My Recent Activities will get the feature you describe but I need to finish some refactoring first.

**Comment by Loskir** [comment]
Thanks for your feedback. I'm looking forward to new improvements of this extension.

I've committed my work-in-progress of the Project screen along with some small fixes to a separate branch (https://github.com/Loskir/extensions/tree/gitlab-dev/extensions/gitlab), you might want to cherry-pick some of them.

**Comment by tonka3000** [comment]
@Loskir You can try out the PR #949 with the `Open Project` action (change in settings is required!) 

![CleanShot 2022-02-19 at 20 57 54](https://user-images.githubusercontent.com/3163807/154816999-6d4f3bea-a496-43af-8f6f-71f6bf44e836.png)
