### ISSUE TITLE
[AirPods Noise Control] Add the "Off" option

### ISSUE THREAD

**Issue by third774** [raycast/extensions#9467]
### Extension

https://www.raycast.com/chrahe/airpods-noise-control

### Description

I often turn noise control off in my home office where it's generally quiet so I don't need noise cancelling, and I want to make sure the batteries will last longer.

![image](https://github.com/raycast/extensions/assets/8732191/e44a360d-9554-4b7e-979a-187a008ef381)

### Who will benefit from this feature?

Anyone who wants to save battery on their airpods

**Comment by third774** [comment]
Bumping this — I might take a stab at this myself soon 😅

**Comment by iamyeizi** [comment]
@third774 I did a PR to fix this, but still no response from the author

**Comment by iamyeizi** [comment]
@raycastbot close this issue

**Comment by third774** [comment]
@iamyeizi awesome, thank you! 🙏🏻
