### ISSUE TITLE
[I Don't Have Spotify] Select default service

### ISSUE THREAD

**Issue by third774** [raycast/extensions#9468]
### Extension

https://www.raycast.com/sjdonado/idonthavespotify

### Description

Would be cool if the extension had the option to select which streaming service is preferred as the default option!

### Who will benefit from this feature?

Everyone, I think!

**Comment by sjdonado** [comment]
@third774 good idea, I'll work on it!

**Comment by third774** [comment]
Commenting to remove stale marker — I think this is a worthwhile feature!

**Comment by sjdonado** [comment]
Sorry that I haven't replied before. I have plans to implement this feature soon :)
