### ISSUE TITLE
[Obsidian] Search Media Obsidian Raycast hotkey not working

### ISSUE THREAD

**Issue by ammarhusain** [raycast/extensions#9485]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'length')

Hn:MediaGrid.tsx:13:10

---
10: import { SearchMediaPreferences } from "../utils/preferences"

### Steps To Reproduce

Set hotkey - Cmd+Alt+M for Obsidian Search Media

This raycast extension command works fine without the hotkey. With the hotkey I get this error 
<img width="743" alt="image" src="https://github.com/raycast/extensions/assets/4248914/7f10a3f7-c654-4532-9812-31f17e40eade">



### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by ammarhusain** [comment]
This is still an issue with the extension. When setting a hotkey and then triggering it here is the error I see 
<img width="745" alt="image" src="https://github.com/raycast/extensions/assets/4248914/53b31cd6-d961-4de8-a415-5d201f57681d">

**Comment by KevinBatdorf** [comment]
Thanks for reporting and sorry for missing the first report. Opened a PR here: https://github.com/raycast/extensions/pull/10286

**Comment by ammarhusain** [comment]
Thanks for the fix!
