### ISSUE TITLE
[GitHub] Unread notifications not properly triggering the menubar icon color change

### ISSUE THREAD

**Issue by PixelJanitor** [raycast/extensions#9505]
### Extension

https://www.raycast.com/raycast/github

### Description

Previously I remember having an orange GitHub icon in the menu bar if I had unread notifications. In recent past I've noticed that stop, but when clicking "View all notifications" in the dropdown it takes me to my inbox containing new and unread notifications.

I've logged out/back in to GitHub through the extension, generated new PAT, uninstalled/reinstalled extension entirely.

I'm on an M1 MBP running Sonoma 14.0

![CleanShot 2023-12-01 at 11 05 15@2x](https://github.com/raycast/extensions/assets/1648941/e16cccac-4407-4ef3-8932-95263ec7e971)

### Steps To Reproduce

1. Get new GitHub notification
2. Not see GitHub logo change in menu bar

I know this isn't helpful but it's a required field 🙃 Not really "Reproducible" per say

**Comment by thomaslombart** [comment]
Are you still getting new notifications in the `Notifications` command?

![CleanShot 2023-12-04 at 09 04 58@2x](https://github.com/raycast/extensions/assets/16003285/eae1c37b-3b78-4efc-b51c-8e41f20ff9fd)

**Comment by PixelJanitor** [comment]
I am, but not for all of my organizations. That looks to be the issue. I noticed the orange logo for the notification of your comment here, but when I went to `Notification` like you suggested, it doesn't contain any of my notifications from my work (@clerk) repos. When I trigger the menubar to go to my GitHub notification inbox the work notifications are there though.

**Comment by thomaslombart** [comment]
So you're getting notifications from personal stuff but not from your work organization, right? Could you please check if the Raycast extension has access to your organization, as shown below?

![CleanShot 2023-12-18 at 09 40 55@2x](https://github.com/raycast/extensions/assets/16003285/0938ec75-a281-418f-8ccb-f86819dd0bd9)
