### ISSUE TITLE
[Wemo] ... Just won't work anymore

### ISSUE THREAD

**Issue by EdFenner** [raycast/extensions#9522]
### Extension

https://www.raycast.com/iamnatch/raycast-wemo

### Description

This worked great for a long time. Strangely it always shows every device twice in the list.
It was still showing them all (twice) but wouldn't  actually control them anymore.
In looking at reproducing, I no longer get any devices loaded

### Steps To Reproduce

Reinstalled fresh - no longer works.

**Comment by IAmNatch** [comment]
I'm not seeing double, but I am seeing this error when I try to control a device:
<img width="757" alt="image" src="https://github.com/raycast/extensions/assets/15078788/56317efb-0771-4ed8-8fc2-4f2e6a7f8913">

**Comment by IAmNatch** [comment]
After further inspection, whenever we try to change a value we get an error:
```
connResetException:errors:721:14
Socket.socketOnEnd:node:_http_client:519:23
Socket.emit:node:events:526:35
Socket.emit:node:domain:488:12
```

I'm guessing, given that there has been no change in the sourcecode of this plugin, that this is the result of a firmware update to the wemos. My wemos are on version `WeMo_WW_2.00.11573.PVT-OWRT-Dimmer`.

[Node Red also has a wemo client inside its lib](https://github.com/node-red/node-red-nodes/blob/master/hardware/wemo/lib/wemo.js), so depending on the license I may be able to switch out the current lib for that one at a later date. Don't think I'd be able to dig too much deeper for a few weeks, but open to PRs if anyone wants to try it out.
