### ISSUE TITLE
[YouTube Downloader] Loading spinner is not ending after downloaded file

### ISSUE THREAD

**Issue by teziovsky** [raycast/extensions#9530]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

If I want to download any video as `mp3` everything is going all right, but the loading is not ending when the file is downloaded.

https://github.com/raycast/extensions/assets/36273653/c296040c-45c8-470c-b9c9-4b1a23235b63

### Steps To Reproduce

1. Copy the link to the YouTube video
2. Paste and choose `mp3`
3. Click download
4. Wait for the downloaded file
5. Check loading spinner 

### Current Behaviour

The loading spinner is spinning infinitely

### Expected Behaviour

Properly show that the file is downloaded correctly

**Comment by teziovsky** [comment]
It could be great to have an extension near audio formats like this:
`128kbps ({size_of_file} MB) [mp3]`
It will allow users to search by writing just typing `mp3`

**Comment by vimtor** [comment]
Hey @teziovsky!

1. Does the infinite spinner always happen? We are using the unofficial YouTube API and it's a bit flakky.
2. Sadly, more `kbps` are only available on YT premium #8123
3. Adding `[mp3]` to the audio formats is a great idea!

**Comment by teziovsky** [comment]
@vimtor 

1. Yes, every download
2. Well ok 🥲
3. Great 🫶

**Comment by vimtor** [comment]
Regarding the infinite spinner, it probably has to do with your `ffmpeg` installation. I would suggest trying to reinstall it to see if the problem persists. As for the `[mp3]`, I will add it in one day along with the next batch of updates.

**Comment by teziovsky** [comment]
😔
