### ISSUE TITLE
[Apple Reminders] The date selection field is filled with time, even if it is not specified

### ISSUE THREAD

**Issue by borzov** [raycast/extensions#9538]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

If you use the window for quickly adding a task and specify it without a specific time in the date selection field, for example, “Tomorrow,” then the exact time of 12:00 will definitely be added to the window, although in fact it will not be set. This seems wrong because the reminder is set for a specific date without time. Also missing is the ability to change the date display format, it would be great to be able to fix it in the settings or use the one installed on the system.

![20231204233418-New Issue · raycast:extensions-t026m](https://github.com/raycast/extensions/assets/1586471/7dbabc01-f057-4f82-9ce9-ab55bd88b52d)

![20231204233444-New Issue · raycast:extensions-8hy7m](https://github.com/raycast/extensions/assets/1586471/5e4ebbd9-50e7-4e4d-ae9e-8aa1e07fc662)

### Steps To Reproduce

1. Open the window for adding a reminder
2. In the date selection field, select a day without specifying the time
3. After closing the drop-down list, the date will be displayed along with the time, although adding to reminders without the exact time

**Comment by tleo19** [comment]
I am pretty sure this has been fixed

**Comment by thomaslombart** [comment]
Thanks for reporting the issue. It looks like a bug on our native date picker. We'll fix it!

**Comment by thomaslombart** [comment]
Fixed in release v1.66! 🎉
