### ISSUE TITLE
[0x0] Ability to upload selected file

### ISSUE THREAD

**Issue by jiserra** [raycast/extensions#9539]
### Extension

https://www.raycast.com/pseudobun/0x0

### Description

- Is there any way to grab the selected file from the Finder and upload it? I remember seeing Raycast API support for selected File?

### Who will benefit from this feature?

Everyone who uses this extension, especially if you configure a hotkey

**Comment by pseudobun** [comment]
@jiserra so sorry for such a late response, I totally missed the notification. Could you please elaborate what exactly do you mean with "selected file"?
