### ISSUE TITLE
Menu bar reminders don't show in the menu bar

### ISSUE THREAD

**Issue by Jason-JL** [raycast/extensions#9543]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Menu bar reminders don't show in the menu bar.

### Steps To Reproduce

<img width="506" alt="Screenshot 2023-12-05 at 14 32 57" src="https://github.com/raycast/extensions/assets/150642065/87b36315-7ab8-4d33-8e41-d66c7f5091ed">
<img width="506" alt="Screenshot 2023-12-05 at 14 33 24" src="https://github.com/raycast/extensions/assets/150642065/eefb37f9-6405-40d1-a17a-308126f1c793">

**Comment by thomaslombart** [comment]
Do you have reminders due for today in the `My Reminders` command?
