### ISSUE TITLE
[Library Genesis] ...

### ISSUE THREAD

**Issue by Saidelocha** [raycast/extensions#9546]
### Extension

https://www.raycast.com/yz3440/library-genesis

### Description

The search command is not working.
A typeerror appear, see screenshot.
<img width="848" alt="Capture d’écran 2023-12-05 à 17 53 23" src="https://github.com/raycast/extensions/assets/97402209/ee01f41d-4fbc-4b3b-88df-59990a2af033">

### Steps To Reproduce

Any search

**Comment by j3lte** [comment]
Fixed in #9549, issue can be closed

**Comment by j3lte** [comment]
@raycastbot close this issue
