### ISSUE TITLE
[Spotify Player] ... my favorite list doesn't play

### ISSUE THREAD

**Issue by pabloealarcon** [raycast/extensions#9550]
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```
Error: Invalid context uri

si:play.ts:68:10

---
65:     }
66: 
67:     console.log("play.ts Error: ", error)

### Steps To Reproduce

When I click on my favorite list, there is an error.

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by peduarte** [comment]
Hey @bkeys818, could this be related to the changes in [this PR](https://github.com/raycast/extensions/pull/8616)?

**Comment by bkeys818** [comment]
@peduarte That'd be my assumption, but I can't repeat the bug.

**Comment by thomaslombart** [comment]
I'm closing the issue to maintain a clean backlog as it is becoming stale. Please feel free to reopen it if you still experience the issue.
