### ISSUE TITLE
[Mound] Cannot open Pile in the Pile app after using the extension to create a post

### ISSUE THREAD

**Issue by nukesean** [raycast/extensions#9557]
### Extension

https://www.raycast.com/desmondsofua/mound-for-pile

### Description

The instant I create a post with this extension, I am no longer able to open the Pile in the Pile app. Whenever I try, it just shows this blank, gray window:

![image](https://github.com/raycast/extensions/assets/69487134/17771bf4-de99-4beb-88ff-7db35d7d312c)

To test this issue, I first did the following without using the extension:
1. I made a new Pile using the Pile app
2. I made a new post in that Pile using the Pile app
3. I closed the Pile
4. I re-opened the Pile in the Pile app and did not have any issues

Next, I tested what happened when I used the Mound extension:

6. I created a new post in the same Pile using the Mound extension
7. I checked the Pile app with the Pile already open and did not see the new post displayed
8. I closed the Pile and tried re-opening it in the Pile app, at which point I saw the blank, gray window shown in the screenshot

I also tried creating a new Pile with the extension rather than with the Pile app, and it behaved in exactly the same way as soon as I used the extension to make a new post.

Interestingly, all the posts in the affected Piles are still listed when I open the extension, so it doesn't seem like the files are completely corrupted or something. However, something is clearly getting messed up when I use this extension, because as soon as I use it to make a post, I can no longer open the Pile in the Pile app.

Specs:
M1 Mac Mini
Sonoma 14.1.2
Pile app version 0.8.1 (0.8.1)
Raycast v1.63.0
Mound latest version (just installed from the store)

### Steps To Reproduce

1. Use the extension to create a new post
2. Try to open the Pile in the Pile app

**Comment by cr34t1ve** [comment]
@nukesean thank you for pointing this out early. I have pushed a quick fix.

To resolve the previous please follow the following steps to have Pile open up normally

1. Go to your root directory and find the `Piles` folder
2. Open up `index.json` and find the pile you made the post in
3. Navigate to that folder in your finder
4. In that folder you should see an `index.json`. Open that in a text editor of your choice and go through it. You should see your posts. One (or more) should have `"highlight": "none",
      "highlightColor": "transparent",`
Change that to 
`"highlight": null,
      "highlightColor": null,`.
Everything should work normally after that!
