### ISSUE TITLE
Gmail guide does not work

### ISSUE THREAD

**Issue by chadlavi** [raycast/extensions#9563]
### Description

When you follow the Gmail guide to set up OAuth access, everything works as expected in console.cloud.google.com when setting it up, but you get a 403 when you try to use the oauth clientid to authorize from Raycast.

## To reproduce

1. Install the Gmail extension in Raycast
2. Go to https://github.com/raycast/extensions/blob/2fc991f5aa35df3b423b162641d7414811bf9451/extensions/gmail/README.md and follow the setup instructions

Expected: You are able to set up OAuth in console.cloud.google.com and then are able to use it to sign in to your Google account in Raycast

Actual: You will be able to set up OAuth but when you try to sign in to your google account in Raycast you will get a 403 error.

**Comment by paulora2405** [comment]
I can confirm this is still happening.

**Comment by thomaslombart** [comment]
@tonka3000 fyi

**Comment by tonka3000** [comment]
@chadlavi Did you do the following step from the guide

> Goto to Test Users and add the email address you wanna manage via Raycast

Make sure it is the email address you are using.
