### ISSUE TITLE
[Toggle Menu Bar] ... Another toggle option please

### ISSUE THREAD

**Issue by arfung** [raycast/extensions#9564]
### Extension

https://www.raycast.com/iamyeizi/toggle-menu-bar

### Description

Hi, I'd love it if you added a third configuration option to the "Toggle Menu Bar" Raycast extension. That is to add toggle between "In Full Screen Only - Never" 

### Who will benefit from this feature?

My use case is that I usually want the menu bar to show (not hide) all of the time (in both full screen and normal windowed). However, when I show presentations or watch videos in full screen, I'd like the menu bar to be hidden.

I think other people might have this use case also.

Thank you for a great extension!

**Comment by iamyeizi** [comment]
Hi! The next week I will be trying to do that

**Comment by arfung** [comment]
Excellent. Thank you very much!—archonfung.net | transparencypolicy.net On Dec 8, 2023, at 14:47, iamyeizi ***@***.***> wrote:﻿
Hi! The next week I will be trying to do that

**Comment by iamyeizi** [comment]
@raycastbot reopen this issue
@arfung soon 🤠

**Comment by iamyeizi** [comment]
@raycastbot close this issue
