### ISSUE TITLE
[Obsidian] Times are incorrect

### ISSUE THREAD

**Issue by joshtownley** [raycast/extensions#9566]
### Extension

https://www.raycast.com/KevinBatdorf/obsidian

### Description

For the Append to Daily Note command, I'm using "- {hour}:{minute}: {content}"
Mostly works great, but the time recorded is incorrect, and does not match the time on my computer (inserts 1 hour behind). 
Perhaps not picking up daylight savings time, or incorrect timezone?

### Steps To Reproduce

- Run the command 'Append to Daily Note' with the {hour} element in the template

### Current Behaviour

e.g. Inserts to note with a time stamp of 15:06

### Expected Behaviour

e.g. Should insert the time stamp as 16:06

**Comment by KevinBatdorf** [comment]
It just uses `(new Date()).toLocaleTimeString()`. What happens if you type that in a browser console?

![CleanShot 2023-12-06 at 12 46 23@2x](https://github.com/raycast/extensions/assets/1478421/903f2800-5bb9-401b-8536-db13e88bd2f8)

(This is accurate where I live)

**Comment by joshtownley** [comment]
Thanks for the quick reply.
Strange, (new Date()).toLocaleTimeString() give the correct time for me in the browser, but it doesn't match the time logged in Obsidian:
<img width="762" alt="Screenshot 2023-12-06 at 8 17 56 pm" src="https://github.com/raycast/extensions/assets/95601566/10c8099f-9a09-4ef9-97f0-71e79f14d57b">
