### ISSUE TITLE
[Spotify Player] Can't play music from Search command

### ISSUE THREAD

**Issue by Madofa** [raycast/extensions#9568]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Hi!
There is no way that performing a search and finding an artist will play the music.
I have also tried it from albums or popular songs and it doesn't work either.

### Steps To Reproduce

3

**Comment by peduarte** [comment]
This sounds like it _could_ be related to this https://github.com/raycast/extensions/issues/9649#issuecomment-1917118251
