### ISSUE TITLE
[Spotify Player] ...Menu bar player has encountered an error

### ISSUE THREAD

**Issue by ortonomy** [raycast/extensions#9571]
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```
{"_isRayError":true,"code":16,"title":"Could not initialize OAuth","name":"Error","message":"OAuth request creation is not available when command is launched in background","stack":"Error: OAuth request creation is not available when command is launched in background\n    at Rr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:25:230)\n    at Ye (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6249)\n    at ht (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6374)\n    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6139)\n    at process.processImmediate (node:internal/timers:478:21)","breadcrumbs":[{"level":"debug","category":"Request","message":"","timestamp":"2023-12-06T14:25:47.579Z","data":{"function":"getApplications"}}]}: 


```

### Steps To Reproduce

I've been using it for months. Now it just doesn't work. I keep logging in and succeeding, but it just stays the same

### Current Behaviour

-

### Expected Behaviour

-

**Comment by gpnagy** [comment]
I just installed Raycast for the first time and running into the same issue with the Spotify extension.

`{"_isRayError":true,"code":16,"title":"Could not initialize OAuth","name":"Error","message":"OAuth request creation is not available when command is launched in background","stack":"Error: OAuth request creation is not available when command is launched in background\n    at Rr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:25:230)\n    at Ye (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6249)\n    at ht (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6374)\n    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6139)\n    at process.processImmediate (node:internal/timers:478:21)","breadcrumbs":[{"level":"debug","category":"Request","message":"","timestamp":"2023-12-13T20:06:46.522Z","data":{"function":"getApplications"}}]}: 
`

**Comment by sxn** [comment]
hey @ortonomy & @gpnagy, thanks for reporting this.

There's a bug with menu bar commands that use OAuth and are re-run at very short intervals (the Spotify menu bar command runs every 10 seconds) that makes it so that you have to make sure you complete authentication before a background run can be launched. 😅 I'm looking into fixing that, but in the mean time you should be able to work around it by running a different command (like `Your Library`) and authenticating from that. Once you're authenticated, the menu bar command should work fine, too.

**Comment by gpnagy** [comment]
@sxn Thanks so much for the reply. Confirming that using the `Your Library` command worked to establish the connection Spotify and the menu bar player is working now as well. Very much appreciate your support and amazing work on this project. It's fantastic!

**Comment by marcelscruz** [comment]
Using your "Your library" doesn't work for me, as get logged out of Spotify a few minutes later.
Is there any other workaround, or is a fix for this in the pipeline?
Thanks!

**Comment by thomaslombart** [comment]
This should have been fixed as part of release v1.65. So I'm closing this issue to maintain a clean backlog. Feel free to comment it if you still have the problem.

**Comment by marcelscruz** [comment]
Unfortunately still happening to me, even when signing in through "Your library".
I'm on 1.66.2.

#### Error:
```
{"_isRayError":true,"code":16,"title":"Could not initialize OAuth","name":"Error","message":"OAuth request creation is not available when command is launched in background","stack":"Error: OAuth request creation is not available when command is launched in background\n    at Rr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:25:230)\n    at Ye (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6249)\n    at ht (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6374)\n    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6139)\n    at process.processImmediate (node:internal/timers:478:21)","breadcrumbs":[{"level":"debug","category":"Request","message":"","timestamp":"2024-02-06T02:23:33.767Z","data":{"function":"getApplications"}}]}: 


```

**Comment by peduarte** [comment]
@sxn is this something we recently tried to fix?

**Comment by sxn** [comment]
@peduarte not this particular issue.

we recently fixed a bug that made it hard to authenticate to OAuth via the menu bar command, because you had to finish the entire process before the next background run kicked in.

In this case, it sounds like @marcelscruz logged in just fine, but then for some reason (token expired, something else etc) was logged out. So the next background run kicked in, tried to initialize OAuth and…that's not allowed in background runs. 😅

**Comment by marcelscruz** [comment]
Exactly, I can log in and the menu bar shows the current song and all, but after some time it crashes.

**Comment by ortonomy** [comment]
Did this ever get fixed?

**Comment by ortonomy** [comment]
No, it was never fixed. 

> In this case, it sounds like @marcelscruz logged in just fine, but then for some reason (token expired, something else etc) was logged out. So the next background run kicked in, tried to initialize OAuth and…that's not allowed in background runs.

Yeah, this just happened to me. The menu bar item crashed and stopped working after 24 hours. This is still borked/not working. Uninstalled.
