### ISSUE TITLE
[Set Audio Device] Enabling "Include AirPlay Speakers" makes nothing show up under the "Set Output Device" command

### ISSUE THREAD

**Issue by danvpeterson** [raycast/extensions#9574]
### Extension

https://www.raycast.com/benvp/audio-device

### Description

With "Include AirPlay Speakers" off, everything seems to work as expected. But as soon as I turn that option on and try to use the "Set Output Device" command it just tells me there are no results.

### Steps To Reproduce

1. Turn on "Include AirPlay Speakers"
2. Run "Set Output Device"
3. See the "No Results" graphic

**Comment by demidchick** [comment]
The same problem occurs for me

**Comment by apfelbaum021** [comment]
yes, same problem here
