### ISSUE TITLE
[TinyPNG] ... work with Finder replacements

### ISSUE THREAD

**Issue by yes-captain-75** [raycast/extensions#9576]
### Extension

https://www.raycast.com/kawamataryo/tinypng

### Description

Work with finder replacements such as PathFinder.

### Who will benefit from this feature?

Apple's finder is severely limited. PathFinder offers better tabs and dual pane support just to name a few of its many features. I'm sure there would be many non-finder uses who could benefit from this. 

Great to be able to compress images without having to visit TinyPNGs site. Great job! :)

### Anything else?

I tried running your raycast extension in PathFinder and got the Error "Finder isn't the frontmost application"

**Comment by kawamataryo** [comment]
OK.  I will try to fix it.　This PR would be helpful. 
https://github.com/raycast/extensions/pull/8412
