### ISSUE TITLE
[Rocket.Chat] Request failed with status code 429

### ISSUE THREAD

**Issue by ulziibat-n** [raycast/extensions#9579]
### Extension

https://www.raycast.com/alex-w0/rocket-chat

### Description

Getting this error: Request failed with status code 429
Please see this screen recording https://jmp.sh/CBZsMc8J

### Steps To Reproduce

I have configured the access token with Two Factor Authentication disabled. https://jmp.sh/bBfFqqu8

**Comment by alex-w0** [comment]
@raycastbot close this issue
