### ISSUE TITLE
When loading profile, bookmarks sometimes are not loaded JS Heap out of memory

### ISSUE THREAD

**Issue by koenvb** [raycast/extensions#958]
# Extension – [Google Chrome Profiles](https://github.com/raycast/extensions/tree/022b60caf8144b5bf5007db8d0ee6f3b58e8da47/extensions/google-chrome-profiles/)
Author: @frouo

## Description

Sometime when loading the profiles it errors out when chosing one of the profiles

## Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

__node_internal_captureLargerStackTrace:errors:464:5
NodeError:errors:371:5
Worker.[kOnExit]:worker:279:26
Worker.<computed>.onexit:worker:201:20
```

## Steps To Reproduce

1.Show profiles
2. Choose profile 
3. load the bookmarks -> then it fails

### Raycast version
Version: 1.28.0

**Comment by frouo** [comment]
Hello @koenvb, thanks for your feedback.

Raycast extensions have a limited amount of memory they can use. Maybe your bookmarks chrome file is big. Can we check that? Here is how to:

* open the profile that generates this error
* type in the search bar: `chrome://version` (note that, for chrome security reason, `chrome://...` url cannot be launch from external command, so it cannot be launched using google chrome profile raycast extension)
* copy the "Profile Path"
* then run the command line : `ls -alh "paste-here-the-path"`
* Search for the size (in bytes) of the file named `Bookmarks`

Thanks

![image](https://user-images.githubusercontent.com/2499356/155289585-f2294cd4-7586-44fa-8d52-85ad737980ee.png)

<img width="599" alt="image" src="https://user-images.githubusercontent.com/2499356/155290627-66ec9647-455e-4193-bbea-652a54891668.png">

**Comment by koenvb** [comment]
It feels to me there is some memory leak or so, but hereby the requested info
Before I was running it as a script-command and that worked ok.

(love the extension by the way, it is a blessing! thanks for the work on this one!)

![CleanShot 2022-03-02 at 16 53 39@2x](https://user-images.githubusercontent.com/76891/156398060-98fb9300-91f3-4fad-a95f-c64872155e3b.png)

**Comment by frouo** [comment]
Ok. I learnt that once opened a Raycast extension is allowed to 100mo memory. Which seems more than enough given the size of the files. 

An enhancement I should do is to use `fs` instead `AppleScript` to browse files. Maybe it could help fixing the issue. I'll do this soon.

> love the extension by the way, it is a blessing! thanks for the work on this one!

Thank you, it's very nice to read this 🙏🏻
