### ISSUE TITLE
[Browser Bookmarks] Request support for Brave Nightly browser

### ISSUE THREAD

**Issue by QuantumRoseinAmethystVase** [raycast/extensions#9591]
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

Currently, Browser Bookmarks support Brave and Brave Beta, but do not support Brave Nightly. I think it shouldn't be difficult to improve the support from Beta to Nightly.

### Who will benefit from this feature?

Currently, Browser Bookmarks support Brave and Brave Beta, but not Brave Nightly. I think it shouldn't be difficult to improve the support from Beta to Nightly

**Comment by tleo19** [comment]
Created a PR for Brave Nightly.
