### ISSUE TITLE
[Brave] Requesting support for Brave Nightly browser

### ISSUE THREAD

**Issue by QuantumRoseinAmethystVase** [raycast/extensions#9592]
### Extension

https://www.raycast.com/ron-myers/brave

### Description

As a "Brave" extensions, I believe that its bookmark retrieval should support Brave Nightly.

**Comment by tleo19** [comment]
Created a PR for your request 

https://github.com/raycast/extensions/pull/9604

**Comment by QuantumRoseinAmethystVase** [comment]
> Created a PR for your request
> 
> #9604

Thank you so much!
