### ISSUE TITLE
[elgato-key-light] Add a setBrightness command to set a specific value

### ISSUE THREAD

**Issue by ahpook** [raycast/extensions#9597]
### Extension

https://www.raycast.com/thomas/elgato-key-light

### Description

Hi, I'd like to add a command to set the key light brightness to a specific value rather than just increment it up or down. I have a branch that adds the command to the manifest and works with hardcoded values, but I'm having a hard time (typescript noob) navigating how this particular extension does function dispatch, so that I can modify it to accept an argument. 

Specifically the [docs on accessing arguments](https://developers.raycast.com/information/lifecycle/argument) conflict with the `run` function in the extension's `util.ts`, which does not allow arguments. Even hacking around that convention, I wasn't able to get the `props.arguments` accessor working and hit the limit of my time to poke at it. Could someone better versed in this extension help get it over the line? I think it'd be a useful addition, to go from 5 to 50 percent brightness in one jump!

### Who will benefit from this feature?

Anyone who uses the extension and wants quicker control over the light brightness.

### Anything else?

My branch is at : https://github.com/ahpook/raycast-extensions/tree/ahpook/elgato-setbrightness/extensions/elgato-key-light/src

cc @omarshahine and @thomaspaulmann since you have worked on this before 🙏 TYVM!

**Comment by thomaspaulmann** [comment]
Hey @ahpook let me know if you still want to pick this up. Would be a great addition. We made it easier to work with arguments now.

**Comment by ahpook** [comment]
@thomaspaulmann oh that's awesome to hear! I was sad that it got auto-closed. Is there a doc or another plugin example I can follow to see how passing the argument should work now?
