### ISSUE TITLE
[Bitwarden] Search Vault Fails to Load Items

### ISSUE THREAD

**Issue by LanikSJ** [raycast/extensions#9599]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

I get "Failed to load items" error when I use the Search command and unlock my vault with my master key. I've tried to refresh my Client ID and Client Secret with no luck.  BW CLI also is able to login and see the items in my vault

### Steps To Reproduce

1. Open Search Vault command
2. Unlock with Master Key
3. Sync your vault
4. Wait for the error message

### Current Behaviour

The vault never loads any items even after refreshing my Client ID and Client Secret

### Expected Behaviour

I should see the list of my items in the vault and be able to view the contents

**Comment by bxb100** [comment]
https://github.com/bitwarden/clients/issues/7126

**Comment by LanikSJ** [comment]
Thank you this makes me sad. 😭

**Comment by luckman212** [comment]
I'm sad too. Bitwarden got [$100MM of funding][1] last year, but if anything development seems to have [slowed down][2]. Where did all that money go? They seem to struggle with the most basic things sometimes.

[1]: https://bitwarden.com/blog/accelerating-value-for-bitwarden-users-bitwarden-raises-usd100-million/
[2]: https://github.com/bitwarden/clients/graphs/code-frequency

**Comment by rightsaidfred99** [comment]
> I'm sad too. Bitwarden got [$100MM of funding](https://bitwarden.com/blog/accelerating-value-for-bitwarden-users-bitwarden-raises-usd100-million/) last year, but if anything development seems to have [slowed down](https://github.com/bitwarden/clients/graphs/code-frequency). Where did all that money go? They seem to struggle with the most basic things sometimes.

Agreed, as a user from the early days - just bugs, bugs, bugs everywhere.

**Comment by jordangalvan** [comment]
> [bitwarden/clients#7126](https://github.com/bitwarden/clients/issues/7126)

this was closed yesterday, hopefully fixed soon?
