### ISSUE TITLE
[Dev Tools Feature Request] Add new debug action to keep Raycast opened

### ISSUE THREAD

**Issue by loris** [raycast/extensions#96]
It would be great to have the ability (could be an entry in the Debug menu to toggle it on/off) to make the Raycast window kept opened even if the focus is lost. This way, we could develop extensions in our editor and see the changes live in the Raycast window.

**Comment by mattisssa** [comment]
Introduced in the `v1.38.0` 🚀

**Comment by pistazie** [comment]
@thomaspaulmann How does one enable this feature?

**Comment by pistazie** [comment]
> [@thomaspaulmann](https://github.com/thomaspaulmann) How does one enable this feature?

I found it 🙃
Raycast Settings -> Advanced -> "Keep window always visible during development"
