### ISSUE TITLE
[KeePassXC] Add PIN to use extension

### ISSUE THREAD

**Issue by boggleboggle** [raycast/extensions#9600]
### Extension

https://www.raycast.com/zkytech/keepassxc

### Current behavior:
Once you have entered the KeePass password and key file, anyone with access to the computer can access all the passwords in the database. This is potentially insecure - particularly on laptops, which could be used in public areas.

### Suggested feature:
Add an option to add a PIN, which would be required to access the database.

### Who will benefit from this feature?

Users who are concerned about unauthorized access to the database.

**Comment by Sulfyderz** [comment]
Hello,

It sounds a nice idea. @zkytech is the owner of the extension. I don’t know what he would think about it.
