### ISSUE TITLE
[monday.com] ...

### ISSUE THREAD

**Issue by Gsutt89** [raycast/extensions#9616]
### Extension

https://www.raycast.com/freak4pc/monday-com

### Description

Do you ability to add either new boards or favourites it’s great being able to select your favourite board. However, there are multiple awards that my organisation needs to be on top off and it would be great to be able to access his board quickly.

### Who will benefit from this feature?

I think anyone who stars any of the boards in monday.com, with really feel the benefit of this, as it will give him a quick access of a neat without them, having to go to laborious task of finding the board.

### Anything else?

Start but also thank you so much for creating this app. It really has saved me a lot of time already and I hope that continues to do say anything in my suggestion is to come to fruition. Please let me know

**Comment by freak4pc** [comment]
Hey @Gsutt89,
Thanks for the kind words! 
I don't have any plans to add new features soon but I have some suggestions on how you can achieve what you want:

First, I personally have a hotkey to my "Recent Boards" which really help with accessing all the latest work you've done.

Second, and even easier, you could make a Quicklink to your board, for example like this:
<img width="1512" alt="image" src="https://github.com/raycast/extensions/assets/605076/33df164e-3dae-4f45-bf4d-31c8001ad826">

Then you can quickly just type in your board name, of even apply a hotkey directly to your Quicklink to open it immediately.
Hope this help! 

@raycastbot close this issue
