### ISSUE TITLE
CopyQ not found, or CopyQ server not running

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#9626]
### Extension

https://www.raycast.com/andrewcincotta/copyq-clipboard-manager

### Description

It was working fine before I updated to version 2

### Steps To Reproduce

1. installing copyq
2. setting executable path to /Applications/CopyQ.app
3. running raycast extension "view default tab"

### Current Behaviour

CopyQ not found, or CopyQ server not running
Please check your CopyQ path in preferences, and make sure CopyQ server is running.

**Comment by andrewcincotta** [comment]
> ### Extension
> https://www.raycast.com/andrewcincotta/copyq-clipboard-manager
> 
> ### Description
> It was working fine before I updated to version 2
> 
> ### Steps To Reproduce
> 1. installing copyq
> 2. setting executable path to /Applications/CopyQ.app
> 3. running raycast extension "view default tab"
> 
> ### Current Behaviour
> CopyQ not found, or CopyQ server not running Please check your CopyQ path in preferences, and make sure CopyQ server is running.
> 
> ### Expected Behaviour
> _No response_

Thanks for using the extension Roman! Best bet would be to add copyQ to your path and then use /usr/local/bin/copyq. Did you install CopyQ using homebrew or something else? Also, you can try /Applications/CopyQ.app/Contents/MacOS/CopyQ

**Comment by romanskorobagatko** [comment]
I installed CopyQ using homebrew. Unfortunately I’m not familiar with the process of "adding copyQ to a path", could you please explain how to do this? /Applications/CopyQ.app/Contents/MacOS/CopyQ didn’t work.

**Comment by andrewcincotta** [comment]
@raycastbot close this issue
