### ISSUE TITLE
[Day One] Day One CLI reported as missing even after installing

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#9629]
### Extension

https://www.raycast.com/AntonNiklasson/day-one

### Description

I installed the Day One extension, and when I attempted to use its one command ("Add Entry"), I get an error:

![2023-12-09 (10 42 46) Arc Dev@2x](https://github.com/raycast/extensions/assets/22610/73fcfafd-9eca-4064-921a-325e9906e7f3)

After installing the [Day One CLI ](https://dayoneapp.com/guides/tips-and-tutorials/command-line-interface-cli/), the error message persists.

### Steps To Reproduce

Apple M1 Max, macOS Sonoma 14.1.2 (23B92)

1. Install Day One extension
2. Attempt to run Add entry command
3. Get error to install Day One CLI
4. Install Day One CLI
5. Still get error.

### Current Behaviour

See above.

### Expected Behaviour

An entry should be able to be created.

**Comment by AntonNiklasson** [comment]
Thank you reporting! I'll try to take some time tomorrow to fix this.
