### ISSUE TITLE
[Visual Studio Code - Project Manager] ...

### ISSUE THREAD

**Issue by harshBx** [raycast/extensions#9632]
### Extension

https://www.raycast.com/MarkusLanger/vscode-project-manager

### Description

Remote ssh project not able to open

### Steps To Reproduce

using visual studio code add a remote ssh project in code,
try opening it using extension

**Comment by deepauto-test** [comment]
Hi, I believe this issue should be re-opened. I am experiencing the same issue.

So basically it seems that the Raycast Extension behaves differently than the VSCode extension.

The Project Manager VSCode Extension opens well with a SSH remote project, but Raycast fails to open the same project.

**Comment by kbumsik** [comment]
Hi, I believe this issue should be re-opened. I am experiencing the same issue.

So basically it seems that the Raycast Extension behaves differently than the VSCode extension.

The Project Manager VSCode Extension opens well with a SSH remote project, but Raycast fails to open the same project.

**Comment by theherk** [comment]
I've seen a few issues related to this. For example, #8692. Which had a fix going in #8693 that seems to have stalled. The extension detects remote paths, then opens them with the cli and the `--remote` argument. Where that goes awry, I'm unsure, but maybe follow up on the other issue if that is related.
