### ISSUE TITLE
1password

### ISSUE THREAD

**Issue by rightsaidfred99** [raycast/extensions#9637]
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

It seems after following the guide, the defaults for this setup don't work 

### Steps To Reproduce

Install 1Password 8
Install and activate the CLI (through the developer settings form the official documentation)
macOS will see op in terminal
Raycast's extension will not and you'll just get a tutorial window every time. 

### Current Behaviour

Raycast's extension will not work, only terminal, and you'll just get a tutorial window every time. 

### Expected Behaviour

It should work after installing 1password cli if macOS can see OP

**Comment by dembicki** [comment]
I was facing simiilar issue and here is workaround (assuming you installed 1password cli using brew):
1. Check where your 1password-cli is installed using 
`brew info 1password-cli`
2. Go to extension settings and update `1Password CLI path` field. 

For me the path was `/opt/homebrew/Caskroom/1password-cli/2.23.0/op`

**Comment by rightsaidfred99** [comment]
Thanks @dembicki , I agree the default path was setup differently. 

I think for non tech users, it would be quite difficult to perhaps guess the caskroom path. Not sure if it's a bug or not but it stumped me for a while as all the settings were matched up to the guides.

**Comment by kjeldahl** [comment]
The path can be found by using the which command in a terminal:

```
> which op
/opt/homebrew/bin/op
```

In this case the path is a symlink to the specific path `/opt/homebrew/Caskroom/1password-cli/2.23.0/op`. I recon that brew always symlinks the binaries it installs to `$HOMEBREW_PREFIX/bin/` so it would be an idea to use that path instead to avoid having to update it again when 1Password is updated to a newer version.

**Comment by mbugbee** [comment]
I'm having a related issue caused by syncing between a Silicon and Intel based Mac.  Homebrew installs to /opt/homebrew on Silicon and /usr/local/homebrew.  So when the 1Password CLI path syncs to the other computer be other other will be broken.

**Comment by kjeldahl** [comment]
@mbugbee As a workaround you could symlink the path on one of the computers and use that path in Raycast.
So on the intel mac you could run something like `mkdir /opt/homebrew && ln -s /usr/local/homebrew/bin /opt/homebrew/` and use `/opt/homebrew/bin/op` in Raycast.

**Comment by mbugbee** [comment]
@kjeldahl that worked great, thanks!

**Comment by kayvanaarssen** [comment]
Installed via 1Password Package location `/usr/local/bin/op` but still does not work. Getting the setup instructions every single time.

**Comment by rightsaidfred99** [comment]
Yeah, I have to say creating mkdir /opt/homebrew && ln -s /usr/local/homebrew/bin /opt/homebrew/ doesn't seem to work for me either. I gave up and just used 1Passwords native Control + Spacebar as it's reliable

**Comment by semanser** [comment]
What helped for me was enabling "Keep 1Password in the menu bar" option. It seems like the 1password cli works only if 1password is active (or **_at least_** the menubar icon is enabled).

<img width="782" alt="Screenshot 2024-02-06 at 17 23 44" src="https://github.com/raycast/extensions/assets/4020045/9a4c7bba-8611-4205-96f2-3a0a11a2c14c">

**Comment by kayvanaarssen** [comment]
Already have that one enabled by default :-D But no luck so far
