### ISSUE TITLE
[Apple Reminders] Url field in `Create Reminder` form

### ISSUE THREAD

**Issue by bharam** [raycast/extensions#9641]
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

It would be nice the create reminder action had a ﻿url field in the form. Currently, users have to put links in the ﻿notes field, whereas the Apple Reminders app has a dedicated ﻿url field for each reminder.

### Who will benefit from this feature?

Users who create reminders with a link related to the task.

**Comment by thomaslombart** [comment]
Unfortunately, Apple's APIs don't provide support for the URL field so I'll mark this issue as canceled 😞
