### ISSUE TITLE
Google Bard - Bard not connecting despite adding Cookie key

### ISSUE THREAD

**Issue by micmintran** [raycast/extensions#9643]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

Despite having followed instructions and adding the `__Secure-1PSID` key, I get the "Bard couldn't connect' prompt (screenshot attached)
![Screenshot 2023-12-11 at 2 59 39 PM](https://github.com/raycast/extensions/assets/68480724/0e05e121-d888-4207-bb59-f272f70bb347)

### Steps To Reproduce

Followed instructions listed at https://www.raycast.com/EvanZhouDev/raycast-bard-ai

**Comment by xsbchen** [comment]
#9798 I created a PR for this, plz help to try
