### ISSUE TITLE
[Bear Notes] ...

### ISSUE THREAD

**Issue by stevenge37** [raycast/extensions#9648]
### Extension

https://www.raycast.com/hmarr/bear

### Description

Create the bear note easier. Right now I need to input such as title, text, tags etc. The requirement is create a new bear note and focus on the bear window to keep writing.

**Comment by juanbanchero** [comment]
You can do it on the search command. If you start typing and the note does not exists, it provides you with a "create note". Does it help?

**Comment by stevenge37** [comment]
Hi
I've tried this solutuon. looks it work for me, thanks for reply.

发自我的 iPhone

在 2023年12月12日，18:23，Juan Banchero ***@***.***> 写道：

﻿

You can do it on the search command. If you start typing and the note does not exists, it provides you with a "create note". Does it help?
