### ISSUE TITLE
[Arc] Quicklink or command to open/navigate to favourited tabs

### ISSUE THREAD

**Issue by madebymalavika** [raycast/extensions#9661]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

I want to create a quick link or command that opens or navigate to one of my "favourited" tabs. Right now the quick link I have opens the URL in a new tab that isn't pinned or favourited. I'm not sure how to do this using the search tabs command, though it might be possible.

Thanks!

### Who will benefit from this feature?

Most Arc users probably would want to navigate to their favourited tabs quickly.

**Comment by tleo19** [comment]
Hey, Could you maybe send a screen recording of what you are currently trying to do?

**Comment by madebymalavika** [comment]
Hi there! 
@tleo19 So this notion page for example is pinned as a favourite on arc but i have a quick link to open the same page and it opens in a new page, im wondering if i can navigate to the favourited tabs like how it shows up in the "search tabs" easier through a command or a hotkey. Let me know if this makes more sense, thank you! 


https://github.com/raycast/extensions/assets/48929039/12442435-eef8-4022-85a5-85d70e440bfc

**Comment by tleo19** [comment]
> Hi there! 
> 
> @tleo19 So this notion page for example is pinned as a favourite on arc but i have a quick link to open the same page and it opens in a new page, im wondering if i can navigate to the favourited tabs like how it shows up in the "search tabs" easier through a command or a hotkey. Let me know if this makes more sense, thank you! 
> 
> 
> 
> 
> 
> https://github.com/raycast/extensions/assets/48929039/12442435-eef8-4022-85a5-85d70e440bfc
> 
> 
> 
> 

Hey, 

Thanks for clarifying and sending over a screen recording. I know understand. 

So 2 things: 

First, I am not sure this is currently achievable with quick link. 

Second, maybe as a work around you could use the search tabs command from the arc extension. 
The favorites are displayed at the top of the list and when you click to open it will open directly in that favorite tab.

**Comment by madebymalavika** [comment]
@tleo19 
Hi there! thanks for this; I added that to the end of the screen recording -- i was wondering if there's a way to get to that quicker like through a hot key or an alias but i guess that isn't possible. 

Thanks for your help though.

**Comment by tleo19** [comment]
> @tleo19 Hi there! thanks for this; I added that to the end of the screen recording -- i was wondering if there's a way to get to that quicker like through a hot key or an alias but i guess that isn't possible.
> 
> Thanks for your help though.

with pleasure sorry this is not really the solution you were hoping.
oh yes I see it now on your recording my bad, well the only way would be to have the search tabs command on a hotkey maybe. I am also not sure this an Arc extension limitation since the link is triggered from a quicklink using the actual Arc app .
