### ISSUE TITLE
Ability to clear the search list

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#9663]
### Extension

https://www.raycast.com/dch09/ableton-live

### Description

Would be nice to have an option to clear the search list to get rid of showing unwanted projects

**Comment by dch09** [comment]
Do you have any example of some other extension which has that very feature? Could be helpful.

**Comment by romanskorobagatko** [comment]
Not sure if it's the similar function but here it is - https://www.dropbox.com/t/EqyS4sS3ElTNEoH4

Example extension link - https://www.raycast.com/HelloImSteven/jump

**Comment by dch09** [comment]
So basically this would temporarily remove result from the list? Or do you need some kind of blacklist so that some projects would not appear in results?

**Comment by romanskorobagatko** [comment]
"temporarily remove result from the list" sounds good.

**Comment by dch09** [comment]
> "temporarily remove result from the list" sounds good.

I was planning on releasing an update with blacklisted folders to omit during search, but temporarily removing results was never something I needed. If you need it tho, feel free to contribute.

**Comment by romanskorobagatko** [comment]
Unfortunately I’m not a programmer, I’m musician and have no idea how to do it. Anyway thanks a lot for you work!
