### ISSUE TITLE
[Unicode Symbols Search] ...

### ISSUE THREAD

**Issue by Yukaii** [raycast/extensions#9664]
### Extension

https://www.raycast.com/mmazzarolo/unicode-symbols

#### Error:

~~~
TypeError: Cannot read properties of undefined (reading 'length')

ItemGrid.tsx:29:30

---
26:   `;
27: };
28: 
29: const GridItem = memo(({ item }: { item: Character }) => {
30:   const [light, dark] = useMemo(() => {
31:     return [
32:       `data:image/svg+xml;base64,${encode(getSquare(item.value))}`,
---

    at ray-grid-section
ja:index.js:20:24805
Mr:index.js:11:6635
~~~

### Steps To Reproduce

Running the default command would cause the issue

**Comment by Yukaii** [comment]
After I clear the cache manually, the problem is resolved.

It might be caused by the recent change. https://github.com/raycast/extensions/pull/9506

**Comment by j3lte** [comment]
@Yukaii you might be right, I'm thinking that this was introduced by my PR with this piece of code:

```typescript
        item.aliases.length > 0 ? `Aliases: "${item.aliases.map(upperCaseFirst).join(", ")}"` : "",
```

... which might break on a cached item that doesn't have aliases. In other parts of the code it does a better check for aliases, didn't catch this one in my code. 

I'll write a small fix for it.
