### ISSUE TITLE
[Zed] Open a folder with Zed when I'm inside it

### ISSUE THREAD

**Issue by Angelk90** [raycast/extensions#9673]
### Extension

https://www.raycast.com/ewgenius/zed-recent-projects

### Description

Hi @ewgenius, I recently tried the extension you created, the problem is that when I am inside the folder and it is not selected I would like it to open like the vs code(visual-studio-code-recent-projects) extension does.

I looked at the code, I found this, I don't know if it can be useful to you.

https://github.com/raycast/extensions/blob/5352eaabcffcbc6f32576f4d0b2e8fa705b583c0/extensions/visual-studio-code-recent-projects/src/open-with-vscode.ts#L1-L52

**Comment by ewgenius** [comment]
Hello @Angelk90, thanks for the feedback, I'll take a look
