### ISSUE TITLE
[Height] Open Height desktop app directly from raycast

### ISSUE THREAD

**Issue by calight23** [raycast/extensions#9674]
### Extension

https://www.raycast.com/teziovsky/height

### Description

Provide the ability to open height desktop app when working within the extension. 
![CleanShot 2023-12-13 at 09 53 19@2x](https://github.com/raycast/extensions/assets/85297406/67c7df1b-3b42-4f8b-891c-6e85be35827a)

### Who will benefit from this feature?

All height desktop app users!

**Comment by teziovsky** [comment]
Hey!

It’s awesome to hear that people are enjoying the extension! 🚀

I’ll explore whether the height app accepts URLs for quick opening. I’ll go ahead and work on this. If I hit any roadblocks, I’ll tell you.

Cheers!
