### ISSUE TITLE
[Mailsy] not work anymore

### ISSUE THREAD

**Issue by zalewskigrzegorz** [raycast/extensions#9675]
### Extension

https://www.raycast.com/BalliAsghar/mailsy

### Description

Not working anymore
![2023-12-13_18-32-42 (1)](https://github.com/raycast/extensions/assets/12560152/47a4ab23-818f-47b5-bd94-a34d5b060722)

### Steps To Reproduce

Open any mailsy command

### Current Behaviour

Command doesn't work

### Expected Behaviour

Command should work

**Comment by BalliAsghar** [comment]
#9731 This Pr should fix all issues.

**Comment by BalliAsghar** [comment]
@raycastbot close this issue
