### ISSUE TITLE
[Snippet] Unable to create snippet (blank page)

### ISSUE THREAD

**Issue by BDRfox** [raycast/extensions#9683]
### Extension

[snippets](https://www.raycast.com/extensions/snippets)

### Description

Blank page when trying to create snippets

### Steps To Reproduce

1. launch Raycast with command+space
2. type snippet
3. select "create snippet"
4. blank page

### Current Behaviour

Blank page and unable to create snippet

https://github.com/raycast/extensions/assets/49968679/f9da906e-a8ef-4aa2-9770-61f947eeee31

### Expected Behaviour

Create snippet page that allows name, text, and hotkey input

**Comment by crazytaxi824** [comment]
same here

**Comment by crazytaxi824** [comment]
macOS Sonoma 14.2.1
Raycast v1.64.4
fix the problem

**Comment by BDRfox** [comment]
> macOS Sonoma 14.2.1 Raycast v1.64.4 fix the problem

I have the same exact versions for both OS and Raycast

**Comment by BDRfox** [comment]
bump

**Comment by BDRfox** [comment]
Issue has not been resolved

**Comment by BDRfox** [comment]
Opened new issue: https://github.com/raycast/extensions/issues/10543
