### ISSUE TITLE
[Visual Studio Code] Commands - No response from Raycast for VSCode extension

### ISSUE THREAD

**Issue by kaizenretro** [raycast/extensions#9687]
### Extension

https://www.raycast.com/thomas/visual-studio-code

### Description

I want to use the Commands command, but when I do, I get an error that says "No response from Raycast for VSCode extension."
<img width="755" alt="Screenshot 2023-12-13 at 10 07 13 PM" src="https://github.com/raycast/extensions/assets/145168238/a63ce18b-396a-4d88-9c24-e8ec590652e6">

### Steps To Reproduce

I'm using an M1 Mac running Ventura 13.2. (22D49)

Install Raycast extension
Enable Commands command
Run Commands command

### Current Behaviour

Raycast error message: "No response from Raycast for VSCode extension."

### Expected Behaviour

Gives options from VSCode Command Palette

**Comment by tonka3000** [comment]
@kaizenretro Did you installed the Rayast extension in VSCode? It is required to be able to use the command.

**Comment by tmwrnr** [comment]
Hi @kaizenretro,

did you install the required VSCode [extension](https://marketplace.visualstudio.com/items?itemName=tonka3000.raycast)?
