### ISSUE TITLE
[WordPress Plugins] Add "Copy composer package name" action

### ISSUE THREAD

**Issue by davidmondok** [raycast/extensions#9688]
### Extension

https://www.raycast.com/edmundcwm/wordpress-plugins

### Description

It would great to have an additional action (and maybe even be able to replace/configure a different action besides "Visit Plugin Page" to be the default action) called "Copy composer package name". It's very easy to generate those, because it's always `wpackagist-plugin/` with the plugin name after the slash. The name can be easily extracted from the plugin URL `https://wordpress.org/plugins/{plugin-name}/`.

So for https://wordpress.org/plugins/hello-dolly/ it would be `wpackagist-plugin/hello-dolly`.

Thanks

### Who will benefit from this feature?

WordPress developers using composer to install WP plugins

**Comment by edmundcwm** [comment]
Thanks @davidmondok for the suggestion! I should be able to have a look at this by this week 👀

**Comment by davidmondok** [comment]
Awesome, thanks a lot @edmundcwm, and great job, it's a very helpful and well executed extension!
