### ISSUE TITLE
Unable to login to my lock vault.

### ISSUE THREAD

**Issue by bharathkalyans** [raycast/extensions#969]
# Extension – [Bitwarden Vault](https://github.com/raycast/extensions/tree/71dc0903b48af29aa0595ad456899ba7679312e0/extensions/bitwarden/)
Author: @pomdtr

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.28.0

**Comment by mathieudutour** [comment]
Could you fill up the issue template?
