### ISSUE TITLE
[Change Case] ... Punctuation Removal and Text Merging in Sentence Case Conversion

### ISSUE THREAD

**Issue by jahoseph** [raycast/extensions#9691]
### Extension

https://www.raycast.com/erics118/change-case

### Description

When using the Change Case extension to convert text to 'Sentence case,' I've encountered a significant issue where all punctuation in the original text is removed. This includes commas, colons, periods, ampersands, exclamation points, and dashes. Additionally, this leads to all the text merging into a single, continuous sentence, thereby altering the intended structure and meaning of the text.

**Example:**
Converting the text "The Quick, Brown Cat & Slow Dog Are Friends. They live happily." using the 'Sentence case' option results in "The quick brown cat slow dog are friends they live happily," where all punctuation is missing and the text becomes one long sentence.

This issue persists even when the latest version of the extension and Raycast is used.

### Steps To Reproduce

1. Select text with punctuation and multiple sentences (e.g., "The Quick, Brown Cat & Slow Dog Are Friends. They live happily.").
2. Run the Change Case command in Raycast.
3. Choose the 'Sentence case' option.
4. Observe that the output text lacks all punctuation and merges into a single sentence.

### Current Behaviour

The current output when converting to 'Sentence case' removes all punctuation from the original text and merges multiple sentences into one continuous sentence.

### Expected Behaviour

The expected behavior is for the text to change case to 'Sentence case' while retaining all original punctuation and sentence structure. The ideal output for the above example should be "The quick, brown cat & slow dog are friends. They live happily."

**Comment by erics118** [comment]
The package that I use for changing case doesn't support this. I suggest reporting this issue to https://github.com/blakeembrey/change-case

**Comment by jahoseph** [comment]
> The package that I use for changing case doesn't support this. I suggest reporting this issue to https://github.com/blakeembrey/change-case

I reported this to the package author, and I think they've just issued a fix: https://github.com/blakeembrey/change-case/issues/324#issuecomment-1881808427.

**Comment by erics118** [comment]
I've updated the package version, so the the issue should now be fixed. 

Here is the difference:

Using the text: 
`this is a sentence. this is a sentence. this is a sentence.`
Before: 
`This is a sentence this is a sentence this is a sentence`
Now: 
`This is a sentence. This is a sentence. This is a sentence.`
