### ISSUE TITLE
[Obsidian Bookmarks] Support Arc (Chromium Browsers)

### ISSUE THREAD

**Issue by jshmllr** [raycast/extensions#9693]
### Extension

https://www.raycast.com/dru89/obsidian-bookmarks

### Description

Bookmarks never retrieves the bookmark from a browser such as Arc.

### Who will benefit from this feature?

Anyone using a non-Chrome browser, but is still chromium.

### Anything else?

![Screenshot 2023-12-14 at 8 23 40 AM](https://github.com/raycast/extensions/assets/4146776/2b124fe0-bd75-460e-a082-ccaba183851c)

**Comment by lukasklein** [comment]
Hey @jshmllr, I've just added a PR for this: https://github.com/raycast/extensions/pull/9774
