### ISSUE TITLE
[Reclaim] Option to hide "No upcoming events" text

### ISSUE THREAD

**Issue by ojsef39** [raycast/extensions#9696]
### Extension

https://www.raycast.com/reclaim-ai/reclaim-ai

### Description

It would be great to have the option to have only show the Reclaim logo when there are no upcoming events :)

So the option to hide the "No upcoming events" text.

### Who will benefit from this feature?

- Users with small screens
- Users who have the menu item always shown (e.g. Bartender users)

**Comment by gunrein** [comment]
Thanks for the suggestion @ojsef39 ! I added this to our feature request tracking system as RAI-11586.

**Comment by ojsef39** [comment]
> It will be closed if no further activity occurs in the next 10 days to keep our backlog clean 😊

Is this a problem? Ig its not since there is an internal ticket but i wanted to make sure :)

**Comment by gunrein** [comment]
> Is this a problem?

Nope, we still have the request open internally.
