### ISSUE TITLE
[Life Progress] Crash when opening app

### ISSUE THREAD

**Issue by sebdanielsson** [raycast/extensions#9698]
### Extension

https://www.raycast.com/koinzhang/life-progress

#### Error:
```
X: request to https://apiv3.shanbay.com/weapps/dailyquote/quote/?date=2023-12-14 failed, reason: 

ClientRequest.<anonymous>:life-progress.js:12:30152
ClientRequest.emit:node:events:514:28
ClientRequest.emit:node:domain:488:12
TLSSocket.socketErrorListener:node:_http_client:495:9
```

### Steps To Reproduce

1. Install the app.
2. Perform the initial configuration by entering your birthday and selecting the first day of the week.
3. Launch the app, but it crashes.

**Comment by sebdanielsson** [comment]
Is this extension abandoned?

**Comment by koinzhang** [comment]
@sebdanielsson It looks like the network request encountered an error, I'll add a tout strategy

**Comment by koinzhang** [comment]
@sebdanielsson A PR #10552 has been submitted to fix the network request issue,  if you're still experiencing network request errors, feel free to keep the feedback coming.

**Comment by sebdanielsson** [comment]
Sorry for the slow reply. I've just tested the update and it's working great. Thank you for this great extension!😃
