### ISSUE TITLE
[Dash] Cannot create docset quicklink

### ISSUE THREAD

**Issue by mgingras** [raycast/extensions#9700]
### Extension

https://www.raycast.com/RSO/dash

#### Error:
```
Error: No enabled command 'create-quicklink' found


```

### Steps To Reproduce

1. Try to add quicklink with Dash with keyword `py`

### Current Behaviour

Errors
<img width="742" alt="image" src="https://github.com/raycast/extensions/assets/1209506/a0ecf9b8-53b9-48b6-9758-6f089947b554">

**Comment by RSO** [comment]
Can you try this again after making sure you're on the latest version of Raycast? There was a bug in yesterdays version that broke the `Create Quicklink` command for some users!

**Comment by JasonBoy** [comment]
also works for me on the latest version of Raycast

**Comment by fishiu** [comment]
Have the same problem. By the way, what does `keyword` mean? It is the word I can customize or the doc name determined by dash

**Comment by fishiu** [comment]
Found a (slower) way to achieve this, but at least it does:

Add quick link: raycast://extensions/RSO/dash/docset?arguments=%7B%22docset%22%3A%22<keyword>%22%7D

replace <keyword> by the keyword you set in Dash, for example I use py3 for python3 in dash

**Comment by JasonBoy** [comment]
the keyword is here:
![CleanShot 2023-12-16 at 23 52 01@2x](https://github.com/raycast/extensions/assets/2911620/6b740979-df58-4151-acb5-2e702f644870)

**Comment by RSO** [comment]
@fishiu what version of Raycast are you on? You can find the version in the preferences about panel.

**Comment by fishiu** [comment]
> @fishiu what version of Raycast are you on? You can find the version in the preferences about panel.

I just found that I can create quicklink successfully now.. Have no idea what was happening. Thank you anyway for this wonderful extension and your effort for maintaining it.
