### ISSUE TITLE
[Spotify Player] Ability to see the Queue

### ISSUE THREAD

**Issue by medio4** [raycast/extensions#9704]
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

The ability to see the queue and skip to a song or rearrange it from Raycast would be pretty cool.

**Comment by bkeys818** [comment]
The Spotify API doesn't currently have a way to view or modify the queue.
@raycastbot close this issue

**Comment by bkeys818** [comment]
Hey @thomaslombart, is this an appropriate use case for closing an issue?

**Comment by erics118** [comment]
API does provide queue information: https://developer.spotify.com/documentation/web-api/reference/get-queue

**Comment by bkeys818** [comment]
Oh shoot! Don't know how I missed that. Good catch!

@raycastbot reopen this issue
