### ISSUE TITLE
[Browser Bookmarks]  Something went wrong

### ISSUE THREAD

**Issue by LongyunZhang** [raycast/extensions#9705]
### Extension

http://www.raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

when i search bookmarks, it shows "Something went wrong"

**Comment by QuantumRoseinAmethystVase** [comment]
Same as https://github.com/raycast/extensions/pull/9338. However, I am using the Arc browser, so it is certain to encounter the "Something went wrong" error. It seems that the problem has not been resolved.
