### ISSUE TITLE
[Todoist] Please add duration to the quick create command

### ISSUE THREAD

**Issue by hoegertn** [raycast/extensions#9712]
### Extension

https://www.raycast.com/doist/todoist

### Description

It would be great to be able to set the task duration using the "Create Task" action

**Comment by thomaslombart** [comment]
It's already possible, so I'll close this issue.

![CleanShot 2023-12-18 at 12 59 52@2x](https://github.com/raycast/extensions/assets/16003285/8c8129d3-9046-4e25-bc84-abf5897adbc8)

**Comment by hoegertn** [comment]
Ok, I will check this. I do not get this field in my Raycast...

**Comment by thomaslombart** [comment]
To avoid cluttering the UI, the field is shown only if you have set a date **and** time as it's required to set a duration 🙂

**Comment by hoegertn** [comment]
Ah ok, that does not solve my need. I am not adding times to my tasks.

**Comment by thomaslombart** [comment]
It is a requirement on Todoist. You can reach out to them then 🙂
