### ISSUE TITLE
[Google Translate] ... Proxy settings needed

### ISSUE THREAD

**Issue by Arichy** [raycast/extensions#9715]
### Extension

https://www.raycast.com/gebeto/translate

### Description

In some countries, people can have access to google only via VPN. Now I can get access to google translate in browser, but cannot get response via google translate extension in raycast.
So please support proxy settings in such extensions.
Thanks.

### Who will benefit from this feature?

Users in countries in where google is banned.

**Comment by gebeto** [comment]
I think if you will go to the Settings -> Advanced, scroll down and enable `Use System Network Preferences`, it will use system network proxy

<img width="1112" alt="Screenshot 2024-02-05 at 13 39 35" src="https://github.com/raycast/extensions/assets/13422799/fffaa011-6d74-4e21-aa44-15d11b771374">

**Comment by Arichy** [comment]
> I think if you will go to the Settings -> Advanced, scroll down and enable `Use System Network Preferences`, it will use system network proxy
> 
> <img alt="Screenshot 2024-02-05 at 13 39 35" width="1112" src="https://private-user-images.githubusercontent.com/13422799/302276019-fffaa011-6d74-4e21-aa44-15d11b771374.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODExNjUsIm5iZiI6MTcwNzQ4MDg2NSwicGF0aCI6Ii8xMzQyMjc5OS8zMDIyNzYwMTktZmZmYWEwMTEtNmQ3NC00ZTIxLWFhNDQtMTVkMTFiNzcxMzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDEyMTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NmEwM2VjNGI5YTQzMTZjNTk3NWMxZTZlOGYxYmZkYTIzOTUxZjU4NjBjOTZkZWMwYjNmYjgwYzEyMmFiMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AnKlfYAhJxyouAbH2L5EpGBwvNeg1w6Aei4f1r0UCcQ">

I enabled it, but it did not work. I can open google translate in browser, but cannot translate in the extension.

**Comment by CrazyCatZhang** [comment]
> > I think if you will go to the Settings -> Advanced, scroll down and enable `Use System Network Preferences`, it will use system network proxy
> > <img alt="Screenshot 2024-02-05 at 13 39 35" width="1112" src="https://private-user-images.githubusercontent.com/13422799/302276019-fffaa011-6d74-4e21-aa44-15d11b771374.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODExNjUsIm5iZiI6MTcwNzQ4MDg2NSwicGF0aCI6Ii8xMzQyMjc5OS8zMDIyNzYwMTktZmZmYWEwMTEtNmQ3NC00ZTIxLWFhNDQtMTVkMTFiNzcxMzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDEyMTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NmEwM2VjNGI5YTQzMTZjNTk3NWMxZTZlOGYxYmZkYTIzOTUxZjU4NjBjOTZkZWMwYjNmYjgwYzEyMmFiMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AnKlfYAhJxyouAbH2L5EpGBwvNeg1w6Aei4f1r0UCcQ">
> 
> I enabled it, but it did not work. I can open google translate in browser, but cannot translate in the extension.

i encountered same issue，Google translate is doesn't work

**Comment by cui1204** [comment]
i encountered same issue，Google translate is doesn't work
