### ISSUE TITLE
[Pins] Unable to Use Hotkeys set for Pins

### ISSUE THREAD

**Issue by ambitendencies** [raycast/extensions#9717]
### Extension

https://www.raycast.com/HelloImSteven/pins

### Description

I can't seem to trigger any of my pins via hotkeys that I have set for them.

### Steps To Reproduce

1. Create a new pin
2. Assign keyboard shortcut modifiers (Command, Ctrl, Shift)
3. Assign Keyboard Shortcut 9

I've tried assigning various different keyboard shortcuts on step 3, and changed modifiers on step 2.

### Current Behaviour

When pressing hotkey, nothing happens.

### Expected Behaviour

Expect my pin to trigger the url-scheme specified like it does when I manually click to activate it.

**Comment by SKaplanOfficial** [comment]
Hi, sorry for the delay -- I'm not able to recreate this issue on my machine. Command+9 works once the menu bar dropdown is open. The extension doesn't listen for external keystrokes as Raycast doesn't provide an easy way to do that.
