### ISSUE TITLE
Broken state

### ISSUE THREAD

**Issue by rightsaidfred99** [raycast/extensions#9720]
### Extension

https://www.raycast.com/0x46616c6b/mullvad

### Description

Error: mullvadvpn: No such file or directory @ rb_file_s_rename - (/opt/homebrew/Caskroom/mullvadvpn/2023.5, /opt/homebrew/Caskroom/mullvadvpn/2023.5.upgrading)

### Steps To Reproduce

It's simply not working

### Current Behaviour

See description for error log. No matter what happens, it's borked

**Comment by 0x46616c6b** [comment]
What did you expect? It seems you tried to open the Mullvad App. This extension is not responsible for that. The extension only checks your connection status. 

The error message you provided tells me that the Mullvad App (not this extension) is not in the expected place. So, I would assume you should reinstall the Mullvad VPN Client.

**Comment by rightsaidfred99** [comment]
> What did you expect? It seems you tried to open the Mullvad App. This extension is not responsible for that. The extension only checks your connection status.
> 
> The error message you provided tells me that the Mullvad App (not this extension) is not in the expected place. So, I would assume you should reinstall the Mullvad VPN Client.

Haha, calm your horses - app wasn't being opened. I know what I'm doing.

The reinstall didn't work, the install didn't work, nor did brew cleanup. It got stuck in this state - perhaps it's a brew problem not raycast? I don't know but it's been reported and that was the error message
