### ISSUE TITLE
[ChatGPT] Unable to use Custom APl endpoint

### ISSUE THREAD

**Issue by bo233** [raycast/extensions#9723]
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

Unable to use Custom APl endpoint. Always show that `Error Request failed with status code 404`. I set it as `https://xxxx.org/`, and I'm sure that the url is correct

### Steps To Reproduce

1. set my custom api endpoint and set my own key
2. use 'Ask Questions', enter something and entry
3. display 404 error

**Comment by fivehanz** [comment]
I am having same issue using together ai's openai compatible endpoint.

**Comment by bo233** [comment]
i have solved the problem. we should add ‘/v1’ at the end of the url.
