### ISSUE TITLE
[Apple Reminders] almost a natural language prompts

### ISSUE THREAD

**Issue by bigplayer-ai** [raycast/extensions#9730]
### Extension

http://www.raycast.com/raycast/apple-reminders

### Description

Can you add support for "LIKELY" natural language prompts to the Apple Reminders extension on Raycast? For example, I used to use a similar feature in the Alfred Workflow: https://github.com/surrealroad/alfred-reminders. It would be great if I could use something like "r buy apples in three days 3 pm" to create a reminder.

### Who will benefit from this feature?

Everyone who uses apple reminders

### Anything else?

Yes Alfred had this work flow: https://github.com/surrealroad/alfred-reminders

**Comment by bigplayer-ai** [comment]
Hey Raycastbot is broken, it keeps not finding the extensions!!

**Comment by mwmcode** [comment]
Checkout this script 
https://github.com/raycast/script-commands/tree/master/commands#reminders

Note that it has a dependency 
https://www.icloud.com/shortcuts/62a0cedf7bce488eb0bde4b8a3a8b0de

1. install dependency 
2. add script to raycast
3. make `r` as alias for the script... and you get "similar" functionalities to Alfred's extension 

_It's not as powerful as Alfred's one. It only supports what/when -- no adding to specific lists for example._

![re](https://github.com/raycast/extensions/assets/13101565/9f6ebaad-a41f-4716-b44d-62758d0cc1a6)
