### ISSUE TITLE
[Flow Timer] - Using "Show timer" quits Raycast

### ISSUE THREAD

**Issue by sekeidesign** [raycast/extensions#974]
# Extension – [Flow Timer](https://github.com/raycast/extensions/tree/bfe4cbbdf985254855b1ab36228187e9ce719a89/extensions/flow/)
Author: @vimtor

## Description
Using this extension to show the Flow timer quits Raycast silently

## Steps To Reproduce

1. Use the "Show timer" command

## The current behavior
Raycast is closed as soon as the command is run

## The expected behavior
Raycast stays open after the "show timer" command is run

### Raycast version
Version: 1.29.0

**Comment by fe9lix** [comment]
This is a bug in Raycast 1.29.0 that will be fixed soon with 1.29.1
