### ISSUE TITLE
[Google Bard] Add Gemini Pro?

### ISSUE THREAD

**Issue by GaryKu0** [raycast/extensions#9743]
### Extension

https://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

We can now use the Google Gemini pro API for free, so it would be great to add support for it.

### Who will benefit from this feature?

everyone don't wanna pay to use AI!

**Comment by yzlnew** [comment]
+1

**Comment by xsbchen** [comment]
#9797

**Comment by yzlnew** [comment]
> #9797 i created a PR for this

Thanks, but this PR is closed?

**Comment by xsbchen** [comment]
> > #9797 i created a PR for this
> 
> Thanks, but this PR is closed?

i make a mistakes, try the new one: #9798
