### ISSUE TITLE
Resizing issue [Image Modification] ...

### ISSUE THREAD

**Issue by christmads** [raycast/extensions#9748]
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

Hi. I am getting extreme image compression when resizing images. Is there a way to avoid this? I work a lot with websites where things has to be optimized for mobile and this tool would be SO HELPFUL if it did not do this (or if I could select the compression myself)
![P2241568](https://github.com/raycast/extensions/assets/154071568/5977ee21-7fc8-463a-99a3-888284dca9da)
![Resized](https://github.com/raycast/extensions/assets/154071568/70fdf828-4eb2-4179-a2fd-a89a4e2658b7)

It could be cool to resize by % as well

### Steps To Reproduce

Just try to resize anything

**Comment by SKaplanOfficial** [comment]
Hmm, there might not be a simple fix, but I can look into it. Are you using the `resize` or the `scale` command? Also, is the original image format JPG or something else? (If it's webp, for example, I have more control over the processing.)

For the `resize` command with JPG, the extension uses the native `sips` command to resample the width and height, i.e. it runs the Terminal command `sips -z 800 460 [image path]` in this case. If you run that in the Terminal, do you get the same compression?

**Comment by christmads** [comment]
I haven't used githup before so I am in doubt if the mail forwards my reply, because I can not see it here. I will add it here also. Sorry if you get double notifications.

Hi Stephen.

Thank you for the fast reply!

For this one i am using the resize. If i use scale i can only upscale. I tried putting a - in the factor but it doesn't seem to work unfortunatly. Can it do negative scale?

This one was a JPG. I tried it with PNG also and it does the same. Just tried converting to WEBP and it also compresses it like crazy.

I just tried the sips command and it looks like the issue is within the termial.

Do you have an idea if it is possible to do something with? I would be more than happy to send you a little tip if you do, this would be AMAZING to be able to do with shortcuts!
