### ISSUE TITLE
[Toggle Audio Input (microphone)] ...

### ISSUE THREAD

**Issue by mrnoisytiger** [raycast/extensions#9750]
### Extension

https://www.raycast.com/Quentin23Soleil/mute-microphone

### Description

Unfortunately, this appears to have no effect on MacOS Sonoma 14.1.1. I tried toggling the mute and I am still able to get recordings in Voice Memos even though expected behavior should be that it mutes the input complete.y

### Steps To Reproduce

1. MacOS Sonoma 14.1.1
2. M3 Max Macbook Pro 16"
3. Raycast 1.64.3

No specific steps to reproduce, it just doesn't do anything. I get the popup saying "muted" and "unmuted" as well as the menu bar icon - however, just not the actual function.

**Comment by iamyeizi** [comment]
@raycastbot close this issue

**Comment by alizehctl** [comment]
I just experienced this issue. Running the extension commands didn't do anything
