### ISSUE TITLE
Dash - Terraform Provider does not show up in the extension

### ISSUE THREAD

**Issue by BrendanThompson** [raycast/extensions#976]
# [Dash](https://github.com/raycast/extensions/tree/main/extensions/dash)

Author: @RSO 

## Description

The **Providers** do not show up when using the Dash search extension, it only seems to show **Resources** and **Data Sources**.

## Steps To Reproduce

1. Download the **Terraform** docset
2. Search using Raycast for `Azure Provider`
![CleanShot 2022-02-24 at 16 14 24](https://user-images.githubusercontent.com/2595712/155462367-d3d34ac0-f7f2-4043-ad65-3f936aeafd94.png)

Doing this same query for `Azure Provider` within Dash itself yields the below result:
![CleanShot 2022-02-24 at 16 14 44](https://user-images.githubusercontent.com/2595712/155462533-c2af4538-c096-4f8a-a690-57231944cc77.png)

## The current behavior

The **Provider** will not show up in Raycast

## The expected behavior

The **Provider** should show up in Raycast

### Raycast version

Version: v1.29.0

**Comment by RSO** [comment]
Thanks for the report! I replicated the error and noticed that everything after the space got ignored in Dash, this lead me to realize that we didn't quote the query string when we passed it to the Dash shell script. This got fixed in ba34101!
