### ISSUE TITLE
Can I use snippet trigger keyword CJK language?

### ISSUE THREAD

**Issue by jnote1** [raycast/extensions#977]
Hi I'm newbie so I trying many feature in raycast

I have a question that using snippet

When I create snippet trigger keyword that using korean word + symbols(like 별;;), It dosen't run

![스크린샷 2022-02-24 오후 4 48 34](https://user-images.githubusercontent.com/66677658/155483397-8858621b-e1d9-4c17-8d15-cd8b4fb4b2c3.png)

But I create snippet trigger keyword using english word(like star@@), It does pretty well

![스크린샷 2022-02-24 오후 4 47 46](https://user-images.githubusercontent.com/66677658/155483418-4b388aa2-66bb-4b23-b9bc-2aa8581367f7.png)

**Comment by mathieudutour** [comment]
Hey that doesn't seem to be related to an extension (snippets are a core feature of Raycast). Could you send the question using the "Send Feedback" command in Raycast directly? Thanks
