### ISSUE TITLE
[File Manager] support finder aliases

### ISSUE THREAD

**Issue by paulmarique** [raycast/extensions#9775]
### Extension

https://www.raycast.com/erics118/file-manager

### Description

At the moment the finder Aliases are shown as files in the extension.
But it would be more usefull and consistent with osx environement to be treated as aliases.

### Who will benefit from this feature?

Every person that use aliases to access their files quicker with the keyboard.

### Anything else?

Thanks a lot for your amazing work :)

**Comment by erics118** [comment]
There are two main types of aliases in macOS:
- the one created in Finder using right click -> Make Alias, which creates a file that acts as an alias to a folder or file. This is not implemented, but probably can be implemented using something like [node-alias](https://www.npmjs.com/package/macos-alias). 
- THe one created using `ln -s`, which creates a symbolic link. This should me mostly implemented correctly. 

Feel free to PR any fixes.

**Comment by erics118** [comment]
@raycastbot rename this issue to "[File Manager] support finder aliases"
