### ISSUE TITLE
Bitwarden search vault not working on Raycast

### ISSUE THREAD

**Issue by thakursaurabh1998** [raycast/extensions#9781]
### Extension

http://www.raycast.com/jomifepe/bitwarden

#### Error:
```
Error: Command failed with exit code 1: /usr/local/bin/bw lock
node:internal/modules/cjs/loader:1327
  return process.dlopen(module, path.toNamespacedPath(filename))

### Steps To Reproduce

1. Using raycast to search vault. Was logged in.
2. Raycast asks for master password but as soon as I start typing the password screen vanishes and lands me to the below screenshot.
<img width="757" alt="image" src="https://github.com/raycast/extensions/assets/18613564/9291d692-0161-495a-97af-20909544a2d8">


### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by jomifepe** [comment]
Hey, thanks for reporting. It's a bit hard to tell by the description and screenshot, do you have a more complete error message? Or was that the whole error?

**Comment by thakursaurabh1998** [comment]
Yes, this is the whole error. I am also confused why the error terminates without proper information.

**Comment by jomifepe** [comment]
Can you confirm that your node architecture matches your machine? `node -p "process.arch"`

I've been seeing a lot of these errors, which happen most likely after a migration from an Intel/x64 Mac to an Apple Silicon one, all the software is transferred in the x64 targeted version and some need to be reinstalled, one of them being NodeJS.

<img width="921" alt="Screenshot 2023-12-25 at 22 56 59" src="https://github.com/raycast/extensions/assets/7235666/4d2b28ea-d490-4b6f-aa70-a1a75a06b6e7">
