### ISSUE TITLE
[Google Chrome] Failing to Open Chrome

### ISSUE THREAD

**Issue by bvallelunga** [raycast/extensions#9787]
### Extension

http://www.raycast.com/Codely/google-chrome

### Description

When hitting [enter] key on a url from the browser history, it fails to open the link in Chrome.

### Steps To Reproduce

1. Search History
2. Hit "enter" key
3. Nothing happens

### Current Behaviour

Nothing happens

### Expected Behaviour

Open Chrome browser with link

**Comment by tleo19** [comment]
Does this happen when you do not have a google chrome window open?
If you have one open and you try enter on a history url does it work?
