### ISSUE TITLE
[Ollama AI] ...

### ISSUE THREAD

**Issue by joshmu** [raycast/extensions#9791]
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

When a markdown code block is used in a response it would be great to assign default syntax highlighting if no language type is specified.

Currently there will be no syntax highlighting support if the LLM responds with a code example without providing the language type in the markdown code block.  This has been noticed in __llama2__ and __codellama__.

<img width="770" alt="image" src="https://github.com/raycast/extensions/assets/1970265/357ed1c7-7e57-4cb7-a93d-dcd648ab1ca3">

### Who will benefit from this feature?

All users who refer to code examples when the LLM does not sufficiently provide the language type against the markdown code block.

**Comment by MassimilianoPasquini97** [comment]
Hi @joshmu, 
The LLM response is treated by Raycast as markdown so the LLM need to reference the highlight format on the code block and even phi2 2.7B model can do that. Where an example. This issue can be closed.

## Screenshot

![raycast-ollama 2023-12-20 at 07 14 23](https://github.com/raycast/extensions/assets/62497822/a02ee8de-b6a3-4379-a863-0accb332ce01)

## Response copied to the clipboartd

 Here is an example of a golang array sort code using the built-in "sort" package:
```go
package main
import (
	"fmt"
)
func main() {
	// Define an unsorted slice
	unsorted := []int{3, 1, 4, 2}

	// Sort the slice in ascending order
	sort.Slice(unsorted, func(i int, j int) bool {
		return unsorted[j] < unsorted[i]
	})

	// Print the sorted slice
	fmt.Println("Sorted array:", unsorted)
}
```
Output:
```
Sorted array: [1 2 3 4]
``` 
This code creates an unsorted slice of integers, sorts it in ascending order using the "sort" package, and then prints the sorted slice. The "sort.Slice()" function takes two arguments - the slice to be sorted and a sorting function that returns true if the first element is less than the second element.

**Comment by joshmu** [comment]
Hey @MassimilianoPasquini97 
It depends on the LLM. 

I had success with dolphin-mixtral

However both llama2 and codellama only provided generic markdown code blocks in the response and this is where I noticed the lack of syntax highlighting. 

Perhaps this if more a raycast request if you are using their unbuilt markdown preview?
