### ISSUE TITLE
search assets action via shortcut

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#9792]
### Extension

https://www.raycast.com/colbyfayock/cloudinary

### Description

Search Assets action shows nothing when triggered via shortcut
 
Here is a video of an issue - https://capture.dropbox.com/9nYrvXtOtQNCm4ZT

### Steps To Reproduce

1. Open Raycast
2. Search for "Search Assets" command
3. Hit enter

OR

Press assigned shortcut (option + A in my case)

### Current Behaviour

In case of triggering a command with a shortcut it doesn't show any assets.

### Expected Behaviour

The same as triggering a command like this:

1. Open Raycast
2. Search for "Search Assets" command
3. Hit enter

**Comment by colbyfayock** [comment]
hey @romanskorobagatko i opened up a ticket on the actual repository. i plan on getting to this, i just haven't yet: https://github.com/colbyfayock/raycast-cloudinary/issues/9
