### ISSUE TITLE
[Image Modification] svg files are not recognized as selected

### ISSUE THREAD

**Issue by martvaha** [raycast/extensions#9795]
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

Unable to convert SVG images from one format to another.
<details><summary>Image of the error</summary>

<img width="865" alt="No image selected" src="https://github.com/raycast/extensions/assets/8341598/915961a6-5035-45f2-8158-391d2b6a5350">
</details> 

### Steps To Reproduce

1. Select any svg image
2. Try to convert to any format
3. Gives "No images selected" error

**Comment by JUSTIVE** [comment]
Why has this issue been closed? I'm having the same issue.

**Comment by SKaplanOfficial** [comment]
@JUSTIVE Can you share a screen recording where the issue occurs? Converting SVGs works reliably for me, so I need more context to see what's going wrong.

**Comment by JUSTIVE** [comment]
https://github.com/raycast/extensions/assets/7118300/921c5e4b-11d4-4e12-acff-81830482689a

here's a screen record, simply selecting svg from finder, and tried to convert to webp.

**Comment by JUSTIVE** [comment]
maybe I'm outdated. is there any way to force-update an extension?

**Comment by JUSTIVE** [comment]
figured out how to update extensions. Now I'm up to date, but having still same issue.
