### ISSUE TITLE
[PHP Monitor] Command Switch PHP Version fails

### ISSUE THREAD

**Issue by dsturm** [raycast/extensions#980]
# Extension – [PHP Monitor](https://github.com/raycast/extensions/tree/f7d865341baadc8422e2990627fdec0ad8e196fc/extensions/phpmon/)
Author: @nicoverbruggen

## Description

Trying to use the `Switch PHP Version` Command fails and shows a "Something went wrong" error.

It seems, that the used path for `php-config` is wrong.

```sh
which php-config                      
/usr/local/bin/php-config
```

## Error:
```
Error: Command failed: /opt/homebrew/bin/php-config --version
/bin/sh: /opt/homebrew/bin/php-config: No such file or directory


/bin/sh: /opt/homebrew/bin/php-config: No such file or directory

checkExecSyncError:node:child_process:826:11
execSync:node:child_process:900:15
p:switch.js:1:970
wl:react-reconciler.production.min.js:5:19052
Wi:react-reconciler.production.min.js:9:6962
ji:react-reconciler.production.min.js:9:940
Jo:react-reconciler.production.min.js:9:871
Ut:react-reconciler.production.min.js:9:728
Jl:react-reconciler.production.min.js:7:12492
react-reconciler.production.min.js:5:4358
```

## Steps To Reproduce

1. Open raycast and type to get the `Switch PHP Version` Command
2. Open command

## The current behavior

Command throws an error.

## The expected behavior

The command lists the current and available PHP versions, so you can switch to another.

### Raycast version
Version: 1.29.0

**Comment by dsturm** [comment]
Ok, looks like I'm to slow - this is now a duplicate of #979

**Comment by mathieudutour** [comment]
Going to close this in favour of #979 then
