### ISSUE TITLE
[Set Audio Device] ...Airplay Toggle

### ISSUE THREAD

**Issue by shibanib** [raycast/extensions#9804]
http://www.raycast.com/benvp/audio-device

### Extension

http://www.raycast.com/benvp/audio-device

### Description

Can't list airplay devices in output device options unless they manually connected in the control panel first , disappears when disconnected 

### Steps To Reproduce

1. Configure extension
2. Set display airplay devices toggle on
3. Go to set Audio Output on raycast

### Current Behaviour

No devices show up in the list when the toggle is on

### Expected Behaviour

all devices possible including airplay devices should show up in the list

**Comment by alanhg** [comment]
> I'm also experiencing this
> 
> The best I can diagnose is the `audio-device list --output --json` command just doesn't list the airplay device, but it does once manually connected.

it's @spotxyz/macos-audio-devices issue.

**Comment by pointbreakd** [comment]
Still not working
