### ISSUE TITLE
Toggle Audio Input (microphone)

### ISSUE THREAD

**Issue by rulesolutions** [raycast/extensions#9808]
### Extension

https://www.raycast.com/Quentin23Soleil/mute-microphone

### Description

Not able to mute the microphone for Facetime audio calls

### Steps To Reproduce

1. Toggle the extension to mute the microphone
2. make a Facetime audio call to anyone
3. The user on the other end can hear everything even though the extension reports that it has muted the microphone.

**Comment by iamyeizi** [comment]
@raycastbot close this issue
