### ISSUE TITLE
[Buildkite] Unblock Pipeline

### ISSUE THREAD

**Issue by bennnym** [raycast/extensions#9809]
### Extension

https://www.raycast.com/mskelton/buildkite

### Description

Currently the status of a pipeline does not show as "Pending" or "Blocked" or whatever the official status is when it is requiring to be unblocked for the next stage eg to `prod`.

It would be awesome to be able to unblock a step from raycast without having to navigate to the browser.

### Who will benefit from this feature?

everyone!!

### Anything else?

some context of how easy this should be 

https://forum.buildkite.community/t/unblocked-step-with-api-call/1006/2

**Comment by mskelton** [comment]
@bennnym I don't use Buildkite actively anymore at my current role, so supporting the extension is a bit of a challenge now given my lack of access to real pipelines that I can test with. Happy to help guide you through what it would take to add this feature, but I'll need a bit of help.

**Comment by bennnym** [comment]
Thanks @mskelton, I would need quite a bit of help seeing i am a python dev, but let me see how far I can get on my own. Appreciate the response !
