### ISSUE TITLE
[Google Bard] - The extension won't connect to my __Secure-1PSID

### ISSUE THREAD

**Issue by Alekyuk** [raycast/extensions#9814]
### Extension

http://www.raycast.com/EvanZhouDev/raycast-bard-ai

### Description

Hi there !

I have a little problem with this extension : no matter how much I try, the __Secure-1PSID won't work and the extension keeps saying that it can't connect to Bard ...

### Steps To Reproduce

1. add the  __Secure-1PSID
2. Launch the Raycast extension
3. Wait a few seconds

**Comment by JMeisterDesign** [comment]
I'm experiencing the same issue with this extension found here - https://www.raycast.com/EvanZhouDev/raycast-bard-ai

The cookie it asks you to copy does not allow for connection to the BardAI.
