### ISSUE TITLE
[Meme Generator] Preview text on image before submiting

### ISSUE THREAD

**Issue by Martin-Gonzalez90** [raycast/extensions#9818]
### Extension

https://www.raycast.com/timoransky/meme-generator

### Description

I don't know if it's possible but it would be very nice to preview the text over the image. This could be in two ways:
1. while you are writing
2. after you submit the form, see it a preview and the copy it.

### Who will benefit from this feature?

Better feedback of how the text fit in the image

**Comment by timoransky** [comment]
Hi @Martin-Gonzalez90 and thank you for the request. You are not the first asking for this feature but I believe it was not implemented in the first place because of API limitations. Let me see what I can do and maybe I'll consider adding the preview after generating the image.

**Comment by timoransky** [comment]
Hey @Martin-Gonzalez90! It's long overdue, but I finally found the time to implement the preview feature. It's on a PR currently: https://github.com/raycast/extensions/pull/14224

**Comment by timoransky** [comment]
@raycastbot reopen this issue

**Comment by timoransky** [comment]
The preview feature was implemented in the latest version: https://www.raycast.com/timoransky/meme-generator

**Comment by timoransky** [comment]
@raycastbot close this issue
