### ISSUE TITLE
[Tana] Request failed with status code 400

### ISSUE THREAD

**Issue by isaquepereira** [raycast/extensions#9823]
### Extension

https://www.raycast.com/cheslip/tana

### Description

I've added my API token, but when I try to use the quick add command I got this error.

### Steps To Reproduce

Run "Quick Add" command
Write something
Submit

### Expected Behaviour

Submit to my Tana space.

**Comment by cheslip** [comment]
Hi @isaquepereira - this will be resolved with #9495 where the extension moves to using workspace API tokens. Until that gets merged, you can try re-generating the API token.
