### ISSUE TITLE
[Arc] Cannot use custom search engine

### ISSUE THREAD

**Issue by bachrc** [raycast/extensions#9833]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

In the extension settings, we are able to select the Search Engine from a list of 4 choices. Google, Bing ,Ecosia, Duckduckgo. Though, we are not able to select a custom one, not even the "default arc search engine", which for me is Kagi.

Could it be possible to, at least, use the default search engine?

### Who will benefit from this feature?

People who use a different search engine from the 4 listed engines

**Comment by thomaslombart** [comment]
Fixed as Kagi is now supported.
