### ISSUE TITLE
[Change Case] ... Allow to paste when Used with Quicklink

### ISSUE THREAD

**Issue by reuhno** [raycast/extensions#9834]
### Extension

https://www.raycast.com/erics118/change-case

### Description

When you create a Quicklink to apply a text transform, the changed text goes to the clipboard but does not paste on its own, regardless of the value of the "Primary Action" option.

The productivity gain would be enormous if it were possible to have an auto paste with the quicklink

**Comment by erics118** [comment]
Should the fix be to just respect the value of the `Primary Action` preference?
