### ISSUE TITLE
Add Additional Toggle

### ISSUE THREAD

**Issue by itsfatal** [raycast/extensions#9837]
### Extension

https://www.raycast.com/iamyeizi/toggle-menu-bar

### Description

A toggle for never <-> full screen only would be a great addition. I’m constantly toggling this when watching video or productivity work in full screen apps. 

### Who will benefit from this feature?

All users of the extensions.

**Comment by iamyeizi** [comment]
soon 🤠

**Comment by itsfatal** [comment]
@iamyeizi i really hope we have the same definition of soon 😅

**Comment by iamyeizi** [comment]
very soon 👀

![CleanShot 2024-01-31 at 2  01 53](https://github.com/raycast/extensions/assets/37552350/b68487ed-f321-46d3-9f59-453832c571a5)

**Comment by itsfatal** [comment]
Literally perfect

**Comment by iamyeizi** [comment]
@raycastbot close this issue

**Comment by nileane** [comment]
I just tried the updated extension, but it doesn't seem to work properly.
The setting does change in System Settings but it doesn't take effect. Is that expected? Is there a way to force the setting update?

If I change the menu bar visibility setting from System Settings, it's fine. But if I change it from your extension, macOS doesn't seem to be aware of the change.

**Comment by itsfatal** [comment]
@nileane it works perfect for me. Are you sure you have the automation enabled? 
<img width="844" alt="SCR-20240202-lyxn" src="https://github.com/raycast/extensions/assets/14064875/f4549052-24c3-44ea-b696-66dbabaeb263">

**Comment by nileane** [comment]
Yep, it's enabled
![System Settings - 2024-02-02 à 19 24@2x](https://github.com/raycast/extensions/assets/914451/7855cc05-e74f-47ac-a3e7-78f0a351db38)

Your extension does work.
But I have to re-open an app before I put it in fullscreen for it to take the updated setting into account.

**Comment by itsfatal** [comment]
It's actually @iamyeizi 's app, perhaps he can help here

**Comment by iamyeizi** [comment]
Hi @nileane 👋🏽, that, I need to find out more about what else macOS does when applying the drop down options of "Automatically hide and show menu bar", the setting when changing it from Control Center I know it throws a trigger to the UI to refresh, I need to find out if it is possible to do this and if it is possible to do it through an app like Raycast.

As I only use `Always` > `Full Screen Only`, I don't have this problem.

I have to inform that momentarily it's necessary to make the change with the command before opening the app to put in full screen or if the command is applied afterwards, it's necessary to reopen the app, if using `Never` or `On Desktop Only`.
