### ISSUE TITLE
Auto delete

### ISSUE THREAD

**Issue by itsfatal** [raycast/extensions#9838]
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

Having the extension auto delete the texts would be awesome. 

### Who will benefit from this feature?

All users who want it to function as similar as possible to Apples implementation

**Comment by ronaldheft** [comment]
I'm not sure this is possible at the moment.

The extension reads texts from the Messages sqllite db, which is an unofficially supported method of interacting with Apple Messages. While we could in theory delete them from the database, they wouldn't sync to other iCloud devices.
