### ISSUE TITLE
[TickTick] Show due time when searching tasks

### ISSUE THREAD

**Issue by Yakitrak** [raycast/extensions#9841]
### Extension

https://www.raycast.com/appest/ticktick

### Description

Using the search tasks command (and other commands), shows the tasks with due dates but no time. It would be beneficial to add this information as it is already returned by TIckTick.

### Who will benefit from this feature?

Any user who would like to see the due date / time.

**Comment by Yakitrak** [comment]
Made a PR for this https://github.com/raycast/extensions/pull/9913

**Comment by Yakitrak** [comment]
> It looks great to display task date with time but is missing all day and floating time format logic

Thank you for taking a look! I have updated the PR to correctly handle all day tasks, floating time and time zones. Please let me know if it looks okay or if I missed anything.

Also if possible please reply on the PR so the requested changes are easier to follow.

**Comment by viduycheung** [comment]
@raycastbot close this issue
