### ISSUE TITLE
[Figma File Search] Support passing context

### ISSUE THREAD

**Issue by Scvairy** [raycast/extensions#9852]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

As mentioned in this video https://youtu.be/LyacFwVDr8o?si=pNFbz2Ns1d08O35P&t=135 there is a feature to pass context to extension. I'd like to use a quicklink to quickly search file in figma via hotkey

### Who will benefit from this feature?

Everyone, who uses quicklinks with Figma extension

**Comment by michaelwschultz** [comment]
Thanks for the suggestion @Scvairy. I just put up a PR for this. Should land soon.
