### ISSUE TITLE
[AirPods Noise Control] does not work on my setup

### ISSUE THREAD

**Issue by Kikangh** [raycast/extensions#9854]
### Extension

http://www.raycast.com/chrahe/airpods-noise-control

### Description

Hi,
MacOS Sonoma 14.2.1 (23C71)
Airpods Pro
French language

I did the extension setup but it does not change the sound setting. I fear this is maybe because I am using french as system language ? Here is a screenshot of my "Sound" Menubar item :
<img width="301" alt="image" src="https://github.com/raycast/extensions/assets/15923375/0999dcc3-2528-487d-9e7e-c17e3c30a72f">
 

### Steps To Reproduce

Use the extension to toggle switch noise control mode

### Current Behaviour

Noise control mode does not change

### Expected Behaviour

Noise control should change when using the extension

**Comment by Kikangh** [comment]
> We could not find the extension related to this issue. Please update the issue with the link to the extension.

https://github.com/raycast/extensions/tree/0efeec51772b3062dd1ec80379f0983b641b7e80/extensions/airpods-noise-control

**Comment by iamyeizi** [comment]
@Kikangh check if now works

**Comment by Kikangh** [comment]
It works !
Just tested with my AirPods Pro and my AirPods Pro Max.

Thanks !

Le 7 févr. 2024 à 18:14, iamyeizi ***@***.***> a écrit :


@Kikangh <https://github.com/Kikangh> check if now works
