### ISSUE TITLE
[Figma File Search] Add option to switch to Figma Beta

### ISSUE THREAD

**Issue by stackingsaunter** [raycast/extensions#9874]
### Extension

https://www.raycast.com/michaelschultz/figma-files-raycast-extension

### Description

I use Figma Beta and can't use the extension, as it currently opens only Figma. Would be cool to be able to set in options a switch for it to open Figma Beta.

**Comment by michaelwschultz** [comment]
This should be an easy add. I'll look into it. Thanks for the suggestion.

**Comment by maxvoltar** [comment]
+1 and subscribe 🙂

**Comment by michaelwschultz** [comment]
Tim! Haha it's been years. I'll make it happen.

**Comment by stackingsaunter** [comment]
Yes, please, allow for Figma internal build too 😏

**Comment by michaelwschultz** [comment]
@maxvoltar @stackingsaunter no problem. Do one of you mind getting me the app bundle identifier? You can find it by right clicking on the app and going to "Show Package Contents" > contents > info.plist

For example, here is the identifier for the beta app.

<img width="525" alt="Screenshot 2024-02-17 at 8 05 18 PM" src="https://github.com/raycast/extensions/assets/57668/8eb422ac-ccae-40a4-b396-0a4056426bfe">

**Comment by stackingsaunter** [comment]
@michaelwschultz I don't have access to internal build, just would love to :P
