### ISSUE TITLE
[Pomodoro] Clock is not updating until you click 

### ISSUE THREAD

**Issue by larionovaleksandr** [raycast/extensions#9877]
### Extension

http://www.raycast.com/asubbotin/pomodoro

### Description

I initiated a 25-minute cycle, and the time remains fixed at 25:00 until I click on it, at which point it updates to display the current time.

Rec: https://share.cleanshot.com/CqzXlWYd

### Steps To Reproduce

1. Start timer 
2. Wait few secs 
3. Click on it and time will be updated 

### Current Behaviour

Time is not being updated

### Expected Behaviour

Time updates in real time

**Comment by larionovaleksandr** [comment]
https://github.com/raycast/extensions/issues/9877

**Comment by ShutoAraki** [comment]
I have the same issue on macOS Sonoma 14.2.1

**Comment by khomaldi** [comment]
same. Sonoma 14.2.1 (23C71)
