### ISSUE TITLE
(Splitwise) 404 error when adding expenses

### ISSUE THREAD

**Issue by Necromancer94** [raycast/extensions#9880]
### Description

I've connected splitwise to my raycast following the instructions. I can see and navigate through my expenses just fine but when I try to add a new expenses, it always leads to a 404 error.

Could you kindly advise? Thanks!

### Current Behaviour

404 error when trying to add a new expense via Raycast

**Comment by djpowers** [comment]
Came here to see if this was reported, I'm experiencing the same issue. Of note, the "List Expenses" command appears to work and is pulling in new data, but I get the same "Couldn't add Expense! Request failed with status code 404" error.

**Comment by djpowers** [comment]
Ah, I was confused because I didn't see the `/parse_sentence` endpoint in the [Splitwise API expense docs](https://dev.splitwise.com/#tag/expenses), but it looks like that endpoint has since been removed: splitwise/api-docs#72

It appears this will need to be updated to use the `/create_expense` endpoint, and either use another solution for natural language parsing, or instead update the form to use the JSON fields specified in the docs.

**Comment by mathieudutour** [comment]
Let's open another issue, no? Seems like the original one was fixed, and now the fix should be improved - or am I misunderstanding?

**Comment by maximilianzuern** [comment]
No. The PR fixed the creation of group expenses but **not** the creation of non-group expenses.

**Comment by djpowers** [comment]
Technically the "404 error" this issue reported was resolved by the most recent PR. Handling the non-group scenario is a new issue that now needs to be addressed that I'd say warrants a separate issue that could link to this one and the PR.

**Comment by maximilianzuern** [comment]
Opened another issue #10033

**Comment by Necromancer94** [comment]
Hey everyone. Thanks a lot for picking up so quickly, and sorry for my rather late reply.

Here's what I can see from my end:

-The "natural language processing" option was replaced by a small pop up form which in my opinion is even better, however I get a 400 error  every time I'm trying to add an expense, so the issue is not really gone for me.

Could someone please check?

Much appreciated

**Comment by djpowers** [comment]
@Necromancer94 see the new issue opened in the previous comment.
