### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by macaussie** [raycast/extensions#9884]
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

Is it possible to have compatibilty with the sites of yt-dl?

https://ytb-dl.github.io/ytb-dl/supportedsites.html

### Who will benefit from this feature?

all

**Comment by vimtor** [comment]
I'm sorry, but the extension is not using `ytb-dl` directly. Instead, it uses a [JavaScript wrapper](https://github.com/fent/node-ytdl-core) specifically designed for YouTube. This means that we would have to rewrite the extension from scratch.

![youtube-downloader 2023-12-30 at 18 02 12](https://github.com/raycast/extensions/assets/36263538/876f6301-f595-4dac-a879-af716b8978cf)

However, this may be a good idea for another extension!

@raycastbot close this issue
