### ISSUE TITLE
[Tana] ...

### ISSUE THREAD

**Issue by palseb** [raycast/extensions#9890]
### Extension

https://www.raycast.com/cheslip/tana

### Description

Cannot add a quick add note in Tana, even if I inserted a Tana Token.  Here is the message I get. 'Request failed with status code 400'
Thanks,  Pierre

### Steps To Reproduce

Tana app and Raycast app

### Current Behaviour

Cannot add a quick add note in Tana, even if I inserted a Tana Token.  Here is the message I get. 'Request failed with status code 400'
Thanks,  Pierre

### Expected Behaviour

Should get a quick add note in Tana

**Comment by cheslip** [comment]
hi @palseb - this will be resolved with #9495 where the extension moves to using workspace API tokens. Until that gets merged, you can try re-generating the API token.
