### ISSUE TITLE
[Associated Press] nothing displays?

### ISSUE THREAD

**Issue by barryfishman** [raycast/extensions#9893]
### Extension

http://www.raycast.com/Dammmien/associated-press

### Description

When using the AP Raycast extension... nothing displays? This used to work for me, so I'm not sure what happened. I tried uninstalling and reinstalling the extension, but that didn't help. Any ideas?

### Steps To Reproduce

1. Using Raycast 1.64.4 and AP extension 
2. Type "AP" to invoke extenion

### Current Behaviour

Nothing displays except a folder icon with a magnifying glass saying "No Results"

### Expected Behaviour

A list of AP news headlines!

**Comment by barryfishman** [comment]
extensions/associated-press
#3457

**Comment by xilopaint** [comment]
@raycastbot reopen this issue

@Dammmien Can this extension be fixed or should it be removed from the Store? I can't find any information about the API.

cc @pernielsentikaer

**Comment by xilopaint** [comment]
@raycastbot reopen this issue

**Comment by xilopaint** [comment]
@Dammmien Can this extension be fixed or should it be removed from the Store? I can't find any information about the API.

cc @pernielsentikaer

**Comment by pernielsentikaer** [comment]
We're looking into a way to handle the deprecation in the best way, always sad to let extensions go 😢
