### ISSUE TITLE
[Midjourney] Not finding application folder or token ID

### ISSUE THREAD

**Issue by jmabeebiz** [raycast/extensions#9898]
### Extension

https://www.raycast.com/carter/midjourney

### Description

I've tried multiple browsers including Chrome, but I'm unable to find my Discord token ID or the application folder as outlined in the instructions. Has something changed? 
![CleanShot 2023-12-28 at 10 15 44](https://github.com/raycast/extensions/assets/74937547/cd90ccb6-36aa-451d-86f2-61d8b4a925ad)

### Steps To Reproduce

I cannot even get through to the extension because I need a token ID which I cannot find.

**Comment by CarterMcAlister** [comment]
@jmabeebiz try this guide, the token ID should be in your discord request headers
https://www.geeksforgeeks.org/how-to-get-discord-token/
