### ISSUE TITLE
[Bitwarden Vault] Vault Timeout upon Screen Lock instead of time period

### ISSUE THREAD

**Issue by neumannjan** [raycast/extensions#9934]
### Extension

http://www.raycast.com/jomifepe/bitwarden

### Description

It would be nice if the bitwarden vault could lock not after a timeout, but instead upon locking my Mac screen, like the official Bitwarden app itself can do.

The reason for this is that having to retype the master password often is quite impractical (especially since #8075 is not resolved). However, turning off the timeout also seems to be not sufficiently secure.

### Who will benefit from this feature?

Probably everyone who uses the extension

**Comment by neumannjan** [comment]
> We could not find the extension related to this issue. Please update the issue with the link to the extension.

????? the link is literally right there

**Comment by jomifepe** [comment]
Hey, thanks for the suggestion. This is something I'm already investigating, but haven't found a way to do it, due to the nature of raycast extensions. I described the progress in this issue: https://github.com/jomifepe/extensions/issues/14#issuecomment-1595729940

**Comment by jomifepe** [comment]
Just released two experimental "On system lock" and "On system sleep" timeout options. Give it a try 🙂
