### ISSUE TITLE
[Discord Timestamps] Date Picker Results Dissapear After a Few Seconds

### ISSUE THREAD

**Issue by y-u-s-u-f** [raycast/extensions#9942]
### Extension

https://www.raycast.com/theshadowdev/discord-timestamps

### Description

https://dropover.cloud/7d5d66

When I open the date picker and type a date, the results appear and dissapear in a second ("no results found")

### Steps To Reproduce

1. Open the extension
2. Open set date from input
3. Type the date
4. Wait a few seconds

**Comment by thewilloftheshadow** [comment]
Hey @YufusKhan 
We're using Raycast's native Date Picker there, so this would be an issue with Raycast itself, not the Discord Timestamps extension (You can see that here: https://github.com/raycast/extensions/blob/main/extensions/discord-timestamps/src/timestamp.tsx#L70-L89)

The Apple Reminders extension also uses this same Date Picker, does it happen there as well?
http://www.raycast.com/raycast/apple-reminders

**Comment by YufusKhan** [comment]
No, it doesn't happen on the Apple Reminders extension.

**Comment by thewilloftheshadow** [comment]
@y-u-s-u-f Are you having this issue now on the latest Raycast update?

**Comment by y-u-s-u-f** [comment]
Yup

**Comment by thewilloftheshadow** [comment]
I'm still not able to reproduce this across two different devices, so open an issue on the main Raycast bout the date picker component bugging out then
