### ISSUE TITLE
"Add to Library" command doesn't work [Music] ...

### ISSUE THREAD

**Issue by klkvsky** [raycast/extensions#9950]
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

The "Add to Library" command doesn't work, even though it shows a success toast. 
However, the "Favorite and Add to Library" command works as expected.

### Steps To Reproduce

1. Open the Music app.
2. Play any track that is not in your library.
3. Run the command.

### Current Behaviour

Doesn't add to the library.

### Expected Behaviour

Should add to the library

**Comment by klkvsky** [comment]
@pernielsentikaer help 🥹. The link is correct, and I don't know why the bot decided it's wrong

**Comment by LEUNGHOTIN** [comment]
I guess the format of your issue title is wrong. [Music] should be placed first in the title.

> @pernielsentikaer help 🥹. The link is correct, and I don't know why the bot decided it's wrong
