### ISSUE TITLE
"visual-studio-code-recent-projects" need an option to filter the results.

### ISSUE THREAD

**Issue by fhyoga** [raycast/extensions#997]
# Extension – [visual-studio-code-recent-projects](https://github.com/raycast/extensions/tree/main/extensions/visual-studio-code-recent-projects)

Author: @thomaspaulmann 

**Describe the feature and the current behavior/state.**

Requires an option to filter the results.
For example, a project limited to a few folders is a valid result. Because this scheme now causes any temporary directory to be opened will be displayed in the search results, which affects the accuracy too much.

The initial idea is to provide a configuration that allows users to configure multiple folders, and the search results are limited to the first-level directories of these folders.
A reference is https://github.com/vivaxy/alfred-open-in-vscode where wds configuration is provided
> Set workflow environment wds to your project base folders. e.g. wds: /Users/vivaxy/Developers/*. Workflow searches only first level folders, so make sure wds point to them. wds stands for working directories.

Of course, I just provided an idea. The specific plan can be discussed together. After the plan is confirmed, I can contribute this PR

**Who will benefit from this feature?**
Developers using VScode

**Any Other info.**

**Comment by thomaspaulmann** [comment]
I checked hte alfred workflow. It works slightly different by showing workspaces based on the directory that you provide. My extension reads the recently opened projects and files. May I ask why you have many temporary directories that you open? Doesn't simple filtering work for you in this case? 

Adding a filter mechanism isn't hard, just want to make sure that we're doing it for the correct reasons.
