### ISSUE TITLE
[Toothpick] Device Support Form

### ISSUE THREAD

**Issue by yannickbrouwer** [raycast/extensions#9976]
### Extension

https://www.raycast.com/VladCuciureanu/toothpick

### Description

<b>Device brand and model</b>
Sony WH-1000 XM4

<b>Device data</b>
{"device_address":"AC:80:0A:98:FD:77","device_firmwareVersion":"2.5.2","device_minorType":"Headset","device_productID":"0x0D58","device_services":"0x800019 < HFP AVRCP A2DP ACL >","device_vendorID":"0x054C","device_connected":"true"}

**Comment by VladCuciureanu** [comment]
Hey! Thanks for submitting the device support form. Sadly this device is already mapped inside the extension. Are you having any issues? (Maybe icon not showing up?)

**Comment by VladCuciureanu** [comment]
@raycastbot close this issue
