### ISSUE TITLE
[Bitwarden] Can't log in to bitwarden

### ISSUE THREAD

**Issue by andrhevictor** [raycast/extensions#9977]
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Can't login to bitwarden using the extension, it shows an error message `Please check your API Key and Secret`. When I use the `copy last error` command it says `Traffic from your network looks unusual. Connect to a different network or try again. [Error Code 2`

- Already triple-checked the credentials.
- Rotated new API keys and secrets
- I can log in using the CLI
- I can log in using the web vault
- I can log in using the browser extension

### Steps To Reproduce

1. Try to search vault
2. Fail to login

**Comment by jomifepe** [comment]
Hello, thanks for reporting. This is the first time I've seen this error, and as I don't have enough information to diagnose it, I recommend the following:
- Try reinstalling the extension. Maybe update the CLI if that doesn't work.
- Follow this help guide, which has a couple of other things to try: https://bitwarden.com/help/unusual-traffic-error/

**Comment by andrhevictor** [comment]
It randomly started working again 🤷‍♂️ Thanks for taking a look @jomifepe!
