### ISSUE TITLE
[Tailscale] ...Switch Account commands fails

### ISSUE THREAD

**Issue by pti-cjones** [raycast/extensions#9980]
### Extension

https://www.raycast.com/tailscale/tailscale

#### Error:
```
Error: Could not communicate with command worker


```

### Steps To Reproduce

1. macOS 14.2.1 using latest version of Raycast
2. Running Tailscale version 1.56.1
3. I have two Tailscale accounts (personal and a business account)
4. When using the Tailscale extension and trying to use the "Switch Accounts" command, it just says "Something went wrong"

### Current Behaviour

Get a messaage in Raycast that something went wrong

### Expected Behaviour

I haven't used this extension before but I would expect it would provide a list of accounts to change to and then select the account that I want to switch to.

**Comment by samlinville** [comment]
A fix is being developed in https://github.com/raycast/extensions/pull/9917#issuecomment-1873629103
