### ISSUE TITLE
[Easy Dictionary] Search Word command should open a new session for each search

### ISSUE THREAD

**Issue by wybert** [raycast/extensions#9983]
### Extension

https://www.raycast.com/isfeng/easydict

### Description

1. I have been using the Search Word command to translate or find specific words. However, I have noticed that when I use this function again after a few seconds, it does not search for the new words I have selected. Instead, it shows the previous text I had selected. This is causing some inconvenience for me.
2. While the default behavior may be helpful for users who want to recheck the same translation after a while, it does not suit my needs. It would be great if we could have the following features:
    1. A history function that can save the latest 10 searches, so I can easily access them again.(optional)
    2. An option to start a new session every time I search for selected texts, instead of showing the previous selection.
<img width="737" alt="image" src="https://github.com/raycast/extensions/assets/5254627/1c6bf167-ef26-4580-bfd3-91e0e9dd1eb4">
I hope these suggestions can be implemented to improve the functionality of the Search Word command. Thank you for your help!

**Comment by wybert** [comment]
@tisfeng

**Comment by tisfeng** [comment]
This is a feature or bug of Raycast https://github.com/raycast/extensions/issues/9350 , you should give them feedback about it 😥

**Comment by tisfeng** [comment]
@raycastbot close this issue
