### ISSUE TITLE
[Arc] 'Search Arc' command is opening completely incorrect links

### ISSUE THREAD

**Issue by GeorgeeNico** [raycast/extensions#9993]
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

Quite frequently, I have noticed that when I try to open a specific pinned tab using the 'Search Arc' command, a completely different tab is opened instead. Example:
![Screenshot 2024-01-04 at 14 33 03 2@2x](https://github.com/raycast/extensions/assets/42051158/03472e3c-024c-45ba-aa19-c7f7dd9837e4)
![Screenshot 2024-01-04 at 14 33 42](https://github.com/raycast/extensions/assets/42051158/7aa196ed-c96f-4ada-91be-5a23b95af802)

It's happened quite a few times, with very different results / different tabs openning.

### Steps To Reproduce

1. Select pinned tab
2. open tab
3. sometimes it will open an incorrect tab

**Comment by thomaslombart** [comment]
Hey @GeorgeeNico, are you still having this issue? @loris made a fix over [here](https://github.com/raycast/extensions/pull/10017).

**Comment by GeorgeeNico** [comment]
This issue has been fixed, I am no longer experiencing the extension opening incorrect links. 

I am however experiencing an issue opening any link at all when Arc is open in the background. I will open another ticket related to this.
