### ISSUE TITLE
[Bunch] ... add close action for a bunch found with search

### ISSUE THREAD

**Issue by sleifer** [raycast/extensions#9996]
### Extension

https://www.raycast.com/koinzhang/bunch

### Description

I'd like to be able to close a single Bunch. Adding a close action (next to open action) for a bunch found with search would allow this

### Who will benefit from this feature?

Users of Bunch who allow multiple bunches open at once and both open and close various bunches

**Comment by koinzhang** [comment]
@sleifer Currently the Search Bunches command can shut down a single running bunch, provided the bunch is running.
<img width="761" alt="image" src="https://github.com/raycast/extensions/assets/36128970/b1d9b22d-a4ca-49db-8457-e72b0756256b">

**Comment by sleifer** [comment]
Makes sense. I had ended up with a use style for Bunch where I don't have bunches marked running.
